### PR TITLE
Fixing blank screen when Store Details task clicked on sectioned task list

### LINKED ISSUE #32705: [GlobalStep] "Blank screen" displayed after clicking "Add store details" on "Woocommerce > Home" page.
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

"Blank screen" displayed after clicking "Add store details" on "Woocommerce > Home" page.

### Expected behavior

Store Details should be properly displayed after clicking "Add store details" on "Woocommerce > Home" page.

### Actual behavior

"Blank screen" displayed after clicking "Add store details" on "Woocommerce > Home" page.

### Steps to reproduce

1. Create any test site using JN site.
2. Install and activate WooCommerce 6.5.0-beta.1.
3. Install and activate the latest WooCommerce Test Helper plugin
4. Navigate to Tools > WCA Test Helper > Experiments and toggle woocommerce_tasklist_setup_experiment_2_2022_* to treatment.
5. Go to WooCommerce > Home.
6. Click "Add store details".
7. Observe that "Blank screen" displayed after clicking "Add store details" on "Woocommerce > Home" page.

### Instruction Link:
https://github.com/woocommerce/woocommerce/wiki/Release-Testing-Instructions-WooCommerce-6.5#sectioned-task-list-experiment-32302

### Video:

https://user-images.githubusercontent.com/41110392/164258663-a38d5be2-e81c-41ce-85d7-076eded00fbb.mp4

### WordPress Environment

Environment:
Woocommerce Version: 
WooCommerce: 6.5.0-beta.1
Wordpress version: 5.9.3

PC:
Windows 10
Chrome(Version 100.0.4896.127) 
Firefox(Version 99.0.1)

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

<details>

`
### WordPress Environment ###

WC Version: 6.5.0
REST API Version: ✔ 6.5.0
WC Blocks Version: ✔ 7.4.1
Action Scheduler Version: ✔ 3.4.0
Log Directory Writable: ✔
WP Version: 5.9.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.53 (Unix) OpenSSL/1.0.2g
PHP Version: 7.4.28
PHP Post Max Size: 1 GB
PHP Time Limit: 30
PHP Max Input Vars: 5000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.7.33-0ubuntu0.16.04.1-log
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 6.5.0
WC Database Prefix: wp_
Total Database Size: 4.79MB
Database Data Size: 3.32MB
Database Index Size: 1.47MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 2.42MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_posts: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 1
page: 7
post: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (5) ###

Query Monitor: by John Blackbourn – 3.9.0
Companion Plugin: by Osk – 1.24
WooCommerce Admin Test Helper: by WooCommerce – 0.7.1
WooCommerce Beta Tester: by WooCommerce – 2.0.5
WooCommerce: by Automattic – 6.5.0-beta.1

### Inactive Plugins (3) ###

Akismet Anti-Spam: by Automattic – 4.2.2
Hello Dolly: by Matt Mullenweg – 1.7.2
Jetpack: by Automattic – 10.8

### Dropin Plugins (1) ###

db.php: Query Monitor Database Class (Drop-in)

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: –

### WC Pages ###

Shop base: #6 - /shop/
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty-Two
Version: 1.1
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 4
Oldest: 2022-04-20 13:15:31 +0000
Newest: 2022-04-20 13:49:09 +0000

### Status report information ###

Generated at: 2022-04-20 14:51:28 +00:00
`

</details>

### PR DESCRIPTION
**Pull request by joelclimbsthings**
### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

There was a bug with the sectioned version of the task list (_tasklist_setup_experiment_2_) that didn't support tasks that need to follow an `actionUrl` parameter instead of directing to a slotfill. This resulted in a blank screen when the "Store Details" task was clicked on.

Closes #32705 .

### How to test the changes in this Pull Request:

1. Checkout this branch on fresh site.
2. Don't complete OBW, but ensure marketing is enabled (you can complete the just first step of the OBW to do this)
3. Install and activate the latest WooCommerce Test Helper plugin
4. Navigate to Tools > WCA Test Helper > Experiments and toggle `woocommerce_tasklist_setup_experiment_2_2022_*` to treatment.
5. Go back to Homescreen (ensure page refresh)
6. You should see the sectioned task list
7. Click on "Store Details" step. 
8. It should correctly direct you to the Onboarding Wizard.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully run tests with your changes locally?
* [ ] Have you created a changelog file by running `pnpm nx affected --target=changelog`?

### FOR PR REVIEWER ONLY:

* [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

File: plugins/woocommerce-admin/client/two-column-tasks/task-list.tsx [hunk 1]
```diff
@@ -202,7 +202,7 @@ export const TaskList: React.FC< TaskListProps > = ( {
 		}
 		if ( task.actionUrl ) {
 			if ( task.actionUrl.startsWith( 'http' ) ) {
-				window.location.href = actionUrl;
+				window.location.href = task.actionUrl;
```
Comment (joelclimbsthings) [inline plugins/woocommerce-admin/client/two-column-tasks/task-list.tsx:205]: This also looked like it was a 🐞  waiting to happen.

File: plugins/woocommerce-admin/client/two-column-tasks/sectioned-task-list.tsx [hunk 2]
```diff
@@ -127,13 +131,18 @@ export const SectionedTaskList: React.FC< TaskListProps > = ( {
 		} );
 	};
 
-	const goToTask = ( task: TaskType ) => {
+	const onTaskSelected = ( task: TaskType ) => {
 		trackClick( task );
-		updateQueryString( { task: task.id } );
-	};
+		if ( task.actionUrl ) {
```
Comment (joelclimbsthings) [inline plugins/woocommerce-admin/client/two-column-tasks/sectioned-task-list.tsx:136]: This was the missing logic, just mimicked what was done in the two column task list.

**Review by louwie17 — APPROVED** [review]
LGTM 🚀 Tested well and changes look good, thanks for the fix @joelclimbsthings
