### PR TITLE
Single Product Block: Add missing allowed inner blocks to fix nesting placement restrictions

### LINKED ISSUE #45528: Single Product Block: Restricting Inner Blocks Placement
### Describe the bug

The Single Product block in the editor restricts certain inner blocks from being directly nested within itself. These blocks can only be placed inside the nested "Columns" block. This limitation reduces editing flexibility.

This issue was spotted by @jarekmorawski (ref: p1710240548226409-slack-C02FL3X7KR6)

### Expected behavior

All blocks allowed within the "Columns" block should also be directly insertable as child blocks of the Single Product block. This allows for a more streamlined editing experience and greater control over product page layout.

### Actual behavior

Currently, a defined list of allowed inner blocks restricts which blocks can be directly nested within the Single Product block. Blocks not included in this list can only be added as children of the inner "Columns" block.

### Steps to reproduce

1. Navigate to Single Product template (Appearance > Editor > Templates).
2. Click on "Edit" to open the WordPress editor.
3. In the editor, you should see a block inserter icon or an option to "Add Block". Click on it.
4. Search for "Single Product" in the block inserter or browse the available blocks until you find them. Add it to your content.
5. Move all blocks from the Columns > Column blocks to be directly nested within the Single Product block. Check that you can do it successfully for some blocks but not others.

### PR DESCRIPTION
**Pull request by thealexandrelara**
### Changes proposed in this Pull Request:

Closes #45528 .

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

Test scenario 1: Single Product Template

1. Navigate to Single Product template (Appearance > Editor > Templates).
2. Click on "Edit" to open the WordPress editor.
3. In the editor, you should see a block inserter icon or an option to "Add Block". Click on it.
4. Search for "Single Product" in the block inserter or browse the available blocks until you find them. Add it to your content.
5. Move all blocks from the Columns > Column blocks to be directly nested within the Single Product block. 
6. Make sure you can move all blocks to be directly nested within the Single Product block.
7. Save the template and visit a product page to make sure everything is working as expected.

Test scenario 2: Post

1. Add a new post (Posts > Add new).
2. In the editor, you should see a block inserter icon or an option to "Add Block". Click on it.
3. Search for "Single Product" in the block inserter or browse the available blocks until you find them. Add it to your content.
4. Move all blocks from the Columns > Column blocks to be directly nested within the Single Product block.
5. Make sure you can move all blocks to be directly nested within the Single Product block.
6. Save the post and visit it to make sure everything is working as expected.

Test scenario 3: Page

1. Add a new post (Page > Add new).
2. In the editor, you should see a block inserter icon or an option to "Add Block". Click on it.
3. Search for "Single Product" in the block inserter or browse the available blocks until you find them. Add it to your content.
4. Move all blocks from the Columns > Column blocks to be directly nested within the Single Product block.
5. Make sure you can move all blocks to be directly nested within the Single Product block.
6. Save the page and visit it to make sure everything is working as expected.

#### Before

https://github.com/woocommerce/woocommerce/assets/20469356/10ec6931-c7c9-4fe8-b4c8-edf21361a55a

#### After

https://github.com/woocommerce/woocommerce/assets/20469356/3fb17d00-b01a-444a-b66d-58768ab4c8ab

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 
Fix issue preventing some blocks from being direct children of the Single Product block.

#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce-blocks/assets/js/blocks/single-product/constants.tsx [hunk 1]
```diff
@@ -27,7 +27,7 @@ export const DEFAULT_INNER_BLOCKS: InnerBlockTemplate[] = [
 		[
 			[
 				'core/column',
-				{},
+				{ templateLock: false },
```
Comment (imanish003) [inline plugins/woocommerce-blocks/assets/js/blocks/single-product/constants.tsx]: Nit: Isn't the default value of `templateLock` false? In other words, do we need to define it as false explicitly?

**Review by imanish003 — APPROVED** [review]
Hey @thealexandrelara,
I tested the changes & it's working as expected :shipit:

File: plugins/woocommerce-blocks/assets/js/blocks/single-product/constants.tsx (hunk 1 above)
Comment (thealexandrelara) [reply plugins/woocommerce-blocks/assets/js/blocks/single-product/constants.tsx]: Nice catch! This attribute is unnecessary in this case. Initially, I thought that, for some reason, the `templateLock` was being modified at some point in the code, preventing users from moving the blocks within the Single Product block. With that in mind, I changed the `templateLock` attribute in multiple places to test that theory. Still, when I noticed the allowed inner blocks were causing it, I removed them from almost all areas and forgot this one 😅 .

I just fixed this in c3f3ae673fc263cfa5c58167f8c61eb4fa747afb
