### PR TITLE
Checkout: Fix default customer location and geolocation so only allowed countries get selected

### LINKED ISSUE #51402: Checkout geolocation selects wrong country if it is not in the list of sales locations.
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When geolocation detects the customer's country, but the country is not in the list of sales locations, then it selects the first country in the list. 

### Expected behavior

When the country is not in the sales location then it should not set any country from the list

### Actual behavior

Selects the first country that is on the list

### Steps to reproduce

1. Set Sell to specific countries (e.g. France, Germany)
2. enable MaxMind Geolocation
3. Go to checkout (your geolocation must be different from the one set in Sell for specific countries)

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): http://stg-dagrav2-dev.kinsta.cloud
Site address (URL): http://stg-dagrav2-dev.kinsta.cloud
WC Version: 9.3.1
Legacy REST API Package Version: The Legacy REST API plugin is not installed on this site.
Action Scheduler Version: ✔ 3.8.1
Log Directory Writable: ❌ To allow logging
make /www/dagrav2_309/public/wp-content/uploads/wc-logs/ writable.

WP Version: 6.6.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.25.5
PHP Version: 8.1.29
PHP Post Max Size: 128 MB
PHP Time Limit: 300
PHP Max Input Vars: 10000
cURL Version: 7.68.0
OpenSSL/1.1.1f

SUHOSIN Installed: –
MySQL Version: 10.11.8-MariaDB-ubu2004
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 9.3.1
WC Database Prefix: wp_
Total Database Size: 5.23MB
Database Data Size: 3.51MB
Database Index Size: 1.72MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 2.45MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_posts: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 1
page: 7
post: 2
product: 1
revision: 1
shop_order_placehold: 2
wp_navigation: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 9.3.1

### Inactive Plugins (2) ###

Akismet Anti-spam: Spam Protection: by Automattic - Anti-spam Team – 5.3.3
Hello Dolly: by Matt Mullenweg – 1.7.2

### Must Use Plugins (1) ###

Kinsta Must-use Plugins: by Kinsta Team – 3.1.1

### Settings ###

Legacy API Enabled: –
Force SSL: –
Currency: PLN (zł)
Currency Position: right_space
Thousand Separator: 
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 0 B

### WC Pages ###

Shop base: #7 - /shop/
Cart: #8 - /cart/ -  Contains the woocommerce/cart block
Checkout: #9 - /checkout/ -  Contains the woocommerce/checkout block
My account: #10 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty-Four
Version: 1.2
Author URL: https://wordpress.org
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ❌ Not declared

### Templates ###

Overrides: /www/dagrav2_309/public/wp-content/plugins/woocommerce/templates/block-notices/error.php
/www/dagrav2_309/public/wp-content/plugins/woocommerce/templates/block-notices/notice.php
/www/dagrav2_309/public/wp-content/plugins/woocommerce/templates/block-notices/success.php

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
pattern-toolkit-full-composability
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
printful
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page
launch-your-store

Disabled Features: experimental-blocks
minified-js
product-pre-publish-modal
settings
async-product-editor-category-field
product-editor-template-system
blueprint
reactify-classic-payments-settings

Daily Cron: ✔ Next scheduled: 2024-09-16 11:39:44 +00:00
Options: ✔
Notes: 55
Onboarding: completed

### Action Scheduler ###

Complete: 8
Oldest: 2024-09-15 11:41:38 +0000
Newest: 2024-09-15 11:55:54 +0000

Failed: 1
Oldest: 2024-09-15 11:52:00 +0000
Newest: 2024-09-15 11:52:00 +0000

Pending: 1
Oldest: 2024-09-16 11:41:38 +0000
Newest: 2024-09-16 11:41:38 +0000

### Status report information ###

Generated at: 2024-09-15 12:11:06 +00:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by mikejolley**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Refactor default location logic so that the default country is definitely allowed. This means if it geo-locates to a non-allowed country, the country will be the base country instead of selecting the first country in the dropdown.

Closes #51402

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

To test this you either need to have setup MaxMind under WC > Settings > Integrations, or you can force a value with a small function:

```php
add_filter(
	'woocommerce_geolocate_ip',
	function ( $geolocation ) {
		return 'FR';
	},
	10
);
```

1. Implement snippet above.
2. WC > Settings > Set store address to the UK
3. WC > Settings > Selling Locations. Sell to all countries except France.
4. WC > Settings > Default customer location set to geolocate
5. Go to checkout in a new browser session as a guest. 
6. Confirm UK is selected by default
7. WC > Settings > Default customer location set to "no address"
8. Go to checkout in a new browser session as a guest. 
9. Confirm no country is selected

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce/includes/wc-core-functions.php [hunk 1]
```diff
@@ -1306,6 +1306,50 @@ function wc_get_base_location() {
...
+ * @return array
+ */
+function wc_get_customer_geolocation( $fallback = array(
+	'country' => '',
+	'state'   => '',
+) ) {
+	$ua = wc_get_user_agent();
+
+	// Exclude common bots from geolocation by user agent.
+	if ( stristr( $ua, 'bot' ) || stristr( $ua, 'spider' ) || stristr( $ua, 'crawl' ) ) {
```
Comment (wavvves) [inline plugins/woocommerce/includes/wc-core-functions.php]: ~~By "common bots" is the case-sensitive check deliberate? I see some examples [here](https://github.com/monperrus/crawler-user-agents/blob/master/crawler-user-agents.json) for "Bot". 
Can we use stristr() or stripos()?~~ Misread the code as `strstr()` 🙄

Nevertheless I think `stripos() !== false` might be faster, there's a note on it on the [PHP Manuel](https://www.php.net/manual/en/function.strstr.php) (`str_contains()` is PHP 8 only I believe)

Comment (wavvves) [reply plugins/woocommerce/includes/wc-core-functions.php]: PHP Manuel 🇲🇽 😂

File: plugins/woocommerce/includes/wc-core-functions.php [hunk 2]
```diff
@@ -1306,6 +1306,50 @@ function wc_get_base_location() {
...
+	$geolocation = WC_Geolocation::geolocate_ip( '', true, false );
+
+	if ( empty( $geolocation['country'] ) ) {
+		return $fallback;
+	}
+
+	// Ensure geolocation is valid.
+	$allowed_countries = WC()->countries->get_allowed_countries();
+
+	if ( ! in_array( $geolocation['country'], array_keys( $allowed_countries ), true ) ) {
```
Comment (wavvves) [inline plugins/woocommerce/includes/wc-core-functions.php]: Something made me feel weird reading this line... since arrays keys are case sensitive, isn't this the same as:
`if ( ! isset( $allowed_countries[ $geolocation['country'] ] ) ) {...}`
(But with the overhead of creating another array in memory through `array_keys()`)

File: plugins/woocommerce/includes/wc-core-functions.php [hunk 3]
```diff
@@ -1306,6 +1306,50 @@ function wc_get_base_location() {
...
+		return $fallback;
+	}
+
+	$allowed_states = WC()->countries->get_allowed_country_states();
+	$country_states = $allowed_states[ $geolocation['country'] ] ?? array();
+
+	if ( $country_states && ! in_array( $geolocation['state'], array_keys( $country_states ), true ) ) {
```
Comment (wavvves) [inline plugins/woocommerce/includes/wc-core-functions.php]: Maybe same as comment above?

**Review by wavvves — APPROVED** [review]
Thanks Mike, testing steps check out ok 👍🏼 
Approved, but I left some minor nitpicks 🙂

File: plugins/woocommerce/includes/wc-core-functions.php (hunk 1 above)
Comment (mikejolley) [reply plugins/woocommerce/includes/wc-core-functions.php]: Yeah this is case insensitive. I will try but don't want to break it; this is old code.

File: plugins/woocommerce/includes/wc-core-functions.php (hunk 2 above)
Comment (mikejolley) [reply plugins/woocommerce/includes/wc-core-functions.php]: GPT agrees
