### PR TITLE
Experimental iAPI Mini Cart: Enable SSR

### LINKED ISSUE #58926: Interactivity API powered Mini Cart - error on template hydration
There is a hydration error in the current code that we need to investigate. According to @sam.seay, it only happens with the version of the Interactivity API of WordPress Core and not with the new runtime.

### LINKED ISSUE #59018: Interactivity API powered Mini Cart - Minicart count should work server-side
## What?

Right now, the item count number shown close to the minicart icon seems to work only in the client. This can cause an unnecessary shift.

https://github.com/user-attachments/assets/38ea315f-3dc0-47ab-b9a1-3897db4788b0

## Steps to reproduce

> To test the experimental block, make sure `experimental-iapi-mini-cart` and `experimental-iapi-runtime` are set to `true` in the `development.json` file: [link](https://github.com/woocommerce/woocommerce/blob/c9cc094885a0351dd2cb550a5739f5980e0a5e6c/plugins/woocommerce/client/admin/config/development.json#L8-L9).

1. Ensure the setting to show the count is on.
2. Refresh the page and check the number is rendered only in the client. (You can directly disabled JS or change the speed in the Network tab)

### PR DESCRIPTION
**Pull request by luisherranz**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Activate server-side rendering by adding `supports.interactivity` to `block.json`.

It also corrects an issue with `data-wp-bind--class` that was not populating the class attribute correctly on the server due to lack of state initialization.

Closes #59018, #58926.

### How to test the changes in this Pull Request:

1. Add products to the cart.
2. Refresh the page and view the page source.
3. Look for the badge span (`class="wc-block-mini-cart__badge"`); it should be populated with the correct value.
4. Look for the cart items table `template` (`class="wc-block-cart-items wc-block-mini-cart-items"`). After the `template`, the table should be populated with the correct HTML.

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

Enable SSR on the experimental iAPI Mini Cart.

</details>

### CODE REVIEW

**Review by SantosGuillamot — COMMENTED** [review]
Thanks for working on this, Luis! I've looked at this in more detail and, while the iAPI SSR seems to be fixed, [this issue](https://github.com/woocommerce/woocommerce/issues/59018) where the item count doesn't show without JS is still there.

After checking the code, it looks there is some JS changing the styles, which is causing this behaviour. This is the file handling it: [link](https://github.com/woocommerce/woocommerce/blob/17387ec18dce96e4ab506cbac11075c2834b565f/plugins/woocommerce/client/blocks/assets/js/blocks/mini-cart/utils/set-styles.ts#L46-L50). And this is where it is called in the `iapi-frontend` file: [link](https://github.com/woocommerce/woocommerce/blob/17387ec18dce96e4ab506cbac11075c2834b565f/plugins/woocommerce/client/blocks/assets/js/blocks/mini-cart/iapi-frontend.ts#L40-L42).

Should we work on migrating that into the iAPI as well?

File: plugins/woocommerce/src/Blocks/BlockTypes/MiniCart.php [hunk 1]
```diff
@@ -483,9 +483,10 @@ protected function render_experimental_iapi_mini_cart( $attributes, $content, $b
 			wp_interactivity_state(
 				$this->get_full_block_name(),
 				array(
-					'totalItemsInCart'  => $cart_item_count,
-					'badgeIsVisible'    => $badge_is_visible,
-					'formattedSubtotal' => $formatted_subtotal,
+					'totalItemsInCart'     => $cart_item_count,
+					'badgeIsVisible'       => $badge_is_visible,
+					'formattedSubtotal'    => $formatted_subtotal,
+					'drawerOverlayClass'   => 'wc-block-components-drawer__screen-overlay wc-block-components-drawer__screen-overlay--with-slide-out wc-block-components-drawer__screen-overlay--is-hidden',
```
Comment (SantosGuillamot) [inline plugins/woocommerce/src/Blocks/BlockTypes/MiniCart.php]: Taking a look at the [derived state of this property](https://github.com/woocommerce/woocommerce/blob/17387ec18dce96e4ab506cbac11075c2834b565f/plugins/woocommerce/client/blocks/assets/js/blocks/mini-cart/iapi-frontend.ts#L108-L117), it looks like not all classes are dynamic.

Out of curiosity, did we consider having something like this and remove that prop:

```php
data-wp-class--wc-block-components-drawer__screen-overlay--with-slide-in="context.isOpen"
data-wp-class--wc-block-components-drawer__screen-overlay--is-hidden="!context.isOpen"
```

Comment (luisherranz) [reply plugins/woocommerce/src/Blocks/BlockTypes/MiniCart.php]: Yes, here:

- https://github.com/woocommerce/woocommerce/pull/58265#discussion_r2113568370

@samueljseay said he would do it in a follow-up, but it would be good to open an issue so we don't forget.

**Comment by luisherranz** [comment]
> Should we work on migrating that into the iAPI as well?

At some point, yes. Although I'd say move it to Editor settings, following how the Navigation block handles it.

It's documented here:

- https://github.com/woocommerce/woocommerce/issues/58518

@SantosGuillamot, could you confirm that the behavior you're seeing matches how things worked in the old Minicart, so we don't need to include this fix among those required for the block to be ready?

File: plugins/woocommerce/client/blocks/assets/js/blocks/mini-cart/mini-cart-contents/inner-blocks/empty-mini-cart-contents-block/block.json [hunk 2]
```diff
@@ -10,7 +10,10 @@
 		"multiple": false,
 		"reusable": false,
 		"inserter": false,
-		"lock": false
+		"lock": false,
+		"interactivity": {
+			"clientNavigation": true
+		}
```
Comment (SantosGuillamot) [inline plugins/woocommerce/client/blocks/assets/js/blocks/mini-cart/mini-cart-contents/inner-blocks/empty-mini-cart-contents-block/block.json]: This block includes directives: [link](https://github.com/woocommerce/woocommerce/blob/17387ec18dce96e4ab506cbac11075c2834b565f/plugins/woocommerce/src/Blocks/BlockTypes/EmptyMiniCartContentsBlock.php#L45-L48). Should this be just `interactivity: true`?

File: plugins/woocommerce/client/blocks/assets/js/blocks/mini-cart/mini-cart-contents/inner-blocks/filled-mini-cart-contents-block/block.json [hunk 3]
```diff
@@ -10,7 +10,10 @@
 		"multiple": false,
 		"reusable": false,
 		"inserter": false,
-		"lock": false
+		"lock": false,
+		"interactivity": {
+			"clientNavigation": true
+		}
```
Comment (SantosGuillamot) [inline plugins/woocommerce/client/blocks/assets/js/blocks/mini-cart/mini-cart-contents/inner-blocks/filled-mini-cart-contents-block/block.json]: This block contains directives as well: [link](https://github.com/woocommerce/woocommerce/blob/17387ec18dce96e4ab506cbac11075c2834b565f/plugins/woocommerce/src/Blocks/BlockTypes/FilledMiniCartContentsBlock.php#L44). Should this also be `interactivity: true`?

**Review by SantosGuillamot — APPROVED** [review]
> @SantosGuillamot, could you confirm that the behavior you're seeing matches how things worked in the old Minicart, so we don't need to include this fix among those required for the block to be ready?

Yes, the old Minicart uses the same CSS and JS, so it faces the same issue. I hadn't seen the open ticket, sorry. Thanks for sharing.

I'm approving because everything seems to work as expected. I just left a couple of comments where I'm not sure if we should use `interactivity: true`.

File: plugins/woocommerce/src/Blocks/BlockTypes/MiniCart.php (hunk 1 above)
Comment (SantosGuillamot) [reply plugins/woocommerce/src/Blocks/BlockTypes/MiniCart.php]: I've opened an issue [here](https://github.com/woocommerce/woocommerce/issues/59146). Feel free to add more context if needed.

I can work on a PR once this one is merged to avoid conflicts.

File: plugins/woocommerce/client/blocks/assets/js/blocks/mini-cart/mini-cart-contents/inner-blocks/empty-mini-cart-contents-block/block.json (hunk 2 above)
Comment (luisherranz) [reply plugins/woocommerce/client/blocks/assets/js/blocks/mini-cart/mini-cart-contents/inner-blocks/empty-mini-cart-contents-block/block.json]: Yes. I assumed those two blocks were simple wrappers. Thanks for the catch.

Fixed in https://github.com/woocommerce/woocommerce/pull/59115/commits/a1d9ae4cbfa4e816004e12721235e94a29b64de4.

File: plugins/woocommerce/client/blocks/assets/js/blocks/mini-cart/mini-cart-contents/inner-blocks/filled-mini-cart-contents-block/block.json (hunk 3 above)
Comment (luisherranz) [reply plugins/woocommerce/client/blocks/assets/js/blocks/mini-cart/mini-cart-contents/inner-blocks/filled-mini-cart-contents-block/block.json]: Fixed in https://github.com/woocommerce/woocommerce/pull/59115/commits/a1d9ae4cbfa4e816004e12721235e94a29b64de4.

**Comment by luisherranz** [comment]
Thanks Mario!

File: plugins/woocommerce/src/Blocks/BlockTypes/MiniCart.php (hunk 1 above)
Comment (luisherranz) [reply plugins/woocommerce/src/Blocks/BlockTypes/MiniCart.php]: Thanks Mario.

**Comment by luisherranz** [comment]
I'm reviewing a failure in an end-to-end test that seems related to the mini-cart. However, since the end-to-end tests are running without the new experimental mini-cart, it shouldn't be failing. Also, I'm not able to reproduce this issue locally, so I'm not sure what's going on.

I'm going to revert all the changes in this PR to see if I can pinpoint the exact change that's causing the PR to fail. But in theory, the changes introduced in this PR only affect the `render` function of the new experimental mini-cart for a couple of PHP blocks, which shouldn't impact the end-to-end tests of the previous mini-cart; and updates to the `block.json` files to add `supports.interactivity`, which also shouldn't affect how the previous mini-cart works.

**Comment by luisherranz** [comment]
This is the change that makes the React-based MiniCart e2e tests to fail: https://github.com/woocommerce/woocommerce/pull/59115/commits/e70b766b57df2dd8fa90d183e8ecd650083d37dc

The tests that fail are:
- `tests/e2e/tests/templates/template-customization.block_theme_with_templates.spec.ts:32:8 › Template customization › Mini-Cart template › theme template has priority over WooCommerce's and can be modified`
- `tests/e2e/tests/templates/template-customization.block_theme.spec.ts:143:7 › Template customization › user-modified "Mini-Cart" template based on the theme template has priority over the user-modified template based on the default WooCommerce template`

The change is simply to activate the server-side rendering of the Interactivity API in the Mini Cart blocks using `supports.interactivity = true` in the `block.json`.

**Comment by luisherranz** [comment]
The tests that are failing in this PR are not failing in the [run e2e tests against experimental iapi mini cart](https://github.com/woocommerce/woocommerce/pull/59138) PR, so it might not be a priority to address this issue right now, since it will resolve itself. However, it would be good to identify what is modifying the server-side rendering in order to prevent these tests from failing in the future.

So we can just join this with the upcoming PR that makes the experimental iAPI mini cart the default one.

**Comment by luisherranz** [comment]
Since in the end we are going to maintain both versions for at least one WooCommerce release, let's see if we can solve the problem of that end-to-end test to get the server-side rendering working correctly.

**Comment by luisherranz** [comment]
Thanks for fixing the end-to-end test, David! ❤️
