### PR TITLE
Fix - 23913, Delete product query transients when removing terms via …

### LINKED ISSUE #23913: wp_remove_object_terms() does not delete product query transients
**Describe the bug**
Removing terms via `wp_remove_object_terms()` does not result in `WC_Post_Data::delete_product_query_transients()` being called. This seems to be caused by `WC_Post_Data::delete_product_query_transients()` only being hooked to `set_object_terms`, which is only applicable for `wp_set_object_terms()` and its wrappers.

The `set_object_terms` hook is setup here: https://github.com/woocommerce/woocommerce/blob/9eca72849dba6c3c491e5822dee7a3b47c8bead4/includes/class-wc-post-data.php#L32.

I'm not at all familiar with the WooCommerce source code, but the simplest solution that I can see is to also hook into `deleted_term_relationships`.

**To Reproduce**
1. Remove a product category via `wp_remove_object_terms()`
2. View the category's archive
3. The loop will contain the product until the 'product_query' transient expires

**Screenshots**

**Expected behavior**
I'd expect the product query transients to be deleted.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

### PR DESCRIPTION
**Pull request by aslamshekh**
#23913  I have delete product query transients when removing terms via wp_remove_object_terms() 
### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

Closes #23913 .

Please review from your side and let me know if there is anything.

### CODE REVIEW

File: includes/class-wc-post-data.php [hunk 1]
```diff
@@ -30,6 +30,7 @@ public static function init() {
 		add_action( 'shutdown', array( __CLASS__, 'do_deferred_product_sync' ), 10 );
 		add_action( 'set_object_terms', array( __CLASS__, 'force_default_term' ), 10, 5 );
 		add_action( 'set_object_terms', array( __CLASS__, 'delete_product_query_transients' ) );
+		add_action( 'delete_term_relationships', array( __CLASS__, 'delete_product_query_transients' ) );
```
Comment (vedanshujain) [inline includes/class-wc-post-data.php]: this should be hooked to `deleted_term_relationships` instead. can you please change this and update. thanks

**Review by vedanshujain — CHANGES_REQUESTED** [review]

**Review by vedanshujain — APPROVED** [review]
LGTM! Thanks.
