### PR TITLE
CYS: Fix auto scroll when a new block is added

### LINKED ISSUE #50371: CYS: Automatic Scrolling to Added Pattern Not Functioning
In WooCommerce 9.2, adding a pattern would automatically scroll to the newly added pattern. This functionality is no longer working in the current trunk version. We need to investigate the cause and restore this behavior.

| WooCommerce 9.2 | Trunk |
|--------|--------|
| <video src="https://github.com/user-attachments/assets/a9f6cbed-bbff-48ff-a140-aea3f9c24707" />  | <video src="https://github.com/user-attachments/assets/88984c66-d455-4960-820a-0d913e16ed92" />

### PR DESCRIPTION
**Pull request by gigitux**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes #50371.

This PR adds an E2E tests to catch future regression.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Head over to WooCommerce > Home > Customize your store.
2. Follow the flow.
3. Click on Design your Homepage.
4. Add multiple patterns
5. Ensure that the browser always scrolls to the last added pattern.

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [x] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

CYS: Fix auto scroll when a new block is added.

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce-admin/client/customize-store/assembler-hub/hooks/auto-block-preview-event-listener.ts [hunk 1]
```diff
@@ -175,9 +175,10 @@ const addInertToAssemblerPatterns = (
 const addInertToAllInnerBlocks = ( documentElement: HTMLElement ) => {
 	const body = documentElement.ownerDocument.body;
 	const observerChildList = new window.MutationObserver( () => {
-		const parentBlocks = body.getElementsByClassName(
-			'block-editor-block-list__layout'
-		)[ 0 ].children;
+		const parentBlocks =
+			body.getElementsByClassName(
+				'block-editor-block-list__layout'
+			)[ 0 ]?.children ?? [];
```
Comment (gigitux) [inline plugins/woocommerce-admin/client/customize-store/assembler-hub/hooks/auto-block-preview-event-listener.ts:181]: This change is not related to this PR, but I noticed that in some cases, the browser threw an error because `body.getElementsByClassName('block-editor-block-list__layout')[ 0 ]` returned `undefined`

**Comment by tjcafferkey** [comment]
Thanks @gigitux. Just two things from me.

Can we add the following options to the `scrollIntoView()` function to avoid the user getting disorientated:

```js
block.scrollIntoView( {
	block: 'end',
	behavior: 'smooth',
} );
```

What do you think about renaming the export from `use-insert-pattern` from `blockToScroll` to `insertedPattern` since we may need a reference to it in future for things other than scrolling. We can maintain its variable name during the export.

`const { insertPattern, insertedPattern: blockToScroll } = useInsertPattern();`

**Review by albarin — APPROVED** [review]
Nice! Working great! 🙌

**Comment by gigitux** [comment]
Thanks for the review, folks!

@tjcafferkey, I implemented the feedback! Can you take a look? Thanks!

**Review by tjcafferkey — APPROVED** [review]
