### PR TITLE
Logging: Fix pagination and filtering on DB log list table

### LINKED ISSUE #39359: Pagination issue if WC_LOG_HANDLER is defined as WC_Log_Handler_DB and log filters are set
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When using the WooCommerce plugin with the `WC_LOG_HANDLER` defined as `WC_Log_Handler_DB`, a pagination issue has been identified. The problem occurs when attempting to access logs with filters set through the WooCommerce admin interface. The pagination navigation seems to malfunction, preventing users from navigating through multiple pages of logs for set filters properly.

### Expected behavior

The pagination controls should allow users to navigate through multiple pages of logs for any filters set and view logs recorded beyond the first page without any errors or issues.

### Actual behavior

The pagination controls do not work as expected when filters are set. Clicking on page numbers or the "Next" and "Previous" links does not load the corresponding logs from the database. Instead, the page navigates to the next/previous page of entire log, making it impossible to access logs recorded beyond the initial page for any filter.

### Steps to reproduce

1. Install and activate the WooCommerce plugin on a WordPress website.
2. Define the WC_LOG_HANDLER constant as WC_Log_Handler_DB in the website's wp-config.php.
3. Generate a substantial amount of logs, with a variety of levels, either through test orders or any other means.
4. Navigate to the WooCommerce admin dashboard.
5. Click on "WooCommerce" in the left sidebar and select "Status".
6. Under the "Logs" tab, select a level and filter.
7. Note that the logs are not filtered and the URL in the address bar does not change.

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): http://localhost/
Site address (URL): http://localhost/
WC Version: 7.9.0
REST API Version: ✔ 7.9.0
WC Blocks Version: ✔ 10.4.6
Action Scheduler Version: ✔ 3.6.1
Log Directory Writable: ✔
WP Version: 6.2.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Microsoft-IIS/10.0
PHP Version: 8.1.21
PHP Post Max Size: 64 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.77.0
OpenSSL/1.1.1t

SUHOSIN Installed: –
MySQL Version: 10.5.18-MariaDB-log
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.9.0
WC Database Prefix: wp_
Total Database Size: 4.84MB
Database Data Size: 3.11MB
Database Index Size: 1.73MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 2.03MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.09MB + Index: 0.06MB + Engine InnoDB
wp_posts: Data: 0.05MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 19
page: 7
post: 2
product: 25

### Security ###

Secure connection (HTTPS): ❌
Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 7.9.0

### Settings ###

API Enabled: –
Force SSL: –
Currency: INR (₹)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### WC Pages ###

Shop base: #6 - /shop/
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 4.4.1
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
product-variation-management
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2023-07-21 11:44:16 +05:30
Options: ✔
Notes: 27
Onboarding: skipped

### Action Scheduler ###

Complete: 6
Oldest: 2023-07-07 13:11:18 +0000
Newest: 2023-07-20 13:57:52 +0000

Failed: 2
Oldest: 2022-11-18 10:01:32 +0000
Newest: 2022-11-18 10:03:13 +0000

Pending: 1
Oldest: 2023-07-21 13:57:52 +0000
Newest: 2023-07-21 13:57:52 +0000

### Status report information ###

Generated at: 2023-07-21 15:42:23 +05:30
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by coreymckrill**
### Changes proposed in this Pull Request:

This fixes some long-standing issues (and also some maybe introduced by recent work on the file handler) where pagination and filters were not persisting in the DB log list table view after running a bulk action. Furthermore, there was not a way to customize the number of log entries shown per page.

Fixes #39359

#### Setup

1. In your test site's **wp-config.php** file, add this line: `define( 'WC_LOG_HANDLER', 'WC_Log_Handler_DB' );`. This is what enables the DB log list table view.
2. Install [this plugin](https://gist.github.com/coreymckrill/2968911c8b63c556e7787f2cdc65f966) on your test site for generating test log files. Probably easiest to copy the file into the mu-plugins directory.
3. Open two browser tabs: the Logs screen (WP Admin > WooCommerce > Status > Logs) and the WooCommerce Tools screen (WP Admin > WooCommerce > Status > Tools). On the Tools screen you should see the **Debug Log Generator** tool at the top of the list.

#### Tests

1. On the Tools screen, run the Debug Log Generator tool several times (should generate about 10 entries each time) so that you have at least 30 entries.
2. On the Logs screen, you should see the list table with all the log entries. The list table UI should include page navigation, and tell you how many total log entries there are. Try navigating to another page of log entries.
3. Up at the top of the screen is a "Screen Options" tab. Click on this and change the "Number of items per page" setting to a low number like 5, and click "Apply". This should reload the screen and now the list table should show fewer entries, but have more pages available.
4. While on a subsequent page (e.g. Page 2), check the box next to one or more entries, click the Bulk Actions dropdown, select "Delete", and click "Apply". The entries you selected should go away, but you should still be on the same page you were on before.
5. Now click on the "All sources" dropdown and select a log source, then click "Filter". The list table should now only show you log entries from that particular source.
6. While the list table is still filtered, try using the Bulk delete action again. After the entries have been deleted, you should still be seeing the filtered list table view.
7. At the bottom of the list table is a button labeled "Flush all logs". Click it! You should get a confirmation dialog. If you click "Cancel", nothing should happen. If you click "Ok", all log entries should be deleted, and the list table should now be empty.

### CODE REVIEW

File: plugins/woocommerce/includes/admin/class-wc-admin-status.php [hunk 1]
```diff
@@ -306,20 +314,38 @@ public static function remove_log() {
...
+
+		if ( ! current_user_can( 'manage_woocommerce' ) ) {
+			wp_die( esc_html__( 'You do not have permission to manage log entries.', 'woocommerce' ) );
 		}
 
 		WC_Log_Handler_DB::flush();
 
-		wp_safe_redirect( esc_url_raw( admin_url( 'admin.php?page=wc-status&tab=logs' ) ) );
-		exit();
+		$sendback = remove_query_arg( array( 'action', 'action2', 'flush-logs', '_wpnonce', '_wp_http_referer' ), wp_get_referer() );
```
Comment (jorgeatorres) [inline plugins/woocommerce/includes/admin/class-wc-admin-status.php]: I might be missing something, but I think the original redirect was correct. When flushing all logs, what's the point of sending the user back to a filtered view that might no longer work? We probably do want to remove _all_ query args in this particular case.

File: plugins/woocommerce/includes/admin/class-wc-admin-status.php [hunk 2]
```diff
@@ -328,15 +354,29 @@ private static function flush_db_logs() {
...
-		if ( empty( $_REQUEST['_wpnonce'] ) || ! wp_verify_nonce( $_REQUEST['_wpnonce'], 'woocommerce-status-logs' ) ) { // WPCS: input var ok, sanitization ok.
-			wp_die( esc_html__( 'Action failed. Please refresh the page and retry.', 'woocommerce' ) );
+		check_admin_referer( 'bulk-logs' );
+
+		if ( ! current_user_can( 'manage_woocommerce' ) ) {
+			wp_die( esc_html__( 'You do not have permission to manage log entries.', 'woocommerce' ) );
 		}
 
-		$log_ids = array_map( 'absint', (array) isset( $_REQUEST['log'] ) ? wp_unslash( $_REQUEST['log'] ) : array() ); // WPCS: input var ok, sanitization ok.
+		$log_ids = filter_input(
```
Comment (jorgeatorres) [inline plugins/woocommerce/includes/admin/class-wc-admin-status.php]: There's nothing wrong with this, but just curious: any reason to use `filter_input()` instead of the original code (which could be made even shorter with `??`)? It seems to me they are almost<sup>*</sup> equivalent but IMHO `filter_input` is a bit harder to grok.

<sup>*</sup> It wouldn't make much difference under normal circumstances, but the original code forced `log_ids` to be an array, while the new version doesn't. I understand this is also checked in `WC_Log_Handler_DB::delete()` and the log checkboxes are actually `log[]` but if we're already validating/sanitizing, we might as well go all the way.

File: plugins/woocommerce/includes/admin/class-wc-admin-status.php [hunk 3]
```diff
@@ -328,15 +354,29 @@ private static function flush_db_logs() {
...
+			INPUT_GET,
+			'log',
+			FILTER_CALLBACK,
+			array(
+				'options' => fn( $log ) => absint( $log ),
```
Comment (jorgeatorres) [inline plugins/woocommerce/includes/admin/class-wc-admin-status.php]: If we do keep the `filter_input` I think this could just be `'options' => 'absint'`

**Review by jorgeatorres — CHANGES_REQUESTED** [review]
Hi @coreymckrill!

Thanks for working on this. Tested well.
I left some feedback re a couple of (minor) things I noticed, but nothing too serious.

Please let me know what you think.

File: plugins/woocommerce/includes/admin/class-wc-admin-status.php (hunk 1 above)
Comment (coreymckrill) [reply plugins/woocommerce/includes/admin/class-wc-admin-status.php]: Good point! Changed in cb7a07c5234ab8935be81102cf9293ce09280036

File: plugins/woocommerce/includes/admin/class-wc-admin-status.php (hunk 2 above)
Comment (coreymckrill) [reply plugins/woocommerce/includes/admin/class-wc-admin-status.php]: 🤔 I guess it's mostly a preference for not accessing the REQUEST global directly, and thus having to have an accompanying linting exception comment. You make some good points though. I simplified this in 26c3ec844c5e3d72847a3c06aa6dfb53efd0f895, so I'm curious if you think it's better.

File: plugins/woocommerce/includes/admin/class-wc-admin-status.php (hunk 3 above)
Comment (coreymckrill) [reply plugins/woocommerce/includes/admin/class-wc-admin-status.php]: See 26c3ec844c5e3d72847a3c06aa6dfb53efd0f895 for a change to this.

**Review by jorgeatorres — APPROVED** [review]
Changes look good @coreymckrill.
I couldn't get one of the CI checks to pass even after a few attempts at re-running. It's unrelated to the changes here, so I'm approving to let you merge once that's taken care of.
