### PR TITLE
Fix fatal error on `WC_Customer_Data_Store_Session`

### LINKED ISSUE #50844: [Fatal] error: Uncaught Error: Call to a member function set() on null
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

The following error was observed post deployment in our logs:

```
PHP Fatal error:  Uncaught Error: Call to a member function set() on null in /wordpress/plugins/woocommerce/9.2.1/includes/data-stores/class-wc-customer-data-store-session.php:114
Stack trace:
#0 /wordpress/plugins/woocommerce/9.2.1/includes/data-stores/class-wc-customer-data-store-session.php(63): WC_Customer_Data_Store_Session->save_to_session(Object(WC_Customer))
#1 /wordpress/plugins/woocommerce/9.2.1/includes/class-wc-data-store.php(186): WC_Customer_Data_Store_Session->create(Object(WC_Customer))
#2 /wordpress/plugins/woocommerce/9.2.1/includes/abstracts/abstract-wc-data.php(241): WC_Data_Store->create(Object(WC_Customer))
#3 /wordpress/core/6.6.1/wp-includes/class-wp-hook.php(324): WC_Data->save('')
#4 /wordpress/core/6.6.1/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)
#5 /wordpress/core/6.6.1/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#6 /wordpress/core/6.6.1/wp-includes/load.php(1280): do_action('shutdown')
#7 [internal function]: shutdown_action_hook()
#8 {main}
  thrown in /wordpress/plugins/woocommerce/9.2.1/includes/data-stores/class-wc-customer-data-store-session.php on line 114
```

It could be possibly due to the session object is not being initialized yet, or somehow session reaches an invalid state.

### Expected behavior

Fatal error shouldn't occur while calling `set` function on the session object.

### Actual behavior

Fatal error occurs.

### Steps to reproduce

There aren't any clear steps to replicate at the moment - To be updated after investigation.

### WordPress Environment

NA

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by albarin**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

This PR checks the `WC()->session` is not null before setting any data to avoid fatal errors.

Closes https://github.com/woocommerce/woocommerce/issues/50844

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

While we couldn't reproduce the fatal error organically, this is a small script to reproduce it and check it's fixed.

1. On `trunk`, add this script to `woocommerce.php`:
```php
add_action(
	'admin_init',
	function () {
		$customer = new WC_Customer();
		$customer->set_email( 'customer@example.com' );

		$session = new WC_Customer_Data_Store_Session();
		$session->save_to_session( $customer );
	}
);
```
2. Go to `/wp-admin` on your store and see that you get the fatal error: `Fatal error: Uncaught Error: Call to a member function set() on null in /plugins/woocommerce/plugins/woocommerce/includes/data-stores/class-wc-customer-data-store-session.php:116`
3. Checkout to this branch PR.
4. Reload the page and see you no longer get the fatal error.

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [x] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 
Avoid fatal error on `WC_Customer_Data_Store_Session`.
</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce/includes/data-stores/class-wc-customer-data-store-session.php [hunk 1]
```diff
@@ -111,7 +111,10 @@ public function save_to_session( $customer ) {
 				$data[ $session_key ] = (string) $session_value;
 			}
 		}
-		WC()->session->set( 'customer', $data );
+
+		if ( WC()->session ) {
+			WC()->session->set( 'customer', $data );
+		}
```
Comment (coreymckrill) [inline plugins/woocommerce/includes/data-stores/class-wc-customer-data-store-session.php]: 🤔 I'm wondering if we should have a "doing it wrong" message or some other warning, rather than having it just fail silently here.

Another thought, would it make sense to bail at the top of the function if the session object is null, rather than doing the data processing (including some potential database calls) first?

Comment (albarin) [reply plugins/woocommerce/includes/data-stores/class-wc-customer-data-store-session.php]: Good suggestions @coreymckrill thanks!
I pushed the changes.

File: plugins/woocommerce/includes/data-stores/class-wc-customer-data-store-session.php [hunk 2]
```diff
@@ -78,6 +78,15 @@ public function update( &$customer ) {
 	 * @param WC_Customer $customer Customer object.
 	 */
 	public function save_to_session( $customer ) {
+		if ( ! WC()->session ) {
+			wc_doing_it_wrong(
+				__METHOD__,
+				__( 'WC_Session is not available, customer data cannot be saved to session.', 'woocommerce' ),
```
Comment (coreymckrill) [inline plugins/woocommerce/includes/data-stores/class-wc-customer-data-store-session.php:84]: The only other suggestion I have would be to hint at _why_ WC_Session isn't available. Based on [this](https://github.com/woocommerce/woocommerce/blob/b5eff69e16c05435ebcb30bd72dffd7864376bce/plugins/woocommerce/includes/wc-core-functions.php#L2638-L2657), I would guess that the `woocommerce_init` hook has to fire first...

**Review by coreymckrill — APPROVED** [review]
👍 Successfully prevents the fatal. One other optional suggestion below, but marking as approved because it's otherwise ready to go.
