### PR TITLE
Fix TS errors in `plugins/woocommerce/client/admin/client/products/`

### LINKED ISSUE #54123: Fix TS errors `plugins/woocommerce/client/admin/client/products/`
Part of https://github.com/woocommerce/woocommerce/issues/53939

### PR DESCRIPTION
**Pull request by kmanijak**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Fix or workaround TS errors in `plugins/woocommerce/client/admin/client/products/`

Closes https://github.com/woocommerce/woocommerce/issues/54123

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

To be tested by developers only!

1. Change in [webpack config](https://github.com/woocommerce/woocommerce/blob/d856cb9f8485a5483f4ac12222c58be40efd224a/plugins/woocommerce/client/admin/package.json#L301C7-L314C5):

```
"DISABLE_TYPESCRIPT_CHECKING": {
					"external": false,
					"default": "false"
				},
				"HIDE_TYPESCRIPT_WARNINGS": {
					"external": false,
					"default": "false"
				}
```

2. Run `pnpm build > ./ts-output.txt`
3. Check the newly created file `ts-output.txt` and search for `./client/products/`
4. Expected: There should be no occurrences 

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce/client/admin/client/products/fills/more-menu-items/classic-editor-menu-item.tsx [hunk 1]
```diff
@@ -30,8 +30,12 @@ export const ClassicEditorMenuItem = ( {
 			select( OPTIONS_STORE_NAME );
 
 		const allowTrackingOption =
+			// Todo: awaiting a more global fix, demo:
+			// https://github.com/woocommerce/woocommerce/pull/54146
 			getOption( ALLOW_TRACKING_OPTION_NAME ) || 'no';
```
Comment (Aljullu) [inline plugins/woocommerce/client/admin/client/products/fills/more-menu-items/classic-editor-menu-item.tsx]: Do you have some more context how this relates to #54146? I'm not sure to understand it. :sweat_smile:

File: plugins/woocommerce/client/admin/client/products/product-page.tsx [hunk 2]
```diff
@@ -71,9 +71,11 @@ export default function ProductPage() {
...
 					<>
 						<WooProductMoreMenuItem>
-							{ ( { onClose }: { onClose: () => void } ) => (
-								<MoreMenuFill onClose={ onClose } />
-							) }
+							{
+								( ( { onClose }: { onClose: () => void } ) => (
+									<MoreMenuFill onClose={ onClose } />
+								) ) as unknown as React.ReactNode
+							}
```
Comment (Aljullu) [inline plugins/woocommerce/client/admin/client/products/product-page.tsx]: I know it wasn't introduced in this PR, but I'm a bit confused by this pattern. :thinking: Why are we defining a function that takes the `onClose` prop simply to pass it down to a component? And the usage of  `as unknown` seems not ideal IMO.

I wonder if this could be refactored to simply:

```suggestion
							<MoreMenuFill />
```

And then make the `onClose` prop in `MoreMenuFill` optional. :thinking:

File: plugins/woocommerce/client/admin/client/products/product-variation-page.tsx [hunk 3]
```diff
@@ -41,15 +41,19 @@ export default function ProductPage() {
...
+									<DeleteVariationMenuItem
+										onClose={ onClose }
+									/>
+									<MoreMenuFill
+										productType="product_variation"
+										onClose={ onClose }
+									/>
+								</>
+							) ) as unknown as React.ReactNode
+						}
```
Comment (Aljullu) [inline plugins/woocommerce/client/admin/client/products/product-variation-page.tsx]: Same. :slightly_smiling_face:

**Review by Aljullu — COMMENTED** [review]
Thanks for working on this, @kmanijak! Overall looking good, I just left a couple of questions for things I'm not sure to understand.

File: plugins/woocommerce/client/admin/client/products/fills/more-menu-items/classic-editor-menu-item.tsx (hunk 1 above)
Comment (kmanijak) [reply plugins/woocommerce/client/admin/client/products/fills/more-menu-items/classic-editor-menu-item.tsx]: Ah yeah, it's about changing the way we register stores from using string to store object. Then, the types are properly propagated. @rjchow is working on that and we agreed to have it fixed globally rather then each area separately.

More context: p1735902356485879-slack-C02FL3X7KR6

File: plugins/woocommerce/client/admin/client/products/product-page.tsx (hunk 2 above)
Comment (kmanijak) [reply plugins/woocommerce/client/admin/client/products/product-page.tsx]: This is a Slot Fill pattern used in multiple places in Woo. I'm not convinced to that either.

> I wonder if this could be refactored to simply:

The internal logic behaves differently when you provide React component vs function returning component. So it should not be the way to go.

> And the usage of as unknown seems not ideal IMO.

But I agree with that 😅 let me try to adjust the internal types to accommodate the case with function returning a component as such.

File: plugins/woocommerce/client/admin/client/products/fills/more-menu-items/classic-editor-menu-item.tsx (hunk 1 above)
Comment (Aljullu) [reply plugins/woocommerce/client/admin/client/products/fills/more-menu-items/classic-editor-menu-item.tsx]: Oooh, ok. I wasn't aware of that combo, thanks!

Btw, sharing with you this thread from another PR where we are disabling these errors: https://github.com/woocommerce/woocommerce/pull/54243#discussion_r1905538395, in case we want to do the same in this PR.

Comment (kmanijak) [reply plugins/woocommerce/client/admin/client/products/fills/more-menu-items/classic-editor-menu-item.tsx]: Thank you for pointing it out! I updated those comments!

Change: https://github.com/woocommerce/woocommerce/pull/54129/commits/be080bca7251ec2e22f52785620bcbc3507c2d4f

File: plugins/woocommerce/client/admin/client/products/product-page.tsx (hunk 2 above)
Comment (kmanijak) [reply plugins/woocommerce/client/admin/client/products/product-page.tsx]: I spent some time investigating it but with no luck. I even consulted this with @gigitux and we cannot figure it out. I added `ts-expect-error` for now in those two cases and if we're ok with that, I'll create a dedicated issue for these two. I know it's not ideal.

Change: https://github.com/woocommerce/woocommerce/pull/54129/commits/70f6ba9293ba4ac8e4a65521e2263e852cc9ad8c

Comment (louwie17) [reply plugins/woocommerce/client/admin/client/products/product-page.tsx]: > Why are we defining a function that takes the onClose prop simply to pass it down to a component? And the usage of as unknown seems not ideal IMO.

Just for some extra context around this. The `WooProductMoreMenuItem` is a wrapper around the Slot/Fill components available within GB. A `Slot` component can take `fillProps`, which can be anything, that is passed down into each `Fill` component. In order to pass it down and adhering to type checking the additional function wrapper is necessary. See the `fillProps` example in the docs here: https://github.com/WordPress/gutenberg/blob/trunk/packages/components/src/slot-fill/README.md#props

Technically we don't even know if `onClose` exists or not, if we wanted to we could enforce the `WooProductMoreMenuItem.Slot` type to take `onClose` as its `fillProps` and in turn also update the `WooProductMoreMenuItem` fill to guarantee that `onClose` exists ( from a type perspective ). But for now I pushed these changes: https://github.com/woocommerce/woocommerce/pull/54312/commits/d32cc4f22dac5020abd92765a0573253d35917ca which makes use of the GB `FillProps` type, which can be anything: https://github.com/WordPress/gutenberg/blob/trunk/packages/components/src/slot-fill/types.ts#L17

Comment (kmanijak) [reply plugins/woocommerce/client/admin/client/products/product-page.tsx]: @louwie17, thank you ❤️ This one and the other similar is fixed in https://github.com/woocommerce/woocommerce/pull/54129/commits/bcd77ab3f81f79d319206f930231bfa7525288f1

File: plugins/woocommerce/client/admin/client/products/product-variation-page.tsx (hunk 3 above)
Comment (kmanijak) [reply plugins/woocommerce/client/admin/client/products/product-variation-page.tsx]: Fixed in https://github.com/woocommerce/woocommerce/commit/bcd77ab3f81f79d319206f930231bfa7525288f1

File: plugins/woocommerce/client/admin/client/products/product-page.tsx (hunk 2 above)
Comment (Aljullu) [reply plugins/woocommerce/client/admin/client/products/product-page.tsx]: Thanks for the explanation, @louwie17! It makes sense.

**Review by Aljullu — APPROVED** [review]
Thanks for the updates and the additional context. LGTM!
