### PR TITLE
Protect against inappropriate use of saved download links

### LINKED ISSUE #32754: Customers can still download products from disabled download directories using their direct download links
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When an admin disables a download URL in the "Approved Download Directories" list, a customer who previously purchased the product would still be able to download the product using the direct download link they saved somewhere, like in one of the confirmation emails we sent them.

Internal discussion: pb22l9-1dC-p2#comment-1239

### Expected behavior

Customer should not be able to download the product anymore using the direct download link.

### Actual behavior

Customer can still download the product using the direct download link they saved somewhere.

### Steps to reproduce

1. Install WC 6.5 (currently in Beta)
3. As a store admin, add a downloadable product by uploading a file to the Media Library.
4. As a customer, purchase the downloadable product and save its direct download link somewhere.
5. As a store admin, go to the "Approved Download Directories" page and disable the two `https://` and `file://` paths (the download URL's of the downloadable product in step 2).
6. As a customer, try to download the product using its direct link they saved earlier.

### WordPress Environment

<details>
### WordPress Environment ###

WC Version: 6.5.0
REST API Version: ✔ 6.5.0
WC Blocks Version: ✔ 7.4.1
Action Scheduler Version: ✔ 3.4.0
Log Directory Writable: ✔
WP Version: 5.9.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.53 (Unix) OpenSSL/1.0.2g
PHP Version: 7.4.29
PHP Post Max Size: 1 GB
PHP Time Limit: 30
PHP Max Input Vars: 5000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.7.33-0ubuntu0.16.04.1-log
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 6.5.0
WC Database Prefix: wp_
Total Database Size: 4.88MB
Database Data Size: 3.44MB
Database Index Size: 1.44MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 2.48MB + Index: 0.03MB + Engine InnoDB
wp_postmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_posts: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wpml_mails: Data: 0.06MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

attachment: 2
page: 7
post: 2
product: 1
shop_order: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (4) ###

Companion Plugin: by Osk – 1.24
Jetpack: by Automattic – 10.8
WooCommerce: by Automattic – 6.5.0-beta.1
WP Mail Logging: by Wysija – 1.10.4

### Inactive Plugins (2) ###

Akismet Anti-Spam: by Automattic – 4.2.2
Hello Dolly: by Matt Mullenweg – 1.7.2

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔

### WC Pages ###

Shop base: #6 - /shop/
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty-Two
Version: 1.1
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 8
Oldest: 2022-04-25 06:35:50 +0000
Newest: 2022-04-25 06:46:39 +0000

### Status report information ###

Generated at: 2022-04-25 06:51:30 +00:00

</details>

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by barryhughes**
When the Approved Download Directories feature is enabled, suppose that:

- A customer purchases a downloadable product containing one or more downloadable files.
- The approved directory rules for one or more of those files are subsequently disabled or deleted.
- On visiting **My Account ▸ Downloads** the customer will no longer be able to access the corresponding downloads 👍🏽 
- However, if they saved the download link or retrieve it from the order confirmation email, it will still be possible for them to access the download 👎🏽 

This change corrects that, by adding an additional check in the download handler.

Closes #32754.

### How to test the changes in this Pull Request:

1. As an administrator, visit **WooCommerce ▸ Settings ▸ Products ▸ Approved Download Directories** and ensure the feature is enabled (you should see a `Stop Enforcing Rules` button if it is enabled ... if you do not, click on the `Start Enforcing Rules` button).
2. Please also visit **WooCommerce ▸ Settings ▸ Products ▸ Product Downloads** and ensure the file download method is "Force Downloads" (this fix does not apply to sites operating in redirect mode).
3. Create a downloadable product and add some downloadable files. In this case, for ease of testing, it probably makes most sense to use real files/URLs.
4. As a customer, purchase the above product. As admin, set the order to "completed".
5. As the customer, visit **My Account ▸ Downloads**. You should see the expected download links, which should function as expected. Capture the download link URLs.
6. As admin, disable one or more approved download directory rules relating to those downloadable files.
7. As customer, you should see that the expected range of downloadable files are no longer present in **My Account ▸ Downloads** (this was already the case, but let's confirm it continues to work as expected).
8. Still acting as customer, try using the download links you captured earlier to by-pass this feature. They should not work (you should instead see an "Invalid download link. [Go to shop](https://example.com/shop/)" error).

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?
* [x] Have you created a changelog file by running `pnpm nx affected --target=changelog`?

- The download handler and some of the classes it calls are not super easy to test; to that end I'm happy to revise the added test if there is a better way.
- ~Newly added test is failing locally (headers-already-sent issue). Keeping this as a draft until I figure that one out.~
- Some PHPCS clean-up is included in this change (but in a separate commit to make it easier to separate out during review). The download handler itself has lots of unaddressed (and unrelated) linting issues, which will be flagged by our automated checks, but they are mostly not of a variety that can be cleaned automatically and so I did not address.

### FOR PR REVIEWER ONLY:

* [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

File: plugins/woocommerce/includes/class-wc-download-handler.php [hunk 1]
```diff
@@ -654,10 +665,12 @@ private static function download_error( $message, $title = '', $status = 404 ) {
 		 * Since we will now render a message instead of serving a download, we should unwind some of the previously set
 		 * headers.
 		 */
-		header( 'Content-Type: ' . get_option( 'html_type' ) . '; charset=' . get_option( 'blog_charset' ) );
-		header_remove( 'Content-Description;' );
-		header_remove( 'Content-Disposition' );
-		header_remove( 'Content-Transfer-Encoding' );
+		if ( ! headers_sent() ) {
```
Comment (barryhughes) [inline plugins/woocommerce/includes/class-wc-download-handler.php]: This check was added because, in the context of running the test suite, I encountered a headers-already-sent error (interestingly, this was because a `system()` call is made during test suite bootstrap and apparently a side effect of this is to trigger an output flush).

Seemed like a safe and straightforward solution, but let me know if any concerns.

File: plugins/woocommerce/changelog/fix-32754-inactive-downloads [hunk 2]
```diff
@@ -0,0 +1,5 @@
+Significance: patch
+Type: tweak
```
Comment (vedanshujain) [inline plugins/woocommerce/changelog/fix-32754-inactive-downloads:2]: I suppose we should remove the changelog if it's not needed otherwise the automated script to compile changelog will pick it up.

File: plugins/woocommerce/includes/class-wc-download-handler.php (hunk 1 above)
Comment (vedanshujain) [reply plugins/woocommerce/includes/class-wc-download-handler.php]: Perhaps we can refactor this code in a mockable method? But if this is time sensitive then this looks good enough to me. Also let's add a comment here for the reasoning behind this.

**Review by vedanshujain — COMMENTED** [review]
Left some minor comments, but looks good otherwise!

File: plugins/woocommerce/changelog/fix-32754-inactive-downloads (hunk 2 above)
Comment (barryhughes) [reply plugins/woocommerce/changelog/fix-32754-inactive-downloads:2]: I think this is the proper way to handle that scenario. Internal link: pcShBQ-fw-p2#comment-691

We still add the changelog file (otherwise the linter complains) and use it to document why we felt no changelog is necessary (via the comment field), but omit any actual changelog text.

File: plugins/woocommerce/includes/class-wc-download-handler.php (hunk 1 above)
Comment (barryhughes) [reply plugins/woocommerce/includes/class-wc-download-handler.php]: Yes, although the same thing is at least possible outside of a test scenario—that's just when I encountered this. I expanded it a little to log a specific error in this case (serving the same purpose as a comment but also hopefully helpful in wider terms when merchants or HEs need to troubleshoot this problem).

**Review by vedanshujain — APPROVED** [review]
