### PR TITLE
[Product Importer]: Allow empty Download Limit/Expiry values

### LINKED ISSUE #36176: Import Products reset download count to unlimited
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

I imported the CSV with a "0" in my trestings. I wanted to change it to unlimited downloads so I removed all "0" entries in my spreadsheet and updated the import with the hope it having no entry in the spreadsheet to be listed as unlimited. It seems though that the "0" entry is permanent and that it will not see it as unlimited because the field is not empty. How would I import the spreadsheet that all products have a unlimited option? Thanks Thomas

### Expected behavior

Import and create unlimited downloads with emnty table?

### Actual behavior

Import or replace table entry for Download Limit count to reset to unlimited

### Steps to reproduce

1 Go to woo product
2 Import CSV spreadsheet with empty "Download Limit" table
3 Import will display "0" in field instead of unlimited (empty) field

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://revolt3d.com
Site address (URL): https://revolt3d.com
WC Version: 7.2.2
REST API Version: ✔ 7.2.2
WC Blocks Version: ✔ 8.9.2
Action Scheduler Version: ✔ 3.4.0
Log Directory Writable: ✔
WP Version: 6.1.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 8.0.26
PHP Post Max Size: 256 MB
PHP Time Limit: 300
PHP Max Input Vars: 4000
cURL Version: 7.86.0
OpenSSL/1.1.1s

SUHOSIN Installed: –
MySQL Version: 10.3.37-MariaDB
Max Upload Size: 256 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.2.2
WC Database Prefix: wp_
Total Database Size: 20.14MB
Database Data Size: 15.34MB
Database Index Size: 4.80MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 1.52MB + Index: 0.59MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.41MB + Index: 0.27MB + Engine InnoDB
wp_aioseo_cache: Data: 0.17MB + Index: 0.03MB + Engine InnoDB
wp_aioseo_notifications: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_aioseo_posts: Data: 1.48MB + Index: 0.02MB + Engine InnoDB
wp_as3cf_items: Data: 0.09MB + Index: 0.11MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mclean_refs: Data: 0.14MB + Index: 0.00MB + Engine InnoDB
wp_mclean_scan: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mgmlp_folders: Data: 0.09MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 2.22MB + Index: 0.16MB + Engine InnoDB
wp_postmeta: Data: 5.52MB + Index: 1.61MB + Engine InnoDB
wp_posts: Data: 2.47MB + Index: 0.34MB + Engine InnoDB
wp_snippets: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.13MB + Index: 0.11MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_tm_taskmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_tm_tasks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.13MB + Index: 0.28MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wpdm_social_shares: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_yith_wcwl: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yith_wcwl_lists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB

### Post Type Counts ###

attachment: 1623
custom_css: 1
customize_changeset: 46
footer: 1
mgmlp_media_folder: 29
nav_menu_item: 19
page: 17
post: 1
product: 216
revision: 62
shop_order: 3
wp_navigation: 3
wpcf7_contact_form: 1
yith-wcbm-badge: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (24) ###

All in One SEO: by All in One SEO Team – 4.2.8
WP Offload Media Lite: by Delicious Brains – 3.1.0
Cartsy Helper: by redq – 2.1.3
Contact Form 7: by Takayuki Miyoshi – 5.7.1
Cookie Notice & Compliance for GDPR / CCPA: by Hu-manity.co – 2.4.4
Disable Admin Notices Individually: by Creative Motion  – 1.3.1
Google Analytics for WordPress by MonsterInsights: by MonsterInsights – 8.11.0
GridSter: by redqteam – 2.5
Kirki Customizer Framework: by David Vongries – 4.0.24
Media Library Folders: by Max Foundry – 8.0.4
Media Library Folders Reset: by Max Foundry – 8.0.4
One Click Demo Import: by OCDI – 3.1.2
___RedQ Reuse Form: by redqteam – 4.0.5
Safe SVG: by 10up – 2.0.3
UpdraftPlus - Backup/Restore: by UpdraftPlus.Com
DavidAnderson – 1.22.24

Payment Plugins for Stripe WooCommerce: by Payment Plugins
support@paymentplugins.com – 3.3.35

WOOCS - WooCommerce Currency Switcher: by realmag777 – 1.3.9.4
WooCommerce PayPal Payments: by WooCommerce – 2.0.1
RedQ WooCommerce Quick View: by RedQ,Inc – 1.0.2
WooCommerce Shipping & Tax: by WooCommerce – 2.1.0
WooCommerce: by Automattic – 7.2.2
WP-Optimize - Clean, Compress, Cache: by David Anderson
Ruhani Rabin
Team Updraft – 3.2.10

YITH WooCommerce Badge Management: by YITH – 2.12.0
YITH WooCommerce Wishlist: by YITH – 3.16.0

### Inactive Plugins (9) ###

Akismet Anti-Spam: by Automattic – 5.0.2
Booster for WooCommerce: by Pluggabl LLC – 6.0.1
Code Snippets: by Code Snippets Pro – 3.2.2
Extra product options For WooCommerce | Custom Product Addons and Fields: by ThemeHigh – 3.1.9
Load Google Map: by redqteam – 1.0.2
Media Cleaner: by Jordy Meow – 6.5.1
OptinMonster: by OptinMonster Popup Builder Team – 2.11.1
SiteOrigin CSS: by SiteOrigin – 1.5.5
Snazzy Maps: by Snazzy Maps – 1.4.0

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
Order datastore: WC_Order_Data_Store_CPT

### WC Pages ###

Shop base: #8 - /shop/
Cart: #10 - /cart/
Checkout: #6 - /checkout/
My account: #2 - /my-account/
Terms and conditions: #14 - /terms-conditions/

### Theme ###

Name: cartsy Child
Version: 1.6.4
Author URL: http://redq.io
Child Theme: ✔
Parent Theme Name: cartsy
Parent Theme Version: 2.1.4
Parent Theme Author URL: http://redq.io
WooCommerce Support: ✔

### Templates ###

Overrides: cartsy/woocommerce/archive-product.php
cartsy/woocommerce/cart/cart.php
cartsy/woocommerce/cart/cross-sells.php
cartsy/woocommerce/cart/mini-cart.php
cartsy/woocommerce/checkout/form-checkout.php
cartsy/woocommerce/content-single-product.php
cartsy/woocommerce/global/form-login.php
cartsy/woocommerce/loop/loop-end.php
cartsy/woocommerce/loop/loop-start.php
cartsy/woocommerce/myaccount/dashboard.php
cartsy/woocommerce/myaccount/form-login.php
cartsy/woocommerce/myaccount/navigation.php
cartsy/woocommerce/single-product/add-to-cart/grouped.php
cartsy/woocommerce/single-product/price.php
cartsy/woocommerce/single-product/rating.php
cartsy/woocommerce/single-product/related.php
cartsy/woocommerce/single-product/review.php
cartsy/woocommerce/single-product/up-sells.php
cartsy/woocommerce/single-product.php
cartsy/woocommerce/content-product_cat.php

### WooCommerce PayPal Payments ###

Onboarded: ✔
Shop country code: US
WooCommerce currency supported: ✔
Advanced Card Processing available in country: ✔
Pay Later messaging available in country: ✔
Webhook status: –
Vault enabled: ✔
Logging enabled: –
Reference Transactions: –
Used PayPal Checkout plugin: –
Tracking enabled: ✔

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
experimental-products-task
experimental-import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
multichannel-marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
settings

Daily Cron: ✔ Next scheduled: 2022-12-25 17:53:49 +00:00
Options: ✔
Notes: 49
Onboarding: skipped

### Action Scheduler ###

Complete: 1,685
Oldest: 2022-12-11 17:55:08 +0000
Newest: 2022-12-25 09:35:49 +0000

Pending: 4
Oldest: 2022-12-25 09:50:49 +0000
Newest: 2022-12-26 09:35:49 +0000

### Status report information ###

Generated at: 2022-12-25 09:48:24 +00:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by jimjasson**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

When saving the Download Limit/Expiry fields from the UI, the empty string value is a valid option and indicates unlimited downloads and downloads that never expire, respectively. That's why the value of these fields is not cast to `int` if it is empty: https://github.com/woocommerce/woocommerce/blob/8eeadc72263e5994b8f0bb1a3b5b0b69941dde83/plugins/woocommerce/includes/admin/meta-boxes/class-wc-meta-box-product-data.php#L401-L402

However, when importing a product, the value of this fields is always cast to `int`, even when it is empty. Therefore, it is not possible to clear these fields when importing and updating a product. 

This PR ensures that the empty string is treated as a valid value, similarly to when saving the product via the UI. 

Closes #36176 

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

Start with `trunk`.
1. Create a downloadable Simple Product with a Download Limit and Download Expiry values.
2. Export it.
3. In the exported CSV file, set the values for Download Limit and Download Expiry to empty string. 
4. Import the CSV file back to the site and click to update products with matching IDs. 
5. View the product and notice that `0` has been saved for both fields. 

Check out this branch. 
1. Create a downloadable Simple Product with a Download Limit and Download Expiry values.
2. Export it.
3. In the exported CSV file, set the values for Download Limit and Download Expiry to empty string. 
4. Import the CSV file back to the site and click to update products with matching IDs. 
5. View the product and notice that an empty string has been saved for both fields, meaning 'Unlimited' and 'Never' respectively. 

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 
Fixed an issue that prevented the Download Limit and Expiry fields from being cleared during product import.

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

**Review by naman03malhotra — COMMENTED** [review]
Hey @jimjasson, thanks for working on this!

I noticed that when exporting a downloadable simple product, the `download_limit` and `download_expiry` fields are set to `-1` to indicate unlimited downloads and no expiry.

Try importing this CSV for reference:  
[test-export-umlt.csv](https://github.com/user-attachments/files/20368454/test-export-umlt.csv)

As mentioned in the connected [issue](https://github.com/woocommerce/woocommerce/issues/36176):

> How would I import the spreadsheet so all products have the unlimited option?

Setting `download_limit` and `download_expiry` to `-1` should cover this use case.
image

Given that exports already use `-1` to represent "unlimited", my opinion is that we keep the current behavior and improve the documentation, for now.

Let me know what you think.

**Comment by jimjasson** [comment]
Hey @naman03malhotra, 

Thank you for your comment! 

Looking at `WC_Product::set_download_limit` and `WC_Product::set_download_expiry`, both `''` and `-1` are considered valid ways to clear out this field, but the importer currently supports only 1 of the two:

https://github.com/woocommerce/woocommerce/blob/d596e0344d6eb98c860daa36909680d5a75eff35/plugins/woocommerce/includes/abstracts/abstract-wc-product.php#L1357-L1369

So, I think that both should be supported, especially since leaving a field empty in the CSV file is the most intuitive way to clear it.

File: plugins/woocommerce/includes/import/class-wc-product-csv-importer.php [hunk 1]
```diff
@@ -696,6 +696,12 @@ public function parse_download_file_field( $value ) {
 	 * @return int
```
Comment (naman03malhotra) [inline plugins/woocommerce/includes/import/class-wc-product-csv-importer.php]: We should consider changing the return type, as it will also return an empty string from now on.

File: plugins/woocommerce/tests/legacy/unit-tests/importer/product.php [hunk 2]
```diff
@@ -363,8 +363,8 @@ public function test_get_parsed_data() {
 				'sale_price'            => '18',
 				'regular_price'         => '20',
 				'shipping_class_id'     => 0,
-				'download_limit'        => 0,
-				'download_expiry'       => 0,
+				'download_limit'        => '',
```
Comment (naman03malhotra) [inline plugins/woocommerce/tests/legacy/unit-tests/importer/product.php:366]: For test, what do you think about taking it a step further? it would be great to ensure they not only check that the CSV parser returns '' but also verify the actual state of the product after import.

File: plugins/woocommerce/includes/import/class-wc-product-csv-importer.php [hunk 3]
```diff
@@ -3,7 +3,7 @@
  * WooCommerce Product CSV importer
  *
  * @package WooCommerce\Import
- * @version 3.1.0
+ * @version x.x.x
```
Comment (naman03malhotra) [inline plugins/woocommerce/includes/import/class-wc-product-csv-importer.php]: We should add the next version here before merging, because IIRC, WooCore release process doesn't have a step to look for `x.x.x` placeholders and replace later.

**Review by naman03malhotra — COMMENTED** [review]
Thanks for working on it! Looks good overall.

I followed the mentioned steps and the value is being now being set as unlimited by both `-1` and ''. 

Left some comments about tests, let me know what do you think? I can approve this PR right away, if you plan to do it in a separate PR (or not at all).

File: plugins/woocommerce/includes/import/class-wc-product-csv-importer.php (hunk 1 above)
Comment (jimjasson) [reply plugins/woocommerce/includes/import/class-wc-product-csv-importer.php]: Good catch! Updated!

File: plugins/woocommerce/includes/import/class-wc-product-csv-importer.php (hunk 3 above)
Comment (jimjasson) [reply plugins/woocommerce/includes/import/class-wc-product-csv-importer.php]: I thought that the Woorelease updated these automatically: https://github.com/woocommerce/woorelease/blob/b8a2ec2550f6a6664791962e6f9e29dd61d1b61e/includes/tools/class-version-replace.php#L36

and also `trunk` has some files with `x.x.x` right now. 

But updated it to `10.0.0`.

File: plugins/woocommerce/tests/legacy/unit-tests/importer/product.php (hunk 2 above)
Comment (jimjasson) [reply plugins/woocommerce/tests/legacy/unit-tests/importer/product.php:366]: Thanks for the comment! 

The test I updated is has a very specific context and is meant to test that the Importer parses data correctly, not that the data is actually set on the product. Once the data is parsed, then the Importer calls `set_props` to set them -- this function is tested by separate unit tests.

**Review by naman03malhotra — APPROVED** [review]
Thanks for addressing the comments :shipit:
