### PR TITLE
Ensuring only single product creation with unique SKU for concurrent requests

### LINKED ISSUE #27295: Duplicate products with identical SKUs created via API
**Description of the problem**
The syncing system sends requests to `/wp-json/wc/v3/products/batch` endpoint. It usually creates concurrent connections to the WooCommerce API. Sometimes, it happens that if two or more requests contain information about the same product and they run at the same time we end up with multiple products created having identical SKUs.

**Steps to reproduce**
```
curl -X POST \
  https://shop.test/wp-json/wc/v3/products/batch \
  -H 'Authorization: Basic Y2tfZWExNmNmNzVkZjkyMWM4YWZmYmI2MjAxYmZiMjU0ODAwNjNhYzk2MTpjc183MDAzOGMxNTRiZWVlYmEyMTU2ZmQ4MGQ2NWE5ZmM1NzcyMGY5M2Mz' \
  -H 'Content-Type: application/json' \
  -d '{
    "create": [
        {
            "name": "Unique SKU product",
            "type": "simple",
            "sku": 12345
        }
    ]
}' -k & curl -X POST \
  https://shop.test/wp-json/wc/v3/products/batch \
  -H 'Authorization: Basic Y2tfZWExNmNmNzVkZjkyMWM4YWZmYmI2MjAxYmZiMjU0ODAwNjNhYzk2MTpjc183MDAzOGMxNTRiZWVlYmEyMTU2ZmQ4MGQ2NWE5ZmM1NzcyMGY5M2Mz' \
  -H 'Content-Type: application/json' \
  -d '{
    "create": [
        {
            "name": "Unique SKU product",
            "type": "simple",
            "sku": 12345
        }
    ]
}' -k
```

**Expected behavior**
By default, it should not be possible to add a new product with an existing SKU.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Serverinfo: Apache/2.4.41 (Unix) OpenSSL/1.0.2s PHP/7.2.22
PHP version: 7.2.22
MySQL version: 5.5.5-10.4.6-MariaDB
WooCommerce version: 3.6.4
WordPress version: 5.2.3
```
</details>

### PR DESCRIPTION
**Pull request by naman03malhotra**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:
Closes #27295 

Added a method in the V2 product controller that check unique SKUs in the post meta before going ahead and creating the product.

### Before (on `trunk`)
image

### After
image

### How to test the changes in this Pull Request:

1. Copy the following script locally.
2. Now enter your credentials, you can get them from `woocommerce>settings>advanced>REST API`
3. Create new API keys if you don't have one already.
4. Add the CK and CS in the respective placeholders.
5. Replace the URL to the endpoint
6. Change the initial product SKU to something which is already not present on the table
7. Now run the script in `trunk` first, check the ` log_error_counts.txt` file, note the output
8. Check the products page in WC admin, you'll see multiple products created with the same SKU.
9. Run the script in this branch, check the ` log_error_counts.txt` file the output should be 1, 1
10. Check the products page in WC admin, you'll see only one product created with the same SKU.

I've created this bash script to test the change

```
#!/bin/bash

# Define the URL and authentication
URL="https://d.w.test/wp-json/wc/v3/products/batch"
CK="ck_7b87bfb00d141081ea0b2be4c443b939ac60677e"
CS="cs_0fbab889a09db5d83af5f2096ec553cf011c47c0"
CONTENT_TYPE="Content-Type: application/json"


INITIAL_SKU=4048

ROUNDS=5

CONCURRENT_REQUESTS=10

echo "Sending $ROUNDS rounds of $CONCURRENT_REQUESTS concurrent requests..."

count_errors() {
    local round=$1
    local error_count=0

    for i in $(seq 1 $CONCURRENT_REQUESTS); do
        if grep -q "error" "log_${round}_${i}.txt"; then
            error_count=$((error_count + 1))
        fi
    done

    echo $((CONCURRENT_REQUESTS - $error_count))
}

for j in $(seq 1 $ROUNDS); do
    SKU=$(($INITIAL_SKU + $j - 1)) 
    echo "Round $j with SKU $SKU..."

    for i in $(seq 1 $CONCURRENT_REQUESTS); do
        JSON_DATA=$(cat <<EOF
{
    "create": [
        {
            "name": "${j}-${i} New Test Product",
            "type": "simple",
            "sku": "${SKU}"
        }
    ]
}
EOF
)
        curl -X POST $URL \
            -u "$CK:$CS" \
            -H "$CONTENT_TYPE" \
            -d "$JSON_DATA" -k > "log_${j}_${i}.txt" 2>&1 &
    done

    wait
    echo "Completed round $j."

    error_count=$(count_errors $j)
    echo "Total products created in round $j with sku $SKU: $error_count" >> log_error_counts.txt
done

echo "All requests sent. Check log files for output."

```

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce/includes/rest-api/Controllers/Version3/class-wc-rest-products-controller.php [hunk 1]
```diff
@@ -1721,4 +1721,43 @@ public function get_suggested_products( $request ) {
 
 		return parent::get_items( $request );
 	}
+	/**
+	 * Check if a SKU exists.
+	 * @param string $sku SKU.
+	 * @return bool
+	 */
+	public function does_sku_exist( $sku ) {
```
Comment (vedanshujain) [inline plugins/woocommerce/includes/rest-api/Controllers/Version3/class-wc-rest-products-controller.php]: We should replace the method `is_existing_sku` in the data store CPT, instead of adding a new method with same functionality in a controller.

File: plugins/woocommerce/includes/rest-api/Controllers/Version3/class-wc-rest-products-controller.php [hunk 2]
```diff
@@ -1721,4 +1721,43 @@ public function get_suggested_products( $request ) {
...
+		global $wpdb;
+
+		// phpcs:ignore WordPress.VIP.DirectDatabaseQuery.DirectQuery
+		return (bool) $wpdb->get_var(
+			$wpdb->prepare(
+				"
+				SELECT meta_id
+				FROM $wpdb->postmeta
+				WHERE meta_key = '_sku' AND meta_value = %s
+				LIMIT 1 FOR UPDATE
```
Comment (vedanshujain) [inline plugins/woocommerce/includes/rest-api/Controllers/Version3/class-wc-rest-products-controller.php]: is `FOR UPDATE` necessary, probably a reminiscent of your testing

**Review by naman03malhotra — COMMENTED** [review]
Thanks for the review, it makes sense, I will update the existing method, moving the query from lookup table to postmeta did help, but still duplicate products are being created, which is very annoying tbh, and I do feel the people commenting in the issue.

So to solve this, I created a cleanup function to cleanup duplicate products whenever we encounter a duplicate SKU error during concurrent requests, I've tested it multiple time and it works well.

I plan to move it behind the action scheduler to keep things async, but let me know what you folks think about this.

**Comment by naman03malhotra** [comment]
Relevant slack conversation: p1715603112152869-slack-C0E1AV8T0

File: plugins/woocommerce/includes/data-stores/class-wc-product-data-store-cpt.php [hunk 3]
```diff
@@ -981,29 +981,22 @@ public function get_featured_product_ids() {
 	 * Check if product sku is found for any other product IDs.
 	 *
 	 * @since 3.0.0
-	 * @param int    $product_id Product ID.
 	 * @param string $sku Will be slashed to work around https://core.trac.wordpress.org/ticket/27421.
 	 * @return bool
 	 */
-	public function is_existing_sku( $product_id, $sku ) {
+	public function is_existing_sku( $sku ) {
```
Comment (coreymckrill) [inline plugins/woocommerce/includes/data-stores/class-wc-product-data-store-cpt.php]: Removing `$product_id` from the method signature seems like it would break backcompat, since it is public. Two alternatives I can think of off the top:
* Rather than removing, we could change the name of the param to `$deprecated` and just not use it in the method
* Create a new method, and then deprecate this one and have it call the new method

File: plugins/woocommerce/includes/rest-api/Controllers/Version3/class-wc-rest-crud-controller.php [hunk 4]
```diff
@@ -176,6 +176,43 @@ protected function save_object( $request, $creating = false ) {
...
+		array_shift( $product_ids );
+	
+		if (!empty( $product_ids )) {
+			$ids_to_delete = implode(',', array_map( 'intval', $product_ids ));
+	
+			// Delete prodocts post
+			$wpdb->query( "DELETE FROM $wpdb->posts WHERE ID IN ($ids_to_delete)" );
+	
+			// Delete products post meta
+			$wpdb->query( "DELETE FROM $wpdb->postmeta WHERE post_id IN ($ids_to_delete)" );
```
Comment (coreymckrill) [inline plugins/woocommerce/includes/rest-api/Controllers/Version3/class-wc-rest-crud-controller.php]: Is it safe here to do the product deletions with raw SQL? This will bypass actions/filters that run during normal programmatic production deletion, such as [`woocommerce_pre_delete_product`](https://github.com/woocommerce/woocommerce/blob/db50513c42d77e533f76c4b9b31e42b8709f824b/plugins/woocommerce/includes/abstracts/abstract-wc-data.php#L207-L207) and [`woocommerce_delete_product`](https://github.com/woocommerce/woocommerce/blob/db50513c42d77e533f76c4b9b31e42b8709f824b/plugins/woocommerce/includes/data-stores/class-wc-product-data-store-cpt.php#L303).

**Comment by naman03malhotra** [comment]
@coreymckrill @vedanshujain, this PR is ready to have another look with a changed approach, so far it does the job. I am yet to write a test for it.

File: plugins/woocommerce/includes/data-stores/class-wc-product-data-store-cpt.php [hunk 5]
```diff
@@ -96,6 +96,42 @@ class WC_Product_Data_Store_CPT extends WC_Data_Store_WP implements WC_Object_Da
...
+	private function obtain_lock_on_sku_for_concurrent_requests( $product ) {
+		global $wpdb;
+		$product_id = $product->get_id();
+		$sku        = $product->get_sku();
+
+		$query = $wpdb->prepare(
+			"INSERT INTO $wpdb->wc_product_meta_lookup (product_id, sku)
+			SELECT %d, %s
+			WHERE NOT EXISTS (
+				SELECT * FROM $wpdb->wc_product_meta_lookup WHERE sku = %s
```
Comment (vedanshujain) [inline plugins/woocommerce/includes/data-stores/class-wc-product-data-store-cpt.php]: We can probably `LIMIT 1` this clause too for extra safety (although the outer limit 1 should be sufficient)

File: plugins/woocommerce/includes/data-stores/class-wc-product-data-store-cpt.php [hunk 6]
```diff
@@ -96,6 +96,42 @@ class WC_Product_Data_Store_CPT extends WC_Data_Store_WP implements WC_Object_Da
...
+	 * @return bool True if lock is obtained (unique SKU), false otherwise.
+	 */
+	private function obtain_lock_on_sku_for_concurrent_requests( $product ) {
+		global $wpdb;
+		$product_id = $product->get_id();
+		$sku        = $product->get_sku();
+
+		$query = $wpdb->prepare(
+			"INSERT INTO $wpdb->wc_product_meta_lookup (product_id, sku)
+			SELECT %d, %s
```
Comment (vedanshujain) [inline plugins/woocommerce/includes/data-stores/class-wc-product-data-store-cpt.php]: Note that many hosts won't allow a select without specifying a table name, (for example when DB clustering is being used). So this needs a `FROM` statement for any existing table.

Maybe we can change this line to something like
```
SELECT %d, %s FROM $wpdb->wc_product_meta_lookup
```

**Review by vedanshujain — COMMENTED** [review]
I see that this currently does not handle updates? I think we would need to add similar capability there too.

File: plugins/woocommerce/includes/data-stores/class-wc-product-data-store-cpt.php (hunk 6 above)
Comment (naman03malhotra) [reply plugins/woocommerce/includes/data-stores/class-wc-product-data-store-cpt.php]: Good catch added it here: https://github.com/woocommerce/woocommerce/pull/47476/commits/55954d3411ea25e4652cfc0ec6d6a30610c52a7b

File: plugins/woocommerce/includes/data-stores/class-wc-product-data-store-cpt.php (hunk 5 above)
Comment (naman03malhotra) [reply plugins/woocommerce/includes/data-stores/class-wc-product-data-store-cpt.php]: Added here: https://github.com/woocommerce/woocommerce/pull/47476/commits/55954d3411ea25e4652cfc0ec6d6a30610c52a7b

**Comment by naman03malhotra** [comment]
>I see that this currently does not handle updates? I think we would need to add similar capability there too.

Good idea, though I suggest that we roll out this enhancement first and see how it fairs in the real world and if everything looks good, we can also push it for updates, wdyt?

File: plugins/woocommerce/includes/data-stores/class-wc-product-data-store-cpt.php [hunk 7]
```diff
@@ -137,6 +174,18 @@ public function create( &$product ) {
...
 			$product->set_id( $id );
+			$sku = $product->get_sku();
+
+			/**
+			 * If SKU is already under processing aka Duplicate SKU
+			 * because of concurrent requests, then we should not proceed
+			 * Delete the product and throw an exception.
+			 */
+			if ( ! empty( $sku ) && ! $this->obtain_lock_on_sku_for_concurrent_requests( $product ) ) {
+				$product->delete();
```
Comment (coreymckrill) [inline plugins/woocommerce/includes/data-stores/class-wc-product-data-store-cpt.php]:
```suggestion
				$product->delete( true );
```

I noticed after running the test script that the products that were deleted because they had the same SKU were sitting in the trash. Would it make sense to delete them permanently instead so they don't continue taking up space in the db?

File: plugins/woocommerce/includes/rest-api/Controllers/Version3/class-wc-rest-crud-controller.php [hunk 8]
```diff
@@ -188,7 +188,11 @@ public function create_item( $request ) {
 			return new WP_Error( "woocommerce_rest_{$this->post_type}_exists", sprintf( __( 'Cannot create existing %s.', 'woocommerce' ), $this->post_type ), array( 'status' => 400 ) );
 		}
 
-		$object = $this->save_object( $request, true );
+		try {
+			$object = $this->save_object( $request, true );
+		} catch ( Exception $e ) {
+			return new WP_Error( "woocommerce_rest_{$this->post_type}_not_created", $e->getMessage(), array( 'status' => 500 ) );
```
Comment (coreymckrill) [inline plugins/woocommerce/includes/rest-api/Controllers/Version3/class-wc-rest-crud-controller.php]: Is `500` "internal server error" the right status code here? Seems like maybe it should be [`400` "bad request"](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/400) instead...

**Comment by coreymckrill** [comment]
> I suggest that we roll out this enhancement first and see how it fairs in the real world and if everything looks good, we can also push it for updates

This sounds good to me!

File: plugins/woocommerce/includes/data-stores/class-wc-product-data-store-cpt.php (hunk 6 above)
Comment (naman03malhotra) [reply plugins/woocommerce/includes/data-stores/class-wc-product-data-store-cpt.php]: >SELECT %d, %s FROM $wpdb->wc_product_meta_lookup

used `$wpdb->options` instead of this, as tests were failing as ` $wpdb->wc_product_meta_lookup` was empty

File: plugins/woocommerce/includes/data-stores/class-wc-product-data-store-cpt.php (hunk 7 above)
Comment (naman03malhotra) [reply plugins/woocommerce/includes/data-stores/class-wc-product-data-store-cpt.php]: Good point, made this change

File: plugins/woocommerce/includes/rest-api/Controllers/Version3/class-wc-rest-crud-controller.php (hunk 8 above)
Comment (naman03malhotra) [reply plugins/woocommerce/includes/rest-api/Controllers/Version3/class-wc-rest-crud-controller.php]: Good catch, I added it as a TODO in my head, but forgot later on. Made this change.

**Comment by naman03malhotra** [comment]
@coreymckrill @vedanshujain, thank you for the feedback so far; I've addressed it all and also added a test.

File: plugins/woocommerce/includes/data-stores/class-wc-product-data-store-cpt.php [hunk 9]
```diff
@@ -137,6 +176,18 @@ public function create( &$product ) {
...
+
+			/**
+			 * If SKU is already under processing aka Duplicate SKU
+			 * because of concurrent requests, then we should not proceed
+			 * Delete the product and throw an exception.
+			 */
+			if ( ! empty( $sku ) && ! $this->obtain_lock_on_sku_for_concurrent_requests( $product ) ) {
+				$product->delete( true );
+				// translators: 1: SKU, 2: Product Id.
+				throw new Exception( esc_html( sprintf( __( 'The SKU (%1$s) you are trying to insert with Product Id (%2$s) is already under processing', 'woocommerce' ), $sku, $id ) ) );
```
Comment (coreymckrill) [inline plugins/woocommerce/includes/data-stores/class-wc-product-data-store-cpt.php]: Sorry I didn't think of this earlier, but it occurs to me that throwing an exception in this existing public method might be breaking backcompat, because other codebases that use the method wouldn't be wrapping it in a try/catch (thus risking an "uncaught exception" fatal error). In fact, there is at least one other place in this codebase besides the REST CRUD controller that is using it that this PR doesn't update with a try/catch ([example](https://github.com/woocommerce/woocommerce/blob/f56d3e3ee04a47f750e71bc8c09c4152c293052d/plugins/woocommerce/includes/abstracts/abstract-wc-product.php#L1435-L1435)).

I don't have a better idea off the top of my head for passing the result of the SKU lock check on to the caller, but I do think it's worth considering the risks here. Wdyt?

Comment (naman03malhotra) [reply plugins/woocommerce/includes/data-stores/class-wc-product-data-store-cpt.php]: Being discussed here: p1717092314975919-slack-C0E1AV8T0

File: plugins/woocommerce/includes/rest-api/Controllers/Version3/class-wc-rest-crud-controller.php [hunk 10]
```diff
@@ -166,7 +166,17 @@ protected function save_object( $request, $creating = false ) {
 				return $object;
 			}
 
-			$object->save();
+			/**
+			 * Setting a migic property to indicate that this is a REST request.
+			 * We are doing this to ensure that unique SKU validation
+			 * is only triggered for REST requests where we are handling the exception.
+			 */
+			$object->is_rest_request = true;
```
Comment (coreymckrill) [inline plugins/woocommerce/includes/rest-api/Controllers/Version3/class-wc-rest-crud-controller.php]: This throws a deprecation notice in PHP 8.2+:

```
PHP Deprecated:  Creation of dynamic property WC_Product_Simple::$is_rest_request is deprecated in /var/www/html/wp-content/plugins/woocommerce/includes/rest-api/Controllers/Version3/class-wc-rest-crud-controller.php on line 174
```

Comment (coreymckrill) [reply plugins/woocommerce/includes/rest-api/Controllers/Version3/class-wc-rest-crud-controller.php]: Would it work to use [this function](https://github.com/woocommerce/woocommerce/blob/eabc599c5129493045a20d6fa9dfb0a867aff3eb/plugins/woocommerce/includes/class-woocommerce.php#L459) instead of setting a property?

File: plugins/woocommerce/includes/data-stores/class-wc-product-data-store-cpt.php [hunk 11]
```diff
@@ -96,6 +96,44 @@ class WC_Product_Data_Store_CPT extends WC_Data_Store_WP implements WC_Object_Da
...
+	 * create product with unique SKU for concurrent requests.
+	 *
+	 * We are doing so by inserting a row in the wc_product_meta_lookup table
+	 * upfront with the SKU of the product we are trying to insert.
+	 *
+	 * If the SKU is already present in the table, it means that another
+	 * request is already processing the same SKU and we should not proceed
+	 * with the insert.
+	 *
+	 * using $wpdb->options as it always has some data
```
Comment (vedanshujain) [inline plugins/woocommerce/includes/data-stores/class-wc-product-data-store-cpt.php]: Let's explain this a bit more, specially that if we select from a table that does not have any data, then our query will always return null set and the `where` subquery won't be fired, effectively bypassing any lock.

File: plugins/woocommerce/includes/data-stores/class-wc-product-data-store-cpt.php [hunk 12]
```diff
@@ -137,6 +176,18 @@ public function create( &$product ) {
...
 		if ( $id && ! is_wp_error( $id ) ) {
 			$product->set_id( $id );
+			$sku = $product->get_sku();
+
+			/**
+			 * If SKU is already under processing aka Duplicate SKU
+			 * because of concurrent requests, then we should not proceed
+			 * Delete the product and throw an exception.
+			 */
+			if ( ! empty( $sku ) && ! $this->obtain_lock_on_sku_for_concurrent_requests( $product ) && $product->is_rest_request ) {
```
Comment (vedanshujain) [inline plugins/woocommerce/includes/data-stores/class-wc-product-data-store-cpt.php]: `obtain_lock_on_sku_for_concurrent_requests` should be the last check in `if` condition for performance, since it's considerably heavier than other checks.

File: plugins/woocommerce/tests/php/includes/data-stores/class-wc-product-data-store-cpt-test.php [hunk 13]
```diff
@@ -66,4 +66,54 @@ public function test_rating_counts_are_summed_correctly(): void {
...
+	 *
+	 * Throw error when two concurrent requests try to create a product with the same SKU.
+	 *
+	 * @return void
+	 */
+	public function test_create_product_with_unique_sku_on_concurrent_requests() {
+		try {
+			$this->create_products_concurrently();
+		} catch ( Exception $e ) {
+			$this->assertMatchesRegularExpression(
```
Comment (vedanshujain) [inline plugins/woocommerce/tests/php/includes/data-stores/class-wc-product-data-store-cpt-test.php]: note that this test will not fail even if the exception was not thrown, since the control will never get in this block. consider using the `finally` block, or perhaps `$this->expectException` would be the simplest.

**Review by vedanshujain — COMMENTED** [review]
Adding a few more comments in addition to what Corey added, nice work!

File: plugins/woocommerce/tests/php/includes/data-stores/class-wc-product-data-store-cpt-test.php (hunk 13 above)
Comment (naman03malhotra) [reply plugins/woocommerce/tests/php/includes/data-stores/class-wc-product-data-store-cpt-test.php]: Good catch, added as part of this commit: https://github.com/woocommerce/woocommerce/pull/47476/commits/5b596d822472d79cecfb1449be3497b40fd0a2af

File: plugins/woocommerce/includes/data-stores/class-wc-product-data-store-cpt.php (hunk 12 above)
Comment (naman03malhotra) [reply plugins/woocommerce/includes/data-stores/class-wc-product-data-store-cpt.php]: Good point, modified here: https://github.com/woocommerce/woocommerce/pull/47476/commits/5b596d822472d79cecfb1449be3497b40fd0a2af

File: plugins/woocommerce/includes/data-stores/class-wc-product-data-store-cpt.php (hunk 11 above)
Comment (naman03malhotra) [reply plugins/woocommerce/includes/data-stores/class-wc-product-data-store-cpt.php]: Made changes here: https://github.com/woocommerce/woocommerce/pull/47476/commits/5b596d822472d79cecfb1449be3497b40fd0a2af

File: plugins/woocommerce/includes/rest-api/Controllers/Version3/class-wc-rest-crud-controller.php (hunk 10 above)
Comment (naman03malhotra) [reply plugins/woocommerce/includes/rest-api/Controllers/Version3/class-wc-rest-crud-controller.php]: Works perfectly, added as part of https://github.com/woocommerce/woocommerce/pull/47476/commits/5b596d822472d79cecfb1449be3497b40fd0a2af

File: plugins/woocommerce/includes/data-stores/class-wc-product-data-store-cpt.php (hunk 9 above)
Comment (naman03malhotra) [reply plugins/woocommerce/includes/data-stores/class-wc-product-data-store-cpt.php]: Resolved as part of https://github.com/woocommerce/woocommerce/pull/47476/commits/5b596d822472d79cecfb1449be3497b40fd0a2af

**Comment by naman03malhotra** [comment]
@coreymckrill @vedanshujain thank you for the amazing feedback so far and helping this PR get close to the finish line, the PR is ready for review.

**Review by vedanshujain — APPROVED** [review]
Looks great, note that to test I also shorted the method `wc_product_has_unique_sku` to always return true and checked that the query was fired and the return result was `0`.
