### PR TITLE
Product image: avoid unnecessary calculations

### LINKED ISSUE #61955: Category Archive performance on Block based themes with variable products
## **Describe the bug**

Hi devs,

We're helping a merchant with some performance issue - most of their products are variable products with 100s of variations. They're using non-block based theme however during conflict testing with 2025 theme which is block based we discovered that cat archive page with mostly all variable products is taking 4s-6s to load with just 2025 and WooCommerce active

So while this isn't relevant to merchant's case (non-block theme), I still wanted to report it separately.

Memory consumption is also high. Then on further testing using Pressable's APM it stood out that there's gallery image fetching that's causing additional DB queries.

[https://github.com/woocommerce/woocommerce/blob/66d7b67f9d7e6a95e4534abea6bd3713dfe72bed/plugins/woocommerce/src/Blocks/BlockTypes/ProductImage.php#L164](https://github.com/woocommerce/woocommerce/blob/66d7b67f9d7e6a95e4534abea6bd3713dfe72bed/plugins/woocommerce/src/Blocks/BlockTypes/ProductImage.php#L164)

Temporarily commenting that out and giving blank array to $gallery_image_ids reduces time to less than 1s

I am wondering is gallery image IDs required on category pages when they are not used? Here is a sample trace triggering various functions and DB reads

```
SELECT  t.term_id
			 FROM wp_terms AS t  INNER JOIN wp_term_taxonomy AS tt ON t.term_id = tt.term_id
			 WHERE tt.taxonomy IN ('pa_size') AND t.slug IN ('medium')
			 
			 LIMIT 1

STACK TRACE:
#0 /Applications/MAMP/htdocs/woogenerator/sites/wp-1583632/wp-includes/class-wp-hook.php(324): ks_query_logger_any('SELECT  t.term_...')
#1 /Applications/MAMP/htdocs/woogenerator/sites/wp-1583632/wp-includes/plugin.php(205): WP_Hook->apply_filters('SELECT  t.term_...', Array)
#2 /Applications/MAMP/htdocs/woogenerator/sites/wp-1583632/wp-includes/class-wpdb.php(2228): apply_filters('query', 'SELECT  t.term_...')
#3 /Applications/MAMP/htdocs/woogenerator/sites/wp-1583632/wp-includes/class-wpdb.php(3146): wpdb->query('SELECT  t.term_...')
#4 /Applications/MAMP/htdocs/woogenerator/sites/wp-1583632/wp-includes/class-wp-term-query.php(814): wpdb->get_results('SELECT  t.term_...')
#5 /Applications/MAMP/htdocs/woogenerator/sites/wp-1583632/wp-includes/class-wp-term-query.php(308): WP_Term_Query->get_terms()
#6 /Applications/MAMP/htdocs/woogenerator/sites/wp-1583632/wp-includes/taxonomy.php(1357): WP_Term_Query->query(Array)
#7 /Applications/MAMP/htdocs/woogenerator/sites/wp-1583632/wp-includes/taxonomy.php(1147): get_terms(Array)
#8 /Applications/MAMP/htdocs/woogenerator/sites/wp-1583632/wp-content/plugins/woocommerce/includes/wc-product-functions.php(484): get_term_by('slug', 'medium', 'pa_size')
#9 /Applications/MAMP/htdocs/woogenerator/sites/wp-1583632/wp-content/plugins/woocommerce/includes/data-stores/class-wc-product-variation-data-store-cpt.php(316): wc_get_formatted_variation(Object(WC_Product_Variation), true, false)
#10 /Applications/MAMP/htdocs/woogenerator/sites/wp-1583632/wp-content/plugins/woocommerce/includes/data-stores/class-wc-product-variation-data-store-cpt.php(94): WC_Product_Variation_Data_Store_CPT->generate_product_title(Object(WC_Product_Variation))
#11 /Applications/MAMP/htdocs/woogenerator/sites/wp-1583632/wp-content/plugins/woocommerce/includes/class-wc-data-store.php(159): WC_Product_Variation_Data_Store_CPT->read(Object(WC_Product_Variation))
#12 /Applications/MAMP/htdocs/woogenerator/sites/wp-1583632/wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-product.php(147): WC_Data_Store->read(Object(WC_Product_Variation))
#13 /Applications/MAMP/htdocs/woogenerator/sites/wp-1583632/wp-content/plugins/woocommerce/includes/class-wc-product-simple.php(26): WC_Product->__construct(41)
#14 /Applications/MAMP/htdocs/woogenerator/sites/wp-1583632/wp-content/plugins/woocommerce/includes/class-wc-product-variation.php(59): WC_Product_Simple->__construct(41)
#15 /Applications/MAMP/htdocs/woogenerator/sites/wp-1583632/wp-content/plugins/woocommerce/includes/class-wc-product-factory.php(48): WC_Product_Variation->__construct(41, Array)
#16 /Applications/MAMP/htdocs/woogenerator/sites/wp-1583632/wp-content/plugins/woocommerce/includes/wc-product-functions.php(78): WC_Product_Factory->get_product(41, Array)
#17 /Applications/MAMP/htdocs/woogenerator/sites/wp-1583632/wp-content/plugins/woocommerce/src/Blocks/Utils/ProductGalleryUtils.php(122): wc_get_product(41)
#18 /Applications/MAMP/htdocs/woogenerator/sites/wp-1583632/wp-content/plugins/woocommerce/src/Blocks/Utils/ProductGalleryUtils.php(22): Automattic\WooCommerce\Blocks\Utils\ProductGalleryUtils::get_product_variation_image_ids(Object(WC_Product_Variable))
#19 /Applications/MAMP/htdocs/woogenerator/sites/wp-1583632/wp-content/plugins/woocommerce/src/Blocks/BlockTypes/ProductImage.php(164): Automattic\WooCommerce\Blocks\Utils\ProductGalleryUtils::get_all_image_ids(Object(WC_Product_Variable))
#20 /Applications/MAMP/htdocs/woogenerator/sites/wp-1583632/wp-content/plugins/woocommerce/src/Blocks/BlockTypes/ProductImage.php(237): Automattic\WooCommerce\Blocks\BlockTypes\ProductImage->render_image(Object(WC_Product_Variable), Array, NULL)
#21 /Applications/MAMP/htdocs/woogenerator/sites/wp-1583632/wp-content/plugins/woocommerce/src/Blocks/BlockTypes/AbstractBlock.php(98): Automattic\WooCommerce\Blocks\BlockTypes\ProductImage->render(Array, '\n\t\t\t\n\t\t', Object(WP_Block))
#22 /Applications/MAMP/htdocs/woogenerator/sites/wp-1583632/wp-includes/class-wp-block.php(586): Automattic\WooCommerce\Blocks\BlockTypes\AbstractBlock->render_callback(Array, '\n\t\t\t\n\t\t', Object(WP_Block))
#23 /Applications/MAMP/htdocs/woogenerator/sites/wp-1583632/wp-includes/class-wp-block.php(566): WP_Block->render()
#24 /Applications/MAMP/htdocs/woogenerator/sites/wp-1583632/wp-content/plugins/woocommerce/src/Blocks/BlockTypes/ProductTemplate.php(117): WP_Block->render(Array)
#25 /Applications/MAMP/htdocs/woogenerator/sites/wp-1583632/wp-content/plugins/woocommerce/src/Blocks/BlockTypes/AbstractBlock.php(98): Automattic\WooCommerce\Blocks\BlockTypes\ProductTemplate->render(Array, '', Object(WP_Block))
#26 /Applications/MAMP/htdocs/woogenerator/sites/wp-1583632/wp-includes/class-wp-block.php(586): Automattic\WooCommerce\Blocks\BlockTypes\AbstractBlock->render_callback(Array, '', Object(WP_Block))
#27 /Applications/MAMP/htdocs/woogenerator/sites/wp-1583632/wp-includes/class-wp-block.php(566): WP_Block->render()
#28 /Applications/MAMP/htdocs/woogenerator/sites/wp-1583632/wp-includes/class-wp-block.php(566): WP_Block->render()
#29 /Applications/MAMP/htdocs/woogenerator/sites/wp-1583632/wp-includes/blocks.php(2359): WP_Block->render()
#30 /Applications/MAMP/htdocs/woogenerator/sites/wp-1583632/wp-includes/blocks.php(2431): render_block(Array)
#31 /Applications/MAMP/htdocs/woogenerator/sites/wp-1583632/wp-includes/block-template.php(294): do_blocks('<!-- wp:templat...')
#32 /Applications/MAMP/htdocs/woogenerator/sites/wp-1583632/wp-includes/template-canvas.php(12): get_the_block_template_html()
#33 /Applications/MAMP/htdocs/woogenerator/sites/wp-1583632/wp-includes/template-loader.php(106): include('/Applications/M...')
#34 /Applications/MAMP/htdocs/woogenerator/sites/wp-1583632/wp-blog-header.php(19): require_once('/Applications/M...')
#35 /Applications/MAMP/htdocs/woogenerator/sites/wp-1583632/index.php(17): require('/Applications/M...')
#36 {main}
```

### PR DESCRIPTION
**Pull request by dinhtungdu**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Optimize `ProductImage::render_image()` to avoid unnecessary gallery image calculations when `image_id` is null. Previously, `ProductGalleryUtils::get_all_image_ids()` and `array_merge()` were called even when no specific image ID was provided. Now these operations only execute when `image_id` is provided.

Closes #61955

### Screenshots or screen recordings:

GitHub will automatically download this file and fail due to its size, so I'm removing the protocol here to prevent that. I'm sorry for the inconvenience.

```
cloudup.com/cz2brvjiU6W
```

### How to test the changes in this Pull Request:

1. Add a Product Image block to a product page or product archive.
2. Verify the product image displays correctly.
4. Test with products that have no featured image to ensure placeholder displays correctly.

### Testing that has already taken place:

Tested on a local development environment with products that have featured images, gallery images, and products without images.

### Milestone

- [x] Automatically assign milestone for the **[next WooCommerce version](../blob/trunk/plugins/woocommerce/woocommerce.php#L6)**

> **Note:** Check the box above to have the milestone automatically assigned when merged.
> Alternatively (e.g. for point releases), manually assign the appropriate milestone.

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [x] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 
Optimize ProductImage block to avoid unnecessary gallery image calculations.

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce/src/Blocks/BlockTypes/ProductImage.php [hunk 1]
```diff
@@ -161,9 +161,13 @@ private function render_image( $product, $attributes, $image_id = null ) {
...
-		$provided_image_id_is_valid = $image_id && in_array( $image_id, $available_image_ids, true );
+		$provided_image_id_is_valid = false;
+
+		if ( $image_id ) {
+			$gallery_image_ids          = ProductGalleryUtils::get_all_image_ids( $product );
+			$available_image_ids        = array_merge( [ $featured_image_id ], $gallery_image_ids );
+			$provided_image_id_is_valid = in_array( $image_id, $available_image_ids, true );
+		}
 
 		$target_image_id = $provided_image_id_is_valid ? $image_id : $featured_image_id;
```
Comment (kmanijak) [inline plugins/woocommerce/src/Blocks/BlockTypes/ProductImage.php:172]: Nitpick: I know it's not part of this PR but do you mind reusing `$target_image_id` in line 183, there's exactly the same condition repeated:

```
'data-image-id' => $provided_image_id_is_valid ? $image_id : $featured_image_id,
```

**Review by kmanijak — APPROVED** [review]
Wow, super simple yet powerful improvement! 👏 Thanks for taking care of it! 🙇 

Pre-approving but just noting there's changelog missing!

File: plugins/woocommerce/src/Blocks/BlockTypes/ProductImage.php (hunk 1 above)
Comment (dinhtungdu) [reply plugins/woocommerce/src/Blocks/BlockTypes/ProductImage.php:172]: Sure! I updated this in [af21680](https://github.com/woocommerce/woocommerce/pull/62107/commits/af2168088517f1f2da2832e05ed72218aaef7da4)
