### PR TITLE
Handles errors in fault installations of PHP Intl

### LINKED ISSUE #28516: Fatal error: Uncaught IntlException: Constructor
Per referral from WordPress WooCommerce support forum by @mikejolley; I am reporting this bug issue that has been duplicated is all version 4.6.x and above.

**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
This error is generated consistently with a fresh install both on multi-site and regular WordPress install. I have tried to load the plugin with no other plugin installed and still get the same error. The site returns the following error message in debug mode.  This error is also present in all versions of the app installed on the same server after upgrading to the latest version.

**Expected behavior**
The application should on a fresh install or after update allow normal functionally and be able to navigate all configuration tabs. 

**Actual behavior**
The store's primary settings tab and product tab do not work as expected. The frontend causes the entire site a blank screen when attempting to load until the plugin is disabled.  Even when no other plugin is running the following error is produced.

`
Fatal error: Uncaught IntlException: Constructor failed in /home/userID/domains/iamautumnco.com/public_html/wp-content/plugins/woocommerce/includes/wc-core-functions.php:1799 Stack trace: #0 /home/userID/domains/iamautumnco.com/public_html/wp-content/plugins/woocommerce/includes/wc-core-functions.php(1799): Collator->__construct('en_US') #1 /home/userID/domains/iamautumnco.com/public_html/wp-content/plugins/woocommerce/includes/class-wc-countries.php(53): wc_asort_by_locale(Array) #2 /home/userID/domains/iamautumnco.com/public_html/wp-content/plugins/woocommerce/includes/rest-api/Controllers/Version3/class-wc-rest-data-countries-controller.php(115): WC_Countries->get_countries() #3 /home/userID/domains/iamautumnco.com/public_html/wp-includes/rest-api/class-wp-rest-server.php(1050): WC_REST_Data_Countries_Controller->get_items(Object(WP_REST_Request)) #4 /home/userID/domains/iamautumnco.com/public_html/wp-includes/rest-api.php(464): WP_REST_Server->dispatch(Object(WP_REST_Request)) #5 /home/userID/domains/iamautumnc in /home/userID/domains/iamautumnco.com/public_html/wp-content/plugins/woocommerce/includes/wc-core-functions.php on line 1799`

My site is running on PHP 7.3.24, CentOS. I also found the following errors in my error log file. 

```
[Sun Nov 15 06:35:04.990989 2020] [proxy_fcgi:error] [pid 8331:tid 139783563233024] [client 24.49.43.55:54182] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught IntlException: Constructor failed in /home/userID/truePath/iamautumnco.com/public_html/wp-content/plugins/woocommerce/includes/wc-core-functions.php:1799\nStack trace:\n#0 /home/userID/truePath/iamautumnco.com/public_html/wp-content/plugins/woocommerce/includes/wc-core-functions.php(1799): Collator->__construct('en_US')\n#1 /home/userID/truePath/iamautumnco.com/public_html/wp-content/plugins/woocommerce/includes/class-wc-countries.php(53): wc_asort_by_locale(Array)\n#2 /home/userID/truePath/iamautumnco.com/public_html/wp-content/plugins/woocommerce/includes/class-wc-countries.php(38): WC_Countries->get_countries()\n#3 /home/userID/truePath/iamautumnco.com/public_html/wp-content/plugins/woocommerce/includes/class-wc-countries.php(239): WC_Countries->__get('countries')\n#4 /home/userID/truePath/iamautumnco.com/public_html/wp-content/plugins/woocommerce/includes/wc-core-functions.php(1307): WC_Countries->get_allowed_countries()\n#5 /home/userID/truePath/iamautumnco.co...', referer: https://shop.iamautumnco.com/wp-admin/plugins.php?plugin_status=all&paged=1&s
[Sun Nov 15 06:35:08.640640 2020] [proxy_fcgi:error] [pid 8331:tid 139783563233024] [client 24.49.43.55:54182] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught IntlException: Constructor failed in /home/userID/truePath/iamautumnco.com/public_html/wp-content/plugins/woocommerce/includes/wc-core-functions.php:1799\nStack trace:\n#0 /home/userID/truePath/iamautumnco.com/public_html/wp-content/plugins/woocommerce/includes/wc-core-functions.php(1799): Collator->__construct('en_US')\n#1 /home/userID/truePath/iamautumnco.com/public_html/wp-content/plugins/woocommerce/includes/class-wc-countries.php(53): wc_asort_by_locale(Array)\n#2 /home/userID/truePath/iamautumnco.com/public_html/wp-content/plugins/woocommerce/includes/class-wc-countries.php(38): WC_Countries->get_countries()\n#3 /home/userID/truePath/iamautumnco.com/public_html/wp-content/plugins/woocommerce/includes/class-wc-countries.php(239): WC_Countries->__get('countries')\n#4 /home/userID/truePath/iamautumnco.com/public_html/wp-content/plugins/woocommerce/includes/wc-core-functions.php(1307): WC_Countries->get_allowed_countries()\n#5 /home/userID/truePath/iamautumnco.co...', referer: https://shop.iamautumnco.com/wp-admin/plugins.php?plugin_status=all&paged=1&s
[Sun Nov 15 06:35:23.652241 2020] [proxy_fcgi:error] [pid 8331:tid 139783563233024] [client 24.49.43.55:54200] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught IntlException: Constructor failed in /home/userID/truePath/iamautumnco.com/public_html/wp-content/plugins/woocommerce/includes/wc-core-functions.php:1799\nStack trace:\n#0 /home/userID/truePath/iamautumnco.com/public_html/wp-content/plugins/woocommerce/includes/wc-core-functions.php(1799): Collator->__construct('en_US')\n#1 /home/userID/truePath/iamautumnco.com/public_html/wp-content/plugins/woocommerce/includes/class-wc-countries.php(53): wc_asort_by_locale(Array)\n#2 /home/userID/truePath/iamautumnco.com/public_html/wp-content/plugins/woocommerce/includes/class-wc-countries.php(38): WC_Countries->get_countries()\n#3 /home/userID/truePath/iamautumnco.com/public_html/wp-content/plugins/woocommerce/includes/class-wc-countries.php(239): WC_Countries->__get('countries')\n#4 /home/userID/truePath/iamautumnco.com/public_html/wp-content/plugins/woocommerce/includes/wc-core-functions.php(1307): WC_Countries->get_allowed_countries()\n#5 /home/userID/truePath/iamautumnco.co...', referer: https://shop.iamautumnco.com/wp-admin/plugins.php?plugin_status=all&paged=1&s
[Sun Nov 15 06:35:25.747306 2020] [proxy_fcgi:error] [pid 8331:tid 139783563233024] [client 24.49.43.55:54200] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught IntlException: Constructor failed in /home/userID/truePath/iamautumnco.com/public_html/wp-content/plugins/woocommerce/includes/wc-core-functions.php:1799\nStack trace:\n#0 /home/userID/truePath/iamautumnco.com/public_html/wp-content/plugins/woocommerce/includes/wc-core-functions.php(1799): Collator->__construct('en_US')\n#1 /home/userID/truePath/iamautumnco.com/public_html/wp-content/plugins/woocommerce/includes/class-wc-countries.php(53): wc_asort_by_locale(Array)\n#2 /home/userID/truePath/iamautumnco.com/public_html/wp-content/plugins/woocommerce/includes/class-wc-countries.php(38): WC_Countries->get_countries()\n#3 /home/userID/truePath/iamautumnco.com/public_html/wp-content/plugins/woocommerce/includes/class-wc-countries.php(239): WC_Countries->__get('countries')\n#4 /home/userID/truePath/iamautumnco.com/public_html/wp-content/plugins/woocommerce/includes/wc-core-functions.php(1307): WC_Countries->get_allowed_countries()\n#5 /home/userID/truePath/iamautumnco.co...', referer: https://shop.iamautumnco.com/wp-admin/plugins.php?plugin_status=all&paged=1&s
[Sun Nov 15 06:35:28.540046 2020] [core:error] [pid 8526:tid 139782369593088] [client 24.49.43.55:54207] AH00124: Request exceeded the limit of 10 internal redirects due to probable configuration error. Use 'LimitInternalRecursion' to increase the limit if necessary. Use 'LogLevel debug' to get a backtrace.
[Sun Nov 15 06:35:28.544321 2020] [core:error] [pid 8331:tid 139782134728448] [client 24.49.43.55:54206] AH00124: Request exceeded the limit of 10 internal redirects due to probable configuration error. Use 'LimitInternalRecursion' to increase the limit if necessary. Use 'LogLevel debug' to get a backtrace.
[Sun Nov 15 06:36:05.947661 2020] [access_compat:error] [pid 8331:tid 139782168299264] [client 34.231.33.72:58136] AH01797: client denied by server configuration: /home/userID/truePath/iamautumnco.com/private_html/wp-content/uploads/woocommerce_uploads/, referer: https://iamautumnco.com/wp-content/uploads/woocommerce_uploads/
[Sun Nov 15 06:36:07.445910 2020] [proxy_fcgi:error] [pid 8331:tid 139782780770048] [client 24.49.43.55:54236] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught IntlException: Constructor failed in /home/userID/truePath/iamautumnco.com/public_html/wp-content/plugins/woocommerce/includes/wc-core-functions.php:1799\nStack trace:\n#0 /home/userID/truePath/iamautumnco.com/public_html/wp-content/plugins/woocommerce/includes/wc-core-functions.php(1799): Collator->__construct('en_US')\n#1 /home/userID/truePath/iamautumnco.com/public_html/wp-content/plugins/woocommerce/includes/class-wc-countries.php(53): wc_asort_by_locale(Array)\n#2 /home/userID/truePath/iamautumnco.com/public_html/wp-content/plugins/woocommerce/includes/rest-api/Controllers/Version3/class-wc-rest-data-countries-controller.php(115): WC_Countries->get_countries()\n#3 /home/userID/truePath/iamautumnco.com/public_html/wp-includes/rest-api/class-wp-rest-server.php(1050): WC_REST_Data_Countries_Controller->get_items(Object(WP_REST_Request))\n#4 /home/userID/truePath/iamautumnco.com/public_html/wp-includes/rest-api.php(464): WP_REST_Server->dispatch(Object(WP_REST_Re...', referer: https://iamautumnco.com/wp-admin/plugins.php
```

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Install fresh copy of WordPress
2. Install WooCommerce plugin
3. If no error; Scroll down and make sure the error message is not in lower left corner of plugin iframe; attempt to configure the store.

`Fatal error: Uncaught IntlException: Constructor failed in /home/userID/domains/iamautumnco.com/public_html/wp-content/plugins/woocommerce/includes/wc-core-functions.php:1799 Stack trace: #0 /home/userID/domains/iamautumnco.com/public_html/wp-content/plugins/woocommerce/includes/wc-core-functions.php(1799): Collator->__construct('en_US') #1 /home/userID/domains/iamautumnco.com/public_html/wp-content/plugins/woocommerce/includes/class-wc-countries.php(53): wc_asort_by_locale(Array) #2 /home/userID/domains/iamautumnco.com/public_html/wp-content/plugins/woocommerce/includes/rest-api/Controllers/Version3/class-wc-rest-data-countries-controller.php(115): WC_Countries->get_countries() #3 /home/userID/domains/iamautumnco.com/public_html/wp-includes/rest-api/class-wp-rest-server.php(1050): WC_REST_Data_Countries_Controller->get_items(Object(WP_REST_Request)) #4 /home/userID/domains/iamautumnco.com/public_html/wp-includes/rest-api.php(464): WP_REST_Server->dispatch(Object(WP_REST_Request)) #5 /home/userID/domains/iamautumnc in /home/userID/domains/iamautumnco.com/public_html/wp-content/plugins/woocommerce/includes/wc-core-functions.php on line 1799
`

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
`
### WordPress Environment ###

WordPress address (URL): https://www.homemadedivashop.com
Site address (URL): https://www.homemadedivashop.com
WC Version: 4.7.1
REST API Version: ✔ 4.7.1
WC Blocks Version: ✔ 3.6.0
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.6.3
Log Directory Writable: ✔
WP Version: 5.5.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: –
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2
PHP Version: 7.4.13
PHP Post Max Size: 64 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.73.0
OpenSSL/1.0.2k-fips

SUHOSIN Installed: –
MySQL Version: 5.7.31
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.4.1
WC Database Prefix: wp_
Total Database Size: 21.16MB
Database Data Size: 18.54MB
Database Index Size: 2.62MB
wp_woocommerce_sessions: Data: 2.02MB + Index: 0.08MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mcloud_mux_assets: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mcloud_mux_playback: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mcloud_mux_renditions: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mcloud_task: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mcloud_task_data: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mcloud_task_schedule: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mcloud_task_token: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ms_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 3.02MB + Index: 0.16MB + Engine InnoDB
wp_postmeta: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_posts: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
wp_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfblockediplog: Data: 0.09MB + Index: 0.00MB + Engine InnoDB
wp_wfblocks7: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wfconfig: Data: 2.36MB + Index: 0.00MB + Engine InnoDB
wp_wfcrawlers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wffilechanges: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wffilemods: Data: 5.52MB + Index: 0.00MB + Engine InnoDB
wp_wfhits: Data: 1.02MB + Index: 0.22MB + Engine InnoDB
wp_wfhoover: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfissues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wfknownfilelist: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
wp_wflivetraffichuman: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wflocs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wflogins: Data: 0.38MB + Index: 0.14MB + Engine InnoDB
wp_wfls_2fa_secrets: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfls_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfnotifications: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfpendingissues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wfreversecache: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfsnipcache: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wfstatus: Data: 0.13MB + Index: 0.09MB + Engine InnoDB
wp_wftrafficrates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_yoast_indexable: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_yoast_indexable_hierarchy: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_primary_term: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_yoast_seo_links: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_yoast_seo_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

attachment: 4
custom_css: 1
nav_menu_item: 7
oembed_cache: 1
page: 7
post: 1
revision: 8
wpautoterms_page: 2
wpcf7_contact_form: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (12) ###

WP AutoTerms: by WP AutoTerms – 2.4.3
Child Theme Configurator: by Lilaea Media – 2.5.6
Code Snippets: by Code Snippets Pro – 2.14.0
Contact Form 7: by Takayuki Miyoshi – 5.3.1
Media Cloud: by interfacelab – 4.1.14
Social Feed Gallery: by QuadLayers – 3.1.1
Meta Box: by MetaBox.io – 5.3.5
My Wordpress Login Logo: by Afsal Rahim – 2.3.3
User Role Editor: by Vladimir Garagulya – 4.57
WooCommerce: by Automattic – 4.7.1
Wordfence Security: by Wordfence – 7.4.14
Yoast SEO: by Team Yoast – 15.4

### Inactive Plugins (9) ###

Divi Builder: by Elegant Themes – 4.7.4
Product Feed PRO for WooCommerce: by AdTribes.io – 9.2.4 – Installed version not tested with active version of WooCommerce 4.7.1
ReCaptcha v2 for Contact Form 7: by IQComputing – 1.2.9
Site Kit by Google: by Google – 1.22.0
Strong Testimonials: by MachoThemes – 2.50.3
WooCommerce Google Analytics Integration: by WooCommerce – 1.4.25 – Installed version not tested with active version of WooCommerce 4.7.1
WooCommerce Stripe Gateway: by WooCommerce – 4.5.5 – Installed version not tested with active version of WooCommerce 4.7.1
Woo Invoice: by WebAppick – 3.1.4 – Installed version not tested with active version of WooCommerce 4.7.1
YITH Woocommerce Request A Quote: by YITH – 1.6.0 – Installed version not tested with active version of WooCommerce 4.7.1

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #13 - /shop/
Cart: #14 - /cart/
Checkout: #15 - /checkout/
My account: #16 - /my-account/
Terms and conditions: #23 - /wpautoterms/aup-tc/

### Theme ###

Name: Divi Child Homemade Diva
Version: 3.22.4.1598847898
Author URL: http://www.elegantthemes.com
Child Theme: ✔
Parent Theme Name: Divi
Parent Theme Version: 4.7.4
Parent Theme Author URL: http://www.elegantthemes.com
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Pending: 3
Oldest: 2020-10-26 00:48:03 -0400
Newest: 2020-10-26 01:00:43 -0400

`
All sites installed on this host with this plugin active are broken and load a white page.

### PR DESCRIPTION
**Pull request by claudiosanches**
### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

PHP Collator class from PHP Intl is used to sort country names in the front-end, it works already as a workaround and used only if supported, but we found out that in some installations PHP Intl could be incomplete and not including ICU TZData.

I couldn't find a way to reproduce the error reported in #28516, and since it requires a fix in the server side, I decided to just skip some `IntlException` exception happens, and if `WP_DEBUG` is enabled it will log the exception message and some tips about this error.

Also note that's possible to complete [disable `wc_asort_by_locale()` and replace with custom sorting](https://github.com/woocommerce/woocommerce/blob/20c8cbee0c99e86700d13de9cf7717dba1d60b08/includes/class-wc-countries.php#L44-L58) with:

```php
add_filter( 'woocommerce_sort_countries', '__return_false' );
add_filter( 'woocommerce_countries', 'some_custom_sorting_function' );
```

Closes #28516.

### How to test the changes in this Pull Request:

Sorry but I couldn't reproduce this error.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Fix - Handle errors in fault installations of PHP Intl

### CODE REVIEW

File: includes/wc-core-functions.php [hunk 1]
```diff
@@ -1801,10 +1801,25 @@ function wc_ascii_uasort_comparison( $a, $b ) {
...
-		$collator = new Collator( $locale );
-		$collator->asort( $data, Collator::SORT_STRING );
-		return $data;
+		try {
+			$locale   = $locale ? $locale : get_locale();
+			$collator = new Collator( $locale );
+			$collator->asort( $data, Collator::SORT_STRING );
+			return $data;
+		} catch ( IntlException $e ) {
+			// Just skip if some error got caused.
```
Comment (roykho) [inline includes/wc-core-functions.php:1810]: I see this comment spans multilines, perhaps we could use the coding standards here https://developer.wordpress.org/coding-standards/inline-documentation-standards/php/#5-2-multi-line-comments

File: includes/wc-core-functions.php [hunk 2]
```diff
@@ -1801,10 +1801,25 @@ function wc_ascii_uasort_comparison( $a, $b ) {
...
+			// It may be caused in installations that doesn't include ICU TZData.
+			if ( Constants::is_true( 'WP_DEBUG' ) ) {
+				error_log( // phpcs:ignore WordPress.PHP.DevelopmentFunctions.error_log_error_log
+					sprintf(
+						/* translators: 1: PHP docs link 2: error message */
+						esc_html__( 'An unexpected error occurred while trying to use PHP Intl Collator class, it may be caused by an incorrect installation of PHP Intl and ICU, and could be fixed by reinstallaing PHP Intl, see more details about PHP Intl installation: %1$s. Error message: %2$s', 'woocommerce' ),
```
Comment (roykho) [inline includes/wc-core-functions.php:1816]: Do we want to use `esc_html` here? Otherwise the error log may show things like `&lt;div&gt;&lt;p&gt;This is an error message&lt;/p&gt;&lt;/div&gt;` which makes it hard to read. Maybe use `wp_strip_all_tags` instead?

**Review by roykho — COMMENTED** [review]
Just left some small comments, otherwise it seems to make sense.

File: includes/wc-core-functions.php (hunk 2 above)
Comment (claudiosanches) [reply includes/wc-core-functions.php:1816]: We don't need escaping here, since we print into the error file. I'll remove it, thanks!

File: includes/wc-core-functions.php [hunk 3]
```diff
@@ -1801,10 +1801,27 @@ function wc_ascii_uasort_comparison( $a, $b ) {
...
+		} catch ( IntlException $e ) {
+			/*
+			 * Just skip if some error got caused.
+			 * It may be caused in installations that doesn't include ICU TZData.
+			 */
+			if ( Constants::is_true( 'WP_DEBUG' ) ) {
+				error_log( // phpcs:ignore WordPress.PHP.DevelopmentFunctions.error_log_error_log
+					sprintf(
+						/* translators: 1: PHP docs link 2: error message */
+						__( 'An unexpected error occurred while trying to use PHP Intl Collator class, it may be caused by an incorrect installation of PHP Intl and ICU, and could be fixed by reinstallaing PHP Intl, see more details about PHP Intl installation: %1$s. Error message: %2$s', 'woocommerce' ),
```
Comment (roykho) [inline includes/wc-core-functions.php:1818]: So since we're using a translate function here, it is still good idea to sanitize. We could use `wc_clean` in this case.

Comment (claudiosanches) [reply includes/wc-core-functions.php]: Good catch, I'm removing this translate function since in other places we use `error_log` doesn't include any translate function. Thanks!

**Review by roykho — APPROVED** [review]
LGTM!
