### PR TITLE
Fixed how to flush rewrite rules after save the shop main page

### LINKED ISSUE #14452: Shop Page slug Name change
After changing the slugname of the shop page which already has been set as the shop page in the woo display settings that page will not list or show any products.

Even when changing temporarily the shop page in the woo settings to another page, save the settings and set it back to the shop page with the changed slugname that page will never show any products.
One has to create a new shop page and set that page as the shop page in order to get the products back in the shop.

Looks like a bug to me.

### PR DESCRIPTION
**Pull request by claudiosanches**
Fixes #14452

### CODE REVIEW

File: includes/wc-core-functions.php [hunk 1]
```diff
@@ -793,13 +793,25 @@ function wc_get_page_children( $page_id ) {
 /**
  * Flushes rewrite rules when the shop page (or it's children) gets saved.
  */
-function flush_rewrite_rules_on_shop_page_save( $post_id ) {
+function flush_rewrite_rules_on_shop_page_save() {
+	// Check if is in edit page.
+	if ( 'page' !== get_current_screen()->id ) {
```
Comment (mikejolley) [inline includes/wc-core-functions.php]: Check `get_current_screen()` is an object first; this has caused errors in the past.

File: includes/wc-core-functions.php [hunk 2]
```diff
@@ -793,13 +793,25 @@ function wc_get_page_children( $page_id ) {
 /**
  * Flushes rewrite rules when the shop page (or it's children) gets saved.
  */
-function flush_rewrite_rules_on_shop_page_save( $post_id ) {
+function flush_rewrite_rules_on_shop_page_save() {
+	// Check if is in edit page.
```
Comment (mikejolley) [inline includes/wc-core-functions.php]: Check if this is the edit page.

**Review by mikejolley — CHANGES_REQUESTED** [review]

File: includes/wc-core-functions.php [hunk 3]
```diff
@@ -793,13 +793,25 @@ function wc_get_page_children( $page_id ) {
...
+	if ( 'page' !== get_current_screen()->id ) {
+		return;
+	}
+
+	// Check if page is edited.
```
Comment (mikejolley) [inline includes/wc-core-functions.php]: Check if the page is being edited.

**Review by mikejolley — CHANGES_REQUESTED** [review]
