### PR TITLE
Fix bg color that was not covering the full page

### LINKED ISSUE #35298: [Fix] partial background color in the new product mangement experience.
AC

- [ ] The gray background must cover the entere content of the page without considering the left menu and the top bar.

Image

### PR DESCRIPTION
**Pull request by mdperez86**
### All Submissions:

-   [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
-   [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
-   [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes https://github.com/woocommerce/woocommerce/issues/35298.

- [ ] This PR is a very minor change/addition and does not require testing instructions (if checked you can ignore/remove the next section).

### How to test the changes in this Pull Request:

1. Go to the Add New (MVP) product page
2. The gray background should cover the full screen

### Other information:

-   [x] Have you added an explanation of what your changes do and why you'd like us to include them?
-   [ ] Have you written new tests for your changes, as applicable?
-   [x] Have you created a changelog file for each project being changed, ie `pnpm --filter=<project> changelog add`?

### FOR PR REVIEWER ONLY:

-   [x] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

File: plugins/woocommerce/src/Admin/Features/NewProductManagementExperience.php [hunk 1]
```diff
@@ -16,14 +17,17 @@ class NewProductManagementExperience {
...
-		add_action( 'admin_init', array( $this, 'enqueue_styles' ) );
+		add_action( 'admin_enqueue_scripts', array( $this, 'enqueue_styles' ) );
 	}
 
 	/**
 	 * Enqueue styles needed for the rich text editor.
 	 */
 	public function enqueue_styles() {
-		wp_enqueue_style( 'wp-edit-post' );
+		if ( ! PageController::is_admin_or_embed_page() ) {
```
Comment (joshuatf) [inline plugins/woocommerce/src/Admin/Features/NewProductManagementExperience.php:27]: Thanks for adding this 🙏

**Review by joshuatf — APPROVED** [review]
I wasn't able to reproduce the original issue, but the changes here look good and make sense to me.  @AnnaMag do you want to give this a quick check since it looks like you were able to reproduce the original issue?

Otherwise LGTM!
