### PR TITLE
Fix the REST API entry point to add coupons to an order.

### LINKED ISSUE #27290: [API] PUT /orders with incorrect coupon format removes coupons
**Describe the bug**
When using the API to update (`PUT`) an order, sending back the 'coupon_lines' we got from the API during the`GET` call removes all set coupons on the order. 

The (API documentation)[https://woocommerce.github.io/woocommerce-rest-api-docs/#update-an-order] doesn't specify this behaviour, or the correct way to deliver the `coupon_line` property.

**To Reproduce**
1. Create a coupon.
2. Create an order using the coupon using the store or admin interface (note, coupon has been correctly added to the order).
3. `GET` the order via the API.
4. `PUT` the response from the `GET` via the API.
5. Note the coupon has disappeared in the admin interface, and totals have been recalculated.

**Expected behavior**
I expect the coupon to remain on the order. Otherwise I would expect the API to error (`400 Bad Request`). Or the current behaviour to be documented, with the correct format to update/change `coupon_lines` added.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
N/A

### PR DESCRIPTION
**Pull request by Konamiman**
### All Submissions:

* [ ] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
* [ ] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

After https://github.com/woocommerce/woocommerce/pull/29146 is applied a request for updating the coupons for an order having an invalid input does indeed return a proper error, but the previously existing coupons are still removed from the order. This happens because the existing coupons are removed first, and then the input validation happens.

This PR fixes that:

* Checks that the coupon data in the input has no `id` field and has a `code` field _before_ removing the existing coupons.
* Additionally, a new check is added: the coupon must be valid itself (valid code, not expired, etc); this also happens before the input validation happens.

Also, a couple of redundant checks are removed (is `coupon_lines` and array? Does it contain arrays only?); these cases are already verified by the REST API engine by looking at the schema.

Closes #27290 (again).

### How to test the changes in this Pull Request:

1. Temporarily add this at the ned of your woocommerce.php file, this way you won't have to bother about REST API authentication: `add_filter('woocommerce_rest_check_permissions', function() {return true;}, 10, 0 );` (note that this will cause a bunch of unit tests to fail)
2. Have the id of an order with no coupons and in "Pending payment" status at hand.
3. Try to add an invalid coupon (has `id`, has no `code`, bad coupon code, malformed input) via REST API, verify that in all cases you gent a proper 400 error and the order still doesn't have any coupon applied:

```bash
curl -X PUT "http://localhost/wp-json/wc/v3/orders/<order id>" -H "Content-Type: application/json" -d '{ "coupon_lines": [{ "id": 1234, "code": "the-coupon" }] }'
curl -X PUT "http://localhost/wp-json/wc/v3/orders/<order id>" -H "Content-Type: application/json" -d '{ "coupon_lines": [{ "discount": "30" }] }'
curl -X PUT "http://localhost/wp-json/wc/v3/orders/<order id>" -H "Content-Type: application/json" -d '{ "coupon_lines": [{ "code": "BAD-COUPON-CODE" }] }'
curl -X PUT "http://localhost/wp-json/wc/v3/orders/<order id>" -H "Content-Type: application/json" -d '{ "coupon_lines": "NOT-AN-ARRAY" }'
```

4. Manually add a coupon to the order (via order details in admin), repeat the above invalid requests and verify that the coupon has not been removed from the order.

5. Do a valid request to add a different coupon and verify that it replaces the coupon you had previously added:

```bash
curl -X PUT "http://localhost:8034/wp-json/wc/v3/orders/<order id>" -H "Content-Type: application/json" -d '{ "coupon_lines": [{ "code": "another-coupon"}] }'
```

### Other information:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully run tests with your changes locally?

### Changelog entry

> Fix - Don't remove existing coupons from order when an invalid REST API request for updating coupons is submitted

### CODE REVIEW

File: includes/rest-api/Controllers/Version3/class-wc-rest-orders-controller.php [hunk 1]
```diff
@@ -34,30 +34,45 @@ class WC_REST_Orders_Controller extends WC_REST_Orders_V2_Controller {
...
-					throw new WC_REST_Exception( 'woocommerce_rest_invalid_coupon', __( 'Coupon code is required.', 'woocommerce' ), 400 );
-				}
+			if ( empty( $item['code'] ) ) {
+				throw new WC_REST_Exception( 'woocommerce_rest_invalid_coupon', __( 'Coupon code is required.', 'woocommerce' ), 400 );
+			}
 
-				$results = $order->apply_coupon( wc_clean( $item['code'] ) );
+			$coupon_code  = wc_format_coupon_code( wc_clean( $item['code'] ) );
+			$coupon       = new WC_Coupon( $coupon_code );
+			$check_result = $discounts->is_coupon_valid( $coupon );
```
Comment (vedanshujain) [inline includes/rest-api/Controllers/Version3/class-wc-rest-orders-controller.php:57]: so this check here has an unintended side effect, which is that `is_coupon_valid` also checks for the coupon limits usage.

this means that if I have a coupon already applied to the order, whose limit is already been reached, and try to apply it again using the REST API, it will throw an error. this is a bit different from earlier behavior where we did allow sending the same coupon which is already applied with limit exhausted. it worked earlier because we would remove the coupon, which adds back the limit, and then apply it back again.

i think we should exclude the already applied coupon from this check to make it compatible with existing behavior. wdyt?

**Review by vedanshujain — CHANGES_REQUESTED** [review]
Looks good and great work in adding the unit tests. Requesting changes for an edge case I noticed.

File: includes/rest-api/Controllers/Version3/class-wc-rest-orders-controller.php [hunk 2]
```diff
@@ -34,31 +34,58 @@ class WC_REST_Orders_Controller extends WC_REST_Orders_V2_Controller {
...
+		}
+
+		// Remove all coupons first to ensure calculation is correct.
+		foreach ( $order->get_items( 'coupon' ) as $existing_coupon ) {
+			$order->remove_coupon( $existing_coupon->get_code() );
+		}
+
+		// Apply the coupons.
+		foreach ( $coupons as $new_coupon ) {
+			$results = $order->apply_coupon( $new_coupon );
```
Comment (vedanshujain) [inline includes/rest-api/Controllers/Version3/class-wc-rest-orders-controller.php:84]: looks like sending `new_coupon` object is causing a cache invalidation problem because props like `usage_count` etc are not refreshed even if they are changed decreased in line 79. 

we should instead send `new_coupon->get_code()` like before to force a refresh from DB.

Comment (Konamiman) [reply includes/rest-api/Controllers/Version3/class-wc-rest-orders-controller.php:84]: Done!

**Comment by Konamiman** [comment]
I'm merging for RC.1 since it seems to work as it should now, if more issues are found they can be fixed in a RC.2 or in the final release.
