### PR TITLE
Restore stock_status in V3 response.

### LINKED ISSUE #28729: stock_status JSON field gone from Products data at Woo 4.9.0
**Prerequisites (mark completed items with an [x]):**
- [X] I have have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
When using the Jetpack Rest API Tunnel to request Products data through the `wc/v3/products` using a Woo site with the `4.9.0` version all Products JSON response now returns without the `stock_status` data field from the entire payload, as it is right now this is affecting the UI experience from both Android and iOS apps.

**Expected behavior**
The Products JSON data should describe the Stock status through the `stock_status` field

**Actual behavior**
All Products JSON data comes without any `stock_status` field or relatable information

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Make a `GET` request to `wc/v3/products` using the Jetpack Rest API Tunnel
2. Verify that the list returned at least one product
3. Verify that the `stock_status` JSON value is gone from the response

**Screenshots**
Screen Shot 2021-01-06 at 1 39 34 AM

**Isolating the problem (mark completed items with an [x]):**
- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
`
### WordPress Environment ###

WordPress address (URL): https://thomazlowerwoo.mystagingwebsite.com
Site address (URL): https://thomazlowerwoo.mystagingwebsite.com
WC Version: 4.9.0
REST API Version: ✔ 4.9.0
WC Blocks Version: ✔ 4.0.0
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.8.2
Log Directory Writable: ✔
WP Version: 5.6
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 7.3.25
PHP Post Max Size: 2 GB
PHP Time Limit: 1200
PHP Max Input Vars: 6144
cURL Version: 7.73.0
OpenSSL/1.1.1d

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.3.23-MariaDB-log
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.9.0
WC Database Prefix: wp_
Total Database Size: 3.57MB
Database Data Size: 2.08MB
Database Index Size: 1.49MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 1.08MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.14MB + Index: 0.11MB + Engine InnoDB
wp_posts: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 29
page: 6
post: 1
product: 20
product_variation: 7
shop_order: 10

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (7) ###

Akismet Anti-Spam: by Automattic – 4.1.7
WCS staging: by mb – 1.0
Jetpack by WordPress.com: by Automattic – 9.2.1
WooCommerce Beta Tester: by WooCommerce – 2.0.1 – Installed version not tested with active version of WooCommerce 4.0
WooCommerce Stripe Gateway: by WooCommerce – 4.5.0
WooCommerce Shipping & Tax: by Automattic – 1.25.0 (update to version 1.25.4 is available)
WooCommerce: by Automattic – 4.9.0-rc.1

### Inactive Plugins (2) ###

WooCommerce Admin: by WooCommerce – 1.2.4
WP Downgrade | Specific Core Version: by Reisetiger – 1.2.1

### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
object-cache.php: Memcached

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #5 - /shop/
Cart: #6 - /cart/
Checkout: #7 - /checkout/
My account: #8 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 2.5.7 (update to version 3.1.0 is available)
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 6
Oldest: 2020-12-08 23:12:17 +0000
Newest: 2021-01-05 17:23:44 +0000

Pending: 1
Oldest: 2021-01-06 15:42:28 +0000
Newest: 2021-01-06 15:42:28 +0000

`
```
</details>

### PR DESCRIPTION
**Pull request by vedanshujain**
### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Field `stock_status` is special in that [it's computed using another field `in_stock`](https://github.com/woocommerce/woocommerce/blob/master/includes/rest-api/Controllers/Version3/class-wc-rest-products-controller.php#L1380) (present in V2 API). When we added the performance enhancements to fetch only what was requested, this field got skipped because `in_stock` was never going to be asked by V3 schema (since it was specific to V2), and without in_stock, stock_status can't be computed.

Quite similarly, in Orders V3, `_gmt` dates fields depends upon their usual without `_gmt` fields, and cannot be computed unless their original fields are present.

Also returns refund by default even when empty for consistency with earlier versions.  

Additionally, this PR also adds intensive tests for V2 and V3 orders and products endpoint, to verify that all expected fields are returned, and all expected fields return when they are the only field fetched in the response.

Closes #28729.

### How to test the changes in this Pull Request:

1. Fetch product response in API V3
2. Make sure the field `stock_status` is present.
3. Fetch any order using API and with param `_fields=date_created_gmt`. Make sure that this field is returned.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Fix - Restore `stock_status` in V3 response.

### CODE REVIEW

**Comment by vedanshujain** [comment]
Actually, UTs are failing, taking a look.

**Comment by vedanshujain** [comment]
> Actually, UTs are failing, taking a look.


Should be fixed now.

File: tests/php/includes/rest-api/Controllers/Version3/class-wc-rest-producs-controller-tests.php [hunk 1]
```diff
@@ -1,24 +0,0 @@
-<?php
```
Comment (vedanshujain) [inline tests/php/includes/rest-api/Controllers/Version3/class-wc-rest-producs-controller-tests.php:1]: this files is renamed to fix the typo in file name - `producs` to `products`. More tests are added to git is reading it as deleted file.

File: includes/rest-api/Controllers/Version2/class-wc-rest-orders-v2-controller.php [hunk 2]
```diff
@@ -260,13 +260,28 @@ protected function get_formatted_item_data( $order ) {
...
 
 		// Only fetch fields that we need.
-		$fields            = $this->get_fields_for_response( $this->request );
+		$fields = $this->get_fields_for_response( $this->request );
+		foreach ( $dependent_fields as $field_key => $dependency ) {
+			if ( in_array( $field_key, $fields ) && ! in_array( $dependency, $fields ) ) {
+				$fields[] = $dependency;
+			}
+		}
+
```
Comment (peterfabian) [inline includes/rest-api/Controllers/Version2/class-wc-rest-orders-v2-controller.php:280]: I'm slightly confused here. Even without this code that you added, I still see the `date_created_gmt` in the response in master branch. Am I doing it wrong?

**Review by peterfabian — COMMENTED** [review]
> `_gmt ` fields cannot be computed unless their original fields are present.

Is that so? It seems to me both date fields are fetched via `$data = $order->get_base_data();` in https://github.com/woocommerce/woocommerce/blob/master/includes/rest-api/Controllers/Version2/class-wc-rest-orders-v2-controller.php#L272

File: includes/rest-api/Controllers/Version2/class-wc-rest-orders-v2-controller.php (hunk 2 above)
Comment (peterfabian) [reply includes/rest-api/Controllers/Version2/class-wc-rest-orders-v2-controller.php:280]: As @vedanshujain explained to me in slack, this only becomes a problem if the field is explicitly specified using the `_fields` parameter.

**Comment by peterfabian** [comment]
Thanks for adding the explicit tests, great job!

**Comment by peterfabian** [comment]
One more q: are the changes with `_fields` in 4.9 specific to only Orders and Products? Just double checking if we don't need to check other endpoints as well.

File: includes/rest-api/Controllers/Version2/class-wc-rest-products-v2-controller.php [hunk 3]
```diff
@@ -753,6 +753,7 @@ protected function get_product_data( $product, $context = 'view' ) {
 				case 'stock_quantity':
 					$base_data['stock_quantity'] = $product->get_stock_quantity( $context );
 					break;
+				case 'stock_status': // For API V3, this field is computed using `in_stock`.
```
[the remark this answers is not in the document]
Comment (vedanshujain) [reply includes/rest-api/Controllers/Version2/class-wc-rest-products-v2-controller.php]: I tried to address this somewhat in https://github.com/woocommerce/woocommerce/pull/28731/commits/27b22d3aaa45e360e736d88ab4b0b6bc557ec433, although I can't help but feel that there is an underlying architecture issue that we would need to eventually solve.

File: includes/rest-api/Controllers/Version2/class-wc-rest-orders-v2-controller.php (hunk 2 above)
Comment (vedanshujain) [reply includes/rest-api/Controllers/Version2/class-wc-rest-orders-v2-controller.php:280]: Turns out even `date_created_gmt` and `date_modified_gmt` are also dependencies because even though they are stored in post table, they are not part of $order->get_base_data(), and I think changing order class code is out of scope for this bug fix PR. So I have kept these changes as it is.

**Comment by vedanshujain** [comment]
> One more q: are the changes with _fields in 4.9 specific to only Orders and Products? Just double checking if we don't need to check other endpoints as well.

So these are coming from performance enhancement fixes, specifically the one where we try to read only what is required from the database. Since this enhancement is only limited to orders and products, I don't think anything else will be affected.

**Review by peterfabian — APPROVED** [review]
LGTM now, thanks for making the changes!
