### PR TITLE
Fix: Support keyboard navigation in iAPI minicart

### LINKED ISSUE #61792: iAPI MiniCart - Keyboard navigation could be improved
Rigth now, the keyboard navigation in the iAPI minicart feels a bit broken. These are some scenarios I would expect to work, and they aren't in the existing implementation:

* When opening the minicart, it should probably focus on the first element.
* It should trap the focus so the user always remains inside the minicart while tabbing until it is closed.
* It should be possible to close the minicart when the "Escape" key is pressed.
* It should focus the minicart button when it is closed.

### PR DESCRIPTION
**Pull request by SantosGuillamot**
Co-authored by @DAreRodz 

### Changes proposed in this Pull Request:

In this pull request, we are improving the keyboard navigation in the minicart:
- When opened, it focus on the first element.
- It traps focus in the minicart so user always remains inside it while tabbing.
- It closes the minicart when the "Escape" key is pressed.
- It focuses the minicart button when it is closed.

We also took the opportunity to move `openDrawer`, `closeDrawer`, and `overlayCloseDrawer` to `actions` instead of `callbacks` because I think they should belong there.

Closes #61792

### How to test the changes in this Pull Request:

Navigate with the keyboard and check everything works as expected.

1. Open the minicart.
2. Check that the first focusable element is focused.
3. Navigate to the last focusable element and check that after tabbing it goes to the first element instead of outside of the overlay.
4. Shift-tab when focused on the first element should go to the last focusable element instead of outside of the minicart.
5. Click "Esc" and it should close the minicart and focus on the button.

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message Fix keyboard navigation in iAPI minicart

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

**Review by samueljseay — APPROVED** [review]
Thanks for this improvement! The code looks good and it tests well.

Tab trapping is a bit weird in Safari, but I will note that while you're focussed within an element of the mini cart that `Escape` key works to close the mini cart. This is overall an improvement, and I think at least this can be closed: https://github.com/woocommerce/woocommerce/issues/51132 ?

**Comment by straku** [comment]
In my testing I am experiencing the focus going to elements not visible on the screen after what appears to be the last interactive element in the mini cart. It looks like the content of the cart is repeated below the current one? Do you know what might be wrong in my setup to experience this behavior?  Screen recording below: I've added some logging of the currently focused element. The only thing I do in the video is click "Tab". You will see it going off-screen after navigating from the "Go to checkout" button.

https://github.com/user-attachments/assets/990e0dc6-0c64-4c29-ac70-ecc952a45970

**Comment by samueljseay** [comment]
I saw the same behaviour as @straku but only could repro in Safari

**Comment by straku** [comment]
@samueljseay Chrome for me; I am using a dev release channel for testing.

**Comment by SantosGuillamot** [comment]
> Tab trapping is a bit weird in Safari

I've been testing this, and tabbing in Safari is different because by default it only focuses on form controls. Not only in WordPress but in any page. So tabbing is just different in Safari. It can be changed if you go to Safari->Settings->Advanced->Press Tab to highlight each item on a webpage.

If I do that, the tab trapping seems to work fine on my end.

> It looks like the content of the cart is repeated below the current one? Do you know what might be wrong in my setup to experience this behavior?

I've been trying to replicate this, but I haven't been able. Neither in Safari, Chrome, or Chrome Dev. Is the content repeated in `trunk` as well or only in this pull request? Maybe you have two minicarts somehow?

**Comment by straku** [comment]
> Is the content repeated in `trunk` as well or only in this pull request? Maybe you have two minicarts somehow?

There's only one mini-cart on the page, but I found the reason: the contents of the mini-cart template part are duplicated. I am pretty sure I didn't do it on my own. Any ideas of what could've caused it?

File: plugins/woocommerce/client/blocks/assets/js/blocks/mini-cart/iapi-frontend.ts [hunk 1]
```diff
@@ -215,6 +239,62 @@ store< MiniCart >(
...
+			handleOverlayKeydown: withSyncEvent( ( e: KeyboardEvent ) => {
+				if ( state.isOpen ) {
+					if ( e.key === 'Escape' ) {
+						miniCartActions.closeDrawer();
+					}
+
+					// Trap focus if it is an overlay (main menu).
+					if ( e.key === 'Tab' ) {
+						const { ref } = getElement();
+						const focusableElements = getFocusableElements( ref );
```
Comment (straku) [inline plugins/woocommerce/client/blocks/assets/js/blocks/mini-cart/iapi-frontend.ts:272]: Do we have to do it on every keydown? Can we store/cache the list somewhere?

Comment (SantosGuillamot) [reply plugins/woocommerce/client/blocks/assets/js/blocks/mini-cart/iapi-frontend.ts:272]: > Do we have to do it on every keydown? Can we store/cache the list somewhere?

I guess we could try to do it. The problem I see is that I am not sure when this "cache" should be refreshed. As the minicart is interactive, focusable elements might change. For example, when adding or removing items from the cart. We could refresh the cache when the items change, but maybe there are extensions or blocks doing other things that could change the focusable elements (For example, adding a dropdown in the minicart). I thought doing it per keydown was safer and `querySelectorAll` shouldn't be too costly, but I'd love to know other opinions.

Comment (luisherranz) [reply plugins/woocommerce/client/blocks/assets/js/blocks/mini-cart/iapi-frontend.ts:272]: Yes, caching might give us problems when there are extensions that we don't control that might be adding or removing their own elements. For now, I'd leave it like this.

Comment (straku) [reply plugins/woocommerce/client/blocks/assets/js/blocks/mini-cart/iapi-frontend.ts:272]: Makes sense! All mechanisms that I could think of to update the cache seem more problematic/error-prone vs. what is implemented here. Thanks for giving it a thought, though. Let me resolve the thread.

**Review by straku — APPROVED** [review]
Works as expected 👍  The problem that I am experiencing [here](https://github.com/woocommerce/woocommerce/pull/61716#issuecomment-3473520814) is not caused by this PR; it happens to me on trunk too.

**Comment by SantosGuillamot** [comment]
> Any ideas of what could've caused it?

Sorry I missed this one. I have no idea why it could happen. If it happens consistently, maybe it is worth creating a new issue. Thanks a lot for the review!
