### PR TITLE
Accessibility enhancement for the whole shop accounts section

### LINKED ISSUE #43635: Accessibility: Error message on My Account edit address page not announced to screen reader users
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

On the My Account page, if there is an error submitting the form, the page refreshes rather than submitting the form with ajax, and there is a visual error message but screen reader users are loaded at the top of the page and do not hear the message.
Screenshot of form error message

### Expected behavior

When a form error is present, there should be an auditory message for screen reader users to know that there was an error.

You can either do this by:
A) When the page reloads, set keyboard focus on the error message so it is read out. OR
B) Add an [aria-live](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-live) region on the status message and trigger it after the page loads.

You may also consider changing this form to submit with ajax so screen reader users are not sent to the top of the page as happens with a refresh.

### Actual behavior

Screen reader users don't easily know when a an error occurs.

### Steps to reproduce

1. Turn on a screen reader such as VoiceOver or NVDA.
2. Go to the My Account > Addresses page.
3. Click edit on one of the addresses.
4. Leave at least one required field blank and submit the form.
5. Listen as the page reloads and observe there's no announcement about the error.

### WordPress Environment

N/A

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### LINKED ISSUE #43636: Accessibility: Success messages on forms on My Account pages not announced to screen reader users
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

On the My Account pages, when submitting forms (edit address, account details), the page refreshes rather than submitting the form with ajax. There is a visual error message, but screen reader users are loaded at the top of the page and do not hear the message.
Screenshot 2024-01-14 at 10 57 45 PM

This is likely connected to https://github.com/woocommerce/woocommerce/issues/43635

### Expected behavior

When a form error is present, there should be an auditory message for screen reader users to know that the form submitted successfully.

You can either do this by:
A) When the page reloads, set keyboard focus on the status message so it is read out. OR
B) Add an [aria-live](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-live) region on the status message and trigger it after the page loads.

You may also consider changing this form to submit with ajax, so screen reader users are not sent to the top of the page as happens with a refresh.

### Actual behavior

Screen reader users don't easily know if teh form submitted successfully.

### Steps to reproduce

1. Turn on a screen reader such as VoiceOver or NVDA.
2. Go to the My Account > Account details page.
3. Edit something in your account information and submit the form.
5. Listen as the page reloads and observe there's no announcement about the success.

### WordPress Environment

N/A

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### LINKED ISSUE #43659: Accessibility: Error message on login page not announced to screen reader users
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

On the login form on the My Account Page, error messages are not announced to screen reader users, though they appear visually on the page.
Error message above login form.

The page refreshes rather than submitting the form with ajax, and there is a visual error message but due to the refresh screen reader users are loaded at the top of the page and do not hear the message.

Form code: 
https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/templates/global/form-login.php

This is likely related to https://github.com/woocommerce/woocommerce/issues/43635

### Expected behavior

When a form error is present, there should be an auditory message for screen reader users to know that there was an error.

You can either do this by:
A) When the page reloads, set keyboard focus on the error message so it is read out. OR
B) Add an [aria-live](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-live) region on the status message and trigger it after the page loads.

You may also consider changing this form to submit with ajax so screen reader users are not sent to the top of the page as happens with a refresh.

### Actual behavior

Screen reader users don't easily know when a an error occurs.

### Steps to reproduce

1. Turn on a screen reader such as VoiceOver or NVDA.
2. Go to the My Account page while logged out to see the login form.
3. Leave at least one required field blank and submit the form.
5. Listen as the page reloads and observe there's no announcement about the error.

### WordPress Environment

N/A

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### LINKED ISSUE #46559: Accessibility: Error messages on Lost Password form not announced to screen readers
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

On the password reset form if the form is submitted without filling in a username and password, there is a visible error "Enter a username or email address." that is not announced to screen reader users.
Screenshot error message

This is related to https://github.com/woocommerce/woocommerce/issues/43659 and https://github.com/woocommerce/woocommerce/issues/43635

Essentially, though this element has a role="alert" on it, it's not announced because the alert role is only intended for dynamic elements, and this form does not submit or validate dynamically, only on page load. 

The alert role is not read out on page load only on dynamic elements. [Read more on Mozilla Developer Docs ](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/alert_role)

### Expected behavior

When a form error is present, there should be an auditory message for screen reader users to know that there was an error.

You can either do this by:
A) When the page reloads, set keyboard focus on the error message so it is read out. OR
B) Add an [aria-live](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-live) region on the status message and trigger it **after** the page loads.

You may also consider changing this form to submit with ajax so screen reader users are not sent to the top of the page as happens with a refresh and the existing alert is announced.

### Actual behavior

The error is not announced by the screen reader.

### Steps to reproduce

1. Turn on a screen reader such as VoiceOver or NVDA.
2. Go to the Lost Password page (/my-account/lost-password).
3. Do not fill in the username or email address field, but submit the form.
4. Listen as the page reloads and observe there's no announcement about the error.

### WordPress Environment

N/A

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by naman03malhotra**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

If you the above steps in `trunk` the voice ready will not read out the errors.

### Changes proposed in this Pull Request:

This PR solves the Accessibility issues for the whole shop accounts section and closes several issues reported by the Author.

- As part of the fix I wrote a script that focus on the message if a notice is present for both error and failures after the full page reload.
- Since this only affects the accounts section for now, so I am loading the script only on that route.

Closes #43635 , #43659 , #43636 , https://github.com/woocommerce/woocommerce/issues/46559

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Use the Safari browser for this testing if you are on a Mac or Chrome for Windows.
2. Visit `accounts` section of the shop.
3. Make sure you are logged out.
4. Enable Voice reader (On Mac, press `CMD + F5`). There must be other keys for other OS.
5. Now try to log in without entering the username or password.
6. The reader should read out the error message completely.
7. Next -> The voice reader should read out the error or success message in the following scenarios. 
8. Registering a new account without an email ID or the wrong email ID.
9. Not submitting the email or username on the forgot password page should read out the error.
10. Changing account details after login in the account section, try submitting the form without any data, voice reader should read out multiple errors.
11. Changing the account details with correct data should read out the success message.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce/client/legacy/js/frontend/account-i18n.js [hunk 1]
```diff
@@ -0,0 +1,11 @@
+/* global Cookies */
+jQuery( function( $ ) {
```
Comment (naman03malhotra) [inline plugins/woocommerce/client/legacy/js/frontend/account-i18n.js:2]: I am tempted to use the native ES6, instead jQuery here. However, I would like to double-check the browser compact we offer with WooCommerce before doing so.

Comment (naman03malhotra) [reply plugins/woocommerce/client/legacy/js/frontend/account-i18n.js:2]: Here is the native JS alternative:

```js
document.addEventListener('DOMContentLoaded', function() {
    // Select all elements with the class 'wc-block-components-notice-banner'
    const notices = Array.from(document.querySelectorAll('.wc-block-components-notice-banner')).filter(el => {
        // Filter elements that contain text
        return el.textContent.trim().length > 0;
    });

    // Focus on the first element if any are found
    if (notices.length > 0) {
        notices[0].setAttribute('tabindex', '-1');
        notices[0].focus();
    }
});
```

File: plugins/woocommerce/templates/block-notices/error.php [hunk 2]
```diff
@@ -27,7 +27,7 @@
 
 ?>
 
-<div class="wc-block-components-notice-banner is-error" role="alert" <?php echo $multiple ? '' : wc_get_notice_data_attr( $notices[0] ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped ?>>
```
Comment (jorgeatorres) [inline plugins/woocommerce/templates/block-notices/error.php]: Why are we removing the `role="alert"` attribute here? Most (or all?) of the `block-notices` templates have that, so I guess there must be a reason or at least we should revaluate for consistency.

**Review by jorgeatorres — CHANGES_REQUESTED** [review]
Hi @naman03malhotra!

Thanks for picking this up. This seems to be working correctly for block themes, but not for other themes (such as Storefront).
The notices look different (and have different markup) in those:

Screenshot 2024-05-08 at 17 55 02

Also, I wonder if there was a different way to solve this that was more "generic" than adding a script specifically for the accounts page. Not that I'm against that, but similar behavior (though not identical) is implemented in the checkout blocks, for example, when after an error the page scrolls to the notice (though IMHO it doesn't obtain the focus). And I can see this being necessary in other places.

It'd be good to ask Ghidorah for some feedback. What to do you think?

**Comment by naman03malhotra** [comment]
>This seems to be working correctly for block themes, but not for other themes (such as Storefront).

Thanks for the detailed review @jorgeatorres,  great catch! I've made the changes so that it works on both types of themes.

>Also, I wonder if there was a different way to solve this that was more "generic" than adding a script specifically for the accounts page. Not that I'm against that, but similar behavior (though not identical) is implemented in the checkout blocks, for example, when after an error the page scrolls to the notice

Good point, so I checked how that works. Actually, they are submitting the form for placing an order using an Ajax call and then updating an `aria-live` region dynamically using JS, while here we are doing a full page reload. So, the most reliable way I found to grab the screen reader's attention after a full page reload was to bring the alert element in focus.

File: plugins/woocommerce/templates/block-notices/error.php (hunk 2 above)
Comment (naman03malhotra) [reply plugins/woocommerce/templates/block-notices/error.php]: >Why are we removing the role="alert" attribute here? Most (or all?) of the block-notices templates have that, so I guess there must be a reason or at least we should revaluate for consistency.

That's a good point. For some reason, the other day while I was testing, having role="alert" didn't allow the screen reader to read the multi-line messages, but when I tested again on Safari (and Chrome) today, it was working fine, so I believe it depends on the browser as well.

Another important thing is that `role="alert"` is not supposed to be used in a full page reload scenario.
image
Ref: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/alert_role

That said, 
- since it is a block template, I am assuming that it will be used in scenarios where we update the message inside the error container dynamically.
- A bunch of e2e tests also depend on this attribute, keeping all the factors in mind, it makes sense to keep this attribute.

**Comment by naman03malhotra** [comment]
>It'd be good to ask Ghidorah for some feedback. What to do you think?

Good idea, I've requested their feedback.

File: plugins/woocommerce/client/legacy/js/frontend/account-i18n.js [hunk 3]
```diff
@@ -0,0 +1,13 @@
+/* global Cookies */
+jQuery( function( $ ) {	
+    // Select all elements with the class 'wc-block-components-notice-banner' that contain text
```
Comment (chihsuan) [inline plugins/woocommerce/client/legacy/js/frontend/account-i18n.js]:
```suggestion
    // Select all elements with the [role="alert"] attribute that contain text
```

File: plugins/woocommerce/client/legacy/js/frontend/account-i18n.js [hunk 4]
```diff
@@ -0,0 +1,13 @@
...
+    var notices = $('[role="alert"]').filter(function() {
+        return $(this).text().trim().length > 0;
+    });
+
+    if (notices.length > 0) {
+        setTimeout(function() {
+            $(notices[0]).attr('tabindex', '-1').focus();
+        }, 1000);
```
Comment (chihsuan) [inline plugins/woocommerce/client/legacy/js/frontend/account-i18n.js]: Could you explain why this specific delay is needed? 🙏

**Review by chihsuan — COMMENTED** [review]
> So, the most reliable way I found to grab the screen reader's attention after a full page reload was to bring the alert element in focus.

Thanks for sharing @naman03malhotra 🙏 , I did some investigation and agree with you that bringing the alert element seems the best way to grab the screen reader's attention.

I tested with VoiceOver on macOS Safari, and it works as expected with block themes. However, it doesn't work very well with classic themes such as "StoreFront". I tried a few times and sometimes it reads the alert message, but sometimes it doesn't. (It did focus the alert element.)

https://github.com/woocommerce/woocommerce/assets/4344253/f89c1665-04e1-47d8-81a4-832dcec44532

Additionally, I tested it on Chrome. I noticed that VoiceOver only read `"Error:, and 1 more item, alert, main"` and then stopped. It would be great if we could find a solution for this, but if not, I think we can go with this for now and improve it later.

https://github.com/woocommerce/woocommerce/assets/4344253/9536b683-7ee1-4ec7-b41c-ed77a01fdbd3


I also checked how WordPress handles this on the login page, and it seems that they use `aria-described by` to associate the alert message with the input field and auto-focus on the input field when the page is loaded. I think this is a good approach, but I can see that we will need to make some changes to our code to make it work with our current implementation, so I don't think we can do this now. And if we want to do this, we should also consider if we can submit with Ajax directly.

Screenshot 2024-05-14 at 15 28 50

**Comment by naman03malhotra** [comment]
Thank you @chihsuan for an in-depth review 🙇 

> However, it doesn't work very well with classic themes such as "StoreFront". I tried a few times and sometimes it reads the alert message, but sometimes it doesn't. (It did focus the alert element.)

Hmm, that's strange, it is working well for me at least on Safari. Check the screencast below

https://github.com/woocommerce/woocommerce/assets/15019298/be98389e-ca8d-404c-9573-17bca3cab6c6



>Additionally, I tested it on Chrome. I noticed that VoiceOver only read "Error:, and 1 more item, alert, main" and then stopped. It would be great if we could find a solution for this, but if not, I think we can go with this for now and improve it later.

I also observed that issue; it looks like it is a Chrome thing; I tried to fiddle around to find a solution, so it looks like removing role="alert" solves the issue, but it causes problems in other browsers.

Also, from all the testing, it seems like voice-over for Mac is most compatible with Safari, which I think most folks would be using while leveraging accessibility features.

> but I can see that we will need to make some changes to our code to make it work with our current implementation, so I don't think we can do this now. And if we want to do this, we should also consider if we can submit with Ajax directly.

+1 to this.

I believe that we can have more robust accessibility with dynamic content submission instead of a full page reload, however that would require more code change.

That said, I believe this change will give some relief to folks who need features to be accessible. Later, we can plan to change our accounts section to submit data using Ajax.

File: plugins/woocommerce/client/legacy/js/frontend/account-i18n.js (hunk 3 above)
Comment (naman03malhotra) [reply plugins/woocommerce/client/legacy/js/frontend/account-i18n.js]: Good catch, made the change here: https://github.com/woocommerce/woocommerce/pull/47144/commits/60e0b972822fd0d2e3ddc68f22699acdde1c8159

File: plugins/woocommerce/client/legacy/js/frontend/account-i18n.js (hunk 4 above)
Comment (naman03malhotra) [reply plugins/woocommerce/client/legacy/js/frontend/account-i18n.js]: So I am queuing the focus event at last of the event queue to override any other focus events in case of critical error. In my case, "Skip to content" was being focused just after the error, resulting in the voiceover breaking the message.

I've removed 1000 delay, and just kept the default timeout.

Comment (chihsuan) [reply plugins/woocommerce/client/legacy/js/frontend/account-i18n.js]: @naman03malhotra Thanks for the explanation! That makes sense. Would you mind adding a comment to the code? That would be helpful for future developers.

**Review by chihsuan — APPROVED** [review]
Thanks for the addressing the feedback! I tested again with safari and it seems to be working fine. :thumbsup:

Code looks good to me except for the comment. I'd recommend testing with other browsers on Windows as well but I think this is good to go.

Code looks good to me except for the comment. Pre-approving!

File: plugins/woocommerce/client/legacy/js/frontend/account-i18n.js (hunk 4 above)
Comment (naman03malhotra) [reply plugins/woocommerce/client/legacy/js/frontend/account-i18n.js]: >Would you mind adding a comment to the code? 

Good suggestion, I will add

Comment (naman03malhotra) [reply plugins/woocommerce/client/legacy/js/frontend/account-i18n.js]: Added here: https://github.com/woocommerce/woocommerce/pull/47144/commits/068a94418f832b146d83bb5087ce85553664f8f8

**Review by jorgeatorres — APPROVED** [review]
LGTM. Thank you @naman03malhotra!
