### PR TITLE
Gallery tweaks

### LINKED ISSUE #12868: [2.7-master] Flexslider single product WC onload height is wrong until resize
## EXPLANATION OF THE ISSUE

WooCommerce 2.7-master, FireFox

## STEPS TO REPRODUCE THE ISSUE

Visit single product with or without thumbnails and the height is wrong until resize of the page. 

Incidentally, I used to use FlexSlider and this happened all the time unless I used window.load and not document ready. I use SlickSlider for all slider stuff these days.

Anyway, it looks nice when it works, here is a photo of it not working. It happens with and without my CSS and php.

screen shot 2017-01-17 at 7 00 40 pm

### LINKED ISSUE #12923: New gallery zoom feature
## EXPLANATION OF THE ISSUE

I have my column for product images set to about 590px in width but I upload images of about 600px to account for browser inconsistencies in calculating widths.

This new zoom feature gets triggered unnecessarily in this situation and thus produces visual glitches.

Furthermore, I have some small images there as well (100px in width) and it also works for too small images when there is no need to do that.

### LINKED ISSUE #12934: [2.7] Allow replace flexslider for image gallery
## EXPLANATION OF THE ISSUE

Please, add the ability to disable flexslider for `.woocommerce-product-gallery`. We can `dequeue` the Flexslider library, but if some plugin or custom code will enqueue it again then this code will enable flexslider for the gallery 

`			if ( $.isFunction( $.fn.flexslider ) ) {
				this.init_flexslider();
			}
`

Is it possible to disable flexslider completely without changing HTML structure and class names?

Also, we don't see any usage of the `is_touch_device ` method in `wc_product_gallery` class. Why do you need to keep it?

### PR DESCRIPTION
**Pull request by mikejolley**
Adds conditional support for the 3 gallery features using add_theme_support. Make features work if part is off.

Also improves gallery appearance when all features are off.

Fixes #12868 
Closes #12923 
Closes #12934

### CODE REVIEW

File: includes/class-wc-frontend-scripts.php [hunk 1]
```diff
@@ -354,13 +354,22 @@ public static function load_scripts() {
...
 			self::enqueue_script( 'wc-lost-password' );
 		}
+
+		// Load gallery scripts on product pages only if supported.
 		if ( is_product() || ( ! empty( $post->post_content ) && strstr( $post->post_content, '[product_page' ) ) ) {
-			self::enqueue_script( 'flexslider' );
-			self::enqueue_script( 'photoswipe-ui-default' );
-			self::enqueue_style( 'photoswipe-default-skin' );
-			self::enqueue_script( 'zoom' );
+			if ( get_theme_support( 'wc-product-gallery-zoom' ) ) {
```
Comment (jameskoster) [inline includes/class-wc-frontend-scripts.php]: `current_theme_supports()`? :p
