### PR TITLE
Handle Invalid Product ID

### LINKED ISSUE #52662: Single Product Block - Invalid Product ID
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

If a single product block that has a product assigned and then that product is deleted, you get an invalid product ID error:

"Sorry, an error occurred
The following error was returned
Invalid product ID."

Edit*
If several of these exist on a page it can cause over memory utilisation on the server or crash the browser page. 

### Expected behavior

Allowing the product selector to load even if the error occurs and select a product to clear the error would be far more intuitive and user friendly. 

### Actual behavior

The product selector in the block settings does not load, therefore the only way to recover the block is to manually remove the product ID via the pages code editor. This is undesirable user experience.

### Steps to reproduce

1. Add Single Product block to page
2. Select Product and save 
3. Trash and Delete product from products
4. reload page editor with single product block

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): 
Site address (URL): 
WC Version: 9.3.3
Legacy REST API Package Version: The Legacy REST API plugin is not installed on this site.
Action Scheduler Version: ✔ 3.8.1
Log Directory Writable: ✔
WP Version: 6.6.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_AU
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 8.2.25
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.81.0
OpenSSL/3.0.2

### Isolating the problem

- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by octaedro**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

This PR fixes a problem after deleting a product selected for a `Single Product` block.
There is no way to Choose another product when the product has been deleted.

### Before

Screenshot 2024-12-26 at 11 39 53 AM

### After

Screenshot 2024-12-30 at 4 39 11 PM

Closes #52662.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Create a product.
2. Go to Pages > Add New Page
3. Add a `Single Product` block and select the product you just created.
4. Save the page.
5. Remove the product and delete it permanently.
6. Reload the page.
7. The product picker should be visible with the text: `Previously selected product is no longer available.`
8. Pick another product.
9. The new product should be visible now.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce-blocks/assets/js/blocks/single-product/edit/index.tsx [hunk 1]
```diff
@@ -67,6 +78,10 @@ const Editor = ( {
 		} );
 	} );
 
+	const isProductInvalidId =
```
Comment (roykho) [inline plugins/woocommerce-blocks/assets/js/blocks/single-product/edit/index.tsx]: Is there a reason we don't name it `isInvalidProductId` instead?

Comment (octaedro) [reply plugins/woocommerce-blocks/assets/js/blocks/single-product/edit/index.tsx]: Good call! Fixed in the commit [46c3d4d](https://github.com/woocommerce/woocommerce/pull/54053/commits/46c3d4d6859d55fef5a1039f9e0195217c562785)

**Review by roykho — APPROVED** [review]
Great job!

✅ Deleted a product that was assigned to the Single product. A proper error message is shown.
✅ Product selection list is shown after showing the error message.
