### PR TITLE
Fix/31582 special characters in password on checkout page lead to not working account

### LINKED ISSUE #31582: Special characters in password on checkout page lead to not working account
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

New accounts created from the checkout page with special characters in the password do not work.

It is similar to https://github.com/woocommerce/woocommerce/issues/23922. The fix for #23922 was unfortunately incomplete. In https://github.com/woocommerce/woocommerce/blob/acbe200c79815deda60e9fd5cc1aa63fccdda070/plugins/woocommerce/includes/class-wc-checkout.php#L669 all posted fields including the password are still getting unslashed. This leads to an account creation with unslashed passwords. Everywhere else the passwords have the slashes.

### Expected behavior

The new account should work.

### Actual behaviour

Login denied with an invalid password error message.

### Steps to reproduce

1. Ensure that your Account Settings in WooCommerce are like this: 
image

(basically, you want automatic password creation disabled so that the option to set the password on the checkout page shows). 
2. Create a new account via the checkout page, and when setting the password, use a double quote `"` somewhere in the password.
3. Try to log in with the new account in an incognito window.
4. Login is denied with an invalid password error.

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://10_150_40_200.breakpoint.one
Site address (URL): https://10_150_40_200.breakpoint.one
WC Version: 5.5.1
REST API Version: ✔ 5.5.1
WC Blocks Version: ✔ 5.3.2
Action Scheduler Version: ✔ 3.2.1
WC Admin Version: ✔ 2.4.1
Log Directory Writable: ✔
WP Version: 5.8.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: de_DE_formal
External object cache: –

### Server Environment ###

Server Info: nginx/1.16.1
PHP Version: 7.4.27
PHP Post Max Size: 64 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.80.0
OpenSSL/1.1.1l

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.4.11-MariaDB-1:10.4.11+maria~bionic-log
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 5.5.1
WC Database Prefix: wp_
Datenbank-Gesamtgröße: 10.65MB
Datenbank-Datengröße: 7.39MB
Datenbank-Indexgröße: 3.26MB
wp_woocommerce_sessions: Daten: 0.13MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Daten: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Daten: 0.13MB + Index: 0.28MB + Engine InnoDB
wp_woocommerce_tax_rates: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Daten: 0.02MB + Index: 0.13MB + Engine InnoDB
wp_woocommerce_log: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Daten: 0.02MB + Index: 0.13MB + Engine InnoDB
wp_actionscheduler_claims: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Daten: 0.08MB + Index: 0.09MB + Engine InnoDB
wp_links: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Daten: 1.05MB + Index: 0.09MB + Engine InnoDB
wp_postmeta: Daten: 1.52MB + Index: 0.69MB + Engine InnoDB
wp_posts: Daten: 3.05MB + Index: 0.13MB + Engine InnoDB
wp_ppc_exceptions: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_ppc_exception_items: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_ppc_roles: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_ppi_errors: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_ppi_imported: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_ppi_runs: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_pp_groups: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_pp_group_members: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_termmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Daten: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Daten: 0.08MB + Index: 0.06MB + Engine InnoDB
wp_users: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wcpdf_invoice_number: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_notes: Daten: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Daten: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_reserved_stock: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_gzd_dhl_im_products: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_gzd_dhl_im_product_services: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_gzd_dhl_labelmeta: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_gzd_dhl_labels: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_gzd_packaging: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_gzd_packagingmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_gzd_shipmentmeta: Daten: 0.08MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_gzd_shipments: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_gzd_shipment_itemmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_gzd_shipment_items: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_gzd_shipment_labelmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_gzd_shipment_labels: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_gzd_shipping_provider: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_gzd_shipping_providermeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB

### Post Type Counts ###

attachment: 225
page: 80
polylang_mo: 8
post: 1
product: 86
revision: 3
shop_coupon: 15
shop_order: 73
web-story: 4

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (15) ###

Polylang: von WP SYNTEX – 3.0.4
Application Passwords: von George Stephanis – 0.1.3
XML Sitemaps: von Auctollo – 4.1.1
Insert Pages: von Paul Ryan – 3.6.1
Nginx Helper: von rtCamp – 2.2.2
Post Snippets: von Postsnippets – 3.1.3
Printkit: von  – 1.35.${PROJECT_VERSION}
Structured Content: von Gordon Böhme
Antonio Leutsch – 1.4.6

Very Simple Meta Description: von Guido – 6.4
Web Stories: von Google – 1.15.1
Advanced Order Export For WooCommerce: von AlgolPlus – 3.1.8
PayPal PLUS für WooCommerce: von Inpsyde GmbH – 2.2.1
Germanized für WooCommerce: von vendidero – 3.4.8
WooCommerce PDF Invoices & Packing Slips: von Ewout Fernhout – 2.9.0
WooCommerce: von Automattic – 5.5.1 (Update auf Version 6.0.0 ist verfügbar)

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop-Basis: ❌ Seite nicht festgelegt
Warenkorb: ❌ Seite nicht festgelegt
Kasse: #33 - /checkout/
Mein Konto: #34 - /my-account/
Allgemeine Geschäftsbedingungen: #962 - /agb/

### Theme ###

Name: Storefront Printkit
Version: 1.0.${PROJECT_VERSION}
Author URL: https://printkit.breakpoint.one
Child Theme: ✔
Parent Theme Name: Storefront
Parent Theme Version: 2.5.8 – 3.9.1 ist verfügbar
Parent Theme Author URL: https://woocommerce.com/
WooCommerce Support: ✔

### Templates ###

Overrides: storefront-printkit/woocommerce/archive-product.php Version - ist veraltet. Die Hauptversion ist 3.4.0
storefront-printkit/woocommerce/emails/customer-completed-order.php
storefront-printkit/woocommerce/emails/customer-processing-order.php
storefront-printkit/woocommerce/single-product.php Version - ist veraltet. Die Hauptversion ist 1.6.4

Outdated Templates: ❌
					
					
						Erfahren Sie
wie Sie aktualisieren können

### Action Scheduler ###

Abgeschlossen: 19
Oldest: 2021-12-08 09:41:15 +0000
Newest: 2022-01-06 15:48:04 +0000

### Status report information ###

Generated at: 2022-01-06 16:39:29 +00:00
`

### Isolating the problem

- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by wavvves**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

This PR introduces `wp_slash()` on `$_POST['password']` to mimic the behavior of default account creation on registration during checkout via submitting a password.
On the default account creation, passwords are being slashed before encryption. Lack of this step would prevent a new user from subsequently logging in after creating an account during checkout while submitting the correct password

Closes #31582 .

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

image

1. Set up WooCommerce using the settings from the above printscreen on `/wp-admin/admin.php?page=wc-settings&tab=account`
2. On an incognito browser window, place an order using the shortcode checkout page, and create a new account while doing it using a password containing the `"` character
3. Go to My Account, log out, and try to log back in using the new user credentials
4. Verify that the login process was done successfully

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce/includes/class-wc-checkout.php [hunk 1]
```diff
@@ -1119,7 +1119,7 @@ protected function process_customer( $data ) {
 			$customer_id = wc_create_new_customer(
 				$data['billing_email'],
 				$username,
-				$password,
+				wp_slash($password), // We need to wp_slash() manually here to mimic the normal registration process.
```
Comment (mikejolley) [inline plugins/woocommerce/includes/class-wc-checkout.php]: This needs to have PHPCS applied for correct spacing.

**Review by mikejolley — CHANGES_REQUESTED** [review]
I'm not sure this covers all use cases. I understand its targeting shortcode checkout, but `wc_create_new_customer` is used in several places across the codebase.

Do you think we should move this change within `wc_create_new_customer`? And does this need some kind of test in place to confirm behaviour and avoid future regressions?

Additionally, does this code assume the POST variable was unslashed already? Is that the case everywhere `wc_create_new_customer` is used?

**Comment by wavvves** [comment]
> I'm not sure this covers all use cases. I understand its targeting shortcode checkout, but `wc_create_new_customer` is used in several places across the codebase.
> 
> Do you think we should move this change within `wc_create_new_customer`? And does this need some kind of test in place to confirm behaviour and avoid future regressions?
> 
> Additionally, does this code assume the POST variable was unslashed already? Is that the case everywhere `wc_create_new_customer` is used?

It took a while to debug this; on the default account registration, the password arrives slashed to `wc_create_new_customer,` whereas here, it is not. Actually, it seems that the password is always encrypted after slashing. Using unslashed data should not be a problem since any malicious payload is destroyed after encryption. Still, I strongly think we should keep encrypting slashed passwords, as changing that function seems to have a higher risk of breaking all logins.

I wouldn't test for this behaviour, I would rather do E2E tests that does guest checkout with account creation, check everything works and includes a check that logs in with supplied credentials after. That can be done in a separate issue, let me check what E2E tests are already in place regarding this ;)

**Comment by mikejolley** [comment]
Ok, but can we at least track where the unslash is happening @wavvves? I cannot see it happening when `wc_create_new_customer` is called. It would be useful to confirm where the unslash first happens so it can be documented clearly in the code why the slash is needed. Or we can remove the unslash at source.

File: plugins/woocommerce/includes/class-wc-checkout.php [hunk 2]
```diff
@@ -783,6 +783,9 @@ public function get_posted_data() {
 							$value = wc_sanitize_textarea( $value );
 							break;
 						case 'password':
+							if ( $data[ 'createaccount' ] && 'account_password' === $key ) {
+								$value = wp_slash( $value ); // Passwords are encrypted with slashes on account creation, so we need to slash here too.
```
Comment (wavvves) [inline plugins/woocommerce/includes/class-wc-checkout.php:787]: > Ok, but can we at least track where the unslash is happening @wavvves? I cannot see it happening when wc_create_new_customer is called. It would be useful to confirm where the unslash first happens so it can be documented clearly in the code why the slash is needed. Or we can remove the unslash at source.

@mikejolley unslashing is being done here on L767. Instead of adding an exception there I think it would be more readable and self-contained to be re-slashed on the switch. The tiny performance hit of just avoiding unslashing can be neglected IMO.
What do you think?

Comment (tarunvijwani) [reply plugins/woocommerce/includes/class-wc-checkout.php:787]: @mikejolley Here is the direct link to it: https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/includes/class-wc-checkout.php#L767

Comment (mikejolley) [reply plugins/woocommerce/includes/class-wc-checkout.php:787]: Makes sense.

**Review by mikejolley — APPROVED** [review]
Tests ok. Thanks for investigating.
