### PR TITLE
Fixes two product attributes issues when non-ASCII characters are used in the attribute name

### LINKED ISSUE #21026: Filter by attribute doesn't work well with greek characters
**Describe the bug**
When I add an attribute with greek slug and remove a term from this attribute from a product, it still shows up in the sidebar and I can still see this product if I filter by this term.
Also, if I filter by any term, after I'm not able to clear it because the clear term button (X), doesn't work, even in attributes with greek or english characters.

**To Reproduce**
1. Add an attribute with greek slug. (Ex. δοκιμή)
2. Add some terms with greek or english slugs
3. Edit a product and add a term from this attribute
4. Check your sidebar to see the terms
5. Edit again the product and remove the term
6. You will still see this term in sidebar and you can still filter by this attribute

**Expected behavior**
The terms must remove from sidebar if I remove them from the product (if there only one product with this attribute). If there are more products with this attribute, then the term must not show this product if someone filter it. 
Also, the clear term button in sidebar (X), must work.

**Isolating the problem (mark completed items with an [x]):**
- [x ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
`
### WordPress Environment ###

Home URL: http://localhost/filters/wordpress
Site URL: http://localhost/filters/wordpress
WC Version: 3.4.4
Log Directory Writable: ✔
WP Version: 4.9.8
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.33 (Win64) PHP/7.1.16
PHP Version: 7.1.16 - We recommend using PHP version 7.2 or above for greater performance and security. How to update your PHP version
PHP Post Max Size: 8 MB
PHP Time Limit: 120
PHP Max Input Vars: 2500
cURL Version: 7.59.0
OpenSSL/1.0.2o

SUHOSIN Installed: –
MySQL Version: 5.7.21
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.4.4
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Total Database Size: 0.45MB
Database Data Size: 0.36MB
Database Index Size: 0.09MB
wp_woocommerce_sessions: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_api_keys: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_order_items: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_order_itemmeta: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_tax_rates: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_log: Data: 0.00MB + Index: 0.00MB
wp_commentmeta: Data: 0.00MB + Index: 0.00MB
wp_comments: Data: 0.00MB + Index: 0.01MB
wp_links: Data: 0.00MB + Index: 0.00MB
wp_options: Data: 0.35MB + Index: 0.02MB
wp_postmeta: Data: 0.00MB + Index: 0.01MB
wp_posts: Data: 0.01MB + Index: 0.01MB
wp_termmeta: Data: 0.00MB + Index: 0.01MB
wp_terms: Data: 0.00MB + Index: 0.01MB
wp_term_relationships: Data: 0.00MB + Index: 0.00MB
wp_term_taxonomy: Data: 0.00MB + Index: 0.00MB
wp_usermeta: Data: 0.00MB + Index: 0.01MB
wp_users: Data: 0.00MB + Index: 0.01MB
wp_wc_download_log: Data: 0.00MB + Index: 0.00MB
wp_wc_webhooks: Data: 0.00MB + Index: 0.00MB

### Post Type Counts ###

page: 2
post: 2
product: 2
revision: 2

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 3.4.4

### Settings ###

API Enabled: –
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: ❌ Page not set
Cart: ❌ Page not set
Checkout: ❌ Page not set
My account: ❌ Page not set
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Seventeen
Version: 1.7
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –
`
```
</details>

### PR DESCRIPTION
**Pull request by rodrigoprimo**
### Changes proposed in this Pull Request:

This PR implements two changes to the product attributes code to fix the following issues in the "Filter products by attribute" widget (see commit messages for a detailed explanation of the changes):

- Clearing filters don't work when non-ASCII characters are used in the product attribute name. Commit: 20fd569.
- The "Filter product by attributes" cache is not cleared when an attribute containing a non-ASCII character in the name is added to a product, resulting in the widget displaying the wrong information (wrong attributes available to filter or wrong number of products per attribute). Commit: 4d2530e.

This PR also includes PHPCS fixes in a separate commit.

Closes #21026
Supersedes #21028 

cc @rellect @plxrisa could you please test this PR to confirm if it fixes the issues you reported?

### How to test the changes in this Pull Request:

1. See #21026 and #21028 for instructions

### Changelog entry

> Fixes two product attributes issues when non-ASCII characters are used in the attribute name

### CODE REVIEW

**Comment by rellect** [comment]
Looks good 👍

**Review by claudiulodro — APPROVED** [review]
👍

**Comment by plxrisa** [comment]
I confirm that works well with new products. For existing products, (if you have already remove a term in version 3.4.4), you must edit the product again and update it.

Also, you can clear a term if you click on it. But the (x) button, don't work for me.
Check here what I mean: https://www.useloom.com/share/4a5a3f216c7a4f9ab8936aebb5db5df4

**Comment by rodrigoprimo** [comment]
@plxrisa I'm sorry, I forgot to check that part of your original issue. Could you please open another issue for the "X" button? I tested and I was able to reproduce the problem you described, but as far as I can tell this is not related to non-ASCII characters and happens at least since WooCommerce 3.0.

File: includes/widgets/class-wc-widget-layered-nav.php [hunk 1]
```diff
@@ -423,7 +423,7 @@ protected function layered_nav_list( $terms, $taxonomy, $query_type ) {
 				continue;
 			}
 
-			$filter_name    = 'filter_' . sanitize_title( str_replace( 'pa_', '', $taxonomy ) );
+			$filter_name    = 'filter_' . str_replace( 'pa_', '', $taxonomy );
```
Comment (kloon) [inline includes/widgets/class-wc-widget-layered-nav.php]: My only concern here is by removing the sanitize_title call you introduce the probability of spaces in the filter name, probably not an issue since browsers auto convert these for URLs, just want to be careful we do not change something that can cause a bug. If you are happy with the change then you can ignore my comment.
