### PR TITLE
Make quantity selector more specific Only select the primary quantity

### LINKED ISSUE #36086: onFoundVariation $qty selector is too broad
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

On found variations, the front end script, dynamically updates the quantity input based on the value in the quantity input, adjusted for min/max settings of the found variation.

However, the [jquery selector is too broad](https://github.com/woocommerce/woocommerce/blob/185d3337cac78ba12a4dd6c0384a82df32629cb2/plugins/woocommerce/client/legacy/js/frontend/add-to-cart-variation.js#L248). If for any reason you have other `.quantity` divs in your form, this selector will select them all and get confused about which input it intends to calculate from.

In my case, I am developing Variable Mix and Match so for each variation a bunch of other quantity inputs are also loaded:

image

And when I change the configuration a little, but then switch the variation, the main quantity input suddenly is set to the value of the last mix and match child product's quantity input. 

image

Changing the selector to 
`$qty           = form.$singleVariationWrap.find( '.woocommerce-variation-add-to-cart .quantity' ),`

ensures that you only ever look at the quantity div inside the variation add to cart div, no matter what anyone is doing in the rest of the form.

### Expected behavior

The primary quantity remains unchanged when switching variations

### Actual behavior

primary quantity inherits quantity from other form divs where there is more than 1 `.quantity` div in the `.single_variation_wrap` div.

### Steps to reproduce

This is admittedly using an extremely custom plugin to get myself into this predicament.... a very complex variable-ish product type. However, the proposed fix should have no negative repercussions though and will keep working the same way for regular variable products.

You can test a regular variable product and switch variations and the result will be the same as it currently is. 

### WordPress Environment

n/a

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by helgatheviking**
buttons inside the .woocommerce-variation-add-to-cart div.
 
 More explanation is available in #36086 36086

### All Submissions:

-   [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
-   [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
-   [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes #36086 .

- [x] This PR is a very minor change/addition and does not require testing instructions (if checked you can ignore/remove the next section).

### How to test the changes in this Pull Request (Part 1)

This set of testing instructions is aimed at showing the problem (involving custom code) that this PR solves. Start by adding the following snippet, which adds a new quantity input to the single variation:

```php
function kia_test_single_variation_qty() {
	echo '<div class="quantity"><input class="qty" type="number" name="tacos" /></div>';
}
add_action( 'woocommerce_before_single_variation', 'kia_test_single_variation_qty' );
```

1. Go to a variable product
2. Select a variation by selecting the attributes necessary
3. Increase the rogue quantity input's value
4. change to another variation
5. the main quantity input's value should now match what you entered in the _other_ input.

This will no longer happen with the proposed changes.

Instead, if you increase the primary quantity input's value, then switch variations.. the primary quantity input should stay the same (assuming no stock issues of very specific filters)

### How to test the changes in this Pull Request (Part 2)

This second set of testing instructions aims to confirm that there were no adverse effects to our default plugin behavior following this change.

- Remove any custom snippets you might have added in the previous steps.
- Visit the single product page for a variable product.
- Ensure you can select a variation, and a specific quantity, and add it to the cart successfully.

### Other information:

-   [x] Have you added an explanation of what your changes do and why you'd like us to include them?
-   [ ] Have you written new tests for your changes, as applicable?
-   [x] Have you created a changelog file for each project being changed, ie `pnpm --filter=<project> changelog add`?

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

File: plugins/woocommerce/client/legacy/js/frontend/add-to-cart-variation.js [hunk 1]
```diff
@@ -245,7 +245,7 @@
 			$dimensions    = form.$product.find(
 				'.product_dimensions, .woocommerce-product-attributes-item--dimensions .woocommerce-product-attributes-item__value'
 			),
-			$qty           = form.$singleVariationWrap.find( '.quantity' ),
+			$qty           = form.$singleVariationWrap.find( '.woocommerce-variation-add-to-cart .quantity' ),
```
Comment (barryhughes) [inline plugins/woocommerce/client/legacy/js/frontend/add-to-cart-variation.js]: At the risk of overthinking this, what do you think of this alternative:

```suggestion
			$qty           = form.$singleVariationWrap.find( '.quantity input[name="quantity"]' ),
```

Or simply:

```suggestion
			$qty           = form.$singleVariationWrap.find( 'input[name="quantity"]' ),
```

My thinking is that this is (just slightly) more robust, since the input name is the key differentiator and since the surrounding div classes can be readily changed via template overrides.

I realize surrounding code still relies on CSS selectors, and that the input name can also be changed via a template override, but that change seems marginally less likely ... and any small tweak that might reduce the potential for breakages elsewhere is worth exploring.

File: plugins/woocommerce/changelog/issues-36086-more-specific-variation-qty-selector [hunk 2]
```diff
@@ -0,0 +1,4 @@
+Significance: patch
+Type: enhancement
+
+onFoundVariation make $qty selector more specific
```
Comment (barryhughes) [inline plugins/woocommerce/changelog/issues-36086-more-specific-variation-qty-selector]:
```suggestion
Improves handling of the single product page quantity selector, in relation to variable products.
```

**Review by barryhughes — COMMENTED** [review]
Left some notes, let me know your thoughts.

File: plugins/woocommerce/client/legacy/js/frontend/add-to-cart-variation.js (hunk 1 above)
Comment (helgatheviking) [reply plugins/woocommerce/client/legacy/js/frontend/add-to-cart-variation.js]: Hi @barryhughes is it possible to have multiple products on the same page? like with One Page Checkout or other builders? Would `name` alone be enough then as a selector? But otherwise, `.find( 'input[name="quantity"]' )` does resolve my problem.

Comment (barryhughes) [reply plugins/woocommerce/client/legacy/js/frontend/add-to-cart-variation.js]: I guess that's possible, though we are still looking within the *single variation wrapper,* here. If it otherwise suits your needs, perhaps let's run with the first suggestion (`.quantity input[name="quantity"]`).

Comment (helgatheviking) [reply plugins/woocommerce/client/legacy/js/frontend/add-to-cart-variation.js]: True.. that probably means it should only happen once per `<form>` unless you're doing something super custom (and I'm already out on the edge of super custom with this project). Works for me! Thanks for reviewing this so quickly.

**Comment by helgatheviking** [comment]
LGTM!

**Comment by barryhughes** [comment]
Great—once checks pass (ignoring *'build live branch')* we can go ahead and merge :+1:

**Review by barryhughes — APPROVED** [review]
