### PR TITLE
Replace Congratulations view Buttons with Links 

### LINKED ISSUE #51575: CYS: Congratulations view should use links instead of buttons
## Steps to reproduce

0. If needed, restart the Customize Your Store flow by installing the WooCommerce Beta Tester plugin and going to `wp-admin/tools.php?page=woocommerce-admin-test-helper` > Tools > "Reset Customize Your Store".
1. In the admin, go to WooCommerce > Customize Your Store > Create your own theme.
2. Finish customizing and you will be redirected to the Congratulations view.
imatge
3. Try clicking on _View store_, _Go to Products_, _Go to the Editor_ or _Back to Home_ with your mouse middle click or via <kbd>Ctrl</kbd>+Click to open the links in a new tab.
4. Notice they don't open at all, because they are buttons.

## Expected result

All those links should be `<a>` instead of `<button>`, for accessibility reasons and to make it possible to open them in a new tab, copy the URL, etc.

### PR DESCRIPTION
**Pull request by narenin**
Closes #51575 .

### How to test the changes in this Pull Request:

1. If needed, restart the Customize Your Store flow by installing the WooCommerce Beta Tester plugin and going to `wp-admin/tools.php?page=woocommerce-admin-test-helper > Tools > "Reset Customize Your Store"`.
2. In the admin, go to `WooCommerce > Customize Your Store > Create your own theme`.
3. Finish customizing and you will be redirected to the **Congratulations view**.
4. Try clicking on View store, Go to Products, Go to the Editor or Back to Home with your mouse middle click or via Ctrl+Click to open the links in a new tab.
5. Notice they don't open at all, because they are buttons.

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 
Replaced Congratulations view Buttons with Links for Accessibility reasons.
</details>

### CODE REVIEW

File: plugins/woocommerce-admin/client/customize-store/transitional/index.tsx [hunk 1]
```diff
@@ -178,23 +178,19 @@ export const Transitional = ( {
 											'woocommerce'
 										) }
 									</p>
-									<Button
-										variant="link"
+									<a
```
Comment (kmanijak) [inline plugins/woocommerce-admin/client/customize-store/transitional/index.tsx]: Let's keep using the `Button` component instead of the "raw" `a` element. It's to keep it up to date with any changes coming from Gutenberg. However `Button` component allows you to pass `href` prop and according to [documentation](https://wordpress.github.io/gutenberg/?path=/docs/components-button--docs):

> `href` - string - If provided, renders `a` instead of `button`.

So something like this should work:

```suggestion
									<Button
										variant="link"
										href={`${ ADMIN_URL }edit.php?post_type=product`}
										onClick={ () => {
											trackEvent(
												'customize_your_store_transitional_product_list_click'
											);
										} }
									>
```

This applies to other links as well.

**Review by kmanijak — CHANGES_REQUESTED** [review]
Hey, thanks a lot for your contribution, much appreciated! I left a comment that we should keep using `Button` component so we're aligned with Gutenberg.

Also, the original issue mentions "View Store" as well:

> Try clicking on **View store**, Go to Products, Go to the Editor or Back to Home with your mouse middle click or via Ctrl+Click to open the links in a new tab.

It's in the same file, could you address it as well in the same way?

Thanks!

File: plugins/woocommerce-admin/client/customize-store/transitional/index.tsx (hunk 1 above)
Comment (narenin) [reply plugins/woocommerce-admin/client/customize-store/transitional/index.tsx]: Thanks @kmanijak for the review. I have implemented the feedback, could you please take a look and let me know if any other changes needs to be made.

File: plugins/woocommerce-admin/client/customize-store/transitional/index.tsx [hunk 2]
```diff
@@ -122,15 +122,13 @@ export const Transitional = ( {
 					) }
 
 					<Button
+						href={ homeUrl }
 						className="woocommerce-customize-store__transitional-preview-button"
-						variant={
-							isEntrepreneurFlow() ? 'secondary' : 'primary'
-						}
+						variant="link"
```
Comment (kmanijak) [inline plugins/woocommerce-admin/client/customize-store/transitional/index.tsx]: Let's keep the look and feel the same as it was. I only meant switching from `window.open( ... )` to `href`. Apologies I didn't explain the intention fully.

File: plugins/woocommerce-admin/client/customize-store/transitional/index.tsx [hunk 3]
```diff
@@ -260,6 +252,7 @@ export const Transitional = ( {
 									</p>
 									<Button
 										variant="link"
+										href={ `${ ADMIN_URL }admin.php?page=wc-admin` }
```
Comment (kmanijak) [inline plugins/woocommerce-admin/client/customize-store/transitional/index.tsx]: This line is most likely not needed. "Back to Home" button/link triggers an event that causes a state transition rather than navigation. I'm consulting colleagues about the next steps regarding this, let's wait for their response.

**Review by kmanijak — COMMENTED** [review]
Thanks for the timely response and addressing all the comments!

I tested the changes and I still can't open links in a new tab (CMD + click) for "Back to home" link. However, it's not related to this PR.

I realized there was no `href` or navigation happening on click but the event is sent instead:

```
sendEvent( {
	type: 'GO_BACK_TO_HOME',
} );
```

which I assume is triggering state transition hence maybe it's not meant to be a link at all. I need to consult my colleagues better familiar with this part of the code: @Aljullu, @gigitux, I'm not sure how to semantically treat the "Back to home" button/anchor in here as it triggers transition and is not technically a link. Should we keep this one a button? Maybe we should migrate from transition to a regular link? Not sure about that.

Another option is to merge this PR with the downside of "Back to home" not behaving as a link.

File: plugins/woocommerce-admin/client/customize-store/transitional/index.tsx (hunk 2 above)
Comment (narenin) [reply plugins/woocommerce-admin/client/customize-store/transitional/index.tsx]: @kmanijak Thanks for the feedback, I have implemented the same.

File: plugins/woocommerce-admin/client/customize-store/transitional/index.tsx (hunk 3 above)
Comment (narenin) [reply plugins/woocommerce-admin/client/customize-store/transitional/index.tsx]: @kmanijak Thanks for the update, I will definitely wait for the feedback on this.

**Comment by gigitux** [comment]
> Thanks for the timely response and addressing all the comments!
> 
> I tested the changes and I still can't open links in a new tab (CMD + click) for "Back to home" link. However, it's not related to this PR.
> 
> I realized there was no `href` or navigation happening on click but the event is sent instead:
> 
> ```
> sendEvent( {
> 	type: 'GO_BACK_TO_HOME',
> } );
> ```
> 
> which I assume is triggering state transition hence maybe it's not meant to be a link at all. I need to consult my colleagues better familiar with this part of the code: @Aljullu, @gigitux, I'm not sure how to semantically treat the "Back to home" button/anchor in here as it triggers transition and is not technically a link. Should we keep this one a button? Maybe we should migrate from transition to a regular link? Not sure about that.
> 
> Another option is to merge this PR with the downside of "Back to home" not behaving as a link.

Thanks for the ping, Karol! I agree with you! I don't see any benefit in keeping it as state transition, given that the user leaves the CYS application when click on this button.

What do you think @mdperez86, @Aljullu?

**Comment by Aljullu** [comment]
> Thanks for the ping, Karol! I agree with you! I don't see any benefit in keeping it as state transition, given that the user leaves the CYS application when click on this button.

+1 on this, but I would avoid blocking this specific PR for this. We can leave the "Back to home" button as-is and open a separate issue for it and for removing the `GO_BACK_TO_HOME` state. Would that be a good plan?

**Comment by gigitux** [comment]
> > Thanks for the ping, Karol! I agree with you! I don't see any benefit in keeping it as state transition, given that the user leaves the CYS application when click on this button.
> 
> +1 on this, but I would avoid blocking this specific PR for this. We can leave the "Back to home" button as-is and open a separate issue for it and for removing the `GO_BACK_TO_HOME` state. Would that be a good plan?

For me, it is great!

**Comment by Aljullu** [comment]
> open a separate issue for it and for removing the `GO_BACK_TO_HOME` state

I opened an issue for this: https://github.com/woocommerce/woocommerce/issues/51867. So this should no longer be a blocker for this PR. :slightly_smiling_face:

**Review by kmanijak — CHANGES_REQUESTED** [review]
Thanks folks for the feedback and @narenin for quickly addressing it! 🙌 

There's just one CI error:

```
   24:10  error    'navigateOrParent' is defined but never used.
```

from `plugins/woocommerce-admin/client/customize-store/transitional/index.tsx`.

Please remove the import and we're good to merge the PR! Thanks for the patience!

**Comment by narenin** [comment]
Thanks @kmanijak I am implemented the suggestion please check.

**Comment by kmanijak** [comment]
> Thanks @kmanijak I am implemented the suggestion please check.

Amazing, thank you @narenin!

I didn't spot that earlier but there's one test failing:

> `customize-store/transitional.spec.js:101:3 › Store owner can view the Transitional page › Clicking on "View store" should go to the store home page in a new page`

Because we no longer force opening in a new tab, apologies I didn't mention it earlier. To save you trouble, here's how the test should look like:

```
		test( 'Clicking on "View store" should go to the store home page', async ( {
			pageObject,
			baseURL,
			page,
		} ) => {
			await setOption(
				request,
				baseURL,
				'woocommerce_admin_customize_store_completed',
				'yes'
			);

			await page.goto( TRANSITIONAL_URL );
			const assembler = await pageObject.getAssembler();

			await assembler.getByRole( 'link', { name: 'View store' } ).click();

			await expect( page ).toHaveURL( '/' );
		} );
```

With that change Ci should all be green and we can merge 🙌

**Comment by narenin** [comment]
@kmanijak Thanks for the feedback, I have implemented the same, please take a look.

**Comment by kmanijak** [comment]
> @kmanijak Thanks for the feedback, I have implemented the same, please take a look.

@narenin, I think you edited the wrong test and there are a bunch of other tests failing due to lack of dependencies etc. You've overwritten this test:

```
should record an event when clicking on "View store" button
```
in `plugins/woocommerce-admin/client/customize-store/transitional/test/index.test.tsx`

but you should override:

```
Clicking on "View store" should go to the store home page in a new page
```
in `plugins/woocommerce/tests/e2e-pw/tests/customize-store/transitional.spec.js`.

Please bring back a test to the original state and change the one I mentioned.

**Comment by narenin** [comment]
@kmanijak Thanks for pointing out that, I have made the suggested changes, please have a look.

Thanks for prompt responses and feedback.

**Review by kmanijak — APPROVED** [review]
Thanks for the contribution and your patience with the review process! All is green, I'm merging the PR now, thank you!

**Comment by narenin** [comment]
Thanks for your prompt feedback and the support. I will definitely contribute more.
