### PR TITLE
removed excess 0 from set_total

### LINKED ISSUE #59453: Too many arguments to function set_total(a, b)
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

The function set_total accepts 2 parameters -> key and total. Too many arguments passed in certain function calls.

Image

### Expected behavior

pass max 2 arguments

### Actual behavior

passed 3.

### Steps to reproduce

Go to file 
plugins\woocommerce\includes\class-wc-cart-totals.php
Line 761

### WordPress Environment

<details><summary>System Status Report</summary>

```
### WordPress Environment ###

WordPress address (URL): [Redacted]
Site address (URL): [Redacted]
WC Version: 9.8.5
Legacy REST API Package Version: The Legacy REST API plugin is not installed on this site.
Action Scheduler Version: ✔ 3.9.2
Log Directory Writable: ✔
WP Version: 6.8.1
WP Multisite: ✔
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 8.4.6
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.81.0
OpenSSL/3.0.2

SUHOSIN Installed: –
MySQL Version: 10.6.22-MariaDB-0ubuntu0.22.04.1
Max Upload Size: 1 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

[REDACTED]

### Post Type Counts ###

attachment: 23
mailpoet_page: 2
page: 7
post: 6
product: 20
product_variation: 7
revision: 1
shop_coupon: 1
shop_order_placehold: 13
wp_font_face: 36
wp_font_family: 12
wp_global_styles: 1
wp_navigation: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (16) ###

Akismet Anti-spam: Spam Protection: by Automattic - Anti-spam Team – 5.4
Google for WooCommerce: by WooCommerce – 2.9.13
Hello Dolly: by Matt Mullenweg – 1.7.2
Jetpack: by Automattic – 14.6
Klarna Checkout for WooCommerce: by Klarna – 2.13.8
Klaviyo: by Klaviyo
Inc. – 3.5.0

MailPoet: by MailPoet – 5.12.4
Password Protected: by Password Protected – 2.7.8
Printful Integration for WooCommerce: by Printful – 2.2.11
TikTok: by TikTok – 1.3.1
Amazon Pay for WooCommerce: by Amazon Pay – 2.5.4
WooCommerce Stripe Gateway: by Stripe – 9.5.2
WooPayments: by WooCommerce – 9.4.0 (update to version 9.6.0 is available)
WooCommerce PayPal Payments: by PayPal – 3.0.6 (update to version 3.0.7 is available)
WooCommerce Tax: by WooCommerce – 3.0.2 (update to version 3.0.4 is available)
WooCommerce: by Automattic – 9.8.5 (update to version 9.9.5 is available)

### Inactive Plugins (5) ###

Ibtana - WordPress Website Builder: by VowelWeb – 1.2.5.1
Kliken: Ads + Pixel for Meta: by Kliken – 1.2.0
Pinterest for WooCommerce: by WooCommerce – 1.4.19 (update to version 1.4.21 is available)
Plover Kit: by WP Plover – 1.5.3
Superb Addons: Blocks, Patterns & Theme Designer: by SuperbThemes – 3.5.9

### Settings ###

Legacy API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 3 KB

### WC Pages ###

Shop base: #7 - /shop/
Cart: #8 - /cart/ -  Contains the woocommerce/cart block
Checkout: #9 - /checkout/ -  Contains the woocommerce/checkout block
My account: #10 - /my-account/ -  Contains the [woocommerce_my_account] shortcode
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty-Five
Version: 1.2
Author URL: https://wordpress.org
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
Theme type: Block theme
WooCommerce Support: ❌ Not declared

### Templates ###

Overrides: /home/woocommerce/public_html/wp-content/plugins/woocommerce/templates/block-notices/error.php
/home/woocommerce/public_html/wp-content/plugins/woocommerce/templates/block-notices/notice.php
/home/woocommerce/public_html/wp-content/plugins/woocommerce/templates/block-notices/success.php


### WooPayments ###

Version: 9.4.0
Connected to WPCOM: ❌ No
Logging: Disabled

### WooCommerce Stripe Payment Gateway ###

Version: 9.5.2
Account ID: acct_1P4nyEHrm0UZRN1K
Account Email: Unknown
Test Mode Enabled: Yes
OAuth Connected: ✔
					Yes
Legacy Checkout Experience: ✔
					No
Enabled Payment Methods: alipay,apple_pay,bancontact,card,eps,google_pay,ideal,klarna,link,multibanco,p24,sepa_debit,wechat_pay
Express Checkout: ✔
					Enabled (product,cart,checkout)
Auth and Capture: ✔
					Yes
Logging: No

### MailPoet ###

Sending Method: PHPMail
Send all site's emails with: Default WordPress sending method
Task Scheduler method: Action Scheduler
Cron ping URL: https://woocommerce.gaststelle.com?mailpoet_router&endpoint=cron_daemon&action=ping

### Klarna Checkout Request Log ###

No KCO errors: 

### WooCommerce PayPal Payments ###

Onboarded: ✔
New UI active: ✔
Shop country code: DE
WooCommerce currency supported: ✔
Advanced Card Processing available in country: ✔
Pay Later messaging available in country: ✔
Webhook status: –
PayPal Vault enabled: –
ACDC Vault enabled: –
Logging enabled: –
Reference Transactions: –
Used PayPal Checkout plugin: –
Subscriptions Mode: Disabled
PayPal Shipping Callback: ✔
Apple Pay: –
Google Pay: –
Fastlane: –

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
onboarding
onboarding-tasks
pattern-toolkit-full-composability
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
printful
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page
launch-your-store
add-to-cart-with-options-stepper-layout

Disabled Features: product-data-views
experimental-blocks
coming-soon-newsletter-template
minified-js
product-pre-publish-modal
settings
async-product-editor-category-field
product-editor-template-system
use-wp-horizon
blockified-add-to-cart

Daily Cron: ✔ Next scheduled: 2025-07-05 00:21:09 +00:00
Options: ✔
Notes: 74
Onboarding: completed

### Action Scheduler ###

Complete: 1,528
Oldest: 2025-06-04 01:23:55 +0000
Newest: 2025-07-04 23:50:20 +0000

Failed: 5
Oldest: 2025-05-18 00:22:23 +0000
Newest: 2025-06-05 18:11:04 +0000

Pending: 3
Oldest: 2025-07-04 23:52:20 +0000
Newest: 2025-07-05 03:53:55 +0000


### Status report information ###

Generated at: 2025-07-04 23:51:50 +00:00
```
</details>

### Isolating the problem

- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by harrowmykel**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

removed excessive argument passed to set_total

Closes #59453 .

(For Bug Fixes) Bug introduced in PR #29318 .

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [x] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 
removed excessive arguments from set_total
</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce/includes/class-wc-cart-totals.php [hunk 1]
```diff
@@ -758,7 +758,7 @@ protected function calculate_item_subtotals() {
 
 		// Prices are not rounded here because they should already be rounded based on settings in `get_rounded_items_total` and in `round_line_tax` method calls.
 		$this->set_total( 'items_subtotal', $items_subtotal );
-		$this->set_total( 'items_subtotal_tax', array_sum( $merged_subtotal_taxes ), 0 );
+		$this->set_total( 'items_subtotal_tax', array_sum( $merged_subtotal_taxes ));
```
Comment (nerrad) [inline plugins/woocommerce/includes/class-wc-cart-totals.php]: Add missing space (lint rules)
```suggestion
		$this->set_total( 'items_subtotal_tax', array_sum( $merged_subtotal_taxes ) );
```

**Review by nerrad — COMMENTED** [review]
Thanks for catching this and submitting a fix! There's a minor issue with the bracket spacing.

**Review by nerrad — APPROVED** [review]
