### PR TITLE
[WIP] CYS - Core: add integration with the font library

### LINKED ISSUE #41924: [CYS on Core] Ensure the fonts selected in the Assembler are displayed on the frontend
**Issue Description:**

Whenever running the CYS flow and selecting a font for the site, it is not correctly displayed on the front-end:

https://github.com/woocommerce/woocommerce/assets/15730971/9fa56b45-1212-4232-9ef4-ace4033200af

### Steps to Reproduce

- Ensure you have a WordPress install with WooCommerce, WooCommerce Beta Tester, woo-ai, and WooCommerce Blocks plugins installed (latest and greatest versions).
- Ensure your site has Jetpack installed and that your site is connected with JetPack
- Go to Tools > WCA Test Helper > Features and enable the `customize-store` feature.
- Head over to WooCommerce > Home > Customize your store
- Go through the CYS flow as demonstrated in the video above and select a font.
- Save your changes and go to the front end: notice how your selected font is not being correctly picked up/displayed.

### Expected outcome

Whenever a new font is selected in the CYS flow, it should also be rendered on the frontend.

### PR DESCRIPTION
**Pull request by gigitux**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes #41924.

This PR implements the support for the Font Library to allow the user to pick different fonts on the Assembler.

### Font Library API

The Font Library is based on two post types after the [API refactor](https://github.com/WordPress/gutenberg/pull/57688): 
`wp_font_family` -> contains the data related to the Font Family (e.g.: slug)
`wp_font_face` -> includes the data of specific font faces of a particular font family.

There is a strict relationship between these two post types. The `wp_font_family` is the parent post of the `wp_font_face`. For this reason,  it is necessary to create a `wp_font_family`post before installing the various font faces. 

### CYS integration

The fonts installed are defined with the `FONT_FAMILY_TO_INSTALL` constant. 

This constant is created manually by reading the value from the `FONT_PAIRINGS_WHEN_AI_IS_OFFLINE` constant ([source code](https://github.com/woocommerce/woocommerce/blob/6cfe61d2f877329ab02d2a7001125bf4e7fdba91/plugins/woocommerce-admin/client/customize-store/assembler-hub/sidebar/global-styles/font-pairing-variations/constants.ts/#L13-L74)): we want to install only the necessary fonts to reduce the setup time and not install too many fonts. We could create a logic to generate this variable, but at this time, it isn't worth it, in my opinion.

During the initial setup, the client gets the already installed Font Families (and related Font Face). In this way, we can install only the fonts that aren't already installed. ([source code](https://github.com/woocommerce/woocommerce/blob/6cfe61d2f877329ab02d2a7001125bf4e7fdba91/plugins/woocommerce-admin/client/customize-store/design-without-ai/services.ts/#L91-L97)) 

After the setup is finished, when the Assembler is loaded, all the fonts are preloaded. ([source code](https://github.com/woocommerce/woocommerce/blob/6cfe61d2f877329ab02d2a7001125bf4e7fdba91/plugins/woocommerce-admin/client/customize-store/assembler-hub/preload-fonts.tsx)) 

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Create a new WooCommerce installation with this version.
2. Ensure the WooCommerce Beta Tester plugin is installed and activated (available on this monorepo).
3. Head over to `/wp-admin/tools.php?page=woocommerce-admin-test-helper` and enable `customize-store` feature flag.
4. Install this build of Gutenberg that contains the new Font Library API: 
[gutenberg.zip](https://github.com/woocommerce/woocommerce/files/14085546/gutenberg.zip)

5. Visit the `wp-admin/admin.php?page=wc-admin&path=/customize-store`.
6. Open the network tools.
7. Follow the process.
8. Ensure that there are several POST requests to the `/wp/v2/font-families/` endpoint.
9. Click "Change fonts" on the left sidebar.
10. Select different fonts and ensure that the selected font is applied to the first title
11. Visit the `wp-admin/admin.php?page=wc-admin&path=/customize-store`.
12. Open the network tools.
13. Ensure that no POST requests to the `/wp/v2/font-families/` endpoint are done.

image

### Warnings ⚠️ 

- Currently, in some cases, the font assigned to the buttons isn't the correct one #44010.
- Some E2E tests are failing. The reason is that the Font Library API isn't available on the E2E tests env. Before merging this PR, it is necessary to implement a way to detect if the Font Library isn't available to avoid fetching requests to non-existent endpoints. This work will be done in a dedicated PR.

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [x] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [x] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

CYS - Core: add integration with the font library.

#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce-admin/client/customize-store/design-without-ai/services.ts [hunk 1]
```diff
@@ -45,6 +53,72 @@ const installAndActivateTheme = async () => {
 	}
 };
 
+const installFontFamilies = async () => {
```
Comment (nefeline) [inline plugins/woocommerce-admin/client/customize-store/design-without-ai/services.ts:57]: @gigitux I mentioned this a couple of days ago on Slack, but cross-posting here as well: Ideally, I'd recommend attaching the installation of fonts to the moment the user agreed & opted-in to our services rather than during the loading screen in the Assembler: this way we won't impact performance. We _could_ still have this here as an emergency fallback, but ideally, it should be rarely triggered (as the installation of the fonts should be successful during initial onboarding).

**Review by nefeline — CHANGES_REQUESTED** [review]
Thanks for working on this, @gigitux ! A few notes on my end:

1. Whenever running the Assembler for the first time, the default font pairing is not being pre-selected on the sidebar, so it's impossible to determine the one that is currently active:

https://github.com/woocommerce/woocommerce/assets/15730971/febbdaf1-6536-414e-b4d3-ed47fc715b4b

2. Some font pairings are influencing the size of other font pairings:

-  Click on  **Montserrat + Arvo** 
-  Click on **Albert Sans + Lora**, the size is the same. 
-  Click on **Rubik + Inter** and you'll see the font is bigger. 
-  Click back on **Albert Sans + Lora** and check how the font is bigger when compared to the initial **Albert Sans + Lora** pairing right after clicking on **Montserrat + Arvo**

https://github.com/woocommerce/woocommerce/assets/15730971/62553860-ca65-4476-b6e3-d615a4308ae7

Ideally, the size of the fonts should not be affected by the font family changes, independent of the provided combinations.

3. Some fonts don't seem to be changing in certain patterns whenever selected, see example:

https://github.com/woocommerce/woocommerce/assets/15730971/2d9a0fa6-1933-4a96-bb63-cb06496fe48b

I've also left a note regarding the moment when font installation should be triggered

File: plugins/woocommerce-admin/client/customize-store/design-without-ai/services.ts (hunk 1 above)
Comment (gigitux) [reply plugins/woocommerce-admin/client/customize-store/design-without-ai/services.ts:57]: >  Ideally, I'd recommend attaching the installation of fonts to the moment the user agreed & opted-in to our services rather than during the loading screen in the Assembler: this way we won't impact performance. We could still have this here as an emergency fallback, but ideally, it should be rarely triggered (as the installation of the fonts should be successful during initial onboarding).

Currently, the UI/UX for the opted-in view isn't read, and working on this pull request necessitated the installation of fonts. 
It's worth noting that installing these fonts does consume a considerable amount of time. Ideally, I believe it would be more practical to incorporate this process into the setup phase. However, engaging in any detailed discussions on this matter may be premature until we gain clarity on how the interaction should work.

**Comment by gigitux** [comment]
> Thanks for working on this, @gigitux ! A few notes on my end:
> 
> 1. Whenever running the Assembler for the first time, the default font pairing is not being pre-selected on the sidebar, so it's impossible to determine the one that is currently active:
> 
>  Screen.Recording.2024-01-25.at.09.44.00.mov 
> 2. Some font pairings are influencing the size of other font pairings:
> 
> * Click on  **Montserrat + Arvo**
> * Click on **Albert Sans + Lora**, the size is the same.
> * Click on **Rubik + Inter** and you'll see the font is bigger.
> * Click back on **Albert Sans + Lora** and check how the font is bigger when compared to the initial **Albert Sans + Lora** pairing right after clicking on **Montserrat + Arvo**
> 
>  Screen.Recording.2024-01-25.at.10.01.02.mov 
> Ideally, the size of the fonts should not be affected by the font family changes, independent of the provided combinations.
> 
> 3. Some fonts don't seem to be changing in certain patterns whenever selected, see example:
> 
>  Screen.Recording.2024-01-25.at.10.03.47.mov 
> I've also left a note regarding the moment when font installation should be triggered

Regarding the points 2 and 3, I guess that it is something related to this issue https://github.com/woocommerce/woocommerce/issues/44010, but I will double-check them!


Nice catch regarding the first point!

Thanks for your great review! 🙏

File: plugins/woocommerce-admin/client/customize-store/design-without-ai/services.ts (hunk 1 above)
Comment (nefeline) [reply plugins/woocommerce-admin/client/customize-store/design-without-ai/services.ts:57]: > Ideally, I believe it would be more practical to incorporate this process into the setup phase. However, engaging in any detailed discussions on this matter may be premature until we gain clarity on how the interaction should function.

The copy or placement of the user consent don't really matter in this case: what matters is where (and when) the user consent is saved on the DB to trigger an async scheduled action to install the fonts. It's totally fine if you want to combine this work with the implementation of the UX, though. Let's create an issue so we don't lose track of this task.

> It's worth noting that installing these fonts does consume a considerable amount of time.

Yep, that's precisely the reason why I'm recommending not attaching it to the CYS flow, but to the moment consent is granted (which we are planning to add right after the WooCommerce plugin is installed).

Comment (gigitux) [reply plugins/woocommerce-admin/client/customize-store/design-without-ai/services.ts:57]: > The copy or placement of the user consent don't really matter in this case: what matters is where (and when) the user consent is saved on the DB to trigger an async scheduled action to install the fonts. It's totally fine if you want to combine this work with the implementation of the UX, though. Let's create an issue so we don't lose track of this task.

Currently, the fonts are installed via REST API. Currently, no PHP API is available to proceed with the installation of the fonts.

All the logic is inside the REST controller: https://github.com/WordPress/gutenberg/blob/0227f403c70d96fcb65f11394cc58d74e3cf44e6/lib/experimental/fonts/font-library/class-wp-rest-font-faces-controller.php/#L284-L357

Also, all these requests are done in parallel with the creation of the products, so overall, I don't think that it increases the time of the loading.

Comment (gigitux) [reply plugins/woocommerce-admin/client/customize-store/design-without-ai/services.ts:57]: Another crucial aspect to consider is that, as a user, I am only agreeing to the conditions. Therefore, it seems counterintuitive to install fonts when I haven't even initiated the Customize Your Store flow.

Comment (nefeline) [reply plugins/woocommerce-admin/client/customize-store/design-without-ai/services.ts:57]: > Also, all these requests are done in parallel with the creation of the products, so overall, I don't think that it increases the time of the loading.

Could we make a real performance evaluation here to confirm this assumption is correct? I would rather us base this decision (whether the font installation should be preserved within the CYS onboarding flow or not) on real numbers rather than assumptions. In the end this is the primary motivation for detaching the font install from this flow. If we confirm this is accurate, then I don't have any problems with keeping the installation as is.

> Another crucial aspect to consider is that, as a user, I am only agreeing to the conditions. Therefore, it seems counterintuitive to install fonts when I haven't even initiated the Customize Your Store flow.

When the user agrees with the terms and conditions, they are agreeing to allow us to give them the best possible experience, which includes patterns, fonts, and all the good stuff. I'm not too worried, and I don't think anyone would complain about having more fonts available on their site, but we can confirm with the leadership later on if we identify there's a significant real win in performance by detaching this installation from the CYS flow.

Comment (gigitux) [reply plugins/woocommerce-admin/client/customize-store/design-without-ai/services.ts:57]: > Could we make a real performance evaluation here to confirm this assumption is correct? I would rather us base this decision (whether the font installation should be preserved within the CYS onboarding flow or not) on real numbers rather than assumptions. In the end this is the primary motivation for detaching the font install from this flow. If we confirm this is accurate, then I don't have any problems with keeping the installation as is.

I already did an evaluation, but if you prefer a more in-depth check, I'm happy to do it. This is the site without products and without fonts with the current branch:


https://github.com/woocommerce/woocommerce/assets/4463174/7d4b5ebc-0bc7-4eed-8f9a-c23ae43145ff

As you can see, while all the requests regarding fonts are done, the request to generate the products is still pending.

In this video, I'm filtering the request by time. The `/products` endpoint is the last and it is long 7 seconds:
https://github.com/woocommerce/woocommerce/assets/4463174/a4ab6578-76ee-4e78-bdf9-0fadf431a24e

In the video below, I'm using trunk, and as you can see the request to `/products` endpoint is still the last and it is still long 7 seconds:

https://github.com/woocommerce/woocommerce/assets/4463174/5295fad0-5c19-4873-acd2-2fab00bb9c84

> When the user agrees with the terms and conditions, they are agreeing to allow us to give them the best possible experience, which includes patterns, fonts, and all the good stuff. I'm not too worried, and I don't think anyone would complain about having more fonts available on their site, but we can confirm with the leadership later on if we identify there's a significant real win in performance by detaching this installation from the CYS flow.

True, but as I said earlier, the only way to install new fonts easily is via REST API. Most of the logic is inside the REST Controllers.

Scheduling the installation of fonts would require us to copy-paste some logic from the REST controllers into our codebase.

Comment (nefeline) [reply plugins/woocommerce-admin/client/customize-store/design-without-ai/services.ts:57]: Thanks for your response, @gigitux : 

> I already did an evaluation, but if you prefer a more in-depth check, I'm happy to do it.

Could you please share here the approx. number in seconds that all fonts are taking to load specifically? I am asking this because:

> As you can see, while all the requests regarding fonts are done, the request to generate the products is still pending.

Just because a completely different endpoint is taking longer to complete (the request to the products endpoint), I don't agree that fonts should be a-ok just because they are under 7s. The request to the products endpoint is a bottleneck that we are discussing & addressing separately: we should treat each one of these requests independently, as they are powering completely different features.

> True, but as I said earlier, the only way to install new fonts easily is via REST API. Most of the logic is inside the REST Controllers.

> Scheduling the installation of fonts would require us to copy-paste some logic from the REST controllers into our codebase.

I see this as an opportunity for us to open a discussion & contribute upstream. We already have a number of occasions where we did copy code from GB to our plugin (e.g., Patterns registration & parts of the CYS flow) to achieve our dedicated goals, so I don't see this as a show-stopper.

We already have a significantly slow loading time on WooExpress, so I'd like us to avoid adding extra time to it whenever we can.

**Comment by gigitux** [comment]
https://github.com/WordPress/gutenberg/pull/58222 implements some changes to the API. fcc774b adapt the code with the new shape of the API

File: plugins/woocommerce-admin/client/customize-store/design-without-ai/services.ts (hunk 1 above)
Comment (gigitux) [reply plugins/woocommerce-admin/client/customize-store/design-without-ai/services.ts:57]: Thank you, @nefeline! I agree with you! We should aim to the fastest onboarding experience! 🚀

> Could you please share here the approx. number in seconds that all fonts are taking to load specifically? I am asking this because:

To be honest, I'm not sure why I'm getting different results today, but I did more accurate test today and the real answer is depend:

### TT4 Installation - Activation + Products creation + Font installation


https://github.com/woocommerce/woocommerce/assets/4463174/4b839c5e-f390-4448-a049-957c1bd76e96



```
THEME: 6182.14404296875 ms
PRODUCTS: 9698.5849609375 ms
FONTS: 11833.39892578125 ms
```
### Products Creation + Font Installation




```
THEME: 2262.531982421875 ms
PRODUCTS: 8595.154052734375 ms
FONTS: 8964.864013671875 ms
```
### TT4 Installation - Activation + Font installation


https://github.com/woocommerce/woocommerce/assets/4463174/8706b485-43e7-4a03-80f9-ff3b82ad5801


```
PRODUCTS: 2318.61083984375 ms
THEME: 5477.593994140625 ms
FONTS: 7278.52587890625 ms
```

###  Font installation


https://github.com/woocommerce/woocommerce/assets/4463174/cf5f49eb-4e58-4dc2-88de-f8657fbabfaf


```
PRODUCTS: 2318.61083984375 ms
THEME: 5477.593994140625 ms
FONTS: 7278.52587890625 ms
```


I agree that we should continue with the optimization, but I'm not sure that an async scheduled action is the right way to go for multiple reasons:

- There isn't PHP API for installing fonts, but as you said, we can contribute upstream and/or copy-paste the code.
- Based on my understanding, the action scheduler operates on a 60-second interval, which means there's a window of time during which fonts may not be installed. This could potentially impact some users who rely on consistent font availability. Furthermore, leveraging the scheduler for longer tasks or features that don't demand immediate user interaction, such as sending emails, can be beneficial. In my opinion, we should delay access to the assembler process until the necessary fonts are available (with the loading screen).

Comment (nefeline) [reply plugins/woocommerce-admin/client/customize-store/design-without-ai/services.ts:57]: Thanks for this performance evaluation for fonts, @gigitux , very useful information: even though the results may vary between 7 to 11s, it is safe to assume that this has a significant impact on performance.

> I agree that we should continue with the optimization, but I'm not sure that an async scheduled action is the right way to go for multiple reasons:
> There isn't PHP API for installing fonts, but as you said, we can contribute upstream and/or copy-paste the code.
> Based on my understanding, the action scheduler operates on a 60-second interval, which means there's a window of time during which fonts may not be installed. 

We can schedule an action to run anytime we want, it will operate whenever we schedule it to run. Take https://github.com/woocommerce/woocommerce/blob/a38c7bcccfab789e7555e9b7c34dc7d15fdd4228/plugins/woocommerce/src/Blocks/BlockPatterns.php#L330 as an example, where the action is scheduled to run immediately.

> This could potentially impact some users who rely on consistent font availability. 

Not really: if we follow an implementation as initially proposed https://github.com/woocommerce/woocommerce/pull/44004#discussion_r1466368360, with a scheduled action installing the fonts whenever the user accepts the terms & conditions combined with an "emergency" fallback font installation during the CYS loading screen to be triggered **only if** the fonts were not yet installed by the time the user reaches the CYS flow, we should cover all possible scenarios while at the same time improving performance.

Comment (gigitux) [reply plugins/woocommerce-admin/client/customize-store/design-without-ai/services.ts:57]: Ok, let's implement the font installation via async job! 🚀

**Comment by gigitux** [comment]
@nefeline With [10cb26e](https://github.com/woocommerce/woocommerce/pull/44004/commits/10cb26e175e7e386a83a2126999718fa262d5179) I did another optimization to improve the font installation speed.

I think that it could make sense to review/merge this PR because it is already pretty big. As follow-up:
- we have to implement the async job to install the fonts via PHP -> I will create an issue
- we have to fix that the default font pairing is not being pre-selected on the sidebar -> I will create an issue
- Check the rest of the issue with the font paring in this: https://github.com/woocommerce/woocommerce/issues/44010 because there could be some correlation.

WDYT?

**Review by nefeline — APPROVED** [review]
> @nefeline With https://github.com/woocommerce/woocommerce/pull/44004/commits/10cb26e175e7e386a83a2126999718fa262d5179 I did another optimization to improve the font installation speed.

Excellent! Thanks for your work here, @gigitux. 

> I think that it could make sense to review/merge this PR because it is already pretty big. As follow-up:

Agreed 🤝 . Adding a note here for future reference the following issues must be addressed in order to ensure a successful implementation of this feature on core:

https://github.com/woocommerce/woocommerce/issues/44259
https://github.com/woocommerce/woocommerce/issues/44258
https://github.com/woocommerce/woocommerce/issues/44257
https://github.com/woocommerce/woocommerce/issues/44010

With that said, I'm going ahead and approving the PR so we can unblock the work for the aforementioned bug fixes & improvements.

File: plugins/woocommerce-admin/client/customize-store/design-without-ai/services.ts (hunk 1 above)
Comment (nefeline) [reply plugins/woocommerce-admin/client/customize-store/design-without-ai/services.ts:57]: For future reference: https://github.com/woocommerce/woocommerce/issues/44257 has been created for this implementation

**Comment by gigitux** [comment]
> > @nefeline With [10cb26e](https://github.com/woocommerce/woocommerce/commit/10cb26e175e7e386a83a2126999718fa262d5179) I did another optimization to improve the font installation speed.
> 
> Excellent! Thanks for your work here, @gigitux.
> 
> > I think that it could make sense to review/merge this PR because it is already pretty big. As follow-up:
> 
> Agreed 🤝 . Adding a note here for future reference the following issues must be addressed in order to ensure a successful implementation of this feature on core:
> 
> #44259 #44258 #44257 #44010
> 
> With that said, I'm going ahead and approving the PR so we can unblock the work for the aforementioned bug fixes & improvements.

Thanks for the review and for opening these issues! 🚀
