### PR TITLE
Ensure the table handler is only loaded once. Prevents multiple loads if a plugin calls check_ajax_referer many times.

### LINKED ISSUE #18696: Order list get broken, can't see,edit orders after update 3.3.0
Order list is not working properly. 
Issues - 
Can't edit or display order no. 
Can't pdf invoices
Can't see order details 

Everything is blank there. Only seeing address of customer and vendor name.

### PR DESCRIPTION
**Pull request by mikejolley**
This prevents a conflict with Smart Coupons which causes the order screen to not load at all, or load data multiple times.

Closes #18696

### CODE REVIEW

File: includes/admin/class-wc-admin-post-types.php [hunk 1]
```diff
@@ -101,6 +101,10 @@ public function setup_screen() {
 				new WC_Admin_List_Table_Products();
 				break;
 		}
+
+		// Ensure the table handler is only loaded once. Prevents multiple loads if a plugin calls check_ajax_referer many times.
+		remove_action( 'current_screen', array( $this, 'setup_screen' ) );
```
Comment (rodrigoprimo) [inline includes/admin/class-wc-admin-post-types.php]: Do we need to remove this action as well? It seems to me that we only need to remove `check_ajax_referer`. Not that removing `current_screen` will cause any issues.

**Review by rodrigoprimo — APPROVED** [review]
I can confirm that this change fixes the problem and it seems safe to me to merge it.

Besides the comment that I left, I'm also curious to know why do we need to add an action to `check_ajax_referer`? Feel free to ignore this question if you don't remember the answer off the top of your head.

File: includes/admin/class-wc-admin-post-types.php (hunk 1 above)
Comment (mikejolley) [reply includes/admin/class-wc-admin-post-types.php]: Prevents any possibility of double loading. check_ajax_referer is there so it works when you do an inline-edit (this loads in the row again via ajax).
