### PR TITLE
Fix: Variable product price with tax is not match in Schema

### LINKED ISSUE #31271: Variable product price with tax is not match in Schema
**Prerequisites (mark completed items with an [x]):**
- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
When selected the **Yes, I will enter prices inclusive of tax** as **Prices entered with tax** at WooCommerce -> Settings, variable product has prices with tax, but in **schema**, it is priced without tax.

**Expected behavior**
In variable product schema, price should be shown with tax.

**Actual behavior**
Variable products show price with tax, but in the schema, the tax is not included.

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Go to WooCommerce -> Settings.
2. Click on  **Enable tax rates and calculations**
3. Click on the tab named **Tax**
4. Scroll to **Prices entered with tax** option at **Tax options** tab.
5. Select **Yes, I will enter prices inclusive of tax**
6. Add standard tax of 10%
7. View any variable product.
8. Copy the page source.
9. Page it to https://validator.schema.org/
10. The lowPrice and highPrice at offers are different than the variable product page

**Screenshots**
1. image
2. image
3. image

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
`
### WordPress Environment ###

WordPress address (URL): http://localhost/wordpress/org
Site address (URL): http://localhost/wordpress/org
WC Version: 5.9.0
REST API Version: ✔ 5.9.0
WC Blocks Version: ✔ 6.1.0
Action Scheduler Version: ✔ 3.3.0
WC Admin Version: ✔ 2.8.0
Log Directory Writable: ✔
WP Version: 5.8.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.41 (Ubuntu)
PHP Version: 7.4.25
PHP Post Max Size: 20 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.68.0
OpenSSL/1.1.1f

SUHOSIN Installed: –
MySQL Version: 8.0.27-0ubuntu0.20.04.1
Max Upload Size: 20 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 5.9.0
WC Database Prefix: wp_
Total Database Size: 7.64MB
Database Data Size: 5.16MB
Database Index Size: 2.48MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.05MB + Index: 0.13MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.05MB + Index: 0.09MB + Engine InnoDB
wp_icl_content_status: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_core_status: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_languages: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_icl_languages_translations: Data: 0.20MB + Index: 0.17MB + Engine InnoDB
wp_icl_locale_map: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_message_status: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_icl_mo_files_domains: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_node: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_reminders: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_string_batches: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_string_packages: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_string_pages: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_icl_string_positions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_string_status: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_string_translations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_icl_string_urls: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_strings: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_icl_translate: Data: 0.08MB + Index: 0.02MB + Engine InnoDB
wp_icl_translate_job: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_translation_batches: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_translation_downloads: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_translation_status: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_translations: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 3.05MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.14MB + Index: 0.11MB + Engine InnoDB
wp_posts: Data: 0.08MB + Index: 0.06MB + Engine InnoDB
wp_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_trp_dictionary_en_us_bn_bd: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_trp_gettext_bn_bd: Data: 0.05MB + Index: 0.05MB + Engine InnoDB
wp_trp_gettext_en_us: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_trp_original_meta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_trp_original_strings: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wdr_order_discounts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wdr_order_item_discounts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wdr_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpr_rucss_resources: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wpr_rucss_used_css: Data: 0.02MB + Index: 0.05MB + Engine InnoDB

### Post Type Counts ###

attachment: 69
language_switcher: 4
nav_menu_item: 4
page: 15
post: 1
product: 19
product_variation: 7
revision: 1

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (5) ###

FakerPress: by Gustavo Bordoni – 0.5.1
CTX Feed: by WebAppick – 4.4.37
WOOCS - WooCommerce Currency Switcher: by realmag777 – 1.3.7.1
WooCommerce: by Automattic – 5.9.0
WP Crontrol: by John Blackbourn & crontributors – 1.11.0

### Inactive Plugins (9) ###

Code Snippets: by Code Snippets Pro – 2.14.2
TranslatePress - Multilingual: by Cozmoslabs
Razvan Mocanu
Madalin Ungureanu
Cristophor Hurduban – 2.1.6

Ultimate Member: by Ultimate Member – 2.2.5
WooCommerce Multilingual: by OnTheGoSystems – 4.12.1
Woo Discount Rules: by Flycart – 2.3.10
WPML Multilingual CMS: by OnTheGoSystems – 4.4.10
WPML String Translation: by OnTheGoSystems – 3.1.8
WPML Translation Management: by OnTheGoSystems – 2.10.6
WP Rocket: by WP Media – 3.9.2

### Dropin Plugins (1) ###

advanced-cache.php: advanced-cache.php

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #6 - /
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 3.8.1 (update to version 3.9.1 is available)
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 91
Oldest: 2021-10-22 09:40:19 +0000
Newest: 2021-11-22 07:41:12 +0000

### Status report information ###

Generated at: 2021-11-22 07:54:22 +00:00
`
</details>

### PR DESCRIPTION
**Pull request by masteradhoc**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:
Variable products always showed the price without tax - ignoring the woocommerce_tax_display_shop setting (including or excluding taxes). 

Closes #31271 .

(For Bug Fixes) Bug introduced in PR # .

### Screenshots or screen recordings:

**PRODUCT**
image

**BEFORE**
`"@type":"AggregateOffer","lowPrice":"420.07","highPrice":"941.83","offerCount":2,"priceValidUntil":"2026-12-31","availability":"https://schema.org/InStock"`

**AFTER**
`"@type":"AggregateOffer","lowPrice":"462.08","highPrice":"1036.01","offerCount":2,"priceValidUntil":"2026-12-31","availability":"https://schema.org/InStock"`

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Go to WooCommerce -> Settings.
2. Click on Enable tax rates and calculations
3. Click on the tab named Tax
4. Scroll to Prices entered with tax option at Tax options tab.
5. Select Yes, I will enter prices inclusive of tax
6. Set Prices in Shop "Excluding Tax"
7. Add standard tax of 10% at "Standard rates"
8. View any variable product.
9. Copy the page source.
10. Page it to https://validator.schema.org/
11. The lowPrice and highPrice at offers are not different anymore and are same as on the variable product page
12. try now when setting " No, I will enter prices exclusive of tax" and Display prices in the shop "Including Tax" if it works as well

### Milestone

- [x] Automatically assign milestone for the **[next WooCommerce version](../blob/trunk/plugins/woocommerce/woocommerce.php#L6)**

> **Note:** Check the box above to have the milestone automatically assigned when merged.
> Alternatively (e.g. for point releases), manually assign the appropriate milestone.

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 
Show variable product price in schema based on woocommerce_tax_display_shop setting so the visual prices matches the schema price
</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

**Comment by gigitux** [comment]
Thanks for opening this PR. Should the `valueAddedTaxIncluded` key handle the price with the taxes included? 

https://github.com/woocommerce/woocommerce/blob/155aaa2f699c8cddcba0941c67184c3ab458d4b8/plugins/woocommerce/includes/class-wc-structured-data.php#L244-L250

cc @Aljullu given that reviewed https://github.com/woocommerce/woocommerce/pull/52105 and could have more context than me.

**Review by Aljullu — COMMENTED** [review]
Thanks for working on this, @masteradhoc, and good catch with the issue!

I confirm this PR fixes the issue for variable products, but I can still reproduce the issue with simple products: the prices in the Schema include taxes even if the settings are to display prices without taxes. Can you reproduce too? I wonder if we should use [`wc_get_price_including_tax()`](https://github.com/woocommerce/woocommerce/blob/f1481e26f73a9b23be9203b5668b7353853ac14b/plugins/woocommerce/includes/wc-product-functions.php#L1182) instead of `$product->get_regular_price()`.

Besides that, and as @gigitux mentioned, we will need to update the `valueAddedTaxIncluded` boolean.

To be honest, I think the current implementation we have is wrong. It uses `wc_prices_include_tax()`, which is tied to the '_Prices entered with tax_' setting. Instead, I think we should use `'incl' === get_option( 'woocommerce_tax_display_shop' )`, which is tied to the '_Display prices in the shop_' setting.

```diff
 array( 
 	'@type'                 => 'UnitPriceSpecification', 
 	'price'                 => wc_format_decimal( $lowest, wc_get_price_decimals() ), 
 	'priceCurrency'         => $currency, 
- 	'valueAddedTaxIncluded' => wc_prices_include_tax(),
+ 	'valueAddedTaxIncluded' => 'incl' === get_option( 'woocommerce_tax_display_shop' ),
 	'validThrough'          => $price_valid_until, 
 ), 
```

Let us know how it sounds!

**Comment by masteradhoc** [comment]
@gigitux @Aljullu thank you very much for the feedback and sorry for the late reply.

I reworked my PR a bit to match your feedback and also make it work for simple products. My tests focused now on this setting here

/wp-admin/admin.php?page=wc-settings&tab=tax&section
"Display prices in the shop"

Used Validator Tool: https://validator.schema.org/

Here a result of my test

**1) "Display prices in the shop" = Excluding tax**

Simple Product with Sale Price
-----------------
image
image

Variable Product with Sale Price
-----------------
image
image


Grouped Product with Sale Price
-----------------
image
image


**2) "Display prices in the shop" = Including tax**

Simple Product with Sale Price
-----------------
image
image


Variable Product with Sale Price
-----------------
image
image


Grouped Product with Sale Price
-----------------
image
image


After this adjustment i also removed all the sale prices and checked once again with the setting to include or exclude tax . Also this works great now.

Could you recheck this please as well?

File: plugins/woocommerce/includes/class-wc-structured-data.php [hunk 1]
```diff
@@ -340,17 +340,21 @@ public function generate_product_data( $product = null ) {
...
+				$regular_price    = 'incl' === $tax_display_mode
+					? wc_get_price_including_tax( $product, array( 'price' => $product->get_regular_price() ) )
+					: wc_get_price_excluding_tax( $product, array( 'price' => $product->get_regular_price() ) );
 				$unit_price_specification = array(
 					'@type'                 => 'UnitPriceSpecification',
-					'price'                 => wc_format_decimal( $product->get_regular_price(), wc_get_price_decimals() ),
+					'price'                 => wc_format_decimal( $regular_price, wc_get_price_decimals() ),
 					'priceCurrency'         => $currency,
-					'valueAddedTaxIncluded' => wc_prices_include_tax(),
+					'valueAddedTaxIncluded' => 'incl' === get_option( 'woocommerce_tax_display_shop' ),
```
Comment (Aljullu) [inline plugins/woocommerce/includes/class-wc-structured-data.php]: Small optimization: we can use `$tax_display_mode` here, right?

```diff
-					'valueAddedTaxIncluded' => 'incl' === get_option( 'woocommerce_tax_display_shop' ),
+					'valueAddedTaxIncluded' => 'incl' === $tax_display_mode,
```

File: plugins/woocommerce/includes/class-wc-structured-data.php [hunk 2]
```diff
@@ -376,9 +383,9 @@ public function generate_product_data( $product = null ) {
 						$markup_offer['priceSpecification'],
 						array(
 							'@type'                 => 'UnitPriceSpecification',
-							'price'                 => wc_format_decimal( $product->get_sale_price(), wc_get_price_decimals() ),
+							'price'                 => wc_format_decimal( $sale_price, wc_get_price_decimals() ),
 							'priceCurrency'         => $currency,
-							'valueAddedTaxIncluded' => wc_prices_include_tax(),
+							'valueAddedTaxIncluded' => 'incl' === get_option( 'woocommerce_tax_display_shop' ),
```
Comment (Aljullu) [inline plugins/woocommerce/includes/class-wc-structured-data.php]: Same here:

```diff
-							'valueAddedTaxIncluded' => 'incl' === get_option( 'woocommerce_tax_display_shop' ),
+							'valueAddedTaxIncluded' => $tax_display_mode,
```

File: plugins/woocommerce/includes/class-wc-structured-data.php [hunk 3]
```diff
@@ -259,7 +259,7 @@ public function generate_product_data( $product = null ) {
 					);
 
 					if ( $product->is_on_sale() ) {
-						$lowest_child_sale_price = $product->get_variation_sale_price( 'min', false );
+						$lowest_child_sale_price = $product->get_variation_sale_price( 'min', true );
 						foreach ( $product->get_variation_prices()['sale_price'] as $variation_id => $variation_price ) {
```
Comment (Aljullu) [inline plugins/woocommerce/includes/class-wc-structured-data.php]: Should we update this so [`get_variations_prices()`](https://github.com/woocommerce/woocommerce/blob/1e234e15806b693f6c26a19696674aa085035619/plugins/woocommerce/includes/class-wc-product-variable.php#L99) is also called with `for_display = true`?

I even think we could store it in a variable:

```PHP
$variation_prices = $product->get_variation_prices( true );
```

So it can be re-used in L258 and L263.

File: plugins/woocommerce/includes/class-wc-structured-data.php [hunk 4]
```diff
@@ -234,8 +234,8 @@ public function generate_product_data( $product = null ) {
 			$price_valid_until = gmdate( 'Y-12-31', time() + YEAR_IN_SECONDS );
 
 			if ( $product->is_type( ProductType::VARIABLE ) ) {
-				$lowest  = $product->get_variation_price( 'min', false );
-				$highest = $product->get_variation_price( 'max', false );
+				$lowest  = $product->get_variation_price( 'min', true );
+				$highest = $product->get_variation_price( 'max', true );
```
[the remark this answers is not in the document]
Comment (Aljullu) [reply plugins/woocommerce/includes/class-wc-structured-data.php:238]: This has been fixed in 72867742981783bd6e335e7d21b362be1d40ce69.

**Review by Aljullu — COMMENTED** [review]
Thanks for the updates, @masteradhoc! They look great. I made a couple of extra suggestions that I missed in the first review, but overall looking good.

**Update:**

Btw, can you add this to the PR description? We have a new job in GitHub that requires this to be in the PR description so the `milestone` field is set automatically when merging the PR.

```
### Milestone

<!-- milestone-target-selection -->
- [x] Automatically assign milestone for the **[next WooCommerce version](../blob/trunk/plugins/woocommerce/woocommerce.php#L6)**
<!-- /milestone-target-selection -->
```

File: plugins/woocommerce/includes/class-wc-structured-data.php (hunk 3 above)
Comment (masteradhoc) [reply plugins/woocommerce/includes/class-wc-structured-data.php]: @Aljullu guess you meant like this right? https://github.com/masteradhoc/woocommerce/commit/ef87a7b662814ffcbac4b6615e1b200f3ffce466
would definately make sense!

Comment (Aljullu) [reply plugins/woocommerce/includes/class-wc-structured-data.php]: Yes, exactly! :slightly_smiling_face:

File: plugins/woocommerce/includes/class-wc-structured-data.php [hunk 5]
```diff
@@ -312,7 +314,7 @@ public function generate_product_data( $product = null ) {
 					'@type'                 => 'UnitPriceSpecification',
 					'price'                 => wc_format_decimal( $min_price, wc_get_price_decimals() ),
 					'priceCurrency'         => $currency,
-					'valueAddedTaxIncluded' => wc_prices_include_tax(),
+					'valueAddedTaxIncluded' => 'incl' === get_option( 'woocommerce_tax_display_shop' ),
```
Comment (Aljullu) [inline plugins/woocommerce/includes/class-wc-structured-data.php]: I missed this one, but we can use `$tax_display_mode` here too.

File: plugins/woocommerce/includes/class-wc-structured-data.php [hunk 6]
```diff
@@ -340,17 +342,21 @@ public function generate_product_data( $product = null ) {
 							'@type'                 => 'UnitPriceSpecification',
 							'price'                 => wc_format_decimal( $min_sale_price, wc_get_price_decimals() ),
 							'priceCurrency'         => $currency,
-							'valueAddedTaxIncluded' => wc_prices_include_tax(),
+							'valueAddedTaxIncluded' => 'incl' === get_option( 'woocommerce_tax_display_shop' ),
```
Comment (Aljullu) [inline plugins/woocommerce/includes/class-wc-structured-data.php]: And here. 🙂

File: plugins/woocommerce/includes/class-wc-structured-data.php (hunk 3 above)
Comment (masteradhoc) [reply plugins/woocommerce/includes/class-wc-structured-data.php]: Perfect, then we're ready to get this merged? @Aljullu

File: plugins/woocommerce/includes/class-wc-structured-data.php [hunk 7]
```diff
@@ -340,17 +342,21 @@ public function generate_product_data( $product = null ) {
...
 							'validThrough'          => $sale_price_valid_until ?? $price_valid_until,
 						)
 					);
 				}
 			} else {
+				$tax_display_mode = get_option( 'woocommerce_tax_display_shop' );
+				$regular_price    = 'incl' === $tax_display_mode
```
Comment (Aljullu) [inline plugins/woocommerce/includes/class-wc-structured-data.php]: There is a small linting issue here, these `=` should be aligned with the one in L355.

**Review by Aljullu — COMMENTED** [review]
Thanks for the updates, @masteradhoc! This is looking good to me. I left a couple of minor suggestions, but that's all. There are a couple of things that need to be done before we can merge:

* Adding a changelog entry, either running `pnpm --filter='@woocommerce/plugin-woocommerce' changelog add` or updating the `Changelog entry` section in the PR description.
* There are some PHPStan warnings. Inside `plugins/woocommerce`, can you run `pnpm phpstan:baseline` to update the registered errors and include the update file in this PR? We should make sure no new errors are introduced.

Something I also noticed is that we are printing `valueAddedTaxIncluded` (either true or false) when the _Enable tax rates and calculations_ WC setting is disabled. I think we shouldn't print `valueAddedTaxIncluded` at all in that case. But this is not strictly related to this PR, though, so I can create a separate issue for it. 🙂

**Comment by masteradhoc** [comment]
@Aljullu adjusted your requests, thanks again!
Could you approve this please so [PHPStan runs on the PR itself](https://github.com/woocommerce/woocommerce/actions/runs/21880535663)? then we'll have it documented right away.

**Comment by Aljullu** [comment]
@masteradhoc I run the automations in this PR. Will you be able to review the [linting](https://github.com/woocommerce/woocommerce/actions/runs/21899223233/job/63231940868?pr=61662) and [PHPStan](https://github.com/woocommerce/woocommerce/actions/runs/21899223259/job/63231904851?pr=61662) issues? :pray:

**Review by Aljullu — APPROVED** [review]
Thanks for fixing the linting issues, @masteradhoc! I pushed an updated `phpstan-baseline.neon` file, so now all jobs pass. I did another round of testing, and everything is looking good in all product types and with different tax settings. Let's get this merged and released in WC 10.6. 🚀
