### PR TITLE
Fix menu icon active state when navigating between wc-admin pages

### LINKED ISSUE #55896: Active status for WC's menu icon isn't updated correctly when switching between wc-admin pages
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

There are several menu items (inside the **WooCommerce** menu but also **Analytics** or **Marketing**) that have `admin.php?page=wc-admin` as base (examples: WooCommerce > Customers, or Analytics > Overview). When navigating between these menu items, the "active" (or inactive) status of the main **WooCommerce** menu icon is not always correctly updated.

### Expected behavior

The WooCommerce menu icon should always reflect the menu in which the current page is contained. Also, Analytics menu should open smoothly when activated.

### Actual behavior

The WooCommerce menu icon can remain active when navigating from an item inside the WooCommerce menu to a wc-admin page outside of it.
Conversely, navigating from a wc-admin page outside of the menu to a wc-admin page inside the menu leaves the icon in an inactive state.

Also, the Analytics menu doesn't slide up smoothly.

https://github.com/user-attachments/assets/356468d3-a835-4cdb-a4cc-bcd2bf17b4c7

### Steps to reproduce

1. Go to WooCommerce > Home.
2. Navigate to Analytics > Overview.
3. Notice how the Analytics menu slides up. Animation isn't smooth.
4. Confirm that the WooCommerce menu icon remains active (when it should be inactive).
5. Reload the page (while you remain inside Analytics > Overview).
6. Navigate to WooCommerce > Home.
7. Confirm that the WooCommerce menu icon remains inactive (when it should be active).

### WordPress Environment

N/A

### Isolating the problem

- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by chihsuan**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes https://github.com/woocommerce/woocommerce/issues/55896

This PR fixes the WooCommerce menu icon's active state not updating correctly when navigating between wc-admin pages.

Two issues are fixed in this PR:

1. The WooCommerce menu icon's active state was not updating correctly when navigating between wc-admin pages.
2. Analytics menu doesn't slide up smoothly.

The first issue is fixed by calling `wp.svgPainter.paint()` after updating the menu state. This ensures the WooCommerce icon updates correctly. We also detach the SVG painting event handlers to prevent the active state from resetting on hover. The reason why only WooCommerce icon is affected is because it's a custom SVG icon and the rest of the icons are Dashicons that natively support the active state.

The second issue is fixed by resting the margin-top of the submenu to 0 before the menu is opened.

I've also made some other improvements to the codebase:

1. Added inline comments to explain the `wpNavMenuClassChange` function so that it's easier to understand.
2. Add checks before doing some DOM operations to reduce the number of operations that are performed.

### Screenshots or screen recordings:

Before:

https://github.com/user-attachments/assets/356468d3-a835-4cdb-a4cc-bcd2bf17b4c7  

After:

https://github.com/user-attachments/assets/7da5da91-785a-45a5-b329-bd533f032f95  

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Go to `WooCommerce > Home`
2. Navigate to `Analytics > Overview`
3. Verify that:
   - The Analytics menu slides up smoothly
   - The WooCommerce menu icon becomes inactive (grey)
4. Navigate to `WooCommerce > Home`
5. Verify that:
   - The WooCommerce menu icon becomes active (white)
   - The menu state correctly reflects the current page's conte
6. Navigate between other wc admin pages such as Marketing, Payments and ensure that the menu icon's active state is updated correctly.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce/client/admin/client/layout/controller.js [hunk 1]
```diff
@@ -501,35 +501,67 @@ window.wpNavMenuUrlUpdate = function ( query ) {
 	);
 };
 
+// Cache custom SVG menu items to prevent repeated DOM queries. This is necessary to remove event handlers when the route changes in window.wpNavMenuClassChange.
+const customSVGMenuItems = [];
+const getCustomSVGMenuItems = () => {
+	// Get all menu items with SVG backgrounds
+	// See: https://github.com/WordPress/wordpress-develop/blob/22bebd7de6681c673933953aab8c08802e7e3d4a/src/js/_enqueues/wp/svg-painter.js#L140-L148
+	const menuItems = window.jQuery(
+		'#adminmenu .wp-menu-image, #wpadminbar .ab-item'
```
Comment (ilyasfoo) [inline plugins/woocommerce/client/admin/client/layout/controller.js:510]: This query includes the adminbar icons. Is this expected?

image

**Review by ilyasfoo — APPROVED** [review]
Nice work here, @chihsuan! Left a comment but LGTM

#### Review checklist

| Parameter  | Result |
| ------------- | ------------- |
| Approach  | ✅ All good |
| Implementation  | ✅ All good |
| Automated tests  | ✅ All good |
| Naming  | ✅ All good |
| Typing  | ✅ All good |
| Code comments  | ✅ All good |
| Changelog  | ✅ All good |
| Documentation  | Not applicable |
| PR description  | ✅ All good |
| Testing instructions  | Not applicable |
| Manual testing  | ✅ Works as expected |

#### Scenarios tested

| Scenario  | Result | Screenshot |
| ------------- | ------------- | ------------- |
| Menu icon color change and analytics menu slide smoothly | ✅ Functionality worked correctly | https://github.com/user-attachments/assets/885f2818-4217-4f85-ab63-9c73f819cd99 |
| Responsive menu | ✅ Functionality worked correctly | https://github.com/user-attachments/assets/2cb515f7-2eff-4edb-bf33-b4ce99adacc4 |

File: plugins/woocommerce/client/admin/client/layout/controller.js (hunk 1 above)
Comment (chihsuan) [reply plugins/woocommerce/client/admin/client/layout/controller.js:510]: It's expected. The selector matches the one used in svg-painter.js. While we could improve it with a more specific selector, I prefer to leave it as is to maintain consistency with WP Core.

https://github.com/WordPress/wordpress-develop/blob/22bebd7de6681c673933953aab8c08802e7e3d4a/src/js/_enqueues/wp/svg-painter.js#L123

Comment (ilyasfoo) [reply plugins/woocommerce/client/admin/client/layout/controller.js:510]: Sounds good, thanks for checking!

**Review by psealock — COMMENTED** [review]
Thanks @chihsuan, this is all looking good and testing well. Just on small thing I noticed:

When I'm on a subpage of non-wc-admin WooCommerce, such as WooCommerce > Settings and I click on WooCommerce, there is a 1px shift of the menu downwards. Can you see it?

image

**Comment by chihsuan** [comment]
> When I'm on a subpage of non-wc-admin WooCommerce, such as WooCommerce > Settings and I click on WooCommerce, there is a 1px shift of the menu downwards. Can you see it?

@psealock Yes, I can see it. Great catch. 👍 

I also discovered a similar issue: When focusing or unfocusing the WooCommerce menu item, the menu shifts slightly.

https://github.com/user-attachments/assets/d2fc06d6-f453-4eb6-be37-ffe9ece32bdb

This is due to two CSS rules:

1. When focusing on a menu item, WP core sets the `top` property to `-1` for the `.wp-submenu` element.  I think it works for non-WC admin pages, but not for WC admin pages. 

Screenshot 2025-03-17 at 12 45 25


3. We have a rule that sets `padding-bottom: 1px` for the WC `.menu-top` element when focusing. This was added in [this PR](https://github.com/woocommerce/woocommerce-admin/pull/70) to fix a [jumping issue](https://github.com/woocommerce/woocommerce-admin/pull/70#pullrequestreview-122221184) on the top-level WC menu. I think it might have been necessary in older WP versions but is no longer needed. 🤔 

I've fixed issues in 13258011c39c8fe34152e29e7f9c00fee9d05b0a.

Please test it again and make sure no regression. Thanks!

https://github.com/user-attachments/assets/c3028cc2-61a3-4ee0-b324-8422dc896b5f

**Review by psealock — APPROVED** [review]
Thanks for the changes @chihsuan. This is looking good, no regressions found and changes make sense. I also checked behaviour on narrow screens, which is functioning as expected.
