### PR TITLE
[WOOPLUG-6353] add: orphaned fulfillment records when order is deleted

### LINKED ISSUE #63467: [Order Fulfillments] Orphaned fulfillment records when order is deleted
## Bug Report

**Source:** [GitHub Discussion #60922 — EdithAllison (Sep 23, 2025)](<https://github.com/woocommerce/woocommerce/discussions/60922>)

**Description:**<br>When an order is deleted, associated fulfillment records are not cascade-deleted, leaving orphaned rows in the fulfillments database table. This can lead to data integrity issues over time, especially for stores that frequently delete test or cancelled orders.

**Expected behavior:**<br>Deleting an order should also delete all associated fulfillment records and their metadata from the database.

**Steps to reproduce:**

1. Create an order and add a fulfillment to it.
2. Delete the order (trash and permanently delete).
3. Query the fulfillments table — orphaned records remain.

**Impact:** Data integrity issue. Over time, orphaned records accumulate in the database.

### PR DESCRIPTION
**Pull request by tpaksu**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

When an order is permanently deleted, associated fulfillment records in `wc_order_fulfillments` and `wc_order_fulfillment_meta` tables are not cleaned up, resulting in orphaned rows that accumulate over time.

This PR fixes the data integrity issue by:

- Adding a `delete_by_entity()` method to `FulfillmentsDataStore` that hard-deletes all fulfillment records and their metadata for a given entity, wrapped in a database transaction for atomicity
- Registering order deletion hooks (`woocommerce_before_delete_order` and `before_delete_post`) in `FulfillmentsManager` to trigger fulfillment cleanup when an order is permanently deleted
- Adding unit tests for both the data store deletion method and the manager hook integration

Closes https://github.com/woocommerce/woocommerce/issues/63467 .

Related Linear issue: https://linear.app/a8c/issue/WOOPLUG-6353/order-fulfillments-orphaned-fulfillment-records-when-order-is-deleted

### Screenshots or screen recordings:

| Before | After |
| ------ | ----- |
|        |       |

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://developer.woocommerce.com/docs/contribution/testing/writing-high-quality-testing-instructions/), include your detailed testing instructions:

1. Enable the fulfillments feature flag: set `woocommerce_feature_fulfillments_enabled` option to `yes`.
2. Create a new order and add a fulfillment to it (via the order edit screen or programmatically).
3. Verify the fulfillment record exists by querying: `SELECT * FROM wp_wc_order_fulfillments WHERE entity_id = <order_id>;`
4. Permanently delete the order (move to trash, then delete permanently).
5. Query the fulfillments table again: `SELECT * FROM wp_wc_order_fulfillments WHERE entity_id = <order_id>;`
6. Verify the result is empty; no orphaned records should remain.
7. Also verify the metadata table is clean: `SELECT * FROM wp_wc_order_fulfillment_meta WHERE fulfillment_id = <fulfillment_id>;`

### Testing that has already taken place:

- Unit tests added and passing for `FulfillmentsDataStore::delete_by_entity()` (3 tests: basic deletion, isolation, empty case)
- Unit tests added and passing for `FulfillmentsManager` order deletion hooks (2 tests: hook registration, end-to-end deletion)
- PHPStan analysis passing with no errors
- PHPCS linting passing on all new code

### Milestone

- [x] Automatically assign milestone for the **[next WooCommerce version](../blob/trunk/plugins/woocommerce/woocommerce.php#L6)**

> **Note:** Check the box above to have the milestone automatically assigned when merged.
> Alternatively (e.g. for point releases), manually assign the appropriate milestone.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [x] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 
</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 
Delete orphaned fulfillment records and metadata when an order is permanently deleted.

</details>

### CODE REVIEW

File: plugins/woocommerce/src/Admin/Features/Fulfillments/DataStore/FulfillmentsDataStore.php [hunk 1]
```diff
@@ -629,6 +629,55 @@ public function read_fulfillments( string $entity_type, string $entity_id, bool
...
+				)
+			);
+
+			$wpdb->query( 'COMMIT' );
+		} catch ( \Throwable $e ) {
+			$wpdb->query( 'ROLLBACK' );
+			throw $e;
+		}
+
+		return (int) $rows_deleted;
```
[the remark this answers is not in the document]
Comment (tpaksu) [reply plugins/woocommerce/src/Admin/Features/Fulfillments/DataStore/FulfillmentsDataStore.php]: The current behavior is intentionally defensive and correct.                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                                                                                           
  Why swallowing the exception is the right design here:                                                                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                                                                                                           
  - This runs on woocommerce_before_delete_order / before_delete_post hooks. Re-throwing would block an admin from permanently deleting an order because a secondary cleanup (fulfillment records) failed.                                                                                                                                                 
  - Orphaned fulfillment rows are harmless metadata with no side effects. Blocking order deletion over a transient DB issue or missing table is a worse outcome.                                                                                                                                                                                           
  - The error is already logged, so operators can investigate and clean up if needed.                   
  - WordPress hook callbacks that throw exceptions can cause unpredictable behavior in the hook chain.

  The finding treats orphaned rows as the worst outcome, but preventing a user-initiated order deletion due to a secondary system failure is worse. No change needed.

File: plugins/woocommerce/src/Admin/Features/Fulfillments/FulfillmentsManager.php [hunk 2]
```diff
@@ -67,6 +69,44 @@ private function init_refund_hooks() {
...
+	 * Delete all fulfillment records for an order that is being permanently deleted.
+	 *
+	 * @since 10.7.0
+	 *
+	 * @param int $order_id The ID of the order being deleted.
+	 */
+	public function delete_order_fulfillments( int $order_id ): void {
+		if ( ! OrderUtil::is_order( $order_id, wc_get_order_types() ) ) {
+			return;
+		}
```
Comment (Ferdev) [inline plugins/woocommerce/src/Admin/Features/Fulfillments/FulfillmentsManager.php]: I'd move this to the try/catch block in cae `is_order` throws something unexpected 👍

File: plugins/woocommerce/src/Admin/Features/Fulfillments/DataStore/FulfillmentsDataStore.php [hunk 3]
```diff
@@ -629,6 +629,64 @@ public function read_fulfillments( string $entity_type, string $entity_id, bool
...
+	 *
+	 * @param string $entity_type The entity type (e.g. 'WC_Order').
+	 * @param int    $entity_id   The entity ID.
+	 *
+	 * @return int The number of fulfillment records deleted.
+	 *
+	 * @throws \RuntimeException If a database query fails.
+	 * @throws \Throwable If the deletion fails.
+	 */
+	public function delete_by_entity( string $entity_type, int $entity_id ): int {
```
Comment (Ferdev) [inline plugins/woocommerce/src/Admin/Features/Fulfillments/DataStore/FulfillmentsDataStore.php]: the `$entity_id` argument is an `int` here, but all the other methods in this datastore use `string $entity_id`. I think we should keep this consistent with the other methods signature.

File: plugins/woocommerce/src/Admin/Features/Fulfillments/DataStore/FulfillmentsDataStore.php [hunk 4]
```diff
@@ -629,6 +629,64 @@ public function read_fulfillments( string $entity_type, string $entity_id, bool
...
+		global $wpdb;
+
+		$wpdb->query( 'START TRANSACTION' );
```
Comment (Ferdev) [inline plugins/woocommerce/src/Admin/Features/Fulfillments/DataStore/FulfillmentsDataStore.php]: We should check if this statement runs successfully, otherwise the rest of the sql statements below won't be processed as part of the transaction. So probably returning early here is the best call if this command fails. What do you think?

**Review by Ferdev — COMMENTED** [review]
Left a few comments. The code looks good, but I'd love to hear your thoughts on my suggestions.

I tested it and worked fine 👍

File: plugins/woocommerce/src/Admin/Features/Fulfillments/FulfillmentsManager.php (hunk 2 above)
Comment (tpaksu) [reply plugins/woocommerce/src/Admin/Features/Fulfillments/FulfillmentsManager.php]: Thanks, makes sense, addressed in 545ea64cfb.

File: plugins/woocommerce/src/Admin/Features/Fulfillments/DataStore/FulfillmentsDataStore.php (hunk 3 above)
Comment (tpaksu) [reply plugins/woocommerce/src/Admin/Features/Fulfillments/DataStore/FulfillmentsDataStore.php]: Yep, good catch, it should be string. Addressed.

File: plugins/woocommerce/src/Admin/Features/Fulfillments/DataStore/FulfillmentsDataStore.php (hunk 4 above)
Comment (tpaksu) [reply plugins/woocommerce/src/Admin/Features/Fulfillments/DataStore/FulfillmentsDataStore.php]: I just learned that there's a function that checks for transaction eligibility, named `wc_use_transactions`! I'll use that and be sure that the deletion is successful. Thanks for raising this!

Comment (tpaksu) [reply plugins/woocommerce/src/Admin/Features/Fulfillments/DataStore/FulfillmentsDataStore.php]: Addressed in [6b429db](https://github.com/woocommerce/woocommerce/pull/63572/commits/6b429dba37fceb2ae3d7d1fb6008d72213870d22).

File: plugins/woocommerce/src/Admin/Features/Fulfillments/DataStore/FulfillmentsDataStore.php (hunk 3 above)
Comment (tpaksu) [reply plugins/woocommerce/src/Admin/Features/Fulfillments/DataStore/FulfillmentsDataStore.php]: Thanks, makes sense, addressed in 545ea64cfb.

File: plugins/woocommerce/src/Admin/Features/Fulfillments/DataStore/FulfillmentsDataStore.php (hunk 4 above)
Comment (tpaksu) [reply plugins/woocommerce/src/Admin/Features/Fulfillments/DataStore/FulfillmentsDataStore.php]: Thanks, makes sense, addressed in 6b429dba37. Switched to wc_transaction_query() which handles this and also respects WC_USE_TRANSACTIONS.

File: plugins/woocommerce/tests/php/src/Admin/Features/Fulfillments/DataStore/FulfillmentsDataStoreTest.php [hunk 5]
```diff
@@ -904,4 +904,124 @@ function ( $record ) use ( $meta_key ) {
...
+
+		$rows_deleted = $this->data_store->delete_by_entity( $entity_type, $entity_id );
+
+		$this->assertSame( 2, $rows_deleted, 'Should have deleted 2 fulfillment records' );
+
+		$remaining = $wpdb->get_var(
+			$wpdb->prepare(
+				"SELECT COUNT(*) FROM {$wpdb->prefix}wc_order_fulfillments WHERE entity_type = %s AND entity_id = %d",
+				$entity_type,
+				$entity_id
```
[the remark this answers is not in the document]
Comment (tpaksu) [reply plugins/woocommerce/tests/php/src/Admin/Features/Fulfillments/DataStore/FulfillmentsDataStoreTest.php]: Thanks, addressed in edfcb77d3e.

File: plugins/woocommerce/tests/php/src/Admin/Features/Fulfillments/FulfillmentsManagerTest.php [hunk 6]
```diff
@@ -292,6 +292,62 @@ function ( $providers ) {
...
+					),
+				),
+			)
+		);
+
+		$order_id = $order->get_id();
+
+		$fulfillments_before = $wpdb->get_var(
+			$wpdb->prepare(
+				"SELECT COUNT(*) FROM {$wpdb->prefix}wc_order_fulfillments WHERE entity_type = %s AND entity_id = %d",
```
Comment (Ferdev) [inline plugins/woocommerce/tests/php/src/Admin/Features/Fulfillments/FulfillmentsManagerTest.php]: I think this should be an `$s`:

```suggestion
				"SELECT COUNT(*) FROM {$wpdb->prefix}wc_order_fulfillments WHERE entity_type = %s AND entity_id = %s",
```

**Review by Ferdev — APPROVED** [review]
Looks great, Taha! Thanks for improving this 🙇 

:shipit:

File: plugins/woocommerce/src/Admin/Features/Fulfillments/DataStore/FulfillmentsDataStore.php [hunk 7]
```diff
@@ -621,6 +621,64 @@ public function read_fulfillments( string $entity_type, string $entity_id, bool
...
+		global $wpdb;
+
+		wc_transaction_query( 'start' );
+
+		try {
+			// Delete metadata for all fulfillments belonging to this entity.
+			// phpcs:ignore WordPress.DB.PreparedSQL.InterpolatedNotPrepared -- table names are safe.
+			$result = $wpdb->query(
+				$wpdb->prepare(
+					"DELETE m FROM {$wpdb->prefix}wc_order_fulfillment_meta m INNER JOIN {$wpdb->prefix}wc_order_fulfillments f ON m.fulfillment_id = f.fulfillment_id WHERE f.entity_type = %s AND f.entity_id = %s",
```
Comment (kalessil) [inline plugins/woocommerce/src/Admin/Features/Fulfillments/DataStore/FulfillmentsDataStore.php:649]: @tpaksu : I'm just passing by and curious why not delete in a single statement (like [here](https://stackoverflow.com/a/11442104), via a main table left join meta table)?

Comment (tpaksu) [reply plugins/woocommerce/src/Admin/Features/Fulfillments/DataStore/FulfillmentsDataStore.php:649]: Yea, that would've been a smart thing to do, but I never used that once in my life :)

Comment (tpaksu) [reply plugins/woocommerce/src/Admin/Features/Fulfillments/DataStore/FulfillmentsDataStore.php:649]: Also did you see [this comment](https://stackoverflow.com/questions/3331992/how-to-delete-from-multiple-tables-in-mysql/11442104#comment15565244_11442104)?

Comment (kalessil) [reply plugins/woocommerce/src/Admin/Features/Fulfillments/DataStore/FulfillmentsDataStore.php:649]: Yep, it's niche when you want to execute an atomic deletion without explicitly using transactions.
IIRC, we used this on the payments server at some point. If you want to try it, check if my memory fails first.

> Also, did you see this comment?

Well, it's beyond common sense there. We operate on IDs, which keeps row locking time nearly instant. You can give Claude access to the DB, ask it to back up the tables, and verify how this SQL behaves on different sizes of fulfillment tables.
