### PR TITLE
Fix featured products returning empty on multisite subsites

### LINKED ISSUE #63095: wc_get_products won't return featured products on subsite multisite
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When using the 'featured' flag on a subsite multisite, nothing is returned. 

### Expected behavior

Expected to return featured products.

### Actual behavior

Empty array returned.

### Steps to reproduce

Use 'featured' => true in $args on subsite.

Found work-around: Use tax_query instead.

```php
$args = array(
		'status'   => 'publish',
		'limit'    => 12,
		'orderby'  => 'meta_value_num',
		'meta_key' => 'total_sales',
		'order'    => 'DESC',
		// for whatever reason, 'featured' does not work on multisite's subsite. use direct tax query instead.
		// 'featured' => true,
		'tax_query'	=> array(
			array(
				'taxonomy' => 'product_visibility',
				'field'	=> 'name',
				'terms'	=> array( 'featured' ),
			),
		),
	);
	$featured_products = wc_get_products($args);
```

### WordPress Environment

<details><summary>System Status Report</summary>

```
### WordPress Environment ###

WordPress address (URL): [Redacted]
Site address (URL): [Redacted]
WC Version: 10.4.3
Legacy REST API Package Version: The Legacy REST API plugin is not installed on this site.
Action Scheduler Version: ✔ 3.9.3
Log Directory Writable: ✔
WP Version: 6.9.1
WP Multisite: ✔
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_AU
External object cache: –

### Server Environment ###

Server Info: Apache
Server Architecture: Linux 4.18.0-553.16.1.lve.1.el8.x86_64 x86_64
PHP Version: 8.4.3
PHP Post Max Size: 128 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.61.1
OpenSSL/1.1.1k

SUHOSIN Installed: –
MySQL Version: 10.11.14-MariaDB
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

[REDACTED]

### Post Type Counts ###

acf-field: 122
acf-field-group: 14
af_form: 2
attachment: 256
nav_menu_item: 7
page: 16
post: 3
product: 89
product_variation: 53
revision: 76
section: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (14) ###

Advanced Custom Fields PRO: by WP Engine – 6.7.0.2
Advanced Forms Pro: by Phil Kurth (Hookturn) – 1.9.3.6
Basilisk Global Attributes: by LexGear Development – 0.1
Basilisk SEO: by LexGear Development – 1.0.3
Basilisk Sitemap: by LexGear Development – 1.0.2
Cloudflare: by Cloudflare
Inc. – 4.14.2

Site Kit by Google: by Google – 1.171.0
Mailchimp for WooCommerce: by Mailchimp – 5.6
PPOM Pro for WooCommerce: by Themeisle – 26.0.8
reCAPTCHA for WooCommerce: by Elliot Sowersby
RelyWP – 1.4.7

WooCommerce Stripe Gateway: by Stripe – 10.3.1
PPOM for WooCommerce: by Themeisle – 33.0.18
WooCommerce: by Automattic – 10.4.3
WP Activity Log: by Melapress – 5.5.4

### Inactive Plugins (8) ###

Australia Post WooCommerce Extension: by WPRuby – 1.10.14
Basilisk AF Entries Exporter: by  – 0.1.0
Basilisk Multisite Transfer: by LexGear Development – 1.1.0
Email Log: by WebFactory Ltd – 2.62
Google for WooCommerce: by WooCommerce – 3.5.2
UpdraftPlus - Backup/Restore: by TeamUpdraft
DavidAnderson – 2.25.9

WooCommerce.com Update Manager: by Automattic – 1.0.3
WooCommerce Analytics: by WooCommerce – 0.9.12

### Dropin Plugins () ###

maintenance.php: maintenance.php

### Settings ###

Legacy API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: 
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
external (external-2)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
featured (featured-2)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-2 (rated-2-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5-2)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –
Enabled Features: analytics
marketplace
order_attribution
site_visibility_badge
remote_logging
email_improvements
blueprint
point_of_sale
custom_order_tables


### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 18 KB

### WC Pages ###

Shop base: #5 - /products/
Cart: #7 - /cart/ -  Contains the [woocommerce_cart] shortcode
Checkout: #9 - /checkout/ -  Contains the [woocommerce_checkout] shortcode
My account: #11 - /my-account/ -  Contains the [woocommerce_my_account] shortcode
Terms and conditions: ❌ Page not set

### Theme ###

Name: Basilisk
Version: 1.1
Author URL: 
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
Theme type: Classic theme
WooCommerce Support: ✔

### Templates ###

Overrides: basilisk/woocommerce/archive-product.php
basilisk/woocommerce/content-product.php
basilisk/woocommerce/content-single-product.php
basilisk/woocommerce/global/breadcrumb.php
basilisk/woocommerce/single-product/add-to-cart/simple.php
basilisk/woocommerce/single-product/add-to-cart/variable.php
basilisk/woocommerce/single-product/add-to-cart/variation-add-to-cart-button.php
basilisk/woocommerce/single-product/meta.php
basilisk/woocommerce/single-product/price.php
basilisk/woocommerce/single-product/product-image.php
basilisk/woocommerce/single-product/related.php
basilisk/woocommerce/single-product/review.php
basilisk/woocommerce/single-product/tabs/additional-information.php
basilisk/woocommerce/single-product/tabs/description.php
basilisk/woocommerce/single-product/title.php
basilisk/single-product.php


### WooCommerce Stripe Payment Gateway ###

Version: 10.3.1
Account ID: 
Test Mode Enabled: Yes
OAuth Connected: No
Sync Enabled: No
Optimized Checkout Enabled: No
Enabled Payment Methods: card,link
Express Checkout: ✔
					Enabled (product,cart,checkout)
Auth and Capture: ✔
					Yes
Logging: No

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
experimental-iapi-mini-cart
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
onboarding
onboarding-tasks
pattern-toolkit-full-composability
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
printful
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page
launch-your-store

Disabled Features: product-data-views
experimental-blocks
experimental-iapi-runtime
coming-soon-newsletter-template
minified-js
product-pre-publish-modal
products-catalog-api
settings
async-product-editor-category-field
product-editor-template-system
use-wp-horizon
rest-api-v4

Daily Cron: ❌ Not scheduled
Options: ✔
Notes: 71
Onboarding: completed

### Action Scheduler ###

Complete: 1,210
Oldest: 2026-01-04 13:07:50 +1000
Newest: 2026-02-04 11:58:20 +1000

Failed: 32
Oldest: 2025-11-27 15:48:26 +1000
Newest: 2026-01-29 11:34:54 +1000

Pending: 12
Oldest: 2026-02-04 12:47:40 +1000
Newest: 2026-02-09 05:33:24 +1000


### Status report information ###

Generated at: 2026-02-04 12:22:09 +10:00
```
</details>

### Isolating the problem

- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by faisuc**
### Submission Review Guidelines:

- I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
- I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
- I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
- Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Fix featured products returning empty on multisite subsites when using `wc_get_products( array( 'featured' => true ) )`. Cache product visibility term IDs per blog so each site uses its own IDs.

Closes #63095.

### How to test the changes in this Pull Request:

1. Set up a WordPress multisite and install WooCommerce on a subsite.
2. Create at least one published product and mark it as featured.
3. On the subsite, run: `$products = wc_get_products( array( 'status' => 'publish', 'featured' => true ) );` (e.g. in a snippet or temporary code). Confirm it returns the featured product(s).

### Milestone

- [x] Automatically assign milestone for the **next WooCommerce version**

### Changelog entry

- [ ] Automatically create a changelog entry from the details below.

<details>

<summary>Changelog Entry Details</summary>

#### Significance

- [x] Patch

#### Type

- [x] Fix - Fixes an existing bug

#### Message

Fix featured products returning empty when using `wc_get_products( array( 'featured' => true ) )` on multisite subsites by caching product visibility term IDs per blog.

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment

N/A – changelog entry added above.

</details>

### CODE REVIEW

**Review by kalessil — CHANGES_REQUESTED** [review]
Thank you for crafting the PR @faisuc!

Looks like some tests are failing, can you please look into those failing?

```log
There were 2 failures:

1) WC_Tests_Product_Functions::test_wc_get_products_booleans
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
 Array (
-    0 => 1168
 )

/var/www/html/wp-content/plugins/woocommerce/tests/legacy/unit-tests/product/functions.php:517

2) WC_Tests_Product_Functions::test_wc_get_featured_product_ids
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
 Array (
-    0 => 1191
 )

/var/www/html/wp-content/plugins/woocommerce/tests/legacy/unit-tests/product/functions.php:1002


```

**Comment by faisuc** [comment]
@kalessil Restored the check that skips the cache when the unit test bootstrap is loaded. Without it, the cache was getting filled early in the run before product_visibility terms existed, so later featured queries were using featured => 0 and returning nothing.

**Comment by kalessil** [comment]
Thanks for looking into the failing tests @faisuc! I've started CI checks and will follow up with a review shortly.

**Comment by kalessil** [comment]
@coderabbitai, please review.

File: plugins/woocommerce/tests/php/includes/wc-term-functions-tests.php [hunk 1]
```diff
@@ -176,4 +176,53 @@ public function test_standard_callback_gets_correct_params(): void {
...
+		);
+
+		$featured_ids = array_map(
+			function ( $product ) {
+				return $product->get_id();
+			},
+			$featured_products
+		);
+
+		$this->assertContains( $featured_product->get_id(), $featured_ids );
```
Comment (kalessil) [inline plugins/woocommerce/tests/php/includes/wc-term-functions-tests.php]: Optional suggestion, to improve the test readability:
```php
		$featured_ids = array_map( fn( $product ) => $product->get_id(), $featured_products );
		$this->assertSame( array( $featured_product->get_id() ), $featured_ids );

```

**Review by kalessil — COMMENTED** [review]
Looks good overall! Changelogger keeps failing for some reason, gues we'll need add the change log entry manually with `pnpm --filter='@woocommerce/plugin-woocommerce' changelog add` and we are good to merge this PR after that.

File: plugins/woocommerce/tests/php/includes/wc-term-functions-tests.php (hunk 1 above)
Comment (faisuc) [reply plugins/woocommerce/tests/php/includes/wc-term-functions-tests.php]: Hi @kalessil, thanks again for the review. I added the changelog and applied your optional test suggestion. Ready for another look when you have time.

**Review by kalessil — APPROVED** [review]
