### PR TITLE
Fixed the order of elements on the Order Confirmation screen

### LINKED ISSUE #50395: The title on the confirmation page is below the subtitle
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

The issue is found during update from 9.1.4 to 9.2.0-beta1 build, so not present on the production.

The title Thank You.. is below the subtitle on the confirmation page, tested using one of the T51 test sites.

### Expected behavior

Thank You title above the subtitle.

### Actual behavior

Thank You title below the subtitle.
https://d.pr/i/i6dUHn

### Steps to reproduce

[this issue was found using T51 test site, it can be specific to the site]
1. Go to the shop
2. Add any product to cart
3. Proceed to the checkout
4. Place an order
5. Observe the issue on the confirmation page

### WordPress Environment

<details><summary>System Status Report</summary>

```
### WordPress Environment ###

WordPress address (URL): [Redacted]
Site address (URL): [Redacted]
WC Version: 9.2.0-beta.1
Legacy REST API Package Version: The Legacy REST API plugin is not installed on this site.
Action Scheduler Version: ✔ 3.8.1
Log Directory Writable: ✔
WP Version: 6.6.1
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 8.1.29
PHP Post Max Size: 2 GB
PHP Time Limit: 1200
PHP Max Input Vars: 6144
cURL Version: 8.7.1
OpenSSL/3.0.11

SUHOSIN Installed: –
MySQL Version: 10.6.18-MariaDB-log
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

[REDACTED]

### Post Type Counts ###

attachment: 527
aw_workflow: 4
custom_css: 1
feedback: 274
jp_img_sitemap: 3
jp_sitemap: 3
jp_sitemap_master: 3
jp_vid_sitemap: 3
mailpoet_page: 1
mka-podcast: 23
mka-programs: 9
mka-speakers: 59
mka-team: 14
mka-video: 7
nav_menu_item: 30
page: 26
post: 28
product: 13
revision: 2419
shop_order: 7
shop_order_refund: 2
wp_block: 8
wp_global_styles: 2
wp_navigation: 25
wp_template: 13
wp_template_part: 5

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (24) ###

Akismet Anti-spam: Spam Protection: by Automattic - Anti-spam Team – 5.3.3
AutomateWoo: by WooCommerce – 6.0.24
Coinbase Commerce: by Coinbase Commerce – 1.4.1
Coinbase Commerce For WooCommerce: by CoderPress – 1.6.2
Easy SVG Support: by Benjamin Zekavica – 3.7
Import Export Suite for WooCommerce: by WebToffee – 1.1.7
Jetpack Protect: by Automattic - Jetpack Security team – 2.2.0
Jetpack: by Automattic – 13.7-a.7
Plugin Autoupdate Filter: by WordPress.com Special Projects / Nick Green – 1.0.1
Public Post Preview: by Dominik Schilling – 2.10.0
Redirection: by John Godley – 5.4.2
Remove hooked_block_types filter: by  –
Team51 Donations: by WordPress.com Special Projects – 1.0.3
Jetpack Force SSO: by WordPress.com Special Projects Team – 1.0.2
Timeline Block: by Cool Plugins – 1.6.2
User Switching: by John Blackbourn – 1.8.0
WooCommerce.com Update Manager: by Automattic – 1.0.3
WooCommerce Beta Tester: by WooCommerce – 2.3.2
WooCommerce Dummy Payments Gateway: by SomewhereWarm – 1.0.9
WooPayments: by WooCommerce – 8.0.1
WooCommerce: by Automattic – 9.2.0-beta.1
Fieldmanager: by Alley – 1.3.0
WP Mail Logging: by WP Mail Logging Team – 1.12.0
Integration for WooCommerce and QuickBooks: by CRM Perks – 1.2.9

### Inactive Plugins (13) ###

Google Analytics for WordPress by MonsterInsights: by MonsterInsights – 9.0.0
Gutenberg: by Gutenberg Team – 18.9.0
Lazy Load for Videos: by Kevin Weber – 2.18.3
Mailchimp for WooCommerce: by Mailchimp – 4.2.1
UserFeedback Lite: by UserFeedback Team – 1.1.1
WooCommerce Customer/Order/Coupon CSV Import Suite: by SkyVerge – 3.11.0 (update to version 3.12.0 is available)
WooCommerce PayPal Payments: by WooCommerce – 2.8.2
WooCommerce Stripe Gateway: by WooCommerce – 8.5.2
WooCommerce Subscriptions: by WooCommerce – 6.5.0
WooCommerce Subscriptions CSV Importer and Exporter: by Prospress Inc – 2.1.0
WPForms Lite: by WPForms – 1.8.9.6
WP Mail SMTP: by WP Mail SMTP – 4.1.0
WP Rocket: by WP Media – 3.15.9

### Dropin Plugins () ###

advanced-cache.php: advanced-cache.php
object-cache.php: Memcached

### Must Use Plugins (2) ###

mu-loader.php: by  –
Safety Net Loader: by  – 1.0.0

### Settings ###

Legacy API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 2 MB

### WC Pages ###

Shop base: #5 - /shop/
Cart: #6 - /cart/ -  Contains the [woocommerce_cart] shortcode
Checkout: #7 - /checkout/ -  Contains the [woocommerce_checkout] shortcode
My account: #8 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Mckenna academy 2023
Version: 1.0.0
Author URL: https://github.com/a8cteam51
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ❌ Not declared

### Templates ###

Overrides: mckenna-academy/woocommerce/checkout/form-checkout.php
mckenna-academy/woocommerce/checkout/review-order.php
mckenna-academy/woocommerce/checkout/thankyou.php version 3.7.0 is out of date. The core version is 8.1.0
mckenna-academy/woocommerce/emails/customer-completed-order.php
mckenna-academy/woocommerce/emails/email-order-details.php
mckenna-academy/woocommerce/myaccount/form-login.php version 7.8.0 is out of date. The core version is 9.2.0
mckenna-academy/woocommerce/myaccount/my-orders.php
mckenna-academy/woocommerce/myaccount/orders.php version 7.8.0 is out of date. The core version is 9.2.0
mckenna-academy/woocommerce/myaccount/view-order.php
/srv/htdocs/wp-content/plugins/woocommerce/templates/block-notices/error.php
/srv/htdocs/wp-content/plugins/woocommerce/templates/block-notices/notice.php
/srv/htdocs/wp-content/plugins/woocommerce/templates/block-notices/success.php
mckenna-academy/woocommerce/order/order-details-item.php
mckenna-academy/woocommerce/order/order-details.php version 7.8.0 is out of date. The core version is 9.0.0

Outdated Templates: ❌
					
					
						Learn how to update

### WooPayments ###

Version: 8.0.1
Connected to WPCOM: ❌ No
Logging: Enabled

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
pattern-toolkit-full-composability
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
printful
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page
launch-your-store

Disabled Features: experimental-blocks
minified-js
product-pre-publish-modal
settings
async-product-editor-category-field
product-editor-template-system
beta-tester-slotfill-examples

Daily Cron: ✔ Next scheduled: 2024-08-06 17:59:16 +00:00
Options: ✔
Notes: 215
Onboarding: completed

### Action Scheduler ###

Complete: 51,730
Oldest: 2024-06-29 15:17:29 +0000
Newest: 2024-08-06 09:46:44 +0000

Failed: 52
Oldest: 2021-11-30 18:33:13 +0000
Newest: 2024-08-06 09:18:24 +0000

Pending: 16
Oldest: 2024-08-06 09:47:11 +0000
Newest: 2024-08-12 21:21:47 +0000


### Status report information ###

Generated at: 2024-08-06 09:46:53 +00:00
```
</details>

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by wavvves**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes #50395 

This PR fixes the order of elements on the Order Confirmation page, namely h1 and sub-heading that was changed accidentally in #48673 

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. As a guest, add something to your cart and checkout using the block-based checkout.
2. Ensure you toggle the "create an account" box.
3. After placing the order, assuming you're using the block based order confirmation, you'll see a notice at the top of the screen indicating the account was created. Leave this page open in a browser window.
4. Go find the account email your new account received and click the link to reset/set a password.
5. Set the password for the account and log in.
6. Refresh the order confirmation page from earlier and confirm the notice is now hidden.
7. Visit the order confirmation page in an incognito window and verify that the title appears before the additional information text.
image

8. Change the URL, namely the order number to an invalid one, and check the title appears before the additional information text.

image

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 
Resolved an issue that caused the page title and content text to display in the incorrect order on the Order Confirmation page.

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

**Review by mikejolley — APPROVED** [review]
I committed here so needs second review, but I confirmed the notice is full width given the new wrapper and it shows separate some the "sub" content which is now below the heading.

File: plugins/woocommerce/src/Blocks/BlockTypes/OrderConfirmation/Status.php [hunk 1]
```diff
@@ -40,14 +40,24 @@ protected function render( $attributes, $content, $block ) {
...
 		}
 
-		$additional_content = $this->render_account_notice( $order ) . $this->render_confirmation_notice( $order );
+		$account_notice = $this->render_account_notice( $order );
+
+		if ( $account_notice ) {
+			$block = sprintf(
+				'<div class="wc-block-order-confirmation-status-notices %1$s">%2$s</div>',
+				esc_attr( trim( $classname ) ),
+				$account_notice
```
Comment (opr) [inline plugins/woocommerce/src/Blocks/BlockTypes/OrderConfirmation/Status.php:49]: Noting that this is escaped during `wc_print_notice` so it's fine to keep it as-is here.

**Review by opr — APPROVED** [review]
I tested following the instructions and it works OK. The code looks good too. Thanks for working on this!
