### PR TITLE
[HPOS] Fix regression in supporting nested date query arguments

### LINKED ISSUE #37732: Regression in supported `date_query` levels when querying orders with HPOS enabled
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When querying orders using `wc_get_orders` it's possible to pass a `date_query` which should support an equivalent WP_Date_Query. However since the [change here](https://github.com/woocommerce/woocommerce/pull/36910/files#diff-42f766d9a99cd9d7e77c0948a7120ddcd7123a40fe6504a46bbf715fc68ef3eaR345-R348) (which was included in WC 7.6) it no longer supports date queries with multiple levels.

For example we can provide a date query where the column fields are on the second level such as:
```php
[
	'relation' => 'AND',
	[
		'column'    => 'date_created_gmt',
		'inclusive' => true,
		'after'     => '2020-01-01',
	],
	[
		'column'    => 'date_created_gmt',
		'inclusive' => true,
		'before'    => '2020-12-31',
	],
],
```

> **Note**
The above only works if the relation is `AND`, if it's set to `OR` it breaks because the unset will remove the relation and then it will default to an `AND` relation.

However when we create more advanced queries where we have multiple date fields it now fails because it can't support the deeper level (this was working for HPOS with WooCommerce 7.4 and 7.5):

```php
[
	[
		'relation' => 'AND',
		[
			'column'    => 'date_created_gmt',
			'inclusive' => true,
			'after'     => '2020-01-01',
		],
		[
			'column'    => 'date_created_gmt',
			'inclusive' => true,
			'before'    => '2020-12-31',
		],
	],
	[
		'column' => 'date_paid_gmt',
		'after'  => '2020-04-01',
	],
]
```

### Expected behavior

I expect the date query to return the same results whether HPOS is enabled or not, and there not to be a regression from previous WooCommerce versions.

### Actual behavior

Since WooCommerce 7.6 it doesn't support multiple levels of date queries combined.

### Steps to reproduce

1. Create orders using Smooth Generator that span several years
2. With HPOS disabled query all orders using the following code snippet:
```php
$ids = wc_get_orders(
	[
		'return'     => 'ids',
		'limit'      => -1,
		'date_query' => [
			[
				'relation' => 'AND',
				[
					'column'    => 'date_created_gmt',
					'inclusive' => true,
					'after'     => '2020-01-01',
				],
				[
					'column'    => 'date_created_gmt',
					'inclusive' => true,
					'before'    => '2020-12-31',
				],
			],
		],
	]
);
var_dump( $ids );
```
3. Confirm it returns only the ID's for orders created in 2020
4. Enable HPOS (and make sure orders are finished syncing)
5. Repeat the query using the same code snippet
6. Notice that this time it returns all orders regardless of creation year

### WordPress Environment

PHP 8.0
WordPress 6.2
WooCommerce 7.6

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by vedanshujain**
### Submission Review Guidelines:

- I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
- I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
- I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/). 
- Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

In #36910 when fixing a unit test when in the context of HPOS, we, unfortunately, ended up breaking support for nested date queries as described in #37732. This PR fixes the regression, by mapping all the params in post format to HPOS format recursively instead of just doing it for the outermost array.

Closes #37732.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

For this unit tests should be good enough, however, for smoke testing

1. Create two orders, with different date_created. You can also modify date_created of individual order by going to WooCommerce > Order > Order edit page. Let's set the date of two different orders in gap of one day. Let's say for order1, created at date is set to 2023-04-13:01-01 and for order2 it's set to 2023-04-02:01-01.
2. On a shell run a nested query that gets order created in first week of April, and also modified after first week of April (basically, we will get order2 but it will exclude order1 since while both are modified after first week of April, only order2 was created in the first week) like so:

```php
$created_before_7_april = [ 'column' => 'post_date', 'before' => '2023-04-07' ];
$created_after_1_april = [ 'column' => 'post_date', 'after' => '2023-04-01' ];
$between_1_and_7_april = [ 'relation' => 'AND', $created_after_1_april, $created_before_7_april ];

$modifed_after_7_april = [ 'column' => 'post_modified', 'after' => '2023-04-07' ];

$date_query = [ $between_1_and_7_april, $modifed_after_7_april ];

$ids = wc_get_orders( array( 'return' => 'ids', 'limit' => -1, 'date_query' => $date_query ) ); // this should include id for order2
```

### CODE REVIEW

File: plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableQuery.php [hunk 1]
```diff
@@ -333,30 +329,13 @@ private function process_date_args(): void {
...
-		$local_date_keys        = array_keys( $local_to_gmt_date_keys );
+
+		$gmt_date_keys   = array_values( $local_to_gmt_date_keys );
+		$local_date_keys = array_keys( $local_to_gmt_date_keys );
 
 		$valid_date_keys = array_merge( $gmt_date_keys, $local_date_keys );
 		$date_keys       = array_filter( $valid_date_keys, array( $this, 'arg_isset' ) );
 
-		// Process already passed date queries args.
-		if ( $this->arg_isset( 'date_query' ) && is_array( $this->args['date_query'] ) ) {
```
Comment (vedanshujain) [inline plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableQuery.php:343]: note that this block is refactored to a separate method `map_gmt_and_post_keys_to_hpos_keys`, only difference is, we now call this block on all passed array elements using array_walk, instead of just the outer one.

**Review by coreymckrill — APPROVED** [review]
Tested against the reproduction steps in #37732 and everything checks out 👍
