### PR TITLE
Fix incorrect net sales in analytics product reports for partial and full refunds

### LINKED ISSUE #32837: Inconsistent behavior of Net Sales in Analytics
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Net Sales on the Analytics -> Products screen does not always equal Net Sales on the Analytics -> Revenue Screen

### Expected behavior

Expect that Net Sales on Products and on Revenue is the same value or follows an obvious and clear calculation rule

### Actual behavior

April 13: Net Sales is not the same on both pages

image
image

April 14: Net sales is the same on both pages

image
image

### Steps to reproduce

View Revenue page, view products page

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): [redacted]
Site address (URL): [redacted]
WC Version: 6.4.1
REST API Version: ✔ 6.4.1
WC Blocks Version: ✔ 7.2.2
Action Scheduler Version: ✔ 3.4.0
WC Admin Version: ✔ 3.3.2
Log Directory Writable: ✔
WP Version: 5.9.3
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: Apache
PHP Version: 7.4.28
PHP Post Max Size: 100 MB
PHP Time Limit: 3600
PHP Max Input Vars: 10000
cURL Version: 7.58.0
OpenSSL/1.1.1

SUHOSIN Installed: –
MySQL Version: 5.7.36-39-log
Max Upload Size: 50 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 6.4.1
WC Database Prefix: wp66_
Total Database Size: 1439.32MB
Database Data Size: 798.99MB
Database Index Size: 640.33MB
wp66_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp66_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp66_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp66_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp66_woocommerce_order_items: Data: 7.52MB + Index: 3.52MB + Engine InnoDB
wp66_woocommerce_order_itemmeta: Data: 54.59MB + Index: 48.14MB + Engine InnoDB
wp66_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp66_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp66_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp66_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp66_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp66_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp66_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp66_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp66_actionscheduler_actions: Data: 110.66MB + Index: 42.16MB + Engine InnoDB
wp66_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp66_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp66_actionscheduler_logs: Data: 33.56MB + Index: 27.06MB + Engine InnoDB
wp66_cf_forms: Data: 0.08MB + Index: 0.02MB + Engine InnoDB
wp66_cf_form_entries: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp66_cf_form_entry_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp66_cf_form_entry_values: Data: 0.16MB + Index: 0.14MB + Engine InnoDB
wp66_cf_pro_messages: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp66_cf_queue_failures: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp66_cf_queue_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp66_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp66_comments: Data: 61.59MB + Index: 46.09MB + Engine InnoDB
wp66_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp66_options: Data: 4.48MB + Index: 0.38MB + Engine InnoDB
wp66_postmeta: Data: 312.89MB + Index: 285.75MB + Engine InnoDB
wp66_posts: Data: 32.56MB + Index: 18.09MB + Engine InnoDB
wp66_revslider_css: Data: 0.14MB + Index: 0.02MB + Engine InnoDB
wp66_revslider_css_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp66_revslider_layer_animations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp66_revslider_layer_animations_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp66_revslider_navigations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp66_revslider_navigations_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp66_revslider_sliders: Data: 0.08MB + Index: 0.02MB + Engine InnoDB
wp66_revslider_sliders_bkp: Data: 0.09MB + Index: 0.00MB + Engine InnoDB
wp66_revslider_slides: Data: 0.50MB + Index: 0.02MB + Engine InnoDB
wp66_revslider_slides_bkp: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
wp66_revslider_static_slides: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp66_revslider_static_slides_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp66_shipment_batch_process: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp66_termmeta: Data: 0.09MB + Index: 0.14MB + Engine InnoDB
wp66_terms: Data: 1.52MB + Index: 3.03MB + Engine InnoDB
wp66_term_relationships: Data: 15.55MB + Index: 14.55MB + Engine InnoDB
wp66_term_taxonomy: Data: 1.52MB + Index: 2.02MB + Engine InnoDB
wp66_usermeta: Data: 8.52MB + Index: 6.03MB + Engine InnoDB
wp66_users: Data: 0.17MB + Index: 0.17MB + Engine InnoDB
wp66_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp66_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp66_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp66_wc_customer_lookup: Data: 0.19MB + Index: 0.13MB + Engine InnoDB
wp66_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp66_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp66_wc_order_product_lookup: Data: 8.52MB + Index: 9.06MB + Engine InnoDB
wp66_wc_order_stats: Data: 7.52MB + Index: 6.55MB + Engine InnoDB
wp66_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp66_wc_product_attributes_lookup: Data: 3.52MB + Index: 5.03MB + Engine InnoDB
wp66_wc_product_meta_lookup: Data: 2.52MB + Index: 3.42MB + Engine InnoDB
wp66_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp66_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp66_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp66_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp66_woo_shipment_status_email: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp66_woo_shippment_provider: Data: 0.09MB + Index: 0.00MB + Engine InnoDB
wp66_wsal_metadata: Data: 56.59MB + Index: 102.53MB + Engine InnoDB
wp66_wsal_occurrences: Data: 69.61MB + Index: 15.06MB + Engine InnoDB
wp66_wsal_sessions: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
wp66_yith_wcwl: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp66_yith_wcwl_lists: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_postmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_posts: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB

### Post Type Counts ###

attachment: 21911
clever_menu: 3
clever_menu_theme: 1
custom_css: 1
elementor_library: 1
frontslider: 1
motor_header: 7
motor_project: 46
nav_menu_item: 9
page: 13
post: 15
product: 16999
revision: 40
shop_order: 62938
shop_order_refund: 826
wp_block: 1
wp_global_styles: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 6.4.1

### Inactive Plugins (17) ###

Advanced Shipment Tracking for WooCommerce: by zorem – 3.3.2
Caldera Forms: by Caldera Forms – 1.9.7
Checkout Field Editor for WooCommerce (Pro): by ThemeHigh – 3.1.8
Clear Cart & Sessions for WooCommerce: by Puri.io – 1.5.2
Elementor: by Elementor.com – 3.6.5
FiboSearch - AJAX Search for WooCommerce: by FiboSearch Team – 1.17.0
Kirki Customizer Framework: by David Vongries – 4.0.23
LoginPress - Customizing the WordPress Login Screen.: by WPBrigade – 1.6.0
Motor Custom Types: by Stockware – 3.0.0
Restricted Site Access: by Jake Goldman
10up
Oomph – 7.3.0

Slider Revolution: by ThemePunch – 6.5.19
Software libraries for WP Activity Log: by WP White Security – 1.0.4
WooCommerce Min/Max Quantities: by WooCommerce – 2.4.23
WooCommerce Vehicle Parts Finder - Make/Model/Year/Engine/Category/Keyword: by The WP Instinct Team – 3.0
WP Activity Log (Premium): by WP White Security – 4.4.0
WP Activity Log for WooCommerce: by WP White Security – 1.4.2
WP Crontrol: by John Blackbourn & crontributors – 1.12.1

### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
object-cache.php: Memcached Redux

### Must Use Plugins (6) ###

Force Strong Passwords - WPE Edition: by Jason Cosper – 1.8.0
WPE ElasticPress Autosuggest Logger: by WP Engine – 1.0.0
WP Engine Cache Plugin: by WP Engine – 1.0.9
WP Engine Seamless Login Plugin: by WP Engine – 1.5.5
WP Engine Security Auditor: by wpengine – 1.0.10
WP Engine System: by WP Engine – 5.0.1

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #6 - /shop/
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Motor
Version: 3.0.0
Author URL: http://themeforest.net/user/stockware
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: motor/woocommerce/archive-product.php
motor/woocommerce/cart/cart-empty.php
motor/woocommerce/cart/cart-totals.php
motor/woocommerce/cart/cart.php
motor/woocommerce/cart/cross-sells.php
motor/woocommerce/content-product.php
motor/woocommerce/content-single-product.php
motor/woocommerce/global/quantity-input.php
motor/woocommerce/loop/add-to-cart.php
motor/woocommerce/loop/loop-end.php
motor/woocommerce/loop/loop-start.php
motor/woocommerce/loop/orderby.php
motor/woocommerce/loop/pagination.php
motor/woocommerce/myaccount/downloads.php
motor/woocommerce/myaccount/form-edit-account.php
motor/woocommerce/myaccount/form-edit-address.php
motor/woocommerce/myaccount/form-lost-password.php
motor/woocommerce/myaccount/form-reset-password.php
motor/woocommerce/myaccount/my-account.php
motor/woocommerce/myaccount/my-address.php
motor/woocommerce/myaccount/my-downloads.php
motor/woocommerce/myaccount/my-orders.php
motor/woocommerce/myaccount/navigation.php
motor/woocommerce/myaccount/orders.php
motor/woocommerce/myaccount/payment-methods.php
motor/woocommerce/myaccount/view-order.php
motor/woocommerce/single-product/add-to-cart/simple.php
motor/woocommerce/single-product/add-to-cart/variable.php version 3.5.5 is out of date. The core version is 6.1.0
motor/woocommerce/single-product/add-to-cart/variation-add-to-cart-button.php
motor/woocommerce/single-product/meta.php
motor/woocommerce/single-product/price.php
motor/woocommerce/single-product/product-attributes.php
motor/woocommerce/single-product/product-image.php
motor/woocommerce/single-product/related.php
motor/woocommerce/single-product/review.php
motor/woocommerce/single-product/short-description.php
motor/woocommerce/single-product/tabs/additional-information.php
motor/woocommerce/single-product/tabs/description.php
motor/woocommerce/single-product/tabs/tabs.php
motor/woocommerce/single-product/title.php
motor/woocommerce/single-product/up-sells.php
motor/woocommerce/single-product.php
motor/woocommerce/content-product_cat.php

Outdated Templates: ❌
					
					
						Learn how to update

### Action Scheduler ###

Complete: 150,799
Oldest: 2022-03-31 09:13:10 -0400
Newest: 2022-05-01 22:09:34 -0400

Failed: 47
Oldest: –
Newest: –

### Status report information ###

Generated at: 2022-05-01 22:10:14 -04:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by ianlin**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Part of the epic issue #50480, this PR fixes current WC analytics inconsistent net sales for **partial** and **full** refunds.
Those fixes were tested and reviewed in #48768 and #51262, ~so technically this umbrella PR doesn't require a lot of detailed testing~.

**Update 5th March 2025**

After a long back and forth reviews and fixes, this PR actually solves the problems not specifically to the inconsistent net sales between product and order reports, but the product reports itself by making the table `wp_wc_order_product_lookup` display every amount correctly when the partial and full refunds happen. Before those fixes, there were no record in the table `wp_wc_order_product_lookup` when refunds.

✏️ Note that there were still cases where net sales are inconsistent between product and order reports, such as the issue #56096. In this PR we are focusing on fixing the product reports (`wp_wc_order_product_lookup` table).

Closes #32837 #48761 #48775.

#### Next steps

There is still an issue #48954 that is part of the epic issue #50480 need to be fixed.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Follow the steps in #48768 and #51262, the inconsistent net sales should not occur for partial and full refunds.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce/src/Admin/API/Reports/Products/DataStore.php [hunk 1]
```diff
@@ -432,17 +432,51 @@ public static function sync_order_products( $order_id ) {
 		$decimals       = wc_get_price_decimals();
 		$round_tax      = 'no' === get_option( 'woocommerce_tax_round_at_subtotal' );
 
+		$is_full_refund = false;
+		// Order fully refunded won't have the order line items.
+		if ( 'shop_order_refund' === $order->get_type() && empty( $order_items ) ) {
```
Comment (mikkamp) [inline plugins/woocommerce/src/Admin/API/Reports/Products/DataStore.php]: I don't think this check is very accurate, since get_items by default only queries `line_item`, which doesn't include shipping/tax/etc... For example I can have the following scenario:

1. Order with 2 products purchased and a shipping fee
2. Refund one of the products (at this stage the partial refund will have a single line item) 
3. Second refund of just the shipping fee (here the default get_items will also be empty)

This means that it will now remove the entry that was refunded in 2 and create a product refund entry for both products when only one was refunded (similar will have if we skip step 2 and only refund shipping).

This is [the check in WC for determining if a refund order is partial or not](https://github.com/woocommerce/woocommerce/blob/9.4.3/plugins/woocommerce/includes/wc-order-functions.php#L673), do we want to replicate that check or hook into the actions and save order meta so we can determine if it's partial or not?

File: plugins/woocommerce/src/Admin/API/Reports/Products/DataStore.php [hunk 2]
```diff
@@ -432,17 +432,51 @@ public static function sync_order_products( $order_id ) {
...
+			// Remove the partial refunded order item if exists.
+			$delete_query = "
+				DELETE product_lookup
+				FROM {$table_name} AS product_lookup
+				INNER JOIN {$wpdb->prefix}wc_order_stats AS order_stats
+					ON order_stats.order_id = product_lookup.order_id
+				WHERE 1 = 1
+					AND order_stats.parent_id = %d
+					AND order_stats.total_sales < 0
+			";
```
Comment (mikkamp) [inline plugins/woocommerce/src/Admin/API/Reports/Products/DataStore.php]: This query seems like it's missing some scenarios or mislabeled as it removes more than just the partial refunded rows. When I tested refunding just shipping this removed all entries in the `wp_wc_order_product_lookup` table for a particular order.

As it's linking any entries in the product lookup table to the refunded order, so it's not only catching partial refund lines but any product sales that have been made for the parent order. If it was actually a full refund that might be fine, because the code below re-adds the rows as each product being refunded. But since the code below also uses a `$wpdb->replace` it's not clear to me why we need to remove rows and then add them back again.

File: plugins/woocommerce/includes/wc-update-functions.php [hunk 3]
```diff
@@ -2937,3 +2937,44 @@ function wc_update_950_tracking_option_autoload() {
...
+		}
+	}
+}
+
+/**
+ * Update primary key to composite (order_item_id, order_id) in the wc_order_product_lookup table.
+ */
+function wc_update_960_update_primary_key_to_composite_in_order_product_lookup_table() {
+	global $wpdb;
+	$wpdb->query( "ALTER TABLE {$wpdb->prefix}wc_order_product_lookup DROP PRIMARY KEY, ADD PRIMARY KEY (order_item_id, order_id)" );
```
Comment (mikkamp) [inline plugins/woocommerce/includes/wc-update-functions.php:2996]: Can you clarify why this is needed? From my understanding the original reasoning was:

> because we will have multiple `order_item_id = 0`. Every time an order is refunded, we will insert a new line with `order_item_id = 0` and the `order_id`

However looking at the code below I see that for a full refund we fetch line items using `$parent_order->get_items()`. So each entry in the product lookup table still has a unique line item ID and an order ID.

File: plugins/woocommerce/includes/wc-update-functions.php [hunk 4]
```diff
@@ -2937,3 +2937,44 @@ function wc_update_950_tracking_option_autoload() {
...
+
+	// Get every order ID where the total sales is less than 0 and is not present in the table wc_order_product_lookup.
+	$select_query = "
+	SELECT order_stats.order_id FROM {$wpdb->prefix}wc_order_stats AS order_stats
+	WHERE order_stats.total_sales < 0
+    AND (
+        SELECT COUNT(*)
+        FROM {$wpdb->prefix}wc_order_product_lookup AS product_lookup
+        WHERE product_lookup.order_id = order_stats.parent_id
+          AND product_lookup.product_net_revenue = order_stats.total_sales
```
Comment (mikkamp) [inline plugins/woocommerce/includes/wc-update-functions.php]: This is not super harmful as the consequence will be re-importing additional orders.

However the order `total_sales` will not be equal  to the `product_net_revenue` in quite a variety of cases. For example:
- If we have ordered multiple products in a single order
- If an order has additional fees such as shipping
- `total_sales` will include taxes and `product_net_revenue` will exclude it 

So most likely this is just going to catch all orders that have some kind of refund attached, since the rows where the two matched will not have been recorded previously.

That behaviour might be desired, but it might be better to restructure the query so we can determine what it should be including.

File: plugins/woocommerce/includes/wc-update-functions.php [hunk 5]
```diff
@@ -2937,3 +2937,44 @@ function wc_update_950_tracking_option_autoload() {
...
+    ) = 0";
+
+	// phpcs:ignore WordPress.DB.PreparedSQL.NotPrepared -- No user input in the query, everything is hardcoded.
```
Comment (mikkamp) [inline plugins/woocommerce/includes/wc-update-functions.php]: We can avoid this ignore if we include the hardcoded query without using a temp variable. PHPCS will see that it's hardcoded.

```php
	$orders = $wpdb->get_results(
		"SELECT order_stats.order_id FROM {$wpdb->prefix}wc_order_stats AS order_stats
		WHERE order_stats.total_sales < 0
		AND (
			SELECT COUNT(*)
			FROM {$wpdb->prefix}wc_order_product_lookup AS product_lookup
			WHERE product_lookup.order_id = order_stats.parent_id
				AND product_lookup.product_net_revenue = order_stats.total_sales
		) = 0"
	);
```

**Review by mikkamp — COMMENTED** [review]
When testing I originally came across the issue that Product reports are always based on the date_created, whereas for Order reports this can be date_completed (as specified in the settings). In my case the completed date was a day later so I had to select both days to compare reports.

Considering that the linked investigation mentions:
> These issues are complex, difficult to tackle, and challenging to test all the side effects.

Why don't we see more testing where at least the basic scenarios are covered. For example `WC_Admin_Tests_Reports_Products::test_populate_and_refund` only covers a partial refund in the test, where we are explicitly changing the behaviour for a full refund. A scenario where only a shipping fee is refunded could also be helpful.

Based on the comments I added, I don't feel this is fully ready for pushing to release. I'd feel a lot more confident if some of the scenarios I described are covered in unit tests so we are at least working with predictable outcomes.

**Comment by ianlin** [comment]
@mikkamp Thanks for the review and for catching those issues!

I set up a new local site and generated 10 orders using Smooth Generator. Along with the day_created / day_paid issue you mentioned, I also noticed an inconsistency between Net Sales in the Products report and Net Sales in the Orders report. It turns out this inconsistency is caused by fees - fees aren't included in the Products report since the `wp_wc_order_product_lookup` table doesn't map fees to products. This behaviour also exists in the trunk branch. It feels logical for Net Sales to exclude fees, so the issue seems to be with the Orders report instead.

That said, I agree these inconsistencies need a closer review and more tests to address them properly. I'll mark this PR as a draft and let the HEs know it won't make it into the 9.6 release.

**Comment by mikkamp** [comment]
> I also noticed an inconsistency between Net Sales in the Products report and Net Sales in the Orders report. It turns out this inconsistency is caused by fees - fees aren't included in the Products report since the wp_wc_order_product_lookup table doesn't map fees to products. This behaviour also exists in the trunk branch. It feels logical for Net Sales to exclude fees, so the issue seems to be with the Orders report instead.

Fees would be another difference to take into consideration. However my expectation would be that fees are not included in the products report, but are in the orders report. If that needs to be highlighted then maybe a tooltip or documentation would be the right place to do so. I wouldn't consider that an issue for the orders report.

In my opinion this PR should solely focus on the refunds, and ensure any product refunds are reflected in the `wp_wc_order_product_lookup`. So they don't continue to count as sales in some cases.

File: plugins/woocommerce/src/Admin/API/Reports/Products/DataStore.php (hunk 1 above)
Comment (ianlin) [reply plugins/woocommerce/src/Admin/API/Reports/Products/DataStore.php]: Thanks for pointing this and providing the info of determining partial refund in WC core. I missed the fee factor in the original implementation. I will see which way is better - copy the check or save the wp_wc_orders_meta by hooking into the action.

**Comment by ianlin** [comment]
@mikkamp Thanks again for catching those issues and providing potential solutions.

I've updated the code to reflect all the suggestions you gave. Here's the notable changes:

1. Hook refunded actions to add refund type in `wp_wc_orders_meta` table. This resolve the issue that refunded shipping fee also does not have line items - now the refunded shipping fee is marked as partial refund thanks to the hooks.
2. For the case of full refund, there was a case that the order was refunded partially first then refunded fully after. Since the full refund does not have order line items,  my original implementation was to remove the partial refunds that exists in product look table, and use the parent order's order line items to update to the product lookup table. The new implementation is, select those already existing partial refunds in lookup table first, and exclude them from the parent orders line items.
3. Each of the refunded line items in a full refund is written to the product lookup table, with the `order_item_id` set to `0` and the `order_id` set to the refunded order ID. As a result I made the primary key to a composite key as `(order_item_id, order_id, product_id)`, since there will be multiple items with the same `order_item_id` as `0` and the same `order_id` for the refunded order.
4. Update the test for order stats, since I found there's one test that did not add line items for the partial refund, which makes the test result inaccurate.
5. Add tests for full refunds in product reports
6. Update the migration SQL by specifically exclude refunded shipping fees and refunded tax fees

I agree those issues are really complex, and I've tried my best to explain the changes above, but please let me know if anything is unclear.

File: plugins/woocommerce/src/Admin/API/Reports/Products/DataStore.php (hunk 1 above)
Comment (ianlin) [reply plugins/woocommerce/src/Admin/API/Reports/Products/DataStore.php]: I made it to save the refund type in `wc_orders_meta` table in 8cf996b.

File: plugins/woocommerce/src/Admin/API/Reports/Products/DataStore.php (hunk 2 above)
Comment (ianlin) [reply plugins/woocommerce/src/Admin/API/Reports/Products/DataStore.php]: Thanks. Instead of removing them first, I changed it to select the already existing partial refunds in lookup table, then exclude them from the parent orders line items. 1d54d24

File: plugins/woocommerce/includes/wc-update-functions.php (hunk 3 above)
Comment (ianlin) [reply plugins/woocommerce/includes/wc-update-functions.php:2996]: Thanks for catching this. The previous implementation did not really need the composite primary key, that was a mistake when changing implementations during development. However, the new implementation right now is to also make the primary key as composite one: `(order_item_id, order_id, product_id)`. Please see the point 3 in the https://github.com/woocommerce/woocommerce/pull/53019#issuecomment-2536151879.

File: plugins/woocommerce/includes/wc-update-functions.php (hunk 4 above)
Comment (ianlin) [reply plugins/woocommerce/includes/wc-update-functions.php]: Thanks, I made a change to exclude specifically refunded shipping fees and refunded tax fees.

File: plugins/woocommerce/includes/wc-update-functions.php [hunk 6]
```diff
@@ -2932,3 +2932,49 @@ function wc_update_950_tracking_option_autoload() {
...
+		"SELECT order_stats.order_id
+		FROM {$wpdb->prefix}wc_order_stats AS order_stats
+		WHERE order_stats.total_sales < 0 # Refunded orders
+			AND order_stats.total_sales != order_stats.shipping_total # Exclude refunded shipping
+			AND order_stats.total_sales != order_stats.tax_total # Exclude refunded tax
+			AND (
+				SELECT COUNT(*)
+				FROM wp_wc_order_product_lookup AS product_lookup
+				WHERE product_lookup.order_id = order_stats.order_id
+					AND product_lookup.product_net_revenue = order_stats.total_sales
```
Comment (mikkamp) [inline plugins/woocommerce/includes/wc-update-functions.php]: This is still not going to match if the refund order refunded two products at once. But considering that this is a run once scenario, and ideally it shouldn't have any refund lines in the product_lookup table before this change. It's not going to make a difference. And if it is run a second time then it will just catch extra orders to recalculate.

File: plugins/woocommerce/src/Admin/API/Reports/Products/DataStore.php [hunk 7]
```diff
@@ -432,17 +466,79 @@ public static function sync_order_products( $order_id ) {
...
+				),
+				ARRAY_A
+			);
+
+			$refunded_product_ids = array_map(
+				function ( $refunded_product_id ) {
+					return $refunded_product_id['product_id'];
+				},
+				$refunded_product_ids
+			);
```
Comment (mikkamp) [inline plugins/woocommerce/src/Admin/API/Reports/Products/DataStore.php]: If we aren't worried about type casting, we can use `array_column` for this. Or alternatively if we use `wp_list_pluck` then we can work with a list of objects and we don't need to change the type to `ARRAY_A` for the DB call.

```suggestion
			$refunded_product_ids = array_column( $refunded_product_ids, 'product_id' );
```

File: plugins/woocommerce/src/Admin/API/Reports/Products/DataStore.php [hunk 8]
```diff
@@ -432,17 +466,79 @@ public static function sync_order_products( $order_id ) {
...
+
+			// Exclude the refunded product ids from the parent order items.
+			$order_items = array_values(
+				array_filter(
+					$parent_order_items,
+					function ( $order_item ) use ( $refunded_product_ids ) {
+						$order_item_id = $order_item->get_id();
+						$product_id    = wc_get_order_item_meta( $order_item_id, '_product_id' );
```
Comment (mikkamp) [inline plugins/woocommerce/src/Admin/API/Reports/Products/DataStore.php]: We should only be interested in [WC_Order_Item_Product](https://woocommerce.github.io/code-reference/classes/WC-Order-Item-Product.html) here, if so it has a `get_product_id` function. Although that points out a flaw in this logic.

I can purchase two separate variations from the same product. That's going to give me two line items with an identical `product_id`. Does that mean we should be expanding the primary key to include `variation_id`?

I'm still not totally understanding why we need such a liberal key and why `order_item_id` needs to forced to 0. See comment below where we set it to 0.

File: plugins/woocommerce/src/Admin/API/Reports/Products/DataStore.php [hunk 9]
```diff
@@ -432,17 +466,79 @@ public static function sync_order_products( $order_id ) {
...
+
+			$refunded_product_ids = array_map(
+				function ( $refunded_product_id ) {
+					return $refunded_product_id['product_id'];
+				},
+				$refunded_product_ids
+			);
+
+			// Exclude the refunded product ids from the parent order items.
+			$order_items = array_values(
```
Comment (mikkamp) [inline plugins/woocommerce/src/Admin/API/Reports/Products/DataStore.php]: If we are not concerned about the array index then this seems a little unnecessary, and we can just work with the array returned from `array_filter`.

File: plugins/woocommerce/src/Admin/API/Reports/Products/DataStore.php [hunk 10]
```diff
@@ -432,17 +466,79 @@ public static function sync_order_products( $order_id ) {
...
+			// Get the partially refunded product ids.
+			$query = "
+				SELECT product_lookup.product_id
+				FROM {$table_name} AS product_lookup
+				INNER JOIN {$wpdb->prefix}wc_order_stats AS order_stats
+					ON order_stats.order_id = product_lookup.order_id
+				WHERE 1 = 1
+					AND order_stats.parent_id = %d
+					AND order_stats.total_sales < 0
+			";
```
Comment (mikkamp) [inline plugins/woocommerce/src/Admin/API/Reports/Products/DataStore.php]: I'm not so sure this kind of filtering is going to work in all cases. Because this means for a full refund we are going to skip any line item with a matching product (variations should be taken into consideration here).

However if I have a partial refund order where I decided to do a 40% refund on a particular product and then later decided to fully refund the order, we are detecting this product as "partially refunded", so we'll skip it. Which means in the reports it will still be counting 60% of the product towards sales.

Also because a line item (and a row in the `product_lookup` table) has a `product_qty`. If I have an order where multiples of a product are purchased and only one is refunded, and later the whole order, then we again end up with the same problem.

I think in this case it would be best to calculate the difference with all found partial refunds and then add that as a new product_lookup row to indicate the remaining refund. A simpler method would be to remove old entries, but I have the feeling that would be incorrect. Because each entry in product_lookup has a date timestamp, so that would attribute the refund to the wrong time. So what we really want to see is the full history, ex:

- 2024-12-05 Product ordered $20 revenue
- 2024-12-06 Partial refund -$5 (total revenue for that product is still $15)
- 2024-12-07 Full refund -$15 (no more revenue)

If I view the report for all of December then I'll see no revenue. But if I view breakdown reports, then I can still see the accurate amount of positive or negative revenue that occurred on those days.

File: plugins/woocommerce/src/Admin/API/Reports/Products/DataStore.php [hunk 11]
```diff
@@ -455,15 +551,15 @@ public static function sync_order_products( $order_id ) {
...
 				$tax_amount = round( $tax_amount, $decimals );
 			}
 
 			$result = $wpdb->replace(
 				self::get_db_table_name(),
 				array(
-					'order_item_id'         => $order_item_id,
+					// When the order is full refund, there is no order items, so the order_item_id should be 0.
+					'order_item_id'         => $is_full_refund ? 0 : $order_item_id,
 					'order_id'              => $order->get_id(),
```
Comment (mikkamp) [inline plugins/woocommerce/src/Admin/API/Reports/Products/DataStore.php]: For the order ID we are using the refund order, but the line item ID's are unique entries from the parent order for full refunds and from the refund order for a partial refund.

Since that will still make the order item ID unique in combination with the order number, why can't we just always populate it? Which means we don't need to expand the primary key across product_id (and variation_id).
Does this bring us into trouble when we populate the reports where it might try to fetch/populate the line item details directly linked to the refund order?

I tried adding an entry like this where I use the refund order ID but the order_item_id of the parent product. In the report it seems to populate the data from the product directly, so I don't see anything incorrect:
image

image

File: plugins/woocommerce/src/Admin/API/Reports/Products/DataStore.php [hunk 12]
```diff
@@ -111,6 +111,40 @@ protected function assign_report_columns() {
 	 */
 	public static function init() {
 		add_action( 'woocommerce_analytics_delete_order_stats', array( __CLASS__, 'sync_on_order_delete' ), 10 );
+		add_action( 'woocommerce_order_partially_refunded', array( __CLASS__, 'add_partial_refund_type_meta' ), 10, 2 );
+		add_action( 'woocommerce_order_fully_refunded', array( __CLASS__, 'add_full_refund_type_meta' ), 10, 2 );
```
Comment (mikkamp) [inline plugins/woocommerce/src/Admin/API/Reports/Products/DataStore.php:116]: Should we be concerned that this won't work for refunds created before the fix? Even if we go to re-import orders in Analytics > Settings, it won't find the meta value and default them to partial_refunds.

File: plugins/woocommerce/src/Admin/API/Reports/Products/DataStore.php [hunk 13]
```diff
@@ -432,17 +466,79 @@ public static function sync_order_products( $order_id ) {
 		$decimals       = wc_get_price_decimals();
 		$round_tax      = 'no' === get_option( 'woocommerce_tax_round_at_subtotal' );
 
+		$parent_order_id = $order->get_parent_id();
+
+		$is_full_refund = false;
+		$refund_type    = $order->get_meta( '_refund_type' );
+		// When the order is a full refund, there is no order items.
+		// We need to get the parent order items, and exclude the items that is already being patially refunded.
```
Comment (mikkamp) [inline plugins/woocommerce/src/Admin/API/Reports/Products/DataStore.php]: Can you clarify how it was determined that there are no line items for a full refund? Am I doing something wrong when issuing a full refund? I got one of my test orders and made sure to include everything for a refund (this order had no prior partial refunds):

image

Now if I look up order meta for the refund order I can see it detected it as a full refund:
image

When I check the line items for the refund order, it has one for each product item:
image

Also not finding any other method to refund which might generate the refund order without line items when looking through the [instructions here](https://woocommerce.com/document/woocommerce-refunds/).

Update: I did some searching, you can also toggle the status of an existing order to refunded. Which will create a refund order with the total amount and no line items. I believe that scenario is not very common though, because it means you can't do an automatic refund using the payment gateway. So this will probably be common only for stores that handle payment outside of WooCommerce.

I guess that means we should still include the empty line items check and not fully rely on the $refund_type, as in some cases there will be line items.

File: plugins/woocommerce/src/Admin/API/Reports/Products/DataStore.php [hunk 14]
```diff
@@ -432,17 +466,79 @@ public static function sync_order_products( $order_id ) {
...
 			$shipping_amount     = $order->get_item_shipping_amount( $order_item );
 			$shipping_tax_amount = $order->get_item_shipping_tax_amount( $order_item );
 			$coupon_amount       = $order->get_item_coupon_amount( $order_item );
+			$net_revenue         = round( $order_item->get_total( 'edit' ), $decimals );
+
+			// If the order is a full refund, there is no order items. We use the parent order items instead.
+			// So the net revenue and product quantity should be negative.
+			if ( $is_full_refund ) {
+				$net_revenue = -abs( $net_revenue );
+				$product_qty = -abs( $product_qty );
```
Comment (mikkamp) [inline plugins/woocommerce/src/Admin/API/Reports/Products/DataStore.php:551]: Should this be limited to only quantity and revenue? What about taxes, shouldn't that also be reversed? And this seems to indicate we can also have per product shipping, or coupon amounts per product? Shouldn't that be marked as fully refunded as well? Otherwise the gross revenue calculation is going to be incorrect since it's done with:

`'product_gross_revenue' => $net_revenue + $tax_amount + $shipping_amount + $shipping_tax_amount`

**Review by mikkamp — COMMENTED** [review]
Thanks for adding the additional testing that's helpful to cover more scenarios.

I tried to be very verbose with the comments as I tried to wrap my head around how all the sections work. So sorry if there are a lot of comments in there.

However considering that variations aren't taken into consideration and that in some circumstances full refunds can contain line items, I don't feel comfortable to approve this yet.

**Comment by ianlin** [comment]
@mikkamp Thanks for the detailed testing and providing more scenarios that I did not think of. I updated the code to address most of your concerns. I implemented it based on the expected results you mentioned:

> So what we really want to see is the full history, ex:
>
> 2024-12-05 Product ordered $20 revenue
> 2024-12-06 Partial refund -$5 (total revenue for that product is still $15)
> 2024-12-07 Full refund -$15 (no more revenue)

I also handle when the two variations with the same parent product were refunded case.

Just one thing I wasn't sure how to handle:

> Should this be limited to only quantity and revenue? What about taxes, shouldn't that also be reversed? And this seems to indicate we can also have per product shipping, or coupon amounts per product? Shouldn't that be marked as fully refunded as well? Otherwise the gross revenue calculation is going to be incorrect since it's done with:
>
> 'product_gross_revenue' => $net_revenue + $tax_amount + $shipping_amount + $shipping_tax_amount

This is the case when the order refund type is `full`, and the refunded order does not have line items (i.e. order status changed to `Refunded`). In this case the `$order_items` is the parent order's line items, and the `$order` here is still the refunded order, then the shipping amount (`$order->get_item_shipping_amount( $order_item )`) returns nothing. I think since this PR specifically solves the inconsistency in net revenue, and I don't see product gross revenue is displayed in the Products report, we could probably solve the shipping amount (and tax, coupon, etc) in the follow up PR, as I haven't thought of a good way to handle it?

File: plugins/woocommerce/src/Admin/API/Reports/Products/DataStore.php (hunk 13 above)
Comment (ianlin) [reply plugins/woocommerce/src/Admin/API/Reports/Products/DataStore.php]: Thanks, and yeah, I was only handling full refunds created by changing the order status to "Refunded", and I didn't realise that refunding all the products one by one in an order would also count as a "full" refund. I've added back the check for empty order line items.

File: plugins/woocommerce/src/Admin/API/Reports/Products/DataStore.php (hunk 12 above)
Comment (ianlin) [reply plugins/woocommerce/src/Admin/API/Reports/Products/DataStore.php:116]: Thanks for the reminder, I've added in 5e1bde3. Since we only care about the full refunds without line items, I added the `_refund_type` meta to orders without line items found in the query from the migration script.

File: plugins/woocommerce/src/Admin/API/Reports/Products/DataStore.php (hunk 11 above)
Comment (ianlin) [reply plugins/woocommerce/src/Admin/API/Reports/Products/DataStore.php]: > Since that will still make the order item ID unique in combination with the order number, why can't we just always populate it?

You're absolutely right. Not sure how did I get that far expanding the primary key to `product_id`. 😓 Updated in 7c85581.

File: plugins/woocommerce/src/Admin/API/Reports/Products/DataStore.php (hunk 10 above)
Comment (ianlin) [reply plugins/woocommerce/src/Admin/API/Reports/Products/DataStore.php]: Thanks for the reminder. Updated in da6ad3e and a88e12d.

File: plugins/woocommerce/src/Admin/API/Reports/Products/DataStore.php (hunk 8 above)
Comment (ianlin) [reply plugins/woocommerce/src/Admin/API/Reports/Products/DataStore.php]: Thanks for pointing the variation product issue, updated in [5566b51](https://github.com/woocommerce/woocommerce/pull/53019/commits/5566b51e2ff9d16cbc9eba40f9a7ccb6497c53f1).

File: plugins/woocommerce/includes/wc-update-functions.php (hunk 6 above)
Comment (ianlin) [reply plugins/woocommerce/includes/wc-update-functions.php]: > ideally it shouldn't have any refund lines in the product_lookup table before this change

Agreed, I've removed this check, since it's not possible that refund items exist before this fix.

File: plugins/woocommerce/src/Admin/API/Reports/Products/DataStore.php [hunk 15]
```diff
@@ -432,17 +466,144 @@ public static function sync_order_products( $order_id ) {
...
+		) {
+			$is_full_refund_without_line_items = true;
+
+			$parent_order_id    = $order->get_parent_id();
+			$parent_order       = wc_get_order( $parent_order_id );
+			$parent_order_items = $parent_order->get_items();
+
+			// Get the partially refunded products ID and revenue from the parent order.
+			$partial_refund_products = $wpdb->get_results(
+				$wpdb->prepare(
```
Comment (mikkamp) [inline plugins/woocommerce/src/Admin/API/Reports/Products/DataStore.php:491]: We can also opt to do a `GROUP BY product_id, variation_id` and then get the sum of revenue. That would simplify the array_reduce or array_walk to only separating variation_ids.

Also a `variation_id` would not be identical to `product_id`, so do we really need to keep them separate in the lookup table? If we create one lookup array indexed by either `variation_id` or `product_id` then we wouldn't need to set both key and id later on when we want to lookup a value.

File: plugins/woocommerce/src/Admin/API/Reports/Products/DataStore.php [hunk 16]
```diff
@@ -432,17 +466,144 @@ public static function sync_order_products( $order_id ) {
...
+				// So we can store the difference in the product lookup table later.
+				if ( abs( $partial_refund_product_revenue[ $id_key ][ $id ] ) !== abs( $net_revenue ) ) {
+					return true;
+				}
+
+				return false;
+			};
+
+			// Filter the items that is already being patially refunded from the parent order item.
+			$order_items = array_filter(
```
Comment (mikkamp) [inline plugins/woocommerce/src/Admin/API/Reports/Products/DataStore.php]: From my understanding the reason we are pre-filtering the order items here is because we could have some items which have already been refunded fully. However this means that we have two locations where we calculate the previous refund amount per line item. Can't we simplify that and have it go through all the parent line items, and just do a check if the refund amount is 0 then skip to the next line item.

If we simplify that, it will also make it easier to support cases where all the revenue except taxes was refunded.

So in this part I'm suggesting to completely remove the filtering of $order_items and it's helper function. And then a little further down if `$is_full_refund_without_line_items` is true and `$net_revenue` is zero we can just `continue` and skip to the next line item.

File: plugins/woocommerce/src/Admin/API/Reports/Products/DataStore.php [hunk 17]
```diff
@@ -432,17 +466,144 @@ public static function sync_order_products( $order_id ) {
...
+				$key = $variation_id ? 'variation_ids' : 'product_ids';
+				$id  = $variation_id ? $variation_id : $product_id;
+				if ( isset( $partial_refund_product_revenue[ $key ][ $id ] ) ) {
+					// If a single line item was refunded 60% then fully refunded after, we need store the difference in the product lookup table.
+					// E.g. A product costs $100, it was previously partially refunded $60, then fully refunded $40.
+					// So it will be -abs( 100 + (-60) ) = -40.
+					$net_revenue = -abs( $net_revenue + $partial_refund_product_revenue[ $key ][ $id ] );
+				} else {
+					$net_revenue = -abs( $net_revenue );
+				}
```
Comment (mikkamp) [inline plugins/woocommerce/src/Admin/API/Reports/Products/DataStore.php]: If the previous two suggestions to simplify are taken into account then we can reduce this code a bit more.

```suggestion
			if ( $is_full_refund_without_line_items ) {
				$id             = $variation_id ?: $product_id;
				$partial_refund = $partial_refund_product_revenue[ $id ] ?? 0;
				$net_revenue    = -abs( $net_revenue + $partial_refund );
				
				// Skip items that have already been fully refunded (single or multiple partial refunds).
				if ( 0.0 === $net_revenue ) {
					continue;
				}
```

**Review by mikkamp — COMMENTED** [review]
Thanks for all the refactoring, I know it's gone through a lot of changes. But when looking at the final combination of code, it looks like we could simplify some points a bit more. I've added separate comments for this.

> I think since this PR specifically solves the inconsistency in net revenue, and I don't see product gross revenue is displayed in the Products report, we could probably solve the shipping amount (and tax, coupon, etc) in the follow up PR, as I haven't thought of a good way to handle it?

While I do agree that we can address it in a follow up PR, the thing I'm hesitant about is that this functionality will land in the next release before we have the chance for a follow up PR. Since we've included a DB update function it will go through and fix entries for previous refund orders. So I think we should try and avoid a scenario where we have one release fix entries for most orders and then have the next release which again needs to fix the remaining entries.

I would prefer if we can simplify this code as much as possible (as suggested in the comments), and then add a few more test scenarios where we take additional things like taxes and coupons etc. into account. I'd personally go for a test driven development here and first create some extra unit tests and then tweak the code to make the test pass.

File: plugins/woocommerce/src/Admin/API/Reports/Products/DataStore.php [hunk 18]
```diff
@@ -433,17 +467,106 @@ public static function sync_order_products( $order_id ) {
...
+			$variation_id        = $order_item->get_variation_id( 'edit' );
 			$shipping_amount     = $order->get_item_shipping_amount( $order_item );
 			$shipping_tax_amount = $order->get_item_shipping_tax_amount( $order_item );
 			$coupon_amount       = $order->get_item_coupon_amount( $order_item );
+			$net_revenue         = round( $order_item->get_total( 'edit' ), $decimals );
+
+			// If the order is a full refund and there is no order items. The order item here is the parent order item.
+			if ( $is_full_refund_without_line_items ) {
+				$id             = $variation_id ? $variation_id : $product_id;
+				$partial_refund = $partial_refund_product_revenue[ $id ];
```
Comment (mikkamp) [inline plugins/woocommerce/src/Admin/API/Reports/Products/DataStore.php]: This needs a fallback to set to 0 as there might not be a partial refund for this product. It's causing the [unit tests to fail](https://github.com/woocommerce/woocommerce/actions/runs/12903128065/job/35977882888?pr=53019).

This was my previous suggestion:
```suggestion
				$partial_refund = $partial_refund_product_revenue[ $id ] ?? 0;
```

**Comment by ianlin** [comment]
@mikkamp Thanks again for all the reviews and suggestions. I've added more commits that make the value of `product_gross_revenue` correct when it's a full refund without line items by calculating the `tax_amount`, `shipping_amount`, `shipping_tax_amount`. Note that I set the coupon amount to `0` in that case because it's aligned with the behaviour when partially refund 1 product from the order.

I will update the migration script's versioning when the PR is ready for merge.

File: plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableDataStore.php [hunk 19]
```diff
@@ -1047,8 +1050,12 @@ public function get_total_tax_refunded( $order ) {
...
 				INNER JOIN {$wpdb->prefix}woocommerce_order_items AS order_items ON ( order_items.order_id = orders.id AND order_items.order_item_type = 'tax' )
 				WHERE order_itemmeta.order_item_id = order_items.order_item_id
-				AND order_itemmeta.meta_key IN ('tax_amount', 'shipping_tax_amount')",
-				$order->get_id()
+				AND order_itemmeta.meta_key IN (%s, %s)",
+				array(
+					$order->get_id(),
+					$include_tax_amount ? 'tax_amount' : '',
+					$include_shipping_tax_amount ? 'shipping_tax_amount' : '',
+				)
```
Comment (mikkamp) [inline plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableDataStore.php]: Not wrong but was initially confusing as I think most use the same format as `sprintf`. [According to the docs](https://developer.wordpress.org/reference/classes/wpdb/prepare/) both are allowed:

> Arguments may be passed as individual arguments to the method, or as a single array containing all arguments. A combination of the two is not supported.

File: plugins/woocommerce/includes/class-wc-order.php [hunk 20]
```diff
@@ -2161,18 +2161,21 @@ public function get_total_refunded() {
...
+	public function get_total_tax_refunded( $include_tax_amount = true, $include_shipping_tax_amount = true ) {
 		$cache_key   = WC_Cache_Helper::get_cache_prefix( 'orders' ) . 'total_tax_refunded' . $this->get_id();
 		$cached_data = wp_cache_get( $cache_key, $this->cache_group );
 
 		if ( false !== $cached_data ) {
 			return $cached_data;
 		}
 
-		$total_refunded = $this->data_store->get_total_tax_refunded( $this );
+		$total_refunded = $this->data_store->get_total_tax_refunded( $this, $include_tax_amount, $include_shipping_tax_amount );
```
Comment (mikkamp) [inline plugins/woocommerce/includes/class-wc-order.php]: The two booleans have only been added to the datastore for HPOS, shouldn't it also be added to `WC_Order_Data_Store_CPT` and `WC_Order_Data_Store_Interface` as well?

File: plugins/woocommerce/includes/class-wc-order.php [hunk 21]
```diff
@@ -2161,18 +2161,21 @@ public function get_total_refunded() {
...
 	 * Get the total tax refunded.
 	 *
+	 * @param bool $include_tax_amount          (optional) Whether to include tax amount in the total. Default true.
+	 * @param bool $include_shipping_tax_amount (optional) Whether to include shipping tax amount in the total. Default true.
+	 *
 	 * @since  2.3
 	 * @return float
 	 */
-	public function get_total_tax_refunded() {
+	public function get_total_tax_refunded( $include_tax_amount = true, $include_shipping_tax_amount = true ) {
```
Comment (mikkamp) [inline plugins/woocommerce/includes/class-wc-order.php]: Can you clarify how this handles the cache key? As it is now it looks risky, because if I call this two times in a row the same cache key would be used:

1. `get_total_tax_refunded()` - All order taxes
2. `get_total_tax_refunded( false, true )` - Only shipping taxes

I haven't tested, but based on the logic I'd assume both would return the same value.

File: plugins/woocommerce/src/Admin/API/Reports/Products/DataStore.php [hunk 22]
```diff
@@ -433,30 +467,126 @@ public static function sync_order_products( $order_id ) {
...
+					$shipping_total           = (float) $parent_order->get_shipping_total();
+					$total_shipping_to_refund = $shipping_total - $total_shipping_refunded;
+
+					if ( $total_shipping_to_refund > 0 ) {
+						$shipping_amount = -abs( $parent_order->get_item_shipping_amount( $order_item, $remaining_refund_items, $total_shipping_to_refund ) );
+					}
+
+					// Calculate the shipping tax amount to refund from the parent order.
+					$shipping_tax                 = (float) $parent_order->get_shipping_tax();
+					$total_shipping_tax_refunded  = $parent_order->get_total_tax_refunded( false, true );
```
Comment (mikkamp) [inline plugins/woocommerce/src/Admin/API/Reports/Products/DataStore.php]: Do we ever call this to fetch the total taxes refunded without shipping taxes? Because if the only case is to get the total shipping taxes, then I think it would be safer to create a separate function called `get_total_shipping_tax_refunded`. As mentioned in other comments, that would make it easier to set a unique cache key and would reduce the risk of having to change existing methods.

It would need to be implemented for each data store which would be a risk in itself in case there are plugins that extend/change the datastore. But maybe we can safeguard against that by checking if the datastore has the function `get_total_shipping_tax_refunded`.

File: plugins/woocommerce/src/Admin/Overrides/OrderTraits.php [hunk 23]
```diff
@@ -42,29 +44,35 @@ public function get_item_shipping_amount( $item ) {
...
-		foreach ( $line_items_shipping as $item_id => $shipping_item ) {
-			$tax_data = $shipping_item->get_taxes();
-			if ( $tax_data ) {
-				foreach ( $order_taxes as $tax_item ) {
-					$tax_item_id                = $tax_item->get_rate_id();
-					$tax_item_total             = isset( $tax_data['total'][ $tax_item_id ] ) ? (float) $tax_data['total'][ $tax_item_id ] : 0;
-					$total_shipping_tax_amount += $tax_item_total;
+		$total_shipping_tax_amount = $shipping_tax_amount ? $shipping_tax_amount : 0;
+
+		if ( 0 === $total_shipping_tax_amount ) {
```
Comment (mikkamp) [inline plugins/woocommerce/src/Admin/Overrides/OrderTraits.php]: I know we check against 0 before we call the function. But wouldn't it be safer to check the passed shipping_tax_amount to stay closer to the original implmentation?

```suggestion
		if ( null === $shipping_tax_amount ) {
```

File: plugins/woocommerce/src/Admin/Overrides/OrderTraits.php [hunk 24]
```diff
@@ -42,29 +44,35 @@ public function get_item_shipping_amount( $item ) {
...
+					foreach ( $order_taxes as $tax_item ) {
+						$tax_item_id                = $tax_item->get_rate_id();
+						$tax_item_total             = isset( $tax_data['total'][ $tax_item_id ] ) ? (float) $tax_data['total'][ $tax_item_id ] : 0;
+						$total_shipping_tax_amount += $tax_item_total;
+					}
 				}
 			}
 		}
+
 		return $total_shipping_tax_amount / $order_items * $product_qty;
```
Comment (mikkamp) [inline plugins/woocommerce/src/Admin/Overrides/OrderTraits.php:92]: From what I can see we override this function just to do this one line of calculation. Since we already passed it `$total_shipping_tax_amount` and `$order_items`, wouldn't it be safer to just make a helper function within `Reports/Products/DataStore` to do this calculation? It seems like it's a bit of a niche calculation we are doing here and it's not clear to me how adding this to the OrderTraits makes it useful for others to use (same applies for `get_item_shipping_amount`).

File: plugins/woocommerce/src/Admin/Overrides/OrderTraits.php [hunk 25]
```diff
@@ -42,29 +44,35 @@ public function get_item_shipping_amount( $item ) {
...
-		$order_items = $this->get_item_count();
+	public function get_item_shipping_tax_amount( $item, $order_items_count = null, $shipping_tax_amount = null ) {
+		$order_items = $order_items_count ? $order_items_count : $this->get_item_count();
 		if ( 0 === $order_items ) {
 			return 0;
 		}
 
 		$product_qty               = $item->get_quantity( 'edit' );
 		$order_taxes               = $this->get_taxes();
 		$line_items_shipping       = $this->get_items( 'shipping' );
```
Comment (mikkamp) [inline plugins/woocommerce/src/Admin/Overrides/OrderTraits.php]: These two lines are only needed if we are doing the foreach loop, so I suggest we move them within the if condition.

File: plugins/woocommerce/src/Admin/Overrides/OrderTraits.php (hunk 24 above)
Comment (mikkamp) [reply plugins/woocommerce/src/Admin/Overrides/OrderTraits.php:92]: I checked again and it seems OrderTraits are only added to Orders classes used in WC Admin, so in that aspect it will be safer to change their behaviour. However I'd still add some more context in which cases we might want to override the amounts, by describing a scenario with partial refunds in an order.

File: plugins/woocommerce/src/Admin/Overrides/OrderTraits.php [hunk 26]
```diff
@@ -80,4 +88,24 @@ public function get_item_shipping_tax_amount( $item ) {
 	public function get_item_coupon_amount( $item ) {
 		return floatval( $item->get_subtotal( 'edit' ) - $item->get_total( 'edit' ) );
 	}
+
+	/**
+	 * Calculate cart tax amount for line item/product.
+	 *
+	 * @param WC_Order_Item $item Line item from order.
+	 *
+	 * @return float|int
```
Comment (mikkamp) [inline plugins/woocommerce/src/Admin/Overrides/OrderTraits.php]: I guess this happens in other functions in this class, but if we initialize as `0.0` then we can always return a float.

File: plugins/woocommerce/src/Admin/Overrides/OrderTraits.php [hunk 27]
```diff
@@ -80,4 +88,24 @@ public function get_item_shipping_tax_amount( $item ) {
...
+	 */
+	public function get_item_cart_tax_amount( $item ) {
+		$order_taxes     = $this->get_taxes();
+		$tax_data        = $item->get_taxes();
+		$cart_tax_amount = 0;
+
+		foreach ( $order_taxes as $tax_item ) {
+			$tax_item_id      = $tax_item->get_rate_id();
+			$cart_tax_amount += isset( $tax_data['total'][ $tax_item_id ] ) ? (float) $tax_data['total'][ $tax_item_id ] : 0;
```
Comment (mikkamp) [inline plugins/woocommerce/src/Admin/Overrides/OrderTraits.php:122]: Can you clarify a bit more about what's being calculated here? From what I can see it's only adding up the tax rates if those same ID's are found in the order taxes.

In what cases do the tax ID's not line up with tax ID's in the order? For example in which scenarios can we not add up just all the taxes recorded for this line item?

**Review by mikkamp — COMMENTED** [review]
Thanks for the changes so far, that's looking great. I left some comments though and think I'd need some further explanations to make sure we are covering edge cases. Some tax scenarios can get really complicated, so want to make sure we aren't introducing inconsistencies.

File: plugins/woocommerce/src/Admin/Overrides/OrderTraits.php (hunk 27 above)
Comment (ianlin) [reply plugins/woocommerce/src/Admin/Overrides/OrderTraits.php:122]: It was actually copied from the original implementation in `Reports/Products/DataStore` here:
https://github.com/woocommerce/woocommerce/pull/53019/files#diff-d2438118f148f28d98ab96e1a12bdd753e462f4659970939f2fe3e2b87155f59L450-L456

And I think since an order line item would only have one tax rate (is it true?), we can just assign the rate to `$cart_tax_amount` when match. The commit is 40e9f29.

File: plugins/woocommerce/src/Admin/API/Reports/Products/DataStore.php (hunk 22 above)
Comment (ianlin) [reply plugins/woocommerce/src/Admin/API/Reports/Products/DataStore.php]: Thanks for the suggestion, I wasn't aware of the cache and it makes 100% sense to create a separate method for total shipping tax refunded.

> we can safeguard against that by checking if the datastore has the function get_total_shipping_tax_refunded

I'm not sure what should be doing when the method of the datastore object does not exist. Returning `0` sounds not right as the result would be incorrect. Maybe throws an error?

**Comment by ianlin** [comment]
@mikkamp Thanks for catching up the cache issue. I've updated the code according to the suggestions, it's ready for another round of review.

( I have a question from your comment here: https://github.com/woocommerce/woocommerce/pull/53019#discussion_r1959658964 )

File: plugins/woocommerce/src/Admin/API/Reports/Products/DataStore.php (hunk 22 above)
Comment (mikkamp) [reply plugins/woocommerce/src/Admin/API/Reports/Products/DataStore.php]: I'd be hesitant to error out here, from my understanding that would block any of the rows being recorded for a specific refund order.

I think we should be ok with leaving it at 0 in that case (log a non blocking warning if possible). It would then still calculate the rest just without an accurate shipping tax refunded rate (since the datastore didn't support it).

Looking at the CPT implementation for `get_total_shipping_tax_refunded` we default to 0 anyways if the query fails: `?? 0`
So might as well default to the same if the function doesn't exist in the datastore.

File: plugins/woocommerce/src/Admin/Overrides/OrderTraits.php (hunk 27 above)
Comment (mikkamp) [reply plugins/woocommerce/src/Admin/Overrides/OrderTraits.php:122]: With compound taxes, it can get complicated:
image

As we can see now in the order we have both tax rates applied per line item (also for shipping since the tax rate is set for shipping):
image

It might not be common to configure this manually but there are automatic tax plugins that apply scenarios where they might have a state tax and a city tax. So we do have to take it into consideration.

Comment (mikkamp) [reply plugins/woocommerce/src/Admin/Overrides/OrderTraits.php:122]: > It was actually copied from the original implementation in `Reports/Products/DataStore`

I can't think of a scenario where total order taxes doesn't include line item taxes, as generally we'd expect the order totals to be recalculated as soon as something changes. But I suppose since this code has been around for  along time we could leave it as is, as it still calculates the same thing.

File: plugins/woocommerce/includes/class-wc-order.php [hunk 28]
```diff
@@ -2161,27 +2161,45 @@ public function get_total_refunded() {
...
+	 */
+	public function get_total_shipping_tax_refunded() {
+		$cache_key   = WC_Cache_Helper::get_cache_prefix( 'orders' ) . 'total_shipping_tax_refunded' . $this->get_id();
+		$cached_data = wp_cache_get( $cache_key, $this->cache_group );
+
+		if ( false !== $cached_data ) {
+			return $cached_data;
+		}
+
+		$total_shipping_tax_refunded = $this->data_store->get_total_shipping_tax_refunded( $this );
```
Comment (mikkamp) [inline plugins/woocommerce/includes/class-wc-order.php]: As mentioned I'd add the fallback to 0 here if the function doesn't exist in the data store.

File: plugins/woocommerce/src/Admin/Overrides/OrderTraits.php [hunk 29]
```diff
@@ -118,8 +118,11 @@ public function get_item_cart_tax_amount( $item ) {
 		$cart_tax_amount = 0.0;
 
 		foreach ( $order_taxes as $tax_item ) {
-			$tax_item_id      = $tax_item->get_rate_id();
-			$cart_tax_amount += isset( $tax_data['total'][ $tax_item_id ] ) ? (float) $tax_data['total'][ $tax_item_id ] : 0;
+			$tax_item_id = $tax_item->get_rate_id();
+			if ( isset( $tax_data['total'][ $tax_item_id ] ) ) {
+				$cart_tax_amount = (float) $tax_data['total'][ $tax_item_id ];
+				break;
```
Comment (mikkamp) [inline plugins/woocommerce/src/Admin/Overrides/OrderTraits.php]: As mentioned in the other comment about compound taxes, I think it's safer to leave this as a `+=` and remove the break.

**Review by mikkamp — COMMENTED** [review]
Thanks for all the changes I think we are almost there now.

If we can just get a fallback for the new function not existing in the datastore. As well as a tweak to support compound taxes, and maybe an extra unit test to make sure we get expected results.

After that I think we should be pretty much there.

**Comment by ianlin** [comment]
@mikkamp Thanks again for the suggestions. After testing, it looks like the compound tax case is already covered. I went ahead and added a test for a full refund with compound tax just to be sure.

File: plugins/woocommerce/tests/legacy/unit-tests/woocommerce-admin/reports/class-wc-tests-reports-products.php [hunk 30]
```diff
@@ -491,4 +696,382 @@ public function test_report_export_arguments() {
...
+		WC_Helper_Queue::run_all_pending( 'wc-admin-data' );
+
+		// Refund the order completely by changing the order status to refunded.
+		$order->set_status( OrderStatus::REFUNDED );
+		$order->save();
+
+		WC_Helper_Queue::run_all_pending( 'wc-admin-data' );
+
+		// Get the last order item from the order.
+		$order_item_id = end( $order->get_items() )->get_id();
```
Comment (mikkamp) [inline plugins/woocommerce/tests/legacy/unit-tests/woocommerce-admin/reports/class-wc-tests-reports-products.php]: I get an error when trying to run this test locally:

> Only variables should be passed by reference

```suggestion
		$order_items   = $order->get_items();
		$order_item_id = end( $order_items )->get_id();
```

I understand that in GitHub actions it's running with `wp-env` which is different then I run it. Although it's not clear to me why the same error wouldn't be reported there. I tried testing with different PHP versions and I get the same error all the way from 7.4 - 8.3

There are a few locations in this file where we call `end` on the response of a method call.

File: plugins/woocommerce/tests/legacy/unit-tests/woocommerce-admin/reports/class-wc-tests-reports-products.php [hunk 31]
```diff
@@ -491,4 +696,382 @@ public function test_report_export_arguments() {
...
+
+		// Get the refund order id.
+		$refund_order_id = $order->get_refunds()[0]->get_id();
+
+		$result = $wpdb->get_results(
+			$wpdb->prepare(
+				'SELECT * FROM wp_wc_order_product_lookup WHERE order_item_id = %d AND order_id = %d',
```
Comment (mikkamp) [inline plugins/woocommerce/tests/legacy/unit-tests/woocommerce-admin/reports/class-wc-tests-reports-products.php]: Like I mentioned I'm not running the tests through `wp-env`, so when I run them the WP DB prefix is `wptests_` which causes this to fail because the prefix `wp_` is hardcoded.

```suggestion
				"SELECT * FROM {$wpdb->prefix}wc_order_product_lookup WHERE order_item_id = %d AND order_id = %d",
```

There are a few locations in this file where this happens.

**Review by mikkamp — COMMENTED** [review]
Thanks for all the changes. I ran the unit tests and just found a few minor adjustments needed to allow them to run in all environments.

I also did some testing on my site, but I'd like to clarify what we are expecting to fix with these issues. I see they mostly mention:
> Net sales total displayed in the Products report doesn't match the total we show in the Orders report

So I tested fully refunding an order. The products table is now showing the correct amounts:
image

Which is reflected in the report that there have been 0 sales:
image

But then when I look at the order stats table I get a different picture:
image

Which shows as a negative net sales for both the Orders and the Revenue reports:
image

image

Or do we attribute that to a flaw in the core order handling where if the status is changed to fully refunded it attributes the full refund amount to just a total:
image

When I refund per line item the entries in the order_stats table look better:
image

But the totals in the order and revenue reports are still mixed, the products report is showing correctly, so at least we did fix that.

Are we leaving the other two reports out of the picture? Because if we do we might need to update some of the changelog entries / PR description to clarify what changes we are covering.

**Comment by ianlin** [comment]
> Or do we attribute that to a flaw in the core order handling where if the status is changed to fully refunded it attributes the full refund amount to just a total:

Thanks for catching that. I believe it's a bug in the order reports, created an issue #56096.

I will update the changelog and the PR description.

**Comment by ianlin** [comment]
Thanks for the review again. I've fixed the issue in the test and also updated the PR title, description, and the changelog. It's ready for another round of review.

**Review by mikkamp — APPROVED** [review]
Thanks for the final changes. This looks ready now, so I'll go ahead and approve it.

I've just got two quick remaining comments:
1. The ` @since` tags are still pointing to 9.8.0 (do we have a placeholder?)
2. There are three changelog entries included with this PR, can we clarify in all of them that we are only fixing product reports (or merge the changelog entries)

**Comment by ianlin** [comment]
Thanks for approval!

I've merged the three changelogs into one so it's clearer that we're only solving the issues in product reports.

For the `@since` placeholder like `x.x.x`, as far as I recall WC core doesn't support it and will cause the linter error. I've changed the version for `@since` to `9.9.0`, thanks for catching it.
