### PR TITLE
[Importer/Exporter] Fixed the value display of "Published" for children of draft variable products

### LINKED ISSUE #26860: When exporting draft variable products, variation shows "1" instead of "-1"
reported and replicated for 22155803-hc

**Describe the bug**

When a variable product is set to draft mode, when exported, the variations show `1`, instead of expected `-1`. Note that the parent variable does show the `-1` as intended. 

**Screenshots**

Link to screenshot: https://d.pr/i/jhUvfv

**Isolating the problem (mark completed items with an [x]):**
- [x ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**

<details>
```
`
### WordPress Environment ###

WordPress address (URL): https://wootest2019.mystagingwebsite.com
Site address (URL): https://wootest2019.mystagingwebsite.com
WC Version: 4.2.2
REST API Version: ✔ 1.0.8
WC Blocks Version: ✔ 2.5.16
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.2.4
Log Directory Writable: ✔
WP Version: 5.4.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 7.2.31
PHP Post Max Size: 2 GB
PHP Time Limit: 1200
PHP Max Input Vars: 6144
cURL Version: 7.70.0
OpenSSL/1.1.0l

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.3.21-MariaDB-log
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.2.2
WC Database Prefix: wp_
Total Database Size: 296.25MB
Database Data Size: 198.44MB
Database Index Size: 97.81MB
wp_woocommerce_sessions: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.08MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.50MB + Index: 0.50MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.14MB + Index: 0.08MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.31MB + Index: 0.33MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpstg0_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpstg0_comments: Data: 0.08MB + Index: 0.09MB + Engine InnoDB
wpstg0_followup_coupons: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpstg0_followup_coupon_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpstg0_followup_customers: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpstg0_followup_customer_carts: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpstg0_followup_customer_notes: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpstg0_followup_customer_orders: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpstg0_followup_email_excludes: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpstg0_followup_email_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpstg0_followup_email_orders: Data: 0.08MB + Index: 0.09MB + Engine InnoDB
wpstg0_followup_email_tracking: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wpstg0_followup_followup_history: Data: 0.06MB + Index: 0.05MB + Engine InnoDB
wpstg0_followup_order_categories: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpstg0_followup_order_items: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpstg0_followup_subscribers: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpstg0_followup_subscribers_to_lists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpstg0_followup_subscriber_lists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpstg0_gf_draft_submissions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpstg0_gf_entry: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpstg0_gf_entry_meta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpstg0_gf_entry_notes: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpstg0_gf_form: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpstg0_gf_form_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpstg0_gf_form_revisions: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpstg0_gf_form_view: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpstg0_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpstg0_ms_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpstg0_options: Data: 0.28MB + Index: 0.06MB + Engine InnoDB
wpstg0_postmeta: Data: 4.52MB + Index: 6.03MB + Engine InnoDB
wpstg0_posts: Data: 1.52MB + Index: 0.34MB + Engine InnoDB
wpstg0_rg_form: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpstg0_rg_form_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpstg0_rg_form_view: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpstg0_rg_incomplete_submissions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpstg0_rg_lead: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpstg0_rg_lead_detail: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpstg0_rg_lead_detail_long: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpstg0_rg_lead_meta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpstg0_rg_lead_notes: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpstg0_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpstg0_termmeta: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
wpstg0_terms: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wpstg0_term_relationships: Data: 0.09MB + Index: 0.08MB + Engine InnoDB
wpstg0_term_taxonomy: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
wpstg0_usermeta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wpstg0_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpstg0_wcpv_commissions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpstg0_wcpv_per_product_shipping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpstg0_wc_bookings_availability: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpstg0_wc_booking_relationships: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpstg0_wc_deposits_payment_plans: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpstg0_wc_deposits_payment_plans_schedule: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpstg0_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpstg0_wc_warranty_products: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpstg0_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpstg0_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpstg0_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpstg0_woocommerce_bundled_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpstg0_woocommerce_bundled_items: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpstg0_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpstg0_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpstg0_woocommerce_order_itemmeta: Data: 0.11MB + Index: 0.09MB + Engine InnoDB
wpstg0_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpstg0_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpstg0_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpstg0_woocommerce_per_product_shipping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpstg0_woocommerce_sessions: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wpstg0_woocommerce_shipping_table_rates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpstg0_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpstg0_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpstg0_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpstg0_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpstg0_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpstg0_wpml_mails: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
wpstg0_wrd_discounts: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpstg0_wrd_sent_coupons: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpstg1_advanced_notifications: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpstg1_advanced_notification_triggers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpstg1_automatewoo_abandoned_carts: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wpstg1_automatewoo_customers: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wpstg1_automatewoo_customer_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpstg1_automatewoo_events: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpstg1_automatewoo_guests: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpstg1_automatewoo_guest_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpstg1_automatewoo_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpstg1_automatewoo_log_meta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wpstg1_automatewoo_queue: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpstg1_automatewoo_queue_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpstg1_automatewoo_referrals: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wpstg1_automatewoo_referral_advocate_keys: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpstg1_automatewoo_referral_invites: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpstg1_automatewoo_unsubscribes: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpstg1_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpstg1_comments: Data: 2.52MB + Index: 3.34MB + Engine InnoDB
wpstg1_followup_coupons: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpstg1_followup_coupon_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpstg1_followup_customers: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpstg1_followup_customer_carts: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpstg1_followup_customer_notes: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpstg1_followup_customer_orders: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpstg1_followup_email_excludes: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpstg1_followup_email_logs: Data: 0.09MB + Index: 0.05MB + Engine InnoDB
wpstg1_followup_email_orders: Data: 1.52MB + Index: 0.09MB + Engine InnoDB
wpstg1_followup_email_tracking: Data: 0.05MB + Index: 0.08MB + Engine InnoDB
wpstg1_followup_followup_history: Data: 0.34MB + Index: 0.05MB + Engine InnoDB
wpstg1_followup_order_categories: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpstg1_followup_order_items: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpstg1_followup_subscribers: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpstg1_followup_subscribers_to_lists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpstg1_followup_subscriber_lists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpstg1_gf_addon_feed: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpstg1_gf_draft_submissions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpstg1_gf_entry: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpstg1_gf_entry_meta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpstg1_gf_entry_notes: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpstg1_gf_form: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpstg1_gf_form_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpstg1_gf_form_revisions: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpstg1_gf_form_view: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpstg1_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpstg1_ms_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpstg1_options: Data: 1.52MB + Index: 0.11MB + Engine InnoDB
wpstg1_postmeta: Data: 22.52MB + Index: 16.06MB + Engine InnoDB
wpstg1_posts: Data: 3.52MB + Index: 2.45MB + Engine InnoDB
wpstg1_rg_form: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpstg1_rg_form_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpstg1_rg_form_view: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpstg1_rg_incomplete_submissions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpstg1_rg_lead: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpstg1_rg_lead_detail: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpstg1_rg_lead_detail_long: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpstg1_rg_lead_meta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpstg1_rg_lead_notes: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpstg1_say_what_strings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpstg1_signups: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpstg1_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpstg1_sp_email_logs: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpstg1_termmeta: Data: 0.14MB + Index: 0.20MB + Engine InnoDB
wpstg1_terms: Data: 0.19MB + Index: 0.22MB + Engine InnoDB
wpstg1_term_relationships: Data: 0.50MB + Index: 0.39MB + Engine InnoDB
wpstg1_term_taxonomy: Data: 0.16MB + Index: 0.19MB + Engine InnoDB
wpstg1_usermeta: Data: 0.09MB + Index: 0.09MB + Engine InnoDB
wpstg1_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpstg1_wcato_notes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpstg1_wcpv_commissions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpstg1_wcpv_per_product_shipping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpstg1_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpstg1_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpstg1_wc_bookings_availability: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpstg1_wc_bookings_availabilitymeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpstg1_wc_booking_relationships: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpstg1_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpstg1_wc_cvo_cache: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpstg1_wc_deposits_payment_plans: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpstg1_wc_deposits_payment_plans_schedule: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpstg1_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpstg1_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpstg1_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpstg1_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpstg1_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpstg1_wc_points_rewards_user_points: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpstg1_wc_points_rewards_user_points_log: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpstg1_wc_product_meta_lookup: Data: 0.22MB + Index: 0.64MB + Engine InnoDB
wpstg1_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpstg1_wc_warranty_products: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpstg1_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpstg1_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpstg1_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpstg1_woocommerce_bundled_itemmeta: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wpstg1_woocommerce_bundled_items: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpstg1_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpstg1_woocommerce_exported_csv_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpstg1_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpstg1_woocommerce_order_itemmeta: Data: 1.52MB + Index: 0.64MB + Engine InnoDB
wpstg1_woocommerce_order_items: Data: 0.09MB + Index: 0.05MB + Engine InnoDB
wpstg1_woocommerce_payment_tokenmeta: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wpstg1_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpstg1_woocommerce_per_product_shipping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpstg1_woocommerce_pickup_locations_geodata: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpstg1_woocommerce_sessions: Data: 0.08MB + Index: 0.03MB + Engine InnoDB
wpstg1_woocommerce_shipping_quotes: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpstg1_woocommerce_shipping_table_rates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpstg1_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpstg1_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpstg1_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpstg1_woocommerce_software_activations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpstg1_woocommerce_software_licenses: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpstg1_woocommerce_subscription_downloads: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpstg1_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpstg1_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpstg1_wpml_mails: Data: 15.19MB + Index: 0.00MB + Engine InnoDB
wpstg1_wrd_discounts: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpstg1_wrd_sent_coupons: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpstg1_yoast_seo_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpstg1_yoast_seo_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpstg2_actionscheduler_actions: Data: 2.52MB + Index: 1.08MB + Engine InnoDB
wpstg2_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpstg2_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpstg2_actionscheduler_logs: Data: 1.52MB + Index: 1.88MB + Engine InnoDB
wpstg2_advanced_notifications: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpstg2_advanced_notification_triggers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpstg2_afwc_hits: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpstg2_afwc_payouts: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpstg2_afwc_payout_orders: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpstg2_afwc_referrals: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wpstg2_automatewoo_abandoned_carts: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wpstg2_automatewoo_customers: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wpstg2_automatewoo_customer_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpstg2_automatewoo_events: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpstg2_automatewoo_guests: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpstg2_automatewoo_guest_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpstg2_automatewoo_logs: Data: 0.05MB + Index: 0.05MB + Engine InnoDB
wpstg2_automatewoo_log_meta: Data: 0.11MB + Index: 0.13MB + Engine InnoDB
wpstg2_automatewoo_queue: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpstg2_automatewoo_queue_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpstg2_automatewoo_referrals: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wpstg2_automatewoo_referral_advocate_keys: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpstg2_automatewoo_referral_invites: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpstg2_automatewoo_unsubscribes: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpstg2_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpstg2_comments: Data: 1.52MB + Index: 0.55MB + Engine InnoDB
wpstg2_followup_coupons: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpstg2_followup_coupon_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpstg2_followup_customers: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpstg2_followup_customer_carts: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpstg2_followup_customer_notes: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpstg2_followup_customer_orders: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpstg2_followup_email_excludes: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpstg2_followup_email_logs: Data: 0.11MB + Index: 0.05MB + Engine InnoDB
wpstg2_followup_email_orders: Data: 1.52MB + Index: 0.13MB + Engine InnoDB
wpstg2_followup_email_tracking: Data: 0.05MB + Index: 0.08MB + Engine InnoDB
wpstg2_followup_followup_history: Data: 0.41MB + Index: 0.05MB + Engine InnoDB
wpstg2_followup_order_categories: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wpstg2_followup_order_items: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpstg2_followup_subscribers: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpstg2_followup_subscribers_to_lists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpstg2_followup_subscriber_lists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpstg2_gf_addon_feed: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpstg2_gf_draft_submissions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpstg2_gf_entry: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpstg2_gf_entry_meta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpstg2_gf_entry_notes: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpstg2_gf_form: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpstg2_gf_form_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpstg2_gf_form_revisions: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpstg2_gf_form_view: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpstg2_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpstg2_ms_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpstg2_options: Data: 1.52MB + Index: 0.14MB + Engine InnoDB
wpstg2_postmeta: Data: 22.52MB + Index: 18.06MB + Engine InnoDB
wpstg2_posts: Data: 2.52MB + Index: 0.70MB + Engine InnoDB
wpstg2_rg_form: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpstg2_rg_form_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpstg2_rg_form_view: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpstg2_rg_incomplete_submissions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpstg2_rg_lead: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpstg2_rg_lead_detail: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpstg2_rg_lead_detail_long: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpstg2_rg_lead_meta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpstg2_rg_lead_notes: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpstg2_say_what_strings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpstg2_signups: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpstg2_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpstg2_sp_email_logs: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpstg2_termmeta: Data: 0.14MB + Index: 0.20MB + Engine InnoDB
wpstg2_terms: Data: 0.19MB + Index: 0.22MB + Engine InnoDB
wpstg2_term_relationships: Data: 0.34MB + Index: 0.30MB + Engine InnoDB
wpstg2_term_taxonomy: Data: 0.16MB + Index: 0.20MB + Engine InnoDB
wpstg2_usermeta: Data: 0.09MB + Index: 0.11MB + Engine InnoDB
wpstg2_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpstg2_wcato_notes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpstg2_wcpv_commissions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpstg2_wcpv_per_product_shipping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpstg2_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpstg2_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpstg2_wc_bookings_availability: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpstg2_wc_bookings_availabilitymeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpstg2_wc_booking_relationships: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpstg2_wc_category_lookup: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wpstg2_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpstg2_wc_cvo_cache: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpstg2_wc_deposits_payment_plans: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpstg2_wc_deposits_payment_plans_schedule: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpstg2_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpstg2_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpstg2_wc_order_product_lookup: Data: 0.05MB + Index: 0.06MB + Engine InnoDB
wpstg2_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpstg2_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpstg2_wc_points_rewards_user_points: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpstg2_wc_points_rewards_user_points_log: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpstg2_wc_pos_grid_tiles: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpstg2_wc_product_meta_lookup: Data: 0.23MB + Index: 0.66MB + Engine InnoDB
wpstg2_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpstg2_wc_warranty_products: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpstg2_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpstg2_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpstg2_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpstg2_woocommerce_bundled_itemmeta: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
wpstg2_woocommerce_bundled_items: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpstg2_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpstg2_woocommerce_exported_csv_items: Data: 0.11MB + Index: 0.02MB + Engine InnoDB
wpstg2_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpstg2_woocommerce_order_itemmeta: Data: 1.52MB + Index: 0.94MB + Engine InnoDB
wpstg2_woocommerce_order_items: Data: 0.11MB + Index: 0.06MB + Engine InnoDB
wpstg2_woocommerce_payment_tokenmeta: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
wpstg2_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpstg2_woocommerce_per_product_shipping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpstg2_woocommerce_pickup_locations_geodata: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpstg2_woocommerce_sessions: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpstg2_woocommerce_shipping_quotes: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpstg2_woocommerce_shipping_table_rates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpstg2_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpstg2_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpstg2_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpstg2_woocommerce_software_activations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpstg2_woocommerce_software_licenses: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpstg2_woocommerce_subscription_downloads: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpstg2_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpstg2_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpstg2_wpml_mails: Data: 19.52MB + Index: 0.00MB + Engine InnoDB
wpstg2_wrd_discounts: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpstg2_wrd_sent_coupons: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpstg2_yith_wcwl: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpstg2_yith_wcwl_lists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpstg2_yoast_seo_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpstg2_yoast_seo_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_actionscheduler_actions: Data: 8.02MB + Index: 2.83MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 3.02MB + Index: 3.03MB + Engine InnoDB
wp_advanced_notifications: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_advanced_notification_triggers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_afwc_hits: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_afwc_payouts: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_afwc_payout_orders: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_afwc_referrals: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_automatewoo_abandoned_carts: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_automatewoo_customers: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_automatewoo_customer_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_events: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_guests: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_automatewoo_guest_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_logs: Data: 0.06MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_log_meta: Data: 0.08MB + Index: 0.06MB + Engine InnoDB
wp_automatewoo_queue: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_queue_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_referrals: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_automatewoo_referral_advocate_keys: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_automatewoo_referral_invites: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_unsubscribes: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 3.23MB + Index: 2.44MB + Engine InnoDB
wp_followup_coupons: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_coupon_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_customers: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_followup_customer_carts: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_customer_notes: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_customer_orders: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_followup_email_excludes: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_email_logs: Data: 0.08MB + Index: 0.05MB + Engine InnoDB
wp_followup_email_orders: Data: 1.52MB + Index: 0.13MB + Engine InnoDB
wp_followup_email_tracking: Data: 0.05MB + Index: 0.08MB + Engine InnoDB
wp_followup_followup_history: Data: 0.31MB + Index: 0.05MB + Engine InnoDB
wp_followup_order_categories: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_followup_order_items: Data: 0.05MB + Index: 0.05MB + Engine InnoDB
wp_followup_subscribers: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_subscribers_to_lists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_subscriber_lists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gf_addon_feed: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_gf_draft_submissions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_gf_entry: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gf_entry_meta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_gf_entry_notes: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gf_form: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gf_form_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gf_form_revisions: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gf_form_view: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_ms_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 4.19MB + Index: 1.14MB + Engine InnoDB
wp_pmxi_files: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_history: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_images: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_imports: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_posts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_templates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_postmeta: Data: 33.52MB + Index: 14.81MB + Engine InnoDB
wp_posts: Data: 4.38MB + Index: 2.31MB + Engine InnoDB
wp_reward_points_balances: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_reward_points_config: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_reward_points_transaction_history: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_rg_form: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_rg_form_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_rg_form_view: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_rg_incomplete_submissions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_rg_lead: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_rg_lead_detail: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_rg_lead_detail_long: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_rg_lead_meta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_rg_lead_notes: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_say_what_strings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_signups: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_sp_email_logs: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_termmeta: Data: 0.20MB + Index: 0.25MB + Engine InnoDB
wp_terms: Data: 0.20MB + Index: 0.22MB + Engine InnoDB
wp_term_relationships: Data: 1.05MB + Index: 0.09MB + Engine InnoDB
wp_term_taxonomy: Data: 0.19MB + Index: 0.23MB + Engine InnoDB
wp_usermeta: Data: 0.14MB + Index: 0.14MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wcpv_commissions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcpv_per_product_shipping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_bookings_availability: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_bookings_availabilitymeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_booking_relationships: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_cvo_cache: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_deposits_payment_plans: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_deposits_payment_plans_schedule: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.22MB + Index: 0.19MB + Engine InnoDB
wp_wc_order_stats: Data: 0.19MB + Index: 0.11MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_wc_points_rewards_user_points: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_points_rewards_user_points_log: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_pos_grid_tiles: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.36MB + Index: 0.75MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_warranty_products: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_bundled_itemmeta: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_bundled_items: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_exported_csv_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_per_product_shipping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_pickup_locations_geodata: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_shipping_flat_rate_boxes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_quotes: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_shipping_table_rates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_software_activations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_software_licenses: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_square_customers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_subscription_downloads: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpml_mails: Data: 12.52MB + Index: 0.00MB + Engine InnoDB
wp_wrd_discounts: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wrd_sent_coupons: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_yith_wcwl: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yith_wcwl_lists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_yoast_seo_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_seo_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

addify_rfq: 1
afreg_fields: 2
attachment: 979
aw_workflow: 33
bookable_person: 20
bookable_resource: 29
course: 4
custom_css: 3
customize_changeset: 10
event_ticket: 15
follow_up_email: 27
global_product_addon: 1
jetpack_migration: 2
jp_img_sitemap: 2
jp_sitemap: 2
jp_sitemap_master: 2
jp_vid_sitemap: 2
lesson: 3
mc4wp-form: 1
nav_menu_item: 7
order_shipment: 6
page: 55
polylang_mo: 1
pos_grid: 1
pos_outlet: 2
pos_receipt: 2
pos_register: 2
pos_temp_order: 1
post: 7
product: 247
product_variation: 85
question: 1
quiz: 3
quote: 2
revision: 272
shipping_package: 6
shop_coupon: 197
shop_order: 718
shop_order_refund: 29
shop_subscription: 85
slide: 1
wapl: 3
warranty_request: 3
wc_booking: 191
wc_membership_plan: 6
wc_order_email: 1
wc_order_status: 13
wc_pickup_location: 1
wc_product_tab: 1
wc_user_membership: 18
wc_voucher: 2
wc_voucher_template: 1
wcpf_item: 5
wcpf_project: 1
wishlist: 3
woo_discount: 3
woo_discount_cart: 1
wp_block: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 4.2.2

### Inactive Plugins (106) ###

Action Scheduler: by Automattic – 3.1.6
Advanced Cron Manager: by BracketSpace – 2.3.10
Akismet Anti-Spam: by Automattic – 4.1.6
AutomateWoo: by WooCommerce – 4.9.5
AutomateWoo - Birthdays Add-on: by Prospress – 1.0.0 – Installed version not tested with active version of WooCommerce 4.2.2
AutomateWoo - Refer A Friend Add-on: by WooCommerce – 2.5.4 – Installed version not tested with active version of WooCommerce 4.2.2
AutomateWoo - Subscriptions Add-on: by Prospress Inc. – 1.0.1 – Installed version not tested with active version of WooCommerce 4.2.2
Bookings Helper: by WooCommerce – 1.0.2 – Installed version not tested with active version of WooCommerce 4.2.2
Classic Editor: by WordPress Contributors – 1.5
Code Snippets: by Code Snippets Pro – 2.14.0
Disable Real MIME Check: by Sergey Biryukov – 1.0
Facebook for WooCommerce: by Facebook – 1.11.4
Featured Listing for Product Vendors: by WooCommerce – 1.0.0 – Installed version not tested with active version of WooCommerce 4.2.2
Follow-Up Emails: by WooCommerce – 4.9.1 (update to version 4.9.2 is available) – Installed version not tested with active version of WooCommerce 4.2.2
Gravity Forms: by rocketgenius – 2.4.17
Gravity Forms User Registration Add-On: by rocketgenius – 4.0
Health Check & Troubleshooting: by The WordPress.org community – 1.4.4
Hide Title: by Dojo Digital – 1.0.8
Homepage Control: by WooThemes – 2.0.3
Jetpack by WordPress.com: by Automattic – 8.6.1
Loco Translate: by Tim Whitlock – 2.4.0
MC4WP: Mailchimp for WordPress: by ibericode – 4.7.8
Point of Sale for WooCommerce: by Actuality Extensions – 5.2.9 – Installed version not tested with active version of WooCommerce 4.2.2
Product Filters for WooCommerce: by WooCommerce – 1.2.0 (update to version 1.2.1 is available) – Installed version not tested with active version of WooCommerce 4.2.2
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 3.1.3
Reward Points By Aheadworks: by Rave Digital – 1.0.0 – Installed version not tested with active version of WooCommerce 4.2.2
Say What?: by Lee Willis – 1.9.4
Simply Show Hooks: by Stuart O'Brien
cxThemes – 1.2.1

Sofort payment gateway: by Sven Wagener – 1.4.4 – Installed version not tested with active version of WooCommerce 4.2.2
Storefront Blog Customiser: by WooCommerce – 1.3.0
Storefront Homepage Contact Section: by WooThemes – 1.0.5
Storefront Mega Menus: by WooCommerce – 1.6.2 – Installed version not tested with active version of WooCommerce 4.2.2
Storefront Parallax Hero: by WooCommerce – 1.5.7
Storefront Parallax Hero: by WooCommerce – 1.5.7
Storefront Powerpack: by WooCommerce – 1.5.0
Storefront Pricing Tables: by WooCommerce – 1.1.0
Title Remover: by WPGurus – 1.2.1
WooCommerce - ShipStation Integration: by WooCommerce – 4.1.37
WooCommerce 2Checkout API Gateway: by WooCommerce – 1.0.8 – Installed version not tested with active version of WooCommerce 4.2.2
WooCommerce Accommodation Bookings: by WooCommerce – 1.1.17
WooCommerce Additional Variation Images: by WooCommerce – 1.7.22 (update to version 1.7.23 is available) – Installed version not tested with active version of WooCommerce 4.2.2
WooCommerce All Products For Subscriptions: by SomewhereWarm – 3.1.13 (update to version 3.1.14 is available)
WooCommerce Amazon Pay: by WooCommerce – 1.12.2 – Installed version not tested with active version of WooCommerce 4.2.2
WooCommerce Archive Orders: by N.O.U.S. Ouvert Utile et Simple – 1.0 – Installed version not tested with active version of WooCommerce 4.2.2
WooCommerce AvaTax: by SkyVerge – 1.10.0
WooCommerce Beta Tester: by WooCommerce – 2.0.1 – Installed version not tested with active version of WooCommerce 4.2.2
WooCommerce Blocks: by Automattic – 2.7.1
WooCommerce Bookings: by WooCommerce – 1.15.21
WooCommerce Bookings Availability: by WooCommerce – 1.1.11 – Installed version not tested with active version of WooCommerce 4.2.2
WooCommerce Checkout Field Editor: by WooCommerce – 1.5.32 (update to version 1.5.34 is available) – Installed version not tested with active version of WooCommerce 4.2.2
WooCommerce Composite Products: by SomewhereWarm – 5.1.4 (update to version 7.0.3 is available) – Installed version not tested with active version of WooCommerce 4.2.2
WooCommerce Conditional Shipping and Payments: by SomewhereWarm – 1.7.5 (update to version 1.8.1 is available) – Installed version not tested with active version of WooCommerce 4.2.2
WooCommerce Customer/Order/Coupon CSV Import Suite: by SkyVerge – 3.8.5 (update to version 3.8.7 is available) – Installed version not tested with active version of WooCommerce 4.2.2
WooCommerce Customer/Order/Coupon Export: by SkyVerge – 5.0.12 (update to version 5.0.13 is available) – Installed version not tested with active version of WooCommerce 4.2.2
WooCommerce Deposits: by WooCommerce – 1.4.20 (update to version 1.5.1 is available) – Installed version not tested with active version of WooCommerce 4.2.2
WooCommerce Distance Rate Shipping: by Automattic – 1.0.12 (update to version 1.0.23 is available) – Installed version not tested with active version of WooCommerce 4.2.2
WooCommerce Email Customizer: by WooCommerce – 1.1.15 (update to version 1.1.16 is available) – Installed version not tested with active version of WooCommerce 4.2.2
WooCommerce FedEx Shipping: by WooCommerce – 3.4.31
WooCommerce Flat Rate Box Shipping: by WooCommerce – 2.0.13 (update to version 2.0.14 is available) – Installed version not tested with active version of WooCommerce 4.2.2
WooCommerce Force Sells: by WooCommerce – 1.1.22 (update to version 1.1.24 is available) – Installed version not tested with active version of WooCommerce 4.2.2
WooCommerce Gravity Forms Product Add-Ons: by Lucas Stark – 3.3.7 (update to version 3.3.12 is available) – Installed version not tested with active version of WooCommerce 4.2.2
WooCommerce Memberships: by SkyVerge – 1.16.5 (update to version 1.17.5 is available) – Installed version not tested with active version of WooCommerce 4.2.2
WooCommerce Min/Max Quantities: by WooCommerce – 2.4.18
WooCommerce One Page Checkout: by Automattic – 1.7.6 – Installed version not tested with active version of WooCommerce 4.2.2
WooCommerce Order Barcodes: by WooCommerce – 1.3.17 (update to version 1.3.18 is available) – Installed version not tested with active version of WooCommerce 4.2.2
WooCommerce Order Delivery: by WooCommerce – 1.6.5 (update to version 1.6.8 is available) – Installed version not tested with active version of WooCommerce 4.2.2
WooCommerce Payment Gateway Based Fees: by InoPlugs – 3.1.10 – Installed version not tested with active version of WooCommerce 4.2.2
WooCommerce Payments: by Automattic – 1.0.0 – Installed version not tested with active version of WooCommerce 4.2.2
WooCommerce Payments Dev Tools: by Automattic –  – Installed version not tested with active version of WooCommerce 4.2.2
WooCommerce PayPal Checkout Gateway: by WooCommerce – 2.0.2 – Installed version not tested with active version of WooCommerce 4.2.2
WooCommerce PayPal Payments Advanced Gateway: by WooCommerce – 1.24.9 (update to version 1.24.11 is available) – Installed version not tested with active version of WooCommerce 4.2.2
WooCommerce PayPal Powered by Braintree Gateway: by WooCommerce – 2.3.11
WooCommerce PayPal Pro (Classic and PayFlow Editions) Gateway: by WooCommerce – 4.5.0 – Installed version not tested with active version of WooCommerce 4.2.2
WooCommerce PayPal Pro Hosted: by WooCommerce – 1.0.19 (update to version 1.0.22 is available) – Installed version not tested with active version of WooCommerce 4.2.2
WooCommerce Points and Rewards: by WooCommerce – 1.6.33
WooCommerce Pre-Orders: by WooCommerce – 1.5.21 (update to version 1.5.26 is available) – Installed version not tested with active version of WooCommerce 4.2.2
WooCommerce Product Add-ons: by WooCommerce – 3.0.31 (update to version 3.0.35 is available) – Installed version not tested with active version of WooCommerce 4.2.2
WooCommerce Product Bundles: by SomewhereWarm – 5.13.0 (update to version 6.2.5 is available) – Installed version not tested with active version of WooCommerce 4.2.2
WooCommerce Product Bundles - Min/Max Items: by SomewhereWarm – 1.3.5 – Installed version not tested with active version of WooCommerce 4.2.2
WooCommerce Product CSV Import Suite: by WooCommerce – 1.10.34
WooCommerce Product Documents: by SkyVerge – 1.11.3 – Installed version not tested with active version of WooCommerce 4.2.2
WooCommerce Product Fees: by Caleb Burks – 1.3.0 – Installed version not tested with active version of WooCommerce 4.2.2
WooCommerce Product Vendors: by WooCommerce – 2.1.34 (update to version 2.1.35 is available)
WooCommerce Services: by Automattic – 1.23.2
WooCommerce Shipment Tracking: by WooCommerce – 1.6.22 (update to version 1.6.23 is available) – Installed version not tested with active version of WooCommerce 4.2.2
WooCommerce Shipping Per Product v2: by WooCommerce – 2.3.10
WooCommerce Smart Coupons: by StoreApps – 4.7.5 (update to version 4.7.6 is available) – Installed version not tested with active version of WooCommerce 4.2.2
WooCommerce Square: by WooCommerce – 2.1.5 – Installed version not tested with active version of WooCommerce 4.2.2
WooCommerce Store Credit: by WooCommerce – 2.4.6 (update to version 3.2.1 is available) – Installed version not tested with active version of WooCommerce 4.2.2
WooCommerce Stripe Gateway: by WooCommerce – 4.4.0 – Installed version not tested with active version of WooCommerce 4.2.2
WooCommerce Subscription Downloads: by WooCommerce – 1.1.18 (update to version 1.1.27 is available) – Installed version not tested with active version of WooCommerce 4.2.2
WooCommerce Subscriptions: by WooCommerce – 3.0.5
WooCommerce Subscriptions CSV Importer and Exporter: by Prospress Inc – 2.0.1 – Installed version not tested with active version of WooCommerce 4.2.2
WooCommerce Subscriptions Gifting: by WooCommerce – 2.1.0 (update to version 2.1.1 is available) – Installed version not tested with active version of WooCommerce 4.2.2
WooCommerce Table Rate Shipping: by WooCommerce – 3.0.26 (update to version 3.0.28 is available) – Installed version not tested with active version of WooCommerce 4.2.2
WooCommerce UPS Shipping: by WooCommerce – 3.2.26 (update to version 3.2.27 is available)
WooCommerce URL Coupons: by SkyVerge – 2.9.4 – Installed version not tested with active version of WooCommerce 4.2.2
WooCommerce USPS Shipping: by WooCommerce – 4.4.44
WooCommerce Warranty Requests: by WooCommerce – 1.9.13 (update to version 1.9.15 is available) – Installed version not tested with active version of WooCommerce 4.2.2
WooSlider: by WooThemes – 2.4.2
WooSlider - Instagram Slideshow: by WooThemes – 1.0.0
WP All Import: by Soflyy – 3.5.3
WP Crontrol: by John Blackbourn & crontributors – 1.8.5
WP Mail Logging: by MailPoet – 1.9.6
WP phpMyAdmin: by Puvox.software – 3.02
WP Staging: by WP-Staging – 2.7.3

### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
object-cache.php: Memcached

### Must Use Plugins (2) ###

Health Check Troubleshooting Mode: by  – 1.7.1
WP Staging Optimizer: by René Hermenau – 1.2

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: accommodation-booking (accommodation-booking)
booking (booking)
bundle (bundle)
composite (composite)
external (external)
grouped (grouped)
mix and match (mix-and-match)
photography (photography)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude_from_catalog (exclude_from_catalog)
exclude_from_search (exclude_from_search)
exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #27224 - /
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: #51 - /content-restricted/

### Theme ###

Name: Twenty Twenty
Version: 1.4
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 8,852
Oldest: 2020-05-24 17:48:24 -0400
Newest: 2020-06-22 10:20:47 -0400

Pending: 71
Oldest: 2020-06-24 16:57:06 -0400
Newest: 2021-06-03 12:04:15 -0400

Failed: 3
Oldest: 2019-09-27 12:43:54 -0400
Newest: 2019-09-27 12:43:54 -0400

Canceled: 1
Oldest: 2021-01-06 15:04:44 -0500
Newest: 2021-01-06 15:04:44 -0500

`
```
</details>

### PR DESCRIPTION
**Pull request by claudiosanches**
### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

By default variations only uses "Published" and "Private" statuses, so while exporting a draft variable product, all variations will shows as "Published" instead of a draft as expected.

Link to screenshot: https://d.pr/i/jhUvfv

This PR fixes this display, making easy for any user to understand that all children are also part of the draft product.

Closes #26860.

### How to test the changes in this Pull Request:

1. Create a variable product with some variations, and save your product as a draft.
2. Now export all your products, and note that your new variable product shows `-1` in the "Published" column, while all variations shows as `1`.
3. Apply this patch and export your products again, now note that shows `-1` for the variable product and its variations.
4. Try import the exported file from the previous step.
5. Check if the variations are still published.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Fix - [Importer/Exporter] Fixed the value display of "Published" for children of draft variable products.

### CODE REVIEW

**Review by Konamiman — APPROVED** [review]

File: includes/export/class-wc-product-csv-exporter.php [hunk 1]
```diff
@@ -268,7 +268,13 @@ protected function get_column_value_published( $product ) {
 			'publish' => 1,
 		);
 
-		$status = $product->get_status( 'edit' );
+		// Fix display for variations when parent product is a draft.
+		if ( 'variation' === $product->get_type() ) {
```
Comment (rrennick) [inline includes/export/class-wc-product-csv-exporter.php:272]: @claudiosanches You could add `'draft' === $parent['status']` to the if condition and simplify the code block.

**Review by rrennick — CHANGES_REQUESTED** [review]
@claudiosanches This looks great except for the one item.

File: includes/export/class-wc-product-csv-exporter.php (hunk 1 above)
Comment (claudiosanches) [reply includes/export/class-wc-product-csv-exporter.php:272]: We need to check first if it's a variation because we are using `WC_Product_Variation::get_parent_data`, so moving it from this code block will force us to at least check if the `get_parent_data` is callable, also increasing conditional code.

**Review by rrennick — APPROVED** [review]
