### PR TITLE
Only calls misc recommendations API when the current user can install plugin

### LINKED ISSUE #54596: There was an error loading misc recommendations
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

The error message “There was an error loading misc recommendations” appears when a user with the Shop Manager role accesses an individual order on the WooCommerce Orders page. This issue does not occur when logged in as an Administrator. Despite the error message, the functionality of the order page remains unaffected, and it continues to work as expected.

I am not sure if this is related, but disabling the “Marketplace Suggestions” options under WooCommerce > Settings > Advanced > WooCommerce.com does not resolve the issue

Image

### Expected behavior

Shop Managers should be able to open individual orders on the Orders page without encountering the “There was an error loading misc recommendations” error.

### Actual behavior

When a Shop Manager opens an order on the WooCommerce Orders page, the error message “There was an error loading misc recommendations” is displayed.

### Steps to reproduce

1. Log in as a Shop Manager.
2. Navigate to WooCommerce > Orders.
3. Open any individual order.
4. The error message “There was an error loading misc recommendations” is displayed.

### WordPress Environment

<details><summary>System Status Report</summary>

```
### WordPress Environment ###

WordPress address (URL): [Redacted]
Site address (URL): [Redacted]
WC Version: 9.5.2
Legacy REST API Package Version: The Legacy REST API plugin is not installed on this site.
Action Scheduler Version: ✔ 3.8.2
Log Directory Writable: ✔
WP Version: 6.7.1
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 8.3.15
PHP Post Max Size: 2 GB
PHP Time Limit: 850
PHP Max Input Vars: 6144
cURL Version: 8.10.1
OpenSSL/1.1.1w

SUHOSIN Installed: –
MySQL Version: 10.6.20-MariaDB-log
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

[REDACTED]

### Post Type Counts ###

attachment: 12
customize_changeset: 6
mailpoet_page: 2
page: 9
post: 1
product: 27
product_variation: 12
revision: 6
shop_coupon: 2
shop_order_placehold: 24
wp_font_face: 36
wp_font_family: 12
wp_global_styles: 2
wp_navigation: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 9.5.2

### Inactive Plugins (13) ###

Akismet Anti-spam: Spam Protection: by Automattic - Anti-spam Team – 5.3.5
hCaptcha for WP: by hCaptcha – 4.9.0
Jetpack: by Automattic – 14.3-a.1
MailPoet: by MailPoet – 5.5.2
Pressable OnePress Login: by Pressable – 1.3.2
User Role Editor: by Vladimir Garagulya – 4.64.4
WooCommerce.com Update Manager: by Automattic – 1.0.3
WooCommerce Bookings: by WooCommerce – 2.2.2
WooCommerce PayPal Payments: by WooCommerce – 2.9.6
WooCommerce Shipping: by WooCommerce – 1.3.3
WooCommerce Shipping & Tax: by WooCommerce – 2.8.6
WooCommerce Stripe Gateway: by Stripe – 9.0.0
WooPayments: by WooCommerce – 8.8.0

### Dropin Plugins () ###

advanced-cache.php: advanced-cache.php
object-cache.php: Memcached

### Settings ###

Legacy API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 109 KB

### WC Pages ###

Shop base: #5 - /shop/
Cart: #6 - /cart/ -  Contains the woocommerce/cart block
Checkout: #7 - /checkout/ -  Contains the woocommerce/checkout block
My account: #8 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 4.6.0
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
Theme type: Classic theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
onboarding
onboarding-tasks
pattern-toolkit-full-composability
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
printful
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page
launch-your-store

Disabled Features: product-data-views
experimental-blocks
coming-soon-newsletter-template
minified-js
product-pre-publish-modal
settings
async-product-editor-category-field
product-editor-template-system
blueprint
reactify-classic-payments-settings
use-wp-horizon
add-to-cart-with-options-stepper-layout

Daily Cron: ✔ Next scheduled: 2025-01-17 22:51:02 +00:00
Options: ✔
Notes: 51
Onboarding: completed

### Action Scheduler ###

Complete: 791
Oldest: 2025-01-01 22:51:17 +0000
Newest: 2025-01-17 00:03:38 +0000

Failed: 2
Oldest: 2025-01-01 23:14:04 +0000
Newest: 2025-01-01 23:16:19 +0000

Pending: 2
Oldest: 2025-01-17 20:42:32 +0000
Newest: 2025-02-08 22:44:16 +0000


### Status report information ###

Generated at: 2025-01-17 00:14:24 +00:00
```
</details>

### Isolating the problem

- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by ianlin**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes #54596.

This PR adds a check so it will only call misc recommendations API when the current user can install plugins.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Build WC using this branch
2. Go to `WooCommece > Settings > Advanced > Features`, and enable the **Order Attribution** feature
3. Create a user with "Shop manager"'s role
4. Login to wp-admin using the shop manager account
5. Go to `WooCommece > Orders`, and click any order to enter the order editor
6. From the developer console's "Network" tab, the `/wc-admin/marketing/misc-recommendations` API should not be called
7. The error notice `There was an error loading misc recommendations` should not appear
8. Go to `Analytics > Overview`
9. From the developer console's "Network" tab, the `/wc-admin/marketing/misc-recommendations` API should not be called
10. The error notice `There was an error loading misc recommendations` should not appear
11. Login using the admin account
12. Repeat step 5 and step 8, the misc recommendations API should be called and the promotion banner should appear

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

Only calls misc recommendations API when the current user can install plugin.

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce/client/admin/client/order-attribution-install-banner/use-order-attribution-install-banner.js [hunk 1]
```diff
@@ -128,10 +128,12 @@ export const useOrderAttributionInstallBanner = () => {
 				loadingRecommendations: ! hasFinishedResolution(
```
Comment (eason9487) [inline plugins/woocommerce/client/admin/client/order-attribution-install-banner/use-order-attribution-install-banner.js]: When `canUserInstallPlugins` is `false`, `loadingRecommendations` will always stay `true` because the request to the recommendations API was never started.

This doesn't seem to cause other side effects or even issues, but it's still recommended to make it conditionally determine its state according to `canUserInstallPlugins`.

**Review by eason9487 — APPROVED** [review]
Thanks for the work! Confirmed the change can fix the issue. LGTM.

Left a suggestion but it's not a blocker.

**Comment by richterdev9** [comment]
Hello - is there an eta when this fixed will be released via the plugin update?

**Comment by ianlin** [comment]
Hi @richterdev9, this fix is included in WooCommerce 9.7 and is [scheduled to release on 24th Feb](https://developer.woocommerce.com/2025/01/22/woocommerce-9-7-pre-release-updates/).

**Comment by johanmolen** [comment]
This is still an issue in 9.8.2, the API call is still made.

**Comment by emiel9d** [comment]
We are experiencing this issue in version 9.9.5.

**Comment by DanielHudson2** [comment]
Still experiencing this issue with 10.1.2

We are using `DISALLOW_FILE_MODS` to prevent plugin installs in a production environment which triggers this error still.

Also tested just removing `install_plugins` and `delete_users` (for super admins) permissions without the file mods variable and it still triggers the error.

Another thing of note, we have disabled "marketplace suggestions" under woocommerce settings so this should really be respecting that setting.
