### PR TITLE
[#20404] Fix custom webhook topic selection in dropdown

### LINKED ISSUE #20404: Custom webhooks topics are not persisted in admin UI despite data being saved
#### PR in #20406 

**Describe the bug**

If a third party tries to create a custom webhook, the topics can be correctly shown in the WooCommerce > Settings > Advanced > WebHook edit screen page when creating or editing a webhook. However, upon saving the webhook, the topic chosen is not persisted in the enhanced dropdown. However, the data is correctly stored in the Webhook, pointing to an issue with the HTML view that outputs the selected topic in the edit screen.

This can be reproduced creating a custom webhook or with a plugin like Subscriptions that introduces custom webhooks.

This is not a custom code issue (PR incoming).

**To Reproduce**

1. Ensure you have Subscriptions active or add a custom webhook via custom code
2. Go to WooCommerce > Settings > Advanced > Webhooks
3. Select one of the Subscriptions topics
4. Hit save
5. You'll notice that the selected topic is not persisted
6. However, if you dump data for that Webhook, you'll notice the topic selection is currently stored in the Webhook object

**Expected behavior**

Custom webhook topics should be persisted in the admin UI dropdown.

**Isolating the problem (mark completed items with an [x]):**

- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by unfulvio**
### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

The `selected()` function used for webhook topics does not account for custom topics and therefore fails to make them selected, making the dropdown always empty, despite being saved. This PR addresses that.

Closes #20404

### How to test the changes in this Pull Request:

1. Follow steps in #20404 
2. Try also saving / viewing / editing a core Webhook, they won't be affected

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

### Changelog entry

> * Fix - Ensure custom webhook topic selections are correctly persisted on the webhook admin edit screen

### CODE REVIEW

File: includes/admin/settings/views/html-webhooks-edit.php [hunk 1]
```diff
@@ -86,7 +86,7 @@
 
 							foreach ( $topics as $topic_slug => $topic_name ) :
 								?>
-							<option value="<?php echo esc_attr( $topic_slug ); ?>" <?php selected( $topic_data['topic'], $topic_slug, true ); ?>><?php echo esc_html( $topic_name ); ?></option>
+							<option value="<?php echo esc_attr( $topic_slug ); ?>" <?php selected( $topic_data['resource'] . '.' . $topic_data['event'], $topic_slug, true ); ?>><?php echo esc_html( $topic_name ); ?></option>
```
Comment (claudiulodro) [inline includes/admin/settings/views/html-webhooks-edit.php]: This breaks the selecting of the 'Action' topic.

Comment (claudiosanches) [reply includes/admin/settings/views/html-webhooks-edit.php]: As Claudiu said, this causes a problem.

Comment (claudiulodro) [reply includes/admin/settings/views/html-webhooks-edit.php]: After a little more inspection, the issue is caused [by this](https://github.com/woocommerce/woocommerce/blob/094fc1bf3a25bd5e42becabbb219a7d9f52077ea/includes/admin/class-wc-admin-webhooks.php#L348-L349). For `subscription` the topic becomes `custom` which won't match any of the dropdown options.

I think @unfulvio's `selected` check for both should be a good solution. 👍

**Comment by unfulvio** [comment]
thanks, I've updated PR

File: includes/admin/settings/views/html-webhooks-edit.php (hunk 1 above)
Comment (unfulvio) [reply includes/admin/settings/views/html-webhooks-edit.php]: thanks I've updated PR

File: includes/admin/settings/views/html-webhooks-edit.php [hunk 2]
```diff
@@ -85,8 +85,11 @@
 							);
 
 							foreach ( $topics as $topic_slug => $topic_name ) :
-								?>
-							<option value="<?php echo esc_attr( $topic_slug ); ?>" <?php selected( $topic_data['topic'], $topic_slug, true ); ?>><?php echo esc_html( $topic_name ); ?></option>
+
+							$selected = $topic_slug === $topic_data['topic'] || $topic_slug === $topic_data['resource'] . '.' . $topic_data['event'];
+
+							?>
+							<option value="<?php echo esc_attr( $topic_slug ); ?>" <?php selected( $selected, true, true ); ?>><?php echo esc_html( $topic_name ); ?></option>
```
[the remark this answers is not in the document]
Comment (unfulvio) [reply includes/admin/settings/views/html-webhooks-edit.php]: ok, I sent some edit, I hope it's alright now

**Review by claudiulodro — APPROVED** [review]
Looks great now. Thanks!
