### PR TITLE
Make the refunds creation REST API behave more as documented

### LINKED ISSUE #27376: Refunds via REST doesn't refund line_item quantity (update: now tax)
**Describe the bug**
Doing a full refund of an order via REST doesn't behave as expected, from reading the docs.

Doing a POST (wp-json/wc/v3/orders/123/refunds) with the data:
```
{
    "api_refund": false,
    "amount": "90",
    "line_items": [
    	{
            "id": 123 // <-- the line_item ID on the order
            "quantity": -1,
            "subtotal": "-72",
            "total": "-72"
    	}
    ]
}
```

I cannot get it to refund the line items, which messes up the reports.

**To Reproduce**
1. Just try and do a complete refund of an order via REST.
If you succeed, I'd like to know the recipe.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

I wish doing a full refund via REST would be a simple as:
```
{
   "api_refund": false,
   "full_refund": true
}
```

### PR DESCRIPTION
**Pull request by Konamiman**
### All Submissions:

* [ ] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [ ] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Companion pull request for the documentation: https://github.com/woocommerce/woocommerce-rest-api-docs/pull/191

The REST API for creating a refund is currently pretty inconsistent and [not aligned with what's documented](https://github.com/woocommerce/woocommerce/issues/27376#issuecomment-652421974).  This pull request adjusts the request parameters processing so that:

- It allows the list of line items to process to be a non-associative array where each item is identified by an `id` field.
- Same for the taxes inside line items, the amount to refund can be specified in a `refund_total` key as in the case of line items.
- Allows `quantity` keys as synonyms of `qty`.

Also, as an extra improvement, it automatically calculates the `amount` field as the sum of all the `refund_total` values, but only if the field if missing in the request and all line item and tax items have effectively a valid value for `refund_total`.
line items and taxes have a valid `refund_total` key.

Those changes are backwards compatible: the "old way" of creating refunds (by using associative arrays where the keys are the line item/tax ids, and by using `qty`) still work.

Closes https://github.com/woocommerce/woocommerce/issues/27376.

### How to test the changes in this Pull Request:

1. Temporarily add this at the ned of your `woocommerce.php` file, this way you won't have to bother about REST API authentication:

```php
add_filter('woocommerce_rest_check_permissions', function() {return true;}, 10, 0 );
```

(note that this will cause a bunch of unit tests to fail)

2. As a shopper or in the admin area create an order for two different products, with at least two units of each. Make sure to include taxes and shipping costs.

3. Get the line items and taxes ids for the order. The easiest way is to run this in the console:

```bash
curl localhost/wp-json/wc/v3/orders/<order number> | jq --sort-keys .
```

(The `jq` part is optional, it will just pretty-print the json; install with `apt-get install jq`)

Take note of the line item ids (`line_items`,  `shipping_lines`) and the tax ids from the received json:

```json
{
"line_items": [
    {
      "id": 111,
      "taxes": [
        {
          "id": 222,
        }
      ]
    }
  ],
"shipping_lines": [
    {
      "id": 333,
      "taxes": [
        {
          "id": 444,
        }
      ]
    }
  ]
}
```

4. Run the following to create a refund for one unit of each item, for a value of 1 on each case, including 1 for each tax (adjust the line item and tax ids as appropriate):

```bash
curl -X POST localhost/wp-json/wc/v3/orders/<order id>/refunds \
    -H "Content-Type: application/json" \
    -d '{
"api_refund": false,
"reason": "test",
"line_items": [
{
    "id": "<line item 1 id>",
    "quantity": 1,
    "refund_total": 1,
    "refund_tax": [
         {
        "id": "<tax of line item 1 id>",
        "refund_total": 1
        }  
    ]
},
{
    "id": "<line item 2 id>",
    "quantity": 1,
    "refund_total": 1,
    "refund_tax": [
         {
        "id": "<tax of line item 2 id>",
        "refund_total": 1
         }  
    ]
},
{
    "id": "<shipping line item id>",
    "quantity": 0,
    "refund_total": 1,
    "refund_tax": [
         {
        "id": "<tax of shipping line item id>",
        "refund_total": 1
        }  
    ]
}
]}'
```

5. Verify that the response is a json with information about the newly created refund. Load the order in admin and verify that each line item got a refund of 1 item for a value of 1, and that each tax got a refund for a value of 1 as well; also verify that the total refunded amount is correct (if you had two line items, both with taxes, and the shipping had taxes too, the total amount refunded should be 6).

### Other information:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully run tests with your changes locally?

### Changelog entry

> Fix - Make the parameters of the refund creation REST API behave as documented.

### CODE REVIEW

**Review by jonathansadowski — COMMENTED** [review]
The test-plan works for me, and I've gone through the newly written tests and code, and it appears that this would be backwards compatible — but I'm a bit hesitant to approve this without another set of eyes first, so I'm going to request a second review on this one, just to be safe.

**Comment by Konamiman** [comment]
Hi @vedanshujain , I've added you as the second reviewer since you are the most API-savvy person in the team, feel free to reassign if you deem it appropriate.

File: src/Internal/RestApiUtil.php [hunk 1]
```diff
@@ -0,0 +1,195 @@
...
+	 * - "line_items" in the request is a non-empty array.
+	 * - All line items have a "refund_total" field with a numeric value.
+	 * - All values inside "refund_tax" in all line items are a numeric value.
+	 *
+	 * The request is assumed to be in internal format already.
+	 *
+	 * @param \WP_REST_Request $request The request to maybe calculate the total amount for.
+	 */
+	private static function maybe_calculate_refund_amount_from_line_items( &$request ) {
+		if ( isset( $request['amount'] ) ) {
```
Comment (vedanshujain) [inline src/Internal/RestApiUtil.php:92]: shouldn't we give preference to line item amount if is present? what happens when both are provided but don't match?

File: src/Internal/RestApiUtil.php [hunk 2]
```diff
@@ -0,0 +1,195 @@
...
+
+			foreach ( $item['refund_tax'] as $tax ) {
+				if ( ! is_numeric( $tax ) ) {
+					return;
+				}
+				$amount += $tax;
+			}
+		}
+
+		$request['amount'] = strval( $amount );
```
Comment (vedanshujain) [inline src/Internal/RestApiUtil.php:123]: instead of setting it here, maybe we should return and set it in callee function? that way it will be more usable, wdyt?

File: src/Internal/RestApiUtil.php [hunk 3]
```diff
@@ -0,0 +1,195 @@
...
+	}
+
+	/**
+	 * Convert the line items of a refund request to internal format (see adjust_create_refund_request_parameters).
+	 *
+	 * @param array $line_items The line items to convert.
+	 * @return array The converted line items.
+	 */
+	private static function adjust_line_items_for_create_refund_request( $line_items ) {
+		if ( ! is_array( $line_items ) || empty( $line_items ) || self::is_associative( $line_items ) ) {
```
Comment (vedanshujain) [inline src/Internal/RestApiUtil.php:133]: shouldn't we throw an error if line item key is present but value is not an array? perhaps its already verified as part of validation.

File: tests/php/src/Internal/RestApiUtilTest.php [hunk 4]
```diff
@@ -0,0 +1,283 @@
...
+
+namespace Automattic\WooCommerce\Tests\Internal;
+
+use Automattic\WooCommerce\Internal\RestApiUtil;
+
+/**
+ * Tests for the RestApiUtil class.
+ * @package Automattic\WooCommerce\Tests\Internal
+ */
+class RestApiUtilTest extends \WC_Unit_Test_Case {
```
Comment (vedanshujain) [inline tests/php/src/Internal/RestApiUtilTest.php:11]: can we add a test with just `amount` param and no line items to preserve backward compat?

**Review by vedanshujain — COMMENTED** [review]
Testing well, but added some questions for clarification.

File: src/Internal/RestApiUtil.php (hunk 1 above)
Comment (Konamiman) [reply src/Internal/RestApiUtil.php:92]: The idea is that if the total `amount` is present in the request we assume that the client knows what he's doing and so we don't calculate anything, the provided amount is used even if it wouldn't match the calculation based on `refund_total`s. That's how it works now and I understand that we should keep this behavior for compatibility.

File: src/Internal/RestApiUtil.php (hunk 2 above)
Comment (Konamiman) [reply src/Internal/RestApiUtil.php:123]: I think that the problem is with the method name, instead of `calculate` it should say `adjust`; but just returning the value and calling the method only if there's no `amount` present is also a valid option.

File: src/Internal/RestApiUtil.php (hunk 3 above)
Comment (Konamiman) [reply src/Internal/RestApiUtil.php:133]: I wanted to "disrupt" the current behavior as little as possible, so if I don't find all the required data in the expected format I just leave everything untouched and rely on the already existing error checking mechanism (if there's no such thing then that's a problem, but not for the scope of this PR imho).

File: tests/php/src/Internal/RestApiUtilTest.php (hunk 4 above)
Comment (Konamiman) [reply tests/php/src/Internal/RestApiUtilTest.php:11]: Yep, good point.

Comment (Konamiman) [reply tests/php/src/Internal/RestApiUtilTest.php:11]: Actually this case is already covered in one of the tests (see `data_for_test_adjust_create_refund_request_parameters_does_not_change_amount_if_invalid_data`)

File: src/Internal/RestApiUtil.php (hunk 1 above)
Comment (vedanshujain) [reply src/Internal/RestApiUtil.php]: I tested this out, with amounts not matching:

1. When done from the API, in master, we just ignore line items altogether.

2. In UI, we don't allow to specify refund amount at all. It has to be entered via line items, and there fore takes precedence.

I guess both ways are correct then. Going approve this PR then.

**Review by vedanshujain — APPROVED** [review]
LGTM!

Note that we will allow and give preference `amount` even if line items values are present. The reason is that, incase client is specifically sending `amount` we assume that they know what they are doing, and matching values in line items with final amount is not important to them.
