### PR TITLE
Revert the use of prop here as we want to remove the attribute comple…

### LINKED ISSUE #30282: Quick editing hidden product creates duplication of visibility setting
**Prerequisites (mark completed items with an [x]):**
- [X ] I have have carried out troubleshooting steps and I believe I have found a bug.
- [X ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**

If you mark a product as hidden, and then use the "Quick edit" feature within the product list, other products will be shown as hidden as well. 

**Expected behavior**
Only the product you have marked as hidden should use this visibility

**Actual behavior**
Products you edit (using Quick Edit) after the initial hidden product copy this visibility status

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:

1. Set a product to "hidden" visibility
2. Reload the admin product list wp-admin -> products 
3. Use the "Quick edit" option to edit a hidden product and update without making any changes.
4. Use the "Quick edit" option to edit a normal product and you will see that it also says "hidden".

**Screenshots**

https://d.pr/i/91MMgN+
Direct Link: https://d.pr/i/91MMgN 

Screencast of issue: https://d.pr/i/O1Oo4H

**Isolating the problem (mark completed items with an [x]):**
- [ X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report we won't be able to fully evaluate this issue.
<details>
```
`
### WordPress Environment ###

WordPress address (URL): https://maddiesteststore.mystagingwebsite.com
Site address (URL): https://maddiesteststore.mystagingwebsite.com
WC Version: 5.5.1
REST API Version: ✔ 5.5.1
WC Blocks Version: ✔ 5.3.2
Action Scheduler Version: ✔ 3.2.1
WC Admin Version: ✔ 2.4.1
Log Directory Writable: ✔
WP Version: 5.7.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_AU
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 7.3.29
PHP Post Max Size: 2 GB
PHP Time Limit: 1200
PHP Max Input Vars: 6144
cURL Version: 7.77.0
OpenSSL/1.1.0l

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.3.30-MariaDB-log
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 5.5.1
WC Database Prefix: wp_
Total Database Size: 60.05MB
Database Data Size: 36.56MB
Database Index Size: 23.49MB
wp_woocommerce_sessions: Data: 0.08MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.09MB + Index: 0.09MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.09MB + Index: 0.13MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.08MB + Index: 0.03MB + Engine InnoDB
wp_advanced_notifications: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_advanced_notification_triggers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_automatewoo_abandoned_carts: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_automatewoo_customers: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_automatewoo_customer_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_events: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_guests: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_automatewoo_guest_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_log_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_queue: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_queue_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_referrals: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_automatewoo_referral_advocate_keys: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_automatewoo_referral_invites: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.05MB + Index: 0.09MB + Engine InnoDB
wp_extCCFA_fields: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_extCCFA_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailchimp_carts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailchimp_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ms_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 2.05MB + Index: 0.13MB + Engine InnoDB
wp_postmeta: Data: 21.47MB + Index: 15.06MB + Engine InnoDB
wp_posts: Data: 6.50MB + Index: 2.16MB + Engine InnoDB
wp_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_termmeta: Data: 0.30MB + Index: 0.20MB + Engine InnoDB
wp_terms: Data: 0.19MB + Index: 0.19MB + Engine InnoDB
wp_term_relationships: Data: 1.50MB + Index: 1.39MB + Engine InnoDB
wp_term_taxonomy: Data: 0.25MB + Index: 0.23MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wcpv_commissions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcpv_per_product_shipping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcs_payment_retries: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_bookings_availability: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_bookings_availabilitymeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_booking_relationships: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_cvo_cache: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_deposits_payment_plans: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_deposits_payment_plans_schedule: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_points_rewards_user_points: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_points_rewards_user_points_log: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_pos_grid_tiles: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.27MB + Index: 0.47MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_warranty_products: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_bundled_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_bundled_items: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_exported_csv_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_gc_activity: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_gc_cards: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_prl_deploymentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_prl_deployments: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_prl_frequencies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_prl_tracking_clicks: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_prl_tracking_conversions: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_prl_tracking_views: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_table_rates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_square_customers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpml_mails: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
wp_wps_hit: Data: 0.02MB + Index: 0.14MB + Engine InnoDB
wp_wps_index: Data: 0.16MB + Index: 0.25MB + Engine InnoDB
wp_wps_key: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wps_object_term: Data: 0.23MB + Index: 0.61MB + Engine InnoDB
wp_wps_object_type: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_wps_query: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wps_uri: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wps_user_agent: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

addify_rfq: 2
attachment: 5057
aw_workflow: 4
bookable_person: 1
bookable_resource: 6
custom_css: 1
def_reg_fields: 10
event_ticket: 2
nav_menu_item: 8
order_shipment: 4
page: 31
post: 1
pos_outlet: 1
pos_receipt: 1
pos_register: 1
product: 2248
product_tab: 1
product_variation: 156
revision: 18
shop_coupon: 4
shop_order: 58
shop_order_refund: 3
shop_subscription: 3
wcpf_item: 18
wcpf_project: 2
wc_booking: 9
wc_membership_plan: 2
wc_product_tab: 1
wc_user_membership: 1
wishlist: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (2) ###

Jetpack: by Automattic – 9.9
WooCommerce: by Automattic – 5.5.1

### Inactive Plugins (41) ###

Akismet Anti-Spam: by Automattic – 4.1.10
AutomateWoo: by WooCommerce – 5.4.2
Automatic Order Printing for WooCommerce: by Procom – 1.0.4
Bookings Helper: by WooCommerce – 1.0.3
Code Snippets: by Code Snippets Pro – 2.14.1
Conditional Checkout Fields for WooCommerce: by FME Addons – 1.0.6
Custom Product Tabs Manager: by Addify – 1.0.0
Facebook for WooCommerce: by Facebook – 2.6.0
Health Check & Troubleshooting: by The WordPress.org community – 1.4.5
Paywall for WooCommerce: by TIV.NET INC – 3.0.6 (update to version 3.2.1 is available)
Print Invoice & Delivery Notes for WooCommerce: by Tyche Softwares – 4.6.2
Product Brands for WooCommerce: by WP1 – 1.1.4
Product Filters for WooCommerce: by WooCommerce – 1.2.5
Tiered Price Table for WooCommerce: by Kolya Lukin – 4.0.0
Vertical and accordion tabs for product details: by I Thirteen Web Solution – 1.7
WhatsApp Order and Live Chat: by KoalaApps – 1.0.4
WooCommerce Bookings: by WooCommerce – 1.15.41
WooCommerce Checkout Field Editor: by WooCommerce – 1.6.1 (update to version 1.6.2 is available)
WooCommerce Composite Products: by SomewhereWarm – 8.1.1 (update to version 8.2.0 is available)
WooCommerce Conditional Shipping and Payments: by SomewhereWarm – 1.9.5
WooCommerce Deposits: by WooCommerce – 1.5.7
WooCommerce eWAY Payment Gateway: by WooCommerce – 3.2.2
WooCommerce Min/Max Quantities: by WooCommerce – 2.4.24
WooCommerce Order Barcodes: by WooCommerce – 1.3.23
WooCommerce Payment Gateway Based Fees: by InoPlugs – 3.2.3
WooCommerce Payments: by Automattic – 2.7.0
WooCommerce PayPal Checkout Gateway: by WooCommerce – 2.1.1 (update to version 2.1.2 is available)
WooCommerce Pre-Orders: by WooCommerce – 1.5.30
WooCommerce Print Invoices/Packing Lists: by SkyVerge – 3.11.3
WooCommerce Product Add-ons: by WooCommerce – 4.1.0
WooCommerce Product CSV Import Suite: by WooCommerce – 1.10.41 (update to version 1.10.42 is available)
WooCommerce Product Recommendations: by SomewhereWarm – 1.4.11 (update to version 1.4.13 is available)
WooCommerce Shipment Tracking: by WooCommerce – 1.6.26 (update to version 1.6.27 is available)
WooCommerce Shipping & Tax: by WooCommerce – 1.25.17
WooCommerce Stripe Gateway: by WooCommerce – 5.2.3
WooCommerce Subscriptions: by WooCommerce – 3.1.3
WooCommerce Subscriptions CSV Importer and Exporter: by Prospress Inc – 2.1.0
WooCommerce Table Rate Shipping: by WooCommerce – 3.0.30
WooCommerce USPS Shipping: by WooCommerce – 4.4.52 (update to version 4.4.57 is available)
WP Mail Log: by WPVibes – 0.3
WP Mail Logging: by MailPoet – 1.9.7

### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
object-cache.php: Memcached

### Must Use Plugins (1) ###

Health Check Troubleshooting Mode: by  – 1.7.2

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: booking (booking)
bundle (bundle)
composite (composite)
external (external)
grouped (grouped)
paywall (paywall)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
exclude_from_catalog (exclude_from_catalog)
exclude_from_search (exclude_from_search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #54 - /shop/
Cart: #55 - /cart/
Checkout: #56 - /checkout/
My account: #57 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty
Version: 1.7
Author URL: https://en-au.wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 240
Oldest: 2021-07-13 22:09:32 +0000
Newest: 2021-07-15 02:18:15 +0000

Failed: 1
Oldest: 2020-08-13 16:39:05 +0000
Newest: 2020-08-13 16:39:05 +0000

Pending: 2
Oldest: 2021-07-15 20:44:00 +0000
Newest: 2021-07-15 20:44:00 +0000


### Status report information ###

Generated at: 2021-07-15 02:22:32 +00:00
`
```
</details>

### PR DESCRIPTION
**Pull request by roykho**
…tely closes #30282

### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes #30282

In the jQuery migration efforts, we used `prop` to set `selected` to be false which caused an issue with the UI. So just reverting it back to `removeAttr`. Nothing needs to be done here as far as jQuery 3 migration.

### How to test the changes in this Pull Request:

1. With this PR, go to products page.
2. Click on quick edit on one of the products and choose visibility hidden and update.
3. Click on quick edit on any different product and make sure visibility is not stuck on hidden. They should show as was saved.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully run tests with your changes locally?

### Changelog entry

> Fix - Products quick edit was not showing the correct value for visibility setting.

### CODE REVIEW

**Comment by roykho** [comment]
Hi @jonathansadowski - in case you missed this. Thanks!

**Comment by jonathansadowski** [comment]
Thanks for the reminder @roykho, I tested the change, and everything looked good, but I just wanted to double-check the migration guide and try to understand why it was suggested in the first place (or if I am just misremembering it, and it was never suggested for `selected`) before I approved it. Adding to my list to follow up today.

**Comment by roykho** [comment]
Yeah it was suggested somewhere hence the change to use `prop` however I am not sure if I am misunderstanding their guide. It is said it isn't recommended to use for boolean values such as `selected, checked..etc`. However my understanding is that it applies only if the attribute is something like `selected="true"` or `checked="true"`. For our case we're just wanting to remove the attribute all together and not really looking to set the boolean value. But I could be wrong in my understand of the guide. REF: https://github.com/jquery/jquery-migrate/blob/main/warnings.md

File: assets/js/admin/quick-edit.js [hunk 1]
```diff
@@ -57,7 +57,7 @@ jQuery(
 					'select[name="_visibility"] option, ' +
 					'select[name="_stock_status"] option, ' +
 					'select[name="_backorders"] option'
-				).prop( 'selected', false );
+				).removeAttr( 'selected' );
```
Comment (jonathansadowski) [inline assets/js/admin/quick-edit.js:60]:
```suggestion
				).prop( 'selected', false ).removeAttr( 'selected' );
```

**Review by jonathansadowski — DISMISSED** [review]
Approving this, because in every browser I tested, it works... but I'm still having trouble remedying the documentation of jQuery's migration guide, so I left a suggestion that might be more thorough, but I'll leave it up to you, I think it's fine either way. Nice work.

File: assets/js/admin/quick-edit.js (hunk 1 above)
Comment (roykho) [reply assets/js/admin/quick-edit.js:60]: Or how about `)[0].removeAttribute( 'selected' );` The `[0]` gets the actual DOM element and from there we could use the vanilla JS function of `removeAttribute()`.

Comment (jonathansadowski) [reply assets/js/admin/quick-edit.js:60]: I don't think that'll work in this case, as the selector has the potential to match multiple options, so you'd have to iterate over the set of results... but not only that, I tested that on a smaller scale, and it doesn't appear to actually deselect the option.

I think it's fine as you originally had it. Behind the scenes, `$( selector ).removeAttr` appears to function differently than the native `removeAttribute()`.

Comment (roykho) [reply assets/js/admin/quick-edit.js:60]: So I actually had this:

```
				$(
					'select[name="_tax_status"] option, ' +
					'select[name="_tax_class"] option, ' +
					'select[name="_visibility"] option, ' +
					'select[name="_stock_status"] option, ' +
					'select[name="_backorders"] option'
				).each( function() {
					$( this )[0].removeAttribute( 'selected' );
				} );
```

Comment (roykho) [reply assets/js/admin/quick-edit.js:60]: But I think we could go with your suggestion as it is cleaner.

Comment (jonathansadowski) [reply assets/js/admin/quick-edit.js:60]: Ahh, yep, that appears to work. 👍
