### PR TITLE
Set product status after publishing

### LINKED ISSUE #45417: Product status is published before publishing it
The product status is prematurely set to "Published" before the actual publishing action is completed.  This problem arises specifically in scenarios where a validation error occurs during the publishing process. The product is taken as published even though it is not.

### Expected behavior

The product should be set as published after publishing it. Not before

### Steps to reproduce

1. Enable the New product editor and the Prepublish sidebar (product-pre-publish-modal) under `/wp-admin/admin.php?page=wc-settings&tab=advanced&section=features`.
2. Create a new product with SKU `product`.
3. Now create another product with the same SKU and press Publish.
4. After seeing the prepublish panel press `Publish` again.
5. A validation error will be visible, but a success message will be shown in the prepublish panel.

### PR DESCRIPTION
**Pull request by octaedro**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

This PR adds the changes to set the product status after publishing it.

Closes #45417.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Make sure the New product editor and the Prepublish sidebar (product-pre-publish-modal) are enabled under `/wp-admin/admin.php?page=wc-settings&tab=advanced&section=features`.
2. Create a new product with SKU `product`.
3. Now, create another product with the same SKU and press Publish.
4. After seeing the prepublish panel press `Publish` again.
5. Verify that a validation error will be visible and the success message is not shown in the prepublish panel.
6. Now add a valid SKU and press Publish.
7. The product should be published correctly.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Comment 

</details>

### CODE REVIEW

File: packages/js/product-editor/src/hooks/use-product-manager/use-product-manager.ts [hunk 1]
```diff
@@ -70,17 +71,21 @@ export function useProductManager< T = Product >( postType: string ) {
...
 
 			await validate( extraProps );
+			const { saveEntityRecord } = dispatch( 'core' );
 
-			// @ts-expect-error There are no types for this.
-			const { editEntityRecord, saveEditedEntityRecord } =
-				dispatch( 'core' );
-
-			await editEntityRecord< T >( 'postType', postType, id, extraProps );
+			const { blocks, content, selection, ...editedProduct } = WPSelect(
```
Comment (octaedro) [inline packages/js/product-editor/src/hooks/use-product-manager/use-product-manager.ts]: We extract the props `blocks`, `content`, and `selection` because they are not really part of the product, and that would create unexpected side effects

File: packages/js/product-editor/src/hooks/use-product-manager/use-product-manager.ts [hunk 2]
```diff
@@ -70,17 +70,21 @@ export function useProductManager< T = Product >( postType: string ) {
...
```
Comment (mdperez86) [inline packages/js/product-editor/src/hooks/use-product-manager/use-product-manager.ts]: I think the WPSelect alias should starts with lower case since it refers to a function a not to a type, interface, class or component name.

**Review by mdperez86 — APPROVED** [review]
LGTM! Nice job @octaedro. I just left one comment, it's not a blocker so feel free to merge this PR.

File: packages/js/product-editor/src/hooks/use-product-manager/use-product-manager.ts (hunk 2 above)
Comment (octaedro) [reply packages/js/product-editor/src/hooks/use-product-manager/use-product-manager.ts]: Done in https://github.com/woocommerce/woocommerce/pull/45436/commits/de14c1a86615adbc75270e1a38ee33c721fa8b90

File: packages/js/product-editor/src/hooks/use-product-manager/use-product-manager.ts [hunk 3]
```diff
@@ -70,17 +70,21 @@ export function useProductManager< T = Product >( postType: string ) {
...
-			const savedProduct = await saveEditedEntityRecord< T >(
+			const savedProduct = await saveEntityRecord(
 				'postType',
 				postType,
-				id,
+				{
+					...editedProduct,
+					...extraProps,
+				},
+				// @ts-expect-error There are no types for this.
```
Comment (louwie17) [inline packages/js/product-editor/src/hooks/use-product-manager/use-product-manager.ts:87]: @octaedro @mdperez86 as just a follow up, given we had to create a CFE for this code. Whenever we update requests logic its important to check the request payload before the change and after the change.

As we would of noticed that before this change only the edited changes would of been included in the payload and after this change all product data.

Something that is also valuable if we change GB functions in the future, is to look at the original one. For example, you can see that `saveEditedEntityRecords` [used `getEntityRecordNonTransientEdits`](https://github.com/WordPress/gutenberg/blob/6f2e542eca78f846b80a475d8ba250f82fa81f30/packages/core-data/src/actions.js#L792) and not `getEditedEntityRecord`.
