### PR TITLE
Hash customer email address in download URLs.

### LINKED ISSUE #18835: Product download URLs contain personally identifiable information (PII)
To best protect a user's identity online we should avoid passing their email address in product download links. This information is subject to be collected by 3rd party tools such as Google Analytics. In fact, if Google ever receives this information, [the website will be penalized](https://support.google.com/analytics/answer/6366371?hl=en) until the issue is resolved.

The download action (in WC_Download_Handler class) is not hooked on `init` unless the download file ID, order ID hash and user email are all present in the query string.

```php
<?php
class WC_Download_Handler {

	/**
	 * Hook in methods.
	 */
	public static function init() {
		if ( isset( $_GET['download_file'], $_GET['order'], $_GET['email'] ) ) {
			add_action( 'init', array( __CLASS__, 'download_product' ) );
		}
		add_action( 'woocommerce_download_file_redirect', array( __CLASS__, 'download_file_redirect' ), 10, 2 );
		add_action( 'woocommerce_download_file_xsendfile', array( __CLASS__, 'download_file_xsendfile' ), 10, 2 );
		add_action( 'woocommerce_download_file_force', array( __CLASS__, 'download_file_force' ), 10, 2 );
	}
```

## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Purchase an item that contains downloadable files
2. Check the customer facing receipt email that contains links to each downloadable file

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

### PR DESCRIPTION
**Pull request by alexmacarthur**
Fixes #18835. This PR removes a customer's email address from product download links by hashing the value using the `sha256` hashing algorithm. I opted for that algorithm instead of `md5` because that's what I'm consistently reading that Google requires for hashing values. 

Tested for purchases made by both account holders and guests. Additionally, fallbacks are in place for users who click older download links that still pass an email in the URL. For all new links, a `uid` is passed instead. 

https://support.google.com/analytics/answer/6366371?hl=en
https://developers.google.com/analytics/solutions/crm-integration#user_id

Open to feedback on the most maintainable way to implement this!

### CODE REVIEW

File: includes/class-wc-download-handler.php [hunk 1]
```diff
@@ -41,8 +41,26 @@ public static function download_product() {
 			self::download_error( __( 'Invalid download link.', 'woocommerce' ) );
 		}
 
+		// Fallback, accept email address if it's passed.
+		if ( empty($_GET['email'] ) && empty( $_GET['uid'] ) ) {
```
Comment (kloon) [inline includes/class-wc-download-handler.php]: Missing space before $_GET['email']

File: includes/class-wc-download-handler.php [hunk 2]
```diff
@@ -21,7 +21,7 @@ class WC_Download_Handler {
 	 * Hook in methods.
 	 */
 	public static function init() {
-		if ( isset( $_GET['download_file'], $_GET['order'], $_GET['email'] ) ) {
+		if ( isset( $_GET['download_file'], $_GET['order'] ) && ( isset($_GET['email'] ) || isset( $_GET['uid'] ) ) ) {
```
Comment (kloon) [inline includes/class-wc-download-handler.php]: Missing space before $_GET['email']

File: includes/class-wc-download-handler.php [hunk 3]
```diff
@@ -41,8 +41,26 @@ public static function download_product() {
 			self::download_error( __( 'Invalid download link.', 'woocommerce' ) );
 		}
 
+		// Fallback, accept email address if it's passed.
+		if ( empty($_GET['email'] ) && empty( $_GET['uid'] ) ) {
+			self::download_error( __( 'Invalid download link.', 'woocommerce' ) );
+		}
+
+		if(isset($_GET['email'])) {
```
Comment (kloon) [inline includes/class-wc-download-handler.php]: Missing spaces according to WP coding standards.

File: includes/class-wc-download-handler.php [hunk 4]
```diff
@@ -41,8 +41,26 @@ public static function download_product() {
...
+			$email_address = $_GET['email'];
+		} else {
+			// Get email address from order to verify hash.
+			$order_id = wc_get_order_id_by_order_key($_GET['order']);
```
Comment (kloon) [inline includes/class-wc-download-handler.php]: Missing spaces

File: includes/class-wc-download-handler.php [hunk 5]
```diff
@@ -41,8 +41,26 @@ public static function download_product() {
...
+			$order = new WC_Order($order_id);
```
Comment (kloon) [inline includes/class-wc-download-handler.php]: Missing spaces

File: includes/class-wc-download-handler.php [hunk 6]
```diff
@@ -41,8 +41,26 @@ public static function download_product() {
...
+			$email_address = $order->get_billing_email();
+
+			if( $_GET['uid'] !== hash('sha256', $email_address) ) {
```
Comment (kloon) [inline includes/class-wc-download-handler.php]: Missing spaces

File: includes/class-wc-order-item-product.php [hunk 7]
```diff
@@ -375,7 +375,7 @@ public function get_item_downloads() {
 					$files[ $download_id ]['download_url']        = add_query_arg( array(
 						'download_file' => $product_id,
 						'order'         => $order->get_order_key(),
-						'email'         => urlencode( $order->get_billing_email() ),
+						'uid'         	=> hash('sha256', $order->get_billing_email()),
```
Comment (kloon) [inline includes/class-wc-order-item-product.php]: Missing spaces

**Review by kloon — CHANGES_REQUESTED** [review]
Functionality looks good, just some Coding Standards issues regarding missing spaces.

**Comment by alexmacarthur** [comment]
Thanks, @kloon -- Pushed up a commit to fix those spacing issues.

File: includes/class-wc-download-handler.php [hunk 8]
```diff
@@ -41,8 +41,26 @@ public static function download_product() {
...
+
+		if ( isset( $_GET['email'] ) ) {
+			$email_address = $_GET['email'];
+		} else {
+			// Get email address from order to verify hash.
+			$order_id = wc_get_order_id_by_order_key( $_GET['order'] );
+			$order = new WC_Order( $order_id );
+			$email_address = $order->get_billing_email();
+
+			if( $_GET['uid'] !== hash( 'sha256', $email_address ) ) {
```
Comment (claudiosanches) [inline includes/class-wc-download-handler.php]: Missing space after `if`, and should change `!==` to `hash_equals()`.

File: includes/class-wc-order-item-product.php [hunk 9]
```diff
@@ -375,7 +375,7 @@ public function get_item_downloads() {
 					$files[ $download_id ]['download_url']        = add_query_arg( array(
 						'download_file' => $product_id,
 						'order'         => $order->get_order_key(),
-						'email'         => urlencode( $order->get_billing_email() ),
+						'uid'         	=> hash( 'sha256', $order->get_billing_email() ),
```
Comment (claudiosanches) [inline includes/class-wc-order-item-product.php]: We could just change to MD5 as Mike said.

**Review by claudiosanches — CHANGES_REQUESTED** [review]

File: includes/class-wc-download-handler.php (hunk 8 above)
Comment (alexmacarthur) [reply includes/class-wc-download-handler.php]: Good catch. 👍

File: includes/class-wc-order-item-product.php (hunk 9 above)
Comment (alexmacarthur) [reply includes/class-wc-order-item-product.php]: I like that idea in terms of performance, but I'm consistently reading that Google requires at least SHA-256 for even one-way hashing, especially considering the possible vulnerabilities of `md5`. 

https://developers.google.com/analytics/solutions/crm-integration#user_id
http://searchsecurity.techtarget.com/news/4500270165/MD5-vulnerability-renews-calls-for-faster-SHA-256-transition

It looks like WordFence has also acknowledged the possible insecurity of using `md5` for hashing: 
https://www.wordfence.com/blog/2016/12/gravatar-advisory-protect-email-address-identity/

Comment (claudiosanches) [reply includes/class-wc-order-item-product.php]: I see that this is your personal preference, since we don't need to consider vulnerabilities, since today we already display the email address anyway, we are changing to a hash just to hide this information from Google.

File: includes/class-wc-download-handler.php [hunk 10]
```diff
@@ -41,8 +41,26 @@ public static function download_product() {
...
+		if ( empty( $_GET['email'] ) && empty( $_GET['uid'] ) ) {
+			self::download_error( __( 'Invalid download link.', 'woocommerce' ) );
+		}
+
+		if ( isset( $_GET['email'] ) ) {
+			$email_address = $_GET['email'];
+		} else {
+			// Get email address from order to verify hash.
+			$order_id = wc_get_order_id_by_order_key( $_GET['order'] );
+			$order = new WC_Order( $order_id );
```
Comment (claudiosanches) [inline includes/class-wc-download-handler.php]: Need to change to:

```php
$order = wc_get_order( $order_id );
```

**Review by claudiosanches — CHANGES_REQUESTED** [review]
Just one more change and should be good to go.
Thanks for your contribution.

**Review by claudiosanches — APPROVED** [review]
