### PR TITLE
Fix WCA fatal with bail conditions for WCA execution paths

### LINKED ISSUE #32797: [WC 6.5 RC1] Fatal error with WooCommerce Admin 3.3.2 activated
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When attempting to activate WooCommerce Admin 3.3.2 alongside, the activation fails with the following error:

```
PHP Fatal error:  Uncaught Error: Access to undeclared static property: Automattic\WooCommerce\Admin\Loader::$deprecated_in_version in /var/www/html/wp-content/plugins/woocommerce/src/Admin/DeprecatedClassFacade.php:56
Stack trace:
#0 /var/www/html/wp-content/plugins/woocommerce/src/Admin/DeprecatedClassFacade.php(88): Automattic\WooCommerce\Admin\DeprecatedClassFacade::log_deprecation('should_use_mini...')
#1 /var/www/html/wp-content/plugins/woocommerce-admin/woocommerce-admin.php(94): Automattic\WooCommerce\Admin\DeprecatedClassFacade::__callStatic('should_use_mini...', Array)
#2 /var/www/html/wp-content/plugins/woocommerce-admin/woocommerce-admin.php(120): woocommerce_admin_check_build_files()
#3 /var/www/html/wp-admin/includes/plugin.php(2288): include_once('/var/www/html/w...')
#4 /var/www/html/wp-admin/plugins.php(192): plugin_sandbox_scrape('woocommerce-adm...')
#5 {main}
  thrown in /var/www/html/wp-content/plugins/woocommerce/src/Admin/DeprecatedClassFacade.php on line 5
```

I suspect this is because the entrypoint of WCA `woocommerce-admin.php` is attempting to load `plugins/woocommerce/src/Admin/Loader.php` but it does not have the appropriate static values from its extended class.

Additionally, resolving the missing static values will not prevent another fatal since WCA entrypoint also attempts to load [FeaturePlugin.php](https://github.com/woocommerce/woocommerce-admin/blob/78d0e10a99676c92650a5248917207e7304f5c1b/woocommerce-admin.php#L143) from an incomplete context (I suspect WooCommerce hasn't loaded yet). I think the appropriate fix may be to disable feature plugin altogether.

### Expected behavior

No fatal

### Actual behavior

Fatal

### Steps to reproduce

1. With WooCommerce RC.1, install WooCommerce Admin
2. Activate the plugin & observe the error

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by ilyasfoo**
### Changes proposed in this Pull Request:

Closes #32797. This PR: 

1. Attempts to resolve fatal errors when WCAdmin plugin is activated alongside
2. Deactivate WCAdmin plugin when it's detected

#### Build WooCommerce zip
1. In your local, run `git cherry-pick 1bbf2f50d390acad83b023d1ebe61224944fd102` to get proper WC version in autoloader (Original [PR](https://github.com/woocommerce/woocommerce/pull/32765)). Otherwise WCAdmin plugin may take precedence
3. Run `pnpm nx build:zip woocommerce` to build the zip

#### Testing on existing activated plugin
1. In a JN, install the latest stable WooCommerce
4. Install and activate WooCommerce Admin
5. Build the plugin in your local and upload it to the JN instance
6. Observe no fatal error

#### Testing new activation
1. Install and activate WooCommerce Admin
2. Observe no fatal error and a notice appears after the plugin is deactivated
image

### FOR PR REVIEWER ONLY:

* [x] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

File: plugins/woocommerce/src/Internal/Admin/FeaturePlugin.php [hunk 1]
```diff
@@ -115,7 +120,7 @@ protected function define_constants() {
 		 * @deprecated 3.3.0
 		 * @var string
 		 */
-		define( 'WC_ADMIN_VERSION_NUMBER', '3.3.0' );
+		$this->define( 'WC_ADMIN_VERSION_NUMBER', '3.3.0' );
```
Comment (ilyasfoo) [inline plugins/woocommerce/src/Internal/Admin/FeaturePlugin.php]: This was throwing an admin notice since `WC_ADMIN_VERSION_NUMBER` gets defined twice. It prevents plugin activation in some cases since it causes unexpected output.

image

File: plugins/woocommerce/src/Admin/Loader.php [hunk 2]
```diff
@@ -55,4 +70,20 @@ public static function is_embed_page() {
...
+	 * @return boolean If js asset should use minified version.
+	 *
+	 * @deprecated since 6.3.0, use WCAdminAssets::should_use_minified_js_file( $script_debug )
+	 */
+	public static function should_use_minified_js_file( $script_debug ) {
+		// Bail if WC isn't initialized (This can be called from WCAdmin's entrypoint).
+		if ( ! defined( 'WC_ABSPATH' ) ) {
+			return;
+		}
+		return WCAdminAssets::should_use_minified_js_file( $script_debug );
```
Comment (ilyasfoo) [inline plugins/woocommerce/src/Admin/Loader.php:87]: No deprecation notice via `wc_deprecated_function` since it also causes output during activation, which would break plugin activation.

File: plugins/woocommerce/src/Internal/Admin/Loader.php [hunk 3]
```diff
@@ -84,30 +84,29 @@ public function __construct() {
 		*/
 		remove_action( 'admin_print_scripts', 'print_emoji_detection_script' );
 
-		add_action( 'admin_init', array( __CLASS__, 'is_using_installed_wc_admin_plugin' ) );
+		add_action( 'admin_init', array( __CLASS__, 'deactivate_wc_admin_plugin' ) );
```
Comment (ilyasfoo) [inline plugins/woocommerce/src/Internal/Admin/Loader.php:87]: Replacing the now obsolete version check with deactivation check

File: plugins/woocommerce/src/Internal/Admin/FeaturePlugin.php (hunk 1 above)
Comment (adrianduffell) [reply plugins/woocommerce/src/Internal/Admin/FeaturePlugin.php]:
```suggestion
		if ( ! defined( 'WC_ADMIN_VERSION_NUMBER' ) ) {
			/**
			  * Define the current WC Admin version.
			  *
 			  * @deprecated 3.3.0
 			  * @var string
 			  */
			define( 'WC_ADMIN_VERSION_NUMBER', '3.3.0' );
		}
```

How about using `defined` to make this check rather than the `$this->define` helper? 

While it is longer, it would allow `WC_ADMIN_VERSION_NUMBER` to be deprecated explicitly with the `@deprecated` tag, and IDEs like PHPStorm can use that info to warn devs about any future usage.

Comment (ilyasfoo) [reply plugins/woocommerce/src/Internal/Admin/FeaturePlugin.php]: @adrianduffell That's a great suggestion, I wasn't aware that this change would've affected the deprecation tag. Thanks!

**Review by adrianduffell — APPROVED** [review]
This tested well and LGTM! Thanks for wrangling this @ilyasfoo 👍 🚀
