### PR TITLE
Schema 'offerCount' property should only consider 'valid' offers

### LINKED ISSUE #29153: Schema 'offerCount' property should only consider 'valid' offers
**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
The `offerCount` schema property currently outputs the total number of variations/children of a product, including those which are unavailable to purchase (and therefore aren't "offers").

**Expected behavior**
The `offerCount` property should only count the 'valid' variations (those which are available to be purchased; taking into account all known/predictable scenarios which might prevent this, such as stock status, missing pricing, etc).

**Actual behavior**
https://github.com/woocommerce/woocommerce/pull/23349 suggests that the `offerCount` is implemented as a simple count of `$product->get_children()`.

When a product has multiple dimensions, this count includes combinations which aren't purchasable (e.g., lacking a price).

**Steps to reproduce the bug**
1. Create a variable product
2. Define multiple attributes, with multiple values
3. Generate variations from all combinations
4. Configure a price on only _one_ variation
5. Save/publish the post
6. Note that the source code shows a `offerCount` property which totals all variations.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by masteradhoc**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:
The offerCount schema property was incorrectly counting all product variations, including those that are not purchasable (e.g., missing price, out of stock).

Closes #29153  .

(For Bug Fixes) Bug introduced in PR #23349.

### Screenshots or screen recordings:

| Before | After |
| ------ | ----- |
| image | image |

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Create a variable product
2. Define multiple attributes, with multiple values
3. Generate variations from all combinations
4. Configure a price on only one variation
5. Save/publish the post
6. Note that the source code shows a offerCount property which totals all variations.

Apply the fix

7. check the source code - only shows offerCount 1
8. add prices to two more variations
9. check the source code - shows offerCount 3

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 
Updated offerCount product schema value to only count purchasable product variations, excluding those without price or stock.

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce/includes/class-wc-structured-data.php [hunk 1]
```diff
@@ -255,7 +255,7 @@ public function generate_product_data( $product = null ) {
 						'@type'      => 'AggregateOffer',
 						'lowPrice'   => wc_format_decimal( $lowest, wc_get_price_decimals() ),
 						'highPrice'  => wc_format_decimal( $highest, wc_get_price_decimals() ),
-						'offerCount' => count( $product->get_children() ),
+						'offerCount' => count( $product->get_available_variations() ),
```
Comment (jorgeatorres) [inline plugins/woocommerce/includes/class-wc-structured-data.php]: Maybe we can pass `objects` as argument to at least reduce overhead.

**Review by jorgeatorres — CHANGES_REQUESTED** [review]
Hi @masteradhoc!

Thanks for working on this. I agree that `offerCount` needs to be accurate, but I'm also worried that this new version of the code involves more complex processing, introducing a bit of a performance regression.

I'd like to run some tests. In the mean time, I've left a tiny comment.

What are your thoughts?

File: plugins/woocommerce/includes/class-wc-structured-data.php (hunk 1 above)
Comment (masteradhoc) [reply plugins/woocommerce/includes/class-wc-structured-data.php]: @jorgeatorres great point! adjusted it per your request.

**Comment by masteradhoc** [comment]
@jorgeatorres any chance to check this PR out again? :)

**Review by jorgeatorres — COMMENTED** [review]
Hi @masteradhoc!

Thanks for making the changes and apologies for the delay here. It's been a bit hectic.

I ran some more careful tests, and while `get_available_variations()` is probably the more "correct" function to use here (because it even calls the relevant hooks at the product level), I'm a little concerned that it ends up iterating over all variations and instantiating all those objects.

In "practice" this isn't necessarily a huge problem because similar calls already happen during the normal page load, but I wonder if we could change this to `count( $product->get_variation_prices()['price'] `) instead. It should already take into account empty prices and stock, so in theory should return a similar value but it depends on a transient, so it's essentially free, with no instantiation of anything.

What do you think?

**Comment by masteradhoc** [comment]
Hey @jorgeatorres 
Thank you for the feedback! In my tests your function works as good as the old one so no reason not to use the more performant one :) Committed your suggestion now.

**Review by jorgeatorres — APPROVED** [review]
LGTM. Thank you @masteradhoc for the PR and your patience!
