### PR TITLE
Fix variations menu order not applying correctly when manually set cl…

### LINKED ISSUE #29630: Variation Order Does Not Save
- [X ] I have have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**

Product variation admin order does not save properly. I click the reorder icon, and enter a number, the items change position properly. Then when I reload or come back to the page, the order is wrong.

**Expected behavior**

The items remain in the order I put them.

**Actual behavior**

When leaving the page with the variations in the desired order, then returning to the page, they are in a different order.

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:

Go to a product's variations
Click the reorder icon
Enter a number
Wait for items to reorder
Reload entire page
Items are in a different order

**Screenshots**

**Isolating the problem (mark completed items with an [x]):**
- [X ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report we won't be able to fully evaluate this issue.
<details>
```
`
### WordPress Environment ###

WordPress address (URL): https://astep.design/content
Site address (URL): https://astep.design
WC Version: 5.1.0
REST API Version: ✔ 5.1.0
WC Blocks Version: ✔ 4.4.3
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 2.0.2
Log Directory Writable: ✔
WP Version: 5.7
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.4.16
PHP Post Max Size: 516 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.75.0
OpenSSL/1.1.1k

SUHOSIN Installed: –
MySQL Version: 5.7.23-23
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 5.0.0
WC Database Prefix: wp_
Total Database Size: 41.63MB
Database Data Size: 34.72MB
Database Index Size: 6.91MB
wp_woocommerce_sessions: Data: 0.16MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_api_keys: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_order_items: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wp_woocommerce_order_itemmeta: Data: 0.09MB + Index: 0.08MB + Engine MyISAM
wp_woocommerce_tax_rates: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_actionscheduler_actions: Data: 0.35MB + Index: 0.11MB + Engine MyISAM
wp_actionscheduler_claims: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_actionscheduler_groups: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_actionscheduler_logs: Data: 0.20MB + Index: 0.20MB + Engine MyISAM
wp_commentmeta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_comments: Data: 0.06MB + Index: 0.03MB + Engine MyISAM
wp_ewwwio_images: Data: 0.28MB + Index: 0.15MB + Engine MyISAM
wp_links: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_options: Data: 1.29MB + Index: 0.74MB + Engine MyISAM
wp_postmeta: Data: 2.65MB + Index: 1.12MB + Engine MyISAM
wp_posts: Data: 16.59MB + Index: 0.32MB + Engine MyISAM
wp_termmeta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_terms: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_term_relationships: Data: 0.01MB + Index: 0.02MB + Engine MyISAM
wp_term_taxonomy: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_usermeta: Data: 5.76MB + Index: 2.66MB + Engine MyISAM
wp_users: Data: 0.46MB + Index: 0.46MB + Engine MyISAM
wp_wc_admin_notes: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
wp_wc_admin_note_actions: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
wp_wc_category_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_customer_lookup: Data: 0.06MB + Index: 0.07MB + Engine MyISAM
wp_wc_download_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_order_coupon_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_order_product_lookup: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_order_stats: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_order_tax_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_product_meta_lookup: Data: 0.01MB + Index: 0.02MB + Engine MyISAM
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_webhooks: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfBlockedIPLog: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfBlocks7: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfConfig: Data: 1.94MB + Index: 0.01MB + Engine MyISAM
wp_wfCrawlers: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
wp_wfFileChanges: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfFileMods: Data: 2.44MB + Index: 0.44MB + Engine MyISAM
wp_wfHits: Data: 0.22MB + Index: 0.03MB + Engine MyISAM
wp_wfHoover: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfIssues: Data: 0.03MB + Index: 0.01MB + Engine MyISAM
wp_wfKnownFileList: Data: 1.40MB + Index: 0.14MB + Engine MyISAM
wp_wfLiveTrafficHuman: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfLocs: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfLogins: Data: 0.41MB + Index: 0.08MB + Engine MyISAM
wp_wfls_2fa_secrets: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfls_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfNotifications: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
wp_wfPendingIssues: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfReverseCache: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfSNIPCache: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfStatus: Data: 0.20MB + Index: 0.08MB + Engine MyISAM
wp_wfTrafficRates: Data: 0.00MB + Index: 0.00MB + Engine MyISAM

### Post Type Counts ###

attachment: 693
nav_menu_item: 6
page: 70
post: 61
product: 27
product_variation: 141
revision: 2439
shop_coupon: 4
shop_order: 91
shop_order_refund: 6

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (14) ###

Enable Media Replace: by ShortPixel – 3.5.0
Password Strength for WooCommerce: by Aspen Grove Studios – 1.0.2
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 3.1.5
SSL Insecure Content Fixer: by WebAware – 2.7.2
User Switching: by John Blackbourn & contributors – 1.5.6
Preview E-mails for WooCommerce: by Digamber Pradhan – 1.6.8
Print Invoice & Delivery Notes for WooCommerce: by Tyche Softwares – 4.6.2
WooCommerce Email Test: by RaiserWeb – 1.8
WooCommerce Stripe Gateway: by WooCommerce – 5.0.0
WooCommerce Price Based on Country (Basic): by Oscar Gare – 2.0.17
WooCommerce Quantity Increment: by Automattic
WooThemes – 1.1.0

WooCommerce: by Automattic – 5.1.0
Wordfence Security: by Wordfence – 7.5.2
WordPress Database Backup: by Austin Matzko – 2.3.3

### Inactive Plugins (5) ###

Akismet Anti-Spam: by Automattic – 4.1.9
Hello Dolly: by Matt Mullenweg – 1.7.2
Simple Lightbox: by Archetyped – 2.8.1
Username Changer: by Widgit Team – 3.2.2
WooThemes Helper: by WooThemes – 1.6.2 – Network enabled

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: EUR (€)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
featured (featured-2)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #4 - /shop/
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My account: #7 - /my-account/
Terms and conditions: #236 - /terms/

### Theme ###

Name: Astep
Version: 1.0.0
Author URL: http://astep.design
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: astep/woocommerce/archive-product.php version 2.0.0 is out of date. The core version is 3.4.0
astep/woocommerce/cart/cart-empty.php version 2.0.0 is out of date. The core version is 3.5.0
astep/woocommerce/cart/cart-item-data.php
astep/woocommerce/cart/cart-totals.php
astep/woocommerce/cart/cart.php version 3.0.3 is out of date. The core version is 3.8.0
astep/woocommerce/cart/proceed-to-checkout-button.php
astep/woocommerce/checkout/form-billing.php version 3.0.9 is out of date. The core version is 3.6.0
astep/woocommerce/checkout/form-checkout.php version 2.3.0 is out of date. The core version is 3.5.0
astep/woocommerce/checkout/form-shipping.php version 3.0.9 is out of date. The core version is 3.6.0
astep/woocommerce/content-product.php version 3.0.0 is out of date. The core version is 3.6.0
astep/woocommerce/content-single-product.php version 3.0.0 is out of date. The core version is 3.6.0
astep/woocommerce/emails/customer-completed-order.php version 2.5.0 is out of date. The core version is 3.7.0
astep/woocommerce/emails/customer-note.php version 2.5.0 is out of date. The core version is 3.7.0
astep/woocommerce/emails/email-order-details.php
astep/woocommerce/emails/email-order-items.php
astep/woocommerce/emails/email-styles.php version 2.3.0 is out of date. The core version is 4.0.0
astep/woocommerce/myaccount/dashboard.php version 2.6.0 is out of date. The core version is 4.4.0
astep/woocommerce/myaccount/form-edit-account.php version 2.6.0 is out of date. The core version is 3.5.0
astep/woocommerce/myaccount/form-edit-address.php version 3.0.9 is out of date. The core version is 3.6.0
astep/woocommerce/myaccount/form-login.php version 2.2.6 is out of date. The core version is 4.1.0
astep/woocommerce/myaccount/form-lost-password.php version 3.0.0 is out of date. The core version is 3.5.2
astep/woocommerce/myaccount/form-reset-password.php version 3.0.0 is out of date. The core version is 3.5.5
astep/woocommerce/myaccount/lost-password-confirmation.php version 2.6.0 is out of date. The core version is 3.9.0
astep/woocommerce/myaccount/my-account.php version 2.6.0 is out of date. The core version is 3.5.0
astep/woocommerce/myaccount/my-address.php
astep/woocommerce/myaccount/orders.php version 3.0.0 is out of date. The core version is 3.7.0
astep/woocommerce/myaccount/view-order.php
astep/woocommerce/notices/error.php version 1.6.4 is out of date. The core version is 3.9.0
astep/woocommerce/notices/notice.php version 1.6.4 is out of date. The core version is 3.9.0
astep/woocommerce/notices/success.php version 1.6.4 is out of date. The core version is 3.9.0
astep/woocommerce/single-product/add-to-cart/variable.php
astep/woocommerce/single-product/tabs/description.php
astep/woocommerce/single-product/up-sells.php
astep/woocommerce/single-product.php

Outdated Templates: ❌
					
					
						Learn how to update

### Geolocation debug info ###

Default customer location: geolocation
MaxMind GeoIP database: ✔
MaxMind GeoIP license: ✔
MM_COUNTRY_CODE: ❌
GEOIP_COUNTRY_CODE: ❌
HTTP_CF_IPCOUNTRY: ❌
HTTP_X_COUNTRY_CODE: ❌
HTTP_X_REAL_IP: ❌
HTTP_X_FORWARDED_FOR: ❌
REMOTE_ADDR: 80.161.142.178
Real external IP: 80.161.142.178
WCPBC_USE_REMOTE_ADDR: ✔
Geolocation Test: ✔

### PBC Settings ###

Version: 2.0.17
Base location: IT:MI
Base currency: EUR
Price Based On: shipping
Shipping: –
Test mode: –
Test country: –
Load products price in background: –
Prices entered with tax: –
Calculate tax based on: shipping
Display prices in the shop: incl

### Zone Pricing Europe ###

zone_id: europe
name: Europe
countries: AD | AT | BA | BE | BG | CZ | DE | EE | ES | FI | FR | GR | HR | HU | IE | IT | LT | LU | LV | MC | MK | NL | PL | PT | RO | RS | SI | SK | SM
currency: EUR
exchange_rate: 1
auto_exchange_rate: no
disable_tax_adjustment: no

### Zone Pricing Denmark ###

zone_id: denmark
name: Denmark
countries: DK
currency: DKK
exchange_rate: 1
auto_exchange_rate: no
disable_tax_adjustment: no

### Zone Pricing United Kingdom ###

zone_id: united-kingdom
name: United Kingdom
countries: GB
currency: GBP
exchange_rate: 1
auto_exchange_rate: no
disable_tax_adjustment: no

### Zone Pricing Sweden ###

zone_id: sweden
name: Sweden
countries: SE
currency: SEK
exchange_rate: 1
auto_exchange_rate: no
disable_tax_adjustment: no

### Zone Pricing Norway ###

zone_id: norway
name: Norway
countries: NO
currency: NOK
exchange_rate: 1
auto_exchange_rate: no
disable_tax_adjustment: no

### Action Scheduler ###

Complete: 70
Oldest: 2021-03-09 04:02:09 +0000
Newest: 2021-04-08 18:32:13 +0000


### Status report information ###

Generated at: 2021-04-08 18:36:11 +00:00
`
```
</details>

### PR DESCRIPTION
**Pull request by roykho**
…oses #29630

### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes #29630

So this was a bit tricky to tackle. We basically have two ways of setting the variations menu order. One is by using drag and drop which works fine. The other way is to manually set a menu order value by clicking on the drag and drop icon as noted by the tooltip if you hover over it. This is where the issue lies.  Current logic when `save_variations` action is triggered is to refresh the menu order values so they enumerate in sequential order (1..2...3...etc). After that is done, then it tries to update the current variation that you made change to, to the new menu order value in the DB. Doing could potentially create duplicated menu order values. Now when retrieving these variations menu order, it is no guarantee the order is correct anymore because you have a duplicate value where the value for that row could come before or after the variation row you are editing. Though this fix works, I feel there might be a better way. Open to suggestions.

### How to test the changes in this Pull Request:

1. Create a variable product.
2. Add a custom attribute with 20 terms.
3. Make sure to choose `Used as variations` and then save attributes.
4. Go to the variations tab and run `Create variations from all attributes`.
5. You should have at least 2 pages of variations.
6. On page 1, click on the drag and drop handle icon for the last variation.
7. You should see a window prompt asking you for the menu order value.
8. Enter 2 for example and ok/enter.
9. After an AJAX refresh, you should see the last variation is now in the second position from the top.
10. Click on each of the drag and drop handle icon to make sure the menu order values are indeed correct.
11. Perform the same test from step 6 - 10 except this time do it from page 2 and see if the results are correct.
12. Now test the drag and drop and make sure we don't have any regressions due to this fix.

**NOTE:**
It is normal for menu order values to be out of sequence in an incremental fashion. That is ok and will not deter from the function it is designed to do. For example if you only had 8 variations and you purposely set the 8th variation to menu order value of 10. As long as they're in an incremental menu order value sequentially without duplicates and from top down, it will work correctly.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully run tests with your changes locally?

### Changelog entry

> Fix - Variations menu order not applying correctly when manually set in some cases.

### FOR PR REVIEWER ONLY:

* [x] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

File: includes/admin/meta-boxes/class-wc-meta-box-product-data.php [hunk 1]
```diff
@@ -446,6 +448,35 @@ public static function save_variations( $post_id, $post ) {
...
+				);
+
+				foreach ( $ids as $id ) {
+					$wpdb->query(
+						$wpdb->prepare(
+							"UPDATE {$wpdb->posts} SET menu_order = menu_order + 1 WHERE ID = %d",
+							$id
+						)
+					);
+				}
```
Comment (jonathansadowski) [inline includes/admin/meta-boxes/class-wc-meta-box-product-data.php]: Is there any reason to not do this as a single query?

Something like this?...

```suggestion
				$wpdb->query(
					$wpdb->prepare(
						"UPDATE {$wpdb->posts} SET menu_order = menu_order + 1 WHERE post_type = 'product_variation' AND post_parent = %d AND post_status = 'publish' AND menu_order >= %d AND ID != %d",
						$post_id,
						$new_variation_menu_order_value,
						$new_variation_menu_order_id
					)
				);
```

Comment (roykho) [reply includes/admin/meta-boxes/class-wc-meta-box-product-data.php]: Good find. So in my original solution the order mattered `ORDER BY menu_order ASC` but not anymore in this case so I think a single query is a good idea. Thanks.

**Review by jonathansadowski — APPROVED** [review]
Re-tested after the update to single query, and everything still works as expected. Good work 👍 

Note, the nightly test failure is unrelated, see p1628528704105900-slack-C0E1AV8T0
