### PR TITLE
Core - CYS: fix fonts not loaded on the font picker iframes

### LINKED ISSUE #44427: [CYS on Core] Fix fonts are not loaded on the font picker
The font family used on the font picker is not the expected.
 

| Core | WooExpress |
|--------|--------|
| Screenshot 2024-02-07 at 13 27 25 | Screenshot 2024-02-07 at 13 27 30 |

### PR DESCRIPTION
**Pull request by gigitux**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes #44427.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

### Local Installation

1. Create a new WooCommerce installation with this version.
2. Ensure the WooCommerce Beta Tester plugin is installed and activated (available on this monorepo).
3. Head over to `/wp-admin/tools.php?page=woocommerce-admin-test-helper` and enable `customize-store` feature flag.
4. Install this build of Gutenberg that contains the new Font Library API: [gutenberg.zip](https://github.com/woocommerce/woocommerce/files/14236920/gutenberg.zip)
5. Go on `/wp-admin/admin.php?page=wc-settings&tab=advanced&section=woocommerce_com` and enable the tracking.
6. Visit the `wp-admin/admin.php?page=wc-admin&path=/customize-store`.
7. Follow the process.
8. Click on `Change your font`.
9. For each preview, ensure that the right fonts are rendered.

image

### Woo Express installation

1. Create a new WooCommerce installation with this version.
2. Ensure Jetpack is installed and your site is connected with JP.
3. Ensure the WooCommerce Beta Tester plugin is installed and activated (available on this monorepo).
4. Ensure the Woo AI plugin is installed and activated (available on this monorepo).
5. Head over to `/wp-admin/tools.php?page=woocommerce-admin-test-helper` and enable `customize-store` feature flag.
6. Head over to WooCommerce -> Home and click on "Start Customizing".
7. Ensure that all the flow works correctly.
8. Follow the process.
9. Click on `Change your font`.
10. For each preview, ensure that the right fonts are rendered.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce-admin/client/customize-store/assembler-hub/sidebar/global-styles/font-pairing-variations/preview.tsx [hunk 1]
```diff
@@ -181,6 +204,13 @@ export const FontPairingVariationPreview = () => {
 						onLoad={ handleOnLoad }
 					/>
 				) }
+				{ isNoAIFlow( context.flowType ) && (
+					<FontFamiliesLoader
```
Comment (nefeline) [inline plugins/woocommerce-admin/client/customize-store/assembler-hub/sidebar/global-styles/font-pairing-variations/preview.tsx:208]: 👍

**Review by nefeline — APPROVED** [review]
Nice work! Confirmed the fonts are being correctly loaded on the sidebar.
