### PR TITLE
WP 6.9: load WP Button block styles when rendering the Add to Cart Button

### LINKED ISSUE #61901: WordPress 6.9: Add to Cart Button no longer inherits styles from the core Button block
Apparently, [https://github.com/woocommerce/woocommerce/issues/53138](https://github.com/woocommerce/woocommerce/issues/53138) has resurfaced again with WordPress 6.9: if the *Button* block is not on the page, the *Add to Cart Button* won't inherit its styles.

## **To Reproduce**

Compare the *Shop* page in these cases:

1. WP 6.8:

2. WP 6.9 beta 4:

3. WP 6.9 beta 4 when there is a *Button* block on the page:

As seen in the screenshots, the add-to-cart buttons don't have the rounded borders if the *Button* block is not rendered on the same page.

## **Expected behavior**

The *Add to Cart Button* block should inherit the styles from the *Button* block. In other words, styles should be the same in WP 6.9 than in WP 6.8.

### PR DESCRIPTION
**Pull request by Aljullu**
### Submission Review Guidelines:

Closes #61901.

The work-around we had to load Gutenberg's _Button_ styles when rendering the _Add to Cart Button_ block stopped working in WP 6.9. I refactored it in this PR by using `wp_enqueue_style()`, which seems to work fine.

### How to test the changes in this Pull Request:

1. With a block theme and WP 6.9, go to the _Shop_ page.
2. Verify the Add to Cart buttons have the theme button style. In TT5, they are rounded, you can also tweak their styles in the Site Editor to make it more evident.
3. Repeat the test with WP 6.8 to make sure we aren't introducing a regression in previous versions.

Before | After
--- | ---
imatge | imatge

### CODE REVIEW

File: plugins/woocommerce/src/Blocks/BlockTypes/ProductButton.php [hunk 1]
```diff
@@ -74,9 +74,10 @@ public function dequeue_add_to_cart_scripts() {
 	 * @return string Rendered block type output.
 	 */
 	protected function render( $attributes, $content, $block ) {
-		// This workaround ensures that WordPress loads the core/button block styles.
-		// For more details, see https://github.com/woocommerce/woocommerce/pull/53052.
-		( new \WP_Block( array( 'blockName' => 'core/button' ) ) )->render();
+		// The Product Button block uses the same classes as the GB core block
+		// because we want to inherit its styles. That's why we also need to
+		// enqueue its stylesheet.
+		wp_enqueue_style( 'wp-block-button' );
```
Comment (gigitux) [inline plugins/woocommerce/src/Blocks/BlockTypes/ProductButton.php]: Should we specify that this is a workaround?

**Review by gigitux — APPROVED** [review]
Thanks for catching this regression! The PR LGTM!

https://github.com/user-attachments/assets/ea3c7554-366b-4472-b220-e33dbc679e8d

File: plugins/woocommerce/src/Blocks/BlockTypes/ProductButton.php (hunk 1 above)
Comment (Aljullu) [reply plugins/woocommerce/src/Blocks/BlockTypes/ProductButton.php]: Good point, I updated the comment in 822da8b7e1b90d7e707251c6c1ea11d5cee96658.
