### PR TITLE
Fix a11y issues in Cart/Checkout

### LINKED ISSUE #43561: Accessibility: Mini Cart does not return keyboard focus to the button that triggers it when closed.
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When closing the Mini Cart modal either via the close button or the escape key, keyboard focus is not returned to the mini cart button. Instead, users are dumped into the footer of the website.

### Expected behavior

When a modal is closed, focus must be returned to the element that triggered it.

This ensures that keyboard-only and screen reader users don't lose their place in the page.

See these references for more information:

- [ARIA Authoring Practices Guide Dialog (Modal) Pattern](https://www.w3.org/WAI/ARIA/apg/patterns/dialog-modal/)
- F[ocus Modal Not Returned on Deque](https://docs.deque.com/issue-help/1.0.0/en/focus-modal-not-returned)

### Actual behavior

When the modal is closed focus is lost. Hitting Tab puts the user in the address bar.

### Steps to reproduce

1. Add the Mini Cart button to a page.
2. Open the Mini Cart modal.
3. Close the modal with the escape key or close button.
4. Hit the Tab key and see that instead of going to the next focusable element on the page, you'll be in the browser address bar.

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://shop.equalizedigital.com
Site address (URL): https://shop.equalizedigital.com
WC Version: 8.4.0
REST API Version: ✔ 8.4.0
WC Blocks Version: ✔ 11.6.2
Action Scheduler Version: ✔ 3.7.1
Log Directory Writable: ✔
WP Version: 6.4.2
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 8.2.14
PHP Post Max Size: 100 MB
PHP Time Limit: 43300
PHP Max Input Vars: 10000
cURL Version: 7.81.0
OpenSSL/3.0.2

SUHOSIN Installed: –
MySQL Version: 8.0.35-27
Max Upload Size: 50 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.4.0
WC Database Prefix: wp_
Total Database Size: 11.55MB
Database Data Size: 7.50MB
Database Index Size: 4.05MB
wp_woocommerce_sessions: Data: 0.08MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_ac_segments: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_accessibility_checker: Data: 1.44MB + Index: 0.02MB + Engine InnoDB
wp_accessibility_checker_audit_history: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_accessibility_checker_global_ignores: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_actionscheduler_actions: Data: 1.50MB + Index: 0.83MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.42MB + Index: 0.36MB + Engine InnoDB
wp_admin_columns: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_gf_draft_submissions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_gf_entry: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gf_entry_meta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_gf_entry_notes: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gf_form: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gf_form_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gf_form_revisions: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gf_form_view: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gf_rest_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 0.45MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 1.52MB + Index: 0.56MB + Engine InnoDB
wp_posts: Data: 0.42MB + Index: 0.14MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.06MB + Index: 0.05MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.06MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woo_shippment_provider: Data: 0.14MB + Index: 0.00MB + Engine InnoDB
wp_wpforms_payment_meta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wpforms_payments: Data: 0.02MB + Index: 0.14MB + Engine InnoDB
wp_wpforms_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpmailsmtp_debug_events: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpmailsmtp_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_yoast_indexable: Data: 0.05MB + Index: 0.09MB + Engine InnoDB
wp_yoast_indexable_hierarchy: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_primary_term: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_yoast_seo_links: Data: 0.02MB + Index: 0.03MB + Engine InnoDB

### Post Type Counts ###

attachment: 127
custom_css: 1
customize_changeset: 26
page: 13
post: 3
product: 14
product_variation: 257
shop_order_placehold: 1
wp_global_styles: 1
wp_navigation: 5
wp_template: 5
wp_template_part: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (16) ###

Gravity Forms: by Gravity Forms – 2.8.1
Accessibility Checker: Audit History: by Equalize Digital – 1.0.2
Accessibility Checker Pro: by Equalize Digital – 1.5.2
Accessibility Checker: by Equalize Digital – 1.7.0
Accessibility New Window Warnings: by Equalize Digital – 1.0.8
Admin Columns Pro: by AdminColumns.com – 6.4.3
WP Engine Smart Plugin Manager: by WP Engine – 5.17.30
Font Awesome: by Font Awesome – 4.4.0
Gravity Forms Zero Spam: by GravityKit – 1.4.1
Printful Integration for WooCommerce: by Printful – 2.2.7
SimpleTOC - Table of Contents Block: by Marc Tönsing – 6.0.14
Advanced Shipment Tracking for WooCommerce: by zorem – 3.6.5
WooCommerce Stripe Gateway: by WooCommerce – 7.9.0
WooCommerce: by Automattic – 8.4.0
Yoast SEO: by Team Yoast – 21.8
WP Mail SMTP: by WP Mail SMTP – 3.11.0

### Inactive Plugins (2) ###

Akismet Anti-spam: Spam Protection: by Automattic - Anti-spam Team – 5.3
Variation Swatches for WooCommerce: by Emran Ahmed – 2.0.29

### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
object-cache.php: Memcached Redux

### Must Use Plugins (5) ###

Force Strong Passwords - WPE Edition: by Jason Cosper – 1.8.0
WP Engine Cache Plugin: by WP Engine – 1.1.4
WP Engine Seamless Login Plugin: by WP Engine – 1.6.1
WP Engine Security Auditor: by wpengine – 1.1.1
WP Engine System: by WP Engine – 5.0.1

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to Woo.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### WC Pages ###

Shop base: #31 - /shop/
Cart: #32 - /cart/
Checkout: #33 - /checkout/
My account: #34 - /my-account/
Terms and conditions: #35 - /refund-returns/

### Theme ###

Name: Twenty Twenty-Four
Version: 1.0
Author URL: https://wordpress.org
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ❌ Not declared

### Templates ###

Overrides: /nas/content/live/edshopprd/wp-content/plugins/woocommerce/packages/woocommerce-blocks/templates/notices/error.php
/nas/content/live/edshopprd/wp-content/plugins/woocommerce/packages/woocommerce-blocks/templates/notices/notice.php
/nas/content/live/edshopprd/wp-content/plugins/woocommerce/packages/woocommerce-blocks/templates/notices/success.php

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
product-virtual-downloadable
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: customize-store
minified-js
new-product-management-experience
product-external-affiliate
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2024-01-12 22:12:37 -06:00
Options: ✔
Notes: 70
Onboarding: completed

### Action Scheduler ###

Complete: 2,712
Oldest: 2023-12-18 21:21:19 -0600
Newest: 2024-01-12 09:31:39 -0600

Failed: 2
Oldest: 2024-01-03 00:25:12 -0600
Newest: 2024-01-03 00:25:12 -0600

Pending: 5
Oldest: 2024-01-12 09:32:39 -0600
Newest: 2024-01-12 20:50:19 -0600

### Status report information ###

Generated at: 2024-01-12 09:31:52 -06:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### LINKED ISSUE #43615: Accessibility: View cart link in notice banner fails color contrast and uses color alone to indicate state
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

The link color for the view cart link in the banner notices fails color contrast and uses only color to differentiate between default and hover states.
Screenshot 2024-01-14 at 5 20 46 PM

### Expected behavior

The link should pass color contrast. Remove or change the percentage for the opacity until it passes color contrast.

On hover, the text-decoration should be set to none so the underline goes away and the hover state is indicated by something other than color.

[Additional information on WCAG Use of Color requirements.](https://www.w3.org/WAI/WCAG21/Understanding/use-of-color.html)

### Actual behavior

See the styles defined for .wc-forward:
https://github.com/woocommerce/woocommerce/blob/758df4854d7b627fc26eb5c0860dc492dea6a06e/plugins/woocommerce-blocks/assets/js/base/components/notice-banner/style.scss#L46

The color is set to #2f2f2f and there is an opacity of .6. On a light green background, the color before hover is approximately #878B88. This has a [3.37:1 color contrast ratio](https://webaim.org/resources/contrastchecker/?fcolor=878B88&bcolor=F4FFF7), failing WCAG.

On hover, the opacity changes, but there is no other indicator besides color change that the link is being hovered on.

### Steps to reproduce

Review the code linked above.

### WordPress Environment

N/A

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### LINKED ISSUE #43619: Accessibility: Cart and checkout page labels fail color contrast
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Labels for fields on the cart and checkout page are set to hsla(0,0%,7%,.5) which has a 3.52:1 color contrast ratio, which fails WCAG.
Screenshot 2024-01-14 at 7 13 57 PM

### Expected behavior

All field labels should pass color contrast checks at a [minimum of 4.5:1 (WCAG AA)](https://www.w3.org/WAI/WCAG21/Understanding/contrast-minimum.html) but most ideally at a ratio of [7:1 (WCAG AAA)](https://www.w3.org/WAI/WCAG21/Understanding/contrast-enhanced.html), to ensure that people who have low vision can complete checkout.

### Actual behavior

Field labels are light gray and fail contrast.

Here's where the color on the labels is set to $universal-body-low-emphasis:
https://github.com/woocommerce/woocommerce/blob/758df4854d7b627fc26eb5c0860dc492dea6a06e/plugins/woocommerce-blocks/packages/components/text-input/style.scss#L17C11-L17C38

And where the color is defined:
https://github.com/woocommerce/woocommerce/blob/758df4854d7b627fc26eb5c0860dc492dea6a06e/plugins/woocommerce-blocks/assets/css/abstracts/_colors.scss#L23

### Steps to reproduce

See code linked above.

### WordPress Environment

N/A

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### LINKED ISSUE #43621: Accessibility: Keyboard focus not appropriately managed on the cart page after updating address for shipping rates
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

On the cart page in the Change Address section, the keyboard focus is not managed appropriately.
After updating the country, city, state, and zip, then pressing the update button, the number of rates found is announced by the screen reader (awesome!), but the form is collapsed and keyboard focus stays on the now hidden update button.
 

### Expected behavior

If the form is going to be collapsed, keyboard focus should be shifted to a visible element, such as the found shipping rates. container or first rate.

### Actual behavior

Focus stays on a visually hidden element.

### Steps to reproduce

1. On the cart page, expand the change address form.
2. Fill in the form and then Tab to the update button.
3. Trigger the update button with either the space bar or return/enter key.
4. Observe that there is no longer a visible focus outline on the page.

### WordPress Environment

N/A

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by senadir**
I choose to go with a single PR instead of spamming multiple small PRs that take more time and effort to get setup than to actually fix the code.

This PR fixes the color contrast for the add to cart notice button, the cart/checkout labels, returns focus for the cart shipping calculator, button, and returns focus on whatever element opened the mini cart drawer.

The last one was tricky because we have the logic to return, it just never triggers because we don't unmount our drawer, we just hide it. Switching to removing the element from the page was too much a lift, so I customized the `useFocusReturn` hook to our usage.

I reused that one for the shipping calculator as well, because Gutenberg one didn't work as well.

Closes https://github.com/woocommerce/woocommerce/issues/43619
Closes https://github.com/woocommerce/woocommerce/issues/43615
Closes https://github.com/woocommerce/woocommerce/issues/43561
Closes https://github.com/woocommerce/woocommerce/issues/43621

### Notice color
1. On a product page, add the product to cart.
2. The page will refresh, and a notice will show a button that says 'View cart'.
3. Make sure the button contract is above 4.5, using inspect tools. Note that because opacity is a separate prop, the color will show as contrasting regardless in some browsers, so you might need to change the color to also include the opacity.

### Cart/Checkout labels
1. On Checkout, select the label of an input and ensure its contrast is above 4.5.
2. Switch Checkout to dark mode and ensure its contrast is still above 4.5.

### Return focus on Shipping Calculator
0. If you don't have Shipping Calcualtor enabled, you need to enable the option "Enable the shipping calculator on the cart page" in /wp-admin/admin.php?page=wc-settings&tab=shipping&section=options.
1. In Cart, click "Change Address"
2. Fill out the form and place it.
3. Ensure the Change address button still has focus, this means either an outline around the button, or tabbing forward should take you to the next object in the sidebar, not the top of the page.

### Return focus on Mini Cart
1. Open the mini cart via mini cart button.
2. Click X
3. Ensure the mini cart button is still focused, this means either an outline around the cart button, or tabbing forward should take you to the next object in the navbar/main body, not the top of the page.

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 
Update color contrast for Checkout fields.
Update color contrast for notice buttons.
Return focus when closing mini cart drawer.
Return focus when closing shipping calculator.

#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce-blocks/assets/js/base/utils/use-return-focus.ts [hunk 1]
```diff
@@ -0,0 +1,63 @@
...
+				return;
+			}
+
+			focusedBeforeMount.current = node.ownerDocument.activeElement;
+		} else if ( focusedBeforeMount.current ) {
+			const isFocused = ref.current?.contains(
+				ref.current?.ownerDocument.activeElement
+			);
+
+			if ( ref.current?.isConnected && ! isFocused ) {
```
Comment (nielslange) [inline plugins/woocommerce-blocks/assets/js/base/utils/use-return-focus.ts:40]: If I see this correctly, uncommenting the `return;` is the only difference between this customised version and [Gutenberg's custom hook](https://github.com/WordPress/gutenberg/blob/0a4c5c2f38d801eedd0de2b6e54258e687442777/packages/compose/src/hooks/use-focus-return/index.js#L31-L78), isn't it? 

In the PR description, you mentioned:
> The last one was tricky because we have the logic to return, it just never triggers because we don't unmount our drawer, we just hide it.

Is there something stopping us from unmounting the drawer instead of hiding it so that we can use the custom hook from Gutenberg, before overwriting it?

**Review by nielslange — COMMENTED** [review]
Thanks for working on this, @senadir. I left a question regarding overwriting the Gutenberg custom hook.

Regarding the testing instructions (see note in [this comment](https://github.com/woocommerce/woocommerce/pull/47470#issuecomment-2110357684)), I wonder if we should slightly improve them:

1. **Notice Color**:
   - Currently, it states that _"a notice will show a button to go to cart."_. However, we are using the CSS classes `button wc-forward wp-element-button` on a link element (`<a href="...">`), not a button (`<button>`). We could adjust the instructions to either _"a notice will show a link to go to cart"_ or _"a notice will show a button that says 'View cart'"_ to avoid ambiguity.

2. **Return Focus on the Shipping Calculator**:
   - The instructions mention clicking _"Change address"_, but this requires enabling the option _"Enable the shipping calculator on the cart page"_ in `/wp-admin/admin.php?page=wc-settings&tab=shipping&section=options`. The [high-quality testing instructions guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions) suggests mentioning preconditions, actions, and validation steps. Including this setup step will help prevent confusion about making the "Change address" link visible.

3. **Return Focus on the Shipping Calculator and Return focus on Mini Cart**:
   - The instructions for return focus on the shipping calculator and the mini cart do not mention using a keyboard. However, the related issues #43561 and #43621 explicitly mention keyboard inputs. Should we include keyboard usage in the testing steps?

File: plugins/woocommerce-blocks/assets/js/base/utils/use-return-focus.ts (hunk 1 above)
Comment (senadir) [reply plugins/woocommerce-blocks/assets/js/base/utils/use-return-focus.ts:40]: > Is there something stopping us from unmounting the drawer instead of hiding it so that we can use the custom hook from Gutenberg, before overwriting it?

Yes, the size of the refactor is not worth it and we don't know the risks of doing that. I chatted with @Aljullu around this (given he was the one who introduced this to Mini Cart) and we concluded that we will seek a solution upstream first before rewriting because this used to work fine.

We would also need to rewrite the shipping calculator to make it unmount and return focus.

So the cost of copy pasting a hook is lower than a refactor. Keep also in mind that the Drawer is copy-paste from the Modal component in Gutenberg, with modification.

**Comment by senadir** [comment]
I updated the steps thank you @nielslange

File: plugins/woocommerce-blocks/assets/js/base/utils/use-return-focus.ts (hunk 1 above)
Comment (nielslange) [reply plugins/woocommerce-blocks/assets/js/base/utils/use-return-focus.ts:40]: Thanks for clarifying this, @senadir. In that case, it makes sense to overwrite the custom hook instead of refactor the Mini Cart and the Shipping Calculator on our end.

**Review by nielslange — APPROVED** [review]
Thanks for updating the testing instructions and clarifying my concern around overwriting Gutenberg's custom hook. Let's ⛴️ this improvement, @senadir. 🙌
