### PR TITLE
Fixes WooCommerce knowledge base API returning empty posts

### LINKED ISSUE #39808: WooCommerce knowledge base does not display any posts
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

The WooCommerce knowledge base section in `Marketing > Coupons` does not display any posts.

### Expected behavior

The blog articles that are tagged to `Coupons` should appear here.

### Actual behavior

No articles are displayed.

### Steps to reproduce

1. Install and activate WooCommerce.
2. Navigate to `Marketing > Coupons`.
3. Verify that no posts are displayed in the **WooCommerce knowledge base** section.

image

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): http://localhost:8888
Site address (URL): http://localhost:8888
WC Version: 8.1.0
REST API Version: ✔ 8.1.0
WC Blocks Version: ✔ 10.9.0
Action Scheduler Version: ✔ 3.6.2
Log Directory Writable: ✔
WP Version: 6.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.54 (Debian)
PHP Version: 7.4.33
PHP Post Max Size: 1 GB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.74.0
OpenSSL/1.1.1n

SUHOSIN Installed: –
MySQL Version: 11.0.3-MariaDB-1:11.0.3+maria~ubu2204
Max Upload Size: 1 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.1.0
WC Database Prefix: wp_
Total Database Size: 4.86MB
Database Data Size: 3.16MB
Database Index Size: 1.70MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 2.06MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_posts: Data: 0.05MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 1
page: 7
post: 2
wp_template: 4

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (1) ###

WooCommerce: by Automattic – 8.1.0-dev

### Inactive Plugins (2) ###

Filter Setter: by  –
Hello Dolly: by Matt Mullenweg – 1.7.2

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### WC Pages ###

Shop base: #5 - /?page_id=5
Cart: #6 - /?page_id=6
Checkout: #7 - /?page_id=7
My account: #8 - /?page_id=8
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty-Two
Version: 1.5
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: /var/www/html/wp-content/plugins/woocommerce/packages/woocommerce-blocks/templates/notices/error.php
/var/www/html/wp-content/plugins/woocommerce/packages/woocommerce-blocks/templates/notices/notice.php
/var/www/html/wp-content/plugins/woocommerce/packages/woocommerce-blocks/templates/notices/success.php

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: customize-store
minified-js
new-product-management-experience
product-variation-management
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2023-08-19 14:04:55 +00:00
Options: ✔
Notes: 88
Onboarding: skipped

### Action Scheduler ###

Complete: 7
Oldest: 2023-08-15 08:42:22 +0000
Newest: 2023-08-18 04:41:16 +0000

Failed: 2
Oldest: 2023-03-02 16:24:41 +0000
Newest: 2023-03-28 07:56:09 +0000

Pending: 1
Oldest: 2023-08-19 04:21:13 +0000
Newest: 2023-08-19 04:21:13 +0000

### Status report information ###

Generated at: 2023-08-18 14:28:18 +00:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by ibndawood**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes #39808.

The WooCommerce.com blog posts categories were recently restructured. The `coupons` category was removed and added as a tag in that restructuring. The WooCommerce knowledge base API uses the `coupons` category ID to fetch the posts from this category. In this PR, we'll fetch the posts tagged to `coupons` tag when a request is made to `coupons` term.

### How to test the changes in this Pull Request:

1. On a fresh installation, verify WooCommerce is installed and activated.
3. Navigate to `Marketing > Coupons`.
4. Scroll to the bottom of the page to the `WooCommerce knowledge base` section.
5. Verify no posts are displayed in the section.
6. Checkout this PR.
7. Navigate to `WooCommerce > Status > Tools`.
8. Click on `Clear Transients` to clear all WooCommerce transients.
9. Navigate to `Marketing > Coupons`.
10. Verify the [posts tagged as `coupons` in WooCommerce.com](https://woocommerce.com/posts/tag/coupons/) are displayed in this section.

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [x] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

Fixes WooCommerce knowledge base API returning empty posts.

#### Comment 

</details>

### CODE REVIEW

**Comment by budzanowski** [comment]
`marketing` was returning correct results before this change. Will the behavior for `marketing` also change after this PR?

**Comment by ibndawood** [comment]
Thank you, @budzanowski, for taking the time to review. Yes, the `marketing` behaviour remains the same. If the argument is `marketing`, the API will filter posts from the `marketing` category and the `coupons` tag if the argument is `coupons`. The default is to fetch the `marketing` posts.

By changing the ' category ' param, I've verified the endpoint for `marketing`, `coupons` and without the param as well: `/wc-admin/marketing/knowledge-base&category=coupons&_locale=user`.

**Review by budzanowski — APPROVED** [review]

File: plugins/woocommerce/src/Internal/Admin/Marketing/MarketingSpecs.php [hunk 1]
```diff
@@ -136,34 +136,41 @@ protected function is_marketing_channel_plugin( array $plugin_data ): bool {
...
+				'taxonomy' => 'category',
+				'term_id'  => 1744,
+				'argument' => 'categories',
+			),
+			'coupons'   => array(
+				'taxonomy' => 'post_tag',
+				'term_id'  => 1377,
+				'argument' => 'tags',
+			),
 		);
```
Comment (ecgan) [inline plugins/woocommerce/src/Internal/Admin/Marketing/MarketingSpecs.php:154]: I think we don't need the `taxonomy` field because it is not being used?

**Review by ecgan — APPROVED** [review]
I tested this and it works as expected. Screenshots below for reference.

Marketing page: 

image

Coupons page:

image

Adding a bit more details - the posts are retrieved by making the following API call:

- Marketing: https://woocommerce.com/wp-json/wp/v2/posts?utm_medium=product&categories=1744&page=1&per_page=8&_embed=1
- Coupons: https://woocommerce.com/wp-json/wp/v2/posts?utm_medium=product&tags=1377&page=1&per_page=8&_embed=1

I left one minor comment below, about unused `taxonomy` field.

File: plugins/woocommerce/src/Internal/Admin/Marketing/MarketingSpecs.php (hunk 1 above)
Comment (ibndawood) [reply plugins/woocommerce/src/Internal/Admin/Marketing/MarketingSpecs.php:154]: Thank you, @gan, for taking the time to review this PR. The `taxonomy` field is there for readability purposes because `marketing` and `coupons` are different terms belonging to different taxonomies. Alternatively, we can move it to a comment. What do you think?

**Comment by ibndawood** [comment]
Closing and reopening this PR to run the status checks again.

File: plugins/woocommerce/src/Internal/Admin/Marketing/MarketingSpecs.php (hunk 1 above)
Comment (ecgan) [reply plugins/woocommerce/src/Internal/Admin/Marketing/MarketingSpecs.php:154]: > The `taxonomy` field is there for readability purposes because `marketing` and `coupons` are different terms belonging to different taxonomies.

Is that a standard or common way to do that in WordPress? If it is, then I guess it's fine (and that would be a TIL for me too). 

Otherwise, I'm leaning towards moving it to a comment, because having something like `'taxonomy' => 'post_tag'` made me wonder, e.g. "where is the `'post_tag'` value being shown or used?".

Comment (ecgan) [reply plugins/woocommerce/src/Internal/Admin/Marketing/MarketingSpecs.php:154]: I did a bit more reading and I think now I understand that terms are "items within a taxonomy", and taxonomy here can be either a category or a tag. So I guess it's fine to leave the taxonomy field there, it was just me not familiar with the usage. 😄 

References:

- https://developer.wordpress.org/themes/basics/categories-tags-custom-taxonomies/#terms
- https://developer.wordpress.org/plugins/taxonomies/working-with-custom-taxonomies/

Comment (ibndawood) [reply plugins/woocommerce/src/Internal/Admin/Marketing/MarketingSpecs.php:154]: Thank you, @gan, for your feedback. I'll merge this PR.
