### PR TITLE
Do not disable "Used for variations" checkbox

### LINKED ISSUE #39338: "Variations" disappeared from custom variable product. "Used for variations" checkbox became disabled and unchecked. WC 7.9.0
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

"Variations" disappeared from the custom variable product. "Used for variations" checkbox became disabled and unchecked. This happened after updating WC to the 7.9.0 version

### Expected behavior

Variations should persist for custom variable product.  "Used for variations" checkbox should be enabled.

### Actual behavior

"Variations" disappeared from the custom variable product. "Used for variations" checkbox became disabled and unchecked. This happened after updating WC to the 7.9.0 version

### Steps to reproduce

1. Register custom variable product
2. Go to the custom variable product edit page
3. Check "Variations" and "Attributes" tabs

### WordPress Environment

can't post it due to sensitive data. But all requirements were met and was working ok on the 7.8.2 version before the update

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### LINKED ISSUE #39490: Custom product types: support for variations.
WooCommerce 7.9.0 introduced a change to the "Use with variations" checkbox on the Edit Product page which prevents merchants from being able to create e.g. a Variable Subscription product.

Here's the relevant changes in WooCommerce that caused this:
[WooCommerce PR #38802](https://github.com/woocommerce/woocommerce/pull/38802) Changed the Used for variations checkbox code and adds a new enable_if_variable className
[WooCommerce PR #39106](https://github.com/woocommerce/woocommerce/pull/39106) Causes the Used for variations checkbox to be disabled for variable subscription products

When trying to create a variable subscription product, the "use with variations" checkbox on the attributes page is getting disabled which prevents creating variations for subscriptions:

Image

This was fixed for Subscriptions, we should test on other custom products.

Related report: https://github.com/woocommerce/woocommerce/issues/39338.

### PR DESCRIPTION
**Pull request by mattsherman**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

This PR makes a few changes related to the "Used for variations" checkbox:

* The "Used for variations" checkbox is never disabled. I've reverted the behavior that disabled the checkbox when the product type was not `variable`.
    * This returns the behavior of the checkbox to what it was in WooCommerce 7.8.
    * I have determined that there would not be a way to implement disabling the checkbox without potentially breaking extensions, such as WooCommerce Subscriptions. If we were to add such a feature in the future we would need to be careful to proactively let extensions know that this change would be coming and provide them with a clear way to modify the behavior.
* The `woocommerce_added_attribute` trigger has been restored. This is needed by extensions such as WooCommerce Subscriptions in order to re-show the "Used for variations" checkbox when it is hidden.
* The requesting and generation of the empty attribute form has been moved from when the product edit screen loads to when the "Attributes" tab is shown. This allows for the scenario where the product type is changed from "simple" to something else before clicking the "Attributes" tab. The "Used for variations" checkbox will now be correctly defaulted to checked when on a variable product and unchecked for all other product types. This change will also partially address the lingering issue #39377.

Fixes #39490.
Fixes #39338 (this was closed previously even though it was not fixed)
Fixes #39502 (this was closed previously even though it was not fixed)

### How to test the changes in this Pull Request:

1. Perform general regression testing by creating and editing Simple products, Variable products, etc.
    - The "Used for variations" checkbox should be checked by default for Variable products.
    - The "Used for variations" checkbox should be hidden for all other product types (unless an extension has re-shown it, which is actually what WooCommerce Subscriptions is doing to get it to appear).
3. Install WooCommerce Subscriptions 5.2.0 and create and edit Subscriptions and Variable Subscriptions.
    - WooCommerce Subscriptions 5.2.0 does *not* contain any fixes to handle the issues fixed by this PR, so it is a good test of an extension that was experiencing problems.
    - The "Used for variations" checkbox should be unchecked by default for Variable Subscription products.
    - The "Used for variations" checkbox should be hidden for Subscription products.
    - (In other words, WooCommerce Subscriptions 5.2.0 should work with this fix)
4. Install WooCommerce Subscriptions 5.3.1 and verify that the fixes in that version still work with the fixes in this PR.
    - The "Used for variations" checkbox should be unchecked by default for Variable Subscription products.
    - The "Used for variations" checkbox should be hidden for Subscription products.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Comment 

</details>

### CODE REVIEW

**Comment by AnnaMag** [comment]
> Fixes https://github.com/woocommerce/woocommerce/issues/39338 (this was closed previously even though it was not fixed) 

@mattsherman any related issues were closed in favor of https://github.com/woocommerce/woocommerce/issues/39490 during triage.

File: plugins/woocommerce/includes/class-wc-ajax.php [hunk 1]
```diff
@@ -619,7 +621,13 @@ public static function add_attribute() {
 		$attribute->set_name( sanitize_text_field( wp_unslash( $_POST['taxonomy'] ) ) );
 		/* phpcs:disable WooCommerce.Commenting.CommentHooks.MissingHookComment */
 		$attribute->set_visible( apply_filters( 'woocommerce_attribute_default_visibility', 1 ) );
-		$attribute->set_variation( apply_filters( 'woocommerce_attribute_default_is_variation', 1 ) );
+		$attribute->set_variation(
+			apply_filters(
```
Comment (AnnaMag) [inline plugins/woocommerce/includes/class-wc-ajax.php:625]: Would reverting [to the previous functionality ](https://github.com/woocommerce/woocommerce/pull/38003)be sufficient?

Comment (AnnaMag) [reply plugins/woocommerce/includes/class-wc-ajax.php:625]: This would also fix the test-- setting a simple product as the default could create more edge cases in the future 🤔

**Review by AnnaMag — APPROVED** [review]
Thanks for working on this @mattsherman. 

Tested as described. Approving, pending a fix to the failing test.

File: plugins/woocommerce/includes/class-wc-ajax.php (hunk 1 above)
Comment (mattsherman) [reply plugins/woocommerce/includes/class-wc-ajax.php:625]: @AnnaMag I don't see any failing test. What test are you referring to?

I'd prefer not to revert to the previous functionality, since Jarek has been quite set that this change will help prevent confusion based on his user research.
