### PR TITLE
Prevent "woocommerce_order_status_X' hooks to be called when Order save() action is cancelled

### LINKED ISSUE #46886: WC_Order::$status_transition must be emptied if something prevent save() from happening
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Using `'woocommerce_before_' . $this->object_type . '_object_save'` to prevent saving of an Order does not prevent the  `woocommerce_order_status_X` hooks to be called

### Expected behavior

If we throw an Error that prevents changes, no further status change hook must be called.

### Actual behavior

In one of my devs, I need to prevent some order change status from happening (even the admin is not authorised to do so manualy from the backend) but the existing order admin page still give this availability in several places:
- the status selector 
image
- the buttons in preview view
image

Even if I could remove those button, I still need to prevent those changes on a low level.

Currently, hitting one of those buttons trigger a `WC_Order::set_status()`, filling the `WC_Order::$status_transition` values  and that's fine.

I use the `WC_Abstract_Order::save()` `'woocommerce_before_' . $this->object_type . '_object_save'` action hook to check some conditions and  I throw an Exception that is catched in this same function.

At this point, it cancel the changes (no save) but  `WC_Order::$status_transition` still holds the changes and because `WC_Order::status_transition()` is still called (in `WC_Order::save()`), lot of unexpected hooks get called.

To resume, if I prevent saving a status change by using `'woocommerce_before_' . $this->object_type . '_object_save'`  hook, none of the `woocommerce_order_status_X`hooks should be called.

### Steps to reproduce

```php
add_action(
    hook_name: 'woocommerce_before_order_object_save',
    callback: static function (WC_Order $order) {
        $changes = $order->get_changes();
        if (!empty($changes) && isset($changes['status']) && $changes['status'] === 'refunded') {
            throw new \RuntimeException('to prove my point');
        }
    }
);

add_action(
    hook_name: 'woocommerce_order_status_refunded',
    callback: static function ($id) {
        die('I should have never been called');
    }
);

$order = new Wc_Order();
$order->set_status('draft');
$order->save();
$order->set_status('refunded');
$order->save();
```

### WordPress Environment

WooCommerce version: 		8.8.2
WordPress version: 		6.5.2

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by axi**
### Changes proposed in this Pull Request:

Would close #46886.

### How to test the changes in this Pull Request:
1) Navigate to `/wp-admin/admin.php?page=wc-orders&action=new` and hit "create" button to create an order
2) in `functions.php`, add an action hook to ensure that no order has reach the "refunded" status
```
add_action(
    hook_name: 'woocommerce_order_status_refunded',
    callback: static function ($id) {
        die('If you see this, this fix doesn\'t work :-)');
    }
);
```
3) in functions.php, add an action hook on the `woocommerce_before_order_object_save` to simulate a check that prevent any order to be saved with the "refunded" status
```
add_action(
    hook_name: 'woocommerce_before_order_object_save',
    callback: static function (WC_Order $order) {
        $changes = $order->get_changes();
        if (!empty($changes) && isset($changes['status']) && $changes['status'] === 'refunded') {
            throw new \RuntimeException('to prove my point');
        }
    }
);
```
4) in the backoffice order page, change ist status to "refunded" in the select list and hit the "update" button.
5) page should refresh and still show the previous order status (= NOT refunded)

----

Another way to do actions 1), 4) & 5) would be to use the following code
```
$order = new Wc_Order();
$order->set_status('draft');
$order->save();
$order->set_status('refunded');
$order->save();
```

### CODE REVIEW

**Review by naman03malhotra — COMMENTED** [review]
Hi @axi, thank for submitting this PR. Would it be possible to provide more detailed testing instructions that are easy to understand for a wider audience? This would help ensure that the changes made in the PR are thoroughly tested and can be easily replicated by others.

Please have a look at previous [pull requests](https://github.com/woocommerce/woocommerce/pulls).
https://github.com/woocommerce/woocommerce/pull/46895 is a great example.

**Review by naman03malhotra — COMMENTED** [review]
Forgot to mention, please add a changelog as well.

**Comment by axi** [comment]
> Forgot to mention, please add a changelog as well.

done

**Comment by axi** [comment]
> Hi @axi, thank for submitting this PR. Would it be possible to provide more detailed testing instructions that are easy to understand for a wider audience? This would help ensure that the changes made in the PR are thoroughly tested and can be easily replicated by others.
> 
> Please have a look at previous [pull requests](https://github.com/woocommerce/woocommerce/pulls). #46895 is a great example.

It should be better now, I updated the PR

**Review by naman03malhotra — COMMENTED** [review]
Hey @axi, thank you for your contribution. As I was reviewing your PR, I was trying to understand the actual product usecase you are trying to achieve here, if you can share some light there.

Also, some of the automated checks are failing, can you please take a look into those. Thanks!

**Comment by axi** [comment]
@naman03malhotra 
In my usecase, I want to prevent some admin users to change some order status if some conditions aren't met. For example, in my case, I subdivide some orders and the parent one must not be update manualy by the admin, only automaticaly when some conditions are met.
Before the fix, if the save() was effectively prevented when throwing an Exception, `$this->status_transition()` was still called an execute a whole bunch of unwanted hooks.
#46886 also partially describe my usecase

**Comment by axi** [comment]
Is there something I can do about the 3 failing jobs ?
- Inform Beta Download webhook
- Send workflow dispatch
- Publish reports
?

**Comment by axi** [comment]
Any news on this PR ? I still think it's a bug that could probably be fixed while releasing 9.0

**Comment by axi** [comment]
Hi @vedanshujain, @naman03malhotra 
Can we go ahead with this PR ? Please tell me if I can do something to help.

**Comment by vedanshujain** [comment]
Hey @axi , we have not been able to get to this because these changes to core flows needs more caution then other updates. Note that we will also need unit tests here.

Going through the PR, I am not confident about the coupling of `status_transition` property in the Abstract order class. It's property of a child class and shouldn't be accessed (even behind defensive checks) there. Should we instead modify the `status_transition` method to verify that status transitioning actually happened (i.e. the `to` status is current status) before firing the hooks?

**Comment by axi** [comment]
@vedanshujain Thanks for the feedback and yes, your idea is much better.
I pushed an update, let me know what you think.

**Comment by axi** [comment]
Sorry for the missing dot that broke the  Build Live Branch CI job

**Comment by axi** [comment]
Hi, can someone have a look at this PR after I did the suggested modifications ?

File: plugins/woocommerce/includes/class-wc-order.php [hunk 1]
```diff
@@ -391,6 +391,11 @@ protected function status_transition() {
 		$this->status_transition = false;
 
 		if ( $status_transition ) {
+			// Verify planned status transition did happen, in case save() wasn't successful.
+			if ( $status_transition['to'] !== $this->data['status'] ) {
```
Comment (vedanshujain) [inline plugins/woocommerce/includes/class-wc-order.php]: let's use get_changes instead, generally, we don't access the data array directly outside of getters/setters.
```suggestion
			$changes = $this->get_changes();
			if ( isset( $changes['status'] ) && $changes['status'] === $status_transition['to'] ) {
```

**Review by vedanshujain — COMMENTED** [review]
Requesting some minor changes, but otherwise looks good. Thanks for adding the unit test and detailed test instructions ❤️

File: plugins/woocommerce/includes/class-wc-order.php (hunk 1 above)
Comment (axi) [reply plugins/woocommerce/includes/class-wc-order.php]: Here, `$this->get_changes()['status']` has the "changed value" ("refunded" in our exemple) but `$this->data['status']` still holds the database persisted value ("pending" in our exemple).
image
We want to check the `$status_transition['to']` value against the current persisted value `$this->data['status']` and therefore cannot use the `get_changes()` method.

Comment (axi) [reply plugins/woocommerce/includes/class-wc-order.php]: We could maybe  use `$this->get_base_data()` if we prefer to use a getter ?

Comment (axi) [reply plugins/woocommerce/includes/class-wc-order.php:395]: Here, `$this->get_changes()['status']` has the "changed value" ("refunded" in our exemple) but `$this->data['status']` still holds the database persisted value ("pending" in our exemple).
image
We want to check the `$status_transition['to']` value against the current persisted value `$this->data['status']` and therefore cannot use the `get_changes()` method.

We could maybe  use `$this->get_base_data()` if we prefer to use a getter ?

Comment (axi) [reply plugins/woocommerce/includes/class-wc-order.php]: @vedanshujain can you have a look at my comments above ?

**Comment by axi** [comment]
Hi, Is there something blocking this PR ?

**Comment by vedanshujain** [comment]
(re-assigning so that it says in queue)

**Comment by axi** [comment]
that must be a very long queue :-)
I get that improvements can take long to review, but bugs with proposed resolutions could probably be merged in less than a year, couldn't they ?

**Review by naman03malhotra — COMMENTED** [review]
Thank you for the proposed change. While I see the potential benefits in reducing unnecessary processing when the status doesn't change and the change itself seems logical to an extent, I have some concerns regarding the potential side effects on custom extensions and 3PD plugins that may rely on the status_transition hook.

In some cases, custom extensions or plugins may listen to the status_transition event to perform actions, even if the status hasn't actually changed. By returning early when the status remains the same, this change could prevent those extensions from running their logic, which may result in missed functionality.

We would need to find a way to introduce this change that is backward compatible with the current behavior, especially when this is touching the core functionality.

Requesting another set of eyes from @jorgeatorres on this for his thoughts on this.

**Comment by axi** [comment]
@naman03malhotra thanks for that comment, it makes sense.

One could argue that action name ```'woocommerce_order_status_CHANGED``` (past tense) in class-wc-order.php:l452
```php
do_action( 'woocommerce_order_status_changed', $this->get_id(), $status_transition['from'], $status_transition['to'], $this );
```
and wording ```'Order status CHANGED from %1$s to %2$s.'``` (past tense) in  class-wc-order.php:l446
```php
$transition_note = sprintf( __( 'Order status changed from %1$s to %2$s.', 'woocommerce' ), wc_get_order_status_name( $status_transition['from'] ), wc_get_order_status_name( $status_transition['to'] ) );
```
imply that the action DID succeed. From that, we could also say that existing custom implementations did assume that the status change was aleady validated at this point (as I was thinking) and that it was a bug.

Anyway, I guess it's  tricky to count on how wordings are understood to change an implementation...

Does something like a ```'woocommerce_order_status_will_change'``` hook that would be call before the current hook ```'woocommerce_order_status_' . $status_transition['to']``` could be a better idea ?

**Comment by axi** [comment]
Happy birthday to you "Pull request",
Happy birthday to you "Pull request",
Happy birthday to you "Pull requestttttttttttt" (slow down slightly)
Happy birthday to you 🎉

**Comment by kalessil** [comment]
Hey @axi, and thank you for your patience :wave:

The technical side of this change is straightforward: prevent specific order status transitions. However, the current implementation has some backward compatibility implications (`woocommerce_before_order_object_save` hook [intention](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/includes/abstracts/abstract-wc-order.php#L214) is not aligned with what we are trying to address here, and more potential issues with third-party extensions and customizations).

Can we step back and understand the use case here (IDK, preventing specific status or group of transitions, and why) from the WooCommerce features Point of View?

**Comment by axi** [comment]
@kalessil thanks for the review.
This post was describing my usecase: https://github.com/woocommerce/woocommerce/pull/46887#issuecomment-2093460541.
There's also a bit more technical details on how I found/qualify the bug in the #46886 issue itself

**Comment by axi** [comment]
I'm curious, can you think about a use case where for any reason (let's say database query timeout), the saving to database did not succeed in ```save()``` but you still would want the ```"woocommerce_order_status_changed"``` hook to be triggered ? Because that's what's happening right now.

**Comment by axi** [comment]
I suggested
> Does something like a 'woocommerce_order_status_will_change' hook that would be call before the current hook 'woocommerce_order_status_' . $status_transition['to'] could be a better idea ?

this would help fixing my usecase as I could check for the real success of the save() in it and act accordingly but it sounds like a hack

**Comment by kalessil** [comment]
> this post was describing my usecase: https://github.com/woocommerce/woocommerce/pull/46887#issuecomment-2093460541.

Thanks! Now things are getting clearer to me, I'll share some proposals below in this comment.

> I'm curious, can you think about a use case where for any reason (let's say database query timeout), the saving to database did not succeed in save() but you still would want the "woocommerce_order_status_changed" hook to be triggered ? Because that's what's happening right now.

It's not perfect IMO, but adding some resilience (and logging) to the core itself, if any customizations cause issues, core flows somewhat work, leaving clues for troubleshooting. So I'd let it be as it is.

> this would help fixing my usecase as I could check for the real success of the save() in it and act accordingly but it sounds like a hack

It's not a fit for our use case, which is, in a nutshell, missing admin customization support in two places:
- bulk editing orders ([pointer](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/src/Internal/Admin/Orders/ListTable.php#L318)): it could use a hook allowing to exclude some statuses from the bulk operations
- order editing ([pointer](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/includes/admin/meta-boxes/class-wc-meta-box-order-data.php#L326)):  it could use a hook allowing to exclude some statuses from the status dropdown.

This looks like a solid path forward IMO. What do you think about this proposal @axi ?

**Comment by axi** [comment]
@kalessil 
I still think it's a bug and it should be taking care of at a low level.

I understand the potential BC of my PR if custom implementations relies on  ```'woocommerce_order_status_' . $status_transition['to']``` or ```'woocommerce_order_status_' . $status_transition['from'] . '_to_' . $status_transition['to']``` to trigger actions that don't rely on the success of the save() but I don't see why those potential implementations would want to execute those actions if something bad happened before.

Exemple:
- set order status to   "completed"
- database said nop (timeout or anything)
- let's execute following hooks anyway: send emails, decrement stock

Having a look at current hooks implementation within core (and booking module for example), they all looks like taking the "it's been saved" as granted.

Regarding proposals, yes that would help/solve my case, but if feels like solving the problem from a high level. If I was using the API instead of admin, problem would be the same.

What about a 
```php
// Verify planned status transition did happen, in case save() wasn't successful.
if (apply_filters( 'woocommerce_strict_order_transition_mode', false)
      && $status_transition['to'] !== $this->data['status']
) {
     return;
}
```
that would let people decide the strictness ?

**Comment by kalessil** [comment]
> I still think it's a bug and it should be taking care of at a low level.
> Having a look at current hooks implementation within core (and booking module for example), they all looks like taking the "it's been saved" as granted.

It's optimistic and is tied to the `\WC_Abstract_Order::save` implementation.

The biggest blocker I see is that we have at least four failure points there:
- `do_action( 'woocommerce_before_' . $this->object_type . '_object_save', $this, $this->data_store );`
- `$this->data_store->update( $this );` / `$this->data_store->create( $this )`
- `$this->save_items();`
- `do_action( 'woocommerce_after_' . $this->object_type . '_object_save', $this, $this->data_store );`

If I refine slightly the fix implementation, I still have concerns about `$this->save_items()` - if it fails, the transition will still be triggered, and it's still not right:

```patch
Subject: [PATCH] Orders: do not trigger order state transition if state was not persisted.
---
Index: plugins/woocommerce/includes/abstracts/abstract-wc-order.php
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/plugins/woocommerce/includes/abstracts/abstract-wc-order.php b/plugins/woocommerce/includes/abstracts/abstract-wc-order.php
--- a/plugins/woocommerce/includes/abstracts/abstract-wc-order.php	(revision 6c30f2a631891df50b63fd9235c89ea320b5c022)
+++ b/plugins/woocommerce/includes/abstracts/abstract-wc-order.php	(date 1746172919859)
@@ -74,7 +74,7 @@
 	 * Order items will be stored here, sometimes before they persist in the DB.
 	 *
 	 * @since 3.0.0
-	 * @var array
+	 * @var array<string,array>
 	 */
 	protected $items = array();
 
Index: plugins/woocommerce/includes/class-wc-order.php
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/plugins/woocommerce/includes/class-wc-order.php b/plugins/woocommerce/includes/class-wc-order.php
--- a/plugins/woocommerce/includes/class-wc-order.php	(revision 6c30f2a631891df50b63fd9235c89ea320b5c022)
+++ b/plugins/woocommerce/includes/class-wc-order.php	(date 1746173015118)
@@ -414,11 +414,12 @@
 	 */
 	protected function status_transition() {
 		$status_transition = $this->status_transition;
+		$order_persisted   = array() === $this->changes;
 
 		// Reset status transition variable.
 		$this->status_transition = false;
 
-		if ( $status_transition ) {
+		if ( $status_transition && $order_persisted ) {
 			try {
 				/**
 				 * Fires when order status is changed.

```

For clarity, generalizing the fix to "trigger state transition if order is fully persisted (incl. [line items](\WC_Abstract_Order::save_items))" would work to get this PR moving.

EDIT: `$order_persisted` calculation would need to be expanded to cover line items (I assume `array() === $item->get_changes()` should be possible).

> Regarding proposals, yes that would help/solve my case, but if feels like solving the problem from a high level. If I was using the API instead of admin, problem would be the same.

Yep, I intended to focus on the single use case by stepping back and not going sideways — one thing at a time.
But anyway, I guess this is not the direction you are interested in. Do I understand correctly?

File: plugins/woocommerce/includes/class-wc-order.php [hunk 2]
```diff
@@ -415,15 +415,18 @@ public function update_status( $new_status, $note = '', $manual = false ) {
...
 		// Reset status transition variable.
 		$this->status_transition = false;
 
-		if ( $status_transition ) {
-			// Verify planned status transition did happen, in case save() wasn't successful.
-			if ( $status_transition['to'] !== $this->data['status'] ) {
-				return;
-			}
-
+		if ( $status_transition && $order_persisted && $order_items_persisted ) {
```
Comment (axi) [inline plugins/woocommerce/includes/class-wc-order.php:430]: Test `test_status_transition_hooks_shouldnot_be_called_when_order_save_errored_on_item_save` fails if we remove the  `$order_items_persisted === true` check.

Existing test `test_status_transition_hooks_shouldnot_be_called_when_order_save_canceled` still fails if we remove the  `$order_persisted === true` check.

**Comment by axi** [comment]
Hi @kalessil, thanks for finding another way, it is fine with me.
I updated the PR and added a test.

Let me know what you think

File: plugins/woocommerce/includes/class-wc-order.php [hunk 3]
```diff
@@ -415,10 +415,18 @@ public function update_status( $new_status, $note = '', $manual = false ) {
 	protected function status_transition() {
 		$status_transition = $this->status_transition;
 
+		$order_persisted       = array() === $this->changes;
+		$order_items_persisted = array() === array_filter(
```
Comment (kalessil) [inline plugins/woocommerce/includes/class-wc-order.php]: Nice! I think we need to cover an additional case here: `array() === $this->items_to_delete && array() === array_filter(`

File: plugins/woocommerce/includes/class-wc-order.php (hunk 2 above)
Comment (kalessil) [reply plugins/woocommerce/includes/class-wc-order.php:430]: I'll review tests as well, but here some pointers how to fix it:

```patch
Subject: [PATCH] Orders: fix for failing tests.
---
Index: plugins/woocommerce/tests/php/includes/abstracts/class-wc-abstract-order-test.php
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/plugins/woocommerce/tests/php/includes/abstracts/class-wc-abstract-order-test.php b/plugins/woocommerce/tests/php/includes/abstracts/class-wc-abstract-order-test.php
--- a/plugins/woocommerce/tests/php/includes/abstracts/class-wc-abstract-order-test.php	(revision a328628ff30b67f5fc00ef2c4538fa6e7bd8d97b)
+++ b/plugins/woocommerce/tests/php/includes/abstracts/class-wc-abstract-order-test.php	(date 1746448445021)
@@ -624,20 +624,22 @@
 		$order->add_item($order_item);
 		$order->save();
 
+		$order_item_id = $order_item->get_id();
+
 		// add an action that will simulate an error while saving WC_Order_Item.
 		$callback = static function ( WC_Order_Item $item ) {
 			throw new \RuntimeException( 'Error while saving WC_Order_Item' );
 		};
 		add_action( 'woocommerce_before_order_item_object_save', $callback );
 
-		$order->get_items()[1]->set_name('CHANGED Order Item name');
+		$order->get_items()[$order_item_id]->set_name('CHANGED Order Item name');
 		$order->set_status( $refunded_status );
 		$order->save();
 
 		// Make sure status update has not been saved to database
 		// and our RuntimeException('Error while saving WC_Order_Item') worked.
 		$this->assertEquals(
-			$order->get_items()[1]->get_data()['name'],
+			$order->get_items()[$order_item_id]->get_data()['name'],
 			$initial_order_item_name,
 			'Modified order item name has been saved to database but shouldn\'t have been'
 		);

```

File: plugins/woocommerce/tests/php/includes/abstracts/class-wc-abstract-order-test.php [hunk 4]
```diff
@@ -552,4 +552,102 @@ private function add_product_with_cogs_to_order( WC_Order $order, float $cogs_va
...
+	 */
+	public function test_status_transition_hooks_shouldnot_be_called_when_order_save_canceled() {
+		$initial_status  = OrderStatus::AUTO_DRAFT;
+		$refunded_status = OrderStatus::REFUNDED;
+
+		// add an action that will cancel the save in case the new status is "refunded".
+		$callback = static function ( WC_Order $order ) use ( $refunded_status ) {
+			$changes = $order->get_changes();
+			if ( ! empty( $changes ) && isset( $changes['status'] ) && $changes['status'] === $refunded_status ) {
+				throw new \RuntimeException( 'to prove my point' );
```
Comment (kalessil) [inline plugins/woocommerce/tests/php/includes/abstracts/class-wc-abstract-order-test.php]: Message suggestion: `Interrupt order persistence.`

File: plugins/woocommerce/tests/php/includes/abstracts/class-wc-abstract-order-test.php [hunk 5]
```diff
@@ -552,4 +552,102 @@ private function add_product_with_cogs_to_order( WC_Order $order, float $cogs_va
...
+		$order->save();
+
+		$order->set_status( $refunded_status );
+		$order->save();
+
+		// Make sure status update has not been saved to database and our RuntimeException('to prove my point') worked.
+		$this->assertEquals(
+			$order->get_data()['status'],
+			$initial_status,
+			'Status ' . $refunded_status . ' has been saved to database'
```
Comment (kalessil) [inline plugins/woocommerce/tests/php/includes/abstracts/class-wc-abstract-order-test.php]: In the new test cases, let's skip the failed assertion messages in favour of comments explaining what we assert.
If it starts to fail, we have to investigate the test case anyway.

File: plugins/woocommerce/tests/php/includes/abstracts/class-wc-abstract-order-test.php [hunk 6]
```diff
@@ -552,4 +552,102 @@ private function add_product_with_cogs_to_order( WC_Order $order, float $cogs_va
...
+
+		$order = new Wc_Order();
+		$order->set_status( $initial_status );
+		$order->save();
+
+		$order->set_status( $refunded_status );
+		$order->save();
+
+		// Make sure status update has not been saved to database and our RuntimeException('to prove my point') worked.
+		$this->assertEquals(
```
Comment (kalessil) [inline plugins/woocommerce/tests/php/includes/abstracts/class-wc-abstract-order-test.php]: For the new test cases, let's use stricter `assertSame` - we're tightening types' strictness gradually.

**Review by kalessil — COMMENTED** [review]
@axi: I think we are on the right track.

Leaving some comments + it looks like we have code style violations in tests.

File: plugins/woocommerce/tests/php/includes/abstracts/class-wc-abstract-order-test.php (hunk 5 above)
Comment (axi) [reply plugins/woocommerce/tests/php/includes/abstracts/class-wc-abstract-order-test.php]: Modified wording to "'Order status in database has been modified but but shouldn't have been'"

**Comment by axi** [comment]
Thanks for the review, I applied all your suggestions.

File: plugins/woocommerce/tests/php/includes/abstracts/class-wc-abstract-order-test.php [hunk 7]
```diff
@@ -552,4 +552,105 @@ private function add_product_with_cogs_to_order( WC_Order $order, float $cogs_va
...
+		$order->save();
+
+		// Make sure status update has not been saved to database
+		// and our RuntimeException('Interrupt order persistence.') worked.
+		$this->assertSame(
+			$order->get_data()['status'],
+			$initial_status,
+			'Order status in database has been modified but but shouldn\'t have been'
+		);
+		$this->assertSame(
```
Comment (kalessil) [inline plugins/woocommerce/tests/php/includes/abstracts/class-wc-abstract-order-test.php]: Hint: `assertFalse`

File: plugins/woocommerce/tests/php/includes/abstracts/class-wc-abstract-order-test.php [hunk 8]
```diff
@@ -552,4 +552,105 @@ private function add_product_with_cogs_to_order( WC_Order $order, float $cogs_va
...
+		$order->save();
+
+		// Make sure status update has not been saved to database
+		// and our RuntimeException('Error while saving WC_Order_Item') worked.
+		$this->assertSame(
+			$order->get_items()[ $order_item_id ]->get_data()['name'],
+			$initial_order_item_name,
+			'Modified order item name has been saved to database but shouldn\'t have been'
+		);
+		$this->assertSame(
```
Comment (kalessil) [inline plugins/woocommerce/tests/php/includes/abstracts/class-wc-abstract-order-test.php]: Hint: `assertFalse`

**Review by kalessil — COMMENTED** [review]
Looks good!

Let's address the [code style violations](https://github.com/woocommerce/woocommerce/actions/runs/14880758913/job/41788155679?pr=46887), two minor comments from me, and wrap up the PR.

**Review by kalessil — APPROVED** [review]
LGTM, great work @axi !

CI is green + tested manually potentially affected areas:
- order placement as a buyer :heavy_check_mark: 
- order placement from the admin area :heavy_check_mark: 
- bulk orders status change :heavy_check_mark: 
- order-level status change :heavy_check_mark:

**Comment by axi** [comment]
@kalessil thanks for the guidance on this PR
