### PR TITLE
fix/37604: replace title html attribute with aria-label

### LINKED ISSUE #37604: Accessibility Improvements ‣ Product Page ‣ Quantity Input
As originally reported [over here](https://github.com/woocommerce/woocommerce/issues/24185#issuecomment-873422417), the single product page quantity selector has a `title` attribute which we may wish to replace or remove.

<div align="center">quantity-title-attr</div>

Notes:

- This sometimes gets in the way on hover (and can only be used on hover, so it requires a mouse).
- The title attribute sometimes is and sometimes is not read by screen readers.  
- On zoom, all text becomes really large, except for the tooltip on the title attribute. 

See the W3C HTML 5 recommendations here: https://html.spec.whatwg.org/multipage/dom.html#the-title-attribute.

### PR DESCRIPTION
**Pull request by Sidsector9**
### Submission Review Guidelines:

- I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
- I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
- I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/). 
- Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

As per the recommendation, this PR removes the `title` attribute in favour of the `aria-label` attribute.

Closes #37604.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Install the Screen Reader Chrome extension
2. Go to a single product page
3. Tab until the quantity field is in focus
4. Listen to the screen reader read out "Product Quantity"

### CODE REVIEW

File: plugins/woocommerce/templates/global/quantity-input.php [hunk 1]
```diff
@@ -41,7 +41,7 @@
 		class="<?php echo esc_attr( join( ' ', (array) $classes ) ); ?>"
```
Comment (louwie17) [inline plugins/woocommerce/templates/global/quantity-input.php:41]: Line 15 contains a `version` given we updated the template we should also update the template version number.
Could you change it to `@version 7.8.0` as this would get released in 7.8 when merged?

File: plugins/woocommerce/templates/global/quantity-input.php [hunk 2]
```diff
@@ -41,7 +41,7 @@
...
 		name="<?php echo esc_attr( $input_name ); ?>"
 		value="<?php echo esc_attr( $input_value ); ?>"
-		title="<?php echo esc_attr_x( 'Qty', 'Product quantity input tooltip', 'woocommerce' ); ?>"
+		aria-label="<?php echo esc_attr_e( 'Product quantity', 'woocommerce' ); ?>"
```
Comment (louwie17) [inline plugins/woocommerce/templates/global/quantity-input.php]: Thanks for renaming this as well, `Product quantity` make a lot more sense.

**Review by louwie17 — DISMISSED** [review]
This tested well, thanks for working on this 🎉 
I just left one suggested change to update the template version, this should also help pass one of the required Github actions.

File: plugins/woocommerce/templates/global/quantity-input.php (hunk 1 above)
Comment (Sidsector9) [reply plugins/woocommerce/templates/global/quantity-input.php:41]: @louwie17 I updated the version number in b1a87d0c162c6008b485928d6a89ae41adbe968c

File: plugins/woocommerce/templates/global/quantity-input.php (hunk 2 above)
Comment (jorgeatorres) [inline plugins/woocommerce/templates/global/quantity-input.php]: `esc_atrr_e()` already outputs the string, so we don't need the `echo` before. We can either drop the `echo` or use `esc_attr__()` instead.

**Review by jorgeatorres — CHANGES_REQUESTED** [review]
Hey @Sidsector9!

Thanks for your contribution 💯. This works great.
I left a tiny tiny observation and that would be all from my side.

Please let me know what you think.

**Review by jorgeatorres — APPROVED** [review]
LGTM. Thank you @Sidsector9!
