### PR TITLE
Fix Payments tab tracking

### LINKED ISSUE #28603: Tracks: wcadmin_settings_change not working on the Payments tab
@pmcpinto commented on [Mon Dec 14 2020](https://github.com/woocommerce/woocommerce-admin/issues/5875)

**Describe the bug**
The `wcadmin_settings_change` is not being triggered when you make an update on the Payments tab (Settings)

**To Reproduce**

1. Go to Settings > Payments (make sure that you have event tracking enabled)
2. Toggle one or more payments options
3. Save changes
4. See that `wcadmin_settings_change` wasn't triggered in the network tab. 

**Expected behavior**
Trigger `wcadmin_settings_change` when the user saves any change in the Payments tab. The `tab` prop should have the `checkout` value

---

@pmcpinto commented on [Mon Dec 14 2020](https://github.com/woocommerce/woocommerce-admin/issues/5875#issuecomment-744630693)

@timmyc I suppose that this needs to be implemented in WC Core, so I'm wondering if we still have time to include a fix for 4.9. Assuming that the fix is straightforward. If not let's target 5.0

---

@timmyc commented on [Tue Dec 15 2020](https://github.com/woocommerce/woocommerce-admin/issues/5875#issuecomment-745629908)

Confirmed this is not working on a ecom plan site. I tried toggling COD payment type, and also adjusting values of the COD payment type description and did not see the tracks event record at all. Worth mentioning this is a server side track, so nothing will be shown in the network tab. Rather I was using the tracks viewer for my wpcom user account to test.

Associated logic for this particular track [lives here](https://github.com/woocommerce/woocommerce/blob/085b4b53fae187b0669714bc9da4e3084ba318d8/includes/tracks/events/class-wc-settings-tracking.php#L102) so we should probably move the issue to the woo core repo.

### PR DESCRIPTION
**Pull request by octaedro**
### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes #28603.

This PR adds the code necessary to track the Payments tab.
To save the Payments settings we [do the action `woocommerce_update_options_payment_gateways_[gateway_id]`](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/includes/admin/settings/class-wc-settings-payment-gateways.php#L230) that triggers [the method `process_admin_options`](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/includes/abstracts/abstract-wc-settings-api.php#L204-L220). That method is being hooked in every payment gateway (e.g. [here](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/includes/gateways/cheque/class-wc-gateway-cheque.php#L44)).
Because we are saving the Payments settings in this way is why the [Tracks event `wcadmin_settings_change`](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/includes/tracks/events/class-wc-settings-tracking.php#L102) isn't being triggered.
The changes in this PR allow us to trigger the mentioned Tracks event after the Payments settings are updated.

### How to test the changes in this Pull Request:

0. Check out this branch.
1. The easiest way to test this PR is using the [WooCommerce Admin Test Helper](https://github.com/woocommerce/woocommerce-admin-test-helper). Install and activate it. Be sure that [this PR](https://github.com/woocommerce/woocommerce-admin-test-helper/pull/25) has been merged, otherwise, you should set up the project and check out the branch `fix/8199`. 
2. Go to `WooCommerce` -> `Status` -> `Logs` (URL `wp-admin/admin.php?page=wc-status&tab=logs`).
3. Select a `tracks-*` log from the dropdown.
4. Go to `WooCommerce` -> `Settings` -> `Payments` (URL `/wp-admin/admin.php?page=wc-settings&tab=checkout`) and toggle the different Payment options.

screenshot-woocommerce local-2022 02 04-15_13_34

Under the Log tab (mentioned on step 2), you should see:
```
DEBUG wcadmin_settings_change
DEBUG   - settings: woocommerce_[option]_settings
DEBUG   - tab: checkout
```

5. Verify that the other settings options (not related to the Payments tab) are working correctly.

Please notice that the `Save changes` button is not being tracked, since the payment methods toggle is saving and tracking every event individually.

screenshot-woocommerce local-2022 02 04-15_13_34-2

Actually, I wonder if it might be worth removing completely in a follow-up PR.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

Fix Payments tab tracking.

### FOR PR REVIEWER ONLY:

* [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

File: plugins/woocommerce/includes/tracks/events/class-wc-settings-tracking.php [hunk 1]
```diff
@@ -98,6 +99,9 @@ public function send_settings_change_event() {
 		if ( isset( $current_tab ) ) {
 			$properties['tab'] = $current_tab;
 		}
+		if ( isset( $current_section ) ) {
```
Comment (joshuatf) [inline plugins/woocommerce/includes/tracks/events/class-wc-settings-tracking.php:101]: Nice 👍

File: plugins/woocommerce/includes/gateways/bacs/class-wc-gateway-bacs.php [hunk 2]
```diff
@@ -64,6 +64,7 @@ public function __construct() {
 		);
 
 		// Actions.
+		add_action( 'woocommerce_update_options_payment_gateways_' . $this->id, array( $this, 'add_admin_options_tracking' ) );
```
Comment (joshuatf) [inline plugins/woocommerce/includes/gateways/bacs/class-wc-gateway-bacs.php]: This will require us to add this action in every gateway which is prone to error and won't track third party gateways.

Since the ajax request calls `update_option()` ( https://github.com/woocommerce/woocommerce/blob/f3927c786a62b8bd5ca7ba7c4ef05f2ebdf0b787/plugins/woocommerce/includes/class-wc-ajax.php#L3095-L3099 ), maybe we could just plug in to the option update hook and check if the value has changed.

There's even some precedent for this and we may be able to add this as an allowed settings in this class - https://github.com/woocommerce/woocommerce/blob/f3927c786a62b8bd5ca7ba7c4ef05f2ebdf0b787/plugins/woocommerce/includes/tracks/events/class-wc-settings-tracking.php#L57-L82

File: plugins/woocommerce/includes/class-wc-ajax.php [hunk 3]
```diff
@@ -3099,6 +3100,7 @@ public static function toggle_gateway_enabled() {
 					$gateway->update_option( 'enabled', 'no' );
 				}
 
+				do_action( 'woocommerce_update_options' );
```
Comment (joshuatf) [inline plugins/woocommerce/includes/class-wc-ajax.php:3115]: If we go with my other recommendation, we can probably remove the 2 additions in this file.  If not, we may want to pass additional data to this action to make it more useful to consumers.

**Review by joshuatf — COMMENTED** [review]
Very nice sleuthing, @octaedro!  I added a suggestion that might make this an easier implementation and work across all payment gateways.  Let me know what you think or if you have any questions!

File: plugins/woocommerce/includes/gateways/bacs/class-wc-gateway-bacs.php (hunk 2 above)
Comment (octaedro) [reply plugins/woocommerce/includes/gateways/bacs/class-wc-gateway-bacs.php]: Nice catch @joshuatf! I added commit ca88734 to fix the issue you mentioned here. The solution I found was a little different from what you suggested but I think it will work well.

File: plugins/woocommerce/includes/tracks/events/class-wc-settings-tracking.php [hunk 4]
```diff
@@ -32,6 +32,7 @@ class WC_Settings_Tracking {
 	public function init() {
 		add_action( 'woocommerce_settings_page_init', array( $this, 'track_settings_page_view' ) );
 		add_action( 'woocommerce_update_option', array( $this, 'add_option_to_list' ) );
+		add_action( 'woocommerce_update_options_payment_gateways', array( $this, 'add_option_to_list' ) );
```
Comment (joshuatf) [inline plugins/woocommerce/includes/tracks/events/class-wc-settings-tracking.php]: I think this may be a bit of a code smell.  This class should not contain implementation details on payment gateways.

Instead, we might try to hook into the actions that currently exist here.

File: plugins/woocommerce/includes/class-wc-ajax.php [hunk 5]
```diff
@@ -3086,6 +3086,7 @@ public static function toggle_gateway_enabled() {
 					continue;
 				}
 				$enabled = $gateway->get_option( 'enabled', 'no' );
+				$gateway->add_admin_options_tracking();
```
Comment (joshuatf) [inline plugins/woocommerce/includes/class-wc-ajax.php]: I think we can remove this call and let the settings tracks API deal with this one.

File: plugins/woocommerce/includes/class-wc-ajax.php (hunk 3 above)
Comment (joshuatf) [reply plugins/woocommerce/includes/class-wc-ajax.php:3115]: Scratch my previous comment and leave this one.

File: plugins/woocommerce/includes/class-wc-ajax.php [hunk 6]
```diff
@@ -3099,6 +3100,7 @@ public static function toggle_gateway_enabled() {
 					$gateway->update_option( 'enabled', 'no' );
```
Comment (joshuatf) [inline plugins/woocommerce/includes/class-wc-ajax.php:3112]: Instead of introducting payment logic in the settings API, we can inform it that a setting has changed:

```
$option = array(
	'id' => 'woocommerce_' . $gateway->id . '_settings'
);
do_action( 'woocommerce_update_option', $option );
```

The `do_action` will need to occur in both the enabled and disabled conditions.

**Review by joshuatf — COMMENTED** [review]
Left a couple more comments.  I'm assuming we only want to trigger tracks on toggle, but if we wanted to track all option changes, we might consider moving the logic into `update_option`.

That would have quite a large impact (and I don't think we're attempting to do that here), but if that were the case, we might scope this just to `update_option` of payment gateways.

File: plugins/woocommerce/includes/abstracts/abstract-wc-settings-api.php [hunk 7]
```diff
@@ -215,10 +215,18 @@ public function process_admin_options() {
 				}
 			}
 		}
+		$this->add_admin_options_tracking();
```
Comment (joshuatf) [inline plugins/woocommerce/includes/abstracts/abstract-wc-settings-api.php]: This one can be removed as well.

File: plugins/woocommerce/includes/class-wc-ajax.php [hunk 8]
```diff
@@ -3075,6 +3075,11 @@ public static function shipping_classes_save_changes() {
 	 */
 	public static function toggle_gateway_enabled() {
 		if ( current_user_can( 'manage_woocommerce' ) && check_ajax_referer( 'woocommerce-toggle-payment-gateway-enabled', 'security' ) && isset( $_POST['gateway_id'] ) ) {
+			global $current_tab;
+
+			// Set current tab.
+			$current_tab = 'checkout';
```
Comment (joshuatf) [inline plugins/woocommerce/includes/class-wc-ajax.php]: Minor, but could we check this from `$_SERVER['HTTP_REFERER']`?

`toggle_gateway_enabled` is not called from anywhere else at the moment, but this future proofs us in case we use it elsewhere in the future.

**Review by joshuatf — COMMENTED** [review]
One quick comment, but testing well.

File: plugins/woocommerce/includes/class-wc-ajax.php (hunk 8 above)
Comment (joshuatf) [reply plugins/woocommerce/includes/class-wc-ajax.php]: Edit: probably better to check from `wp_get_referer()`.

Comment (octaedro) [reply plugins/woocommerce/includes/class-wc-ajax.php]: Good idea! I added this in the commit 780a703.

**Review by louwie17 — APPROVED** [review]
Great work on this @octaedro, works as expected and changes look good 🎉 :shipit:
