### PR TITLE
Block Hooks API: Add the block hooks algorithm to Woo templates

### LINKED ISSUE #45618: Block Hooks API: Add block hooks algorithm to Woo's implementation of building block templates
### Describe the bug

The Block Hooks API currently won’t work with WooCommerce templates. This is because we have our own implementations of cores `_build_block_template_result_from_file` and `_build_block_template_result_from_post` helpers [where the block hooks algorithm hooks into](https://github.com/WordPress/wordpress-develop/blob/trunk/src/wp-includes/block-template-utils.php#L557-L565).

### Steps to reproduce

1. Hook a block into Woos single product block template by adding the below code to a block.json file.
2. Load single product template on the frontend and in the editor
3. See that there is no hooked block.

```json
"blockHooks": {
		"woocommerce/product-details": "after"
	},
```

### PR DESCRIPTION
**Pull request by tjcafferkey**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

This adds the block hooks algorithm to WooCommerce block templates. Since core methods to build block templates are not public we implemented our own. This meant that we do not get enhancements that come from WordPress core, including the block hooks functionality.

This PR brings that functionality to WooCommerce blocks templates. So when developers add hooked blocks to their site they are inserted into Woo templates as well to maintain consistency, previously this did not happen.

Closes https://github.com/woocommerce/woocommerce/issues/45618

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Check out this PR & ensure you're running WP 6.5 latest using the Beta Testing plugin
2. Clear all template customizations on your site.
3. Add the first code block to your site. Check the Single Product template and check that the loginout button is inserted after the product details block in both the editor and on the frontend.
4. Save the template. Reload the editor and using the Code Editor check that the `core/loginout` block has been added to the `ignoredHookedBlocks` meta of the product details block. This confirms it works for block templates loaded from the file system.
5. Now add the second block of code to your site. Reload the Single Product template in both the site editor and the frontend and check that the breadcrumbs block has been automatically inserted into the template.
6. Make a change and save the template. Using the Code Editor check that the `woocommerce/breadcrumbs` block has been added to the `ignoredHookedBlocks` meta of the product details block. This confirms it works for customized templates loaded from the database.
7. Try this on a variety of different Woo templates and blocks to ensure it is working as expected.

```php
function hook_loginout_block( $hooked_blocks, $position, $anchor_block, $context ) {
	if ( $anchor_block === 'woocommerce/product-details' && $position === 'after' ) {
		$hooked_blocks[] = 'core/loginout';
	}

	return $hooked_blocks;
}

add_filter( 'hooked_block_types', 'hook_loginout_block', 10, 4 );
```

```php
function hook_breadcrumbs_block( $hooked_blocks, $position, $anchor_block, $context ) {
	if ( $anchor_block === 'woocommerce/product-details' && $position === 'after' ) {
		$hooked_blocks[] = 'woocommerce/breadcrumbs';
	}

	return $hooked_blocks;
}

add_filter( 'hooked_block_types', 'hook_breadcrumbs_block', 10, 4 );
```

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [x] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [x] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce/src/Blocks/Utils/BlockTemplateUtils.php [hunk 1]
```diff
@@ -229,6 +242,21 @@ public static function build_template_result_from_file( $template_file, $templat
...
+		if ( function_exists( 'inject_ignored_hooked_blocks_metadata_attributes' ) ) {
+			$before_block_visitor = '_inject_theme_attribute_in_template_part_block';
+			$after_block_visitor  = null;
+			$hooked_blocks        = get_hooked_blocks();
+			if ( ! empty( $hooked_blocks ) || has_filter( 'hooked_block_types' ) ) {
+				$before_block_visitor = make_before_block_visitor( $hooked_blocks, $template );
+				$after_block_visitor  = make_after_block_visitor( $hooked_blocks, $template );
+			}
+			$blocks            = parse_blocks( $template->content );
+			$template->content = traverse_and_serialize_blocks( $blocks, $before_block_visitor, $after_block_visitor );
```
Comment (tjcafferkey) [inline plugins/woocommerce/src/Blocks/Utils/BlockTemplateUtils.php:257]: If you're wondering why we run the `parse_blocks` and `traverse_and_serialize_blocks` functions outside of the if statement it is because the visitor needs to look for Template Part blocks, and inject a theme attribute (set to the current theme’s name) into each of them. This predates Block Hooks; it was done a bit differently before, but essentially also required parsing and traversal.

You can find the same in WordPress core [here](https://github.com/WordPress/wordpress-develop/blob/trunk/src/wp-includes/block-template-utils.php#L560C1-L565C109), where we are mimicking this.

**Review by Aljullu — APPROVED** [review]
This is testing well, thanks for working on this @tjcafferkey!

Just one comment about the testing steps:

> Add the first code block to your site.

I would mention they can use the [Code Snippets plugin](https://wordpress.org/plugins/code-snippets/) for this. Otherwise, somebody testing the release might have trouble adding custom code.
