### PR TITLE
Query string -> form field helper function

### LINKED ISSUE #11326: Notice: Array to string conversion
## EXPLANATION OF THE ISSUE
Error on the store page when `$_GET` is recursive array.
 

> Notice: Array to string conversion 

## STEPS TO REPRODUCE THE ISSUE

Go to the store page and add query to url
Example: `site.com/shop/?uf[t][product_cat][value][0]=15&uf[t][product_cat][value][1]=10&uf[t][product_cat][rel]=OR&uf[m][_price][value][0]=0&uf[m][_price][value][1]=12950&uf[m][_price][rel]=BETWEEN`

## A quickfix:

add new function:

```
function query_string_vars($key, $val)
{
	if ( is_array( $val ) ) {
		foreach( $val as $index => $innerVal ) {
			query_string_vars($key . '['.$index.']', $innerVal );
		}
	} else {
		echo '<input type="hidden" name="' . esc_attr( $key ) . '" value="' . esc_attr( $val ) . '" />';
	}
}
```
on the template file woocommerce\templates\loop\orderby.php  replace lines 36-38 to
```
foreach( $val as $index => $innerVal ) {
	query_string_vars($key . '['.$index.']', $innerVal );
}
```

### PR DESCRIPTION
**Pull request by mikejolley**
Used in orderby, this converts query strings to hidden inputs so they can be posted.

Closes #11326 

Testing: go to shop page and add a bunch of query string values. See if they appear in the source of the orderby form.

e.g. `?uf[t][product_cat][value][0]=15&uf[t][product_cat][value][1]=10&uf[t][product_cat][rel]=OR&uf[m][_price][value][0]=0&uf[m][_price][value][1]=12950&uf[m][_price][rel]=BETWEEN`

### CODE REVIEW

File: includes/wc-template-functions.php [hunk 1]
```diff
@@ -337,6 +337,31 @@ function wc_product_post_class( $classes, $class = '', $post_id = '' ) {
 	return $classes;
 }
 
+/**
+ * Outputs hidden form inputs for each query string variable.
+ * @param array $values name value pairs
+ * @param array $exclude keys to exclude
+ * @since 2.7.0
+ */
+function wc_query_string_form_fields( $values = null, $exclude = array(), $currentkey = '' ) {
```
Comment (claudiosmweb) [inline includes/wc-template-functions.php]: Missing inline doc for `$currentkey` and it should be `$current_key`.

File: includes/wc-template-functions.php [hunk 2]
```diff
@@ -337,6 +337,31 @@ function wc_product_post_class( $classes, $class = '', $post_id = '' ) {
 	return $classes;
 }
 
+/**
+ * Outputs hidden form inputs for each query string variable.
+ * @param array $values name value pairs
```
Comment (claudiosmweb) [inline includes/wc-template-functions.php]: Need to start with Uppercase and have a period...

File: includes/wc-template-functions.php [hunk 3]
```diff
@@ -337,6 +337,31 @@ function wc_product_post_class( $classes, $class = '', $post_id = '' ) {
...
+ * @param array $exclude keys to exclude
+ * @since 2.7.0
```
Comment (claudiosmweb) [inline includes/wc-template-functions.php]: Always great when `@since` comes first than the params.
