### PR TITLE
Fix texts in wp-admin-scripts not translated

### LINKED ISSUE #34370: Texts in woocommerce-admin/client/wp-admin-scripts are not translated
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

All texts in woocommerce-admin/client/wp-admin-scripts are not translated

For example texts in product tour are not translated

Screen Shot 2022-08-18 at 15 47 57

### Expected behavior

texts in woocommerce-admin/client/wp-admin-scripts should be translated

### Actual behavior

All texts in woocommerce-admin/client/wp-admin-scripts are not translated

### Steps to reproduce

1. Change site language to `Spanish`
2. Manually set yourself to woocommerce_products_tour treatment group
3. Go to WooCommerce > Home
4. Go to add product tasks
5. Select a template
6. Observe that product spotlight tour is displayed with untranslated texts

### WordPress Environment

N/A

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by chihsuan**
### All Submissions:

-   [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
-   [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
-   [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes #34370.

This PR fixes a bug that texts in wp-admin-scripts are not translated.

Changes:

- Create a util method `register_script` to register admin scripts
- Call `wp_set_script_translations` to get scripts translated

### How to test the changes in this Pull Request:

**Prerequisites**

1.  Switch the site language to `Español`
2. Go to `Escritorio > Actualizaciones` (Dashboard > Updates)
3. Scroll to page bottom and make sure "Translations (Traducciones)" are all up to updated
4. Enable logging `localStorage.setItem( 'debug', 'wc-admin:*' )`

**Test product-tour, product-tracking and onboarding-product-notice**

1. Manually add `experiment woocommerce_products_tour` and set it to treatment via `WooCommerce Admin Test Helper`
2. Experiments woocommerce_products_task_layout_card_v2 and woocommerce_products_task_layout_stacked_v2 should be set to control
3. `Go to WooCommerce > Inicio (Home)` 
4. Skip OBW
5. Go to `Añadir productos`
6. Select physical product template `Producto físico`
7. Observe that texts on the product tour step 1 are translated `Empieza a escribir aquí el nombre de tu nuevo producto. Este será el que verán los clientes en tu tienda.`
8. Observe that `wcadmin_product_edit_view` event is triggered
9. Dismiss the product tour
10. Create the product
11. Observe that `🎉¡Felicidades por haber añadido tu primer producto!` notice is dispalyed.

**Test marketing-coupons**

1. Go to Marketing > Cupones
2. Observe that `Aprende los entresijos de un marketing de éxito de los expertos de WooCommerce.` text is displayed.

**Test navigation-opt-out**

1. Go to `Ajustes > Avanzado > Características` (Settings > Advanced > Features)
2. Enable Navegación
3. Disable Navegación
5. Observe that a modal "Ayúdanos a mejorar" is displayed.

**Test onboarding-tax-notice**

1. Go to WooCommerce > Home
2. Go to `Añade tarifas de impuestos` (tax task)
3. Click `Configura los impuestos manualmente`
4. Add a tax 
6. Observe that a notice `¡Has añadido tu primera tasa de impuestos!` is displayed. 

---

Since the changes are similar, I think the above tests should be enough, but free feel to test the other admin scripts

- payment-method-promotions
- print-shipping-label-banner
- onboarding-homepage-notice

### Other information:

-   [x] Have you added an explanation of what your changes do and why you'd like us to include them?
-   [ ] Have you written new tests for your changes, as applicable?
-   [ ] Have you successfully run tests with your changes locally?
-   [x] Have you created a changelog file for each project being changed, ie `pnpm changelog add --filter=<project>`?

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

File: plugins/woocommerce/src/Admin/Features/OnboardingTasks/Tasks/Products.php [hunk 1]
```diff
@@ -176,16 +158,7 @@ public function possibly_add_load_sample_return_notice_script( $hook ) {
 			return;
 		}
 
-		$script_assets_filename = WCAdminAssets::get_script_asset_filename( 'wp-admin-scripts', 'onboarding-product-notice' );
```
Comment (ilyasfoo) [inline plugins/woocommerce/src/Admin/Features/OnboardingTasks/Tasks/Products.php:179]: I noticed the this has a different script name that is imported, `onboarding-product-notice` compared to the queued filename, `onboarding-load-sample-products-notice`.

I think by changing it to use the `register_script` function, it's now not imported anymore?

**Review by ilyasfoo — COMMENTED** [review]
Great refactor and fix! Tested well, I just have a comment on what could be unintended:

File: plugins/woocommerce/src/Admin/Features/OnboardingTasks/Tasks/Products.php (hunk 1 above)
Comment (chihsuan) [reply plugins/woocommerce/src/Admin/Features/OnboardingTasks/Tasks/Products.php:179]: It's still getting imported 😄 , and `onboarding-load-sample-products-notice` is the correct one because we just need to get its dependencies. 

It didn't cause the error with `onboarding-product-notice`  Because `onboarding-product-notice` dependencies are the superset of `onboarding-load-sample-products-notice`'s.

**Review by ilyasfoo — APPROVED** [review]
Sorry for the delayed re-review. In that case, LGTM! 🚢
