### PR TITLE
Check if there's a 404 template before using it

### LINKED ISSUE #51304: [Fatal] Path cannot be empty in `wc_template_redirect()` include statement | `wc-template-functions.php`
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

During the 9.3.0 release, we observed the following error:

```
PHP Fatal error: Uncaught ValueError: Path cannot be empty 
in /.../woocommerce/includes/wc-template-functions.php:53
```

💡 We can see error logs suggesting this is not new as of 9.3.0.

<details>
<summary> Backtrace </summary>

```
#0 /.../wp-includes/class-wp-hook.php(324): wc_template_redirect('')
#1 /.../wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)
#2 /.../wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#3 /.../wp-includes/template-loader.php(13): do_action('template_redire...')
#4 /.../wp-blog-header.php(19): require_once('/wordpress/core...')
#5 /.../index.php(17): require('/wordpress/core...')
#6 {main}
  thrown in /wp-content/plugins/woocommerce/includes/wc-template-functions.php on line 53
```

</details>

[Relevant code](https://github.com/woocommerce/woocommerce/blob/9.2.3/plugins/woocommerce/includes/wc-template-functions.php#L49-L55)

We're trying to `include` whatever `get_query_template( '404' )` returns, which probably is a valid filepath in lots of cases but, actually, can be anything at all—including an empty string.

### Expected behavior

If we don't have a valid template path, let's find another way to gracefully exit (which is what happens anyway, once execution enters this path) without causing a fatal error.

### Actual behavior

In some circumstances, when we can't determine a valid 404 template path, we're triggering a fatal error.

### Steps to reproduce

No steps to share, this was observed by monitoring error logs.

### WordPress Environment

—

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by albarin**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

This PR checks if the `get_query_template('404')` is empty before including the file, this way we avoid any fatal errors.
Closes https://github.com/woocommerce/woocommerce/issues/51304

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. On `trunk`, make sure your theme does not have a 404-page template.
2. Go to `[YOUR_STORE_URL]/cart/orders/` and check that you get a fatal error like:
```
Warning: include(): Filename cannot be empty in /plugins/woocommerce/plugins/woocommerce/includes/wc-template-functions.php on line 58
Warning: include(): Failed opening '' for inclusion (include_path='.:/usr/share/php:/www/wp-content/pear') in /plugins/woocommerce/plugins/woocommerce/includes/wc-template-functions.php on line 58
```
3. Checkout to this PR branch.
4. Refresh and check you no longer see a fatal error.

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [x] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 
Avoid fatal errors when the theme does not have a 404 page template.

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

**Comment by albarin** [comment]
@naman03malhotra when you review this, can I get your opinion on something: of course, this is better than just getting a fatal error, but it still gives you a blank page, do you think we could do something like this? 👇  I'm seeing that `wc_template_redirect` is redirecting on other cases.
```php
$template = get_query_template('404');
if ( $template ) {
	include $template;
} else {
	wp_safe_redirect( home_url() );
}
```

File: plugins/woocommerce/includes/wc-template-functions.php [hunk 1]
```diff
@@ -53,7 +53,11 @@ function wc_template_redirect() {
 	if ( is_wc_endpoint_url() && ! is_account_page() && ! is_checkout() && apply_filters( 'woocommerce_account_endpoint_page_not_found', true ) ) {
 		$wp_query->set_404();
 		status_header( 404 );
-		include get_query_template( '404' );
+
+		$template = get_query_template( '404' );
+		if ( $template ) {
```
Comment (naman03malhotra) [inline plugins/woocommerce/includes/wc-template-functions.php]: What do you think about adding a check like:

```if ( ! empty( $template ) && file_exists( $template ) )```

File: plugins/woocommerce/includes/wc-template-functions.php [hunk 2]
```diff
@@ -1567,7 +1571,15 @@ function woocommerce_catalog_ordering( $attributes = null ) {
...
-		$show_default_orderby    = 'menu_order' === apply_filters( 'woocommerce_default_catalog_orderby', get_option( 'woocommerce_default_catalog_orderby', 'menu_order' ) );
+
+		/**
+		 * Filter the default catalog orderby.
+		 *
+		 * @since 1.6.4
+		 *
+		 * @param string $default_orderby The default orderby option.
+		 */
+		$show_default_orderby = 'menu_order' === apply_filters( 'woocommerce_default_catalog_orderby', get_option( 'woocommerce_default_catalog_orderby', 'menu_order' ) );
```
Comment (naman03malhotra) [inline plugins/woocommerce/includes/wc-template-functions.php:1584]: should this change part of this PR?

**Review by naman03malhotra — COMMENTED** [review]
> I'm seeing that wc_template_redirect is redirecting on other cases.

I tried to find it in the codebase but couldn't, can you please share the reference?

I think, redirecting to home page sounds like a better idea than just showing a white screen (which ofc, is better than fatal).

File: plugins/woocommerce/includes/wc-template-functions.php (hunk 1 above)
Comment (naman03malhotra) [reply plugins/woocommerce/includes/wc-template-functions.php]: Also is it possible to add tests for this change?

**Comment by albarin** [comment]
> > I'm seeing that wc_template_redirect is redirecting on other cases.
> 
> I tried to find it in the codebase but couldn't, can you please share the reference?

I just meant that the `wc_template_redirect` function is using `wc_safe_redirect` on other cases like:
https://github.com/woocommerce/woocommerce/blob/abbe664879b7b530863655e6108b0681b6a43114/plugins/woocommerce/includes/wc-template-functions.php#L35
 
> I think, redirecting to home page sounds like a better idea than just showing a white screen (which ofc, is better than fatal).

Agree!

File: plugins/woocommerce/includes/wc-template-functions.php (hunk 2 above)
Comment (albarin) [reply plugins/woocommerce/includes/wc-template-functions.php:1584]: Not related but the linter kept complaining that a comment there was necessary 🤔

**Review by naman03malhotra — APPROVED** [review]
For some strange reason, I am not getting a fatal when visiting the `/cart/orders`

Steps I performed on `trunk`:
- Deleted 404 template for the theme.
- Visited `/cart/order` 

I received 404 without fatal.

I can reproduce similar behavior for this branch. I might be missing something.

That said, I believe this PR will only improve the fatal error rate, if that's happening in certain cases.

I am pre-approving this, I believe we still need to add the redirection for to the home page.

image
