### PR TITLE
Fix `wc_customer_bought_product` by using default tables

### LINKED ISSUE #55052: Bug Report: wc_customer_bought_product Always Returns False in WooCommerce 9.6.0
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Describe the Bug
The function wc_customer_bought_product() always returns false in WooCommerce version 9.6.0, even when the customer has purchased the product.

Steps to Reproduce the Issue

Ensure WooCommerce is updated to version 9.6.0.

Create a test product and purchase it using a test customer.

Run the following code to check if the function detects the purchase:
```
$customer_email = 'test@example.com'; // Replace with actual email used in purchase
$product_id = 123; // Replace with actual product ID
$bought = wc_customer_bought_product( $customer_email, get_current_user_id(), $product_id );

var_dump( $bought ); // Expected: true, Actual: false
```
The function incorrectly returns false even when the purchase has been completed.

Environment

WooCommerce Version: 9.6.0
WordPress Version: 6.7.1
PHP Version: 8.2
Theme: Hello Elementor
Plugins Active: Only WooCommerce
Additional Context
This issue started appearing after updating to WooCommerce 9.6.0. The function worked correctly in version 9.4.3.

### Expected behavior

The function should return true if the customer has purchased the product.

### Actual behavior

The function always returns false, regardless of whether the customer has bought the product.

### Steps to reproduce

**Update WooCommerce to version 9.6.0.**
Ensure that the active WooCommerce version is 9.6.0.

**Create a new product in WooCommerce.**
Go to WooCommerce → Products → Add New.
Add a simple product with a fixed price (e.g., $10).
Click Publish.

**Create a test order with a test user.**

Go to WooCommerce → Orders → Add New.
Create a new order and add the product created in the previous step.
Assign the order to a test user (e.g., with email test@example.com).

**Change the order status to Completed and save it.**
Run the following code to check if the function detects the purchase:

Add this snippet to functions.php or run it in a test script:

```
$customer_email = 'test@example.com'; // Email of the test customer
$product_id = 123; // ID of the purchased product
$bought = wc_customer_bought_product( $customer_email, get_current_user_id(), $product_id );

var_dump( $bought ); // Expected: true, Actual: false
```
Check the output:

The expected result is true, but the function always returns false, even if the customer has purchased the product.

### WordPress Environment

<details><summary>System Status Report</summary>

```
### WordPress Environment ###

WordPress address (URL): [Redacted]
Site address (URL): [Redacted]
WC Version: 9.6.0
Legacy REST API Package Version: The Legacy REST API plugin is not installed on this site.
Action Scheduler Version: ✔ 3.9.0
Log Directory Writable: ✔
WP Version: 6.7.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.62 (Unix) PHP/8.2.27
PHP Version: 8.2.27
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 8.11.1
OpenSSL/3.4.0 (SecureTransport)

SUHOSIN Installed: –
MySQL Version: 9.0.1
Max Upload Size: 8 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

[REDACTED]

### Post Type Counts ###

attachment: 1
cbq_log: 8
page: 7
post: 2
product: 1
revision: 3
shop_order_placehold: 2
wp_navigation: 1

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (4) ###

RTL license management: by RTL-Theme – 1.7.7
Modarres Assistant: by CoderBoy – 1.6.2
WooCommerce: by Automattic – 9.6.0
WooLearn: by CoderBoy – 1.2.2

### Inactive Plugins (7) ###

Contact Form 7: by Takayuki Miyoshi – 5.9.8
Dokan: by weDevs – 3.11.5
Elementor: by Elementor.com – 3.23.4
One Click Demo Import: by OCDI – 3.2.1
TeraWallet: by StandaloneTech – 1.5.7
YITH WooCommerce Wishlist: by YITH – 3.38.0
دکان پرو: by weDevs – 3.11.4

### Settings ###

Legacy API Enabled: –
Force SSL: –
Currency: IRR (﷼)
Currency Position: left
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 0
Taxonomies: Product Types: course (course)
external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 30 KB

### WC Pages ###

Shop base: #7 - /shop/
Cart: #8 - /cart/ -  Contains the [woocommerce_cart] shortcode
Checkout: #9 - /checkout/ -  Contains the [woocommerce_checkout] shortcode
My account: #10 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: مدرس
Version: 1.6.2
Author URL: https://coderboy.ir/about/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
Theme type: Classic theme
WooCommerce Support: ✔

### Templates ###

Overrides: modarres/woocommerce/archive-product.php
modarres/woocommerce/cart/cart-empty.php
modarres/woocommerce/cart/cart.php
modarres/woocommerce/content-product.php
modarres/woocommerce/content-single-product.php
modarres/woocommerce/loop/loop-end.php
modarres/woocommerce/loop/loop-start.php
modarres/woocommerce/loop/orderby.php
modarres/woocommerce/myaccount/form-login.php
modarres/woocommerce/myaccount/navigation.php
modarres/woocommerce/single-product/meta.php
modarres/woocommerce/single-product/price.php
modarres/woocommerce/single-product/product-image.php
modarres/woocommerce/single-product/rating.php
modarres/woocommerce/single-product/tabs/tabs.php version 3.8.0 is out of date. The core version is 9.6.0

Outdated Templates: ❌
					
					
						Learn how to update					 |
					
						
					
					
						Clear system status theme info cache

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
onboarding
onboarding-tasks
pattern-toolkit-full-composability
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
printful
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page
launch-your-store

Disabled Features: product-data-views
experimental-blocks
coming-soon-newsletter-template
minified-js
product-pre-publish-modal
settings
async-product-editor-category-field
product-editor-template-system
blueprint
reactify-classic-payments-settings
use-wp-horizon
add-to-cart-with-options-stepper-layout
blockified-add-to-cart

Daily Cron: ✔ Next scheduled: 2025-02-02 06:08:20 +03:30
Options: ✔
Notes: 60
Onboarding: completed

### Action Scheduler ###

Complete: 11
Oldest: 2025-02-01 06:09:32 +0000
Newest: 2025-02-01 07:45:24 +0000

Failed: 1
Oldest: 2025-02-01 06:17:03 +0000
Newest: 2025-02-01 06:17:03 +0000

Pending: 1
Oldest: 2025-02-02 06:09:32 +0000
Newest: 2025-02-02 06:09:32 +0000


### Status report information ###

Generated at: 2025-02-01 11:15:49 +03:30
```
</details>

### Isolating the problem

- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by bor0**
Adds a parameter to use lookup tables, which may be performant in some cases, but correctness depends on when the AS job was ran.

Ideally there would be no delay for populating the lookup table but that might be trickier, and the this PR could serve as a good quick fix.

### Changes proposed in this Pull Request:

Closes #55052, #54853, #54898. Introduced by #52919.

### How to test the changes in this Pull Request:

Buy a product and run the following code to ensure that the function detects the purchase:

```
$customer_email = 'test@example.com'; // Replace with actual email used in purchase
$product_id = 123; // Replace with actual product ID
$bought = wc_customer_bought_product( $customer_email, get_current_user_id(), $product_id );

var_dump( $bought ); // Expected: true
```

Now, add this code snippet to your test site:

```php
add_filter( 'woocommerce_customer_bought_product_use_lookup_tables', '__return_true' );
```

Then buy another product, go to Tools > Scheduled Actions and run the pending action to sync the order product lookup table, and run the code again. You should get the same result.

Disable HPOS (go to WooCommerce > Settings > Advanced > Features and switch "Order data storage" to "WordPress posts), and try the testing steps again, making sure you still get the same results.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

**Review by coreymckrill — COMMENTED** [review]
@bor0 🤔 I like the idea of making the performance improvement an option to toggle on (with explanation of the tradeoffs). But. I'm not convinced that adding the toggle as a function parameter is the best approach. With this, if I'm thinking about this correctly (never a sure bet), we would need to go in and update the usages of the function within WC Core, and then individual sites would still not be able to choose if they want the performance enhancement or not. So it would only be useful for usages within custom code.

What if instead, we added another filter hook right after the conditional resolution of the `woocommerce_pre_customer_bought_product` hook? Something like this:

```php
$use_lookup_tables = apply_filters( 'woocommerce_customer_bought_product_use_lookup_tables', false, $customer_email, $user_id, $product_id );

if ( true === $use_lookup_tables ) {
	// ...
}
```

**Comment by bor0** [comment]
@coreymckrill that's a great idea! I like the possibility of a global application through filters.

Addressed in b8f20cb.

File: plugins/woocommerce/includes/wc-user-functions.php [hunk 1]
```diff
@@ -462,8 +482,19 @@ function ( $status ) {
 ) AS subquery
 WHERE product_or_variation_id != 0
 ";
+			} else {
+				$sql = "
```
Comment (coreymckrill) [inline plugins/woocommerce/includes/wc-user-functions.php:488]:
```suggestion
				// HPOS: yes. Lookup table: no.
				$sql = "
```

Since it's not immediately obvious from the conditional clauses, I think it would be helpful to add a comment like this above each of the four SQL blocks stating which conditions it applies to.

Wdyt?

**Review by coreymckrill — COMMENTED** [review]
👍 Tests well on my local test site. I tried with and without HPOS, with and without the filter to turn on the lookup table. After doing that I updated the testing instructions to reflect that it's a filter now instead of a function parameter.

One comment below to discuss, and then I think this is ready to go.

**Review by imanish003 — COMMENTED** [review]
I've tested the fix for #54898 and can confirm it resolves the issue with review verification delays. Thank you @bor0 for implementing this solution quickly. Note: I tested only functionality, but didn't do a code review.

File: plugins/woocommerce/includes/wc-user-functions.php (hunk 1 above)
Comment (bor0) [reply plugins/woocommerce/includes/wc-user-functions.php:488]: Great idea! Thanks. Tackled in 24bd29f.

**Comment by bor0** [comment]
@coreymckrill or @imanish003 I'll need another review to be able to merge this :)

**Review by coreymckrill — APPROVED** [review]
Approving, but not merging yet until we determine if this is going to be a CFE.
