### PR TITLE
Display line breaks of customer notes in emails, and order details.

### LINKED ISSUE #23956: In Email - Order notes field stripping out line breaks
Like on this bug reported in 2013: https://github.com/woocommerce/woocommerce/issues/3882, the issue is still there.

Is there a solution to keep line breaks from the textarea order notes (in the emails sent)?

### PR DESCRIPTION
**Pull request by claudiosanches**
### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

We don't convert line breaks to `<br>` inside emails or in the order details screen.

Closes #23956.

### How to test the changes in this Pull Request:

1. Place an order (or editing an existing order), and enter a some customer note with line breaks. Placing an order should already trigger emails, but if editing, you may want to select "Resend new order notification" before save.
2. See the line breaks are there in the source code, but doesn't display any `<br>`.
3. Apply this patch, and resend the email, now see that there's `<br>`, and the message display properly.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Fix - Display line breaks of customer notes in emails, and order details.

### CODE REVIEW

File: templates/emails/plain/email-order-details.php [hunk 1]
```diff
@@ -12,37 +12,38 @@
...
-	foreach ( $totals as $total ) {
+if ( $item_totals ) {
+	foreach ( $item_totals as $total ) {
 		echo wp_kses_post( $total['label'] . "\t " . $total['value'] ) . "\n";
 	}
 }
 
 if ( $order->get_customer_note() ) {
-	echo esc_html__( 'Note:', 'woocommerce' ) . "\t " . wp_kses_post( wptexturize( $order->get_customer_note() ) ) . "\n";
+	echo esc_html__( 'Note:', 'woocommerce' ) . "\t " . wp_kses_post( nl2br( wptexturize( $order->get_customer_note() ) ) ) . "\n";
```
Comment (kloon) [inline templates/emails/plain/email-order-details.php]: This change will cause the text <br/> to be outputted in text emails. I think it should not be passed through nl2br for plain text emails.

**Review by kloon — CHANGES_REQUESTED** [review]
Just a small issue with plain text emails

File: templates/emails/plain/email-order-details.php (hunk 1 above)
Comment (claudiosanches) [reply templates/emails/plain/email-order-details.php]: Ohh, yeah, we can avoid that, still plain text emails should strip those anyway.

**Review by kloon — APPROVED** [review]

**Comment by adrien-robert** [comment]
Do you know when this change will be release? Next WooCommerce version? Any ETA?
Thanks a lot.

**Comment by kloon** [comment]
@adrien-robert this will be part of the 3.7 release, the beta version is out already and ready for testing if you want to give it a test. You can download it here https://downloads.wordpress.org/plugin/woocommerce.3.7.0-beta.1.zip

**Comment by adrien-robert** [comment]
> @adrien-robert this will be part of the 3.7 release, the beta version is out already and ready for testing if you want to give it a test. You can download it here https://downloads.wordpress.org/plugin/woocommerce.3.7.0-beta.1.zip

Thanks!
