### PR TITLE
Marketplace: better update the update badge count in My Subscription tab

### LINKED ISSUE #46484: My subscriptions notification badge is not synced automatically in some cases in the WooCommerce Extensions page
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

The notification badge that appears next to `My subscription` in `WooCommerce > Extensions` isn't synced automatically, and some times it can cause confusion to the users.

You can spot this behaviour when you install a plugin in WooCommerce 8.8.0 (which contains the Woo Update Manager) and it raises a notification for whatever reason (for example, and old version that requires an update but you can't update it because you have already installed the extension in other sites).

In this case, when you uninstall the plugin that triggered that notification, you can see how the notification doesn't change. This is because it's not synced automatically, and you need to refresh the subscriptions in-app and then refresh the browser so that you can see the changes.

This behaviour can be confusing to our users, so it would be great if we could find the way to automatically sync the notification badge next to `My subscriptions` in order to improve the user experience.

### Expected behavior

The number inside the notification badge next to `My subscriptions` should be decreased by 1 compared to the one noted in the step 5 of the testing instructions after uninstalling AutomateWoo.

If the number was 1 prior to uninstalling the plugin, now the notification badge should disappear.

### Actual behavior

The notification badge next to `My subscriptions` looks exactly the same than prior to uninstalling AutomateWoo. You need to refresh your subscriptions in the `My subscriptions` page and then refresh the page so that you can see the notification badge updated accordingly.

### Steps to reproduce

1. Make sure you have 2 sites with a plugin from WooCommerce.com like AutomateWoo connected to your WooCommerce.com account (I think this is the maximum number of sites you can connect a paid plugin to WooCommerce.com with your account simultaneously). We need to make sure you have spent the number of simultaneous installations for a WooCommerce.com plugin.
2. Create a new site with WooCommerce 8.8.0.
3. Install an outdated version of AutomateWoo on this site too (which would exceed the number of plugins installations that you can connect to WooCommerce.com).
4. Connect this site to WooCommerce.com, which should install the Woo Update Manager plugin.
5. Go to `WooCommerce > Extensions > My Subscriptions` and make sure there is an entry for AutomateWoo in the `Installed on this store` section. Also make sure there is a red notification badge next to `My subscriptions`. This notification badge should have a number inside, note this number.
6. Go to `WooCommerce > Plugins > Installed Plugins` and uninstall AutomateWoo.
7. Go again to `WooCommerce > Extensions > My Subscriptions`.

### WordPress Environment

Any site with WooCommerce 8.8.0.

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by raicem**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

The badge shown in the My Subscriptions tab is the number of outdated WooCommerce.com products. 

image

Whenever a user deactivates or activates a Woo plugin we ping WooCommerce.com to establish a connection for the subscription. As a result, we flush cache to re-calculate the pending updates for WooCommerce.com products. 

However, the timing of this cache was not ideal. 

- Activation: if a subscription is maxed out or not found, we _don't_ flush the cache. So product becomes active in the local store, but we pretend it's not. We should start showing a badge if the product is out of date, but we don't.
- Deactivation: if subscription wasn't connected in the first place, we never flush the cache as a result of deactivation. Users expecting update badge to disappear, but it doesn't.

As a result, the `_woocommerce_helper_updates_count` transient is never flushed and  `WC_Helper_Updater::get_updates_count` returns stale data. 

Also, when we calculate the number of pending updates, we also count deactivated plugins as well. This PR also changes that behavior and they are not counted towards the badge.

Closes #46484.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Checkout this branch and get a new build `pnpm install && pnpm build`
2. We need to max out subscription connections first. From WooCommerce.com My Subscriptions page, share that paid subscription to two other other accounts. This will max out all connections.
    - To confirm, WCCOM My Subscription will show `Not available - shared with 2 others` message 
3. Start your local WooCommerce dev environment. Connect it to the same WooCommerce.com account. 
4. Download the outdated version of the paid plugin you have subscription to and upload it to your test site. 
    - Please ping me if you need assistance in finding the outdated versions. 
5. After activating the plugin, go to[ My Subscription tab ](http://localhost:8888/wp-admin/admin.php?page=wc-admin&term=afdfd&tab=my-subscriptions&path=%2Fextensions)and confirm you see a badge next to the tab.
   - if you don't have WooCommerce Update Manager installed, the badge starts from 1. So +1 for missing WUM and then +1 for oudated plugin. 
6. Hover the badge to read the explanation. 
    - Unfortunately, if the badge is there for WUM, the explanation is not great. 
7. Deactivate the plugin and go back to [the My Subscriptions tab](http://localhost:8888/wp-admin/admin.php?page=wc-admin&term=afdfd&tab=my-subscriptions&path=%2Fextensions) again. Confirm the badge is gone. 
8. Repeat the same steps with a paid theme as well.
9. Perform a search and hover over the badges next to the tabs such as Extensions and Themes. Confirm the explanation now includes the number as well.
10. Please test around this issue.

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 
Better updates the pending updates count in the Marketplace My Subscriptions tab.
</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce/includes/admin/helper/class-wc-helper-updater.php [hunk 1]
```diff
@@ -690,6 +690,10 @@ public static function get_updates_count() {
 				continue;
 			}
 
+			if ( ! is_plugin_active( $plugin['_filename'] ) ) {
+				continue;
+			}
```
Comment (raicem) [inline plugins/woocommerce/includes/admin/helper/class-wc-helper-updater.php:699]: This is a change that I need to double check with the team. This will **not** count deactivated products in the update badge.

File: plugins/woocommerce/client/admin/client/marketplace/components/tabs/tabs.tsx [hunk 2]
```diff
@@ -98,6 +98,28 @@ const renderTabs = (
...
+									: __(
+											'Number of matching items in this category',
+											'woocommerce'
+									  )
+							}
+							aria-label={
+								tabKey === 'my-subscriptions'
+									? __(
+											'Number of updates available for your subscriptions',
+											'woocommerce'
```
Comment (KokkieH) [inline plugins/woocommerce/client/admin/client/marketplace/components/tabs/tabs.tsx]: Voiceover is reading out this text without quoting the actual number, which is confusing.

Screenshot_2025_07_17__12_44

We should include the actual count here as well for this screen reader text to make sense.

**Review by KokkieH — CHANGES_REQUESTED** [review]
It works as described for plugins and themes, but there's a change needed to the aria-label to make it less confusing.

File: plugins/woocommerce/client/admin/client/marketplace/components/tabs/tabs.tsx (hunk 2 above)
Comment (raicem) [reply plugins/woocommerce/client/admin/client/marketplace/components/tabs/tabs.tsx]: Thanks for the suggestion, updated in: [`7908479` (#56158)](https://github.com/woocommerce/woocommerce/pull/56158/commits/79084799bd9b44b94368946fc9b6dbff1e8673a1)

**Review by KokkieH — APPROVED** [review]
Thanks for the change. Screen reader text is much clearer now.
