### PR TITLE
Fix issue that breaks the WooCommerce Home Page when Gutenberg 15.5 is active

### LINKED ISSUE #37640: [GlobalStep] "Blank Screen" is displayed after clicking "Woocommerce> Home" when Gutenberg plugin is active.
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

"Blank Screen" is displayed after clicking "Woocommerce> Home" when Gutenberg plugin is active.

### Expected behavior

After clicking "Woocommerce > Home" appropriate page should be displayed.

### Actual behavior

Blank Screen is displayed after clicking "Woocommerce > Home" when Gutenberg plugin is active.

### Steps to reproduce

1. Create a new test site.
2. Install and activate all the required plugins.
3. Install and activate WooCommerce 7.6 RC2.
4. Complete OBW flow.
5. Install and activate the "Gutenberg" plugin
6. Click on "Woocommerce > Home" 
7. Observe that the Blank Screen is displayed.

### WordPress Environment

Woocommerce Version:
WooCommerce 7.6.0 RC2
WordPress version: 6.2

PC:
Windows 10
Chrome(Version  112.0.5615.50)
Firefox(Version111.0.1)

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

<details>

`
### WordPress Environment ###

WC Version: 7.6.0
REST API Version: ✔ 7.6.0
WC Blocks Version: ✔ 9.8.4
Action Scheduler Version: ✔ 3.5.4
Log Directory Writable: ✔
WP Version: ❌ 6.2 - There is a newer version of WordPress available (6.2.1-alpha-55640)
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.56 (Unix) OpenSSL/1.0.2g
PHP Version: 8.0.28
PHP Post Max Size: 1 GB
PHP Time Limit: 30
PHP Max Input Vars: 5000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.7.33-0ubuntu0.16.04.1-log
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.6.0
WC Database Prefix: wp_
Total Database Size: 11.56MB
Database Data Size: 8.94MB
Database Index Size: 2.62MB
wp_woocommerce_sessions: Data: 0.03MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.08MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_automations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_automation_runs: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_automation_run_logs: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_automation_run_subjects: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_automation_triggers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_automation_versions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_custom_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_dynamic_segment_filters: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_feature_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_forms: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletters: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_newsletter_links: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_newsletter_option: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_option_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_posts: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_segment: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_templates: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_scheduled_tasks: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_scheduled_task_subscribers: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_segments: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_sending_queues: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_settings: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_statistics_bounces: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_statistics_clicks: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_statistics_forms: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_statistics_newsletters: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_statistics_opens: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_mailpoet_statistics_unsubscribes: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_statistics_woocommerce_purchases: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_mailpoet_stats_notifications: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_subscribers: Data: 0.02MB + Index: 0.13MB + Engine InnoDB
wp_mailpoet_subscriber_custom_field: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_subscriber_ips: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_subscriber_segment: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_subscriber_tag: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_tags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_user_agents: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_user_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 4.45MB + Index: 0.11MB + Engine InnoDB
wp_postmeta: Data: 0.13MB + Index: 0.06MB + Engine InnoDB
wp_posts: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 27
mailpoet_page: 1
page: 10
post: 2
product: 22
product_variation: 7
revision: 3
shop_order: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (6) ###

Query Monitor: by John Blackbourn – 3.12.1
Companion Plugin: by Osk – 1.29
Gutenberg: by Gutenberg Team – 15.5.0
WooCommerce: by Automattic – 7.6.0-rc.2
WordPress Beta Tester: by WordPress Upgrade/Install Team – 3.3.7
WP Crontrol: by John Blackbourn & crontributors – 1.15.2

### Inactive Plugins (4) ###

Akismet Anti-Spam: by Automattic – 5.1
Hello Dolly: by Matt Mullenweg – 1.7.2
Jetpack: by Automattic – 12.0
MailPoet: by MailPoet – 4.11.0

### Dropin Plugins (1) ###

db.php: Query Monitor Database Class (Drop-in)

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
Order datastore: WC_Order_Data_Store_CPT

### WC Pages ###

Shop base: #7 - /shop/
Cart: #74 - /test-cart/
Checkout: #76 - /test-checkout/
My account: #10 - /my-account/
Terms and conditions: #9 - /checkout/

### Theme ###

Name: Storefront
Version: 4.2.0
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
multichannel-marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: block-editor-feature-enabled
minified-js
new-product-management-experience
product-variation-management
settings

Daily Cron: ✔ Next scheduled: 2023-04-11 06:41:02 +00:00
Options: ✔
Notes: 40
Onboarding: completed

### Action Scheduler ###

Complete: 112
Oldest: 2023-04-10 06:42:07 +0000
Newest: 2023-04-10 12:05:08 +0000

Failed: 12
Oldest: 2023-04-10 06:45:07 +0000
Newest: 2023-04-10 12:07:02 +0000

Pending: 1
Oldest: 2023-04-11 06:42:07 +0000
Newest: 2023-04-11 06:42:07 +0000

### Status report information ###

Generated at: 2023-04-10 14:13:11 +00:00
`

</details>

### PR DESCRIPTION
**Pull request by nerrad**
### Submission Review Guidelines:

- I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
- I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
- I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/). 
- Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes #37640.

In the linked issue you can see the report on how when Gutenberg 15.5 is active, the WooCommerce home page is broken. This release of Gutenberg updated some behaviour for the `useSelect` API, and while I'm not 100% sure - it impacts the (arguably incorrect) usage of `registry.dispatch` in provided `useSelect` callbacks.

I was able to resolve the error by ensuring any dispatch calls are in a `useEffect` (they are side-effects so _should_ be). 

There were also a couple other incorrect calls to a `setState` function outside of an effect that I fixed in this PR.

Very important:

- This likely has subtle impact on behaviours, I don't know what those are, nor did I test extensively. I focused on fixing the error and providing a potential path forward. Followup is needed.
- The usage of legacy HOCs and React class components in the codebase is going to be more problematic as time goes on (due to changes with React concurrency mode, suspense etc). I strongly recommend setting some time to refactor away from them.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Activate Gutenberg 15.5
2. Verify the WooCommerce Admin Home page loads without issues.
3. Verify that skipping the onboarding wizard works without issue, and also with completing the onboarding wizard
4. Verify that homescreen's inbox notes are displayed as usual
5. Verify steps 2 - 5 still apply with Gutenberg plugin disabled

### CODE REVIEW

File: packages/js/data/src/onboarding/with-onboarding-hydration.tsx [hunk 1]
```diff
@@ -20,39 +19,26 @@ export const withOnboardingHydration = ( data: {
...
-					}
-				},
-				[]
-			);
+			const { startResolution, finishResolution, setProfileItems } =
+				useDispatch( STORE_NAME );
+			useEffect( () => {
+				if ( ! onboardingRef.current ) {
+					return;
+				}
```
Comment (nerrad) [inline packages/js/data/src/onboarding/with-onboarding-hydration.tsx:43]: I left this logic mostly as is, unclear why it's needed. I also moved in the `profileItems` check from `homescreen/index.js` which makes the confusing logic stand out a bit more.

File: packages/js/data/src/onboarding/with-onboarding-hydration.tsx [hunk 2]
```diff
@@ -20,39 +19,26 @@ export const withOnboardingHydration = ( data: {
...
+
+				const { profileItems } = onboardingRef.current;
+				if ( ! profileItems ) {
+					return;
+				}
+
+				if ( profileItems && ! hydratedProfileItems ) {
```
Comment (nerrad) [inline packages/js/data/src/onboarding/with-onboarding-hydration.tsx]: Given the existing `profileItems` check above, the additional isn't needed.

File: packages/js/data/src/settings/with-settings-hydration.tsx [hunk 3]
```diff
@@ -16,31 +16,45 @@ export const withSettingsHydration = ( group: string, settings: Settings ) =>
...
+						isResolvingGroup: isResolving( 'getSettings', [
+							group,
+						] ),
+						hasFinishedResolutionGroup: hasFinishedResolution(
+							'getSettings',
+							[ group ]
+						),
+					};
+				}
+			);
```
Comment (nerrad) [inline packages/js/data/src/settings/with-settings-hydration.tsx]: I forgot to add dependencies on the `useSelect` callback, can probably add `[]` here?

File: plugins/woocommerce-admin/client/homescreen/index.tsx [hunk 4]
```diff
@@ -50,10 +49,8 @@ const withSelectHandler = ( select: WCDataSelector ) => {
 };
 
 export default compose(
-	onboardingData.profile
-		? withOnboardingHydration( {
-				profileItems: onboardingData.profile,
-		  } )
-		: identity,
```
Comment (nerrad) [inline plugins/woocommerce-admin/client/homescreen/index.tsx:57]: Conditional composition here is a bit confusing and potentially prone to bugs so I moved the `onboardingData.profile` check into the HOC.

File: plugins/woocommerce-admin/client/homescreen/layout.js [hunk 5]
```diff
@@ -76,9 +77,11 @@ export const Layout = ( {
...
 			'two_columns' && hasTwoColumnContent;
 
-	if ( isBatchUpdating && ! showInbox ) {
-		setShowInbox( true );
-	}
+	useEffect( () => {
+		if ( isBatchUpdating && ! showInbox ) {
+			setShowInbox( true );
+		}
+	}, [ isBatchUpdating, showInbox ] );
```
Comment (nerrad) [inline plugins/woocommerce-admin/client/homescreen/layout.js]: `setState` should not occur outside of an effect.

Comment (mattsherman) [reply plugins/woocommerce-admin/client/homescreen/layout.js]: I don't think this is a general rule, right?

Unless I'm missing something, I don't even see where `showInbox` is used at all! So, I think we can just totally remove this bit of state.

Comment (ilyasfoo) [reply plugins/woocommerce-admin/client/homescreen/layout.js]: Good catch, @mattsherman! It seems the `showInbox` usage was removed in [this PR](https://github.com/woocommerce/woocommerce-admin/pull/5465/files#diff-de1bf1e6e26b24ec1623b1a6c816a8fb3984b05375c320c8ad82d44701f59ad7L85).

File: packages/js/data/src/settings/with-settings-hydration.tsx (hunk 3 above)
Comment (ilyasfoo) [reply packages/js/data/src/settings/with-settings-hydration.tsx]: Added in 07456fe86781c3b514bdcb9ade0640066c83a30d

File: plugins/woocommerce-admin/client/homescreen/layout.js (hunk 5 above)
Comment (ilyasfoo) [reply plugins/woocommerce-admin/client/homescreen/layout.js]: Removed this in [1fd1e86](https://github.com/woocommerce/woocommerce/pull/37641/commits/1fd1e8638ab613effcba9889fd503a7b49669eb1)

**Review by ilyasfoo — APPROVED** [review]
Tested well

File: packages/js/data/src/onboarding/with-onboarding-hydration.tsx (hunk 2 above)
Comment (ilyasfoo) [reply packages/js/data/src/onboarding/with-onboarding-hydration.tsx]: We've found that it actually broke redirects p1681188908953349/1681170705.881689-slack-C01SFMVEYAK

Added back the checks in https://github.com/woocommerce/woocommerce/pull/37641/commits/a0f40d1324ca0342bba43a74907794892098d480

File: plugins/woocommerce-admin/client/homescreen/layout.js (hunk 5 above)
Comment (jsnajdr) [reply plugins/woocommerce-admin/client/homescreen/layout.js]: `setState` outside an effect, directly during render, can be fine in some cases, and this one seems to have been one of them. When the `isBatchUpdating` prop changed to `true`, it was syncing the `showInbox` state to be `true`, too. Kind of a hook version of `getDerivedStateFromProps`.

When `setState` is called directly in render, then the result of the current render is guaranteed to be never used. Not committed to DOM, no effects running. Because the render was kind of inconsistent: `isBatchUpdating` is already `true`, but `showInbox` can still be `false`. Instead, the `setState` is scheduled to be run as soon as possible, and triggers a new render, with the new, consistent, state values.

`getDerivedStateFromProps`, internally, has the same semantics and scheduling.

File: packages/js/data/src/onboarding/with-onboarding-hydration.tsx [hunk 6]
```diff
@@ -21,39 +20,54 @@ export const withOnboardingHydration = ( data: {
 		( OriginalComponent ) => ( props ) => {
 			const onboardingRef = useRef( data );
```
Comment (jsnajdr) [inline packages/js/data/src/onboarding/with-onboarding-hydration.tsx:21]: This ref probably never had to be there? The `data` value is constant, it's passed once for all when creating a HOC with `withOnboardingHydration( data )`. There's no need for each wrapped component to store its own copy in a local ref. The code can just reference the `data` variable in the closure. Just like it references `hydratedProfileItems`, or `group` (in other usages of this pattern).

File: packages/js/data/src/onboarding/with-onboarding-hydration.tsx [hunk 7]
```diff
@@ -21,39 +20,54 @@ export const withOnboardingHydration = ( data: {
...
-						profileItems &&
-						! hydratedProfileItems &&
-						! isResolving( 'getProfileItems', [] ) &&
-						! hasFinishedResolution( 'getProfileItems', [] )
-					) {
-						startResolution( 'getProfileItems', [] );
-						setProfileItems( profileItems, true );
-						finishResolution( 'getProfileItems', [] );
-
-						hydratedProfileItems = true;
```
Comment (jsnajdr) [inline packages/js/data/src/onboarding/with-onboarding-hydration.tsx:51]: This is a really weird use of `useSelect` and I'm starting to see how https://github.com/WordPress/gutenberg/pull/47243 could break it. The main issue is that the `useSelect` callback is run _reentrantly_, as the dispatches modify the same store, even the same value, as is being selected.

The sequence of events is:
1. `useSelect` runs the select callback.
2. The callback dispatches the `startResolution` action.
3. After the `startResolution` action modifies the store, it runs all registered listeners.
4. One of the listeners is our own `useSelect` hook.
5. The listener calls the select callback to determine the new selected value.
6. There is a second call of the select callback, at the time when the first call is still running!

Now note that `useSelect` runs the select callback inside the [`__unstableMarkListeningStores`](https://github.com/WordPress/gutenberg/blob/79623c991ca8b37e5b104264b8be12c5ae72e82d/packages/data/src/registry.js#L120-L128) wrapper, which sets and unsets the global `listenerStores` variable. While the first call is still running, the second call resets the shared `listenerStores` set with a new, empty instance.

The `listenerStores` set keeps a list of stores to subscribe to, to watch changes in them. Now, instead of subscribing to `STORE_NAME`, the `useSelect` hook won't subscribe to any stores, because the set is empty, and won't see any store updates, like changes in resolution status.

Before https://github.com/WordPress/gutenberg/pull/47243, `useSelect` used the `__unstableMarkListeningStores` wrapper only on mount, to figure out the set of stores to subscribe to, but after that PR, it uses the wrapper for every select, because it can newly add new subscriptions dynamically. Therefore, there are many more opportunities to hit that reentrancy issue.

File: packages/js/data/src/onboarding/with-onboarding-hydration.tsx [hunk 8]
```diff
@@ -21,39 +20,54 @@ export const withOnboardingHydration = ( data: {
...
+					hydratedProfileItems = true;
+				}
+			}, [
+				finishResolution,
+				setProfileItems,
+				startResolution,
+				isResolvingGroup,
+				hasFinishedResolutionGroup,
+			] );
+
```
Comment (jsnajdr) [inline packages/js/data/src/onboarding/with-onboarding-hydration.tsx:70]: The goal, as I understand it, is that a component wrapped with `withOnboardingHydration( data )( Comp )` will, on mount, simulate running the `getProfileItems` selector. Pretend that the resolution has started, written the data, and ended. External observer shouldn't see any difference from running the real resolver, fetching from a REST endpoint.

Then I would write it this way:
```js
function withOnboardingHydration( data ) {
  return createHigherOrderComponent( ( Wrapped ) => ( props ) => {
    const registry = useRegistry();
    useEffect( () => {
      const { profileItems } = data;
      if ( ! profileItems ) {
        return;
      }
      const shouldHydrate = registry.select( STORE_NAME ).getIsResolving( 'getProfileItems', [] ) !== undefined;
      if ( ! shouldHydrate ) {
        return;
      }
      registry.dispatch( STORE_NAME ).startResolution( 'getProfileItems', [] );
      registry.dispatch( STORE_NAME ).setProfileItems( profileItems );
      registry.dispatch( STORE_NAME ).finishResolution( 'getProfileItems', [] );
    }, [ registry ] );
    return <Wrapped { ...props } />;
  } );
}
```
The `getIsResolving` selector is a shortcut for "is resolving or has finished resolving". We don't need the `hydratedProfileItems` variable because the same information is already stored in the resolution status. And I'm avoiding the `useSelect` and `useDispatch` hooks, and use the data stores "procedurally" from inside the effect callback.
