### PR TITLE
[Experimental] Product Filters - Conditionally remove router region

### LINKED ISSUE #52796: [Experimental] Duplicated elements when the Product Filters block is moved within the Product Collection block
If you add the Product Filters block within the Product Collection block, there will be some visual oddities after filtering. In this case, filters seem to duplicate itself. Note that this does not happen in the Product Catalog Template when it is not inside the Product Collections Block. Please see screen recording:

https://github.com/user-attachments/assets/cabcf1f7-ace0-4b05-bd2a-e36eb7c35073

Some internal discussions ref: p1737417870580729-slack-C04QWL152LX

**Steps to reproduce:**

- Add a page.
- Add the Product Collection block.
- Add the Product Filters (Experimental) block into (within) the Product Collection block.
- Save and visit the frontend.
- Play around with the filters check/uncheck them and you will see the visual oddities.

### PR DESCRIPTION
**Pull request by roykho**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes #52796

This PR is a work around fix until https://github.com/woocommerce/gutenberg/pull/4 is merged and available in WP. Basically the bug is when Product Filters (Experimental) is added within the Product Collection block, we would visually see duplicated filter options.

### Screenshots or screen recordings:

The bug will visually look like this:
CleanShot 2025-03-03 at 09 12 33

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

> [!NOTE]  
> **Pre-requisite**
> - If you're using WC Beta Tester plugin, make sure the `experimental-blocks` feature is enabled (Tools > WCA Test Helper > Features).
> - Make sure to reset Product Catalog Template.

1. Navigate to Product Catalog template (Appearance > Editor > Templates > Product Catalog template.
2. Edit the template.
3. Add the Product Filters (Experimental) outside of the Product Collection block. See image below:
CleanShot 2025-03-03 at 09 07 35
4. Save and go to the frontend.
5. Click on the Color Attribute filter "Red" to check it and then click on it again to uncheck it.
6. Ensure you don't see any duplicated filter items visually.
7. Now go back and move the Product Filters (Experimental) inside of the Product Collection block. See image below:
CleanShot 2025-03-03 at 09 06 44
8. Save and go to the frontend.
9. Click on the Color Attribute filter "Red" to check it and then click on it again to uncheck it.
10. Ensure you don't see any duplicated filter items visually.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

**Comment by roykho** [comment]
👋 @tjcafferkey in case you missed this.

**Review by tjcafferkey — APPROVED** [review]
This tests well and the code LGTM lets just make sure we create a follow-up issue so we dont forget about this I think!

**Screenshots**

CleanShot 2025-03-06 at 10 27 33

CleanShot 2025-03-06 at 10 27 45

CleanShot 2025-03-06 at 10 29 51

**Environment**
* LocalWP
* WP 6.7

**Testing steps**
I followed the same steps outlined in the description of this PR.

**Comment by tjcafferkey** [comment]
@roykho I just want to double check for my own understanding that we want to run `maybeRemoveRouterRegion` on the _current_ content (e.g. before `navigate()`) as my concern was that there could be a race condition if we wanted to do it on new content and `navigate()` updated the markup _afterwards_

**Comment by dinhtungdu** [comment]
@roykho I have the same concern as @tjcafferkey. If the objective is to remove the router region attribute when Product Filters is nested inside the PC, what do you think about doing it from the server side using block context? Product Collection block provides some context, Product Filter can use one of them to determine if it's being nested inside PC or not.

**Comment by roykho** [comment]
@tjcafferkey @dinhtungdu thanks for the review. I actually first tried server side implementation but forgot that PC provides context. So thanks for reminding me. I have pushed up changes to detect this only on server side.

File: plugins/woocommerce/src/Blocks/BlockTypes/ProductFilters.php [hunk 1]
```diff
@@ -18,7 +18,7 @@ class ProductFilters extends AbstractBlock {
 	 * @return string[]
 	 */
 	protected function get_block_type_uses_context() {
-		return array( 'postId', 'query', 'queryId' );
+		return array( 'postId', 'query', 'queryId', 'woocommerce/product-collection' );
```
Comment (dinhtungdu) [inline plugins/woocommerce/src/Blocks/BlockTypes/ProductFilters.php]: The PC block doesn't provide this context (`woocommerce/product-collection`), so why do we need this change?

You can use `productCollectionLocation` without declaring anything, as that context is injected into the block that uses the `query` context.

**Review by dinhtungdu — COMMENTED** [review]
Thanks for the update! I tested with Product Filters nested inside the PC and didn't see the duplicated filter options. I have a question about the context declaration though.

#### Screenshot
image

#### Test environment
- WordPress 6.7.2
- Only WooCommerce is activated.

#### Testing steps
Tested both cases when the Product Filters block is and isn't nested inside the Product Collection block.

File: plugins/woocommerce/src/Blocks/BlockTypes/ProductFilters.php (hunk 1 above)
Comment (roykho) [reply plugins/woocommerce/src/Blocks/BlockTypes/ProductFilters.php]: Ah sorry I was testing something and accidentally left it there. I pushed update to remove it. https://github.com/woocommerce/woocommerce/pull/56038/commits/6794aa46348f605c5197c299bdeb999a6f1540b0

File: plugins/woocommerce/src/Blocks/BlockTypes/ProductFilters.php [hunk 2]
```diff
@@ -100,12 +100,17 @@ function ( $carry, $parsed_block ) use ( $block_context ) {
 			'data-wp-interactive'              => $this->get_full_block_name(),
 			'data-wp-watch--scrolling'         => 'callbacks.scrollLimit',
 			'data-wp-on--keyup'                => 'actions.closeOverlayOnEscape',
-			'data-wp-router-region'            => $this->generate_navigation_id( $block ),
 			'data-wp-context'                  => wp_json_encode( $interactivity_context, JSON_HEX_TAG | JSON_HEX_APOS | JSON_HEX_QUOT | JSON_HEX_AMP ),
 			'data-wp-class--is-overlay-opened' => 'context.isOverlayOpened',
 			'style'                            => $styles,
 		);
 
+		// phpcs:ignore
```
Comment (dinhtungdu) [inline plugins/woocommerce/src/Blocks/BlockTypes/ProductFilters.php]: I can see that you put the ignore here to avoid the warning with todo below, but I think the warning is actually needed to remind us about the todo. Does CI complaint about that or do you have any other reason?

Comment (roykho) [reply plugins/woocommerce/src/Blocks/BlockTypes/ProductFilters.php]: Yeah I am getting warning in the IDE...Not sure in CI though.

Comment (dinhtungdu) [reply plugins/woocommerce/src/Blocks/BlockTypes/ProductFilters.php]: Then I think we should try removing that ignore to use the warning for our benefit. That's my only remaining recommendation. We have multiple todos in our codebase, none of them is ignored.

Comment (roykho) [reply plugins/woocommerce/src/Blocks/BlockTypes/ProductFilters.php]: Done here [cdbdf62](https://github.com/woocommerce/woocommerce/pull/56038/commits/cdbdf62699b1371d3dc4f133bc03e02c806ed570)

**Review by dinhtungdu — APPROVED** [review]
Thanks for addressing the feedback. This PR is LGTM now.
