### PR TITLE
Mark marketing task as complete when an extension is installed

### LINKED ISSUE #32149: Is not possible to mark the marketing task as complete in the setup tasklist
### Describe the bug

Is not possible to mark the marketing task as complete in the setup tasklist.

### To Reproduce

1. In a brand new store, go through the OBW, and in step 4 (Business Details), go to `Free features` and install the `MailPoet` extension.
2. Finish the OBW.
3. On the `Home` page, press `Set up marketing tools`.
4. The marketing task should be marked as complete but that is not happening and there is no way to do it without installing an extension in the task.

### Actual behavior:

Is not possible to mark the marketing task as complete in the setup tasklist. To accomplish that it's necessary [to install an extension in the step](https://github.com/woocommerce/woocommerce-admin/blob/main/client/tasks/fills/Marketing/index.tsx#L153).

### Screenshots

screenshot-confused-fly jurassic ninja-2022 02 25-18_45_23

### Expected behavior

If the user has one of the marketing extensions installed, we should action the task after pressing `Set up marketing tools` (p1645789832142759/1645544417.244379-slack-C01CMSA1VHS).

### PR DESCRIPTION
**Pull request by octaedro**
### All Submissions:

* [ ] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
* [ ] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes #32149.

### How to test the changes in this Pull Request:

1. In a brand new store, go through the OBW, and in step 4 (Business Details), go to `Free features` and install the `MailPoet` extension.
2. Finish the OBW.
3. Go to the `Home` screen and verify that the marketing task is marked as completed.
4. Delete the `MailPoet` extension.
5. Verify that the marketing task is not marked as completed now.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?
* [x] Have you created a changelog file by running `pnpm nx affected --target=changelog`?

### FOR PR REVIEWER ONLY:

* [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

File: plugins/woocommerce/src/Admin/Features/OnboardingTasks/Tasks/Marketing.php [hunk 1]
```diff
@@ -125,13 +125,13 @@ public static function has_installed_extensions() {
...
-		}
-
-		// Make sure the task has been actioned and at least one extension is installed.
-		if ( count( $installed ) > 0 && Task::is_task_actioned( 'marketing' ) ) {
+		// Make sure the task has been actioned or all extensions installed
+		// or a marketing extension has been installed.
+		if (
+			count( $installed ) > 0 ||
+			Task::is_task_actioned( 'marketing' ) ||
+			count( $remaining ) === 0
```
Comment (joelclimbsthings) [inline plugins/woocommerce/src/Admin/Features/OnboardingTasks/Tasks/Marketing.php]: Just curious, this condition seems a little redundant with the first one, since `$remaining` is just the inverse of `$installed`, but perhaps it's needed to capture the condition that there are _no_ plugins?

**Review by joelclimbsthings — DISMISSED** [review]
Thanks @octaedro , tests well and looks good. Left a quick question, but not a blocker by any means. 🚢

File: plugins/woocommerce/src/Admin/Features/OnboardingTasks/Tasks/Marketing.php (hunk 1 above)
Comment (octaedro) [reply plugins/woocommerce/src/Admin/Features/OnboardingTasks/Tasks/Marketing.php]: Nice catch! I removed the redundant condition in commit 48a3724

**Comment by octaedro** [comment]
Thank you @joelclimbsthings for the review, I addressed the change you mentioned.
Could you take another look at this PR?

**Review by joelclimbsthings — APPROVED** [review]
Right on @octaedro , looks great! 🚢
