### PR TITLE
Fix some issues in performance tests

### LINKED ISSUE #47782: [Performance tests]: Problem with the typing tests
### Describe the bug

The PR #47590 added some performance tests to the product editor.
The tour that we showed the first time the product editor was loaded was affecting the typing tests.

We should dismiss the tour when it's visible.

### PR DESCRIPTION
**Pull request by octaedro**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

This PR fixes some issues in the performance tests. 

- The tour that appeared when opening the product editor for the first time was affecting the typing tests.
- It also collects more data in the editor tests.

Closes #47782.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. To run this process, you will have to run the following commands
```
cd plugins/woocommerce
pnpm test:metrics
```

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Comment 

</details>

### CODE REVIEW

**Review by mdperez86 — APPROVED** [review]
LGTM @octaedro nice job!!!

File: tools/compare-perf/performance.js [hunk 1]
```diff
@@ -368,7 +368,7 @@ async function runPerformanceTests( branches, options ) {
 			const resultsRounds = resultFiles
 				.filter( ( file ) =>
 					file.includes(
-						`${ testSuite }_${ sanitizedBranchName }_round-`
+						`/${ testSuite }_${ sanitizedBranchName }_round-`
```
Comment (octaedro) [inline tools/compare-perf/performance.js:371]: Since we have two test suites, one for the `editor` and another one for the `product editor`, we added a slash "/" here because `editor` was included in `editor_trunk_round-` and in `product-editor_trunk_round-`.

File: plugins/woocommerce/tests/metrics/specs/editor.spec.js [hunk 2]
```diff
@@ -95,8 +95,32 @@ test.describe( 'Editor Performance', () => {
...
+					results.totalBlockingTime = results.tbt || [];
+					results.totalBlockingTime.push( totalBlockingTime );
+					results.cumulativeLayoutShift =
+						results.cumulativeLayoutShift || [];
+					results.cumulativeLayoutShift.push( cumulativeLayoutShift );
+					results.largestContentfulPaint =
+						results.largestContentfulPaint || [];
+					results.largestContentfulPaint.push(
+						largestContentfulPaint
+					);
```
Comment (octaedro) [inline plugins/woocommerce/tests/metrics/specs/editor.spec.js:123]: This adds the metrics for `totalBlockingTime`, `cumulativeLayoutShift`, `largestContentfulPaint` and `largestContentfulPaint` to the Editor tests suite.

**Comment by octaedro** [comment]
Hi @youknowriad,

Could you take a look at this PR?

It adds [some metrics](https://github.com/woocommerce/woocommerce/pull/47735#discussion_r1622515197) to the `editor` tests, fixes the error [you mentioned about](https://github.com/woocommerce/woocommerce/pull/47590#issuecomment-2123483493) the type metric, and fixes a small problem in the action [here](https://github.com/woocommerce/woocommerce/pull/47735/files#r1622510045).

If you think that everything here looks correct, could you add the metrics: `totalBlockingTime`, `cumulativeLayoutShift`, `largestContentfulPaint`, `firstPaint`, `domContentLoaded`, `loaded`  and `serverResponse`, for the editor and the product editor in Code Vitals?

Please let me know if we need extra changes on the tests or if anything looks incorrect.

**Comment by youknowriad** [comment]
Sorry for the late reply here. I'm happy to add these metrics to your dashboard. Note that in Gutenberg, we found that some of these server "loading metrics" (domContentLoaded, loaded, serverResponse, firstPaint, largestContentfulPaint) were not very helpful for us (and can be unstable at time) so we chose not to track them but ultimately it's your decision, you choose what's important for you to track and address. I'm happy to add all of them if you like.

**Comment by octaedro** [comment]
Thank you @youknowriad. Got it!

If it's okay with you, I think it would be great to add the metrics: `totalBlockingTime`, `cumulativeLayoutShift`, and `largestContentfulPaint` to Code Vitals. Then, we can analyze whether they are correct and continue improving the way we measure them on the WC side.

**Comment by youknowriad** [comment]
Understood, metrics added to the dashboard.

**Comment by octaedro** [comment]
Thank you @youknowriad!
