### PR TITLE
Accessibility: add global event handler for anchors with button role triggering the click on spacebar keydown

### LINKED ISSUE #59542: [Accessibility] JavaScript needed for adding spacebar support to links with a role of button
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

The full screen popup trigger button has been remediated to be a button, however it cannot be triggered via the space bar, as is expected for a button.

`<a href="#" role="button" class="woocommerce-product-gallery__trigger" aria-haspopup="dialog" aria-label="View full-screen image gallery"><span aria-hidden="true">🔍</span></a>`

This came up in the composite products extensions audit for a similar link and @PanosSynetos suggested that this should be fixed in core in a way that any link with a role of button, either this one or ones that exist in extensions, will automatically have space bar functionality.
>  I think this JS should be core, where ALL  document.querySelectorAll('a[role="button"]'); should react on space, not just enter.

### Expected behavior

When links are remediated to announce as buttons, they should also function as a button and be able to be triggered with the spacebar. 

See [MDN Web Docs ARIA: button role](ARIA: button role) for additional information.

The implementation should be broad enough that it adds spacebar support to all links with a role of button, even those created by extensions.

### Actual behavior

Pressing the space bar when focused on the product gallery trigger scrolls the page instead of opening the lightbox.

### Steps to reproduce

1. Go to https://woo.equalizedigital.com/product/extra-tough-hardware/ (password: wooa11y)
2. Tab to the magnifying glass.
3. Press the space bar and observe that it does not trigger the modal.

### WordPress Environment

`
--
### wp-core ###
 
version: 6.8.1
site_language: en_US
user_language: en_US
timezone: America/Chicago
permalink: /%postname%/
https_status: true
multisite: false
user_registration: 0
blog_public: 0
default_comment_status: open
environment_type: production
user_count: 9
dotorg_communication: true
 
### wp-paths-sizes ###
 
wordpress_path: /home2/amberhin/public_html/website_f5ae36ad
wordpress_size: 57.63 MB (60432205 bytes)
uploads_path: /home2/amberhin/public_html/website_f5ae36ad/wp-content/uploads
uploads_size: 1.01 MB (1059230 bytes)
themes_path: /home2/amberhin/public_html/website_f5ae36ad/wp-content/themes
themes_size: 19.95 MB (20916426 bytes)
plugins_path: /home2/amberhin/public_html/website_f5ae36ad/wp-content/plugins
plugins_size: 99.73 MB (104572087 bytes)
fonts_path: /home2/amberhin/public_html/website_f5ae36ad/wp-content/uploads/fonts
fonts_size: directory not found
database_size: 13.11 MB (13746176 bytes)
total_size: 191.43 MB (200726124 bytes)
 
### wp-active-theme ###
 
name: Twenty Twenty-Five (twentytwentyfive)
version: 1.2
author: the WordPress team
author_website: https://wordpress.org
parent_theme: none
theme_features: core-block-patterns, post-thumbnails, responsive-embeds, editor-styles, html5, automatic-feed-links, widgets-block-editor, block-templates, post-formats, editor-style
theme_path: /home2/amberhin/public_html/website_f5ae36ad/wp-content/themes/twentytwentyfive
auto_update: Enabled
 
### wp-themes-inactive (3) ###
 
Twenty Twenty-Four: version: 1.3, author: the WordPress team, Auto-updates enabled
Twenty Twenty-Three: version: 1.6, author: the WordPress team, Auto-updates enabled
Twenty Twenty-Two: version: 2.0, author: the WordPress team, Auto-updates enabled
 
### wp-mu-plugins (1) ###
 
SSO: version: 0.5, author: Garth Mortensen, Mike Hansen
 
### wp-plugins-active (17) ###
 
Disable Emails: version: 1.8.2, author: WebAware, Auto-updates enabled
Password Protected: version: 2.7.8, author: Password Protected, Auto-updates enabled
PU2 DevTools: author: (undefined), version: (undefined), Auto-updates enabled
The Bluehost Plugin: version: 4.4.0, author: Bluehost, Auto-updates enabled
UpdraftPlus - Backup/Restore: version: 1.25.6, author: TeamUpdraft, DavidAnderson, Auto-updates enabled
User Switching: version: 1.9.2, author: John Blackbourn, Auto-updates enabled
WooCommerce: version: 10.0.0-rc.1, author: Automattic, Auto-updates enabled
WooCommerce Back In Stock Notifications: version: 3.3.100-dev, author: Woo, Auto-updates enabled
WooCommerce Composite Products: version: 10.5.0, author: Woo, Auto-updates enabled
WooCommerce Conditional Shipping and Payments: version: 2.2.0, author: Woo, Auto-updates enabled
WooCommerce Gift Cards: version: 2.5.0, author: Woo, Auto-updates enabled
WooCommerce Min/Max Quantities: version: 5.2.5, author: Woo, Auto-updates enabled
WooCommerce Product Add-Ons: version: 7.9.0, author: Woo, Auto-updates enabled
WooCommerce Product Bundles: version: 8.4.0, author: Woo, Auto-updates enabled
WooCommerce Smooth Generator: version: 1.2.0, author: Automattic, Auto-updates enabled
WooCommerce Stripe Gateway: version: 9.5.3, author: Stripe, Auto-updates enabled
WP Mail Logging: version: 1.14.0, author: WP Mail Logging Team, Auto-updates enabled
 
### wp-plugins-inactive (3) ###
 
Akismet Anti-spam: Spam Protection: version: 5.4, author: Automattic - Anti-spam Team, Auto-updates enabled
Jetpack: version: 14.8, author: Automattic, Auto-updates enabled
WooCommerce Product Recommendations: version: 4.1.5, author: Woo, Auto-updates enabled
 
### wp-media ###
 
image_editor: WP_Image_Editor_Imagick
imagick_module_version: 1690
imagemagick_version: ImageMagick 6.9.10-68 Q16 x86_64 2024-11-12 https://imagemagick.org
imagick_version: 3.4.3
file_uploads: 1
post_max_size: 516M
upload_max_filesize: 512M
max_effective_size: 512 MB
max_file_uploads: 20
imagick_limits:
imagick::RESOURCETYPE_AREA: 85 GB
imagick::RESOURCETYPE_DISK: 9223372036854775807
imagick::RESOURCETYPE_FILE: 12288
imagick::RESOURCETYPE_MAP: 48 MB
imagick::RESOURCETYPE_MEMORY: 48 MB
imagick::RESOURCETYPE_THREAD: 1
imagick::RESOURCETYPE_TIME: 300
imagemagick_file_formats: 3FR, 3G2, 3GP, AAI, AI, ART, ARW, AVI, AVS, BGR, BGRA, BGRO, BMP, BMP2, BMP3, BRF, CAL, CALS, CANVAS, CAPTION, CIN, CIP, CLIP, CMYK, CMYKA, CR2, CRW, CUR, CUT, DATA, DCM, DCR, DCX, DDS, DFONT, DNG, DOT, DPX, DXT1, DXT5, EPDF, EPI, EPS, EPS2, EPS3, EPSF, EPSI, EPT, EPT2, EPT3, ERF, EXR, FAX, FILE, FITS, FRACTAL, FTP, FTS, G3, G4, GIF, GIF87, GRADIENT, GRAY, GRAYA, GROUP4, GV, H, HALD, HDR, HISTOGRAM, HRZ, HTM, HTML, HTTP, HTTPS, ICB, ICO, ICON, IIQ, INFO, INLINE, IPL, ISOBRL, ISOBRL6, J2C, J2K, JNG, JNX, JP2, JPC, JPE, JPEG, JPG, JPM, JPS, JPT, JSON, K25, KDC, LABEL, M2V, M4V, MAC, MAGICK, MAP, MASK, MAT, MATTE, MEF, MIFF, MKV, MNG, MONO, MOV, MP4, MPC, MPEG, MPG, MRW, MSL, MSVG, MTV, MVG, NEF, NRW, NULL, ORF, OTB, OTF, PAL, PALM, PAM, PANGO, PATTERN, PBM, PCD, PCDS, PCL, PCT, PCX, PDB, PDF, PDFA, PEF, PES, PFA, PFB, PFM, PGM, PGX, PICON, PICT, PIX, PJPEG, PLASMA, PNG, PNG00, PNG24, PNG32, PNG48, PNG64, PNG8, PNM, PPM, PREVIEW, PS, PS2, PS3, PSB, PSD, PTIF, PWP, RADIAL-GRADIENT, RAF, RAS, RAW, RGB, RGBA, RGBO, RGF, RLA, RLE, RMF, RW2, SCR, SCT, SFW, SGI, SHTML, SIX, SIXEL, SPARSE-COLOR, SR2, SRF, STEGANO, SUN, SVG, SVGZ, TEXT, TGA, THUMBNAIL, TIFF, TIFF64, TILE, TIM, TTC, TTF, TXT, UBRL, UBRL6, UIL, UYVY, VDA, VICAR, VID, VIFF, VIPS, VST, WBMP, WMF, WMV, WMZ, WPG, X, X3F, XBM, XC, XCF, XPM, XPS, XV, XWD, YCbCr, YCbCrA, YUV
gd_version: bundled (2.1.0 compatible)
gd_formats: GIF, JPEG, PNG, WebP, BMP, XPM
ghostscript_version: 9.25
 
### wp-server ###
 
server_architecture: Linux 4.19.286-203.ELK.el7.x86_64 x86_64
httpd_software: Apache
php_version: 7.4.33 64bit
php_sapi: litespeed
max_input_variables: 1000
time_limit: 60
memory_limit: 512M
max_input_time: 60
upload_max_filesize: 512M
php_post_max_size: 516M
curl_version: 8.7.1 OpenSSL/1.1.1w
suhosin: false
imagick_availability: true
pretty_permalinks: true
htaccess_extra_rules: true
static_robotstxt_file: false
current: 2025-07-07T18:22:20+00:00
utc-time: Monday, 07-Jul-25 18:22:20 UTC
server-time: 2025-07-07T13:22:19-05:00
 
### wp-database ###
 
extension: mysqli
server_version: 5.7.23-23
client_version: mysqlnd 7.4.33
max_allowed_packet: 268435456
max_connections: 150
 
### wp-constants ###
 
WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: /home2/amberhin/public_html/website_f5ae36ad/wp-content
WP_PLUGIN_DIR: /home2/amberhin/public_html/website_f5ae36ad/wp-content/plugins
WP_MEMORY_LIMIT: 40M
WP_MAX_MEMORY_LIMIT: 512M
WP_DEBUG: false
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: false
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_ENVIRONMENT_TYPE: undefined
WP_DEVELOPMENT_MODE: undefined
DB_CHARSET: utf8
DB_COLLATE: utf8_unicode_ci
 
### wp-filesystem ###
 
wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable
fonts: does not exist
mu-plugins: writable
 
`

### Isolating the problem

- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by kmanijak**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

When links are remediated to announce as buttons, they should also function as a button and be able to be triggered with the spacebar. It's not necessarily a case and this came up in the composite products extensions audit, however, similar case(s) were found in WooCommerce core.

In this PR, I'm adding a global event handler for all `a[role="button"]`, that triggers click on those elements as a response to spacebar keydown.

In addition, I found few instances where it was explicitly attached to some anchors with button role. I removed those as it's handled globally now. This should also handle extensions and elements added after page load thanks to single event listener at the top.

Closes https://github.com/woocommerce/woocommerce/issues/59542

(For Bug Fixes) Bug introduced in PR # .

### Screenshots or screen recordings:

| Before | After |
| ------ | ----- |
|     https://github.com/user-attachments/assets/c1fc336e-1e98-48f8-99fc-f777b56ef298   |      https://github.com/user-attachments/assets/33b3c0c3-3722-42dd-8beb-18f649c16ba5 |

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

#### Product Image Gallery - magnifying glass (bugfix testing)

1. Go to Editor > Single Product
2. Make sure you use Product Image Gallery block
3. Go to frontend
4. Use tab to focus on magnifying glass icon on gallery
5. Press spacebar
6. **Expected:** lightbox gallery opens
7. Close with escape and press enter
8. **Expected:** lightbox gallery opens

image

#### Classic Cart - remove product (regression testing)

1. Go to Editor > Page: Cart
2. Remove content and add Classic Cart
4. Go to frontend
5. Add some products to cart and go to cart
6. Use tab to focus on "X" button next to product
7. Press spacebar
8. **Expected:** product gets removed from cart
10. Focus on another one and press enter
11. **Expected:** product gets removed from cart

image

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce/client/legacy/js/frontend/woocommerce.js [hunk 1]
```diff
@@ -22,31 +31,22 @@ jQuery( function ( $ ) {
 		$( '.woocommerce-store-notice' ).hide();
 	} else {
 		$( '.woocommerce-store-notice' ).show();
-		/**
-		 * After adding the role="button" attribute to the 
-		 * .woocommerce-store-notice__dismiss-link element, 
-		 * we need to add the keydown event listener to it.
-		 */
-		function store_notice_keydown_handler( event ) {
-			if ( ['Enter', ' '].includes( event.key ) ) {
```
Comment (kmanijak) [inline plugins/woocommerce/client/legacy/js/frontend/woocommerce.js:31]: Enter is handled on anchors by default, no matter the role so it's ok to remove.

**Review by PanosSynetos — APPROVED** [review]
Hey @kmanijak - Thanks for this. I'll leave the code review to people with more experience on a11y, but I tested this branch against Composite Products, and I can verify that space and enter works when opening the gallery for a component

I also checked with simple product's gallery, and verified it works.

Compared to trunk, the gallery only opened with enter.

File: plugins/woocommerce/client/legacy/js/frontend/woocommerce.js [hunk 2]
```diff
@@ -14,6 +14,15 @@ jQuery( function ( $ ) {
...
 	} );
 
+	// Global accessibility handler for all links with role="button"
+	// This ensures both spacebar and enter keypresses trigger click events, as per ARIA specification
+	$( document.body ).on( 'keydown', 'a[role="button"]', function ( event ) {
+		if ( event.key === ' ' || event.key === 'Enter' ) {
+			event.preventDefault();
+			$( this ).trigger( 'click' );
+		}
+	} );
```
Comment (Aljullu) [inline plugins/woocommerce/client/legacy/js/frontend/woocommerce.js]: Should we take the opportunity to rewrite this in vanilla JS?

**Review by Aljullu — COMMENTED** [review]
Changes look good to me. I'm a bit wary of adding an event to all `a[role="button"]` elements, as some of them might not be generated by WooCommerce, but I guess it's fine considering that's the expected behavior for accessibility reasons.

I tested the following links, and all of them worked well:

✅ Product Image Gallery magnifier button
✅ Demo store notice close button
✅ Cart widget remove from cart button

I only left one comment inline, I think we could take the opportunity to rewrite that code in vanilla JS and, in this way, clean up a bit of jQuery code.

File: plugins/woocommerce/client/legacy/js/frontend/woocommerce.js (hunk 2 above)
Comment (kmanijak) [reply plugins/woocommerce/client/legacy/js/frontend/woocommerce.js]: TBH I felt obliged to use jQuery to keep it consistent with the rest of the file 😂 But why not!

Comment (kmanijak) [reply plugins/woocommerce/client/legacy/js/frontend/woocommerce.js]: Done in https://github.com/woocommerce/woocommerce/pull/59578/commits/d9af7d0e7e77ff612e9c0f6c06e20f7199d95964. Do you want to double check or you're good with me merging?

Comment (Aljullu) [reply plugins/woocommerce/client/legacy/js/frontend/woocommerce.js]: Tested again and it works fine on my end. :ship:
