### PR TITLE
[Experimental] Product Filters - Fix attributes sort order not working

### LINKED ISSUE #56042: [Experimental] Product filters - Attributes sort order not working
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Changing the Sort Order settings for the Product Filters (Experimental) - Attributes filter is not reflected on the frontend. The editor side however does work. I have attached a reference image of what I am referring to:

Image

### Expected behavior

I expect the sort order to be displayed in the frontend as it is set in the editor.

### Actual behavior

The sort order is always in the default state.

### Steps to reproduce

> [!NOTE]  
> **Pre-requisite**
> - If you're using WC Beta Tester plugin, make sure the `experimental-blocks` feature is enabled (Tools > WCA Test Helper > Features).
> - Make sure to reset Product Catalog Template.

1. Go to the Product Catalog Template
2. Add the Product Filters (Experimental) to the editor
3. Select the Attributes Filter (Color)
4. In the inspector controls change the Sort Order to "Name, Z to A"
5. Ensure you see the attributes update in the editor
6. Save and go to the frontend
7. The sort order is still showing as default

### WordPress Environment

<details><summary>System Status Report</summary>

```
### WordPress Environment ###

WordPress address (URL): [Redacted]
Site address (URL): [Redacted]
WC Version: 9.9.0-dev
Legacy REST API Package Version: The Legacy REST API plugin is not installed on this site.
Action Scheduler Version: ✔ 3.9.2
Log Directory Writable: ✔
WP Version: 6.7.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.26.1
PHP Version: 8.1.23
PHP Post Max Size: 1,000 MB
PHP Time Limit: 1200
PHP Max Input Vars: 4000
cURL Version: 8.7.1
(SecureTransport) LibreSSL/3.3.6

SUHOSIN Installed: –
MySQL Version: 8.0.16
Max Upload Size: 300 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

[REDACTED]

### Post Type Counts ###

attachment: 37
aw_workflow: 1
elementor_library: 1
global_product_addon: 1
guides: 1
page: 13
post: 5
product: 19
product_variation: 7
revision: 186
shop_order: 4
shop_order_placehold: 4
wp_block: 1
wp_font_face: 33
wp_font_family: 12
wp_global_styles: 6
wp_navigation: 1
wp_template: 9
wp_template_part: 5

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (6) ###

Code Snippets: by Code Snippets Pro – 3.6.8
Plugin Check (PCP): by WordPress Performance Team and Plugin Review Team – 1.4.0
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 3.1.6
SMNTCS Show Symlinked Plugins: by Niels Lange – 1.3
WooCommerce Beta Tester: by WooCommerce – 3.0.0
WooCommerce: by Automattic – 9.9.0-dev

### Inactive Plugins (25) ###

Akismet Anti-spam: Spam Protection: by Automattic - Anti-spam Team – 5.3.7
Block Visibility: by Nick Diego – 3.7.1
Classic Editor: by WordPress Contributors – 1.6.7
CoBlocks: by GoDaddy – 3.1.14
Core Rollback: by Andy Fragen – 1.3.7
Debug Bar: by wordpressdotorg – 1.1.6
Enable Responsive Image: by Aki Hamano – 1.3.0
Gutenberg: by Gutenberg Team – 20.3.0
Hello Dolly: by Matt Mullenweg – 1.7.2
Jetpack: by Automattic – 14.3
Loco Translate: by Tim Whitlock – 2.7.1
Mail logging - WP Mail Catcher: by James Ward – 2.1.10
Myhook: by The WordPress Contributors – 0.1.0
RTL Tester: by <a href="http://blog.yoavfarhi.com">Yoav Farhi</a>
<a href="http://automattic.com">Automattic</a> – 1.2

Say What?: by Ademti Software – 2.2.5
Woo Blocks Bindings: by The WordPress Contributors – 0.1.0
WooCommerce Additional Variation Images: by WooCommerce – 2.3.2
WooCommerce PayPal Payments: by WooCommerce – 2.9.6
WooCommerce Shipping & Tax: by WooCommerce – 2.8.7
WooCommerce Stripe Gateway: by Stripe – 9.2.0
WooPayments: by WooCommerce – 9.0.0
WordPress Beta Tester: by WordPress Upgrade/Install Team – 3.6.2
WordPress Importer: by wordpressdotorg – 0.8.3
WP-Optimize - Clean, Compress, Cache: by TeamUpdraft
DavidAnderson – 4.0.1

WP Debugging: by Andy Fragen – 2.12.2

### Settings ###

Legacy API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: bundle (bundle)
composite (composite)
external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 450 KB

### WC Pages ###

Shop base: #6 - /shop/
Cart: #7 - /cart/ -  Contains the woocommerce/cart block
Checkout: #8 - /checkout/ -  Contains the woocommerce/checkout block
My account: #9 - /my-account/ -  This page's content is overridden by custom template content
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty-Four
Version: 1.3
Author URL: https://wordpress.org
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
Theme type: Block theme
WooCommerce Support: ❌ Not declared

### Templates ###

Overrides: /Users/royho/projects/woocommerce-monorepo/plugins/woocommerce/templates/block-notices/error.php
/Users/royho/projects/woocommerce-monorepo/plugins/woocommerce/templates/block-notices/notice.php
/Users/royho/projects/woocommerce-monorepo/plugins/woocommerce/templates/block-notices/success.php


### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
experimental-blocks
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
minified-js
mobile-app-banner
onboarding
onboarding-tasks
pattern-toolkit-full-composability
payment-gateway-suggestions
product-custom-fields
printful
remote-inbox-notifications
remote-free-extensions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page
async-product-editor-category-field
launch-your-store
add-to-cart-with-options-stepper-layout
blockified-add-to-cart
beta-tester-slotfill-examples

Disabled Features: product-data-views
coming-soon-newsletter-template
product-pre-publish-modal
settings
product-editor-template-system
reactify-classic-payments-settings
use-wp-horizon

Daily Cron: ✔ Next scheduled: 2025-03-04 18:27:05 +00:00
Options: ✔
Notes: 110
Onboarding: skipped

### Action Scheduler ###

Complete: 97
Oldest: 2025-01-31 20:53:28 +0000
Newest: 2025-03-03 16:23:52 +0000

Failed: 2
Oldest: 2023-12-23 18:41:51 +0000
Newest: 2024-11-13 15:04:00 +0000

Pending: 1
Oldest: 2025-03-04 00:10:04 +0000
Newest: 2025-03-04 00:10:04 +0000


### Status report information ###

Generated at: 2025-03-03 20:07:37 +00:00
```
</details>

### Isolating the problem

- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by roykho**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes #56042 

This PR fixes the issue for the attributes filter sort order not displaying as expected on the frontend.

### Screenshots or screen recordings:

(SORT ORDER: Name, Z to A )

| Before | After |
| ------ | ----- |
|CleanShot 2025-03-04 at 05 43 59|CleanShot 2025-03-04 at 05 43 36|

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

> [!NOTE]  
> **Pre-requisite**
> - If you're using WC Beta Tester plugin, make sure the `experimental-blocks` feature is enabled (Tools > WCA Test Helper > Features).
> - Make sure to reset Product Catalog Template.

1. Navigate to Product Catalog template (Appearance > Editor > Templates > Product Catalog template.
2. Add the Product Filters (Experimental) block to the page.
3. Select the Attributes Filter Block (Color).
4. In the inspector controls, try changing the SORT ORDER setting.
5. Save and go to the frontend and ensure the attributes filter is displaying per the sort order you chose.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce/src/Blocks/BlockTypes/ProductFilterAttribute.php [hunk 1]
```diff
@@ -166,19 +166,25 @@ protected function render( $block_attributes, $content, $block ) {
...
 		} else {
 			$attribute_terms = get_terms(
 				array(
 					'taxonomy'   => $product_attribute->slug,
 					'hide_empty' => false,
+					'orderby'    => $orderby,
+					'order'      => $order,
 				)
 			);
 		}
```
Comment (kmanijak) [inline plugins/woocommerce/src/Blocks/BlockTypes/ProductFilterAttribute.php]: I know it's not in scope of this PR but I can't help but notice the duplication in this `if else` statement. Super nitpick but you could consider something like:

```suggestion
		$args = array(
			'taxonomy' => $product_attribute->slug,
			'orderby'  => $orderby,
			'order'    => $order,
		);

		if ( $hide_empty ) {
			$args['include'] = array_keys( $attribute_counts );
		} else {
			$args['hide_empty'] = false;
		}

		$attribute_terms = get_terms( $args );
```

Leaving it up to you to decide.

**Review by kmanijak — COMMENTED** [review]
Hmm.. I can't make the filters working.

- When using `pnpm --filter='@woocommerce/plugin-woocommerce' watch:build` I'm getting console errors and filters don't display in the frontend at all:

Console | Frontend
-- | --
image | image

- When using `pnpm build` there's no console errors but filters don't really work:
image

To be fair, filters can be inserted just fine in the editor

image

Any idea what am I doing wrong? 😅

**Comment by roykho** [comment]
@kmanijak hmmm interesting. WP 6.7? What theme? And if you go to the frontend source, do you see `wcSettings`?

CleanShot 2025-03-05 at 06 40 16

**Review by kmanijak — APPROVED** [review]
Thanks for addressing the other comment!

Tested the PR and sorting works just fine:

A to Z | Z to A | Least results first
-- | -- | --
image | image | image
