### PR TITLE
Avoid lists of one Express Payment options.

### LINKED ISSUE #60556: Accessibility: Express Payments Buttons Container can contain a list of one.
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Originally reported as WOOPYBR-66.

> The container that holds the express payments iframe is incorrectly coded as a list and is announced as a list of one item, though visually it is multiple items (a link-styled button and two different PayPal buttons). 
> 
> The list semantics add unnecessary noise for screen reader users and may cause confusion.
> 
> **Component or Page:**
> 
> Cart
> 
> **Affected Element:**
> 
> Express Payments Buttons Container
> 
> **Relevant Code Snippet:**
> 
> ```html
> <ul class="wc-block-components-express-payment__event-buttons"><li id="express-payment-method-braintree_paypal_express"><div class=""><div class="" aria-hidden="false"><div id="wc-braintree-paypal-pay-later-messaging-container" data-pp-id="1">
> 
> [...]
> 
> </div></li></ul>
> ```
> 
> **Recommended Fix:**
> 
> Change the container from a list of one item to a non-semantic container for the iframe, such as a div.

I think the solution is to modify this block of code to use lists for multiple express payment methods and `divs` when their is only one payment method.

https://github.com/woocommerce/woocommerce/blob/f8435947eb91ac3588f0470dfe98067dfbe93135/plugins/woocommerce/client/blocks/assets/js/blocks/cart-checkout-shared/payment-methods/express-payment-methods.tsx#L160-L192

### Expected behavior

Lists of one should not exist as they add noise for users of assistive technology

### Actual behavior

Express payments use a list of one

### Steps to reproduce

1. Enable a gateway that uses express payment methods, eg [Braintree for WooCommerce Payment Gateway](https://wordpress.org/plugins/woocommerce-gateway-paypal-powered-by-braintree/)
2. Configure gateway to enable a single express payment method (for Braintreee, this means leaving Apple Pay off and enabling the PayPal buttons)
3. Add a product to the cart
4. Proceed to the cart
5. Observe the express pay button is a list of one.

### WordPress Environment

Unsure of environment this was originally tested on, I've been able to reproduce it with the one below

<details><summary>System Status Report</summary>

```
### WordPress Environment ###

WordPress address (URL): [Redacted]
Site address (URL): [Redacted]
WC Version: 10.1.0
Legacy REST API Package Version: The Legacy REST API plugin is not installed on this site.
Action Scheduler Version: ✔ 3.9.3
Log Directory Writable: ✔
WP Version: 6.9-alpha-60655
WP Multisite: ✔
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: –
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.18.0
Server Architecture: Linux 5.15.0-92-generic aarch64
PHP Version: 8.3.20
PHP Post Max Size: 2 GB
PHP Time Limit: 900
PHP Max Input Vars: 1000
cURL Version: 7.81.0
OpenSSL/3.0.2

SUHOSIN Installed: –
MySQL Version: 8.0.36-0ubuntu0.22.04.1
Max Upload Size: 0 B
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

[REDACTED]

### Post Type Counts ###

attachment: 7
page: 6
post: 2
product: 2
revision: 2
shop_order_placehold: 4
wp_global_styles: 1
wp_navigation: 2
wp_template_part: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (5) ###

Query Monitor: by John Blackbourn – 3.19.0
User Switching: by John Blackbourn – 1.10.0
Braintree for WooCommerce Payment Gateway: by WooCommerce – 3.2.9
WooCommerce Subscriptions: by WooCommerce – 7.5.0
WooCommerce: by Automattic – 10.1.0 (update to version 10.1.1 is available)

### Inactive Plugins (22) ###

Airplane Mode: by Andrew Norcross – 0.2.5
Google for WooCommerce: by WooCommerce – 3.3.1
Loco Translate: by Tim Whitlock – 2.8.0
WooCommerce Accommodation Bookings: by WooCommerce – 1.3.4
WooCommerce Bookings: by WooCommerce – 2.2.8
WooCommerce Bookings Availability: by WooCommerce – 1.3.0
WooCommerce Box Office: by WooCommerce – 1.3.6
WooCommerce Bulk Stock Management: by WooCommerce – 2.3.0
WooCommerce Deposits: by WooCommerce – 2.4.0
WooCommerce Dummy Payments Gateway: by Woo – 1.10.0
WooCommerce EU VAT Number: by WooCommerce – 2.9.16
WooCommerce Payfast Gateway: by WooCommerce – 1.7.3
WooCommerce Pre-Orders: by WooCommerce – 2.2.9
WooCommerce Product Bundles: by Woo – 8.4.2
WooCommerce Product CSV Import Suite: by WooCommerce – 1.10.78
WooCommerce Product Vendors: by WooCommerce – 2.4.6
WooCommerce Purchase Order Payment Gateway: by WooCommerce – 1.5.4
WooCommerce Square: by WooCommerce – 4.9.7 (update to version 4.9.8 is available)
WooCommerce Stripe Gateway: by Stripe – 9.8.0
WooCommerce Xero Integration: by WooCommerce – 1.9.6
WooPayments: by WooCommerce – 9.8.0
WP Dev Tools: by Peter Wilson – 1.0.0

### Dropin Plugins () ###

db.php: Query Monitor Database Class (Drop-in)

### Must Use Plugins (16) ###

add-site-id-to-admin-menu.php: by  –
Cavalcade-loader.php: by  –
deposits-cart-stuff.php: by  –
filter-bookings-my-account-endpoint.php: by  –
more-products-per-page.php: by  –
no-ssl.php: by  –
pre-orders-fast-schedule.php: by  –
Preload options used by Woo that do not use autoload.: by  –
Rapid Deposits.: by  –
rewrite-apple-pay.php: by  –
Unique order IDs: by  –
wpcli-dev-commands.php: by  –
Xero - Mock API Rate Limiting: by  –
_init-as-live-store.php: by  –
_no-log-doing-wrong-i18n.php: by  –
_qm-mappings.php: by  –

### Settings ###

Legacy API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –
Enabled Features: analytics
marketplace
order_attribution
site_visibility_badge
remote_logging
email_improvements
blueprint
point_of_sale
custom_order_tables


### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 383 KB

### WC Pages ###

Shop base: #5 - /shop/
Cart: #81 - /cart/ -  Contains the woocommerce/cart block
Checkout: #82 - /checkout/ -  Contains the woocommerce/checkout block
My account: #8 - /my-account/ -  Contains the [woocommerce_my_account] shortcode
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty-Five
Version: 1.3
Author URL: https://wordpress.org
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
Theme type: Block theme
WooCommerce Support: ❌ Not declared

### Templates ###

Overrides: /vagrant/content/plugins/woocommerce/templates/block-notices/error.php
/vagrant/content/plugins/woocommerce/templates/block-notices/notice.php
/vagrant/content/plugins/woocommerce/templates/block-notices/success.php


### Subscriptions ###

WCS_DEBUG: ✔ No
Subscriptions Mode: ✔ Live
Subscriptions Live URL: https://steady-starling-concrete.ngrok-free.app/paypal-braintree
Subscriptions-core Library Version: 8.3.0
Subscription Statuses: wc-cancelled: 1
wc-pending-cancel: 1

WooCommerce Account Connected: ❌ No

### Store Setup ###

Country / State: United States (US) — Iowa

### Subscriptions by Payment Gateway ###

Braintree (Credit Card): wc-cancelled: 1
Braintree (PayPal): wc-pending-cancel: 1

### Payment Gateway Support ###

Braintree (Credit Card): products
card_types
payment_form
tokenization
charge
charge-virtual
authorization
capture_charge
customer_decline_messages
refunds
voids
customer_id
add_payment_method
token_editor
apple_pay
subscriptions
subscription_suspension
subscription_cancellation
subscription_reactivation
subscription_amount_changes
subscription_date_changes
multiple_subscriptions
subscription_payment_method_change_customer
subscription_payment_method_change_admin

Braintree (PayPal): products
card_types
payment_form
tokenization
charge
charge-virtual
authorization
capture_charge
customer_decline_messages
refunds
voids
customer_id
add_payment_method
token_editor
subscriptions
subscription_suspension
subscription_cancellation
subscription_reactivation
subscription_amount_changes
subscription_date_changes
multiple_subscriptions
subscription_payment_method_change_customer
subscription_payment_method_change_admin


### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
onboarding
onboarding-tasks
pattern-toolkit-full-composability
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
printful
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page
launch-your-store
add-to-cart-with-options-stepper-layout

Disabled Features: product-data-views
experimental-blocks
experimental-iapi-mini-cart
experimental-iapi-runtime
coming-soon-newsletter-template
minified-js
product-pre-publish-modal
settings
async-product-editor-category-field
product-editor-template-system
use-wp-horizon
experimental-wc-rest-api

Daily Cron: ✔ Next scheduled: 2025-08-23 01:25:13 +00:00
Options: ✔
Notes: 77
Onboarding: completed

### Braintree (Credit Card) ###

Environment: Sandbox
Tokenization Enabled: ✔
Debug Mode: Save to Log

### Braintree (PayPal) ###

Environment: Sandbox
Tokenization Enabled: ✔
Debug Mode: Off

### Action Scheduler ###

Complete: 1
Oldest: 2025-12-03 00:00:17 +0000
Newest: 2025-12-03 00:00:17 +0000

Failed: 1
Oldest: 2025-07-07 04:04:03 +0000
Newest: 2025-07-07 04:04:03 +0000

Pending: 4
Oldest: 2025-08-23 00:17:37 +0000
Newest: 2025-12-03 12:00:17 +0000


### Status report information ###

Generated at: 2025-08-22 01:50:38 +00:00
```
</details>

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by peterwilsoncc**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Improves the accessibility of the Express Payment buttons on the Block Cart page by avoiding lists of one.

A list of one adds noise to screen readers as the list will be announced as containing "one item" (which isn't a list), whereas a user only needs to know if there are a list of options/items if there are multiple items available.

Closes #60556
Closes WOOPYBR-66
Supersedes PR #60559

(For Bug Fixes) Bug introduced in PR # .

### Screenshots or screen recordings:

Markup before:

```html
<ul class="wc-block-components-express-payment__event-buttons">
  <li id="express-payment-method-Dummy Express"><!-- item markup --></li>
</ul>
```

Markup after:

```html
<div class="wc-block-components-express-payment__event-buttons">
  <div id="express-payment-method-Dummy Express"><!-- item markup --></div>
</div>
```

### How to test the changes in this Pull Request:

I used the [Dummy Gateway](https://github.com/woocommerce/woocommerce-gateway-dummy) for testing this and hacked it to add a placeholder for express payment options.

In the plugin, I added the following to the footer of the `resources/js/frontend/index.js` file:

```js
import { registerExpressPaymentMethod } from '@woocommerce/blocks-registry';
registerExpressPaymentMethod( {
	name: 'Dummy Express',
	title: 'Dummy Express',
	description: 'A setence or two about your payment method',
	gatewayId: 'dummy',
	label: <div>label</div>,
	content: <div>Dummy Payment Express</div>,
	edit: <div>edit</div>,
	canMakePayment: () => true,
	paymentMethodId: 'dummy',
} );

// Remove when testing one payment gateway only.
registerExpressPaymentMethod( {
	name: 'Dummy Express 2',
	title: 'Dummy Express 2',
	description: 'A setence or two about your payment method',
	gatewayId: 'dummy',
	label: <div>label</div>,
	content: <div>Dummy Payment Express Two</div>,
	edit: <div>edit</div>,
	canMakePayment: () => true,
	paymentMethodId: 'dummy',
} );
```

1. Hack the dummy gateway as noted above
2. Run `npm i; npm run start` on the dummy gateway
3. Activate the dummy gateway plugin
4. Add a product to the cart
5. Proceed to the block cart
6. Inspect the markup to ensure the two express pay options display as a list.
7. Remove the second gateway from the dummy gateway test code & save.
8. Reload the cart page
9. Inspect the markup to ensure the one express pay option displays using divs.

### Testing that has already taken place:

As above

I also tested with the [Braintree gateway](https://wordpress.org/plugins/woocommerce-gateway-paypal-powered-by-braintree/) using a properly configured express payment option.

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [x] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

Accessibility: Avoid list of one for a single express pay option on the block cart page.

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce/client/blocks/assets/js/blocks/cart-checkout-shared/payment-methods/express-payment-methods.tsx [hunk 1]
```diff
@@ -157,14 +157,28 @@ const ExpressPaymentMethods = () => {
 	 * paymentMethodInterface itself also updates on most renders.
 	 */
 	const entries = Object.entries( paymentMethods );
+	/*
+	 * Define the elements used for the Express Payments markup.
+	 *
+	 * When multiple express payment options are available, this will use an
+	 * unordered list to display the each option.
```
Comment (dkotter) [inline plugins/woocommerce/client/blocks/assets/js/blocks/cart-checkout-shared/payment-methods/express-payment-methods.tsx]:
```suggestion
	 * unordered list to display each option.
```

**Review by dkotter — COMMENTED** [review]
This looks good to me. Ready for QA @ankitguptaindia @qasumitbagthariya

**Comment by qasumitbagthariya** [comment]
### QA/Test Report ✅ 
-------------

I have checked this PR in the `peterwilsoncc:fix/60556-a11y-express-payments-list-of-one` branch and changes working as expected.

> Inspect the markup to ensure the two express pay options display as a list. ✅

image


> Inspect the markup to ensure the one express pay option displays using divs. ✅

image


**Testing Environment** 

<Details>

- WordPress: 6.8.1
- Theme: Storefront 4.6.0
- WooCommerce - WooCommerce - Dev version with this fix specific branch.
- PHP: 8.0.30
- Web Server: Nginx 1.20.2
- Browser: Chrome 
- OS: macOS  15.2 
- Git Branch: [Manussakis:fix/43631](amesplant:fix/43628-view-button-orders-page)

</Details>

@vikrampm1 ready for the next step.

**Comment by vikrampm1** [comment]
@peterwilsoncc please move this PR out of the draft and we can then request review from the Woo team.

File: plugins/woocommerce/client/blocks/assets/js/blocks/cart-checkout-shared/payment-methods/express-payment-methods.tsx [hunk 2]
```diff
@@ -174,20 +188,20 @@ const ExpressPaymentMethods = () => {
 								deprecatedSetExpressPaymentError,
 							buttonAttributes,
 						} ) }
-					</li>
+					</ExpressPayItem>
 				) : null;
 			} )
 		) : (
-			<li key="noneRegistered">
+			<ExpressPayItem key="noneRegistered">
```
Comment (opr) [inline plugins/woocommerce/client/blocks/assets/js/blocks/cart-checkout-shared/payment-methods/express-payment-methods.tsx]: Minor nitpick, but this would always be `div` wouldn't it? This wouldn't render unless `entries` was 0 so maybe we can just use that to make this slightly easier for future code-readers.

**Review by opr — APPROVED** [review]
Thanks @peterwilsoncc this looks good, I tested with various gateways including dummy gateway, braintree, and Stripe, and combinations of these together.

Left one minor nitpick comment, feel free to address, or let me know if you won't and I'll merge.

Thanks!

File: plugins/woocommerce/client/blocks/assets/js/blocks/cart-checkout-shared/payment-methods/express-payment-methods.tsx (hunk 2 above)
Comment (peterwilsoncc) [reply plugins/woocommerce/client/blocks/assets/js/blocks/cart-checkout-shared/payment-methods/express-payment-methods.tsx]: > Minor nitpick, but this would always be `div` wouldn't it? This wouldn't render unless `entries` was 0 so maybe we can just use that to make this slightly easier for future code-readers.

This makes sense to me, I've push af5dad77fc7b01392a1495ad93dc557017ab74cc to address this.

File: plugins/woocommerce/client/blocks/assets/js/blocks/cart-checkout-shared/payment-methods/express-payment/cart-express-payment.js [hunk 3]
```diff
@@ -63,6 +63,19 @@ const CartExpressPayment = () => {
...
 	}
+	/*
+	 * Define the elements used for the Express Payments markup.
+	 *
+	 * When multiple express payment options are available, this will use an
+	 * unordered list to display each option.
+	 *
+	 * When only one express payment option is available, this will use a
+	 * non-sematic DIV for both the wrapper and the individual items. This
+	 * it to prevent accessibility issues caused by a list of one (which isn't
```
Comment (opr) [inline plugins/woocommerce/client/blocks/assets/js/blocks/cart-checkout-shared/payment-methods/express-payment/cart-express-payment.js]:
```suggestion
	 * non-semantic DIV for both the wrapper and the individual items. This
	 * is to prevent accessibility issues caused by a list of one (which isn't
```

File: plugins/woocommerce/client/blocks/assets/js/blocks/cart-checkout-shared/payment-methods/express-payment-methods.tsx [hunk 4]
```diff
@@ -157,14 +157,28 @@ const ExpressPaymentMethods = () => {
...
 	const entries = Object.entries( paymentMethods );
+	/*
+	 * Define the elements used for the Express Payments markup.
+	 *
+	 * When multiple express payment options are available, this will use an
+	 * unordered list to display each option.
+	 *
+	 * When only one express payment option is available, this will use a
+	 * non-sematic DIV for both the wrapper and the individual items. This
+	 * it to prevent accessibility issues caused by a list of one (which isn't
```
Comment (opr) [inline plugins/woocommerce/client/blocks/assets/js/blocks/cart-checkout-shared/payment-methods/express-payment-methods.tsx]:
```suggestion
	 * non-semantic DIV for both the wrapper and the individual items. This
	 * is to prevent accessibility issues caused by a list of one (which isn't
```

**Review by opr — COMMENTED** [review]
Hi @peterwilsoncc thanks - I just noticed coderabbit had some suggestions about adding tests, I think this would be a good idea, let me ask it to draft some, and you could apply them (or at least select what seems useful from there)

@coderabbitai please draft the tests suggested in your last review

There's also a lint error:

```
. lint:lang:js: /home/runner/work/woocommerce/woocommerce/plugins/woocommerce/client/blocks/assets/js/blocks/cart-checkout-shared/payment-methods/express-payment-methods.tsx
. lint:lang:js:   181:21  error  Replace `·key={·id·}·id={·`express-payment-method-${·id·}`·}` with `⏎↹↹↹↹↹↹key={·id·}⏎↹↹↹↹↹↹id={·`express-payment-method-${·id·}`·}⏎↹↹↹↹↹`  prettier/prettier
```

**Comment by opr** [comment]
@coderabbitai please draft the tests

**Comment by peterwilsoncc** [comment]
@opr Woah, I didn't know it was possible to ask the bot for help with tests. Very nice.

I'll review the drafts and see what I can figure out.

**Comment by peterwilsoncc** [comment]
@opr Sorry to ask something that probably should be obvious, how do I get the tests to run in the file `plugins/woocommerce/client/blocks/assets/js/blocks/cart-checkout-shared/payment-methods/express-payment/test/cart-express-payment.tsx`?

I tried running `pnpm test:e2e --ui` in the `plugins/woocommerce/client/blocks` but could not see the cart-checkout-shared block listed.

**Comment by peterwilsoncc** [comment]
OK, I think I figured it out: the bot is suggesting tests that were in the jest test suite but that was deprecated in a16fdf381661f114ce719d4b6773717019b00bdb although the test files appear to remain.

I've reviewed the tests in `plugins/woocommerce/client/blocks/tests/e2e/tests/{cart,checkout}` and can't find anything testing various configurations of the Express Payment methods so am unsure how to proceed.

**Comment by peterwilsoncc** [comment]
@coderabbitai please draft the tests using the playwright test suite.

**Comment by opr** [comment]
Hey @peterwilsoncc - I don't think these changes need e2e tests, you can run the test you've added by running:

`pnpm --filter=@woocommerce/block-library test:js -- plugins/woocommerce/client/blocks/assets/js/blocks/cart-checkout-shared/payment-methods/express-payment/test/cart-express-payment`

**Comment by peterwilsoncc** [comment]
I've added the tests.

The bot hallucinated where the component gets tested, it's in `plugins/woocommerce/client/blocks/assets/js/blocks/cart-checkout-shared/payment-methods/test/express-payment-methods.tsx`

The new tests will run correctly with `pnpm --filter=@woocommerce/block-library test:js -- plugins/woocommerce/client/blocks/assets/js/blocks/cart-checkout-shared/payment-methods/test/express-payment-methods.tsx`

I attempted to add a test for the single express payment item in the editor context but it started triggering errors in `Payment methods available > In a frontend context` so I left it alone.

**Review by opr — APPROVED** [review]
@peterwilsoncc thanks for working through the tests - I added one more (and pushed it)  so when CI is green we can merge this 👌🏼

**Comment by peterwilsoncc** [comment]
Thanks Thomas, I've rebased to branch to allow someone with write access to merge once the light goes green.

**Comment by opr** [comment]
Thanks a lot @peterwilsoncc  👏🏼
