### PR TITLE
Fix incorrect coming soon template path to editor if theme provides coming soon template

### LINKED ISSUE #53309: Coming Soon: Incorrect path to editor template if theme provides coming soon template
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

In WooCommerce > Settings > Site Visibility, there is an "Editor" text link direct to the Coming Soon template in the site editor.

This link is the wrong path if the active theme contains it's own Coming Soon template.

`site-editor.php?postType=wp_template&postId=woocommerce%2Fwoocommerce%2F%2Fcoming-soon&canvas=edit` is ok if the theme does not contain it's own version of the template.

If the theme does have it's own template, the path of the Editor link should be something like `site-editor.php?postId=themeslug%2F%2Fcoming-soon&postType=wp_template&canvas=edit`

The consequence of this is that if the user is presented with a different template to edit vs the template that is available when going via Site Editor > Templates.

### Expected behavior

.

### Actual behavior

.

### Steps to reproduce

.

### WordPress Environment

.

### Isolating the problem

- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by chihsuan**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

This PR enhances the Site Visibility settings by dynamically fetching the coming soon template ID using the WordPress core-data store. This improvement ensures that the link to the coming soon template in the Site Editor is correct.

Closes https://github.com/woocommerce/woocommerce/issues/53309

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Create a fresh site 
2. Go to the Site Visibility settings (`wp-admin/admin.php?page=wc-settings&tab=site-visibility`)
3. Confirm that the `Editor` link to the WooCommerce Coming Soon template
4. Upload and activate [twentytwentyfour-coming-soon.zip](https://github.com/user-attachments/files/19483763/twentytwentyfour-coming-soon.zip) theme
5. Go to the Site Visibility settings again
6. Confirm that the `Editor` link now points to the twentytwentyfour-coming-soon template (`/wp-admin/site-editor.php?postType=wp_template&postId=twentytwentyfour-coming-soon%2F%2Fcoming-soon&canvas=edit`)
7. Switch back to the default theme
8. Modify the coming soon template and save it
9. Switch to twentytwentyfour-coming-soon theme
10. Confirm that the `Editor` link still points to the modified coming soon template
11. Activate a classic theme, such as storefront
12. Confirm that Site Visibility settings display correctly without the `Editor` link

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

Fix the link to the coming soon template in the Site Editor

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

**Review by moon0326 — COMMENTED** [review]
Summarizing comment about my review goes here. 
___
#### Review checklist
| Parameter  | Result |
| ------------- | ------------- |
| Approach  | ✅ All good |
| Implementation  | ⚠️  Left a comment about the default link behavior. |
| Automated tests  | Not applicable |
| Naming  | ✅ All good |
| Typing  |   ✅ All good |
| Code comments  | Not applicable |
| Changelog  |   ✅ All good |
| Documentation  | ✅ All good |
| PR description  | ✅ All good |
| Testing instructions  | ✅ All good |
| Manual testing  | ✅ Works as expected | 
 
 
#### Scenarios tested
| Scenario  | Result | Screenshot |
| ------------- | ------------- | ------------- |
| Editor link works as expected  | ✅ Functionality worked correctly | |
| Editor link points to the twentytwentyfour coming soon template  | ✅ Functionality worked correctly |  |

File: plugins/woocommerce/client/admin/client/launch-your-store/settings/slotfill.js [hunk 1]
```diff
@@ -172,7 +178,9 @@ const SiteVisibility = () => {
 								{
 									a: createElement( 'a', {
 										target: '_blank',
-										href: COMING_SOON_PAGE_EDITOR_LINK,
+										href: getAdminLink(
+											`site-editor.php?postType=wp_template&postId=${ comingSoonTemplateId }&canvas=edit`
```
Comment (moon0326) [inline plugins/woocommerce/client/admin/client/launch-your-store/settings/slotfill.js]: What do you think about linking to the editor initially, and then updating the link once we have the comingSoonTemplateId value?

Right now, the 'You can customize your Coming Soon landing page via the Editor' link appears with a delay of about a second.


https://github.com/user-attachments/assets/06c71ab9-a648-44f8-bfc0-f2263fba5ee9

Comment (chihsuan) [reply plugins/woocommerce/client/admin/client/launch-your-store/settings/slotfill.js]: Good idea! I'll make the changes.

Comment (chihsuan) [reply plugins/woocommerce/client/admin/client/launch-your-store/settings/slotfill.js]: Updated in https://github.com/woocommerce/woocommerce/pull/56743/commits/e43be6643891f4d4358f35fe116a419c7e8438d5

Comment (moon0326) [reply plugins/woocommerce/client/admin/client/launch-your-store/settings/slotfill.js]: @chihsuan LGTM! ✅

**Review by moon0326 — APPROVED** [review]

**Review by psealock — COMMENTED** [review]
> 9. Confirm that the Editor link still points to modified coming soon template

When I switch back to the default theme, the editor link takes me to the default template. I made changes to text as well as background color of a random block and saved. Can you reproduce?

**Comment by chihsuan** [comment]
> When I switch back to the default theme, the editor link takes me to the default template. I made changes to text as well as background color of a random block and saved. Can you reproduce?

@psealock Thanks, I can reproduce the issue. Sorry that the testing instructions were inaccurate. I have made the necessary updates.

Basically, we need to make sure that the `Editor` link directs to the current coming soon page displayed when the coming soon mode is enabled. It looks like the theme's coming soon page is not available when the theme is not active, even if the page has been modified.

Conversely, if the WooCommerce coming soon page is altered, it will consistently display the modified version regardless of the active theme, as it is part of the core functionality.

**Review by psealock — APPROVED** [review]
Thanks for the updated instructions. In this case, this is the desired behaviour and testing well. Code changes make sense. Tested on JN instance 👍🏽
