### PR TITLE
Prevent unnecessary query in clearing admin notices

### LINKED ISSUE #30823: delete_option being called over and over
Please provide us with the information requested in this bug report. Without these details, we won't be able to fully evaluate this issue. 
Bug reports lacking detail, or for any other reason than to report a bug, may be closed without action.

**Prerequisites (mark completed items with an [x]):**
- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
the `delete_option` function, which is triggering a SQL query in order to evaluate if an option exists before proceeding with deletion, is being called on every admin screen load via `WC_Admin_Notices::remove_notice` method, which is called on `wp_loaded` hook from `WC_Admin_Notices::add_redirect_download_method_notice`. (and the same goes for `WC_Regenerate_Images::regenerating_notice`)

**Expected behavior**
IMHO, the code should take advantage of the internal caching inside the `get_option` function to check whether the option has to be deleted, before calling the `delete_option`.

**Actual behavior**
No check is performed.

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. have a plugin allowing to check SQL queries run on a specific screen (eg.: Query Monitor) installed
2. Go to wp-admin screen
3. See the SQL query coming from the `delete_option` being run

**Screenshots**

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report we won't be able to fully evaluate this issue.
<details>
```
### WordPress Environment ###

WordPress address (URL): http://one.wordpress.test
Site address (URL): http://one.wordpress.test
WC Version: 5.7.1
REST API Version: ✔ 5.7.1
WC Blocks Version: ✔ 5.7.2
Action Scheduler Version: ✔ 3.2.1
WC Admin Version: ✔ 2.6.5
Log Directory Writable: ✔
WP Version: 5.8.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.21.1
PHP Version: 7.3.29-1+ubuntu20.04.1+deb.sury.org+1
PHP Post Max Size: 1 GB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.68.0
OpenSSL/1.1.1f

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.5.12-MariaDB-1:10.5.12+maria~focal
Max Upload Size: 1 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 5.7.1
WC Database Prefix: wp_
Total Database Size: 3.79MB
Database Data Size: 2.39MB
Database Index Size: 1.40MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.13MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 1.52MB + Index: 0.03MB + Engine InnoDB
wp_postmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_posts: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 1
page: 7
post: 3
revision: 2
wp_template_part: 1

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (3) ###

Query Monitor: by John Blackbourn – 3.7.1
Gutenberg: by Gutenberg Team – 11.5.1
WooCommerce: by Automattic – 5.7.1

### Inactive Plugins (2) ###

Akismet Anti-Spam: by Automattic – 4.1.12
Hello Dolly: by Matt Mullenweg – 1.7.2

### Dropin Plugins (1) ###

db.php: Query Monitor Database Class

### Must Use Plugins (1) ###

test.php: by  –

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #19 - /?page_id=19
Cart: #20 - /?page_id=20
Checkout: #21 - /?page_id=21
My account: #22 - /?page_id=22
Terms and conditions: ❌ Page not set

### Theme ###

Name: Blockbase
Version: 1.2.0
Author URL: https://automattic.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ❌ Not declared

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 1
Oldest: 2021-09-27 13:21:38 +0000
Newest: 2021-09-27 13:21:38 +0000


### Status report information ###

Generated at: 2021-09-27 13:27:32 +00:00
```
</details>

### PR DESCRIPTION
**Pull request by jorgeatorres**
### Changes proposed in this Pull Request:

This PR optimizes the `WC_Admin_Notices::remove_notice()` method to prevent redundant database queries on every WordPress admin screen load, leveraging WP's internal caching for options.

Even though all of the queries involved are very fast, reducing unnecessary queries seems like good form.

Closes #30823.

### How to test the changes in this Pull Request:

1. Confirm the issue on `trunk`:
   1. Install Query Monitor or similar on your test site.
   1. Check out `trunk`.
   1. Go to _any_ admin page.
   1. Confirm that the following queries are always executed:
      Screenshot 2025-10-22 at 17 44 09
1. Check out this branch (`fix/30823`).
1. Visit any admin page.
1. Confirm the queries are no longer executed.
1. Confirm that the notices functionality remains intact:
   1. Go to WC > Settings > Products > Downloadable products.
   1. Change **File download method** to **Redirect only** and save the settings.
   1. Confirm you see a warning about it:
      Screenshot 2025-10-22 at 18 08 46
   1. Change back the setting to another download method.
   1. Confirm the notice goes away.
1. Use `wp shell` to register a custom notice:
   ```
   wp> \WC_Admin_Notices::add_custom_notice( 'my_test_notice', 'Life is suffering.' );
   wp> \WC_Admin_Notices::store_notices();
   ```
1. Confirm that the notice is visible on the admin.
1. Remove the notice with `wp shell`:
   ```
   wp> \WC_Admin_Notices::remove_notice( 'my_test_notice', true );
   ```
1. Confirm that the notice is no longer visible on the admin and there's no option with name `woocommerce_admin_notice_my_test_notice` in the `wp_options` table.

### CODE REVIEW

**Review by ObliviousHarmony — CHANGES_REQUESTED** [review]
Thanks @jorgeatorres,

In cases without persistent cross-request storage, wouldn't this actually _add_ a query? `delete_option()` always performs a query for the lookup so the `get_option()` won't hydrate a cache for it to use. If so, wouldn't that mean a query in `get_option()` and then query again in `delete_option()`?

---

After looking through `WC_Admin_Notices`, it seems like these queries happen because `WC_Admin_Notices::remove_notice()` is being used incorrectly. The class provides a [`WC_Admin_Notices::has_notice()` function that checks a cached list of active notices](https://github.com/woocommerce/woocommerce/blob/0549cd9eb7098a46f027e2185f657ac7e7927a75/plugins/woocommerce/includes/admin/class-wc-admin-notices.php#L256-L258) without any database queries. Consumers are supposed to call this before attempting to remove a notice since the expectation is that the notice exists at the time of removal.

Something else worth noting is that we don't even need to call `delete_option` for these notices in the first place! [The individual `woocommerce_admin_notice_{key}` options are meant to contain the HTML for _custom_ admin notices](https://github.com/woocommerce/woocommerce/blob/0549cd9eb7098a46f027e2185f657ac7e7927a75/plugins/woocommerce/includes/admin/class-wc-admin-notices.php#L367-L381). In the case of "core" notices, [like the ones that prompted this PR](https://github.com/woocommerce/woocommerce/blob/0549cd9eb7098a46f027e2185f657ac7e7927a75/plugins/woocommerce/includes/admin/class-wc-admin-notices.php#L36-L49), the HTML is included as a template within WooCommerce and that option is not used.

How would you feel about the following:

1. Review the uses of `WC_Admin_Notices::remove_notice()` and make sure they only try to remove the notice if it exists. This will probably only be the two you noticed in the PR description.
2. Check `WC_Admin_Notices::$core_notices` in `remove_notice` and only try to delete the HTML of custom notices.
3. It looks like [`WC_Admin_Notices::remove_notices()` has a bug we can fix too](https://github.com/woocommerce/woocommerce/blob/0549cd9eb7098a46f027e2185f657ac7e7927a75/plugins/woocommerce/includes/admin/class-wc-admin-notices.php#L237-L247)! Right now, it removes the notices (including custom ones) but does not delete the option for custom notices. We should make sure that we're cleaning up the HTML for those notices in the bulk-remove as well.

**Comment by jorgeatorres** [comment]
🤦 You're right @ObliviousHarmony. I did notice (pun intended?) something like that but was trying a few things locally and probably missed the query moving to a different caller.
You're correct that the current code won't save us the SELECT query (unless the site has persistent cache). Let me rewind things a bit and update the PR.

Thank you for the review and for proposing a new course of action! 🙇

**Comment by jorgeatorres** [comment]
Hey @ObliviousHarmony! I've reworked the code a bit. Under normal circumstances this should now lead to no queries at all (unless actively adding or removing a notice).
Can you please take another look? Thanks!

File: plugins/woocommerce/includes/admin/class-wc-admin-notices.php [hunk 1]
```diff
@@ -97,7 +96,20 @@ public static function prepare_note_with_nonce( $response ) {
 	 * Store the locally cached notices to DB.
 	 */
 	public static function store_notices() {
-		update_option( 'woocommerce_admin_notices', self::get_notices() );
+		$current_notices = self::get_notices();
+		$prev_notices    = get_option( 'woocommerce_admin_notices', array() );
```
Comment (ObliviousHarmony) [inline plugins/woocommerce/includes/admin/class-wc-admin-notices.php:100]: What if instead of getting the previous notices from the option we stored them in the class? Then `remove_notice()` would add it to the array, and in `store_notices()`, it would only run if that list was non-empty and it would iterate it for the deletion?

File: plugins/woocommerce/includes/admin/class-wc-admin-notices.php [hunk 2]
```diff
@@ -215,8 +227,12 @@ public static function add_notice( $name, $force_save = false ) {
 	 * @param bool   $force_save Force saving inside this method instead of at the 'shutdown'.
 	 */
 	public static function remove_notice( $name, $force_save = false ) {
+		// Don't proceed if the notice doesn't exist.
+		if ( ! self::has_notice( $name ) ) {
```
Comment (ObliviousHarmony) [inline plugins/woocommerce/includes/admin/class-wc-admin-notices.php]: Do you think we should check `$force_save` and run the function if it was set? I could see someone using `remove_notice()` with the expectation that it forces a save rather than calling `store_notices()`. It's not super likely but "force" seems like something you'd be expecting it to do.

File: plugins/woocommerce/includes/admin/class-wc-admin-notices.php [hunk 3]
```diff
@@ -470,7 +486,7 @@ public static function legacy_shipping_notice() {
 		if ( $enabled ) {
 			include __DIR__ . '/views/html-notice-legacy-shipping.php';
 		} else {
-			self::remove_notice( 'template_files' );
+			self::remove_notice( 'legacy_shipping' );
```
Comment (ObliviousHarmony) [inline plugins/woocommerce/includes/admin/class-wc-admin-notices.php:486]: Wow, nice catch! This has been a bug for 10 years!

**Review by ObliviousHarmony — COMMENTED** [review]
Awesome @jorgeatorres, just one small comment but otherwise this is great!

File: plugins/woocommerce/includes/admin/class-wc-admin-notices.php (hunk 2 above)
Comment (jorgeatorres) [reply plugins/woocommerce/includes/admin/class-wc-admin-notices.php]: Addressed in 84f3cc9e45a60300939a3431c2546c98e7e01287.

File: plugins/woocommerce/includes/admin/class-wc-admin-notices.php (hunk 1 above)
Comment (jorgeatorres) [reply plugins/woocommerce/includes/admin/class-wc-admin-notices.php:100]: Based on our chat, I kept this as-is as a way to clean up possible lingering custom notices.

File: plugins/woocommerce/includes/admin/class-wc-admin-notices.php (hunk 3 above)
Comment (jorgeatorres) [reply plugins/woocommerce/includes/admin/class-wc-admin-notices.php:486]: Better late than never?

**Comment by jorgeatorres** [comment]
Hey @ObliviousHarmony! I made the change and now `$force_save = true` in `remove_notice()` calls `store_notices()` regardless of whether the notice existed or not. Let me know what you think!

**Review by ObliviousHarmony — APPROVED** [review]
Great work @jorgeatorres, no more queries :smile:
