### PR TITLE
performance: checks fo $this->data_synchronizer->data_sync_is_enabled…

### LINKED ISSUE #46556: [HPOS] FeatureChecker->is_hpos_in_sync() should not call get_current_orders_pending_sync_count when Enable compatibility mode is disabled.
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

If Enable compatibility mode is turned off, calling `OrderUtil::is_custom_order_tables_in_sync()` should return false, instead of querying the database.

At the moment of writing this issue, the following tables have the following number of rows in our database:

- wp_posts 1,415,466
- wp_wc_orders 1,207,359

And the respective meta tables are above 80m rows each, we invested a lot of resources getting our website compatible with **HPOS** to finally decouple the big amount of orders from the rest of information store in wp_posts and increase the performance for every other part of the website.

But I noticed that the `COTMigrationUtil` class runs the following query in our order listing page:
```mysql
SELECT( (
SELECT COUNT(1)
FROM wp_posts posts
INNER JOIN wp_wc_orders orders
ON posts.id=orders.id
WHERE posts.post_type = 'shop_order_placehold'
AND orders.status not in ( 'auto-draft' )
AND orders.type IN ('shop_order', 'shop_order_refund', 'shop_subscription')) + (SELECT COUNT(1)
FROM (
SELECT orders.id
FROM wp_wc_orders orders JOIN wp_posts posts on posts.ID = orders.id
WHERE posts.post_type IN ('shop_order', 'shop_order_refund', 'shop_subscription')
AND orders.date_updated_gmt > posts.post_modified_gmt ) x) ) count /* From [harvest.org/wp-admin/admin.php?page=wc-orders] in [/nas/content/live/harvestsite/wp-content/plugins/woocommerce/src/Internal/DataStores/Orders/DataSynchronizer.php:543] */
```

This query takes between 4-5 **seconds** to run, making our order listing page load slow in consequence. This query is run because of the plugin woocommerce-zappier is checking if the orders are in sync, which in this configuration will never be true, I consider running said query in this configuration instead of plainly returning false is against the spirit of HPOS of having a better performing Order Storage.

### Expected behavior

When calling `OrderUtil::is_custom_order_tables_in_sync()` and Enable compatibility mode is disabled in the settings, the return should be always false.

### Actual behavior

When calling `OrderUtil::is_custom_order_tables_in_sync()` and Enable compatibility mode is disabled in the settings, the following gets called `DataSynchronizer->get_current_orders_pending_sync_count()` which runs a heave 4-5s query that shouldn't be run when sync is turned off.

### Steps to reproduce

1. Enable High-performance order storage in Settings -> Advanced -> Features
2. Disable "Enable compatibility mode" in Settings -> Advanced -> Features
3. Call `OrderUtil::is_custom_order_tables_in_sync()` from code.

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://harvest.org
Site address (URL): https://harvest.org
WC Version: 8.7.0
REST API Version: ✔ 8.7.0
Action Scheduler Version: ✔ 3.7.2
Log Directory Writable: ✔
WP Version: 6.5.2
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: Apache
PHP Version: 8.2.14
PHP Post Max Size: 100 MB
PHP Time Limit: 3600
PHP Max Input Vars: 10000
cURL Version: 7.81.0
OpenSSL/3.0.2

SUHOSIN Installed: –
MySQL Version: 8.0.35
Max Upload Size: 50 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.7.0
WC Database Prefix: wp_
Total Database Size: 45123.08MB
Database Data Size: 16419.12MB
Database Index Size: 28703.96MB
wp_woocommerce_sessions: Data: 11.02MB + Index: 5.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 102.64MB + Index: 63.69MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 758.00MB + Index: 698.00MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 3.52MB + Index: 2.52MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 9.52MB + Index: 10.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
_mig_wpmdb_alter_statements: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_actionscheduler_actions: Data: 69.09MB + Index: 63.23MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.22MB + Index: 0.14MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 48.08MB + Index: 32.06MB + Engine InnoDB
wp_advanced_cf7_data: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_alm: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_charitable_campaign_donations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_charitable_donormeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_charitable_donors: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_cloudinary_relationships: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_comments: Data: 3219.98MB + Index: 2850.69MB + Engine InnoDB
wp_css_js_manager: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_db7_forms: Data: 153.67MB + Index: 0.00MB + Engine InnoDB
wp_donate: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_donate_setting: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_downloads: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_duplicator_packages: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_eum_logs: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_failed_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_give_donationmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_give_donormeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_give_donors: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_give_formmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_give_logmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_give_logs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_give_sequential_ordering: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_give_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_imagify_files: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_imagify_folders: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailchimp_carts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mepr_events: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_mepr_jobs: Data: 0.02MB + Index: 0.14MB + Engine InnoDB
wp_mepr_tax_rate_locations: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_mepr_tax_rates: Data: 0.02MB + Index: 0.14MB + Engine InnoDB
wp_mepr_transactions: Data: 0.02MB + Index: 0.31MB + Engine InnoDB
wp_monsterinsights_pageinsights_cache: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_ngg_album: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_ngg_gallery: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_ngg_imagify_data: Data: 0.16MB + Index: 0.02MB + Engine InnoDB
wp_ngg_pictures: Data: 0.31MB + Index: 0.02MB + Engine InnoDB
wp_oauth_access_tokens: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_oauth_authorization_codes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_oauth_jwt: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_oauth_public_keys: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_oauth_refresh_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_oauth_scopes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 87.39MB + Index: 13.17MB + Engine InnoDB
wp_pms_member_subscriptionmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_pms_paymentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_pmxe_exports: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
wp_pmxe_google_cats: Data: 0.39MB + Index: 0.00MB + Engine InnoDB
wp_pmxe_posts: Data: 6.52MB + Index: 0.00MB + Engine InnoDB
wp_pmxe_templates: Data: 0.23MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_files: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_hash: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_history: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_images: Data: 0.16MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_imports: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_posts: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_templates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_popularpostsdata: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_popularpostssummary: Data: 0.08MB + Index: 0.11MB + Engine InnoDB
wp_post_views: Data: 429.80MB + Index: 426.77MB + Engine InnoDB
wp_postmeta: Data: 5653.02MB + Index: 17764.88MB + Engine InnoDB
wp_posts: Data: 427.36MB + Index: 371.97MB + Engine InnoDB
wp_queue: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_redirection_404: Data: 13.02MB + Index: 11.05MB + Engine InnoDB
wp_redirection_groups: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_redirection_items: Data: 0.05MB + Index: 0.09MB + Engine InnoDB
wp_redirection_logs: Data: 0.06MB + Index: 0.05MB + Engine InnoDB
wp_revslider_css: Data: 0.20MB + Index: 0.02MB + Engine InnoDB
wp_revslider_css_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_layer_animations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_layer_animations_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_navigations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_navigations_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_sliders: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_revslider_sliders_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_slides: Data: 1.34MB + Index: 0.02MB + Engine InnoDB
wp_revslider_slides_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_static_slides: Data: 0.20MB + Index: 0.02MB + Engine InnoDB
wp_revslider_static_slides_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_seamless_donations_audit: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_shortpixel_folders: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_shortpixel_meta: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_shortpixel_postmeta: Data: 8.52MB + Index: 10.48MB + Engine InnoDB
wp_shortpixel_queue: Data: 39.28MB + Index: 1.03MB + Engine InnoDB
wp_simple_history: Data: 13.02MB + Index: 6.03MB + Engine InnoDB
wp_simple_history_contexts: Data: 56.09MB + Index: 43.14MB + Engine InnoDB
wp_sm_sync: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
wp_stream: Data: 6.02MB + Index: 11.13MB + Engine InnoDB
wp_stream_meta: Data: 14.02MB + Index: 25.08MB + Engine InnoDB
wp_term_relationships: Data: 22.56MB + Index: 15.55MB + Engine InnoDB
wp_term_taxonomy: Data: 1.48MB + Index: 0.72MB + Engine InnoDB
wp_termmeta: Data: 0.16MB + Index: 0.33MB + Engine InnoDB
wp_terms: Data: 1.44MB + Index: 1.64MB + Engine InnoDB
wp_tm_taskmeta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_tm_tasks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_toolset_associations: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_toolset_connected_elements: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_toolset_post_guid_id: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
wp_toolset_relationships: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_toolset_type_sets: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_ualp_user_activity: Data: 3.52MB + Index: 0.00MB + Engine InnoDB
wp_usermeta: Data: 792.91MB + Index: 1103.52MB + Engine InnoDB
wp_users: Data: 18.55MB + Index: 23.06MB + Engine InnoDB
wp_vxcf_hubspot: Data: 1.52MB + Index: 0.02MB + Engine InnoDB
wp_vxcf_hubspot_accounts: Data: 0.28MB + Index: 0.00MB + Engine InnoDB
wp_vxcf_hubspot_log: Data: 819.61MB + Index: 1.52MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 38.56MB + Index: 28.08MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_gpf_render_cache: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_order_addresses: Data: 293.89MB + Index: 337.88MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_operational_data: Data: 175.77MB + Index: 94.33MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 106.66MB + Index: 99.34MB + Engine InnoDB
wp_wc_order_stats: Data: 126.66MB + Index: 69.66MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 21.56MB + Index: 16.03MB + Engine InnoDB
wp_wc_orders: Data: 385.94MB + Index: 317.48MB + Engine InnoDB
wp_wc_orders_meta: Data: 2109.00MB + Index: 3938.72MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.16MB + Index: 0.33MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.06MB + Index: 0.05MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_zapier_history: Data: 40.58MB + Index: 14.53MB + Engine InnoDB
wp_wcs_payment_retries: Data: 12.52MB + Index: 2.52MB + Engine InnoDB
wp_wcsc_error_logs: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wcsc_logs: Data: 146.67MB + Index: 192.31MB + Engine InnoDB
wp_wdi_feeds: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wdi_themes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfblockediplog: Data: 1.02MB + Index: 0.00MB + Engine InnoDB
wp_wfblocks7: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wfconfig: Data: 5.25MB + Index: 0.00MB + Engine InnoDB
wp_wfcrawlers: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wffilechanges: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wffilemods: Data: 59.64MB + Index: 0.00MB + Engine InnoDB
wp_wfhits: Data: 2.02MB + Index: 0.22MB + Engine InnoDB
wp_wfhoover: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfissues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wfknownfilelist: Data: 27.55MB + Index: 0.00MB + Engine InnoDB
wp_wflivetraffichuman: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wflocs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wflogins: Data: 1.02MB + Index: 0.17MB + Engine InnoDB
wp_wfls_2fa_secrets: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfls_role_counts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfls_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfnotifications: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfpendingissues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wfreversecache: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfsecurityevents: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfsnipcache: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wfstatus: Data: 1.02MB + Index: 0.33MB + Engine InnoDB
wp_wftrafficrates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfwafconfig: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
wp_wfwaffailures: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_exported_csv_items: Data: 1.14MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_gpf_google_taxonomy: Data: 1.52MB + Index: 0.13MB + Engine InnoDB
wp_wpcw_certificates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpcw_courses: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wpcw_member_levels: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpcw_modules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpcw_question_random_lock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpcw_question_tags: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpcw_question_tags_map: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpcw_queue_dripfeed: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpcw_quizzes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wpcw_quizzes_feedback: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpcw_quizzes_questions: Data: 0.14MB + Index: 0.00MB + Engine InnoDB
wp_wpcw_quizzes_questions_map: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wpcw_units_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpcw_user_courses: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpcw_user_progress: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpcw_user_progress_quizzes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpf_logging: Data: 4.52MB + Index: 0.22MB + Engine InnoDB
wp_wpfm_backup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpfront_ure_login_redirect: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wpfront_ure_options: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wpfront_ure_post_type: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wpfront_ure_taxonomy: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wpr_rocket_cache: Data: 3.38MB + Index: 3.88MB + Engine InnoDB
wp_wpr_rucss_used_css: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wsal_metadata: Data: 5.52MB + Index: 10.03MB + Engine InnoDB
wp_wsal_occurrences: Data: 0.28MB + Index: 0.45MB + Engine InnoDB
wp_yoast_indexable: Data: 11.48MB + Index: 10.86MB + Engine InnoDB
wp_yoast_indexable_hierarchy: Data: 3.03MB + Index: 6.08MB + Engine InnoDB
wp_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_primary_term: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_yoast_prominent_words: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_yoast_seo_links: Data: 1.34MB + Index: 0.36MB + Engine InnoDB
wp_yoast_seo_meta: Data: 23.56MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

acf: 6
acf-field: 1346
acf-field-group: 152
activity: 2
ajde_events: 12
attachment: 8580
audioplayer: 1
blocked_user: 3
campaign: 1
church-location: 159
course_unit: 32
course-unit: 6
course-unit-old: 26
custom_css: 1
customize_changeset: 5
devotion: 6132
display_type: 7
ebook: 38
faq: 9
funds: 1
gregs-notes: 139
gregsblog: 1309
harvest-event: 134
harvest-film: 3
jr-post: 5
know-god-article: 233
memberpressproduct: 9
memberpressrule: 6
nav_menu_item: 177
newsroom-gallery: 1
ngg_album: 3
ngg_gallery: 11
ngg_pictures: 333
oembed_cache: 1293
page: 233
podcast: 2271
post: 949
press-release: 18
product: 469
product_variation: 697
radio: 4628
revision: 68
services: 39
shop_coupon: 4
shop_order: 1175838
shop_order_placehold: 1279
shop_order_refund: 243
shop_subscription: 22639
slick_slider: 1
tv: 553
ultimate-fields: 1
video: 4
wc_zapier_feed: 5
webcast: 2705
wo_client: 4
wp_block: 2
wp_global_styles: 1
wp-types-group: 7
wpcf7_contact_form: 9
wpcf7s: 203712
wpcode: 3

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (71) ###

Query Monitor: by John Blackbourn – 3.15.0
Advanced Custom Fields PRO: by WP Engine – 6.2.9
FiboSearch - AJAX Search for WooCommerce: by FiboSearch Team – 1.27.0
ARI Fancy Lightbox: by ARI Soft – 1.3.13
Conditional Fields for Contact Form 7: by Jules Colle – 2.4.10
Integration for Contact Form 7 and HubSpot Pro: by CRM Perks – 1.2.9
Church Locations: by Bartek Makowski – 0.1.0
Classic Editor: by WordPress Contributors – 1.6.3
Contact Form 7: by Takayuki Miyoshi – 5.9.3
Contact Form CFDB7: by Arshid – 1.2.6.8
Disable Cart Fragments: by Optimocha – 2.3
GTM4WP - A Google Tag Manager (GTM) plugin for WordPress: by Thomas Geiger – 1.20.2
Easy Load More: by Idiom Interactive – 1.0.3
Facebook for WooCommerce: by Facebook – 3.1.14
Harvest Portal: by Advant Interactive – 0.2.0
Index WP MySQL For Speed: by Oliver Jones
Rick James – 1.4.17

WPCode Lite: by WPCode – 2.1.11
WP OAuth Server - CE: by WP OAuth Server – 4.4.0
Post Views Counter: by dFactory – 1.4.5
Printify Shipping Method: by Printify – 2.8
Product Open Pricing (Name Your Price) for WooCommerce Pro: by WP Wham – 1.3.2
reCAPTCHA for WooCommerce: by Elliot Sowersby
RelyWP – 1.3.3

Redirection: by John Godley – 5.4.2
Redis Object Cache: by Till Krüss – 2.5.1
Slider Revolution Particle Wave Add-On: by ThemePunch – 1.1.0
Slider Revolution Transitionpack Add-On: by ThemePunch – 1.0.6
Slider Revolution: by ThemePunch – 6.6.18
MWW Scheduled Post Trigger: by Moss Web Works – 3.2
Search Exclude: by QuadLayers – 2.0.9
ShipWorks Connector: by AdvancedCreation – 5.1.6
ShortPixel Image Optimizer: by ShortPixel - Convert WebP/AVIF & Optimize Images – 5.5.5
Simple History: by Pär Thernström – 4.14.0
Simple Post Type Permalinks: by Toro_Unit – 2.0.5
Sticky: by CVMH solutions – 2.5.6
Easy Updates Manager: by Easy Updates Manager Team – 9.0.17
Stream: by XWP – 4.0.0
Theme Customisations: by WooThemes – 1.0.0
TikTok: by TikTok – 1.2.5
Advanced Editor Tools: by Automattic – 5.9.2
Toolset Types: by OnTheGoSystems – 3.4.20
User Switching: by John Blackbourn & contributors – 1.7.3
XT Floating Cart for WooCommerce: by XplodedThemes – 2.7.7
Payment Plugins for Stripe WooCommerce: by Payment Plugins
support@paymentplugins.com – 3.3.60

Checkout Field Editor for WooCommerce (Pro): by ThemeHigh – 3.6.1
WooCommerce Duplicate Billing Address: by Andrew Schultz – 1.16
WooCommerce Dynamic Pricing: by Element Stark – 3.2.6
WooCommerce Stripe Gateway: by WooCommerce – 8.1.1
WooCommerce Google Analytics Pro: by SkyVerge – 2.0.16
Order Exporter: by Advant Interactive – 0.2
WooCommerce Pre-Orders: by WooCommerce – 2.1.0
WooCommerce Product CSV Import Suite: by WooCommerce – 1.10.69
WooCommerce Google Product Feed: by Ademti Software Ltd. – 11.0.1
WooCommerce Shipping & Tax: by WooCommerce – 2.5.4
WooCommerce UPS Shipping: by WooCommerce – 3.5.9
WooCommerce USPS Shipping: by WooCommerce – 4.8.3
WooCommerce Subscriptions - Preserve Billing Schedule: by Prospress Inc. – 1.0.0
Woo Subscriptions: by WooCommerce – 6.1.0
Woocommerce Webhooks Monitor: by Bartek Makowski – 0.1.0
WooCommerce Zapier: by OM4 Software – 2.10.0
WooCommerce: by Automattic – 8.7.0
Wordfence Security: by Wordfence – 7.11.5
Cloud Sites SSL Fixes: by Nathan Smith – 0.2
Yoast SEO Premium: by Team Yoast – 22.4
Yoast SEO: by Team Yoast – 22.4
WP Crontrol: by John Blackbourn – 1.16.2
WP-DownloadManager: by Lester 'GaMerZ' Chan – 1.68.8
WP Migrate Lite: by Delicious Brains – 2.5.0
WP Rocket: by WP Media – 3.15.10
WP All Export - User Export Add-On Pro: by Soflyy – 1.0.7
WPFront User Role Editor: by Syam Mohan – 4.1.0
NextGEN Gallery: by Imagely – 3.58

### Inactive Plugins (23) ###

a3 Lazy Load: by a3rev Software – 2.7.2
Admin Bar Wrap Fix: by KZeni – 1.2.7
BugFu Console Debugger: by Federico Andrioli – 1.3.0
Code Profiler: by Jerome Bruandet ~ NinTechNet Ltd. – 1.6.6
Contact Form Submissions: by Jason Green – 1.7.1
Download Plugin: by Metagauss – 2.0.8
Font Awesome: by Font Awesome – 4.4.0
Fraud Prevention For Woocommerce: by theDotstore – 2.1.8
Lazy Load - Optimize Images: by WP Rocket – 2.3.6
Show Current Template: by JOTAKI Taisuke – 0.5.2
WooCommerce Anti Fraud: by OPMC Australia Pty Ltd – 4.4
WooCommerce Customer/Order/Coupon Export: by SkyVerge – 5.5.1
Woocommerce Extended Zip Codes: by Advant Interactive – 0.2.0
WooCommerce Order Test - WP Fix It: by WP Fix It – 2.1
Woo Conditional Shipping and Payments: by Woo – 1.15.8
WooPayments: by Automattic – 7.4.0
WP-Cron Status Checker: by Webhead LLC – 1.2.5
WP-Stateless: by UDX – 4.0.1
WP-Sweep: by Lester 'GaMerZ' Chan – 1.1.8
WP All Export - WooCommerce Export Add-On Pro: by Soflyy – 1.0.9
WP All Export Pro: by Soflyy – 1.8.8
WP Fusion: by Very Good Plugins – 3.40.32
Yoast Duplicate Post: by Enrico Battocchi & Team Yoast – 4.5

### Dropin Plugins () ###

advanced-cache.php: advanced-cache.php
object-cache.php: Redis Object Cache Drop-In

### Must Use Plugins (8) ###

Code Profiler (mu-plugin): by Jerome Bruandet – 1.0
Force Strong Passwords - WPE Edition: by Jason Cosper – 1.8.0
Index WP MySQL For Speed Upgrade Filter for mu-plugins.: by  – 1.4.14
WP Engine Cache Plugin: by WP Engine – 1.3.0
WP Engine Seamless Login Plugin: by WP Engine – 1.6.1
WP Engine Security Auditor: by wpengine – 1.1.1
WP Engine System: by WP Engine – 5.0.1
WP Migrate Lite Compatibility: by Delicious Brains – 1.3

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude_from_catalog (exclude_from_catalog)
exclude_from_search (exclude_from_search)
exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to Woo.com: ✔
Enforce Approved Product Download Directories: –
HPOS feature screen enabled: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 1 day
Level threshold: –
Log directory size: 133 MB

### WC Pages ###

Shop base: #15 - /store/
Cart: #19835 - /cart/
Checkout: #19836 - /checkout/
My account: #19837 - /partner-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Harvest
Version: 1.0 (update to version 2.0 is available)
Author URL: http://fishermenlabs.com
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ❌ Not declared

### Templates ###

Overrides: harvest/woocommerce/archive-product.php
harvest/woocommerce/cart/cart-empty.php version 3.5.0 is out of date. The core version is 7.0.1
harvest/woocommerce/cart/cart.php version 3.5.0 is out of date. The core version is 7.9.0
harvest/woocommerce/checkout/form-billing.php version 3.0.9 is out of date. The core version is 3.6.0
harvest/woocommerce/checkout/form-checkout.php
harvest/woocommerce/checkout/form-login.php version 3.4.0 is out of date. The core version is 3.8.0
harvest/woocommerce/checkout/form-shipping.php version 3.0.9 is out of date. The core version is 3.6.0
harvest/woocommerce/checkout/payment-method.php
harvest/woocommerce/checkout/payment.php version 3.4.0 is out of date. The core version is 8.1.0
harvest/woocommerce/checkout/review-order.php
harvest/woocommerce/checkout/thankyou.php version 3.2.0 is out of date. The core version is 8.1.0
harvest/woocommerce/content-single-product.php
harvest/woocommerce/emails/admin-new-order.php
harvest/woocommerce/emails/customer-completed-order.php
harvest/woocommerce/emails/customer-processing-order.php
harvest/woocommerce/emails/customer-refunded-order.php
harvest/woocommerce/global/form-login.php version 3.3.0 is out of date. The core version is 7.0.1
harvest/woocommerce/myaccount/form-login.php version 3.5.0 is out of date. The core version is 7.0.1
harvest/woocommerce/myaccount/form-lost-password.php version 3.4.0 is out of date. The core version is 7.0.1
harvest/woocommerce/myaccount/form-reset-password.php version 3.5.0 is out of date. The core version is 7.0.1
harvest/woocommerce/single-product/add-to-cart/grouped.php version 4.8.0 is out of date. The core version is 7.0.1
harvest/woocommerce/single-product/product-image.php version 3.5.1 is out of date. The core version is 7.8.0
harvest/woocommerce/single-product/related.php version - is out of date. The core version is 3.9.0

Outdated Templates: ❌
					
					
						Learn how to update

### Subscriptions ###

WCS_DEBUG: ✔ No
Subscriptions Mode: ✔ Live
Subscriptions Live URL: https://harvest.org
Subscriptions-core Library Version: 6.9.0
Subscription Statuses: wc-active: 8435
wc-cancelled: 12778
wc-expired: 1
wc-on-hold: 1384
wc-pending: 37
wc-pending-cancel: 17

WooCommerce Account Connected: ✔ Yes
Active Product Key: ✔ Yes
Custom Retry Rules: ✔ No
Custom Retry Rule Class: ✔ No
Custom Raw Retry Rule: ✔ No
Custom Retry Rule: ✔ No
Retries Migration Status: ✔ Completed
Report Cache Enabled: ✔ Yes
Cache Update Failures: ✔ 0 failure

### Store Setup ###

Country / State: United States (US) — California

### Subscriptions by Payment Gateway ###

Stripe: wc-active: 7735
wc-cancelled: 10997
wc-expired: 1
wc-on-hold: 1327
wc-pending-cancel: 16

ACH (Stripe) by Payment Plugins: wc-active: 700
wc-cancelled: 192
wc-on-hold: 50
wc-pending: 5
wc-pending-cancel: 1

other: wc-cancelled: 2

### Payment Gateway Support ###

Check payments: products
Cash on delivery: products
Stripe: products
refunds
tokenization
add_payment_method
subscriptions
subscription_cancellation
subscription_suspension
subscription_reactivation
subscription_amount_changes
subscription_date_changes
subscription_payment_method_change
subscription_payment_method_change_customer
subscription_payment_method_change_admin
multiple_subscriptions
pre-orders

ACH (Stripe) by Payment Plugins: tokenization
products
subscriptions
add_payment_method
subscription_cancellation
multiple_subscriptions
subscription_amount_changes
subscription_date_changes
default_credit_card_form
refunds
pre-orders
subscription_payment_method_change_admin
subscription_reactivation
subscription_suspension
subscription_payment_method_change_customer

### WooCommerce Google Product Feed feeds ###

93ca89bc17ad1803: Google merchant centre product feed
  Type: google
  Category filter: -
  Categories: -

### WooCommerce Google Product Feed options ###

Include variations in feed: Enabled
Send "item group ID": Enabled
Expanded schema markup: -
Debug key: fc57cbe4-911a-49d0-9615-8e190c949ae0

### WooCommerce Google Product Feed fields ###

Title: Pre-populates from product product_title.
Availability (in stock products): Defaults to "in stock".
Availability (backordered products): Defaults to "in stock".
Availability (out of stock products): Defaults to "out of stock".
Brand: 
Manufacturer Part Number (MPN): 
Product Type: 
Google Product Category: 
Size system: 

### WooCommerce Google Product Feed DB status ###

Database version: 17
Active database version: 17
wc_gpf_render_cache: Empty
woocommerce_gpf_google_taxonomy (en-US): 5595 items

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
product-virtual-downloadable
product-external-affiliate
product-grouped
product-linked
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: customize-store
minified-js
new-product-management-experience
product-pre-publish-modal
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2024-04-13 19:35:22 -07:00
Options: ✔
Notes: 63
Onboarding: completed

### Action Scheduler ###

Canceled: 101
Oldest: 2024-03-15 02:04:54 -0700
Newest: 2024-04-12 12:00:03 -0700

Complete: 163,364
Oldest: 2024-03-12 17:00:34 -0700
Newest: 2024-04-12 15:38:01 -0700

Failed: 8
Oldest: 2024-03-13 12:43:41 -0700
Newest: 2024-04-11 14:47:54 -0700

Pending: 8,458
Oldest: 2024-04-12 15:46:14 -0700
Newest: 2024-06-15 07:49:01 -0700

### WooCommerce Zapier ###

Database Version: ✔ 19
Detailed Logging Enabled: Yes
Legacy Mode Disabled: ❌ No
SSL: ✔ Yes
REST API Authentication Key(s): ✔ 11
Task History Record Count: ✔ 232641
Webhook #7: WooCommerce Zapier
- Status: active
- Trigger: order.status_changed_to_completed
- Delivery Count: 49844
- User: robertb@harvest.org
Webhook #3: WooCommerce Zapier
- Status: active
- Trigger: order.status_changed_to_completed
- Delivery Count: 113095
- User: robertb@harvest.org
Deleted Webhook Delivery Count: 308
Customer Action Count: 32200
Order Action Count: 37194
Legacy Cron Tasks: ✔ 0
Active Legacy Feeds: ❌ 5 active Legacy Feed(s) need to be migrated before Apr 30
2022. Migrate Your Zaps Now

Legacy Feed #1: Subscription created
- Trigger: Subscription Created
- Webhook URL: https://hooks.zapier.com/hooks/catch/1240470/blzoh6e/
Legacy Feed #2: Renewal Transactional Email
- Trigger: Subscription Renewed
- Webhook URL: https://hooks.zapier.com/hooks/catch/1240470/737804/
Legacy Feed #3: User Creation
- Trigger: New Customer
- Webhook URL: https://hooks.zapier.com/hooks/catch/1240470/v2yat9/
Legacy Feed #4: New Order
- Trigger: New Order
- Webhook URL: https://hooks.zapier.com/hooks/catch/1240470/nk8j6z/
Legacy Feed #5: Failed Subscription
- Trigger: Subscription Renewal Failed
- Webhook URL: https://hooks.zapier.com/hooks/catch/1240470/of2taq5/

### Status report information ###

Generated at: 2024-04-12 15:46:01 -07:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by EngHell**
…() before executing $this->data_synchronizer->get_sync_status()

### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes #46556 .

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Before checking out this branch, install the Query Monitor plugin on your test site.
2. Navigate to the WooCommerce > Settings > Advanced > Features screen in WP Admin. Ensure that High-performance order storage is enabled, and compatibility mode is disabled.
3. Open the Query Monitor console, click on "Database Queries", and then "Queries by Caller". Find the caller with the name that's something like `Automattic\W\I\D\O\DataSynchronizer->get_current_orders_pending_sync_count()`. Note the number of queries being run by this caller.
4. Add this snippet to your site (in an mu-plugin file for example):
    ```php
	use Automattic\WooCommerce\Utilities\OrderUtil;
	add_action(
		'admin_init',
		function() {
			OrderUtil::is_custom_order_tables_in_sync();
		}
	);
    ```
5. Refresh the screen and check the QM console again. The number of queries for our caller should be higher now.
6. Now check out this branch (or apply this PR's changeset as a patch) and refresh the screen again. The number of queries should be back at its original number, indicating that `OrderUtil::is_custom_order_tables_in_sync()` is no longer causing extra queries to run when compatibility mode is disabled.

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [x] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

Avoid unnecessary query when HPOS compatibility mode is disabled.

#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce/src/Internal/Utilities/COTMigrationUtil.php [hunk 1]
```diff
@@ -74,8 +74,11 @@ private function custom_orders_table_usage_is_enabled() : bool {
 	 * @return bool
 	 */
 	public function is_custom_order_tables_in_sync() : bool {
+		if(!$this->data_synchronizer->data_sync_is_enabled()) {
+			return false;
+		}
```
Comment (coreymckrill) [inline plugins/woocommerce/src/Internal/Utilities/COTMigrationUtil.php]:
```suggestion
		if ( ! $this->data_synchronizer->data_sync_is_enabled() ) {
			return false;
		}

```

**Review by coreymckrill — APPROVED** [review]
Thanks for the PR @EngHell. I updated the testing instructions a bit and fixed some code linting issues, but it's otherwise looking good. Waiting to see if the CI checks pass.

**Comment by EngHell** [comment]
@coreymckrill Thanks for the updates to the PR description, I will use them as an example in the case I contribute again in the future.

**Comment by rodelgc** [comment]
Thank you so much too @coreymckrill for updating the testing instructions. It's a really big help when analyzing the impact of the PR's.
