### PR TITLE
Revert deprecation of $type on the get_european_union_countries method

### LINKED ISSUE #26105: get_vat_countries() not the same as get_european_union_countries( 'eu_vat' )
**Describe the bug**
On WooCommerce 4.0 the WC_Countries `get_european_union_countries` method `$type` parameter was deprecated and the warning tells us to use `get_vat_countries()`.

Before 4.0 `get_european_union_countries( 'eu_vat' )` returned the 28 EU countries + Monaco and Isle of Man, which was correct.

`get_vat_countries()` returns 80 countries, which may be correct for "the countries that use VAT" but it's not correct as a new method to get the "European VAT zone countries".

**To Reproduce**
Run `WC()->countries->get_european_union_countries( 'eu_vat' )` before and after WooCommerce 4.0
You will get 28+2 countries before WooCommerce 4 and 80 countries after WooCommerce 4 because if 'eu_vat' is passed on to the `get_european_union_countries` method, the new `get_vat_countries` is called, which is wrong.

**Expected behavior**
`get_vat_countries()` should not be announced or used as an alternative to `get_european_union_countries( 'eu_vat' )`.

**Possible solutions**
- A new method should be created to get the EU VAT countries (not a good idea because this will force people to use a new method)
- The `get_european_union_countries` `$type` parameter should work as before (best solution because existing code will work)

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by webdados**
Closes #26105 

### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Revert deprecation of $type parameter on the WC_Countries get_european_union_countries method.

Closes #26105 

### How to test the changes in this Pull Request:

1. Call WC()->countries->get_european_union_countries('eu_vat') and make sure you get the EU countries + Monaco + Isle of Man + Greaat Britain instead of a list of 80 countries

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully run tests with your changes locally?

### Changelog entry

> Revert deprecation of $type parameter on the WC_Countries get_european_union_countries method

### CODE REVIEW

File: includes/class-wc-countries.php [hunk 1]
```diff
@@ -350,18 +350,20 @@ public function get_shipping_country_states() {
...
+	public function get_european_union_countries( $type = '' ) {
 		$countries = array( 'AT', 'BE', 'BG', 'CY', 'CZ', 'DE', 'DK', 'EE', 'ES', 'FI', 'FR', 'GR', 'HU', 'HR', 'IE', 'IT', 'LT', 'LU', 'LV', 'MT', 'NL', 'PL', 'PT', 'RO', 'SE', 'SI', 'SK' );
 
-		if ( ! empty( $deprecated ) ) {
-			wc_deprecated_argument( 'type', '4.0.0', 'Use the WC_Countries::get_vat_countries method instead.' );
-			$countries = $this->get_vat_countries();
+		if ( 'eu_vat' === $type ) {
+			$countries[] = 'MC';
+			$countries[] = 'IM';
+			//The UK is still part of the EU VAT zone
```
Comment (claudiosanches) [inline includes/class-wc-countries.php:362]: Please update to:

```
// The UK is still part of the EU VAT zone.
```

**Review by claudiosanches — CHANGES_REQUESTED** [review]
This change looks good.
There's just a small tweak to do before we can approve.
Thanks!

File: includes/class-wc-countries.php (hunk 1 above)
Comment (webdados) [reply includes/class-wc-countries.php]: Done

**Comment by webdados** [comment]
@claudiosanches Should we add a date check so that IM and GB are only returned until December 31st 2020?
https://www.avalara.com/vatlive/en/vat-news/uk-to-leave-eu-vat-regime-31-dec-20200.html

**Review by claudiosanches — APPROVED** [review]
Thanks!
