### PR TITLE
ShippingController->register_local_pickup defensive checks to prevent fatal

### LINKED ISSUE #56907: [Fatal] PHP Fatal error: Uncaught Error: Call to a member function register_shipping_method() on null in | ShippingController.php:323
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Witnessed in `9.7.1`

[link to code](https://github.com/woocommerce/woocommerce/blob/9ef801f1c3786a8d394edb99b202d4947986f520/plugins/woocommerce/src/Blocks/Shipping/ShippingController.php#L323)

```
PHP Fatal error:  Uncaught Error: Call to a member function register_shipping_method() on null in /../plugins/woocommerce/9.7.1/src/Blocks/Shipping/ShippingController.php:323
Stack trace:
#0 /../core/6.7.2/wp-includes/class-wp-hook.php(324): Automattic\WooCommerce\Blocks\Shipping\ShippingController->register_local_pickup(Array)
#1 /../core/6.7.2/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)
#2 /../core/6.7.2/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#3 /../plugins/woocommerce/9.7.1/includes/class-wc-shipping.php(181): do_action('woocommerce_loa...', Array)
#4 /../plugins/woocommerce/9.7.1/includes/class-wc-shipping.php(221): WC_Shipping->load_shipping_methods()
#5 /../plugins/woocommerce-shipping-fedex/4.3.5/includes/class-logger.php(49): WC_Shipping->get_shipping_methods()
#6 /../plugins/woocommerce-shipping-fedex/4.3.5/includes/class-logger.php(71): WooCommerce\FedEx\Logger::get_shipping_method()
#7 /../plugins/woocommerce-shipping-fedex/4.3.5/includes/class-logger.php(143): WooCommerce\FedEx\Logger::log('error', 'FedEx_OAuth::re...', Array)
#8 /../plugins/woocommerce-shipping-fedex/4.3.5/includes/api/rest/class-fedex-oauth.php(150): WooCommerce\FedEx\Logger::error('FedEx_OAuth::re...')
#9 /../plugins/woocommerce-shipping-fedex/4.3.5/includes/api/rest/class-fedex-oauth.php(98): WooCommerce\FedEx\FedEx_OAuth->get_access_token_from_fedex()
#10 /../plugins/woocommerce-shipping-fedex/4.3.5/includes/api/rest/class-fedex-rest-api.php(83): WooCommerce\FedEx\FedEx_OAuth->get_access_token()
#11 /../plugins/woocommerce-shipping-fedex/4.3.5/includes/class-wc-shipping-fedex.php(607): WooCommerce\FedEx\FedEx_REST_API->__construct(Object(WC_Shipping_Fedex))
#12 /../plugins/woocommerce-shipping-fedex/4.3.5/includes/class-wc-shipping-fedex.php(369): WC_Shipping_Fedex->set_settings()
#13 /../plugins/woocommerce-shipping-fedex/4.3.5/includes/class-wc-shipping-fedex.php(2788): WC_Shipping_Fedex->__construct()
#14 /../plugins/woocommerce-shipping-fedex/4.3.5/includes/class-wc-shipping-fedex-init.php(168): include_once('/../plug...')
#15 /../core/6.7.2/wp-includes/class-wp-hook.php(324): WC_Shipping_Fedex_Init->includes('')
#16 /../core/6.7.2/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)
#17 /../core/6.7.2/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#18 /../plugins/woocommerce/9.7.1/includes/class-wc-shipping.php(122): do_action('woocommerce_shi...')
#19 /../plugins/woocommerce/9.7.1/includes/class-wc-shipping.php(114): WC_Shipping->init()
#20 /../plugins/woocommerce/9.7.1/includes/class-wc-shipping.php(68): WC_Shipping->__construct()
#21 /../plugins/woocommerce/9.7.1/includes/class-woocommerce.php(1168): WC_Shipping::instance()
#22 /../plugins/woocommerce/9.7.1/includes/class-woocommerce.php(200): WooCommerce->shipping()
#23 /../plugins/woocommerce-avatax/2.10.2/src/admin/class-wc-avatax-shipping-transport.php(121): WooCommerce->__get('shipping')
#24 /../core/6.7.2/wp-includes/class-wp-hook.php(324): WC_AvaTax_Shipping_Transport->add_custom_field_to_shipping_methods('')
#25 /../core/6.7.2/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)
#26 /../core/6.7.2/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#27 /../plugins/woocommerce/9.7.1/includes/class-woocommerce.php(861): do_action('woocommerce_ini...')
#28 /../core/6.7.2/wp-includes/class-wp-hook.php(324): WooCommerce->init('')
#29 /../core/6.7.2/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)
#30 /../core/6.7.2/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#31 /../core/6.7.2/wp-settings.php(704): do_action('init')
#32 /../wp-config.php(83): require_once('/../core...')
#33 /../core/6.7.2/wp-load.php(55): require_once('/../wp-...')
#34 /../core/6.7.2/wp-admin/admin-ajax.php(22): require_once('/../core...')
#35 {main}
  thrown in /../plugins/woocommerce/9.7.1/src/Blocks/Shipping/ShippingController.php on line 323
``` 

### Expected behavior

No fatals expected

### Actual behavior

Fatals were witnessed

### Steps to reproduce

We don’t have steps to reproduce, but observed 30 Fatals of this type were observed on Fri March 7 2025 across 1 site.
Hopefully, someone can dig in and apply a defensive check if appropriate. – To be updated after investigation

### WordPress Environment

N/A

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by tjcafferkey**
### Changes proposed in this Pull Request:

Added defensive checks to prevent fatal errors when `WC()` function doesn't exist or when `WC()->shipping` is not available in the ShippingController's `register_local_pickup` method. This fix prevents fatal errors such as the one reported in the linked issue

Closes [WOOPLUG-3722](https://linear.app/a8c/issue/WOOPLUG-3722)
Closes https://github.com/woocommerce/woocommerce/issues/56907

(For Bug Fixes) Bug introduced in PR # .

### Screenshots or screen recordings:

| Before | After |
| ------ | ----- |
|        |       |

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Check CI passes with new tests
2. WooCommerce > Settings > Shipping > Confirm the Local Pickup option in the top links
3. Enable Local Pickup
4. Ensure its reflected in the Checkout block and works as expected

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce/src/Blocks/Shipping/ShippingController.php [hunk 1]
```diff
@@ -333,7 +333,7 @@ public function admin_scripts() {
 	 * Registers the Local Pickup shipping method used by the Checkout Block.
 	 */
 	public function register_local_pickup() {
-		if ( CartCheckoutUtils::is_checkout_block_default() ) {
+		if ( CartCheckoutUtils::is_checkout_block_default() && method_exists( wc(), 'shipping' ) && method_exists( wc()->shipping, 'register_shipping_method' ) ) {
```
Comment (opr) [inline plugins/woocommerce/src/Blocks/Shipping/ShippingController.php]:
```suggestion
		if ( CartCheckoutUtils::is_checkout_block_default() && method_exists( WC(), 'shipping' ) && method_exists( WC()->shipping, 'register_shipping_method' ) ) {
```

File: plugins/woocommerce/src/Blocks/Shipping/ShippingController.php [hunk 2]
```diff
@@ -333,7 +333,7 @@ public function admin_scripts() {
...
 			wc()->shipping->register_shipping_method( new PickupLocation() );
```
Comment (opr) [inline plugins/woocommerce/src/Blocks/Shipping/ShippingController.php]:
```suggestion
			WC()->shipping->register_shipping_method( new PickupLocation() );
```

File: plugins/woocommerce/src/Blocks/Shipping/ShippingController.php (hunk 1 above)
Comment (opr) [reply plugins/woocommerce/src/Blocks/Shipping/ShippingController.php]: let's also consider logging an error here (and a test to check the logger was triggered!)

**Review by opr — CHANGES_REQUESTED** [review]
Hi @tjcafferkey thanks for the PR - it's testing well, but I have some minor nitpicks about casing.

We should also log an error when `shipping` or `register_shipping_method` doesn't exist, and update the tests to cover that as well.

File: plugins/woocommerce/src/Blocks/Shipping/ShippingController.php (hunk 2 above)
Comment (tjcafferkey) [reply plugins/woocommerce/src/Blocks/Shipping/ShippingController.php]: https://github.com/woocommerce/woocommerce/pull/57154/commits/11db0b05b4fdd866c6a271353c35abc19e4371fe

File: plugins/woocommerce/src/Blocks/Shipping/ShippingController.php (hunk 1 above)
Comment (tjcafferkey) [reply plugins/woocommerce/src/Blocks/Shipping/ShippingController.php]: https://github.com/woocommerce/woocommerce/pull/57154/commits/06041d6d9c809bf855b7d701e4606b83a8938a9c

Comment (tjcafferkey) [reply plugins/woocommerce/src/Blocks/Shipping/ShippingController.php]: https://github.com/woocommerce/woocommerce/pull/57154/commits/d68efb203c89613c53c3301f141e5e8df60c74be

File: plugins/woocommerce/tests/php/src/Blocks/Shipping/ShippingControllerTest.php [hunk 3]
```diff
@@ -90,4 +128,52 @@ function ( $locale ) {
...
+			$incomplete_wc = new \stdClass(); // Object without shipping property.
+			$woocommerce   = $incomplete_wc;
+
+			$this->shipping_controller->register_local_pickup();
+			$this->assertTrue( true, 'Method did not throw exceptions with missing WC object' );
+		} finally {
+			global $woocommerce;
+			$woocommerce = $wc_backup;
+			remove_all_filters( 'woocommerce_logging_class' );
+		}
```
Comment (opr) [inline plugins/woocommerce/tests/php/src/Blocks/Shipping/ShippingControllerTest.php]: Why put this in a try/finally? You can just do it at the end of the test, also the filter removal could go into `tearDown` couldn't it? I think that is a more common pattern, e.g. https://github.com/woocommerce/woocommerce/blob/c9ee77c785f5e319e8b57bc11a765f892b7eb6bf/plugins/woocommerce/tests/php/src/Blocks/StoreApi/Routes/CartItems.php#L93

File: plugins/woocommerce/tests/php/src/Blocks/Shipping/ShippingControllerTest.php [hunk 4]
```diff
@@ -90,4 +128,52 @@ function ( $locale ) {
...
+				return $logger_mock;
+			},
+			10,
+			0
+		);
+
+		try {
+			// Test that the method does not throw exceptions without missing dependencies.
+			$this->shipping_controller->register_local_pickup();
+			$this->assertTrue( true, 'Method did not throw exceptions without missing dependencies' );
```
Comment (opr) [inline plugins/woocommerce/tests/php/src/Blocks/Shipping/ShippingControllerTest.php]: Why are we doing this? I'm not sure these particular logs add any value, if the test fails, we would see an error indicating why, and the stack trace would point us to which call the error originated from.

**Review by opr — CHANGES_REQUESTED** [review]
Most of the test looks fine, but there are a couple of changes I think we should make to it.

File: plugins/woocommerce/tests/php/src/Blocks/Shipping/ShippingControllerTest.php (hunk 3 above)
Comment (tjcafferkey) [reply plugins/woocommerce/tests/php/src/Blocks/Shipping/ShippingControllerTest.php]: https://github.com/woocommerce/woocommerce/pull/57154/commits/38d5ee2db60c2e47dfbd93d14fca04ea6e5bbabf

File: plugins/woocommerce/tests/php/src/Blocks/Shipping/ShippingControllerTest.php (hunk 4 above)
Comment (tjcafferkey) [reply plugins/woocommerce/tests/php/src/Blocks/Shipping/ShippingControllerTest.php]: The assertion implies the intention behind the test, that we are specifically testing it to not throw.

**Review by opr — APPROVED** [review]
Thanks for the changes 👌🏼  looks good!
