### PR TITLE
Handle 0 attribute value for variations correctly.

### LINKED ISSUE #24667: Stock Variations issue with Invalid value posted for Size
**Describe the bug**

Hi
I have an issue with a site, we updated to the latest version of woocommerce and on some products I get a strange error. We changed to the twenty nineteen theme and disabled all plugins and the error still occurs.
The product has 139 variations based on colour and size. When selecting a size and colour variation the price shows incorrectly on some of the variations, and if you add to cart you get an error stating:

"Invalid value posted for Size"

**To Reproduce**
1. Go to https://www.purplefishmedia.co.uk/product/julius-k9-idc-powerharness/
(we have deleted all plugins except woocommerce, simple ssl is enabled but the issue still occurs when its deleted. we have deleted all other products, and are using Twenty Nineteen theme)
2. Select Color: Chocolate-Brown, size 2 
3. The SKU code is the same as size 0 and price is also from size 0.
4. Add to basket
5. you will see the error "Invalid value posted for size"

**Screenshots**
backend: (screenshot below shows the backend for chocolate-brown colour size 2. you can see sku and price) https://www.dropbox.com/s/5t99ti8ys7cuhka/Edit%20product%20%E2%80%B9%20WordPress.png

**Isolating the problem (mark completed items with an [x]):**
- [x ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
`
### WordPress Environment ###

WordPress address (URL): https://www.purplefishmedia.co.uk
Site address (URL): https://www.purplefishmedia.co.uk
WC Version: 3.7.0
REST API Version: ✔ 1.0.2
Log Directory Writable: ✔
WP Version: 5.1.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_GB
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.3.9
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.66.0
OpenSSL/1.0.2t

SUHOSIN Installed: –
MySQL Version: 5.7.27-log
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.7.0
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Total Database Size: 733.97MB
Database Data Size: 613.69MB
Database Index Size: 120.28MB
wp_woocommerce_sessions: Data: 8.52MB + Index: 0.14MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 1.16MB + Index: 3.08MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_categorymeta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 10.06MB + Index: 12.19MB + Engine InnoDB
wp_csp3_subscribers: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_cspv5_pages: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
wp_ebay_accounts: Data: 0.13MB + Index: 0.00MB + Engine MyISAM
wp_ebay_auctions: Data: 4.66MB + Index: 0.03MB + Engine MyISAM
wp_ebay_categories: Data: 1.18MB + Index: 0.48MB + Engine MyISAM
wp_ebay_jobs: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_ebay_log: Data: 33.04MB + Index: 0.14MB + Engine MyISAM
wp_ebay_messages: Data: 1.25MB + Index: 0.01MB + Engine MyISAM
wp_ebay_orders: Data: 64.17MB + Index: 0.15MB + Engine MyISAM
wp_ebay_payment: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_ebay_profiles: Data: 0.02MB + Index: 0.00MB + Engine MyISAM
wp_ebay_shipping: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
wp_ebay_sites: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
wp_ebay_store_categories: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wp_ebay_transactions: Data: 244.37MB + Index: 0.85MB + Engine MyISAM
wp_elfsight_instagram_feed_widgets: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_failed_jobs: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_gf_addon_feed: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_gf_draft_submissions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_gf_entry: Data: 0.04MB + Index: 0.01MB + Engine MyISAM
wp_gf_entry_meta: Data: 0.07MB + Index: 0.07MB + Engine MyISAM
wp_gf_entry_notes: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_gf_form: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_gf_form_meta: Data: 0.03MB + Index: 0.00MB + Engine MyISAM
wp_gf_form_revisions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_gf_form_view: Data: 0.11MB + Index: 0.05MB + Engine MyISAM
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailchimp_carts: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mainwp_stream: Data: 32.49MB + Index: 20.43MB + Engine MyISAM
wp_mainwp_stream_context: Data: 12.00MB + Index: 5.76MB + Engine MyISAM
wp_mainwp_stream_meta: Data: 78.39MB + Index: 34.41MB + Engine MyISAM
wp_member_catmeta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 10.36MB + Index: 1.50MB + Engine InnoDB
wp_portfolio_catmeta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_postmeta: Data: 91.48MB + Index: 32.23MB + Engine InnoDB
wp_posts: Data: 15.42MB + Index: 5.61MB + Engine InnoDB
wp_po_plugins: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_product_catmeta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_queue: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_revslider_css: Data: 0.13MB + Index: 0.00MB + Engine InnoDB
wp_revslider_layer_animations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_navigations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_sliders: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_slides: Data: 0.16MB + Index: 0.00MB + Engine InnoDB
wp_revslider_static_slides: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_rg_form: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_rg_form_meta: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
wp_rg_form_view: Data: 0.03MB + Index: 0.02MB + Engine MyISAM
wp_rg_incomplete_submissions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_rg_lead: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_rg_lead_detail: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_rg_lead_detail_long: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_rg_lead_meta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_rg_lead_notes: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.41MB + Index: 0.23MB + Engine InnoDB
wp_term_taxonomy: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 1.05MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.11MB + Index: 0.06MB + Engine InnoDB
wp_wc_download_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.08MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.06MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_exported_csv_items: Data: 0.03MB + Index: 0.00MB + Engine MyISAM
wp_yith_wcwl: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yith_wcwl_lists: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_yoast_seo_links: Data: 0.03MB + Index: 0.01MB + Engine MyISAM
wp_yoast_seo_meta: Data: 1.84MB + Index: 1.88MB + Engine MyISAM

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (2) ###

Really Simple SSL: by Rogier Lankhorst
Mark Wolters – 3.2.5

WooCommerce: by Automattic – 3.7.0

### Inactive Plugins (0) ###


### Settings ###

API Enabled: ✔
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #207 - /shop/
Basket: #208 - /cart/
Checkout: #209 - /checkout/
My account: #210 - /my-account/
Terms and conditions: #593 - /terms-and-conditions/

### Theme ###

Name: Twenty Nineteen
Version: 1.4
Author URL: https://en-gb.wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build
personally we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 8,142
Oldest: 2019-08-23 18:08:16 +0100
Newest: 2019-09-23 16:20:38 +0100

Pending: 0
Oldest: –
Newest: –

Canceled: 0
Oldest: –
Newest: –

In-progress: 0
Oldest: –
Newest: –

Failed: 259
Oldest: 2019-06-07 12:16:35 +0100
Newest: 2019-06-11 00:52:08 +0100

````
</details>

### PR DESCRIPTION
**Pull request by peterfabian**
### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes #24667  .

### How to test the changes in this Pull Request:

1. Create a variable product with attribute having 0 and 1 values, set different prices for them.
2. Try to select variation with attribute value 1, observe the one with 0 gets selected (as the price is picked incorrectly).
3. Try to click on 'Add to cart', it fails.
4. After applying the change, both should work correctly.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Handle 0 attribute value for variations correctly.

### CODE REVIEW

File: includes/data-stores/class-wc-product-data-store-cpt.php [hunk 1]
```diff
@@ -1112,7 +1112,7 @@ public function find_matching_product_variation( $product, $match_attributes = a
 
 			// Loop over the variation meta keys and values i.e. what is saved to the products. Note: $attribute_value is empty when 'any' is in use.
 			foreach ( $variation as $attribute_key => $attribute_value ) {
-				$match_any_value = empty( $attribute_value );
+				$match_any_value = empty( $attribute_value ) && 0 != $attribute_value;
```
Comment (vedanshujain) [inline includes/data-stores/class-wc-product-data-store-cpt.php]: not a blocker, but I think we should use `!==` here.

**Review by vedanshujain — APPROVED** [review]
tested it out, works as expected. left a minor comment, other than that looks great.

File: includes/data-stores/class-wc-product-data-store-cpt.php (hunk 1 above)
Comment (peterfabian) [reply includes/data-stores/class-wc-product-data-store-cpt.php]: I actually purposefully didn't use strict comparison in order to match also '0.0' or 0 or 0.0

Maybe it would be better to be explicit, though.

Comment (kloon) [reply includes/data-stores/class-wc-product-data-store-cpt.php]: Maybe we should check for an empty string instead of using empty? I think we might get the same results if you use false or 0.0 since empty will return true on all of those. All we want to check here is if the value is an empty string?

Comment (vedanshujain) [reply includes/data-stores/class-wc-product-data-store-cpt.php]: I agree with @kloon 's suggestion above. if we check for the empty string then I guess we won't need to do any other comparison right? wdyt @peterfabian ?

Comment (peterfabian) [reply includes/data-stores/class-wc-product-data-store-cpt.php]: I was trying to be cautious in case the value could be NULL or something else that `empty` would evaluate to true. 
Fixed to only check empty string now.

**Review by vedanshujain — APPROVED** [review]
