### PR TITLE
CYS - reset products and pattern when the site doesn't have AI generated content

### LINKED ISSUE #42906: CYS - Make sure patterns are not reset to default if AI is down and the store already has AI-generated content
On the very first attempt, whenever AI is down, all products and patterns are reset to their default content:

https://github.com/woocommerce/woocommerce/assets/15730971/1813f66c-12be-4cb1-af51-09a102a713aa

Currently, on the second failed attempt, patterns are updated to their default content, while products are unchanged. We need to change this logic to ensure that if the store already has AI-generated content, both patterns and products **do not** have their content changed to the default (the user should keep the previously AI-generated content for their store), while still displaying the "AI is offline" modal (to be worked on as part of https://github.com/woocommerce/woocommerce/issues/42905).

### PR DESCRIPTION
**Pull request by gigitux**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

When the AI is offline, the store should use default products and pattern only when the store doesn't have AI generated content.

Closes #42906 .

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Make sure you have WooCommerce Beta Tester installed.
2. Enable the customize-store feature flag in Tools -> WCA Test Helper -> Features.
3. Go to WooCommerce -> Home and click on Customize your store task.
4. Set up the store.
5. Ensure that the products and images are generated
6. Go to WooCommerce -> Home and click on Customize your store task.
7. Open your browser's inspector and use Chrome's content override [feature](https://developer.chrome.com/docs/devtools/overrides/) to change the content of https://status.openai.com/api/v2/status.json call. Change status.indicator to major.
8. Refresh the page
9. Setup the store
10. Ensure that the products and images are the same as in step 5.

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [x] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [x] Enhancement - Improvement to existing functionality

#### Message 

CYS - Reset products and pattern when the site doesn't have AI generated content.

#### Comment 

</details>

### CODE REVIEW

**Review by albarin — APPROVED** [review]
LGTM

**Review by nefeline — APPROVED** [review]
Tested and confirmed the content in patterns and products are not reset if AI is down and the store owner already generated content with AI at least once, great job @gigitux ! 🎉

File: plugins/woocommerce/src/StoreApi/Routes/V1/AI/StoreInfo.php [hunk 1]
```diff
@@ -0,0 +1,85 @@
...
+	 *
+	 * @param  \WP_REST_Request $request Request object.
+	 *
+	 * @return bool|string|\WP_Error|\WP_REST_Response
+	 */
+	protected function get_route_response( \WP_REST_Request $request ) {
+		$product_updater = new ProductUpdater();
+		$patterns        = PatternsHelper::get_patterns_ai_data_post();
+
+		$products = $product_updater->fetch_product_ids( 'dummy' );
```
Comment (nefeline) [inline plugins/woocommerce/src/StoreApi/Routes/V1/AI/StoreInfo.php:66]: Solid work on identifying if the store already has AI-generated content 👌
