### PR TITLE
Show rating stars for the cross-sells products

### LINKED ISSUE #42033: Cross-Sells products on Cart block show plain text instead of star rating
## Describe the bug

Currently, when adding a product to the cart that has cross-sells products with ratings, a plain text is visible instead of the star rating.

## To reproduce

1. Add a rating to a product. 
2. Define the rated product as a cross-sells product of another product.
3. Go to the frontend and add the second product to the cart.
4. Go to the Cart and see that the cross-sells product shows the rating as plain text instead of the star rating.

## Expected behavior

Similar to the corresponding product page and the All Products block, I expect to see the rating in stars instead of as plain text.

### Cart block

Screenshot 2023-12-06 at 00 31 19</td>

<table>
<tr>
<td valign="top">Product page:
<br><br>
Screenshot 2023-12-06 at 00 32 54
</td>
<td valign="top">All Broducts block:
<br><br>
Screenshot 2023-12-06 at 00 33 35
</td>
</tr>
</table>

### PR DESCRIPTION
**Pull request by nielslange**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes #42033.

Recently, I noticed that the rating stars for the cross-sells products on the _Cart block_ were no longer visible. Instead, the rating text, e.g. _"Rated 2.5 out of 5 based on 2 customer ratings"_, was visible. This issue is caused because some required CSS definitions do not get loaded. 

In https://github.com/woocommerce/woocommerce-blocks/pull/10005, @albarin introduced the _Product Rating Stars block_. In this PR, I'm switching from the _Product Ratings block_ to the _Product Rating Stars block_, as that block loads the required CSS correctly and therefore the rating stars become visible again.

I also added missing props to the `<ProductImage>` and `<ProductRating>` components to address current TS errors. 

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Add a rating to a product. 
2. Define the rated product as a cross-sells product of another product.
3. Go to the frontend and add the second product to the cart.
4. Go to the Cart and verify that the rating stars are visible instead of the plain rating text.

<table>
<tr>
<td valign="top">Before:
<br><br>
Screenshot 2023-12-22 at 13 10 44
</td>
<td valign="top">After:
<br><br>
Screenshot 2023-12-22 at 13 07 50
</td>
</tr>
</table>

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce-blocks/assets/js/blocks/cart/cart-cross-sells-product-list/cart-cross-sells-product.tsx [hunk 1]
```diff
@@ -45,13 +44,23 @@ const CartCrossSellsProduct = ( {
...
 						/>
-						<ProductRating />
+						<ProductRating
+							isDescendentOfQueryLoop={ false }
+							isDescendentOfSingleProductBlock={ false }
+							productId={ product.id }
+							postId={ 0 }
+							shouldDisplayMockedReviewsWhenProductHasNoReviews={
+								false
+							}
```
Comment (opr) [inline plugins/woocommerce-blocks/assets/js/blocks/cart/cart-cross-sells-product-list/cart-cross-sells-product.tsx:62]: I see these are required fields, but I don't think we should have to pass them. Maybe they can be given default values in the `ProductImage` block.

Also, @albarin is there any concern with us using this block here?

**Review by opr — APPROVED** [review]
This is working well for me Niels, I suggest not merging until @albarin has responded to my comment, though.

File: plugins/woocommerce-blocks/assets/js/blocks/cart/cart-cross-sells-product-list/cart-cross-sells-product.tsx (hunk 1 above)
Comment (nielslange) [reply plugins/woocommerce-blocks/assets/js/blocks/cart/cart-cross-sells-product-list/cart-cross-sells-product.tsx:62]: Thanks for your review, @opr. I'll await @albarin's reply before taking next steps.

Comment (albarin) [reply plugins/woocommerce-blocks/assets/js/blocks/cart/cart-cross-sells-product-list/cart-cross-sells-product.tsx:62]: I think it's fine to use it in here.

**Review by albarin — APPROVED** [review]

File: plugins/woocommerce-blocks/assets/js/blocks/cart/cart-cross-sells-product-list/cart-cross-sells-product.tsx (hunk 1 above)
Comment (nielslange) [reply plugins/woocommerce-blocks/assets/js/blocks/cart/cart-cross-sells-product-list/cart-cross-sells-product.tsx:62]: Thanks for confirming this, @albarin.
