### PR TITLE
[COT] Fix inappropriate deletion of order from posts with sync off

### LINKED ISSUE #36579: [COT] Deleting an order with COT authoritative also deletes post with sync off
When the orders table is authoritative and orders sync is off, deleting an order also deletes it from the orders table as if sync was on.

### Steps to reproduce

1. Set the orders table as authoritative (Settings - Advanced - Custom data stores) with sync on.
2. Create an order, verify that it exists in both the posts table and in `wc_orders`.
3. Turn sync off.
4. Trash and then delete the order.
5. Verify that the order has been deleted from `wc_orders` (expected) but also from posts (that shouldn't happen).

The opposite case (posts authoritative) works fine: when deleting an order with sync off the order still stays in `wc_orders`.

Related: https://github.com/woocommerce/woocommerce/issues/36580

### PR DESCRIPTION
**Pull request by Konamiman**
### All Submissions:

-   [ ] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
-   [ ] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
-   [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change?

### Changes proposed in this Pull Request:

When the orders table is authoritative and sync is off, deleting and order is deleting the order record from the posts table, which is something that shouldn't happen. This commit changes that for consistency with the case when the posts table is authoritative (deleting an order from posts doesn't delete it from the orders table when sync is off).

Additionally, `OrdersTableDataStore::delete` will now trigger the `woocommerce_delete_order` action in all cases, even when the
method is called while the posts table is authoritative.

Closes #36579.

- [ ] This PR is a very minor change/addition and does not require testing instructions (if checked you can ignore/remove the next section).

### How to test the changes in this Pull Request:

1. Set the orders table as authoritative and enable sync (Settings - Advanced - Custom data stores).
2. Create an order and verify that records are created in both the orders table and the posts table.
3. Now disably sync.
4. Trash the order, then delete it.
5. Verify that the order has been deleted in the orders table **and** in the posts table (the later isn't true without this fix).
6. Repeat leaving sync on when deleting the order, verify that the order is still deleted from both tables.

### Other information:

-   [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
-   [ ] Have you written new tests for your changes, as applicable?
-   [ ] Have you created a changelog file for each project being changed, ie `pnpm --filter=<project> changelog add`?

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

File: plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableDataStore.php [hunk 1]
```diff
@@ -1766,15 +1766,15 @@ public function delete( &$order, $args = array() ) {
 
 			$order->set_id( 0 );
 
-			// If this datastore method is called while the posts table is authoritative, refrain from deleting post data.
-			if ( $order->get_data_store()->get_current_class_name() !== self::class ) {
-				return;
+			// If this datastore method is called while the posts table is authoritative, or if data synchronization is disabled,
+			// refrain from deleting post data.
```
Comment (coreymckrill) [inline plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableDataStore.php]: I found this comment a bit confusing, I think because it's saying kind of the opposite of what the `if` condition is actually doing.

```suggestion
			// Only delete post data if synchronization is enabled, or if the posts table is authoritative.
```

**Review by coreymckrill — APPROVED** [review]
> 5. Verify that the order has been deleted in the orders table **and** in the posts table (the later isn't true without this fix).

I think this should read "Verify that the order has been deleted in the orders table **but not** in the posts table". Assuming that's true, this works as expected 👍 

One suggested change to the wording of the code comment, but not a blocker.

**Review by coreymckrill — CHANGES_REQUESTED** [review]
Actually, I just noticed that this change is causing a unit test to fail, so that should get updated first.

File: plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableDataStore.php (hunk 1 above)
Comment (Konamiman) [reply plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableDataStore.php]: The comment is maybe confusing, but it's correct; it's using the fact that "A and B == not((not A) or (not B))". Your comment is better but the "or" should be an "and", I'll change it accordingly.

**Comment by Konamiman** [comment]
The failing unit test was caused by a bug that had been introduced in the pull request: deleting the order with the orders table authoritative and sync off was **not** deleting the order items (since these were deleted by `wp_delete_post`). I've pushed a commit fixing that.

File: plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableDataStore.php [hunk 2]
```diff
@@ -1987,6 +1988,28 @@ public function delete_order_data_from_custom_order_tables( $order_id ) {
 		}
 	}
 
+	/**
+	 * Deletes shared order data (created with and without custom order tables in use).
+	 *
+	 * @param int $order_id The order ID.
+	 * @return void
+	 */
+	private function delete_order_data_from_shared_tables( $order_id ) {
```
Comment (coreymckrill) [inline plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableDataStore.php]: Could you use [this inherited method](https://github.com/woocommerce/woocommerce/blob/9be843422d6a10d699ca8aa59f5e79eadb99720f/plugins/woocommerce/includes/data-stores/abstract-wc-order-data-store-cpt.php#L422) instead of adding a new one?

Comment (Konamiman) [reply plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableDataStore.php]: Good point, changed.

**Review by coreymckrill — APPROVED** [review]
👍
