### PR TITLE
Fix incorrectly used aria-describedby in add to cart button of variable product

### LINKED ISSUE #38801: `aria-describedby` attribute is set incorrectly
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Since WooCommerce 7.8.0, the `aria-describedby` attribute set on the add to cart button of variable products in products list renders an accessibility error (tested with [WAVE](https://wave.webaim.org/)).

### Expected behavior

[`aria-describedby` attribute](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-describedby) value should be set to an ID of an HTML element containing the description text.

(To fix the issue, perhaps [`aria-description` attribute](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-description) can be used instead, depending on the intention of this WooCommerce 7.8.0 code.)

### Actual behavior

In WooCommerce 7.8.0 the [value of `aria-describedby` attribute](https://github.com/woocommerce/woocommerce/blob/7.8.0/plugins/woocommerce/includes/class-wc-product-variable.php#L65) is set with the actual description text, which is incorrect.

### Steps to reproduce

1. Take a WooCommerce 7.8.0 website
2. Navigate to a page containing a list of products where at least one product is a variable product.
3. Test the page with https://wave.webaim.org/ and check for accessibility errors.

Example: https://wave.webaim.org/report#/https://themedemos.webmandesign.eu/eimear/product-category/furniture/

### WordPress Environment

n/a

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by samueljseay**
### Changes proposed in this Pull Request:

As correctly raised in #38801 the aria-describedby attribute should contain an ID pointing to an element which contains the description. To maintain backwards compatibility I have avoided renaming the filter, but rather described in the comments that it is intended to contain the text not the ID. internally in the template we generate a unique per product ID for the description and hide it using the screen-reader-text class.

Closes https://github.com/woocommerce/woocommerce/issues/38801

### How to test the changes in this Pull Request:

1. With a non-block theme such as storefront enabled, ensure you have some variable products
2. Visit the shop page
3. Inspect the "Select options" button and see that the aria-describedby attribute specifies an ID and that a span is rendered next to the button that contains the description. make sure the span is not visible.

Also you can test with the [wave chrome extension](https://chromewebstore.google.com/detail/wave-evaluation-tool/jbbplnpkjmmeebjpijfedlgcdilocofh) on trunk you'll see one error if you load the same shop page as above.

on this branch there should be no errors.

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [x] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 
Fix an accessibility error in the add to cart button template.

#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce/includes/wc-template-functions.php [hunk 1]
```diff
@@ -470,7 +470,7 @@ function wc_get_loop_class() {
 	$loop_index = wc_get_loop_prop( 'loop', 0 );
 	$columns    = absint( max( 1, wc_get_loop_prop( 'columns', wc_get_default_products_per_row() ) ) );
 
-	$loop_index ++;
+	++$loop_index;
```
Comment (samueljseay) [inline plugins/woocommerce/includes/wc-template-functions.php:473]: ugh this is auto formatting, forgot to save without. Let me know if you'd prefer me to exclude formatting changes.

File: plugins/woocommerce/templates/loop/add-to-cart.php [hunk 2]
```diff
@@ -12,7 +12,7 @@
  *
  * @see         https://woocommerce.com/document/template-structure/
  * @package     WooCommerce\Templates
- * @version     3.3.0
+ * @version     3.3.1
```
Comment (samueljseay) [inline plugins/woocommerce/templates/loop/add-to-cart.php]: I thought this was all that is required for version bump. Why would it expect 8.9.0? Is the version related to Woo rather than a version for the template?

**Comment by gigitux** [comment]
I'm not sure that I'm doing something wrong, but I don't see the `aria-describedby` label:

image

File: plugins/woocommerce/templates/loop/add-to-cart.php (hunk 2 above)
Comment (gigitux) [reply plugins/woocommerce/templates/loop/add-to-cart.php]: It looks that it depends by Woo version:  https://github.com/woocommerce/woocommerce/pull/33681

Comment (samueljseay) [reply plugins/woocommerce/templates/loop/add-to-cart.php]: Thanks will fix.

**Comment by samueljseay** [comment]
@gigitux its right there in your screenshot 😄 described by is supposed to be an id. the id points to that span with screen reader text class. (You can see that in your screenshot)

the nature of this bug was that the original implementer thought describedby should contain the label text

**Comment by samueljseay** [comment]
edit, so sorry @gigitux i didnt read your screenshot properly. my bad 😭

**Review by gigitux — APPROVED** [review]
Thanks for working on this! I can confirm that everything works as expected:

image

🚢

**Comment by OmarFPG** [comment]
We're getting reports about this [here](https://wordpress.org/support/topic/undefined-array-key-aria-describedby_text/) and [here](https://wordpress.org/support/topic/error-aria-describedby_text/). Any thoughts?

**Comment by gigitux** [comment]
Looking at the first report, I think that we can avoid the warning by ensuring that `$args['aria-describedby_text']` isn't null before returning the template: https://github.com/woocommerce/woocommerce/blob/91464aac8eb2220cd8b624170958ef25e519788e/plugins/woocommerce/templates/loop/add-to-cart.php/#L39-L42


@samueljseay What do you think?

**Comment by samueljseay** [comment]
@gigitux I have a PR up for this, https://github.com/woocommerce/woocommerce/pull/48969

I need to come back and test this with avada because supposedly the issues were with that theme (I guess it uses the template but doesn't pass the new variable name) and could not be reproduced without it.

Would you mind having a look at my approach in that PR and see if it makes sense?
