### PR TITLE
[2.6] API Fixes for 4.7

### LINKED ISSUE #12532: REST API and WP 4.7 problem type array
In WordPress 4.7 i think the validation of the rest api schema has changed. That is why now with WooCommerce 2.6 i get the error message:
`{"code":"rest_invalid_param","message":"Invalid` parameter(s): billing, shipping","data":{"status":400,"params":{"billing":"billing is not of type array.","shipping":"shipping is not of type array."}}}`

The definition as array https://github.com/woocommerce/woocommerce/blob/master/includes/api/class-wc-rest-customers-controller.php#L679 is now that it must be a numberd indexed array!

I think that the type should be changed to 'object'. See http://json-schema.org/latest/json-schema-core.html#rfc.section.4.2

In moment i don't know if there more places where it must be changed.

### PR DESCRIPTION
**Pull request by mikejolley**
Travis is reporting errors due to no ‘items’ being present in our array definitions in the API.

This converts to OBJECT and fixes tests. Tested some endpoints and it works.

Tests pass locally.

Fixes #12532

### CODE REVIEW

File: includes/api/class-wc-rest-coupons-controller.php [hunk 1]
```diff
@@ -502,7 +502,7 @@ public function get_item_schema() {
 				),
 				'meta_data' => array(
 					'description' => __( 'Order meta data.', 'woocommerce' ),
-					'type'        => 'array',
```
Comment (danielhuesken) [inline includes/api/class-wc-rest-coupons-controller.php]: I think that is a array of objects. there array is right.

Comment (mikejolley) [inline includes/api/class-wc-rest-coupons-controller.php]: @danielhuesken won't that still error in 4.7 due to having no 'items' prop?

**Comment by danielhuesken** [comment]
There are some changed that must be let as array. Because ther comes back a array of objects.

File: includes/api/class-wc-rest-coupons-controller.php (hunk 1 above)
Comment (danielhuesken) [inline includes/api/class-wc-rest-coupons-controller.php]: @mikejolley Sorry, but i can't test it in moment. But i think that when a list of items will given back that is a normal numeric array. WordPress 4.7 uses the `wp is_numeric_array()` function to check the property.

Comment (mikejolley) [inline includes/api/class-wc-rest-coupons-controller.php]: Got it.

**Comment by TimothyBJacobs** [comment]
For the ones that are arrays of objects, you should be using the `items` key.

**Comment by mikejolley** [comment]
@TimothyBJacobs you got any documentation handy for that?

**Comment by TimothyBJacobs** [comment]
Not handy, but IIRC.

```
array(
    'type' => 'array',
    'items' => array(
        'type' => 'object',
        'properties' => array() // Properties as normal
    ),
),
```

See `rest_validate_value_from_schema()`.

**Comment by TimothyBJacobs** [comment]
See actual [spec definition](http://json-schema.org/latest/json-schema-validation.html#rfc.section.5.9).

**Comment by mikejolley** [comment]
cc @claudiosanches ^ I'll do my best whilst you're away :)

File: includes/api/class-wc-rest-coupons-controller.php [hunk 2]
```diff
@@ -504,22 +504,25 @@ public function get_item_schema() {
...
-						'value' => array(
-							'description' => __( 'Meta value.', 'woocommerce' ),
-							'type'        => 'string',
-							'context'     => array( 'view', 'edit' ),
+					'items'       => array(
+						'type'       => 'object',
+						'properties' => array(
+							'id' => array(
+								'description' => __( 'Meta ID.', 'woocommerce' ),
+								'type'        => 'int',
```
Comment (justinshreve) [inline includes/api/class-wc-rest-coupons-controller.php]: This should be `integer` instead of `int`. I think some WP-API checks explicitly look for `integer`.

File: includes/api/class-wc-rest-customers-controller.php [hunk 3]
```diff
@@ -799,22 +799,25 @@ public function get_item_schema() {
...
-						'value' => array(
-							'description' => __( 'Meta value.', 'woocommerce' ),
-							'type'        => 'string',
-							'context'     => array( 'view', 'edit' ),
+					'items'       => array(
+						'type'       => 'object',
+						'properties' => array(
+							'id' => array(
+								'description' => __( 'Meta ID.', 'woocommerce' ),
+								'type'        => 'int',
```
Comment (justinshreve) [inline includes/api/class-wc-rest-customers-controller.php]: integer

File: includes/api/class-wc-rest-order-notes-controller.php [hunk 4]
```diff
@@ -393,7 +393,7 @@ public function get_item_schema() {
 		$schema = array(
 			'$schema'    => 'http://json-schema.org/draft-04/schema#',
 			'title'      => 'tax',
```
Comment (justinshreve) [inline includes/api/class-wc-rest-order-notes-controller.php]: title here should be `order_note`.

File: includes/api/class-wc-rest-order-refunds-controller.php [hunk 5]
```diff
@@ -336,164 +336,179 @@ public function get_item_schema() {
...
-						'value' => array(
-							'description' => __( 'Meta value.', 'woocommerce' ),
-							'type'        => 'string',
-							'context'     => array( 'view', 'edit' ),
+					'items'       => array(
+						'type'       => 'object',
+						'properties' => array(
+							'id' => array(
+								'description' => __( 'Meta ID.', 'woocommerce' ),
+								'type'        => 'int',
```
Comment (justinshreve) [inline includes/api/class-wc-rest-order-refunds-controller.php]: integer

File: includes/api/class-wc-rest-order-refunds-controller.php [hunk 6]
```diff
@@ -336,164 +336,179 @@ public function get_item_schema() {
...
+							'meta_data' => array(
+								'description' => __( 'Order item meta data.', 'woocommerce' ),
+								'type'        => 'array',
+								'context'     => array( 'view', 'edit' ),
+								'items'       => array(
+									'type'       => 'object',
+									'properties' => array(
+										'id' => array(
+											'description' => __( 'Meta ID.', 'woocommerce' ),
+											'type'        => 'int',
```
Comment (justinshreve) [inline includes/api/class-wc-rest-order-refunds-controller.php]: integer

File: includes/api/class-wc-rest-orders-controller.php [hunk 7]
```diff
@@ -1062,164 +1062,179 @@ public function get_item_schema() {
...
-						'value' => array(
-							'description' => __( 'Meta value.', 'woocommerce' ),
-							'type'        => 'string',
-							'context'     => array( 'view', 'edit' ),
+					'items'       => array(
+						'type'       => 'object',
+						'properties' => array(
+							'id' => array(
+								'description' => __( 'Meta ID.', 'woocommerce' ),
+								'type'        => 'int',
```
Comment (justinshreve) [inline includes/api/class-wc-rest-orders-controller.php]: integer

File: includes/api/class-wc-rest-orders-controller.php [hunk 8]
```diff
@@ -1062,164 +1062,179 @@ public function get_item_schema() {
...
+							'meta_data' => array(
+								'description' => __( 'Order item meta data.', 'woocommerce' ),
+								'type'        => 'array',
+								'context'     => array( 'view', 'edit' ),
+								'items'       => array(
+									'type'       => 'object',
+									'properties' => array(
+										'id' => array(
+											'description' => __( 'Meta ID.', 'woocommerce' ),
+											'type'        => 'int',
```
Comment (justinshreve) [inline includes/api/class-wc-rest-orders-controller.php]: integer

File: includes/api/class-wc-rest-orders-controller.php [hunk 9]
```diff
@@ -1230,69 +1245,75 @@ public function get_item_schema() {
...
```
Comment (justinshreve) [inline includes/api/class-wc-rest-orders-controller.php]: integer

File: includes/api/class-wc-rest-orders-controller.php [hunk 10]
```diff
@@ -1302,74 +1323,83 @@ public function get_item_schema() {
...
```
Comment (justinshreve) [inline includes/api/class-wc-rest-orders-controller.php]: integer

File: includes/api/class-wc-rest-orders-controller.php [hunk 11]
```diff
@@ -1379,86 +1409,95 @@ public function get_item_schema() {
...
```
Comment (justinshreve) [inline includes/api/class-wc-rest-orders-controller.php]: integer

File: includes/api/class-wc-rest-orders-controller.php [hunk 12]
```diff
@@ -1468,49 +1507,55 @@ public function get_item_schema() {
...
```
Comment (justinshreve) [inline includes/api/class-wc-rest-orders-controller.php]: integer

**Review by emdashcodes — COMMENTED** [review]
The only two issues I noticed was an incorrect 'title' for order notes, and using `int` instead of `integer`. Everything else looked good.
