### PR TITLE
Remove persistent carts in favour of longer duration sessions

### LINKED ISSUE #26374: Persistent cart doesn't get updated unless quantity is changed
**Describe the bug**
The persistent cart functionality in `WC_Cart_Session` is designed to [save the persistent cart when certain actions occur](https://github.com/woocommerce/woocommerce/blob/0c523a24a59e00ed84c3183fdc2ba8a8796a4432/includes/class-wc-cart-session.php#L54-L58) such as when the quantity of an item changes or an item is added to the cart. While this covers most use cases, we also have an ["Update cart" action](https://github.com/woocommerce/woocommerce/blob/0c523a24a59e00ed84c3183fdc2ba8a8796a4432/includes/class-wc-form-handler.php#L573
) on the cart page and an associated filter ([`woocommerce_update_cart_action_cart_updated`](https://github.com/woocommerce/woocommerce/blob/0c523a24a59e00ed84c3183fdc2ba8a8796a4432/includes/class-wc-form-handler.php#L670-L671
)) that allows 3rd parties to update the cart and even update the `$cart_updated` variable.
If this filter is used to do something with the cart (other than adding/removing), those changes won't be persisted because `WC_Cart_Session` doesn't even notice. That regardless of the value of `$cart_updated`.

In _WooCommerce Subscriptions Gifting_ we sometimes need to use this hook to add certain keys to cart contents. Those changes don't persist as per the above unless they're performed along a change in quantity. Calling [`WC_Cart_Session::persistent_cart_update()`](https://github.com/woocommerce/woocommerce/blob/0c523a24a59e00ed84c3183fdc2ba8a8796a4432/includes/class-wc-cart-session.php#L250) directly is also not an option because the `WC_Cart_Session` instance is a [protected variable in `WC_Cart`](https://github.com/woocommerce/woocommerce/blob/0c523a24a59e00ed84c3183fdc2ba8a8796a4432/includes/class-wc-cart.php#L87-L92).

While Gifting might be an edge case (and there are definitely some workarounds) I wanted to bring attention to this issue to see what we could do or if this is just the way things are intended to work (which is fine, as coupons are also not persisted right now).

**To Reproduce**
1. Log in.
1. Add an item to the cart.
1. Confirm that the persistent cart for your user is correct by looking for a row with `meta_key = '_woocommerce_persistent_cart_<your user id>'` in the `usermeta` table.
1. Activate a test plugin (or similar) with code hooked into `woocommerce_update_cart_action_cart_updated` similar to this:

    ```php
    add_filter( 'woocommerce_update_cart_action_cart_updated', function( $cart_updated ) {
	    $contents = WC()->cart->cart_contents;
    
	    foreach ( $contents as $key => &$item ) {
		    $item['custom_key'] = 'custom_value';
	    }
    
	    WC()->cart->set_cart_contents( $contents );
	    return true;
    } );
    ```
1. Click "Update cart" on the cart page.
1. Confirm that the persistent cart array doesn't contain the new key "custom_key".

**Expected behavior**
It'd be great if `WC_Cart_Session` also updated the persistent cart when the update cart action is processed. Alternatively, we could have some hooks around `persistent_cart_update()` to at least add anything we might need to save so that it gets restored when the persistent cart is.

**Isolating the problem (mark completed items with an [x]):**
- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### LINKED ISSUE #40669: Inconsistent cart item handling when login at checkout
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

There is inconsistent behavior when a logged out user, who had previously logged in and added items to a cart, logs in at checkout. Sometimes the carts merge, sometimes the logged in cart is replaced with the current cart. I tested both with and without Jetpack Dedicated Sync active with the same results. 

This was tested on WoA, Pressable,  and a locally hosted site. On the locally hosted site Jetpack was fully disabled and only WC was active

### Expected behavior

I would expect the current cart to override the existing saved cart (maybe with a prompt asking if I want to add the old items?)

### Actual behavior

The carts either merge and both old and new items are present (usually) or are replaced (periodically)

before login 
2023-10-10 at 17 08

after login
2023-10-10 at 17 08

### Steps to reproduce

On a site with Jetpack and WooCommerce

1. with a logged in user add items to the cart on a site; leave the items in the cart
2. then log the user out, refresh the page, and add more items (try this with both the same item and different items)
3. log in at checkout and check the state of the cart

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://whatisthisthing299984144.wpcomstaging.com
Site address (URL): https://whatisthisthing299984144.wpcomstaging.com
WC Version: 8.2.0.30
REST API Version: ✔ 8.2.0.30
WC Blocks Version: ✔ 11.2.0
Action Scheduler Version: ✔ 3.6.3
Log Directory Writable: ✔
WP Version: 6.3.1
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 8.0.30
PHP Post Max Size: 2 GB
PHP Time Limit: 1200
PHP Max Input Vars: 6144
cURL Version: 8.3.0
OpenSSL/1.1.1n

SUHOSIN Installed: –
MySQL Version: 10.4.25-MariaDB-log
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.2.0.30
WC Database Prefix: wp_
Total Database Size: 48.31MB
Database Data Size: 34.71MB
Database Index Size: 13.60MB
wp_woocommerce_sessions: Data: 0.09MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vp_backup_wp_actionscheduler_actions: Data: 0.06MB + Index: 0.11MB + Engine InnoDB
vp_backup_wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vp_backup_wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vp_backup_wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vp_backup_wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vp_backup_wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
vp_backup_wp_e_events: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vp_backup_wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vp_backup_wp_mailpoet_automations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
vp_backup_wp_mailpoet_automation_runs: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vp_backup_wp_mailpoet_automation_run_logs: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vp_backup_wp_mailpoet_automation_triggers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
vp_backup_wp_mailpoet_automation_versions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vp_backup_wp_mailpoet_custom_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vp_backup_wp_mailpoet_dynamic_segment_filters: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vp_backup_wp_mailpoet_feature_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vp_backup_wp_mailpoet_forms: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
vp_backup_wp_mailpoet_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
vp_backup_wp_mailpoet_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vp_backup_wp_mailpoet_newsletters: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vp_backup_wp_mailpoet_newsletter_links: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
vp_backup_wp_mailpoet_newsletter_option: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vp_backup_wp_mailpoet_newsletter_option_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vp_backup_wp_mailpoet_newsletter_posts: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vp_backup_wp_mailpoet_newsletter_segment: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vp_backup_wp_mailpoet_newsletter_templates: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
vp_backup_wp_mailpoet_scheduled_tasks: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vp_backup_wp_mailpoet_scheduled_task_subscribers: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vp_backup_wp_mailpoet_segments: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vp_backup_wp_mailpoet_sending_queues: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vp_backup_wp_mailpoet_settings: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vp_backup_wp_mailpoet_statistics_bounces: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
vp_backup_wp_mailpoet_statistics_clicks: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
vp_backup_wp_mailpoet_statistics_forms: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vp_backup_wp_mailpoet_statistics_newsletters: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vp_backup_wp_mailpoet_statistics_opens: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
vp_backup_wp_mailpoet_statistics_unsubscribes: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
vp_backup_wp_mailpoet_statistics_woocommerce_purchases: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
vp_backup_wp_mailpoet_stats_notifications: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vp_backup_wp_mailpoet_subscribers: Data: 0.02MB + Index: 0.13MB + Engine InnoDB
vp_backup_wp_mailpoet_subscriber_custom_field: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vp_backup_wp_mailpoet_subscriber_ips: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vp_backup_wp_mailpoet_subscriber_segment: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vp_backup_wp_mailpoet_subscriber_tag: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vp_backup_wp_mailpoet_tags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vp_backup_wp_mailpoet_user_agents: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vp_backup_wp_mailpoet_user_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vp_backup_wp_options: Data: 2.52MB + Index: 0.06MB + Engine InnoDB
vp_backup_wp_postmeta: Data: 1.52MB + Index: 0.14MB + Engine InnoDB
vp_backup_wp_posts: Data: 1.52MB + Index: 0.06MB + Engine InnoDB
vp_backup_wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vp_backup_wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vp_backup_wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vp_backup_wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vp_backup_wp_usermeta: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
vp_backup_wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
vp_backup_wp_user_profile_follow: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
vp_backup_wp_user_profile_reactions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
vp_backup_wp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
vp_backup_wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vp_backup_wp_wc_bookings_availability: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vp_backup_wp_wc_bookings_availabilitymeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vp_backup_wp_wc_booking_relationships: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vp_backup_wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
vp_backup_wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vp_backup_wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vp_backup_wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vp_backup_wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
vp_backup_wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
vp_backup_wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vp_backup_wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vp_backup_wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vp_backup_wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
vp_backup_wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vp_backup_wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
vp_backup_wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vp_backup_wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vp_backup_wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vp_backup_wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vp_backup_wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
vp_backup_wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vp_backup_wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vp_backup_wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vp_backup_wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vp_backup_wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vp_backup_wp_woocommerce_sessions: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
vp_backup_wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
vp_backup_wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vp_backup_wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
vp_backup_wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
vp_backup_wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vp_backup_wp_zbscrm_api_keys: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
vp_backup_wp_zbs_admlog: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
vp_backup_wp_zbs_aka: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vp_backup_wp_zbs_companies: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
vp_backup_wp_zbs_contacts: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vp_backup_wp_zbs_customfields: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
vp_backup_wp_zbs_dbmigration_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vp_backup_wp_zbs_dbmigration_posts: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
vp_backup_wp_zbs_events: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
vp_backup_wp_zbs_event_reminders: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
vp_backup_wp_zbs_externalsources: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
vp_backup_wp_zbs_forms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vp_backup_wp_zbs_invoices: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
vp_backup_wp_zbs_lineitems: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vp_backup_wp_zbs_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vp_backup_wp_zbs_meta: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vp_backup_wp_zbs_notifications: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
vp_backup_wp_zbs_object_links: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vp_backup_wp_zbs_quotes: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
vp_backup_wp_zbs_quotes_templates: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vp_backup_wp_zbs_security_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
vp_backup_wp_zbs_segments: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
vp_backup_wp_zbs_segments_conditions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
vp_backup_wp_zbs_settings: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vp_backup_wp_zbs_sys_cronmanagerlogs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
vp_backup_wp_zbs_sys_email: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
vp_backup_wp_zbs_sys_email_hist: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vp_backup_wp_zbs_tags: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
vp_backup_wp_zbs_tags_links: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
vp_backup_wp_zbs_tax_table: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
vp_backup_wp_zbs_temphash: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
vp_backup_wp_zbs_tracking: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
vp_backup_wp_zbs_transactions: Data: 0.02MB + Index: 0.14MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.06MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_abandoned_carts: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_automatewoo_customers: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_automatewoo_customer_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_guests: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_automatewoo_guest_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_log_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_queue: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_queue_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_e_events: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_gla_attribute_mapping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gla_budget_recommendations: Data: 0.22MB + Index: 0.14MB + Engine InnoDB
wp_gla_merchant_issues: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gla_shipping_rates: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gla_shipping_times: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_jetpack_sync_queue: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_automations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_automation_runs: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_mailpoet_automation_run_logs: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_mailpoet_automation_run_subjects: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_automation_triggers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_automation_versions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_custom_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_dynamic_segment_filters: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_feature_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_forms: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletters: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_newsletter_links: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_newsletter_option: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_option_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_posts: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_segment: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_templates: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_scheduled_tasks: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_scheduled_task_subscribers: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_segments: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_sending_queues: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_settings: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_statistics_bounces: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_statistics_clicks: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_statistics_forms: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_statistics_newsletters: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_statistics_opens: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_mailpoet_statistics_unsubscribes: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_statistics_woocommerce_purchases: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_mailpoet_stats_notifications: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_subscribers: Data: 0.02MB + Index: 0.23MB + Engine InnoDB
wp_mailpoet_subscriber_custom_field: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_subscriber_ips: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_subscriber_segment: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_subscriber_tag: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_tags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_user_agents: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_user_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 2.06MB + Index: 0.08MB + Engine InnoDB
wp_postmeta: Data: 0.08MB + Index: 0.03MB + Engine InnoDB
wp_posts: Data: 0.11MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_user_profile_follow: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_user_profile_reactions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_wc_bookings_availability: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_bookings_availabilitymeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_booking_relationships: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_bundle_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_bis_activity: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_bis_notifications: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_woocommerce_bis_notificationsmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_bundled_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_bundled_items: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_gc_activity: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_gc_cards: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_gc_cardsmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_prl_deploymentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_prl_deployments: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_prl_frequencies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_prl_generator_queue: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_prl_tracking_conversions: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_zbscrm_api_keys: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_zbs_admlog: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_zbs_aka: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_zbs_companies: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_zbs_contacts: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_zbs_customfields: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_zbs_dbmigration_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_zbs_dbmigration_posts: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_zbs_events: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_zbs_event_reminders: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_zbs_externalsources: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_zbs_forms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_zbs_invoices: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_zbs_lineitems: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_zbs_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_zbs_meta: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_zbs_notifications: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_zbs_object_links: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_zbs_quotes: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_zbs_quotes_templates: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_zbs_security_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_zbs_segments: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_zbs_segments_conditions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_zbs_settings: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_zbs_sys_cronmanagerlogs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_zbs_sys_email: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_zbs_sys_email_hist: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_zbs_tags: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_zbs_tags_links: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_zbs_tax_table: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_zbs_temphash: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_zbs_tracking: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_zbs_transactions: Data: 0.02MB + Index: 0.14MB + Engine InnoDB
__wp_actionscheduler_actions: Data: 1.52MB + Index: 0.61MB + Engine InnoDB
__wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_actionscheduler_logs: Data: 0.45MB + Index: 0.39MB + Engine InnoDB
__wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
__wp_e_events: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_mailpoet_automations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
__wp_mailpoet_automation_runs: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_mailpoet_automation_run_logs: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_mailpoet_automation_triggers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
__wp_mailpoet_automation_versions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_mailpoet_custom_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_mailpoet_dynamic_segment_filters: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_mailpoet_feature_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_mailpoet_forms: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
__wp_mailpoet_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
__wp_mailpoet_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_mailpoet_newsletters: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_mailpoet_newsletter_links: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
__wp_mailpoet_newsletter_option: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_mailpoet_newsletter_option_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_mailpoet_newsletter_posts: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_mailpoet_newsletter_segment: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_mailpoet_newsletter_templates: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
__wp_mailpoet_scheduled_tasks: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_mailpoet_scheduled_task_subscribers: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_mailpoet_segments: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_mailpoet_sending_queues: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_mailpoet_settings: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_mailpoet_statistics_bounces: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
__wp_mailpoet_statistics_clicks: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
__wp_mailpoet_statistics_forms: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_mailpoet_statistics_newsletters: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_mailpoet_statistics_opens: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
__wp_mailpoet_statistics_unsubscribes: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
__wp_mailpoet_statistics_woocommerce_purchases: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
__wp_mailpoet_stats_notifications: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_mailpoet_subscribers: Data: 0.02MB + Index: 0.13MB + Engine InnoDB
__wp_mailpoet_subscriber_custom_field: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_mailpoet_subscriber_ips: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_mailpoet_subscriber_segment: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_mailpoet_subscriber_tag: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_mailpoet_tags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_mailpoet_user_agents: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_mailpoet_user_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_options: Data: 3.02MB + Index: 0.08MB + Engine InnoDB
__wp_postmeta: Data: 2.38MB + Index: 0.14MB + Engine InnoDB
__wp_posts: Data: 3.36MB + Index: 0.06MB + Engine InnoDB
__wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_usermeta: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
__wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
__wp_user_profile_follow: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
__wp_user_profile_reactions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
__wp_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
__wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_wc_bookings_availability: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_wc_bookings_availabilitymeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_wc_booking_relationships: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
__wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
__wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
__wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
__wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
__wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
__wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_woocommerce_sessions: Data: 0.11MB + Index: 0.02MB + Engine InnoDB
__wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
__wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
__wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
__wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_zbscrm_api_keys: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
__wp_zbs_admlog: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
__wp_zbs_aka: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_zbs_companies: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
__wp_zbs_contacts: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_zbs_customfields: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_zbs_dbmigration_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_zbs_dbmigration_posts: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
__wp_zbs_events: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
__wp_zbs_event_reminders: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
__wp_zbs_externalsources: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
__wp_zbs_forms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_zbs_invoices: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
__wp_zbs_lineitems: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_zbs_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_zbs_meta: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_zbs_notifications: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
__wp_zbs_object_links: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_zbs_quotes: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
__wp_zbs_quotes_templates: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_zbs_security_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
__wp_zbs_segments: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
__wp_zbs_segments_conditions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
__wp_zbs_settings: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_zbs_sys_cronmanagerlogs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
__wp_zbs_sys_email: Data: 0.03MB + Index: 0.00MB + Engine InnoDB
__wp_zbs_sys_email_hist: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_zbs_tags: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
__wp_zbs_tags_links: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
__wp_zbs_tax_table: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
__wp_zbs_temphash: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
__wp_zbs_tracking: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
__wp_zbs_transactions: Data: 0.02MB + Index: 0.14MB + Engine InnoDB

### Post Type Counts ###

attachment: 8
jetpack_migration: 2
mailpoet_page: 1
page: 8
post: 8
product: 2
revision: 14
shop_order: 5
wp_global_styles: 1
wp_navigation: 1
wp_template: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (2) ###

Jetpack: by Automattic – 12.7-a.7
WooCommerce: by Automattic – 8.2.0.30

### Inactive Plugins (53) ###

Akismet Anti-spam: Spam Protection: by Automattic - Anti-spam Team – 5.3
All-in-One WP Migration: by ServMask – 7.78
AutomateWoo: by WooCommerce – 6.0.5
Avalara AvaTax: by Avalara – 2.6.1
Bookings Helper: by WooCommerce – 1.0.3
Classic Editor: by WordPress Contributors – 1.6.3
CoBlocks: by GoDaddy – 3.1.4
Companion Plugin: by Osk – 1.29
Contact Form 7: by Takayuki Miyoshi – 5.8.1
Crowdsignal Forms: by Automattic – 1.7.0
Crowdsignal Polls & Ratings: by Automattic
Inc. – 3.0.11

Easy Google Fonts: by Titanium Themes – 2.0.4
Elementor: by Elementor.com – 3.16.5
Export Import Menus: by Akshay Menariya – 1.8.0
Facebook for WooCommerce: by Facebook – 3.0.34
Google Listings and Ads: by WooCommerce – 2.5.8
Gutenberg: by Gutenberg Team – 16.7.1
Health Check & Troubleshooting: by The WordPress.org community – 1.7.0
Hello Dolly: by Matt Mullenweg – 1.7.2
Jetpack Boost: by Automattic - Jetpack Site Speed team – 2.1.1
Jetpack CRM: by Automattic - Jetpack CRM team – 6.1.0
Layout Grid: by Automattic – 1.8.4
MailPoet: by MailPoet – 4.31.0
MailPoet Premium: by MailPoet – 4.30.0
Media Library Assistant: by David Lingren – 3.12
Page Optimize: by Automattic – 0.5.4
Pinterest for WooCommerce: by WooCommerce – 1.3.10
Polylang: by WP SYNTEX – 3.5
Royal Elementor Addons: by WP Royal – 1.3.79
RSS Feed Retriever: by Theme Mason – 1.6.10
TaxJar - Sales Tax Automation for WooCommerce: by TaxJar – 4.2.0
TikTok: by TikTok – 1.1.7
User profile: by pickplugins – 2.0.19
Woo AI: by WooCommerce – 0.4.0
WooCommerce Australia Post Shipping: by WooCommerce – 2.5.7
WooCommerce Back In Stock Notifications: by WooCommerce – 1.6.4
WooCommerce Brands: by WooCommerce – 1.6.58
WooCommerce Canada Post Shipping: by WooCommerce – 2.8.3
WooCommerce EU VAT Number: by WooCommerce – 2.8.8
WooCommerce FedEx Shipping: by WooCommerce – 3.8.4
WooCommerce Gift Cards: by WooCommerce – 1.16.5
WooCommerce Google Analytics Integration: by WooCommerce – 1.8.6
WooCommerce Min/Max Quantities: by WooCommerce – 4.1.1
WooCommerce Payments: by Automattic – 6.5.1
WooCommerce Product Add-ons: by WooCommerce – 6.4.7
WooCommerce Product Bundles: by WooCommerce – 6.22.3
WooCommerce Product Recommendations: by WooCommerce – 3.0.1
WooCommerce Royal Mail: by WooCommerce – 3.0.0
WooCommerce Shipment Tracking: by WooCommerce – 2.4.0
WooCommerce Shipping & Tax: by WooCommerce – 2.3.5
WooCommerce UPS Shipping: by WooCommerce – 3.5.7
WooCommerce USPS Shipping: by WooCommerce – 4.7.4
WordPress.com Editing Toolkit: by Automattic – 3.80855

### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
object-cache.php: Memcached

### Must Use Plugins (2) ###

Health Check Troubleshooting Mode: by  – 1.8.1
WP.com Site Helper: by  –

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: bundle (bundle)
external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### WC Pages ###

Shop base: #46 - /shop/
Cart: #47 - /cart/
Checkout: #48 - /checkout/
My account: #49 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty-Three
Version: 1.1 (update to version 1.2 is available)
Author URL: https://wordpress.org
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: /wordpress/plugins/woocommerce-accelerated-frequency/8.2.0.30/packages/woocommerce-blocks/templates/notices/error.php
/wordpress/plugins/woocommerce-accelerated-frequency/8.2.0.30/packages/woocommerce-blocks/templates/notices/notice.php
/wordpress/plugins/woocommerce-accelerated-frequency/8.2.0.30/packages/woocommerce-blocks/templates/notices/success.php

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
onboarding
onboarding-tasks
product-variation-management
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: customize-store
minified-js
navigation
new-product-management-experience
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2023-10-11 12:11:54 +00:00
Options: ✔
Notes: 94
Onboarding: skipped

### Action Scheduler ###

Complete: 64
Oldest: 2023-10-10 12:12:00 +0000
Newest: 2023-10-10 13:21:16 +0000

Pending: 5
Oldest: 2023-10-10 13:22:31 +0000
Newest: 2023-11-09 12:11:53 +0000

Failed: 16
Oldest: 2023-01-02 15:07:22 +0000
Newest: 2023-10-10 13:16:15 +0000

### Status report information ###

Generated at: 2023-10-10 13:22:13 +00:00
`

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by mikejolley**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Removes the persistent cart that was being stored to usermeta for logged in users. Instead of syncing data to this persistent cart as updates occur, we can instead utilise the existing session table and increase its expiration. The removal of syncing both simplifies core logic and potentially increases performance due to less writes.

1. Deprecates all existing persistent cart functions and functionality
2. Increases the expiration of customer sessions when logged in from 48h to 7 days.
3. Introduces a `woocommerce_migrate_guest_session_to_user_session` filter to control which data is moved from a guest session to a user session after login. 
4. Merges carts when you log-in and have a guest cart.
5. ~~Moved `init_session_cookie` to hook so that `woocommerce_migrate_guest_session_to_user_session` can be consumed internally.~~ Suspect this was breaking tests so I've moved it back and put the cart merge into the session class. Not ideal but not possible to do this from `WC_Cart_Session` without moving the cookie initialisation to a later hook.
6. Added tests to simulate customer behaviour and to check cart data after initialising the session

Because we're removing the need for sync, this should mitigate #26374
Because we're removing actions tied to wp_login events and just using sessions, this should also mitigate #40669

Closes #26374
Closes #40669

Because the scope of this change involves older core functionality, I am manually tagging some additional reviewers for feedback.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

Guest = Logged out customer
User = Logged in customer

**Restoring user cart**
1. As a user, add something to your cart. Note the cart contents.
2. Log-out. Confirm cart is empty.
3. Log-in as user via account page.
4. Check cart contents contains the products again.

**Restoring user cart (merge)**
1. As a user, add something to your cart. Note the cart contents.
2. Log-out. Confirm cart is empty.
3. As a guest, add something to your cart. Note the cart contents.
4. Log-in as user via account page.
5. Check cart contents contains both sets of products.

### Testing that has already taken place:

I've tested the above steps and ran the new unit test locally.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce/includes/class-wc-session-handler.php [hunk 1]
```diff
@@ -88,54 +88,103 @@ public function init() {
...
+	}
+
+	/**
+	 * Merges the cart data from the guest session to the user session.
+	 *
+	 * @param array $data The updated session data.
+	 * @param array $user_session_data The user session data that will be overridden.
+	 * @return array The updated session data.
+	 */
+	private function migrate_cart_data( array $data, array $user_session_data ) {
```
Comment (mikejolley) [inline plugins/woocommerce/includes/class-wc-session-handler.php:311]: I did want to place this hooked via `WC_Cart_Session` class, however, because the session initializes in `init` and is not hooked in, `WC_Cart_Session` loads too late to listen. I did try to refactor to use a later hook (wp_loaded) but it caused some other test fails so I've just placed it here.

File: plugins/woocommerce/includes/class-wc-cart-session.php [hunk 2]
```diff
@@ -95,33 +94,33 @@ public function init() {
...
 		$this->cart->set_coupon_discount_totals( WC()->session->get( 'coupon_discount_totals', array() ) );
 		$this->cart->set_coupon_discount_tax_totals( WC()->session->get( 'coupon_discount_tax_totals', array() ) );
 		$this->cart->set_removed_cart_contents( WC()->session->get( 'removed_cart_contents', array() ) );
 
-		$update_cart_session = false; // Flag to indicate the stored cart should be updated.
-		$order_again         = false; // Flag to indicate whether this is a re-order.
-		$cart                = WC()->session->get( 'cart', null );
-		$merge_saved_cart    = (bool) get_user_meta( get_current_user_id(), '_woocommerce_load_saved_cart_after_login', true );
+		// Flag to indicate the stored cart should be updated. If cart totals are null, this will be true to calculate totals.
+		$update_cart_session = is_null( $cart_totals );
```
Comment (senadir) [inline plugins/woocommerce/includes/class-wc-cart-session.php:114]: I'm struggling to understand why this change was needed? as opposed to the previous one?

File: plugins/woocommerce/includes/class-wc-cart-session.php [hunk 3]
```diff
@@ -95,33 +94,33 @@ public function init() {
...
 
-		// Merge saved cart with current cart.
-		if ( is_null( $cart ) || $merge_saved_cart ) {
-			$saved_cart          = $this->get_saved_cart();
-			$cart                = is_null( $cart ) ? array() : $cart;
-			$cart                = array_merge( $saved_cart, $cart );
-			$update_cart_session = true;
-
-			delete_user_meta( get_current_user_id(), '_woocommerce_load_saved_cart_after_login' );
-		}
```
Comment (senadir) [inline plugins/woocommerce/includes/class-wc-cart-session.php]: Why was this deleted?

File: plugins/woocommerce/includes/class-wc-cart-session.php [hunk 4]
```diff
@@ -188,16 +187,40 @@ public function get_cart_from_session() {
...
+
+				/**
+				 * Fires when cart item is removed from the session.
+				 *
+				 * @since 3.6.0
+				 *
+				 * @param string     $key Cart item key.
+				 * @param array      $values Cart item values e.g. quantity and product_id.
+				 */
+				do_action( 'woocommerce_remove_cart_item_from_session', $key, $values );
```
Comment (senadir) [inline plugins/woocommerce/includes/class-wc-cart-session.php:223]: I know it already exists but should this be done here to begin with? why not at normalize stage later down the road.

File: plugins/woocommerce/includes/class-wc-cart-session.php (hunk 3 above)
Comment (senadir) [reply plugins/woocommerce/includes/class-wc-cart-session.php]: So this was moved to migrate?

File: plugins/woocommerce/includes/class-wc-session-handler.php (hunk 1 above)
Comment (senadir) [reply plugins/woocommerce/includes/class-wc-session-handler.php:311]: But why did you want it make it hooked?

File: plugins/woocommerce/tests/php/includes/class-wc-cart-persistence.php [hunk 5]
```diff
@@ -0,0 +1,138 @@
...
+		wp_set_current_user( 0 ); // Start as guest.
+	}
+
+	/**
+	 * Cleanup product and cart.
+	 */
+	public function tearDown(): void {
+		parent::tearDown();
+		if ( $this->product ) {
+			$this->product->delete( true );
```
Comment (senadir) [inline plugins/woocommerce/tests/php/includes/class-wc-cart-persistence.php:46]: Do we need to delete the user as well?

File: plugins/woocommerce/tests/php/includes/class-wc-cart-persistence.php [hunk 6]
```diff
@@ -0,0 +1,138 @@
...
+		WC()->cart->calculate_totals();
+		$guest_cart = WC()->cart->get_cart();
+
+		// Log in again.
+		$this->simulate_user_switch( $this->user_id );
+		$cart_after = WC()->cart->get_cart();
+		$this->assertEquals( $guest_cart, $cart_after );
+
+		$guest_product->delete( true );
+		WC()->session = $old_session;
```
Comment (senadir) [inline plugins/woocommerce/tests/php/includes/class-wc-cart-persistence.php]: So carts were not merged?

File: plugins/woocommerce/includes/class-wc-cart-session.php (hunk 2 above)
Comment (mikejolley) [reply plugins/woocommerce/includes/class-wc-cart-session.php:114]: Naming change?

File: plugins/woocommerce/includes/class-wc-cart-session.php (hunk 3 above)
Comment (mikejolley) [reply plugins/woocommerce/includes/class-wc-cart-session.php]: We're not using the user meta data. So merging has moved to when the session is initialized.

**Review by senadir — DISMISSED** [review]
Okay, took me some time to understand the changes but I like them and I'm onboard. The only breaking change I'm not fully on board of is that you removed merging carts. I'm not sure how will that be received.

File: plugins/woocommerce/includes/class-wc-cart-session.php (hunk 2 above)
Comment (senadir) [reply plugins/woocommerce/includes/class-wc-cart-session.php:114]: We had `$update_cart_session = false;` before, and below we would check that and null totals. Now it's just null totals, why? because in this code path, it will always be false?

File: plugins/woocommerce/includes/class-wc-cart-session.php (hunk 4 above)
Comment (mikejolley) [reply plugins/woocommerce/includes/class-wc-cart-session.php:223]: I'd be fine with moving it in another refactor but not here.

File: plugins/woocommerce/includes/class-wc-session-handler.php (hunk 1 above)
Comment (mikejolley) [reply plugins/woocommerce/includes/class-wc-session-handler.php:311]: @senadir I wanted this to take care of general session only rather than specific cart details.

File: plugins/woocommerce/tests/php/includes/class-wc-cart-persistence.php (hunk 5 above)
Comment (mikejolley) [reply plugins/woocommerce/tests/php/includes/class-wc-cart-persistence.php:46]: Yeah good shout.

File: plugins/woocommerce/tests/php/includes/class-wc-cart-persistence.php (hunk 6 above)
Comment (mikejolley) [reply plugins/woocommerce/tests/php/includes/class-wc-cart-persistence.php]: Correct. This test confirms that a guest cart is not overridden.

File: plugins/woocommerce/includes/class-wc-cart-session.php (hunk 2 above)
Comment (mikejolley) [reply plugins/woocommerce/includes/class-wc-cart-session.php:114]: I've just repurposed this instead of doing it later. We only set this flag `true` as the function progresses. We know that if the totals are null, we **do** need to update the session, so just added the null check here.

If cart totals are null, update the session.

**Comment by mikejolley** [comment]
@tjcafferkey @opr Do you want to weigh in on that?

Current behaviour: If a guest has a cart and logs in, the logged in cart (that they had previously) is merged with the guest cart.

Updated behaviour: If a guest has a cart and logs in, the logged in cart (that they had previously) is discarded.

My reasoning here is to avoid unexpected changes, especially during checkout. Because if you have a guest cart already, its likely thats your intended cart and changing it could lead to unexpected items in the order.

The logged in cart is still restored if you login without anything in your cart.

**Comment by tjcafferkey** [comment]
@mikejolley personally, I am in favour of the new behaviour since I have experienced merging of carts once logging in at a checkout _and_ also losing my guest cart after logging in. So I like that we carry over the guest cart explicitly after login.

That said, we should probably loop in @pierorocca and @yjailin for awareness on this proposed change just in case they have any objections. We will merge at the end of the week otherwise.

**Comment by opr** [comment]
> My reasoning here is to avoid unexpected changes, especially during checkout. Because if you have a guest cart already, its likely thats your intended cart and changing it could lead to unexpected items in the order.

This makes sense to me, if I'm shopping and add some items to my cart, then remember I have an account on that store, I would prefer it if the cart I was actively using stayed, rather than bringing in some items from last time I was on that store

**Comment by BusinessBloomer** [comment]
I honestly don't see why you should remove the "_merge cart_" thing. It's a good ecommerce feature.

It could be I forgot to complete the order for product A last time I logged in.

Now I get back to the site as I'm interested in product B.

I log in and - wow! - I also see I forgot to buy product A -- and buy both.

Logged in carts should persist (and merge), imho.

**Comment by senadir** [comment]
I agree that we shouldn't merge carts at Checkout, the moment you have intent to Checkout (a draft order in session, or in Checkout page), we shouldn't merge. Other places are gray area for me.

**Comment by rwkyyy** [comment]
I know a lot of people who do this (myself included), add things to cart then log in. Is there an option to chose or merge maybe?

**Comment by codeagencybe** [comment]
I don't agree that the merge function must be deleted. I prefer the behavior as it is today. 

If customers still had goods in their cart from a previous session it doesn't make sense to drop that just because im shopping again while not logged in and then loose that cart once I'm ready to buy. 

I don't understand what's wrong to keep both and merge? At least a customer can see what's in the cart after the merge and if they no longer want something just delete it. That's at least transparent and clear. Also some customers prefer to collect items in a cart and finish the checkout at a later time. That behavior would also be broken as suddenly they only have the last session items. How can that be not confusing compared to having all items? 

Imho, bad design change, bad decision and bad  user experience. Why break something that never was broken?

**Comment by senadir** [comment]
> Imho, bad design change, bad decision and bad user experience. Why break something that never was broken?

The system was broken and had less performance and did surface bugs, see the PR description please.

I do think that maybe we should make a decision for pre-checkout merging, merging at Checkout phase is the confusing part that I please we shouldn't do.

**Comment by codeagencybe** [comment]
I agree on the checkout part. You don't want unexpected things while going into payment process. 

But why not make this optional? Let the merchant choose whether they want to merge carts or not? I don't understand why a software always must dictate the direction.

**Comment by mikejolley** [comment]
@codeagencybe Software should implement sensible defaults. Not everything needs a settings page. As someone who's experienced items being added to my cart _during checkout_ and being charged extra, I can say thats **inexcusable** from a customer POV.

I should point out, developers (and merchants) do have control of the end state of the cart after guest→ customer migration via the `woocommerce_migrate_guest_session_to_user_session` hook proposed in this PR. It gives you the guest cart and logged in cart values, and filters the result.

I should also point out @BusinessBloomer forgot to mention that if you log-in with no current cart, the previous cart is restored. 

If any compromise were to happen it would be to detect if the current request is happening on cart or checkout to skip merging, but I fear that will be brittle and I'd personally prefer to err on the side of caution and only replace empty carts.

**Comment by senadir** [comment]
> But why not make this optional? Let the merchant choose whether they want to merge carts or not? I don't understand why a software always must dictate the direction.

Because every option you add is a fork in your software, and every fork adds further complexity and confusion and possibility to miss things in refactors or introduce bugs.

**Comment by mikejolley** [comment]
Just to note given the merge conflicts and work in https://github.com/woocommerce/woocommerce/pull/58140, this should be put on hold. Ill rebase when the other PRs are reviewed and/or merged because of the overlap.

**Comment by mikejolley** [comment]
I've updated the approach to merge after confirming login is never automatic on checkout, so you at least see order summary with the merged contents. Can be revisited if needed. For now this mimics status quo.

File: plugins/woocommerce/includes/wc-deprecated-functions.php [hunk 7]
```diff
@@ -1188,21 +1187,7 @@ function wc_get_log_file_name( $handle ) {
...
-	if ( ! $saved_cart ) {
-		return;
-	}
-
-	$cart = WC()->session->cart;
-
-	if ( empty( $cart ) || ! is_array( $cart ) || 0 === count( $cart ) ) {
-		WC()->session->cart = $saved_cart['cart'];
-	}
+	wc_deprecated_function( 'wc_load_persistent_cart', '2.3.0' );
```
[the remark this answers is not in the document]
Comment (mikejolley) [reply plugins/woocommerce/includes/wc-deprecated-functions.php:1190]: Was already deprecated just not with a warning.

File: plugins/woocommerce/includes/class-wc-session-handler.php [hunk 8]
```diff
@@ -280,6 +299,39 @@ private function restore_session_data() {
...
+			$data['cart'] = array_filter(
+				array_merge(
+					(array) maybe_unserialize( $data['cart'] ),
+					(array) maybe_unserialize( $user_session_data['cart'] )
+				)
+			);
+		}
+
+		return $data;
+	}
```
[the remark this answers is not in the document]
Comment (mikejolley) [reply plugins/woocommerce/includes/class-wc-session-handler.php]: Approach was revised to always merge.

File: plugins/woocommerce/tests/php/includes/class-wc-cart-persistence.php [hunk 9]
```diff
@@ -0,0 +1,145 @@
...
+		WC()->cart->calculate_totals();
+		$guest_cart = WC()->cart->get_cart();
+
+		// Log in again.
+		$this->simulate_user_switch( $this->user_id );
+		$cart_after = WC()->cart->get_cart();
+		$this->assertEquals( $cart_after, array_merge( $guest_cart, $user_cart ) );
+
+		$guest_product->delete( true );
+	}
```
[the remark this answers is not in the document]
Comment (mikejolley) [reply plugins/woocommerce/tests/php/includes/class-wc-cart-persistence.php]: Approach was revised to always merge.

File: plugins/woocommerce/includes/class-wc-session-handler.php [hunk 10]
```diff
@@ -231,12 +231,31 @@ private function clone_session_data( string $clone_from_customer_id ) {
...
+		$user_session_id    = strval( $user_id );
+		$guest_session_data = (array) $this->_data;
+		$user_session_data  = (array) $this->get_session( $user_session_id, array() );
 
-		$this->_data  = $this->get_session( $guest_session_id, array() );
-		$this->_dirty = true;
+		/**
+		 * Filters the data to be merged into the user session.
+		 *
+		 * @since 9.10.0
```
Comment (mikejolley) [inline plugins/woocommerce/includes/class-wc-session-handler.php]: 11.0.0

File: plugins/woocommerce/includes/class-wc-session-handler.php [hunk 11]
```diff
@@ -280,6 +299,39 @@ private function restore_session_data() {
...
+		}
+
+		$guest_cart_is_empty = empty( $data['cart'] );
+
+		if ( $guest_cart_is_empty ) {
+			// Replace the guest cart with the user cart.
+			$data['cart'] = $user_session_data['cart'];
+		} else {
+			// Merge carts.
+			$data['cart'] = array_filter(
```
Comment (mikejolley) [inline plugins/woocommerce/includes/class-wc-session-handler.php:326]: Add test for same product merging.

File: plugins/woocommerce/tests/php/includes/class-wc-cart-persistence.php [hunk 12]
```diff
@@ -0,0 +1,145 @@
...
+		WC()->cart->add_to_cart( $this->product->get_id(), 1 );
+		WC()->cart->calculate_totals();
+		$user_cart = WC()->cart->get_cart();
+
+		// Log out, as guest add item B.
+		$this->simulate_user_switch( 0 );
+		$guest_product = WC_Helper_Product::create_simple_product();
+		WC()->cart->add_to_cart( $guest_product->get_id(), 1 );
+		WC()->cart->calculate_totals();
+		$guest_cart = WC()->cart->get_cart();
```
Comment (mikejolley) [inline plugins/woocommerce/tests/php/includes/class-wc-cart-persistence.php:108]: merge empty user cart, when guest cart has contents

File: plugins/woocommerce/includes/class-wc-session-handler.php [hunk 13]
```diff
@@ -231,12 +231,31 @@ private function clone_session_data( string $clone_from_customer_id ) {
...
+		 * @param array $data The updated session data.
+		 * @param array $guest_session_data The guest session data.
+		 * @param array $user_session_data The user session data.
+		 */
+		$this->_data        = (array) apply_filters(
+			'woocommerce_migrate_guest_session_to_user_session',
+			$this->migrate_cart_data( $guest_session_data, $user_session_data ),
+			$guest_session_data,
+			$user_session_data
+		);
```
Comment (opr) [inline plugins/woocommerce/includes/class-wc-session-handler.php:252]: How can we prevent extensions returning incorrect/invalid data here, is there a way to validate the data?

**Review by opr — APPROVED** [review]
Thanks Mike, this is working well for me, I just want to make sure we're being super careful about the result of the new filter, what can we do to ensure nothing breaks if this is used incorrectly?

File: plugins/woocommerce/includes/class-wc-session-handler.php (hunk 13 above)
Comment (mikejolley) [reply plugins/woocommerce/includes/class-wc-session-handler.php:252]: What type of breakage? Try catch fallback?

Comment (opr) [reply plugins/woocommerce/includes/class-wc-session-handler.php:252]: Not super sure on how this could be abused, like can data be put unto the user session that causes it to break later, like objects/arrays etc. or is this stuff handled already?

I don't think a try catch at _this_ point would be useful, but maybe a check on the new session data (if that's possible)

Comment (mikejolley) [reply plugins/woocommerce/includes/class-wc-session-handler.php:252]: There are other hooks that let you manipulate sessions on load so I think the risk here is the same. We could remove the hook if its a concern?

Comment (opr) [reply plugins/woocommerce/includes/class-wc-session-handler.php:252]: I think the hook is useful, but just wanted to be sure we've thought about it. If you're not concerned then it's fine to leave, just checking.

Comment (mikejolley) [reply plugins/woocommerce/includes/class-wc-session-handler.php:252]: Yeah I'm not concerned. It typecasts to array so fatal breakage is at least avoided. Worse case your cart goes bye bye.

**Comment by KPYahoo** [comment]
@mikejolley @opr @senadir  @BusinessBloomer 

We are store owners with a couple of websites using Woocommerce. We strongly urge reconsideration and rollback of this change. Removing persistent carts in favor of longer-duration sessions is not just a technical refactor — it has real-world consequences for stores and customers.

1. Real-world shopping behavior depends on persistent carts
As @rwkyyy commented 
> “I know a lot of people who do this (myself included), add things to cart then log in.”
This isn’t an edge case — customers browse, add items, and only then log in to complete checkout. Persistent carts make that seamless. Removing them means those customers will often see an empty cart after logging in.

2. Customer frustration risks lost sales
Echoed by @codeagencybe 
>“If customers still had goods in their cart from a previous session it doesn't make sense to drop that…”
Dropping carts not only frustrates shoppers, it erodes trust. It makes flows feel broken or even punitive, not user-friendly.

3. Actual customer complaint — not just theory
This isn’t hypothetical. A real customer of ours took the trouble to send this message (screenshot attached):
image

You would be AWARE most customers won’t even report it — they’ll silently abandon the site, taking their order with them. That’s a direct sales loss.
In this specific case, since we are on an older version of Woocommerce, we will be going down the rabbit hole to see what caused this issue on our store. God help us!

4. The silent damage
Most store owners are not technical enough to follow PR discussions or GitHub changes. They’ll be caught completely unaware, wondering why sales dropped or customers are complaining. This kind of regression will slip under the radar until revenue is already impacted.

5. Technical simplicity vs. business reliability
Yes, simplifying to a single session model sounds clean from a developer perspective. But real stores prioritize customer experience over architectural elegance. Persistence across logins is a business-critical feature, not a developer convenience.

6. A better approach
Revert the removal and restore persistent cart functionality as the default.
Provide a setting or filter to disable persistent carts for those who truly don’t want them.
Maintain backward compatibility so merchants are not blindsided.

In the **real world**, customers and store owners care about keeping carts intact to complete sales — this is business-critical. Developers may see value in cleaner session code, but “tech for the sake of tech” should never come at the cost of breaking a proven, revenue-generating shopping flow.

Hopefully better sense will prevaill! 

Have a nice day!

**Comment by mikejolley** [comment]
@KPYahoo Honestly from that comment I think you've misunderstood the change. The ability to log-in and keep your cart is not affected. 

**The change is how persistent carts are stored within the database.** Previously they'd be stored in the users table as meta. Now they remain in the sessions table. The duration of a persistent cart is shorter (we're talking a week), but the ability to log in and resume the session is still in place. As is cart session merging, like before.
