### PR TITLE
Fix TS errors @woocommerce/beta-tester and re-enable type checking

### LINKED ISSUE #53944: [React 18 update] Fix TS errors @woocommerce/beta-tester and re-enable type checking
After updating the admin areas to React 18 in https://github.com/woocommerce/woocommerce/pull/53531 we need to fix the TS errors that appeared in `plugins/woocommerce-beta-tester`.
The errors from a couple of packages `packages/js/` were silenced in the package's tsconfig files.
These errors need to be fixed before the WC 9.7 release and the `noCheck` option removed from the tsconfig file.

More details in pdV5qK-JW-p2

### PR DESCRIPTION
**Pull request by chihsuan**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes https://github.com/woocommerce/woocommerce/issues/53944.

This PR fixes TypeScript errors in the WooCommerce Beta Tester plugin and re-enable type checking.

- Removed noCheck option
- Added proper type checking
- Added missing WordPress package dependencies
- Updated data store registration to use createReduxStore

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Confirm you can build the beta tester plugin without TypeScript errors. `pnpm install && pnpm --filter="@woocommerce/plugin-woocommerce-beta-tester" build`
2. Test around beta tester plugin and confirm it works as expected.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce-beta-tester/src/live-branches/components/BranchList.tsx [hunk 1]
```diff
@@ -153,7 +150,9 @@ export const BranchList = ( { branches }: { branches: Branch[] } ) => {
 					) }
 					{ ! activeBranch && <WooCommerceVersionInfo /> }
 				</CardBody>
-				<CardFooter></CardFooter>
+				<CardFooter>
+					<Fragment />
+				</CardFooter>
```
Comment (chihsuan) [inline plugins/woocommerce-beta-tester/src/live-branches/components/BranchList.tsx:155]: Added a Fragment because children is a required prop in the `CardFooter` component.

File: plugins/woocommerce-beta-tester/src/tools/data/action-types.ts [hunk 2]
```diff
@@ -0,0 +1,17 @@
+const TYPES = {
```
Comment (rjchow) [inline plugins/woocommerce-beta-tester/src/tools/data/action-types.ts]: Was the duplicate actions.js and actions.ts accidental?

**Review by rjchow — APPROVED** [review]
Aside from the duplicate actions.{ts,js}, tested well, thank you!

**Review by moon0326 — APPROVED** [review]
Tested well and build command worked without any errors 👍 🚀

File: plugins/woocommerce-beta-tester/src/tools/data/action-types.ts (hunk 2 above)
Comment (chihsuan) [reply plugins/woocommerce-beta-tester/src/tools/data/action-types.ts]: Yes, it was accidental. I'll remove the duplicate file. Thanks!

Comment (chihsuan) [reply plugins/woocommerce-beta-tester/src/tools/data/action-types.ts]: Removed in d1921047c5ec5b2fdce48e47012e9b3fa971cc83
