### PR TITLE
Send $product_name through woocommerce_cart_item_name filter once

### LINKED ISSUE #38744: woocommerce_cart_item_name filter is applied twice
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

The `woocommerce_cart_item_name` filter in the 7.8.0 [cart.php](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/templates/cart/cart.php#L49) template is applied twice. That leads to issues with plugins that use the filter to adjust the cart item name (as the additional info may be added twice).

### Expected behavior

Do only apply the filter once or pass the original, non-filtered `$_product->get_name()` as first parameter to the next filter call instead of `$product_name` (which already has been filtered).

### Actual behavior

The filter is being applied twice. First on creating the variable:

`$product_name = apply_filters( 'woocommerce_cart_item_name', $_product->get_name(), $cart_item, $cart_item_key );`

and during output:

`echo wp_kses_post( apply_filters( 'woocommerce_cart_item_name', $product_name, $cart_item, $cart_item_key ) . '&nbsp;' );`

### Steps to reproduce

1. Add a snippet to your functions.php:

```php
add_filter( 'woocommerce_cart_item_name', function( $cart_item_name ) {
   return $cart_item_name . ' - test';
} );
```
2. Add a product to cart
3. See how the `-test` suffix is added twice.

### WordPress Environment

Latest WP and Woo version. Latest storefront theme.

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by helgatheviking**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Echo out filtered product name instead of filtering it again

 Closes #38744.

### How to test the changes in this Pull Request:

Follow the repro steps in the original issue.

1- Add this snippet
```
add_filter( 'woocommerce_cart_item_name', function( $cart_item_name ) {
   return $cart_item_name . ' - test';
} );
```

2- Add an item to the cart. 
3- Go to cart.
4- Without the patch `-test` should appear twice. With the patch, `-test` should appear only once.

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement

#### Message 

Eliminate woocommerce_cart_item_name filter running twice on cart.php template

#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce/templates/cart/cart.php [hunk 1]
```diff
@@ -93,15 +93,15 @@
 							 * @param array $cart_item The product in the cart.
 							 * @param string $cart_item_key Key for the product in the cart.
 							 */
-							echo wp_kses_post( apply_filters( 'woocommerce_cart_item_name', $product_name, $cart_item, $cart_item_key ) . '&nbsp;' );
+							echo wp_kses_post( apply_filters( 'woocommerce_cart_item_name', $_product->get_name(), $cart_item, $cart_item_key ) . '&nbsp;' );
```
Comment (rrennick) [inline plugins/woocommerce/templates/cart/cart.php]: We should remove this filter and just pass `$product_name . '&nbsp;'`. Same with the second change.

File: plugins/woocommerce/templates/cart/cart.php [hunk 2]
```diff
@@ -12,7 +12,7 @@
  *
  * @see     https://docs.woocommerce.com/document/template-structure/
  * @package WooCommerce\Templates
- * @version 7.8.0
+ * @version 7.8.2
```
Comment (rrennick) [inline plugins/woocommerce/templates/cart/cart.php]: If we get this merged this afternoon, I can request it be included in 7.9.0.

**Review by rrennick — CHANGES_REQUESTED** [review]
@helgatheviking Thanks for submitting this. I apologize for not catching that on the original PR.

File: plugins/woocommerce/templates/cart/cart.php (hunk 1 above)
Comment (helgatheviking) [reply plugins/woocommerce/templates/cart/cart.php]: whelp, I thought I _had_ done that. must not have committed it. lemme fix it.

File: plugins/woocommerce/templates/cart/cart.php [hunk 3]
```diff
@@ -93,15 +93,15 @@
...
+							echo wp_kses_post( apply_filters( 'woocommerce_cart_item_name', $_product->get_name(), $cart_item, $cart_item_key ) . '&nbsp;' );
 						} else {
 							/**
 							 * Filter the product name.
 							 *
 							 * @since 7.8.0
 							 * @param string $product_url URL the product in the cart.
 							 */
-							echo wp_kses_post( apply_filters( 'woocommerce_cart_item_name', sprintf( '<a href="%s">%s</a>', esc_url( $product_permalink ), $product_name ), $cart_item, $cart_item_key ) );
+							echo wp_kses_post( apply_filters( 'woocommerce_cart_item_name', sprintf( '<a href="%s">%s</a>', esc_url( $product_permalink ), $_product->get_name() ), $cart_item, $cart_item_key ) );
```
Comment (helgatheviking) [inline plugins/woocommerce/templates/cart/cart.php:97]: @rrennick thoughts on this one? why should the filter apply to the `<a>` element only in this case?

File: plugins/woocommerce/templates/cart/cart.php (hunk 1 above)
Comment (helgatheviking) [reply plugins/woocommerce/templates/cart/cart.php]: sidenote, why the `&nbsp;`

Comment (rrennick) [reply plugins/woocommerce/templates/cart/cart.php]: There's a hook after the if that allows outputting additional content so I think it may have been originally added to add spacing.

File: plugins/woocommerce/templates/cart/cart.php (hunk 2 above)
Comment (rrennick) [reply plugins/woocommerce/templates/cart/cart.php]: I bumped the version to 7.9.0.

File: plugins/woocommerce/templates/cart/cart.php (hunk 3 above)
Comment (rrennick) [reply plugins/woocommerce/templates/cart/cart.php:97]: Good catch. If the link is passed through the text is appended after the link. We should restore this back to the pre-7.8.0 change which is https://github.com/woocommerce/woocommerce/pull/37830/files#diff-d3262e00ef9c075cc1fc7ae1dcaea582a69a9bbf278bf5b35ef73236168e889bL82

Comment (helgatheviking) [reply plugins/woocommerce/templates/cart/cart.php:97]: It looks like that commit is just adding some docblock. The `<a>` element is still filtered there. I limited the filter to only the link text in my PR because that made sense to me, but it's a deviation from how it used to be. Just to confirm, I think you are saying you want me to bring that back? 

https://github.com/faisal-alvi/woocommerce/commit/70cbbeebd422b7c592a49442dd31f83e976a9838

**Comment by barryhughes** [comment]
✍🏼 Not something introduced by this PR, and so doesn't necessarily need to be changed here, but I think the `@since` tag for this hook should be `2.1.0`, not `7.8.0` (we're documenting when the hook was introduced, not when the hook documentation was added).

File: plugins/woocommerce/templates/cart/cart.php [hunk 4]
```diff
@@ -85,23 +87,9 @@
...
+							echo wp_kses_post( $product_name . '&nbsp;' );
 						} else {
-							/**
-							 * Filter the product name.
-							 *
-							 * @since 7.8.0
-							 * @param string $product_url URL the product in the cart.
-							 */
-							echo wp_kses_post( apply_filters( 'woocommerce_cart_item_name', sprintf( '<a href="%s">%s</a>', esc_url( $product_permalink ), $product_name ), $cart_item, $cart_item_key ) );
+							printf( '<a href="%s">%s</a>', esc_url( $product_permalink ), wp_kses_post( $product_name ) );
```
Comment (barryhughes) [inline plugins/woocommerce/templates/cart/cart.php]: @rrennick @helgatheviking — this is a *lot* cleaner than how things used to be ... but ... the previous convention (ie, what we had before 7.8.0, where the hook [existed twice](https://github.com/woocommerce/woocommerce/blob/7.0.0/plugins/woocommerce/templates/cart/cart.php#L79-L83) and supplied a product name in one case and a link in another) was in place for a long time.

Can we consider the impact on existing third party code doing something like the following?

```php
add_filter( 'woocommerce_cart_item_name', function () {
	return '<a href="foo-bar">Foo Bar</a>';
} );
```

This is not a hypothetical, as I found code doing essentially this (though of course I've simplified it greatly) when searching the marketplace. This would not have presented a problem prior to 7.8.0, regardless of [which branch](https://github.com/woocommerce/woocommerce/blob/7.0.0/plugins/woocommerce/templates/cart/cart.php#L79-L83) was followed in relation to our hook. Now, however, the above code would run the risk of output looking like:

```html
<a href="PRODUCTURL"><a href="foo-bar">Foo Bar</a></a>
```

What do we think?

File: plugins/woocommerce/templates/cart/cart.php (hunk 3 above)
Comment (rrennick) [reply plugins/woocommerce/templates/cart/cart.php:97]: > I think you are saying you want me to bring that back?

Yes. I realize what is being passed to the filter is inconsistent but that's the way it was prior to the 7.8 PR.

File: plugins/woocommerce/templates/cart/cart.php (hunk 4 above)
Comment (rrennick) [reply plugins/woocommerce/templates/cart/cart.php]: @barryhughes Yup. We need to revert the filters that pass the `<a>` tags back to the pre 7.8.0 implementation. The test code in the description would add ` - test` after the link pre 7.8.0 while 7.8.0 adds it to the link text and after the link.

Comment (barryhughes) [reply plugins/woocommerce/templates/cart/cart.php]: Yep, sorry now I re-read your earlier comments I see I'm repeating the same thing.

**Comment by rrennick** [comment]
@helgatheviking Thanks for the help with this. I made the last change to the PR ecause we are running a tight timeline to get it included in 7.9.0.

File: plugins/woocommerce/templates/cart/cart.php [hunk 5]
```diff
@@ -85,23 +87,9 @@
...
-							/**
-							 * Filter the product name.
-							 *
-							 * @since 7.8.0
-							 * @param string $product_name Name of the product in the cart.
-							 * @param array $cart_item The product in the cart.
-							 * @param string $cart_item_key Key for the product in the cart.
-							 */
-							echo wp_kses_post( apply_filters( 'woocommerce_cart_item_name', $product_name, $cart_item, $cart_item_key ) . '&nbsp;' );
+							echo wp_kses_post( $product_name . '&nbsp;' );
```
Comment (barryhughes) [inline plugins/woocommerce/templates/cart/cart.php:90]: Solves the problem ... a little nervous because it means that callbacks on `woocommerce_cart_item_name` may be fired twice for the same item (once via line 51 and again via line 92, unless the permalink is empty), but I don't know we can do too much about that now the product name is used in the remove item link.

File: plugins/woocommerce/templates/cart/cart.php [hunk 6]
```diff
@@ -85,23 +87,9 @@
...
 						} else {
-							/**
-							 * Filter the product name.
-							 *
-							 * @since 7.8.0
-							 * @param string $product_url URL the product in the cart.
-							 */
-							echo wp_kses_post( apply_filters( 'woocommerce_cart_item_name', sprintf( '<a href="%s">%s</a>', esc_url( $product_permalink ), $product_name ), $cart_item, $cart_item_key ) );
+							echo wp_kses_post( apply_filters( 'woocommerce_cart_item_name', sprintf( '<a href="%s">%s</a>', esc_url( $product_permalink ), $_product->get_name() ), $cart_item, $cart_item_key ) );
```
Comment (barryhughes) [inline plugins/woocommerce/templates/cart/cart.php:97]: Hooks need to be documented for the required PHPCS check to pass. We can follow the [duplicate hook convention](https://developer.wordpress.org/coding-standards/inline-documentation-standards/php/#4-1-duplicate-hooks), though.

**Review by barryhughes — COMMENTED** [review]
Nice: if we can get the required checks passing, it should be good to merge.

**Comment by jorgeatorres** [comment]
Hi @helgatheviking,

Thanks for your contribution 💯. I've taken the liberty of fixing the version in the filter docblock (as suggested by @barryhughes) and added `wp_strip_all_tags()` around `$product_name` when it is used in an attribute. Otherwise, things looked good to me, so I'm approving.

On account of those changes, though, I'm asking for a review from @vedanshujain, so he can give the final approval.

**Review by jorgeatorres — APPROVED** [review]

**Comment by helgatheviking** [comment]
Hey gang, thanks for carrying this across the finish line!

**Review by Konamiman — APPROVED** [review]
