### PR TITLE
[Accessibility] Fix/43628 view button orders page

### LINKED ISSUE #43628: Accessibility: Ambiguous view link on My Account orders table
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

On the My Account Orders page, the orders table contains a "View" button in the actions table that does not include any reference to the account number, either in visible text or an aria-label.
https://github.com/woocommerce/woocommerce/blob/758df4854d7b627fc26eb5c0860dc492dea6a06e/plugins/woocommerce/templates/myaccount/orders.php#L70

### Expected behavior

The View link should be unique so that when multiple orders are present in the table, it is possible to distinguish each View link from one another.

Add an aria-label that includes the order number to the link like this:
`<a href="https://shop.equalizedigital.com/my-account/view-order/518/" class="woocommerce-button wp-element-button button view" aria-label="View order number 518">View</a>`

### Actual behavior

Links are ambiguous

### Steps to reproduce

See code linked above.

### WordPress Environment

N/A

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by amesplant**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes #43628

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

**Pre-requisite:**
- You should be a registered customer with several completed orders placed.

**Steps:**
1. Enable screen reader on your computer.
2. In your WooCommerce store frontend, log in as a customer in the "My Account" page.
3. Go to My Account > Orders.
7. Press tab until the focus lands on the "View" button of an completed order.
8. Verify that the screen reader announces the View button link together with the order number.
9. Verify that the screen reader does this for each of the other View buttons.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [x] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

**Comment by amesplant** [comment]
@dkotter sending to you for Code Review

File: plugins/woocommerce/templates/myaccount/orders.php [hunk 1]
```diff
@@ -68,7 +68,7 @@
 
 								if ( ! empty( $actions ) ) {
 									foreach ( $actions as $key => $action ) { // phpcs:ignore WordPress.WP.GlobalVariablesOverride.Prohibited
-										echo '<a href="' . esc_url( $action['url'] ) . '" class="woocommerce-button' . esc_attr( $wp_button_class ) . ' button ' . sanitize_html_class( $key ) . '">' . esc_html( $action['name'] ) . '</a>';
+										echo '<a href="' . esc_url( $action['url'] ) . '" class="woocommerce-button' . esc_attr( $wp_button_class ) . ' button ' . sanitize_html_class( $key ) . '" aria-label="' . esc_attr( sprintf( __( 'View order number %s', 'woocommerce' ), $order->get_order_number() ) ) . '">' . esc_html( $action['name'] ) . '</a>';
```
Comment (dkotter) [inline plugins/woocommerce/templates/myaccount/orders.php:79]: We'll need a translators comment here since there's a placeholder, see https://github.com/woocommerce/woocommerce/actions/runs/9896640866/job/27339537309?pr=49424#step:4:27

**Review by dkotter — CHANGES_REQUESTED** [review]
Left a minor comment but we may also need to bump the template version number

File: plugins/woocommerce/templates/myaccount/orders.php (hunk 1 above)
Comment (amesplant) [reply plugins/woocommerce/templates/myaccount/orders.php:79]: Thanks @dkotter I have added in the translator comment.

**Review by amesplant — COMMENTED** [review]
@dkotter I have added a translator comment and bumped the template version.

File: plugins/woocommerce/templates/myaccount/orders.php [hunk 2]
```diff
@@ -68,7 +68,8 @@
 
 								if ( ! empty( $actions ) ) {
 									foreach ( $actions as $key => $action ) { // phpcs:ignore WordPress.WP.GlobalVariablesOverride.Prohibited
-										echo '<a href="' . esc_url( $action['url'] ) . '" class="woocommerce-button' . esc_attr( $wp_button_class ) . ' button ' . sanitize_html_class( $key ) . '">' . esc_html( $action['name'] ) . '</a>';
+                                        /* translators: 1: button label 2: order number */
+                                        echo '<a href="' . esc_url( $action['url'] ) . '" class="woocommerce-button' . esc_attr( $wp_button_class ) . ' button ' . sanitize_html_class( $key ) . '" aria-label="' . esc_attr( sprintf( __( 'View order number %s', 'woocommerce' ), $order->get_order_number() ) ) . '">' . esc_html( $action['name'] ) . '</a>';
```
Comment (dkotter) [inline plugins/woocommerce/templates/myaccount/orders.php]: Getting another PHPCS error related to using spaces instead of tabs for indentation: https://github.com/woocommerce/woocommerce/actions/runs/9908739007/job/27375395683?pr=49424#step:4:27

**Review by dkotter — CHANGES_REQUESTED** [review]

File: plugins/woocommerce/templates/myaccount/orders.php (hunk 2 above)
Comment (amesplant) [reply plugins/woocommerce/templates/myaccount/orders.php]: @dkotter this should now be fixed

**Review by dkotter — APPROVED** [review]

**Comment by dkotter** [comment]
@ankitguptaindia @qasumitbagthariya This is ready for QA

File: plugins/woocommerce/changelog/fix-43628-view-button-orders-page [hunk 3]
```diff
@@ -0,0 +1,4 @@
+Significance: minor
+Type: fix
+
+Add aria-label on View oder button to aid in accessibility for screen readers
```
Comment (mikejolley) [inline plugins/woocommerce/changelog/fix-43628-view-button-orders-page]:
```suggestion
Add aria-label on View order button to aid in accessibility for screen readers
```

File: plugins/woocommerce/templates/myaccount/orders.php (hunk 1 above)
Comment (mikejolley) [reply plugins/woocommerce/templates/myaccount/orders.php:79]: I don't think this translator comment is correct. The string is `View order number %s` which contains one placeholder, so it should read:

```
/* translators: %s: order number */
```

**Review by mikejolley — CHANGES_REQUESTED** [review]
Thanks for the contribution. I took a look and found 2 small issues. Functionality wise this works.

**Comment by amesplant** [comment]
Thanks @mikejolley for the catch .. I updated and pushed the fix.

**Comment by qasumitbagthariya** [comment]
QA Update ✅
---

**Testing Environment** 

<Details>

- WordPress: 6.6
- Theme: Storefront 4.6.0
- WooCommerce - WooCommerce - Dev version with this fix specific branch.
- PHP: 8.0.30
- Web Server: Nginx 1.20.2
- Browser: Chrome 
- OS: macOS Ventura 13.3 
- Git Branch: [Manussakis:fix/43631](amesplant:fix/43628-view-button-orders-page)

</Details>

Changes work as expected. ✅

View button that also announces the order number  ✅

*Functional Demo / Screencast* -

https://github.com/user-attachments/assets/240b1afe-84f7-4c55-a114-bb80ce6fb6ff

**Comment by qasumitbagthariya** [comment]
@Manussakis please remove [WIP] from the title and take this PR out of draft.

**Comment by Manussakis** [comment]
> @Manussakis please remove [WIP] from the title and take this PR out of draft.

@qasumitbagthariya I am not in charge of this PR, @amesplant is 🙂

**Comment by amesplant** [comment]
> @Manussakis please remove [WIP] from the title and take this PR out of draft.

I remove the [WIP] and set it ready for review (taking it out of draft).

**Review by mikejolley — APPROVED** [review]
Thanks for the changes. This template already had a version bump to 9.2 so that lint can be ignored.

**Review by mikejolley — CHANGES_REQUESTED** [review]
Sorry, I missed something. The change is fine and works but there is incorrect indenting picked up by the CI job. Space indenting before the `/* translators: %s: order number */`. This needs to be fixed before we can merge.

**Comment by amesplant** [comment]
> Sorry, I missed something. The change is fine and works but there is incorrect indenting picked up by the CI job. Space indenting before the `/* translators: %s: order number */`. This needs to be fixed before we can merge.

Sorry about that @mikejolley, fixed the indentation

**Review by mikejolley — APPROVED** [review]

**Comment by rodelgc** [comment]
Hi @amesplant 👋 

I updated the testing instructions to be a bit more detailed. The new set of steps now clearly say which "View" button was being referred to without digging into the details of the PR and the linked issue. I also added a step to clarify that this PR should be tested as a registered customer. During release testing, we do final rounds of checks on the PRs, and we rely on the clarity of their testing instructions to avoid the danger of assuming details as the release date nears.

**Comment by christopher-bio** [comment]
Hi @amesplant 

Thank you very much for this contribution. I was surprised and happy to see this going live.

Just one small note: All 3 actions (Pay order, view order, cancel order) get the same aria-label now. Are there any plans to have more specific aria-labels for the different actions?

**Comment by Manussakis** [comment]
Hey @christopher-bio 👋

Thanks for flagging that. I created the https://github.com/woocommerce/woocommerce/issues/51404 issue and will fix it ASAP.
