### PR TITLE
Use string instead of number for email logo width default value

### LINKED ISSUE #56752: Value of `woocommerce_email_header_image_width` email setting is a string in some external environments instead of a number.
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

`woocommerce_email_header_image_width` is a number in our default wp-env localhost testing environment, while it's a string on our Pressable testing environment.

#### On wp-env localhost:
Image

#### On Pressable
Image

### Expected behavior

The value of `woocommerce_email_header_image_width` should consistently be a number across all environments.

### Actual behavior

The value of `woocommerce_email_header_image_width` is a string on Pressable.

### Steps to reproduce

1. In a Pressable site, make an authenticated request to `/wp-json/wc/v3/settings/email/woocommerce_email_header_image_width`.
2. Notice that the `value` in the response body is a numerical string, instead of a number.

### WordPress Environment

WP 6.7
WC 9.8 Beta

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by NeosinneR**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

This PR changes the `woocommerce_email_header_image_width` type from number to string. The reason is that there is no harm in using a string, and it's more difficult to ensure that the value is everywhere a number, when in the database, it's saved in the LONGTEXT column.

Closes #56752, closes WOOPLUG-3638.

(For Bug Fixes) Bug introduced in PR #54897.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Go to **Settings > Permalinks** and ensure that anything other than `Plain` is chosen (otherwise REST API doesn't work). 
2. Go to **User > Profile** and create a new Application password (note the password).
3. Locally, you can test that `curl -u "admin:APPLICATION_PASSWORD" "http://localhost:8888/wp-json/wc/v3/settings/email/woocommerce_email_header_image_width"` return strings for both `value` and `default`.

### Testing that has already taken place:

I've tested locally that both values are strings.

### CODE REVIEW

File: plugins/woocommerce/includes/admin/settings/class-wc-settings-emails.php [hunk 1]
```diff
@@ -149,7 +149,7 @@ protected function get_settings_for_default_section() {
 				'title'    => __( 'Logo width (px)', 'woocommerce' ),
 				'id'       => 'woocommerce_email_header_image_width',
 				'desc_tip' => '',
-				'default'  => 120,
+				'default'  => '120',
 				'type'     => 'number',
```
Comment (websupporter) [inline plugins/woocommerce/includes/admin/settings/class-wc-settings-emails.php:153]: shouldnt the `type` be `string` then?

Comment (NeosinneR) [reply plugins/woocommerce/includes/admin/settings/class-wc-settings-emails.php:153]: This is used for `<input type="HERE">` - I used number so there is HTML validation for this being a number and also it adds the arrows to the input and allows changing the value with arrows. 
Screenshot 2025-04-04 at 09 59 06

Comment (websupporter) [reply plugins/woocommerce/includes/admin/settings/class-wc-settings-emails.php:153]: So that type field is used to determine the input type?

**Comment by websupporter** [comment]
Have we explored what it would take to ensure that always numbers are returned?

File: plugins/woocommerce/includes/admin/settings/class-wc-settings-emails.php (hunk 1 above)
Comment (NeosinneR) [reply plugins/woocommerce/includes/admin/settings/class-wc-settings-emails.php:153]: Yes. So you can also use anything there, e.g. `my_custom_component` and render whatever there. Or you can use any of the predefined types, which will render the setting row for you https://github.com/woocommerce/woocommerce/blob/6376d46d9c2aca9d097f4a37669e032424094818/plugins/woocommerce/includes/admin/class-wc-admin-settings.php#L333-L367

**Comment by NeosinneR** [comment]
> Have we explored what it would take to ensure that always numbers are returned?

@websupporter not really, because I don't necessarily see the value of it being a number all the time. The way it's implemented now implies it should be a number, because in https://github.com/woocommerce/woocommerce/blob/5a787b309bcc16be3fc6a546f4e4dead1fcd13ad/plugins/woocommerce/templates/emails/email-styles.php#L167-L169 we append `px`, but number-like is good enough, even if the type is string. Not sure if it's worth trying to force the number there.

**Comment by websupporter** [comment]
Reading the issue again:
> Expected behavior
> The value of woocommerce_email_header_image_width should consistently be a number across all environments.

I think we should investigate why it is a string in Pressable and see how we can ensure it is numeric. Changing the default to a string while claiming the type is a number; that feels inconsistent to me and atm I cant evaluate whether  it solves the issue.

**Comment by NeosinneR** [comment]
@websupporter the `default` being a number (`120` instead of `'120'`) might have been the wrong assumption from the start. So while the issue is reported to expect it to be number in all environments, it's based on (my) wrong assumption from the start.

Looking at other number-like settings in Core, all of them use `'type' => 'number'` while having the default value string:

https://github.com/woocommerce/woocommerce/blob/5a787b309bcc16be3fc6a546f4e4dead1fcd13ad/plugins/woocommerce/includes/admin/settings/class-wc-settings-general.php#L282-L288
https://github.com/woocommerce/woocommerce/blob/5a787b309bcc16be3fc6a546f4e4dead1fcd13ad/plugins/woocommerce/includes/admin/settings/class-wc-settings-products.php#L250-L259
https://github.com/woocommerce/woocommerce/blob/5a787b309bcc16be3fc6a546f4e4dead1fcd13ad/plugins/woocommerce/includes/admin/settings/class-wc-settings-products.php#L298-L307

So this PR makes it more consistent with the rest of the Core settings. It goes against the expected behaviour from the issue, but I don't think that should necessarily be a driving factor. Does this make it clearer?

**Review by websupporter — APPROVED** [review]
lgtm. thank you @NeosinneR
