### PR TITLE
Fix selection of term after clicking the value name

### LINKED ISSUE #39456: [GlobalStep] Unable to select attribute values after clicking value name on "Products > Add new" page.
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Unable to select attribute values after clicking value name on "Products > Add new" page.

### Expected behavior

Clicking value name should select attribute value on "Products > Add new" page.

### Actual behavior

Unable to select attribute values after clicking value name on "Products > Add new" page.

### Steps to reproduce

1. Create any test site.
2. Install and activate all required plugins.
3. Using the Woocommerce beta tester plugin switch the version to 8.0.0-beta.2.
4. Add sample product csv file
5. Go to Woocommerce > Setting > Advance page.
6. Enable the "New product editor" option.
7. Go to the Products > Add new" page. 
8. Click on the "Add  Attribute" button.
9. Select an Attribute, then click on the dropdown option for value.
10. Try clicking on text of any attribute value.
11. Observe that, you are unable to select attribute values after clicking value name.

### Note:
For Firefox browser, Double clicking the value name selects the attribute value.

### Video:

https://github.com/woocommerce/woocommerce/assets/41110392/a8865e5e-49d2-4ae6-8f92-b142de71fd49

### WordPress Environment

Woocommerce Version: 8.0.0-beta.2
WordPress version: 6.3-RC2, 6.2.2
PHP version: 8.0.29

PC:
Windows 10
Chrome(Version 115.0.5790.110)
Firefox (Version 115.0.2)

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

<details>

`
### WordPress Environment ###

WC Version: 8.0.0
REST API Version: ✔ 8.0.0
WC Blocks Version: ✔ 10.6.1
Action Scheduler Version: ✔ 3.6.1
Log Directory Writable: ✔
WP Version: 6.3-RC2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.57 (Unix) OpenSSL/1.0.2g
PHP Version: 8.0.29
PHP Post Max Size: 1 GB
PHP Time Limit: 30
PHP Max Input Vars: 5000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.7.33-0ubuntu0.16.04.1-log
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.0.0
WC Database Prefix: wp_
Total Database Size: 7.17MB
Database Data Size: 5.36MB
Database Index Size: 1.81MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.06MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 4.03MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.14MB + Index: 0.11MB + Engine InnoDB
wp_posts: Data: 0.09MB + Index: 0.06MB + Engine InnoDB
wp_snippets: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 31
page: 8
post: 2
product: 29
product_variation: 16
shop_order: 1
wp_global_styles: 1
wp_navigation: 1
wp_template: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (6) ###

Query Monitor: by John Blackbourn – 3.13.1
Code Snippets: by Code Snippets Pro – 3.4.2
Companion Plugin: by Osk – 1.29
WooCommerce Payments: by Automattic – 6.2.0
WooCommerce: by Automattic – 8.0.0-beta.2
WordPress Beta Tester: by WordPress Upgrade/Install Team – 3.5.2

### Inactive Plugins (5) ###

Akismet Anti-Spam: Spam Protection: by Automattic - Anti Spam Team – 5.2
Hello Dolly: by Matt Mullenweg – 1.7.2
Jetpack: by Automattic – 12.3
WooCommerce Beta Tester: by WooCommerce – 2.1.0
WooCommerce Subscriptions: by WooCommerce – 5.3.0

### Dropin Plugins (1) ###

db.php: Query Monitor Database Class (Drop-in)

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### WC Pages ###

Shop base: #6 - /shop/
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty-Three
Version: 1.1
Author URL: https://wordpress.org
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
product-variation-management
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2023-07-28 08:48:51 +00:00
Options: ✔
Notes: 76
Onboarding: skipped

### WooCommerce Payments ###

Version: 6.2.0
Connected to WPCOM: Yes
Blog ID: 221673843
Account ID: acct_1NY4iZCT9W7qPnsb

### Action Scheduler ###

Complete: 85
Oldest: 2023-07-26 08:48:54 +0000
Newest: 2023-07-27 14:14:39 +0000

Failed: 1
Oldest: 2023-07-26 08:54:08 +0000
Newest: 2023-07-26 08:54:08 +0000

Pending: 1
Oldest: 2023-07-28 14:12:06 +0000
Newest: 2023-07-28 14:12:06 +0000

### Status report information ###

Generated at: 2023-07-27 14:14:52 +00:00
`

</details>

### PR DESCRIPTION
**Pull request by octaedro**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

This PR addresses an issue with selecting term attributes. Previously, when clicking a term name, it would not be selected as expected.
The proposed changes fix this behavior. The method [isEventOutside](https://github.com/woocommerce/woocommerce/blob/trunk/packages/js/components/src/experimental-select-control/select-control.tsx#L243) was erroneously returning true, while the event was actually inside the component.

Closes #39456.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Checkout this branch.
2. Install and activate all the required plugins.
3. Add a sample product CSV file or create a couple of global attributes with terms (under Product > Attributes).
4. Go to Woocommerce > Setting > Advanced page.
5. Enable the "New product editor" option.
6. Go to the Products > Add new" page. 
7. Click on the "Add  Attribute" button.
8. Select an Attribute, then click on the dropdown option for value.
9. Try clicking on the text of any attribute value. The term should now be selected as expected.

Screen Capture on 2023-08-03 at 18-56-39

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Comment 

</details>

### CODE REVIEW

File: packages/js/components/src/experimental-select-control/select-control.tsx [hunk 1]
```diff
@@ -297,7 +303,10 @@ function SelectControl< ItemType = DefaultItemType >( {
 					...getDropdownProps( {
 						preventKeyAction: isOpen,
 					} ),
-					className: 'woocommerce-experimental-select-control__input',
+					className: classnames(
+						'woocommerce-experimental-select-control__input',
+						listItemClassName
```
Comment (joshuatf) [inline packages/js/components/src/experimental-select-control/select-control.tsx]: This will add `woocommerce-experimental-select-control__list-item` to the input which seems semantically incorrect and could lead to styling errors.

File: packages/js/components/src/experimental-select-control/select-control.tsx [hunk 2]
```diff
@@ -241,9 +243,13 @@ function SelectControl< ItemType = DefaultItemType >( {
...
 	const isEventOutside = ( event: React.FocusEvent ) => {
-		return ! document
-			.querySelector( '.' + instanceId )
-			?.contains( event.relatedTarget );
+		const inputClasses = event?.target?.className;
+		return (
+			! document
+				.querySelector( '.' + instanceId )
+				?.contains( event.relatedTarget ) &&
+			! inputClasses.includes( listItemClassName )
```
Comment (joshuatf) [inline packages/js/components/src/experimental-select-control/select-control.tsx]: Does the original issue occur because of focusing the input?  I'm curious why this isn't under the instance.

Or is the issue that the popover list items are slotfilled into a div outside of the instance?  If that's the case, we probalby don't need to add `woocommerce-experimental-select-control__list-item` to the input below, right?

**Review by joshuatf — COMMENTED** [review]
I wasn't able to reproduce the original issue unfortunately.  Is there anything special I need to do to hit this bug?

I left a comment and question about why this is happening though with some thoughts depending on why it's occurring.

File: packages/js/components/src/experimental-select-control/select-control.tsx (hunk 2 above)
Comment (octaedro) [reply packages/js/components/src/experimental-select-control/select-control.tsx]: I believe the problem originates from the element's `onBlur` method. After clicking an item's name, the `onBlur` method is triggered. This method calls ([isEventOutside](https://github.com/woocommerce/woocommerce/blob/trunk/packages/js/components/src/experimental-select-control/select-control.tsx#L243)) and it returns `true`, even though the click was actually made inside. This is why I added the class to have a more specific check.
An alternative approach could be to only use the class `woocommerce-experimental-select-control__input`, which is already in [use there](https://github.com/woocommerce/woocommerce/blob/trunk/packages/js/components/src/experimental-select-control/select-control.tsx#L300).
Does that sound good to you?

File: packages/js/components/src/experimental-select-control/select-control.tsx (hunk 1 above)
Comment (octaedro) [reply packages/js/components/src/experimental-select-control/select-control.tsx]: Yeah, I used that name because at the end we see a list of inputs. But I'm totally ok removing that class. I did that in commit [57f2879](https://github.com/woocommerce/woocommerce/pull/39574/commits/57f2879ccc1ee05165f56e775a8c6ca0fce5b911)

File: packages/js/components/src/experimental-select-control/select-control.tsx (hunk 2 above)
Comment (octaedro) [reply packages/js/components/src/experimental-select-control/select-control.tsx]: I created [this commit](https://github.com/woocommerce/woocommerce/pull/39574/commits/57f2879ccc1ee05165f56e775a8c6ca0fce5b911) that removes the other class name and uses `woocommerce-experimental-select-control__input` to verify that the click has been done on the input in the list.

**Review by joshuatf — COMMENTED** [review]
Code looks good to me!  I'm still struggling to reproduce the issue.

If someone else on @woocommerce/mothra can reproduce the original issue and confirm this is fixed, this is good to go IMO 👍

**Review by joshuatf — APPROVED** [review]
The error magically started occurring for me after switching to 8.0 RC1 and back to `trunk` 🎉 

Just noting that the real issue here is that `Popover` (the `Menu`) gets appended to the body of the page which is outside the select control instance.

The check that occurs to see if a click is outside usually does not cause any issue [since actions are prevented] but(https://github.com/woocommerce/woocommerce/blob/ac9ec7d2a4311d6bebcf30066d25ad4546da1f2f/packages/js/components/src/experimental-select-control/selected-items.tsx#L68), but I'm guessing that clicking on the label is bypassing that and causing an event to occur.

Approving as I think the fix here works because the next focused item is the input which is being checked in this PR, but noting that if we run into this issue again, we probably want to add an instance ID to the popover and check if the related target was inside the popover.
