### PR TITLE
Modify wc_get_low_stock_amount function to always return a number

### LINKED ISSUE #29525: wc_get_low_stock_amount() returns a string if not set at product level
**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
When the low stock amount is pulled from the global settings via `$low_stock_amount = get_option( 'woocommerce_notify_low_stock_amount', 2 );` 

the value returned is a string and not an integer like the doc-block suggests.

**Expected behavior**
Always return an integer.

**Actual behavior**
A clear and concise description of what actually happens. Please be as descriptive as possible; 

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Go to product data metabox
2. select "manage stock" checkbox
3. leave "low stock" threshold empty/null
image

4. Add snippet:
```
function kia_test_low_stock_amount() {
	global $product;
	var_dump( wc_get_low_stock_amount( $product ) );
}
add_action( 'woocommerce_before_add_to_cart', 'kia_test_low_stock_amount' );
```
5. Visit product page.
6. See the threshold is a string
image

7. Optionally, you can edit the product's low-stock threshold, save, and refresh the page to confirm it's an integer when set at the product-level.

### PR DESCRIPTION
**Pull request by Konamiman**
### All Submissions:

* [ ] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
* [ ] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

The `wc_get_low_stock_amount` function is documented as returning an `int`, but when a product didn't have an explicit low stock amount configured the default value from the `woocommerce_notify_low_stock_amount` was returned verbatim, and that value is stored as a string. This pull request makes sure that the function always returns a number.

Also the related unit tests are updated so that they set the value of the `woocommerce_notify_low_stock_amount` option as a string, which is what actually happens in WooCommerce; and now they also verify that the function returns a number.

Closes #29525.

### How to test the changes in this Pull Request:

The easiest way to test this is by using the wp cli tool.

1. Create/edit a product so that it has "Enable stock management at product level" set and "Low stock threshold" unset:

image

2. Take note of the product id, it's in the product edit page url (`?post=...`) or in the products list (`ID: ...` when you hover the product row).

3. Run this in a console: 

```php
wp eval 'echo gettype(wc_get_low_stock_amount(wc_get_product(<product id>)));'
```

Without the fix you'll get `string`, with the fix you'll get `integer`.

### Other information:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully run tests with your changes locally?

### Changelog entry

> Fix - wc_get_low_stock_amount was returning a string, not an integer, for products not having an explicit low stock value set.

### CODE REVIEW

File: includes/wc-stock-functions.php [hunk 1]
```diff
@@ -403,13 +403,13 @@ function wc_get_low_stock_amount( WC_Product $product ) {
...
+		$product          = wc_get_product( $product->get_parent_id() );
 		$low_stock_amount = $product->get_low_stock_amount();
 	}
 
 	if ( '' === $low_stock_amount ) {
 		$low_stock_amount = get_option( 'woocommerce_notify_low_stock_amount', 2 );
 	}
 
-	return $low_stock_amount;
+	return intval( $low_stock_amount );
```
Comment (roykho) [inline includes/wc-stock-functions.php:414]: Unless we're using the second argument to change the `base`, it is preferred to use `(int)` instead as it is faster than calling a type casting function.

**Review by roykho — CHANGES_REQUESTED** [review]
Left a comment and also the unit test is failing.

**Review by roykho — APPROVED** [review]
LGTM! e2e tests are failing but upon looking at it, it doesn't seem like it is caused by this PR.
