### PR TITLE
Hide backorder meta on completed orders

### LINKED ISSUE #28195: Product Variation - Backordered Product bought, still shows as on backorder in order completed email
**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
Situation: A product has been bought which was currently available on backorder.
The Information that the product is on backorder gets shown correctly in cart and also in the order confirmation email.

If a order gets completed however this information gets still sent out to the client. This shouldnt happen as the product is not anymore on backorder - its packaged and sent out to the client.

**Expected behavior**
On the order completed email there is no additional information about a product that was previously on backorder. 

**Actual behavior**
Product still is listed in the order completed email as backordered

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Go to a product with variations on the frontend
2. Order although it shows the product variation is on backorder
3. check the cart and the order confirmation if it shows that the product variation is on backorder. if yes finally order it
4. Mark the order as completed. check if the email still shows that the product is on backorder.

**Screenshots**
WooCommerce Settings
woo-settings

Product Inventory
product-variation-inventory

Product Variation - Inventory
product-variation-inventory-variations

Order Completed - Backordered Information
order-completed-backordered

Order Completed - Backordered Information (E-Mail)
order-completed-backordered-email

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by pavel-mailpoet**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Products previously on backorder continued showing the backorder status in emails after the order was fulfilled.

Closes #28195 WOOPLUG-266 (note: the issue describes the issue for variable products, but it the problem is in all types of products)

### Screenshots or screen recordings:

| Before | After |
| ------ | ----- |
| Screenshot 2025-04-22 at 9 17 56  |  Screenshot 2025-04-22 at 9 19 06   |

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Create or update any product 
2. Go to Inventory and set "Allow backorders?" to "Allow, but notify customer"
3. Also, in the Inventory, set Quantity to 0
4. Use another browser and, as a customer, go to the product frontend
5. Order the product, although it shows the product variation is on backorder
6. As a customer, see that you received an email with the new order, and the product is correctly marked as "Backordered"
7. As the merchant, open the order and mark it as completed
8. As a customer, see that you received an email saying that the order is on its way. The product should not be marked as "Backordered" in this email. 

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce/includes/class-wc-order-item-product.php [hunk 1]
```diff
@@ -435,6 +435,43 @@ public function get_tax_status() {
...
+	 * @param string $hideprefix  Meta data prefix, (default: _).
+	 * @param bool   $include_all Include all meta data, this stop skip items with values already in the product name.
+	 * @return array
+	 */
+	public function get_formatted_meta_data( $hideprefix = '_', $include_all = false ) {
+		$formatted_meta = parent::get_formatted_meta_data( $hideprefix, $include_all );
+
+		$order = $this->get_order();
+
+		if ( $order && $order->has_status( 'completed' ) ) {
```
Comment (kalessil) [inline plugins/woocommerce/includes/class-wc-order-item-product.php]: HInt: we have `\Automattic\WooCommerce\Enums\OrderStatus` enum class.

Comment (pavel-mailpoet) [reply plugins/woocommerce/includes/class-wc-order-item-product.php]: Fixed, thank you.

File: plugins/woocommerce/tests/php/includes/class-wc-order-item-product-test.php [hunk 2]
```diff
@@ -0,0 +1,79 @@
...
+		foreach ( $formatted_meta_before as $meta ) {
+			if ( $meta->key === $backorder_meta_key ) {
+				$found_backorder_before = true;
+				break;
+			}
+		}
+		$this->assertTrue( $found_backorder_before, 'Backorder meta should exist before order completion.' );
+
+		// 5. Complete the order.
+		$order->update_status( 'completed' );
```
Comment (lysyjan) [inline plugins/woocommerce/tests/php/includes/class-wc-order-item-product-test.php]: We can also use here the enum class `\Automattic\WooCommerce\Enums\OrderStatus`. What do you think?

File: plugins/woocommerce/tests/php/includes/class-wc-order-item-product-test.php [hunk 3]
```diff
@@ -0,0 +1,79 @@
...
+ *
+ * @package WooCommerce\Tests
+ */
+
+declare( strict_types=1 );
+
+use WC_Helper_Product;
+use WC_Helper_Order;
+use WC_Order_Item_Product;
+use WC_Unit_Test_Case;
```
Comment (lysyjan) [inline plugins/woocommerce/tests/php/includes/class-wc-order-item-product-test.php]: Those use statements are redundant and cause warnings in the test output:
Screenshot 2025-04-23 at 21 21 49

**Review by lysyjan — COMMENTED** [review]
@pavel-mailpoet Good job 👍 It works as expected. I also tested it for another language, but I found some warnings when I executed your new test locally.

File: plugins/woocommerce/tests/php/includes/class-wc-order-item-product-test.php (hunk 3 above)
Comment (pavel-mailpoet) [reply plugins/woocommerce/tests/php/includes/class-wc-order-item-product-test.php]: Thank you, removed them

**Review by lysyjan — APPROVED** [review]
It works as expected. I tested this PR on my local with two different languages.

I used WP 6.8 and the theme Twenty Twenty-Five.

Here are email screenshots received in Mailpit:
Screenshot 2025-04-25 at 15 08 47

Screenshot 2025-04-25 at 15 08 34
