### PR TITLE
Fix removal of express payment method from state

### LINKED ISSUE #44694: REMOVE_AVAILABLE_EXPRESS_PAYMENT_METHOD reducer not working correctly
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

The [REMOVE_AVAILABLE_EXPRESS_PAYMENT_METHOD reducer](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce-blocks/assets/js/data/payment/reducers.ts#L90) is not working as expected. It removes all the express payment method present at the Checkout block.  

https://github.com/woocommerce/woocommerce/assets/11503784/410c3773-e99b-45c2-86ab-0ce8799fb5e5

### Expected behavior

The [REMOVE_AVAILABLE_EXPRESS_PAYMENT_METHOD reducer] should remove the provided express payment method. 

### Actual behavior

The [REMOVE_AVAILABLE_EXPRESS_PAYMENT_METHOD reducer] removes all express payment method. 

### Steps to reproduce

1. Enable Stripe and Paypal express payment methods. 
2. Add a product to the Cart and visit the Checkout block page.
3. Notice there are 3 express checkout buttons.
4. Open console log and run `wp.data.dispatch( 'wc/store/payment' ).__internalRemoveAvailableExpressPaymentMethod('payment_request')` code to remove stripe's express payment method.
5. Notice there are no express payment methods available now.

### WordPress Environment

n/a

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by tarunvijwani**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

With this PR, we are fixing the behavior of the REMOVE_AVAILABLE_EXPRESS_PAYMENT_METHOD reducer to correctly remove the specified express payment method.

Closes #44694.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Enable Stripe and Paypal express payment methods. 
2. Add a product to the Cart and visit the Checkout block page.
3. Notice there are 3 express checkout buttons.
4. Open console log and run `wp.data.dispatch( 'wc/store/payment').__internalRemoveAvailableExpressPaymentMethod('payment_request')` code to remove stripe's express payment method.
5. Confirm stripe express payment method is removed correctly.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [x] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 
Fixed a bug where express payment methods could not be removed from the wc/store/payment data store. 

#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce-blocks/assets/js/data/payment/test/reducers.js [hunk 1]
```diff
@@ -151,7 +151,12 @@ describe( 'paymentMethodDataReducer', () => {
 				isSuccessful: false,
 			},
 			availablePaymentMethods: {},
-			availableExpressPaymentMethods: [ 'my-new-method' ],
+			availableExpressPaymentMethods: {
+				'my-new-method': {
+					name: 'My New Method',
+					description: 'A new way to pay quickly.',
```
Comment (opr) [inline plugins/woocommerce-blocks/assets/js/data/payment/test/reducers.js]: Nice catch, but looking at the type def I don't think the data store supports `description` 

```ts
/**
 * Used to represent payment methods in a context where storing objects is not allowed, i.e. in data stores.
 */
export type PlainPaymentMethods = Record< string, { name: string } >;

/**
 * Used to represent payment methods in a context where storing objects is not allowed, i.e. in data stores.
 */
export type PlainExpressPaymentMethods = PlainPaymentMethods;
```

File: plugins/woocommerce/changelog/44633-fix-available-express-payment-method-removal [hunk 2]
```diff
@@ -0,0 +1,4 @@
+Significance: minor
+Type: fix
+
+Fix the removal of the express payment method from the state.
```
Comment (opr) [inline plugins/woocommerce/changelog/44633-fix-available-express-payment-method-removal]: This could be improved, it doesn't really describe the fix very well.

Perhaps: "Fixed a bug where express payment methods could not be removed from the `wc/store/payment` data store"

**Review by opr — CHANGES_REQUESTED** [review]
Thanks @tarunvijwani this is testing OK for me, the code changes look 99% good too, just a couple of changes needed (I don't think the reducer test is a huge deal, but it would be nice to make sure we're being consistent with the test data vs. real life data)

File: plugins/woocommerce-blocks/assets/js/data/payment/test/reducers.js (hunk 1 above)
Comment (tarunvijwani) [reply plugins/woocommerce-blocks/assets/js/data/payment/test/reducers.js]: Thank you for sharing the datatype. I have removed the description field now. 🙂

**Comment by tarunvijwani** [comment]
> Thanks @tarunvijwani this is testing OK for me, the code changes look 99% good too, just a couple of changes needed (I don't think the reducer test is a huge deal, but it would be nice to make sure we're being consistent with the test data vs. real life data)

Thank you so much for the suggestion. I have updated the tests and changelog. 👍

**Review by opr — APPROVED** [review]
Thanks Tarun, looks good now! 👏🏼

**Comment by tarunvijwani** [comment]
Thank you for reviewing the PR, @opr! 🎉
