### PR TITLE
[Accessibility] Convert the remove item link into a button on cart and mini-cart

### LINKED ISSUE #56606: Accessibility: Mini cart remove button should be a button not a link
In block-based themes, the remove button is a button. This is a good example:

Image

## Problem
In themes like Astra that call WC_Widget_Cart, the remove product button is incorrectly coded as a link.

https://github.com/woocommerce/woocommerce/blob/d1e8f3832d2a12141ac0b1f1667460ded8905f0a/plugins/woocommerce/templates/cart/mini-cart.php#L50

### PR DESCRIPTION
**Pull request by Manussakis**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes #56606 .

The "Remove from cart" button on the legacy Minicart is not actually a button, but a link. It uses the `<a>` HTML tag.
This is a semantics issue because a link should be used to link to another page or a page section. For the action it does, the `<button>` is the appropriate HTML tag.
However, changing the HTML is problematic because it's prone to regression, so the `role="button"` attribute was added to the `<a>` tag.
Once the link has a button role, it also needs to act as a button. Which means that it should be possible to click on it using the keyboard Space key. However, it's very unlikely that users click on it using the Space key since the legacy minicart can only be opened once the user hovers over the cart icon with the mouse. But we wanted to cover all cases and implemented the feature anyway.

(For Bug Fixes) Bug introduced in PR # .

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

This PR should also be tested with Storefront theme, but I will detail the steps to QA using the Astra theme as it was flagged on the issue.

Here's how to insert the WooCommerce Cart in the header in Astra.

1. Install the Astra theme.
1. Go to Appearance > Customize.
2. Click Header Builder.
3. In the header builder section that opens at the bottom of the main content in the Customizer, hover over a column to 4. see a + icon appear.
5. Click on the column and an "Insert Elements" modal appears.
6. In the insert elements modal, click on the cart. This will insert the cart in the header.
7. Publish changes.
image

The steps below should be done with the WooCommerce -> Settings -> Products -> Add to cart behaviour -> "Enable AJAX add to cart buttons on archives" option both disabled and enabled.

8. Go to the shop page on the frontend.
9. Add a product to the cart.
10. Hover over the Mini-cart on the header.
11. Verify the remove item link has the `role="button"` attribute. 💡**Tip**: The Mini-cart content only appears while the mouse is over it, so you may need to open the Dev tools with the shorthand command. (Command + Shif + c, on Mac).
Screenshot 2025-03-31 at 16 43 03

12. Verify the remove item link can be clicked by pressing the Space key on the keyboard. Once the Mini-cart appears, click on the subtotal text and press Shift + Tab until you get to the remove item link. Then, press the Space key on the keyboard.
13. Go to the Cart page.
14. Verify the remove item link has the `role="button"` attribute.
image

15. Turn on the screen reader.
16. Focus on the remove item link.
17. Verify it's announced as a button.
18. Verify the link can be clicked by pressing the Space key on the keyboard.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

## Summary by CodeRabbit

- **New Features**
	- Improved keyboard accessibility for removing items from the cart and mini-cart, allowing users to use the Space key to activate the remove action.
- **Style**
	- Updated remove item links in the cart and mini-cart to use button semantics for better accessibility.
- **Tests**
	- Added end-to-end tests to verify keyboard accessibility for removing items from the mini-cart.

### CODE REVIEW

**Comment by Manussakis** [comment]
@dkotter This PR is ready for code review.
You will notice that some tests are failing, but I couldn't associate them with the changes made. I also noticed that the same tests are failing on another PR I am working on (https://github.com/woocommerce/woocommerce/pull/56875), so I assume that this is on trunk.

**Review by dkotter — DISMISSED** [review]
@ankitguptaindia @qasumitbagthariya This is ready for QA

**Comment by ankitguptaindia** [comment]
@Manussakis Thanks for the fixes. 

 - ⚠️  - I can see the "role="button" attribute on the mini cart when it is open in hover, but it doesn't click/remove when I press the space bar but it scrolls the page instead.
- ✅ - Changes on the Cart page work as expected. 


Screenshot 2025-04-01 at 11 21 46 AM



**Please have a look in below screencast for my steps:**

https://github.com/user-attachments/assets/9ad2438b-6474-4714-ab6a-39cc01397dc5

**Comment by Manussakis** [comment]
Thanks, @ankitguptaindia for testing this PR 🙂

I was not able to reproduce the issue you flagged, please watch the video below.
Could you please tell me more about your testing environment?
Thanks!

https://github.com/user-attachments/assets/6f5a4bdc-da2d-4990-9f3f-762dec75d44f

**Comment by ankitguptaindia** [comment]
Hey @Manussakis Thanks for looking into it.

Regarding your query:
>Could you please tell me more about your testing environment? 

To ensure the issue is not environment-specific, I tested it on different setups and devices, and I experienced the same issue as in my usual testing environment.

I debugged this in detail and observed that the issue occurs when the store has the "Enable AJAX add to cart buttons on archives" setting disabled on the Product Settings page.

When this setting is enabled, the product removal icon works as described in the PR.

image

**Please have a look in this video for more details:** 

https://github.com/user-attachments/assets/8e50b086-3b55-444e-a0ca-3a63c2ab48b9




----


**Next Step-** Moving back for remediation.

**Comment by Manussakis** [comment]
Thanks, @ankitguptaindia for debugging it!

@dkotter Please review this code update:
[Trigger remove item click when the Space key is pressed with AJAX dis…](https://github.com/woocommerce/woocommerce/pull/56869/commits/e63a7db92d77d072a090420f261b675bec6fdc27)

Thanks!

File: plugins/woocommerce/client/legacy/js/frontend/woocommerce.js [hunk 1]
```diff
@@ -182,9 +182,27 @@ jQuery( function ( $ ) {
 		} );
 	} );
 
+	// If the the "Enable AJAX add to cart buttons on archives" setting is disabled
```
Comment (dkotter) [inline plugins/woocommerce/client/legacy/js/frontend/woocommerce.js]:
```suggestion
	// If the "Enable AJAX add to cart buttons on archives" setting is disabled
```

File: plugins/woocommerce/client/legacy/js/frontend/woocommerce.js [hunk 2]
```diff
@@ -182,9 +182,27 @@ jQuery( function ( $ ) {
...
+	// the add-to-cart.js file won't be loaded, so we need to add the event listener here.
+	if( typeof wc_add_to_cart_params === 'undefined') {
```
Comment (dkotter) [inline plugins/woocommerce/client/legacy/js/frontend/woocommerce.js]:
```suggestion
	if ( typeof wc_add_to_cart_params === 'undefined') {
```

File: plugins/woocommerce/client/legacy/js/frontend/woocommerce.js [hunk 3]
```diff
@@ -182,9 +182,27 @@ jQuery( function ( $ ) {
...
+		$( document.body ).on( 'keydown', '.remove_from_cart_button', on_keydown_remove_from_cart );
+	}
+
 	$( document.body ).on( 'item_removed_from_classic_cart', focus_populate_live_region );
 } );
 
+/**
+ * Handle when pressing the Space key on the remove item link.
+ * This is necessary because the link got the role="button" attribute
```
Comment (dkotter) [inline plugins/woocommerce/client/legacy/js/frontend/woocommerce.js]:
```suggestion
 * This is necessary because the link has the role="button" attribute
```

**Review by dkotter — DISMISSED** [review]

**Comment by ankitguptaindia** [comment]
**QA/Test Report-** ✅ 
------------

**Testing Environment -** 

<Details>

* WordPress: 6.7.2
* Theme:  
 - Astra
* WooCommerce - Development version with this fix-specific branch.  
* PHP: 8.3
* Web Server: Nginx
* Browser: Chrome - Version 134
* OS: macOS Sonoma 14.6.1 


</Details>


**Test Results -** 

The changes work as intended and have been tested across Safari, Firefox, and Chrome. 

**Functional Demo /  Screencast -**


https://github.com/user-attachments/assets/b3a028d4-a5fc-4768-bd94-3a1a91cfa0d1

**Comment by ankitguptaindia** [comment]
@Manussakis Could you please open this PR.

File: plugins/woocommerce/client/legacy/js/frontend/add-to-cart.js [hunk 4]
```diff
@@ -169,6 +170,18 @@ jQuery( function( $ ) {
...
+	 * Handle when pressing the Space key on the remove item link.
+	 * This is necessary because the link got the role="button" attribute
+	 * and needs to act like a button.
+	 */
+	AddToCartHandler.prototype.onKeydownRemoveFromCart = function( e ) {
+		if ( e.key === ' ' ) {
+			e.preventDefault();
+			$( this ).trigger( 'click' );
+		}
+	};
```
Comment (nielslange) [inline plugins/woocommerce/client/legacy/js/frontend/add-to-cart.js]: For increased readability, I suggest using `event` instead of `e`. It's something we also do in other functions.

```suggestion
	AddToCartHandler.prototype.onKeydownRemoveFromCart = function( event ) {
		if ( event.key === ' ' ) {
			event.preventDefault();
			$( this ).trigger( 'click' );
		}
	};
```

File: plugins/woocommerce/client/legacy/js/frontend/cart.js [hunk 5]
```diff
@@ -761,6 +766,20 @@ jQuery( function ( $ ) {
...
+		 * and needs to act like a button.
+		 *
+		 * @param {Object} evt The JQuery event
+		 */
+		on_keydown_remove_item: function ( evt ) {
+			if( evt.key === ' ' ) {
+				evt.preventDefault();
+				$( evt.currentTarget ).trigger( 'click' );
+			}
+		},
```
Comment (nielslange) [inline plugins/woocommerce/client/legacy/js/frontend/cart.js]: Similar as before, changing `evt` to `event` would increase the readability here:

```suggestion
		on_keydown_remove_item: function ( event ) {
			if ( event.key === ' ' ) {
				event.preventDefault();
				$( event.currentTarget ).trigger( 'click' );
			}
		},
```

File: plugins/woocommerce/client/legacy/js/frontend/woocommerce.js [hunk 6]
```diff
@@ -182,9 +182,27 @@ jQuery( function ( $ ) {
...
+ * Handle when pressing the Space key on the remove item link.
+ * This is necessary because the link has the role="button" attribute
+ * and needs to act like a button.
+ */
+function on_keydown_remove_from_cart( e ) {
+	if ( e.key === ' ' ) {
+		e.preventDefault();
+		e.currentTarget.click();
+	}
+}
```
Comment (nielslange) [inline plugins/woocommerce/client/legacy/js/frontend/woocommerce.js]: Finally, in this case, we could also use `event` over `e`:

```suggestion
function on_keydown_remove_from_cart( event ) {
	if ( event.key === ' ' ) {
		event.preventDefault();
		event.currentTarget.click();
	}
}
```

**Review by nielslange — COMMENTED** [review]
Thanks for working on this, @Manussakis. I left a few suggestions to improve readability.

Quick question on step 12 of the testing instructions:

> _Verify the remove item link can be clicked by pressing the Space key on the keyboard. Once the Mini-cart appears, click on the subtotal text and press Shift + Tab until you get to the remove item link. Then, press the Space key on the keyboard._

I’m unable to open the Mini Cart using just the keyboard. Is this working for you?

**Comment by Manussakis** [comment]
@nielslange 

> I’m unable to open the Mini Cart using just the keyboard. Is this working for you?

If you are testing using Storefront or Astra themes, this is not possible, it only appears when hovering over it since clicking on it leads to the Cart page. That's why I left this tip:

> Once the Mini-cart appears, click on the subtotal text and press Shift + Tab until you get to the remove item link. Then, press the Space key on the keyboard.

Please let me know if that helps 🙂

**Comment by nielslange** [comment]
> @nielslange
> 
> > I’m unable to open the Mini Cart using just the keyboard. Is this working for you?
> 
> If you are testing using Storefront or Astra themes, this is not possible, it only appears when hovering over it since clicking on it leads to the Cart page. That's why I left this tip:
> 
> > Once the Mini-cart appears, click on the subtotal text and press Shift + Tab until you get to the remove item link. Then, press the Space key on the keyboard.
> 
> Please let me know if that helps 🙂

My question was a bit more general, @Manussakis. I’m wondering why we highlight the Space key interaction in the testing steps. Since the Mini Cart isn’t easily accessible via keyboard in most themes, it’s unlikely that users would interact with it this way, making the scenario feel somewhat abstract.

I also noticed the addition of keyboard handling logic like `.on('keydown', '.remove_from_cart_button', this.onKeydownRemoveFromCart)`, but since this part of the UI is only accessible via mouse, the keyboard support doesn't feel particularly actionable in practice.

To ensure this change works as expected, and continues to do so, could you add an integration test for the changes?

**Comment by vikrampm1** [comment]
@nielslange just noting here that @Manussakis will be looking into this next week when he is back on the project.

**Comment by nielslange** [comment]
> @nielslange just noting here that @Manussakis will be looking into this next week when he is back on the project.

Thanks for letting me know, @vikrampm1. As tomorrow will be my last working day at Automattic, I've unassigned myself as a reviewer and requested a review from @woocommerce/rubik.

**Comment by Manussakis** [comment]
@woocommerce/rubik 

Replying to [this concern](https://github.com/woocommerce/woocommerce/pull/56869#issuecomment-2820597048) from @nielslange 

The "Remove from cart" button on the legacy Mini Cart is not actually a button, but a link. It uses the `<a>` HTML tag.
This is a semantics issue because a link should be used to link to another page or a page section. For the action it does, the `<button>` is the appropriate HTML tag.
However, changing the HTML is problematic because it's prone to regression, so the `role="button"` attribute was added to the `<a>` tag.
Once the link has a button role, it also needs to act as a button. Which means that it should be possible to click on it using the keyboard Space key. However, it's very unlikely that users click on it using the Space key since the legacy Mini Cart can only be opened once the user hovers over the cart icon with the mouse. But we wanted to cover all cases and implemented the feature anyway.

@nielslange suggested that an integration test should be done, but I didn't see any example of it for legacy templates like the Mini Cart. I only see tests for the Mini Cart block, which was not touched in this PR.

@woocommerce/rubik could you assess the PR and confirm an integration test is needed? If so, could you please provide me with any guidance on that?

Thanks!

@vikrampm1

**Comment by mikejolley** [comment]
@Manussakis I agree with change to role button.

Does the `<a role="button">` also need tabindex? And should it be space and enter keyboard events? We can use keycodes like in WP core https://github.com/WordPress/WordPress/blob/779dc9c93d18c19c41897d5b993c77eec6787edc/wp-admin/js/application-passwords.js#L153C2-L158C6

R/e tests. Legacy cart does not have an integration test. You could add something to the e2e tests here:
https://github.com/woocommerce/woocommerce/blob/trunk/packages/js/e2e-core-tests/src/specs/shopper/front-end-cart.test.js#L66

**Comment by Manussakis** [comment]
Hey @mikejolley 

> Does the `<a role="button">` also need tabindex? 

It doesn't. The goal is just to improve the semantics and not change the natural tab order when using the `Tab` key for navigation.

>  And should it be space and enter keyboard events?

Yes, it should, since this is the default behavior of buttons.

> R/e tests. Legacy cart does not have an integration test. You could add something to the e2e tests here:

Perfect, thanks!

cc: @vikrampm1 @faisal-alvi

**Comment by faisal-alvi** [comment]
@mikejolley I’ve added an e2e test to cover mini-cart product removal, including the Space key trigger. However, I couldn’t find the test running in the pipeline, just wanted to confirm if I missed anything.

File: plugins/woocommerce/templates/cart/cart.php [hunk 7]
```diff
@@ -12,7 +12,7 @@
  *
  * @see     https://woocommerce.com/document/template-structure/
  * @package WooCommerce\Templates
- * @version 7.9.0
+ * @version 9.9.0
```
Comment (mikejolley) [inline plugins/woocommerce/templates/cart/cart.php]: Needs bump to 10.0.0

File: plugins/woocommerce/templates/cart/mini-cart.php [hunk 8]
```diff
@@ -14,7 +14,7 @@
  *
  * @see     https://woocommerce.com/document/template-structure/
  * @package WooCommerce\Templates
- * @version 9.4.0
+ * @version 9.9.0
```
Comment (mikejolley) [inline plugins/woocommerce/templates/cart/mini-cart.php]: Needs bump to 10.0.0

**Review by mikejolley — DISMISSED** [review]
I've tested functionality—happy with this, it looks good to go. There are 2 changes needed before this can merge.

1. 2 template bumps need to increase to 10.0
2. @faisal-alvi The test added to `core-e2e-tests` won't run. That is apparently deprecated. Could you add the test under `tests/e2e-pw/tests/cart` instead? `e2e-pw` will run on the CI.

Thanks!

**Comment by mikejolley** [comment]
@opr please merge this when Im away when the tests are updated and passing.

**Comment by vikrampm1** [comment]
@opr just checking if this is good to merge or is there anything needed here?

**Comment by opr** [comment]
@vikrampm1 please see above, there are outstanding suggestions from Mike that need to be addressed before this can be merged.

https://github.com/woocommerce/woocommerce/pull/56869#pullrequestreview-2881591212

**Comment by vikrampm1** [comment]
@opr got it. We will address those asap and ping you back.

File: plugins/woocommerce/templates/cart/mini-cart.php (hunk 8 above)
Comment (amesplant) [reply plugins/woocommerce/templates/cart/mini-cart.php]: @mikejolley this is now bumped to 10.0.0

File: plugins/woocommerce/templates/cart/cart.php (hunk 7 above)
Comment (amesplant) [reply plugins/woocommerce/templates/cart/cart.php]: @mikejolley this is now bumped to 10.0.0

**Comment by amesplant** [comment]
@opr 
Both issues outlined in [#56869 (review)](https://github.com/woocommerce/woocommerce/pull/56869#pullrequestreview-2881591212) have been addressed.

File: plugins/woocommerce/tests/e2e-pw/tests/cart/add-to-cart.spec.js [hunk 9]
```diff
@@ -9,6 +9,8 @@ import { addAProductToCart } from '@woocommerce/e2e-utils-playwright';
 import { tags, test } from '../../fixtures/fixtures';
 import { WC_API_PATH } from '../../utils/api-client';
 import { checkCartContentInBlocksCart } from '../../utils/cart';
+import { it } from '@jest/globals';
```
Comment (opr) [inline plugins/woocommerce/tests/e2e-pw/tests/cart/add-to-cart.spec.js]: This is not used

File: plugins/woocommerce/tests/e2e-pw/tests/cart/add-to-cart.spec.js [hunk 10]
```diff
@@ -9,6 +9,8 @@ import { addAProductToCart } from '@woocommerce/e2e-utils-playwright';
...
+import { shopper, uiUnblocked } from '@woocommerce/e2e-utils';
```
Comment (opr) [inline plugins/woocommerce/tests/e2e-pw/tests/cart/add-to-cart.spec.js]: This needs to be moved to the

```
/**
 * External dependencies
 */
```

block

**Review by opr — CHANGES_REQUESTED** [review]
The E2E test added seems to be for a deprecated test setup we had and transferring it over directly like this doesn't seem to work. We should rewrite the test to work with the current system.

Some instructions to help get the e2e suite running locally:

- `pnpm --filter=@woocommerce/plugin-woocommerce env:start`
- `pnpm --filter=@woocommerce/plugin-woocommerce test:e2e --ui`

You won't see the `add-to-cart-spec` in the list because there's an error with the newly added test (`page` doesn't exist).

I bet if you give an agent the tests in `client/blocks/test/e2e` as context, it would be able to rewrite this one easily.

**Comment by opr** [comment]
@faisal-alvi I see you pushed changes, are there more to come? CI is still failing. The test should use updated e2e utils from `@woocommerce/e2e-utils-playwright`. An example of a test that adds an item to the cart is here https://github.com/woocommerce/woocommerce/blob/f2b16512c421c90131e1e0afac1f36bc6c455113/plugins/woocommerce/tests/e2e-pw/tests/coupons/cart-checkout-coupons.spec.js#L234

**Comment by faisal-alvi** [comment]
@opr Thanks for the help! I’ve implemented the suggestions and updated the E2E test - it’s now passing. However, another E2E test is failing: `tests/e2e/tests/checkout/checkout-block.shopper.block_theme.spec.ts:173:2`

This failure seems unrelated to the changes in this PR and I don’t see an option to re-run the tests in Github on my end to check if it’s a flaky one. Could you please re-run the tests or let me know if you have any suggestions?

**Comment by vikrampm1** [comment]
@opr just noting that this is awaiting your response/feedback.

**Comment by opr** [comment]
The tests are passing, the failure on the job is probably because this is on a fork. The check passes locally for me.

```
pnpm analyzer "03d7702625dcff5e35ed372bb787eba5fb532da0" $version --ba
 ✔  08:43:12 p.m. 
se "6dfd5f16aecbeee2fae0ec30e0c7ce7036cfeaac" --outputStyle "github" --exclude "plugins/woocommerce/tests"

> code-analyzer@1.0.0 analyzer /Users/thomas/code/tomato/app/public/wp-content/plugins/woocommerce-monorepo/tools/code-analyzer
> node -r ts-node/register ./src/commands/analyzer/index.ts "03d7702625dcff5e35ed372bb787eba5fb532da0" "3.7.1" "--base" "6dfd5f16aecbeee2fae0ec30e0c7ce7036cfeaac" "--outputStyle" "github" "--exclude" "plugins/woocommerce/tests"

✔ Making temporary clone of /Users/thomas/code/tomato/app/public/wp-content/plugins/woocommerce-monorepo/...... complete.
Temporary clone of /Users/thomas/code/tomato/app/public/wp-content/plugins/woocommerce-monorepo/ created at /var/folders/pn/bdk4xh7x4t9cf18mzm8d5r6c0000gn/T/code-analyzer-tmp/e62d055f-3acc-46c3-9a54-bb3a4209de35
✔ Detecting hook changes...... complete.
⠦ Detecting template changes......Unable to get PR number in /plugins/woocommerce/templates/cart/cart.php:15
⠸ Detecting template changes......Unable to get PR number in /plugins/woocommerce/templates/cart/cart.php:63
⠦ Detecting template changes......Unable to get PR number in /plugins/woocommerce/templates/cart/mini-cart.php:17
⠋ Detecting template changes......Unable to get PR number in /plugins/woocommerce/templates/cart/mini-cart.php:50
✔ Detecting template changes...... complete.
✔ Detecting DB changes...... complete.
::warning file=/plugins/woocommerce/templates/cart/cart.php,line=1,title=TEMPLATES::This template may require a version bump! Expected 3.7.1
::warning file=/plugins/woocommerce/templates/cart/mini-cart.php,line=1,title=TEMPLATES::This template may require a version bump! Expected 3.7.1

::set-output name=templates::\n\n### Template changes:\n* **File:** /plugins/woocommerce/templates/cart/cart.php\n  * WARNING: This template may require a version bump! Expected 3.7.1\n* **File:** /plugins/woocommerce/templates/cart/mini-cart.php\n  * WARNING: This template may require a version bump! Expected 3.7.1


## HOOK CHANGES
---------------------------------------------------
No hook changes found.
---------------------------------------------------


## DB CHANGES
---------------------------------------------------
No db changes found.
---------------------------------------------------
```

**Comment by vikrampm1** [comment]
@opr thanks. Is there anything needed here from our end or can you proceed and merge the PR?

**Comment by opr** [comment]
> @opr thanks. Is there anything needed here from our end or can you proceed and merge the PR?

The PR is currently set to draft. Please:
- rebase on trunk
- fix any merge conflicts
- open the PR (mark is as ready for review)
- Re-request a review from me

**Review by opr — APPROVED** [review]
Thanks, tests are passing, the failing CI check is because this is a fork. Approving! 👏🏼

**Comment by vikrampm1** [comment]
Thanks @opr please proceed and merge the PR if there are no concerns here. Hopefully this makes it to the 10.0 before the code freeze.
