### PR TITLE
Properly break from Note loop using break

### LINKED ISSUE #40455: WooSubscriptionNotes has incorrect usage of `continue`, it should use `break` instead.
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Reported in 7085329-zen.

In the following line https://github.com/woocommerce/woocommerce/blob/60c4807/plugins/woocommerce/src/Internal/Admin/Notes/WooSubscriptionsNotes.php#L296, we are using `continue` statement. However, just in the previous line, we have set the `$note` to false, so in cases where the count of `$bump_thresholds` is more than one, then in the second iteration of the loop, the line `$note->delete();` will result in an error, because it would have been set to false in the previous iteration of the loop.

Stack trace for the error:

```log
/var/www/redacted/www/wp-content/plugins/woocommerce/src/Internal/Admin/Notes/WooSubscriptionsNotes.php:321
Stack trace:
#0 /var/www/redacted/www/wp-content/plugins/woocommerce/src/Internal/Admin/Notes/WooSubscriptionsNotes.php(467): AutomatticWooCommerceInternalAdminNotesWooSubscriptionsNotes->add_or_update_subscription_expiring()
#1 /var/www/redacted/www/wp-content/plugins/woocommerce/src/Internal/Admin/Notes/WooSubscriptionsNotes.php(109): AutomatticWooCommerceInternalAdminNotesWooSubscriptionsNotes->refresh_subscription_notes()
#2 /var/www/redacted/www/wp-includes/class-wp-hook.php(310): AutomatticWooCommerceInternalAdminNotesWooSubscriptionsNotes->admin_head()
#3 /var/www/redacted/www/wp-includes/class-wp-hook.php(334): WP_Hook->apply_filters()
#4 /var/www/redacted/www/wp-includes/plugin.php(517): WP_Hook->do_action()
#5 /var/www/redacted/www/wp-admin/admin-header.php(163): do_action()
#6 /var/www/redacted/www/wp-admin/edit.php(407): require_once('/var/www/...')
#7 {main}
thrown i /var/www/redacted/www/wp-content/plugins/woocommerce/src/Internal/Admin/Notes/WooSubscriptionsNotes.php på linje 321
```

### Expected behavior

No errors.

### Actual behavior

There is an error with stack strace as described above in some cases.

### Steps to reproduce

Unfortunately we only have the stack trace, no reliable steps to reproduce.

### WordPress Environment

n/a

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by bor0**
Also perform some tiny refactoring.

### Changes proposed in this Pull Request:

Closes #40455.

Review this easier by [ignoring whitespace changes](https://github.com/woocommerce/woocommerce/pull/52671/files?diff=unified&w=1).

### Testing instructions

1. Make sure your store is connected to WCCOM, and that you have [active subscriptions](http://localhost:8080/wp-admin/admin.php?page=wc-admin&tab=my-subscriptions&path=%2Fextensions)
1. In wp-cli, run these commands:
```
> ( new Automattic\WooCommerce\Internal\Admin\Notes\WooSubscriptionsNotes() )->add_or_update_subscription_expiring( current( \WC_Helper::get_subscriptions() ) ); // to mimic an expiring subscription
> $array = get_transient( '_woocommerce_helper_subscriptions' );
> $array[ array_key_first( $array ) ][ 'expires'] = 1; // update subscription
> set_transient( '_woocommerce_helper_subscriptions', $array, 1 * HOUR_IN_SECONDS );
> $note = ( new Automattic\WooCommerce\Internal\Admin\Notes\WooSubscriptionsNotes() )->find_note_for_product_id( current( \WC_Helper::get_subscriptions() )['product_id'] );
> $note->set_content_data( (object) ( [ 'days_until_expiration' => 45 ] + (array) $note->get_content_data() ) );
> $note->save(); // update note to trigger code
> ( new Automattic\WooCommerce\Internal\Admin\Notes\WooSubscriptionsNotes() )->add_or_update_subscription_expiring( current( \WC_Helper::get_subscriptions() ) ); // trigger refresh code
```

In `trunk`, should get error `Uncaught Error: Call to a member function delete() on false`. On this branch, should get no error.

### CODE REVIEW

File: plugins/woocommerce/src/Internal/Admin/Notes/WooSubscriptionsNotes.php [hunk 1]
```diff
@@ -22,16 +22,7 @@ class WooSubscriptionsNotes {
 	const CONNECTION_NOTE_NAME    = 'wc-admin-wc-helper-connection'; // deprecated.
 	const SUBSCRIPTION_NOTE_NAME  = 'wc-admin-wc-helper-subscription';
 	const NOTIFY_WHEN_DAYS_LEFT   = 60;
-
-	/**
-	 * We want to bubble up expiration notices when they cross certain age
-	 * thresholds. PHP 5.2 doesn't support constant arrays, so we do this.
```
Comment (bor0) [inline plugins/woocommerce/src/Internal/Admin/Notes/WooSubscriptionsNotes.php:28]: This seems an old left-over; we already use const arrays in the codebase.

Comment (andfinally) [reply plugins/woocommerce/src/Internal/Admin/Notes/WooSubscriptionsNotes.php:28]: Can confirm – I found at least one in WC Helper. Also, WooCommerce has required min PHP 7.0 since version 4.0.

File: plugins/woocommerce/src/Internal/Admin/Notes/WooSubscriptionsNotes.php [hunk 2]
```diff
@@ -274,27 +265,21 @@ public function add_or_update_subscription_expiring( $subscription ) {
...
-						$note = false;
-						continue;
-					}
+			// If we have a note and we are at or have crossed a threshold, we should delete
+			// the old note and create a new one, thereby "bumping" the note to the top of the inbox.
+			foreach ( (array) self::BUMP_THRESHOLDS as $bump_threshold ) {
+				if ( ( $note_days_until_expiration > $bump_threshold ) && ( $days_until_expiration <= $bump_threshold ) ) {
+					$note->delete();
+					$note = false;
+					break;
```
Comment (andfinally) [inline plugins/woocommerce/src/Internal/Admin/Notes/WooSubscriptionsNotes.php:282]: I guess this is the critical difference. I'll have to have another look at this tomorrow to try and understand what we're doing here.

* `$note_days_until_expiration` is days until the note expires, that is, until we want to stop showing it.
* `$days_until_expiration` is days until the subscription expires.
* We loop through the array of bump thresholds, which is ordered largest to smallest.
* If the note is due to expire after a threshold and the subscription to expire sooner than the threshold, delete the note and break from the loop.

I suppose the key thing is whether we omit any useful thresholds by breaking here.

Comment (bor0) [reply plugins/woocommerce/src/Internal/Admin/Notes/WooSubscriptionsNotes.php:282]: @andfinally when we delete the `$note` it's already false, so we can't delete it again :)

This is why it only makes sense to do it once, and break. The thresholds are only used to check whether deletion should happen or not

Comment (andfinally) [reply plugins/woocommerce/src/Internal/Admin/Notes/WooSubscriptionsNotes.php:282]: I get it now, thanks. There is only one `$note`, so once deleted we don't want to do anything else.

**Review by andfinally — APPROVED** [review]
Makes good sense and works as planned! 👌
