### PR TITLE
Deprecated WC_Cart->is_coupon_emails_allowed in favour of static DiscountsUtil::is_coupon_emails_allowed

### LINKED ISSUE #47330: Applying coupon on subscription renewal throws PHP Fatal error:  Uncaught Error: Call to a member function is_coupon_emails_allowed() on null in /wp-content/plugins/woocommerce/includes/class-wc-discounts.php:979
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

We are applying custom coupon codes on subscription renewals and due to the is_coupon_emails_allowed function introduced a couple of weeks ago we’ve started to get errors with subscription renewals.

```
2024-05-01T11:01:13+00:00 Notice scheduled action XYZ (subscription payment) failed to finish processing due to the following exception: Call to a member function is_coupon_emails_allowed() on null  
Additional context
{
    "_legacy": true
}

2024-05-01T11:01:13+00:00 Notice action args: subscription_id: XYZ
```

It looks like `WC()->cart` is null in this scenario in https://github.com/woocommerce/woocommerce/blob/release/8.8.0.20/plugins/woocommerce/includes/class-wc-discounts.php#L979 

```
[29-Apr-2024 09:51:25 UTC] PHP Fatal error:  Uncaught Error: Call to a member function is_coupon_emails_allowed() on null in /wp-content/plugins/woocommerce/includes/class-wc-discounts.php:979
Stack trace:
#0 /wp-content/plugins/woocommerce/includes/class-wc-discounts.php(1046): WC_Discounts->validate_coupon_allowed_emails(Object(WC_Coupon))
#1 /wp-content/plugins/woocommerce/includes/class-wc-discounts.php(252): WC_Discounts->is_coupon_valid(Object(WC_Coupon))
#2 /wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-order.php(1252): WC_Discounts->apply_coupon(Object(WC_Coupon))
#3 /wp-content/themes/my_theme/custom/discount-on-renewal.php(132): WC_Abstract_Order->apply_coupon('renewal_couponXYZ')
```

My custom function is called using this filter
```
add_filter( 'wcs_renewal_order_created', 'apply_discount_on_renewal_order_created', 10, 2 );

function apply_discount_on_renewal_order_created( $renewal_order, $subscription ) {
    $coupon_codes = array( 'renewal_code1', 'renewal_code2', 'renewal_code3');

    $order = new WC_Order( $renewal_order->get_id() );
 
   foreach ( $coupon_codes as $coupon_code ) {
	  $coupon        = new WC_Coupon( $coupon_code ); 
	  $expiry_date = $coupon->get_date_expires();

	  if( $coupon->get_usage_count() < $coupon->get_usage_limit() && (date('Y-m-d') < date('Y-m-d', strtotime($expiry_date)) ) ){
		$order->apply_coupon($coupon_code);
	   }
     }
}
```

I’ve already fixed the issue in my theme and wrapped the code in try/catch block but I’m wondering if this shouldn’t be fixed in WooCommerce code as well as cart is not available it this specific scenarion.

Thanks
Michal

### Expected behavior

Email restricted coupons should be applied on subscription renewals

### Actual behavior

Fatal error is thrown

### Steps to reproduce

Apply an email restricted coupon code on subscription renewals

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): http://prodog.local
Site address (URL): http://prodog.local
WC Version: 8.8.3
REST API Version: ✔ 8.8.3
Action Scheduler Version: ✔ 3.7.4
Log Directory Writable: ✔
WP Version: ❌ 6.4.1 - There is a newer version of WordPress available (6.5.3)
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: –
WP Cron: –
Language: en_GB
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.43 (Unix)
PHP Version: 8.2.10
PHP Post Max Size: 1,000 MB
PHP Time Limit: 1200
PHP Max Input Vars: 4000
cURL Version: 8.4.0
(SecureTransport) LibreSSL/3.3.6

SUHOSIN Installed: –
MySQL Version: 5.7.28
Max Upload Size: 300 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ❌ wp_remote_post() failed. Contact your hosting provider.
Remote Get: ❌ wp_remote_get() failed. Contact your hosting provider.

### Database ###

WC Database Version: 7.8.2
WC Database Prefix: wp_
Total Database Size: 10896.83MB
Database Data Size: 5296.99MB
Database Index Size: 5599.84MB

### Status report information ###

Generated at: 2024-05-09 16:01:47 +01:00
`

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by wavvves**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

This PR refactors code and deprecates and moves `is_coupon_emails_allowed()` from `WC_Cart` into a new ` DiscountsUtil` class as it is better suited to live there. This enables 3rd party code to use WC_Discounts in Order context, where a cart might not exist (specific use case linked in the mentioned issue below), thus preventing a fatal error from occurring when trying to access the non-existent cart.

Closes #47330 .

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Create a new coupon named "exclusive", and set email restriction on it
2. Install the Code Snippets extensions and add the following snippet:
```php
add_action("wp_loaded","test_coupon",20,1);
function test_coupon(){
	WC()->cart = null; // making sure there is no cart
	$order = new WC_Order();
	$order->apply_coupon('exclusive');
}
```
3. Refresh any store page and ensure no critical error is displayed
4. Repeat the steps on an unpatched installation and verify that after adding the snippet a critical error is produced.

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 
Fixed a fatal error when programmatically using the WC_Discounts::class in a context where no cart exists.

#### Comment 

</details>

### CODE REVIEW

**Review by Konamiman — DISMISSED** [review]
Given that:

1. We are trying to not add any new methods to classes in `includes` (everything new should go in `src`), and
2. The code in `is_coupon_emails_allowed` is acting exclusively on the input (it doesn't depend on any state)

then I think the `is_coupon_emails_allowed` method should be a `static` method in a new `CouponUtil` class (or perhaps `DiscountUtil`) in `src/Utilities` (normally I would suggest `src/Internal/Utilities` instead, but the method is already public anyway).

Also this is a case where I would add unit tests. I can help with that if you want.

**Comment by wavvves** [comment]
> Given that:
> 
> 1. We are trying to not add any new methods to classes in `includes` (everything new should go in `src`), and
> 2. The code in `is_coupon_emails_allowed` is acting exclusively on the input (it doesn't depend on any state)
> 
> then I think the `is_coupon_emails_allowed` method should be a `static` method in a new `CouponUtil` class (or perhaps `DiscountUtil`) in `src/Utilities` (normally I would suggest `src/Internal/Utilities` instead, but the method is already public anyway).
> 
> Also this is a case where I would add unit tests. I can help with that if you want.

I 100% agree with going the static route. I can make the change, but I do have a question. Do you think it is worth considering if, at this point, anything else should qualify for moving into a DiscountsUtil class and move it, or should I just highlight it for a future refactor?
I'm not a big fan of segmented Utility classes, as that doesn't ever sound too "clean cody" to me (maybe the object scope should be reconsidered if anything kinda falls into its responsibilities but it doesn't fit like a glove). So it becomes harder to justify opening a new Util class with just one method, that might never fit anything else in there becoming a "one trick dog" 🙄

**Comment by barryhughes** [comment]
Adding a couple of thoughts:

> Should be a static method in a new `CouponUtil` class 
> ...
> [Should] anything else should qualify for moving into a `DiscountsUtil` class

Small thing, but if a new util class is the way we go here then, in relation to the proposed classname I also prefer `Discounts` over `Coupons` in this particular case.

> Or should I just highlight it for a future refactor?

I think this is the way to do it. I understand and agree with the concerns around segmentation, but even superficially simple refactorings tend to increase risk and so minimizing the surface area of a change has its own value (in terms of release stability).

**Comment by wavvves** [comment]
@Konamiman @barryhughes I pushed some changes:

* Created a DiscountsUtil class w/ the static method as suggested https://github.com/woocommerce/woocommerce/pull/47589/commits/e26ca24b332630384e927b3eada1305bbb729eb5
* Moved tests that already existed https://github.com/woocommerce/woocommerce/pull/47589/commits/16d3bd114826c270ad6d025917b0a69fbace7fe3
* Took a step further, updating all calls in our codebase for the deprecated method and added a doing it wrong warning to the wrapper. I can revert this if needed https://github.com/woocommerce/woocommerce/pull/47589/commits/37d95a925e1a0f19f1bffd8e4bfcf14cfa38e58b

File: plugins/woocommerce/tests/legacy/unit-tests/discounts/discounts-util.php [hunk 1]
```diff
@@ -0,0 +1,24 @@
...
+ * Test for the discounts utility class.
+ * @package WooCommerce\Tests\DiscountsUtil
+ */
+
+use Automattic\WooCommerce\Utilities\DiscountsUtil;
+
+/**
+ * WC_Tests_DiscountsUtil.
+ */
+class WC_Tests_DiscountsUtil extends WC_Unit_Test_Case {
```
Comment (barryhughes) [inline plugins/woocommerce/tests/legacy/unit-tests/discounts/discounts-util.php]: Thank you for adding, but can we relocate (and rename) so this lives at:

```
tests/php/src/Utilities/DiscountsUtilTest.php
```

[(See guidance here.)](https://github.com/woocommerce/woocommerce/blob/8.9.1/plugins/woocommerce/tests/README.md#guide-for-writing-unit-tests)

Comment (wavvves) [reply plugins/woocommerce/tests/legacy/unit-tests/discounts/discounts-util.php]: Thank you for pointing this out for me, I made the needed adjustments 👍🏼 
I also added a few quick asserts to the test at hand

File: plugins/woocommerce/tests/php/src/Utilities/DiscountsUtilTest.php [hunk 2]
```diff
@@ -0,0 +1,33 @@
...
+	public function test_is_coupon_emails_allowed() {
+		// Direct match.
+		$this->assertEquals( true, DiscountsUtil::is_coupon_emails_allowed( array( 'customer@wc.local' ), array( 'customer@wc.local' ) ) );
+		$this->assertEquals( false, DiscountsUtil::is_coupon_emails_allowed( array( 'customer@wc.local' ), array( 'customer2@wc.local' ) ) );
+
+		// Wildcard match.
+		$this->assertEquals( true, DiscountsUtil::is_coupon_emails_allowed( array( 'customer@wc.local' ), array( '*.local' ) ) );
+		$this->assertEquals( false, DiscountsUtil::is_coupon_emails_allowed( array( 'customer@wc.local' ), array( '*.test' ) ) );
+
+		// Case sensitivity.
```
Comment (wavvves) [inline plugins/woocommerce/tests/php/src/Utilities/DiscountsUtilTest.php:23]: There are [examples](https://github.com/woocommerce/woocommerce/blob/e26ca24b332630384e927b3eada1305bbb729eb5/plugins/woocommerce/includes/class-wc-discounts.php#L984) on handling this outside the method, so added this one to show that, for now, we are specifically taking case in consideration, and not something missed.

File: plugins/woocommerce/tests/php/src/Utilities/DiscountsUtilTest.php [hunk 3]
```diff
@@ -0,0 +1,33 @@
...
+		$this->assertEquals( false, DiscountsUtil::is_coupon_emails_allowed( array( 'Customer@WC.local' ), array( 'customer@wc.local' ) ) );
+
+		// Empty allowed list.
+		$this->assertEquals( false, DiscountsUtil::is_coupon_emails_allowed( array( 'customer@wc.local' ), array() ) );
+		$this->assertEquals( false, DiscountsUtil::is_coupon_emails_allowed( array(), array( 'customer@wc.local' ) ) );
+
+		// Special characters in email.
+		$this->assertEquals( false, DiscountsUtil::is_coupon_emails_allowed( array( 'special@example.com' ), array( 'special+char@example.com' ) ) );
```
Comment (wavvves) [inline plugins/woocommerce/tests/php/src/Utilities/DiscountsUtilTest.php:31]: Also added this one to show we're not currently considering this a match.

File: plugins/woocommerce/includes/class-wc-cart.php [hunk 4]
```diff
@@ -1696,29 +1697,18 @@ public function check_customer_coupons( $posted ) {
...
 	 * @param array $check_emails Array of customer email addresses.
 	 * @param array $restrictions Array of allowed email addresses.
+	 *
 	 * @return bool
+	 * @deprecated 9.0.0 In favor of static method Automattic\WooCommerce\Utilities\DiscountsUtil::is_coupon_emails_allowed.
 	 */
 	public function is_coupon_emails_allowed( $check_emails, $restrictions ) {
+		wc_doing_it_wrong(
+			'WC_Cart::is_coupon_emails_allowed',
+			'This method has been deprecated and will be removed soon. Use Automattic\WooCommerce\Utilities\DiscountsUtil::is_coupon_emails_allowed instead.',
```
Comment (barryhughes) [inline plugins/woocommerce/includes/class-wc-cart.php]: We don't seem to be consistent on this across the codebase, but I think it may be best to localize this message (if a merchant notices the warning, for instance, we probably want them to see it and read it in their own language).

```suggestion
			__( 'This method has been deprecated and will be removed soon. Use Automattic\WooCommerce\Utilities\DiscountsUtil::is_coupon_emails_allowed instead.', 'woocommerce' ),
```

**Review by barryhughes — APPROVED** [review]
Looks good!

🗣️ Left one note about a possible i18n improvement.

🛒 Tested in the cart and checkout, using coupons with 1 allowed email, 2 allowed emails and no allowed emails, and different combinations of user data.

💻 Tested in the WP shell, with `WC()->cart` nullified, as a compliment to the provided testing instructions.

🛠️ Additional tests look great!

**Comment by barryhughes** [comment]
Thanks! Good to merge on my end, unless we want either of the other reviewers to approve first?

**Comment by wavvves** [comment]
> Thanks! Good to merge on my end, unless we want either of the other reviewers to approve first?

I'd be okay merging it now, but merging is blocked pending approval by @Konamiman due to requested changes
