### PR TITLE
CYS - Update the `show_on_front` setting to `posts`

### LINKED ISSUE #49192: Won't open pages after customizing store through CYS feature
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

CYS designed store won't open sample pages due to specific WP settings and for pages after starting CYS. Please check the instructions.

### Expected behavior

Pages accessible

### Actual behavior

Pages not shown, home page instead shown

### Steps to reproduce

1. create a new site
2. update the WP settings like in the attached image
3. create a new page
4. Publish the new page
5. Visit the page and ensure that the right content is visible
6. Start the CYS flow
7. Save the CYS flow
8. Try to visit the new page

image

### WordPress Environment

clean install JN

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by albarin**
This is needed for the CYS flow to work properly

### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes https://github.com/woocommerce/woocommerce/issues/49192

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Make sure all your templates in the TT4 theme are the default ones in `wp-admin/site-editor.php?postType=wp_template`. If they are not, reset each of them until they are.
2. Go to `wp-admin/options-reading.php` and make sure you select `A static page` and save.
Screenshot 2024-07-29 at 13 52 04
3. Go to `wp-admin/tools.php?page=woocommerce-admin-test-helper` and run the `Reset Customize Your Store` command.
3. Go to `wp-admin/admin.php?page=wc-admin&path=%2Fcustomize-store` and click `Start designing`.
4. After the assembler loads go to `wp-admin/options-reading.php` and make sure the `Your homepage displays` is set to `Your latest posts`.

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [x] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 
CYS - Update the "show_on_front" setting to "posts" to avoid overriding the "page" template.
</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce-admin/client/customize-store/design-without-ai/services.ts [hunk 1]
```diff
@@ -128,6 +128,20 @@ const updateGlobalStylesWithDefaultValues = async (
 	);
 };
 
+const updateShowOnFront = async () => {
```
Comment (tjcafferkey) [inline plugins/woocommerce-admin/client/customize-store/design-without-ai/services.ts:131]: I think `apiFetch` won't throw an error for HTTP status code errors (e.g. `400`, `500`). It will only throw an error for network errors.

We should probably handle these cases too, right?

According to the docs `apiFetch` is a wrapper around `window.fetch` which means we can check `response.ok` to determine if the request has been successful or not.

Comment (tjcafferkey) [reply plugins/woocommerce-admin/client/customize-store/design-without-ai/services.ts:131]: That said, `apiFetch` might actually handle non `2xx` status codes by throwing an error. I don't see any handling in Gutenberg specific for status code errors.

Comment (tjcafferkey) [reply plugins/woocommerce-admin/client/customize-store/design-without-ai/services.ts:131]: Seems fine checking the source code https://github.com/WordPress/gutenberg/blob/trunk/packages/api-fetch/src/index.js#L69-L82

**Review by tjcafferkey — APPROVED** [review]
LGTM and works as expected!
