### PR TITLE
Fix 'Invalid payment method' error upon double click 'Delete' #30862

### LINKED ISSUE #30862: "Invalid payment method" error is displayed upon clicking "Delete" button twice on "Add Payment method" screen.
**Prerequisites (mark completed items with an [x]):**
- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
"Invalid payment method" error is displayed upon clicking "Delete" button twice on "Add Payment method" screen.

**Expected behavior**
Payment method should be get deleted without any error.

**Actual behavior**
"Invalid payment method" error is displayed upon clicking "Delete" button twice on "Add Payment method" screen. 

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Create any test site using JN site.
2. Install and activate all the required plugins.
3. Upload and activate the WooCommerce Payments v3.0.0-test-2 plugin.
4. Complete the setup wizard.
5. Complete the KYC flow.
6. Go to Store page and add any product to the cart.
7. Completing the checkout using any test card and save the card during checkout.
8. Go to "Payment Methods".
9. Click on "Delete" button twice.
10. Observe that "Invalid payment method" error is displayed.

**Video**
https://user-images.githubusercontent.com/41110392/132382278-7ef89cd9-bcce-42a0-8c7c-31db314acf6b.mp4

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report we won't be able to fully evaluate this issue.
<details>
```
`
### WordPress Environment ###

WordPress address (URL): http://localhost:8082
Site address (URL): http://localhost:8082
WC Version: 5.7.1
REST API Version: ✔ 5.7.1
WC Blocks Version: ✔ 5.7.2
Action Scheduler Version: ✔ 3.2.1
WC Admin Version: ✔ 2.6.5
Log Directory Writable: ✔
WP Version: 5.8.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.48 (Debian)
PHP Version: 7.3.31
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.74.0
OpenSSL/1.1.1k

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.5.8-MariaDB-1:10.5.8+maria~focal
Max Upload Size: 8 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 5.7.1
WC Database Prefix: wp_
Total Database Size: 5.69MB
Database Data Size: 4.20MB
Database Index Size: 1.49MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.13MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 3.17MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.14MB + Index: 0.09MB + Engine InnoDB
wp_posts: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 23
page: 7
post: 2
product: 19
product_variation: 7
shop_order: 3

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (4) ###

WooCommerce Payments: by Automattic – 3.0.0
WooCommerce: by Automattic – 5.7.1
WordPress Importer: by wordpressdotorg – 0.7

### Inactive Plugins (2) ###

Akismet Anti-Spam: by Automattic – 4.1.12
Hello Dolly: by Matt Mullenweg – 1.7.2

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #5 - /shop/
Cart: #6 - /cart/
Checkout: #7 - /checkout/
My account: #8 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 3.9.1
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Canceled: 3
Oldest: -0001-11-30 00:00:00 +0000
Newest: -0001-11-30 00:00:00 +0000

Complete: 10
Oldest: 2021-09-28 13:24:32 +0000
Newest: 2021-09-30 17:54:27 +0000

Pending: 3
Oldest: 2021-10-01 08:06:03 +0000
Newest: 2021-10-01 08:52:04 +0000


### Status report information ###

Generated at: 2021-10-01 12:11:11 +00:00
`
```
</details>

### PR DESCRIPTION
**Pull request by mgascam**
### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

An 'Invalid payment method' error shows when a user double clicks the'Delete' button in the 'Add Payment method screen'. Every time the user clicks the button, there is a GET request to delete the payment method. First request is handled correctly, but subsequent requests throw an error, because the payment method cannot be found since it was already deleted.

This is a [video](https://user-images.githubusercontent.com/41110392/132382278-7ef89cd9-bcce-42a0-8c7c-31db314acf6b.mp4) of the bug, taken from the issue.

To avoid firing the multiple requests, this PR adds an event handler to the buttons in the Payment method table. The event is attached to the table `tbody` and delegated to `.payment-method-actions .button`. When the event handler is executed, it will check if the button has `.disabled` class. If the button is not disabled, it will add this class and the GET request will fire. If the button is disabled, it calls `preventDefault` in the event, to avoid firing the request.

I'd like to merge this PR to avoid confusion for the user and I also think there is a little performance gain since we are sparing some requests that will end up throwing an error.

Closes #30862

### How to test the changes in this Pull Request:
**Prerequisites**
You'll need to upload and activate the WooCommerce Payments plugin, to be able to add and remove payment methods in the user's account

1. Log in with a valid shop user
2. Go to My Account > Payment Methods
3. Add a Payment method
4. On Payment methods table, double click on 'Delete' button
5. Check that the payment method is correctly removed and there are no errors displayed to the user

This the behavior with the fix applied:

Screen Capture on 2021-10-05 at 18-23-53

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

- Fix 'Invalid payment method' error upon double click 'Delete' button on Add Payment methods screen

### FOR PR REVIEWER ONLY:

* [x] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

File: assets/js/frontend/add-payment-method.js [hunk 1]
```diff
@@ -32,4 +32,10 @@ jQuery( function( $ ) {
 
 	$( document.body ).trigger( 'init_add_payment_method' );
 
+	// Prevent firing multiple requests upon double clicking the buttons in payment methods table
```
Comment (kalessil) [inline assets/js/frontend/add-payment-method.js]: We can simplify to the following:

```javascript
$( 'the button selector here' ).on( 'click', function() {
		$(this).addClass('disabled');
});
```

- `addClass` IIRC will take care of not adding duplicate classes
- `the button selector here` could be `.woocommerce .payment-method-actions .button.delete` - for more flexibility and readability

**Review by kalessil — CHANGES_REQUESTED** [review]
The approach looks good ! Leaving a simplification proposal.

File: assets/js/frontend/add-payment-method.js (hunk 1 above)
Comment (mgascam) [reply assets/js/frontend/add-payment-method.js]: Thanks for checking it @kalessil!

> addClass IIRC will take care of not adding duplicate classes

Yes, good point!. I'll refactor it to follow your suggestion. But I guess I'll still need to check if the element is disabled to call `preventDefault`

> the button selector here could be .woocommerce .payment-method-actions .button.delete - for more flexibility and readability

I decided to use event delegation and attach the event to the payment methods table `.woocommerce-MyAccount-paymentMethods tbody`. In theory there is a small performance boost since there is only one event handler attached vs. one event attached per button. Since it is not likely that a user has that many payment methods, I agree this event delegation is maybe overkill. I am happy to follow your suggestion :)

Comment (kalessil) [reply assets/js/frontend/add-payment-method.js]: `preventDefault`, right, this might be needed. Please add it if it needed.

`I am happy to follow your suggestion`, delegation is an option, but IMO here we can take a simple approach, which is aligned with the rest of the file we are touching. Thanks !

**Comment by kalessil** [comment]
Pulling @nerrad and @ObliviousHarmony for a review, on my end, the changes are looking good !

**Comment by kalessil** [comment]
Ping @ObliviousHarmony

**Review by vedanshujain — APPROVED** [review]
LGTM! Looks like CI is failing, but it's probably unrelated. I have restarted it, and will merge when it passes.
