### PR TITLE
Fix SQL error for exclusion-only and empty search queries

### LINKED ISSUE #63590: Empty or exclusion-only searches cannot produce a valid relevance ORDER BY
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Empty or exclusion-only searches cannot produce a valid relevance ORDER BY.
https://github.com/woocommerce/woocommerce/blob/99bbcac63ac3433ea0e66305f3ddfb49b3aed3c3/plugins/woocommerce/includes/class-wc-query.php#L600-L606
HTTP request: `GET /?post_type=product&s=-condebug`

### Expected behavior

something like
```php
  if ( is_search() ) {
        $search_value = trim( (string) get_query_var( 's' ) );

        // Empty or exclusion-only searches cannot produce a valid relevance ORDER BY.
        if ( '' === $search_value || preg_match( '/^\s*(?:(?:-"[^"]+"|-\S+)\s*)+$/', $search_value ) ) {
                $orderby_value = 'date';
        } else {
                $orderby_value = 'relevance';
        }
  } else {
        $orderby_value = apply_filters( 'woocommerce_default_catalog_orderby',
  get_option( 'woocommerce_default_catalog_orderby', 'menu_order' ) );
  }
```

### Actual behavior

SQL syntax error: `ORDER BY  DESC,`

### Steps to reproduce

HTTP request: `GET /?post_type=product&s=-condebug`

### WordPress Environment

any

### Isolating the problem

- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by kraftbj**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

When a user performs a search with only exclusion terms (e.g. `?s=-condebug`) or an empty search string, WooCommerce unconditionally sets `orderby=relevance`. WordPress core's relevance ordering requires at least one positive search term to build a valid `ORDER BY` clause. Without positive terms, the resulting SQL contains `ORDER BY DESC,` which is a syntax error that causes a fatal database error.

This PR adds a `has_positive_search_terms()` helper method to `WC_Query` that checks whether the current search query contains at least one non-exclusion term. Instead of using a custom regex (which can't accurately replicate WordPress's search tokenization), this delegates to `WP_Query` to parse search terms using core's own rules — correctly handling comma and plus-sign delimiters, quoted phrases, and the `wp_query_search_exclusion_prefix` filter.

When no positive terms are found, the ordering falls back to the default catalog ordering instead of relevance.

Fixes #63590.

### How to test the changes in this Pull Request:

1. Set up a WooCommerce store with some products.
2. Navigate to the shop page with an exclusion-only search: `/?s=-condebug&post_type=product`
3. **Before fix:** A database error / fatal error occurs due to invalid SQL.
4. **After fix:** The page loads normally, using the default catalog ordering.
5. Repeat with an empty search: `/?s=&post_type=product` — should also load without error.
6. Repeat with a bare dash: `/?s=-&post_type=product` — should also load without error.
7. Repeat with comma-separated mixed terms: `/?s=-foo,bar&post_type=product` — should use relevance ordering since `bar` is a positive term.
8. Verify normal searches still work: `/?s=shirt&post_type=product` — should use relevance ordering as before.
9. Verify mixed searches work: `/?s=shirt+-condebug&post_type=product` — should use relevance ordering since there's a positive term.

### Testing that has already taken place:

- PHPStan analysis: no errors
- PHP linting (PHPCS): clean
- Unit tests cover: normal search (relevance), exclusion-only search (fallback), empty search (fallback), multiple exclusion terms (fallback), mixed positive+exclusion terms (relevance), bare dash (fallback), comma-separated mixed terms (relevance), and custom exclusion prefix via filter (fallback).

### Milestone

- [x] Automatically assign milestone for the **[next WooCommerce version](../blob/trunk/plugins/woocommerce/woocommerce.php#L6)**

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

> Changelog entry was created manually and included in the commit.

### CODE REVIEW

**Review by szepeviktor — COMMENTED** [review]
This is very hard. There isn’t a public WordPress API like “is relevance ORDER BY valid for this search?”.

My robobuddy says 🤖 

  Two correctness issues remain in this fix:

  1. `has_positive_search_terms()` still lets `s=-` through, so the SQL error is not fully fixed.

     A lone `-` does **not** match the new exclusion-only regex, so WooCommerce still sets `orderby=relevance`. In core,
  that term gets discarded during search-term parsing as a single dash, which leaves no positive terms for relevance
  ordering and can still produce the broken `ORDER BY DESC` path.

     Can we add a regression test for:

     `/?s=-&post_type=product`

  2. The new regex does not match WordPress search parsing semantics, so it can misclassify searches.

     Core splits search terms on spaces, commas, and `+`, and it also respects the `wp_query_search_exclusion_prefix`
  filter. This implementation hardcodes `-` and treats the raw search string as a single grammar, which creates false
  results.

     Examples:
     - `s=-foo,bar` is a valid mixed search in core (`-foo` + `bar`), but this regex treats it as exclusion-only and
  skips relevance ordering.
     - If a site changes the exclusion prefix to `!`, an exclusion-only search like `s=!foo` would still be treated as
  having positive terms here.

     I think the guard needs to follow core tokenization/exclusion rules much more closely rather than using a
  standalone regex.

  Suggested extra coverage:
  - `/?s=-&post_type=product`
  - `/?s=-foo,bar&post_type=product`
  - a case with a filtered exclusion prefix, e.g. `!`

File: plugins/woocommerce/includes/class-wc-query.php [hunk 1]
```diff
@@ -598,7 +629,7 @@ public function get_catalog_ordering_args( $orderby = '', $order = '' ) {
 			}
 
 			if ( ! $orderby_value ) {
-				if ( is_search() ) {
+				if ( is_search() && $this->has_positive_search_terms() ) {
```
Comment (kalessil) [inline plugins/woocommerce/includes/class-wc-query.php:654]: I wish the solution were as straightforward as this fix suggests. Here is a general approach for addressing the issue reliably:

```php
			if ( ! $orderby_value ) {
				$orderby_value = apply_filters( 'woocommerce_default_catalog_orderby', get_option( 'woocommerce_default_catalog_orderby', 'menu_order' ) );
				if ( is_search() ) {
					// Include a high-level description of the specific edge case we are addressing. Note that we need to
					// use WP_Query to extract the search term because of the various filters and underlying complexity involved.
					$search_string = get_query_var( 's' );
					$search_string = is_array( $search_string ) ? '' : trim ( (string) $search_string );
					if ( '' !== $search_string ) {
						$search_terms     = ( new WP_Query( array( 's' => get_query_var( 's' ) ) ) )->query_vars['search_terms'] ?? array();
						$exclusion_prefix = apply_filters( 'wp_query_search_exclusion_prefix', '-' );
						if ( ! empty( $search_terms ) && '' !== $exclusion_prefix ) {
							$search_terms = array_filter( $search_terms, static fn( $term ) => ! str_starts_with( $term, $exclusion_prefix ) );
							if ( ! empty( $search_terms ) ) {
								$orderby_value = 'relevance';
							}
						}
					}
				}
			}
``

Comment (kraftbj) [reply plugins/woocommerce/includes/class-wc-query.php:654]: Implemented this approach in 5214d5b — replaced the regex with `WP_Query`-based tokenization that delegates to core's search term parsing. This handles comma/plus delimiters, quoted phrases, and the `wp_query_search_exclusion_prefix` filter.

Added test coverage for bare dash (`/?s=-`), comma-separated mixed terms (`/?s=-foo,bar`), and custom exclusion prefix via filter.

**Comment by kraftbj** [comment]
Addressed the feedback from both reviews in 5214d5b:

**Re szepeviktor's points:**
1. Bare dash (`/?s=-`) — now handled correctly. WP_Query's tokenization discards the lone dash, resulting in an empty `search_terms` array, so we fall back to default ordering. Added a regression test.
2. Regex vs core tokenization mismatch — replaced the custom regex entirely. The method now delegates to `WP_Query` for search term parsing, which correctly splits on spaces, commas, and `+`. Comma-separated mixed searches like `/?s=-foo,bar` now correctly detect `bar` as a positive term and use relevance ordering. Added test coverage.
3. Custom exclusion prefix — the method now applies `wp_query_search_exclusion_prefix` instead of hardcoding `-`. Added a test with `!` as the prefix.

**Re kalessil's suggested approach:** adopted it as the foundation. The implementation uses `WP_Query` to extract `search_terms`, then filters out exclusion-prefixed terms using the `wp_query_search_exclusion_prefix` filter.

**Review by szepeviktor — COMMENTED** [review]
Let's merge it!

File: plugins/woocommerce/includes/class-wc-query.php [hunk 2]
```diff
@@ -576,6 +576,52 @@ public function remove_ordering_args() {
...
+		$search_query = new \WP_Query( array( 's' => $search_string ) );
+		$search_terms = $search_query->query_vars['search_terms'] ?? array();
+
+		if ( empty( $search_terms ) ) {
+			return false;
+		}
+
+		/** This filter is documented in wp-includes/class-wp-query.php */
+		$exclusion_prefix = apply_filters( 'wp_query_search_exclusion_prefix', '-' ); // phpcs:ignore WooCommerce.Commenting.CommentHooks.MissingSinceComment
+		$exclusion_prefix = is_string( $exclusion_prefix ) ? $exclusion_prefix : '';
```
Comment (kalessil) [inline plugins/woocommerce/includes/class-wc-query.php]: I'd go with `(string) apply_filters(...)` for simplicity.

File: plugins/woocommerce/includes/class-wc-query.php [hunk 3]
```diff
@@ -576,6 +576,52 @@ public function remove_ordering_args() {
...
+
+		if ( '' !== $exclusion_prefix ) {
+			$search_terms = array_filter(
+				$search_terms,
+				static function ( $term ) use ( $exclusion_prefix ) {
```
Comment (kalessil) [inline plugins/woocommerce/includes/class-wc-query.php]: IIRC, `static fn() => ...` allows to omit `use ( ... )` and keep the code simple. Worth double-checking though.

File: plugins/woocommerce/includes/class-wc-query.php [hunk 4]
```diff
@@ -576,6 +576,52 @@ public function remove_ordering_args() {
...
+	 * terms, which results in invalid SQL when relevance ordering is used.
+	 *
+	 * This method delegates tokenization to WP_Query so it correctly handles WordPress's search
+	 * term parsing (splitting on spaces, commas, and +) and respects the
+	 * wp_query_search_exclusion_prefix filter.
+	 *
+	 * @since 10.8.0
+	 * @return bool
+	 */
+	private function has_positive_search_terms() {
```
Comment (kalessil) [inline plugins/woocommerce/includes/class-wc-query.php]: We can add explicit ': bool' as return type here to align with strictly typed coding style we are leaning towards. Also, if we could come up with an alternative name, it's be great, but non blocking.

File: plugins/woocommerce/tests/php/includes/class-wc-query-test.php [hunk 5]
```diff
@@ -77,4 +78,115 @@ public function test_shop_page_in_home_displays_correctly() {
 		update_option( 'page_on_front', $default_page_on_front );
 		wp_delete_post( $shop_page_id, true );
 	}
+
+	/**
+	 * @testdox Ordering args should use relevance for searches with positive terms.
+	 */
+	public function test_get_catalog_ordering_args_uses_relevance_for_normal_search(): void {
```
Comment (kalessil) [inline plugins/woocommerce/tests/php/includes/class-wc-query-test.php]: Nice group of tests! Can we refactor those so they use data provider (except `test_get_catalog_ordering_args_respects_custom_exclusion_prefix`)?

**Comment by kalessil** [comment]
@coderabbitai: final review, please.

**Comment by kalessil** [comment]
> 1. The new \WP_Query() call runs a real database query

@coderabbitai: addressed

> 2. No memoization

@coderabbitai: With the DB query gone, I assume this should be cheap to execute, so we don't need to memorize it. Can you confirm this assumption is valid?

**Review by kalessil — APPROVED** [review]
Looks good to me.

- I have followed the testing instructions, and the fix functions as intended.
- The code changes are clear and logical.
