### PR TITLE
[COT] Fix error during apply coupon when COT enabled.

### LINKED ISSUE #34470: [COT] Fatal Error on adding Coupons to manual order
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When adding Coupons to manual orders, the site throws Fatal Error. 

https://user-images.githubusercontent.com/6384299/186706402-5a965fe4-cf48-4e81-99bc-401e39c0f912.mp4

### Expected behavior

Coupons should apply without any error. 

### Actual behavior

Site has below error in Log and coupon adding screen stuck in progress for long time. 

`
[25-Aug-2022 15:25:25 UTC] PHP Fatal error:  Uncaught Exception: Unimplemented in /Users/ank/Local Sites/cotwoolocal/app/public/wp-content/plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableDataStore.php:1400
Stack trace:
#0 /Users/ank/Local Sites/cotwoolocal/app/public/wp-content/plugins/woocommerce/includes/class-wc-data-store.php(224): Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore->release_held_coupons(Object(Automattic\WooCommerce\Admin\Overrides\Order), true)
#1 /Users/ank/Local Sites/cotwoolocal/app/public/wp-content/plugins/woocommerce/includes/wc-order-functions.php(932): WC_Data_Store->__call('release_held_co...', Array)
#2 /Users/ank/Local Sites/cotwoolocal/app/public/wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-order.php(1186): wc_update_coupon_usage_counts(3924)
#3 /Users/ank/Local Sites/cotwoolocal/app/public/wp-content/plugins/woocommerce/src/Internal/Orders/CouponsController.php(77): WC_Abstract_Order->apply_coupon('20off')
#4 /Users/ank/Local Sites/cotwoolocal/app/public/wp-content/plugins/woocommerce/src/Internal/Orders/CouponsController.php(25): Automattic\WooCommerce\Internal\Orders\CouponsController->add_coupon_discount(Array)
#5 /Users/ank/Local Sites/cotwoolocal/app/public/wp-content/plugins/woocommerce/includes/class-wc-ajax.php(1166): Automattic\WooCommerce\Internal\Orders\CouponsController->add_coupon_discount_via_ajax()
#6 /Users/ank/Local Sites/cotwoolocal/app/public/wp-includes/class-wp-hook.php(307): WC_AJAX::add_coupon_discount('')
#7 /Users/ank/Local Sites/cotwoolocal/app/public/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters('', Array)
#8 /Users/ank/Local Sites/cotwoolocal/app/public/wp-includes/plugin.php(476): WP_Hook->do_action(Array)
#9 /Users/ank/Local Sites/cotwoolocal/app/public/wp-admin/admin-ajax.php(187): do_action('wp_ajax_woocomm...')
#10 {main}
  thrown in /Users/ank/Local Sites/cotwoolocal/app/public/wp-content/plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableDataStore.php on line 1400
`

### Steps to reproduce

1. Follow this guide and make site COT testable [Custom Order Table testing guide](https://developer.woocommerce.com/2022/05/16/call-for-early-testing-custom-order-table-migrations/)
2. Go to WP Dashboard > WooCommerce > Orders > New order
3. Add Coupon in Apply Coupon Section
4.  Check the error in Log file
5. Order screen will stuck in progress mode

### WordPress Environment

<Details>
`
### WordPress Environment ###

WordPress address (URL): https://cotwoolocal.local
Site address (URL): https://cotwoolocal.local
WC Version: 6.9.0
REST API Version: ✔ 6.9.0
WC Blocks Version: ✔ 8.0.0
Action Scheduler Version: ✔ 3.4.0
Log Directory Writable: ✔
WP Version: 6.0.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.16.0
PHP Version: 8.0.0
PHP Post Max Size: 1,000 MB
PHP Time Limit: 1200
PHP Max Input Vars: 4000
cURL Version: 7.54.0
LibreSSL/2.6.5

SUHOSIN Installed: –
MySQL Version: 5.7.28
Max Upload Size: 300 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 6.9.0
WC Database Prefix: wp_
Total Database Size: 53.95MB
Database Data Size: 31.54MB
Database Index Size: 22.41MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.13MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 1.52MB + Index: 0.72MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 1.02MB + Index: 0.59MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 1.02MB + Index: 0.31MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 7.52MB + Index: 9.09MB + Engine InnoDB
wp_email_log: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
wp_gla_budget_recommendations: Data: 0.22MB + Index: 0.14MB + Engine InnoDB
wp_gla_merchant_issues: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_gla_shipping_rates: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gla_shipping_times: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mo2f_network_blocked_ips: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mo2f_network_email_sent_audit: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mo2f_network_transactions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mo2f_network_whitelisted_ips: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mo2f_user_details: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mo2f_user_login_info: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 7.33MB + Index: 0.13MB + Engine InnoDB
wp_postmeta: Data: 7.42MB + Index: 8.75MB + Engine InnoDB
wp_posts: Data: 1.50MB + Index: 0.42MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.11MB + Index: 0.06MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.08MB + Index: 0.06MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wcpv_commissions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcpv_per_product_shipping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_wc_bookings_availability: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_bookings_availabilitymeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_booking_relationships: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_deposits_payment_plans: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_deposits_payment_plans_schedule: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_orders: Data: 0.28MB + Index: 0.13MB + Engine InnoDB
wp_wc_orders_meta: Data: 1.52MB + Index: 0.52MB + Engine InnoDB
wp_wc_order_addresses: Data: 0.17MB + Index: 0.14MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_operational_data: Data: 0.14MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.09MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.08MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.08MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_square_customers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpns_attack_logs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpns_backup_report: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpns_files_scan: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wpns_ip_rate_details: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpns_malware_hash_file: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wpns_malware_scan_report: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpns_malware_scan_report_details: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpns_malware_skip_files: Data: 0.02MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

attachment: 55
bookable_person: 34
bookable_resource: 150
event_ticket: 140
event_ticket_email: 1
global_product_addon: 1
nav_menu_item: 6
page: 40
post: 15
product: 368
product_variation: 34
revision: 240
shop_coupon: 3
shop_order: 626
shop_order_placehold: 4
shop_order_refund: 5
shop_subscription: 3
wc_booking: 620
wc_membership_plan: 1
wc_user_membership: 1
wp_global_styles: 2
wp_template_part: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (2) ###

WooCommerce Product Vendors: by WooCommerce – 2.1.64
WooCommerce: by Automattic – 6.9.0-dev

### Inactive Plugins (28) ###

Bookings Helper: by WooCommerce – 1.0.3
Debug Log - Config Tool: by Lukman Nakib – 1.1
Email Log: by Sudar – 2.4.8
PHP Compatibility Checker: by WP Engine – 1.6.0
Pig Latin: by Nikolay Bachiyski – 0.2
Plugin Toggle: by Cedaro – 1.3.1
Publisher Media Kit: by 10up – 1.2.1
RTL Tester: by <a href="http://blog.yoavfarhi.com">Yoav Farhi</a>
<a href="http://automattic.com">Automattic</a> – 1.2

WooCommerce Accommodation Bookings: by WooCommerce – 1.1.33
WooCommerce Blocks: by Automattic – 8.3.1
WooCommerce Bookings: by WooCommerce – 1.15.60
WooCommerce Bookings Availability: by WooCommerce – 1.1.20
WooCommerce Box Office: by WooCommerce – 1.1.39
WooCommerce Currency Converter: by WooCommerce – 1.6.28
WooCommerce Deposits: by WooCommerce – 1.5.11
WooCommerce EU VAT Number: by WooCommerce – 2.4.2
WooCommerce Memberships: by SkyVerge – 1.22.9
WooCommerce Min/Max Quantities: by WooCommerce – 3.0.0
WooCommerce Multi-currency: by TIV.NET INC – 2.14.3
WooCommerce PayFast Gateway: by WooCommerce – 1.4.24
WooCommerce PDF Invoices: by Andrew Benbow – 4.15.6
WooCommerce Pre-Orders: by WooCommerce – 1.7.1
WooCommerce Product Add-ons: by WooCommerce – 4.4.0
WooCommerce Product CSV Import Suite: by WooCommerce – 1.10.48
WooCommerce Stripe Gateway: by WooCommerce – 6.6.0
WooCommerce Subscriptions: by WooCommerce – 3.1.3
WP Crontrol: by John Blackbourn & crontributors – 1.14.0
WP Rollback: by Impress.org – 1.7.1

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: accommodation-booking (accommodation-booking)
booking (booking)
external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude_from_catalog (exclude_from_catalog)
exclude_from_search (exclude_from_search)
exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: –

### WC Pages ###

Shop base: #6 - /shop/
Cart: #2333 - /block-based-cart/
Checkout: #1940 - /block-based-checkout/
My account: #9 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 4.1.2 (update to version 4.1.3 is available)
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
experimental-products-task
experimental-import-products-task
experimental-fashion-sample-products
experimental-product-tour
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
settings

Daily Cron: ✔ Next scheduled: 2022-08-26 13:39:06 +05:30
Options: ✔
Notes: 98
Onboarding: completed

### Action Scheduler ###

Complete: 1,577
Oldest: 2022-07-26 13:21:20 +0530
Newest: 2022-08-25 20:44:04 +0530

Pending: 3
Oldest: 2022-08-25 20:49:04 +0530
Newest: 2022-09-18 20:50:03 +0530

### Status report information ###

Generated at: 2022-08-25 20:49:28 +05:30
`
</Details>

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

### LINKED ISSUE #34485: [COT] Error on adding Coupons ->  Error during status transition. Unimplemented
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When we add a coupon during cart product it will give an error. Also I have cross verify with the normal WooCommerce setup it's working as expected there.
Error: " Error during status transition. Unimplemented"

### Expected behavior

The error should not occur.

### Actual behavior

**[COT] WooCommerce setup**
---
image
image

**Without COT normal setup**
---
image

### Steps to reproduce

1. Follow this guide and make site COT testable [Custom Order Table testing guide](https://developer.woocommerce.com/2022/05/16/call-for-early-testing-custom-order-table-migrations/)
2. Add product to the cart
3. View cart and Apply coupon code
4. Process to checkout and complete the order
5. Edit the order in the backend and check the error

### WordPress Environment

**Testing Environment** 
<Details>

`
### WordPress Environment ###

WordPress address (URL): https://woocommerce.test
Site address (URL): https://woocommerce.test
WC Version: 6.9.0
REST API Version: ✔ 6.9.0
WC Blocks Version: ✔ 8.0.0
Action Scheduler Version: ✔ 3.4.0
Log Directory Writable: ✔
WP Version: 6.0.1
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.20.2
PHP Version: 8.0.21
PHP Post Max Size: 2 GB
PHP Time Limit: 36000
PHP Max Input Vars: 1000
cURL Version: 7.76.1
OpenSSL/1.1.1p

SUHOSIN Installed: –
MySQL Version: 5.7.33
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 6.9.0
WC Database Prefix: wp_
Total Database Size: 10.76MB
Database Data Size: 7.39MB
Database Index Size: 3.37MB
wp_woocommerce_sessions: Data: 0.03MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.20MB + Index: 0.20MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.36MB + Index: 0.39MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.19MB + Index: 0.17MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.16MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 3.05MB + Index: 0.08MB + Engine InnoDB
wp_postmeta: Data: 1.52MB + Index: 0.83MB + Engine InnoDB
wp_posts: Data: 0.25MB + Index: 0.09MB + Engine InnoDB
wp_taxjar_record_queue: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_deposits_payment_plans: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_deposits_payment_plans_schedule: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_orders: Data: 0.17MB + Index: 0.05MB + Engine InnoDB
wp_wc_orders_meta: Data: 0.31MB + Index: 0.28MB + Engine InnoDB
wp_wc_order_addresses: Data: 0.11MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_operational_data: Data: 0.09MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.05MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.06MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 28
global_product_addon: 1
page: 9
post: 2
product: 22
product_variation: 7
revision: 30
shop_coupon: 3
shop_order: 334
shop_order_placehold: 23
shop_order_refund: 1
shop_subscription: 7
wp_global_styles: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (5) ###

Query Monitor: by John Blackbourn – 3.9.0
WooCommerce Stripe Gateway: by WooCommerce – 6.5.1
WooCommerce Payments: by Automattic – 4.5.1 (update to version 4.6.0 is available)
WooCommerce Subscriptions: by WooCommerce – 3.1.3
WooCommerce: by Automattic – 6.9.0-dev

### Inactive Plugins (21) ###

Akismet Anti-Spam: by Automattic – 4.2.4
Braintree for WooCommerce Payment Gateway: by WooCommerce – 2.6.5
ClassifAI: by 10up – 1.7.2
Debug Bar: by wordpressdotorg – 1.1.3
Distributor: by 10up Inc. – 1.6.9
Hello Dolly: by Matt Mullenweg – 1.7.2
Jetpack: by Automattic – 11.1.1
TaxJar - Sales Tax Automation for WooCommerce: by TaxJar – 4.1.3
WooCommerce Blocks: by Automattic – 8.2.1
WooCommerce Bookings: by WooCommerce – 1.15.57
WooCommerce Checkout Add-Ons: by SkyVerge – 2.5.6
WooCommerce Currency Converter: by WooCommerce – 1.6.28
WooCommerce Deposits: by WooCommerce – 1.6.0
WooCommerce Eway Payment Gateway: by WooCommerce – 3.4.3 (update to version 3.4.4 is available)
WooCommerce GoCardless Gateway: by WooCommerce – 2.4.15
WooCommerce Multi-currency: by TIV.NET INC – 2.14.3
WooCommerce One Page Checkout: by Automattic – 1.9.4
WooCommerce Product Add-ons: by WooCommerce – 5.0.0
WooCommerce Subscriptions CSV Importer and Exporter: by Prospress Inc – 2.1.0
WooCommerce Xero Integration: by WooCommerce – 1.7.44
WP Crontrol: by John Blackbourn & crontributors – 1.14.0

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔

### WC Pages ###

Shop base: #6 - /shop/
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 4.1.2 (update to version 4.1.3 is available)
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Subscriptions ###

WCS_DEBUG: ✔ No
Subscriptions Mode: ✔ Live
Subscriptions Live URL: https://woocommerce.test
Subscription Statuses: wc-active: 5
wc-on-hold: 2

WooCommerce Account Connected: ❌ No
Report Cache Enabled: ✔ Yes
Cache Update Failures: ✔ 0 failure

### Store Setup ###

Country / State: United States (US) — Alabama

### Subscriptions by Payment Gateway ###

other: wc-active: 2
wc-on-hold: 1

Stripe: wc-active: 2

### Payment Gateway Support ###

Cash on delivery: products
Direct bank transfer: products
Check payments: products
Stripe: products
refunds
tokenization
add_payment_method
subscriptions
subscription_cancellation
subscription_suspension
subscription_reactivation
subscription_amount_changes
subscription_date_changes
subscription_payment_method_change
subscription_payment_method_change_customer
subscription_payment_method_change_admin
multiple_subscriptions

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
experimental-products-task
experimental-import-products-task
experimental-fashion-sample-products
experimental-product-tour
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
settings

Daily Cron: ✔ Next scheduled: 2022-08-26 11:01:07 +00:00
Options: ✔
Notes: 62
Onboarding: completed

### WooCommerce Payments ###

Version: 4.5.1
Connected to WPCOM: No
Blog ID: -
Account ID: -

### Action Scheduler ###

Complete: 1,064
Oldest: 2022-07-26 09:53:58 +0000
Newest: 2022-08-17 06:36:42 +0000

Pending: 6
Oldest: 2022-08-26 09:14:43 +0000
Newest: 2022-09-05 13:22:20 +0000

### Status report information ###

Generated at: 2022-08-26 09:09:34 +00:00
`

</Details>

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by iamdharmesh**
### All Submissions:

-   [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
-   [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
-   [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change?

### Changes proposed in this Pull Request:
This PR implements coupon held methods (`set_coupon_held_keys`, `release_held_coupons` etc...) in the Orders Table data store. Basically, it is the same code as `WC_Order_Data_Store_CPT` data store. 

Alternative solution: We can call a method of `WC_Order_Data_Store_CPT` class from `OrdersTableDataStore` to reduce code duplication. 

Closes #34470
Closes #34485 

### How to test the changes in this Pull Request:
**34470**
1. Follow this guide and make site COT testable [Custom Order Table testing guide](https://developer.woocommerce.com/2022/05/16/call-for-early-testing-custom-order-table-migrations/)
2. Go to WP Dashboard > WooCommerce > Orders > New order
3. Add Coupon in Apply Coupon Section
4. Make sure the coupon is applied properly without any errors.

**34485**
1. Follow this guide and make site COT testable [Custom Order Table testing guide](https://developer.woocommerce.com/2022/05/16/call-for-early-testing-custom-order-table-migrations/)
2. Add product to the cart
3. View cart and Apply coupon code
4. Process to checkout and complete the order
5. Update order status.
6. Verify order status is updated properly and there is no order note like `Error during status transition. Unimplemented`

### Other information:

-   [x] Have you added an explanation of what your changes do and why you'd like us to include them?
-   [ ] Have you written new tests for your changes, as applicable?
-   [ ] Have you successfully run tests with your changes locally?
-   [x] Have you created a changelog file for each project being changed, ie `pnpm changelog add --filter=<project>`?

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

File: plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableDataStore.php [hunk 1]
```diff
@@ -1453,20 +1453,85 @@ protected function update_post_meta( &$order ) {
...
+	 *
+	 * @param WC_Order $order Current order object.
+	 * @param bool     $save  Whether to delete keys from DB right away. Could be useful to pass `false` if you are building a bulk request.
+	 */
 	public function release_held_coupons( $order, $save = true ) {
-		throw new \Exception( 'Unimplemented' );
+		$coupon_held_keys = $this->get_coupon_held_keys( $order );
+		if ( is_array( $coupon_held_keys ) ) {
+			foreach ( $coupon_held_keys as $coupon_id => $meta_key ) {
+				delete_post_meta( $coupon_id, $meta_key );
```
Comment (vedanshujain) [inline plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableDataStore.php]: this should be replaced with $coupon->delete_meta, and then a save call

File: plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableDataStore.php [hunk 2]
```diff
@@ -1453,20 +1453,85 @@ protected function update_post_meta( &$order ) {
...
+			}
+		}
+		$order->delete_meta_data( '_coupon_held_keys' );
+
+		$coupon_held_keys_for_users = $this->get_coupon_held_keys_for_users( $order );
+		if ( is_array( $coupon_held_keys_for_users ) ) {
+			foreach ( $coupon_held_keys_for_users as $coupon_id => $meta_key ) {
+				delete_post_meta( $coupon_id, $meta_key );
```
Comment (vedanshujain) [inline plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableDataStore.php]: same as above, should replace with $coupon->delete_meta

**Review by vedanshujain — CHANGES_REQUESTED** [review]
requesting minor changes, otherwise looks good. thanks!

File: plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableDataStore.php (hunk 1 above)
Comment (iamdharmesh) [reply plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableDataStore.php]: Hi @vedanshujain, I tried to delete meta data with the $coupon but got strange behavior.
I am replacing `delete_post_meta` with the below code. but it does not remove metadata from the database.
```php
$coupon = new \WC_Coupon( $coupon_id );
$coupon->delete_meta_data( $meta_key );
$coupon->save_meta_data();
```
I debugged on this and found that `$coupon` object does not contain the metadata we are trying to delete ($meta_key), `$coupon->meta_exists( $meta_key );` returns `false`. I believe it is because of the cache, maybe because we are adding `_coupon_held_XXX` metadata using SQL query so, it is not clear the meta cache. I tried putting the below code before the above code and it started working (save_meta_data() has cleared meta cache so it is getting the latest data from DB properly now.). 

```php
$coupon = new \WC_Coupon( $coupon_id );
$coupon->save_meta_data();
```

do you have any idea about this or have you faced a situation like this before? If yes can you please suggest on how we can proceed here?

Thanks

Comment (vedanshujain) [reply plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableDataStore.php]: Your reasoning makes sense, maybe we need to call `clean_post_cache( $coupon->get_id() )` or something similar right after we insert the metadata? maybe here -> https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/includes/data-stores/class-wc-coupon-data-store-cpt.php#L558

Comment (iamdharmesh) [reply plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableDataStore.php]: Thanks, Clearing meta cache did the job here. :+1:

**Comment by vedanshujain** [comment]
Thanks, the changes look good. I am pushing recent trunk into this branch to see if tests pass. Thanks!

**Review by vedanshujain — APPROVED** [review]
LGTM! Seems like the failing test is because this is a fork. Manually verified that there are no hooks needing documentation.
