### PR TITLE
Send calling code to PayPal

### LINKED ISSUE #21110: Phone number does not pass to PayPal Guest Checkout
**Describe the bug**
Using PayPal Standard the phone number filled out on the checkout page isn't passed to PayPal guest checkout.

**To Reproduce**
1. Prefill checkout page fields
2. Choose PayPal Standard payment option and Proceed to PayPal
3. Select the **Pay with Debit or Credit Card** button on PayPal login page
4. See error no phone number is added to PayPal Guest Checkout fields.

**Screenshots**
Screenshot
Image Link: http://cld.wthms.co/gtkMxf

### PR DESCRIPTION
**Pull request by mikejolley**
Send calling code + phone in paypal request.

Fixes #21110

@peterfabian I found docs buried on PP website somewhere that night_phone_a should be the calling code when dealing with non-US phone numbers. This fixed the issue.

- Introduces `get_calling_code_for_country` function + json file with codes
- Works out calling code based on country code
- Formats night_phone a and b correctly.

To test,

- Use sandbox
- Valid UK address and phone
- Go to PayPal and choose to pay by card

You may need to clean all paypal cookies before doing this and turn off proxy. That was the only way I could get UK to pre-populate paypal side.

> Send correct calling code and phone number to PayPal standard when using non-US addresses.

### CODE REVIEW

**Review by claudiosanches — CHANGES_REQUESTED** [review]
I think we could parse this into an array, so we don't need to set cache or read a JSON file.
Those numbers should not change, or at least not too often anyway.

File: includes/class-wc-countries.php [hunk 1]
```diff
@@ -90,6 +90,24 @@ public function get_continent_code_for_country( $cc ) {
...
 	}
 
+	/**
+	 * Get calling code for a country code.
+	 *
+	 * @since 3.6.0
+	 * @param string $cc Country code.
+	 * @return string
+	 */
+	public function get_calling_code_for_country( $cc ) {
```
Comment (claudiosanches) [inline includes/class-wc-countries.php]: We could rename to `get_country_callind_code()`.

File: includes/gateways/paypal/includes/class-wc-gateway-paypal-request.php [hunk 2]
```diff
@@ -210,8 +210,11 @@ protected function get_phone_number_args( $order ) {
 				'night_phone_c' => substr( $phone_number, 6, 4 ),
 			);
 		} else {
+			$calling_code = WC()->countries->get_calling_code_for_country( $order->get_billing_country() );
+			$phone_number = $calling_code ? preg_replace( '/^0/', '', $order->get_billing_phone() ) : $order->get_billing_phone();
```
Comment (claudiosanches) [inline includes/gateways/paypal/includes/class-wc-gateway-paypal-request.php]: We are removing `0` from the beginning, but is fine use `+`? Maybe we should remove too, or start including, since that list doesn't include for all numbers.
Also what happens if a customer already includes calling code? Probably we should remove it before including into `night_phone_b`.

**Review by claudiosanches — DISMISSED** [review]

File: includes/gateways/paypal/includes/class-wc-gateway-paypal-request.php (hunk 2 above)
Comment (peterfabian) [reply includes/gateways/paypal/includes/class-wc-gateway-paypal-request.php]: This won't work for some countries, as per [popular phone numbers resource](https://github.com/googlei18n/libphonenumber/blob/master/FALSEHOODS.md) bullet point 12 and 20. However, I guess it should work for most.

**Comment by peterfabian** [comment]
I'm still having problems getting the phone number to show in PayPal. Incognito mode, so hopefully no cookies.

Seems like formats +44 XX XXXX XXXX or 0044 XX XXXX XXXX are not sent correctly?

**Comment by mikejolley** [comment]
@peterfabian Can you explain?

+44 is a UK format which is the one I tested. We don't separate numbers like that, and when +44 is used, the preceeding 0 is removed.

e.g. +441954 123456

File: includes/gateways/paypal/includes/class-wc-gateway-paypal-request.php (hunk 2 above)
Comment (claudiosanches) [reply includes/gateways/paypal/includes/class-wc-gateway-paypal-request.php]: @peterfabian yep, but probably depends on how PayPal wants that data, with that `+` or not...

**Comment by peterfabian** [comment]
E.g.I tried this
screenshot 2019-02-22 at 19 40 26

which creates a PayPal link with `night_phone_a=44&night_phone_b=%2B442076232323` that does not show up in PayPal for me. 

I'm not sure about the correct formatting, just took an address from Google Maps, e.g.:
screenshot 2019-02-22 at 19 44 49

Tried using number +441954 123456, but that also didn't go through, maybe I'm having something set up incorrectly.

**Comment by claudiosanches** [comment]
@mikejolley @peterfabian Maybe removing `%2B44` from `night_phone_a=44&night_phone_b=%2B442076232323` ?

**Comment by mikejolley** [comment]
@peterfabian I've updated the logic to work with +44 format entered manually. Can you test again?

If we feel this is going to be too difficult to get right (reading that link you sent), perhaps we just mark won't fix and let them enter manually on PayPal?

**Review by peterfabian — APPROVED** [review]
Seems to work correctly now. 👍
