### PR TITLE
Display product URL only if is not hidden in downloads list

### LINKED ISSUE #17925: Links to hidden products displayed when they are also downloadable
As stated in the title, if a hidden product is also downloadable and is purchased (most likely through a grouping), a link to the product is displayed in the Thank You page and also the order confirmation email.

This is due to the [order-downloads template](https://github.com/woocommerce/woocommerce/blob/3.2.5/templates/order/order-downloads.php#L45-L48) does not do the same (or similar) check as the [order-details-item template](https://github.com/woocommerce/woocommerce/blob/3.2.5/templates/order/order-details-item.php#L31-L34) to see if the product is visible or not. 

## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Create a product, make it downloadable, and set as hidden.
2. Purchase product.
3. View Thank You page and email received, there will be a link to the product.

Image Link: http://cld.wthms.co/ikk80G

### PR DESCRIPTION
**Pull request by claudiosanches**
Fixes #17925

### CODE REVIEW

File: includes/class-wc-order.php [hunk 1]
```diff
@@ -105,7 +108,7 @@ public function payment_complete( $transaction_id = '' ) {
 			}
 			do_action( 'woocommerce_pre_payment_complete', $this->get_id() );
 
-			if ( ! empty( WC()->session ) ) {
+			if ( ! WC()->session ) {
```
Comment (claudiulodro) [inline includes/class-wc-order.php]: This check is the opposite of what it used to be. Did you mean `if ( WC()->session )`?

**Comment by claudiulodro** [comment]
A test broke during the phpcs fixes: https://travis-ci.org/woocommerce/woocommerce/jobs/308419595

**Comment by claudiulodro** [comment]
Just needs a couple small changes then it's good to merge.
