### PR TITLE
Fix shipping cost formatting to respect shipping formula

### LINKED ISSUE #42892: Shipping calculation formula does not display correctly in modal after saving
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When using shipping formulas in advanced flat rate costs, the formula is omitted when reopening the modal after saving. This only happens for merchant-generated zones, not the default "Rest of the world" zone. 

### Expected behavior

I expected that the entered formulas would stay visible so that I could see the exact shipping costs I had created for the store. 

### Actual behavior

While the formulas are saved, they're not displayed correctly when edited again. This makes it appear they are saving incorrectly. Saving again overwrites with the incorrect shipping amount. 

Setting as entered: 
Screenshot 2023-12-15 at 5 06 37 PM

Shipping in the cart: 
Screenshot 2023-12-15 at 5 06 46 PM

Setting opened again and resaved: 
Screenshot 2023-12-15 at 5 06 57 PM

Shipping in the cart: 
Screenshot 2023-12-15 at 5 07 11 PM

Rest of world shipping, does not show curre
Screenshot 2023-12-15 at 5 09 08 PM
ncy symbol or decimals, respects formula as entered. 

### Steps to reproduce

1. Create at least one shipping zone 
2. Add flat rate shipping with a formula to that zone, ex: `5*[qty]` or `10 + (2*[qty])`
3. Add items to the cart and see that the formula is respected 
4. Click edit for the same flat rate method again, see the formula is missing, only `5.00` or `10.00` remains 
5. Click Save within the modal
6. Refresh the cart and see the shipping rate does not respect the formula  
7. Repeat creating a shipping formula in the "Rest of the world" zone 
8. See that the formula persists when the method is edited 

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://wooooooo.mystagingwebsite.com
Site address (URL): https://wooooooo.mystagingwebsite.com
WC Version: 8.4.0
REST API Version: ✔ 8.4.0
WC Blocks Version: ✔ 11.6.2
Action Scheduler Version: ✔ 3.7.0
Log Directory Writable: ✔
WP Version: 6.4.2
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 8.1.26
PHP Post Max Size: 2 GB
PHP Time Limit: 1200
PHP Max Input Vars: 6144
cURL Version: 8.4.0
OpenSSL/1.1.1n

SUHOSIN Installed: –
MySQL Version: 10.4.26-MariaDB-log
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.4.0
WC Database Prefix: wp_
Total Database Size: 47.06MB
Database Data Size: 29.24MB
Database Index Size: 17.82MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.11MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 1.52MB + Index: 0.52MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 3.02MB + Index: 0.98MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 1.30MB + Index: 0.52MB + Engine InnoDB
wp_advanced_notifications: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_advanced_notification_triggers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_afwc_campaigns: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_afwc_commission_plans: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_afwc_hits: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_afwc_payouts: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_afwc_payout_orders: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_afwc_referrals: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_automatewoo_abandoned_carts: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_automatewoo_customers: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_automatewoo_customer_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_guests: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_automatewoo_guest_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_log_meta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_queue: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_queue_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_referrals: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_automatewoo_referral_advocate_keys: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_automatewoo_referral_invites: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_ce4wp_abandoned_checkout: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_ced_amazon_feeds: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ced_amazon_profiles: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 1.52MB + Index: 0.67MB + Engine InnoDB
wp_FmeCCFA_fields: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_followup_coupons: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_coupon_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_customers: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_followup_customer_carts: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_customer_notes: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_customer_orders: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_followup_email_excludes: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_email_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_email_orders: Data: 0.09MB + Index: 0.09MB + Engine InnoDB
wp_followup_email_tracking: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_followup_followup_history: Data: 0.11MB + Index: 0.05MB + Engine InnoDB
wp_followup_order_categories: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_order_items: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_subscribers: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_subscribers_to_lists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_subscriber_lists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gla_attribute_mapping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gla_budget_recommendations: Data: 0.20MB + Index: 0.11MB + Engine InnoDB
wp_gla_merchant_issues: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gla_shipping_rates: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_gla_shipping_times: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_hubwoo_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_jetpack_sync_queue: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailchimp_carts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailchimp_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_automations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_automation_runs: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_mailpoet_automation_run_logs: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_mailpoet_automation_run_subjects: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_automation_triggers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_automation_versions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_custom_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_dynamic_segment_filters: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_feature_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_forms: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_mapping_to_external_entities: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletters: Data: 0.16MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_newsletter_links: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_newsletter_option: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_option_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_posts: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_segment: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_templates: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_scheduled_tasks: Data: 0.13MB + Index: 0.13MB + Engine InnoDB
wp_mailpoet_scheduled_task_subscribers: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_segments: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_sending_queues: Data: 0.11MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_settings: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_statistics_bounces: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_statistics_clicks: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_statistics_forms: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_statistics_newsletters: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_statistics_opens: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_mailpoet_statistics_unsubscribes: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_statistics_woocommerce_purchases: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_mailpoet_stats_notifications: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_subscribers: Data: 0.02MB + Index: 0.23MB + Engine InnoDB
wp_mailpoet_subscriber_custom_field: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_subscriber_ips: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_subscriber_segment: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_subscriber_tag: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_tags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_user_agents: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_user_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_ms_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 4.17MB + Index: 0.25MB + Engine InnoDB
wp_postmeta: Data: 3.52MB + Index: 3.03MB + Engine InnoDB
wp_posts: Data: 1.52MB + Index: 0.36MB + Engine InnoDB
wp_rank_math_internal_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_rank_math_internal_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_snippets: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_stream: Data: 0.02MB + Index: 0.13MB + Engine InnoDB
wp_stream_meta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.14MB + Index: 0.06MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.11MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wcpv_commissions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcpv_per_product_shipping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcrp_rental_products_rentals: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcs_payment_retries: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.11MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.08MB + Index: 0.02MB + Engine InnoDB
wp_wc_avatax_tax_codes: Data: 0.33MB + Index: 0.00MB + Engine InnoDB
wp_wc_bookings_availability: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_bookings_availabilitymeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_booking_relationships: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_deposits_payment_plans: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_deposits_payment_plans_schedule: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_orders: Data: 0.27MB + Index: 0.39MB + Engine InnoDB
wp_wc_orders_meta: Data: 1.52MB + Index: 4.03MB + Engine InnoDB
wp_wc_order_addresses: Data: 0.19MB + Index: 0.28MB + Engine InnoDB
wp_wc_order_bundle_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_order_composite_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_operational_data: Data: 0.14MB + Index: 0.09MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.09MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.08MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_wc_points_rewards_user_points: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_points_rewards_user_points_log: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_pos_grid_tiles: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.06MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_warranty_products: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_zapier_history: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_bundled_itemmeta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_bundled_items: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_exported_csv_items: Data: 0.45MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_gc_activity: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_gc_cards: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_gc_cardsmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_pickup_locations_geodata: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_prl_deploymentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_prl_deployments: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_prl_frequencies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_prl_tracking_conversions: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_shipping_quotes: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_shipping_table_rates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_square_customers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpml_mails: Data: 1.52MB + Index: 0.02MB + Engine InnoDB
wp_wp_phpmyadmin_extension__errors_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wsal_metadata: Data: 0.09MB + Index: 0.11MB + Engine InnoDB
wp_wsal_occurrences: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_wt_iew_action_history: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wt_iew_cron: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wt_iew_ftp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wt_iew_mapping_template: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_yoast_indexable: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_yoast_indexable_hierarchy: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_primary_term: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_yoast_seo_links: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_zbscrm_api_keys: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_zbs_admlog: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_zbs_aka: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_zbs_companies: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_zbs_contacts: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_zbs_customfields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_zbs_dbmigration_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_zbs_dbmigration_posts: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_zbs_events: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_zbs_event_reminders: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_zbs_externalsources: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_zbs_forms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_zbs_invoices: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_zbs_lineitems: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_zbs_logs: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_zbs_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_zbs_notifications: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_zbs_object_links: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_zbs_quotes: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_zbs_quotes_templates: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_zbs_security_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_zbs_segments: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_zbs_segments_conditions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_zbs_settings: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_zbs_sys_cronmanagerlogs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_zbs_sys_email: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_zbs_sys_email_hist: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_zbs_tags: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_zbs_tags_links: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_zbs_tax_table: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_zbs_temphash: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_zbs_tracking: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_zbs_transactions: Data: 0.02MB + Index: 0.14MB + Engine InnoDB
wp_zettle_queue: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_zettle_woocommerce_id_map: Data: 0.02MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

attachment: 175
aw_workflow: 13
bookable_person: 3
bookable_resource: 5
custom_css: 2
efw_fees: 1
event_ticket: 4
fme_upload_files: 1
follow_up_email: 8
global_product_addon: 1
jetpack_migration: 2
jp_pay_product: 3
mailpoet_page: 1
nav_menu_item: 25
oembed_cache: 9
page: 47
pdr_product_base: 16
post: 8
pos_outlet: 1
pos_receipt: 1
pos_register: 1
pos_session: 1
pos_temp_order: 1
prl_engine: 1
product: 145
product_variation: 259
qts_form_field: 12
revision: 94
seedprod: 2
shop_coupon: 35
shop_order: 666
shop_order_refund: 16
shop_subscription: 82
sidebar: 1
user_request: 4
wc_booking: 45
wc_memberships_team: 1
wc_membership_plan: 2
wc_order_email: 1
wc_order_status: 8
wc_user_membership: 3
wc_voucher: 2
wc_voucher_template: 3
woa_rules: 1
wp_global_styles: 5
wp_navigation: 4
wp_template: 13
wp_template_part: 3

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 8.4.0

### Inactive Plugins (6) ###

Akismet Anti-spam: Spam Protection: by Automattic - Anti-spam Team – 5.3
Code Snippets: by Code Snippets Pro – 3.6.2
Jetpack: by Automattic – 13.0-a.5
WooCommerce Shipping & Tax: by WooCommerce – 2.4.2
WooPayments: by Automattic – 6.9.2
WP Mail Logging: by WP Mail Logging Team – 1.12.0

### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
object-cache.php: Memcached

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: booking (booking)
bundle (bundle)
composite (composite)
external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to Woo.com: ✔
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: ✔

### WC Pages ###

Shop base: #5 - /shop/
Cart: #6 - /cart/
Checkout: #7 - /checkout/
My account: #8 - /my-account/
Terms and conditions: ❌ Page visibility should be public

### Theme ###

Name: Storefront
Version: 4.5.3
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: /wordpress/plugins/woocommerce/8.4.0/packages/woocommerce-blocks/templates/notices/error.php
/wordpress/plugins/woocommerce/8.4.0/packages/woocommerce-blocks/templates/notices/notice.php
/wordpress/plugins/woocommerce/8.4.0/packages/woocommerce-blocks/templates/notices/success.php

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
product-virtual-downloadable
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: customize-store
minified-js
new-product-management-experience
product-external-affiliate
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2023-12-16 17:44:56 -08:00
Options: ✔
Notes: 204
Onboarding: completed

### Action Scheduler ###

Canceled: 3
Oldest: 2023-11-23 03:59:33 -0800
Newest: 2023-11-30 15:54:59 -0800

Complete: 1,079
Oldest: 2023-11-14 17:10:42 -0800
Newest: 2023-12-15 17:06:04 -0800

Failed: 1,622
Oldest: 2022-11-02 17:41:52 -0700
Newest: 2023-12-15 17:02:43 -0800

Pending: 3
Oldest: 2023-12-16 04:19:35 -0800
Newest: 2024-07-15 18:31:28 -0700

### Status report information ###

Generated at: 2023-12-15 17:10:38 -08:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by ilyasfoo**
### Changes proposed in this Pull Request:

Closes #42892:

- Fix number formatting function to respect shipping formula
- Add relevant unit tests

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. In a fresh store with default country and currency configuration, go to WooCommerce > Settings > Shipping
2. Create a new shipping zone
3. From the new shipping zone, add a shipping method, choose `Flat rate`
4. In the `Cost` field, set `10*[qty]+(1+(2/[cost]))+([fee percent="10" max_fee="8.33"])`
5. Click `Create`
6. Refresh the page
7. Click on `Edit` on the new shipping method
8. Observe that the value is `10*[qty]+(1+(2/[cost]))+([fee percent="10" max_fee="8.33"])`
9. Test all possible combination of valid shipping formula and ensure the formatting does not break the formula

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce-admin/client/wp-admin-scripts/shipping-settings-region-picker/currency-context.js [hunk 1]
```diff
@@ -5,14 +5,39 @@ import { useContext, useEffect } from '@wordpress/element';
...
+	if ( typeof number === 'string' ) {
+		/**
+		 * \b: Ensures that we're capturing whole numbers (word boundaries).
+		 * \d+: Matches one or more digits.
+		 * (\.\d+)?: Optionally matches a decimal point followed by one or more digits.
+		 * (?![^[]*\]): A negative lookahead to avoid numbers inside square brackets.
+		 * g: Global flag to match all instances in the string.
+		 */
+		return number.replace( /(\b\d+(\.\d+)?\b)(?![^[]*\])/g, ( n ) =>
+			numberFormat( config, n )
```
Comment (psealock) [inline plugins/woocommerce-admin/client/wp-admin-scripts/shipping-settings-region-picker/currency-context.js]: I'm not entirely sure we should format numbers in the formula.

`50000000.00 + (([qty]*2.00+1.00)(5.00*10.00))(1.00)` becomes the following. Its probably rare but I'm not sure how much we gain here. 

```
50,000,000.00 + (([qty]*2.00+1.00)(5.00*10.00))(1.00)
```

Comment (psealock) [reply plugins/woocommerce-admin/client/wp-admin-scripts/shipping-settings-region-picker/currency-context.js]: Then again, it does seem to work with the formatted values. I'm still of the mind that this introduces complexity and we can remove it. What do you think?

image

**Review by psealock — COMMENTED** [review]
Nice solution here @ilyasfoo 

I've tested a few combinations and seen them correctly reflected on the frontend at checkout.

I did raise an issue with formatting numbers in the formula.

File: plugins/woocommerce-admin/client/wp-admin-scripts/shipping-settings-region-picker/currency-context.js (hunk 1 above)
Comment (ilyasfoo) [reply plugins/woocommerce-admin/client/wp-admin-scripts/shipping-settings-region-picker/currency-context.js]: Good point, I tend to agree now. I'll simplify to only handle formatting when it's exclusively a number. Thanks for the feedback!

**Comment by psealock** [comment]
@ilyasfoo Something else is amiss here.

When setting my currency to Euro with `.` thousandth separator and `,` as decimal it treats it like a string

image

When you add/save a cost I get this behaviour.

`7,5` -> `7,00,5,00`
`7.5` -> `75,00`

and if you edit/save without changing the value changes each time.

**Comment by ilyasfoo** [comment]
Great catch, @psealock!

In https://github.com/woocommerce/woocommerce/pull/42916/commits/1c1da9bd0986ff8c9702eca0dacd98c768ed65da, I've converted the regex to be dynamic and respects the thousands and decimal separator set in config. I've also added a test case when the config is set differently.

I also addressed your feedback on formatting formula. Now, the formatter only applies format when it's a single number. Please take another look! 🙇

File: plugins/woocommerce/includes/shipping/flat-rate/class-wc-shipping-flat-rate.php [hunk 2]
```diff
@@ -281,7 +281,7 @@ public function find_shipping_classes( $package ) {
 	public function sanitize_cost( $value ) {
 		$value = is_null( $value ) ? '' : $value;
 		$value = wp_kses_post( trim( wp_unslash( $value ) ) );
-		$value = str_replace( array( get_woocommerce_currency_symbol(), html_entity_decode( get_woocommerce_currency_symbol() ), wc_get_price_thousand_separator() ), '', $value );
+		$value = str_replace( array( get_woocommerce_currency_symbol(), html_entity_decode( get_woocommerce_currency_symbol() ) ), '', $value );
```
Comment (ilyasfoo) [inline plugins/woocommerce/includes/shipping/flat-rate/class-wc-shipping-flat-rate.php:284]: This was interfering with saving an "invalid" value, in essence trying to outsmart the user:

1. Set thousands separator to `.`
2. Set decimal separator to `,`
3. Attempt to save `7.5`
4. Now it should still save `7.5` instead of `75`

p1702984979539049/1702957440.967159-slack-C01SFMVEYAK

**Review by psealock — APPROVED** [review]
This is testing well, thanks for all the hard work getting this right @ilyasfoo

**Comment by psealock** [comment]
[This change](https://github.com/woocommerce/woocommerce/pull/42916#pullrequestreview-1789057553) had me thinking its not being done right in free shipping and local pickup either. One reason is `$value` is being changed before saving, but what really needs to happen is the decimal separator swapped out for `.` and the thousandth separator removed only for testing purposes but not for saving the value to the database.

In https://github.com/woocommerce/woocommerce/pull/42916/commits/b6a08cfd212368dc509a61acda7dec697c25e254 I fixed up the validation for free shipping and local pickup.

### Testing instructions addendum

1. Change the settings to different thousandth separator and decimal separator and currency.
2. Add free shipping with a requirement so the cost field shows.
3. Add a local pickup with cost too,
4. Add a flat rate and try using a formula
5. Save all, try entering bad numbers, but ultimately save values with different thousandth separator and decimal separator present in the string.
6. Add a product and go to checkout to make sure all the values are correctly reflected.

image

**Review by chihsuan — APPROVED** [review]
Thanks for the fix! @ilyasfoo @psealock 👍 

LGTM and confirmed the formatting does not break the formula.
