### PR TITLE
Fix/24791

### LINKED ISSUE #24791: WC_Admin_Settings::get_option produce warning when fetching a multidimensional array
**Describe the bug**
Under `WC_Admin_Settings::get_option` a `stripslashes` filter is applied for the returned setting value. See https://github.com/woocommerce/woocommerce/blob/master/includes/admin/class-wc-admin-settings.php#L190

When a **setting value is a multidimensional array** (array of arrays), the use of `array_map` with the `stripslashes` will produce a warning: 
```
PHP Warning:  stripslashes() expects parameter 1 to be string, array given in /srv/www/sites/apfs/wp-content/plugins/woocommerce/includes/admin/class-wc-admin-settings.php on line 190
```

This came to the foreground after the WC 3.7.0 update that pre-fetches the setting value. See https://github.com/woocommerce/woocommerce/blob/master/includes/admin/class-wc-admin-settings.php#L238

**To Reproduce**
N/A

**Expected behavior**
The `array_map` call should use the `stripslashes_deep` instead of the simple `stripslashes`

### PR DESCRIPTION
**Pull request by xristos3490**
### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Replaced the use of `stripslashes` with `stripslashes_deep` when dealing with non-scalar setting values under the `WC_Admin_Settings::get_option` method.

Closes #24791 

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully run tests with your changes locally?

### Changelog entry

> Fix - Use of recursive stripslashes function when escaping admin settings values #24791

### CODE REVIEW

File: includes/admin/class-wc-admin-settings.php [hunk 1]
```diff
@@ -187,7 +187,7 @@ public static function get_option( $option_name, $default = '' ) {
 			}
 
 			if ( is_array( $option_value ) ) {
-				$option_value = array_map( 'stripslashes', $option_value );
+				$option_value = array_map( 'stripslashes_deep', $option_value );
```
Comment (claudiosanches) [inline includes/admin/class-wc-admin-settings.php]: This code can be more clean, like:

```php
$option_value = wp_unslash( $option_value );
```

**Review by claudiosanches — CHANGES_REQUESTED** [review]

File: includes/admin/class-wc-admin-settings.php (hunk 1 above)
Comment (xristos3490) [reply includes/admin/class-wc-admin-settings.php]: Nice catch @claudiosanches

**Review by claudiosanches — APPROVED** [review]
Thanks for your contribution!
