### PR TITLE
Fix variable prod can be added to cart without variations #44868

### LINKED ISSUE #44868: Variable Product Can Be Programmatically Added to Cart and Purchased Without Variation Set
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Possible regression of #28179

You can programmatically (ex. "add_to_cart() function and supply a variable product as product_id and zero as variation_id) add a base/parent variable product to your cart and checkout without a variation being selected.

Found [on Twitter](https://twitter.com/PoeHaH/status/1760357023755936061): 

> If adding a variable product programmatically to the cart without variation ID, WooCommerce adds that base product. Seems illogical? On the product page, you are required to select a variation, so I'd expect WooCommerce to auto-select the first variation programmatically?

Another user [verified it](https://twitter.com/morganhvidt/status/1760255026285715831) in the replies.

### Expected behavior

It is not possible to add a variable product without a variation selected to cart or be able to checkout. 

### Actual behavior

It is possible to programmatically add a variable product without a variation selected to cart and checkout. 

### Steps to reproduce

ex. "add_to_cart() function and supply a variable product as product_id and zero as variation_id

### WordPress Environment

Unavailable.

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by PavloBorysenko**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes #44868  .

Added check for product type. Variable product should not be added to cart without selected variation
eb8ff-clip-29kb

The reason for this behavior:
If $variation_id =0  then the variable product will go into  $product_data
`$product_data = wc_get_product( $variation_id ? $variation_id : $product_id );`

Since this is a variable product it does not pass this condition into the block where there is a check for an empty variation.
`if ( $product_data->is_type( 'variation' ) ) {`

Below in the code there are no conditions that will not allow this product to be added to the cart

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1) Take the id($variable_ID) of any variable product (important! this product must be created earlier, not in the same process where the test function is executed - add_to_cart())

2) Using an extension like [WP Console](https://wordpress.org/plugins/wp-console/), execute functions:
```
WC()->initialize_cart();
WC()->initialize_session();
WC()->cart->empty_cart(); // For a clean test
WC()->cart->add_to_cart($variable_ID,1,0);
```

3) Check the contents of the basket (the product should not be added):
`WC()->cart->get_cart_contents_count()`

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 
Added verification for variable product without a specified variation when programmatically calling add_to_cart()
</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce/includes/class-wc-cart.php [hunk 1]
```diff
@@ -1036,7 +1036,7 @@ public function add_to_cart( $product_id = 0, $quantity = 1, $variation_id = 0,
 			$product_data = wc_get_product( $variation_id ? $variation_id : $product_id );
 			$quantity     = apply_filters( 'woocommerce_add_to_cart_quantity', $quantity, $product_id );
 
-			if ( $quantity <= 0 || ! $product_data || 'trash' === $product_data->get_status() ) {
+			if ( $quantity <= 0 || ! $product_data || 'trash' === $product_data->get_status() || $product_data->is_type( 'variable' ) ) {
```
Comment (wavvves) [inline plugins/woocommerce/includes/class-wc-cart.php]: This would be better off in a separate check, throwing an exception, if indeed, adding a variable item without specifying the variation is an unallowed operation.

Also, it interferes with the Exception thrown in line 1142, which is being caught for user feedback, when submiting two variable product ids.
Eg, the call `/cart/?add-to-cart=<variable_id_1>&variation_id=<variable_id_2>` will stop producing a notice.

I do think the PR is valid, the check done here already exists in other places, for example in `class-wc-form-handler.php`
```php
// Prevent parent variable product from being added to cart.
if ( empty( $variation_id ) && $product && $product->is_type( 'variable' ) ) {
	/* translators: 1: product link, 2: product name */
	wc_add_notice( sprintf( __( 'Please choose product options by visiting <a href="%1$s" title="%2$s">%2$s</a>.', 'woocommerce' ), esc_url( get_permalink( $product_id ) ), esc_html( $product->get_name() ) ), 'error' );

	return false;
}
```

...And I couldn't really find a use case for adding variable products to cart without variation defined, don't think it should use attribute defaults, those are only purposed to pre-select options and display a default item configuration.
image

File: plugins/woocommerce/tests/php/includes/class-wc-cart-test.php [hunk 2]
```diff
@@ -96,6 +96,32 @@ public function test_add_variation_to_the_cart_invalid_variation_id() {
...
+
+		// Add variable and variation_id=0.
+		WC()->cart->add_to_cart(
+			$variable_product->get_id(),
+			1,
+			0
+		);
+
+		// Check for cart contents.
+		$this->assertCount( 0, WC()->cart->get_cart_contents() );
```
Comment (wavvves) [inline plugins/woocommerce/tests/php/includes/class-wc-cart-test.php:117]: We shouldn't rely on other methods to evaluate the integrity of` add_to_cart()` here. If `get_cart_contents()` breaks, this test will fail.

Also, we're just checking for cart item count, if `create_variation_product()` breaks and outputs a random object with `id=0`, the test will pass even if `add_to_cart()` doesn't check for variable products anymore.

In this specific case, this should assert method return values and thrown exceptions.

**Review by wavvves — CHANGES_REQUESTED** [review]
Hi @PavloBorysenko, thank you for your contribution!

I looked around in the codebase, and I found some examples that indeed reinforce that adding a variable product without variation data shouldn't be part of `WC_Cart::add_to_cart()` behaviour, yet I left some notes regarding the introduced check.

File: plugins/woocommerce/tests/php/includes/class-wc-cart-test.php [hunk 3]
```diff
@@ -96,6 +96,32 @@ public function test_add_variation_to_the_cart_invalid_variation_id() {
...
+		$this->assertEquals( 0, WC()->cart->get_cart_contents_count() );
```
Comment (wavvves) [inline plugins/woocommerce/tests/php/includes/class-wc-cart-test.php:118]: Same goes for `get_cart_contents_count()`

**Review by wavvves — CHANGES_REQUESTED** [review]

**Comment by PavloBorysenko** [comment]
Hello @wavvves 
Thank you for your very helpful comments. I fixed the code.
I hope it looks better now.

**Comment by juliaamosova** [comment]
I removed Solaris team from reviewers since we were tagged automatically due to what looks like force push that was used to sync the PR with trunk. That push probably contained some commits that changed _e2e-utils_ code that we own. Please read us if we should look at something gin particular.

File: plugins/woocommerce/tests/php/includes/class-wc-cart-test.php [hunk 4]
```diff
@@ -96,6 +96,39 @@ public function test_add_variation_to_the_cart_invalid_variation_id() {
 		$variable_product->delete( true );
 	}
 
+	/**
+	 * @testdox variable product should not be added to the cart if variation_id=0.
+	 */
+	public function test_add_variation_to_the_cart_zero_variation_id() {
```
Comment (wavvves) [inline plugins/woocommerce/tests/php/includes/class-wc-cart-test.php:102]: > Hello @wavvves Thank you for your very helpful comments. I fixed the code. I hope it looks better now.

We shouldn't rely on `get_cart_contents()` and that was kept, while introducing another dependency on notices. 
To properly scope a unit test to this, we should be trying to add an item without a variation, and checking for thrown error. That would be all we need to check, not quantities or if the error message bubbles up into the notices.

Something similar to:

```php
public function test_add_variation_to_the_cart_zero_variation_id() {
    WC()->cart->empty_cart();

    $variable_product = WC_Helper_Product::create_variation_product();

    $this->expectException(Exception::class);
    $this->expectExceptionMessage(
        sprintf(
            'Please choose product options by visiting <a href="%1$s" title="%2$s">%2$s</a>.',
            esc_url($variable_product->get_permalink()),
            esc_html($variable_product->get_name())
        )
    );

    // Add variable and variation_id=0.
    WC()->cart->add_to_cart(
        $variable_product->get_id(),
        1,
        0
    );
}
```

**Review by wavvves — CHANGES_REQUESTED** [review]
Thanks for addressing the changes @PavloBorysenko
I think there is some confusion on the unit tests, I left a comment with an example of what the scope of the test should be. Let me know if you have any questions :)

File: plugins/woocommerce/tests/php/includes/class-wc-cart-test.php (hunk 4 above)
Comment (PavloBorysenko) [reply plugins/woocommerce/tests/php/includes/class-wc-cart-test.php:102]: Hello @wavvves 

Thanks for the tip, that makes sense. I was thinking about that, but the problem is (maybe I'm wrong) if the code being tested is in a try/catch block, then it's impossible to get an expectException in the test.
bc159-clip-89kb

Because the try/catch block will catch the Exception.

Then in this case I can remove the check for the contents of the cart from the test and only check for the presence of error

```php
public function test_add_variation_to_the_cart_zero_variation_id() {

		WC()->cart->empty_cart();
		WC()->session->set( 'wc_notices', null );

		$variable_product = WC_Helper_Product::create_variation_product();

		// Add variable and variation_id=0.
		WC()->cart->add_to_cart(
			$variable_product->get_id(),
			1,
			0
		);
		$notices = WC()->session->get( 'wc_notices', array() );

		// Check that the notices contain an error message about the product option is not selected.
		$this->assertArrayHasKey( 'error', $notices );
		$this->assertCount( 1, $notices['error'] );
		$expected = sprintf(
			'Please choose product options by visiting <a href="%1$s" title="%2$s">%2$s</a>.',
			esc_url( $variable_product->get_permalink() ),
			esc_html( $variable_product->get_name() )
		);
		$this->assertEquals( $expected, $notices['error'][0]['notice'] );

		// Reset cart.
		WC()->cart->empty_cart();
		$variable_product->delete( true );
	}
```

Comment (wavvves) [reply plugins/woocommerce/tests/php/includes/class-wc-cart-test.php:102]: You are right, I apologize for the mistake that is a huge method and I overlooked the `catch` 😔

Still in that case, it should be expected that we mock `wc_add_notice()` and ensure it is called the right amount of times with the correct message. I believe Mockery is available for this. Otherwise you can probably namespace a mock to ensure it gets called instead of the global function. Also assert that the end return value is false:

```php
public function test_add_variation_to_the_cart_zero_variation_id() {
        WC()->cart->empty_cart();
        $variable_product = WC_Helper_Product::create_variation_product();

        $expected_message = sprintf(
            'Please choose product options by visiting <a href="%1$s" title="%2$s">%2$s</a>.',
            esc_url( $variable_product->get_permalink() ),
            esc_html( $variable_product->get_name() )
        );

        $mock_wc_add_notice = Mockery::mock('alias:wc_add_notice');
        $mock_wc_add_notice
            ->shouldReceive('wc_add_notice')
            ->once()
            ->with($expected_message, 'error');

        $result = WC()->cart->add_to_cart(
            $variable_product->get_id(),
            1,
            0 // variation_id = 0 to trigger the condition
        );

        $this->assertFalse($result, 'Expected add_to_cart to return false when variation ID is 0.');
    }
```

Comment (PavloBorysenko) [reply plugins/woocommerce/tests/php/includes/class-wc-cart-test.php:102]: Hello @wavvves

Maybe I'm wrong but because of the priority of calling functions in PHP Mockery can't mock a function that is not defined in the namespace. For this reason, it is not possible to mock a function if the code (class) being tested is not defined in the namespace.  For this I found third-party libraries like - Patchwork. But I doubt that this is the right way to add a library for one test.   While looking for inspiration I found this great tool -[ FunctionsMockerHack.](https://github.com/PavloBorysenko/woocommerce/tree/trunk/plugins/woocommerce/tests/Tools/CodeHacking)  This tool (it's part of woocommerce) allows me to mock the function with minimal code changes.

```php
	public function test_add_variation_to_the_cart_zero_variation_id() {

		WC()->cart->empty_cart();

		$variable_product = WC_Helper_Product::create_variation_product();
		$expected = sprintf(
			'Please choose product options by visiting <a href="%1$s" title="%2$s">%2$s</a>.',
			esc_url( $variable_product->get_permalink() ),
			esc_html( $variable_product->get_name() )
		);

		FunctionsMockerHack::add_function_mocks(
			array(
				'wc_add_notice' => function ( $message, $type ) {
					echo $message;
				},
			)
		);

		$this->expectOutputString($expected);

		// Add variable and variation_id=0
		$result = WC()->cart->add_to_cart(
			$variable_product->get_id(),
			1,
			0
		);

		$this->assertFalse($result, 'Expected add_to_cart to return false when variation ID is 0.');
	}
```

Comment (wavvves) [reply plugins/woocommerce/tests/php/includes/class-wc-cart-test.php:102]: I don't think that works that way, plus anything extra in the output will likely cause this to break.
I did some poking around, and I think the whole set of tests on that file rely too much on dependencies, and that it is requiring a refactor to make the function more testable, eg. by breaking it apart exposing the thrown errors.
Not to block this anymore, I'm doing a final review now, as is, using the test you provided, and eventually follow up on improving the tests in a separate issue 👍🏼

File: plugins/woocommerce/includes/class-wc-cart.php [hunk 5]
```diff
@@ -1045,6 +1045,12 @@ public function add_to_cart( $product_id = 0, $quantity = 1, $variation_id = 0,
 				return false;
 			}
 
+			// Variable product cannot be added to cart.
```
Comment (wavvves) [inline plugins/woocommerce/includes/class-wc-cart.php]:
```suggestion
			// Variable product cannot be added to cart without a specified variation.
```

File: plugins/woocommerce/tests/php/includes/class-wc-cart-test.php (hunk 4 above)
Comment (PavloBorysenko) [reply plugins/woocommerce/tests/php/includes/class-wc-cart-test.php:102]: Ok! I understand!
about FunctionsMockerHack - I read the documentation of this tool and did all the tests it works (catches exception throwing).  I also checked how this tool is used in other tests. This might not be a bad option in this case. But I completely agree with you, the more correct way is to refactor the add_to_cart function

**Review by wavvves — APPROVED** [review]
Thank you for the contribution and patience @PavloBorysenko 🙂
I left a comment about testing, there's too much in there already to warrant any changes here, it will be looked at on the scope of a new issue.

**Comment by shaunjc** [comment]
Hi team, we've inherited a website that relies on the functionality of being able to add a variable product to a cart without a variation.

In our example, numerous hire products were imported from a third party system that charged separate rates depending on the length of time the product was hired for, where each rate had been imported as a new variation. The cost shown on the product page and in the cart is then dynamically calculated based on the total hire length of the product, so adding a specific variation to the cart wasn't included by the original developers.

At this point, we're unable to update WooCommerce to the latest version as most items on the store cannot be added to the cart with this change. We've been unsuccessful when attempting to create a new product type for these hire products, and adding a random variation ID to the cart also appears to either throw their own errors or break the current price calculations.

There may need to be some form of backwards-compatibility added for those niche providers who rely on this functionality.
