### PR TITLE
Fixes an issue with the 'woocommerce_grant_product_download_access' hook

### LINKED ISSUE #20904: 'woocommerce_grant_product_download_access' hook doesn't work as expected
**Description:**

cc @mattyza @gedex 

WooCommerce throws a fatal error if I attempt to create a new order note when downloadable permissions are granted for a product using the WooCommerce.com admin dashboard.

**Steps to reproduce the behaviour:**

To accomplish this, I hooked a custom function to the `woocommerce_grant_product_download_access` hook on the `woocommerce_init` hook and called wc_create_order_note() inside my custom function. 

When I then grant download permissions to a product, I see this fatal error in debug logs:

```
[26-Jul-2018 08:15:08 UTC] PHP Fatal error:  Uncaught Exception: Invalid download. in /var/www/wordpress/wp-content/plugins/woocommerce/includes/data-stores/class-wc-customer-download-data-store.php:95
Stack trace:
#0 /var/www/wordpress/wp-content/plugins/woocommerce/includes/class-wc-data-store.php(156): WC_Customer_Download_Data_Store->read(Object(WC_Customer_Download))
#1 /var/www/wordpress/wp-content/plugins/woocommerce/includes/class-wc-customer-download.php(66): WC_Data_Store->read(Object(WC_Customer_Download))
#2 /var/www/wordpress/wp-content/plugins/woocommerce/includes/class-wc-ajax.php(769): WC_Customer_Download->__construct(4243305)
#3 /var/www/wordpress/wp-includes/class-wp-hook.php(286): WC_AJAX::grant_access_to_download('')
#4 /var/www/wordpress/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array)
#5 /var/www/wordpress/wp-includes/plugin.php(453): WP_Hook->do_action(Array)
#6 /var/www/wordpress/wp-admin/admin-ajax.php(97): do_action('wp_ajax_woocomm...')
#7 {main}
  thrown in /var/www/wordpress/wp-content/plugins/woocommerce/includes/data-stores/class-wc-customer-download-data-store.php on line 95
[26-Jul-2018 08:15:08 UTC] PHP Notice:  [wccom-logger critical fatal-errors]: Array
(
    [current_user] => 1
    [log] => Uncaught Exception: Invalid download. in /var/www/wordpress/wp-content/plugins/woocommerce/includes/data-stores/class-wc-customer-download-data-store.php:95
Stack trace:
#0 /var/www/wordpress/wp-content/plugins/woocommerce/includes/class-wc-data-store.php(156): WC_Customer_Download_Data_Store->read(Object(WC_Customer_Download))
#1 /var/www/wordpress/wp-content/plugins/woocommerce/includes/class-wc-customer-download.php(66): WC_Data_Store->read(Object(WC_Customer_Download))
#2 /var/www/wordpress/wp-content/plugins/woocommerce/includes/class-wc-ajax.php(769): WC_Customer_Download->__construct(4243305)
#3 /var/www/wordpress/wp-includes/class-wp-hook.php(286): WC_AJAX::grant_access_to_download('')
#4 /var/www/wordpress/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array)
#5 /var/www/wordpress/wp-includes/plugin.php(453): WP_Hook->do_action(Array)
#6 /var/www/wordpress/wp-admin/admin-ajax.php(97): do_action('wp_ajax in /var/www/wordpress/wp-content/plugins/wccom-plugins/logger/includes/class-logger.php on line 47
```

**Expected behavior**

I should be able to add an order note using `wc_create_order_note` when downloadable permissions are granted for a product.

**Possible fix**

I'm not sure what the root cause of the issue is but moving the following line:

`do_action( 'woocommerce_grant_product_download_access', $data );`

to the bottom of the `create()` function in the `WC_Customer_Download_Data_Store` class fixed it for me.

PR: #20905 

**WordPress Environment**
```
Home URL: https://woocommerce.test
Site URL: https://woocommerce.test
WC Version: 3.4.0
Log Directory Writable: ✔
WP Version: ❌ 4.9.4 - There is a newer version of WordPress available (4.9.7)
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –
```

### PR DESCRIPTION
**Pull request by kanishkdudeja**
Fixes #20904 

cc @mattyza @gedex 

### Changes proposed in this Pull Request:

This PR just moves the following line:

`do_action( 'woocommerce_grant_product_download_access', $data );`

to the bottom of the `create()` function in the `WC_Customer_Download_Data_Store` class.

### How to test the changes in this Pull Request:

Provided in #20904 

### Changelog entry

> Fixes an issue with the `woocommerce_grant_product_download_access` hook

### CODE REVIEW

File: includes/data-stores/class-wc-customer-download-data-store.php [hunk 1]
```diff
@@ -61,12 +61,12 @@ public function create( &$download ) {
...
 		);
 
-		do_action( 'woocommerce_grant_product_download_access', $data );
-
 		if ( $result ) {
 			$download->set_id( $wpdb->insert_id );
 			$download->apply_changes();
 		}
+
+		do_action( 'woocommerce_grant_product_download_access', $data );
```
Comment (gedex) [inline includes/data-stores/class-wc-customer-download-data-store.php]: it seems the fatal error you got is caused by download ID not being set properly at that time.

The hook should be inside the `if ( $result )`. Otherwise you'd get fatal error again if `$wpdb->insert` is failed.

Comment (kanishkdudeja) [reply includes/data-stores/class-wc-customer-download-data-store.php]: Yes. Looks like so.

Let's wait for someone to confirm this though. Maybe, the issue gets triggered specifically due to some custom code in our WooCommerce installation.

Comment (kloon) [reply includes/data-stores/class-wc-customer-download-data-store.php]: Mind sharing details on how you are hooking into this and the code you are running?

Comment (kanishkdudeja) [reply includes/data-stores/class-wc-customer-download-data-store.php]: Hello,

You should be able to see the code here: https://github.com/Automattic/woocommerce.com/pull/4662

**Review by claudiulodro — APPROVED** [review]
See https://github.com/woocommerce/woocommerce/issues/20904#issuecomment-409321135. This solution should work and looks good to me. Great find.

**Comment by kanishkdudeja** [comment]
Thank you.

**Comment by kanishkdudeja** [comment]
@mattyza We need this change pulled in WooCommerce.com before we can merge https://github.com/Automattic/woocommerce.com/pull/4662

Since updating WooCommerce core will require a significant amount of testing, should we manually change this in the WooCommerce core file for now (in the repository) ?
