### PR TITLE
WC_Geolocation::geolocate_ip() doesn't use fallback if MaxMind integration is disabled.

### LINKED ISSUE #44410: WC_Geolocation::geolocate_ip() doesn't use fallback if MaxMind integration is disabled.
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

If the MaxMind integration is disabled by removing it from the `woocommerce_integrations`, `WC_Geolocation::geolocate_ip()` will no longer use the api or external fallback handling even if `$fallback` or `$api_fallback` is set to true. 

This stems from f9c31589c618, where the checks against the $country_code were made to use an empty string instead of false.  However, the default value passed into the `woocommerce_geolocate_ip` filter was not updated from `false` to `''`.

Once the MaxMind integration is disabled, it is no longer filtering `woocommerce_get_geolocation` to set `$geolocation['country'] => ''` and it remains as `false` for the following lines:

https://github.com/woocommerce/woocommerce/blob/1bfe2761049cbee57ba6dda2d6a587450a250a6d/plugins/woocommerce/includes/class-wc-geolocation.php#L181-L194

### Expected behavior

If a country code has not yet been set, the fallbacks should be used if the parameters specify.

### Actual behavior

The fallbacks are skipped regardless of the parameter value for using the fallbacks.

### Steps to reproduce

Use the following to disable the MaxMind integration:

```php
add_filter( 'woocommerce_integrations', function( array $load_integrations ) {
	$load_integrations = array_diff( $load_integrations, [ 'WC_Integration_MaxMind_Geolocation' ] );

	return $load_integrations;
}
```

### WordPress Environment

WPCOM

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by devanshijoshi9**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

- Change country code default from false to empty string in woocommerce_geolocate_ip hook

Closes #44410.

### How to test the changes in this Pull Request:

Use the following to disable the MaxMind integration:

```php
add_filter( 'woocommerce_integrations', function( array $load_integrations ) {
	$load_integrations = array_diff( $load_integrations, [ 'WC_Integration_MaxMind_Geolocation' ] );

	return $load_integrations;
}
``` 

### Milestone

- [ ] Automatically assign milestone for the **[next WooCommerce version](../blob/trunk/plugins/woocommerce/woocommerce.php#L6)**

> **Note:** Check the box above to have the milestone automatically assigned when merged.
> Alternatively (e.g. for point releases), manually assign the appropriate milestone.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce/includes/class-wc-geolocation.php [hunk 1]
```diff
@@ -158,9 +158,9 @@ public static function geolocate_ip( $ip_address = '', $fallback = false, $api_f
 		 * @param bool $api_fallback If true, uses geolocation APIs if the database file doesn't exist (can be slower).
 		 * @return string
 		 */
-		$country_code = apply_filters( 'woocommerce_geolocate_ip', false, $ip_address, $fallback, $api_fallback );
+		$country_code = apply_filters( 'woocommerce_geolocate_ip', '', $ip_address, $fallback, $api_fallback );
```
Comment (prettyboymp) [inline plugins/woocommerce/includes/class-wc-geolocation.php]: This changes the signature of the filter which breaks backward compatibility.  Any existing plugins that expect `false` or return `false` expecting certain behavior will no longer work the same.

**Review by prettyboymp — CHANGES_REQUESTED** [review]
Hi @devanshijoshi9, 

Thanks for working on this fix! The changes you made would work, but there are backward compatibility concerns with changing the parameter of the `woocommerce_geolocate_ip` filter. 

I did some more digging into what caused this bug and found that the type mismatch was introduced when PR #31394 moved `get_country_code_from_headers()` inside a conditional, creating a code path where `$country_code` remains `false` instead of being replaced by a string.

### Suggested Change

Rather than changing the filter's default value (which changes its public API), the fix should coerce the value at the point where it's assigned to the `$geolocation` array. This matches the pattern already used in `WC_Integration_MaxMind_Geolocation::get_geolocation()`:

```diff
  $geolocation = apply_filters(
      'woocommerce_get_geolocation',
      array(
-         'country'  => $country_code,
+         'country'  => $country_code ? $country_code : '',
          'state'    => '',
          'city'     => '',
          'postcode' => '',
      ),
      $ip_address
  );
```

File: plugins/woocommerce/includes/class-wc-geolocation.php (hunk 1 above)
Comment (devanshijoshi9) [reply plugins/woocommerce/includes/class-wc-geolocation.php]: I agree! I have reverted the code to use false as default value. Thanks

File: plugins/woocommerce/includes/class-wc-geolocation.php [hunk 2]
```diff
@@ -160,7 +160,7 @@ public static function geolocate_ip( $ip_address = '', $fallback = false, $api_f
 		 */
 		$country_code = apply_filters( 'woocommerce_geolocate_ip', false, $ip_address, $fallback, $api_fallback );
 
-		if ( false !== $country_code ) {
+		if ( '' !== $country_code ) {
```
Comment (prettyboymp) [inline plugins/woocommerce/includes/class-wc-geolocation.php]: This change isn't needed.  We still need to check against `false` here.

**Review by prettyboymp — CHANGES_REQUESTED** [review]

**Review by prettyboymp — APPROVED** [review]
@devanshijoshi9 Thanks for the fix!
