### PR TITLE
Fix mobile unresponsiveness of product gallery after ‘Reviews’ tab click

### LINKED ISSUE #57292: Product Image Slide Becomes Unresponsive on Mobile After First Click on ‘Reviews’ Tab
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

On mobile devices, the product image slide function (e.g., clicking to switch images) stops working after the first click on the ‘Reviews’ tab in the product details section. This doesn’t affect the entire gallery — just the ability to switch or slide through images by tapping them.

### Expected behavior

Gallery image sliding should remain functional after clicking the Reviews tab, without requiring an extra click outside.

### Actual behavior

After the first tap on the Reviews tab, image sliding becomes stuck — tap events on the gallery don’t respond unless the user first taps elsewhere.

### Steps to reproduce

1. Open a single product page on a mobile device or in browser mobile view.
2. Tap the ‘Description’ tab (or any other tab except Reviews).
3. Then tap the ‘Reviews’ tab.
4. Try tapping a gallery image to slide or switch — nothing happens.
5. Tap outside the gallery area (e.g., another tab or blank space).
6. Try the gallery again — now the slide interaction works.

### WordPress Environment

<details><summary>System Status Report</summary>

```
### WordPress Environment ###

WordPress address (URL): [Redacted]
Site address (URL): [Redacted]
WC Version: 9.8.1
Legacy REST API Package Version: The Legacy REST API plugin is not installed on this site.
Action Scheduler Version: ✔ 3.9.2
Log Directory Writable: ✔
WP Version: 6.8
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 8.1.32
PHP Post Max Size: 2 GB
PHP Time Limit: 850
PHP Max Input Vars: 6144
cURL Version: 8.12.1
OpenSSL/3.0.15

SUHOSIN Installed: –
MySQL Version: 10.11.10-MariaDB-log
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

[REDACTED]

### Post Type Counts ###

attachment: 26
customize_changeset: 1
custom_css: 1
elementor_library: 1
nav_menu_item: 6
page: 9
post: 1
product: 20
product_variation: 47
revision: 27
shop_coupon: 6
shop_order: 21
wpcode: 4
wp_font_face: 36
wp_font_family: 12
wp_global_styles: 5
wp_navigation: 1
wp_template: 1
wp_template_part: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 9.8.1

### Inactive Plugins (3) ###

Akismet Anti-spam: Spam Protection: by Automattic - Anti-spam Team – 5.3.7
Jetpack: by Automattic – 14.6-a.3
WP Mail Logging: by WP Mail Logging Team – 1.14.0

### Dropin Plugins () ###

advanced-cache.php: advanced-cache.php
object-cache.php: Memcached

### Settings ###

Legacy API Enabled: –
Force SSL: –
Currency: CAD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: ✔

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 1 MB

### WC Pages ###

Shop base: #5 - /shop/
Cart: #6 - /cart/ -  Contains the woocommerce/cart block
Checkout: #7 - /checkout/ -  Contains the woocommerce/checkout block
My account: #8 - /my-account/ -  Contains the [woocommerce_my_account] shortcode
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty-Five
Version: 1.1 (update to version 1.2 is available)
Author URL: https://wordpress.org
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
Theme type: Block theme
WooCommerce Support: ❌ Not declared

### Templates ###

Overrides: /srv/htdocs/wp-content/plugins/woocommerce/templates/block-notices/error.php
/srv/htdocs/wp-content/plugins/woocommerce/templates/block-notices/notice.php
/srv/htdocs/wp-content/plugins/woocommerce/templates/block-notices/success.php


### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
onboarding
onboarding-tasks
pattern-toolkit-full-composability
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
printful
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page
launch-your-store
add-to-cart-with-options-stepper-layout

Disabled Features: product-data-views
experimental-blocks
coming-soon-newsletter-template
minified-js
product-pre-publish-modal
settings
async-product-editor-category-field
product-editor-template-system
use-wp-horizon
blockified-add-to-cart

Daily Cron: ✔ Next scheduled: 2025-04-16 11:48:27 +00:00
Options: ✔
Notes: 75
Onboarding: skipped

### Action Scheduler ###

Complete: 330
Oldest: 2025-03-18 01:23:01 +0000
Newest: 2025-04-16 03:40:58 +0000

Failed: 32
Oldest: 2024-12-14 03:27:10 +0000
Newest: 2025-04-16 03:40:58 +0000

Pending: 3
Oldest: 2025-04-16 04:21:04 +0000
Newest: 2025-04-16 04:56:50 +0000


### Status report information ###

Generated at: 2025-04-16 03:42:43 +00:00
```
</details>

### Isolating the problem

- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by gigitux**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

This PR addresses a regression introduced in [#53158](https://github.com/woocommerce/woocommerce/pull/53158), where, in mobile view, the touch event on the description and reviews tabs sets the animation to `true` without resetting it. This prevents the animation logic in [jquery.flexslider.js](https://github.com/woocommerce/woocommerce/blob/f3eac49e1d8bd39fbfde10bc9a037e5131a27775/plugins/woocommerce/client/legacy/js/flexslider/jquery.flexslider.js#L619-L724) from executing, causing the animation to fail.

Additionally, this PR resolves the issue noted in [#53018](https://github.com/woocommerce/woocommerce/pull/53018#issuecomment-2498921373). After investigation, the following fixes were implemented:

- Use the `keyup` event, consistent with [FlexSlider's implementation](https://github.com/woocommerce/woocommerce/blob/297c33addb4d0e7faa9e4e4b1fd2400c2c84b2b8/plugins/woocommerce/client/legacy/js/flexslider/jquery.flexslider.js#L140-L154), to handle keyboard interactions.
- Now, that the same event is used, prevent event bubbling to the gallery via `stopPropagation`, ensuring that keyboard updates to the stars do not trigger unintended gallery behavior.

Given that there is a back and forth with these changes, I created E2E tests to covere these scenario.

These changes fix the regression and ensure proper behavior for both touch and keyboard interactions.

I'm going to see how we can fix it, but sharing in case you have a better idea to avoid setting animating to true.

Closes #57292 (WOOPLUG-3943) .

(For Bug Fixes) Bug introduced in PR #53158 .

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Visit a product that has multiple images.
2. Click on the reviews tab.
3. Click on stars.
4. Update stars via directional keys
5. Ensure that the stars are updated.
6. Ensure that the active image isn't updated.
7. Click on the Reviews tab
8. Move across tabs via directional keys.
9. Ensure that the focused tab is updated.
10. Ensure that the active image isn't updated.
11. Visit a product that has multiple images in browser mobile view.
12. Tap the ‘Description’ tab (or any other tab except Reviews).
13. Then tap the ‘Reviews’ tab.
14. Try tapping a gallery image to slide or switch.
15. Ensure that the active image is updated.

## Run test

1. Run `plugins/woocommerce/client/blocks/tests/e2e/tests/product-image-gallery/product-image-gallery.block_theme.spec.ts` E2E tests against trunk.
2. See that the second test fail
3. Run `plugins/woocommerce/client/blocks/tests/e2e/tests/product-image-gallery/product-image-gallery.block_theme.spec.ts` E2E tests against this branch.
4. See that all tests pass

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [x] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

Fix mobile unresponsiveness of product gallery after ‘Reviews’ tab click.

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

**Comment by gigitux** [comment]
@kmanijak I added you as a reviewer since you might have more context, having reviewed the previous implementation.

File: plugins/woocommerce/client/legacy/js/frontend/single-product.js [hunk 1]
```diff
@@ -78,19 +78,6 @@ jQuery( function( $ ) {
...
-				var $closestBlocker = $activeElement.closest( sliderKeyupBlockers.join( ', ' ) );
-		
-				if ( $closestBlocker.length ) {
-					// Prevent keyup events from being triggered on the flexslider when the focus is on the stars or tabs.
-					productGalleryElement.data('flexslider').animating = true;
-					return;
-				}
-		
-				productGalleryElement.data('flexslider').animating = false;
-			}, 0);
```
Comment (Manussakis) [inline plugins/woocommerce/client/legacy/js/frontend/single-product.js:93]: @gigitux By removing this piece of code, the gallery keeps sliding even if the user uses the keyboard to navigate through the tabs.
I explained more about my findings in [this comment](https://github.com/woocommerce/woocommerce/pull/53158/files#r2049331268).

**Review by Manussakis — CHANGES_REQUESTED** [review]

**Comment by Manussakis** [comment]
@gigitux 
I have created this [Draft PR as a POC](https://github.com/woocommerce/woocommerce/pull/57377/files) just for you to see the changes that can fix this issue, according to my tests.

cc: @vikrampm1

File: plugins/woocommerce/client/legacy/js/frontend/single-product.js (hunk 1 above)
Comment (kmanijak) [reply plugins/woocommerce/client/legacy/js/frontend/single-product.js:93]: I could reproduce this issue @Manussakis raised (and similar related to stars vs images) but ONLY on mobile view where there's no keyboard and arrows to control the UI. I couldn't reproduce the issue on desktop view hence I think it's acceptable 🤔

**Review by kmanijak — COMMENTED** [review]
I tested the solution on mobile and desktop view.

I could reproduce issue raised by @Manussakis in the inline comment but I think it's acceptable as we're talking about issue related to keyboard usage but only on mobile view. I'm not approving yet to hear @Manussakis's view on that though.

**Comment by gigitux** [comment]
With 8214e0ea957242195de9e1fd40589f2ad458f45c I fixed the behavior reported by @Manussakis https://github.com/woocommerce/woocommerce/pull/57373#discussion_r2049404386:

| Before | After |
|--------|--------|
| <video src="https://github.com/user-attachments/assets/93e8152e-cf21-4182-bea9-a9ffba50c923" /> | <video src="https://github.com/user-attachments/assets/bf6c3d90-6df7-449d-bd12-194dc969e70f" /> | 

@Manussakis if you agree with this approach, I will do another E2E test to cover this scenario as well (great catch - thanks). Also, I think that we could remove this check as well:

https://github.com/woocommerce/woocommerce/blob/1ad283404703f4a78bde9e686563cadf46f21a85/plugins/woocommerce/client/legacy/js/frontend/single-product.js#L76-L81

File: plugins/woocommerce/client/legacy/js/frontend/single-product.js [hunk 2]
```diff
@@ -152,7 +139,11 @@ jQuery( function( $ ) {
 				return false;
 			}
 		} )
-		.on( 'keydown', '#respond p.stars a', function( e ) {
+		/**
+		 * Handle keyup events for tabs, tabs li a, and respond p.stars a.
+		 * The stopPropagation is used to prevent the keyup event from being triggered on the flexslider.
+		 */
+		.on( 'keyup', '.wc-tabs li a, ul.tabs li a,#respond p.stars a', function( e ) {
```
Comment (Manussakis) [inline plugins/woocommerce/client/legacy/js/frontend/single-product.js]:
```suggestion
		.on( 'keyup', '.wc-tabs li a, ul.tabs li a, #respond p.stars a', function( e ) {
```

**Review by Manussakis — APPROVED** [review]
Thanks for fixing that 🚀 
I left only one suggestion.

**Comment by gigitux** [comment]
Thanks for the @Manussakis for the review 🙇 I updated the selector and removed the not necessary code via 1ff8baffa689af27fd9bbdfb97fe302d612c65fa. Also, I added another E2E test with b5f4f5f3bcd40a0f5534d83d62eb47d5ada502b0.


To merge this PR, I need an approval from a reviewer with write access - @kmanijak, if you agree with this approach, could you approve the PR? Thanks 🙇

File: plugins/woocommerce/client/blocks/tests/e2e/tests/product-image-gallery/product-image-gallery.block_theme.spec.ts [hunk 3]
```diff
@@ -0,0 +1,92 @@
...
+
+		const newActiveImage = page.locator( '.flex-active' );
+
+		await expect( newActiveImage ).toHaveAttribute(
+			'src',
+			activeImageSrc as string
+		);
+	} );
+
+	test( 'should switch to the next image when the user cursor is focused on tabs', async ( {
```
Comment (kmanijak) [inline plugins/woocommerce/client/blocks/tests/e2e/tests/product-image-gallery/product-image-gallery.block_theme.spec.ts]: I think there's leftover here from copying:

```suggestion
	test( 'should switch to the next image when the user cursor is focused on thumbnails', async ( {
```

**Review by kmanijak — APPROVED** [review]
I confirm each of the elements can be navigated with arrows separately when focused:
- images
- tabs
- stars

On mobile as well and changing tabs doesn't trigger changing images ✅ 

I left minor comment but preapproving!

File: plugins/woocommerce/client/blocks/tests/e2e/tests/product-image-gallery/product-image-gallery.block_theme.spec.ts (hunk 3 above)
Comment (gigitux) [reply plugins/woocommerce/client/blocks/tests/e2e/tests/product-image-gallery/product-image-gallery.block_theme.spec.ts]: I clarified the test descriptions:

- **First two tests**: Ensure that the image switch is **not** triggered via keyboard input when the focus is on the tabs or stars.
- **Last test**: Ensure that the image **is** switched when a tab is focused and the user uses a **touch** event to trigger the change.

I hope that it makes sense!
