### PR TITLE
Interactivity API powered MiniCart - Move MiniCart overlay to the `body`

### LINKED ISSUE #60357: Text not visible in the iAPI Mini-Cart if the header text is light
## **Describe the bug**

When the header has light text (usually with a dark background), the Mini-Cart contents aren't visible in the Interactivity API based Mini-Cart.

## **To Reproduce**

1. Go to *WooCommerce* > *Settings* > *Advanced* > *Features* and enable the *Interactivity API powered Mini Cart*.
2. Go to *Appearance* > *Editor* and edit any template.
3. Change the styles of the header so it has dark background and light text.

3. Now go to the front end.
4. Open the Mini-Cart.
5. Notice the text is not visible:

| Current Mini-Cart | iAPI-based Mini-Cart |
| -- | -- |
|  |  |

## **Expected behavior**

Styles shouldn't have changed when migrating from the React-based Mini-Cart to the iAPI-based Mini-Cart.

### PR DESCRIPTION
**Pull request by SantosGuillamot**
### Changes proposed in this Pull Request:

I'm moving the iAPI powered minicart overlay to the `body` instead of having it inside the minicart block markup. This is how it is working right now, which makes sense and prevent styling issues.

Closes #60357 .

### Screenshots or screen recordings:

| Before | After |
| ------ | ----- |
|  Screenshot 2025-08-19 at 13 25 26  |   Screenshot 2025-08-19 at 13 23 18 |

### How to test the changes in this Pull Request:

1. Go to *WooCommerce* > *Settings* > *Advanced* > *Features* and enable the *Interactivity API powered Mini Cart*.
2. Go to *Appearance* > *Editor* and edit any template.
3. Change the styles of the header so it has dark background and light text.
3. Now go to the front end.
4. Open the Mini-Cart.
5. Notice the text is visible.
6. Check the minicart is working as expected.

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary></summary>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message Move iAPI mini-cart overlay to the `body`

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce/src/Blocks/BlockTypes/MiniCart.php [hunk 1]
```diff
@@ -553,7 +554,6 @@ protected function render_experimental_iapi_mini_cart( $attributes, $content, $b
 			);
 
 			$context = array(
-				'isOpen'                       => false,
 				'productCountVisibility'       => $product_count_visibility,
 				'displayCartPriceIncludingTax' => $display_cart_price_including_tax,
 			);
```
Comment (SantosGuillamot) [inline plugins/woocommerce/src/Blocks/BlockTypes/MiniCart.php:559]: Right now, I think we are not using these other properties in the overlay, but I wonder if we should move them to the state anyways.

File: plugins/woocommerce/src/Blocks/BlockTypes/MiniCart.php [hunk 2]
```diff
@@ -575,6 +575,46 @@ protected function render_experimental_iapi_mini_cart( $attributes, $content, $b
...
+										echo $template_part_contents;
+									?>
+								</div>
+							</div>
+						</div>
+					</div>				
+
+					<?php
+					// phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped
+					echo wp_interactivity_process_directives( ob_get_clean() );
```
Comment (SantosGuillamot) [inline plugins/woocommerce/src/Blocks/BlockTypes/MiniCart.php]: As it is using the HTML API, I assume it is already safe, right?

Comment (Aljullu) [reply plugins/woocommerce/src/Blocks/BlockTypes/MiniCart.php]: This is printing the template part contents, so I assume we can trust it.

**Review by Aljullu — APPROVED** [review]
Thanks for picking this up, @SantosGuillamot! Confirming this fixes the issue for me.

Before | After
--- | ---
imatge | imatge

I think the suggestion made by CodeRabbit is a good one. Right now, if I create a page with the Mini-Cart block while it's also in the header, trying to open it in the frontend causes two overlays to open at the same time.

Besides that, everything looks good to me, so approving from my side.

<details>
<summary>Testing environment</summary>

* WordPress 6.8.2 local dev environment
* Plugins: -
* Theme: TT5
* Store creation: June 2025
* Store size: small
* Browser: Firefox
</details>
