### PR TITLE
[WOOPLUG-6354] Fix fulfillment email subject plural form for multiple items

### LINKED ISSUE #63468: [Order Fulfillments] Email subject line doesn't use correct plural form for multiple items
## Bug Report

**Source:** [GitHub Discussion #60922 — EdithAllison (Sep 23, 2025)](<https://github.com/woocommerce/woocommerce/discussions/60922>)

**Description:**<br>When a fulfillment notification email is sent for a shipment containing multiple items, the email subject line still reads "An item" instead of using the correct plural form (e.g., "Items" or "X items"). This creates a confusing customer experience.

**Expected behavior:**<br>Email subject lines should correctly reflect singular vs. plural when a fulfillment contains one item vs. multiple items.

**Steps to reproduce:**

1. Create an order with multiple items.
2. Create a fulfillment with 2+ items.
3. Mark as Fulfilled with customer notification enabled.
4. Check the email subject line — it still says "An item" regardless of quantity.

### PR DESCRIPTION
**Pull request by tpaksu**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

When a fulfillment notification email is sent for a shipment containing multiple items, the email subject line incorrectly reads "An item from {site_title} order {order_number} has been fulfilled!" and the heading reads "Your item is on the way!" regardless of the item count.

This PR updates the `WC_Email_Customer_Fulfillment_Created` class to dynamically choose between singular and plural forms based on the number of items in the fulfillment:

- **1 item (singular):** "An item from {site_title} order {order_number} has been fulfilled!" / "Your item is on the way!"
- **2+ items (plural):** "Items from {site_title} order {order_number} have been fulfilled!" / "Your items are on the way!"

Closes https://github.com/woocommerce/woocommerce/issues/63468.

### Screenshots or screen recordings:

| Before | After |
| ------ | ----- |
|        |       |

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://developer.woocommerce.com/docs/contribution/testing/writing-high-quality-testing-instructions/), include your detailed testing instructions:

1. Create an order with multiple line items (e.g. 2 or more different products).
2. Create a fulfillment for that order containing 2+ items.
3. Mark the fulfillment as Fulfilled with customer notification enabled.
4. Check the email subject line: it should now say "Items from {site_title} order {order_number} have been fulfilled!" and the heading should say "Your items are on the way!"
5. Repeat with a fulfillment containing only 1 item: the subject should say "An item from..." and heading "Your item is on the way!"

### Testing that has already taken place:

- 6 unit tests covering singular, plural, and no-fulfillment-set cases for both subject and heading. All pass.
- PHPStan analysis passes with no errors.
- PHP linting passes.

### Milestone

- [x] Automatically assign milestone for the **[next WooCommerce version](../blob/trunk/plugins/woocommerce/woocommerce.php#L6)**

> **Note:** Check the box above to have the milestone automatically assigned when merged.
> Alternatively (e.g. for point releases), manually assign the appropriate milestone.

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

Fix fulfillment created email subject and heading to use correct plural form when shipment contains multiple items.

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce/includes/emails/class-wc-email-customer-fulfillment-created.php [hunk 1]
```diff
@@ -86,23 +86,41 @@ public function trigger( $order_id, $fulfillment, $order = false ) {
...
 		}
 
+		/**
+		 * Get the number of items in the fulfillment.
+		 *
+		 * @since 10.7.0
+		 * @return int
+		 */
+		private function get_fulfillment_item_count() {
+			return $this->fulfillment ? count( $this->fulfillment->get_items() ) : 1;
```
Comment (ayushpahwa) [inline plugins/woocommerce/includes/emails/class-wc-email-customer-fulfillment-created.php]: I think we should be counting the qty for each item rather than just the number of unique items. For eg. if I purchased 2 qty of one item, this will still count it as a single item.

Comment (ayushpahwa) [reply plugins/woocommerce/includes/emails/class-wc-email-customer-fulfillment-created.php]: I remember seeing a similar function in the other pr i was reviewing #60205. That one seems to be the correct logic.

Image

Comment (ayushpahwa) [reply plugins/woocommerce/includes/emails/class-wc-email-customer-fulfillment-created.php]: Would be good to add tests for the fixed version too. One unique item with multiple qty.

**Review by ayushpahwa — COMMENTED** [review]
I left a comment about multiple qty of a single unique item are not being handled by the code. Sharing the screenshot from the manual testing. Please take a look. Thanks!
Image

File: plugins/woocommerce/includes/emails/class-wc-email-customer-fulfillment-created.php (hunk 1 above)
Comment (tpaksu) [reply plugins/woocommerce/includes/emails/class-wc-email-customer-fulfillment-created.php]: I think I've added the correct count logic to another PR (using `array_reduce` with summing quantities), but didn't merge it yet, thought Claude also got this right. My bad. Also added two new tests for the subject and body on [0a6e33c](https://github.com/woocommerce/woocommerce/pull/63765/commits/0a6e33c3d2c27bab08978f29b9f02a8f796b9191).

Comment (tpaksu) [reply plugins/woocommerce/includes/emails/class-wc-email-customer-fulfillment-created.php]: Thanks for catching this btw!

**Review by ayushpahwa — APPROVED** [review]
Changes look good and the testing instructions work as expected. Thanks for adding the tests too! One minor thing outside of the scope of the PR but still close is the copy of the body text in the email. 

Image

The sentence doesn't seem grammatically correct and we can change it to something like

` "You can access more details of your order by visiting My Account > Orders and selecting the order you wish to see the latest delivery status for."`

In any case, this is not the scope of the PR so feel free to take it up later. Thanks!

File: plugins/woocommerce/includes/emails/class-wc-email-customer-fulfillment-created.php (hunk 1 above)
Comment (ayushpahwa) [reply plugins/woocommerce/includes/emails/class-wc-email-customer-fulfillment-created.php]: Thanks for fixing this. I guess you would now need to manage the merge b/w the 2 PRs.
