### PR TITLE
CYS: fix flickering effect

### LINKED ISSUE #48728: CYS: Pop-up effect opt-in tracking section notice
When the user has the tracking enabled and clicks on "Design your homepage", there is a pop-up effect opt-in tracking section notice 

<video src="https://github.com/woocommerce/woocommerce/assets/4463174/2d513c75-2edd-4d36-a14d-2dd9a6dd8873" />

### PR DESCRIPTION
**Pull request by gigitux**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes #48728.

| Before | After |
|--------|--------|
| <video src="https://github.com/woocommerce/woocommerce/assets/4463174/8743acf2-5e45-4d3e-8358-742ee5aedc38" />|<video src="https://github.com/woocommerce/woocommerce/assets/4463174/76499b46-53c7-4889-9c31-5492848d9254" /> | 

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Ensure that you have the last version of Gutenberg enabled.
2. Make sure you have the WooCommerce beta tester plugin installed.
3. Head over to Tools > WCA Test Helper > Features.
4. Make sure you see the `pattern-toolkit-full-composability` on the list.
5. Enable it.
6. Visit `wp-admin/admin.php?page=wc-settings&tab=advanced&section=woocommerce_com`
7. Ensure that the tracking is disabled.
8. Head over to WooCommerce > Home > Customize your store.
9. Click on Start designing.
10. Click on "Choose your homepage".
11. Ensure that the `WANT MORE PATTERNS?` section is visible.
12. Visit `wp-admin/admin.php?page=wc-settings&tab=advanced&section=woocommerce_com`
13. Enable the tracking.
14. Head over to WooCommerce > Home > Customize your store.
15. Click on "Choose your homepage".
16.  Ensure that the `WANT MORE PATTERNS?` section is not visible.

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [x] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

CYS: fix flickering effect.

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce-admin/client/customize-store/assembler-hub/sidebar/sidebar-navigation-screen-homepage.tsx [hunk 1]
```diff
@@ -223,10 +223,8 @@ export const SidebarNavigationScreenHomepage = ( {
 
 	const isNetworkOffline = useNetworkStatus();
 	const isPTKPatternsAPIAvailable = context.isPTKPatternsAPIAvailable;
-	const trackingAllowed = useSelect( ( sel ) =>
-		sel( OPTIONS_STORE_NAME ).getOption( 'woocommerce_allow_tracking' )
-	);
-	const isTrackingDisallowed = trackingAllowed === 'no' || ! trackingAllowed;
+
+	const isTrackingAllowed = useTrackingAllowed();
```
Comment (samueljseay) [inline plugins/woocommerce-admin/client/customize-store/assembler-hub/sidebar/sidebar-navigation-screen-homepage.tsx]: It's really a minor complaint/nitpick, but I don't think you should trick the consumer of the API into thinking this is a hook when it's not. E.g. you'd be inclined to think it follows or must implement the rules of hooks when it's just a plain function.

Also because of that the variable is not really needed, you can just call your function in the else (thats another nitpick :D )

Comment (gigitux) [reply plugins/woocommerce-admin/client/customize-store/assembler-hub/sidebar/sidebar-navigation-screen-homepage.tsx]: 💯 agree! Thanks for pointing this out! Fixed with [00f9f8e](https://github.com/woocommerce/woocommerce/pull/48767/commits/00f9f8e426f743d5b2d44295ba385c85ef892fd0)

**Review by samueljseay — APPROVED** [review]
Tests well and the code looks good :) 🚢
