### PR TITLE
Make compound rates stack

### LINKED ISSUE #18571: Compound Tax Calculation Issue with 3+ Tax Rates
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Setup 3 compounded tax rates.

Example here: 
http://cld.wthms.co/Me3kzt

2. Check out product

3. Price/compound tax rates are calculated incorrectly:

http://cld.wthms.co/SlNZoR

## Expected/actual behavior

When I follow those steps, the first two tax rates are correct, but the last compounded tax rate (named `I.V.A.` in the screenshot) should be `151,30`, not `145, 48`.

The calculation breakdown should be as follows:

1. 575 x 15% = 86.25 
2. 575 + 86.25 = 661,25 
3. 661,25 x 4% = 26,45 
4. 661,25 + 26.45 = 687.,70 
5. 687,70 x 22% = 151,30 
6. 687,70 + 151,30 = 838

It looks like it calculates like this instead though:

1. 575 x 15% = 86,25 
2. 575 + 86.25 = 661,25 
3. 661,25 x 4% = 26,45
4. 661,25 x 22% = 145,48
5. 661,25 + 26, 45 + 145, 48 = 833,18

I tried this on a user's site, then also on two of my own.

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
### WordPress Environment ###

Home URL: https://zachwootest1.mystagingwebsite.com
Site URL: https://zachwootest1.mystagingwebsite.com
WC Version: 3.2.6
Log Directory Writable: ✔
WP Version: 4.9.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: nginx
PHP Version: 7.0.27
PHP Post Max Size: 100 MB
PHP Time Limit: 300
PHP Max Input Vars: 6144
cURL Version: 7.57.0
OpenSSL/1.0.1t

SUHOSIN Installed: –
Max Upload Size: 100 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.2.6
WC Database Prefix: wp_
Total Database Size: 4.91MB
Database Data Size: 2.86MB
Database Index Size: 2.05MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_order_itemmeta: Data: 0.06MB + Index: 0.03MB
wp_woocommerce_tax_rates: Data: 0.09MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.11MB + Index: 0.22MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_commentmeta: Data: 0.06MB + Index: 0.03MB
wp_comments: Data: 0.02MB + Index: 0.08MB
wp_followup_coupons: Data: 0.02MB + Index: 0.03MB
wp_followup_coupon_logs: Data: 0.02MB + Index: 0.03MB
wp_followup_customers: Data: 0.02MB + Index: 0.06MB
wp_followup_customer_carts: Data: 0.02MB + Index: 0.03MB
wp_followup_customer_notes: Data: 0.02MB + Index: 0.03MB
wp_followup_customer_orders: Data: 0.02MB + Index: 0.02MB
wp_followup_email_coupons: Data: 0.02MB + Index: 0.02MB
wp_followup_email_excludes: Data: 0.02MB + Index: 0.05MB
wp_followup_email_logs: Data: 0.02MB + Index: 0.05MB
wp_followup_email_orders: Data: 0.08MB + Index: 0.09MB
wp_followup_email_order_coupons: Data: 0.02MB + Index: 0.02MB
wp_followup_email_tracking: Data: 0.02MB + Index: 0.08MB
wp_followup_followup_history: Data: 0.02MB + Index: 0.05MB
wp_followup_order_categories: Data: 0.02MB + Index: 0.03MB
wp_followup_order_items: Data: 0.02MB + Index: 0.05MB
wp_followup_subscribers: Data: 0.02MB + Index: 0.03MB
wp_followup_subscribers_to_lists: Data: 0.02MB + Index: 0.03MB
wp_followup_subscriber_lists: Data: 0.02MB + Index: 0.03MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_options: Data: 1.30MB + Index: 0.05MB
wp_postmeta: Data: 0.20MB + Index: 0.16MB
wp_posts: Data: 0.11MB + Index: 0.06MB
wp_termmeta: Data: 0.02MB + Index: 0.03MB
wp_terms: Data: 0.02MB + Index: 0.03MB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wp_usermeta: Data: 0.03MB + Index: 0.03MB
wp_users: Data: 0.02MB + Index: 0.05MB
wp_wc_booking_relationships: Data: 0.02MB + Index: 0.03MB
wp_wc_points_rewards_user_points: Data: 0.02MB + Index: 0.03MB
wp_wc_points_rewards_user_points_log: Data: 0.02MB + Index: 0.05MB
wp_wc_warranty_products: Data: 0.02MB + Index: 0.05MB
wp_yoast_seo_links: Data: 0.02MB + Index: 0.02MB
wp_yoast_seo_meta: Data: 0.02MB + Index: 0.00MB

### Post Type Counts ###

attachment: 53
page: 12
post: 1
product: 37
product_variation: 38
revision: 12
scheduled-action: 52
shop_coupon: 2
shop_order: 22

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 3.2.6

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: booking (booking)
external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: #3 - /
Cart: #4 - /cart/
Checkout: #5 - /checkout/
My account: #6 - /my-account/
Terms and conditions: #312 - /terms-conditions/

### Theme ###

Name: Storefront
Version: 2.2.7
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –
```
</details>

### PR DESCRIPTION
**Pull request by mikejolley**
Fixes #18571 by making compound rates stack correctly when there are multiple rates with differing priorities.

Tests are passing. I also compared tax incl/excl carts to ensure the calculations match.

Phew.

### CODE REVIEW

File: includes/class-wc-tax.php [hunk 1]
```diff
@@ -190,26 +184,22 @@ public static function calc_exclusive_tax( $price, $rates ) {
...
-				$tax_amount = apply_filters( 'woocommerce_price_ex_tax_amount', $tax_amount, $key, $rate, $price, $the_price_inc_tax, $pre_compound_total );
-
-				// Add rate
 				if ( ! isset( $taxes[ $key ] ) ) {
 					$taxes[ $key ] = $tax_amount;
 				} else {
 					$taxes[ $key ] += $tax_amount;
 				}
+
+				$pre_compound_total = array_sum( $taxes );
```
Comment (claudiulodro) [inline includes/class-wc-tax.php]: `$pre_compound_total` doesn't seem to be used anywhere or for anything?

**Comment by claudiulodro** [comment]
Tests pass and this looks good. Just an unused variable (or something?) needs to be taken care of.

File: includes/class-wc-tax.php (hunk 1 above)
Comment (claudiulodro) [reply includes/class-wc-tax.php]: Never mind I see it's within the foreach loop. All good.
