### PR TITLE
A few updates for flaky e2e tests

### LINKED ISSUE #44813: [Flaky] merchant/products/block-editor/create-simple-product-block-editor.spec.js
can not create a product with duplicated SKU 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/7976145561

### LINKED ISSUE #45200: [Flaky] shopper/cart-checkout-block-calculate-tax.spec.js
can create Cart Block page 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/8088511775

### LINKED ISSUE #45206: [Flaky] shopper/cart-block-calculate-shipping.spec.js
allows customer to calculate Flat rate and Local pickup in cart block if in Portugal 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/8090875077

### LINKED ISSUE #45857: [Flaky] shopper/cart-checkout-restricted-coupons.spec.js
coupon cannot be used by any customer on checkout (email restricted) 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/8397062058

### PR DESCRIPTION
**Pull request by lanej0**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Updates that should stabilize a number of flaky/failing e2e tests.  ~~I skipped the `loading-screen.spec.js` tests because I cannot get them to pass locally, no matter what I try (running them alone, or with the entire suite)~~ (turns out I had a problem with my build, all good).

Closes: https://github.com/woocommerce/woocommerce/issues/45200
Closes: https://github.com/woocommerce/woocommerce/issues/45206
Closes: https://github.com/woocommerce/woocommerce/issues/44813
Closes: https://github.com/woocommerce/woocommerce/issues/45857

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Ensure tests pass in CI
2. `pnpm env:restart && pnpm test:e2e-pw`

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce/tests/e2e-pw/utils/editor.js [hunk 1]
```diff
@@ -10,8 +10,8 @@ const closeWelcomeModal = async ( { page } ) => {
 };
 
 const disableWelcomeModal = async ( { page } ) => {
-	await page.waitForLoadState();
-	await page.waitForFunction( () => window?.wp?.data );
+	await page.waitForLoadState( 'domcontentloaded' );
+	// await page.waitForFunction( () => window?.wp?.data );
```
Comment (adimoldovan) [inline plugins/woocommerce/tests/e2e-pw/utils/editor.js]: I'm not sure how this change helps with flakiness.

File: plugins/woocommerce/tests/e2e-pw/tests/shopper/cart-checkout-restricted-coupons.spec.js [hunk 2]
```diff
@@ -661,14 +661,16 @@ test.describe( 'Cart & Checkout Restricted Coupons', () => {
...
-			.fill( 'marge@example.com' );
+			.fill( 'marge.simpson@example.org' );
 
 		await page
 			.getByRole( 'link', { name: 'Click here to enter your code' } )
 			.click();
 		await page.getByPlaceholder( 'Coupon code' ).fill( 'email-restricted' );
 		await page.getByRole( 'button', { name: 'Apply coupon' } ).click();
 
+		await page.waitForLoadState( 'networkidle' );
```
Comment (adimoldovan) [inline plugins/woocommerce/tests/e2e-pw/tests/shopper/cart-checkout-restricted-coupons.spec.js:672]: Is waiting for network really necessary? The next expect should wait and timeout.

File: plugins/woocommerce/tests/e2e-pw/utils/editor.js (hunk 1 above)
Comment (lanej0) [reply plugins/woocommerce/tests/e2e-pw/utils/editor.js]: The test was failing consistently on this line -- I think that sometimes this function was failing/failing to load/I don't know. I tried a few different wait scenarios and waiting for the DOM seemed to work best.

File: plugins/woocommerce/tests/e2e-pw/tests/shopper/cart-checkout-restricted-coupons.spec.js (hunk 2 above)
Comment (lanej0) [reply plugins/woocommerce/tests/e2e-pw/tests/shopper/cart-checkout-restricted-coupons.spec.js:672]: Weirdly, without this in here explicitly, it would occasionally not wait and just report that the next element isn't visible.

File: plugins/woocommerce/tests/e2e-pw/utils/editor.js (hunk 1 above)
Comment (adimoldovan) [reply plugins/woocommerce/tests/e2e-pw/utils/editor.js]: If `window?.wp?.data` is not available the next code block will fail with a less friendlier error - the reason I've added this particular check. `window?.wp?.data` not being available most probably means the page did not load in the expected time. 
I guess waiting for `domcontentloaded` does the same thing, `domcontentloaded` probably implies that `window?.wp?.data` also loaded, as opposed to the default `load`. 
I see an advantage in having a single line instead of two, but still don't see why it helps with flakiness. 🤔 
If you decide to leave it as is, can you please remove the commented out code?

Comment (lanej0) [reply plugins/woocommerce/tests/e2e-pw/utils/editor.js]: I've seen a number of failures happen on this line.  

I'm not sure that this is the right fix, but let's give it a try for now.  I'll remove the commented line, but put in a comment so that if we continue to see errors, the next person investigating will know what went down.

**Review by adimoldovan — APPROVED** [review]
