### PR TITLE
Product Collection: Add support for passing extra attributes like "align" while registering a custom collection

### LINKED ISSUE #53287: Product Collection: `RegisterProductCollection` does not recognize align & layout attributes
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

The Product Collection block supports the align and layout attributes, but when registering a custom product collection with `__experimentalRegisterProductCollection` the align and layout attributes are not passed to the product collection block.

```
wc.wcBlocksRegistry.__experimentalRegisterProductCollection( {
	name: 'woocommerce/product-collection/themeslug-product-collection',
	title: __( 'Just a Test', 'themeslug'),
	scope: ['block'],
	attributes:
	{
		displayLayout: {
			type: 'flex',
			columns: 4,
			shrinkColumns: true
		},
		query: {
			perPage: 4,
			pages: 1
		},
		align: 'full',
		layout: {
			type: 'constrained'
		}
	},
	innerBlocks:[
		[
			'woocommerce/product-template',
			{},
			[
				[
					'woocommerce/product-image',
					{
						'imageSizing': 'thumbnail',
						'isDescendentOfQueryLoop': true
					},
					[]
				],
				[
					'core/post-title',
					{
						'textAlign': 'center',
						'level': 3,
						'isLink': true,
						'fontSize': 'medium',
						'__woocommerceNamespace': 'woocommerce/product-collection/product-title'
					},
					[]
				],
				
			]
		]
	]
} );
```

In the example above, one would expect the block to be displayed full-width after selecting the "Just a Test" product collection, but it is displayed in the default width.

### Expected behavior

The block should be initially displayed with the defined width, as the block does support the alignment attribute.

### Actual behavior

The alignment attribute is not recognized.

### Steps to reproduce

1. Add the above example code to a theme or plugin.
2. Add a Product Collection block to a new page or post.
3. In the Choose Collection select "Just a Test" custom product collection.
4. Notice that the block is displayed in the default width, when it should be full width.

### WordPress Environment

.

### Isolating the problem

- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by imanish003**
### Changes proposed in this Pull Request:

Closes #53287

While registering a custom collection using `__experimentalRegisterProductCollection`, user [reported](https://github.com/woocommerce/woocommerce/issues/53287) that the align and layout attributes are not passed to the product collection block. After [looking at the code](https://github.com/woocommerce/woocommerce/blob/db81bf0925a4f5802128f7051faf1cab99666070/plugins/woocommerce-blocks/assets/js/blocks-registry/product-collection/register-product-collection.tsx#L377-L423), I can see that we are selectively passing the attributes to the product collection block.

We had two options to fix this issue:
1. Pass only `align` and `layout` attributes selectively to the product collection block as we are doing for all other attributes.
2. Pass all attributes and then override attributes selectively. This way, If we don't override the attributes, they will be passed to the product collection block.

I went with the second option because it will give 3PDs more flexibility to provide any custom attributes to the product collection block and we won't need to maintain selective passing of attributes. Let me know your thoughts.

### How to test the changes in this Pull Request:

1. Create a new post
2. Run following code in browser console. This will register a new custom collection with title "Just a Test" and align attribute set to "full".
```tsx
wc.wcBlocksRegistry.__experimentalRegisterProductCollection({
  name: "woocommerce/product-collection/just-a-test",
  title: "Just a Test",
  scope: ["block", "inserter"],
  attributes: {
    align: "full",
  },
  innerBlocks: [
    [
      "woocommerce/product-template",
      {},
      [
        [
          "woocommerce/product-image",
          {
            imageSizing: "thumbnail",
            isDescendentOfQueryLoop: true,
          },
          [],
        ],
        [
          "core/post-title",
          {
            textAlign: "center",
            level: 3,
            isLink: true,
            fontSize: "medium",
            __woocommerceNamespace:
              "woocommerce/product-collection/product-title",
          },
          [],
        ],
      ],
    ],
  ],
});
```
3. Add Product Collection block and choose "Just a Test" collection.
4. Verify that the block is displayed full-width as shown in the screenshot below:
Image

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [x] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [x] Enhancement - Improvement to existing functionality

#### Message 
Product Collection: Add support for passing extra attributes like align while registering a custom collection.
</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

**Comment by imanish003** [comment]
CC: @kmanijak, I have also added you as a reviewer, as it would be good to get your thoughts on this.

File: plugins/woocommerce-blocks/assets/js/blocks-registry/product-collection/register-product-collection.tsx [hunk 1]
```diff
@@ -375,6 +375,7 @@ export const __experimentalRegisterProductCollection = (
 		example: config.example,
 		scope: config.scope,
 		attributes: {
+			...config.attributes, // Allow users to pass extra attributes.
```
Comment (kmanijak) [inline plugins/woocommerce-blocks/assets/js/blocks-registry/product-collection/register-product-collection.tsx:378]: In that case we can remove:

- `displayLayout: config.attributes?.displayLayout,` ([here](https://github.com/woocommerce/woocommerce/pull/53785/files#diff-c7bc52835382b93fa7671255cb9aae9e6eee453f93a53ed11f6e116646df7f5bR417))

- `queryContextIncludes: config.attributes?.queryContextIncludes,` ([here](https://github.com/woocommerce/woocommerce/pull/53785/files#diff-c7bc52835382b93fa7671255cb9aae9e6eee453f93a53ed11f6e116646df7f5bR419))

**Review by kmanijak — APPROVED** [review]
I agree with this approach. And it works as expected. 👍 

I jest left a minor comment to avoid code duplication but pre-approving!

File: plugins/woocommerce-blocks/assets/js/blocks-registry/product-collection/register-product-collection.tsx (hunk 1 above)
Comment (imanish003) [reply plugins/woocommerce-blocks/assets/js/blocks-registry/product-collection/register-product-collection.tsx:378]: Good point! I have removed the duplicate attribute assignments since we're now spreading all config.attributes at once. This makes the code cleaner and more maintainable. Thanks for pointing this out.
