### PR TITLE
Product Collection - Cross-sell product: fix Product Selector when the selected product is deleted

### LINKED ISSUE #54345: [Product Collection] - Cross-sells product selection error when the original was deleted
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Fist selection doesn't work when picking a substitute product for `Cross-sells` (or `Upsells`) after deleting the original.

https://github.com/user-attachments/assets/7afa9274-966a-4428-84b2-816cebbc44c5

Please take a look at the solution proposed by [this PR](https://github.com/woocommerce/woocommerce/pull/54053) for this problem.

### Expected behavior

Selecting the product to replace the original one only once should be enough. 

### Actual behavior

It's necessary to select the replacement product twice.

### Steps to reproduce

1. Create two products
2. Go to Pages > Add New Page
3. Add a Product Collection block and select the `Cross-Sells` (or `Upsells`) option.
4. Select one of the products you just created and save.
5. Delete the product permanently and refresh the page you saved in step 4
6. You will see a form to pick a replacement like this

Image

7. Pick a product on the list.
8. Verify that you need to select the product twice in order to get the action done.

### WordPress Environment

This is happening on `trunk`.

### Isolating the problem

- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by gigitux**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

The `ProductPicker` component was re-rendering due to the use of `useBlockProps`. Attributes are set up long the entire the Product Collection components tree and this causes the re-rendering. Since `useBlockProps` isn't necessary in this context, it has been removed to improve performance and stability.

Also, fixing the `tests/editor/create-woocommerce-blocks.spec.js` E2E, I noticed duplicate `useBlockProps` usage across different block.

Closes #54345 (WOOPLUG-2976).

### Screenshots or screen recordings:

| Before | After |
| ------ | ----- |
| <video src="https://github.com/user-attachments/assets/a59c26f5-c9f2-477b-8cb6-9182b56b46ee" />   |  <video src="https://github.com/user-attachments/assets/4a64db48-a74c-4d0c-9280-22bfb3efbaf5" />     |

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Create two products
2. Go to Pages > Add New Page
3. Add a Product Collection block and select the `Cross-Sells` (or `Upsells`) option.
4. Select one of the products you just created and save.
5. Delete the product permanently and refresh the page you saved in step 4
6. You will see a form to pick a replacement like this

Image

7. Pick a product on the list.
8. Verify that you need to select the product only once.

## Reviews By Category
1. Create a new page.
2. Add the `reviews by category` block.
3. Ensure that the block wrapper attributes aren't duplicated in two nested divs:

| Before | After |
|--------|--------|
| image | image | 

### Product Collection
1. Create a new page.
2. Add the `Product Collection` block.
3. Select a collection
4. Ensure that the block wrapper attributes aren't duplicated in two nested divs:

| Before | After |
|--------|--------|
| image | image |
 

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [x] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 
Product Collection - Cross-sell product: fix Product Selector when the selected product is deleted.

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce/client/blocks/assets/js/blocks/product-collection/edit/ProductPicker.tsx [hunk 1]
```diff
@@ -2,16 +2,13 @@
...
  */
 import { __, sprintf } from '@wordpress/i18n';
-import { useBlockProps } from '@wordpress/block-editor';
 import { Icon, info } from '@wordpress/icons';
 import ProductControl from '@woocommerce/editor-components/product-control';
 import type { SelectedOption } from '@woocommerce/block-hocs';
 import { createInterpolateElement } from '@wordpress/element';
 import {
 	Placeholder,
-	// @ts-expect-error Using experimental features
```
Comment (gigitux) [inline plugins/woocommerce/client/blocks/assets/js/blocks/product-collection/edit/ProductPicker.tsx:12]: Removed this comment because after updating to `@wordpress/components` is not necessary anymore.

**Comment by gigitux** [comment]
Added as reviewer @kmanijak given that could have more context.

**Review by kmanijak — APPROVED** [review]
Huh, good catch @gigitux!

Tested Upsells and Cross-Sells, product picker picks up at first choice!

**Comment by gigitux** [comment]
@kmanijak I didn't realize that the automerge was enabled, but fixing the `tests/editor/create-woocommerce-blocks.spec.js ` E2E test, I noticed duplicate `useBlockProps` usage across different blocks, so I fixed them: I updated the testing instruction. Can you review my changes? I will fix any comment in a follow-up PR! Thanks! 🙇

File: plugins/woocommerce/client/blocks/assets/js/blocks/product-collection/edit/product-collection-content.tsx [hunk 2]
```diff
@@ -155,7 +155,7 @@ const ProductCollectionContent = ( {
 	}
 
 	return (
-		<div { ...blockProps }>
```
Comment (kmanijak) [inline plugins/woocommerce/client/blocks/assets/js/blocks/product-collection/edit/product-collection-content.tsx:158]: @gigitux  this one is needed. After choosing a collection (initial prompt), this is the main wrapper of the Product Collection. Without it Product Collection block is not highlighted in editor 

https://github.com/user-attachments/assets/3b61cef0-7f7d-4e44-a5a0-3e2ac7747a1c

File: plugins/woocommerce/client/blocks/assets/js/blocks/product-collection/edit/ProductPicker.tsx [hunk 3]
```diff
@@ -52,36 +48,34 @@ const ProductPicker = (
 		  );
 
 	return (
-		<div { ...blockProps }>
```
Comment (kmanijak) [inline plugins/woocommerce/client/blocks/assets/js/blocks/product-collection/edit/ProductPicker.tsx:55]: This one as well. Basically in the  https://github.com/woocommerce/woocommerce/blob/f861f01d3c9cc1c0d632bbb4e651f829654c41d7/plugins/woocommerce/client/blocks/assets/js/blocks/product-collection/edit/index.tsx you can see there's a choice which component is rendered and any of them can be a "main" block and each of them should get block props.

**Review by kmanijak — COMMENTED** [review]
> @kmanijak I didn't realize that the automerge was enabled, but fixing the tests/editor/create-woocommerce-blocks.spec.js  E2E test, I noticed duplicate useBlockProps usage across different blocks, so I fixed them: I updated the testing instruction. Can you review my changes? I will fix any comment in a follow-up PR! Thanks! 🙇

They're actually needed, I left two comments. Let me know when you plan to address it. I can spin up a quick PR, would be good to bring it back before Monday's code freeze.
