### PR TITLE
Fix: append changelog entries grouped by type

### LINKED ISSUE #60421: Fix the order of the issues in the changelog PR
When running the [Release: Compile changelog](https://github.com/woocommerce/woocommerce/actions/workflows/release-compile-changelog.yml), the logs in the updated `readme.txt` are always added at the end (see [here](https://github.com/woocommerce/woocommerce/pull/60293/commits/1105cffa9480b3125aad4d369fe42df5a69e14f6)), forcing us to do a manual update to group them (see [here](https://github.com/woocommerce/woocommerce/pull/60293/commits/62f617975f342723c3bfe2bfcfe00a8f472321eb)).

We should investigate if it's possible to automatically group them to avoid any manual modification.

### PR DESCRIPTION
**Pull request by albarin**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

This PR makes sure the newly added changelog entries are added in the right order. Before, new entries were added at the end of the changelog instead of grouping them by type (see [this PR](https://github.com/woocommerce/woocommerce/pull/60293/commits) as an example of the manual fix that was needed).

Closes #60421

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Fork the WooCommerce repository and merge this PR into `trunk`.
2. Go to **Code > Branches** and create a new branch named `release/10.2` based off of `trunk`.
3. Run the "Compile changelog" workflow for version `10.2`.
4. Merge the resulting `Release: Prepare the changelog for 10.2`.
5. Using the `pnpm --filter=@woocommerce/plugin-woocommerce changelog add` command, add multiple changelogs with different types (add, dev, enhancement, fix, update, twear, or performance) to the `release/10.2` branch.
6. Run the "Compile changelog" workflow again for version `10.2`.
7. Ensure the resulting `Release: Prepare the changelog for 10.2` PR has all the new changelog entries added at the end of their corresponding group. If there's no group for some of them, they should be added at the end.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

File: tools/monorepo-utils/src/code-freeze/commands/changelog/lib/index.ts [hunk 1]
```diff
@@ -62,17 +108,7 @@ const updateReleaseChangelogs = async (
...
-			.replace(
-				/^= \d+\.\d+\.\d+ \d{4}-\d{2}-\d{2} =\n\n\*\*WooCommerce\*\*\n\n/,
-				''
-			)
-			.trim();
-		readme = readme.replace(
-			/\n+(\[See changelog for all versions\])/,
-			`\n${ changelogEntries }\n\n$1`
-		);
+		readme = appendSortedChangelog( nextLog, readme );
```
Comment (jorgeatorres) [inline tools/monorepo-utils/src/code-freeze/commands/changelog/lib/index.ts]: Instead of moving everything to a function with all the logic, could we maybe break the process up in a few steps? That way it is also easier to debug or grasp the logic.

For example, instead of calling `appendSortedChangelog()`  and expect it to do everything, we could here:

- Match the existing changelog entries from `readme`.
- Fetch the new changelog entries as `nextLog` and remove the header.
- Call, say, `mergeChangelog()` (instead of `appendSortedChangelog()`) that receives both the existing entries as well as the new ones, and returns the combined result.
- Insert it the result in the readme replacing the existing changelog.

This might sound a bit unnecessary, but even though I'm relatively familiar with this code, I always have to wonder whether a specific variable is the full file or just the changelog entries or the entries with the header and the last link or without the link, etc., so I thought doing it "step by step" might be useful for anyone having to dive into this code in the future.

It could also help unify the append and non-append versions a bit.

File: tools/monorepo-utils/src/code-freeze/commands/changelog/lib/index.ts [hunk 2]
```diff
@@ -19,6 +19,52 @@ import {
...
+		const match = entry.match(
+			/^\* (Fix|Add|Dev|Enhancement|Update|Tweak|Performance)/i
+		);
+		if ( ! match ) return;
+
+		const entryType = match[ 1 ];
+
+		// Find all existing entries of the same type
+		const typeRegex = new RegExp( `\\* ${ entryType }.*`, 'gi' );
+		const matches = [ ...updatedReadme.matchAll( typeRegex ) ];
```
Comment (jorgeatorres) [inline tools/monorepo-utils/src/code-freeze/commands/changelog/lib/index.ts]: Unless I'm missing something, I don't think we need to specifically match against one of the changelog entry types. We could just extract `* (a word) -` or even just `* (a word)` from the entry and search for that in `updatedReadme`.

Unless Jetpack changelogger changes, it always prefixes entries in that way, and we wouldn't have to hardcode the different types here. It'd be sort of a more "generic" sorted merge.

What do you think?

**Review by jorgeatorres — CHANGES_REQUESTED** [review]
Hey @albarin!

This works beautifully. It's like magic 🪄.
I left some comments around the code structure and maybe a way to simplify things, but overall looks good to me and tests well.

One thing I did notice is that it's possible to create changelog files with messages that span several lines (maybe not via CLI but by editing the file or through the PR automation). This was already a problem before (it's not a regression introduced with this PR) but the entry manipulation we're adding here will make things worse when such entry is encountered.

Can you check if there's some flag we can pass to the changelogger tool to remove new lines or make it part of the changelog validation on PRs that the entry doesn't contain new line characters? I feel we should address that before the changes here are merged.

What do you think?

File: tools/monorepo-utils/src/code-freeze/commands/changelog/lib/index.ts (hunk 2 above)
Comment (albarin) [reply tools/monorepo-utils/src/code-freeze/commands/changelog/lib/index.ts]: Yep, great suggestion. I just pushed a change for this. I'll probably have a look at the other comment tomorrow.

File: tools/monorepo-utils/src/code-freeze/commands/changelog/lib/index.ts (hunk 1 above)
Comment (albarin) [reply tools/monorepo-utils/src/code-freeze/commands/changelog/lib/index.ts]: Hey @jorgeatorres, I've pushed a refactor.
I've added a new `processNextChangelog` function, which extracts the title and next entries and then, depending on the append flag, does different things with them. Let me know what you think or if you would refactor it even more. Thanks!

File: tools/monorepo-utils/src/code-freeze/commands/changelog/lib/index.ts [hunk 3]
```diff
@@ -19,6 +19,87 @@ import {
...
+	changelogEntries = changelogEntries.replace(
+		/\[#(\d+)\](?!\()/g,
+		'[#$1](https://github.com/woocommerce/woocommerce/pull/$1)'
+	);
+
+	// Split changelogEntries into individual entries by detecting lines that start with "* "
+	// This preserves multiline changelog entries.
+	const entries = changelogEntries
+		.split( '\n' )
+		.filter( ( line ) => line.trim() );
```
Comment (jorgeatorres) [inline tools/monorepo-utils/src/code-freeze/commands/changelog/lib/index.ts]: I believe the comment here is incorrect. We're actually **not** preserving multiline entries if we just split by `\n`. I didn't test [the approach the rabbit suggested](https://github.com/woocommerce/woocommerce/pull/60529/files#r2309840965) but it might be worth giving it a try.

**Review by jorgeatorres — CHANGES_REQUESTED** [review]
Hey @albarin!

Thanks for the little refactor. It makes following the flow of the code much easier 💯

CodeRabbit suggested an approach for supporting multiline entries. If that works well and it's robust enough, I'm good with that. Otherwise, we could end up with entries that are missing content.

During testing, I noticed that with [this changelog file](https://github.com/jorgeatorres/woocommerce/blob/release/10.3/plugins/woocommerce/changelog/2025-09-13-changelog3) the code on this branch [results in](https://github.com/jorgeatorres/woocommerce/pull/252/files#diff-af9803036f8a727e2311b0ef2971497323c6c4aa67d5e0dab4ee4b68a25464b7R314)

> * Dev - This is a multiline

while the code on `trunk` correctly handles [the multiple lines](https://github.com/jorgeatorres/woocommerce/pull/253/files#diff-af9803036f8a727e2311b0ef2971497323c6c4aa67d5e0dab4ee4b68a25464b7R340-R342).

As I said before, I'd prefer if we don't allow multiple lines in changelog entries but we should either enforce that (#60678) or support it here to avoid producing the incorrect output. What do you think?

File: tools/monorepo-utils/src/code-freeze/commands/changelog/lib/index.ts (hunk 3 above)
Comment (albarin) [reply tools/monorepo-utils/src/code-freeze/commands/changelog/lib/index.ts]: Sorry, the comment is a leftover from the previous approach. I just removed it.
The coderabbit suggestion was good, actually. I tested with the same multiline changelog entry you mentioned and it works https://github.com/albarin/woocommerce/pull/13/files#diff-af9803036f8a727e2311b0ef2971497323c6c4aa67d5e0dab4ee4b68a25464b7R307

**Comment by albarin** [comment]
@jorgeatorres I fixed the issue and removed the comment. Yes, let's not allow a multiline changelog with https://github.com/woocommerce/woocommerce/issues/60678.

**Review by jorgeatorres — APPROVED** [review]
Thanks for making the changes @albarin (and for your patience)! 

Confirmed in my fork that things are working correctly, both the initial changelog generation (https://github.com/jorgeatorres/woocommerce/pull/254) as well as the update with a multiline entry (https://github.com/jorgeatorres/woocommerce/pull/256/files).
