### PR TITLE
Set user's selected payment gateway after checkout fragment refresh (#11492)

### LINKED ISSUE #11492: checkout_update trigger reverts payment gateway selection when payment token present
When you have a saved payment token, it default to using that payment gateway with the payment token pre-selected which is working as intended.

However, if visit the checkout, then choose a payment gateway other than the one with the saved payment method, it will revert back to the payment gateway with the default payment token when you change something like the Country (which will trigger "checkout_update")

To reproduce:

1. Visit checkout
2. Saved default payment token should be pre-selected
3. Select a new payment gateway
4. Change Country (or similar, basically looking to trigger checkout_update)
5. On AJAX refresh it reverts the selected payment gateway back to the default payment token.

I came across this issue due to our third party plugin triggering checkout_update on payment gateway change in order to add a fee specific to the payment gateway (loads of third party plugins and custom code examples do this, eg. charge a fee for using cheque gateway) which then automatically reverted the gateway again meaning you couldn't change the payment gateway if there was saved payment token!

Ideally you would only pre-select the payment gateway with the default payment token on initial page load not after every checkout update. Basically if subsequent checkout_updated calls retained the selected payment gateway then this would avoid a whole host of issues with 3rd party code integration.

Alternatively another approach would be to provide additional filters for third party plugins to hook in and change the selected payment token during checkout update.

This issue is present on WooCommerce 2.6.x after Payment Token API was released. Happens on all themes.

### PR DESCRIPTION
**Pull request by emdashcodes**
The HTML fragments for the payment methods are completely updated as a part of `checkout_update` to make sure payment methods are updated with correct information (ex: fees or other changes). This can reset the selected payment gateway since the full HTML is refreshed. This PR grabs the selected payment gateway before the update happens, so we can make sure to set the users choice back (instead of defaulting to anything else).

Fixes #11492.

### CODE REVIEW

File: assets/js/frontend/checkout.js [hunk 1]
```diff
@@ -55,17 +55,21 @@ jQuery( function( $ ) {
...
 		},
-		init_payment_methods: function() {
+		init_payment_methods: function( selectedPaymentMethod ) {
 			var $payment_methods = $( '.woocommerce-checkout' ).find( 'input[name="payment_method"]' );
 
-			// If there is one method, we can hide the radio input
-			if ( 1 === $payment_methods.length ) {
-				$payment_methods.eq(0).hide();
-			}
+			if ( selectedPaymentMethod ) {
```
Comment (mikejolley) [inline assets/js/frontend/checkout.js]: What if there is only 1 method, but that method is 'selected'? Does this still handle that? I ask because the radio is still there, just hidden if there is one method only.

File: assets/js/frontend/checkout.js [hunk 2]
```diff
@@ -271,6 +275,9 @@ jQuery( function( $ ) {
 				url:		wc_checkout_params.wc_ajax_url.toString().replace( '%%endpoint%%', 'update_order_review' ),
 				data:		data,
 				success:	function( data ) {
+
+					var selectedPaymentMethod = $( '.woocommerce-checkout' ).find( 'input[name="payment_method"]' ).filter( ':checked' ).attr( 'id' );
```
Comment (mikejolley) [inline assets/js/frontend/checkout.js]: Any performance improvement with `filter()` vs `:checked` in the first selector?

File: assets/js/frontend/checkout.js (hunk 1 above)
Comment (justinshreve) [inline assets/js/frontend/checkout.js]: Thanks for pointing that out. I moved the hiding code outside of the else block, because it should run either way. The PR works with it.

File: assets/js/frontend/checkout.js (hunk 2 above)
Comment (justinshreve) [inline assets/js/frontend/checkout.js]: Just did a quick test and it looked like :checked is indeed faster.

**Comment by justinshreve** [comment]
Changes made!

File: assets/js/frontend/checkout.js [hunk 3]
```diff
@@ -55,17 +55,21 @@ jQuery( function( $ ) {
...
 			}
 
-			// If there are none selected, select the first.
-			if ( 0 === $payment_methods.filter( ':checked' ).length ) {
-				$payment_methods.eq(0).prop( 'checked', true );
+			if ( selectedPaymentMethod ) {
+				$( '#' + selectedPaymentMethod ).prop( 'checked', true );
+			} else {
+				// If there are none selected, select the first.
+				if ( 0 === $payment_methods.filter( ':checked' ).length ) {
```
Comment (mikejolley) [inline assets/js/frontend/checkout.js]: Sorry, 1 more thing :) This logic sees if there are checked elements, and if not checks the first.

Wouldn't it make sense to move this out of the conditonal `if ( selectedPaymentMethod ) {`? Then it can still run if the ID was not found for example.

Comment (justinshreve) [inline assets/js/frontend/checkout.js]: @mikejolley It runs on the `else`, so it does run if no ID is found. We could move it out of the else, but there isn't much point in running it if selectedPaymentMethod already got selected.

Comment (mikejolley) [inline assets/js/frontend/checkout.js]: The else runs if `if ( selectedPaymentMethod ) {` is false. I don't know if it's even possible, but it won't run if `$( '#' + selectedPaymentMethod )` matches nothing.

**Comment by justinshreve** [comment]
Got it. Handled in https://github.com/woothemes/woocommerce/pull/11501/commits/f77cdd366d2b835db5f689752777530a37306715.

**Comment by mikejolley** [comment]
👍 LGTM
