### PR TITLE
Blueprint - Fix theme activation bug

### LINKED ISSUE #54219: [Blueprint] Install Theme step doesn't work correctly - fails at activating the theme after installation
When a step with theme installation is imported, the theme is correctly installed but the following bit fails when activating. A subsequent retry does not error, but it also does not correctly activate the theme. This is due to an early return when the theme has been detected to be already installed.

### To Reproduce

- Install WC trunk on JN, with blueprint feature flag activated
- Go to WC Settings | Advanced | Blueprint and import this blueprint: [woo-blueprint-install-theme.json](https://github.com/user-attachments/files/18329413/woo-blueprint-install-theme.json)

### Expected Behaviour

- The theme installation step should not fail when activating the theme
- The theme installation step should not report successful completion prematurely if it is detected to be installed, when it has not been activated.

### PR DESCRIPTION
**Pull request by moon0326**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes #54219  .

This PR resolves an issue where theme activation was not functioning correctly.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Create a new JN site with this branch and enable `blueprint` feature flag.
2. Navigate to `WooCommerce -> Settings -> Advanced -> Blueprint`
3. Upload [woo-blueprint-install-theme.json](https://github.com/user-attachments/files/18329413/woo-blueprint-install-theme.json) and import it.
4. Navigate to `Appearance -> Themes`
5. Twenty Twenty-Five theme should now be active.

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [x] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

Blueprint - Fix bug with installTheme step where it ignored 'activate' flag

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

**Review by chihsuan — COMMENTED** [review]
Just found that the `pr-build-live-branch.yml` is not running because `packages/php/**` is ignored. Maybe we should enable it for blueprints for easier review. 🤔 

https://github.com/woocommerce/woocommerce/blob/590c52da332cbb0de6e91151810ae435a8ff71aa/.github/workflows/pr-build-live-branch.yml#L11

**Review by chihsuan — COMMENTED** [review]
> Twenty Twenty-Five theme should now be active.


I tested on my local but Twenty Twenty-Five theme is not active. It seems like it's because Twenty Twenty-Five theme is already installed and it skips the activation step. Is this expected?

**Comment by moon0326** [comment]
> Just found that the `pr-build-live-branch.yml` is not running because `packages/php/**` is ignored. Maybe we should enable it for blueprints for easier review. 🤔
> 
> https://github.com/woocommerce/woocommerce/blob/590c52da332cbb0de6e91151810ae435a8ff71aa/.github/workflows/pr-build-live-branch.yml#L11

~Good call! Updated it in a separate PR [Blueprint - Trigger live build for blueprint package changes](https://github.com/woocommerce/woocommerce/pull/55149#top)~

Good call! Updated it in [Trigger live build for blueprint package changes](https://github.com/woocommerce/woocommerce/pull/54586/commits/bc18bad589784cfe93ff48c701f32d473c0e2eaa)

**Comment by moon0326** [comment]
> > Twenty Twenty-Five theme should now be active.
> 
> I tested on my local but Twenty Twenty-Five theme is not active. It seems like it's because Twenty Twenty-Five theme is already installed and it skips the activation step. Is this expected?

Good catch! Fixed it in [Attempt to activate theme if it is already installed](https://github.com/woocommerce/woocommerce/pull/54586/commits/72eda2f28a037dd88f17ca5bf2077d6d7801d232)

File: packages/php/blueprint/src/Importers/ImportInstallTheme.php [hunk 1]
```diff
@@ -81,17 +87,25 @@ public function process( $schema ): StepProcessorResult {
...
-			$this->result->add_info( "Switched theme to '$theme->slug'." );
-		} else {
-			$this->result->add_error( "Failed to switch theme to '$theme->slug'." );
-		}
+		$this->activate_theme( $schema );
 
 		return $this->result;
 	}
 
+	protected function activate_theme( $schema ) {
```
Comment (chihsuan) [inline packages/php/blueprint/src/Importers/ImportInstallTheme.php:102]: Can we also add doc comment for this function?

File: packages/php/blueprint/src/Importers/ImportInstallTheme.php [hunk 2]
```diff
@@ -81,17 +87,25 @@ public function process( $schema ): StepProcessorResult {
...
+		$theme = $schema->themeZipFile;
```
Comment (chihsuan) [inline packages/php/blueprint/src/Importers/ImportInstallTheme.php:104]: Not related to this PR, but I think we should use snake case format for variables.

**Review by chihsuan — APPROVED** [review]
Thanks for addressing feedback, tested well!  🚢

File: packages/php/blueprint/src/Importers/ImportInstallTheme.php (hunk 2 above)
Comment (moon0326) [reply packages/php/blueprint/src/Importers/ImportInstallTheme.php:104]: @chihsuan this is actually Blueprint spec. It's been renamed (deprecated) to `themeData` in the latest spec though. 

```
{
    "steps": [
        {
            "step": "login"
        },
        {
            "step": "installTheme",
            "themeData": {
                "resource": "wordpress.org/themes",
                "slug": "pendant"
            },
            "options": {
                "activate": true,
                "importStarterContent": true
            }
        }
    ]
}
```

File: packages/php/blueprint/src/Importers/ImportInstallTheme.php (hunk 1 above)
Comment (moon0326) [reply packages/php/blueprint/src/Importers/ImportInstallTheme.php:102]: Done in [Add comment and fix lint issue](https://github.com/woocommerce/woocommerce/pull/54586/commits/40faaabd1cc70e7475272633ea25dbd53fbb4e49)
