### PR TITLE
Remove unnecessary APIs calls when the setup tasklist is shown

### LINKED ISSUE #40292: Stat APIs are requested even when the setup tasklist is active
**Issue Description:**

The following APIs are requested when the setup tasklist is active. Those APIs should only be requested with the ActivityPanel when the setup tasklist is hidden.

/wp-json/wc-analytics/products/low-in-stock
/wp-json/wc-analytics/products/reviews
/wp-json/wc-analytics/orders

## Steps to reproduce

1. Create a new JN site.
2. Complete the core profiler and navigate to WooCommerce Home
3. Open browser inspector and click `Network` tab
4. Refresh the page
5. Confirm the APIs are requested when the setup tasklist is active.

It also happens on almost all other WC pages, where we have `Activity` button.

### PR DESCRIPTION
**Pull request by moon0326**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes #40292 .

This PR fixes a bug where ActivtiyPanel calls orders, reviews, and stock APIs even when the setup tasklist is shown. The APIs should only be called when the tasklist is hidden.

- Sets default value to false to prevent [checkIfHasAbbreviatedNotifications](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce-admin/client/activity-panel/activity-panel.js#L177) from calling the APIs when the tasklist is being resolved.
- Consider setup tasklist is hidden when `activeSetupList` is null

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Create a new JN site with this branch.
2. Complete the core profiler and navigate to `WooCommerce -> Home`
3. Make sure the setup tasklist is shown.
4. Open your browser console and click `Network` tab.
5. Make sure the following API endpoints are not called.

APIs
- /wp-json/wc-analytics/products/low-in-stock
- /wp-json/wc-analytics/products/reviews
- /wp-json/wc-analytics/orders

6. Hide the setup tasklist

Screen Shot 2023-09-19 at 5 19 14 PM

7. Refresh the page.
8. Confirm the APIs are requested.
9. Navigate to other WC pages such as products, analytics, and confirm the same behavior.

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

Remove unnecessary APIs calls when the setup tasklist is shown

#### Comment 

</details>

### CODE REVIEW

**Review by crunnells — APPROVED** [review]
Tested fine, LGTM!

File: plugins/woocommerce-admin/client/activity-panel/activity-panel.js [hunk 1]
```diff
@@ -164,9 +164,9 @@ export const ActivityPanel = ( { isEmbedded, query } ) => {
 			ONBOARDING_STORE_NAME
 		);
 
-		const setupList = getTaskList( activeSetupList );
+		const setupList = activeSetupList && getTaskList( activeSetupList );
 
-		const isSetupTaskListHidden = setupList?.isHidden ?? true;
+		const isSetupTaskListHidden = setupList?.isHidden ?? false;
```
Comment (psealock) [inline plugins/woocommerce-admin/client/activity-panel/activity-panel.js:169]: Odd that the way this was written, ie if `setupList` was null or undefined, `isSetupTaskListHidden` would evaluate to `true`. I wasn't able to spot any downstream problems with this logic reversed though 🤷🏽

**Review by psealock — COMMENTED** [review]
This is testing well, thanks @moon0326. However I see `/wp-json/wc-analytics/reports/performance-indicators` still being called. That endpoint powers these stats and can be also disabled when the TaskList is present.

image

File: plugins/woocommerce-admin/client/activity-panel/activity-panel.js (hunk 1 above)
Comment (moon0326) [reply plugins/woocommerce-admin/client/activity-panel/activity-panel.js:169]: So when `isSetupTaskListHidden` is true, https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce-admin/client/activity-panel/activity-panel.js#L177 requests the API endpoints. Since `isSetupTaskListHidden` always evaulates to true initially, the APIs are requested regardless of the final value of `isSetupTaskListHidden`

Comment (moon0326) [reply plugins/woocommerce-admin/client/activity-panel/activity-panel.js:169]: > This is testing well, thanks @moon0326. However I see /wp-json/wc-analytics/reports/performance-indicators still being called. That endpoint powers these stats and can be also disabled when the TaskList is present.

Good catch 👍 I'll work on a patch.

Comment (moon0326) [reply plugins/woocommerce-admin/client/activity-panel/activity-panel.js:169]: @psealock  I've looked into the [code](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce-admin/client/homescreen/stats-overview/index.js#L141) and it doesn't check for the Tasklist visibility.  Since stores can have orders regardless of the TaskList status, wouldn't it be expected to query the endpoint? 🤔

Comment (psealock) [reply plugins/woocommerce-admin/client/activity-panel/activity-panel.js:169]: >Since stores can have orders regardless of the TaskList status, wouldn't it be expected to query the endpoint? 🤔

If I remember correctly, the `performance-indicators` endpoint just powers those stats I screenshoted which are hidden when the task list is available. I don't think they are used elsewhere like the Orders page.

Comment (moon0326) [reply plugins/woocommerce-admin/client/activity-panel/activity-panel.js:169]: @psealock, Thanks! I'll look into it further. Those stats are visible all the time for me for some reason. I might have enabled it manually.

Comment (psealock) [reply plugins/woocommerce-admin/client/activity-panel/activity-panel.js:169]: >Those stats are visible all the time for me for some reason.

In that case we should leave the endpoints in place then. Thanks for double checking
