### PR TITLE
Fixed "woocommerce_new_order" triggering on checkout blocks page visit

### LINKED ISSUE #45145: woocommerce_new_order triggers on checkout visiting
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

hey ,

It looks like WooCommerce's latest version has a bug.

using 

The woocommerce_new_order hook gets triggered on checkout page visits and is not as expected. 
I have reproduced a bug for three clean WordPress installations.
Please note that it gets triggered only on the first checkout page visit on the specific cart key. 

### Expected behavior

woocommerce_new_order triggers on new order

### Actual behavior

woocommerce_new_order triggers on checkout page visited

### Steps to reproduce

1 - Enable WP debug

2- paste this code into functions.php
```php
add_action("woocommerce_new_order","any",20,1);
function any($order_id){
    error_log("new triggred --------|");
}
```
3- if your cart has items make sure to place a new order
4 - and then go back and add item(s) to your cart and visit the checkout page 
then check your debug file

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): http://dev2.local
Site address (URL): http://dev2.local
WC Version: 8.6.1
REST API Version: ✔ 8.6.1
WC Blocks Version: ✔ 11.8.0-dev
Action Scheduler Version: ✔ 3.7.1
Log Directory Writable: ✔
WP Version: 6.4.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.16.0
PHP Version: 8.1.23
PHP Post Max Size: 1,000 MB
PHP Time Limit: 1200
PHP Max Input Vars: 4000
cURL Version: 7.77.0
OpenSSL/1.1.1t

SUHOSIN Installed: –
MySQL Version: 8.0.16
Max Upload Size: 300 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.6.1
WC Database Prefix: wp_
Total Database Size: 5.30MB
Database Data Size: 3.60MB
Database Index Size: 1.70MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 2.48MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_posts: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wc_orders_meta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 1
page: 7
post: 2
product: 1
shop_order_placehold: 14
wp_template: 2

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 8.6.1

### Settings ###

API Enabled: –
Force SSL: –
Currency: DZD (د.ج)
Currency Position: left_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to Woo.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### WC Pages ###

Shop base: #6 - /shop/
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Astra
Version: 4.6.5
Author URL: https://wpastra.com/about/?utm_source=theme_preview&utm_medium=author_link&utm_campaign=astra_theme
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
product-virtual-downloadable
product-external-affiliate
product-grouped
product-linked
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: customize-store
minified-js
new-product-management-experience
product-pre-publish-modal
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2024-02-27 16:26:57 +00:00
Options: ✔
Notes: 64
Onboarding: skipped

### Action Scheduler ###

Complete: 26
Oldest: 2024-02-26 16:28:00 +0000
Newest: 2024-02-26 16:56:34 +0000

Failed: 1
Oldest: 2024-02-26 16:28:35 +0000
Newest: 2024-02-26 16:28:35 +0000

Pending: 1
Oldest: 2024-02-27 16:28:00 +0000
Newest: 2024-02-27 16:28:00 +0000

### Status report information ###

Generated at: 2024-02-26 17:11:23 +00:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by wavvves**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

This PR fixes "woocommerce_new_order" triggering on checkout blocks page visit, and introduces some changes regarding multiple draft statuses, making the logic consistent. These changes, although not fixing additional bugs reported are crucial to tackle them in the separate issues https://github.com/woocommerce/woocommerce/issues/48080 https://github.com/woocommerce/woocommerce/issues/48342 https://github.com/woocommerce/woocommerce/issues/48343

Fixes #45145 .

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

### Testing preparation:
1. Install the Code Snippets extension and add the following snippet:

```php
add_action("woocommerce_new_order","any",20,1);
function any($order_id){
    ob_get_clean();
    die("woocommerce_new_order was triggered");
}
```
### Testing "woocommerce_new_order" is NOT triggered when visiting checkout, before actually placing an order 
1. If your cart has items make sure to place a new order to clear any draft order in place
2. Add item(s) to your cart and visit the checkout blocks page
3. Verify the checkout page displays correctly and the text "woocommerce_new_order was triggered" **is NOT displayed**
4. Go to Admin > WooCommerce > Advanced > Features and switch between Wordpress posts storage/High-performance order storage (depending on the previous choice). You might have to sync orders before doing so.
image

5. Repeat steps 1-3

### Testing "woocommerce_new_order" IS triggered when creating an order with completed status
1. Go to WooCommerce > Orders and click "Add order"
2. Edit a new order and select "**Completed**" from the status dropdown. (see note below)
3. Click "Create"  and verify the text "woocommerce_new_order was triggered" **is displayed**
4. Go to Admin > WooCommerce > Advanced > Features and switch between Wordpress posts storage/High-performance order storage (depending on the previous choice). You might have to sync orders before doing so.
image

5. Repeat steps 1-3

**Important note: we're creating an order and marking as Completed because before clicking Create the order already exists in draft, hitting create with a Completed status will trigger a new order action.**

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 
Fixed "woocommerce_new_order" triggering on checkout blocks page visit.

#### Comment 

</details>

### CODE REVIEW

**Review by senadir — CHANGES_REQUESTED** [review]
Wanted to get this PR merged today but it's still missing too many things.

The code only applies to HPOS stores, not regular stores ([see code](https://github.com/woocommerce/woocommerce//blob/7f8747f478c8e305d1c6e211b9066cb9f8282ece/plugins/woocommerce/includes/data-stores/class-wc-order-data-store-cpt.php#L98-L104)).
It fails to trigger the new order hook for orders that were previously draft ([see code](https://github.com/woocommerce/woocommerce//blob/c80cbd77f90ef160f940e75effbf760f228b4eef/plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableDataStore.php#L2597-L2601) and [this code](https://github.com/woocommerce/woocommerce//blob/7f8747f478c8e305d1c6e211b9066cb9f8282ece/plugins/woocommerce/includes/data-stores/class-wc-order-data-store-cpt.php#L193-L197)).

**Comment by wavvves** [comment]
> Wanted to get this PR merged today but it's still missing too many things.
> 
> The code only applies to HPOS stores, not regular stores ([see code](https://github.com/woocommerce/woocommerce//blob/7f8747f478c8e305d1c6e211b9066cb9f8282ece/plugins/woocommerce/includes/data-stores/class-wc-order-data-store-cpt.php#L98-L104)). It fails to trigger the new order hook for orders that were previously draft ([see code](https://github.com/woocommerce/woocommerce//blob/c80cbd77f90ef160f940e75effbf760f228b4eef/plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableDataStore.php#L2597-L2601) and [this code](https://github.com/woocommerce/woocommerce//blob/7f8747f478c8e305d1c6e211b9066cb9f8282ece/plugins/woocommerce/includes/data-stores/class-wc-order-data-store-cpt.php#L193-L197)).


Not sure I follow this, there's no consideration for status strings on the linked example (create order), and the new order action seems to be triggered disregarding the status.

For the [other example](https://github.com/woocommerce/woocommerce//blob/7f8747f478c8e305d1c6e211b9066cb9f8282ece/plugins/woocommerce/includes/data-stores/class-wc-order-data-store-cpt.php#L193-L197) (since one has a broken link, and there's no referenced lines if I try to fix it), I agree with you, it is not considering moving the order from `checkout-draft`, I added it https://github.com/woocommerce/woocommerce/pull/47422/commits/3f959f6fa1f77149f970567a918f2d5494bc44b4

Can you please elaborate on the other two Nadir? Thanks in advance :)

**Review by vedanshujain — COMMENTED** [review]
@wavvves I think what @senadir is referring to here is we would want two separate changes:
1. Not trigger the `woocommerce_new_order` hook when the status is one of the draft ones. You are already doing this for HPOS but not for CPT.
2. Do trigger this hook, when the status is changed from a draft one to a non draft one. You are doing this for CPT but not for HPOS.

Essentially, we should:
- [ ] Prevent triggering this hook for CPT when status is draft. See https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/includes/data-stores/class-wc-order-data-store-cpt.php#L103C15-L103C24
- [x] Prevent triggering this hook for HPOS when status is draft. (You are already doing this)
- [x] Trigger this hook when status is changed from draft to non draft for CPT. (You are already doing this). 
- [ ] Trigger this hook when status is changed from draft to non draft for HPOS. See https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableDataStore.php#L2626. 

Additionally, we should probably make the list of draft statuses consistent, plus maybe add some unit tests around these flows. wdyt?

**Comment by senadir** [comment]
Yeah that's exactly what I had in mind @vedanshujain , just more elegantly from your side

**Comment by senadir** [comment]
Do ping me again for a review once those sections are also handled.

**Comment by wavvves** [comment]
@senadir @vedanshujain Thank you both for your input, things are now much clearer and this PR gained much more importance! What started out as an isolated problem with the "checkout-draft" status has now evolved into a much deeper issue across all draft statuses, namely triggering this hook on CPT disregarding the order status (a draft, no matter what kind will never be a new order) and the tech debt of dragging multiple draft variations across our codebase. 
I am delighted with the outcome of your collaboration on this, on to the adjustments now 💪

PS- I am also updating PR description and title, and will look for any relating issues to link them

**Comment by wavvves** [comment]
Changing the PR to draft until I find the reason why unit testing is failing ⏲️

File: plugins/woocommerce/includes/data-stores/class-wc-order-data-store-cpt.php [hunk 1]
```diff
@@ -100,6 +100,12 @@ public function create( &$order ) {
 			$order->set_order_key( wc_generate_order_key() );
 		}
 		parent::create( $order );
+
+		// Do not fire 'woocommerce_new_order' for draft statuses.
+		if ( in_array( $order->get_status( 'edit' ), array( 'auto-draft', 'draft', 'checkout-draft' ), true ) ) {
```
Comment (vedanshujain) [inline plugins/woocommerce/includes/data-stores/class-wc-order-data-store-cpt.php:105]: should we extract this list into a common method (like we have for paid statuses `wc_get_is_paid_statuses` )?

**Review by vedanshujain — COMMENTED** [review]
Looks good, left a minor comment. Also, can we add unit test for this change? Maybe some thing like hooking a test method and then checking:
1. It's not executed when a new order is created with draft status.
2. It _is_ executed when it's moved to a non-draft status.

File: plugins/woocommerce/includes/data-stores/class-wc-order-data-store-cpt.php (hunk 1 above)
Comment (wavvves) [reply plugins/woocommerce/includes/data-stores/class-wc-order-data-store-cpt.php:105]: I thought about that, ultimately deciding not to at this point as it is used only 2 times, the other condition also uses "new" status 🤔

Comment (wavvves) [reply plugins/woocommerce/includes/data-stores/class-wc-order-data-store-cpt.php:105]: > It's not executed when a new order is created with draft status.
> It is executed when it's moved to a non-draft status.

I created a new issue just for this: https://github.com/woocommerce/woocommerce/issues/48080. This PR was done to prevent this from triggering when checkout is visited and to consolidate behavior between CPT and HPOS.

**Review by senadir — CHANGES_REQUESTED** [review]
This is still not working for me, using the following snippet:

```php
add_action( 'woocommerce_new_order', 'any', 20, 1 );
function any( $order_id ) {
	error_log( 'Order ID: ' . $order_id . ' with status: ' . get_post_status( $order_id ) );
}
```

### On CPT
- Going to Checkout blocks, nothing is logged ✅
- Placing the order, nothing is logged still ❌
- In the admin, creating a new draft order triggers the log with `checkout-draft` status ❌ 
- In the admin, changing an order from draft to completed doesn't trigger anything ❌

### On HPOS
- Going to Checkout, nothing is logged ✅
- Placing the order, a log is triggered with pending status  ✅
- In the admin, creating a new draft order triggers the log with `checkout-draft` status ❌ 
- In the admin, changing an order from draft to completed triggers the log with status completed ✅

**Comment by wavvves** [comment]
> This is still not working for me, using the following snippet:
> 
> ```
> add_action( 'woocommerce_new_order', 'any', 20, 1 );
> function any( $order_id ) {
> 	error_log( 'Order ID: ' . $order_id . ' with status: ' . get_post_status( $order_id ) );
> }
> ```
> 
> ### On CPT
> * Going to Checkout, nothing is logged ✅
> * Placing the order, nothing is logged still ❌
> * In the admin, creating a new draft order triggers the log with `checkout-draft` status ❌
> * In the admin, changing an order from draft to completed doesn't trigger anything ❌
> 
> ### On HPOS
> * Going to Checkout, nothing is logged ✅
> * Placing the order, a log is triggered with pending status  ✅
> * In the admin, creating a new draft order triggers the log with `checkout-draft` status ❌
> * In the admin, changing an order from draft to completed triggers the log with status completed ✅

Thanks for testing this out @senadir! For both "In the admin, creating a new draft order triggers the log with `checkout-draft` status ❌" and "* In the admin, changing an order from draft to completed doesn't trigger anything ❌" is being handled in another issue https://github.com/woocommerce/woocommerce/issues/48080 . Changing from draft to completed is not triggering the hook but it was already triggered when creating the draft order (it goes from draft to checkout-draft, this the bug reported in the mentioned issue).

It was decided to tackle that separately to keep this PR in scope with the original issue, while adding consistency between HPOS and CPT.


"In the admin, changing an order from draft to completed doesn't trigger anything"
I think this one can be added to the above issue too, to keep these order updates. I will use your usecases to complete the issue description.

" Placing the order, nothing is logged still ❌"

I did a little digging, and this only happens in blocks, which means it is our beloved Store API. I will create an issue for that one, too.

This PR has grown to include multiple things discovered in the meantime, it is going way beyond the original issue scope of fixing a misfire of the hook on checkout blocks page :/

**Review by senadir — APPROVED** [review]
It would have been ideal to smack down all combinations in a single issue so it's easier to know what's not working and what's working.

Approving this because it works as expected for HPOS when visiting Checkout and placing an order.

**Comment by vedanshujain** [comment]
Hey @wavvves just checking in, are you planning to add unit tests for this PR? (no worries if it's going to take a bit)

**Comment by wavvves** [comment]
> Hey @wavvves just checking in, are you planning to add unit tests for this PR? (no worries if it's going to take a bit)

Yes, added in https://github.com/woocommerce/woocommerce/pull/47422/commits/85bd02158ec3bc98892703b54e766536124c3751 let's see how those go.
Sorry about the delay, I had a problem with my IDE freezing at 100% CPU usage 🫠

**Review by vedanshujain — APPROVED** [review]
LGTM!
