### PR TITLE
[Accessibility] Make tab elements as direct children of tablist in product page

### LINKED ISSUE #55980: Woocommerce 9.7.0 product TAB's accessibility issue
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Hi there,

Woocommerce 9.7.0 has accessibility issue with product tabs.
https://prnt.sc/Qj5YQ_vF9pFf

ARIA
Elements with an ARIA [role] that require children to contain a specific [role] are missing some or all of those required children.
[role]s are not contained by their required parent element
List items (<li>) are not contained within <ul>, <ol> or <menu> parent elements.

But when I downgrade 9.5.2 it is OK.
https://prnt.sc/oy0enoHVLD9J

fyi.

### Expected behavior

No accessibility issue for sure.

### Actual behavior

accessibility issue on product tabs.

### Steps to reproduce

1. pagespeed tool can show details

### WordPress Environment

Wordpress latest
php 8.3

### Isolating the problem

- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by Manussakis**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes #55980 .

(For Bug Fixes) Bug introduced in PR https://github.com/woocommerce/woocommerce/pull/53158.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Open a product page (test both on Storefront and a WP block-based theme).
2. Open the Dev Tools > Lighthouse
3. Select the following options and analyze the page:
    - Navigation (Default)
    - Desktop
    - Accessibility
image

5. Verify you can not see these errors:

**Error 1**
image

**Error 2**
image

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

**Comment by Manussakis** [comment]
@dkotter This PR is ready for code review.

Notes:
- The failed test doesn't seem to be related to this PR.
- The Highlight Template Changes seem flaky since I indeed updated the template version.

Thanks!

**Review by dkotter — APPROVED** [review]
@ankitguptaindia @qasumitbagthariya This is ready for QA

**Comment by qasumitbagthariya** [comment]
QA / Need Feedback ⚠️
---

@Manussakis 

The error mentioned in the description has been resolved. However, I have noticed something that I share below. I hope it does not have any impact.


image

image

image

**Comment by Manussakis** [comment]
@qasumitbagthariya Thanks for testing it.

The points you flagged are not related to this PR, so we are good to move forward with it.

**Image 1**
Can you please create a task for that? It is likely associated with the theme, but it's worth investigating it.

**Image 2**
I was not able to reproduce it. Can you please create an issue detailing what page and components the issue happens on?

**Image 3**
This is related to WordPress admin and how it uses the role attribute. This won't affect the accessibility report of WooCommerce stores.
image

**Comment by qasumitbagthariya** [comment]
Thanks, @Manussakis for the detailed comment 

I have tested this PR and verified the changes as per the testing instructions. While testing, I identified an issue related to accessibility in the Lighthouse audit.

To track this separately, I have created a new issue: [#56239](https://github.com/woocommerce/woocommerce/issues/56239).

Approving this PR as the reported issue is not directly related to the changes introduced here.

File: plugins/woocommerce/templates/single-product/tabs/tabs.php [hunk 1]
```diff
@@ -33,7 +33,7 @@
 	<div class="woocommerce-tabs wc-tabs-wrapper">
 		<ul class="tabs wc-tabs" role="tablist">
 			<?php foreach ( $product_tabs as $key => $product_tab ) : ?>
-				<li class="<?php echo esc_attr( $key ); ?>_tab" id="tab-title-<?php echo esc_attr( $key ); ?>">
+				<li role="none" class="<?php echo esc_attr( $key ); ?>_tab" id="tab-title-<?php echo esc_attr( $key ); ?>">
```
Comment (samueljseay) [inline plugins/woocommerce/templates/single-product/tabs/tabs.php]: I believe it would be more semantic and more consistent across screen readers to have `role="presentation"` here rather than `role="none"` what do you think?

**Review by samueljseay — CHANGES_REQUESTED** [review]
Some things I tested:

1. tested keyboard navigation with tablist in chromium browser, still works as before ✅ 
2. tested with voiceover + safari + keyboard, there seems to be a tab trap in the page but it's not related to this I saw that happen on trunk too. Voiceover works even a bit better now, announcing that tabs can be selected, a good improvement ✅ 

I just have one suggestion around using a more semantic role of presentation which does much the same as role of none afaik. From what I've read online older screen readers are better / more consistent at handling role of presentation.

File: plugins/woocommerce/templates/single-product/tabs/tabs.php (hunk 1 above)
Comment (Manussakis) [reply plugins/woocommerce/templates/single-product/tabs/tabs.php]: Hey @samueljseay 👋

`role=none` should be correct, but it's not widely supported, as you flagged. Let's keep it as `role=presentation` as recommended by the [WAI-ARIA documentation](https://www.w3.org/TR/wai-aria-1.2/#presentation)

> Note regarding the ARIA 1.1 [none](https://www.w3.org/TR/wai-aria-1.2/#none) role.
In ARIA 1.1, the working group introduced [none](https://www.w3.org/TR/wai-aria-1.2/#none) as a synonym to the presentation role, due to author confusion surrounding the intended meaning of the word "presentation" or "presentational." Many individuals erroneously consider role="presentation" to be synonymous with aria-hidden="true", and we believe role="none" conveys the actual meaning more unambiguously.

> Until implementations include sufficient support for role="none", web authors are advised to use the presentation role alone role="presentation" or redundantly as a fallback to the [none](https://www.w3.org/TR/wai-aria-1.2/#none) role role="none presentation".

Thanks for catching that!

**Comment by vikrampm1** [comment]
@samueljseay this is ready for your re-review!

File: plugins/woocommerce/templates/single-product/tabs/tabs.php (hunk 1 above)
Comment (samueljseay) [reply plugins/woocommerce/templates/single-product/tabs/tabs.php]: Thanks @Manussakis I didn't know it was considered a synonym and I'll keep that in mind for future.

**Review by samueljseay — APPROVED** [review]
Looks good. I already confirmed that role=presentation works. so 🚢

**Comment by vikrampm1** [comment]
@samueljseay thanks. This PR is now ready for you / Woo to merge.

**Comment by betayazilim** [comment]
problem is still happening with latest woocommerce

**Comment by gigitux** [comment]
Thanks for the feedback @ned-bs. Which version of WooCommerce are you running? This patch will land on WooCommerce 9.9 (not released yet)
