### PR TITLE
Fix deleting a tax class via WP CLI.

### LINKED ISSUE #27215: CLI: Using wp wc tax_class ID not listed and delete doesn't work
**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
`wp wc tax_class list --user=1` lists only the _slug_ and _name_ of tax classes, no ID. 

To delete a tax_class the command is listed like so, and ID is required: 
`wp wc tax_class delete <id> [--slug=<slug>] [--force=<force>] [--porcelain]`

The [TAX Classes API](https://woocommerce.github.io/woocommerce-rest-api-docs/#tax-class-properties) has no ID property, as mentioned in the [Forum post](https://wordpress.org/support/topic/wpcli-impossible-to-manage-tax-classes-via-cli/). 

**Expected behavior**

Would expect to see the ID listed when using `wp wc tax_class list --user=1`

**Actual behavior**

ID is not listed with the command's output. 
Also, getting and using the `tax_rate_class_id` from the DB table `wp_wc_tax_rate_classes` directly, this error is displayed in CLI:
`Error: No route was found matching the URL and request method {"status":404}`

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
**Part 1**
1. Go to CLI
2. Run `wp wc tax_class list --user=1`
3. Notice ID column is missing. 
**Part 2**
4. Retrieve `tax_rate_class_id` from db directly 
5. Use that to run `wp wc tax_class delete <id> [--slug=<slug>] [--force=<force>] [--porcelain]`
6. Notice the error as described above.

**Screenshots**
N/a

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report we won't be able to fully evaluate this issue.
<details>
```
`
### WordPress Environment ###

WordPress address (URL): https://woo.tst
Site address (URL): https://woo.tst
WC Version: 4.3.1
REST API Version: ✔ 1.0.10
WC Blocks Version: ✔ 2.7.2
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.3.1
Log Directory Writable: ✔
WP Version: 5.4.2
WP Multisite: –
WP Memory Limit: 999 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.41 (Unix) OpenSSL/1.1.1f PHP/7.4.1
PHP Version: 7.4.1
PHP Post Max Size: 64 MB
PHP Time Limit: 300
PHP Max Input Vars: 1000
cURL Version: 7.67.0
OpenSSL/1.1.1f

SUHOSIN Installed: –
MySQL Version: 5.7.27
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.3.1
WC Database Prefix: wp_
Total Database Size: 7.69MB
Database Data Size: 4.34MB
Database Index Size: 3.35MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.08MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_advanced_notifications: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_advanced_notification_triggers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_automatewoo_abandoned_carts: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_automatewoo_customers: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_automatewoo_customer_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_events: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_guests: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_automatewoo_guest_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_log_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_queue: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_queue_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_referrals: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_automatewoo_referral_advocate_keys: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_automatewoo_referral_invites: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_followup_coupons: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_coupon_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_customers: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_followup_customer_carts: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_customer_notes: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_customer_orders: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_followup_email_excludes: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_email_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_email_orders: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_followup_email_tracking: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_followup_followup_history: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_order_categories: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_order_items: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_subscribers: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_subscribers_to_lists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_subscriber_lists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gf_addon_feed: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_gf_draft_submissions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_gf_entry: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gf_entry_meta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_gf_entry_notes: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gf_form: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gf_form_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gf_form_revisions: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gf_form_view: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 2.02MB + Index: 0.08MB + Engine InnoDB
wp_postmeta: Data: 0.36MB + Index: 0.28MB + Engine InnoDB
wp_posts: Data: 0.09MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_bookings_availability: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_bookings_availabilitymeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_booking_relationships: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_deposits_payment_plans: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_deposits_payment_plans_schedule: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_per_product_shipping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_square_customers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

attachment: 39
aw_workflow: 3
bookable_resource: 2
customize_changeset: 3
nav_menu_item: 6
page: 14
post: 2
product: 58
product_variation: 17
revision: 12
shop_coupon: 3
shop_order: 13
shop_subscription: 9
wc_booking: 4

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 4.3.1

### Inactive Plugins (163) ###

Action Scheduler: by Automattic – 3.1.6
Add Admin CSS: by Scott Reilly – 1.9
Advanced Custom Fields: by Elliot Condon – 5.8.12
Advanced Flat Rate Shipping For WooCommerce: by theDotstore – 4.1 – Installed version not tested with active version of WooCommerce 4.3.1
Affiliate For WooCommerce: by StoreApps – 2.0.0 – Installed version not tested with active version of WooCommerce 4.3.1
Akismet Anti-Spam: by Automattic – 4.1.6
AutomateWoo: by WooCommerce – 5.0.0
AutomateWoo - Birthdays Add-on: by WooCommerce – 1.1.2 – Installed version not tested with active version of WooCommerce 4.3.1
AutomateWoo - Refer A Friend Add-on: by WooCommerce – 2.5.5 – Installed version not tested with active version of WooCommerce 4.3.1
AutomateWoo - Subscriptions Add-on: by Prospress Inc. – 1.0.1 – Installed version not tested with active version of WooCommerce 4.3.1
Bookings Helper: by WooCommerce – 1.0.3 – Installed version not tested with active version of WooCommerce 4.3.1
Bulk Order Form For WooCommerce: by wpexpertsio – 1.1.0 – Installed version not tested with active version of WooCommerce 4.3.1
Catalog mode for woocommerce: by ELEXtensions – 1.0.1 – Installed version not tested with active version of WooCommerce 4.3.1
Classic Editor: by WordPress Contributors – 1.5
CoBlocks: by GoDaddy – 2.0.3
Code Snippets: by Code Snippets Pro – 2.14.0
Codisto LINQ by Codisto: by Codisto – 1.3.51 – Installed version not tested with active version of WooCommerce 4.3.1
Cookie Notice: by dFactory – 1.3.2
Custom User Registration Fields for WooCommerce: by Addify – 1.5.5
Follow-Up Emails: by WooCommerce – 4.9.3 – Installed version not tested with active version of WooCommerce 4.3.1
Free Gifts for WooCommerce: by FantasticPlugins – 5.1 – Installed version not tested with active version of WooCommerce 4.3.1
Fusion Builder: by ThemeFusion – 2.2.2
Fusion Core: by ThemeFusion – 4.2.2
Gantry 5 Framework: by RocketTheme
LLC – 5.4.34

Gravity Forms: by Gravity Forms – 2.4.19
Gravity Forms Advanced Post Creation Add-On: by Gravity Forms – 1.0-beta-4.2
Gutenberg: by Gutenberg Team – 8.5.1
Health Check & Troubleshooting: by The WordPress.org community – 1.4.4
Homepage Control: by WooThemes – 2.0.3
Jetpack by WordPress.com: by Automattic – 8.7
Loco Translate: by Tim Whitlock – 2.4.0
Mailchimp for WooCommerce: by Mailchimp – 2.4.1 – Installed version not tested with active version of WooCommerce 4.3.1
Monkeyman Rewrite Analyzer: by Jan Fabry – 1.0
Pay Fake for WooCommerce: by SkyVerge – 1.0.2 – Installed version not tested with active version of WooCommerce 4.3.1
Perfect WooCommerce Brands: by QuadLayers – 1.8.3 – Installed version not tested with active version of WooCommerce 4.3.1
Point of Sale for WooCommerce: by Actuality Extensions – 5.2.9 – Installed version not tested with active version of WooCommerce 4.3.1
Polylang: by WP SYNTEX – 2.7.4
Post SMTP: by Yehuda Hassine – 2.0.12
Product Filters for WooCommerce: by WooCommerce – 1.2.1 – Installed version not tested with active version of WooCommerce 4.3.1
Products By Attributes & Variations for WooCommerce: by Addify – 1.2.5 – Installed version not tested with active version of WooCommerce 4.3.1
Query Monitor: by John Blackbourn – 3.6.0
Quote Request for WooCommerce: by FantasticPlugins – 1.3 – Installed version not tested with active version of WooCommerce 4.3.1
Request a Quote for WooCommerce: by Addify – 1.5.2 – Installed version not tested with active version of WooCommerce 4.3.1
Sensei LMS: by Automattic – 3.2.0 (update to version 3.3.1 is available)
Sensei with WooCommerce Paid Courses: by Automattic – 3.2.0.2.0.1 – Installed version not tested with active version of WooCommerce 4.3.1
SS4WC - SnapScan for WooCommerce: by Jaco Bah – 0.0.3 – Installed version not tested with active version of WooCommerce 4.3.1
SS4WC - SnapScan for WooCommerce: by Jaco Bah – 0.0.2 – Installed version not tested with active version of WooCommerce 4.3.1
Storefront Homepage Contact Section: by WooThemes – 1.0.5
Storefront Mega Menus: by WooCommerce – 1.6.2 – Installed version not tested with active version of WooCommerce 4.3.1
Storefront Powerpack: by WooCommerce – 1.5.0
Teams for WooCommerce Memberships: by SkyVerge – 1.3.1 – Installed version not tested with active version of WooCommerce 4.3.1
Top Bar for WooCommerce: by Addify – 1.2.2
WC Marketplace: by WC Marketplace
The Grey Parrots – 3.5.3 – Installed version not tested with active version of WooCommerce 4.3.1

Wholesale For WooCommerce: by wpexpertsio – 1.3.3 – Installed version not tested with active version of WooCommerce 4.3.1
Woo All In One Product Slider Carousel: by I Thirteen Web Solution – 1.0.5 – Installed version not tested with active version of WooCommerce 4.3.1
WooCommerce - ShipStation Integration: by WooCommerce – 4.1.22 – Installed version not tested with active version of WooCommerce 4.3.1
WooCommerce Accommodation Bookings: by WooCommerce – 1.1.18 – Installed version not tested with active version of WooCommerce 4.3.1
WooCommerce Additional Variation Images: by WooCommerce – 1.7.23 – Installed version not tested with active version of WooCommerce 4.3.1
WooCommerce Address Validation: by SkyVerge – 2.6.5 – Installed version not tested with active version of WooCommerce 4.3.1
WooCommerce Admin: by WooCommerce – 1.3.0 – Installed version not tested with active version of WooCommerce 4.3.1
WooCommerce Advanced Ajax Layered Navigation: by WooCommerce – 1.4.24 – Installed version not tested with active version of WooCommerce 4.3.1
WooCommerce Advanced Notifications: by WooCommerce – 1.2.26 – Installed version not tested with active version of WooCommerce 4.3.1
WooCommerce Advanced Product Labels: by Jeroen Sormani – 1.1.7 – Installed version not tested with active version of WooCommerce 4.3.1
WooCommerce Advanced Shipping Packages: by Jeroen Sormani – 1.1.7 – Installed version not tested with active version of WooCommerce 4.3.1
WooCommerce Affirm Gateway: by WooCommerce – 1.1.10 – Installed version not tested with active version of WooCommerce 4.3.1
WooCommerce All Products For Subscriptions: by SomewhereWarm – 3.1.14
WooCommerce Australia Post Shipping: by WooCommerce – 2.4.25 – Installed version not tested with active version of WooCommerce 4.3.1
WooCommerce Beta Tester: by WooCommerce – 2.0.1 – Installed version not tested with active version of WooCommerce 4.3.1
WooCommerce Bookings: by WooCommerce – 1.15.23 – Installed version not tested with active version of WooCommerce 4.3.1
WooCommerce Bookings Availability: by WooCommerce – 1.1.13 – Installed version not tested with active version of WooCommerce 4.3.1
WooCommerce Bookings Filters: by Codup – 1.1.3.16 – Installed version not tested with active version of WooCommerce 4.3.1
WooCommerce Box Office: by WooCommerce – 1.1.26 – Installed version not tested with active version of WooCommerce 4.3.1
WooCommerce Braintree Gateway: by SkyVerge – 3.3.3 – Installed version not tested with active version of WooCommerce 4.3.1
WooCommerce Brands: by WooCommerce – 1.6.18 – Installed version not tested with active version of WooCommerce 4.3.1
WooCommerce Bulk Stock Management: by WooCommerce – 2.2.28 – Installed version not tested with active version of WooCommerce 4.3.1
WooCommerce Buy One Get One Free: by Oscar Gare – 2.0.10
WooCommerce Canada Post Shipping: by WooCommerce – 2.5.17 – Installed version not tested with active version of WooCommerce 4.3.1
WooCommerce Catalog Visibility Options: by Lucas Stark – 3.2.10 – Installed version not tested with active version of WooCommerce 4.3.1
WooCommerce Chained Products: by StoreApps – 2.9.6 – Installed version not tested with active version of WooCommerce 4.3.1
WooCommerce Checkout Field Editor: by WooCommerce – 1.5.35 – Installed version not tested with active version of WooCommerce 4.3.1
WooCommerce Composite Products: by SomewhereWarm – 7.0.4
WooCommerce Conditional Shipping and Payments: by SomewhereWarm – 1.8.1 – Installed version not tested with active version of WooCommerce 4.3.1
WooCommerce Customer/Order/Coupon CSV Import Suite: by SkyVerge – 3.8.7 – Installed version not tested with active version of WooCommerce 4.3.1
WooCommerce Customer/Order/Coupon Export: by SkyVerge – 5.0.13 – Installed version not tested with active version of WooCommerce 4.3.1
WooCommerce Deposits: by WooCommerce – 1.5.2 – Installed version not tested with active version of WooCommerce 4.3.1
WooCommerce Disability VAT Exemption: by WooCommerce – 1.4.3 – Installed version not tested with active version of WooCommerce 4.3.1
WooCommerce Distance Rate Shipping: by Automattic – 1.0.24 – Installed version not tested with active version of WooCommerce 4.3.1
WooCommerce Dropshipping: by WooCommerce – 2.4 – Installed version not tested with active version of WooCommerce 4.3.1
WooCommerce Dynamic Pricing: by Lucas Stark – 3.1.19 – Installed version not tested with active version of WooCommerce 4.3.1
WooCommerce Elavon Converge Gateway: by SkyVerge – 2.6.9 – Installed version not tested with active version of WooCommerce 4.3.1
WooCommerce EU VAT Number: by WooCommerce – 2.3.21 – Installed version not tested with active version of WooCommerce 4.3.1
WooCommerce Force Sells: by WooCommerce – 1.1.24 – Installed version not tested with active version of WooCommerce 4.3.1
WooCommerce Freshdesk: by Automattic – 1.1.25 – Installed version not tested with active version of WooCommerce 4.3.1
WooCommerce Gift Cards: by SomewhereWarm – 1.3.5
WooCommerce Global Payments HPP: by SkyVerge – 2.3.7 – Installed version not tested with active version of WooCommerce 4.3.1
WooCommerce GoCardless Gateway: by WooCommerce – 2.4.13 – Installed version not tested with active version of WooCommerce 4.3.1
WooCommerce Google Analytics Integration: by WooCommerce – 1.4.22 – Installed version not tested with active version of WooCommerce 4.3.1
WooCommerce Google Product Feed: by Ademti Software Ltd. – 8.1.3
WooCommerce Gravity Forms Product Add-Ons: by Lucas Stark – 3.3.14 – Installed version not tested with active version of WooCommerce 4.3.1
WooCommerce MailChimp Integration: by WooCommerce – 1.0.4 – Installed version not tested with active version of WooCommerce 4.3.1
WooCommerce Measurement Price Calculator: by SkyVerge – 3.17.5 – Installed version not tested with active version of WooCommerce 4.3.1
WooCommerce Memberships: by SkyVerge – 1.17.5 – Installed version not tested with active version of WooCommerce 4.3.1
WooCommerce Min/Max Quantities: by WooCommerce – 2.4.18 – Installed version not tested with active version of WooCommerce 4.3.1
WooCommerce Mix and Match Products: by Kathy Darling – 1.9.11 – Installed version not tested with active version of WooCommerce 4.3.1
WooCommerce MSRP Pricing: by Ademti Software Ltd. – 2.9.16
WooCommerce Multi-currency: by TIV.NET INC – 2.6.0
WooCommerce Name Your Price: by Kathy Darling – 3.1.1 – Installed version not tested with active version of WooCommerce 4.3.1
WooCommerce One Page Checkout: by Automattic – 1.7.6 – Installed version not tested with active version of WooCommerce 4.3.1
WooCommerce Order Barcodes: by WooCommerce – 1.3.19 – Installed version not tested with active version of WooCommerce 4.3.1
WooCommerce Order Delivery: by Themesquad – 1.6.8 – Installed version not tested with active version of WooCommerce 4.3.1
WooCommerce PayFast Gateway: by WooCommerce – 1.4.15 – Installed version not tested with active version of WooCommerce 4.3.1
WooCommerce Payments: by Automattic – 1.1.0 (update to version 1.2.0 is available) – Installed version not tested with active version of WooCommerce 4.3.1
WooCommerce PayPal Adaptive Payments: by WooCommerce – 1.1.11 – Installed version not tested with active version of WooCommerce 4.3.1
WooCommerce PayPal Checkout Gateway: by WooCommerce – 2.0.3
WooCommerce PayPal Pro (Classic and PayFlow Editions) Gateway: by WooCommerce – 4.5.0 – Installed version not tested with active version of WooCommerce 4.3.1
WooCommerce PDF Invoices: by Andrew Benbow – 4.7.0
WooCommerce PDF Watermark: by WooCommerce – 1.2.1 – Installed version not tested with active version of WooCommerce 4.3.1
WooCommerce Points and Rewards: by WooCommerce – 1.6.34 – Installed version not tested with active version of WooCommerce 4.3.1
WooCommerce Pre-Orders: by WooCommerce – 1.5.27 – Installed version not tested with active version of WooCommerce 4.3.1
WooCommerce Print Invoices/Packing Lists: by SkyVerge – 3.8.6 – Installed version not tested with active version of WooCommerce 4.3.1
WooCommerce Product Add-ons: by WooCommerce – 3.0.36 – Installed version not tested with active version of WooCommerce 4.3.1
WooCommerce Product Bundles: by SomewhereWarm – 6.3.1
WooCommerce Product CSV Import Suite: by WooCommerce – 1.10.35 – Installed version not tested with active version of WooCommerce 4.3.1
WooCommerce Product Reviews Pro: by SkyVerge – 1.15.4 – Installed version not tested with active version of WooCommerce 4.3.1
WooCommerce Product Search: by itthinx – 2.21.0 – Installed version not tested with active version of WooCommerce 4.3.1
WooCommerce Product Vendors: by WooCommerce – 2.1.38 – Installed version not tested with active version of WooCommerce 4.3.1
WooCommerce Royal Mail: by WooCommerce – 2.5.29 – Installed version not tested with active version of WooCommerce 4.3.1
WooCommerce Sales Report Email: by WooCommerce – 1.1.14 – Installed version not tested with active version of WooCommerce 4.3.1
WooCommerce Services: by Automattic – 1.23.2 (update to version 1.24.0 is available) – Installed version not tested with active version of WooCommerce 4.3.1
WooCommerce Shipment Tracking: by WooCommerce – 1.6.23 – Installed version not tested with active version of WooCommerce 4.3.1
WooCommerce Shipping Per Product v2: by WooCommerce – 2.3.10 – Installed version not tested with active version of WooCommerce 4.3.1
WooCommerce Ship to Multiple Addresses: by WooCommerce – 3.6.20 – Installed version not tested with active version of WooCommerce 4.3.1
WooCommerce Smart Coupons: by StoreApps – 4.7.6 – Installed version not tested with active version of WooCommerce 4.3.1
WooCommerce SnapScan Gateway: by WooCommerce – 1.1.9 – Installed version not tested with active version of WooCommerce 4.3.1
WooCommerce Software Add-On: by WooCommerce – 1.7.15 – Installed version not tested with active version of WooCommerce 4.3.1
WooCommerce Splash Popup: by WooCommerce – 1.2.17 – Installed version not tested with active version of WooCommerce 4.3.1
WooCommerce Square: by WooCommerce – 2.1.5 (update to version 2.1.6 is available) – Installed version not tested with active version of WooCommerce 4.3.1
WooCommerce Stamps.com API integration: by WooCommerce – 1.3.19 – Installed version not tested with active version of WooCommerce 4.3.1
WooCommerce Stripe Gateway: by WooCommerce – 4.5.0 – Installed version not tested with active version of WooCommerce 4.3.1
WooCommerce Subscriptions: by WooCommerce – 3.0.5 – Installed version not tested with active version of WooCommerce 4.3.1
WooCommerce Subscriptions Gifting: by WooCommerce – 2.1.1 – Installed version not tested with active version of WooCommerce 4.3.1
WooCommerce Subscriptions No $0 Emails: by  – 0.1 – Installed version not tested with active version of WooCommerce 4.3.1
WooCommerce Sync for QuickBooks Online - by MyWorks Software: by MyWorks Software – 2.1 – Installed version not tested with active version of WooCommerce 4.3.1
WooCommerce Table Rate Shipping: by WooCommerce – 3.0.28 – Installed version not tested with active version of WooCommerce 4.3.1
WooCommerce UPS Shipping: by WooCommerce – 3.2.27 – Installed version not tested with active version of WooCommerce 4.3.1
WooCommerce USPS Shipping: by WooCommerce – 4.4.45 – Installed version not tested with active version of WooCommerce 4.3.1
WooCommerce Variation Swatches and Photos: by Lucas Stark – 3.1.1 – Installed version not tested with active version of WooCommerce 4.3.1
WooCommerce Waitlist: by Neil Pie – 2.1.23 – Installed version not tested with active version of WooCommerce 4.3.1
WooCommerce Warranty Requests: by WooCommerce – 1.9.16 – Installed version not tested with active version of WooCommerce 4.3.1
WooCommerce WishLists: by Lucas Stark – 2.2.0 – Installed version not tested with active version of WooCommerce 4.3.1
WooCommerce Xero Integration: by WooCommerce – 1.7.32 – Installed version not tested with active version of WooCommerce 4.3.1
WooCommerce Zapier: by OM4 – 2.0.4 – Installed version not tested with active version of WooCommerce 4.3.1
WooSlider: by WooThemes – 2.4.0
WooSlider - WooCommerce Products Slideshow: by WooCommerce – 1.0.20 – Installed version not tested with active version of WooCommerce 4.3.1
WordPress Beta Tester: by Peter Westwood
Andy Fragen – 2.2.10

WordPress Importer: by wordpressdotorg – 0.7
WP Crontrol: by John Blackbourn & crontributors – 1.8.5
WPC Variations Radio Buttons for WooCommerce: by WPClever.net – 2.1.2 – Installed version not tested with active version of WooCommerce 4.3.1
WP Job Manager: by Automattic – 1.34.2
WP Job Manager - WooCommerce Paid Listings: by Automattic – 2.8.3 – Installed version not tested with active version of WooCommerce 4.3.1
WPML Multilingual CMS: by OnTheGoSystems – 4.3.12
WPML Multilingual CMS: by OnTheGoSystems – 4.3.12
Yoast SEO: by Team Yoast – 14.5 – Installed version not tested with active version of WooCommerce 4.3.1

### Must Use Plugins (1) ###

Health Check Troubleshooting Mode: by  – 1.7.0

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left_space
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: booking (booking)
external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #6 - /shop/
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 2.5.8
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 159
Oldest: 2020-07-23 13:30:29 +0000
Newest: 2020-08-04 07:11:23 +0000

Pending: 5
Oldest: 2020-08-04 07:30:56 +0000
Newest: 2021-08-01 13:01:34 +0000

`
```
</details>

### PR DESCRIPTION
**Pull request by rrennick**
### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

This PR adds `GET` support for an individual tax class and fixes deleting a tax class via WP CLI 
Closes #27215 .

### How to test the changes in this Pull Request:

1. Create two new test tax classes via the REST API (eg. `{"name":"Sample Tax"}`)
2. Retrieve the tax classes to verify `/wp-json/wc/v3/taxes/classes`
3. `wp wc tax_class list --user=1`
4. `wp wc tax_class delete example-tax --force=true --user=1`
5. Check both REST API and WP CLI to verify the tax class was removed

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Fix - Fixed WP CLI command to delete tax classes.

### CODE REVIEW

File: includes/rest-api/Controllers/Version1/class-wc-rest-tax-classes-v1-controller.php [hunk 1]
```diff
@@ -40,43 +38,56 @@ class WC_REST_Tax_Classes_V1_Controller extends WC_REST_Controller {
...
+					'slug' => array(
+						'description' => __( 'Unique slug for the resource.', 'woocommerce' ),
+						'type'        => 'string',
 					),
 				),
-			),
-			'schema' => array( $this, 'get_public_item_schema' ),
-		) );
+				array(
+					'methods'             => WP_REST_Server::READABLE,
```
Comment (claudiosanches) [inline includes/rest-api/Controllers/Version1/class-wc-rest-tax-classes-v1-controller.php:72]: We should move it for Version 3, since this version is outdated already, and this is a inclusion.
Also WP-CLI uses the latest version of our REST API.

**Review by claudiosanches — CHANGES_REQUESTED** [review]
Works great, but I think we should implement it only in REST API v3.

File: includes/rest-api/Controllers/Version1/class-wc-rest-tax-classes-v1-controller.php (hunk 1 above)
Comment (rrennick) [reply includes/rest-api/Controllers/Version1/class-wc-rest-tax-classes-v1-controller.php]: The target version is `v2` in https://github.com/woocommerce/woocommerce/blob/master/includes/cli/class-wc-cli-runner.php#L51. Move to `v2` in `2fd1260`.

**Review by claudiosanches — DISMISSED** [review]
Works great!

**Review by jonathansadowski — DISMISSED** [review]
Tested the behavior before and after this PR, and verified that before this, I was unable to delete a tax class by slug via WP CLI. After applying this PR, I am able to delete tax classes by slug. Nice work.

**Review by claudiosanches — APPROVED** [review]

**Review by jonathansadowski — APPROVED** [review]
