### PR TITLE
Fix for product meta lookup table incorrectly marking a product as onsale Closes #43008

### LINKED ISSUE #43008: Product meta lookup table incorrectly shows product on sale
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

If i product has its `_sale_price` and `_regular_price` the same then `_price` will also be the same. `$product->is_on_sale()` will correctly return false as it checks against the regular price but the lookup table will show on sale as it ignores the regular price and just checks if the `_price` is the same as the `_sale_price`

It may be incorrect to have all 3 prices be the same, but it can happen and it will cause this behavior. In my case its not in my control as we are working with a company which integrates our products/inventory with another system (which is where prices are configured) I have an issue opened with them as well to not populate the `_sale_price` meta field when its the same. but regardless i think this should also be fixed here

### Expected behavior

`wp_wc_product_meta_lookup.onsale` should be 0 when `$product->is_on_sale()` is false

### Actual behavior

`wp_wc_product_meta_lookup.onsale` can sometimes be 1 when `$product->is_on_sale()` is false

### Steps to reproduce

set regular_price, price, and sale_price to the same value and generate lookup tables`

### WordPress Environment

N/A

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by pintend**
Determine if a product is on sale based on regular price, which is how its done in the WC_Product class https://github.com/woocommerce/woocommerce/blob/7122669d448acb90d0f8a7177b76baaccec2e76b/plugins/woocommerce/includes/abstracts/abstract-wc-product.php#L1634

Currently `$product->is_on_sale() == false` when `_regular_price` and `_sale_price` are the same, but the product lookup table ignores the `_regular_price` and only checks that `_price` and `_sale_price` are the same.

### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes https://github.com/woocommerce/woocommerce/issues/43008 .

### How to test the changes in this Pull Request:

1. Create a simple test product in WC > Products. Make sure it's not "on sale" and take note of its ID.
1. Force an update of the meta lookup table by running `wp eval "wc_update_product_lookup_tables_column( 'onsale' );"`.
1. Confirm the product is not on sale in the lookup table:
   ```
   > wp db query "SELECT onsale FROM $(wp db prefix)wc_product_meta_lookup WHERE product_id = <product_id>;"
   +--------+
   | onsale |
   +--------+
   |      0 |
   +--------+
   ```
1. Now go back and edit the product and set a sale price.
1. Confirm that the product appears on sale in the lookup table:
   ```
   > wp db query "SELECT onsale FROM $(wp db prefix)wc_product_meta_lookup WHERE product_id = <product_id>;"
   +--------+
   | onsale |
   +--------+
   |      1 |
   +--------+
   ```
1. To simulate the product having `regular_price`, `sale_price` and `price` all set to the same value run the following command:
   ```shell
   wp post meta update <product_id> _sale_price `wp post meta get <product_id> _regular_price`
   wp post meta update <product_id> _price `wp post meta get <product_id> _regular_price`
   ```
   Not that this is only to expedite testing, but this is in fact possible via the admin UI if one disables frontend validation (for example, by disabling JS).
4. Force (again) an update of the meta lookup table by running `wp eval "wc_update_product_lookup_tables_column( 'onsale' );"`.
5. Confirm that the product is not marked as being on sale in the lookup tables:
   ```
   > wp db query "SELECT onsale FROM $(wp db prefix)wc_product_meta_lookup WHERE product_id = <product_id>;"
   +--------+
   | onsale |
   +--------+
   |      0 |
   +--------+
   ```

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 
Use regular_price to determine if product is not sale and don't rely only on price for product_meta_lookup
#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce/includes/wc-product-functions.php [hunk 1]
```diff
@@ -1565,11 +1565,13 @@ function wc_update_product_lookup_tables_column( $column ) {
 						{$wpdb->wc_product_meta_lookup} lookup_table
 						LEFT JOIN {$wpdb->postmeta} meta1 ON lookup_table.product_id = meta1.post_id AND meta1.meta_key = '_price'
 						LEFT JOIN {$wpdb->postmeta} meta2 ON lookup_table.product_id = meta2.post_id AND meta2.meta_key = '_sale_price'
+	  					LEFT JOIN {$wpdb->postmeta} meta3 ON lookup_table.product_id = meta3.post_id AND meta3.meta_key = '_regular_price'
 					SET
 						lookup_table.`{$column}` = IF (
 							CAST( meta1.meta_value AS DECIMAL ) >= 0
 							AND CAST( meta2.meta_value AS CHAR ) != ''
 							AND CAST( meta1.meta_value AS DECIMAL( 10, %d ) ) = CAST( meta2.meta_value AS DECIMAL( 10, %d ) )
+							AND CAST( meta3.meta_value AS DECIMAL( 10, %d ) ) > CAST( meta2.meta_value AS DECIMAL( 10, %d ) )
```
Comment (jorgeatorres) [inline plugins/woocommerce/includes/wc-product-functions.php:1571]: We are adding two more placeholders (`%d`) with this change, so we need to add the corresponding variables (`$decimals`) to the `$wpdb->prepare()` call.

**Review by jorgeatorres — CHANGES_REQUESTED** [review]
Hi @pintend!

Thanks for your contribution 💯. I left some feedback regarding a tiny change that we would need to make in order for this to work as intended.

Let me know what you think!

**Review by pintend — COMMENTED** [review]
did i miss that in the commit? i had it in my test query `AND CAST(meta3.meta_value AS DECIMAL(10, 2)) > CAST(meta2.meta_value AS DECIMAL(10, 2))`

**Comment by jorgeatorres** [comment]
@pintend: You did use `DECIMAL(10, 2)` in the testing instructions, but the code itself uses a placeholder for the decimal places (`%d`) which is correct, but then you need to provide the actual value.

https://github.com/woocommerce/woocommerce/blob/0fd0c8e9d406f178c9d1c3da2cfb5a3b63d1a290/plugins/woocommerce/includes/wc-product-functions.php#L1571-L1578

**Comment by jorgeatorres** [comment]
Hey @pintend,

Thanks for making the changes. I was testing this again and now I'm wondering where the original bug came from. Using the `set_price()`, `set_regular_price()` and `set_sale_price()` functions I can't set a sale price that is equal to the price/regular price. In all cases, the `price` property updates to the proper amount, which is what the lookup table uses (as you mentioned).

We recently merged fixes related to product sales, so something might've changed.

Is there a way to reproduce this that doesn't involve changing the metadata directly in the database? This is not necessarily supported. Hardening the lookup update might still make sense, but I'd like to understand if there's something else we're missing.

**Comment by pintend** [comment]
@jorgeatorres: The issue started when a 3rd party plugin created and updated product records directly in the db, although the issue _should_ really be fixed in that plugin (which I don't have control over) I don't see the harm "fixing" it here as well, especially when in the application this is the method it uses to determine if its on sale... might as well keep the logic consistent.

Although the functions dont allow a developer to create this issue, some developers might and do go around those helper functions. adding this extra check should be a safe change that protects from that even if its "useless" for most cases

> if the `sale_price` is not blank and `regular_price` is more than the `sale_price`
https://github.com/woocommerce/woocommerce/blob/7122669d448acb90d0f8a7177b76baaccec2e76b/plugins/woocommerce/includes/abstracts/abstract-wc-product.php#L1634

> if the `sale_price` is not blank and the `price` and `sale_price` are equal 
https://github.com/woocommerce/woocommerce/blob/7122669d448acb90d0f8a7177b76baaccec2e76b/plugins/woocommerce/includes/wc-product-functions.php#L1572

my change:  
> if the `sale_price` is not blank and `regular_price` is more than the `sale_price` and the `price` and `sale_price` are equal
https://github.com/woocommerce/woocommerce/blob/7263053535bb5d5d46cdf05c82219ac3980cc56a/plugins/woocommerce/includes/wc-product-functions.php#L1574

it make it more consistent and prevents the issue from other plugins

**Review by jorgeatorres — APPROVED** [review]
LGTM. Thanks for your patience here @pintend and for this fix. It works great.

FYI I edited the first comment by adding some testing instructions to make it easier for our team to confirm this is working correctly.
