### PR TITLE
Prevent shipping tax fallback to standard tax rates when inheriting tax class from cart items

### LINKED ISSUE #58757: Shipping tax class based on cart items does not appear to be working
## **Describe the bug**

When using the setting `shipping tax class based on cart items` with a single, reduced tax class item in the cart, shipping tax continues to apply standard rates.

In addition, when paying with an Express Payment method, The amount charged will not match the amount displayed on the order after completion.

The Express Payment method will charge the standard rate tax for shipping, but the order will reflect a total without shipping (as should have been charged) BUT will include shipping tax in the subtotals (ie totals do not add up to order total).

## **To Reproduce**

1. Set product to reduced rates tax class
2. Setup a 10% tax rate which includes shipping as a standard rate
3. Set up a 5% tax rate which excludes shipping as a reduced rate
4. Set Shipping tax to shipping tax class based on cart items
5. Checkout. When paying with credit card, the thank you page will show the full (incorrect) amount paid
6. Checkout again with an Express Payment method. The Thank you page and order will not show the amount paid.

## **Expected behavior**

I expect the shipping tax rate from reduced tax class to be assigned

## **Screenshots**

If applicable, add screenshots to help explain your problem. (or upload as files via Asks)

## Environment

Please fill out any of the below that applies

**Operating System/Device**

- [ ] Windows
- [ ] MacOS
- [ ] Linux
- [ ] iPhone
- [ ] Samsung
- [ ] Other (add in additional context field)

**Version:** Add the Desktop OS and/or Device version(s) here

**Browser**

- [ ] Desktop Edge
- [ ] Desktop Chrome/Chromium
- [ ] Desktop Safari
- [ ] Mobile Edge
- [ ] Mobile Chrome/Chromium
- [ ] Mobile Safari
- [ ] Other (add in additional context field)

**Version:** Add the browser version(s) here.

## **Additional context**

This issue will be published publicly, add system status report and internal links to Slack thread after issue created.

### PR DESCRIPTION
**Pull request by mikejolley**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

When shipping tax is set to "inherit from cart items" and cart contains items with a tax class that doesn't have shipping tax enabled (e.g., reduced-rate with shipping checkbox unchecked), the system was incorrectly falling back to standard shipping tax rates instead of applying no shipping tax.

Root Cause: The get_shipping_tax_rates() method had fallback logic that would use standard rates when no shipping rates were found for the inherited tax class, which defeated the purpose of tax class inheritance.

Fix: Removed the fallback logic so that when a tax class doesn't have shipping tax enabled, no shipping tax is applied (returns empty array). This ensures that the administrator's intent is respected - if they don't check the "Shipping" checkbox for a tax rate, no shipping tax should be charged for that tax class.

Impact: Fixes the bug described in GitHub issue #58757 where customers were being charged incorrect shipping tax amounts.

Fixes #58757

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Create a standard tax rate of 20%. Check the "shipping" box for the rate.
2. Create a reduced tax rate of 5%. Uncheck the "shipping" box for the rate.
3. No other rates defined.
4. Tax > Tax Options > Shipping tax class > Shipping tax class based on cart items
5. Create one shipping option worldwide. Flat rate.
6. Create a product with assigned tax class of reduced rate
7. Add said product to cart.
8. The product should be taxed, but the shipping should not.
9. Place order.
10. Ensure the order totals match what was in the cart.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

**Comment by straku** [comment]
First some notes from my manual testing as they're fresh in my head.

For me, it's not super clear what should happen when we have this setting:

Screenshot 2025-07-03 at 17 38 59

Alongside a cart consisting of items with tax rate with shipping disabled:

Screenshot 2025-07-03 at 17 39 12

You are definitely applying a saner default and what is currently on `trunk` is broken, but it was not clear to me based on the labels and explanations within the setting what is going on. For me, having shipping disabled on a tax rate means "don't apply this tax rate to shipping ever", not "don't apply any tax rate to shipping" (which is what can happen with "Shipping tax class based on cart items" set).

This is just an observation, I don't think I have any alternative to offer 🫠 Maybe when "Shipping tax class based on cart items" is set we should have another input that would control the fallback behavior. By fallback, I mean – what should happen when items in the cart don't have any tax rates that can be applied to shipping?

File: plugins/woocommerce/includes/class-wc-tax.php [hunk 1]
```diff
@@ -549,11 +549,22 @@ public static function get_shop_base_rate( $tax_class = '' ) {
...
+	 * This method determines which tax rates to apply to shipping costs by following this priority:
+	 * 1. Uses the explicitly configured shipping tax class from WooCommerce settings if not set to 'inherit'
+	 * 2. If tax_class is provided (per-item shipping), uses that specific class
+	 * 3. If no tax_class provided (per-order shipping), analyzes cart items to determine the appropriate class:
+	 *    - Returns empty array if cart has no taxable items
+	 *    - For multiple tax classes: prioritizes standard rate, then uses first class found in tax class hierarchy
+	 *    - For single tax class: uses that class directly
+	 * 4. Returns only rates that have shipping tax enabled for the determined tax class
+	 *    - If no shipping rates exist for the tax class, returns empty array (no fallback to standard rates)
+	 *    - This ensures tax class inheritance works correctly - if a tax class doesn't apply to shipping, no shipping tax is charged
```
Comment (straku) [inline plugins/woocommerce/includes/class-wc-tax.php:563]: 👏

File: plugins/woocommerce/includes/class-wc-tax.php [hunk 2]
```diff
@@ -563,80 +574,85 @@ public static function get_shipping_tax_rates( $tax_class = null, $customer = nu
...
-				);
+		foreach ( $tax_class_slugs as $tax_class_slug ) {
+			if ( in_array( $tax_class_slug, $cart_tax_classes, true ) ) {
+				return $tax_class_slug;
 			}
 		}
 
-		return $matched_tax_rates;
+		// Default to standard tax class if nothing else matches.
+		return $standard_tax_class;
```
Comment (straku) [inline plugins/woocommerce/includes/class-wc-tax.php:655]: As far as I understood, it is impossible to get here if everything is configured (and working) properly. We would have to get a complete mismatch between tax rates that we have in the cart and the ones configured in the settings.

Returning standard tax rate is a safe fallback, but feels like admitting something is very wrong but still continuing "normally". Should we return the first tax rate from the cart instead? Or throw/log (I am not yet aware of our capabilities in this matter)?

**Review by straku — APPROVED** [review]
I really like the clarity of the new approach and the way you've implemented it. The code is very easy to read. Thanks for the thorough testing suite and great inline docs (and the opportunity for me to set up taxes in Woo for the first time 😅).

Apart from the code review and following testing steps that you provided, I tried a mix of all the settings, with some custom tax rates applied (with shipping on/off) and all worked nice.

I am a bit worried that this fix might seem like a breaking change for some. This comes mostly from my initial experience with all the settings that I described [here](https://github.com/woocommerce/woocommerce/pull/59324#issuecomment-3032765703). It's not easy to build a mental model of what is going on.

File: plugins/woocommerce/includes/class-wc-tax.php (hunk 2 above)
Comment (mikejolley) [reply plugins/woocommerce/includes/class-wc-tax.php:655]: Its true it shouldn't happen, unless a cache is stale or something strange like that.

I don't think we can throw as that would definitely break customer facing views. Standard feels like the safest default, otherwise we could return null and skip altogether. Which do you prefer?

**Comment by mikejolley** [comment]
> For me, having shipping disabled on a tax rate means "don't apply this tax rate to shipping ever", not "don't apply any tax rate to shipping" (which is what can happen with "Shipping tax class based on cart items" set).

It is the former, because you can have tax rates that apply to shipping defined as well alongside. e.g. if there was a slightly different tax rate for shipping reduced rate, you'd have another rate defined here with the same priority as the other one, but with shipping checked. So I think that part is ok.

> Maybe when "Shipping tax class based on cart items" is set we should have another input that would control the fallback behavior. By fallback, I mean – what should happen when items in the cart don't have any tax rates that can be applied to shipping?

I think given you can define a tax rate for the shipping separate to the others, and the control you have which class gets applied to shipping in the first place, a fallback shouldn't be necessary.

I added a comment about the default tax class @straku Ill wait for your reply before merging.

File: plugins/woocommerce/includes/class-wc-tax.php (hunk 2 above)
Comment (straku) [reply plugins/woocommerce/includes/class-wc-tax.php:655]: I will leave it up to you, let's pick whatever we tend to do in cases like this. I am assuming your experience steered you toward this choice, so I would leave it like that.

**Comment by straku** [comment]
@mikejolley Yeah, it's definitely an edge-case scenario when your cart consists only of items with a tax rate that doesn't apply to shipping, alongside the setting to derive tax rate for shipping from the cart. Still, presented with these criteria, it feels a bit weird to not apply any tax to shipping 🤷‍♂️

**Comment by mikejolley** [comment]
@straku Given the shipping tax boxes are checked by default, I think you'd have to be pretty intentional about that setup. Ill put it a different way, if we apply tax like we did before, **there is no way to prevent the fallback**. With the fixed system you can choose either way. So while the behaviour has changed, its more flexible this way and should account for those setups as reported in the original issue.

Thanks for checking. I will push the button.
