### PR TITLE
Fix: show correct attribute and price filter data on the category/tag template

### LINKED ISSUE #42542: Product Query: [Filters] When inside a Product by Category template using a Filter by Attribute, non-pertaining attributes can be selected
> **Warning**
> In order to reproduce this bug, woocommerce/woocommerce-blocks#7382 is suggested

## Describe the bug

If a “Filter by Attribute” block is added within a “Products by Category” template, it shows all attributes available even if not pertaining to that category.

In combination with the normal classic block, it produces a mismatch between the data shown in the filter block and the classic block (similar, but different from https://github.com/woocommerce/woocommerce-blocks/issues/7607).

When combined the “Product Query” block with the “inherit query from template option”, it allows products from different categories to be displayed inside another category (e.g. a yellow cap inside the t-shirts category, as shown in the screenshot).

Also be aware of https://github.com/woocommerce/woocommerce-blocks/issues/7604 when reproducing this issue.

## To reproduce

Steps to reproduce the behavior with WooCommerce default sample data:

1. Add a “Filter by Attribute” block to the “Products by Category” template.
2. Go to a specific category, such as “T-shirts”.
3. Notice that the filter block shows attributes not available in the “T-shirts” category, such as “Yellow (1)”.

Optionally:

1. Make sure woocommerce/woocommerce-blocks#7382 is merged.
2. Add a “Product Query” block with “inherit query from template” option.
3. Repeat the steps above and select “Yellow”.
4. Notice you'll have a cap inside the t-shirts category.

## Screenshots

Screenshot 2022-11-08 at 02 26 51

### PR DESCRIPTION
**Pull request by normana10**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

_Partially_  fixes #42542 (product filters within the category template are not limited to _just_ that category)

The backend endpoints for calculating the price range _already_ support filtering by category, this PR _just_ changes the price filter block to include the category ID in it's request

(The way I'm currently grabbing the category ID is _cursed_. Surely someone knows of an better way to get the ID of the current category within the Category template?)

#### Before changes

1. Set a product's price to something quite high (below example has set the `WordPress Pennant` to a price of $1,000)
2. Add a price filter to the category template and the shop template
3. Go to a category that does _not_ include the product modified in step 1 (below example is "Clothing")
4. Observe that the price filter includes products _not_ within the current category

image

#### After changes

1. Same steps as above
2. Observe that the price filter in the Category template accurately reflects _only_ products within that category 
3. Return to the "shop" page
4. Observe that the price filter correctly displays the price range _including_ the very expensive item

image
image

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message

Fix: show correct attribute and price filter data on the category/tag template.

</details>

### CODE REVIEW

File: plugins/woocommerce-blocks/assets/js/blocks/price-filter/block.tsx [hunk 1]
```diff
@@ -71,6 +71,14 @@ function formatPrice( value: unknown, minorUnit: number ) {
...
 }
 
+// TODO There *has* to be a better way of getting this... Currently depending on `body` to get the `term-XYZ` CSS class...
+const getCategoryId = () =>
+	// @ts-ignore TS doesn't think `DOMTokenList` is iterable?
+	[ ...document.body.classList ]
+		.map( ( className ) => /term-(\d+)/.exec( className ) )
+		.filter( ( match ) => match !== null )
+		.map( ( match ) => match[ 1 ] )[ 0 ];
+
```
Comment (normana10) [inline plugins/woocommerce-blocks/assets/js/blocks/price-filter/block.tsx]: This is the cursed bit of code I'm hoping someone can point me at a better way of doing?

We literally _just_ need the current category ID, but I couldn't find any hooks/etc that would provide that to me?

Comment (WunderBart) [reply plugins/woocommerce-blocks/assets/js/blocks/price-filter/block.tsx]: Not sure if there's a better way of fetching that data apart maybe from shortening the above to `document.body.className.match(/term-(\d+)/)[1]`, but I understand we don't want to rely on the class prop here. Possibly @dinhtungdu or @gigitux will have some more insight here! 🙏

Comment (normana10) [reply plugins/woocommerce-blocks/assets/js/blocks/price-filter/block.tsx]: Makes sense to me

Changed

Comment (gigitux) [reply plugins/woocommerce-blocks/assets/js/blocks/price-filter/block.tsx]: Thanks for working on this block and improving it!

I completely agree with you; we should revisit this approach mostly because any JS script can manipulate that class.

What do you think about enqueuing the category ID on the PHP side? You can do this adding to the [`PriceFilter.php`](https://github.com/woocommerce/woocommerce/blob/ac9f47cb8dcf44c80c5fa95c3d6127119d9a6495/plugins/woocommerce/src/Blocks/BlockTypes/PriceFilter.php/#L20-L31), this function:

```php
	/**
	 * Extra data passed through from server to client for block.
	 *
	 * @param array $attributes  Any attributes that currently are available from the block.
	 *                           Note, this will be empty in the editor context when the block is
	 *                           not in the post content on editor load.
	 */
	protected function enqueue_data( array $attributes = [] ) {
		$category = get_queried_object();
		$cat_id   = $category->term_id;
		$this->asset_data_registry->add( 'categoryId', $cat_id );
	}
```


You can retrieve this value on the frontend with `getSettingWithCoercion` function. In the [`block.tsx`](https://github.com/woocommerce/woocommerce/blob/ac9f47cb8dcf44c80c5fa95c3d6127119d9a6495/plugins/woocommerce-blocks/assets/js/blocks/price-filter/block.tsx/#L140-L141), you can add these lines:

```js
const categoryId = getSettingWithCoercion( 'categoryId', null, isNumber );

```

This code is just a POC, we should ensure that we enqueue data only on the frontend. You can test different approach like using `is_admin` or `is_archive` checks on the `enqueue_data` function.

Also, I want to highlight that we are working on new enhancement block filters. Feel free to check them and leave feedback: https://github.com/woocommerce/woocommerce/issues/46142

Comment (normana10) [reply plugins/woocommerce-blocks/assets/js/blocks/price-filter/block.tsx]: Thanks for the suggestion @gigitux 

I was completely unaware of `enqueue_data` and that seems like _exactly_ what I was looking for

Changes made

**Comment by gigitux** [comment]
Thanks for addressing the feedback! Code-wise, this PR LGTM, I have some concerns about the minimum price.


| Trunk | PR |
|--------|--------|
| image | image | 


In this PR, the minimum price isn't 0, instead, there is a price that doesn't look correct:


https://github.com/user-attachments/assets/f9bebf36-f394-4ad8-8dfb-4a519180cf35


For the min price, I would not change the trunk beavhiour. What do you think?

File: plugins/woocommerce-blocks/assets/js/blocks/price-filter/block.tsx [hunk 2]
```diff
@@ -112,8 +113,14 @@ const PriceFilterBlock = ( {
...
+		'categoryId',
+		undefined,
+		isNumber
+	);
 	const { results, isLoading } = useCollectionData( {
 		queryPrices: true,
+		...( queryCategory && { queryCategory } ),
 		queryState,
 		isEditor,
 	} );
```
Comment (dinhtungdu) [inline plugins/woocommerce-blocks/assets/js/blocks/price-filter/block.tsx]: `useCollectionData` [supports](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/src/StoreApi/docs/product-collection-data.md) all product list attributes, including `category`. So instead of modifying the hook, you can pass the category ID directly here, like this:

```js
	const { results, isLoading } = useCollectionData( {
		queryPrices: true,
		queryState: {
			...queryState,
			category: queryCategory,
		},
		isEditor,
	} );

```

**Review by dinhtungdu — COMMENTED** [review]
Thanks for working on the PR. This PR is testing well following the instructions. Apart from review comments, I have concerns about merging this PR at its current state.

This PR only fixes the Price Filter, so if on the category page, merchants use other filter blocks (Attribute, for example), that block will still show incorrect attribute data that doesn't match products in the category (it shows data for all products). The same applies to other filter blocks. So if we fix it for the Price filter, should we fix it for other filter blocks too?

Also, what about tag or search results pages? We may not want to do everything all at once, but if we want to support tag and other pages in the future, what should we implement this fix to support that purpose?

What I'd do, is instead of passing only category ID from the server side, we pass a partial query object. By doing so, when we fix the same issue for tag pages, we only need to modify that object and don't have to touch the block component. What do you think?



> In this PR, the minimum price isn't 0, instead, there is a price that doesn't look correct:

> For the min price, I would not change the trunk beavhiour. What do you think?

@gigitux the behavior is still the same as the `trunk`, you see different minimum price because the product set in the category is now limited to that category only. While with `trunk`, the price filter shows data for all products.

**Comment by gigitux** [comment]
> you see different minimum price because the product set in the category is now limited to that category only.


This makes sense, but currently, it looks broken. I would always expect to see at least one product. In the attached video, I set the max price to 14, and I got 0 products found.

File: plugins/woocommerce-blocks/assets/js/blocks/price-filter/block.tsx (hunk 2 above)
Comment (normana10) [reply plugins/woocommerce-blocks/assets/js/blocks/price-filter/block.tsx]: Tested and working, will push it up

**Comment by normana10** [comment]
@gigitux 

Oh weird I can replicate

_Some time later_

Oooh, ok so this is due to `usePriceConstraint`

We're passing the response from `useCollectionData` (min of 15 and max of 25) into `usePriceConstraint` and it's rounding the min down to 10 and the max up to 30

Seems like _this block_ is `usePriceConstraint`'s only usage (so I suppose we can change the default if we like without worry of impacting anything else)

I could understand rounding to maybe the nearest _whole_ number, rounding to the nearest 10 seems a bit much, but that _sounds_ like something we should leave up to the user via a config (maybe in _another_ PR?)

We think it would be reasonable to round to the nearest _whole_ number by default?

As I agree it's a bit weird to be able to get the filter into a state that matches _no_ products. _Granted_ even if we _did_ only round to whole numbers a customer _could_ presumably set the filter to like 13-14, which would also match no products 🤷‍♂️ 

But (in my opinion) it's way more annoying to go, "Ok show me products 10-15" where the lowest product is like 18 and you just get _nothing_ back as opposed to setting _both_ the min and max so close together it matches nothing (customer needed to make _multiple_ actions to get into that state)

I suppose it's a decision between making the filter more "useful" (showing the _actual_ min/max) and more "pretty" (showing nice round numbers)


@dinhtungdu

Agree that it may be weird that the _other_ filters don't respect the current category

I was going to go try my hand at fixing the _attribute_ filter next as that's the other main filter I use and it's annoying it isn't scoped to the current category

I did the price filter first because I thought it would be a trivial win (since the `collection-data` endpoint supports being passed category ids)

Now the _attribute_ filter I think is going to be more difficult... I _believe_ (and I'd love someone to correct me if I'm wrong) that the product attributes are just being stored as terms and therefore the _counts_ we get back can't really be filtered as they're just sitting in the DB as something like: "T-Shirt Size" => "5" (I can't rotate on that on something like "color")

So we'd need to pull _all_ the products matching the filter and compute counts "on the fly" (and then hopefully cache those... somewhere...)

Unless someone knows of a magic table or function call hiding somewhere that already does this?

(Oh maybe this isn't as big a deal as I thought because that's pretty much how `/products/collection-data`'s `calculate_price_range` works over in `ProductQueryFilters.php`)

Alright I might go slap together an implementation of that and see what people think?

**Comment by normana10** [comment]
Waaaaait a second, limiting the attributes based on a filter has been implemented in the backend already...

Right here: https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/src/StoreApi/Utilities/ProductQueryFilters.php#L163

So we literally just need to do the same song and dance as the price filter... and it works!

Before:
image
After:
image

That's _exactly_ the behavior I'm looking for

I _think_ I've come up with a slightly more extensible way to pass the partial `queryState` that the backend is aware of to the frontend, interested in people's thoughts

Thanks!

**Comment by dinhtungdu** [comment]
Thanks so much for the update, @normana10! This PR is testing well on my end, 🎉 

> Waaaaait a second, limiting the attributes based on a filter has been implemented in the backend already...

That's right, that's also why I suggest you pass a partial query state. Not only attributes but other filters are taken into account as well, so you can add category support to all of the current filter blocks by just providing the partial query state that contains the current category ID.

> I think I've come up with a slightly more extensible way to pass the partial queryState that the backend is aware of to the frontend, interested in people's thoughts

Do you mean creating the `AbstractFilterBlock` class for filter blocks? If true, then my thought is that we shouldn't create a new abstraction just for one purpose. I'm happier with even duplicating the code among filter blocks than having another abstraction layer. We're working on new filter blocks in #46142 and they will replace current filter blocks (which we're updating in this PR), so having some duplication here doesn't matter and is better than having a shared utils class or trait.

**Comment by normana10** [comment]
Hey @dinhtungdu 

Oh ok, is there a general timeline on those new filters? If they're coming imminently and fix this issue, then I suppose we can drop these changes and I can wait for the the new filters? (Or contribute if someone points me in the right direction!)

Either which way, I removed the abstraction layer and duplicated the code in both filters 👍

To clarify, when you say

> I suggest you pass a partial query state

Do you mean _not_ something like:
```php
$queryState = [];

if (is_product_category()) {
$queryState['category'] = get_queried_object_id();
}
if (is_product_tag()) {
$queryState['tag'] = get_queried_object()->term_id;
}

$this->asset_data_registry->add( 'queryState', $queryState );
```

(I tried just straight up passing `get_queried_object()` to the frontend, but that got a bit chaotic...)

Thanks!

**Comment by dinhtungdu** [comment]
> Oh ok, is there a general timeline on those new filters? If they're coming imminently and fix this issue, then I suppose we can drop these changes and I can wait for the the new filters? (Or contribute if someone points me in the right direction!)

@normana10 We haven't had a timeline for new filters yet. But even though we're releasing soon, we still should merge and ship this PR. The new filter blocks use a different approach than current ones and don't have this issue.

> Either which way, I removed the abstraction layer and duplicated the code in both filters 👍

Thank you so much!

> Do you mean not something like:

No, that's what I mean. I meant instead of passing a single value like category ID, we should pass an array that contains multiple query params like category or tag, like you're doing here.

The Lint and JS unit test workflow are failing, can you fix them so we can merge this PR?

**Comment by normana10** [comment]
@dinhtungdu 

Sounds good to me

Fixed! (I think)

**Review by dinhtungdu — APPROVED** [review]
@normana10 Thanks for fixing the test! This PR is LGTM now. I also manually tested this PR and can confirm the attribute and price filter blocks show relevant filter data for the current category. Great work!
