### PR TITLE
CYS: Fix Looker dashboard data

### LINKED ISSUE #50832: CYS: Fix Looker dashboard data
- [x] Remove all AI related information from the dashboard.
- [x] Remove `Assembler Hub > Of Users Click "Done"`
- [x] Rename `Intro Screen > Click On > Design Without AI` to "Design Your Own Theme"
- [x] `Transitional Page > Click On` should show all 5 click actions which are: Share Feedback / View Store / Go to Products / Go to Editor / Back to My Home
- [x] `Transitional Page > Survey` always shows zero for "Complete Survey"
- [x] `Transitional Page > Survey` can we add a CTA to link users to the Superset Dashboard
- [x] Add a "Feedback" section which shows: Total Feedback Sent / Average Feedback Score / Feedback Score which shows count per rating 1-5 (Refer to Project Thread for example of this)
- [x] Track & display average loading times
- [ ] `Intro Screen > Select a Theme`should only track clicks specifically on the theme thumbnails. The fact that Tsubaki is listed here indicates that its mixing AI flow data (from DotCom) with Core data.
- [x] Track & display data for font and color pairings including "Create your own" option.
- [x] Track & display data around tracking consent for those that give consent vs deny consent for fonts and patterns
- [x] Nice to have: Track and display data for logo flow. Enters section > Adds logo vs doesnt add logo vs clicks fiverr option.

### PR DESCRIPTION
**Pull request by mdperez86**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes #50832

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Paste this code into the browser devtools Console (<kbd>F12</kbd>) to debug: `localStorage.setItem( 'debug', 'wc-admin:*' );` the triggered events..
2. Go to WooCommerce > Home > Customize Your Store > Start designing.
3. Click on _Choose your color palette_ and select a different palette. Verify the `wcadmin_customize_your_store_assembler_hub_color_palette_item_click` event is triggered.
4. Click on _Or create your own_ and verify the `wcadmin_customize_your_store_assembler_hub_color_palette_create_toggle` event is triggered.
5. Go back and click on _Choose fonts_ and select a different font. Verify the `wcadmin_customize_your_store_assembler_hub_typography_item_click` event is triggered.
6. Go back and click on _Add your logo_ upload a file and verify the `wcadmin_customize_your_store_assembler_hub_logo_select` event is triggered.
7. Delete it and verify the `wcadmin_customize_your_store_assembler_hub_logo_remove_click` event is triggered.
8. Upload it again and replace it. Verify the `wcadmin_customize_your_store_assembler_hub_logo_replace_click` event is triggered.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce-admin/client/customize-store/assembler-hub/sidebar/sidebar-navigation-screen-color-palette.tsx [hunk 1]
```diff
@@ -27,6 +28,11 @@ const SidebarNavigationScreenColorPaletteContent = () => {
 	const hasCreatedOwnColors = !! (
 		user.settings.color && user.settings.color.palette.hasCreatedOwnColors
 	);
+	function handlePanelBodyToggle() {
+		trackEvent(
+			'customize_your_store_assembler_hub_color_palette_create_toggle'
+		);
```
Comment (Aljullu) [inline plugins/woocommerce-admin/client/customize-store/assembler-hub/sidebar/sidebar-navigation-screen-color-palette.tsx]: Currently, clicking the toggle to open or close it causes the same event. What do you think about adding information on whether it's clicked to open or close it?

File: plugins/woocommerce-admin/client/customize-store/assembler-hub/sidebar/sidebar-navigation-screen-logo.tsx [hunk 2]
```diff
@@ -351,10 +361,17 @@ const LogoEdit = ( {
 		<>
 			<MediaUploadCheck>
 				<MediaUpload
-					onSelect={ onInitialSelectLogo }
+					onSelect={ handleMediaUploadSelect }
 					allowedTypes={ ALLOWED_MEDIA_TYPES }
 					render={ ( { open }: { open: () => void } ) =>
-						cloneElement( logoImg, { onClick: open } )
+						cloneElement( logoImg, {
+							onClick() {
```
Comment (Aljullu) [inline plugins/woocommerce-admin/client/customize-store/assembler-hub/sidebar/sidebar-navigation-screen-logo.tsx:368]: I know that's subjective, but what do you feel about using an arrow function here? I feel it's more clear (not a strong opinion, though):

```suggestion
							onClick: () => {
```

**Review by Aljullu — COMMENTED** [review]
This looks great, @mdperez86, thanks for working on this! I left some minor comments inline, but overall looks good.

I used these testing steps:

1. Paste this code into the browser devtools Console (<kbd>F12</kbd>) to debug: `localStorage.setItem( 'debug', 'wc-admin:*' );` the triggered events..
2. Go to WooCommerce > Home > Customize Your Store > Start designing.
3. Click on _Choose your color palette_ and select a different palette. Verify the `wcadmin_customize_your_store_assembler_hub_color_palette_item_click` event is triggered.
4. Click on _Or create your own_ and verify the `wcadmin_customize_your_store_assembler_hub_color_palette_create_toggle` event is triggered.
5. Go back and click on _Choose fonts_ and select a different font. Verify the `wcadmin_customize_your_store_assembler_hub_typography_item_click` event is triggered.
6. Go back and click on _Add your logo_ upload a file and verify the `wcadmin_customize_your_store_assembler_hub_logo_select` event is triggered.
7. Delete it and verify the `wcadmin_customize_your_store_assembler_hub_logo_remove_click` event is triggered.
8. Upload it again and replace it. Verify the `wcadmin_customize_your_store_assembler_hub_logo_replace_click` event is triggered.

File: plugins/woocommerce-admin/client/customize-store/assembler-hub/sidebar/sidebar-navigation-screen-logo.tsx (hunk 2 above)
Comment (mdperez86) [reply plugins/woocommerce-admin/client/customize-store/assembler-hub/sidebar/sidebar-navigation-screen-logo.tsx:368]: Well l always favor normal function in almost any case except when I need to get access to the `this` instance of an outer context (and it's only for simplicity since I can still get access to the contextual `this` when using normal functions through the `bind` utility)

My reason why I don't like arrow functions is because they are treated as anonymous functions which is very bad for debugging. 
image
The same thing happens in the profiler 
image
So how do you know what is the function that you are inspecting or debugging?
This makes bug fixing or performance analysis a real hell just because we are obsessed with the arrow functions ;)!

So due to the way react functions behaves (we don't have to care about the `this` anymore) so arrow functions are not required at all.

File: plugins/woocommerce-admin/client/customize-store/assembler-hub/sidebar/sidebar-navigation-screen-color-palette.tsx (hunk 1 above)
Comment (mdperez86) [reply plugins/woocommerce-admin/client/customize-store/assembler-hub/sidebar/sidebar-navigation-screen-color-palette.tsx]: Done -> [9f8bc2c](https://github.com/woocommerce/woocommerce/pull/51206/commits/9f8bc2c11f7fe4bacd34c1dcff9a50e0446e17d8)

Comment (Aljullu) [reply plugins/woocommerce-admin/client/customize-store/assembler-hub/sidebar/sidebar-navigation-screen-color-palette.tsx]: Works as expected, thanks!

File: plugins/woocommerce-admin/client/customize-store/assembler-hub/sidebar/sidebar-navigation-screen-logo.tsx (hunk 2 above)
Comment (Aljullu) [reply plugins/woocommerce-admin/client/customize-store/assembler-hub/sidebar/sidebar-navigation-screen-logo.tsx:368]: Makes sense, let's not change it, then.

**Review by Aljullu — APPROVED** [review]
LGTM, thanks @mdperez86!
