### PR TITLE
Fixed call to member function is_visible Fatal Error

### LINKED ISSUE #51176: [Fatal] Call to a member function is_visible() on string | content-product.php:23
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

We observed the following fatal error in relation to WooCommerce 9.2.3:

[Link to code](https://github.com/woocommerce/woocommerce/blob/release/9.2/plugins/woocommerce/templates/content-product.php#L23)

<details><summary>Stack trace</summary>

```
PHP Fatal error:  Uncaught Error: Call to a member function is_visible() on string in /.../plugins/woocommerce/9.2.3/templates/content-product.php:23
Stack trace:
#0 /.../core/6.6.1/wp-includes/template.php(812): require()
#1 /.../plugins/woocommerce/9.2.3/includes/wc-core-functions.php(284): load_template('/srv/htdocs/wp-...', false)
#2 /.../plugins/woocommerce/9.2.3/includes/shortcodes/class-wc-shortcode-products.php(660): wc_get_template_part('content', 'product')
#3 /.../plugins/woocommerce/9.2.3/includes/shortcodes/class-wc-shortcode-products.php(100): WC_Shortcode_Products->product_loop()
#4 /.../plugins/woocommerce/9.2.3/includes/class-wc-shortcodes.php(259): WC_Shortcode_Products->get_content()
#5 /srv/htdocs/wp-content/themes/electro/inc/functions/extras.php(25): WC_Shortcodes::recent_products(Array, NULL, 'recent_products')
#6 /srv/htdocs/wp-content/themes/electro/inc/woocommerce/template-tags.php(1522): electro_do_shortcode('recent_products', Array)
#7 /srv/htdocs/wp-content/themes/electro/404.php(35): electro_promoted_products(3, 3)
#8 /.../core/6.6.1/wp-includes/template-loader.php(106): include('/srv/htdocs/wp-...')
#9 /.../core/6.6.1/wp-blog-header.php(19): require_once('/.../core...')
#10 /.../core/6.6.1/index.php(17): require('/.../core...')
#11 {main}
  thrown in /.../plugins/woocommerce/9.2.3/templates/content-product.php on line 23
```

</details> 

### Expected behavior

No fatal errors when $product->is_visible() is called.

### Actual behavior

Fatal errors when $product->is_visible() is called.

### Steps to reproduce

We don't have steps to reproduce, but observed 991 instances of this problem on Fri Aug 30, 1200 UTC to 2359 UTC on one site. Hopefully, someone can dig in and apply a defensive check if appropriate. - To be updated after investigation.

### WordPress Environment

N/A

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by narenin**
Closes #51176 .

### How to test the changes in this Pull Request:

In most cases, the cited fatal error does not occur. To be able to verify this, consider installing and activating [Query Monitor](https://wordpress.org/plugins/query-monitor/) (or else make sure you have some other way to test for the occurrence of errors). Then, let's begin by testing the "happy path": our goal here is to ensure nothing has broken or changed since the last version.

1. Ensure you have multiple test products.
2. Create a new page or post, or edit an existing one, and add the `[recent_products]` shortcode (remember you must add this via a Shortcode block, when working within the block editor).
3. View the frontend: you should see that the shortcode successfully generates a grid of products, and you should not observe any (new) errors, and definitely should not encounter fatal errors.
4. To all intents and purposes, the behavior you see when testing this change should match the previous stable version.

Now let's simulate the reported problem. Start by adding the following code snippet to a suitable location such as `wp-content/mu-plugins/test-pr-51286.php`:

```php
<?php

add_action(
	'wp_before_load_template',
	function ( $template_file ) {
		global $product;

		if (
			str_ends_with( $template_file, '/templates/content-product.php' )
			&& isset( $product )
		) {
			$product = null;
		}
	}
);
```

1. Repeat the original test.
2. This time, when you view the page or post containing the recent products shortcode, it should be mostly empty (the shortcode will not generate anything).
3. However, *so long as you are testing this branch,* you should also not observe any fatal errors.

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 
Fixed call to a member function is_visible() on string | content-product.php:23
</details>

### CODE REVIEW

File: plugins/woocommerce/templates/content-product.php [hunk 1]
```diff
@@ -20,7 +20,7 @@
 global $product;
 
 // Ensure visibility.
-if ( empty( $product ) || ! $product->is_visible() ) {
+if ( empty( $product ) || ! is_a( $product, 'WC_Product' ) || ! $product->is_visible() ) {
```
Comment (barryhughes) [inline plugins/woocommerce/templates/content-product.php]: Not sure we need to check it is empty **and** that it is a `WC_Product`. I'm also wondering if it might be better to reference the class in a slightly different way, to improve the debug+development experience for folks working with IDEs 🤔 

What do you think of:

```suggestion
if ( ! is_a( $product, WC_Product::class ) || ! $product->is_visible() ) {
```

**Review by barryhughes — CHANGES_REQUESTED** [review]
Thanks for submitting this!

- Left a note about a possible amendment to the line you changed.
- We should also update the template's version tag, from `3.6.0` to `9.4.0`.
- Can you provide testing instructions, per the PR template? When writing those, it is worth considering things like when this template block will be invoked.
- We also need a changelog. You should be able to generate one by populating the relevant fields in the PR description (otherwise, I can also circle back and add one manually).

File: plugins/woocommerce/templates/content-product.php (hunk 1 above)
Comment (narenin) [reply plugins/woocommerce/templates/content-product.php]: @barryhughes Thanks for reviewing this PR and sharing the valuable feedback. I have implemented the suggestions so could you please take a look into this.

Comment (wavvves) [reply plugins/woocommerce/templates/content-product.php]: Hi @narenin, just a note, a `empty()` or `isset()` check is not needed here as the global statement initializes the var if not present in the $GLOBALS array. Not sure if defensively we should be using the check anyway or the null coalescing operator in case the way $product var arrives there to prevent a warning/notice oh PHP 8+/7.4

I've pre-approved the PR, but let's also get @barryhughes' take to ensure this is just being overly cautious ;)

**Review by wavvves — APPROVED** [review]

File: plugins/woocommerce/templates/content-product.php (hunk 1 above)
Comment (barryhughes) [reply plugins/woocommerce/templates/content-product.php]: The suggestion was adopted in https://github.com/woocommerce/woocommerce/pull/51286/commits/9f706ae8b50a3cb4213af6585417c220345363c9, so I think we're good (we now know that `$product` is an instance of `WC_Product`) and things can flow from there. Per previous notes, though, we do still need a bump to the `@version` tag, testing instructions and a changelog.

Comment (narenin) [reply plugins/woocommerce/templates/content-product.php]: Thanks @wavvves @barryhughes for your feedback, I have updated the `@version` tag and also testing instructions and a changelog has been added.

File: plugins/woocommerce/changelog/51286-51176-fixed-fatal-is_visible-func [hunk 2]
```diff
@@ -0,0 +1,4 @@
+Significance: patch
+Type: fix
+Comment: Fixed call to a member function is_visible() on string | content-product.php:23
```
Comment (barryhughes) [inline plugins/woocommerce/changelog/51286-51176-fixed-fatal-is_visible-func:3]: Hi! Why would we not surface this in the changelog?

(Making it a comment means essentially means it will be hidden from the changelog.)

Comment (narenin) [reply plugins/woocommerce/changelog/51286-51176-fixed-fatal-is_visible-func:3]: Hi @barryhughes ,

Can we use the give on as comment in changelog.

```
Fixed an error in `content-product.php` where a call to `is_visible()` was made on a string instead of a product object, preventing proper visibility checks.
```

Comment (barryhughes) [inline plugins/woocommerce/changelog/51286-51176-fixed-fatal-is_visible-func:3]:
```suggestion

Fixed call to a member function is_visible() on string, in `content-product.php:23`.
```

**Comment by barryhughes** [comment]
> I have updated the @version tag and also testing instructions
> > No steps to share, this was observed by monitoring error logs.

I'll try to circle back and add some more instructions, but (and I'm partly noting this in case helpful to others that want to contribute) the above isn't really what we're looking for, that just copies a note from the original issue.

What we need is a set of steps that guide developers (and also non-developers involved in testing) to perform some actions that verify the fix, or at least verify that the happy path has not been broken. See [this guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions) for more details.

**Comment by narenin** [comment]
@barryhughes thanks for sharing the details, I will definitely follow this.

**Comment by barryhughes** [comment]
Testing instructions updated: once CI passes, I think we'll be good to merge. Thanks again for taking the time to address this problem 🎉

**Review by barryhughes — APPROVED** [review]
