### PR TITLE
Fix saving bug with Woo AI settings page and simplify.

### LINKED ISSUE #39535: Make sure Woo AI branding + tone settings persist after disabling Woo AI.
See P2 post comment here:
pb22l9-2eF-p2#comment-2518

### PR DESCRIPTION
**Pull request by tommyshellberg**
### Changes proposed in this Pull Request:

Refactors the Woo AI Settings class to avoid a bug in which the "tone of voice" select field and "business description" textarea input values are not POSTed if the "Enable AI features in your store" option is disabled when saving the Advanced->Features settings section.

To see where this was initially discovered along with a screencast of how to reproduce it, go to #39535.
The crux of this is that the enqueued JavaScript on the page was disabling the fields, which ultimately meant that they were not included in the POST data when the page was saved. 
The main fix here is that we are no longer disabling those fields but rather hiding them when the "Enable AI features in your store" option is unchecked.

Closes https://github.com/woocommerce/woocommerce/issues/39535

### How to test the changes in this Pull Request:

Screen Capture on 2023-08-03 at 15-09-55

1. Go to WooCommerce->Settings->Advanced->Features and test saving various settings on this page, most notably, testing that your input values are not reset if you disable AI features and save the page.
2. Make sure that you can update other settings on that page and that they persist when saving.
3. Make sure that the "tone of voice" and "business description" fields are hidden when the enable checkbox is unchecked.
4. Make sure that with the enable checkbox unchecked and saved, if you refresh the page, the "tone of voice" select field and "business description" fields should still be disabled.

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Comment 

</details>

### CODE REVIEW

File: plugins/woo-ai/includes/class-woo-ai-settings.php [hunk 1]
```diff
@@ -168,74 +96,58 @@ public function add_woo_ai_settings( $settings = array(), $current_section = nul
...
-				'id'      => 'woo_ai_enable_checkbox',
-				'default' => 'yes',
-				'type'    => 'checkbox',
+		$settings_ai[] = array(
+			'id'      => self::TONE_OF_VOICE_OPTION_KEY,
+			'name'    => __( 'Tone of voice', 'woocommerce' ),
+			'desc'    => __( 'Select the tone of voice for the AI', 'woocommerce' ),
+			'type'    => 'select',
+			'options' => array(
+				'informal'     => __( 'Relaxed and friendly.', 'woocommerce' ),
```
Comment (tommyshellberg) [inline plugins/woo-ai/includes/class-woo-ai-settings.php:125]: One of my goals with this PR was to try to simplify the settings page. Previously, we had longer descriptions of each "tone of voice" which couldn't fit into the select option field. So, we had JavaScript which would update the description underneath the select field based on the option selected.
I feel like we could get rid of this complexity by 1) shortening the descriptions and 2) select the descriptions themselves('Light-hearted and fun') rather than the one word key (humorous, neutral).

File: plugins/woo-ai/src/product-name/product-name.scss [hunk 2]
```diff
@@ -7,161 +7,162 @@ $z-index-header: 1002;
...
-
-  .wc-product-name-suggestions__error-message {
-	display: flex;
-	align-items: center;
-    margin: 0;
-    padding: 10px;
-
-	img {
-		margin-right: 10px;
+	border: 1px solid $border-color;
```
Comment (tommyshellberg) [inline plugins/woo-ai/src/product-name/product-name.scss:14]: These changes come from some auto-fixing of CSS linting errors.

File: plugins/woo-ai/src/settings.ts [hunk 3]
```diff
@@ -15,56 +15,20 @@ const fieldMap = {
 	) as HTMLInputElement,
 };
 
-const getSelectedOption = (): Element | null =>
-	document.querySelector( `.woo-ai-settings-tone-option.selected` );
-
-const setSelectedDescription = ( value: string ): void => {
```
Comment (tommyshellberg) [inline plugins/woo-ai/src/settings.ts:21]: As mentioned above, we can remove a considerable amount of JavaScript if we don't need to update the description below the Select field.

File: plugins/woo-ai/includes/class-woo-ai-settings.php [hunk 4]
```diff
@@ -168,74 +96,58 @@ public function add_woo_ai_settings( $settings = array(), $current_section = nul
...
-				'desc_tip'          => __( 'Tell us what makes your business unique to further improve accuracy of the AI-generated content. This will not be shown to customers.', 'woocommerce' ),
-				'placeholder'       => __( 'e.g. Marianne Renoir is a greengrocery taken over by a ten generations Parisian family who wants to keep quality and tradition in the quarter of Montmartre', 'woocommerce' ),
-				'css'               => 'min-width:300px;min-height: 130px;',
-			),
+		$settings_ai[] = array(
+			'id'          => self::STORE_DESCRIPTION_OPTION_KEY,
+			'title'       => __( 'Describe your business', 'woocommerce' ),
+			'type'        => 'textarea',
+			'desc_tip'    => __( 'Tell us what makes your business unique to further improve accuracy of the AI-generated content. This will not be shown to customers.', 'woocommerce' ),
+			'placeholder' => __( 'e.g. Marianne Renoir is a greengrocery taken over by a ten generations Parisian family who wants to keep quality and tradition in the quarter of Montmartre', 'woocommerce' ),
```
Comment (nima-karimi) [inline plugins/woo-ai/includes/class-woo-ai-settings.php:142]: I think a short doc block for the translators (`/* translators: ... */`) would be good here. Just to indicate what this sentence is and how it will be used.

File: plugins/woo-ai/includes/class-woo-ai-settings.php (hunk 1 above)
Comment (nima-karimi) [reply plugins/woo-ai/includes/class-woo-ai-settings.php:125]: This makes more sense than just including one word. I'd be interested to see how the model behaves if we included these descriptions in the prompt instead of the single word describing the tone. I think these will give the model more info on what we expect in the result.

Also tagging @jarekmorawski here to double check the wording for these options.

File: plugins/woo-ai/src/settings.scss [hunk 5]
```diff
@@ -1,4 +1,5 @@
 .woo-ai-settings-tone-option {
```
Comment (nima-karimi) [inline plugins/woo-ai/src/settings.scss]: Let's move the `settings.scss` and `settings.ts` files into a separate `settings` folder under `src`.

**Review by nima-karimi — CHANGES_REQUESTED** [review]
Thanks @tommyshellberg! I've left a few comments. Also noticed that the input fields for tone and store description flash when the "AI Features" is unchecked and you refresh the page. Possible because of the time it takes for the JS code to run and hide it on the first load. I think we can resolve it by adding a `display:none;` to their style when the fields are rendered by Woo.


https://github.com/woocommerce/woocommerce/assets/73110514/91d6c5f5-7048-4e3f-b9d1-98c312a3fe0f

**Comment by tommyshellberg** [comment]
> Thanks @tommyshellberg! I've left a few comments. Also noticed that the input fields for tone and store description flash when the "AI Features" is unchecked and you refresh the page. Possible because of the time it takes for the JS code to run and hide it on the first load. I think we can resolve it by adding a `display:none;` to their style when the fields are rendered by Woo.
> 
>  Screen.Recording.2023-08-09.at.6.25.12.PM.mov

Great catch! I've flipped things around so that the inputs are hidden via CSS by default and are shown via JS.
Hiding these table rows ended up being quite tricky because creating these settings via WooCommerce creates a table row for each field, but, you can't add any classes or hide the table rows, only the fields themselves. 
The only way I was able to do it was using the `:has()` property:

```
tr:has(#woo_ai_tone_of_voice_select),
tr:has(#woo_ai_describe_store_description) {
    display: none;
}
```

Unfortunately, Firefox _still_ doesn't have full support for `:has()`. Thus, there is still a bit of JS which will hide the fields on page load if the checkbox is unchecked; the flashing issue will thus remain for the small percentage of Firefox users until the browser implements `:has()` fully.

**Comment by tommyshellberg** [comment]
@nima-karimi this is ready for review again, thanks for the feedback!
You'll notice that the settings.scss file looks much smaller than before; there were some leftover CSS rules that no longer applied, so that's been cleaned up.

**Review by nima-karimi — APPROVED** [review]
Thanks for the updates, @tommyshellberg, This looks good 🚢
