### PR TITLE
Queue all webhooks on shutdown.

### LINKED ISSUE #27066: Async Webhook sends old information in order.update
**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
When changing order status in a Woo order; when the webhook `order.update` fires it is possible that it fires with the old status information.

This is similar to the bug details in https://github.com/woocommerce/woocommerce/issues/26787 except that it also happens with Async webhooks as well.

The difference here is that because it is async it doesn't happen all of the time but it is a race condition depending if the webhook fires before or after the status change has happened.

Basically when the Action Scheduler happens to catch the new webhook when it does the first update call when the order is created it can send the data as `pending`. When payment completes less than a second later and triggers and update to `processing` the webhook can still be running so it doesn't add the duplicate yet so in this case a webhook with the status of `processing` will never send.

We have observed this happening on a site with a high volume of orders where the first `order.update` webhook when the payment completes sends with `pending` instead of `processing`. A guess at frequency is that over 99% of webhooks correctly send the updated status.

**Expected behavior**
The status change from `pending` to `processing` should always fire a webhook with the status of `processing`.

**Actual behavior**
It is possible that the webhook will fire with the status as still `pending` and a webhook will never fire on the status change to `processing`

**Steps to reproduce the bug**
I have created a repository here which demos the issue by both running the Action Scheduler quickly and generating orders quickly until a webhook is fired with the wrong status.

See: https://github.com/matt-h/woocommerce-webhook-race

See instructions in the readme of the repository to reproduce the bug.

**Possible Solution**
A similar update to https://github.com/woocommerce/woocommerce/pull/26878 except for all webhooks should be added on shutdown and not just syncronous ones. This should give time for all updates in the request to have completed before it adds the webhook to the queue.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue.
Without this report we won't be able to fully evaluate this issue.
<details>
`
### WordPress Environment ###

WordPress address (URL): http://localhost
Site address (URL): http://localhost
WC Version: 4.3.0
REST API Version: ✔ 1.0.10
WC Blocks Version: ✔ 2.7.1
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.3.0
Log Directory Writable: ✔
WP Version: 5.4.2
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: PHP 7.4.8 Development Server
PHP Version: 7.4.8
PHP Post Max Size: 8 MB
PHP Time Limit: 300
PHP Max Input Vars: 1000
cURL Version: 7.71.1
OpenSSL/1.1.1g

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.4.13-MariaDB
Max Upload Size: 8 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.3.0
WC Database Prefix: wp_
Total Database Size: 9.84MB
Database Data Size: 5.28MB
Database Index Size: 4.56MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.08MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.30MB + Index: 0.30MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.33MB + Index: 0.39MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.09MB + Index: 0.06MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.25MB + Index: 0.23MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.09MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 1.52MB + Index: 0.19MB + Engine InnoDB
wp_postmeta: Data: 1.52MB + Index: 2.02MB + Engine InnoDB
wp_posts: Data: 0.22MB + Index: 0.22MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.06MB + Index: 0.05MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.08MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.06MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.08MB + Index: 0.13MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 1
page: 2
post: 2
product: 509
shop_order: 359

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (1) ###

WooCommerce: by Automattic – 4.3.0

### Inactive Plugins (2) ###

Akismet Anti-Spam: by Automattic – 4.1.5
Hello Dolly: by Matt Mullenweg – 1.7.2

### Must Use Plugins (1) ###

test-overrides.php: by  –

### Settings ###

API Enabled: –
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: ❌ Page not set
Cart: ❌ Page not set
Checkout: ❌ Page not set
My account: ❌ Page not set
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty
Version: 1.2 (update to version 1.4 is available)
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 1,060
Oldest: 2020-07-16 18:24:08 +0000
Newest: 2020-07-16 18:54:46 +0000

Pending: 1
Oldest: 2020-07-17 18:28:19 +0000
Newest: 2020-07-17 18:28:19 +0000

`
</details>

### PR DESCRIPTION
**Pull request by matt-h**
This is a potential fix for https://github.com/woocommerce/woocommerce/issues/27066

It is possible for a later duplicate webhook to be fired too early if the same webhook triggers in one request more than once with the updated changes from the second one missing if it happens too quickly. (See https://github.com/woocommerce/woocommerce/issues/27066 for more details)

This queues all webhook to be register on shutdown instead of just synchronous ones to make sure all data from the request is updated first before the webhook gets queued. This is based on the change here: https://github.com/woocommerce/woocommerce/pull/26878

I'm not sure if this is the best way to fix this, but with this change in place I am no longer able to reproduce the bug with my tests here: https://github.com/matt-h/woocommerce-webhook-race

Open to any suggestions. I made changes to the tests which removes the specific test that added this to sync webhooks and included them in the test that tests all. Not sure if this should be broken out more?

### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes #27066

### How to test the changes in this Pull Request:

1. Load this change into the WooCommerce install running through this: https://github.com/matt-h/woocommerce-webhook-race
2. Run the tests, it should never trigger the issue and just keep generating orders successfully.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Fix - Delayed the execution of all webhooks until after the request has completed.

### CODE REVIEW

**Comment by ObliviousHarmony** [comment]
Howdy @matt-h,

I actually thought about the same initially but was worried that it might be a break in backwards compatibility. Given that the bug is also present in asynchronous webhooks due to a race condition though I think this might be a reasonable change. _It's worth noting since we haven't shipped 4.4.0 yet that renaming the function and global is fine._

The other thing that worried me about webhooks is that the stale `arg` value is passed while values given by subsequent actions are ignored. I almost wonder if we should be indexing the webhook by the ID so that later hook queue events will simply override previous events entirely? I wonder if people might be relying on the bad behavior though?

**Comment by matt-h** [comment]
I don't think that the `arg` value is ignored at all.

The code here:
```
$wc_queued_webhooks[] = array(
	'webhook' => $webhook,
	'arg'     => $arg,
);
```
Just appends it to an array to it goes through and executes them all the same as it would on a normal run. The only difference is they all happen at the end of the php request instead of in different places in the middle it.

In `includes/class-wc-webhook.php` in the `process` function the `should_deliver` already uses the `arg` to check if it was triggered with the same `arg` or not so the behavior here should not change at all from the current behavior.

**Comment by ObliviousHarmony** [comment]
> In `includes/class-wc-webhook.php` in the `process` function the `should_deliver` already uses the `arg` to check if it was triggered with the same `arg` or not so the behavior here should not change at all from the current behavior.

Sorry, I missed that! Let me get some input from others on the team on this one but I'm going to approve it.

**Review by ObliviousHarmony — APPROVED** [review]

File: includes/wc-webhook-functions.php [hunk 1]
```diff
@@ -9,21 +9,40 @@
...
+				WC()->queue()->add( 'woocommerce_deliver_webhook_async', $queue_args, 'woocommerce-webhooks' );
+			}
+		} else {
+			// Deliver immediately.
+			$data['webhook']->deliver( $data['arg'] );
+		}
 	}
 }
-register_shutdown_function( 'wc_webhook_execute_synchronous_queue' );
+register_shutdown_function( 'wc_webhook_execute_queue' );
```
Comment (rrennick) [inline includes/wc-webhook-functions.php:45]: Is there a reason the WordPress `shutdown` hook isn't used here?

**Comment by rrennick** [comment]
@ObliviousHarmony This looks fine to me other than the question on the shutdown hook.

File: includes/wc-webhook-functions.php (hunk 1 above)
Comment (matt-h) [reply includes/wc-webhook-functions.php]: Good call on that. I think that the `shutdown` hook is the proper way to register this.

I have added a commit to switch it to using the `shutdown` hook.

**Comment by matt-h** [comment]
Good call on the `shutdown` hook. I think that the `shutdown` hook is the proper way to register this.

I have added a commit to switch it to using the `shutdown` hook.

**Review by rrennick — APPROVED** [review]
@matt-h Thanks for the contribution and included updated unit tests.
