### PR TITLE
Move settings save functionality to wp_loaded hook

### LINKED ISSUE #23087: Settings are updated after admin menu hook
**Describe the bug**
Options from the setting page are updated after the `admin_menu` hook.  For the most part this is not an issue, but one very minor problem is that this will prevent checking options on the next page load.

It looks like the options are being updated in the `'load-' . $settings_page` hook.  We might consider putting these on an earlier hook like `init` or `wp_loaded` if possible.

**To Reproduce**
1. Check an option value in an earlier hook than `'load-' . $settings_page`.  E.g.,
```php
function add_menu_item() {
    	if ( 'yes' === get_option( 'woocommerce_manage_stock' ) ) {
            // This block won't fire until the next page load.
        }
}
add_action( 'admin_menu', 'add_menu_item' );
```
2. Change an option and save.  E.g., enable stock management at `/wp-admin/admin.php?page=wc-settings&tab=products&section=inventory`
3. Note the option remains as the old value on initial page load.

This behavior can be seen in [this branch of wc-admin](https://github.com/woocommerce/woocommerce-admin/pull/1841).

**Screenshots**
(missing "Stock" page included in wc-admin when stock management is enabled)
Screen Shot 2019-03-20 at 2 34 28 PM
Screen Shot 2019-03-20 at 2 34 13 PM

**Expected behavior**
Expected to be able to get the new option setting inside the `admin_menu` to conditionally load pages.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by kloon**
### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:
This PR addresses an issue where menus are defined before settings are saved, resulting in conditional menus being out of sync when. I used wp_loaded to avoid issues with redirect loops and functions not being available instead of init, also added checks so the save functionality is not executed on all page loads, even though the actual saving works based on hooks defined via the current_section and current_tab variables.

Closes #23087 

### How to test the changes in this Pull Request:

See #23087 for testing instructions.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

### Changelog entry

> Update - Move settings save functionality to separate hook.

### CODE REVIEW

File: includes/admin/class-wc-admin-menus.php [hunk 1]
```diff
@@ -116,6 +106,34 @@ public function settings_page_init() {
 		do_action( 'woocommerce_settings_page_init' );
 	}
 
+	/**
+	 * Handle saving of settings.
+	 *
+	 * @return void
+	 */
+	public function save_settings() {
```
Comment (peterfabian) [inline includes/admin/class-wc-admin-menus.php]: Great that the method for saving the settings is now extracted. Much better than hidden inside an unrelated method.

File: includes/admin/class-wc-admin-menus.php [hunk 2]
```diff
@@ -116,6 +106,34 @@ public function settings_page_init() {
...
+		global $current_tab, $current_section;
+
+		// We should only save on the settings page.
+		if ( ! is_admin() || ! isset( $_GET['page'] ) || 'wc-settings' !== $_GET['page'] ) { // phpcs:ignore WordPress.Security.NonceVerification.NoNonceVerification
```
Comment (peterfabian) [inline includes/admin/class-wc-admin-menus.php]: Just wondering if it isn't better to check the nonce earlier than in `WC_Admin_Settings::save()`. Perhaps it doesn't matter much, just following the 'validate input early' rule I memorised from the Plugin developer handbook :)
On the other hand, maybe it would just introduce more problems, as public method `WC_Admin_Settings::save()` already verifies nonce, so removing it from that one could introduce problems and we don't want to perform double work.

**Review by peterfabian — APPROVED** [review]
This seems to work fine in my testing, I tried to change settings from tax classes to email templates, to payments, to shipping settings, all worked fine so far. Not sure if @rodrigoprimo wants to double check.

**Comment by rodrigoprimo** [comment]
> Not sure if @rodrigoprimo wants to double check.

I was going to review this PR someday last week and that is why I self-requested a review. But somehow I forgot about it. Thanks for reviewing the PR, Peter. I have removed my own request for review.
