### PR TITLE
Download Log FK Contraint check

### LINKED ISSUE #20473: Woocommerce Update Adds Foreign Key Constraint for wc_download_log Even If It Already Exists
It looks like beginning with Woocommerce (WC) 3.4.0, /includes/class-wc-install.php adds a new foreign key constraint to the table wc_download_log even if an identical foreign key constraint already exists. That means that a site which started with version 3.4.0, then updated to 3.4.1, and then to 3.4.2 (the current version as of this writing) ends up with three identical foreign key constraints for the table wc_download_log. 

1. Start with an installation of version 3.4.0 of WC that uses the InnoDB database engine for both the wc_download_log and woocommerce_downloadable_product_permissions tables. In my testing, both tables were empty, but I don't think that's necessary to reproduce the issue. 
2. Update to version 3.4.1 of WC. (This step is only necessary if you want to see _three_ duplicate foreign key constraints instead of just two.)
3. Update to version 3.4.2 of WC.
4. Use phpMyAdmin to view the Structure of the wc_download_log table.
5. Click the "Relation View" button on the Structure page for the table wc_download_log in phpMyAdmin to view foreign key constraints, where you will see multiple identical foreign key constraints. (Two for an installation that upgraded from 3.4.0 to 3.4.2, skipping 3.4.1, or three for an installation that went through all three versions.)

Expected Behavior
The expected behavior is that the /includes/class-wc-install.php script should check to be sure the foreign key constraint doesn't already exist, and create a foreign key constraint only if one does not exist.

Isolating the problem (mark completed items with an [x]):
- [x ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ x] This bug happens with a default WordPress theme active (TwentySeventeen).
- [ x] I can reproduce this bug consistently using the steps above.

The problem code can be found on line 560 of /includes/class-wc-install.php in version 3.4.2 of WC.

<details>
### WordPress Environment ###

Home URL: http://tempsite.com
Site URL: http://tempsite.com
WC Version: 3.4.2
Log Directory Writable: ✔
WP Version: 4.9.6
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.2.6
PHP Post Max Size: 8 MB
PHP Time Limit: 90
PHP Max Input Vars: 1000
cURL Version: 7.60.0
OpenSSL/1.0.2o

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.1.33-MariaDB
Max Upload Size: 5 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.4.2
WC Database Prefix: wp_
MaxMind GeoIP Database: ❌ The MaxMind GeoIP Database does not exist - Geolocation will not function. You can download and install it manually from https://dev.maxmind.com/geoip/geoip2/geolite2/ to the path: . Scroll down to "Downloads" and download the "MaxMind DB binary
gzipped" file next to "GeoLite2 Country". Please remember to uncompress GeoLite2-Country_xxxxxxxx.tar.gz and upload the GeoLite2-Country.mmdb file only.

Total Database Size: 2.51MB
Database Data Size: 1.67MB
Database Index Size: 0.84MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_comments: Data: 0.02MB + Index: 0.08MB
wp_icwp_wpsf_ip_lists: Data: 0.02MB + Index: 0.00MB
wp_icwp_wpsf_reporting: Data: 0.02MB + Index: 0.00MB
wp_icwp_wpsf_sessions: Data: 0.02MB + Index: 0.00MB
wp_icwp_wpsf_statistics: Data: 0.02MB + Index: 0.00MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_options: Data: 1.05MB + Index: 0.02MB
wp_postmeta: Data: 0.02MB + Index: 0.03MB
wp_posts: Data: 0.02MB + Index: 0.06MB
wp_termmeta: Data: 0.02MB + Index: 0.03MB
wp_terms: Data: 0.02MB + Index: 0.03MB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wp_usermeta: Data: 0.02MB + Index: 0.03MB
wp_users: Data: 0.02MB + Index: 0.05MB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB

### Post Type Counts ###

attachment: 1
customize_changeset: 1
nav_menu_item: 3
page: 6
post: 6
revision: 5

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (2) ###

WooCommerce Stripe Gateway: by WooCommerce – 4.1.7
WooCommerce: by Automattic – 3.4.2

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #20 - /shop/
Cart: #21 - /cart/
Checkout: #22 - /checkout/
My account: #23 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Seventeen
Version: 1.6
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –
</details>

### PR DESCRIPTION
**Pull request by kloon**
### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:
This PR introduces a check on the permission_id FK to ensure that it is not added multiple times on upgrades. It also names the key specifically to ensure future changes to the key can be targeted properly.

Closes #20473 .

### How to test the changes in this Pull Request:

1. Check out this path, and go through WooCommerce setup it not already set up.
2. Check FK existence by running the following SQL `SELECT * FROM information_schema.TABLE_CONSTRAINTS` and checking for any foreign keys on the download_log table.
3. Change the wc_version option in the options table to 3.3 `wp option update woocommerce_version '3.3'`
4. Open up wp-admin and let it finish loading, now check the SQL command from nr 2 above again, no additional FK's should be present and there should also be no error log entries referring to foreign keys.
5. Delete all foreign keys for the wc_download_log table using this sql command `alter table wp_wc_download_log drop foreign key wp_wc_download_log_ibfk_1` replace `wp_wc_download_log_ibfk_1` with the constraint name if diffirent and repeat for each FK entry for the table.
6. Repeat step 3
7. Run SQL query from step 2 again and check that only 1 FK is present with the name `fk_wc_download_log_permission_id`

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

### Changelog entry

> Fix - Add check to ensure download log FK does not exist before adding it.

### CODE REVIEW

File: includes/class-wc-install.php [hunk 1]
```diff
@@ -565,7 +565,24 @@ private static function create_tables() {
...
 		// Add constraint to download logs if the columns matches.
 		if ( ! empty( $download_permissions_column_type ) && ! empty( $download_log_column_type ) && $download_permissions_column_type === $download_log_column_type ) {
-			$wpdb->query( "ALTER TABLE {$wpdb->prefix}wc_download_log ADD FOREIGN KEY (permission_id) REFERENCES {$wpdb->prefix}woocommerce_downloadable_product_permissions(permission_id) ON DELETE CASCADE" );
+			$wpdb->query( "
+				IF NOT EXISTS (
+					SELECT NULL FROM information_schema.TABLE_CONSTRAINTS
+					WHERE
+						CONSTRAINT_SCHEMA = '{$wpdb->dbname}' AND
+						(
+							CONSTRAINT_NAME LIKE '%wc_download_log_ib%' OR
```
Comment (rodrigoprimo) [inline includes/class-wc-install.php]: Just a minor detail, but at least on my local environment we could be more specific and search for CONSTRAINT_NAME like `{$wpdb->prefix}wc_download_log_ibfk_%` instead of `%wc_download_log_ib%`. Although, I agree that `%wc_download_log_ib%` is probably specific enough so feel free to ignore this comment.

**Review by rodrigoprimo — COMMENTED** [review]
I tested this change and it worked as described but I second @thomas-zg question: should we remove duplicated foreign keys in a database update routine? Maybe in the next patch release instead of 3.5? Maybe we should make sure that the remaining key is called `fk_wc_download_log_permission_id` instead of `{$wpdb->prefix}wc_download_log_ibfk_%` to keep consistency and avoid potential issues in the future?

My main concern here is the potential performance implications of having duplicated foreign keys, but I don't know enough about how MySQL works to tell if the impact is negligible or not. Thoughts?

File: includes/class-wc-install.php (hunk 1 above)
Comment (kloon) [reply includes/class-wc-install.php]: I will add a cleanup routine

Comment (rodrigoprimo) [reply includes/class-wc-install.php]: > @rodrigoprimo I did that on purpose for cases where you would restore a DB from another server and the prefix is different.

Ok, makes sense. Thanks for the clarification.

> I will add a cleanup routine

Great, I will check the new version of this PR with the cleanup routine.

File: includes/wc-update-functions.php [hunk 2]
```diff
@@ -1802,3 +1802,35 @@ function wc_update_340_last_active() {
...
+		SELECT CONSTRAINT_NAME, TABLE_NAME
+		FROM information_schema.TABLE_CONSTRAINTS
+		WHERE CONSTRAINT_SCHEMA = '{$wpdb->dbname}'
+		AND CONSTRAINT_NAME LIKE '%wc_download_log_ib%'
+		AND CONSTRAINT_TYPE = 'FOREIGN KEY'
+	" );
+
+	if ( $results ) {
+		foreach ( $results as $fk ) {
+			$wpdb->query( "ALTER TABLE {$fk->TABLE_NAME} DROP FOREIGN KEY {$fk->CONSTRAINT_NAME}" ); // phpcs:ignore
```
Comment (rodrigoprimo) [inline includes/wc-update-functions.php]: I would recommend that we avoid as much as possible using `phpcs:ignore` without specifying which rules to ignore. In this particular case I would use:

`// phpcs:ignore WordPress.WP.PreparedSQL.NotPrepared`

File: includes/class-wc-install.php [hunk 3]
```diff
@@ -565,7 +569,24 @@ private static function create_tables() {
...
```
Comment (rodrigoprimo) [inline includes/class-wc-install.php]: Now that I cleanup routine has been added, I don't think this query should still be checking if foreign keys matching `%wc_download_log_ib%` exists. It should only check if a key named `fk_wc_download_log_permission_id` exists.

If we don't create a `fk_wc_download_log_permission_id` foreign key if a `%wc_download_log_ib%` foreign key exists, sites updating to WC 3.4.3 from any of the previous 3.4.x versions will be left with no foreign keys after `wc_update_343_cleanup_foreign_keys()` runs.

**Review by rodrigoprimo — CHANGES_REQUESTED** [review]

**Comment by mikejolley** [comment]
@kloon Some feedback above ^ Could you address that Monday please? Need to do the next release probably tues.

**Review by rodrigoprimo — APPROVED** [review]

File: includes/class-wc-install.php [hunk 4]
```diff
@@ -565,7 +569,21 @@ private static function create_tables() {
 
 		// Add constraint to download logs if the columns matches.
 		if ( ! empty( $download_permissions_column_type ) && ! empty( $download_log_column_type ) && $download_permissions_column_type === $download_log_column_type ) {
-			$wpdb->query( "ALTER TABLE {$wpdb->prefix}wc_download_log ADD FOREIGN KEY (permission_id) REFERENCES {$wpdb->prefix}woocommerce_downloadable_product_permissions(permission_id) ON DELETE CASCADE" );
+			$fk_result = $wpdb->get_row( "
+				SELECT COUNT(*) AS fk_count
+				FROM information_schema.TABLE_CONSTRAINTS
+				WHERE CONSTRAINT_SCHEMA = '{$wpdb->dbname}'
+				AND CONSTRAINT_NAME = 'fk_wc_download_log_permission_id'
```
Comment (rodrigoprimo) [inline includes/class-wc-install.php]: I would suggest we limit the query using `AND TABLE_NAME = '{$wpdb->prefix}wc_download_log'`. I say this because without specifying a table name MySQL will scan all databases and this is potentially slow for servers having a significant number of databases. Unless there is a reason not to specify the table name?

```
MariaDB [wccore]> explain SELECT * FROM information_schema.TABLE_CONSTRAINTS WHERE CONSTRAINT_SCHEMA = 'wccore' AND CONSTRAINT_NAME = 'fk_wc_download_log_permission_id' AND CONSTRAINT_TYPE = 'FOREIGN KEY';
+------+-------------+-------------------+------+---------------+------+---------+------+------+-----------------------------------------------------+
| id   | select_type | table             | type | possible_keys | key  | key_len | ref  | rows | Extra                                               |
+------+-------------+-------------------+------+---------------+------+---------+------+------+-----------------------------------------------------+
|    1 | SIMPLE      | TABLE_CONSTRAINTS | ALL  | NULL          | NULL | NULL    | NULL | NULL | Using where; Open_full_table; Scanned all databases |
+------+-------------+-------------------+------+---------------+------+---------+------+------+-----------------------------------------------------+
1 row in set (0.00 sec)
MariaDB [wccore]> explain SELECT COUNT(*) AS fk_count FROM information_schema.TABLE_CONSTRAINTS WHERE CONSTRAINT_SCHEMA = 'wccore' AND TABLE_NAME = 'wp_wc_download_log' AND CONSTRAINT_NAME = 'fk_wc_download_log_permission_id' AND CONSTRAINT_TYPE = 'FOREIGN KEY';
+------+-------------+-------------------+------+---------------+------------+---------+------+------+--------------------------------------------------+
| id   | select_type | table             | type | possible_keys | key        | key_len | ref  | rows | Extra                                            |
+------+-------------+-------------------+------+---------------+------------+---------+------+------+--------------------------------------------------+
|    1 | SIMPLE      | TABLE_CONSTRAINTS | ALL  | NULL          | TABLE_NAME | NULL    | NULL | NULL | Using where; Open_full_table; Scanned 1 database |
+------+-------------+-------------------+------+---------------+------------+---------+------+------+--------------------------------------------------+
1 row in set (0.00 sec)
```

I'm sorry I didn't notice this in my first review.

File: includes/wc-update-functions.php [hunk 5]
```diff
@@ -1802,3 +1802,35 @@ function wc_update_340_last_active() {
...
+/**
+ * Remove duplicate foreign keys
+ *
+ * @return void
+ */
+function wc_update_343_cleanup_foreign_keys() {
+	global $wpdb;
+
+	$results = $wpdb->get_results( "
+		SELECT CONSTRAINT_NAME, TABLE_NAME
```
Comment (rodrigoprimo) [inline includes/wc-update-functions.php]: Same as above

**Review by rodrigoprimo — COMMENTED** [review]
I found one last issue that is probably worth addressing before we merge this unless there is a reason not to specify the table name in the query. See inline comment above.

Out of curiosity, could you please elaborate on why we can't use IFs inside the queries (commit 477b81b67783a6fa454222296b6a9fcc754da9d6)?
