### PR TITLE
Fix missing notes table on 4.0.0 upgrade.

### LINKED ISSUE #25876: WC Admin notice tables don't exist during the upgrade
Based on https://wordpress.org/support/topic/wordpress-database-error-table-during-upgrade-to-4-0/

**Describe the bug**
During 4.0 upgrade, the log filled with many entries of those below. The table described is available after update. 

```
WordPress database error Table 'my-domain-wp-Tm6qKxT9.wp_eb51a9edfd_wc_admin_notes' doesn't exist for query SELECT note_id FROM wp_eb51a9edfd_wc_admin_notes WHERE name = 'wc-update-db-reminder' ORDER BY note_id ASC made by require_once('wp-admin/admin.php'), require_once('wp-load.php'), require_once('wp-config.php'), require_once('wp-settings.php'), do_action('init'), WP_Hook->do_action, WP_Hook->apply_filters, WC_Install::check_version, WC_Install::install, WC_Install::maybe_update_db_version, WC_Notes_Run_Db_Update::show_reminder, WC_Notes_Run_Db_Update::get_current_notice, WC_Data_Store->__call, Automattic\WooCommerce\Admin\Notes\DataStore->get_notes_with_name
WordPress database error Table 'my-domain-wp-Tm6qKxT9.wp_eb51a9edfd_wc_admin_notes' doesn't exist for query SHOW FULL COLUMNS FROM <code>wp_eb51a9edfd_wc_admin_notes</code> made by require_once('wp-admin/admin.php'), require_once('wp-load.php'), require_once('wp-config.php'), require_once('wp-settings.php'), do_action('init'), WP_Hook->do_action, WP_Hook->apply_filters, WC_Install::check_version, WC_Install::install, WC_Install::maybe_update_db_version, WC_Notes_Run_Db_Update::show_reminder, WC_Notes_Run_Db_Update::update_needed_notice, WC_Data->save, WC_Data_Store->create, Automattic\WooCommerce\Admin\Notes\DataStore->create
WordPress database error Table 'my-domain-wp-Tm6qKxT9.wp_eb51a9edfd_wc_admin_note_actions' doesn't exist for query DELETE FROM wp_eb51a9edfd_wc_admin_note_actions WHERE note_id = 0 made by require_once('wp-admin/admin.php'), require_once('wp-load.php'), require_once('wp-config.php'), require_once('wp-settings.php'), do_action('init'), WP_Hook->do_action, WP_Hook->apply_filters, WC_Install::check_version, WC_Install::install, WC_Install::maybe_update_db_version, WC_Notes_Run_Db_Update::show_reminder, WC_Notes_Run_Db_Update::update_needed_notice, WC_Data->save, WC_Data_Store->create, Automattic\WooCommerce\Admin\Notes\DataStore->create, Automattic\WooCommerce\Admin\Notes\DataStore->save_actions
WordPress database error Table 'my-domain-wp-Tm6qKxT9.wp_eb51a9edfd_wc_admin_note_actions' doesn't exist for query SHOW FULL COLUMNS FROM <code>wp_eb51a9edfd_wc_admin_note_actions</code> made by require_once('wp-admin/admin.php'), require_once('wp-load.php'), require_once('wp-config.php'), require_once('wp-settings.php'), do_action('init'), WP_Hook->do_action, WP_Hook->apply_filters, WC_Install::check_version, WC_Install::install, WC_Install::maybe_update_db_version, WC_Notes_Run_Db_Update::show_reminder, WC_Notes_Run_Db_Update::update_needed_notice, WC_Data->save, WC_Data_Store->create, Automattic\WooCommerce\Admin\Notes\DataStore->create, Automattic\WooCommerce\Admin\Notes\DataStore->save_actions
WordPress database error Table 'my-domain-wp-Tm6qKxT9.wp_eb51a9edfd_wc_admin_note_actions' doesn't exist for query SHOW FULL COLUMNS FROM <code>wp_eb51a9edfd_wc_admin_note_actions</code> made by require_once('wp-admin/admin.php'), require_once('wp-load.php'), require_once('wp-config.php'), require_once('wp-settings.php'), do_action('init'), WP_Hook->do_action, WP_Hook->apply_filters, WC_Install::check_version, WC_Install::install, WC_Install::maybe_update_db_version, WC_Notes_Run_Db_Update::show_reminder, WC_Notes_Run_Db_Update::update_needed_notice, WC_Data->save, WC_Data_Store->create, Automattic\WooCommerce\Admin\Notes\DataStore->create, Automattic\WooCommerce\Admin\Notes\DataStore->save_actions
WordPress database error Table 'my-domain-wp-Tm6qKxT9.wp_eb51a9edfd_wc_admin_note_actions' doesn't exist for query SELECT action_id, name, label, query, status, is_primary
				FROM wp_eb51a9edfd_wc_admin_note_actions

```
It seems that the code can be triggered before the tables are available under some circumstances. Please analyze.

### PR DESCRIPTION
**Pull request by jeffstieler**
### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes #25876. 

This PR moves the creation of the WC Admin Note to after WC Admin itself has been update - thus insuring the database tables exist.

### How to test the changes in this Pull Request:

1. Create a new site on WC 3.9.3
1. Check out this branch
1. Patch the packaged version of WooCommerce Admin with: https://github.com/woocommerce/woocommerce-admin/pull/3896
1. Verify that no PHP errors result from the `WC_Notes_Run_Db_Update` class

### Other information:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully run tests with your changes locally?

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

Fix admin notes table does not exist errors when upgrading to 4.0.x.

### CODE REVIEW

File: includes/class-wc-install.php [hunk 1]
```diff
@@ -156,7 +156,7 @@ class WC_Install {
 	public static function init() {
 		add_action( 'init', array( __CLASS__, 'check_version' ), 5 );
 		add_action( 'init', array( __CLASS__, 'manual_database_update' ), 20 );
-		add_action( 'plugins_loaded', array( __CLASS__, 'wc_admin_db_update_notice' ), 100 );
+		add_action( 'woocommerce_admin_updated', array( __CLASS__, 'wc_admin_db_update_notice' ) );
```
Comment (vedanshujain) [inline includes/class-wc-install.php]: this is a very significant change because we are now hooked on an action that will happen only once in a lifetime per version from an action that was happening on every request. 

Do we also want to remove early return conditions from https://github.com/woocommerce/woocommerce/blob/master/includes/admin/notes/class-wc-notes-run-db-update.php#L29 to make ensure that `show_reminder` runs (or maybe call it directly from the constructor)?

Maybe another way would be to keep this as it is and add a check for if option `woocommerce_admin_install_timestamp` is present?

**Review by vedanshujain — COMMENTED** [review]
I am not able to reproducce the original issue, have you already figured out an straightforward way to repro?

File: includes/class-wc-install.php (hunk 1 above)
Comment (jeffstieler) [reply includes/class-wc-install.php]: > this is a very significant change because we are now hooked on an action that will happen only once in a lifetime per version from an action that was happening on every request.

Good point. 🤔 

> Maybe another way would be to keep this as it is and add a check for if option `woocommerce_admin_install_timestamp` is present?

Yeah I think this is a good approach - I'll work on modifying the PR.

**Comment by jeffstieler** [comment]
> I am not able to reproducce the original issue, have you already figured out an straightforward way to repro?

@vedanshujain - the testing steps are pretty much it:

1. Create a new site on WC 3.9.3 (no other plugins)
1. Upgrade to 4.0.0
1. See PHP error on dashboard reload

**Comment by jeffstieler** [comment]
@vedanshujain this is ready for another review/test.

**Comment by peterfabian** [comment]
Just so that I understand...
in the plugin file itself, 
`\Automattic\WooCommerce\Packages::init();` is called... that hooks `\Automattic\WooCommerce\Packages::on_init` to `plugins_loaded` with the default priority.

When `on_init` runs at `plugins_loaded`, it triggers `\Automattic\WooCommerce\Admin\Composer\Package::init`, which at the very end, calls `\Automattic\WooCommerce\Admin\FeaturePlugin::init`.

Now if at this point, we're past `plugins_loaded`, `\Automattic\WooCommerce\Admin\FeaturePlugin::on_plugins_loaded` is called directly. If not, the code hooks the same function to `plugins_loaded` with the default priority. This seems like a potential problem in case we're in the process of running `plugins_loaded`, no? Or will always push this newly hooked code as the last in the list with the current priority and thus we can be certain it will run?

The `\Automattic\WooCommerce\Admin\FeaturePlugin::on_plugins_loaded` then calls `\Automattic\WooCommerce\Admin\FeaturePlugin::includes`, which in turn calls `\Automattic\WooCommerce\Admin\Install::init` to hook `\Automattic\WooCommerce\Admin\Install::check_version` to `admin_init` with priority 5. And only at this `admin_init`, the WC Admin tables are getting created in `\Automattic\WooCommerce\Admin\Install::install`. That seems quite late to me? 

WC runs table creation as a plugin activation hook or during the `init` action. Wouldn't it be better to also run the db creation sooner?

As for the notice code, maybe we can run it during `admin_init` with prio larger than 5, what do you think?

**Comment by peterfabian** [comment]
Also, right after the update, I visited the dashboard and got this, which indicates we should create those WC Admin tables sooner?

Screenshot 2020-03-13 at 09 56 02

**Comment by jeffstieler** [comment]
Looks like you're sleuthing skills are on point @peterfabian 🕵 

> WC runs table creation as a plugin activation hook or during the init action. Wouldn't it be better to also run the db creation for WC Admin sooner?

Yep, I'm sure `init` would be better than `admin_init`. We can make that change in the WC-Admin repo.

> As for the notice code, (other than removing the notice code from the 2 functions as @jeffstieler did) maybe we can run it during `admin_init` with prio larger than 5, what do you think?

Yep, that makes sense to me. I'll modify the PR to do just that.

**Comment by peterfabian** [comment]
For future reference, as @vedanshujain pointed out in slack, my assumption about `did_action` was incorrect, it returns true very early while running the action, before any of the callbacks are getting called, so the `plugins_loaded` conflict I described should not happen.

**Comment by peterfabian** [comment]
Sounds good, @jeffstieler , thanks!

**Comment by jeffstieler** [comment]
@peterfabian @vedanshujain updated the code and testing instructions.

**Review by peterfabian — APPROVED** [review]
I've tried to simulate the regular plugin update by installing from WP CLI and jumping to dashboard immediately after the update. Using this approach, I was able to get the errors with 4.0.0 package, but no errors coming from this notice with this change combined with the other one from the WC Admin repo, so it seems to me this works fine.

**Comment by peterfabian** [comment]
Thanks for jumping on it and fixing it quickly, @jeffstieler !
