### PR TITLE
Reveal admin errors when saving a coupon with invalid data

### LINKED ISSUE #27632: There is no validation warning for coupon amount when the percentage discount value is more than 100
## Bug Description:
Validation fails to display for coupon amount field when the percentage discount value is more than 100.

## Environment:
Windows 10
Browser: Chrome(Version 85.0.4183.83 (64-bit))
                 Firefox(Version 80.0.1)(64-bit)
                 Safari(Version 13.1.1)

## Steps to Reproduce:
1. Create any test site using Jurassic Ninja.
1. Install and activate all required plugins.
1. Go to Marketing->Coupons.
1. Add a new coupon.
1. Select discount type to "Percentage discount".
1. Now enter a value more than 100 in coupon amount field.
1. Click on Update. 
1. Note that coupon amount value gets reset to previous value.                
1. Observe that validation fails to display for coupon amount field.

## Actual Result:
Validation fails to display for coupon amount field when the percentage discount value is more than 100.

## Expected Result:
Validation should be display for coupon amount field if the value is more than 100 for percentage discount.  

## Artifacts:
[#27632.zip](https://github.com/woocommerce/woocommerce/files/5196391/27632.zip)

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

<details>
```
`
### WordPress Environment ###

WordPress address (URL): https://intimate-guanaco.jurassic.ninja
Site address (URL): https://intimate-guanaco.jurassic.ninja
WC Version: 4.5.0
REST API Version: ✔ 4.5.0
WC Blocks Version: ✔ 3.1.0
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.5.0
Log Directory Writable: ✔
WP Version: 5.5.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.46 (Unix) OpenSSL/1.0.2g
PHP Version: 7.4.9
PHP Post Max Size: 1 GB
PHP Time Limit: 30
PHP Max Input Vars: 5000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.7.31-0ubuntu0.16.04.1-log
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.5.0
WC Database Prefix: wp_
Total Database Size: 3.77MB
Database Data Size: 2.36MB
Database Index Size: 1.41MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailchimp_carts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailchimp_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 1.48MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_posts: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 1
page: 7
post: 2
shop_coupon: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (8) ###

Query Monitor: by John Blackbourn – 3.6.4
Companion Plugin: by Osk – 1.17
Facebook for WooCommerce: by Facebook – 2.0.1 – Installed version not tested with active version of WooCommerce 4.5.0
Jetpack by WordPress.com: by Automattic – 8.9
Google Ads for WooCommerce: by Kliken – 1.0.4 – Installed version not tested with active version of WooCommerce 4.5.0
Mailchimp for WooCommerce: by Mailchimp – 2.4.5 – Installed version not tested with active version of WooCommerce 4.5.0
WooCommerce Beta Tester: by WooCommerce – 2.0.1 – Installed version not tested with active version of WooCommerce 4.5.0
WooCommerce: by Automattic – 4.5.0

### Inactive Plugins (2) ###

Akismet Anti-Spam: by Automattic – 4.1.6
Hello Dolly: by Matt Mullenweg – 1.7.2

### Dropin Plugins (1) ###

db.php: Query Monitor Database Class

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #6 - /shop/
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 2.7.0
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 1
Oldest: 2020-09-09 14:31:44 +0000
Newest: 2020-09-09 14:31:44 +0000

`
```
</details>

### PR DESCRIPTION
**Pull request by jimjasson**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

This PR ensures that any errors that are triggered while saving a coupon with invalid data are displayed to the admin user. 

In `WC_Meta_Box_Coupon_Data`, the return value of `set_props` was ignored, instead of checking if it is a `WP_Error`, similar to how it is done in the `WC_Meta_Box_Product_Data` class: https://github.com/woocommerce/woocommerce/blob/e68ccf8620455a1ab5268ca7bd7b5ce2f2190845/plugins/woocommerce/includes/admin/meta-boxes/class-wc-meta-box-product-data.php#L373

**Important**: When saving a coupon with invalid data, you get two messages: A success message saying 'Coupon updated' and an error message with the specific error. The same happens when saving a product with a duplicate SKU -- you get a 'Product updated' success message and then an error message with the specific error. Behind the scenes, all the valid data are set, that's why two messages show up.

Closes #27632 

### Screenshots or screen recordings:

https://github.com/user-attachments/assets/37e2ccee-e3b3-41f7-9a64-521d265e3abc

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Go to Marketing > Coupons. 
2. Create a 'Percentage Discount' coupon.
3. Set the 'Coupon amount' to something greater than 100 -- e.g. 1000. 
4. Save the coupon. 
5. Ensure that you see a error message related to the discount amount and the invalid amount was not saved. 
6. Try with a different invalid amount, like -10, and ensure that the same flow is triggered. 
7. Try with a valid amount and ensure that you don't see any errors. 

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 
Revealed admin notices when saving a coupon with invalid data.
</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

**Review by PanosSynetos — CHANGES_REQUESTED** [review]
Awesome - It's great that we fixed this and admins can now see the validation errors.

File: plugins/woocommerce/includes/admin/meta-boxes/class-wc-meta-box-coupon-data.php [hunk 1]
```diff
@@ -388,6 +388,11 @@ public static function save( $post_id, $post ) {
 				'email_restrictions'          => array_filter( array_map( 'trim', explode( ',', wc_clean( $_POST['customer_email'] ) ) ) ),
 			)
 		);
+
+		if ( is_wp_error( $errors ) ) {
+			WC_Admin_Meta_Boxes::add_error( $errors->get_error_message() );
+		}
```
Comment (PanosSynetos) [inline plugins/woocommerce/includes/admin/meta-boxes/class-wc-meta-box-coupon-data.php]: If there are multiple errors, only one is displayed
- Enter negative coupon amount
- Enter maximum spend < minimum

With the suggestion, all errors will be displayed

```suggestion
		if ( is_wp_error( $errors ) ) {
			foreach ( $errors->get_error_messages() as $error_message ) {
				WC_Admin_Meta_Boxes::add_error( $error_message );
			}
		}
```

image

Comment (jimjasson) [reply plugins/woocommerce/includes/admin/meta-boxes/class-wc-meta-box-coupon-data.php]: Hey @PanosSynetos, 

I agree that this approach is better, as users have more context about the fields that were not saved. 

The reason why I only displayed 1 error was to be consistent with how product errors are displayed: [https://github.com/woocommerce/woocommerce/blob/e68ccf8620455a1ab5268ca7bd7b5ce2f2[…]ce/includes/admin/meta-boxes/class-wc-meta-box-product-data.php](https://github.com/woocommerce/woocommerce/blob/e68ccf8620455a1ab5268ca7bd7b5ce2f2190845/plugins/woocommerce/includes/admin/meta-boxes/class-wc-meta-box-product-data.php#L423-L425), but in that case it is quite difficult to post a request with more than 1 invalid options from the UI -- some DOM editing is required to post invalid values in some fields.

**Review by PanosSynetos — APPROVED** [review]
Retested, works as expected and multiple error messages appear. WTG!
