### PR TITLE
Customize Your Store: fix TS errors

### LINKED ISSUE #54125: Fix TS errors `plugins/woocommerce/client/admin/client/customize-store`
Part of https://github.com/woocommerce/woocommerce/issues/53939

### PR DESCRIPTION
**Pull request by gigitux**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes https://github.com/woocommerce/woocommerce/issues/54125 .

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Visit `wp-admin/admin.php?page=wc-admin&path=%2Fcustomize-store`
2. Click on "Start designing"
3. Do smoke test CYS

#### Only dev 

1. Go to `plugins/woocommerce/client/admin`
2. Comment [these lines](https://github.com/woocommerce/woocommerce/blob/d856cb9f8485a5483f4ac12222c58be40efd224a/plugins/woocommerce/client/admin/webpack.config.js#L189-L215)
3. Run `npx tsc | grep "customize-store"`
4. Ensure that no TS error appear.

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [x] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

Customize Your Store: fix TS errors.

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce/client/admin/client/customize-store/assembler-hub/auto-block-preview.tsx [hunk 1]
```diff
@@ -165,8 +181,7 @@ function ScaledBlockPreview( {
 		: 0;
 
 	// Initialize on render instead of module top level, to avoid circular dependency issues.
-	MemoizedBlockList = MemoizedBlockList || pure( BlockList );
```
Comment (gigitux) [inline plugins/woocommerce/client/admin/client/customize-store/assembler-hub/auto-block-preview.tsx:168]: `pure` is a deprecated method

File: plugins/woocommerce/client/admin/client/customize-store/transitional/index.tsx [hunk 2]
```diff
@@ -74,9 +74,6 @@ export const Transitional = ( {
 				</Modal>
 			) }
 			<SiteHub
-				variants={ {
```
Comment (gigitux) [inline plugins/woocommerce/client/admin/client/customize-store/transitional/index.tsx:77]: This prop isn't used

File: plugins/woocommerce/client/admin/client/customize-store/intro/index.tsx [hunk 3]
```diff
@@ -377,9 +377,6 @@ export const Intro: CustomizeStoreComponent = ( { sendEvent, context } ) => {
 			) }
 			<div className="woocommerce-customize-store-header">
 				<SiteHub
-					variants={ {
-						view: { x: 0 },
```
Comment (gigitux) [inline plugins/woocommerce/client/admin/client/customize-store/intro/index.tsx:381]: This prop isn't used

File: plugins/woocommerce/client/admin/client/customize-store/assembler-hub/sidebar/sidebar-navigation-screen.tsx [hunk 4]
```diff
@@ -117,7 +117,7 @@ export const SidebarNavigationScreen = ( {
 						}
 						color={ '#e0e0e0' /* $gray-200 */ }
 						level={ 1 }
-						size={ 20 }
```
Comment (gigitux) [inline plugins/woocommerce/client/admin/client/customize-store/assembler-hub/sidebar/sidebar-navigation-screen.tsx:120]: `size` isn't a valid prop

File: plugins/woocommerce/client/admin/client/customize-store/assembler-hub/block-editor-container.tsx [hunk 5]
```diff
@@ -186,7 +186,7 @@ export const BlockEditorContainer = () => {
 		<BlockEditor
 			renderedBlocks={ blocks }
 			isScrollable={ isScrollable }
-			onChange={ onChange }
+			onChange={ ( blockInstance ) => onChange( blockInstance, {} ) }
```
Comment (louwie17) [inline plugins/woocommerce/client/admin/client/customize-store/assembler-hub/block-editor-container.tsx]: This may actually break things right, I went down the rabbit hole a bit and it looks like the `onChange` would get called with the `blockInstance` and `selection` data: https://github.com/WordPress/gutenberg/blob/609a3c8d38a0608b41b1827ec4a8c1f812487ef2/packages/block-editor/src/components/provider/use-block-sync.js#L273-L283

The above change would also remove the the `selection` data. But it also means the types on our end are wrong for the `BlockEditor` onChange method.

File: plugins/woocommerce/client/admin/client/customize-store/assembler-hub/block-editor.tsx [hunk 6]
```diff
@@ -21,12 +21,13 @@ export const BlockEditor = memo(
 		onChange,
 	}: {
 		renderedBlocks: BlockInstance[];
-		settings: Record< string, unknown > & {
+		settings: EditorSettings & {
 			styles: string[];
+			[ key: string ]: unknown;
```
Comment (louwie17) [inline plugins/woocommerce/client/admin/client/customize-store/assembler-hub/block-editor.tsx:26]: Hmm looks like this was needed? If so, its all good!
It just always feels weird to me adding a generic item like this in addition to distinct typed values.

File: plugins/woocommerce/client/admin/client/customize-store/assembler-hub/toolbar/shuffle.tsx [hunk 7]
```diff
@@ -79,7 +80,9 @@ export default function Shuffle( { clientId }: { clientId: string } ) {
 		patternName: string;
 	} = useSelect(
 		( select ) => {
-			const { getBlockAttributes } = select( blockEditorStore );
+			const { getBlockAttributes } = select( blockEditorStore ) as {
+				getBlockAttributes: ( clientId: string ) => BlockAttributes;
+			};
```
Comment (louwie17) [inline plugins/woocommerce/client/admin/client/customize-store/assembler-hub/toolbar/shuffle.tsx]: Should we move some of these `blockEditorStore` to a central place, like a types file? and use them here. Given we manually set these in a couple places, like here: https://github.com/woocommerce/woocommerce/blob/843187ceff692bb78d59e3110a436f7213805f4a/plugins/woocommerce/client/admin/client/customize-store/assembler-hub/auto-block-preview.tsx#L131-L133

**Review by louwie17 — CHANGES_REQUESTED** [review]
This tested well, and changes look good for the most part. I did leave a couple comments, one important one around the `onChange` method. I am not sure if the change affected anything, but would break things.

File: plugins/woocommerce/client/admin/client/customize-store/assembler-hub/toolbar/shuffle.tsx (hunk 7 above)
Comment (gigitux) [reply plugins/woocommerce/client/admin/client/customize-store/assembler-hub/toolbar/shuffle.tsx]: As we decided, I added a comment (4fdd78f).

File: plugins/woocommerce/client/admin/client/customize-store/assembler-hub/block-editor-container.tsx (hunk 5 above)
Comment (gigitux) [reply plugins/woocommerce/client/admin/client/customize-store/assembler-hub/block-editor-container.tsx]: > The above change would also remove the the selection data. But it also means the types on our end are wrong for the BlockEditor onChange method.

I updated the type definition with [4048b51](https://github.com/woocommerce/woocommerce/pull/54133/commits/4048b51a3cf2d44234cc9f6d6e8142b44d7406ae)

File: plugins/woocommerce/client/admin/client/customize-store/assembler-hub/hooks/use-editor-blocks.ts [hunk 8]
```diff
@@ -7,21 +7,22 @@
 import { useEntityBlockEditor } from '@wordpress/core-data';
 import { BlockInstance } from '@wordpress/blocks';
 
-export type ChangeHandler = (
+type InputHandler = ( blocks: BlockInstance[] ) => void;
+type ChangeHandler = (
 	blocks: BlockInstance[],
-	options: Record< string, unknown >
+	options?: Record< string, unknown >
```
Comment (louwie17) [inline plugins/woocommerce/client/admin/client/customize-store/assembler-hub/hooks/use-editor-blocks.ts]: I believe `options` is actually required here, so this would be the wrong type - https://github.com/WordPress/gutenberg/blob/609d573625be035953f3782efdc0589f617b4b78/packages/core-data/src/hooks/use-entity-block-editor.js#L95

I was actually thinking that we should update the `onChange` type in the `BlockEditor` component: https://github.com/woocommerce/woocommerce/blob/5345873399b7c7439a45fc6236238a336772f5e8/plugins/woocommerce/client/admin/client/customize-store/assembler-hub/block-editor.tsx#L30
And in turn also in the `BlockPreview` `onChange` prop: https://github.com/woocommerce/woocommerce/blob/816aee20f4e6eea96ff60724c043b8efa7c3c1bf/plugins/woocommerce/client/admin/client/customize-store/assembler-hub/block-preview.tsx#L51

I noticed though that unfortunately the type for the `BlockEditorProvider` is out of date: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/wordpress__block-editor/components/provider.d.ts#L30-L37
As you can see in the actual code it does call the `onChange` or `onInput` with a second parameter that contains the selection information: https://github.com/WordPress/gutenberg/blob/609a3c8d38a0608b41b1827ec4a8c1f812487ef2/packages/block-editor/src/components/provider/use-block-sync.js#L276
In our case I did prefer we add a `@ts-expect-error` comment with our use of `BlockEditorProvider`, instead of adopting to the wrong type.

**Review by louwie17 — CHANGES_REQUESTED** [review]
Thanks for the updates @gigitux, I just left a follow up comment around the `useEditorBlocks` and `onChange` method updates. Let me know what you think.

File: plugins/woocommerce/client/admin/client/customize-store/assembler-hub/hooks/use-editor-blocks.ts (hunk 8 above)
Comment (gigitux) [reply plugins/woocommerce/client/admin/client/customize-store/assembler-hub/hooks/use-editor-blocks.ts]: Mmm, good point 🤔 Thanks for going in-depth! Fixed with ca7324dba057e76c01ce201170022832e65a7734

File: plugins/woocommerce/client/admin/client/customize-store/assembler-hub/block-editor-container.tsx [hunk 9]
```diff
@@ -186,6 +186,7 @@ export const BlockEditorContainer = () => {
 		<BlockEditor
 			renderedBlocks={ blocks }
 			isScrollable={ isScrollable }
+			// @ts-expect-error The type is not up to date.
```
Comment (louwie17) [inline plugins/woocommerce/client/admin/client/customize-store/assembler-hub/block-editor-container.tsx]: Sorry to be nitpicky here, but  the `BlockEditor` component is actually an internal component we can update ourselves.
I was thinking of adding the above comment here: https://github.com/woocommerce/woocommerce/blob/816aee20f4e6eea96ff60724c043b8efa7c3c1bf/plugins/woocommerce/client/admin/client/customize-store/assembler-hub/block-preview.tsx#L49
As the `BlockEditorProvider` is imported from the GB package.

**Review by louwie17 — CHANGES_REQUESTED** [review]
Sorry to be nitpicky, and I am sure you are ready to call it quits on these type changes. But left one more suggestion, I am also happy to push the change up though :)

File: plugins/woocommerce/client/admin/client/customize-store/assembler-hub/block-editor-container.tsx (hunk 9 above)
Comment (gigitux) [reply plugins/woocommerce/client/admin/client/customize-store/assembler-hub/block-editor-container.tsx]: No worries! I appreciated it! I'm dealing with multiple TS errors in different branches, and it creates some confusion for me :D 

Fixed with 95ef4cdca179a935189e292cf46d315bb477955e

**Review by louwie17 — APPROVED** [review]
This looks good to me, thanks for addressing the several suggestions. It also remained to test well 👍
