### PR TITLE
Skip loading of webhooks if webhooks disabled

### LINKED ISSUE #44791: Webhooks loaded too early when updating triggering MySQL errors due to missing webhooks table
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/includes/class-woocommerce.php#L907

This will load the webhooks (run DB query for webhooks table) and there is a condition for WP installed above https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/includes/class-woocommerce.php#L895, however when updating WooCommerce from an older version where the webhook table doesn't exist yet, because the updates didn't run, it will trigger a database error.

```
WordPress database error Table '...wc_webhooks' doesn't exist for query SELECT webhook_id FROM ...wc_webhooks 			WHERE 1=1 AND `status` = 'active'
```

I encountered this when upgrading WC using WP CLI with `wp wc update`

### Expected behavior

No error

### Actual behavior

WordPress database error

The simplest fix is probably to not load the webhooks when the WooCommerce version value stored is lower than the specific value where this table was added

### Steps to reproduce

Upgrade from an old WC version that doesn't have the `wc_webhooks` table to latest WooCommerce

### WordPress Environment

irrelevant

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by kkmuffme**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

If `woocommerce_load_webhooks_limit` is filtered to 0 or any other calls that have a webhook limit of 0, it should completely skip loading of webhooks (instead of running queries that are wasted).

This is useful e.g. to avoid DB notices in update https://github.com/woocommerce/woocommerce/issues/44791 (would require an add filter to set it to 0) or e.g. to disable webhooks loading completely in CLI.

Closes #44791 (not really, but gives people the ability to fix this)

### How to test the changes in this Pull Request:

No change in functionality, but just short-circuits existing behavior to avoid unnecessary DB queries.

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [x] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Comment
Doesn't change functionality, just avoids running queries that won't be used anyway.

</details>

### CODE REVIEW

**Comment by vedanshujain** [comment]
Closing and re-opening to trigger CI again.

**Review by vedanshujain — APPROVED** [review]
LGTM! This is also well covered in unit tests, will merge after CI passes.

File: plugins/woocommerce/includes/wc-webhook-functions.php [hunk 1]
```diff
@@ -159,6 +159,11 @@ function wc_get_webhook_statuses() {
  * @return bool
  */
 function wc_load_webhooks( $status = '', $limit = null ) {
+	// short-circuit if webhooks should not be loaded at all
```
Comment (vedanshujain) [inline plugins/woocommerce/includes/wc-webhook-functions.php]: Lint error:
```suggestion
	// short-circuit if webhooks should not be loaded at all.
```
