### PR TITLE
Fix PHPUnit test failure in WC_Tracks role properties test

### LINKED ISSUE #60299: PHPUnit Test Failure: WC_Tracks_Test::test_role_properties_for_multiple_roles
## Test Failure

**Test:** `WC_Tracks_Test::test_role_properties_for_multiple_roles`

**Failure:** Failed asserting that false matches expected true.

**File:** `/tests/php/includes/class-wc-tracks-test.php:108`

**Full Error Output:**
```
1) WC_Tracks_Test::test_role_properties_for_multiple_roles
Failed asserting that false matches expected true.

/var/www/html/wp-content/plugins/woocommerce/tests/php/includes/class-wc-tracks-test.php:108
/var/www/html/wp-content/plugins/woocommerce/bin/composer/phpunit/vendor/phpunit/vendor/phpunit/src/TextUI/Command.php:146
/var/www/html/wp-content/plugins/woocommerce/bin/composer/phpunit/vendor/phpunit/src/TextUI/Command.php:99
```

## Environment

When executing locally against a recently pulled trunk, with fresh wp-env setup (made sure I destroyed existing containers):
- `cd plugins/woocommerce`
- `pnpm run test:php:env`

## Details

The test is failing on line 108 of the WC_Tracks_Test class, where it's expecting a true value but receiving false. This suggests there may be an issue with role property handling in the Tracks functionality.

## Impact

This test failure indicates a potential regression in the role properties functionality for multiple roles in WooCommerce Tracks.

---

*Issue generated with the help of AI via Cursor*

### PR DESCRIPTION
**Pull request by chihsuan**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes #60299.

In my local environment, this PR also fixes some other test failures. https://github.com/woocommerce/woocommerce/issues/60300 https://github.com/woocommerce/woocommerce/issues/60302 https://github.com/woocommerce/woocommerce/issues/60303 https://github.com/woocommerce/woocommerce/issues/60304

Fixes a PHPUnit test failure in `WC_Tracks_Test::test_role_properties_for_multiple_roles` that occurs when running the full test suite. The test was failing because the `test_uninstall()` method removes WooCommerce roles (including `shop_manager`) but doesn't restore them, causing subsequent tests that depend on these roles to fail.

**Modified** `plugins/woocommerce/tests/legacy/unit-tests/util/install.php`:
- Added role restoration after uninstall test: `WC_Install::create_roles()` and `wp_roles()->for_site()`
- This ensures proper test isolation by restoring the system state after the destructive uninstall test

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

With fresh wp-env setup,

1. `cd plugins/woocommerce`
2. `pnpm run test:php:env`
3. Confirm that there are still some test failures, but the `WC_Tracks_Test` failure is fixed.

`Tests: 7353, Assertions: 25298, Errors: 1, Failures: 4, Warnings: 1, Skipped: 30, Risky: 1.`

<details>

```bash
There was 1 warning:

1) Automattic\WooCommerce\Tests\Blocks\StoreApi\Routes\CartItems::test_cart_item_image_filtering_logging
The at() matcher has been deprecated. It will be removed in PHPUnit 10. Please refactor your test to not rely on the order in which methods are invoked.

--

There were 4 failures:

1) WC_Admin_Tests_API_Reports_Import::test_import_params
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'Steve User'
+'Changed User'

/var/www/html/wp-content/plugins/woocommerce/tests/legacy/unit-tests/woocommerce-admin/api/reports-import.php:173

2) WC_Settings_Accounts_Test::test_get_settings__all_settings_are_present
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
     'woocommerce_trash_cancelled_orders' => 'relative_date_selector'
     'woocommerce_anonymize_refunded_orders' => 'relative_date_selector'
     'woocommerce_anonymize_completed_orders' => 'relative_date_selector'
+    'woocommerce_enable_delayed_account_creation' => 'checkbox'
 )

/var/www/html/wp-content/plugins/woocommerce/tests/php/includes/settings/class-wc-settings-accounts-test.php:73

3) Automattic\WooCommerce\Tests\Blocks\StoreApi\Routes\Patterns::test_post_endpoint_when_tracking_is_allowed
Failed asserting that false is not false.

/var/www/html/wp-content/plugins/woocommerce/tests/php/src/Blocks/StoreApi/Routes/Patterns.php:55

4) Automattic\WooCommerce\Tests\Internal\Utilities\COTMigrationUtilTest::test_init_theorder_object
Failed asserting that two objects are equal.
--- Expected
+++ Actual
@@ @@
 WC_Order Object (
-    'id' => 5080
+    'id' => 0
     'data' => Array (
         'parent_id' => 0
         'status' => 'pending'
         'currency' => 'USD'
         'version' => '10.2.0'
-        'prices_include_tax' => true
-        'date_created' => 2025-08-12T16:21:12.000000+0530
+        'prices_include_tax' => false
+        'date_created' => 2025-08-12T10:47:26.000000+0000
         'date_modified' => null
         'discount_total' => '0'
         'discount_tax' => '0'
@@ @@
         'total' => '50.00'
         'total_tax' => '0'
         'customer_id' => 1
-        'order_key' => 'wc_order_oZFcgIEBiaduA'
+        'order_key' => 'wc_order_pqlsF8PPgWEgc'
         'billing' => Array (
             'first_name' => 'Jeroen'
             'last_name' => 'Sormani'
@@ @@
             'address_2' => ''
             'city' => 'WooCity'
             'state' => 'NY'
-            'postcode' => '123456'
+            'postcode' => '12345'
             'country' => 'US'
             'email' => 'admin@example.org'
             'phone' => '555-32123'
@@ @@
         'payment_method_title' => 'Direct bank transfer'
         'transaction_id' => ''
         'customer_ip_address' => '127.0.0.1'
-        'customer_user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3'
+        'customer_user_agent' => 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36'
         'created_via' => ''
         'customer_note' => ''
         'date_completed' => null
@@ @@
     'legacy_datastore_props' => Array (...)
     'items' => Array (
         'line_items' => Array (
-            2294 => WC_Order_Item_Product Object (...)
+            248 => WC_Order_Item_Product Object (...)
         )
         'shipping_lines' => Array (
-            2295 => WC_Order_Item_Shipping Object (...)
+            249 => WC_Order_Item_Shipping Object (...)
         )
     )
     'items_to_delete' => Array ()

/var/www/html/wp-content/plugins/woocommerce/tests/php/src/Internal/Utilities/COTMigrationUtilTest.php:70

--

There was 1 risky test:

1) Automattic\WooCommerce\Tests\Internal\EmailEditor\WCTransactionalEmails\WCTransactionalEmailPostsGeneratorTest::testGetEmailTemplateReturnsDefaultTemplateWhenCustomTemplateDoesNotExist
Test code or tested code did not (only) close its own output buffers

--
```

</details>

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [x] Patch

#### Type

-   [x] Fix - Fixes an existing bug

#### Message
Fix PHPUnit test failure in WC_Tracks role properties test by ensuring roles are recreated after uninstallation test

</details>

### CODE REVIEW

**Comment by chihsuan** [comment]
This test is failing in CI, but I was also able to reproduce the failure locally using trunk.

`pnpm --filter @woocommerce/plugin-woocommerce run test:php:env -- --filter WC_Admin_Tests_API_Reports_Import`

```
There was 1 failure:

1) WC_Admin_Tests_API_Reports_Import::test_import_params
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'Steve User'
+'Changed User'

/var/www/html/wp-content/plugins/woocommerce/tests/legacy/unit-tests/woocommerce-admin/api/reports-import.php:173
```

File: plugins/woocommerce/tests/legacy/unit-tests/util/install.php [hunk 1]
```diff
@@ -117,10 +117,16 @@ public function test_create_roles() {
...
-
-		$this->assertNull( get_role( 'customer' ) );
-		$this->assertNull( get_role( 'shop_manager' ) );
+		try {
+			WC_Install::remove_roles();
+
+			$this->assertNull( get_role( 'customer' ) );
+			$this->assertNull( get_role( 'shop_manager' ) );
+		} finally {
+			// Always restore roles for subsequent tests.
```
Comment (jorgeatorres) [inline plugins/woocommerce/tests/legacy/unit-tests/util/install.php]: Given all the tests in this class deal with installation, maybe instead of trying to restore the state in this particular test we instead do it inside `tearDownAfterClass()` at the class level? As in we fully uninstall WC and reinstall via `WC_Install::install()`?

Not sure if re-installing surfaces other issues, but I do worry that `test_create_roles()` is also not restoring things to the previous state, so we're technically not running a "recently installed" WC anymore after that test runs.

If this is too much trouble, we can definitely go with the current approach.

**Review by jorgeatorres — APPROVED** [review]
Thanks for the PR @chihsuan!
I can confirm that this fixes the failures mentioned (and also for #60300). I left some comments, but totally optional. Please let me know what you think!

File: plugins/woocommerce/tests/legacy/unit-tests/util/install.php (hunk 1 above)
Comment (chihsuan) [reply plugins/woocommerce/tests/legacy/unit-tests/util/install.php]: Thanks for the feedback @jorgeatorres! That makes sense.

I've updated `tearDownAfterClass()` as you suggested. Now, after all tests finish, WC is reinstalled. This doesn't affect the test outcomes, but it should help restore the test environment more thoroughly. However, it's still not perfect. For instance, role objects aren't automatically refreshed, so we still need to manually call `wp_roles()->for_site();` to reload them. Please take another look. Thanks!

**Edit:** I updated the PR to use the same approach as the Bootstrap class to restore roles.

**Review by albarin — APPROVED** [review]
Thanks @chihsuan !
✅ Confirmed this PR fixes the `WC_Tracks_Test` tests.
✅ Confirmed it also fixes https://github.com/woocommerce/woocommerce/issues/60300 https://github.com/woocommerce/woocommerce/issues/60302 https://github.com/woocommerce/woocommerce/issues/60303 https://github.com/woocommerce/woocommerce/issues/60304
