### PR TITLE
Fix: Email editor compatibility with WordPress 6.8

### LINKED ISSUE #56272: WordPress 6.8 compatibility
Problems with the latest version of WordPress 6.8 beta-1

1. ~There is an error in the console: `Store "core/interface" is already registered.`~ Known issue
2. When I create a new email using the default template, the template part doesn't load, and the footer and header are missing: https://d.pr/i/hwHCFH – However, the header and footer are rendered in preview and in the sent email
3. Details parts are missing: https://d.pr/i/CdpcY4
4. There is a "No title" in the sidebar: https://d.pr/i/3kA0Nh
5. When I save the email, it says, “Email saved”, I refresh the page, and I can see the template selector
6. There is no scrollbar in the sidebar. When the content is too long I cannot get to the end: https://d.pr/i/kaQmz4
7. The "Bold" selector is too small: https://d.pr/i/QNdhOB

### PR DESCRIPTION
**Pull request by lysyjan**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes #56272, Closes WOOPLUG-2.

### Screenshots or screen recordings:

| Before | After |
| ------ | ----- |
|Screenshot 2025-03-30 at 15 28 30 | Screenshot 2025-03-30 at 15 07 29|
|Screenshot 2025-03-30 at 15 28 54| Screenshot 2025-03-30 at 15 08 06|

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Install the latest WP 6.8 (you can use the WordPress Beta Tester plugin)
2. Visit the page http://localhost:8888/wp-admin/edit.php?post_type=woo_email
3. Observe that the email editor looks as expected

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce/src/Internal/EmailEditor/Integration.php [hunk 1]
```diff
@@ -108,7 +108,12 @@ public function add_email_post_type( array $post_types ): array {
 					'search_items'  => __( 'Search Woo Emails', 'woocommerce' ),
 				),
 				'rewrite'  => array( 'slug' => self::EMAIL_POST_TYPE ),
-				'supports' => array( 'title', 'editor' ),
+				'supports' => array(
+					'title',
+					'editor' => array(
+						'default-mode' => 'template-locked',
+					),
+				),
```
Comment (triple0t) [inline plugins/woocommerce/src/Internal/EmailEditor/Integration.php:127]: Hi @lysyjan 
I remembered it would be best to move this fix to the Core Editor PHP package [here](https://github.com/woocommerce/woocommerce/blob/trunk/packages/php/email-editor/src/Engine/class-email-editor.php#L173), and we can remove the supports parameter from this array.

This ensures other extenders receive the update as well when we publish the packages.

Comment (lysyjan) [reply plugins/woocommerce/src/Internal/EmailEditor/Integration.php:127]: Hey @triple0t!
This is a good point, but I am afraid that moving the fix is not possible. We also need to add the default mode to the default values, but because there is array_merge, the value from the Integrator has a higher priority. I am going to add a new commit.

**Review by triple0t — APPROVED** [review]
LGTM. 

Tested on WP 6.8 and can confirm the issues are resolved.

Thank you

**Review by costasovo — APPROVED** [review]
Good Job! I checked the editor and I see that all the issues are fixed.

Video in current WP:

https://github.com/user-attachments/assets/c0c5fe76-b200-4b4d-b735-6fe59ef58092

Video in WP 6.8 RC2

https://github.com/user-attachments/assets/243141f4-1c61-47c9-9345-cfbf2a4254f4
