### PR TITLE
Fix order counts in status widget for sites with Redis object cache

### LINKED ISSUE #46809: WooCommerce 8.8.2 and Redis Are Causing Issues
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

You can view a description of the bug here https://wordpress.org/support/topic/woocommerce-8-8-2-not-playing-nice-with-redis/ 

At the moment, the common setup between the users experiencing issues is WooCommerce 8.8.2 and Redis (v5.3.7) I've searched the open issues and don't see anything related to what is described in that forum thread. 

### Expected behavior

The WooCommerce Status Widget updates when an order status changes without clearing the cache. 

### Actual behavior

"Since upgrading WC from 8.7.0 to 8.8.2, I’ve noticed the that the WooCommerce status widget on the Admin dashboard doesn’t update if the order statuses change."

### Steps to reproduce

Run WooCommerce 8.8.2 and Redis 5.3.7. Update the order status and see if the dashboard widget updates accordingly. 

### WordPress Environment

You'll have to obtain them from the people in the forum thread linked above. 

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by jorgeatorres**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

When Redis persistent cache is in use, the order counts in the status widget on the dashboard might not reflect the correct numbers unless you manually flush the cache.

This PR moves that cache to the standard "counts" WordPress cache group, which is (by default) non-persistent and plays better with Redis.

Closes #46809.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Make sure to start with a site that has a few orders.
1. Enable Redis on your environment (server + PHP extension) and a Redis plugin on your site.
   - On macOS, Redis can be installed by `brew install redis` and ran with `brew services start redis`.
   - The PHP extension can be installed, if necessary, with `pecl`: `pecl install redis`.
   - On the WP side, you can install the "Redis Object Cache" in Plugins > Add New Plugin. Make sure to enable the object cache in Settings > Redis.
1. Go to the WP dashboard and check the numbers in the "WooCommerce Status" widget.
   If not visible, make sure it is enabled inside "Screen Options". You might also need to run `wp option update woocommerce_task_list_hidden yes` if you didn't complete onboarding.
1. Go to WC > Orders and change the status of a few orders to "Processing" and others to "On hold".
1. Go back to the WP dashboard and make sure the order numbers reflect these changes.
1. Repeat the above with a different order datastore: run `wp wc cot sync` to sync orders and then go to WC > Settings > Advanced > Features and switch to the other "order data storage" option.

If the "WooCommerce Status" widget isn't displayed, make sure it is enabled inside "Screen Options". You might also need to complete the onboarding steps or skip them by running the following command:
`wp option update woocommerce_task_list_hidden yes`

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce/src/Utilities/OrderUtil.php [hunk 1]
```diff
@@ -196,8 +196,8 @@ public static function get_table_for_order_meta() {
 	public static function get_count_for_type( $order_type ) {
 		global $wpdb;
 
-		$cache_key        = 'order-count-' . $order_type;
-		$count_per_status = wp_cache_get( $cache_key, 'orders' );
+		$cache_key        = 'wc-order-count-' . $order_type;
```
Comment (vedanshujain) [inline plugins/woocommerce/src/Utilities/OrderUtil.php]: This should use the `WC_Cache_Helper::get_cache_prefix( 'orders' )` as the prefix, to tie in with wc order cache.  Passing count as a group `counts` will probably not work on memcache-based clients.
```suggestion
		$cache_key        = WC_Cache_Helper::get_cache_prefix( 'orders' ) . 'wc-order-count-' . $order_type;
```

Comment (jorgeatorres) [reply plugins/woocommerce/src/Utilities/OrderUtil.php]: Applied in 94ef10bbb7132d8525b09efe6100c2265f6ebbeb.

**Review by vedanshujain — APPROVED** [review]
LGTM!
