### PR TITLE
Product Block Editor: populate attribute options optimistically 

### LINKED ISSUE #47289: Product Block Editor: improve visualization when a new term is created
It would be nice to update the store optimistically when a new term is created. For this, we need to work on the CRUD implementation.

### LINKED ISSUE #48269: New Product Editor: Glitches On Variations Value Input
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Entering variation values by typing and hitting 'Enter' makes them disappear, and then popping up again when entering the next value.

https://github.com/woocommerce/woocommerce/assets/29686881/456bde23-fa2c-4c21-a4bf-45fe31295529

### Expected behavior

Variations values are added as they are typed in after pressing 'Enter' key.

### Actual behavior

Variations values disappear, and then popping up again when entering the next value.

### Steps to reproduce

PRE: New Product Editor is enabled under wp-admin/admin.php?page=wc-settings&tab=advanced&section=features

1. Go to Products -> Add New (/wp-admin/admin.php?page=wc-admin&path=%2Fadd-product)
2. Click on "Add options" button.
3. Add a variation like, for example: Color.
4. Then add its possible values. For instance: red, yellow, green. Write them one by one, pressing 'Enter' after each value.
5. Notice the value that was just entered.

### WordPress Environment

PHP 8.1
WC 9.0.0.40
WP 6.5.4
JP 13.5-beta

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by retrofox**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

This PR populates optimistically the attribute options in the "New attributes modal" in the UI, taking advantage of the recent changes in the CRUD implementation plus a few changes in the component.

Fixes #47289
Fixes #48269

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

Test the whole process of creating Variation options
  * Create/Select a Product Attribute
  * Create/Select attribute values 

1. Enable the new Product Editor
2. Go to the Variations tab
3. Click on `Add options` button to start creating new variations
4. Create/Select n attribute
5. Create/Select attribute values
6. Add as many attributes as you want to generate the product variations
7. When ready, click on the `Add` button
8. Confirm it creates variations based on all options combinations

https://github.com/woocommerce/woocommerce/assets/77539/ba227b60-f624-46dd-b3ad-f1bc98304df8

9. Go to `Organization` tab
10. Add product attributes by clicking on the `Add new` button on the `Attributes` subsection

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Comment 

</details>

### CODE REVIEW

File: packages/js/product-editor/src/components/attribute-control/attribute-table-row.tsx [hunk 1]
```diff
@@ -7,12 +7,13 @@ import {
 	Button,
 	FormTokenField as CoreFormTokenField,
 } from '@wordpress/components';
-import { useSelect, useDispatch } from '@wordpress/data';
+import { useSelect, useDispatch, select as sel } from '@wordpress/data';
```
Comment (retrofox) [inline packages/js/product-editor/src/components/attribute-control/attribute-table-row.tsx:10]: Using the `select` alias is undesired. I added a @todo below about it.

File: packages/js/product-editor/src/components/attribute-control/attribute-table-row.tsx [hunk 2]
```diff
@@ -29,6 +30,38 @@ interface FormTokenFieldProps extends CoreFormTokenField.Props {
 const FormTokenField =
 	CoreFormTokenField as React.ComponentType< FormTokenFieldProps >;
 
+/*
+ * Type copied form core FormTokenField component.
```
Comment (mattsherman) [inline packages/js/product-editor/src/components/attribute-control/attribute-table-row.tsx]: `form` -> `from`

File: packages/js/product-editor/src/components/attribute-control/attribute-table-row.tsx [hunk 3]
```diff
@@ -29,6 +30,38 @@ interface FormTokenFieldProps extends CoreFormTokenField.Props {
...
+ * Todo: move to a shared location.
+ */
+export interface TokenItem {
```
Comment (mattsherman) [inline packages/js/product-editor/src/components/attribute-control/attribute-table-row.tsx]: For now, since this isn't used outside of this file, and you plan on moving it to another location, we don't need to export the interface.

File: packages/js/product-editor/src/components/attribute-control/attribute-table-row.tsx [hunk 4]
```diff
@@ -166,37 +225,70 @@ export const AttributeTableRow: React.FC< AttributeTableRowProps > = ( {
...
+						attribute_id: attributeId,
+					},
+					optimisticUrlParameters: [ attributeId ],
+				}
+			) ) as ProductAttributeTerm;
 
 			return newTerm;
 		} );
 
 		const newItems = await Promise.all( promises );
```
Comment (mattsherman) [inline packages/js/product-editor/src/components/attribute-control/attribute-table-row.tsx]: Looks like an existing issue, but we aren't handling if any of the promises reject.

With the optimistic handling, this now results in an attribute added to the list that is always `validating` and can't be removed if the REST API to add the term fails.

Since this is an edge case, I'm okay with handling this in a follow up PR/issue if it isn't easy to address in this PR.

File: packages/js/product-editor/src/components/attribute-control/new-attribute-modal.scss [hunk 5]
```diff
@@ -34,6 +34,20 @@
...
+				background-size: 100px 100%;
+				box-shadow: 0 0 1px black inset;
+				opacity: 1;
+
+				.components-form-token-field__token-text,
+				.components-form-token-field__remove-token {
+					background-color:transparent;
+					pointer-events: none;
+				}
+			}
```
Comment (mattsherman) [inline packages/js/product-editor/src/components/attribute-control/new-attribute-modal.scss:50]: It would be nice to push this state and styling upstream to the core token field component in a future PR.

**Review by mattsherman — CHANGES_REQUESTED** [review]
Overall, works great. Feels much better! Nice work!

Left a few comments for requested/suggested changes. And, potentially addressing the failure case when adding a term, unless you think it is beyond the scope of this PR and should be handled in a follow up.

File: packages/js/product-editor/src/components/attribute-control/attribute-table-row.tsx (hunk 4 above)
Comment (retrofox) [reply packages/js/product-editor/src/components/attribute-control/attribute-table-row.tsx]: Yes, we need to continue improving the error handling here. As mentioned in a comment on this pull request, I believe we should relocate this logic to the store level. In that scenario, error handling should be simpler and more robust.

File: packages/js/product-editor/src/components/attribute-control/new-attribute-modal.scss (hunk 5 above)
Comment (retrofox) [reply packages/js/product-editor/src/components/attribute-control/new-attribute-modal.scss:50]: I'm unsure if core wants to apply these styles. We can ask to confirm.

**Comment by retrofox** [comment]
> Overall, works great. Feels much better! Nice work!
> 
> Left a few comments for requested/suggested changes. And, potentially addressing the failure case when adding a term, unless you think it is beyond the scope of this PR and should be handled in a follow up.

I think it's out of the scope. We can work right after this one.

**Review by mattsherman — APPROVED** [review]
Retested and still works as expected.

Thanks for improving the jsdoc and naming.

Re-running failed CI checked now. If they pass, I will merge this.

**Comment by retrofox** [comment]
I've skipped the `can create a variation option and publish the product` test for now. Let's try to restore it in a follow-up. cc @octaedro
