### PR TITLE
Puerto Rico: Remove "City" field and rename "State" to "Municipality"

### LINKED ISSUE #26643: Puerto Rico being listed as a country leaves state field still required
**Describe the bug**

Puerto Rico is listed as a country in WooCommerce core. This means that the state field is shown, and still required. Puerto Rico has no states. We are currently advising people to make state field not required, but that brings another set of issues.

**To Reproduce**
1. Go to checkout
2. Select country as Puerto Rico
3. Don't select a state

**Screenshots**
screenshot **Image Link:** https://d.pr/i/crPQ2O

**Expected behavior**

Not to require a state when a "country" doesn't use states

**Isolating the problem (mark completed items with an [x]):**
- [x ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
`
### WordPress Environment ###

WordPress address (URL): https://slashandy.mystagingwebsite.com
Site address (URL): https://slashandy.mystagingwebsite.com
WC Version: 4.1.1
REST API Version: ✔ 1.0.7
WC Blocks Version: ✔ 2.5.16
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.1.3
Log Directory Writable: ✔
WP Version: 5.4.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 7.4.6
PHP Post Max Size: 2 GB
PHP Time Limit: 1200
PHP Max Input Vars: 6144
cURL Version: 7.70.0
OpenSSL/1.1.0l

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.3.21-MariaDB-log
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.1.1
WC Database Prefix: wp_
Total Database Size: 28.11MB
Database Data Size: 16.49MB
Database Index Size: 11.62MB
wp_woocommerce_sessions: Data: 1.48MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.09MB + Index: 0.09MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 2.02MB + Index: 4.33MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 1.02MB + Index: 2.03MB + Engine InnoDB
wp_ariadminer_connections: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_automatewoo_abandoned_carts: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_automatewoo_customers: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_automatewoo_customer_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_events: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_guests: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_automatewoo_guest_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_log_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_queue: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_queue_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_unsubscribes: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_commentmeta: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 1.05MB + Index: 0.09MB + Engine InnoDB
wp_email_log: Data: 0.19MB + Index: 0.00MB + Engine InnoDB
wp_followup_coupons: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_coupon_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_customers: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_followup_customer_carts: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_customer_notes: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_customer_orders: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_followup_email_coupons: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_followup_email_excludes: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_email_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_email_orders: Data: 0.14MB + Index: 0.09MB + Engine InnoDB
wp_followup_email_order_coupons: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_followup_email_tracking: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_followup_followup_history: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_order_categories: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_order_items: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_subscribers: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_subscribers_to_lists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_subscriber_lists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_ms_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 6.38MB + Index: 1.05MB + Engine InnoDB
wp_postmeta: Data: 1.38MB + Index: 1.31MB + Engine InnoDB
wp_posts: Data: 1.11MB + Index: 0.06MB + Engine InnoDB
wp_say_what_strings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wcpv_commissions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcpv_per_product_shipping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_bookings_availability: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_bookings_availabilitymeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_booking_relationships: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_points_rewards_user_points: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_points_rewards_user_points_log: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_warranty_products: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_bundled_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_bundled_items: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_exported_csv_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_square_customers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

attachment: 53
aw_workflow: 1
carts: 4
custom_css: 1
event_ticket: 3
follow_up_email: 1
jp_img_sitemap: 3
jp_sitemap: 3
jp_sitemap_master: 3
page: 14
post: 3
product: 33
product_variation: 17
revision: 18
shop_coupon: 4
shop_order: 41
shop_order_refund: 4
shop_subscription: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (31) ###

Akismet Anti-Spam: by Automattic – 4.1.5
ARI Adminer: by ARI Soft – 1.2.3
AutomateWoo: by WooCommerce – 4.9.2
Code Snippets: by Code Snippets Pro – 2.14.0
Email Log: by Sudar – 2.3.2
Health Check & Troubleshooting: by The WordPress.org community – 1.4.4
Jetpack by WordPress.com: by Automattic – 8.5
Storefront Powerpack: by WooCommerce – 1.5.0
WooCommerce Bookings: by WooCommerce – 1.15.20
WooCommerce Box Office: by WooCommerce – 1.1.23
WooCommerce Checkout Field Editor: by WooCommerce – 1.5.33
WooCommerce Cost of Goods: by SkyVerge – 2.9.7
WooCommerce Customer/Order/Coupon Export: by SkyVerge – 5.0.12
WooCommerce Dynamic Pricing: by Lucas Stark – 3.1.19 – Installed version not tested with active version of WooCommerce 4.1.1
Follow-Up Emails: by WooCommerce – 4.9.1
WooCommerce PayPal Checkout Gateway: by WooCommerce – 2.0.1 (update to version 2.0.2 is available)
WooCommerce PayPal Powered by Braintree Gateway: by WooCommerce – 2.3.10
WooCommerce Stripe Gateway: by WooCommerce – 4.4.0 – Installed version not tested with active version of WooCommerce 4.1.1
WooCommerce Memberships: by SkyVerge – 1.17.4
WooCommerce Multi-currency: by TIV.NET INC – 2.5.0 (update to version 2.5.4 is available) – Installed version not tested with active version of WooCommerce 4.1.1
WooCommerce Name Your Price: by Kathy Darling – 3.0.4 (update to version 3.0.6 is available)
WooCommerce One Page Checkout: by Automattic – 1.7.5 (update to version 1.7.6 is available)
WooCommerce Payments: by Automattic – 1.0.0
WooCommerce Product Add-ons: by WooCommerce – 3.0.33
WooCommerce Product Vendors: by WooCommerce – 2.1.4 (update to version 2.1.33 is available) – Installed version not tested with active version of WooCommerce 4.1.1
WooCommerce Quick View: by WooCommerce – 1.2.8
WooCommerce Services: by Automattic – 1.23.0 – Installed version not tested with active version of WooCommerce 4.1.1
WooCommerce USPS Shipping: by WooCommerce – 4.4.43
WooCommerce Square: by WooCommerce – 2.1.5
WooCommerce Subscriptions: by WooCommerce – 3.0.4 – Installed version not tested with active version of WooCommerce 4.1.1
WooCommerce: by Automattic – 4.1.1

### Inactive Plugins (19) ###

Facebook for WooCommerce: by Facebook – 1.11.3
Homepage Control: by WooThemes – 2.0.3
Loco Translate: by Tim Whitlock – 2.4.0
Say What?: by Lee Willis – 1.9.4
User Switching: by John Blackbourn & contributors – 1.5.4
WooCommerce Advanced Ajax Layered Navigation: by WooCommerce – 1.4.13 (update to version 1.4.23 is available) – Installed version not tested with active version of WooCommerce 4.1.1
WooCommerce Amazon Pay: by WooCommerce – 1.12.2
WooCommerce AvaTax: by SkyVerge – 1.4.4 (update to version 1.9.5 is available) – Installed version not tested with active version of WooCommerce 4.1.1
WooCommerce Bulk Stock Management: by WooCommerce – 2.2.24 (update to version 2.2.26 is available) – Installed version not tested with active version of WooCommerce 4.1.1
WooCommerce Cart Reports: by WPBackOffice – 1.1.13 – Installed version not tested with active version of WooCommerce 4.1.1
WooCommerce Dropshipping: by WooCommerce – 1.1.2 (update to version 2.3 is available) – Installed version not tested with active version of WooCommerce 4.1.1
WooCommerce MyGate Gateway: by WooCommerce – 1.2.9 (update to version 1.2.15 is available) – Installed version not tested with active version of WooCommerce 4.1.1
WooCommerce Payment Gateway Based Fees: by WooThemes – 3.1.4 – Installed version not tested with active version of WooCommerce 4.1.1
WooCommerce Points and Rewards: by WooCommerce – 1.6.32
WooCommerce Product Bundles: by SomewhereWarm – 6.2.4
WooCommerce Product Reviews Pro: by SkyVerge – 1.11.0 (update to version 1.15.4 is available) – Installed version not tested with active version of WooCommerce 4.1.1
WooCommerce Smart Coupons: by WooCommerce – 3.4.1 (update to version 4.7.5 is available) – Installed version not tested with active version of WooCommerce 4.1.1
WooCommerce Warranty Requests: by WooCommerce – 1.9.13
WP Crontrol: by John Blackbourn & crontributors – 1.8.3

### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
object-cache.php: Memcached

### Must Use Plugins (1) ###

Health Check Troubleshooting Mode: by  – 1.7.0

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: USD (USD)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: booking (booking)
bundle (bundle)
external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #3 - /shop/
Cart: #4 - /cart/
Checkout: #5 - /checkout/
My account: #6 - /my-account/
Terms and conditions: #121 - /my-ticket/

### Theme ###

Name: Storefront
Version: 2.5.6
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Memberships ###

Restriction mode:: Hide content only
Public content:: –
Excluded from discounts:: –
Membership plans:: ❌ No published plans

### Subscriptions ###

WCS_DEBUG: ✔ No
Subscriptions Mode: ✔ Live
Subscriptions Live URL: https://slashandy.mystagingwebsite.com
Subscription Statuses: wc-pending-cancel: 1
WooCommerce Account Connected: ✔ Yes
Active Product Key: ✔ Yes
Report Cache Enabled: ✔ Yes
Cache Update Failures: ✔ 0 failure

### Store Setup ###

Country / State: United States (US) — Alabama

### Subscriptions by Payment Gateway ###

other: wc-pending-cancel: 1

### Payment Gateway Support ###

PayPal Checkout: products
refunds
subscriptions
subscription_cancellation
subscription_reactivation
subscription_suspension
multiple_subscriptions
subscription_payment_method_change_customer
subscription_payment_method_change_admin
subscription_amount_changes
subscription_date_changes

Square: products
card_types
customer_decline_messages
payment_form
authorization
charge
charge-virtual
capture_charge
refunds
voids
customer_id
tokenization
add_payment_method
token_editor
subscriptions
subscription_suspension
subscription_cancellation
subscription_reactivation
subscription_amount_changes
subscription_date_changes
multiple_subscriptions
subscription_payment_method_change_customer
subscription_payment_method_change_admin


### Square ###

Environment: Production
Tokenization Enabled: ✔
Debug Mode: Off

### WooCommerce Customer/Order/Coupon Export ###

Automated exports: 0
Custom formats: 0
Next export: Not scheduled

### Multi-currency ###

allow_price_per_product: yes
currency_symbol_AED: -
currency_symbol_CAD: CAD
currency_symbol_USD: USD
enabled_currencies: a:3:{i:0;s:3:"AED";i:1;s:3:"CAD";i:2;s:3:"USD";}
fee_percent: 0
log_level: error
price_charm: 0
price_format_AED: -
price_format_CAD: -
price_format_USD: -
rates: array(171)
rates_provider_id: OpenExchangeRates
rates_retrieval_status: 1
rates_timestamp: 1590768000
rates_update_schedule: daily
round_to: 0.01
version: 2.5.0

### Action Scheduler ###

Complete: 2,365
Oldest: 2020-04-28 16:40:30 -0500
Newest: 2020-05-29 16:07:39 -0500

Pending: 10
Oldest: 2020-05-29 16:47:39 -0500
Newest: 2021-03-26 10:59:31 -0500


### Name Your Price ###

Template Overrides: –
`
```
</details>

### PR DESCRIPTION
**Pull request by claudiosanches**
### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

This PR rename "State" to "Municipality" and remove "City" from Puerto Rico addresses, also improves the formatting based on: https://pe.usps.com/text/pub28/28c2_041.htm

Closes #26643.

### How to test the changes in this Pull Request:

1. Checkout this branch.
2. Add a product to the cart and to go the checkout page.
3. Select "Puerto Rico", and check for the "Municipality" field.
4. Place an order and check for the address generated in the "order received page".

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Localization - Improved Puerto Rico addresses and improve address formatting.

### CODE REVIEW

File: includes/class-wc-countries.php [hunk 1]
```diff
@@ -527,6 +527,7 @@ public function get_address_formats() {
 					'NZ'      => "{name}\n{company}\n{address_1}\n{address_2}\n{city} {postcode}\n{country}",
 					'NO'      => "{company}\n{name}\n{address_1}\n{address_2}\n{postcode} {city}\n{country}",
 					'PL'      => "{company}\n{name}\n{address_1}\n{address_2}\n{postcode} {city}\n{country}",
+					'PR'      => "{company}\n{name}\n{address_1} {address_2}\n{state} {postcode}\n{country}",
```
Comment (jonathansadowski) [inline includes/class-wc-countries.php:530]: I believe that [postal code generally follows 'country'](https://pe.usps.com/text/pub28/28c2_041.htm) in PR address formats.

```suggestion
					'PR'      => "{company}\n{name}\n{address_1} {address_2}\n{state} \n{country} {postcode}",
```

**Review by jonathansadowski — DISMISSED** [review]

File: includes/class-wc-countries.php (hunk 1 above)
Comment (claudiosanches) [reply includes/class-wc-countries.php]: Thanks!

**Review by slash1andy — APPROVED** [review]

**Review by rrennick — APPROVED** [review]
@claudiosanches LGTM 🚢

**Comment by soussartdirection** [comment]
Removing City field for Puerto Rico broke my merchant plugin. NMI.  Transactions give an error that "city field is needed"
