### PR TITLE
Fix/37599 Add Product Name in the `aria-label` attribute

### LINKED ISSUE #37599: Accessibility Improvements ‣ Cart ‣ Remove Item 'X' Buttons
As originally noted [over here](https://github.com/woocommerce/woocommerce/issues/24185#issuecomment-779227823), there may be room to improve accessibility in relation to the Remove Item ('X') buttons on the cart page.

cart-remove-item

It already has an `aria-label` attribute, but it seems this may not be sufficient by itself, and it is proposed we add an `aria-describedby` attribute matching a corresponding ID for the product link in the cart table.

### PR DESCRIPTION
**Pull request by faisal-alvi**
### Submission Review Guidelines:

- I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
- I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
- I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/). 
- Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Adds a Product Name in the `aria-label` attribute on the cart page.

Closes #37599.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Use the storefront theme (this is to see the mini cart popup in the header).
2. Add a product to the cart.
3. Visit the cart page.
4. Activate the screen reader on your device. For Windows users, you can use NVDA or JAWS screen reader. For Mac users, you can use VoiceOver.
5. Once the screen reader is activated, navigate to the 'X' icon beside the product in the cart. Use the screen reader's keyboard commands to reach it. For example, use the "Tab" key to move between links, buttons, and form fields.
6. It should say "Remove XX from cart". Where XX is the product name.

image

7. Now visit the shop page, and check the top right side cart icon, hover over it and navigate to the 'X' icon in the popup.
8. Again, it should say "Remove XX from cart". Where XX is the product name.

image

### CODE REVIEW

**Comment by qasumitbagthariya** [comment]
### QA Update ✅ 
-------------

The aria label should have 'Remove XX'; where XX is the product name. Earlier it was 'Remove this item'.

**Testing Environment** 

<Details>

- WordPress: 6.2
- Theme: Storefront 4.2.0
- Woocommerce - 7.6.0
- PHP: 8.0.21
- Web Server: Nginx 1.20.2
- Browser: Chrome 
- OS: Windows 11
- Git Branch: faisal-alvi:fix/37599

</Details>


image
image

QA Status- Pass ✅

File: plugins/woocommerce/templates/cart/cart.php [hunk 1]
```diff
@@ -53,7 +54,7 @@
 									sprintf(
 										'<a href="%s" class="remove" aria-label="%s" data-product_id="%s" data-product_sku="%s">&times;</a>',
 										esc_url( wc_get_cart_remove_url( $cart_item_key ) ),
-										esc_html__( 'Remove this item', 'woocommerce' ),
+										sprintf( esc_attr__( 'Remove %s', 'woocommerce' ), $product_name ),
```
Comment (opr) [inline plugins/woocommerce/templates/cart/cart.php]: We should add a translation hint above, to note that `%s` is the product name.

Like so: `/* translators: %s is the product name */`

Comment (opr) [inline plugins/woocommerce/templates/cart/cart.php]: In this line, only the translated string "Remove %s" is escaped. Not the product name. The product name is filled in _after_ the escape.

I think we should do it like this, to ensure the product name is escaped correctly, too:

```suggestion
										esc_attr( sprintf( __( 'Remove %s', 'woocommerce' ), $product_name ) ),

```

File: plugins/woocommerce/templates/cart/mini-cart.php [hunk 2]
```diff
@@ -44,7 +44,7 @@
 						sprintf(
 							'<a href="%s" class="remove remove_from_cart_button" aria-label="%s" data-product_id="%s" data-cart_item_key="%s" data-product_sku="%s">&times;</a>',
 							esc_url( wc_get_cart_remove_url( $cart_item_key ) ),
-							esc_attr__( 'Remove this item', 'woocommerce' ),
+							sprintf( esc_attr__( 'Remove %s', 'woocommerce' ), $product_name ),
```
Comment (opr) [inline plugins/woocommerce/templates/cart/mini-cart.php]: Same as the suggestion above, we should do `esc_attr` on the final result.

```suggestion
							esc_attr( sprintf( __( 'Remove %s', 'woocommerce' ), $product_name ) ),

```

We also need a `/* translators:` comment above this use of `__`

File: plugins/woocommerce/templates/cart/cart.php (hunk 1 above)
Comment (Aljullu) [inline plugins/woocommerce/templates/cart/cart.php]: Thanks for this PR, @faisal-alvi! I didn't do a full review, but leaving a question here (maybe for @opr?):

[The Cart block uses `Remove %s from cart`](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/assets/js/base/components/cart-checkout/cart-line-items-table/cart-line-item-row.tsx#L316). I don't have a strong preference between both strings, but it might be a good idea to unify them, so we reduce the work for translators. Reusing the existing one in the Cart block would also guarantee that we have available translations. What do you think?

**Review by opr — CHANGES_REQUESTED** [review]
Hey @faisal-alvi, thanks for working on this! I tested this and it works really, well, however I have requested some changes which you can see in-line.

I would also like to request changes to your testing notes in the main PR body.

Please could you add some steps to describe testing the mini cart, and could you also add some steps to describe testing this with a screen reader?

Thanks!

File: plugins/woocommerce/templates/cart/cart.php (hunk 1 above)
Comment (opr) [reply plugins/woocommerce/templates/cart/cart.php]: I think this is a great idea, `Remove %s from cart` sounds good!

File: plugins/woocommerce/changelog/fix-37599 [hunk 3]
```diff
@@ -0,0 +1,4 @@
+Significance: patch
+Type: fix
+
+Add a product name in the aria-label attribute on the cart page.
```
Comment (opr) [inline plugins/woocommerce/changelog/fix-37599]: Just a thought, what do you think about this for a changelog note instead? I think it's a little more descriptive

```suggestion
Add the product name to the "Remove from cart" button's aria-label in the cart and mini cart.
```

**Comment by faisal-alvi** [comment]
@opr thanks for the feedback. The suggestions/changes are implemented. I've also added steps to describe testing the mini cart, and steps to describe testing this with a screen reader in the PR description: https://github.com/woocommerce/woocommerce/pull/37830#issue-1674664497.

File: plugins/woocommerce/templates/cart/cart.php [hunk 4]
```diff
@@ -38,8 +38,9 @@
 
 			<?php
 			foreach ( WC()->cart->get_cart() as $cart_item_key => $cart_item ) {
-				$_product   = apply_filters( 'woocommerce_cart_item_product', $cart_item['data'], $cart_item, $cart_item_key );
-				$product_id = apply_filters( 'woocommerce_cart_item_product_id', $cart_item['product_id'], $cart_item, $cart_item_key );
+				$_product     = apply_filters( 'woocommerce_cart_item_product', $cart_item['data'], $cart_item, $cart_item_key );
+				$product_id   = apply_filters( 'woocommerce_cart_item_product_id', $cart_item['product_id'], $cart_item, $cart_item_key );
+				$product_name = apply_filters( 'woocommerce_cart_item_name', $_product->get_name(), $cart_item, $cart_item_key );
```
Comment (rrennick) [inline plugins/woocommerce/templates/cart/cart.php:49]: There are some `$_product->get_name()` calls further down in the template that should be updated to `$product_name`.

**Review by rrennick — CHANGES_REQUESTED** [review]
@faisal-alvi Thanks for submitting this. In addition to my comment below, the template version in both templates needs to be updated to `7.8.0`.

File: plugins/woocommerce/templates/cart/cart.php (hunk 4 above)
Comment (faisal-alvi) [reply plugins/woocommerce/templates/cart/cart.php:49]: Correct, those are replaced too. Thanks https://github.com/woocommerce/woocommerce/pull/37830/commits/70cbbeebd422b7c592a49442dd31f83e976a9838

**Comment by faisal-alvi** [comment]
@rrennick Thanks for the feedback. The requested changes are implemented. Please check.

**Review by rrennick — DISMISSED** [review]
@faisal-alvi Looks great. Thanks for participating in the contributor day.

**Review by rrennick — APPROVED** [review]

**Review by opr — APPROVED** [review]
Looks great, thanks for your contribution @faisal-alvi!

**Comment by SiKth** [comment]
Hi,
This update might have caused and issue with the hook "woocommerce_cart_item_name". A lot of people use this to add information after the product name in the Cart and in the Checkout. Now all that data also gets output in the aria-label field. I have this on my site and when I search for this a lot of people recommend this solution to do just this. Anything we can look into?

Try this code for example, where the data comes from custom fields.

```
`add_filter( 'woocommerce_cart_item_name', 'cfwc_cart_item_name', 10, 3 );
function cfwc_cart_item_name( $name, $cart_item, $cart_item_key ) {
	
	if( isset( $cart_item['size'] ) ) {
		$name .= '<br><b>Size:</b> ' . $cart_item['size'] . '';
	}
	if( isset( $cart_item['color'] ) ) {
		$name .= '<br><b>Color:</b> ' . $cart_item['color'] . '';
	}
	
	return $name;
}`
```
