### PR TITLE
Sync Local Pickup title between Checkout block and shipping settings UI and vice/versa

### LINKED ISSUE #45160: Local pickup - title change isn't reflected in the local pickup button
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

The Local Pickup button in the Shipping Method section doesn't reflect the content changes when the title is changed in the Admin experience.

### Expected behavior

The local pickup title change should be reflected in any place where the title is displayed.

### Actual behavior

See the screenshot. The title change is reflected in the Order Summary section, but the Local Pickup button still shows "Local Pickup".
Annotation on 2024-02-27 at 11-36-25

### Steps to reproduce

1. Create a new test store with the Checkout block enabled, some sample products and an offline payment.
2. Go to WooCommerce > Settings > Shipping > Local Pickup
3. Enable Local Pickup, change the title, and add one location
4. Go to the store front-end and add a product to the cart
5. Go to the checkout and see that the title change isn't applied to the Local pickup button

### WordPress Environment

-

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by opr**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

This PR introduces some changes that will cause the local pickup title to save to the settings UI when edited in the block, and save to the block when edited in the settings UI.

To facilitate the sync from settings -> editor/front-end, the current local pickup title is output in the asset data registry (accessible via `wc.wcSettings`) this value is used by the block to render the title.

To handle syncing from editor -> settings UI, the `post_saved` action is hooked and we check if the post being saved is the checkout template, or the checkout page. If so, then the title text from the `Local Pickup` selector is extracted and saved to the settings.

This PR also adds E2E tests which checks the sync between editor/frontend and settings UI and vice/versa.

Closes #45160.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Use a block theme such as Twenty Twenty-Four. 
2. Go to WooCommerce -> Settings -> Shipping -> Local Pickup.
3. Add a location and enable local pickup.
4. Change the title of local pickup to something different.
5. Open the Checkout page template in the Site editor.
6. Ensure you can see the updated local pickup title from step 4.
image

7. Click into the local pickup selector and edit the title to something different.
8. Save the template and then go back to WooCommerce -> Settings -> Shipping -> Local Pickup.
9. Ensure the title shown here is the same as what you entered in the site editor.

https://www.loom.com/share/9324af6dd240411c839e944ac09ae367

1. Use a classic theme, such as storefront.
2. Repeat the steps above, but instead of going to the site editor, go to Pages -> then to your checkout page.

#### Edge case testing

1. Add a new page - insert the checkout block and edit the local pickup title.
2. Ensure it does **not** update the local pickup title in the settings UI. (this is because it only applies to the designated Checkout page).

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce/src/Blocks/BlockTypes/Checkout.php [hunk 1]
```diff
@@ -242,6 +244,71 @@ protected function is_checkout_endpoint() {
...
+		// Check if we are editing the checkout page and that it contains a Checkout block.
+		// Cast to string for Checkout page ID comparison because get_option can return it as a string, so better to compare both values as strings.
+		if ( ! empty( $post->post_type ) && 'wp_template' !== $post->post_type && ( false === has_block( 'woocommerce/checkout', $post ) || (string) get_option( 'woocommerce_checkout_page_id' ) !== (string) $post_id ) ) {
+			return;
+		}
+
+		if ( ( ! empty( $post->post_type ) && ! empty( $post->post_name ) && 'page-checkout' !== $post->post_name && 'wp_template' === $post->post_type ) || false === has_block( 'woocommerce/checkout', $post ) ) {
+			return;
+		}
+		$pickup_location_settings = get_option( 'woocommerce_pickup_location_settings', array() );
```
Comment (nielslange) [inline plugins/woocommerce/src/Blocks/BlockTypes/Checkout.php:270]: _When in doubt, space it out._ 😁

```suggestion
		}
		
		$pickup_location_settings = get_option( 'woocommerce_pickup_location_settings', array() );
```

File: plugins/woocommerce/src/Blocks/BlockTypes/Checkout.php [hunk 2]
```diff
@@ -242,6 +244,71 @@ protected function is_checkout_endpoint() {
...
+			return;
+		}
+
+		if ( empty( $post->post_content ) ) {
+			return;
+		}
+
+		$post_blocks = parse_blocks( $post->post_content );
+		$title       = $this->find_local_pickup_text_in_checkout_block( $post_blocks );
+		if ( $title ) {
```
Comment (nielslange) [inline plugins/woocommerce/src/Blocks/BlockTypes/Checkout.php]: Adding a line break here as well, might also increase the readability.

```suggestion
		$title       = $this->find_local_pickup_text_in_checkout_block( $post_blocks );
		
		if ( $title ) {
```

File: plugins/woocommerce/src/Blocks/BlockTypes/Checkout.php [hunk 3]
```diff
@@ -242,6 +244,71 @@ protected function is_checkout_endpoint() {
...
+			$pickup_location_settings['title'] = $title;
+			update_option( 'woocommerce_pickup_location_settings', $pickup_location_settings );
+		}
+	}
+
+	/**
+	 * Recurse through the blocks to find the shipping methods block, then get the value of the localPickupText attribute from it.
+	 *
+	 * @param array $blocks The block(s) to search for the local pickup text.
+	 * @return void|string  The local pickup text if found, otherwise void.
```
Comment (nielslange) [inline plugins/woocommerce/src/Blocks/BlockTypes/Checkout.php]: Should the `@return` annotation here be `null|string` instead? Typically, `@return void` implies that the method doesn't return a value. However, in the described method, it either returns the `localPickupText` attribute's value or it returns `null` when no value is specified.

File: plugins/woocommerce-blocks/assets/js/blocks/checkout/inner-blocks/checkout-shipping-method-block/block.tsx [hunk 4]
```diff
@@ -172,6 +172,10 @@ const Block = ( {
 		'shippingCostRequiresAddress',
 		false
 	);
+	const localPickupTextFromSettings = getSetting< string >(
+		'localPickupText',
+		localPickupText || defaultLocalPickupText
+	);
```
Comment (nielslange) [inline plugins/woocommerce-blocks/assets/js/blocks/checkout/inner-blocks/checkout-shipping-method-block/block.tsx:178]: Nitpic: I wonder if we should use `localPickupTitle` and `defaultLocalPickupTitle` instead of `localPickupText` and `defaultLocalPickupText`. 

1. In the editor, we call that field title.
Screenshot 2024-03-27 at 13 33 10

2. In the frontend, the top text looks like the title, while the bottom text looks like regular text.
Screenshot 2024-03-27 at 13 33 24

If we'd adjust that, we'd have to change it in various areas. I believe such a change would make the code a bit easier to read, but I'll leave that up to you.

File: plugins/woocommerce-blocks/tests/e2e/tests/local-pickup/local-pickup.merchant.block_theme.side_effects.spec.ts [hunk 5]
```diff
@@ -0,0 +1,96 @@
...
+			location: {
+				name: 'Automattic, Inc.',
+				address: '60 29th Street, Suite 343',
+				city: 'San Francisco',
+				postcode: '94110',
+				state: 'US:CA',
+				details: 'American entity',
+			},
+		} );
+		await localPickupUtils.disableLocalPickupCosts();
```
Comment (nielslange) [inline plugins/woocommerce-blocks/tests/e2e/tests/local-pickup/local-pickup.merchant.block_theme.side_effects.spec.ts:24]: As we're not checking against local pickup costs, do we need this part?

File: plugins/woocommerce-blocks/tests/e2e/tests/local-pickup/local-pickup.merchant.block_theme.side_effects.spec.ts [hunk 6]
```diff
@@ -0,0 +1,96 @@
...
+		await localPickupUtils.enableLocalPickup();
+	} );
+
+	test.afterEach( async ( { localPickupUtils } ) => {
+		await localPickupUtils.deleteLocations();
+		await localPickupUtils.disableLocalPickupCosts();
```
Comment (nielslange) [inline plugins/woocommerce-blocks/tests/e2e/tests/local-pickup/local-pickup.merchant.block_theme.side_effects.spec.ts]: Same as my previous comment. I wonder if we need this part.

File: plugins/woocommerce-blocks/tests/e2e/tests/local-pickup/local-pickup.merchant.block_theme.side_effects.spec.ts [hunk 7]
```diff
@@ -0,0 +1,96 @@
...
+		await localPickupUtils.setTitle( 'Local Pickup' );
+		await localPickupUtils.enableLocalPickup();
```
Comment (nielslange) [inline plugins/woocommerce-blocks/tests/e2e/tests/local-pickup/local-pickup.merchant.block_theme.side_effects.spec.ts]: In `test.beforeEach`, we're enabling local pickups. In the tests, I do not see that we're disabling them. Do we really need to enable them again in `test.afterEach`? I'd assume that they're still enabled.

File: plugins/woocommerce-blocks/tests/e2e/utils/local-pickup/local-pickup-utils.page.ts [hunk 8]
```diff
@@ -32,6 +33,17 @@ export class LocalPickupUtils {
...
+			return window.wp.data
+				.select( 'core/notices' )
+				.getNotices()
+				.some(
+					( notice: Notice ) =>
+						notice.status === 'success' &&
+						notice.content ===
+							'Local Pickup settings have been saved.'
+				);
+		} );
```
Comment (nielslange) [inline plugins/woocommerce-blocks/tests/e2e/utils/local-pickup/local-pickup-utils.page.ts]: In our e2e tests, we don't seem to check against this notice content. Do we really need this part? If so, shouldn't we handle the notice content?

File: plugins/woocommerce-blocks/tests/e2e/utils/local-pickup/local-pickup-utils.page.ts [hunk 9]
```diff
@@ -60,6 +72,12 @@ export class LocalPickupUtils {
 		await this.saveLocalPickupSettings();
 	}
 
+	async setTitle( title: string ) {
+		await this.openLocalPickupSettings();
+		await this.page.getByLabel( 'Title' ).fill( title );
+		await this.saveLocalPickupSettings();
+	}
```
Comment (nielslange) [inline plugins/woocommerce-blocks/tests/e2e/utils/local-pickup/local-pickup-utils.page.ts]: What are your thoughts on:
- renaming this function from `setTitle` to `setLocalPickupTitle` to be consistent with the other function names
- moving this function below `disableLocalPickupCosts()` as it's currently between `enableLocalPickupCosts()` and `disableLocalPickupCosts()` to keep these functions together

File: plugins/woocommerce/src/Blocks/BlockTypes/Checkout.php [hunk 10]
```diff
@@ -242,6 +244,71 @@ protected function is_checkout_endpoint() {
...
+	 *
+	 * @param int      $post_id The post ID.
+	 * @param \WP_Post $post    The post object.
+	 * @return void
+	 */
+	public function update_local_pickup_title( $post_id, $post ) {
+		if ( empty( $post->post_status ) || 'inherit' === $post->post_status ) {
+			// This is not a proper save action, maybe an autosave, so don't continue.
+			return;
+		}
```
Comment (nielslange) [inline plugins/woocommerce/src/Blocks/BlockTypes/Checkout.php]: What are your thoughts on moving the comment above the conditional check?

```suggestion
		// This is not a proper save action, maybe an autosave, so don't continue.
		if ( empty( $post->post_status ) || 'inherit' === $post->post_status ) {
			return;
		}
```

**Review by nielslange — APPROVED** [review]
Thanks for working on this, @opr. The PR works as expected and the code looks great. Well done. 👏

I just left a few minor comments and suggestions, but pre-approving this PR as it's already in a great shape.

File: plugins/woocommerce-blocks/assets/js/blocks/checkout/inner-blocks/checkout-shipping-method-block/block.tsx (hunk 4 above)
Comment (opr) [reply plugins/woocommerce-blocks/assets/js/blocks/checkout/inner-blocks/checkout-shipping-method-block/block.tsx:178]: Thanks for the suggestion, it makes sense but I feel this is out of scope for this PR and changing it would increase testing. We could address that in a refactor in future.

File: plugins/woocommerce-blocks/tests/e2e/tests/local-pickup/local-pickup.merchant.block_theme.side_effects.spec.ts (hunk 7 above)
Comment (opr) [reply plugins/woocommerce-blocks/tests/e2e/tests/local-pickup/local-pickup.merchant.block_theme.side_effects.spec.ts]: We basically want to reset the local pickup to how it was before we saw it, but since we need a page object to do so, we can't do this in `beforeAll` or `afterAll`, therefore I defaulted to `beforeEach` and `afterEach` where page contexts exist

File: plugins/woocommerce-blocks/tests/e2e/utils/local-pickup/local-pickup-utils.page.ts (hunk 9 above)
Comment (opr) [reply plugins/woocommerce-blocks/tests/e2e/utils/local-pickup/local-pickup-utils.page.ts]: Nice idea, thanks for the suggestion

File: plugins/woocommerce-blocks/tests/e2e/utils/local-pickup/local-pickup-utils.page.ts (hunk 8 above)
Comment (opr) [reply plugins/woocommerce-blocks/tests/e2e/utils/local-pickup/local-pickup-utils.page.ts]: Sorry Niels but I don't really follow. This check is in place to see when the save action has completed. We could check against request/response completion too but this seemed easier.

**Comment by opr** [comment]
@nielslange thanks for your review, I addressed the comments, but I don't think there's anything actionable from this one: https://github.com/woocommerce/woocommerce/pull/45720#discussion_r1540559065

On this basis I've enabled auto merge for this PR.

File: plugins/woocommerce-blocks/tests/e2e/utils/local-pickup/local-pickup-utils.page.ts (hunk 8 above)
Comment (nielslange) [reply plugins/woocommerce-blocks/tests/e2e/utils/local-pickup/local-pickup-utils.page.ts]: What I mean is, that we're not checking if the notice `Local Pickup settings have been saved.` appears, did we? At least, I could not see it. That's why I was asking if this part is necessary.

Comment (opr) [reply plugins/woocommerce-blocks/tests/e2e/utils/local-pickup/local-pickup-utils.page.ts]: Thanks for the suggestion, I've updated the test to look for the text now, removed the data store check.

Comment (nielslange) [reply plugins/woocommerce-blocks/tests/e2e/utils/local-pickup/local-pickup-utils.page.ts]: Thanks for adjusting this, Thomas.
