### PR TITLE
Optimize the regeneration of the product attributes lookup table

### LINKED ISSUE #46699: Dynamic update of wp_wc_product_attributes_lookup not working as expected
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

**Moving this over from the WordPress.org forums: https://wordpress.org/support/topic/issue-with-dynamic-update-of-wp_wc_product_attributes_lookup/. Originally posted by [oxfordmetadata](https://wordpress.org/support/users/oxfordmetadata/). This issue was flagged to us during Developer Office Hours, and I've asked the OP to provide any additional context they have here. I've filled out as much information as I have.**

----

We are involved in a project where the customer opted to have 377 product attributes with 6676 product attribute terms. These exact numbers are a result of the queries.

```
SELECT COUNT(DISTINCT taxonomy) AS total_attributes
FROM wp_term_taxonomy
WHERE taxonomy LIKE ‘pa_%’;
```
```
SELECT COUNT(*) AS total_attribute_terms
FROM wp_terms
WHERE term_id IN (
SELECT term_id
FROM wp_term_taxonomy
WHERE taxonomy LIKE ‘pa_%’
);
```

The problem we are facing is that at times our product filters in the category pages were failing. This is because the product filters in order to determine which products to show on each category were utilising the wp_wc_product_attribute_look up table.

Following extensive debugging, we realised that when the lookup table we set to be updated dynamically, when the stock was changing for product with over 200 attribute terms, it was failing. It was corrupted. Here you can see such one such product with 268 variations: [Aloha Ημιμόνιμο Βερνίκι Eight Color Coat 8ml – Femme Fatale (femme-fatale.gr)](https://femme-fatale.gr/product/nychia/imimonima-vernikia/xromata/aloha-imimonimo-verniki-eight-color-coat-8ml)

I wonder what we can do in order to sort out the update and make sure that the dynamic update code is not failing.

Note that we are using a 96GB server that has less than 30% CPU utilization whereas our database has a max memory limit of 60GB and usually 45GB is available.

The site (on the front end is one of the fastest woocommerce stores ever developed – i.e. this product with the 268 variation, loads at 0.8s ([Latest Performance Report for: ](https://gtmetrix.com/reports/femme-fatale.gr/83RMbXQO/)https://femme-fatale.gr/product/nychia/imimonima-vernikia/xromata/aloha-imimonimo-verniki-eight-colo&#8230; | GTmetrix). So, I am inclined not to buy even a hint that our server could be better tuned and that responsible for the failing is our infrastructure.

Are there any plans to make the dynamic population of the wp_wc_product_attributes_lookup more robust, as nowadays, Woocommerce is becoming the platform of choice for more demanding eshops?

Also note that in our case, for 8958 products – the manual regeneration of the wp_wc_product_attributes_lookup via the tools sections takes about 2 hours.

Thank you.

Please also refer to these (partly additional) issues:
[Major bug in product inventory status | WordPress.org](https://wordpress.org/support/topic/major-bug-in-product-inventory-status/#post-17684447)
[Hide out of stock items from the catalog – the case where it doesn’t work | WordPress.org](https://wordpress.org/support/topic/hide-out-of-stock-items-from-the-catalog-the-case-where-it-doesnt-work/)

Suffices to say that all along we were taking for granted that the wp_wc_product_attributes_lookup is always correct – was our datum. We invested 100s of man hours on this effort that led to this rather unfortunate finding/conclusion.

### Expected behavior

Product filters on category pages update

### Actual behavior

Product filters in the category page are failing when utilitising `wp_wc_product_attribute_look`. That lookup table was corrupted.

### Steps to reproduce

Pinged OP and asked them to provide.

### WordPress Environment

Pinged OP and asked them to provide.

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by Konamiman**
#### What

This pull request introduces a new method for creating and updating entries in the product attributes lookup table in a more performant way. The currently existing method makes use of the standard WordPress and WooCommerce functions to retrieve all the relevant data needed for composing the lookup data (product, taxonomies, terms), the new method uses SQL queries for direct access to the relevant tables.

The performance gain is apparent especially in variable products having lots of variations. Tests on a product having about 270 variation have shown a 100x improvement in the time needed to regenerate the lookup data.

The new method can only be used if products are stored in the posts table (and product attributes are standard WordPress taxonomies). Additionally, a new setting is introduced, `woocommerce_attribute_lookup_optimized_updates`, to enable the usage of the new method; it's available in the _WooCommerce - Settings - Product - Advanced_ settings page and it's disabled by default.

image

[The CLI tools](https://github.com/woocommerce/woocommerce/pull/47311) are also adjusted so that by default the `regenerate` and `regenerate_for_product` commands use the new method when possible, but an optional argument is added to use the old method instead.

This pull request also changes the default value of the background table regeneration step size (the amount of products that are processed in each run of the scheduled action) from 10 to 100. Each step involves a call to `wc_get_products`, which is an expensive operation, and there's also the overhead of scheduling and running the actions; the value of 10 was too conservative and that made the regeneration process to be slower than it should. A value of 100 is still reasonable and provides a significant performance gain (additional to the other changes introduced here).

#### How

Data is (re-)created in the product attributes lookup table when any of the following happens:

1. A background table regeneration is triggered from the WooCommerce tools page or from CLI (`initiate_regeneration` command).
2. A product (including variations) is created or updated (only changes to product attributes trigger the re-creation of entries in the lookup table).
3. A synchronous table regeneration is triggered from CLI (`regenerate` and `regenerate_for_product` commands).

For 1 and 2, the new method is used only if the `woocommerce_attribute_lookup_optimized_updates` setting is set to `yes` *and* products are stored as custom post types. The later is checked as follows: `is_a( \WC_Data_Store::load( 'product' )->get_current_class_name(), 'WC_Product_Data_Store_CPT', true );`.

For 3, the new method is used by default as long as products are stored as custom post types (the value of the `woocommerce_attribute_lookup_optimized_updates` setting is irrelevant). The `--disable-db-optimization` argument can be added to force the use of the old method.

Note: updating the stock status of a product or variation will update the corresponding row(s) in the lookup table accordingly, and deleting a product or variation will of course delete the corresponding rows; but that's irrelevant in the scope of this pull request.

Closes #46699.

### How to test the changes in this Pull Request:

You need a WooCommerce install populated with products in order to test these changes, you can use [Smooth Generator](https://github.com/woocommerce/wc-smooth-generator) for that.

Also, you can run `wp wc palt info` before starting your tests, and between testing steps, to verify that the rows and products count stays consistent. As for verifying the table contents, use your favourite database querying tool or simply run `wp db query "select * from wp_wc_product_attributes_lookup where product_or_parent_id=<product id>"`.

1. Try a full table regeneration triggered from the WooCommerce tools page (WooCommerce - Status - Tools). Run the _"Regenerate the product attributes lookup table"_ tool, remove the `&action=regenerate_product_attributes_lookup_table` from the URL once the page has reloaded, and reload the page manually (or run `wp action-scheduler run`) until the button text goes from "Filling in progress" to "Regenerate" again. Try with and without the "Optimized updates" setting being active. Verify that the table updates appropriately.

2. Enable direct lookup table updates (_WooCommerce - Settings - Product - Advanced_, "Direct updates" setting). Try creating a new product, adding a new variation to an existing product, or modifying the attributes for a product. Try with and without the "Optimized updates" setting being active. Verify that the table updates appropriately.

3. Run [the CLI tools](https://github.com/woocommerce/woocommerce/pull/47311) for synchronous product and full table regeneration (`regenerate` and `regenerate_for_product`), with and without the `--disable-db-optimization` argument. Try with a variable product having a lot of variations, the process should be much faster with the optimization.

4. Although not impacted by this pull request, try that deletion and stock status changing on products and variations still update the lookup table as expected.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce/src/Utilities/ArrayUtil.php [hunk 1]
```diff
@@ -286,40 +284,66 @@ private static function deep_compute_or_compare_array_diff( array $array1, array
...
+	 * keys are the distinct column values found, and values are arrays with all the matches found
+	 * (or only the last matching array found, if $single_values is true).
+	 * See ArrayUtilTest for examples.
+	 *
+	 * @param array  $items The array to process.
+	 * @param string $column The name of the key to group by.
+	 * @param bool   $single_values True to only return the last suitable array found for each column value.
+	 * @return array The grouped array.
+	 */
+	public static function group_by_column( array $items, string $column, bool $single_values = false ): array {
```
Comment (coreymckrill) [inline plugins/woocommerce/src/Utilities/ArrayUtil.php:335]: Does [wp_list_pluck](https://developer.wordpress.org/reference/functions/wp_list_pluck/) do basically the same thing?

Comment (coreymckrill) [reply plugins/woocommerce/src/Utilities/ArrayUtil.php:335]: Nevermind, I see from the examples in the unit tests that they're different.

**Comment by coreymckrill** [comment]
@Konamiman I've started looking at this one, but just wanted to note that since #47311 was merged, this one has conflicts.

**Comment by Konamiman** [comment]
Conflicts fixed!

File: plugins/woocommerce/src/Internal/ProductAttributesLookup/LookupDataStore.php [hunk 2]
```diff
@@ -703,11 +745,287 @@ private function add_product_attributes_lookup_table_settings( array $settings,
...
+	 * Core version of create_data_for_product_cpt (doesn't catch exceptions).
+	 *
+	 * @param int $product_id Product or variation id.
+	 * @return void
+	 */
+	private function create_data_for_product_cpt_core( int $product_id ) {
+		global $wpdb;
+
+		$sql = $wpdb->prepare(
+			"delete from {$wpdb->prefix}wc_product_attributes_lookup where product_or_parent_id=%d",
```
Comment (coreymckrill) [inline plugins/woocommerce/src/Internal/ProductAttributesLookup/LookupDataStore.php]:
```suggestion
			"delete from {$this->lookup_table_name} where product_or_parent_id=%d",
```

File: plugins/woocommerce/src/Internal/ProductAttributesLookup/LookupDataStore.php [hunk 3]
```diff
@@ -703,11 +745,287 @@ private function add_product_attributes_lookup_table_settings( array $settings,
...
+		$sql = $wpdb->prepare(
+			"select meta_value from {$wpdb->postmeta} where post_id=%d and meta_key=%s",
+			$main_product_id,
+			'_product_attributes'
+		);
+
+		// phpcs:ignore WordPress.DB.PreparedSQL.NotPrepared
+		$temp = $wpdb->get_var( $sql );
+
+		if ( is_null( $temp ) ) {
```
Comment (coreymckrill) [inline plugins/woocommerce/src/Internal/ProductAttributesLookup/LookupDataStore.php:903]: Might be good to add a code comment here explaining why we're bailing early.

File: plugins/woocommerce/src/Internal/ProductAttributesLookup/LookupDataStore.php [hunk 4]
```diff
@@ -703,11 +745,287 @@ private function add_product_attributes_lookup_table_settings( array $settings,
...
+			$values_strings = array();
+			foreach ( $insert_data_chunk as $dataset ) {
+				$attribute_name   = esc_sql( $dataset[2] );
+				$values_strings[] = "{$dataset[0]},{$dataset[1]},'{$attribute_name}',{$dataset[3]},{$dataset[4]},{$dataset[5]}";
+			}
+
+			$sql .= implode( '),(', $values_strings ) . ')';
+
+			// phpcs:ignore WordPress.DB.PreparedSQL.NotPrepared
+			$wpdb->query( $sql );
```
Comment (coreymckrill) [inline plugins/woocommerce/src/Internal/ProductAttributesLookup/LookupDataStore.php]: Would it be worth capturing/returning the result of this in case there are database errors?

File: plugins/woocommerce/src/Internal/ProductAttributesLookup/LookupDataStore.php [hunk 5]
```diff
@@ -703,11 +745,287 @@ private function add_product_attributes_lookup_table_settings( array $settings,
 					'type'          => 'checkbox',
 					'checkboxgroup' => 'start',
 				);
+
+				$settings[] = array(
+					'title'         => __( 'Optimized updates', 'woocommerce' ),
+					'desc'          => __( 'Use direct database access to retrieve the data needed for updates, instead of the standard WordPress and WooCommerce data store functions.', 'woocommerce' ),
+					'desc_tip'      => __( 'This setting has effect only if products are stored as custom post types.', 'woocommerce' ),
```
Comment (coreymckrill) [inline plugins/woocommerce/src/Internal/ProductAttributesLookup/LookupDataStore.php]:
```suggestion
					'desc_tip'      => __( 'This setting only works when product data is stored in the posts table.', 'woocommerce' ),
```

File: plugins/woocommerce/src/Internal/ProductAttributesLookup/LookupDataStore.php [hunk 6]
```diff
@@ -703,11 +745,287 @@ private function add_product_attributes_lookup_table_settings( array $settings,
 					'type'          => 'checkbox',
 					'checkboxgroup' => 'start',
 				);
+
+				$settings[] = array(
+					'title'         => __( 'Optimized updates', 'woocommerce' ),
+					'desc'          => __( 'Use direct database access to retrieve the data needed for updates, instead of the standard WordPress and WooCommerce data store functions.', 'woocommerce' ),
```
Comment (coreymckrill) [inline plugins/woocommerce/src/Internal/ProductAttributesLookup/LookupDataStore.php]:
```suggestion
					'desc'          => __( 'Uses much more performant queries to update the lookup table, but may not be compatible with some extensions.', 'woocommerce' ),
```

Suggested change to give users more info about why they might want to check the box, or not.

**Review by coreymckrill — COMMENTED** [review]
👍 Worked well in testing. I had 1,500 products (~500 were variable) and without the optimization, the `wc palt regenerate` command took ~10 seconds, but _with_ the optimization, it took 2 seconds!

I think it's theoretically possible, though unlikely, that the attributes for a product could be modified via filter in such a way that the resulting lookup table data would be different when using the direct SQL queries vs the data store methods. I'm not sure there's much we can do to detect or mitigate that, but that's why I added an inline suggestion to change the setting label to let people know that there could be a compatibility issue with some extensions. Wdyt?

Sidenote: this PR probably needs to be rebased again so it can get the fix for the flaky e2e test that is failing.

File: plugins/woocommerce/src/Internal/ProductAttributesLookup/LookupDataStore.php (hunk 3 above)
Comment (Konamiman) [reply plugins/woocommerce/src/Internal/ProductAttributesLookup/LookupDataStore.php:903]: Good idea, added in https://github.com/woocommerce/woocommerce/pull/47700/commits/42bb5252a20060b217393415b4b5c626feca9c1e.

File: plugins/woocommerce/src/Internal/ProductAttributesLookup/LookupDataStore.php (hunk 4 above)
Comment (Konamiman) [reply plugins/woocommerce/src/Internal/ProductAttributesLookup/LookupDataStore.php]: Good catch. And not only that: if something goes wrong during the regeneration process proper log entries would have been written, but the CLI commands would happily say "Success", which is quite confusing. I've changed that in https://github.com/woocommerce/woocommerce/pull/47700/commits/1331c29e5bb7e09aec59f044ee1f02ddf0308d45.

File: plugins/woocommerce/src/Internal/ProductAttributesLookup/DataRegenerator.php [hunk 7]
```diff
@@ -71,6 +78,15 @@ final public function init( LookupDataStore $data_store ) {
 		$this->data_store = $data_store;
 	}
 
+	/**
+	 * Check if the last regeneration step failed.
+	 *
+	 * @return bool True if the last regeneration step failed.
+	 */
+	public function get_last_regeneration_step_feiled() {
```
Comment (coreymckrill) [inline plugins/woocommerce/src/Internal/ProductAttributesLookup/DataRegenerator.php]:
```suggestion
	public function get_last_regeneration_step_failed() {
```

Typo in method name (plus its usages elsewhere)

File: plugins/woocommerce/src/Internal/ProductAttributesLookup/CLIRunner.php [hunk 8]
```diff
@@ -407,20 +431,28 @@ private function regenerate_core( array $args = array(), array $assoc_args = arr
...
-		if ( $processed_count > 0 ) {
-			$progress->tick( $processed_count );
-		}
+		$progress->tick( $processed_count );
 
-		while ( $this->data_regenerator->do_regeneration_step( $batch_size ) ) {
+		$regeneration_step_failed = false;
+		while ( $this->data_regenerator->do_regeneration_step( $batch_size, $use_db_optimization ) ) {
 			$progress->tick( $batch_size );
+			$regeneration_step_failed |= $this->data_regenerator->get_last_regeneration_step_feiled();
```
Comment (coreymckrill) [inline plugins/woocommerce/src/Internal/ProductAttributesLookup/CLIRunner.php]: 🤔 I wasn't sure what `|=` actually does, so I did [a bit of research](https://stackoverflow.com/a/7142105). That didn't totally answer it for me, though, so I did some tests in a scratch file.

* Basically, this throws a fatal error if either side is not numeric or a boolean. In this case, we're dealing with booleans.
* I don't have a super good handle on bitwise operations, but my understanding is if the two sides are numeric and have different positions of `1` in their binary representation, those 1's will combine and form a different number. E.g. 1 |= 4 is the same as `0100 |= 0001` and that will give us `0101` or 5.
* When used with booleans, there's only one bit, so it's not going to give us anything other than a 0 or a 1. But it does recast the result as an integer rather than a boolean.

I guess the usage of `|=` in this context just feels weird and potentially confusing, and I'm wondering if there's a specific reason to use it rather than just doing

```
$regeneration_step_failed = $this->data_regenerator->get_last_regeneration_step_failed();
```

(Same question applies to the other usage in DataRegenerator.php)

Comment (Konamiman) [reply plugins/woocommerce/src/Internal/ProductAttributesLookup/CLIRunner.php]: > I'm wondering if there's a specific reason to use it rather than just doing

It makes sense if you look at the complete loop:

```php
$regeneration_step_failed = false;
while ( $this->data_regenerator->do_regeneration_step( $batch_size, $use_db_optimization ) ) {
	$progress->tick( $batch_size );
	$regeneration_step_failed |= $this->data_regenerator->get_last_regeneration_step_failed();
}
```

I want the variable to be true if _at least one_ of the steps fails, so I'm ORing all the values together; thus the final value of the variable will be true if at least one of the intermediate values was true.

That said: indeed, the `|` operator (or the variant I was using, `|=`) is the _bitwise_ OR operator and while it works with booleans, it's more appropriate to use `||` instead, which is the _logical_ OR operator. There's no `||=` operator in PHP unfortunately, so I've changed it to use `||` repeating the variable name in the left and right sides of the expression.

**Review by coreymckrill — APPROVED** [review]
