### PR TITLE
Fix variation selector display issues on the front end

### LINKED ISSUE #47794: Variation selector display issues on the front end
First reported here: https://github.com/woocommerce/woocommerce/issues/42299

There are a few issues with how the variation selector block is shown on the front-end. Tested in Chrome and Safari on MacOS.

**The dropdown should use the same appearance settings (height, padding, border size and color) as the stepper and the quantity input field.**

image

**On a variable product page, the right padding of the dropdown button is missing.**

image

**The dropdown is unstyled in Safari.**

image

### PR DESCRIPTION
**Pull request by octaedro**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

There were a couple of visual problems with the variation selector.
- We weren't applying the styles we usually use for selectors on the product page.
- The chevron alignment was fixed as well.   

Before

Screenshot 2024-08-28 at 12 40 19 PM

After

Screenshot 2024-08-29 at 10 50 24 AM

Closes #47794.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Create a new variable product with some variations.
2. Go to Pages > Add New Page.
3. Add a `Single product` block and select the product you just created.
4. Publish it and go to the page.
5. Verify the variation selector styles were applied correctly, at least in Chrome, Safari, Firefox, etc. The chevron should be aligned correctly as well.
6. Verify the product also looks correct.

https://github.com/user-attachments/assets/967e407b-9679-4f80-a86c-796001706fe6

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce-blocks/assets/js/blocks/single-product/save.tsx [hunk 1]
```diff
@@ -4,7 +4,9 @@
 import { InnerBlocks, useBlockProps } from '@wordpress/block-editor';
 
 const Save = () => {
-	const blockProps = useBlockProps.save();
+	const blockProps = useBlockProps.save( {
+		className: 'woocommerce',
```
Comment (octaedro) [inline plugins/woocommerce-blocks/assets/js/blocks/single-product/save.tsx:8]: Unlike the product page, the `single-product` block doesn't add the `woocommerce` class, which is needed to apply the missing styles in the selector.

File: plugins/woocommerce/client/legacy/css/woocommerce.scss [hunk 2]
```diff
@@ -445,6 +445,18 @@ p.demo_store,
...
+					/* We hide the default chevron because it cannot be directly modified. Instead, we add a custom chevron using a background image. */
+					appearance: none;
+					-webkit-appearance: none;
+					-moz-appearance: none;
+					padding-right: 2em;
+					background: url(data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgc3Ryb2tlPSJibGFjayIgc3Ryb2tlLXdpZHRoPSIyIiBzdHJva2UtbGluZWNhcD0icm91bmQiIHN0cm9rZS1saW5lam9pbj0icm91bmQiIGNsYXNzPSJmZWF0aGVyIGZlYXRoZXItY2hldnJvbi1kb3duIj48cG9seWxpbmUgcG9pbnRzPSI2IDkgMTIgMTUgMTggOSI+PC9wb2x5bGluZT48L3N2Zz4=)
+						no-repeat;
+					background-size: 16px;
+					-webkit-background-size: 16px;
+					background-position: calc(100% - 12px) 50%;
```
Comment (octaedro) [inline plugins/woocommerce/client/legacy/css/woocommerce.scss:458]: In order to increase the [gap between the chevron and the edge of the selector](https://github.com/woocommerce/woocommerce/issues/47794#issuecomment-2316956615), we needed to hide the default WebKit chevron (because it's not modifiable) and add a custom one, positioning it accordingly.
// cc @j111q

Comment (ObliviousHarmony) [reply plugins/woocommerce/client/legacy/css/woocommerce.scss:458]: It's definitely more than a little weird that this isn't something browsers have already solved with pseudo-elements 😅 I can confirm though that _there is no other way to do this_!

**Review by ObliviousHarmony — COMMENTED** [review]
Thanks @octaedro, the extra spacing on the design just plain looks better!

With that said, I do have concerns about putting the `woocommerce` class on the block. As folks build more FSE themes I'd wager we're inevitably going to run into more problems with the missing `<body>` classes. These classes are intended to be added on any page that has WooCommerce content and arguably any post, page, or template with one of our blocks fits that definition.

Howow would you feel about us taking a look at a broader solution? The `woocommerce` class (along with others) is added to the `<body>` tag using the `wc_body_class()` function. I'm not sure how possible or trivial it is, however, it seems reasonable to add some of these classes when a page has one of our blocks on it.

**Review by ObliviousHarmony — APPROVED** [review]
After discussing it with @octaedro we decided that the best course of action is to create a GitHub discussion about the body class and merge this PR as-is. It worked when I tested it so I'm going to go ahead and approve.

**Comment by ResponsiveFlow** [comment]
The issue is still present on safari
Screenshot 2024-09-01 at 5 51 26 PM

**Comment by octaedro** [comment]
Thank you @tomxygen, for reporting this,

Just to check, did you remove the block and add it again? Otherwise, the changes won't be applied.

What version of Safari are you using? I'm testing on Safari Version 17.6 (19618.3.11.11.5), and it's working well here.
