### PR TITLE
[Checkout] Local Pickup rates should be available regardless of shipping restrictions

### LINKED ISSUE #55253: Local pickup options are dependent on the customer's billing address
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

The following refers to the **new** Local Pickup option within a Checkout block - not the legacy local pickup functionality.

1. User arrives on the checkout page
2. User selects the Pickup option
3. User chooses a pickup location
4. User begins to fill-in their billing address
5. User selects a country other than the one the pickup location is in (for example, a customer in Canada is purchasing from a store in the UK)
6. User enters a their name, address, city and privince
7. User enters their Postal Code
8. Observe how the pickup option and pickup locations disappear

### Expected behavior

If a customer has chosen the **Pickup** option, entering their address should not remove the Pickup option or any pickup locations.

Pickup locations should not be determined by the customer's billing address. There are a number of valid use cases for a customer entering a billing address for one country and placing an order for collection from a store in another country (eg. ordering a gift for a friend to pickup, placing an order while on holiday or extended visit to another country)

### Actual behavior

Upon entering their **billing** address:

- The list of pickup locations disappears
- The Ship/Pickup selector disappears
- The "Pickup locations" heading remains on-screen
- No error message is displayed
- "No available delivery option" is shown in the order summary panel (sidebar)

This leaves the customer unable to checkout and with little visual feedback as to what the probelm is.

### Steps to reproduce

In WooCommerce settings:

Under Settings > General > General Options
- Set Selling location(s) to "Sell to all countries"
- Set Shipping location(s) to "Ship to specific countries only"
- Set Ship to specific countries to "United Kingdom (UK"

As a user:

1. User arrives on the checkout page
2. User selects the Pickup option
3. User chooses a pickup location
4. User begins to fill-in their billing address
5. User selects a country other than the one the pickup location is in (for example, a customer in Canada is purchasing from a store in the UK)
6. User enters a their name, address, city and privince
7. User enters their Postal Code

### WordPress Environment

<details><summary>System Status Report</summary>

```
### WordPress Environment ###

WordPress address (URL): [Redacted]
Site address (URL): [Redacted]
WC Version: 9.6.1
Legacy REST API Package Version: The Legacy REST API plugin is not installed on this site.
Action Scheduler Version: ✔ 3.9.0
Log Directory Writable: ✔
WP Version: 6.7.1
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 8.1.31
PHP Post Max Size: 2 GB
PHP Time Limit: 850
PHP Max Input Vars: 6144
cURL Version: 8.12.0
OpenSSL/1.1.1w

SUHOSIN Installed: –
MySQL Version: 10.6.18-MariaDB-log
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

[REDACTED]

### Post Type Counts ###

acf-taxonomy: 2
attachment: 12303
customize_changeset: 128
custom_css: 1
feedback: 10261
forminator_forms: 5
jetpack_migration: 2
jp_img_sitemap: 37
jp_img_sitemap_index: 7
jp_sitemap: 21
jp_sitemap_index: 7
jp_sitemap_master: 7
list: 21
ml-slide: 124
ml-slider: 13
nav_menu_item: 56
page: 63
post: 3
postman_sent_mail: 16
product: 5739
product_variation: 286
revision: 2750
shop_coupon: 13
shop_order: 24185
shop_order_refund: 577
sp_wps_shortcodes: 48
woostockalert: 4
wpcode: 6
wp_block: 5
wp_global_styles: 3
wp_navigation: 6
wp_template: 5
wp_template_part: 4

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (33) ###

Admin and Site Enhancements (ASE): by wpase.com – 7.6.9
Advanced Custom Fields PRO: by WP Engine – 6.3.12
Akismet Anti-spam: Spam Protection: by Automattic - Anti-spam Team – 5.3.6
BCS BatchLine Book Importer: by BCS Studio – 1.6.16
Block Manager: by Darren Cooney – 3.1.0
Block Visibility: by Nick Diego – 3.7.1
Code Snippets: by Code Snippets Pro – 3.6.7
Enable Button Icons: by Nick Diego – 0.1.0
Forminator: by WPMU DEV – 1.39.1
Google for WooCommerce: by WooCommerce – 2.9.8
The Icon Block: by Nick Diego – 2.0.0
WPCode Lite: by WPCode – 2.2.5
Jetpack: by Automattic – 14.3
Mailchimp for WooCommerce: by Mailchimp – 5.2
Page Optimize: by Automattic – 0.5.6
Redirection: by John Godley – 5.5.1
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 3.1.6
Relevanssi: by Mikko Saari – 4.24.3
Storysmith Blocks: by Andrew Viney – 1.3
Storysmith Page to List Migrator: by Andrew Viney – 1.0
Storysmith Tweaks: by Andrew Viney – 1.3
Temporary Login Without Password: by StoreApps – 1.8.5
WP Sheet Editor - WooCommerce Products: by WP Sheet Editor – 1.7.7
WooCommerce.com Update Manager: by Automattic – 1.0.3
WooCommerce Back In Stock Notifications: by Woo – 3.0.0
WooCommerce Stripe Gateway: by Stripe – 9.1.1
WooPayments: by WooCommerce – 8.9.1
WooCommerce Shipping & Tax: by WooCommerce – 2.8.7
WooCommerce: by Automattic – 9.6.1
WP Mail Logging: by WP Mail Logging Team – 1.14.0
WP Mail SMTP: by WP Mail SMTP – 4.3.0
WPForms Lite: by WPForms – 1.9.3.2
Yet Another Related Posts Plugin (YARPP): by YARPP – 5.30.11

### Inactive Plugins (17) ###

All-in-One WP Migration: by ServMask – 7.89
AMP: by AMP Project Contributors – 2.5.5
Classic Editor: by WordPress Contributors – 1.6.7
CoBlocks: by GoDaddy – 3.1.14
Gutenberg: by Gutenberg Team – 20.0.0
Health Check & Troubleshooting: by The WordPress.org community – 1.7.1
Layout Grid: by Automattic – 1.8.4
MetaSlider: by MetaSlider – 3.95.0
NationalBookTokens: by INVDP / Reuben Digital Ltd – 3.2
Post SMTP: by Post SMTP – 3.0.2
Post Type Switcher: by Triple J Software
Inc. – 3.3.1

Product Slider for WooCommerce: by ShapedPlugin LLC – 2.8.4
Product Slider Pro for WooCommerce: by ShapedPlugin – 3.4.0
Product Stock Waitlist Manager for WooCommerce: by MultiVendorX – 2.5.15
Related Products for WooCommerce: by WebToffee – 1.6.0
WooCommerce PayPal Payments: by WooCommerce – 2.9.6
WPB Product Slider for WooCommerce: by wpbean – 2.0.9.9

### Dropin Plugins () ###

advanced-cache.php: advanced-cache.php
object-cache.php: Memcached

### Must Use Plugins (2) ###

Health Check Troubleshooting Mode: by  – 1.7.2
wpcomsh-loader.php: by  –

### Settings ###

Legacy API Enabled: –
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 25 MB

### WC Pages ###

Shop base: ❌ Page not set
Cart: #1574 - /cart/ -  Contains the [woocommerce_cart] shortcode
Checkout: #1575 - /checkout/ -  Contains the woocommerce/checkout block
My account: #1576 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Bokiz
Version: 1.5.1
Author URL: https://www.itsviney.com
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
Theme type: Block theme
WooCommerce Support: ❌ Not declared

### Templates ###

Overrides: bokiz/woocommerce/cart/cart-empty.php
bokiz/woocommerce/cart/cart-item-data.php
bokiz/woocommerce/cart/cart-shipping.php
bokiz/woocommerce/cart/cart-totals.php
bokiz/woocommerce/cart/cart.php
bokiz/woocommerce/cart/cross-sells.php version 4.4.0 is out of date. The core version is 9.6.0
bokiz/woocommerce/cart/proceed-to-checkout-button.php
bokiz/woocommerce/cart/shipping-calculator.php version 7.0.1 is out of date. The core version is 9.5.0
bokiz/woocommerce/myaccount/dashboard.php
bokiz/woocommerce/myaccount/downloads.php
bokiz/woocommerce/myaccount/form-add-payment-method.php
bokiz/woocommerce/myaccount/form-edit-account.php version 8.7.0 is out of date. The core version is 9.6.0
bokiz/woocommerce/myaccount/form-edit-address.php
bokiz/woocommerce/myaccount/form-login.php
bokiz/woocommerce/myaccount/form-lost-password.php
bokiz/woocommerce/myaccount/form-reset-password.php
bokiz/woocommerce/myaccount/lost-password-confirmation.php
bokiz/woocommerce/myaccount/my-account.php
bokiz/woocommerce/myaccount/my-address.php
bokiz/woocommerce/myaccount/my-downloads.php
bokiz/woocommerce/myaccount/my-orders.php
bokiz/woocommerce/myaccount/navigation.php
bokiz/woocommerce/myaccount/orders.php version 9.2.0 is out of date. The core version is 9.5.0
bokiz/woocommerce/myaccount/payment-methods.php
bokiz/woocommerce/myaccount/view-order.php
/wordpress/plugins/woocommerce/9.6.1/templates/block-notices/error.php
/wordpress/plugins/woocommerce/9.6.1/templates/block-notices/notice.php
/wordpress/plugins/woocommerce/9.6.1/templates/block-notices/success.php
bokiz/parts/checkout-header.html
bokiz/parts/mini-cart.html
bokiz/templates/archive-product.html
bokiz/templates/coming-soon.html
bokiz/templates/order-confirmation.html
bokiz/templates/page-cart.html
bokiz/templates/page-checkout.html
bokiz/templates/product-search-results.html
bokiz/templates/single-product.html
bokiz/templates/taxonomy-product_tag.html

Outdated Templates: ❌
					
					
						Learn how to update					 |
					
						
					
					
						Clear system status theme info cache

### WooPayments ###

Version: 8.9.1
Connected to WPCOM: Yes
WPCOM Blog ID: 150875142
Account ID: acct_1Ns1hsFjPdUMF3qc
Payment Gateway: Enabled
Test Mode: Disabled
Enabled APMs: card
WooPay: Not eligible
Apple Pay / Google Pay: Disabled
Fraud Protection Level: basic
Multi-currency: Enabled
Auth and Capture: Disabled
Documents: Enabled
Logging: Enabled

### Back In Stock ###

Database Version: 3.0.0
Loopback Test: ✔

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
onboarding
onboarding-tasks
pattern-toolkit-full-composability
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
printful
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page
launch-your-store

Disabled Features: product-data-views
experimental-blocks
coming-soon-newsletter-template
minified-js
product-pre-publish-modal
settings
async-product-editor-category-field
product-editor-template-system
blueprint
reactify-classic-payments-settings
use-wp-horizon
add-to-cart-with-options-stepper-layout
blockified-add-to-cart

Daily Cron: ✔ Next scheduled: 2025-02-07 18:38:45 +00:00
Options: ✔
Notes: 235
Onboarding: completed

### Action Scheduler ###

Canceled: 289
Oldest: 2025-01-08 08:02:28 +0000
Newest: 2025-02-07 13:58:13 +0000

Complete: 10,968
Oldest: 2025-01-07 17:04:03 +0000
Newest: 2025-02-07 17:00:28 +0000

Failed: 67
Oldest: 2022-11-02 21:02:48 +0000
Newest: 2024-12-12 17:15:15 +0000

Pending: 13
Oldest: 2025-02-07 17:01:28 +0000
Newest: 2025-02-11 16:32:43 +0000


### Status report information ###

Generated at: 2025-02-07 17:01:13 +00:00
```
</details>

### Isolating the problem

- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by mikejolley**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Local Pickup is a "shipping method" but it shouldn't care about shipping address. There was a bug in block checkout where if you had a certain setup with restricted shipping locations, depending on the billing address, local pickup options could vanish. This PR fixes this issue and some related bugs.

Closes #55253

I will leave some notes inline but the reviewer may want to review with me in case a change is not clear.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Under WC > Settings, use the following settings:
Screenshot 2025-04-01 at 16 16 54

2. Enable Local Pickup and some other shipping rates
3. Go to block checkout. 
4. Select Local Pickup
5. Enter a billing address for the US
6. Local Pickup should not disappear and you should be able to place the order
7. Repeat the test in classic checkout. You will see a notice stating that you cannot ship to your chosen country. _I chose to leave the existing behaviour in place for classic checkout since it has different UI._

For the country validation,

1. Use a setup like this:
Screenshot 2025-04-03 at 12 31 23

2. Go to checkout and try selecting invalid billing and shipping countries.
3. Confirm you see notices when the choice is not valid:
Screenshot 2025-04-03 at 12 29 29

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce/client/blocks/assets/js/base/context/hooks/use-show-shipping-total-warning.ts [hunk 1]
```diff
@@ -53,7 +53,7 @@ export const useShowShippingTotalWarning = () => {
 		if ( hasMismatch && ! isShowingNotice ) {
 			createInfoNotice(
 				__(
-					'Totals will be recalculated when a valid shipping method is selected.',
+					'Totals will be recalculated when a valid shipping option is selected.',
```
Comment (mikejolley) [inline plugins/woocommerce/client/blocks/assets/js/base/context/hooks/use-show-shipping-total-warning.ts]: Inconsistency; we use "options" verbiage on checkout frontend

File: plugins/woocommerce/client/blocks/assets/js/base/context/providers/cart-checkout/checkout-processor.ts [hunk 2]
```diff
@@ -177,7 +177,7 @@ const CheckoutProcessor = () => {
 				return {
 					type: responseTypes.ERROR,
 					errorMessage: __(
-						'Sorry, this order requires a shipping option.',
+						'This order requires a shipping option.',
```
Comment (mikejolley) [inline plugins/woocommerce/client/blocks/assets/js/base/context/providers/cart-checkout/checkout-processor.ts]: These messages were apologetic so changed to get to the point.

File: plugins/woocommerce/client/blocks/assets/js/settings/blocks/constants.ts [hunk 3]
```diff
@@ -76,44 +76,29 @@ const countryData = getSetting< Record< string, CountryData > >(
...
-			return countryData[ countryCode ].allowBilling === true;
-		} )
-		.map( ( countryCode ) => {
-			return [ countryCode, countries[ countryCode ] || '' ];
-		} )
+// Previously we had separate ALLOWED_COUNTRIES and SHIPPING_COUNTRIES (as well as states), however, this lead to problems
+// when syncing values between billing and shipping if some countries were not available for shipping or vice versa. To get
+// around this, we combine countries available for billing and/or shipping so all are available for selection. Invalid
+// combinations are validated on post.
+const availableCountries = Object.keys( countryData ).filter(
```
Comment (mikejolley) [inline plugins/woocommerce/client/blocks/assets/js/settings/blocks/constants.ts]: This change was to prevent the checkout reaching a broken state. You can reproduce this in trunk by having a US address on your account for shipping/billing, and then changing "selling" countries to only the UK. When you reach checkout, UK will be selected, but the postcode validation will fail, because the server still thinks you're using a US address.

Since we sync between billing and shipping, to get around problems where some countries are allowed or disallowed for shipping or billing, we need to consolidate both lists of countries.  If you end up trying to place an order from somewhere not allowed, or try to ship to somewhere not allowed, that will be caught on validation when you place order.

File: plugins/woocommerce/includes/admin/meta-boxes/class-wc-meta-box-order-data.php [hunk 4]
```diff
@@ -159,7 +159,7 @@ protected static function get_shipping_fields( $order = false, $context = 'edit'
 					'show'    => false,
 					'type'    => 'select',
 					'class'   => 'js_field-country select short',
-					'options' => array( '' => __( 'Select a country / region&hellip;', 'woocommerce' ) ) + WC()->countries->get_shipping_countries(),
+					'options' => array( '' => __( 'Select a country / region&hellip;', 'woocommerce' ) ) + WC()->countries->get_countries(),
```
Comment (mikejolley) [inline plugins/woocommerce/includes/admin/meta-boxes/class-wc-meta-box-order-data.php:162]: Similar to https://github.com/woocommerce/woocommerce/pull/56922/files#r2023093633, there should be no restriction in the admin area of what counties are shown. Otherwise the real value will be hidden if the country is no longer allowed after settings change.

File: plugins/woocommerce/includes/class-wc-cart.php [hunk 5]
```diff
@@ -1506,15 +1507,7 @@ public function calculate_shipping() {
...
-		$chosen_methods = array();
-		// Get chosen methods for each package to get our totals.
-		foreach ( $calculated_shipping_packages as $key => $package ) {
-			$chosen_method = wc_get_chosen_shipping_method_for_package( $key, $package );
-			if ( $chosen_method ) {
-				$chosen_methods[ $key ] = $package['rates'][ $chosen_method ];
-			}
-		}
-		return $chosen_methods;
+		return ShippingUtil::get_selected_shipping_rates_from_packages( $calculated_shipping_packages );
```
Comment (mikejolley) [inline plugins/woocommerce/includes/class-wc-cart.php:1510]: Moved to util for reuse.

File: plugins/woocommerce/includes/class-wc-checkout.php [hunk 6]
```diff
@@ -954,11 +954,6 @@ protected function validate_checkout( &$data, &$errors ) {
 
 			if ( empty( $shipping_country ) ) {
 				$errors->add( 'shipping', __( 'Please enter an address to continue.', 'woocommerce' ) );
-			} elseif ( ! in_array( $shipping_country, array_keys( WC()->countries->get_shipping_countries() ), true ) ) {
-				if ( WC()->countries->country_exists( $shipping_country ) ) {
-					/* translators: %s: shipping location (prefix e.g. 'to' + ISO 3166-1 alpha-2 country code) */
-					$errors->add( 'shipping', sprintf( __( 'Unfortunately <strong>we do not ship %s</strong>. Please enter an alternative shipping address.', 'woocommerce' ), WC()->countries->shipping_to_prefix( $shipping_country ) . ' ' . $shipping_country ) );
-				}
```
Comment (mikejolley) [inline plugins/woocommerce/includes/class-wc-checkout.php]: This validation should not be needed. Shipping rates will not return if the destination country is invalid.

File: plugins/woocommerce/includes/class-wc-order.php [hunk 7]
```diff
@@ -1690,7 +1691,7 @@ public function needs_shipping_address() {
 			return false;
 		}
 
-		$hide          = apply_filters( 'woocommerce_order_hide_shipping_address', array( 'local_pickup' ), $this );
+		$hide          = apply_filters( 'woocommerce_order_hide_shipping_address', array_merge( LocalPickupUtils::get_local_pickup_method_ids(), array( 'local_pickup' ) ), $this );
```
Comment (mikejolley) [inline plugins/woocommerce/includes/class-wc-order.php]: Missing other local pickup methods.

File: plugins/woocommerce/includes/class-wc-shipping.php [hunk 8]
```diff
@@ -334,28 +333,36 @@ public function calculate_shipping_for_package( $package = array(), $package_key
...
-					 * @param WC_Shipping_Method $shipping_method Shipping method instance.
-					 */
-					do_action( 'woocommerce_after_get_rates_for_package', $package, $shipping_method );
+				// If the shipping method supports shipping zones and is not an instance, skip it.
+				if ( $shipping_method->supports( 'shipping-zones' ) && ! $shipping_method->get_instance_id() ) {
+					continue;
+				}
+
+				// If the package is not shippable and the shipping method does not support local pickup, skip it.
+				if ( ! $is_shippable && ! $shipping_method->supports( 'local-pickup' ) ) {
```
Comment (mikejolley) [inline plugins/woocommerce/includes/class-wc-shipping.php]: This line allows local pickup rates to be returned even if the "shipping country" is invalid according to settings.

File: plugins/woocommerce/src/Blocks/Shipping/PickupLocation.php [hunk 9]
```diff
@@ -38,7 +38,7 @@ public function __construct() {
 	 */
 	public function init() {
 		$this->enabled          = $this->get_option( 'enabled' );
-		$this->title            = $this->get_option( 'title' );
+		$this->title            = $this->get_option( 'title', __( 'Pickup', 'woocommerce' ) );
```
Comment (mikejolley) [inline plugins/woocommerce/src/Blocks/Shipping/PickupLocation.php:41]: In some instances, title was missing on classic checkout. I assume its because the default is blank.

File: plugins/woocommerce/src/StoreApi/Utilities/OrderController.php [hunk 10]
```diff
@@ -364,44 +365,59 @@ protected function validate_email( \WC_Order $order ) {
...
+			$selected_shipping_rates  = ShippingUtil::get_selected_shipping_rates_from_packages( WC()->shipping()->get_packages() );
+			$is_local_pickup_selected = array_all(
+				$selected_shipping_rates,
+				function ( $rate ) use ( $local_pickup_method_ids ) {
+					return in_array( $rate->get_method_id(), $local_pickup_method_ids, true );
+				}
+			);
+
+			// If only local pickup is selected, we don't need to validate the shipping country.
+			if ( ! $is_local_pickup_selected && ! $this->validate_allowed_country( $shipping_country, (array) wc()->countries->get_shipping_countries() ) ) {
```
Comment (mikejolley) [inline plugins/woocommerce/src/StoreApi/Utilities/OrderController.php]: Skip validation if only using local pickup.

File: plugins/woocommerce/src/StoreApi/Utilities/OrderController.php [hunk 11]
```diff
@@ -368,19 +371,31 @@ protected function validate_addresses( \WC_Order $order, bool $needs_shipping )
...
-					$shipping_country
-				),
-				400,
-				array(
-					'allowed_countries' => array_keys( wc()->countries->get_shipping_countries() ),
-				)
+		if ( $needs_shipping ) {
+			$local_pickup_method_ids  = LocalPickupUtils::get_local_pickup_method_ids();
+			$selected_shipping_rates  = ShippingUtil::get_selected_shipping_rates_from_packages( WC()->shipping()->get_packages() );
+			$is_local_pickup_selected = array_all(
```
Comment (mikejolley) [inline plugins/woocommerce/src/StoreApi/Utilities/OrderController.php]: Clarify naming for "all"

File: plugins/woocommerce/src/StoreApi/Utilities/OrderController.php [hunk 12]
```diff
@@ -368,19 +371,31 @@ protected function validate_addresses( \WC_Order $order, bool $needs_shipping )
...
+				$selected_shipping_rates,
+				function ( $rate ) use ( $local_pickup_method_ids ) {
+					return in_array( $rate->get_method_id(), $local_pickup_method_ids, true );
+				}
 			);
+
+			// If only local pickup is selected, we don't need to validate the shipping country.
+			if ( ! $is_local_pickup_selected && ! $this->validate_allowed_country( $shipping_country, (array) wc()->countries->get_shipping_countries() ) ) {
```
Comment (mikejolley) [inline plugins/woocommerce/src/StoreApi/Utilities/OrderController.php]: Unit test this

File: plugins/woocommerce/includes/class-wc-shipping.php [hunk 13]
```diff
@@ -334,6 +333,11 @@ public function calculate_shipping_for_package( $package = array(), $package_key
 
 		if ( ! is_array( $stored_rates ) || $package_hash !== $stored_rates['package_hash'] || 'yes' === get_option( 'woocommerce_shipping_debug_mode', 'no' ) ) {
 			foreach ( $this->load_shipping_methods( $package ) as $shipping_method ) {
+				// If the package is not shippable and the shipping method does not support local pickup, skip it.
+				if ( ! $is_shippable && ! $shipping_method->supports( 'local-pickup' ) ) {
```
Comment (mikejolley) [inline plugins/woocommerce/includes/class-wc-shipping.php]: Unit test this; confirm local pickup comes back

File: plugins/woocommerce/src/StoreApi/Utilities/OrderController.php (hunk 12 above)
Comment (mikejolley) [reply plugins/woocommerce/src/StoreApi/Utilities/OrderController.php]: Test virtual products return no shipping or pickup

File: plugins/woocommerce/includes/admin/meta-boxes/class-wc-meta-box-order-data.php (hunk 4 above)
Comment (senadir) [reply plugins/woocommerce/includes/admin/meta-boxes/class-wc-meta-box-order-data.php:162]: Wouldn't this cause a painful list of scroll?

File: plugins/woocommerce/src/StoreApi/Utilities/LocalPickupUtils.php [hunk 14]
```diff
@@ -82,7 +82,7 @@ function ( $methods, $method ) {
 				}
 				return $methods;
 			},
-			array()
+			array( 'local_pickup' )
```
Comment (senadir) [inline plugins/woocommerce/src/StoreApi/Utilities/LocalPickupUtils.php:85]: Was it not included?

**Review by senadir — APPROVED** [review]
Thank you for the tests and changes Mike, I first tested this without actually building, which showed the frustrating experience of being locked out to a country you can't ship to, this is much better.
