### PR TITLE
Fix `Single product` translations on edit mode

### LINKED ISSUE #50049: Problems with displaying "Single Product" block translations
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

The title and description of the "**Single Product**" block is not always shown translated

### Expected behavior

The title and description of the "**Single Product**" block is always shown translated

### Actual behavior

The title and description of the "**Single Product**" block is not always shown translated

### Steps to reproduce

Screenshot (Spanish)

wc-single-product

### WordPress Environment

<details><summary>System Status Report</summary>

```
### WordPress Environment ###

WordPress address (URL): [Redacted]
Site address (URL): [Redacted]
WC Version: 9.1.4
Legacy REST API Package Version: El plugin Legacy REST API no está instalado en este sitio.
Action Scheduler Version: ✔ 3.7.4
Log Directory Writable: ✔
WP Version: 6.6.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: es_ES
External object cache: –

### Server Environment ###

Server Info: TasteWP-S3 Official/3.0.0
PHP Version: 8.0.30
PHP Post Max Size: 128 MB
PHP Time Limit: 100
PHP Max Input Vars: 5000
cURL Version: 7.68.0
OpenSSL/1.1.1f

SUHOSIN Installed: –
MySQL Version: 8.0.32-0ubuntu0.20.04.2
Max Upload Size: 60 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

[REDACTED]

### Post Type Counts ###

attachment: 1
elementor_library: 1
page: 13
post: 2
product: 1
revision: 2
wp_global_styles: 1
wp_navigation: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ❌Los mensajes de error no deberían mostrarse a los visitantes.

### Active Plugins (1) ###

WooCommerce: por Automattic – 9.1.4

### Inactive Plugins (7) ###

Backup Migration: por Inisev – 1.4.6
Copy & Delete Posts: por Inisev – 1.4.7
Elementor: por Elementor.com – 3.23.3
Loco Translate: por Tim Whitlock – 2.6.11
MyPopUps: por Inisev – 1.2.6
Redirect Redirection: por Inisev – 1.2.3
String Locator: por InstaWP – 2.6.5

### Dropin Plugins () ###

maintenance.php: maintenance.php

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 días
Level threshold: –
Log directory size: 13 B

### WC Pages ###

Base de la tienda: #13 - /negozio/
Carrito: #14 - /carrello/ -  Contiene el bloque woocommerce/cart
Finalizar compra: #15 - /pagamento/ -  Contiene el bloque woocommerce/checkout
Mi cuenta: #16 - /mio-account/
Términos y condiciones: ❌ Página sin definir

### Theme ###

Name: Twenty Twenty-Three
Version: 1.5
Author URL: https://es.wordpress.org
Child Theme: ❌ – Si estás modificando WooCommerce en un tema padre que no has creado personalmente
te recomendamos utilizar un tema hijo. Ver: Cómo crear un tema hijo

WooCommerce Support: ✔

### Templates ###

Overrides: /s3-selfishhouses/wordpress/wp-content/plugins/woocommerce/templates/block-notices/error.php
/s3-selfishhouses/wordpress/wp-content/plugins/woocommerce/templates/block-notices/notice.php
/s3-selfishhouses/wordpress/wp-content/plugins/woocommerce/templates/block-notices/success.php


### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page
launch-your-store

Disabled Features: experimental-blocks
minified-js
pattern-toolkit-full-composability
product-pre-publish-modal
printful
settings
async-product-editor-category-field
product-editor-template-system

Daily Cron: ✔ Next scheduled: 2024-07-27 21:02:19 +00:00
Options: ✔
Notes: 57
Onboarding: skipped

### Action Scheduler ###

Completo: 3
Oldest: 2024-07-26 21:03:24 +0000
Newest: 2024-07-27 07:49:58 +0000

Pendiente: 1
Oldest: 2024-07-27 21:03:24 +0000
Newest: 2024-07-27 21:03:24 +0000


### Status report information ###

Generated at: 2024-07-27 08:00:25 +00:00
```
</details>

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by albarin**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes https://github.com/woocommerce/woocommerce/issues/50049

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Go to `wp-admin/options-general.php` and change the language to a 100% translated one (like Spanish or Italian).
2. Create a new page or post.
3. Insert the `Single Product` block.
4. Check that the title and description of the block in edit mode are translated.

| Before | After |
|--------|--------|
| Screenshot 2024-08-12 at 16 00 32 | Screenshot 2024-08-12 at 15 58 48 |

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [x] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 
Single product block - Fix translation for title and description in edit mode.
</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce-blocks/assets/js/blocks/single-product/edit/index.tsx [hunk 1]
```diff
@@ -53,6 +53,10 @@ const Editor = ( {
 	const [ isEditing, setIsEditing ] = useState( ! productId );
 	const blockProps = useBlockProps();
 
+	const block = useSelect( ( select ) =>
+		select( 'core/blocks' ).getBlockType( metadata.name )
+	);
```
Comment (gigitux) [inline plugins/woocommerce-blocks/assets/js/blocks/single-product/edit/index.tsx]:
```suggestion
	const block = useSelect( ( select ) =>
		select( 'core/blocks' ).getBlockType( metadata.name ), [ ]);
```

Let's pass an empty array as a dependency array, so `getBlockType` is invoked only one time.

**Review by gigitux — APPROVED** [review]
Thanks for working on this! LGTM! I'm pre-approving the PR, but before merging the PR, let's ensure that an empty array is added as a dependency array.

File: plugins/woocommerce-blocks/assets/js/blocks/single-product/edit/index.tsx (hunk 1 above)
Comment (albarin) [reply plugins/woocommerce-blocks/assets/js/blocks/single-product/edit/index.tsx]: Done, thanks!
