### PR TITLE
Keep legacy and wc-admin version of db update notice in sync

### LINKED ISSUE #60367: Update WooCommerce Database button leads to expired page
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Hi,

I've had this on multiple websites the past few weeks, with multiple versions of WooCommerce. 

After updating WooCommerce, and being shown the "Update WooCommerce Database", clicking the button simply leads you to a page that shows the following error message:

```
The link you followed has expired.
Please try again.
```

'Please try again' is linked, and clicking it simply takes you back to the General Tab within WooCommerce settings, which then shows the same Dashboard notification prompting you to click the "Update WooCommerce Database" button.

Image

### Expected behavior

It should start the WooCommerce database update task.

### Actual behavior

It takes you to an error page as shown in the screenshot above.

### Steps to reproduce

1. Update WooCommerce
2. When prompted to click the "Update WooCommerce Database" button, click it.
3. See if it takes you to a page with the expired link notice

### WordPress Environment

<details>

<summary>WordPress Environment</summary>

<details><summary>System Status Report</summary>

```
### WordPress Environment ###

WordPress address (URL): [Redacted]
Site address (URL): [Redacted]
WC Version: 10.0.3
Legacy REST API Package Version: The Legacy REST API plugin is not installed on this site.
Action Scheduler Version: ✔ 3.9.2
Log Directory Writable: ✔
WP Version: 6.8.2
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: –
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
Server Architecture: Linux 4.18.0 x86_64
PHP Version: 8.1.33
PHP Post Max Size: 100 MB
PHP Time Limit: 300
PHP Max Input Vars: 1000
cURL Version: 7.61.1
OpenSSL/1.1.1k

SUHOSIN Installed: –
MySQL Version: 10.6.23-MariaDB
Max Upload Size: 100 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

[REDACTED]

### Post Type Counts ###

acf-field: 3
acf-field-group: 1
attachment: 694
elementor_library: 5
itsec-dash-card: 7
itsec-dashboard: 1
nav_menu_item: 10
oembed_cache: 2
page: 17
post: 1
product: 403
revision: 1062
shop_order: 47
shop_order_refund: 2
tt_font_control: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (19) ###

Advanced Custom Fields: by WP Engine – 6.4.2
Autoptimize: by Frank Goossens (futtta) – 3.1.13
Solid Backups – Legacy: by SolidWP – 9.1.17
Classic Editor: by WordPress Contributors – 1.6.7
Classic Widgets: by WordPress Contributors – 0.3
Display User Registration Date: by Anthony Hortin – 1.0.1
Elementor Pro: by Elementor.com – 3.31.2
Elementor: by Elementor.com – 3.31.2
Essential Addons for Elementor - Pro: by WPDeveloper – 6.4.1
Essential Addons for Elementor: by WPDeveloper – 6.2.1
GA Google Analytics: by Jeff Starr – 20250326
Gravity Forms: by Gravity Forms – 2.9.13
Solid Security Pro: by SolidWP – 8.5.8
Simple Cloudflare Turnstile: by Elliot Sowersby, RelyWP – 1.32.0
WooCommerce Stripe Gateway: by Stripe – 9.8.0
WooCommerce: by Automattic – 10.0.3 (update to version 10.1.0 is available)
Yoast SEO: by Team Yoast – 25.5
WP Super Cache: by Automattic – 3.0.0
YITH WooCommerce Category Accordion: by YITH – 1.6.0

### Inactive Plugins (0) ###


### Dropin Plugins () ###

advanced-cache.php: advanced-cache.php

### Settings ###

Legacy API Enabled: –
Force SSL: –
Currency: AUD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –
Enabled Features: analytics
marketplace
order_attribution
site_visibility_badge
remote_logging
blueprint
point_of_sale


### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 5 KB

### WC Pages ###

Shop base: #3464 - /shop/
Cart: #3465 - /cart/ -  Contains the woocommerce_cart shortcode
Checkout: #3466 - /checkout/ -  Contains the woocommerce_checkout shortcode
My account: #3467 - /my-account/ -  Contains the [woocommerce_my_account] shortcode
Terms and conditions: #3470 - /terms-conditions/

### Theme ###

Name: Artemis Framing & Art Gallery
Version: 2.0.0
Author URL: https://maddisondesigns.com
Child Theme: ✔
Parent Theme Name: Ephemeris
Parent Theme Version: 1.5.3
Parent Theme Author URL: https://maddisondesigns.com
Theme type: Classic theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### WooCommerce Stripe Payment Gateway ###

Version: 9.8.0
Account ID: ***********
Account Email: ************
Test Mode Enabled: ✔
					No
OAuth Connected: No
Sync Enabled: No
Legacy Checkout Experience: ✔
					No
Optimized Checkout Enabled: No
Enabled Payment Methods: card
Express Checkout: ✔
					Enabled (cart)
Auth and Capture: ✔
					Yes
Logging: No

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
onboarding
onboarding-tasks
pattern-toolkit-full-composability
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
printful
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page
launch-your-store
add-to-cart-with-options-stepper-layout

Disabled Features: product-data-views
experimental-blocks
experimental-iapi-mini-cart
experimental-iapi-runtime
coming-soon-newsletter-template
minified-js
product-pre-publish-modal
settings
async-product-editor-category-field
product-editor-template-system
use-wp-horizon

Daily Cron: ✔ Next scheduled: 2025-08-14 08:44:29 +10:00
Options: ✔
Notes: 3
Onboarding: completed

### Action Scheduler ###

Complete: 217
Oldest: 2025-07-14 18:45:02 +1000
Newest: 2025-08-14 15:12:02 +1000

Failed: 949
Oldest: 2023-10-26 17:38:28 +1100
Newest: 2025-08-09 16:15:02 +1000

Pending: 5
Oldest: 2025-08-14 19:03:03 +1000
Newest: 2025-08-15 15:42:05 +1000


### Status report information ###

Generated at: 2025-08-14 15:25:17 +10:00
```
</details>

</details>

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by jorgeatorres**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

We currently have two types of db update notices (a legacy one managed via `WC_Admin_Notices`) and a wc-admin note. The install process has always handled the first one, but the second one was "automatically" updated to match the first one based on the state of the db updates.

This PR ensures that both notes are reset at plugin upgrade time and that they stay in sync.
It also makes it explicit when the notes should be added and/or removed, so we no longer need to check on every admin page load whether the note needs to be updated or not. This now happens when the note is loaded.

The changes in this PR also address the situation in #60367, where a site had an unactioned db update note prior to 10.0.x and then because of the automatic updates, the note never went away.

Closes #60367 .

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. **Ensure basic note / notice functionality:**
   1. In a mu-plugin or a snippet, enable the following code on your test site to disable automatic updates:
   ```php
   <?php
   add_filter( 'woocommerce_enable_auto_update_db', '__return_false' );
   ```
   1. Run `wp transient delete wc_installing && wp option set woocommerce_db_version 10.2.0 && wp option set woocommerce_version 10.2.0` to simulate an upgrade that doesn't involve db updates.
   1. Go to **Dashboard** and **WooCommerce > Home** and confirm that no update notice appears on either page.
   1. Run `wp transient delete wc_installing && wp option set woocommerce_db_version 10.1.0 && wp option set woocommerce_version 10.1.0` to simulate an upgrade that **does** involve db updates.
   1. Go to **Dashboard** and confirm that the legacy update notice appears.
   1. Go to **WooCommerce > Home** and confirm that the wc-admin db update note appears. Click the button and confirm that you are taken back to the **WooCommerce > Home** screen.
   1. Confirm that the notice changes to the "in progress" version both on **Dashboard** and **WooCommerce > Home**.
   1. Wait a bit for the A-S jobs to run (or run via `wp action-scheduler run`).
   1. Confirm that the notice changes to the "update done" version both on **Dashboard** and **WooCommerce > Home**.
   1. Confirm that `wp option get woocommerce_db_version` returns `10.3.0-dev`.
   1. Click the **Dismiss** button on the **Dashboard** version of the notice and confirm that no notice appears either on **Dashboard** or **WooCommerce > Home**.
1. **Ensure plugin upgrades clear previous notes:**
   1. Run `wp transient delete wc_installing && wp option set woocommerce_db_version 10.1.0 && wp option set woocommerce_version 10.1.0` to simulate an upgrade to a version with db updates.
   1. Confirm that the notices appear on both the **Dashboard** and **WooCommerce > Home** pages. Do not click any buttons.
   1. Run any pending A-S jobs with `wp action-scheduler run`.
   1. Confirm that `wp option get woocommerce_db_version` returns `10.1.0`, meaning the db update routine from `10.2.0` hasn't run yet.
   1. Disable or remove the snippet of code we added in step 1-i so that automatic updates are re-enabled.
   1. Run `wp transient delete wc_installing && wp option set woocommerce_version 10.2.0` to simulate a plugin upgrade.
   1. Confirm that `wp option get woocommerce_db_version` returns `10.1.0`, meaning nothing has changed yet.
   1. Confirm that no update notices are visible on either the **Dashboard** or the **WooCommerce > Home** screen.
   1. Run any pending A-S jobs with `wp action-scheduler run`.
   1. Confirm that `wp option get woocommerce_db_version` returns `10.3.0-dev`, which signals updates have been applied.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce/includes/class-wc-install.php [hunk 1]
```diff
@@ -488,10 +529,25 @@ public static function install_actions() {
...
 			wc_get_logger()->info( 'Manual database update triggered.', array( 'source' => 'wc-updater' ) );
 			self::update();
-			WC_Admin_Notices::add_notice( 'update', true );
+			self::add_update_db_notice();
+
+			$return_url = $_GET['return_url'] ?? ''; // phpcs:ignore WordPress.Security.ValidatedSanitizedInput.MissingUnslash,WordPress.Security.ValidatedSanitizedInput.InputNotSanitized -- sanitized below before use.
+			if ( ! empty( $return_url ) ) {
+				// Try to go back to the previus page.
+				if ( 'wc-admin-referer' === $return_url ) {
+					$return_url = preg_replace( '/^.*\/wp-admin\//i', '', wp_get_referer() ? wp_get_referer() : '' );
```
Comment (joshuatf) [inline plugins/woocommerce/includes/class-wc-install.php]: Since the admin URL can be filtered and different on each site, we should probably use `get_admin_url()`.

File: plugins/woocommerce/tests/legacy/unit-tests/admin/notes/class-wc-tests-notes-run-db-update.php [hunk 2]
```diff
@@ -110,7 +110,8 @@ private static function create_db_update_note() {
 	 * No note should be created/exist if db version is equal to WC code version.
 	 */
 	public function test_noop_db_update_note() {
-		update_option( 'woocommerce_db_version', WC()->version );
+		// Set the db version to the latest.
+		\WC_Install::update_db_version();
```
Comment (joshuatf) [inline plugins/woocommerce/tests/legacy/unit-tests/admin/notes/class-wc-tests-notes-run-db-update.php:114]: Nice update!

File: plugins/woocommerce/includes/class-wc-install.php [hunk 3]
```diff
@@ -414,17 +417,55 @@ public static function manual_database_update() {
...
+	 *
+	 * @since 10.3.0
+	 */
+	private static function add_update_db_notice() {
+		if ( ! \WC_Admin_Notices::has_notice( 'update' ) ) {
+			\WC_Admin_Notices::add_notice( 'update', true );
+		}
+
+		try {
+			if ( WC()->is_wc_admin_active() && false !== get_option( 'woocommerce_admin_install_timestamp' ) ) {
```
Comment (joshuatf) [inline plugins/woocommerce/includes/class-wc-install.php:442]: Is there a race condition we're trying to avoid?  Wondering why this very specific option needs to be checked and what the consequences are for not checking this.

It seems like if we need to keep this, this logic should be moved into an admin class check to see if that class is ready. to be used.

File: plugins/woocommerce/includes/admin/notes/class-wc-notes-run-db-update.php [hunk 4]
```diff
@@ -202,22 +226,26 @@ private static function update_in_progress_notice( $note_id ) {
...
 	/**
 	 * Update the existing note with $note_id with information that db upgrade is done.
 	 *
 	 * This is the last notice (3 out of 3 notices) displayed to the user.
 	 *
-	 * @param int $note_id Note id to update.
+	 * @param int|Note $note_id Note id to update.
 	 */
 	private static function update_done_notice( $note_id ) {
+		$note = ( $note_id instanceof Note ) ? $note_id : new Note( $note_id );
```
Comment (joshuatf) [inline plugins/woocommerce/includes/admin/notes/class-wc-notes-run-db-update.php]: I assume this is a small optimization to not re-initialize the note.  Could we update this to always use the `$note` instance if that's the case?  It seems like it's available in the other areas we use `update_done_notice()`.

File: plugins/woocommerce/includes/admin/notes/class-wc-notes-run-db-update.php [hunk 5]
```diff
@@ -105,15 +130,17 @@ private static function note_up_to_date( $note, $update_url, $current_actions )
 	 *
 	 * If a $note_id is given, the method updates the note instead of creating a new one.
 	 *
-	 * @param integer $note_id Note db record to update.
+	 * @param int|Note $note_id Note db record to update.
 	 * @return int Created/Updated note id
 	 */
 	private static function update_needed_notice( $note_id = null ) {
+		$note = ( $note_id instanceof Note ) ? $note_id : new Note( $note_id );
```
Comment (joshuatf) [inline plugins/woocommerce/includes/admin/notes/class-wc-notes-run-db-update.php]: Same comment here about simplifying the argument type options.

File: plugins/woocommerce/includes/admin/notes/class-wc-notes-run-db-update.php [hunk 6]
```diff
@@ -19,20 +19,43 @@ class WC_Notes_Run_Db_Update {
...
-		if ( defined( 'DOING_AJAX' ) && DOING_AJAX
-			|| defined( 'DOING_CRON' ) && DOING_CRON
-			|| ! is_admin() ) {
-			return;
+	public static function maybe_update_notice( $note ) {
+		if ( ! $note instanceof Note || $note->get_name() !== self::NOTE_NAME ) {
+			return $note;
+		}
+
+		if ( ! in_array( 'update', \WC_Admin_Notices::get_notices(), true ) ) {
```
Comment (joshuatf) [inline plugins/woocommerce/includes/admin/notes/class-wc-notes-run-db-update.php:36]: I'm not one for a lot of inline comments, but this seems like a good case to either add them or piece these out into methods that describe what's happening.  It definitely takes a minute to parse what's happening in each of these conditions.

File: plugins/woocommerce/includes/class-wc-install.php [hunk 7]
```diff
@@ -488,10 +529,25 @@ public static function install_actions() {
...
+						);
+					} else {
+						$return_url = admin_url( 'admin.php?page=wc-settings' );
+					}
+				}
 
-			if ( ! empty( $_GET['return_url'] ) ) { // WPCS: input var ok.
-				$return_url = esc_url_raw( wp_unslash( $_GET['return_url'] ) );
+				$return_url = esc_url_raw( wp_unslash( $return_url ) );
 				wp_safe_redirect( $return_url ); // WPCS: input var ok.
```
[the remark this answers is not in the document]
Comment (jorgeatorres) [reply plugins/woocommerce/includes/class-wc-install.php]: Fixed in 06aafd0b1ce8d949bb034601e9f66959184c438b and 20ad800d2b28e8e025dc58c4412691a2bfa99345.

File: plugins/woocommerce/includes/class-wc-install.php (hunk 1 above)
Comment (jorgeatorres) [reply plugins/woocommerce/includes/class-wc-install.php]: Done in bc48e5fac8e9c97bad16b016b26b2daccc7cf99b.

File: plugins/woocommerce/includes/admin/notes/class-wc-notes-run-db-update.php (hunk 4 above)
Comment (jorgeatorres) [reply plugins/woocommerce/includes/admin/notes/class-wc-notes-run-db-update.php]: Right. For some reason I thought these were public methods and was trying to 'preserve' backwards compat, but they are private, so I've just reworked the logic a bit in 6b6a6f7609716df7b00d7b0baf653e50db68c22a. Hopefully it is now less confusing.

File: plugins/woocommerce/includes/admin/notes/class-wc-notes-run-db-update.php (hunk 6 above)
Comment (jorgeatorres) [reply plugins/woocommerce/includes/admin/notes/class-wc-notes-run-db-update.php:36]: Added some comments in 7991bfca9bd2f4a974a7b8e0914f2dad186b423e.

File: plugins/woocommerce/includes/class-wc-install.php (hunk 3 above)
Comment (jorgeatorres) [reply plugins/woocommerce/includes/class-wc-install.php:442]: Not specifically a race condition, we're just trying not to create or delete a note when WC is being installed for the first time (and thus the tables haven't yet been created). It doesn't have to be this specific option, though, it's just one that gets added [after tables have been created](https://github.com/woocommerce/woocommerce/blob/bc48e5fac8e9c97bad16b016b26b2daccc7cf99b/plugins/woocommerce/includes/class-wc-install.php#L582). 

As for the consequences, nothing serious... just some noise in the logs due to our attempt to insert a record into a table that doesn't exist.

Given this is a path that we should be hitting less and less (after auto-updates by default) I thought we didn't need to add any new stuff. Happy to make further changes if you think it's a blocker. Just let me know.

**Comment by jorgeatorres** [comment]
@joshuatf: Thanks for the initial review. I've responded to your comments and made some adjustments. Please let me know what you think!

File: plugins/woocommerce/includes/class-wc-install.php (hunk 3 above)
Comment (joshuatf) [reply plugins/woocommerce/includes/class-wc-install.php:442]: Ya, this isn't a big deal, but if we continue to check for `woocommerce_admin_install_timestamp` presence as a pattern, I'd like to move this to a util.  E.g., `WC_Admin::is_ready()` or something more appropriately named.

But this is fine as is and doesn't need to block this PR.

File: plugins/woocommerce/includes/admin/notes/class-wc-notes-run-db-update.php [hunk 8]
```diff
@@ -19,28 +19,56 @@ class WC_Notes_Run_Db_Update {
...
+		return $note;
 	}
 
 	/**
 	 * Get current notice id from the database.
 	 *
 	 * Retrieves the first notice of this type.
 	 *
-	 * @return int|void Note id or null in case no note was found.
+	 * @return Note Note or null in case no note was found.
```
Comment (joshuatf) [inline plugins/woocommerce/includes/admin/notes/class-wc-notes-run-db-update.php]: Note Note 🗒️ 🗒️ 

```suggestion
	 * @return Note|null Note or null in case no note was found.
```

**Review by joshuatf — APPROVED** [review]
Testing perfectly!  Left one docblock suggestion, but pre-approving.

✅ Update routine with no DB updates does not show the note
✅ Update routine with DB updates shows notes in both the WCA homescreen and the WP dashboard
✅ Notes are synced; in progress notes are synced and dismissing one dismisses the other.
✅ Plugin upgrades clears previous notes
Screenshot 2025-09-05 at 7 08 21 AM
Screenshot 2025-09-05 at 7 08 15 AM
Screenshot 2025-09-05 at 7 06 43 AM

File: plugins/woocommerce/includes/admin/notes/class-wc-notes-run-db-update.php (hunk 8 above)
Comment (jorgeatorres) [reply plugins/woocommerce/includes/admin/notes/class-wc-notes-run-db-update.php]: Fixed via 0b27abd8cd555ce3be206df159ec908d016c8b24.
