### PR TITLE
Interactivity API powered Mini Cart - Support store notices messages

### LINKED ISSUE #59014: Interactivity API powered Mini Cart - Support store notices messages
## What?

In some cases, there is a store notice at the top of the minicart that is shown in the current block but it doesn't in the experimental one. One example is when the user has an item in the cart and it gets out of stock.

| Existing block | Experimental block |
|---------------|------------------|
| Image | Image | 

## Steps to reproduce

> To test the experimental block, make sure `experimental-iapi-mini-cart` and `experimental-iapi-runtime` are set to `true` in the `development.json` file: [link](https://github.com/woocommerce/woocommerce/blob/c9cc094885a0351dd2cb550a5739f5980e0a5e6c/plugins/woocommerce/client/admin/config/development.json#L8-L9).

1. Add a product to the cart.
2. Edit this product -> Inventory -> Set "Quantity" to 0.
3. Refresh the page and check that the error message is shown.

### PR DESCRIPTION
**Pull request by DAreRodz**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

This PR adds error notices at the top of the Mini Cart block, reproducing the same behavior that the React version has:

- When the fetch request is OK and there are no errors, it removes all notices.
- When the fetch request is OK but has errors in the body, it replaces the current notices with the new ones.
- When the fetch request fails, the error message is added to the current notices, instead of replacing them.

Closes #59014.

### Screenshots or screen recordings:

| Before | After |
| ------ | ----- |
| Screenshot 2025-07-11 at 18 47 57 | Screenshot 2025-07-11 at 18 47 11 |

### How to test the changes in this Pull Request:

> To test the experimental minicart block powered by the iAPI, make sure `experimental-iapi-mini-cart` and `experimental-iapi-runtime` are set to true in the `development.json` file: [link](https://github.com/woocommerce/woocommerce/blob/c9cc094885a0351dd2cb550a5739f5980e0a5e6c/plugins/woocommerce/client/admin/config/development.json#L8-L9).

1. Add some products to the shopping cart.
2. Leave the mini-cart open.
3. In another browser tab, open the admin panel.
4. Modify one of the products you've added to the cart so it's out of stock.
5. Go back to the previous page.
6. Try to modify the product quantity from the mini-cart.
7. Ensure an error notice appears.
8. Remove the product without stock.
9. Ensure the error notice disappears.

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message
</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment

Support store notices on the iAPI-powered MiniCart block.

</details>

</details>

### CODE REVIEW

**Comment by DAreRodz** [comment]
Hi @Aljullu, I've just added you as a reviewer for this PR. 🙂 

I know you folks are working on the Add To Cart block, and are touching the `cart.ts` store file as well. I'm wondering if my approach is correct, especially regarding the assumption I made about how and when notifications should be displayed (posted in the PR description):

> - When the fetch request is OK and there are no errors, it removes all notices.
> - When the fetch request is OK but has errors in the body, it replaces the current notices with the new ones.
> - When the fetch request fails, the error message is added to the current notices, instead of replacing them.

Please let me know if this assumption is correct or if I should modify the logic. Thanks!

**Review by Aljullu — COMMENTED** [review]
Thanks for checking, @DAreRodz! I didn't review the PR in detail, I assume somebody from Billow should do it, but from a quick glance, everything looks good on my end.

> I know you folks are working on the Add To Cart block, and are touching the cart.ts store file as well. I'm wondering if my approach is correct, especially regarding the assumption I made about how and when notifications should be displayed (posted in the PR description):

Yes, that would work well for the _Add to Cart + Options_ use cases, so +1 from my side.

File: plugins/woocommerce/client/blocks/assets/js/base/stores/woocommerce/cart.ts [hunk 1]
```diff
@@ -399,6 +417,44 @@ const { state, actions } = store< Store >(
...
+				if ( removeOthers ) {
+					notices
+						.map( ( { id } ) => id )
+						.filter( ( id ) => ! noticeIds.includes( id ) )
+						.forEach( ( id ) => noticeActions.removeNotice( id ) );
+				}
+
+				// Emmits console.error for troubleshooting.
+				// eslint-disable-next-line no-console
+				console.error( errors );
```
Comment (luisherranz) [inline plugins/woocommerce/client/blocks/assets/js/base/stores/woocommerce/cart.ts]:
```suggestion
```

**Review by luisherranz — APPROVED** [review]
LGTM!
