### PR TITLE
Hide stock status field if stock management is enabled

### LINKED ISSUE #37878: WC 7.7 beta: Stock status should be hidden when stock management is enabled
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Stock status is displayed when stock management is enabled, which can confuse the user and create conflicts on the product page. Stock status is used only when stock management is disabled.

### Expected behavior

Stock status should only be used when stock management is disabled. It should be removed when the user enables stock management. 

### Actual behavior

Captura de ecrã 2023-04-20, às 10 07 20

### Steps to reproduce

1. Install 7.7 beta
2. Create a new product
3. Go to the inventory tab (stock management needs to be enabled)
4. Enable "Track stock quantity for this product"
5. See that the "Stock status" section remains in the tab

### WordPress Environment

-

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by mattsherman**
### Submission Review Guidelines:

- I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
- I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
- I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/). 
- Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

This PR fixes a regression introduced in #37278 where the stock status field was not hidden when stock management is enabled for a product.

Closes #37878.

#### Before

image

#### After

Screenshot 2023-04-20 at 11 32 22

### How to test the changes in this Pull Request:

1. Make sure `Enable stock management` is enabled in `WooCommerce` > `Settings` > `Products` > `Inventory`
1. Go to `Products` > `Add New`
3. Go to `Inventory` tab
4. Enable `Track stock quantity for this product`
5. Verify the `Stock status` field is hidden
6. Disabled `Track stock quantity for this product`
7. Verify the `Stock status` field is shown

### CODE REVIEW

File: plugins/woocommerce/client/legacy/js/admin/meta-boxes-product.js [hunk 1]
```diff
@@ -330,19 +330,34 @@ jQuery( function ( $ ) {
 	);
 
 	// Stock options.
+	function show_or_hide_stock_management_fields(
+		isStockManagementEnabled,
+		productType
+	) {
+		const stockManagementFields = $( '.stock_fields' );
```
Comment (octaedro) [inline plugins/woocommerce/client/legacy/js/admin/meta-boxes-product.js]: I wonder if we should convert the `const`s into `var`s. The `const` keyword was introduced to JavaScript with the ECMAScript 2015 specification.

File: plugins/woocommerce/client/legacy/js/admin/meta-boxes-product.js [hunk 2]
```diff
@@ -330,19 +330,34 @@ jQuery( function ( $ ) {
...
+		const stockStatusField = $( '.stock_status_field' );
```
Comment (octaedro) [inline plugins/woocommerce/client/legacy/js/admin/meta-boxes-product.js]: I would follow the jQuery naming convention for variables that store jQuery objects prefixing them with a `$`.

File: plugins/woocommerce/client/legacy/js/admin/meta-boxes-product.js (hunk 1 above)
Comment (mattsherman) [reply plugins/woocommerce/client/legacy/js/admin/meta-boxes-product.js]: I'm pretty sure all the browsers we support support const. Doesn't some of our other compiled code have const in the output?

Comment (mattsherman) [reply plugins/woocommerce/client/legacy/js/admin/meta-boxes-product.js]: https://caniuse.com/const

File: plugins/woocommerce/client/legacy/js/admin/meta-boxes-product.js [hunk 3]
```diff
@@ -330,19 +330,34 @@ jQuery( function ( $ ) {
...
+		if ( isStockManagementEnabled ) {
+			stockManagementFields.show();
+			stockStatusField.hide();
+		} else {
+			stockManagementFields.hide();
+			// do not show stock status field if it should be hidden for the product type
+			if ( ! stockStatusField.is( '.hide_if_' + productType ) ) {
+				stockStatusField.show();
+			}
+		}
```
Comment (octaedro) [inline plugins/woocommerce/client/legacy/js/admin/meta-boxes-product.js]: What do you think about using the method `.toggle` here?

The code would look like this:
```
	stockManagementFields.toggle( isStockManagementEnabled );
	stockStatusField.toggle(
		! isStockManagementEnabled &&
			! stockStatusField.is( '.hide_if_' + productType )
	);
```

Comment (mattsherman) [reply plugins/woocommerce/client/legacy/js/admin/meta-boxes-product.js]: I like it, nice suggestion!

File: plugins/woocommerce/client/legacy/js/admin/meta-boxes-product.js (hunk 2 above)
Comment (mattsherman) [reply plugins/woocommerce/client/legacy/js/admin/meta-boxes-product.js]: Good point

**Comment by mattsherman** [comment]
@octaedro Thanks for the review -- I've changed the jQuery const names and used `.toggle()` as suggested. I kept the `const` because that is widely supported by this point and `const` is used elsewhere in this file and in other JS that we ship to the browser. Ready for a re-review!

**Review by octaedro — APPROVED** [review]
Great job @mattsherman! LGTM :shipit:
