### PR TITLE
Do not run `BatchProcessingController`'s cleanup after a premature shutdown

### LINKED ISSUE #49229: Undefined function `as_has_scheduled_action`
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

This is a bug in WC 9.1-RC.1.

Which cause the exception:

```
PHP Fatal error:  Uncaught Error: Call to undefined function Automattic\WooCommerce\Internal\BatchProcessing\as_has_scheduled_action() in /var/www/wp-content/plugins/woocommerce/src/Internal/BatchProcessing/BatchProcessingController.php:531
Stack trace:
#0 /var/www/wp-content/plugins/woocommerce/src/Internal/BatchProcessing/BatchProcessingController.php(86): Automattic\WooCommerce\Internal\BatchProcessing\BatchProcessingController->remove_or_retry_failed_processors()
#1 /var/www/wp-includes/class-wp-hook.php(324): Automattic\WooCommerce\Internal\BatchProcessing\BatchProcessingController->Automattic\WooCommerce\Internal\BatchProcessing\{closure}('')
#2 /var/www/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)
#3 /var/www/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#4 /var/www/wp-includes/load.php(1270): do_action('shutdown')
#5 [internal function]: shutdown_action_hook()
#6 {main}
  thrown in /var/www/wp-content/plugins/woocommerce/src/Internal/BatchProcessing/BatchProcessingController.php on line 531
```

Reason seems to be the newly added shutdown hook here: https://github.com/woocommerce/woocommerce/blob/9.1.0-rc.1/plugins/woocommerce/src/Internal/BatchProcessing/BatchProcessingController.php#L83

- When the shutdown hook is called, it look for the function `as_has_scheduled_action`.
- But `as_has_scheduled_action` is defined after the shoulddown hook is added.
- If the process got killed at a point between BatchProcessingController constructor being called and `as_has_scheduled_action` is defined, this error will be thrown.

### Expected behavior

Check if `as_has_scheduled_action` is defined before calling it.

### Actual behavior

Shutdown hook throws an exception [here](https://github.com/woocommerce/woocommerce/blob/9.1.0-rc.1/plugins/woocommerce/src/Internal/BatchProcessing/BatchProcessingController.php#L531).

### Steps to reproduce

1. The `BatchProcessingController` is created [here](https://github.com/woocommerce/woocommerce/blob/9.1.0-rc.1/plugins/woocommerce/src/Internal/DependencyManagement/ServiceProviders/BatchProcessingServiceProvider.php#L37)
2.  Call `wp_die()` right after this line.
```
public function register() {
		$this->share( BatchProcessingController::class, new BatchProcessingController() );
		wp_die();
		$this->share_with_implements_tags( OrderCouponDataMigrator::class );
	}
```
3. The exception mentioned in the error should occure.

### WordPress Environment

<details><summary>System Status Report</summary>

```
### WordPress Environment ###

WordPress address (URL): [Redacted]
Site address (URL): [Redacted]
WC Version: 9.1.0-rc.1
Legacy REST API Package Version: The Legacy REST API plugin is not installed on this site.
Action Scheduler Version: ✔ 3.7.4
Log Directory Writable: ✔
WP Version: 6.5.5
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.59 (Debian)
PHP Version: 8.1.28
PHP Post Max Size: 100 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.88.1
OpenSSL/3.0.11

SUHOSIN Installed: –
MySQL Version: 10.3.35-MariaDB-log
Max Upload Size: 100 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

[REDACTED]

### Post Type Counts ###

attachment: 7
page: 7
post: 2
product: 1
shop_order: 1
wp_font_face: 33
wp_font_family: 12
wp_global_styles: 1
wp_navigation: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (3) ###

WooCommerce Deposits: by WooCommerce – 2.2.9
WooCommerce Table Rate Shipping: by WooCommerce – 3.2.1 (update to version 3.2.2 is available)
WooCommerce: by Automattic – 9.1.0-rc.1

### Inactive Plugins (0) ###


### Must Use Plugins (1) ###

wccom-helper-local-testing-hacks.php: by  –

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 2 KB

### WC Pages ###

Shop base: #5 - /shop/
Cart: #6 - /cart/ -  Contains the woocommerce/cart block
Checkout: #7 - /checkout/ -  Contains the woocommerce/checkout block
My account: #8 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Nineteen
Version: 2.8
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page
launch-your-store

Disabled Features: experimental-blocks
minified-js
pattern-toolkit-full-composability
product-pre-publish-modal
printful
settings
async-product-editor-category-field
product-editor-template-system

Daily Cron: ✔ Next scheduled: 2024-07-08 13:28:08 +00:00
Options: ✔
Notes: 78
Onboarding: skipped

### Action Scheduler ###

Complete: 20
Oldest: 2024-06-10 04:06:53 +0000
Newest: 2024-07-08 11:11:49 +0000

Failed: 10
Oldest: 2024-06-04 11:01:59 +0000
Newest: 2024-07-08 11:10:13 +0000

Pending: 2
Oldest: 2024-07-08 23:10:13 +0000
Newest: 2024-07-09 11:10:13 +0000


### Status report information ###

Generated at: 2024-07-08 11:32:08 +00:00
```
</details>

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by jorgeatorres**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

`BatchProcessingController` has a small routine hooked onto `shutdown` that attempts to re-schedule (or mark as failed) background processors that failed due to a fatal error or some abnormal circumstance.

That logic shouldn't be problematic, but the fact that we're running it during a `shutdown` means it's also executed when script execution has been halted (by an error or just an `exit/die` statement) **before** WooCommerce or even Action-Scheduler have been initialized. Given our reliance on A-S functions being available, this produces further fatal errors.

This PR makes sure we only run this function if WP has reached a stage where AS and WC should be available, and also if no fatal error is the source of the script being halted.

Closes #49229.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. (Optional) To confirm _when_ the cleanup routine is actually being executed, add the following to line 539 in `[...]/woocommerce/src/Internal/BatchProcessing/BatchProcessingController.php`:
   ```php
   error_log( 'Running BatchProcessingController cleanup routine...' );
   ```
1. Using a suitable location (such as a .php file in `wp-content/mu-plugins`) activate all 
of the following snippets. Make sure to comment out (as necessary) the other snippets. You should only have one active at a given time.

   ```php
   <?php
   // Snippet 1. Stops execution before A-S has been initialized. Should prevent the cleanup routine from running.
   add_action( 'plugins_loaded', 'wp_die', 0 );
   
   // Snippet 2. Stops execution before A-S has been initialized. Should prevent the cleanup routine from running.
   add_action( 'init', function() { as_has_scheduled_action( 'zzz' ); }, 0 );
   
   // Snippet 3. Stops execution after A-S has been initialized. Should not prevent the cleanup routine from running.
   add_action( 'wp_loaded', 'wp_die', 999 );
   
   // Snippet 4. Produces a fatal error. Should prevent the cleanup routine from running.
   add_action( 'wp_loaded', function() { 1 / 0; }, 999 );
   
   // Snippet 5. Produces a warning. Won't prevent the cleanup routine from running.
   add_action( 'wp_loaded', function() { $a = (object) array(); $a->x; }, 999 );
   ```
3. Make sure that no fatal errors are logged in relation to `BatchProcessingController` or A-S.
4. (Optional) Repeat the above on `trunk`, where any of the 3 first snippets will produce errors related to `BatchProcessingController`.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

**Comment by barryhughes** [comment]
This looks good to me. 

- I did make a small tweak in https://github.com/woocommerce/woocommerce/pull/49243/commits/ad9acb5bf478e42aef6c7becd53dc03a391a8471 (commit message goes into more detail, but the short version of events is we cannot assume `as_has_scheduled_event` will be available).
- @thilinah if you have a moment and want to look over the proposed solution, we'd welcome your thoughts.
- @coreymckrill can I ask you to (re-)review, since I've modified the code?

File: plugins/woocommerce/src/Internal/BatchProcessing/BatchProcessingController.php [hunk 1]
```diff
@@ -528,7 +528,20 @@ private function log_consistent_failure( BatchProcessorInterface $batch_processo
 	 * @since 9.1.0
 	 */
 	private function remove_or_retry_failed_processors(): void {
-		if ( as_has_scheduled_action( self::WATCHDOG_ACTION_NAME ) ) {
+		if ( ! did_action( 'wp_loaded' ) ) {
+			return;
+		}
+
+		$last_error = error_get_last();
+		if ( ! is_null( $last_error ) && in_array( $last_error['type'], array( E_ERROR, E_PARSE, E_CORE_ERROR, E_COMPILE_ERROR, E_USER_ERROR, E_RECOVERABLE_ERROR ), true ) ) {
```
Comment (coreymckrill) [inline plugins/woocommerce/src/Internal/BatchProcessing/BatchProcessingController.php:536]: There's [another place](https://github.com/woocommerce/woocommerce/blob/a93343dd90aa16c3182a7baf21d6be0d5e837e89/plugins/woocommerce/includes/class-woocommerce.php#L336) where we make basically this same kind of check, with the array of different error types. I wonder if it would be worth abstracting this so we can be consistent with the types of errors that qualify? Perhaps out of scope for this PR.

**Review by thilinah — APPROVED** [review]
Code looks good. I've tested this change on WCCOM repo  and it works fine.

However I've noticed that, when testing on WCCOM trunk I get the fatal error only for snippet 1. I made sure the fix introduced with https://github.com/Automattic/woocommerce.com/pull/20990 is removed before testing.

**Review by coreymckrill — APPROVED** [review]
I noticed that when I add the error_log line so that I can see when the cleanup routine has been run, it adds the log entry _7 times_ each time I refresh the tab with my test site. For the first two test cases, all 7 entries are prevented, but for the third test case, 1 entry still gets added... I'm not sure any of this matters, but mentioning here in case anyone might know why this is happening.

The code looks good to me, and the fatal errors that happen with the test cases on trunk are all prevented with this PR branch 👍

**Comment by jorgeatorres** [comment]
> but for the third test case, 1 entry still gets added...

Good catch @coreymckrill. I believe it was just a copy-paste mistake on my side as that `wp_die` doesn't happen before A-S is initialized nor is a serious error itself. I've updated the instructions.

File: plugins/woocommerce/src/Internal/BatchProcessing/BatchProcessingController.php (hunk 1 above)
Comment (barryhughes) [reply plugins/woocommerce/src/Internal/BatchProcessing/BatchProcessingController.php:536]: Agree! I [logged a housekeeping task](https://github.com/woocommerce/woocommerce/issues/49245) (just to minimize delay, since we have some time constraints for this PR).

**Comment by barryhughes** [comment]
> However I've noticed that, when testing on WCCOM trunk I get the fatal error only for snippet 1.

I can't replicate this (though I'm not testing on WCCOM), but in any case I'm not sure it needs to block us (any further thoughts)?

**Review by barryhughes — APPROVED** [review]
