### PR TITLE
Apply webhook delivery hook args filter to delivery pings

### LINKED ISSUE #60886: deliver_ping does not add woocommerce_webhook_http_args headers
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

This is being transferred from https://wordpress.org/support/topic/order-created-webhook-firing-twice/#post-18637097

The symptom is that a programmatically-created webhook (via `wp wc webhook create`) that also had additional header requirements (set via `woocommerce_webhook_http_args`) does not include said headers when making `deliver_ping` requests, meaning the webhook's DB record gets stuck with `pending_delivery` equalling `1`, so the cycle of `deliver_ping` being called on every webhook request never resolves.

There are two issues here, this only addresses the first one: the headers missing from the `deliver_ping` call.

Here is the relevant bit of the `deliver_ping` code:

```
public function deliver_ping() {
	$args = array(
		'user-agent' => sprintf( 'WooCommerce/%s Hookshot (WordPress/%s)', Constants::get_constant( 'WC_VERSION' ), $GLOBALS['wp_version'] ),
		'body'       => 'webhook_id=' . $this->get_id(),
	);

	$test          = wp_safe_remote_post( $this->get_delivery_url(), $args );
```

If one's remote service requires other headers, such as `Authorization`, this request will never succeed.

For "normal" webhook request, `delivery` is called. Here is the relevant code:

```
public function deliver( $arg ) {
	// SNIP
	
	// Setup request args.
	$http_args = array(
		// SNIP
	);

	$http_args = apply_filters( 'woocommerce_webhook_http_args', $http_args, $arg, $this->get_id() );

	// Add custom headers.
	// SNIP
```

The key bit is the `apply_filters` call. This finishes setting the headers for the webhook request, to make it valid.

The fix for this issue is to similarly call `apply_filters` in `deliver_ping`.

This does not impact webhooks created via the UI, as there's no mechanism to specify the addition header requirement there, as far as I can tell (this itself is a shortfall, but unrelated).

Let me know if you need any further information.

### Expected behavior

`deliver_ping` should apply the headers the webhook has been configured to use, and have more of a chance of getting a 200-OK response.

### Actual behavior

`deliver_ping` does not apply the headers the webhook has been configured to use, so is likely to fail if those headers are required for auth, etc.

### Steps to reproduce

1 Create a webhook via the CLI via `wp wc webhook create`.
2 Add required headers to the webhook via the `woocommerce_webhook_http_args` filter, eg `Authorization` with a bearer token.
3 Cause the webhook to fire. In my case it's the `order.created`, so make an order.
4 Observe on the remote server's Nginx logs that along with the successful order request, there is an additional request which 401s as it does not send the Authorization.
5 Observe that this happens with every single order.
6 Manually setting the webhook's `pending_delivery` value to `0` makes the second request stop.
7 Observe that the fact that the actual order request being successful doesn't automatically set `pending_delivery` to be `0`.

### WordPress Environment

[SystemStatusReport_indievet.local_2025-09-12T07-44-02.txt](https://github.com/user-attachments/files/22292788/SystemStatusReport_indievet.local_2025-09-12T07-44-02.txt)

I dispute that this is going to be at all relevant to this issue, but... so be it. Attached.

### Isolating the problem

- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by joshuatf**
### Changes proposed in this Pull Request:

While webhooks have the ability to add in headers and other information by use of the `woocommerce_webhook_http_args` filter, this information was not applied to delivery pings, resulting in their failure when additional info is needed in the http request.

This PR adds that filter to those requests so that the same arguments are applied.

Closes #60886 .

(For Bug Fixes) Bug introduced in PR # .

### Screenshots or screen recordings:

| Before | After |
| ------ | ----- |
|   Screenshot 2025-09-15 at 12 26 40 PM |  Screenshot 2025-09-15 at 12 32 21 PM     |

### How to test the changes in this Pull Request:

1. Add the below `webhook-test.php` file to the root of your site's public directory
2. Add the below snippet to add in header auths to your WP site
3. Navigate to WooCommerce -> Settings -> Advanced -> Webhooks
4. Create a webhook that is `Active` and set a topic to one easily triggered (e.g., coupon creation)
5. Save the webhook
6. Note that the save is successful with no errors
7. Trigger the webhook (e.g., create a coupon if that's the trigger you chose)
8. Navigate to WooCommerce -> Status -> Logs and find your webhook logs
9. Make sure that webhook call was successful

```php
// Snippet to add header auths
add_filter( 'woocommerce_webhook_http_args', function( $args ) {
	$args['headers']['Authorization'] = 'Bearer test12345';
	return $args;
}, 10 );
```

```php
<!-- webhook-test.php -->
<?php
// Fake Quick Header Auth Test

// Grab all request headers
$headers = getallheaders();

// Define a fake expected token
$expected_token = "test12345";

http_response_code(400);

// Check if "Authorization" header exists
if (isset($headers['Authorization'])) {
    $auth_header = $headers['Authorization'];

    // For testing: expect "Bearer test12345"
    if ($auth_header === "Bearer " . $expected_token) {
        http_response_code(200);
        echo json_encode([
            "status" => "success",
            "message" => "Authorized ✅"
        ]);
    } else {
        http_response_code(401);
        echo json_encode([
            "status" => "failure",
            "message" => "Invalid token ❌"
        ]);
    }
} else {
    echo json_encode([
        "status" => "error",
        "message" => "Authorization header missing ⚠️"
    ]);
}
```

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce/includes/class-wc-webhook.php [hunk 1]
```diff
@@ -606,7 +615,18 @@ public function deliver_ping() {
 			'body'       => 'webhook_id=' . $this->get_id(),
 		);
 
-		$test          = wp_safe_remote_post( $this->get_delivery_url(), $args );
+		/**
+		 * Filters the HTTP arguments for the webhook delivery ping.
+		 *
+		 * @since 3.3.0
```
Comment (joshuatf) [inline plugins/woocommerce/includes/class-wc-webhook.php:621]: Not sure if we have precedence for this, but this filter has been around since 3.3.0, but only applied to delivery pings in 10.3.0.

Comment (Konamiman) [reply plugins/woocommerce/includes/class-wc-webhook.php:621]: Maybe we could leave the `@since` untouched but add something like "applied to delivery pings since 10.3.0" in the docblock.

**Review by Konamiman — APPROVED** [review]
For the record, here's a simpler way to test: add the snippet that hooks into the filter and adds the header, but don't create the `webhook-test.php` file. Then create the hook using an address in [webhook.site](https://webhook.site/) as the target, and verify that the request that the site receives when a new coupon is created includes the added header.
