### PR TITLE
Fix products base incorrectly matching pages with the same prefix

### LINKED ISSUE #51535: WordPress core page with `product` in URL is incorrectly considered as store page
### Issue Description

Originally reported by @PoppyDev in https://github.com/woocommerce/woocommerce/discussions/47418#discussioncomment-10669978

WordPress core pages with `/product` in URL is incorrectly hidden behind coming soon when "Coming soon" and "Apply to store pages only" is enabled.

image

#### To reproduce

1. In a fresh site, go to `Pages > Add new page`
2. Set page title and content to anything
3. In site editor's `Page` tab, click `link`
4. Set the link to `product` and save the page
5. Go to `WooCommerce > Settings > Site visibility`
6. Enable `Coming soon` and `Apply to store pages only` and save
1. In an incognito window, navigate to the site's frontend
2. Click on the link to the new page
3. Observe coming soon page is shown

### PR DESCRIPTION
**Pull request by ilyasfoo**
### Changes proposed in this Pull Request:

Closes #51535.

Fixes store page detection incorrectly flagging core pages where its URL has certain prefix.

image

### How to test the changes in this Pull Request:

1. In a fresh site, go to `Pages > Add new page`
2. Set page title and content to anything
3. In site editor's `Page` tab, click `link`
4. Set the link to `products-demo` and publish the page
5. Go to `WooCommerce > Settings > Site visibility`
6. Enable `Coming soon` and `Apply to store pages only` and save
1. In an incognito window, navigate to the site's frontend
2. Click on the link to the new page
3. Observe coming soon page is **NOT shown**

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce/src/Admin/WCAdminHelper.php [hunk 1]
```diff
@@ -217,30 +217,40 @@ public static function is_store_page( $url = '' ) {
...
-			if ( 0 === strpos( $normalized_path, trim( $permalink_structure[ $key ], '/' ) ) ) {
-				return true;
-			}
+		$url_path = wp_parse_url( $normalized_path, PHP_URL_PATH );
 
-			// If the permalink structure contains placeholders, we need to check if the URL matches the structure using regex.
-			if ( strpos( $permalink_structure[ $key ], '%' ) !== false ) {
-				global $wp_rewrite;
-				$rules = $wp_rewrite->generate_rewrite_rule( $permalink_structure[ $key ] );
+		if ( $url_path ) {
```
Comment (rjchow) [inline plugins/woocommerce/src/Admin/WCAdminHelper.php:215]: This chunk seems really complex to me, do you think it would be helpful if we added some inline comments with a few examples to help with visualising the code?

**Review by rjchow — APPROVED** [review]
The code changes went a bit over my head, but it tested well

**Review by psealock — APPROVED** [review]
This is working well. I think @rjchow's comment about adding examples would be helpful. Pre-approving

File: plugins/woocommerce/src/Admin/WCAdminHelper.php (hunk 1 above)
Comment (ilyasfoo) [reply plugins/woocommerce/src/Admin/WCAdminHelper.php:215]: Thanks! Great idea - I've added some examples in e22e2fcc181998a6349527494e0493b8b1249dec
