### PR TITLE
Set the Products > All products as the active submenu for Product Importer/Exporter

### LINKED ISSUE #25918: Import Products and Products nav menu
**Describe the bug**

During products importing there is no submeny active, although "Products" parent menu is marked as active.

**To Reproduce**
1. Go to Products importing interface
2. Select sample-products.csv file that is shipped with WC 4.0
3. Start importing process
4. Check the "Products" admin area menu.

**Screenshots**

image

**Expected behavior**

If "Products" is marked as active, I expect to see some submenu item being active too, right now parent only is marked as active.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
### WordPress Environment ###

WordPress address (URL): http://example.local/wc
Site address (URL): http://example.local/wc
WC Version: 4.0.0
REST API Version: ✔ 1.0.7
WC Blocks Version: ✔ 2.5.14
Action Scheduler Version: ✔ 3.1.2
WC Admin Version: ✔ 1.0.0
Log Directory Writable: ✔
WP Version: 5.3.2
WP Multisite: –
WP Memory Limit: 2 GB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.2.10
PHP Post Max Size: 100 MB
PHP Time Limit: 180
PHP Max Input Vars: 1000
cURL Version: 7.59.0
OpenSSL/1.1.0i

SUHOSIN Installed: –
MySQL Version: 5.7.23
Max Upload Size: 100 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.0.0
WC Database Prefix: wp_
Total Database Size: 4.14MB
Database Data Size: 2.62MB
Database Index Size: 1.52MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailchimp_carts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailchimp_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 1.50MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.13MB + Index: 0.06MB + Engine InnoDB
wp_posts: Data: 0.09MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 28
customize_changeset: 2
page: 9
post: 2
product: 19
product_variation: 7
revision: 3

### Security ###

Secure connection (HTTPS): ❌
                    Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (3) ###

Dummy Gateway for WooCommerce: by Vlado Pajić – 1.0 – Not tested with the active version of WooCommerce
Mailchimp for WooCommerce: by Mailchimp – 2.3.4 – Not tested with the active version of WooCommerce
WooCommerce: by Automattic – 4.0.0

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #7 - /shop/
Cart: #8 - /cart/
Checkout: #9 - /checkout/
My account: #10 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 2.5.5
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 11
Oldest: 2020-03-13 20:25:01 +0000
Newest: 2020-03-13 21:13:02 +0000

Pending: 1
Oldest: 2020-03-14 00:00:00 +0000
Newest: 2020-03-14 00:00:00 +0000
```
</details>

### PR DESCRIPTION
**Pull request by jimjasson**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

This PR makes the Products > All Products submenu the highlighted submenu when viewing the Product Import and Export pages. This is done by overriding the `$submenu_file` global variable, similar to what happens in `WC_Admin_Menus::menu_highlight`: https://github.com/woocommerce/woocommerce/blob/edc272041e06679f437fdce8acdf460ad47f70fc/plugins/woocommerce/includes/admin/class-wc-admin-menus.php#L235

Closes #25918 

### Screenshots or screen recordings:

| Before | After |
| ------ | ----- |
|  Markup on 2025-05-09 at 13:52:48 |  Markup on 2025-05-09 at 13:51:35 |
| Markup on 2025-05-09 at 13:52:21 | Markup on 2025-05-09 at 13:51:56 |

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Go to the Products tab.
2. Click on the Import button at the top of the page.
3. Ensure that the All Products submenu is highlighted. 
4. Go to the Products tab.
5. Click on the Export button at the top of the page.
6.  Ensure that the All Products submenu is highlighted. 

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [x] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 
Highlighted the Products > All Products tab, when viewing the Product Import/Export screens.
</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce/includes/admin/class-wc-admin-importers.php [hunk 1]
```diff
@@ -32,6 +32,7 @@ public function __construct() {
 		add_action( 'admin_menu', array( $this, 'add_to_menus' ) );
 		add_action( 'admin_init', array( $this, 'register_importers' ) );
 		add_action( 'admin_head', array( $this, 'hide_from_menus' ) );
+		add_action( 'admin_head', array( $this, 'set_active_submenu_for_product_importer' ) );
```
Comment (xristos3490) [inline plugins/woocommerce/includes/admin/class-wc-admin-importers.php]: Nit. Maybe use a "menu_highlight" name here? The "product_importer" is assumed by the context. Same for exporter.

**Review by xristos3490 — APPROVED** [review]
Looking good! At first, I thought that having everything under `WC_Admin_Menus` would be ideal here, but I realized that each of these controllers has custom handling for the menu pages, so I stand by your idea of having them in both places. I left a nit but pre-approved it.

**Comment by gigitux** [comment]
Thanks for working on this PR! This fixes https://github.com/woocommerce/woocommerce/issues/56112. I tried this approach, but after a discussion, we aren't sure that this is the right approach (cc @dinhtungdu @Aljullu). I invite you to read the entire discussion: WOOPLUG-3340. 

I don't have a strong preference, and I'm fine with this approach, but sharing for awareness.

**Comment by jimjasson** [comment]
Hey @gigitux, 

Thank you for the comment! 

This PR targets specifically the Product Import/Export screens -- see: https://github.com/woocommerce/woocommerce/pull/57877/files#diff-dfcffa1944298480c6871b05f7ebae0fcb8ec3e566fda1217e8748adc273d9a4R95

The discussion you shared seems to be related to the Products screen, and specifically when there are no products in the store. 

I don't think that these two are related, but please let me know if I am missing something. :)

**Comment by gigitux** [comment]
Ops, sorry for the confusion 😅 Yeah you're right! Please, @dinhtungdu and @Aljullu ignore my previous message.
