### PR TITLE
Fix/20921 - Throw error for invalid character in flat rate cost.

### LINKED ISSUE #20921: Error found in: class-wc-eval-math.php, pfx, 298
**Describe the bug**
Overnight I became unable to click the add to card button in the shop page for products. The remove from cart buttons don't work either, showing the same error.

**To Reproduce**
1. Go to 'https://feedmefit.ca/menu/'
2. Click on 'any "Add to Cart" button'
3. See error

**Expected behavior**
You will see a blank screen and an error on top that says 

**Isolating the problem (mark completed items with an [x]):**
- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
`
### WordPress Environment ###

Home URL: https://feedmefit.ca
Site URL: https://feedmefit.ca
WC Version: 3.4.4
Log Directory Writable: ✔
WP Version: 4.9.7
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_CA
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.1.19 - We recommend using PHP version 7.2 or above for greater performance and security. How to update your PHP version
PHP Post Max Size: 8 MB
PHP Time Limit: 300
PHP Max Input Vars: 1000
cURL Version: 7.59.0
OpenSSL/1.0.2o

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.2.16-MariaDB-log
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.4.4
WC Database Prefix: wp_
Total Database Size: 108.55MB
Database Data Size: 69.98MB
Database Index Size: 38.57MB
wp_woocommerce_sessions: Data: 0.39MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_order_items: Data: 1.52MB + Index: 0.23MB
wp_woocommerce_order_itemmeta: Data: 6.52MB + Index: 7.03MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wpstg0_adtribes_my_conversions: Data: 0.02MB + Index: 0.02MB
wpstg0_alm: Data: 0.02MB + Index: 0.00MB
wpstg0_AnythingPopup: Data: 0.00MB + Index: 0.00MB
wpstg0_commentmeta: Data: 0.02MB + Index: 0.03MB
wpstg0_comments: Data: 1.52MB + Index: 0.69MB
wpstg0_failed_jobs: Data: 0.02MB + Index: 0.00MB
wpstg0_giftvouchers_list: Data: 0.02MB + Index: 0.00MB
wpstg0_giftvouchers_setting: Data: 0.02MB + Index: 0.00MB
wpstg0_giftvouchers_template: Data: 0.02MB + Index: 0.00MB
wpstg0_itro_plugin_field: Data: 0.02MB + Index: 0.00MB
wpstg0_itro_plugin_option: Data: 0.02MB + Index: 0.00MB
wpstg0_links: Data: 0.02MB + Index: 0.02MB
wpstg0_mailchimp_carts: Data: 0.13MB + Index: 0.00MB
wpstg0_options: Data: 3.52MB + Index: 0.23MB
wpstg0_pimwick_gift_card: Data: 0.02MB + Index: 0.02MB
wpstg0_pimwick_gift_card_activity: Data: 0.02MB + Index: 0.02MB
wpstg0_pkpo_markers: Data: 0.02MB + Index: 0.00MB
wpstg0_postmeta: Data: 16.52MB + Index: 8.03MB
wpstg0_posts: Data: 1.52MB + Index: 0.44MB
wpstg0_pum_subscribers: Data: 0.02MB + Index: 0.06MB
wpstg0_queue: Data: 0.02MB + Index: 0.00MB
wpstg0_rednao_wc_invoice: Data: 0.02MB + Index: 0.00MB
wpstg0_rednao_wc_invoices_created: Data: 0.02MB + Index: 0.00MB
wpstg0_rednao_wc_invoices_custom_field: Data: 0.02MB + Index: 0.00MB
wpstg0_sb_image_hover_effects_list: Data: 0.02MB + Index: 0.00MB
wpstg0_sb_image_hover_effects_style: Data: 0.02MB + Index: 0.00MB
wpstg0_termmeta: Data: 0.02MB + Index: 0.03MB
wpstg0_terms: Data: 0.02MB + Index: 0.03MB
wpstg0_term_relationships: Data: 0.02MB + Index: 0.02MB
wpstg0_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wpstg0_UPCP_Catalogues: Data: 0.02MB + Index: 0.00MB
wpstg0_UPCP_Catalogue_Items: Data: 0.02MB + Index: 0.00MB
wpstg0_UPCP_Categories: Data: 0.02MB + Index: 0.00MB
wpstg0_UPCP_Custom_Fields: Data: 0.02MB + Index: 0.00MB
wpstg0_UPCP_Fields_Meta: Data: 0.02MB + Index: 0.00MB
wpstg0_UPCP_Items: Data: 0.02MB + Index: 0.00MB
wpstg0_UPCP_Item_Images: Data: 0.02MB + Index: 0.00MB
wpstg0_UPCP_SubCategories: Data: 0.02MB + Index: 0.00MB
wpstg0_UPCP_Tagged_Items: Data: 0.02MB + Index: 0.00MB
wpstg0_UPCP_Tags: Data: 0.02MB + Index: 0.00MB
wpstg0_UPCP_Tag_Groups: Data: 0.02MB + Index: 0.00MB
wpstg0_UPCP_Videos: Data: 0.02MB + Index: 0.00MB
wpstg0_usermeta: Data: 1.52MB + Index: 0.83MB
wpstg0_users: Data: 0.08MB + Index: 0.05MB
wpstg0_wcpdf_invoice_number: Data: 0.02MB + Index: 0.00MB
wpstg0_wc_download_log: Data: 0.02MB + Index: 0.03MB
wpstg0_wc_webhooks: Data: 0.02MB + Index: 0.02MB
wpstg0_weu_subscribers: Data: 0.02MB + Index: 0.00MB
wpstg0_weu_unsubscriber: Data: 0.02MB + Index: 0.00MB
wpstg0_weu_user_notification: Data: 0.02MB + Index: 0.00MB
wpstg0_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wpstg0_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wpstg0_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wpstg0_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wpstg0_woocommerce_min_max_rules: Data: 0.02MB + Index: 0.00MB
wpstg0_woocommerce_order_itemmeta: Data: 6.52MB + Index: 6.03MB
wpstg0_woocommerce_order_items: Data: 1.52MB + Index: 0.20MB
wpstg0_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wpstg0_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wpstg0_woocommerce_pickup_locations_geodata: Data: 0.02MB + Index: 0.05MB
wpstg0_woocommerce_sessions: Data: 0.23MB + Index: 0.02MB
wpstg0_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wpstg0_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wpstg0_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wpstg0_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wpstg0_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wpstg0_woof_query_cache: Data: 0.02MB + Index: 0.02MB
wpstg0_wpgmza: Data: 0.02MB + Index: 0.00MB
wpstg0_wpgmza_categories: Data: 0.02MB + Index: 0.00MB
wpstg0_wpgmza_category_maps: Data: 0.02MB + Index: 0.00MB
wpstg0_wpgmza_circles: Data: 0.02MB + Index: 0.00MB
wpstg0_wpgmza_datasets: Data: 0.02MB + Index: 0.00MB
wpstg0_wpgmza_maps: Data: 0.02MB + Index: 0.00MB
wpstg0_wpgmza_polygon: Data: 0.02MB + Index: 0.00MB
wpstg0_wpgmza_polylines: Data: 0.02MB + Index: 0.00MB
wpstg0_wpgmza_rectangles: Data: 0.02MB + Index: 0.00MB
wpstg0_wplc_chat_msgs: Data: 0.25MB + Index: 0.00MB
wpstg0_wplc_chat_ratings: Data: 0.02MB + Index: 0.00MB
wpstg0_wplc_chat_sessions: Data: 0.08MB + Index: 0.00MB
wpstg0_wplc_chat_triggers: Data: 0.02MB + Index: 0.00MB
wpstg0_wplc_custom_fields: Data: 0.02MB + Index: 0.00MB
wpstg0_wplc_departments: Data: 0.02MB + Index: 0.00MB
wpstg0_wplc_devices: Data: 0.02MB + Index: 0.00MB
wpstg0_wplc_offline_messages: Data: 0.02MB + Index: 0.00MB
wpstg0_wplc_roi_conversions: Data: 0.02MB + Index: 0.00MB
wpstg0_wplc_roi_goals: Data: 0.02MB + Index: 0.00MB
wpstg0_wplc_webhooks: Data: 0.02MB + Index: 0.00MB
wpstg0_yith_wapo_groups: Data: 0.02MB + Index: 0.00MB
wpstg0_yith_wapo_types: Data: 0.02MB + Index: 0.00MB
wpstg0_yoast_seo_links: Data: 0.02MB + Index: 0.02MB
wpstg0_yoast_seo_meta: Data: 0.02MB + Index: 0.00MB
wp_adtribes_my_conversions: Data: 0.02MB + Index: 0.02MB
wp_alm: Data: 0.02MB + Index: 0.00MB
wp_AnythingPopup: Data: 0.00MB + Index: 0.00MB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_comments: Data: 1.52MB + Index: 0.72MB
wp_failed_jobs: Data: 0.02MB + Index: 0.00MB
wp_itro_plugin_field: Data: 0.02MB + Index: 0.00MB
wp_itro_plugin_option: Data: 0.02MB + Index: 0.00MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_mailchimp_carts: Data: 0.28MB + Index: 0.00MB
wp_options: Data: 2.45MB + Index: 0.22MB
wp_pkpo_markers: Data: 0.02MB + Index: 0.00MB
wp_postmeta: Data: 17.52MB + Index: 10.03MB
wp_posts: Data: 1.52MB + Index: 0.45MB
wp_pum_subscribers: Data: 0.02MB + Index: 0.06MB
wp_queue: Data: 0.02MB + Index: 0.00MB
wp_rednao_wc_invoice: Data: 0.02MB + Index: 0.00MB
wp_rednao_wc_invoices_created: Data: 0.02MB + Index: 0.00MB
wp_rednao_wc_invoices_custom_field: Data: 0.02MB + Index: 0.00MB
wp_sb_image_hover_effects_list: Data: 0.02MB + Index: 0.00MB
wp_sb_image_hover_effects_style: Data: 0.02MB + Index: 0.00MB
wp_termmeta: Data: 0.02MB + Index: 0.03MB
wp_terms: Data: 0.02MB + Index: 0.03MB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wp_UPCP_Catalogues: Data: 0.02MB + Index: 0.00MB
wp_UPCP_Catalogue_Items: Data: 0.02MB + Index: 0.00MB
wp_UPCP_Categories: Data: 0.02MB + Index: 0.00MB
wp_UPCP_Custom_Fields: Data: 0.02MB + Index: 0.00MB
wp_UPCP_Fields_Meta: Data: 0.02MB + Index: 0.00MB
wp_UPCP_Items: Data: 0.02MB + Index: 0.00MB
wp_UPCP_Item_Images: Data: 0.02MB + Index: 0.00MB
wp_UPCP_SubCategories: Data: 0.02MB + Index: 0.00MB
wp_UPCP_Tagged_Items: Data: 0.02MB + Index: 0.00MB
wp_UPCP_Tags: Data: 0.02MB + Index: 0.00MB
wp_UPCP_Tag_Groups: Data: 0.02MB + Index: 0.00MB
wp_UPCP_Videos: Data: 0.02MB + Index: 0.00MB
wp_usermeta: Data: 1.52MB + Index: 1.94MB
wp_users: Data: 0.08MB + Index: 0.05MB
wp_wcpdf_invoice_number: Data: 0.05MB + Index: 0.00MB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB
wp_weu_subscribers: Data: 0.02MB + Index: 0.00MB
wp_weu_unsubscriber: Data: 0.02MB + Index: 0.00MB
wp_weu_user_notification: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_pickup_locations_geodata: Data: 0.02MB + Index: 0.05MB
wp_woof_query_cache: Data: 0.02MB + Index: 0.02MB
wp_wpgmza: Data: 0.02MB + Index: 0.00MB
wp_wpgmza_categories: Data: 0.02MB + Index: 0.00MB
wp_wpgmza_category_maps: Data: 0.02MB + Index: 0.00MB
wp_wpgmza_circles: Data: 0.02MB + Index: 0.00MB
wp_wpgmza_datasets: Data: 0.02MB + Index: 0.00MB
wp_wpgmza_maps: Data: 0.02MB + Index: 0.00MB
wp_wpgmza_polygon: Data: 0.02MB + Index: 0.00MB
wp_wpgmza_polylines: Data: 0.02MB + Index: 0.00MB
wp_wpgmza_rectangles: Data: 0.02MB + Index: 0.00MB
wp_wplc_chat_msgs: Data: 0.22MB + Index: 0.00MB
wp_wplc_chat_ratings: Data: 0.02MB + Index: 0.00MB
wp_wplc_chat_sessions: Data: 0.08MB + Index: 0.00MB
wp_wplc_chat_triggers: Data: 0.02MB + Index: 0.00MB
wp_wplc_custom_fields: Data: 0.02MB + Index: 0.00MB
wp_wplc_departments: Data: 0.02MB + Index: 0.00MB
wp_wplc_devices: Data: 0.02MB + Index: 0.00MB
wp_wplc_offline_messages: Data: 0.02MB + Index: 0.00MB
wp_wplc_roi_conversions: Data: 0.02MB + Index: 0.00MB
wp_wplc_roi_goals: Data: 0.02MB + Index: 0.00MB
wp_wplc_webhooks: Data: 0.02MB + Index: 0.00MB

### Post Type Counts ###

attachment: 221
customize_changeset: 3
custom_css: 1
fl-builder-template: 1
fpf_fields: 1
google_maps: 1
ich_cpt: 1
jetpack_migration: 2
jp_img_sitemap: 1
jp_sitemap: 1
jp_sitemap_master: 1
ml-slide: 1
ml-slider: 1
nav_menu_item: 14
oembed_cache: 1
page: 17
pickup_location: 4
popup: 5
popup_theme: 6
post: 4
product: 73
product_variation: 149
rd-hover: 1
revision: 191
shop_coupon: 78
shop_order: 1140
shop_order_refund: 33
wc_pickup_location: 5
woo_product_tab: 3
wpcf7_contact_form: 1
xlwcty_thankyou: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (28) ###

WooODT extended: by Mrinmoy Dalabar – 1.0.6.1 – Not tested with the active version of WooCommerce
Advanced Custom CSS: by Prasad Kirpekar – 1.0.0
Beaver Builder Cards: by Beaver Builder Addon – 1.1.0
Beaver Builder Header Footer: by Brainstorm Force – 1.1.7
Beaver Builder Plugin (Standard Version): by The Beaver Builder Team – 2.1.3.5
Booster Plus for WooCommerce: by Algoritmika Ltd – 3.7.0 – Not tested with the active version of WooCommerce
CB Custom Beaver Builder Modules: by Crafty Beavers – 1.5.7
Contact Form 7: by Takayuki Miyoshi – 5.0.3
Lightweight Social Icons: by Thomas Usborne – 1.0.1
MailChimp for WooCommerce: by MailChimp – 2.1.9 – Not tested with the active version of WooCommerce
Popup Maker: by WP Popup Maker – 1.7.29
PowerPack Lite for Beaver Builder: by Beaver Addons – 1.2.2
Ship to Different Address Unchecked for WooCommerce: by eCreations – 1.1 – Not tested with the active version of WooCommerce
SSL Insecure Content Fixer: by WebAware – 2.7.0
Ultimate Addons for Beaver Builder - Lite: by Brainstorm Force – 1.2.3
WC Password Strength Settings: by Daniel Santoro – 2.0.2 – Not tested with the active version of WooCommerce
Woocommerce Add-to-Cart Custom Redirect: by Ren Ventura – 1.2.3 – Not tested with the active version of WooCommerce
WooCommerce Checkout Manager: by Visser Labs – 4.2.3 – Not tested with the active version of WooCommerce
WooCommerce MailChimp: by Saint Systems – 2.1.12 – Not tested with the active version of WooCommerce
WooCommerce Menu Cart: by Jeremiah Prummer
Ewout Fernhout – 2.7.1 – Not tested with the active version of WooCommerce

Advanced Order Export For WooCommerce (Pro): by AlgolPlus – 1.5.1 – Not tested with the active version of WooCommerce
WooCommerce PDF Invoices & Packing Slips: by Ewout Fernhout – 2.1.10 – Not tested with the active version of WooCommerce
WooCommerce PDF Invoices & Packing Slips Premium Templates: by Ewout Fernhout – 2.5.6 – Not tested with the active version of WooCommerce
WooCommerce Smart Coupons: by WooCommerce – 3.3.6 – Not tested with the active version of WooCommerce
WooCommerce Square: by WooCommerce – 1.0.31 – Not tested with the active version of WooCommerce
WooCommerce: by Automattic – 3.4.4
WP Google Maps - Pro Add-on: by WP Google Maps – 6.19
WP Google Maps: by WP Google Maps – 6.4.09

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: CAD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #10 - /menu/
Cart: #11 - /cart/
Checkout: #12 - /checkout/
My account: #13 - /my-account/
Terms and conditions: #535 - /terms-conditions/

### Theme ###

Name: Astra
Version: 1.4.4
Author URL: http://wpastra.com/about/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –
`
</details>

### PR DESCRIPTION
**Pull request by TimBHowe**
Added a call to the evaluate_cost function in the flat rate shipping cost input's sanitize_cost function to throw an exception if there is an illegal character in the input in the back end to avoid the error going unnoticed until a user/customer hits it in the front-end

### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:
This change would run the the evaluate_cost function on the flat rate shipping's input sanitize_cost function throwing any error in the back-end before they happen on the front end.
Closes #20921

### How to test the changes in this Pull Request:

1. In WooCommerce General Settings set the site currency to EUR €.
2. Set up a shipping zone with a flat rate shipping method.
3. Enter a USD $ currency symbol or some other invalid character like an under score _ into the cost field.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Fix: Added validation to the cost field for flat rate shipping.

### CODE REVIEW

**Comment by peterfabian** [comment]
Thanks for your contribution, @TimBHowe . Would you mind fixing the other input in Setup Wizard as per comment https://github.com/woocommerce/woocommerce/issues/20921#issuecomment-559537243?

**Comment by TimBHowe** [comment]
Hey so I added some additional check to sanitize the input removing the set currency symbol when saving the value in the set up wiz.

Also added the pattern attribute which should support entering only numbers, periods and commas in both the US and EU currency format standards.

I wanted to also add the pattern attribute to the flat rate settings inputs, but as they are sent via ajax it would need to use something like the [checkValidity](https://developer.mozilla.org/en-US/docs/Web/API/HTMLSelectElement/checkValidity) and didn't know if it would be ok to use/add.

Otherwise this should fix most of the problem. The sanitation on the wiz is not as strong and it might help to add additional instructions laying out the rules, but this should be a good start.

File: includes/admin/class-wc-admin-setup-wizard.php [hunk 1]
```diff
@@ -937,6 +937,7 @@ protected function get_wizard_shipping_methods( $country_code, $currency_code )
 						'default_value' => __( 'Cost', 'woocommerce' ),
 						'description'   => __( 'What would you like to charge for flat rate shipping?', 'woocommerce' ),
 						'required'      => true,
+						'pattern'       => '^[+-]?[0-9]{1,3}(?:[0-9]*(?:[.,][0-9]{2})?|(?:,[0-9]{3})*(?:\.[0-9]{2})?|(?:\.[0-9]{3})*(?:,[0-9]{2})?)$',
```
Comment (ObliviousHarmony) [inline includes/admin/class-wc-admin-setup-wizard.php]: Due to the way browsers display pattern errors, I don't think we should add this constraint. Having a server-side error thrown for invalid formats should be sufficient.

File: includes/admin/class-wc-admin-setup-wizard.php [hunk 2]
```diff
@@ -1279,13 +1281,19 @@ public function wc_setup_shipping_save() {
 
 			// Save chosen shipping method settings (using REST controller for convenience).
 			if ( ! empty( $_POST['shipping_zones']['domestic'][ $domestic_method ] ) ) { // WPCS: input var ok.
+
+				// Sanitize the cost field.
+				$domestic_cost = wc_clean( wp_unslash( $_POST['shipping_zones']['domestic'][ $domestic_method ] ) );
+				$domestic_cost = str_replace( array( get_woocommerce_currency_symbol(), html_entity_decode( get_woocommerce_currency_symbol() ) ), '', $domestic_cost );
```
Comment (ObliviousHarmony) [inline includes/admin/class-wc-admin-setup-wizard.php]: Since the primary reason for this PR is to change the sanitization on the flat rate shipping method, I don't think we should make a change to the wizard that would affect others. I agree that the sanitization here could be a lot better though!

File: includes/admin/class-wc-admin-setup-wizard.php [hunk 3]
```diff
@@ -1297,13 +1305,19 @@ public function wc_setup_shipping_save() {
 		if ( $setup_intl ) {
 			// Save chosen shipping method settings (using REST controller for convenience).
 			if ( ! empty( $_POST['shipping_zones']['intl'][ $intl_method ] ) ) { // WPCS: input var ok.
+
+				// Sanitize the cost field.
+				$intl_cost = wc_clean( wp_unslash( $_POST['shipping_zones']['intl'][ $intl_method ] ) );
+				$intl_cost = str_replace( array( get_woocommerce_currency_symbol(), html_entity_decode( get_woocommerce_currency_symbol() ) ), '', $intl_cost );
```
Comment (ObliviousHarmony) [inline includes/admin/class-wc-admin-setup-wizard.php]: Same as the other!

**Review by ObliviousHarmony — CHANGES_REQUESTED** [review]
Thank you very much for the contribution! I've left some comments for you!

File: includes/admin/class-wc-admin-setup-wizard.php (hunk 3 above)
Comment (ObliviousHarmony) [reply includes/admin/class-wc-admin-setup-wizard.php]: This will work fine.

File: includes/admin/class-wc-admin-setup-wizard.php (hunk 2 above)
Comment (ObliviousHarmony) [reply includes/admin/class-wc-admin-setup-wizard.php]: This will work fine.

File: includes/admin/class-wc-admin-setup-wizard.php (hunk 1 above)
Comment (ObliviousHarmony) [reply includes/admin/class-wc-admin-setup-wizard.php]: Hey @TimBHowe,

Did you want to wrap this PR up?

Comment (TimBHowe) [reply includes/admin/class-wc-admin-setup-wizard.php]: Ok, I'll remove it.

**Review by ObliviousHarmony — APPROVED** [review]
Looks good to me, thanks for the fine work!
