### PR TITLE
[e2e tests] Fix flakiness in page publishing action

### LINKED ISSUE #50325: [Flaky Test] prevents cart block applying coupon with usage limit
**Flaky test detected. This is an auto-generated issue by GitHub Actions. Please do NOT edit this manually.**

## Test title
prevents cart block applying coupon with usage limit

## Test path
`/plugins/woocommerce/tests/e2e-pw/tests/shopper/cart-block-coupons.spec.js`

## Errors

<time datetime="2024-08-03T03:57:50.917Z"><code>[2024-08-03T03:57:50.917Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/woocommerce/woocommerce/actions/runs/10224974129"><code>trunk</code></a>.
<br/>
<details>
<summary>
	<time datetime="2024-09-04T08:18:29.454Z"><code>[2024-09-04T08:18:29.454Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/woocommerce/woocommerce/actions/runs/10694609002"><code>trunk</code></a>.
</summary>

```
Error: Timed out 20000ms waiting for expect(locator).toBeVisible()

Locator: getByText('Cart Block Page 64ca4f34 is now live.')
Expected: visible
Received: <element(s) not found>
Call log:
  - expect.toBeVisible with timeout 20000ms
  - waiting for getByText('Cart Block Page 64ca4f34 is now live.')

    at publishPage (/home/runner/work/woocommerce/woocommerce/plugins/woocommerce/tests/e2e-pw/utils/editor.js:141:4)
    at Object.page (/home/runner/work/woocommerce/woocommerce/plugins/woocommerce/tests/e2e-pw/tests/shopper/cart-block-coupons.spec.js:44:3)
```
</details>

### LINKED ISSUE #50326: [Flaky Test] should show correct total cart block price after updating quantity
**Flaky test detected. This is an auto-generated issue by GitHub Actions. Please do NOT edit this manually.**

## Test title
should show correct total cart block price after updating quantity

## Test path
`/plugins/woocommerce/tests/e2e-pw/tests/shopper/cart-block-calculate-shipping.spec.js`

## Errors

<time datetime="2024-08-03T03:57:51.486Z"><code>[2024-08-03T03:57:51.486Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/woocommerce/woocommerce/actions/runs/10224974129"><code>trunk</code></a>.
<br/>
<time datetime="2024-08-08T04:17:08.879Z"><code>[2024-08-08T04:17:08.879Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/woocommerce/woocommerce/actions/runs/10295464681"><code>trunk</code></a>.
<br/>
<time datetime="2024-08-08T14:13:55.459Z"><code>[2024-08-08T14:13:55.459Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/woocommerce/woocommerce/actions/runs/10295464681"><code>trunk</code></a>.
<br/>
<details>
<summary>
	<time datetime="2024-08-29T04:09:20.439Z"><code>[2024-08-29T04:09:20.439Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/woocommerce/woocommerce/actions/runs/10608212283"><code>trunk</code></a>.
</summary>

```
Error: Timed out 20000ms waiting for expect(locator).toBeVisible()

Locator: getByText('Cart Block Page 04aea519 is now live.')
Expected: visible
Received: <element(s) not found>
Call log:
  - expect.toBeVisible with timeout 20000ms
  - waiting for getByText('Cart Block Page 04aea519 is now live.')

    at publishPage (/home/runner/work/woocommerce/woocommerce/plugins/woocommerce/tests/e2e-pw/utils/editor.js:141:4)
    at Object.cartBlockPage (/home/runner/work/woocommerce/woocommerce/plugins/woocommerce/tests/e2e-pw/tests/shopper/cart-block-calculate-shipping.spec.js:28:3)
```
</details>

### LINKED ISSUE #50330: [Flaky Test] allows cart block to apply coupon of any type
**Flaky test detected. This is an auto-generated issue by GitHub Actions. Please do NOT edit this manually.**

## Test title
allows cart block to apply coupon of any type

## Test path
`/plugins/woocommerce/tests/e2e-pw/tests/shopper/cart-block-coupons.spec.js`

## Errors

<time datetime="2024-08-04T03:57:35.035Z"><code>[2024-08-04T03:57:35.035Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/woocommerce/woocommerce/actions/runs/10233173089"><code>trunk</code></a>.
<br/>
<time datetime="2024-08-15T03:57:13.495Z"><code>[2024-08-15T03:57:13.495Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/woocommerce/woocommerce/actions/runs/10398329666"><code>trunk</code></a>.
<br/>
<time datetime="2024-08-19T04:02:57.151Z"><code>[2024-08-19T04:02:57.151Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/woocommerce/woocommerce/actions/runs/10446649380"><code>trunk</code></a>.
<br/>
<time datetime="2024-08-23T03:58:11.747Z"><code>[2024-08-23T03:58:11.747Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/woocommerce/woocommerce/actions/runs/10519399661"><code>trunk</code></a>.
<br/>
<time datetime="2024-08-27T04:01:06.412Z"><code>[2024-08-27T04:01:06.412Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/woocommerce/woocommerce/actions/runs/10571208112"><code>trunk</code></a>.
<br/>
<time datetime="2025-01-14T17:18:15.215Z"><code>[2025-01-14T17:18:15.215Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/woocommerce/woocommerce/actions/runs/12772551460"><code>add/42079-additional-fields=persistent-updates</code></a>.
<br/>
<details>
<summary>
	<time datetime="2025-01-22T10:22:31.378Z"><code>[2025-01-22T10:22:31.378Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/woocommerce/woocommerce/actions/runs/12905336605"><code>add/42079-additional-fields=persistent-updates</code></a>.
</summary>

```
Error: Timed out 20000ms waiting for expect(locator).toBeVisible()

Locator: locator('.wc-block-components-notice-banner__content').getByText('Coupon code "50percoff" has been removed from your cart.')
Expected: visible
Received: <element(s) not found>
Call log:
  - expect.toBeVisible with timeout 20000ms
  - waiting for locator('.wc-block-components-notice-banner__content').getByText('Coupon code "50percoff" has been removed from your cart.')

    at /home/runner/work/woocommerce/woocommerce/plugins/woocommerce/tests/e2e-pw/tests/shopper/cart-block-coupons.spec.js:175:8
```
</details>

### LINKED ISSUE #50735: [Flaky Test] can see empty cart, add and remove simple & cross sell product, increase to max quantity
**Flaky test detected. This is an auto-generated issue by GitHub Actions. Please do NOT edit this manually.**

## Test title
can see empty cart, add and remove simple & cross sell product, increase to max quantity

## Test path
`/plugins/woocommerce/tests/e2e-pw/tests/shopper/cart-block.spec.js`

## Errors

<time datetime="2024-08-17T03:58:52.918Z"><code>[2024-08-17T03:58:52.918Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/woocommerce/woocommerce/actions/runs/10429211019"><code>trunk</code></a>.
<br/>
<time datetime="2024-08-20T04:00:38.343Z"><code>[2024-08-20T04:00:38.343Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/woocommerce/woocommerce/actions/runs/10464797357"><code>trunk</code></a>.
<br/>
<time datetime="2024-09-04T08:18:27.828Z"><code>[2024-09-04T08:18:27.828Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/woocommerce/woocommerce/actions/runs/10694609002"><code>trunk</code></a>.
<br/>
<time datetime="2025-01-07T16:46:47.801Z"><code>[2025-01-07T16:46:47.801Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/woocommerce/woocommerce/actions/runs/12655027749"><code>add/42079-additional-fields=persistent-updates</code></a>.
<br/>
<time datetime="2025-01-13T17:29:35.995Z"><code>[2025-01-13T17:29:35.995Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/woocommerce/woocommerce/actions/runs/12752276923"><code>add/42079-additional-fields=persistent-updates</code></a>.
<br/>
<time datetime="2025-01-14T16:21:31.068Z"><code>[2025-01-14T16:21:31.068Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/woocommerce/woocommerce/actions/runs/12752276923"><code>add/42079-additional-fields=persistent-updates</code></a>.
<br/>
<time datetime="2025-01-21T15:02:48.353Z"><code>[2025-01-21T15:02:48.353Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/woocommerce/woocommerce/actions/runs/12888906003"><code>add/42079-additional-fields=persistent-updates</code></a>.
<br/>
<time datetime="2025-01-22T10:22:32.333Z"><code>[2025-01-22T10:22:32.333Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/woocommerce/woocommerce/actions/runs/12905336605"><code>add/42079-additional-fields=persistent-updates</code></a>.
<br/>
<time datetime="2025-01-24T10:54:20.795Z"><code>[2025-01-24T10:54:20.795Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/woocommerce/woocommerce/actions/runs/12947970295"><code>add/42079-additional-fields=persistent-updates</code></a>.
<br/>
<details>
<summary>
	<time datetime="2025-01-24T17:21:13.620Z"><code>[2025-01-24T17:21:13.620Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/woocommerce/woocommerce/actions/runs/12953784412"><code>add/42079-additional-fields=persistent-updates</code></a>.
</summary>

```
Error: Timed out 20000ms waiting for expect(locator).toBeHidden()

Locator: getByRole('heading', { name: 'You may be interested in…' })
Expected: hidden
Received: visible
Call log:
  - expect.toBeHidden with timeout 20000ms
  - waiting for getByRole('heading', { name: 'You may be interested in…' })
    24 × locator resolved to <h2 class="wp-block-heading has-large-font-size">You may be interested in…</h2>
       - unexpected value "visible"

    at /home/runner/work/woocommerce/woocommerce/plugins/woocommerce/tests/e2e-pw/tests/shopper/cart-block.spec.js:185:7
```
</details>

### LINKED ISSUE #51026: [Flaky Test] prevents cart block applying same coupon twice
**Flaky test detected. This is an auto-generated issue by GitHub Actions. Please do NOT edit this manually.**

## Test title
prevents cart block applying same coupon twice

## Test path
`/plugins/woocommerce/tests/e2e-pw/tests/coupons/cart-block-coupons.spec.js`

## Errors

<time datetime="2024-08-29T04:09:19.642Z"><code>[2024-08-29T04:09:19.642Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/woocommerce/woocommerce/actions/runs/10608212283"><code>trunk</code></a>.
<br/>
<time datetime="2024-08-30T04:12:05.940Z"><code>[2024-08-30T04:12:05.940Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/woocommerce/woocommerce/actions/runs/10626352951"><code>trunk</code></a>.
<br/>
<time datetime="2024-09-04T08:18:30.376Z"><code>[2024-09-04T08:18:30.376Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/woocommerce/woocommerce/actions/runs/10694609002"><code>trunk</code></a>.
<br/>
<time datetime="2025-06-30T11:28:36.422Z"><code>[2025-06-30T11:28:36.422Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/woocommerce/woocommerce/actions/runs/15971294327"><code>cfe/fix/payments-nox-step-statuses-on-switch-to-live-via-client</code></a>.
<br/>
<time datetime="2025-07-28T11:18:11.859Z"><code>[2025-07-28T11:18:11.859Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/woocommerce/woocommerce/actions/runs/16567241938"><code>wooplug-4986-generic-block-i</code></a>.
<br/>
<time datetime="2025-07-28T12:29:14.093Z"><code>[2025-07-28T12:29:14.093Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/woocommerce/woocommerce/actions/runs/16567241938"><code>wooplug-4986-generic-block-i</code></a>.
<br/>
<time datetime="2025-11-10T15:58:35.830Z"><code>[2025-11-10T15:58:35.830Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/woocommerce/woocommerce/actions/runs/19236746391"><code>fix/site-editor-warnings</code></a>.
<br/>
<time datetime="2025-11-14T14:41:24.537Z"><code>[2025-11-14T14:41:24.537Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/woocommerce/woocommerce/actions/runs/19366831676"><code>wooprd-998-media-library-doesnt-work-on-freshly-re-loaded-email-editor</code></a>.
<br/>
<details>
<summary>
	<time datetime="2025-11-14T15:34:42.048Z"><code>[2025-11-14T15:34:42.048Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/woocommerce/woocommerce/actions/runs/19366831676"><code>wooprd-998-media-library-doesnt-work-on-freshly-re-loaded-email-editor</code></a>.
</summary>

```
Error: Timed out 20000ms waiting for expect(locator).toBeVisible()

Locator: getByRole('alert').getByText('Coupon code "5fixedcart" has already been applied.')
Expected: visible
Received: <element(s) not found>
Call log:
  - expect.toBeVisible with timeout 20000ms
  - waiting for getByRole('alert').getByText('Coupon code "5fixedcart" has already been applied.')

    at /home/runner/work/woocommerce/woocommerce/plugins/woocommerce/tests/e2e-pw/tests/coupons/cart-block-coupons.spec.js:259:7
```
</details>

### PR DESCRIPTION
**Pull request by adimoldovan**
### Changes proposed in this Pull Request:

Fixes flakiness in the publishPage method. This mostly occurs when WooCommerce PayPal Payments is installed. After adding a cart block the tests proceed to publish the page and checks for the message `<Page title> is live`. But the PayPal setting panel sometimes interferes, and even though the page was successfully published the expected message is dismissed by the PayPal setting panel. 

The tricky part here was to find a solution that works for all cases, all environments and is fast enough without checking for installed plugins or panels that may or may not appear.

I opted to check for the API response to validate the page was published instead of checking the UI. I think this is fine because it's not really a WooCommerce flow anyway, and we can skip using the UI in this case.

Closes https://github.com/woocommerce/woocommerce/issues/51026
Closes https://github.com/woocommerce/woocommerce/issues/50735
Closes https://github.com/woocommerce/woocommerce/issues/50330
Closes https://github.com/woocommerce/woocommerce/issues/50326
Closes https://github.com/woocommerce/woocommerce/issues/50325

### How to test the changes in this Pull Request:

The affected specs are:

```
merchant/create-cart-block.spec.js merchant/create-checkout-block.spec.js merchant/create-page.spec.js merchant/create-post.spec.js merchant/create-woocommerce-blocks.spec.js merchant/create-woocommerce-patterns.spec.js shopper/cart-block-calculate-shipping.spec.js shopper/cart-block-coupons.spec.js shopper/cart-block.spec.js shopper/cart-checkout-block-calculate-tax.spec.js shopper/checkout-block-coupons.spec.js shopper/checkout-block.spec.js shopper/hop-products-filter-by-price.spec.js
```

- Check CI - it should be green
- Run the affected specs with multiple environments, multiple times:

Basic setup
```
pnpm test:e2e merchant/create-cart-block.spec.js merchant/create-checkout-block.spec.js merchant/create-page.spec.js merchant/create-post.spec.js merchant/create-woocommerce-blocks.spec.js merchant/create-woocommerce-patterns.spec.js shopper/cart-block-calculate-shipping.spec.js shopper/cart-block-coupons.spec.js shopper/cart-block.spec.js shopper/cart-checkout-block-calculate-tax.spec.js shopper/checkout-block-coupons.spec.js shopper/checkout-block.spec.js shopper/hop-products-filter-by-price.spec.js
```
With WooCommerce PayPal Payments
```
pnpm test:e2e:with-env woocommerce-paypal-payments merchant/create-cart-block.spec.js merchant/create-checkout-block.spec.js merchant/create-page.spec.js merchant/create-post.spec.js merchant/create-woocommerce-blocks.spec.js merchant/create-woocommerce-patterns.spec.js shopper/cart-block-calculate-shipping.spec.js shopper/cart-block-coupons.spec.js shopper/cart-block.spec.js shopper/cart-checkout-block-calculate-tax.spec.js shopper/checkout-block-coupons.spec.js shopper/checkout-block.spec.js shopper/hop-products-filter-by-price.spec.js
```
With Gutenberg
```
pnpm test:e2e:with-env gutenberg-stable merchant/create-cart-block.spec.js merchant/create-checkout-block.spec.js merchant/create-page.spec.js merchant/create-post.spec.js merchant/create-woocommerce-blocks.spec.js merchant/create-woocommerce-patterns.spec.js shopper/cart-block-calculate-shipping.spec.js shopper/cart-block-coupons.spec.js shopper/cart-block.spec.js shopper/cart-checkout-block-calculate-tax.spec.js shopper/checkout-block-coupons.spec.js shopper/checkout-block.spec.js shopper/hop-products-filter-by-price.spec.js
```

### CODE REVIEW

File: plugins/woocommerce/tests/e2e-pw/utils/editor.js [hunk 1]
```diff
@@ -129,17 +129,35 @@ const transformIntoBlocks = async ( page ) => {
...
+			response
+				.json()
+				.then(
+					( json ) =>
+						json.title.rendered === pageTitle &&
+						json.status === 'publish'
+				)
+		);
+	} );
+
```
Comment (lanej0) [inline plugins/woocommerce/tests/e2e-pw/utils/editor.js:151]: Might be good to log errors here (to console) in case the API request starts failing.  Might make troubleshooting easier.

**Review by lanej0 — APPROVED** [review]
Ran the default environment tests 10 times locally, and no issues.  No issues running with either plugin installed either.  

One minor suggestion, but not a blocker if we want to merge and add in a follow up PR 👍🏼
