### PR TITLE
Customer Account: Don't hook block unless filter is available.

### LINKED ISSUE #47168: In WP 6.4.4, the newly added CustomerAccount block to the header has an attached label in certain themes
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Discovered while doing 8.9 Beta testing.

This issue could be related to https://github.com/woocommerce/woocommerce/pull/43267

In WP 6.4.4, the CustomerAccount block in the header contains an attached label. The following themes where I saw the labels are:
- Tsubaki
- TT4

In WP 6.5, the label is not shown as expected:
Screenshot from 2024-05-06 15-30-21

But in WP 6.4, the label appears:
Screenshot 2024-05-06 at 3 48 37 PM

### Expected behavior

There should be a consistent behavior of the CustomerAccount block in both WP 6.5 and WP 6.4. Inferring from the testing instructions in https://github.com/woocommerce/woocommerce/pull/43267, there should be no label for the CustomerAccount block in both WP versions.

### Actual behavior

In WP 6.4.4, the CustomerAccount block appears with a label in Tsubaki and TT4. 

### Steps to reproduce

1. Install WP 6.4.4 and WC 8.9 Beta 2. You can get the beta 2 [here](https://a8c.slack.com/archives/C01DT6U03HC/p1714567961381599?thread_ts=1714003650.636069&cid=C01DT6U03HC).
2. Use either TT4 or Tsubaki theme.
3. As a shopper, visit the store's homepage.
4. Notice that the customer account block in the header has an attached label

### WordPress Environment

WP 6.4.4
WC 8.9.0-beta.2
Theme: Tsubaki or TT4

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by tjcafferkey**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Before hooking the Customer Account block we need to check that the `hooked_block_{$hooked_block_type}` filter is available which was added in 6.5 (`hooked_block_types` was added in 6.4) so we can hide the label of the hooked block.

I tried to think of a way of checking compatibility without checking `$wp_version` but since we are the only code adding the filter 'hooked_block_woocommerce/customer-account' it means using `has_filter()` for a compatibility check won't work because `add_filter()` is used in the same file.

Closes https://github.com/woocommerce/woocommerce/issues/47168

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Install WooCommerce and Core Rollback plugin
2. Check Customer Account is added to the header of TT4 without a label on latest WP
3. Use Core Rollback to re-install 6.4.4
4. Check that the Customer Account block is now omitted from the header.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message

Don't automatically insert hooked customer account block into header for sites running less than WP 6.5

#### Comment

Check we can use filter hooked_block_woocommerce/customer-account to hide label before adding block to the header

</details>

### CODE REVIEW

File: plugins/woocommerce/src/Blocks/BlockTypes/CustomerAccount.php [hunk 1]
```diff
@@ -41,8 +41,16 @@ class CustomerAccount extends AbstractBlock {
...
 		parent::initialize();
-		add_filter( 'hooked_block_types', array( $this, 'register_hooked_block' ), 9, 4 );
-		add_filter( 'hooked_block_woocommerce/customer-account', array( $this, 'modify_hooked_block_attributes' ), 10, 5 );
+		/**
+		 * The hooked_block_{$hooked_block_type} filter was added in WordPress 6.5.
+		 * We are the only code adding the filter 'hooked_block_woocommerce/customer-account'.
+		 * Using has_filter() for a compatibility check won't work because add_filter() is used in the same file.
+		 */
+		global $wp_version;
+		if ( version_compare( $wp_version, '6.5', '>=' ) ) {
```
Comment (opr) [inline plugins/woocommerce/src/Blocks/BlockTypes/CustomerAccount.php]: Looks like we do a WP Version comparison like so in MiniCart.php

https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/src/Blocks/BlockTypes/MiniCart.php#L179

```php
if ( version_compare( get_bloginfo( 'version' ), '5.9', '<' ) )
```

maybe switching to that would be better?

**Review by opr — APPROVED** [review]
Functionality wise this works for me, and code-wise this seems like a sound approach, but I added one suggestion about re-using a pattern we have in place already (only a slight difference to what you have here).

File: plugins/woocommerce/src/Blocks/BlockTypes/CustomerAccount.php (hunk 1 above)
Comment (tjcafferkey) [reply plugins/woocommerce/src/Blocks/BlockTypes/CustomerAccount.php]: Nice, thanks! Updated in https://github.com/woocommerce/woocommerce/pull/47171/commits/0204c0a1c290bebf971f32fe30aaf682711c7c94

Will merge once CI passes
