### PR TITLE
Merging plugin's tax_queries on REST endpoint, fixes #20914

### LINKED ISSUE #20914: Plugin's tax_queries are being overwritten by category search
**Describe the bug**
As a plugin author I'm using the ``woocommerce_rest_product_object_query`` filter to add an additional argument to the REST products endpoint (which later triggers a tax_query). This works fine as long as the default ``category`` argument is not used at the same time, because this overwrites all ``tax_query``s and the plugins ``tax_query``s are no longer applied.

**To Reproduce**
This is a simplified plugin function that allows to specify tags of products that should **not** be returned by the REST endpoint.
```
add_filter('woocommerce_rest_product_object_query', 'add_negative_tags', 10, 2);

function add_negative_tags($args, $request) {
    if ($request->get_param('not_tags')) {
        $args['tax_query'][] =
            array(
                'taxonomy' => 'product_tag',
                'field'    => 'slug',
                'terms'    => $request->get_param('not_tags'),
                'operator' => 'NOT IN'
            );
    }
    return $args;
}
```
This works fine as long as the ``category`` argument is not used at the same time.

**Expected behavior**
The ``WC_REST_Products_Controller`` should merge it's own ``tax_query`` with the ``tax_query`` from plugins to respect arguments added by plugins.
At the moment I don't see any other way to allow this plugin functionality.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

I will submit a pull request for review.

### PR DESCRIPTION
**Pull request by stromhalm**
### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

This change ensures that third party plugin's ``tax_query``s are respected when the ``category`` argument is used on the product's REST endpoint.

Closes #20914 .

### How to test the changes in this Pull Request:

The plugin function in #20914 works as expected.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

### Changelog entry

>  Third party plugin's ``tax_query``s are respected when the ``category`` argument is used on the product's REST endpoint.

### CODE REVIEW

File: includes/api/class-wc-rest-products-controller.php [hunk 1]
```diff
@@ -237,7 +237,7 @@ protected function prepare_objects_query( $request ) {
 		}
 
 		if ( ! empty( $tax_query ) ) {
-			$args['tax_query'] = $tax_query; // WPCS: slow query ok.
+			$args['tax_query'] = array_merge($tax_query, $args['tax_query']); // WPCS: slow query ok.
```
Comment (claudiulodro) [inline includes/api/class-wc-rest-products-controller.php]: - `$args['tax_query']` may not necessarily be set. This should check `$args['tax_query']` exists before doing the `array_merge`. [See the failing tests](https://travis-ci.org/woocommerce/woocommerce/jobs/408573093#L930-L1023)
- The WP style guide requires spaces between parentheses and their contents. [See the failing style check](https://travis-ci.org/woocommerce/woocommerce/jobs/408573093#L1036-L1042).

**Review by claudiulodro — CHANGES_REQUESTED** [review]
Thanks for the contribution. Just a couple changes then this can be merged.

File: includes/api/class-wc-rest-products-controller.php (hunk 1 above)
Comment (stromhalm) [reply includes/api/class-wc-rest-products-controller.php]: Thanks @claudiulodro for your feedback! I have made your requested changes, hope it‘s fine now.

Comment (claudiulodro) [reply includes/api/class-wc-rest-products-controller.php]: Looks great! Thanks.

**Review by claudiulodro — APPROVED** [review]
