### PR TITLE
Fix a bug where woocommerce removes the current-menu-item class

### LINKED ISSUE #46060: Woocommerce removes the current-menu-item class
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

In case of WooCommerce usage, the current-menu-item class is removed

see this PR https://github.com/woocommerce/woocommerce/pull/45095

### Expected behavior

Woo must not remove the classes, especially the current-menu-item that permits to style any selected entry

### Actual behavior

We cannot style the current entry within the menu
the WP current-menu-item class is removed

### Steps to reproduce

1. Use TT4 theme
2. Add a navigation
3. Observe that the current-menu-item-class is not present in case you click on a menu entry
4. Works in case no woocommerce entry is there in the navigation bar

### WordPress Environment

WP 6.4.3 
Woo 8.7
TT4

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by benn0r**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

`wc_nav_menu_item_classes` can currently remove the `current-menu-item` from a taxonomy menu item if its ID matches with the ID of the `page_for_posts`. This PR adds the menu_item type `page` as a condition.

Fixes #46060

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

Note that we need to create a conflict between a category ID and a page ID to reproduce this issue. Since creating that conflict like that is cumbersome, we will directly edit the setting as part of testing instructions so that we can test.
1. Switch to a theme that allows modifying menu items directly, such as store front.
2. Add a new product category, or use an existing one. Note down it's ID, (to get the ID of category, open it for editing, and note the `tag_ID` in the URL).
3. Update the option for posts for page like so: `wp option set 'page_for_posts' XXX` where `XXX` is the category ID.
4. Add this category as a menu navigation item, by going to Appearance > Menu and add the Product Category as menu item. Note that if you don't see the Product Category as an option, you would have to enable by clicking on the Screen Options and enabling product categories.
Screenshot 2024-06-26 at 3 31 50 PM
5. Add this category in menu and save.
6. Go to frontend and click on this category from navigation bar.
7. Make sure that it displays as selected.

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

Fix a bug where woocommerce removes the current-menu-item class.

#### Comment 

</details>

### CODE REVIEW

**Comment by lsinger** [comment]
Closing and re-opening to make the checks run again.

**Review by lsinger — CHANGES_REQUESTED** [review]
Thank you, @benn0r. Unfortunately I'm having trouble reproducing the issue on `trunk`. 

I have a category with a term_ID that matches the page ID of the page set as the posts page. Both are present in the main navigation. When I navigate to the posts page, the list item that contains the link has a class of `current-menu-item` added. When I navigate to the category page, this link's list item *also* has that class added. 

Could you refine your testing instructions to make sure I'm not doing something wrong here?

**Comment by Marc-pi** [comment]
hello,
i do confirm we have this  issue, for instance with TT4
WP6.4.3 / Woo 8.7
is there any chance we get a fix on this, so our nav highligh can work ?

**Comment by Marc-pi** [comment]
Hello,
who can have a look at this so it can be shipped soon
it's a very annoying bug, preventing us to design the current menu highlighting (UX)
ping @vedanshujain

**Review by vedanshujain — APPROVED** [review]
LGTM! Category has the selected class even when there's conflict:

Screenshot 2024-06-26 at 3 36 22 PM

@benn0r can you please rebase your PR with latest trunk so that CI passes.

**Comment by Marc-pi** [comment]
It is a good news 😘

**Comment by benn0r** [comment]
> @benn0r can you please rebase your PR with latest trunk so that CI passes.

thanks for the update @vedanshujain. I updated the branch with Github "Sync" feature. I think it did a merge instead of a rebase. Tell me if i have to fix this or not.

File: plugins/woocommerce/includes/wc-page-functions.php [hunk 1]
```diff
@@ -168,7 +168,7 @@ function wc_nav_menu_item_classes( $menu_items ) {
 			$menu_id = (int) $menu_item->object_id;
 
 			// Unset active class for blog page.
-			if ( $page_for_posts === $menu_id ) {
+			if ( $page_for_posts === $menu_id && 'page' === $menu_item->object ) {
```
Comment (vedanshujain) [inline plugins/woocommerce/includes/wc-page-functions.php]: Let's add a defensive check here before we access the object (I don't see it being accessed anywhere else, so we don't know if it will necessarily be set)
```suggestion
			if ( $page_for_posts === $menu_id && isset( $menu_item->object ) && 'page' === $menu_item->object ) {
```

File: plugins/woocommerce/changelog/45095-trunk [hunk 2]
```diff
@@ -0,0 +1,4 @@
+Significance: patch
+Type: fix
+
+Fix a bug where woocommerce removes the current-menu-item class.  #### Comment <!-- If the changes in this pull request don't warrant a changelog entry, you can alternatively supply a comment here. Note that comments are only accepted with a significance of "Patch" -->
```
Comment (vedanshujain) [inline plugins/woocommerce/changelog/45095-trunk:4]:
```suggestion
Fix WC removing current-menu-item class when there's a page_id conflict.
```

**Review by vedanshujain — COMMENTED** [review]
Hey yes merging to trunk is fine. Added couple of suggestions that I just noticed for bit more defensive coding.

**Review by vedanshujain — APPROVED** [review]
LGTM!

**Comment by Marc-pi** [comment]
@vedanshujain the merge is blocked ;-)
