### PR TITLE
Removed  legacy notification to connect with WooCommerce

### LINKED ISSUE #25889: Connect your store JITM can't be dismissed
### Describe the bug
The JITM for connecting with WooCommerce.com is currently not dismissable and that could cause frustration for merchants who don't want to or need to connect. Not quite a bug but a usability issue. 

### To Reproduce
1. Go to a WooCommerce wp-admin dashboard for a store that's not yet connected to WooCommerce.com
2. See the JITM "Connect your store to WooCommerce.com to reveice extensions updates and support.
3. See issue that it can't be dismissed

### Expected behavior
We should use a class of JITM that can be dismissed, such as `notice is-dismissible notice-info` or add the X to dismiss to this class `updated woocommerce-message`.

### Scope / Impact
I think this will go a long way towards helping merchants maintain trust in our product. Not being able to dismiss a notice feels like you're being forced into something you may not necessarily want to do.

### Screenshots
Screen Shot 2020-03-11 at 11 25 59 AM

#### Desktop (please complete the following information):
- Mac OS 10.15.3
- Firefox 73.0.1

### PR DESCRIPTION
**Pull request by octaedro**
### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

This PR removes a legacy JITM for connecting with WooCommerce.com. This message is now a part of `WC Admin` bar via `Inbox`.

Closes #25889 .

### How to test the changes in this Pull Request:

1. Go to a WooCommerce wp-admin dashboard for a store that's not yet connected to WooCommerce.com
2. The JITM `Connect your store to WooCommerce.com to reveice extensions updates and support.` message shouldn't be visible.

### Other information:

* [x] Have you successfully run tests with your changes locally?

### CODE REVIEW

File: includes/admin/helper/class-wc-helper.php [hunk 1]
```diff
@@ -1527,12 +1527,6 @@ private static function _prompt_helper_connect( $screen_id ) {
 
 		$active_woo_plugins = array_intersect_key( $woo_plugins, array_flip( $active_plugins ) );
 
-		if ( count( $active_woo_plugins ) > 0 ) {
```
Comment (claudiosanches) [inline includes/admin/helper/class-wc-helper.php:1530]: Now this function there's no use, but will keep running in `WC_Helper::admin_notices`.
Also this a private method, so we can just remove it.

**Review by claudiosanches — CHANGES_REQUESTED** [review]

File: includes/admin/helper/class-wc-helper.php (hunk 1 above)
Comment (octaedro) [reply includes/admin/helper/class-wc-helper.php:1530]: Nice catch @claudiosanches! It's a good idea!
I removed the function in the commit  [134c0ea](https://github.com/woocommerce/woocommerce/pull/26167/commits/134c0ea0db8fd934053906f7c68beedf5af2ea30)

**Review by claudiosanches — APPROVED** [review]
LGTM!
