### PR TITLE
WC_Product_Variable_Data_Store_CPT: Add variable product transient validation

### LINKED ISSUE #50855: Persistent "This product is currently out of stock and unavailable." error on WooCommerce Products
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

I've found a persistent bug in woocommerce where products in stock, out of the blue, stop showing the variations and instead display the following message:

"This product is currently out of stock and unavailable."

This issue occurs even when the product is, in fact, available in stock. The problem affects both variable and non-variable products, making it difficult to pinpoint the exact cause based on the solutions available online.

The only temporary solution I've found so far is to edit the product, not make any changes at all, and click on update. Then the variations reappear. So far, this seems to have solved the problem with simple and variable products with just one attribute. But I have a category of variable products with two attributes, where I have seen this message reappear on a daily basis.

I've also found a similar issue reported on the woocommerce plugin support page and seems to happen to many people from the comments: https://wordpress.org/support/topic/this-product-is-currently-out-of-stock-and-unavailable-10/
Also on the web: https://stackoverflow.com/questions/24639288/woocommerce-products-showing-out-of-stock-message-when-not-actually-out-of-sto

### Expected behavior

That my products with stock and variations remain as such.

### Actual behavior

After a few days the product in the general grid doesn't show the "Out of stock" badge but when you enter the product page (single product) it shows the message "This product is currently out of stock and unavailable."

Captura de ecrã 2024-08-21, às 22 27 01

### Steps to reproduce

I'd love to know, but I still don't know what's causing this error. BUT:

1. I have a suspicion... I don't know if it's at the end of a day, two days, or just a few hours. But I have an idea that when a customer buys this product, it shows the error "This product is currently out of stock and unavailable." straight afterwards, but I haven't checked this yet, it's a clue.

2. It seems to appear more in a product range that has two attributes than in the range that only has one attribute of variations, which has only happened once to date.

### WordPress Environment

`### WordPress Environment ###

WordPress address (URL): https://floresnocais.pt
Site address (URL): https://floresnocais.pt
WC Version: 9.2.1
Legacy REST API Package Version: The Legacy REST API plugin is not installed on this site.
Action Scheduler Version: ✔ 3.8.1
Log Directory Writable: ✔
WP Version: 6.6.1
WP Multisite: –
WP Memory Limit: 4 GB
WP Debug Mode: –
WP Cron: –
Language: pt_PT
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.59 (Debian)
PHP Version: 7.4.33
PHP Post Max Size: 428 MB
PHP Time Limit: 899
PHP Max Input Vars: 5000
cURL Version: 7.64.0
OpenSSL/1.1.1n

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.4.34-MariaDB-1:10.4.34+maria~deb10-log
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 9.2.1
WC Database Prefix: wpet_
Tamanho total da base de dados: 3290.66MB
Tamanho dos dados da base de dados: 1350.84MB
Tamanho do índice da base de dados: 1939.82MB
wpet_woocommerce_sessions: Dados: 1.02MB + Índice: 0.02MB + Engine InnoDB
wpet_woocommerce_api_keys: Dados: 0.02MB + Índice: 0.03MB + Engine InnoDB
wpet_woocommerce_attribute_taxonomies: Dados: 0.02MB + Índice: 0.02MB + Engine InnoDB
wpet_woocommerce_downloadable_product_permissions: Dados: 0.02MB + Índice: 0.06MB + Engine InnoDB
wpet_woocommerce_order_items: Dados: 13.52MB + Índice: 5.52MB + Engine InnoDB
wpet_woocommerce_order_itemmeta: Dados: 188.69MB + Índice: 79.20MB + Engine InnoDB
wpet_woocommerce_tax_rates: Dados: 0.02MB + Índice: 0.06MB + Engine InnoDB
wpet_woocommerce_tax_rate_locations: Dados: 0.02MB + Índice: 0.05MB + Engine InnoDB
wpet_woocommerce_shipping_zones: Dados: 0.02MB + Índice: 0.00MB + Engine InnoDB
wpet_woocommerce_shipping_zone_locations: Dados: 0.11MB + Índice: 0.27MB + Engine InnoDB
wpet_woocommerce_shipping_zone_methods: Dados: 0.02MB + Índice: 0.00MB + Engine InnoDB
wpet_woocommerce_payment_tokens: Dados: 0.19MB + Índice: 0.08MB + Engine InnoDB
wpet_woocommerce_payment_tokenmeta: Dados: 0.45MB + Índice: 0.45MB + Engine InnoDB
wpet_woocommerce_log: Dados: 0.02MB + Índice: 0.02MB + Engine InnoDB
wpet_actionscheduler_actions: Dados: 81.11MB + Índice: 73.34MB + Engine InnoDB
wpet_actionscheduler_claims: Dados: 0.02MB + Índice: 0.02MB + Engine InnoDB
wpet_actionscheduler_groups: Dados: 0.02MB + Índice: 0.02MB + Engine InnoDB
wpet_actionscheduler_logs: Dados: 58.09MB + Índice: 36.09MB + Engine InnoDB
wpet_automatewoo_abandoned_carts: Dados: 2.06MB + Índice: 0.23MB + Engine InnoDB
wpet_automatewoo_customers: Dados: 4.52MB + Índice: 12.08MB + Engine InnoDB
wpet_automatewoo_customer_meta: Dados: 0.41MB + Índice: 0.52MB + Engine InnoDB
wpet_automatewoo_guests: Dados: 0.08MB + Índice: 0.09MB + Engine InnoDB
wpet_automatewoo_guest_meta: Dados: 0.02MB + Índice: 0.03MB + Engine InnoDB
wpet_automatewoo_logs: Dados: 3.52MB + Índice: 4.55MB + Engine InnoDB
wpet_automatewoo_log_meta: Dados: 14.52MB + Índice: 11.03MB + Engine InnoDB
wpet_automatewoo_queue: Dados: 0.02MB + Índice: 0.05MB + Engine InnoDB
wpet_automatewoo_queue_meta: Dados: 0.02MB + Índice: 0.03MB + Engine InnoDB
wpet_automatewoo_referrals: Dados: 0.02MB + Índice: 0.08MB + Engine InnoDB
wpet_automatewoo_referral_advocate_keys: Dados: 0.02MB + Índice: 0.02MB + Engine InnoDB
wpet_automatewoo_referral_invites: Dados: 0.02MB + Índice: 0.05MB + Engine InnoDB
wpet_bv_ip_store: Dados: 0.25MB + Índice: 0.17MB + Engine InnoDB
wpet_cart_notices: Dados: 0.02MB + Índice: 0.00MB + Engine InnoDB
wpet_chaty_contact_form_leads: Dados: 0.02MB + Índice: 0.00MB + Engine InnoDB
wpet_chaty_widget_analysis: Dados: 0.17MB + Índice: 0.00MB + Engine InnoDB
wpet_commentmeta: Dados: 1.41MB + Índice: 1.33MB + Engine InnoDB
wpet_comments: Dados: 98.69MB + Índice: 101.38MB + Engine InnoDB
wpet_e_events: Dados: 0.02MB + Índice: 0.02MB + Engine InnoDB
wpet_e_submissions: Dados: 0.03MB + Índice: 0.27MB + Engine InnoDB
wpet_e_submissions_actions_log: Dados: 0.02MB + Índice: 0.11MB + Engine InnoDB
wpet_e_submissions_values: Dados: 0.02MB + Índice: 0.03MB + Engine InnoDB
wpet_followup_coupons: Dados: 0.02MB + Índice: 0.03MB + Engine InnoDB
wpet_followup_coupon_logs: Dados: 0.02MB + Índice: 0.05MB + Engine InnoDB
wpet_followup_customers: Dados: 0.08MB + Índice: 0.09MB + Engine InnoDB
wpet_followup_customer_carts: Dados: 0.02MB + Índice: 0.03MB + Engine InnoDB
wpet_followup_customer_notes: Dados: 0.02MB + Índice: 0.03MB + Engine InnoDB
wpet_followup_customer_orders: Dados: 0.06MB + Índice: 0.02MB + Engine InnoDB
wpet_followup_email_excludes: Dados: 0.02MB + Índice: 0.05MB + Engine InnoDB
wpet_followup_email_logs: Dados: 0.02MB + Índice: 0.05MB + Engine InnoDB
wpet_followup_email_orders: Dados: 0.02MB + Índice: 0.09MB + Engine InnoDB
wpet_followup_email_tracking: Dados: 0.02MB + Índice: 0.08MB + Engine InnoDB
wpet_followup_followup_history: Dados: 0.02MB + Índice: 0.05MB + Engine InnoDB
wpet_followup_order_categories: Dados: 0.06MB + Índice: 0.03MB + Engine InnoDB
wpet_followup_order_items: Dados: 0.06MB + Índice: 0.05MB + Engine InnoDB
wpet_followup_subscribers: Dados: 0.02MB + Índice: 0.03MB + Engine InnoDB
wpet_followup_subscribers_to_lists: Dados: 0.02MB + Índice: 0.03MB + Engine InnoDB
wpet_followup_subscriber_lists: Dados: 0.02MB + Índice: 0.03MB + Engine InnoDB
wpet_gens_raf: Dados: 0.08MB + Índice: 0.00MB + Engine InnoDB
wpet_gens_rafmeta: Dados: 0.30MB + Índice: 0.27MB + Engine InnoDB
wpet_icl_background_task: Dados: 0.02MB + Índice: 0.00MB + Engine InnoDB
wpet_icl_content_status: Dados: 0.02MB + Índice: 0.02MB + Engine InnoDB
wpet_icl_core_status: Dados: 0.02MB + Índice: 0.02MB + Engine InnoDB
wpet_icl_flags: Dados: 0.02MB + Índice: 0.02MB + Engine InnoDB
wpet_icl_languages: Dados: 0.02MB + Índice: 0.03MB + Engine InnoDB
wpet_icl_languages_translations: Dados: 0.20MB + Índice: 0.17MB + Engine InnoDB
wpet_icl_locale_map: Dados: 0.02MB + Índice: 0.00MB + Engine InnoDB
wpet_icl_message_status: Dados: 0.02MB + Índice: 0.03MB + Engine InnoDB
wpet_icl_mo_files_domains: Dados: 0.13MB + Índice: 0.05MB + Engine InnoDB
wpet_icl_node: Dados: 0.02MB + Índice: 0.00MB + Engine InnoDB
wpet_icl_reminders: Dados: 0.02MB + Índice: 0.00MB + Engine InnoDB
wpet_icl_strings: Dados: 6.52MB + Índice: 7.03MB + Engine InnoDB
wpet_icl_string_batches: Dados: 0.02MB + Índice: 0.00MB + Engine InnoDB
wpet_icl_string_packages: Dados: 0.08MB + Índice: 0.00MB + Engine InnoDB
wpet_icl_string_pages: Dados: 0.02MB + Índice: 0.03MB + Engine InnoDB
wpet_icl_string_positions: Dados: 1.52MB + Índice: 0.25MB + Engine InnoDB
wpet_icl_string_status: Dados: 0.02MB + Índice: 0.02MB + Engine InnoDB
wpet_icl_string_translations: Dados: 3.52MB + Índice: 1.89MB + Engine InnoDB
wpet_icl_string_urls: Dados: 0.02MB + Índice: 0.02MB + Engine InnoDB
wpet_icl_translate: Dados: 1.52MB + Índice: 0.06MB + Engine InnoDB
wpet_icl_translate_job: Dados: 0.02MB + Índice: 0.02MB + Engine InnoDB
wpet_icl_translations: Dados: 4.52MB + Índice: 10.06MB + Engine InnoDB
wpet_icl_translation_batches: Dados: 0.02MB + Índice: 0.00MB + Engine InnoDB
wpet_icl_translation_downloads: Dados: 0.02MB + Índice: 0.00MB + Engine InnoDB
wpet_icl_translation_status: Dados: 1.52MB + Índice: 0.02MB + Engine InnoDB
wpet_jet_fb_reset_passwords: Dados: 0.02MB + Índice: 0.02MB + Engine InnoDB
wpet_jet_post_types: Dados: 0.02MB + Índice: 0.00MB + Engine InnoDB
wpet_jet_smart_filters_indexer: Dados: 0.06MB + Índice: 0.00MB + Engine InnoDB
wpet_jet_taxonomies: Dados: 0.02MB + Índice: 0.00MB + Engine InnoDB
wpet_links: Dados: 0.02MB + Índice: 0.02MB + Engine InnoDB
wpet_mailchimp_carts: Dados: 0.17MB + Índice: 0.00MB + Engine InnoDB
wpet_mailchimp_jobs: Dados: 8.02MB + Índice: 0.00MB + Engine InnoDB
wpet_mrw_cities: Dados: 0.02MB + Índice: 0.00MB + Engine InnoDB
wpet_mrw_orders: Dados: 34.56MB + Índice: 0.00MB + Engine InnoDB
wpet_mrw_ranges: Dados: 0.02MB + Índice: 0.00MB + Engine InnoDB
wpet_mrw_taxes: Dados: 0.02MB + Índice: 0.00MB + Engine InnoDB
wpet_options: Dados: 17.17MB + Índice: 6.84MB + Engine InnoDB
wpet_portuguese_postcodes: Dados: 23.55MB + Índice: 0.00MB + Engine InnoDB
wpet_postmeta: Dados: 464.75MB + Índice: 1047.09MB + Engine InnoDB
wpet_posts: Dados: 28.36MB + Índice: 13.95MB + Engine InnoDB
wpet_revslider_css: Dados: 0.13MB + Índice: 0.02MB + Engine InnoDB
wpet_revslider_css_bkp: Dados: 0.13MB + Índice: 0.00MB + Engine InnoDB
wpet_revslider_layer_animations: Dados: 0.02MB + Índice: 0.00MB + Engine InnoDB
wpet_revslider_layer_animations_bkp: Dados: 0.02MB + Índice: 0.00MB + Engine InnoDB
wpet_revslider_navigations: Dados: 0.02MB + Índice: 0.00MB + Engine InnoDB
wpet_revslider_navigations_bkp: Dados: 0.02MB + Índice: 0.00MB + Engine InnoDB
wpet_revslider_sliders: Dados: 0.06MB + Índice: 0.02MB + Engine InnoDB
wpet_revslider_sliders7: Dados: 0.02MB + Índice: 0.02MB + Engine InnoDB
wpet_revslider_sliders_bkp: Dados: 0.06MB + Índice: 0.00MB + Engine InnoDB
wpet_revslider_slides: Dados: 1.52MB + Índice: 0.02MB + Engine InnoDB
wpet_revslider_slides7: Dados: 0.42MB + Índice: 0.02MB + Engine InnoDB
wpet_revslider_slides_bkp: Dados: 0.16MB + Índice: 0.00MB + Engine InnoDB
wpet_revslider_static_slides: Dados: 0.02MB + Índice: 0.02MB + Engine InnoDB
wpet_revslider_static_slides_bkp: Dados: 0.08MB + Índice: 0.00MB + Engine InnoDB
wpet_termmeta: Dados: 0.20MB + Índice: 0.44MB + Engine InnoDB
wpet_terms: Dados: 0.02MB + Índice: 0.03MB + Engine InnoDB
wpet_term_relationships: Dados: 0.22MB + Índice: 0.17MB + Engine InnoDB
wpet_term_taxonomy: Dados: 0.05MB + Índice: 0.03MB + Engine InnoDB
wpet_usermeta: Dados: 213.83MB + Índice: 477.67MB + Engine InnoDB
wpet_users: Dados: 10.52MB + Índice: 14.84MB + Engine InnoDB
wpet_wcs_payment_retries: Dados: 0.16MB + Índice: 0.02MB + Engine InnoDB
wpet_wc_admin_notes: Dados: 0.02MB + Índice: 0.00MB + Engine InnoDB
wpet_wc_admin_note_actions: Dados: 0.02MB + Índice: 0.02MB + Engine InnoDB
wpet_wc_category_lookup: Dados: 0.02MB + Índice: 0.00MB + Engine InnoDB
wpet_wc_customer_lookup: Dados: 6.52MB + Índice: 6.02MB + Engine InnoDB
wpet_wc_download_log: Dados: 0.02MB + Índice: 0.03MB + Engine InnoDB
wpet_wc_gpf_render_cache: Dados: 0.02MB + Índice: 0.02MB + Engine InnoDB
wpet_wc_ie_scheduled_docs: Dados: 0.02MB + Índice: 0.00MB + Engine InnoDB
wpet_wc_orders: Dados: 0.02MB + Índice: 0.11MB + Engine InnoDB
wpet_wc_orders_meta: Dados: 0.02MB + Índice: 0.03MB + Engine InnoDB
wpet_wc_order_addresses: Dados: 0.02MB + Índice: 0.06MB + Engine InnoDB
wpet_wc_order_coupon_lookup: Dados: 0.28MB + Índice: 0.41MB + Engine InnoDB
wpet_wc_order_operational_data: Dados: 0.02MB + Índice: 0.03MB + Engine InnoDB
wpet_wc_order_product_lookup: Dados: 7.52MB + Índice: 9.05MB + Engine InnoDB
wpet_wc_order_stats: Dados: 6.52MB + Índice: 6.53MB + Engine InnoDB
wpet_wc_order_tax_lookup: Dados: 4.52MB + Índice: 3.03MB + Engine InnoDB
wpet_wc_product_attributes_lookup: Dados: 0.06MB + Índice: 0.06MB + Engine InnoDB
wpet_wc_product_download_directories: Dados: 0.02MB + Índice: 0.02MB + Engine InnoDB
wpet_wc_product_meta_lookup: Dados: 0.16MB + Índice: 0.38MB + Engine InnoDB
wpet_wc_rate_limits: Dados: 0.02MB + Índice: 0.02MB + Engine InnoDB
wpet_wc_reserved_stock: Dados: 0.02MB + Índice: 0.00MB + Engine InnoDB
wpet_wc_tax_rate_classes: Dados: 0.02MB + Índice: 0.02MB + Engine InnoDB
wpet_wc_webhooks: Dados: 0.02MB + Índice: 0.02MB + Engine InnoDB
wpet_wc_zapier_history: Dados: 0.02MB + Índice: 0.00MB + Engine InnoDB
wpet_wfsecurityevents: Dados: 0.02MB + Índice: 0.00MB + Engine InnoDB
wpet_wfwaffailures: Dados: 0.02MB + Índice: 0.00MB + Engine InnoDB
wpet_woocommerce_bis_activity: Dados: 0.05MB + Índice: 0.05MB + Engine InnoDB
wpet_woocommerce_bis_notifications: Dados: 0.02MB + Índice: 0.09MB + Engine InnoDB
wpet_woocommerce_bis_notificationsmeta: Dados: 0.05MB + Índice: 0.03MB + Engine InnoDB
wpet_woocommerce_bundled_itemmeta: Dados: 0.02MB + Índice: 0.03MB + Engine InnoDB
wpet_woocommerce_bundled_items: Dados: 0.02MB + Índice: 0.03MB + Engine InnoDB
wpet_woocommerce_gc_activity: Dados: 0.02MB + Índice: 0.06MB + Engine InnoDB
wpet_woocommerce_gc_cards: Dados: 0.02MB + Índice: 0.06MB + Engine InnoDB
wpet_woocommerce_gc_cardsmeta: Dados: 0.02MB + Índice: 0.03MB + Engine InnoDB
wpet_woocommerce_gpf_google_taxonomy: Dados: 3.02MB + Índice: 0.23MB + Engine InnoDB
wpet_woocommerce_prl_deploymentmeta: Dados: 0.02MB + Índice: 0.03MB + Engine InnoDB
wpet_woocommerce_prl_deployments: Dados: 0.02MB + Índice: 0.06MB + Engine InnoDB
wpet_woocommerce_prl_frequencies: Dados: 0.02MB + Índice: 0.02MB + Engine InnoDB
wpet_woocommerce_prl_tracking_conversions: Dados: 0.02MB + Índice: 0.05MB + Engine InnoDB
wpet_wpfm_backup: Dados: 0.02MB + Índice: 0.00MB + Engine InnoDB
wpet_wpmailsmtp_emails_log: Dados: 0.20MB + Índice: 0.03MB + Engine InnoDB
wpet_wpr_above_the_fold: Dados: 3.02MB + Índice: 0.13MB + Engine InnoDB
wpet_wpr_rocket_cache: Dados: 0.14MB + Índice: 0.14MB + Engine InnoDB
wpet_wpr_rucss_used_css: Dados: 3.02MB + Índice: 1.39MB + Engine InnoDB
wpet_wpstg_queue: Dados: 15.52MB + Índice: 0.00MB + Engine InnoDB
wpet_wrd_discounts: Dados: 0.02MB + Índice: 0.02MB + Engine InnoDB
wpet_wrd_sent_coupons: Dados: 0.02MB + Índice: 0.05MB + Engine InnoDB
wpet_yith_wapo_addons: Dados: 0.28MB + Índice: 0.00MB + Engine InnoDB
wpet_yith_wapo_blocks: Dados: 0.02MB + Índice: 0.00MB + Engine InnoDB
wpet_yith_wapo_blocks_assoc: Dados: 0.02MB + Índice: 0.03MB + Engine InnoDB
wpet_yith_wapo_groups: Dados: 0.02MB + Índice: 0.00MB + Engine InnoDB
wpet_yith_wapo_types: Dados: 0.17MB + Índice: 0.00MB + Engine InnoDB
wpet_yith_wccl_meta: Dados: 0.02MB + Índice: 0.00MB + Engine InnoDB
wpet_yith_wcwl: Dados: 0.02MB + Índice: 0.02MB + Engine InnoDB
wpet_yith_wcwl_lists: Dados: 0.02MB + Índice: 0.03MB + Engine InnoDB
wpet_yith_wc_stripe_blacklist: Dados: 0.02MB + Índice: 0.05MB + Engine InnoDB
wpet_yith_ywrac_email_log: Dados: 0.02MB + Índice: 0.00MB + Engine InnoDB
wpet_yith_ywsbs_activities_log: Dados: 0.02MB + Índice: 0.00MB + Engine InnoDB
wpet_yoast_indexable: Dados: 0.50MB + Índice: 0.22MB + Engine InnoDB
wpet_yoast_indexable_hierarchy: Dados: 0.05MB + Índice: 0.05MB + Engine InnoDB
wpet_yoast_migrations: Dados: 0.02MB + Índice: 0.02MB + Engine InnoDB
wpet_yoast_primary_term: Dados: 0.05MB + Índice: 0.03MB + Engine InnoDB
wpet_yoast_prominent_words: Dados: 0.11MB + Índice: 0.22MB + Engine InnoDB
wpet_yoast_seo_links: Dados: 2.47MB + Índice: 0.73MB + Engine InnoDB
wpet_yoast_seo_meta: Dados: 0.42MB + Índice: 0.00MB + Engine InnoDB
wpet_ywcars_messagemeta: Dados: 0.02MB + Índice: 0.00MB + Engine InnoDB
wpet_ywcars_messages: Dados: 0.02MB + Índice: 0.00MB + Engine InnoDB
wpet_ywcdd_calendar: Dados: 0.08MB + Índice: 0.00MB + Engine InnoDB
wp_bv_fw_requests: Dados: 0.02MB + Índice: 0.00MB + Engine InnoDB
wp_bv_ip_store: Dados: 0.38MB + Índice: 0.28MB + Engine InnoDB
wp_bv_lp_requests: Dados: 0.02MB + Índice: 0.00MB + Engine InnoDB
wp_commentmeta: Dados: 0.02MB + Índice: 0.03MB + Engine InnoDB
wp_comments: Dados: 0.02MB + Índice: 0.08MB + Engine InnoDB
wp_links: Dados: 0.02MB + Índice: 0.02MB + Engine InnoDB
wp_options: Dados: 0.16MB + Índice: 0.03MB + Engine InnoDB
wp_postmeta: Dados: 0.02MB + Índice: 0.03MB + Engine InnoDB
wp_posts: Dados: 0.02MB + Índice: 0.06MB + Engine InnoDB
wp_termmeta: Dados: 0.02MB + Índice: 0.03MB + Engine InnoDB
wp_terms: Dados: 0.02MB + Índice: 0.03MB + Engine InnoDB
wp_term_relationships: Dados: 0.02MB + Índice: 0.02MB + Engine InnoDB
wp_term_taxonomy: Dados: 0.02MB + Índice: 0.03MB + Engine InnoDB
wp_usermeta: Dados: 0.02MB + Índice: 0.03MB + Engine InnoDB
wp_users: Dados: 0.02MB + Índice: 0.05MB + Engine InnoDB

### Post Type Counts ###

af_promo_bar: 1
amn_exact-metrics: 1
attachment: 1428
aw_workflow: 6
br_notice: 1
cms_block: 1
cookielawinfo: 12
custom_css: 6
ec_woo_ddb_template: 12
elementor_font: 2
elementor_icons: 2
elementor_library: 49
flamingo_contact: 70
flamingo_inbound: 49
global_product_addon: 11
ifso_triggers: 1
inspire_invoice: 3
jet-engine: 2
jet-form-builder: 2
jet-smart-filters: 4
jet-woo-builder: 7
job_listing: 1
kwlogos: 5
mc4wp-form: 2
nav_menu_item: 63
oembed_cache: 6
opanda-item: 1
page: 90
post: 40
prl_engine: 2
product: 257
product_variation: 672
shop_coupon: 114
shop_order: 54595
shop_order_refund: 529
shop_subscription: 233
testimonials: 7
user_request: 8
wapl: 1
wc_product_tab: 7
wmpc-trash: 93
woo_mb_template: 10
wp_navigation: 1
wpforms: 1
yith_carrier: 1
yith_proc_method: 1
yith_wcpmr_rule: 3
yith-wcet-etemplate: 1
yith-wcgpf-feed: 3
yith-wcgpf-template: 1
ywar_reviews: 78
ywdpd_discount: 2
ywsbs_subscription: 4
ywtm_tab: 3

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (48) ###

Admin Menu Editor Pro: por Janis Elsts – 2.26.1
AutomateWoo: por WooCommerce – 6.0.32
Chaty Pro: por Premio – 3.2.9
Yoast Duplicate Post: por Enrico Battocchi e Team Yoast – 4.5
GTM4WP - A Google Tag Manager (GTM) plugin for WordPress: por Thomas Geiger – 1.20.2
Elementor Pro: por Elementor.com – 3.23.3
Elementor: por Elementor.com – 3.23.4
Facebook for WooCommerce: por Facebook – 3.2.7
JetElements For Elementor: por Crocoblock – 2.6.20.1
JetEngine: por Crocoblock – 3.5.4
JetFormBuilder User Login Action: por Crocoblock – 2.0.5
JetSmartFilters: por Crocoblock – 3.5.4
JetTabs For Elementor: por Crocoblock – 2.2.3.1
JetWooBuilder For Elementor: por Crocoblock – 2.1.13
JetProductGallery: por Crocoblock – 2.1.18
JetFormBuilder: por Crocoblock – 3.4.0
JetWooBuilder - Products Grid Load More: por Crocoblock – 1.2.0
Mailchimp for WooCommerce: por Mailchimp – 4.2.1
Multibanco, MB WAY, Cartão de crédito, Payshop e Cofidis Pay (IfthenPay) para WooCommerce: por PT Woo Plugins (by Webdados) – 9.4.4
Order Delivery Date Pro for WooCommerce: por Tyche Softwares – 11.0.0
Portuguese Postcodes for WooCommerce: por PT Woo Plugins (by Webdados) – 5.6
WooCommerce Subscriptions Compatibility Addon: por Tyche Softwares – 1.5.0
Stock Dependencies for WooCommerce: por Kevin McCall – 1.6.2
Converter for Media: por matt plugins - Optimize images by convert WebP & AVIF – 5.13.1
Weglot Translate: por Equipa do Weglot Translate – 4.2.8
Invoicing with InvoiceXpress for WooCommerce - Pro: por PT Woo Plugins (by Webdados) – 5.8
Woo Reviews for Google: por ICREATOR – 1.0
Variation Swatches for WooCommerce - Pro: por Emran Ahmed – 2.1.3
Variation Swatches for WooCommerce: por Emran Ahmed – 2.1.1
Woo Conditional Shipping and Payments: por Woo – 2.0.2
WooCommerce Email Customizer: por cxThemes – 3.33
Plataforma do Stripe para o WooCommerce: por WooCommerce – 8.6.1
MRW: por Webubi – 4.3.1
WooCommerce Google Product Feed: por Ademti Software Ltd. – 11.0.12
WooCommerce Sequential Order Numbers Pro: por SkyVerge – 1.21.3
WooCommerce Shipment Tracking: por WooCommerce – 2.5.0
WooCommerce Smart Coupons: por StoreApps – 9.7.0
WooCommerce Subscriptions: por WooCommerce – 6.5.0
WooCommerce Waitlist: por Neil Pie – 2.4.13
WooCommerce: por Automattic – 9.2.1
Yoast SEO Premium: por Team Yoast – 23.3
Yoast SEO: por Team Yoast – 23.3
WP Mail SMTP Pro: por WP Mail SMTP – 4.1.1
WP Rocket: por WP Media – 3.16.4
Refer a Friend for WooCommerce PREMIUM: por WPGens – 4.1.4
YITH WooCommerce Product Add-ons & Extra Options Premium: por YITH – 4.16.0
YITH WooCommerce Bulk Product Editing Premium: por YITH – 3.9.0

### Dropin Plugins () ###

advanced-cache.php: advanced-cache.php
maintenance.php: maintenance.php

### Must Use Plugins (1) ###

WP STAGING Optimizer: por WP STAGING – 1.5.6

### Settings ###

Legacy API Enabled: ✔
Force SSL: ✔
Currency: EUR (€)
Currency Position: right
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: bundle (bundle)
composite (composite)
external (external)
gift-card (gift-card)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)
variation (variation)
yith-composite (yith-composite)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 dias
Level threshold: –
Log directory size: 89 MB

### WC Pages ###

Página da Loja: #577 - /loja/
Carrinho: #3496 - /cesto/ -  Contains the [woocommerce_cart] shortcode
Finalizar compras: #3498 - /checkout/ -  Contains the [woocommerce_checkout] shortcode
A minha conta: ❌ A página não contém o shortcode [woocommerce_my_account].
Termos e condições: #1463 - /termos-e-condicoes/

### Theme ###

Name: Hello Elementor Child
Version: 2.0.0
Author URL: https://elementor.com/
Child Theme: ✔
Parent Theme Name: Hello Elementor
Parent Theme Version: 3.1.1
Parent Theme Author URL: https://elementor.com/?utm_source=wp-themes&utm_campaign=author-uri&utm_medium=wp-dash
WooCommerce Support: ✔

### Templates ###

Overrides: /home/1090615.cloudwaysapps.com/amqzkxvawh/public_html/wp-content/plugins/jet-woo-builder/templates/woocommerce/cart/cart-empty.php
/home/1090615.cloudwaysapps.com/amqzkxvawh/public_html/wp-content/plugins/jet-woo-builder/templates/woocommerce/cart/cart.php
/home/1090615.cloudwaysapps.com/amqzkxvawh/public_html/wp-content/plugins/jet-woo-builder/templates/woocommerce/checkout/form-checkout.php
/home/1090615.cloudwaysapps.com/amqzkxvawh/public_html/wp-content/plugins/jet-woo-builder/templates/woocommerce/checkout/thankyou.php
/home/1090615.cloudwaysapps.com/amqzkxvawh/public_html/wp-content/plugins/woocommerce-email-control/templates/emails/deluxe/admin-cancelled-order.php versão 3.7.0 está desactualizado. A versão actual é 4.1.0
/home/1090615.cloudwaysapps.com/amqzkxvawh/public_html/wp-content/plugins/woocommerce-email-control/templates/emails/deluxe/admin-failed-order.php
/home/1090615.cloudwaysapps.com/amqzkxvawh/public_html/wp-content/plugins/woocommerce-email-control/templates/emails/deluxe/admin-new-order.php
/home/1090615.cloudwaysapps.com/amqzkxvawh/public_html/wp-content/plugins/woocommerce-email-control/templates/emails/deluxe/customer-completed-order.php
/home/1090615.cloudwaysapps.com/amqzkxvawh/public_html/wp-content/plugins/woocommerce-email-control/templates/emails/deluxe/customer-invoice.php
/home/1090615.cloudwaysapps.com/amqzkxvawh/public_html/wp-content/plugins/woocommerce-email-control/templates/emails/deluxe/customer-new-account.php versão 3.7.0 está desactualizado. A versão actual é 6.0.0
/home/1090615.cloudwaysapps.com/amqzkxvawh/public_html/wp-content/plugins/woocommerce-email-control/templates/emails/deluxe/customer-note.php
/home/1090615.cloudwaysapps.com/amqzkxvawh/public_html/wp-content/plugins/woocommerce-email-control/templates/emails/deluxe/customer-on-hold-order.php versão 3.7.0 está desactualizado. A versão actual é 7.3.0
/home/1090615.cloudwaysapps.com/amqzkxvawh/public_html/wp-content/plugins/woocommerce-email-control/templates/emails/deluxe/customer-processing-order.php
/home/1090615.cloudwaysapps.com/amqzkxvawh/public_html/wp-content/plugins/woocommerce-email-control/templates/emails/deluxe/customer-refunded-order.php
/home/1090615.cloudwaysapps.com/amqzkxvawh/public_html/wp-content/plugins/woocommerce-email-control/templates/emails/deluxe/customer-reset-password.php versão 3.7.0 está desactualizado. A versão actual é 4.0.0
/home/1090615.cloudwaysapps.com/amqzkxvawh/public_html/wp-content/plugins/woocommerce-email-control/templates/emails/deluxe/email-addresses.php versão 3.5.4 está desactualizado. A versão actual é 8.6.0
/home/1090615.cloudwaysapps.com/amqzkxvawh/public_html/wp-content/plugins/woocommerce-email-control/templates/emails/deluxe/email-customer-details.php
/home/1090615.cloudwaysapps.com/amqzkxvawh/public_html/wp-content/plugins/woocommerce-email-control/templates/emails/deluxe/email-downloads.php
/home/1090615.cloudwaysapps.com/amqzkxvawh/public_html/wp-content/plugins/woocommerce-email-control/templates/emails/deluxe/email-footer.php versão 3.7.0 está desactualizado. A versão actual é 7.4.0
/home/1090615.cloudwaysapps.com/amqzkxvawh/public_html/wp-content/plugins/woocommerce-email-control/templates/emails/deluxe/email-header.php versão 2.4.0 está desactualizado. A versão actual é 7.4.0
/home/1090615.cloudwaysapps.com/amqzkxvawh/public_html/wp-content/plugins/woocommerce-email-control/templates/emails/deluxe/email-order-details.php
/home/1090615.cloudwaysapps.com/amqzkxvawh/public_html/wp-content/plugins/woocommerce-email-control/templates/emails/deluxe/email-order-items.php
/home/1090615.cloudwaysapps.com/amqzkxvawh/public_html/wp-content/plugins/woocommerce-email-control/templates/emails/deluxe/email-styles.php versão 3.3.0 está desactualizado. A versão actual é 8.6.0

Outdated Templates: ❌
					
					
						Saiba como actualizar

### Assinaturas ###

WCS_DEBUG: ✔ Não
Subscriptions Mode: ✔ Ativo
Subscriptions Live URL: https://floresnocais.pt
Subscriptions-core Library Version: 7.3.0
Subscription Statuses: wc-active: 42
wc-expired: 1
wc-pending-cancel: 4
wc-pending: 1
wc-on-hold: 36
wc-cancelled: 149

WooCommerce Account Connected: ✔ Yes
Active Product Key: ✔ Yes
Custom Retry Rules: ✔ No
Custom Retry Rule Class: ✔ No
Custom Raw Retry Rule: ✔ No
Custom Retry Rule: ✔ No
Retries Migration Status: ✔ Completed
Report Cache Enabled: ✔ Sim
Cache Update Failures: ✔ 0 tentativa de pagamento falhadas

### Configuração da loja ###

Country / State: Portugal — Setúbal

### Assinaturas pelo Gateway de Pagamento ###

PayPal Standard: wc-active: 9
wc-cancelled: 43
wc-on-hold: 2

Stripe: wc-active: 32
wc-cancelled: 106
wc-expired: 1
wc-on-hold: 32
wc-pending-cancel: 4

### Suporte do Gateway de pagamento ###

Pagamento de Serviços no Multibanco (IfthenPay): products
Pagamento MB WAY no telemóvel (IfthenPay): products
Stripe: products
refunds
tokenization
add_payment_method
subscriptions
subscription_cancellation
subscription_suspension
subscription_reactivation
subscription_amount_changes
subscription_date_changes
subscription_payment_method_change
subscription_payment_method_change_customer
subscription_payment_method_change_admin
multiple_subscriptions

PayPal Standard: subscription_payment_method_change_customer
subscription_payment_method_change_admin
subscription_amount_changes
subscription_date_changes
multiple_subscriptions
subscription_payment_method_delayed_change
subscriptions
subscription_cancellation
subscription_suspension
subscription_reactivation
products
refunds

PayPal Reference Transactions Enabled: ✔ Yes

### WooCommerce Google Product Feed feeds ###

google: Google merchant centre product feed
  Type: google
  Category filter: -
  Categories: -
googlereview: Google merchant centre product review feed
  Type: googlereview
  Category filter: -
  Categories: -

### WooCommerce Google Product Feed options ###

Include variations in feed: -
Send "item group ID": -
Expanded schema markup: -
Debug key: 4f995a8b-8f84-40e9-98be-68a21c559373

### WooCommerce Google Product Feed fields ###

Availability (backordered products): Defaults to "out of stock".
Availability (in stock products): Defaults to "in stock".
Availability (out of stock products): Defaults to "out of stock".
Condition: Defaults to "new".
Product description: Main product description only (short preferred)
Google Product Category: Defaults to "Arts & Entertainment > Party & Celebration > Gift Giving > Fresh Cut Flowers".
Manufacturer Part Number (MPN): 
Brand: Defaults to "Flores no Cais".
Size: Pre-populates from pa_tamanho taxonomy.
Product Type: 
Title: Pre-populates from product product_title.
Adult content: Defaults to "no".
Bundle indicator (is_bundle): 
Ships from country: Defaults to "PT".

### WooCommerce Google Product Feed DB status ###

Database version: 17
Active database version: 17
wc_gpf_render_cache: Empty
woocommerce_gpf_google_taxonomy (en-US): 5595 items
woocommerce_gpf_google_taxonomy (pt-BR): 5595 items

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
pattern-toolkit-full-composability
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
printful
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page
launch-your-store

Disabled Features: experimental-blocks
minified-js
product-pre-publish-modal
settings
async-product-editor-category-field
product-editor-template-system

Daily Cron: ✔ Next scheduled: 2024-08-22 12:03:28 +01:00
Options: ✔
Notes: 21
Onboarding: completed

### Action Scheduler ###

Canceled: 10
Oldest: 2024-08-19 18:54:09 +0100
Newest: 2024-08-21 20:20:56 +0100

Complete: 187.261
Oldest: 2024-07-21 22:34:14 +0100
Newest: 2024-08-21 22:33:42 +0100

Failed: 39
Oldest: 2024-08-17 08:47:38 +0100
Newest: 2024-08-20 15:23:37 +0100

Pending: 80
Oldest: 2024-08-21 22:34:36 +0100
Newest: 2025-04-19 03:21:14 +0100

### Status report information ###

Generated at: 2024-08-21 22:34:47 +01:00`

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by tjcafferkey**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

For a summary of the bug this fixes please see here https://github.com/woocommerce/woocommerce/issues/50855#issuecomment-2531651353

We are validating variable product transient data before using it. This is because there is an ongoing and widespread issue whereby corrupted transient data is being used, this results in products being displayed as out of stock on the frontend until the user updates the product to refresh the transient data.

We don't know what or how this data is being corrupted yet, but in the meantime this PR adds validation so we can avoid using it unless we are certain its valid.

In this PR I add validation to both `wc_product_children_` and `wc_var_prices_` transient data to check their validity.

`validate_children_data`:
* Data is an array
* Has required keys 'all' and 'visible'
* Both 'all' and 'visible' are arrays
* If version exists, matches current version
* All IDs in both arrays are numeric values

`validate_prices_data`
* Data is an array
* If version exists, matches current version
* Has required price type arrays: 'price', 'regular_price', 'sale_price'
* All price type entries are arrays
* Variation IDs are numeric
* Price values are either numeric or empty strings
* Each variation ID has entries for all price types

We have added a new `version` property to the transient so we check this exists before validating it to ensure backwards compat.

Closes https://github.com/woocommerce/woocommerce/issues/50855

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

Reproducing this issue reliably has proven difficult. As a result I think its best to do a full regression test of adding, viewing and purchasing variable products to ensure no regressions or errors occur. On top of that please:

1. Install Transient Manager plugin and do a search for a variable product prices `_transient_wc_var_prices_`
2. If you want to, you can add some `var_dump()` logs for valid/invalid to observe on the frontend near the top of `read_price_data` method
3. This should evaluate valid currently, now update the transient data with the below (invalid code).
4. Refresh the variable product page of the product who's transient you updated, it should evaluate as invalid but should also correctly display the price (because its updated the transient cache after detecting invalid data)
5. Refresh the page again, and it should evaluate as valid (because it was updated in step 4).
6. Do the same with `wc_product_children_` transient data and the `read_children` method.
7. Do some regression testing across classic & block themes archive/category pages and product pages.

```
{
  "version": "1725527855",
  "f9e544f77b7eac7add281ef28ca5559f": {
    "price": [],
    "regular_price": [],
    "sale_price": []
  },
  "f74c5567e2b347f8728ea07774b6f7e4": {
    "price": [],
    "regular_price": [],
    "sale_price": []
  }
}
```

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

**Comment by tjcafferkey** [comment]
cc'ing @ricardoaraujo330, @vmavrikios and @tobijafischer for visibility

File: plugins/woocommerce/includes/data-stores/class-wc-product-variable-data-store-cpt.php [hunk 1]
```diff
@@ -149,6 +159,7 @@ public function read_children( &$product, $force_read = false ) {
 			}
 			$children['all']     = get_posts( apply_filters( 'woocommerce_variable_children_args', $all_args, $product, false ) );
 			$children['visible'] = get_posts( apply_filters( 'woocommerce_variable_children_args', $visible_only_args, $product, true ) );
+			$children['version'] = WC_Cache_Helper::get_transient_version( 'product' );
```
Comment (Aljullu) [inline plugins/woocommerce/includes/data-stores/class-wc-product-variable-data-store-cpt.php]: Would this be equivalent to:

```suggestion
			$children['version'] = $transient_version;
```

File: plugins/woocommerce/includes/data-stores/class-wc-product-variable-data-store-cpt.php [hunk 2]
```diff
@@ -274,6 +285,13 @@ public function read_price_data( &$product, $for_display = false ) {
...
 
+			// If the prices are not valid, reset the transient cache.
+			if ( ! $this->validate_prices_data( $transient_cached_prices_array, $transient_version ) ) {
+				$transient_cached_prices_array = array(
+					'version' => $transient_version,
+				);
+			}
+
 			// If the product version has changed since the transient was last saved, reset the transient cache.
 			if ( ! isset( $transient_cached_prices_array['version'] ) || $transient_version !== $transient_cached_prices_array['version'] ) {
```
Comment (Aljullu) [inline plugins/woocommerce/includes/data-stores/class-wc-product-variable-data-store-cpt.php]: Are this check and the one in [L785](https://github.com/woocommerce/woocommerce/pull/53603/files#diff-c4ec3aeace51d4a1a8c8c49cc02b4046f9c650912cf7468426854d9595ac1755R785) checking the same? Wondering if we could get rid of one of them.

File: plugins/woocommerce/includes/data-stores/class-wc-product-variable-data-store-cpt.php [hunk 3]
```diff
@@ -710,4 +728,104 @@ public function untrash_variations( $product_id ) {
...
+				foreach ( $required_types as $type ) {
+					if ( ! array_key_exists( $variation_id, $price_data[ $type ] ) ) {
+						return false;
+					}
+
+					$type_price = $price_data[ $type ][ $variation_id ];
+					if ( ! is_numeric( $type_price ) && '' !== $type_price ) {
+						return false;
+					}
+				}
```
Comment (Aljullu) [inline plugins/woocommerce/includes/data-stores/class-wc-product-variable-data-store-cpt.php]: I might be misunderstanding this, but I think we are checking `price` twice. One inside the `if` (L812-814) and another one inside the `foreach` (L822-824). Could one of them be removed?

**Review by Aljullu — COMMENTED** [review]
Thanks for working on this, @tjcafferkey! Really nice to see progress on this issue. :raised_hands: 

The code looks good to me, I left some minor questions below, but nothing blocking. I did a round of smoke testing and everything was looking good on my end. I wasn't able to reproduce the original issue, though, so wondering if @kmanijak or somebody else should give the final approval?

File: plugins/woocommerce/includes/data-stores/class-wc-product-variable-data-store-cpt.php (hunk 1 above)
Comment (tjcafferkey) [reply plugins/woocommerce/includes/data-stores/class-wc-product-variable-data-store-cpt.php]: thanks! done in https://github.com/woocommerce/woocommerce/pull/53603/commits/7d9b4bb3f13faa2840167d32308fbb06e74854ef

File: plugins/woocommerce/includes/data-stores/class-wc-product-variable-data-store-cpt.php (hunk 2 above)
Comment (tjcafferkey) [reply plugins/woocommerce/includes/data-stores/class-wc-product-variable-data-store-cpt.php]: Your right, done in https://github.com/woocommerce/woocommerce/pull/53603/commits/cbfbc24d19bd546e8e894706974554869421f308

File: plugins/woocommerce/includes/data-stores/class-wc-product-variable-data-store-cpt.php (hunk 3 above)
Comment (tjcafferkey) [reply plugins/woocommerce/includes/data-stores/class-wc-product-variable-data-store-cpt.php]: Nope you were right, goot catch. Done in https://github.com/woocommerce/woocommerce/pull/53603/commits/c6c1801c0f9548b3367bd05e410c3254e01055fa

**Review by kmanijak — APPROVED** [review]
LGTM! I made multiple checks on multiple variable products and didn't spot any issues in transients (invalid ones get updated) as well as on the frontend (didn't find a variable product being out of stock incorrectly). Great work! 🚀
