### PR TITLE
Store API: Normalize cart items on load to ensure quantity limits are respected

### LINKED ISSUE #52109: Cart block doesn't apply the min/max restrictions very thoroughly
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

It's rather easy to checkout with more than the maximum allowed number of products via StoreAPI/cart/checkout blocks.

### Expected behavior

Not being able to check out with quantity exceeding the number from `woocommerce_store_api_product_quantity_maximum`.

### Actual behavior

Checkout goes through.

### Steps to reproduce

1. Add a filter for `woocommerce_store_api_product_quantity_maximum` to only allow quantity <= 2 for each product, e.g. as below:
```
add_filter( 'woocommerce_store_api_product_quantity_maximum', 'filter_max_cart_item_qty', 10, 3 );

function filter_max_cart_item_qty( $value, $product, $cart_item ){
	return 2;
}
```
2. Open page with **simple product P**, add 5 to cart.
3. Go to cart, observe the quantity is 5.
4. Proceed to Checkout
6. Checkout loads with 5 items in order summary
7. Click Place Order/Pay Now 
8. See that you just bought 5 items. 

The limit gets applied when e.g. the shipping changes, but not when the cart gets reloaded (using the browser refresh button).

### WordPress Environment

Use only WC core and Storefront, no payment gateways or other plugins, otherwise something triggers a reload quite often.

### Isolating the problem

- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by mikejolley**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Quantity limits can be set using filters. Minimum, maximum, multiple. This was respected on add to cart endpoints, but not general cart responses and checkout.

This PR adds a normalisation method to ensure cart item quantities fit within the limits. Because this is done on the API side, `notifyIfQuantityLimitsChanged` is not needed because the client will only see valid amounts.

This is an alternative to allowing invalid amounts and surfacing errors in the cart for manual resolution.

Closes #52109

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

Testers should check for regressions by going through the full add to cart, cart, checkout flow.

Developers can use snippets to test the normalization. 

1. Go to a single product page and add 6 of the same item to the cart.
2. Implement this snippet:

```php
add_filter( 'woocommerce_store_api_product_quantity_maximum', 'filter_max_cart_item_qty', 10, 3 );

function filter_max_cart_item_qty( $value, $product, $cart_item ) {
	return 2;
}
```

3. Visit the cart page
4. Item quantity will be reduced to 2

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

**Comment by mikejolley** [comment]
@opr this was the alternative solution. Quantities returned by the API will always be valid and I removed the notices you added as they won't be needed.

See any issues with this?

File: plugins/woocommerce/src/StoreApi/Utilities/QuantityLimits.php [hunk 1]
```diff
@@ -73,6 +75,38 @@ public function get_add_to_cart_limits( \WC_Product $product ) {
...
 
+	/**
+	 * Fix a quantity violation by adjusting it to the nearest valid quantity.
+	 *
+	 * @param int   $quantity The quantity to fix.
+	 * @param array $cart_item The cart item.
+	 * @return int
+	 */
+	public function normalize_cart_item_quantity( int $quantity, array $cart_item ) {
+		$product = $cart_item['data'];
```
Comment (opr) [inline plugins/woocommerce/src/StoreApi/Utilities/QuantityLimits.php]: Is it possible for `$cart_item['data']` not to be set? Should we check before accessing it?

File: plugins/woocommerce/src/StoreApi/Utilities/QuantityLimits.php [hunk 2]
```diff
@@ -92,51 +126,32 @@ public function limit_to_multiple( int $number, int $multiple_of, string $roundi
...
-	 * @param integer           $quantity Quantity to validate.
-	 * @param \WC_Product|array $cart_item Cart item.
+	 * @param integer $quantity Quantity to validate.
+	 * @param array   $cart_item Cart item.
 	 * @return \WP_Error|true
 	 */
 	public function validate_cart_item_quantity( $quantity, $cart_item ) {
-		$limits = $this->get_cart_item_quantity_limits( $cart_item );
+		$limits  = $this->get_cart_item_quantity_limits( $cart_item );
+		$product = $cart_item['data'];
```
Comment (opr) [inline plugins/woocommerce/src/StoreApi/Utilities/QuantityLimits.php]: Same here, is it possible for $cart_item['data'] not to be set? Should we check before accessing it?

**Review by opr — DISMISSED** [review]
Thanks Mike, this is working as far as it prevents the order being placed with an invalid quantity, however during testing I didn't get any warnings while checking out, and I feel the shopper experience is poor because of this. There is no warning that the item quantity changed to 2, if the quantity limit is implemented while the user is on the checkout form, and then presses "Place order" then the order is placed without notifying the user. I think we need to throw an exception the first time the quantity is changed to make sure the user is notified.

File: plugins/woocommerce/src/StoreApi/Utilities/QuantityLimits.php [hunk 3]
```diff
@@ -92,51 +126,32 @@ public function limit_to_multiple( int $number, int $multiple_of, string $roundi
...
 
 		if ( ! $limits['editable'] ) {
-			return new \WP_Error(
-				'readonly_quantity',
-				__( 'This item is already in the cart and its quantity cannot be edited', 'woocommerce' )
-			);
+			/* translators: 1: product name */
```
Comment (opr) [inline plugins/woocommerce/src/StoreApi/Utilities/QuantityLimits.php:142]: When are these errors thrown? During set quantity?

File: plugins/woocommerce/src/StoreApi/Utilities/QuantityLimits.php (hunk 1 above)
Comment (mikejolley) [reply plugins/woocommerce/src/StoreApi/Utilities/QuantityLimits.php]: I think everywhere in core assumes the cart returns valid types. We can add an extra check, it won't hurt.

File: plugins/woocommerce/src/StoreApi/Utilities/QuantityLimits.php (hunk 3 above)
Comment (mikejolley) [reply plugins/woocommerce/src/StoreApi/Utilities/QuantityLimits.php:142]: Updating qty via the API yeah.

File: plugins/woocommerce/src/StoreApi/Utilities/QuantityLimits.php (hunk 2 above)
Comment (mikejolley) [reply plugins/woocommerce/src/StoreApi/Utilities/QuantityLimits.php]: https://github.com/woocommerce/woocommerce/pull/52154/commits/aae25d6c0fdf1aafa2d1ee02fc90f99ff102c1b1

File: plugins/woocommerce/src/StoreApi/Utilities/QuantityLimits.php (hunk 1 above)
Comment (mikejolley) [reply plugins/woocommerce/src/StoreApi/Utilities/QuantityLimits.php]: https://github.com/woocommerce/woocommerce/pull/52154/commits/aae25d6c0fdf1aafa2d1ee02fc90f99ff102c1b1

**Comment by mikejolley** [comment]
> this is working as far as it prevents the order being placed with an invalid quantity, however during testing I didn't get any warnings while checking out, and I feel the shopper experience is poor because of this. There is no warning that the item quantity changed to 2, if the quantity limit is implemented while the user is on the checkout form, and then presses "Place order" then the order is placed without notifying the user. I think we need to throw an exception the first time the quantity is changed to make sure the user is notified.

@opr I fear we are trying to take care of too many edge cases in this qty logic which leads to compromises and complexity elsewhere. 

The issue you mention, things changing as you place order, could also encompass other edge cases such as:

1. Products being edited e.g. changing price, as the customer places the order
2. Shipping methods being edited while someone checks out
3. Qty changing due to purchase from another customer 
4. etc, anything that changes totals on the server during checkout

Perhaps the way to fix this would be some kind of validation between client and checkout route when placing order, This could be either:

- Passing the cart hash. If the hash changes, reject the request and update totals
- Passing the order total. If the total changes, reject the request and update totals

I know you're afk so I will cc @ralucaStan for thoughts. My preference would be to solve the normalisation issue here, then fix the checkout totals changes edge case in a follow up. This PR will still need code review.

**Comment by senadir** [comment]
I'm fine going as is with this. I'm trying to think of cases where quantity is bypassed and you reach Checkout with invalid quantity, and it's not clear if such thing is possible (and not caught early on at add product phase). From my testing, Mini Cart will fix those on load as well.

**Review by senadir — APPROVED** [review]
Thank you for working on this Mike, love deleting code.

**Comment by mikejolley** [comment]
I've logged the total changing issue here https://github.com/woocommerce/woocommerce/issues/52663

File: plugins/woocommerce/src/StoreApi/Utilities/QuantityLimits.php [hunk 4]
```diff
@@ -92,51 +126,36 @@ public function limit_to_multiple( int $number, int $multiple_of, string $roundi
...
-			return new \WP_Error(
-				'invalid_quantity',
-				sprintf(
-					// Translators: %s amount.
-					__( 'The minimum quantity that can be added to the cart is %s', 'woocommerce' ),
-					$limits['minimum']
-				)
-			);
+			/* translators: 1: product name 2: minimum quantity */
+			return new \WP_Error( 'invalid_quantity', sprintf( __( 'The minimum quantity of &quot;%1$s&quot; allowed in the cart is %2$s', 'woocommerce' ), $product->get_name(), $limits['minimum'] ) );
```
Comment (senadir) [inline plugins/woocommerce/src/StoreApi/Utilities/QuantityLimits.php:148]: Any idea why those quotes were pre-escaped?

Comment (mikejolley) [reply plugins/woocommerce/src/StoreApi/Utilities/QuantityLimits.php:148]: No; is that an issue? Could use left/right quotes instead.
