### PR TITLE
check low_stock for empty string vs isset

### LINKED ISSUE #22730: Low stock threshold on product defaults to 0
**Describe the bug**
A followup to #22084 - If no low stock threshold is entered in the product a `0` is saved as the value in the DB. 

**To Reproduce**
1. Enable stock management
2. Edit any product
3. Enable Manage Stock
4. Clear the low threshold field
5. Save the product
6. The value in the field is `0` when the page reloads. The meta_value in the DB is also `0`.

**Expected behavior**
The DB meta_value should be empty. The product edit screen should show the placeholder.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by rrennick**
### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

In the product edit screen, the low stock field is POSTed as an empty string when stock management is enabled. `absint('')` returns a `0`. This changes the `isset` on the low stock field check to an empty string check.

Closes #22730 .

### How to test the changes in this Pull Request:

1. Edit a product
2. Enable stock management and remove the low stock threshold value
3. Save the product
4. On re-load the low stock threshold placeholder should be visible and have the value of the WC settings low stock threshold.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?

### Changelog entry

> Fix allow product low stock threshold be the WC settings default.

### CODE REVIEW

File: includes/admin/meta-boxes/class-wc-meta-box-product-data.php [hunk 1]
```diff
@@ -365,20 +365,20 @@ public static function save( $post_id, $post ) {
 				'backorders'         => isset( $_POST['_backorders'] ) ? wc_clean( wp_unslash( $_POST['_backorders'] ) ) : null,
 				'stock_status'       => wc_clean( wp_unslash( $_POST['_stock_status'] ) ),
 				'stock_quantity'     => $stock,
-				'low_stock_amount'   => isset( $_POST['_low_stock_amount'] ) ? wc_stock_amount( wp_unslash( $_POST['_low_stock_amount'] ) ) : null,
+				'low_stock_amount'   => '' !== $_POST['_low_stock_amount'] ? wc_stock_amount( wp_unslash( $_POST['_low_stock_amount'] ) ) : null,
```
Comment (claudiosanches) [inline includes/admin/meta-boxes/class-wc-meta-box-product-data.php]: This generate the follow PHP notice when stock management is deactivated on WooCommerce:

```
PHP Notice:  Undefined index: _low_stock_amount in wp-content/plugins/woocommerce/includes/admin/meta-boxes/class-wc-meta-box-product-data.php on line 368
```

Also this don't fix the issue, need to set as empty string instead of `null`, see the logic here:

https://github.com/woocommerce/woocommerce/blob/889cf64ac465826104080e5f8ce23e09109cf777/includes/abstracts/abstract-wc-product.php#L982-L990

```
$ wp shell
wp> absint( null )
=> int(0)
```

This should solve all issues:

```php
'low_stock_amount'   => isset( $_POST['_low_stock_amount'] ) && '' !== $_POST['_low_stock_amount'] ? wc_stock_amount( wp_unslash( $_POST['_low_stock_amount'] ) ) : '',
```

**Review by claudiosanches — CHANGES_REQUESTED** [review]
Thanks for your work, just some small fixes missing here before we are able to merge.

File: includes/admin/meta-boxes/class-wc-meta-box-product-data.php (hunk 1 above)
Comment (rrennick) [reply includes/admin/meta-boxes/class-wc-meta-box-product-data.php]: @claudiosanches Thanks. I've update the PR.

**Review by claudiosanches — APPROVED** [review]
LGTM!

**Review by mikejolley — APPROVED** [review]
