### PR TITLE
Interactivity API powered Mini Cart - Add "Available in backorder" badge

### LINKED ISSUE #59009: Interactivity API powered Mini Cart - Show "Available in backorder" badge
## What?

When the show in backorder option is enabled for a product, it should show a badge saying "Available in backorder".

| Existing block | Experimental block |
|---------------|------------------|
| Image |  Image | 

## Steps to reproduce

> To test the experimental block, make sure `experimental-iapi-mini-cart` and `experimental-iapi-runtime` are set to `true` in the `development.json` file: [link](https://github.com/woocommerce/woocommerce/blob/c9cc094885a0351dd2cb550a5739f5980e0a5e6c/plugins/woocommerce/client/admin/config/development.json#L8-L9).

1. Edit a product -> Inventory -> Set "Quantity" to 0.
2. Edit Inventory -> Check "Track stock quantity for this product" -> Select "Allow, but notify customer".
3. Add this product to the cart.
4. Check that the "Available in backorder" is shown.

### PR DESCRIPTION
**Pull request by SantosGuillamot**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Adds the "Available in backorder" badge to the iAPI powered minicart, which wasn't included yet.

Closes #59009.

### Screenshots or screen recordings:

| Before | After |
|---------------|------------------|
| Image | Image | 

### How to test the changes in this Pull Request:

> To test the experimental block, make sure `experimental-iapi-mini-cart` and `experimental-iapi-runtime` are set to `true` in the `development.json` file: [link](https://github.com/woocommerce/woocommerce/blob/c9cc094885a0351dd2cb550a5739f5980e0a5e6c/plugins/woocommerce/client/admin/config/development.json#L8-L9).

1. Edit a product -> Inventory -> Set "Quantity" to 0.
2. Edit Inventory -> Check "Track stock quantity for this product" -> Select "Allow, but notify customer".
3. Add this product to the cart.
4. Check that the "Available in backorder" is shown.
5. You can change the setting and check it doesn't show.

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment

Add "Available in backorder" badge in iAPI powered minicart.

</details>

### CODE REVIEW

File: plugins/woocommerce/client/blocks/assets/js/blocks/mini-cart/iapi-frontend.ts [hunk 1]
```diff
@@ -371,6 +371,10 @@ const { state: cartItemState } = store(
 
 				return formatPriceWithCurrency( totalLinePrice, itemCurrency );
 			},
+
+			get isAvailableInBackorder(): boolean {
+				return cartItemState.cartItem.show_backorder_badge;
+			},
```
Comment (SantosGuillamot) [inline plugins/woocommerce/client/blocks/assets/js/blocks/mini-cart/iapi-frontend.ts]: Theoretically, I believe we could use directly `context...show_backorder_badge` in the directive. But, if I am not mistaken, we need to use derived state until this is fixed: https://github.com/woocommerce/woocommerce/blob/923651affc42007b94a29e62f680507a5680267f/plugins/woocommerce/client/blocks/assets/js/blocks/mini-cart/iapi-frontend.ts#L198-L210

File: plugins/woocommerce/src/Blocks/BlockTypes/MiniCartItemsBlock.php [hunk 2]
```diff
@@ -92,6 +94,9 @@ protected function render_experimental_iapi_markup( $attributes, $content, $bloc
 								<td class="wc-block-cart-item__product">
 									<div class="wc-block-cart-item__wrap">
 										<a data-wp-text="state.cartItemName" data-wp-bind--href="state.cartItem.permalink" class="wc-block-components-product-name"></a>
+										<div data-wp-bind--hidden="!state.isAvailableInBackorder" class="wc-block-components-product-badge wc-block-components-product-backorder-badge" hidden>
```
Comment (SantosGuillamot) [inline plugins/woocommerce/src/Blocks/BlockTypes/MiniCartItemsBlock.php]: I've added `hidden` to the HTML because it is the pattern I saw in the other elements. However, I wonder if we should initialize the state from the server somehow.

File: plugins/woocommerce/client/blocks/assets/js/blocks/mini-cart/iapi-frontend.ts [hunk 3]
```diff
@@ -371,6 +371,10 @@ const { state: cartItemState } = store(
 
 				return formatPriceWithCurrency( totalLinePrice, itemCurrency );
 			},
+
+			get isAvailableInBackorder(): boolean {
```
Comment (opr) [inline plugins/woocommerce/client/blocks/assets/js/blocks/mini-cart/iapi-frontend.ts]: One small nitpick, the correct grammar would be _on_ backorder

Comment (opr) [reply plugins/woocommerce/client/blocks/assets/js/blocks/mini-cart/iapi-frontend.ts]: https://github.com/woocommerce/woocommerce/blob/d596e0344d6eb98c860daa36909680d5a75eff35/plugins/woocommerce/src/Enums/ProductStockStatus.php#L25-L30

Comment (SantosGuillamot) [reply plugins/woocommerce/client/blocks/assets/js/blocks/mini-cart/iapi-frontend.ts]: You're totally right. I've just changed it in the last commit. Thanks for pointing that out!

File: plugins/woocommerce/client/blocks/assets/js/blocks/mini-cart/iapi-frontend.ts (hunk 1 above)
Comment (SantosGuillamot) [reply plugins/woocommerce/client/blocks/assets/js/blocks/mini-cart/iapi-frontend.ts]: Never mind, I used the state directly in [this commit](https://github.com/woocommerce/woocommerce/pull/59388/commits/b1123d6853d6623a4072909e28bc5156e0198f4a) 🤦

**Review by DAreRodz — APPROVED** [review]
Approved!

File: plugins/woocommerce/src/Blocks/BlockTypes/MiniCartItemsBlock.php (hunk 2 above)
Comment (DAreRodz) [reply plugins/woocommerce/src/Blocks/BlockTypes/MiniCartItemsBlock.php]: Yeah, the `hidden` attribute should not be required there, as I pointed out in https://github.com/woocommerce/woocommerce/pull/59399#discussion_r2185676103. Also, for SSR, it would be good to initialize these values in the state.

I checked it, and SSR is not being applied for some reason here. 🤔

Comment (SantosGuillamot) [reply plugins/woocommerce/src/Blocks/BlockTypes/MiniCartItemsBlock.php]: I've removed the `hidden` property and opened [this other issue](https://github.com/woocommerce/woocommerce/issues/59477) to track and discuss the server initialization.
