### PR TITLE
[WooCommerce Analytics] Fix: Show variations only for the selected product's variations

### LINKED ISSUE #43110: Variable Product analytics shows variations of all products instead of the selected product's variations.
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When you go to Analytics > Products and select a single variable product, it would show variations of all the products under the "Variations" section. Previously (WooCommerce version 8.4.0) only used to show the variations of the selected product in "Variations" section.

### Expected behavior

The variations section should only show variations of the selected variable product.

### Actual behavior

The variations section should only show variations of the selected variable product.

### Steps to reproduce

1. On a store, make sure that you have orders for multiple variable products (say Variable Product 1, Variable Product 2)
2. Go to Analytica > Products, and filter only the report for "Variable Product 1".
3. You will notice that variations of Variable Product 2 is also showing under the "Variations" section.
4. Now roll back WooCommerce to version 8.4.0 and check the same report. You will see the "Variations" section only shows variations of "Variable Product 1".

### WordPress Environment

`
### WordPress Environment ###

WC Version: 8.4.0
REST API Version: ✔ 8.4.0
WC Blocks Version: ✔ 11.6.2
Action Scheduler Version: ✔ 3.7.0
Log Directory Writable: ✔
WP Version: 6.4.2
WP Multisite: –
WP Memory Limit: 4 گیگابایت
WP Debug Mode: –
WP Cron: ✔
Language: fa_IR
External object cache: ✔

### Server Environment ###

Server Info: Apache
PHP Version: 7.4.33
PHP Post Max Size: 512 مگابایت
PHP Time Limit: 300
PHP Max Input Vars: 10000
cURL Version: 8.5.0
OpenSSL/1.1.1w

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.5.23-MariaDB
Max Upload Size: 512 مگابایت
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.4.0
WC Database Prefix: wp_
اندازه کل پایگاه داده: 1951.89MB
اندازه داده‌های پایگاه داده: 1200.10MB
اندازه فهرست پایگاه داده: 751.79MB

### Post Type Counts ###

attachment: 10498
cms_block: 9
custom_css: 1
cycloneslider: 1
elementor_library: 1
mc4wp-form: 1
nav_menu_item: 117
page: 82
portfolio: 9
post: 3
product: 853
product_variation: 6543
revision: 54
shop_coupon: 5
shop_order: 180388
shop_order_refund: 13
woodmart_sidebar: 2
woodmart_size_guide: 667
wp_global_styles: 1
wpcode: 4
wpdiscuz_form: 1
xlwcty_thankyou: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (17) ###

دیجیتس ippanel : ورود و ثبت نام با موبایل: توسط UnitedOver
ippanel – 7.7

ویژوال کامپوزر: توسط بومی سازی شده – 6.7.0
کش لایت اسپید: توسط LiteSpeed Technologies – 6.0.0.1
مکمل افزونه پیامک ووکامرس برای ippanel: توسط  – 1.6
پیامک حرفه ای ووکامرس: توسط ووکامرس فارسی – 4.4.0
Product Variations Swatches for WooCommerce: توسط VillaTheme – 1.1.1
SSL واقعا ساده: توسط پلاگین های واقعا ساده – 7.1.3
Remember Me Controls: توسط Scott Reilly – 2.0.1
Password Strength Settings for WooCommerce: توسط Daniel Santoro – 3.0.0
Shipping Method Description for WooCommerce: توسط Thomas Charbit – 1.2.6
CTX Feed: توسط WebAppick – 4.4.45
ویرایشگر فرم پرداخت برای ووکامرس: توسط ThemeHigh – 2.0.0
WooCommerce Custom Payment Gateway: توسط WPRuby – 1.3.5
Stock Manager for WooCommerce: توسط StoreApps – 3.0.0
ووکامرس: توسط اتوماتیک – 8.4.0
Woodmart Core: توسط  – 1.0.29
افزونه پرداخت امن زرین‌پال برای ووکامرس: توسط Masoud Amini 
alireza yousefi – 4.8.1

### Inactive Plugins (7) ###

IDPay payment gateway for Woocommerce: توسط IDPay – 2.1.2
IranDargah Payment Gateway for WooCommerce: توسط IranDargah – 2.1.5
Loco Translate: توسط Tim Whitlock – 2.6.2
Media Cleaner: توسط Jordy Meow – 6.6.7
Query Monitor: توسط John Blackbourn – 3.15.0
Resize Image After Upload: توسط ShortPixel – 1.8.6
WPCode Lite: توسط WPCode – 2.1.3.1

### Dropin Plugins (2) ###

maintenance.php: maintenance.php
object-cache.php: object-cache.php

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: IRT (تومان)
Currency Position: right_space
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 0
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to Woo.com: –
Enforce Approved Product Download Directories: –
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### WC Pages ###

پایگاه فروشگاه: #6 - /shop/
سبد خرید: #7 - /cart/
پرداخت: #8 - /checkout/
حساب کاربری من: #9 - /my-account/
شرایط و ضوابط: ❌ برگه تنظیم نشده است

### Theme ###

Name: Woodmart
Version: 6.1.4 (به‌روزرسانی به نسخه 7.3.4 در دسترس است)
Author URL: http://themeforest.net/user/xtemos
Child Theme: ❌ – اگر شما در حال ویرایش و شخصی سازی ووکامرس روی قالب والد هستید پیشنهاد می کنیم از قالب فرزند استفاده کنید. ببینید: چگونه یک قالب فرزند بسازیم
WooCommerce Support: ✔

### Templates ###

Overrides: woodmart/woocommerce/archive-product.php
woodmart/woocommerce/cart/cart-item-data.php
woodmart/woocommerce/cart/cart.php نسخه 4.4.0 تاریخ گذشته است. نسخه اصلی هست 7.9.0
woodmart/woocommerce/cart/cross-sells.php
woodmart/woocommerce/cart/mini-cart.php نسخه 5.2.0 تاریخ گذشته است. نسخه اصلی هست 7.9.0
woodmart/woocommerce/checkout/form-checkout.php
woodmart/woocommerce/checkout/thankyou.php نسخه 3.7.0 تاریخ گذشته است. نسخه اصلی هست 8.1.0
woodmart/woocommerce/content-product-cat.php
woodmart/woocommerce/content-product.php
woodmart/woocommerce/content-single-product.php
woodmart/woocommerce/content-widget-product.php
woodmart/woocommerce/global/breadcrumb.php
woodmart/woocommerce/global/form-login.php نسخه 3.6.0 تاریخ گذشته است. نسخه اصلی هست 7.0.1
woodmart/woocommerce/global/quantity-input.php نسخه 4.0.0 تاریخ گذشته است. نسخه اصلی هست 7.8.0
woodmart/woocommerce/loop/add-to-cart.php
woodmart/woocommerce/loop/loop-end.php
woodmart/woocommerce/loop/loop-start.php
woodmart/woocommerce/loop/no-products-found.php نسخه 2.0.0 تاریخ گذشته است. نسخه اصلی هست 7.8.0
woodmart/woocommerce/loop/orderby.php
woodmart/woocommerce/loop/pagination.php
woodmart/woocommerce/loop/sale-flash.php
woodmart/woocommerce/myaccount/form-login.php نسخه 4.1.0 تاریخ گذشته است. نسخه اصلی هست 7.0.1
woodmart/woocommerce/product-searchform.php نسخه 3.3.0 تاریخ گذشته است. نسخه اصلی هست 7.0.1
woodmart/woocommerce/single-product/add-to-cart/grouped.php نسخه 4.8.0 تاریخ گذشته است. نسخه اصلی هست 7.0.1
woodmart/woocommerce/single-product/add-to-cart/variable.php نسخه 3.5.5 تاریخ گذشته است. نسخه اصلی هست 6.1.0
woodmart/woocommerce/single-product/meta.php
woodmart/woocommerce/single-product/product-image.php نسخه 3.5.1 تاریخ گذشته است. نسخه اصلی هست 7.8.0
woodmart/woocommerce/single-product/product-thumbnails.php
woodmart/woocommerce/single-product/rating.php
woodmart/woocommerce/single-product/related.php
woodmart/woocommerce/single-product/sale-flash.php
woodmart/woocommerce/single-product/tabs/tabs.php
woodmart/woocommerce/single-product/title.php
woodmart/woocommerce/single-product/up-sells.php
woodmart/woocommerce/single-product.php

Outdated Templates: ❌
					
					
						چگونگی به روز رسانی را بیاموزید

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
product-virtual-downloadable
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: customize-store
minified-js
new-product-management-experience
product-external-affiliate
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2023-12-26 15:12:41 +03:30
Options: ✔
Notes: 31
Onboarding: completed

### Action Scheduler ###

تکمیل شده: 16,496
Oldest: 2023-11-25 07:59:59 +0000
Newest: 2023-12-26 07:48:13 +0000

ناموفق: 14
Oldest: 2023-11-07 10:33:49 +0000
Newest: 2023-11-22 16:17:14 +0000

در انتظار: 1
Oldest: 2023-12-26 14:07:11 +0000
Newest: 2023-12-26 14:07:11 +0000

### Status report information ###

Generated at: 2023-12-26 11:23:58 +03:30
`

### Isolating the problem

- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by puntope**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes #43110 

Fixes a bug that showed up all the product variations instead of the selected one

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. On a store, make sure that you have orders for multiple variable products (say Variable Product 1, Variable Product 2)
2. Go to Analytics > Products, and filter only the report for "Variable Product 1".
2. You will notice that variations of Variable Product 2 is also showing under the "Variations" section.
3. Checkout this PR and refresh the page
4. Now just the variations for the selected product are shown.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce/src/Admin/API/Reports/Variations/Controller.php [hunk 1]
```diff
@@ -39,6 +39,8 @@ class Controller extends ReportsController implements ExportableInterface {
 	 */
 	protected $param_mapping = array(
 		'variations' => 'variation_includes',
+		'products'   => 'product_includes',
+		'categories' => 'category_includes',
```
Comment (ianlin) [inline plugins/woocommerce/src/Admin/API/Reports/Variations/Controller.php]: It seems that we don't need this line (`'categories' => 'category_includes'`) in order to fix this issue. Also I think if we add this line here, we also need to define `$params['categories']` in the `get_collection_params()` method, just like you defined the `params['products']`. Otherwise [this loop for mapping registered params and request params](https://github.com/woocommerce/woocommerce/blob/0cdb36f11de1eab39ae79061d6de1d91329a710e/plugins/woocommerce/src/Admin/API/Reports/Variations/Controller.php#L66-L74) wouldn't be reached.

**Review by ianlin — APPROVED** [review]
Thanks for fixing the issue. I tested locally and confirmed the variations table only included the filtered one. Left a minor comment that isn't a blocker for this PR. LGTM.
