### PR TITLE
Fix cart: prevent false "Quantity changed to 1" notices and add optimistic removal feedback

### LINKED ISSUE #63381: Fix cart prevent false "Quantity changed to 1" notices and add optimistic removal feedback
This PR addresses UX issues discovered during testing of **#62766** (Implement request batching/queueing for cart operations). The fixes are designed to work with the new batching logic to ensure a smooth user experience during rapid add/remove flows.

### Changes proposed

**1. Fix for false "Quantity changed to 1" notices**
When items are rapidly deleted and re-added, the system previously treated the re-add as a quantity update. I adjusted the logic in `getInfoNoticesFromCartUpdates` to strictly check if the item existed in the old snapshot and had `old.quantity > 0`. This prevents incorrect "changed to 1" notices on rapid delete/re-add flows.

**2. Implemented Optimistic "Item Removed" notices**
Previously, **no notice was displayed** when an item was removed from the cart. I updated `removeCartItem` to trigger the "Removed" notice instantly alongside the DOM update (before the server response).
*   **If deleting the last item:** The system detects this is the last item, clears all notices immediately, and allows the "Your cart is currently empty!" placeholder to appear cleanly. This ensures that adding a new item afterwards starts with a fresh state, without showing outdated "removed" notices from the previous session.

### UI/UX Recommendations for Future Improvements
While this PR fixes the logic of the notices, the current notification system has UX drawbacks that should be addressed to make the Mini-Cart feel modern and stable:

*   **Move Notice Banner to Bottom:** Currently, notices appear at the top of the Mini-Cart. This causes the entire item list to jump up and down whenever a notice appears or disappears (layout shift). I recommend moving the notice container to the **bottom of the mini-cart**, just before the "View Cart" and "Checkout" buttons, to stop the content from jumping.
*   **Auto-dismissal:** Notices should automatically disappear after a short duration (e.g., **2 seconds**) instead of staying visible until the page reloads or manual close. This keeps the interface clean.
*   **Remove Manual Close Buttons:** For transient success messages, the "X" (close) buttons are redundant and clutter the UI. A modern approach relies on auto-dismissal or context clearing.

### How to test the changes
**Test Steps:**

1.  **Test Fix 1 (False notices):**
    *   Add 5-6 different simple products to the cart.
    *   Open the Mini-Cart.
    *   Rapidly delete all 5-6 items one by one.
    *   Immediately re-add them quickly.
    *   **Expected:** You should **NOT** see a notice saying "The quantity of [Product] was changed to 1".

2.  **Test Fix 2 (Instant feedback):**
    *   Add items again to the cart.
    *   Click "Remove" on one item.
    *   **Expected:** The notice "was removed from your cart." should appear **instantly** with your click. The item disappears from the list, and the notice appears *before* the server responds (Optimistic UI), confirming the action without lag.

3.  **Test Last Item & Clean State:**
    *   Delete the last remaining item in the cart.
    *   **Expected:** All previous notices should clear **immediately** as the "Your cart is currently empty!" placeholder appears.
    *   Add a new product to this empty cart.
    *   **Expected:** The new item appears. There should be **no** lingering "removed" notices from the previous deletion session.

### PR DESCRIPTION
**Pull request by markusfoo**
### Changes proposed in this Pull Request:

This PR addresses UX issues discovered during testing of **#62766** (Implement request batching/queueing for cart operations). The fixes are designed to work with the new batching logic to ensure a smooth user experience during rapid add/remove flows.

**1. Fix for false "Quantity changed to 1" notices**
When items are rapidly deleted and re-added, the system previously treated the re-add as a quantity update. I adjusted the logic in `getInfoNoticesFromCartUpdates` to strictly check if the item existed in the old snapshot and had `old.quantity > 0`. This prevents incorrect "changed to 1" notices on rapid delete/re-add flows.

**2. Implemented Optimistic "Item Removed" notices**
Previously, **no notice was displayed** when an item was removed from the cart. I updated `removeCartItem` to trigger the "Removed" notice instantly alongside the DOM update (before the server response).
*   **If deleting the last item:** The system detects this is the last item, clears all notices immediately, and allows the "Your cart is currently empty!" placeholder to appear cleanly.

Closes #63381

### How to test the changes in this Pull Request:

**Test Steps:**

1.  **Test Fix 1 (False notices):**
    *   Add 5-6 different simple products to the cart.
    *   Open the Mini-Cart.
    *   Rapidly delete all 5-6 items one by one.
    *   Immediately re-add them quickly.
    *   **Expected:** You should **NOT** see a notice saying "The quantity of [Product] was changed to 1".

2.  **Test Fix 2 (Instant feedback):**
    *   Add items again to the cart.
    *   Click "Remove" on one item.
    *   **Expected:** The notice "was removed from your cart." should appear **instantly** with your click. The item disappears from the list, and the notice appears *before* the server responds (Optimistic UI), confirming the action without lag.

3.  **Test Last Item & Clean State:**
    *   Delete the last remaining item in the cart.
    *   **Expected:** All previous notices should clear **immediately** as the "Your cart is currently empty!" placeholder appears.
    *   Add a new product to this empty cart.
    *   **Expected:** The new item appears. There should be **no** lingering "removed" notices from the previous deletion session.

### UI/UX Recommendations for Future Improvements
While this PR fixes the logic of the notices, the current notification system has UX drawbacks that should be addressed to make the Mini-Cart feel modern and stable:

*   **Move Notice Banner to Bottom:** Currently, notices appear at the top of the Mini-Cart. This causes the entire item list to jump up and down whenever a notice appears or disappears (layout shift).
*   **Auto-dismissal:** Notices should automatically disappear after a short duration (e.g., **2 seconds**) instead of staying visible until the page reloads.

### Changelog entry

> Fix - Fixes an existing bug

> Fixed false "Quantity changed to 1" notices and added optimistic removal feedback in Mini-Cart.

### CODE REVIEW

**Comment by Konamiman** [comment]
Hi @markusfoo, are the comments generated by Coderabbit addressed already? Also it seems that there are some linting issues.

**Comment by markusfoo** [comment]
> Hi @markusfoo, are the comments generated by Coderabbit addressed already? Also it seems that there are some linting issues.

Hi @Konamiman — addressed both points:
1. CodeRabbit's last-item notice logic is now implemented — when removing the last item, all notices are cleared immediately so the empty-cart placeholder appears cleanly.
2. Could you point to the specific linting issue? I've checked indentation (tabs) and formatting but want to make sure I'm fixing the right thing.

**Comment by markusfoo** [comment]
Hi again @kmanijak — while you're here, would you mind taking a look at #63403 as well? It's a related cart UX fix in the same area:

https://github.com/user-attachments/assets/a089c566-4a30-4e7d-a34c-a86e7620ffe8

### 3G Aggressive Test on clean store

https://github.com/user-attachments/assets/d2dd3420-0a2c-40a6-a37b-cf601a5b8e3b

1. **False "Quantity changed to 1" notices** — prevents incorrect notices when items are rapidly deleted and re-added (the re-add was being treated as a quantity update) - for fast test need make 3G/4G throttling 

2. **Optimistic "Item Removed" feedback** — shows the removal notice immediately alongside the DOM update, before the server responds
3. **Last item clean state** — clears all notices when the last item is removed so the empty-cart placeholder appears cleanly

All CodeRabbit comments are addressed (including the last-item logic it flagged). The only open question from @Konamiman is the specific linting issue — happy to fix it immediately once pointed out.

Thanks again for the #63402 review and merge! 🙏

**Comment by luisherranz** [comment]
Is this still reproducible after merging the PR that implements batching?

- https://github.com/woocommerce/woocommerce/pull/62766

**Comment by markusfoo** [comment]
> Is this still reproducible after merging the PR that implements batching?
> 
> * [Implement request batching/queueing for cart operations, utilize the queue within addCartItem, removeCartItem #62766](https://github.com/woocommerce/woocommerce/pull/62766)

Its Woocommerce 10.6/10.7 test) This bug appears on all builds, the video shows the batch packager from this merge.

PS. I wrote about this bug both before the merger and after the merger it was known about, but now I raised this issue again because it is an ignore for two Milestones 10.6.0 + 10.7.0. Details that here #63381 + #63078

My test site that I added always works on DEV clusters, you can run tests there. To make it easier to catch bugs, enable 3G throttling

**Comment by luisherranz** [comment]
We will try to reproduce it, thanks.

File: plugins/woocommerce/client/blocks/assets/js/base/stores/woocommerce/cart.ts [hunk 1]
```diff
@@ -172,18 +172,15 @@ const getInfoNoticesFromCartUpdates = (
 	const newItems = newCart.items;
 
 	const {
-		productsPendingAdd: pendingAdd = [],
 		cartItemsPendingQuantity: pendingQuantity = [],
-		cartItemsPendingDelete: pendingDelete = [],
 	} = quantityChanges;
```
Comment (SantosGuillamot) [inline plugins/woocommerce/client/blocks/assets/js/base/stores/woocommerce/cart.ts]: If I understand it correctly, the params passed to `getInfoNoticesFromCartUpdates` are:
- The cart after optimistic updates.
- The cart from the server.
In that case, I believe we don't need to track the `quantityChanges`, and just compare both.

File: plugins/woocommerce/client/blocks/assets/js/base/stores/woocommerce/cart.ts [hunk 2]
```diff
@@ -172,18 +172,15 @@ const getInfoNoticesFromCartUpdates = (
...
-	const autoDeletedToNotify = oldItems
-		.filter( isCartItem )
-		.filter(
-			( old ) =>
-				! newItems.some( ( item ) => old.key === item.key ) &&
-				! pendingDelete.includes( old.key )
-		);
+	const autoDeletedToNotify = oldItems.filter(
+		( old ) =>
+			old.key &&
```
Comment (SantosGuillamot) [inline plugins/woocommerce/client/blocks/assets/js/base/stores/woocommerce/cart.ts]: I think we don't need this `old.key` check because it would fail in the other checks.

File: plugins/woocommerce/client/blocks/assets/js/base/stores/woocommerce/cart.ts [hunk 3]
```diff
@@ -192,10 +189,10 @@ const getInfoNoticesFromCartUpdates = (
 		const old = oldItems.find( ( o ) => o.key === item.key );
 		return old
 			? ! pendingQuantity.includes( item.key ) &&
-					item.quantity !== old.quantity
-			: ! pendingAdd.includes( item.id );
+					item.quantity !== old.quantity &&
+					old.quantity > 0
+			: false;
```
Comment (SantosGuillamot) [inline plugins/woocommerce/client/blocks/assets/js/base/stores/woocommerce/cart.ts]: As mentioned in [this comment](https://github.com/woocommerce/woocommerce/pull/63403/changes#r2889926668), I believe we don't need to check `pendingQuantity` either.

Additionally, I think `old.quantity` should always be greater than 0, so I'd remove that check.

I think this could be simplified to something like this:

```js
return old && item.quantity !== old.quantity;
```

File: plugins/woocommerce/client/blocks/assets/js/base/stores/woocommerce/cart.ts [hunk 4]
```diff
@@ -319,7 +316,29 @@ const { state, actions } = store< Store >(
...
+							generateInfoNotice(
+								'"%s" was removed from your cart.'.replace(
+									'%s',
+									itemToRemove.name
+								)
+							),
+						] );
+					}
+				}
+
```
Comment (SantosGuillamot) [inline plugins/woocommerce/client/blocks/assets/js/base/stores/woocommerce/cart.ts]: As shared in the review, I would revert these changes because we shouldn't show a notice when the items are removed through user interaction.

**Review by SantosGuillamot — COMMENTED** [review]
Thanks for taking a look at this 🙂 I've been triaging it, and these are my thoughts:

### 1. Don't show "Quantity changed to X" notices

I agree we shouldn't show those notices because the products are updated via user interaction. And I confirm I'm able to replicate.

The batching and notices existing logic is complicated, but I believe your changes are in the right direction. I left some comments that could simplify the logic a bit.

From my understanding of `getInfoNoticesFromCartUpdates`, I believe we could remove `quantityChanges` by just comparing the cart after optimistic updates with the cart from the server, which solves the problem you are facing. However, it'd be great if @DAreRodz could take a look as well, as he introduced that logic in https://github.com/woocommerce/woocommerce/pull/59683.

I followed the testing steps without tracking the quantity changes, and it seems to work fine. But it needs to be double-checked.

### 2. Optimistic "Item Removed" notices

In this case, I don't think we should show any notice. The items are removed by the user manually, so I wouldn't expect a notice in the minicart. Actually, with this implementation, we can see how the notice is removed when the server updates. And that's because there shouldn't be a notice at all.

**Comment by markusfoo** [comment]
Thanks for the detailed triage @SantosGuillamot! All four inline points are addressed in the latest commit — replied directly under each one.

The core insight from your review is really clean: since we capture the optimistic snapshot *before* passing it to `getInfoNoticesFromCartUpdates`, the function already sees user intent baked in — no need to track it separately. That simplifies the whole thing significantly.

Agreed on the optimistic removal notice too — reverted that fully. I originally added it thinking users needed instant feedback, but you're right that in a mini-cart context it just creates noise, especially since the item disappears from the list immediately anyway.

Would be great to have @DAreRodz take a look at the `getInfoNoticesFromCartUpdates` simplification when he gets a chance, especially the rapid delete/re-add edge case — he introduced that logic in #59683 so he'll know the edge cases better than anyone.

File: plugins/woocommerce/client/blocks/assets/js/base/stores/woocommerce/cart.ts [hunk 5]
```diff
@@ -319,8 +312,8 @@ const { state, actions } = store< Store >(
 	'woocommerce',
 	{
 		actions: {
-			*removeCartItem( key: string ): AsyncAction< void > {
```
Comment (SantosGuillamot) [inline plugins/woocommerce/client/blocks/assets/js/base/stores/woocommerce/cart.ts:322]: We should keep this action type.

**Review by SantosGuillamot — APPROVED** [review]
Looks good to me 🙂 I just left a minor comment about an extra change that should be reverted. Thanks for working on it.

**Review by DAreRodz — COMMENTED** [review]
I think the code changes in this PR make sense. It's true that the `quantityChanges` param in `getInfoNoticesFromCartUpdates` is not necessary, as long as `oldCart` and `newCart` contain the state before and after the server response arrives, respectively, and notifications can be computed from the differences.

One thing I see that could be addressed in a follow-up PR is that all the notification-generation logic could live inside `sendCartRequest()`, rather than duplicating it across all actions that use it (`removeCartItem`, `addCartItem`, etc.).

cc: @SantosGuillamot

**Comment by markusfoo** [comment]
Thanks for the insight! I agree that centralizing notice generation in sendCartRequest would be much cleaner and reduce duplication.

I see @SantosGuillamot opened #63560 to track that work, so I'll leave that extraction for the follow-up PR. Thanks for the review!
