### PR TITLE
Fix race conditions when quickly switching between delivery options

### LINKED ISSUE #57542: Incorrect rate when toggling between shipping and local pickup quickly
## **Describe the bug**

When toggling between shipping and local pickup quickly the incorrect shipping rate can be selected.

## **To Reproduce**

1. Go to WC -> Settings -> Shipping -> Local pickup.
2. Enable Local Pickup and set up a location.
3. Ensure you have valid shipping methods set up.
4. Add an item to your cart and go to the Checkout block.
5. Switch between Local Pickup and Shipping quickly and notice that sometimes the incorrect rate is chosen, e.g. "Flat rate" will show while Local Pickup is selected.

## **Expected behavior**

The correct rate should be shown

## **Screenshots**

[Local pickup bug](https://www.loom.com/share/3967a1f782cd4e51b1c0d54ecd0cc7db?sid=6e74d9af-4459-448d-9c5d-ba56800ffa53)

## Environment

Please fill out any of the below that applies

**Operating System/Device**

- [ ] Windows
- [ ] MacOS
- [ ] Linux
- [ ] iPhone
- [ ] Samsung
- [ ] Other (add in additional context field)

**Version:** 

**Browser**

- [ ] Desktop Edge
- [ ] Desktop Chrome/Chromium
- [ ] Desktop Safari
- [ ] Mobile Edge
- [ ] Mobile Chrome/Chromium
- [ ] Mobile Safari
- [ ] Other (add in additional context field)

**Version:** 

## WordPress Environment

<details><summary>System Status report</summary>

</details>

### PR DESCRIPTION
**Pull request by straku**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes #57542

Every time the new delivery option is selected, we're doing a server call through `selectShippingRate` thunk present in the cart data store. The problem is, even though we properly abort the async operation within `selectShippingRate` thunk (see [this abort controller](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/client/blocks/assets/js/data/cart/thunks.ts#L418)), we don't call it consistently every time we switch the tab between delivery and pickup options. 

My fix resolves around:
- calling it consistently on component mount and letting thunk handle conflicts with the mentioned abort controller
- make sure it is consistently called every time a new delivery option is picked from the list (not changing tabs, but picking some specific option from the list)

I also simplified the `LocalPickupSelect` component API slightly to make it easier to follow. Instead of passing functions that are leaking implementation details (`setSelectedOption`, `onSelectRate`) I've opted it to a generic `onChange` handler.

### How to test the changes in this Pull Request:

1. Go to WC → Settings → Shipping → Local pickup.
2. Enable Local Pickup and set up a location.
3. Ensure you have valid shipping methods set up.
4. Add an item to your cart and go to the Checkout block.
5. Switch between Local Pickup and Shipping quickly and notice that sometimes the incorrect rate is chosen. Some additional notes here:
    - suggest watching the video attached to the issue before proceeding with testing
    - what you need to do essentially is be on the "ship" tab and then quickly switch to "pickup" and back to "ship" again (or pickup → ship → pickup), without the fix this would cause the pickup rate being selected even though you are on the ship tab after performing these steps
    - with "Slow 4G" network throttling it was easier to reproduce the bug, so you might opt it for testing with some throttling as well
    - you can inspect the network tab and verify whether the API calls for selecting shipping rate are properly cancelled

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce/client/blocks/assets/js/base/components/cart-checkout/shipping-rates-control-package/package-rates.tsx [hunk 1]
```diff
@@ -53,13 +53,19 @@ const PackageRates = ( {
 		}
 	}, [ selectedRateId, selectedOption, previousSelectedRateId ] );
```
Comment (straku) [inline plugins/woocommerce/client/blocks/assets/js/base/components/cart-checkout/shipping-rates-control-package/package-rates.tsx]: Apply something similar to the other component to account for changes in data store.

File: plugins/woocommerce/client/blocks/assets/js/base/components/cart-checkout/shipping-rates-control-package/package-rates.tsx [hunk 2]
```diff
@@ -67,6 +56,17 @@ const PackageRates = ( {
...
+	useEffect( () => {
+		if (
+			selectedRateId &&
+			selectedRateId !== previousSelectedRateId &&
+			selectedRateId !== selectedOption
+		) {
+			setSelectedOption( selectedRateId );
+		}
+	}, [ selectedRateId, selectedOption, previousSelectedRateId ] );
+
```
Comment (straku) [inline plugins/woocommerce/client/blocks/assets/js/base/components/cart-checkout/shipping-rates-control-package/package-rates.tsx:69]: Moved it for the sake of clarity. It works better in my head to have `useEffect` that runs only on mount to be above this one.

File: plugins/woocommerce/client/blocks/assets/js/blocks/checkout/inner-blocks/checkout-pickup-options-block/block.tsx [hunk 3]
```diff
@@ -175,6 +175,16 @@ const Block = () => {
...
+	// Update the selected option if cart state changes in the data store.
+	useEffect( () => {
+		const selectedRate = pickupLocations.find( ( rate ) => rate.selected );
+		const selectedRateId = selectedRate?.rate_id;
+
+		if ( selectedRateId && selectedRateId !== selectedOption ) {
+			setSelectedOption( selectedRateId );
+		}
+	}, [ pickupLocations, selectedOption ] );
+
```
Comment (straku) [inline plugins/woocommerce/client/blocks/assets/js/blocks/checkout/inner-blocks/checkout-pickup-options-block/block.tsx:187]: Not tested yet

**Comment by straku** [comment]
@opr It took a while, but the tests are there 😌

File: plugins/woocommerce/client/blocks/assets/js/blocks/checkout/inner-blocks/checkout-pickup-options-block/test/block.tsx [hunk 4]
```diff
@@ -0,0 +1,216 @@
...
+			selectShippingRate: jest.fn(),
+			isSelectingRate: false,
+			shippingRates: [ testPackageData ],
+		};
+	} );
+
+	render( <CheckoutPickupOptionsBlock /> );
+
+	// Find the radio buttons directly using screen queries
+	// The baseElement option allows us to search within portals
```
Comment (opr) [inline plugins/woocommerce/client/blocks/assets/js/blocks/checkout/inner-blocks/checkout-pickup-options-block/test/block.tsx]: Should this `baseElement` comment be here, doesn't look like we're using that

**Review by opr — APPROVED** [review]
Thanks @straku I tested this pretty extensively with different network throttle speeds and it worked each time! Appreciate you picking this up and the tests look great too 👏🏼  Just one comment about a comment but this can be merged.

Thanks!

File: plugins/woocommerce/client/blocks/assets/js/blocks/checkout/inner-blocks/checkout-pickup-options-block/test/block.tsx (hunk 4 above)
Comment (straku) [reply plugins/woocommerce/client/blocks/assets/js/blocks/checkout/inner-blocks/checkout-pickup-options-block/test/block.tsx]: It's a leftover from my pairing session with Claude (it wasn't too helpful in this case), let me remove it. Thanks for spotting!
