### PR TITLE
Fetch Marketplace promotions - ensure callback is always registered for `woocommerce_marketplace_fetch_promotions` action

### LINKED ISSUE #46923: Upgrading WooCommerce to 8.8.x results in cron errors regarding to woocommerce_marketplace_fetch_promotions
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

All of my clients have WP Cron running on server versus WordPress' internal cron. Since updating to WooCommerce 8.8.x I'm seeing this error report for all WooCommerce sites:

`Error: Error processing action 1448751: Scheduled action for woocommerce_marketplace_fetch_promotions will not be executed as no callbacks are registered.
`

### Expected behavior

Cron not to give any errors like it did for the 8.7.x branch.

### Actual behavior

Running WordPress 6.4.4, WooCommerce 8.8.2, WP Cron deferred to the server yields error message

### Steps to reproduce

1. Moved cron to server
2. See errors flood in

Not sure what else to say here besides the attached WordPress environment data and the explanation above. 

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): redacted
Site address (URL): redacted
WC Version: 8.8.2
REST API Version: ✔ 8.8.2
Action Scheduler Version: ✔ 3.7.4
Log Directory Writable: ✔
WP Version: 6.5.2
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: –
WP Cron: –
Language: nl_NL
External object cache: –

### Server Environment ###

Server Info: Apache/2.4
PHP Version: 8.0.30
PHP Post Max Size: 50 MB
PHP Time Limit: 600
PHP Max Input Vars: 2000
cURL Version: 7.82.0
OpenSSL/1.0.2k-fips

SUHOSIN Installed: –
MySQL Version: 10.5.21-MariaDB-log
Max Upload Size: 50 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.8.2
WC Database Prefix: 
Totale database grootte: 711.70MB
Database gegevens grootte: 515.51MB
Database index grootte: 196.19MB
woocommerce_sessions: Data: 5.02MB + Index: 0.08MB + Engine InnoDB
woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
woocommerce_order_items: Data: 2.52MB + Index: 1.52MB + Engine InnoDB
woocommerce_order_itemmeta: Data: 37.56MB + Index: 18.02MB + Engine InnoDB
woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
actionscheduler_actions: Data: 38.58MB + Index: 27.03MB + Engine InnoDB
actionscheduler_claims: Data: 2.52MB + Index: 1.52MB + Engine InnoDB
actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
actionscheduler_logs: Data: 30.56MB + Index: 15.03MB + Engine InnoDB
adtribes_my_conversions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
atum_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
atum_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
atum_product_data: Data: 1.52MB + Index: 0.41MB + Engine InnoDB
berocket_termmeta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
blogmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
blogs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
blog_versions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
cky_banners: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
cky_cookies: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
cky_cookie_categories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
cli_cookie_scan: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
cli_cookie_scan_categories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
cli_cookie_scan_cookies: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
cli_cookie_scan_url: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
cli_scripts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
commentmeta: Data: 0.08MB + Index: 0.03MB + Engine InnoDB
comments: Data: 10.52MB + Index: 10.08MB + Engine InnoDB
lecm_rewrite: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
mailchimp_carts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
mailchimp_jobs: Data: 0.25MB + Index: 0.00MB + Engine InnoDB
mclean_refs: Data: 0.52MB + Index: 0.00MB + Engine InnoDB
mclean_scan: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
member_catmeta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
options: Data: 41.44MB + Index: 1.27MB + Engine InnoDB
pmxe_exports: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
pmxe_google_cats: Data: 0.39MB + Index: 0.00MB + Engine InnoDB
pmxe_posts: Data: 0.44MB + Index: 0.00MB + Engine InnoDB
pmxe_templates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
portfolio_catmeta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
postmeta: Data: 273.25MB + Index: 93.59MB + Engine InnoDB
posts: Data: 23.09MB + Index: 7.16MB + Engine InnoDB
product_catmeta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
registration_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
say_what_strings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
sb_queue: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
signups: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
site: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
sitemeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
snippets: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
termmeta: Data: 0.16MB + Index: 0.17MB + Engine InnoDB
terms: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
term_relationships: Data: 2.52MB + Index: 1.48MB + Engine InnoDB
term_taxonomy: Data: 0.11MB + Index: 0.06MB + Engine InnoDB
tm_taskmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
tm_tasks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
usermeta: Data: 5.50MB + Index: 7.03MB + Engine InnoDB
users: Data: 0.36MB + Index: 0.28MB + Engine InnoDB
wcpdf_invoice_number: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wcpdf_invoice_number_2021: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
wcpdf_invoice_number_2022: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wcpdf_invoice_number_2023: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wcpdf_packing_slip_number: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wc_admin_notes: Data: 0.13MB + Index: 0.00MB + Engine InnoDB
wc_admin_note_actions: Data: 0.08MB + Index: 0.02MB + Engine InnoDB
wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wc_customer_lookup: Data: 0.45MB + Index: 0.34MB + Engine InnoDB
wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wc_order_product_lookup: Data: 2.52MB + Index: 2.56MB + Engine InnoDB
wc_order_stats: Data: 1.52MB + Index: 0.63MB + Engine InnoDB
wc_order_tax_lookup: Data: 0.41MB + Index: 0.34MB + Engine InnoDB
wc_product_attributes_lookup: Data: 0.14MB + Index: 0.08MB + Engine InnoDB
wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wc_product_meta_lookup: Data: 1.52MB + Index: 1.34MB + Engine InnoDB
wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wfblockediplog: Data: 0.17MB + Index: 0.00MB + Engine InnoDB
wfblocks7: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wfconfig: Data: 0.52MB + Index: 0.00MB + Engine InnoDB
wfcrawlers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wffilechanges: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wffilemods: Data: 11.55MB + Index: 0.00MB + Engine InnoDB
wfhits: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wfhoover: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wfissues: Data: 0.13MB + Index: 0.06MB + Engine InnoDB
wfknownfilelist: Data: 8.52MB + Index: 0.00MB + Engine InnoDB
wflivetraffichuman: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wflocs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wflogins: Data: 0.41MB + Index: 0.17MB + Engine InnoDB
wfls_2fa_secrets: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wfls_role_counts: Data: 0.00MB + Index: 0.00MB + Engine MEMORY
wfls_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wfnotifications: Data: 0.09MB + Index: 0.00MB + Engine InnoDB
wfpendingissues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wfreversecache: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wfsecurityevents: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wfsnipcache: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wfstatus: Data: 0.28MB + Index: 0.16MB + Engine InnoDB
wftrafficrates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wfwaffailures: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpr_rocket_cache: Data: 0.38MB + Index: 0.48MB + Engine InnoDB
wpr_rucss_used_css: Data: 1.52MB + Index: 1.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_postmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_posts: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
yoast_indexable: Data: 3.52MB + Index: 1.00MB + Engine InnoDB
yoast_indexable_hierarchy: Data: 0.19MB + Index: 0.23MB + Engine InnoDB
yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
yoast_primary_term: Data: 0.11MB + Index: 0.11MB + Engine InnoDB
yoast_prominent_words: Data: 0.33MB + Index: 0.59MB + Engine InnoDB
yoast_seo_links: Data: 0.52MB + Index: 0.30MB + Engine InnoDB

### Post Type Counts ###

attachment: 5362
atum_supplier: 21
br_labels: 14
cookielawinfo: 6
customize_changeset: 7
custom_css: 1
elementor_library: 2
nav_menu_item: 102
NIET_op_transaction: 2
op_transaction: 5791
op_z_report: 1318
page: 48
popup: 1
popup_theme: 8
porto_builder: 16
post: 43
postman_sent_mail: 186
product: 3153
product_variation: 1205
revision: 328
shop_coupon: 7
shop_order: 5906
shop_order_refund: 101
wcpcsu-custom-post: 1
wcps: 6
wcps_layout: 1
whatsapp-accounts: 1
wpcf7_contact_form: 2
wp_block: 1
wp_global_styles: 2
wp_navigation: 1
_op_receipt: 2
_op_register: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (37) ###

ManageWP - Worker: door GoDaddy – 4.9.19
ATUM Voorraadbeheer voor WooCommerce: door Stock Management Labs ™ – 1.9.38
Classic Widgets: door WordPress Contributors – 0.3
Code Snippets: door Code Snippets Pro – 3.6.4
CookieYes | GDPR Cookie Consent: door CookieYes – 3.2.2
Yoast Duplicate Post: door Enrico Battocchi & Team Yoast – 4.5
Facebook for WooCommerce: door Facebook – 3.1.15
Site Kit by Google: door Google – 1.125.0
LitExtension Customer Password Plugin: door LitExtension – 1.0.0
LitExtension SEO Plugin: door LitExtension – 1.0.1
Mailchimp for WooCommerce: door Mailchimp – 4.0.1
Mailgun: door Mailgun – 1.9.9
Pinterest for WooCommerce: door WooCommerce – 1.3.24
PixelYourSite: door PixelYourSite – 9.5.5
Porto Theme - Functionality: door P-Themes – 3.0.3
Product GTIN (EAN, UPC, ISBN) for WooCommerce: door Emanuela Castorina – 1.1.1
Say What?: door Ademti Software – 2.2.2
Scanfully: door Scanfully – 1.1.2
Servebolt Optimizer: door Servebolt – 3.5.32
WooCommerce Sisow betaalmethoden: door Sisow – 5.5.8
Spectra: door Brainstorm Force – 2.12.9
Product Feed PRO for WooCommerce: door AdTribes.io – 13.3.2
WooCommerce.com Update Manager: door Automattic – 1.0.2
WooCommerce Advanced Product Labels: door BeRocket – 3.2.6.5
Booster for WooCommerce: door Pluggabl LLC – 7.1.9
Woocommerce - Openpos - WooCommerce Germanized: door anhvnit@gmail.com – 1.0
Woocommerce OpenPos Pending Payment: door anhvnit@gmail.com – 1.1
Woocommerce OpenPos: door anhvnit@gmail.com – 6.0.7.1
PDF Invoices & Packing Slips for WooCommerce: door WP Overnight – 3.8.1
Product Slider for WooCommerce by PickPlugins: door PickPlugins – 1.13.49
WooCommerce: door Automattic – 8.8.2
WordPress Importer: door wordpressdotorg – 0.8.2
Yoast SEO Premium: door Team Yoast – 22.5
Yoast SEO: door Team Yoast – 22.5
WP Chat App: door NinjaTeam – 3.6.4
WP All Export - User Export Add-On Pro: door Soflyy – 1.0.7
Yoast SEO: WooCommerce: door Team Yoast – 16.2

### Inactive Plugins (6) ###

Contact Form 7: door Takayuki Miyoshi – 5.9.3
Google Analytics for WooCommerce: door WooCommerce – 2.0.6
WP All Export - ACF Export Add-On Pro: door Soflyy – 1.0.5
WP All Export - WooCommerce Export Add-On Pro: door Soflyy – 1.0.9
WP All Export Pro: door Soflyy – 1.8.3
WP Rocket: door WP Media – 3.15.0.1

### Dropin Plugins () ###

advanced-cache.php: advanced-cache.php

### Must Use Plugins (1) ###

ManageWP - Worker Loader: door GoDaddy – 1.0.0

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: left
Thousand Separator: 
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: –
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 dagen
Level threshold: –
Log directory size: 105 MB

### WC Pages ###

Winkelbasis: #207 - /shop/
Winkelwagen: #208 - /winkelwagen/
Afrekenen: #209 - /afrekenen/
Mijn account: #210 - /my-account/
Algemene voorwaarden: #3312 - /algemene-voorwaarden-webshop/

### Theme ###

Name: Porto Child
Version: 1.1
Author URL: https://www.portotheme.com/
Child Theme: ✔
Parent Theme Name: Porto
Parent Theme Version: 7.0.10
Parent Theme Author URL: https://www.portotheme.com/
WooCommerce Support: ✔

### Templates ###

Overrides: porto/woocommerce/archive-product.php
porto/woocommerce/cart/cart-empty.php
porto/woocommerce/cart/cart-shipping.php
porto/woocommerce/cart/cart-totals.php
porto/woocommerce/cart/cart.php
porto/woocommerce/cart/cross-sells.php
porto/woocommerce/cart/mini-cart.php
porto/woocommerce/cart/proceed-to-checkout-button.php
porto/woocommerce/cart/shipping-calculator.php
porto/woocommerce/checkout/form-billing.php
porto/woocommerce/checkout/form-checkout.php
porto/woocommerce/checkout/form-coupon.php
porto/woocommerce/checkout/form-login.php
porto/woocommerce/checkout/form-pay.php
porto/woocommerce/checkout/form-shipping.php
porto/woocommerce/checkout/payment-method.php
porto/woocommerce/checkout/payment.php
porto/woocommerce/checkout/review-order.php
porto/woocommerce/checkout/thankyou.php
porto/woocommerce/content-product-cat.php
porto/woocommerce/content-product.php
porto/woocommerce/content-single-product.php
porto/woocommerce/content-widget-product.php
porto/woocommerce/global/form-login.php
porto/woocommerce/global/quantity-input.php
porto/woocommerce/global/wrapper-start.php
porto/woocommerce/loop/add-to-cart.php
porto/woocommerce/loop/loop-end.php
porto/woocommerce/loop/loop-start.php
porto/woocommerce/loop/no-products-found.php
porto/woocommerce/loop/orderby.php
porto/woocommerce/loop/pagination.php
porto/woocommerce/loop/rating.php
porto/woocommerce/loop/sale-flash.php
porto/woocommerce/myaccount/dashboard.php
porto/woocommerce/myaccount/downloads.php
porto/woocommerce/myaccount/form-add-payment-method.php
porto/woocommerce/myaccount/form-edit-account.php
porto/woocommerce/myaccount/form-edit-address.php
porto/woocommerce/myaccount/form-login.php
porto/woocommerce/myaccount/form-lost-password.php
porto/woocommerce/myaccount/form-reset-password.php
porto/woocommerce/myaccount/lost-password-confirmation.php
porto/woocommerce/myaccount/my-account.php
porto/woocommerce/myaccount/my-address.php
porto/woocommerce/myaccount/my-downloads.php
porto/woocommerce/myaccount/my-orders.php
porto/woocommerce/myaccount/navigation.php
porto/woocommerce/myaccount/orders.php
porto/woocommerce/myaccount/payment-methods.php
porto/woocommerce/myaccount/view-order.php
porto/woocommerce/order/form-tracking.php
porto/woocommerce/order/order-details-customer.php
porto/woocommerce/order/order-details.php
porto/woocommerce/order/order-downloads.php
porto/woocommerce/order/tracking.php
porto-child/woocommerce/single-product/add-to-cart/simple.php
porto/woocommerce/single-product/add-to-cart/variable.php
porto/woocommerce/single-product/meta.php
porto-child/woocommerce/single-product/product-attributes.php
porto/woocommerce/single-product/product-image.php
porto/woocommerce/single-product/product-thumbnails.php
porto/woocommerce/single-product/rating.php
porto/woocommerce/single-product/related.php
porto/woocommerce/single-product/review-meta.php
porto/woocommerce/single-product/review-rating.php
porto/woocommerce/single-product/review.php
porto/woocommerce/single-product/sale-flash.php
porto/woocommerce/single-product/short-description.php
porto/woocommerce/single-product/tabs/tabs.php
porto/woocommerce/single-product/title.php
porto/woocommerce/single-product/up-sells.php
porto/woocommerce/single-product-reviews.php

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
product-virtual-downloadable
product-external-affiliate
product-grouped
product-linked
product-pre-publish-modal
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
product-custom-fields
settings
async-product-editor-category-field
launch-your-store

Daily Cron: ✔ Next scheduled: 2024-04-26 10:19:34 +02:00
Options: ✔
Notes: 208
Onboarding: completed

### Action Scheduler ###

Geannuleerd: 4
Oldest: 2024-04-17 16:25:03 +0200
Newest: -0001-11-30 00:19:32 +0019

Afgerond: 41.678
Oldest: 2024-03-25 15:10:03 +0100
Newest: 2024-04-25 16:00:40 +0200

Mislukt: 48.542
Oldest: 2021-01-27 14:09:19 +0100
Newest: 2024-04-25 16:05:03 +0200

In afwachting: 15
Oldest: 2024-04-25 16:05:09 +0200
Newest: 2025-01-01 00:00:01 +0100

### Status report information ###

Generated at: 2024-04-25 16:09:05 +02:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by mcliwanow**
We started getting errors 'Scheduled action for woocommerce_marketplace_fetch_promotions will not be executed as no callbacks are registered.' on some environments.

In this commit we ensure that WC_Admin_Marketplace_Promotions::fetch_marketplace_promotions() is always added as a calback to our action hook.

### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

1. Ensure that file `plugins/woocommerce/includes/admin/class-wc-admin-marketplace-promotions.php` is always loaded. This is to ensure that callback for previously scheduled action (added in WC Core 8.8) is always there.
2. Change how we fetch Marketplace promotions by switching from Action Scheduler to transients. This makes it easier to ensure that action is called only in admin context and has no impact on frontend users.
3. Reuse the `woocommerce_marketplace_suppress_promotions` filter in more places to ensure that it suppresses fetching data and displaying it.

Closes #46923 .

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Check out this branch.
2. Apply the following patch (it adds 2 `error_log()` entries and changes URL for fetching promotions) 
[promotions_transients.patch](https://github.com/woocommerce/woocommerce/files/15317832/promotions_transients.patch)

3. Build WooCommerce
```
cd plugins/woocommerce
nvm use
pnpm install
pnpm --filter='@woocommerce/plugin-woocommerce' build
```
4. Enter docker running at port 8888 (`wordpress-1`) and tail debug logs
```
cd wp-content
tail -f debug.log
```
5. Enter CLI docker (Name: `cli-1`) separately
6. Use the site as a regular user
   - confirm that there are no new log entries
   - Ensure that transient is not set - `wp transient get woocommerce_marketplace_promotions_v2` should be empty 
8. View site as admin
   - confirm there's one log for `fetch promotions`
   - browse through admin pages and confirm that remaining logs are `skip fetching promotions`
   - Go back to CLI docker and confirm that there's a value for the transient `wp transient get woocommerce_marketplace_promotions_v2`
9. Confirm that you see Sale bubble in the menu and that Sale notification is displayed in the In-App Marketplace
image
10. In CLI docker enter wp shell by running `wp shell` and run `WC_Admin_Marketplace_Promotions::get_active_promotions();` - confirm that active promotions return only what is matching current dates
11. Still in WP shell, remove the transient `delete_transient('woocommerce_marketplace_promotions_v2');`
12. Refresh admin pages and ensure that log `fetch promotions` is there
13. Add filter `add_filter( 'woocommerce_marketplace_suppress_promotions', '__return_true' );` and ensure that both sale bubble and notification inside In-App are no longer visible
14. Go to http://wccore.test:8888/wp-admin/admin.php?page=wc-status&tab=action-scheduler&action=-1&action2=-1&status=pending
2. Check if you have `woocommerce_marketplace_fetch_promotions` in pending actions
3. If yes, run the action
4. Make sure that afterward action `woocommerce_marketplace_fetch_promotions_clear` runs too and that when it's done you see neither `woocommerce_marketplace_fetch_promotions` nor `woocommerce_marketplace_fetch_promotions_clear` in pending actions
15. Please test around this issue / Try to break things

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce/includes/class-woocommerce.php [hunk 1]
```diff
@@ -585,6 +585,7 @@ public function includes() {
 		include_once WC_ABSPATH . 'includes/queue/class-wc-action-queue.php';
 		include_once WC_ABSPATH . 'includes/queue/class-wc-queue.php';
 		include_once WC_ABSPATH . 'includes/admin/marketplace-suggestions/class-wc-marketplace-updater.php';
+		include_once WC_ABSPATH . 'includes/admin/class-wc-admin-marketplace-promotions.php';
```
Comment (andfinally) [inline plugins/woocommerce/includes/class-woocommerce.php:588]: This means `WC_Admin_Marketplace_Promotions::init` is run for every request, even front end Ajax and Cron requests. It seems a shame that we have to do this simply because some users apparently run cron without setting `DOING_CRON`. But I can see there's not much else we can do to account for that case. And we have enough conditions in `init` to mean this should not be too heavy.

**Review by andfinally — APPROVED** [review]
Thanks Michal, this works as expected. 💯 

Hopefully rebasing on trunk will fix the test errors.

We should probably change these last points in the steps:

> 15. add filter `woocommerce_marketplace_suppress_promotions` that always returns true
> 16. Visit the [pending scheduled actions page](http://localhost:8888/wp-admin/admin.php?page=wc-status&tab=action-scheduler&status=pending) and search for `woocommerce_marketplace_fetch_promotions`. If there's a pending action, cancel it using the "cancel" hover link under it in the list. A new action should be scheduled.
> 17. Ensure that the action is available in the Pending tab and after a while it should be available in new tab Past-due (you might need to refresh the page)
> 18. Run the action via CLI `pnpm -- wp-env run cli wp cron event run action_scheduler_run_queue` and ensure that it's completed successfully - logs should indicate that early exits were triggered properly

because when the filter returns true, we don't even schedule the action. So when you cancel the remaining scheduled action, no new one is created, and the CLI command will do nothing. This is fine!

It was impossible to remove the value of `DISABLE_WP_CRON` once I'd set it – restarting wp-env didn't clear it, even though it was removed from the config file. I eventually had to set it to false.

**Comment by mcliwanow** [comment]
@andfinally, @corsonr, after some refactoring that changes code from using Action Scheduler to rely on transients (and running code only in wp admin context), I made changes to PR description and testing instructions. Would you mind doing another review?

File: plugins/woocommerce/changelog/fix-woocommerce_marketplace_fetch_promotions-broken-with-cron [hunk 2]
```diff
@@ -0,0 +1,4 @@
+Significance: patch
+Type: fix
+
+Switch marketplace promotions from Action Scheduler to cron.
```
Comment (andfinally) [inline plugins/woocommerce/changelog/fix-woocommerce_marketplace_fetch_promotions-broken-with-cron]: We should change this to something like `from Action Scheduler to transient`.

File: plugins/woocommerce/includes/admin/class-wc-admin-marketplace-promotions.php [hunk 3]
```diff
@@ -38,25 +37,8 @@ class WC_Admin_Marketplace_Promotions {
...
-		// Add the callback for our scheduled action.
-		if ( ! has_action( self::SCHEDULED_ACTION_HOOK, array( __CLASS__, 'fetch_marketplace_promotions' ) ) ) {
-			add_action( self::SCHEDULED_ACTION_HOOK, array( __CLASS__, 'fetch_marketplace_promotions' ) );
-		}
-
-		if ( is_admin() ) {
-			add_action( 'init', array( __CLASS__, 'schedule_promotion_fetch' ), 12 );
-		}
+		// A legacy hook that can be triggered by action scheduler.
+		add_action( 'woocommerce_marketplace_fetch_promotions', '__return_true' );
```
Comment (andfinally) [inline plugins/woocommerce/includes/admin/class-wc-admin-marketplace-promotions.php]: Clever, I'm glad you thought of that!

File: plugins/woocommerce/includes/class-woocommerce.php (hunk 1 above)
Comment (andfinally) [reply plugins/woocommerce/includes/class-woocommerce.php:588]: This is now superseded by the new method of fetching.

File: plugins/woocommerce/includes/admin/class-wc-admin-marketplace-promotions.php [hunk 4]
```diff
@@ -292,13 +325,14 @@ private static function append_bubble( string $menu_item_text, string $bubble_te
 	}
 
 	/**
-	 * When WooCommerce is deactivated, clear the scheduled action.
+	 * Clear event that was used for fetching promotions in WC Core 8.8.
```
Comment (andfinally) [inline plugins/woocommerce/includes/admin/class-wc-admin-marketplace-promotions.php]:
```suggestion
	 * Clear the scheduled action that was used to fetch promotions in WooCommerce 8.8.
```

**Review by andfinally — COMMENTED** [review]
This looks great, thanks, and tests as expected. I could have saved us a lot of work by just taking your original suggestion and not the advice of the clever people who recommended scheduled actions!

I had to comment out these options in `fetch_marketplace_promotions`, otherwise the function got a 404 when trying to fetch the gist.

```php
$fetch_options  = array(
	'auth'    => true,
	'country' => true,
);
```


I love the safeguard `add_action` for the legacy hook in `init`. I wonder if it would make sense to go further and cancel the leftover scheduled action? I still have the `woocommerce_marketplace_fetch_promotions` SA scheduled for every 12 hours.

One fairly safe way would be to restore

```php
register_deactivation_hook( WC_PLUGIN_FILE, array( __CLASS__, 'clear_scheduled_event' ) );
```

which would clear it for some people. (We're not using `clear_scheduled_event` otherwise.) We could also add a `register_activation_hook`, as that may be called when the user upgrades WooCommerce. Or we could even check the WooCommerce version on `plugins_loaded`, like discussed [here](https://wordpress.stackexchange.com/a/144873/14984).

**Comment by mcliwanow** [comment]
@andfinally , nice catch with 
```
register_deactivation_hook( WC_PLUGIN_FILE, array( __CLASS__, 'clear_scheduled_event' ) );
```

I wanted to keep it but must have removed it by accident 🤦 

Now I'm thinking about replacing this line `add_action( 'woocommerce_marketplace_fetch_promotions', '__return_true' );` to call a simple callback which would unscheduled the action if it was scheduled. It means that it should run only once then. I'll test it and will update the PR if it works.


> I had to comment out these options in fetch_marketplace_promotions, otherwise the function got a 404 when trying to fetch the gist.

Interesting 🤔 It worked for me without this particular change, but it's a good tip for other reviewers.

File: plugins/woocommerce/includes/admin/class-wc-admin-marketplace-promotions.php (hunk 3 above)
Comment (mcliwanow) [reply plugins/woocommerce/includes/admin/class-wc-admin-marketplace-promotions.php]: Thanks! I've changed it a bit in https://github.com/woocommerce/woocommerce/pull/47262/commits/ddd1cb793a69c6cdeeedc5806b2a27c89d585a2f and I wonder if you wouldn't mind reviewing this part?

I'll add the following steps to testing instructions:
1. Go to http://wccore.test:8888/wp-admin/admin.php?page=wc-status&tab=action-scheduler&action=-1&action2=-1&status=pending
2. Check if you have `woocommerce_marketplace_fetch_promotions` in pending actions
3. If yes, run the action
4. Make sure that afterward action `woocommerce_marketplace_fetch_promotions_clear` runs too and that when it's done you see neither `woocommerce_marketplace_fetch_promotions` nor `woocommerce_marketplace_fetch_promotions_clear` in pending actions

**Review by andfinally — APPROVED** [review]
Genius solution to the leftover scheduled actions! 🏆 I retested everything and all worked as expected.

**Comment by mcliwanow** [comment]
I did one small change after @andfinally's review - minor lint fix, so I just amended the commit. In history it looks like it happened after @andfinally's review but 99% of the changes were reviewed by him.

File: plugins/woocommerce/includes/admin/class-wc-admin-marketplace-promotions.php [hunk 5]
```diff
@@ -66,31 +49,73 @@ public static function init() {
 			return;
 		}
 
+		if ( ! is_admin() ) {
+			return;
+		}
+
+		self::maybe_update_promotions();
```
Comment (ilyasfoo) [inline plugins/woocommerce/includes/admin/class-wc-admin-marketplace-promotions.php:56]: Hey, @mcliwanow! I'm working on [identifying synchronous remote requests to WCCOM](https://github.com/woocommerce/woocommerce/issues/50543). Just wanted to flag that this is running synchronously when viewing `wp-admin`. While this has caching to limit requests, could it be made better by running it in a cron instead?

Comment (ilyasfoo) [reply plugins/woocommerce/includes/admin/class-wc-admin-marketplace-promotions.php:56]: Or alternatively, via ajax request

Comment (mcliwanow) [reply plugins/woocommerce/includes/admin/class-wc-admin-marketplace-promotions.php:56]: @ilyasfoo, we can take a look at this one. Before we do though, do you think it'd make sense to create some abstraction layer making it easier to communicate with WCCOM in a safe, async, and cachable way?

Comment (ilyasfoo) [reply plugins/woocommerce/includes/admin/class-wc-admin-marketplace-promotions.php:56]: Thanks, @mcliwanow!

> do you think it'd make sense to create some abstraction layer making it easier to communicate with WCCOM in a safe, async, and cachable way?

We do have an existing generic class ([DataSourcePoller](https://github.com/woocommerce/woocommerce/blob/0a60c3c5ec9b4830ab7d4e3817354f25bec597c3/plugins/woocommerce/src/Admin/RemoteSpecs/DataSourcePoller.php#L1)) which handles API requests, locale, and caching. However, it doesn't implement async queries out of the box.

Feel free to improve the class if you'd like, I'd be glad to help around with reviews and suggestions!

Comment (andfinally) [reply plugins/woocommerce/includes/admin/class-wc-admin-marketplace-promotions.php:56]: Hi @ilyasfoo 👋, IIRC, we had some [problems](https://woocorerelease.wordpress.com/2024/04/16/code-freeze-exception-8-8-2-2/) previously we tried to update this data using Action Scheduler. What's the background to this?

I read on the linked issue that this type of request can break wp-admin and on the P2 it [says](https://ghidorahp2.wordpress.com/2024/08/08/plan-of-attack-remote-specs-faults/#problem-3-synchronous-requests) we want to rewrite such requests. Are we worried for example that if the endpoint requested no longer exists, this will break the rest of the page?

Looking at the [function concerned](https://github.com/woocommerce/woocommerce/blob/536807ca432c8ff466d3726c7735073cc9008234/plugins/woocommerce/includes/admin/class-wc-admin-marketplace-promotions.php#L109-L160), we seem to have adequate error handling, so that in this case the error would be contained.

Comment (ilyasfoo) [reply plugins/woocommerce/includes/admin/class-wc-admin-marketplace-promotions.php:56]: Hey, @andfinally. Thanks for looking into it!

> What's the background to this?

The primary goal of changing it to async is to improve the stability `wp-admin` experience. As of now, the request runs synchronously and runs on all `wp-admin` pages. In the event of an unresponsive `woocommerce.com` and cache not available, it can potentially hold up `wp-admin` requests at least until a cache is set. 

> Are we worried for example that if the endpoint requested no longer exists, this will break the rest of the page?

While it's unlikely for `woocommerce.com` to go down, when it happens, it could stall merchants/admin users even if don't intend to use WooCommerce. In a typical configuration, API requests or PHP execution timeouts can take up to 30 seconds. I think it's still worth attempting to improve the experience.

We can simulate the current issue by using beta tester tool with the following steps:

1. Create a fresh Jurassic Ninja site with `woocommerce`
2. Install `woocommerce-beta-tester` (download [woocommerce-beta-tester.zip](https://github.com/user-attachments/files/17094190/woocommerce-beta-tester.zip) or build from `trunk` in core repo)
3. Go to `Tools > WCA Test Helper > Tools`
4. In `Force errors on woocommerce.com requests`, select `Timeout after 6 seconds` and click `Run` ([screenshot](https://github.com/user-attachments/assets/de3ab026-5bb7-41de-8f5f-c383da9916f1))
5. SSH to the site, and run `wp cache flush`
6. Go to `/wp-admin`
7. Observe the request takes at least 6 seconds to load

Comment (andfinally) [reply plugins/woocommerce/includes/admin/class-wc-admin-marketplace-promotions.php:56]: HI @ilyasfoo thanks for the details! We have an [issue](21774-gh-Automattic/woocommerce.com) to fix this in the upcoming release.
