### PR TITLE
Fix lost password page visibility when logged in

### LINKED ISSUE #28956: Logged in user can visit page to reset password (lost-password)
This logic allows a logged user to visit page `/my-account/lost-password/`

https://github.com/woocommerce/woocommerce/blob/af3077bca9990260feae2850cd63762d06035f9c/includes/shortcodes/class-wc-shortcode-my-account.php#L42

A possible fix would be:
```diff
-- if ( ! is_user_logged_in() || isset( $wp->query_vars['lost-password'] ) ) {
++ if ( ! is_user_logged_in() && isset( $wp->query_vars['lost-password'] ) ) {
```

### PR DESCRIPTION
**Pull request by mikejolley**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Prevents access to the lost password page when logged in. Also cleans up rendering of account page to remove deprecated elements and split logged in/logged out behaviour (which I implemented before the redirect).

Closes #28956

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. As a logged in user go to the my account page
2. Navigate between each section and ensure things look correct
3. Navigate directly to /my-account/lost-password. You should be redirected to the "edit account" page.
4. Log out.
5. On the account page click "lost password"
6. Ensure the lost password form is shown and you can go through the full account reset flow

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce/includes/shortcodes/class-wc-shortcode-my-account.php [hunk 1]
```diff
@@ -56,50 +61,16 @@ public static function output( $atts ) {
...
-			self::my_account( $atts );
-
-			/**
-			 * Deprecated my-account.php template handling. This code should be
-			 * removed in a future release.
-			 *
-			 * If woocommerce_account_content did not run, this is an old template
-			 * so we need to render the endpoint content again.
-			 */
-			if ( ! did_action( 'woocommerce_account_content' ) ) {
```
Comment (mikejolley) [inline plugins/woocommerce/includes/shortcodes/class-wc-shortcode-my-account.php:81]: This code has been in a deprecated state since 2.6.0 so should be safe to remove by now.

File: plugins/woocommerce/includes/shortcodes/class-wc-shortcode-my-account.php [hunk 2]
```diff
@@ -56,50 +61,16 @@ public static function output( $atts ) {
...
-				}
-			}
+			return;
+		}
 
-			// Send output buffer.
-			ob_end_flush();
+		if ( isset( $wp->query_vars['customer-logout'] ) ) {
+			/* translators: %s: logout url */
+			wc_add_notice( sprintf( __( 'Are you sure you want to log out? <a href="%s">Confirm and log out</a>', 'woocommerce' ), wc_logout_url() ) );
```
Comment (mikejolley) [inline plugins/woocommerce/includes/shortcodes/class-wc-shortcode-my-account.php:69]: This will be removed in this related PR https://github.com/woocommerce/woocommerce/pull/49605

File: plugins/woocommerce/changelog/fix-lost-password-page-visibility-28956 [hunk 3]
```diff
@@ -0,0 +1,4 @@
+Significance: minor
```
Comment (mikejolley) [inline plugins/woocommerce/changelog/fix-lost-password-page-visibility-28956:1]: @opr up for debate p1721305560590119/1721298070.980489-slack-C8X6Q7XQU

File: plugins/woocommerce/includes/wc-template-functions.php [hunk 4]
```diff
@@ -46,6 +46,12 @@ function wc_template_redirect() {
 		exit;
 	}
 
+	// Redirect to edit account if trying to recover password whilst logged in.
+	if ( isset( $wp->query_vars['lost-password'] ) && is_user_logged_in() ) {
+		wp_safe_redirect( wc_get_endpoint_url( 'edit-account', '', wc_get_page_permalink( 'myaccount' ) ) );
```
Comment (opr) [inline plugins/woocommerce/includes/wc-template-functions.php]: Above `esc_url_raw` is used, should we do the same here?

**Review by opr — APPROVED** [review]
Functionally this is working fine, and we discussed removing the deprecated code.

It has been showing a deprecation notice since 2.6.0 and in the case anyone is still using it, the error would be doubled up "My account" content shown on the page. Seems like a low-likelihood, low-risk fix.

I left one comment inline, merge if you don't think it's necessary.
