### PR TITLE
[NOX In-Context] Fix the default country in the business step to match the selected one in NOX

### LINKED ISSUE #58186: [NOX In-Context] Activate payments steps is not pre-filled with the business location selected in NOX
When we change the country in the switcher (e.g. Emirates) before kicking off NOX In-Context, the country stays old in the Activate payments step.

### PR DESCRIPTION
**Pull request by elazzabi**
### Changes proposed in this Pull Request:

When starting the NOX In-Context, the country selected in the Payments settings doesn't match the one shown inside the business step.

CleanShot 2025-05-21 at 16 19 17@2x

Closes WOOPLUG-4366
Closes #58186 

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Get this PR
2. Select a country in Settings > Payments
3. Start the onboarding process using NOX In-Context
4. When you reach the business step, ensure the default selected country matches the one selected before.

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [x] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

Fix the default country in the business step to match the selected one in NOX
</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce/client/admin/client/settings-payments/onboarding/providers/woopayments/steps/business-verification/index.tsx [hunk 1]
```diff
@@ -30,10 +30,7 @@ export const BusinessVerificationStep: React.FC = () => {
 			location.hostname === 'localhost'
 				? 'https://wcpay.test'
 				: window.wcSettings?.homeUrl + getComingSoonShareKey(),
-		country: (
-			window.wcSettings?.admin?.preloadSettings?.general
-				?.woocommerce_default_country || 'US'
-		).split( ':' )[ 0 ],
```
Comment (elazzabi) [inline plugins/woocommerce/client/admin/client/settings-payments/onboarding/providers/woopayments/steps/business-verification/index.tsx:36]: I'm wondering if there are some edge cases here, and we should keep the split just to be safe 🤔

Comment (elazzabi) [reply plugins/woocommerce/client/admin/client/settings-payments/onboarding/providers/woopayments/steps/business-verification/index.tsx:36]: Added this back in https://github.com/woocommerce/woocommerce/pull/58190/commits/656118ae36274193d538ad924bf84af8b9f972d1

Comment (mordeth) [reply plugins/woocommerce/client/admin/client/settings-payments/onboarding/providers/woopayments/steps/business-verification/index.tsx:36]: The country switcher component only supports two-digit country codes. In my view, the split isn’t necessary.

Comment (elazzabi) [reply plugins/woocommerce/client/admin/client/settings-payments/onboarding/providers/woopayments/steps/business-verification/index.tsx:36]: Good call, reverted in 53ae88d736ccca300dc817f4640ecceeaaf63879

**Review by vladolaru — APPROVED** [review]
Thank you for fixing this, @elazzabi! The code changes are simple and straightforward and the testing instructions checked out: the NOX business location country is carried over to the pre-KYC form and the WooCommerce store location is not.

**Review by oaratovskyi — APPROVED** [review]
Tested for the UK, works well! 🎉

**Comment by vladolaru** [comment]
@elazzabi, I noticed a possible issue: if I close the NOX in-context modal at the first step of the activate payments step, and then reopen it, it reopens correctly, but I get US, when I should get UK (the selected business location in NOX). Could you check what is going on?
