### PR TITLE
Optimize variable product duplication slug generation

### LINKED ISSUE #24315: Duplicating a variable product repeatedly can lead to a performance issue
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Create a variable product, let's call it "Product template" with N variations, for example "Small" and "Large"
2. Use the duplicate feature on the product
3. Change title, description, image on the draft and publish it
4. Repeat 2-3 for a few times
5. If you look at the `wp_posts` entries for the variations the `post_name` is always something like `product-template-small-4`, `product-template-small-5` etc. even if the `post_name` for the parent is not `product-template` anymore.

## Expected/actual behavior

I found this problem debugging a nasty 504 error on a store with more than 40000 photos sold in two print sizes. I set up a draft product with variations already on, so one has just to clone that, change name, description, image, SKU and publish. This worked smoothly for about 900 new products (SiteGround GrowBig tier).
In the last few days duplicating that template product lead to 504 error most of the times. Using `SAVEQUERIES` I found that on duplication there were over 900 queries to find the first usable `post_name` for the first variation, and another set of 900+ queries for the second variation: this happens because when the variations are cloned they tend to keep the same original `post_name`, which doesn't change even when the draft is published (as opposed to `post_name` for the parent variable product).
Deleting the old draft product and creating a new one with a new `post_name` stopped the 504 errors, but I suppose it will happen again once this new draft is cloned for a similar number of times.

I know it's something happening only on very special setups and it's strongly dependent on the system hosting the site, but since `WC_Product_Variable_Data_Store_CPT::sync_variation_names()` already keeps the variation `post_title` in sync with the parent, couldn't the same be done with `post_name`? Even not being concerned about the performance issue, consindering occasional duplication of products, the data would also be more consistent, without `post_names` unrelated to the actual products and variations names.

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
`
### WordPress Environment ###

WordPress address (URL): https://photorally.it/admin
Site address (URL): https://photorally.it
WC Version: 3.6.5
Log Directory Writable: ✔
WP Version: 5.2.2
WP Multisite: –
WP Memory Limit: 768 MB
WP Debug Mode: ✔
WP Cron: –
Language: it_IT
External object cache: ✔

### Server Environment ###

Server Info: Apache
PHP Version: 7.1.30 - Consigliamo di usare PHP versione 7.2 o superiore per prestazioni e sicurezza maggiori. Come aggiornare la versione di PHP
PHP Post Max Size: 128 MB
PHP Time Limit: 120
PHP Max Input Vars: 3000
cURL Version: 7.59.0
OpenSSL/1.0.2r

SUHOSIN Installed: –
MySQL Version: 5.6.40-84.0-log
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.6.5
WC Database Prefix: pr_
MaxMind GeoIP Database: ✔
Dimensione totale database: 544.55MB
Dimensione dati database: 368.67MB
Dimensione indice database: 175.88MB
pr_woocommerce_sessions: Dati: 10.02MB + Indice: 1.16MB
pr_woocommerce_api_keys: Dati: 0.02MB + Indice: 0.03MB
pr_woocommerce_attribute_taxonomies: Dati: 0.02MB + Indice: 0.02MB
pr_woocommerce_downloadable_product_permissions: Dati: 0.02MB + Indice: 0.06MB
pr_woocommerce_order_items: Dati: 0.16MB + Indice: 0.06MB
pr_woocommerce_order_itemmeta: Dati: 1.52MB + Indice: 0.52MB
pr_woocommerce_tax_rates: Dati: 0.02MB + Indice: 0.06MB
pr_woocommerce_tax_rate_locations: Dati: 0.02MB + Indice: 0.03MB
pr_woocommerce_shipping_zones: Dati: 0.02MB + Indice: 0.00MB
pr_woocommerce_shipping_zone_locations: Dati: 0.02MB + Indice: 0.03MB
pr_woocommerce_shipping_zone_methods: Dati: 0.02MB + Indice: 0.00MB
pr_woocommerce_payment_tokens: Dati: 0.02MB + Indice: 0.02MB
pr_woocommerce_payment_tokenmeta: Dati: 0.02MB + Indice: 0.03MB
pr_woocommerce_log: Dati: 0.02MB + Indice: 0.02MB
pr_aepc_custom_audiences: Dati: 0.02MB + Indice: 0.00MB
pr_aepc_logs: Dati: 0.02MB + Indice: 0.00MB
pr_commentmeta: Dati: 0.02MB + Indice: 0.03MB
pr_comments: Dati: 0.08MB + Indice: 0.09MB
pr_ewwwio_images: Dati: 0.02MB + Indice: 0.03MB
pr_ewwwio_queue: Dati: 0.02MB + Indice: 0.02MB
pr_links: Dati: 0.02MB + Indice: 0.02MB
pr_logger_ginger: Dati: 0.02MB + Indice: 0.00MB
pr_options: Dati: 21.55MB + Indice: 7.52MB
pr_postmeta: Dati: 217.78MB + Indice: 114.28MB
pr_posts: Dati: 75.61MB + Indice: 24.13MB
pr_smush_dir_images: Dati: 0.02MB + Indice: 0.03MB
pr_termmeta: Dati: 1.52MB + Indice: 0.83MB
pr_terms: Dati: 1.52MB + Indice: 0.53MB
pr_term_relationships: Dati: 10.55MB + Indice: 5.52MB
pr_term_taxonomy: Dati: 1.52MB + Indice: 0.59MB
pr_usermeta: Dati: 0.44MB + Indice: 0.39MB
pr_users: Dati: 0.06MB + Indice: 0.05MB
pr_wcpdf_invoice_number: Dati: 0.02MB + Indice: 0.00MB
pr_wc_admin_notes: Dati: 0.02MB + Indice: 0.00MB
pr_wc_admin_note_actions: Dati: 0.02MB + Indice: 0.02MB
pr_wc_customer_lookup: Dati: 0.05MB + Indice: 0.03MB
pr_wc_download_log: Dati: 0.02MB + Indice: 0.03MB
pr_wc_order_coupon_lookup: Dati: 0.02MB + Indice: 0.03MB
pr_wc_order_product_lookup: Dati: 0.14MB + Indice: 0.16MB
pr_wc_order_stats: Dati: 0.05MB + Indice: 0.05MB
pr_wc_order_tax_lookup: Dati: 0.02MB + Indice: 0.03MB
pr_wc_product_meta_lookup: Dati: 12.52MB + Indice: 17.09MB
pr_wc_webhooks: Dati: 0.02MB + Indice: 0.02MB
pr_wfblockediplog: Dati: 0.02MB + Indice: 0.00MB
pr_wfblocks7: Dati: 0.02MB + Indice: 0.05MB
pr_wfconfig: Dati: 0.42MB + Indice: 0.00MB
pr_wfcrawlers: Dati: 0.02MB + Indice: 0.00MB
pr_wffilechanges: Dati: 0.02MB + Indice: 0.00MB
pr_wffilemods: Dati: 2.52MB + Indice: 0.00MB
pr_wfhits: Dati: 2.02MB + Indice: 0.38MB
pr_wfhoover: Dati: 0.02MB + Indice: 0.02MB
pr_wfissues: Dati: 0.02MB + Indice: 0.06MB
pr_wfknownfilelist: Dati: 1.52MB + Indice: 0.00MB
pr_wflivetraffichuman: Dati: 0.02MB + Indice: 0.02MB
pr_wflocs: Dati: 0.02MB + Indice: 0.00MB
pr_wflogins: Dati: 0.02MB + Indice: 0.03MB
pr_wfls_2fa_secrets: Dati: 0.02MB + Indice: 0.02MB
pr_wfls_settings: Dati: 0.02MB + Indice: 0.00MB
pr_wfnotifications: Dati: 0.02MB + Indice: 0.00MB
pr_wfpendingissues: Dati: 0.02MB + Indice: 0.06MB
pr_wfreversecache: Dati: 0.02MB + Indice: 0.00MB
pr_wfsnipcache: Dati: 0.02MB + Indice: 0.05MB
pr_wfstatus: Dati: 0.16MB + Indice: 0.11MB
pr_wftrafficrates: Dati: 0.08MB + Indice: 0.00MB
pr_yoast_seo_links: Dati: 3.52MB + Indice: 1.52MB
pr_yoast_seo_meta: Dati: 2.52MB + Indice: 0.00MB

### Post Type Counts ###

acf-field: 4
acf-field-group: 1
attachment: 45143
jetpack_migration: 2
ml-slide: 5
ml-slider: 1
nav_menu_item: 11
page: 20
post: 2
product: 45017
product_variation: 89898
revision: 51
scheduled-action: 100
shop_coupon: 28
shop_order: 176
wpcf7_contact_form: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (23) ###

Query Monitor: by John Blackbourn – 3.3.7
Campi Personalizzati Avanzati: by Elliot Condon – 5.8.2
WP Offload Media Lite: by Delicious Brains – 2.2.1
Contact Form 7: by Takayuki Miyoshi – 5.1.3
Duplicate Post: by Enrico Battocchi – 3.2.3
EU Cookie Law: by Alex Moss
Marco Milesi
Peadig
Shane Jones – 3.0.6

EWWW Image Optimizer: by Exactly WWW – 4.8.1
FG PrestaShop to WooCommerce Premium: by Frédéric GILLES – 3.47.1 – Non testato con la versione attiva di WooCommerce
Fly Dynamic Image Resizer: by Junaid Bhura – 2.0.5
Genesis Connect for WooCommerce: by StudioPress – 1.1.0
Google Analytics Dashboard per WP (GADWP): by ExactMetrics – 5.3.8
Image Watermark: by dFactory – 1.6.5
MetaSlider: by Team Updraft – 3.14.0
SG Optimizer: by SiteGround – 5.2.1
WooCommerce P.IVA e Codice Fiscale per Italia: by dot4all – 2.1.9 – Non testato con la versione attiva di WooCommerce
WooCommerce Admin: by WooCommerce – 0.16.0
WooCommerce PayPal Checkout Gateway: by WooCommerce – 1.6.16
WooCommerce PayPal Powered by Braintree Gateway: by WooCommerce – 2.2.5
WooCommerce PDF Invoices & Packing Slips: by Ewout Fernhout – 2.3.0
WooCommerce: by Automattic – 3.6.5
Wordfence Security: by Wordfence – 7.3.6
Yoast SEO: by Team Yoast – 11.7 – Non testato con la versione attiva di WooCommerce
WP Term Order: by John James Jacoby – 0.1.4

### Inactive Plugins (1) ###

Jetpack by WordPress.com: by Automattic – 7.5.3

### Dropin Plugins (2) ###

db.php: Query Monitor Database Class
object-cache.php: Memcached

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: left
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: simple (simple)
grouped (grouped)
variable (variable)
external (external)

Taxonomies: Product Visibility: exclude-from-search (exclude-from-search)
exclude-from-catalog (exclude-from-catalog)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #20050 - /negozio/
Carrello: #20051 - /carrello/
Cassa: #20052 - /checkout/
Il mio account: #20053 - /mio-account/
Termini e condizioni: #44005 - /termini-condizioni/

### Theme ###

Name: Seasons Pro
Version: 1.4.2
Author URL: https://www.wpstud.io
Child Theme: ✔
Parent Theme Name: Genesis
Parent Theme Version: 3.0.2
Parent Theme Author URL: https://www.studiopress.com/
WooCommerce Support: ✔

### Templates ###

Overrides: seasons-pro/woocommerce/loop/orderby.php

### Action Scheduler ###

Complete: 99
Oldest: 2019-07-26 23:33:08 +0200
Newest: 2019-08-03 00:00:03 +0200

Pending: 1
Oldest: 2019-08-03 01:00:04 +0200
Newest: 2019-08-03 01:00:04 +0200

Canceled: 0
Oldest: –
Newest: –

In-progress: 0
Oldest: –
Newest: –

Failed: 0
Oldest: –
Newest: –

`
```
</details>

### PR DESCRIPTION
**Pull request by ObliviousHarmony**
### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

The standard WordPress `wp_unique_post_slug()` function will query every consecutive suffix until it finds an available suffix. The consequence of this is that when using a template variable product, it can take a significant amount of time to clone the template once enough duplicates have been generated. I have gone ahead and generated the suffix before we save the variation, preventing WordPress from doing the expensive generation altogether.

Closes #24315.

### How to test the changes in this Pull Request:

1. Create a variable product template with variations
2. Clone the variation an incredibly large number of times.
3. The amount of time taken to perform the generation will not increase in the way it did before the change.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Fix: Adjusted the slug generation for duplicated variable products to prevent performance degradation when using templates.

### CODE REVIEW

**Comment by ObliviousHarmony** [comment]
I'm wondering a few things about this:

- Should I apply the generation we do here to the main product as well as the variations?
- Should we batch the query to prevent excessive memory usage? Since these are just post titles, and we're not loading the products, I wasn't sure if it was really that much of an issue?

File: includes/admin/class-wc-admin-duplicate-product.php [hunk 1]
```diff
@@ -215,6 +230,42 @@ private function get_product_to_duplicate( $id ) {
 
 		return $post;
 	}
+
+	/**
+	 * Generates a unique slug for a given product. We do this so that we can override the
+	 * behavior of wp_unique_post_slug(). The normal slug generation will run single
+	 * select queries on every non-unique slug, resulting in very bad performance.
+	 *
```
Comment (kloon) [inline includes/admin/class-wc-admin-duplicate-product.php]: Would you mind adding a since tag here so we know when the method was introduced?

File: includes/admin/class-wc-admin-duplicate-product.php [hunk 2]
```diff
@@ -215,6 +230,42 @@ private function get_product_to_duplicate( $id ) {
...
+
+		// The slug is already unique!
+		if ( empty( $results ) ) {
+			return;
+		}
+
+		// Find the maximum suffix so we can ensure uniqueness.
+		$max_suffix = 1;
+		foreach ( $results as $result ) {
+			$suffix = intval( substr( $result->post_name, strrpos( $result->post_name, '-' ) + 1 ) );
```
Comment (kloon) [inline includes/admin/class-wc-admin-duplicate-product.php]: Just a suggestion as I find substr with strrpos very confusing to read, perhaps use `intval( array_pop( explode( '-', $result->post_name ) ) );` instead? Up to you to decide though.

**Review by kloon — DISMISSED** [review]
Just a docblock change and then a suggestion that is up to you if you want to implement it or not. Big thanks for the unit tests!

**Review by claudiosanches — APPROVED** [review]
LGTM!
