### PR TITLE
 Change wp_woocommerce_sessions before dbDelta() is called

### LINKED ISSUE #21534: Database error when updating to 3.5.0
There might be a database error when updating to 3.5.0 as reported in https://github.com/woocommerce/woocommerce/pull/21245#issuecomment-420194220 introduced by the way I handled the new indexes on wp_woocommerce_sessions in #21245. I'm creating this issue to make sure we check this before tagging 3.5 rc2.

This is the error that @shivapoudel reported:

```
[11-Sep-2018 08:32:04 UTC] WordPress database error Multiple primary key defined for query ALTER TABLE wp_woocommerce_sessions ADD PRIMARY KEY  (`session_id`) made by activate_plugin, do_action('activate_woocommerce/woocommerce.php'), WP_Hook->do_action, WP_Hook->apply_filters, WC_Install::install, WC_Install::create_tables, dbDelta
```

I haven't had time yet to test it properly. When I created #21245, I was under the impression that `dbDelta()` didn't handle index changes and that is why I created `wc_update_350_change_woocommerce_sessions_schema`, but maybe I was wrong? Probably worth checking.

### PR DESCRIPTION
**Pull request by rodrigoprimo**
### Changes proposed in this Pull Request:

On PR #21245, I added a db update routine to change wp_woocommerce_sessions primary key from session_key char(32) to session_id bigint auto_increment as dbDelta() is unable to handle primary key changes (see https://core.trac.wordpress.org/ticket/40357). But I didn't realize that dbDelta() was actually trying to add a new primary key to the table without dropping the old key first, and this was generating the following error:

```
WordPress database error Multiple primary key defined for query ALTER TABLE wp_woocommerce_sessions ADD PRIMARY KEY  (`session_id`)
```

To prevent this error from happening, this PR moves the query that changes the primary key from db update routine to WC_Install::create_tables() so that it runs before dbDelta() is called. It also reverts the commits added in #21561 as they didn't produce the desired effect (see comments starting from https://github.com/woocommerce/woocommerce/issues/21534#issuecomment-429956490).

Closes #21534 

### How to test the changes in this Pull Request:

1. Make sure your store is running a WC database <= 3.4.6 (check the value of the wp_options `woocommerce_version` and `woocommerce_db_version`) and WC codebase <= 3.4.6.
2. Switch the codebase to `master`
3. Visit a WP admin page to trigger a call to WC_Install::create_tables() and then run the database update routine
4. Check that there are no errors on debug.log and the resulting `wp_woocommerce_sessions` schema is equal to the following (`session_id` should be the primary key and `session_key` a regular unique index):

```
desc wp_woocommerce_sessions;
+----------------+---------------------+------+-----+---------+----------------+
| Field          | Type                | Null | Key | Default | Extra          |
+----------------+---------------------+------+-----+---------+----------------+
| session_id     | bigint(20) unsigned | NO   | PRI | NULL    | auto_increment |
| session_key    | char(32)            | NO   | UNI | NULL    |                |
| session_value  | longtext            | NO   |     | NULL    |                |
| session_expiry | bigint(20) unsigned | NO   |     | NULL    |                |
+----------------+---------------------+------+-----+---------+----------------+
4 rows in set (0.00 sec)
```

### CODE REVIEW

File: includes/class-wc-install.php [hunk 1]
```diff
@@ -554,6 +553,22 @@ private static function create_tables() {
...
 		}
 
+		/**
+		 * Change wp_woocommerce_sessions schema to use a bigint auto increment field instead of char(32) field as
+		 * the primary key as it is not a good practice to use a char(32) field as the primary key of a table and as
+		 * there were reports of issues with this table (see https://github.com/woocommerce/woocommerce/issues/20912).
+		 *
+		 * This query needs to run before dbDelta() as this WP function is not able to handle primary key changes
+		 * (see https://github.com/woocommerce/woocommerce/issues/21534 and https://core.trac.wordpress.org/ticket/40357).
+		 */
```
Comment (claudiulodro) [inline includes/class-wc-install.php]: Good documentation. 👍

**Review by claudiulodro — APPROVED** [review]
Code looks good and this works well: (before and after running update routine)

screen shot 2018-10-18 at 8 43 49 pm

I'll leave this unmerged for now in case anyone else wants to test/review, but this seems to do the trick. 🥇
