### PR TITLE
Post editor: ensure that blocks aren't registered multiple times

### LINKED ISSUE #53195: `registerBlockSingleProductTemplate` register blocks twice in posts
**Steps to reproduce:**
1. Create new post
2. Open console

Expected: there should be no (or less 😅 ) warnings 
Actual: there's set of warning regarding blocks being already registered

Image

**Tech notes:**

Most likely it's a consequence of https://github.com/woocommerce/woocommerce/pull/53077. Before block registration in `subscribe( ..., 'core/edit-site' );` was "blocked" by the checked removed in https://github.com/woocommerce/woocommerce/pull/53077. Now the blocks are tried to be registered in both `subscribes`s.

### PR DESCRIPTION
**Pull request by gigitux**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

This PR improves the check to ensure that we don't try to register blocks that are already registered. As @kmanijak mentioned this error is caused by https://github.com/woocommerce/woocommerce/pull/53077:

> Before block registration in subscribe( ..., 'core/edit-site' ); was "blocked" by the checked removed in https://github.com/woocommerce/woocommerce/pull/53077. Now the blocks are tried to be registered in both subscribess.

Closes https://github.com/woocommerce/woocommerce/issues/53195.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Create new post
2. Open console
3. See no errors.

#### Single Product template

1. Go to Editor > Single Product template
2. Try to insert Product Price and Product Rating in couple of places
3. **Expected:** They should be available in the inserter

#### Other templates

1. Go to Editor > Product Catalog template
2. Try to insert Product Price and Product Rating within Product Collection block
3. **Expected:** They should be available in the inserter
4. Try to insert Product Price and Product Rating outside of Product Collection block
3. **Expected:** They should NOT be available in the inserter

#### Patterns

1. Go to Editor > Patterns > Add new pattern
2. Create synced pattern
3. Insert Single Product block
4. Try to insert Product Price and Product Rating within Single Product block
5. **Expected:** They should be available in the inserter
6. Try to insert Product Price and Product Rating outside of Single Product block
3. **Expected:** They should NOT be available in the inserter

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [x] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

Post editor: ensure that blocks aren't registered multiple times.

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce-blocks/assets/js/atomic/utils/register-block-single-product-template.ts [hunk 1]
```diff
@@ -102,17 +105,14 @@ export const registerBlockSingleProductTemplate = ( {
 	}, 'core/edit-site' );
 
 	subscribe( () => {
-		const isBlockRegistered = Boolean( variationName )
+		const isRegistered = Boolean( variationName )
```
Comment (kmanijak) [inline plugins/woocommerce-blocks/assets/js/atomic/utils/register-block-single-product-template.ts:109]: I'm thinking that maybe we should skip the logic of `blocksRegistered` Set completely for blocks and just keep if only for variations.

```suggestion
	subscribe( () => {
		const isRegistered = Boolean( variationName )
			? blocksRegistered.has( variationName )
			: isBlockRegistered( blockName );
		// This subscribe callback could be invoked with the core/blocks store
		// which would cause infinite registration loops because of the `registerBlockType` call.
		// This local cache helps prevent that.
		if ( ! isRegistered && isAvailableOnPostEditor && ! editSiteStore ) {
			if ( isVariationBlock ) {
				blocksRegistered.add( variationName ); // keep it for variation
				registerBlockVariation(
					blockName,
					blockSettings as BlockVariation< BlockAttributes >
				);
			} else {
			    // remove the locksRegistered.add( blockName ) for blocks
				// @ts-expect-error: `registerBlockType` is typed in WordPress core
				registerBlockType( blockMetadata, blockSettings );
			}
		}
	}, 'core/edit-post' );
```

GitHub doesn't allow me to put suggestion to the whole block, hence it's not the best diff, sorry about that.

**Review by kmanijak — APPROVED** [review]
Works as expected! I left one suggestion for simplification but otherwise all good! Thanks for quickly taking care of it!

File: plugins/woocommerce-blocks/assets/js/atomic/utils/register-block-single-product-template.ts (hunk 1 above)
Comment (gigitux) [reply plugins/woocommerce-blocks/assets/js/atomic/utils/register-block-single-product-template.ts:109]: I thought the same thing, but I wasn't sure that it made sense! Thanks for your feedback! I implemented it with 34120ec and 96ea336576ee09c230c88fe7c12542bacb0eb6ca. Can you take another look?

**Review by kmanijak — APPROVED** [review]
Re-checked the changes and all looks good! Thanks for addressing my feedback!

**Comment by gigitux** [comment]
I reverted the commit 34120ecfc48efded6f94d54c19f0dd6d66961ae9 due E2E tests failed because `isBlockRegistered` always returns false in certain cases (like the widget area). The `Set` object helps avoid infinite loops even if a block isn't registered. Should we rename it from `blocksRegistered` to `blockRegistrationAttempts` to better reflect its purpose?

**Comment by kmanijak** [comment]
> Should we rename it from blocksRegistered to blockRegistrationAttempts to better reflect its purpose?

Overall I think it's a good idea. But considering the scope of this PR I think it's a nice to have. But feel free if you don't mind 😄

**Comment by gigitux** [comment]
Thanks for the review! I updated the name and I'm going to merge this PR when CI will finish!
