### PR TITLE
Fix flakiness around the `Turn off the new product form` menu item

### LINKED ISSUE #39888: E2E: Fix flakiness around the `Turn off the new product form` menu item
In the E2E test `merchant/products/block-editor/disable-block-product-editor.spec.js > Disable block product editor > can be disabled from the header`, there is flakiness on the step where Playwright attempts to click the `Turn off the new product form` menu item. 

If you look at `0:09` and `0:10` of the E2E screen recording, notice that the menu was opened correctly as expected. The test's next step is to click on the `Turn off the new product form` item in that menu.

But on `00:11` notice that the menu suddenly closed when the `Welcome to the new product form` pop-up message appeared, and so Playwright couldn't find the menu anymore.

Maybe there's a race condition happening somewhere that causes the Options menu to be closed accidentally. It's tempting to add a "wait until network idle" after loading the new product editor, but it's a discouraged strategy by Playwright. The best practice is to wait for a specific network request that ensures that the state of the page is fully loaded. 

[1dc45caf4b4b0bda.webm](https://github.com/woocommerce/woocommerce/assets/4509348/deb6d34b-4674-4542-a2c0-133de413f552)

Looping in @octaedro for awareness because of the great work their team had been doing so far in providing E2E coverage of the new product editor. I'll have some time tomorrow to fix this, and might reach out to you for some questions 😄

### PR DESCRIPTION
**Pull request by rodelgc**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes https://github.com/woocommerce/woocommerce/issues/39888.

The E2E test `merchant/products/block-editor/disable-block-product-editor.spec.js > Disable block product editor > can be disabled from the header` had been flaky recently because the menu that contains the `Turn off the new product form` option automatically closes when the _"Welcome to the new product form!"_ tour message appears. To fix this flakiness, this PR makes sure that the block product editor tour would be disabled at the start of the test.

I don't see any of the specs inside the `merchant/products/block-editor` folders to be depending on whether the block product form tour is enabled or not, so I assume it's safe to disable the tour to prevent flakiness.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

#### Test the `can be disabled from the header` isolated

1. Checkout this branch and launch the local E2E environment.
1. Run the `can be disabled from the header` test 10 times without retries, and verify that it passes each time:
    ```bash
    pnpm test:e2e-pw -g "can be disabled from the header" --retries=0 --workers=1 --repeat-each=10
    ```

#### Run all the tests in the `merchant/products/block-editor` folder

1. Checkout this branch and launch the local E2E environment.
2. Run all the tests in the `merchant/products/block-editor` folder, repeating each test at least thrice. Allow retries this time, because other tests seem to be flaky still. They can be addressed separately in another PR.
    ```bash
    pnpm test:e2e-pw 'merchant/products/block-editor' --repeat-each=3
    ```
1. In the Playwright HTML report, filter by "Passed" tests.
1. Make sure that the three `can be disabled from the header` tests are all passing -- not flaky nor failed.

    QfDOd0UTIv

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce/tests/e2e-pw/utils/tours.js [hunk 1]
```diff
@@ -0,0 +1,31 @@
...
+/**
+ * Enables or disables the product editor tour.
+ *
+ * @param {import('@playwright/test').APIRequestContext} request Request context from calling function.
+ * @param {boolean} enable Set to `true` if you want to enable the block product tour. `false` if otherwise.
+ */
+const toggleBlockProductTour = async ( request, enable ) => {
+	const url = '/wp-json/wc-admin/options';
+	const params = { _locale: 'user' };
+	const toggleValue = enable ? 'no' : 'yes';
```
Comment (alopezari) [inline plugins/woocommerce/tests/e2e-pw/utils/tours.js:20]: Here I understand that if the function argument **enable** is `true`, then `woocommerce_block_product_tour_shown` will be set to `no`, which sounds different than the explanation of the argument in the function documentation:
```
@param {boolean} enable Set to `true` if you want to enable the block product tour. `false` if otherwise.
```

Could I be missing anything here?

File: plugins/woocommerce/tests/e2e-pw/utils/tours.js [hunk 2]
```diff
@@ -0,0 +1,31 @@
+const { admin } = require( '../test-data/data' );
+
+const base64String = Buffer.from(
+	`${ admin.username }:${ admin.password }`
+).toString( 'base64' );
+
+const headers = {
+	Authorization: `Basic ${ base64String }`,
+	cookie: '',
```
Comment (alopezari) [inline plugins/woocommerce/tests/e2e-pw/utils/tours.js]: Out of curiosity, is there any reason why we need to set the `cookie` header empty here?

**Review by alopezari — COMMENTED** [review]
Thanks for working on this PR @rodelgc! I left a couple of questions.

**Comment by alopezari** [comment]
The tests suggested in the testing instructions passed, but there is one `can be disabled from the header` that was flaky twice in a row when running `pnpm test:e2e-pw 'merchant/products/block-editor' --repeat-each=3`:
image

Is this a problem?

**Comment by rodelgc** [comment]
> The tests suggested in the testing instructions passed, but there is one `can be disabled from the header` that was flaky twice in a row when running `pnpm test:e2e-pw 'merchant/products/block-editor' --repeat-each=3`: image
> 
> Is this a problem?

Hi @alopezari. It seems that the browser unexpectedly closed, based on the error message you got. I tried rerunning the command with repeat-each set to `6`, and I got all 6 of the `can be disabled from the header` tests passing without needing a retry. The whole command was `pnpm test:e2e-pw 'merchant/products/block-editor' --repeat-each=6`

UvgmySJ4A7

Would you be able to try again with either repeat-each set to `3` or `6`? Also looping in @nigeljamesstevenson as the incoming reviewer.

File: plugins/woocommerce/tests/e2e-pw/utils/tours.js (hunk 2 above)
Comment (rodelgc) [reply plugins/woocommerce/tests/e2e-pw/utils/tours.js]: Oh, great catch @alopezari! `cookie` is not necessary in this case. I had just pushed 02638a71e831389bb109766116eca2a4d43ccdc4 to remove it.

I copied that function from another E2E test. That test used the `page` object to construct the `request` object so it needed to have an empty `cookie` header. Otherwise, that test will get a `401 Unauthorized` as a response.

But in this test, it passed even without the `cookie` header so I removed it. I guess it's because the function, particularly in this [line](https://github.com/woocommerce/woocommerce/blob/02638a71e831389bb109766116eca2a4d43ccdc4/plugins/woocommerce/tests/e2e-pw/utils/tours.js#L17), uses the `request` object instead of the usual `page` object.

File: plugins/woocommerce/tests/e2e-pw/utils/tours.js (hunk 1 above)
Comment (rodelgc) [reply plugins/woocommerce/tests/e2e-pw/utils/tours.js:20]: Right, it does appear confusing at first. But the documentation and the logic is still correct. 

When the `woocommerce_block_product_tour_shown` property is set to `no`, that means the tour was **not** shown to the user yet. Therefore, the tour will appear on the next time the user visits the new "Add product" page. So to enable the tour, we must set  `woocommerce_block_product_tour_shown` to `no`, and that could be done by passing `enable=true` to the `toggleBlockProductTour` function.

Let me know if it still sounds confusing.

**Comment by nigeljamesstevenson** [comment]
Thanks for the updates @rodelgc and for the review @alopezari 👏🏻

Great instructions - I have tested a couple of times and things are looking good 👍
image

There were other tests in the `block-editor` directory that were flaky 
image

e.g. `merchant/products/block-editor/enable-block-product-editor.spec.js:46:3 › Enable block product editor › Enabled › is not hooked up to sidebar "Add New"`, 
but, as you mentioned, they can be handled separately.

With a view to reducing the flakiness in the tests I am going to Merge this one.

**Review by nigeljamesstevenson — APPROVED** [review]
