### PR TITLE
Re-assign existing webhooks during user deletion

### LINKED ISSUE #37806: `woocommerce_rest_cannot_view` Webhook payload sent when webhook owner has been deleted
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Existing WooCommerce webhook(s) will stop sending the correct payloads if the Administrator user used to create the webhook(s) is subsequently deleted from the WordPress site.

### Expected behavior

Webhooks should continue to send the correct data even after an existing Administrator user is deleted.

When deleting an existing administrator user, and the **Attribute all content to** option is chosen during user deletion, any existing webhooks that are linked to the user being deleted should be re-assigned to the new user instead.

### Actual behavior

The following ` WP_Error` JSON payload is sent to the webhook:

```json
{
  "code": "woocommerce_rest_cannot_view",
  "message": "Sorry, you cannot view this resource.",
  "data": {
    "status": 401
  }
}
```

### Steps to reproduce

1. Set `WP_DEBUG` to `true` in wp-config.php so that webhook bodies are logged.
2. Log into WP-Admin. Go to `/wp-admin/admin.php?page=wc-settings&tab=advanced&section=webhooks` and add a new webhook, ensuring it is active. I suggest using **Order updated** as the topic.
3. Go to `/wp-admin/edit.php?post_type=shop_order` and edit an existing order. Edit something in the order (eg a shipping address), and save.
4. Go to `/wp-admin/admin.php?page=wc-status&tab=action-scheduler&status=pending` and wait until the `woocommerce_deliver_webhook_async` pending action is processed.
5. Go to `/wp-admin/admin.php?page=wc-status&tab=logs` and view the latest `webhooks-delivery` log file, and confirm the `Body` contains the order data from the order you just updated.
6. The above steps confirm the webhook is working as expected.
7. Create a new administrator user on your store.
8. Log in as that new administrator.
9. Delete the previous administrator account. There is now an existing webhook with a `user_id` field that points to a user ID that no longer exists.
10. Go to `/wp-admin/edit.php?post_type=shop_order` and edit the same order Edit something in the order (eg a shipping address), and save.
11. Go to `/wp-admin/admin.php?page=wc-status&tab=action-scheduler&status=pending` and wait until the `woocommerce_deliver_webhook_async` pending action is processed.
12. Go to `/wp-admin/admin.php?page=wc-status&tab=logs` and view the latest `webhooks-delivery` log file, and confirm the `Body` from the latest delivery is now a `woocommerce_rest_cannot_view` error rather than an expected order payload.

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): http://woocore.local
Site address (URL): http://woocore.local
WC Version: 7.8.0
REST API Version: ✔ 7.8.0
WC Blocks Version: ✔ 10.0.1
Action Scheduler Version: ✔ 3.5.4
Log Directory Writable: ✔
WP Version: 6.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.16.0
PHP Version: 8.0.22
PHP Post Max Size: 1,000 MB
PHP Time Limit: 1200
PHP Max Input Vars: 4000
cURL Version: 7.84.0
(SecureTransport) OpenSSL/1.1.1q

SUHOSIN Installed: –
MySQL Version: 8.0.16
Max Upload Size: 300 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.8.0
WC Database Prefix: wp_
Total Database Size: 2.43MB
Database Data Size: 1.00MB
Database Index Size: 1.43MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_postmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_posts: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 1
page: 7
post: 2

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 7.8.0-dev

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### WC Pages ###

Shop base: #6 - /shop/
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty-Three
Version: 1.1
Author URL: https://wordpress.org
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: product-block-editor
minified-js
new-product-management-experience
product-variation-management
settings

Daily Cron: ✔ Next scheduled: 2023-04-20 05:03:17 +00:00
Options: ✔
Notes: 51
Onboarding: skipped

### Action Scheduler ###

Pending: 3
Oldest: 2023-04-19 05:03:18 +0000
Newest: 2023-04-19 05:04:17 +0000

### Status report information ###

Generated at: 2023-04-19 05:03:32 +00:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### Previous reports of this problem

Other users have previously reported this `woocommerce_rest_cannot_view` error in other issues, but the underlying cause has never been obvious:

- #26926
- #28466
- #24533

### PR DESCRIPTION
**Pull request by thejamescollins**
### Submission Review Guidelines:

- I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
- I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
- I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/). 
- Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

1. When deleting an administrator user, and the **Attribute all content to** option is chosen on the WordPress delete user screen, any existing webhook(s) owned by the user being deleted are re-assigned to the other user.
This helps prevent `woocommerce_rest_cannot_view` webhook payload errors that occur after an administrator with existing webhooks is deleted.
2. When deleting an administrator user without the **Attribute all content to** option being chosen on the WordPress delete user screen, any existing webhook(s) owned by the user being deleted are re-assigned to `user_id` zero.
This avoids webhooks from being left in the database with an invalid (non existent) `user_id`.
An admin can edit and re-save each of these webhooks in order to get them to be assigned to a valid user. This is because re-saving a webhook that has user_id=0 causes the webhook ownership to be updated to the currently logged in user.
3. The "Delete users" WordPress page will display a text explaining that the users that are about to be deleted have webhooks assigned, if that's the case.
4. Adds the ability to search for webhooks matching a `user_id` using `WC_Webhook_Data_Store::search_webhooks()` by specifying a `user_id` argument.

Closes #37806.

### How to test the changes in this Pull Request:

For the original issue: follow the **Steps to reproduce** in #37806, however in the last step (step 12), the webhook payload will be a valid order payload rather than a `woocommerce_rest_cannot_view` error.

For the new behavior of the user deletion:

1. Create two administrator users (Users - Add New, select "Administrator" in "Role").
2. Login and create a new webhook (WooCommerce - Settings - Advanced - Webhooks) with each of the newly created users.
3. Go to the users page, check the box for the two newly created users, select "Delete" in the "Bulk actions" dropdown, then click "Apply".

You'll now see a message that warns  about existing webhooks right before the "Confirm Deletion" button:

image

4. Choose the "Delete all content" radio button and click "Confirm Deletion".
5. Verify that the webhooks still exist and have user id 0 assigned. The easiest way is to directly query the database: `wp db query "select name,user_id from wp_wc_webhooks"`
6. Verify that editing and saving one of the webhooks with user id 0 will indeed set the user id of that webhook to the id of the user currently logged in.

If a user doesn't have any content assigned there will be no choice as to what to do with the user content. The webhooks warning will still appear but with a slightly different wording:

image

Testing this isn't straightforwards since a post is created automatically for an user the first time it logs in. You can try creating yet another administrator user, *not* logging in with that user, taking note of its user id (search for `user_id` in the query string of the user edit url in the users page) and manually modifying one of the entries in the `wp_wc_webhooks` table to have that value for `user_id`.

### CODE REVIEW

**Comment by thejamescollins** [comment]
> I wasn't sure what we should do in cases where an administrator user is deleted _without_ the **Attribute all content to** option being chosen.
> 
> In that case we still end up with `wp_wc_webhooks` database records with a `user_id` that is no longer valid, which then causes `woocommerce_rest_cannot_view` payloads whenever data is sent to those webhooks.

I'm very interested if anyone has any feedback on what we could or should do in that case.

Right now, sending a `WP_Error` style payload to the delivery URL is not ideal.

And once webhooks are in existence with a non-existent/invalid `user_id`, there is no easy way for a store owner or administrator to fix them without editing the database directly.

Thanks

**Comment by thejamescollins** [comment]
> I wasn't sure what we should do in cases where an administrator user is deleted _without_ the **Attribute all content to** option being chosen.
> 
> In that case we still end up with `wp_wc_webhooks` database records with a `user_id` that is no longer valid, which then causes `woocommerce_rest_cannot_view` payloads whenever data is sent to those webhooks.


In c56a6d4 I have elected to re-assign those webhooks to `user_id` zero.

This avoids webhooks from being left in the database with an invalid (non existent) `user_id`.

Any admin can edit and re-save each of these webhooks in order to get them to be assigned to a valid user. This is because re-saving a webhook that has `user_id`=`0` causes the webhook ownership to be updated to the currently logged in user.

**Review by Konamiman — CHANGES_REQUESTED** [review]
Hi @om4james, thanks for your contribution. I have a couple of changes to request.

First, [as per our documentation](https://github.com/woocommerce/woocommerce/tree/trunk/plugins/woocommerce/includes#woocommerce-includes-files) (although we can agree that it isn't very easy to find) we try to not put any new code inside the `includes` directory, which we consider as legacy; all new code should go into `src` instead. Thus the `wc_reassign_webhooks_to_new_user_id` function that you created should go into a class in `src` instead of being a function.

I have done that change myself in my local development environment, but I don't have permission to push the changes into your fork of WooCommerce. If you want to [give WooCommerce maintainers push permissions for your fork](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork) I'll push the change.

Second, it would be great if the user deletion confirmation page had a message for users with webhooks assigned, explaining that these will either be assigned user id 0 or the user id of the selected "Attribute all content to" user. This message could be added by using the `delete_user_form` hook. I could do that myself too if you want, or I can leave the fun of doing it for yourself, whatever you prefer. 🙂

So, if you are willing to give me push permissions for your fork I'll be happy to push the first change (and work on the second change too if you want). Thank you!

**Comment by thejamescollins** [comment]
Hi there @Konamiman, thank you for your feedback!

> First, [as per our documentation](https://github.com/woocommerce/woocommerce/tree/trunk/plugins/woocommerce/includes#woocommerce-includes-files) (although we can agree that it isn't very easy to find) we try to not put any new code inside the `includes` directory, which we consider as legacy; all new code should go into `src` instead. Thus the `wc_reassign_webhooks_to_new_user_id` function that you created should go into a class in `src` instead of being a function.

Thanks for pointing that out, I wasn't aware of that policy but it definitely makes sense.

> I have done that change myself in my local development environment, but I don't have permission to push the changes into your fork of WooCommerce. If you want to [give WooCommerce maintainers push permissions for your fork](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork) I'll push the change.

Unfortunately I don't seem to be able to give you permission to push to our fork. I think it's because it's an organization owned fork rather than a user owned fork.

I'm happy for you to contribute and make that change, but I'm not sure of the best way to do so given the organization owned fork limitation. Any suggestions welcome :)
 
> Second, it would be great if the user deletion confirmation page had a message for users with webhooks assigned, explaining that these will either be assigned user id 0 or the user id of the selected "Attribute all content to" user. This message could be added by using the `delete_user_form` hook. I could do that myself too if you want, or I can leave the fun of doing it for yourself, whatever you prefer. 🙂

I like that idea in principle, I think the challenge is that users generally have no idea at all that webhooks are "owned" by a user. Deleting a user and assigning product authorship to a new user is probably easily understood by a user, but warning users of webhook ownership transfer might confuse most users during the deletion process?
If we add a web hook-related message to the `delete_user_form`, then we should probably also do the same thing for products etc too?

At that point I wonder if it may also be out of the scope of this PR then too?

Thanks again for your input and time so far!

**Comment by Konamiman** [comment]
Hi @om4james 

> Unfortunately I don't seem to be able to give you permission to push to our fork. I think it's because it's an organization owned fork rather than a user owned fork.

Ouch. The only alternative I can think of in that case is creating a new fork of WooCommerce in a personal GitHub account, applying the changes there, and submitting a new pull request. Would you be able to do that?

>  I think the challenge is that users generally have no idea at all that webhooks are "owned" by a user (...) but warning users of webhook ownership transfer might confuse most users during the deletion process?

I disagree. We aren't talking about regular users here, but site administrators. They _should_ know what's going on in their server, including the presence of webhooks; and if they don't, then a brief text reminding them of their existence is even more needed! 🙂 The text may also include a link to the webhooks settings page (`/wp-admin/admin.php?page=wc-settings&tab=advanced&section=webhooks`) for even more clarity.

> If we add a web hook-related message to the delete_user_form, then we should probably also do the same thing for products etc too?

Products and the like alre already covered by the regular user deletion behavior that's explained in the user deletion confirmation page (these are either deleted or reassigned), but webhooks are a special case (if "delete content" is selected, these are not deleted but assigned user 0) that deserve a separate notice I think.

**Comment by thejamescollins** [comment]
Hi @Konamiman,

I just invited you to have write access to our https://github.com/OM4/woocommerce-develop fork.

I think this should mean that you can now push to [the branch that this PR is based on](https://github.com/OM4/woocommerce-develop/tree/fix/37806).

Please push your already committed `includes` -> `src` changes to the branch so they are part of this PR.

I'm also more than happy for you to work on and commit/push the UI changes using the `delete_user_form` hook as well. Thank you for offering to handle that.

**Comment by Konamiman** [comment]
@om4james Thanks, indeed now I've been able to push my commit, feel free to take a look if you want. And sure, I'll work on the UI changes.

**Comment by Konamiman** [comment]
@om4james UI changes done. I've assigned a second reviewer from my team for reviewing my own changes. I've also updated the pull request description accordingly.

File: plugins/woocommerce/src/Internal/Utilities/WebhookUtil.php [hunk 1]
```diff
@@ -0,0 +1,136 @@
...
+
+		if ( $users_have_content ) {
+			$text = __( 'If the "Delete all content" option is selected, the affected webhooks will <b>not</b> be deleted and will be attributed to user id 0.<br/>', 'woocommerce' );
+		} else {
+			$text = __( 'The affected webhooks will <b>not</b> be deleted and will be attributed to user id 0.<br/>', 'woocommerce' );
+		}
+
+		$text .= sprintf(
+			/* translators: 1 = url of the WooCommerce webhooks settings page */
+			__( 'After that they can be reassigned to the logged in user by going to the <a href="%1$s">webhooks settings page</a> and re-saving them.', 'woocommerce' ),
```
Comment (thejamescollins) [inline plugins/woocommerce/src/Internal/Utilities/WebhookUtil.php]:
```suggestion
			__( 'After that they can be reassigned to the logged-in user by going to the <a href="%1$s">WooCommerce webhooks settings page</a> and re-saving them.', 'woocommerce' ),
```

- Explain to the user that these are WooCommerce webhooks, as the user doing the deletion may not be working in a WooCommerce context.
- Use correct `logged-in` [phrase](https://english.stackexchange.com/a/11002).

File: plugins/woocommerce/src/Internal/Utilities/WebhookUtil.php [hunk 2]
```diff
@@ -0,0 +1,136 @@
...
+			if ( $wpdb->get_var( "SELECT ID FROM {$wpdb->posts} WHERE post_author IN( " . implode( ',', $userids ) . ' ) LIMIT 1' ) ) {
+				$users_have_content = true;
+			} elseif ( $wpdb->get_var( "SELECT link_id FROM {$wpdb->links} WHERE link_owner IN( " . implode( ',', $userids ) . ' ) LIMIT 1' ) ) {
+				$users_have_content = true;
+			}
+		}
+		// phpcs:enable WooCommerce.Commenting.CommentHooks, WordPress.DB.PreparedSQL.NotPrepared
+
+		if ( $users_have_content ) {
+			$text = __( 'If the "Delete all content" option is selected, the affected webhooks will <b>not</b> be deleted and will be attributed to user id 0.<br/>', 'woocommerce' );
```
Comment (thejamescollins) [inline plugins/woocommerce/src/Internal/Utilities/WebhookUtil.php]:
```suggestion
			$text = __( 'If the "Delete all content" option is selected, the affected WooCommerce webhooks will <b>not</b> be deleted and will be attributed to user id 0.<br/>', 'woocommerce' );
```

- Explains to the user that these are WooCommerce webhooks, as the user doing the deletion may not be working in a WooCommerce context.

File: plugins/woocommerce/src/Internal/Utilities/WebhookUtil.php [hunk 3]
```diff
@@ -0,0 +1,136 @@
...
+		} else {
+			$text = __( 'The affected webhooks will <b>not</b> be deleted and will be attributed to user id 0.<br/>', 'woocommerce' );
```
Comment (thejamescollins) [inline plugins/woocommerce/src/Internal/Utilities/WebhookUtil.php]:
```suggestion
			$text = __( 'The affected WooCommerce webhooks will <b>not</b> be deleted and will be attributed to user id 0.<br/>', 'woocommerce' );
```

- Explains to the user that these are WooCommerce webhooks, as the user doing the deletion may not be working in a WooCommerce context.

File: plugins/woocommerce/src/Internal/Utilities/WebhookUtil.php [hunk 4]
```diff
@@ -0,0 +1,136 @@
...
+		}
+
+		$text .= sprintf(
+			/* translators: 1 = url of the WooCommerce webhooks settings page */
+			__( 'After that they can be reassigned to the logged in user by going to the <a href="%1$s">webhooks settings page</a> and re-saving them.', 'woocommerce' ),
+			$webhooks_settings_url
+		);
+
+		echo '<p>' . esc_html( $text ) . '</p>';
```
Comment (thejamescollins) [inline plugins/woocommerce/src/Internal/Utilities/WebhookUtil.php]:
```suggestion
		echo '<p>' . wp_kses_post( $text ) . '</p>';
```

Ensure bold and the link are output to the page, and not escaped.

Fixes this bug:

Screenshot 2023-05-03 at 9 01 12 am

File: plugins/woocommerce/src/Internal/Utilities/WebhookUtil.php [hunk 5]
```diff
@@ -0,0 +1,136 @@
...
+
+			$user_data      = get_userdata( $user_id );
+			$user_login     = false === $user_data ? '' : $user_data->user_login;
+			$webhooks_count = count( $webhook_ids );
+
+			$text = sprintf(
+				/* translators: 1 = user id, 2 = user login, 3 = webhooks count */
+				_nx(
+					'User #%1$s %2$s has created %3$d webhook.',
+					'User #%1$s %2$s has created %3$d webhooks.',
```
Comment (thejamescollins) [inline plugins/woocommerce/src/Internal/Utilities/WebhookUtil.php]:
```suggestion
					'User #%1$s %2$s has created %3$d WooCommerce webhook.',
					'User #%1$s %2$s has created %3$d WooCommerce webhooks.',
```

- Explains to the user that these are WooCommerce webhooks, as the user doing the deletion may not be working in a WooCommerce context.

**Review by thejamescollins — COMMENTED** [review]
Thank you @Konamiman for improving on my original idea and implementation, it looks great I think.

I have suggested one bug fix, and then also a few minor wording changes for the Delete User UI.

Thanks again.

**Comment by Konamiman** [comment]
@om4james Thanks for the fixes, I could swear the link rendered correctly on my local environment but I must have missed something 🤷🏻‍♂️ I have committed your change suggestions.

File: plugins/woocommerce/src/Internal/Utilities/WebhookUtil.php [hunk 6]
```diff
@@ -0,0 +1,136 @@
...
+namespace Automattic\WooCommerce\Internal\Utilities;
+
+use Automattic\WooCommerce\Internal\Traits\AccessiblePrivateMethods;
+
+/**
+ * Class with utility methods for dealing with webhooks.
+ */
+class WebhookUtil {
+
+	use AccessiblePrivateMethods;
```
Comment (peterfabian) [inline plugins/woocommerce/src/Internal/Utilities/WebhookUtil.php:15]: Side note not affecting the acceptance: Do you think there should be some convention where we briefly document why this is being used and add a reference to our docs or sth like that? I'm just trying to make sure ppl understand the implications etc.

**Review by peterfabian — APPROVED** [review]
The reassignment works fine as described in the instructions, so 👍 from my side. Nice touch with using the WP default UI.

The only note that I have is that it's not apparent that a webhook is assigned to a(ny) user. There's nowhere in the UI that suggests this is the case, so all the user switches are done outside of the UI. Maybe adding username/userid to the webhook UI (either to the list of details) would make sense (not necessarily as part of this PR). I mean, if we're asking users to pick an API version to use for webhooks, we can let them also pick the user whose privileges should be used for the API, no? We already have the UI components in the create REST API key screen.

**Review by Konamiman — APPROVED** [review]

**Comment by thejamescollins** [comment]
Thank you for your help here @Konamiman and @peterfabian 💯
