### PR TITLE
Thank you page (/checkout/order-received): payment gateway title formatting

### LINKED ISSUE #27518: HTML in 'Title' field of Payment method displays as text on /checkout/order-received/
**Describe the bug**
- 'Title' field for a payment method in Woocommerce settings accepts HTML. (e.g. Settings > Payments > Paypal > Title)
- On the Checkout page /checkout/ this HTML displays correctly as 'Payment method'.
- In the Order notification email this HTML displays correctly as 'Payment method'.
- On /checkout/order-received/ this field is displayed twice - the first one renders the HTML but the second one does not. See screenshot. 

**Expected behavior**
HTML should be rendered as HTML, not text. 

**Actual behavior**
HTML is display as text - see screenshot.

Screenshot

**WordPress Environment**
Wordpress 5.5
Woocommerce 4.4.1

### PR DESCRIPTION
**Pull request by barryhughes**
We allow a safe subset of HTML to be used in payment gateway titles but, within the thank-you page, there is a spot where we 'over-escape' things, leading to a broken appearance in some cases.

| Before (Broken) | After (Fixed) |
| --- | --- |
| Screenshot_20230328_124951 | Screenshot_20230328_125011 |

In the above screenshots, we can see how the payment gateway title is displayed twice: once toward the top of the page, and again further down, beside the order items. However, currently, the second of those is fully escaped and so the payment icon does not appear—instead we see the raw HTML for the image tag. 

The screenshot on the right shows how things look with this change. This time, the image is actually rendered.

Closes #27518.

### How to test the changes in this Pull Request:

- [x] Have you followed the [Writing high-quality testing instructions guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions)?

1. Visit **WooCommerce ‣ Settings ‣ Payments** and enable the Direct Bank Transfer gateway. Edit the title so it includes an image tag. Example: `Direct bank transfer ` (and remember to save).
2. As a customer, purchase an item and use the Direct Bank Transfer gateway when doing so.
3. Once you arrive at the thank-you page (the URL will look something like `/checkout/order-received/1234/?key=wc_order_ABC123DEF456`) you should see that your custom payment gateway title, including the image, are successfully rendered in both places, as demonstrated in the second of the screenshots found above.

Please note this change just allows for a safe subset of HTML (including image tags) to be used, it doesn't mean that any old HTML is allowed. Refer to [`HtmlSanitizer::LOW_HTML_BALANCED_TAGS_NO_LINKS`](https://github.com/woocommerce/woocommerce/blob/7.5.1/plugins/woocommerce/src/Internal/Utilities/HtmlSanitizer.php#L13-L32) to see what we allow by default.

### Other information:

-   [x] Have you added an explanation of what your changes do and why you'd like us to include them?
-   [ ] Have you written new tests for your changes, as applicable?
-   [x] Have you created a changelog file for each project being changed, ie `pnpm --filter=<project> changelog add`?
-   [x] Have you included testing instructions?

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

File: plugins/woocommerce/templates/order/order-details.php [hunk 1]
```diff
@@ -83,7 +85,7 @@
 				?>
 					<tr>
 						<th scope="row"><?php echo esc_html( $total['label'] ); ?></th>
-						<td><?php echo ( 'payment_method' === $key ) ? esc_html( $total['value'] ) : wp_kses_post( $total['value'] ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped ?></td>
+						<td><?php echo ( 'payment_method' === $key ) ? wc_get_container()->get( HtmlSanitizer::class )->sanitize( $total['value'] ) : wp_kses_post( $total['value'] ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped ?></td>
```
Comment (vedanshujain) [inline plugins/woocommerce/templates/order/order-details.php]: seems like we should be using `wp_kses_post` here instead of the sanitizer class to be consistent with  the [thankyou page](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/templates/checkout/thankyou.php#L71). HtmlSanitizer is already being run when getting the titime in `abstract-wc-payment-gateway.php`

**Review by vedanshujain — CHANGES_REQUESTED** [review]
Requesting a minor change

File: plugins/woocommerce/templates/order/order-details.php (hunk 1 above)
Comment (barryhughes) [reply plugins/woocommerce/templates/order/order-details.php]: We can, I felt this was better because it matches the allowed range of HTML more closely than does `wp_kses_post()`, but I think you're right (also, I forgot that `HtmlSanitizer` is internal).

Comment (barryhughes) [reply plugins/woocommerce/templates/order/order-details.php]: (Fixed in 3a1fc7744219562faf7ff033e80c0cd8eb38877f)

**Review by vedanshujain — APPROVED** [review]
LGTM!

**Comment by barryhughes** [comment]
Giving the E2E tests another spin ... at first glance the fails seem unrelated:

```
4) [Chrome] › admin-analytics/analytics-overview.spec.js:171:2 › Analytics pages › should allow a user to add a section back in 

Test timeout of 90000ms exceeded while running "afterEach" hook.
```

(This change should not impact analytics screens at all.)
