### PR TITLE
REST API: reject orders endpoint updates against non-shop_order IDs

### LINKED ISSUE #63936: Rest API wc/v3/orders might cause Order Type Change
#### A clear and concise description of what the bug is.

Inadvertently calling POST `wc/v3/orders/123` to update an order where the type is incorrect eg Subscription results into type change from `shop_subscription` to `shop_order`.

To replicate:

* Install WC Subscriptions
* Buy a Subscription - eg ID is 123
* Update the customer note on the subscription but using the orders endpoint `wc/v3/orders/123`

```
(async () => {
	const siteUrl = 'http://localhost:8888/woogenerator/sites/wp-5061114';
	const ck = 'ck_test';
	const cs = 'cs_test';
	const id = 123; // subscription ID

	const url = `${siteUrl}/wp-json/wc/v3/orders/${id}?consumer_key=${encodeURIComponent(ck)}&consumer_secret=${encodeURIComponent(cs)}`;

	const body = {
		customer_note: 'test via wc/v3/orders against subscription id 123',
	};

	const res = await fetch(url, {
		method: 'PUT',
		headers: {
			'Content-Type': 'application/json',
		},
		body: JSON.stringify(body),
	});

	const text = await res.text();

	console.log('HTTP:', res.status);

	try {
		console.log(JSON.parse(text));
	} catch (e) {
		console.log(text);
	}
})();
```

Note that the Subscription turns into an order. Ideally, we should reject the request on type mismatch if ID is a valid number > 0.

Previously, we've seen that this was a result of doing

```
$order = new WC_Order($subsid);
$order->save();
```

And WC Rest API might be doing a similar approach here [https://github.com/woocommerce/woocommerce/blob/d3cced8e2be990e5a77aef3e6fe3953e21b87b64/plugins/woocommerce/includes/rest-api/Controllers/Version3/class-wc-rest-orders-controller.php#L113](<https://github.com/woocommerce/woocommerce/blob/d3cced8e2be990e5a77aef3e6fe3953e21b87b64/plugins/woocommerce/includes/rest-api/Controllers/Version3/class-wc-rest-orders-controller.php#L113>)

For reference - in the support case we investigated - a Zapier workflow was calling /orders endpoint on a Subs ID.

### PR DESCRIPTION
**Pull request by albarin**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

`PUT /wc/v3/orders/{id}` (and the equivalent v2 endpoint) silently converted any non-`shop_order` record (specifically a WooCommerce Subscription) into a regular shop order on save.

This PR adds a single upfront type check in `WC_REST_Orders_V2_Controller::update_item()` that rejects the request when the persisted order type doesn't match `shop_order`. The check mirrors the one [`WC_REST_Orders_V1_Controller::update_item()`](../blob/trunk/plugins/woocommerce/includes/rest-api/Controllers/Version1/class-wc-rest-orders-v1-controller.php#L878) already performs.

**Backwards compatibility note**

The only behavior change is that `PUT /orders/{id}` now returns **400 `woocommerce_rest_shop_order_invalid_id` "ID is invalid."** when the target ID is not a `shop_order`. Previously it returned 200 and silently corrupted the record. `GET`/`DELETE /orders/{id}` and `POST /orders` are unchanged.

Closes #63936

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://developer.woocommerce.com/docs/contribution/testing/writing-high-quality-testing-instructions/), include your detailed testing instructions:

**Prerequisites**

- WordPress install with WooCommerce (this branch) and **WooCommerce Subscriptions** active.
- A REST API key with read/write permissions (WP Admin → WooCommerce → Settings → Advanced → REST API).

**Set up a subscription to target**

1. Create a Simple Subscription product (WP Admin → Products → Add New → set Product data to "Simple subscription").
2. Place an order for it from the front-end, or create one via WP Admin → WooCommerce → Subscriptions → Add Subscription.
3. Note the Subscription ID and confirm:
   ```sh
   wp post get <SUB_ID> --field=post_type
   # Expected: shop_subscription
   ```

**Verify the fix on this branch**

4. Send a PUT against the subscription ID:
   ```sh
   curl -i -X PUT \
     -u 'ck_xxx:cs_xxx' \
     -H 'Content-Type: application/json' \
     -d '{"customer_note":"test via wc/v3/orders against subscription"}' \
     'https://your-site.local/wp-json/wc/v3/orders/<SUB_ID>'
   ```
5. Confirm the response is HTTP `400` with body `{"code":"woocommerce_rest_shop_order_invalid_id","message":"ID is invalid.","data":{"status":400}}`.
6. Confirm the subscription is unchanged:
   ```sh
   wp post get <SUB_ID> --field=post_type
   # Expected: shop_subscription
   ```
7. Confirm the subscription still appears in WP Admin → WooCommerce → Subscriptions.

**Verify the bug on trunk (optional)**

8. Check out trunk and re-run the same `curl` against a fresh subscription. Expected (buggy) result: HTTP `200` with a regular order JSON, `wp post get` now returns `shop_order`, and the subscription has disappeared from the Subscriptions list and now shows in WP Admin → Orders.

Repeat the tests, but for the `v2` route.

### Testing that has already taken place:

- 3 new PHPUnit tests in `WC_REST_Orders_Controller_Tests`, all running against both CPT and HPOS data stores via the inherited `OrdersTableDataStoreRestOrdersControllerTests`:
  - `test_update_rejects_non_shop_order_post_type` — PUT against a custom order type ID returns 400, post type unchanged, request body not applied.
  - `test_update_rejects_nonexistent_id` — PUT against `999999999` returns 400.
  - `test_update_shop_order_passes_type_guard_and_applies_changes` — PUT against a real `shop_order` still returns 200 and applies the change.
- Manual repro on a Local site with WooCommerce Subscriptions confirmed: trunk converts the subscription, this branch returns 400 and leaves the subscription intact.

### Milestone

- [x] Automatically assign milestone for the **[next WooCommerce version](../blob/trunk/plugins/woocommerce/woocommerce.php#L6)**

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message

REST API: prevent PUT /wc/v(2|3)/orders/{id} from converting non-shop_order records into orders.

</details>

### CODE REVIEW

**Review by prettyboymp — APPROVED** [review]
Looks good — clean, well-targeted fix. The type guard correctly mirrors the existing V1 pattern, works for both CPT and HPOS, and V3 inherits it automatically.

Verified locally against V2 and V3 endpoints: valid orders return 200, non-shop_order IDs and non-existent IDs correctly return 400.

File: plugins/woocommerce/tests/php/includes/rest-api/Controllers/Version3/class-wc-rest-orders-controller-tests.php [hunk 1]
```diff
@@ -317,6 +317,70 @@ public function test_order_empty_created_via_param_is_set_to_rest_api() {
...
+	public function test_update_rejects_non_shop_order_post_type(): void {
+		wc_register_order_type( 'shop_test' );
+		$post_id = wp_insert_post(
+			array(
+				'post_type'   => 'shop_test',
+				'post_status' => 'wc-pending',
+				'post_title'  => 'test',
+			)
+		);
+
```
Comment (nerrad) [inline plugins/woocommerce/tests/php/includes/rest-api/Controllers/Version3/class-wc-rest-orders-controller-tests.php:333]: * The test coverage is only against custom post type implementation of orders and does not cover HPOS (`wc_orders`).

File: plugins/woocommerce/tests/php/includes/rest-api/Controllers/Version3/class-wc-rest-orders-controller-tests.php [hunk 2]
```diff
@@ -317,6 +317,70 @@ public function test_order_empty_created_via_param_is_set_to_rest_api() {
...
+		$this->assertSame( 400, $response->get_status() );
+		$this->assertArrayHasKey( 'code', $data );
+		$this->assertSame( 'woocommerce_rest_shop_order_invalid_id', $data['code'] );
+
+		// The persisted record must be untouched: same post type, no added customer_note.
+		$this->assertSame( 'shop_test', get_post_type( $post_id ) );
+		$this->assertSame( '', (string) get_post_meta( $post_id, '_customer_note', true ) );
+
+		unregister_post_type( 'shop_test' );
```
Comment (nerrad) [inline plugins/woocommerce/tests/php/includes/rest-api/Controllers/Version3/class-wc-rest-orders-controller-tests.php:348]: Minor, but it looks like if any assertion before this line fails, `shop_test` remains regisered globally and can contaminate later tests in the same process? I haven't searched more throughly to see if there are global post type cleanups in any `teardown` to verify.

**Review by nerrad — COMMENTED** [review]
@albarin - I stumbled on this PR when it a customer issue was brought up in Slack and just happened to notice a couple things that might need followed up on.

**Comment by albarin** [comment]
> @albarin - I stumbled on this PR when it a customer issue was brought up in Slack and just happened to notice a couple things that might need followed up on.

Thanks @nerrad , I've created a follow up PR https://github.com/woocommerce/woocommerce/pull/64506
