### PR TITLE
[COT] Log errors during the posts to orders table migrations

### LINKED ISSUE #32664: [COT] Implement error logging during migrations
During migrations, we may encounter errors in inserting new records because of mismatched data types, values exceeding allowed length, etc.

We need to log these errors properly as they happen during migrations. This issue scopes logging these errors, we will create a different issue to track mitigations for failed order migrations.

### PR DESCRIPTION
**Pull request by Konamiman**
### All Submissions:

-   [ ] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
-   [ ] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
-   [ ] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Implement logging for errors that happen during the execution of `PostsToOrdersMigrationController::migrate_orders`. The following types of errors are logged:

1. Unhandled exceptions.
2. Database errors caused by `$wpdb->query` and `$wpdb->get_results`.
3. Not enough rows processed after an insert or update operation.
4. Validation errors on the data to be migrated.

Errors are logged using the standard WooCommerce logger, using `posts-to-orders-migration` as the source name.

Closes #32664.

### How to test the changes in this Pull Request:

First, enable the feature by adding the following code snippet somewhere, for example at the end of `woocommerce.php`:

```php
wc_get_container()
   ->get('Automattic\WooCommerce\Internal\DataStores\Orders\CustomOrdersTableController')
   ->show_feature();
```

Then force errors of each type, then go to WooCommerce - Status - Logs and verify that the errors are properly logged.

One way to force errors is to to temporarily modify the code as follows (don't try more than one at the same time tas it would get confusing):

1. In `TableMigrator::process_migration_batch_for_ids`, right before the first statement of the `try` block, add this: `throw new \Exception("Ouch!!");`
2. In `TableMigrator::db_query`, right before the `return` statement, add this: `$this->add_error('Gasp!!');` (also in `db_get_results`)
3. In `TableMigrator::maybe_add_insert_or_update_mismatch_error`, right after `$count` is calculated increase it by one.
4. In `MetaToCustomTableMigrator::validate_data`, add this right before the first line of the method: `return new \WP_Error('Argh!!');`

Feel free to use other (probably more proper) ways to force errors. For example you could temporarily remove or rename the `wp_wc_orders` table.

### Other information:

-   [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
-   [ ] Have you written new tests for your changes, as applicable?
-   [ ] Have you successfully run tests with your changes locally?
-   [ ] Have you created a changelog file for each project being changed, ie `pnpm nx changelog <project>`?

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

**Comment by botwoo** [comment]
:bar_chart: Test reports for this pull request have been published and are accessible through the following links:

- [REST API Test Report](https://woocommerce.github.io/woocommerce-test-reports/pr/33034/api/)
- E2E Test Report (TBC)

Latest commit referenced in the reports: `Move the base table migration classes outside CustomOrderTable directory` 71e0fd92d60d11a773b3123836e01a03bc34893d
This comment will automatically be updated with the latest referenced commit when you push new changes to this pull request.

---

_Visit the [WooCommerce Test Reports](https://woocommerce.github.io/woocommerce-test-reports) homepage to view all published reports. See the [FAQs](https://github.com/woocommerce/woocommerce-test-reports/wiki/FAQs) page if you're having problems accessing them._

File: plugins/woocommerce/src/Database/Migrations/CustomOrderTable/MetaToCustomTableMigrator.php [hunk 1]
```diff
@@ -224,21 +216,23 @@ protected function generate_column_clauses( array $columns_schema, array $batch
 	}
 
 	/**
-	 * Process next migration batch, uses option `wc_cot_migration` to checkpoints of what have been processed so far.
+	 * Migrate a batch of orders from the posts table to the corresponding table.
 	 *
-	 * @param array $entity_ids List of entity IDs to perform migrations for.
+	 * @param array $entity_ids Ids of orders ro migrate.
```
Comment (vedanshujain) [inline plugins/woocommerce/src/Database/Migrations/CustomOrderTable/MetaToCustomTableMigrator.php]: typo  `ro` -> `to`
```suggestion
	 * @param array $entity_ids Ids of entities to migrate.
```

File: plugins/woocommerce/src/Database/Migrations/CustomOrderTable/MetaToCustomTableMigrator.php [hunk 2]
```diff
@@ -224,21 +216,23 @@ protected function generate_column_clauses( array $columns_schema, array $batch
 	}
 
 	/**
-	 * Process next migration batch, uses option `wc_cot_migration` to checkpoints of what have been processed so far.
+	 * Migrate a batch of orders from the posts table to the corresponding table.
```
Comment (vedanshujain) [inline plugins/woocommerce/src/Database/Migrations/CustomOrderTable/MetaToCustomTableMigrator.php]: suggestion to use `entities` instead of orders since this class (along with MetaToMetaTableMigrator) are generic, and they can migrate any entity (product, coupon, booking, etc) from the posts table and not just orders. On that note, we should also move them out of the `CustomOrderTable` folder.

File: plugins/woocommerce/src/Utilities/ArrayUtil.php [hunk 3]
```diff
@@ -67,5 +67,48 @@ public static function is_truthy( array $array, string $key ) {
...
+	 * Source: https://stackoverflow.com/a/34254663/4574
+	 *
+	 * @param array     $items    An array (in any order, see $sort) of individual numbers.
+	 * @param string    $item_separator  The string that separates sequential range groups.  Defaults to ', '.
+	 * @param string    $range_separator The string that separates ranges.  Defaults to '-'.  A plausible example otherwise would be ' to '.
+	 * @param bool|true $sort     Sort the array prior to iterating?  You'll likely always want to sort, but if not, you can set this to false.
+	 *
+	 * @return string
+	 */
+	public static function to_ranges_string( array $items, string $item_separator = ', ', string $range_separator = '-', bool $sort = true ): string {
```
Comment (vedanshujain) [inline plugins/woocommerce/src/Utilities/ArrayUtil.php:83]: nice

File: plugins/woocommerce/src/Database/Migrations/CustomOrderTable/PostsToOrdersMigrationController.php [hunk 4]
```diff
@@ -18,86 +19,102 @@ class PostsToOrdersMigrationController {
...
+
+		$this->all_migrators = array(
+			$order_table_migrator,
+			$billing_address_table_migrator,
+			$shipping_address_table_migrator,
+			$operation_data_table_migrator,
+			$meta_table_migrator,
+		);
+
+		$this->error_logger = wc_get_logger();
```
Comment (vedanshujain) [inline plugins/woocommerce/src/Database/Migrations/CustomOrderTable/PostsToOrdersMigrationController.php:61]: we can remove the `MigrationErrorLogger` if we are not going to use it

**Review by vedanshujain — COMMENTED** [review]
Looks good to me. I have added some minor suggestions. Other than those, I was wondering if we can add some tests for the logger as well? For example, we can delete tables and execute the migration to see what will come in logs.

**Review by vedanshujain — APPROVED** [review]

**Comment by Konamiman** [comment]
Changelog file added in https://github.com/woocommerce/woocommerce/pull/33136
