### PR TITLE
Catch fatals when loading cart and correctly handle sold individually items.

### LINKED ISSUE #54352: [Fatal] PHP Fatal error: Uncaught Automattic\WooCommerce\StoreApi\Exceptions\RouteException: The quantity of &quot;Fenix7&quot; cannot be changed in | CartController.php:238
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

This issue will be resolved in pull request #53316

witnessed in `9.5.1`

[link to code](https://github.com/woocommerce/woocommerce/blob/574ebef60ae6dc4989dceef1844fef2e7c616444/plugins/woocommerce/src/StoreApi/Utilities/CartController.php#L238)

```
PHP Fatal error:  Uncaught Automattic\WooCommerce\StoreApi\Exceptions\RouteException: The quantity of &quot;Fenix7&quot; cannot be changed in /../plugins/woocommerce/9.5.1/src/StoreApi/Utilities/CartController.php:238
Stack trace:
#0 /../plugins/woocommerce/9.5.1/src/StoreApi/Utilities/CartController.php(52): Automattic\WooCommerce\StoreApi\Utilities\CartController->set_cart_item_quantity('86f6596d0664653...', 1)
#1 /../plugins/woocommerce/9.5.1/src/StoreApi/Routes/V1/AbstractCartRoute.php(180): Automattic\WooCommerce\StoreApi\Utilities\CartController->normalize_cart()
#2 /../plugins/woocommerce/9.5.1/src/StoreApi/Routes/V1/AbstractCartRoute.php(114): Automattic\WooCommerce\StoreApi\Routes\V1\AbstractCartRoute->load_cart_session(Object(WP_REST_Request))
#3 /../core/6.7.1/wp-includes/rest-api/class-wp-rest-server.php(1292): Automattic\WooCommerce\StoreApi\Routes\V1\AbstractCartRoute->get_response(Object(WP_REST_Request))
#4 /../core/6.7.1/wp-includes/rest-api/class-wp-rest-server.php(1125): WP_REST_Server->respond_to_request(Object(WP_REST_Request), '/wc/store/v1/ca...', Array, NULL)
#5 /../core/6.7.1/wp-includes/rest-api/class-wp-rest-server.php(439): WP_REST_Server->dispatch(Object(WP_REST_Request))
#6 /../core/6.7.1/wp-includes/rest-api.php(449): WP_REST_Server->serve_request('/wc/store/v1/ca...')
#7 /../core/6.7.1/wp-includes/class-wp-hook.php(324): rest_api_loaded(Object(WP))
#8 /../core/6.7.1/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)
#9 /../core/6.7.1/wp-includes/plugin.php(565): WP_Hook->do_action(Array)
#10 /../core/6.7.1/wp-includes/class-wp.php(418): do_action_ref_array('parse_request', Array)
#11 /../core/6.7.1/wp-includes/class-wp.php(813): WP->parse_request('')
#12 /../core/6.7.1/wp-includes/functions.php(1336): WP->main('')
#13 /../core/6.7.1/wp-blog-header.php(16): wp()
#14 /../core/6.7.1/index.php(17): require('/../core...')
#15 {main}
  thrown in /../plugins/woocommerce/9.5.1/src/StoreApi/Utilities/CartController.php on line 238
``` 

### Expected behavior

No fatals witnessed

### Actual behavior

Fatals witnessed

### Steps to reproduce

N/A. 126 fatals witnessed on Jan 3, 2025 across 6 sites

### WordPress Environment

N/A

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

### LINKED ISSUE #55962: [Fatal] PHP Fatal error: Uncaught Automattic\WooCommerce\StoreApi\Exceptions\RouteException: The quantity of * cannot be changed in | CartController.php:238
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Witnessed in `9.6.2`

[link to code](https://github.com/woocommerce/woocommerce/blob/10aa8d876b76e5a70113461ce924e7282e2bfc0f/plugins/woocommerce/src/StoreApi/Utilities/CartController.php#L238)

```
PHP Fatal error:  Uncaught Automattic\WooCommerce\StoreApi\Exceptions\RouteException: The quantity of &quot;The Midderlands - Swords & Wizardry Complete Cheat Sheets&quot; cannot be changed in /../plugins/woocommerce/9.6.2/src/StoreApi/Utilities/CartController.php:238
Stack trace:
#0 /../plugins/woocommerce/9.6.2/src/StoreApi/Utilities/CartController.php(52): Automattic\WooCommerce\StoreApi\Utilities\CartController->set_cart_item_quantity('cb1b0adbdade7ef...', 1)
#1 /../plugins/woocommerce/9.6.2/src/StoreApi/Routes/V1/AbstractCartRoute.php(180): Automattic\WooCommerce\StoreApi\Utilities\CartController->normalize_cart()
#2 /../plugins/woocommerce/9.6.2/src/StoreApi/Routes/V1/AbstractCartRoute.php(114): Automattic\WooCommerce\StoreApi\Routes\V1\AbstractCartRoute->load_cart_session(Object(WP_REST_Request))
#3 /../core/6.7.2/wp-includes/rest-api/class-wp-rest-server.php(1292): Automattic\WooCommerce\StoreApi\Routes\V1\AbstractCartRoute->get_response(Object(WP_REST_Request))
#4 /../core/6.7.2/wp-includes/rest-api/class-wp-rest-server.php(1125): WP_REST_Server->respond_to_request(Object(WP_REST_Request), '/wc/store/cart', Array, NULL)
#5 /../core/6.7.2/wp-includes/rest-api/class-wp-rest-server.php(439): WP_REST_Server->dispatch(Object(WP_REST_Request))
#6 /../core/6.7.2/wp-includes/rest-api.php(449): WP_REST_Server->serve_request('/wc/store/cart')
#7 /../core/6.7.2/wp-includes/class-wp-hook.php(324): rest_api_loaded(Object(WP))
#8 /../core/6.7.2/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)
#9 /../core/6.7.2/wp-includes/plugin.php(565): WP_Hook->do_action(Array)
#10 /../core/6.7.2/wp-includes/class-wp.php(418): do_action_ref_array('parse_request', Array)
#11 /../core/6.7.2/wp-includes/class-wp.php(813): WP->parse_request('')
#12 /../core/6.7.2/wp-includes/functions.php(1336): WP->main('')
#13 /../core/6.7.2/wp-blog-header.php(16): wp()
#14 /../core/6.7.2/index.php(17): require('/../core...')
#15 {main}
  thrown in /../plugins/woocommerce/9.6.2/src/StoreApi/Utilities/CartController.php on line 238
``` 

### Expected behavior

No fatals expected

### Actual behavior

Fatals were witnessed

### Steps to reproduce

We don't have steps to reproduce, but observed 48 instances of this problem on Fri Feb 21, 2025 across 3 sites. Hopefully, someone can dig in and apply a defensive check if appropriate. - To be updated after investigation.

### WordPress Environment

N/A

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

### LINKED ISSUE #56130: Checking out with 2 items of the same sold individually product breaks Checkout
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Items that are sold individually that are added twice to Checkout would break Checkout.

### Expected behavior

Checkout should surface a warning and correct the quantity instead of breaking.

### Actual behavior

Checkout shows an error and any changes you do to Checkout would throw a fatal.

### Steps to reproduce

1. Add an item twice to your cart.
2. Edit the item so it's sold individually.
3. Go to Checkout, notice an error telling you to reduce quantity.
4. Try typing an email or changing shipping, it should throw a fatal.

### WordPress Environment

WC 8.8

### Isolating the problem

- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by senadir**
This PR fixes32 issues in one PR, those issues. Those issues are closely related:

### Cart can't normalize a sold individually product with quantity more than 1.
Cart would fail to normalize a sold individually product who has 2 in cart, and it would result in a fatal from further checks down the road.

### Store API being initialized in the editor
A recent PR made Store API get initialized and registered in the editor, we don't have valid use cases for Store API in the editor but hooking into `rest_api_init` and initiating cart would cause that, it would also surface any fatals (from issue 1) into the admin screen and can block it. This PR gates against that.

### Fatals and exceptions thrown by cart are not caught
Cart initialization with 2 items would throw a exception, that exception should never be reached, but due to issue 1, it was reached. Regardless, uncaught exceptions shouldn't exist, this PR catches them.

### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

closes https://github.com/woocommerce/woocommerce/issues/54352
closes https://github.com/woocommerce/woocommerce/issues/56130
closes https://github.com/woocommerce/woocommerce/issues/55962
(For Bug Fixes) Bug introduced in PR https://github.com/woocommerce/woocommerce/pull/55299

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Add an item to cart twice.
2. Modify said item to be sold individually.
3. Go to Checkout, you should see the error about the quantity (that's valid).
4. Change shipping or apply an address, quantity should be fixed.

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

Fix a bug in which having 2x of a sold individually item in cart would throw a fatal.

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce/src/Blocks/Domain/Bootstrap.php [hunk 1]
```diff
@@ -137,8 +137,12 @@ function () {
 		$is_rest              = wc()->is_rest_api_request();
 		$is_store_api_request = wc()->is_store_api_request();
 
+		// Initialize Store API in non-admin context.
+		if ( ! is_admin() ) {
+			$this->container->get( StoreApi::class )->init();
+		}
```
Comment (nielslange) [inline plugins/woocommerce/src/Blocks/Domain/Bootstrap.php:143]: Nice improvement! 👏

**Review by nielslange — APPROVED** [review]
Thanks for working on this, @senadir. I've successfully tested the PR and the code changes look good.
