### PR TITLE
Remove Add to Cart + Options template part from block inserter

### LINKED ISSUE #59288: Add to Cart + Options template part shouldn't appear in the inserter in the Site Editor
Similar to [https://github.com/woocommerce/woocommerce/issues/43316](https://github.com/woocommerce/woocommerce/issues/43316) but for the *Add to Cart + Options*.

The *Add to Cart + Options* template part area shouldn't appear in the inserter.

## **To Reproduce**

1. Go to *Appearance* > *Editor* > *Templates* and open any template.
2. Open the inserter and search for *Add to cart*.
3. Notice the *Add to Cart + Options* template part area is in the list.

## **Expected behavior**

The *Add to Cart + Options* template part area shouldn't be available from the inserter, as it's only intended to be used inside the *Add to Cart + Options* block.

### PR DESCRIPTION
**Pull request by AhmarZaidi**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

This PR removes the Add to Cart + Options template part area from the block inserter by conditionally filtering it's block variation in the `Add to Cart + Options (Beta)` block using the variation name `area_add-to-cart-with-option`.

Closes #59288 

### Screenshots or screen recordings:

https://github.com/user-attachments/assets/e8927460-62d5-46fc-aec5-a70ed4f37c7a

| Before | After |
| ------ | ----- |
| image | image |

### How to test the changes in this Pull Request:

1. Go to Appearance > Editor > Templates and open any template.
2. Open the inserter and search for Add to cart.
3. Notice the Add to Cart + Options template part area is not in the list.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

**Comment by AhmarZaidi** [comment]
Thanks @Aljullu for the helpful comment which was essential in solving this issue: https://github.com/woocommerce/woocommerce/issues/59288#issuecomment-3047772424

File: plugins/woocommerce/client/blocks/assets/js/blocks/add-to-cart-with-options/index.tsx [hunk 1]
```diff
@@ -45,3 +46,28 @@ registerProductBlockType< Attributes >(
...
+addFilter(
+	'blocks.registerBlockType',
+	'woocommerce/area_add-to-cart-with-options',
+	function ( blockSettings, blockName ) {
+		if ( blockName === 'core/template-part' ) {
+			return {
+				...blockSettings,
+				variations: blockSettings.variations.map(
+					( variation: { name: string } ) => {
+						if ( variation.name === 'area_add-to-cart-with-options' ) {
```
Comment (Aljullu) [inline plugins/woocommerce/client/blocks/assets/js/blocks/add-to-cart-with-options/index.tsx]: Apparently there is a linting error here. You should be able to run lint locally by running:

```
pnpm --filter=@woocommerce/plugin-woocommerce lint
```

**Review by Aljullu — COMMENTED** [review]
Thanks for opening this PR, @AhmarZaidi! Overall looking good, but there seems to be a [linting error](https://github.com/woocommerce/woocommerce/actions/runs/16138499462/job/45554092760?pr=59501) that will need to be fixed. I commented it inline below: :point_down:

File: plugins/woocommerce/client/blocks/assets/js/blocks/add-to-cart-with-options/index.tsx (hunk 1 above)
Comment (AhmarZaidi) [reply plugins/woocommerce/client/blocks/assets/js/blocks/add-to-cart-with-options/index.tsx]: Fixed.

**Review by Aljullu — APPROVED** [review]
Thanks for picking this up, @AhmarZaidi! Really happy to see this being solved, as it was clearly a cause of confusion for our users.

It tested the post editor and the Site Editor and confirmed the _Add to Cart + Options_ template part isn't available in the inserter.

Before | After
--- | ---
imatge | imatge


<details>
<summary>Testing environment</summary>

* WordPress 6.8.1 local dev environment
* Plugins: WooCommerce Beta Tester
* Theme: Woo Starter Theme
* Store creation: June 2025
* Store size: small
</details>
