### PR TITLE
Store API: Reduced number of recalculations on Store API cart routes

### LINKED ISSUE #47296: Store API  - AbstractCartRoute uses previous data when calculates the totals
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

We have a plugin that adjusts prices based on quantity (tiered pricing table for woocommerce)

We have successfully utilized the "woocommerce_before_calculate_totals" for years to set new prices for cart items.
We pull "quantity" from the cart item, calculate a new price, and set it directly to the WC_Product instance via $cart_item['data'], so WC_Cart_Totals can calculate totals based on the new price.

### Expected behavior

It works perfectly with the old cart and checkout.
However, the new Store API endpoints do not use the latest cart item data, causing a big problem during calculations.

It triggers cart_controller->calculate_totals(), which is fine, but it loads the cart from the session -> calculates prices, and then updates the cart in the session with the new quantity. This means the "woocommerce_before_calculate_totals" hook (and all others during the calculations) uses $cart_item with the previous data.
We get the outdated $cart_item['quantity'] and cannot correctly calculate the new price. I believe this could also affect other plugins.

I hope this makes sense and can be fixed in the subsequent WooCommerce release.

Thank you 

### Actual behavior

So, your logic is the following: 
1. You get a request to update the cart item
2. You load the cart instance from the session (but it does not include updated quantity)
3. You trigger cart_controller->calculate_totals() with the wrong quantity (it works fine for default WooCommerce because  the new cart block actually calculates totals using JS on the frontend; it uses only cart item price, which is not changed)
4. You update the cart with the new quantity and store it in the session.

### Steps to reproduce

Try to use "woocommerce_before_calculate_totals" hook to get cart item quantity

### WordPress Environment

Default WooCommerce setup

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by mikejolley**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

This is an attempt to reduce the number of calculations that are run on Store API cart endpoints by:

- Loading only cart item data when hitting the API
- Recalculating before returning the response, but not before generation
- Avoiding duplicate shipping calculation calls (since the main calculation method handles it)

Most events such as adding items or removing coupons trigger a recalculation automatically so there is no need to do it manually from Store API.

Closes #47296

### How to test the changes in this Pull Request:

Test suites should cover API routes. You should test the full checkout flow to spot regressions, taking note of displayed totals when adding and removing items from cart, applying coupons, and changing shipping methods.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

**Review by nielslange — APPROVED** [review]
Thanks for working on this, @mikejolley. I've successfully tested the PR and the code looks good. Let's ⛴️ this improvement.

File: plugins/woocommerce/src/StoreApi/Utilities/CartController.php [hunk 1]
```diff
@@ -27,20 +26,40 @@ class CartController {
...
+	 * @since 9.2.0 Calculate shipping was removed here because it's called already by calculate_totals.
+	 *
+	 * @return \WC_Cart
 	 */
 	public function calculate_totals() {
 		$cart = $this->get_cart_instance();
 		$cart->get_cart();
 		$cart->calculate_fees();
-		$cart->calculate_shipping();
 		$cart->calculate_totals();
```
Comment (senadir) [inline plugins/woocommerce/src/StoreApi/Utilities/CartController.php:61]: In my testing, leaving everything as is and just removing this reduced the amount of totals calculation while keeping other thing correct.
