### PR TITLE
Fix TypeScript errors in Marketing pages

### LINKED ISSUE #54484: `plugins/woocommerce/client/admin/client/marketing`
Part of https://github.com/woocommerce/woocommerce/issues/53939.

After updating the admin area to React 18, a bunch of TypeScript errors show up in the Marketing pages. We want to fix them in this issue.

### PR DESCRIPTION
**Pull request by ecgan**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes https://github.com/woocommerce/woocommerce/issues/54484. See parent issue https://github.com/woocommerce/woocommerce/issues/53939 for more background details.

In this PR, we fix TypeScript errors that are related to the Marketing pages. The errors came up after updating the admin area to React 18.

This PR also fixes missing type for `getPluginInstallState` selector in `@woocommerce/data` package.

#### Functionality test

There should be no functionality change in this PR. Perform smoke test on the Marketing pages and make sure they are still working as expected.

- Marketing > Overview page (`/wp-admin/admin.php?page=wc-admin&path=%2Fmarketing`)
- Marketing > Coupons page (`/wp-admin/edit.php?post_type=shop_coupon`)

#### Code test

1. Go to `./plugins/woocommerce/client/admin`, and then run `pnpm ts:check`. There should be a bunch of errors. None of them should be related to Marketing pages (i.e. files under `./plugins/woocommerce/client/admin/client/marketing`).

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

**Review by retrofox — COMMENTED** [review]
While reviewing the code, my first comment is why we use CamelCase for folders and files 😅 I think it's a very uncommon naming convention.

File: plugins/woocommerce/client/admin/client/marketing/components/PluginCardBody/SmartPluginCardBody.tsx [hunk 1]
```diff
@@ -40,8 +39,18 @@ export const SmartPluginCardBody = ( {
 		null
 	);
 	const { installAndActivatePlugins } = useDispatch( PLUGINS_STORE_NAME );
-	const { isPluginInstalledNotActivated } =
-		useIsPluginInstalledNotActivated();
+	const { installState } = useSelect(
```
Comment (retrofox) [inline plugins/woocommerce/client/admin/client/marketing/components/PluginCardBody/SmartPluginCardBody.tsx:42]: This seems to not only be about TS issues. I'm not sure how to test these changes. Do you have any advice?

Comment (retrofox) [reply plugins/woocommerce/client/admin/client/marketing/components/PluginCardBody/SmartPluginCardBody.tsx:42]: I've already found
image

Comment (retrofox) [reply plugins/woocommerce/client/admin/client/marketing/components/PluginCardBody/SmartPluginCardBody.tsx:42]: minor suggestion: instead of returning an object, why not simply return the `initialState` string?

```es6
	const installState = useSelect(
		( select ) => {
			const { getPluginInstallState } = select(
				PLUGINS_STORE_NAME
			) as PluginSelectors;

			return getPluginInstallState( plugin.product );
		},
		[ plugin.product ]
	);
```

File: plugins/woocommerce/client/admin/client/marketing/components/PluginCardBody/SmartPluginCardBody.tsx [hunk 2]
```diff
@@ -76,7 +85,12 @@ export const SmartPluginCardBody = ( {
 	const renderButton = () => {
 		const buttonDisabled = !! currentPlugin;
 
-		if ( isPluginInstalledNotActivated( plugin.product ) ) {
+		/**
+		 * When the plugin is installed but not activated yet.
+		 */
+		const isPluginInstalledNotActivated = installState === 'installed';
+
+		if ( isPluginInstalledNotActivated ) {
```
Comment (retrofox) [inline plugins/woocommerce/client/admin/client/marketing/components/PluginCardBody/SmartPluginCardBody.tsx:93]: I think we can avoid creating a const here:

```suggestion
		if ( installState === 'installed' ) {
```

File: plugins/woocommerce/client/admin/client/marketing/data-multichannel/selectors.ts [hunk 3]
```diff
@@ -1,3 +1,8 @@
+/**
+ * External dependencies
+ */
+import { WPDataSelector, WPDataSelectors } from '@woocommerce/data';
```
Comment (retrofox) [inline plugins/woocommerce/client/admin/client/marketing/data-multichannel/selectors.ts]: We can explicitly import the type:

```suggestion
import type { WPDataSelector, WPDataSelectors } from '@woocommerce/data';
```

File: plugins/woocommerce/client/admin/client/marketing/data/index.js [hunk 4]
```diff
@@ -13,10 +13,12 @@ import * as selectors from './selectors';
 import * as resolvers from './resolvers';
 import reducer from './reducer';
 
-registerStore( STORE_KEY, {
+export const store = createReduxStore( STORE_KEY, {
```
Comment (retrofox) [inline plugins/woocommerce/client/admin/client/marketing/data/index.js:16]: Excellent! <3

File: plugins/woocommerce/client/admin/client/marketing/hooks/useInstalledPluginsWithoutChannels.ts [hunk 5]
```diff
@@ -7,7 +7,7 @@ import { chain } from 'lodash';
 /**
  * Internal dependencies
  */
-import { STORE_KEY } from '~/marketing/data/constants';
+import { store } from '~/marketing/data';
```
Comment (retrofox) [inline plugins/woocommerce/client/admin/client/marketing/hooks/useInstalledPluginsWithoutChannels.ts]: Usually, especially in core, it's common to use an alias here

```suggestion
import { store as marketingStore } from '~/marketing/data';
```

You will have to update the references below

File: plugins/woocommerce/client/admin/client/marketing/components/PluginCardBody/SmartPluginCardBody.tsx [hunk 6]
```diff
@@ -2,12 +2,12 @@
...
  */
 import { useState } from '@wordpress/element';
-import { useDispatch } from '@wordpress/data';
+import { useDispatch, useSelect } from '@wordpress/data';
 import { Button } from '@wordpress/components';
 import { Pill } from '@woocommerce/components';
 import { __ } from '@wordpress/i18n';
 import { recordEvent } from '@woocommerce/tracks';
-import { PLUGINS_STORE_NAME } from '@woocommerce/data';
+import { PLUGINS_STORE_NAME, PluginSelectors } from '@woocommerce/data';
```
Comment (retrofox) [inline plugins/woocommerce/client/admin/client/marketing/components/PluginCardBody/SmartPluginCardBody.tsx]: we could explicitly import the type
```suggestion
import { PLUGINS_STORE_NAME, type PluginSelectors } from '@woocommerce/data';
```

File: plugins/woocommerce/client/admin/client/marketing/components/PluginCardBody/SmartPluginCardBody.tsx (hunk 2 above)
Comment (ecgan) [reply plugins/woocommerce/client/admin/client/marketing/components/PluginCardBody/SmartPluginCardBody.tsx:93]: If we use `if ( installState === 'installed' )`, it may not be immediately clear to developers that it means "installed but not yet activated". Developers may think that "activated plugins are installed, so using `installState === 'installed'` would also include activated plugins", but that's not the case. 

That's the reason why I came up with the constant with a code comment, to make it clearer.

What do you think? Does this make sense?

File: plugins/woocommerce/client/admin/client/marketing/components/PluginCardBody/SmartPluginCardBody.tsx (hunk 6 above)
Comment (ecgan) [reply plugins/woocommerce/client/admin/client/marketing/components/PluginCardBody/SmartPluginCardBody.tsx]: Done in [`82bbd9e` (#54485)](https://github.com/woocommerce/woocommerce/pull/54485/commits/82bbd9e5d1bb5324d16e620aec840ade52d03c0c).

File: plugins/woocommerce/client/admin/client/marketing/hooks/useInstalledPluginsWithoutChannels.ts (hunk 5 above)
Comment (ecgan) [reply plugins/woocommerce/client/admin/client/marketing/hooks/useInstalledPluginsWithoutChannels.ts]: Thanks. Done in [`25ee49a` (#54485)](https://github.com/woocommerce/woocommerce/pull/54485/commits/25ee49af1d3fd93663a152111787e7421afe6676). I changed it in 3 files with similar occurrences.

File: plugins/woocommerce/client/admin/client/marketing/components/PluginCardBody/SmartPluginCardBody.tsx (hunk 1 above)
Comment (ecgan) [reply plugins/woocommerce/client/admin/client/marketing/components/PluginCardBody/SmartPluginCardBody.tsx:42]: > This seems to not only be about TS issues. 

Oh yes, I did a bit of refactor and simplified the code. The code was previously in `useIsPluginInstalledNotActivated`, which is now deleted. See [`36e0012` (#54485)](https://github.com/woocommerce/woocommerce/pull/54485/commits/36e0012e8df35d5d1697c1a846c1b8999a12c972).

> minor suggestion: instead of returning an object, why not simply return the `initialState` string?

Technically that would work, but it is better to always return objects. See [Best practices for using useSelect() from @wordpress/data](https://jardasn.blog/2021/01/22/some-best-practices-for-using-useselect-from-wordpress-data/) (look for "Prefer returning objects with properties from the callback").

File: plugins/woocommerce/client/admin/client/marketing/components/PluginCardBody/useIsPluginInstalledNotActivated.ts [hunk 7]
```diff
@@ -1,24 +0,0 @@
...
-import { useSelect } from '@wordpress/data';
-import { PLUGINS_STORE_NAME } from '@woocommerce/data';
-
-export const useIsPluginInstalledNotActivated = () => {
-	const { getPluginInstallState } = useSelect( ( select ) => {
-		return {
-			getPluginInstallState:
-				select( PLUGINS_STORE_NAME ).getPluginInstallState,
-		};
-	} );
```
Comment (ecgan) [inline plugins/woocommerce/client/admin/client/marketing/components/PluginCardBody/useIsPluginInstalledNotActivated.ts:14]: The code here was returning the `getPluginInstallState` selector function but not calling the function. This is not a good practice and can be buggy. See [Best practices for using useSelect() from @wordpress/data
](https://jardasn.blog/2021/01/22/some-best-practices-for-using-useselect-from-wordpress-data/) (look for "Always call selector functions inside the callback").

That's why I have refactored, simplified and removed this `useIsPluginInstalledNotActivated` hook in [`36e0012` (#54485)](https://github.com/woocommerce/woocommerce/pull/54485/commits/36e0012e8df35d5d1697c1a846c1b8999a12c972).

File: plugins/woocommerce/client/admin/client/marketing/data-multichannel/types.ts [hunk 8]
```diff
@@ -81,11 +81,6 @@ export type CampaignsState = {
 	meta: CampaignsMeta;
 };
 
-export type CampaignsPagination = {
-	campaignsPage: CampaignsPage | null;
-	meta: CampaignsMeta;
-};
-
```
Comment (ecgan) [inline plugins/woocommerce/client/admin/client/marketing/data-multichannel/types.ts:88]: This is not being used anymore, so we just remove it.

File: plugins/woocommerce/client/admin/client/marketing/hooks/useIntroductionBanner.ts [hunk 9]
```diff
@@ -30,9 +30,11 @@ export const useIntroductionBanner = (): UseIntroductionBanner => {
 			select( OPTIONS_STORE_NAME );
 
 		return {
+			// @ts-expect-error Todo: awaiting more global fix, demo: https://github.com/woocommerce/woocommerce/pull/54146
```
Comment (ecgan) [inline plugins/woocommerce/client/admin/client/marketing/hooks/useIntroductionBanner.ts:33]: I found this in the existing code base, so I just follow the same convention. See PR https://github.com/woocommerce/woocommerce/pull/54146. We can also use the PR number and link to search for more info in internal Slack and P2s.

**Review by ecgan — COMMENTED** [review]
Adding some comments for my code changes.

**Comment by ecgan** [comment]
> While reviewing the code, my first comment is why we use CamelCase for folders and files 😅 I think it's a very uncommon naming convention.

We shall address that separately later, not in this PR. 😅

File: plugins/woocommerce/client/admin/client/marketing/components/PluginCardBody/SmartPluginCardBody.tsx (hunk 1 above)
Comment (retrofox) [reply plugins/woocommerce/client/admin/client/marketing/components/PluginCardBody/SmartPluginCardBody.tsx:42]: :til: Thanks a lot for the explanation and the reference!

**Review by retrofox — APPROVED** [review]
Awesome job, Gan! Tested and it fixes all TS issues. 🚀

File: plugins/woocommerce/client/admin/client/marketing/components/PluginCardBody/SmartPluginCardBody.tsx (hunk 2 above)
Comment (retrofox) [reply plugins/woocommerce/client/admin/client/marketing/components/PluginCardBody/SmartPluginCardBody.tsx:93]: yes
