### PR TITLE
[Accessibility] Remove title attribute from images in product gallery

### LINKED ISSUE #43576: Accessibility: Product gallery images on single product contain title attribute, resulting in unnecessary noise for screen reader users
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

On the single product page, the product images in the gallery output a title attribute. Here's an example:
Screenshot 2024-01-12 at 11 14 54 AM

When a screen reader encounters these images it reads out both the alt text and the title attribute. 

In the worse-case scenario, the title is the file name (as is shown in the screenshot) and junky information is read out. This is most commonly the case as WordPress creates the title from the file name on upload. In a best-case scenario, the user has written a title, but it is commonly duplicative of what is in the alt text.

The title attribute should not be included in image tags.

### Expected behavior

Images will not have a title attribute and use the alt attribute only.

### Actual behavior

A title attribute is present.

### Steps to reproduce

Go to a product single and inspect the images in the image gallery.

### WordPress Environment

N/A

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by Manussakis**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes #43576  .

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Go to a product single and inspect the images in the image gallery.
2. Verify the images don't have the `title` attribute.
   image

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce/includes/wc-template-functions.php [hunk 1]
```diff
@@ -1622,7 +1622,6 @@ function wc_get_gallery_image_html( $attachment_id, $main_image = false ) {
 		apply_filters(
 			'woocommerce_gallery_image_html_attachment_image_params',
 			array(
-				'title'                   => _wp_specialchars( get_post_field( 'post_title', $attachment_id ), ENT_QUOTES, 'UTF-8', true ),
```
Comment (Manussakis) [inline plugins/woocommerce/includes/wc-template-functions.php:1625]: To remove the `title` HTML attribute from the product gallery images, the `title` property needs to be removed from the array returned by the `woocommerce_gallery_image_html_attachment_image_params` filter. However, plugins/themes that have hooked into this filter may depend on this property.

What would be the appropriate way to handle this case?

**Comment by Manussakis** [comment]
@dkotter This PR is ready for code review. Please take a look at this comment. https://github.com/woocommerce/woocommerce/pull/50886#discussion_r1727967322

File: plugins/woocommerce/includes/wc-template-functions.php (hunk 1 above)
Comment (dkotter) [reply plugins/woocommerce/includes/wc-template-functions.php:1625]: I think the only approach we could take here is to move this filter out of the `wp_get_attachment_image` call and instead assign the value of whatever the filter returns to a variable, then use that variable in `wp_get_attachment_image`. This would then allow us to keep the arguments the same in the filter call but remove `title` after the fact.

Something like the following (note it's untested):
```php
$image_params = apply_filters(
	'woocommerce_gallery_image_html_attachment_image_params',
	array(
		'title'                   => _wp_specialchars( get_post_field( 'post_title', $attachment_id ), ENT_QUOTES, 'UTF-8', true ),
		'data-caption'            => _wp_specialchars( get_post_field( 'post_excerpt', $attachment_id ), ENT_QUOTES, 'UTF-8', true ),
		'data-src'                => esc_url( $full_src[0] ),
		'data-large_image'        => esc_url( $full_src[0] ),
		'data-large_image_width'  => esc_attr( $full_src[1] ),
		'data-large_image_height' => esc_attr( $full_src[2] ),
		'class'                   => esc_attr( $main_image ? 'wp-post-image' : '' ),
	),
	$attachment_id,
	$image_size,
	$main_image
);

if ( isset( $image_params['title'] ) {
	unset( $image_params['title'] );
}

$image = wp_get_attachment_image(
	$attachment_id,
	$image_size,
	false,
	$image_params
);
```

Comment (Manussakis) [reply plugins/woocommerce/includes/wc-template-functions.php:1625]: Great idea, @dkotter. Thanks!
Please re-review the PR.

**Review by dkotter — APPROVED** [review]
@ankitguptaindia @qasumitbagthariya This is ready for QA

**Comment by ankitguptaindia** [comment]
**QA/Test Report-** ✅ 
------------

**Testing Environment -** 

<Details>

* WordPress: 6.6.1
* Theme: 
**Storefront Version: 4.6.0  
**Twenty Twenty-Four Version: 1.2
* WooCommerce - Development version with this fix-specific branch.  
* PHP: 8.3
* Web Server: Nginx
* Browser: Chrome - Version 127
* OS: macOS Sonoma 14.5

</Details>


**Test Results -** 

The changes work as intended and tested across Safari, Firefox, and Chrome. PR was verified using macOS VoiceOver. Testing was conducted with both the Storefront theme and the Twenty Twenty-Four theme.
 

**Functional Demo /  Screencast -** 











| Before Fix: Title attribute appears | After Fix: Title attribute doesn't appear.  | After Fix: Title attribute doesn't appear.  |
|--------|--------|--------|
| Screenshot 2024-08-23 at 10 34 24 PM | Screenshot 2024-08-23 at 10 30 42 PM | Screenshot 2024-08-23 at 10 30 03 PM |

**Comment by ankitguptaindia** [comment]
Hi 👋🏼 @Manussakis 
Thanks for the excellent work on this PR! All cases have been successfully verified in testing. Could you please undraft and mark this PR as ready for review?

cc: @vikrampm1

**Review by roykho — APPROVED** [review]
Thanks for working on this. LGTM!

✅ `title` attribute is no longer added to the img tag.
