### PR TITLE
Fix: Featured invalid-id item handled with new item picker panel 

### LINKED ISSUE #42677: Featured Product: display a message in the editor if the product is not 'Published'
It's technically possible that the Featured Product block might be pointing to a product which is not visible to most users like draft, private, scheduled products... (see steps below). It would be nice if the editor displayed a notice in some way about this.

**To Reproduce**
1. Add a _Featured Product_ block to a post and select a product (ie: _Album_).
2. Edit the _Album_ product and set its status to _Draft_.
3. Reload the post in the frontend: the product is not visible.
4. Reload the post in the editor: there is no message telling editors that the product won't be visible for most users.

Expected result: in step 4 there should be a message somewhere letting the editor know that the product is visible to them but not to most other users.

### PR DESCRIPTION
**Pull request by Kallyan01**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

This PR introduces a custom hook `useFeaturedItemStatus` to handle `invalid` selected items for the Featured Product and Featured Category block.

The `useFeaturedItemStatus` hook:

- Accepts an itemId and an itemType ('product' or 'category')

- Returns three state values:

  - status: the current publish status of the item ('publish', 'draft', etc.)

  - isDeleted: a boolean indicating whether the item has been deleted .

  - isLoading: indicates the loading state during fetch.

Closes #42677 .

### Screenshots or screen recordings:

https://github.com/user-attachments/assets/185e2d79-ee71-43cc-8b58-aadbb98485da

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

- Add a Featured Product or Featured Category block to a post/page.
- Select an item from the picker and publish the page.
- Delete the selected product/category from the dashboard.
- Reopen the editor:
  - The block should automatically switch to edit mode
  - The picker UI should prompt the user to select a new item
- Repeat the same steps for both block types to ensure consistency.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

## Summary by CodeRabbit

- **Bug Fixes**
  - Improved handling of invalid or deleted product and category references in featured item blocks to prevent display errors or inconsistencies.

- **New Features**
  - Added contextual feedback in edit mode when a selected product or category is no longer available.
  - Introduced a new info icon with updated styling and color in the featured items block for clearer status indication.

- **Style**
  - Updated the info icon color in the featured items block for enhanced visual clarity.

### CODE REVIEW

File: plugins/woocommerce/client/blocks/assets/js/blocks/featured-items/utils.ts [hunk 1]
```diff
@@ -91,3 +97,21 @@ export function dimRatioToClass( ratio: number ) {
...
+	return name === BLOCK_NAMES.featuredProduct
+		? __(
+				'Previously selected Product is no longer available',
+				'woocommerce'
+		  )
+		: __(
+				'Previously selected Category is no longer available',
+				'woocommerce'
+		  );
+}
```
[the remark this answers is not in the document]
Comment (Kallyan01) [reply plugins/woocommerce/client/blocks/assets/js/blocks/featured-items/utils.ts]: As we are handing category and product type only so the new message is not required here .

File: plugins/woocommerce/client/blocks/assets/js/blocks/featured-items/use-featured-item-status.ts [hunk 2]
```diff
@@ -0,0 +1,98 @@
...
+				getEntityRecord,
+				getEntityRecords,
+				hasFinishedResolution,
+				getLastEntitySaveError,
+			} = selectFunc( coreDataStore );
+
+			if ( itemType === BLOCK_NAMES.featuredProduct ) {
+				const productArgs = [ 'postType', 'product', itemId ];
+				const product = getEntityRecord( ...productArgs );
+				const saveError = getLastEntitySaveError( ...productArgs );
```
Comment (gigitux) [inline plugins/woocommerce/client/blocks/assets/js/blocks/featured-items/use-featured-item-status.ts]: There are some TS errors. Could you add the `@ts-expect-error` comment?

File: plugins/woocommerce/client/blocks/assets/js/blocks/featured-items/use-featured-item-status.ts [hunk 3]
```diff
@@ -0,0 +1,98 @@
...
+					return {
+						status: 'deleted',
+						isDeleted: true,
+						isLoading: false,
+					};
+				}
+
+				return {
+					status:
+						product?.status ?? ( isResolved ? 'deleted' : null ),
```
Comment (gigitux) [inline plugins/woocommerce/client/blocks/assets/js/blocks/featured-items/use-featured-item-status.ts]: Same

File: plugins/woocommerce/client/blocks/assets/js/blocks/featured-items/use-featured-item-status.ts [hunk 4]
```diff
@@ -0,0 +1,98 @@
...
+				};
+			}
+
+			if ( itemType === BLOCK_NAMES.featuredCategory ) {
+				const categoryArgs = [
+					'taxonomy',
+					'product_cat',
+					{ include: [ itemId ] },
+				];
+				const categories = getEntityRecords( ...categoryArgs );
```
Comment (gigitux) [inline plugins/woocommerce/client/blocks/assets/js/blocks/featured-items/use-featured-item-status.ts:59]: Same

File: plugins/woocommerce/client/blocks/assets/js/blocks/featured-items/utils.ts [hunk 5]
```diff
@@ -98,6 +99,24 @@ export function dimRatioToClass( ratio: number ) {
...
+export function getInvalidItemDescription( name: string ):string {
+	return name === BLOCK_NAMES.featuredProduct
+		? __(
+				'Previously selected Product is no longer available',
+				'woocommerce'
+		  )
+		: __(
+				'Previously selected Category is no longer available',
+				'woocommerce'
+		  );
```
Comment (gigitux) [inline plugins/woocommerce/client/blocks/assets/js/blocks/featured-items/utils.ts]: Should we put the first capital letter in Product and Category? I think that `product` and `category` without capital letter is okay.

File: plugins/woocommerce/client/blocks/assets/js/blocks/featured-items/with-edit-mode.tsx [hunk 6]
```diff
@@ -61,14 +73,64 @@ export const withEditMode =
...
+					status !== 'publish' ) ||
+				isDeleted;
+
+			if (
+				currEditModeValue !== attributes.editMode &&
+				typeof currEditModeValue === 'boolean'
+			) {
+				setAttributes( { editMode: currEditModeValue } );
+			}
+		}, [ status, isDeleted, attributes.editMode, name, setAttributes ] );
```
Comment (gigitux) [inline plugins/woocommerce/client/blocks/assets/js/blocks/featured-items/with-edit-mode.tsx]: It is not a blocker, but I think that we should get rid of the `editMode` attribute and handle the editor mode in React and not via block attributes. It would be an interesting follow-up.

File: plugins/woocommerce/client/blocks/assets/js/blocks/featured-items/with-edit-mode.tsx [hunk 7]
```diff
@@ -61,14 +73,64 @@ export const withEditMode =
...
-					{ description }
+					<HStack alignment="center">
+						{ attributes.productId || attributes.categoryId ? (
+							<Icon
+								icon={ info }
+								className="wc-blocks-featured-items__orange-info-icon"
+							/>
+						) : (
+							<Icon icon={ info } />
+						) }
```
Comment (gigitux) [inline plugins/woocommerce/client/blocks/assets/js/blocks/featured-items/with-edit-mode.tsx]: Why is this conditional logic needed?

**Review by gigitux — CHANGES_REQUESTED** [review]
Thanks for working on this! Everything works as expected:


https://github.com/user-attachments/assets/fb58019d-a331-404d-b728-c9ebc548d102



I left a few comments, but they are pretty straightforward to fix. 

I see two interesting follow-ups if you are interested in working on:

- Remove `editMode` attribute -> I think that we should not have the `editMode` attribute because it is just a “flag” for the editor side, but handle with a React state.
- We have the same issue for other blocks. It would be interesting to create a block that renders the list of product/category/etc and handles the invalid ID too. At the same time, I don't know how much effort is required.

**Comment by gigitux** [comment]
Also, it looks like that this PR breaks some E2E tests. Can you investigate why?

File: plugins/woocommerce/client/blocks/assets/js/blocks/featured-items/with-edit-mode.tsx (hunk 7 above)
Comment (Kallyan01) [reply plugins/woocommerce/client/blocks/assets/js/blocks/featured-items/with-edit-mode.tsx]: @gigitux This logic is responsible for the color of the `info` icon , if the Id's present and the edit mode is rendering show the orange color one and if no id is present then it's a fresh block so keep the normal info color one 
 
image

image

File: plugins/woocommerce/client/blocks/assets/js/blocks/featured-items/with-edit-mode.tsx (hunk 6 above)
Comment (Kallyan01) [reply plugins/woocommerce/client/blocks/assets/js/blocks/featured-items/with-edit-mode.tsx]: Should i create a new PR for adding this specific change to this blocks ?

Comment (gigitux) [reply plugins/woocommerce/client/blocks/assets/js/blocks/featured-items/with-edit-mode.tsx]: > Should i create a new PR for adding this specific change to this blocks ?

As you prefer, I think that this refactor will simplify the codebase of these two blocks.

**Comment by Kallyan01** [comment]
Hello @gigitux ,
I have resolved the e2e testcases , the item picker `Done` button was causing the failure because we were skipping click event on it entirely and setting the `editMode` to false once the user selects an option. I've resolved that issue now .

I have a doubt regarding `product_variation` postType . Can we make it available in rest api ?

```php
	register_post_type(
			'product_variation',
			apply_filters(
				'woocommerce_register_post_type_product_variation',
				array(
					'label'           => __( 'Variations', 'woocommerce' ),
					'public'          => false,
					'hierarchical'    => false,
					'supports'        => false,
					'capability_type' => 'product',
					'rewrite'         => false,
					'show_in_rest'    => true,
				)
			)
		);

```

The reason behind this change is , while i was performing test on the productPicker i've noticed it's only working for single products .Whenever i'm selecting a variable product option -> save -> refresh it , it's causing edit mode to true as the product was not found as it's a `product_variation` type post [[ref](https://github.com/Kallyan01/woocommerce/blob/b7e8425720c91c3448a68708d97fd7b78fc21d78/plugins/woocommerce/client/blocks/assets/js/blocks/featured-items/use-featured-item-status.ts#L46)].

**Comment by gigitux** [comment]
> Hello @gigitux , I have resolved the e2e testcases , the item picker `Done` button was causing the failure because we were skipping click event on it entirely and setting the `editMode` to false once the user selects an option. I've resolved that issue now .
> 
> I have a doubt regarding `product_variation` postType . Can we make it available in rest api ?
> 
> ```
> 	register_post_type(
> 			'product_variation',
> 			apply_filters(
> 				'woocommerce_register_post_type_product_variation',
> 				array(
> 					'label'           => __( 'Variations', 'woocommerce' ),
> 					'public'          => false,
> 					'hierarchical'    => false,
> 					'supports'        => false,
> 					'capability_type' => 'product',
> 					'rewrite'         => false,
> 					'show_in_rest'    => true,
> 				)
> 			)
> 		);
> ```
> 
> The reason behind this change is , while i was performing test on the productPicker i've noticed it's only working for single products .Whenever i'm selecting a variable product option -> save -> refresh it , it's causing edit mode to true as the product was not found as it's a `product_variation` type post [[ref](https://github.com/Kallyan01/woocommerce/blob/b7e8425720c91c3448a68708d97fd7b78fc21d78/plugins/woocommerce/client/blocks/assets/js/blocks/featured-items/use-featured-item-status.ts#L46)].

Sorry for the late reply, and thanks for further testing! 

This happens because you're using WordPress REST API to retrieve products. At this point, I think that it makes sense to use the WooCommerce REST API to retrieve products. In this way, product variations will be present. 

You can use the WooCommerce REST API via the `@woocommerce/data` package. You can check this code as example:

https://github.com/woocommerce/woocommerce/blob/8f3852dfdc118411e7711ce50946fc0ff4a4b36c/plugins/woocommerce/client/blocks/assets/js/blocks/add-to-cart-with-options/grouped-product-selector/product-item/edit.tsx#L100-L108

**Review by gigitux — CHANGES_REQUESTED** [review]
Thanks for addressing the feedback! I noticed this wrong behavior when I selected the product. The label is updated in the wrong way:

https://github.com/user-attachments/assets/1888f11f-1718-4338-80c2-6b1306327bb0

Also, I noticed that when the product is deleted (and for a new block , the product isn't visible in the list), the block doesn't change its status:


https://github.com/user-attachments/assets/4a016d56-8f7e-494f-80b1-9a908be84e4e

File: plugins/woocommerce/client/blocks/assets/js/blocks/featured-items/style.scss [hunk 8]
```diff
@@ -180,6 +180,10 @@
 	.wp-block-button.aligncenter {
 		text-align: center;
 	}
+
+	.wc-blocks-featured-items__orange-info-icon {
+	fill: var(--wp--preset--color--luminous-vivid-orange, #e26f56);
+}
```
Comment (gigitux) [inline plugins/woocommerce/client/blocks/assets/js/blocks/featured-items/style.scss]: It looks like that this CSS isn't formatted correctly.

It should be:

```css
.wc-blocks-featured-items__orange-info-icon {
    fill: var(--wp--preset--color--luminous-vivid-orange, #e26f56);
}
```

**Comment by Kallyan01** [comment]
Hi @gigitux, thanks for the feedback!

I tested the item picker issue with the "deleted product" description and was able to reproduce it, it's caused by the item picker button feature I addressed in earlier commits.

As for the second issue you mentioned, I couldn’t reproduce it on my end. It might be related to caching. I’ve tested it thoroughly, and it seems to be working as expected.

Let me know if you continue to face it, and I’ll take another look.

**Comment by Kallyan01** [comment]
@gigitux if i'm not wrong the failed CI test isn't associated with this PRs changes.

**Comment by gigitux** [comment]
> @gigitux if i'm not wrong the failed CI test isn't associated with this PRs changes.

You're right!

File: plugins/woocommerce/client/blocks/assets/js/blocks/featured-items/use-featured-item-status.ts [hunk 9]
```diff
@@ -0,0 +1,87 @@
...
+			if ( ! itemId ) {
+				return {
+					status: null,
+					isDeleted: true,
+					isLoading: false,
+				};
+			}
+
+			if ( itemType === BLOCK_NAMES.featuredProduct ) {
+				const { getProduct, hasFinishedResolution } =
```
Comment (gigitux) [inline plugins/woocommerce/client/blocks/assets/js/blocks/featured-items/use-featured-item-status.ts]: We've decided to transition from the `@woocommerce/data` package to the `@wordpress/core-data` package.  
Could you refactor the code accordingly and start using the `useProduct` hook? https://github.com/woocommerce/woocommerce/pull/60074/files#diff-b0dd86b8fdc84b4e6884bb0d17ab974f8da91364cba724a1218a15e7f2666e64R8
That would be great, thanks!

**Review by gigitux — CHANGES_REQUESTED** [review]
Thanks, I left a comment regarding a refactor that it is needed. Also, I noticed that the label is wrong when the product list is rendered: can you replicate it? 

https://github.com/user-attachments/assets/7af4f057-7bdc-4fa0-90ec-1a404ca5d4ad

**Comment by Kallyan01** [comment]
@gigitux resolved the feedbacks, Thanks!

https://github.com/user-attachments/assets/66e0c0e1-5bba-4dbd-8762-46e43d236bff

File: plugins/woocommerce/client/blocks/assets/js/blocks/featured-items/use-featured-item-status.ts [hunk 10]
```diff
@@ -0,0 +1,89 @@
...
+	isLoading: boolean;
+}
+
+export const useFeaturedItemStatus = ( {
+	itemId,
+	itemType,
+}: UseFeaturedItemProps ): UseFeaturedItemReturnType => {
+	const { product, isResolutionFinished } = useProduct( itemId );
+
+	{
```
Comment (gigitux) [inline plugins/woocommerce/client/blocks/assets/js/blocks/featured-items/use-featured-item-status.ts]: I think that we should remove the `{` parenthesis .

**Review by gigitux — CHANGES_REQUESTED** [review]
I tested the PR and now it works correctly! I left a small feedback; once you fix it, I will do the final round of testing! Thanks! 🙇

**Comment by Kallyan01** [comment]
> I tested the PR and now it works correctly! I left a small feedback; once you fix it, I will do the final round of testing! Thanks! 🙇

Thanks, removed the parenthesis.

**Review by gigitux — APPROVED** [review]
Thanks for all your work. LGTM! Everything works as expected!

### Blocks with not deleted product
https://github.com/user-attachments/assets/15ee388b-71bb-4119-87a0-175c4c5bbcfb

### Blocks with deleted product


https://github.com/user-attachments/assets/929ff7ac-787e-425e-8653-12650ecba26f


It is not related to this PR, but I noticed a different behavior between the Featured Category block and the Featured Product block.

When the category is deleted, the block renders nothing on the frontend. However, in the Featured Product block, the product is still displayed. This likely happens because the PHP render logic for Featured Product doesn’t check whether the product is in the trash.

**Comment by gigitux** [comment]
Also, with 3d5f993648d0ac135a14ae0060ccf95abac5fc41, I update the error type from `Error` to `ErrorObject`.

**Why**  
- Upstream HOCs (`withProduct`/`withCategory`) return `Promise<ErrorObject>` via `formatError()`.  
- `withEditMode` passes this to downstream HOCs.  
- Downstream (`withApiError`) expects `ErrorObject` for `ErrorPlaceholder`.  

I hope that it makes sense!
