### PR TITLE
Fixes issue #33335

### LINKED ISSUE #33335: Variation name is not displayed correctly when attribute name is "0"
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

We have attribute terms like "1" and "2" and "12" and so on. We also have "0". Setting these attributes on parents and creating variations out of them works just as we want it to work. No problem there. But calling `get_name` on a variation from the attribute "0" does not show the name correctly.

### Expected behavior

Calling `get_name` on a variation from the attribute "1" on a variable product with the name "Test" returns "Test - 1". I expect calling `get_name` on a variation from the attribute "0" to return "Test - 0".

### Actual behavior

Calling `get_name` on a variation from the attribute "0" returns "Test".

### Steps to reproduce

Create a variation from an attribute called "0" and get the variation name through `get_name`.

### WordPress Environment

WordPress Environment
WordPress address (URL): http://clean.localhost/
Site address (URL): http://clean.localhost/
WC Version: 6.5.1
REST API Version: ✔ 6.5.1
WC Blocks Version: ✔ 7.4.3
Action Scheduler Version: ✔ 3.4.0
Log Directory Writable: ✔
WP Version: 6.0
WP Multisite: –
WP Memory Limit: 4 GB
WP Debug Mode: ✔
WP Cron: ✔
Language: nb_NO
External object cache: –

Server Environment
Server Info: Apache/2.4.43 (Win64) OpenSSL/1.1.1g PHP/7.4.7
PHP Version: 7.4.7
PHP Post Max Size: 64 MB
PHP Time Limit: 120
PHP Max Input Vars: 1000
cURL Version: 7.69.1
OpenSSL/1.1.1g

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.4.13-MariaDB
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Serveren din har ikke SoapClient-klassen aktivert. Noen gatewayutvidelser som bruker SOAP vil kanskje ikke fungere som forventet.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

Database
WC Database Version: 6.5.1
WC Database Prefix: wp_
Total database størrelse: 6.35MB
Database data størrelse: 4.17MB
Database indeks størrelse: 2.18MB
wp_woocommerce_sessions: Data: 0.02MB + indeks: 0.02MB + motor InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + indeks: 0.03MB + motor InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + indeks: 0.02MB + motor InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + indeks: 0.17MB + motor InnoDB
wp_woocommerce_order_items: Data: 0.02MB + indeks: 0.03MB + motor InnoDB
wp_woocommerce_order_itemmeta: Data: 0.06MB + indeks: 0.05MB + motor InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + indeks: 0.08MB + motor InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + indeks: 0.05MB + motor InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + indeks: 0.00MB + motor InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + indeks: 0.03MB + motor InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + indeks: 0.00MB + motor InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + indeks: 0.03MB + motor InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + indeks: 0.05MB + motor InnoDB
wp_woocommerce_log: Data: 0.02MB + indeks: 0.02MB + motor InnoDB
wp_actionscheduler_actions: Data: 0.02MB + indeks: 0.13MB + motor InnoDB
wp_actionscheduler_claims: Data: 0.02MB + indeks: 0.02MB + motor InnoDB
wp_actionscheduler_groups: Data: 0.02MB + indeks: 0.02MB + motor InnoDB
wp_actionscheduler_logs: Data: 0.02MB + indeks: 0.03MB + motor InnoDB
wp_commentmeta: Data: 0.02MB + indeks: 0.03MB + motor InnoDB
wp_comments: Data: 0.02MB + indeks: 0.09MB + motor InnoDB
wp_fld_active_gwps: Data: 0.02MB + indeks: 0.00MB + motor InnoDB
wp_fld_tft_active_products: Data: 0.02MB + indeks: 0.06MB + motor InnoDB
wp_fld_tft_campaigns: Data: 0.02MB + indeks: 0.00MB + motor InnoDB
wp_links: Data: 0.02MB + indeks: 0.02MB + motor InnoDB
wp_options: Data: 3.03MB + indeks: 0.06MB + motor InnoDB
wp_postmeta: Data: 0.09MB + indeks: 0.09MB + motor InnoDB
wp_posts: Data: 0.05MB + indeks: 0.06MB + motor InnoDB
wp_termmeta: Data: 0.02MB + indeks: 0.03MB + motor InnoDB
wp_terms: Data: 0.02MB + indeks: 0.03MB + motor InnoDB
wp_term_relationships: Data: 0.02MB + indeks: 0.02MB + motor InnoDB
wp_term_taxonomy: Data: 0.02MB + indeks: 0.03MB + motor InnoDB
wp_usermeta: Data: 0.02MB + indeks: 0.03MB + motor InnoDB
wp_users: Data: 0.02MB + indeks: 0.05MB + motor InnoDB
wp_wc_admin_notes: Data: 0.05MB + indeks: 0.00MB + motor InnoDB
wp_wc_admin_note_actions: Data: 0.03MB + indeks: 0.02MB + motor InnoDB
wp_wc_category_lookup: Data: 0.02MB + indeks: 0.00MB + motor InnoDB
wp_wc_customer_lookup: Data: 0.02MB + indeks: 0.05MB + motor InnoDB
wp_wc_download_log: Data: 0.02MB + indeks: 0.05MB + motor InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + indeks: 0.03MB + motor InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + indeks: 0.11MB + motor InnoDB
wp_wc_order_stats: Data: 0.02MB + indeks: 0.30MB + motor InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + indeks: 0.03MB + motor InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + indeks: 0.03MB + motor InnoDB
wp_wc_product_download_directories: Data: 0.02MB + indeks: 0.02MB + motor InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + indeks: 0.09MB + motor InnoDB
wp_wc_rate_limits: Data: 0.02MB + indeks: 0.02MB + motor InnoDB
wp_wc_reserved_stock: Data: 0.02MB + indeks: 0.00MB + motor InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + indeks: 0.02MB + motor InnoDB
wp_wc_webhooks: Data: 0.02MB + indeks: 0.03MB + motor InnoDB

Post Type Counts
attachment: 1
page: 7
post: 2
product: 3
product_variation: 2
shop_coupon: 1
shop_order: 26

Security
Secure connection (HTTPS): ❌
Butikken din bruker ikke HTTPS. Ler mer om HTTPS og SSL sertifikater.
Hide errors from visitors: ❌Feilmeldinger skal ikke vised til besøkende.

Active Plugins (2)
CLI: av Dekadinious – 2.0.0
WooCommerce: av Automattic – 6.5.1

Inactive Plugins (5)
[REDACTED]

Settings
API Enabled: –
Force SSL: –
Currency: NOK (kr)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: –

WC Pages
Butikkbase: https://github.com/woocommerce/woocommerce/issues/6 - /butikk/
Handlekurv: https://github.com/woocommerce/woocommerce/issues/7 - /handlekurv/
Til kassen: https://github.com/woocommerce/woocommerce/issues/8 - /kassen/
Min konto: https://github.com/woocommerce/woocommerce/issues/9 - /min-konto/
Vilkår og betingelser: ❌ Sidesynlighet bør være offentlig

Theme
Name: Storefront
Version: 4.1.0
Author URL: https://woocommerce.com/
Child Theme: ❌ – Hvis du endrer WooCommerce eller et foreldertema du ikke selv har bygget
anbefaler vi å bruke et dattertema. Se: Hvordan lage et dattertema

WooCommerce Support: ✔

Templates
Overrides: –

Action Scheduler
Fullført: 22
Oldest: 2022-06-07 10:49:08 +0200
Newest: 2022-06-07 10:59:07 +0200

Status report information
Generated at: 2022-06-07 10:59:16 +02:00

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by Dekadinious**
Check for an empty string instead of an empty variable.

### All Submissions:

-   [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
-   [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
-   [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Calling get_name on a variation from the attribute "0" does not show the name correctly because it is tested for being empty instead of an empty string. This pull request fixes this.

Closes #33335 

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

File: plugins/woocommerce/includes/wc-product-functions.php [hunk 1]
```diff
@@ -392,7 +392,7 @@ function wc_get_formatted_variation( $variation, $flat = false, $include_names =
 			// If this is a term slug, get the term's nice name.
 			if ( taxonomy_exists( $name ) ) {
 				$term = get_term_by( 'slug', $value, $name );
-				if ( ! is_wp_error( $term ) && ! empty( $term->name ) ) {
+				if ( ! is_wp_error( $term ) && "" !== $term->name ) {
```
Comment (peterfabian) [inline plugins/woocommerce/includes/wc-product-functions.php]: Thanks, this looks good. WordPress generally prefers using single quotes when the string doesn't need to be interpolated ([ref](https://developer.wordpress.org/coding-standards/wordpress-coding-standards/php/#single-and-double-quotes)), can you please update? Then it should be good to go :)

**Review by peterfabian — CHANGES_REQUESTED** [review]
Hi, thanks for the contribution! 🎉  It just needs a small change, otherwise it looks good 💪 .

File: plugins/woocommerce/includes/wc-product-functions.php [hunk 2]
```diff
@@ -392,7 +392,7 @@ function wc_get_formatted_variation( $variation, $flat = false, $include_names =
 			// If this is a term slug, get the term's nice name.
 			if ( taxonomy_exists( $name ) ) {
 				$term = get_term_by( 'slug', $value, $name );
-				if ( ! is_wp_error( $term ) && ! empty( $term->name ) ) {
+				if ( ! is_wp_error( $term ) && '' !== $term->name ) {
```
Comment (peterfabian) [inline plugins/woocommerce/includes/wc-product-functions.php]: Sorry I haven't noticed this before, but the unit tests showed that `empty` actually behaves in a way that `$term` can be `null` and it won't produce a PHP Notice while this new code does, so we'd first need to test whether `$term` is set. 

Additionally, we should probably also check for `$term->name` being `null` to not introduce subtle bugs somewhere down the line. 

Can you please update the code to include the checks? Thanks!

**Review by peterfabian — CHANGES_REQUESTED** [review]
Our unit tests caught one small additional problem as explained below. Can you please update? Thanks!

**Review by peterfabian — APPROVED** [review]
Looks good now, thanks!
