### PR TITLE
Product Filters > Clear button: Refactor the Product Filters to use a function instead of the hook

### LINKED ISSUE #51636: Clear button doesn't respect filter block setting
The Clear Button block is always rendered in both editors and on the front end even if the corresponding setting is disabled in the Filter Block setting.

### Steps to reproduce
0. Ensure the experimental blocks are enabled:
    - If you use the WooCommerce Beta Tester plugin, you can enable the experimental blocks in Tools > WCA Test Helper > Features. Toggle the `experimental-blocks` option.
    - If you build this PR locally, build the branch with `pnpm --filter='@woocommerce/plugin-woocommerce' watch:build` command to have experimental blocks available.
1. Edit the Product Catalog template, and add the `Product Filters (Experimental)` template part to the page.
2. See the attribute filter block set to your store's product attribute automatically.
3. Select the attribute filter block > Inspector controls sidebar > Styles tab.
4. Toggle off the Clear button setting.
5. See the Clear button block is still rendered in the canvas.
6. Save the page and see the same things on the frontend (when you choose a filter).

### Screenshots 

Thanks @roykho for the screenshots:

image

image

### PR DESCRIPTION
**Pull request by thealexandrelara**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes #51636 .

This PR refactors the current useProductFilterClearButtonManager and transforms it into a util function that can be used by each individual filter when the "Show clear button" setting is modified. I added E2E tests in the previous PR to ensure the functionality will continue working as expected.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

> [!NOTE]  
> **Pre-requisite**
> - If you're using WC Beta Tester plugin, make sure the `experimental-blocks` feature is enabled (Tools > WCA Test Helper > Features).

1. Navigate to Product Catalog template (Appearance > Editor > Template > Product Catalog).
2. Add the Product Filters (Experimental) block.
3. For each individual filter, select it and open the Inspector Controls.
4. Disable the "Clear" button and ensure it's hidden in the Editor.
5. Save the template and visit the front page to ensure it's hidden there as well.
6. Go back to the Product Catalog template and enable the "Clear" button;
7. Make sure the Clear button is restored.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [x] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment  Refactor individual filters to use a function instead of a hook.

</details>

### CODE REVIEW

**Review by dinhtungdu — APPROVED** [review]
Thank you for working on this! I tested the PR in JN and it's working as expected. The factory is an interesting design choice! Great work! :shipit:

**Review by roykho — CHANGES_REQUESTED** [review]
Looking good so far. I did find an issue. If you default the clear button to false in `block.json`. The editor and frontend still displays the clear button.

**Comment by thealexandrelara** [comment]
> Looking good so far. I did find an issue. If you default the clear button to false in `block.json`. The editor and frontend still displays the clear button.
> 

Really nice catch! I fixed the issue in: d419c67a0ac8c457edd71c9c7869e4027ca0db8c

File: plugins/woocommerce-blocks/assets/js/blocks/product-filters/utils/get-colors-from-block-supports.ts [hunk 1]
```diff
@@ -0,0 +1,19 @@
+/**
+ * External dependencies
+ */
+import { BlockAttributes } from '@wordpress/blocks';
+
+function getCSSVar( slug: string | undefined, value: string | undefined ) {
```
Comment (roykho) [inline plugins/woocommerce-blocks/assets/js/blocks/product-filters/utils/get-colors-from-block-supports.ts]: I believe this is already available here: https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce-blocks/assets/js/blocks/product-filters/utils/colors/index.ts#L13

**Review by roykho — APPROVED** [review]
Great work and thanks for the fix. I've left a comment on potentially duplicated code. But other than that LGTM so I will pre-approve this.

File: plugins/woocommerce-blocks/assets/js/blocks/product-filters/inner-blocks/price-filter/edit.tsx [hunk 2]
```diff
@@ -32,10 +36,13 @@ const Edit = ( props: BlockEditProps< BlockAttributes > ) => {
...
-		clientId,
-		showClearButton: clearButton,
-	} );
+	useEffect( () => {
+		toggleProductFilterClearButtonVisibility( {
+			clientId,
+			showClearButton: clearButton,
+		} );
+		// eslint-disable-next-line react-hooks/exhaustive-deps
+	}, [] );
```
Comment (dinhtungdu) [inline plugins/woocommerce-blocks/assets/js/blocks/product-filters/inner-blocks/price-filter/edit.tsx]: So we still have to use a hook? It sounds like we're going in a full circle 😂

**Comment by dinhtungdu** [comment]
> > If you default the clear button to false in block.json. The editor and frontend still displays the clear button.
>
> I fixed the issue in: https://github.com/woocommerce/woocommerce/commit/d419c67a0ac8c457edd71c9c7869e4027ca0db8c

@thealexandrelara that issue doesn't really belong to the scope of this PR. The clear button still displays because it's listed in the block template, for example: 
https://github.com/woocommerce/woocommerce/blob/1d26d2d944639720a7d20ad53518f035a3e79d69/plugins/woocommerce-blocks/assets/js/blocks/product-filters/inner-blocks/price-filter/edit.tsx#L95-L103

I don't think using the hook is the right fix in this case. Instead, we should take the default value into account in the block template. The utility only needs to be executed in the callback of the inspector setting.

File: plugins/woocommerce-blocks/assets/js/blocks/product-filters/inner-blocks/price-filter/edit.tsx (hunk 2 above)
Comment (thealexandrelara) [reply plugins/woocommerce-blocks/assets/js/blocks/product-filters/inner-blocks/price-filter/edit.tsx:45]: Unfortunately yes 😅, it’s necessary due to the way React handles component lifecycles. The advantage of this new approach is that it will only run when the component mounts for the first time and when the attribute changes. The previous approach was triggered on every render but included a conditional to prevent the code from running every time.

File: plugins/woocommerce-blocks/assets/js/blocks/product-filters/utils/colors/index.ts [hunk 3]
```diff
@@ -10,15 +10,15 @@ import { paramCase as kebabCase } from 'change-case';
  * @param {string} value Value of the color.
  * @return {string} CSS variable value.
  */
-function getCSSVar(
+export function getCSSVar(
```
Comment (dinhtungdu) [inline plugins/woocommerce-blocks/assets/js/blocks/product-filters/utils/colors/index.ts]: This needs more specific naming, as the variable is only for color, while we have more styles, for example, spacing.

**Review by dinhtungdu — APPROVED** [review]
Thanks for the update! This looks good to me now. Left a minor comment but preapproving this one! Great work!

File: plugins/woocommerce-blocks/assets/js/blocks/product-filters/utils/colors/index.ts (hunk 3 above)
Comment (thealexandrelara) [reply plugins/woocommerce-blocks/assets/js/blocks/product-filters/utils/colors/index.ts]: Great suggestion! I renamed and started reusing this util function in other places: https://github.com/woocommerce/woocommerce/pull/52678/commits/1b2a1ba1a6d9baebcc6a9f86c87ce2b0fdc7f66e

**Comment by thealexandrelara** [comment]
> I don't think using the hook is the right fix in this case. Instead, we should take the default value into account in the block template. The utility only needs to be executed in the callback of the inspector setting.

That's correct, I changed that to your suggestion in 7e90194e01c28debb87fa34284487913e831275d. I'll wait for the pipeline to pass then I'll merge the PR. Thank you all for your reviews!
