### PR TITLE
Properly convert shorthand date queries in local time to UTC

### LINKED ISSUE #39927: wc_get_orders() date query not working with local timezone
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When using wc_get_orders with date queries the documentation says to use date strings (YYYY-MM-DD) to query in local timezone and unix timestamps to query in UTC timezone: [Documentation](https://github.com/woocommerce/woocommerce/wiki/wc_get_orders-and-WC_Order_Query#date)

This was also working before the switch to HPOS. Now when I query with date strings, I also get orders matching the requested strings but in UTC timezone. I.e. my timezone is  (UTC+2), when I try to query orders for the current day, I get all orders after 2 am instead of orders from 0:00.

I've implemented a fix in my code to convert timestamps to UTC and query that way. But I think this should be addressed.

### Expected behavior

Query:

`$query = wc_get_orders( array(
			'date_created' => date_i18n('Y-m-d'),
			'type'         => 'shop_order',
			'limit'        => - 1,
			'status'       => array_keys( wc_get_order_statuses() ),
		) );`

Returns orders done in shop of current day (starting 0:00)

### Actual behavior

Query:

`$query = wc_get_orders( array(
			'date_created' => date_i18n('Y-m-d'),
			'type'         => 'shop_order',
			'limit'        => - 1,
			'status'       => array_keys( wc_get_order_statuses() ),
		) );`

Returns orders done in shop of current day (starting 2:00 --> UTC time offset)

### Steps to reproduce

Do queries with code.

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): http://gut-betucht.test
Site address (URL): http://gut-betucht.test
WC Version: 8.0.2
REST API Version: ✔ 8.0.2
WC Blocks Version: ✔ 10.6.5
Action Scheduler Version: ✔ 3.6.1
Log Directory Writable: ✔
WP Version: 6.3
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: de_DE
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.47 (Win64) OpenSSL/1.1.1q PHP/8.2.9
PHP Version: 8.2.9
PHP Post Max Size: 2 GB
PHP Time Limit: 36000
PHP Max Input Vars: 1000
cURL Version: 7.85.0
OpenSSL/3.0.8

SUHOSIN Installed: –
MySQL Version: 5.7.33
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.0.2
WC Database Prefix: wp_
Datenbank-Gesamtgröße: 402.30MB
Datenbank-Datengröße: 316.03MB
Datenbank-Indexgröße: 86.27MB
wp_woocommerce_sessions: Daten: 0.02MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_api_keys: Daten: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_woocommerce_attribute_taxonomies: Daten: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_woocommerce_downloadable_product_permissions: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_order_items: Daten: 1.33MB + Index: 0.63MB + Engine MyISAM
wp_woocommerce_order_itemmeta: Daten: 8.76MB + Index: 6.04MB + Engine MyISAM
wp_woocommerce_tax_rates: Daten: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_woocommerce_tax_rate_locations: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_shipping_zones: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_shipping_zone_locations: Daten: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_woocommerce_shipping_zone_methods: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_payment_tokens: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_payment_tokenmeta: Daten: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_woocommerce_log: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_actionscheduler_actions: Daten: 3.90MB + Index: 1.73MB + Engine MyISAM
wp_actionscheduler_claims: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_actionscheduler_groups: Daten: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_actionscheduler_logs: Daten: 2.71MB + Index: 1.59MB + Engine MyISAM
wp_advanced_notifications: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_advanced_notification_triggers: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_berocket_termmeta: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_commentmeta: Daten: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_comments: Daten: 7.59MB + Index: 3.24MB + Engine MyISAM
wp_edp_remote_image_ids: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ewwwio_queue: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_gbak_contest: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_gbwc_babywearing_consultancy_appointments: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gbwc_custom_shipping_labels: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_gbwc_order_item_packaging: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gbwc_print_node_keys: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gbwc_product_filter_data: Daten: 2.02MB + Index: 0.00MB + Engine InnoDB
wp_gbwc_product_waitlists: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gbwc_shipping_barcodes: Daten: 0.17MB + Index: 0.02MB + Engine MyISAM
wp_gbwc_shipping_stamps: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_gbwc_shipping_tracking_information: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_gbwc_shippment_tracking: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_gbwc_stockkeeping: Daten: 0.16MB + Index: 0.00MB + Engine InnoDB
wp_gbwc_stock_boxes: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gbwc_stock_boxes_free_text: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gbwc_stock_shelves: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gbwc_stock_shelves_products: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_instock_email_alert: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_links: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mame_ws_addition: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mame_ws_address: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mame_ws_category: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mame_ws_category_to_media_type: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mame_ws_country: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mame_ws_custom_media: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mame_ws_license: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mame_ws_media: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mame_ws_media_type: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mame_ws_message: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mame_ws_order: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mame_ws_order_item: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mame_ws_product: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mame_ws_product_list: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mame_ws_stamp: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mame_ws_template: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mame_ws_zone: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mobileassistant_accounts: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mobileassistant_devices: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mobileassistant_failed_login: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mobileassistant_push_settings: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mobileassistant_session_keys: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mobileassistant_users: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_nextend2_image_storage: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_nextend2_section_storage: Daten: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_nextend2_smartslider3_generators: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_nextend2_smartslider3_sliders: Daten: 0.01MB + Index: 0.00MB + Engine MyISAM
wp_nextend2_smartslider3_sliders_xref: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_nextend2_smartslider3_slides: Daten: 0.01MB + Index: 0.01MB + Engine MyISAM
wp_options: Daten: 3.65MB + Index: 0.43MB + Engine MyISAM
wp_postmeta: Daten: 144.54MB + Index: 24.61MB + Engine MyISAM
wp_posts: Daten: 76.63MB + Index: 2.35MB + Engine MyISAM
wp_post_smtp_logmeta: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_post_smtp_logs: Daten: 20.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_css: Daten: 0.09MB + Index: 0.00MB + Engine MyISAM
wp_revslider_layer_animations: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_revslider_navigations: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_revslider_sliders: Daten: 0.02MB + Index: 0.00MB + Engine MyISAM
wp_revslider_slides: Daten: 0.11MB + Index: 0.00MB + Engine MyISAM
wp_revslider_static_slides: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_termmeta: Daten: 0.06MB + Index: 0.04MB + Engine MyISAM
wp_terms: Daten: 0.02MB + Index: 0.04MB + Engine MyISAM
wp_term_relationships: Daten: 0.35MB + Index: 0.70MB + Engine MyISAM
wp_term_taxonomy: Daten: 0.03MB + Index: 0.02MB + Engine MyISAM
wp_tm_taskmeta: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_tm_tasks: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_usermeta: Daten: 2.85MB + Index: 1.76MB + Engine MyISAM
wp_users: Daten: 0.14MB + Index: 0.16MB + Engine MyISAM
wp_wc_admin_notes: Daten: 0.07MB + Index: 0.00MB + Engine MyISAM
wp_wc_admin_note_actions: Daten: 0.04MB + Index: 0.01MB + Engine MyISAM
wp_wc_category_lookup: Daten: 0.01MB + Index: 0.01MB + Engine MyISAM
wp_wc_customer_lookup: Daten: 0.19MB + Index: 0.16MB + Engine MyISAM
wp_wc_download_log: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_orders: Daten: 2.52MB + Index: 2.20MB + Engine InnoDB
wp_wc_orders_meta: Daten: 25.56MB + Index: 31.23MB + Engine InnoDB
wp_wc_order_addresses: Daten: 2.52MB + Index: 3.97MB + Engine InnoDB
wp_wc_order_coupon_lookup: Daten: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_order_operational_data: Daten: 1.52MB + Index: 0.50MB + Engine InnoDB
wp_wc_order_product_lookup: Daten: 0.57MB + Index: 0.59MB + Engine MyISAM
wp_wc_order_stats: Daten: 0.26MB + Index: 0.17MB + Engine MyISAM
wp_wc_order_tax_lookup: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_product_attributes_lookup: Daten: 0.28MB + Index: 0.25MB + Engine InnoDB
wp_wc_product_download_directories: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Daten: 0.30MB + Index: 0.38MB + Engine MyISAM
wp_wc_rate_limits: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Daten: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_wallee_attribute_options: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_wallee_completion_job: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_wallee_method_config: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_wallee_refund_job: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_wallee_token_info: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_wallee_transaction_info: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_wallee_void_job: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_webhooks: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wflivetraffichuman: Daten: 0.01MB + Index: 0.02MB + Engine MyISAM
wp_wftrafficrates: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_gpf_google_taxonomy: Daten: 0.86MB + Index: 0.00MB + Engine MyISAM
wp_woof_query_cache: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_yoast_indexable: Daten: 5.52MB + Index: 2.75MB + Engine InnoDB
wp_yoast_indexable_hierarchy: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_yoast_migrations: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_primary_term: Daten: 0.11MB + Index: 0.13MB + Engine InnoDB

### Post Type Counts ###

amn_exact-metrics: 1
anmeldung: 6
attachment: 4547
br_filters_group: 1
br_product_filter: 8
gbkr_anfragen: 31
gbkr_kurs: 30
gbkr_kursleiter: 10
gk_anmeldung: 2
gk_kurse: 3
gk_kursorte: 1
gk_themen: 3
global_product_addon: 2
kanga: 2
kanga_anmeldung: 271
kanga_kurs: 27
kanga_kursort: 3
message: 560
nachricht: 9
nav_menu_item: 113
oembed_cache: 2
outdoor_kanga: 1
page: 21
post: 3
product: 1671
product_variation: 2566
returns: 131
revision: 351
shipping_rules: 6
shop_coupon: 1369
shop_order: 7090
shop_order_refund: 240
trageberatung: 147
trainer: 2
waitlist: 4
wapl: 1
wc_order_email: 1
wc_order_status: 7
yith-wcbm-badge: 2
yith-wccos-ostatus: 4
yith-wcet-etemplate: 1
ywcm_message: 1
ywtm_tab: 1

### Security ###

Secure connection (HTTPS): ❌
					Dein Shop benutzt kein HTTPS. Erfahre mehr über HTTPS und SSL-Zertifikate.
Hide errors from visitors: ✔

### Active Plugins (11) ###

Post SMTP: von Post SMTP – 2.5.9.3
Black Studio TinyMCE Widget: von Black Studio – 2.7.2
Classic Editor: von WordPress-Mitwirkende – 1.6.3
Debug Bar: von wordpressdotorg – 1.1.4
Disable Comments: von WPDeveloper – 2.4.4
Gut Betucht Woocommerce: von Lukas Connolly – 1.0.0
Kanga Kurse: von Lukas Connolly – 2.1.0
Simply Show Hooks: von Stuart O'Brien
cxThemes – 1.2.1

UpdraftPlus - Backup/Restore: von UpdraftPlus.Com
DavidAnderson – 2.23.9.1

WooCommerce: von Automattic – 8.0.2
WP Crontrol: von John Blackbourn & Mitwirkende – 1.15.3

### Must Use Plugins (2) ###

DEV Plugin: von Lukas Connolly – 1.0.0
everyday-master.php: von  –

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: CHF (CHF)
Currency Position: right_space
Thousand Separator: '
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: –
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: ✔

### WC Pages ###

Shop-Basis: #203 - /shop/
Warenkorb: #8 - /cart/
Kasse: #9 - /checkout/
Mein Konto: #10 - /mein-account/
Allgemeine Geschäftsbedingungen: #177 - /allgemeine-geschaeftsbedingungen-agb/

### Theme ###

Name: Gut Betucht Theme
Version: 0.1
Author URL: https://connollyweb.ch/
Child Theme: ❌ – Wenn du WooCommerce mit einem Theme
das du nicht selbst entwickelt hast
an eigene Bedürfnisse anpasst
dann empfehlen wir die Verwendung eines Child-Themes. Siehe Wie du ein Child-Theme erstellst (engl.)

WooCommerce Support: ✔

### Templates ###

Overrides: gut-betucht-theme/woocommerce/archive-product.php
gut-betucht-theme/woocommerce/cart\cart-shipping.php
gut-betucht-theme/woocommerce/checkout\form-billing.php
gut-betucht-theme/woocommerce/checkout\form-checkout.php
gut-betucht-theme/woocommerce/checkout\form-shipping.php
gut-betucht-theme/woocommerce/checkout\payment-method.php
gut-betucht-theme/woocommerce/checkout\terms.php
gut-betucht-theme/woocommerce/emails\email-footer.php
gut-betucht-theme/woocommerce/emails\email-header.php
gut-betucht-theme/woocommerce/product-searchform.php
gut-betucht-theme/woocommerce/single-product.php

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
product-variation-management
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2023-08-27 21:52:30 +02:00
Options: ✔
Notes: 132
Onboarding: completed

### Action Scheduler ###

Abgeschlossen: 12.924
Oldest: 2023-08-02 12:36:14 +0200
Newest: 2023-08-27 11:53:14 +0200

Fehlgeschlagen: 9
Oldest: 2020-04-12 23:52:32 +0200
Newest: 2023-06-08 23:15:13 +0200

Ausstehend: 2
Oldest: 2023-08-28 11:53:14 +0200
Newest: 2023-08-31 22:59:41 +0200

### Status report information ###

Generated at: 2023-08-27 11:55:07 +02:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by jorgeatorres**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

According to [our own docs](https://github.com/woocommerce/woocommerce/wiki/wc_get_orders-and-WC_Order_Query#date) when a query involves properties `date_created`, `date_updated`, `date_paid` and `date_completed` the expectation is that local time will be used (except when explicitly using the `_gmt` variants of those properties).

In particular, a query such as `['date_created' => '2023-09-10']` should return all orders created on 2023-09-10 in local time, but it is currently returning all orders created on `2023-09-10` in UTC, which is not necessarily the same.

For example, for a site in UTC+2, a query for orders created on 2023-09-10 (local time) should include all those created between 2023-09-09 22:00 and 2023-09-10 22:00, but should not include any orders between 22:00 and 23:59:59 UTC on the 10th. 

This PR introduces a few changes to how we deal with these queries, but the main change is that when querying a specific date (in local time) we convert that to the appropriate UTC-based date query.

It also fixes a query in the orders list table that resulted in the dates filter showing dates in UTC time instead of local time (despite the filtering always occurring in local time).

Closes #39927.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

That unit tests (which involve date queries) continue to pass is a good sign, but you can also confirm that things are looking ok via the admin:

1. Make sure HPOS is enabled: **High-performance order storage** should be selected as **Order data storage** in WC > Settings > Advanced > Features.
2. Change your site timezone to **UTC+2** in Settings > General.
3. Go to WC > Orders and click **Add order**.
4. Enter any details you want for this order but make sure that _Date created_ is **2023-09-01 01:00**. Click **Create** to save the order.
5. Repeat steps 3-4 but this time setting _Date created_ to **2023-10-31 00:00**.
6. Go to WC > Orders.
7. Confirm that the dates filter ("All Dates" dropdown) shows both September 2023 and October 2023.
8. Confirm that selecting one of these months and clicking **Filter** results in the appropriate order(s) being shown.

**Optional:** Contrast the above with current `trunk`, which would show August 2023 and September 2023 in the dropdown, and will display the Sept order in Aug, and the Oct order in Sep.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce/src/Internal/Admin/Orders/ListTable.php [hunk 1]
```diff
@@ -711,20 +711,15 @@ private function months_filter() {
...
-				FROM $orders_table
-
-				WHERE status NOT IN (
-					'trash'
-				)
-
-				ORDER BY year DESC, month DESC;
+				SELECT DISTINCT YEAR( t.date_created_local ) AS year,
+								MONTH( t.date_created_local ) AS month
+				FROM ( SELECT DATE_ADD( date_created_gmt, INTERVAL $utc_offset SECOND ) AS date_created_local FROM $orders_table WHERE status != 'trash' ) t
```
Comment (vedanshujain) [inline plugins/woocommerce/src/Internal/Admin/Orders/ListTable.php:721]: not pertinant to this PR, but should be cache this query? it oftens show up in slow query log (as it needs to scan the full index)

**Review by vedanshujain — COMMENTED** [review]
Looks good and testing instructions works as expected. Although, this can use some unit test (note that tests in OrdersTableDataStoreTests class runs in Asia/Kolkata timezone if that's helpful).

**Comment by jorgeatorres** [comment]
@vedanshujain: I've added some unit tests as requested. Let me know what you think.

**Review by Konamiman — APPROVED** [review]
