### PR TITLE
Preserve manual discount when manually editing an order

### LINKED ISSUE #60235: [WC 10.1 RC1/2] Item price edit is broken when manually editing an order
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

This is a regression from WC 10.0.
We don't see the details about the discount and the final price is wrong (missing the discount).

### Expected behavior

WC 10.0.4 (last stable)

https://github.com/user-attachments/assets/b28d2125-85c8-4363-a559-b665f3622064

### Actual behavior

WC 10.1.0-rc.2

https://github.com/user-attachments/assets/1e26fdf4-3b29-4365-bf52-eb247db6095b

### Steps to reproduce

1. Create a new order from the backend
2. Click on "Add Item(s)"
3. Add a product
4. On the product item line, click the pencil icon to edit the price
5. Change the value "Before discount" and hit enter

### WordPress Environment

<details>

<summary>WordPress Environment</summary>

The System Status Report is found in your WordPress admin under **WooCommerce > Status**. 
Please select “Get system report”, then “Copy for GitHub”, and then paste it here.

</details>

### Isolating the problem

- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by NeosinneR**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

**Note: this is targeting 10.1 milestone, to be included in next week's 10.1 release.** 

In https://github.com/woocommerce/woocommerce/pull/59606 we added a fix, that when manually editing an order with a coupon code, increasing item quantity wouldn't cause the discount to be greater than the coupon's value. This was done by calling `$order->recalculate_coupons();` on order items save. 

However, this introduced an issue when manually adding a discount to the order without using any coupon code:
Screenshot 2025-08-07 at 08 20 59

In this case, calling `$order->recalculate_coupons();` removes the discount, because there is no coupon associated so the order items totals are recalculated to remove the discount (i.e., so the discount is not greater than $0). 

The fix is to only call `$order->recalculate_coupons();` when a coupon code is associated with the order. 

Closes #60235, closes WOOPLUG-5271.

(For Bug Fixes) Bug introduced in PR #59606.

### Screenshots or screen recordings:

| Before | After |
| ------ | ----- |
|     Screenshot 2025-08-07 at 08 20 25   |    Screenshot 2025-08-07 at 08 20 45   |

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Go to **WooCommerce > Orders > Add orde**.
2. Add any product. 
3. Edit order item (the pencil icon).
4. Update prices so `Before discount` is greater than `Total`.
5. Click `Save` and check, that the discount is applied.

### CODE REVIEW

File: plugins/woocommerce/includes/admin/wc-admin-functions.php [hunk 1]
```diff
@@ -454,7 +454,14 @@ function wc_save_order_items( $order_id, $items ) {
 	}
 
 	$order->update_taxes();
-	$order->recalculate_coupons();
+
+	// Only recalculate when a coupon is applied.
+	// This allows manual discounts to be preserved when order items are saved.
+	$order_coupons = $order->get_items( 'coupon' );
```
Comment (yuliyan) [inline plugins/woocommerce/includes/admin/wc-admin-functions.php]: Nit: Could use `$order->get_coupons()` instead.

**Review by yuliyan — COMMENTED** [review]
I've confirmed that with these changes, adding a manual discount works as expected when no coupon is applied.

However, when a coupon is applied, modifying the item discount manually has no effect. Just wanted to confirm if this is the intended behavior.

File: plugins/woocommerce/includes/admin/wc-admin-functions.php (hunk 1 above)
Comment (NeosinneR) [reply plugins/woocommerce/includes/admin/wc-admin-functions.php]: Fixed in https://github.com/woocommerce/woocommerce/pull/60240/commits/6b5ab8c0591897a4e33ecfe0d5714cb15ec596bf

**Comment by NeosinneR** [comment]
> However, when a coupon is applied, modifying the item discount manually has no effect. Just wanted to confirm if this is the intended behavior.

@yuliyan correct. I also noticed this. I don't think there is anything we can do, because the coupon code is not directly tied to specific order item, but rather it's proportionally divided to all order items. And to preserve the original fix from https://github.com/woocommerce/woocommerce/pull/59606 to prevent applying discount bigger than the coupon amount, any other manual discount is discarded.

**Review by yuliyan — APPROVED** [review]
LGTM!
