### PR TITLE
Fix Blockified Add to cart and Options button cart count on variable products 

### LINKED ISSUE #58683: Add to Cart + Options: 'X in cart' count in Product Button doesn't update properly when a variation accepts 'any' for one attribute
When a variation allows 'any' in at least one of the attributes, the 'X in cart' counter in the Add to Cart button doesn't work properly and gets stuck at the value of the first variation added to the cart.

#### Preparation

1. Install and activate the [WooCommerce Beta Tester](https://woocommerce.com/products/woocommerce-beta-tester/) extension.
2. Go to *WooCommerce Admin Test Helper* > *Features* and enable `experimental-blocks` and `blockified-add-to-cart`.
3. Go to *Appearance* > *Editor* > *Templates* > *Single Product*.
4. Click on the *Add to Cart with Options* block and update to the blockified version.

#### Reproducing the issue

1. Create a variable product with one variation that has 'Any' as one of the parameters.

2. In the frontend, add that product to the cart, notice the Add to Cart button updates with '1 in cart', '2 in cart', etc.
3. Now, change the attribute which the variation allows 'any' value.
4. Keep adding products to cart.
5. Notice the Add to Cart button text no longer updates.

[Enregistrament de pantalla a 2025-06-10 15-20-27.mp4](https://uploads.linear.app/f629fcde-6f9b-48e8-8af3-60eed8823bff/fd7269db-7e73-48d6-a193-2a7955f087d1/92808abb-92d6-4e7c-a266-3c1325cb8bb9?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2Y2MjlmY2RlLTZmOWItNDhlOC04YWYzLTYwZWVkODgyM2JmZi9mZDcyNjlkYi03ZTczLTQ4ZDYtYTE5My0yYTc5NTVmMDg3ZDEvOTI4MDhhYmItOTJkNi00ZTdjLWEyNjYtM2MxMzI1Y2I4YmI5IiwiaWF0IjoxNzQ5NTYxODQ5LCJleHAiOjMzMzIwMTIxODQ5fQ.QfnZVaiNpC5u5uM3Rly6u5toefRO89NjAOWfUbQgJIQ)

### PR DESCRIPTION
**Pull request by Kallyan01**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

This PR fixes an issue in `Blockified Add to Cart and Options` button cart quantity calculation where items with the same variationId but different attribute combinations (e.g., Size, Color) .It's being treated as the same, resulting in incorrect quantity totals.

To address this, a utility function `getMatchedCartItem()` was introduced. It performs a deep comparison of variation attributes between the cart item and the selected variation, ensuring quantity is calculated only for exact attribute matches, even when variationId is shared.

Closes #58683 .

### Screenshots or screen recordings:

**After :**

https://github.com/user-attachments/assets/c2fcec48-e288-4c60-a298-1089b803f0db 

**Before :**

https://github.com/user-attachments/assets/bdee99cb-6097-4ba4-ad0d-5c375b7b6a1b 

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Navigate to the Admin Dashboard and open the Products page.
2. Edit a variable product that has multiple variations.
3. Scroll down to the Product data section and click the Variations tab.
4. In one of the variation rows, set one or more attribute dropdowns (e.g., Color, Size) to `Any` instead of selecting a specific value (e.g., Color → red, Size → XL etc).
5. Save the product changes.
6. Visit the store and open the single product page for the product you just updated.
7. Select variation options on the product page where one or more attributes match the Any setting.
8. Add the product to the cart and observe the cart item count in the "Add to cart" button.
   - Ensure that it reflects the correct quantity .

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce/client/blocks/assets/js/atomic/blocks/product-elements/button/frontend.ts [hunk 1]
```diff
@@ -51,14 +52,51 @@ const { state: addToCartWithOptionsState } = store< AddToCartWithOptionsStore >(
...
+					.toLowerCase();
+				const selectedItemValue = item.value.toLowerCase();
+
+				if (
+					selectedItemAttr === attribute.toLowerCase() &&
+					( selectedItemValue === value.toLowerCase() ||
+						( item.value && value === '' ) )
+				) {
+					return true;
+				}
```
Comment (Aljullu) [inline plugins/woocommerce/client/blocks/assets/js/atomic/blocks/product-elements/button/frontend.ts]: This is a bit problematic because we are comparing the attribute display name with its key. Ie `Logo` with `attribute_logo`. The current transformation works well with words without special characters, but it might fail otherwise. Internally, WooCommerce [uses `sanitize_title()`](https://github.com/woocommerce/woocommerce/blob/f3ac26246c85635bd688baa13a420d3562cebd1b/plugins/woocommerce/includes/wc-attribute-functions.php#L151) to generate the attribute key, but we don't have an equivalent in the JS side.

To solve this, `cartItem.variation` should ideally have the raw attribute key, without formatting. We can add it from `ProductItemTrait.php` ([L77-L80](https://github.com/woocommerce/woocommerce/blob/b85c17e74186e635e814d22eae28ca3f4ca94eb3/plugins/woocommerce/src/StoreApi/Utilities/ProductItemTrait.php#L77-L80)), something along these lines:

```diff
$return[] = [
+ 	'raw_attribute' => $this->prepare_html_response( $key ),
	'attribute'     => $this->prepare_html_response( $label ),
	'value'         => $this->prepare_html_response( $value ),
];
```

If you do that, you should have `raw_attribute` available here, so you can make the comparison easier and more reliable. :slightly_smiling_face:

**Review by Aljullu — COMMENTED** [review]
Thanks for working on this, @Kallyan01! Overall it works well and fixes the issue, but I noticed that this PR seems to have broken the "X in cart" text appearing in simple products. Can you reproduce too? I guess in `getMatchedCartItem()` we should return early if it's not a variation. I also left an inline comment below about the way we are comparing the attribute keys.

Btw, it would be a good idea to check the Code Rabbit [nitpick comments](https://github.com/woocommerce/woocommerce/pull/59274#pullrequestreview-2970960260), as some of them sound like good improvements.

File: plugins/woocommerce/client/blocks/assets/js/atomic/blocks/product-elements/button/frontend.ts [hunk 2]
```diff
@@ -51,14 +55,59 @@ const { state: addToCartWithOptionsState } = store< AddToCartWithOptionsStore >(
...
+	);
+};
+
 const productButtonStore = {
 	state: {
 		get quantity(): number {
-			const product = wooState.cart?.items.find(
-				( item ) => item.id === state.productId
+			const selectedAttribute =
+				addToCartWithOptionsState?.selectedAttributes;
```
Comment (Aljullu) [inline plugins/woocommerce/client/blocks/assets/js/atomic/blocks/product-elements/button/frontend.ts]: I would move this directly before the line where `selectedAttribute` is used. Right before:

```JS
const selectedProduct = product.find( ( item ) =>
	getMatchedCartItem( item, selectedAttribute )
);
```

File: plugins/woocommerce/client/blocks/assets/js/atomic/blocks/product-elements/button/frontend.ts [hunk 3]
```diff
@@ -51,14 +55,59 @@ const { state: addToCartWithOptionsState } = store< AddToCartWithOptionsStore >(
...
+
+			const product = wooState.cart?.items.filter( ( item ) => {
```
Comment (Aljullu) [inline plugins/woocommerce/client/blocks/assets/js/atomic/blocks/product-elements/button/frontend.ts]: Given that `.filter()` returns an array, I would rename this variable from `product` to `products`. What do you think?

File: plugins/woocommerce/client/blocks/assets/js/atomic/blocks/product-elements/button/frontend.ts [hunk 4]
```diff
@@ -51,14 +55,59 @@ const { state: addToCartWithOptionsState } = store< AddToCartWithOptionsStore >(
...
+				if ( item.id === state.productId ) {
+					return item;
+				}
```
Comment (Aljullu) [inline plugins/woocommerce/client/blocks/assets/js/atomic/blocks/product-elements/button/frontend.ts]: Heads-up that the `.filter()` inner function needs to return a boolean. In this case, I think it could be `return item.id === state.productId`.

File: plugins/woocommerce/client/blocks/assets/js/atomic/blocks/product-elements/button/frontend.ts [hunk 5]
```diff
@@ -51,14 +55,59 @@ const { state: addToCartWithOptionsState } = store< AddToCartWithOptionsStore >(
...
+		( {
+			raw_attribute,
+			value,
+		}: {
+			raw_attribute: string;
+			value: string;
+		} ) =>
+			selectedItem.some( ( item ) => {
+				const selectedItemAttr = item.attribute;
+				const selectedItemValue = item.value.toLowerCase();
```
Comment (Aljullu) [inline plugins/woocommerce/client/blocks/assets/js/atomic/blocks/product-elements/button/frontend.ts]: Nitpick: I would remove these assignments and instead use `item.attribute` and `item.value` directly in the return below. I think it will make it easier to understand.

**Review by Aljullu — COMMENTED** [review]
Thanks for the updates, @Kallyan01! This is working well on my end and confirming the button in simple products works well, too.

I left some minor comments below about code style. There are also some [linting errors](https://github.com/woocommerce/woocommerce/actions/runs/16027246530/job/45273905198?pr=59274) that might be worth reviewing.

Btw, did you get the chance to review [Code Rabbit's nitpick comments](https://github.com/woocommerce/woocommerce/pull/59274#pullrequestreview-2970960260)? I think most of them would be good to implement to improve code legibility.

**Comment by Kallyan01** [comment]
> Thanks for the updates, @Kallyan01! This is working well on my end and confirming the button in simple products works well, too.
> 
> I left some minor comments below about code style. There are also some [linting errors](https://github.com/woocommerce/woocommerce/actions/runs/16027246530/job/45273905198?pr=59274) that might be worth reviewing.
> 
> Btw, did you get the chance to review [Code Rabbit's nitpick comments](https://github.com/woocommerce/woocommerce/pull/59274#pullrequestreview-2970960260)? I think most of them would be good to implement to improve code legibility.

Sorry @Aljullu , i've overlooked the nitpick comments as they were hidden , Will go through them and implement them shortly . Thanks for pointing it out .

File: plugins/woocommerce/client/blocks/assets/js/atomic/blocks/product-elements/button/frontend.ts [hunk 6]
```diff
@@ -51,14 +55,58 @@ const { state: addToCartWithOptionsState } = store< AddToCartWithOptionsStore >(
...
 		get quantity(): number {
-			const product = wooState.cart?.items.find(
+			const products = wooState.cart?.items.filter(
 				( item ) => item.id === state.productId
 			);
 
-			return product?.quantity || 0;
+			// Return the product quantity when the item is a non-variable product.
+			if ( products[ 0 ]?.type !== 'variation' ) {
+				return products[ 0 ]?.quantity;
```
Comment (Aljullu) [inline plugins/woocommerce/client/blocks/assets/js/atomic/blocks/product-elements/button/frontend.ts]: Just in case, should this still be:

```suggestion
				return products[ 0 ]?.quantity || 0;
```

File: plugins/woocommerce/client/blocks/assets/js/atomic/blocks/product-elements/button/frontend.ts [hunk 7]
```diff
@@ -51,14 +55,58 @@ const { state: addToCartWithOptionsState } = store< AddToCartWithOptionsStore >(
...
 
+const isCartItemMatched = (
+	cartItem: OptimisticCartItem,
+	selectedItem: CartVariationItem[]
+) => {
+	if (
+		! Array.isArray( cartItem.variation ) ||
+		! Array.isArray( selectedItem )
+	)
+		return false;
```
Comment (Aljullu) [inline plugins/woocommerce/client/blocks/assets/js/atomic/blocks/product-elements/button/frontend.ts]: Small formatting suggestion, but we usually try to wrap clauses with `{ ... }`:

```suggestion
	if (
		! Array.isArray( cartItem.variation ) ||
		! Array.isArray( selectedItem )
	) {
		return false;
	}
```

File: plugins/woocommerce/client/blocks/assets/js/atomic/blocks/product-elements/button/frontend.ts [hunk 8]
```diff
@@ -51,14 +55,58 @@ const { state: addToCartWithOptionsState } = store< AddToCartWithOptionsStore >(
...
+
+	// Incase the attributes list length is different in both the objects
```
Comment (Aljullu) [inline plugins/woocommerce/client/blocks/assets/js/atomic/blocks/product-elements/button/frontend.ts]: Comment formatting:

```suggestion
	// In case the attributes list length is different in both the objects.
```

**Review by Aljullu — APPROVED** [review]
Thanks for all the updates, @Kallyan01! This is working well on my end:

https://github.com/user-attachments/assets/660faafa-ec53-4733-89fb-4f1b8e610cd6

I left a couple of last comments inline, and there are some [linting errors](https://github.com/woocommerce/woocommerce/actions/runs/16049755545/job/45352879542?pr=59274). But besides that, LGTM.

<details>
<summary>Testing environment</summary>

* WordPress 6.8.1 local dev environment
* Plugins: WooCommerce Beta Tester
* Theme: Woo Starter Theme
* Store creation: June 2025
* Store size: small
</details>

File: plugins/woocommerce/src/StoreApi/Utilities/ProductItemTrait.php [hunk 9]
```diff
@@ -74,10 +74,11 @@ protected function format_variation_data( $variation_data, $product ) {
...
 
-			$return[] = [
-				'attribute' => $this->prepare_html_response( $label ),
-				'value'     => $this->prepare_html_response( $value ),
-			];
+			$return[] = array(
+				'raw_attribute' => $this->prepare_html_response( $key ),
+				'attribute'     => $this->prepare_html_response( $label ),
+				'value'         => $this->prepare_html_response( $value ),
+			);
```
Comment (Aljullu) [inline plugins/woocommerce/src/StoreApi/Utilities/ProductItemTrait.php:81]: @senadir I pinged Rubik for review for the changes in this file, as they affect the `cart` endpoint in the Store API. The _tl;dr_ is that we are introducing the `raw_attribute` key to variation data, this is needed in the frontend because `attribute` was the display name, so it couldn't be reliably matched to an attribute.

Comment (senadir) [reply plugins/woocommerce/src/StoreApi/Utilities/ProductItemTrait.php:81]: That's good and great! No objection from my side as Store API is compatible with adding things, can you possibly also document this?

Comment (Aljullu) [reply plugins/woocommerce/src/StoreApi/Utilities/ProductItemTrait.php:81]: Thanks, @senadir!

@Kallyan01 do you think we can include the updated docs in this PR? If I'm not wrong, we would only need to update _Example response_ in the _List Cart Items_ docs to include the `raw_attribute` key:

https://github.com/woocommerce/woocommerce/blob/1aa92f68805c83899b3d796c0396f7a4f4fdf127/docs/apis/store-api/resources-endpoints/cart-items.md#list-cart-items

Comment (Kallyan01) [reply plugins/woocommerce/src/StoreApi/Utilities/ProductItemTrait.php:81]: Yes @Aljullu we can do that , adding the changes shortly . Thanks !

**Review by Aljullu — COMMENTED** [review]
Thanks for the updates, @Kallyan01! Apparently, there are some [linting errors](https://github.com/woocommerce/woocommerce/actions/runs/16139662024/job/45557944157?pr=59274). Could you take a look at them?

And I originally missed it, but for tests to pass, you will need to add `raw_attribute` to the schema, too:

https://github.com/woocommerce/woocommerce/blob/65c7709097495ae0bda4e70fc3865cf129a51a97/plugins/woocommerce/src/StoreApi/Schemas/V1/ItemSchema.php#L141-L163

**Comment by Kallyan01** [comment]
> Thanks for the updates, @Kallyan01! Apparently, there are some [linting errors](https://github.com/woocommerce/woocommerce/actions/runs/16139662024/job/45557944157?pr=59274). Could you take a look at them?
> 
> And I originally missed it, but for tests to pass, you will need to add `raw_attribute` to the schema, too:
> 
> https://github.com/woocommerce/woocommerce/blob/65c7709097495ae0bda4e70fc3865cf129a51a97/plugins/woocommerce/src/StoreApi/Schemas/V1/ItemSchema.php#L141-L163

I'll add the schema changes .

```
. lint:lang:js:   77:4  error  Parameter name `raw_attribute` must match one of the following formats: camelCase, PascalCase, UPPER_CASE  @typescript-eslint/naming-convention
```
Should i add a ts error ignore comment for this one ?

**Comment by Aljullu** [comment]
> Should i add a ts error ignore comment for this one ?

Yes, I think we can keep it as `raw_attribute` and add a comment to ignore the rule in the affected lines.

**Comment by Kallyan01** [comment]
@Aljullu requested for review , could you please take a look ?

**Review by Aljullu — COMMENTED** [review]
Thanks for the update, @Kallyan01! I just noticed one more thing. When checking out this branch, I see TS errors in `add-to-cart-with-options/frontend.ts`:

imatge

Can you reproduce too? I didn't investigate it in detail, but I think in some places in that file we are using the `CartVariationItem` type when it should be a completely different type. :thinking:

**Comment by Kallyan01** [comment]
Thanks @Aljullu for pointing out the ts error , I have added `raw_attribute` to selectedAttributes obj , this change caused slight modification in the [ref](https://github.com/Kallyan01/woocommerce/blob/469b66c5d22c7c70891210be1f7a20ec4a8a3f5b/plugins/woocommerce/client/blocks/assets/js/atomic/blocks/product-elements/button/frontend.ts#L59) function . 

**Before :**
```js
selectedItem.some( ( item ) => {
				return (
					item.attribute === raw_attribute &&
					( item.value.toLowerCase() === value.toLowerCase() ||
						( item.value && value === '' ) ) // Handle "any" attribute type
				);
			} )
```

**After:**
```js
selectedItem.some( ( item ) => {
				return (
					item.raw_attribute === raw_attribute &&
					( item.value.toLowerCase() === value.toLowerCase() ||
						( item.value && value === '' ) ) // Handle "any" attribute type
				);
			} )
```

File: plugins/woocommerce/src/StoreApi/Schemas/V1/ItemSchema.php
Comment (Aljullu) [inline plugins/woocommerce/src/StoreApi/Schemas/V1/ItemSchema.php:1]: In this file, I think we should leave the array format as it was, to keep it consistent with the other schemas. So instead of `array()` it should be `[]`. I guess your editor formatted it automatically. :thinking:

File: plugins/woocommerce/client/blocks/assets/js/blocks/add-to-cart-with-options/frontend.ts [hunk 10]
```diff
@@ -195,15 +203,18 @@ const addToCartWithOptionsStore = store(
 					( selectedAttribute ) =>
 						selectedAttribute.attribute === attribute
 				);
+
 				if ( index >= 0 ) {
 					selectedAttributes[ index ] = {
 						attribute,
 						value,
+						raw_attribute: attribute,
```
Comment (Aljullu) [inline plugins/woocommerce/client/blocks/assets/js/blocks/add-to-cart-with-options/frontend.ts]: The solution here shouldn't be to add `raw_attribute` unnecessarily to match the type. Instead, I think we should create a new type specific for this:

```TS
type SelectedAttributes = Omit< CartVariationItem, 'raw_attribute' >;
```

And use it in [`selectedAttributes`](https://github.com/woocommerce/woocommerce/blob/23f9c0799e9991aecb2fb1ac3f01381f6f7b4a7c/plugins/woocommerce/client/blocks/assets/js/blocks/add-to-cart-with-options/frontend.ts#L21), [`variation`](https://github.com/woocommerce/woocommerce/blob/23f9c0799e9991aecb2fb1ac3f01381f6f7b4a7c/plugins/woocommerce/client/blocks/assets/js/blocks/add-to-cart-with-options/frontend.ts#L31), etc.

How does it sound?

**Review by Aljullu — COMMENTED** [review]
Thanks for the updates, @Kallyan01, I left a couple of extra comments inline. :point_down:

File: plugins/woocommerce/client/blocks/assets/js/blocks/add-to-cart-with-options/frontend.ts (hunk 10 above)
Comment (Kallyan01) [reply plugins/woocommerce/client/blocks/assets/js/blocks/add-to-cart-with-options/frontend.ts]: Yes @Aljullu, this approach makes sense and I agree it’s a better solution. However, when I initially attempted to implement it, I encountered new type errors in different [file](https://github.com/Kallyan01/woocommerce/blob/226fa3d3e7ef7b0fc0f7dc267bbbfb63a551c799/plugins/woocommerce/client/blocks/assets/js/atomic/blocks/product-elements/button/frontend.ts#L76) that would have required refactoring of the existing type definitions.So, I proceeded with the current approach as it was more straightforward .

I’ll revisit your suggestion and give it a second try by tomorrow 😄 .

Thanks !

**Review by Aljullu — COMMENTED** [review]
Thanks for the updates @Kallyan01! I left one minor comment about the types names, but besides that, everything is looking good to me.

**Comment by Kallyan01** [comment]
> Thanks for the updates @Kallyan01! I left one minor comment about the types names, but besides that, everything is looking good to me.

@Aljullu the comment isn't visible to me ! could you please check it once ?

File: plugins/woocommerce/client/blocks/assets/js/base/stores/woocommerce/cart.ts [hunk 11]
```diff
@@ -17,11 +17,18 @@ import type { Store as StoreNotices } from '@woocommerce/stores/store-notices';
...
 	key?: string;
 	id: number;
 	quantity: number;
 	variation?: CartVariationItem[];
+	type: string;
+};
+
+export type ClientCartItemType = Omit< OptimisticCartItem, 'variation' > & {
+	variation?: SelectedAttributesType[];
 };
```
Comment (Aljullu) [inline plugins/woocommerce/client/blocks/assets/js/base/stores/woocommerce/cart.ts]: I would remove the `Type` part from the types' name. This would keep them shorter and more in line with the other types, which don't contain it either. So they would become `SelectedAttributes` and `ClientCartItem`. How does it sound?

**Review by Aljullu — COMMENTED** [review]
Ups, my bad, forgot to save it. :man_facepalming: Posted it now again.

File: plugins/woocommerce/client/blocks/assets/js/base/stores/woocommerce/cart.ts (hunk 11 above)
Comment (Kallyan01) [reply plugins/woocommerce/client/blocks/assets/js/base/stores/woocommerce/cart.ts]: OK ! It sounds good to me , pushing the changes shortly .
Thanks !

**Comment by Kallyan01** [comment]
@Aljullu i've incorporated the suggested type defination changes , please do check it out and let me know if anything else need to be resolved .

Thanks !

**Review by Aljullu — COMMENTED** [review]
Thanks for the updates, @Kallyan01! Apparently there are some new [linting issues](https://github.com/woocommerce/woocommerce/actions/runs/16196542102/job/45724982548?pr=59274). Will you be able to take a look? :pray: 

You should be able to run lint locally by `pnpm --filter=@woocommerce/plugin-woocommerce lint` or `pnpm --filter=@woocommerce/plugin-woocommerce lint:php src/StoreApi/Schemas/V1/ItemSchema.php` if you want to check only one file.

**Comment by Kallyan01** [comment]
@Aljullu Sorry ! for the repeated linting issues , this issue was not being flagged on my local env for some odd reason , fixed it now , hopefully no more issues will be there related to linting 😄 .

**Review by Aljullu — COMMENTED** [review]
Thanks for updating it again, @Kallyan01! I did another round of testing, and noticed there are some TS errors in `variation-selector/attribute-options/frontend.tsx`, still:

imatge

Can you reproduce too?

(Sorry I missed those in previous reviews)

**Review by Aljullu — APPROVED** [review]
Thanks for all the updates and hard work, @Kallyan01! This LGTM and will ship with WooCommerce 10.1! :raised_hands:

**Comment by Kallyan01** [comment]
Thanks @Aljullu for your continus support throughout.
