### PR TITLE
Fix: missing handling for null meta keys/values in POST/PUT endpoints

### LINKED ISSUE #63849: PHP 8.x Warning: Undefined array key "value" in class-wc-rest-products-controller.php:1134
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

After upgrading from PHP 7.4 to PHP 8.x, a PHP warning appears in the error log on every REST API call that includes meta_data.

PHP Warning: Undefined array key "value" in .../Version3/class-wc-rest-products-controller.php on line 1134
The issue is a systematic pattern across multiple REST API controllers in both v2 and v3. $meta['id'] is correctly guarded with isset(), but $meta['key'] and $meta['value'] are not:

$product->update_meta_data( $meta['key'], $meta['value'], isset( $meta['id'] ) ? $meta['id'] : '' );

Notably, class-wc-rest-orders-v2-controller.php:910 does handle this correctly:
$value = isset( $meta['value'] ) ? $meta['value'] : null;

Affected files include: class-wc-rest-products-controller.php, class-wc-rest-product-variations-controller.php, class-wc-rest-orders-controller.php, class-wc-rest-order-refunds-controller.php (v3), and their v2 counterparts.

Suggested fix: Use $meta['value'] ?? null consistently across all controllers.

### Expected behavior

No PHP warnings should be generated when calling the WooCommerce REST API with product meta_data. Accessing an array key that may not exist should be handled gracefully.

### Actual behavior

The following warning is logged:
PHP Warning: Undefined array key "value" in .../rest-api/Controllers/Version3/class-wc-rest-products-controller.php on line 1134

### Steps to reproduce

WordPress + WooCommerce installed
PHP 8.x
Make a POST /wp-json/wc/v3/products REST API request with a meta_data entry missing the value key
Check PHP error log

### WordPress Environment

WordPress: 6.9.4
WooCommerce: 10.6.1
PHP: 8.4 
Server: Apache / Linux
WP Multisite: Yes

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by Konamiman**
### Changes proposed in this Pull Request:

WooCommerce has several REST API endpoints that allow to modify the metadata of varios entities like products and orders. The common JSON syntax for these is `"meta_data":[{"key":"the_key","value":"the_value"},{...` - where a null or missing value causes the key to be ignored on creation, and the metadata entry to be deleted on update.

There were two pieces of validation code missing in the corresponding controllers:

- No validation for missing key. This caused meta entries with an empty key to be created when metadata entries with no key were supplied.
- No validation for missing value, so accessing `$meta['value']` without verifying if 'value' actually exists in the array. This caused the value to be effectively evaluated as `null`,  but with an "undefined array key" notice (in PHP 7) or warning (in PHP 8) being generated.

This pull request fixes this in all the affected endpoints:

- Entries with no key aren't processed.
- Values are retrieved with `$meta['value'] ?? null`, so no notice/warning is generated.
- A new `MetaDataUtil` class encapsulates the normalize + update procedure in one single `update` method.

...and adds unit tests to verify that.

Full list of affected endpoints:

- `PUT /wc/v2/products/{id}`
- `PUT /wc/v2/products/{parent_id}/variations/{id}`
- `PUT /wc/v2/coupons/{id}`
- `PUT /wc/v2/customers/{id}`
- `POST /wc/v2/orders/{order_id}/refunds`
- `PUT /wc/v2/orders/{id}` (line items meta; already had the fix, just cleaned up to use `??`)
- `PUT /wc/v3/products/{id}`
- `PUT /wc/v3/products/{parent_id}/variations/{id}`
- `PUT /wc/v3/orders/{id}`
- `POST /wc/v3/orders/{order_id}/refunds`
- `PUT /wc/v3/coupons/{id}`
- `POST /wc/v4/refunds`
- `PUT /wc/v4/products/{id}`
- `PUT /wc/v4/orders/{id}`
- `PATCH /wc/v3/orders/{order_id}/fulfillments/{fulfillment_id}`
- `PATCH /wc/v3/orders/{order_id}/fulfillments/{fulfillment_id}/metadata`

Closes #63849.

### How to test the changes in this Pull Request:

The testing basically consists of creating some test metadata for one of the affected entities, then using the REST API to modify the metadata covering all cases (no key, no value, key and value) and verifying that:

- Null keys don't generate new meta entries.
- Null values work as expected and do NOT generate warnings (better to test in PHP 8.1+).
- Key+value creates or deletes the meta entry appropriately.

For example, for products, use this to create the meta entries:

```bash
curl -s "http://localhost/wp-json/wc/v3/products/<product id>" \
    -u <consumer key>:<consumer secret>
    -X PUT \
    -H "Content-Type: application/json" \
    -d '{"meta_data":[{"key":"key1","value":"value1"},{"key":"key2","value":"value2"},{"key":"key3","value":"value3"}]}'
```

Then run this:

```bash
curl -s "http://localhost/wp-json/wc/v3/products/<product id>" \
    -u <consumer key>:<consumer secret> \
    -X PUT \
    -H "Content-Type: application/json" \
    -d '{"meta_data":[{"value":"orphan"},{"key":"key1"},{},{"key":"key2","value":"another_value"}]}'
```

...and verify that:

- No new entries are created.
- `key1` has been deleted.
- `key2` has now `another_value`.
- `key3` is unchanged.

Verify also that no "undefined array key" warnings are generated in the WordPress log.

### Milestone

- [x] Automatically assign milestone for the **[next WooCommerce version](../blob/trunk/plugins/woocommerce/woocommerce.php#L6)**

> **Note:** Check the box above to have the milestone automatically assigned when merged.
> Alternatively (e.g. for point releases), manually assign the appropriate milestone.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce/tests/php/helpers/MetaDataAssertionTrait.php [hunk 1]
```diff
@@ -0,0 +1,58 @@
...
+			array(
+				'key'   => 'key_explicit_null',
+				'value' => null,
+			),
+			array(),
+			array(
+				'key'   => 'complete_key',
+				'value' => 'complete_value',
+			),
+		);
```
[the remark this answers is not in the document]
Comment (Konamiman) [reply plugins/woocommerce/tests/php/helpers/MetaDataAssertionTrait.php:34]: We have `isset( $meta['key'] )` checks everywhere, and this will effectively treat null keys the same way as non-existing keys. No need to explicitly test that.

File: plugins/woocommerce/includes/rest-api/Controllers/Version2/class-wc-rest-coupons-v2-controller.php [hunk 2]
```diff
@@ -311,7 +311,9 @@ protected function prepare_object_for_database( $request, $creating = false ) {
 					case 'meta_data':
 						if ( is_array( $value ) ) {
 							foreach ( $value as $meta ) {
-								$coupon->update_meta_data( $meta['key'], $meta['value'], isset( $meta['id'] ) ? $meta['id'] : '' );
+								if ( isset( $meta['key'] ) ) {
```
Comment (kalessil) [inline plugins/woocommerce/includes/rest-api/Controllers/Version2/class-wc-rest-coupons-v2-controller.php]: Can we implement a method for the REST and fulfillment controllers to normalize metadata, skipping entries without keys and applying necessary fallbacks?

EDIT: The root cause fix appears solid. We now need to apply DRY principles to improve the implementation.

**Review by kalessil — CHANGES_REQUESTED** [review]

File: plugins/woocommerce/includes/rest-api/Controllers/Version2/class-wc-rest-coupons-v2-controller.php (hunk 2 above)
Comment (Konamiman) [reply plugins/woocommerce/includes/rest-api/Controllers/Version2/class-wc-rest-coupons-v2-controller.php]: There's some "duplication" indeed, but we are talking about two-liners:

```
if ( isset( $meta['key'] ) ) {
  update_some_meta($meta['key'], $meta['value] ?? null);
}
```

Is it really worth replacing these with a one-line call to an utility method?

That said: if we consider it to be worth it, perhaps a follow-up refactoring pr would be more appropriate, leaving this one as bug fixing only.

Comment (kalessil) [reply plugins/woocommerce/includes/rest-api/Controllers/Version2/class-wc-rest-coupons-v2-controller.php]: I think we should implement this method in this PR (yes, it worth it):
- It should skip entries without a key
- it should apply `$meta['value'] ?? null`, `$meta['id'] ?? ''` to the entries as well (simplifies outer logic)
- then we can do `foreach ( $this->normalize_metas( $value ) as $meta ) {`

The diff will be small. Normalization will be handled in a single method, reducing the number of iterations needed to create, review, and test another PR.

Comment (Konamiman) [reply plugins/woocommerce/includes/rest-api/Controllers/Version2/class-wc-rest-coupons-v2-controller.php]: Ok, implemented in https://github.com/woocommerce/woocommerce/pull/63971/changes/df4b291b43e2f7f17f4b0a27fa71d1e0c2d1e31e (new `MetaDataUtil` class).

File: plugins/woocommerce/src/Admin/Features/Fulfillments/OrderFulfillmentsRestController.php [hunk 3]
```diff
@@ -384,16 +385,15 @@ public function update_fulfillment( WP_REST_Request $request ): WP_REST_Response
...
 
 				// Remove the meta data keys that don't exist in the request, by matching their keys.
+				$normalized_keys    = array_column( MetaDataUtil::normalize( $meta_data, 0 ), 'key' );
 				$existing_meta_data = $fulfillment->get_meta_data();
 				foreach ( $existing_meta_data as $meta ) {
-					if ( ! in_array( $meta->key, array_column( $request->get_json_params()['meta_data'], 'key' ), true ) ) {
+					if ( ! in_array( $meta->key, $normalized_keys, true ) ) {
 						$fulfillment->delete_meta_data( $meta->key );
 					}
 				}
```
[the remark this answers is not in the document]
Comment (Konamiman) [reply plugins/woocommerce/src/Admin/Features/Fulfillments/OrderFulfillmentsRestController.php:402]: Addressed in 45faff7c34a61d6f903470a0db954c4dc23536cc

File: plugins/woocommerce/src/Utilities/MetaDataUtil.php [hunk 4]
```diff
@@ -0,0 +1,75 @@
...
+	public static function normalize( array $meta_data, $default_id = '' ): array {
+		$normalized = array();
+		foreach ( $meta_data as $meta ) {
+			if ( isset( $meta['key'] ) ) {
+				$normalized[] = array(
+					'key'   => $meta['key'],
+					'value' => $meta['value'] ?? null,
+					'id'    => $meta['id'] ?? $default_id,
+				);
+			}
```
[the remark this answers is not in the document]
Comment (Konamiman) [reply plugins/woocommerce/src/Utilities/MetaDataUtil.php:60]: Addressed in ab36fdeeb723628e6782c603e4f2c7f7b95fed62

File: plugins/woocommerce/includes/rest-api/Controllers/Version2/class-wc-rest-customers-v2-controller.php [hunk 5]
```diff
@@ -130,14 +132,14 @@ protected function update_customer_meta_fields( $customer, $request ) {
...
 		// Meta data.
 		if ( isset( $request['meta_data'] ) ) {
-			if ( is_array( $request['meta_data'] ) ) {
-				foreach ( $request['meta_data'] as $meta ) {
-					if ( is_protected_meta( $meta['key'], 'user' ) ) { // bypass internal keys.
-						continue;
+			MetaDataUtil::update(
+				$request['meta_data'],
+				function ( $meta ) use ( $customer ) {
+					if ( ! is_protected_meta( $meta['key'], 'user' ) ) {
```
Comment (kalessil) [inline plugins/woocommerce/includes/rest-api/Controllers/Version2/class-wc-rest-customers-v2-controller.php]: I think we can pre-filter metadata here: then we can simplify `MetaDataUtil::update` (drop callabacks support).

File: plugins/woocommerce/src/Admin/Features/Fulfillments/OrderFulfillmentsRestController.php [hunk 6]
```diff
@@ -8,6 +8,7 @@
 namespace Automattic\WooCommerce\Admin\Features\Fulfillments;
 
 use Automattic\WooCommerce\Internal\Admin\Settings\Exceptions\ApiException;
+use Automattic\WooCommerce\Utilities\MetaDataUtil;
```
Comment (kalessil) [inline plugins/woocommerce/src/Admin/Features/Fulfillments/OrderFulfillmentsRestController.php:11]: For this file, I think we should create a migration ticket and hand it over to the maintenance team (and not touch it in this PR), as the changes are more complex than others.

File: plugins/woocommerce/includes/rest-api/Controllers/Version2/class-wc-rest-customers-v2-controller.php (hunk 5 above)
Comment (Konamiman) [reply plugins/woocommerce/includes/rest-api/Controllers/Version2/class-wc-rest-customers-v2-controller.php]: Good idea. Implemented in 774e60f92123abcb193269361e249580044ba499

File: plugins/woocommerce/src/Admin/Features/Fulfillments/OrderFulfillmentsRestController.php (hunk 6 above)
Comment (Konamiman) [reply plugins/woocommerce/src/Admin/Features/Fulfillments/OrderFulfillmentsRestController.php:11]: I think it would be enough if we can get someone from the maintenance team to review that part of the pr, a separate one would be a bit overkill. Is there someone you could suggest?

Comment (kalessil) [reply plugins/woocommerce/src/Admin/Features/Fulfillments/OrderFulfillmentsRestController.php:11]: WFM, I think @tpaksu has been the most active in that area. Adding Taha to reviewers.

File: plugins/woocommerce/includes/rest-api/Controllers/Version2/class-wc-rest-customers-v2-controller.php (hunk 5 above)
Comment (kalessil) [reply plugins/woocommerce/includes/rest-api/Controllers/Version2/class-wc-rest-customers-v2-controller.php]: Nice!

File: plugins/woocommerce/src/Admin/Features/Fulfillments/OrderFulfillmentsRestController.php (hunk 6 above)
Comment (tpaksu) [reply plugins/woocommerce/src/Admin/Features/Fulfillments/OrderFulfillmentsRestController.php:11]: The changes look good to me, thanks for fixing the warnings on missing keys and values, also adding a default 0 value to add meta keys, maybe we can also apply the normalization to the `set_meta_data` function on fulfillment creation too, it requires all metadata to have {"key": 0} to get saved correctly I believe. 

If you say it is out of scope of this PR, I can fix it after this gets merged.

https://github.com/woocommerce/woocommerce/blob/774e60f92123abcb193269361e249580044ba499/plugins/woocommerce/src/Admin/Features/Fulfillments/OrderFulfillmentsRestController.php#L272

Comment (Konamiman) [reply plugins/woocommerce/src/Admin/Features/Fulfillments/OrderFulfillmentsRestController.php:11]: I guess you mean something like this:

```php
$fulfillment->set_meta_data( MetaDataUtil::normalize( $request->get_json_params()['meta_data'] ?? array(), 0 ) );
```

Yes, this better goes in a separate PR since it would be a behavioral change (incomplete meta entries are currently silently ignored, and with this change they would be saved) and this PR is about bugfixing only. So @kalessil and @tpaksu, if you agree could you please approve the PR?

**Review by kalessil — APPROVED** [review]
LGTM (pre-approving)!

- I followed the testing instructions, and everything worked as expected.
- The changes are clear and logical.
- I did not follow up on the fulfillment-related changes and will leave that to the team.

**Review by tpaksu — APPROVED** [review]
I've tested the fulfillments related part and it is still working, thanks for the fix! I can add the meta normalization code on fulfillment create endpoint after this gets merged. LGTM!
