### PR TITLE
Use correct tax status when running recalc on admin

### LINKED ISSUE #53885: [GlobalStep] "Tax" and "Order Total" values changes after clicking the "Recalculate" button for "none-taxable shipping rate" on "Edit order" page.
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

"Tax" and "Order Total" values changes after clicking the "Recalculate" button for "none-taxable shipping rate" on "Edit order" page.

### Expected behavior

"Tax" and "Order Total" values should be stable and unchanged after clicking the "Recalculate" button for "none-taxable shipping rate" on "Edit order" page.

### Actual behavior

"Tax" and "Order Total" values changes after clicking the "Recalculate" button for "none-taxable shipping rate" on "Edit order" page.

### Steps to reproduce

1. Create a test site.
2. Install and activate the Woocommerce version 9.6.0-beta.1 plugins.
3. Enable taxes, make sure they account for shipping, set them to a predictable amount (20% for example).
4. Add 2 flat rates, both having the same price, one of them should have a tax status of none, the other should be taxable.
5. Add an item to cart and go to Checkout, select the taxable shipping rate, ensure the totals are correct (item + shipping) * 120%.
6. Place the order, ensure the total value is still the same in the order confirmation screen.
7. Add the same item back to cart, go to Checkout, select the none-taxable item, make sure the totals are correct (item * 120%) + shipping.
8. Place the order, ensure the total value is still the same in the order confirmation screen.
9. Go to the admin order screen, and go to the first order, make sure the "Recalculate" button is visible, if it's not, change the order status to on hold and save.
10. Take note of the totals, hit "Recalculate", the totals should stay the same.
11. Go to the newer order, do the same,
12. Observe that, "Tax" and "Order Total" values changes after clicking the "Recalculate" button for "none-taxable shipping rate" on "Edit order" page.

### Video 
https://github.com/user-attachments/assets/7f6a80d5-6796-469e-ac80-b5f3abc45fda

### WordPress Environment

Woocommerce Version: 9.6.0-beta.1
WordPress version: 6.7.2
PC:
Windows 10
Chrome (Version 131.0.6778.205)
Firefox (Version 133.0.3)

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

<details><summary>System Status Report</summary>

```
### WordPress Environment ###

WordPress address (URL): [Redacted]
Site address (URL): [Redacted]
WC Version: 9.6.0-beta.1
Legacy REST API Package Version: The Legacy REST API plugin is not installed on this site.
Action Scheduler Version: ✔ 3.9.0
Log Directory Writable: ✔
WP Version: 6.7.1
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 8.3.14
PHP Post Max Size: 2 GB
PHP Time Limit: 850
PHP Max Input Vars: 6144
cURL Version: 8.10.1
OpenSSL/3.0.15

SUHOSIN Installed: –
MySQL Version: 10.11.10-MariaDB-log
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

[REDACTED]

### Post Type Counts ###

attachment: 24
page: 7
post: 2
product: 18
product_variation: 7
revision: 2
shop_coupon: 6
shop_order_placehold: 8
wp_font_face: 36
wp_font_family: 12
wp_navigation: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (3) ###

Akismet Anti-spam: Spam Protection: by Automattic - Anti-spam Team – 5.3.5
Query Monitor: by John Blackbourn – 3.17.0
WooCommerce: by Automattic – 9.6.0-beta.1

### Inactive Plugins (0) ###


### Dropin Plugins () ###

advanced-cache.php: advanced-cache.php
db.php: Query Monitor Database Class (Drop-in)
object-cache.php: Memcached

### Must Use Plugins (1) ###

load.php: by  –

### Settings ###

Legacy API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 88 B

### WC Pages ###

Shop base: #7 - /shop/
Cart: #8 - /cart/ -  Contains the woocommerce/cart block
Checkout: #9 - /checkout/ -  Contains the woocommerce/checkout block
My account: #10 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty-Four
Version: 1.3
Author URL: https://wordpress.org
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
Theme type: Block theme
WooCommerce Support: ❌ Not declared

### Templates ###

Overrides: /srv/htdocs/wp-content/plugins/woocommerce/templates/block-notices/error.php
/srv/htdocs/wp-content/plugins/woocommerce/templates/block-notices/notice.php
/srv/htdocs/wp-content/plugins/woocommerce/templates/block-notices/success.php


### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
onboarding
onboarding-tasks
pattern-toolkit-full-composability
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
printful
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page
launch-your-store

Disabled Features: product-data-views
experimental-blocks
coming-soon-newsletter-template
minified-js
product-pre-publish-modal
settings
async-product-editor-category-field
product-editor-template-system
blueprint
reactify-classic-payments-settings
use-wp-horizon
add-to-cart-with-options-stepper-layout
blockified-add-to-cart

Daily Cron: ✔ Next scheduled: 2024-12-20 06:28:26 +00:00
Options: ✔
Notes: 58
Onboarding: skipped

### Action Scheduler ###

Complete: 72
Oldest: 2024-12-19 06:29:31 +0000
Newest: 2024-12-19 11:24:50 +0000

Failed: 2
Oldest: 2024-12-19 06:30:37 +0000
Newest: 2024-12-19 06:30:37 +0000

Pending: 1
Oldest: 2024-12-20 06:29:31 +0000
Newest: 2024-12-20 06:29:31 +0000


### Status report information ###

Generated at: 2024-12-19 12:45:33 +00:00
```
</details>

### PR DESCRIPTION
**Pull request by senadir**
This is a follow up to https://github.com/woocommerce/woocommerce/pull/46069, tax status calculation worked fine but weren't stored or loaded correctly for shipping items, this meant that running recalc on admin will always default to taxable.

This PR changes that so it's not stored but always loaded from the method. This matches the behavior of tax status in products (which are not saved to order line items and [are always loaded from the product](https://github.com/woocommerce/woocommerce//blob/5e69275f3f7b5088fd2c27395319da935519d074/plugins/woocommerce/includes/class-wc-order-item-product.php#L427-L435)).

### Changes proposed in this Pull Request:

Closes https://github.com/woocommerce/woocommerce/issues/53885

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Enable taxes, make sure they account for shipping, set them to a predictable amount (20% for example).
2. Add 2 flat rates, both having the same price, one of them should have a tax status of none, the other should be taxable.
3. Add an item to cart and go to Checkout, select the none-taxable shipping rate, ensure the totals are correct (item * 120%) + shipping.
4. Place the order, ensure the total value is still the same in the order confirmation screen.
5. Go to the admin order screen, and go to the order, make sure the "Recalculate" button is visible, if it's not, change the order status to on hold and save.
6. Take note of the totals, hit "Recalculate", the totals should stay the same.
7. Go to shipping, change the shipping method tax status to taxable.
8. Go back to the order, hit "Recalculate", the new totals should reflect a tax as well.

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

Correctly calculate shipping taxes when running recalculation on admin.

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce/includes/class-wc-order-item-shipping.php [hunk 1]
```diff
@@ -153,17 +153,6 @@ public function set_taxes( $raw_tax_data ) {
...
-	 * Set tax_status.
-	 *
-	 * @param string $value Tax status.
-	 */
-	public function set_tax_status( $value ) {
-		if ( in_array( $value, array( 'taxable', 'none' ), true ) ) {
-			$this->set_prop( 'tax_status', $value );
-		}
-	}
-
```
Comment (wavvves) [inline plugins/woocommerce/includes/class-wc-order-item-shipping.php]: This was introduced in https://github.com/woocommerce/woocommerce/pull/46069 which is on 9.6 milestone. Even if shortlived, if this PR lands on 9.7, any code attempting to use it will throw a fatal (it doesn't exist in upstream extends or traits). Can't we ship the setter anyway?

**Review by wavvves — APPROVED** [review]
Thanks for the PR @senadir !
The recalculate button seems to be working properly now, approving but left a [note](https://github.com/woocommerce/woocommerce/pull/54200#discussion_r1905366840) regarding `set_tax_status()`. Either risk shipping this PR on the next version without that, ship both PRs on the same version, or keep the setter. Up to you 👍🏼

File: plugins/woocommerce/includes/class-wc-order-item-shipping.php (hunk 1 above)
Comment (senadir) [reply plugins/woocommerce/includes/class-wc-order-item-shipping.php]: The setter has no value because the value is not read. I would not worry too much about this tbh.

Comment (ralucaStan) [reply plugins/woocommerce/includes/class-wc-order-item-shipping.php]: It's still considered public code and we should be proactive about preventing that fatal, no matter how low the chance.

**Comment by senadir** [comment]
Feedback address, not sure if this needs another review :)
