### PR TITLE
Fix additional field validation failing when text field is equal to 0

### LINKED ISSUE #52111: woocommerce_register_additional_checkout_field : passing value "0" to the form doens't record the value.
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When adding a new field with woocommerce_register_additional_checkout_field, if the user sets the value `0`, the value is considered as empty. If the field is required, the form validation fails with a WP error after submit.

### Expected behavior

`0` should be considered as a value.

### Actual behavior

`0` is considered as an absence of value (empty form input). Also tried with `null` and `false`, but the latter two works well.

### Steps to reproduce

Fresh WP/WC install, add the following code into wp-content/themes/twentytwentyfour/functions.php:

```
add_action(
        'woocommerce_init',
        function() {
                woocommerce_register_additional_checkout_field(
                        array(
                                'id'            => 'mynamespace/number',
                                'label'         => 'Choose number',
                                'location'      => 'address',
                                'required'      => true
                        ),
                );
        }
);
```

Note: in the my account page, if the field "location" is "contact", the value can't be changed at all from here (already reported here : https://github.com/woocommerce/woocommerce/issues/52066)

### WordPress Environment

<details><summary>System Status Report</summary>

```
### WordPress Environment ###

WordPress address (URL): [Redacted]
Site address (URL): [Redacted]
WC Version: 9.3.3
Legacy REST API Package Version: L’extension Legacy REST API n’est pas installée sur ce site.
Action Scheduler Version: ✔ 3.8.1
Log Directory Writable: ✔
WP Version: 6.6.2
WP Multisite: –
WP Memory Limit: 256 Mo
WP Debug Mode: ✔
WP Cron: ✔
Language: fr_FR
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.41 (Ubuntu)
PHP Version: 8.2.4
PHP Post Max Size: 100 Mo
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.68.0
OpenSSL/1.1.1f

SUHOSIN Installed: –
MySQL Version: 10.3.39-MariaDB-0ubuntu0.20.04.2
Max Upload Size: 100 Mo
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Votre serveur n’a pas la classe SoapClient activée - certaines extensions de passerelle utilisant SOAP peuvent ne pas fonctionner correctement.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

[REDACTED]

### Post Type Counts ###

attachment: 1
page: 7
post: 2
product: 1
revision: 2
shop_order_placehold: 1
wp_navigation: 1

### Security ###

Secure connection (HTTPS): ❌
					Votre boutique n’utilise pas HTTPS. En savoir plus sur HTTPS et les certificats SSL.
Hide errors from visitors: ❌Les messages d’erreur ne doivent pas s’afficher aux visiteurs.

### Active Plugins (1) ###

WooCommerce: par Automattic – 9.3.3

### Inactive Plugins (2) ###

Akismet Anti-spam: Spam Protection: par Automattic - Anti-spam Team – 5.3.3
Hello Dolly: par Matt Mullenweg – 1.7.2

### Settings ###

Legacy API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: 
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 jours
Level threshold: –
Log directory size: 13 o

### WC Pages ###

Base de la boutique: #7 - /index.php/boutique/
Panier: #8 - /index.php/panier/ -  Contient le bloc woocommerce/cart
Commander: #9 - /index.php/commander/ -  Contient le bloc woocommerce/checkout
Mon compte: #10 - /index.php/mon-compte/
Conditions générales de vente et d’utilisation: ❌ Page non définie

### Theme ###

Name: Twenty Twenty-Four
Version: 1.2
Author URL: https://fr.wordpress.org
Child Theme: ❌ – Si vous modifiez WooCommerce sur un thème parent que vous n‘avez pas construit personnellement
nous vous recommandons d‘utiliser un thème enfant. Voir : Comment créer un thème enfant

WooCommerce Support: ❌ Non déclaré

### Templates ###

Overrides: /var/www/wptest/wp-content/plugins/woocommerce/templates/block-notices/error.php
/var/www/wptest/wp-content/plugins/woocommerce/templates/block-notices/notice.php
/var/www/wptest/wp-content/plugins/woocommerce/templates/block-notices/success.php


### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
pattern-toolkit-full-composability
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
printful
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page
launch-your-store

Disabled Features: experimental-blocks
minified-js
product-pre-publish-modal
settings
async-product-editor-category-field
product-editor-template-system
blueprint
reactify-classic-payments-settings

Daily Cron: ✔ Next scheduled: 2024-10-17 17:18:49 +02:00
Options: ✔
Notes: 55
Onboarding: completed

### Action Scheduler ###

Terminé: 7
Oldest: 2024-10-16 19:19:19 +0200
Newest: 2024-10-17 13:55:23 +0200

Échoué: 1
Oldest: 2024-10-17 13:45:21 +0200
Newest: 2024-10-17 13:45:21 +0200

En attente: 1
Oldest: 2024-10-17 19:19:20 +0200
Newest: 2024-10-17 19:19:20 +0200


### Status report information ###

Generated at: 2024-10-17 14:17:00 +02:00
```
</details>

### Isolating the problem

- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by alexflorisca**
### Changes proposed in this Pull Request:

This PR fixes the validation for additional fields. When a required text input has the value `0`, which is a valid number, the validation fails saying the field is empty. We want to allow the following as valid input `(int) 0`, `(string) 0`, and `false`. Extra checks have been added to allow these but error on anything else.

Closes #52111 .

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Add the following code to either `functions.php` or using a code snippet plugin

```
add_action(
        'woocommerce_init',
        function() {
                woocommerce_register_additional_checkout_field(
                        array(
                                'id'            => 'mynamespace/number',
                                'label'         => 'Choose number',
                                'location'      => 'address',
                                'required'      => true
                        ),
                );
        }
);
```

2. Add a product to your cart and visit the checkout
3. Fill in all the required fields, and input `0` for Choose number.
4. Place the order and make sure the order goes through ok.
5. Check the order in the backend to make sure the value was stored correctly for Choose number field.

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

A required text additional field will now accept 0 as a valid input.

</details>

### CODE REVIEW

File: plugins/woocommerce/src/StoreApi/Utilities/OrderController.php [hunk 1]
```diff
@@ -391,7 +391,7 @@ protected function validate_address_fields( \WC_Order $order, $address_type, \WP
 		$address = array_merge( $address, $additional_fields );
 
 		foreach ( $current_locale as $address_field_key => $address_field ) {
-			if ( empty( $address[ $address_field_key ] ) && $address_field['required'] ) {
+			if ( ! isset( $address[ $address_field_key ] ) && $address_field['required'] ) {
```
Comment (wavvves) [inline plugins/woocommerce/src/StoreApi/Utilities/OrderController.php]: I think a blank space string or empty string will bypass this required field check, also this might throw a warning if the key doesn't exist or is of an incorrect type. A mix of array_key_exists, is_string and trim($string) !== '' might do the trick 👍

**Review by wavvves — CHANGES_REQUESTED** [review]

File: plugins/woocommerce/src/StoreApi/Utilities/OrderController.php (hunk 1 above)
Comment (alexflorisca) [reply plugins/woocommerce/src/StoreApi/Utilities/OrderController.php]: Thanks Paulo, I had similar thoughts but I decided against the extra checks because the value comes from client side where the input is trimmed and validated for empty strings if it is required. Also, this will need to work with checkbox type inputs soon too, so this if statement may get quite complex. But thinking about it some more, it's not guaranteed the input comes from the client, could be a direct request potentially from headless or somewhere else. Either way it's probably a good idea to harden this a bit, you're right

Comment (opr) [reply plugins/woocommerce/src/StoreApi/Utilities/OrderController.php]: > I decided against the extra checks because the value comes from client side where the input is trimmed and validated for empty strings if it is required

This could be overridden, or the order placed via Store API using a different client that doesn't implement these.

File: plugins/woocommerce/src/StoreApi/Utilities/OrderController.php [hunk 2]
```diff
@@ -391,7 +391,8 @@ protected function validate_address_fields( \WC_Order $order, $address_type, \WP
 		$address = array_merge( $address, $additional_fields );
 
 		foreach ( $current_locale as $address_field_key => $address_field ) {
-			if ( ! isset( $address[ $address_field_key ] ) && $address_field['required'] ) {
+			// If the field is required, but is not set or it's an empty string, we throw an error.
+			if ( $address_field['required'] && ( ! isset( $address[ $address_field_key ] ) || ( is_string( $address[ $address_field_key ] ) && '' === trim( $address[ $address_field_key ] ) ) ) ) {
```
Comment (wavvves) [inline plugins/woocommerce/src/StoreApi/Utilities/OrderController.php]: Hey @alexflorisca, sorry this might be nitpicking, but I still think there might be something missing here because we lost a check when we ditched `empty()`. I should have been more explicit in my first review and not only pointed out an issue being carried over but also anything else useful that the method could be doing and is now dropped.

The problem with `empty()` is that the function is very opinionated about what it considers empty and not empty. 
Apart from `null`, zero-length strings or arrays, and undefined vars or array indexes (which should fail the _required_ check here), it will also consider empty `(int) 0`, `(string) 0`, and `false`, all of which are valid values when submitted.
Furthermore, it will not consider empty a string filled with spaces. It’s often used when checking for “falsy” values combined with absence, and we're only interested in absence here, being the space-filled string and the empty array exceptions. **Empty array is the check that was lost when we ditched** `empty()`.

So, the space-filled string was a flaw carried on with the removal of `empty()` which is now fixed (👍🏼 ), but `empty()` was also guarding us from the empty array. If an API call can be crafted to include data that translate into an empty array value for the field defined or filters allow it, it will circumvent the required check. 
Long shot I know, since values made from arrays don't seem to be possible right now in regular and additional fields, **unless a third party using the filters enables that.**

If you decide to keep it for backwards compatibility, add another check for is_array() && count(). To make this more readable you can nest and indent them, under a quick check for field requirement:

```php
if ( $address_field['required'] ) ) {
    if ( 
        ! isset( $address[ $address_field_key ] ) ||
        ( is_string( $address[ $address_field_key ] ) && '' === trim( $address[ $address_field_key ] ) ||
        ( is_array( $address[ $address_field_key ] ) && 0 === count(  $address[ $address_field_key ] )
    ) {
        // add required field error
    } 
}
```

Apart from this, we could update the PR description to mention fixes for `(int) 0`, `(string) 0`, and `false`, as I think those 3 cases may be valid here (again, a third party using filters might feed these values).


EDITED COMMENT: I had some doubts about default values for fields, specifically if the required entry was always present, but after testing this seems to be the case for both regular and additional fields, so I removed that part. Sorry for the unneeded pings team.

**Review by wavvves — CHANGES_REQUESTED** [review]
Hey @alexflorisca thanks for the changes, but I think there's more being overlooked here :(

File: plugins/woocommerce/src/StoreApi/Utilities/OrderController.php (hunk 2 above)
Comment (wavvves) [reply plugins/woocommerce/src/StoreApi/Utilities/OrderController.php]: PS - Even better for readability and avoid nested `ifs`, continue the loop if not required.

Comment (alexflorisca) [reply plugins/woocommerce/src/StoreApi/Utilities/OrderController.php]: Thanks Paulo, I've made the changes, can I get your eyes on it again?

**Comment by ralucaStan** [comment]
@alexflorisca @wavvves is there anything keeping this PR review from progressing? Should it be marked as a draft?

**Review by wavvves — APPROVED** [review]
Thanks for the patience Alex! Approved!
