### PR TITLE
Fix Mini-Cart footer to show only enabled calculation types

### LINKED ISSUE #44286: Mini-Cart tells the customer shipping will be calculated at checkout even if shipping is disabled in the store
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

The Mini-Cart Drawer at the bottom shows the following text even if you have shipping disabled:

"Shipping, taxes, and discounts calculated at checkout."

image

### Expected behavior

Text should change based on the store settings. You can disable shipping, taxes and discounts too, so it can be multiple variations of this text.

### Actual behavior

At the moment it is a single string, no alternative versions based on store context. 

### Steps to reproduce

1. Disable Shipping in WooCommerce / Settings / General / Shipping location(s) - Disable shipping & shipping calculations
2. Go to the site, add something to the cart and check out the mini-cart drawer block at the bottom

### WordPress Environment

-

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by nerrad**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

This PR fixes the Mini-Cart footer description to dynamically show only the relevant calculation information (shipping, taxes, discounts) based on which features are enabled in WooCommerce settings.

**Problem:**
The Mini-Cart footer always displayed "Shipping, taxes, and discounts calculated at checkout" regardless of whether shipping, taxes, or coupons were actually enabled in the store settings. This confused customers when these features were disabled.

**Solution:**

-   Implemented \`get_total_items_description()\` method in \`MiniCartFooterBlock\` class that checks which features are enabled (\`wc_shipping_enabled()\`, \`wc_tax_enabled()\`, \`wc_coupons_enabled()\`)
-   Returns appropriate description text based on enabled features (8 different combinations)
-   Returns empty string when none of the features are enabled
-   Exposed the description text via \`miniCartFooterDescription\` setting to JavaScript
-   Created \`getTotalItemsDescription()\` helper function in utils.ts to retrieve the setting
-   Updated both block.tsx and edit.tsx to use the helper function. This is needed so that the editor view is accurate.
-   Added comprehensive PHPUnit tests covering all 8 scenarios

Closes #44286.
Linear: WOOPLUG-1937

### Screenshots or screen recordings:

| Before                                                                | After                                                                                    |
| --------------------------------------------------------------------- | ---------------------------------------------------------------------------------------- |
| CleanShot 2025-11-08 at 14 50 39@2x |  CleanShot 2025-11-08 at 14 51 58@2x |

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Install and activate WooCommerce
2. Add products to your cart
3. Open the Mini-Cart (add Mini-Cart block to your site if needed)
4. Observe the footer description below the subtotal

**Test different settings combinations:**

5. Go to WooCommerce > Settings > General

    - Enable shipping, taxes, and coupons
    - Check Mini-Cart footer shows: "Shipping, taxes, and discounts calculated at checkout."

6. Disable shipping (Settings > General > "Enable shipping" unchecked)

    - Check Mini-Cart footer shows: "Taxes and discounts calculated at checkout."

7. Re-enable shipping, disable taxes (Settings > Tax > "Enable taxes" unchecked)

    - Check Mini-Cart footer shows: "Shipping and discounts calculated at checkout."

8. Disable coupons (Settings > General > "Enable coupons" unchecked, shipping and taxes enabled)

    - Check Mini-Cart footer shows: "Shipping and taxes calculated at checkout."

9. Enable only shipping (disable taxes and coupons)

    - Check Mini-Cart footer shows: "Shipping calculated at checkout."

10. Enable only taxes (disable shipping and coupons)

    - Check Mini-Cart footer shows: "Taxes calculated at checkout."

11. Enable only coupons (disable shipping and taxes)

    - Check Mini-Cart footer shows: "Discounts calculated at checkout."

12. Disable all three (shipping, taxes, and coupons)
    - Check Mini-Cart footer shows no description text below the subtotal

### Testing that has already taken place:

-   **Unit tests:** Added comprehensive PHPUnit test coverage for all 8 combinations of settings in \`MiniCartFooterBlock.php\`
-   **Test execution:** All tests pass with \`pnpm test:php:env -- --filter MiniCartFooterBlock --verbose\`
-   **Environment:** Local WordPress/WooCommerce development environment
-   **Manual testing:** Verified behavior with different settings combinations in the Mini-Cart block

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message

Fix Mini-Cart footer to show only enabled calculation types (shipping, taxes, discounts) instead of always showing all three.

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment

</details>

### CODE REVIEW

File: plugins/woocommerce/src/Blocks/BlockTypes/MiniCartFooterBlock.php [hunk 1]
```diff
@@ -92,6 +102,67 @@ protected function get_cart_instance() {
...
+
+		// Only taxes.
+		if ( $taxes_enabled ) {
+			return __( 'Taxes calculated at checkout.', 'woocommerce' );
+		}
+
+		// Only discounts.
+		if ( $coupons_enabled ) {
+			return __( 'Discounts calculated at checkout.', 'woocommerce' );
+		}
```
Comment (tyxla) [inline plugins/woocommerce/src/Blocks/BlockTypes/MiniCartFooterBlock.php:165]: A bummer we need all those new strings, but at the same time, the extra complexity if we were to reduce the repetition here and have fewer strings is likely not worth it.

File: plugins/woocommerce/client/blocks/assets/js/blocks/mini-cart/mini-cart-contents/inner-blocks/utils.ts [hunk 2]
```diff
@@ -31,3 +32,12 @@ export const hasChildren = ( children ): boolean => {
 		return isObject( child ) && child.key !== null;
 	} );
 };
+
+/**
+ * Gets the total items description text from PHP-computed setting.
+ *
+ * @return {string} The description text for the total items.
+ */
+export const getTotalItemsDescription = (): string => {
```
Comment (tyxla) [inline plugins/woocommerce/client/blocks/assets/js/blocks/mini-cart/mini-cart-contents/inner-blocks/utils.ts]: Is `utils` the best place for this new function? No strong feelings, was just curious.

Comment (tyxla) [inline plugins/woocommerce/client/blocks/assets/js/blocks/mini-cart/mini-cart-contents/inner-blocks/utils.ts]: Also, a nit: in other places in code, we're referring to those as "totals item". Here, we're calling it "total items". Does it make sense to make it consistent and rename this to:


```suggestion
export const getTotalsItemDescription = (): string => {
```

File: plugins/woocommerce/src/Blocks/BlockTypes/MiniCartFooterBlock.php [hunk 3]
```diff
@@ -92,6 +102,67 @@ protected function get_cart_instance() {
 		return null;
 	}
 
+	/**
+	 * Computes the total items description text based on which settings are enabled.
+	 *
+	 * @return string The description text for the total items, or empty string if none are enabled.
+	 */
+	private function get_total_items_description() {
```
Comment (tyxla) [inline plugins/woocommerce/src/Blocks/BlockTypes/MiniCartFooterBlock.php]: Similar as above with regards to the function name:


```suggestion
	private function get_totals_item_description() {
```

File: plugins/woocommerce/src/Blocks/BlockTypes/MiniCartFooterBlock.php [hunk 4]
```diff
@@ -14,6 +14,16 @@ class MiniCartFooterBlock extends AbstractInnerBlock {
...
 	protected $block_name = 'mini-cart-footer-block';
 
+	/**
+	 * Enqueue frontend data.
+	 *
+	 * @param array $attributes Block attributes.
+	 */
+	protected function enqueue_data( array $attributes = array() ) {
+		parent::enqueue_data( $attributes );
+		$this->asset_data_registry->add( 'miniCartFooterDescription', $this->get_total_items_description() );
```
Comment (tyxla) [inline plugins/woocommerce/src/Blocks/BlockTypes/MiniCartFooterBlock.php]: Does it make sense to render this variable if it's an empty string? Perhaps we can just check if `miniCartFooterDescription` exists, and if it doesn't, render nothing?

File: plugins/woocommerce/src/Blocks/BlockTypes/MiniCartFooterBlock.php [hunk 5]
```diff
@@ -14,6 +14,16 @@ class MiniCartFooterBlock extends AbstractInnerBlock {
 	 */
 	protected $block_name = 'mini-cart-footer-block';
 
+	/**
+	 * Enqueue frontend data.
+	 *
+	 * @param array $attributes Block attributes.
```
Comment (tyxla) [inline plugins/woocommerce/src/Blocks/BlockTypes/MiniCartFooterBlock.php]: Should we duplicate this docs block from `AbstractBlock` instead of writing our own?

File: plugins/woocommerce/tests/php/src/Blocks/BlockTypes/MiniCartFooterBlock.php [hunk 6]
```diff
@@ -0,0 +1,113 @@
...
+			}
+		);
+		add_filter(
+			'wc_tax_enabled',
+			function () use ( $taxes_enabled ) {
+				return $taxes_enabled;
+			}
+		);
+		add_filter(
+			'pre_option_woocommerce_enable_coupons',
```
Comment (tyxla) [inline plugins/woocommerce/tests/php/src/Blocks/BlockTypes/MiniCartFooterBlock.php:98]: Is there a reason why we're using the `pre_option` filter here instead of the `woocommerce_coupons_enabled` filter?

**Review by tyxla — COMMENTED** [review]
This works great in my testing! 👍 

Just a few minor questions/suggestions, nothing blocking really.

File: plugins/woocommerce/src/Blocks/BlockTypes/MiniCartFooterBlock.php (hunk 1 above)
Comment (nerrad) [reply plugins/woocommerce/src/Blocks/BlockTypes/MiniCartFooterBlock.php:165]: Ya, and for i18n purposes there isn't much we can do dynamically without risking improper context communicated to translators.

File: plugins/woocommerce/client/blocks/assets/js/blocks/mini-cart/mini-cart-contents/inner-blocks/utils.ts (hunk 2 above)
Comment (nerrad) [reply plugins/woocommerce/client/blocks/assets/js/blocks/mini-cart/mini-cart-contents/inner-blocks/utils.ts]: Actually, getSetting can probably be called directly rather than having this helper wrapper.

Comment (nerrad) [reply plugins/woocommerce/client/blocks/assets/js/blocks/mini-cart/mini-cart-contents/inner-blocks/utils.ts]: What do you think about just calling `getSetting` directly in the components instead of this helper (see previous reply to your comment where you questioned implementing in utils)?

File: plugins/woocommerce/tests/php/src/Blocks/BlockTypes/MiniCartFooterBlock.php (hunk 6 above)
Comment (nerrad) [reply plugins/woocommerce/tests/php/src/Blocks/BlockTypes/MiniCartFooterBlock.php:98]: I'd have to ask Claude 😄.  Either should suffice, really. We're not testing the filters themselves, just using this to setup the test expectations.

File: plugins/woocommerce/client/blocks/assets/js/blocks/mini-cart/mini-cart-contents/inner-blocks/utils.ts (hunk 2 above)
Comment (nerrad) [reply plugins/woocommerce/client/blocks/assets/js/blocks/mini-cart/mini-cart-contents/inner-blocks/utils.ts]: Chatted in person, and this helps with typing (because `getSetting` is unknown). So will leave.

Comment (nerrad) [reply plugins/woocommerce/client/blocks/assets/js/blocks/mini-cart/mini-cart-contents/inner-blocks/utils.ts]: See [this comment](https://github.com/woocommerce/woocommerce/pull/61861#discussion_r2507162876).

File: plugins/woocommerce/tests/php/src/Blocks/BlockTypes/MiniCartFooterBlock.php (hunk 6 above)
Comment (tyxla) [reply plugins/woocommerce/tests/php/src/Blocks/BlockTypes/MiniCartFooterBlock.php:98]: Yeah, I guess this is mostly about consistency, and I was also curious if I'm missing something

File: plugins/woocommerce/client/blocks/assets/js/blocks/mini-cart/mini-cart-contents/inner-blocks/utils.ts [hunk 7]
```diff
@@ -31,3 +32,12 @@ export const hasChildren = ( children ): boolean => {
...
 };
+
+/**
+ * Gets the total items description text from PHP-computed setting.
+ *
+ * @return {string} The description text for the total items.
+ */
+export const getTotalsItemDescription = (): string => {
+	return getSetting( 'miniCartFooterDescription', '' );
+};
```
[the remark this answers is not in the document]
Comment (tyxla) [reply plugins/woocommerce/client/blocks/assets/js/blocks/mini-cart/mini-cart-contents/inner-blocks/utils.ts:43]: Coderabbit has a point here, let's do this!

File: plugins/woocommerce/tests/php/src/Blocks/BlockTypes/MiniCartFooterBlock.php [hunk 8]
```diff
@@ -0,0 +1,113 @@
...
+use Automattic\WooCommerce\Blocks\Assets\Api;
+use Automattic\WooCommerce\Blocks\Assets\AssetDataRegistry;
+use Automattic\WooCommerce\Blocks\Integrations\IntegrationRegistry;
+
+/**
+ * Tests for the MiniCartFooterBlock block type.
+ *
+ * @since 10.4.0
+ */
+class MiniCartFooterBlock extends \WP_UnitTestCase {
```
[the remark this answers is not in the document]
Comment (tyxla) [reply plugins/woocommerce/tests/php/src/Blocks/BlockTypes/MiniCartFooterBlock.php:16]: This is reasonable, unless you have a good reason to go with `WP_UnitTestCase`.

File: plugins/woocommerce/src/Blocks/BlockTypes/MiniCartFooterBlock.php (hunk 5 above)
Comment (tyxla) [reply plugins/woocommerce/src/Blocks/BlockTypes/MiniCartFooterBlock.php]: Were you also planning to address this one @nerrad?

File: plugins/woocommerce/client/blocks/assets/js/blocks/mini-cart/mini-cart-contents/inner-blocks/utils.ts (hunk 7 above)
[the remark this answers is not in the document]
Comment (nerrad) [reply plugins/woocommerce/client/blocks/assets/js/blocks/mini-cart/mini-cart-contents/inner-blocks/utils.ts:43]: Fixed in later commit.

File: plugins/woocommerce/client/blocks/assets/js/blocks/mini-cart/mini-cart-contents/inner-blocks/mini-cart-footer-block/edit.tsx [hunk 9]
```diff
@@ -17,6 +17,7 @@ import { PaymentEventsProvider } from '@woocommerce/base-context';
 /**
  * Internal dependencies
  */
+import { getTotalItemsDescription } from '../utils';
```
[the remark this answers is not in the document]
Comment (nerrad) [reply plugins/woocommerce/client/blocks/assets/js/blocks/mini-cart/mini-cart-contents/inner-blocks/mini-cart-footer-block/edit.tsx]: fixed in later commit

File: plugins/woocommerce/client/blocks/assets/js/blocks/mini-cart/mini-cart-contents/inner-blocks/mini-cart-footer-block/block.tsx [hunk 10]
```diff
@@ -19,7 +19,7 @@ import clsx from 'clsx';
  */
 import CartButton from '../mini-cart-cart-button-block/block';
 import CheckoutButton from '../mini-cart-checkout-button-block/block';
-import { hasChildren } from '../utils';
+import { hasChildren, getTotalItemsDescription } from '../utils';
```
[the remark this answers is not in the document]
Comment (nerrad) [reply plugins/woocommerce/client/blocks/assets/js/blocks/mini-cart/mini-cart-contents/inner-blocks/mini-cart-footer-block/block.tsx]: fixed in later commit

File: plugins/woocommerce/src/Blocks/BlockTypes/MiniCartFooterBlock.php (hunk 5 above)
Comment (nerrad) [reply plugins/woocommerce/src/Blocks/BlockTypes/MiniCartFooterBlock.php]: Oh yea, see d53d6da

File: plugins/woocommerce/src/Blocks/BlockTypes/MiniCartFooterBlock.php (hunk 4 above)
Comment (nerrad) [reply plugins/woocommerce/src/Blocks/BlockTypes/MiniCartFooterBlock.php]: Good call. See 0fe47dc

File: plugins/woocommerce/client/blocks/assets/js/blocks/mini-cart/mini-cart-contents/inner-blocks/utils.ts [hunk 11]
```diff
@@ -31,3 +32,12 @@ export const hasChildren = ( children ): boolean => {
 		return isObject( child ) && child.key !== null;
 	} );
 };
+
+/**
+ * Gets the total items description text from PHP-computed setting.
+ *
+ * @return {string} The description text for the total items.
```
Comment (tyxla) [inline plugins/woocommerce/client/blocks/assets/js/blocks/mini-cart/mini-cart-contents/inner-blocks/utils.ts]: I think this is still saying "total items" and not "totals item", which we might want to update for consistency.


```suggestion
 * Gets the totals item description text from PHP-computed setting.
 *
 * @return {string} The description text for the totals item.
```

**Review by tyxla — APPROVED** [review]
Retesting worked well, and code LGTM 👍 

Thanks @nerrad, that's a neat improvement!
