### PR TITLE
Fix issue where analytics reports generate duplicate rows in variations

### LINKED ISSUE #60163: WooCommerce Analytics generates duplicate rows in Variations report
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When exporting the “Variations” report from WooCommerce Analytics, the CSV file includes duplicate rows for the same product variation (same SKU, same title, same quantity sold, same order count, same revenue) even though the product variation exists only once in the WooCommerce catalog and database.

### Expected behavior

Each product variation should appear only once in the exported report, with data aggregated correctly across orders.

### Actual behavior

Some product variations appear multiple times with no distinguishable difference in the row content. This happens even after running the historical data import under Analytics > Settings > Import Historical Data.
The product catalog contains no duplicate variants, and WooCommerce frontend and admin views display only one instance of each.

### Steps to reproduce

Go to WooCommerce > Analytics > Variations

Filter by a date range that includes historical sales

Click Export CSV

Open the CSV file

Notice that some product variations appear multiple times with identical values (SKU, title, quantity, revenue, order count)

### WordPress Environment

<details><summary>System Status Report</summary>

```
### WordPress Environment ###

WordPress address (URL): [Redacted]
Site address (URL): [Redacted]
WC Version: 9.9.5
Legacy REST API Package Version: Il plugin API REST legacy non è installato in questo sito.
Action Scheduler Version: ✔ 3.9.3
Log Directory Writable: ✔
WP Version: ❌ 6.7.2 - È disponibile una versione più recente di WordPress (6.8.2)
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: –
WP Cron: ✔
Language: it_IT
External object cache: –




### Isolating the problem

- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by louwie17**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

This makes two changes:
- Adds the necessary `order by` SQL params like product and variation id when ordering by either 'items_sold', 'net_revenue', or 'orders_count' ( this fixes an issue where pagination causes duplicate results ).
- Updates the export for variations to include attribute names, this matches the exact front-end representation already [done here](https://github.com/woocommerce/woocommerce/blob/a16f11ad6ee01389bdb68ee499b85c676e283d36/plugins/woocommerce/client/admin/client/lib/async-requests/index.js#L99)

Closes #60163 .

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Don't load this branch yet
2. Add a set of variable products, more then 50.
3. Enable taxes
4. Install the [Smooth Generator plugin](https://github.com/woocommerce/wc-smooth-generator) and generate about a 100 orders across a month ( under **Tools > Smooth Generator** )
5. Add some coupons and create a couple orders with the coupons
6. Go to either **Analytics > Products** or **Analytics > Variations** and make sure you have multiple pages of data
7. Click **Download** ( it should email it to you )
8. Look at the CSV, it most likely has duplicate entries ( you can match by SKU and name ), depending on the size of your store you may just have a couple ( I just asked AI to scan it for me :) ) It generated a python script I will paste below.
Also notice that variations with local attributes do not have the selected option appended to the variation name.
9. If you **did not** find duplicates, you may need to create more variations/products and more orders.
10. Now load this branch and click **Download** again.
11. Look at the CSV, it should not contain duplicates this time. For the variation export it should also contain the selected options for each variation name.
12. Go to the **WooCommerce > Customers**, **Analytics > Taxes**, and **Analytics > Coupons** reports and sort by the numbered values, and make sure things sort correctly. **Note: Cursor things these reports also have the same issue as above, but I found it a bit harder to reproduce**.

**Duplicate python script**
```
python3 -c "
import csv
from collections import Counter

# Read the CSV file
with open('wc-variations-report-export-17545549467584.csv', 'r') as file:
    reader = csv.reader(file)
    next(reader)  # Skip header
    first_column_values = [row[0] for row in reader]

# Count occurrences
counter = Counter(first_column_values)

# Find duplicates (items that appear more than once)
duplicates = {item: count for item, count in counter.items() if count > 1}

print('DUPLICATE ENTRIES IN FIRST COLUMN:')
print('=' * 50)
for item, count in duplicates.items():
    print(f'\"{item}\" - appears {count} times')

print(f'\nTotal unique products: {len(counter)}')
print(f'Total duplicate products: {len(duplicates)}')
print(f'Total rows: {len(first_column_values)}')
"
```

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce/src/Admin/API/Reports/Variations/Controller.php [hunk 1]
```diff
@@ -391,8 +391,31 @@ public function get_export_columns() {
...
+		$product_name = $item['extended_info']['name'];
+		/**
+		 * Filter the separator used in the product variation title.
+		 *
+		 * @since 10.2.0
+		 * @param string $separator The separator.
+		 * @param \WC_Product $product The product object.
+		 * @return string The separator.
+		*/
+		$separator = apply_filters( 'woocommerce_product_variation_title_attributes_separator', ' - ', new \WC_Product() );
```
Comment (chihsuan) [inline plugins/woocommerce/src/Admin/API/Reports/Variations/Controller.php:403]: Should we pass the actual product object instead of `new \WC_Product()`?

File: plugins/woocommerce/src/Admin/API/Reports/Products/DataStore.php [hunk 2]
```diff
@@ -379,7 +380,11 @@ public function get_noncached_data( $query_args ) {
 
 			$this->subquery->clear_sql_clause( 'select' );
 			$this->subquery->add_sql_clause( 'select', $selections );
-			$this->subquery->add_sql_clause( 'order_by', $this->get_sql_clause( 'order_by' ) );
+			if ( in_array( $query_args['orderby'], array( 'items_sold', 'net_revenue', 'orders_count' ), true ) ) {
```
Comment (chihsuan) [inline plugins/woocommerce/src/Admin/API/Reports/Products/DataStore.php]:
```suggestion
			if ( in_array( $query_args['orderby'], array( 'items_sold', 'net_revenue', 'orders_count', 'variations' ), true ) ) {
```
Should we add `variations`? Users have the option to sort by "variations," and I can see CSV file has duplicate rows in the exported CSV file when sorting by "variations."

Screenshot 2025-08-12 at 15 17 43

**Review by chihsuan — COMMENTED** [review]
Thanks for the fix! @louwie17  Overall, this looks good. Just found a few issues.

Just to confirm, is issue unique to the product and variation reports, or do other reports also encounter it?

File: plugins/woocommerce/src/Admin/API/Reports/Variations/Controller.php (hunk 1 above)
Comment (louwie17) [reply plugins/woocommerce/src/Admin/API/Reports/Variations/Controller.php:403]: I can, although decided not to, as the way the filter is structured it may break backwards compatibility. Given the filter uses a product object in the other instances and we don't have the exact product instance here: https://github.com/search?q=repo%3Awoocommerce%2Fwoocommerce%20woocommerce_product_variation_title_attributes_separator&type=code

File: plugins/woocommerce/src/Admin/API/Reports/Products/DataStore.php (hunk 2 above)
Comment (louwie17) [reply plugins/woocommerce/src/Admin/API/Reports/Products/DataStore.php]: Good catch, will do!

Comment (louwie17) [reply plugins/woocommerce/src/Admin/API/Reports/Products/DataStore.php]: Updated: https://github.com/woocommerce/woocommerce/pull/60258/commits/ed179373f08647068142f1d038b667d8007c2999

**Comment by louwie17** [comment]
Thanks for the review @chihsuan, I addressed your changes and left a reply to one of your comments.
In regards to other reports, I asked Cursor, and it seemed to think that customers, coupons, and taxes would also encounter this. I tried to reproduce it with customers, but it was a bit difficult. Coupons and taxes was a lot more difficult, as those lists would hardly go beyond the 50 mark.

File: plugins/woocommerce/src/Admin/API/Reports/Variations/Controller.php (hunk 1 above)
Comment (chihsuan) [reply plugins/woocommerce/src/Admin/API/Reports/Variations/Controller.php:403]: Thanks for the explanation, that makes sense.

**Review by chihsuan — APPROVED** [review]
Thanks for addressing the changes! 🙌

I’ve reviewed the changes, and they look solid. I verified that the Product/Variations analytics report works correctly after your updates. 

For customers, coupons, and taxes, the changes look appropriate as well. (I only confirmed that downloading the report still functions correctly.)
