### PR TITLE
Fix validation behavior

### LINKED ISSUE #37984: Product Block Editor: Fix validation behavior
**Description**

Currently each field validation happened at render time. It uses the locking editor feature to prevent the form from been submitted.
If at first render there is an invalid field value, the error message immediately arises, when that should happen only if the field is dirty or if it has been touched by the user.
If we don't run the validation at the very beginning we are not going to be able to disable the `Save` button and prevent the product creation.

**AC**

- [ ] We want to check whether the form is in a dirty/touched state to enable/disable the `Save` button.
- [ ] We need to check if a particular field that is being validated is dirty/touched to prevent the error message to be shown before it has been touched.

### PR DESCRIPTION
**Pull request by mdperez86**
### Submission Review Guidelines:

- I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
- I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
- I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/). 
- Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes #37984

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Got to `/wp-admin/tools.php?page=woocommerce-admin-test-helper`
2. Under Features tab make sure to enable `product-block-editor`
3. Then visit `/wp-admin/admin.php?page=wc-admin&path=/add-product`
4. Each validation should happen on per field blur and when trying to save the form.
5. If when trying to save the form there are invalid fields then the first visible field should receive the focus and all validation messages should be visible for all invalid fields.

https://github.com/woocommerce/woocommerce/assets/13334210/b7d5391a-68b4-41a5-8477-62ff9a35bcd1

### CODE REVIEW

File: packages/js/product-editor/src/contexts/validation-context/validation-provider.tsx [hunk 1]
```diff
@@ -0,0 +1,79 @@
...
+} from './types';
+import { ValidationContext } from './validation-context';
+
+export function ValidationProvider< T >( {
+	initialValue,
+	children,
+}: PropsWithChildren< ValidationProviderProps< T > > ) {
+	const [ validators, setValidators ] = useState<
+		Record< string, Validator< T > >
+	>( {} );
```
Comment (louwie17) [inline packages/js/product-editor/src/contexts/validation-context/validation-provider.tsx]: Do we need to use `useState` for setting validators? We could probably just use a `useRef` object for this right? Given we don't call `validateField` upon `setValidators`.

Comment (mdperez86) [reply packages/js/product-editor/src/contexts/validation-context/validation-provider.tsx]: Yep at the beginning I thought validations to be exposed via context so anyone can use then in their own way. But yes, after having this other functions that gets access to validations I don't think we need to share them anyway. So yes, we can use `useRef` to avoid non necessary renders here. 
Thanks @louwie17 nice suggestion

File: packages/js/product-editor/src/blocks/schedule-sale/edit.tsx [hunk 2]
```diff
@@ -84,9 +87,13 @@ export function Edit( {}: BlockEditProps< ScheduleSalePricingBlockAttributes > )
 	const _dateOnSaleFrom = moment( dateOnSaleFromGmt, moment.ISO_8601, true );
 	const _dateOnSaleTo = moment( dateOnSaleToGmt, moment.ISO_8601, true );
 
-	const dateOnSaleFromGmtValidationError = useValidation(
-		'product/date_on_sale_from_gmt',
-		function dateOnSaleFromValidator() {
+	const {
+		// ref: dateOnSaleFromGmtRef,
```
Comment (joshuatf) [inline packages/js/product-editor/src/blocks/schedule-sale/edit.tsx:91]: Any reason to comment this one out?

File: packages/js/product-editor/src/blocks/schedule-sale/edit.tsx [hunk 3]
```diff
@@ -99,12 +106,17 @@ export function Edit( {}: BlockEditProps< ScheduleSalePricingBlockAttributes > )
...
-		}
+		},
+		[ showScheduleSale, dateOnSaleFromGmt, _dateOnSaleFrom, _dateOnSaleTo ]
 	);
 
-	const dateOnSaleToGmtValidationError = useValidation(
-		'product/date_on_sale_to_gmt',
-		function dateOnSaleToValidator() {
+	const {
+		// ref: dateOnSaleToGmtRef,
```
Comment (joshuatf) [inline packages/js/product-editor/src/blocks/schedule-sale/edit.tsx:114]: Same question on this one.

File: packages/js/product-editor/src/blocks/schedule-sale/edit.tsx [hunk 4]
```diff
@@ -133,6 +146,7 @@ export function Edit( {}: BlockEditProps< ScheduleSalePricingBlockAttributes > )
 				<div className="wp-block-columns">
 					<div className="wp-block-column">
 						<DateTimePickerControl
+							// ref={ dateOnSaleFromGmtRef }
```
Comment (joshuatf) [inline packages/js/product-editor/src/blocks/schedule-sale/edit.tsx:149]: Same question here.

File: packages/js/product-editor/src/blocks/schedule-sale/edit.tsx [hunk 5]
```diff
@@ -145,11 +159,13 @@ export function Edit( {}: BlockEditProps< ScheduleSalePricingBlockAttributes > )
 								dateOnSaleFromGmtValidationError && 'has-error'
 							}
 							help={ dateOnSaleFromGmtValidationError as string }
+							onBlur={ validateDateOnSaleFromGmt }
 						/>
 					</div>
 
 					<div className="wp-block-column">
 						<DateTimePickerControl
+							// ref={ dateOnSaleToGmtRef }
```
Comment (joshuatf) [inline packages/js/product-editor/src/blocks/schedule-sale/edit.tsx:168]: And here.

File: packages/js/product-editor/src/contexts/validation-context/helpers.ts [hunk 6]
```diff
@@ -0,0 +1,33 @@
...
+import { ValidationErrors } from './types';
+
+export function findFirstInvalidElement< E extends Element = Element >(
+	elementsMap: Record< string, E >,
+	errors: ValidationErrors
+): E | undefined {
+	const fieldRefsWithError = Object.entries( elementsMap ).filter(
+		( [ validatorId, element ] ) =>
+			// Pick the element if it is under the selected tab.
+			element?.closest( '.is-selected[role="tabpanel"]' ) &&
```
Comment (joshuatf) [inline packages/js/product-editor/src/contexts/validation-context/helpers.ts:13]: Do we only want to find invalid elements under the currently selected tab?  I would think we just find the first and then change to that tab.

Also noting that this function is currently very tied to our UI, which we may consider decoupling a bit later, but I think this is a good first iteration.

**Review by joshuatf — COMMENTED** [review]
Great work on this, @mdperez86!  Love the overall direction.

Left a couple comments/questions.  One odd quirk if we enable the buttons all the time is that clicking "Add/Save" again when there is no dirty state will result in failed to publish.

Screen Shot 2023-05-11 at 12 33 15 PM

File: packages/js/product-editor/src/blocks/schedule-sale/edit.tsx (hunk 2 above)
Comment (mdperez86) [reply packages/js/product-editor/src/blocks/schedule-sale/edit.tsx:91]: That is because the DateTimePickerControl is not ForwardedRef yet. That is going to be covered in [#38248](https://github.com/woocommerce/woocommerce/issues/38248).

File: packages/js/product-editor/src/blocks/schedule-sale/edit.tsx (hunk 3 above)
Comment (mdperez86) [reply packages/js/product-editor/src/blocks/schedule-sale/edit.tsx:114]: That is because the DateTimePickerControl is not ForwardedRef yet. That is going to be covered in [#38248](https://github.com/woocommerce/woocommerce/issues/38248).

File: packages/js/product-editor/src/blocks/schedule-sale/edit.tsx (hunk 4 above)
Comment (mdperez86) [reply packages/js/product-editor/src/blocks/schedule-sale/edit.tsx:149]: That is because the DateTimePickerControl is not ForwardedRef yet. That is going to be covered in [#38248](https://github.com/woocommerce/woocommerce/issues/38248).

File: packages/js/product-editor/src/blocks/schedule-sale/edit.tsx (hunk 5 above)
Comment (mdperez86) [reply packages/js/product-editor/src/blocks/schedule-sale/edit.tsx:168]: That is because the DateTimePickerControl is not ForwardedRef yet. That is going to be covered in [#38248](https://github.com/woocommerce/woocommerce/issues/38248).

File: packages/js/product-editor/src/contexts/validation-context/helpers.ts (hunk 6 above)
Comment (mdperez86) [reply packages/js/product-editor/src/contexts/validation-context/helpers.ts:13]: > Do we only want to find invalid elements under the currently selected tab? I would think we just find the first and then change to that tab.

We may want to talk about this a little bit, because:
1. We don't want to couple this to our UI but since we are hiding elements using `display: none` it's not easy to detect if the element can receive the focus from javascript.
2. If we are going to change the selected tab that contains the invalid field then we need to know the structure of the UI which will make the implementation very coupled.
3. Considering this is part of the product editor package, shouldn't that be tied enough to the editor made under this package?
4. For know this is a work around until we found a better less coupled and extensible solution.

**Comment by mdperez86** [comment]
> One odd quirk if we enable the buttons all the time is that clicking "Add/Save" again when there is no dirty state will result in failed to publish.

@joshuatf good catch here. I was taking a look at this function `saveEditedEntityRecord` and it does return `undefined` if there are no changes, meaning that we are being prevented from submitting the product when there are no changes.
In this case what the button should does after clicking it. Nothing, or showing the alert message?

File: packages/js/product-editor/src/contexts/validation-context/helpers.ts (hunk 6 above)
Comment (jarekmorawski) [reply packages/js/product-editor/src/contexts/validation-context/helpers.ts:13]: Good question. We may want to change tabs if necessary, but the more I think about it, the more sense it makes to use the pre-publish modal from the post editor and surface the errors there. Combining both solutions (focusing on the first affected field and having a clear list of all errors) may produce the best UX.

Comment (joshuatf) [reply packages/js/product-editor/src/contexts/validation-context/helpers.ts:13]: I'm good with leaving this as is until we create a way to surface all errors easily.

>If we are going to change the selected tab that contains the invalid field then we need to know the structure of the UI which will make the implementation very coupled.

One possible solution to this if we need it is to provide a path option along with the field ref.  Since tab selection is also dictated by URL, we could switch to `...&tab=general` prior to focus which doesn't tie us specifically to our UI or require knowledge around UI elements.

**Comment by jarekmorawski** [comment]
> In this case what the button should does after clicking it. Nothing, or showing the alert message?

Can we just publish the product again? 🤔 Like, by force? Or fake the update and show the Product updated message? There's no error, so there isn't anything we need to warn or inform the user about. Or better yet, can we lock the button when the form isn't dirty?

**Comment by mdperez86** [comment]
@jarekmorawski thanks for your replay
> Can we just publish the product again? 🤔 Like, by force? 

Nope. Unless we reimplement the GB function that saves the changes into the server. According the name of the function `saveEditedEntityRecord`, it does exactly what its name said right. Only save edited entity, meaning, non dirty or unchanged entities right!

> Or fake the update and show the Product updated message?

We can do this, but for this case we need to know if we are going to send the tracking event too? Aren't we?

> Or better yet, can we lock the button when the form isn't dirty?

We move to always enabled the button so if we do this I think we are going to have a regression here and will increase the code complexity of this. 
If form isn't dirty then the save button is disabled but we need the button to be enabled to highlight/focus the first invalid form field. Imagine we are creating the product but the user never touched/focused any field, at this point the user wont be able to submit the form unless he/she changes any field. Feels like a dependency loop for me.

**Comment by jarekmorawski** [comment]
> We can do this, but for this case we need to know if we are going to send the tracking event too? Aren't we?

No, we should track this event. I don't believe this is the best solution, though.

> Imagine we are creating the product but the user never touched/focused any field, at this point the user wont be able to submit the form unless he/she changes any field. Feels like a dependency loop for me.

I'm not sure I follow. If the form isn't dirty, doesn't that mean that the user didn't make any changes? If so, they shouldn't be able to submit the form because there are no updates to publish. It could still enable when there's an error because the presence of an error indicates that a change was made.

Is there a use case I can't see?

**Comment by mdperez86** [comment]
> It could still enable when there's an error because the presence of an error indicates that a change was made.

That is the case. The required validation constraint must be highlighted even when the form is not dirty or touched. We shouldn't force the user with poor visibility to traverse the entire form to fill all the required field before going to the submit button. The user should be able to go directly to the submit button and triggers the validation to easily fill the focused field with the error. Remember the user can navigate not only using Tab key, but also per section, list item, or buttons with different keys as a shortcut traversal, so they can avoid go through one by one field and we shouldn't prevent them form doing that.

**Review by joshuatf — APPROVED** [review]
Looks great and is testing well!  There are some failing tests, but I believe those are unrelated.  I'll try and restart them to see if we can get them passing.

>The required validation constraint must be highlighted even when the form is not dirty or touched. We shouldn't force the user with poor visibility to traverse the entire form to fill all the required field before going to the submit button. 

I overall agree with this.  Keeping the button unlocked allows these errors to be surfaced easier and is much more accessible than a disabled button.

But we do have the inverse of that right now, which is nothing happening when the button is clicked.  I think the same notice of "Product was published" is fine (not actually publishing again, but just showing this) or a notice that says "No new changes to publish" might work.

@mdperez86 can you open an issue to tackle this in a follow-up?

**Comment by jarekmorawski** [comment]
Thanks for sharing your thoughts, folks. Let's default to displaying a success message instead of disabling the submit button. I wanted to align with Gutenberg (that's how they handle non-dirty states in the editor), but after some digging I discovered that it's better to give the user a positive reinforcement.

Added a comment to #38329.
