### PR TITLE
Prevent order attribution install banner when file mods are not allowed

### LINKED ISSUE #60573: Marketing marketplace suggestions console logs if DISALLOW_FILE_MODS e.g. on wpvip.com
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When `DISALLOW_FILE_MODS` is defined and non-falsy (= true) or the `file_mod_allowed` filter returns false, there's a console.log on lots of wp-admin pages (e.g. order edit page) with content

```
{
	"code": "woocommerce_rest_cannot_update",
	"message": "Sorry, you cannot manage plugins.",
	"data": {
		"status": 403
	}
}
```

Coming from woocommerce/assets/client/admin/embed/index.js

Even when unchecking marketplace suggestions in "/wp-admin/admin.php?page=wc-settings&tab=advanced&section=woocommerce_com" it will still send this request (unnecessarily, since it's disabled)

This error is coming from https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/src/Admin/API/Marketing.php#L105

It's extremely annoying, especially for [wpvip.com](https://wpvip.com/) customers, where file mods are disallowed by default.

### Expected behavior

No error/console

Specifically:

1) https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/src/Admin/API/Marketing.php#L104 should check whether marketplace suggestions are disabled and not return an error if they are disabled

2) https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/src/Admin/API/Marketing.php#L104 should check `wp_is_file_mod_allowed( 'woocommerce' ) === false` and not return an error if file mods are disabled

3) woocommerce/assets/client/admin/embed/index.js should not send the marketplace wp-json AJAX request if either marketplace suggestions are disabled or `wp_is_file_mod_allowed( 'woocommerce' ) === false` since it's pointless

### Actual behavior

console logged:

```
{
	"code": "woocommerce_rest_cannot_update",
	"message": "Sorry, you cannot manage plugins.",
	"data": {
		"status": 403
	}
}
```

### Steps to reproduce

1. `define( 'DISALLOW_FILE_MODS', true );`
2. open the order details/edit page of any WooCommerce order and look at the console

### WordPress Environment

WP 6.8.2
WC 10.0.0

### Isolating the problem

- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by joshuatf**
### Changes proposed in this Pull Request:

Requests to get plugin recommendations were being made on order pages in the order attribution install banner.  Requests to those endpoints should not be made when the file mods are not allowed or marketplace suggestions are disabled.

This PR addresses that in a couple ways:

1. Updates the `install_plugins` capability to be `false` when `wp_is_file_mod_allowed( 'woocommerce' )` is not true.  This matches WP's [default behavior](https://github.com/WordPress/wordpress-develop/blob/57c1af7f8e408979e11fb543f676aa929cf49c62/src/wp-includes/capabilities.php#L621-L642) for `current_user_can( 'install_plugins' )` though I'm not sure why the choice was not made by WP to apply this filter to all WP user data.
2. The banner itself is wrapped in a check so that it doesn't get loaded when marketplace suggestions and various install behavior is not enabled.

Closes #60573 .

### How to test the changes in this Pull Request:

1. Make sure marketplace suggestions are enabled at `/wp-admin/admin.php?page=wc-settings&tab=advanced&section=woocommerce_com`
2. Navigate to an order edit page as an admin user `/wp-admin/admin.php?page=wc-orders&action=edit&id={ID}`
2. Make sure that no console errors/warnings are shown regarding user capabilities.  If you end up in the experiment group, you should still see the order attribution install banner on a fresh site
3. Disable marketplace suggestions.
4. Navigate to an order edit page as an admin user `/wp-admin/admin.php?page=wc-orders&action=edit&id={ID}`
5. Make sure no errors are shown in the console around user capabilities.
6. Re-enable marketplace suggestions.
7. Add `define( 'DISALLOW_FILE_MODS', true );` to your wp-config.php file
8. Make sure no errors are shown in the console around user capabilities. 

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce/src/Internal/Admin/WCAdminUser.php [hunk 1]
```diff
@@ -153,4 +153,39 @@ public static function get_user_data_field( $user_id, $field ) {
...
 		return $meta_value;
 	}
+
+	/**
+	 * Get the current user data.
+	 *
+	 * @return array User data.
+	 */
+	public static function get_user_data() {
+		$user_controller = new \WP_REST_Users_Controller();
```
Comment (joshuatf) [inline plugins/woocommerce/src/Internal/Admin/WCAdminUser.php:163]: This is a little funky and we might be better of using `get_userdata` instead of creating a REST call within the code, but that would require refactoring the registered REST fields in this class which I opted not to do to keep the scope on this PR a bit narrower.

File: plugins/woocommerce/src/Internal/Admin/WCAdminUser.php [hunk 2]
```diff
@@ -153,4 +153,39 @@ public static function get_user_data_field( $user_id, $field ) {
...
+	 *
+	 * @param array $user_data User data.
+	 * @return array Filtered user data.
+	 */
+	private static function filter_user_capabilities( $user_data ) {
+		if ( ! is_array( $user_data ) || ! isset( $user_data['capabilities'] ) ) {
+			return $user_data;
+		}
+
+		// If the user has install_plugins capability, check if file modifications are allowed
```
Comment (kalessil) [inline plugins/woocommerce/src/Internal/Admin/WCAdminUser.php]: IMO this should be relocated into `\WP_REST_Users_Controller::prepare_item_for_response` or `\WP_REST_Users_Controller::get_current_item`, at least based on my current understanding of the PR.

File: plugins/woocommerce/src/Internal/Admin/WCAdminUser.php (hunk 1 above)
Comment (kalessil) [reply plugins/woocommerce/src/Internal/Admin/WCAdminUser.php:163]: @joshuatf : are you referring to the REST-preload functionality in `\Automattic\WooCommerce\Internal\Admin\Settings::add_component_settings`?

Comment (joshuatf) [reply plugins/woocommerce/src/Internal/Admin/WCAdminUser.php:163]: No, the REST fields that are included in this class.

https://github.com/woocommerce/woocommerce/blob/3017ba0367abbb48ce305419b90fcd95fbb0ef54/plugins/woocommerce/src/Internal/Admin/WCAdminUser.php#L54-L63

File: plugins/woocommerce/src/Internal/Admin/WCAdminUser.php (hunk 2 above)
Comment (joshuatf) [reply plugins/woocommerce/src/Internal/Admin/WCAdminUser.php]: Yes, I think this portion is an upstream issue.  However, those are WP classes and we don't have access to them directly.  This is a workaround that allows us to match the `current_user_can( 'install_plugins' )` behavior for now within WC.

File: plugins/woocommerce/templates/order/attribution-details.php [hunk 3]
```diff
@@ -136,5 +136,7 @@
 		</span>
 	<?php endif; ?>
 	<!-- A placeholder for the OA install banner React component. -->
-	<div id="order-attribution-install-banner-slotfill"></div>
+	<?php if ( WC_Marketplace_Suggestions::allow_suggestions() ) : ?>
```
Comment (kalessil) [inline plugins/woocommerce/templates/order/attribution-details.php]: Some tests are failing, as this class can not be resolved. Perhaps we can use `\WC_Marketplace_Suggestions` here to address that.

**Review by kalessil — APPROVED** [review]
LGTM! Pre-approving (followed the testing instructions and it works as intended, still some CI checks are failing).
