### PR TITLE
iAPI Minicart: Fix same item with different props not working as expected.

### LINKED ISSUE #61405: Data Misalignment in Mini-Cart Items When Adding the Same Product with Different Cart Data
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When adding the same product to the Cart with different configurations, the mini-cart displays the same data twice. The issue is only present in the mini-cart; the Cart page shows them as expected. Additionally, the item data values do not get overridden by the "display" key in the `woocommerce_get_item_data` filter.

### Expected behavior

- Each cart item should be a distinct combination of its cart item data.
- Display format should be respected.

### Actual behavior

Two issues:
- Data misalignment, most likely due to caching.
- "Display" value based on the `woocommerce_get_item_data` hook is not respected in the Mini Cart.

https://github.com/user-attachments/assets/c6a10562-33f3-4990-9e21-ae5996ce9a23

Image

#### Prerequisites

Install the following snippet:
```php
add_action( 'init', function () {
	if ( ! isset( $_GET['test_key'] ) ) {
		return;
	}

	$PRODUCT_ID = 1105; // Replace with a product ID on your store.

	// Add to cart.
	WC()->cart->add_to_cart( $PRODUCT_ID, 1, 0, array(), array(
		'test_key' => 1,
	) );

	WC()->cart->add_to_cart( $PRODUCT_ID, 1, 0, array(), array(
		'test_key' => 2,
	) );
});

add_filter( 'woocommerce_get_item_data', function( $other_data, $cart_item ) {
	$other_data[] = array(
		'name'    => 'test_key',
		'value'    => $cart_item['test_key'],
		'display' => 'Formatted value: ' . $cart_item['test_key'],
	);
	return $other_data;
}, 10, 2 );
```

#### Testing steps
1. Visit a frontend page with the `?test_key=1` suffix in the URL.
2. Open the Mini-Cart.
3. Notice the "Test Key" appears as `1` twice, instead of having two different values 1 and 2.
4. Visit the Cart page and ensure the view appears as expected.

### WordPress Environment

<details>

<summary>WordPress Environment</summary>

The System Status Report is found in your WordPress admin under **WooCommerce > Status**. 
Please select “Get system report”, then “Copy for GitHub”, and then paste it here.

</details>

### Isolating the problem

- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by SantosGuillamot**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes #61405.

In this pull request I'm addressing the two bugs described in the mentioned issue:
- Allow multiple instances of the same product when they have different props: Right now, we are filtering by product ID, so they are duplicated. In the pull request I'm using the `key` property instead.
- Respect the `display` property in `woocommerce_get_item_data` filter: We were always showing the `value` but `display` should take precedence as [it's happening in the cart](https://github.com/woocommerce/woocommerce/blob/92543ad5d198ed91f46b192d946f7b8362bd1375/plugins/woocommerce/client/blocks/assets/js/base/components/cart-checkout/product-details/index.tsx#L63), for example.

### Screenshots or screen recordings:

| Before | After |
| ------ | ----- |
|  Screenshot 2025-10-22 at 17 38 57   |    Screenshot 2025-10-22 at 17 34 32   |

### How to test the changes in this Pull Request:

Detailed testing instructions from the original issue: https://github.com/woocommerce/woocommerce/issues/61405 .

1. Add the same product with different props twice to the cart. You can do it by adding the following snippet and visiting any page with `?test_key=1`. **Just once** to ensure they are added to the cart is enough to avoid problems.

```php
add_action( 'init', function () {
	if ( ! isset( $_GET['test_key'] ) ) {
		return;
	}

	$PRODUCT_ID = 1105; // Replace with a product ID on your store.

	// Add to cart.
	WC()->cart->add_to_cart( $PRODUCT_ID, 1, 0, array(), array(
		'test_key' => 1,
	) );

	WC()->cart->add_to_cart( $PRODUCT_ID, 1, 0, array(), array(
		'test_key' => 2,
	) );
});
```

2. Add the following snippet to show the custom props:
```
add_filter( 'woocommerce_get_item_data', function( $other_data, $cart_item ) {
	$other_data[] = array(
		'name'    => 'test_key',
		'value'    => $cart_item['test_key'],
		'display' => 'Formatted value: ' . $cart_item['test_key'],
	);
	return $other_data;
}, 10, 2 );
```
3. Check that the "Formatted value: " string is included.
4. Check that each item shows a different number.

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message Support same item with different props in the iAPI minicart.

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

**Review by xristos3490 — APPROVED** [review]
Nice work @SantosGuillamot! Both issues are resolved, and different Cart items with the same product test well on my end! There are some failures, most probably related to WP 6.9, so I'm pre-approving.

File: plugins/woocommerce/client/blocks/assets/js/blocks/mini-cart/iapi-frontend.ts [hunk 1]
```diff
@@ -126,10 +126,7 @@ store< MiniCart >(
 	{
 		state: {
 			get totalItemsInCart() {
-				return woocommerceState.cart.items.reduce< number >(
-					( total, { quantity } ) => total + quantity,
-					0
-				);
+				return woocommerceState.cart.items_count;
```
Comment (luisherranz) [inline plugins/woocommerce/client/blocks/assets/js/blocks/mini-cart/iapi-frontend.ts]: Why do we need this change? Doesn't this affect the Optimistic UI? I don't see it mentioned in the PR description.

**Review by samueljseay — APPROVED** [review]
Code changes make sense to me and it tests well for me.

File: plugins/woocommerce/client/blocks/assets/js/blocks/mini-cart/iapi-frontend.ts (hunk 1 above)
Comment (SantosGuillamot) [reply plugins/woocommerce/client/blocks/assets/js/blocks/mini-cart/iapi-frontend.ts]: It wasn't part of this PR. I was testing another one and I committed it by mistake. I've removed the change.

Comment (luisherranz) [reply plugins/woocommerce/client/blocks/assets/js/blocks/mini-cart/iapi-frontend.ts]: Perfect, thanks.
