### PR TITLE
FIx trashed post show up in email listing and cannot be deleted

### LINKED ISSUE #57550: Trashed post show up in email listing and cannot be deleted or edited
### **Problem**

When a post is trashed from the email editor UI, it is marked as trashed but can still be viewed on the email listing page.

Attempting to view or edit the transaction email from the email listing page results in this error.

The post can not be edited or permanently deleted, leading to a bad experience for the merchant. **They are stuck**.

Currently, when an email post is permanently deleted, attempting to view or edit the transaction email from the email listing page directs the user to the legacy view page.

Let's ensure merchants can still access this page to edit their email settings.

### Proposal

Trashing a post from the email editor should permanently delete the post.

### Specs

1. Update the trash post confirmation modal content from trash to permanently delete

   
2. On confirmation, delete the post, skip trash
3. Add a Reset email content menu item to the context list on the Email

   

   a. For emails without an associated email post, automatically create the email post  
   b. ~~For emails with an existing email post, show a confirmation prompt informing the merchant that the action will reset the email content to default.~~  
   c. For third-party emails, repeat a and b if the email is included [here](https://github.com/woocommerce/woocommerce/blob/d8e4eed76569f66e314197892f488d19216cd054/plugins/woocommerce/src/Internal/EmailEditor/WCTransactionalEmails/WCTransactionalEmails.php#L73).

### Visual

[Screen Recording at 2025-04-28 at 09-18-53.mp4](https://uploads.linear.app/f629fcde-6f9b-48e8-8af3-60eed8823bff/58f12498-71a4-4242-9cfe-3fbdc0069e64/a1b85d4c-874f-470f-b7bc-76960246e04e?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2Y2MjlmY2RlLTZmOWItNDhlOC04YWYzLTYwZWVkODgyM2JmZi81OGYxMjQ5OC03MWE0LTQyNDItOWNmZS0zZmJkYzAwNjllNjQvYTFiODVkNGMtODc0Zi00NzBmLWI3YmMtNzY5NjAyNDZlMDRlIiwiaWF0IjoxNzQ1OTE4MjA4LCJleHAiOjMzMzE2NDc4MjA4fQ.omhTN9-l8CqUn25GauhU4bD_HbyzTJ8DIJYC9OoDY6o)

### PR DESCRIPTION
**Pull request by triple0t**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

This PR addresses an issue where trashed email posts show up in the email listing and cannot be deleted. The changes include:

1. Added support for permanent deletion of email posts from the database (bypassing trash)
2. Implemented a new "Recreate email post" action in the email listing page
3. Added a new REST API endpoint for recreating email posts
4. Enhanced the trash modal UI to support both trash and permanent deletion modes

Note: The "Recreate email post" action will only appear when the transactional email does not have an associated post_id.

Closes #57550 WOOPLUG-4080

(For Bug Fixes) Bug introduced in PR # .

**Additional Documentation**

The PR introduces a new filter `woocommerce_email_editor_trash_modal_should_permanently_delete` in the email editor that controls whether emails should be permanently deleted or moved to trash. When set to `true`, emails will be permanently deleted instead of being moved to trash.

### Screenshots or screen recordings:

| Before | After |
| ------ | ----- |
|    Screenshot 2025-04-29 at 10 11 19 AM  |    Screenshot 2025-05-06 at 10 17 34 PM   |
| Current |  Screenshot 2025-05-29 at 6 46 52 PM  |
| Current | Screenshot 2025-05-29 at 6 46 56 PM |
| New |  Screenshot 2025-05-29 at 6 46 05 PM |
| New | Screenshot 2025-05-29 at 6 46 12 PM |

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Navigate to WooCommerce > Settings > Emails
2. Verify that emails without post IDs show a "Recreate email post" action
3. Click on "Recreate email post" and confirm that the post is recreated
4. Try to delete an email and verify:
   - The delete modal shows appropriate messaging for permanent deletion
   - The email is permanently deleted (skipping trash)
   - The email can be recreated from the listing page

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce/src/Internal/Admin/Emails/EmailListingRestController.php [hunk 1]
```diff
@@ -0,0 +1,195 @@
...
+	}
+
+	/**
+	 * Get the accepted arguments for the POST recreate-email-post request.
+	 *
+	 * @return array[]
+	 */
+	private function get_args_for_recreate_email_post() {
+		return array(
+			'emailId'  => array(
```
Comment (lysyjan) [inline plugins/woocommerce/src/Internal/Admin/Emails/EmailListingRestController.php]: I think the parameter `emailId` should be in the snakecase format for alignment with the rest of the codebase. So I would expect here `email_id`. What do you think?

Comment (triple0t) [reply plugins/woocommerce/src/Internal/Admin/Emails/EmailListingRestController.php]: Okay 👌🏿

**Review by lysyjan — COMMENTED** [review]
Great job @triple0t!

I have a couple of questions about the UI and compatibility:
1. What about the compatibility with the previous WP version? Is this feature fully compatible? Based on my testing, it looks like it isn't.

2. When I recreated the email post from the listing. It worked, but as a user, I was a bit confused because there wasn't any notification or message about the output. Should we improve it? Maybe in a follow-up ticket if needed.

3. Another confusion was related to the deleted email post. When I tried to edit an email notification, I expected a notice that the post for the specific email type had been deleted in the old email editor. For example, when one user deletes an email post and the second user wants to edit the same email later. He could be surprised by opening the old editor.

Here is an example how it could look like:
Screenshot 2025-06-02 at 9 26 45

File: plugins/woocommerce/src/Internal/Admin/Emails/EmailListingRestController.php (hunk 1 above)
Comment (triple0t) [reply plugins/woocommerce/src/Internal/Admin/Emails/EmailListingRestController.php]: Implemented in https://github.com/woocommerce/woocommerce/pull/57827/commits/47c1bdf62a6d1ee99118da850a03158bf30bbf9f

**Comment by triple0t** [comment]
Thanks for the review, @lysyjan 

> What about the compatibility with the previous WP version? Is this feature fully compatible? Based on my testing, it looks like it isn't.

Nice catch. Fixed in https://github.com/woocommerce/woocommerce/pull/57827/commits/5a73c1b8e34667d60bdd2d44ab50ae530df08d48

> When I recreated the email post from the listing. It worked, but as a user, I was a bit confused because there wasn't any notification or message about the output. Should we improve it? Maybe in a follow-up ticket if needed.

I agree with you. Let's do this in a follow-up ticket.

> Another confusion was related to the deleted email post. When I tried to edit an email notification, I expected a notice that the post for the specific email type had been deleted in the old email editor. For example, when one user deletes an email post and the second user wants to edit the same email later. He could be surprised by opening the old editor.

This part is a little bit more complicated, but would be better to tackle in another ticket as well.

Complications:
1. The Block editor is still behind a feature flag, and we limit the transactional emails for which we automatically generate email posts.
2. The legacy email page is the current default for transactional emails without an associated email post. We want to keep this for compatibility with other Woo extensions and third-party plugins.
3. For this to work effectively, we would have to set an option in the DB to indicate that the email post associated with the transactional email was deleted. It's not a big deal, but it's also not something we should do in this PR.

I hope this helps.

**Review by lysyjan — APPROVED** [review]
It works as expected with WP 6.8 and 6.7.

I tested deleting an email post for various email types and recreating it.
Here are some screenshots from my testing:
Screenshot 2025-06-03 at 17 07 21
Screenshot 2025-06-02 at 10 03 38
