### PR TITLE
Use first meta value instead of last to be consistent with WP_Post.

### LINKED ISSUE #37660: [HPOS] Adopt migration and verification scripts to handle duplicate unique metas
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

In posts meta table, there is no uniqueness constraint on the meta_key <> meta_value columns. This means many meta entries may have duplicate values even if they are added with the unique flag set. This issue scopes intentionally handling them in a way so that the behavior is predictable and accounting for that behavior when running the verification script.

### Expected behavior

When a duplicate meta is encountered for a supposedly unique meta value, we should pick the first meta value we encounter. This is to be consistent with the behavior of [WP_Posts in such cases](https://github.com/WordPress/WordPress/blob/master/wp-includes/meta.php#L635:L639). So migration should pick the first value when encountering duplicate meta, and verification script should also verify against the first meta value.

### Actual behavior

Currently, the last meta value is being picked up. Additionally, the verification script detects and flags issues when duplicate meta values are found.

### Steps to reproduce

1. Create duplicate meta value entry for a supposedly unique meta entry, such as `_order_key` for any particular order.
2. Migrate the order to HPOS.
3. You will see that last value was migrated.
4. Run the verification script using `wp wc cot verify_cot_data` you will see that it will error on this error.

### WordPress Environment

-

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by vedanshujain**
### Submission Review Guidelines:

- I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
- I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
- I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/). 
- Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

In several cases, we will have multiple meta values for supposedly unique meta keys, such as order_key, date_paid, etc, since in the post meta table, the unique constraint on the post_id <> meta_key combination cannot be enforced. When migrated to HPOS, unique constrained is enforced in the sense that these keys are not mapped to flat columns, which can only hold one value per row.

Currently, when multi-record are encountered, we select the last one, however, this is inconsistent with how WP core treats the case of multiple meta values for supposedly unique meta keys, which is to select the first value. This PR makes the HPOS migration consistent with the WP core's behavior in selecting the first meta value instead of the last one when there are duplicate meta.

Closes #37660 

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Set the posts to authoritative and sync to off.
2. Create a new order, note it's ID. Make sure it has some value as the billing first name.
3. Add another meta entry for a supposedly unique meta key, such as `_billing_first_name`. You can do it from CLI like so: `wp post meta add XXXX _billing_first_name testname` where XXXX is the ID of the order created in the previous step.
4. Migrate the order to HPOS.
5. Open the order again with HPOS authoritative, you should still see the original first value instead of the `testname`.

### CODE REVIEW

File: plugins/woocommerce/src/Database/Migrations/MetaToCustomTableMigrator.php [hunk 1]
```diff
@@ -646,31 +644,85 @@ protected function build_verification_query( $source_ids ) {
...
 SELECT $select_clause
 FROM $source_table
     LEFT JOIN $source_destination_join_clause
-    LEFT JOIN $meta_join_clause
 WHERE $where_clause
 ";
 	}
 
+	/**
+	 * Fill source metadata for given IDS for verification. This will return filled data in following format:
```
Comment (barryhughes) [inline plugins/woocommerce/src/Database/Migrations/MetaToCustomTableMigrator.php]:
```suggestion
	 * Fill source metadata for given IDs for verification. This will return filled data in following format:
```

File: plugins/woocommerce/src/Database/Migrations/MetaToCustomTableMigrator.php [hunk 2]
```diff
@@ -646,31 +644,85 @@ protected function build_verification_query( $source_ids ) {
...
+		$meta_key_column       = $this->schema_config['source']['meta']['meta_key_column'];
+		$meta_value_column     = $this->schema_config['source']['meta']['meta_value_column'];
+		$meta_id_column        = $this->schema_config['source']['meta']['meta_id_column'];
+		$meta_columns          = array_keys( $this->meta_column_mapping );
+
+		$meta_columns_placeholder = implode( ', ', array_fill( 0, count( $meta_columns ), '%s' ) );
+		$source_ids_placeholder   = implode( ', ', array_fill( 0, count( $source_ids ), '%d' ) );
+
+		$query = $wpdb->prepare(
+		// phpcs:disable WordPress.DB.PreparedSQL.InterpolatedNotPrepared, WordPress.DB.PreparedSQLPlaceholders.UnfinishedPrepare
```
Comment (barryhughes) [inline plugins/woocommerce/src/Database/Migrations/MetaToCustomTableMigrator.php:694]:
```suggestion
			// phpcs:disable WordPress.DB.PreparedSQL.InterpolatedNotPrepared, WordPress.DB.PreparedSQLPlaceholders.UnfinishedPrepare
```

**Review by barryhughes — DISMISSED** [review]

**Comment by barryhughes** [comment]
@vedanshujain → looks good! We have one conflict to solve and I triggered a re-run of tests (E2E with COT enabled was failing previously).

**Review by barryhughes — APPROVED** [review]
Noice.

**Comment by barryhughes** [comment]
Looks good, though required E2E checks are still failing (I think flakiness ... some may be covered by https://github.com/woocommerce/woocommerce/issues/37724 though others relate to payment setup tasks, analytics, etc). Triggering a re-run.
