### PR TITLE
Remove shipping if there is no address, always allow hide shipping costs option

### LINKED ISSUE #50554: [Shipping calculator] Panel updates in the cart sidebar when the shipping calculator is enabled
This is a followup to https://github.com/woocommerce/woocommerce/issues/46948

```[tasklist]
### Changes when shipping calculator is enabled
- [ ] Display the address form, when clicking the `Enter address to check delivery options` link, in a `<panel>` component, similar to the `Add a coupon` section. (See image 1 for expected result)
- [ ] When an address has been provided and a shipping method is available, link the wording `Delivers to {ADDRESS}` to open the address form `<panel>`.
- [ ] When an address has been provided and a shipping method is available, remove the link `Change address`
- [ ] When an address has been provided, but no shipping methods are available, display the wording `No delivery options available for {ADDRESS}` as the panel title. (see image 2 for expected result)
```

[Link to design](https://www.figma.com/design/c8VYjXqluE9vlVSE1RgJix/%5BPublic%5D-Cart-%26-Checkout-Blocks?node-id=463-4936&node-type=frame&t=0F4LMujfmarnvowB-0).

### Image 1
image

### Image 2
image |

### LINKED ISSUE #52335: Local Pickup options show in Cart block when shipping calculator is disabled
> [!IMPORTANT]
> This issue is currently blocked by #50554, see https://github.com/woocommerce/woocommerce/issues/52335#issuecomment-2458614791.

### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

On the cart block, when the shipping calculator is disabled, the shipping options can't be changed. However local pickup doesn't need an address, so local pickup options show here. This is confusing for the shopper, as they can only change their shipping method to a local pickup one, but not a shipping one.

Slack conversation for context (p1729685919085089-slack-C02TS23QJ1X)

### Expected behavior

Ideally, we want to disable local pickup options from showing in the cart if the shipping calculator is disabled. 

### Actual behavior

Only the local pickup options show, but no shipping options.

### Steps to reproduce

1. In the admin navigate to WooCommerce > Settings > Shipping > Shipping settings and untick the `Enable the shipping calculator on the cart page` checkbox.
2. Make sure you have at least 1 pickup location enabled
3. On the frontend, add an item to cart
4. Visit the page with the cart block
5. Notice that only the pickup location is selectable on the cart page. 

### WordPress Environment

WC 9.4
WP 6.7 RC1

### Isolating the problem

- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by samueljseay**
Closes #52335 

With some adjustments:

1. We used to disable "hide shipping costs until an address is entered" when local pickup was enabled. We now allow it to be enabled but we explain the behaviour (`Local pickup rates will display in the Checkout block, even without an address`). @opr and I agreed this experience felt clearer and covered all cases well, but it would be good to get some feedback about this cc @pmcpinto 

2. If an address has not been entered and the user has hide shipping costs enabled we do not display the *Shipping* options

Added by @opr 

- Changes the shipping calculator logic to display "Enter an address to check delivery options" if only a partial address has been entered (e.g. when the shopper has a default location)
- We previously hid the "Ship" selector when:
  - Shipping is not required
  - Shipping calculations have not been completed
  - No shipping rates are available
  - The item is not collectible
  - Local pickup is not enabled
  - No shipping methods are currently available
- however this would hide it even if rates _might_ become available later, after a full address had been entered. Instead I changed the logic to force the control to show if the following is true:
  - Shipping is enabled, and
  - The cart needs shipping, and
  - All packages in the cart support collectible, and
  - Local pickup is enabled, and
  - Shipping methods exist on the site
- Updated shipping calculator so it doesn't show a "No delivery options available for XXX, XX" message unless there's a full address. I figured the shopper could be negatively affected by such a message if they haven't even filled their address in and they're already seeing a message saying there are no shipping methods. Because of this, I updated the tests in `plugins/woocommerce-blocks/tests/e2e/tests/cart/cart-checkout-block-shipping.block_theme.spec.ts`.
- Added a `has_full_shipping_address` method to `ShippingController` - this uses `WC()->countries->get_country_locale` to determine whether the state, city, country, postcode (based on locale requirement) is filled before stripping out "shipping" methods (and leaving pickup methods intact).
  - Needed because we have to determine whether to remove rates from the response if shipping requires a full address.
  

### How to test the changes in this Pull Request:

Smoke test a few scenarios to ensure no regressions. For the shopper part it is best to open an incognito window to clear the address state that would be remembered between scenarios.

#### Scenario 1
1. Have local pickup disabled
2. Have hide shipping costs until address entered **enabled**
3. As shopper go through cart and checkout and ensure that shipping costs are not shown on cart page / checkout page until address entered

#### Scenario 2

1.  Have local pickup disabled
2. Have hide shipping costs until address entered **disabled**
3. As a shopper go through cart and checkout and ensure that shipping and pick up options are visible before address is entered

#### Scenario 3

1. Have local pickup enabled
2. Have hide shipping costs until address entered **enabled**
3.  As a shopper go through cart and checkout and ensure that shipping options are not shown but pickup options are still shown.

#### Scenario 4

1. Go to WC -> Settings -> General. Set Shipping location(s) to `Disable shipping & shipping calculations`
2. Try to check out with a physical product. You should not be able to enter a shipping address or select local pickup. Checkout should succeed.
3. Try to check out with a virtual product. You should not be able to enter a shipping address or select local pickup. Checkout should succeed.

#### General testing

Test with various setups of:
- Local pickup enabled/disabled
- Hide shipping costs until an address is entered enabled/disabled
- Shipping calculator enabled/disabled
- No shipping zones enabled on the whole site
- Only fallback shipping zones enabled
- No fallback zones enabled, but methods exist for specific countries. Test with addresses in and out of these countries.
- Mixtures of virtual, downloadable, and physical products in the cart. Try with each type individually too.

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [x] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 
Improve how we show/hide shipping address at cart and checkout based on options.

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

**Comment by samueljseay** [comment]
Hey @pmcpinto,

@opr and I did some adjustments of how we handle hiding/showing the addresses for shipping and pick up in this PR with a slight modification to the behaviour and wording of the `Hide shipping costs until an address is entered`. I was wondering if you could have a look at the new behaviour and see if it's ok.

**Comment by pmcpinto** [comment]
> @opr and I did some adjustments of how we handle hiding/showing the addresses for shipping and pick up in this PR with a slight modification to the behaviour and wording of the Hide shipping costs until an address is entered. I was wondering if you could have a look at the new behaviour and see if it's ok.

Thanks for the ping. The changes look good to me.

File: plugins/woocommerce/src/Blocks/Shipping/ShippingController.php [hunk 1]
```diff
@@ -433,6 +430,42 @@ function ( $rate ) {
 		return $packages;
 	}
 
+	/**
+	 * Remove shipping if no address is entered.
```
Comment (opr) [inline plugins/woocommerce/src/Blocks/Shipping/ShippingController.php]: Even though we just paired on this, it took me a minute to remember what this was for and figure out why. I think the comment could be updated, I made a suggestion:

```suggestion
	 * Remove shipping (i.e. delivery, not local pickup) if "Hide shipping costs until an address is entered" is enabled, and no address has been entered yet.
```

File: plugins/woocommerce/src/Blocks/Shipping/ShippingController.php [hunk 2]
```diff
@@ -433,6 +430,42 @@ function ( $rate ) {
...
+	 *
+	 * @param array $packages Array of shipping packages.
+	 * @return array
+	 */
+	public function remove_shipping_if_no_address( $packages ) {
+		$customer = wc()->customer;
```
Comment (opr) [inline plugins/woocommerce/src/Blocks/Shipping/ShippingController.php]: Lint error here, equals not lined up

File: plugins/woocommerce/src/Blocks/Shipping/ShippingController.php [hunk 3]
```diff
@@ -433,6 +430,42 @@ function ( $rate ) {
...
+		$has_address = $customer->has_shipping_address();
+
+		remove_filter( 'option_woocommerce_shipping_cost_requires_address', array( $this, 'override_cost_requires_address_option' ) );		
+		$option_checked = filter_var( get_option( 'woocommerce_shipping_cost_requires_address', 'no' ), FILTER_VALIDATE_BOOLEAN );
+		add_filter( 'option_woocommerce_shipping_cost_requires_address', array( $this, 'override_cost_requires_address_option' ) );
+
+		if ( ! $has_address && $option_checked ) {
+			$packages = array_map(
+				function ( $package ) {
+					if ( ! is_array( $package['rates'] ) ) {
```
Comment (opr) [inline plugins/woocommerce/src/Blocks/Shipping/ShippingController.php]: Do we want to check if `$package['rates']` is set first before we try is_array on it, just thinking if $package doesn't have a member called rates this will warn, won't it?

File: plugins/woocommerce/src/Blocks/Shipping/ShippingController.php [hunk 4]
```diff
@@ -433,6 +430,42 @@ function ( $rate ) {
...
+						$package['rates'] = array();
+						return $package;
+					}
+					$package['rates'] = array_filter(
+						$package['rates'],
+						function ( $rate ) {
+							return in_array( $rate->get_method_id(), LocalPickupUtils::get_local_pickup_method_ids(), true );
```
Comment (opr) [inline plugins/woocommerce/src/Blocks/Shipping/ShippingController.php]: Do we want to check if `$rate instanceof WC_Shipping_Rate` just in case?

**Review by opr — COMMENTED** [review]
Change makes sense to me, doesn't _solve_ the original issue, but the behaviour is improved and clearer isn't it?

I think you should ask for a second review since I helped you write this, however I made a couple of comments anyway that you may want to look at.

File: plugins/woocommerce/src/Blocks/Shipping/ShippingController.php [hunk 5]
```diff
@@ -142,13 +144,8 @@ public function remove_shipping_settings( $settings ) {
...
 			foreach ( $settings as $index => $setting ) {
 				if ( 'woocommerce_shipping_cost_requires_address' === $setting['id'] ) {
-					$settings[ $index ]['desc'] = sprintf(
-						/* translators: %s: URL to the documentation. */
-						__( 'Hide shipping costs until an address is entered (Not available when using the <a href="%s">Local pickup options powered by the Checkout block</a>)', 'woocommerce' ),
-						'https://woocommerce.com/document/woocommerce-blocks-local-pickup/'
-					);
-					$settings[ $index ]['disabled'] = true;
-					$settings[ $index ]['value']    = 'no';
+					$settings[ $index ]['desc'] =
```
Comment (mikejolley) [inline plugins/woocommerce/src/Blocks/Shipping/ShippingController.php]: Look at how "Debug mode" is presented on the same screen with the extra description below. I would add the second part like that to keep the label short.

`Local pickup rates will display in the Checkout block, even without an address`

Comment (mikejolley) [reply plugins/woocommerce/src/Blocks/Shipping/ShippingController.php]: This part is missing in test instructions FYI.

File: plugins/woocommerce/src/Blocks/Shipping/ShippingController.php [hunk 6]
```diff
@@ -433,6 +430,42 @@ function ( $rate ) {
...
+	 *
+	 * @param array $packages Array of shipping packages.
+	 * @return array
+	 */
+	public function remove_shipping_if_no_address( $packages ) {
+		$customer = wc()->customer;
+		$has_address = $customer->has_shipping_address();
+
+		remove_filter( 'option_woocommerce_shipping_cost_requires_address', array( $this, 'override_cost_requires_address_option' ) );		
+		$option_checked = filter_var( get_option( 'woocommerce_shipping_cost_requires_address', 'no' ), FILTER_VALIDATE_BOOLEAN );
```
Comment (mikejolley) [inline plugins/woocommerce/src/Blocks/Shipping/ShippingController.php]: I don't know which is "better" but there is a `wc_string_to_bool` function which does this.

File: plugins/woocommerce/src/Blocks/Shipping/ShippingController.php [hunk 7]
```diff
@@ -89,9 +90,10 @@ function () {
 	 * @return boolean Whether shipping cost calculation should require an address to be entered before calculating.
 	 */
 	public function override_cost_requires_address_option( $value ) {
-		if ( CartCheckoutUtils::is_checkout_block_default() && $this->local_pickup_enabled ) {
+		if ( is_checkout() && ! is_admin() && CartCheckoutUtils::is_checkout_block_default() && $this->local_pickup_enabled ) {
```
Comment (mikejolley) [inline plugins/woocommerce/src/Blocks/Shipping/ShippingController.php]: Why is the admin check needed when there is a check for `is_checkout()`?

**Review by mikejolley — COMMENTED** [review]
Seems to work fine. I added some comments in addition to Thomas' feedback.

File: plugins/woocommerce/src/Blocks/Shipping/ShippingController.php (hunk 4 above)
Comment (samueljseay) [reply plugins/woocommerce/src/Blocks/Shipping/ShippingController.php]: Can't hurt, but I'm curious what would make us be so defensive of this? Shouldn't we rather see fatal error so we can fix if we ever did not have a WC_Shipping_Rate in this array?

File: plugins/woocommerce/src/Blocks/Shipping/ShippingController.php (hunk 5 above)
Comment (samueljseay) [reply plugins/woocommerce/src/Blocks/Shipping/ShippingController.php]: Great suggestion thanks. Fixed in https://github.com/woocommerce/woocommerce/pull/53466/commits/3d9aae0f98dba5cda4ba9c29c05dcc7d53ffcceb

File: plugins/woocommerce/src/Blocks/Shipping/ShippingController.php (hunk 6 above)
Comment (samueljseay) [reply plugins/woocommerce/src/Blocks/Shipping/ShippingController.php]: I find filter var and it's wording about "validating a boolean" doesnt really match the idea of a straight conversion, so yeah I'm happy to use the woo one here.

File: plugins/woocommerce/src/Blocks/Shipping/ShippingController.php (hunk 7 above)
Comment (samueljseay) [reply plugins/woocommerce/src/Blocks/Shipping/ShippingController.php]: Thats a good point. It will never be admin if is_checkout is true. I'll change this and retest. Thanks for spotting this.

File: plugins/woocommerce/src/Blocks/Shipping/ShippingController.php (hunk 6 above)
Comment (samueljseay) [reply plugins/woocommerce/src/Blocks/Shipping/ShippingController.php]: Resolved in https://github.com/woocommerce/woocommerce/pull/53466/commits/ba1ce0874440608568fc0b2107bb0bf7f36cfeaa

File: plugins/woocommerce/src/Blocks/Shipping/ShippingController.php (hunk 7 above)
Comment (samueljseay) [reply plugins/woocommerce/src/Blocks/Shipping/ShippingController.php]: Resolved in https://github.com/woocommerce/woocommerce/pull/53466/commits/ba1ce0874440608568fc0b2107bb0bf7f36cfeaa

File: plugins/woocommerce/src/Blocks/Shipping/ShippingController.php (hunk 4 above)
Comment (samueljseay) [reply plugins/woocommerce/src/Blocks/Shipping/ShippingController.php]: Oh right because this comes from a filter ofc. Yeah I'll add the defensive check.

Comment (samueljseay) [reply plugins/woocommerce/src/Blocks/Shipping/ShippingController.php]: Resolved in https://github.com/woocommerce/woocommerce/pull/53466/commits/7c5344bbdec33a7a4523cd4cdf6b13527cf0ecd9

**Comment by samueljseay** [comment]
@opr @mikejolley Thanks so much for all the great suggestions. I've implemented and re-tested. Would you mind taking another look? 🙇

**Comment by mikejolley** [comment]
I'm seeing some very strange behaviour on this branch; maybe @opr can confirm.

1. Hide shipping options **enabled**
2. Local pickup options **enabled**
3. Incognito window. Add to cart. 
4. Cart page shows no shipping or pickup options
5. Checkout page shows pickup options. Change the pickup option. _Shipping address appears and pickup is hidden. Shipping/collection toggle block is also hidden_

This seems to be a bug.

**Review by opr — COMMENTED** [review]
Can also reproduce what Mike is seeing - Scenarios 1 and 2 are working OK but 3 is buggy.

Looks like [this line](https://github.com/woocommerce/woocommerce/blob/d1498d45f2804eede99538d13717c4e2cf602308/plugins/woocommerce/src/StoreApi/Schemas/V1/CartSchema.php#L346) is the cause, when selecting a local pickup method, the cart response is re-fetched, but because no address data is entered the packages are not returned in the response. (Didn't dig into why they are returned at first, though).

If you update that line to:

```php
		$shipping_packages = $has_calculated_shipping || LocalPickupUtils::is_local_pickup_enabled() ? $controller->get_shipping_packages() : [];
```

it seems to work, not sure if that's the best fix though.

**Comment by samueljseay** [comment]
Just noting that I've talked to @opr and will hand this PR over to him to take over the line while I focus on other priorities. I'm moving this PR into draft and then he can decide what to do next with it.

File: plugins/woocommerce/src/StoreApi/Schemas/V1/CartSchema.php [hunk 8]
```diff
@@ -342,8 +343,12 @@ public function get_item_response( $cart ) {
...
 		$has_calculated_shipping = $cart->show_shipping();
 
-		// Get shipping packages to return in the response from the cart.
-		$shipping_packages = $has_calculated_shipping ? $controller->get_shipping_packages() : [];
+		$has_local_pickup_methods = LocalPickupUtils::is_local_pickup_enabled() && count( LocalPickupUtils::get_local_pickup_method_ids() ) > 0;
+
+		// Get shipping packages to return in the response from the cart. Always get the shipping packages if local
+		// pickup is enabled and has methods. If the address is required then regular shipping rates will be filtered
+		// out later.
+		$shipping_packages = $has_calculated_shipping || $has_local_pickup_methods ? $controller->get_shipping_packages() : [];
```
Comment (opr) [inline plugins/woocommerce/src/StoreApi/Schemas/V1/CartSchema.php:351]: If there are local pickup methods, we should return these regardless of whether an address has been entered. `$has_calculated_shipping` is a _little_ misleading, as `$cart->show_shipping()` checks whether shipping is enabled and cart has items, and if an address is required to show shipping, returns whether the address fields are complete, otherwise returns true, so it's not really to do with calcuation completeness, but address completeness.

File: plugins/woocommerce/tests/php/src/Blocks/StoreApi/Routes/Checkout.php [hunk 9]
```diff
@@ -599,6 +599,7 @@ function ( $locale ) {
 			}
 		);
 
+		unset( WC()->countries->locale );
```
Comment (opr) [inline plugins/woocommerce/tests/php/src/Blocks/StoreApi/Routes/Checkout.php:606]: This is needed so the filter applied above actually works. This filter is applied after the locale is cached.

File: plugins/woocommerce/src/Blocks/Shipping/ShippingController.php [hunk 10]
```diff
@@ -433,6 +412,82 @@ function ( $rate ) {
...
 	}
 
+	/**
+	 * Checks whether the address is "full" in the sense that it contains all required fields to calculate shipping rates.
+	 *
+	 * @return bool Whether the customer has a full shipping address (address_1, city, state, postcode, country).
+	 * Only required fields are checked.
+	 */
+	public function has_full_shipping_address() {
+		$customer = WC()->customer;
```
Comment (mikejolley) [inline plugins/woocommerce/src/Blocks/Shipping/ShippingController.php:424]: Unlikely but to be defensive I would include a check to ensure this is a `WC_Customer` object. Before cart init this can be null.

File: plugins/woocommerce/src/Blocks/Shipping/ShippingController.php [hunk 11]
```diff
@@ -433,6 +412,82 @@ function ( $rate ) {
...
+			'postcode' => $customer->get_shipping_postcode(),
+			'country'  => $customer->get_shipping_country(),
+		);
+		$address_fields   = WC()->countries->get_country_locale();
+		$locale_key       = ! empty( $shipping_address['country'] ) && array_key_exists( $shipping_address['country'], $address_fields ) ? $shipping_address['country'] : 'default';
+		$default_locale   = $address_fields['default'];
+		$country_locale   = $address_fields[ $locale_key ] ?? array();
+
+		// For all fields in $shipping_address, check if they are required in the country-specific locale first, if
+		// not set, orn$address_fields and if so, check if they are not empty.
```
Comment (mikejolley) [inline plugins/woocommerce/src/Blocks/Shipping/ShippingController.php]: `orn$address_fields`?

File: plugins/woocommerce/src/Blocks/Shipping/ShippingController.php [hunk 12]
```diff
@@ -433,6 +412,82 @@ function ( $rate ) {
...
+		$shipping_cost_requires_address = wc_string_to_bool( get_option( 'woocommerce_shipping_cost_requires_address', 'no' ) );
+
+		// Return early here for a small performance gain if we don't need to hide shipping costs until an address is entered.
+		if ( ! $shipping_cost_requires_address ) {
+			return $packages;
+		}
+
+		$has_full_address = $this->has_full_shipping_address();
+
+		if ( ! $has_full_address ) {
```
Comment (mikejolley) [inline plugins/woocommerce/src/Blocks/Shipping/ShippingController.php]: We should tweak this to return early. So have:

```php
if ( $has_full_address ) {
	return $packages;
}
```

before the array map.

**Review by mikejolley — COMMENTED** [review]
Minor feedback attached. I tested a variety of flows. One thing stuck out as odd and it was this case.

1. Hide rates until address entered
2. Shop base UK. Local Pickup enabled. Local pickup location something odd like US address.
3. Go to cart. It says enter an address to see rates.
4. Enter UK address in shipping calculator. Submit.
5. Rates appear but the address shows a US address (the pickup location)

Its not a bug per-se but I had a moment where I was confused because I entered a UK address but it said I was collecting from a US address. Obviously I needed to pick a rate, but maybe it needs to reset selection after populating rates?

@opr

File: plugins/woocommerce/src/Blocks/Shipping/ShippingController.php (hunk 12 above)
Comment (opr) [reply plugins/woocommerce/src/Blocks/Shipping/ShippingController.php]: Thanks, done in 65f8bc8601610b8631312899fcd0e29f904d1fca

File: plugins/woocommerce/src/Blocks/Shipping/ShippingController.php (hunk 11 above)
Comment (opr) [reply plugins/woocommerce/src/Blocks/Shipping/ShippingController.php]: Not sure where that came from, but re-wrote this comment in 893a7b9c28798aa5f01756256336fee58120503a

File: plugins/woocommerce/src/Blocks/Shipping/ShippingController.php (hunk 10 above)
Comment (opr) [reply plugins/woocommerce/src/Blocks/Shipping/ShippingController.php:424]: Thanks, I think it's fine for this method to return false if that's the case, since the rates are not going to show anywhere anyway. Done in 1472929c07b9bdfc1e7206ee3dce63a3518534ea

File: plugins/woocommerce/includes/class-wc-shipping.php [hunk 13]
```diff
@@ -367,6 +367,12 @@ public function calculate_shipping_for_package( $package = array(), $package_key
 			 */
 			$package['rates'] = apply_filters( 'woocommerce_package_rates', $package['rates'], $package );
 
+			// Package rates should be an array, if it was filtered into a non-array, reset it. Don't reset to the
+			// unfiltered value, as e.g. a 3pd could have set it to "false" to remove rates.
+			if ( ! is_array( $package['rates'] ) ) {
+				$package['rates'] = array();
+			}
+
```
Comment (senadir) [inline plugins/woocommerce/includes/class-wc-shipping.php:375]: Did you actually run into an issue here?

**Review by senadir — APPROVED** [review]
Reviewed the code changes and they make sense to me, nothing that looks off.

File: plugins/woocommerce/includes/class-wc-shipping.php (hunk 13 above)
Comment (opr) [reply plugins/woocommerce/includes/class-wc-shipping.php:375]: Well, no not any specific issue, but we need to make sure it's an array before continuing. I originally wanted to just reset to the original rates, but Mike mentioned 

> Don't reset to the unfiltered value, as e.g. a 3pd could have set it to "false" to remove rates.

It seems fine to just empty it, because if they're actually changing the rates correctly, an array would be returned, I can't think of any use case where rates would be modified into a non-array and expected to show anything.

**Review by alexflorisca — APPROVED** [review]
I haven't reviewed the code, but I did go through the testing instructions and it all looks pretty groovy. I tried pretty hard to break it, setting the shop to only sell and ship to specific countries, and it works well. Just one thing probably worth mentioning.

When the shop is restricted to selling to only select countries, local pickup locations that are **not** in those countries are shown in the list. E.g. If I only sell to UK and US, and I have a pickup location in France, this shows in the list. I don't think this is a huge problem, as it's more of a setup problem by the merchant, but wondering if we should hide local pickup locations that are outside of the countries the shop sells to?

**Comment by opr** [comment]
> When the shop is restricted to selling to only select countries, local pickup locations that are **not** in those countries are shown in the list. E.g. If I only sell to UK and US, and I have a pickup location in France, this shows in the list. I don't think this is a huge problem, as it's more of a setup problem by the merchant, but wondering if we should hide local pickup locations that are outside of the countries the shop sells to?

Interesting use case, I think the distinction here is that local pickup is a _shipping_ address, so the customer may be billed in UK, but send their friend to collect in France in your above example. It seems weird and is probably not likely to ever be set up like that, so I'm happy to leave this as it is.

~There is a bug (not caused by this PR) where if you have local pickup options in different countries, then set values in "Ship to specific countries only" then no local pickup options appear unless _all_ local pickup options are in a supported country.~ - Can't reproduce now

Think that's for another day though the scope of this PR shouldn't grow any bigger!

File: plugins/woocommerce/src/StoreApi/Schemas/V1/CartSchema.php (hunk 8 above)
Comment (wavvves) [reply plugins/woocommerce/src/StoreApi/Schemas/V1/CartSchema.php:351]: Why not rename it and update comments? maybe `$can_calculate_shipping`.
We have other bits that can get confusing when looking at the var name, like `WC()->customer->has_calculated_shipping()`

Comment (wavvves) [reply plugins/woocommerce/src/StoreApi/Schemas/V1/CartSchema.php:351]: ~Also, by definition this sounds like  `ShippingController::has_full_shipping_address()` introduced in this PR~
Nevermind, the other goes beyond that to check if shipping can appear in Totals.
I see there's an issue to clear this https://github.com/woocommerce/woocommerce/issues/54894 :)

**Review by wavvves — APPROVED** [review]
Test steps, I messed around with it but didn't spot anything.
Approving, and left a nitpick.
