### PR TITLE
Interactivity API powered mini cart - Add  "Stock left" badge

### LINKED ISSUE #59010: Interactivity API powered Mini Cart - Show Stock left badge
## What?

When the stock of a product is low, in the current block there is an option to show a warning that there is not much stock left, and it is not respected in the minicart.

| Existing block | Experimental block |
|---------------|------------------|
| Image |  Image | 

## Steps to reproduce

> To test the experimental block, make sure `experimental-iapi-mini-cart` and `experimental-iapi-runtime` are set to `true` in the `development.json` file: [link](https://github.com/woocommerce/woocommerce/blob/c9cc094885a0351dd2cb550a5739f5980e0a5e6c/plugins/woocommerce/client/admin/config/development.json#L8-L9).

1. Edit a product -> Inventory -> Set Quantity to 1.
2. Select "Track stock quantity for this product" and "Do not allow".
3. Add that product to the cart.
4. Check that the stock left badge is shown.

### PR DESCRIPTION
**Pull request by SantosGuillamot**
**This PR is built on top of https://github.com/woocommerce/woocommerce/pull/59388 because it needs to read the backorder status.**

### Changes proposed in this Pull Request:

It adds support for the "Stock left" badge in the minicart powered by the iAPI. It replicates [this conditional ](https://github.com/woocommerce/woocommerce/blob/7cbfd3e1b09cfa0b0915d51cbaeabddcaed511c9/plugins/woocommerce/client/blocks/assets/js/base/components/cart-checkout/cart-line-items-table/cart-line-item-row.tsx#L247-L256) and the HTML returned by `ProductLowStockBadge`.

Closes #59010.

### Screenshots or screen recordings:

| Before | After |
|---------------|------------------|
| Image |  Image  | 

### How to test the changes in this Pull Request:

> To test the experimental block, make sure `experimental-iapi-mini-cart` and `experimental-iapi-runtime` are set to `true` in the `development.json` file: [link](https://github.com/woocommerce/woocommerce/blob/c9cc094885a0351dd2cb550a5739f5980e0a5e6c/plugins/woocommerce/client/admin/config/development.json#L8-L9).

1. Edit a product -> Inventory -> Set Quantity to 2.
2. Select "Track stock quantity for this product" and "Allow, but notify customer".
3. Add that product to the cart.
4. Check that the stock left badge is shown.
5. Reduce the quantity to 0 and check that the "Available in backorder" badge is shown instead.
6. You can also increase it to 10 to check it doesn't show anything in that case.

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment

Add "Stock left" badge to the iAPI powered minicart.

</details>

### CODE REVIEW

File: plugins/woocommerce/src/Blocks/BlockTypes/MiniCartItemsBlock.php [hunk 1]
```diff
@@ -97,6 +101,13 @@ protected function render_experimental_iapi_markup( $attributes, $content, $bloc
 										<div data-wp-bind--hidden="!state.isAvailableOnBackorder" class="wc-block-components-product-badge wc-block-components-product-backorder-badge" hidden>
 											<?php echo esc_html( $available_on_backorder_label ); ?>
 										</div>
+										<div 
+											class="wc-block-components-product-badge wc-block-components-product-low-stock-badge"
+											data-wp-bind--hidden="!state.isLowInStockVisible"
+											data-wp-text="state.lowInStockLabel"
+											hidden
```
Comment (DAreRodz) [inline plugins/woocommerce/src/Blocks/BlockTypes/MiniCartItemsBlock.php]: I don't think this `hidden` is necessary, as it is inside the `<template>` element. The `data-wp-bind--hidden` attribute would be added during either server-side or client-side rendering.

**Review by DAreRodz — APPROVED** [review]
Looks good to me!

File: plugins/woocommerce/src/Blocks/BlockTypes/MiniCartItemsBlock.php (hunk 1 above)
Comment (SantosGuillamot) [reply plugins/woocommerce/src/Blocks/BlockTypes/MiniCartItemsBlock.php]: I've removed the `hidden` property and opened https://github.com/woocommerce/woocommerce/issues/59477 to track and discuss the server initialization.
