### PR TITLE
Resolved invalid atc form submit button animation

### LINKED ISSUE #59282: Add to Cart + Options: disable button optimistic updates if the form is invalid
The *Add to Cart Button* has optimistic updates: when clicked, it increases the "X in cart" count before receiving a response from the backend. That works well in most cases because most requests succeed. But in the *Add to Cart + Options* block, the form might be invalid (ie: variable products with no attributes selected). In those cases, optimistic updates should be disabled.

## **To Reproduce**

1. Go to *Appearance* > *Editor* > *Templates* > *Single Product*.
2. Click on the *Add to Cart with Options* block and update to the blockified version.
3. In the frontend, go to a variable product page.
4. You might need to throttle network requests using your browser devtools to see the issue.
5. Click on *Add to cart* before selecting any attribute.
6. Notice the button changes to "1 in cart" to then go back to "Add to cart".

https://github.com/user-attachments/assets/cbd5e094-9240-4b7e-bb2e-9a8ca470da24

## **Expected behavior**

When we know the form is invalid, and we will likely display an error, the button shouldn't change to "1 in cart" until the request succeeded.

### PR DESCRIPTION
**Pull request by Kallyan01**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:
This PR fixes a minor animation glitch that occurs on variable product pages. When a user clicks the "Add to Cart" button, a slide animation intended to reflect quantity change briefly flashes, even though the quantity remains unchanged.

Closes #59282 .

### Screenshots or screen recordings:

https://github.com/user-attachments/assets/adf93ed3-dc44-431d-8fd2-3711a732de17

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Go to store page .
2. Select a variable product which has different variations .
3. On the single product page don't select any variation options .
4. Click on the disabled `Add to Cart` button .
5. Notice a error notice will be visible but no animation change will be observed in the `Add to Cart` button as described in the issue .
6. Aditionally test the _Product Collection Block_  Add to cart button animation functionality .

https://github.com/user-attachments/assets/beebf48d-1484-449d-9a41-818732e820be

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce/client/blocks/assets/js/atomic/blocks/product-elements/button/frontend.ts [hunk 1]
```diff
@@ -194,9 +194,12 @@ const productButtonStore = {
 			// We start the animation if the temporary quantity is out of
 			// sync with the quantity in the cart and the animation hasn't
 			// started yet.
+
```
Comment (Aljullu) [inline plugins/woocommerce/client/blocks/assets/js/atomic/blocks/product-elements/button/frontend.ts]: I would update this comment mentioning that we skip the animation altogether if the _Add to Cart + Options_ form is invalid.

**Review by Aljullu — COMMENTED** [review]
Thanks for investigating this, @Kallyan01! It's working well on my end. I left one minor comment, but besides that, LGTM. Good job!

https://github.com/user-attachments/assets/cdcf141c-280b-410e-a1a0-c008e526f1ef

<details>
<summary>Testing environment</summary>

* WordPress 6.8.1 local dev environment
* Plugins: WooCommerce Beta Tester
* Theme: Woo Starter Theme
* Store creation: June 2025
* Store size: small
</details>

**Comment by Kallyan01** [comment]
Thanks @Aljullu , updated the comment , please do take a look .

**Review by Aljullu — APPROVED** [review]
Thanks, @Kallyan01! It looks good to me!
