### PR TITLE
fix/28214 Backorders have a wrong availability on application/ld+json

### LINKED ISSUE #28214: Backorders have a wrong availability on application/ld+json
JSON structured data on single products pages are showing availability instock on backorder products. According to Schema, the availability value should be instead PreSale or PreOrder:

https://schema.org/ItemAvailability

As a consequence, Google shows a wrong availability on its SERP.

I have tested it  in Storefront without any other active plugin than WooCommerce.

<details>
```
`
### WordPress Environment ###

WordPress address (URL): https://dev.fanaticguitars.com
Site address (URL): https://dev.fanaticguitars.com
WC Version: 4.6.1
REST API Version: ✔ 4.6.1
WC Blocks Version: ✔ 3.4.0
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.6.2
Log Directory Writable: ✔
WP Version: 5.5.3
WP Multisite: –
WP Memory Limit: 1,020 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.4.4
PHP Post Max Size: 128 MB
PHP Time Limit: 3600
PHP Max Input Vars: 9999
cURL Version: 7.65.0
OpenSSL/1.0.2o

SUHOSIN Installed: –
MySQL Version: 5.6.21
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.6.1
WC Database Prefix: wp_
Total Database Size: 1032.45MB
Database Data Size: 725.12MB
Database Index Size: 307.33MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_order_items: Data: 0.67MB + Index: 0.37MB + Engine MyISAM
wp_woocommerce_order_itemmeta: Data: 6.83MB + Index: 3.78MB + Engine MyISAM
wp_woocommerce_tax_rates: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
backorders_en: Data: 0.00MB + Index: 0.00MB + Engine
backorders_es: Data: 0.00MB + Index: 0.00MB + Engine
constock: Data: 0.00MB + Index: 0.00MB + Engine
diff_price_lsi_woo: Data: 0.00MB + Index: 0.00MB + Engine
diff_stock_lsi_woo: Data: 0.00MB + Index: 0.00MB + Engine
lista_productos: Data: 0.00MB + Index: 0.00MB + Engine
lista_productos_all: Data: 0.00MB + Index: 0.00MB + Engine
lista_productos_fix_stock: Data: 0.00MB + Index: 0.00MB + Engine
lsi_woo_sync: Data: 0.00MB + Index: 0.00MB + Engine
noStockToday: Data: 0.02MB + Index: 0.03MB + Engine MyISAM
noStockYesterday: Data: 0.02MB + Index: 0.03MB + Engine MyISAM
price_en: Data: 0.00MB + Index: 0.00MB + Engine
price_idioma: Data: 0.00MB + Index: 0.00MB + Engine
productos_variables: Data: 0.00MB + Index: 0.00MB + Engine
product_visibility: Data: 0.00MB + Index: 0.00MB + Engine
regular_price_en: Data: 0.00MB + Index: 0.00MB + Engine
regular_price_es: Data: 0.00MB + Index: 0.00MB + Engine
regular_price_idioma: Data: 0.00MB + Index: 0.00MB + Engine
sale_price_en: Data: 0.00MB + Index: 0.00MB + Engine
sale_price_es: Data: 0.00MB + Index: 0.00MB + Engine
sale_price_idioma: Data: 0.00MB + Index: 0.00MB + Engine
sinstock: Data: 0.00MB + Index: 0.00MB + Engine
stock_en: Data: 0.00MB + Index: 0.00MB + Engine
stock_es: Data: 0.00MB + Index: 0.00MB + Engine
stock_idioma: Data: 0.00MB + Index: 0.00MB + Engine
wp_actionscheduler_actions: Data: 144.20MB + Index: 73.25MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 77.14MB + Index: 64.19MB + Engine InnoDB
wp_aelia_dismissed_messages: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_aelia_exchange_rates_history: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ariadminer_connections: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_bannerize: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_cartflows_ca_cart_abandonment: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_cartflows_ca_email_history: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_cartflows_ca_email_templates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cartflows_ca_email_templates_meta: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_cart_process: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_commentmeta: Data: 0.17MB + Index: 0.09MB + Engine MyISAM
wp_comments: Data: 3.12MB + Index: 1.27MB + Engine MyISAM
wp_cookie_compliance_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_cookie_compliance_visitor: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_duplicator: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_duplicator_packages: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_duplicator_pro_entities: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_duplicator_pro_packages: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_failed_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gf_addon_feed: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_gf_draft_submissions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_gf_entry: Data: 2.52MB + Index: 0.39MB + Engine InnoDB
wp_gf_entry_meta: Data: 5.52MB + Index: 7.58MB + Engine InnoDB
wp_gf_entry_notes: Data: 1.52MB + Index: 0.19MB + Engine InnoDB
wp_gf_form: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gf_form_meta: Data: 0.11MB + Index: 0.00MB + Engine InnoDB
wp_gf_form_revisions: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gf_form_view: Data: 1.52MB + Index: 0.92MB + Engine InnoDB
wp_icl_cms_nav_cache: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_icl_content_status: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_icl_core_status: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_icl_currencies: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_icl_flags: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_icl_languages: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_icl_languages_currencies: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_icl_languages_translations: Data: 0.10MB + Index: 0.11MB + Engine MyISAM
wp_icl_locale_map: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_icl_message_status: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_icl_mo_files_domains: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_node: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_icl_reminders: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_icl_strings: Data: 5.50MB + Index: 3.69MB + Engine MyISAM
wp_icl_string_batches: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_string_packages: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_string_pages: Data: 39.58MB + Index: 64.16MB + Engine InnoDB
wp_icl_string_positions: Data: 0.11MB + Index: 0.03MB + Engine MyISAM
wp_icl_string_status: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_icl_string_translations: Data: 0.04MB + Index: 0.03MB + Engine MyISAM
wp_icl_string_urls: Data: 0.08MB + Index: 0.06MB + Engine InnoDB
wp_icl_translate: Data: 30.71MB + Index: 5.41MB + Engine MyISAM
wp_icl_translate_job: Data: 0.63MB + Index: 0.33MB + Engine MyISAM
wp_icl_translations: Data: 4.32MB + Index: 8.09MB + Engine MyISAM
wp_icl_translation_batches: Data: 0.13MB + Index: 0.00MB + Engine InnoDB
wp_icl_translation_downloads: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_translation_status: Data: 29.38MB + Index: 1.19MB + Engine MyISAM
wp_imagify_files: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_imagify_folders: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_lhr_log: Data: 4.02MB + Index: 0.00MB + Engine InnoDB
wp_links: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mailchimp_carts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mclean_refs: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
wp_mclean_scan: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
wp_mrw_cities: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mrw_orders: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mrw_ranges: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mrw_taxes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ms_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 7.82MB + Index: 0.32MB + Engine MyISAM
wp_pagantis_concurrency: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pagantis_config: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pagantis_logs: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
wp_pmt_concurrency: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pmt_config: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pmt_logs: Data: 0.47MB + Index: 0.00MB + Engine InnoDB
wp_pmxe_exports: Data: 0.41MB + Index: 0.00MB + Engine InnoDB
wp_pmxe_google_cats: Data: 0.39MB + Index: 0.00MB + Engine InnoDB
wp_pmxe_posts: Data: 0.22MB + Index: 0.00MB + Engine InnoDB
wp_pmxe_templates: Data: 0.30MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_files: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_pmxi_history: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_imports: Data: 0.17MB + Index: 0.00MB + Engine MyISAM
wp_pmxi_posts: Data: 0.05MB + Index: 0.02MB + Engine MyISAM
wp_pmxi_templates: Data: 0.23MB + Index: 0.00MB + Engine MyISAM
wp_postmeta: Data: 274.86MB + Index: 33.13MB + Engine MyISAM
wp_posts: Data: 36.74MB + Index: 8.63MB + Engine MyISAM
wp_queue: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_redirection_404: Data: 0.13MB + Index: 0.11MB + Engine InnoDB
wp_redirection_groups: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_redirection_items: Data: 0.05MB + Index: 0.08MB + Engine InnoDB
wp_redirection_logs: Data: 0.06MB + Index: 0.08MB + Engine InnoDB
wp_redirection_modules: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_relevanssi: Data: 7.64MB + Index: 10.96MB + Engine MyISAM
wp_relevanssi_log: Data: 0.32MB + Index: 0.15MB + Engine MyISAM
wp_relevanssi_stopwords: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wp_rg_form: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_rg_form_meta: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
wp_rg_form_view: Data: 1.52MB + Index: 0.69MB + Engine InnoDB
wp_rg_incomplete_submissions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_rg_lead: Data: 0.41MB + Index: 0.13MB + Engine InnoDB
wp_rg_lead_detail: Data: 1.52MB + Index: 2.05MB + Engine InnoDB
wp_rg_lead_detail_long: Data: 0.20MB + Index: 0.00MB + Engine InnoDB
wp_rg_lead_meta: Data: 0.33MB + Index: 0.45MB + Engine InnoDB
wp_rg_lead_notes: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_shipment_batch_process: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_sib_model_contact: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_sib_model_country: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_smush_dir_images: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_termmeta: Data: 1.52MB + Index: 0.67MB + Engine InnoDB
wp_terms: Data: 0.03MB + Index: 0.05MB + Engine MyISAM
wp_term_relationships: Data: 1.21MB + Index: 2.38MB + Engine MyISAM
wp_term_taxonomy: Data: 0.05MB + Index: 0.05MB + Engine MyISAM
wp_usermeta: Data: 3.11MB + Index: 1.57MB + Engine MyISAM
wp_users: Data: 0.16MB + Index: 0.12MB + Engine MyISAM
wp_w3tc_cdn_queue: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wclsi_items: Data: 4.52MB + Index: 2.33MB + Engine InnoDB
wp_wclsi_item_attribute_sets: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wclsi_item_categories: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wclsi_item_e_commerce: Data: 0.45MB + Index: 0.09MB + Engine InnoDB
wp_wclsi_item_images: Data: 0.08MB + Index: 0.09MB + Engine InnoDB
wp_wclsi_item_prices: Data: 1.52MB + Index: 0.36MB + Engine InnoDB
wp_wclsi_item_shops: Data: 1.52MB + Index: 2.92MB + Engine InnoDB
wp_wcpdf_credit_note_number: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcpdf_invoice_number: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
wp_wcpdf_packing_slip_number: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcpdf_proforma_number: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 1.52MB + Index: 0.31MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_gpf_render_cache: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 1.52MB + Index: 0.64MB + Engine InnoDB
wp_wc_order_stats: Data: 0.45MB + Index: 0.45MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.27MB + Index: 0.23MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 1.52MB + Index: 1.67MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woochimp_scheduled_events: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_gpf_google_taxonomy: Data: 2.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_table_rates: Data: 0.02MB + Index: 0.01MB + Engine MyISAM
wp_woocommerce_shipping_zone_shipping_methods: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woo_shippment_provider: Data: 0.09MB + Index: 0.00MB + Engine InnoDB
wp_wprc_cached_requests: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wprc_extensions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wprc_extension_types: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wprc_repositories: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wprc_repositories_relationships: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_zerospam_blocked_ips: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_zerospam_log: Data: 4.52MB + Index: 0.36MB + Engine InnoDB

### Post Type Counts ###

acf: 3
acf-field: 8
acf-field-group: 3
attachment: 76329
blog: 59
ewsm_search: 3170
jp_img_sitemap: 10
jp_img_sitemap_index: 1
jp_sitemap: 1
jp_sitemap_master: 1
nav_menu_item: 108
oembed_cache: 482
page: 44
post: 2
product: 9717
product_variation: 8
reverb: 1230
revision: 1
shop_coupon: 5
shop_order: 3604
shop_order_refund: 417
vtmin-rule: 1
wooframework: 39
wpcf7_contact_form: 2
wp_block: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 4.6.1 (update to version 4.6.2 is available)

### Inactive Plugins (36) ###

Advanced Custom Fields: by Elliot Condon – 5.9.3
Advanced Shipment Tracking for WooCommerce: by zorem – 3.1.4
Aelia Currency Switcher for WooCommerce: by Aelia – 4.9.1.201005
Aelia Foundation Classes for WooCommerce: by Aelia – 2.0.22.201005
Aelia Tax Display by Country for WooCommerce: by Aelia – 1.12.2.200127 – Installed version not tested with active version of WooCommerce 4.6.1
Akismet Anti-Spam: by Automattic – 4.1.7
Easy WP SMTP: by wpecommerce
alexanderfoxc – 1.4.1

Fanatic Guitars Admin Theme: by Fanatic Guitars Web SCP – 1.0
Google Tag Manager for Wordpress: by Thomas Geiger – 1.11.5 – Installed version not tested with active version of WooCommerce 4.6.1
Google XML Sitemaps: by Auctollo – 4.1.1
Gravity Forms: by Gravity Forms – 2.4.21
Gravity Forms Mailchimp Add-On: by Gravity Forms – 4.8
Gravity Forms Multilingual: by OnTheGoSystems – 1.5.4
Pagantis: by Pagantis – 8.3.6
Query Monitor: by John Blackbourn – 3.6.4
Stop Spammers: by Trumani – 2020.6.1
WooChimp: by RightPress – 2.2.7 – Installed version not tested with active version of WooCommerce 4.6.1
WooCommerce Blacklister: by Aelia – 1.0.5.200727 – Installed version not tested with active version of WooCommerce 4.6.1
WooCommerce Brands: by WooCommerce – 1.6.20 (update to version 1.6.21 is available) – Installed version not tested with active version of WooCommerce 4.6.1
WooCommerce EU VAT Assistant: by Aelia – 1.14.13.201103
WooCommerce Google Product Feed: by Ademti Software Ltd. – 9.3.0 (update to version 9.3.1 is available)
WooCommerce Multilingual: by OnTheGoSystems – 4.10.3 – Installed version not tested with active version of WooCommerce 4.6.1
WooCommerce PayPal Checkout Gateway: by WooCommerce – 2.1.0 – Installed version not tested with active version of WooCommerce 4.6.1
WooCommerce PDF Invoices & Packing Slips: by Ewout Fernhout – 2.7.0
WooCommerce PDF Invoices & Packing Slips Professional: by Ewout Fernhout – 2.6.6 – Installed version not tested with active version of WooCommerce 4.6.1
WooCommerce Sendinblue Newsletter Subscription: by Sendinblue – 2.0.3 – Installed version not tested with active version of WooCommerce 4.6.1
WooCommerce Servired/RedSys Spain Gateway: by José Conti – 12.0.0
WooCommerce Table Rate Shipping: by WooCommerce – 3.0.30 – Installed version not tested with active version of WooCommerce 4.6.1
WooCommerce URL Coupons: by SkyVerge – 2.5.3 (update to version 2.11.0 is available) – Installed version not tested with active version of WooCommerce 4.6.1
WPML CMS Nav: by OnTheGoSystems – 1.5.5
WPML Media: by OnTheGoSystems – 2.6.0
WPML Multilingual CMS: by OnTheGoSystems – 4.4.4
WPML String Translation: by OnTheGoSystems – 3.1.4
WPML Translation Management: by OnTheGoSystems – 2.10.2
WP Overnight Sidekick: by Jeremiah Prummer
Ewout Fernhout
Michael Kluver – 2.2.2

WP Rocket: by WP Media – 3.7.4

### Dropin Plugins (1) ###

advanced-cache.php: advanced-cache.php

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: EUR (€)
Currency Position: right
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #37864 - /tienda/
Cart: #883 - /cart/
Checkout: #884 - /checkout/
My account: #9 - /my-account/
Terms and conditions: #616 - /terminos-condiciones/

### Theme ###

Name: Storefront
Version: 2.8.0
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 360,005
Oldest: 2020-10-09 08:10:25 +0000
Newest: 2020-11-09 08:10:19 +0000

Failed: 6
Oldest: 2019-07-18 18:13:22 +0000
Newest: 2020-01-16 09:02:09 +0000

Pending: 4
Oldest: 2020-11-09 08:10:30 +0000
Newest: 2021-05-03 11:27:56 +0000

`
```
</details>

### PR DESCRIPTION
**Pull request by NguyenBao10**
Closes #28214.

Testing instruction: 
- Create some products with different stock status, we have 3 status now (instock, outofstock, onbackorder), so 3 products is minimum
- You can set stock status for those products at Inventory tab in product admin page as below

image

- Visit each product's page and view page source, then find the availability attribute in LD+JSON schema
- Make sure this value is correct with product's stock status:
      onbackorder = BackOrder
      instock = InStock
      outofstock = OutOfStock
image

### CODE REVIEW

File: plugins/woocommerce/includes/class-wc-structured-data.php [hunk 1]
```diff
@@ -257,9 +257,25 @@ public function generate_product_data( $product = null ) {
...
+					$stock_status_schema = 'InStock';
+					break;
+				case 'outofstock':
+                    $stock_status_schema = 'OutOfStock';
+					break;
+				case "onbackorder":
+                    $stock_status_schema = 'BackOrder';
+					break;
+				default:
+                    $stock_status_schema = '';
```
Comment (jorgeatorres) [inline plugins/woocommerce/includes/class-wc-structured-data.php]: I don't think we should allow an empty `$stock_status_schema` as that might result in broken JSON. Also, looking at how this is working right now, I can see that we are really using the result from [`is_in_stock()`](https://github.com/woocommerce/woocommerce/blob/b0f042e252cd7adeabfe6c131734c3b0aa40bd36/plugins/woocommerce/includes/abstracts/abstract-wc-product.php#L1670-L1672) which involves a filter.

We don't want to lose that flexibility (for other plugins to use that filter to change the "in stock" status) nor affect backwards compatibility, so I'd suggest we do things slightly different.

How about instead of a `case` we do a check for `is_in_stock()` and set `$stock_status_schema` to either `InStock` or `BackOrder` if the stock status is explicitly "backorder". Otherwise, we set `$stock_status_schema` to `OutOfStock`.

That way we preserve current behavior and also reduce the chances that we end up with an empty `$stock_status_schema`.

For example, something along these lines might work:

```php
if ( $product->is_in_stock() ) {
	$stock_status_schema = ( 'onbackorder' === $product->get_stock_status() ) ? 'BackOrder' : 'InStock';
} else {
	$stock_status_schema = 'OutOfStock';
}
```

What are your thoughts?

**Review by jorgeatorres — CHANGES_REQUESTED** [review]
Hi @NguyenBao10,

Thanks for your contribution 💯! This works great, but after exploring a bit more how things are working correctly, I left a suggestion.
Even though your code is correct, the current implementation uses `is_in_stock()` instead of explicitly checking the stocks status via `get_stock_status()`, so it allows 3d party plugins to mark products as in stock regardless of the exact status.

We don't want to lose that, but we do want to handle backorders better, and I described a way to do that, but feel free to implement it other ways.

Also: +100 points on adding the changelog file with the PR, which is something a few people struggle with. I think it'd also be good to write some testing instructions as part of the PR description.

Please let me know what you think!

File: plugins/woocommerce/includes/class-wc-structured-data.php (hunk 1 above)
Comment (NguyenBao10) [reply plugins/woocommerce/includes/class-wc-structured-data.php]: yeah, i did not notice about 3d party plugins, so your way is more flexible and better, let me improve this, thank you

**Review by jorgeatorres — APPROVED** [review]
LGTM. Thank you @NguyenBao10 for your contribution!
