### PR TITLE
Hid variable parent products from "Add Products" search on order page

### LINKED ISSUE #24018: For variable product only its variations name should come on adding product in a order from back-end
**Describe the bug**
For variable product only its active variations name should come on adding product in a order from back-end not the parent product name

**To Reproduce**
1. Go to Add order
2. Click on add item => add product.
3. In drop-down showing parent variable product name also and placing order with random product price among variations.

**Screenshots**
variable

**Expected behavior**
Parent variable product name must not appear in the drop-down and its order must not be placed. Only variation name come.

**WordPress Environment**
status

### PR DESCRIPTION
**Pull request by ObliviousHarmony**
### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Right now, variable product parents can be added to orders. This change prevents that from being possible.

Closes #24018.

### How to test the changes in this Pull Request:

1. Create a variable product with a variation.
2. Go to orders in the admin area and create one.
3. Select "Add Item(s)" and select a product.
4. Enter the name of the variable product.
5. Without the change, both the variation and the parent product will be visible and can be added to the order. With the change, the parent product is hidden, and if you could see it, an error would be thrown when adding it.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Fix: Prevent variable product parents from being added to orders.
> Dev: Ability to exclude certain product types from product search calls.

### CODE REVIEW

File: includes/class-wc-ajax.php [hunk 1]
```diff
@@ -1536,6 +1540,15 @@ public static function json_search_products( $term = '', $include_variations = f
 		$include_ids = ! empty( $_GET['include'] ) ? array_map( 'absint', (array) wp_unslash( $_GET['include'] ) ) : array();
 		$exclude_ids = ! empty( $_GET['exclude'] ) ? array_map( 'absint', (array) wp_unslash( $_GET['exclude'] ) ) : array();
 
+		if ( ! empty( $_GET['exclude_type'] ) ) {
+			$exclude_types = array_map( 'strtolower', (array) wp_unslash( $_GET['exclude_type'] ) ); // phpcs:ignore WordPress.Security.ValidatedSanitizedInput.InputNotSanitized
```
Comment (claudiosanches) [inline includes/class-wc-ajax.php]: We could replace this code to:
```php
$exclude_types = array_map( 'trim', array_map( 'strtolower', explode( ',', wp_unslash( $_GET['exclude_type'] ) ) ) )
```

**Review by claudiosanches — DISMISSED** [review]
Great work!
Just a small tweak left to be done, just to better allow exclude multiple types of product separated by comma.

File: includes/class-wc-ajax.php (hunk 1 above)
Comment (ObliviousHarmony) [reply includes/class-wc-ajax.php]: I've added support for comma delimited lists.

**Review by kloon — APPROVED** [review]
LGTM, the failing coding standard test is from code you did not touch so will let that go.

**Comment by ObliviousHarmony** [comment]
Hello @sotirissmix,

I'm sorry for any inconvenience this change may have caused you!

> This effectively destroys the AJAX search when creating orders. Not all websites have use for this functionality, and it would be better to implement an option within woocommerce to control whether you want variable products to appear or not.

Could you tell me about the setup and workflow that this change broke? I don't think adding more configuration options is the solution, given that parent products aren't used in orders in the first place.

> If the intended use was to hide the parent variable product but only show it's variants, currently it does not accomplish this function.

I've just tested against master and indeed, all other types products (including`product_variation`) are visible. The only type of product that should be excluded by this is the variable product type, which is the parent product type.

**Comment by sotirissmix** [comment]
I tested it on an older installation (WooCommerce 3.4.x) that got upgraded to 3.9.1. 
Before the update, the AJAX search when adding a product to an order worked correctly, showing all products as expected. 

After the update, it would only show products that weren't set as "variable", excluding both parent and child variable products. 

Haven't had the chance to check if something else was wrong code-wise, but once this specific line was reverted back to not excluding data, the AJAX search functioned as expected again.

I did perform some database maintenance and optimization, product lookup table recreation and plugin reinstallation (after testing all major plugin versions from 3.4 to 3.9.1) prior to finding this commit.

The installation this all happened on is running a multitude of WC extensions, but were all disabled during the testing of the AJAX search function so I'm not sure if they created a conflict somehow. 

Seeing as nobody else has commented on this issue yet, I will assume for now that it was an installation specific problem that required this line to be reverted back to it's non-exclusion state.
