### PR TITLE
Revert "Clear" Button from <button> to <a> Tag for Improved Theme Compatibility while maintaining accessibility improvements #54309

### LINKED ISSUE #54085: "clear" button to clear variations on single product page has changed from a <a> to a <button>. Causes issues to my theme UI
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

I have confirmed that the issue with your support. As they say
"I understand your frustration. I have checked the issue on my test site and noticed that the “Clear” text previously appeared in an <a> tag. After updating to the new version, the “Clear” text now appears in a <button> tag, which makes it a button and applies the button style from your theme."

So, my theme's "button styling" comes into effect. This is not good, as it is exactly the same as the "add to cart" button next door. I can restyle this button with CSS, but it will never look good. I just have "clear" transparent button, floating around with different colour text, with no context, and not lined up nicely. You can't just change a <a> to a <button> and not expect issues... BTW, I'm using Storefront theme, so thats as standard as you get theme wise.
The current Clear, looks good, it's subtle, and it lines up perfectly. 

### Expected behavior

what used to happen.
https://snipboard.io/jqGwuv.jpg

### Actual behavior

Current behaviour 
https://snipboard.io/1erpDb.jpg

The line up is really bad. Especially if variations have different prices. The Clear is just above the price and looks "lost". It is closer to the price than the variations themselves 

### Steps to reproduce

find a product with variations
select a variation.

The clear button (or text) appears

### WordPress Environment

<details><summary>System Status Report</summary>

```
### WordPress Environment ###

WordPress address (URL): [Redacted]
Site address (URL): [Redacted]
WC Version: 9.5.1
Legacy REST API Package Version: The Legacy REST API plugin is not installed on this site.
Action Scheduler Version: ✔ 3.9.0
Log Directory Writable: ✔
WP Version: 6.7.1
WP Multisite: –
WP Memory Limit: 2 GB
WP Debug Mode: –
WP Cron: ✔
Language: en_ZA
External object cache: –

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 8.1.31
PHP Post Max Size: 512 MB
PHP Time Limit: 300
PHP Max Input Vars: 1000
cURL Version: 8.9.1
OpenSSL/1.1.1w

SUHOSIN Installed: –
MySQL Version: 10.6.20-MariaDB-cll-lve
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

[REDACTED]

### Post Type Counts ###

adt_product_feed: 9
amn_exact-metrics: 1
attachment: 6602
custom_css: 9
customize_changeset: 6
filter-field: 1
filter-set: 1
grw_feed: 2
kadence_form: 1
ml-slide: 5
ml-slider: 3
nav_menu_item: 302
oembed_cache: 189
page: 26
post: 61
product: 1615
product_variation: 2996
revision: 1912
rm_content_editor: 1
shop_coupon: 3
shop_order: 3078
shop_order_refund: 1
sidebar_instance: 6
tablepress_table: 52
wp_block: 7
wp_global_styles: 1
wp_navigation: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (47) ###

Akismet Anti-spam: Spam Protection: by Automattic - Anti-spam Team – 5.3.5
Banner Management For WooCommerce: by theDotstore – 2.5.0
Bulky - Bulk Edit Products for WooCommerce: by VillaTheme – 1.2.9
Classic Widgets: by WordPress Contributors – 0.3
Code Snippets: by Code Snippets Pro – 3.6.6.1
GTM4WP - A Google Tag Manager (GTM) plugin for WordPress: by Thomas Geiger – 1.20.3
Email Templates: by wpexpertsio – 1.4.4
Filter Everything — WooCoomerce Product & WordPress Filter: by Andrii Stepasiuk – 1.8.8
Homepage Control: by WooThemes – 2.0.3
Smash Balloon Instagram Feed: by Smash Balloon – 6.6.1
Kadence Blocks – Gutenberg Blocks for Page Builder Features: by Kadence WP – 3.4.3
Max Mega Menu - Pro Addon: by megamenu.com – 2.4
Max Mega Menu - StoreFront Integration: by megamenu.com – 1.0.3
Max Mega Menu: by megamenu.com – 3.4.1
Payment Methods by Product & Country for WooCommerce: by WPFactory – 1.8.1
Perfect Brands WooCommerce: by QuadLayers – 3.4.7
PW WooCommerce Gift Cards Pro: by Pimwick
LLC – 1.221

Rank Math SEO PRO: by Rank Math – 3.0.72
Rank Math SEO: by Rank Math SEO – 1.0.234.1
Simple Social Icons: by OsomPress – 3.2.5
Storefront Blog Customiser: by WooCommerce – 1.3.0
Storefront Powerpack: by WooCommerce – 1.6.3
TablePress Extension: Responsive Tables: by Tobias Bäthge – 1.8
TablePress: by Tobias Bäthge – 3.0.1
Category Order and Taxonomy Terms Order: by Nsp-Code – 1.8.7
WC Hide Shipping Methods: by Rynaldo Stoltz – 1.8
WebP Express: by Bjørn Rosell – 0.25.9
Widget Context: by Kaspars Dambis – 1.3.3
Plugin for Google Reviews: by RichPlugins  – 5.1
WPC Product Bundles for WooCommerce (Premium): by WPClever – 8.1.6
Product Feed ELITE for WooCommerce: by AdTribes.io – 4.9.9
Product Feed PRO for WooCommerce: by AdTribes.io – 13.4.0
Product Filter by WBW: by woobewoo – 2.7.7
WooCommerce.com Update Manager: by Automattic – 1.0.3
Variation Swatches for WooCommerce - Pro: by Emran Ahmed – 2.1.5
Variation Swatches for WooCommerce: by Emran Ahmed – 2.1.3
WooCommerce Payfast Gateway: by WooCommerce – 1.6.9
WooCommerce: by Automattic – 9.5.1
WBW Product Filter PRO: by WBW – 2.7.6
Wordfence Security: by Wordfence – 8.0.1
WP Crontrol: by John Blackbourn – 1.17.1
WP File Manager: by mndpsingh287 – 8.0
WP Rollback: by WP Rollback – 2.0.7
Social Chat PRO: by QuadLayers – 7.3.8
Social Chat: by QuadLayers – 7.5.0
Custom Product Tabs for WooCommerce: by Code Parrots – 1.8.5
Yoco Payments: by Yoco – 3.8.1

### Inactive Plugins (3) ###

LiteSpeed Cache: by LiteSpeed Technologies – 6.5.4
OMGF: by Daan from Daan.dev – 5.9.1
WooCommerce Direct Checkout: by QuadLayers – 3.4.2

### Dropin Plugins () ###

advanced-cache.php: advanced-cache.php
maintenance.php: maintenance.php

### Settings ###

Legacy API Enabled: –
Force SSL: –
Currency: ZAR (R)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
pw gift card (pw-gift-card)
simple (simple)
variable (variable)
woosb (woosb)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 142 KB

### WC Pages ###

Shop base: #27 - /shop/
Basket: #28 - /basket/ -  Contains the woocommerce/cart block
Checkout: #29 - /checkout/ -  Contains the [woocommerce_checkout] shortcode
My account: #30 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront Blank Child Theme
Version: 1.0
Author URL: http://www.pootlepress.com
Child Theme: ✔
Parent Theme Name: Storefront
Parent Theme Version: 4.6.0
Parent Theme Author URL: https://woocommerce.com/
Theme type: Classic theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
onboarding
onboarding-tasks
pattern-toolkit-full-composability
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
printful
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page
launch-your-store

Disabled Features: product-data-views
experimental-blocks
coming-soon-newsletter-template
minified-js
product-pre-publish-modal
settings
async-product-editor-category-field
product-editor-template-system
blueprint
reactify-classic-payments-settings
use-wp-horizon
add-to-cart-with-options-stepper-layout

Daily Cron: ✔ Next scheduled: 2024-12-31 13:51:18 +02:00
Options: ✔
Notes: 20
Onboarding: completed

### Action Scheduler ###

Canceled: 69
Oldest: 2024-12-05 13:28:29 +0200
Newest: 2024-12-26 07:26:45 +0200

Complete: 31,035
Oldest: 2024-12-05 07:20:49 +0200
Newest: 2024-12-30 16:01:51 +0200

Failed: 37
Oldest: 2020-06-27 01:15:26 +0200
Newest: 2024-12-29 10:54:51 +0200

Pending: 8
Oldest: 2024-12-30 16:02:51 +0200
Newest: 2025-01-20 02:54:20 +0200


### Status report information ###

Generated at: 2024-12-30 16:02:36 +02:00
```
</details>

### Isolating the problem

- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by imanish003**
### Changes proposed in this Pull Request:

In WooCommerce 9.5, PR #50183 changed the "Clear" button on single product pages for variable products from an `<a>` tag to a `<button>` tag. While this improved accessibility, it is causing (widespread) visual issues, the Clear button now appears more prominent than the Add to Cart button. After internal discussion on Slack (p1736320650381359-slack-C02FL3X7KR6), it was decided to change the Clear button back to an `<a>` tag.

In summary:
- Replaced `<button>` tag with `<a>` tag and added `role="button"` for accessibility.
- Added keyboard event handling (Enter/Space) to match button behavior i.e. user will be able to use Enter or Space to clear the selection.
- Most of changes made in PR #50183 are preserved. For example, clearing attribute values will add a screen reader text "Your selection has been reset. Please select some product options before adding this product to your cart."

image

It was also raised on woo-dev slack channel (p1736165110941609-slack-C7U3Y3VMY).

Closes #54085

#### Verify that the "Clear" button is an `<a>` tag

1. Go to frontend of any variable product. For example, Hoodie (in case you are using sample products)
2. Select some variation attributes. For example, select "Red" for "Color".
3. Verify that the "Clear" button is an `<a>` tag. See before vs this PR screenshot below.
image

#### Scenario: Testing for regression

> [!NOTE]
> This PR reverts the change from PR #50183 that converted the "Clear" link from an `<a>` tag back to a `<button>` tag. We need to verify that this reversion maintains the same functionality and accessibility improvements that were introduced in #50183.

1. Activate screen reader of your choice.
	- Tip: You can use shortcut “Cmd + F5” to enable VoiceOver on Mac.
2. Go to frontend of any variable product. For example, Hoodie (in case you are using sample products)
3. Tab to variation attributes, use your arrows and space bar to make a selection. For example, select "Red" for "Color".
4. Tab to the "Clear" button.
5. Verify that you can use either Enter or Spacebar to clear the selection.
6. Verify that you hear a message "Your selection has been reset. Please select some product options before adding this product to your cart."

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [x] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 
Fix: Revert "Clear" Button from <button> to <a> Tag for Improved Theme Compatibility while maintaining accessibility improvements

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

**Comment by imanish003** [comment]
@roykho @samueljseay JFYI I've assigned you both as reviewers on the new PR #54320, as I needed to close the previous one (see [comment](https://github.com/woocommerce/woocommerce/pull/54309#issuecomment-2580033199)).

File: plugins/woocommerce/client/legacy/js/frontend/add-to-cart-variation.js [hunk 1]
```diff
@@ -603,6 +606,16 @@
 			.slideDown( 200 );
 	};
 
+	/**
+	 * Handle reset key down event for accessibility.
+	 */
+	VariationForm.prototype.onResetKeyDown = function ( event ) {
+		if ( event.keyCode === 32 || event.keyCode === 13 ) {
```
Comment (roykho) [inline plugins/woocommerce/client/legacy/js/frontend/add-to-cart-variation.js]: I would change this to using the `code` property instead `if ( event.code === 'Enter' || event.code === 'Space' ) {`

**Review by roykho — CHANGES_REQUESTED** [review]
I left a comment.

Also do we not need any `aria-label` for the clear link? Another thing I observed is that right after you clear the link with voice over on, you first hear the "select options..." message first before you hear the "clear..." message. Is that expected?

File: plugins/woocommerce/client/legacy/js/frontend/add-to-cart-variation.js (hunk 1 above)
Comment (imanish003) [reply plugins/woocommerce/client/legacy/js/frontend/add-to-cart-variation.js]: Good point. I'll update the PR to use `event.code`.

**Comment by imanish003** [comment]
Hi @roykho, Thank you for your thorough review. You've raised some important points.

> Also do we not need any aria-label for the clear link?

Good eyes! It makes sense to also add `aria-label` to provide better context for screen reader users, changing from just "Clear" to "Clear options". I have made the changes.

> Another thing I observed is that right after you clear the link with voice over on, you first hear the "select options..." message first before you hear the "clear..." message. Is that expected?

After investigating the [code](https://github.com/woocommerce/woocommerce/blob/d02020dcc8a81075ec362a956bf336217b5af880/plugins/woocommerce/client/legacy/js/frontend/add-to-cart-variation.js#L62-L71), I found that this behavior occurs because `announce_reset` is called after updating the attribute field values. I attempted to resolve it by moving `announce_reset` before the change event trigger, but the issue persisted. While this warrants further investigation, I don't believe we should block this CFE since this is existing behavior rather than a regression. What are your thoughts on proceeding with the current changes? Maybe we can create a follow up issue to fix this?

---

I have addressed your feedback. Can you please review the PR again?

File: plugins/woocommerce/templates/single-product/add-to-cart/variable.php [hunk 2]
```diff
@@ -45,7 +45,7 @@
 										'product'   => $product,
 									)
 								);
-								echo end( $attribute_keys ) === $attribute_name ? wp_kses_post( apply_filters( 'woocommerce_reset_variations_link', '<a class="reset_variations" href="#">' . esc_html__( 'Clear', 'woocommerce' ) . '</a>' ) ) : '';
+								echo end( $attribute_keys ) === $attribute_name ? wp_kses_post( apply_filters( 'woocommerce_reset_variations_link', '<a class="reset_variations" href="#" aria-label="' . esc_html__( 'Clear options', 'woocommerce' ) . '">' . esc_html__( 'Clear', 'woocommerce' ) . '</a>' ) ) : '';
```
Comment (roykho) [inline plugins/woocommerce/templates/single-product/add-to-cart/variable.php]: Because this is an attribute, we should use `esc_attr__()` instead.

**Review by roykho — CHANGES_REQUESTED** [review]
Thanks for making the changes. I found one small issue.

As for the voice over, yeah please create a separate issue for that.

**Comment by imanish003** [comment]
@roykho Good catch! I have replaced `esc_html__()` with `esc_attr__()` in for `aria-label` attribute. Can you please review the PR again?

PS: I'd appreciate it if we could merge this PR on Monday before the RC release to include it in testing.

CC: @kmanijak @tjcafferkey Could you please review and help merge this PR on Monday? Given the timezone differences with @roykho, waiting for his review may delay inclusion in Monday's release. Thanks! 🙂

**Review by roykho — APPROVED** [review]
Thanks for making the changes and great work! It looks good to me now.

✅ The HTML is now rendering an anchor tag with aria-label
✅ Using voiceover, it correctly announces the "Clear options" selection
✅ Using keyboard, I am able to clear the options with "Space" and "Enter" keys.
✅ After clearing the options, I can hear a message stating my options are cleared.

**Review by samueljseay — APPROVED** [review]
@roykho did a great job of the review on this and I don't have anything to add. I'm sorry I can't jump in and test this one, but had a look over the follow up changes and it looks good to me.

**Comment by kmanijak** [comment]
[CFE has been approved](https://github.com/woocommerce/woocommerce/issues/54310#issuecomment-2579980221). PR is approved twice, merging on behalf of Manish 🙌
