### PR TITLE
Clarify tax semantics in Orders REST API and add refund total_tax

### LINKED ISSUE #62846: Orders API endpoint: line_items totals are tax excluded while the main total is tax included
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

The order's main total is tax included but line_items total is as net. Both have "total_tax" which is the same value. Can we trust that it is like that in every setup?

So in the root there is `"cart_tax":"10.15","total":"49.96","total_tax":"10.15"`<br>And in the line_items there is `"subtotal":"39.81","subtotal_tax":"10.15","total":"39.81","total_tax":"10.15"`

The order returns with `"prices_include_tax":false`, which increases the confusion and doesn't seem to affect the values which the API returns (as noticed in [https://github.com/woocommerce/woocommerce/issues/17276](<https://github.com/woocommerce/woocommerce/issues/17276>) also)

In our tax settings we have:

* Prices entered with tax: "No, I will enter prices exclusive of tax"
* Display prices in the shop: Including tax
* Display prices during cart and checkout: Including tax
* Display tax totals: Itemized

Moreover, the orders API endpoint doesn't return refund amount tax separated, it is just marked as "total" and it is tax included, so calculating refund without tax from that is impossible in many scenarios: it is now just like: `"refunds":[{"id":33119,"reason":"","total":"-263.59"}],`

There is a previous discussion from many years ago, but it has been closed: [https://github.com/woocommerce/woocommerce/issues/17276](<https://github.com/woocommerce/woocommerce/issues/17276>)

To improve the situation without breaking old API requests, maybe it would be smart to just add new fields to the orders endpoint? Like total_net and total_gross.

### Expected behavior

* Values should be either gross or net (or both), for both order total and line_items totals.
* It would be good if the refunds would also include tax info, so the net refund could be calculated from that.
* If prices_include_tax true/false is returned with the orders, the totals should be also effected by that.

### Actual behavior

* The order's main total is tax included but the line_items totals don't include tax. Both have total_tax field also.
* Refunds returned via the orders endpoint don't include tax info at all and calculating net refund value is impossible
* The endpoint returns orders with boolean prices_include_tax, but actually it doesn't seem to affect the totals or other price fields at all.

### Steps to reproduce

* 

### WordPress Environment

* 

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](<https://woocommerce.com/products/storefront/>).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by kraftbj**
### Submission Review Guidelines:

- [x] I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
- [x] I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
- [x] I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
- [x] Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

The Orders REST API schema descriptions did not communicate whether totals include or exclude tax, causing confusion for integrators. The order-level `total` is tax-inclusive (grand total the customer paid), while `line_items[].total`, `shipping_lines[].total`, and `fee_lines[].total` are tax-exclusive (with tax broken out in `total_tax`). The existing descriptions were ambiguous or copy-pasted across contexts (e.g., shipping and fee totals both said "Line total (after discounts)").

Additionally, inline refund data only returned `total` (tax-inclusive) with no way to separate the net amount from tax, making it impossible for integrations to account for refunds at the tax level.

This PR:
1. Clarifies tax inclusion/exclusion in schema descriptions for order total, line items, shipping lines, fee lines, and refunds
2. Adds a `total_tax` field to inline refund data so API consumers can calculate net refund amounts
3. Fixes grammatically awkward `prices_include_tax` description

Closes #62846.

### How to test the changes in this Pull Request:

1. Create a WooCommerce store with tax enabled (e.g., 10% tax rate).
2. Create an order with line items, shipping, and fees.
3. Issue a partial refund on the order.
4. Fetch the order via the REST API: `GET /wp-json/wc/v3/orders/<id>`
5. Verify that:
   - The `refunds` array now includes a `total_tax` field alongside `total`.
   - The API schema (`OPTIONS /wp-json/wc/v3/orders`) shows updated descriptions:
     - Order `total`: "Grand total, including tax."
     - Line item `subtotal`: "Line subtotal, excluding tax (before discounts)."
     - Line item `total`: "Line total, excluding tax (after discounts)."
     - Shipping `total`: "Shipping total, excluding tax."
     - Fee `total`: "Fee total, excluding tax."
     - Refund `total`: "Refund total, including tax."
     - Refund `total_tax`: "Refund total tax."
     - `prices_include_tax`: "Whether prices included tax during checkout."

### Testing that has already taken place:

Code review against existing behavior and the V2 controller source. The change is documentation-only for existing fields plus one new read-only field (`total_tax` on refunds) that uses the same pattern as other `total_tax` fields in the response.

### Milestone

- [x] Automatically assign milestone for the **[next WooCommerce version](../blob/trunk/plugins/woocommerce/woocommerce.php#L6)**

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [x] Patch

#### Type

-   [x] Fix - Fixes an existing bug

#### Message
Clarify tax inclusion/exclusion in Orders REST API schema descriptions and add total_tax field to inline refund data.

</details>

### CODE REVIEW

File: plugins/woocommerce/includes/rest-api/Controllers/Version2/class-wc-rest-orders-v2-controller.php [hunk 1]
```diff
@@ -426,9 +426,10 @@ protected function get_formatted_item_data( $order ) {
 					$data['refunds'] = array();
 					foreach ( $order->get_refunds() as $refund ) {
 						$data['refunds'][] = array(
-							'id'     => $refund->get_id(),
-							'reason' => $refund->get_reason() ? $refund->get_reason() : '',
-							'total'  => '-' . wc_format_decimal( $refund->get_amount(), $this->request['dp'] ),
+							'id'        => $refund->get_id(),
+							'reason'    => $refund->get_reason() ? $refund->get_reason() : '',
+							'total'     => '-' . wc_format_decimal( $refund->get_amount(), $this->request['dp'] ),
+							'total_tax' => wc_format_decimal( (float) $refund->get_total_tax(), $this->request['dp'] ),
```
Comment (kalessil) [inline plugins/woocommerce/includes/rest-api/Controllers/Version2/class-wc-rest-orders-v2-controller.php:432]: This is a good addition. However, I recommend prefixing it with `-` for consistency (if `get_total_tax` returns positive number). This will ensure that the `total - total_tax` formula produces the expected results.

File: plugins/woocommerce/includes/rest-api/Controllers/Version2/class-wc-rest-orders-v2-controller.php [hunk 2]
```diff
@@ -1839,12 +1840,12 @@ public function get_item_schema() {
...
 							),
 							'total'      => array(
-								'description' => __( 'Line total (after discounts).', 'woocommerce' ),
+								'description' => __( 'Fee total, excluding tax.', 'woocommerce' ),
 								'type'        => 'string',
 								'context'     => array( 'view', 'edit' ),
 							),
 							'total_tax'  => array(
-								'description' => __( 'Line total tax (after discounts).', 'woocommerce' ),
+								'description' => __( 'Fee total tax.', 'woocommerce' ),
```
Comment (kalessil) [inline plugins/woocommerce/includes/rest-api/Controllers/Version2/class-wc-rest-orders-v2-controller.php:1848]: Thanks for correcting the copy-paste descriptions.

**Review by kalessil — CHANGES_REQUESTED** [review]
Looks good overall!

Please review my comments for further consideration. We should also resolve the duplicate changelog entries and add a test case for the new attribute to verify its correctness.

File: plugins/woocommerce/includes/rest-api/Controllers/Version2/class-wc-rest-orders-v2-controller.php (hunk 1 above)
Comment (kraftbj) [reply plugins/woocommerce/includes/rest-api/Controllers/Version2/class-wc-rest-orders-v2-controller.php:432]: Verified this against the refund creation flow. In \`wc_create_refund()\` (wc-order-functions.php), line item taxes are negated via \`wc_format_refund_total()\` before being set on the refund, and then \`calculate_totals()\` sums those negative tax values into \`total_tax\`. So \`get_total_tax()\` on a refund already returns a negative number.

Adding a \`-\` prefix here would double-negate it and produce a positive value, breaking the \`total - total_tax\` formula.

The \`total\` field is different — it uses \`get_amount()\` which returns the absolute refund amount, so it needs the manual \`-\` prefix. But \`get_total_tax()\` returns the raw (already negative) calculated value.

File: plugins/woocommerce/changelog/fix-62846-orders-api-tax-docs [hunk 3]
```diff
@@ -0,0 +1,5 @@
+Significance: patch
+Type: fix
+Comment: Clarify tax inclusion/exclusion in Orders REST API schema descriptions and add total_tax field to inline refund data.
+
+
```
[the remark this answers is not in the document]
Comment (kraftbj) [reply plugins/woocommerce/changelog/fix-62846-orders-api-tax-docs]: Fixed — removed the duplicate changelog file (`fix-62846-orders-api-tax-docs`), keeping only `63692-fix-order-api-tax-docs`.

File: plugins/woocommerce/includes/rest-api/Controllers/Version2/class-wc-rest-orders-v2-controller.php (hunk 1 above)
Comment (kalessil) [reply plugins/woocommerce/includes/rest-api/Controllers/Version2/class-wc-rest-orders-v2-controller.php:432]: Gotcha, thanks for verifying this!

**Review by kalessil — APPROVED** [review]
LGTM!

- I followed the testing instructions, and the functionality works as expected.
- The code changes are clear and logical.
