### PR TITLE
Set date paid for old orders

### LINKED ISSUE #13420: [2.7] Paid date not available even though order version is now 2.7+
## EXPLANATION OF THE ISSUE

In WC < 2.7, the `_paid_date` post meta value was not always set on an order. The order needed to have its `payment_complete()` method called in order for it to be set (and not all payment methods called this function).

In WC 2.7+, the paid date will be always be set. Thanks to #13382, the payment gateway doesn't need to call `WC_Order::payment_complete()` anymore :heart:.

This means that in the WC 2.7+ order data structure, **the paid date value for an order that has been paid will always reflect the date the order transitioned to the paid status**. However, if an order is saved with WC 2.7, and it was created < 2.7 and doesn't have a paid date set, the paid date data isn't updated properly even though the order's version is updated to 2.7+.

This is a minor issue and there is easy to work around in 3rd party code - if the paid date isn't set, use the order's creation date instead and check the order has a paid status. However, **because the order version and order's data are out-of-sync, it's still a bug**.

It's also a consequence of the issue I was talking about with #13381 where the order version is always incremented based on the assumption that all order data is updated to the latest version (it was actually the issue that originally lead to the report in #13381). In this case, the order data is not being updated completely. Specifically, the paid date isn't being set to a valid value (which would probably be the date created value), it's just being set to whatever the current value of the prop is, which will be the default value because the order was created in WC < 2.7 where this paid date wasn't set. The order version is being updated though signifying that the paid date _would_ be set if the order has been paid.

## STEPS TO REPRODUCE THE ISSUE
 
1. Place an order via checkout using WC < 2.7 and BACs as the payment method (because it doesn't call `WC_Order::payment_complete()`)
1. Change the order's status to _Complete_ to signify that it was paid
1. See that the `'_paid_date'` value in post meta is not set and does not have the date the order was paid
1. Upgrade the site to WC 2.7
1. Update something unrelated on the order, e.g. a total or address
1. Save the order
1. See that the `'_paid_date'` value in post meta is set, but does not have the date the order was paid
1. Repeat steps 1 & 2 with WC 2.7 active
1. See that the `'_paid_date'` value in post meta _is_ set and has the date the order was paid - this confirms that in the WC 2.7 order data structure, the paid date will be set for this type of order (#13382 also shows the code for this)

### PR DESCRIPTION
**Pull request by mikejolley**
If an order is old (<2.7) and has no date paid value set, and is also completed already, update the paid date to the order creation date so it’s not left blank.

Fixes #13420

### CODE REVIEW

**Comment by mikejolley** [comment]
@thenbrent

File: includes/data-stores/abstract-wc-order-data-store-cpt.php [hunk 1]
```diff
@@ -108,6 +108,14 @@ public function read( &$order ) {
 				$order->set_discount_total( (double) get_post_meta( $order->get_id(), '_cart_discount', true ) - (double) get_post_meta( $order->get_id(), '_cart_discount_tax', true ) );
 			}
 		}
+
+		/**
+		 * In older versions, paid date may not have been set.
+		 * @todo When/if meta is flattened, handle this in the migration script.
+		 */
+		if ( ! $order->get_version( 'edit' ) || version_compare( $order->get_version( 'edit' ), '2.7', '<' ) ) {
+			$order->maybe_set_date_paid( $order->get_date_created( 'edit' ) );
```
Comment (thenbrent) [inline includes/data-stores/abstract-wc-order-data-store-cpt.php]: I think this should check the order version and if there is no `date_paid` value set.

Otherwise, it will override any existing `date_paid` value based only on the order version. It's possible even if the order's version < 2.7 that the order has an existing and valid `date_paid` value set that is different to the `date_created`. In those cases, that value should be honoured.

**Comment by thenbrent** [comment]
@mikejolley looks good other than the one issue mentioned in https://github.com/woocommerce/woocommerce/pull/13444/files#r103988184

**Comment by claudiulodro** [comment]
Looks good to me. 👍

**Comment by mikejolley** [comment]
@thenbrent does my note above make sense?

File: includes/data-stores/abstract-wc-order-data-store-cpt.php (hunk 1 above)
Comment (thenbrent) [inline includes/data-stores/abstract-wc-order-data-store-cpt.php]: @mikejolley ah of course, that makes sense 👍
