### PR TITLE
Product Gallery: fix ghost overflow

### LINKED ISSUE #59810: Overflow-y on Product Gallery Block (beta) with vertical mode
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Using Product Gallery Block (beta and reinsered with WC 10.0.0) with product thumbnails below the product image shows a scrolling bar because overflow-y is used on class: `.is-vertical .wc-block-product-gallery-thumbnails .wc-block-product-gallery-thumbnails__scrollable`

I think we should apply on overflow property to cover all cases.

Bug found on several FSE websites.

### Expected behavior

Hidding scroll

### Actual behavior

Horizontal sroll is shown

### Steps to reproduce

Update to WC 10.0.0 and visit a single product page. Edit template, add again Product Gallery Block (beta) and save. The bug also appears without reinsertion.

### WordPress Environment

<details><summary>System Status Report</summary>

```
### WordPress Environment ###

WordPress address (URL): [Redacted]
Site address (URL): [Redacted]
WC Version: 10.0.2
Legacy REST API Package Version: The Legacy REST API plugin is not installed on this site.
Action Scheduler Version: ✔ 3.9.2
Log Directory Writable: ✔
WP Version: 6.8.2
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: –
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: Apache
Server Architecture: Linux 4.18.0-348.lve.el8.x86_64 x86_64
PHP Version: 8.3.22
PHP Post Max Size: 512 MB
PHP Time Limit: 360
PHP Max Input Vars: 250000
cURL Version: 8.14.1
OpenSSL/1.1.1w

SUHOSIN Installed: –
MySQL Version: 8.0.42
Max Upload Size: 32 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

[REDACTED]

### Post Type Counts ###

acf-field: 18
acf-field-group: 3
attachment: 2254
blockslider: 1
collection: 33
fgf_rules: 1
nav_menu_item: 24
oembed_cache: 39
page: 50
product: 278
revision: 1816
seopress_404: 13380
seopress_schemas: 1
shop_bogof_rule: 24
shop_coupon: 1
shop_order: 47
shop_order_placehold: 1
shop_order_refund: 1
store: 51
wp_block: 125
wp_global_styles: 3
wp_navigation: 19
wp_template: 15
wp_template_part: 44
yaymail_template: 76

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (59) ###

Admin Columns Pro: by AdminColumns.com – 6.4.20
Advanced Custom Fields PRO: by WP Engine – 6.3.11
APCu Manager: by Pierre Lannoy / PerfOps One – 4.2.1
BBQ Firewall: by Jeff Starr – 20250324
Block Visibility: by Nick Diego – 3.7.1
Carousel Slider Block for Gutenberg: by  – 1.0.10
Classic Menu Block: by Jonathan Harris – 0.1.7
Complianz | GDPR/CCPA Cookie Consent: by Really Simple Plugins – 7.4.1
Countdown: by GutenbergHub – 1.0.0
Disable Comments: by WPDeveloper – 2.5.2
Meta Field Block: by Phi Phan – 1.4.3
Yoast Duplicate Post: by Enrico Battocchi & Team Yoast – 4.5
Facebook for WooCommerce: by Facebook – 3.5.4
Google for WooCommerce: by WooCommerce – 3.1.1
Gravity Forms: by Gravity Forms – 2.9.13
Gravity Forms Mailchimp Add-On: by Gravity Forms – 5.7.0
Gravity SMTP: by Gravity Forms – 1.9.5
Accordion: by GutenbergHub – 1.0.0
Query Slider: by GutenbergHub – 1.2.1
Scroll Box: by GutenbergHub – 1.0.0
Imagify: by Imagify Image Optimizer – Optimize Images & Convert WebP & Avif – 2.2.6
Instagram Feed Pro Developer: by Smash Balloon – 6.8.1
Limit Login Attempts Reloaded: by Limit Login Attempts Reloaded – 2.26.19
Mailchimp for WooCommerce: by Mailchimp – 5.4
MainWP Child Reports: by MainWP – 2.2.6
MainWP Child: by MainWP – 5.4.0.11
Max Mega Menu - Pro Addon: by megamenu.com – 2.4.3
Max Mega Menu: by megamenu.com – 3.6.2
Permalink Manager Pro: by Maciej Bis – 2.5.1.2
Polylang Pro: by WP SYNTEX – 3.7.3
Polylang for WooCommerce: by WP SYNTEX – 2.1.4
Popup: by GutenbergHub – 1.1.0
Relevanssi Premium: by Mikko Saari – 2.27.0
Simple Cloudflare Turnstile: by Elliot Sowersby
RelyWP – 1.32.0

Simple Popup Block: by codemanas – 1.2.6
Swiss Post: by FirstPoint Sàrl – 2.3.1
Theme and plugin translation for Polylang (TTfP): by Marcin Kazmierski – 3.4.9
UpdraftPlus - Backup/Restore: by TeamUpdraft
DavidAnderson – 2.25.6.26

User Switching: by John Blackbourn – 1.9.2
WPC Custom Related Products for WooCommerce: by WPCodelibrary – 1.3.2
WooCommerce Buy One Get One Free: by Oscar Gare – 5.5.6
WooCommerce Customer/Order/Coupon Export: by SkyVerge – 5.5.3
WooCommerce Stripe Gateway: by Stripe – 9.6.0
WooCommerce Gift Checkout Block: by WP channel – 1.0.0
PDF Invoices & Packing Slips for WooCommerce: by WP Overnight – 4.5.2
PDF Invoices & Packing Slips for WooCommerce - Professional: by WP Overnight – 2.16.8
PDF Invoices & Packing Slips for WooCommerce - Premium Templates: by WP Overnight – 2.21.9
WooCommerce Shipment Tracking: by WooCommerce – 2.6.1
WooCommerce: by Automattic – 10.0.2
WP Grid Builder - Caching: by Loïc Blascos – 1.2.1
WP Grid Builder - Map Facet: by Loïc Blascos – 2.0.4
WP Grid Builder - Multilingual: by Loïc Blascos – 1.1.2
WP Grid Builder: by Loïc Blascos – 2.2.1
WP HTTP Blocklist: by Be API – 1.0.6
WP Rocket | Enforce Trailing Slash on URLs: by WP Rocket Support Team –
WP Rocket: by WP Media – 3.19.1.2
SEOPress PRO: by The SEO Guys at SEOPress – 8.9.0.1
SEOPress: by The SEO Guys at SEOPress – 8.9.0.2
YayMail Pro - WooCommerce Email Customizer: by YayCommerce – 4.0.8

### Inactive Plugins (0) ###


### Dropin Plugins () ###

advanced-cache.php: advanced-cache.php
db.php: Query Monitor Database Class (Drop-in)
object-cache.php: APCu Objects Cache Handler

### Must Use Plugins (4) ###

Back-Office Enhancements: by Aurélien Denis (WP channel) – 20230901
Custom WordPress Login: by Aurélien Denis (WP channel) – 20230901
Front-Office Enhancements: by Aurélien Denis (WP channel) – 20230901
Sanitize File Name: by Mickaël Gris (Saipafo) & Aurélien Denis (WP channel) – 20240103

### Settings ###

Legacy API Enabled: –
Force SSL: –
Currency: CHF (CHF)
Currency Position: left_space
Thousand Separator: '
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: ✔
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: ✔
Enabled Features: analytics
marketplace
order_attribution
site_visibility_badge
point_of_sale


### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 3 MB

### WC Pages ###

Shop base: #1737 - /shop/
Cart: #1140 - /cart/ -  This page's content is overridden by custom template content
Checkout: #1145 - /order/ -  This page's content is overridden by custom template content
My account: #1496 - /my-account/ -  Contains the [woocommerce_my_account] shortcode
Terms and conditions: #1724 - /terms-and-conditions/

### Theme ###

Name: La Colline (FSE)
Version: 20250721
Author URL: https://wpchannel.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
Theme type: Block theme
WooCommerce Support: ✔

### Templates ###

Overrides: /home/chlacolline/public_html/wp-content/plugins/woocommerce/templates/block-notices/error.php
/home/chlacolline/public_html/wp-content/plugins/woocommerce/templates/block-notices/notice.php
/home/chlacolline/public_html/wp-content/plugins/woocommerce/templates/block-notices/success.php
la-colline-fse/parts/checkout-header.html
la-colline-fse/parts/mini-cart.html
la-colline-fse/templates/archive-product.html
la-colline-fse/templates/order-confirmation.html
la-colline-fse/templates/page-cart.html
la-colline-fse/templates/page-checkout.html
la-colline-fse/templates/product-search-results.html
la-colline-fse/templates/single-product.html
la-colline-fse/templates/taxonomy-product_attribute.html
la-colline-fse/templates/taxonomy-product_cat.html
la-colline-fse/templates/taxonomy-product_tag.html


### WooCommerce Stripe Payment Gateway ###

Version: 9.6.0
Account ID: acct_1NEX4ZLtbI96p9CZ
Account Email: e.chappuy@lacolline-skincare.com
Test Mode Enabled: ✔
					No
OAuth Connected: ✔
					Yes
Legacy Checkout Experience: ✔
					No
Enabled Payment Methods: card
Express Checkout: ✔
					Enabled (checkout)
Auth and Capture: ✔
					Yes
Logging: No

### WC Pages Translations ###

Shop base: ✔
Cart: ✔
Checkout: ✔
My account: ✔
Terms and conditions: ✔

### Buy One Get One Free ###

Database version: 5.5.6
Legacy options: yes
Disable coupons: no
Custom attributes: no
Rule #28436: title: "2024 Code promo - SOMMERINTERLAKEN (copy) (de)"; type: "buy_a_get_b"; applies_to: " Product in  ( Illuminating Youth Cream (3051P) | Illuminating Youth Lotion (3052P) | Illuminating Youth Serum (3050P) | Le Métaprotecteur (3049P) ) "; action: "add_to_cart"; free_product_id: "3587"; gift_products: " Product in  ( Lip and Contour Remodelling Care (8050N) ) "; quantity_rules: "{"2":{"cart_quantity":2,"free_quantity":1,"discount_type":"percentage","discount":100,"cart_limit":1}}"; conditions: " Cart - Virtual coupon is CLAROINTERLAKEN "; start_date: "2024-09-30 00:00:00"; end_date: "2024-10-13 23:59:59"; exclude_other_rules: "1"; exclude_coupon_validation: "1"
Rule #28434: title: "2024 Code promo - CLAROINTERLAKEN"; type: "buy_a_get_b"; applies_to: " Product in  ( La Crème - Illuminating Youth Cream (3051P) | La Lotion - Illuminating Youth Lotion (3052P) | Le Sérum - Illuminating Youth Serum (3050P) | Le Métaprotecteur (3049P) ) "; action: "add_to_cart"; free_product_id: "293"; gift_products: " Product in  ( Lip and Contour Remodelling Care (8050N) ) "; quantity_rules: "{"2":{"cart_quantity":2,"free_quantity":1,"discount_type":"percentage","discount":100,"cart_limit":1}}"; conditions: " Cart - Virtual coupon is CLAROINTERLAKEN "; start_date: "2024-09-30 00:00:00"; end_date: "2024-10-13 23:59:59"; exclude_other_rules: "1"; exclude_coupon_validation: "1"
Rule #28435: title: "2024 Code promo - SOMMERINTERLAKEN (copy) (fr)"; type: "buy_a_get_b"; applies_to: " Product in  ( La Crème Illuminatrice Jeunesse (3051P) | La Lotion Illuminatrice Jeunesse (3052P) | Le Sérum Illuminateur Jeunesse (3050P) | Le Métaprotecteur (3049P) ) "; action: "add_to_cart"; free_product_id: "352"; gift_products: " Product in  ( Soin Remodelant Lèvres et Contours (8050N) ) "; quantity_rules: "{"2":{"cart_quantity":2,"free_quantity":1,"discount_type":"percentage","discount":100,"cart_limit":1}}"; conditions: " Cart - Virtual coupon is CLAROINTERLAKEN "; start_date: "2024-09-30 00:00:00"; end_date: "2024-10-13 23:59:59"; exclude_other_rules: "1"; exclude_coupon_validation: "1"
Rule #15728: title: "2024 Code promo - SOMMERINTERLAKEN (de)"; type: "buy_a_get_b"; applies_to: " Product in  ( Cellular Eco-Hydration Treatment (8086P) | Cellular Youth Hydration Balm (8082P) | Cellular Youth Hydration Cream (8080P) | Cellular Youth Hydration Serum (8083P) | Moisture Boost ++ Geschenkset (9060RS) ) "; action: "add_to_cart"; free_product_id: "4577"; gift_products: " Product in  ( Swiss Alps Cellular Mist (8085P) ) "; quantity_rules: "{"2":{"cart_quantity":2,"free_quantity":1,"discount_type":"percentage","discount":100,"cart_limit":1}}"; conditions: " Cart - Virtual coupon is SOMMERINTERLAKEN "; start_date: "2024-07-08 00:00:00"; end_date: "2024-07-21 23:59:59"; exclude_other_rules: "1"; exclude_coupon_validation: "1"
Rule #15727: title: "2024 Code promo - SOMMERINTERLAKEN (fr)"; type: "buy_a_get_b"; applies_to: " Product in  ( Traitement Cellulaire Eco-Hydratant (8086P) | Baume Cellulaire Hydratation Jeunesse (8082P) | Crème Cellulaire Hydratation Jeunesse (8080P) | Masque Cellulaire Hydratation Jeunesse (8784P) | Sérum Cellulaire Hydratation Jeunesse (8083P) | Moisture Boost ++ Coffret Cadeau (9060RS) ) "; action: "add_to_cart"; free_product_id: "305"; gift_products: " Product in  ( Brume Cellulaire des Alpes Suisses (8085P) ) "; quantity_rules: "{"2":{"cart_quantity":2,"free_quantity":1,"discount_type":"percentage","discount":100,"cart_limit":1}}"; conditions: " Cart - Virtual coupon is SOMMERINTERLAKEN "; start_date: "2024-07-08 00:00:00"; end_date: "2024-07-21 23:59:59"; exclude_other_rules: "1"; exclude_coupon_validation: "1"
Rule #15726: title: "2024 Code promo - SOMMERINTERLAKEN"; type: "buy_a_get_b"; applies_to: " Product in  ( Cellular Eco-Hydration Treatment (8086P) | Cellular Youth Hydration Balm (8082P) | Cellular Youth Hydration Cream (8080P) | Cellular Youth Hydration Mask (8784P) | Cellular Youth Hydration Serum (8083P) | Moisture Boost ++ Gift Set (9060RS) ) "; action: "add_to_cart"; free_product_id: "258"; gift_products: " Product in  ( Swiss Alps Cellular Mist (8085P) ) "; quantity_rules: "{"2":{"cart_quantity":2,"free_quantity":1,"discount_type":"percentage","discount":100,"cart_limit":1}}"; conditions: " Cart - Virtual coupon is SOMMERINTERLAKEN "; start_date: "2024-07-08 00:00:00"; end_date: "2024-07-21 23:59:59"; exclude_other_rules: "1"; exclude_coupon_validation: "1"
Rule #12145: title: "Palier 300 CHF - NativAge Gift Set (EN)"; type: "buy_a_get_b"; applies_to: " All Products "; action: "add_to_cart"; free_product_id: "4193"; gift_products: " Product in  ( NativAge Gift Set (8961GWP) ) "; quantity_rules: "{"1":{"cart_quantity":1,"free_quantity":1,"discount_type":"percentage","discount":100,"cart_limit":1}}"; conditions: " Cart - Subtotal (after discount coupons) greater_than 299 "; exclude_coupon_validation: "1"
Rule #12146: title: "Palier 300 CHF - NativAge Gift Set (FR)"; type: "buy_a_get_b"; applies_to: " All Products "; action: "add_to_cart"; free_product_id: "4202"; gift_products: " Product in  ( NativAge Coffret Cadeau (8961GWP) ) "; quantity_rules: "{"1":{"cart_quantity":1,"free_quantity":1,"discount_type":"percentage","discount":100,"cart_limit":1}}"; conditions: " Cart - Subtotal (after discount coupons) greater_than 299 "; exclude_coupon_validation: "1"
Rule #12147: title: "Palier 300 CHF - NativAge Gift Set (DE)"; type: "buy_a_get_b"; applies_to: " All Products "; action: "add_to_cart"; free_product_id: "6622"; gift_products: " Product in  ( NativAge Geschenkset (8961GWP) ) "; quantity_rules: "{"1":{"cart_quantity":1,"free_quantity":1,"discount_type":"percentage","discount":100,"cart_limit":1}}"; conditions: " Cart - Subtotal (after discount coupons) greater_than 299 "; exclude_coupon_validation: "1"
Rule #4620: title: "3 échantillons offerts au choix [EN]"; type: "buy_a_get_b"; applies_to: " All Products "; action: "choose_from"; gift_products: " Category in  ( Samples ) "; quantity_rules: "{"1":{"cart_quantity":1,"free_quantity":3,"discount_type":"percentage","discount":100,"cart_limit":3}}"; exclude_coupon_validation: "1"

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
onboarding
onboarding-tasks
pattern-toolkit-full-composability
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
printful
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page
launch-your-store
add-to-cart-with-options-stepper-layout

Disabled Features: product-data-views
experimental-blocks
experimental-iapi-mini-cart
experimental-iapi-runtime
coming-soon-newsletter-template
minified-js
product-pre-publish-modal
settings
async-product-editor-category-field
product-editor-template-system
use-wp-horizon

Daily Cron: ✔ Next scheduled: 2025-07-21 13:39:43 +02:00
Options: ✔
Notes: 55
Onboarding: skipped

### WooCommerce Customer/Order/Coupon Export ###

Automated exports: 1
Custom formats: 0
Next export: Scheduled on July 22
2025 11:07 am


### Action Scheduler ###

Complete: 3,639
Oldest: 2025-07-14 09:20:18 +0200
Newest: 2025-07-21 11:14:04 +0200

Failed: 72
Oldest: 2025-07-14 09:32:05 +0200
Newest: 2025-07-21 08:32:48 +0200

Pending: 12
Oldest: 2025-07-21 21:04:09 +0200
Newest: 2025-08-04 09:10:10 +0200


### Status report information ###

Generated at: 2025-07-21 11:16:45 +02:00
```
</details>

### Isolating the problem

- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by kmanijak**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

There's this interesting bug happening in Product Gallery Thumbails. There's a ghost scrollbar showing up under specific conditions:

image

It only appears under special conditions, in this case
- 4 images and default thumbnails size (25%)
- 3 images and thumbnails size 33%.

It would also appear with 5 images and thumbnails size 20%, etc. Basically, in such conditions, thumbnails actually overflow (but barely) and so the scrollbar appears. However scrollbar pushes the thumbnails from the bottom making them smaller and eventually NOT overflowing. And hence the scrollbar is there but empty!

This PR fixes it by checking if there's `ghost overflow` via iAPI, and if so make the scrollbar disappear. Keep in mind `scrollbar-gutter` which is designed for this purpose, unfortunately doesn't work well with horizontal scrollbar and flexbox like in this case hence programmatic approach.

Closes https://github.com/woocommerce/woocommerce/issues/59810

(For Bug Fixes) Bug introduced in PR # .

### Screenshots or screen recordings:

Below images of Product Galleries for
    - 2 Images product - no changes
    - 4 Images product - NO GHOST SCROLLBAR
    - 5 Images product - no changes

| Before | After |
| ------ | ----- |
|    image    |   image    |

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:
0. If needed create products with 2, 4 and 5 images.
1. Create new post
2. Insert 3 Product blocks and choose products you created:
    - 2 Images product
    - 4 Images product
    - 5 Images product
3. In each block Product block:
    - Replace Product Image with Product Gallery (Beta)
    - Change Product Gallery orientation so thumbnails become horizontal
4. Save and go to frontend
5. Expected:
    - 2 Images product - there's no scrollbar
    - 4 Images product - thumbnails overflow slightly but there's no scrollbar
    - 5 Images product - thumbnails overflow slightly and there is scrollbar

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce/src/Blocks/BlockTypes/ProductGalleryThumbnails.php [hunk 1]
```diff
@@ -81,7 +81,7 @@ class="wc-block-product-gallery-thumbnails <?php echo esc_attr( $classes_and_sty
 			data-wp-class--wc-block-product-gallery-thumbnails--overflow-right="context.thumbnailsOverflow.right">
 			<div
 				class="wc-block-product-gallery-thumbnails__scrollable"
-				data-wp-init="callbacks.initResizeObserver"
+				data-wp-init="callbacks.initScrollable"
```
Comment (dinhtungdu) [inline plugins/woocommerce/src/Blocks/BlockTypes/ProductGalleryThumbnails.php]: The `initScrollable` is only a wrapper for other callbacks. We can have multiple init callbacks attached to the same element.
```suggestion
				data-wp-init--resize="callbacks.initResizeObserver"
				data-wp-init--fix-ghost-overflow="callbacks.hideGhostOverflow"
```

**Review by dinhtungdu — CHANGES_REQUESTED** [review]
This is testing great on my end. I tested on Chrome and Firefox and confirmed that the ghost scrollbar is hidden. I only have a comment on the init callbacks. Otherwise, this is LGTM!


#### 🖼️ Screenshots/ screen recordings

Image

Image

#### 🌐 Site details
<details><summary>System Status Report</summary>

```
### WordPress Environment ###

WordPress address (URL): [Redacted]
Site address (URL): [Redacted]
WC Version: 10.2.0-dev
Legacy REST API Package Version: The Legacy REST API plugin is not installed on this site.
Action Scheduler Version: ✔ 3.9.3
Log Directory Writable: ✔
WP Version: 6.8.2
WP Multisite: –
WP Memory Limit: 2 GB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.25.4
Server Architecture: Darwin 24.6.0 arm64
PHP Version: 7.4.33
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 8.5.0
OpenSSL/3.1.4

SUHOSIN Installed: –
MySQL Version: 8.0.33
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

[REDACTED]

### Post Type Counts ###

attachment: 26
elementor_library: 1
global_product_addon: 1
page: 25
post: 3
product: 18
product_tab: 1
product_variation: 7
revision: 232
wp_font_face: 36
wp_font_family: 12
wp_global_styles: 5
wp_navigation: 1
wp_template: 9
wp_template_part: 8

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (2) ###

Laravel DD for Wordpress: by Peter Hegman – 1.0.1
WooCommerce: by Automattic – 10.2.0-dev

### Inactive Plugins (18) ###

Akismet Anti-spam: Spam Protection: by Automattic - Anti-spam Team – 5.3.6
bbPress: by The bbPress Contributors – 2.6.13
Block Hooks Experiments for WooCommerce: by Automattic –
Custom Product Tabs Manager: by Addify – 1.2.2
Elementor: by Elementor.com – 3.31.1
Elementor Pro: by Elementor.com – 3.30.0
Extra product options For WooCommerce | Custom Product Addons and Fields: by ThemeHigh – 3.3.2
Gutenberg: by Gutenberg Team – 20.7.0-rc.1
Hello Dolly: by Matt Mullenweg – 1.7.2
Product Filters for WooCommerce: by WooCommerce – 1.4.38
Query Monitor: by John Blackbourn – 3.17.2
What Can Wp Scripts Do: by The WordPress Contributors – 0.1.0
WooCommerce: by Automattic – 9.7.1 (update to version 10.0.4 is available)
WooCommerce Beta Tester: by WooCommerce – 3.0.0
WooCommerce PayPal Payments: by PayPal – 3.0.0 (update to version 3.0.9 is available)
WooCommerce Product Add-Ons: by Woo – 7.8.1 (update to version 7.9.2 is available)
WooPayments: by WooCommerce – 9.1.0 (update to version 9.7.0 is available)
WP BASIC Auth: by wokamoto – 1.1.4

### Must Use Plugins (1) ###

WooCommerce Product Details Extension Demo: by  – 1.0.0

### Settings ###

Legacy API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 1
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –
Enabled Features: analytics
marketplace
order_attribution
site_visibility_badge
remote_logging
email_improvements
point_of_sale
custom_order_tables


### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 2 MB

### WC Pages ###

Shop base: #7 - /shop/
Cart: #8 - /cart/ -  Contains the woocommerce/cart block
Checkout: #9 - /checkout/ -  Contains the woocommerce/checkout block
My account: #10 - /my-account/ -  Contains the [woocommerce_my_account] shortcode
Terms and conditions: ❌ Page not set

### Theme ###

Name: Assembler
Version: 0.0.46
Author URL: https://automattic.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
Theme type: Block theme
WooCommerce Support: ❌ Not declared

### Templates ###

Overrides: /Users/tung/workspace/woocommerce/plugins/woocommerce/templates/block-notices/error.php
/Users/tung/workspace/woocommerce/plugins/woocommerce/templates/block-notices/notice.php version 9.5.0 is out of date. The core version is 10.2.0
/Users/tung/workspace/woocommerce/plugins/woocommerce/templates/block-notices/success.php

Outdated Templates: ❌
					
					
						Learn how to update					 |
					
						
					
					
						Clear system status theme info cache

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
onboarding
onboarding-tasks
pattern-toolkit-full-composability
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
printful
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page
launch-your-store

Disabled Features: product-data-views
experimental-blocks
experimental-iapi-mini-cart
experimental-iapi-runtime
coming-soon-newsletter-template
minified-js
product-pre-publish-modal
settings
async-product-editor-category-field
product-editor-template-system
use-wp-horizon
experimental-wc-rest-api

Daily Cron: ✔ Next scheduled: 2025-08-13 10:10:56 +00:00
Options: ✔
Notes: 84
Onboarding: completed

### Action Scheduler ###

Complete: 128
Oldest: 2025-07-13 08:59:40 +0000
Newest: 2025-08-12 02:23:12 +0000

Failed: 4
Oldest: 2025-03-05 03:00:25 +0000
Newest: 2025-07-21 12:42:44 +0000

Pending: 3
Oldest: 2025-08-12 14:23:12 +0000
Newest: 2025-08-13 02:23:12 +0000


### Status report information ###

Generated at: 2025-08-12 10:57:53 +00:00
```
</details>

File: plugins/woocommerce/src/Blocks/BlockTypes/ProductGalleryThumbnails.php (hunk 1 above)
Comment (kmanijak) [reply plugins/woocommerce/src/Blocks/BlockTypes/ProductGalleryThumbnails.php]: > The initScrollable is only a wrapper for other callbacks. We can have multiple init callbacks attached to the same element.

Oh nice, I missed this!

I tried with something like this:

```
data-wp-init="callbacks.initResizeObserver"
data-wp-init="callbacks.hideGhostOverflow"
```

but I missed the part they have to be named! Cool tip, thanks!

Comment (kmanijak) [reply plugins/woocommerce/src/Blocks/BlockTypes/ProductGalleryThumbnails.php]: Addressed in https://github.com/woocommerce/woocommerce/pull/60274/commits/a772c6d519844df6a4d643a70b3fddc4f8a92ca5

**Review by dinhtungdu — APPROVED** [review]
Thanks for the update! Let's ship this!
