### PR TITLE
CYS - make the progress bar move forward in small segments 

### LINKED ISSUE #41231: [CYS] Make the progress bar move forward in small segments
p1698811547214709/1698803237.183139-slack-C01SFMVEYAK

Make the progress bar move forward in small segments like in NUX

https://github.com/woocommerce/woocommerce/assets/4344253/cd97f488-c14c-4831-8f41-bea76a6e4209

> @rjchow: we can add a prop [here](https://github.com/woocommerce/woocommerce/blob/1f625ca671d915551b45b4d42fd8dc86e5c2bbe4/packages/js/onboarding/src/components/Loader/Loader.tsx#L89) isSmoothProgress , then set a ref inside to track when the progress value has changed and smooth fill it forward/backward until it reaches the new value
I'm busy with the email validation code freeze exception though so I don't think I can fit it in today

### PR DESCRIPTION
**Pull request by moon0326**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes #41231 

- Duplicates the loader steps with incremented progress value to move the progress bar more often
- Applied transition to the progress bar

https://github.com/woocommerce/woocommerce/assets/4723145/59879c40-e988-4159-8cfc-2c35469014b4

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Create a new JN site with this branch and WooCommerce Beta Tester
2. Install and activate [woocommerce-blocks-trunk-nightly.zip](https://github.com/woocommerce/woocommerce-blocks/releases/download/nightly/woocommerce-blocks-trunk-nightly.zip)
3. Enable `customize-store` feature flag on Tools -> WCA Test Helper -> Features
4. Go to `WooCommerce -> Home` and start Cutomize your store task
5. Proceed to the Tone of Voice page and click Continue
6. You should see the updated API Loader

You can also run the storybook locally.

1. Checkout this branch locally
2. Run `pnpm --filter=@woocommerce/storybook run storybook`
3. Open the storybook once it's ready and choose `Application -> Customize Store -> Design with AI -> API Call Loader -> Api Call Loader Page with Smooth Transition`

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [x] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [x] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

Update the CYS task API loader smoother

#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce-admin/client/customize-store/design-with-ai/pages/ApiCallLoader.tsx [hunk 1]
```diff
@@ -113,22 +114,53 @@ export const ApiCallLoader = () => {
 		preload( openingTheDoors );
 	}, [] );
 
+	// Make the loader last longer and provide a smoother progress by duplicating the steps.
+	const augmentedSteps = loaderSteps
```
Comment (chihsuan) [inline plugins/woocommerce-admin/client/customize-store/design-with-ai/pages/ApiCallLoader.tsx]: Do you think it's possible to make this reusable? I wonder if we can pass a prop to enable this. 🤔

File: plugins/woocommerce-admin/client/customize-store/design-with-ai/pages/ApiCallLoader.tsx [hunk 2]
```diff
@@ -113,22 +114,53 @@ export const ApiCallLoader = () => {
...
 						<Loader.Illustration>
 							{ step.image }
 						</Loader.Illustration>
 						<Loader.Title>{ step.title }</Loader.Title>
-						<Loader.ProgressBar progress={ step.progress || 0 } />
 					</Loader.Layout>
 				) ) }
 			</Loader.Sequence>
+			<Loader.ProgressBar
+				className="smooth-transition"
```
Comment (chihsuan) [inline plugins/woocommerce-admin/client/customize-store/design-with-ai/pages/ApiCallLoader.tsx:176]: Can we also make `AssembleHubLoader` progress bar smooth?

**Review by chihsuan — APPROVED** [review]
Nice work! @moon0326 Looks good and tested well. 👍 

Left some comments but can address them as follow-ups.

**Review by ilyasfoo — APPROVED** [review]
Tests well! 🚢

File: plugins/woocommerce-admin/client/customize-store/design-with-ai/pages/ApiCallLoader.tsx (hunk 2 above)
Comment (chihsuan) [reply plugins/woocommerce-admin/client/customize-store/design-with-ai/pages/ApiCallLoader.tsx:176]: Updated in 5682ed691cbd202324b186f6bc14cfa5d10ba253

**Comment by chihsuan** [comment]
Merging this on behalf of @moon0326

File: plugins/woocommerce-admin/client/customize-store/design-with-ai/pages/ApiCallLoader.tsx (hunk 1 above)
Comment (moon0326) [reply plugins/woocommerce-admin/client/customize-store/design-with-ai/pages/ApiCallLoader.tsx]: @chihsuan I think we can make a function and provide it from the loader component. I'll work on it in a separate PR since this has been merged 👍

Comment (moon0326) [reply plugins/woocommerce-admin/client/customize-store/design-with-ai/pages/ApiCallLoader.tsx]: NVM 😄 I see you've already created it https://github.com/woocommerce/woocommerce/blob/426fa56dfce61fc16cd1441a93e7967c2ad54a17/plugins/woocommerce-admin/client/customize-store/design-with-ai/pages/ApiCallLoader.tsx#L102C7-L102C27

Nice!
