### PR TITLE
Fix duplicate product endpoint args for item schema 

### LINKED ISSUE #46535: API Rest endpoint to duplicate product is not duplicating stock management check
The [PR 46141](https://github.com/woocommerce/woocommerce/pull/46141) introduced a new API endpoint to duplicate a product. However, the [method product_duplicate](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/includes/admin/class-wc-admin-duplicate-product.php#L130) is not duplicating the stock management option.

### PR DESCRIPTION
**Pull request by octaedro**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

This PR fixes an error related to the duplicate product REST API endpoint. The method was working well but it did not duplicate the stock management option.

That was happening because we sent the wrong param to `get_endpoint_args_for_item_schema`.
This PR adds some unit tests and fixes the bug.

Product `type` and `status` are not editable.

Closes #46535.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Create a simple and a variable product and write down their IDs. In the case of the variable product, set a price for all the variations.
2. Install [this plugin](https://github.com/woocommerce/woocommerce/files/14885178/duplicate-product.zip) and activate it.
3. The plugin will show two buttons, `Duplicate` and `Duplicate and modify`. After pressing any of them, a prompt asking for a `Product ID` to duplicate will be visible. After adding a product ID and pressing ok, it will send a request to `/wp-json/wc/v3/products/[your-product-id]/duplicate`.
4. Open the browser's dev tools and go to the `Console` tab.
5. Press `Duplicate` and add the ID of the simple product to the prompt. If everything goes well you'll see the duplicated product printed in the console.
6. Verify that the new product has:
- A new ID
- The product's name says ` (Copy)` at the end
- The product status is `Draft`.

7. You can also go to `Products > All Products` and find the duplicated product there.
8. Repeat step 5 with the variable product ID.
9. Select the duplicated product from `Products > All Products`. Verify that the variations were duplicated correctly (the prices set in step 1 should match).
10. Now press `Duplicate and modify` and add the ID of the simple product to the prompt. If everything goes well you'll see the duplicated product printed in the console. This option also sends a description of the product, so the duplicated product's description should say: "This is my description".
11. Repeat step 10 with a variable product. 

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce/includes/rest-api/Controllers/Version3/class-wc-rest-products-controller.php [hunk 1]
```diff
@@ -99,10 +99,6 @@ public function duplicate_product( $request ) {
 			return new WP_Error( 'woocommerce_rest_product_invalid_id', __( 'Invalid product ID.', 'woocommerce' ), array( 'status' => 404 ) );
 		}
 
-		if ( 'simple' !== $product->get_type() ) {
```
Comment (octaedro) [inline plugins/woocommerce/includes/rest-api/Controllers/Version3/class-wc-rest-products-controller.php:102]: I removed this because it's not necessary anymore.

**Review by mdperez86 — APPROVED** [review]
LGTM @octaedro nice job!
