### PR TITLE
Fix navigation between variations and tab selection

### LINKED ISSUE #36237: Product variation tab is not initially shown when navigating to a variation
When navigating to a product variation, the `tab` is initially set to `options` so nothing is shown since this tab does not exist under variations.

### Screenshot

Image

### Testing

1. Create a product with a variation
2. Navigate to the new product experience `admin.php?page=wc-admin&path=/{product_id}`
3. Navigate to the variation by using the `edit` button under the variations section in the "Options" tab
4. Note that a blank screen is shown

### PR DESCRIPTION
**Pull request by joshuatf**
### All Submissions:

-   [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
-   [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
-   [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes the issue where the variations page does not load initially when clicking “Edit.”

Screen Shot 2022-12-30 at 7 20 46 AM

Closes #36237  .

- [ ] This PR is a very minor change/addition and does not require testing instructions (if checked you can ignore/remove the next section).

### How to test the changes in this Pull Request:

1. Create a product with some variations in the legacy experience
2. Navigate to the product in the new experience `admin.php?page=wc-admin&path=/{product_id}`
3. Click “Edit” on a variation
4. Make sure the “General” tab is loaded

### Other information:

-   [x] Have you added an explanation of what your changes do and why you'd like us to include them?
-   [ ] Have you written new tests for your changes, as applicable?
-   [x] Have you created a changelog file for each project being changed, ie `pnpm --filter=<project> changelog add`?

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

File: plugins/woocommerce-admin/client/products/product-variation-form.tsx [hunk 1]
```diff
@@ -50,7 +50,7 @@ export const ProductVariationForm: React.FC< {
 			ref={ formRef }
 		>
 			<ProductVariationFormHeader />
-			<ProductFormLayout>
+			<ProductFormLayout key={ productVariation.id }>
```
Comment (joshuatf) [inline plugins/woocommerce-admin/client/products/product-variation-form.tsx:53]: I think this might be the key to some of our update issues instead of calling `resetForm`.

**Review by octaedro — APPROVED** [review]
Nice job @joshuatf! The code looks good and is testing well on my end :shipit:
