### PR TITLE
Product Gallery block: Prevent page from scrolling when pop-up is open

### LINKED ISSUE #43343: Product Gallery block: Prevent page scrolling when pop-up is open
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When the Product Gallery Pop-up is open, and the mouse scroll is used, there is a scrolling effect appearing that should not occur.

### Expected behavior

The Product Gallery Pop-up should be confined to the page viewport and not extend beyond it.

### Actual behavior

Once the pop-up is open and the mouse is scrolled, a scrolling animation appears at the border of the browser.

https://github.com/woocommerce/woocommerce/assets/20469356/c240bbe0-5ddb-4763-a066-e87f93d23175

### Steps to reproduce

1. From your WordPress dashboard, go to Appearance > Themes. Make sure you have a block-based theme installed and activated. If not, you can install one from the Add New option. Block-based themes include "Twenty-twenty Three," "Twenty-twenty Four," etc.
2. On the left-hand side menu, click on Appearance > Editor > Templates
3. Find and select the 'Single Product' template from the list.
4. When the Classic Product Template renders, click on Transform into Blocks. This will transform the Classic template in a block template if you haven't done it before.
5. Inside the Page editor, click on the '+' button to add a new block.
6. In the block library that pops up, search for the 'Product Gallery' block. Click on it to add the block to the template.
7. Click on Save;
8. Visit a product page of a Variable Product;
9. Click on the Large Image;
10. When the pop-up appears scroll down the mouse and make sure you see the scroll bar appearing to the right side.

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): http://woo.local
Site address (URL): http://woo.local
WC Version: 8.6.0
REST API Version: ✔ 8.6.0
WC Blocks Version: ✔ 11.8.0-dev
Action Scheduler Version: ✔ 3.7.1
Log Directory Writable: ✔
WP Version: 6.4.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.16.0
PHP Version: 8.1.23
PHP Post Max Size: 1,000 MB
PHP Time Limit: 1200
PHP Max Input Vars: 4000
cURL Version: 8.4.0
(SecureTransport) LibreSSL/3.3.6

### Active Plugins (2) ###

WooCommerce Google Analytics Integration: by WooCommerce – 1.8.12
WooCommerce: by Automattic – 8.6.0-dev

### Theme ###

Name: Twenty Twenty-Four
Version: 1.0
Author URL: https://wordpress.org
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ❌ Not declared

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by thealexandrelara**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

- Added a new class to the body element that is only applied when the pop-up is open.
- Remove the class from the body element when the pop-up is closed.

Closes #43343 .

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. From your WordPress dashboard, go to Appearance > Themes. Make sure you have a block-based theme installed and activated. If not, you can install one from the Add New option. Block-based themes include "Twenty-twenty Three," "Twenty-twenty Four," etc.
2. On the left-hand side menu, click on Appearance > Editor > Templates
3. Find and select the 'Single Product' template from the list.
4. When the Classic Product Template renders, click on Transform into Blocks. This will transform the Classic template in a block template if you haven't done it before.
5. Inside the Page editor, click on the '+' button to add a new block.
6. In the block library that pops up, search for the 'Product Gallery' block. Click on it to add the block to the template.
7. Click on Save;
8. Visit a product page of a Variable Product;
9. Click on the Large Image;
10. When the pop-up appears scroll down the mouse and make sure you see the scroll bar does not appear to the right side.

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Comment 
Prevent page scrolling when the Product Gallery Pop-Up is open.

</details>

### CODE REVIEW

File: plugins/woocommerce-blocks/assets/js/blocks/product-gallery/frontend.tsx [hunk 1]
```diff
@@ -40,6 +40,7 @@ const closeDialog = ( context: ProductGalleryContext ) => {
 	context.isDialogOpen = false;
 	// Reset the main image.
 	context.selectedImage = context.firstMainImageId;
+	document.body.classList.remove( 'modal-open' );
```
Comment (roykho) [inline plugins/woocommerce-blocks/assets/js/blocks/product-gallery/frontend.tsx]: I wonder if it would be better to namespace this classname so that there is no chance of a conflict if some other extensions are doing the same. Perhaps `wc-block-product-gallery-modal-open`? WDYT?

Comment (samueljseay) [reply plugins/woocommerce-blocks/assets/js/blocks/product-gallery/frontend.tsx]: I agree it might be nice to namespace

Comment (thealexandrelara) [reply plugins/woocommerce-blocks/assets/js/blocks/product-gallery/frontend.tsx]: Great suggestion! Included in 56537ac52da08e0e8b37cf0e3353c71a75731dd3

File: plugins/woocommerce-blocks/assets/js/blocks/product-gallery/frontend.tsx [hunk 2]
```diff
@@ -60,6 +61,7 @@ const productGallery = {
 		openDialog: () => {
 			const context = getContext();
 			context.isDialogOpen = true;
+			document.body.classList.add( 'modal-open' );
```
Comment (roykho) [inline plugins/woocommerce-blocks/assets/js/blocks/product-gallery/frontend.tsx]: Missed one.

Comment (thealexandrelara) [reply plugins/woocommerce-blocks/assets/js/blocks/product-gallery/frontend.tsx]: Nice catch! I just fixed it in https://github.com/woocommerce/woocommerce/pull/43378/commits/94bca53f19d2587dc93621842133d2e29380abf4

**Review by roykho — APPROVED** [review]
Thanks for making the changes. I no longer see the scroll bar on popover good job!
