### PR TITLE
HPOS: Ensure refund meta data is saved correctly (alternative approach)

### LINKED ISSUE #39215: HPOS - Refund amount is missing in Woo API order refunds response payload and in data received via Webhooks if HPOS is enabled
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

The following info is missing in the response payload from Woo API GET `wp-json/wc/v3 /orders/<orderid>refund` if an order is refunded while HPOS is enabled: 
"amount": "0.00",
"refunded_by": 0,

The same scenario goes for data received via Webhooks.

If HPOS is disabled, everything works - values come correct and on time.

### Expected behavior

Refunds response values  when **HPOS enabled** via woo API GET `wp-json/wc/v3 /orders/<orderid>refund`
 
 "amount": "40.50", (expected amount while according to goods price on test shop)
  "refunded_by": 1,

### Actual behavior

Refunds response values  when **HPOS disabled** via woo API GET `wp-json/wc/v3 /orders/<orderid>refund`

"amount": "0.00",
"refunded_by": 0,

### Steps to reproduce

1. Create completed order;
2. Refund order;
3. Get refund data via Woo API GET `wp-json/wc/v3 /orders/<orderid>refund`
4. "amount" is 0.00
5. "refunded_by" is 0

### WordPress Environment

[SystemStatusReport_woo-e2e-test.omni-woo-test.com_2023-07-13T11-26-58.txt](https://github.com/woocommerce/woocommerce/files/12038819/SystemStatusReport_woo-e2e-test.omni-woo-test.com_2023-07-13T11-26-58.txt)

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by coreymckrill**
### Changes proposed in this Pull Request:

This is an alternative to #39466, as a way to ensure that refund meta data gets saved correctly. Instead of overriding the meta data setter methods, this approach sets the meta data directly in the `update_order_meta` method, using the recent (#39381) `get_metadata_by_key` data store method.

Pros:
* Avoids class overrides in the refund CRUD object.

Cons:
* Requires a small change to the save routine in the OrdersTableDataStore parent class, which could have unintended side effects (but hopefully not).
* Completely side steps the system in CRUD objects for managing meta data, which feels like it might create more technical debt than it actually mitigates.

Fixes #39215

### How to test the changes in this Pull Request:

The testing instructions in #39466 apply here as well.

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [x] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message

Ensure refund meta data is saved correctly when HPOS is enabled.

#### Comment

</details>

### CODE REVIEW

File: plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableDataStore.php [hunk 1]
```diff
@@ -2353,10 +2353,10 @@ protected function persist_save( &$order, bool $force_all_fields = false, $backf
 			$order->set_date_modified( current_time( 'mysql' ) );
 		}
 
-		$this->update_order_meta( $order );
-
 		$this->persist_order_to_db( $order, $force_all_fields );
 
+		$this->update_order_meta( $order );
```
Comment (vedanshujain) [inline plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableDataStore.php:2363]: accidental change?

File: plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableRefundDataStore.php [hunk 2]
```diff
@@ -159,8 +161,17 @@ public function update_order_meta( &$refund ) {
 
 		$props_to_update = $this->get_props_to_update( $refund, $meta_key_to_props );
 		foreach ( $props_to_update as $meta_key => $prop ) {
-			$value = $refund->{"get_$prop"}( 'edit' );
-			$refund->update_meta_data( $meta_key, $value );
+			$meta_object        = new WC_Meta_Data();
```
Comment (vedanshujain) [inline plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableRefundDataStore.php:164]: wdyt about adding a new method to datastore meta that gets metadata by key without having to pass a meta object?

File: plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableDataStore.php (hunk 1 above)
Comment (coreymckrill) [reply plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableDataStore.php:2363]: No, changing the order so that `update_order_meta` comes after `persist_order_to_db` is necessary so that the new refund object has an ID to attach the meta to. Otherwise the meta rows are generated but they have an `order_id` value of `0`.

File: plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableRefundDataStore.php (hunk 2 above)
Comment (coreymckrill) [reply plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableRefundDataStore.php:164]: We are kind of doing that below on line 167. I guess we could change the order so that we look for existing meta before generating a new one.

Or do you mean making it so that the `update_meta` and `add_meta` methods work without passing in a full meta object?

Comment (vedanshujain) [reply plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableRefundDataStore.php:164]: > Do you mean making it so that the update_meta and add_meta methods work without passing in a full meta object?

Yeah this, there have been asks from the community to have a lightweight way to update meta, but now that I think more about it, it probably needs more consideration. I think we are good to go here as that should be handled in a separate PR.

**Comment by vedanshujain** [comment]
@coreymckrill changes looks good to me, is this ready for review, or are you waiting on some more changes?

**Comment by coreymckrill** [comment]
@vedanshujain Thanks, marking this as ready for review. Still need to decide for sure if we want to go with this PR or with #39466

**Review by vedanshujain — APPROVED** [review]
LGTM! Let's merge post rebasing from trunk and CI passing.

**Comment by coreymckrill** [comment]
Failed e2e tests are running fine locally. It looks like there is a known flakiness problem with these two particular tests.
