### PR TITLE
Fix REST API coupon validation for percentage amounts over 100%

### LINKED ISSUE #60066: REST API: unexpected response when creating an invalid coupon
## **Describe the bug**

When sending a POST request to /wp-json/wc/v3/coupons, and the posted coupon amount is greater than 100%, the coupon is created with a zero value amount.

## **To Reproduce**

1. [Following these steps](https://woocommerce.github.io/woocommerce-rest-api-docs/#create-a-coupon), set up your Woo testing site to accept REST requests from cUrl or from your favorite REST request manager.
2. Send a POST request to `/wp-json/wc/v3/coupons`, with the following JSON body:

   ```postman_json
   {
     "code": "0035",
     "discount_type": "percent",
     "amount": "200",
     "individual_use": true,
     "exclude_sale_items": true
   }
   ```
3. The response will include `"amount": "0.00",` and the coupon will be created.

## **Expected behavior**

The endpoint should throw a validation error.

## Environment

Please fill out any of the below that applies

**Operating System/Device**

- [ ] Windows
- [ ] MacOS
- [ ] Linux
- [ ] iPhone
- [ ] Samsung
- [ ] Other (add in additional context field)

**Version:**

**Browser**

- [ ] Desktop Edge
- [ ] Desktop Chrome/Chromium
- [ ] Desktop Safari
- [ ] Mobile Edge
- [ ] Mobile Chrome/Chromium
- [ ] Mobile Safari
- [ ] Other (add in additional context field)

**Version:**

### PR DESCRIPTION
**Pull request by nerrad**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

This PR fixes a validation bug in the WooCommerce REST API where percentage coupons with amounts over 100% were being created with amount "0.00" instead of returning a proper validation error.

**Root Cause**: The validation logic was not executing in REST API requests before setting the property because `set_amount` was being executed before the discount type got set. 

**Solution**: 
3. **Explicitly set discount type before other props** - This ensures the existing validation in `WC_Coupon::set_amount` works as expected.
4. **Comprehensive tests** - Added test coverage for both valid and invalid scenarios (they were missing).

Closes #60066.

### How to test the changes in this Pull Request:

1. Set up WooCommerce with REST API access
2. Send a POST request to `/wp-json/wc/v3/coupons` with JSON body: `{"code": "invalid-test", "discount_type": "percent", "amount": "200"}`
3. Verify it returns 400 error with message "Percentage discount cannot exceed 100%." (before fix: would return 201 success with amount "0.00")

### Testing that has already taken place:

- **Unit Tests**: Added comprehensive test coverage for all validation scenarios
- **Manual Testing**: Verified all test cases work as expected
- **Backward Compatibility**: Ensured existing valid coupons continue to work
- **Performance**: No performance impact - validation occurs at object creation time

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.
-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message

Fix REST API coupon validation for percentage amounts over 100%. Resolves issue where percentage coupons with amounts > 100 were created with 0.00 amount instead of returning validation error.

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment

</details>

### CODE REVIEW

File: plugins/woocommerce/includes/rest-api/Controllers/Version2/class-wc-rest-coupons-v2-controller.php [hunk 1]
```diff
@@ -304,6 +313,13 @@ protected function prepare_object_for_database( $request, $creating = false ) {
 						break;
 					default:
 						if ( is_callable( array( $coupon, "set_{$key}" ) ) ) {
+							// Special validation for amount when discount_type is percent.
+							if ( 'amount' === $key && 'percent' === ( $request['discount_type'] ?? 'fixed_cart' ) ) {
+								$amount = wc_format_decimal( $value );
+								if ( $amount > 100 ) {
+									return new WP_Error( 'woocommerce_rest_invalid_coupon_amount', __( 'Percentage discount cannot exceed 100%.', 'woocommerce' ), array( 'status' => 400 ) );
+								}
+							}
```
Comment (nerrad) [inline plugins/woocommerce/includes/rest-api/Controllers/Version2/class-wc-rest-coupons-v2-controller.php]: This is where the main change was made (besides additional tests). The rest of the changes are from autoformatting fixes.

File: plugins/woocommerce/includes/rest-api/Controllers/Version2/class-wc-rest-coupons-v2-controller.php [hunk 2]
```diff
@@ -275,6 +286,11 @@ protected function prepare_object_for_database( $request, $creating = false ) {
 			return new WP_Error( 'woocommerce_rest_empty_coupon_code', sprintf( __( 'The coupon code cannot be empty.', 'woocommerce' ), 'code' ), array( 'status' => 400 ) );
 		}
 
+		// Handle setting discount type first because that is needed for validation.
+		if ( isset( $request['discount_type'] ) ) {
+			$coupon->set_discount_type( $request['discount_type'] );
+		}
```
Comment (nerrad) [inline plugins/woocommerce/includes/rest-api/Controllers/Version2/class-wc-rest-coupons-v2-controller.php:292]: This is the important relevant change for the fix (besides tests). The rest is from autoformatting.

Comment (roccotripaldi) [reply plugins/woocommerce/includes/rest-api/Controllers/Version2/class-wc-rest-coupons-v2-controller.php:292]: Great find!  In my brief exploration I had tried overriding `get_additional_fields` to add `discount_type`, but found no joy down that road. This is much better.

**Review by roccotripaldi — APPROVED** [review]
I've confirmed in local testing that this PR fixes the issue. I now get the expected error message when creating a coupon with a 200% discount via a REST request. I used Postman to send requests to a local site.

Screenshot 2025-07-29 at 7 33 05 AM

Additionally, I ran smoke tests on GET requests to `/wp-json/wc/v3/coupons/` and `/wp-json/wc/v3/coupons/$coupon_id` and saw no regressions.

And to be extra safe, I ran a few POST requests and saw no regressions. Here's what I POSTed:

"discount_type": "fixed_cart" and "amount": "0" ✅
"discount_type": "fixed_cart" and  "amount": "-1" ❌ should see validation error
"discount_type": "fixed_cart" and  "amount": "10" and "minimum_amount": "100" and "maximum_amount": "0" ✅
"discount_type": "fixed_cart" and  "amount": "10" and "minimum_amount": "100" ✅
"discount_type": "fixed_cart" and  "amount": "10" and "minimum_amount": "100" and "maximum_amount": "" ✅
"discount_type": "fixed_cart" and  "amount": "10" and "minimum_amount": "100" and "maximum_amount": "50" ❌ should see validation error
"discount_type": "fixed_cart" and  "amount": "10" and "minimum_amount": "100" and "maximum_amount": "500" ✅
"discount_type": "percent" and "amount": "200" ❌ should see validation error
"discount_type": "percent" and "amount": "100" ✅

**Comment by roccotripaldi** [comment]
Ooops. I accidently clicked the re-request review button. Please ignore.

**Comment by nerrad** [comment]
This is a bug fix that doesn't require a documentation update.
