### PR TITLE
Fix adding product variant to cart using `add-to-cart` parameter (#24000)

### LINKED ISSUE #24000: When adding a variation to cart using the "add-to-cart" URL parameter the attributes are not loaded
When adding a variation to cart using the "add-to-cart" URL parameter the attributes are not correctly loaded into the "variation" array on the cart item.

**To Reproduce**
1. Add a variation via the product screen
2. Add the same variation using its ID on the "add-to-cart" URL parameter

You get the variation doubled on the cart.

**Screenshots**
image

**Video**
https://cld.pt/dl/download/65164caa-e38e-4932-bac5-5461f34227d7/woocommerce-variation-add-to-cart-url.mov

**Cart item var_dump**
Added via the product page on the left and using the "add-to-cart" URL parameter on the right
image

**Expected behavior**
When using the "add-to-cart" the quantity should be increased instead of creating a new cart entry.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by jonathansadowski**
### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

* Update the `add_to_cart_handler_variable` form handler method such that when a variant `product_id` is supplied, the attributes for the variant are populated for the `add_to_cart` call.

Closes #24000.

### How to test the changes in this Pull Request:

1. Start with an empty cart.
1. Create a product variant and note its variant id.
1. Add that variant to the cart using the `add-to-cart` parameter.
1. Note that the quantity of that item in your cart is now 1.
1. From the parent product page, add the variant to the cart.
1. Note that the existing cart-item is updated and that its new quantity is 2. (Prior to this PR, a new cart-item was created, and both lines had individual quantities of 1).

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Using the `add-to-cart` parameter with a product variant id will now have the variation attributes populated correctly.

### CODE REVIEW

**Comment by peterfabian** [comment]
Btw I have a feeling this might also improve the situation for https://github.com/woocommerce/woocommerce/issues/16620.

File: includes/class-wc-form-handler.php [hunk 1]
```diff
@@ -904,6 +906,9 @@ private static function add_to_cart_handler_variable( $product_id ) {
 				}
 			}
 
+			// Merge variation attributes and posted attributes.
+			$posted_and_variation_attributes = array_merge( $posted_attributes, $variation_attributes );
```
Comment (peterfabian) [inline includes/class-wc-form-handler.php:910]: I'm not sure about the order of arrays here. 

In case all attributes are specified for a variation, then it makes sense to leave it as it is, since `$posted_attributes` could be (theoretically) incorrect.

On the other hand, there are variations that can have an attribute value set to `Any`. 
Screenshot 2020-04-22 at 13 34 11


Then `$posted_attributes` can theoretically further specify which option customer chose, e.g. via args `?add-to-cart=448&attribute_color=Black`. In that case, the extra attribute value would get lost, no?

File: tests/unit-tests/cart/cart.php [hunk 2]
```diff
@@ -2051,6 +2051,49 @@ public function test_rounding_with_fees_25629() {
...
+				'attribute_pa_colour'  => 'red',
+				'attribute_pa_number' => '2',
+			)
+		);
+
+		// Check that the second add to cart call increases the quantity of the existing cart-item.
+		$this->assertEquals( 1, count( WC()->cart->get_cart_contents() ) );
+		$this->assertEquals( 2, WC()->cart->get_cart_contents_count() );
+	}
+
```
Comment (peterfabian) [inline tests/unit-tests/cart/cart.php:2096]: Should we add a test case for variation with `Any` value as well?

**Review by peterfabian — CHANGES_REQUESTED** [review]
Nice work! 

It should work fine in the case where all the variations are fully specified, but not 100% when variation has attribute value set to `Any`.

File: includes/class-wc-form-handler.php (hunk 1 above)
Comment (jonathansadowski) [reply includes/class-wc-form-handler.php:910]: It doesn't appear the extra attribute value gets lost, because `$adding_to_cart->get_variation_attributes()` only returns attributes that are defined for the variation, in your screenshot, the size attribute. If color was specified via args, the `array_merge` should merge size and color keys into a single array, regardless of order.

I believe that the only case of something being lost would be if you specified size as an argument. For example, in your screenshot `?add-to-cart=448&attribute_pa_size=s&attribute_pa_color=green`, the `$posted_attributes` size would be lost and replaced with the attribute size from `$variation_attributes`. This would add the medium green shirt to the cart, ignoring `attribute_pa_size` in the args.

However, when I try to do that with a variation product id, for any attribute value other than the one belonging to the variation, I receive this error if I swap the order of the `array_merge` arguments (example `?add-to-cart=448&attribute_pa_size=s&attribute_pa_color=green`)

image

I think it's a matter of preference whether or not we display that error messages when you try to override an attribute belonging to the variation. Do you have a preference?

File: tests/unit-tests/cart/cart.php (hunk 2 above)
Comment (jonathansadowski) [reply tests/unit-tests/cart/cart.php:2096]: Thanks, great idea -- I'll add that test case.

File: includes/class-wc-form-handler.php (hunk 1 above)
Comment (jonathansadowski) [reply includes/class-wc-form-handler.php]: I ended up swapping the order and adding a check to test for the error message when attempting to override an attribute belonging to the variation.

Comment (peterfabian) [reply includes/class-wc-form-handler.php]: > because $adding_to_cart->get_variation_attributes() only returns attributes that are defined for the variation,

For me, `$adding_to_cart->get_variation_attributes()` returns empty string for unassigned variation:
Screenshot 2020-04-28 at 20 29 07

so I thought `array_merge($posted, $variation)` would replace `$posted` attribute with the empty string from `$variation`, e.g. when testing:

```
php > $posted = array('size' => 'm', 'color' => 'blue');
php > $variation = array('size' => '', 'color' => 'blue');
php > var_dump(array_merge($posted, $variation));
array(2) {
  ["size"]=>
  string(0) ""
  ["color"]=>
  string(4) "blue"
}
```

Thanks for updating, I think it behaves better now.

**Comment by peterfabian** [comment]
Just to understand the use cases here, trying it now once again:
- variation with 1 variation for each combination of attributes:
 -1 using `?add-to-cart=XX` works fine and picks up correct attribute values
 -2 using `?add-to-cart=XX&attribute_pa_size=m&attribute_color=green` works fine and picks up attribute values, so there will a qty of 2 items in cart, as expected
- variation with 1 attribute specified (as size in the example above) and 1 any attribute (as color in the above):
 -3 using `?add-to-cart=YY` adds to cart, but the product is not fully specified, as there is no value for color.
 -4 using `?add-to-cart=YY&attribute_pa_size=m&attribute_color=green` works fine and picks up correct attribute values
 -5 using `?add-to-cart=YY&attribute_color=green`, where size can be inferred from variation id (YY) works fine and adds quantity to correct product in cart

This seems almost correct, the only improvement is probably if case no 3 would return a notice saying this is not a valid product? What do you think?

**Comment by jonathansadowski** [comment]
> This seems almost correct, the only improvement is probably if case no 3 would return a notice saying this is not a valid product? What do you think?

Good catch. I'll get that notice added.

**Review by peterfabian — APPROVED** [review]
Thanks for the update. Great work! It seems that it's working fine now in all the cases. 

If this doesn't need any update on the REST API side, then we're good to merge, I think, so pre-approving.
