### PR TITLE
Issues/58990 blockified grouped products

### LINKED ISSUE #58990: Blockified Grouped Product: do not default to 1 and incorrect display when max=1
I was checking out the recent blockified add to cart with options for grouped products and I see 2 issues.

Image

1. The default value appears to be `1`. I think this is a UX problem as customers will have to go through and edit every product they do NOT want. The default should not be that all products are added to the cart.

And from my consultations with accessibility experts this is a major problem for users who rely on keyboard navigation. In fact, their recommendation to me was to start with a [null/empty input](https://github.com/woocommerce/woocommerce/blob/396263cd853833d5bce9afe00c9abc807d4ab2c6/plugins/woocommerce/templates/single-product/add-to-cart/grouped.php#L92), which is what is happening in the classic template. 

2. The "pineapple soda" product has 1 in stock. so `max = step`. At the moment, it just looks like a plus/minus button pair. in the source we see it's a hidden input, so what do those the plus/minus buttons do in this scenario? 

Image

Perhaps this should be a checkbox? sold individually items are a [checkbox](https://github.com/woocommerce/woocommerce/blob/396263cd853833d5bce9afe00c9abc807d4ab2c6/plugins/woocommerce/templates/single-product/add-to-cart/grouped.php#L66) in the classic template.

### PR DESCRIPTION
**Pull request by helgatheviking**
### Changes proposed in this Pull Request:

Grouped product quantity inputs start empty by default with a 0 placeholder.

Closes #58990 .

(For Bug Fixes) Bug introduced in #58002 .

### Screenshots or screen recordings:

After

image

### How to test the changes in this Pull Request:

Apply these changes and rebuild scripts. View a grouped product, the inputs should now be empty. And when the products are added to cart the add to cart button text will say "X in cart" where X is the number of the grouped products in the cart. 

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message

Blockified grouped product quantity inputs start empty by default with a 0 placeholder.

</details>

### CODE REVIEW

File: plugins/woocommerce/client/blocks/assets/js/atomic/blocks/product-elements/button/frontend.ts [hunk 1]
```diff
@@ -99,7 +99,11 @@ const productButtonStore = {
 					groupedProductIdsInCart?.some( ( qty ) => qty > 0 ) &&
 					hasPressedButton
 				) {
-					return state.inTheCartText;
+					const totalQuantity = groupedProductIdsInCart?.reduce((sum, qty) => sum + qty, 0) || 0;
+					return state.inTheCartText.replace(
+						'###',
+						totalQuantity.toString()
+					);
```
Comment (Aljullu) [inline plugins/woocommerce/client/blocks/assets/js/atomic/blocks/product-elements/button/frontend.ts]: For grouped products, we don't want to display the product count in the button as it might be misunderstood. "2 in cart" might be understood as there are two items of each child product in the cart.

For grouped products `state.inTheCartText`, [is `Added to cart`](https://github.com/woocommerce/woocommerce/blob/71504cc9ea047a52c7aa1c44c67f2b20b215be38/plugins/woocommerce/src/Blocks/BlockTypes/ProductButton.php#L347-L349).

So I would leave this as it was.

File: plugins/woocommerce/src/Blocks/BlockTypes/AddToCartWithOptions/GroupedProductItemSelector.php [hunk 2]
```diff
@@ -34,12 +34,34 @@ private function get_quantity_selector_markup( $product ) {
 		ob_start();
 
 		woocommerce_quantity_input(
-			array_merge(
-				AddToCartWithOptionsUtils::get_quantity_input_args( $product ),
```
Comment (Aljullu) [inline plugins/woocommerce/src/Blocks/BlockTypes/AddToCartWithOptions/GroupedProductItemSelector.php:38]: With this change, `AddToCartWithOptionsUtils::get_quantity_input_args()` will be only used in:

https://github.com/woocommerce/woocommerce/blob/71504cc9ea047a52c7aa1c44c67f2b20b215be38/plugins/woocommerce/src/Blocks/BlockTypes/AddToCartWithOptions/QuantitySelector.php#L72

It would be nice to inline the args there too, and get rid of the util method entirely.

(Not a blocker for this PR, though)

**Review by Aljullu — COMMENTED** [review]
Thanks a lot for reporting these issues and fixing them, @helgatheviking! :raised_hands: Confirming this PR:

1. Makes it possible to set the quantity selectors to 0 in grouped product children.
2. Fixes the display issue on products with only one in stock.

Before | After
--- | ---
imatge | imatge

I just left a comment below about the button text, that we should leave as-is.

Oh, and you will need to add a changelog entry with:

```
pnpm --filter='@woocommerce/plugin-woocommerce' changelog add
```

<details>
<summary>Testing environment</summary>

* WordPress 6.8.1 local dev environment
* Plugins: WooCommerce Beta Tester
* Theme: Woo Starter Theme
* Store creation: June 2025
* Store size: small
</details>

File: plugins/woocommerce/client/blocks/assets/js/atomic/blocks/product-elements/button/frontend.ts (hunk 1 above)
Comment (helgatheviking) [reply plugins/woocommerce/client/blocks/assets/js/atomic/blocks/product-elements/button/frontend.ts]: Leave it as "### in cart"? So hashtag hashtag in cart? or showing my age "pound pound in cart"? Neither was clear to me what that means... that's why I thought it was an oversight.

File: plugins/woocommerce/src/Blocks/BlockTypes/AddToCartWithOptions/GroupedProductItemSelector.php (hunk 2 above)
Comment (helgatheviking) [reply plugins/woocommerce/src/Blocks/BlockTypes/AddToCartWithOptions/GroupedProductItemSelector.php:38]: Do you want me to get rid of the util method? is it beta enough that we can do so? well now I see that it says it's for internal use only.

File: plugins/woocommerce/client/blocks/assets/js/atomic/blocks/product-elements/button/frontend.ts (hunk 1 above)
Comment (Aljullu) [reply plugins/woocommerce/client/blocks/assets/js/atomic/blocks/product-elements/button/frontend.ts]: That's weird, in grouped products you shouldn't see `### in cart`, instead, the text for grouped products is `Added to cart`:

https://github.com/user-attachments/assets/38489563-a5a9-4795-b166-46de44b57b6a

File: plugins/woocommerce/src/Blocks/BlockTypes/AddToCartWithOptions/GroupedProductItemSelector.php (hunk 2 above)
Comment (Aljullu) [reply plugins/woocommerce/src/Blocks/BlockTypes/AddToCartWithOptions/GroupedProductItemSelector.php:38]: Yes, `AddToCartWithOptionsUtils` is [marked as internal](https://github.com/woocommerce/woocommerce/blob/df79113484c55f5cf969e641625f843c87d247a5/plugins/woocommerce/src/Blocks/BlockTypes/AddToCartWithOptions/Utils.php#L11), so it should be fine to remove it. :slightly_smiling_face:

**Comment by helgatheviking** [comment]
Do the prompts to make a changelog from the github issue not work? If not, I would remove that from the template. Could the changelog command be _added_ to the issue template because I do not ever remember it. :sweat_smile: It's kind of a pain for outside contributors.

File: plugins/woocommerce/client/blocks/assets/js/atomic/blocks/product-elements/button/frontend.ts (hunk 1 above)
Comment (helgatheviking) [reply plugins/woocommerce/client/blocks/assets/js/atomic/blocks/product-elements/button/frontend.ts]: ok, "added to cart" makes a lot more sense, but this is what I was seeing:
image

Comment (helgatheviking) [reply plugins/woocommerce/client/blocks/assets/js/atomic/blocks/product-elements/button/frontend.ts]: Lines 99-100 are `true` for me and `state.inTheCartText` is `### in cart` 
```
if (
					groupedProductIdsInCart?.some( ( qty ) => qty > 0 ) &&
					hasPressedButton
				) {
				```

Comment (helgatheviking) [reply plugins/woocommerce/client/blocks/assets/js/atomic/blocks/product-elements/button/frontend.ts]: in slack you and i were just discussing context vs state, but for product button blocks wouldn't we need to use context as there can be more than 1 block on the page and [`wp_interactivity_state( 'woocommerce/product-button' )` will keep overwriting the `inTheCartText` parameter](https://github.com/woocommerce/woocommerce/blob/969313a488cd2fc1e960d456c92f0613ccddfd69/plugins/woocommerce/src/Blocks/BlockTypes/ProductButton.php#L101-L119)?

Comment (Aljullu) [reply plugins/woocommerce/client/blocks/assets/js/atomic/blocks/product-elements/button/frontend.ts]: Ah, you're right. That might be the issue. I was also able to reproduce what you mention:

1. Add two Single Product blocks into a post or page, one containing a grouped product and the next containing a simple product.
2. In the frontend, add the simple product into the cart.
3. Reload the page.
4. Add the grouped product into the cart.
5. `### in cart` appears on the button.

https://github.com/user-attachments/assets/2072c845-e604-426a-9619-1d0f0ab270af

And as you mention, I also think the issue is that we save `inTheCartText` in the global state instead of the local context.

I'm going to open a separate issue for that, I think it's better to fix it separately from this, how does it sound?

And once again, thanks for testing it and finding all these issues! :raised_hands:

Comment (Aljullu) [reply plugins/woocommerce/client/blocks/assets/js/atomic/blocks/product-elements/button/frontend.ts]: Issue created: https://github.com/woocommerce/woocommerce/issues/59032. :slightly_smiling_face:

**Comment by Aljullu** [comment]
> Do the prompts to make a changelog from the github issue not work? If not, I would remove that from the template. Could the changelog command be _added_ to the issue template because I do not ever remember it. :sweat_smile: It's kind of a pain for outside contributors. 

Wait, let me run the workflows, it might have been my mistake, I didn't let them run. :grimacing:

**Comment by Aljullu** [comment]
> Do the prompts to make a changelog from the github issue not work? If not, I would remove that from the template. Could the changelog command be _added_ to the issue template because I do not ever remember it. :sweat_smile: It's kind of a pain for outside contributors. 

Apparently, the issue was that there needs to be a `### Message` header before the changelog text. That job now passed, but now there are two changelog files. Will you be able to remove one, @helgatheviking?

Also, I didn't think about that, but we will need to update the [e2e test that checks that grouped products can be added to cart](https://github.com/woocommerce/woocommerce/blob/925471f41695ad832f9c0266cedcd06c8daea492/plugins/woocommerce/client/blocks/tests/e2e/tests/add-to-cart-with-options/add-to-cart-with-options.block_theme.spec.ts#L165-L190) making sure at lest one of the products quantity is not 0.

File: plugins/woocommerce/client/blocks/assets/js/atomic/blocks/product-elements/button/frontend.ts (hunk 1 above)
Comment (helgatheviking) [reply plugins/woocommerce/client/blocks/assets/js/atomic/blocks/product-elements/button/frontend.ts]: I reverted this change here. And sent the PR for the other issue. I think we can resolve this convo?

File: plugins/woocommerce/src/Blocks/BlockTypes/AddToCartWithOptions/GroupedProductItemSelector.php (hunk 2 above)
Comment (helgatheviking) [reply plugins/woocommerce/src/Blocks/BlockTypes/AddToCartWithOptions/GroupedProductItemSelector.php:38]: removed in [da01bd3](https://github.com/woocommerce/woocommerce/pull/58997/commits/da01bd3c291cf843c49e29b24aeabeddf96ace17)

**Comment by helgatheviking** [comment]
changelog removed. e2e tests are over my head. but that does make me think that a grouped product should have at least 1 quantity selected before you can click add to cart?

File: plugins/woocommerce/client/blocks/assets/js/atomic/blocks/product-elements/button/frontend.ts (hunk 1 above)
Comment (Aljullu) [reply plugins/woocommerce/client/blocks/assets/js/atomic/blocks/product-elements/button/frontend.ts]: Yes, thanks for splitting it, this way it's easier to review and merge! :slightly_smiling_face:

**Comment by Aljullu** [comment]
> but that does make me think that a grouped product should have at least 1 quantity selected before you can click add to cart?

Well, the issue will still be there because a shopper can still try to submit the form with all zeroes. :smile: 

I was thinking we could simply set [`isFormValid`](https://github.com/woocommerce/woocommerce/blob/1b0822887f8cb79b844cf594f59dc8fd11c62a18/plugins/woocommerce/client/blocks/assets/js/blocks/add-to-cart-with-options/frontend.ts#L149-L155) to false when all quantities are `0` and display a message if the user tries to click on the _Add to Cart Button_. But IMO this can be worked on in a follow-up.

**Review by Aljullu — APPROVED** [review]
Once again, thanks for your contribution, @helgatheviking! :raised_hands:  I updated the e2e tests. Testing is still working well, and it's possible to set grouped product children to `0` quantity or increase it as expected:

image

<details>
<summary>Testing environment</summary>

* WordPress 6.8.1 local dev environment
* Plugins: WooCommerce Beta Tester
* Theme: Woo Starter Theme
* Store creation: June 2025
* Store size: small
</details>
