### PR TITLE
Fixed: Draft post set as shop page causes trouble

### LINKED ISSUE #24136: Draft post set as shop page causes trouble
**Describe the bug**
ref: p9F6qB-3wL-p2

TL;DR: Setting draft page as a shop page causes weird effects. We can notify the user or add a warning to the system status report about this or solve this in some nice way?

### PR DESCRIPTION
**Pull request by Knyazevich**
Disallow a user to use draft pages as a Shop page to avoid weird behaviour it causes.

### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes #24136.

### How to test the changes in this Pull Request:

1. You should have at least one page with status "Draft";
2. Go to Woocommerce -> Settings -> Products;
3. Expand the "Shop page" select. You shouldn't see any drafts.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Tweak - Exclude draft pages from the "Shop page" setting.

### CODE REVIEW

**Comment by Knyazevich** [comment]
**To the reviewer:** I will be very appreciated if you add the `hacktoberfest-accepted` label to this PR in case if it looks ok generally for you :slightly_smiling_face:

File: includes/admin/settings/class-wc-settings-products.php [hunk 1]
```diff
@@ -304,6 +313,7 @@ public function get_settings( $current_section = '' ) {
 							'id'       => 'woocommerce_shop_page_id',
 							'type'     => 'single_select_page',
 							'default'  => '',
+							'args'     => array( 'exclude' => $draft_pages ),
```
Comment (claudiosanches) [inline includes/admin/settings/class-wc-settings-products.php:316]: Drafts are included using `post_type` in https://github.com/woocommerce/woocommerce/blob/3377c60c5e5602a4c82b6ef43b7b48b9c895f9ad/includes/admin/class-wc-admin-settings.php#L563

So should be easier to just include the types you like instead of querying all drafts and excluding it. 

```suggestion
							'args'     => array( 'post_status' => 'publish,private' ),
```

**Review by claudiosanches — CHANGES_REQUESTED** [review]
Thanks for your help, but there's better ways to solve it.

File: includes/admin/settings/class-wc-settings-products.php (hunk 1 above)
Comment (Knyazevich) [reply includes/admin/settings/class-wc-settings-products.php:316]: @claudiosanches 

Makes sense. Will fix it today.

**Review by claudiosanches — APPROVED** [review]
Thank you very much for your help!

Works great now.

> To the reviewer: I will be very appreciated if you add the hacktoberfest-accepted label to this PR in case if it looks ok generally to you slightly_smiling_face

Note that WooCommerce repositories uses the `hacktoberfest ` topic, so it's all ready for you :tada:
