### PR TITLE
Fix inconsistent behavior of net sales in analytics

### LINKED ISSUE #32837: Inconsistent behavior of Net Sales in Analytics
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Net Sales on the Analytics -> Products screen does not always equal Net Sales on the Analytics -> Revenue Screen

### Expected behavior

Expect that Net Sales on Products and on Revenue is the same value or follows an obvious and clear calculation rule

### Actual behavior

April 13: Net Sales is not the same on both pages

image
image

April 14: Net sales is the same on both pages

image
image

### Steps to reproduce

View Revenue page, view products page

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): [redacted]
Site address (URL): [redacted]
WC Version: 6.4.1
REST API Version: ✔ 6.4.1
WC Blocks Version: ✔ 7.2.2
Action Scheduler Version: ✔ 3.4.0
WC Admin Version: ✔ 3.3.2
Log Directory Writable: ✔
WP Version: 5.9.3
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: Apache
PHP Version: 7.4.28
PHP Post Max Size: 100 MB
PHP Time Limit: 3600
PHP Max Input Vars: 10000
cURL Version: 7.58.0
OpenSSL/1.1.1

SUHOSIN Installed: –
MySQL Version: 5.7.36-39-log
Max Upload Size: 50 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 6.4.1
WC Database Prefix: wp66_
Total Database Size: 1439.32MB
Database Data Size: 798.99MB
Database Index Size: 640.33MB
wp66_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp66_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp66_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp66_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp66_woocommerce_order_items: Data: 7.52MB + Index: 3.52MB + Engine InnoDB
wp66_woocommerce_order_itemmeta: Data: 54.59MB + Index: 48.14MB + Engine InnoDB
wp66_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp66_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp66_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp66_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp66_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp66_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp66_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp66_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp66_actionscheduler_actions: Data: 110.66MB + Index: 42.16MB + Engine InnoDB
wp66_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp66_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp66_actionscheduler_logs: Data: 33.56MB + Index: 27.06MB + Engine InnoDB
wp66_cf_forms: Data: 0.08MB + Index: 0.02MB + Engine InnoDB
wp66_cf_form_entries: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp66_cf_form_entry_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp66_cf_form_entry_values: Data: 0.16MB + Index: 0.14MB + Engine InnoDB
wp66_cf_pro_messages: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp66_cf_queue_failures: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp66_cf_queue_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp66_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp66_comments: Data: 61.59MB + Index: 46.09MB + Engine InnoDB
wp66_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp66_options: Data: 4.48MB + Index: 0.38MB + Engine InnoDB
wp66_postmeta: Data: 312.89MB + Index: 285.75MB + Engine InnoDB
wp66_posts: Data: 32.56MB + Index: 18.09MB + Engine InnoDB
wp66_revslider_css: Data: 0.14MB + Index: 0.02MB + Engine InnoDB
wp66_revslider_css_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp66_revslider_layer_animations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp66_revslider_layer_animations_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp66_revslider_navigations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp66_revslider_navigations_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp66_revslider_sliders: Data: 0.08MB + Index: 0.02MB + Engine InnoDB
wp66_revslider_sliders_bkp: Data: 0.09MB + Index: 0.00MB + Engine InnoDB
wp66_revslider_slides: Data: 0.50MB + Index: 0.02MB + Engine InnoDB
wp66_revslider_slides_bkp: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
wp66_revslider_static_slides: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp66_revslider_static_slides_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp66_shipment_batch_process: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp66_termmeta: Data: 0.09MB + Index: 0.14MB + Engine InnoDB
wp66_terms: Data: 1.52MB + Index: 3.03MB + Engine InnoDB
wp66_term_relationships: Data: 15.55MB + Index: 14.55MB + Engine InnoDB
wp66_term_taxonomy: Data: 1.52MB + Index: 2.02MB + Engine InnoDB
wp66_usermeta: Data: 8.52MB + Index: 6.03MB + Engine InnoDB
wp66_users: Data: 0.17MB + Index: 0.17MB + Engine InnoDB
wp66_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp66_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp66_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp66_wc_customer_lookup: Data: 0.19MB + Index: 0.13MB + Engine InnoDB
wp66_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp66_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp66_wc_order_product_lookup: Data: 8.52MB + Index: 9.06MB + Engine InnoDB
wp66_wc_order_stats: Data: 7.52MB + Index: 6.55MB + Engine InnoDB
wp66_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp66_wc_product_attributes_lookup: Data: 3.52MB + Index: 5.03MB + Engine InnoDB
wp66_wc_product_meta_lookup: Data: 2.52MB + Index: 3.42MB + Engine InnoDB
wp66_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp66_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp66_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp66_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp66_woo_shipment_status_email: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp66_woo_shippment_provider: Data: 0.09MB + Index: 0.00MB + Engine InnoDB
wp66_wsal_metadata: Data: 56.59MB + Index: 102.53MB + Engine InnoDB
wp66_wsal_occurrences: Data: 69.61MB + Index: 15.06MB + Engine InnoDB
wp66_wsal_sessions: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
wp66_yith_wcwl: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp66_yith_wcwl_lists: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_postmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_posts: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB

### Post Type Counts ###

attachment: 21911
clever_menu: 3
clever_menu_theme: 1
custom_css: 1
elementor_library: 1
frontslider: 1
motor_header: 7
motor_project: 46
nav_menu_item: 9
page: 13
post: 15
product: 16999
revision: 40
shop_order: 62938
shop_order_refund: 826
wp_block: 1
wp_global_styles: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 6.4.1

### Inactive Plugins (17) ###

Advanced Shipment Tracking for WooCommerce: by zorem – 3.3.2
Caldera Forms: by Caldera Forms – 1.9.7
Checkout Field Editor for WooCommerce (Pro): by ThemeHigh – 3.1.8
Clear Cart & Sessions for WooCommerce: by Puri.io – 1.5.2
Elementor: by Elementor.com – 3.6.5
FiboSearch - AJAX Search for WooCommerce: by FiboSearch Team – 1.17.0
Kirki Customizer Framework: by David Vongries – 4.0.23
LoginPress - Customizing the WordPress Login Screen.: by WPBrigade – 1.6.0
Motor Custom Types: by Stockware – 3.0.0
Restricted Site Access: by Jake Goldman
10up
Oomph – 7.3.0

Slider Revolution: by ThemePunch – 6.5.19
Software libraries for WP Activity Log: by WP White Security – 1.0.4
WooCommerce Min/Max Quantities: by WooCommerce – 2.4.23
WooCommerce Vehicle Parts Finder - Make/Model/Year/Engine/Category/Keyword: by The WP Instinct Team – 3.0
WP Activity Log (Premium): by WP White Security – 4.4.0
WP Activity Log for WooCommerce: by WP White Security – 1.4.2
WP Crontrol: by John Blackbourn & crontributors – 1.12.1

### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
object-cache.php: Memcached Redux

### Must Use Plugins (6) ###

Force Strong Passwords - WPE Edition: by Jason Cosper – 1.8.0
WPE ElasticPress Autosuggest Logger: by WP Engine – 1.0.0
WP Engine Cache Plugin: by WP Engine – 1.0.9
WP Engine Seamless Login Plugin: by WP Engine – 1.5.5
WP Engine Security Auditor: by wpengine – 1.0.10
WP Engine System: by WP Engine – 5.0.1

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #6 - /shop/
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Motor
Version: 3.0.0
Author URL: http://themeforest.net/user/stockware
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: motor/woocommerce/archive-product.php
motor/woocommerce/cart/cart-empty.php
motor/woocommerce/cart/cart-totals.php
motor/woocommerce/cart/cart.php
motor/woocommerce/cart/cross-sells.php
motor/woocommerce/content-product.php
motor/woocommerce/content-single-product.php
motor/woocommerce/global/quantity-input.php
motor/woocommerce/loop/add-to-cart.php
motor/woocommerce/loop/loop-end.php
motor/woocommerce/loop/loop-start.php
motor/woocommerce/loop/orderby.php
motor/woocommerce/loop/pagination.php
motor/woocommerce/myaccount/downloads.php
motor/woocommerce/myaccount/form-edit-account.php
motor/woocommerce/myaccount/form-edit-address.php
motor/woocommerce/myaccount/form-lost-password.php
motor/woocommerce/myaccount/form-reset-password.php
motor/woocommerce/myaccount/my-account.php
motor/woocommerce/myaccount/my-address.php
motor/woocommerce/myaccount/my-downloads.php
motor/woocommerce/myaccount/my-orders.php
motor/woocommerce/myaccount/navigation.php
motor/woocommerce/myaccount/orders.php
motor/woocommerce/myaccount/payment-methods.php
motor/woocommerce/myaccount/view-order.php
motor/woocommerce/single-product/add-to-cart/simple.php
motor/woocommerce/single-product/add-to-cart/variable.php version 3.5.5 is out of date. The core version is 6.1.0
motor/woocommerce/single-product/add-to-cart/variation-add-to-cart-button.php
motor/woocommerce/single-product/meta.php
motor/woocommerce/single-product/price.php
motor/woocommerce/single-product/product-attributes.php
motor/woocommerce/single-product/product-image.php
motor/woocommerce/single-product/related.php
motor/woocommerce/single-product/review.php
motor/woocommerce/single-product/short-description.php
motor/woocommerce/single-product/tabs/additional-information.php
motor/woocommerce/single-product/tabs/description.php
motor/woocommerce/single-product/tabs/tabs.php
motor/woocommerce/single-product/title.php
motor/woocommerce/single-product/up-sells.php
motor/woocommerce/single-product.php
motor/woocommerce/content-product_cat.php

Outdated Templates: ❌
					
					
						Learn how to update

### Action Scheduler ###

Complete: 150,799
Oldest: 2022-03-31 09:13:10 -0400
Newest: 2022-05-01 22:09:34 -0400

Failed: 47
Oldest: –
Newest: –

### Status report information ###

Generated at: 2022-05-01 22:10:14 -04:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by louwie17**
### Changes proposed in this Pull Request:

This is the re-introduction of https://github.com/woocommerce/woocommerce/pull/53019 with two main changes:
- Removal of the `get_total_shipping_tax_refunded` function introduced in the `WC_Order_Data_Store_Interface` and instead added the function to the abstract-wc-order-data-store-cpt.php class.
- Moved DB key update logic before `dbDelta( self::get_schema() )` is run, to prevent this error from happening:
```
WordPress database error Multiple primary key defined for query ALTER TABLE wp_wc_order_product_lookup ADD PRIMARY KEY  (`order_item_id`,`order_id`) made by require_once('wp-load.php'), require_once('wp-config.php'), require_once('wp-settings.php'), do_action('init'), WP_Hook->do_action, WP_Hook->apply_filters, WC_Install::check_version, WC_Install::install, WC_Install::install_core, WC_Install::create_tables, dbDelta
```

Closes https://github.com/woocommerce/woocommerce/issues/32837 https://github.com/woocommerce/woocommerce/issues/48761 https://github.com/woocommerce/woocommerce/issues/48775.

(For Bug Fixes) Bug introduced in PR # .

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

**Note: The refund order stuff should of already been tested as part of the [original PR](https://github.com/woocommerce/woocommerce/pull/53019) that was suppose to be release with 9.9, but got reverted because of the backwards compatibility issue with the interface changes**.

1. Before loading this branch make sure you have the latest WooCommerce installed and activated.
2. Double check with `phpMyAdmin` if the `wp_wc_order_product_lookup` has a single primary key ( `order_item_id` ).
3. Now load this branch ( or install it, you can generate a zip using: `pnpm --filter=@woocommerce/plugin-woocommerce build:zip` )
4. Check if the `wp_wc_order_product_lookup` has two primary keys now and check if there are **no** error logs.
5. Install & activate this plugin [custom-order-store.zip](https://github.com/user-attachments/files/20694955/custom-order-store.zip) which implements the `WC_Order_Data_Store_Interface` interface, and make sure no fatals happen when navigating around.
6. Now create several completed orders with a shipping amount and change the dates to something in the past
7. Refund and partial refund a couple of the orders ( partial refund can be done [this way](https://github.com/woocommerce/woocommerce/assets/1314156/0c5c5781-2a7d-4450-bedb-cf75d03de335) )
8. Go to **WooCommerce > Status > Scheduled Actions** and make sure there are only two ( or less ) pending actions.
9. Go to **Analytics > Revenue** and take note of the Net Sales
Screenshot 2025-06-11 at 14 08 30
10. Look at refunds, this should be the total refunded amount including the tax amount refunded ( this was different for full/partial refunds in the past )
11. If you created an order and selected a full refund the same day, then the Net sales and taxes should render zero for that day ( previously they didn't ).
12. Go to **Analytics > Orders** and **Analytics > Products** the Net sales amount should be the same as the Revenue one ( when comparing to products, you may need to subtract any fees from an order, the smooth generator adds this sometimes ).
13. Now change the date ranges around and compare the above two, they should stay the same.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce/includes/class-wc-install.php [hunk 1]
```diff
@@ -1574,6 +1576,12 @@ public static function create_tables() {
 			}
 		}
 
+		if ( $wpdb->get_var( "SHOW TABLES LIKE '{$wpdb->prefix}wc_order_product_lookup';" ) ) {
+			if ( 2 > $wpdb->get_var( "SELECT COUNT(*) FROM INFORMATION_SCHEMA.STATISTICS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = '{$wpdb->prefix}wc_order_product_lookup' AND INDEX_NAME = 'PRIMARY'" ) ) {
+				$result = $wpdb->query( "ALTER TABLE {$wpdb->prefix}wc_order_product_lookup DROP PRIMARY KEY, ADD PRIMARY KEY (order_item_id, order_id)" );
+			}
+		}
```
Comment (louwie17) [inline plugins/woocommerce/includes/class-wc-install.php:1558]: Moved here so it can run before `$db_delta_result = dbDelta( self::get_schema() );`

File: plugins/woocommerce/includes/wc-update-functions.php [hunk 2]
```diff
@@ -2993,6 +2993,58 @@ function wc_update_961_migrate_default_email_base_color() {
...
+			if ( empty( $order->get_items() ) ) {
+				$order->update_meta_data( '_refund_type', 'full' );
+				$order->save_meta_data();
+			}
+
+			/**
+			 * Trigger an action to schedule the data import for old refunded order items.
+			 *
+			 * @param int $order_id The ID of the order to be synced.
+			 * @since 9.9.0
```
Comment (chihsuan) [inline plugins/woocommerce/includes/wc-update-functions.php]:
```suggestion
			 * @since 10.0.0
```

File: plugins/woocommerce/includes/class-wc-install.php (hunk 1 above)
Comment (chihsuan) [reply plugins/woocommerce/includes/class-wc-install.php:1558]: If we moved this here, why do we still need `wc_update_1000_update_primary_key_to_composite_in_order_product_lookup_table` in db updates?

Additionally, it would be helpful to include some comments to explain why we add it here. 🙂

File: plugins/woocommerce/includes/class-wc-order.php [hunk 3]
```diff
@@ -2207,6 +2207,31 @@ public function get_total_tax_refunded() {
 		return $total_refunded;
 	}
 
+	/**
+	 * Get the total shipping tax refunded.
+	 *
+	 * @since  9.9.0
```
Comment (chihsuan) [inline plugins/woocommerce/includes/class-wc-order.php]:
```suggestion
	 * @since  10.0.0
```

File: plugins/woocommerce/includes/data-stores/abstract-wc-order-data-store-cpt.php [hunk 4]
```diff
@@ -805,4 +805,30 @@ protected function update_order_meta_from_object( $order ) {
 
 		$this->update_post_meta( $order );
 	}
+
+	/**
+	 * Get the total shipping tax refunded.
+	 *
+	 * @param  WC_Order $order Order object.
+	 *
+	 * @since 9.9.0
```
Comment (chihsuan) [inline plugins/woocommerce/includes/data-stores/abstract-wc-order-data-store-cpt.php]:
```suggestion
	 * @since 10.0.0
```

File: plugins/woocommerce/includes/data-stores/abstract-wc-order-data-store-cpt.php [hunk 5]
```diff
@@ -805,4 +805,30 @@ protected function update_order_meta_from_object( $order ) {
...
+			$wpdb->prepare(
+				"SELECT SUM( order_itemmeta.meta_value )
+				FROM {$wpdb->prefix}woocommerce_order_itemmeta AS order_itemmeta
+				INNER JOIN $wpdb->posts AS posts ON ( posts.post_type = 'shop_order_refund' AND posts.post_parent = %d )
+				INNER JOIN {$wpdb->prefix}woocommerce_order_items AS order_items ON ( order_items.order_id = posts.ID AND order_items.order_item_type = 'tax' )
+				WHERE order_itemmeta.order_item_id = order_items.order_item_id
+				AND order_itemmeta.meta_key = 'shipping_tax_amount'",
+				$order->get_id()
+			)
+		) ?? 0;
```
Comment (chihsuan) [inline plugins/woocommerce/includes/data-stores/abstract-wc-order-data-store-cpt.php:836]: Since we're using inner joins here, I think there is an opportunity to optimize the query for better performance.

Need to double-check, but here is the revised SQL query:

```sql
$total = $wpdb->get_var( 
    $wpdb->prepare( 
        "SELECT COALESCE(SUM(order_itemmeta.meta_value), 0) 
         FROM {$wpdb->prefix}woocommerce_order_items AS order_items
         INNER JOIN {$wpdb->prefix}woocommerce_order_itemmeta AS order_itemmeta 
            ON order_items.order_item_id = order_itemmeta.order_item_id
         INNER JOIN {$wpdb->posts} AS posts 
            ON order_items.order_id = posts.ID
         WHERE posts.post_type = 'shop_order_refund' 
           AND posts.post_parent = %d 
           AND order_items.order_item_type = 'tax'
           AND order_itemmeta.meta_key = 'shipping_tax_amount'
           AND order_itemmeta.meta_value IS NOT NULL", 
        $order->get_id() 
    ) 
);
```

 **Improvements Made**

1. Added COALESCE(SUM(...), 0) - handles NULL results in SQL
2. Reordered JOINs - start with order_items table first
3. Added IS NOT NULL - excludes NULL meta values from SUM
4. Moved conditions to WHERE - better performance than JOIN conditions

File: plugins/woocommerce/src/Admin/API/Reports/Orders/DataStore.php [hunk 6]
```diff
@@ -502,8 +502,9 @@ protected function get_products_by_order_ids( $order_ids ) {
 						ELSE product_id
 					END
 				)
-			WHERE
-				order_id IN ({$included_order_ids})
+			WHERE 1 = 1
```
Comment (chihsuan) [inline plugins/woocommerce/src/Admin/API/Reports/Orders/DataStore.php]: Could we remove `1 = 1`? It seems to be unnecessary.

File: plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableDataStore.php [hunk 7]
```diff
@@ -1048,6 +1049,36 @@ public function get_total_tax_refunded( $order ) {
...
+
+		return abs( $total );
+	}
+
+	/**
+	 * Get the total shipping tax refunded.
+	 *
+	 * @param WC_Order $order Order object.
+	 *
+	 * @since 9.9.0
```
Comment (chihsuan) [inline plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableDataStore.php]:
```suggestion
	 * @since 10.0.0
```

File: plugins/woocommerce/src/Admin/Overrides/OrderTraits.php [hunk 8]
```diff
@@ -16,20 +16,30 @@ trait OrderTraits {
...
+
 		if ( 0 === $order_items ) {
 			return 0;
 		}
 
-		$total_shipping_amount = (float) $this->get_shipping_total();
+		// Use the passed shipping_amount if provided, otherwise get the total shipping amount in the order.
+		// This is useful when calculating refunds for partial shipping in an order.
+		// For example, if $10 shipping is refunded from an order with $30 shipping, the remaining $20 should be distributed to the remaining items.
+		$total_shipping_amount = $shipping_amount ? $shipping_amount : (float) $this->get_shipping_total();
```
Comment (chihsuan) [inline plugins/woocommerce/src/Admin/Overrides/OrderTraits.php]: If $shipping_amount is 0, the method mistakenly uses the order’s shipping total. Should we use a null check instead, or check if it's numeric to avoid potential errors?

```php
$total_shipping_amount = null !== $shipping_amount
    ? $shipping_amount
    : (float) $this->get_shipping_total();
```

File: plugins/woocommerce/src/Admin/Overrides/OrderTraits.php [hunk 9]
```diff
@@ -42,29 +52,43 @@ public function get_item_shipping_amount( $item ) {
...
-		$line_items_shipping       = $this->get_items( 'shipping' );
-		$total_shipping_tax_amount = 0;
-		foreach ( $line_items_shipping as $item_id => $shipping_item ) {
-			$tax_data = $shipping_item->get_taxes();
-			if ( $tax_data ) {
-				foreach ( $order_taxes as $tax_item ) {
-					$tax_item_id                = $tax_item->get_rate_id();
-					$tax_item_total             = isset( $tax_data['total'][ $tax_item_id ] ) ? (float) $tax_data['total'][ $tax_item_id ] : 0;
-					$total_shipping_tax_amount += $tax_item_total;
+		// Use the passed shipping_tax_amount if provided, otherwise initiliase it to 0 and calculate the total shipping tax amount in the order.
```
Comment (chihsuan) [inline plugins/woocommerce/src/Admin/Overrides/OrderTraits.php]: typo

```suggestion
		// Use the passed shipping_tax_amount if provided, otherwise initialize it to 0 and calculate the total shipping tax amount in the order.
```

File: plugins/woocommerce/src/Admin/Overrides/OrderTraits.php [hunk 10]
```diff
@@ -16,20 +16,30 @@ trait OrderTraits {
...
+	public function get_item_shipping_amount( $item, $order_items_count = null, $shipping_amount = null ) {
 		// Shipping amount loosely based on woocommerce code in includes/admin/meta-boxes/views/html-order-item(s).php
 		// distributed simply based on number of line items.
 		$product_qty = $item->get_quantity( 'edit' );
-		$order_items = $this->get_item_count();
+
+		// Use the passed order_items_count if provided, otherwise get the total number of items in the order.
+		// This is useful when calculating refunds for partial items in an order.
+		// For example, if 2 items are refunded from an order with 4 items. The remaining 2 items should have the shipping fee of the refunded items distributed to them.
+		$order_items = $order_items_count ? $order_items_count : $this->get_item_count();
```
Comment (chihsuan) [inline plugins/woocommerce/src/Admin/Overrides/OrderTraits.php]: If $order_items_count is 0, the method mistakenly uses the get_item_count. Should we use a null check instead, or check if it's numeric to avoid potential errors?

File: plugins/woocommerce/src/Admin/Overrides/OrderTraits.php [hunk 11]
```diff
@@ -42,29 +52,43 @@ public function get_item_shipping_amount( $item ) {
...
 	 *
 	 * @return float|int
 	 */
-	public function get_item_shipping_tax_amount( $item ) {
-		$order_items = $this->get_item_count();
+	public function get_item_shipping_tax_amount( $item, $order_items_count = null, $shipping_tax_amount = null ) {
+		// Use the passed order_items_count if provided, otherwise get the total number of items in the order.
+		// This is useful when calculating refunds for partial items in an order.
+		// For example, if 2 items are refunded from an order with 4 items. The remaining 2 items should have the shipping tax of the refunded items distributed to them.
+		$order_items = $order_items_count ? $order_items_count : $this->get_item_count();
```
Comment (chihsuan) [inline plugins/woocommerce/src/Admin/Overrides/OrderTraits.php]: Same here.

File: plugins/woocommerce/src/Admin/API/Reports/Products/DataStore.php [hunk 12]
```diff
@@ -433,30 +467,126 @@ public static function sync_order_products( $order_id ) {
...
 		$round_tax      = 'no' === get_option( 'woocommerce_tax_round_at_subtotal' );
 
+		$is_full_refund_without_line_items = false;
+		$partial_refund_product_revenue    = array();
+		$refund_type                       = $order->get_meta( '_refund_type' );
+
+		$parent_order = null;
+
+		// When changing the order status to "Refunded", the refund order's type will be full refund, and the order items will be empty.
+		// We need to get the parent order items, and exclude the items that is already being patially refunded.
```
Comment (chihsuan) [inline plugins/woocommerce/src/Admin/API/Reports/Products/DataStore.php]: typo

```suggestion
		// We need to get the parent order items, and exclude the items that are already being partially refunded.
```

**Review by chihsuan — COMMENTED** [review]
Thank you for addressing this issue! 

I tested the branch and confirmed:

1. No errors in debug.log when updating from WC 9.9 and with the `custom-order-store` plugin installed.
2. Manually created orders and refunds are working as expected. The numbers in Analytics > Products are the same as in Analytics > Revenue.

However, I found that when I generated order vis `wc-smooth-generator` (without refound), the numbers in Analytics > Products are not the same as in Analytics > Revenue, or Orders. Do we know if this is expected?

https://github.com/user-attachments/assets/54b7e51c-3af5-48c8-bbc5-417ff270c367

I've also reviewed the code and left some comments.

**Comment by chihsuan** [comment]
I'll be testing it more tomorrow.

**Comment by chihsuan** [comment]
> However, I found that when I generated order vis wc-smooth-generator (without refound), the numbers in Analytics > Products are not the same as in Analytics > Revenue, or Orders. Do we know if this is expected?

~I've confirmed that this issue doesn't occur when using WooCommerce 9.9. The new order is somehow not reflected in Analytics.~


https://github.com/user-attachments/assets/76304c6a-fc5d-4e35-9e1a-eda1d8ba999a

False positives are because the WC smooth generator sometimes generates orders that are paid in the future.

Screenshot 2025-06-13 at 16 01 53

File: plugins/woocommerce/includes/wc-update-functions.php [hunk 13]
```diff
@@ -2993,6 +2993,58 @@ function wc_update_961_migrate_default_email_base_color() {
 	}
 }
 
+/**
+ * Add old refunded order items to the product_lookup_table.
+ */
+function wc_update_1000_add_old_refunded_order_items_to_product_lookup_table() {
+	global $wpdb;
+
+	// Get every order ID where:
```
Comment (chihsuan) [inline plugins/woocommerce/includes/wc-update-functions.php:3029]: Would it be worth testing this change in a large store to see if any performance issues arise? This could potentially affect query execution time and resource usage, as we will be retrieving all old refunded order items from the product lookup table.

**Comment by nerrad** [comment]
@louwie17 and @chihsuan, it looks like this got stalled, what are the plans here?

**Comment by louwie17** [comment]
> @louwie17 and @chihsuan, it looks like this got stalled, what are the plans here?

Yeah we are actually following back up on it after the discussion here: p6q6po-its-p2

File: plugins/woocommerce/includes/data-stores/abstract-wc-order-data-store-cpt.php (hunk 5 above)
Comment (louwie17) [reply plugins/woocommerce/includes/data-stores/abstract-wc-order-data-store-cpt.php:836]: Did you get a chance to test this? I just asked Cursor and it seemed to think that the current query implementation is more performant then this one, for the below reasons:

Current query is likely more performant because:
- Better JOIN order: Starting with order_itemmeta and filtering by meta_key = 'shipping_tax_amount' early reduces the dataset significantly before joining with other tables.
- Fewer conditions in WHERE: current has fewer WHERE conditions, which can be more efficient.
- Combined JOIN conditions: The combined JOIN conditions in current query can sometimes be optimized better by the query planner.

File: plugins/woocommerce/includes/class-wc-install.php (hunk 1 above)
Comment (louwie17) [reply plugins/woocommerce/includes/class-wc-install.php:1558]: Thanks, makes sense! I removed it.

File: plugins/woocommerce/includes/wc-update-functions.php (hunk 13 above)
Comment (louwie17) [reply plugins/woocommerce/includes/wc-update-functions.php:3029]: Yeah it did probably be worth testing, as I am looking at this logic, it also looks like this can probably be optimized quite a bit, as we are doing:
- Getting all the refunded order ids
- Then getting each order object individually ( triggering a query in behind )
- Checking if the order has line items ( this could be checked in the original query )
- Triggering a scheduled action for each refunded order ( this may not be as bad, as the scheduler will handle this ).

Comment (louwie17) [reply plugins/woocommerce/includes/wc-update-functions.php:3029]: So I did make a small update to this, so we only retrieve the entire order object if the `num_items_sold` is set to 0, this more accurately reflects a fully refunded order.
I don't anticipate the actual select query to be much of a bottleneck.

Plus this update function gets triggered in a cron job, same goes for the import calls, which in turn also gets badged if there is a bunch of them.

**Comment by louwie17** [comment]
@chihsuan this should be ready for review :)

File: plugins/woocommerce/includes/data-stores/abstract-wc-order-data-store-cpt.php (hunk 5 above)
Comment (chihsuan) [reply plugins/woocommerce/includes/data-stores/abstract-wc-order-data-store-cpt.php:836]: I just ran some tests, and both queries seem to have similar performance. This may be because MySQL’s optimizer is able to reorder joins. The current query works for me.

Screenshot 2025-08-20 at 11 35 54
Screenshot 2025-08-20 at 11 35 30

File: plugins/woocommerce/src/Admin/API/Reports/Products/DataStore.php [hunk 14]
```diff
@@ -437,30 +471,126 @@ public static function sync_order_products( $order_id ) {
...
+							ON order_stats.order_id = product_lookup.order_id
+						WHERE 1 = 1
+							AND order_stats.parent_id = %d
+							AND product_lookup.product_net_revenue < 0
+						GROUP BY product_lookup.product_id, product_lookup.variation_id
+					",
+					$table_name,
+					$parent_order_id
+				)
+			);
```
[the remark this answers is not in the document]
Comment (chihsuan) [reply plugins/woocommerce/src/Admin/API/Reports/Products/DataStore.php:512]: Since WordPress 6.2, `$wpdb->prepare()` does support %i as an identifier placeholder (for table/column names).

File: plugins/woocommerce/src/Admin/API/Reports/Products/DataStore.php [hunk 15]
```diff
@@ -112,6 +112,40 @@ protected function assign_report_columns() {
...
+	 * Add a refund type meta to the order.
+	 *
+	 * @param int    $refund_id Refund ID.
+	 * @param string $type      Refund type.
+	 */
+	public static function add_refund_type_meta( $refund_id, $type ) {
+		$order = wc_get_order( $refund_id );
+		$order->update_meta_data( '_refund_type', $type );
+		$order->save_meta_data();
 	}
```
[the remark this answers is not in the document]
Comment (chihsuan) [reply plugins/woocommerce/src/Admin/API/Reports/Products/DataStore.php:149]: Since this function is invoked by hooks, it's generally safe to assume the order exists.

File: plugins/woocommerce/src/Admin/Overrides/OrderTraits.php (hunk 10 above)
Comment (chihsuan) [reply plugins/woocommerce/src/Admin/Overrides/OrderTraits.php]: @louwie17 👋 What are your thoughts on this? Same as the comment below.

**Review by chihsuan — COMMENTED** [review]
I've tested this PR again on a fresh JN and confirmed that the analytics net sales calculations now work correctly across Revenue, Orders, and Products reports. 👍 

Only left two inline comments in the code regarding how zero values are handled. Instead of relying on truthy checks, I suggest we explicitly compare the value to null.

The unit tests seem to be failing due to the fix for full refound logic. I think it's an expected behavior and we should update expectations to reflect the new behavior, since we intentionally change how full refunds affect `num_items_sold`.

File: plugins/woocommerce/src/Admin/Overrides/OrderTraits.php (hunk 10 above)
Comment (louwie17) [reply plugins/woocommerce/src/Admin/Overrides/OrderTraits.php]: Ooops yeah, I thought I addressed them all, but missed these two, thanks :)

**Comment by louwie17** [comment]
Thanks for the review @chihsuan :)

> Only left two inline comments in the code regarding how zero values are handled. Instead of relying on truthy checks, I suggest we explicitly compare the value to null.

Thanks, I missed those prior, and addressed them this time!

> The unit tests seem to be failing due to the fix for full refound logic. I think it's an expected behavior and we should update expectations to reflect the new behavior, since we intentionally change how full refunds affect `num_items_sold`.

While looking at the tests, I realized a couple other things that didn't make sense. For example in the stats the `orders` count skips refunded orders, but the `avg_order_value` and `avg_items_per_order` does include them, but both of them only divide by non refunded orders.
So I updated the query in this commit: https://github.com/woocommerce/woocommerce/pull/58744/commits/f95e14e011c06e27f008f3c5a08465cf130487f8 and updated the tests accordingly.

Otherwise this would cause some weird stats like if you had one normal order on a single and 3 refunds, all with 2 products each ( 25$ each ), then some of the stats would look like:
Total orders: 1
Avg items per order: -5 ( ( 2 + -2 + -2 + -2 ) / 1 )
Avg Order Value: -150  ( ( 50 + -50 + -50 + -50 ) / 1 )
Now it should show:
Total orders: 1
Avg items per order: 2 ( ( 2 ) / 1 )
Avg Order Value: 50  ( ( 50 ) / 1 )

**Review by chihsuan — APPROVED** [review]
> While looking at the tests, I realized a couple other things that didn't make sense. For example in the stats the orders count skips refunded orders, but the avg_order_value and avg_items_per_order does include them, but both of them only divide by non refunded orders.
So I updated the query in this commit: https://github.com/woocommerce/woocommerce/commit/f95e14e011c06e27f008f3c5a08465cf130487f8 and updated the tests accordingly.

Looks good to me! Thanks for catching that inconsistency.

**Comment by louwie17** [comment]
@chihsuan apologies for asking again, but could you review this one more time? After talking with @rossanafmenezes we also addressed an issue around taxes and refunds.
I made two additions changes:
- For full refunds we also set the correct `tax_total` and `net_total` ( not including the tax ): https://github.com/woocommerce/woocommerce/pull/58744/commits/f6da4ef9b61e4fbc0de7ee1f883737fe527554d1 this was done correctly in the partial refunds
- Updated the refunds calculation to include the tax amount, this required a small change in the gross total as well: https://github.com/woocommerce/woocommerce/pull/58744/commits/4de35304cd3f46f439f3ded5f2826e51ebd7b20f
- Removed the full refund not being included tooltip https://github.com/woocommerce/woocommerce/pull/58744/commits/ddba17e7f31cc9126e98f92efabd8612f2834a00

This should fix all the issues in regards to full refunds I believe, and will also be relevant for Woo Analytics, since we rely on these tables.

**Review by chihsuan — COMMENTED** [review]
> * For full refunds we also set the correct `tax_total` and `net_total` ( not including the tax ): [f6da4ef](https://github.com/woocommerce/woocommerce/commit/f6da4ef9b61e4fbc0de7ee1f883737fe527554d1) this was done correctly in the partial refunds
> * Updated the refunds calculation to include the tax amount, this required a small change in the gross total as well: [4de3530](https://github.com/woocommerce/woocommerce/commit/4de35304cd3f46f439f3ded5f2826e51ebd7b20f)
> * Removed the full refund not being included tooltip [ddba17e](https://github.com/woocommerce/woocommerce/commit/ddba17e7f31cc9126e98f92efabd8612f2834a00)
> 
> This should fix all the issues in regards to full refunds I believe, and will also be relevant for Woo Analytics, since we rely on these tables.

Thank you for the explanation! @louwie17 It helps me understand the changes. :slightly_smiling_face:

I tested a full refund and noticed that the "Return" value in the report does not match the actual refunded amount. It's because shipping costs ($1.00) are not included. Should we also include shipping costs in refund calculations?

I full-refounded an order ($11.01 = $10.00 subtotal + $1.00 shipping + $0.01 tax).
Screenshot 2025-08-22 at 11 28 28

"Return" in the report is `$10.1` instead of `$11.01`:
Screenshot 2025-08-22 at 11 29 13

**Comment by louwie17** [comment]
> I tested a full refund and noticed that the "Return" value in the report does not match the actual refunded amount. It's because shipping costs ($1.00) are not included. Should we also include shipping costs in refund calculations?
> 
> I full-refounded an order ($11.01 = $10.00 subtotal + $1.00 shipping + $0.01 tax).

Thanks @chihsuan for the additional review, and catching the shipping costs refunds. That is a good suggestion and another item that the full refunds wasn't updating correctly.
I made three follow up changes:
- Update the import script so that the correct shipping total is set for full refunds ( this may require a trigger of DB update again to set the correct data ): https://github.com/woocommerce/woocommerce/pull/58744/commits/af2ed12a53b7e5b3a023d1bae8920004bef36ccc ( partial refunds did this correctly.
- Added `shipping_total` to the sum of the refunds query https://github.com/woocommerce/woocommerce/pull/58744/commits/5f95a8d472c0942ac9654fd477930a230530eef7
- Added a tooltip to the returns box to mention that it includes returned tax/shipping amounts ( as this was not explicit before ) https://github.com/woocommerce/woocommerce/pull/58744/commits/e87a74ff1e6c67e0ce317d382e45d23798d10cfe

**Review by chihsuan — APPROVED** [review]
> Update the import script so that the correct shipping total is set for full refunds ( this may require a trigger of DB update again to set the correct data ): https://github.com/woocommerce/woocommerce/commit/af2ed12a53b7e5b3a023d1bae8920004bef36ccc ( partial refunds did this correctly.
Added shipping_total to the sum of the refunds query https://github.com/woocommerce/woocommerce/commit/5f95a8d472c0942ac9654fd477930a230530eef7
Added a tooltip to the returns box to mention that it includes returned tax/shipping amounts ( as this was not explicit before ) https://github.com/woocommerce/woocommerce/commit/e87a74ff1e6c67e0ce317d382e45d23798d10cfe

Thanks for addressing this! @louwie17 Tested this locally and it looks good to me. 🎉

File: plugins/woocommerce/includes/class-wc-install.php (hunk 1 above)
Comment (Nikschavan) [reply plugins/woocommerce/includes/class-wc-install.php:1558]: Will adding it here will drop the index and re-create it for each WC update? On large stores with many product items sold the size of this table could be large and this can be an expensive operation

Comment (Nikschavan) [reply plugins/woocommerce/includes/class-wc-install.php:1558]: Never mind, I just realised we are indeed checking the number of columns for the primary key
