### PR TITLE
fix: block checkout local pickup fails to render

### LINKED ISSUE #62785: [Block Checkout] Local Pickup fails to render in certain scenarios
#### A clear and concise description of what the bug is.

Hi team,

In 10687337-zen, it was noted that the local tab doesn't display any options:

With the following error in console

Ref:[https://github.com/woocommerce/woocommerce/blob/5c42d25e0fa9227c70c12b9a11c709e4137275a0/plugins/woocommerce/client/blocks/assets/js/blocks/checkout/inner-blocks/checkout-pickup-options-block/block.tsx#L213C1-L229C6](https://github.com/woocommerce/woocommerce/blob/5c42d25e0fa9227c70c12b9a11c709e4137275a0/plugins/woocommerce/client/blocks/assets/js/blocks/checkout/inner-blocks/checkout-pickup-options-block/block.tsx#L213C1-L229C6)

```
                  m.ExperimentalOrderLocalPickupPackages,
                  {
                    children: (0, P.jsx) (
                      fe.G,
                      {
                        title: e[0].name,
                        selectedOption: null != r ? r : '',
                        renderPickupLocation: ye,
                        pickupLocations: o,
                        packageCount: (0, se.T4) (e),
                        onChange: e => i(e)
                      }
                    )
                  }
```

On investigation, it stood out that this might happen in a couple of scenarios. As an example - if store is required to have full address before displaying shipping and something else ends up calculating `calculate_totals` before Blocks inserts the `$preloaded_api_requests_script` - the value of shipping data will appear as follows

```
has_calculated_shipping":false,
"shipping_rates":[],"
```

Whereas it should be ideally below if at least one pickup option is available (regardless of the full address requirement)

```
has_calculated_shipping":true,
"shipping_rates":[
{
"package_id":0,
"name":"Shipment 1",
...
```

This is because within the calculate_shipping() method - the `public function show_shipping() {` returns false probably because of the wrong context here:

```
if ( 'shortcode' === $this->cart_context ) {
```

**To Replicate:**

* Store Address: US, sell and ship to all countries
* Customer location: Base country
* Shipping Zones > Add US > Flat Rate
* Local pick up > Enable > and add US address location
* Important: Enable `Hide shipping costs until an address is entered`
* Deploy the snippet below
* In a private browsing window, add item to cart, land on checkout page, and try switching to Local Pickup tab - no methods would be shown

```
add_action( 'wp_enqueue_scripts', function () {

	WC()->cart->calculate_totals();

}, 10 );  
```

On the site in Question, it was the PixelYourSite plugin doing this:

```
#0 /wp-2638511/wp-content/plugins/woocommerce/includes/class-wc-cart.php(1512): WC_Cart->show_shipping()
#1 /wp-2638511/wp-content/plugins/woocommerce/includes/class-wc-cart-totals.php(352): WC_Cart->calculate_shipping()
#2 /wp-2638511/wp-content/plugins/woocommerce/includes/class-wc-cart-totals.php(856): WC_Cart_Totals->get_shipping_from_cart()
#3 /wp-2638511/wp-content/plugins/woocommerce/includes/class-wc-cart-totals.php(148): WC_Cart_Totals->calculate_shipping_totals()
#4 /wp-2638511/wp-content/plugins/woocommerce/includes/class-wc-cart-totals.php(138): WC_Cart_Totals->calculate()
#5 /wp-2638511/wp-content/plugins/woocommerce/includes/class-wc-cart.php(1465): WC_Cart_Totals->__construct(Object(WC_Cart))
#6 /wp-2638511/wp-content/plugins/pixelyoursite/includes/functions-woo.php(99): WC_Cart->calculate_totals()
#7 /wp-2638511/wp-content/plugins/pixelyoursite/modules/facebook/function-helpers.php(444): PixelYourSite\getWooCartSubtotal()
#8 /wp-2638511/wp-content/plugins/pixelyoursite/modules/facebook/facebook.php(686): PixelYourSite\Facebook\Helpers\getWooCartParams('InitiateCheckou...')
#9 /wp-2638511/wp-content/plugins/pixelyoursite/modules/facebook/facebook.php(306): PixelYourSite\Facebook->getWooInitiateCheckoutEventParams()
#10 /wp-2638511/wp-content/plugins/pixelyoursite/modules/facebook/facebook.php(134): PixelYourSite\Facebook->addParamsToEvent(Object(PixelYourSite\SingleEvent))
#11 /wp-2638511/wp-content/plugins/pixelyoursite/includes/events/interface-events.php(40): PixelYourSite\Facebook->generateEvents(Object(PixelYourSite\SingleEvent))
#12 /wp-2638511/wp-content/plugins/pixelyoursite/includes/class-events-manager.php(243): PixelYourSite\EventsFactory->generateEvents()
#13 /wp-2638511/wp-includes/class-wp-hook.php(341): PixelYourSite\EventsManager->setupEventsParams('')
#14 /wp-2638511/wp-includes/class-wp-hook.php(365): WP_Hook->apply_filters(NULL, Array)
#15 /wp-2638511/wp-includes/plugin.php(522): WP_Hook->do_action(Array)
#16 /wp-2638511/wp-includes/script-loader.php(2311): do_action('wp_enqueue_scri...')
#17 /wp-2638511/wp-includes/class-wp-hook.php(341): wp_enqueue_scripts('')
#18 /wp-2638511/wp-includes/class-wp-hook.php(365): WP_Hook->apply_filters(NULL, Array)
#19 /wp-2638511/wp-includes/plugin.php(522): WP_Hook->do_action(Array)
#20 /wp-2638511/wp-includes/general-template.php(3197): do_action('wp_head')
#21 /wp-2638511/wp-content/themes/storefront/header.php(18): wp_head()
#22 /wp-2638511/wp-includes/template.php(814): require_once('/Applications/M...')
#23 /wp-2638511/wp-includes/template.php(749): load_template('/Applications/M...', true, Array)
#24 /wp-2638511/wp-includes/general-template.php(48): locate_template(Array, true, true, Array)
#25 /wp-2638511/wp-content/themes/storefront/page.php(13): get_header()
#26 /wp-2638511/wp-includes/template-loader.php(125): include('/Applications/M...')
#27 /wp-2638511/wp-blog-header.php(19): require_once('/Applications/M...')
#28 /wp-2638511/index.php(17): require('/Applications/M...')
#29 {main}
```

### PR DESCRIPTION
**Pull request by ayushpahwa**
### Submission Review Guidelines:

- [x] I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
- [x] I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
- [x] I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).

#### Background

This PR addresses the root cause of a bug where Local Pickup fails to render in the Block Checkout under certain conditions.

**The issue:** When a third-party plugin calls `WC()->cart->calculate_totals()` early in the page lifecycle with `cart_context = 'shortcode'` (the default), and "Hide shipping costs until an address is entered" is enabled, the `show_shipping()` method returns `false` because the Local Pickup bypass only existed in the non-shortcode (`store-api`) context branch. This causes `has_calculated_shipping` to remain `false` and `shipping_rates` to be empty.

**Why the bug doesn't always surface:** Two factors mask this issue:
1. The hydration process often recalculates shipping with the correct `store-api` context, recovering from the bad state
2. A defensive fix added on Dec 11, 2025 ([#61625](https://github.com/woocommerce/woocommerce/pull/61625)) added optional chaining (`packageData?.name`) which prevents the JavaScript error, though the Pickup tab still becomes non-functional

**The fix:** Move the Local Pickup enabled check to run *before* the cart context check in `show_shipping()`, so it applies to both `shortcode` and `store-api` contexts. This ensures pickup locations are always available when Local Pickup is enabled, regardless of when `calculate_totals()` is called.

Closes #62785.

#### Setup (do once)
1. Enable Local Pickup: WooCommerce → Settings → Shipping → Local pickup → Enable and add at least one pickup location
2. Enable "Hide shipping costs until an address is entered": WooCommerce → Settings → Shipping → Shipping settings
3. Add a shipping zone for your country with at least one shipping method (e.g., Flat rate)
4. Add this test code to your theme's `functions.php`:
```php
add_action( 'wp_enqueue_scripts', function() {
    if ( ! function_exists( 'is_checkout' ) || ! is_checkout() ) {
        return;
    }
    if ( WC()->cart ) {
        WC()->cart->cart_context = 'shortcode';
        WC()->cart->calculate_totals();
        error_log( 'has_calculated_shipping: ' . ( WC()->cart->has_calculated_shipping() ? 'true' : 'false' ) );
    }
}, 5 );
```

#### Test on trunk (verify bug exists)
1. Checkout `trunk` branch
2. Open an incognito browser window
3. Add a product to cart and go to checkout
4. Check the debug log

**Expected:** `has_calculated_shipping: false`

#### Test on this branch (verify fix)
1. Checkout this branch
2. Open an incognito browser window  
3. Add a product to cart and go to checkout
4. Check the debug log

**Expected:** `has_calculated_shipping: true`

5. Click the "Pickup" tab - pickup locations should display correctly
6. Remove the test code from `functions.php` when done

### Testing that has already taken place:

- Unit test added: `test_show_shipping_returns_true_with_local_pickup_enabled_and_no_address`
- All existing `show_shipping` tests pass (3 tests, 21 assertions)
- Manual testing with forced `shortcode` context confirms fix

### Milestone

- [x] Automatically assign milestone for the **[next WooCommerce version](../blob/trunk/plugins/woocommerce/woocommerce.php#L6)**

### Changelog entry

- [ ] Automatically create a changelog entry from the details below.

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce/includes/class-wc-cart.php [hunk 1]
```diff
@@ -1734,6 +1734,11 @@ public function show_shipping() {
 		}
 
 		if ( 'yes' === get_option( 'woocommerce_shipping_cost_requires_address' ) ) {
+			// If local pickup is enabled, shipping should be shown so that pickup locations are visible before address entry.
+			if ( LocalPickupUtils::is_local_pickup_enabled() ) {
+				return true;
```
Comment (samnajian) [inline plugins/woocommerce/includes/class-wc-cart.php]: We should be using `apply_filters( 'woocommerce_cart_ready_to_calc_shipping', true );` here as done at the end of this method.

**Review by straku — APPROVED** [review]
Pretty challenging flow to follow, but the fix makes sense. I don't think Claude is right in its assessment of breaking compatibility. The behavior that we're breaking here is a buggy one, I can't imagine someone relying on it. But I will let you address it.

Approving on human end 👍

File: plugins/woocommerce/includes/class-wc-cart.php (hunk 1 above)
Comment (ayushpahwa) [reply plugins/woocommerce/includes/class-wc-cart.php]: Added duplicate filter with comment (comment is following this [standard](https://developer.wordpress.org/coding-standards/inline-documentation-standards/php/#4-1-duplicate-hooks))

File: plugins/woocommerce/includes/class-wc-cart.php [hunk 2]
```diff
@@ -1734,6 +1734,11 @@ public function show_shipping() {
 		}
 
 		if ( 'yes' === get_option( 'woocommerce_shipping_cost_requires_address' ) ) {
+			// If local pickup is enabled, shipping should be shown so that pickup locations are visible before address entry.
+			if ( LocalPickupUtils::is_local_pickup_enabled() ) {
```
[the remark this answers is not in the document]
Comment (ayushpahwa) [reply plugins/woocommerce/includes/class-wc-cart.php:1768]: This behaviour was a bug and highly unlikely being used by plugin devs

File: plugins/woocommerce/includes/class-wc-cart.php [hunk 3]
```diff
@@ -1734,6 +1734,16 @@ public function show_shipping() {
...
+				/**
+				 * This filter is documented below.
+				 *
+				 * @since 10.6.0
```
Comment (samnajian) [inline plugins/woocommerce/includes/class-wc-cart.php]: We should remove thins `since` annotation, specially since it's wrong, this hook is not getting added in `10.6.0`

**Review by samnajian — APPROVED** [review]
LGTM, let's update the doc block for the hook before merging.

File: plugins/woocommerce/includes/class-wc-cart.php (hunk 3 above)
Comment (ayushpahwa) [reply plugins/woocommerce/includes/class-wc-cart.php]: The annotation is enforced by linter. There are other places the same method is used. Also, since the upcoming milestone is 10.6, hence I added this.

Comment (senadir) [reply plugins/woocommerce/includes/class-wc-cart.php]: I don't think it should be done like this, feel free to copy paste the same body from the original place of the filter if it exists, if it doesn't exists, do write it from that point of view

Comment (ayushpahwa) [reply plugins/woocommerce/includes/class-wc-cart.php]: The filter exists, I was following this [standard](https://developer.wordpress.org/coding-standards/inline-documentation-standards/php/#4-1-duplicate-hooks) in case of duplicates.

Comment (ayushpahwa) [reply plugins/woocommerce/includes/class-wc-cart.php]: I see other places in the codebase where similar method is used. (templates/cart/cart.php)
CleanShot 2026-01-22 at 17 43 41@2x

Comment (senadir) [reply plugins/woocommerce/includes/class-wc-cart.php]: Amm that's inconsistent because we do tend to copy the whole docblock in other places, maybe time to align with Core. In this case, ignore my comment, sorry :D
