### PR TITLE
Fix: order metadata changes from admin not applied with HPOS active.

### LINKED ISSUE #40161: Metadata is not updated when updating the order via admin
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

With HPOS enabled, updating the value for a given meta key inside the "Custom Fields" metabox and then saving the order doesn't persist the new value.

### Expected behavior

Values should be persisted when saving the order, as in the CPT case.

### Actual behavior

Old value remains (even after refreshing the page).

### Steps to reproduce

1. Enable HPOS by going to WC > Settings > Advanced > Features and choosing **High-performance order storage (recommended)** as **Order Data Storage**.
2. Go to WC > Orders and click **Add Order**.
3. Enter any details you'd like.
4. Scroll down to the "Custom Fields" metabox and enter `test_key` as Name and `test_value` as Value.
5. Click the **Create** order button.
6. Confirm that the metadata you just entered wasn't persisted.
7. Now repeat step 4 but click **Add Custom Field** instead.
8. Refresh the page and confirm that the metadata was persisted.
9. Now change the value of the meta key you just added, and click the **Update** order button.
10. Confirm that the update to the meta value didn't get persisted.

### WordPress Environment

N/A

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by Konamiman**
### Changes proposed in this Pull Request:

When an order is open in the admin area and changes are made to custom field keys or values, or a new custom field is added in the "Add New Custom Field" section, but the order "Update" button is clicked directly (without having clicked the "Update" button in the modified fields or the "Add Custom Field" button), the changes in the custom fields should be applied to the order anyway. That was happening when the posts table is authoritative but not when the orders table is authoritative. This pull request fixes that.

Closes #40161.

### How to test the changes in this Pull Request:

1. Make sure that HPOS is enabled (WooCommerce - Settings - Advanced - Features - Order data storage, or from command line: `wp wc cot enable`).
2. Create an order or open an existing order in the admin area. If it has custom fields already, delete all of them and reload the page.
3. Create four custom fields, with names `name1` to `name4` and values `value1` to `value4` respectively (click "Add custom field" for each). Reload the page.
4. Now do the following:
   * Delete the `name1` field (using the "Delete" button below the field name).
   * Change the _name_ of the `name2` field to `name2!`. **Don't** click "Update".
   * Change the _value_ of the `name3` field to `value3!`. **Don't** click "Update".
   * In the "Add New Custom Field" section write `name4` as the name and `value4!` as the value. **Don't** click "Add Custom Field".
5. Scroll up and click the "Update" button in the "Order actions" section.
6. Wait for the page to reload and verify that the changes have been applied as expected, including having now two fields named `name4` (this is consistent with the behavior when the posts table is authoritative):

image

7. Finally, verify that you can add a new custom field with an empty value (as before: write the name but directly click "Update" in "Order actions").

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message

Fix changes in order custom fields made from admin not being applied when using the order "Update" button with HPOS active.

#### Comment

</details>

### CODE REVIEW

File: plugins/woocommerce/includes/admin/meta-boxes/class-wc-meta-box-order-data.php [hunk 1]
```diff
@@ -708,6 +709,37 @@ public static function save( $order_id ) {
...
 		}
 
+		// Metadata (only needed when HPOS table is in use).
+		if ( wc_get_container()->get( CustomOrdersTableController::class )->custom_orders_table_usage_is_enabled() ) {
+			$order_meta = $order->get_meta_data();
+
+			$order_meta =
+				array_combine(
+					array_map( fn( $meta ) => $meta->id, $order_meta ),
+					array_map( fn( $meta ) => $meta, $order_meta )
```
Comment (jorgeatorres) [inline plugins/woocommerce/includes/admin/meta-boxes/class-wc-meta-box-order-data.php]: This could just be `$order_meta` itself instead of the `array_map()` that iterates over each item just to return that same item, right?

**Review by jorgeatorres — CHANGES_REQUESTED** [review]
Hi @Konamiman,

Thanks for working on this. It works perfectly. I just left a tiny suggestion... but also wonder if we should move this metadata handling metadata to [`Automattic\WooCommerce\Internal\Admin\Orders\MetaBoxes\CustomMetaBox`](https://github.com/woocommerce/woocommerce/blob/6b8e22c45e4c1dae5afcb5e60c2a950f5f2b493e/plugins/woocommerce/src/Internal/Admin/Orders/MetaBoxes/CustomMetaBox.php#L0-L1) instead, where the AJAX actions are already handled (and also the rendering of the metabox).

We could add a `save()` method or something that we hook onto `woocommerce_process_shop_order_meta` (as the other metaboxes) or we directly call from within [`Edit::handle_order_update()`](https://github.com/woocommerce/woocommerce/blob/93b6f1b8ce5b27064ef9745cf4f49026365b114e/plugins/woocommerce/src/Internal/Admin/Orders/Edit.php#L210) given the instance is already available as [`$this->custom_meta_box`](https://github.com/woocommerce/woocommerce/blob/93b6f1b8ce5b27064ef9745cf4f49026365b114e/plugins/woocommerce/src/Internal/Admin/Orders/Edit.php#L28).

I'm not sure if that's worth the trouble, so this is by no means a blocker, but wanted to get your opinion.

File: plugins/woocommerce/includes/admin/meta-boxes/class-wc-meta-box-order-data.php (hunk 1 above)
Comment (Konamiman) [reply plugins/woocommerce/includes/admin/meta-boxes/class-wc-meta-box-order-data.php]: Uuuuh... yes, true. That was originally `$meta->value` and when doing the change I didn't notice that.

**Comment by Konamiman** [comment]
> We could add a save() method or something that we hook onto woocommerce_process_shop_order_meta (as the other metaboxes) or we directly call from within [Edit::handle_order_update()](https://github.com/woocommerce/woocommerce/blob/93b6f1b8ce5b27064ef9745cf4f49026365b114e/plugins/woocommerce/src/Internal/Admin/Orders/Edit.php#L210) given the instance is already available as [$this->custom_meta_box](https://github.com/woocommerce/woocommerce/blob/93b6f1b8ce5b27064ef9745cf4f49026365b114e/plugins/woocommerce/src/Internal/Admin/Orders/Edit.php#L28).

That makes sense, thanks. I've implemented the change with the direct method call approach (it doesn't much sense to use a hook when we know beforehand where's the code we want to invoke).

File: plugins/woocommerce/src/Internal/Admin/Orders/Edit.php [hunk 2]
```diff
@@ -233,6 +232,10 @@ public function handle_order_update() {
 		 */
 		do_action( 'woocommerce_process_shop_order_meta', $this->order->get_id(), $this->order );
 
+		if ( wc_get_container()->get( CustomOrdersTableController::class )->custom_orders_table_usage_is_enabled() ) {
```
Comment (jorgeatorres) [inline plugins/woocommerce/src/Internal/Admin/Orders/Edit.php]: This check shouldn't be necessary as `Edit` is only used within an HPOS codepath. I believe it should be safe to assume that it is enabled. Context:

https://github.com/woocommerce/woocommerce/blob/93b6f1b8ce5b27064ef9745cf4f49026365b114e/plugins/woocommerce/src/Internal/Admin/Orders/PageController.php#L349 and https://github.com/woocommerce/woocommerce/blob/93b6f1b8ce5b27064ef9745cf4f49026365b114e/plugins/woocommerce/includes/admin/class-wc-admin-menus.php#L340-L341)

Also, that line is producing a fatal error because the `CustomOrdersTableController` can't be resolved.

**Review by jorgeatorres — CHANGES_REQUESTED** [review]
Hi @Konamiman!

Code looks more organized, but it's producing a fatal error with a check that we can remove anyways. I commented out that code and testing looked fine, so I believe that should be all that's left to address before merging.

Please let me know what you think.

File: plugins/woocommerce/src/Internal/Admin/Orders/Edit.php (hunk 2 above)
Comment (Konamiman) [reply plugins/woocommerce/src/Internal/Admin/Orders/Edit.php]: Argh. I added the HPOS check in the last moment before committing and didn't think that an import would be needed.

Anyway, you are right, the check isn't needed. I've removed it.

**Review by jorgeatorres — APPROVED** [review]
LGTM. Tested various updates related to metadata: renaming, deleting, adding, etc. both values and keys.
Also confirmed that this doesn't interfere with the CPT implementation.
