### PR TITLE
Product Editor: Fix editor crash when clicking in editor margin when summary or description fields are focused

### LINKED ISSUE #45522: Product Editor: Editor crashes when clicking off of text area (such as summary field)
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

The product editor crashes when the summary field is focused and then you click off into the margin of the editor. Tabbing to focus on another field, or clicking on another field does not cause this crash.

This only happens when Gutenberg 17.9.0 or later is installed.

This might be related to the recent change to the canvas in the product editor: https://github.com/woocommerce/woocommerce/pull/44166

### Expected behavior

The summary field loses focus and the editor does not crash.

### Actual behavior

The editor crashes and becomes blank.

https://github.com/woocommerce/woocommerce/assets/2098816/51df8219-e059-4ebf-b44e-3faa7b2302a7

### Steps to reproduce

With a WooCommerce dev env with the new product editor enabled (**WooCommerce** > **Settings** > **Advanced** > **Features** > **Experimental features**)...

1. Go to **Products** > **Add New**
1. Click on summary field to focus it.
2. Click on margin of editor.
3. Verify the editor crashes and is blank.

### WordPress Environment

- Gutenberg plugin activated.

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by mattsherman**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

This PR reverts the changes made in #44166, in order to provide a workaround to a **Gutenberg 17.9.0** bug that caused the product editor to crash when clicking on the margins when the summary or description fields were focused.

Once Gutenberg 18 is used, this workaround can be removed and the changes from #44166 can be used again (GB fix: https://github.com/WordPress/gutenberg/pull/59800). 

Fixes #45522.

### How to test the changes in this Pull Request:

With the new product editor enabled (**WooCommerce** > **Settings** > **Advanced** > **Features** > **Experimental features**), and the **Gutenberg 17.9.0** plugin activated...

1. Go to **Products** > **Add New**
1. Click on summary or description field to focus it.
2. Click on margin of editor.
3. Verify the editor does not crash and that the toolbar for the summary or description field is hidden.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Comment 

</details>

### CODE REVIEW

File: packages/js/product-editor/src/blocks/generic/text-area/edit.tsx [hunk 1]
```diff
@@ -120,6 +126,7 @@ export function TextAreaBlockEdit( {
 						placeholder={ placeholder }
 						required={ required }
 						disabled={ disabled }
+						onBlur={ hideToolbar }
```
Comment (retrofox) [inline packages/js/product-editor/src/blocks/generic/text-area/edit.tsx:129]: I like how you rename the generic`handlBlur` name of the function provided by the hook to hide the`hideToolbar`; it is more descriptive in this context. Finally, I like how you assign the onBlur event with the action to take: hideToolbar 💯 
I always try to use the same name convention. When I see `onChange= { onThingChange }`, I lose some hair.

File: packages/js/product-editor/src/hooks/use-clear-selected-block-on-blur/use-clear-selected-block-on-blur.ts [hunk 2]
```diff
@@ -0,0 +1,30 @@
...
+// fix from https://github.com/WordPress/gutenberg/pull/59800
+export const useClearSelectedBlockOnBlur = () => {
+	// eslint-disable-next-line @typescript-eslint/ban-ts-comment
+	// @ts-ignore No types for this exist yet.
+	const { clearSelectedBlock } = useDispatch( blockEditorStore );
+
+	function handleBlur( event: {
+		relatedTarget: ( EventTarget & Element ) | null;
+	} ) {
+		const isToolbar = event.relatedTarget?.closest(
```
Comment (retrofox) [inline packages/js/product-editor/src/hooks/use-clear-selected-block-on-blur/use-clear-selected-block-on-blur.ts]: I'm slightly concerned about not checking the related target property. Although it expects to be defined, would check whether it's defined prevent unexpected errors?

```suggestion
		const isToolbar = event?.relatedTarget?.closest(
```

**Review by retrofox — APPROVED** [review]
LGTM 🚢 

I am looking forward to seeing WordPress/gutenberg#59800 changes available.
