### PR TITLE
Fix non-ASCII coupon search

### LINKED ISSUE #32536: Coupons: Issues with latin1 and non-latin1 characters
Re: p9F6qB-94u-p2

### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Re: p9F6qB-94u-p2

Sites using the `latin1, latin1_swedish_ci` charset & collation can encounter issues with coupon codes similar to the search issues described on https://github.com/woocommerce/woocommerce/issues/24746 / https://github.com/woocommerce/woocommerce/pull/25314

While not WPCOM Atomic-specific, this can impact all WPCOM Atomic sites.

### Expected behavior

Create a coupon like `VÅR20` and be able to apply it at checkout.

### Actual behavior

LIKE queries are case-sensitive on non-latin1 characters.

When attempting to use `VÅR20` it will fail as the input is converted to `vår20`. Fails.

Attempting to use `vår20` fails as the coupon is `VÅR20`

### Steps to reproduce

1. Have a site with a `latin1, latin1_swedish_ci` charset & collation, like those available on WPCOM Atomic
2. Create a coupon in all caps using special characters, like `VÅR20`
3. Attempt to apply `VÅR20` at checkout. 
4. See failure, coupon doesn't exist

<details>
<summary>WordPress Environment</summary>

```
### WordPress Environment ###

WordPress address (URL): https://goodeatomictesting2022.wpcomstaging.com
Site address (URL): https://goodeatomictesting2022.wpcomstaging.com
WC Version: 6.3.1
REST API Version: ✔ 6.3.1
WC Blocks Version: ✔ 6.9.0
Action Scheduler Version: ✔ 3.4.0
WC Admin Version: ✔ 3.2.1
Log Directory Writable: ✔
WP Version: ❌ 5.8.2 - There is a newer version of WordPress available (5.9.3)
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: nb_NO
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 7.4.28
PHP Post Max Size: 2 GB
PHP Time Limit: 1200
PHP Max Input Vars: 6144
cURL Version: 7.82.0
OpenSSL/1.1.0l

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.3.34-MariaDB-log
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 6.3.1
WC Database Prefix: wp_
Total Database Size: 5.12MB
Database Data Size: 3.42MB
Database Index Size: 1.70MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.14MB + Index: 0.14MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.08MB + Index: 0.06MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_nx_entries: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_nx_posts: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_nx_stats: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 1.05MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 1.02MB + Index: 0.09MB + Engine InnoDB
wp_posts: Data: 0.14MB + Index: 0.06MB + Engine InnoDB
wp_rank_math_internal_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_rank_math_internal_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

amp_validated_url: 1
attachment: 24
elementor_library: 1
jetpack_migration: 2
jp_img_sitemap: 1
jp_sitemap: 1
jp_sitemap_master: 1
nav_menu_item: 1
page: 8
post: 1
product: 18
product_variation: 9
revision: 6
shop_coupon: 8
wp_global_styles: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (16) ###

Akismet Anti-Spam: by Automattic – 4.2.2
AMP: by AMP Project Contributors – 2.2.3
CoBlocks: by GoDaddy – 2.22.10
Crowdsignal Forms: by Automattic – 1.6.0
Facebook for WooCommerce: by Facebook – 2.6.12
Folders: by Premio – 2.7.5
WordPress.com Editing Toolkit: by Automattic – 3.30625
Gutenberg: by Gutenberg Team – 12.9.0
Jetpack Boost: by Automattic – 1.4.1
Jetpack: by Automattic – 10.9-a.1
Layout Grid: by Automattic – 1.8.1
Page Optimize: by Automattic – 0.5.2
Crowdsignal Polls & Ratings: by Automattic
Inc. – 3.0.7

Rank Math SEO: by Rank Math – 1.0.86.1
WooCommerce Payments: by Automattic – 3.9.3
WooCommerce: by Automattic – 6.3.1

### Inactive Plugins (4) ###

Classic Editor: by WordPress Contributors – 1.6.2
Elementor: by Elementor.com – 3.6.2
NotificationX: by WPDeveloper – 2.4.2
Query Monitor: by John Blackbourn – 3.8.2

### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
object-cache.php: Memcached

### Must Use Plugins (1) ###

WP.com Site Helper: by  –

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #36 - /shop/
Cart: #37 - /cart/
Checkout: #38 - /checkout/
My account: #39 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Videomaker
Version: 1.0.10 (update to version 1.0.16 is available)
Author URL: https://automattic.com/
Child Theme: ✔
Parent Theme Name: Blockbase (Premium)
Parent Theme Version: 2.0.15
Parent Theme Author URL: https://automattic.com/
WooCommerce Support: ❌ Not declared

### Templates ###

Overrides: –

### Subscriptions ###

WCS_DEBUG: ✔ No
Subscriptions Mode: ✔ Live
Subscriptions Live URL: https://goodeatomictesting2022.wpcomstaging.com
Subscription Statuses: –
WooCommerce Account Connected: ❌ No

### Store Setup ###

Country / State: United States (US) — Tennessee

### Payment Gateway Support ###


### WooCommerce Payments ###

Version: 3.9.3
Connected to WPCOM: Yes
Blog ID: 201075165
Account ID: -

### Action Scheduler ###

Complete: 292
Oldest: 2022-03-08 18:03:30 -0500
Newest: 2022-04-08 13:51:41 -0400

Pending: 2
Oldest: 2022-04-08 14:52:47 -0400
Newest: 2022-04-09 12:52:48 -0400


### Status report information ###

Generated at: 2022-04-08 14:04:56 -04:00
```

</details>

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by timur27**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes https://github.com/woocommerce/woocommerce/issues/32536

When PHP attempts to `strtolower()` for non-ASCII chars, the converted value is corrupted which is why the search for coupons with titles like e.g. `VÅR20` failed. This PR removes the lowercase, similarly to how it was done in https://github.com/woocommerce/woocommerce/pull/25314.

#### 0️⃣  Preparation steps
* Change the collation for your DB and all the tables in it with the following steps
> Once inside the database, click on the "Operations" tab in the top menu.
Change Database Collation:
Scroll down to the "Collation" section.
From the dropdown menu, select **latin1_swedish_ci**.
Check the boxes for "Change all tables collations" and "Change all tables columns collations".
Click Go to apply changes.

* Use the following SQL to check whether the table has the `latin1_swedish_ci` collation set

```sql
SELECT TABLE_NAME, TABLE_COLLATION 
FROM information_schema.TABLES 
WHERE TABLE_SCHEMA = 'wordpress'
AND TABLE_NAME = 'wp_posts';
```

Also define the collation and charset constants in `docker/wordpress/wp-config.php`

```php
define('DB_CHARSET', 'latin1');
define('DB_COLLATE', 'latin1_swedish_ci');
```

#### 1️⃣ Adding coupons
* Go to WooCommerce → Coupons → Add New
* Enter a coupon code with mixed case (e.g., `SummerSale2025`)
* Create the coupon with the following title: `VÅR20`

#### 2️⃣ Applying coupons
On the shortcode

* Apply the `VÅR20` coupon and confirm it's applied
* Remove the `VÅR20` and confirm it's removed
* Apply the `vÅr20` coupon and confirm case-insensitivity as the coupon should be applied too
* Apply the `SummerSale2025` coupon and confirm it's applied
* Apply the `SUMMERSALE2025` coupon and confirm that you see the "Coupon code already applied!" message under the input field

#### 3️⃣ Removing coupons
Staying on the shortcode

* remove all the currently applied coupons and confirm they are successfully removed

#### 4️⃣ Other pages
* Repeat steps 2️⃣ and 3️⃣ on
    * Blocks checkout page
    * Cart block page
    * Shortcode cart page

#### 5️⃣ Manual order creation & coupon management
* Create a new order in WooCommerce admin (WooCommerce → Orders → Add New)
* Add some products to the order
* Apply the `VÅR20` coupon and confirm it's applied
* Remove the `VÅR20` and confirm it's removed
* Apply the `vÅr20` coupon and confirm case-insensitivity as the coupon should be applied too
* Apply the `SummerSale2025` coupon and confirm it's applied
* Apply the `SUMMERSALE2025` coupon and confirm that you see the "Coupon code already applied!" message under the input field
* Remove the coupons by clicking on the small "x" on the coupon icons and confirm the coupons are successfully removed

#### 6️⃣ APIv1 tests
* Perform a `POST /wp-json/wc/v1/coupons`

<details>
<summary>Here's the request body to take as an example</summary>

```json
{
  "code": "MÅQ25",
  "discount_type": "percent",
  "amount": "10",
  "individual_use": true,
  "exclude_sale_items": false,
  "minimum_amount": "100.00"
}
```
</details>

* Once the POST request is successful, please verify if you can use this coupon on any of the checkout or cart pages in different forms
    * `MÅQ25`
    * `mÅq25`

#### 7️⃣ APIv2 tests
* Perform a `POST /wp-json/wc/v2/coupons`
<details>
<summary>Here's the request body to take as an example</summary>

```json
{
  "code": "DÅQ25",
  "discount_type": "percent",
  "amount": "10",
  "individual_use": true,
  "exclude_sale_items": false,
  "minimum_amount": "100.00"
}
```
</details>

* Once the POST request is successful, please verify if you can use this coupon on any of the checkout or cart pages in different forms
    * `DÅQ25`
    * `dÅq25`

#### 8️⃣  APIv3 order test
* perform a`POST /wp-json/wc/v3/orders` request with a different case of a coupon included in the request body and confirm, that for all of them the request is successful

<details>
<summary>Example (additionally try with other combinations of existing coupon code e.g. `vÅR20` and `VÅR20` or `vÅr20` </summary>

```json
{
  "payment_method": "bacs",
  "payment_method_title": "Direct Bank Transfer",
  "set_paid": false,
  "billing": {
    "first_name": "John",
    "last_name": "Doe",
    "email": "admin@example.com"
  },
  "line_items": [
    {
      "product_id": 123,
      "quantity": 2
    }
  ],
  "coupon_lines": [
    {
      "code": "vÅR20"
    }
  ]
}
```
</details>

* Once the POST request is successful, check that the coupon is attached to the order in the order details

#### 9️⃣ WooCommerce Analytics
* Navigate to Analytics -> Orders and confirm that the coupon codes are displayed for the orders they were used at
* Navigate to Analytics -> Coupons and confirm that the filtering/search of coupons works and is case-insensitive

 
### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

**Comment by timur27** [comment]
I checked the failing e2e tests and they occur on `trunk` too.

**Comment by timur27** [comment]
I think I switched the context to something else yesterday and forgot to push ae4cdbf631eb2e9301f560cb50ef1c8f0f384e25 as well. Now it's here.

File: plugins/woocommerce/includes/wc-core-functions.php [hunk 1]
```diff
@@ -39,7 +39,6 @@
  */
 add_filter( 'woocommerce_coupon_code', 'html_entity_decode' );
 add_filter( 'woocommerce_coupon_code', 'wc_sanitize_coupon_code' );
-add_filter( 'woocommerce_coupon_code', 'wc_strtolower' );
```
Comment (frosso) [inline plugins/woocommerce/includes/wc-core-functions.php:42]: I still have to complete the full review of the changes/code.
I think most of the changes seem good at a first sight, but this particular one is giving me pause.

I'd like to hear your thoughts on the possibility that there are other plugins (or code) that relies on having the `woocommerce_coupon_code` filter return a lowercase string (instead of a string with its case maintained), including consumers of `wc_format_coupon_code`, and the impact of this change on them.

Examples could be `WooCommerce Customer/Order/Coupon CSV Import` by SkyVerge, the `WooCommerce Smart Coupons`, or some of the ZenDesk tools that are hosted on WCcom.

Comment (timur27) [reply plugins/woocommerce/includes/wc-core-functions.php:42]: @frosso great point, apologies for missing that in the first place - I ended up being too focused on discovering all the possible coupon use cases within WooCommerce :) 

There were two approaches I considered - to introduce a separate formatting function and a new hook w/o lowercasing [[example](https://github.com/woocommerce/woocommerce/pull/56319/commits/f3dc2ac4860262baefc7aae59bc8f632615a5e43#diff-b30e72bdafa06ec50e9bd0f25a729265d7151acefc256ddfd790ca58d44bbd3dR366-R368)] or expanding the existing formatting function with backwards compatibility in mind [[example](https://github.com/woocommerce/woocommerce/pull/56319/commits/eef953676a495fc0d662ff9209625d0baeef28f2#diff-b30e72bdafa06ec50e9bd0f25a729265d7151acefc256ddfd790ca58d44bbd3dR360-R377)]. I eventually went with this second approach because it looks less confusing as there's only one formatting function to call. May I ask you to have another look? 👀

File: plugins/woocommerce/includes/wc-core-functions.php [hunk 2]
```diff
@@ -37,8 +37,10 @@
 /**
  * Filters on data used in admin and frontend.
  */
-add_filter( 'woocommerce_coupon_code', 'html_entity_decode' );
-add_filter( 'woocommerce_coupon_code', 'wc_sanitize_coupon_code' );
+foreach ( array( 'woocommerce_coupon_code', 'woocommerce_coupon_code_without_lower' ) as $filter ) {
+	add_filter( $filter, 'html_entity_decode' );
+	add_filter( $filter, 'wc_sanitize_coupon_code' );
+}
```
Comment (frosso) [inline plugins/woocommerce/includes/wc-core-functions.php]: FWIW, I didn't mind the previous approach where each `add_filter` was repeated :) 

Otherwise one might even have done a few rows below:
```
foreach ( [
    'wptexturize',
    'convert_smilies',
    'convert_chars',
    'wpautop',
    'shortcode_unautop',
    'prepend_attachment',
    'wc_do_oembeds',
] as $filter) {
    add_filter('woocommerce_short_description', $filter);
}
```

File: plugins/woocommerce/includes/wc-formatting-functions.php [hunk 3]
```diff
@@ -360,11 +360,21 @@ function wc_format_localized_decimal( $value ) {
...
+ *
  * @since  3.0.0
  * @param  string $value Coupon code to format.
+ * @param  bool   $skip_lowercase Whether to skip the lowercase conversion.
  * @return string
  */
-function wc_format_coupon_code( $value ) {
+function wc_format_coupon_code( $value, $skip_lowercase = false ) {
+	if ( $skip_lowercase ) {
+		/* phpcs:disable WooCommerce.Commenting.CommentHooks.MissingHookComment */
```
Comment (frosso) [inline plugins/woocommerce/includes/wc-formatting-functions.php]: I think it would be useful to provide a comment here? Something about its purpose and maybe even the `@since` tag.

File: plugins/woocommerce/includes/wc-formatting-functions.php [hunk 4]
```diff
@@ -360,11 +360,21 @@ function wc_format_localized_decimal( $value ) {
...
+ * Skipping the lowercase conversion is useful when coupon codes contain non-ASCII characters (like 'Å', 'Ö', 'Ü')
+ * which can be negatively affected by the lowercase conversion, especially on sites using latin1 charset.
+ *
  * @since  3.0.0
  * @param  string $value Coupon code to format.
+ * @param  bool   $skip_lowercase Whether to skip the lowercase conversion.
  * @return string
  */
-function wc_format_coupon_code( $value ) {
+function wc_format_coupon_code( $value, $skip_lowercase = false ) {
```
Comment (frosso) [inline plugins/woocommerce/includes/wc-formatting-functions.php]: (minor naming suggestion) I like how `$skip_lowercase` is explicit in what it does, but I was wondering if you had considered naming this argument `preserve_case` (instead of `skip_lowercase`) so its naming would align with other naming conventions (like `$preserve_keys` or `preserve_headers` in WC Core, but even `preserveAspectRatio` on SVGs).

I was thinking that `preserve_` would also be a good suitor here, since it conveys that the case should remain untouched. "skip" conveys "prevent the lowercasing from happening", but "preserve" conveys to me "maintain the original format".

Minor thing - not saying that there aren't precedents for the `skip_*` prefix :) 

Then, the `woocommerce_coupon_code_without_lower` could also be converted to something with a positive action - like `woocommerce_coupon_code_original_case` or `woocommerce_coupon_code_case_sensitive`.

File: plugins/woocommerce/includes/wc-core-functions.php (hunk 1 above)
Comment (frosso) [reply plugins/woocommerce/includes/wc-core-functions.php:42]: Both solutions/options sound good to me, thank you for outlining them :)

In that case, there's also the possibility that other plugins or themes have hooked into the `woocommerce_coupon_code` filter.
With either of the implementations you suggested, any additional filter that was added to `woocommerce_coupon_code` by third-parties wouldn't be applied to `woocommerce_coupon_code_without_lower`.

Am I thinking that right? 👀  Do you think that would be a concerning factor?

**Review by frosso — COMMENTED** [review]
I left a few more comments about the new implementation, but the main one is about the possibility that filters applied onto `woocommerce_coupon_code` wouldn't be applied to `woocommerce_coupon_code_without_lower` - I'd like to hear your thoughts on that point.

**Comment by timur27** [comment]
After discussing in p1741951466805729-slack-C8X6Q7XQU and f2f, we picked the initial version of the implementation, which removes the `wc_strtolower` from the formatting filter chain. I also added the helper comparison function to encapsulate the lowercasing to simplify it a bit.

@frosso thanks for the reviews so far, may I ask you to review & test it?

**Comment by timur27** [comment]
@frosso after https://github.com/woocommerce/woocommerce/pull/56319#issuecomment-2725045016 on Friday, I also added https://github.com/woocommerce/woocommerce/pull/56319/commits/3f2624c2c44b82920a6fa7e9611ac83afef2fcc2 today in the morning because I realized that it wouldn't hurt to have an extra sanitization when comparing values too. I hope it didn't interfere with your review process. Thanks!

File: plugins/woocommerce/includes/wc-coupon-functions.php [hunk 5]
```diff
@@ -71,6 +71,20 @@ function wc_coupons_enabled() {
...
+ * Lowercasing to ensure case-insensitive comparison.
+ *
+ * @since 9.9.0
+ *
+ * @param string $coupon_1 Coupon code 1.
+ * @param string $coupon_2 Coupon code 2.
+ * @return bool
+ */
+function wc_is_same_coupon( $coupon_1, $coupon_2 ) {
+	return wc_strtolower( $coupon_1 ) === wc_strtolower( $coupon_2 );
```
Comment (frosso) [inline plugins/woocommerce/includes/wc-coupon-functions.php:85]: (minor) I wonder about the utility of a function that says it's comparing coupons, when in reality it's just comparing two strings converted to lowercase. Are you just trying to get a consistent comparison without the overhead of `WC_Coupon`?

I was thinking that one alternative could be to use the `WC_Coupon` core class - something like this:
```php
function wc_is_same_coupon( $coupon_1, $coupon_2 ) {
    $coupon_obj_1 = new WC_Coupon( $coupon_1 );
    $coupon_obj_2 = new WC_Coupon( $coupon_2 );
    
    return $coupon_obj_1->get_code() === $coupon_obj_2->get_code();
}
```

That way, you don't need to call `wc_strtolower` each time (and you could possibly keep the filter).

But there might be some overhead with the usage of `WC_Coupon` 🤷 

In terms of naming convention, I noticed that there seem to be a slight preference towards the `wc_[object]_is*` convention - so _maybe_ consider the naming `wc_coupon_is_equal()`? But again, up for discussion, I'd like to hear your thoughts 🤷

**Review by frosso — APPROVED** [review]
Tested all checkout flavors, API, coupon management with same coupon code, etc.
Here's a non-comprehensive dump of test scenarios I performed:
Screenshot 2025-03-17 at 10 16 10 PM
Screenshot 2025-03-17 at 9 58 15 PM
Screenshot 2025-03-17 at 9 58 05 PM
Screenshot 2025-03-17 at 9 57 54 PM
Screenshot 2025-03-17 at 9 57 03 PM
Screenshot 2025-03-17 at 9 54 28 PM

Screenshot 2025-03-17 at 9 52 06 PM

My comment is non-blocking. Just trying to think of different scenarios. Thank you for all the discussion(s) so far!

File: plugins/woocommerce/includes/wc-coupon-functions.php (hunk 5 above)
Comment (timur27) [reply plugins/woocommerce/includes/wc-coupon-functions.php:85]: Thanks for the thoughts!

The coupon class is slightly more preferable to me too, and we could move to using the state of the class and doing something like 
```php
public function is_coupon_code_equal_to( $coupon_code ) {
    return wc_strtolower( $this->get_code() ) === wc_strtolower( $coupon_code );
}
```

in `WC_Coupon`, but I haven't done so because there's also `WC_Order_Item_Coupon` class for order flows and I didn't want to repeat the logic when there's an utility file. I acknowledge that there are existing places that are duplicated but I didn't want to follow this behavior.

---------

> In terms of naming convention, I noticed that there seem to be a slight preference towards the wc_[object]_is* convention

I was considering that too, but I found helper functions following the `wc_is_*` pattern to be more prevalent:
```
wc_is_order_status()
wc_is_valid_url()
wc_is_attribute_in_product_name()
wc_is_webhook_valid_topic()
wc_is_webhook_valid_status()
wc_is_current_account_menu_item()
wc_is_external_resource()
wc_is_active_theme()
wc_is_wp_default_theme_active()
wc_is_file_valid_csv()
```

many of `wc_is_*` are also helper functions performing some basic operations of objects/collections/types.


I think having said that plus the fact that new changes will require additional round of testing, I think keeping things as they are would be my favorite option, but I will keep the PR open for a bit in case you will want to chat more. Thank you!

Comment (frosso) [reply plugins/woocommerce/includes/wc-coupon-functions.php:85]: > The coupon class is slightly more preferable to me too, and we could move to using the state of the class and doing something like [...] in WC_Coupon, but I haven't done so because there's also WC_Order_Item_Coupon class for order flows and I didn't want to repeat the logic when there's an utility file. I acknowledge that there are existing places that are duplicated but I didn't want to follow this behavior.

That's also a great suggestion - unfortunate about `WC_Order_Item_Coupon`.

> I was considering that too, but I found helper functions following the `wc_is_*` pattern to be more prevalent

I was basing my observation off of this:
`(wc|woocommerce)_(is|has)_[a-z]*`: 97 results, 29 unique instances
`(wc|woocommerce)_[a-z]*_(is|has)_[a-z_-]*`: 110 results, 37 unique instances

This includes both functions and filters, of course.

But either way - not a massive difference in terms of results :) Thank you for the consideration!
