### PR TITLE
[Experimental] Product Filters Redesign > Clear Button: Make the block respect the filter settings

### LINKED ISSUE #51636: Clear button doesn't respect filter block setting
The Clear Button block is always rendered in both editors and on the front end even if the corresponding setting is disabled in the Filter Block setting.

### Steps to reproduce
0. Ensure the experimental blocks are enabled:
    - If you use the WooCommerce Beta Tester plugin, you can enable the experimental blocks in Tools > WCA Test Helper > Features. Toggle the `experimental-blocks` option.
    - If you build this PR locally, build the branch with `pnpm --filter='@woocommerce/plugin-woocommerce' watch:build` command to have experimental blocks available.
1. Edit the Product Catalog template, and add the `Product Filters (Experimental)` template part to the page.
2. See the attribute filter block set to your store's product attribute automatically.
3. Select the attribute filter block > Inspector controls sidebar > Styles tab.
4. Toggle off the Clear button setting.
5. See the Clear button block is still rendered in the canvas.
6. Save the page and see the same things on the frontend (when you choose a filter).

### Screenshots 

Thanks @roykho for the screenshots:

image

image

### PR DESCRIPTION
**Pull request by thealexandrelara**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes #51636.

This PR allows merchants to enable or disable the "Clear" button. When enabled, the "Clear" button will appear once the user selects a filter option. When disabled, the "Clear" button will be hidden all the time.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

> [!NOTE]  
> **Pre-requisite**
> - If you're using WC Beta Tester plugin, make sure the `experimental-blocks` feature is enabled (Tools > WCA Test Helper > Features).

1. Navigate to Product Catalog template (Appearance > Editor > Template > Product Catalog).
2. Add the Product Filters (Experimental) block.
3. Select the Attribute filter and open the Inspector Controls.
4. Disable the "Clear" button and ensure it's hidden in the Editor.
5. Save the template and visit the front page to ensure it's hidden there as well.
6. Go back to the Product Catalog template and enable the "Clear" button;
7. Make sure the Clear button is restored.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [x] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment  Fix an error where the Product Filter Clear Button block does not respect the filter settings.

</details>

### CODE REVIEW

**Comment by dinhtungdu** [comment]
As discussed in our check-in call, we should have a unified solution combining this and @roykho implementation in #52268.

**Comment by thealexandrelara** [comment]
> As discussed in our check-in call, we should have a unified solution combining this and @roykho implementation in #52268.

I didn't attend the check-in call; however, I suggest we merge this PR as soon as possible. Using the `useProductFilterClearButtonManager()` hook implemented in this PR in any filter will handle the clear button setting (hiding or showing the Clear button depending on the selected option). Roy's implementation is focused on the Active Filters block.

**Comment by dinhtungdu** [comment]
> I didn't attend the check-in call;

@thealexandrelara, in summary, @roykho shared that he has a different approach to the clear button in his PR (https://github.com/woocommerce/woocommerce/pull/52268). So we think that it's best to have a unified approach before moving on and I suggest centralizing the work on the clear button in this PR.

> Using the useProductFilterClearButtonManager() hook implemented in this PR in any filter will handle the clear button setting (hiding or showing the Clear button depending on the selected option). Roy's implementation is focused on the Active Filters block.

I see, as Roy raised the point, let's wait for him to reply on this.

As you're in the close timezone, I think it's best to pair on this PR and decide the path forward. What do you think?

**Comment by dinhtungdu** [comment]
I will hold my review on this PR until then.

**Comment by roykho** [comment]
A couple of questions:

- If we're to use this implementation for all the clear buttons, shouldn't it be moved out of attributes folder and into product filters?
- Does this implementation account for when there is no header group because Active filters don't have that?
- Does this implementation account for the Active filter where the clear button should be positioned under the chips block unlike the other filters where it is above and/or next to the heading name?

**Comment by imanish003** [comment]
FWIW, I was also taking a quick look at this PR as I was also assigned as a reviewer. I also have a concern similar to the one raised by @roykho. Specifically:

> Does this implementation according for when there is no header group because Active filters don't have that?

The `findPositionToAddTheClearButtonBlock` function makes assumptions that could be problematic:
- It relies on finding the first `core/group` block and assumes it's the header group
- This approach is fragile since merchants can add multiple group blocks
- There's no guarantee the first group block will always be the header

**Alternative solutions?**

1. Use a named group approach with metadata:

Maybe we can consider naming the group block? For example, Here is how group with name "My Group Name" looks like:

```tsx
<!-- wp:group {"metadata":{"name":"My Group Name"},"layout":{"type":"constrained"}} -->
<div class="wp-block-group"></div>
<!-- /wp:group -->
```

2. We can consider creating a new inner block for header group

3. Maybe we can create block variations? For example, we can create a new block variation of `core/group`.

4. We can also consider adding new block attributes to core blocks like `core/group`. For example, we are adding `__woocommerceNamespace` attribute to various core block [here](https://github.com/woocommerce/woocommerce/blob/008580c2c7f870d04127bec029a4e7ae8d6d1ce2/plugins/woocommerce-blocks/assets/js/blocks/product-query/index.tsx#L25-L42).

These are just some initial thoughts and potential approaches to consider for a more robust solution. I hope these are helpful 🙇

**Comment by thealexandrelara** [comment]
Thank you all for your inputs!

> If we're to use this implementation for all the clear buttons, shouldn't it be moved out of attributes folder and into product filters?

Yes, that can be moved there.

> Does this implementation account for when there is no header group because Active filters don't have that?
Does this implementation account for the Active filter where the clear button should be positioned under the chips block unlike the other filters where it is above and/or next to the heading name?

Regarding the first point, yes, it does; by default, the block will be added as the first inner block. As for the second point, no, it doesn’t.

The implementation essentially focuses on three things:

- Removing the block when the setting is disabled.
- Adding the block back to its default position (within the group block) when the setting is enabled.
- Adding the block back to a fallback position (by default, the first inner block of the filter block) when the default position is not found.

Ultimately, users can customize each block in countless ways, and it would be impossible to cover all of them. I think we should at least define and focus on default behavior and fallback behavior in the settings. Manish’s idea of adding a metadata group name could improve the success rate of the default behavior; however, we would still need a fallback that simply places the block, for example, at the beginning of the filter block, allowing users to move it to wherever they prefer, as there will be cases where the group block will not be there for us to use it as a reference.

One option to improve the current implementation is to expose a way for each filter block to pass the expected position for the clear button in the `useProductFilterClearButtonManager` hook. The hook would then use the `createBlock` or the [moveBlockToPosition](https://developer.wordpress.org/block-editor/reference-guides/data/data-core-block-editor/#moveblocktoposition) methods to create/move the block to the correct position. This approach would allow us to extend this functionality for any future filters, as I believe each filter will better understand where to position the Clear button, rather than trying to create a one-size-fits-all solution in the hook itself. I'm currently in SR, but I can start working on this next week.

File: plugins/woocommerce-blocks/assets/js/blocks/product-filters/inner-blocks/attribute-filter/use-product-filter-clear-button-manager.tsx [hunk 1]
```diff
@@ -0,0 +1,132 @@
...
+				clearButtonParentBlockId: filterBlockHeader?.clientId,
+			};
+		}
+		return {
+			clearButtonBlockPosition: 0,
+			clearButtonParentBlockId: clientId,
+		};
+	}
+
+	useEffect( () => {
```
Comment (dinhtungdu) [inline plugins/woocommerce-blocks/assets/js/blocks/product-filters/inner-blocks/attribute-filter/use-product-filter-clear-button-manager.tsx]: I wonder if we can make it a shared util instead of a hook to execute on an attribute change event. Instead of subscribe to the change, we can only do the manipulation when we need it.

Comment (thealexandrelara) [reply plugins/woocommerce-blocks/assets/js/blocks/product-filters/inner-blocks/attribute-filter/use-product-filter-clear-button-manager.tsx]: Sorry I missed your message 😞 . We can convert the hook to just be a regular function, but TBH I don't see any advantage in this case since we would have to duplicate the logic on each filter to detect the attribute change and react accordingly. The current implementation already handles that since it's hooked into the React state and lifecycle.

Comment (dinhtungdu) [reply plugins/woocommerce-blocks/assets/js/blocks/product-filters/inner-blocks/attribute-filter/use-product-filter-clear-button-manager.tsx]: > I don't see any advantage in this case

I'm commenting from the performance perspective. Because using a hook means that the callback will execute anytime dependencies change. We short-circuit most of the cases so it's probably not an issue here. Although the `useSelect` is always executed, the counterpoint is: that it's cached so it's cheap to run. I don't have any benchmark to back my concern so you can skip this comment. The performance gain (if any) might not be worth the effort, too.

> since we would have to duplicate the logic on each filter to detect the attribute change and react accordingly

I don't think so. We only need to execute the function in the `onChange` callback of the inspector control. I don't see the need to detect the attribute change here.

File: plugins/woocommerce-blocks/assets/js/blocks/product-filters/inner-blocks/attribute-filter/inspector.tsx [hunk 2]
```diff
@@ -64,10 +64,12 @@ export const Inspector = ( {
 	);
 
 	if ( displayStyleOptions.length === 0 ) {
-		displayStyleOptions = getBlockTypes().filter( ( blockType ) =>
-			blockType.ancestor?.includes(
-				'woocommerce/product-filter-attribute'
-			)
+		displayStyleOptions = getBlockTypes().filter(
+			( blockType ) =>
+				blockType.name !== 'woocommerce/product-filter-clear-button' &&
```
Comment (dinhtungdu) [inline plugins/woocommerce-blocks/assets/js/blocks/product-filters/inner-blocks/attribute-filter/inspector.tsx:69]: This makes me realize the current mechanism for registering display-style blocks is quite fragile, as blocks can be inner block of the filter block but not necessarily a display-style block.

File: plugins/woocommerce-blocks/assets/js/blocks/product-filters/inner-blocks/attribute-filter/use-product-filter-clear-button-manager.tsx (hunk 1 above)
Comment (thealexandrelara) [reply plugins/woocommerce-blocks/assets/js/blocks/product-filters/inner-blocks/attribute-filter/use-product-filter-clear-button-manager.tsx]: Oh, now I see what you mean. Yeah, performance-wise, I don’t think we would gain much, but in terms of only calling the function when the attribute changes, I agree it would be better. I refactored part of the code and moved some functions to the product-filters/utils folder, but I’ll explore your suggestion tomorrow. I think with that, we can get rid of the hook. Thank you for sharing this!

Comment (dinhtungdu) [reply plugins/woocommerce-blocks/assets/js/blocks/product-filters/inner-blocks/attribute-filter/use-product-filter-clear-button-manager.tsx]: What do you think about refactoring it later as we're wrapping up this cycle?

Comment (thealexandrelara) [reply plugins/woocommerce-blocks/assets/js/blocks/product-filters/inner-blocks/attribute-filter/use-product-filter-clear-button-manager.tsx]: I agree with you. Let's review the current implementation then, and we can refactor it later if needed.

File: plugins/woocommerce-blocks/assets/js/blocks/product-filters/inner-blocks/rating-filter/components/inspector.tsx [hunk 3]
```diff
@@ -59,64 +59,78 @@ export const Inspector = ( {
...
+					<ToggleControl
+						label={ __( 'Clear button', 'woocommerce' ) }
+						checked={ clearButton }
+						onChange={ ( value ) =>
+							setAttributes( { clearButton: value } )
+						}
+					/>
+				</PanelBody>
+			</InspectorControls>
+		</>
```
Comment (dinhtungdu) [inline plugins/woocommerce-blocks/assets/js/blocks/product-filters/inner-blocks/rating-filter/components/inspector.tsx:134]: This is creating two `Display` panels in two tabs. Looks like we need to review the placement of the Display panel. I prefer to place that panel under the Settings tab over the Styles tab. But that should be addressed in a follow-up PR.

File: plugins/woocommerce-blocks/assets/js/blocks/product-filters/utils/index.ts
Comment (dinhtungdu) [inline plugins/woocommerce-blocks/assets/js/blocks/product-filters/utils/index.ts:1]: We should also refactor the function in this file into their own files, in a follow-up PR.

**Review by dinhtungdu — APPROVED** [review]
Thanks for working on this! Tested and worked great in my test. The code looks good too! This PR is LGTM :shipit: 

After merging this PR, we should create a follow-up PR to update the Active block to use this hook.
