### PR TITLE
Download handler: support falling back on the redirect method (as an option, not a default)

### LINKED ISSUE #30288: Redirect to page using Downloadable Products is broken since 5.5.1/5.5.0 (download_file_redirect/download_file_force)
Hello,

I couldn't find anywhere if this change is intended or not (WooCommerce 5.5.1 changelog is not published). There is nothing on 5.5.0 changelog https://github.com/woocommerce/woocommerce/blob/release/5.5/changelog.txt#L3-L185
Before 5.5.1 you could use "Force download" for products and it will fallback to download_file_redirect if file was remote or not found on server.

Commit that changed this behavior:
https://github.com/woocommerce/woocommerce/commit/f88586eb1f040b81a73a62f183aa7084dccfdbc5

This is breaking change, because if you run store with "mixed" files from cloud and local and some redirects to pages, now your redirects to pages are downloading htmls, instead of redirecting.

Maybe there should be another download option "Mixed" or something that will allow to have both benefits of forced download and redirect. Or maybe you should be able to specify it on each downloadable product

### PR DESCRIPTION
**Pull request by barryhughes**
The product download handler supports 3 different methods of serving files:

| Method | Note |
| --- | --- |
| X-Accel/X-Sendfile | Secure _(customer cannot see the source URL)_ |
| Force Download | Secure _(customer cannot see the source URL)_ |
| Redirect Only | Insecure _(source URL is exposed to the customer)_ |

Previously (before 5.5.0) the system included a fallback mechanism as follows:

* If `X-Accel/X-Sendfile` is the preferred method but cannot be used, it falls back on Force Download. 
* If `Force Download` cannot be used and if the digital product file **is remote**, then a final fallback is made to the Redirect method 
* `Redirect` is the last method, there is no further fallback.

In f88586e we removed that final fallback, so as to avoid inadvertently exposing the digital asset's public path to the world (in other words, the idea was that redirects should be explicitly enabled or not happen at all), however there were some problems with this:

* In some cases, even though the merchant may have selected one of the secure delivery methods, their server was not configured appropriately and so downloads were relying on the redirect fallback. Therefore, removing that fallback had the effect of breaking their customers' access to purchased digital assets.
* In other cases, the merchant (knowingly or unkowingly) relied on the previous chain of fallbacks because they hosted their assets across a diverse range of storage platforms, some that were suitable for `Force Download` but others that were not. The previous system of fallbacks was therefore essential to supporting this arrangement.

In this change:

* We add a new option _"Allow using redirect mode as a last resort"._
* We add logging, so that a record is kept of any fallbacks that take place (letting the merchant or site operator find problems and take corrective steps if appropriate).

This hopefully gives the best of both worlds. Improved security (we don't allow redirects if the merchant hasn't specifically allowed for them) with the flexibility of the earlier, pre-5.5.0 approach (by allowing redirects as a final fallback, but only if explicitly enabled).

Closes #30288.

### Screenshots

optional-redirect-fallback-option
:point_up: New option, allowing fallbacks on redirects but making it something that needs to be explicitly enabled.

Screenshot 2021-07-19 at 15-43-14 WooCommerce settings ‹ WC Lab — WordPress
:point_up: Revised message text for the deprecation warning that renders when _"Redirect Only"_ is selected.

### How to test the changes in this Pull Request:

Setup

1. Configure your PHP so that `allow_url_fopen` is disabled.
2. Visit **WooCommerce ▸ Settings ▸ Products ▸ Downloadable Products**.
3. Set the **File Download Method** to **Force Downloads**.
4. Enable the new _"Allow using redirect mode as a last resort"_ option.
5. Add a remote file to one of your downloadable products (remote := hosted on another site).

Testing

1. Try purchasing and downloading.
2. With _"Allow using redirect mode as a last resort"_ enabled, the download should work (but via a redirect).
3. Try again with _"Allow using redirect mode as a last resort"_ disabled, the download should not work.

Other aspects

1. See also this [alternative set of testing steps](https://github.com/woocommerce/woocommerce/pull/30294#issuecomment-884280912) (documented in a comment, below).
2. If fallbacks (to redirect mode) take place, an entry should be recorded in the logs to document it.
3. When "Redirect Only" is selected, the content of the resulting admin notice that renders (to warn that the method is deprecated) has been updated to reflect this change.

### Other information

* As an alternative, there is [another draft PR](https://github.com/woocommerce/woocommerce/pull/30292/) which, like this PR, adds logging—but otherwise essentially reverts things such that the previous fallback logic is always enabled.
* If we accept this change, we may need to adjust the following resources (not exhaustive):
    * [Digital Download Product Handling](https://docs.woocommerce.com/document/digital-downloadable-product-handling/)
    * [Amazon S3 Storage Docs](https://docs.woocommerce.com/document/amazon-s3-storage/)
    * Other extensions? The deprecation notice (see above screenshot) mentions Google Drive, for instance, but I'm unsure which extension that relates to.

### Changelog entry

> Fix - Add a new option allowing product downloads to be served using redirects as a last resort. #30288

### CODE REVIEW

**Comment by barryhughes** [comment]
:memo: One [failing E2E test](https://github.com/woocommerce/woocommerce/blob/3f869efe06b32462cea259b836f48933de3d76df/tests/e2e/core-tests/specs/merchant/wp-admin-settings-product.test.js#L14), which I still need to review and update.

File: includes/admin/settings/class-wc-settings-products.php [hunk 1]
```diff
@@ -386,6 +386,16 @@ protected function get_settings_for_downloadable_section() {
 					'autoload' => false,
 				),
 
+				array(
+					'desc'          => __( 'Allow using redirect mode as a last resort', 'woocommerce' ),
```
Comment (vedanshujain) [inline includes/admin/settings/class-wc-settings-products.php:390]: Perhaps we can change the string to `redirect mode (insecure)` to be consistent with labelling above? wdyt?

File: includes/admin/settings/class-wc-settings-products.php [hunk 2]
```diff
@@ -386,6 +386,16 @@ protected function get_settings_for_downloadable_section() {
...
+					'id'            => 'woocommerce_downloads_redirect_fallback_allowed',
+					'type'          => 'checkbox',
+					'default'       => 'no',
+					'desc_tip'      => __( 'If the "Force Downloads" or "X-Accel-Redirect/X-Sendfile" download method is selected but does not work, the system will use the "Redirect" method as a last resort.', 'woocommerce' ),
```
Comment (vedanshujain) [inline includes/admin/settings/class-wc-settings-products.php:394]: Let's add a link to our support page https://docs.woocommerce.com/document/digital-downloadable-product-handling/  as well

**Review by vedanshujain — COMMENTED** [review]
Adding some minor comments related to messaging.

File: includes/admin/settings/class-wc-settings-products.php (hunk 1 above)
Comment (barryhughes) [reply includes/admin/settings/class-wc-settings-products.php]: Updated :+1:

File: includes/admin/settings/class-wc-settings-products.php (hunk 2 above)
Comment (barryhughes) [reply includes/admin/settings/class-wc-settings-products.php]: Updated :+1:

**Comment by Konamiman** [comment]
@barryhughes I have followed the testing instructions and it works fine. I have also tested as follows:

1. Configure PHP so that `allow_url_fopen` is enabled.
2. Configure **File Download Method** as **X-Accel-Redirect/X-Sendfile** (without having the required module installed)
2. Add a locally hosted file to the download product.
3. Purchase.
4. Download the file, it should work.
5. Verify that a `WARNING (file URL) could not be served using the X-Accel-Redirect/X-Sendfile method. A Force Download will be used instead.` message has been added to the logs.

Maybe you want to add this to the testing instructions.

**Comment by barryhughes** [comment]
📝 Quick note on E2E tests—they don't seem to relate to this change. At time of writing both fails are from `specs/front-end/product-browse-search-sort.test.js`:

* _Search, browse by categories and sort items in the shop › should let user search the store_
* _Search, browse by categories and sort items in the shop › should let user browse products by categories_

However, by creating a draft PR that is 1:1 with current trunk (will clean it up later) I can see [exactly the same fails](https://github.com/woocommerce/woocommerce/pull/30332/checks?check_run_id=3128663022).

**Review by Konamiman — APPROVED** [review]
