### PR TITLE
Fix product prices not being updated on scheduled sale automatically.

### LINKED ISSUE #41569: Scheduling issue
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

I schedule a 'sale' in my woocommerce shop. When the sale goes live, it doesn';t show the sale price (even though I've added it to the 'sale' field, but it still shows the normal price. As soon as I switch off the scheduling though, it shows the sale price.

Images available here:
https://we.tl/t-I7yUGSz78b

Mark

### Expected behavior

Should show sale price

### Actual behavior

Doesn't

### Steps to reproduce

list an item
put a sale price in
Schedule it
When live, it shows now scheduled sale price

### WordPress Environment

Shop

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by vedanshujain**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

This PR essentially reverts #39948, and there closes #41569, but reopens #34696.

In 39948, we stopped clearing the sales start date, when a sale is supposed to be started. However, this had an unintended consequence, in that we used the clearing of the sales start date prop as a trigger to update the product price to the sale price. So this broke the product sale price updation flow when a product sale is scheduled sometime in the future.

I tried using the price change as a trigger, instead of clearing the scheduled date param, but that means we will over write the product price, either with the sale price or with the regular price whenever the price is changed. This can also have unintended consequences, especially if someone is using the `_price` prop as a temporary active product price, which will then become a no-op unless a regular price is also changed.

Ultimately, I am opting to revert the PR, and perhaps we can use custom product meta to store sales schedules which can target 34696 instead of this fix.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Create a new product, set the regular price to 100, sale price to 50. Set the sale schedule to start few days in future. Note the product ID of this product. 
2. Go to the product listing page, and verify that the listed product price is 100 (and not 50).
3. Via WP CLI (`wp shell`), update the product schedule sales start date to sometime in the past and run the sale cron, like so:
```php
// XXX should be replaced the by product ID from step 1
$p = wc_get_product( XXX ); 

// Update the sale start date to sometime in past directly
update_post_meta( $p->get_id(), '_sale_price_dates_from', time() - 1000 );

// Call the sale schedule cron job manually.
wc_scheduled_sales();
```
5. Refresh the product list page again, you should now see sale prices for the product.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce/includes/data-stores/class-wc-product-data-store-cpt.php [hunk 1]
```diff
@@ -647,7 +647,15 @@ protected function handle_updated_props( &$product ) {
...
 
-			if ( in_array( 'date_on_sale_from', $this->updated_props, true ) || in_array( 'date_on_sale_to', $this->updated_props, true ) || in_array( 'regular_price', $this->updated_props, true ) || in_array( 'sale_price', $this->updated_props, true ) || in_array( 'product_type', $this->updated_props, true ) ) {
+			/**
+			 * It's tempting to add a check for `_price` in the updated props, so that when `wc_scheduled_sales` is called, we don't have to rely on `date_on_sale_from` being present in the list of updated props.
+			 *
+			 * However, it has a side effect of overriding the `_price` meta value with the `_sale_price` meta value when product is in sale, or with `_regular_price` meta value when product is not in sale. This is not desirable, because `_price` can also be set as a temporary active price for a product, and we don't want to override it.
+			 *
+			 * If we want to preserve previous sales schedules, a better way would be to store them in dedicated meta keys as logs.
+			 */
+			$product_price_props = array( 'date_on_sale_from', 'date_on_sale_to', 'regular_price', 'sale_price', 'product_type' );
```
Comment (vedanshujain) [inline plugins/woocommerce/includes/data-stores/class-wc-product-data-store-cpt.php:657]: Note that this and the next line is just simplifying what we were doing earlier, there is no functional change.

**Review by jorgeatorres — APPROVED** [review]
LGTM. Thank you @vedanshujain!

Confirmed (via CLI) that scheduled job does take care of changing the price and that in `trunk` that wasn't happening.
