### PR TITLE
Skip serialization for customer meta and be more defensive around loading it.

### LINKED ISSUE #47485: Checkout block shows warning `Warning: foreach() argument must be of type array|object, string given` when a guest session is loaded after upgrading to 8.9
#### Issue

Warning shown when loading the Checkout block in WC 8.9 with a guest session created in 8.8.

`Warning: foreach() argument must be of type array|object, string given in wp-content/plugins/woocommerce/includes/data-stores/class-wc-customer-data-store-session.php on line 152`

It is potentially linked to https://github.com/woocommerce/woocommerce/pull/46762/files#diff-578ec004cc2b40bb0b5b7d4901dc51c209cc8a76456b588cbcbc12b693757466

#### Reproduction steps

1. Be on WC 8.8.3 with no other plugins installed
2. Open an incognito window and add an item to your cart. Go to the Checkout block and check out as a guest.
3. Add an item to the cart and go to the Checkout block.
4. In your main window, upgrade to WC 8.9
5. In the incognito window, refresh the Checkout page.
6. The warning will be shown

### PR DESCRIPTION
**Pull request by senadir**
This PR skips customer meta data serialization as we already serialize data when doing `session->set`, it's also more defensive around loading it and only loop over it if it's an array.

Closes https://github.com/woocommerce/woocommerce/issues/47485

### How to test the changes in this Pull Request:

// From 8.8.x, json_decode to nothing:
1. In WooCommerce 8.8.x, logged out, start a session, add an item to Cart, go to checkout, and fill out the fields.
2. Update to this PR, refresh checkout, whatever fields you filled should still be there, there shouldn't be any warnings or errors.

// From 8.9.0, maybe_serialize to nothing
1. In WooCommerce 8.9.x, logged out, start a session, add an item to Cart, go to checkout, and fill out the fields.
2. Update to this PR, refresh checkout, whatever fields you filled should still be there, there shouldn't be any warnings or errors.

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

Fix warning when loading guest sessions from previous sessions.

#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce/includes/data-stores/class-wc-customer-data-store-session.php [hunk 1]
```diff
@@ -94,29 +94,27 @@ public function save_to_session( $customer ) {
...
+				$allowed_keys      = apply_filters( 'woocommerce_customer_allowed_session_meta_keys', array(), $customer );
+				$session_value     = array_map(
+					function ( $meta_data ) {
+						// Data comes to us a WC_Meta_Data, we cast it to an array to ensure it is serializable when doing WC()->session->set.
+							return array(
+								'key'   => $meta_data->key,
+								'value' => $meta_data->value,
+							);
+					},
+					array_filter(
```
Comment (wavvves) [inline plugins/woocommerce/includes/data-stores/class-wc-customer-data-store-session.php]: Instead of using `array_map` and `array_filter` combined, for performance reasons, can we just foreach once and populate the `$session_value`?

Comment (opr) [reply plugins/woocommerce/includes/data-stores/class-wc-customer-data-store-session.php]: I agree but I feel this is outside the scope of this PR.

File: plugins/woocommerce/includes/data-stores/class-wc-customer-data-store-session.php [hunk 2]
```diff
@@ -147,8 +145,8 @@ public function read( &$customer ) {
 				}
 				if ( ! empty( $data[ $session_key ] ) && is_callable( array( $customer, "set_{$function_key}" ) ) ) {
 					if ( 'meta_data' === $session_key ) {
-						$meta_data_values = maybe_unserialize( $data[ $session_key ] );
-						if ( $meta_data_values ) {
+						$meta_data_values = is_serialized( $data[ $session_key ], true ) ? maybe_unserialize( $data[ $session_key ] ) : $data[ $session_key ];
```
Comment (opr) [inline plugins/woocommerce/includes/data-stores/class-wc-customer-data-store-session.php]: I see `maybe_unserialize` calls `is_serialized` with strict mode `true` anyway, so is the change on this line needed?

I see this line doing basically the same thing as a direct call to `maybe_unserialize`. Line below is definitely needed though.

**Review by opr — CHANGES_REQUESTED** [review]
I checked this out and the changes work as expected, no errors or warning.

Just not sure on checking `is_serialized` first as it would run twice when data is serialized, I'd like you to look at that in a little more detail.

File: plugins/woocommerce/includes/data-stores/class-wc-customer-data-store-session.php (hunk 2 above)
Comment (senadir) [reply plugins/woocommerce/includes/data-stores/class-wc-customer-data-store-session.php]: I think we can skip this all together, this is intended for Additional Fields with individual fields which didn't ship yet, so we can just check if it's an array.

If it was serialized before, it will be overridden after first load.

**Review by opr — APPROVED** [review]
- Discussed that the data will only be serialized if a store is using 8.9.0
- After upgrading to 8.9.1 if it was serialized before, it will be overridden after first load.
- Additional fields filled in for _existing_ carts will need to be re-filled. This is low-impact and low-risk.

Given the above, happy to approve this change. Thanks for working on it Nadir.
