### PR TITLE
[Experimental] Product Filter: Price (Beta) block: Prevent invalid price range selection in Product Filter Price block

### LINKED ISSUE #45361: Product Filter: Price (Beta) - Invalid Price Range Selection
### Describe the bug

Shoppers can select a maximum price lower than the minimum price (or vice-versa) through both the slider and input fields.

This issue was initially mentioned by @imanish003 in https://github.com/woocommerce/woocommerce/pull/45327#pullrequestreview-1919489433

### Expected behavior

When using the "Product Filter: Price (Beta)" block, the user should only be able to select a valid price range where the minimum price is less than or equal to the maximum price. This applies to both the slider and input field interactions.

### Actual behavior

Currently, shoppers can choose a maximum price value that is lower than the minimum price selected.

### Steps to reproduce

1. Navigate to Single Product template (Appearance > Editor > Templates > Product Catalog template - or any archive template).
2. Click on "Edit" to open the WordPress editor.
3. In the editor, you should see a block inserter icon or an option to "Add Block". Click on it.
4. Search for "Product Filter: Price (Beta)" in the block inserter or browse the available blocks until you find them. Add it to your content.
5. Click on Save to save the changes.
6. Visit the Shop page (`/shop`).
7. Move the max price to somewhere in the middle of the price slider. Move the min price past the selected max price.
8. Check that this invalid price range is accepted and the products are filtered according to this range.

cc: @dinhtungdu

### PR DESCRIPTION
**Pull request by thealexandrelara**
### Changes proposed in this Pull Request:

This PR adds checks to prevent shoppers from using invalid price range selections, such as selecting a minimum price that is higher than the max price. It also uses the `getElement` method from the Interactivity API to get the element that triggered the update price event and force the correct value to be set to the input.

Closes #45361.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Navigate to Single Product template (Appearance > Editor > Templates > Product Catalog template - or any archive template).
2. Click on "Edit" to open the WordPress editor.
3. In the editor, you should see a block inserter icon or an option to "Add Block". Click on it.
4. Search for "Product Filter: Price (Beta)" in the block inserter or browse the available blocks until you find them. Add it to your content.
5. Click on Save to save the changes.
6. Visit the Shop page (`/shop`).
7. Move the max price to somewhere in the middle of the price slider. Move the min price past the selected max price.
8. Make sure that only valid price range is accepted and the products are filtered according to this range.

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 
Fix an issue where shoppers could select invalid price ranges in the Product Filter: Price (Beta) block

#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce-blocks/assets/js/blocks/product-filter/inner-blocks/price-filter/frontend.ts [hunk 1]
```diff
@@ -70,17 +70,28 @@ store< PriceFilterStore >( 'woocommerce/product-filter-price', {
...
+			// In some occasions the input element is updated with the incorrect value.
+			// By using the element that triggered the event, we can ensure the correct value is used for the input.
+			const element = getElement();
+			if ( type === 'min' ) {
+				element.ref.value = currentMinPrice;
+			}
+
+			if ( type === 'max' ) {
+				element.ref.value = currentMaxPrice;
+			}
```
Comment (dinhtungdu) [inline plugins/woocommerce-blocks/assets/js/blocks/product-filter/inner-blocks/price-filter/frontend.ts:93]: Nice solution!

File: plugins/woocommerce-blocks/assets/js/blocks/product-filter/inner-blocks/price-filter/frontend.ts [hunk 2]
```diff
@@ -70,17 +70,28 @@ store< PriceFilterStore >( 'woocommerce/product-filter-price', {
...
 			const currentMaxPrice =
 				type === 'max'
 					? Math.max(
 							Number.isNaN( value ) ? maxRange : value,
-							minRange + 1
+							minPrice
 					  )
 					: maxPrice;
 
+			// In some occasions the input element is updated with the incorrect value.
```
Comment (dinhtungdu) [inline plugins/woocommerce-blocks/assets/js/blocks/product-filter/inner-blocks/price-filter/frontend.ts:84]: In my case, when the min and max price are equal, if I continue to move the max price to lower than the min price, the prices in the text inputs are correct, but the thumb doesn't return to the correct position.

**Review by dinhtungdu — APPROVED** [review]
Code looks good and tested well! Thanks for working on this PR! LGTM 🚢
