### PR TITLE
Make qty input box visible when min_qty = max_qty

### LINKED ISSUE #34280: Cannot see product quantity when min-qty and max-qty is same
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

This bug was found in https://github.com/woocommerce/woocommerce-min-max-quantities/issues/176 and is reported here as a core issue.

The quantity input box is not shown when a product's min qty and max qty are the same. The code responsible for this can be found [here](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/templates/global/quantity-input.php#L20-L25). I think the reasoning behind it could be that if the user cannot set the quantity of the product anyways, then what's the point of showing input box. 

However, this creates an issue that the user does not know what the quantity is, so IMO it's better if the quantity input is disabled when `min_qty=max_qty`.

### Expected behaviour

Input quantity is shown when min_qty=max_qty

### Actual behavior

Input quantity is not shown when min_qty=max_qty

### Steps to reproduce

1. Add https://github.com/woocommerce/woocommerce-min-max-quantities/ plugin.
2. Create a simple product with min_qty=max_qty=5
3. Add product to the cart.

You will see that the qty input box is no longer visible. If you change the min qty to 4, you'll be able to see the quantity input box.

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://woo.test
Site address (URL): https://woo.test
WC Version: 6.9.0
REST API Version: ✔ 6.9.0
WC Blocks Version: ✔ 8.0.0
Action Scheduler Version: ✔ 3.4.0
Log Directory Writable: ✔
WP Version: 6.0.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.23.0
PHP Version: 7.4.29
PHP Post Max Size: 0 B
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.81.0
OpenSSL/3.0.2

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.3.35-MariaDB-1:10.3.35+maria~focal
Max Upload Size: 0 B
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 6.9.0
WC Database Prefix: wp_
Total Database Size: 7.38MB
Database Data Size: 5.36MB
Database Index Size: 2.02MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.13MB + Index: 0.14MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.14MB + Index: 0.14MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.09MB + Index: 0.06MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.06MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mail_catcher_logs: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 2.03MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.45MB + Index: 0.41MB + Engine InnoDB
wp_posts: Data: 0.09MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wcpv_commissions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcpv_per_product_shipping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 24
page: 7
post: 2
product: 19
product_variation: 13
revision: 4
shop_coupon: 1
shop_order: 109
wp_global_styles: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (6) ###

Query Monitor: by John Blackbourn – 3.9.0
Debug Bar: by wordpressdotorg – 1.1.3
WooCommerce Min/Max Quantities: by WooCommerce – 2.4.25
WooCommerce: by Automattic – 6.9.0-dev
WP Crontrol: by John Blackbourn & crontributors – 1.14.0
Mail logging - WP Mail Catcher: by James Ward – 2.0.5

### Inactive Plugins (4) ###

WooCommerce EU VAT Number: by WooCommerce – 2.5.0
WooCommerce GoCardless Gateway: by WooCommerce – 2.4.19
WooCommerce Product Vendors: by WooCommerce – 2.1.62
WooCommerce Square: by WooCommerce – 3.1.0

### Dropin Plugins (1) ###

db.php: Query Monitor Database Class (Drop-in)

### Must Use Plugins (1) ###

temp.php: by  –

### Settings ###

API Enabled: –
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔

### WC Pages ###

Shop base: #6 - /shop/
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 4.1.1 (update to version 4.1.2 is available)
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
experimental-products-task
experimental-import-products-task
experimental-fashion-sample-products
experimental-product-tour
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
wc-pay-promotion
wc-pay-welcome-page
wc-pay-subscriptions-page

Disabled Features: minified-js
settings

Daily Cron: ✔ Next scheduled: 2022-08-11 18:07:14 +05:30
Options: ✔
Notes: 32
Onboarding: completed

### Action Scheduler ###

Complete: 372
Oldest: 2022-07-21 13:44:33 +0000
Newest: 2022-08-11 09:53:26 +0000

Pending: 2
Oldest: 2022-08-11 10:11:48 +0000
Newest: 2022-08-12 09:08:12 +0000

### Status report information ###

Generated at: 2022-08-11 15:40:59 +05:30
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by kirtangajjar**
### All Submissions:

-   [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
-   [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
-   [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change?

### Changes proposed in this Pull Request:

This change makes the input for quantity visible when `min_qty = max_qty`. The dropdown will be disabled so that users won't be able to change it. 

Closes #34280.

### How to test the changes in this Pull Request:

1. Add https://github.com/woocommerce/woocommerce-min-max-quantities.
2. Create a simple product with min_qty=max_qty. 
3. Go add the product page. You will be able to see the quantity input there.

### Other information:

-   [x] Have you added an explanation of what your changes do and why you'd like us to include them?
-   [x] Have you written new tests for your changes, as applicable?
-   [x] Have you successfully run tests with your changes locally?
-   [x] Have you created a changelog file for each project being changed, ie `pnpm changelog add --filter=<project>`?

### FOR PR REVIEWER ONLY:

-   [x] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

File: plugins/woocommerce/templates/global/quantity-input.php [hunk 1]
```diff
@@ -23,29 +23,43 @@
 		<input type="hidden" id="<?php echo esc_attr( $input_id ); ?>" class="qty" name="<?php echo esc_attr( $input_name ); ?>" value="<?php echo esc_attr( $min_value ); ?>" />
 	</div>
 	<?php
-} else {
-	/* translators: %s: Quantity. */
-	$label = ! empty( $args['product_name'] ) ? sprintf( esc_html__( '%s quantity', 'woocommerce' ), wp_strip_all_tags( $args['product_name'] ) ) : esc_html__( 'Quantity', 'woocommerce' );
+}
```
Comment (barryhughes) [inline plugins/woocommerce/templates/global/quantity-input.php]: It seems a little odd that we are still outputting a hidden input (lines 20-26). Additionally, this leads to us having two inputs with the same ID on the same page (something to avoid where possible).

File: plugins/woocommerce/templates/global/quantity-input.php [hunk 2]
```diff
@@ -23,29 +23,43 @@
...
+/* translators: %s: Quantity. */
+$label = ! empty( $args['product_name'] ) ? sprintf( esc_html__( '%s quantity', 'woocommerce' ), wp_strip_all_tags( $args['product_name'] ) ) : esc_html__( 'Quantity', 'woocommerce' );
+?>
+<div class="quantity">
+	<?php
+	/**
+	 * Hook to output something before quantity input field
+	 *
+	 * @since 3.6.0
```
Comment (barryhughes) [inline plugins/woocommerce/templates/global/quantity-input.php]:
```suggestion
	 * Hook to output something before the quantity input field.
	 *
	 * @since 7.0.0
```

(Unless I'm mistaken, this hook is newly introduced, so the version tag should reflect that. Sidenote: at time of writing GH is highlighting and transforming `@since` in a weird way ... but I believe that's presentational only.)

**Review by barryhughes — CHANGES_REQUESTED** [review]
Thanks for submitting this!

I left a note about a couple of small changes we should look into, and we should also bump the `@version` tag on line 15 to `7.0.0`.

File: plugins/woocommerce/changelog/fix-GH-34280 [hunk 3]
```diff
@@ -0,0 +1,4 @@
+Significance: minor
+Type: fix
+
+Fix qty input not showing when min_qty = max_qty
```
Comment (barryhughes) [inline plugins/woocommerce/changelog/fix-GH-34280]:
```suggestion
When the minimum and maximum quantity are identical, render the quantity input and set it to disabled.
```

☝🏽 Possible re-wording that might be easier for non-developers to digest.

File: plugins/woocommerce/templates/global/quantity-input.php (hunk 1 above)
Comment (manospsyx) [reply plugins/woocommerce/templates/global/quantity-input.php]: Might help: https://github.com/woocommerce/woocommerce/commit/846e1ca25c078f9803f955e14617f3646d7777f3

If I understand correctly, the goal of this PR is essentially to revert this old commit ^. I agree that there's no need to preserve the hidden input -- but it might make sense to think about Mike's motivation behind doing that old commit.

Comment (kirtangajjar) [reply plugins/woocommerce/templates/global/quantity-input.php]: @barryhughes @manospsyx We have hidden input because when minimum and maximum quantity are same, we do have a dud quantity field input box, which we do by setting the [disabled attribute to true](https://github.com/woocommerce/woocommerce/pull/34282/files#diff-5fe95244e467e57c0cf6ade504e454fb98ae2f474351186612da8e096eed4195R42) on it. If a field has `disabled` attribute, the browser will not send that field's value to the backend on form submission. In that case, we rely on the hidden field to ensure that the quantity field value is sent to the backend as expected.

Comment (barryhughes) [reply plugins/woocommerce/templates/global/quantity-input.php]: Understood, thanks! 

Even though the name:value of a disabled input will not be submitted, this still leads us to have a duplicate ID in the DOM.  Not a huge problem, but it's still something we should address if there is a reasonably straightforward way of doing so. What do you think of using the `readonly` property (instead of `disabled`)? This means we can have a single input, the value will be submitted, and it will not normally be possible for end-users to modify it.

Comment (barryhughes) [reply plugins/woocommerce/templates/global/quantity-input.php]: ✍🏽 `wp_readonly()` is a helper function we could take advantage of for this.

Comment (kirtangajjar) [reply plugins/woocommerce/templates/global/quantity-input.php]: @barryhughes Absolutely, that does make sense. Just yesterday, before going to bed, I realised I could've tried `readonly` there, huh 🤔.

Comment (barryhughes) [reply plugins/woocommerce/templates/global/quantity-input.php]: Great—I think that will be a nice clean solution (and will reduce the total amount of code)—and we can then move this toward completion.

**Review by barryhughes — CHANGES_REQUESTED** [review]
Just circling back here to note we'd still ideally make a further change [as discussed here](https://github.com/woocommerce/woocommerce/pull/34282/files#r964589456)—this should then be ready to merge.

**Comment by kirtangajjar** [comment]
@barryhughes: Yes, Unfortunately, my work schedule has been a bit tight, so getting time for it has proved difficult. I'll try to make that change when time allows. 

Alternatively, if you or someone else would like to make this change to the PR, please feel free to do so. I can even provide access to my repo if required(I'm not even sure if it's needed, but I'm ready if that's the case).

**Comment by barryhughes** [comment]
No problem, I can make a further commit to wrap this up—thanks for confirming!

**Comment by barryhughes** [comment]
Updated per discussion, so requesting fresh review.

---

With this further change, when the quantity cannot be changed, the quantity selector will be a visible but readonly text field. So, when the quantity cannot be changed:

- This makes the quantity visible (which was the original goal).
- It avoids outputting two different input fields (one hidden, one disabled—as in an earlier iteration).
- By switching the field type to text, browsers generally will not render increment/decrement buttons (which might be confusing, given the value cannot be changed).

readonly-non-readonly

---

To test, please follow the original PR testing instructions. Or if you prefer not to install and activate an additional plugin, add a snippet like the following example to a mu-plugin file or other handy spot:

```php
$return_an_integer = static function () {
	static $integer = 0;
	$integer = 0 === $integer ? rand( 1, 10 ) : $integer;
	return $integer;
};

add_filter( 'woocommerce_quantity_input_max', $return_an_integer );
add_filter( 'woocommerce_quantity_input_min', $return_an_integer );
```

With the snippet in place, the quantity selector on single product pages should go into 'readonly mode'.

**Comment by barryhughes** [comment]
✍🏽 Quick note on the failing **Highlight Templates and Hooks Change** check—since it would otherwise be relevant—it's failing because of [this problem](https://github.com/woocommerce/woocommerce/issues/33286) (impacts all or most community PRs).

**Comment by jimjasson** [comment]
Hey @barryhughes, 

Our team @woocommerce/somewherewarm is now maintaining Min/Max Quantities and I stumbled upon this issue. I was wondering if there is any pending work still left in this PR, and if there is, how can we help? 

Thanks!

**Comment by barryhughes** [comment]
Hi @jimjasson—it's in the code review queue and really is just waiting on any final feedback and/or approval (though it started as a community PR, I made a few small amendments so it needed a second reviewer—cc @vedanshujain). If you have space definitely feel free to give it a look and leave any notes you might have :+1:

**Comment by jimjasson** [comment]
Hey @barryhughes,

The changes look OK to me. The only feedback I have is that the way we are displaying the quantity of products with Min = Max Quantity in the cart is slightly different than how we handle Sold Individually products (which essentially have Min = Max Quantity = 1).

Here's an example:
Markup 2022-10-12 at 14 53 35

**Comment by barryhughes** [comment]
Good catch, @jimjasson! I guess there was an existing discrepancy (since, even without this change, the way things render when a product is sold individually vs having a min and max of 1 were not consistent). I'll update so that sold individually also outputs a readonly input (but let me know if you disagree with this approach).

**Comment by barryhughes** [comment]
sold-individually-min-max
:point_up: Following discussion, I pushed a further change in 8577ec58 such that the quantity renders the same way, whether the product is sold individually or min and max are both set to 1 (and of course, this will also be consistent with cases where min = max and max > 1).

**Comment by jimjasson** [comment]
Awesome, @barryhughes -- this looks good to me!

**Comment by barryhughes** [comment]
Re-running some failed checks...

**Comment by barryhughes** [comment]
Required PHPCS check [failing again](https://github.com/woocommerce/woocommerce/actions/runs/3238522680/jobs/5319271953), with:

```
 Error: Error: Command failed: plugins/woocommerce/vendor/bin/phpcs --report=checkstyle --standard=phpcs.xml plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableFieldQuery.php plugins/woocommerce/src/Internal/DependencyManagement/ServiceProviders/FeaturesServiceProvider.php plugins/woocommerce/src/Internal/Features/FeaturesController.php plugins/woocommerce/src/Utilities/FeaturesUtil.php plugins/woocommerce/src/Utilities/PluginUtil.php plugins/woocommerce/tests/php/helpers/HPOSToggleTrait.php plugins/woocommerce/tests/php/includes/wc-user-functions-test.php plugins/woocommerce/tests/php/src/Internal/Features/FeaturesControllerTest.php plugins/woocommerce/tests/php/src/Utilities/PluginUtilTests.php
```

**Review by barryhughes — APPROVED** [review]

**Comment by jimjasson** [comment]
@barryhughes 

We ran our extensions' e2e tests with the latest WooCommerce beta, which includes the changes introduced by this PR, and found an issue. 

Composite Products uses the quantities of each component to calculate the total Composite Price -- the component subtotal is calculated like so: `price of selected product * component quantity`. 

After this set of changes, the `quantity-input.php` template was updated and some attributes, such as min/max, are not added to the quantity selector element if the minimum and maximum quantities are identical: https://github.com/woocommerce/woocommerce/commit/a5814f1bc70f5b174a6a1195a18615ffc3b843b4#diff-5fe95244e467e57c0cf6ade504e454fb98ae2f474351186612da8e096eed4195R50

I was wondering if you could provide some more details about why this is required. If I temporarily remove the `if ( ! $is_readonly )` validation that determines if the min/max attributes will be added to the element, then:
- Composite Products calculates prices correctly.
- The original issue that this PR resolves continues to be resolved.

**Comment by barryhughes** [comment]
Hi @jimjasson,

Though it seems we only merged this a little over a month ago, I've probably forgotten some of the fine detail already ... but here goes 😬 

> After this set of changes, the quantity-input.php template was updated and some attributes, such as min/max, are not added to the quantity selector element if the minimum and maximum quantities are identical ... I was wondering if you could provide some more details about why this is required.

I don't think it is required as such. As best I can recall, the reasoning was something like this: if the input is `readonly`, then we don't want to give the impression that the value can be changed. 

There are lots of ways we and the browser can communicate this to users (CSS, etc) but in support of this goal we also decided to switch the input from `type="number"` to `type="text"`. We did this because most browsers will continue to render increment/decrement (arrow) buttons for a numeric input, suggesting mutability, even when it is `readonly`.

Building on that, the `min` and `max` attributes don't really make sense when the input type is `text` (they are only applicable for [types such as `number`, `date`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Input#max), etc). So, identifying them as being unnecessary in this context, we stopped rendering them—hence they were moved within the `if {}` block you identified.

Of course, we didn't detect any problems when testing this change and didn't anticipate the problem you outlined with Composite Products. Some options:

- We could restore `min` and `max` attributes even when the input is `text`/`readonly`. This is easy to do, and I think it would also be safe. If this is the path we prefer, perhaps we should discuss how quickly it is needed (do we need a code freeze exception, etc)?
- *Perhaps* it is easier and faster to update Composite Products so that when `min` and `max` are missing, it simply uses the `value` instead?

Let me know your thoughts, here or in team chat, and we can work on resolving this.

Sorry for the disruption!

**Comment by jimjasson** [comment]
Hey @barryhughes , 

Thank you for your detailed analysis of this! 

I had a look at the Composite Products script and I noticed that it automatically creates the minimum/maximum attributes if the quantity input is of type `hidden`: https://github.com/woocommerce/woocommerce-composite-products/blob/master/resources/js/frontend/step_factory.js#L1774-L1777

After this PR, the input type has changed from `hidden` to `text` when the minimum quantity is equal to the maximum. I think that we can update this validation to look for `text` or `! number` instead of hidden. 

Let me take @manospsyx opinion on this too.

**Comment by barryhughes** [comment]
(Internal conversation p1669371133940499-slack-CNA89KY6M)

We'll make a change on this side. I'll follow-up with a fresh PR and tag you there!

**Comment by andreus1610** [comment]
With the last Woocommerce update (7.2.0) products sold individually show the quantity at 1.
How can I hide the quantity if product is sold individually (as it was before)?

how_hide_quantity

**Comment by barryhughes** [comment]
Hi @andreus1610,

Using a method of your choosing (one option would be the **[Appearance ▸ Customize ▸ Additional CSS](https://docs.themeinwp.com/docs/blogging/customizer-options-and-setups/additional-css/)** tool) you could add a custom CSS rule like the following:

```css
.product.sold-individually input.qty {
	display: none;	
}
```

This should hide the quantity input within single product pages, where the product is sold individually, without impacting other products.

**Comment by andreus1610** [comment]
> Hi @andreus1610,
> 
> Using a method of your choosing (one option would be the **[Appearance ▸ Customize ▸ Additional CSS](https://docs.themeinwp.com/docs/blogging/customizer-options-and-setups/additional-css/)** tool) you could add a custom CSS rule like the following:
> 
> ```css
> .product.sold-individually input.qty {
> 	display: none;	
> }
> ```
> 
> This should hide the quantity input within single product pages, where the product is sold individually, without impacting other products.

Thanks @barryhughes it works! :)
