### PR TITLE
Cast multiselect and select keys as strings

### LINKED ISSUE #20568: Problem with integer-keyed values in WC_Settings_API::generate_multiselect_html and generate_select_html functions
**Describe the bug**
WC_Settings_API::generate_multiselect_html and generate_select_html functions fail if the key values for the selects are integers.

**To Reproduce**
1. Get a plugin that uses the generate_{type}_html functions, like https://github.com/afterpay/afterpay-woocommerce
2. Add a custom settings field that uses integers for values
3. The settings are saved correctly, but the saved values aren't shown.

**Expected behavior**
The saved value should be selected when loading the select or multiselect field, but it doesn't work. (Related to #18645 and #18651)

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
`
### WordPress Environment ###

Home URL: https://secure.healthymummy.local
Site URL: https://secure.healthymummy.local
WC Version: 3.4.2
Log Directory Writable: ✔
WP Version: ❌ 4.9.5 - There is a newer version of WordPress available (4.9.6)
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: –
Language: en_AU
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.29 (Ubuntu)
PHP Version: 7.2.5-0ubuntu0.18.04.1
PHP Post Max Size: 8 MB
PHP Time Limit: 0
PHP Max Input Vars: 1000
cURL Version: 7.58.0
OpenSSL/1.1.0g

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.1.29-MariaDB-6
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.4.0
WC Database Prefix: wp_
Total Database Size: 3907.81MB
Database Data Size: 2404.43MB
Database Index Size: 1503.38MB
wp_woocommerce_sessions: Data: 0.09MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_order_items: Data: 5.52MB + Index: 1.52MB
wp_woocommerce_order_itemmeta: Data: 47.58MB + Index: 47.69MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 2.52MB + Index: 1.52MB
wp_woocommerce_payment_tokenmeta: Data: 7.52MB + Index: 8.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
challenge_exercises: Data: 67.59MB + Index: 0.00MB
challenge_fitness_test_progress: Data: 11.52MB + Index: 0.00MB
challenge_members: Data: 0.02MB + Index: 0.00MB
challenge_photos: Data: 0.38MB + Index: 0.00MB
challenge_pledges: Data: 0.02MB + Index: 0.00MB
challenge_refer_friends: Data: 0.02MB + Index: 0.00MB
invenco_orders_tracking: Data: 0.02MB + Index: 0.02MB
invenco_shipment_email_log: Data: 0.02MB + Index: 0.00MB
newsletter_competition_submissions: Data: 1.52MB + Index: 0.00MB
sg_challenge_passcode: Data: 0.02MB + Index: 0.00MB
sg_custom_mealplanner: Data: 0.02MB + Index: 0.05MB
sg_fav_recipes: Data: 0.02MB + Index: 0.03MB
sg_mealplanner_ingredient_and_categories: Data: 0.02MB + Index: 0.00MB
sg_one_off_challenges: Data: 0.02MB + Index: 0.00MB
sg_paypal_cancellation_and_refunds: Data: 0.02MB + Index: 0.00MB
sg_paypal_ipn_log: Data: 0.02MB + Index: 0.00MB
sg_paypal_subscription_cancellations_and_refunds: Data: 0.02MB + Index: 0.00MB
sg_paypal_subscription_orders: Data: 0.02MB + Index: 0.02MB
sg_paypal_subscription_payments: Data: 0.02MB + Index: 0.00MB
temp1: Data: 7.52MB + Index: 0.00MB
temp2: Data: 0.23MB + Index: 0.00MB
wp_acf_fields: Data: 0.02MB + Index: 0.00MB
wp_acf_rules: Data: 0.02MB + Index: 0.00MB
wp_acf_values: Data: 0.02MB + Index: 0.00MB
wp_adrotate: Data: 0.05MB + Index: 0.00MB
wp_adrotate_blocks: Data: 0.02MB + Index: 0.00MB
wp_adrotate_groups: Data: 0.02MB + Index: 0.00MB
wp_adrotate_linkmeta: Data: 0.02MB + Index: 0.00MB
wp_adrotate_schedule: Data: 0.02MB + Index: 0.02MB
wp_adrotate_stats: Data: 0.31MB + Index: 0.22MB
wp_adrotate_tracker: Data: 0.02MB + Index: 0.03MB
wp_advanced_notifications: Data: 0.02MB + Index: 0.00MB
wp_advanced_notification_triggers: Data: 0.02MB + Index: 0.00MB
wp_affiliate_wp_affiliatemeta: Data: 0.30MB + Index: 0.34MB
wp_affiliate_wp_affiliates: Data: 0.30MB + Index: 0.08MB
wp_affiliate_wp_affiliates_backup20170922: Data: 0.11MB + Index: 0.02MB
wp_affiliate_wp_campaigns: Data: 0.00MB + Index: 0.00MB
wp_affiliate_wp_creatives: Data: 0.02MB + Index: 0.02MB
wp_affiliate_wp_customermeta: Data: 0.02MB + Index: 0.03MB
wp_affiliate_wp_customers: Data: 0.02MB + Index: 0.03MB
wp_affiliate_wp_payouts: Data: 1.52MB + Index: 0.13MB
wp_affiliate_wp_payouts_backup: Data: 1.52MB + Index: 0.09MB
wp_affiliate_wp_referrals: Data: 111.64MB + Index: 2.52MB
wp_affiliate_wp_referrals_20170926: Data: 48.58MB + Index: 0.00MB
wp_affiliate_wp_rest_consumers: Data: 0.02MB + Index: 0.02MB
wp_affiliate_wp_visits: Data: 0.02MB + Index: 0.02MB
wp_commentmeta: Data: 28.56MB + Index: 27.11MB
wp_comments: Data: 456.02MB + Index: 532.81MB
wp_csp3_subscribers: Data: 0.02MB + Index: 0.00MB
wp_cspv5_pages: Data: 0.02MB + Index: 0.00MB
wp_ebayaffinity_categories: Data: 1.52MB + Index: 0.34MB
wp_ebayaffinity_categories_bak: Data: 1.52MB + Index: 0.34MB
wp_ebayaffinity_itemspecific_mapping: Data: 0.02MB + Index: 0.02MB
wp_ebayaffinity_log: Data: 132.63MB + Index: 14.55MB
wp_ebayaffinity_pushtoken: Data: 0.02MB + Index: 0.02MB
wp_ebayaffinity_shiprules: Data: 0.02MB + Index: 0.00MB
wp_ebayaffinity_titlerules: Data: 0.02MB + Index: 0.00MB
wp_ebook_subscription_event_types: Data: 0.02MB + Index: 0.02MB
wp_ebook_subscription_log: Data: 0.02MB + Index: 0.00MB
wp_ebook_subscription_logs: Data: 7.52MB + Index: 0.00MB
wp_gf_addon_feed: Data: 0.02MB + Index: 0.02MB
wp_ia_savedcarts: Data: 84.55MB + Index: 0.00MB
wp_itsec_lockouts: Data: 0.02MB + Index: 0.08MB
wp_itsec_log: Data: 0.02MB + Index: 0.03MB
wp_itsec_temp: Data: 0.02MB + Index: 0.06MB
wp_iwp_backup_status: Data: 0.02MB + Index: 0.00MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_login_redirects: Data: 0.02MB + Index: 0.00MB
wp_mavis_settings: Data: 0.02MB + Index: 0.00MB
wp_options: Data: 4.44MB + Index: 0.73MB
wp_options_2: Data: 0.02MB + Index: 0.05MB
wp_ot_faq_categories: Data: 0.02MB + Index: 0.00MB
wp_ot_faq_questions: Data: 0.05MB + Index: 0.00MB
wp_pageflip: Data: 0.02MB + Index: 0.00MB
wp_pageflip_gallery: Data: 0.02MB + Index: 0.00MB
wp_pageflip_img: Data: 0.02MB + Index: 0.00MB
wp_postmeta: Data: 267.83MB + Index: 296.39MB
wp_posts: Data: 40.56MB + Index: 24.09MB
wp_propa_diaries: Data: 3.52MB + Index: 0.00MB
wp_propa_logs: Data: 0.02MB + Index: 0.00MB
wp_propa_measurements: Data: 19.55MB + Index: 36.61MB
wp_propa_profiles: Data: 6.52MB + Index: 5.52MB
wp_propa_summerchallenges: Data: 1.52MB + Index: 0.00MB
wp_propa_tips: Data: 0.02MB + Index: 0.00MB
wp_propa_usercompetitions: Data: 0.02MB + Index: 0.00MB
wp_recipe_schema_ingredients: Data: 0.02MB + Index: 0.00MB
wp_redirection_groups: Data: 0.02MB + Index: 0.03MB
wp_redirection_items: Data: 0.02MB + Index: 0.08MB
wp_redirection_logs: Data: 0.02MB + Index: 0.08MB
wp_redirection_modules: Data: 0.02MB + Index: 0.03MB
wp_rg_campaignmonitor: Data: 0.02MB + Index: 0.02MB
wp_rg_form: Data: 0.02MB + Index: 0.00MB
wp_rg_form_meta: Data: 0.42MB + Index: 0.00MB
wp_rg_form_view: Data: 0.02MB + Index: 0.03MB
wp_rg_incomplete_submissions: Data: 0.02MB + Index: 0.02MB
wp_rg_infusionsoft: Data: 0.02MB + Index: 0.02MB
wp_rg_lead: Data: 0.02MB + Index: 0.03MB
wp_rg_lead_detail: Data: 0.02MB + Index: 0.06MB
wp_rg_lead_detail_long: Data: 0.02MB + Index: 0.00MB
wp_rg_lead_meta: Data: 0.02MB + Index: 0.05MB
wp_rg_lead_notes: Data: 0.02MB + Index: 0.03MB
wp_shopp_address: Data: 54.61MB + Index: 6.52MB
wp_shopp_asset: Data: 0.02MB + Index: 0.00MB
wp_shopp_customer: Data: 17.55MB + Index: 6.03MB
wp_shopp_index: Data: 1.52MB + Index: 0.06MB
wp_shopp_meta: Data: 199.75MB + Index: 129.42MB
wp_shopp_price: Data: 0.13MB + Index: 0.03MB
wp_shopp_promo: Data: 0.09MB + Index: 0.02MB
wp_shopp_purchase: Data: 72.61MB + Index: 5.52MB
wp_shopp_purchased: Data: 107.64MB + Index: 42.09MB
wp_shopp_shopping: Data: 0.02MB + Index: 0.02MB
wp_shopp_summary: Data: 0.13MB + Index: 0.05MB
wp_stream: Data: 48.58MB + Index: 58.13MB
wp_stream_meta: Data: 133.67MB + Index: 189.00MB
wp_tantan_wordpress_s3_cache: Data: 0.02MB + Index: 0.00MB
wp_termmeta: Data: 0.09MB + Index: 0.11MB
wp_terms: Data: 0.09MB + Index: 0.09MB
wp_term_relationships: Data: 1.52MB + Index: 1.52MB
wp_term_taxonomy: Data: 0.09MB + Index: 0.11MB
wp_thm_challenge_users: Data: 4.52MB + Index: 5.52MB
wp_thm_churn_data: Data: 0.02MB + Index: 0.00MB
wp_thm_churn_data_month: Data: 0.06MB + Index: 0.00MB
wp_thm_iap_tokens: Data: 0.02MB + Index: 0.00MB
wp_transients: Data: 68.02MB + Index: 1.02MB
wp_usermeta: Data: 82.61MB + Index: 35.09MB
wp_users: Data: 3.52MB + Index: 4.55MB
wp_wafp_clicks: Data: 0.02MB + Index: 0.14MB
wp_wafp_commissions: Data: 0.02MB + Index: 0.14MB
wp_wafp_links: Data: 0.02MB + Index: 0.05MB
wp_wafp_payments: Data: 0.02MB + Index: 0.05MB
wp_wafp_responses: Data: 0.02MB + Index: 0.05MB
wp_wafp_transactions: Data: 0.02MB + Index: 0.27MB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_wc_gpf_render_cache: Data: 0.02MB + Index: 0.02MB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_bundled_itemmeta: Data: 2.52MB + Index: 4.02MB
wp_woocommerce_bundled_items: Data: 0.11MB + Index: 0.14MB
wp_woocommerce_gpf_google_taxonomy: Data: 1.52MB + Index: 0.00MB
wp_woocommerce_invenco: Data: 213.69MB + Index: 9.03MB
wp_woocommerce_preorder_orders: Data: 2.52MB + Index: 1.52MB
wp_woocommerce_preorder_orders_deferred: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_preorder_products: Data: 0.05MB + Index: 0.00MB
wp_woocommerce_termmeta: Data: 0.02MB + Index: 0.03MB
wp_wp125_ads: Data: 0.02MB + Index: 0.00MB
wp_wp_seo_404_links: Data: 0.11MB + Index: 0.08MB
wp_wp_seo_cache: Data: 0.02MB + Index: 0.00MB
wp_wp_seo_redirection: Data: 0.02MB + Index: 0.02MB
wp_wp_seo_redirection_log: Data: 0.08MB + Index: 0.00MB
wp_yarpp_related_cache: Data: 1.52MB + Index: 0.83MB
wp_yith_ywpar_points_log: Data: 10.52MB + Index: 0.00MB

### Post Type Counts ###

acf: 42
acf-field: 715
acf-field-group: 79
attachment: 18354
challenge-admin: 1
challenge-round: 40
exercisehub: 295
exerciseplanner: 1237
fbtab: 1
fl-builder-template: 4
gift_card: 91
ingredients: 666
mealplanner: 158
nav_menu_item: 99
omapi: 16
page: 180
payment_retry: 36638
post: 8
product: 714
product_variation: 315
qa_faqs: 22
recipe-schema: 1
recipehub: 3843
revision: 4142
scheduled-action: 52
shop_coupon: 329
shop_order: 16667
shop_order_refund: 161
shop_subscription: 5051
shopp_product: 323
slide: 5
slides: 5
smoothie_sub_popup: 3
thm_affwp_category: 7
video: 44
wafp-subscriptions: 255

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (72) ###

Gravity Forms: by rocketgenius – 2.2.1.2
AddressFinder: by Abletech – 1.2.9 – Not tested with the active version of WooCommerce
Advanced Custom Fields PRO: by Elliot Condon – 5.5.14
AffiliateWP - Groups: by Click Studio – 1.4.4
AffiliateWP - Lifetime Commissions: by Pippin Williamson and Andrew Munro – 1.2.4
AffiliateWP - Recurring Referrals: by Pippin Williamson and Andrew Munro – 1.6.1
AffiliateWP: by AffiliateWP
LLC – 2.1.4.1

AffiliateWP - Checkout Referrals: by AffiliateWP – 1.0.4 – Not tested with the active version of WooCommerce
AffiliateWP - Multi Level Affiliates: by Click Studio – 0.9.9
AffiliateWP - Order Details For Affiliates: by AffiliateWP – 1.1.3
WooCommerce Afterpay Gateway: by AfterPay – 1.3.1 – Not tested with the active version of WooCommerce
Akismet Anti-Spam: by Automattic – 4.0.3
BMI Calculator: by calculator.net – 1.0
Disable Password Change/Reset Notification: by Summit Creative – 1.0
Google Tag Manager for Wordpress: by Thomas Geiger – 1.7.2
eBook Library: by Mark Dave Alonzo – 1.0.0
Imsanity: by Jason Hinkle – 2.3.5
InfusedWoo Pro: by Mark Joseph – 3.8.6
Infusionsoft SDK: by Novak Solutions – 1.0.12
Gravity Forms Infusionsoft Add-On: by Katz Web Services
Inc. – 1.5.12

Log Viewer: by Markus Fischbacher – 14.05.04
Members: by Justin Tadlock – 2.0.2
Multiple Roles per User: by nikolov.tmw – 1
OPcache Dashboard: by Daisuke Takahashi(Extend Wings) – 0.3.1
OptinMonster API: by OptinMonster Team – 1.2.2
PB Woo Admin: by Mark Dave Alonzo – 1.0.0 – Not tested with the active version of WooCommerce
PixelYourSite PRO: by PixelYourSite – 6.3.4 – Not tested with the active version of WooCommerce
Postmark (Official): by Andrew Yates & Matt Gibbs – 1.9.2
ReferralCandy for WooCommerce: by ReferralCandy – 1.3.3 – Not tested with the active version of WooCommerce
Responsive Slider: by AlienWP – 0.1.8
Search by Algolia – Instant & Relevant results: by Algolia – 2.8.1
Secure HTML5 Video Player: by Lucinda Brown
Jinsoo Kang – 3.9

SG Mealplanner Customizer: by Zach Moon (Summit Group) – 0.1
Simple 301 Redirects: by Scott Nellé – 1.06
Stream: by XWP – 3.2.3
Swift Mailer: by  – 5.4.1
THM AffiliateWP Customizations: by David Marín – 0.0.1
THM API: by David Marín – 0.0.1
THM CampaignMonitor: by David Marín – 0.0.1
THM Challenge: by David Marín – 0.0.1
THM Core: by Saxon Landers – 0.0.1
THM In-App Purchases: by Saxon Landers – 0.0.1
THM Infusionsoft Customizations: by David Marín – 0.0.1
THM NewRelic: by David Marín – 0.0.1
THM PixelYourSite Additional IDs: by PixelYourSite (extracted from PixelYourSite Super Pack plugin) – 1.2.1
THM WooCommerce Customizations: by David Marín – 0.0.1
THM WooCommerce Coupons Overview: by David Marín – 0.0.1 – Not tested with the active version of WooCommerce
THM WooCommerce Multiple Free Gift: by Ankit Pokhrel & David Marín – 1.3.0 – Not tested with the active version of WooCommerce
THM yith points and rewards support role: by Irish Senapilo – 1.0
THM yith points and rewards restrict user role: by Irish Senapilo – 1.0
THM Yith WooCommerce Gift Cards Customizations: by David Marín – 0.0.1 – Not tested with the active version of WooCommerce
Compress JPEG & PNG images: by TinyPNG – 2.2.6
User Switching: by John Blackbourn – 1.0.9
VidEmbed: by The PluginBuddy Team – 1.0.17
WooCommerce Advanced Notifications: by WooCommerce – 1.2.11 – 1.2.14 is available – Not tested with the active version of WooCommerce
WooCommerce Extended Coupon Features PRO: by Soft79 – 2.5.5.1 – Not tested with the active version of WooCommerce
Commission Factory for WooCommerce: by Commission Factory Pty Ltd – 1.0 – Not tested with the active version of WooCommerce
WooCommerce Merchant Warrior (Transparent Redirect) Gateway: by Tyson Armstrong – 1.6.1 – Not tested with the active version of WooCommerce
WooCommerce AdWords Dynamic Remarketing: by Wolf + Bär GmbH – 1.3.3 – Not tested with the active version of WooCommerce
WooCommerce Invenco Connector: by Healthy Mummy PTY LTD – 1.0 – Not tested with the active version of WooCommerce
WooCommerce Product Bundles: by SomewhereWarm – 5.7.8 – 5.7.10 is available
WooCommerce Google Product Feed: by Ademti Software Ltd. – 7.4.1 – 7.6.0 is available – Not tested with the active version of WooCommerce
WooCommerce Products Visibility: by codemine – 2.4 – Not tested with the active version of WooCommerce
WooCommerce Subscriptions: by Prospress Inc. – 2.2.18 – 2.2.21 is available – Not tested with the active version of WooCommerce
WooCommerce URL Coupons: by SkyVerge – 2.6.0 – 2.6.3 is available – Not tested with the active version of WooCommerce
WooCommerce: by Automattic – 3.4.2
Yoast SEO: by Team Yoast – 3.6
Email Login: by Beau Lebens – 4.6.4
WP-PageNavi: by Lester 'GaMerZ' Chan – 2.87
YITH WooCommerce Gift Cards Premium: by YITHEMES – 1.6.7 – Not tested with the active version of WooCommerce
YITH WooCommerce Points and Rewards Premium: by YITHEMES – 1.3.1 – Not tested with the active version of WooCommerce

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: AUD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: bundle (bundle)
external (external)
gift-card (gift-card)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-filtered (exclude-from-filtered)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-3 (rated-3-2)
rated-4 (rated-4)
rated-5 (rated-5)
rated-5 (rated-5-2)
rated-5 (rated-5-3)


### WC Pages ###

Shop base: #51799 - /shop/
Cart: #51800 - /cart/
Checkout: #51801 - /checkout/
My account: #51802 - /my-account/
Terms and conditions: #6613 - /healthy-mummy-terms-conditions/

### Theme ###

Name: LBWAU child
Version: 1.0.0
Author URL: http://example.com
Child Theme: ✔
Parent Theme Name: LBW
Parent Theme Version: 2.0
Parent Theme Author URL: http://www.summitcreative.com.au
WooCommerce Support: ✔

### Templates ###

Overrides: lbwau/woocommerce/archive-product.php
lbwau/woocommerce/cart/cart-empty.php
lbwau/woocommerce/cart/cart-totals.php
lbwau/woocommerce/cart/cart.php
lbwau/woocommerce/cart/cross-sells.php
lbwau/woocommerce/cart/proceed-to-checkout-button.php
lbwau/woocommerce/checkout/form-billing.php
lbwau/woocommerce/checkout/form-checkout.php
lbwau/woocommerce/checkout/form-login.php
lbwau/woocommerce/checkout/form-pay.php
lbwau/woocommerce/checkout/form-shipping.php
lbwau/woocommerce/checkout/review-order.php
lbwau/woocommerce/checkout/thankyou.php
lbwau/woocommerce/content-product.php
lbwau/woocommerce/content-single-product.php
lbwau/woocommerce/emails/customer-new-account.php
lbwau/woocommerce/emails/customer-processing-order.php
lbwau/woocommerce/emails/email-footer.php
lbwau/woocommerce/emails/email-order-details.php
lbwau/woocommerce/emails/email-order-items.php
lbwau/woocommerce/global/quantity-input.php
lbwau/woocommerce/loop/loop-end.php
lbwau/woocommerce/loop/loop-start.php
lbwau/woocommerce/loop/price.php
lbwau/woocommerce/myaccount/dashboard.php
lbwau/woocommerce/myaccount/my-orders.php
lbwau/woocommerce/myaccount/navigation.php
lbwau/woocommerce/myaccount/orders.php
lbwau/woocommerce/myaccount/view-order.php
lbwau/woocommerce/notices/success.php
lbwau/woocommerce/order/order-details-item.php
lbwau/woocommerce/order/order-details.php
lbwau/woocommerce/order/tracking.php
lbwau/woocommerce/single-product/add-to-cart/simple.php
lbwau/woocommerce/single-product/add-to-cart/variable.php version 3.4.0 is out of date. The core version is 3.4.1
lbwau/woocommerce/single-product/add-to-cart/variation-add-to-cart-button.php
lbwau/woocommerce/single-product/add-to-cart/variation.php
lbwau/woocommerce/single-product/price.php
lbwau/woocommerce/single-product/product-image.php
lbwau/woocommerce/single-product/product-thumbnails.php
lbwau/woocommerce/single-product/short-description.php
lbwau/woocommerce/single-product/stock.php
lbwau/woocommerce/single-product/title.php
lbwau/single-product.php
lbwau/woocommerce/taxonomy-product_cat.php
lbwau/woocommerce/taxonomy-product_tag.php

Outdated Templates: ❌
					
					
						Learn how to update

### WooCommerce Google Product Feed fields ###

Availability: Defaults to "in stock".
Brand: Defaults to "The Healthy Mummy".
Manufacturer Part Number (MPN): Pre-populates from "sku taxonomy".
Product Type: 
Google Product Category: Defaults to "Health & Beauty > Health Care > Fitness & Nutrition".
Gender: Defaults to "female".
Age Group: Defaults to "adult".
Size system: 
Adwords grouping filter: Defaults to "Google Woo Store".
Custom label 1: Pre-populates from "product_cat taxonomy".
Custom label 2: Pre-populates from "product_tag taxonomy".

### WooCommerce Google Product Feed options ###

Include variations in feed: No
Send item_group_id: No

### subscriptions ###

WCS_DEBUG: ✔
						No
Subscriptions Mode: ✔
						Live
Subscriptions Template Theme Overrides: lbwau/woocommerce/checkout/recurring-totals.php lbwau/woocommerce/emails/customer-processing-renewal-order.php lbwau/woocommerce/emails/customer-renewal-invoice.php lbwau/woocommerce/emails/email-order-details.php lbwau/woocommerce/emails/subscription-info.php lbwau/woocommerce/myaccount/my-subscriptions.php lbwau/woocommerce/myaccount/view-subscription.php lbwau/woocommerce/single-product/add-to-cart/subscription.php lbwau/woocommerce/single-product/add-to-cart/variable-subscription.php
Report Cache Enabled: ✔
						Yes
Cache Update Failures: ✔
						0 failure
`
```
</details>

### PR DESCRIPTION
**Pull request by davefx**
### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes #20568 . Closely related to #18651.

### How to test the changes in this Pull Request:

1. Get a plugin that uses the generate_{type}_html functions, like https://github.com/afterpay/afterpay-woocommerce
2. Add two custom settings fields, of select and multiselect type, that use integers for values
3. The settings will be saved correctly, and the saved values will be shown.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

### Changelog entry

> Fix: generate_select_html and generate_multiselect_html functions again support the usage of integer-keyed arrays as available values.

### CODE REVIEW

File: includes/abstracts/abstract-wc-settings-api.php [hunk 1]
```diff
@@ -708,7 +708,7 @@ public function generate_select_html( $key, $data ) {
 					<legend class="screen-reader-text"><span><?php echo wp_kses_post( $data['title'] ); ?></span></legend>
 					<select class="select <?php echo esc_attr( $data['class'] ); ?>" name="<?php echo esc_attr( $field_key ); ?>" id="<?php echo esc_attr( $field_key ); ?>" style="<?php echo esc_attr( $data['css'] ); ?>" <?php disabled( $data['disabled'], true ); ?> <?php echo $this->get_custom_attribute_html( $data ); // WPCS: XSS ok. ?>>
 						<?php foreach ( (array) $data['options'] as $option_key => $option_value ) : ?>
-							<option value="<?php echo esc_attr( $option_key ); ?>" <?php selected( $option_key, esc_attr( $this->get_option( $key ) ) ); ?>><?php echo esc_attr( $option_value ); ?></option>
+							<option value="<?php echo esc_attr( $option_key ); ?>" <?php selected( $option_key, (string) esc_attr( $this->get_option( $key ) ) ); ?>><?php echo esc_attr( $option_value ); ?></option>
```
Comment (mikejolley) [inline includes/abstracts/abstract-wc-settings-api.php]: Isn't this casting the wrong value?

Comment (davefx) [reply includes/abstracts/abstract-wc-settings-api.php]: You are totally right! I tested it only with multiselect.

**Review by mikejolley — APPROVED** [review]
