### PR TITLE
Consistent cart forms and woocommerce_after_add_to_cart_button placement

### LINKED ISSUE #19654: woocommerce_after_add_to_cart_button behaves differently based on the product type.
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Add an action that adds text/img/other element to the woocommerce_after_add_to_cart_button filter.
2. Go to a product page to see the result based on the product type.

## Expected/actual behavior

When I follow those steps, I see on a grouped or simple product the text/img/element behind the add to cart button. On an external product it is below the `<p>` element and on a variable product it is aligned to the bottom of the **quantity** `div`.

I was expecting to see (almost) the exact same behaviour on all product type pages. With either the added text/img/element being aligned next to or below the add to cart button.

Am I wrong in expecting this behavior or is a change welcome that introduces uniformity in the filters behavior?

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
`
### WordPress Environment ###

Home URL: https://demo-woocommerce.local.propoza.com
Site URL: https://demo-woocommerce.local.propoza.com
WC Version: 3.3.4
Log Directory Writable: ✔
WP Version: 4.9.5
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache/2.4.27 (Unix) OpenSSL/1.0.1p PHP/7.1.8
PHP Version: 7.1.8
PHP Post Max Size: 200 MB
PHP Time Limit: 0
PHP Max Input Vars: 1000
cURL Version: 7.43.0
OpenSSL/1.0.1p

SUHOSIN Installed: –
MySQL Version: 5.6.37
Max Upload Size: 200 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.3.4
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Total Database Size: 2.17MB
Database Data Size: 1.02MB
Database Index Size: 1.15MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_comments: Data: 0.02MB + Index: 0.09MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_options: Data: 0.09MB + Index: 0.02MB
wp_postmeta: Data: 0.28MB + Index: 0.27MB
wp_posts: Data: 0.11MB + Index: 0.06MB
wp_termmeta: Data: 0.02MB + Index: 0.03MB
wp_terms: Data: 0.02MB + Index: 0.03MB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wp_usermeta: Data: 0.02MB + Index: 0.03MB
wp_users: Data: 0.02MB + Index: 0.05MB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_bundled_itemmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_bundled_items: Data: 0.02MB + Index: 0.03MB

### Post Type Counts ###

attachment: 35
page: 5
post: 2
product: 64
product_variation: 11
shop_coupon: 14
shop_quote: 60

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (4) ###

WooCommerce Propoza: by Propoza – 1.0.17 – Not tested with the active version of WooCommerce
WooCommerce Product Bundles: by SomewhereWarm – 5.7.3 – 5.7.7 is available
WooCommerce: by Automattic – 3.3.4
WordPress Importer: by wordpressdotorg – 0.6.4

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: ZAR (R)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: bundle (bundle)
external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: #4 - /?page_id=4
Cart: #5 - /?page_id=5
Checkout: #6 - /?page_id=6
My account: #7 - /?page_id=7
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 2.2.8
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –
`
```
</details>

### PR DESCRIPTION
**Pull request by mikejolley**
Fixes #19654 by making all add to cart forms honour the correct placement of `woocommerce_after_add_to_cart_button`.

For external products, this also replaces the link with a form tag so it better matches simple products.

Most templates were already bumped; I fixed PHPCS violations.

View simple, grouped, external, and variable product forms to test - they should the same after updating.

### CODE REVIEW

File: templates/single-product/add-to-cart/variable.php [hunk 1]
```diff
@@ -23,54 +23,58 @@
...
 			</tbody>
 		</table>
 
-		<?php do_action( 'woocommerce_before_add_to_cart_button' ); ?>
-
 		<div class="single_variation_wrap">
 			<?php
 				/**
-				 * woocommerce_before_single_variation Hook.
+				 * Woocommerce_before_single_variation Hook.
```
Comment (claudiosanches) [inline templates/single-product/add-to-cart/variable.php]: Better change to `Hook: woocommerce_before_single_variation` like we do in other templates.

File: templates/single-product/add-to-cart/variable.php [hunk 2]
```diff
@@ -23,54 +23,58 @@
...
+				 *
 				 * @since 2.4.0
 				 * @hooked woocommerce_single_variation - 10 Empty div for variation data.
 				 * @hooked woocommerce_single_variation_add_to_cart_button - 20 Qty and cart button.
 				 */
 				do_action( 'woocommerce_single_variation' );
 
 				/**
-				 * woocommerce_after_single_variation Hook.
+				 * Woocommerce_after_single_variation Hook.
```
Comment (claudiosanches) [inline templates/single-product/add-to-cart/variable.php]: `Hook: Woocommerce_after_single_variation`

**Review by claudiosanches — DISMISSED** [review]

**Review by claudiulodro — APPROVED** [review]

**Comment by WesKel** [comment]
Hi There,

Due to issue: #20535

Thanks for your reply but the issue is not solved yet... :-(

Option 1: is ONLY working in Google Chrome and Safari. Not in MS Edge & Firefox. So we don't have anything with this option.

Option 2: I don't understand this.

Option 3: It's not an option due to SEO perspectives.

QUESTION 1: Could you guys from woocommerce make option 1 compatible with ALL BROWSERS? 
QUESTION 2: I'm not a programmer. Could you explain option 2?
