### PR TITLE
Consistently format empty strings in decimal format utils

### LINKED ISSUE #58866: Investigate `wc_format_decimal` and ensure it handles empty strings correctly
## **Describe the bug**

It seems that this function processes empty strings differently depending on its `$dp` value. When `false`, it seems to return the empty string, but when set to an integer it seems to convert an empty string to 0.

## **To Reproduce**

Call `wc_format_decimal` with: `wc_format_decimal( '', false )` and observe the output. Then call it like `wc_format_decimal( '', 0 )` and observe the output.

## **Expected behavior**

The function likely should handle empty strings consistently

## Environment

Please fill out any of the below that applies

**Operating System/Device**

- [ ] Windows
- [ ] MacOS
- [ ] Linux
- [ ] iPhone
- [ ] Samsung
- [ ] Other (add in additional context field)

**Version:** 

**Browser**

- [ ] Desktop Edge
- [ ] Desktop Chrome/Chromium
- [ ] Desktop Safari
- [ ] Mobile Edge
- [ ] Mobile Chrome/Chromium
- [ ] Mobile Safari
- [ ] Other (add in additional context field)

**Version:**

### PR DESCRIPTION
**Pull request by joshuatf**
### Changes proposed in this Pull Request:

When using `wc_format_decimal( '', false )` and `wc_format_decimal( '', 0 )` different results are given.

Because many other modules rely on the empty string returning an empty string, these results should remain empty for other areas of core (and tests) to continue working in a backwards compatible manner.

See https://github.com/woocommerce/woocommerce/commit/5ca67f418bfa816c304a10af386b14edefe1e52e

Closes #58866 .

(For Bug Fixes) Bug introduced in PR # .

### Screenshots or screen recordings:

**Before**

```
wc_format_decimal( "", false ): 
wc_format_decimal( "", 0 ): 0
```

**After**
```
wc_format_decimal( "", false ): 
wc_format_decimal( "", 0 ): 
```

### How to test the changes in this Pull Request:

1. Add the following custom snippet to your site:
```php
add_action( 'init', function() {
	error_log( 'wc_format_decimal( "", false ): ' . wc_format_decimal( "", false ) );
	error_log( 'wc_format_decimal( "", 0 ): ' . wc_format_decimal( "", 0 ) );
} );
```
2. Refresh any page.
3. Check your error log and expect to get all empty strings results from each of the logs.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

**Comment by joshuatf** [comment]
@coderabbitai configuration

**Comment by joshuatf** [comment]
Just want to double check expectations that we want to always return an empty string when one is provided.  Some items in endpoints are formatted with 2 decimals ([example](https://github.com/woocommerce/woocommerce/blob/297d91ee2eebf9cf6972c70e750c48b047ce6931/plugins/woocommerce/includes/rest-api/Controllers/Version2/class-wc-rest-coupons-v2-controller.php/#L146-L153)) and this breaks assertions in tests.

I think logically it makes sense to format these to `''` instead of converting an empty string to `0.00`, but I'm not sure if this affects backwards compatibility with anyone using those endpoints.

cc @opr @mikejolley in case you have more context before I update these tests.

**Comment by opr** [comment]
> Just want to double check expectations that we want to always return an empty string when one is provided. Some items in endpoints are formatted with 2 decimals ([example](https://github.com/woocommerce/woocommerce/blob/297d91ee2eebf9cf6972c70e750c48b047ce6931/plugins/woocommerce/includes/rest-api/Controllers/Version2/class-wc-rest-coupons-v2-controller.php/#L146-L153)) and this breaks assertions in tests.
> 
> I think logically it makes sense to format these to `''` instead of converting an empty string to `0.00`, but I'm not sure if this affects backwards compatibility with anyone using those endpoints.
> 
> cc @opr @mikejolley in case you have more context before I update these tests.

@joshuatf I agree, formatting an empty string should still output an empty string, making `''` have decimal places should still be `''` that seems "correct" to me.

With that said, there are many uses of this in the wild (https://github.com/search?q=wc_format_decimal&type=code) that don't look like they have much robust handling in place for empty strings coming back (where they would previously have been `0.00`. Looking at these examples, it seems like most of them are inputting integers anyway, so the change _shouldn't_ affect them.

I'd suggest putting a dev advisory out alongside this fix if we proceed.

File: plugins/woocommerce/includes/wc-formatting-functions.php [hunk 1]
```diff
@@ -286,7 +286,11 @@ function wc_format_refund_total( $amount ) {
  * @return string
  */
 function wc_format_decimal( $number, $dp = false, $trim_zeros = false ) {
-	$number = $number ?? '';
+	$number = $number ?? '0';
```
Comment (kalessil) [inline plugins/woocommerce/includes/wc-formatting-functions.php]: It looks like a BC break to me, but regarding my other comment, it might be unnecessary.

If we agree with that statement, we can delete this line and update line 300 to `$number = str_replace( $decimals, '.', (string) $number );` - `null` gets cast to empty string (https://3v4l.org/adYIc). That change would be backward compatible and eradicate explicit null handling (which is not in the function doc-block anyway, but still works).

File: plugins/woocommerce/includes/wc-formatting-functions.php [hunk 2]
```diff
@@ -286,7 +286,11 @@ function wc_format_refund_total( $amount ) {
...
+
+	if ( '' === $number ) {
```
Comment (kalessil) [inline plugins/woocommerce/includes/wc-formatting-functions.php:291]: I suggest adjusting the approach slightly and pursuing this approach instead:

```php
    // Lines 306-309 as per the review state of the file
   	if ( is_numeric( $number ) && false !== $dp ) {
		$dp     = intval( '' === $dp ? wc_get_price_decimals() : $dp );
		$number = number_format( floatval( $number ), $dp, '.', '' );
	} elseif ...
```

This one does not introduce any logic branching, and as a fix, it is better to be bound contextually.

File: plugins/woocommerce/includes/wc-formatting-functions.php (hunk 1 above)
Comment (joshuatf) [reply plugins/woocommerce/includes/wc-formatting-functions.php]: Nice catch!  I do agree that this change is not needed, but we can revert back to the original line of `$number = $number ?? '';`.

Changing to casting it as a string opens up the possibility for failure when providing a null value and a DP (e.g., `wc_format_decimal( '', 0 )`).  This would result in `0` providing inconsistent results.

File: plugins/woocommerce/includes/wc-formatting-functions.php (hunk 2 above)
Comment (joshuatf) [reply plugins/woocommerce/includes/wc-formatting-functions.php:291]: The problem with this is that any other changes, such as coercions or other formatting, leave open the possibility for an empty string to return something other than an empty string when passed.  This is demonstrated by the changes suggested in [this comment](https://github.com/woocommerce/woocommerce/pull/59368#discussion_r2189471682).

Instead, when we receive an empty string, we should return early with an empty string since the other arguments don't have any bearing and future additions to formatting could introduce issues.

File: plugins/woocommerce/includes/wc-formatting-functions.php (hunk 1 above)
Comment (kalessil) [reply plugins/woocommerce/includes/wc-formatting-functions.php]: Right, then an early return is our safest option - I'm on board with that approach.

**Review by kalessil — DISMISSED** [review]
LGTM (pre-approving)! Thanks for additional clarifications!

**Comment by joshuatf** [comment]
bugbot run

**Comment by joshuatf** [comment]
@opr @mikejolley Just double confirming before I make changes to our own tests and endpoints: this change will change the response in our coupons endpoint for `minimum_amount` from `0.00` to `''`.  See https://github.com/woocommerce/woocommerce/actions/runs/16142559961/job/45553218547?pr=59368

This seems like a more semantic response since a minimum was never provided, but it does change the expectations in our endpoint and will require a few updates.

Also cc @woocommerce/ventures as you appear to be the main consumer of this endpoint internally.  At a quick glance it doesn't seem like this will cause any issues, but please let me know if you see otherwise.

**Comment by opr** [comment]
> @opr @mikejolley Just double confirming before I make changes to our own tests and endpoints: this change will change the response in our coupons endpoint for `minimum_amount` from `0.00` to `''`. See [woocommerce/woocommerce/actions/runs/16142559961/job/45553218547?pr=59368](https://github.com/woocommerce/woocommerce/actions/runs/16142559961/job/45553218547?pr=59368)
> 
> This seems like a more semantic response since a minimum was never provided, but it does change the expectations in our endpoint and will require a few updates.
> 
> Also cc @woocommerce/ventures as you appear to be the main consumer of this endpoint internally. At a quick glance it doesn't seem like this will cause any issues, but please let me know if you see otherwise.

I am still a bit concerned about backward compatibility issues for third party extensions if they're expecting a number but now get a string. I agree the change makes sense and is semantically correct. Can we put a dev advisory out _now_ but defer shipping this change for a couple of versions?

I agree with the proposed changes, just want to be careful about how we ship it.

File: plugins/woocommerce/includes/class-wc-coupon.php [hunk 3]
```diff
@@ -400,20 +418,26 @@ public function get_exclude_sale_items( $context = 'view' ) {
 	 *
 	 * @since  3.0.0
 	 * @param  string $context What the value is for. Valid values are 'view' and 'edit'.
-	 * @return float
+	 * @return string
```
Comment (joshuatf) [inline plugins/woocommerce/includes/class-wc-coupon.php:421]: These types were always strings.  They have never been floats, which probably would have been a better type.

File: plugins/woocommerce/includes/class-wc-coupon.php [hunk 4]
```diff
@@ -413,6 +434,9 @@ public function get_minimum_amount( $context = 'view' ) {
 	 * @return float
 	 */
 	public function get_maximum_amount( $context = 'view' ) {
+		if ( $this->get_prop( 'maximum_amount', $context ) === '' ) {
+			return wc_format_decimal( 0 );
+		}
```
[the remark this answers is not in the document]
Comment (joshuatf) [reply plugins/woocommerce/includes/class-wc-coupon.php:439]: These always return strings formatted using `wc_format_decimal`.

File: plugins/woocommerce/includes/class-wc-coupon.php [hunk 5]
```diff
@@ -145,6 +145,24 @@ public function __construct( $data = '' ) {
...
 
+	/**
+	 * Returns all data for this object.
+	 *
+	 * @since  2.6.0
+	 * @return array
+	 */
+	public function get_data() {
+		$data = parent::get_data();
+		if ( '' === $data['minimum_amount'] ) {
```
Comment (joshuatf) [inline plugins/woocommerce/includes/class-wc-coupon.php:156]: This keeps backwards compatibility in the REST API which expects to always have numbers regardless of assignment (and doesn't use the getters for some reason).

File: plugins/woocommerce/includes/class-wc-coupon.php [hunk 6]
```diff
@@ -400,20 +418,26 @@ public function get_exclude_sale_items( $context = 'view' ) {
...
 	 * Get maximum spend amount.
 	 *
 	 * @since  3.0.0
 	 * @param  string $context What the value is for. Valid values are 'view' and 'edit'.
-	 * @return float
+	 * @return string
 	 */
 	public function get_maximum_amount( $context = 'view' ) {
-		return $this->get_prop( 'maximum_amount', $context );
+		if ( 'edit' !== $context && $this->get_prop( 'maximum_amount', $context ) === '' ) {
```
Comment (joshuatf) [inline plugins/woocommerce/includes/class-wc-coupon.php:437]: The editor should still allow an empty string.

**Comment by joshuatf** [comment]
@kalessil I made some more changes to this PR due to failing tests and backwards compatibility issues.  Key changes include:

* Updating the coupon data store to always return formatted decimal values instead of empty strings.  This matches existing expectations for the REST response and _most_ areas where maximum/minimum coupon amounts are used for backwards compatibility.
* Allowing empty strings within the editor context so that input fields can remain empty and show placeholder labels.

The architecture in coupons is too coupled with the UI and ideally these numbers would always be `float|null`, but this would create significant breaks in backwards compatbility.

**Additional testing**
1. Make sure that you can create coupons in the admin and that min/max fields work as expected (empty values are the default)
2. Test coupons both with and without min/max options
3. Make sure the coupons still work as expected
4. Make a GET request to the coupons endpoint `/wp-json/wc/v3/coupons`
5. Make sure that min/max values are formatted decimals even when empty (e.g., `'0.00'`)

**Review by kalessil — APPROVED** [review]
LGTM (given editing and REST compatibility requirements, great work!)!

Tested managing the coupons, using coupons at checkout, and accessing coupons via REST: noticed no regressions.
