### PR TITLE
Accept an error message from payment methods or convert notices for failure only

### LINKED ISSUE #51272: Block checkout doesn't show the error message from process_payment
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

We are working on update our custom gateway payment to support block checkout feature.
On the classic checkout, the error message is shown correctly when there are something wrong with payment processing. but the only a generic message is shown up for block checkout.

image

image

### Expected behavior

We should show the error message from the repsonse of the API `/wp-json/wc/store/v1/checkout`

```
payment_result => payment_details => item_with_key[messages]
```

### Actual behavior

a generic message is shown up
```
Something went wrong. Please contact us to get assistance.
```

### Steps to reproduce

1. Make your payment gateway throw a custom error.

process_payment function
```
        } catch (\Throwable $ex) {
            $error = $ex->getMessage();
            $userError = $this->format_bfx_error($ex);

            $logger = wc_get_logger();
            $logger->error('CREATE INVOICE CALL >> '.$error, ['source' => 'bitfinex-pay']);

            wc_add_notice($userError, 'error');
            $order->update_status('failed', $userError);

            return [
                'result' => 'failure',
                'messages' => $userError,
            ];
        }
```

2. Click checkout
3. the error happens

### WordPress Environment

<details><summary>System Status Report</summary>

```
### WordPress Environment ###

WordPress address (URL): [Redacted]
Site address (URL): [Redacted]
WC Version: 9.1.2
Legacy REST API Package Version: The Legacy REST API plugin is not installed on this site.
Action Scheduler Version: ✔ 3.7.4
Log Directory Writable: ✔
WP Version: ❌ 6.6.1 - There is a newer version of WordPress available (6.6.2)
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.57 (Debian)
PHP Version: 8.2.16
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.88.1
OpenSSL/3.0.11

SUHOSIN Installed: –
MySQL Version: 8.0.36
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

[REDACTED]

### Post Type Counts ###

attachment: 1
page: 8
post: 3
product: 1
revision: 6
shop_order_placehold: 7
wp_font_face: 33
wp_font_family: 12
wp_global_styles: 1
wp_navigation: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (4) ###

BFX crypto map: by BFX – 1.4.4
Bitfinex Pay: by Bitfinex – 3.1.0
WooCommerce: by Automattic – 9.1.2 (update to version 9.2.3 is available)
OfficeRnD Bitfinex Pay integration: by BFX – 1.0.5

### Inactive Plugins (3) ###

Akismet Anti-spam: Spam Protection: by Automattic - Anti-spam Team – 5.3.1
Bitfinex Pay: by Bitfinex – 3.0.2
Hello Dolly: by Matt Mullenweg – 1.7.2

### Settings ###

API Enabled: –
Force SSL: –
Currency: VND (₫)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 0
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 67 KB

### WC Pages ###

Shop base: #14 - /shop/
Cart: #15 - /cart/ -  Contains the woocommerce/cart block
Checkout: #16 - /checkout/ -  Contains the woocommerce/checkout block
My account: #17 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty-Four
Version: 1.0 (update to version 1.2 is available)
Author URL: https://wordpress.org
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ❌ Not declared

### Templates ###

Overrides: /var/www/html/wp-content/plugins/woocommerce/templates/block-notices/error.php
/var/www/html/wp-content/plugins/woocommerce/templates/block-notices/notice.php
/var/www/html/wp-content/plugins/woocommerce/templates/block-notices/success.php


### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page
launch-your-store

Disabled Features: experimental-blocks
minified-js
pattern-toolkit-full-composability
product-pre-publish-modal
printful
settings
async-product-editor-category-field
product-editor-template-system

Daily Cron: ✔ Next scheduled: 2024-07-25 14:58:44 +00:00
Options: ✔
Notes: 63
Onboarding: completed

### Action Scheduler ###

Complete: 2
Oldest: 2024-07-25 01:24:56 +0000
Newest: 2024-07-25 01:33:32 +0000

Pending: 13
Oldest: 2024-07-21 15:00:49 +0000
Newest: 2024-09-11 02:45:46 +0000


### Status report information ###

Generated at: 2024-09-11 03:45:06 +00:00
```
</details>

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by senadir**
### Submission Review Guidelines:

This PR is a third spin on https://github.com/woocommerce/woocommerce-blocks/pull/4700 and https://github.com/woocommerce/woocommerce-blocks/pull/4871

This for me, addresses the concerns in those 2 previous issues, by only converting error notices to exception if the payment gateway explicitly returned a failure status, and didn't return a message with the payment result.

Otherwise, this adds support for returning a message with failure status which will be used instead of notices.

I tried to expand this to shortcode Checkout but was a bit finicky.

### Changes proposed in this Pull Request:

Closes https://github.com/woocommerce/woocommerce/issues/51272

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

Using this requires modifying code to modify a core payment method.

1. Modify COD class `process_payment` method and return this at the top of the file:
```php
return array(
	'result' => 'failure',
	'message' => __( 'Cash on delivery is not available for this order.', 'woocommerce' ),
);
```
2. On Checkout block, place an order using COD, ensure that it doesn't pass and you get that error.
3. Remove the `message` part of the error, try placing again. Ensure you get a generic error `Something went wrong. Please contact us to get assistance.`
4. Add a notice before the return:
```php
wc_add_notice( __( 'Cash on delivery is not available for this order, but a notice.', 'woocommerce' ), 'error' );
```
5. On placing the order, ensure you get that error.
6. Now, leave both the message and the notice and try to place an order, only the one from the array (without `, but with a notice`) should be shown.

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [x] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [x] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 
Accept a `message` in the payment result when processing payment, as well as convert error notices on failure.

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce/src/StoreApi/Legacy.php [hunk 1]
```diff
@@ -56,16 +56,24 @@ public function process_legacy_payment( PaymentContext $context, PaymentResult &
 		// Restore $_POST data.
 		$_POST = $post_data;
 
-		// If `process_payment` added notices, clear them. Notices are not displayed from the API -- payment should fail,
-		// and a generic notice will be shown instead if payment failed.
-		wc_clear_notices();
+		// If the payment failed with a message, throw an exception.
+		if ( 'failure' === $gateway_result['result'] ) {
```
Comment (mikejolley) [inline plugins/woocommerce/src/StoreApi/Legacy.php]: This will create a PHP error notice if `result` does not exist in the array. Since we handle this further down (`$result_status = $gateway_result['result'] ?? 'failure';`) you could move that line above this and use that.

**Review by mikejolley — APPROVED** [review]
Excellent, sensible approach. Thanks @senadir 👍🏻 Spotted one minor thing that you can fix but pre-approving.

File: plugins/woocommerce/src/StoreApi/Legacy.php (hunk 1 above)
Comment (senadir) [reply plugins/woocommerce/src/StoreApi/Legacy.php]: I will check for that instead of moving that line. That check will always assign `failure` as a result, and we can't know if the payment method explicitly returned failure or just didn't do anything.

Comment (senadir) [inline plugins/woocommerce/src/StoreApi/Legacy.php]:
```suggestion
		if ( isset( $gateway_result['result'] ) && 'failure' === $gateway_result['result'] ) {
```
