### PR TITLE
Select a shipping rate after they load 

### LINKED ISSUE #47115: [Checkout Block] Single shipping option is not selected by default when switching from Local Pickup
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

For some stores with one shipping rate and local pickup places defined shoppers can place orders with no selected shipping option.

### Expected behavior

- shoppers should not be able to place orders without shipping options, when shipping is selected
- there should be a front-end validation at the shipping options level to make sure we aren't allowing placing an order

### Actual behavior

When displaying shipping options we normally select the first option by default. See https://github.com/woocommerce/woocommerce/blob/6d914ff573c1946d3f50ee0a93417380c10adb39/plugins/woocommerce-blocks/assets/js/base/components/cart-checkout/shipping-rates-control-package/package-rates.tsx#L46.

But in this case, see testing steps, the option does not get selected.

Screenshot 2024-04-26 at 12 26 19

There is no frontend validation in place for shipping options.

In reality, it's the local pickup option that gets saved, and that's why no validation is present.

### Steps to reproduce

 I have this setup for my store:

- 1 shipping rate; flat rate for Europe
- 1 Local pickup option defined
- store country US, Default customer location: shop country
- Go on an incognito window;
- Add product to cart
- Go directly to Checkout block; for me local pickup is selected by default
- switch to shipping
- change country from US to France

Notice the shipping option appears and it's not selected

### WordPress Environment

n/a

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by senadir**
When switching from Local Pickup to Shipping options set, Local pickup is still selected. However, once you add an address and rates are returned, the first rate should be selected, but it's still stuck at local pickup. This PR fixes it.

Closes https://github.com/woocommerce/woocommerce/issues/47115

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Enable Local Pickup with a location and Enable shipping rates for specific countries (Europe for example.
2. Set store default location to US, and set customer default location to store location.
3. On an incognito window, go to Checkout, see that Local Pickup is selected.
4. Switch to shipping, see that there are not rates and local pickup is still selected, change the address to one in europe.
5. Notice that the server returns rates and the first one is selected after that.

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

Select the first shipping rate when local pickup is enabled and customer switches to shipping.

#### Comment 

</details>

### CODE REVIEW

**Comment by senadir** [comment]
Spent some time trying to add E2E to this but it required switching up how tests are initiated, so decided to skip that for now.

**Comment by senadir** [comment]
Although we have logic in the same component for that, [in this line.](https://github.com/woocommerce/woocommerce/blob/6d914ff573c1946d3f50ee0a93417380c10adb39/plugins/woocommerce-blocks/assets/js/base/components/cart-checkout/shipping-rates-control-package/package-rates.tsx#L46) That only run on first mount, but because first mount start with no rates, it doesn't get fixed after that.

**Review by nielslange — APPROVED** [review]
Thanks for fixing this issue, @senadir. I've successfully tested this change.

File: plugins/woocommerce-blocks/assets/js/base/components/cart-checkout/shipping-rates-control-package/package-rates.tsx [hunk 1]
```diff
@@ -64,6 +64,14 @@ const PackageRates = ( {
 		}
 	}, [ onSelectRate, selectedOption ] );
 
+	// Update the selected option if there is no rate selected on mount.
+	useEffect( () => {
+		if ( ! selectedOption && rates.length > 0 ) {
+			setSelectedOption( rates[ 0 ].rate_id );
+			onSelectRate( rates[ 0 ].rate_id );
+		}
+	}, [ onSelectRate, rates, selectedOption ] );
```
Comment (ralucaStan) [inline plugins/woocommerce-blocks/assets/js/base/components/cart-checkout/shipping-rates-control-package/package-rates.tsx:69]: this works. 

I'd actually move this one before the useEffect on line 61. Although it makes no difference, at least chronologically this is how events are triggered. 

I'd also add a check on line 46. `return rates[ 0 ]?.rate_id;`, to return the first rate only when `rates.length > 0`; this would make the code more clear and explain why we need this extra effect

**Review by ralucaStan — COMMENTED** [review]
I've added a comment.
