### PR TITLE
Revert PR #17895

### LINKED ISSUE #21656: post_author issues after WC 3.5 database update
**Describe the bug**
When working on the data migration routine on PR #17895 to improve the performance of the WC queries that filter orders by customer ID, I assumed that WC before 3.5 always set post_author to 1 (see https://github.com/woocommerce/woocommerce/issues/17087#issue-263398846) for every order. But @stianandreassen has brought to my attention (see their comments starting here https://github.com/woocommerce/woocommerce/pull/17895#issuecomment-432635912) that this assumption is wrong and that WC before 3.5 will set post_author to the current WP user ID when orders are created manually via wp-admin.

This has two different consequences depending on how the database update routine is triggered. This because the `wc_update_350_order_customer_id()` function uses two different strategies to migrate the customer ID from `_customer_user` postmeta to `post_author` depending on whether the process was started via the WP-CLI command or the wp-admin interface.

- If the process was started via the WP-CLI command, the data will be migrated successfully and WC will display the correct information about the customer, but the IDs of the WP users, usually shop managers, that manually created the orders (that was previously stored in the post_author field) will be lost. WC never used or exposed those IDs so, although we didn't anticipate that this would happen, I don't think we need to fix it (the only way I can see to fix this is to revert #17895 and keep using postmeta to store the customer ID).

- If the database update routine was started via the wp-admin interface, the [query that gets the IDs of the orders that need to be updated](https://github.com/woocommerce/woocommerce/blob/245e1768f9674391a2deb5b2b44943e515a8eb98/includes/wc-update-functions.php#L1905) ignores entries created manually via the wp-admin interface by users other than user ID 1. This means that after the 3.5 database update, the post_author field for the orders ignored by the query are not updated and remain with the ID of the user that manually created the order instead of the customer ID. As a result, for those orders, WooCommerce will display the wrong customer. Luckily, the correct information is still stored in the old `_customer_user` postmeta and probably the easiest solution is to write another update routine that will migrate the data for the orders that are displaying the wrong customer.

**To Reproduce**
1. Make sure you are running WC < 3.5 and that the database version is also < 3.5 (check the value of the options `woocommerce_version` and `woocommerce_db_version`).
2. Create a shop_manager and a customer user.
3. Login with the shop_manager user and manually create an order setting the customer of that order as the user named customer.
4. Check in the order page that "customer" is correctly identified as the customer of that order.
5. Update to WC 3.5.0 and run the database update routine via the wp-admin interface.
5. Reload the order page, and WC will show "shop_manager" as the customer of the order.

**Screenshots**
Screenshots provided by @stianandreassen

woo_350_1

woo_350_2

**Expected behavior**
WC should display customer as the customer of the order instead of shop_manager.

### PR DESCRIPTION
**Pull request by rodrigoprimo**
### Changes proposed in this Pull Request:

This PR reverts #17895 which was introduced in WC 3.5 to use post_author instead of `_customer_user` post meta to store customer ID for orders. After talking to @claudiulodro, we decided to revert the changes for WC 3.5.1 and reconsider #17895 for 3.6. This decision was made due to the bugs that were introduced by #17895 and that we didn't catch before the release (#21656, #21687 and #21737). All the issues seem fixable, but we are opting to err on the side of caution instead of rushing to create fixes that could introduce more problems. Reverting is the safest and fastest option that we have now.

#17895 copied data from `_customer_user` postmeta to the field `post_autor` of the table `wp_posts` and changed WooCommerce to populate both `customer_user` and `post_author` when a order is created or updated. So, this PR simply revert the code changes to make WooCommerce get the customer ID for orders in the old way. For now, we are not touching the data that was copied to `post_author` and this shouldn't be a problem as WooCommerce doesn't use this field for orders.

It was not possible to revert #17895 automatically, so I had to revert each commit manually. I decided to keep the changes introduced in `includes/class-wc-background-updater.php` (https://github.com/woocommerce/woocommerce/pull/17895/files#diff-3809cc9b6218b1f645071ed0351b2edc) as they could be useful for future database update routines.

Closes #21656, #21687, #21737 and #21741.
Supersedes #21673 and #21695

### How to test the changes in this Pull Request:

1. Check that code changes were properly reverted
2. Check that the issue in #21737 was fixed
3. Test that the functionality altered in this PR still works: customer reports, filter orders by customer in the admin interface, filter orders by customer in the REST API, saving customer ID when placing an order or manually created it via wp-admin, saving customer ID when updating an order, get customer last order (https://github.com/woocommerce/woocommerce/compare/revert/17895?expand=1#diff-d6dba1e5e24baa6d5d15671305dd1994R325), `wc_reset_order_customer_id_on_deleted_user()` and `wc_customer_bought_product()`.
4. Make sure that orders that were created after the WC 3.5 have the correct customer after updating to 3.5.1.

### Changelog entry

> Revert PR to use post_author instead of the post meta '_customer_user' to store customer ID for orders

### CODE REVIEW

File: includes/data-stores/class-wc-order-data-store-cpt.php [hunk 1]
```diff
@@ -265,9 +258,10 @@ protected function update_post_meta( &$order ) {
 			update_post_meta( $id, '_shipping_address_index', implode( ' ', $order->get_address( 'shipping' ) ) );
 		}
 
-		// If customer email changed, update any downloadable permissions.
-		if ( in_array( 'billing_email', $updated_props ) ) {
-			$this->update_downloadable_permissions( $order );
+		// If customer changed, update any downloadable permissions.
+		if ( in_array( 'customer_user', $updated_props ) || in_array( 'billing_email', $updated_props ) ) {
```
Comment (claudiulodro) [inline includes/data-stores/class-wc-order-data-store-cpt.php]: This should be [customer_id](https://github.com/woocommerce/woocommerce/pull/17895/files#diff-9b0af3108fffa9d52d09b6504882fd0aL262)

**Review by claudiulodro — CHANGES_REQUESTED** [review]
Looks good and works well in my testing. Just one small change needed.

**Comment by rodrigoprimo** [comment]
@claudiulodro, fce22a7 adds the change you requested. When I reverted each of the commits in this PR individually, I didn't revert merge commits that were used to keep #17895 branch in sync with master. When commit 61c7abce4f50146fa595f6429e8f8d6fc082d9fc was made a few months ago, there was a bug in the code and it was using`customer_user` instead of `customer_id`. This bug was fixed in a unrelated commit (https://github.com/woocommerce/woocommerce/commit/c765ce644db14e322fc77b0d3863d2e4160ecd4f#diff-9b0af3108fffa9d52d09b6504882fd0aL262) and the fixed was overrode when I created ece9f02776626e7bff03ee635b1ce6129e1daae3.

**Review by claudiulodro — APPROVED** [review]
