### PR TITLE
Fix fatal error in cart template when filter returns non-product

### LINKED ISSUE #64156: Potential Fatal Error: Call to member function on null in Cart template
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

In the cart template `https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/templates/cart/cart.php` line 41  the `$_product` variable is set through a filter, and unlike in other uses of the filter there is a call to the `get_name()` at line 51 function before checking the variable is valid and exists. This causes a fatal error if a function hooked onto the filter ends up returning anything other than a WC_Product. This is already resolved in the `cart/mini-cart` and `checkout/review-order templates`, the `$product_name` is not used outside of the existing if statement that checks the existence of `$_product` so it should be safe to just move the declaration inside of it.

### Expected behavior

Graceful handling of unexpected data type

### Actual behavior

Fatal error when presented with an unexpected data type

### Steps to reproduce

1. Add product to cart
2. Create new filter to return unexpected data type, e.g. 
```
add_filter( 'woocommerce_cart_item_product', function () {
	return false;
} );
```
3. Open Cart page

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://aisnsw.test
Site address (URL): https://aisnsw.test
WC Version: 10.6.1
Legacy REST API Package Version: The Legacy REST API plugin is not installed on this site.
Action Scheduler Version: ✔ 3.9.3
Log Directory Writable: ✔
WP Version: 6.9.4
WP Multisite: –
WP Memory Limit: ❌ 40 MB - We recommend setting memory to at least 64MB. See: Increasing memory allocated to PHP
WP Debug Mode: –
WP Cron: –
WP Environment Type: production
Language: en_AU
External object cache: –

### Server Environment ###

Server Info: nginx/1.25.4
Server Architecture: Darwin 25.2.0 arm64
PHP Version: 8.4.11
PHP Post Max Size: 1 GB
PHP Time Limit: 300
PHP Max Input Vars: 5000
cURL Version: 8.15.0
OpenSSL/3.5.1

SUHOSIN Installed: –
MySQL Version: 8.0.33
Max Upload Size: 1 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 10.6.1
WC Database Prefix: wp_
Total Database Size: 246.25MB
Database Data Size: 203.13MB
Database Index Size: 43.12MB
wp_woocommerce_sessions: Data: 0.08MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.19MB + Index: 0.20MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 1.52MB + Index: 1.30MB + Engine InnoDB
wp_actionscheduler_claims: Data: 1.52MB + Index: 1.52MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 1.52MB + Index: 0.38MB + Engine InnoDB
wp_agend_cp_actor_meta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_catfolders: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_catfolders_posts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.23MB + Index: 0.31MB + Engine InnoDB
wp_e_events: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_e_notes: Data: 0.02MB + Index: 0.17MB + Engine InnoDB
wp_e_notes_users_relations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_e_submissions: Data: 0.02MB + Index: 0.27MB + Engine InnoDB
wp_e_submissions_actions_log: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_e_submissions_values: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_formsync_gf_feed_uuids: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gf_addon_feed: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_gf_draft_submissions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_gf_entry: Data: 0.08MB + Index: 0.03MB + Engine InnoDB
wp_gf_entry_meta: Data: 0.23MB + Index: 0.25MB + Engine InnoDB
wp_gf_entry_notes: Data: 0.08MB + Index: 0.03MB + Engine InnoDB
wp_gf_form: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gf_form_meta: Data: 0.42MB + Index: 0.00MB + Engine InnoDB
wp_gf_form_revisions: Data: 0.08MB + Index: 0.03MB + Engine InnoDB
wp_gf_form_view: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_gf_rest_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_iugo_membership_kiosk_log: Data: 95.64MB + Index: 8.58MB + Engine InnoDB
wp_iugo_membership_kiosk_redirects: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_iugo_membership_kiosk_session: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 14.08MB + Index: 0.27MB + Engine InnoDB
wp_pmxe_exports: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pmxe_google_cats: Data: 0.39MB + Index: 0.00MB + Engine InnoDB
wp_pmxe_posts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pmxe_templates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_files: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_hash: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_history: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_images: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_imports: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_posts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_templates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_postmeta: Data: 43.23MB + Index: 14.55MB + Engine InnoDB
wp_posts: Data: 9.52MB + Index: 0.70MB + Engine InnoDB
wp_prevent_direct_access_free: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_saml_idp_audit_log: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_say_what_available_strings: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_say_what_strings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_say_what_wildcards: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_searchwp_index: Data: 4.52MB + Index: 9.06MB + Engine InnoDB
wp_searchwp_log: Data: 0.08MB + Index: 0.11MB + Engine InnoDB
wp_searchwp_status: Data: 0.05MB + Index: 0.05MB + Engine InnoDB
wp_searchwp_tokens: Data: 1.52MB + Index: 1.05MB + Engine InnoDB
wp_shepherd_tec_tasks: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_signups: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_tec_events: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_tec_kv_cache: Data: 1.02MB + Index: 0.00MB + Engine InnoDB
wp_tec_occurrences: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_tec_posts_and_ticket_groups: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_tec_series_relationships: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_tec_slr_layouts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_tec_slr_maps: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_tec_slr_seat_types: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_tec_slr_sessions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_tec_ticket_groups: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_tec_waitlist_pending_users: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_tec_waitlist_subscribers: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_tec_waitlists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.08MB + Index: 0.05MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.39MB + Index: 0.42MB + Engine InnoDB
wp_users: Data: 0.05MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.09MB + Index: 0.02MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.14MB + Index: 0.00MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_addresses: Data: 0.05MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_operational_data: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_orders: Data: 0.08MB + Index: 0.14MB + Engine InnoDB
wp_wc_orders_meta: Data: 0.27MB + Index: 0.45MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfauditevents: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfblockediplog: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfblocks7: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wfconfig: Data: 1.45MB + Index: 0.00MB + Engine InnoDB
wp_wfcrawlers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wffilechanges: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfFileMods: Data: 11.55MB + Index: 0.00MB + Engine InnoDB
wp_wfhits: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wfhoover: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfissues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wfknownfilelist: Data: 8.52MB + Index: 0.00MB + Engine InnoDB
wp_wflivetraffichuman: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wflocs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wflogins: Data: 0.30MB + Index: 0.13MB + Engine InnoDB
wp_wfls_2fa_secrets: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfls_role_counts: Data: 0.00MB + Index: 0.00MB + Engine MEMORY
wp_wfls_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfnotifications: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfpendingissues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wfreversecache: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfsecurityevents: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfsnipcache: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wfstatus: Data: 0.13MB + Index: 0.09MB + Engine InnoDB
wp_wftrafficrates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfwaffailures: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_yoast_indexable: Data: 0.28MB + Index: 0.23MB + Engine InnoDB
wp_yoast_indexable_hierarchy: Data: 0.08MB + Index: 0.08MB + Engine InnoDB
wp_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_primary_term: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_yoast_seo_links: Data: 1.52MB + Index: 0.41MB + Engine InnoDB

### Post Type Counts ###

acf-field: 11
acf-field-group: 2
acf-post-type: 1
attachment: 577
bnfw_notification: 4
custom_css: 1
customize_changeset: 126
e-landing-page: 2
elementor_font: 11
elementor_library: 162
elementor_snippet: 1
nav_menu_item: 69
newsroom: 68
oembed_cache: 2
offer: 2
page: 282
post: 16
product: 50
promo-section: 4
resource: 1
resources: 86
revision: 2112
segment: 3
shop_coupon: 3
shop_order_placehold: 146
ticket-meta-fieldset: 2
tribe_events: 35
tribe_venue: 7
tribe_wooticket: 127
wp_font_face: 33
wp_font_family: 12

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (55) ###

Advanced Custom Fields: Gravity Forms Add-on: by Say Hello GmbH – 1.3.10
Action Scheduler - Disable Default Queue Runner: by Prospress Inc. – 1.0.0
Advanced Custom Fields: Font Awesome: by Justin Kruit
Matt Keys – 5.0.2

Advanced Custom Fields PRO: by WP Engine – 6.8.0
Agend Apps Core: by Agend – 1.0.0
Agend Apps Shop: by Agend – 1.0.0
Agend Committees Extension: by Iugo Pty Ltd – 1.7.1
Agend LearnUpon Integration: by Iugo Pty Ltd – 1.1.0
WordPress SAML Identity Provider by Agend systems: by <a href="https://agend.com.au/">Agend systems</a> – 1.1.0
Better Notifications for WP: by Made with Fuel – 1.9.9.1
CatFolders Pro - WP Media Folders: by CatFolders – 2.5
Classic Editor: by WordPress Contributors – 1.6.7
Classic Widgets: by WordPress Contributors – 0.3
Yoast Duplicate Post: by Enrico Battocchi & Team Yoast – 4.6
Elementor Pro: by Elementor.com – 4.0.0
Elementor: by Elementor.com – 4.0.0
Enable Media Replace: by ShortPixel – 4.1.8
Event Tickets Plus: by The Events Calendar – 6.9.2
Event Tickets: by The Events Calendar – 5.27.5
The Events Calendar Pro: by The Events Calendar – 7.7.14
FormSync: by Ren Ventura – 0.7.0
GP Populate Anything: by Gravity Wiz – 2.1.63
Gravity Forms: by Gravity Forms – 2.9.30
Gravity Forms CLI: by Rocketgenius – 1.7
Gravity Forms User Registration Add-On: by Gravity Forms – 5.4.0
GP Auto Login: by Gravity Wiz – 2.2.6
GP Read Only: by Gravity Wiz – 1.9.29
GP Terms of Service: by Gravity Wiz – 1.4.9
If Menu - Visibility control for menus: by Layered – 0.19.2
ISNSW Plugin: by Iugo Pty Ltd – 1.0.0
Agend Product Integrations: by Iugo Pty Ltd – 1.190.1
Agend Membership: by Iugo Pty Ltd – 1.230.0
Prevent Direct Access: by BWPS – 2.8.8.6
Redirection: by John Godley – 5.7.5
Safe SVG: by 10up – 2.4.0
Say What?: by Ademti Software – 2.2.6
SearchWP Exclude UI: by SearchWP – 1.2.3
SearchWP WooCommerce Integration: by SearchWP – 1.3.12
SearchWP: by SearchWP – 4.5.9
Spellbook: by Gravity Wiz – 3.0.20
The Events Calendar: Filter Bar: by The Events Calendar – 5.6.3
The Events Calendar: by The Events Calendar – 6.15.18
User Switching: by John Blackbourn – 1.11.2
WooCommerce.com Update Manager: by Automattic – 1.0.3
WooCommerce Checkout Field Editor: by WooCommerce – 1.7.25
WooCommerce CyberSource Gateway: by SkyVerge – 2.10.1 (update to version 2.10.2 is available)
WooCommerce: by Automattic – 10.6.1 (update to version 10.7.0 is available)
Wordfence Security: by Wordfence – 8.1.4
Iugo Common Wordpress Functionality: by Iugo Pty Ltd – 0.27.0
Agend Content Personalisation: by Iugo Pty Ltd – 1.22.0
Yoast SEO: by Team Yoast – 27.2
WordPress Update CLI scripts: by Iugo Pty Ltd – 1.0.0
WP All Export - ACF Export Add-On: by Soflyy – 1.0.1
WP All Export Pro: by Soflyy – 1.9.15
WP All Export - ACF Export Add-On Pro: by Soflyy – 2.0.0

### Inactive Plugins (5) ###

Agend CPD Extension: by Iugo Pty Ltd – 1.21.0
GP Advanced Select: by Gravity Wiz – 1.1.19
Mailgun: by Mailgun – 2.1.10
Rollbar: by Rollbar – 3.1.1
Simple CAPTCHA Alternative with Cloudflare Turnstile: by Elliot Sowersby
RelyWP – 1.37.0

### Dropin Plugins () ###

advanced-cache.php: advanced-cache.php

### Settings ###

Legacy API Enabled: –
Force SSL: ✔
Currency: AUD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: event_crm_product (event_crm_product)
external (external)
grouped (grouped)
renewal_crm_product (renewal_crm_product)
simple (simple)
simple_crm_product (simple_crm_product)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: –
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –
Enabled Features: marketplace
custom_order_tables

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 3 MB

### WC Pages ###

Shop base: ❌ Page visibility should be public
Cart: #11 - /cart -  Contains the [woocommerce_cart] shortcode
Checkout: #13 - /checkout -  Contains the [woocommerce_checkout] shortcode
My account: #15 - /my-account -  Contains the [woocommerce_my_account] shortcode
Terms and conditions: #17 - /terms-and-conditions

### Theme ###

Name: Agend Theme
Version: 1.53.0
Author URL: https://www.iugo.com.au/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build
personally we recommend using a child theme. See: How to create a child theme

Theme type: Classic theme
WooCommerce Support: ✔

### Templates ###

Overrides: wordpress-theme-agend/woocommerce/emails/customer-reset-password.php
wordpress-theme-agend/woocommerce/global/wrapper-end.php
wordpress-theme-agend/woocommerce/global/wrapper-start.php
wordpress-theme-agend/woocommerce/loop/pagination.php
wordpress-theme-agend/woocommerce/myaccount/dashboard.php
wordpress-theme-agend/woocommerce/myaccount/my-account.php
wordpress-theme-agend/woocommerce/myaccount/navigation.php
wordpress-theme-agend/woocommerce/notices/error.php
wordpress-theme-agend/woocommerce/notices/notice.php
wordpress-theme-agend/woocommerce/notices/success.php

### CyberSource Credit Card ###

Environment: Test
Tokenization Enabled: ✔
Debug Mode: Off

### Admin ###

Enabled Features: activity-panels
analytics
analytics-scheduled-import
product-block-editor
experimental-iapi-mini-cart
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
onboarding
onboarding-tasks
pattern-toolkit-full-composability
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
printful
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page
launch-your-store

Disabled Features: product-data-views
experimental-blocks
experimental-iapi-runtime
coming-soon-newsletter-template
minified-js
product-pre-publish-modal
products-catalog-api
settings
async-product-editor-category-field
product-editor-template-system
use-wp-horizon
rest-api-v4

Daily Cron: ✔ Next scheduled: 2025-11-08 00:21:08 +11:00
Options: ✔
Notes: 234
Onboarding: completed

### Action Scheduler ###

Complete: 585
Oldest: 2025-10-07 12:05:06 +1100
Newest: 2026-03-18 13:40:53 +1100

Pending: 191
Oldest: 2025-11-07 14:12:44 +1100
Newest: 2026-04-09 17:12:01 +1000

Failed: 1,310
Oldest: 2024-05-07 19:10:04 +1000
Newest: 2025-10-31 12:25:03 +1100

Cancelled: 17
Oldest: 2025-10-31 12:20:05 +1100
Newest: -0001-11-30 10:04:52 +1004

### Status report information ###

Generated at: 2026-04-15 09:48:52 +10:00
`

### Isolating the problem

- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by mikejolley**
### Submission Review Guidelines:

- I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
- I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
- I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
- Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

In `templates/cart/cart.php`, `$_product->get_name()` was called before the `if ( $_product && $_product->exists() ... )` validity check, so a filter hooked onto `woocommerce_cart_item_product` that returns anything other than a `WC_Product` (e.g. `false`) caused a fatal error. This PR moves the `$product_name` assignment inside the existing validity check, matching the pattern already used in `cart/mini-cart.php` and `checkout/review-order.php`.

Closes #64156.

### How to test the changes in this Pull Request:

1. Add any product to the cart.
2. In a snippet or `functions.php`, add:
   ```php
   add_filter( 'woocommerce_cart_item_product', function () {
       return false;
   } );
   ```
3. Visit the Cart page.
4. **Expected:** The cart renders without any row for the affected item and no fatal error. **Before this PR:** a fatal "Call to a member function get_name() on bool" error occurs.
5. Remove the snippet, reload the cart, and confirm the product row renders normally.

### Testing that has already taken place:

- Manually reproduced the fatal error on trunk using the snippet above and confirmed the patched template renders without error.
- `pnpm --filter=@woocommerce/plugin-woocommerce lint:php:changes` and `lint:changes:branch` — clean.

### Milestone

- [x] Automatically assign milestone for the **[next WooCommerce version](../blob/trunk/plugins/woocommerce/woocommerce.php#L6)**

> **Note:** Check the box above to have the milestone automatically assigned when merged.
> Alternatively (e.g. for point releases), manually assign the appropriate milestone.

### Changelog entry

Changelog entry added manually in `plugins/woocommerce/changelog/wooplug-6544-cart-template-null-product`.

### CODE REVIEW

File: plugins/woocommerce/templates/cart/cart.php [hunk 1]
```diff
@@ -40,17 +40,27 @@
...
+				 * @param bool   $visible     Whether the cart item is visible. Default true.
+				 * @param array  $cart_item     The cart item data.
+				 * @param string $cart_item_key The cart item key.
 				 */
-				$product_name = apply_filters( 'woocommerce_cart_item_name', $_product->get_name(), $cart_item, $cart_item_key );
-
-				if ( $_product && $_product->exists() && $cart_item['quantity'] > 0 && apply_filters( 'woocommerce_cart_item_visible', true, $cart_item, $cart_item_key ) ) {
+				$visible = apply_filters( 'woocommerce_cart_item_visible', true, $cart_item, $cart_item_key );
+
+				if ( $_product instanceof WC_Product && $_product->exists() && $cart_item['quantity'] > 0 && $visible ) {
```
Comment (ralucaStan) [inline plugins/woocommerce/templates/cart/cart.php:54]: `$_product instanceof WC_Product`, this guard is not aligned with the Mini-Cart or Review order. I'd skip it if there isn't a strong reason for it, because the fatal is avoided without it and we keep the alignment with the other surface areas.

**Review by ralucaStan — CHANGES_REQUESTED** [review]
I've tested the PR and the fatal is not happening anymore.

I don't like the empty cart experience that shows a total, but the behaviour isn't introduced by this PR. Since returning false from the filter is not supported, I don't think we should handle this edge case in the template.
Image

I left another comment.

Thank you, Mike!

File: plugins/woocommerce/templates/cart/cart.php (hunk 1 above)
Comment (mikejolley) [reply plugins/woocommerce/templates/cart/cart.php:54]: @ralucaStan its not aligned but its needed in order to be defensive against filter misuse (returning any value other than product). Other locations should be hardened to match but I didn't want to increase scope of this fix.

Comment (ralucaStan) [reply plugins/woocommerce/templates/cart/cart.php:54]: Could you create a follow-up PR for the remaining changes? I'll approve this one.

**Review by ralucaStan — APPROVED** [review]
Approving with the note that a follow-up PR should be done to also use `$_product instanceof WC_Product` in the Mini-Cart, etc.
