### PR TITLE
Avoid JS errors if Sourcebuster library isn't loaded

### LINKED ISSUE #45569: sbjs is undefined - JS error when sourcebuster.js script is blocked by Cookie Compliance plugins
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Opening this issue after discussion on Slack p1710313840148399-slack-C7U3Y3VMY

Originally reported on 7852179-zen

If any cookie compliance plugin classifies the Source Buster script as marketing script and blocks it, the references to sbjs function throws `sbjs is undefined` error. 

> We seem to be getting some JS errors with your Order Attribution feature when cookie compliance is active and the customers have not accepted cookies.

> sbjs is undefined on line https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/client/legacy/js/frontend/order-attribution.js#L25 or https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/client/legacy/js/frontend/order-attribution.js#L70 within the unminified file as linked above, or the minified file that is distributed with released versions of the plugins.

> the code relies on sourcebuster to be loaded ( https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/src/Internal/Orders/OrderAttributionController.php#L225-L231 ) but including cookie consent plugins ( cookie yes for example ) this JS will be blocked, so the above JS will say sbjs undefined.

> the code in order-attribution.js can check if the source buster object is loaded, and do the code only if the object is loaded

It is seen that scripts like Sourcebuster can be blocked by security and compliance tools.

We've discussed this and @layoutd has come up with a workaround snippet for compatibility with CookieYes https://gist.github.com/layoutd/c8be62b2507ce4995789b4e9ba9f275e

### PR DESCRIPTION
**Pull request by layoutd**
### Changes proposed in this Pull Request:

This just adds a bailout in the Order Attribution initialization process that catches a missing Sourcebuster-JS library (not loaded or blocked by a consent management plugin) and skips any `sbjs` object operations, preventing a JavaScript error.

Closes #45569.

### How to test the changes in this Pull Request:
**Quick local test**
1. Install this branch. 
2. Make the Sourcebuster.js library unavailable:
   - Rename the files `woocommerce/assets/js/frontend/order-attribution.js` and `woocommerce/assets/js/frontend/order-attribution.min.js` so they aren't loaded
   - Or, change the name in `woocommerce/src/Internal/Orders/OrderAttributionController.php::227` so that WooCommerce tries to load the wrong file.
4. In the current implementation, this will throw an error:
`Uncaught ReferenceError: sbjs is not defined`
5. With this bailout, the error will be that the Sourcebuster library can't be loaded `GET … sourcebuster.min.js 404 (Not Found)` but no JavaScript error.
6. Make a purchase at the store and confirm that there are no errors, and the Order origin is "Unknown"
image

7. Make the Sourcebuster library available again (undoing step 2). Visit the store with some UTM params, like `?utm_source=TEST_SOURCE`
8. After a checkout, confirm that the source is assigned correctly to the order:
image

**CookieYes**
There's also JN site with CookieYes installed and actively blocking the Sourcebuster library.
1. Visit `https://fixed-pine.jurassic.ninja/shop/` (valid through 24 April)
2. Confirm that the CookieYes consent popup displays:
image
3. Check there are no JS errors in the console.
4. Check that no cookies are created besides `cookieyes-consent`:
image
5. Complete a checkout to confirm no errors. Check the order has no origin info.
6. Load the shop again, accept the cookies, and RELOAD with the UTM params (CookieYes doesn't currently load origin info on consent events, so there needs to be a reload after accepting the cookies).
7. Confirm the `sbjs` cookies are created, complete checkout, and confirm that the origin is added correctly.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce/client/legacy/js/frontend/order-attribution.js [hunk 1]
```diff
@@ -65,6 +65,8 @@
 		if ( ! allow ) {
 			// Reset cookies, and clear form data.
 			removeTrackingCookies();
+		} else if ( typeof sbjs === 'undefined' ) {
+			return; // Do nothing, as sourcebuster.js is not loaded.
```
Comment (rawdreeg) [inline plugins/woocommerce/client/legacy/js/frontend/order-attribution.js:69]: Why isn't the check the beginning of setOrderTracking(), like:

```
wc_order_attribution.setOrderTracking = function( allow ) {
 if ( typeof sbjs === 'undefined' ) {
    return;			
 }
 
 if ( ! allow ) {
    // Reset cookies, and clear form data.
    removeTrackingCookies();
  }
  ....
 }
 ```
 We still want to removeTrackingCookies(); if not allow, I presume?

Comment (layoutd) [reply plugins/woocommerce/client/legacy/js/frontend/order-attribution.js:69]: Yeah, in theory it would be to handle the case where a user accepted cookies, then went back and changed their preferences. The Sourcebuster library wouldn't be loaded, but still should remove any existing cookies.

**Review by rawdreeg — APPROVED** [review]
Thanks @layoutd . This fixes the issue.
