### PR TITLE
Verify country code on checkout

### LINKED ISSUE #27521: Customer can check out although mandatory field "Country" is not given
Tested with 4.4.1
A customer can check out even if he omits the mandatory field "Country".

**Describe the bug**
Put a product in the cart, checkout. Enter all data just leave the Country field blank.
There will be no error and the order goes through, although no country is provided and "Country" is marked as mandatory field with an asterisk.

**Expected behavior**
An error message should appear, making clear that "Country" is a mandatory field.

**Actual behavior**
The order goes though, in the backend the Country fields for Shipping and Billing Address will have the entry "default". 
Any invoice gets the wrong "default" string also which violates tax laws in many countries.

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Make an order
2. Leave Country blank
3. Submit the order
4. Check the backend.

**WordPress Environment**
<details>
### WordPress Environment ###

WC Version: 4.4.1
REST API Version: ✔ 1.0.15
WC Blocks Version: ✔ 3.1.0
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.4.0
Log Directory Writable: ✔
WP Version: 5.5
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.3.21
PHP Post Max Size: 200 MB
PHP Time Limit: 900
PHP Max Input Vars: 20000
cURL Version: 7.61.1
OpenSSL/1.1.1c

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.3.17-MariaDB
Max Upload Size: 200 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.4.1
WC Database Prefix: wp_lrt_
Total Database Size: 1056.11MB
Database Data Size: 803.13MB
Database Index Size: 252.98MB
wp_lrt_woocommerce_sessions: Data: 4.02MB + Index: 0.13MB + Engine InnoDB
wp_lrt_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_lrt_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_lrt_woocommerce_downloadable_product_permissions: Data: 1.49MB + Index: 1.50MB + Engine MyISAM
wp_lrt_woocommerce_order_items: Data: 3.21MB + Index: 1.57MB + Engine MyISAM
wp_lrt_woocommerce_order_itemmeta: Data: 21.59MB + Index: 13.67MB + Engine MyISAM
wp_lrt_woocommerce_tax_rates: Data: 0.01MB + Index: 0.02MB + Engine MyISAM
wp_lrt_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_lrt_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_lrt_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_lrt_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_lrt_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_lrt_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_lrt_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_lrt_actionscheduler_actions: Data: 0.45MB + Index: 0.50MB + Engine InnoDB
wp_lrt_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_lrt_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_lrt_actionscheduler_logs: Data: 0.36MB + Index: 0.23MB + Engine InnoDB
wp_lrt_affiliates_banners_tbl: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_lrt_affiliates_clickthroughs_tbl: Data: 38.12MB + Index: 0.00MB + Engine MyISAM
wp_lrt_affiliates_leads_tbl: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_lrt_affiliates_payouts_tbl: Data: 0.02MB + Index: 0.00MB + Engine MyISAM
wp_lrt_affiliates_relations_tbl: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_lrt_affiliates_sales_tbl: Data: 0.27MB + Index: 0.00MB + Engine MyISAM
wp_lrt_affiliates_tbl: Data: 0.07MB + Index: 0.01MB + Engine MyISAM
wp_lrt_affiliates_user_link_tbl: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_lrt_commentmeta: Data: 31.34MB + Index: 16.78MB + Engine MyISAM
wp_lrt_comments: Data: 131.80MB + Index: 23.24MB + Engine MyISAM
wp_lrt_dlm_order: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_lrt_dlm_order_customer: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_lrt_dlm_order_item: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_lrt_dlm_order_transaction: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_lrt_dlm_session: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_lrt_download_log: Data: 192.73MB + Index: 20.55MB + Engine InnoDB
wp_lrt_icl_content_status: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_lrt_icl_core_status: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_lrt_icl_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_lrt_icl_languages: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_lrt_icl_languages_translations: Data: 0.19MB + Index: 0.08MB + Engine InnoDB
wp_lrt_icl_locale_map: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_lrt_icl_message_status: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_lrt_icl_mo_files_domains: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_lrt_icl_node: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_lrt_icl_reminders: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_lrt_icl_strings: Data: 5.52MB + Index: 6.89MB + Engine InnoDB
wp_lrt_icl_string_packages: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_lrt_icl_string_pages: Data: 5.52MB + Index: 7.03MB + Engine InnoDB
wp_lrt_icl_string_positions: Data: 1.52MB + Index: 0.16MB + Engine InnoDB
wp_lrt_icl_string_status: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_lrt_icl_string_translations: Data: 3.52MB + Index: 1.89MB + Engine InnoDB
wp_lrt_icl_string_urls: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_lrt_icl_translate: Data: 7.52MB + Index: 0.09MB + Engine InnoDB
wp_lrt_icl_translate_job: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_lrt_icl_translations: Data: 7.52MB + Index: 14.06MB + Engine InnoDB
wp_lrt_icl_translation_batches: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_lrt_icl_translation_downloads: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_lrt_icl_translation_status: Data: 2.52MB + Index: 0.02MB + Engine InnoDB
wp_lrt_links: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_lrt_newsletter: Data: 4.52MB + Index: 1.75MB + Engine InnoDB
wp_lrt_newsletter_emails: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
wp_lrt_newsletter_sent: Data: 9.86MB + Index: 14.80MB + Engine MyISAM
wp_lrt_newsletter_stats: Data: 40.55MB + Index: 16.03MB + Engine InnoDB
wp_lrt_newsletter_user_logs: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
wp_lrt_options: Data: 6.66MB + Index: 0.15MB + Engine MyISAM
wp_lrt_postmeta: Data: 178.67MB + Index: 68.05MB + Engine MyISAM
wp_lrt_posts: Data: 26.31MB + Index: 3.08MB + Engine MyISAM
wp_lrt_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_lrt_terms: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_lrt_term_relationships: Data: 0.01MB + Index: 0.02MB + Engine MyISAM
wp_lrt_term_taxonomy: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_lrt_usermeta: Data: 38.80MB + Index: 22.11MB + Engine MyISAM
wp_lrt_users: Data: 1.91MB + Index: 1.61MB + Engine MyISAM
wp_lrt_wcpdf_credit_note_number: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_lrt_wcpdf_invoice_number: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_lrt_wcpdf_proforma_number: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_lrt_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_lrt_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_lrt_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_lrt_wc_customer_lookup: Data: 4.52MB + Index: 3.03MB + Engine InnoDB
wp_lrt_wc_download_log: Data: 0.34MB + Index: 0.27MB + Engine InnoDB
wp_lrt_wc_order_coupon_lookup: Data: 0.08MB + Index: 0.09MB + Engine InnoDB
wp_lrt_wc_order_product_lookup: Data: 5.52MB + Index: 6.06MB + Engine InnoDB
wp_lrt_wc_order_stats: Data: 5.52MB + Index: 4.55MB + Engine InnoDB
wp_lrt_wc_order_tax_lookup: Data: 1.52MB + Index: 0.70MB + Engine InnoDB
wp_lrt_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_lrt_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_lrt_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_lrt_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_lrt_wfBlockedIPLog: Data: 0.09MB + Index: 0.00MB + Engine InnoDB
wp_lrt_wfBlocks7: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_lrt_wfConfig: Data: 2.23MB + Index: 0.00MB + Engine InnoDB
wp_lrt_wfCrawlers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_lrt_wfFileChanges: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_lrt_wfFileMods: Data: 5.52MB + Index: 0.00MB + Engine InnoDB
wp_lrt_wfHits: Data: 1.02MB + Index: 0.22MB + Engine InnoDB
wp_lrt_wfHoover: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_lrt_wfIssues: Data: 0.05MB + Index: 0.06MB + Engine InnoDB
wp_lrt_wfKnownFileList: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
wp_lrt_wfLiveTrafficHuman: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_lrt_wfLocs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_lrt_wfLogins: Data: 0.39MB + Index: 0.13MB + Engine InnoDB
wp_lrt_wfls_2fa_secrets: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_lrt_wfls_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_lrt_wfNotifications: Data: 0.13MB + Index: 0.00MB + Engine InnoDB
wp_lrt_wfPendingIssues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_lrt_wfReverseCache: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_lrt_wfSNIPCache: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_lrt_wfStatus: Data: 0.17MB + Index: 0.11MB + Engine InnoDB
wp_lrt_wfTrafficRates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_lrt_yoast_indexable: Data: 2.52MB + Index: 0.70MB + Engine InnoDB
wp_lrt_yoast_indexable_hierarchy: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_lrt_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_lrt_yoast_primary_term: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_lrt_yoast_seo_links: Data: 0.16MB + Index: 0.06MB + Engine InnoDB
wp_lrt_yoast_seo_meta: Data: 0.06MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

attachment: 814
dlm_download: 23
dlm_download_version: 143
nav_menu_item: 44
oembed_cache: 93
page: 111
post: 82
product: 39
revision: 2484
shop_coupon: 67
shop_order: 37776
shop_order_refund: 366
user_request: 2
wpcf7_contact_form: 5

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (43) ###

WPML Multilingual CMS: by OnTheGoSystems – 4.3.19
Yoast SEO Multilingual: by OnTheGoSystems – 1.2.2
Affiliates WooCommerce Advanced Integration: by Tips and Tricks HQ – 1.8 – Installed version not tested with active version of WooCommerce 4.4.1
AMP: by AMP Project Contributors – 2.0.0
Antispam Bee: by pluginkollektiv – 2.9.2
Classic Editor: by WordPress Contributors – 1.6
CMS Tree Page View: by Jon Christopher – 1.6.1
Configure SMTP: by Scott Reilly – 3.1
Contact Form 7: by Takayuki Miyoshi – 5.2.2
Content Anchor Links: by Roland Barker
xnau webdesign – 1.6.2

Download Monitor: by Never5 – 4.4.3
Facebook Like Thumbnail: by Ashfame – 0.4
Geolocation IP Detection: by Yellow Tree (Benjamin Pick) – 3.1.1
gw News Widget: by Gunther Wegner – 1.0
Lazy Load for Videos: by Kevin Weber – 2.8.7
Limit Login Attempts: by Johan Eenfeldt – 1.7.1
Newsletter - Addons Manager: by The Newsletter Team – 1.1.3
Newsletter - Feed by Mail: by The Newsletter Team – 4.1.1
Newsletter - Reports and Retargeting: by The Newsletter Team – 4.3.7
Newsletter: by Stefano Lissa & The Newsletter Team – 6.8.7
Quick Page/Post Redirect Plugin: by anadnet – 5.2.0
Rel Nofollow Checkbox: by Fabio Santos – 1.1.5
Replace Content Image Size: by Pau Iglesias
Blogestudio – 1.2.1

Responsive Lightbox & Gallery: by dFactory – 2.2.3.1
Simple Image Sizes: by Rahe – 3.2.1
PayPal PLUS for WooCommerce: by Inpsyde GmbH – 2.2.1 – Installed version not tested with active version of WooCommerce 4.4.1
WooCommerce Customer/Order CSV Export: by SkyVerge – 4.3.5 – Installed version not tested with active version of WooCommerce 4.4.1
WooCommerce Email Validation: by Hugh Lashbrooke – 2.1.1 – Installed version not tested with active version of WooCommerce 4.4.1
WooCommerce EU VAT Compliance (Premium): by David Anderson – 1.14.13 – Installed version not tested with active version of WooCommerce 4.4.1
WooCommerce PayPal Checkout Gateway: by WooCommerce – 2.0.3 – Installed version not tested with active version of WooCommerce 4.4.1
WooCommerce Multi Currency Premium: by VillaTheme – 2.1.9.4 – Installed version not tested with active version of WooCommerce 4.4.1
WooCommerce Multilingual: by OnTheGoSystems – 4.10.2
WooCommerce PDF Invoices & Packing Slips: by Ewout Fernhout – 2.6.0
WooCommerce PDF Invoices & Packing Slips Professional: by Ewout Fernhout – 2.6.5
WooCommerce: by Automattic – 4.4.1
Wordfence Security: by Wordfence – 7.4.11
WordPress Post Tabs: by Internet Techies
Tejaswini Deshpande – 1.6.3

WP Affiliate Platform: by Tips and Tricks HQ
Ruhul Amin – 6.2.4

WPML Media: by OnTheGoSystems – 2.5.6
WPML String Translation: by OnTheGoSystems – 3.0.14
WPML Translation Management: by OnTheGoSystems – 2.9.11
WP Overnight Sidekick: by Jeremiah Prummer
Ewout Fernhout
Michael Kluver – 2.2.1

WPS Hide Login: by WPServeur
NicolasKulka
tabrisrp – 1.5.6

### Inactive Plugins (3) ###

Shariff Wrapper: by Jan-Peter Lambeck & 3UU – 4.6.5
WP Staging: by WP-Staging – 2.7.5
Yoast SEO: by Team Yoast – 14.8.1

### Dropin Plugins (1) ###

maintenance.php: maintenance.php

### Must Use Plugins (1) ###

WP Staging Optimizer: by René Hermenau – 1.1

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
featured (featured-2)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #1233 - /products/
Cart: #1244 - /cart/
Checkout: #1245 - /checkout/
My account: #1246 - /my-account/
Terms and conditions: #346 - /eula/

### Theme ###

Name: lrt-woo
Version: 1.1
Author URL: 
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Customer/Order CSV Export ###

Order Export Format: custom
Customer Export Format: default
Automatically Export Orders: disabled
Automatically Export Customers: disabled

### Action Scheduler ###

Complete: 1,663
Oldest: 2020-07-29 17:21:57 +0200
Newest: 2020-08-29 14:56:33 +0200

Pending: 1
Oldest: 2020-09-03 09:18:00 +0200
Newest: 2020-09-03 09:18:00 +0200
</details>

### PR DESCRIPTION
**Pull request by Konamiman**
### All Submissions:

* [ ] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [ ] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Currently the checkout process doesn't validate if the posted country codes (in `billing_country` and `shipping_country` POST keys) actually exist, so it's possible to post a non-existing country code e.g. "XX" and it will be recorded as such in the billing or shipping address. This pull request adds validation for these keys in the checkout process.

Closes #27521.

### How to test the changes in this Pull Request:

1. Start with `master`.
2. Add the following at the end of `woocommerce.php` to simulate tampering with the form data:

```php
if ( array_key_exists( 'billing_country', $_POST ) ) $_POST['billing_country'] = 'XX';
if ( array_key_exists( 'shipping_country', $_POST ) ) $_POST['shipping_country'] = 'YY';
```

3. Place an order where the shipping address is the same as the billing address. The checkout will succeed, go check the order details and see that the country in the billing address is "XX".
4. Switch to this branch.
5. Repeat 3. Now the checkout should fail with a _'XX' is not a valid country code_ error.
6. Place an order where the shipping address is different from the billing address. Now there are two errors on checkout, one for 'XX' and another one for 'YY'.
7. Remove the hack on `woocommerce.php`, try to complete checkout without specifying a country and verify that the error message is still the proper one ("is a required field").

### Other information:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully run tests with your changes locally?

### Changelog entry

> Fix - add validation of the posted country codes on checkout

### CODE REVIEW

File: includes/class-wc-countries.php [hunk 1]
```diff
@@ -57,6 +57,24 @@ public function get_countries() {
...
+	 * @param string $country_code The country code to check as a ISO 3166-1 alpha-2 code.
+	 * @param bool   $throw True to throw an exception if the country code isn't recognized.
+	 * @return bool True if the country is known to us, false otherwise.
+	 * @throws Exception The country code isn't recognized, and the $throw argument was passed as true.
+	 */
+	public function country_exists( $country_code, $throw = false ) {
+		$exists = array_key_exists( $country_code, $this->get_countries() );
+		if ( ! $exists && $throw ) {
+			/* translators: %s: ISO 3166-1 alpha-2 country code. */
+			throw new Exception( sprintf( __( "'%s' is not a valid country code", 'woocommerce' ), $country_code ) );
```
Comment (vedanshujain) [inline includes/class-wc-countries.php:73]: what do you think about moving the exception throwing logic to the parent code, to make the code there more directly readable?

**Review by vedanshujain — COMMENTED** [review]
Looks good and testing well. Thanks for update to coding standards as well.

Left a minor comment, and can we also add unit tests for this?

File: includes/class-wc-countries.php (hunk 1 above)
Comment (Konamiman) [reply includes/class-wc-countries.php]: I was trying to provide a centralized point for exceptioning, but sure, readabilty is important. I've done the change.

File: includes/class-wc-checkout.php [hunk 2]
```diff
@@ -825,12 +827,20 @@ protected function validate_posted_data( &$data, &$errors ) {
...
 	 * @param  array    $data   An array of posted data.
 	 * @param  WP_Error $errors Validation errors.
+	 * @throws Exception Invalid country code in billing or shipping address.
 	 */
 	protected function validate_checkout( &$data, &$errors ) {
 		$this->validate_posted_data( $data, $errors );
 		$this->check_cart_items();
 
-		if ( empty( $data['woocommerce_checkout_update_totals'] ) && empty( $data['terms'] ) && ! empty( $_POST['terms-field'] ) ) { // WPCS: input var ok, CSRF ok.
+		$billing_country = WC()->customer->get_shipping_country();
```
Comment (vedanshujain) [inline includes/class-wc-checkout.php:836]: Looking at line https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-checkout.php#L759 it seems like this method is used as a fallback and not as default way to get country address (unless cart needs shipping). Perhaps we should move these checks to inside `validate_posted_data` method only if country is a required field (it might not be for some shops, I think looking at the linked code).

File: includes/class-wc-checkout.php [hunk 3]
```diff
@@ -825,12 +827,20 @@ protected function validate_posted_data( &$data, &$errors ) {
...
+		if ( ! WC()->countries->country_exists( $billing_country ) ) {
+			/* translators: %s: ISO 3166-1 alpha-2 country code. */
+			throw new Exception( sprintf( __( "'%s' is not a valid country code", 'woocommerce' ), $billing_country ) );
```
Comment (vedanshujain) [inline includes/class-wc-checkout.php:839]: instead of throwing immediately, should we be doing `$errors->add( $key . '_validation', ... );` to be consistent with other usages in this class?

**Review by vedanshujain — COMMENTED** [review]
Thanks for updating, I noticed that country _might_ be optional in some cases, left couple of minor comments to that effect.
Also, can we add unit tests for this?

File: includes/class-wc-countries.php [hunk 4]
```diff
@@ -57,6 +57,17 @@ public function get_countries() {
...
 
+	/**
+	 * Check if a given code represents a valid ISO 3166-1 alpha-2 code for a country known to us.
+	 *
+	 * @since 5.1.0
+	 * @param string $country_code The country code to check as a ISO 3166-1 alpha-2 code.
+	 * @return bool True if the country is known to us, false otherwise.
+	 */
+	public function country_exists( $country_code ) {
+		return array_key_exists( $country_code, $this->get_countries() );
```
Comment (superdav42) [inline includes/class-wc-countries.php:68]:
```suggestion
		return isset( $country_code, $this->get_countries() );
```
Since `isset` is a language construct it is slightly faster than calling the function `array_key_exists`. You only need to use array_key_exists if might be dealing with an array which contains null values. See https://www.php.net/manual/en/function.array-key-exists.php#example-5434

File: includes/class-wc-checkout.php (hunk 2 above)
Comment (Konamiman) [reply includes/class-wc-checkout.php:836]: I see an inconsistency here. On one hand the `validate_posted_data` method is doing

```php
$country = isset( $data[ $fieldset_key . '_country' ] ) ? $data[ $fieldset_key . '_country' ] : WC()->customer->{"get_{$fieldset_key}_country"}();
```

but on the other hand the `validate_checkout` method does just

```php
if ( WC()->cart->needs_shipping() ) {
	$shipping_country = WC()->customer->get_shipping_country();
```

so maybe that needs fixing too?
```

Comment (Konamiman) [reply includes/class-wc-checkout.php:836]: After a second look I see that `WC()->customer->get_shipping_country()` is effectively getting the country from the request... not sure if that's intentional (it's confusing at least).

File: includes/class-wc-countries.php (hunk 4 above)
Comment (Konamiman) [reply includes/class-wc-countries.php:68]: Thanks for the suggestion but the actual syntax is slightly different: `isset( $this->get_countries()[ $country_code ] );` - I'll apply it and push by myself.

File: includes/class-wc-checkout.php [hunk 5]
```diff
@@ -825,23 +834,27 @@ protected function validate_posted_data( &$data, &$errors ) {
 	 * @since  3.0.0
 	 * @param  array    $data   An array of posted data.
 	 * @param  WP_Error $errors Validation errors.
+	 * @throws Exception Invalid country code in billing or shipping address.
```
Comment (vedanshujain) [inline includes/class-wc-checkout.php:837]: is this comment still correct?

File: includes/class-wc-checkout.php [hunk 6]
```diff
@@ -825,23 +834,27 @@ protected function validate_posted_data( &$data, &$errors ) {
...
-			$shipping_country = WC()->customer->get_shipping_country();
+			$shipping_country = isset( $data['shipping_country'] ) ? $data['shipping_country'] : WC()->customer->get_shipping_country();
 
 			if ( empty( $shipping_country ) ) {
 				$errors->add( 'shipping', __( 'Please enter an address to continue.', 'woocommerce' ) );
-			} elseif ( ! in_array( WC()->customer->get_shipping_country(), array_keys( WC()->countries->get_shipping_countries() ), true ) ) {
-				/* translators: %s: shipping location */
-				$errors->add( 'shipping', sprintf( __( 'Unfortunately <strong>we do not ship %s</strong>. Please enter an alternative shipping address.', 'woocommerce' ), WC()->countries->shipping_to_prefix() . ' ' . WC()->customer->get_shipping_country() ) );
+			} elseif ( ! in_array( $shipping_country, array_keys( WC()->countries->get_shipping_countries() ), true ) ) {
+				if ( WC()->countries->country_exists( $shipping_country ) ) {
```
Comment (vedanshujain) [inline includes/class-wc-checkout.php:854]: do we need this check here? Looks like we are already checking this in `validate_posted_data`

File: includes/class-wc-checkout.php [hunk 7]
```diff
@@ -744,6 +746,13 @@ protected function validate_posted_data( &$data, &$errors ) {
 				$format      = array_filter( isset( $field['validate'] ) ? (array) $field['validate'] : array() );
 				$field_label = isset( $field['label'] ) ? $field['label'] : '';
 
+				if ( 'country' === $field['type'] &&
+					! ( 'shipping' === $fieldset_key && ! $data ['ship_to_different_address'] ) &&
```
Comment (vedanshujain) [inline includes/class-wc-checkout.php:750]: should we add a clause for `$required` and `isset( $data[ $key ] )` incase country is not a required field at all. based on the code in callee functions, seems like if this field is not present, we can use `WC()->customer->get_shipping_country()` as a backup.

File: includes/class-wc-checkout.php [hunk 8]
```diff
@@ -825,23 +834,27 @@ protected function validate_posted_data( &$data, &$errors ) {
...
 
-		if ( empty( $data['woocommerce_checkout_update_totals'] ) && empty( $data['terms'] ) && ! empty( $_POST['terms-field'] ) ) { // WPCS: input var ok, CSRF ok.
+		// phpcs:ignore WordPress.Security.NonceVerification.Missing
+		if ( empty( $data['woocommerce_checkout_update_totals'] ) && empty( $data['terms'] ) && ! empty( $_POST['terms-field'] ) ) {
 			$errors->add( 'terms', __( 'Please read and accept the terms and conditions to proceed with your order.', 'woocommerce' ) );
 		}
 
 		if ( WC()->cart->needs_shipping() ) {
-			$shipping_country = WC()->customer->get_shipping_country();
+			$shipping_country = isset( $data['shipping_country'] ) ? $data['shipping_country'] : WC()->customer->get_shipping_country();
```
Comment (vedanshujain) [inline includes/class-wc-checkout.php:849]: nice work to make this explicit 👍

**Review by vedanshujain — COMMENTED** [review]
Overall looks good. I have left some minor comments, which are mostly questions for myself.

Also test suite looks pretty neat 💯, thanks for adding it!

File: includes/class-wc-checkout.php (hunk 6 above)
Comment (Konamiman) [reply includes/class-wc-checkout.php:854]: I added this to prevent an "Unfortunately do not ship to (invalid country code)" notice, which would be pretty much useless once we have shown the "Invalid country code" one.

File: includes/class-wc-checkout.php (hunk 5 above)
Comment (Konamiman) [reply includes/class-wc-checkout.php:837]: It's not! I'll remove it.

File: includes/class-wc-checkout.php (hunk 7 above)
Comment (Konamiman) [reply includes/class-wc-checkout.php:750]: But this code is part of the loop that iterates over the posted data, so it will validate the posted country only if there is any. Also there's a `if ( ! isset( $data[ $key ] ) ) continue;` at the beginning of the loop. Or you mean something else?

The `! ( 'shipping' === $fieldset_key && ! $data ['ship_to_different_address'] )` is there to prevent a duplicate "Invalid country code" error, since when "ship to different address" is unchecked then shipping and billing countries will be the same ones.

Comment (vedanshujain) [reply includes/class-wc-checkout.php:750]: > But this code is part of the loop that iterates over the posted data

Ah sorry, I meant `empty` not `isset`.  Basically, if a field is not required then it can be empty as well right? Or not? We should probably bail from checking if the country is valid, if its not a required field and is empty. 

> The ! ( 'shipping' === $fieldset_key && ! $data ['ship_to_different_address'] ) is there to prevent a duplicate "Invalid country code" error, since when "ship to different address" is unchecked then shipping and billing countries will be the same ones.

Makes sense :+1:

Comment (Konamiman) [reply includes/class-wc-checkout.php]: Ok, a couple of things:

1. Theres's a `$validate_fieldset` variable already for that, generated by calling `maybe_skip_fieldset`; so we can just use that.
2. `maybe_skip_fieldset` is already doing the `'shipping' === $fieldset_key && ! $data ['ship_to_different_address'] ` part so there's no need to repeat it.

So I've pushed a commit with these changes.

**Review by vedanshujain — APPROVED** [review]
LGTM!
