### PR TITLE
Remove check for logged in user on the order received page for displaying billing/shipping addresses

### LINKED ISSUE #31990: Guest order: Billing and shipping address not visible on order received page
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When placing an order as a guest (thus, not logged in) the billing and shipping address are not visible on the order confirmation page. 

### Expected behavior

I expect the billing and shipping address to be visible on the order confirmation page, even when a guest places an order.

### Actual behavior

See bug description.

### Steps to reproduce

1. Go to a product page and add a product to the cart.
2. Go to the checkout page.
3. Provide both a billing and a shipping address.
4. Place the order.
5. See that no billing and shipping address are visible when placing the order as a guest.

### Screenshot

Screen Shot 2022-02-25 at 16 02 42

<details>
<summary>WordPress Environment</summary>

```
### WordPress Environment

WordPress address (URL): http://localhost:8889
Site address (URL): http://localhost:8889
WC Version: 6.2.1
REST API Version: ✔ 6.2.1
WC Blocks Version: ✔ 7.1.0-dev
Action Scheduler Version: ✔ 3.4.0
WC Admin Version: ✔ 3.1.0
Log Directory Writable: ✔
WP Version: 5.9.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.52 (Debian)
PHP Version: 7.4.28
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.74.0
OpenSSL/1.1.1k

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.6.5-MariaDB-1:10.6.5+maria~focal
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 6.2.1
WC Database Prefix: wp_
Total Database Size: 4.81MB
Database Data Size: 3.41MB
Database Index Size: 1.40MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 2.52MB + Index: 0.03MB + Engine InnoDB
wp_postmeta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_posts: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 5
page: 7
post: 2
shop_order: 1
wp_global_styles: 1

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (3) ###

JSON Basic Authentication: by WordPress API Team – 0.1
WooCommerce Blocks: by Automattic – 7.1.0-dev
WooCommerce: by Automattic – 6.2.1

### Inactive Plugins (2) ###

Akismet Anti-Spam: by Automattic – 4.2.2
Hello Dolly: by Matt Mullenweg – 1.7.2

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #5 - /shop/
Cart: #6 - /cart/
Checkout: #7 - /checkout/
My account: #8 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 3.9.1
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Pending: 7
Oldest: 2022-02-25 14:52:01 +0000
Newest: 2022-02-25 14:55:20 +0000


### Status report information ###

Generated at: 2022-02-25 15:13:40 +00:00
```

</details>

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### LINKED ISSUE #43987: Order Success page lacks critical shipping and billing information
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

I understand that core recently plugged a security hole by requiring shoppers to be authenticated in order to access order details. That impacted guest checkout by requiring a guest shopper without an account to sign-in to view the order success page. 

My understanding was that a workaround was implemented so that a one time, short lived 10 minutes access token was provided to guest checkout shoppers, so they could confirm their order details and see the order success page.

Over the last few weeks I've seen the billing address disappear, and now the shipping address in gone too. While shoppers should get an email confirmation of the order, it cannot be solely relied upon as a receipt. [Per Baymard:](https://baymard.com/premium/guideline-collections/echwd2/596)

> The order confirmation page serves as a vital signal to users that their order has been successfully completed. While many participants in testing admitted that they only looked to the confirmation page to confirm their purchase had been submitted, relying instead on the order confirmation email as the full accounting of their order (see [#597](https://baymard.com/premium/guideline-collections/jg0yod/597)), we observed two smaller subgroups for whom this step and its information became highly important: those who are were especially meticulous (e.g., users who’ve just placed a very expensive order, and who typically will be more concerned about double-checking the order details at the confirmation step), and those who never received the order confirmation email, or receive it only after a long delay. For these users — as well as for those who are naturally more detail-oriented — confirmation pages that lack sufficient detail fail to provide key reference information on their order, increasing their anxiety and the need to contact the site’s customer service to recall key details.

### Expected behavior

Guest checkout shoppers, when the payment has been completed and the shoppers is redirected to the order success page, that page must contain the billing and shipping (when applicable) information. 

### Actual behavior

Guest checkout shoppers, when the payment has been completed and the shoppers is redirected to the order success page, that page does not contain the billing and shipping information. It is an incomplete receipt record.

### Steps to reproduce

1. Launch a test store with a short code theme, running WooPayments
2. Make a purchase as a guest checkout user
3. Successfully place an order
4. Observe that the order success page lack critical billing and shipping info, thus does not serve as a receipt record

### WordPress Environment

N/A

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by wavvves**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

This PR enables guest users to visualize shipping/billing addresses on the Order Received page. For a details on why this is needed, see #43987

Closes #31990 
Closes #43987

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Install and activate a non-blocks theme (eg Storefront)
2. **Without being logged in**, go to a product page and add a product to the cart.
3. Go to the checkout page.
4. Provide both a billing and a shipping address.
5. Place the order.
6. See that **billing and shipping address are visible on the order received page** as a guest.
7. Copy the Order Recived page link.
8. Log in as an user, and navigate to the link saved in the previous step.
9. Verify that billing and shipping addresses is not visible on the page

image

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [x] Enhancement - Improvement to existing functionality

#### Message 
Enable guest users to visualize shipping/billing information on the order received page.

#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce/templates/order/order-details.php [hunk 1]
```diff
@@ -27,9 +27,11 @@
 
 $order_items           = $order->get_items( apply_filters( 'woocommerce_purchase_order_item_types', 'line_item' ) );
 $show_purchase_note    = $order->has_status( apply_filters( 'woocommerce_purchase_note_order_statuses', array( 'completed', 'processing' ) ) );
-$show_customer_details = is_user_logged_in() && $order->get_user_id() === get_current_user_id();
 $downloads             = $order->get_downloadable_items();
 
+// We make sure the order belongs to the user. This will also be true if the user is a guest, and the order belongs to a guest (userID === 0).
+$show_customer_details = $order->get_user_id() === get_current_user_id();
+
```
Comment (senadir) [inline plugins/woocommerce/templates/order/order-details.php]: If this is important and needs to be here? can it be done via a hook? otherwise a version bump is needed.

**Review by senadir — APPROVED** [review]
Checks out!

File: plugins/woocommerce/templates/order/order-details.php (hunk 1 above)
Comment (wavvves) [reply plugins/woocommerce/templates/order/order-details.php]: Nice catch 👍 , bumped template version in https://github.com/woocommerce/woocommerce/pull/47477/commits/7f95e1ebeee12d68ef22b01ad2b23f786ea7ef29
