### PR TITLE
Ensure local state is not overwritten by server when using `extensionCartUpdate`

### LINKED ISSUE #49203: Block Checkout resets in Woo 9.0.0 and above when `woocommerce_store_api_register_update_callback()` is called
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When adding a custom input field to the Checkout block, if you register an update callback using `woocommerce_store_api_register_update_callback`, the other Checkout fields are reset when you update the custom input field.

This only happens on Woo 9.0.0 and above.

### Expected behavior

I should be able to update the custom input field without resetting core Checkout fields.

### Actual behavior

If I update, let say the billing country and then update the custom input field, the billing country field is reset.

### Screencast

https://github.com/woocommerce/woocommerce/assets/17757960/819e7705-284b-495d-baf2-f9eb10944b4d

### Steps to reproduce

1. Download this plugin that implements an additional field to the block Checkout page. [custom-checkout-field.zip](https://github.com/user-attachments/files/16111767/custom-checkout-field.zip).
2. Go to the `custom-checkout-field` plugin directory and run `nvm install` and `npm run build`.
3. Open incognito and add a product to cart and visit block Checkout.
4. Change the country to anything else.
5. Update the custom field.
6. Observe that the country is reset to its original value.

### WordPress Environment

<details><summary>System Status Report</summary>

```
### WordPress Environment ###

WordPress address (URL): [Redacted]
Site address (URL): [Redacted]
WC Version: 9.0.2
Legacy REST API Package Version: The Legacy REST API plugin is not installed on this site.
Action Scheduler Version: ✔ 3.7.4
Log Directory Writable: ✔
WP Version: 6.5.5
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.16.0
PHP Version: 8.0.30
PHP Post Max Size: 1,000 MB
PHP Time Limit: 1200
PHP Max Input Vars: 4000
cURL Version: 8.4.0
(SecureTransport) LibreSSL/3.3.6

SUHOSIN Installed: –
MySQL Version: 8.0.16
Max Upload Size: 300 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

[REDACTED]

### Post Type Counts ###

attachment: 1
page: 14
post: 2
product: 2
revision: 11
shop_order_placehold: 33
wp_navigation: 1
wp_template: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (2) ###

Custom Checkout Field: by The WordPress Contributors – 0.1.0
WooCommerce: by Automattic – 9.0.2

### Inactive Plugins (25) ###

Braintree for WooCommerce Payment Gateway: by WooCommerce – 3.1.6
My Extension Name: by The WordPress Contributors – 0.1.0
Query Monitor: by John Blackbourn – 3.16.3
WooCommerce Accommodation Bookings: by WooCommerce – 1.2.6
WooCommerce Bookings: by WooCommerce – 2.1.2 (update to version 2.1.3 is available)
WooCommerce Bookings Availability: by WooCommerce – 1.2.6
WooCommerce Box Office: by WooCommerce – 1.2.5
WooCommerce Deposits: by WooCommerce – 2.2.8 (update to version 2.2.9 is available)
WooCommerce Elavon Converge EU Gateway: by Elavon – 1.16.0
WooCommerce EU VAT Number: by WooCommerce – 2.9.5
WooCommerce GoCardless Gateway: by WooCommerce – 2.6.0 (update to version 2.7.1 is available)
WooCommerce Order Barcodes: by WooCommerce – 1.7.3 (update to version 1.7.5 is available)
WooCommerce Payfast Gateway: by WooCommerce – 1.6.5
WooCommerce Pre-Orders: by WooCommerce – 2.1.0 (update to version 2.1.1 is available)
WooCommerce Product CSV Import Suite: by WooCommerce – 1.10.70 (update to version 1.10.71 is available)
WooCommerce Product Vendors: by WooCommerce – 2.2.9
WooCommerce Purchase Order Payment Gateway: by WooCommerce – 1.4.7
WooCommerce Stripe Gateway: by WooCommerce – 8.4.0
WooCommerce Subscriptions: by WooCommerce – 6.4.0 (update to version 6.4.1 is available)
WooCommerce Xero Integration: by WooCommerce – 1.8.6 (update to version 1.8.7 is available)
WooPayments: by Automattic – 7.2.0 (update to version 7.8.1 is available)
Woo Select Product Field: by The WordPress Contributors – 0.1.0
WP Crontrol: by John Blackbourn & crontributors – 1.16.1
WP Debugging: by Andy Fragen – 2.11.22
WPvivid Database Snapshots: by wpvivid.com – 0.9.4

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 526 KB

### WC Pages ###

Shop base: #7 - /shop/
Cart: #8 - /cart/
Checkout: #9 - /checkout/
My account: #10 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 4.5.4 (update to version 4.6.0 is available)
Author URL: https://woo.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
pattern-toolkit-full-composability
product-pre-publish-modal
settings
async-product-editor-category-field
launch-your-store
product-editor-template-system

Daily Cron: ✔ Next scheduled: 2024-07-06 13:11:49 +00:00
Options: ✔
Notes: 74
Onboarding: skipped

### Action Scheduler ###

Complete: 365
Oldest: 2024-07-02 15:11:13 +0000
Newest: 2024-07-05 14:17:35 +0000

Pending: 1
Oldest: 2024-07-06 14:00:46 +0000
Newest: 2024-07-06 14:00:46 +0000


### Status report information ###

Generated at: 2024-07-05 16:03:39 +00:00
```
</details>

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by opr**
### Changes proposed in this Pull Request:

~~Add new property to the `wc/store/cart` data store. The new property is in the `metaData` object and is called `isCustomerDataDirty`. This will track whether an address change is pending (i.e. not pushed to the server yet). When a request to update customer data completes, `isCustomerDataDirty` is set to false.~~

- When the shipping or billing addresses are updated, add a flag to `localStorage` to mark whether the addresses are dirty (i.e. not synced with server yet).
- When the address is pushed, set this flag to false.
- **Push entire address object when updating customer, not just dirty keys.** - This is required because if you change the address in tab A, then only new changes in tab B are synced, problematic when country is changed and things like State and Postcode are synced and "invalid".
- Add some e2e tests for `extensionCartUpdate` - may not completely cover its functionality but covers this use-case.
- Add new arg to `extensionCartUpdate` called `overwriteDirtyCustomerData` - this can be used by extensions if they don't care about overwriting pending data. This defaults to `false`.
- Update documentation to reflect new args

Closes #49203

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

#### Developer only testing

1. Install the [Code Snippets](https://wordpress.org/plugins/code-snippets/) plugin. Add a new snippet containing the following:

```php
use Automattic\WooCommerce\StoreApi\Schemas\ExtendSchema;
use Automattic\WooCommerce\StoreApi\StoreApi;

add_action(
	'woocommerce_init',
	function () {
		$extend = StoreApi::container()->get( ExtendSchema::class );
		if (
			is_callable(
				array(
					$extend,
					'register_update_callback',
				)
			)
		) {
			$extend->register_update_callback(
				array(
					'namespace' => 'woocommerce-blocks-test-extension-cart-update',
					'callback'  => function ( $data ) {
						if ( ! empty( $data['test-name-change'] ) ) {
							WC()->cart->get_customer()->set_shipping_first_name( 'Mr. Test' );
							WC()->cart->get_customer()->save();
						}
					},
				)
			);
		}
	}
);
```
2. In an incognito session, add an item to your cart and go to the Checkout block. **Be sure not to fill in any data unless the test instructions say so**.
3. Enter the following into your JS console: `wc.blocksCheckout.extensionCartUpdate( { namespace: 'woocommerce-blocks-test-extension-cart-update', data: { 'test-name-change': true } } )`
4. Check the name on your Shipping Address, it should be `Mr. Test`.
5. Change the name to something else. Repeat step 3 and 4.
6. Change the country and repeat step 3.
7. Ensure the country has not reset or changed.
8. Change the name again, fill the rest of your details and check out. 
9. Re-add an item to your cart and go to the Checkout block. Change country again.
10. Repeat step 3. Ensure the name changes to `Mr. Test`.

##### In multiple tabs

Open two tabs, follow the instructions in order from top to bottom.

| Tab A | Tab B |
| ------ | ----- |
| Add an item to your cart and go to the Checkout page  |  |
| Set the country to UK, fill in a full address (example address: 566 Chiswick High Road, London, United Kingdom, W4 5YE) | |
| | Go to the Checkout page |
| | Change the country from UK to US, do not fill anything else in. |
| | Enter the following into your JS console: `wc.blocksCheckout.extensionCartUpdate( { namespace: 'woocommerce-blocks-test-extension-cart-update', data: { 'test-name-change': true } } )`. Ensure the country is still US and has not reverted to UK. The name you entered should not change at this point. |
| | Fill a full US address (example address: 2401 Utah Avenue, South Seattle, Washington, 98134). Set the name to `Should change`. |
| | Enter the following into your JS console: `wc.blocksCheckout.extensionCartUpdate( { namespace: 'woocommerce-blocks-test-extension-cart-update', data: { 'test-name-change': true } } )`. The name should update to 'Mr. Test' |
| Reload the page, ensure the address entered in Tab B shows here. | |

#### Regression testing

1. Add an item to your cart and ensure you can check out successfully.
2. Test with WC EU VAT Number and/or WC Points and Rewards. Ensure these plugins work correctly in the Checkout block.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce-blocks/assets/js/data/cart/reducers.ts [hunk 1]
```diff
@@ -80,8 +80,20 @@ const reducer: Reducer< CartState > = (
...
+				return (
+					action.billingAddress[ key ] !==
+					state.cartData.billingAddress?.[ key ]
+				);
+			} );
 			state = {
 				...state,
+				metaData: {
+					...state.metaData,
+					isCustomerDataDirty: billingAddressChanged,
```
Comment (mikejolley) [inline plugins/woocommerce-blocks/assets/js/data/cart/reducers.ts]: Potential logic bug; if this is true, but this particular dispatch did not result in a change, a `true` value will switch to `false`.

File: plugins/woocommerce-blocks/docs/third-party-developers/extensibility/rest-api/extend-rest-api-update-cart.md [hunk 2]
```diff
@@ -1,3 +1,4 @@
+<!-- markdownlint-disable MD024 -->
```
Comment (mikejolley) [inline plugins/woocommerce-blocks/docs/third-party-developers/extensibility/rest-api/extend-rest-api-update-cart.md]: What does this do?

**Review by mikejolley — CHANGES_REQUESTED** [review]
I think there is a logic bug in the reducer—can you check?

I think this will solve the immediate problem. Medium term we could look into updating based on last date modified, or look at other systems which deal with syncs between server state and local state.

File: plugins/woocommerce-blocks/assets/js/data/cart/actions.ts [hunk 3]
```diff
@@ -188,16 +188,36 @@ export const shippingRatesBeingSelected = ( isResolving: boolean ) =>
...
 		try {
 			const { response } = await apiFetchWithHeaders( {
 				path: '/wc/store/v1/cart/extensions',
 				method: 'POST',
 				data: { namespace: args.namespace, data: args.data },
 				cache: 'no-store',
 			} );
-			dispatch.receiveCart( response );
-			return response;
+			if ( args.overwriteDirtyCustomerData === true ) {
```
Comment (mikejolley) [inline plugins/woocommerce-blocks/assets/js/data/cart/actions.ts]: If you overwrite data here, what happens if there was a dirty state before? Will it push those dirty updates *next* update, or use these new values?

File: plugins/woocommerce-blocks/docs/third-party-developers/extensibility/rest-api/extend-rest-api-update-cart.md (hunk 2 above)
Comment (opr) [reply plugins/woocommerce-blocks/docs/third-party-developers/extensibility/rest-api/extend-rest-api-update-cart.md]: Hm, this rule is for duplicate headings, not sure why it has been added to this file, there are no duplicate headings here. The other file (`plugins/woocommerce-blocks/docs/third-party-developers/extensibility/data-store/cart.md`) is valid.

File: plugins/woocommerce-blocks/assets/js/data/cart/reducers.ts (hunk 1 above)
Comment (opr) [reply plugins/woocommerce-blocks/assets/js/data/cart/reducers.ts]: Hm, yes you're right. Probably should be
```suggestion
					isCustomerDataDirty: state.metaData.isCustomerDataDirty || billingAddressChanged,
```

suppose this also adds to the case for timestamp-based tracking, though.

File: plugins/woocommerce-blocks/assets/js/data/cart/actions.ts (hunk 3 above)
Comment (opr) [reply plugins/woocommerce-blocks/assets/js/data/cart/actions.ts]: The old "dirty" values will be discarded and the new values will be used. I don't think anything will be pushed until the addresses change again.

**Comment by opr** [comment]
Setting back to draft while AFK, and I want to improve the testing and instructions around this.

**Comment by mikejolley** [comment]
I think we should add tests for edge cases just to be sure the stale approach works. e.g. Say you have 2 tabs open and change country in one. Do pushes fail? 

If the stale approach works we're good, but if we need to know which is more current thats where we'd need the timestamps.

**Comment by opr** [comment]
@mikejolley OK I see there is an issue with stale data now, you get bugs where it claims the postcode is invalid because country updated in another tab, so it seems strange to see this type of thing with a valid postcode.

image

I think timestamp based approach is better for now.

**Comment by jeffpaul** [comment]
@opr @mikejolley checking in to see if this is likely to move forward here in Q4 (as we're blocked downstream in EU VAT by functionality here)?

**Comment by opr** [comment]
@jeffpaul - I tried again today. I will ask Mike to review this approach.

I don't think timestamps can solve this.

## Problem

1. Any actions that return the cart from the server will replace the client-side cart.
2. If the client-side cart contains unsynced data (due to partial address completion, or it didn't have time to push yet, e.g. due to debounce) then the data from the server will replace it without question. This is bad.

### Problem with boolean "stale" flag

1. If shoppers only used a single tab, this would be OK, but they don't and we need to cater for this. For instance, shoppers may open multiple tabs to look at different items, then get halfway through the checkout, get distracted and come back later and proceed in a different tab. If the checkout doesn't resume smoothly the chance that shopper converts is probably decreased.

### Problem with timestamp approach

1. Knowing when the cart was updated on the server does not solve for partially pushed addresses, and also falls down with the same problem as the boolean stale flag.

## Suggested solution

In the updated solution, I propose using local storage to track whether the address is dirty, this solves the problem of the boolean flag across tabs (but not across browsers, though I think we can get away with not supporting this).

@mikejolley any thoughts on this, do you feel using local storage is a good approach? If you could review the new changes that would be really appreciated, I appreciate you reviewed them a long time ago so you would probably have to start fresh.

File: plugins/woocommerce-blocks/assets/js/data/cart/actions.ts [hunk 4]
```diff
@@ -166,16 +167,30 @@ export const shippingRatesBeingSelected = ( isResolving: boolean ) =>
...
+				shipping_address: _,
+				billing_address: __,
+				...responseWithoutShippingOrBilling
+			} = response;
+			if ( getIsCustomerDataDirty() ) {
+				dispatch.receiveCart( responseWithoutShippingOrBilling );
+				return;
+			}
 			dispatch.receiveCart( response );
-			return response;
```
Comment (mikejolley) [inline plugins/woocommerce-blocks/assets/js/data/cart/actions.ts]: Should we still return the promise, and is there a chance someone was using it to add their own `.then()`?

File: plugins/woocommerce-blocks/assets/js/data/cart/actions.ts [hunk 5]
```diff
@@ -166,16 +167,30 @@ export const shippingRatesBeingSelected = ( isResolving: boolean ) =>
...
+				dispatch.receiveCart( response );
+				return response;
+			}
+			// If the customer data is dirty, we don't want to overwrite it with the response.
+			// Remove shipping and billing address from the response and then receive the cart.
+			const {
+				shipping_address: _,
+				billing_address: __,
+				...responseWithoutShippingOrBilling
+			} = response;
```
Comment (mikejolley) [inline plugins/woocommerce-blocks/assets/js/data/cart/actions.ts]: Should this be within the conditional to avoid setting the const unless required?

File: plugins/woocommerce-blocks/assets/js/data/cart/utils.ts [hunk 6]
```diff
@@ -116,3 +116,24 @@ export const validateDirtyProps = ( dirtyProps: {
...
 	return invalidProps.length === 0;
 };
+
+/**
+ * Gets the localStorage flag to indicate whether the customer data is dirty.
+ */
+export const getIsCustomerDataDirty = () => {
+	return (
+		window.localStorage.getItem(
+			'woocommerce_checkout_is_customer_data_dirty'
```
Comment (mikejolley) [inline plugins/woocommerce-blocks/assets/js/data/cart/utils.ts]: Should we agree on naming for local storage items going forward? Gutenberg mostly seems to use all caps, underscores, WP prefix:

https://github.com/search?q=repo%3AWordPress%2Fgutenberg%20localStorage&type=code

So I guess if we follow the same pattern this would be called WC_CHECKOUT_SOMETHING. Just thinking out loud but I guess some utilities around this could help enforce certain naming. I intend to use local storage for https://github.com/woocommerce/woocommerce/pull/51981 too.

**Review by mikejolley — COMMENTED** [review]
Thanks @opr I left a few questions. I would recommend someone else (Nadir?) reviewing just the dirty prop/partial update part in case I'm missing something important.

Regarding multiple tab testing I'm not sure if it worked as intended. The update in the second tab did nothing (no data changed). The form in the second tab was blank.

Could you clarify what actions to perform in each tab more clearly (numbered) and what the default state of each should be?

File: plugins/woocommerce-blocks/assets/js/data/cart/utils.ts (hunk 6 above)
Comment (opr) [reply plugins/woocommerce-blocks/assets/js/data/cart/utils.ts]: Yes, aligning with Gutenberg is a good idea, thanks for the suggestion

**Comment by opr** [comment]
@mikejolley I updated the testing instructions for tabs I did it in a table that you can follow top to bottom, hopefully that's a little more clear?

@senadir please can you review this too, specifically the part about sending the full address to the server on update, rather than only dirty props?

**Review by mikejolley — APPROVED** [review]
Testing as intended now so from my side I am approving. Thanks for the updated instructions.

File: plugins/woocommerce-blocks/assets/js/data/cart/utils.ts [hunk 7]
```diff
@@ -116,3 +116,24 @@ export const validateDirtyProps = ( dirtyProps: {
...
+
+/**
+ * Sets a flag in localStorage to indicate whether the customer data has been modified.
+ */
+export const setIsCustomerDataDirty = ( isCustomerDataDirty: boolean ) => {
+	window.localStorage.setItem(
+		'WOOCOMMERCE_CHECKOUT_IS_CUSTOMER_DATA_DIRTY',
+		isCustomerDataDirty ? 'true' : 'false'
+	);
+};
```
Comment (senadir) [inline plugins/woocommerce-blocks/assets/js/data/cart/utils.ts]: I'm still reviewing but I'm not sure how to best handle this? Different tabs can't know if local storage got updated unless you're calling localStorage each time which isn't that good, though we're reading booleans so it should be fine.

Do we need to clear this after an order is placed? is it okay for address to be marked dirty on future orders?

Comment (opr) [reply plugins/woocommerce-blocks/assets/js/data/cart/utils.ts]: > unless you're calling localStorage each time which isn't that good, though we're reading booleans so it should be fine.

The read only really matters in `applyExtensionCartUpdate`, and it is done each time then (this is following an API call, so not super regular).

I also just pushed a change so that writing to local storage is debounced (300ms) and is no longer read each time the `SET_BILLING_ADDRESS` and `SET_SHIPPING_ADDRESS` is dispatched.

> Do we need to clear this after an order is placed? is it okay for address to be marked dirty on future orders?

Hmm, we should remove it from localStorage when the order is placed I guess, no need to keep it around any more. Added in 754a60bffbcc0d4b41a615dcb0b73ae4ec82ade9
