### PR TITLE
Duplicate products; fix variation creation and add actions

### LINKED ISSUE #13180: Product Duplication: no more filter to exclude post meta
There used to be a `woocommerce_duplicate_product_exclude_meta` filter in WooCommerce that would allow to exclude specific post meta when duplicating a product, but it looks like that filter was removed in 10d3e2d580cc7ad815eddf32ca486f5c5fb2d26c. 

That filter was useful with other plugins like Jetpack, where it allowed site owners to exclude specific post meta (e.g. post meta controlling whether a product should be publicized or not) from being duplicated alongside a product.

Is there a better way to control what's duplicated by WooCommerce now?

P.S.: it looks like `woocommerce_duplicate_product_exclude_taxonomies` was also removed.

### LINKED ISSUE #13199: [2.7] Attributes and Variations are lost in the duplicated variable product.
WordPress : 4.7.2
Plugins activated : Only WooCommerce 2.7 beta2 (master)
Theme : StoreFront 2.1.7

To reproduce, duplicate a variable product. Then edit the duplicated product : Attributes and Variations tab are empty.

### PR DESCRIPTION
**Pull request by mikejolley**
Force allows create to make sure data is set regardless of whether it
was changed. This fixes product duplication.

Fixes #13199

Adds actions when duplicating things so objects can be changed, and
reinstates woocommerce_duplicate_product_exclude_meta which can unset
meta keys before save.

Closes #13180

### CODE REVIEW

File: includes/data-stores/class-wc-product-variation-data-store-cpt.php [hunk 1]
```diff
@@ -138,23 +136,24 @@ public function create( &$product ) {
...
-			'menu_order'     => $product->get_menu_order(),
-		);
+		$changes = $product->get_changes();
 
-		wp_update_post( $post_data );
+		// Only update the post when the post data changes.
+		if ( array_intersect( array( 'description', 'short_description', 'name', 'parent_id', 'reviews_allowed', 'status', 'menu_order' ), array_keys( $changes ) ) ) {
+			wp_update_post( array(
+				'ID'             => $product->get_id(),
+				'post_title'     => $this->generate_product_title( $product ), // !
```
Comment (claudiulodro) [inline includes/data-stores/class-wc-product-variation-data-store-cpt.php]: ```// !``` Does this mean anything?

Comment (mikejolley) [inline includes/data-stores/class-wc-product-variation-data-store-cpt.php]: My bad, patching the issue I missed.
