### PR TITLE
[Accessibility] Hide zoomed product images for screen readers.

### LINKED ISSUE #44478: Accessibility issue when a product have more than 1 image.
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When there is more than one image, product page have accessibility issue.
Values assigned to role="" are not valid ARIA roles.
img.zoomImg css class probably

### Expected behavior

There should be no error

### Actual behavior

https://pagespeed.web.dev/analysis/https-themes-woo-com-storefront-product-build-your-dslr/3zcvlwuhd6?form_factor=mobile

Values assigned to role="" are not valid ARIA roles. on Accessibility section

### Steps to reproduce

1. Go to product page which has more than 1 image
2. Copy url and paste pagespeed tool or right click and use lighthouse tool
Here is an example

### WordPress Environment

All latest.
But even storefront theme have it on woo.com

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by Manussakis**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes #44478  .

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Create a new store and import the sample products.
2. Go to Media -> Library and add an alt text to all Hoodie images.
3. Go to the Hoodie product page on the frontend www.example.com/product/hoodie/.
4. Open the Develop Tools.
5. Open the Lighthouse tab and select:
    - Mode = Navigation.
    - Device = Mobile
    - Categories = Accessibility
      image
6. Click on the "Analyze page load" button.
7. Once the report completes, check the `Values assigned to role="" are not valid ARIA roles` error.
8. Open the error details and verify that the images of the Hoodie product are not part of the error.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce/client/legacy/js/frontend/single-product.js [hunk 1]
```diff
@@ -213,7 +213,16 @@ jQuery( function( $ ) {
 		// But only zoom if the img is larger than its container.
 		if ( zoomEnabled ) {
 			var zoom_options = $.extend( {
-				touch: false
+				touch: false,
+				callback: function() {
+					var zoomImg = this;
+					
+					setTimeout( function() {
```
Comment (Manussakis) [inline plugins/woocommerce/client/legacy/js/frontend/single-product.js:220]: `setTimeout` is required to wait for the `jquery.zoom.js` plugin to complete adding the attributes to the image element so we can manipulate them.

File: plugins/woocommerce/client/legacy/js/frontend/single-product.js [hunk 2]
```diff
@@ -213,7 +213,16 @@ jQuery( function( $ ) {
...
+						zoomImg.removeAttribute( 'role' );
+						zoomImg.setAttribute( 'alt', '' );
+						zoomImg.setAttribute( 'aria-hidden', 'true' );
```
Comment (Manussakis) [inline plugins/woocommerce/client/legacy/js/frontend/single-product.js:223]: `aria-hidden="true"` should hide the image for assistive technologies. However, since it's not widely supported, the removal of the `role="presentation"` attribute and the empty `alt` value ensures the zoomed-in image is interpreted as decorative.

In fact, the `role="presentation"` attribute and `alt` with a valid value should not coexist since they provide opposite information to assistive technologies.

**Reference**:
https://www.w3.org/WAI/tutorials/images/decorative/

**Comment by Manussakis** [comment]
@dkotter This PR is ready for code review.

**Review by dkotter — APPROVED** [review]
@ankitguptaindia @qasumitbagthariya This is ready for QA

**Comment by ankitguptaindia** [comment]
**QA/Test Report-** ✅ 
------------

**Testing Environment -** 

<Details>

* WordPress: 6.6.1
* Theme: Twenty Twenty-Four Version: 1.1
* WooCommerce - Dev version with this fix specific branch.  
* PHP: 8.3
* Web Server: Nginx
* Browser: Chrome - Version 126
* OS: macOS Sonoma 14.5
* Git Branch: fix/44478


</Details>


**Test Results -** 

Changes work as explained. Tested with Chrome Browser and Lighthouse Dev tool. 


| Before Fix | After Fix |
|--------|--------|
| Screenshot 2024-07-27 at 6 13 59 PM |  Screenshot 2024-07-27 at 6 14 20 PM |

**Comment by ankitguptaindia** [comment]
Hi @Manussakis This PR changes work as expected and ready for Woo review. Could you please remove WIP prefix and make PR un-draft? thank you!

**Comment by Manussakis** [comment]
@vikrampm1 This PR is ready for Woo review.

**Comment by vikrampm1** [comment]
@woocommerce/mothra this PR is ready for Woo review.

**Comment by jeffpaul** [comment]
@woocommerce/mothra @coreymckrill checking in to see if there's anything we can do to move this PR along for code review?

**Comment by coreymckrill** [comment]
@jeffpaul Mothra is no longer the correct team for this. Let me figure out where this should get directed...

**Review by gigitux — APPROVED** [review]
Nice work! LGTM! 🚀 

I'm going to merge this PR!
