### PR TITLE
Fix rendering issue with RTL currency symbols in product price block

### LINKED ISSUE #49102: Product Price: Issues like no space between normal price and sale price
I found a few minor issues in "Product Price" block while testing on WordPress 6.6. Here are the details:

**Issue 1:** There is no space between the normal price and the sale price. Here is how to reproduce it:

1. In WooCommerce > Settings > General, this is what I had set that resulted in the issue:
  - Currency: AFN - Afghan afghani
  - Currency position: Left with space
  - Thousand separator: .
  - Decimal separator: ,
  - Number of decimals: 2
2. Create a new post and add Product Collection block. In "Product Price" block, you will see that there is no space between normal price and sale price as shown in the screenshot below.
image

**Issue 2:** It's looking weird when I keep the same settings as above but change "Currency position" to "Right with space". Here is how to reproduce it:

1. In WooCommerce > Settings > General, change "Currency position" to "Right with space".
2. Create a new post and add Product Collection block. In "Product Price" block, you will notice that it's looking weird as shown in the screenshot below.
image

### PR DESCRIPTION
**Pull request by AhmarZaidi**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

This PR adds custom styles inluding the [`unicode-bidi`](https://developer.mozilla.org/en-US/docs/Web/CSS/unicode-bidi) along with [`direction`](https://developer.mozilla.org/en-US/docs/Web/CSS/direction) CSS properties to fix the RTL currency symbol issue. 

Additionally, it also adds a `renderTextWithRtlStyles` function to `FormattedMonetaryAmount` component. This `clones` the `renderText` element, if passed and applies the necessary `RTL` style classes to it. This is used for `SalePrice` of the  [`ProductPrice`](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/client/blocks/assets/js/base/components/product-price/index.tsx) component.

It also handles the additional cases mentioned here: https://github.com/woocommerce/woocommerce/issues/49102#issuecomment-2865305538

Closes #49102

### Screenshots or screen recordings:

https://github.com/user-attachments/assets/e5de2d19-493d-4de8-bdd4-96553ed5adc6

- Currency position: `Left with space`
  - Product collection block in Editor
    | Before | After |
    | ------ | ----- |
    | image | image |

  - Checkout page order summary
    | Before | After |
    | ------ | ----- |
    | image | image |

  - Cart page
    | Before | After |
    | ------ | ----- |
    | image | image |

  - Variable product frontend
    | Before | After |
    | ------ | ----- |
    | image | image |

- Currency position: `Right with space`
  - Product collection block in Editor
    | Before | After |
    | ------ | ----- |
    | image | image |

  - Product collection block in Frontend
    | Before | After |
    | ------ | ----- |
    | image | image |

### How to test the changes in this Pull Request:

**Fix 1**: Add space between the normal price and the sale price:

1. In WooCommerce > Settings > General, this is what I had set that resulted in the issue:
- Currency: AFN - Afghan afghani
- Currency position: Left with space
- Thousand separator: .
- Decimal separator: ,
- Number of decimals: 2
2. Create a new post and add Product Collection block. In "Product Price" block, you will see that space is correctly added between normal price and sale price as shown in the screenshot below.

    image
     
**Fix 2**: Keep the same settings as above but change "Currency position" to "Right with space":

1. In WooCommerce > Settings > General, change "Currency position" to "Right with space".
2. Create a new post and add Product Collection block. In "Product Price" block, notice that it's looking correct as shown in the screenshot below.

    image

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce/client/blocks/packages/components/formatted-monetary-amount/index.tsx [hunk 1]
```diff
@@ -86,6 +87,29 @@ const FormattedMonetaryAmount = ( {
...
+			? {
+					unicodeBidi: 'bidi-override' as const,
+					direction: 'ltr' as const,
+			  }
+			: {};
+
+	const renderTextWithRtlStyles = ( val: string ) => {
+		// Apply the rtlPrefixStyles to the element returned by renderText.
+		const element = props.renderText ? props.renderText( val ) : null;
+		if ( ! isValidElement( element ) ) return null;
```
Comment (tjcafferkey) [inline plugins/woocommerce/client/blocks/packages/components/formatted-monetary-amount/index.tsx]:
```suggestion
		if ( ! isValidElement( element ) ) {
			return null;
		}
```

File: plugins/woocommerce/client/blocks/packages/components/formatted-monetary-amount/index.tsx [hunk 2]
```diff
@@ -86,6 +87,29 @@ const FormattedMonetaryAmount = ( {
...
+
+		return cloneElement( element as ReactElement, {
+			style: {
+				...rtlPrefixStyles,
```
Comment (tjcafferkey) [inline plugins/woocommerce/client/blocks/packages/components/formatted-monetary-amount/index.tsx]: Lets spread `...rtlPrefixStyles,` after `...( element as ReactElement ).props.style,` to ensure these are not overwritten

**Review by tjcafferkey — COMMENTED** [review]
This works well, I've tested various currencies and positions and cant find any issues here. I've also tested classic themes for potential regressions and can't find any. It would be great to get this out of draft when you are able to so we can review it properly. Finally, I just left a few minor comments

File: plugins/woocommerce/client/blocks/packages/components/formatted-monetary-amount/index.tsx (hunk 1 above)
Comment (AhmarZaidi) [reply plugins/woocommerce/client/blocks/packages/components/formatted-monetary-amount/index.tsx]: Done

File: plugins/woocommerce/client/blocks/packages/components/formatted-monetary-amount/index.tsx (hunk 2 above)
Comment (AhmarZaidi) [reply plugins/woocommerce/client/blocks/packages/components/formatted-monetary-amount/index.tsx]: Makes sense.

**Comment by tjcafferkey** [comment]
@AhmarZaidi looks like there are some failing tests that need investigating. They might be because of the markup changes, if so they might need updating.

**Comment by AhmarZaidi** [comment]
@tjcafferkey Will check and update those.

**Comment by tjcafferkey** [comment]
@AhmarZaidi there appears to be some failing E2E tests, I have reran them and they fail consistently so they might be legit.

To run them locally you can run the following commands from the repo root (ensure Docker is installed):

1. Setup the env `pnpm --filter=@woocommerce/block-library env:start`
2. Run the test `pnpm --filter=@woocommerce/block-library test:e2e --ui woocommerce/plugins/woocommerce/<path to file>`

[You also might need `@wordpress/env`](https://www.npmjs.com/package/@wordpress/env)

**Comment by AhmarZaidi** [comment]
Hey @tjcafferkey,

I've fixed the PHP unit and JS test however I cannot get the CI/Playwright tests to properly run on my local setup.

I've tried the instructions as you mentioned [above](https://github.com/woocommerce/woocommerce/pull/58134#issuecomment-2918988855) and also [these docs for WooCommerce Playwright End-to-End Tests](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/tests/e2e-pw/README.md).

Quite likely I'm missing something simple, it would be a great help if you could guide me 😅

---

I was trying to only run the test that were failing [here](https://github.com/woocommerce/woocommerce/actions/runs/15321101394/job/43106562617?pr=58134) (not sure these are related to my code). The closest I was able to get was using this command:
```
pnpm test:e2e --ui woocommerce/plugins/woocommerce/tests/e2e-pw/tests/coupons/cart-block-coupons.spec.js
```

Here's the error I am getting when I run that test from the UI: 'No route was found matching the URL and request method.'

image

Note that I've omitted the `--filter=@woocommerce/block-library` since this test is present directly in `woocommerce/plugin`. I also tried using `pnpm --filter=@woocommerce/plugin-woocommerce test:e2e --ui woocommerce/plugins/woocommerce/tests/e2e-pw/tests/coupons/cart-block-coupons.spec.js` but I get the same error as before.

**Comment by straku** [comment]
@AhmarZaidi Hi! The tests that are failing are core tests, and you can find their readme [here](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/tests/e2e-pw/README.md). I followed these steps to get them running locally just now on your branch (I was able to confirm that failures are most likely related to your changes).
1. `cd` to the top-level directory of the repository
2. Install all dependencies with `pnpm install --frozen-lockfile`
3. `pnpm --filter=@woocommerce/plugin-woocommerce watch:build` (or `build` should work too)
4. Make sure that the docker is running in the background
5. `pnpm --filter=@woocommerce/plugin-woocommerce env:start`
6. `pnpm --filter=@woocommerce/plugin-woocommerce test:e2e tests/e2e-pw/tests/coupons/cart-block-coupons.spec.js` – first failure (running this should produce an HTML output of the test run with explanation of the failure)
7. `pnpm --filter=@woocommerce/plugin-woocommerce test:e2e tests/e2e-pw/tests/coupons/cart-block-coupons.spec.js` – second failure

I hope this helps 🤞

Can you also please fix the images in the PR description?

**Comment by AhmarZaidi** [comment]
Hey @straku 

I've updated the tests, they were failing due to the addition of `wc-block-number-format-container` span element. 
All the 3 test files now pass:
<details>
<summary>coupons/cart-block-coupons.spec.js</summary>

➜  woocommerce git:(fix/49102) ✗ pnpm --filter=@woocommerce/plugin-woocommerce test:e2e tests/e2e-pw/tests/coupons/cart-block-coupons.spec.js

...

Running 12 tests using 1 worker

  -  1 [install wc] › tests/e2e-pw/fixtures/install-wc.setup.js:21:6 › Install WC using WC Beta Tester
  ✓  2 [global authentication] › tests/e2e-pw/fixtures/auth.setup.js:35:6 › authenticate admin (1.3s)
  ✓  3 [global authentication] › tests/e2e-pw/fixtures/auth.setup.js:39:6 › authenticate customer (569ms)
  ✓  4 [site setup] › tests/e2e-pw/fixtures/site.setup.js:9:6 › configure HPOS (346ms)
DISABLE_HPOS: undefined
HPOS configuration (woocommerce_custom_orders_table_enabled): yes - High-performance order storage (recommended)
  ✓  5 [site setup] › tests/e2e-pw/fixtures/site.setup.js:64:6 › disable coming soon (344ms)
  ✓  6 [site setup] › tests/e2e-pw/fixtures/site.setup.js:68:6 › disable onboarding wizard (371ms)
  ✓  7 [site setup] › tests/e2e-pw/fixtures/site.setup.js:72:6 › determine if multisite (194ms)
  ✓  8 [site setup] › tests/e2e-pw/fixtures/site.setup.js:84:6 › general settings (191ms)
  ✓  9 …k Applying Coupons › allows cart block to apply coupon of any type @payments @services @could-be-lower-level-test (9.5s)
  ✓  10 …ck Applying Coupons › allows cart block to apply multiple coupons @payments @services @could-be-lower-level-test (8.4s)
  ✓  11 …Applying Coupons › prevents cart block applying same coupon twice @payments @services @could-be-lower-level-test (3.7s)
  ✓  12 …ng Coupons › prevents cart block applying coupon with usage limit @payments @services @could-be-lower-level-test (2.6s)

  1 skipped
  11 passed (42.7s)
::debug::Getting environment details

</details>

<details>
<summary>coupons/checkout-block-coupons.spec.js</summary>

➜  woocommerce git:(fix/49102) ✗ pnpm --filter=@woocommerce/plugin-woocommerce test:e2e tests/e2e-pw/tests/coupons/checkout-block-coupons.spec.js   

...

Running 12 tests using 1 worker

  -  1 [install wc] › tests/e2e-pw/fixtures/install-wc.setup.js:21:6 › Install WC using WC Beta Tester
  ✓  2 [global authentication] › tests/e2e-pw/fixtures/auth.setup.js:35:6 › authenticate admin (574ms)
  ✓  3 [global authentication] › tests/e2e-pw/fixtures/auth.setup.js:39:6 › authenticate customer (443ms)
  ✓  4 [site setup] › tests/e2e-pw/fixtures/site.setup.js:9:6 › configure HPOS (256ms)
DISABLE_HPOS: undefined
HPOS configuration (woocommerce_custom_orders_table_enabled): yes - High-performance order storage (recommended)
  ✓  5 [site setup] › tests/e2e-pw/fixtures/site.setup.js:64:6 › disable coming soon (251ms)
  ✓  6 [site setup] › tests/e2e-pw/fixtures/site.setup.js:68:6 › disable onboarding wizard (751ms)
  ✓  7 [site setup] › tests/e2e-pw/fixtures/site.setup.js:72:6 › determine if multisite (270ms)
  ✓  8 [site setup] › tests/e2e-pw/fixtures/site.setup.js:84:6 › general settings (189ms)
  ✓  9 …tests/coupons/checkout-block-coupons.spec.js:123:3 › Checkout Block Applying Coupons › allows checkout block to apply coupon of any type @payments @services @could-be-lower-level-test (9.8s)
  ✓  10 …/tests/coupons/checkout-block-coupons.spec.js:170:3 › Checkout Block Applying Coupons › allows checkout block to apply multiple coupons @payments @services @could-be-lower-level-test (8.9s)
  ✓  11 …sts/coupons/checkout-block-coupons.spec.js:223:3 › Checkout Block Applying Coupons › prevents checkout block applying same coupon twice @payments @services @could-be-lower-level-test (3.3s)
  ✓  12 …upons/checkout-block-coupons.spec.js:265:3 › Checkout Block Applying Coupons › prevents checkout block applying coupon with usage limit @payments @services @could-be-lower-level-test (3.2s)

  1 skipped
  11 passed (41.3s)
::debug::Getting environment details

</details>

<details>
<summary>coupons/create-restricted-coupons.spec.js</summary>

➜  woocommerce git:(fix/49102) ✗ pnpm --filter=@woocommerce/plugin-woocommerce test:e2e tests/e2e-pw/tests/coupons/create-restricted-coupons.spec.js                              

...

Running 20 tests using 1 worker

  -  1 [install wc] › tests/e2e-pw/fixtures/install-wc.setup.js:21:6 › Install WC using WC Beta Tester
  ✓  2 [global authentication] › tests/e2e-pw/fixtures/auth.setup.js:35:6 › authenticate admin (2.1s)
  ✓  3 [global authentication] › tests/e2e-pw/fixtures/auth.setup.js:39:6 › authenticate customer (625ms)
  ✓  4 [site setup] › tests/e2e-pw/fixtures/site.setup.js:9:6 › configure HPOS (634ms)
DISABLE_HPOS: undefined
HPOS configuration (woocommerce_custom_orders_table_enabled): yes - High-performance order storage (recommended)
  ✓  5 [site setup] › tests/e2e-pw/fixtures/site.setup.js:64:6 › disable coming soon (492ms)
  ✓  6 [site setup] › tests/e2e-pw/fixtures/site.setup.js:68:6 › disable onboarding wizard (336ms)
  ✓  7 [site setup] › tests/e2e-pw/fixtures/site.setup.js:72:6 › determine if multisite (7.1s)
  ✓  8 [site setup] › tests/e2e-pw/fixtures/site.setup.js:84:6 › general settings (441ms)
  ✓  9 [e2e] › tests/e2e-pw/tests/coupons/create-restricted-coupons.spec.js:139:3 › Restricted coupon management › can create new minimumSpend coupon @services (17.5s)
  ✓  10 [e2e] › tests/e2e-pw/tests/coupons/create-restricted-coupons.spec.js:139:3 › Restricted coupon management › can create new maximumSpend coupon @services (12.4s)
  ✓  11 [e2e] › tests/e2e-pw/tests/coupons/create-restricted-coupons.spec.js:139:3 › Restricted coupon management › can create new individualUse coupon @services (18.0s)
  ✓  12 [e2e] › tests/e2e-pw/tests/coupons/create-restricted-coupons.spec.js:139:3 › Restricted coupon management › can create new excludeSaleItems coupon @services (17.9s)
  ✓  13 [e2e] › tests/e2e-pw/tests/coupons/create-restricted-coupons.spec.js:139:3 › Restricted coupon management › can create new productCategories coupon @services (14.8s)
  ✓  14 [e2e] › tests/e2e-pw/tests/coupons/create-restricted-coupons.spec.js:139:3 › Restricted coupon management › can create new excludeProductCategories coupon @services (11.9s)
  ✓  15 [e2e] › tests/e2e-pw/tests/coupons/create-restricted-coupons.spec.js:139:3 › Restricted coupon management › can create new excludeProductBrands coupon @services (11.1s)
  ✓  16 [e2e] › tests/e2e-pw/tests/coupons/create-restricted-coupons.spec.js:139:3 › Restricted coupon management › can create new products coupon @services (17.8s)
  ✓  17 [e2e] › tests/e2e-pw/tests/coupons/create-restricted-coupons.spec.js:139:3 › Restricted coupon management › can create new excludeProducts coupon @services (12.6s)
  ✓  18 [e2e] › tests/e2e-pw/tests/coupons/create-restricted-coupons.spec.js:139:3 › Restricted coupon management › can create new allowedEmails coupon @services (9.5s)
  ✓  19 [e2e] › tests/e2e-pw/tests/coupons/create-restricted-coupons.spec.js:139:3 › Restricted coupon management › can create new usageLimitPerCoupon coupon @services (8.6s)
  ✓  20 [e2e] › tests/e2e-pw/tests/coupons/create-restricted-coupons.spec.js:139:3 › Restricted coupon management › can create new usageLimitPerUser coupon @services (10.5s)

  Slow test file: [e2e] › tests/e2e-pw/tests/coupons/create-restricted-coupons.spec.js (2.7m)
  Consider running tests from slow files in parallel, see https://playwright.dev/docs/test-parallel.
  1 skipped
  19 passed (3.0m)
::debug::Getting environment details

</details>

---

> Can you also please fix the images in the PR description?

Can you please clarify what needs to be fixed here? 

Thanks!

**Comment by straku** [comment]
@AhmarZaidi Thanks for fixing tests 👏  When it comes to the images, this is how they display to me:

Screenshot 2025-06-26 at 12 06 25

Trying to open them leads to a 404 page. It will be difficult to properly review without access to them.

**Comment by AhmarZaidi** [comment]
@straku

> Trying to open them leads to a 404 page. It will be difficult to properly review without access to them.

My bad, updated them, should be visible now 😅

---

Also, I checked and these tests pass on my local but were failing on the last commit:
<details>
<summary>
<a href="https://github.com/woocommerce/woocommerce/actions/runs/15878992504/job/44838217836?pr=58134">Core e2e tests - WP latest-1 [WP 6.7.2] 4/5 - @woocommerce/plugin-woocommerce [e2e]</a>
</summary>

➜  woocommerce git:(fix/49102) pnpm --filter=@woocommerce/plugin-woocommerce test:e2e tests/e2e-pw/tests/product/create-product-attributes.spec.js

Using config file: /Users/ahmar/Ahmar/CODING/rtCamp/woocommerce/plugins/woocommerce/tests/e2e-pw/envs/default/playwright.config.js
Arguments: --project=e2e tests/e2e-pw/tests/product/create-product-attributes.spec.js

BASE_URL is not set. Using default: http://localhost:8086

Running 9 tests using 1 worker

  -  1 [install wc] › tests/e2e-pw/fixtures/install-wc.setup.js:21:6 › Install WC using WC Beta Tester
  ✓  2 [global authentication] › tests/e2e-pw/fixtures/auth.setup.js:35:6 › authenticate admin (4.7s)
  ✓  3 [global authentication] › tests/e2e-pw/fixtures/auth.setup.js:39:6 › authenticate customer (417ms)
  ✓  4 [site setup] › tests/e2e-pw/fixtures/site.setup.js:9:6 › configure HPOS (326ms)
DISABLE_HPOS: undefined
HPOS configuration (woocommerce_custom_orders_table_enabled): yes - High-performance order storage (recommended)
  ✓  5 [site setup] › tests/e2e-pw/fixtures/site.setup.js:64:6 › disable coming soon (298ms)
  ✓  6 [site setup] › tests/e2e-pw/fixtures/site.setup.js:68:6 › disable onboarding wizard (305ms)
  ✓  7 [site setup] › tests/e2e-pw/fixtures/site.setup.js:72:6 › determine if multisite (2.4s)
  ✓  8 [site setup] › tests/e2e-pw/fixtures/site.setup.js:84:6 › general settings (293ms)
  ✓  9 [e2e] › tests/e2e-pw/tests/product/create-product-attributes.spec.js:143:1 › can add custom product attributes (14.7s)

  1 skipped
  8 passed (33.1s)

</details>

<details>
<summary>
<a href="https://github.com/woocommerce/woocommerce/actions/runs/15878992504/job/44838217760?pr=58134">[PHP: 8.4 WP: latest [WP latest] 2/2 - @woocommerce/plugin-woocommerce [unit:php]</a>
</summary>

➜  woocommerce git:(fix/49102) pnpm --filter=@woocommerce/plugin-woocommerce test:unit:env -- --filter=WC_Tests_CRUD_Orders                       

> @woocommerce/plugin-woocommerce@10.1.0 test:unit:env /Users/ahmar/Ahmar/CODING/rtCamp/woocommerce/plugins/woocommerce
> pnpm test:php:env "--" "--filter=WC_Tests_CRUD_Orders"


> @woocommerce/plugin-woocommerce@10.1.0 test:php:env /Users/ahmar/Ahmar/CODING/rtCamp/woocommerce/plugins/woocommerce
> sh ./client/blocks/bin/copy-blocks-json.sh && wp-env run --env-cwd='wp-content/plugins/woocommerce' tests-cli vendor/bin/phpunit -c phpunit.xml --verbose "--" "--filter=WC_Tests_CRUD_Orders"

ℹ Starting 'vendor/bin/phpunit -c phpunit.xml --verbose --filter=WC_Tests_CRUD_Orders' on the tests-cli container. 

Installing...
Running as single site... To run multisite, use -c tests/phpunit/multisite.xml
Installing WooCommerce...
Not running ajax tests. To execute these, use --group ajax.
Not running ms-files tests. To execute these, use --group ms-files.
Not running external-http tests. To execute these, use --group external-http.
PHPUnit 9.6.23 by Sebastian Bergmann and contributors.

Runtime:       PHP 8.1.32
Configuration: phpunit.xml

...............................................................  63 / 130 ( 48%)
............................................................... 126 / 130 ( 96%)
....                                                            130 / 130 (100%)

Time: 00:02.974, Memory: 153.00 MB

OK (130 tests, 191 assertions)
✔ Ran `vendor/bin/phpunit -c phpunit.xml --verbose --filter=WC_Tests_CRUD_Orders` in 'tests-cli'. (in 7s 818ms)

</details>

File: plugins/woocommerce/client/blocks/packages/components/formatted-monetary-amount/index.tsx [hunk 3]
```diff
@@ -94,6 +95,31 @@ const FormattedMonetaryAmount = ( {
...
+			return null;
+		}
+
+		return cloneElement( element as ReactElement, {
+			style: {
+				...( element as ReactElement ).props.style,
+				...rtlPrefixStyles,
+			},
+		} );
+	};
```
Comment (straku) [inline plugins/woocommerce/client/blocks/packages/components/formatted-monetary-amount/index.tsx]: I would prefer to avoid this pattern. For a few reasons:
- we are overriding the default `renderText` signature here, which means we can no longer rely on the library's default behavior (and documentation)
- we are taking over the responsibility of setting styles (and their priority), whereas in the previous implementation it was the responsibility of the code that was providing `renderText` implementation

If you take a look at the [react-number-format implementation of `renderText`](https://github.com/s-yadav/react-number-format/blob/v4.9.3/src/number_format.js#L1045-L1051) it passes all the props as second argument. We're not using it anywhere, but I argue that we should. That way the usage would change from (pseudocode):
```ts
// before
renderText={(value) => <span>{value}</span>}

// after
// the custom styles that you are setting should be available in otherProps
renderText=((value, otherProps) => <span {...otherProps}>{value}</span>

// we can be even more specific
renderText=((value, { style }) => <span style={style}>{value}</span>
```
So what I would suggest, instead of reimplementing the function, let's update our usages of `renderText` to properly use the second argument. Either spreading it all (this would need thorough additional testing) or focusing on the style props (less testing).

What do you think?

**Review by straku — CHANGES_REQUESTED** [review]
Thank you for your hard work, please address [this comment](https://github.com/woocommerce/woocommerce/pull/58134/files?diff=unified&w=0#r2177276589) and we will get it merged 😊

File: plugins/woocommerce/client/blocks/packages/components/formatted-monetary-amount/index.tsx (hunk 3 above)
Comment (AhmarZaidi) [reply plugins/woocommerce/client/blocks/packages/components/formatted-monetary-amount/index.tsx]: Hey @straku

Custom style for `renderText` was manily required currently for Sale Prices since the styles applied by `numberFormatProps` were not reflefting the correct currency symbol direction.

The reason I used this approach (of cloning the renderText element with custom `rtlPrefixStyles` styles) was that, these same styles need to be applied to all the places where a custom renderText is provided (as in the case of Sale Price) so I thould handling all such cases in the `FormattedMonetaryAmount` component would be better.

However, it may be better to use the library's inbuilt provisions and new implementataions using custom renderText could follow the method used here.

File: plugins/woocommerce/client/blocks/assets/js/base/components/product-price/index.tsx [hunk 4]
```diff
@@ -288,6 +301,15 @@ const ProductPrice = ( {
...
 	if ( isDiscounted ) {
+		// If we have rtl character in the prefix, we need to set the direction to ltr
+		// to avoid the price being displayed in the wrong direction.
+		const rtlPrefixStyles =
+			currency?.prefix !== ''
+				? {
+						unicodeBidi: 'bidi-override' as const,
+						direction: 'ltr' as const,
+				  }
+				: {};
```
[the remark this answers is not in the document]
Comment (AhmarZaidi) [reply plugins/woocommerce/client/blocks/assets/js/base/components/product-price/index.tsx]: Fixed.

**Comment by AhmarZaidi** [comment]
Hey @straku,

I've implemented the changes requested [here](https://github.com/woocommerce/woocommerce/pull/58134#discussion_r2194747392)

Please let me know if any other changes are required.

Thanks!

**Review by straku — APPROVED** [review]
Looks good to me after the latest changes 👏 I also tested with VoiceOver and the experience is the same as on trunk. I've updated the branch; once CI is green I will merge your change. Thanks for the contribution; it's a great quality of life improvement 🙏

**Comment by straku** [comment]
@AhmarZaidi We had to revert this change due to https://github.com/woocommerce/woocommerce/issues/60986. Sorry for not catching the issue during testing. The original ticket is reopened and assigned to me. If you have ideas on how to properly account for the encountered issue, feel free to leave any comments there.

**Comment by Robertght** [comment]
@straku is there any ETA on this?

**Comment by straku** [comment]
@Robertght I am investigating the issue now, but I am leaning toward the conclusion that our current implementation is correct. Are you also affected by the issue? Which version of WooCommerce are you using? Can I ask you to comment on the original issue with eventual response https://github.com/woocommerce/woocommerce/issues/49102?

**Comment by Robertght** [comment]
I'm not personally affected; however, we found some customers on our end(dotcom) affected by this bug. Thanks!
