### PR TITLE
Enhance AJAX security for product and term ordering

### LINKED ISSUE #63421: Missing Nonce Validation in WooCommerce Admin AJAX Ordering Handlers Enables CSRF (Authenticated Victim Required)
WooCommerce 10.5.2 contains two state-changing admin AJAX handlers that do not validate a nonce before processing requests:

* `WC_AJAX::product_ordering` (`includes/class-wc-ajax.php:2137`)
* `WC_AJAX::term_ordering` (`includes/class-wc-ajax.php:2105`)

Both handlers check capability (`edit_products`) but do not call `check_ajax_referer()`.<br>Authenticated requests without nonce are accepted (`HTTP 200`), creating CSRF risk for logged-in users with `edit_products` capability.

## **Platform(s) Affected:**

WooCommerce core plugin (WordPress admin AJAX endpoint `/wp-admin/admin-ajax.php`).

## **Steps To Reproduce:**

1. Install WordPress 6.9.1 and WooCommerce 10.5.2.
2. Log in as Administrator or Shop Manager.
3. Send POST request to `/wp-admin/admin-ajax.php` without nonce:
   * `action=woocommerce_product_ordering&id=15&nextid=14&previd=0`
4. Observe `HTTP 200` with JSON response.
5. Verify `menu_order` values changed (before/after DB evidence attached).
6. Repeat without authenticated session and observe rejection (`HTTP 400` in my test).

## **Impact**

Integrity impact: an attacker can trigger unauthorized product/category ordering changes by inducing a logged-in privileged user (edit_products capability) to send crafted requests without nonce protection.

### PR DESCRIPTION
**Pull request by sunyatasattva**
### Changes proposed in this Pull Request:

`WC_AJAX::product_ordering()` and `WC_AJAX::term_ordering()` are state-changing AJAX handlers that modify `menu_order` in the database. Both check `current_user_can( 'edit_products' )` but skip nonce verification, the only two handlers in the file (out of 40+) that do so. The `phpcs:disable WordPress.Security.NonceVerification.Missing` comments confirm this was a deliberate suppression but do not specifically mention the reason behind it.

This creates a CSRF risk: an attacker could trick a logged-in admin into reordering products or categories via a crafted request.

This PR adds `check_ajax_referer()` to both handlers and passes the corresponding nonces from the localized script params to the AJAX POST data in the frontend JS.

Closes #63421 

### How to test the changes in this Pull Request:

**Product ordering CSRF scenario:**

1. Open browser DevTools **Console** tab.
2. Run the following (replace `1` with a real product ID):
   ```js
   jQuery.post( ajaxurl, { action: 'woocommerce_product_ordering', id: 1, previd: 0, nextid: 0 } ).fail(function(r){ console.log('Status:', r.status); });
   ```
3. Verify the request returns **403**.

**Term ordering CSRF scenario:**

1. In the Console, run (replace `1` with a real category term ID):
   ```js
   jQuery.post( ajaxurl, { action: 'woocommerce_term_ordering', id: 1, nextid: 0, thetaxonomy: 'product_cat' } ).fail(function(r){ console.log('Status:', r.status); });
   ```
2. Verify the request returns **403**.

On top of that, verify that legitimate reordering still works.

### Milestone

- [x] Automatically assign milestone for the **[next WooCommerce version](../blob/trunk/plugins/woocommerce/woocommerce.php#L6)**

> **Note:** Check the box above to have the milestone automatically assigned when merged.
> Alternatively (e.g. for point releases), manually assign the appropriate milestone.

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message
Add nonce verification to `product_ordering` and `term_ordering` AJAX handlers to prevent CSRF.

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment

</details>

### CODE REVIEW

File: plugins/woocommerce/includes/class-wc-ajax.php [hunk 1]
```diff
@@ -2204,7 +2204,8 @@ public static function json_search_pages() {
 	 * @return void
 	 */
 	public static function term_ordering() {
-		// phpcs:disable WordPress.Security.NonceVerification.Missing
```
Comment (tyxla) [inline plugins/woocommerce/includes/class-wc-ajax.php:2207]: 😉

**Review by tyxla — APPROVED** [review]
This LGTM and tests well 👍
