### PR TITLE
Upgrade pelago/emogrifier to v8.0 to fix CSS parsing

### LINKED ISSUE #60474: Object of class Sabberworm\CSS\Rule\Rule could not be converted to string
## **Describe the bug**

Hi devs,

I am opening this for awareness as we've seen at least three reports of this in August.

* [https://wordpress.org/support/topic/jetpack-breaks-woocommerce-email-preview/](https://wordpress.org/support/topic/jetpack-breaks-woocommerce-email-preview/)
* 10108423-zen
* 10122663-zen

Merchant in 10108423-zen reported this affected the checkout processing since it originates from Woo Emails logic for inline styles - hence halting the checkout process/renewals when Woo sends order emails

```
$css_inliner = CssInliner::fromHtml( $content )->inlineCss( $css );
```

After they disabled and re-enabled all plugins - the issue was no longer seen.

I am not sure why would it throw this - as it seems the class Rule has \__toString method - though I am not sure if there could be other scenarios that can trigger the same error

```
Object of class Sabberworm\CSS\Rule\Rule could not be converted to string in /wordpress/plugins/woocommerce/10.0.4/vendor/pelago/emogrifier/src/Css/StyleRule.php:57 
```

I'll add more to the issue as I discover. Full trace below:

```
Stack trace:
#0 /wordpress/plugins/woocommerce/10.0.4/vendor/pelago/emogrifier/src/Css/StyleRule.php(57): implode(' ', Array)
#1 /wordpress/plugins/woocommerce/10.0.4/vendor/pelago/emogrifier/src/CssInliner.php(588): Pelago\Emogrifier\Css\StyleRule->getDeclarationAsText()
#2 /wordpress/plugins/woocommerce/10.0.4/vendor/pelago/emogrifier/src/CssInliner.php(185): Pelago\Emogrifier\CssInliner->collateCssRules(Object(Pelago\Emogrifier\Css\CssDocument))
#3 /wordpress/plugins/woocommerce/10.0.4/includes/emails/class-wc-email.php(831): Pelago\Emogrifier\CssInliner->inlineCss('\n/*\n* Temporary...')
#4 /wordpress/plugins/woocommerce/10.0.4/includes/emails/class-wc-email.php(956): WC_Email->style_inline('<!DOCTYPE html>...')
#5 /wordpress/plugins/woocommerce/10.0.4/includes/emails/class-wc-email-customer-completed-order.php(73): WC_Email->send('test@test....', 'Your ...', '<!DOCTYPE html>...', 'Content-Type: t...', Array)
#6 /wordpress/core/6.8.2/wp-includes/class-wp-hook.php(326): WC_Email_Customer_Completed_Order->trigger(197882, Object(Automattic\WooCommerce\Admin\Overrides\Order))
#7 /wordpress/core/6.8.2/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)
#8 /wordpress/core/6.8.2/wp-includes/plugin.php(565): WP_Hook->do_action(Array)
#9 /wordpress/plugins/woocommerce/10.0.4/includes/class-wc-emails.php(210): do_action_ref_array('woocommerce_ord...', Array)
#10 /wordpress/core/6.8.2/wp-includes/class-wp-hook.php(324): WC_Emails::send_transactional_email(Array, Object(Automattic\WooCommerce\Admin\Overrides\Order), Array)
#11 /wordpress/core/6.8.2/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)
#12 /wordpress/core/6.8.2/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#13 /wordpress/plugins/woocommerce/10.0.4/includes/class-wc-order.php(448): do_action('woocommerce_ord...', 197882, Object(Automattic\WooCommerce\Admin\Overrides\Order), Array)
#14 /wordpress/plugins/woocommerce/10.0.4/includes/class-wc-order.php(274): WC_Order->status_transition()
#15 /wordpress/plugins/woocommerce/10.0.4/includes/class-wc-order.php(172): WC_Order->save()
#16 /wordpress/plugins/woocommerce/10.0.4/src/StoreApi/Utilities/CheckoutTrait.php(49): WC_Order->payment_complete()
#17 /wordpress/plugins/woocommerce/10.0.4/src/StoreApi/Routes/V1/Checkout.php(559): Automattic\WooCommerce\StoreApi\Routes\V1\Checkout->process_without_payment(Object(WP_REST_Request), Object(Automattic\WooCommerce\StoreApi\Payments\PaymentResult))
#18 /wordpress/plugins/woocommerce/10.0.4/src/StoreApi/Routes/V1/AbstractRoute.php(119): Automattic\WooCommerce\StoreApi\Routes\V1\Checkout->get_route_post_response(Object(WP_REST_Request))
#19 /wordpress/plugins/woocommerce/10.0.4/src/StoreApi/Routes/V1/Checkout.php(158): Automattic\WooCommerce\StoreApi\Routes\V1\AbstractRoute->get_response_by_request_method(Object(WP_REST_Request))
#20 /wordpress/core/6.8.2/wp-includes/rest-api/class-wp-rest-server.php(1292): Automattic\WooCommerce\StoreApi\Routes\V1\Checkout->get_response(Object(WP_REST_Request))
#21 /wordpress/core/6.8.2/wp-includes/rest-api/class-wp-rest-server.php(1125): WP_REST_Server->respond_to_request(Object(WP_REST_Request), '/wc/store/v1/ch...', Array, NULL)
#22 /wordpress/core/6.8.2/wp-includes/rest-api/class-wp-rest-server.php(439): WP_REST_Server->dispatch(Object(WP_REST_Request))
#23 /wordpress/core/6.8.2/wp-includes/rest-api.php(459): WP_REST_Server->serve_request('/wc/store/v1/ch...')
#24 /wordpress/core/6.8.2/wp-includes/class-wp-hook.php(324): rest_api_loaded(Object(WP))
#25 /wordpress/core/6.8.2/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)
#26 /wordpress/core/6.8.2/wp-includes/plugin.php(565): WP_Hook->do_action(Array)
#27 /wordpress/core/6.8.2/wp-includes/class-wp.php(418): do_action_ref_array('parse_request', Array)
#28 /wordpress/core/6.8.2/wp-includes/class-wp.php(818): WP->parse_request('')
#29 /wordpress/core/6.8.2/wp-includes/functions.php(1342): WP->main('')
#30 /wordpress/core/6.8.2/wp-blog-header.php(16): wp()
#31 /wordpress/core/6.8.2/index.php(17): require('/wordpress/core...')
#32 {main}
```

### PR DESCRIPTION
**Pull request by pavel-mailpoet**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Merchants reported "Object of class Sabberworm\CSS\Rule\Rule could
  not be converted to string" errors during checkout when WooCommerce
  sends order emails. Caused by version mismatch.

The issue occurred in email CSS inlining when Rule objects were
  implicitly converted to strings without calling render() method.

Upgrading emogrifier from v7.3 to v8.0 includes sabberworm/
  php-css-parser v9.0 which fixes the Rule object string conversion
  and provides better type handling for CSS parsing.

Closes #60474 [WOOPLUG-5371].

### Screenshots or screen recordings:

Here is the email rendered with the new version with and without the new editor:

Screenshot 2025-08-20 at 12 41 27

Screenshot 2025-08-20 at 12 42 40

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Test sending WooCommerce emails and verify that they are rendered properly.
2. Activate the Block Email Editor (alpha) feature
3. Test sending and rendering WooCommerce emails and verify that the new emails are rendered properly too.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce/lib/packages/Detection/MobileDetect.php [hunk 1]
```diff
@@ -829,7 +829,7 @@ class MobileDetect
      * @param string|null $userAgent Inject the User-Agent header. If null, will use HTTP_USER_AGENT
      *                               from the $headers array instead.
      */
-    public function __construct(?array $headers = null, ?string $userAgent = null)
+    public function __construct(array $headers = null, string $userAgent = null)
```
Comment (costasovo) [inline plugins/woocommerce/lib/packages/Detection/MobileDetect.php]: I have a concern about this change and others in this file. Because technically, this is a BC Break. The previous code allows `new MobileDetect(null, null);` but after the change this would cause an error. This will also cause PHP Warning in PHP8.4.
Is this related/needed to "Upgrade pelago/emogrifier to v8.0 to fix CSS parsing"?

```
Implicitly marking parameter $headers as nullable is deprecated, the explicit nullable type must be used instead in
```

**Review by costasovo — COMMENTED** [review]
@pavel-mailpoet  I tested it locally and can confirm that the emails render with the updated library.
I noticed potential issues in the MobileDetect class. Please see my other comment.

File: plugins/woocommerce/lib/packages/Detection/MobileDetect.php (hunk 1 above)
Comment (pavel-mailpoet) [reply plugins/woocommerce/lib/packages/Detection/MobileDetect.php]: This is why this was changed:

  1. The composer update process updated the external mobiledetect/mobiledetectlib package in vendor/
  2. WooCommerce has a build process (build-lib.sh) that runs after composer updates
  3. This build process uses Mozart (a PHP dependency rewriter) to copy and rewrite external dependencies into
  WooCommerce's own lib/packages/ directory
  4. So plugins/woocommerce/lib/packages/Detection/MobileDetect.php is actually WooCommerce's vendored/bundled copy of the mobiledetect library that gets updated whenever the external dependency is updated through Mozart's rewriting process. This is WooCommerce's way of bundling external dependencies into their own codebase rather than relying on users to have them in vendor/. The file got updated because Mozart successfully rewrote the updated mobiledetect library into WooCommerce's lib structure, despite the error message.
  
  
  I will try to revert that, but I am not sure if it is possible.

Comment (costasovo) [reply plugins/woocommerce/lib/packages/Detection/MobileDetect.php]: Aha! Thanks for explanation. I found that someone made these changes manually https://github.com/woocommerce/woocommerce/commit/e386dcbfe79b6386be1665fb62e10d444831eddd some time ago to prevent the issues with warnings.
So it seems that they were patched incorrectly in the packages folder that is automatically updated. But still letting the changes in would cause the warnings.

Comment (pavel-mailpoet) [reply plugins/woocommerce/lib/packages/Detection/MobileDetect.php]: Updated

**Review by costasovo — APPROVED** [review]
@pavel-mailpoet  Thank you for updating the nullable params!

@prettyboymp I see you were assigned as a Flux member. I think it is because the PR contains some dependency updates. Do you want to take a look or is it ok to merge?

### Testing

I tested with the block editor both enabled and disabled and received emails rendered properly.
I did not experienced any notices or warnigns in debug.log

| Enabled | Disabled |
|---------|----------|
|Screenshot 2025-08-22 at 11 14 17| Screenshot 2025-08-22 at 11 12 24|

**Review by prettyboymp — CHANGES_REQUESTED** [review]
I believe we want to leave out the change to the composer.lock files in the bin directory.  I'm not sure why it is running since the version of `bamarni/composer-bin-plugin` we use shouldn't be automatically forwarding the update commands.

**Comment by pavel-mailpoet** [comment]
@prettyboymp and @costasovo, I updated this and reset the files.

**Review by prettyboymp — APPROVED** [review]
The dependency changes look good.  I have not tested the email integration.  @costasovo, it can be merged if you have validated that everything works as expected.
