### PR TITLE
Fix product images not displaying in transactional emails

### LINKED ISSUE #58950: New email template product images do not work when upgrading from existing store, unless you opt-in, then out out, then in again
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

After upgrading to the new WooCommerce email template system, product images do not appear in transactional emails (e.g., order confirmation) on existing stores — unless the email template opt-in setting is toggled off and back on again.

### Expected behavior

Product images should display correctly upon first enabling the new email templates, without needing to toggle the setting off and on again.

### Actual behavior

Product images do not appear unless the opt-in is toggled off and back on after the upgrade.

Tested On:

    Reproduced consistently on 7 different production WooCommerce sites (all existing installs upgraded to latest).

    All were running standard setups with no major customisation of email templates.

### Steps to reproduce

1.     Upgrade an existing WooCommerce store to the latest version with the new email template system.
2.     Enable the new email templates via WooCommerce > Settings > Emails.
3.     Send a test email or place an order.
4.     Observe that product images are missing.
5.     Disable the new email template system, save.
6.     Re-enable the new email template system, save again.
7.     Send another test email — product images now appear correctly.

### WordPress Environment

<details><summary>System Status Report</summary>

```
### WordPress Environment ###

WordPress address (URL): [Redacted]
Site address (URL): [Redacted]
WC Version: 9.9.4
Legacy REST API Package Version: The Legacy REST API plugin is not installed on this site.
Action Scheduler Version: ✔ 3.9.2
Log Directory Writable: ✔
WP Version: 6.8.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_GB
External object cache: ✔

### Server Environment ###

Server Info: LiteSpeed
Server Architecture: Linux 6.8.0-57-generic x86_64
PHP Version: 8.2.28
PHP Post Max Size: 256 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 8.5.0
OpenSSL/3.0.13

SUHOSIN Installed: –
MySQL Version: 11.4.7-MariaDB-ubu2404
Max Upload Size: 256 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

[REDACTED]

### Post Type Counts ###

acf-field: 1
acf-field-group: 1
aoc_popup: 1
attachment: 1488
bafg: 4
bookable_resource: 2
boxzilla-box: 4
custom_css: 2
customize_changeset: 3
dzsrst_items: 1
elementor_library: 1
erm_menu: 1
erm_menu_item: 2
event: 1
fdm-menu: 2
fdm-menu-item: 29
flamingo_contact: 657
flamingo_inbound: 1331
food-menu: 2
lc_block: 1
lc_dynamic_template: 1
lc_partial: 17
lc_section: 12
mc4wp-form: 1
mep_events: 1
mep_events_attendees: 1
nav_menu_item: 30
oembed_cache: 19
page: 63
post: 34
product: 278
product_variation: 16
revision: 718
rl_gallery: 27
sa_slider: 2
shop_order: 944
shop_order_refund: 17
sp_wp_carousel: 3
ticket-meta-fieldset: 5
tribe_events: 61
tribe_organizer: 1
tribe_rsvp_attendees: 194
tribe_rsvp_tickets: 3
tribe_tpp_tickets: 12
tribe_venue: 1
tribe_wooticket: 1657
tribe-ea-record: 1
twabc: 1
venue: 1
wc_booking: 8
wpcf7_contact_form: 15

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (40) ###

Better Search Replace: by WP Engine – 1.4.10
Boxzilla: by ibericode – 3.4.2
All In One Login: by AIO Login – 2.0.8
Classic Editor: by WordPress Contributors – 1.6.7
WP Image CAPTCHA: by WP Image CAPTCHA – 3.3.26
Contact Form 7: by Takayuki Miyoshi – 6.0.6
CookieYes | GDPR Cookie Consent: by CookieYes – 3.2.10
Event Tickets Plus: by The Events Calendar – 6.6.0
Event Tickets: by The Events Calendar – 5.24.1.1
Advanced Shipping Rates for WooCommerce: by wpcentrics – 2.1.0
Flamingo: by Takayuki Miyoshi – 2.5
FluentSMTP: by FluentSMTP & WPManageNinja Team – 2.2.90
Fluid Checkout for WooCommerce - Lite: by Fluid Checkout – 4.0.6
hCaptcha for WP: by hCaptcha – 4.14.0
HubSpot All-In-One Marketing - Forms, Popups, Live Chat: by HubSpot – 11.3.6
LiteSpeed Cache: by LiteSpeed Technologies – 7.1
LiveCanvas: by The LiveCanvas Team – 4.5.0
MC4WP: Mailchimp for WordPress: by ibericode – 4.10.4
NinjaFirewall (WP Edition): by The Ninja Technologies Network – 4.7.5
NinjaScanner: by The Ninja Technologies Network – 3.2.5
OG — Better Share on Social Media: by Marcin Pietrzak – 3.3.7
Fixed Widget: by Thomas Maier
Max Bond – 6.2.3

eCommerce Theme Core: by E-COMMERCE – 1.0.0
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 3.1.6
Responsive Lightbox & Gallery: by dFactory – 2.5.2
Schema & Structured Data for WP & AMP: by Magazine3 – 1.47
Rank Math SEO: by Rank Math SEO – 1.0.246
Table of Contents Plus: by All in One SEO Team – 2411.1
The Events Calendar Shortcode & Block: by Event Calendar Newsletter – 3.1
The Events Calendar: by The Events Calendar – 6.13.2.1
User Role Editor: by Vladimir Garagulya – 4.64.5
XT Floating Cart for WooCommerce: by XplodedThemes – 2.8.6
Advanced Order Export For WooCommerce: by AlgolPlus – 4.0.2
Shipping Method Display Style for WooCommerce: by theDotstore – 3.7.9
WooCommerce Stripe Gateway: by Stripe – 9.5.2
Google Analytics for WooCommerce: by WooCommerce – 2.1.15
WooCommerce: by Automattic – 9.9.4
WP 2FA - Two-factor authentication for WordPress: by Melapress – 2.8.0
WP Crontrol: by John Blackbourn – 1.19.1
WP Rollback: by WP Rollback – 2.0.7

### Inactive Plugins (3) ###

Disable User Login: by Saint Systems – 1.3.10
Easy Username Updater: by Yogesh C. Pant – 1.0.6
Post SMTP: by Post SMTP – 3.3.0

### Dropin Plugins () ###

maintenance.php: maintenance.php
object-cache.php: LiteSpeed Cache - Object Cache (Drop-in)

### Must Use Plugins (2) ###

LiveCanvas Compatibility Filters Plugin: by The LiveCanvas Team – 1.1.2
NinjaFirewall WP (mu-plugin): by The Ninja Technologies Network – 1.0

### Settings ###

Legacy API Enabled: –
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: accommodation-booking (accommodation-booking)
booking (booking)
external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –
Enabled Features: analytics
marketplace
order_attribution
site_visibility_badge
remote_logging
blueprint


### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 75 MB

### WC Pages ###

Shop base: #3982 - /browse-our-online-shop/
Basket: #3563 - /basket/ -  Contains the woocommerce_cart shortcode
Checkout: #3564 - /checkout/ -  Contains the woocommerce_checkout shortcode
My account: #3565 - /my-account/ -  Contains the [woocommerce_my_account] shortcode
Terms and conditions: ❌ Page not set

### Theme ###

Name: qcd
Version: 1.0.0
Author URL: 
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build
personally we recommend using a child theme. See: How to create a child theme

Theme type: Classic theme
WooCommerce Support: ✔

### Templates ###

Overrides: qcd/woocommerce/archive-product.php
qcd/woocommerce/cart/cart.php
qcd/woocommerce/cart/cross-sells.php
qcd/woocommerce/content-product.php
qcd/woocommerce/content-single-product.php
qcd/woocommerce/content-widget-price-filter.php
qcd/woocommerce/content-widget-reviews.php
qcd/woocommerce/emails/customer-completed-order.php version 3.7.0 is out of date. The core version is 9.9.0
qcd/woocommerce/emails/customer-on-hold-order.php version 3.7.0 is out of date. The core version is 9.8.0
qcd/woocommerce/emails/customer-processing-order.php version 3.7.0 is out of date. The core version is 9.9.0
qcd/woocommerce/global/breadcrumb.php
qcd/woocommerce/global/form-login.php
qcd/woocommerce/global/quantity-input.php
qcd/woocommerce/global/sidebar.php
qcd/woocommerce/global/wrapper-end.php
qcd/woocommerce/global/wrapper-start.php
qcd/woocommerce/loop/loop-end.php
qcd/woocommerce/loop/loop-start.php
qcd/woocommerce/loop/no-products-found.php
qcd/woocommerce/loop/pagination.php
qcd/woocommerce/myaccount/form-login.php
qcd/woocommerce/product-searchform.php
qcd/woocommerce/single-product/add-to-cart/variable.php
qcd/woocommerce/single-product/add-to-cart/variation.php
qcd/woocommerce/single-product/meta.php version 3.0.0 is out of date. The core version is 9.7.0
qcd/woocommerce/single-product/product-image.php
qcd/woocommerce/single-product/product-thumbnails.php
qcd/woocommerce/single-product/related.php
qcd/woocommerce/single-product/tabs/description.php
qcd/woocommerce/single-product/tabs/tabs.php
qcd/woocommerce/single-product/up-sells.php
qcd/woocommerce/single-product-reviews.php
qcd/woocommerce/single-product.php
qcd/woocommerce/content-product_cat.php
qcd/woocommerce/taxonomy-product_cat.php
qcd/woocommerce/taxonomy-product_tag.php

Outdated Templates: ❌
					
					
						Learn how to update					 |
					
						
					
					
						Clear system status theme info cache

### WooCommerce Stripe Payment Gateway ###

Version: 9.5.2
Account ID: -------------------------
Account Email: ----------------------------
Test Mode Enabled: ✔
					No
OAuth Connected: ✔
					Yes
Legacy Checkout Experience: ✔
					No
Enabled Payment Methods: card,klarna,link,bacs_debit
Express Checkout: ✔
					Enabled (product,cart,checkout)
Auth and Capture: ✔
					Yes
Logging: No

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
onboarding
onboarding-tasks
pattern-toolkit-full-composability
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
printful
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page
launch-your-store
add-to-cart-with-options-stepper-layout
disable-core-profiler-fallback

Disabled Features: product-data-views
experimental-blocks
coming-soon-newsletter-template
minified-js
point-of-sale
product-pre-publish-modal
settings
async-product-editor-category-field
product-editor-template-system
use-wp-horizon
blockified-add-to-cart

Daily Cron: ✔ Next scheduled: 2025-06-19 10:18:27 +01:00
Options: ✔
Notes: 221
Onboarding: completed

### Action Scheduler ###

Complete: 264
Oldest: 2025-05-18 16:16:46 +0100
Newest: 2025-06-18 11:13:46 +0100

Failed: 36,483
Oldest: 2022-09-20 09:13:06 +0100
Newest: 2025-06-17 14:05:09 +0100

Pending: 28
Oldest: 2025-06-18 21:14:34 +0100
Newest: 2026-03-19 23:00:00 +0000


### Status report information ###

Generated at: 2025-06-18 11:36:11 +01:00
```
</details>

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by pavel-mailpoet**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Product images were missing in emails after upgrading to the new email template system when lazy loading attributes were being applied. Email clients don’t support JavaScript-based lazy loading, which caused images to show placeholder data instead of actual product images. This fix removes lazy loading attributes from product thumbnails in email contexts.

Closes #58950. 

Bug introduced in PR [#54440](https://github.com/woocommerce/woocommerce/pull/54440).

### Screenshots or screen recordings:

| Before | After |
| ------ | ----- |
|     Screenshot 2025-06-20 at 9 57 02   |    Screenshot 2025-06-20 at 11 29 23  |

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Enable email improvements: WooCommerce > Settings > Emails > Enable new email templates
2. Enable a theme/plugin that adds lazy loading to product images
3. Place a test order or send a test email
4. Check the email HTML - you should see the broken lazy loading structure

**Popular plugins that add lazy loading:** Autoptimize, WP Rocket, Lazy Load by WP Rocket, Smush

Or use a manual snippet:
```
add_filter( 'woocommerce_order_item_thumbnail', function( $image, $item ) {
    if ( strpos( $image, '<img' ) !== false ) {
        $image = str_replace( 'class="', 'class="lazyload ', $image );
        $image = str_replace( 'src="', 'src="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==" data-src="', $image );
    }
    return $image;
}, 10, 2 );
```

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

**Review by NeosinneR — COMMENTED** [review]
I'd like to suggest a different approach here, for a couple of reasons:
1. The number of regexes makes this a fairly complex implementation to understand and maintain. Also easy to introduce a bug. 
2. It makes some assumptions (presence of `lazyload` and `data-src`), which might exclude some lazy-loading plugins. 
3. It's undoing an operation, resulting in wasted performance. 

What I'd suggest is to prevent the images from becoming lazy loaded in the first place. Lazy loading plugins have a way to prevent applying lazy loading by adding a special class or an attribute. Quickly checking with ChatGPT, adding `skip-lazy` and `no-lazyload` classes should cover the most popular plugins, but it might be worth doing a bit more research, if there are other popular classes or attributes, to improve the coverage. 

Then it should be a matter of using WC filter to modify the image in emails before the lazy-loading plugins do their work. What do you think about this approach?

**Comment by NeosinneR** [comment]
FYI, the images can be displayed also in the old email templates, they are just off by default. So the issue itself is present in the Core for years and is not directly tied to new email templates - they just made it more visible.

File: plugins/woocommerce/includes/emails/class-wc-email.php [hunk 1]
```diff
@@ -1491,4 +1494,40 @@ private function get_block_email_html_content(): ?string {
...
+		// These are the most common skip classes used by popular lazy loading plugins.
+		if ( isset( $attributes['class'] ) ) {
+			$classes = array_filter( array_map( 'trim', explode( ' ', $attributes['class'] ) ) );
+			// Add skip classes if they don't already exist.
+			$skip_classes = array( 'skip-lazy', 'no-lazyload', 'lazyload-disabled', 'no-lazy', 'skip-lazyload' );
+			foreach ( $skip_classes as $skip_class ) {
+				if ( ! in_array( $skip_class, $classes, true ) ) {
+					$classes[] = $skip_class;
+				}
+			}
```
Comment (NeosinneR) [inline plugins/woocommerce/includes/emails/class-wc-email.php]: Can this be just `$classes = array_unique( array_merge( $classes, $skip_classes ) )`?

File: plugins/woocommerce/includes/emails/class-wc-email.php [hunk 2]
```diff
@@ -1491,4 +1494,40 @@ private function get_block_email_html_content(): ?string {
...
+			$attributes['class'] = implode( ' ', $classes );
+		} else {
+			// No class attribute exists, add one with skip classes.
+			$attributes['class'] = 'skip-lazy no-lazyload lazyload-disabled no-lazy skip-lazyload';
```
Comment (NeosinneR) [inline plugins/woocommerce/includes/emails/class-wc-email.php]: This list is duplicating the one above (`implode( ' ', $skip_classes )`) and in the future when we extend one, it's possible to forget update both. Could you please unify them?

**Review by NeosinneR — CHANGES_REQUESTED** [review]
Noting, that I can't really replicate the issue so I couldn't verify the before and after that it actually worked. 

I'd like to request some changes in the code to simplify and improve it, but I assume you verified it actually fixed the issue.

**Comment by NeosinneR** [comment]
@coderabbitai rereview again

**Review by NeosinneR — APPROVED** [review]
