### PR TITLE
Prevent possible activation notice due to early initialization of feature settings

### LINKED ISSUE #41363: Function FeaturesController::get_compatible_plugins_for_feature was called incorrectly
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

There is a https://github.com/woocommerce/woocommerce/issues/41003, but it has emphasis on unit tests which could be misleading because the bug is reproducable in a clear way without phpunit involved.

I setup a clean site with wp cli, download and activate WC 8.3.0-rc.2 and get a php notice.

### Expected behavior

Activate WC plugin without any PHP notices.

### Actual behavior

When activating WC 8.3.0-rc.2 with wp cli, I am getting the following:

> wp plugin activate woocommerce

```
PHP Notice:  Function FeaturesController::get_compatible_plugins_for_feature was called incorrectly. FeaturesController::get_compatible_plugins_for_feature should not be called before the woocommerce_init action. Backtrace: include('phar:///usr/local/bin/wp/php/boot-phar.php'), include('phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/wp-cli.php'), WP_CLI\bootstrap, WP_CLI\Bootstrap\LaunchRunner-&gt;process, WP_CLI\Runner-&gt;start, WP_CLI\Runner-&gt;run_command_and_exit, WP_CLI\Runner-&gt;run_command, WP_CLI\Dispatcher\Subcommand-&gt;invoke, call_user_func, WP_CLI\Dispatcher\CommandFactory::WP_CLI\Dispatcher\{closure}, call_user_func, Plugin_Command-&gt;activate, activate_plugin, do_action('activate_woocommerce/woocommerce.php'), WP_Hook-&gt;do_action, WP_Hook-&gt;apply_filters, WC_Install::install, WC_Install::create_options, WC_Settings_Page-&gt;get_settings, WC_Settings_Page-&gt;get_settings_for_section, apply_filters('woocommerce_get_settings_advanced'), WP_Hook-&gt;apply_filters, Automattic\WooCommerce\Internal\Fea in /var/www/blank2/wp-includes/functions.php on line 6031
Notice: Function FeaturesController::get_compatible_plugins_for_feature was called incorrectly. FeaturesController::get_compatible_plugins_for_feature should not be called before the woocommerce_init action. Backtrace: include('phar:///usr/local/bin/wp/php/boot-phar.php'), include('phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/wp-cli.php'), WP_CLI\bootstrap, WP_CLI\Bootstrap\LaunchRunner-&gt;process, WP_CLI\Runner-&gt;start, WP_CLI\Runner-&gt;run_command_and_exit, WP_CLI\Runner-&gt;run_command, WP_CLI\Dispatcher\Subcommand-&gt;invoke, call_user_func, WP_CLI\Dispatcher\CommandFactory::WP_CLI\Dispatcher\{closure}, call_user_func, Plugin_Command-&gt;activate, activate_plugin, do_action('activate_woocommerce/woocommerce.php'), WP_Hook-&gt;do_action, WP_Hook-&gt;apply_filters, WC_Install::install, WC_Install::create_options, WC_Settings_Page-&gt;get_settings, WC_Settings_Page-&gt;get_settings_for_section, apply_filters('woocommerce_get_settings_advanced'), WP_Hook-&gt;apply_filters, Automattic\WooCommerce\Internal\Fea in /var/www/blank2/wp-includes/functions.php on line 6031
PHP Notice:  Function FeaturesController::get_compatible_plugins_for_feature was called incorrectly. FeaturesController::get_compatible_plugins_for_feature should not be called before the woocommerce_init action. Backtrace: include('phar:///usr/local/bin/wp/php/boot-phar.php'), include('phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/wp-cli.php'), WP_CLI\bootstrap, WP_CLI\Bootstrap\LaunchRunner-&gt;process, WP_CLI\Runner-&gt;start, WP_CLI\Runner-&gt;run_command_and_exit, WP_CLI\Runner-&gt;run_command, WP_CLI\Dispatcher\Subcommand-&gt;invoke, call_user_func, WP_CLI\Dispatcher\CommandFactory::WP_CLI\Dispatcher\{closure}, call_user_func, Plugin_Command-&gt;activate, activate_plugin, do_action('activate_woocommerce/woocommerce.php'), WP_Hook-&gt;do_action, WP_Hook-&gt;apply_filters, WC_Install::install, WC_Install::create_options, WC_Settings_Page-&gt;get_settings, WC_Settings_Page-&gt;get_settings_for_section, apply_filters('woocommerce_get_settings_advanced'), WP_Hook-&gt;apply_filters, Automattic\WooCommerce\Internal\Fea in /var/www/blank2/wp-includes/functions.php on line 6031
Notice: Function FeaturesController::get_compatible_plugins_for_feature was called incorrectly. FeaturesController::get_compatible_plugins_for_feature should not be called before the woocommerce_init action. Backtrace: include('phar:///usr/local/bin/wp/php/boot-phar.php'), include('phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/wp-cli.php'), WP_CLI\bootstrap, WP_CLI\Bootstrap\LaunchRunner-&gt;process, WP_CLI\Runner-&gt;start, WP_CLI\Runner-&gt;run_command_and_exit, WP_CLI\Runner-&gt;run_command, WP_CLI\Dispatcher\Subcommand-&gt;invoke, call_user_func, WP_CLI\Dispatcher\CommandFactory::WP_CLI\Dispatcher\{closure}, call_user_func, Plugin_Command-&gt;activate, activate_plugin, do_action('activate_woocommerce/woocommerce.php'), WP_Hook-&gt;do_action, WP_Hook-&gt;apply_filters, WC_Install::install, WC_Install::create_options, WC_Settings_Page-&gt;get_settings, WC_Settings_Page-&gt;get_settings_for_section, apply_filters('woocommerce_get_settings_advanced'), WP_Hook-&gt;apply_filters, Automattic\WooCommerce\Internal\Fea in /var/www/blank2/wp-includes/functions.php on line 6031
Plugin 'woocommerce' activated.
Success: Activated 1 of 1 plugins.
```

### Steps to reproduce

```
wp core download
wp config create --dbname=blank2 --dbuser=wp --dbpass=1234
wp core install --url=http://blank2.wp --title=Blank2 --admin_user=val --admin_email="val@local.dev"
wp config set WP_DEBUG true --raw
wp plugin install woocommerce --version=8.3.0-rc.2
wp plugin activate woocommerce
```

### WordPress Environment

>wp core version
6.4.1
>php -v
PHP 7.4.33

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by jorgeatorres**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

This PR addresses a possible "doing it wrong" notice that can appear during activation if callbacks associated to features in `FeaturesController` end up calling functions (from `FeaturesController` itself) that are not available until after the `woocommerce_init` hook.

This can happen, for example, when `WC_Install::create_options()` attempts [to load settings pages](https://github.com/woocommerce/woocommerce/blob/55766ac140f6c234d548e53099c642d3590a63e3/plugins/woocommerce/includes/class-wc-install.php#L886-L894) (and thus, settings), including those [handled](https://github.com/woocommerce/woocommerce/blob/55766ac140f6c234d548e53099c642d3590a63e3/plugins/woocommerce/src/Internal/Features/FeaturesController.php#L88) by `FeaturesController`. This would only happen when it is executed as an [activation hook](https://github.com/woocommerce/woocommerce/blob/55766ac140f6c234d548e53099c642d3590a63e3/plugins/woocommerce/includes/class-woocommerce.php#L230). When it is triggered by a version change (or in any other form) this wouldn't be a problem since it'd occur during `init` and after `woocommerce_init` has run.

(See p1699891043650119-slack-C0E1AV8T0).

Closes #41363.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Manually deactivate WooCommerce (if active) and re-activate. Alternatively, use WP-CLI:
   ```
   wp plugin deactivate woocommerce && wp plugin activate woocommerce
   ```
2. Make sure no notices are logged. In particular, the following one should not occur:
   > PHP Notice:  Function FeaturesController::get_compatible_plugins_for_feature was called incorrectly. FeaturesController::get_compatible_plugins_for_feature should not be called before the woocommerce_init action.
3. Try the above on a new site (for instance using JN) and confirm that after activation, HPOS is the default order datastore. Confirm this in WC > Settings > Advanced > Features.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce/src/Internal/Features/FeaturesController.php [hunk 1]
```diff
@@ -688,19 +686,21 @@ function( $feature_id ) use ( $features ) {
 			'id'   => empty( $experimental_feature_ids ) ? 'features_options' : 'experimental_features_options',
 		);
 
-		// Allow feature setting properties to be determined dynamically just before being rendered.
-		$feature_settings = array_map(
-			function( $feature_setting ) {
-				foreach ( $feature_setting as $prop => $value ) {
-					if ( is_callable( $value ) ) {
-						$feature_setting[ $prop ] = call_user_func( $value );
+		if ( $this->verify_did_woocommerce_init() ) {
```
Comment (jorgeatorres) [inline plugins/woocommerce/src/Internal/Features/FeaturesController.php:689]: Despite what I wrote in the Slack thread, I guess it makes sense to use `verify_did_woocommerce_init()` here instead of checking whether WC is being installed. It's a way of ensuring that the callbacks we're about to... well... call are safe to use the functionality this same controller makes available. And this doesn't break the setting of defaults that `WC_Install::create_options()` performs, whether that's useful or not.

**Review by coreymckrill — APPROVED** [review]
👍 Looks good to me, and tests as described. I agree that using `verify_did_woocommerce_init()` is better than checking whether WC is being installed.
