### PR TITLE
Fix schedule sales error

### LINKED ISSUE #41898: Schedule sale error
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

The scheduled sale is not working well.

Screenshot 2023-12-05 at 15 53 13

Screenshot 2023-12-05 at 15 52 11

#### Update

Please consider that we already tried to solve this error [with this PR](https://github.com/woocommerce/woocommerce/pull/42700), but it has been reverted because it created some unexpected side effects.

The approach suggested by Vedanshu [here](https://github.com/woocommerce/woocommerce/discussions/43643#discussioncomment-8133739) seems like a possible solution:

_We can schedule an action to run at the sale start time that would call the `wc_scheduled_sales();` method._

### Expected behavior

The price set for the scheduled sale should be the same before publishing the sale.

### Actual behavior

Screenshot 2023-12-05 at 15 53 13

Even when the list and sale prices for the scheduled sale are different (in the example above are $100 and $90); the price is changed to the list price after starting the sale.

Screenshot 2023-12-05 at 15 52 11

### Steps to reproduce

1. Enable the new product experience.
2. Create a product with a scheduled sale for a moment in the future (e.g.: in two minutes).
3. After that time, go to the product and verify that the sale price is the same as the list price.

### WordPress Environment

It's happening in `trunk`.

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by octaedro**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

This PR fixes an error when setting a scheduled sale. Before this fix, the product price didn't change after the sale started. 

Before

Screenshot 2023-12-05 at 15 52 11

After

Screenshot 2023-12-12 at 10 44 37

Closes #41898.

## UPDATED

This PR only fixes the scheduled sales error for **simple products**. I also opened https://github.com/woocommerce/woocommerce/issues/42971 to tackle the error we face with scheduled sales in variable products.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Create a WooCommerce store with this branch and enable the product editor using **WooCommerce > Settings > Advanced > Features**.
2. Go to **Products > Add New** and create a product **simple** with a scheduled sale after your current time (one minute or two). Set the end of the scheduled sale one minute after the sale starts.
4. Press `Preview` quickly and verify the sale hasn't started yet.
5. Wait until the scheduled sale starts and verify that the sale price is correct.
6. Wait until the scheduled sale ends and verify that the price is the regular price again.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce/includes/data-stores/class-wc-product-data-store-cpt.php [hunk 1]
```diff
@@ -371,6 +371,13 @@ protected function read_product_data( &$product ) {
 		$set_props['gallery_image_ids'] = array_filter( explode( ',', $set_props['gallery_image_ids'] ?? '' ) );
 
 		$product->set_props( $set_props );
+		if ( 'variable' !== $product->get_type() && $product->is_on_sale() ) {
+			$product->set_price( $set_props['sale_price'] );
+			$this->clear_caches( $product );
```
Comment (louwie17) [inline plugins/woocommerce/includes/data-stores/class-wc-product-data-store-cpt.php]: I am not a huge fan of adding a specific exception here for `variable` products, given we also have subscription variable products in plugins. I think this could cause problems in the future.

Instead of adding the below logic here, would it make more sense to add it here: https://github.com/woocommerce/woocommerce/blob/12940ebcd60bf72857f8b080dbccb47638b74e7c/plugins/woocommerce/includes/abstracts/abstract-wc-product.php#L1879
Where `is_on_sale` is already being triggered?

**Review by louwie17 — CHANGES_REQUESTED** [review]
This did fix the error I was seeing previously, but not sure if I like adding a specific condition for variable products just to accommodate for that.
I left an alternative suggestion.
Btw it might be worth checking in with someone from Proton to get their intake as well.

File: plugins/woocommerce/includes/data-stores/class-wc-product-data-store-cpt.php (hunk 1 above)
Comment (octaedro) [reply plugins/woocommerce/includes/data-stores/class-wc-product-data-store-cpt.php]: Good call! I added the code to clean the cache in the commit https://github.com/woocommerce/woocommerce/pull/42700/commits/de03fd1b279f678c3c2b85880d6b428ed40188c4

**Comment by octaedro** [comment]
Hey @louwie17, I removed the code to clean the cache from this PR (to fix the error only for scheduled sales in simple products) and created [this issue](https://github.com/woocommerce/woocommerce/issues/42971) containing the information I gathered for variable products.
Could you take another look at this PR?

File: plugins/woocommerce/tests/legacy/unit-tests/product/data.php [hunk 2]
```diff
@@ -273,6 +273,41 @@ public function test_multiple_get_price_html_calls() {
 		$this->assertEquals( '<span class="woocommerce-Price-amount amount"><bdi><span class="woocommerce-Price-currencySymbol">&#36;</span>50.00</bdi></span>', $product->get_price_html() );
 	}
 
+	/**
+	 * A test ensuring get_price_html works well for scheduled sales for issue #41898.
+	 */
+	public function test_get_price_html_for_scheduled_sales() {
```
Comment (louwie17) [inline plugins/woocommerce/tests/legacy/unit-tests/product/data.php:279]: Thanks for adding a test for this :)

**Review by louwie17 — CHANGES_REQUESTED** [review]
Hmm I guess maybe the `get_price_html` isn't the only place and we want to change it in the `get_price` method?
Screenshot 2023-12-20 at 10 37 41 AM

Maybe reverting this change and instead add:
```
if ( $this->is_on_sale() ) {
			return $this->get_prop( 'sale_price', $context );
		}
```
here would solve it: https://github.com/woocommerce/woocommerce/blob/01fb8f221665897753540fe9f6f7f04c1460e80d/plugins/woocommerce/includes/abstracts/abstract-wc-product.php#L269

**Comment by octaedro** [comment]
Good eyes @louwie17! I like the `get_price` approach! I added it in the commit [61f3b7a](https://github.com/woocommerce/woocommerce/pull/42700/commits/61f3b7aaa4f19bcd20fc7a65ff1b778a6a1a4435).

**Review by louwie17 — APPROVED** [review]
LGTM 🚀 Tested well, thanks for working on this @octaedro, it was a tricky one.

File: plugins/woocommerce/includes/abstracts/abstract-wc-product.php [hunk 3]
```diff
@@ -267,6 +267,9 @@ public function get_sku( $context = 'view' ) {
 	 * @return string price
 	 */
 	public function get_price( $context = 'view' ) {
+		if ( $this->is_on_sale() ) {
+			return $this->get_prop( 'sale_price', $context );
+		}
```
Comment (nerrad) [inline plugins/woocommerce/includes/abstracts/abstract-wc-product.php:272]: This is a _pretty significant change_ to existing behaviour - especially considering there is an explicit `get_sale_price` method already available. The public contract for this method has now changed and I suspect could have a ripple effect across all code, referencing it for products that have a sale price. 

Please review and ensure this won't impact negatively existing usages.

Comment (nerrad) [reply plugins/woocommerce/includes/abstracts/abstract-wc-product.php:272]: On the surface, this does look like the right fix, but looking at code [like this](https://github.com/woocommerce/woocommerce/blob/99aeaff6dd132e55520695d07af57322c0d7bc73/plugins/woocommerce/includes/wc-product-functions.php#L451) the price field for the product is _supposed_ to be updated to the sale price in the db. I'd be wary about shipping this change as it looks like it might just be a bandaid over the real problem (and might introduce problems of its own).

Comment (nerrad) [reply plugins/woocommerce/includes/abstracts/abstract-wc-product.php:272]: To sum up my previous two comments:

- The code changed in this PR has been present for 7 years. Bugs can be in code that old, but `$product->get_price` is a pretty hot code path so we'd want to make sure any changes are not affecting the expected return value.
- The code added is an attempt to make sure `get_price` is returning the `sale price` (overriding what is in the db) if the product is on sale (to fix the apparent bug with scheduled sales not updating price).
- I'm concerned it's a bandaid over the actual problem, given the sale price is supposed to be [updated in the DB on schedule](https://github.com/woocommerce/woocommerce/blob/99aeaff6dd132e55520695d07af57322c0d7bc73/plugins/woocommerce/includes/wc-product-functions.php#L451).
- This fix on the surface looks like a good fix, but still changes the behaviour for the getter which may already be a bug accounted for in code in the wild. So the fix may have some unexpected side-effects if released as is (besides not addressing what may potentially be the real bug).

I'm concerned this fix is a shallow fix without giving appropriate thought to the ramifications of the change nor accounting for what the _real_ bug might be (for instance, why isn't the price updated in the DB?).

Comment (retrofox) [reply plugins/woocommerce/includes/abstracts/abstract-wc-product.php:272]: We've created a https://github.com/woocommerce/woocommerce/pull/43094 as we are considering reverting the change.
