### PR TITLE
[2.7] CRUD performance improvements for emails

### LINKED ISSUE #12802: [2.7] Creating an Order Exponentially Slower
## EXPLANATION OF THE ISSUE

Creating an order with a large number of products is vastly slower in WooCommerce 2.7-beta (master). 

## STEPS TO REPRODUCE THE ISSUE

1. Add ~100 products to your cart:
  https://gist.github.com/spencerfinnell/c9cf17aedf03c57a2e8f681215408ec1 
  Visit `http://yoursite.com?add-products` to add 100 items.
2. Visit the checkout page and complete the order. 
3. Check out the `release/2.6` branch and repeat. 

## SYSTEM STATUS REPORT

https://gist.github.com/spencerfinnell/509cb4a95330774b1d3ef77792f59774

### PR DESCRIPTION
**Pull request by mikejolley**
- Tweaks some of the code used during item creation for speed
- Introduces caching for orders and order item factories
- Defers email sending using CRON so requests are faster (2s to < 1s)

Closes #12802

### CODE REVIEW

File: includes/class-wc-emails.php [hunk 1]
```diff
@@ -84,17 +84,38 @@ public static function init_transactional_emails() {
...
-			add_action( $action, array( __CLASS__, 'send_transactional_email' ), 10, 10 );
+			add_action( $action, array( __CLASS__, 'queue_transactional_email' ), 10, 10 );
 		}
 	}
 
 	/**
+	 * Queue transactional email via cron so it's not sent in current request.
+	 */
+	public static function queue_transactional_email() {
+		wp_schedule_single_event( time() + 10, 'send_queued_transactional_email', array(
```
Comment (justinshreve) [inline includes/class-wc-emails.php]: I think we should probably prefix our events. The actual hook here that gets ran is `send_queued_transactional_email`, where something like `wc_send_queued_transactional_email` would have less of a chance of colliding.
