### PR TITLE
Defer nonce creation until displayed by WC Admin closes #27424

### LINKED ISSUE #27424: Notifications won't go away after clicking their button
**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
The notifications at the top won't go away after clicking their buttons:
"Coupon management has moved!"
"WooCommerce database update done"

I clicked their buttons many times, nothing happened.
I cleared cache, loged out, deleted cookies, cleared browser cache.

**Expected behavior**
The notification should go away after you click them once.

**Actual behavior**
The notifications at the top won't go away after clicking their buttons

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
This started after updating to the WC 4.4.1
Using PHP 7.4.9

**Screenshots**
https://ibb.co/hBjgzr3

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report we won't be able to fully evaluate this issue.
<details>
`
### WordPress Environment ###

WordPress address (URL): https://www.japanese-knives.co.il
Site address (URL): https://www.japanese-knives.co.il
WC Version: 4.4.1
REST API Version: ✔ 1.0.15
WC Blocks Version: ✔ 3.1.0
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.4.0
Log Directory Writable: ✔
WP Version: 5.5
WP Multisite: –
WP Memory Limit: 2 GB
WP Debug Mode: ✔
WP Cron: –
Language: he_IL
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.4.9
PHP Post Max Size: 2 GB
PHP Time Limit: 600
PHP Max Input Vars: 10000
cURL Version: 7.71.1
OpenSSL/1.1.1g

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.3.24-MariaDB
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.4.1
WC Database Prefix: hks_
Total Database Size: 361.97MB
Database Data Size: 304.73MB
Database Index Size: 57.24MB
hks_woocommerce_sessions: Data: 0.27MB + Index: 0.02MB + Engine InnoDB
hks_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
hks_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
hks_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
hks_woocommerce_order_items: Data: 2.52MB + Index: 0.42MB + Engine InnoDB
hks_woocommerce_order_itemmeta: Data: 14.52MB + Index: 10.03MB + Engine InnoDB
hks_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
hks_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
hks_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
hks_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
hks_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
hks_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
hks_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
hks_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
cerber_acl: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
cerber_blocks: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
cerber_countries: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
cerber_lab: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
cerber_lab_ip: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
cerber_lab_net: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
cerber_log: Data: 2.52MB + Index: 0.72MB + Engine InnoDB
cerber_qmem: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
cerber_traffic: Data: 159.27MB + Index: 2.48MB + Engine InnoDB
hks_actionscheduler_actions: Data: 1.52MB + Index: 0.52MB + Engine InnoDB
hks_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
hks_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
hks_actionscheduler_logs: Data: 1.52MB + Index: 0.30MB + Engine InnoDB
hks_atum_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
hks_atum_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
hks_atum_product_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
hks_cerber_files: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
hks_cerber_sets: Data: 0.28MB + Index: 0.00MB + Engine InnoDB
hks_cerber_uss: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
hks_commentmeta: Data: 0.06MB + Index: 0.09MB + Engine InnoDB
hks_comments: Data: 7.52MB + Index: 2.64MB + Engine InnoDB
hks_duplicator_packages: Data: 0.03MB + Index: 0.02MB + Engine InnoDB
hks_duplicator_pro_entities: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
hks_duplicator_pro_packages: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
hks_enquiry_detail_new: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
hks_enquiry_history: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
hks_enquiry_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
hks_enquiry_quotation: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
hks_enquiry_thread: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
hks_gcb: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
hks_grp_google_place: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
hks_grp_google_review: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
hks_huge_itgallery_gallerys: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
hks_huge_itgallery_images: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
hks_huge_itgallery_like_dislike: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
hks_huge_itgallery_params: Data: 0.02MB + Index: 0.00MB + Engine MyISAM
hks_imagify_files: Data: 0.36MB + Index: 0.33MB + Engine InnoDB
hks_imagify_folders: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
hks_itbbc_history: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
hks_itbbc_history_items: Data: 0.08MB + Index: 0.03MB + Engine InnoDB
hks_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
hks_mclean_refs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
hks_mclean_scan: Data: 0.30MB + Index: 0.00MB + Engine InnoDB
hks_media_file_manager_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
hks_nextend2_image_storage: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
hks_nextend2_section_storage: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
hks_nextend2_smartslider3_generators: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
hks_nextend2_smartslider3_sliders: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
hks_nextend2_smartslider3_sliders_xref: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
hks_nextend2_smartslider3_slides: Data: 0.30MB + Index: 0.00MB + Engine InnoDB
hks_options: Data: 27.50MB + Index: 0.59MB + Engine InnoDB
hks_postmeta: Data: 54.58MB + Index: 27.08MB + Engine InnoDB
hks_posts: Data: 9.52MB + Index: 2.42MB + Engine InnoDB
hks_redirection_404: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
hks_redirection_groups: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
hks_redirection_items: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
hks_redirection_logs: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
hks_revslider_css: Data: 0.13MB + Index: 0.00MB + Engine InnoDB
hks_revslider_css_bkp: Data: 0.13MB + Index: 0.00MB + Engine InnoDB
hks_revslider_layer_animations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
hks_revslider_layer_animations_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
hks_revslider_navigations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
hks_revslider_navigations_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
hks_revslider_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
hks_revslider_sliders: Data: 0.11MB + Index: 0.00MB + Engine InnoDB
hks_revslider_sliders_bkp: Data: 0.11MB + Index: 0.00MB + Engine InnoDB
hks_revslider_slides: Data: 0.14MB + Index: 0.00MB + Engine InnoDB
hks_revslider_slides_bkp: Data: 0.41MB + Index: 0.00MB + Engine InnoDB
hks_revslider_static_slides: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
hks_revslider_static_slides_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
hks_tcb_api_error_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
hks_termmeta: Data: 0.17MB + Index: 0.17MB + Engine InnoDB
hks_terms: Data: 1.52MB + Index: 0.53MB + Engine InnoDB
hks_term_relationships: Data: 1.52MB + Index: 0.39MB + Engine InnoDB
hks_term_taxonomy: Data: 0.38MB + Index: 0.36MB + Engine InnoDB
hks_tge_answers: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
hks_tge_questions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
hks_tm_taskmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
hks_tm_tasks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
hks_tqb_event_log: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
hks_tqb_results: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
hks_tqb_tests: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
hks_tqb_tests_items: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
hks_tqb_users: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
hks_tqb_user_answers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
hks_tqb_variations: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
hks_ukuu_favorites: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
hks_usermeta: Data: 2.52MB + Index: 3.03MB + Engine InnoDB
hks_users: Data: 0.13MB + Index: 0.14MB + Engine InnoDB
hks_wcsc_error_logs: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
hks_wcsc_logs: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
hks_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
hks_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
hks_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
hks_wc_customer_lookup: Data: 0.34MB + Index: 0.20MB + Engine InnoDB
hks_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
hks_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
hks_wc_order_product_lookup: Data: 1.52MB + Index: 0.63MB + Engine InnoDB
hks_wc_order_stats: Data: 0.41MB + Index: 0.31MB + Engine InnoDB
hks_wc_order_tax_lookup: Data: 0.27MB + Index: 0.20MB + Engine InnoDB
hks_wc_product_meta_lookup: Data: 0.13MB + Index: 0.19MB + Engine InnoDB
hks_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
hks_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
hks_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
hks_wc_zapier_history: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
hks_wd_fb_data: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
hks_wd_fb_info: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
hks_wd_fb_option: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
hks_wd_fb_shortcode: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
hks_wd_fb_theme: Data: 0.03MB + Index: 0.00MB + Engine InnoDB
hks_woocommerce_bundled_itemmeta: Data: 1.52MB + Index: 0.58MB + Engine InnoDB
hks_woocommerce_bundled_items: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
hks_yoast_indexable: Data: 6.52MB + Index: 1.09MB + Engine InnoDB
hks_yoast_indexable_hierarchy: Data: 0.08MB + Index: 0.14MB + Engine InnoDB
hks_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
hks_yoast_primary_term: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
hks_yoast_prominent_words: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
hks_yoast_seo_links: Data: 0.34MB + Index: 0.11MB + Engine InnoDB
hks_yoast_seo_meta: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
sib_model_contact: Data: 0.02MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

amn_smtp: 1
attachment: 3292
clients: 1
content_block: 75
decision_tree: 1
follow_up_email: 8
klaviyo_shop_cart: 1
nav_menu_item: 359
oembed_cache: 3
optionsframework: 12
page: 56
post: 29
postman_sent_mail: 250
product: 555
product_variation: 368
pys_event: 3
revision: 36
shop_coupon: 305
shop_order: 5003
shop_order_refund: 4
slide: 1
sp_wpsp_shortcodes: 1
thrive_image: 5
tqb_quiz: 4
tqb_results: 3
tqb_splash: 1
vc_grid_item: 1
wcct-deal-shortcode: 1
wcct_countdown: 45
wcst_trigger: 9
wc_zapier_feed: 2
wp-type-contacts: 2
wpb-rs-global: 7
wpcf7_contact_form: 1
wp_quiz: 1
xlwcty_thankyou: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (72) ###

Query Monitor: by John Blackbourn – 3.6.2
10bit-woocommerce-zap-mirror: by 10bit – 1.3.14 – Installed version not tested with active version of WooCommerce 4.4.1
Classic Editor: by WordPress Contributors – 1.6
Contact Form 7: by Takayuki Miyoshi – 5.2.1
Content Blocks (Custom Post Widget): by Johan van der Wijk – 3.1.1
Duplicate Menu: by Jonathan Christopher – 0.2.2
Enable Media Replace: by ShortPixel – 3.4.2
Envato Market: by Envato – 2.0.3
Facebook Post Embed: by Alobaidi – 1.0.0
Finale WooCommerce Deal Pages: by XLPlugins – 1.4.1 – Installed version not tested with active version of WooCommerce 4.4.1
Finale - WooCommerce Sales Countdown Timer & Discount Plugin: by XLPlugins – 2.17.1 – Installed version not tested with active version of WooCommerce 4.4.1
Force Regenerate Thumbnails: by Pedro Elsner – 2.0.6
Global Content Blocks: by Dave Liske – 2.1.5
WhatsApp Chat for WordPress / WooCommerce: by idnovate.com – 1.3.9 – Installed version not tested with active version of WooCommerce 4.4.1
Imagify: by WP Media – 1.9.10
Klaviyo: by Klaviyo
Inc. – 2.2.4 – Installed version not tested with active version of WooCommerce 4.4.1

Loco Translate: by Tim Whitlock – 2.4.2
One Time Login: by Daniel Bachhuber – 0.3.0
Perfmatters: by forgemedia – 1.6.0
PixelYourSite PRO: by PixelYourSite – 7.6.4 – Installed version not tested with active version of WooCommerce 4.4.1
plugin load filter: by enomoto@celtislab – 3.3.0
Post SMTP: by Yehuda Hassine – 2.0.15
Product Filter for WooCommerce: by XforWooCommerce – 7.3.3 – Installed version not tested with active version of WooCommerce 4.4.1
Product Catalog Feed Pro by PixelYourSite: by PixelYourSite – 4.1.3 – Installed version not tested with active version of WooCommerce 4.4.1
PushAlert - Web Push Notifications: by PushAlert – 2.6.0 – Installed version not tested with active version of WooCommerce 4.4.1
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 3.1.3
Slider Revolution: by ThemePunch – 6.2.22
snip - The Rich Snippets & Structured Data Plugin: by wpbuddy – 2.19.0
Search & Replace: by Inpsyde GmbH – 3.2.1
ShiftNav Pro - Responsive Mobile Menu: by Chris Mavricos
SevenSpark – 1.7.0.1

Shortcode Empty Paragraph Fix: by  – 0.2
SmartLook Visitor Recording: by Smartsupp – 2.1.1
Hide SEO Bloat: by SO WP – 3.14.3
Social Icons Widget & Block by WPZOOM: by WPZOOM – 4.0.3
SOFT79 Cart Links for WooCommerce: by Soft79 – 1.1.4 – Installed version not tested with active version of WooCommerce 4.4.1
WooCommerce Thank You Page - NextMove: by XLPlugins – 1.14.0 – Installed version not tested with active version of WooCommerce 4.4.1
TWB Woocommerce Reviews: by Abu Bakar – 1.7.3 – Installed version not tested with active version of WooCommerce 4.4.1
UberMenu 3 - The Ultimate WordPress Mega Menu: by Chris Mavricos
SevenSpark – 3.7.2

Widget CSS Classes: by C.M. Kendrick – 1.5.4
CardCom Payment Gateway: by CardCom LTD – 3.3.2.8 – Installed version not tested with active version of WooCommerce 4.4.1
WooCommerce Breadcrumbs: by Anthony Hortin – 1.0.7 – Installed version not tested with active version of WooCommerce 4.4.1
WooCommerce - Frontend Inventory: by Mirko Grewing – 0.7 – Installed version not tested with active version of WooCommerce 4.4.1
WooCommerce Google Ads Conversion Tracking: by Wolf+Bär Agency – 1.6.9
WooCommerce Google Analytics Pro: by SkyVerge – 1.8.14 – Installed version not tested with active version of WooCommerce 4.4.1
WooCommerce Notification Premium: by Andy Ha (villatheme.com) – 1.4.2 – Installed version not tested with active version of WooCommerce 4.4.1
WooCommerce Product Bundles: by SomewhereWarm – 6.3.3 – Installed version not tested with active version of WooCommerce 4.4.1
WooCommerce Product Primary Category: by BeoCode.d.o.o. – 0.1.2 – Installed version not tested with active version of WooCommerce 4.4.1
WooCommerce Show Attributes: by Isabel Castillo – 1.6.4 – Installed version not tested with active version of WooCommerce 4.4.1
WooCommerce Zapier: by OM4 – 2.0.4 – Installed version not tested with active version of WooCommerce 4.4.1
WooCommerce: by Automattic – 4.4.1
WooSidebars: by WooCommerce – 1.4.5
Yoast SEO Premium: by Team Yoast – 14.8
WP Accessibility Helper: by Alex Volkov – 0.5.9.4
WP Cerber Security, Anti-spam & Malware Scan: by Cerber Tech Inc. – 8.6.7
WP-Cron Status Checker: by Webhead LLC – 1.2.1
Custom Body Class: by Andrei Lupu – 0.7.2
WP Memory: by Bill Minozzi – 1.1
WP-Optimize - Clean, Compress, Cache: by David Anderson
Ruhani Rabin
Team Updraft – 3.1.2

WP Rocket | Set Tablets As Mobile: by WP Rocket Support Team –
WP Rocket | YITH WooCommerce Recently Viewed Products Integration: by WP Rocket Support Team –  – Installed version not tested with active version of WooCommerce 4.4.1
WP Rocket | Custom cURL Timeout For Preload Requests: by WP Rocket Support Team –
WP Rocket | CPCSS Debug Helper: by WP Rocket Support Team – 1.0.0
WP Rocket | Exclude Files from Defer JS: by WP Rocket Support Team –
WP Rocket: by WP Media – 3.6.4
WP-RTL: by Fahad Alduraibi – 1.0
WP Server Stats: by Saumya Majumder
Acnam Infotech – 1.6.9

WP-Sweep: by Lester 'GaMerZ' Chan – 1.1.3
WP User Avatars: by John James Jacoby – 1.4.0
WPX Cron Manager Light: by Giovambattista Fazioli – 2.3.4
Finale Email Countdown Timer: by XLPlugins – 1.2.0 – Installed version not tested with active version of WooCommerce 4.4.1
XL WooCommerce Sales Triggers: by XLPlugins – 2.10.0 – Installed version not tested with active version of WooCommerce 4.4.1
Embed Plus for YouTube Pro - Gallery, Channel, Playlist, Live Stream: by Embed Plus for YouTube Team – 13.4.1

### Inactive Plugins (13) ###

Akismet Anti-Spam: by Automattic – 4.1.6
Contact Form 7 Captcha: by 247wd – 0.0.7
Duplicator: by Snap Creek – 1.3.36
Health Check & Troubleshooting: by The WordPress.org community – 1.4.4
Hello Dolly: by Matt Mullenweg – 1.7.2
Media Cleaner (Pro): by Jordy Meow – 6.0.2
Redirection: by John Godley – 4.8
Stop Generating Unnecessary Thumbnails: by codexpert – 3.0.4
What The File: by Never5 – 1.5.4
Widget Options: by Widget Options Team – 3.7.4
Widget Shortcode: by Hassan Derakhshandeh – 0.3.5
WooCommerce Blocks: by Automattic – 3.2
WooCommerce Conversion Tracking: by weDevs – 2.0.8 – Installed version not tested with active version of WooCommerce 4.4.1

### Dropin Plugins (3) ###

advanced-cache.php: advanced-cache.php
db.php: Query Monitor Database Class
maintenance.php: maintenance.php

### Must Use Plugins (3) ###

aaa-wp-cerber.php: by Cerber Tech Inc. – 1.0
Health Check Troubleshooting Mode: by  – 1.7.1
plugin load filter [plf-filter]: by enomoto@celtislab – 3.3.0

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: ILS (₪)
Currency Position: right
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: bundle (bundle)
external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #1812 - /shop/
Cart: #5 - /cart/
Checkout: #6 - /order/
My account: #7 - /my-account/
Terms and conditions: #605 - /legal/

### Theme ###

Name: Flatsome Child
Version: 3.0
Author URL: 
Child Theme: ✔
Parent Theme Name: Flatsome
Parent Theme Version: 3.12.2
Parent Theme Author URL: http://www.uxthemes.com/
WooCommerce Support: ✔

### Templates ###

Overrides: flatsome/woocommerce/archive-product.php
flatsome/woocommerce/cart/cart-empty.php
flatsome/woocommerce/cart/cart-shipping.php
flatsome/woocommerce/cart/cart.php
flatsome/woocommerce/checkout/form-checkout.php
flatsome/woocommerce/checkout/form-coupon.php
flatsome/woocommerce/checkout/terms.php
flatsome/woocommerce/checkout/thankyou.php
flatsome/woocommerce/content-product.php
flatsome/woocommerce/content-product_cat.php
flatsome/woocommerce/content-single-product.php
flatsome/woocommerce/content-widget-product.php
flatsome/woocommerce/global/breadcrumb.php
flatsome/woocommerce/global/quantity-input.php
flatsome/woocommerce/global/wrapper-end.php
flatsome/woocommerce/global/wrapper-start.php
flatsome/woocommerce/loop/loop-end.php
flatsome/woocommerce/loop/loop-start.php
flatsome/woocommerce/loop/pagination.php
flatsome/woocommerce/loop/result-count.php
flatsome/woocommerce/loop/sale-flash.php
flatsome/woocommerce/myaccount/form-login.php
flatsome/woocommerce/myaccount/navigation.php
flatsome/woocommerce/notices/error.php
flatsome/woocommerce/notices/notice.php
flatsome/woocommerce/notices/success.php
flatsome/woocommerce/product-searchform.php
flatsome/woocommerce/single-product/photoswipe.php
flatsome/woocommerce/single-product/price.php
flatsome/woocommerce/single-product/product-image.php
flatsome/woocommerce/single-product/product-thumbnails.php
flatsome/woocommerce/single-product/rating.php
flatsome/woocommerce/single-product/related.php
flatsome/woocommerce/single-product/review.php
flatsome/woocommerce/single-product/sale-flash.php
flatsome/woocommerce/single-product/share.php
flatsome/woocommerce/single-product/short-description.php
flatsome/woocommerce/single-product/tabs/tabs.php
flatsome/woocommerce/single-product/title.php
flatsome/woocommerce/single-product/up-sells.php
flatsome/woocommerce/single-product-reviews.php
flatsome/woocommerce/single-product.php

### Product Bundles ###

Database Version: 6.3.3
Loopback Test: ❌ Loopback test failed.
Template Overrides: –

### Action Scheduler ###

Complete: 2,132
Oldest: 2020-07-20 16:17:44 +0300
Newest: 2020-08-20 13:53:48 +0300

Failed: 10
Oldest: 2019-05-30 09:09:52 +0300
Newest: 2020-03-27 22:20:38 +0300

Pending: 3
Oldest: 2020-08-21 04:21:09 +0300
Newest: 2020-08-21 13:59:37 +0300

### WooCommerce Zapier ###

Database Version: ✔ 12
Detailed Logging Enabled: No
Legacy Mode Disabled: ❌ No
SSL: ✔ Yes
REST API Authentication Key(s): ❌ 0
Task History Record Count: ❌ 0
Legacy Cron Tasks: ✔ 0
Active Legacy Feeds: ❌ 2 active Legacy Feed(s) need to be migrated before 30/04/2021. Migrate Your Zaps Now
Legacy Feed #1: WooCommerce new order to Pipedrive
- Trigger: New Order
- Webhook URL: https://hooks.zapier.com/hooks/catch/1820158/az4tnv/
Legacy Feed #2: WooCommerce new person to Pipedrive
- Trigger: New Order
- Webhook URL: https://hooks.zapier.com/hooks/catch/1820158/w3lvd2/
`
</details>

### PR DESCRIPTION
**Pull request by roykho**
### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Ref: p7bje6-2HA-p2

Closes #27424

### How to test the changes in this Pull Request:
 **UPDATE:**
This PR no longer requires anything from WC Admin.

1. Trigger a WooCommerce Database Update Required notice. One way to do this is set your database version to an older version than what is installed. For example got to `wp_options` table search for `woocommerce_db_version` and set it to `4.4.0`.
2. Ensure you're able to click on the `Update WooCommerce database` button without errors and you're able to see the process started to run.
3. After it is done, you should see another banner/notice `WooCommerce database update done`. When you see this open another browser or incognito mode and login as the same admin user so you have two concurrent sessions going.
4. For the second user navigate to WooCommerce->Home. Ensure you also see the same banner/notice `WooCommerce database update done`.
5. Go back to your first user session and now click on the `Thanks!` dismissal button.
6. Ensure the banner goes away after clicking. If it doesn't work the first time, try one more time after refresh and it should now go away. You shouldn't have to reload the page more than twice for it to go away.
7. Navigate to other WooCommerce pages and ensure that banner/notice does not reappear anywhere in either sessions.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Fix - Admin notices sometimes were persisting even after dismissing.

### CODE REVIEW

**Comment by Konamiman** [comment]
I tried the test steps but when I click the "Update WooCommerce database" button I get a "The link you followed has expired" error... am I doing something wrong?

**Comment by roykho** [comment]
@Konamiman - are you triggering a new notice? As in this is not a notice that was already in the database unactioned before this PR?

**Comment by Konamiman** [comment]
@roykho Yes, I'm following the testing steps from the PR description: manually modify the db version in the options table, then load the admin page in the site and click "Update database", that's all.

**Comment by roykho** [comment]
@Konamiman - I know you're following the steps however since I can't see, I have to make sure on a few keys steps. Have you have WC Admin activated as separate plugin and checked out this PR woocommerce/woocommerce-admin#5827 ?

**Comment by Konamiman** [comment]
Sorry, totally my fault, I hadn't seen that prerrequisite line 🤦🏻‍♂️ 

I've now been able to trigger the db update, however after it finishes and I click "Thanks" I get the "expired link" error again. Same if I retry, and the third time the banner has disappeared (including the banner in the other session).

**Comment by roykho** [comment]
Hmmm I've not seen the "expired link" error in my testing. Only that sometimes the banner doesn't disappear right away on first click and that is normal. But it should definitely disappear after second click after a page refresh.

**Comment by roykho** [comment]
Hey @jonathansadowski - sorry to wrangle you in here but I need a second tester to see if y'all are both having the issues testing this PR as described by @Konamiman Thanks!

**Comment by jonathansadowski** [comment]
@roykho I'm having the same issue as @Konamiman 


When I try and dismiss this notice:

image

I see this error:

image

Clicking on "please try again" displays the notice again.

Clicking on the notice dismissal shows "please try again" again.

Clicking on it the last time does dismiss the notice.

**Comment by roykho** [comment]
@jonathansadowski - Thanks for testing. Would you happen to know the URL link to the dismissal button? I want to see if it is formatted correctly.

**Comment by jonathansadowski** [comment]
> Thanks for testing. Would you happen to know the URL link to the dismissal button? I want to see if it is formatted correctly.

@roykho, sorry for the delay in responding.

After I load the dashboard in the incognito window, the link in the main window is to: `/wp-admin/admin.php?page=wc-admin&do_update_woocommerce=true&wc-hide-notice=update&_wc_notice_nonce=A`

The error message's try again link is: `/wp-admin/admin.php?page=wc-admin&do_update_woocommerce=true&wc_db_update_nonce=B`  (with a different nonce than before)

When I see the dialog again after the try again link fails, that button's nonce is again `/wp-admin/admin.php?page=wc-admin&do_update_woocommerce=true&wc-hide-notice=update&_wc_notice_nonce=A` (with the same nonce as the dialog before, but different than the try again link)

The error message that the link has expired again links to: `/wp-admin/admin.php?page=wc-admin&do_update_woocommerce=true&wc_db_update_nonce=B` (same nonce as the previous try-again link)

Finally, the link in the incognito window (which I didn't click) is: `/wp-admin/admin.php?page=wc-admin&wc-hide-notice=update&_wc_notice_nonce=C`  (with a different nonce than any of the previous)

**Comment by roykho** [comment]
Ok I think I found the culprit. The query arg `do_update_woocommerce` sometimes persists in the query when you stay on the same page and just clicked refresh to get the "Thanks for updating" notice to show. In my testing, I clicked away from that page hence that query arg isn't there and hence I couldn't reproduce the issue y'all are seeing. So I pushed up a change to remove this query arg when showing the "Thanks for updating" notice.

Could y'all please go this another go? @Konamiman @jonathansadowski

**Comment by jonathansadowski** [comment]
I ran into an interesting issue while testing this. I'm a bit puzzled as to how it could be related to this PR, but let me describe how I've been able to reproduce it:

1) Started with a brand-new WordPress site with this branch checked out, built, and activated. I skipped the on-boarding wizard.
2) Built and activated the branch from https://github.com/woocommerce/woocommerce-admin/pull/5827.
3) Went to WooCommerce dashboard (where I left the task list was entirely uncompleted).
4) Open the network inspector and have it monitoring requests.
5) Updated the `woocommerce_db_version` option to `4.4.0` as described in the original test plan. I used `wp option update woocommerce_db_version 4.4.0`.
6) Reloaded the page, and clicked on `Update WooCommerce database`.
7) Reload the page after the update starts. Afterward, I noticed hundreds of requests in the network inspector — they appear to be trying to update the task list. None of them had a response.
image

Switching from this branch to master (and reloading the Dashboard), back to this branch seemed to resolve the issue for me.

I repeated the above steps, again starting on a brand new site, except on the `master` branch of WC / `main` branch of WCA, and wasn't able to reproduce the same issue. 

Not sure of this is some symptom of how I'm testing this, or some weird obscure thing, so I figure I'd drop it here with the steps I used to recreate it. @Konamiman, could you see if you're able to reproduce the issue I ran into?

**Comment by Konamiman** [comment]
Hi @roykho, after your update it seems to work as expected for me (I had to reload a couple of times for the notice to disappear but that's expected according to your description). I'll now check what @jonathansadowski has found.

**Comment by Konamiman** [comment]
Hi @jonathansadowski, I haven't been able to reproduce the hundreds of network requests issue locally.

**Review by Konamiman — DISMISSED** [review]
I'm approving since the main issue addressed by the PR seems to be fixed. If what @jonathansadowski found rutns out to be a real issue I think it could be addressed in a separate PR.

**Comment by roykho** [comment]
Hi @Konamiman - thanks for testing and approving. Could you please also approve this one here that is linked https://github.com/woocommerce/woocommerce-admin/pull/5827

**Comment by jonathansadowski** [comment]
I'm a little concerned because of the nature of the issue I ran into, but if it doesn't worry you, and nobody else can reproduce it, I'm happy to create a new issue if I still run into it after this is merged.

**Comment by roykho** [comment]
Hi @jonathansadowski @Konamiman - sorry to rope y'all in on this again. So after speaking with Isotope, we found a suitable hook to use from WC Admin to achieve the same results. This means we don't  need to make any changes over on WC Admin side. So basically I just ported the code I've added from there to here. It works the same way as before. Could y'all please review again?

**Review by jonathansadowski — DISMISSED** [review]
This is working for me... plus, the issue that I was experiencing before with the repeating requests isn't happening with this update. Nice work. 👍

File: includes/admin/class-wc-admin-notices.php [hunk 1]
```diff
@@ -64,6 +64,52 @@ public static function init() {
...
+				$url = $url_parts['scheme'] . '://' . $url_parts['host'] . $url_parts['path'];
+
+				$parsed_query = wp_nonce_url(
+					add_query_arg(
+						$_params,
+						$url
+					),
+					$params['_nonce_action'],
+					$params['_nonce_name']
+				);
```
Comment (xknown) [inline includes/admin/class-wc-admin-notices.php:103]: Maybe we can just use use directly `add_query_arg()` instead of relying in `wp_nonce_url`, especially if later we end up calling `html_entity_decode`
```
$parsed_query = $parsed_query = add_query_arg(
					$params['_nonce_action'],
					wp_create_nonce( $params['_nonce_name'] ),
					add_query_arg(
						$_params,
						$url
					)
				);
```

To avoid potential security issues, we need to restrict what sort of values are allowed for `$params['_nonce_action']`, not sure if there's some sort of prefix we can enforce. Otherwise, this endpoint can be used to generate some other nonces not really related to this feature.

**Review by xknown — CHANGES_REQUESTED** [review]

File: includes/admin/class-wc-admin-notices.php [hunk 2]
```diff
@@ -64,6 +64,51 @@ public static function init() {
...
+				unset( $org_params['_nonce_name'] );
+
+				$url = $url_parts['scheme'] . '://' . $url_parts['host'] . $url_parts['path'];
+
+				$nonce         = array( $params['_nonce_name'] => wp_create_nonce( $params['_nonce_action'] ) );
+				$merged_params = array_merge( $nonce, $org_params );
+				$parsed_query  = add_query_arg( $merged_params, $url );
+
+				$response->data['actions'][ $action_key ]->query = html_entity_decode( $parsed_query );
+				$response->data['actions'][ $action_key ]->url   = html_entity_decode( $parsed_query );
```
Comment (xknown) [inline includes/admin/class-wc-admin-notices.php:105]: Is `html_entity_decode` still needed? If so, I assume the code that consumes these potentially unsafe urls are able to handle it properly?

Comment (roykho) [reply includes/admin/class-wc-admin-notices.php:105]: Good catch.No it is not needed anymore. This was actually leftover code when I had to port this from my original implementation which needed it. Removing now.

File: includes/admin/class-wc-admin-notices.php (hunk 1 above)
Comment (roykho) [reply includes/admin/class-wc-admin-notices.php]: Thanks for looking @xknown - so we do have a check here https://github.com/woocommerce/woocommerce/pull/28500/files#diff-16f554e0b9034833e30aa59fb984c8a67a1faadb5c9bc511db4e9e716c5556f5R74 that ensures we're taking action only on known items. But regardless I've pushed up changes to specifically whitelist the nonce action names.

**Review by xknown — APPROVED** [review]
Thanks for addressing the feedback. The changes look fine, although I didn't really test the whole workflow.

**Review by claudiosanches — APPROVED** [review]
Works great!
