### PR TITLE
Fix for issue #21395

### LINKED ISSUE #21395: Help Tooltip issue on Product category page.
When we disable Image option from Screen Options help tooltip removed for "Uncategorized" category.

1) Admin Panel > Products > Categories > Screen Options at top right > Image( uncheck )

working_without_issue
issue

### PR DESCRIPTION
**Pull request by khanrn**
### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:
First we need to understand why this issue was happening. Actually we are [adding the tooltip to the **Image** AKA `thumb` column](https://github.com/woocommerce/woocommerce/blob/0566708744e109c6b50e630f8099a4735eac33a9/includes/admin/class-wc-admin-taxonomies.php#L406) data and unchecking the **Image** checkbox hides the **Image** column. So when the **Image** column gets hidden the tooltip gets hidden as well.

Now we can fix this by adding the tooltip to the `cb` AKA **checkbox** column. But unfortunately [`columns_cb()` method or `cb` or **checkbox** column data is immutable with *PHP*](https://github.com/WordPress/WordPress/blob/56c162fbc9867f923862f64f1b4570d885f1ff03/wp-admin/includes/class-wp-terms-list-table.php#L344). ( also [see this](https://github.com/WordPress/WordPress/blob/2e8c823212d7c5b87e607cab6b53d070358ff3ee/wp-admin/includes/class-wp-list-table.php#L1313) )

I also tried to manipulate the data of the `cb` or **checkbox** column otherwise, but no luck. So two options were there-
1. Use custom list table for the `product_cat` taxonomy.
2. Use *jQuery* to manipulate the *DOM* and move the tooltip to the `cb` or **checkbox** column.

The first option will need a complete refactor for the WooCommerce taxonomy rendering system as well as API and I think it's not worth doing a complete refactor for a positional fix of a tooltip only. So, I have chosen the second option, *jQuery*.

> N.B. : Some other refactor is also needed for this `WC_Admin_Taxonomies` class like for WPCS errors and some other. I'm willing to do it, but need feedback on this issue first.

Closes #21395.

### How to test the changes in this Pull Request:

1. Go to **Admin Panel > Products > Categories**
2. Click on **Screen Options** at top right
3. Uncheck the **Image** checkbox.
4. **The tooltip isn't vanishing**.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

### Changelog entry

- `scripts_at_product_cat_screen_footer` method introduced in `class-wc-admin-taxonomies.php` class and it's hooked to `admin_footer` for adding some scripts to the footer of the `product_cat` admin screen.

### CODE REVIEW

File: includes/admin/class-wc-admin-taxonomies.php [hunk 1]
```diff
@@ -436,6 +449,25 @@ public function disable_checked_ontop( $args ) {
...
+	 * @return void
+	 */
+	public function scripts_at_product_cat_screen_footer() {
+		if ( ! isset( $_GET['taxonomy'] ) || 'product_cat' !== $_GET['taxonomy'] ) { // WPCS: ok
+			return;
+		}
+		wc_enqueue_js("
+			(function( $ ) {
+				'use strict';
+				var product_cat = $('tr#tag-" . $this->default_cat_id . "');
```
Comment (claudiulodro) [inline includes/admin/class-wc-admin-taxonomies.php]: This needs some sanitizing before being output. Since it's an ID, I recommend `absint`.

The JS code style should also have spaces between the function parentheses (e.g. `( 'th' )`).

It would also be good to have a comment near this function or in the docblock saying what exactly this script will do ("Ensure the tooltip is displayed when the image column is disabled on product categories"). Otherwise nobody will remember what this bit of script is for. :)

**Review by claudiulodro — CHANGES_REQUESTED** [review]
Thanks for the contribution @rnaby! This approach looks good. A couple small changes then this is good to merge.

File: includes/admin/class-wc-admin-taxonomies.php [hunk 2]
```diff
@@ -436,6 +449,25 @@ public function disable_checked_ontop( $args ) {
...
 		return $args;
 	}
+
+	/**
+	 * Admin footer scripts for the product categories admin screen
+	 *
+	 * @return void
+	 */
+	public function scripts_at_product_cat_screen_footer() {
+		if ( ! isset( $_GET['taxonomy'] ) || 'product_cat' !== $_GET['taxonomy'] ) { // WPCS: ok
```
Comment (claudiulodro) [inline includes/admin/class-wc-admin-taxonomies.php]: I don't believe `WPCS: ok` is a recognized tag. This doesn't look like it should cause issues in WPCS so you can probably just remove the comment.

**Comment by kloon** [comment]
@rnaby just checking that you saw Claudiu's comments? If you can get those fixed then we can get this PR merged.

**Comment by rnaby** [comment]
@kloon and @claudiulodro I've fixed the PR as you suggested. Please have a look.

**Comment by claudiulodro** [comment]
Looks good. Thanks for making the revisions and thanks for the contribution!

**Review by claudiulodro — APPROVED** [review]
