### PR TITLE
Product Editor: Add keyboard shortcuts for undo/redo to modal block editor

### LINKED ISSUE #47188: Product Editor: Undo/redo keyboard shortcuts don't work in description modal editor
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

The keyboard shortcuts for undo and redo (CMD+Z and CMD+SHIFT+Z on macOS) do not work in the description modal block editor.

Found during testing of #47123

### Expected behavior

The keyboard shortcuts for undo and redo should work

### Actual behavior

The keyboard shortcuts for undo and redo should work

### Steps to reproduce

With a WooCommerce dev env with the new product editor enabled (**WooCommerce** > **Settings** > **Advanced** > **Features** > **Experimental features**) and the test plugin above installed...

1. Go to **Products** > **Add New**
2. Click in the **Description** field and then click the **Full Editor** button to bring up the modal editor
3. Type some content in the modal editor
4. Verify that the undo/redo keyboard shortcuts do nothing

### WordPress Environment

n/a

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by mattsherman**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

This PR adds the following keyboard shortcuts to the new product editor's modal block editor:

* Undo: `⌘Z`
* Redo: `⇧⌘Z`
* Document overview: `⌃⌥O`
* Settings sidebar: `⇧⌘,`

Known issues that will be addressed in follow up PRs:

- https://github.com/woocommerce/woocommerce/issues/47508

Closes #47188.

### How to test the changes in this Pull Request:

With a WooCommerce env with the new product editor enabled (**WooCommerce** > **Settings** > **Advanced** > **Features** > **Experimental features**)...

1. Go to **Products** > **Add New**
2. Click on **Description** > **Full Editor** to bring up the modal editor
3. Type some text
4. Verify the above listed keyboard shortcuts function as expected

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Comment 

</details>

### CODE REVIEW

File: packages/js/product-editor/src/components/iframe-editor/keyboard-shortcuts/keyboard-shortcuts.tsx [hunk 1]
```diff
@@ -0,0 +1,85 @@
...
+/**
+ * Internal dependencies
+ */
+import { EditorContext } from '../context';
+import {
+	SETTINGS_SIDEBAR_IDENTIFIER,
+	SIDEBAR_COMPLEMENTARY_AREA_SCOPE,
+} from '../constants';
+
+export const KeyboardShortcuts = () => {
```
Comment (octaedro) [inline packages/js/product-editor/src/components/iframe-editor/keyboard-shortcuts/keyboard-shortcuts.tsx:21]: Same [as `RegisterKeyboardShortcuts`](https://github.com/woocommerce/woocommerce/pull/47488/files#r1602145979), I would transform this into a hook.

File: packages/js/product-editor/src/components/iframe-editor/keyboard-shortcuts/register-keyboard-shortcuts.tsx [hunk 2]
```diff
@@ -0,0 +1,75 @@
...
+ */
+import { useEffect } from '@wordpress/element';
+import { useDispatch } from '@wordpress/data';
+import { __ } from '@wordpress/i18n';
+import { store as keyboardShortcutsStore } from '@wordpress/keyboard-shortcuts';
+// @ts-expect-error missing types.
+// eslint-disable-next-line @woocommerce/dependency-group
+import { isAppleOS } from '@wordpress/keycodes';
+
+export const RegisterKeyboardShortcuts = () => {
```
Comment (octaedro) [inline packages/js/product-editor/src/components/iframe-editor/keyboard-shortcuts/register-keyboard-shortcuts.tsx:12]: Can we transform this into a hook? Since it's not rendering anything and is only executing a side effect, it would make more sense to handle this code as a hook rather than as a normal component.

**Review by octaedro — COMMENTED** [review]
Nice job @mattsherman! This is testing well on my end and the code looks mostly good. I just left a couple of comments. I think that after addressing those suggestions this PR will be good to go.

File: packages/js/product-editor/src/components/iframe-editor/keyboard-shortcuts/keyboard-shortcuts.tsx (hunk 1 above)
Comment (mattsherman) [reply packages/js/product-editor/src/components/iframe-editor/keyboard-shortcuts/keyboard-shortcuts.tsx:21]: I thought the same thing. But, this needs to be under the `<BlockEditorProvider>`, so that it is in the right context. I could create a wrapper component that used the hook under there, but that wrapper component would also render nothing other than its children.

This is how Gutenberg handles this in its editors.

File: packages/js/product-editor/src/components/iframe-editor/keyboard-shortcuts/register-keyboard-shortcuts.tsx (hunk 2 above)
Comment (mattsherman) [reply packages/js/product-editor/src/components/iframe-editor/keyboard-shortcuts/register-keyboard-shortcuts.tsx:12]: I thought the same thing. But, this needs to be under the `<BlockEditorProvider>`, so that it is in the right context. I could create a wrapper component that used the hook under there, but that wrapper component would also render nothing other than its children.

This is how Gutenberg handles this in its editors.

**Comment by mattsherman** [comment]
Thanks for the review @octaedro! I too initially thought these could/should be hooks, but there is no component that the hooks would be used by in the right context. I followed the same approach that Gutenberg core did.

File: packages/js/product-editor/src/components/iframe-editor/keyboard-shortcuts/register-keyboard-shortcuts.tsx (hunk 2 above)
Comment (octaedro) [reply packages/js/product-editor/src/components/iframe-editor/keyboard-shortcuts/register-keyboard-shortcuts.tsx:12]: I usually prefer using a HOC over a component that doesn't render anything (functional component), but given that we use that pattern sporadically, it's good as it is.

**Review by octaedro — APPROVED** [review]
Good job @mattsherman! The functional component works well here. I’m approving this PR.
