### PR TITLE
Accessibility: Prevent shipping losing focus when making selections during checkout

### LINKED ISSUE #48104: Focus is lost on shipping selection after toggling between available and disabled.
Currently, we only disable radio inputs when making network requests, this causes focus to be lost when making a network request, for example selecting a shipping rate. Focus should be retained on that element.

It appears that there is no definitive decision around this, check this Gutenberg issue about that https://github.com/WordPress/gutenberg/issues/56547

Given that, I think we should retain focus on our disabled radio inputs, unless we know for sure other cases in which a radio input will stay visible but disabled.

### Steps to reproduces

1. Have at least 2 rates.
2. On Checkout, click the first shipping element.
3. Using keyboard, select the second option.
4. Wait until network request is done.
5. Click arrow up, notice that the page scrolls up instead of selecting the top element.

### Expexted behavior

Focus should be retained and narrowing up should select the previous element.

### PR DESCRIPTION
**Pull request by mikejolley**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

This PR prevents focus being lost on the radio inputs in the shipping component of the block based checkout. To do this we need to change `disabled` to `aria-disabled` so focus can be left in place.

A side effect of this is that you can still select options while the selected option is being pushed to the server. This can cause the UI to update unexpectedly as you toggle options too quickly. I've mitigated this by:

1. Disabling keyboard (arrow key) navigation between items when `aria-disabled` is true. This means you must wait for the option to propagate to server before switching options again. You can still tab out of the component if you wish.
2. Implementing request cancelling for the select shipping event. This is so when you use the mouse to toggle options, requests do not keep stacking on top of each other.

Additionally, I found and removed a rogue `useEffect` which was causing two requests each time you choose a shipping option. The request is made `onChange` so the `useEffect` was not needed.

Closes #48104

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Go to WooCommerce > Settings > Shipping and ensure you have several shipping rates setup. For testing purposes 3 or 4 is a good amount. 
4. Add an item to your cart and go to checkout (block based checkout).
5. Click on a shipping option.
6. Keyboard navigation test
     - Press the down and up keys to navigate between shipping options
     - When a new option is selected it should fade and keyboard navigation should be prevented
     - Once the option s updated, navigation is restored
     - You should be able to tab out of the area at any point
7. Mouse test 
     - Click on shipping options
     - Click around while they are loading. There should be no errors, and your last selection should propagate to the server.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

Accessibility: Prevent shipping losing focus when making selections during checkout.

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

**Comment by mikejolley** [comment]
Pining @senadir to review the cancelling part. I didn't go with the full implementation in his recent PR.

**Review by nielslange — APPROVED** [review]
Thanks for working on this, @mikejolley. I've successfully tested this PR and could not spot anything issues with the code. However, let's wait for @senadir's review as requested in https://github.com/woocommerce/woocommerce/pull/48370#issuecomment-2160478965, before merging this PR.

**Review by senadir — APPROVED** [review]
Looks really good! As I see it, I saw a flaw in my original request cancel approach, but yours doesn't have issue, so we're good to do.


The issue with my original approach is that I didn't take request params into account, not sure which ones to take to begin with.

File: plugins/woocommerce-blocks/assets/js/base/components/cart-checkout/shipping-rates-control-package/package-rates.tsx [hunk 1]
```diff
@@ -68,13 +68,6 @@ const PackageRates = ( {
 		}
 	}, [ onSelectRate, rates, selectedOption ] );
 
-	// Update the data store when the local selected rate changes.
-	useEffect( () => {
-		if ( selectedOption ) {
-			onSelectRate( selectedOption );
-		}
-	}, [ onSelectRate, selectedOption ] );
-
```
Comment (senadir) [inline plugins/woocommerce-blocks/assets/js/base/components/cart-checkout/shipping-rates-control-package/package-rates.tsx:77]: I feel this change should have been bigger, why didn't we remove the `onSelectRate` and go up even further?

Comment (mikejolley) [reply plugins/woocommerce-blocks/assets/js/base/components/cart-checkout/shipping-rates-control-package/package-rates.tsx:77]: What do you mean bigger? There was a duplicate update (this caused 2 requests instead of 1, so for this PR, immediate cancel and retry).
