### PR TITLE
[CYS] Fix the failed to load resource error in the CYS whenever the current active theme is not TT4 

### LINKED ISSUE #45479: [CYS on Core] Fix the failed to load resource error in the CYS whenever the current active theme is not TT4
**Issue Description:**

Whenever you access the CYS flow for the very first time and your current active theme is not TT4, it is possible for the following error to come up when clicking on "Start designing" > "Design a new theme" modal:

`Failed to load resource: the server responded with a status of 404 ()` 

The resource that is failing to load is:

`wp-json/wp/v2/global-styles?context=edit&_locale=user`

## Steps to reproduce

1. Make sure you have the WooCommerce Beta Tester plugin installed and activated
2. Under Tools > WCA Test Helper > Features, make sure `customize-store` is enabled
3. Under Tools > WCA Test Helper > Tools, click on `Reset Customize Your Store`
4. Make sure your current active theme is TT1
5. Head over to WooCommerce > Home > Customize your store
6. Click on "Start designing" and then on "Design a new theme" when the modal opens
7. See the following error:

Screenshot 2024-03-11 at 13 20 15

### PR DESCRIPTION
**Pull request by albarin**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes https://github.com/woocommerce/woocommerce/issues/45479

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Ensure the `WooCommerce Beta Tester` plugin is installed and activated (available on this monorepo).
2. Head over to `/wp-admin/tools.php?page=woocommerce-admin-test-helper` and enable `customize-store` feature flag.
3. Click on `Tools` and run the `Reset Customize Your Store` and the `Delete all products` commands.
5. Enable the TT1 theme.
6. Go to `wp-admin/admin.php?page=wc-admin&path=%2Fcustomize-store`.
7. Open the inspector.
8. Click on `Start designing`.
9. Make sure you see the following modal:
Screenshot 2024-03-13 at 16 52 20

10. Click on `Design a new theme`.
11. Check there's no 404 error in the inspector and the flow finishes and it loads the assembler (this is the [error](https://github.com/woocommerce/woocommerce/issues/45479) this PR is trying to fix, it should not happen anymore).
13. Go to `wp-admin/themes.php` and make sure the active theme is TT4.

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [x] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 
CYS - Fix the failed to load resource error in the CYS whenever the current active theme is not TT4
#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce-admin/client/customize-store/design-without-ai/services.ts [hunk 1]
```diff
@@ -155,6 +158,28 @@ const createProducts = async () => {
...
+	const activeThemes = await resolveSelect( 'core' ).getEntityRecords(
+		'root',
+		'theme',
+		{ status: 'active' },
+		true
+	);
+
+	// @ts-expect-error
+	if ( ! activeThemes.length ) {
+		return null;
```
Comment (nefeline) [inline plugins/woocommerce-admin/client/customize-store/design-without-ai/services.ts]: @albarin I think this might be the culprit for the issues I've been occasionally experiencing whenever testing this PR: could we ensure that we attempt to fetch the activeThemes again at this point instead of returning null?

Comment (nefeline) [reply plugins/woocommerce-admin/client/customize-store/design-without-ai/services.ts]: FU Question: could we implement a fallback here to ensure that whenever `activeThemes` fails for some reason, we have a backup plan? Ideally users should not be blocked from proceeding to the assembler due to a lack of `globalStylesObject.id`

**Review by nefeline — APPROVED** [review]
Excellent work here @albarin, this was a very complex problem with a lot of nuances to it and you did an exceptional work on handling all possible scenarios of failure.

🚀
