### PR TITLE
[Accessibility] Add address title to edit/add buttons on My Account page

### LINKED ISSUE #43631: Accessibility: Edit links on My Account Addresses page ambiguous
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

The edit links for the billing and shipping addresses on the My Account Address page are ambiguous and don't specify which address you'll be editing. They both just have an anchor that says "Edit" and no aria-label.

https://github.com/woocommerce/woocommerce/blob/758df4854d7b627fc26eb5c0860dc492dea6a06e/plugins/woocommerce/templates/myaccount/my-address.php#L63

### Expected behavior

Links should make it clear what their purpose is. The links should have an aria-label that adds the address title to add meaning for screen reader users.

Example:
`<a href="https://shop.equalizedigital.com/my-account/edit-address/billing/" class="edit" aria-label="Edit billing address">Edit</a>`

### Actual behavior

The links are identical, though they do different things.

### Steps to reproduce

See code linked above.

### WordPress Environment

N/A

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by Manussakis**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes #43631 .

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. On the frontend, go to My Account -> Addresses page
2. Turn on the screen reader.
3. Focus on the edit billing address button.
image
4. Verify the screen reader announces "Edit Billing address".
5. Focus on the add shipping address button.
image
6. Verify the screen reader announces "Add Shipping address".

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [x] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

**Comment by Manussakis** [comment]
@dkotter This task is ready for code review.

**Review by naman03malhotra — COMMENTED** [review]
Hey @Manussakis, this PR is marked in draft mode, is it ready for review yet?

**Comment by Manussakis** [comment]
> Hey @Manussakis, this PR is marked in draft mode, is it ready for review yet?

Hey @naman03malhotra ! Yes, it's ready for review. However, I am not supposed to remove it out of Draft until it has gone through the 10up internal review.

**Review by dkotter — APPROVED** [review]
@ankitguptaindia @qasumitbagthariya This is ready for QA

File: plugins/woocommerce/templates/myaccount/my-address.php [hunk 1]
```diff
@@ -60,7 +60,7 @@
 	<div class="u-column<?php echo $col < 0 ? 1 : 2; ?> col-<?php echo $oldcol < 0 ? 1 : 2; ?> woocommerce-Address">
 		<header class="woocommerce-Address-title title">
 			<h3><?php echo esc_html( $address_title ); ?></h3>
-			<a href="<?php echo esc_url( wc_get_endpoint_url( 'edit-address', $name ) ); ?>" class="edit"><?php echo $address ? esc_html__( 'Edit', 'woocommerce' ) : esc_html__( 'Add', 'woocommerce' ); ?></a>
+			<a href="<?php echo esc_url( wc_get_endpoint_url( 'edit-address', $name ) ); ?>" class="edit"><?php echo $address ? esc_html__( 'Edit', 'woocommerce' ) : esc_html__( 'Add', 'woocommerce' ); ?> <?php echo esc_html( $address_title ); ?></a>
```
Comment (naman03malhotra) [inline plugins/woocommerce/templates/myaccount/my-address.php]: Ideally, we should have used `aria-label` to enhance the accessibility and description, but the text here is hidden using the `:before` pseudo-element in CSS, so that should be fine.

Works well, looks good to me.

image

**Review by naman03malhotra — APPROVED** [review]
Works well, thanks for working on it!

**Comment by qasumitbagthariya** [comment]
QA Report ⚠️ 
---

@Manussakis Thanks for the PR.

When using VoiceOver on both the Mac default VoiceOver and a Chrome extension, hovering over edit buttons incorrectly announces them as "visited link edit" instead of identifying them as "Edit Billing address' and "Add Shipping address"

**Comment by Manussakis** [comment]
> ## QA Report ⚠️
> @Manussakis Thanks for the PR.
> 
> When using VoiceOver on both the Mac default VoiceOver and a Chrome extension, hovering over edit buttons incorrectly announces them as "visited link edit" instead of identifying them as "Edit Billing address' and "Add Shipping address"

@qasumitbagthariya Thanks for testing it.
I was not able to reproduce the issue you flagged. Just to confirm, have you pulled and built the correct branch?
I am asking because the issue you encountered is exactly the one without the changes implemented by this PR 🤔 

If you still face the problem, could you please provide me with a video so I can get more context?

File: plugins/woocommerce/templates/myaccount/my-address.php (hunk 1 above)
Comment (mikejolley) [inline plugins/woocommerce/templates/myaccount/my-address.php]: I would recommend using placeholders in the translation string so the words can be reordered if needed e.g. `Edit %s`, using sprintf to inject $address_title.

Comment (Manussakis) [reply plugins/woocommerce/templates/myaccount/my-address.php]: @mikejolley Thanks for the feedback. Please review this commit: [Use placeholder in the edit/add address translation](https://github.com/woocommerce/woocommerce/pull/49171/commits/b2b64ed3c30912fcce7df0796a402bb73397fc11)

**Comment by qasumitbagthariya** [comment]
### QA Update ✅
-------------

**Testing Environment** 

<Details>

- WordPress: 6.6
- Theme: Storefront 4.6.0
- WooCommerce - WooCommerce - Dev version with this fix specific branch.
- PHP: 8.0.30
- Web Server: Nginx 1.20.2
- Browser: Chrome 
- OS: macOS Ventura 13.3 
- Git Branch: Manussakis:fix/43631

</Details>

Changes work as expected. ✅

Tested Cases with Classic and Block Checkout:

- Focus on the edit billing address button. ✅
- Focus on the add shipping address button. ✅

*Functional Demo / Screencast -

https://github.com/user-attachments/assets/db814e02-a18f-4b59-8b67-ef4da8e949b8

**Review by mikejolley — APPROVED** [review]

**Review by mikejolley — APPROVED** [review]
Just needs:

- Marking ready for review (this is a draft)
- Rebasing/updated from trunk 
- Passing CI

But pre-approving.

**Comment by vikrampm1** [comment]
@mikejolley this PR is ready to be merged by Woo.
