### PR TITLE
Prevent saved changes message when leaving page closes #29359

### LINKED ISSUE #29359: Shipping Zone - Save changes button is disabled but unsaved warning is still shown when navigating out after adding a method.
Please provide us with the information requested in this bug report. Without these details, we won't be able to fully evaluate this issue. 
Bug reports lacking detail, or for any other reason than to report a bug, may be closed without action.

**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**

After adding a new shipping zone, the zone is autosaved, but trying to leave the page you get a warning:

**Image Link**: https://d.pr/i/iri3h0+

The Save Change button is disabled since it's already saved, but I get this warning.

**Expected behavior**
It should just switch page without warning me.

**Actual behavior**
It asks confirmation as something might not be saved.

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Go to WooCommerce > Settings > Shipping > Shipping zones
2. Add a new zone
3. Add shipping methods to it
4. Try to leave to see the error

**Screenshots**

**Image Link**: https://d.pr/i/iri3h0+

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report we won't be able to fully evaluate this issue.
<details>
```
### WordPress Environment ###

WordPress address (URL): https://support.local
Site address (URL): https://support.local
WC Version: 5.1.0
REST API Version: ✔ 5.1.0
WC Blocks Version: ✔ 4.4.3
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 2.0.2
Log Directory Writable: ✔
WP Version: 5.7
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.16.0
PHP Version: 7.4.1
PHP Post Max Size: 1,000 MB
PHP Time Limit: 1200
PHP Max Input Vars: 4000
cURL Version: 7.54.0
LibreSSL/2.6.5

SUHOSIN Installed: –
MySQL Version: 8.0.16
Max Upload Size: 300 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 5.1.0
WC Database Prefix: wp_
Total Database Size: 15.76MB
Database Data Size: 12.16MB
Database Index Size: 3.60MB
wp_woocommerce_sessions: Data: 0.14MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.11MB + Index: 0.09MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.17MB + Index: 0.14MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.09MB + Index: 0.09MB + Engine InnoDB
wp_afwc_campaigns: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_afwc_hits: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_afwc_payout_orders: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_afwc_payouts: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_afwc_referrals: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_automatewoo_abandoned_carts: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_automatewoo_customer_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_customers: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_automatewoo_events: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_guest_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_guests: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_automatewoo_log_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_queue: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_queue_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_referral_advocate_keys: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_automatewoo_referral_invites: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_referrals: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.06MB + Index: 0.09MB + Engine InnoDB
wp_email_log: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
wp_followup_coupon_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_coupons: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_customer_carts: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_customer_notes: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_customer_orders: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_followup_customers: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_followup_email_excludes: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_email_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_email_orders: Data: 0.09MB + Index: 0.09MB + Engine InnoDB
wp_followup_email_tracking: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_followup_followup_history: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_order_categories: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_order_items: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_subscriber_lists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_subscribers: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_subscribers_to_lists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 8.03MB + Index: 0.08MB + Engine InnoDB
wp_postmeta: Data: 0.25MB + Index: 0.30MB + Engine InnoDB
wp_posts: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_booking_relationships: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_bookings_availability: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_bookings_availabilitymeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_deposits_payment_plans: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_deposits_payment_plans_schedule: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_points_rewards_user_points: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_points_rewards_user_points_log: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wcpv_commissions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcpv_per_product_shipping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_bundled_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_bundled_items: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_exported_csv_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_shipping_table_rates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_square_customers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

attachment: 3
aw_workflow: 1
bookable_resource: 2
follow_up_email: 1
page: 11
post: 2
product: 15
product_variation: 6
revision: 11
shop_coupon: 2
shop_order: 45
shop_order_refund: 1
shop_subscription: 6
wc_booking: 5

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (5) ###

Email Log: by Sudar – 2.4.3
Jetpack by WordPress.com: by Automattic – 9.5
Plugin Toggle: by Cedaro – 1.3.1
WooCommerce Stripe Gateway: by WooCommerce – 4.9.0
WooCommerce: by Automattic – 5.1.0

### Inactive Plugins (677) ###

A/B Testing for WooCommerce: by Progressus.io – 1.0.1
Abandoned Cart Recovery: by Addify – 1.0.0
ACS Courier Automatic Shipping Calculation: by WPSlash – 1.4.4
ACS Courier Voucher for WooCommerce: by WPSlash – 2.4.3
Acutrack Webservices: by Acutrack Inc – 1.0.1
Add Featured Videos in Product Gallery for WooCommerce: by FME ADDONS – 1.0.2
Address Autocomplete: by HighAddons – 1.0.3
Address Field Autocomplete For WooCommerce: by wpexpertsio – 1.0.0
Add To Cart Redirect for WooCommerce: by Jeroen Sormani – 1.0.3
Advanced Cash on Delivery with Fee: by Addify – 1.0.0
Advanced Cash on Delivery with Fee: by Addify – 1.0.0
Advanced Catalog Mode for WooCommerce: by ELEXtensions – 1.0.3
Advanced Easy Shipping For WooCommerce: by idomit – 2.0
Advanced Flat Rate Shipping For WooCommerce: by theDotstore – 4.3
Advanced Product Quantity: by Addify – 1.0.6
Affiliate For WooCommerce: by StoreApps – 2.8.0
Affiliate Program For WooCommerce: by E Plugins – 1.2.1
AliExpress Dropshipping for WooCommerce: by CedCommerce – 1.0.4
Aliexpress Product Importer: by Nxtal – 1.0.1
Amazon Product Importer: by Nxtal – 1.0.1
AntsRoute for Woocomerce: by DMConcept – 1.0
API Manager Example: by Todd Lahman LLC – 1.2
Approve New User Registration: by Addify – 1.4.0
Assorted Products For WooCommerce: by CodeIncept – 1.0.3
Auctions and Biddings for WooCommerce: by FantasticPlugins – 1.0
Auctions for WooCommerce: by WPInstitut – 1.3
Auctions Made Easy for WooCommerce: by FantasticPlugins – 2.3
AutomateWoo: by WooCommerce – 5.1.3
AutomateWoo - Birthdays Add-on: by WooCommerce – 1.2.0
AutomateWoo - Refer A Friend Add-on: by WooCommerce – 2.5.6
Auto Update Cart for WooCommerce: by Amplify Plugins – 1.2.0
Availability Scheduler: by HighAddons – 1.0.0
B2B E-commerce For WooCommerce: by Codup – 1.3.10.5
B2B for WooCommerce: by Addify – 1.4.6
BadgeOS Sensei Add-On: by Credly – 1.0.4
Best Sellers for WooCommerce: by FantasticPlugins – 1.1
Birthday Discount Coupon: by KoalaApps – 1.0.0
Bought Together for WooCommerce: by WP1 – 1.0.1
Braintree for WooCommerce Payment Gateway: by WooCommerce – 2.4.3
Bulk Add To Cart By Aheadworks: by Aheadworks – 1.0.0
Bulk Edit Products, Prices & Attributes for Woocommerce: by ELEX – 1.0.3
Bulk Order Form For WooCommerce: by wpexpertsio – 1.1.0
Bulk Order Form For WooCommerce: by wpexpertsio – 1.1.1
Bulk Shop for WooCommerce: by Consortia – 1.3.31
Bulk Table Editor for WooCommerce: by Consortia – 2.1.10
Buy Again for WooCommerce: by FantasticPlugins – 2.1
Calculate your price for WooCommerce: by Consortia – 2.0.4
CartMagician iOS only: by CartMagician – 1.0.11
Cart Reports for WooCommerce: by WooCommerce – 1.2.9
Cart To Quote: by HighAddons – 1.0.1
Cart Upsell for WooCommerce: by SKROTRON – 1.0.4
Cashier for WooCommerce: by StoreApps – 1.2.0
Catalog Visibility for WooCommerce: by Codup – 1.1.6.1
CDEK PRO for WooCommerce: by Artem Komarov – 1.0.5
Choose User Role at Registration: by Addify – 1.1.0
Clever Ads Campaigns: by Clever Ecommerce – 1.0.1
Commerce Direct Plugin: by Commerce Direct
Inc. – 1.5

Conditional Checkout Fields for WooCommerce: by FME Addons – 1.0.5
Conditional Payment Methods For WooCommerce: by StoreApps – 1.2.0
Contact and Quote Form: by POWr.io – 2.0.2
Convertiply Popups: by convertiply – 1.5
Countdown and Notifier For WooCommerce: by Skrotron – 1.0.3
Coupon Referral Program: by MakeWebBetter – 1.5.0
Coupons Pro for WooCommerce: by FantasticPlugins – 1.2
Credits for WooCommerce: by FantasticPlugins – 2.2
Customer Specific Pricing for WooCommerce: by WisdmLabs – 4.6.1
Customer Upload Files for WooCommerce: by FME Addons – 1.0.2
Customize My Account Page For Woocommerce: by WPEverest – 0.2.4
Custom Product Boxes: by CodeIncept – 1.0.2
Custom Product Designer for WooCommerce: by Extendons – 1.0.1
Custom Product Tag Image: by KoalaApps – 1.0.0
Custom User Defined Price for WooCommerce: by FME ADDONS – 1.0.3
Custom User Registration Fields for WooCommerce: by Addify – 1.6.2
Deals for WooCommerce: by FantasticPlugins – 1.4
Donation For Woocommerce: by wpexpertsio – 2.0.2
E-commerce SEO by WordLift: by WordLift
Insideout10 – 1.0.5

eBay Integration for Woocommerce: by CedCommerce – 1.0.4
eBay Product Importer: by Nxtal – 1.0.1
Elta Courier Voucher for WooCommerce: by WPSlash – 2.4.3
Email Customizer for WooCommerce: by StoreApps – 1.0.0
Email Customizer Pro For WooCommerce: by StoreApps – 2.2.0
Enhancer for WooCommerce Subscriptions: by FantasticPlugins – 1.7
ePay.bg Gateway for WooCommerce: by VanboDevelops – 1.4.3
Etsy Integration for WooCommerce: by CedCommerce – 1.1.2
Express Checkout for WooCommerce: by Express Checkout – 1.2
Extendons - Woocommerce Customize Account Dashboard Plugin: by Extendons – 1.1.0
Extendons - WooCommerce Mini Cart Plugin: by Extendons – 1.2.0
Extendons: Woocommerce Product Quantity: by Extendons – 2.0.0
Extendons GEO IP Ultimate Lock: by Extendons – 1.0.1
Extendons WooCommerce Custom Product Boxes Plugin: by Extendons – 1.0.0
Extendons WooCommerce Product Image Zoom: by Extendons – 1.0.1
Extra Fees for WooCommerce: by FantasticPlugins – 1.7
Facebook for WooCommerce: by Facebook – 2.3.2
Featured Listing for Product Vendors: by WooCommerce – 1.0.0
Featured Listing for WooCommerce: by itzmekhokan – 1.0.1
Floating Cart For WooCommerce: by SkroTron – 1.1.1
FME Addons: Customer Upload Files: by FME Addons – 1.0.0
FME Addons: Sales Countdown Timer For Woocommerce: by fmeaddons – 1.0.4
FME Addons: Shop as a Customer for WooCommerce: by fmeaddons – 1.0.7
Follow-Up Emails: by WooCommerce – 4.9.8
FooSales for WooCommerce: by FooSales – 1.4.3
FreeAgent for WooCommerce: by Neil Pie – 1.2.10
Free Gifts for WooCommerce: by FantasticPlugins – 5.9
Frequently Bought Together: by Premmerce – 1.0.0
Gallery Captions for WooCommerce: by John Beales – 1.3.1
Gateway for WooCommerce to Wirecard system: by VanboDevelops – 1.7.4
GDPR Cookies: by opmc – 1.1
Gems for WooCommerce: by CherryPick Studios – 1.5.0
Geniki Taxydromiki Voucher for WooCommerce: by WPSlash – 2.4.5
Gift Wrapper for WooCommerce: by FantasticPlugins – 2.5
Google Ads for WooCommerce: by Kliken – 1.0.4
Google Auto-fill Address on Checkout, Order & Account Page: by FME Addons – 1.0.0
Groups WooCommerce: by itthinx – 1.20.0
Heraldbee: by Heraldbee – 1.0
Hide Price and Add to Cart Button: by Addify – 1.2.2
Hide Prices & Private Store for WooCommerce: by WebWizards – 1.0.0
Hide Shipping Methods for WooCommerce: by ELEXtensions – 1.0.2
HubSpot for WooCommerce: by MakeWebBetter – 1.0.6
Integration of Firebase Analytics and WooCommerce: by Appmaker – 0.2.7
Intercom Integration for WooCommerce: by WooCommerce – 1.0
JivoChat: by JivoChat – 1.4.1
KindBuys for WooCommerce: by KindBuys – 1.1.0
KIWIZ Invoices Certification & PDF System: by KIWIZ – 2.1.3
Krokedil Product Documents: by Krokedil – 1.0.1
Krokedil Wishlist: by Krokedil – 1.0.0
Last Minute Offer For WooCommerce: by WP1 – 1.0.1
Liberty Reserve for Woocommerce: by Amin Abbasi – 0.2
LimeSpot for WooCommerce: by LimeSpot – 2.0.0
Live Sales Notifications for WooCommerce: by PI Websolution – 2.1.7
Loco Translate: by Tim Whitlock – 2.5.1
Logico Bid Smart Advertising: by Logico Team – 1.10.3
Lottery for WooCommerce: by FantasticPlugins – 3.4
Lower Price for WooCommerce: by FantasticPlugins – 1.1
MailChimp for WooCommerce Memberships: by SkyVerge – 1.4.0
Max upload size: by Ziscom – 3.0.0
Megaventory: by Megaventory – 2.2.6
Menu by User Roles: by Addify – 1.0.0
Minimum Periods for WooCommerce Subscriptions: by WP Extend – 1.1.0
MultilingualPress: by Inpsyde GmbH – 3.5.0
Multiple email attachments: by Brick Zero – 1.0.0
My Account Page Editor: by KoalaApps – 1.0.0
My Account Page Editor: by KoalaApps – 1.1.1
My Wish List for WooCommerce: by WP1 – 1.0.9
Odoo for Woocommerce: by OPMC – 1.1
OneStock for WooCommerce: by Inpsyde GmbH – 1.1.1
Order Bump for WooCommerce: by FantasticPlugins – 1.2
Order Cancellation Email to Customer: by KoalaApps – 1.0.0
Order On WhatsApp for woocommerce: by FME ADDONS – 1.0.5
Pasarela de pago para Pasat 4B: by Mikel Martin (ZhenIt Software) – 1.0.1
Password Protected Categories & Store: by CodeIncept – 1.0.0
Payment Reminder for WooCommerce: by SKROTRON – 1.0.5
Paywall for WooCommerce: by TIV.NET INC – 2.3.0
Phone Orders & Payments: by 99w – 1.0.0
Pinterest for WooCommerce: by premmerce – 2.3.1
Point of Sale for WooCommerce: by Actuality Extensions – 5.3.4
Popup Pro By Aheadworks: by Aheadworks – 1.0.1
POWr Countdown Timer: by POWr.io – 2.0.1
POWr Faq: by POWr.io – 2.0.1
POWr Form Builder: by POWr.io – 2.0.0
POWr Media Gallery: by POWr.io – 2.0.1
POWr Multi Slider: by POWr.io – 2.0.1
POWr Popup: by POWr.io – 2.0.1
POWr Reviews: by POWr.io – 2.0.1
POWr Social Feed: by POWr.io – 2.0.1
POWr Store Locator: by POWr.io – 2.0.1
Prdocut Variation Table Plugin: by FME ADDONS – 1.0.0
Price & Stock Import: by 99w – 1.1.0
Price By Country: by HighAddons – 1.0.2
Price Drop Notifier for WooCommerce: by FantasticPlugins – 1.2
Price Text for WooCommerce: by KoalaApps – 1.0.0
Private Store For WooCommerce: by CodeIncept – 1.0.4
Product Availability Slots for WooCommerce: by FantasticPlugins – 3.3
Product Badges: by 99w – 1.2.1
Product Brands for WooCommerce: by WP1 – 1.0.9
Product Condition for WooCommerce: by Amplify Plugins – 1.3.3
Product Description in Loop: by Extendons – 1.0.0
Product Description on Shop Page: by KoalaApps – 1.0.1
Product Description on Shop Page: by KoalaApps – 1.0.0
Product Designer for WooCommerce: by FantasticPlugins – 1.0
Product FAQs: by 99w – 1.0.5
Product Filters for WooCommerce: by WooCommerce – 1.2.4
Product Importer: by Nxtal – 1.0.1
Product Likes: by 99w – 1.0.4
Product listing page with list & grid view: by FME Addons – 1.0.0
Product Price Before & After Text: by 99w – 1.0.1
Product Prices by User Roles for WooCommerce Pro: by Tyche Softwares – 1.3.3
Product Questions By Aheadworks: by Aheadworks – 1.0.0
Product Recommendation Quiz for WooCommerce: by RevenueHunt – 1.0.12
Product Sales Count for WooCommerce: by FantasticPlugins – 1.1
Products By Attributes & Variations for WooCommerce: by Addify – 1.2.6
Product Slider for WooCommerce: by Weave Apps – 1.0.1
Product Sold Counter: by KoalaApps – 1.0.0
Products Visibility by User Roles: by Addify – 1.2.4
Product Variation Table Plugin: by FME ADDONS – 1.0.1
Product Video for WooCommerce: by Addify – 1.3.6
Quick Buy Now Button for WooCommerce: by Addify – 1.3.5
Quick Checkout for WooCommerce: by FantasticPlugins – 1.0
Quote Request for WooCommerce: by FantasticPlugins – 1.5
Rabo OmniKassa: by Paytium – 1.1.0
Rapyd Payments: by Rapyd – 1.0.5
ReadyCloud for WooCommerce: by ReadyCloud – 1.0.0
reCaptcha for WooCommerce: by I Thirteen Web Solution – 2.2
Redirect After Login, Registration & Logout: by Addify – 1.1.3
Registration & Login with Mobile Phone Number: by FME ADDONS – 1.0.0
Remove Related Products for WooCommerce: by poglaa – 1.0.1
Rental Products: by 99w – 2.8.2
Request a Quote for WooCommerce: by Addify – 2.1.2
Request a Quote for WooCommerce: by Addify – 1.5.5
Restaurant For WooCommerce: by wpexpertsio – 1.2.2
Reward Points By Aheadworks: by Aheadworks – 1.1.0
Richpanel for WooCommerce: by Richpanel – 2.2.7
Richpanel for WooCommerce: by Richpanel – 2.2.7
Rich Snippets & Schema Markup Plugin for WooCommerce: by Extendons – 1.0.0
Role Based Pricing for WooCommerce: by Addify – 1.5.0
Roles & Rules B2B for WooCommerce: by Consortia – 1.0.6
Russian Post and EMS PRO for WooCommerce: by Artem Komarov – 1.0.9
Save & Share Cart: by HighAddons – 1.0.0
Save & Share Cart: by HighAddons – 1.0.1
Save Cart Later: by MakeWebBetter – 1.0.1
Saved Addresses For WooCommerce: by StoreApps – 2.1.0
Save for Later for WooCommerce: by FantasticPlugins – 2.5
Save Now Buy Later for WooCommerce: by WP1 – 1.0.3
Scanventory Pro: by Scanventory.net – 1.1.5
Scratch Coupon for WooCommerce: by WP1 – 1.0.3
Search Merchandising: by 99w – 1.0.3
See You Later by WooThemes: by WooThemes – 1.1.1
Sensei Content Drip: by Automattic – 2.1.0
Sensei Course Participants: by Automattic – 2.0.2
Sensei LMS: by Automattic – 3.8.1
Sensei LMS Certificates: by Automattic – 2.1.0
Sensei LMS Course Progress: by Automattic – 2.0.3
Sensei LMS Media Attachments: by Automattic – 2.0.3
Sensei Modules: by WooThemes – 1.0.10
Sensei Share Your Grade: by Automattic – 2.0.1
Sensei with WooCommerce Paid Courses: by Automattic – 3.5.3.2.1.1
Share Cart URL for WooCommerce: by Eplugins – 1.0.0
Share Your Purchase for WooCommerce: by Enrique J. Ros – 2.4.0
Shipping Locations Pro: by WPExtend – 1.0.0
Shopee Integration for WooCommerce: by CedCommerce – 1.0.6
Simple Sale Countdown Timer: by Avamaksa – 1.2.0
Sirio: by Chiron <sirio@chiron.ai> – 0.0.1
Sirio: by Chiron <sirio@chiron.ai> – 0.0.1
SixAds: by SixAds – 1.05
Size Chart for WooCommerce: by KoalaApps – 1.0.1
Smart Bulk Variations: by HighAddons – 1.0.0
Smart Product Bundles For WooCommerce: by wpexpertsio – 1.1.3
Smart Product Quantity: by HighAddons – 1.0.0
Social Login Pro for WooCommerce: by WP Plugin Experts – 1.0.0
Sofort payment gateway: by Sven Wagener – 1.4.4
Speedex Courier Voucher for WooCommerce: by WPSlash – 2.4.2
Spin to Win: by POWr.io – 2.0.1
Spin Wheel PopUp: by SkroTron – 1.0.9
Spocket: by Spocket – 1.6.1
Sticky Cart For WooCommerce: by SkroTron – 1.1.4
Storefront Blog Customiser: by WooCommerce – 1.3.0
Storefront Checkout Customiser: by WooThemes – 1.1.4
Storefront Designer: by WooThemes – 1.8.4
Storefront Mega Menus: by WooCommerce – 1.6.2
Storefront Parallax Hero: by WooCommerce – 1.5.7
Storefront Powerpack: by WooCommerce – 1.5.0
Storefront Pricing Tables: by WooCommerce – 1.1.0
Storefront Product Hero: by WooThemes – 1.2.13
Storefront Reviews: by WooCommerce – 1.0.6
Storefront WooCommerce Customiser: by WooThemes – 1.9.1
Store Locator Plugin for WooCommerce: by EXTENDONS Addons – 1.1.0
Storewide Sale: by HighAddons – 1.0.0
Subscription Plus For WooCommerce: by Codup – 1.1.1.5
Subscriptions Add-On for WooCommerce: by Codup – 1.2.5.11
Subscriptions Add-On for WooCommerce: by Codup – 1.1.1.6
TargetBay Product and Site reviews: by TargetBay – 1.1
Tax Exempt for WooCommerce: by Addify – 1.4.8
Teams for WooCommerce Memberships: by SkyVerge – 1.5.2
THSA Apps | One-click Switcher: by The Health Sciences Academy – 2.0.7
Tiered Price Table for WooCommerce: by Kolya Lukin – 3.1.1
Tipping for WooCommerce: by WPSlash – 1.0.3
Top Bar: by WP Darko – 3.0.3
Top Bar for WooCommerce: by Addify – 1.2.2
Vertical & Accordion Product Detail Tabs: by I Thirteen Web Solution – 1.0
Viva Wallet for WooCommerce: by Viva Wallet – 1.2.0
Vosfactures: by VosFactures – 1.1.6
Walmart Canada Integration for WooCommerce: by CedCommerce – 1.0.1
Walmart Integration for WooCommerce: by CedCommerce – 2.0.5
Walmart Product Importer: by Nxtal – 1.0.1
WC Currency Switcher: by wpexpertsio – 1.3
Wholesale For WooCommerce: by wpexpertsio – 1.4.0
Wholesale Market for WooCommerce: by CedCommerce <plugins@cedcommerce.com> – 1.0.0
Wholesale Product Page Customizer For WooCommerce: by Codup – 1.1.2.30
Wholesale Product Page Customizer For WooCommerce: by Codup – 1.1.2.24
Wish.com Integration for WooCommerce: by CedCommerce <cedcommerce.com> – 2.0.3
Woo All In One Product Slider Carousel: by I Thirteen Web Solution – 1.0.13
Woo Bot for WooCommerce: by WP1 – 1.0.0
WooCommerce - Amazon Simple Pay: by Matt Gates – 2.0.2
WooCommerce - Bring: by Matt Gates – 1.1.4
WooCommerce - Clockwork SMS: by <a href="http://www.mediaburst.co.uk/">Mediaburst</a> – 2.0.11
WooCommerce - e-Path Payment Gateway: by OM4 – 1.7.1
WooCommerce - Facebook Tab: by WooThemes – 1.2.0
WooCommerce - JigoShop -> WooCommerce Converter: by WooThemes – 2.0.1
WooCommerce - Limited Deals: by Matt Gates – 2.0.4
Woocommerce - QR Code Generator: by Matt Gates – 1.0.3
WooCommerce - Sermepa Standard Payment Gateway: by UCI Informatica – 1.0.1
WooCommerce - ShipStation Integration: by WooCommerce – 4.1.22
WooCommerce - Watermark: by David Baker – 1.1.4
WooCommerce - WP E-Commerce -> WooCommerce Converter: by WooThemes – 1.1.7
WooCommerce 2Checkout - Inline Checkout: by WooCommerce – 1.1.15
WooCommerce 2Checkout API Gateway: by WooCommerce – 1.0.8
WooCommerce 2Checkout Gateway: by Krokedil – 1.5.1
WooCommerce 360° Image: by WooCommerce – 1.1.19
WooCommerce Accommodation Bookings: by WooCommerce – 1.1.23
WooCommerce Account Funds: by Themesquad – 2.3.4
WooCommerce Additional Variation Images: by WooCommerce – 1.7.26
WooCommerce Address Validation: by SkyVerge – 2.7.2
WooCommerce Admin Custom Order Fields: by SkyVerge – 1.15.0
WooCommerce Advanced Ajax Layered Navigation: by WooCommerce – 1.4.27
WooCommerce Advanced Notifications: by WooCommerce – 1.2.28
WooCommerce Advanced Product Labels: by Jeroen Sormani – 1.1.7
WooCommerce Advanced Shipping Packages: by Jeroen Sormani – 1.1.7
WooCommerce Affirm Gateway: by WooCommerce – 1.1.12
WooCommerce After the Order: by OM4 – 1.0.6
WooCommerce Aliant Payment Systems Gateway: by Russell Benzing – 1.1.1
WooCommerce Alipay Cross-Border: by WooThemes – 2.9.2
WooCommerce Allied Wallet Gateway: by WooCommerce – 1.3.2
WooCommerce All Products For Subscriptions: by SomewhereWarm – 3.1.19
WooCommerce Amazon and eBay Integration: by Codisto – 1.3.53
WooCommerce Amazon FPS Gateway: by SkyVerge – 2.2.0
WooCommerce Amazon Fulfillment: by Never Settle – 3.3.5
WooCommerce Amazon Pay: by WooCommerce – 1.13.1
WooCommerce Amazon S3 Storage: by WooCommerce – 2.1.22
WooCommerce Amazon Simple Pay Gateway: by SkyVerge – 1.2.0
WooCommerce Ambassador Integration: by WooThemes – 1.1.5
WooCommerce Anti Fraud: by OPMC Australia Pty Ltd – 3.2
WooCommerce ANZ eGate Gateway: by Tyson Armstrong – 3.0.10
WooCommerce API Manager: by Todd Lahman LLC – 2.3.9
WooCommerce Aramex: by WooCommerce – 1.0.10
WooCommerce Assistant: by TIV.NET – 1.0.1
WooCommerce Atos SIPS gateway: by 6WWW – 1.0.1
WooCommerce Australia Post Shipping: by WooCommerce – 2.4.27
WooCommerce Authipay Gateway: by WooCommerce – 1.0.10
WooCommerce Authorize.Net Accept Hosted Gateway: by SkyVerge – 2.1.5
WooCommerce Authorize.Net AIM Gateway: by SkyVerge – 3.14.6
WooCommerce Authorize.net DPM Gateway: by WooCommerce – 1.8.1
WooCommerce Authorize.Net Gateway: by SkyVerge – 3.3.2
WooCommerce Authorize.Net Reporting: by SkyVerge – 1.11.1
WooCommerce AvaTax: by SkyVerge – 1.10.5
WooCommerce AWeber Newsletter Subscription: by Themesquad – 3.3.1
WooCommerce B2B Roles & Permissions: by Codup – 1.1.2.14
WooCommerce B2B Roles & Permissions: by Codup – 1.1.2.34
WooCommerce Bambora Gateway: by SkyVerge – 2.3.2
WooCommerce BluePay Gateway: by WooCommerce – 1.1.8
WooCommerce Bonus Downloads: by WooThemes – 1.0
WooCommerce Bookings: by WooCommerce – 1.15.33
WooCommerce Bookings Availability: by WooCommerce – 1.1.16
WooCommerce Bookings Filters: by Codup – 1.2.0.10
WooCommerce Box Office: by WooCommerce – 1.1.30
WooCommerce Braintree Gateway: by SkyVerge – 3.3.3
WooCommerce Braintree TR Payment Gateway: by SkyVerge – 1.3.1
WooCommerce Branding: by WooCommerce – 1.0.28
WooCommerce Brands: by WooCommerce – 1.6.21
WooCommerce Bulk Download: by WooCommerce – 1.2.13
WooCommerce Bulk Stock Management: by WooCommerce – 2.2.31
WooCommerce Bulk Variations: by Lucas Stark – 1.6.6
WooCommerce Buy One Get One Free: by Oscar Gare – 2.0.13
WooCommerce Canada Post Shipping: by WooCommerce – 2.5.19
WooCommerce CardStream Gateway: by Add On Enterprises – 2.2.2
WooCommerce Cart Add-Ons: by WooCommerce – 1.15.33
WooCommerce Cart Notices: by SkyVerge – 1.13.0
WooCommerce Catalog Restrictions: by Lucas Stark – 1.0
WooCommerce Catalog Visibility Options: by Lucas Stark – 3.2.12
WooCommerce Certitrade Gateway: by Krokedil – 1.2.1
WooCommerce CertoConnect Payment Gateway: by Ivan Andreev – 1.0.3
WooCommerce Chained Products: by StoreApps – 2.9.9
WooCommerce Chase Paymentech Gateway: by SkyVerge – 1.15.1
WooCommerce Checkout (Finland) Payment Gateway: by SkyVerge – 3.2.0
WooCommerce Checkout Add-Ons: by SkyVerge – 2.5.1
WooCommerce Checkout Field Editor: by WooCommerce – 1.5.37
WooCommerce ClickandBuy Banking: by Sven Wagener & MarketPress – 1.1.0
WooCommerce Clickatell SMS Notifications: by WooCommerce – 1.4.10
WooCommerce Clone Orders: by Vibe Agency – 1.1.0
WooCommerce Colissimo Shipping Rates: by WooCommerce – 1.1.9
WooCommerce Compare Products PRO: by A3 Revolution – 2.2.1
WooCommerce Composite Products: by SomewhereWarm – 7.1.6
WooCommerce Conditional Content: by Lucas Stark – 2.1.4
WooCommerce Conditional Shipping and Payments: by SomewhereWarm – 1.8.11
WooCommerce Constant Contact: by SkyVerge – 1.12.0
WooCommerce Contact for Shipping Quote: by Jeroen Sormani – 1.2.1
WooCommerce Conversion Tracking Pro: by weDevs – 1.0.3
WooCommerce Correios BR: by WooCommerce – 2.6.2
WooCommerce Cost of Goods: by SkyVerge – 2.10.0
WooCommerce Coupon Campaigns & Tracking: by WooCommerce – 1.1.16
WooCommerce Coupon Restrictions: by WooCommerce – 1.8.1
WooCommerce Currency Converter: by WooCommerce – 1.6.23
WooCommerce Customer/Order/Coupon CSV Import Suite: by SkyVerge – 3.9.1
WooCommerce Customer/Order/Coupon Export: by SkyVerge – 5.1.2
WooCommerce Customer/Order XML Export Suite: by SkyVerge – 2.6.3
WooCommerce Customer History: by Brian Richards – 1.2.1
WooCommerce Custom Thank You Pages: by Jeroen Sormani – 1.0.3
WooCommerce CyberSource Gateway: by SkyVerge – 2.3.1
WooCommerce CyberSource SA SOP Gateway: by SkyVerge – 2.9.2
WooCommerce CyberSource SOP eCheck Gateway: by SkyVerge – 1.2.1
WooCommerce Danske Bank Gateway: by WooThemes – 1.0.0
WooCommerce DataCash Payment Gateway: by Automattic – 1.2.6
WooCommerce Delivery Slots by Iconic: by Iconic – 1.13.3
WooCommerce Deposits: by WooCommerce – 1.5.6
WooCommerce DIBS FlexWin Gateway: by Krokedil – 2.1.7
WooCommerce Disability VAT Exemption: by WooCommerce – 1.4.4
WooCommerce Distance Rate Shipping: by Automattic – 1.0.26
WooCommerce DNB Gateway: by WooThemes – 1.0.0
WooCommerce Dotpay Gateway: by Inspire Labs – 1.0.1
WooCommerce Drip: by WooCommerce – 1.2.23
WooCommerce Dropshipping: by WooCommerce – 2.9
WooCommerce Dwolla Gateway: by SkyVerge – 1.7.0
WooCommerce Dynamic Pricing: by Lucas Stark – 3.1.22
WooCommerce E-Mail Attachments (by Inoplugs): by InoPlugs – 3.0.12
WooCommerce eBay Sync: by eBay Australia – 2.07
WooCommerce Elavon Converge Gateway: by SkyVerge – 2.9.0
WooCommerce Email Customizer: by WooCommerce – 1.1.18
WooCommerce ePay Payment Solutions Gateway: by ePay – 1.0.1
WooCommerce EU VAT Number: by WooCommerce – 2.3.25
WooCommerce evriPay Payment Gateway: by Gerhard Potgieter – 1.1
WooCommerce eWAY gateway (AU): by Andy Zhang – 1.3.2
WooCommerce eWAY gateway (NZ): by Andy Zhang – 1.1.1
WooCommerce eWAY gateway (UK): by Andy Zhang – 1.1.1
WooCommerce eWAY Shared Payments Gateway: by WooThemes – 1.0.7
WooCommerce FedEx Shipping: by WooCommerce – 3.4.33
WooCommerce First Data Payeezy Gateway: by SkyVerge – 4.8.1
WooCommerce FirstData UK Gateway: by WooCommerce – 1.1.6
WooCommerce Flat Rate Box Shipping: by WooCommerce – 2.0.16
WooCommerce Force Sells: by WooCommerce – 1.1.27
WooCommerce Free Gift Coupons: by Kathy Darling – 3.0.4
WooCommerce Freshbooks: by SkyVerge – 2.1.3
WooCommerce FreshBooks: by SkyVerge – 3.14.1
WooCommerce Freshdesk: by Automattic – 1.1.27
WooCommerce Gateway F2B: by John-Henrique – 1.0.1
WooCommerce Gateway Locaweb Boleto bancário: by John-Henrique – 2.7
WooCommerce Gateway Pagamento Digital: by WooCommerce – 1.3.3
WooCommerce Gift Cards: by SomewhereWarm – 1.5.6
WooCommerce Give Products: by WooThemes – 1.0
WooCommerce Give Products: by WooCommerce – 1.1.11
WooCommerce Global Payments Direct Gateway: by SkyVerge – 2.4.1
WooCommerce Global Payments HPP: by SkyVerge – 2.5.2
WooCommerce GoCardless Gateway: by WooCommerce – 2.4.13
WooCommerce Google Analytics Pro: by SkyVerge – 1.9.2
Woocommerce Google Merchant Center Customer Reviews: by WebPerfect.com – 1.1.4
WooCommerce Google Product Feed: by Ademti Software Ltd. – 9.4.1
WooCommerce Google Product Reviews Feed for Google Shopping Ads: by WebPerfect.com – 1.3.3
WooCommerce Google Wallet Gateway: by Niklas Högefjord – 1.3.5
WooCommerce Gravity Forms Product Add-Ons: by Lucas Stark – 3.3.16
WooCommerce Group Coupons: by itthinx – 1.16.0
WooCommerce Heidelpay Gateway: by Hinnerk Altenburg – 1.2.0
WooCommerce Help Scout: by WooCommerce – 2.6
Woocommerce Hipay Gateway: by Dimitri Lekien – 1.0.10
WooCommerce HipChat: by WooCommerce – 1.0.3
WooCommerce HiTrust Gateway: by Niklas Högefjord – 1.0.1
WooCommerce HSBC gateway: by Andy Zhang – 1.0.1
WooCommerce iDeal via Sisow Gateway: by WooCommerce – 2.1.9
WooCommerce IfMB Gateway: by Tiago Noronha (WooThemes) – 1.1.0
WooCommerce Infusionsoft: by Objects – 1.0.4
WooCommerce Ingenico (Ogone Platform): by SkyVerge – 1.13.0
WooCommerce Instagram: by Themesquad – 3.4.0
WooCommerce InterFax Integration: by WooCommerce – 1.1.3
WooCommerce Intuit Payments Gateway: by SkyVerge – 2.8.1
WooCommerce iPay88 Payment Gateway: by VanboDevelops – 1.3.3
WooCommerce iVeri Lite Payment Gateway: by Gerhard Potgieter / WooThemes – 1.0.9
WooCommerce JPlayer Product Sampler: by Automattic – 1.4.1
WooCommerce Kissmetrics: by SkyVerge – 1.16.0
WooCommerce KISS Metrics Custom Events: by WooThemes – 1.0.0
WooCommerce Klarna Gateway: by WooCommerce – 2.5.15
WooCommerce Krediidipank Gateway: by WooThemes – 1.0.0
WooCommerce LevelUp: by WooThemes – 1.1.3
WooCommerce LHV Gateway: by WooThemes – 1.0.0
WooCommerce LightSpeed POS: by WooCommerce – 1.9.1
WooCommerce Linnworks Integration: by Ivan Andreev | VanboDevelops – 1.0.6
WooCommerce Litmos: by SkyVerge – 1.7.0
WooCommerce Local Pickup Plus: by SkyVerge – 2.9.2
WooCommerce Mad Mimi integration: by WooThemes – 1.2.1
WooCommerce MailChimp Integration: by WooCommerce – 1.0.4
WooCommerce Measurement Price Calculator: by SkyVerge – 3.18.2
WooCommerce Media-to-product linker: by WooThemes – 1.0.4
WooCommerce Memberships: by SkyVerge – 1.19.2
WooCommerce MercadoPago Gateway: by Mariano Pérez Rodriguez – 1.1.4
WooCommerce Merchant Warrior Gateway: by Tyson Armstrong – 2.0.2
WooCommerce Merge Orders: by Vibe Agency – 1.0.1
WooCommerce Min/Max Quantities: by WooCommerce – 2.4.20
WooCommerce Minimum Advertised Price: by SkyVerge – 1.8.0
WooCommerce Mix and Match Products: by Kathy Darling – 1.10.6
WooCommerce Mixpanel: by SkyVerge – 1.16.1
WooCommerce Mobilpay Gateway: by Andrei Neamtu – 1.0.5
WooCommerce Moip Gateway: by WooCommerce – 1.5.3
WooCommerce Mollie Gateway: by SkyVerge – 2.15.2
WooCommerce Mollie iDEAL Gateway: by SkyVerge – 1.7
WooCommerce Moneris Gateway: by SkyVerge – 2.15.0
WooCommerce MSRP Pricing: by Ademti Software Ltd. – 3.1.1
WooCommerce Multi-currency: by TIV.NET INC – 2.9.3
WooCommerce MyGate Gateway: by WooCommerce – 1.2.15
WooCommerce MYOB Integration: by WooCommerce – 1.3
WooCommerce NAB Transact Gateway: by Tyson Armstrong – 2.3.1
WooCommerce Name Your Price: by Kathy Darling – 3.1.7
WooCommerce Nested Category Layout: by SkyVerge – 1.15.1
WooCommerce NETbilling Gateway: by SkyVerge – 1.14.0
WooCommerce New Zealand Post: by WooCommerce – 2.1.1
WooCommerce Ninja Forms Product Add-Ons: by WooThemes – 1.1.8.1
WooCommerce Nochex Gateway: by WooThemes – 1.2.0
WooCommerce Nordea Gateway: by WooThemes – 1.0.0
WooCommerce Offline CC Proccessing: by Patrick Garman – 1.0.1
WooCommerce One Page Checkout: by Automattic – 1.7.10
WooCommerce Opayo (formally SagePay) Form and Direct Gateway: by Andrew Benbow – 4.8.5
WooCommerce Order Barcodes: by WooCommerce – 1.3.23
WooCommerce Order Delivery: by Themesquad – 1.8.3
WooCommerce Order Status Change Notifier: by WooThemes – 1.1.0
WooCommerce Order Status Control: by SkyVerge – 1.14.0
WooCommerce Order Status Manager: by SkyVerge – 1.12.2
WooCommerce PagSeguro Gateway: by WooCommerce – 1.3.7
WooCommerce Pay360 (PayPoint) Gateway: by VanboDevelops – 2.2.1
WooCommerce Paya Gateway: by Andrew Benbow – 3.3.4
WooCommerce PayEx Gateway: by Krokedil – 1.2.3
WooCommerce PayGate Gateway: by WooCommerce – 1.3.4
WooCommerce PayLeap Gateway: by WebDevStudios – 1.1.1
WooCommerce Payment Express PX Post Gateway: by WooThemes – 2.1
WooCommerce Payment Gateway Based Fees: by InoPlugs – 3.2.1
WooCommerce Payments: by Automattic – 2.0.0
WooCommerce Paymill Gateway: by Lee Willis – 3.3.0
WooCommerce PayPal Adaptive Payments: by WooCommerce – 1.1.11
WooCommerce PayPal Digital Goods Gateway: by Prospress Inc. – 3.2.2
WooCommerce PayPal Express Gateway: by WooThemes / SkyVerge – 3.7.2
WooCommerce PayPal Payments Advanced Gateway: by WooCommerce – 1.24.11
WooCommerce PayPal Pro (Classic and PayFlow Editions) Gateway: by WooCommerce – 4.5.0
WooCommerce PayPal Pro Hosted: by WooCommerce – 1.0.22
WooCommerce Paysafe Gateway: by VanboDevelops – 3.7.1
WooCommerce Payson Gateway: by Krokedil – 1.7.4
WooCommerce PayTrace Payment Gateway: by VanboDevelops – 2.5.7
WooCommerce Paytrail Gateway: by SkyVerge – 2.8.0
WooCommerce PayU India Gateway: by WooCommerce – 1.8.2
WooCommerce PayU PL Gateway: by WooCommerce – 2.4.2
WooCommerce PayU Turkey Gateway: by Kiran Polapragada – 2.4
WooCommerce Payza Gateway: by WooCommerce – 1.3.4
WooCommerce PDF Invoices: by Andrew Benbow – 4.10.3
WooCommerce PDF Product Vouchers: by SkyVerge – 3.8.2
WooCommerce PDF Watermark: by WooCommerce – 1.2.1
WooCommerce Peach Payments Gateway: by WooCommerce – 1.1.2
WooCommerce PencePay Payment Gateway: by VanboDevelops | Ivan Andreev – 2.0
WooCommerce Photography: by WooCommerce – 1.0.28
WooCommerce PickingPal: by PickingPal – 1.3.0
WooCommerce Pinit: by Kevin Ye <widcater@gmail.com> – 1.2.0
WooCommerce Pin Payments Gateway: by Tyson Armstrong – 1.8.6
WooCommerce Points and Rewards: by WooCommerce – 1.6.42
WooCommerce PostNL: by WooCommerce – 1.2.7
WooCommerce Pre-Orders: by WooCommerce – 1.5.29
WooCommerce Print Invoices/Packing Lists: by SkyVerge – 3.11.0
WooCommerce Product Add-ons: by WooCommerce – 3.1.1
WooCommerce Product Bundles: by SomewhereWarm – 6.5.1
WooCommerce Product CSV Import Suite: by WooCommerce – 1.10.38
Woocommerce Product Disclaimer: by wpexperts.io – 2.5
WooCommerce Product Documents: by SkyVerge – 1.12.1
WooCommerce Product Enquiry Form: by WooCommerce – 1.2.16
WooCommerce Product Finder: by WooCommerce – 1.2.17
WooCommerce Product Gallery Slider: by WooCommerce – 1.4.2
WooCommerce Product Merchandizing: by Vibe Agency – 1.1.0
WooCommerce Product Owners: by WooThemes – 1.0
WooCommerce Product Recommendations: by SomewhereWarm – 1.4.7
WooCommerce Product Retailers: by SkyVerge – 1.14.1
WooCommerce Product Reviews Pro: by SkyVerge – 1.17.0
WooCommerce Products Compare: by WooCommerce – 1.0.23
WooCommerce Product Search: by itthinx – 3.5.1
WooCommerce Products Of The Day: by WooThemes – 1.2.0
WooCommerce Product Support: by WebDevStudios – 2.0.2
WooCommerce Product Table: by Codup.io – 1.2.2.30
WooCommerce Product Table: by Codup.io – 1.2.2.19
WooCommerce Product Vendors: by WooCommerce – 2.1.47
Woocommerce Product Warning & Disclaimer: by WiserSteps – 1.0.4
WooCommerce Professor Cloud: by Add On Enterprises – 2.0.17
WooCommerce Przelewy24 Gateway: by Inspire Labs – 1.4.2
WooCommerce PsiGate Payment Gateway: by VanboDevelops – 1.7.0
WooCommerce Purchase Order Payment Gateway: by WooCommerce – 1.2.12
WooCommerce Purolator: by WooCommerce – 2.4.17
WooCommerce Quick Order: by Codup – 1.2.0.12
WooCommerce Quick Order: by Codup – 1.2.0.25
WooCommerce Quick View: by WooCommerce – 1.2.12
WooCommerce Recommendation Engine: by Lucas Stark – 3.2.4
WooCommerce Recommendations by Graphflow: by WooThemes – 2.0.5
WooCommerce Referral System: by Codup.io – 1.3.4.15
WooCommerce Review for Discount: by WooCommerce – 1.6.19
WooCommerce Role Based Methods: by WPBackOffice – 2.4.2
WooCommerce Royal Mail: by WooCommerce – 2.5.31
WooCommerce Sale Flash Pro: by WooCommerce – 1.2.19
WooCommerce Sales Analysis: by itthinx – 1.4.0
WooCommerce Sales Report Email: by WooCommerce – 1.1.17
WooCommerce Samurai Payment Gateway: by WooThemes – 1.0.5
WooCommerce SAPO Domestic Parcel Service: by WooCommerce – 1.4.0
WooCommerce SAPO International Parcel Service: by WooCommerce – 1.2.6
WooCommerce SEB Gateway: by WooThemes – 1.0.0
WooCommerce SecureNet Gateway: by SkyVerge – 1.8.0
WooCommerce SecurePay (Direct Post) Gateway: by WooThemes – 1.4.3
WooCommerce SecureTrading Gateway: by Krokedil – 1.6.4
WooCommerce Segment.com Connector: by StoreApps – 1.9.3
WooCommerce Sequential Order Numbers Pro: by SkyVerge – 1.16.1
WooCommerce Servired/RedSys Spain Gateway: by José Conti – 12.0.3
WooCommerce shipcloud.io: by WooThemes – 1.2.0
WooCommerce Shipment Tracking: by WooCommerce – 1.6.26
WooCommerce Shipping & Tax: by Automattic – 1.25.8
WooCommerce ShippingEasy Integration: by WooThemes – 4.1.1
WooCommerce Shipping Per Product v2: by WooCommerce – 2.3.12
WooCommerce Ship to Multiple Addresses: by WooCommerce – 3.6.23
WooCommerce Shipwire: by SkyVerge – 2.6.1
WooCommerce Shopdock: by WooThemes – 1.1.0
WooCommerce Skrill Payment Gateway: by SkyVerge – 1.7.1
WooCommerce Slack: by WooCommerce – 1.2.6
WooCommerce Smart Cart: by WP1 – 1.2.5
WooCommerce Smart Coupons: by StoreApps – 4.12.2
WooCommerce Smart Refunder: by StoreApps – 1.5.2
WooCommerce SnapScan Gateway: by WooCommerce – 1.1.12
WooCommerce Social Login: by SkyVerge – 2.11.0
WooCommerce Social Rewards: by AppsXtreme – 1.0
WooCommerce Sofort Gateway: by Webshop112 - Radomir van Dalen – 1.1
WooCommerce Software Add-On: by WooCommerce – 1.7.17
WooCommerce Spee-Dee Shipping: by OPMC Australia Pty Ltd – 1.0.6
WooCommerce Speed Services Couriers: by WooCommerce – 1.0.12
WooCommerce Splash Popup: by WooCommerce – 1.2.19
WooCommerce Split Orders: by Vibe Agency – 1.2.0
WooCommerce Sponsorship Add-On: by Justin Kussow (jdkussow@gmail.com) and Chris Lema (cflema@gmail.com) – 1.0
WooCommerce Square: by WooCommerce – 2.3.4
WooCommerce Stamps.com API integration: by WooCommerce – 1.3.21
WooCommerce Stamps.com Export Suite: by SkyVerge – 2.11.1
WooCommerce Store Catalog PDF Download: by WooCommerce – 1.10.27
WooCommerce Store Credit: by Themesquad – 3.4.0
WooCommerce Subscribe to Newsletter: by Themesquad – 2.9.1
WooCommerce Subscription Downloads: by WooCommerce – 1.1.31
WooCommerce Subscriptions: by WooCommerce – 3.0.10
WooCommerce Subscriptions Gifting: by WooCommerce – 2.1.1
WooCommerce Suomen Verkkomaksut Payment Gateway: by Ilari Mäkelä – 1.1.4
WooCommerce SveaWebPay Gateway: by Krokedil – 1.4.3
WooCommerce Swedbank Gateway: by WooThemes – 1.0.4
WooCommerce Sync for QuickBooks Online - by MyWorks Software: by MyWorks Software – 2.2.0
WooCommerce Systempay Cyberplus gateway: by 6WWW – 1.0.1
WooCommerce Table Rate Shipping: by WooCommerce – 3.0.30
WooCommerce Tab Manager: by SkyVerge – 1.13.1
WooCommerce Taxamo: by WooCommerce – 1.2.17
WooCommerce Terms & Conditions Popup: by Patrick Rauland – 1.0.3
WooCommerce TiendaEnvío: by Midla – 1.0.0
WooCommerce to Shipworks XML Export: by Sebs Studio (Sebastien) – 1.0.0
WooCommerce TradeGecko Integration: by TradeGecko Pte Ltd – 1.7.9
WooCommerce TrustCommerce Gateway: by VanboDevelops – 2.2.1
WooCommerce Twilio SMS Notifications: by SkyVerge – 1.16.0
WooCommerce UPS Shipping: by WooCommerce – 3.2.29
WooCommerce URL Coupons: by SkyVerge – 2.12.0
WooCommerce USA ePay Gateway: by SkyVerge – 2.3.0
WooCommerce User Switching: by Krokedil – 1.0.0
WooCommerce UserVoice Integration: by WooThemes – 1.1.6
WooCommerce US Export: by InsideOut10 – 1.0.7
WooCommerce USPS Shipping: by WooCommerce – 4.4.49
WooCommerce Vantiv Gateway (Formerly Litle & Co): by WooCommerce – 1.2.5
WooCommerce Variation Swatches and Photos: by Lucas Stark – 3.1.2
WooCommerce VCS Payment Gateway - direct connection: by WooCommerce – 1.0.10
WooCommerce Virtual Card Services Gateway: by WooCommerce – 1.1.10
WooCommerce Virtual Merchant Gateway: by Jacob Davidson – 1.0.1
WooCommerce Waitlist: by Neil Pie – 2.2.2
WooCommerce Warranty Requests: by WooCommerce – 1.9.19
WooCommerce WebCash Payment Gateway: by WooThemes – 2.0.0
WooCommerce WePay Gateway: by SkyVerge – 1.6.0
WooCommerce Westpac & St. George PayWay NET Gateway: by Tyson Armstrong – 2.2.0
WooCommerce Westpac Australia PayWay payment gateway: by Tyson Armstrong – 1.0.1
WooCommerce Westpac PayWay API Gateway: by Tyson Armstrong – 1.5.3
WooCommerce Windcave Gateway: by OPMC – 4.3
WooCommerce Wishlist Member Integration: by WooCommerce – 2.5.2
WooCommerce WishLists: by Lucas Stark – 2.2.2
WooCommerce WorldPay Gateway: by Andrew Benbow – 4.1.7
WooCommerce WS Form PRO Product Add-Ons: by Westguard Solutions – 1.1.49
WooCommerce Xero Integration: by WooCommerce – 1.7.35
WooCommerce Zapier: by OM4 – 2.0.5
WooCommerce ZENDESK Support Integration: by WooCommerce – 1.0
WooCommerce Zferral Affiliates Integration: by WooThemes – 1.1.2
Woo Product Table PRO: by WooBeWoo – 1.3.9
WooSlider: by WooThemes – 2.4.0
WooSlider - Instagram Slideshow: by WooThemes – 1.0.0
WooSlider - WooCommerce Products Slideshow: by WooCommerce – 1.0.22
Woo Store finder: by wpexpertsio – 1.0.1
Woo Wheel: by wpexpertsio – 1.4
Worldpay Online Payments: by Worldpay
WooCommerce
Andrew Benbow – 2.1.3

WP Crontrol: by John Blackbourn & crontributors – 1.10.0

### Settings ###

API Enabled: –
Force SSL: –
Currency: AUD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: accommodation-booking (accommodation-booking)
booking (booking)
bundle (bundle)
external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #6 - /shop/
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 3.5.0
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 341
Oldest: 2021-02-09 05:11:21 +0000
Newest: 2021-03-12 04:38:54 +0000

Pending: 10
Oldest: 2021-03-12 04:51:29 +0000
Newest: 2021-04-11 06:02:22 +0000


### Status report information ###

Generated at: 2021-03-12 14:50:53 +10:00
```
</details>

### PR DESCRIPTION
**Pull request by roykho**
### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes #29359

### How to test the changes in this Pull Request:

1. Go to woocommerce->settings->shipping and add a shipping zone with a shipping method.
2. After seeing the "Save Changes" button disables, try to navigate away from this page.
3. Ensure you're not seeing any save changes message pop up from the browser.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Fix - Unneeded browser popup message of unsaved changes when adding a shipping zone with a shipping method.

### CODE REVIEW

File: assets/js/admin/wc-shipping-zone-methods.js [hunk 1]
```diff
@@ -62,6 +62,7 @@
 							shippingMethod.trigger( 'change:methods' );
 							shippingMethod.changes = {};
 							shippingMethod.trigger( 'saved:methods' );
+							window.onbeforeunload = null;
```
Comment (barryhughes) [inline assets/js/admin/wc-shipping-zone-methods.js:65]: Looks like a practical fix :vulcan_salute: 

I was initially confused why we interact with the `onbeforeunload` property directly (since within this same file we set things up using an [event listener](https://github.com/woocommerce/woocommerce/pull/29510/files#diff-f6d591c256ea15681bdaec8d51ddf7937d80db8c773fd86bb185650002ddacaeR82) rather than using the window property directly), so I wonder if adding a comment might be useful for the next person to touch this, something like:

```suggestion
							// Overrides the onbeforeunload callback added by settings.js.
							window.onbeforeunload = null;
```

(Just to make it clearer that this relates specifically to the dirty page handler from that other piece of JS, and not the `setUnloadConfirmation` or `clearUnloadConfirmation` functions from this file.)

**Review by barryhughes — CHANGES_REQUESTED** [review]
Looks good, optionally could add a comment to give some context to the next maintainer.

File: assets/js/admin/wc-shipping-zone-methods.js (hunk 1 above)
Comment (roykho) [reply assets/js/admin/wc-shipping-zone-methods.js:67]: Good idea. Added.

**Review by barryhughes — APPROVED** [review]
