### PR TITLE
Refresh UX to enable HPOS tables

### LINKED ISSUE #34975: [COT/HPOS]: UX Improvements to HPOS feature screen
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

We would like to make following improvements to HPOS feature screen to make it easier to use, combining them all into one issue since they are best handled by a single PR otherwise there will be lot of conflicts:

#### Remove the option to "Keep the posts table and the orders tables synchronized"
When COT/HPOS is enabled, if there are some orders pending migration and the `Keep the posts table and the orders tables synchronized` option is enabled on the COT/HPOS settings page, a new checkbox appears to enable an option for automatically switching to the new WC table once the migration is complete. It seems this option doesn't work as expected, see video below:

[https://d.pr/v/TjQk7y](https://d.pr/v/TjQk7y)

#### Remove other options for transactions except for "Read Uncommitted"

We currently allow using all modes of transactions that MySQL supports, such as Repeatable read, Read committed, Read uncommitted etc. However for our use case, just the "read uncommitted" transaction mode is sufficient, as it does not locks the posts table, but at the same if migration fails for some reason for the current batch, it will still roll back any partial changes.

We should declutter this UI to not only provide only this mode, as other modes can lock the posts and postmeta tables on a live site, but also we don't expect regular merchants to make sense of these transaction modes.

#### In the features controller page, add a link to the HPOS managment screen

When the feature is first enabled via WooCommerce > Settings > Advanced > Features, it is not immediately clear that the user would need to go to WooCommerce > Settings > Advanced > Custom Data Stores to actually enable the sync and make the HPOS authoritative. We should add a link to the manage feature page in the Features screen that should give the direction to user about where to go to.

### PR DESCRIPTION
**Pull request by vedanshujain**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

This PR makes the following changes to the feature-enabling flow for HPOS:

### Setting for specifying transactions is removed

Since many merchants would not be able to take an informed decision about which transaction setting to use (and whether to use transactions in the first place), this PR

1. Removes the setting to select the transaction and enabled it for everyone by default in `READ UNCOMMITTED` mode.
2. Reduces the scope of the transaction so that only insert and update statements of the batch are enclosed in a transaction. Currently, select statements (on the posts table) were also enclosed and therefore locks the post table for the duration of the transaction, which is something that is now avoided.

### Dedicated feature setting page is now folded into the feature controller page itself.

Currently, we have a dedicated feature setting page, which is now removed and folded into the features setting page itself so that merchant won't have to navigate to yet another screen to enable disable the feature.

### HPOS feature is elevated to stable and reduced the severity of warning messages

Currently, we have marked HPOS as experimental, however with this PR we have marked it as stable, and also reduced the severity of warning messages that we are showing.

So with this PR, the feature page will look like this:

When HPOS tables are authoritative

Screenshot 2023-07-07 at 6 59 12 PM

When post tables are authoritative (and incompatible plugins + un-synced orders are present)

Screenshot 2023-07-07 at 6 57 32 PM

Closes #34975 

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

**Pre-testing**
1. Start with a new show as this flow will be best tested when we start with a new shop on this branch. Alternatively, to start with the existing shop, switch to post tables, disable the sync, and drop the tables created for HPOS.
2. Create some products and some orders.
3. Add a dummy incompatible plugin. To do this create a new file called incompatible.php with the following contents and upload it to the site and activate the plugin
```php
<?php
/**
 * Plugin Name: Incompatible
 * WC requires at least: 5.0.0
 * WC tested up to: 7.4.0
 */

/**
 * Declare HPOS (in)compatibility.
 */
add_action( 'before_woocommerce_init', function() {
	if ( class_exists( \Automattic\WooCommerce\Utilities\FeaturesUtil::class ) ) {
		\Automattic\WooCommerce\Utilities\FeaturesUtil::declare_compatibility( 'custom_order_tables', __FILE__, false );
	}
} );

```

**Actual testing**
1. After completing pre-testing, let's go to WooCommerce > Settings> Advanced > Features. You should see the HPOS setting right on this screen.
2. Check that option to enable HPOS is disabled with the warning about incompatible plugins and unsynced order.
3. Start the sync, and test that it completes after some time.
4. Once sync is complete, go to the screen now, the warning about unsynced orders should go away.
5. Go the plugins screen and disable the test plugin that we uploaded.
6. Come back to the WooCommerce > Settings> Advanced > Features, option to enable HPOS should now be available.
7. Test that you can enable HPOS, go to the orders page and check that orders are listed as expected.

Please also refer to additional scenarios covered [in this comment](https://github.com/woocommerce/woocommerce/pull/38993#issuecomment-1630964276).

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [x] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [x] Enhancement

#### Message 

Refresh the HPOS enable UX flow for better clarity.

#### Comment 

</details>

### CODE REVIEW

**Comment by barryhughes** [comment]
💡 I modified the test plugin slightly to avoid an error (`$compatibility` was not in the closure's scope).

File: plugins/woocommerce/src/Internal/Features/FeaturesController.php [hunk 1]
```diff
@@ -109,11 +113,16 @@ public function __construct() {
...
 				'disable_ui'      => false,
 			),
-			'custom_order_tables'  => array(
-				'name'            => __( 'High-Performance order storage (COT)', 'woocommerce' ),
-				'description'     => __( 'Enable the high performance order storage feature.', 'woocommerce' ),
-				'is_experimental' => true,
-				'disable_ui'      => false,
+			// Options for HPOS features are added in CustomOrdersTableController to keep the logic in same place.
+			'custom_order_tables'  => array( // This exists for back-compat, otherwise is always enabled and hidden from WC 8.0.
+				'name'               => '',
```
Comment (barryhughes) [inline plugins/woocommerce/src/Internal/Features/FeaturesController.php]: Shall we give it a name?

```suggestion
				'name'               => __( 'High-Performance order storage (COT)', 'woocommerce' ),
```

Could also add back the description unless it is no longer used, but the name is definitely needed in some parts of the UI:

<div align="center">Screenshot 2023-07-10 at 11 41 15</div>

File: plugins/woocommerce/src/Internal/DataStores/Orders/CustomOrdersTableController.php [hunk 2]
```diff
@@ -606,5 +428,101 @@ private function register_post_type_for_order_placeholders(): void {
...
+		if ( ! $sync_complete ) {
+			$disabled_option = array( 'yes', 'no' );
+		}
+
+		return array(
+			'id'          => self::CUSTOM_ORDERS_TABLE_USAGE_ENABLED_OPTION,
+			'title'       => __( 'Data storage for orders', 'woocommerce' ),
+			'type'        => 'radio',
+			'options'     => array(
+				'no'  => __( 'WordPress Post tables', 'woocommerce' ),
```
Comment (barryhughes) [inline plugins/woocommerce/src/Internal/DataStores/Orders/CustomOrdersTableController.php]: This is a nit, but I don't think `Post` should be capitalized (and it doesn't tend to be in other places where it's used in a sentence or phrase within the WP UI):

```suggestion
				'no'  => __( 'WordPress post tables', 'woocommerce' ),
```

File: plugins/woocommerce/src/Internal/DataStores/Orders/CustomOrdersTableController.php [hunk 3]
```diff
@@ -606,5 +428,101 @@ private function register_post_type_for_order_placeholders(): void {
...
+		if ( $sync_in_progress && $sync_status['current_pending_count'] > 0 ) {
+			$sync_message = sprintf(
+				// translators: %d: number of pending orders.
+				__( 'Currently syncing orders... %d pending', 'woocommerce' ),
+				$sync_status['current_pending_count']
+			);
+		} elseif ( $sync_status['current_pending_count'] > 0 ) {
+			$sync_message = sprintf(
+				// translators: %d: number of pending orders.
+				__( 'Sync %d pending orders. You can switch data storage for orders only when posts and orders table are in sync.', 'woocommerce' ),
```
Comment (barryhughes) [inline plugins/woocommerce/src/Internal/DataStores/Orders/CustomOrdersTableController.php]: Not essential, but we could do:

```suggestion
				_n( 
					'Sync %d pending order. You can switch data storage for orders only when posts and orders table are in sync.', 'woocommerce' ),
					'Sync %d pending orders. You can switch data storage for orders only when posts and orders table are in sync.', 'woocommerce' ),
					$sync_status['current_pending_count'],
					'woocommerce'
				),
```

Or even just:

```suggestion
				__( 'Sync %d pending order(s). You can switch data storage for orders only when posts and orders table are in sync.', 'woocommerce' ),
```

File: plugins/woocommerce/src/Internal/DataStores/Orders/CustomOrdersTableController.php [hunk 4]
```diff
@@ -606,5 +428,101 @@ private function register_post_type_for_order_placeholders(): void {
...
+				$sync_status['current_pending_count']
+			);
+		}
+
+		return array(
+			'id'       => DataSynchronizer::ORDERS_DATA_SYNC_ENABLED_OPTION,
+			'title'    => '',
+			'type'     => 'checkbox',
+			'desc'     => __( 'Keep posts and orders table in sync. (Compatibility mode)', 'woocommerce' ),
```
Comment (barryhughes) [inline plugins/woocommerce/src/Internal/DataStores/Orders/CustomOrdersTableController.php]: Another nit, sorry 😬 ... Grammarly seems to prefer:

```suggestion
			'desc'     => __( 'Keep the posts and orders tables in sync (compatibility mode).', 'woocommerce' ),
```

File: plugins/woocommerce/src/Utilities/PluginUtil.php [hunk 5]
```diff
@@ -171,4 +171,61 @@ private function handle_plugin_de_activation(): void {
...
+				$feature_warning = sprintf(
+				/* translators: %1\$s, %2\$s = printable plugin names */
+					__( '⚠ 2 Incompatible plugins detected (%1$s and %2$s).', 'woocommerce' ),
+					$this->get_plugin_name( $incompatibles[0] ),
+					$this->get_plugin_name( $incompatibles[1] )
+				);
+			} else {
+
+				$feature_warning = sprintf(
+				/* translators: %1\$s, %2\$s = printable plugin names, %3\$d = plugins count */
```
Comment (barryhughes) [inline plugins/woocommerce/src/Utilities/PluginUtil.php]: Indentation could be tweaked:

```suggestion
					/* translators: %1\$s, %2\$s = printable plugin names, %3\$d = plugins count */
```

File: plugins/woocommerce/src/Utilities/PluginUtil.php [hunk 6]
```diff
@@ -171,4 +171,61 @@ private function handle_plugin_de_activation(): void {
...
+
+			$incompatible_plugins_url = add_query_arg(
+				array(
+					'plugin_status' => 'incompatible_with_feature',
+					'feature_id'    => $feature_id,
+				),
+				admin_url( 'plugins.php' )
+			);
+			/* translators: %s = URL of the plugins page */
+			$extra_desc_tip = sprintf( __( "<br><a href='%s'>View and manage</a>", 'woocommerce' ), $incompatible_plugins_url );
```
Comment (barryhughes) [inline plugins/woocommerce/src/Utilities/PluginUtil.php]: Thinking it is better to keep HTML out of translatable strings, what do you think of something like:

```suggestion
			/* translators: %1$s opening link tag %2$s closing link tag. */
			$extra_desc_tip = '<br>' . sprintf( 
				__( '%1$sView and manage%2$s', 'woocommerce' ), 
				'<a href="' . esc_url( $incompatible_plugins_url ) . '">',
				'</a>'
			);
```

File: plugins/woocommerce/includes/admin/class-wc-admin-settings.php [hunk 7]
```diff
@@ -439,7 +440,11 @@ class="<?php echo esc_attr( $value['class'] ); ?>"
 							</th>
 							<td class="forminp forminp-<?php echo esc_attr( sanitize_title( $value['type'] ) ); ?>">
 								<fieldset>
-									<?php echo $description; // WPCS: XSS ok. ?>
+									<?php
+									if ( ! $show_desc_at_end ) {
+										echo wp_kses_post( $description );
```
Comment (barryhughes) [inline plugins/woocommerce/includes/admin/class-wc-admin-settings.php:445]: (1/2) If the description is shown at the start, we echo `$description`.

File: plugins/woocommerce/includes/admin/class-wc-admin-settings.php [hunk 8]
```diff
@@ -458,6 +463,9 @@ class="<?php echo esc_attr( $value['class'] ); ?>"
 										</li>
 										<?php
 									}
+									if ( $show_desc_at_end ) {
+										echo wp_kses_post( "<p class='description description-thin'>{$value['desc']}</p>" );
```
Comment (barryhughes) [inline plugins/woocommerce/includes/admin/class-wc-admin-settings.php]: (2/2) If the description is shown at the end, we echo `$value['desc']`. Even if these are effectively aliases, seems it might be better to use the same one in both places?

Comment (barryhughes) [reply plugins/woocommerce/includes/admin/class-wc-admin-settings.php]: Unless this is deliberate, of course.

**Review by barryhughes — COMMENTED** [review]
Sharing some straightforward and minor notes on the UI part of this change, still looking at the other half (changes to migration code, etc).

**Review by barryhughes — COMMENTED** [review]
Nice!

Beyond the small things noted earlier, this tests well and I was able to re-sync and view orders post-migration, as expected.

File: plugins/woocommerce/src/Internal/DataStores/Orders/CustomOrdersTableController.php (hunk 3 above)
Comment (vedanshujain) [reply plugins/woocommerce/src/Internal/DataStores/Orders/CustomOrdersTableController.php]: Great suggestion!

File: plugins/woocommerce/includes/admin/class-wc-admin-settings.php (hunk 8 above)
Comment (vedanshujain) [reply plugins/woocommerce/includes/admin/class-wc-admin-settings.php]: I used `value['desc']` because `$description` won't be set when `desc_tip` is true, but on thinking further, it looks like it's fine not to set it in those cases. Added the recommendation.

**Comment by vedanshujain** [comment]
@barryhughes note that I am testing few more flows after #37050, will add review request when it's ready to be reviewed again.

**Comment by vedanshujain** [comment]
To test

**On a new shop, with at least one incompatible plugin but no orders**
- [x] When installing WC for the first time, posts are enabled. Additionally, there is no warning even when installing incompatible plugins (since post tables are enabled).
- [x] On the setting page, the option to switch to HPOS is disabled. However, the option to keep posts and HPOS in sync is enabled.
- [x] In the settings page, the incompatible plugin is listed. Additionally, clicking on "View and manage" takes to the plugin list page with incompatible plugins visible.
- [x] We show correct tools visibility in WooCommerce > Status > Tools. The tool for deleting order tables should be hidden.
- [x] Deactivating the incompatible plugin, enables the option to switch to HPOS (assuming no orders).
- [x] Enabling the HPOS (or enabling sync) also creates the order tables.
- [x] Tools visibility should be inverted, now the tool for dropping the order table should be visible. However, it is still disabled, since HPOS is authoritative.
- [x] Option to switch back to the post should be available. When switched back, the option to drop the order table should become visible again.

**On a shop with existing orders and post authoritative with all compatible plugins is updated to a version that contains this PR (custom order feature was not enabled)**
- [x] Posts are enabled by default, but the option to switch to HPOS is disabled. The radio box for posts is also disabled indicating that till there are orders to be synced, the authoritative source cannot be changed.
- [x] On enabling the option to keep posts and HPOS in sync, the message should be displayed in the settings section that sync is currently in progress.
- [x] At this point, going to WooCommerce > Status > Scheduled Actions should display the action pending for sync in either the pending or running tab.
- [x] After a while sync should complete, or at least the count should start decreasing.
- [x] Option to turn off sync should always be available.
- [x] When turned off, the action for migrating orders will not be scheduled again, even if there are pending orders. Already scheduled action will still be processed.
- [x] Tools visibility is as expected similar to the new shop flow.

**Other misc testings**
- [x] On shop with HPOS already enabled, switching to this PR will still have all corresponding settings enabled.
- [x] On shop with MyISAM table instead of InnoDB, transaction commands still works as expected without locking the orders table.

**Comment by barryhughes** [comment]
**On a new shop, with at least one incompatible plugin but no orders**

- [x] When installing WC for the first time, posts are enabled. Additionally, there is no warning even when installing incompatible plugins (since post tables are enabled).
- [ ] On the setting page, the option to switch to HPOS is disabled. However, the option to keep posts and HPOS in sync is enabled.
    - **No** → On a brand new site, after activating WooCommerce, the **Keep the posts and orders tables in sync (compatibility mode)** option is not checked.
- [x] In the settings page, the incompatible plugin is listed. Additionally, clicking on "View and manage" takes to the plugin list page with incompatible plugins visible.
    - Yes, once activated.
- [ ] We show correct tools visibility in WooCommerce > Status > Tools. The tool for creating order tables should be visible, and deleting order tables should be hidden.
    - **No** → The tool for deleting order tables is visible, and the tables are already in existence.
    - I wiped my install and started again to be sure; `<prefix>_wc_orders` is created as soon as I run through NUX (but probably earlier). Ditto the order meta table.
- [x] Deactivating the incompatible plugin, enables the option to switch to HPOS (assuming no orders).
- [ ] Enabling the HPOS also creates the order tables.
    - **No** → See earlier note, it seems like something is triggering table creation at some earlier juncture.
- [x] Tools visibility should be inverted, now the tool for dropping the order table should be visible. However, it is still disabled, since HPOS is authoritative.
    - Yes, however, I noticed something that is possible of interest. Before HPOS is enabled, but when the tables are created, the delete tool is present but disabled. Here's what I see (in this scenario, shouldn't the tool be enabled?):

<div align="center">Screenshot 2023-07-12 at 06 33 15</div>

- [ ] Option to switch back to the post should be available. When switched back, the option to drop the order table should become visible again.
    - **No** → I guess related to my previous note, though the drop tool is visible it is not enabled (contrary to what it says in the description).

**Comment by barryhughes** [comment]
Sorry for the delay, @vedanshujain. Left notes on the initial set of testing steps: do you want to check those out before I proceed to the second and third sets?

**Comment by vedanshujain** [comment]
@barryhughes No worries for now, I found some bug as I was going through the testing instructions myself. Let me convert this PR to draft to indicate that some identified work is pending.

**Comment by vedanshujain** [comment]
@barryhughes this is ready for review again, but note that I have not yet implemented the language softening we chatted about yesterday. Let's address that in a separate PR, since this one is getting too big, and I want to spread the test build around soon-ish. wdyt?

**Comment by barryhughes** [comment]
> Let's address that in a separate PR, since this one is getting too big, and I want to spread the test build around soon-ish. wdyt?

:+1:

File: plugins/woocommerce/src/Database/Migrations/CustomOrderTable/PostsToOrdersMigrationController.php [hunk 9]
```diff
@@ -26,7 +26,7 @@ class PostsToOrdersMigrationController {
 	/**
 	 * Array of objects used to perform the migration.
 	 *
-	 * @var array
+	 * @var array[TableMigrator]
```
Comment (barryhughes) [inline plugins/woocommerce/src/Database/Migrations/CustomOrderTable/PostsToOrdersMigrationController.php]: Feel free to ignore me if I'm wrong—it just jumped out because I don't think I've often seen it expressed this way—should this be:

```suggestion
	 * @var TableMigrator[]
```

https://docs.phpdoc.org/2.9/references/phpdoc/types.html#arrays

File: plugins/woocommerce/src/Database/Migrations/MetaToMetaTableMigrator.php [hunk 10]
```diff
@@ -61,33 +61,77 @@ public function __construct() {
...
-	protected function process_migration_batch_for_ids_core( array $entity_ids ): void {
+	public function fetch_sanitized_migration_data( $entity_ids ) {
+		$this->clear_errors();
 		$to_migrate = $this->fetch_data_for_migration_for_ids( $entity_ids );
 		if ( empty( $to_migrate ) ) {
-			return;
+			return array(
+				array(),
+				array(),
+			);
```
Comment (barryhughes) [inline plugins/woocommerce/src/Database/Migrations/MetaToMetaTableMigrator.php]: Also optional, because I think wherever the returned array is consumed we have appropriate checks, but, should this ideally be:

```suggestion
			return array(
				'data'   => array(),
				'errors' => array(),
			);
```

File: plugins/woocommerce/src/Internal/Features/FeaturesController.php [hunk 11]
```diff
@@ -722,16 +703,23 @@ private function get_setting_for_feature( string $feature_id, array $feature, bo
...
 			'disabled' => $disabled && ! $this->force_allow_enabling_features,
 			'desc_tip' => $desc_tip,
 			'tooltip'  => $tooltip,
 			'default'  => $this->feature_is_enabled_by_default( $feature_id ) ? 'yes' : 'no',
 		);
+
+		/**
+		 * Allows to modify feature setting that will be used to render in the feature page.
+		 *
+		 * @since 8.0.0
```
Comment (barryhughes) [inline plugins/woocommerce/src/Internal/Features/FeaturesController.php:730]: Should we document the filter params?

```suggestion
		 * @since 8.0.0
		 *
		 * @param array $feature_setting {
		 *     Describes the feature.
		 *
		 *     @type string $title    Feature title.
		 *     @type string $desc     Feature description.
		 *     @type string $type     Example: 'checkbox'.
		 *     @type string $id       Feature ID/slug.
		 *     @type bool   $disabled If disabled.
		 *     @type string $desc_tip Description tooltip text.
		 *     @type string $default  Default value for this feature setting.
		 * }
		 * @param string $feature_id  The feature ID.
		 
```

File: plugins/woocommerce/src/Utilities/PluginUtil.php [hunk 12]
```diff
@@ -171,4 +171,65 @@ private function handle_plugin_de_activation(): void {
...
+		$incompatibles      = array_merge( $plugin_feature_info['incompatible'], $plugin_feature_info['uncertain'] );
+		$incompatibles      = array_filter( $incompatibles, 'is_plugin_active' );
+		$incompatible_count = count( $incompatibles );
+		if ( $incompatible_count > 0 ) {
+			if ( 1 === $incompatible_count ) {
+				/* translators: %s = printable plugin name */
+				$feature_warning = sprintf( __( '⚠ 1 Incompatible plugin detected (%s).', 'woocommerce' ), $this->get_plugin_name( $incompatibles[0] ) );
+			} elseif ( 2 === $incompatible_count ) {
+				$feature_warning = sprintf(
+				/* translators: %1\$s, %2\$s = printable plugin names */
```
Comment (barryhughes) [inline plugins/woocommerce/src/Utilities/PluginUtil.php]:
```suggestion
					/* translators: %1\$s, %2\$s = printable plugin names */
```

**Review by barryhughes — APPROVED** [review]
Great! Some optional but non-required minor changes. This feels really nice.

File: plugins/woocommerce/src/Database/Migrations/MetaToMetaTableMigrator.php (hunk 10 above)
Comment (vedanshujain) [reply plugins/woocommerce/src/Database/Migrations/MetaToMetaTableMigrator.php]: Thanks for catching, seems like I missed this.

File: plugins/woocommerce/src/Utilities/PluginUtil.php (hunk 12 above)
Comment (vedanshujain) [reply plugins/woocommerce/src/Utilities/PluginUtil.php]: Addressed in https://github.com/woocommerce/woocommerce/pull/38993/commits/94fce9c169809e484a9d75803600ae3ad88b4ee5

File: plugins/woocommerce/src/Internal/Features/FeaturesController.php (hunk 11 above)
Comment (vedanshujain) [reply plugins/woocommerce/src/Internal/Features/FeaturesController.php:730]: Addressed in https://github.com/woocommerce/woocommerce/pull/38993/commits/94fce9c169809e484a9d75803600ae3ad88b4ee5

File: plugins/woocommerce/src/Database/Migrations/MetaToMetaTableMigrator.php (hunk 10 above)
Comment (vedanshujain) [reply plugins/woocommerce/src/Database/Migrations/MetaToMetaTableMigrator.php]: Addressed in https://github.com/woocommerce/woocommerce/pull/38993/commits/94fce9c169809e484a9d75803600ae3ad88b4ee5
