### PR TITLE
Fix/Fix new order triggers when creating/moving orders into draft or from draft to valid statuses

### LINKED ISSUE #48080: Creating an order in a draft status will trigger the "woocommerce_new_order" action
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When creating an Order through the admin screens with the Draft status, the hook "woocommerce_new_order" is erroneously triggered.

### Expected behavior

The aforementioned hook should not be triggered.

### Actual behavior

The aforementioned hook is triggered.

### Steps to reproduce

1. Install the Code Snippets extension and add the following snippet:

```php
add_action("woocommerce_new_order","any",20,1);
function any($order_id){
    ob_get_clean();
    die("woocommerce_new_order was triggered");
}
```
2. On WooCommerce > Orders click Add Order
3. On the order details screen choose the Draft status from the dropdown and click Create
4. See the "woocommerce_new_order was triggered" text on screen confirming the hook was called.

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): http://localhost
Site address (URL): http://localhost
WC Version: 9.1.0-dev
Legacy REST API Package Version: The Legacy REST API plugin is not installed on this site.
Action Scheduler Version: ✔ 3.7.4
Log Directory Writable: ✔
WP Version: 6.5.3
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.57 (Debian)
PHP Version: 8.3.4
PHP Post Max Size: 128 MB
PHP Time Limit: 600
PHP Max Input Vars: 1000
cURL Version: 7.88.1
OpenSSL/3.0.11

SUHOSIN Installed: –
MySQL Version: 11.3.2-MariaDB-1:11.3.2+maria~ubu2204
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 9.1.0
WC Database Prefix: wp_
Total Database Size: 18.23MB
Database Data Size: 15.41MB
Database Index Size: 2.82MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.13MB + Index: 0.13MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.14MB + Index: 0.14MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.11MB + Index: 0.13MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.06MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 12.02MB + Index: 0.08MB + Engine InnoDB
wp_postmeta: Data: 1.50MB + Index: 0.55MB + Engine InnoDB
wp_posts: Data: 0.22MB + Index: 0.06MB + Engine InnoDB
wp_snippets: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_orders: Data: 0.06MB + Index: 0.11MB + Engine InnoDB
wp_wc_orders_meta: Data: 0.14MB + Index: 0.25MB + Engine InnoDB
wp_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_operational_data: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.05MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wsal_metadata: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wsal_occurrences: Data: 0.02MB + Index: 0.03MB + Engine InnoDB

### Post Type Counts ###

attachment: 23
page: 11
post: 2
product: 23
product_variation: 12
revision: 16
shop_coupon: 3
shop_order: 220
wp_global_styles: 2
wp_navigation: 1
wp_template: 1
wp_template_part: 2

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (4) ###

Code Snippets: by Code Snippets Pro – 3.6.4
Debug Bar: by wordpressdotorg – 1.1.6
Debug Log Manager: by Bowo – 2.3.3
WooCommerce: by Automattic – 9.1.0-dev

### Inactive Plugins (19) ###

Akismet Anti-spam: Spam Protection: by Automattic - Anti-spam Team – 5.3.2
Another Show Hooks: by Exlac – 1.0.2
Error Log Viewer by BestWebSoft: by BestWebSoft – 1.1.5
Google Analytics for WooCommerce: by WooCommerce – 2.0.7
Gutenberg: by Gutenberg Team – 18.3.0
Multiple Packages for WooCommerce: by Erica Dion – 1.1
Newsletter Test Plugin: by opr – 2.0.0
Rate Limiting for Store API: by Paulo Arromba – 1.0
Simple Custom CSS and JS: by SilkyPress.com – 3.46
WooCommerce Bookings: by WooCommerce – 2.0.0 (update to version 2.1.2 is available)
WooCommerce Cart Add-Ons: by WooCommerce – 2.3.0
WooCommerce Checkout Field Editor: by WooCommerce – 1.7.11 (update to version 1.7.13 is available)
WooCommerce EU VAT Number: by WooCommerce – 2.4.1 (update to version 2.9.4 is available)
WooCommerce One Page Checkout: by Automattic – 2.8.0 (update to version 2.8.2 is available)
WooCommerce Sale Flash Pro: by WooCommerce – 1.2.22 (update to version 1.3.2 is available)
WooCommerce Smart Coupons: by StoreApps – 8.20.0 (update to version 9.0.1 is available)
WooCommerce Stripe Gateway: by WooCommerce – 8.2.0
WooPayments: by Automattic – 7.6.0 (update to version 7.7.0 is available)
WordPress Beta Tester: by WordPress Upgrade/Install Team – 3.5.5

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: 
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: ✔

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 220 KB

### WC Pages ###

Shop base: #7 - /shop/
Cart: #8 - /cart/
Checkout: #9 - /checkout/
My account: #10 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 4.5.4 (update to version 4.6.0 is available)
Author URL: https://woo.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page
launch-your-store

Disabled Features: experimental-blocks
minified-js
pattern-toolkit-full-composability
product-pre-publish-modal
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2024-06-01 11:17:37 +00:00
Options: ✔
Notes: 80
Onboarding: completed

### Action Scheduler ###

Complete: 406
Oldest: 2024-04-30 16:58:28 +0000
Newest: 2024-05-31 16:41:24 +0000

Failed: 2
Oldest: 2024-02-06 11:18:39 +0000
Newest: 2024-02-06 11:25:56 +0000

Pending: 2
Oldest: 2024-05-31 17:14:08 +0000
Newest: 2024-06-01 14:59:50 +0000

### Status report information ###

Generated at: 2024-05-31 16:41:34 +00:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### LINKED ISSUE #48342: In the admin, changing an order from draft to completed doesn't trigger anything when using CPT
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When CPT is enabled for orders, changing a draft order into the complete status won't trigger the `woocommerce_new_order`hook.

### Expected behavior

The hook `woocommerce_new_order` should be triggered, and the error log should print information about the order.

### Actual behavior

The `woocommerce_new_order` hook is not triggered

### Steps to reproduce

1. Install the Debug Log Manager extension
2. Using the Code Snippets extension add the following snippet
```php
add_action( 'woocommerce_new_order', 'any', 20, 1 );
function any( $order_id ) {
	error_log( 'Order ID: ' . $order_id . ' with status: ' . get_post_status( $order_id ) );
}
```
3. Go to WooCommerce > Settings > Advanced > Features
4. Enable WordPress posts storage (legacy)
5. Go to WooCommerce > Orders and click `Add Order`
6. Change the order status to draft and click `Create`
7. Go to `/wp-admin/tools.php?page=debug-log-manager` and clear the log
8. Go back to WooCommerce > Orders open the just created draft order and change the status to completed. Save the changes
9. Go to `/wp-admin/tools.php?page=debug-log-manager` and verify that no error is present confirming the new order hook wasn't triggered.,

### WordPress Environment

n/a

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### LINKED ISSUE #48343: Placing an order on Checkout Blocks won't trigger the woocommerce_new_order hook when using CPT
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Placing an order on Checkout Blocks won't trigger the woocommerce_new_order hook when using CPT

### Expected behavior

The hook `woocommerce_new_order` should be triggered, and the error log should print information about the order.

### Actual behavior

The woocommerce_new_order hook is not triggered

### Steps to reproduce

1. Install the Debug Log Manager extension
2. Using the Code Snippets extension add the following snippet
```php
add_action( 'woocommerce_new_order', 'any', 20, 1 );
function any( $order_id ) {
	error_log( 'Order ID: ' . $order_id . ' with status: ' . get_post_status( $order_id ) );
}
```
3. Go to WooCommerce > Settings > Advanced > Features
4. Enable `WordPress posts storage (legacy)`
5. Place an order using the Checkout Blocks
6. Go to /wp-admin/tools.php?page=debug-log-manager and verify that no error is present confirming the new order hook wasn't triggered.,

### WordPress Environment

n/a

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by wavvves**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

This PR resolves issues with new order hook triggers during transitions to and from draft status as well as creating a new order with a draft status, using CPT and HPOS. It fixes the following scenarios:

On CPT

- Placing the order, the new order hook is not triggered ❌
- In the admin, creating a new draft order triggers the new order hook with checkout-draft status ❌
- In the admin, changing an order from draft to completed doesn't trigger the new order hook ❌

On HPOS

- In the admin, creating a new draft order triggers the new order hook with checkout-draft status ❌

Closes #48342 
Closes #48080
Closes #48343 

### Testing preparation:
1. Install the Debug Log Manager and Code Snippets extensions and add the following snippet:

```php
add_action( 'woocommerce_new_order', 'any', 20, 1 );
function any( $order_id ) {
	$order = wc_get_order( $order_id );
	error_log( 'Order ID: ' . $order_id . ' with status: ' . $order->get_status() );
}
```
2. Keep a tab open with `/wp-admin/tools.php?page=debug-log-manager` and be sure to clear the log before starting the test.

### Testing Steps
1. Clear the error log and go to WooCommerce > Orders and click "Add order"
2. Edit the new order and select "**Draft**" from the status dropdown.
3. Click "Create" and verify that "Created Order ID: xxx with status.. " IS NOT shown on the log manager.
4. Change the Order status again to `Completed` click `Update` and verify that "Created Order ID: xxx with status.. " IS shown on the log manager.
5. Clear the log
6. Make an order using the Checkout Blocks
7. Verify that "Created Order ID: xxx with status.. " IS shown on the log manager.
8. Go to `Admin` > `WooCommerce` > `Advanced` > `Features` and switch between Wordpress posts storage/High-performance order storage (depending on the previous choice). You might have to sync orders before doing so.
image

9. Repeat steps 1-8

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce/includes/data-stores/class-wc-order-data-store-cpt.php [hunk 1]
```diff
@@ -193,18 +193,34 @@ public function update( &$order ) {
 		// Update the order.
 		parent::update( $order );
 
-		// Fire a hook depending on the status - this should be considered a creation if it was previously draft status.
 		$new_status = $order->get_status( 'edit' );
 
-		if ( $new_status !== $previous_status && in_array( $previous_status, array( 'new', 'auto-draft', 'draft', 'checkout-draft' ), true ) ) {
+		// We need to remove the wc- prefix from the status for comparison and proper evaluation of new vs updated orders.
+		if ( strpos( $previous_status, 'wc-' ) === 0 ) {
+			$previous_status = substr( $previous_status, 3 );
```
Comment (mikejolley) [inline plugins/woocommerce/includes/data-stores/class-wc-order-data-store-cpt.php]: nit: `current_status` might be more understandable. We're looking at current status from the DB before the order object is updated.

File: plugins/woocommerce/includes/data-stores/class-wc-order-data-store-cpt.php [hunk 2]
```diff
@@ -193,18 +193,34 @@ public function update( &$order ) {
...
+		}
+
+		if ( strpos( $new_status, 'wc-' ) === 0 ) {
```
Comment (mikejolley) [inline plugins/woocommerce/includes/data-stores/class-wc-order-data-store-cpt.php]: The abstract order class has some code which removes prefix in the `set_status`  method. How about creating a utility method that this can share?

File: plugins/woocommerce/includes/data-stores/class-wc-order-data-store-cpt.php [hunk 3]
```diff
@@ -193,18 +193,34 @@ public function update( &$order ) {
...
+			$new_status = substr( $new_status, 3 );
+		}
+
+		$nonTriggeringOrderStatuses = array( 'new', 'auto-draft', 'draft', 'checkout-draft', 'refunded', 'failed', 'cancelled');
```
Comment (mikejolley) [inline plugins/woocommerce/includes/data-stores/class-wc-order-data-store-cpt.php]: Check your IDE is setup to show linting rules. This violates naming (snake_case is needed on the PHP side).

File: plugins/woocommerce/includes/data-stores/class-wc-order-data-store-cpt.php [hunk 4]
```diff
@@ -193,18 +193,34 @@ public function update( &$order ) {
...
+
+		// This hook should be fired only if the new status is not one of the non-triggering statuses and the previous status was one of the non-triggering statuses.
+		if (
+			$new_status !== $previous_status
+			&& ! in_array( $new_status, $nonTriggeringOrderStatuses, true )
+			&& in_array( $previous_status, $nonTriggeringOrderStatuses, true )
```
Comment (mikejolley) [inline plugins/woocommerce/includes/data-stores/class-wc-order-data-store-cpt.php]: Does this work reliably if creating a new order from scratch? The `$previous_status` comes from the database, so if the order does not exist in the database yet will this break?

File: plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableDataStore.php [hunk 5]
```diff
@@ -2621,8 +2621,15 @@ public function update( &$order ) {
...
-		// For backwards compatibility, moving a draft order to a valid status triggers the 'woocommerce_new_order' hook.
-		if ( ! empty( $changes['status'] ) && in_array( $previous_status, array( 'new', 'auto-draft', 'draft', 'checkout-draft' ), true ) ) {
+		$nonTriggeringOrderStatuses = array( 'new', 'auto-draft', 'draft', 'checkout-draft', 'refunded', 'failed', 'cancelled');
+
+		// For backwards compatibility, this hook should be fired only if the new status is not one of the non-triggering statuses and the previous status was one of the non-triggering statuses.
+		if (
+			! empty( $changes['status'] )
+			&& $changes['status'] !== $previous_status
+			&& ! in_array( $changes['status'], $nonTriggeringOrderStatuses, true )
+			&& in_array( $previous_status, $nonTriggeringOrderStatuses, true )
```
Comment (mikejolley) [inline plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableDataStore.php]: Looking at the code, in this context, a brand new unsaved order would have $previous_status set to `status`?

```
$previous_status = ArrayUtil::get_value_or_default( $order->get_data(), 'status' );
```

Thus this would break.

File: plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableDataStore.php [hunk 6]
```diff
@@ -2621,8 +2621,15 @@ public function update( &$order ) {
 		$order->apply_changes();
 		$this->clear_caches( $order );
 
-		// For backwards compatibility, moving a draft order to a valid status triggers the 'woocommerce_new_order' hook.
-		if ( ! empty( $changes['status'] ) && in_array( $previous_status, array( 'new', 'auto-draft', 'draft', 'checkout-draft' ), true ) ) {
+		$nonTriggeringOrderStatuses = array( 'new', 'auto-draft', 'draft', 'checkout-draft', 'refunded', 'failed', 'cancelled');
```
Comment (mikejolley) [inline plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableDataStore.php]: More snake_case issues.

File: plugins/woocommerce/tests/php/includes/data-stores/class-wc-order-data-store-cpt-test.php [hunk 7]
```diff
@@ -466,4 +466,50 @@ public function test_create_draft_order_doesnt_trigger_hook() {
...
+			++$new_count;
+		};
+
+		add_action( 'woocommerce_new_order', $callback );
+
+		$nonTriggeringOrderStatuses = array( 'checkout-draft', 'refunded', 'failed', 'cancelled' );
+
+		$order_data_store_cpt = new WC_Order_Data_Store_CPT();
+
+		$order = new WC_Order();
```
Comment (mikejolley) [inline plugins/woocommerce/tests/php/includes/data-stores/class-wc-order-data-store-cpt-test.php:485]: I would add another test case here to create a new order, set status to `processing` immediately, and update. It should trigger `woocommerce_new_order` but I suspect it will not until my other feedback is resolved.

File: plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableDataStore.php (hunk 5 above)
Comment (mikejolley) [reply plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableDataStore.php]: We could default the status to `new` is the order is not yet saved in DB.

**Review by mikejolley — CHANGES_REQUESTED** [review]
Added some questions and feedback r/e linting and new orders created manually without first creating a draft.

File: plugins/woocommerce/includes/data-stores/class-wc-order-data-store-cpt.php (hunk 1 above)
Comment (wavvves) [reply plugins/woocommerce/includes/data-stores/class-wc-order-data-store-cpt.php]: done in https://github.com/woocommerce/woocommerce/pull/49098/commits/146b14297abba200d644cfda31bd59a52ec059e0 👍🏼

File: plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableDataStore.php (hunk 5 above)
Comment (wavvves) [reply plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableDataStore.php]: The second arg is `$key`, this would actually return `null` as `$previous_status`. But what you say makes sense, an order that exists only in memory going from `null` status into one of the triggering status should trigger the new order hook!

Changed in https://github.com/woocommerce/woocommerce/pull/49098/commits/f0b4303eea5c00f9e47cf28acc54af531c40fb6f

File: plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableDataStore.php (hunk 6 above)
Comment (wavvves) [reply plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableDataStore.php]: https://github.com/woocommerce/woocommerce/pull/49098/commits/3f28c6b664885f7ee475803df85b1766eca56dc7

File: plugins/woocommerce/includes/data-stores/class-wc-order-data-store-cpt.php (hunk 3 above)
Comment (wavvves) [reply plugins/woocommerce/includes/data-stores/class-wc-order-data-store-cpt.php]: It is highlighting, I don't know what glitch got into it or my brain 🫠
Changed in https://github.com/woocommerce/woocommerce/pull/49098/commits/3f28c6b664885f7ee475803df85b1766eca56dc7

File: plugins/woocommerce/includes/data-stores/class-wc-order-data-store-cpt.php (hunk 2 above)
Comment (wavvves) [reply plugins/woocommerce/includes/data-stores/class-wc-order-data-store-cpt.php]: Good call, added in https://github.com/woocommerce/woocommerce/commit/8b50abaf6bd7e9f48540559799752e562f75b5db and replaced a few other places in the code that was doing the same thing 👍🏼

File: plugins/woocommerce/includes/data-stores/class-wc-order-data-store-cpt.php (hunk 4 above)
Comment (wavvves) [reply plugins/woocommerce/includes/data-stores/class-wc-order-data-store-cpt.php]: We can implement a similar solution to what you suggested with HPOS. In this case, the `$previous_status` will be `false` if it fails to retrieve it from the database. By setting it to `new,` we can correctly trigger the hook if it lands outside the non-triggering statuses. Do you agree?

```php
// Also grab the current status so we can compare.
$previous_status = get_post_status( $order->get_id() );
// If the order doesn't exist in the DB, we will consider it as new.
if ( ! $previous_status ) {
    $previous_status = 'new';
}
```

I added this in https://github.com/woocommerce/woocommerce/pull/49098/commits/b733fa699ea423b3262b80d818519dc7d3dbd7b4 Let me know what you think

File: plugins/woocommerce/tests/php/includes/data-stores/class-wc-order-data-store-cpt-test.php (hunk 7 above)
Comment (wavvves) [reply plugins/woocommerce/tests/php/includes/data-stores/class-wc-order-data-store-cpt-test.php:485]: Like this https://github.com/woocommerce/woocommerce/pull/49098/commits/4848866e2089c2fd58af3f4e5c937150b996bcff ?

Comment (mikejolley) [reply plugins/woocommerce/tests/php/includes/data-stores/class-wc-order-data-store-cpt-test.php:485]: Yes 👍🏻

**Review by mikejolley — APPROVED** [review]
Changes since last review look good. Thanks for taking care of those improvements. Since tests are green I think you're good to go.

**Comment by wavvves** [comment]
> Changes since last review look good. Thanks for taking care of those improvements. Since tests are green I think you're good to go.

Thanks Mike! I just wait for a look by Proton before merging 👍🏼 cc/ @vedanshujain

File: plugins/woocommerce/includes/data-stores/class-wc-order-data-store-cpt.php [hunk 8]
```diff
@@ -189,22 +191,37 @@ public function update( &$order ) {
 
 		// Also grab the current status so we can compare.
 		$previous_status = get_post_status( $order->get_id() );
+		// If the order doesn't exist in the DB, we will consider it as new.
+		if ( ! $previous_status ) {
```
Comment (vedanshujain) [inline plugins/woocommerce/includes/data-stores/class-wc-order-data-store-cpt.php]: get_post_status can be false when there's a intermittent DB issue, and not necessarily if the post does not exist. A better check for not existing in DB is to check fo `$order->get_id() > 0`

File: plugins/woocommerce/includes/data-stores/class-wc-order-data-store-cpt.php [hunk 9]
```diff
@@ -189,22 +191,37 @@ public function update( &$order ) {
...
 
-		if ( $new_status !== $previous_status && in_array( $previous_status, array( 'new', 'auto-draft', 'draft', 'checkout-draft' ), true ) ) {
-			do_action( 'woocommerce_new_order', $order->get_id(), $order );
-		} else {
-			do_action( 'woocommerce_update_order', $order->get_id(), $order );
+		// We need to remove the wc- prefix from the status for comparison and proper evaluation of new vs updated orders.
+		$previous_status = OrderUtil::remove_status_prefix( $previous_status );
+		$current_status  = OrderUtil::remove_status_prefix( $current_status );
+
+		$non_triggering_order_statuses = array( 'new', 'auto-draft', 'draft', 'checkout-draft', 'refunded', 'failed', 'cancelled' );
```
Comment (vedanshujain) [inline plugins/woocommerce/includes/data-stores/class-wc-order-data-store-cpt.php]: can you add the justification for adding `'refunded', 'failed', 'cancelled'` here, I don't think we were doing this before?

**Review by vedanshujain — COMMENTED** [review]
Added a questions around new status before we can merge

File: plugins/woocommerce/includes/data-stores/class-wc-order-data-store-cpt.php (hunk 9 above)
Comment (wavvves) [reply plugins/woocommerce/includes/data-stores/class-wc-order-data-store-cpt.php]: Removing these as, after discussion, the conclusion was each order ID should trigger one new order event 👍🏼

Comment (wavvves) [reply plugins/woocommerce/includes/data-stores/class-wc-order-data-store-cpt.php]: https://github.com/woocommerce/woocommerce/pull/49098/commits/1175b38586a630bedc6bd969dde03e57adf3a610

File: plugins/woocommerce/includes/data-stores/class-wc-order-data-store-cpt.php (hunk 8 above)
Comment (wavvves) [reply plugins/woocommerce/includes/data-stores/class-wc-order-data-store-cpt.php]: could this be `( ! $previous_status && $order->get_id() === 0 )` or is it too redundant? Since we have the bool already, it would be quick to evaluate and save the `get_id()` call.
We're only changing order status in a non-persistent way here to allow the triggering of the hook, as per Mike's comment

Comment (wavvves) [reply plugins/woocommerce/includes/data-stores/class-wc-order-data-store-cpt.php]: I added the check on https://github.com/woocommerce/woocommerce/pull/49098/commits/1ab534aabc39613aa8f21e872a0b3087b2b2c0d0 in case you are onboard with it and decide to approve 👍🏼

**Review by vedanshujain — APPROVED** [review]
LGTM! Code looks good and verified hooks with sync enabled on both HPOS and posts data store. Note that I also updated the snippet in testing instruction to handle both posts and HPOS.
