### PR TITLE
Check if terms is an array before calling array_shift. 

### LINKED ISSUE #55102: [Fatal] PHP Fatal error:  Uncaught TypeError: array_shift(): Argument #1 ($array) must be of type array, WP_Error given in | class-wc-brands.php:187
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

witnessed in `9.6.0`

[link to code](https://github.com/woocommerce/woocommerce/blob/6f5032a0277a0eb006a442407d9d09c0c370b8be/plugins/woocommerce/includes/class-wc-brands.php#L187)

```
PHP Fatal error:  Uncaught TypeError: array_shift(): Argument #1 ($array) must be of type array, WP_Error given in /../plugins/woocommerce/9.6.0/includes/class-wc-brands.php:187
Stack trace:
#0 /../plugins/woocommerce/9.6.0/includes/class-wc-brands.php(187): array_shift(Object(WP_Error))
#1 /../core/6.7.1/wp-includes/class-wp-hook.php(326): WC_Brands->post_type_link('https://971nerd...', Object(WP_Post))
#2 /../core/6.7.1/wp-includes/plugin.php(205): WP_Hook->apply_filters('https://971nerd...', Array)
#3 /../core/6.7.1/wp-includes/link-template.php(375): apply_filters('post_type_link', 'https://971nerd...', Object(WP_Post), false, false)
#4 /../core/6.7.1/wp-includes/link-template.php(201): get_post_permalink(Object(WP_Post), false, false)
#5 /../core/6.7.1/wp-includes/link-template.php(500): get_permalink(Object(WP_Post))
#6 /../core/6.7.1/wp-includes/link-template.php(199): get_attachment_link(Object(WP_Post), false)
#7 /../plugins/jetpack/14.3-a.5/jetpack_vendor/automattic/jetpack-sync/src/modules/class-posts.php(596): get_permalink(Object(WP_Post))
#8 [internal function]: Automattic\Jetpack\Sync\Modules\Posts->filter_post_content_and_add_links(Object(WP_Post))
#9 /../plugins/jetpack/14.3-a.5/jetpack_vendor/automattic/jetpack-sync/src/modules/class-posts.php(899): array_map(Array, Array)
#10 /../plugins/jetpack/14.3-a.5/jetpack_vendor/automattic/jetpack-sync/src/modules/class-posts.php(878): Automattic\Jetpack\Sync\Modules\Posts->expand_posts(Array)
#11 /../plugins/jetpack/14.3-a.5/jetpack_vendor/automattic/jetpack-sync/src/modules/class-module.php(397): Automattic\Jetpack\Sync\Modules\Posts->get_next_chunk(1, Array, 100)
#12 /../plugins/jetpack/14.3-a.5/jetpack_vendor/automattic/jetpack-sync/src/modules/class-full-sync-immediately.php(396): Automattic\Jetpack\Sync\Modules\Module->send_full_sync_actions(1, Array, 1738367851.5746)
#13 /../plugins/jetpack/14.3-a.5/jetpack_vendor/automattic/jetpack-sync/src/modules/class-full-sync-immediately.php(374): Automattic\Jetpack\Sync\Modules\Full_Sync_Immediately->send()
#14 /../plugins/jetpack/14.3-a.5/jetpack_vendor/automattic/jetpack-sync/src/modules/class-full-sync-immediately.php(340): Automattic\Jetpack\Sync\Modules\Full_Sync_Immediately->continue_sending()
#15 /../plugins/jetpack/14.3-a.5/jetpack_vendor/automattic/jetpack-sync/src/class-sender.php(348): Automattic\Jetpack\Sync\Modules\Full_Sync_Immediately->continue_enqueuing()
#16 /../plugins/jetpack/14.3-a.5/jetpack_vendor/automattic/jetpack-sync/src/class-sender.php(315): Automattic\Jetpack\Sync\Sender->continue_full_sync_enqueue()
#17 /../core/6.7.1/wp-includes/class-wp-hook.php(324): Automattic\Jetpack\Sync\Sender->do_full_sync('')
#18 /../core/6.7.1/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(Object(WP_Error), Array)
#19 /../core/6.7.1/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#20 /../core/6.7.1/wp-includes/load.php(1279): do_action('shutdown')
#21 [internal function]: shutdown_action_hook()
#22 {main}
  thrown in /../plugins/woocommerce/9.6.0/includes/class-wc-brands.php on line 187
``` 

### Expected behavior

no fatals witnessed

### Actual behavior

fatals were witnessed

### Steps to reproduce

We don't have steps to reproduce, but observed 80 instances of this problem on Fri Jan 31, 2025 across 1 site. Hopefully, someone can dig in and apply a defensive check if appropriate. - To be updated after investigation

### WordPress Environment

N/A

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by rawdreeg**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

An `array_shift()` throws a Fatal Error because we assume that get_terms will always return an array or an empty value. This PR adds in a check to ensure that `$terms` is an array before calling `array_shift()`. I also added a check to confirm the value assigned to `$first_term` is indeed a WP_Term ( This should cover arrays of strings, for example ).

Closes #55102.

### How to test the changes in this Pull Request:

A way to reproduce:
1. Go to Products > Brands and create a brand. And assign it to a product.
2. Go to Settings > Permalinks and in `Product permalinks` select `Custom base` and add `/product/%product_brand%/`.
3. Add this temporary filter to make the `get_the_terms` function return an error.
```php
add_filter(
	'get_the_terms',
	function ( $terms, $post_id, $taxonomy ) {
		if ($taxonomy == 'product_brand') {
			return "Nothing to see here";
		}
		return $terms;
	}, 
	10, 
	3
);
```
4. Open the product page with the brands assigned ( Step 2 ) and confirm there's no fatal error

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 
Check if $terms is an array before calling array_shift to prevent fatal errors.

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce/includes/class-wc-brands.php [hunk 1]
```diff
@@ -183,13 +183,13 @@ public function post_type_link( $permalink, $post ) {
...
 		$terms = get_the_terms( $post->ID, 'product_brand' );
 
-		if ( empty( $terms ) ) {
-			// If no terms are assigned to this post, use a string instead (can't leave the placeholder there).
-			$product_brand = _x( 'uncategorized', 'slug', 'woocommerce' );
-		} else {
-			// Replace the placeholder rewrite tag with the first term's slug.
-			$first_term    = array_shift( $terms );
-			$product_brand = $first_term->slug;
+		$product_brand = _x( 'uncategorized', 'slug', 'woocommerce' );
```
Comment (budzanowski) [inline plugins/woocommerce/includes/class-wc-brands.php:187]: Please consider retaining the comment. The bit about the placeholder sounds like it has some value.

Comment (rawdreeg) [reply plugins/woocommerce/includes/class-wc-brands.php:187]: Thanks. I added it back here 2426d36911073f0c33086ad11616fb9757b77c94 and here f3351e1c737f4ccb85ffff68fbbed7aa1cf3bfc3

**Review by budzanowski — APPROVED** [review]
