### PR TITLE
Show correct heading for billing address when Local Pickup is selected

### LINKED ISSUE #58213: Block Checkout Heading
**Describe the bug**

When you enable the **Force shipping to the customer billing address** setting and select local pickup, the heading for the address section says "Billing and shipping address" which is misleading as this is only a billing address in this context.

## **To Reproduce**

1. Go to WC > Settings > Shipping > Shipping options
2. Enable **Force shipping to the customer billing address**
3. Enable Local Pickup
4. Go to block checkout with something in your cart
5. Select Local Pickup

## **Expected behavior**

The heading should only say "Billing Address".

## Environment

Please fill out any of the below that applies

**Operating System/Device**

- [ ] Windows
- [ ] MacOS
- [ ] Linux
- [ ] iPhone
- [ ] Samsung
- [ ] Other (add in additional context field)

**Version:** 

**Browser**

- [ ] Desktop Edge
- [ ] Desktop Chrome/Chromium
- [ ] Desktop Safari
- [ ] Mobile Edge
- [ ] Mobile Chrome/Chromium
- [ ] Mobile Safari
- [ ] Other (add in additional context field)

**Version:** 

## **Additional context**

N/A

### PR DESCRIPTION
**Pull request by BurakParsAydin**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes #58213  .

(For Bug Fixes) Bug introduced in PR # .

### Screenshots or screen recordings:

Screenshot from 2025-05-23 00-33-43

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

### How to test the changes in this Pull Request

1. **Enable Local Pickup**
   - Go to `WooCommerce > Settings > Shipping`.
   - Create a Shipping Zone if one doesn’t exist.
   - Add a **Local Pickup** method to the zone.

2. **Enable "Force shipping to the customer billing address"**
   - Go to `WooCommerce > Settings > Shipping > Shipping destination`.
   - Enable the checkbox: **"Force shipping to the customer billing address"**.
   - Save the settings.

3. **Navigate to Checkout**
   - Add any product to the cart.

4. **Verify heading behavior**
   - Select a shipping method (e.g., **Ship**):
     -  The address heading should read: **"Billing and shipping address"**.
   - Switch to **Local Pickup**:
     -  The heading should update to: **"Billing address"** only.

This ensures the heading accurately reflects the actual checkout scenario.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [x] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 
Fix - Show 'Billing address' instead of 'Billing and shipping address' when Local Pickup is selected and shipping is forced to the billing address.
</details>

### CODE REVIEW

**Comment by opr** [comment]
Hi, I'll be AFK until 20th February, and due to capacity constraints it's not likely this will be reviewed before then, so I appreciate your patience and I will review when I get back.

File: plugins/woocommerce/client/blocks/assets/js/blocks/checkout/inner-blocks/checkout-billing-address-block/frontend.tsx [hunk 1]
```diff
@@ -37,14 +40,27 @@ const FrontendBlock = ( {
...
 		useCheckoutAddress();
 
+	const { shippingRates } = useShippingData();
+
+	const hasSelectedLocalPickup = shippingRates.some( ( pkg ) =>
+		pkg.shipping_rates.some(
+			( rate ) => rate.method_id === 'pickup_location' && rate.selected
+		)
+	);
+
```
Comment (senadir) [inline plugins/woocommerce/client/blocks/assets/js/blocks/checkout/inner-blocks/checkout-billing-address-block/frontend.tsx]: This check is insufficient because not all local pickup methods are `pickup_location`, and is also redundant. Use `hasSelectedLocalPickup` from `useShippingData` directly.

**Review by senadir — APPROVED** [review]
