### PR TITLE
Fix: Core reports an out of date template for blocks themes from Core itself

### LINKED ISSUE #61277: Core reports an out of date template for blocks themes from Core itself
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

With a default installation of WooCommerce Core (10.2.2) and a default block theme (or any) block theme active, Core reports an out of date template which appears to be from Core itself:

Image

### Expected behavior

Included blocks templates should be up to date.

### Actual behavior

Reported out of date template:

```
/var/www/html/wp-content/plugins/woocommerce/templates/block-notices/error.php,
/var/www/html/wp-content/plugins/woocommerce/templates/block-notices/notice.php version 9.5.0 is out of date. The core version is 10.2.0,
/var/www/html/wp-content/plugins/woocommerce/templates/block-notices/success.php
```

### Steps to reproduce

1. Spin up a test site using WooCommerce 10.2.2
2. Install and activate any block theme, such as Twenty Twenty-Five
3. Navigate to the WooCommerce > Status page
4. Scroll to the templates section
5. Note it warns about an out of date template

### WordPress Environment

<details>

<summary>WordPress Environment</summary>

`
### WordPress Environment ###

WordPress address (URL): http://localhost:8882
Site address (URL): http://localhost:8882
WC Version: 10.2.2
Legacy REST API Package Version: The Legacy REST API plugin is not installed on this site.
Action Scheduler Version: ✔ 3.9.3
Log Directory Writable: ✔
WP Version: 6.8.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: PHP.wasm
Server Architecture: Emscripten 4.0.5 wasm32
PHP Version: 8.4.0-dev
PHP Post Max Size: 2 GB
PHP Time Limit: 0
PHP Max Input Vars: 1000
cURL Version: 7.69.1
OpenSSL/1.1.1t

SUHOSIN Installed: –
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 10.2.2
WC Database Prefix: wp_
Total Database Size: 0.00MB
Database Data Size: 0.00MB
Database Index Size: 0.00MB
wp_woocommerce_sessions: Data: 0.00MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.00MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.00MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.00MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.00MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_log: Data: 0.00MB + Index: 0.00MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.00MB + Index: 0.00MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.00MB + Index: 0.00MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.00MB + Index: 0.00MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.00MB + Index: 0.00MB + Engine InnoDB
wp_commentmeta: Data: 0.00MB + Index: 0.00MB + Engine InnoDB
wp_comments: Data: 0.00MB + Index: 0.00MB + Engine InnoDB
wp_links: Data: 0.00MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 0.00MB + Index: 0.00MB + Engine InnoDB
wp_postmeta: Data: 0.00MB + Index: 0.00MB + Engine InnoDB
wp_posts: Data: 0.00MB + Index: 0.00MB + Engine InnoDB
wp_term_relationships: Data: 0.00MB + Index: 0.00MB + Engine InnoDB
wp_term_taxonomy: Data: 0.00MB + Index: 0.00MB + Engine InnoDB
wp_termmeta: Data: 0.00MB + Index: 0.00MB + Engine InnoDB
wp_terms: Data: 0.00MB + Index: 0.00MB + Engine InnoDB
wp_usermeta: Data: 0.00MB + Index: 0.00MB + Engine InnoDB
wp_users: Data: 0.00MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.00MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.00MB + Index: 0.00MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.00MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.00MB + Index: 0.00MB + Engine InnoDB
wp_wc_download_log: Data: 0.00MB + Index: 0.00MB + Engine InnoDB
wp_wc_order_addresses: Data: 0.00MB + Index: 0.00MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.00MB + Index: 0.00MB + Engine InnoDB
wp_wc_order_operational_data: Data: 0.00MB + Index: 0.00MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.00MB + Index: 0.00MB + Engine InnoDB
wp_wc_order_stats: Data: 0.00MB + Index: 0.00MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.00MB + Index: 0.00MB + Engine InnoDB
wp_wc_orders: Data: 0.00MB + Index: 0.00MB + Engine InnoDB
wp_wc_orders_meta: Data: 0.00MB + Index: 0.00MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.00MB + Index: 0.00MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.00MB + Index: 0.00MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.00MB + Index: 0.00MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.00MB + Index: 0.00MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.00MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.00MB + Index: 0.00MB + Engine InnoDB
wp_wc_webhooks: Data: 0.00MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

attachment: 1
page: 7
post: 2
product: 1
revision: 1
wp_navigation: 1

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 10.2.2

### Dropin Plugins () ###

db.php: SQLite integration (Drop-in)

### Settings ###

Legacy API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –
Enabled Features: analytics
marketplace
order_attribution
site_visibility_badge
remote_logging
email_improvements
blueprint
point_of_sale
custom_order_tables

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 310 KB

### WC Pages ###

Shop base: #7 - /shop/
Cart: #8 - /cart/ -  Contains the woocommerce/cart block
Checkout: #9 - /checkout/ -  Contains the woocommerce/checkout block
My account: #10 - /my-account/ -  Contains the [woocommerce_my_account] shortcode
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty-Five
Version: 1.3
Author URL: https://wordpress.org
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
Theme type: Block theme
WooCommerce Support: ❌ Not declared

### Templates ###

Overrides: /var/www/html/wp-content/plugins/woocommerce/templates/block-notices/error.php
/var/www/html/wp-content/plugins/woocommerce/templates/block-notices/notice.php version 9.5.0 is out of date. The core version is 10.2.0
/var/www/html/wp-content/plugins/woocommerce/templates/block-notices/success.php

Outdated Templates: ❌
					
					
						Learn how to update					 |
					
						
					
					
						Clear system status theme info cache

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
onboarding
onboarding-tasks
pattern-toolkit-full-composability
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
printful
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page
launch-your-store

Disabled Features: product-data-views
experimental-blocks
experimental-iapi-mini-cart
experimental-iapi-runtime
coming-soon-newsletter-template
minified-js
product-pre-publish-modal
settings
async-product-editor-category-field
product-editor-template-system
use-wp-horizon
experimental-wc-rest-api

Daily Cron: ❌ Not scheduled
Options: ✔
Notes: 55
Onboarding: skipped

### Action Scheduler ###

Pending: 10
Oldest: 2025-09-30 11:38:12 +0000
Newest: 2025-09-30 11:45:29 +0000

### Status report information ###

Generated at: 2025-10-06 11:51:04 +00:00
`

</details>

### Isolating the problem

- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by dinhtungdu**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

This PR fixes the outdated template report for the block notice template, which internally overrides the legacy template itself. Therefore, we have to manually keep their versions synced.

Closes #61277

### Screenshots or screen recordings:

| Before | After '
|-|-|
| image | image |

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Use a block theme without any custom template.
2. Open System Status Report.
3. See the Templates Overrides section.
4. See no outdated report.
5. Try clearing the theme info cache if you still see the outdated template.

### CODE REVIEW

File: plugins/woocommerce/templates/notices/notice.php [hunk 1]
```diff
@@ -12,7 +12,7 @@
  *
  * @see     https://woocommerce.com/document/template-structure/
  * @package WooCommerce\Templates
- * @version 10.2.0
+ * @version 10.4.0
```
Comment (Aljullu) [inline plugins/woocommerce/templates/notices/notice.php:15]: Should we add a comment here mentioning this version needs to be kept in sync with the other file? Otherwise, I worry this issue might happen again in the future.

**Review by Aljullu — APPROVED** [review]
LGTM, thanks for investigating this issue, @dinhtungdu! I left one minor suggestion about adding a comment, but not a blocker, so approving. :shipit: 

Before | After
--- | ---
Image | Image

File: plugins/woocommerce/templates/notices/notice.php (hunk 1 above)
Comment (dinhtungdu) [reply plugins/woocommerce/templates/notices/notice.php:15]: My only concern with adding a comment is that it creates more noise for developers who copy this template for overriding. In my opinion, we can accept that situation given the frequency with which these templates are updated. WDYT?

Comment (Aljullu) [reply plugins/woocommerce/templates/notices/notice.php:15]: Oh, good point. Let's leave it as-is, I agree. :+1:

Comment (Aljullu) [reply plugins/woocommerce/templates/notices/notice.php:15]: In the future we could consider adding tests for this. Simply testing that in a fresh WC install the outdated templates message has no warnings.

Comment (dinhtungdu) [reply plugins/woocommerce/templates/notices/notice.php:15]: We can do it now, I added a unit test to énure the version between notice templates are matched.
