### PR TITLE
Analytics and Product CSV export: allow negative numeric values to be left unescaped to fix CSV output

### LINKED ISSUE #53020: CSV export PHP: Unnecessary escaping of negative numbers is preventing numerical analysis in spreadsheets
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

> [!IMPORTANT]  
> This is the same issue as described in #25379 which is for JS-based exporting via `@woocommerce/csv-export`. This issue is for the PHP-based CSV exporting from WC → Analytics.

When you export CSV data from Analytics using the built-in CSV export tool, an apostrophe `'` is prepended to any negative quantities. As a result, negative numbers prefixed with `'` (e.g., `'-42`) forces users to manually edit exports for numeric operations, like summing values in Google Sheets.

The `'` prefix is intended to prevent CSV Injection, but is not required for purely numeric values. String values that could pose CSV Injection risks will continue to be escaped.

https://github.com/woocommerce/woocommerce/blob/fd16dc0644d0b7476c751b26e41bbc6b87c4c072/plugins/woocommerce/includes/export/abstract-wc-csv-exporter.php#L354-L380

**Example Scenario:**

In an exported CSV, a value like `'-42` is treated as text, so functions like `SUM()` fail unless users manually strip the prefix. Example WC → Analytics → Stock CSV opened in Google Sheets:

google-sheets

### Expected behavior

Negative numeric values (e.g. `-42`) should be left unescaped in the exported CSV, whilst string values prepended with a dangerous `-` character (e.g. `"-42+dangerousformula"`) should remain escaped.

### Actual behavior

Negative numeric values (e.g. `-42`) are escaped (prepended with a `'` character in the exported CSV.

### Steps to reproduce

1. In WP Admin, modify the stock of one or more of your products to a negative value
3. Navigate to **Analytics → Stock**. 
4. Ensure there are more pages than are visible by appending the URL query string `&per_page=1`
5. Click download to export a CSV and it will be emailed to your WP user's email address.
6. Opening the CSV in Excel, Numbers, LibreOffice or Google Sheets.
	- Notice that negative values are prepended by `'`, making them unusable for numeric calculations, e.g. `SUM()`.
		numbers-csv-trunk

### WordPress Environment

<details><summary>System Status Report</summary>

```
### WordPress Environment ###

WordPress address (URL): [Redacted]
Site address (URL): [Redacted]
WC Version: 9.4.2
Legacy REST API Package Version: The Legacy REST API plugin is not installed on this site.
Action Scheduler Version: ✔ 3.8.2
Log Directory Writable: ✔
WP Version: 6.7
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 8.1.30
PHP Post Max Size: 2 GB
PHP Time Limit: 850
PHP Max Input Vars: 6144
cURL Version: 8.10.1
OpenSSL/1.1.1w

SUHOSIN Installed: –
MySQL Version: 10.6.18-MariaDB-log
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

[REDACTED]

### Post Type Counts ###

attachment: 23
page: 8
post: 1
product: 29
product_variation: 15
revision: 4
shop_order: 157
shop_order_refund: 16
shop_subscription: 29
wp_global_styles: 2
wp_navigation: 1
wp_template: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (9) ###

Akismet Anti-spam: Spam Protection: by Automattic - Anti-spam Team – 5.3.5
Jetpack Beta Tester: by Automattic – 4.1.0
Jetpack: by Automattic – 14.1-a.3
Query Monitor: by John Blackbourn – 3.16.4
WooCommerce Payments Dev Tools: by Automattic –
WooPayments: by WooCommerce – 8.0.2 (update to version 8.5.0 is available)
Woo Subscriptions: by WooCommerce – 6.0.0 (update to version 6.9.0 is available)
WooCommerce: by Automattic – 9.4.2
WP Console: by Edi Amin – 2.5.0

### Inactive Plugins (7) ###

Pressable Maintenance Mode: by Pressable – 1.0.2
SQL Buddy: by Delicious Brains – 1.0.0
WooCommerce Blocks: by Automattic – 11.7.0
WooCommerce PDF Invoices: by Andrew Benbow – 4.15.4 (update to version 5.0.7 is available)
WooCommerce Stripe Gateway: by Stripe – 8.9.0
WooCommerce Subscriptions Gifting: by WooCommerce – 2.5.0 (update to version 2.9.0 is available)
YITH WooCommerce Product Bundles Premium: by YITH – 1.13.0

### Dropin Plugins () ###

advanced-cache.php: advanced-cache.php
db.php: Query Monitor Database Class (Drop-in)
object-cache.php: Memcached

### Settings ###

Legacy API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)
yith_bundle (yith_bundle)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 454 B

### WC Pages ###

Shop base: #5 - /shop/
Cart: #6 - /cart/ -  Contains the [woocommerce_cart] shortcode
Checkout: #7 - /checkout/ -  Contains the [woocommerce_checkout] shortcode
My account: #8 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 4.2.0 (update to version 4.6.0 is available)
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### WooPayments ###

Version: 8.0.2
Connected to WPCOM: Yes
WPCOM Blog ID: 202877349
Account ID: acct_1KTaXO2HhVprjHvj
Payment Gateway: Enabled
Test Mode: Enabled
Enabled APMs: card
WooPay: Not eligible
Apple Pay / Google Pay: Enabled (product,cart,checkout)
Fraud Protection Level: basic
Multi-currency: Enabled
Auth and Capture: Enabled
Documents: Disabled
Logging: Disabled

### Subscriptions ###

WCS_DEBUG: ✔ No
Subscriptions Mode: ✔ Live
Subscriptions Live URL: https://ej-woo.mystagingwebsite.com
Subscriptions-core Library Version: 6.8.0
Subscription Statuses: wc-on-hold: 20
wc-cancelled: 9

WooCommerce Account Connected: ❌ No
Custom Retry Rules: ✔ No
Custom Retry Rule Class: ✔ No
Custom Raw Retry Rule: ✔ No
Custom Retry Rule: ✔ No
Retries Migration Status: ✔ Completed
Report Cache Enabled: ✔ Yes
Cache Update Failures: ✔ 0 failure

### Store Setup ###

Country / State: United States (US) — Alabama

### Subscriptions by Payment Gateway ###

other: wc-cancelled: 1
wc-on-hold: 1

WooPayments: wc-cancelled: 8
wc-on-hold: 19


### Payment Gateway Support ###

WooPayments: products
refunds
multiple_subscriptions
subscription_cancellation
subscription_payment_method_change_admin
subscription_payment_method_change_customer
subscription_payment_method_change
subscription_reactivation
subscription_suspension
subscriptions
subscription_amount_changes
subscription_date_changes
tokenization
add_payment_method

Cash on delivery: products

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
pattern-toolkit-full-composability
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
printful
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page
launch-your-store

Disabled Features: product-data-views
experimental-blocks
minified-js
product-pre-publish-modal
settings
async-product-editor-category-field
product-editor-template-system
blueprint
reactify-classic-payments-settings
use-wp-horizon

Daily Cron: ✔ Next scheduled: 2024-11-21 06:09:08 +02:00
Options: ✔
Notes: 171
Onboarding: completed

### Action Scheduler ###

Canceled: 2
Oldest: 2024-11-19 01:29:12 +0200
Newest: 2024-11-19 04:14:03 +0200

Complete: 101
Oldest: 2024-10-21 10:04:48 +0300
Newest: 2024-11-21 07:24:57 +0200

Failed: 173
Oldest: 2022-03-21 06:18:14 +0200
Newest: 2024-08-22 13:47:05 +0300

Pending: 4
Oldest: 2024-11-21 07:25:23 +0200
Newest: 2024-11-22 01:16:59 +0200


### Status report information ###

Generated at: 2024-11-21 07:25:32 +02:00
```
</details>

### Isolating the problem

- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by Jinksi**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes #53020

**Summary**

This PR stops escaping negative numeric values in CSV exports (Analytics and Product export), improving usability for users who rely on numeric data handling in spreadsheets. String values that could pose CSV Injection risks will continue to be escaped.

**Problem addressed**

When exporting from Analytics, we currently escape cell values that start with `-` to prevent CSV Injection, even for numeric values. As a result, negative numbers are prefixed with `'` (e.g., `'-42`), forcing users to manually edit exports for numeric operations, like summing values in Google Sheets.

**Example Scenario:**

In an exported CSV, a value like `'-42` is treated as text, so functions like `SUM()` fail unless users manually strip the prefix. Example WC → Analytics → Stock CSV opened in Google Sheets:

google-sheets

**Solution**

This PR improves usability by allowing negative numeric values to be exported unescaped while still escaping strings that could trigger formula evaluation in spreadsheets:

```php
$num = -42; // Allow unescaped as it's a number

// The following string representations could be problematic and will still be escaped
$riskyStrings = [
    "-42+cmd|' /C calc'!A0", // Command injection attempt
    "=-42", // Formula
    "=SUM(-42)", // Function call
    "@-42"  // Macro/reference syntax
];
```

> [!IMPORTANT]  
> This change affects the PHP-based CSV export used in WC → Analytics.
> The same issue for JS-based CSV export in `@woocommerce/csv-export` is being addressed in #52727

### How to test the changes in this Pull Request:

1. In WP Admin, modify the stock of one or more of your products to a negative value
3. Navigate to **Analytics → Stock**. 
4. Ensure there are more pages than are visible by appending the URL query string `&per_page=1`
5. Click download to export a CSV and it will be emailed to your WP user's email address.
6. Opening the CSV in Excel, Numbers, LibreOffice or Google Sheets.
	- Ensure that negative values are not prepended by `'`.
		numbers-csv-trunk
3. Navigate to **Products** and click **Export** to generate a CSV of products
4. Opening the CSV in Excel, Numbers, LibreOffice or Google Sheets
    - Ensure that negative values are not prepended by `'`.

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

Improved Analytics and Product CSV export usability by allowing negative numeric values to be unescaped while continuing to escape potentially risky strings to prevent CSV Injection (async, PHP-based CSV exporting).

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce/includes/export/abstract-wc-csv-exporter.php [hunk 1]
```diff
@@ -372,6 +375,11 @@ public function escape_data( $data ) {
 		// 0x0d: Carriage Return (\r)
 		$active_content_triggers = array( '=', '+', '-', '@', chr( 0x09 ), chr( 0x0d ) );
 
+		// Don't escape pure numeric values since they cannot form a valid formula to be injected.
+		if ( is_int( $data ) || is_float( $data ) ) {
```
Comment (brucealdridge) [inline plugins/woocommerce/includes/export/abstract-wc-csv-exporter.php:379]: `is_int` and `is_float` will fail for string values. Depending on how the data is stored, there is a good chance that numeric values are `string` here. `is_numeric` may be better as it checks for numeric values in strings as well as `int`/`float`

The first example in the phpdocs seems to allow everything we'd want to accept while refusing anything problematic.

**Review by brucealdridge — APPROVED** [review]
Changes look good but might be too strict in some cases.
I haven't tested the changes.

**Comment by brucealdridge** [comment]
> I haven't tested the changes.

✅ Tested negative stock with the playground.

```
... eifend leo.",,,taxable,,0,-7,,0,0,,,,,1,, ...
```

Note: Playground is awesome. It took a couple of minutes to start, import products, adjust stock and export.

File: plugins/woocommerce/includes/export/abstract-wc-csv-exporter.php (hunk 1 above)
Comment (Jinksi) [reply plugins/woocommerce/includes/export/abstract-wc-csv-exporter.php:379]: Manually testing seems to show that the data we care about (Product data, Analytics data) is stored as a pure numeric value (int or float). I'm happy to err on the side of caution with this PR and only allow int/float since it solves our immediate problem and remains "air-tight". 

Also, this is what we're doing with JS-based CSV export in #52727, so we should see consistent output.

If we do see escaped string-numeric values becoming an issue in the future, we can make this less strict, or perhaps prepare the data as int/float prior to escaping.

**Review by ecgan — APPROVED** [review]
Tested, working as expected. LGTM 🙂 👍

**Comment by Jinksi** [comment]
Closing and re-opening to trigger CI run, required for merge.
