### PR TITLE
Fix `InboxNoteActionButton` component regression

### LINKED ISSUE #54488: Admin note action button of type link no longer works
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

During the testing of WooPayments `8.8.0-test-3`, it was discovered that some of our admin notes were no longer working: https://github.com/Automattic/woocommerce-payments/issues/10148

Apparently, this is a regression introduced in WooCommerce `9.7.0-dev`, where the note CTA is only rendered as a `<button>`, e.g:

```html
<button type="button" class="components-button woocommerce-inbox-note__action-button is-secondary">
	<span>Set up now</span>
</button>
```

Whereas before `9.7.0-dev`, it can be rendered as an `<a>` tag:

```html
<a href="https://website-url.test/wp-admin/admin.php?page=wc-admin&amp;path=/payments/multi-currency-setup" class="components-button woocommerce-inbox-note__action-button is-secondary">
	<span>Set up now</span>
</a>
```

### Expected behavior

Admin note CTA should be rendered as a link as well.

### Actual behavior

Admin note action button is only rendered as a `<button>`.

### Steps to reproduce

Steps to reproduce: https://github.com/Automattic/woocommerce-payments/issues/10148.

### WordPress Environment

<details><summary>System Status Report</summary>

```
### WordPress Environment ###

WordPress address (URL): [Redacted]
Site address (URL): [Redacted]
WC Version: 9.7.0-dev
Legacy REST API Package Version: The Legacy REST API plugin is not installed on this site.
Action Scheduler Version: ✔ 3.9.0
Log Directory Writable: ✔
WP Version: 6.7.1
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 8.3.15
PHP Post Max Size: 2 GB
PHP Time Limit: 850
PHP Max Input Vars: 6144
cURL Version: 8.10.1
OpenSSL/3.0.15

SUHOSIN Installed: –
MySQL Version: 10.11.10-MariaDB-log
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

[REDACTED]

### Post Type Counts ###

attachment: 24
page: 9
post: 4
product: 24
product_variation: 7
revision: 9
shop_coupon: 4
shop_order_placehold: 91
wp_font_face: 36
wp_font_family: 12
wp_navigation: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (6) ###

Akismet Anti-spam: Spam Protection: by Automattic - Anti-spam Team – 5.3.5
Code Snippets: by Code Snippets Pro – 3.6.6.1
Query Monitor: by John Blackbourn – 3.17.0
WooPayments: by WooCommerce – 8.8.0-test-3
WooCommerce Subscriptions: by WooCommerce – 7.1.0
WooCommerce: by Automattic – 9.7.0-dev

### Inactive Plugins (1) ###

WooCommerce Payments Dev Tools: by Automattic –

### Dropin Plugins () ###

advanced-cache.php: advanced-cache.php
db.php: Query Monitor Database Class (Drop-in)
object-cache.php: Memcached

### Must Use Plugins (1) ###

load.php: by  –

### Settings ###

Legacy API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 6 MB

### WC Pages ###

Shop base: #7 - /shop/
Cart: #8 - /cart/ -  Contains the woocommerce/cart block
Checkout: #9 - /checkout/ -  Contains the woocommerce/checkout block
My account: #10 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 4.6.0
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
Theme type: Classic theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### WooPayments ###

Version: 8.8.0-test-3
Connected to WPCOM: Yes
WPCOM Blog ID: 240702045
Account ID: acct_1Qh44oC2xlt50fcY
Payment Gateway: Enabled
Test Mode: Enabled
Enabled APMs: card
WooPay: Enabled (product,cart,checkout)
WooPay Incompatible Extensions: No
Apple Pay / Google Pay: Enabled (product,cart,checkout)
Fraud Protection Level: basic
Multi-currency: Enabled
Auth and Capture: Disabled
Documents: Disabled
Logging: Enabled

### Subscriptions ###

WCS_DEBUG: ✔ No
Subscriptions Mode: ✔ Live
Subscriptions Live URL: https://planned-komodo-cephalopod.jurassic.ninja
Subscriptions-core Library Version: 7.9.0
Subscription Statuses: wc-active: 11
wc-cancelled: 1

WooCommerce Account Connected: ❌ No
Report Cache Enabled: ✔ Yes
Cache Update Failures: ✔ 0 failure

### Store Setup ###

Country / State: United States (US) — California

### Subscriptions by Payment Gateway ###

WooPayments: wc-active: 11
wc-cancelled: 1


### Payment Gateway Support ###

WooPayments: products
refunds
multiple_subscriptions
subscription_cancellation
subscription_payment_method_change_admin
subscription_payment_method_change_customer
subscription_payment_method_change
subscription_reactivation
subscription_suspension
subscriptions
subscription_amount_changes
subscription_date_changes
tokenization
add_payment_method


### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
onboarding
onboarding-tasks
pattern-toolkit-full-composability
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
printful
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page
launch-your-store
add-to-cart-with-options-stepper-layout

Disabled Features: product-data-views
experimental-blocks
coming-soon-newsletter-template
minified-js
product-pre-publish-modal
settings
async-product-editor-category-field
product-editor-template-system
blueprint
reactify-classic-payments-settings
use-wp-horizon
blockified-add-to-cart

Daily Cron: ✔ Next scheduled: 2025-01-15 06:51:57 +00:00
Options: ✔
Notes: 61
Onboarding: skipped

### Action Scheduler ###

Canceled: 26
Oldest: 2025-01-14 07:09:25 +0000
Newest: 2025-01-14 11:23:50 +0000

Complete: 592
Oldest: 2025-01-14 06:53:12 +0000
Newest: 2025-01-14 08:21:23 +0000

Failed: 2
Oldest: 2025-01-14 06:57:31 +0000
Newest: 2025-01-14 08:11:57 +0000

Pending: 13
Oldest: 2025-01-15 06:53:12 +0000
Newest: 2025-03-14 08:23:50 +0000


### Status report information ###

Generated at: 2025-01-14 16:53:14 +00:00
```
</details>

### Isolating the problem

- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by gigitux**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

This PR fixes a small regression introduced with https://github.com/woocommerce/woocommerce/pull/54160.

Reading the docs, I discovered that `button` or `anchor` element is based on the present of the href prop:

https://github.com/WordPress/gutenberg/blob/24c4575e6af827638f7ef83cbf5190d1ad4a9280/packages/components/src/button/README.md#L71-L76

Based on this, I updated the code and add tests to avoid similar regression in the future.

Closes #54488.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Visit `wp-admin/admin.php?page=wc-admin`
2. Via Chrome Dev Tools inspect header and buttons for each element in the list:

image

3. Ensure that when `href` is present, a `<a>` element is rendered. Otherwise, a `<button>` should be rendered
image

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [x] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

Fix `InboxNoteActionButton` component regression.

</details>

### CODE REVIEW

**Comment by gigitux** [comment]
@ricardo I don't have an env with Woo Payments configured, could you take a look and see if this PR fixes the issue following the retro steps of https://github.com/Automattic/woocommerce-payments/issues/10148? Thanks! 🙇

File: packages/js/experimental/src/inbox-note/action.tsx [hunk 1]
```diff
@@ -56,26 +56,12 @@ export const InboxNoteActionButton: React.FC< InboxNoteActionProps > = ( {
...
-		);
-	}
-
 	return (
 		<Button
 			className="woocommerce-inbox-note__action-button"
 			variant={ variant }
 			isBusy={ inAction }
-			disabled={ inAction }
+			{ ...( href ? { href } : {} ) }
```
Comment (ricardo) [inline packages/js/experimental/src/inbox-note/action.tsx]: Maybe we shouldn't remove the `disabled` prop, because otherwise it can still trigger subsequent clicks and consequently new requests to `/wc-analytics/admin/notes/{note_id}`.

Nit: Also, maybe simplifying the `href` prop handling to `href={ href || undefined }` to make slightly more readable?

**Review by ricardo — COMMENTED** [review]
I confirmed that this PR fixes the regression with WooPayments notes ✅ 

Also, props for adding the tests!

Please check my comment regarding the `disabled` prop.

File: packages/js/experimental/src/inbox-note/action.tsx (hunk 1 above)
Comment (gigitux) [reply packages/js/experimental/src/inbox-note/action.tsx]: > Maybe we shouldn't remove the disabled prop.

Good catch! It was not my intention to remove it! 

>  Also, maybe simplifying the href prop handling to href={ href || undefined } to make slightly more readable?

It makes sense!

Addressed both feedback with 25802722de745b84792b63e247a94156ec895f88! Thanks for the review!

**Review by kmanijak — APPROVED** [review]
LGTM! 💪

**Review by ricardo — APPROVED** [review]
LGTM and tests well!
