### PR TITLE
Store transactional meta in HPOS tables.

### LINKED ISSUE #35612: [HPOS] Order payment tokens are stored in post meta on HPOS environments
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

With HPOS tables enabled, order `_payment_tokens` are still stored in post meta. 

The reason that this occurs is because payment tokens are updated/set via `WC_Order::add_payment_token()` and fetched with `WC_Order::get_payment_tokens()` both these functions call subsequent functions in the datastore, however both those functions `update_payment_token_ids()` and `get_payment_token_ids()` only exist in the CPT datastore. 

Therefore, when you call `WC_Order::add_payment_token()` it writes directly to post meta via `update_post_meta()`. 

### Expected behavior

On HPOS stores, I'd expect tokens to be stored in the `wc_orders_meta` table or one of the other new tables.

### Actual behavior

The `_payment_tokens` are stored in post meta. 

### Steps to reproduce

**Customer flow**
1. Enable HPOS tables with syncing turned off.
2. Purchase a product with WC Payments (or another gateway that utilises the payment token API). 
3. Go to the post meta table and note that the payment tokens are stored in post meta. 

**Programmatically** 

```php
$token = new WC_Payment_Token_CC();

$token->set_token( 'pm_1234' );
$token->set_gateway_id( 'stripe' );
$token->set_card_type( 'visa' );
$token->set_last4( 1234 );
$token->set_expiry_month( 12 );
$token->set_expiry_year( 2022 );
$token->save();

$order = wc_get_order( 647 ); // <-- Replace ID with an order ID on your store.
$order->add_payment_token( $token );
```

Screen Shot 2022-11-17 at 6 40 25 pm
^ Post meta showing the tokens being stored

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://hpos.local
Site address (URL): https://hpos.local
WC Version: 7.2.0
REST API Version: ✔ 7.2.0
WC Blocks Version: ✔ 8.9.1
Action Scheduler Version: ✔ 3.4.0
Log Directory Writable: ✔
WP Version: 6.1.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.43 (Unix)
PHP Version: 8.0.0
PHP Post Max Size: 1,000 MB
PHP Time Limit: 1200
PHP Max Input Vars: 4000
cURL Version: 7.79.1
(SecureTransport) LibreSSL/3.3.6

SUHOSIN Installed: –
MySQL Version: 5.7.28
Max Upload Size: 300 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.2.0
WC Database Prefix: wp_
Total Database Size: 16.03MB
Database Data Size: 9.68MB
Database Index Size: 6.35MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.36MB + Index: 0.44MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 1.52MB + Index: 1.13MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 1.52MB + Index: 0.61MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.30MB + Index: 0.31MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 3.03MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 1.52MB + Index: 1.86MB + Engine InnoDB
wp_posts: Data: 0.05MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wc_orders_meta: Data: 0.23MB + Index: 0.55MB + Engine InnoDB
wp_wc_order_addresses: Data: 0.08MB + Index: 0.13MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_operational_data: Data: 0.11MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.05MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.06MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_square_customers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

attachment: 1
customize_changeset: 1
page: 7
post: 2
product: 6
revision: 1
shop_order_placehold: 81
wp_global_styles: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (6) ###

WooCommerce Payments Dev Tools: by Automattic –
WooCommerce Payments: by Automattic – 5.0.3
WooCommerce Subscriptions Core: by Automattic – 5.0.0
WooCommerce Subscriptions: by WooCommerce – 4.6.0
WooCommerce: by Automattic – 7.2.0-dev
WP Console: by Edi Amin – 2.3.1

### Inactive Plugins (4) ###

WooCommerce: by Automattic – 7.2.0-dev
WooCommerce: by Automattic – 6.8.2 (update to version 7.1.0 is available)
WooCommerce Square: by WooCommerce – 3.3.0
WooCommerce Stripe Gateway: by WooCommerce – 6.9.0

### Settings ###

API Enabled: –
Force SSL: –
Currency: AUD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### WC Pages ###

Shop base: #6 - /shop/
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 4.1.3 (update to version 4.2.0 is available)
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Subscriptions ###

WCS_DEBUG: ❌ Yes
Subscriptions Mode: ✔ Live
Subscriptions Live URL: https://hpos.local
Subscription Statuses: –
WooCommerce Account Connected: ❌ No
Report Cache Enabled: ✔ Yes
Cache Update Failures: ✔ 0 failure

### Store Setup ###

Country / State: Australia — Queensland

### Payment Gateway Support ###

WooCommerce Payments: products
refunds
multiple_subscriptions
subscription_cancellation
subscription_payment_method_change_admin
subscription_payment_method_change_customer
subscription_payment_method_change
subscription_reactivation
subscription_suspension
subscriptions
subscription_amount_changes
subscription_date_changes
tokenization
add_payment_method

Direct bank transfer: products

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
experimental-products-task
experimental-import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
multichannel-marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
settings

Daily Cron: ✔ Next scheduled: 2022-11-18 05:23:43 +00:00
Options: ✔
Notes: 57
Onboarding: completed

### WooCommerce Payments ###

Version: 5.0.3
Connected to WPCOM: Yes
Blog ID: 211584384
Account ID: acct_1LuRHeCSQIDdUhVA

### Action Scheduler ###

Canceled: 83
Oldest: 2022-10-27 07:43:57 +0000
Newest: 2022-11-17 06:40:37 +0000

Complete: 3,004
Oldest: 2022-10-24 06:02:08 +0000
Newest: 2022-11-16 08:09:43 +0000

Failed: 36
Oldest: 2022-11-08 21:48:26 +0000
Newest: 2022-11-16 04:08:39 +0000

Pending: 171
Oldest: 2022-11-17 08:41:47 +0000
Newest: 2023-02-10 02:32:47 +0000

### Status report information ###

Generated at: 2022-11-17 08:41:54 +00:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by vedanshujain**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Store transactional data in HPOS tables instead of post meta tables when HPOS is authoritative. We use direct queries to store and retrieve data from post meta table instead of using props or instead of storing in metadata because:
1. We don't use props because that will cause delayed insertion or retrieval from the table, i.e. data will be written to DB only when `->save()` is called and read when the entire object is read. While this is fine usually, unfortunately, this is different from the behavior in the CPT table where payment_token was read and written immediately, so to preserve backward compat, we use the same approach.
2. We don't use the object's metadata prop to store this data because it's marked as internal and as such should not be returned in interfaces such as REST API.

Closes #35612 

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

Since we cannot test this using WC UX, we will use custom code to test it out:

1. Using the shell, run the following commands:
```
// Let's create a new order first and save it. Note the order ID, let's say its ORDER_ID
$order = wc_create_order();
$order->save();

// Add some payment token for this order.
$token = new WC_Payment_Token_ECheck();
$token->set_last4( 1234 );
$token->set_token( time() );
$token->save();

// Add the token to order
$order->add_payment_token( $token );

// Let's refresh the order and see if the token was saved.
$refreshed_order = wc_get_order( $order->get_id() );
// This should return the ID of the token in an array. If the payment token table was empty earlier, this will return `[1]`. Note down the ID, let's say it's [XXX].
$refreshed_order->get_payment_tokens();
```
3. Verify that the above token is stored in order meta table, by running the following SQL query:
```
wp db query "SELECT * FROM wp_wc_orders_meta WHERE order_id = ORDER_ID and meta_key = '_payment_tokens';"
```
You should see a serialized value, for example, if the value when getting from code is `[1]`, then the serialized will be `a:1:{i:0;i:1;}` 

If you see a table not existing in this step, then most possible the table prefix is different than `wp_`. In this case, run the `wp db prefix` command and replace `wp_wc_orders_meta` with correct `{prefix}wc_orders_meta`.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Comment 

</details>

### CODE REVIEW

**Comment by vedanshujain** [comment]
@coreymckrill note that this also needs a migration, but looking to get your early thoughts before I work on that.

File: plugins/woocommerce/core
Comment (coreymckrill) [inline plugins/woocommerce/core:1]: Looks like maybe this file was added by mistake?

File: plugins/woocommerce/src/Internal/DataStores/CustomMetaDataStore.php [hunk 1]
```diff
@@ -194,4 +194,41 @@ public function get_metadata_by_id( $meta_id ) {
 
 		return $meta;
 	}
+
+	/**
+	 * Retrieves metadata by meta key.
+	 *
+	 * @param \WC_Abstract_Order $object Object ID..
```
Comment (coreymckrill) [inline plugins/woocommerce/src/Internal/DataStores/CustomMetaDataStore.php]:
```suggestion
	 * @param \WC_Abstract_Order $object Object ID.
```

**Review by coreymckrill — COMMENTED** [review]
👍 Thanks for the clear testing instructions. Worked as described.

Two very minor tweaks (see below) and then this is ready to ship.

**Comment by coreymckrill** [comment]
> this also needs a migration, but looking to get your early thoughts before I work on that.

@vedanshujain is this still the case, or is this ready to merge?

**Comment by vedanshujain** [comment]
> is this still the case, or is this ready to merge?

there is, but let me do that in another PR and merge this one, wdyt?

File: plugins/woocommerce/src/Internal/DataStores/CustomMetaDataStore.php (hunk 1 above)
Comment (vedanshujain) [reply plugins/woocommerce/src/Internal/DataStores/CustomMetaDataStore.php]: Addressed in https://github.com/woocommerce/woocommerce/pull/39381/commits/29d9055278002e888c8b04bf0bf2f042fd8b8167

**Comment by coreymckrill** [comment]
Sounds good. I'll go ahead and ~merge this~ mark for analysis since it's ready.

**Review by coreymckrill — APPROVED** [review]
