### PR TITLE
Do not load unsupported theme functionality when shop page -1

### LINKED ISSUE #19790: Condition In WC_Template_Loader::unsupported_theme_init() Doesn't Account For Possible -1 Page ID Value
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Look at the logic in `WC_Template_Loader::unsupported_theme_init()` and notice that a `-1` value will be considered `true` when the intent of the code is not to run when there is no shop page.

https://github.com/woocommerce/woocommerce/blob/1d0528b73fe92d91556083351f039ed428c51082/includes/class-wc-template-loader.php#L195-L205

The possible `-1` value ultimately comes from here:
https://github.com/woocommerce/woocommerce/blob/e8cc1076ad6d6f1d3932fb8087689e79f776768d/includes/wc-page-functions.php#L41-L56

## Expected/actual behavior

When I follow those steps, I see...

I was expecting to see...

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```
</details>

### PR DESCRIPTION
**Pull request by kloon**
### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

This PR fixes an issue where the shop page ID can result in a -1 when the option does not exist in the DB due to how wc_get_page_id works. When WooCommerce then checks to see if the unsupported theme functionality should be loaded it will load it even if there is no shop page defined as -1 is seen as true when checking boolean values.

Closes #19790 

### How to test the changes in this Pull Request:

1. Delete the option for woocommerce_shop_page_id from the wp_options table
2. Try and load the shop page, it should not load the unsupported WooCommerce theme functionality.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

### Changelog entry

> Fix - Unsupported theme functionality loading when no shop page defined.

### CODE REVIEW

File: includes/class-wc-template-loader.php [hunk 1]
```diff
@@ -193,7 +193,7 @@ public static function comments_template_loader( $template ) {
 	 * @since 3.3.0
 	 */
 	public static function unsupported_theme_init() {
-		if ( self::$shop_page_id ) {
+		if ( self::$shop_page_id && intval( self::$shop_page_id ) > 0 ) {
```
Comment (mikejolley) [inline includes/class-wc-template-loader.php]: `wc_get_page_id` always returns `int`. It uses absint or returns -1. Therefore it should be safe to check > 0 only.

This should also use yoda condition, So `0 < self::$shop_page_id`

**Review by mikejolley — CHANGES_REQUESTED** [review]
See comments.

**Review by mikejolley — APPROVED** [review]
