### PR TITLE
Product Collection: Handpicked Products filter is broken on stores with high volume of products

### LINKED ISSUE #48367: Product Collection: The Hand-picked products filter is broken for stores with the high volume of products
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

The hand-picked product filter is broken in my test store, which has 50k products.

### Expected behavior

The hand-picked filter should work flawlessly no matter how many products stores may have.

### Actual behavior

The filter only shows the loading indicator after it's selected. The console log throws an error indicating execution timeout on the server.

image

### Steps to reproduce

1. Add the Product Collection block to a page.
2. Choose the Product Catalog preset.
3. From the inspector setting, add the Hand-picked products filter.
4. See the error as described above.

### WordPress Environment

<details><summary>System Status Report</summary>

```
### WordPress Environment ###

WordPress address (URL): http://woo.test
Site address (URL): http://woo.test
WC Version: 9.1.0-dev
Legacy REST API Package Version: The Legacy REST API plugin is not installed on this site.
Action Scheduler Version: ✔ 3.7.4
Log Directory Writable: ✔
WP Version: 6.5.4
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.25.4
PHP Version: 8.1.26
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 8.5.0
OpenSSL/3.1.4

SUHOSIN Installed: –
MySQL Version: 8.0.33
Max Upload Size: 8 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 9.1.0
WC Database Prefix: wp_
Total Database Size: 910.25MB
Database Data Size: 487.44MB
Database Index Size: 422.81MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 58.09MB + Index: 53.61MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 40.28MB + Index: 32.83MB + Engine InnoDB
wp_automatewoo_abandoned_carts: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_automatewoo_customer_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_customers: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_automatewoo_guest_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_guests: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_automatewoo_log_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_queue: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_queue_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 3.03MB + Index: 1.05MB + Engine InnoDB
wp_postmeta: Data: 245.81MB + Index: 250.66MB + Engine InnoDB
wp_posts: Data: 79.59MB + Index: 27.11MB + Engine InnoDB
wp_term_relationships: Data: 29.58MB + Index: 14.53MB + Engine InnoDB
wp_term_taxonomy: Data: 0.45MB + Index: 0.50MB + Engine InnoDB
wp_termmeta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.42MB + Index: 0.53MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 11.56MB + Index: 11.27MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 17.55MB + Index: 29.05MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 102
page: 9
post: 5
product: 50347
product_variation: 125080
revision: 248
wp_global_styles: 4
wp_navigation: 1
wp_template: 7
wp_template_part: 1

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (2) ###

Laravel DD for Wordpress: by Peter Hegman – 1.0.1
WooCommerce: by Automattic – 9.1.0-dev

### Inactive Plugins (4) ###

Attribute Color Filter: by The WordPress Contributors – 0.1.0
AutomateWoo: by WooCommerce – 6.0.12 (update to version 6.0.24 is available)
Gutailberg: by Tung Du – 0.1.0
WooCommerce Smooth Generator: by Automattic – 1.1.0

### Must Use Plugins (1) ###

test.php: by  –

### Settings ###

API Enabled: –
Force SSL: –
Currency: VND (₫)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 0
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 34 KB

### WC Pages ###

Shop base: #7 - /shop/
Cart: #8 - /cart/
Checkout: #9 - /checkout/
My account: #10 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty-Four
Version: 1.1
Author URL: https://wordpress.org
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ❌ Not declared

### Templates ###

Overrides: /Users/tung/workspace/woocommerce/plugins/woocommerce/templates/block-notices/error.php
/Users/tung/workspace/woocommerce/plugins/woocommerce/templates/block-notices/notice.php
/Users/tung/workspace/woocommerce/plugins/woocommerce/templates/block-notices/success.php


### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page
launch-your-store

Disabled Features: experimental-blocks
minified-js
pattern-toolkit-full-composability
product-pre-publish-modal
settings
async-product-editor-category-field
product-editor-template-system

Daily Cron: ✔ Next scheduled: 2024-06-12 06:31:46 +00:00
Options: ✔
Notes: 82
Onboarding: skipped

### Action Scheduler ###

Complete: 175,264
Oldest: 2024-02-02 09:53:29 +0000
Newest: 2024-06-11 09:45:49 +0000

Failed: 95
Oldest: 2023-12-08 03:13:21 +0000
Newest: 2024-02-21 11:25:32 +0000

Pending: 1
Oldest: 2024-06-12 09:29:14 +0000
Newest: 2024-06-12 09:29:14 +0000


### Status report information ###

Generated at: 2024-06-11 10:32:47 +00:00
```
</details>

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by kmanijak**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

This PR solves a problem in which a handpicked product filter was broken with large product volume stores (3k+). The issue was introduced in https://github.com/woocommerce/woocommerce/pull/45931, where tried to fetch ALL of the products at once, no matter the size. Server returned 500 when trying to fetch 3k+ products (it was slow but still successful up to 2k).

This PR fixes the problem applied two strategies for handpicked products:

#### "Small" catalog (<= 100 products)
For small catalogs, we keep the "old" logic in which we fetch ALL the products once, display them all, and allow browsing through them. 

#### "Large" catalog (> 100 products )
For large catalogs, we refetch products depends on the user input (debouce on 250ms is applied). In that case we make two requests:
- one based on the user's input
- second one for `selected` items (there's no guarantee above request return selected products which then goas blank based on FormTokenField logic)

#### Why not unify the strategies?
1. There's an internal logic of `getProductRqeusts` util [here](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce-blocks/assets/js/editor-components/utils/index.js#L38) which only allow fetching `selected` items when store is "large". If we use "large" stores strategy to "small" stores the control breaks easily.
2. Most stores are considered small so it's better keeping single request for them rather than multiple requests depends on the input.

Closes https://github.com/woocommerce/woocommerce/issues/48367

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

#### Small store logic

0. Make sure your store has up to 100 products
1. Create new post
2. Add Product Collection block and choose Product Catalog
3. In Inspector Controls add "Hand-picked products" filter
4. Smoke test it by typing, adding, removing items
5. **Expected:** Options can be "filtered out" depends on the input, products are filtered depends on the input

##### Creating large number of products

1. Use [WooCommerce Smooth Generator](https://github.com/woocommerce/wc-smooth-generator)
2. Download the latest release as a zip file from https://github.com/woocommerce/wc-smooth-generator/releases/
3. Install in your WordPress site as you would any other plugin zip file.
4. Open terminal in scope of your site
5. Run command `wp wc generate products <nr of products>`

##### Logic

0. Create 150 products - don't create more yet. WooCommerce Smooth Generator creates products with duplicated names when requesting higher number of products. There's a bug (https://github.com/WordPress/gutenberg/issues/62533) in `FormTokenField` that we use in Handpicked Product filter which causes some options to stay visible etc. This scenario is about testing the products fetching works fine hence we avoid encountering that issue.

1. Create new post
2. Add Product Collection block and choose Product Catalog
3. In Inspector Controls add "Hand-picked products" filter
4. Smoke test it by typing (try words `wooden`, `leather` if you use WC Smooth Generator), adding, and removing items
5. **Expected:** Options can be "filtered out" depends on the input (list of products is updated after you stop typing), products are filtered depends on the input

##### Performance

0. Create 5000 products - note, it may take some time!
1. Create new post
2. Add Product Collection block and choose Product Catalog
3. In Inspector Controls add "Hand-picked products" filter
4. Smoke test it by typing (try words `wooden`, `leather` if you use WC Smooth Generator), adding, and removing items
5. **Expected:** Control can be used and doesn't crash
6. Open Developer Tools and Console
7. **Expected:** There's NO error like in the screenshot below:

image

Note: be aware the control may behave weirdly and display unexpected options which is related to the bug I mentioned above (https://github.com/WordPress/gutenberg/issues/62533).

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

**Review by dinhtungdu — COMMENTED** [review]
The PR is working great on my test store with 50k products. I have one issue and one suggestion but they do not necessarily belong to the scope of this PR, raising them here for awareness and discussion first while I review the code more thoroughly:
- My test store has some products with duplicated title, which throw this error in the console: 
image
- We only use the ID and title of the product but the StoreAPI returns the whole product data. StoreAPI doesn't have any query params to limit the fields to return, maybe we should add that ability?

File: plugins/woocommerce-blocks/assets/js/blocks/product-collection/edit/inspector-controls/hand-picked-products-control.tsx [hunk 1]
```diff
@@ -36,13 +42,27 @@ function useProducts() {
...
+						// Limit search to 40 results. If results are not satisfying
+						// user needs to type more characters to get closer to actual
+						// product name.
+						per_page: 40,
+				  }
+				: {},
+		};
+		getProducts( query ).then( ( results ) => {
 			const newProductsMap = new Map();
 			( results as ProductResponseItem[] ).forEach( ( product ) => {
```
Comment (dinhtungdu) [inline plugins/woocommerce-blocks/assets/js/blocks/product-collection/edit/inspector-controls/hand-picked-products-control.tsx:70]: Again, this one is also not under the scope of this PR, but it's possible to select the wrong product if we have two or more products with the same title:

```
newProductsMap.set( product.name, product );
```

File: plugins/woocommerce-blocks/assets/js/blocks/product-collection/edit/inspector-controls/hand-picked-products-control.tsx
Comment (imanish003) [inline plugins/woocommerce-blocks/assets/js/blocks/product-collection/edit/inspector-controls/hand-picked-products-control.tsx:1]: If there are some hand-picked products and I reload the page. When I select Product Collection block after reloading, I can see empty placeholders for the selected products. Which is then replaced with actual products after a second. Maybe it's happening because product fetching starts as soon as the Product Collection block is selected. For this, we may consider not showing placeholders while products are being fetched. What do you think? (See attached video)


https://github.com/woocommerce/woocommerce/assets/16707866/0c0e64f9-e501-45ca-8ec2-d457ff37d9b9

Comment (dinhtungdu) [reply plugins/woocommerce-blocks/assets/js/blocks/product-collection/edit/inspector-controls/hand-picked-products-control.tsx:1]: We removed the placeholder [here](https://github.com/woocommerce/woocommerce/pull/48379/files#diff-cb24114eeb42dcbc00cb6a158773c7eb9c0ad63630ef529d2f4cd4eedb000031L146-L150). @kmanijak can you share the reason for that removal?

Comment (kmanijak) [reply plugins/woocommerce-blocks/assets/js/blocks/product-collection/edit/inspector-controls/hand-picked-products-control.tsx:1]: It's a leftover of a different approach I tried for a moment. Good catch both of you! I brought it back!

**Comment by kmanijak** [comment]
Thanks @dinhtungdu for review!

> My test store has some products with duplicated title, which throw this error in the console:

I noticed that during implementation. It results it weird behavior of FormTokenField and that's why I mention it in PR description.

I don’t think we can fix the problem of duplicated keys without major change in FormTokenField.

1. I can switch from array of `name`s to array of `id`s as suggestions passed to FormTokenField
2. Then I can obviously use `displayTransform` to correctly display the values mapping from id to name - that solves the problem of duplicated keys as well
3. But then the FormTokenField uses the suggestions to search values and not what’s displayed which means:
    - If I input Beanie no results shows up
    - If I input 3 all products which IDs include 3 show up

I didn’t want to touch that before and hence I mentioned [this issue](https://github.com/WordPress/gutenberg/issues/62533) in PR description. It also says:
> P.S.: I am aware that the FormTokenField is currently being rewritten. However, I believe it is important to report this issue regardless.“.

I don’t have confirmation but I’d rather leave it as is. The problem touches multiple places FormTokenField is used to choose products.

> We only use the ID and title of the product but the StoreAPI returns the whole product data. StoreAPI doesn't have any query params to limit the fields to return, maybe we should add that ability?

Re this, while I totally agree, I don't consider it a priority and would rather not address it atm.

**Review by dinhtungdu — APPROVED** [review]
I can confirm the filter is working as intended on my 50k products test store. The placeholder shows up again as well. About the duplicated keys, as I mentioned in the previous review, I don't think it belong to the scope of this PR. Thanks for working on this, LGTM!

File: plugins/woocommerce-blocks/assets/js/blocks/product-collection/edit/inspector-controls/hand-picked-products-control.tsx [hunk 2]
```diff
@@ -36,13 +42,27 @@ function useProducts() {
...
+			selected: isLargeCatalog ? selected.map( Number ) : [],
+			queryArgs: isLargeCatalog
+				? {
+						search,
+						// Limit search to 40 results. If results are not satisfying
+						// user needs to type more characters to get closer to actual
+						// product name.
+						per_page: 40,
+				  }
+				: {},
```
Comment (imanish003) [inline plugins/woocommerce-blocks/assets/js/blocks/product-collection/edit/inspector-controls/hand-picked-products-control.tsx]: Nitpick: Maybe we can pass `per_page: 0,` explicitly in query while calling `getProducts` function. It will make it more clear that we are fetching all the products. :slightly_smiling_face:
Otherwise, We rely on [this logic](https://github.com/woocommerce/woocommerce/blob/eb33beb2ffb3f26b9661afb1b98901d5899dae55/plugins/woocommerce-blocks/assets/js/editor-components/utils/index.js#L24), which may stop working in future if inside [getProductsRequests](https://github.com/woocommerce/woocommerce/blob/eb33beb2ffb3f26b9661afb1b98901d5899dae55/plugins/woocommerce-blocks/assets/js/editor-components/utils/index.js#L17-L21) function, [this condition](https://github.com/woocommerce/woocommerce/blob/eb33beb2ffb3f26b9661afb1b98901d5899dae55/plugins/woocommerce-blocks/assets/js/editor-components/utils/index.js#L22) will be changed i.e. instead of using 100 to calculate `isLargeCatalog`, it is changed to something else. 

Feel free to ignore this if you think it's not needed. Also, Please let me know if I misunderstood something.

**Review by imanish003 — APPROVED** [review]
I tested the changes and it seems to be working as expected 🚀 I left one minor nitpick comment, but pre-approving the PR as I don't think it's a blocker. 

FWIW I used products from [here](https://glover.us/blog/woocommerce-sample-data-set/) for testing. This doesn't have duplicate products name 😀

File: plugins/woocommerce-blocks/assets/js/blocks/product-collection/edit/inspector-controls/hand-picked-products-control.tsx (hunk 2 above)
Comment (kmanijak) [reply plugins/woocommerce-blocks/assets/js/blocks/product-collection/edit/inspector-controls/hand-picked-products-control.tsx]: Yeah, I agree it makes sense to pass it explicitly! :) changed in https://github.com/woocommerce/woocommerce/pull/48379/commits/ae536960a1c600707543751d3f6c18c64c4de1cc
