### PR TITLE
Product Gallery block: Fix error on revisiting template without reloading the page

### LINKED ISSUE #46274: Product Gallery (beta): Block error on revisit
Seeing this error `Your site doesn’t include support for the "woocommerce/product-gallery" block. You can leave this block intact, convert its content to a Custom HTML block, or remove it entirely.`

This happens when you use the Product Gallery (beta) block on the single product template. Note that this does not affect the frontend.

https://github.com/woocommerce/woocommerce/assets/2132595/3588f82d-751c-4954-bc53-9ca27292f963

Reproducible steps:

1. With a block theme, go to Appearance->Editor->Templates->Single product
2. Remove the Product Image Gallery block.
3. Add the Product Gallery (beta) block and save.
4. Navigate away from the Editor.
5. Come back to the Single product template and witness the block error.

### PR DESCRIPTION
**Pull request by thealexandrelara**
### Changes proposed in this Pull Request:

In this PR, I've changed the way we identify the current selected template. Previously, we relied on the WP Data stores. However, I noticed that when we leave the template and revisit the page using the Navigation sidebar instead of reloading the page, the state wasn't correctly updated. This meant that the template detector didn't trigger a template change, and consequently, the Product Gallery block wasn't registered on the Single Product template.

With this change, we now detect the current template from the URL, which always points to the correct template. I've also added an E2E test to cover this change and catch similar errors in the future.

Closes #46274 .

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Navigate to Single Product template (Appearance > Editor > Templates > Product Catalog template - or any archive template).
2. Click on "Edit" to open the WordPress editor.
3. In the editor, you should see a block inserter icon or an option to "Add Block". Click on it.
4. Search for "Product Gallery (Beta)" in the block inserter or browse the available blocks until you find them. Add it to your content.
5. Click on the Save button.
6. Click on the WordPress logo at the top left corner - to open the Navigation sidebar.
7. Click on the Back button - to go back to the templates list.
8. Visit another template, for example: click on the Index template. Wait for the template to load.
9. On the Navigation sidebar, click on the Back button again to visit the templates list.
10. Visit the Single Product template.
11. Make sure you can see the Product Gallery block that was previously added and no block error is shown in the editor.

| Before | After |
|--------|--------|
| CleanShot 2024-05-21 at 17 31 28@2x | CleanShot 2024-05-21 at 17 29 40@2x | 

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [x] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 
Fix Product Gallery block error on revisiting Single Product template without fully reloading the page.

#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce-blocks/assets/js/atomic/utils/blocks-registration-manager/template-change-detector.ts [hunk 1]
```diff
@@ -81,6 +82,20 @@ export class TemplateChangeDetector implements TemplateChangeDetectorSubject {
...
+		const isTemplatePage = path
+			? path.includes( 'site-editor.php' )
+			: false;
+		let templateId;
+
+		if ( isTemplatePage ) {
+			templateId = getQueryArg( url, 'postId' );
+		}
+
+		return templateId as string;
```
Comment (gigitux) [inline plugins/woocommerce-blocks/assets/js/atomic/utils/blocks-registration-manager/template-change-detector.ts:96]: This cast isn't necessary because we define the return type

**Review by gigitux — APPROVED** [review]
LGTM! Everything works correctly and this approach looks good to me. I just left a minor comment, but I'm pre-approving this PR! Nice work and thanks for adding E2E tests 🙇 

Is it possible that https://github.com/woocommerce/woocommerce/issues/46781 is caused by this issue that this PR address? 

cc @nefeline that it is working on #46781 - WDYT?

File: plugins/woocommerce-blocks/assets/js/atomic/utils/blocks-registration-manager/template-change-detector.ts (hunk 1 above)
Comment (thealexandrelara) [reply plugins/woocommerce-blocks/assets/js/atomic/utils/blocks-registration-manager/template-change-detector.ts:96]: Unfortunately this is required because the `getQueryArg` method from the `@wordpress/url` package returns a value of type `QueryArgParsed` which is not compatible with the string type. I could change the return type of this function to be of type `QueryArgParsed` but I would have to cast it to string on the `parseTemplateId` method 😅.

**Comment by thealexandrelara** [comment]
Thank you for reviewing it, Luigi! 

> Is it possible that https://github.com/woocommerce/woocommerce/issues/46781 is caused by this issue that this PR address?

Good question! I believe it could be related because the inner blocks of the Single Product block use the `registerSingleProductTemplate` function and subscribe to the core/edit-site and core/edit-post stores. Considering that the issue is being caused because the stores are not correctly updating when the template changes (without a full page reload), this could be the same problem.

I'll investigate this further during the cooldown. Perhaps we can use the same solution to register the inner blocks of the Single Product block. It's also more performant because we don't have to watch for every single update on the stores; it will just register/unregister the block if the template, post, or page changes.

**Comment by nefeline** [comment]
> Is it possible that https://github.com/woocommerce/woocommerce/issues/46781 is caused by this issue that this PR address?

I'm not sure if those two are related, but sounds like @thealexandrelara is already heads down on this, given:

> I'll investigate this further during the cooldown.

Since you mentioned you are planning to investigate this during cooldown, I reassigned https://github.com/woocommerce/woocommerce/issues/46781 to you so we don't step on each other's toes ;)

File: plugins/woocommerce-blocks/assets/js/atomic/utils/blocks-registration-manager/template-change-detector.ts (hunk 1 above)
Comment (gigitux) [reply plugins/woocommerce-blocks/assets/js/atomic/utils/blocks-registration-manager/template-change-detector.ts:96]: Ah ok, gotcha!
