### PR TITLE
Fix legacy order data PHP 8 compatibility issue

### LINKED ISSUE #39489: Legacy order data PHP 8 compatibility issue
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

CRITICAL Uncaught TypeError: Unsupported operand types: string + string in xxx/plugins/woocommerce/includes/abstracts/abstract-wc-order.php:2032 

This issue occurs when accessing old/legacy order data, when line totals were sometimes (in case empty, e.g. free shipping) stored as empty strings instead of decimals. In this case calling `WC_Order_Item_Shipping::get_total()` will return an empty string and not a number. Using `WC_Order::get_line_total( $item, true );` (and other methods, e.g. `get_item_total`) will lead to fatal errors being thrown when using PHP 8.X. 

The problem is being amplified by extensions (e.g. Woo Subscriptions) that copy old order data to a _new_ order, e.g. renewal order which might contain/keep the same, problematic line totals.

### Expected behavior

The `WC_Order_Item::set_total()` (shipping, fee, line _item) method should prevent empty strings from being stored as total. Empty strings should be stored as 0 instead. Another option would be to harden the actual data store object to prevent such issues from happening right when loading the data from the actual (meta) table. 

### Actual behavior

CRITICAL Uncaught TypeError: Unsupported operand types: string + string in xxx/plugins/woocommerce/includes/abstracts/abstract-wc-order.php:2032 

is thrown when calling WC_Order::get_line_total( $item, true ); (mind the $inc_tax = true parameter as this will lead to the actual addition being applied) on a item that includes `''` (empty string) as total in the database.

### Steps to reproduce

1. Add an order containing a shipping item
2. Make sure to use PHP 8.X
3. Call

```php
$order = wc_get_order( $order_id );
array_values( $order->get_items( 'shipping' ) )[0]->set_total( '' );
$order->save();

$order = wc_get_order( $order_id );
$order->get_line_total(  array_values( $order->get_items( 'shipping' ) )[0], true );
```

This code snippet simulates what happened in older Woo versions when a line total of 0 was eventually stored as an empty string.

### WordPress Environment

Latest WP, Woo.

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by lsinger**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

As detailed in #39489, it was possible to set some values like shipping to the empty string, which would then lead to problems under PHP 8 when trying to calculate with totals derived from such values. This PR adds a failing test for the case discussed in #39489, adds a solution that makes the test pass, and for good measure adds a few additional casts to float where we calculate with values that we can't definitely guarantee to not be strings. 

Closes #39489.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. checkout this branch
2. step back a few commits so that only the failing test is being added
3. start `wp-env` with PHP 8.1 like so: `WP_ENV_PHP_VERSION=8.1 wp-env start`
4. run `pnpm --filter=woocommerce test:unit:env --filter=WC_Tests_Order_Item_Product::test_get_item_shipping_total`
5. note that the test fails ("TypeError: Unsupported operand types: string + string")
6. move the commit pointer forward again so that all commits from this branch are applied
7. re-run the test and see that it passes; optionally run the whole test suite by removing the filter but the CI should take care of that anyway

<!-- End testing instructions -→

### Changelog entry

<!-- You can optionally choose to enter a changelog entry by checking the box and supplying data. -→

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

<!-- Choose only one -→

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

<!-- Choose only one -→

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Comment <!-- If the changes in this pull request don't warrant a changelog entry, you can alternatively supply a comment here. Note that comments are only accepted with a significance of "Patch" -→

</details>

### CODE REVIEW

File: plugins/woocommerce/includes/abstracts/abstract-wc-order.php [hunk 1]
```diff
@@ -1783,7 +1783,7 @@ public function get_total_fees() {
 		return array_reduce(
```
Comment (rrennick) [inline plugins/woocommerce/includes/abstracts/abstract-wc-order.php:1783]: The third parameter of an `array_reduce` is the initial value (in this case `$carry`). Let's set that to 0.0.

**Review by rrennick — APPROVED** [review]
Nive work @lsinger. I just had the one optional suggestion.

File: plugins/woocommerce/includes/abstracts/abstract-wc-order.php (hunk 1 above)
Comment (lsinger) [reply plugins/woocommerce/includes/abstracts/abstract-wc-order.php:1783]: Great catch, thanks Ron! Pushed that change. 👍
