### PR TITLE
CYS: Investigate multiple requests being made to the patterns endpoint

### LINKED ISSUE #50907: CYS: Investigate multiple requests being made to the patterns endpoint
Whilst reviewing https://github.com/woocommerce/woocommerce/pull/50400 I noticed we are sending multiple requests to the patterns endpoint (screenshot below). We should investigate why this is happening and if this is necessary. If its not, we should fix and optimize this.

### To reproduce

1. Go to `wp-admin/tools.php?page=woocommerce-admin-test-helper` and click the Tools tabs.
2. Run the `Reset Customize Your Store` command.
3. Go to `wp-admin/admin.php?page=wc-admin&path=%2Fcustomize-store`.
3. Open the network tools and click on `Start designing`.
4. Filter by `wc-admin/patterns` and observe the requests

Image

### PR DESCRIPTION
**Pull request by mdperez86**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes #50907
Related to https://github.com/woocommerce/woocommerce/pull/50529

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

### Tracking is already enabled

1. Visit `wp-admin/admin.php?page=wc-settings&tab=advanced&section=woocommerce_com`
2. Ensure that `Enable tracking` is toggled to on
3. Head over to WooCommerce > Home > Customize your store.
4. Follow the flow.
5. Click on Choose your fonts.
6. Ensure that 10 are visible.
7. Go back.
8. Click on "Design your homepage".
9. Ensure that the `Intro` section has more than four patterns.

### Tracking is not enabled - font opt-in flow

1. Visit `wp-admin/admin.php?page=wc-settings&tab=advanced&section=woocommerce_com`
2. Ensure that `Enable tracking` is toggled to off.
3. Head over to WooCommerce > Home > Customize your store.
4. Follow the flow.
5. Click on Choose your fonts.
6. Ensure that only two fonts are visible.
7. Click on `usage tracking`
8. Click on `opt-in`.
9. After the loading, ensure that 10 fonts are visible
10. Click on "Design your homepage".
11. Ensure that the `Intro` section has more than four patterns.

### Tracking is not enabled - pattern opt-in flow

1. Visit `wp-admin/admin.php?page=wc-settings&tab=advanced&section=woocommerce_com`
2. Ensure that `Enable tracking` is toggled to off.
3. Head over to WooCommerce > Home > Customize your store.
4. Follow the flow.
5. Click on "Design your homepage".
6.  Ensure that the `Intro` section has only four patterns.
7. Click on `usage tracking`
8. Click on `opt-in`.
9. After the loading, ensure that more than four patterns are visible.
10. Click on Click on Choose your fonts.
11. Ensure that 10 fonts are visible

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce-admin/client/customize-store/assembler-hub/opt-in/opt-in.tsx [hunk 1]
```diff
@@ -19,143 +19,139 @@ import { unlock } from '@wordpress/edit-site/build-module/lock-unlock';
...
+		}
+	);
+
+	const { custom } = enabledFontFamilies;
+
+	const enabledFontSlugs = [
+		...( custom ? custom.map( ( font ) => font.slug ) : [] ),
+	];
+
+	const fontFamiliesToEnable = parsedInstalledFontFamilies.reduce(
```
Comment (Aljullu) [inline plugins/woocommerce-admin/client/customize-store/assembler-hub/opt-in/opt-in.tsx:89]: Not a blocker as this code is not introduced in this PR, but I think this `reduce` could be rewritten as a `filter`, no?

File: plugins/woocommerce-admin/client/customize-store/assembler-hub/opt-in/opt-in.tsx [hunk 2]
```diff
@@ -19,143 +19,139 @@ import { unlock } from '@wordpress/edit-site/build-module/lock-unlock';
...
 
-				setOptInFlowStatus( OPTIN_FLOW_STATUS.DONE );
+	useEffect(
+		function optedInListener() {
+			if ( ! isOptedIn ) return;
 
-				unsubscribe();
+			async function installPatternsAndFonts() {
+				await installPatterns();
+				const fontFamilies = await installFonts( enabledFontFamilies );
```
Comment (Aljullu) [inline plugins/woocommerce-admin/client/customize-store/assembler-hub/opt-in/opt-in.tsx:142]: Do you think it would be possible to run `installPatterns()` and `installFonts()` in parallel? Something like:

```TS
await Promise.all([
      installPatterns(),
      installFonts(enabledFontFamilies),
]);
```

**Review by Aljullu — APPROVED** [review]
This is testing well and code changes look good too. I left two comments, but not blocking.

File: plugins/woocommerce-admin/client/customize-store/assembler-hub/opt-in/opt-in.tsx (hunk 1 above)
Comment (mdperez86) [reply plugins/woocommerce-admin/client/customize-store/assembler-hub/opt-in/opt-in.tsx:89]: Well I was trying to touch as less as possible this code and focus only on the scope of the issue.

File: plugins/woocommerce-admin/client/customize-store/assembler-hub/opt-in/opt-in.tsx (hunk 2 above)
Comment (mdperez86) [reply plugins/woocommerce-admin/client/customize-store/assembler-hub/opt-in/opt-in.tsx:142]: I just followed the prev implementation that is sequential too.

Comment (Aljullu) [reply plugins/woocommerce-admin/client/customize-store/assembler-hub/opt-in/opt-in.tsx:142]: I created an issue to investigate this, so we don't forget: https://github.com/woocommerce/woocommerce/issues/51983.

File: plugins/woocommerce-admin/client/customize-store/assembler-hub/opt-in/opt-in.tsx (hunk 1 above)
Comment (Aljullu) [reply plugins/woocommerce-admin/client/customize-store/assembler-hub/opt-in/opt-in.tsx:89]: I opened an issue to refactor this so we don't forget: https://github.com/woocommerce/woocommerce/issues/51984.
