### PR TITLE
Fix order search flaky tests by switching from e2e test to php unit test

### LINKED ISSUE #57700: [Flaky Test] can search for order by order id
**Flaky test detected. This is an auto-generated issue by GitHub Actions. Please do NOT edit this manually.**

## Test title
can search for order by order id

## Test path
`/plugins/woocommerce/tests/e2e-pw/tests/order/order-search.spec.js`

## Errors

<time datetime="2025-05-04T03:41:25.505Z"><code>[2025-05-04T03:41:25.505Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/woocommerce/woocommerce/actions/runs/14817243292"><code>trunk</code></a>.
<br/>
<time datetime="2025-05-07T12:46:08.072Z"><code>[2025-05-07T12:46:08.072Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/woocommerce/woocommerce/actions/runs/14883099168"><code>lstr/update-wordpress-jest-preset-default</code></a>.
<br/>
<time datetime="2025-05-16T10:41:38.185Z"><code>[2025-05-16T10:41:38.185Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/woocommerce/woocommerce/actions/runs/15066049024"><code>dev/try-blocks-e2e-speedup</code></a>.
<br/>
<time datetime="2025-05-21T08:54:35.014Z"><code>[2025-05-21T08:54:35.014Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/woocommerce/woocommerce/actions/runs/15157334710"><code>dev/ci-php-8-3-job</code></a>.
<br/>
<details>
<summary>
	<time datetime="2025-05-21T09:16:53.949Z"><code>[2025-05-21T09:16:53.949Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/woocommerce/woocommerce/actions/runs/15157334710"><code>dev/ci-php-8-3-job</code></a>.
</summary>

```
Error: expect.toContainText: Error: strict mode violation: locator('.order_number > a.order-view') resolved to 2 elements:
    1) <a class="order-view" href="http://localhost:2980/wp-admin/post.php?post=121&action=edit">…</a> aka getByRole('link', { name: '#121 James Doe' })
    2) <a class="order-view" href="http://localhost:2980/wp-admin/post.php?post=39&action=edit">…</a> aka getByRole('link', { name: '#39 Chauncey Bode' })

Call log:
  - expect.toContainText with timeout 20000ms
  - waiting for locator('.order_number > a.order-view')

    at /home/runner/work/woocommerce/woocommerce/plugins/woocommerce/tests/e2e-pw/tests/order/order-search.spec.js:157:6
```
</details>

### PR DESCRIPTION
**Pull request by mikejolley**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Removes an e2e test and replaces with a PHP unit/integration test to check that search functionality returns the correct results. While working on this I noticed under some circumstances, order IDs would come back as strings instead of int.

Closes #57700

(For Bug Fixes) Bug introduced in PR # .

### How to test the changes in this Pull Request:

Tests should pass.
### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce/includes/data-stores/class-wc-order-data-store-cpt.php [hunk 1]
```diff
@@ -684,7 +684,18 @@ public function search_orders( $term ) {
...
+		 *
+		 * @since 3.0.0
+		 * @param array $order_ids The order ids.
+		 * @param string $term The search term.
+		 * @param array $search_fields The search fields.
+		 * @return array
+		 */
+		$order_ids = apply_filters( 'woocommerce_shop_order_search_results', $order_ids, $term, $search_fields );
+
+		return array_map( 'absint', $order_ids );
```
Comment (senadir) [inline plugins/woocommerce/includes/data-stores/class-wc-order-data-store-cpt.php:698]: This is fine but why would order ids return as strings? random?

File: plugins/woocommerce/tests/php/includes/admin/list-tables/class-wc-admin-list-table-orders-test.php [hunk 2]
```diff
@@ -0,0 +1,234 @@
...
+declare( strict_types = 1);
+
+require_once WC_ABSPATH . '/includes/admin/list-tables/class-wc-admin-list-table-orders.php';
+
+/**
+ * WC Admin List Table Orders test
+ */
+class WC_Admin_List_Table_Orders_Test extends WC_Unit_Test_Case {
+	/**
+	 * Test that the order search custom fields logic works as expected. The list table makes use of wc_order_search to
```
Comment (senadir) [inline plugins/woocommerce/tests/php/includes/admin/list-tables/class-wc-admin-list-table-orders-test.php:15]: Intresting high level approach, better than just calling `wc_order_search` directly.

File: plugins/woocommerce/tests/php/includes/admin/list-tables/class-wc-admin-list-table-orders-test.php [hunk 3]
```diff
@@ -0,0 +1,234 @@
...
+		$dummy_order->save();
+
+		foreach ( $fields as $field => $value ) {
+			$order  = WC_Helper_Order::create_order();
+			$setter = 'set_' . $field;
+			$order->$setter( $value );
+			$order->save();
+
+			$_GET['s']          = $value;
+			$GLOBALS['pagenow'] = 'edit.php'; // phpcs:ignore WordPress.WP.GlobalVariablesOverride.Prohibited
```
Comment (senadir) [inline plugins/woocommerce/tests/php/includes/admin/list-tables/class-wc-admin-list-table-orders-test.php:91]: Not a big fan of this but I guess it's needed?

File: plugins/woocommerce/tests/php/includes/admin/list-tables/class-wc-admin-list-table-orders-test.php [hunk 4]
```diff
@@ -0,0 +1,234 @@
...
+		$dummy_order->set_billing_first_name( 'NotAMatch' );
+		$dummy_order->save();
+
+		foreach ( $fields as $field => $value ) {
+			$order  = WC_Helper_Order::create_order();
+			$setter = 'set_' . $field;
+			$order->$setter( $value );
+			$order->save();
+
+			$_GET['s']          = $value;
```
Comment (senadir) [inline plugins/woocommerce/tests/php/includes/admin/list-tables/class-wc-admin-list-table-orders-test.php:90]: I guess `WC_Admin_List_Table_Orders` only reads from query params and ignore what was passed to `WP_Query`?

File: plugins/woocommerce/tests/php/includes/admin/list-tables/class-wc-admin-list-table-orders-test.php
Comment (senadir) [inline plugins/woocommerce/tests/php/includes/admin/list-tables/class-wc-admin-list-table-orders-test.php:1]: Do we need to keep this filter in mind when testing? it seems to have affect and I'm not sure if it's unique to HPOS or not, but this test is HPOS
image

**Review by senadir — APPROVED** [review]
Overall looking good, left a small question about serach filter

File: plugins/woocommerce/tests/php/includes/admin/list-tables/class-wc-admin-list-table-orders-test.php (hunk 3 above)
Comment (mikejolley) [reply plugins/woocommerce/tests/php/includes/admin/list-tables/class-wc-admin-list-table-orders-test.php:91]: To this this particular function yes. We could test at higher level, but in that case its just `wc_order_search` which has tests.

File: plugins/woocommerce/includes/data-stores/class-wc-order-data-store-cpt.php (hunk 1 above)
Comment (mikejolley) [reply plugins/woocommerce/includes/data-stores/class-wc-order-data-store-cpt.php:698]: Database related I think. I had some strings come back, and noticed some stores cast to int and some do not. This ensures integers only. It's also filtered.

File: plugins/woocommerce/tests/php/includes/admin/list-tables/class-wc-admin-list-table-orders-test.php (hunk 4 above)
Comment (mikejolley) [reply plugins/woocommerce/tests/php/includes/admin/list-tables/class-wc-admin-list-table-orders-test.php:90]: Yeah I was populating the query manually to simulate what the form would do.

File: plugins/woocommerce/tests/php/includes/admin/list-tables/class-wc-admin-list-table-orders-test.php
Comment (mikejolley) [reply plugins/woocommerce/tests/php/includes/admin/list-tables/class-wc-admin-list-table-orders-test.php:1]: These tests (and the original tests) use the default "all". We could expand the tests to cover the filter to make sure only filtered results return, however, since this PR is switching from e2e to php unit rather than adding new tests, I think I will just merge this to fix the flaky test.

Comment (senadir) [reply plugins/woocommerce/tests/php/includes/admin/list-tables/class-wc-admin-list-table-orders-test.php:1]: Just noting that the list doesn't exists when you run non-HPOS
