### PR TITLE
Prevent unnecessary DELETE queries in order datastore

### LINKED ISSUE #63680: StoreAPI: Prevent unnecessary item deletion requests in update_line_items_from_cart
## **Describe the bug**

Please feel free to consider this low priority / backlog.

While working on a case, I noted when a draft order is created for the first time - there are some unnecessary SQLs fired to delete non existent items with order ID being 0. This I think is because the order is still in memory and not created yet.

[https://github.com/woocommerce/woocommerce/blob/fa4bd69d62ab9a73e23b756c24c0e860d560b215/plugins/woocommerce/src/StoreApi/Utilities/OrderController.php#L802](<https://github.com/woocommerce/woocommerce/blob/fa4bd69d62ab9a73e23b756c24c0e860d560b215/plugins/woocommerce/src/StoreApi/Utilities/OrderController.php#L802>)

```
DELETE itemmeta FROM wp_woocommerce_order_itemmeta as itemmeta INNER JOIN wp_woocommerce_order_items as items WHERE itemmeta.order_item_id = items.order_item_id AND items.order_id = 0 AND items.order_item_type = 'line_item'

DELETE FROM wp_woocommerce_order_items WHERE order_id = 0 AND order_item_type = 'line_item'

DELETE itemmeta FROM wp_woocommerce_order_itemmeta as itemmeta INNER JOIN wp_woocommerce_order_items as items WHERE itemmeta.order_item_id = items.order_item_id AND items.order_id = 0 AND items.order_item_type = 'shipping'

DELETE FROM wp_woocommerce_order_items WHERE order_id = 0 AND order_item_type = 'shipping'

DELETE itemmeta FROM wp_woocommerce_order_itemmeta as itemmeta INNER JOIN wp_woocommerce_order_items as items WHERE itemmeta.order_item_id = items.order_item_id AND items.order_id = 0 AND items.order_item_type = 'coupon'

DELETE FROM wp_woocommerce_order_items WHERE order_id = 0 AND order_item_type = 'coupon'

DELETE itemmeta FROM wp_woocommerce_order_itemmeta as itemmeta INNER JOIN wp_woocommerce_order_items as items WHERE itemmeta.order_item_id = items.order_item_id AND items.order_id = 0 AND items.order_item_type = 'fee'

DELETE FROM wp_woocommerce_order_items WHERE order_id = 0 AND order_item_type = 'fee'

DELETE itemmeta FROM wp_woocommerce_order_itemmeta as itemmeta INNER JOIN wp_woocommerce_order_items as items WHERE itemmeta.order_item_id = items.order_item_id AND items.order_id = 0 AND items.order_item_type = 'tax'

DELETE FROM wp_woocommerce_order_items WHERE order_id = 0 AND order_item_type = 'tax'
```

Might not make much difference performance wise but I thought this is worth reporting.

### PR DESCRIPTION
**Pull request by jorgeatorres**
### Changes proposed in this Pull Request:

When a draft order is first created via the Store API, `update_line_items_from_cart()` calls `remove_order_items()` before the order has been saved to the database. This causes up to 10 unnecessary `DELETE ... WHERE order_id = 0` queries to be executed against the database on every new checkout session.

This PR adds an early return in `Abstract_WC_Order_Data_Store_CPT::delete_items()` when the order ID is 0, skipping the DELETE queries altogether. The in-memory item clearing in `WC_Abstract_Order::remove_order_items()` still executes normally for all callers.

Closes #63680.

### How to test the changes in this Pull Request:

1. Install and activate the [Query Monitor](https://wordpress.org/plugins/query-monitor/) plugin.
1. Remove all products from your cart (if any).
1. Add a few products to your cart and navigate to the block-based checkout page.
1. Open Query Monitor and look at the database queries panel.
1. Confirm that no `order_id = 0` DELETE queries appear.
1. Go back to your cart (without completing the purchase) and remove some items or change quantities.
1. Go back to the checkout.
1. Complete the checkout and verify the order is created correctly with all line items, shipping, coupons, fees, and taxes intact.
1. Repeat all of the above on `trunk`, and you will see multiple `DELETE`  queries with `order_id = 0` involving tables `wp_woocommerce_order_items` and `wp_woocommerce_order_itemmeta` when you first visit the checkout page.

### Milestone

- [X] Automatically assign milestone for the **[next WooCommerce version](../blob/trunk/plugins/woocommerce/woocommerce.php#L6)**

> **Note:** Check the box above to have the milestone automatically assigned when merged.
> Alternatively (e.g. for point releases), manually assign the appropriate milestone.

### CODE REVIEW

File: plugins/woocommerce/includes/data-stores/abstract-wc-order-data-store-cpt.php [hunk 1]
```diff
@@ -760,6 +760,10 @@ protected function prime_needs_processing_transients( $order_ids, $query_vars )
 	public function delete_items( $order, $type = null ) {
 		global $wpdb;
 
+		if ( ! $order->get_id() ) {
```
Comment (kalessil) [inline plugins/woocommerce/includes/data-stores/abstract-wc-order-data-store-cpt.php]: As a micro- or nanooptimization, can we move `$order->get_id()` into a local variable perhaps?

Comment (jorgeatorres) [reply plugins/woocommerce/includes/data-stores/abstract-wc-order-data-store-cpt.php]: Sure! I was almost certain I had done that, but apparently not! 🥲

**Review by kraftbj — APPROVED** [review]
I agree with @kalessil's suggestion for an micro-improvement, though I don't consider it a blocker. In either event, giving it my stamp as a pre-approval.

File: plugins/woocommerce/includes/data-stores/abstract-wc-order-data-store-cpt.php (hunk 1 above)
Comment (kalessil) [reply plugins/woocommerce/includes/data-stores/abstract-wc-order-data-store-cpt.php]: All good and thanks! I'll review on Monday - want to verify if bypassing cache clear due to early return has any side-effects.
