### PR TITLE
Product Gallery block: Load in variable product specific images

### LINKED ISSUE #46396: Product Gallery (beta): variation images don't change when selecting a variation
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

In a variable product with three or more variables, if variations have a specific image set, when selecting the shopper selects the variation, the product image doesn't change accordingly.

### Expected behavior

The image should change according to the selected variation as the current gallery block does.

### Actual behavior

The image doesn't change

### Steps to reproduce

1. Go to the single product template
2. Add the product gallery (beta) block
3. Create a new variable product  and assign specific images to the variations
4. visit the product on the front end and select a variation

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): http://tommasop42.sg-host.com
Site address (URL): http://tommasop42.sg-host.com
WC Version: 8.9.0
REST API Version: ✔ 8.9.0
Action Scheduler Version: ✔ 3.7.3
Log Directory Writable: ✔
WP Version: 6.5
WP Multisite: –
WP Memory Limit: 768 MB
WP Debug Mode: –
WP Cron: ✔
Language: it_IT
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.4.33
PHP Post Max Size: 256 MB
PHP Time Limit: 120
PHP Max Input Vars: 3000
cURL Version: 8.2.1
OpenSSL/3.1.1

SUHOSIN Installed: –
MySQL Version: 5.7.44-48-log
Max Upload Size: 256 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.9.0
WC Database Prefix: qji_
Dimensione totale database: 224.36MB
Dimensione dati database: 113.43MB
Dimensione indice database: 110.93MB
qji_woocommerce_sessions: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
qji_woocommerce_api_keys: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
qji_woocommerce_attribute_taxonomies: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
qji_woocommerce_downloadable_product_permissions: Dati: 0.02MB + indice: 0.06MB + motore InnoDB
qji_woocommerce_order_items: Dati: 5.52MB + indice: 2.52MB + motore InnoDB
qji_woocommerce_order_itemmeta: Dati: 38.58MB + indice: 46.11MB + motore InnoDB
qji_woocommerce_tax_rates: Dati: 0.02MB + indice: 0.06MB + motore InnoDB
qji_woocommerce_tax_rate_locations: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
qji_woocommerce_shipping_zones: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
qji_woocommerce_shipping_zone_locations: Dati: 0.02MB + indice: 0.05MB + motore InnoDB
qji_woocommerce_shipping_zone_methods: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
qji_woocommerce_payment_tokens: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
qji_woocommerce_payment_tokenmeta: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
qji_woocommerce_log: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
qji_actionscheduler_actions: Dati: 4.52MB + indice: 5.91MB + motore InnoDB
qji_actionscheduler_claims: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
qji_actionscheduler_groups: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
qji_actionscheduler_logs: Dati: 3.52MB + indice: 4.03MB + motore InnoDB
qji_commentmeta: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
qji_comments: Dati: 6.52MB + indice: 2.80MB + motore InnoDB
qji_links: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
qji_options: Dati: 16.09MB + indice: 0.22MB + motore InnoDB
qji_postmeta: Dati: 2.52MB + indice: 3.03MB + motore InnoDB
qji_posts: Dati: 3.42MB + indice: 2.41MB + motore InnoDB
qji_sgs_log_events: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
qji_sgs_log_visitors: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
qji_termmeta: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
qji_terms: Dati: 0.05MB + indice: 0.03MB + motore InnoDB
qji_term_relationships: Dati: 0.16MB + indice: 0.09MB + motore InnoDB
qji_term_taxonomy: Dati: 0.05MB + indice: 0.03MB + motore InnoDB
qji_usermeta: Dati: 6.52MB + indice: 9.03MB + motore InnoDB
qji_users: Dati: 0.41MB + indice: 0.42MB + motore InnoDB
qji_wc_admin_notes: Dati: 0.06MB + indice: 0.00MB + motore InnoDB
qji_wc_admin_note_actions: Dati: 0.05MB + indice: 0.02MB + motore InnoDB
qji_wc_category_lookup: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
qji_wc_customer_lookup: Dati: 1.52MB + indice: 0.44MB + motore InnoDB
qji_wc_download_log: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
qji_wc_orders: Dati: 2.52MB + indice: 5.83MB + motore InnoDB
qji_wc_orders_meta: Dati: 4.52MB + indice: 8.09MB + motore InnoDB
qji_wc_order_addresses: Dati: 3.52MB + indice: 5.06MB + motore InnoDB
qji_wc_order_coupon_lookup: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
qji_wc_order_operational_data: Dati: 2.52MB + indice: 1.81MB + motore InnoDB
qji_wc_order_product_lookup: Dati: 8.52MB + indice: 11.06MB + motore InnoDB
qji_wc_order_stats: Dati: 1.52MB + indice: 1.03MB + motore InnoDB
qji_wc_order_tax_lookup: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
qji_wc_product_attributes_lookup: Dati: 0.11MB + indice: 0.08MB + motore InnoDB
qji_wc_product_download_directories: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
qji_wc_product_meta_lookup: Dati: 0.13MB + indice: 0.20MB + motore InnoDB
qji_wc_rate_limits: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
qji_wc_reserved_stock: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
qji_wc_tax_rate_classes: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
qji_wc_webhooks: Dati: 0.02MB + indice: 0.02MB + motore InnoDB

### Post Type Counts ###

attachment: 101
page: 7
post: 2
product: 302
product_variation: 656
revision: 4
shop_order_placehold: 12643
wp_global_styles: 1
wp_navigation: 1
wp_template: 1

### Security ###

Secure connection (HTTPS): ❌
					Il tuo negozio non utilizza HTTPS. Scopri di più su HTTPS e certificati SSL .
Hide errors from visitors: ✔

### Active Plugins (4) ###

Speed Optimizer: di SiteGround – 7.5.0
WooCommerce Smooth Generator: di Automattic – 1.1.0
WooCommerce Legacy REST API: di WooCommerce – 1.0.1
WooCommerce: di Automattic – 8.9.0-dev

### Inactive Plugins (3) ###

Security Optimizer: di SiteGround – 1.4.13
SiteGround Central: di SiteGround – 3.0.2
WooCommerce Beta Tester: di WooCommerce – 2.3.0

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to Woo.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 giorni
Level threshold: –
Log directory size: 16 KB

### WC Pages ###

Shop base: #6 - /shop/
Carrello: #7 - /cart/
Pagamento: #8 - /checkout/
Il mio account: #9 - /my-account/
Termini e condizioni: ❌ La pagina non è impostata

### Theme ###

Name: Twenty Twenty-Four
Version: 1.1
Author URL: https://wordpress.org
Child Theme: ❌ – Se stai modificando WooCommerce o un tema genitore che non hai costruito personalmente
ti consigliamo di utilizzare un tema child. Vedi: Come creare un tema child

WooCommerce Support: ❌ Non dichiarato

### Templates ###

Overrides: /home/customer/www/tommasop42.sg-host.com/public_html/wp-content/plugins/woocommerce/templates/block-notices/error.php
/home/customer/www/tommasop42.sg-host.com/public_html/wp-content/plugins/woocommerce/templates/block-notices/notice.php
/home/customer/www/tommasop42.sg-host.com/public_html/wp-content/plugins/woocommerce/templates/block-notices/success.php

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
product-virtual-downloadable
product-external-affiliate
product-grouped
product-linked
product-pre-publish-modal
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
product-custom-fields
settings
async-product-editor-category-field
launch-your-store

Daily Cron: ✔ Next scheduled: 2024-04-10 10:12:25 +00:00
Options: ✔
Notes: 68
Onboarding: -

### Action Scheduler ###

Completato: 13.982
Oldest: 2024-04-04 15:48:58 +0000
Newest: 2024-04-09 10:24:56 +0000

Operazione non riuscita: 1
Oldest: 2024-04-05 10:12:47 +0000
Newest: 2024-04-05 10:12:47 +0000

In attesa: 2
Oldest: 2024-04-09 22:12:26 +0000
Newest: 2024-04-10 00:55:40 +0000

### Status report information ###

Generated at: 2024-04-09 19:21:31 +00:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by tjcafferkey**
### Changes proposed in this Pull Request:

If a product variant has a specific image which is not selected in the "Product gallery" metabox. When this variation is selected the image will not show. This PR fixes that by expanding the usage of the Product Gallery imageData object to house variation specific images also.

Closes https://github.com/woocommerce/woocommerce/issues/46396

(For Bug Fixes) Bug introduced in PR # .

### Screenshots or screen recordings:

| Before | After |
| ------ | ----- |
| CleanShot 2025-03-07 at 14 15 14 | CleanShot 2025-03-07 at 14 14 14 |

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Edit a variable product such as Hoodie
2. Check that it has an image assigned to a specific variation in the Variations tab
3. Select a variation, and remove this product from the main product gallery metabox (under Product Image)
4. Save product and go to the frontend
5. Ensure the image is present in the gallery
6. Now select the correct attribute values for that variation and check the correct image scrolls into view

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce/changelog/fix-product-gallery-beta-variable-specific-product-images [hunk 1]
```diff
@@ -0,0 +1,4 @@
+Significance: patch
+Type: fix
+
+Product Gallery: If a user selects the attributes of a product which has a specific image that is not present in the product gallery metabox, ensure it loads
```
Comment (cpapazoglou) [inline plugins/woocommerce/changelog/fix-product-gallery-beta-variable-specific-product-images]: _Just a suggestion_
```suggestion
Product Gallery: Ensure loading the "selected variant" image even if it's not added in the product image gallery.
```

File: plugins/woocommerce/src/Blocks/Utils/ProductGalleryUtils.php [hunk 2]
```diff
@@ -15,17 +15,52 @@ class ProductGalleryUtils {
...
-		$image_ids  = self::get_product_gallery_image_ids( $product );
+		$image_data = array(
+			// Images specifically added to the gallery.
+			'gallery_images'   => array(),
+			// Images that are variations of the product. These may not exist in the gallery.
+			'variation_images' => array(),
+			// All images for the product.
+			'all_images'       => array(),
+		);
+
```
Comment (cpapazoglou) [inline plugins/woocommerce/src/Blocks/Utils/ProductGalleryUtils.php:24]: Let's avoid doing computations if it's not a product

```suggestion
if ( ! $product instanceof \WC_Product ) {
			wc_doing_it_wrong( __FUNCTION__, __( 'Invalid product object.', 'woocommerce' ), '9.8.0' );
			return $image_data;
		}
```

File: plugins/woocommerce/src/Blocks/Utils/ProductGalleryUtils.php [hunk 3]
```diff
@@ -15,17 +15,52 @@ class ProductGalleryUtils {
...
+	}
+
+	/**
+	 * Get the image source data.
+	 *
+	 * @param array $image_ids The image IDs to retrieve the source data for.
+	 * @return array An array of image source data.
+	 */
+	public static function get_image_src_data( $image_ids ) {
+		$image_src_data = array();
```
Comment (cpapazoglou) [inline plugins/woocommerce/src/Blocks/Utils/ProductGalleryUtils.php:54]:
```suggestion
		$image_src_data = array();
		if ( ! is_array( $image_ids ) ) {
			wc_doing_it_wrong( __FUNCTION__, __( 'Image IDs must be an array.', 'woocommerce' ), '9.8.0' );
			return $image_src_data;
		}
```

File: plugins/woocommerce/src/Blocks/Utils/ProductGalleryUtils.php [hunk 4]
```diff
@@ -37,15 +72,40 @@ public static function get_product_gallery_image_data( $product ) {
...
+
+	/**
+	 * Get the product variation image data.
+	 *
+	 * @param \WC_Product $product The product object to retrieve the variation images for.
+	 * @return array An array of image data for the product variation images.
+	 */
+	public static function get_product_variation_image_ids( $product ) {
+		$variation_image_ids = array();
+
```
Comment (cpapazoglou) [inline plugins/woocommerce/src/Blocks/Utils/ProductGalleryUtils.php:94]:
```suggestion
if ( ! $product instanceof \WC_Product ) {
			wc_doing_it_wrong( __FUNCTION__, __( 'Invalid product object.', 'woocommerce' ), '9.8.0' );
			return $variation_image_ids;
		}
```

File: plugins/woocommerce/src/Blocks/Utils/ProductGalleryUtils.php [hunk 5]
```diff
@@ -37,15 +72,40 @@ public static function get_product_gallery_image_data( $product ) {
...
+			$variations = $product->get_children();
+			foreach ( $variations as $variation_id ) {
+				$variation = wc_get_product( $variation_id );
+				if ( $variation ) {
+					$variation_image_id = $variation->get_image_id();
+					if ( ! empty( $variation_image_id ) && ! in_array( strval( $variation_image_id ), $variation_image_ids, true ) ) {
+						$variation_image_ids[] = strval( $variation_image_id );
+					}
+				}
+			}
```
Comment (cpapazoglou) [inline plugins/woocommerce/src/Blocks/Utils/ProductGalleryUtils.php]: Should we wrap this in a try-catch block?

File: plugins/woocommerce/src/Blocks/Utils/ProductGalleryUtils.php [hunk 6]
```diff
@@ -15,17 +15,52 @@ class ProductGalleryUtils {
...
+		$all_images    = array_merge( $image_data['gallery_images'], $image_data['variation_images'] );
+		$unique_images = array();
+		$seen_ids      = array();
+		foreach ( $all_images as $image ) {
+			if ( ! isset( $seen_ids[ $image['id'] ] ) ) {
+				$unique_images[]          = $image;
+				$seen_ids[ $image['id'] ] = true;
+			}
+		}
+		$image_data['all_images'] = $unique_images;
```
Comment (cpapazoglou) [inline plugins/woocommerce/src/Blocks/Utils/ProductGalleryUtils.php]: It seems that `gallery_images` and `variation_images` are not used and only `all_images` is used? In this case we can simplify a lot of things including creating a unique array of `gallery_image_ids` and then just returning `self::get_image_src_data( $gallery_image_ids );`

**Review by cpapazoglou — CHANGES_REQUESTED** [review]
Followed the testing instructions, it's nice seeing that a variation image is now included in the gallery even if it hasn't been entered there 💪.

It seems we should add it in the thumbnails too

CleanShot 2025-03-06 at 15 59 04@2x

Also, I think it will be useful adding some tests for `get_product_gallery_image_data`.

**Comment by tjcafferkey** [comment]
>It seems we should add it in the thumbnails too

I think this will be tackled separately as the thumbnails logic is bit more self-contained. Also if we are moving to a thumbnail slider then it will be fixed then anyway.

**Comment by tjcafferkey** [comment]
@cpapazoglou thanks for your feedback I have implemented basically all of your suggestions! Im going to work on adding some tests now to this method.

**Comment by cpapazoglou** [comment]
> > It seems we should add it in the thumbnails too
> 
> I think this will be tackled separately as the thumbnails logic is bit more self-contained. Also if we are moving to a thumbnail slider then it will be fixed then anyway.

I am afraid that if variation images are not injected now in [get_product_gallery_images](https://github.com/woocommerce/woocommerce/blob/79150aeb8c91dab4c3521d07c83f86df0d0a2178/plugins/woocommerce/src/Blocks/BlockTypes/ProductGalleryThumbnails.php#L147) we might end up forgetting it. We can do it as a follow up issue though.

File: plugins/woocommerce/tests/php/src/Blocks/Utils/ProductGalleryUtilsTest.php [hunk 7]
```diff
@@ -0,0 +1,71 @@
...
+
+		$this->assertArrayHasKey( 'image_ids', $image_data );
+		$this->assertArrayHasKey( 'images', $image_data );
+		$this->assertNotEmpty( $image_data['image_ids'] );
+		$this->assertNotEmpty( $image_data['images'] );
+
+		// Assert that the keys of $image_data['image_ids'] are IDs.
+		foreach ( $image_data['image_ids'] as $image_id ) {
+			$this->assertIsString( $image_id );
+			$image_id = intval( $image_id );
```
Comment (cpapazoglou) [inline plugins/woocommerce/tests/php/src/Blocks/Utils/ProductGalleryUtilsTest.php]: is this required? I guess they should already be `int` and not some kind of mixed value.

Comment (cpapazoglou) [reply plugins/woocommerce/tests/php/src/Blocks/Utils/ProductGalleryUtilsTest.php]: Ahhhhh

```
/**
	 * Get main image ID.
	 *
	 * @since  3.0.0
	 * @param  string $context What the value is for. Valid values are view and edit.
	 * @return string
	 */
	public function get_image_id( $context = 'view' ) {
		return $this->get_prop( 'image_id', $context );
	}
```

**Review by cpapazoglou — APPROVED** [review]
Thanks for addressing the feedback and adding tests.
Tested it again and works as advertised.

**Review by cpapazoglou — APPROVED** [review]
Testing this again after the updates, I confirm it's working.

Just opened an unrelated issue https://github.com/woocommerce/woocommerce/issues/56216
