### PR TITLE
Fix 'too much recursion' error when interacting with the Add to Cart + Options quantity selector

### LINKED ISSUE #59523: Add to Cart + Options: 'too much recursion' error when a Quantity Selector button is clicked
When changing the quantity of a product using the Quantity Selector buttons, there is a JS error in the console.

## **To Reproduce**

1. Go to *Appearance* > *Editor* > *Templates* > *Single Product*.
2. Click on the *Add to Cart with Options* block and update to the blockified version.
3. Go to the page of a product in the frontend.
4. Click on the quantity selector buttons.
5. Notice the JS error in your console.

[https://github.com/user-attachments/assets/0fb05fe6-914d-4170-a960-aaca89a5404a](https://github.com/user-attachments/assets/0fb05fe6-914d-4170-a960-aaca89a5404a)

## **Expected behavior**

There should be no error.

### PR DESCRIPTION
**Pull request by Aljullu**
### Changes proposed in this Pull Request:

Closes https://github.com/woocommerce/woocommerce/issues/59523.

(For Bug Fixes) Bug introduced in PR https://github.com/woocommerce/woocommerce/pull/59408.

Since #59408, we were updating the quantity inputs inside the _Add to Cart + Options_ block when the quantity changed. That allows us to avoid incorrect quantities being added to the cart. But I missed it was _alwasys_ triggered, even when the input and the new value were the same, causing an infinite recursion. :man_facepalming: 

Thanks @helgatheviking for reporting this issue and the potential fix.

### How to test the changes in this Pull Request:

1. Go to *Appearance* > *Editor* > *Templates* > *Single Product*.
2. Click on the *Add to Cart with Options* block and update to the blockified version.
3. Go to the page of a product in the frontend.
4. Click on the quantity selector buttons.
5. Verify there are no JS errors in your console.

### CODE REVIEW

**Comment by helgatheviking** [comment]
This fixes the recursion for me :muscle:

File: plugins/woocommerce/client/blocks/assets/js/blocks/add-to-cart-with-options/frontend.ts [hunk 1]
```diff
@@ -47,9 +47,7 @@ const getInputElementFromEvent = (
 	let inputElement = null;
 
 	if ( event.target instanceof HTMLButtonElement ) {
-		inputElement = event.target.parentElement?.querySelector(
-			'.input-text.qty.text'
-		);
+		inputElement = event.target.parentElement?.querySelector( '.qty' );
```
Comment (Aljullu) [inline plugins/woocommerce/client/blocks/assets/js/blocks/add-to-cart-with-options/frontend.ts:50]: This isn't needed for the fix, but given that it's a small change, I included it in this PR. We discussed it in the [WooCommerce Slack](https://woocommercecommunity.slack.com/archives/C03MCL9RTAR/p1751984653541299): there was no reason why this selector needed to include the `.input-text` and `.text` classes, as `.qty` is more intentional than the other two. In the future, this might make it easier for extensions to reuse this logic.

Comment (helgatheviking) [reply plugins/woocommerce/client/blocks/assets/js/blocks/add-to-cart-with-options/frontend.ts:50]: Could we do the same thing [here](https://github.com/woocommerce/woocommerce/blob/68855a96f8ba6248328fe09b4c5d66c6bb0dc42a/plugins/woocommerce/client/blocks/assets/js/blocks/add-to-cart-with-options/style.scss#L38) in the styles?

Comment (Aljullu) [reply plugins/woocommerce/client/blocks/assets/js/blocks/add-to-cart-with-options/frontend.ts:50]: Fair enough, done in 14178c7bea504024284d365fd80da39db9405ad3.

**Review by kmanijak — APPROVED** [review]
I confirm the error is gone and quantities are handled as expected. Checked:
- ✅ using +/- buttons
- ✅ manually changing quantity.

(Sorry I missed this error when reviewing https://github.com/woocommerce/woocommerce/pull/59408 🙇 I don't recall seeing it).
