### PR TITLE
Hide Postcode/Zip field on billing/shipping form when Ghana is selected

### LINKED ISSUE #26270: Hide the Postcode/Zip field on the billing/shipping form when Ghana is selected
### Explain the issue
Ghana has no post codes, but entering a post code is currently required when Ghana is selected at checkout

### Steps to reproduce the issue

1. When checking out, select Ghana as billing/shipping address
2. Attempt to pay without entering a post code

You'll get an error message saying "Postcode/Zip is not a valid Postcode/Zip"

### Expected behavior
When Ghana is selected, the Postcode/Zip field should be hidden

### Isolating the problem (mark completed items with an [x]):

* [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
* [x] This bug happens with a default WordPress theme active, or Storefront.
* [x] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by tolu-paystack**
### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes #26270.

### How to test the changes in this Pull Request:

See #26270.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

Hides the Postcode/Zip field on the billing/shipping form when Ghana is selected.

### CODE REVIEW

File: includes/class-wc-countries.php [hunk 1]
```diff
@@ -944,6 +944,16 @@ public function get_country_locale() {
 							'required' => false,
 						),
 					),
+					'GH' => array(
+						'postcode' => array(
+							'label'    => __( 'Postcode', 'woocommerce' ),
```
Comment (claudiosanches) [inline includes/class-wc-countries.php:949]: You don't need to include a label if this is a hidden field.

File: includes/class-wc-countries.php [hunk 2]
```diff
@@ -944,6 +944,16 @@ public function get_country_locale() {
...
+							'required' => false,
+							'hidden'   => true,
+						),
+						'state'    => array(
+							'label' => __( 'State', 'woocommerce' ),
```
Comment (claudiosanches) [inline includes/class-wc-countries.php:954]: Why you need to change this label?

**Review by claudiosanches — CHANGES_REQUESTED** [review]

File: includes/class-wc-countries.php (hunk 1 above)
Comment (tolu-paystack) [reply includes/class-wc-countries.php:949]: Ok. I just used the entry for Nigeria(NG) as a frame of reference for this, because I know the field gets hidden when you select Nigeria. Should I remove the label then?

File: includes/class-wc-countries.php (hunk 2 above)
Comment (tolu-paystack) [reply includes/class-wc-countries.php:954]: The state label? Again, just used another country that's already hidden as reference. Sorry if I did this wrong, first commit to the repo :/

File: includes/class-wc-countries.php (hunk 1 above)
Comment (tolu-paystack) [reply includes/class-wc-countries.php:949]: @claudiosanches I see what you mean, I'll edit this now

File: includes/class-wc-countries.php (hunk 2 above)
Comment (tolu-paystack) [reply includes/class-wc-countries.php:954]: @claudiosanches I should have actually changed the label to 'Region'. I'll edit this now as well

**Comment by tolu-paystack** [comment]
@claudiosanches please see new commit for changes

**Comment by juliaamosova** [comment]
Adding a note here and not on the issue since there is already PR. 

There is some conflicting information about Ghana zip codes that I can find:

- [Wikipedia suggests there are postcodes](https://en.wikipedia.org/wiki/Postal_codes_in_Ghana)
- [Zipcodespostal.com says there are none](https://www.zipcodespostal.com/ghana-zip-codes/)
- [There is a plugin that allows to bypass zipcode field in WooCommerce for countries that don't have zip codes](https://elextensions.com/knowledge-base/process-woocommerce-shipping-countries-no-zip-code/) - apparently, there are more of them

Should we discuss this further @claudiosanches?

**Comment by tolu-paystack** [comment]
@juliaamosova for added context, we(Paystack) are a payment gateway operating in Nigeria and Ghana and have multiple team members in Ghana with on-the-ground knowledge of daily life there. This issue was actually flagged by a member of our team in Ghana when he was trying to make a purchase from a Ghanaian merchant using WooCommerce. He was unable to because of the error thrown by not having the Postcode. 

Adoption of the National Digital Address System is still far from universal, even though it was announced a few years ago, so most people still don't use it. As a result, it's affecting our conversions in the country, as customers abandon orders at this point unless they know to just enter a random number in the field

**Comment by tolu-paystack** [comment]
Hi @juliaamosova @claudiosanches just wanted to follow up on this. Our merchants' customers are still experiencing issues when trying to checkout due to this, so we're hoping we can resolve the issue as soon as possible for them.

**Comment by claudiosanches** [comment]
But why not just make it not required? Since there's a postcode system in place, people may still want to use it.

**Comment by tolu-paystack** [comment]
@claudiosanches that makes sense. I'll make the necessary changes

**Comment by tolu-paystack** [comment]
@claudiosanches requested change has been made

**Comment by tolu-paystack** [comment]
@claudiosanches sorry to bug you, just following up on this as well. I've made the required changes

**Comment by tolu-paystack** [comment]
hi @claudiosanches just following up again

**Review by claudiosanches — CHANGES_REQUESTED** [review]
Oops..

**Review by claudiosanches — APPROVED** [review]
Looks good now.
Thanks for your contribution!
