### PR TITLE
Fix SQL syntax error in order search queries #53023

### LINKED ISSUE #53023: SQL syntax error on order search at the admin end
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

SQL syntax error on order search at the admin end

### Expected behavior

Searching for an order should return relevant results without errors.

### Actual behavior

A SQL syntax error occurs. https://webkul.chatwhizz.com/share/screenshot/673ec46c09ce574ce8b911bf

### Steps to reproduce

1. Go to the WordPress Admin.
2. Navigate to WooCommerce > Orders.
3. Use the search bar to search for an order using string(abc) terms or patterns and select order id in the option.
4. Observe the SQL syntax error displayed. https://webkul.chatwhizz.com/share/screenshot/673ec46c09ce574ce8b911bf

### WordPress Environment

<details><summary>System Status Report</summary>

```
### WordPress Environment ###

WordPress address (URL): [Redacted]
Site address (URL): [Redacted]
WC Version: 9.4.2
Legacy REST API Package Version: The Legacy REST API plugin is not installed on this site.
Action Scheduler Version: ✔ 3.8.2
Log Directory Writable: ✔
WP Version: 6.7
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.41 (Ubuntu)
PHP Version: 8.2.25
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.68.0
OpenSSL/1.1.1f

SUHOSIN Installed: –
MySQL Version: 8.0.40-0ubuntu0.20.04.1
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

[REDACTED]

### Post Type Counts ###

attachment: 26
page: 8
post: 2
product: 21
product_variation: 7
revision: 12
shop_order_placehold: 23
wp_font_face: 33
wp_font_family: 12
wp_navigation: 1

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (6) ###

Loco Translate: by Tim Whitlock – 2.6.14
WhatsApp Order Notifications: by Webkul – 1.0.0
WooCommerce: by Automattic – 9.4.2
WP Mail Logging: by WP Mail Logging Team – 1.13.1
WP Mail SMTP: by WP Mail SMTP – 4.2.0
WP PHP Console (Forked for wppcd): by Fulvio Notarstefano – 9.9.10

### Inactive Plugins (1) ###

WooCommerce Matrix Multi Level Marketing: by Webkul – 1.0.0

### Settings ###

Legacy API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 67 KB

### WC Pages ###

Shop base: #7 - /shop/
Cart: #8 - /cart/ -  Contains the woocommerce/cart block
Checkout: #9 - /checkout/ -  Contains the woocommerce/checkout block
My account: #10 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 4.6.0
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
pattern-toolkit-full-composability
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
printful
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page
launch-your-store

Disabled Features: product-data-views
experimental-blocks
minified-js
product-pre-publish-modal
settings
async-product-editor-category-field
product-editor-template-system
blueprint
reactify-classic-payments-settings
use-wp-horizon

Daily Cron: ✔ Next scheduled: 2024-11-22 05:55:15 +00:00
Options: ✔
Notes: 72
Onboarding: completed

### Action Scheduler ###

Complete: 67
Oldest: 2024-10-23 12:12:04 +0000
Newest: 2024-11-21 04:29:24 +0000

Failed: 2
Oldest: 2024-07-24 06:00:12 +0000
Newest: 2024-11-20 10:53:23 +0000

Pending: 3
Oldest: 2024-11-21 09:38:01 +0000
Newest: 2024-11-26 09:37:19 +0000


### Status report information ###

Generated at: 2024-11-21 06:42:44 +00:00
```
</details>

### Isolating the problem

- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by akhil-webkul**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request: 

Closes #53023 

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

### 1. Identify the Issues

Two issues need to be addressed:- https://webkul.chatwhizz.com/share/screenshot/673ec46c09ce574ce8b911bf

### -> generate_where Method Issue:

Empty conditions were being added, causing invalid SQL syntax (e.g., WHERE ()).
Solution: Return an empty string when the condition list is empty.

### -> build_query Method Issue:

Empty values in the **$this->where** array led to invalid SQL (e.g., AND ()).
Solution: Add a check to exclude empty conditions.

### 2. Apply the Fixes

Update generate_where Method

### Replace the original code:
```php
$where_statement = implode( ' OR ', $where );
return " ( $where_statement ) ";
```

### With the improved version:
```php
$where_statement = implode( ' OR ', $where );
return $where_statement ? " ( $where_statement ) " : '';
```

**This ensures no empty WHERE clause is added when no valid conditions exist.**

### Update build_query Method
Replace:
```php
$where = '1=1';
foreach ( $this->where as $_where ) {
    $where .= " AND ({$_where})";
}
```
With:
```php
$where = '1=1';
foreach ( $this->where as $_where ) {
    if ( $_where ) { // Include only non-empty conditions
        $where .= " AND ({$_where})";
    }
}
```

This prevents invalid SQL caused by empty conditions.

### 3. Test the Changes
Test Scenarios
1. Empty **$this->where** Array:
     Query should result in a valid WHERE 1=1.

2. Valid **$this->where** Conditions:
     Verify all valid conditions are included in the SQL.

2. Mixed Empty and Valid Conditions:
    Ensure only valid conditions are added.

### Testing Tips
Add unit tests for generate_where and build_query to validate these changes.
Test the behavior of the order search feature to ensure proper results are returned.

### Final Note
These changes improve query robustness and prevent SQL errors, ensuring WooCommerce's functionality remains stable.

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

### CODE REVIEW

**Comment by barryhughes** [comment]
Thanks for this submission, @akhil-webkul. Regarding the testing instructions:

> Empty $this->where Array:
> Query should result in a valid WHERE 1=1.

Do you have a sense as to the conditions needed to replicate this problem, *without* modifying the code (or modifying variables at runtime via debug code)? I did take a look at #53023 and saw this note in the *steps to replicate:*

> Use the search bar to search for an order using string(abc) terms or patterns and select order id in the option.

However, unless I'm misunderstanding, I'm not sure I can find the necessary input string needed to see the problem.

Possibly we should still harden things and protect against the possibility, but I'd still like to understand the conditions under which you experience this before we proceed.

**Comment by akhil-webkul** [comment]
Hello @barryhughes 

Thank you for taking the time to review and focus on our PR request.

To reproduce the issue, please follow these steps:

1. Go to the WooCommerce -> Orders page.
2. Select an order ID from the options, enter a customer name or email, and click the Search button.
3. This will result in an SQL syntax error.

The error occurs because an empty condition is being added to the SQL query, which causes the syntax issue.

For further clarification, we have also provided a video with detailed instructions. 

Video - https://webkul.chatwhizz.com/share/view-recording/674d38ee5658cb0570865030

Kindly take a look at it.

**Comment by akhil-webkul** [comment]
@barryhughes Have you checked my [previous comment](https://github.com/woocommerce/woocommerce/pull/53025#issuecomment-2510564096), details and process are provided there.

File: plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableSearchQuery.php [hunk 1]
```diff
@@ -164,7 +164,7 @@ private function generate_where(): string {
 
 		$where_statement = implode( ' OR ', $where );
 
-		return " ( $where_statement ) ";
+		return $where_statement ? " ( $where_statement ) " : '';
```
Comment (barryhughes) [inline plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableSearchQuery.php]: The result of the call to `$this->generate_where_for_search_filter()` is filterable and so, while the current solution covers the scenario you've described, I think it may be worth doing something more explicit than testing if the string is truthy (because something like `(string) ' '` will still pass the test, yet could still lead to the same problem of an empty where clause).

What do you think of changing the earlier block (beginning line 159) from:

```php
$search_where = $this->generate_where_for_search_filter( $search_filter );
if ( ! empty( $search_where ) ) {
	$where[] = $search_where;
}
```

To:

```php
$search_where = trim( $this->generate_where_for_search_filter( $search_filter ) );
if ( strlen( $search_where ) > 0 ) {
	$where[] = $search_where;
}
```

Similarly, on this line:

```suggestion
		return ( strlen( $where_statement ) > 0 ) ? " ( $where_statement ) " : '';
```

We could be similarly explicit in `OrdersTableQuery::build_query()`.

**Review by barryhughes — CHANGES_REQUESTED** [review]
Thanks! This looks good, but I think we can/should tighten things a little more.

**Comment by akhil-webkul** [comment]
@barryhughes Yes The method $this->generate_where_for_search_filter() always returns an empty string when no conditions are met. However, there is a possibility that an (string) '  ' string could still be passed via the woocommerce_hpos_generate_where_for_search_filter filter.

I have implemented stricter checks to address this issue and have [committed](https://github.com/woocommerce/woocommerce/pull/53025/commits/fbc78e398c8687d891bba446cd26483696b32506) the changes. Please review and merge my PR.

Thank you very much for your time and consideration.

**Review by barryhughes — APPROVED** [review]
Tests well, I can't bring about the empty where clause error any longer. I'll add a changelog entry, and confirm tests are passing, then I think we'll be good to merge :+1:

Thanks for contributing!

**Comment by barryhughes** [comment]
E2E fails seem unrelated, but re-running to be safe.

**Comment by akhil-webkul** [comment]
@barryhughes Thank you for merging my PR I appreciate the opportunity to contribute to this project and your guidance throughout the process. It’s been a great experience collaborating with the team, and I look forward to contributing more in the future.
