### PR TITLE
Add migration to fix incorrect product review count.

### LINKED ISSUE #27688: [GlobalStep - WooCommerce 4.5.2] On front-end, Review count fails to update when user adds a review from WooCommerce dashboard.
## Bug Description:
Review count fails to update on front end when user adds a review from WooCommerce dashboard.

## Environment:
Windows 10, Mac Mojave:10.14.6 (18G103)
Browser: Chrome(Version 85.0.4183.83 (64-bit))
                 Firefox(Version 80.0.1)(64-bit)
                 Safari(Version 13.1.1)

## Steps To Reproduce:
1. Create any test site using Jurassic Ninja.
1. Install and activate all required plugins.
1. Click on "Run the Setup Wizard"
1. Complete the onBoarding process.
1. Go to Products->Add New.
1. Create a Product.
1. Add a Comment to a Product and Update the product.
1. Click on "Preview" option and Scroll down to Reviews section on frontend.
1. Observe that Review count fails to update on front-end.

**Note:** 
Reviews that are added from dashboard when unapproved from "WooCommerce->Comments"  it fails to reflect under "Reviews" icon present on "WooCommerce->Home".

## Actual Result:
Review count fails to update on front end when user adds a review from WooCommerce dashboard.

## Expected Result:
Review count should update on front end when user adds a review from WooCommerce dashboard.

## Artifacts:
[#27688.zip](https://github.com/woocommerce/woocommerce/files/5233325/27688.zip)

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

<details>
````
### WordPress Environment ###

WordPress address (URL): https://relieved-anaconda.jurassic.ninja
Site address (URL): https://relieved-anaconda.jurassic.ninja
WC Version: 4.5.2
REST API Version: ✔ 4.5.2
WC Blocks Version: ✔ 3.1.0
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.5.0
Log Directory Writable: ✔
WP Version: 5.5.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.46 (Unix) OpenSSL/1.0.2g
PHP Version: 7.4.10
PHP Post Max Size: 1 GB
PHP Time Limit: 30
PHP Max Input Vars: 5000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.7.31-0ubuntu0.16.04.1-log
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.5.2
WC Database Prefix: wp_
Total Database Size: 4.51MB
Database Data Size: 3.05MB
Database Index Size: 1.46MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailchimp_carts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailchimp_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 2.03MB + Index: 0.08MB + Engine InnoDB
wp_postmeta: Data: 0.13MB + Index: 0.06MB + Engine InnoDB
wp_posts: Data: 0.05MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 24
page: 6
post: 2
product: 21
product_variation: 11
shop_order: 3

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (10) ###

Query Monitor: by John Blackbourn – 3.6.4
Companion Plugin: by Osk – 1.17
Facebook for WooCommerce: by Facebook – 2.0.1 – Installed version not tested with active version of WooCommerce 4.5.2
Jetpack by WordPress.com: by Automattic – 8.9
Google Ads for WooCommerce: by Kliken – 1.0.4 – Installed version not tested with active version of WooCommerce 4.5.2
Mailchimp for WooCommerce: by Mailchimp – 2.4.5 – Installed version not tested with active version of WooCommerce 4.5.2
WooCommerce Beta Tester: by WooCommerce – 2.0.1 – Installed version not tested with active version of WooCommerce 4.5.2
WooCommerce Payments: by Automattic – 1.4.1 – Installed version not tested with active version of WooCommerce 4.5.2
WooCommerce Services: by Automattic – 1.24.2 – Installed version not tested with active version of WooCommerce 4.5.2
WooCommerce: by Automattic – 4.5.2

### Inactive Plugins (2) ###

Akismet Anti-Spam: by Automattic – 4.1.6
Hello Dolly: by Matt Mullenweg – 1.7.2

### Dropin Plugins (1) ###

db.php: Query Monitor Database Class

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #6 - /shop/
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 2.7.0
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 7
Oldest: 2020-09-16 07:51:15 +0000
Newest: 2020-09-16 10:26:59 +0000

`
```
</details>

### PR DESCRIPTION
**Pull request by vedanshujain**
### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

In https://github.com/woocommerce/woocommerce/pull/28624 we fixed the root cause for $27688, however, we still needed a migration to fix the product review counts. This PR adds that migration, to fix the counts, we loop over all meta props with keys `_wc_review_count` and update them if they are incorrect and post belongs to a product.

Closes #27688.

### How to test the changes in this Pull Request:

1. Run this query to invalidate all product review count in your shop:
```sql
UPDATE %postmeta_table_name%
SET meta_value = '9999'
WHERE meta_key = '_wc_review_count';
```
2. Go to any product page in the frontend and check that the review count is incorrect.
3. Open a WP shell and run this command:
```php
include_once dirname( WC_PLUGIN_FILE ) . '/includes/wc-update-functions.php';
WC_Install::run_update_callback('wc_update_500_fix_product_review_count'); // Keep on calling this till output is false. 
```
4. Go back to the product page in the frontend, refresh and check that the review count is now correct.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Fix - Add migration to fix existing product review count.

### CODE REVIEW

File: includes/class-wc-comments.php [hunk 1]
```diff
@@ -340,6 +340,46 @@ public static function get_average_rating_for_product( &$product ) {
...
+		global $wpdb;
+
+		if ( empty( $product_ids ) ) {
+			return array();
+		}
+
+		$product_id_string = implode( "','", array_map( 'esc_sql', $product_ids ) );
+
+		$review_counts = $wpdb->get_results(
+			// phpcs:disable WordPress.DB.PreparedSQL.InterpolatedNotPrepared
```
Comment (roykho) [inline includes/class-wc-comments.php:362]: How come we're bypassing `prepare` here?

**Review by roykho — COMMENTED** [review]
Tested well for me. I had to checkout release/4.8 and followed the steps in the original issue to reproduce it. Then I checkout this PR and followed the testing steps and it fixed the arbitrary review count `9999` to the correct count in the product frontend.

Thanks for including the test cases. I just left small comments.

File: includes/class-wc-comments.php (hunk 1 above)
Comment (vedanshujain) [reply includes/class-wc-comments.php]: This is because of `$product_id_string` which we were expanding for `IN` clause. I thought this is the standard way to use when doing interpolation for `IN` clause.

But after your comment, I looked in detail and see how WP core is doing it, and found this reference: https://github.com/pantheon-systems/wordpress-network/blob/master/wp-includes/class-wp-meta-query.php#L639. 
This approach still ignores phpcs, but does not bypass `prepare` so I have changed the code to use this approach in https://github.com/woocommerce/woocommerce/pull/28814/commits/9f9475a18b6a80f1b256041b4c9e56d40a45ebe8. Let me know if this makes sense.

File: includes/wc-update-functions.php [hunk 2]
```diff
@@ -2219,3 +2219,67 @@ function wc_update_450_sanitize_coupons_code() {
...
+	if ( $product_id ) {
+		return update_option( 'woocommerce_update_500_last_product_id', $product_id );
+	}
+
+	delete_option( 'woocommerce_update_500_last_product_id' );
+	return false;
+}
+
+/**
+ * Update DB version to 4.5.0.
```
[the remark this answers is not in the document]
Comment (vedanshujain) [reply includes/wc-update-functions.php]: Good catch, addressed in https://github.com/woocommerce/woocommerce/pull/28814/commits/9f9475a18b6a80f1b256041b4c9e56d40a45ebe8

**Review by roykho — APPROVED** [review]
LGTM!
