### PR TITLE
Fix RIM rules processor

### LINKED ISSUE #38167: Remote Inbox Notifications rules is matching on system status url rather than the siteurl
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

I created a Remote Inbox Notification to inform WCPay merchants of a new feature. I created a test RIN using my test site as a target using an options based rule on the `siteurl.` The RIN never showed up. I ran 4 tests: Test A, B, C, and D that consisted of variations of the url:

A:
{
"type": "option",
"option_name": "siteurl",
"value": "https://pieroatomic3.wpcomstaging.com",
"default": "",
"operation": "="
}

B:
{
"type": "option",
"option_name": "siteurl",
"value": "http://pieroatomic3.wpcomstaging.com",
"default": "",
"operation": "="
}

C:
{
"type": "option",
"option_name": "siteurl",
"value": "https://pieroatomic3.wpcomstaging.com/",
"default": "",
"operation": "="
}

D:
{
"type": "option",
"option_name": "siteurl",
"value": "http://pieroatomic3.wpcomstaging.com/",
"default": "",
"operation": "="
}

Test A matched based on https://pieroatomic3.wpcomstaging.com/ which is the Site address (url) in the WC System Status report. 

My siteurl value in the wp_options table, observed with phpmyadmin, however is http://pieroatomic3.wpcomstaging.com/

### Expected behavior

The RIN rule based on the options value siteurl should have matched on the siteurl value in the wp_options table not the system status siteurl.

### Actual behavior

The rules matched on the WooCommerce system status site url value

### Steps to reproduce

1.  Go to Woocommerce.com/wp-admin and create a RIN using the UI interface (see https://woocommerce.com/wp-admin/post.php?post=18734001943713&action=edit for the actual RIN configuration)

2. Publish the RIN

3. Force run the wc_admin_daily cron job

4.  Observe that the RIN matched based on the WooCommerce system status value and not the siteurl value in the wp_options table.

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://pieroatomic3.wpcomstaging.com
Site address (URL): https://pieroatomic3.wpcomstaging.com
WC Version: 7.6.1
REST API Version: ✔ 7.6.1
WC Blocks Version: ✔ 10.1.0
Action Scheduler Version: ✔ 3.5.4
Log Directory Writable: ✔
WP Version: 6.2
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 8.0.28
PHP Post Max Size: 2 GB
PHP Time Limit: 1200
PHP Max Input Vars: 6144
cURL Version: 7.86.0
OpenSSL/1.1.1n

SUHOSIN Installed: –
MySQL Version: 10.4.25-MariaDB-log
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.6.1
WC Database Prefix: wp_
Total Database Size: 6.22MB
Database Data Size: 4.52MB
Database Index Size: 1.70MB
wp_woocommerce_sessions: Data: 0.16MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.06MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 1.11MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.36MB + Index: 0.20MB + Engine InnoDB
wp_posts: Data: 0.31MB + Index: 0.06MB + Engine InnoDB
wp_snippets: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.08MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wpml_mails: Data: 1.52MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

attachment: 33
customize_changeset: 3
jetpack_migration: 2
jp_img_sitemap: 6
jp_pay_product: 5
jp_sitemap: 6
jp_sitemap_master: 6
nav_menu_item: 6
page: 8
post: 8
product: 19
product_variation: 7
revision: 14
shop_order: 26
shop_subscription: 1
wp_global_styles: 5
wp_navigation: 1
wp_template: 1
wp_template_part: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (17) ###

Akismet Anti-Spam: by Automattic – 5.1
Code Snippets: by Code Snippets Pro – 3.3.0
Crowdsignal Forms: by Automattic – 1.7.0
WordPress.com Editing Toolkit: by Automattic – 3.64678
Gutenberg: by Gutenberg Team – 15.7.0
Jetpack: by Automattic – 12.2-a.1
Layout Grid: by Automattic – 1.8.2
Page Optimize: by Automattic – 0.5.3
Crowdsignal Polls & Ratings: by Automattic
Inc. – 3.0.10

WooCommerce Blocks: by Automattic – 10.1.0
WooCommerce EU VAT Number: by WooCommerce – 2.8.3
WooCommerce Payments Dev Tools: by Automattic –
WooCommerce Payments: by Automattic – 5.8.1
WooCommerce Shipping & Tax: by WooCommerce – 2.2.4
WooCommerce: by Automattic – 7.6.1
WP Crontrol: by John Blackbourn & crontributors – 1.15.2
WP Mail Logging: by WP Mail Logging Team – 1.11.0

### Inactive Plugins (1) ###

Classic Editor: by WordPress Contributors – 1.6.3

### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
object-cache.php: Memcached

### Must Use Plugins (1) ###

WP.com Site Helper: by  –

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
Order datastore: WC_Order_Data_Store_CPT

### WC Pages ###

Shop base: #16 - /
Cart: #118 - /cart-2/
Checkout: #99 - /checkout/
My account: #19 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 4.2.0
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: /srv/htdocs/wp-content/plugins/woo-gutenberg-products-block/templates/notices/error.php
/srv/htdocs/wp-content/plugins/woo-gutenberg-products-block/templates/notices/notice.php
/srv/htdocs/wp-content/plugins/woo-gutenberg-products-block/templates/notices/success.php

### Subscriptions ###

WCS_DEBUG: ✔ No
Subscriptions Mode: ✔ Live
Subscriptions Live URL: https://pieroatomic3.wpcomstaging.com
Subscriptions-core Library Version: 5.6.0
Subscription Statuses: wc-active: 1
WooCommerce Account Connected: ❌ No

### Store Setup ###

Country / State: United States (US) — California

### Subscriptions by Payment Gateway ###

WooCommerce Payments: wc-active: 1

### Payment Gateway Support ###

WooCommerce Payments: products
refunds
multiple_subscriptions
subscription_cancellation
subscription_payment_method_change_admin
subscription_payment_method_change_customer
subscription_payment_method_change
subscription_reactivation
subscription_suspension
subscriptions
gateway_scheduled_payments
tokenization
add_payment_method

Direct bank transfer: products
Check payments: products
Cash on delivery: products
WooCommerce Payments (Bancontact): products
refunds
multiple_subscriptions
subscription_cancellation
subscription_payment_method_change_admin
subscription_payment_method_change_customer
subscription_payment_method_change
subscription_reactivation
subscription_suspension
subscriptions
gateway_scheduled_payments
tokenization
add_payment_method

WooCommerce Payments (EPS): products
refunds
multiple_subscriptions
subscription_cancellation
subscription_payment_method_change_admin
subscription_payment_method_change_customer
subscription_payment_method_change
subscription_reactivation
subscription_suspension
subscriptions
gateway_scheduled_payments
tokenization
add_payment_method

WooCommerce Payments (giropay): products
refunds
multiple_subscriptions
subscription_cancellation
subscription_payment_method_change_admin
subscription_payment_method_change_customer
subscription_payment_method_change
subscription_reactivation
subscription_suspension
subscriptions
gateway_scheduled_payments
tokenization
add_payment_method

WooCommerce Payments (Sofort): products
refunds
multiple_subscriptions
subscription_cancellation
subscription_payment_method_change_admin
subscription_payment_method_change_customer
subscription_payment_method_change
subscription_reactivation
subscription_suspension
subscriptions
gateway_scheduled_payments
tokenization
add_payment_method

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
multichannel-marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: block-editor-feature-enabled
minified-js
new-product-management-experience
product-variation-management
settings

Daily Cron: ✔ Next scheduled: 2023-05-08 17:50:17 -07:00
Options: ✔
Notes: 65
Onboarding: completed

### WooCommerce Payments ###

Version: 5.8.1
Connected to WPCOM: Yes
Blog ID: 209425323
Account ID: acct_1LTAQF2EovLjg4D0

### Action Scheduler ###

Complete: 6
Oldest: 2023-05-05 10:49:56 -0700
Newest: 2023-05-08 08:24:45 -0700

Pending: 1
Oldest: 2023-05-08 23:27:17 -0700
Newest: 2023-05-08 23:27:17 -0700

### Status report information ###

Generated at: 2023-05-08 08:24:55 -07:00
`

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by octaedro**
### Submission Review Guidelines:

- I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
- I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
- I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/). 
- Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

This PR introduces code to accurately parse the `siteurl` during the execution of the remote inbox messages rules processor.
Closes #38167.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Install WooCommerce Payments, [WC Beta tester](https://github.com/woocommerce/woocommerce/tree/trunk/plugins/woocommerce-beta-tester) or [WC-Admin Test Helper](https://github.com/woocommerce/woocommerce-admin-test-helper).
2. To facilitate testing, I created [this plugin](https://gist.github.com/octaedro/3b8c4921b0657bd5063bac5ad68b1ffa). Install and activate it.
3. Go to `Tools > WCA Test Helper > Options` and delete the options: `_transient_timeout_woocommerce_admin_remote_inbox_notifications_specs` and `_transient_woocommerce_admin_remote_inbox_notifications_specs`
4. Go to `Tools > WCA Test Helper > Tools` and press the `Run` button next to `Run wc_admin_daily job`
5. The message titled `Increase conversions with WooPay — our fastest checkout yet` should be visible four times under the Inbox section. 

_I'm going to add some unit tests in a follow-up PR._

### CODE REVIEW

File: plugins/woocommerce/changelog/fix-38167_RIM_rules_processor [hunk 1]
```diff
@@ -0,0 +1,4 @@
+Significance: minor
+Type: fix
+
+Fix RIM rules processor
```
Comment (mattsherman) [inline plugins/woocommerce/changelog/fix-38167_RIM_rules_processor]: Some more detail/context would be good.

File: plugins/woocommerce/src/Admin/RemoteInboxNotifications/OptionRuleProcessor.php [hunk 2]
```diff
@@ -45,13 +46,32 @@ public function process( $rule, $stored_state ) {
 			$option_value = TransformerService::apply( $option_value, $rule->transformers, $default );
 		}
 
+		$rule_value = $rule->value;
+
+		if ( $is_siteurl_option ) {
+			$rule_value   = $this->getRuleValue( $rule_value );
+			$option_value = $this->getRuleValue( $option_value );
+		}
```
Comment (mattsherman) [inline plugins/woocommerce/src/Admin/RemoteInboxNotifications/OptionRuleProcessor.php]: What about using the option transformer support to:

1. Create a new transformer that cleans up a URL.
2. Dynamically insert that transformer into the rule's `transformers` if `$is_siteurl_option` and the transformer isn't in there already.

I think that would be a bit cleaner and make use of the existing processing pipeline for rules.

File: plugins/woocommerce/src/Admin/RemoteInboxNotifications/OptionRuleProcessor.php [hunk 3]
```diff
@@ -45,13 +46,32 @@ public function process( $rule, $stored_state ) {
...
+	 *
+	 * @param string $url The URL to parse.
+	 *
+	 * @return string
+	 */
+	protected function getRuleValue( $url ) {
+		$url_parts = wp_parse_url( rtrim( $url, '/' ) );
+		return isset( $url_parts['path'] ) ? $url_parts['host'] . $url_parts['path'] : $url_parts['host'];
+	}
+
```
Comment (mattsherman) [inline plugins/woocommerce/src/Admin/RemoteInboxNotifications/OptionRuleProcessor.php]: As mentioned above, I'd move this to a transformer.

**Review by mattsherman — DISMISSED** [review]
I didn't test this yet, but I did review the code...

I think that we should make use of the transformer support in RIM processing.

And, some unit tests surrounding this would be nice, in:
* https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/tests/legacy/unit-tests/woocommerce-admin/remote-inbox-notifications/transformer-service.php
* https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/tests/legacy/unit-tests/woocommerce-admin/remote-inbox-notifications/option-rule-processor.php

File: plugins/woocommerce/src/Admin/RemoteInboxNotifications/OptionRuleProcessor.php [hunk 4]
```diff
@@ -25,7 +25,7 @@ public function process( $rule, $stored_state ) {
 		$default       = isset( $rule->default ) ? $rule->default : $default_value;
 		$option_value  = get_option( $rule->option_name, $default );
 
-		if ( $is_contains && ! is_array( $option_value ) ) {
+		if ( $is_contains && ! is_array( $option_value ) && ( ! is_string( $option_value ) || ! is_string( $rule->value ) ) ) {
```
Comment (louwie17) [inline plugins/woocommerce/src/Admin/RemoteInboxNotifications/OptionRuleProcessor.php]: This additional condition is really confusing to me, maybe it would be worth adding a comment here, or is there a way to simplify this?
Why are we also checking if `rule->value` is not a string? Given the condition only sets the option value to an empty array.

Would `$is_contains && ! ( is_array( $option_value ) || is_string( $option_value ) )` be enough?

Comment (louwie17) [reply plugins/woocommerce/src/Admin/RemoteInboxNotifications/OptionRuleProcessor.php]: Maybe it be worth writing some tests around this, to make sure the scenarios are covered.

**Review by louwie17 — COMMENTED** [review]
Nice work @octaedro, this is testing well, and the code changes mostly look good, I did leave one suggestion/comment in the option rule processor condition, as it looks a bit confusing, and I am not sure what test cases we could use to better test this.

File: plugins/woocommerce/src/Admin/RemoteInboxNotifications/OptionRuleProcessor.php [hunk 5]
```diff
@@ -23,9 +23,33 @@ public function process( $rule, $stored_state ) {
...
+	 * @param mixed  $default      The default value.
+	 * @param bool   $is_contains  Indicates whether the operation is "contains".
+	 *
+	 * @return mixed The option value.
+	 */
+	private function get_option_value( $rule, $default, $is_contains ) {
+		$option_value      = get_option( $rule->option_name, $default );
+		$is_contains_valid = $is_contains && ( is_array( $option_value ) || ( is_string( $option_value ) && is_string( $rule->value ) ) );
+
+		if ( ! $is_contains_valid ) {
```
Comment (louwie17) [inline plugins/woocommerce/src/Admin/RemoteInboxNotifications/OptionRuleProcessor.php]: In order for this logic to work correctly you did have to add `$is_contains &&` to this condition as well. As any other condition outside of `$is_contains` would render `$is_contains_valid` as false, causing all the option values being overwritten to an empty array.

**Review by louwie17 — CHANGES_REQUESTED** [review]
Small suggestion in the `get_option_value` function logic as it breaks all other operations, but otherwise I like the seperation into another function.

File: plugins/woocommerce/src/Admin/RemoteInboxNotifications/OptionRuleProcessor.php (hunk 5 above)
Comment (octaedro) [reply plugins/woocommerce/src/Admin/RemoteInboxNotifications/OptionRuleProcessor.php]: Good call! I fixed it in the commit [a71ac47](https://github.com/woocommerce/woocommerce/pull/38312/commits/a71ac474c7c1e8efdb3c1a9464ab08f90e8ca231)

**Comment by octaedro** [comment]
@louwie17 I just addressed the changes you mentioned. Could you take another look at this PR?

**Review by louwie17 — APPROVED** [review]
Nice work @octaedro, thanks for adding tests and addressing the suggestions, this looks good and tested well, good to 🚢
