### PR TITLE
If `geo_hash` is known and correct, avoid an unnecessary redirect

### LINKED ISSUE #29873: Geolocation: Page reloads the first time you land on a site
**Prerequisites (mark completed items with an [x]):**
- [X] I have have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
When `Default customer location` is set to `Geolocate (With page caching support)` and the visitor lands on any page containing the correct `v=` parameter, the page reloads.

**Expected behavior**
The page should only reload if the `v=` parameter is missing or is incorrect

**Actual behavior**
The page reloads the **first** time a visitor lands on the site, regardless of the value of the `v=` parameter
This happens on both Chrome and Firefox (latest versions). It also consistently happens on remote servers and can even be seen on the waterfall of the likes of gtmetrix.

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Ensure `Default customer location` is set to `Geolocate (With page caching support)`
2. On any browser window, load a page (such as /shop)
3. Copy the entire URL, including the `v=` parameter
4. Start an incognito window
5. Press F12, go to `Network` and ensure `Preserve log` is ticked.
6. Paste the URL you copied before and press enter
7. Keep an eye on the document/html requests.

**Isolating the problem (mark completed items with an [x]):**
- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Possible cause**
On https://github.com/woocommerce/woocommerce/blob/5.2.2/assets/js/frontend/geolocation.js#L88-L89 there's no check if the current `v=` matches the hash, and is always replaced.

**Possible solutions**
1. On https://github.com/woocommerce/woocommerce/blob/5.2.2/assets/js/frontend/geolocation.js#L89 check if the `hash` is the same as the `v=`
2. On https://github.com/woocommerce/woocommerce/blob/5.2.2/assets/js/frontend/geolocation.js#L96 check if `this_page` is identical to `window.location.toString()` and if so, don't set it again and don't trigger a reload.

**Related**
https://github.com/woocommerce/woocommerce/pull/29182
https://github.com/woocommerce/woocommerce/issues/26973

### PR DESCRIPTION
**Pull request by barryhughes**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

If **WooCommerce ▸ Settings ▸ General ▸ Default customer location** is set to **Geolocate (with page caching support)**, then a hash looking like `?v=abc12345` will be appended to storefront URLs (the actual value of the hash varies according to the shopper's current location).

For example, suppose a visitor lands on a single product page:

```
https://store.front/product/a-product
```

The URL does not contain the geo hash, so we try to determine what that is and append it to the URL via a redirect to:

```
https://store.front/product/a-product?v=abc12345
```

Note that the value of the hash is also stored in a cookie named `woocommerce_geo_hash`. However, as described in the linked issue, the problem is that if that cookie no longer exists, we still perform a redirect *even if the URL already contains the correct geo hash.* Reloading the same page unnecessarily is of course an unwelcome performance hit.

Closes #29873.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

While testing, I recommend you use your browser's dev tools to monitor network requests. You may also wish to enable *'Persist/Preserve Logs'.*

1. Start by enabling **Geolocate (with page caching support)** (as described in the above description).
2. Visit the storefront (could be a single product page, or the main catalog page). You should see that a geo hash like `?v=abc12345` is appended to the URL.
3. Reload the page: there should be no redirect (this is unchanged, we're just checking this part continues to work as previously).
4. Using your browser's dev tools, delete the `woocommerce_geo_hash` cookie then reload the page (before you do this, you may also want to delete any network logs that have already been gathered). **You should not observe a redirect.** Whereas, *before* this PR, you should be able to observe a redirect back to the same URL you just arrived at.
5. Modify the URL and change the hash. For example, if it is `?v=abc12345` try changing it to `?v=xyz9876`. After entering this, you should be redirected back to the same hash as previously (again, this is unchanged, we're just checking this part continues to work as previously).

**Testing notes**

- If you are testing via a local clone of the repo, and especially if you are comparing `trunk` and this branch, remember to rebuild assets after switching branches: `pnpm run --filter='woocommerce/client/legacy' build`
- It is worth noting that the redirects can be triggered at one of two different levels: server-side and client-side. The redirect we've eliminated from step 4 was a client-side redirect, and happens after the page starts to load. I'm flagging this because, if you try replicating the problem without this PR, you should be aware that quite a large number of network requests will be logged before you see the redirect. Example:

<div align="center">clientsideredirect</div>

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Comment 

</details>

### CODE REVIEW

**Comment by rrennick** [comment]
@barryhughes This needs a trunk merge to enable the remaining 10 checks.

**Comment by barryhughes** [comment]
Updated ... though I think we'll next hit an unrelated issue with the checks re PHP 7.4. Will wait on https://github.com/woocommerce/woocommerce/pull/39830 then update again.

**Comment by barryhughes** [comment]
@rrennick checks are passing now ✅

File: plugins/woocommerce/client/legacy/js/frontend/geolocation.js [hunk 1]
```diff
@@ -83,17 +83,14 @@ jQuery( function( $ ) {
...
-
-		if ( this_page.indexOf( '?v=' ) > 0 || this_page.indexOf( '&v=' ) > 0 ) {
-			this_page = this_page.replace( /v=[^&]+/, 'v=' + hash );
-		} else if ( this_page.indexOf( '?' ) > 0 ) {
-			this_page = this_page + '&v=' + hash;
-		} else {
-			this_page = this_page + '?v=' + hash;
-		}
+		const urlQuery     = new URL( window.location ).searchParams;
+		const existingHash = urlQuery.get( 'v' )
```
Comment (rrennick) [inline plugins/woocommerce/client/legacy/js/frontend/geolocation.js]: Should this have a `;`?

**Review by rrennick — APPROVED** [review]
Nice fix @barryhughes . I just had the one optional question. Pre-approving.

File: plugins/woocommerce/client/legacy/js/frontend/geolocation.js (hunk 1 above)
Comment (barryhughes) [reply plugins/woocommerce/client/legacy/js/frontend/geolocation.js]: Good catch! Added in 1d6f912b2524960b3b7d4cffe66920861463d2b1.

**Comment by barryhughes** [comment]
Going ahead with the merge; I don't think we need extra analysis beforehand: it's a pretty contained change and, overall, a small tweak to our geocaching/cache busting which can only be seen when the **Geolocate (with page caching support)** setting is enabled.
