### PR TITLE
[HPOS CLI] Add support for backfilling specific properties or metadata

### LINKED ISSUE #41910: [CLI] Allow syncing of only missing data or even specific properties
Related to #41909, we've seen cases where only certain properties need to be synced to/from either the CPT or HPOS datastores.
For example, we've seen cases where certain metadata managed by plugins is incorrect in the HPOS datastore but correct in CPT, but HPOS has been made authoritative so the current `sync` command assumes the incorrect data is valid.

### PR DESCRIPTION
**Pull request by jorgeatorres**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

In #44281 we introduced the `wp wc hpos backfill` command which allows backfilling an order from/to the HPOS or posts datastore, regardless of which datastore is currently active. This allows merchants to fix one off errors where some data might've been modified outside of the CRUD layer.

While this works ok, sometimes there might be a need to sync just some specific metadata or properties from/to either datastore instead of the whole order. This PR introduces `--meta-keys` and `--props` arguments to `wp wc hpos backfill` which do precisely that.
While ideally orders would be backfilled in their entirety, this at least provides a last resort for some possible tricky cases.

Closes #41910.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Make sure HPOS is set as datastore in WC > Settings > Advanced > Features and also that sync (compatibility mode) is disabled.
   **Note:** It shouldn't really matter which datastore is set and we'll test syncing both ways, but this will make testing instructions more straightforward.
2. Make sure your site has at least one order with billing details. Take note of its ID.
3. Run `wp wc cot sync` to ensure that things are 100% synced between datastores.
4. Open the order from step 2 for editing:
   - Change its status to any status.
   - Change the billing first name to any value you like.
   - Add some metadata using the metadata metabox ("Custom Fields") and make a note of the "Name" you used for the field.
5. Run `wp wc hpos diff <order_id>` and confirm that the changes made above are listed as differences.
6. Run `wp wc hpos backfill <order_id> --from=hpos --to=posts --props=billing_first_name` to backfill the billing first name alone.
7. Run `wp wc hpos diff <order_id>` again and confirm that the status is no longer listed as being different. This proves that the `--props` arg limited the backfill to only that prop (leaving "status" and meta alone).
8. Let's add some metadata to the posts version with `wp post meta update <order_id> my_posts_meta my_meta_value`.
9. Run `wp wc hpos diff <order_id>` to confirm that the new meta is listed as a difference (with a value only on the 'post' side).
10. Let's migrate `my_posts_meta` from the post to the HPOS order by running `wp wc hpos backfill <order_id> --from=posts --to=hpos --meta_keys=my_posts_meta`. Run `wp wc hpos diff <order_id>` to confirm that this difference has now disappeared.
11. Now let's migrate the HPOS meta you added on step 4 by running `wp wc hpos backfill <order_id> --from=posts --to=hpos --meta_keys=<meta_key>`. Again, verify that the difference is gone with `wp wc hpos diff <order_id>`.
12. Finally, let's backfill a property (in this case, the status, which we've left alone thus far) from posts to HPOS: `wp wc hpos backfill <order_id> --from=posts --to=hpos --props=status`. Verify once more with `wp wc hpos diff <order_id>`.
13. Thank you for following such long testing instructions. You're a beautiful person 😸.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce/tests/php/src/Internal/DataStores/Orders/LegacyDataHandlerTests.php [hunk 1]
```diff
@@ -189,4 +189,60 @@ public function test_datastore_manual_backfill( $source_data_store = 'hpos' ) {
...
+		// Re-load the HPOS version and confirm billing first name is different.
+		$order_hpos = $this->sut->get_order_from_datastore( $order->get_id(), 'hpos' );
+		$this->assertNotEquals( $order_hpos->get_billing_first_name(), $order_cpt->get_billing_first_name() );
+
+		// Backfill name and confirm.
+		$this->sut->backfill_order_to_datastore( $order->get_id(), 'posts', 'hpos', array( 'props' => array( 'billing_first_name' ) ) );
+		$order_hpos = $this->sut->get_order_from_datastore( $order->get_id(), 'hpos' );
+		$this->assertEquals( $order_hpos->get_billing_first_name(), $order_cpt->get_billing_first_name() );
+		$this->assertEquals( $order_hpos->get_status(), $order_cpt->get_status() );
+	}
```
Comment (lsinger) [inline plugins/woocommerce/tests/php/src/Internal/DataStores/Orders/LegacyDataHandlerTests.php:256]: I wonder if it could be beneficial here to add a last scenario where we re-enable sync and see that even if partial backfills happened in the meantime, sync still behaves as intended. What do you think? 🤔

File: plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableDataStore.php [hunk 2]
```diff
@@ -629,6 +629,41 @@ public function backfill_post_record( $order ) {
 		do_action( 'woocommerce_hpos_post_record_backfilled', $order );
 	}
 
+	/**
+	 * Updates an order (in this datastore) from another order object.
+	 *
+	 * @param \WC_Abstract_Order $order Source order.
+	 * @return bool Whether the order was updated.
```
Comment (lsinger) [inline plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableDataStore.php:636]: Is there ever a situation where we don't return `true`? If not -- should there be? Or will there be one in the future? If we only ever return `true`, having a return value feels a bit misleading, as a caller of the method might believe based on the return value that it can fail.

File: plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableDataStore.php [hunk 3]
```diff
@@ -3007,6 +3059,17 @@ private function should_save_after_meta_change( $order, $meta = null ) {
...
-		return $order->get_date_modified() < $current_date_time && empty( $order->get_changes() ) && ( ! is_object( $meta ) || ! in_array( $meta->key, $this->ephemeral_meta_keys, true ) );
+		/**
+		 * Allows code to skip a full order save() when metadata is changed.
+		 *
+		 * @since 8.8.0
+		 *
+		 * @param bool $should_save Whether to trigger a full save after metadata is changed.
+		 */
+		return apply_filters(
+			'woocommerce_orders_table_datastore_should_save_after_meta_change',
```
Comment (lsinger) [inline plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableDataStore.php]: For improving readability a bit, could we pull out the boolean value into its own variable (e.g., `$should_save`) that we then pass to `apply_filters`?

File: plugins/woocommerce/src/Internal/DataStores/Orders/LegacyDataHandler.php [hunk 4]
```diff
@@ -321,28 +323,87 @@ public function get_order_from_datastore( int $order_id, string $data_store_id =
...
+				}
+			}
 		}
+
+		// Backfill props.
+		if ( ! empty( $fields['props'] ) ) {
+			$new_values = array_combine(
+				$fields['props'],
+				array_map(
+					fn( $prop_name ) => $src_order->{"get_{$prop_name}"}(),
```
Comment (lsinger) [inline plugins/woocommerce/src/Internal/DataStores/Orders/LegacyDataHandler.php:381]: Should we check to see if $src_order does indeed have that method before calling it?

File: plugins/woocommerce/src/Internal/DataStores/Orders/LegacyDataHandler.php [hunk 5]
```diff
@@ -372,13 +433,119 @@ private function order_meta_to_array( \WC_Order &$order ): array {
...
+		foreach ( $this->data_store->get_all_order_column_mappings() as $mapping ) {
+			$base_props = array_merge( $base_props, array_column( $mapping, 'name' ) );
+		}
+
+		return $base_props;
+	}
+
+	/**
+	 * Filters a set of HPOS row updates to those matching a specific set of order properties.
+	 * Hooked onto 'woocommerce_orders_table_datastore_db_rows_for_order'.
```
Comment (lsinger) [inline plugins/woocommerce/src/Internal/DataStores/Orders/LegacyDataHandler.php]: I wasn't sure what was meant by "hooked onto" so I looked around and tried to reword so that I'd understand it better. What do you think? 

```suggestion
	 * Called via the `woocommerce_orders_table_datastore_db_rows_for_order` filter in `backfill_order_to_datastore`.
```

File: plugins/woocommerce/src/Internal/DataStores/Orders/LegacyDataHandler.php (hunk 4 above)
Comment (lsinger) [reply plugins/woocommerce/src/Internal/DataStores/Orders/LegacyDataHandler.php:381]: Just saw that `validate_backfill_fields` already ensures this. ✅

**Review by lsinger — APPROVED** [review]
This tests as described and looks good to me -- very nice job. ☺️

I did leave a few comments, but I'd consider none of them blocking. Please handle them as you see fit and feel free to re-request a review if you prefer.

File: plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableDataStore.php (hunk 2 above)
Comment (jorgeatorres) [reply plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableDataStore.php:636]: So this docblock was just copied over from the parent class, which does return a value [based on whether the post was updated or not](https://github.com/woocommerce/woocommerce/blob/faa184e25126d975a38327e12f04e89fa0f18a19/plugins/woocommerce/includes/data-stores/abstract-wc-order-data-store-cpt.php#L680). That said, it's a bit misleading too since the metadata update could've failed (which in that case is actually all order data except status/date) and that's not taken into account.

Similarly, `save_meta_data()` doesn't tell us whether the meta was updated, so I'd say that right now we can't really tell whether the order was correctly updated or not, so the bool seems useless but we might eventually provided we make some adjustments elsewhere.

File: plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableDataStore.php (hunk 3 above)
Comment (jorgeatorres) [reply plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableDataStore.php]: Done in 70a77f2f31874ae873132455a63e74f985e99c73.

File: plugins/woocommerce/src/Internal/DataStores/Orders/LegacyDataHandler.php (hunk 5 above)
Comment (jorgeatorres) [reply plugins/woocommerce/src/Internal/DataStores/Orders/LegacyDataHandler.php]: Thanks for the suggestion @lsinger. Commited in de2402aa1559a405aeb6a970dc9e6b8431dde618.

File: plugins/woocommerce/tests/php/src/Internal/DataStores/Orders/LegacyDataHandlerTests.php (hunk 1 above)
Comment (jorgeatorres) [reply plugins/woocommerce/tests/php/src/Internal/DataStores/Orders/LegacyDataHandlerTests.php:256]: Added in c7fa5fe3b447740f5b2fb3e11c367a3f53e22e48.

**Comment by Stojdza** [comment]
> Thank you for following such long testing instructions. You're a beautiful person

Thank you for such detailed testing instructions 🙌
