### PR TITLE
Fix and improve k6 perf test My Account Open Order

### LINKED ISSUE #51234: [Flaky K6 test] My Account Open Order flaky test
K6 perf tests has been flaky in the last week. Example: https://github.com/woocommerce/woocommerce/actions/runs/10772857128/job/29871446358#step:9:1439

```
█ My Account Open Order
       ✓ is status 200
       ✗ title is: "My account – WooCommerce Core E2E Test Suite"
        ↳  66% — ✓ 2 / ✗ 1
       ✓ body contains: 
       ✓ footer contains: Built with WooCommerce
       ✓ body contains: 100
```

### PR DESCRIPTION
**Pull request by veljkho**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes #51234

This turned to be a much more worse problem with this test and not flakiness.

The first issue was related to no order creation for the customer when viewing the order via `/view-order/[id]`
The second issue was that the test itself contained `const response` that didn't allow user to see it as logged in customer, but as a guest.
The check response in the test allowed the test to pass with empty order ID.

Additionally, I fixed linting issues as it forced me locally when saving the file.

I had to update view places for this test to pass correctly.
This also includes linting issues in the test file `cart-checkout-shortcode.js` and disabling `jsdoc/require-property-description`, `@woocommerce/dependency-group` and `import/no-unresolved` (which one is disabled in every test file already).

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. All checks are green
2. The specific test should pass on CI with newly added assertions like new title with order and and the body:
 █ My Account Open Order
       ✓ is status 200
       ✓ title is: "Order # 97 – WooCommerce Core E2E Test Suite"
       ✓ body contains: Order #<mark class="order-number">97</mark> was placed
       ✓ footer contains: Built with WooCommerce

This means the changes were good and we finally test the My Account > View Order properly with a strong check in the body.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce/tests/performance/requests/shopper/my-account-orders.js [hunk 1]
```diff
@@ -29,6 +29,7 @@ import { checkResponse } from '../../utils.js';
 
 export function myAccountOrders() {
 	let my_account_order_id;
+	let response;
```
Comment (adimoldovan) [inline plugins/woocommerce/tests/performance/requests/shopper/my-account-orders.js]: Why are you re-using a global response variable? I don't see how this helps in fixing the test.

File: plugins/woocommerce/tests/performance/requests/api/orders.js [hunk 2]
```diff
@@ -84,7 +123,7 @@ export function ordersAPI() {
 		);
 		check( response, {
 			'status is 201': ( r ) => r.status === 201,
-			"body contains: 'Pending' Status": ( response ) =>
```
Comment (adimoldovan) [inline plugins/woocommerce/tests/performance/requests/api/orders.js:87]: That is [valid syntax](https://grafana.com/docs/k6/latest/javascript-api/k6/check/), I don't see why you need to remove it.

**Review by adimoldovan — CHANGES_REQUESTED** [review]

File: plugins/woocommerce/tests/performance/requests/api/orders.js (hunk 2 above)
Comment (veljkho) [reply plugins/woocommerce/tests/performance/requests/api/orders.js:87]: It works in both cases when tested locally (probably will pass also on CI), but I'm getting linting issues in CI that the response is already declared in file, as a `let response;`. Please check. @adimoldovan

File: plugins/woocommerce/tests/performance/requests/shopper/my-account-orders.js (hunk 1 above)
Comment (veljkho) [reply plugins/woocommerce/tests/performance/requests/shopper/my-account-orders.js]: I reverted the change, thanks for spotting this. It worked in both ways, but at some point, I thought this blocked the test.

File: plugins/woocommerce/tests/performance/requests/api/orders.js (hunk 2 above)
Comment (adimoldovan) [reply plugins/woocommerce/tests/performance/requests/api/orders.js:87]: Yes, that's because of the global `response`. But you don't have to delete it, only rename it. You can use `r`, just like in the above `'status is 201'` check.

**Comment by adimoldovan** [comment]
@veljkho I may be missing something here, but how is the update in the `orders.js` affecting the test in `my-account-orders.js`? I cannot see how this fixes the test, and why it was flaky before.

File: plugins/woocommerce/tests/performance/requests/api/orders.js (hunk 2 above)
Comment (veljkho) [reply plugins/woocommerce/tests/performance/requests/api/orders.js:87]: Ah I see, done in a new commit.

**Comment by veljkho** [comment]
@adimoldovan 
Before, the test was looking for the title `My Account - ` while checking the `view-order/id` page where My Account is not the title, but `Order #id - ` instead. Why it was passing then? Because there was no order created for customer user to see it. If there is no order attached, then the page would be with `My Account - ` title.

I created and attached one order for the customer user, where I also obtained the ID dynamically.

Why was it failing then sometimes? Because the title was not `My Account - ` and I'm not going further why since I realized the test was wrong from the beginning of its creation. The body check was also wrong, because checking if the body contains the order ID, even if it is empty value, it will pass. Now, with the body checking for the sentence containing the order ID, it makes the test pass or fail.

File: plugins/woocommerce/tests/performance/tests/gh-action-pr-requests.js [hunk 3]
```diff
@@ -22,7 +22,7 @@ import { ordersFilter } from '../requests/merchant/orders-filter.js';
 import { addOrder } from '../requests/merchant/add-order.js';
 import { ordersAPI } from '../requests/api/orders.js';
 import { homeWCAdmin } from '../requests/merchant/home-wc-admin.js';
-import { useCartCheckoutShortcodes } from '../setup/cart-checkout-shortcode.js';
+import { setCartCheckoutShortcodes } from '../setup/cart-checkout-shortcode.js';
```
Comment (veljkho) [inline plugins/woocommerce/tests/performance/tests/gh-action-pr-requests.js:25]: this is to avoid linting error from React Hook asking us to change the function starting with use or something about big first letter. This fix is as simple as it is.

**Comment by adimoldovan** [comment]
> Before, the test was looking for the title `My Account - ` while checking the `view-order/id` page where My Account is not the title, but `Order #id - ` instead. Why it was passing then? Because there was no order created for customer user to see it. If there is no order attached, then the page would be with `My Account - ` title.

Let me share more of my thinking.
Let's say that's the case. Then why did you add the create order in `orders.js` instead of `my-account-orders.js`?
 The flaky test is in `my-account-orders.js`. Your code changes are in `orders.js`. If you changes are indeed fixing the test, it means that `my-account-orders.js` is dependent on `orders.js`. It may be that it was like that before, but why won't you fix that dependency, and create the orders in `my-account-orders.js`?

But, I'm still not convinced that's the case, because even if `my-account-orders.js` was depending on `orders.js`, if you check the order of execution, it doesn't fit, because `my-account-orders.js` is always being executed before `orders.js`. So, then, why was it passing before? And why is it passing now? It makes no sense to me.

File: plugins/woocommerce/tests/performance/requests/api/orders.js [hunk 4]
```diff
@@ -194,6 +232,7 @@ export function ordersAPI() {
 			updateBatchItem = {
 				id: `${ post_ids[ index ] }`,
 				status: 'completed',
+				customer_id: 2,
```
Comment (adimoldovan) [inline plugins/woocommerce/tests/performance/requests/api/orders.js]: Not sure about the hardcoded id. Maybe we want to use `customerId` instead?

Comment (veljkho) [reply plugins/woocommerce/tests/performance/requests/api/orders.js]: Omg, good spot. This is leftover from earlier commits, I removed it and will push a new commit.

**Comment by veljkho** [comment]
I agree about it all, and I am confused about the test suite setup.
I can add order creation inside the test and not in `orders.js`, but I thought that file is for creating data for the whole test suite.

Let's ask @tammullen, who may know the answer about the performance test suite.
Simple question, Tam, TLDR: Is there a single file for creating orders for all the tests related to orders? And, if I want to add a new order to the test, should I do that within the specific test or somewhere else, e.g. `api/orders.js`? Thanks.

**Comment by tammullen** [comment]
An important piece of context for these k6 tests is that these tests were originally created (and still are ran today) for load tests against real hosted sites. So they needed to be flexible enough to run against any site with 1000s of iterations and be ok to have a small % of iterations fail due to server issues. They also need to be capable of running specific data profiles e.g. we want X orders created per minute. This also makes it slightly tricky to manage data, as if e.g. we create a fresh order for use in a request that extra order creation also needs to be accounted for in the load profile of the test. Doesn't mean we can't do that, but just to explain why it wasn't initially done.

> Let's ask @tammullen, who may know the answer about the performance test suite. Simple question, Tam, TLDR: Is there a single file for creating orders for all the tests related to orders? And, if I want to add a new order to the test, should I do that within the specific test or somewhere else, e.g. `api/orders.js`? Thanks.

For the my account test it looks for orders created by the `customer_username` which I think is only the `checkout-customer-login.js` requests? That seems to run after the `my-account-orders.js` in CI so yeah unless there is another order creation request running before it that is using `customer_username` it probably shouldn't have been passing at all.

**Comment by veljkho** [comment]
Thanks @tammullen for the context. It is quite complicated to manage data and tests to test load test. In this case, the test was originally created to look for an empty `/view-order/` page with the warning message there that there is no order to look for with the title at that state `My Account`. When I investigated problem I realized that to really look for an order there should be some order first to load the page with it, so creating order before the test is mandatory for it and the title would be `Order #123` then.

There was a race condition recently whether that test `checkout-customer-login.js` creates an order before or after the test `my-account-open-orders` which changes the `view-order/id` page. I would add some order to the customer and test the view order page with the order, because without the order created that page is not accessible via UI end user, there won't be `view` button in My Account to see it, so order is mandatory for this test.

Now looking where to put that order creation and to make sure the test will always have order attached to the user. Currently, it seems good, but will check once again in details. CC @adimoldovan

**Comment by adimoldovan** [comment]
> Thanks @tammullen for the context. It is quite complicated to manage data and tests to test load test. In this case, the test was originally created to look for an empty `/view-order/` page with the warning message there that there is no order to look for with the title at that state `My Account`. When I investigated problem I realized that to really look for an order there should be some order first to load the page with it, so creating order before the test is mandatory for it and the title would be `Order #123` then.
> 
> There was a race condition recently whether that test `checkout-customer-login.js` creates an order before or after the test `my-account-open-orders` which changes the `view-order/id` page. I would add some order to the customer and test the view order page with the order, because without the order created that page is not accessible via UI end user, there won't be `view` button in My Account to see it, so order is mandatory for this test.
> 
> Now looking where to put that order creation and to make sure the test will always have order attached to the user. Currently, it seems good, but will check once again in details. CC @adimoldovan

I'm reading this as "we're not really sure what's happening, let's throw some code in there (not sure where either) to create some orders". I'm insisting on first clarifying why was it passing before, why is it still passing in CI. It did not fail for a few runs actually. What is the response body in the failed response?

**Comment by veljkho** [comment]
> why was it passing before, why is it still passing in CI. It did not fail for a few runs actually. What is the response body in the failed response?

I already said that. It is passing now and before because there is no order when viewing the order page as a customer, verifying the title as `My Account` (wrongly written test).
It was sometimes failing due to a race condition with another test because another test had created an order. When viewing the order page, the title changed properly to `Order #123`, but it was looking for `My Account` instead.

When it was failing actually that was the correct test, but our checks were written to verify when it was wrong. That was confusing part. @adimoldovan 

I can add order creation and make it work as expected.

**Comment by adimoldovan** [comment]
> > why was it passing before, why is it still passing in CI. It did not fail for a few runs actually. What is the response body in the failed response?
> 
> I already said that. It is passing now and before because there is no order when viewing the order page as a customer, verifying the title as `My Account` (wrongly written test). It was sometimes failing due to a race condition with another test because another test had created an order. When viewing the order page, the title changed properly to `Order #123`, but it was looking for `My Account` instead.
> 
> When it was failing actually that was the correct test, but our checks were written to verify when it was wrong. That was confusing part. @adimoldovan
> 
> I can add order creation and make it work as expected.

Can you consistently reproduce the failure? What is the response body in the failed response?

**Comment by adimoldovan** [comment]
From what I can see:

`my_account_order_id` can be empty (and probably is, by the look of the error). The request is then made to `my-account/view-order/${ my_account_order_id }`, which instead of the expected `my-account/view-order/123` is `my-account/view-order/`. 

I suggest we start with a check on the `my_account_order_id`. If empty, we throw an error. 

Then, if missing orders is proved to be the cause, I suggest creating at least 1 order in the `setup()` function.

**Comment by veljkho** [comment]
> Can you consistently reproduce the failure? What is the response body in the failed response?

Of course, just like we see it as passing in CI mostly. I can confirm that the order ID is empty in that case.

> I suggest we start with a check on the my_account_order_id. If empty, we throw an error.

It is not possible for k6 to fail and to notify us in that case but only to see the error thrown in the console.
However, I strengthened the check in the test to fail in that case (improved body check).

> Then, if missing orders is proved to be the cause, I suggest creating at least 1 order in the setup() function.

It is the issue, confirmed from the local. I will change the place where the order is created and add a commit.

**Comment by tammullen** [comment]
> I will change the place where the order is created

Added myself as a reviewer as I would like to review that bit from a load testing POV

**Comment by adimoldovan** [comment]
> It is not possible for k6 to fail and to notify us in that case but only to see the error thrown in the console.
> However, I strengthened the check in the test to fail in that case (improved body check).

I'm not sure what you mean by `It is not possible for k6 to fail and to notify us`, but this code worked great for me right after the `my_account_order_id` is being set:

```
check( my_account_order_id, {
	'order ID is not undefined': () => {
		console.log( `order id: ${ my_account_order_id }` );
		return !! my_account_order_id;
	},
} );
```

**Comment by veljkho** [comment]
Thanks fellas for helping me move. Your help was greatly appreciated! @adimoldovan @tammullen 
The merge candidate has been committed, including all what we spoke about. 🚀

File: plugins/woocommerce/tests/performance/setup/add-customer-order.js [hunk 5]
```diff
@@ -0,0 +1,52 @@
...
+			Authorization: `Basic ${ encodedCredentials }`,
+			'Content-Type': 'application/json',
+		};
+
+		response = http.get( `${ base_url }/wp-json/wc/v3/customers`, {
+			headers: requestHeaders,
+			tags: { name: 'API - Retrieve Customer' },
+		} );
+
+		const customerId = findBetween( response.body, '"id":', ',' );
```
Comment (adimoldovan) [inline plugins/woocommerce/tests/performance/setup/add-customer-order.js]: I like how this makes an existing customer is used, but there is a chance it will pick other customer than the one used in `my-account-orders.js`. We need to use the same customer id.

File: plugins/woocommerce/tests/performance/setup/add-customer-order.js [hunk 6]
```diff
@@ -0,0 +1,52 @@
...
+		const createCustomerOrderData = {
+			customer_id: customerId,
+			status: 'completed',
+		};
+		response = http.post(
+			`${ base_url }/wp-json/wc/v3/orders`,
+			JSON.stringify( createCustomerOrderData ),
+			{
+				headers: requestHeaders,
+				tags: { name: 'API - Create Customer Order' },
```
Comment (adimoldovan) [inline plugins/woocommerce/tests/performance/setup/add-customer-order.js]: I don't think we need the tags in here.

File: plugins/woocommerce/tests/performance/setup/add-customer-order.js [hunk 7]
```diff
@@ -0,0 +1,52 @@
...
+/**
+ * Internal dependencies
+ */
+import { base_url, admin_username, admin_password } from '../config.js';
+
+/**
+ * Convert Cart & Checkout pages to shortcode.
+ */
+export function addCustomerOrder() {
+	function addOrderToCustomer() {
```
Comment (adimoldovan) [inline plugins/woocommerce/tests/performance/setup/add-customer-order.js]: Why is there a nested function instead of having everything in `addCustomerOrder()`?

**Review by adimoldovan — CHANGES_REQUESTED** [review]
Thanks @veljkho for the updates. Left some comments.

File: plugins/woocommerce/tests/performance/setup/add-customer-order.js (hunk 6 above)
Comment (veljkho) [reply plugins/woocommerce/tests/performance/setup/add-customer-order.js]: That's right, removed them.

File: plugins/woocommerce/tests/performance/setup/add-customer-order.js (hunk 7 above)
Comment (veljkho) [reply plugins/woocommerce/tests/performance/setup/add-customer-order.js]: Just followed the same design in cart-checkout-shortcode.js, in case there will be new functions added. However, I removed it in a new commit.

File: plugins/woocommerce/tests/performance/setup/add-customer-order.js (hunk 5 above)
Comment (veljkho) [reply plugins/woocommerce/tests/performance/setup/add-customer-order.js]: @adimoldovan I updated the code in add-customer-order.js completely to align with this. However, found some obstacles in the design:

1. The test suite has `customer_username` stored in `config.js` as [email address](https://github.com/woocommerce/woocommerce/blob/e35429538776c9984e6a506ca0354792584afcc6/plugins/woocommerce/tests/performance/config.js#L12).
2. There is no any customer with `customer` username on the `wcnightlysmoketest.wpcomstaging.com` test site
3. There is also [customer ID hardcoded in the config](https://github.com/woocommerce/woocommerce/blob/e35429538776c9984e6a506ca0354792584afcc6/plugins/woocommerce/tests/performance/config.js#L15), but this is not related to my code which dynamically extracts the whatever customer ID is used on any test site (so just a sidenote)

How do you think we should proceed with this now? Pinging @tammullen for the `wcnightlysmoketest.wpcomstaging.com` test site, should we maybe create a customer with `customer` username and/or can we change the `customer_username` in the `config.js` file to `customer` and add a new config for the `email`?

Comment (adimoldovan) [reply plugins/woocommerce/tests/performance/setup/add-customer-order.js]: Hardcoding the customer id would be the fast way and prone to flakiness.
The safe way would be to use the api to search for the customer that has the `customer_username` username and return the id.

Comment (adimoldovan) [reply plugins/woocommerce/tests/performance/setup/add-customer-order.js]: > The safe way would be to use the api to search for the customer that has the `customer_username` username and return the id.

Which I now see you already implemented. So we're good for the scope of this PR.

> There is no any customer with customer username on the wcnightlysmoketest.wpcomstaging.com test site

Not sure if this site is still in use, maybe for some release runs, but the CI runs are not using it. If it's in use it should be updated.

> There is also [customer ID hardcoded in the config](https://github.com/woocommerce/woocommerce/blob/e35429538776c9984e6a506ca0354792584afcc6/plugins/woocommerce/tests/performance/config.js#L15), but this is not related to my code which dynamically extracts the whatever customer ID is used on any test site (so just a sidenote)

I'm thinking we should change this, and update the customer id via the setup. But we can do this in a follow up PR. 
From the top of my head: the setup should check if the customer exist, if not create it, and return the id which is stored in the config. This way we'll always have the right data in any environment.

Comment (veljkho) [reply plugins/woocommerce/tests/performance/setup/add-customer-order.js]: > the setup should check if the customer exist, if not create it

I was thinking about the same, so done in a new commit.

Not sure about storing the customer ID in a config.js file, doesn't seem doable with k6 as JS doesn't have permission to write to a config.js file (if that's the intention). We can work on this separately.

Please take another peek and approve if everything's good.
I will wait for @tammullen 's review as well before merging.

Also question for Tam, do we need to update any var somewhere stored for maybe external sites for the `customer_username` as I added `customer_email` instead?

Comment (adimoldovan) [reply plugins/woocommerce/tests/performance/setup/add-customer-order.js]: We should do this in a follow up PR. I'm fine with leaving this as it is in this PR.

To avoid any potential misuse and flakiness I would remove the `customer_user_id` constant from config.js. From a quick check that constant is only used in `order-filter.js` in `ordersFilter()`

This is what I think we need to do:

- delete the `customer_user_id` from config.js
- extract a function to create the customer if it doesn't exist in the setup module. It should return the user id
- call that function in every test where the customer id is needed and set a global const in there
- update the test functions that required the if to accept the id as an argument

```
// gh-action-pr-requests.js
let customerUserId;

export function setup() {
	setCartCheckoutShortcodes();
	customerUserId = createCustomer();
	addCustomerOrder( customerUserId );
}

...

export function allMerchantFlow() {
	wpLogin();
	homeWCAdmin( { other: false, orders: false, reviews: false, products: false} );
	addOrder();
	orders();
	ordersSearch();
	ordersFilter( customerUserId );
	addProduct();
	products();
	coupons();
}
```

Comment (veljkho) [reply plugins/woocommerce/tests/performance/setup/add-customer-order.js]: That makes sense; please approve the PR so I can merge if @tammullen is okay with the changes.

Comment (adimoldovan) [reply plugins/woocommerce/tests/performance/setup/add-customer-order.js]: I'll let @tammullen check this out before merging. From my POV consider this approved.
Can you please create an issue for us to track the follow-up work per the above thread?

File: plugins/woocommerce/tests/performance/requests/shopper/my-account-orders.js [hunk 8]
```diff
@@ -98,9 +98,16 @@ export function myAccountOrders() {
 			}
 		);
 
+		check( my_account_order_id, {
+			'order ID is not undefined': () => {
+				console.log( `order id: ${ my_account_order_id }` );
```
Comment (tammullen) [inline plugins/woocommerce/tests/performance/requests/shopper/my-account-orders.js]: Generally we want to avoid console.log in case we generate large amounts of logs during a load test, but I think given the other changes this will hopefully not be triggered much/ever. Although maybe that means we can remove it?

**Review by tammullen — APPROVED** [review]
Thanks for the fix, improvement, and discussions!

> verifying the title as My Account (wrongly written test).

Just to clarify it wasn't intentionally wrongly written, until https://github.com/woocommerce/woocommerce/pull/50900 the page title of the view order page was still `<title>My account – WooCommerce Core E2E Test Suite</title>`, if you downgrade a site to 9.3.x or earlier the old title displays.

>  Not sure if this site is still in use

> do we need to update any var somewhere stored for maybe external sites for the customer_username as I added customer_email instead?

It is used for release testing, so we can update it's guide, I will share the link internally.

--

I think we also could have alternatively more simply solved the missing orders by re-ordering the scenarios in the `performance/tests/` files but I do like the more robust approach introduced here.

I had one question about the logging added but it's not a dealbreaker. Approving.

File: plugins/woocommerce/tests/performance/requests/shopper/my-account-orders.js (hunk 8 above)
Comment (adimoldovan) [reply plugins/woocommerce/tests/performance/requests/shopper/my-account-orders.js]: +1 on removing this. I believe it was left in my code sample for debugging.

Comment (veljkho) [reply plugins/woocommerce/tests/performance/requests/shopper/my-account-orders.js]: Done in a new commit

File: plugins/woocommerce/tests/performance/setup/add-customer-order.js (hunk 5 above)
Comment (veljkho) [reply plugins/woocommerce/tests/performance/setup/add-customer-order.js]: Sure, done in #51536

**Review by adimoldovan — APPROVED** [review]
