### PR TITLE
Fixes tax rounding issues

### LINKED ISSUE #25629: Totals calculation causes rounding problems due to wc_round_tax_total()
In WC_Cart_Totals:: calculate_totals() the taxes are always rounded before adding them to the total with wc_round_tax_total():

```
$this->set_total( 'total', round( $this->get_total( 'items_total', true ) + $this->get_total( 'fees_total', true ) + $this->get_total( 'shipping_total', true ) + wc_round_tax_total( array_sum( $this->get_merged_taxes( true ) ), 0 ), 0 ) );
```

This causes a rounding problem of 1 Cent for me in a few cases when calculating the totals with a product, a custom fee and an applied percentage discount coupon when using tax-inclusive pricing. I can provide an example if needed.

I have activated "Round tax at subtotal level, instead of rounding per line". Is there a specific reason to round taxes before adding them to the total? If I remove the call to wc_round_tax_total at this position, the total comes up correctly.

I'm on WordPress 5.3.2 and WooCommerce 3.9.1

### LINKED ISSUE #25748: Rounding is off in manual orders
**Describe the bug**

When adding items to a manual order that are tax excluded, with option `Round tax at subtotal level, instead of rounding per line` checked, total amount is off by 1 cent while it shows the correct amount for a normal order on the site.

**To Reproduce**
1. Settings: 2dp, `Round tax at subtotal level, instead of rounding per line` checked and price entered excluding tax:
Screen Shot 2020-02-25 at 4 13 49 PM
Screen Shot 2020-02-25 at 4 13 55 PM

2. Add these items to a manual order:

Screen Shot 2020-02-25 at 4 14 23 PM

3. See that the total is $40.36, while it's $40.3535, which should be rounded up to $40.35

Screen Shot 2020-02-25 at 4 14 32 PM

4. Place a test order by adding these items to cart and check out
5. See that the total amount from the order is $40.35, which is what it should be:

Screen Shot 2020-02-25 at 4 14 43 PM

**Expected behavior**
The total in the manual order is $40.36, while it's $40.3535, which should be rounded up to $40.35 as seen in the normal order

**Isolating the problem (mark completed items with an [x]):**
- [ x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ x] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by vedanshujain**
### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

This PR is a follow up from #24828, ultimately the goal is to have shared logic for rounding in both orders and cart. In this PR, I am removing individual rounding logic from multiple places and relying on logic added in #24828 . I am also relying on unit tests heavily to make sure that we don't add any regressions and calculations are correct for majority of use cases.

Another notable change is that some logic from `create_order` is not refactored into `set_data_from_cart`. This is to make that method better unit-testable. 

Closes #25629, #25748, #25641

### How to test the changes in this Pull Request:

There are multiple parts to testing this PR:

Part 1 (for 25629):
1. Set setting `Yes, I will enter prices inclusive of tax`, and `Round tax at subtotal level, instead of rounding per line ` to true.
2. Add a tax rate for 10percent.
3. Add following snippet to your theme;s function.php
```
add_action('woocommerce_cart_calculate_fees', 'set_box_fee', 10);
function set_box_fee($cart) {
    $boxFee = 1.5/1.1; // 1.5€ fee, of which we only need the net part
    $cart->add_fee(__('Packaging', 'woocommerce'), $boxFee, true);
}
```
4. Create a Product for 71.50.
5. Create a coupon for a 3 percent cart discount.
6. In a cart, try to checkout with the product added in step 4, apply the coupon. Without this patch, the total should be 70.85, with this patch it should be 70.86.

Part 2 (for #25748):
1.  Set setting `No, I will enter prices exclusive of tax`.
2. Set setting `Round tax at subtotal level, instead of rounding per line ` to true.
3. Add a tax rate of 21%.
4. Create a product for 23.85.
5. Create a manual order with the product added in step 4, and add a shipping rate for 9.5.
6. Click on recalculate, without this patch, the total will be 40.36, with this patch, it should be 40.35.

Part 3 (for #25641 )
1. Set setting `No, I will enter prices exclusive of tax`.
2. Set setting `Round tax at subtotal level, instead of rounding per line` to true.
3. Add a tax rate for 7%
4. Add another tax rate for 2.25 %. Make sure these two rates have different priorities.
5. Create a product for 22.99.
6. Add a shipping flat rate for 10.
7. Set setting `Display tax totals ` to `As a single total`.
8. Check out the product created in step 5, in the Place order page, verify that tax total is 3.05.
9. Place the order. In the order details screen, without this patch, order total will change to 3.06,  whereas with this patch, it will stay at 3.05

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Fix - Remove some of the individual rounding logic to make sure we round at certain places only.

### CODE REVIEW

**Comment by Konamiman** [comment]
I have tried the test cases and they all work as expected 👍🏻

**Review by claudiosanches — APPROVED** [review]
Great work!

File: tests/unit-tests/order/class-wc-tests-orders.php [hunk 1]
```diff
@@ -52,4 +52,110 @@ public function test_order_calculate_total_rounding_24695() {
...
+		$tax_rate = array(
+			'tax_rate_country'  => '',
+			'tax_rate_state'    => '',
+			'tax_rate'          => '21.0000',
+			'tax_rate_name'     => 'CGST',
+			'tax_rate_priority' => '1',
+			'tax_rate_compound' => '0',
+			'tax_rate_shipping' => '1',
+			'tax_rate_order'    => '1',
+			'tax_rate_class'    => 'tax_1',
```
Comment (claudiosanches) [inline tests/unit-tests/order/class-wc-tests-orders.php:74]: It doesn't work properly because there's no tax class created for it.

Here how to create the tax class:
```php
WC_Tax::create_tax_class( 'tax_1' );
```

File: tests/unit-tests/cart/cart.php [hunk 2]
```diff
@@ -2009,6 +2009,57 @@ public function test_changing_tax_class_via_filter_issue_23340() {
...
+		$tax_rate    = array(
+			'tax_rate_country'  => '',
+			'tax_rate_state'    => '',
+			'tax_rate'          => '10.0000',
+			'tax_rate_name'     => 'TAX10',
+			'tax_rate_priority' => '1',
+			'tax_rate_compound' => '0',
+			'tax_rate_shipping' => '1',
+			'tax_rate_order'    => '1',
+			'tax_rate_class'    => '10percent',
```
Comment (claudiosanches) [inline tests/unit-tests/cart/cart.php:2030]: Need to create this tax class first with `WC_Tax::create_tax_class( '10percent' );`

**Review by claudiosanches — CHANGES_REQUESTED** [review]
There's some errors in the unit tests that doesn't get the correct tax class because those tax classes need to get created first.

**Comment by vedanshujain** [comment]
@claudiosanches I have removed tax class props because they were not being used anyway. WDYT?

**Review by claudiosanches — APPROVED** [review]
Works fine, seems like only broke some coding standards on Travis so seems good to go.

**Comment by vedanshujain** [comment]
Note: Adding a high impact label because this affects lots of core flows and with more changes merged, it's important to keep an eye and test this patch again.

**Comment by starypop** [comment]
Hey @vedanshujain, could you please take a look at my issue #25447 and verify if this PR also fixes that bug?

It seems that it might be somehow connected, but the issue is not mentioned in PR's references.
