### PR TITLE
Prevent fatals while uninstalling with `WC_REMOVE_ALL_DATA`

### LINKED ISSUE #39881: PHP Fatal when uninstalling the plugin and `WC_REMOVE_ALL_DATA` constant set to `true`
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When deleting the plugin and the `WC_REMOVE_ALL_DATA` constant is set to `true` I get a PHP fatal error.

### Expected behavior

 I would expect the WooCommerce plugin to be deleted and all of its data removed, and mostly getting no errors.

### Actual behavior

The Delete button link turns into "Deleting..."
An admin notice appears saying: `Deletion failed: There has been a critical error on this website.Learn more about troubleshooting WordPress.`

 - nothing else happens. 

Refreshing the page you see the plugin isn't there anymore, so it was deleted, although not all of its data was, plus in the error log you'd see something like:
```
[24-Aug-2023 10:04:19 UTC] PHP Warning:  require(/shared/httpd/wptest/wordpress/wp-content/plugins/woocommerce/src/Internal/Admin/Analytics.php): failed to open stream: No such file or directory in /shared/httpd/wptest/wordpress/wp-content/plugins/woocommerce/vendor/jetpack-autoloader/class-php-autoloader.php on line 90
[24-Aug-2023 10:04:19 UTC] PHP Fatal error:  require(): Failed opening required '/shared/httpd/wptest/wordpress/wp-content/plugins/woocommerce/src/Internal/Admin/Analytics.php' (include_path='.:/usr/local/lib/php') in /shared/httpd/wptest/wordpress/wp-content/plugins/woocommerce/vendor/jetpack-autoloader/class-php-autoloader.php on line 90
[24-Aug-2023 10:04:19 UTC] PHP Fatal error:  Uncaught Error: Class 'ActionScheduler_Lock' not found in /shared/httpd/wptest/wordpress/wp-content/plugins/woocommerce/packages/action-scheduler/classes/abstracts/ActionScheduler.php:29
Stack trace:
#0 /shared/httpd/wptest/wordpress/wp-content/plugins/woocommerce/packages/action-scheduler/classes/ActionScheduler_QueueRunner.php(106): ActionScheduler::lock()
#1 /shared/httpd/wptest/wordpress/wp-includes/class-wp-hook.php(310): ActionScheduler_QueueRunner->maybe_dispatch_async_request('')
#2 /shared/httpd/wptest/wordpress/wp-includes/class-wp-hook.php(334): WP_Hook->apply_filters(NULL, Array)
#3 /shared/httpd/wptest/wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#4 /shared/httpd/wptest/wordpress/wp-includes/load.php(1252): do_action('shutdown')
#5 [internal function]: shutdown_action_hook()
#6 {main}
  thrown in /shared/httpd/wptest/wordpress/wp-content/plugins/woocommerce/packages/action-scheduler/classes/abstracts/ActionScheduler.php on line 29
 ```
 
If you wait a bit more you'll also see a warning about the action_scheduler. Please note that I hadn't activated WooCommerce yet:
```
[24-Aug-2023 10:05:05 UTC] Cron reschedule event error for hook: action_scheduler_run_queue, Error code: invalid_schedule, Error message: Event schedule does not exist., Data: {"schedule":"every_minute","args":["WP Cron"],"interval":60}
```

Also note that if you instead activate WooCommerce first and then disable it and delete it you get an additional fatal:
```
[24-Aug-2023 10:15:02 UTC] PHP Warning:  include_once(/shared/httpd/wptest/wordpress/wp-content/plugins/woocommerce/includes/admin/plugin-updates/class-wc-plugin-updates.php): failed to open stream: No such file or directory in /shared/httpd/wptest/wordpress/wp-content/plugins/woocommerce/includes/wc-core-functions.php on line 2300
[24-Aug-2023 10:15:02 UTC] PHP Warning:  include_once(): Failed opening '/shared/httpd/wptest/wordpress/wp-content/plugins/woocommerce/includes/admin/plugin-updates/class-wc-plugin-updates.php' for inclusion (include_path='.:/usr/local/lib/php') in /shared/httpd/wptest/wordpress/wp-content/plugins/woocommerce/includes/wc-core-functions.php on line 2300
[24-Aug-2023 10:15:02 UTC] PHP Fatal error:  Uncaught Error: Class 'WC_Plugin_Updates' not found in /shared/httpd/wptest/wordpress/wp-content/plugins/woocommerce/includes/wc-core-functions.php:2304
Stack trace:
#0 /shared/httpd/wptest/wordpress/wp-includes/class-wp-hook.php(310): wc_enable_wc_plugin_headers(Array)
#1 /shared/httpd/wptest/wordpress/wp-includes/plugin.php(205): WP_Hook->apply_filters(Array, Array)
#2 /shared/httpd/wptest/wordpress/wp-includes/functions.php(6710): apply_filters('extra_plugin_he...', Array)
#3 /shared/httpd/wptest/wordpress/wp-admin/includes/plugin.php(91): get_file_data('/shared/httpd/w...', Array, 'plugin')
#4 /shared/httpd/wptest/wordpress/wp-admin/includes/plugin.php(339): get_plugin_data('/shared/httpd/w...', false, false)
#5 /shared/httpd/wptest/wordpress/wp-content/plugins/woocommerce/includes/admin/helper/class-wc-helper.php(1162): get_plugins()
#6 /shared/httpd/wptest/wordpress/wp-content/plugins/woocommerce/includes/admin/helper/class-wc-helper-updater.php(179): WC_Helper::get_local_woo_plugins()
#7 /shared/httpd/ in /shared/httpd/wptest/wordpress/wp-content/plugins/woocommerce/includes/wc-core-functions.php on line 2304
[24-Aug-2023 10:15:02 UTC] PHP Fatal error:  Uncaught Error: Class 'ActionScheduler_Lock' not found in /shared/httpd/wptest/wordpress/wp-content/plugins/woocommerce/packages/action-scheduler/classes/abstracts/ActionScheduler.php:29
Stack trace:
#0 /shared/httpd/wptest/wordpress/wp-content/plugins/woocommerce/packages/action-scheduler/classes/ActionScheduler_QueueRunner.php(106): ActionScheduler::lock()
#1 /shared/httpd/wptest/wordpress/wp-includes/class-wp-hook.php(310): ActionScheduler_QueueRunner->maybe_dispatch_async_request('')
#2 /shared/httpd/wptest/wordpress/wp-includes/class-wp-hook.php(334): WP_Hook->apply_filters(NULL, Array)
#3 /shared/httpd/wptest/wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#4 /shared/httpd/wptest/wordpress/wp-includes/load.php(1252): do_action('shutdown')
#5 [internal function]: shutdown_action_hook()
#6 {main}
  thrown in /shared/httpd/wptest/wordpress/wp-content/plugins/woocommerce/packages/action-scheduler/classes/abstracts/ActionScheduler.php on line 29
[24-Aug-2023 10:15:58 UTC] Cron reschedule event error for hook: action_scheduler_run_queue, Error code: invalid_schedule, Error message: Event schedule does not exist., Data: {"schedule":"every_minute","args":["WP Cron"],"interval":60}
```

### Steps to reproduce

- Install WooCommerce
- (log your PHP error)
- add `define( 'WC_REMOVE_ALL_DATA', true );` to your wp-config.php
- Delete WooCommerce plugin: from wp-admin Plugins, Delete button link.

### WordPress Environment

```
### WordPress Environment ###

WordPress address (URL): http://wptest.dvl.to
Site address (URL): http://wptest.dvl.to
WC Version: 8.0.2
REST API Version: ✔ 8.0.2
WC Blocks Version: ✔ 10.6.5
Action Scheduler Version: ✔ 3.6.1
Log Directory Writable: ✔
WP Version: 6.3
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.22.1
PHP Version: 7.4.33
PHP Post Max Size: 72 MB
PHP Time Limit: 120
PHP Max Input Vars: 8000
cURL Version: 7.74.0
OpenSSL/1.1.1n

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.6.12-MariaDB-1:10.6.12+maria~ubu2004-log
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.0.2
WC Database Prefix: wp_
Total Database Size: 5.23MB
Database Data Size: 3.53MB
Database Index Size: 1.70MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 2.47MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_posts: Data: 0.05MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.03MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 2
page: 8
post: 2
product: 1
revision: 4
wp_navigation: 1
wp_template: 2

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 8.0.2

### Inactive Plugins (7) ###

Akismet Anti-Spam: Spam Protection: by Automattic - Anti Spam Team – 5.2
Elementor: by Elementor.com – 3.15.3
Hello Dolly: by Matt Mullenweg – 1.7.2
LifterLMS: by LifterLMS – 7.3.0
LifterLMS Assignments: by LifterLMS – 2.1.0
User Switching: by John Blackbourn & contributors – 1.7.0
Yoast SEO: by Team Yoast – 21.0

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### WC Pages ###

Shop base: #19 - /shop/
Cart: #8 - /cart/
Checkout: #9 - /checkout/
My account: #10 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty-Three
Version: 1.2
Author URL: https://wordpress.org
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
product-variation-management
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2023-08-25 10:17:57 +00:00
Options: ✔
Notes: 61
Onboarding: completed

### Action Scheduler ###

Complete: 5
Oldest: 2023-08-24 10:14:54 +0000
Newest: 2023-08-24 10:19:11 +0000

Failed: 1
Oldest: 2023-08-24 10:19:05 +0000
Newest: 2023-08-24 10:19:05 +0000

Pending: 1
Oldest: 2023-08-25 10:14:54 +0000
Newest: 2023-08-25 10:14:54 +0000


### Status report information ###

Generated at: 2023-08-24 10:21:35 +00:00
```

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by jorgeatorres**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

This PR makes sure that fully uninstalling WooCommerce doesn't trigger any fatal errors.

The reason for these fatals is that in #34469 we changed the uninstall routine from requiring only `WC_Install` to requiring the full WooCommerce plugin. This allowed us to gain access to the container and some constants (which was used to remove HPOS tables) but at the same time resulted in all callbacks being connected to hooks that might run as part or after the uninstall process. This is problematic because some code is hooked to `shutdown` or later hooks and might attempt to run after the files had been removed by the uninstall process producing autoloader errors.

Ideally, a fully initialized WC shouldn't fatal when uninstalled but ensuring functionality and hooks are all "uninstall aware" is much more difficult and error prone than keeping the uninstall process as simple as possible, which is what this PR does.

Closes #39881.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Build a ZIP from this branch for easier testing.
   ```
   cd plugins/woocommerce
   pnpm build:zip
   ```

   This will give you a `woocommerce.zip` inside `plugins/woocommerce` which you can upload to a test site.
1. Edit the `wp-config.php` file on your test site to include the following line:
   ```php
   define( 'WC_REMOVE_ALL_DATA', true );
   ```
1. Upload `woocommerce.zip` from step 1 to your test site and activate it.
1. Go to **Plugins**:
   1. Click **Deactivate** for the **WooCommerce** plugin.
   2. Click **Delete** for the **WooCommerce** plugin.
   3. The process should end successfully with message
      > WooCommerce was successfully deleted. 
   4. No fatal errors should be logged in your log files.
   5. Ensure WC tables have been removed from your site:
      ```
      wp db tables '*wc_*' --all-tables
      ```
1. Install and activate the latest version of WooCommerce on your test site by searching for WooCommerce in **Plugins > Add Plugin**.
1. Go to **Plugins** and click **Deactivate** followed by **Delete**.
1. The process will likely fail with message "Deletion failed: There has been a critical error on this website.Learn more about troubleshooting WordPress." and you'll find some errors in your logs:
   ```
   PHP Fatal error:  Uncaught Error: Class "WC_Plugin_Updates" not found in [...]/plugins/woocommerce/includes/wc-core-functions.php:2401
   PHP Fatal error:  Uncaught Error: Class "ActionScheduler_Lock" not found in [...]/plugins/woocommerce/packages/action-scheduler/classes/abstracts/ActionScheduler.php:55
   ```

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce/includes/class-wc-install.php [hunk 1]
```diff
@@ -2028,6 +2032,12 @@ public static function get_tables() {
 			"{$wpdb->prefix}wc_admin_note_actions",
 			"{$wpdb->prefix}wc_customer_lookup",
 			"{$wpdb->prefix}wc_category_lookup",
+
+			// HPOS.
```
Comment (joshuatf) [inline plugins/woocommerce/includes/class-wc-install.php:2036]: I was a little concerned that `get_tables()` might be used to also help generate tables initially, but does not seem to be the case and at least the comment on this function seems to suggest it's only for uninstall so I think this is safe.

File: plugins/woocommerce/includes/class-wc-install.php [hunk 2]
```diff
@@ -317,6 +317,10 @@ class WC_Install {
 	 * Hook in tabs.
 	 */
 	public static function init() {
+		if ( defined( 'WC_UNINSTALLING_PLUGIN' ) ) {
```
Comment (joshuatf) [inline plugins/woocommerce/includes/class-wc-install.php]: Is it possible to just rely on `WP_UNINSTALL_PLUGIN` instead of creating a new constant?  Or are there some edge cases in uninstalls where WC might need to be loaded?

I can't imagine another plugin could rely on WC being loaded during an uninstall but 🤷‍♂️

Comment (jorgeatorres) [reply plugins/woocommerce/includes/class-wc-install.php]: My thinking was that `WP_UNINSTALL_PLUGIN` would be set while you uninstall _other_ plugin (not WC) and we wouldn't necessarily want to prevent `WC_Install` from being correctly initialized in that case.

It could indeed be an edge case, but decided to err on the side of caution.

File: plugins/woocommerce/includes/class-wc-install.php (hunk 1 above)
Comment (jorgeatorres) [reply plugins/woocommerce/includes/class-wc-install.php:2036]: It's also used when a WPMU site is removed and the tables need to be dropped. That's why I also think this table should list all possible tables.

**Comment by jorgeatorres** [comment]
@joshuatf: Thanks for taking a look. You were quicker to review than I was to finish the PR, so there were a few things that were missing. I've pushed some commits with some changes:

- Instead of using a constant, I'm now relying on a global that gets set and unset during `uninstall.php`. This might be slightly better in cases (such as inside unit tests) where we might want to include `uninstall.php` more than once or run `WC_Install` afterwards and we don't want the constant to make that impossible.
- There was also a unit test that was failing, which was in theory used to make sure that `WC_Install::get_tables()` included all WC tables (so that nothing would be missed while removing) but in reality it did the opposite: it expected the database to contain all tables listed in `get_tables()`. I don't think this is correct because there might be some tables that are created conditionally (in `get_schema()`). I updated the test so it now uses `get_schema()` which I think is slightly better (despite the regex) because now what we're checking is that we don't create any tables that we then not remove.

Please let me know what you think and, once again, thanks for the review!

File: plugins/woocommerce/tests/legacy/unit-tests/util/install.php [hunk 3]
```diff
@@ -131,19 +131,24 @@ public function test_remove_roles() {
 	 * @group core-only
 	 */
 	public function test_get_tables() {
-		global $wpdb;
+		// Make WC_Install::get_schema() accessible.
+		$wc_install = new \ReflectionClass( WC_Install::class );
+		$get_schema = $wc_install->getMethod( 'get_schema' );
+		$get_schema->setAccessible( true );
+		$schema = $get_schema->invoke( null );
+		preg_match_all( '/CREATE TABLE (.*?)\s*\(/i', $schema, $matches, PREG_PATTERN_ORDER );
```
Comment (joshuatf) [inline plugins/woocommerce/tests/legacy/unit-tests/util/install.php:139]: One of the things that the old test might do a better job of catching is if someone creates a table outside of the `WC_Install` class.

While that hopefully should not happen, I like that we match against any table with `woocommerce_` or `wc_` in case a feature class decides to manually implement their own tables.

File: plugins/woocommerce/uninstall.php [hunk 4]
```diff
@@ -73,11 +71,6 @@
 	$wpdb->query( "DELETE FROM {$wpdb->comments} WHERE comment_type IN ( 'order_note' );" );
 	$wpdb->query( "DELETE meta FROM {$wpdb->commentmeta} meta LEFT JOIN {$wpdb->comments} comments ON comments.comment_ID = meta.comment_id WHERE comments.comment_ID IS NULL;" );
 
-	foreach ( wc_get_container()->get( OrdersTableDataStore::class )->get_all_table_names() as $cot_table ) {
```
Comment (joshuatf) [inline plugins/woocommerce/uninstall.php:76]: 🎉

File: plugins/woocommerce/includes/class-wc-install.php [hunk 5]
```diff
@@ -317,6 +317,10 @@ class WC_Install {
 	 * Hook in tabs.
 	 */
 	public static function init() {
+		if ( ! empty( $GLOBALS['wc_uninstalling_plugin'] ) ) {
```
Comment (joshuatf) [inline plugins/woocommerce/includes/class-wc-install.php:320]: I think it's not overly likely that another plugin will be using the installer class when they're uninstalling, but if we want to be extra cautious without introducing a new global, we can still use `WP_UNINSTALL_PLUGIN`.

`WP_UNINSTALL_PLUGIN` is [defined with the plugin uninstall file](https://github.com/WordPress/wordpress-develop/blob/1e04fc0864544f5a224dbe4718979367ab2a208c/src/wp-admin/includes/plugin.php#L1311) and we could check to make sure it matches the current plugin directory.

**Review by joshuatf — COMMENTED** [review]
Logic makes sense!  Just left a couple comments around tests and one optional reversion to `WP_UNINSTALL_PLUGIN` to help keep globals down.

File: plugins/woocommerce/tests/legacy/unit-tests/util/install.php (hunk 3 above)
Comment (jorgeatorres) [reply plugins/woocommerce/tests/legacy/unit-tests/util/install.php:139]: Just adding that I'm leaving this as-is per our discussion.

File: plugins/woocommerce/includes/class-wc-install.php (hunk 5 above)
Comment (jorgeatorres) [reply plugins/woocommerce/includes/class-wc-install.php:320]: Just adding that I'm leaving this as-is per our discussion.

File: plugins/woocommerce/tests/legacy/unit-tests/util/install.php (hunk 3 above)
Comment (joshuatf) [reply plugins/woocommerce/tests/legacy/unit-tests/util/install.php:139]: To add some context to this: the old way just tables that were created and doesn't catch things removed.  When it comes to catching created tables, it was slightly flawed given it checked the entire DB.

So previously this actually wouldn't catch classes adding tables outside of this class and may actually provide false positives.

The new way is more contained and checks in isolation that the installer class is doing what it's supposed to 👍

File: plugins/woocommerce/includes/class-wc-install.php (hunk 5 above)
Comment (joshuatf) [reply plugins/woocommerce/includes/class-wc-install.php:320]: Leaving this as the new global due to an 11 year outstanding bug in WP - https://core.trac.wordpress.org/ticket/26735

🤦

**Review by joshuatf — APPROVED** [review]
Testing great!  Thanks for taking the time to discuss this even though my suggestions did not pan out.

✅ Deletion of the current WPORG plugin results in error
✅ Deletion is successful without errors in the UI or logs
✅ All tables are successfully removed

Screenshot 2025-06-05 at 7 53 21 AM
(current WPORG plugin results)
Screenshot 2025-06-05 at 7 52 03 AM
Screenshot 2025-06-05 at 7 51 37 AM
