### PR TITLE
Storefront in wizard for non WC themes and default themes

### LINKED ISSUE #18182: Show Storefront notice in Wizard if using a default WordPress theme.
## Steps to reproduce the issue

1. Wipe a site clean.
2. Go through wizard wanting to get recommended Storefront.
3. Won't get the notice, even if using a default WordPress theme.

## Expected/actual behavior

When I follow those steps, I'd expect to get Storefront recommended. I understand that notice won't show if using a WooCommerce compatible theme, and even though the default themes are, that seems like a good time to recommend Storefront. :)

### PR DESCRIPTION
**Pull request by kloon**
The wizard will recommend storefront as a theme to install when a theme with no woocommerce support is active, however since we add woocommerce support for default themes the notice is not displaying.

This PR addresses the issue by showing the theme when a theme with no woocommerce support is active, or when using one of the default themes.

Closes #18182

### CODE REVIEW

File: includes/class-woocommerce.php [hunk 1]
```diff
@@ -254,7 +254,7 @@ private function is_request( $type ) {
 	 * @param  string $theme Theme slug to check.
 	 * @return bool
 	 */
-	private function is_active_theme( $theme ) {
```
Comment (mikejolley) [inline includes/class-woocommerce.php]: Since this is private now, my pref would be to move it out of the main class as a new core function and call that instead. Thoughts on that vs public method?

File: includes/admin/class-wc-admin-setup-wizard.php [hunk 2]
```diff
@@ -75,8 +75,10 @@ protected function should_show_theme_extra() {
 		return (
 			current_user_can( 'install_themes' ) &&
 			current_user_can( 'switch_themes' ) &&
-			! is_multisite() &&
-			! current_theme_supports( 'woocommerce' )
+			! is_multisite() && (
+				! current_theme_supports( 'woocommerce' ) ||
```
Comment (mikejolley) [inline includes/admin/class-wc-admin-setup-wizard.php]: This conditional is pretty hard to read now - let's move the theme support + theme checking part into a variable before being used here.

**Review by mikejolley — CHANGES_REQUESTED** [review]
