### PR TITLE
Fix `taxonomy-product_brand` template inheritance from `archive-product`

### LINKED ISSUE #58003: Taxonomy brand template is not tied to archive-product template in the same way attribute, cat and tag are
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

The following pseudo templates take their content (block/layout/styling) from the `archive-product.html` template if they do not exist either as theme files or saved templates in the database:
`taxonomy-product_attribute` - Products by Attribute
`taxonomy-product_cat` - Products by Category
`taxonomy-product_brand` - Products by Tag

However, this template does not, and is styled independently, and does not inherit the archive-product template:
`taxonomy-product_brand` - Taxonomy Product Brand

### Expected behavior

The taxonomy brand template should also inherit the product archive if it does not exist as a file or saved template.

### Actual behavior

 The taxonomy brand template deos not inherit the template of the product archive.

### Steps to reproduce

Use the [woostarter theme](https://github.com/woocommerce/woo-themes/tree/trunk/woostarter) which has an `archive-product.html` template, and no other taxonomy specific templates.
Go to Editor > Templates and make some changes to the Product Catalog template.
Notice that the Attribute, Category and Tag templates inherit the changes made to the Product Catalog template.
Notice that the Brand template does not inherit the changes made to the Product Catalog template.

Image

### WordPress Environment

WP 6.8.1
WooCommerce 9.8.5
woostarter theme, but any block theme with an `archive-product` template will reproduce

### Isolating the problem

- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by sunyatasattva**
### Changes proposed in this Pull Request:

The `taxonomy-product_brand` template was not inheriting from `archive-product` like other taxonomy templates (category, tag, attribute). When users modified the "Product Catalog" template, changes would appear in category/tag templates but not in brand templates.

This was because `WC_Brands_Block_Templates` class was intercepting template loading and bypassing the normal fallback mechanism.

Closes #58003.

(For Bug Fixes) Bug introduced in PR #50165.

### Screenshots or screen recordings:

164545be-107e-4e8d-a81e-b7e2edcc0d30

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

#### Fallback to Product Archive

1. Go to the Site Editor.
2. Make sure the “Products by Brand” template is unmodified.
3. Modify the “Products Catalog” template.
4. Load the “Products by Brand” template in both the Site Editor, and the front-end (`/brand/your-brand`).
5. Confirm that your edits are present.

#### Preserves its own edits

1. Edit the “Products by Brand” template in a unique way.
2. Go to the front-end and make sure that the new template is respected.

### Testing that has already taken place:

All of the above.

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

Fixed the “Product Brands” template not falling back correctly to the “Product Catalog”

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

**Comment by sunyatasattva** [comment]
(Sorry @Aljullu, I manually requested your review because you are the one who refactored the `BlockTemplatesController` and I wanted to make sure I'm registering the template following the best pattern, so that when we move to the GB implementation this can go seamlessly).

File: plugins/woocommerce/includes/blocks/class-wc-brands-block-templates.php [hunk 1]
```diff
@@ -1,156 +0,0 @@
...
-	 *
-	 * @param string $template_type The post_type for the template. Normally wp_template or wp_template_part.
-	 *
-	 * @return WP_Block_Template The taxonomy-product_brand template.
-	 */
-	private function get_product_brands_template( $template_type ) {
-		$template_db = $this->get_product_brand_template_db();
-
-		if ( $template_db ) {
-			return BlockTemplateUtilsDuplicated::gutenberg_build_template_result_from_post( $template_db );
```
Comment (Aljullu) [inline plugins/woocommerce/includes/blocks/class-wc-brands-block-templates.php:78]: I think now the `BlockTemplateUtilsDuplicated` class can be removed? I believe it wasn't used anywhere else.

**Review by Aljullu — COMMENTED** [review]
Nice to see that we can move this to use the same logic we use for the other taxonomy templates! :clap: 

I found a couple of issues:

1. The template wasn't showing for me in the Site Editor. I had to add it manually in this array of slugs (side note: in a future PR, this could be refactored to use the `BlockTemplatesRegistry` so we don't need to keep the slugs in two places):

https://github.com/woocommerce/woocommerce/blob/3f9651a3845c74f21fdb5b71ec992af0a512cc32/plugins/woocommerce/src/Blocks/Utils/BlockTemplateUtils.php#L301-L311

2. I see a warning in the frontend when loading any page, I guess coming from [here](https://github.com/woocommerce/woocommerce/blob/3f9651a3845c74f21fdb5b71ec992af0a512cc32/plugins/woocommerce/src/Internal/Brands.php#L34):

> Warning: include_once(): Failed opening '/woocommerce/plugins/woocommerce/includes/blocks/class-wc-brands-block-templates.php' for inclusion (include_path='.:/usr/share/php:/www/wp-content/pear') in /woocommerce/plugins/woocommerce/src/Internal/Brands.php on line 34

**Comment by sunyatasattva** [comment]
> Nice to see that we can move this to use the same logic we use for the other taxonomy templates! 👏
> 
> I found a couple of issues:
> 
> 1. The template wasn't showing for me in the Site Editor. I had to add it manually in this array of slugs (side note: in a future PR, this could be refactored to use the `BlockTemplatesRegistry` so we don't need to keep the slugs in two places):

That's strange! I wonder why it was showing for me? Any ideas?

> I see a warning in the frontend when loading any page, I guess coming from [here](https://github.com/woocommerce/woocommerce/blob/3f9651a3845c74f21fdb5b71ec992af0a512cc32/plugins/woocommerce/src/Internal/Brands.php#L34):

Heh, I had left the file in my repo, but it was empty, so it didn't trigger the error. My bad!

**Review by Aljullu — APPROVED** [review]
imatge

:heart_eyes: 

Tested that:

1. ✅ Products by Brand templates falls back to the Product Catalog template when it's the default and when customized.
2. ✅ Products by Brand can be overridden by the user.
3. ✅ Products by Brand can be overridden by the theme (but the user template has priority).

imatge

<details>
<summary>Testing environment</summary>

* WordPress 6.8.1 local dev environment
* Plugins: WooCommerce Beta Tester
* Theme: Woo Starter Theme
* Store creation: June 2025
* Store size: small
</details>

> That's strange! I wonder why it was showing for me? Any ideas?

Not sure. Did you have it saved in the database or in the theme? Otherwise, I'm not sure why it would show up for you and nnot for me. :confused:

**Comment by sunyatasattva** [comment]
> Not sure. Did you have it saved in the database or in the theme? Otherwise, I'm not sure why it would show up for you and nnot for me. 😕

If it was saved in the DB I wouldn't be able to test the fallback, no? 🤔 

Though to be honest I had some strange behaviors with the “reset” customization button.
