### PR TITLE
Cart/Checkout Block: Allow HTML on shipping rates

### LINKED ISSUE #54385: Cart and Checkout Block does not render HTML in product names on shipping rates
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Currently we support HTML on products names, it's rendered correctly on the cart and checkout blocks items listing.

Some plugins, like WooCommerce Subscriptions, adds the product name on the shipping rates to specify what's related to each shipping rate, and the HTML on the product names are not loaded as expected.

This happens because the `Label` component [here](https://github.com/woocommerce/woocommerce/blob/3dd035917b982093ac15f3472d7bc7df0e56b94a/plugins/woocommerce-blocks/packages/components/label/index.tsx#L48) does not load HTML.

Image

Image

### Expected behavior

Load the HTML in product names on the shipping rates. 

### Actual behavior

The HTML source code is showed in the product name.

### Steps to reproduce

1. Install WooCommerce Subscriptions.
2. Create a subscription with HTML in the name.
3. Add this subscription to the cart.
4. Add a normal product to the cart.
5. Access the cart or checkout page.
6. The HTML in the product name for the shipping rate is not loaded.

### WordPress Environment

This is happening on `trunk`.

### Isolating the problem

- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by alefesouza**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

This PR allows HTML to be rendered on the shipping rates section of cart and checkout block to handle products with HTML in the name.

| Before | After |
|-|-|
| Screenshot 2025-01-10 at 5 14 04 PM | Screenshot 2025-01-10 at 5 11 58 PM |
| Screenshot 2025-01-10 at 6 01 38 PM | Screenshot 2025-01-10 at 5 38 18 PM |

Closes #54385 .

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Install WooCommerce Subscriptions.
2. Create a subscription with HTML in the name.
3. Add this subscription to the cart.
4. Add a normal product to the cart.
5. Access the blocks cart and checkout page.
6. The HTML in the product name for the shipping rate is not loaded.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [x] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

This PR does not need a changelog because it's a simple change that does not affect so many users.

</details>

### CODE REVIEW

File: plugins/woocommerce-blocks/packages/components/label/index.tsx [hunk 1]
```diff
@@ -45,7 +47,17 @@ const Label = ( {
 	if ( hasLabel && hasScreenReaderLabel && label !== screenReaderLabel ) {
 		return (
 			<Wrapper { ...wrapperProps }>
-				<span aria-hidden="true">{ label }</span>
+				{ allowHTML ? (
+					<span
+						aria-hidden="true"
+						dangerouslySetInnerHTML={ {
```
Comment (mikejolley) [inline plugins/woocommerce-blocks/packages/components/label/index.tsx]: There is a `RawHTML` component which may be more appropriate here.

File: plugins/woocommerce-blocks/packages/components/label/index.tsx [hunk 2]
```diff
@@ -20,6 +21,7 @@ export interface LabelProps extends HTMLProps< HTMLElement > {
  */
 const Label = ( {
 	label,
+	allowHTML,
```
Comment (mikejolley) [inline plugins/woocommerce-blocks/packages/components/label/index.tsx]: Should we default to `false` here?

File: plugins/woocommerce-blocks/packages/components/label/index.tsx [hunk 3]
```diff
@@ -45,7 +47,17 @@ const Label = ( {
 	if ( hasLabel && hasScreenReaderLabel && label !== screenReaderLabel ) {
 		return (
 			<Wrapper { ...wrapperProps }>
-				<span aria-hidden="true">{ label }</span>
+				{ allowHTML ? (
+					<span
+						aria-hidden="true"
+						dangerouslySetInnerHTML={ {
+							__html: label,
```
Comment (mikejolley) [inline plugins/woocommerce-blocks/packages/components/label/index.tsx]: How about doing some form of sanitization using `sanitizeHTML`? This uses DomPurify library.

**Review by mikejolley — CHANGES_REQUESTED** [review]
Hi @alefesouza 

I think allowing HTML is fine but I think we need some protections and limitations in place. See my comments.

Thanks

**Comment by alefesouza** [comment]
@mikejolley thanks! Updated on https://github.com/woocommerce/woocommerce/pull/54386/commits/cba713897a0bde5ac7be7964bf20f80cba4b6d3a, I was using the same approach used by the cart product item name [here](https://github.com/woocommerce/woocommerce/pull/54386/commits/cba713897a0bde5ac7be7964bf20f80cba4b6d3a), maybe it would be good to use your suggestions there too.

File: plugins/woocommerce-blocks/packages/components/label/index.tsx [hunk 4]
```diff
@@ -45,7 +48,25 @@ const Label = ( {
 	if ( hasLabel && hasScreenReaderLabel && label !== screenReaderLabel ) {
 		return (
 			<Wrapper { ...wrapperProps }>
-				<span aria-hidden="true">{ label }</span>
+				{ allowHTML ? (
+					<RawHTML>
+						{ sanitizeHTML( label, {
+							tags: [
```
Comment (mikejolley) [inline plugins/woocommerce-blocks/packages/components/label/index.tsx:54]: Not blocking, but I am fairly sure if you leave this out, it uses our defaults.

```
const ALLOWED_TAGS = [ 'a', 'b', 'em', 'i', 'strong', 'p', 'br' ];
const ALLOWED_ATTR = [ 'target', 'href', 'rel', 'name', 'download' ];
```

I see no reason why those defaults couldn't be expanded to include span and style.

**Review by mikejolley — APPROVED** [review]
Thanks for making those changes. I made one comment but its not blocking. Approving.

File: plugins/woocommerce-blocks/packages/components/label/index.tsx (hunk 4 above)
Comment (alefesouza) [reply plugins/woocommerce-blocks/packages/components/label/index.tsx:54]: I think maybe we didn't want to include the `style` in the past so this can break existing systems where we are not expecting customized styles.
