### PR TITLE
FIX strtotime(): Passing null to parameter #1 () of type string is deprecated PHP 8

### LINKED ISSUE #40532: Deprecated strtotime( $datetime = NULL )
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

page: /wp-admin/post-new.php?post_type=shop_order

Got error message:

```
Deprecated: strtotime(): Passing null to parameter #1 ($datetime) of type string is deprecated in C:\xampp\htdocs\wordplate\public\plugins\woocommerce\includes\admin\class-wc-admin-post-types.php on line 203
```

### Expected behavior

Should not have a deprecation

### Actual behavior

Have a deprecation

### Steps to reproduce

Install Woocommerce with php > 8.0

go to page: /wp-admin/post-new.php?post_type=shop_order

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): http://sageapi.local/wordpress
Site address (URL): http://sageapi.local
WC Version: 8.1.1
REST API Version: ✔ 8.1.1
WC Blocks Version: ✔ 10.9.3
Action Scheduler Version: ✔ 3.6.2
Log Directory Writable: ✔
WP Version: 6.3.1
WP Multisite: –
WP Memory Limit: 512 Mo
WP Debug Mode: ✔
WP Cron: ✔
Language: fr_FR
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.56 (Win64) OpenSSL/1.1.1t PHP/8.2.4
PHP Version: 8.2.4
PHP Post Max Size: 40 Mo
PHP Time Limit: 120
PHP Max Input Vars: 1000
cURL Version: 7.85.0
OpenSSL/3.0.8

SUHOSIN Installed: –
MySQL Version: 10.4.28-MariaDB
Max Upload Size: 40 Mo
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Votre serveur n’a pas la classe SoapClient activée - certaines extensions de passerelle utilisant SOAP peuvent ne pas fonctionner correctement.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.1.1
WC Database Prefix: wp_
Taille totale de la base de données: 4.89MB
Taille de la base de données: 3.19MB
Taille de l’index: 1.70MB
wp_woocommerce_sessions: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_woocommerce_api_keys: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_woocommerce_attribute_taxonomies: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_woocommerce_downloadable_product_permissions: Données : 0.02MB + Index : 0.06MB + Moteur InnoDB
wp_woocommerce_order_items: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_woocommerce_order_itemmeta: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_woocommerce_tax_rates: Données : 0.02MB + Index : 0.06MB + Moteur InnoDB
wp_woocommerce_tax_rate_locations: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_woocommerce_shipping_zones: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_woocommerce_shipping_zone_locations: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_woocommerce_shipping_zone_methods: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_woocommerce_payment_tokens: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_woocommerce_payment_tokenmeta: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_woocommerce_log: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_actionscheduler_actions: Données : 0.02MB + Index : 0.11MB + Moteur InnoDB
wp_actionscheduler_claims: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_actionscheduler_groups: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_actionscheduler_logs: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_commentmeta: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_comments: Données : 0.02MB + Index : 0.09MB + Moteur InnoDB
wp_links: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_options: Données : 2.11MB + Index : 0.06MB + Moteur InnoDB
wp_postmeta: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_posts: Données : 0.05MB + Index : 0.06MB + Moteur InnoDB
wp_termmeta: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_terms: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_term_relationships: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_term_taxonomy: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_usermeta: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_users: Données : 0.02MB + Index : 0.05MB + Moteur InnoDB
wp_wc_admin_notes: Données : 0.06MB + Index : 0.00MB + Moteur InnoDB
wp_wc_admin_note_actions: Données : 0.05MB + Index : 0.02MB + Moteur InnoDB
wp_wc_category_lookup: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_wc_customer_lookup: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_wc_download_log: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_wc_orders: Données : 0.02MB + Index : 0.11MB + Moteur InnoDB
wp_wc_orders_meta: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_wc_order_addresses: Données : 0.02MB + Index : 0.06MB + Moteur InnoDB
wp_wc_order_coupon_lookup: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_wc_order_operational_data: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_wc_order_product_lookup: Données : 0.02MB + Index : 0.06MB + Moteur InnoDB
wp_wc_order_stats: Données : 0.02MB + Index : 0.05MB + Moteur InnoDB
wp_wc_order_tax_lookup: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_wc_product_attributes_lookup: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_wc_product_download_directories: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_wc_product_meta_lookup: Données : 0.02MB + Index : 0.09MB + Moteur InnoDB
wp_wc_rate_limits: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_wc_reserved_stock: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_wc_tax_rate_classes: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_wc_webhooks: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB

### Post Type Counts ###

attachment: 1
nav_menu_item: 6
page: 7
post: 2
post_type: 2
shop_order: 3

### Security ###

Secure connection (HTTPS): ❌
					Votre boutique n’utilise pas HTTPS. En savoir plus sur HTTPS et les certificats SSL.
Hide errors from visitors: ❌Les messages d’erreur ne doivent pas s’afficher aux visiteurs.

### Active Plugins (3) ###

GP Premium: par Tom Usborne – 2.3.2
Sage: par Alexandre Beaujour – 1.0.0
WooCommerce: par Automattic – 8.1.1

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### WC Pages ###

Base de la boutique: #16 - /boutique/
Panier: #17 - /panier/
Commander: #18 - /commander/
Mon compte: #19 - /mon-compte/
Conditions générales de vente et d’utilisation: ❌ Page non définie

### Theme ###

Name: GeneratePress
Version: 3.3.1
Author URL: https://tomusborne.com
Child Theme: ❌ – Si vous modifiez WooCommerce sur un thème parent que vous n’avez pas construit personnellement
nous vous recommandons d’utiliser un thème enfant. Voir : Comment créer un thème enfant

WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: customize-store
minified-js
new-product-management-experience
product-variation-management
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2023-10-02 22:41:57 +00:00
Options: ✔
Notes: 59
Onboarding: -

### Action Scheduler ###

Terminé: 2
Oldest: 2023-10-01 22:44:13 +0000
Newest: 2023-10-01 22:44:18 +0000

En attente: 1
Oldest: 2023-10-02 22:44:13 +0000
Newest: 2023-10-02 22:44:13 +0000

### Status report information ###

Generated at: 2023-10-02 00:57:56 +00:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by Lenny4**
Fix: https://github.com/woocommerce/woocommerce/issues/40532

## Testing instructions

1. Make sure HPOS is disabled in WC > Settings > Advanced > Features. That is, "WordPress posts storage (legacy)" should be selected as datastore.
2. Make sure you're on PHP > 8.x.
3. Go to page: /wp-admin/post-new.php?post_type=shop_order.
4. With this PR you should **not** have the deprecation message:
   ```
   Deprecated: strtotime(): Passing null to parameter #1 ($datetime) of type string is deprecated in C:\xampp\htdocs\wordplate\public\plugins\woocommerce\includes\admin\class-wc-admin-post-types.php on line 203
   ```

### CODE REVIEW

File: plugins/woocommerce/includes/admin/class-wc-admin-post-types.php [hunk 1]
```diff
@@ -139,7 +139,7 @@ public function post_updated_messages( $messages ) {
 			9  => sprintf(
 				/* translators: 1: date 2: product url */
 				__( 'Product scheduled for: %1$s. <a target="_blank" href="%2$s">Preview product</a>', 'woocommerce' ),
-				'<strong>' . date_i18n( __( 'M j, Y @ G:i', 'woocommerce' ), strtotime( $post->post_date ) ) . '</strong>',
+				'<strong>' . date_i18n( __( 'M j, Y @ G:i', 'woocommerce' ), ($post->post_date ? strtotime( $post->post_date ) : false) ) . '</strong>',
```
Comment (jorgeatorres) [inline plugins/woocommerce/includes/admin/class-wc-admin-post-types.php]: This change isn't necessary. In this context, `$post` is guaranteed to be a valid object (including post date).

File: plugins/woocommerce/includes/admin/class-wc-admin-post-types.php [hunk 2]
```diff
@@ -161,7 +161,7 @@ public function post_updated_messages( $messages ) {
 			9  => sprintf(
 				/* translators: %s: date */
 				__( 'Coupon scheduled for: %s.', 'woocommerce' ),
-				'<strong>' . date_i18n( __( 'M j, Y @ G:i', 'woocommerce' ), strtotime( $post->post_date ) ) . '</strong>'
+				'<strong>' . date_i18n( __( 'M j, Y @ G:i', 'woocommerce' ), ($post->post_date ? strtotime( $post->post_date ) : false) ) . '</strong>'
```
Comment (jorgeatorres) [inline plugins/woocommerce/includes/admin/class-wc-admin-post-types.php]: Same as above.

File: plugins/woocommerce/includes/admin/class-wc-admin-post-types.php [hunk 3]
```diff
@@ -200,7 +201,7 @@ public function order_updated_messages( array $messages ) {
 			9  => sprintf(
 			/* translators: %s: date */
 				__( 'Order scheduled for: %s.', 'woocommerce' ),
-				'<strong>' . date_i18n( __( 'M j, Y @ G:i', 'woocommerce' ), strtotime( $theorder->get_date_created() ) ) . '</strong>'
+				'<strong>' . date_i18n( __( 'M j, Y @ G:i', 'woocommerce' ), ($theorderDateCreated ? strtotime( $theorderDateCreated ) : false) ) . '</strong>'
```
Comment (jorgeatorres) [inline plugins/woocommerce/includes/admin/class-wc-admin-post-types.php]: At its core, the issue here is that `$theorder->get_date_created()` returns `NULL` in this context (as the order hasn't been saved yet). I believe we could do this differently and more succinctly (and skip the assignment above):

```suggestion
				'<strong>' . date_i18n( __( 'M j, Y @ G:i', 'woocommerce' ), ( $theorder->get_date_created() ?? $post->post_date ) . '</strong>'
```

**Review by jorgeatorres — CHANGES_REQUESTED** [review]
Hi @Lenny4!

Thanks for taking the time to contribute 💯. I've taken a look at your PR and it does fix the problem, but I left some comments on some unnecessary changes that are being included and also a different way to do the fixing that might be a bit less verbose.

Please let me know what you think.

Also, even for a simple change like this, we'll want to include testing instructions on the PR. Could you please add some?
A changelog file is also required, which you can generate locally by running `pnpm --filter=woocommerce changelog add`.

If you're having trouble with any of the above, please let me know. And once again, thank you for contributing!

File: plugins/woocommerce/includes/admin/class-wc-admin-post-types.php (hunk 1 above)
Comment (Lenny4) [reply plugins/woocommerce/includes/admin/class-wc-admin-post-types.php]: indeed, done

File: plugins/woocommerce/includes/admin/class-wc-admin-post-types.php (hunk 2 above)
Comment (Lenny4) [reply plugins/woocommerce/includes/admin/class-wc-admin-post-types.php]: indeed, done

File: plugins/woocommerce/includes/admin/class-wc-admin-post-types.php (hunk 3 above)
Comment (Lenny4) [reply plugins/woocommerce/includes/admin/class-wc-admin-post-types.php]: I changed it to `$theorder->get_id() !== 0 ? strtotime( $theorder->get_date_created() ) : false`, is it ok now ?

**Comment by Lenny4** [comment]
## Testing instructions

go to page: /wp-admin/post-new.php?post_type=shop_order with php > 8 installed

With this PR you sloud not have the deprecation message:
```
Deprecated: strtotime(): Passing null to parameter #1 ($datetime) of type string is deprecated in C:\xampp\htdocs\wordplate\public\plugins\woocommerce\includes\admin\class-wc-admin-post-types.php on line 203
```

**Comment by Lenny4** [comment]
> Also, even for a simple change like this, we'll want to include testing instructions on the PR. Could you please add some? A changelog file is also required, which you can generate locally by running `pnpm --filter=woocommerce changelog add`.


changelog added :+1:

File: plugins/woocommerce/includes/admin/class-wc-admin-post-types.php [hunk 4]
```diff
@@ -137,7 +137,7 @@ public function post_updated_messages( $messages ) {
 			/* translators: %s: product url */
 			8  => sprintf( __( 'Product submitted. <a target="_blank" href="%s">Preview product</a>', 'woocommerce' ), esc_url( add_query_arg( 'preview', 'true', get_permalink( $post->ID ) ) ) ),
 			9  => sprintf(
-				/* translators: 1: date 2: product url */
+			/* translators: 1: date 2: product url */
```
Comment (jorgeatorres) [inline plugins/woocommerce/includes/admin/class-wc-admin-post-types.php]: No sure why this change made was made, but it's not necessary either.

File: plugins/woocommerce/includes/admin/class-wc-admin-post-types.php [hunk 5]
```diff
@@ -159,7 +159,7 @@ public function post_updated_messages( $messages ) {
 			7  => __( 'Coupon saved.', 'woocommerce' ),
 			8  => __( 'Coupon submitted.', 'woocommerce' ),
 			9  => sprintf(
-				/* translators: %s: date */
+			/* translators: %s: date */
```
Comment (jorgeatorres) [inline plugins/woocommerce/includes/admin/class-wc-admin-post-types.php]: Same as above.

File: plugins/woocommerce/includes/admin/class-wc-admin-post-types.php [hunk 6]
```diff
@@ -200,7 +200,7 @@ public function order_updated_messages( array $messages ) {
 			9  => sprintf(
 			/* translators: %s: date */
 				__( 'Order scheduled for: %s.', 'woocommerce' ),
-				'<strong>' . date_i18n( __( 'M j, Y @ G:i', 'woocommerce' ), strtotime( $theorder->get_date_created() ) ) . '</strong>'
+				'<strong>' . date_i18n( __( 'M j, Y @ G:i', 'woocommerce' ), $theorder->get_id() !== 0 ? strtotime( $theorder->get_date_created() ) : false ) . '</strong>'
```
Comment (jorgeatorres) [inline plugins/woocommerce/includes/admin/class-wc-admin-post-types.php]: This doesn't solve the issue (the warning is back). We should check that `$theorder->get_date_created()` is not null, not that `$theorder->get_id() != 0` (which shouldn't be the case ever if everything's correct).

Please take a look at the initial suggestion I gave, which was just a shortcut to this check. Also, passing `false` to `strtotime()`, while it doesn't produce an error, isn't great either. We do have the correct time, either from the order object itself or from `$post`.

**Review by jorgeatorres — CHANGES_REQUESTED** [review]
Hi @Lenny4!

Thanks for adding the instructions and changelog. The latest changes brought back the issue. Please take a look at my review comments.

Let me know what you think.

File: plugins/woocommerce/includes/admin/class-wc-admin-post-types.php (hunk 3 above)
Comment (jorgeatorres) [reply plugins/woocommerce/includes/admin/class-wc-admin-post-types.php]: It's not because `$theorder` should always have an ID. What it doesn't necessarily have is a created date, but in those cases we could use the `$post->post_date` which is what my suggestion did. Alternatively, we could also try to use the current time, but if `$post->post_date` works, I'd vote for that instead.

I also added this bit of feedback to my latest review. Here to help if you have any other questions!

File: plugins/woocommerce/includes/admin/class-wc-admin-post-types.php (hunk 5 above)
Comment (Lenny4) [reply plugins/woocommerce/includes/admin/class-wc-admin-post-types.php]: sorry my IDEA made this change

**Comment by Lenny4** [comment]
@jorgeatorres ,
it took a lot of time just for this simple change. I hope it's fine for you now

**Review by jorgeatorres — APPROVED** [review]
Works great. Tested that the warning does no longer appear when either HPOS or the CPT datastore is in use.
