### PR TITLE
remove em tags from translated string

### LINKED ISSUE #22213: Incorrectly escaped HTML output when Javascript disabled
With Javascript disabled on the Checkout page, I see this:

> Since your browser does not support JavaScript, or it is disabled, please ensure you click the \<em\>Update Totals\</em\> button before placing your order. You may be charged more than the amount stated above if you fail to do so.	

The \<em\> tags are being *escaped* rather than displaying emphasized text.

The offending line is in [templates/checkout/payment.php](https://github.com/woocommerce/woocommerce/blob/master/templates/checkout/payment.php), line 40 (specifically, the call to `esc_html_e()`):

    <?php esc_html_e( 'Since your browser does not support JavaScript, or it is disabled, please ensure you click the <em>Update Totals</em> button before placing your order. You may be charged more than the amount stated above if you fail to do so.', 'woocommerce' ); ?>

### PR DESCRIPTION
**Pull request by rrennick**
### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

Remove `em` tags from escaped translated string.

### Changes proposed in this Pull Request:

Closes #22213 .

### How to test the changes in this Pull Request:

1. Disable javascript
2. Add an item to the cart.
3. Go to checkout.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?

### Changelog entry

> Fix escaped html on checkout when javascript is disabled.

### CODE REVIEW

File: templates/checkout/payment.php [hunk 1]
```diff
@@ -10,7 +10,7 @@
  * happen. When this occurs the version of the template file will be bumped and
  * the readme will list any important changes.
  *
- * @see https://docs.woocommerce.com/document/template-structure/
+ * @see     https://docs.woocommerce.com/document/template-structure/
  * @package WooCommerce/Templates
  * @version 3.4.0
```
Comment (kloon) [inline templates/checkout/payment.php]: Can you please bump this version number to 3.5.3 for inclusion in the next fix release?

**Review by kloon — CHANGES_REQUESTED** [review]
Just the version bump and it is good to merge.

File: templates/checkout/payment.php (hunk 1 above)
Comment (rrennick) [reply templates/checkout/payment.php]: Done.

**Review by claudiulodro — APPROVED** [review]
