### PR TITLE
Only GET requests are cached, so passing the no-store header to POST requests is redundant

### LINKED ISSUE #62449: Add unit tests for Store API cart caching issue
Create regression unit tests for the cart caching behavior related to https://github.com/woocommerce/woocommerce/issues/62396 (mini cart not updating with 10.4.0). 

Tests should cover the `/wp-json/wc/store/v1/cart` endpoint and ensure the correct caching headers are used so that responses are not cached with empty `items`.

There is a work-in-progress branch with initial work: [add-regression-unit-test-for-cache-issue](https://github.com/woocommerce/woocommerce/tree/add-regression-unit-test-for-cache-issue).

### PR DESCRIPTION
**Pull request by samueljseay**
### Changes proposed in this Pull Request:

In #62396 it was identified the API GET request was getting cached, causing the Mini Cart to get out of date. That issue was solved in #62403, but it was pointed out by @luisherranz that [POST requests won't be cached](https://github.com/woocommerce/woocommerce/pull/62403#pullrequestreview-3569824482). 

I've therefore opted to remove all instances where we add the header to POST requests, for clarity. Additionally I've added a unit test to cover regressions to the GET request that caused the initial issue. That will close #62403 . 

### Screenshots or screen recordings:

N/A

### How to test the changes in this Pull Request:

You can use WooCommerce Beta Tester plugin and Live branches to test this branch on Pressable or Wordpress.com

Beta tester install instructions:

* In this repo, run `plugins/woocommerce-beta-tester/bin/build-zip.sh` it will generate the plugin zip at `plugins/woocommerce-beta-tester/woocommerce-beta-tester.zip`
* In your live site (Wordpress.com or Pressable) upload and activate the plugin generated  in the previous step and activate it.
* Now go to WooCommerce > Live Branches
* Choose this branch and install it:
Screenshot 2025-12-29 at 7 52 17 PM

The next steps are copied from the replication steps of the original issue:

* 2025 theme on Pressable or WordPress.com
* Publish some products, go to Shop archive page in a new private browsing window
* Open browser console, notice the /wp-json/wc/store/v1/cart response - open this URL in a new tab to confirm the browser shows 0 item counts etc.
* Come back to the archive page, add item to cart, the mini cart **should** update.

### Testing that has already taken place:

I've manually tested the above steps myself.

### Milestone

- [x] Automatically assign milestone for the **[next WooCommerce version](../blob/trunk/plugins/woocommerce/woocommerce.php#L6)**

> **Note:** Check the box above to have the milestone automatically assigned when merged.
> Alternatively (e.g. for point releases), manually assign the appropriate milestone.

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [x] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 
Only apply no-store header to GET request of Mini Cart store.

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce/client/blocks/assets/js/base/stores/woocommerce/test/cart.ts [hunk 1]
```diff
@@ -0,0 +1,59 @@
...
+describe( 'WooCommerce Cart Interactivity API Store', () => {
+	it( 'refreshCartItems passes cache: no-store to fetch to prevent browser caching', () => {
+		const mockFetch = jest
+			.fn()
+			.mockResolvedValue(
+				new Response(
+					JSON.stringify( { items: [], totals: {}, errors: [] } )
+				)
+			);
+		global.fetch = mockFetch;
```
Comment (luisherranz) [inline plugins/woocommerce/client/blocks/assets/js/base/stores/woocommerce/test/cart.ts:42]: Is it necessary to reset this at the end of the test?

**Review by luisherranz — APPROVED** [review]
LGTM!

File: plugins/woocommerce/client/blocks/assets/js/base/stores/woocommerce/test/cart.ts (hunk 1 above)
Comment (samueljseay) [reply plugins/woocommerce/client/blocks/assets/js/base/stores/woocommerce/test/cart.ts:42]: It sort of depends but I don't think it's necessary for this test. The mock is a per file thing, so gone once this suite runs.

but also this doesn't likely affect additional tests, if we add additional tests we'll most likely want to mock fetch in those too, so we'd overwrite this mock in the next test. If a more complex setup is needed it could be added by the next person to add tests here imo.

Comment (samueljseay) [reply plugins/woocommerce/client/blocks/assets/js/base/stores/woocommerce/test/cart.ts:42]: I'm going to merge assuming my opinion here is correct :D but if you highlight something I've missed I can do a follow up PR.
