### PR TITLE
Avoid reading items from DB of a order whose ID is zero

### LINKED ISSUE #25623: Two Orders at the same time (can) lead to a empty and a "merged" order
**Describe the bug**
First: Issue #17660 do look like the same issue, but as the issue is closed I will open a new issue with further descriptions.

If two customers orders something in our store at the same time, some (all?) products ordered from customer A get moved to customer B.

This happened now the second time, with a gap of about 6 month (?). PayPal and Amazon Pay got used as Payment Method. The older orders (~6 month ago) did use "Klarna" and PayPal.

We don't use any kind of caching (even WP-Optimize is activated as plugin, the "caching" feature got disabled, same for "Redis Object Cache" - plugin is enabled, but caching feature is disabled). We don't use load balancing and are only using a single database and server.

**To Reproduce**
1. Order something in your store two time at the same time
2. See, that some (all?) products of your first order gets included to the second order (or vice-versa).

**Screenshots**

here is the first order

first-order

here is the second order, where all ordered products got appended (the first two products belong to the first order, the third product should really be part of the order).

second-order

**Expected behavior**

Order of customer A should only include products ordered from customer A and the order of customer B should only include products ordered from customer B.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
### WordPress Environment ###

WordPress address (URL): https://auto4style.com
Site address (URL): https://auto4style.com
WC Version: 3.9.1
REST API Version: ✔ 1.0.7
Log Directory Writable: ✔
WP Version: 5.3.2
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: –
WP Cron: –
Language: de_DE
External object cache: –

### Server Environment ###

Server Info: nginx/1.16.1
PHP Version: 7.4.1
PHP Post Max Size: 50 MB
PHP Time Limit: 600
PHP Max Input Vars: 10000
cURL Version: 7.67.0
OpenSSL/1.1.1d

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.4.11-MariaDB
Max Upload Size: 50 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.8.1
WC Database Prefix: wp_
Datenbank-Gesamtgröße: 791.55MB
Datenbank-Datengröße: 429.02MB
Datenbank-Indexgröße: 362.53MB
wp_woocommerce_sessions: Daten: 9.02MB + Index: 0.08MB + Engine InnoDB
wp_woocommerce_api_keys: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Daten: 5.52MB + Index: 1.52MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Daten: 80.61MB + Index: 143.30MB + Engine InnoDB
wp_woocommerce_tax_rates: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_log: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_affiliate_wp_affiliatemeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_affiliate_wp_affiliates: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_affiliate_wp_creatives: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_affiliate_wp_customermeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_affiliate_wp_customers: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_affiliate_wp_payouts: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_affiliate_wp_referralmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_affiliate_wp_referrals: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_affiliate_wp_rest_consumers: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_affiliate_wp_visits: Daten: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_commentmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Daten: 21.55MB + Index: 16.88MB + Engine InnoDB
wp_icl_content_status: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_core_status: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_flags: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_languages: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_icl_languages_translations: Daten: 0.19MB + Index: 0.08MB + Engine InnoDB
wp_icl_locale_map: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_message_status: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_icl_mo_files_domains: Daten: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_icl_node: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_reminders: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_strings: Daten: 7.52MB + Index: 11.09MB + Engine InnoDB
wp_icl_string_packages: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_string_pages: Daten: 44.56MB + Index: 43.09MB + Engine InnoDB
wp_icl_string_positions: Daten: 0.34MB + Index: 0.11MB + Engine InnoDB
wp_icl_string_status: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_string_translations: Daten: 9.52MB + Index: 4.03MB + Engine InnoDB
wp_icl_string_urls: Daten: 0.05MB + Index: 0.05MB + Engine InnoDB
wp_icl_translate: Daten: 1.52MB + Index: 0.13MB + Engine InnoDB
wp_icl_translate_job: Daten: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_icl_translations: Daten: 4.52MB + Index: 10.06MB + Engine InnoDB
wp_icl_translation_batches: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_translation_downloads: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_translation_status: Daten: 4.52MB + Index: 1.52MB + Engine InnoDB
wp_links: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Daten: 6.20MB + Index: 0.39MB + Engine InnoDB
wp_postmeta: Daten: 164.70MB + Index: 97.22MB + Engine InnoDB
wp_posts: Daten: 38.14MB + Index: 18.02MB + Engine InnoDB
wp_redirection_404: Daten: 0.20MB + Index: 0.20MB + Engine InnoDB
wp_redirection_groups: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_redirection_items: Daten: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_redirection_logs: Daten: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_smush_dir_images: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Daten: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_terms: Daten: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Daten: 0.48MB + Index: 0.28MB + Engine InnoDB
wp_term_taxonomy: Daten: 0.06MB + Index: 0.06MB + Engine InnoDB
wp_tm_taskmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_tm_tasks: Daten: 0.09MB + Index: 0.02MB + Engine InnoDB
wp_usermeta: Daten: 0.06MB + Index: 0.06MB + Engine InnoDB
wp_users: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Daten: 2.52MB + Index: 1.77MB + Engine InnoDB
wp_wc_download_log: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Daten: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Daten: 3.52MB + Index: 1.91MB + Engine InnoDB
wp_wc_order_stats: Daten: 2.52MB + Index: 1.23MB + Engine InnoDB
wp_wc_order_tax_lookup: Daten: 1.52MB + Index: 0.89MB + Engine InnoDB
wp_wc_product_meta_lookup: Daten: 0.13MB + Index: 0.38MB + Engine InnoDB
wp_wc_tax_rate_classes: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_gzd_dhl_labelmeta: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_gzd_dhl_labels: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_gzd_shipmentmeta: Daten: 4.52MB + Index: 3.03MB + Engine InnoDB
wp_woocommerce_gzd_shipments: Daten: 1.52MB + Index: 0.39MB + Engine InnoDB
wp_woocommerce_gzd_shipment_itemmeta: Daten: 1.52MB + Index: 0.83MB + Engine InnoDB
wp_woocommerce_gzd_shipment_items: Daten: 1.52MB + Index: 0.94MB + Engine InnoDB
wp_woocommerce_gzd_shipping_provider: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_gzd_shipping_providermeta: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_yoast_seo_links: Daten: 3.52MB + Index: 1.52MB + Engine InnoDB
wp_yoast_seo_meta: Daten: 5.52MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

attachment: 62246
fpf_fields: 1
invoice: 17868
jetpack_migration: 2
jp_sitemap: 1
jp_sitemap_master: 1
ml-slide: 605
ml-slider: 71
nav_menu_item: 66
page: 336
post: 2
product: 110
product_variation: 1394
revision: 23
scheduled-action: 6239
shop_coupon: 25
shop_order: 19847
shop_order_refund: 38
site-review: 78
wc_reminder_email: 6
wpcf7_contact_form: 15

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (35) ###

WPML Multilingual CMS: von OnTheGoSystems – 4.3.6
AffiliateWP: von Sandhills Development
LLC – 2.4.4

Classic Editor: von WordPress-Mitwirkende – 1.5
Contact Form 7: von Takayuki Miyoshi – 5.1.6
Klarna Order Management for WooCommerce: von klarna
krokedil – 1.5.0 – Nicht getestest mit der aktiven WooCommerce-Version

Klarna Payments for WooCommerce: von krokedil
klarna
automattic – 2.0.5 – Nicht getestest mit der aktiven WooCommerce-Version

MetaSlider: von Team Updraft – 3.15.3
PixelYourSite Pinterest: von PixelYourSite – 2.0.10
PixelYourSite: von PixelYourSite – 7.1.4 – Nicht getestest mit der aktiven WooCommerce-Version
Redis Object Cache: von Till Krüss – 1.5.6
Site Reviews: von Paul Ryley – 4.3.8
Storefront Mega Menus: von WooCommerce – 1.6.2 – Nicht getestest mit der aktiven WooCommerce-Version
Storefront Powerpack: von WooCommerce – 1.5.0
Products: von Mathias Rohnstock – 1.0.0
User Role Editor: von Vladimir Garagulya – 4.53
Vendidero Helper: von Vendidero – 1.3.0
WooCommerce Smart Reminder Emails: von Ewout Fernhout – 1.4.2 – Nicht getestest mit der aktiven WooCommerce-Version
WC Variations Radio Buttons: von 8manos – 2.0.2 – Nicht getestest mit der aktiven WooCommerce-Version
WooCommerce Admin: von WooCommerce – 0.25.1
WooCommerce Amazon Pay: von WooCommerce – 1.11.0 – Nicht getestest mit der aktiven WooCommerce-Version
WooCommerce PayPal Checkout Gateway: von WooCommerce – 1.6.19
Sofort payment gateway: von Sven Wagener – 1.4.4 – Nicht getestest mit der aktiven WooCommerce-Version
WooCommerce Stripe-Gateway: von WooCommerce – 4.3.1 – Nicht getestest mit der aktiven WooCommerce-Version
Germanized für WooCommerce Pro: von Vendidero – 2.0.12
Germanized für WooCommerce: von Vendidero – 3.1.2
WooCommerce Multilingual: von OnTheGoSystems – 4.7.7 – Nicht getestest mit der aktiven WooCommerce-Version
WooCommerce: von Automattic – 3.9.1
Yoast SEO Premium: von Team Yoast – 12.5
WP Mail SMTP: von WPForms – 1.8.1
WP-Optimize - Clean, Compress, Cache: von David Anderson
Ruhani Rabin
Team Updraft – 3.0.16

Smush: von WPMU DEV – 3.4.2
WP Desk Helper: von WP Desk – 1.7.0 – Nicht getestest mit der aktiven WooCommerce-Version
WPML Media: von OnTheGoSystems – 2.5.5
WPML String Translation: von OnTheGoSystems – 3.0.6
WPML Translation Management: von OnTheGoSystems – 2.9.4

### Inactive Plugins (4) ###

Flexible Product Fields: von WP Desk – 1.2.11
Flexible Product Fields Pro: von WP Desk – 1.2.1 – Nicht getestest mit der aktiven WooCommerce-Version
Redirection: von John Godley – 4.6.2
WooCommerce Services: von Automattic – 1.22.3

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop-Basis: ❌ Seite nicht festgelegt
Warenkorb: #6 - /cart/
Kasse: #7 - /checkout/
Mein Konto: #8 - /mein-konto/
Allgemeine Geschäftsbedingungen: #194 - /allgemeine-geschaeftsbedingungen/

### Theme ###

Name: Storefront
Version: 2.5.3
Author URL: https://woocommerce.com/
Child Theme: ❌ – Wenn du WooCommerce mit einem Theme
das du nicht selbst entwickelt hast
an eigene Bedürfnisse anpasst
dann empfehlen wir die Verwendung eines Child-Themes. Siehe Wie du ein Child-Theme erstellst (engl.)

WooCommerce Support: ✔

### Templates ###

Overrides: /srv/http/auto4style/wp-content/plugins/theme-customisations/custom/templates/woocommerce/cart/cart-item-data.php

### Action Scheduler ###

Abgeschlossen: 5.613
Oldest: 2020-01-10 10:16:04 +0100
Newest: 2020-02-10 10:15:03 +0100

Ausstehend: 352
Oldest: 2020-02-10 10:17:27 +0100
Newest: 2020-03-11 01:41:14 +0100

Abgebrochen: 274
Oldest: 2020-02-04 13:42:33 +0100
Newest: 2020-03-07 23:32:59 +0100

In Bearbeitung: 0
Oldest: –
Newest: –

Fehlgeschlagen: 0
Oldest: –
Newest: –
</details>

Thanks

### PR DESCRIPTION
**Pull request by vedanshujain**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

When the order ID is zero, we should avoid reading its items altogether. Usually, we expect that items are not saved to DB till the order itself is saved first, however, via custom code, we can end up in a scenario where order items are indeed saved before the order is. In this case, items are saved with order id of `0`, and such there is not way to differentiate between items of different orders that are saved with ID 0.

We prevent this by not reading items from DB at all when ID is zero.

Closes #25623 

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

Note that it's really hard to test via testing instructions due to the nature of bug (race condition). So exploratory testing around creating orders via blocks checkout and traditional checkout should be enough. I have added a unit test simulating the race condition.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Comment 

</details>

### CODE REVIEW

**Comment by vedanshujain** [comment]
Note that CI is failing because of an upstream connection issue, I will try CI again in a while.

File: plugins/woocommerce/includes/data-stores/abstract-wc-order-data-store-cpt.php [hunk 1]
```diff
@@ -135,7 +143,7 @@ public function read( &$order ) {
 		$order->set_defaults();
 		$post_object = get_post( $order->get_id() );
 		if ( ! $order->get_id() || ! $post_object || ! in_array( $post_object->post_type, wc_get_order_types(), true ) ) {
-			throw new Exception( __( 'Invalid order.', 'woocommerce' ) );
+			throw new Exception( esc_html( __( 'Invalid order.', 'woocommerce' ) ) );
```
Comment (coreymckrill) [inline plugins/woocommerce/includes/data-stores/abstract-wc-order-data-store-cpt.php]:
```suggestion
			throw new Exception( esc_html__( 'Invalid order.', 'woocommerce' ) );
```

**Review by coreymckrill — APPROVED** [review]
👍 I just did some smoke tests by sending requests to the API to create orders, and everything looks ok.

One optional code tweak and then this is ready to merge.
