### PR TITLE
Fix remote inbox notification showing up for wrong country

### LINKED ISSUE #34272: Remote inbox notification appears in the wrong country
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Context: pdibGW-LT-p2

An inbox note appears in the wrong country with the following rules:

```json
{
    "rules": [
        {
            "type": "publish_after_time",
            "publish_after": "2022-08-08 00:01:07"
        },
        {
            "type": "publish_before_time",
            "publish_before": "2022-08-22 23:59:00"
        },
        {
            "type": "or",
            "operands": [
                {
                    "type": "base_location_country",
                    "operation": "=",
                    "value": "AU"
                },
                {
                    "type": "base_location_country",
                    "operation": "=",
                    "value": "AT"
                },
                {
                    "type": "base_location_country",
                    "operation": "=",
                    "value": "BE"
                },
                {
                    "type": "base_location_country",
                    "operation": "=",
                    "value": "CA"
                },
                {
                    "type": "base_location_country",
                    "operation": "=",
                    "value": "DK"
                },
                {
                    "type": "base_location_country",
                    "operation": "=",
                    "value": "FI"
                },
                {
                    "type": "base_location_country",
                    "operation": "=",
                    "value": "FR"
                },
                {
                    "type": "base_location_country",
                    "operation": "=",
                    "value": "DE"
                },
                {
                    "type": "base_location_country",
                    "operation": "=",
                    "value": "IT"
                },
                {
                    "type": "base_location_country",
                    "operation": "=",
                    "value": "NL"
                },
                {
                    "type": "base_location_country",
                    "operation": "=",
                    "value": "NZ"
                },
                {
                    "type": "base_location_country",
                    "operation": "=",
                    "value": "NO"
                },
                {
                    "type": "base_location_country",
                    "operation": "=",
                    "value": "ES"
                },
                {
                    "type": "base_location_country",
                    "operation": "=",
                    "value": "SE"
                },
                {
                    "type": "base_location_country",
                    "operation": "=",
                    "value": "CH"
                },
                {
                    "type": "base_location_country",
                    "operation": "=",
                    "value": "GB"
                },
                {
                    "type": "base_location_country",
                    "operation": "=",
                    "value": "US"
                }
            ]
        },
        {
            "type": "not",
            "operand": [
                {
                    "type": "plugins_activated",
                    "plugins": ["klarna-payments"]
                }
            ]
        }
    ]
}
```

### Expected behavior

A note should not appear in the mismatched country such as South Africa

### Actual behavior

A note appears when the store country is set to `South Africa`.

### Steps to reproduce

1. Use a fresh site
2. Set store country to **South Africa** and click on the “Continue” button
3. Skip or complete the OBW
4. Observe that the `Meet Klarna – your ultimate growth partner note` is displayed.

### WordPress Environment

N/A

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by louwie17**
### All Submissions:

-   [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
-   [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
-   [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change?

### Changes proposed in this Pull Request:

Makes sure we don't trigger the Remote inbox notifications until either the onboarding wizard has been skipped or finished, or when the user has updated the store address. This was suggested as a solution here: pdibGW-LT-p2#comment-590 

Closes [#34272](https://github.com/woocommerce/woocommerce/issues/34272) .

### How to test the changes in this Pull Request:

1. Load this branch and start a brand new store
2. add this piece of code to your mu-plugin, if you don't have an mu-plugin set up you could install the [code snippets](https://wordpress.org/plugins/code-snippets/) plugin and add this as part of that:
```
function add_datasource_remote_inbox_notifications( $data_sources, $id ) {
	if ( "remote_inbox_notifications" === $id ) {
		$data_sources[] = "https://gist.githubusercontent.com/louwie17/bd6f9fb6e0dec763f3dd9ed204924689/raw/36a64c663691ae495883a7c837a0c2bc231a3a9e/inbox-notifications.json";
	}
	return $data_sources;
}
add_filter( 'data_source_poller_data_sources', 'add_datasource_remote_inbox_notifications', 10, 2 );
```
3. Without finishing the onboarding wizard, go to **WooCommerce > Products > All products** and click Activity in the top right.
4. You should not see the **Navigate to add products only in USA and Canada** note
5. Now start the onboarding by selecting South Africa as the store location and finish the rest of the wizard.
6. Once on the home screen more notes should show, but not one with the title **Navigate to add products only in USA and Canada**, see the [inbox notification json](https://gist.githubusercontent.com/louwie17/bd6f9fb6e0dec763f3dd9ed204924689/raw/36a64c663691ae495883a7c837a0c2bc231a3a9e/inbox-notifications.json) for the full rules (should be added as part of the above snippet. You should see **Navigate to onboarding wizard** for example.
7. Start another brand new store with the same snippet above. Finish the onboarding, but this time selecting an American or Canadian address. Once you are back on the home screen it should show the **Navigate to add products only in USA and Canada** note.

### Other information:

-   [x] Have you added an explanation of what your changes do and why you'd like us to include them?
-   [x] Have you written new tests for your changes, as applicable?
-   [x] Have you successfully run tests with your changes locally?
-   [x] Have you created a changelog file for each project being changed, ie `pnpm changelog add --filter=<project>`?

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

File: plugins/woocommerce/src/Admin/RemoteInboxNotifications/RemoteInboxNotificationsEngine.php [hunk 1]
```diff
@@ -71,24 +79,37 @@ function() {
...
 	public static function update_profile_option( $old_value, $new_value ) {
 		// Return early if we're not completing the profiler.
+		$is_completed = isset( $new_value['completed'] ) && true === $new_value['completed'];
+		$is_skipped   = isset( $new_value['skipped'] ) && true === $new_value['skipped'];
 		if (
 			( isset( $old_value['completed'] ) && $old_value['completed'] ) ||
-			! isset( $new_value['completed'] ) ||
-			! $new_value['completed']
+			( isset( $old_value['skipped'] ) && $old_value['skipped'] ) ||
+			! ( $is_completed || $is_skipped )
```
Comment (louwie17) [inline plugins/woocommerce/src/Admin/RemoteInboxNotifications/RemoteInboxNotificationsEngine.php]: Also add the condition if the user skipped the onboarding wizard or not.

File: plugins/woocommerce/src/Admin/RemoteInboxNotifications/RemoteInboxNotificationsEngine.php [hunk 2]
```diff
@@ -105,6 +126,15 @@ public static function on_init() {
 		StoredStateSetupForProducts::init();
 	}
 
+	/**
+	 * Call the run function if the onboarding wizard has been completed.
+	 */
+	public static function possibly_run() {
+		if ( ! OnboardingProfile::needs_completion() || get_option( 'woocommerce_default_country', 'US:CA' ) !== 'US:CA' || ! empty( get_option( 'woocommerce_store_address', '' ) ) ) {
```
Comment (louwie17) [inline plugins/woocommerce/src/Admin/RemoteInboxNotifications/RemoteInboxNotificationsEngine.php]: I added the extra condition of the default_country check and store_address, as I am not sure if this would break things on existing stores.
Most if not all existing stores should have the onboarding wizard set to completed, but I don't know if there could be a way around that.

One other solution is to allow notes to be updated back to `pending` after being set to `unactioned`, we currently don't allow this, but this would fix the problem as well.
I decided to not go this route, as it could potentially cause strange behaviour as well, it might actually remove a lot of notes that rely on the store age. As a lot of those are time boxed between 1-7days for example, but maybe that is acceptable if the note was still `unactioned`?

File: plugins/woocommerce/src/Internal/Admin/Events.php [hunk 3]
```diff
@@ -158,7 +158,7 @@ public function do_wc_admin_daily() {
 
 		if ( $this->is_remote_inbox_notifications_enabled() ) {
 			DataSourcePoller::get_instance()->read_specs_from_data_sources();
-			RemoteInboxNotificationsEngine::run();
+			RemoteInboxNotificationsEngine::possibly_run();
```
Comment (louwie17) [inline plugins/woocommerce/src/Internal/Admin/Events.php]: Also updated it here, as this appears to be run when WooCommerce is initially installed/enabled.

File: plugins/woocommerce/src/Admin/RemoteInboxNotifications/RemoteInboxNotificationsEngine.php (hunk 2 above)
Comment (chihsuan) [reply plugins/woocommerce/src/Admin/RemoteInboxNotifications/RemoteInboxNotificationsEngine.php]: > I decided to not go this route, as it could potentially cause strange behaviour as well, it might actually remove a lot of notes that rely on the store age. As a lot of those are time boxed between 1-7days for example, but maybe that is acceptable if the note was still unactioned?

While I'm also not sure if it's safe, I think it makes sense to update `unactioned` notes back to `pending` when their rules no longer pass. 

cc @pmcpinto

Comment (pmcpinto) [reply plugins/woocommerce/src/Admin/RemoteInboxNotifications/RemoteInboxNotificationsEngine.php]: > I decided to not go this route, as it could potentially cause strange behaviour as well, it might actually remove a lot of notes that rely on the store age. As a lot of those are time boxed between 1-7days for example, but maybe that is acceptable if the note was still unactioned?


would this option remove notifications to any store or just existing stores?

Comment (louwie17) [reply plugins/woocommerce/src/Admin/RemoteInboxNotifications/RemoteInboxNotificationsEngine.php]: It would remove notifications for any store only for the remote notifications. IF the conditions don't meet anymore and if the user hasn't clicked the note already. 
For example the **WooCommerce Shipping & Tax** note, has a condition to show up for stores less than two day's old. This would mean it would be removed after the store is older then 2 days.

We could potentially add an exception to the **publish_before_time** & **wcadmin_active_for**, or add a new option to the Remote Inbox Notifications, that would allow certain notes to be updated after moving to `unactioned`, but the default will not be.

**Review by moon0326 — COMMENTED** [review]
Code LGTM and tested as expected 🎉 , but I was wondering if it makes things simpler if we update [BaseLocationCountryRuleProcess.php](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/src/Admin/RemoteInboxNotifications/BaseLocationCountryRuleProcessor.php) instead? As far as I understand, the [default country](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/includes/wc-core-functions.php#L1319) is the culprit of the problem.

**Comment by louwie17** [comment]
> Code LGTM and tested as expected 🎉 , but I was wondering if it makes things simpler if we update [BaseLocationCountryRuleProcess.php](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/src/Admin/RemoteInboxNotifications/BaseLocationCountryRuleProcessor.php) instead? As far as I understand, the [default country](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/includes/wc-core-functions.php#L1319) is the culprit of the problem.

Hmm yeah that's a good suggestion. Do you think we should add a condition to that rule to check if the `country` is actually set? and if not default to `false`?
That would fix this problem, and be a much better solution ( I think ).

**Comment by moon0326** [comment]
> 

Yup! That should work unless there are other problems related to onboarding data.

File: plugins/woocommerce/src/Admin/RemoteInboxNotifications/RemoteInboxNotificationsEngine.php (hunk 2 above)
Comment (pmcpinto) [reply plugins/woocommerce/src/Admin/RemoteInboxNotifications/RemoteInboxNotificationsEngine.php]: > It would remove notifications for any store only for the remote notifications. IF the conditions don't meet anymore and if the user hasn't clicked the note already.
For example the WooCommerce Shipping & Tax note, has a condition to show up for stores less than two day's old. This would mean it would be removed after the store is older then 2 days.

Mmm I think this can be problematic, as users would have a short window of time to interact with the notification.

Comment (louwie17) [reply plugins/woocommerce/src/Admin/RemoteInboxNotifications/RemoteInboxNotificationsEngine.php]: > Mmm I think this can be problematic, as users would have a short window of time to interact with the notification.

Yeah that is my thinking as well, I think [Moon's suggestion](https://github.com/woocommerce/woocommerce/pull/34632#pullrequestreview-1104454767) for this would be better, and allow things to work the same otherwise.

**Comment by louwie17** [comment]
@moon0326 or @chihsuan would you have time for another look. I updated this to follow @moon0326 suggestion by only updating the base location country rule, this feels much nicer.

**Review by chihsuan — DISMISSED** [review]
Perfect! Thanks for the fix. @louwie17 👍

**Comment by louwie17** [comment]
> Perfect! Thanks for the fix. @louwie17 👍

@chihsuan would you be able to give me a re-approval, I had to do a rebase to get the E2E tests passing again, that was related to this issue: p1663068308711999-slack-C03CPM3UXDJ

**Review by octaedro — APPROVED** [review]
LGTM 🚀
