### PR TITLE
Ensure Order Attribution input element stamped

### LINKED ISSUE #62508: Order Attribution frequently records source as “Unknown” despite valid UTM session entry (since WooCommerce 8.9 / 9.x)
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

After upgrading WooCommerce (worked correctly before), **Order Attribution frequently saves orders with source = “Unknown”**, even when the customer clearly enters the site via a URL containing valid UTM parameters and completes checkout in the same session.

This results in significant attribution loss in WooCommerce Analytics.

### Expected behavior

When a user enters the site via a URL like:
https://example.com/?utm_source=test&utm_medium=test&utm_campaign=test

and completes checkout in the same session, WooCommerce should persist:

- `_wc_order_attribution_source_type = utm`
- `_wc_order_attribution_utm_source`
- `_wc_order_attribution_utm_medium`
- `_wc_order_attribution_utm_campaign`

### Actual behavior

- Orders are frequently saved with:
  - Source = **Unknown**
  - All `_wc_order_attribution_utm_*` meta fields empty
- This happens even when:
  - The first page load contains UTM parameters
  - Checkout is completed without leaving the session
  - No redirects occur

### Evidence / Verification

To verify whether UTMs actually exist in the user session, we compared results with PixelYourSite:

For several orders marked as “Unknown” by WooCommerce, PixelYourSite detected:

- Traffic source: `google.com`
- utm_source: `Googleads`
- utm_medium: `cpc_feed`
- utm_campaign: `Pmax`

This confirms that UTMs **exist in the browser session**, but are not persisted by WooCommerce Order Attribution.

---

### What we already tried

1. Verified cookies:
   - `sbjs_first`, `sbjs_current`
   - `wp_woocommerce_session_*`
   - UTM parameters present on landing page

2. Tested in incognito mode with a clean session.

3. Implemented the following snippet suggested by WooCommerce support to add fallback hooks for attribution stamping:

```php
add_filter('wc_order_attribution_stamp_checkout_html_actions', function($actions) {
    $actions[] = 'woocommerce_before_checkout_form';
    $actions[] = 'woocommerce_checkout_billing';
    $actions[] = 'woocommerce_review_order_before_payment';
    return array_unique($actions);
}, 10);

Result: No improvement. Orders still saved with “Unknown”.

Implemented a temporary fallback that copies UTM data from PixelYourSite cookies only when WooCommerce attribution is empty (to avoid losing all attribution).
This confirms the data exists, but WooCommerce does not capture it reliably.

Hypothesis

This appears to be a timing / session initialization issue, possibly related to:

When WooCommerce Order Attribution JS runs

When the WooCommerce session is initialized

Interaction with themes that defer WooCommerce JS

CMP consent timing (even when consent is granted)

It seems attribution may be finalized before UTM data is reliably available, leading to “Unknown” attribution.

Request

Could you please clarify:

What exact conditions must be met for Order Attribution to persist UTM data?

Is there a recommended way to debug or log when attribution stamping runs and what payload it sees?

Have there been recent changes (8.9 / 9.x) that made Order Attribution stricter or altered its timing?

Are there known issues with custom themes, deferred JS, or CMP interaction?

I’m happy to provide:

order meta exports

cookie snapshots

logs from test orders

if you can advise what to capture.

Thanks for looking into this.

### WordPress Environment

- WordPress: latest 6.9
- WooCommerce: 10.4.0 (issue started after recent updates)
- Checkout: standard `[woocommerce_checkout]` shortcode
- Theme: Rey (uses custom WooCommerce templates)
- Plugins involved:
  - Elementor / Elementor Pro
  - Complianz Premium (CMP)
  - PixelYourSite (used only for comparison / validation)
- Order Attribution: enabled



### Isolating the problem

- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by layoutd**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes #62508

This PR fixes an issue where shortcodes being executed before page rendering could lead to the  `<wc-order-attribution-inputs>` element being marked as stamped, which prevented the data from being included in the checkout form, and thus in the order data.

**Problem:**
The previous implementation used a static flag (`$is_stamp_checkout_html_called`) to prevent the checkout HTML element from being stamped multiple times. However, this approach was overly restrictive and didn't account for legitimate scenarios where the element might need to be rendered multiple times during the page lifecycle (e.g., during form pre-generation and actual rendering). Additionally, the JavaScript layer only removed duplicate elements once during initial script execution, meaning any elements added after initialization would persist as duplicates.

**Solution:**
- **PHP Layer**: Removed the static flag restriction, allowing the element to be stamped naturally when needed. Added a filter (`wc_order_attribution_allow_multiple_elements`) to allow opt-back into single-output behavior during the transition period.
- **JavaScript Layer**: Add the `removeDuplicateInputGroups()` function to run every time form values are updated (inside `updateFormValues()`). This ensures duplicate elements are removed continuously, regardless of when they're added to the DOM (pre-rendering, AJAX updates, dynamic form changes, etc.).
- Updated documentation to clarify that multiple instances may exist temporarily but are handled gracefully by the JavaScript layer.
- Cursor also caught a possible bug where the static property could be persisted across sessions and users if they're on the same PHP-FPM worker, so the property is reset on init as well.

This approach is more flexible and handles edge cases better (including checkout page pre-rendering and dynamic updates) while still preventing duplicate data submission.

Closes WOOPLUG-6040.

### How to test the changes in this Pull Request:

1. Set up a WooCommerce store.
2. Navigate to the checkout page
3. Open browser developer tools and inspect the DOM for `<wc-order-attribution-inputs>` elements and ensure only one is present `document.querySelectorAll( 'wc-order-attribution-inputs' )`
4. Verify that order attribution data is properly captured and submitted with checkout (only once)
5. Test with various checkout scenarios:
   - Checkout page with shortcode `[woocommerce_checkout]`
   - With a test hook to pre-render the checkout code:
   ```php
    /**
      * Simulates SEO plugin analyzing page content before render.
      * This reproduces the RankMath/Yoast "time to read" calculation issue.
      */
    add_action( 'wp', function() {
        if ( function_exists( 'is_checkout' ) && is_checkout() ) {
            $post = get_post();
            if ( $post ) {
                do_shortcode( $post->post_content );
            }
        }
    }, 5 );
    ```
   - Standard checkout flow
   - Checkout with validation errors (forcing form re-render)
   - Checkout with multiple payment methods
   

8. Verify that no duplicate order attribution data appears in submitted orders meta data
9. Check browser console for any JavaScript errors related to order attribution

### Testing that has already taken place:

- Verified that the `removeDuplicateInputGroups()` function correctly identifies and removes duplicate elements on every form update
- Tested checkout flow with form validation errors that trigger re-renders
- Confirmed order attribution data is properly captured and submitted without duplication
- Verified that dynamically added elements (after initial page load) are properly cleaned up

### Milestone

- [x] Automatically assign milestone for the **[next WooCommerce version](../blob/trunk/plugins/woocommerce/woocommerce.php#L6)**

> **Note:** Check the box above to have the milestone automatically assigned when merged.
> Alternatively (e.g. for point releases), manually assign the appropriate milestone.

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message

Fix missing order attribution elements when checkout page is pre-rendered.

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment

</details>

### CODE REVIEW

File: plugins/woocommerce/src/Internal/Orders/OrderAttributionController.php [hunk 1]
```diff
@@ -141,7 +134,7 @@ function () {
 			)
 		);
 		foreach ( $stamp_checkout_html_actions as $action ) {
-			add_action( $action, array( $this, 'stamp_checkout_html_element_once' ) );
+			add_action( $action, array( $this, 'stamp_html_element' ) );
```
[the remark this answers is not in the document]
Comment (layoutd) [reply plugins/woocommerce/src/Internal/Orders/OrderAttributionController.php:153]: Restored method and marked as deprecated in 34450671a45232a6349cce84cd59edcbe96e4322

File: plugins/woocommerce/src/Internal/Orders/OrderAttributionController.php [hunk 2]
```diff
@@ -387,23 +380,13 @@ private function output_origin_column( WC_Order $order ) {
...
-	}
-
-	/**
-	 * Output `<wc-order-attribution-inputs>` element that contributes the order attribution values to the enclosing form.
-	 * Used customer register forms, and for checkout forms through `stamp_checkout_html_element()`.
+	 * Note: This method may output multiple instances of the element when called multiple times
+	 * (e.g., during checkout form pre-generation and actual rendering). The JavaScript layer
+	 * will update all instances and the form submission will determine which data is used.
 	 *
 	 * @return void
```
[the remark this answers is not in the document]
Comment (layoutd) [reply plugins/woocommerce/src/Internal/Orders/OrderAttributionController.php:420]: Added filter in 34450671a45232a6349cce84cd59edcbe96e4322

File: plugins/woocommerce/src/Internal/Orders/OrderAttributionController.php [hunk 3]
```diff
@@ -387,23 +388,46 @@ private function output_origin_column( WC_Order $order ) {
...
 	 */
 	public function stamp_checkout_html_element_once() {
-		if ( self::$is_stamp_checkout_html_called ) {
+		wc_deprecated_function( __METHOD__, '9.5.0', 'stamp_html_element' );
+
+		/**
+		 * Filter to allow sites to opt back into single-output behavior during the transition period.
+		 *
+		 * @since 9.5.0
```
Comment (chihsuan) [inline plugins/woocommerce/src/Internal/Orders/OrderAttributionController.php]:
```suggestion
		 * @since 10.5.0
```

File: plugins/woocommerce/src/Internal/Orders/OrderAttributionController.php [hunk 4]
```diff
@@ -387,23 +388,46 @@ private function output_origin_column( WC_Order $order ) {
...
+	 * Handles the `<wc-order-attribution-inputs>` element for checkout forms.
 	 *
 	 * @since 9.0.0
+	 * @deprecated 9.5.0 Use stamp_html_element() instead. This method is maintained for backwards compatibility.
 	 *
 	 * @return void
 	 */
 	public function stamp_checkout_html_element_once() {
-		if ( self::$is_stamp_checkout_html_called ) {
+		wc_deprecated_function( __METHOD__, '9.5.0', 'stamp_html_element' );
```
Comment (chihsuan) [inline plugins/woocommerce/src/Internal/Orders/OrderAttributionController.php]:
```suggestion
		wc_deprecated_function( __METHOD__, '10.5.0', 'stamp_html_element' );
```

File: plugins/woocommerce/src/Internal/Orders/OrderAttributionController.php [hunk 5]
```diff
@@ -387,23 +388,46 @@ private function output_origin_column( WC_Order $order ) {
 	}
 
 	/**
-	 * Handles the `<wc-order-attribution-inputs>` element for checkout forms, ensuring that the field is only output once.
+	 * Handles the `<wc-order-attribution-inputs>` element for checkout forms.
 	 *
 	 * @since 9.0.0
+	 * @deprecated 9.5.0 Use stamp_html_element() instead. This method is maintained for backwards compatibility.
```
Comment (chihsuan) [inline plugins/woocommerce/src/Internal/Orders/OrderAttributionController.php]:
```suggestion
	 * @deprecated 10.5.0 Use stamp_html_element() instead. This method is maintained for backwards compatibility.
```

File: plugins/woocommerce/src/Internal/Orders/OrderAttributionController.php (hunk 4 above)
Comment (chihsuan) [reply plugins/woocommerce/src/Internal/Orders/OrderAttributionController.php]: I noticed that we're still registering `stamp_checkout_html_element_once` method s the callback for checkout actions. This will generate deprecation notices on every checkout page load for all sites.

**Review by chihsuan — COMMENTED** [review]
Thanks for this fix, @layoutd! The approach of allowing multiple elements in PHP and deduplicating in JavaScript is sound. However, I found two critical issues that should be addressed before merging:

 1. Incorrect Version Annotations

  The `@since` and `@deprecated` annotations use 9.5.0, but based on the current trunk version (10.5.0-dev), these should be 10.5.0.

2. Deprecation Notice Will Trigger on Every Checkout Page Load

The `stamp_checkout_html_element_once()` method is marked deprecated, and calls `wc_deprecated_function()`, but we still register this method as the callback for checkout actions.


Since this method resides in the **internal** namespace and is unlikely to be used outside of WooCommerce Core, preserving backward compatibility is not required IMO. I'd suggest directly depreciating or removing the method.

File: plugins/woocommerce/src/Internal/Orders/OrderAttributionController.php (hunk 4 above)
Comment (layoutd) [reply plugins/woocommerce/src/Internal/Orders/OrderAttributionController.php]: Good catch, I've replaced the deprecated method altogether in 0be17617281ae1cdd1081ba59bbfb54e7063c059

File: plugins/woocommerce/src/Internal/Orders/OrderAttributionController.php [hunk 6]
```diff
@@ -387,23 +388,46 @@ private function output_origin_column( WC_Order $order ) {
...
 			return;
 		}
+
 		$this->stamp_html_element();
-		self::$is_stamp_checkout_html_called = true;
+
+		if ( ! $allow_multiple ) {
+			self::$is_stamp_checkout_html_called = true;
+		}
 	}
```
[the remark this answers is not in the document]
Comment (layoutd) [reply plugins/woocommerce/src/Internal/Orders/OrderAttributionController.php:409]: Already addressed in 0be17617281ae1cdd1081ba59bbfb54e7063c059

**Review by chihsuan — APPROVED** [review]
Thanks for addressing feedback! @layoutd LGTM! Let's get this merged. 🚢

**Comment by sunethkr2-prog** [comment]
is this really fixed, mine have latest woocommerce version and still not since Feb 8 Origin of all orders shows as Unknown, how to fix this
Screenshot 2026-03-09 090905
