### PR TITLE
Do not load all tables in multisite system status

### LINKED ISSUE #20724: Status Page performance and security issues on multisite
## Prerequisites

- [ x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Setup a wordpress multisite network 
2. Navigate to a child site
3. View WooCommerce -> Status Page

## Expected/actual behavior

I was requested to write this up by WooCommerce help.

- The Status page loads up every single table in the multisite network. If the network is large ( over ~500 sites) The page load time can get very long. I am experiencing several minutes on my 1600 site network.
- This makes accessing items under the "Tools" and "Logs" tab very inconvenient
- Submitting support tickets to WooCommerce becomes difficult with the size of status report. There should be a summary option for multisite that only shows most important details.
- Also, single site admins really shouldn't be allowed to see tables for every single site in the network, or most of the details in the system status report either.  For my use case I would just block access to the "Status" page, but I like to allow access to the "Tools" tab. 
- In my opinion, it would be nice if system status and tools were separate menu items or that system status reports had their own permission settings.

## Isolating the problem

- [x ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x ] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
Wordpress Multisite 4.9.6
Status Report: ... that's kind of the point of my post, it's too big.
```
</details>

### PR DESCRIPTION
**Pull request by kloon**
### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

This PR makes it that when on a multisite and opening up the system status report it should not load all the tables in the database for the multisite, but only ones matching the current blog.

Closes #20724

### How to test the changes in this Pull Request:

1. Create a WP multisite install
2. Setup two or more stores on the MS
3. Log into one of the stores and view the system status report, it should only display the tables matching that store.
4. Normal WP installs should still load tables present in the DB.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

### Changelog entry

> Update - Only display the current site's tables for a multisite install when viewing the system status.

### CODE REVIEW

File: includes/api/class-wc-rest-system-status-controller.php [hunk 1]
```diff
@@ -722,6 +722,12 @@ public function get_database_info() {
 		);
 
 		foreach ( $database_table_sizes as $table ) {
+			// Only include tables matching the prefix of the current site, this is to prevent displaying all tables on a MS install not relating to the current.
+			if ( is_multisite() ) {
+				if ( 0 !== strpos( $table->name, $wpdb->prefix ) ) {
```
Comment (claudiulodro) [inline includes/api/class-wc-rest-system-status-controller.php]: I think this logic needs some tweaking. [Sites created after the first one will have `wp_2`, `wp_3`, etc. as their prefix.](https://premium.wpmudev.org/forums/topic/table-prefix-on-multisite#post-324657) 

This check will make the first site in the multisite (with prefix `wp_`) to show all tables from all sites, as `0 === strpos( 'wp_2_tablename', 'wp_' )`. I was able to reproduce this in my local environment.

**Review by claudiulodro — CHANGES_REQUESTED** [review]
Good idea; just a small bug that needs fixing.

File: includes/api/class-wc-rest-system-status-controller.php (hunk 1 above)
Comment (kloon) [reply includes/api/class-wc-rest-system-status-controller.php]: This is a tricky one as all prefixes start with the same chars, I was under the impression on a MS the first blog would prefix _1 as it uses the ID for all other sites in a network but guess this is not the case.

Any recommendation on what to do here?

Comment (kloon) [reply includes/api/class-wc-rest-system-status-controller.php]: @claudiulodro thanks for pointing me in the right direction here, found there's a $wpdb->tables() function that simplifies this even more so used that instead.

**Review by claudiulodro — APPROVED** [review]

**Comment by iWebbers** [comment]
Don't want to spoil everyones dinner but after updating to WooCommerce version 3.5.1 this bug (Database tables do not exist) still remains.

**Comment by kloon** [comment]
@iWebbers the PR with the supposed fix has not been merged yet, will likely make it into 3.5.2 https://github.com/woocommerce/woocommerce/pull/21706

**Comment by dbmpls** [comment]
Apologies, not sure how the workflow here works. I reported the original issue here: https://github.com/woocommerce/woocommerce/issues/20724

However, as of WooCommerce 3.6.3 I still take down my multisite network by clicking on the woocommerce status page. 

If the fix has been implemented, it unfortunately does not work.  What would be the best way that I can followup on a fix, and provide additional information if needed?
