### PR TITLE
Simplify the applied coupon data that gets stored as line item meta

### LINKED ISSUE #36295: Order item metadata table coupon_data rows growing nearly half the total database size
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Reopening issue #19450 after an earlier fix became inadequate.

I'm looking at a client's site with Database Data Size = 1235.88MB and of that the coupon_data rows of wp_woocommerce_order_items are ~450MB.

I checked on the age of the orders for which this data is stored and see it includes orders from today and recently.

This client actively uses an older coupon code with the restriction "Usage limit per user" = 1.

I'll attach the unserialized data showing where 340 rows fit into the data and are redacted here for privacy.

```
Array
(
    [id] => 4626
    [code] => first15
    [amount] => 15
    [status] => publish
    [date_created] => __PHP_Incomplete_Class Object
        (
            [__PHP_Incomplete_Class_Name] => WC_DateTime
            [ * utc_offset] => 0
            [date] => 2020-08-05 09:58:00.000000
            [timezone_type] => 3
            [timezone] => America/Los_Angeles
        )

    [date_modified] => __PHP_Incomplete_Class Object
        (
            [__PHP_Incomplete_Class_Name] => WC_DateTime
            [ * utc_offset] => 0
            [date] => 2020-09-08 10:48:38.000000
            [timezone_type] => 3
            [timezone] => America/Los_Angeles
        )

    [date_expires] => 
    [discount_type] => percent
    [description] => Spin to Win - 1x use per customer
    [usage_count] => 7570
    [individual_use] => 1
    [product_ids] => Array
        (
        )

    [excluded_product_ids] => Array
        (
        )

    [usage_limit] => 0
    [usage_limit_per_user] => 1
    [limit_usage_to_x_items] => 
    [free_shipping] => 
    [product_categories] => Array
        (
        )

    [excluded_product_categories] => Array
        (
        )

    [exclude_sale_items] => 
    [minimum_amount] => 
    [maximum_amount] => 
    [email_restrictions] => Array
        (
        )

    [virtual] => 
    [meta_data] => Array
        (
            [0] => __PHP_Incomplete_Class Object
                (
                    [__PHP_Incomplete_Class_Name] => WC_Meta_Data
                    [ * current_data] => Array
                        (
                            [id] => 127599
                            [key] => itemlist_item_3711
                            [value] => Array
                                (
                                )

                        )

                    [ * data] => Array
                        (
                            [id] => 127599
                            [key] => itemlist_item_3711
                            [value] => Array
                                (
                                )

                        )

                )

...

            [339] => __PHP_Incomplete_Class Object
                (
                    [__PHP_Incomplete_Class_Name] => WC_Meta_Data
                    [ * current_data] => Array
                        (
                            [id] => 3195766
                            [key] => _maybe_used_by_1672260676_OGhoxS
                            [value] => email_redacted@gmail.com
                        )

                    [ * data] => Array
                        (
                            [id] => 3195766
                            [key] => _maybe_used_by_1672260676_OGhoxS
                            [value] => email_redacted@gmail.com
                        )

                )

        )

)
```

### Expected behavior

I expect to see only data related to an order stored within its order items. Wider coupon usage data belongs with the coupon.

### Actual behavior

We're storing data from 340 users of a coupon code into new orders where the coupon code was used just once.

### Steps to reproduce

1. Open WooCommerce > Status
2. Observe wp_woocommerce_order_itemmeta = Data 628.61MB and Database Data Size = 1235.88MB
3. Open PhpMyAdmin and select the store's database
5. Click SQL and run this query to see the largest order item meta rows with order IDs and dates: `SELECT p.ID, p.post_date, oim.meta_key, ROUND( LENGTH( oim.meta_value ) / 1024 ) as size FROM wp_woocommerce_order_itemmeta oim JOIN wp_woocommerce_order_items oi ON oim.order_item_id = oi.order_item_id JOIN wp_posts p ON oi.order_id = p.ID ORDER BY `size` DESC;`
6. Observe thousands of rows of coupon_data occupying up to 94KB each.

### WordPress Environment

`
### WordPress Environment ###

WC Version: 7.2.2
REST API Version: ✔ 7.2.2
WC Blocks Version: ✔ 8.9.2
Action Scheduler Version: ✔ 3.4.0
Log Directory Writable: ✔
WP Version: 6.1.1
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 8.0.25
PHP Post Max Size: 100 MB
PHP Time Limit: 43300
PHP Max Input Vars: 10000
cURL Version: 7.58.0
OpenSSL/1.1.1

SUHOSIN Installed: –
MySQL Version: 5.7.39-42-log
Max Upload Size: 50 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.2.2
WC Database Prefix: wp_
Total Database Size: 1830.49MB
Database Data Size: 1235.88MB
Database Index Size: 594.61MB
wp_woocommerce_sessions: Data: 26.05MB + Index: 2.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 12.52MB + Index: 3.52MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 628.61MB + Index: 68.19MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.50MB + Index: 0.09MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 1.52MB + Index: 0.66MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 83.14MB + Index: 103.44MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.06MB + Index: 0.05MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 60.61MB + Index: 47.14MB + Engine InnoDB
wp_commentmeta: Data: 4.52MB + Index: 4.02MB + Engine InnoDB
wp_comments: Data: 70.61MB + Index: 47.13MB + Engine InnoDB
wp_dgwt_wcas_index: Data: 0.42MB + Index: 0.02MB + Engine InnoDB
wp_dgwt_wcas_invindex_cache: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_dgwt_wcas_invindex_cache_page: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_dgwt_wcas_invindex_cache_post: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_dgwt_wcas_invindex_doclist: Data: 26.55MB + Index: 30.06MB + Engine InnoDB
wp_dgwt_wcas_invindex_doclist_page: Data: 0.16MB + Index: 0.19MB + Engine InnoDB
wp_dgwt_wcas_invindex_doclist_post: Data: 2.52MB + Index: 3.03MB + Engine InnoDB
wp_dgwt_wcas_invindex_wordlist: Data: 1.52MB + Index: 0.44MB + Engine InnoDB
wp_dgwt_wcas_invindex_wordlist_page: Data: 0.11MB + Index: 0.08MB + Engine InnoDB
wp_dgwt_wcas_invindex_wordlist_post: Data: 0.45MB + Index: 0.30MB + Engine InnoDB
wp_dgwt_wcas_tax_index: Data: 0.11MB + Index: 0.05MB + Engine InnoDB
wp_dgwt_wcas_var_index: Data: 0.39MB + Index: 0.06MB + Engine InnoDB
wp_e_events: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_e_notes: Data: 0.02MB + Index: 0.17MB + Engine InnoDB
wp_e_notes_users_relations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_e_submissions: Data: 0.02MB + Index: 0.27MB + Engine InnoDB
wp_e_submissions_actions_log: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_e_submissions_values: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gla_attribute_mapping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gla_budget_recommendations: Data: 0.22MB + Index: 0.14MB + Engine InnoDB
wp_gla_merchant_issues: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gla_shipping_rates: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gla_shipping_times: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_ms_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 3.05MB + Index: 0.17MB + Engine InnoDB
wp_postmeta: Data: 235.77MB + Index: 221.55MB + Engine InnoDB
wp_posts: Data: 18.52MB + Index: 10.06MB + Engine InnoDB
wp_redirection_404: Data: 3.02MB + Index: 0.70MB + Engine InnoDB
wp_redirection_groups: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_redirection_items: Data: 0.23MB + Index: 0.30MB + Engine InnoDB
wp_redirection_logs: Data: 0.13MB + Index: 0.05MB + Engine InnoDB
wp_signups: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_smush_dir_images: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_snippets: Data: 0.09MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.45MB + Index: 0.52MB + Engine InnoDB
wp_terms: Data: 0.13MB + Index: 0.16MB + Engine InnoDB
wp_term_relationships: Data: 0.36MB + Index: 0.28MB + Engine InnoDB
wp_term_taxonomy: Data: 2.52MB + Index: 0.11MB + Engine InnoDB
wp_tm_taskmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_tm_tasks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_usermeta: Data: 23.56MB + Index: 25.09MB + Engine InnoDB
wp_users: Data: 1.52MB + Index: 1.11MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 3.52MB + Index: 3.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_gpf_render_cache: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 1.52MB + Index: 0.75MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 7.52MB + Index: 8.06MB + Engine InnoDB
wp_wc_order_stats: Data: 5.52MB + Index: 4.55MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.14MB + Index: 0.13MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.25MB + Index: 0.53MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_gpf_google_taxonomy: Data: 1.52MB + Index: 0.13MB + Engine InnoDB
wp_woocommerce_shipping_table_rates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_yith_wcan_filter_sessions: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_yoast_indexable: Data: 2.52MB + Index: 0.97MB + Engine InnoDB
wp_yoast_indexable_hierarchy: Data: 0.27MB + Index: 0.25MB + Engine InnoDB
wp_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_primary_term: Data: 0.08MB + Index: 0.06MB + Engine InnoDB
wp_yoast_prominent_words: Data: 1.52MB + Index: 3.50MB + Engine InnoDB
wp_yoast_seo_links: Data: 0.52MB + Index: 0.39MB + Engine InnoDB
wp_yoast_seo_meta: Data: 0.16MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

acf-field: 20
acf-field-group: 9
attachment: 1301
custom_css: 3
elementor_font: 1
elementor_library: 19
nav_menu_item: 101
oembed_cache: 19
page: 21
post: 94
product: 523
product_variation: 597
revision: 38
shop_coupon: 307
shop_order: 43577
shop_order_refund: 1391
wp_block: 1
wp_global_styles: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (30) ###

Advanced Custom Fields: by WP Engine – 6.0.6
FiboSearch - AJAX Search for WooCommerce (Pro): by FiboSearch Team – 1.21.1
Akismet Anti-Spam: by Automattic – 5.0.2
WP Engine Smart Plugin Manager: by WP Engine – 5.13.8
Code Snippets: by Code Snippets Pro – 3.2.2
Elementor Pro: by Elementor.com – 3.9.2
Elementor: by Elementor.com – 3.9.2
Facebook for WooCommerce: by Facebook – 3.0.7
Google Listings and Ads: by WooCommerce – 2.3.5
Google Tag Manager for WooCommerce PRO: by Handcraft Byte – 1.7.3
Judge.me Product Reviews for WooCommerce: by Judge.me – 1.3.20
Klaviyo: by Klaviyo
Inc. – 3.0.6

Pinterest for WooCommerce: by WooCommerce – 1.2.8
reCaptcha for WooCommerce: by I Thirteen Web Solution – 2.38
Redirection: by John Godley – 5.3.6
Up-sell Trio for WooCommerce: by Coded Commerce
LLC – 1.2

User Role Editor: by Vladimir Garagulya – 4.63.2
User Switching: by John Blackbourn & contributors – 1.7.0
WooCommerce Address Validation: by SkyVerge – 2.10.0
WooCommerce Stripe Gateway: by WooCommerce – 7.0.1
WooCommerce Multi-currency: by TIV.NET INC – 3.1.2
WooCommerce Quick View: by WooCommerce – 1.6.0
WooCommerce - ShipStation Integration: by WooCommerce – 4.3.2
WooCommerce: by Automattic – 7.2.2
Yoast SEO Premium: by Team Yoast – 19.6
Yoast SEO: by Team Yoast – 19.13
WP-Optimize - Clean, Compress, Cache: by David Anderson
Ruhani Rabin
Team Updraft – 3.2.10

Smush: by WPMU DEV – 3.12.4
Yoast SEO: WooCommerce: by Team Yoast – 15.4
Zoho Mail: by Zoho Mail – 1.4.9

### Inactive Plugins (2) ###

GoDaddy Payments: by GoDaddy – 1.3.4
Query Monitor: by John Blackbourn – 3.11.1

### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
object-cache.php: Memcached Redux

### Must Use Plugins (5) ###

Force Strong Passwords - WPE Edition: by Jason Cosper – 1.8.0
WP Engine Cache Plugin: by WP Engine – 1.1.0
WP Engine Seamless Login Plugin: by WP Engine – 1.6.0
WP Engine Security Auditor: by wpengine – 1.0.10
WP Engine System: by WP Engine – 5.0.1

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: –
Order datastore: WC_Order_Data_Store_CPT

### WC Pages ###

Shop base: #16485 - /products/
Cart: #122 - /cart/
Checkout: #123 - /checkout/
My account: #125 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Hello Elementor
Version: 2.6.1
Author URL: https://elementor.com/?utm_source=wp-themes&utm_campaign=author-uri&utm_medium=wp-dash
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
experimental-products-task
experimental-import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
multichannel-marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
settings

Daily Cron: ✔ Next scheduled: 2023-01-04 18:56:23 -08:00
Options: ✔
Notes: 8
Onboarding: completed

### Action Scheduler ###

Complete: 250,207
Oldest: 2022-12-04 09:48:10 -0800
Newest: 2023-01-04 09:42:41 -0800

Pending: 21
Oldest: 2023-01-04 09:44:55 -0800
Newest: 2023-01-10 11:25:18 -0800

### Status report information ###

Generated at: 2023-01-04 09:44:14 -08:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by Konamiman**
### Changes proposed in this Pull Request:

Context: https://github.com/woocommerce/woocommerce/discussions/41040

Short version of the issue: whenever a coupon is applied to an order a `coupon_data` metadata entry is created for the corresponding discount line item, which contains an almost entire copy of the coupon object; https://github.com/woocommerce/woocommerce/pull/19669 removed the coupon usage data from the data that gets stored, but still, the stored data is too big and is causing issues in large stores.

This pull request introduces the following changes:

1. Instead of the verbose `coupon_data` entry, a simplified `coupon_info` entry is created when a coupon is applied to an order. It contains a JSON encoded array with the following information about the coupon: id, code, discount type (`fixed_cart` is considered the default and stored as `null`), nominal amount, and whether the coupon grants free shipping (this is added to the array only if the value is `true`).
2. The `WC_Coupon` class gets the `get_short_info` method that gets the data for `coupon_info` ready to use (already JSON encoded), and the corresponding `set_short_info` method. 
3. When the discounts for an order are recalculated because a coupon is added or removed, **and** a coupon that had been previously applied to the order no longer exists, the `coupon_info` entry of the corresponding discount line item will be used if available; otherwise the old `coupon_data` will be used (one of the two should always exist for a discount line item).
4. The following items are added to the discount line items entries (`coupon_lines` item) in the data returned by the order details REST API endpoint (`/wp-json/wc/v3/orders/<order id>`): `discount_type` (string), `nominal_amount` (float) and `free_shipping` (boolean). Previously this information had to be extracted from the item metadata.
5. A tool (in WooCommerce - Status - Tools) is added to convert existing `coupon_data` entries into simplified `coupon_info` entries in a background process.

Note that the discussion starter post incorrectly states that `coupon_data` entries are used only to be returned as part of the order detail in the REST API endpoint: actually, they are also used to recalculate discounts when the original coupon no longer exists.

Closes #36295.

#### Initial setup

First you need a WooCommerce site **without** the changes applied to this pull request (you can use the latest released WooCommerce). Once you have it:

1. Create a couple of coupons, one of type "fixed cart discount" and another of type "percent discount".
2. Create a bunch of orders. You can use [smooth generator](https://github.com/woocommerce/wc-smooth-generator) for that.
3. Apply both coupons to all orders. You can run the following code from `wp shell` for that (adjust query limit and coupon codes accordingly):

```php
$orders=wc_get_orders(['limit'=>1000]);
foreach($orders as $order) {$order->apply_coupon('coupon1'); $order->apply_coupon('coupon2'); $order->save();}
```

Verify that you actually have 2000 coupon meta entries:

```
wp db query "select count(*) from wp_woocommerce_order_itemmeta where meta_key='coupon_data'"
```

And **now** is when you upgrade to a WooCommerce version that has this pull request applied.

#### (Re)applying coupons

Create a new order and apply the two coupons, verify that two `coupon_info` entries have been created but there's no trace of `coupon_data`:

```
wp db query "select * from wp_woocommerce_order_itemmeta where meta_key like 'coupon_%' and order_item_id in (select order_item_id from wp_woocommerce_order_items where order_id=<order id>)"
```

Now open one of the old orders, remove the coupons and add them again. The query above will show two `coupon_info` entries this time too, and the query before that (the `select count(*)` one) this time will yield a value of 1998 (the old `coupon_data` entries were deleted when the coupons were removed).

Now delete one of the coupons, go back to the order, remove _the other_ coupon (not the one you just deleted) and add it again. Verify that discounts are recalculated properly, including the one for the deleted coupon.

#### REST API additions

Perform an order details REST API query (`/wp-json/wc/v3/orders/<order id>` endpoint) for both the new order (having `coupon_info` entries) and one of the old ones (still having `coupon_data` entries) and verify that in both cases the items listed in `coupon_lines` have three new keys: `discount_type`, `nominal_amount` and `free_shipping`.

#### Metadata conversion tool

Go to WooCommerce - Status - Tools and locate the _"Start converting order coupon data to the simplified format"_ entry at the bottom. Click the "Start converting" button. (If you have created a big enough number of orders -batch step size is 1000- you'll be able to see how upon page reload the button text has changed to "Stop converting", clicking it will do what it says).

Once the process finishes verify that no `coupon_data` entries exist, all have been converted to `coupon_info`:

```
wp db query "select count(*) from wp_woocommerce_order_itemmeta where meta_key='coupon_data'"
wp db query "select count(*) from wp_woocommerce_order_itemmeta where meta_key='coupon_info'"
```

Additionally, the "Start converting" button of the tool now appears grayed out.

You can repeat the "reapply the non-deleted coupon" step in any of the old orders to verify that order discounts are still recalculated properly.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce/includes/class-wc-coupon.php [hunk 1]
```diff
@@ -1097,4 +1097,49 @@ public static function get_generic_coupon_error( $err_code ) {
...
+	 * 1: Code
+	 * 2: Type, null is equivalent to 'fixed_cart'
+	 * 3: Amount
+	 * 4: The coupon grants free shipping? (present only if true)
+	 *
+	 * @return string A JSON string with information that allows the coupon to be reapplied to an existing order.
+	 */
+	public function get_short_info(): string {
+		$type = $this->get_discount_type();
+		$info = array(
```
Comment (vedanshujain) [inline plugins/woocommerce/includes/class-wc-coupon.php:1118]: Should this be key value? Are you using array instead of hash for performance? If so then note that this won't be extendible for 3pd to add their own data. maybe we can add an optional field for 3pd data that is present only if something is added to it (which can probably be done in a separate PR if needed).

Also note that we don't need to store the code or discount amount, code is already stored in the `order_item_name` column of `wp_woocommerce_order_items` table, and discount amount is being stored as a separate meta key. This only leaves `id` and `type`, perhaps we can store them as separate meta too?

File: plugins/woocommerce/includes/rest-api/Controllers/Version2/class-wc-rest-orders-v2-controller.php [hunk 2]
```diff
@@ -289,6 +289,25 @@ function( $meta ) use ( $product, $order_item_name ) {
 			);
 		}
 
+		// Add additional applied coupon information.
+		if ( $item instanceof WC_Order_Item_Coupon ) {
+			$temp_coupon         = new WC_Coupon();
```
Comment (vedanshujain) [inline plugins/woocommerce/includes/rest-api/Controllers/Version2/class-wc-rest-orders-v2-controller.php]: Do we need to instantiate a coupon object here? I think we can just set the `data` keys using the `coupon_info ` or  `coupon_data` directly.

File: plugins/woocommerce/src/Admin/API/Reports/Coupons/DataStore.php [hunk 3]
```diff
@@ -64,8 +64,10 @@ protected function assign_report_columns() {
 
 	/**
 	 * Set up all the hooks for maintaining and populating table data.
+	 *
+	 * @internal
 	 */
-	public static function init() {
+	final public static function init() {
```
Comment (vedanshujain) [inline plugins/woocommerce/src/Admin/API/Reports/Coupons/DataStore.php]: Is this needed? could be a backward incompatible change.

**Review by vedanshujain — COMMENTED** [review]
Overall it looks good to me, I have left couple of question, but important one is probably just storing the coupon_info array vs storing `type` and `shipping` as separate keys.

File: plugins/woocommerce/includes/class-wc-coupon.php (hunk 1 above)
Comment (Konamiman) [reply plugins/woocommerce/includes/class-wc-coupon.php:1118]: > Are you using array instead of hash for performance?

More than performance I did that to minimize the database space used.

> If so then note that this won't be extendible for 3pd to add their own data

And that's fine I think, this data is intended for internal usage and not for external code usage or extension (and that's why I added the extra fields in the REST API endpoint, so that clients can simply forget about this meta thing). 3pd willing to add custom data should do so using a separate meta entry.

>  and discount amount is being stored as a separate meta key

What gets stored is the _actual amount_ discounted from the line, but not the _nominal amount_ of the coupon; both will be different if the coupon is of type "percent".

> Also note that we don't need to store the code or discount amount

Storing the code here is indeed redundant, but I think it's important for `coupon_info` to be "self-contained", especially as it's a replacement for `coupon_data` which contained the same information. It's a redundancy that we can afford in order to reduce confussion and increase robustness.

File: plugins/woocommerce/includes/rest-api/Controllers/Version2/class-wc-rest-orders-v2-controller.php (hunk 2 above)
Comment (Konamiman) [reply plugins/woocommerce/includes/rest-api/Controllers/Version2/class-wc-rest-orders-v2-controller.php]: Using an actual coupon object allows the info encoding and deconding logic to be constrained to a single place (the coupon class), which is good for code readability and robustness.

File: plugins/woocommerce/src/Admin/API/Reports/Coupons/DataStore.php (hunk 3 above)
Comment (Konamiman) [reply plugins/woocommerce/src/Admin/API/Reports/Coupons/DataStore.php]: All the `init` methods in classes in `src` need to be final, it's a requirement enforced by the linter (we introduced that requirement together with the dependency injection container).

Comment (vedanshujain) [reply plugins/woocommerce/src/Admin/API/Reports/Coupons/DataStore.php]: I see, but if we have already released it then it would be backward incompatible if someone is overwriting this class.

File: plugins/woocommerce/includes/class-wc-coupon.php (hunk 1 above)
Comment (vedanshujain) [reply plugins/woocommerce/includes/class-wc-coupon.php:1118]: That makes sense, can you please add this info as a comment, specifically that 3PD should add their data in a different field and that the store info is external.

> What gets stored is the actual amount discounted from the line, but not the nominal amount of the coupon; both will be different if the coupon is of type "percent".

I see, 👍 . Can you share an example of this difference, maybe we need to add some more documentation around it to clarify this difference?

**Comment by Konamiman** [comment]
> Can you share an example of this difference, maybe we need to add some more documentation around it to clarify this difference?

For a 20% coupon applied to a 500$ order, the discount amount in the order is 100 ($), but the nominal amount of the coupon is 20 (%).

File: plugins/woocommerce/src/Admin/API/Reports/Coupons/DataStore.php (hunk 3 above)
Comment (Konamiman) [reply plugins/woocommerce/src/Admin/API/Reports/Coupons/DataStore.php]: Ok, I have removed it and added a linter exception.

File: plugins/woocommerce/includes/class-wc-coupon.php (hunk 1 above)
Comment (Konamiman) [reply plugins/woocommerce/includes/class-wc-coupon.php:1118]: Ok, I have extended the comment of `get_short_info`. Anyway I was planning to publish an announcement post in the developer blog once this is released.

File: plugins/woocommerce/includes/class-wc-coupon.php [hunk 4]
```diff
@@ -1097,4 +1097,50 @@ public static function get_generic_coupon_error( $err_code ) {
...
+	 * Get the coupon information that is needed to reapply the coupon to an existing order.
+	 * This information is intended to be stored as a meta value in the order line item corresponding to the coupon
+	 * and should NOT be modified or extended (additional/custom data should go in a separate metadata entry).
+	 *
+	 * The information returned is a JSON-encoded string of an array with the following coupon information:
+	 *
+	 * 0: Id
+	 * 1: Code
+	 * 2: Type, null is equivalent to 'fixed_cart'
+	 * 3: Amount
```
Comment (vedanshujain) [inline plugins/woocommerce/includes/class-wc-coupon.php]: Let's clarify that this amount could be percent when coupon type is percent

**Review by vedanshujain — APPROVED** [review]
Left another optional comment, but tested out and looks good. I agree with you that this definitely need a developer note.

I ran the CI tests and seems to be passing now! Approving

**Comment by pankaj-nikam** [comment]
Hi @Konamiman while I welcome the new format, I would like to see some backward compatibilty since it was a breaking change for existing APIs which depeneded on the old functionality. It broke our production workflow and it would be nice if such breaking changes are versioned so that the old calls do not break.
Thank you.
