### PR TITLE
Avoid duplicate templates appearing on the Site Editor when the WooCommerce template and the theme template have been customized by the user

### LINKED ISSUE #42220: BlockTemplatesController: Duplicate templates in the template list
## Describe the bug

When a theme has its version of Woo templates, and the user edits the template and saves it, in the templates list will be visible two versions of the same template:
- one from Woo
- one from the theme

## To reproduce

1. Install a block theme that it has its version of the Single Product Template (like Tsubaki)
2. Edit the Single Product Template.
3. Ensure that the name is Single Product.
4. Apply a change to the template.
5. Save it.
6. Open the templates list.
7. Single Product template is duplicated.

## Expected behavior

In the templates list view, there should be no duplicates.

## Screenshots

image

image

### PR DESCRIPTION
**Pull request by Aljullu**
### Changes proposed in this Pull Request:

Fixes https://github.com/woocommerce/woocommerce/issues/42220.

Blocks https://github.com/woocommerce/woocommerce/pull/43794.

As mentioned in #42220, if the user modified a WooCommerce templates twice, once using the WooCommerce template as the base and the other time using the theme templates as the base, we ended up with duplicate templates on the list.

This PR fixes that and adds some tests to verify we don't introduce regressions in the future.

### How to test the changes in this Pull Request:

1. Activate a theme without WooCommerce templates (ie: Twenty Twenty Four).
2. Make a modification to a WooCommerce template. Ie: add a "Hello world" paragraph somewhere in the Single Product template.
3. Now, switch your theme to a theme with WooCommerce templates (ie: Tsubaki).
4. Make a modification to the same template from step 2. You will probably need to access it via the URL. Ie: `/wp-admin/site-editor.php?postId=theme-tsubaki%2F%2Fsingle-product&postType=wp_template&canvas=edit`. Note: the `theme-tsubaki` part of the URL might change depending on the ZIP file name that you uploaded. In case of doubt, go to Appearance > Editor > Templates > Template Catalog and look at the URL.
5. Load the templates list: `/wp-admin/site-editor.php?path=%2Fwp_template%2Fall`.
6. Verify there is only one template named "Single Product".

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message

Avoid duplicate templates appearing on the Site Editor when the WooCommerce template and the theme template have been customized by the user

#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce-blocks/tests/e2e/tests/templates/constants.ts [hunk 1]
```diff
@@ -0,0 +1,100 @@
...
+	templateName: string;
+	templatePath: string;
+	templateType: string;
+	defaultTemplate?: {
+		templateName: string;
+		templatePath: string;
+	};
+};
+
+export const CUSTOMIZABLE_WC_TEMPLATES: TemplateCustomizationTest[] = [
```
Comment (Aljullu) [inline plugins/woocommerce-blocks/tests/e2e/tests/templates/constants.ts:27]: While this constant is currently only used in one file (`template-customization.block_theme.side_effects.spec.ts`), my plan is to update `template-user-customization.block_theme_with_templates.spec.ts` and `template-user-customization.block_theme.spec.ts` to use it as well.

File: plugins/woocommerce/src/Blocks/Utils/BlockTemplateUtils.php [hunk 2]
```diff
@@ -690,6 +690,45 @@ function( $template ) use ( $customised_template_slugs ) {
...
+	 * @return array Filtered list of templates with only relevant templates available.
+	 */
+	public static function remove_duplicate_customized_templates( $templates, $theme_slug ) {
+		$filtered_templates = array_filter(
+			$templates,
+			function( $template ) use ( $templates, $theme_slug ) {
+				if ( $template->theme === $theme_slug ) {
+					// This is a customized template based on the theme template, so it should be returned.
+					return true;
+				} elseif ( self::PLUGIN_SLUG !== $template->theme && self::DEPRECATED_PLUGIN_SLUG !== $template->theme ) {
```
Comment (dinhtungdu) [inline plugins/woocommerce/src/Blocks/Utils/BlockTemplateUtils.php]: Do we need this? In `get_block_templates_from_db`, we only get the templates with theme set to Woo and the current theme, so I'm afraid this will be never executed 🤔

**Review by dinhtungdu — APPROVED** [review]
I can confirm issue is fixed following the testing instruction in my tests. The code also looks good to me. I left a minor but non blocking comment. Approving 🚢

File: plugins/woocommerce/src/Blocks/Utils/BlockTemplateUtils.php (hunk 2 above)
Comment (Aljullu) [reply plugins/woocommerce/src/Blocks/Utils/BlockTemplateUtils.php]: Yeah, good point. I wanted to be extra-cautious, but as you say, it doesn't make a lot of sense if that condition will never evaluate to true... :sweat_smile: I just removed it in 18d70ce7cbabb35d2429038a29d52ecba30de421.
