### PR TITLE
Conditionally load WooCommerce Brands CSS on a need basis

### LINKED ISSUE #61051: Brands CSS is loaded on any page
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Today I noticed on a client website that a "brands.css" file by WooCommerce is loaded.
The client is a brand self and never used that feature by other plugins or WooCommerce core. 

I also check other production website by other clients that don't use the feature. Finding the not needed CSS file.
After that I checked local development systems that don't use the brands feature. This also load the css file.

### Expected behavior

Any CSS should only be loaded if it's needed. Better to be attached to blocks or have conditions to load only if needed.

### Actual behavior

"brands-styles" CSS is enqueued to any page

### Steps to reproduce

1. Open a website with active WooCommerce
2. Check network tab in browser development tools
3. filter loaded resources for brands.css

### WordPress Environment

<details><summary>System Status Report</summary>

```
### WordPress Environment ###

WordPress address (URL): [Redacted]
Site address (URL): [Redacted]
WC Version: 10.1.2
Legacy REST API Package Version: Auf dieser Website ist das alte REST-API-Plugin nicht installiert.
Action Scheduler Version: ✔ 3.9.3
Log Directory Writable: ✔
WP Version: 6.8.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: de_DE
External object cache: –

### Server Environment ###

Server Info: nginx/1.26.1
Server Architecture: Darwin 24.6.0 x86_64
PHP Version: 8.2.29
PHP Post Max Size: 1.000 MB
PHP Time Limit: 1200
PHP Max Input Vars: 4000
cURL Version: 8.7.1
(SecureTransport) LibreSSL/3.3.6

SUHOSIN Installed: –
MySQL Version: 8.0.35
Max Upload Size: 300 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

[REDACTED]

### Post Type Counts ###

attachment: 1
page: 17
post: 11001
product: 3
revision: 2
shop_order_placehold: 112000
wp_global_styles: 1
wp_navigation: 1

### Security ###

Secure connection (HTTPS): ❌
					Dein Shop benutzt kein HTTPS. Erfahre mehr über HTTPS und SSL-Zertifikate.
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: von Automattic – 10.1.2

### Inactive Plugins (0) ###


### Settings ###

Legacy API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –
Enabled Features: analytics
marketplace
order_attribution
site_visibility_badge
remote_logging
blueprint
point_of_sale
custom_order_tables


### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 Tage
Level threshold: –
Log directory size: 974 B

### WC Pages ###

Shop-Basis: #6 - /shop/
Warenkorb: #7 - /cart/ -  Enthält den woocommerce/cart-Block
Kasse: #8 - /checkout/ -  Enthält den woocommerce/checkout-Block
Mein Konto: #9 - /my-account/ -  Enthält den [woocommerce_my_account]-Shortcode
Allgemeine Geschäftsbedingungen: ❌ Seite nicht festgelegt

### Theme ###

Name: Twenty Twenty-Four
Version: 1.3
Author URL: https://de.wordpress.org
Child Theme: ❌ – Wenn du WooCommerce mit einem Theme
das du nicht selbst entwickelt hast
an eigene Bedürfnisse anpasst
dann empfehlen wir die Verwendung eines Child-Themes. Siehe Wie du ein Child-Theme erstellst (engl.)

Theme type: Block-Theme
WooCommerce Support: ❌ Nicht deklariert

### Templates ###

Overrides: /Users/ralfwiechers/Sites/CrossMediaCloud/hpos/app/public/wp-content/plugins/woocommerce/templates/block-notices/error.php
/Users/ralfwiechers/Sites/CrossMediaCloud/hpos/app/public/wp-content/plugins/woocommerce/templates/block-notices/notice.php
/Users/ralfwiechers/Sites/CrossMediaCloud/hpos/app/public/wp-content/plugins/woocommerce/templates/block-notices/success.php


### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
onboarding
onboarding-tasks
pattern-toolkit-full-composability
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
printful
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page
launch-your-store
add-to-cart-with-options-stepper-layout

Disabled Features: product-data-views
experimental-blocks
experimental-iapi-mini-cart
experimental-iapi-runtime
coming-soon-newsletter-template
minified-js
product-pre-publish-modal
settings
async-product-editor-category-field
product-editor-template-system
use-wp-horizon
experimental-wc-rest-api

Daily Cron: ✔ Next scheduled: 2025-09-23 06:36:40 +02:00
Options: ✔
Notes: 74
Onboarding: skipped

### Action Scheduler ###

Abgeschlossen: 225.044
Oldest: 2024-07-09 18:01:41 +0200
Newest: 2025-09-22 12:47:31 +0200

Ausstehend: 11
Oldest: 2025-09-22 13:44:08 +0200
Newest: 2025-10-07 12:47:31 +0200


### Status report information ###

Generated at: 2025-09-22 12:54:38 +02:00
```
</details>

### Isolating the problem

- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by sunyatasattva**
### Changes proposed in this Pull Request:

WooCommerce Brands CSS should only load when actually needed:

- When we are on a taxonomy archive for Brands.
- When a brand-related shortcode is present.
- When a brand widget is present.
- When we are in a single product page of a product with a brand (I'm not 100% sure we _need_ this, since I think everything is covered by the other conditions. However, being not too familiar with Brands, I decided to err on the side of caution for this).

Also included a filter to allow 3PDs to modify the condition for loading the CSS.

Closes #61051.

#### 1. Brands CSS shouldn't load unnecessarily

1. Go to your homepage, the product catalogue, a single product without a brand or any page.
2. Verify that `brands.css` is not loaded.

#### 2. Brands CSS should load whenever a brand shortcode is present

1. Test [these shortcodes](https://woocommerce.com/document/managing-product-taxonomies/product-brands/#shortcode-reference) on any page.
2. Make sure they work as expected and that `brands.css` is loaded.

#### 3. Brands CSS should load whenever a brand widget is present

1. Test [these widgets](https://woocommerce.com/document/managing-product-taxonomies/product-brands/#widgets).
2. Make sure they work as expected and that `brands.css` is loaded.

#### 3. Brands CSS should load when on a single product page with a brand assigned.

1. Assign a brand to any product.
2. Go to that product page.
3. Verify that `brands.css` is loaded.

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [x] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [x] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

WooCommerce will only load the `brand.css` file when strictly needed.

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce/includes/class-wc-brands.php [hunk 1]
```diff
@@ -237,10 +237,70 @@ public function add_body_class( $classes ) {
...
+			return true;
+		}
+
+		// Should load on single product pages that have brands assigned.
+		if ( is_singular( 'product' ) && $post ) {
+			$terms = get_the_terms( $post->ID, 'product_brand' );
+			if ( ! empty( $terms ) && ! is_wp_error( $terms ) ) {
+				return true;
+			}
+		}
```
Comment (tyxla) [inline plugins/woocommerce/includes/class-wc-brands.php]: Can we simplify a bit if we use `has_term()`?

```suggestion
		if ( is_singular( 'product' ) && has_term( '', 'product_brand' ) ) {
			return true;
		}
```

File: plugins/woocommerce/includes/class-wc-brands.php [hunk 2]
```diff
@@ -237,10 +237,70 @@ public function add_body_class( $classes ) {
...
+
+		// Check if any brand shortcodes are present in the content.
+		if ( $post && isset( $post->post_content ) ) {
```
Comment (tyxla) [inline plugins/woocommerce/includes/class-wc-brands.php]: Is there a chance `$post->post_content` won't be set if `$post` is set?

**Review by tyxla — COMMENTED** [review]
Thanks for working on it @sunyatasattva 🙌

File: plugins/woocommerce/includes/class-wc-brands.php [hunk 3]
```diff
@@ -237,10 +237,70 @@ public function add_body_class( $classes ) {
...
+
+			foreach ( $brand_shortcodes as $shortcode ) {
+				if ( has_shortcode( $post->post_content, $shortcode ) ) {
+					return true;
+				}
+			}
+		}
+
+		// Check if any brand widgets are active.
+		if ( is_active_widget( false, false, 'woocommerce_brand_description' ) ||
```
Comment (kmanijak) [inline plugins/woocommerce/includes/class-wc-brands.php]: It's called `wc_brands_brand_description` as per this:

https://github.com/woocommerce/woocommerce/blob/d821a5778e54633a614a25bdeab164e827e70b56/plugins/woocommerce/includes/widgets/class-wc-widget-brand-description.php#L51

```suggestion
		if ( is_active_widget( false, false, 'wc_brands_brand_description' ) ||
```

File: plugins/woocommerce/includes/class-wc-brands.php [hunk 4]
```diff
@@ -237,10 +237,70 @@ public function add_body_class( $classes ) {
...
+			is_active_widget( false, false, 'woocommerce_brand_nav' ) ||
+			is_active_widget( false, false, 'woocommerce_brand_thumbnails' ) ) {
```
Comment (kmanijak) [inline plugins/woocommerce/includes/class-wc-brands.php]: It's called `wc_brands_brand_thumbnails` as per this:

https://github.com/woocommerce/woocommerce/blob/d821a5778e54633a614a25bdeab164e827e70b56/plugins/woocommerce/includes/widgets/class-wc-widget-brand-thumbnails.php#L51

```suggestion
			is_active_widget( false, false, 'wc_brands_brand_thumbnails' ) ) {
```

**Review by kmanijak — CHANGES_REQUESTED** [review]
Nice improvement!

Tested taxonomy template, shortcode presence, single product with brand assigned (not sure as well if CSS is needed in that case 🤷 ) and all good! CSS file is loaded in those cases and not in others.

I also checked widgets and as mentioned in inline comments, two widget IDs are incorrect. Once updated, it's good to ship!

File: plugins/woocommerce/includes/class-wc-brands.php (hunk 1 above)
Comment (sunyatasattva) [reply plugins/woocommerce/includes/class-wc-brands.php]: Woops, much better 😅  I think I defaulted to the pattern I saw elsewhere in the file, but that's used for different reasons.

File: plugins/woocommerce/includes/class-wc-brands.php (hunk 2 above)
Comment (sunyatasattva) [reply plugins/woocommerce/includes/class-wc-brands.php]: Mm, technically, it _could_ be, I guess—but very unlikely at this stage of enqueuing script… But perhaps this should be `! empty( $post->post_content )`, which is a much more likely the case, what do you think?

**Review by kmanijak — APPROVED** [review]
Thanks for updates! LGTM now!

I noticed funny thing, that adding widget in classic theme's footer (e.g. Storefront) makes `is_active_widget` return `true` in block theme even though widget is not technically rendered.

Overall that doesn't seem right but in context of this change, given the CSS here is just 1kb I wouldn't worry about it much.

**Review by tyxla — APPROVED** [review]
This is testing well and looking good from my perspective. Thanks @sunyatasattva 🙌
