### PR TITLE
Make "Proceed to Checkout" button non-sticky when zoom level is bigger than 100%

### LINKED ISSUE #43637: Accessibility: When zoomed to 400% the Proceed to Checkout button is sticky on the bottom of the cart page and blocks the content
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Low-vision users frequently zoom in on websites to be able to use them. The cart page currently has code which makes the "Proceed to Checkout" button sticky in some situations. See:
https://github.com/woocommerce/woocommerce/blob/758df4854d7b627fc26eb5c0860dc492dea6a06e/plugins/woocommerce-blocks/assets/js/blocks/cart/inner-blocks/proceed-to-checkout-block/block.tsx#L113

and
https://github.com/woocommerce/woocommerce/blob/758df4854d7b627fc26eb5c0860dc492dea6a06e/plugins/woocommerce-blocks/assets/js/blocks/cart/inner-blocks/proceed-to-checkout-block/style.scss#L24

When zooming the browser in to 400%, this blocks a significant portion of the screen (almost 30%), making it difficult for low-vision users to read the content.
Screenshot of sticky element

### Expected behavior

When zooming the website there should be no sticky elements or elements blocking user's ability to read the content.

### Actual behavior

See above.

### Steps to reproduce

1. Open a browser window on a website using Twenty Twenty-Four and zoom your bowser to 250% or greater.
2. Add a product to the cart and visit the cart page.

### WordPress Environment

N/A

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by nielslange**
### Changes proposed in this Pull Request:

When the screen width is smaller than 782px, the `Proceed to Checkout` button becomes sticky. When a user is zooming into the screen, the `Proceed to Checkout` button could overlap the product items. This PR prevents that the `Proceed to Checkout` button becomes sticky when the screen height is smaller than 500px, to ensure that the products items remain visible even with a high zoom factor.

Closes #43637.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Add a product to the cart.
2. Zoom into the page to decrease the screen height.
3. Verify that the `Proceed to order` button is sticky when the screen height is bigger than 500px, and the screen width is smaller than 782px.
4. Verify that the `Proceed to order` button is no longer sticky when the screen height is 500px or less, and the screen width is smaller than 782px.

### Screenshots

<table>
<tr>
<td valign="top">
Zoom: 100% / Width: 600px / Height: 1000px
<br><br>
Screenshot 2024-06-20 at 15 17 16
</td>
<td valign="top">
Zoom: 200% / Width: 300px / Height: 500px
<br><br>
Screenshot 2024-06-20 at 15 18 24
</td>
</tr>
</table>

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce-blocks/assets/js/blocks/cart/inner-blocks/proceed-to-checkout-block/block.tsx [hunk 1]
```diff
@@ -103,15 +103,18 @@ const Block = ( {
...
 	return (
 		<div className={ clsx( 'wc-block-cart__submit', className ) }>
 			{ positionReferenceElement }
 			{ /* The non-sticky container must always be visible because it gives height to its parent, which is required to calculate when it becomes visible in the viewport. */ }
 			<div className="wc-block-cart__submit-container">
 				{ submitContainerContents }
 			</div>
-			{ /* If the positionReferenceElement is below the viewport, display the sticky container. */ }
-			{ positionRelativeToViewport === 'below' && (
+			{ /* If the positionReferenceElement is below the viewport and if the the zoom level is <= 100%, display the sticky container. */ }
```
Comment (tarunvijwani) [inline plugins/woocommerce-blocks/assets/js/blocks/cart/inner-blocks/proceed-to-checkout-block/block.tsx]: Since we're just adding a new class and style based on the conditions, I think we can simplify this code by using conditional classes with clsx.

Example: 

```js

	const zoomLevel = ( window.outerWidth / window.innerWidth ) * 100;
	const isStickyContainer =
		positionRelativeToViewport === 'below' && zoomLevel <= 100;

	const submitContainerClass = clsx( 'wc-block-cart__submit-container', {
		'wc-block-cart__submit-container--sticky': isStickyContainer,
	} );

	return (
		<div className={ clsx( 'wc-block-cart__submit', className ) }>
			{ positionReferenceElement }
			<div
				className={ submitContainerClass }
				style={ isStickyContainer ? { backgroundColor } : undefined }
			>
				{ submitContainerContents }
			</div>
		</div>
	);

```

**Review by tarunvijwani — COMMENTED** [review]
Thank you for working on this, Niels! The code looks good, but I'm unable to test the PR. The zoom level value remains at 100 all the time for me, even when I tried on a mobile device. Am I missing anything?

Testing site: https://prime-flute-raccoon.jurassic.ninja/


https://github.com/woocommerce/woocommerce/assets/11503784/dbd98d28-5115-4852-bc56-a3e22aceb88d

File: plugins/woocommerce-blocks/assets/js/blocks/cart/inner-blocks/proceed-to-checkout-block/block.tsx (hunk 1 above)
Comment (nielslange) [reply plugins/woocommerce-blocks/assets/js/blocks/cart/inner-blocks/proceed-to-checkout-block/block.tsx]: Thanks for your suggestion, @tarunvijwani. As I've opted for a different approach, based on our discussion in p1718875553124459-slack-C8X6Q7XQU, I'd prefer to leave the logic as it is for now to prevent accidentally introducing a regression.

**Comment by nielslange** [comment]
Thanks for your review, @tarunvijwani. Based on our discussion in p1718875553124459-slack-C8X6Q7XQU, I've updated this PR. I would appreciate it if you could review the PR again.

File: plugins/woocommerce-blocks/assets/js/blocks/cart/inner-blocks/proceed-to-checkout-block/style.scss [hunk 2]
```diff
@@ -44,3 +38,15 @@
...
 	}
 }
+
+@include breakpoint(">=782px") {
+	.wc-block-cart .wc-block-cart__submit-container--sticky {
+		display: none;
+	}
+}
+
+@media screen and (max-height: 500px) {
```
Comment (tarunvijwani) [inline plugins/woocommerce-blocks/assets/js/blocks/cart/inner-blocks/proceed-to-checkout-block/style.scss:48]: I think we should have min-height here. As it is now removing the sticky container for for mobile screens as well.

**Review by tarunvijwani — CHANGES_REQUESTED** [review]
Thank you for changing the approach. The changes are still not working for me. I also see a glitch, sticky container class gets added and removed at certain scroll height rapidly. 

https://github.com/woocommerce/woocommerce/assets/11503784/3f161150-152e-4bca-bcab-6eb64d8cf099

**Comment by nielslange** [comment]
> Thank you for changing the approach. The changes are still not working for me. I also see a glitch, sticky container class gets added and removed at certain scroll height rapidly.

Good catch, @tarunvijwani. Apparently, this issue was already existing before my PR, but went unnoticed until now. I just addressed it. Feel free to review the PR again.

File: plugins/woocommerce-blocks/assets/js/blocks/cart/inner-blocks/proceed-to-checkout-block/style.scss (hunk 2 above)
Comment (nielslange) [reply plugins/woocommerce-blocks/assets/js/blocks/cart/inner-blocks/proceed-to-checkout-block/style.scss:48]: It's expected that the sticky button will disappear on mobile screens when the screen height is smaller than 500px, to ensure that the sticky button does not overlap the product line items. How would you use `min-height` in this case? This part is not clear to me.

Comment (tarunvijwani) [reply plugins/woocommerce-blocks/assets/js/blocks/cart/inner-blocks/proceed-to-checkout-block/style.scss:48]: Please ignore my comment. I thought it was related to the screen orientation and maximum height, so I tested it on a mobile device as well.

File: plugins/woocommerce-blocks/assets/js/blocks/cart/inner-blocks/proceed-to-checkout-block/block.tsx [hunk 3]
```diff
@@ -106,18 +106,18 @@ const Block = ( {
...
-			{ positionRelativeToViewport === 'below' && (
+			{ /* Choose which container to display based on the position of the reference element */ }
+			{ positionRelativeToViewport === 'below' ? (
 				<div
 					className="wc-block-cart__submit-container wc-block-cart__submit-container--sticky"
 					style={ { backgroundColor } }
 				>
 					{ submitContainerContents }
 				</div>
+			) : (
```
Comment (tarunvijwani) [inline plugins/woocommerce-blocks/assets/js/blocks/cart/inner-blocks/proceed-to-checkout-block/block.tsx]: >Thanks for your suggestion, @tarunvijwani. As I've opted for a different approach, based on our discussion in p1718875553124459-slack-C8X6Q7XQU, I'd prefer to leave the logic as it is for now to prevent accidentally introducing a regression.

I still feel that using clsx we can make the code look simpler and easier to read. However, this is not a blocker, so I will approve the PR. 

```js
	// Determine if the container should be sticky based on the position relative to the viewport.
	const displayStickyContainer = positionRelativeToViewport === 'below';

	const submitContainerClass = clsx( 'wc-block-cart__submit-container', {
		'wc-block-cart__submit-container--sticky': displayStickyContainer,
	} );

	return (
		<div className={ clsx( 'wc-block-cart__submit', className ) }>
			{ positionReferenceElement }
			<div
				className={ submitContainerClass }
				style={ displayStickyContainer ? { backgroundColor }: {} }
			>
				{ submitContainerContents }
			</div>
		</div>
	);
	
```

**Review by tarunvijwani — APPROVED** [review]
Thank you for the update @nielslange. It works great now.

File: plugins/woocommerce-blocks/assets/js/blocks/cart/inner-blocks/proceed-to-checkout-block/block.tsx (hunk 3 above)
Comment (nielslange) [reply plugins/woocommerce-blocks/assets/js/blocks/cart/inner-blocks/proceed-to-checkout-block/block.tsx]: I've applied your suggestion to increase the readability, @tarunvijwani. Thanks for suggesting this. 🙌
