### PR TITLE
Product Filters: add support for databases using ANSI_QUOTES 

### LINKED ISSUE #61629: Fatal Error: Improper escaping of string value causes it to be interpreted as a column name for custom attributes in the Product Filter block.
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When using the Product Filters block on a product archive page, if you use a custom product attribute, the SQL query to obtain the count of products associated with that term fails. This causes the custom attribute filters to not generate on the frontend (as if they were "missing") and silently fail. A PHP error is logged when this happens (the example below uses the Color attribute on product as an example):

```
[25-Oct-2025 14:20:19 UTC] WordPress database error Unknown column 'pa_color' in 'where clause' for query 
			SELECT COUNT( DISTINCT posts.ID ) as term_count, terms.term_id as term_count_id
			FROM wp_posts AS posts
			INNER JOIN wp_term_relationships AS term_relationships ON posts.ID = term_relationships.object_id
			INNER JOIN wp_term_taxonomy AS term_taxonomy USING( term_taxonomy_id )
			INNER JOIN wp_terms AS terms USING( term_id )
			WHERE posts.ID IN ( REDACTED )
			AND term_taxonomy.taxonomy IN ("pa_color")
			GROUP BY terms.term_id
		 made by require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), include('wp-includes/template-canvas.php'), get_the_block_template_html, do_blocks, render_block, WP_Block->render, WP_Block->render, Automattic\WooCommerce\Blocks\BlockTemplatesController->render_woocommerce_template_part, render_block_core_template_part, do_blocks, render_block, WP_Block->render, WP_Block->render, WP_Block->render, WP_Block->render, Automattic\WooCommerce\Blocks\BlockTypes\AbstractBlock->render_callback, Automattic\WooCommerce\Blocks\BlockTypes\ProductFilters->render, array_reduce, Automattic\WooCommerce\Blocks\BlockTypes\ProductFilters->Automattic\WooCommerce\Blocks\BlockTypes\{closure}, WP_Block->render, Automattic\WooCommerce\Blocks\BlockTypes\AbstractBlock->render_callback, Automattic\WooCommerce\Blocks\BlockTypes\ProductFilterAttribute->render, Automattic\WooCommerce\Blocks\BlockTypes\ProductFilterAttribute->get_attribute_counts, Automattic\WooCommerce\Internal\ProductFilters\FilterData->get_attribute_counts
```

This failure is due to the way the taxonomy is wrapped with double quotes instead of single quotes in the SQL query. The error is caused because the double quotes makes the string value of the slug for the attribute appear to be a column, instead of a string value. The errors are found inside the `get_attribute_counts()` method under the following files:

1. `woocommerce\src\Blocks\QueryFilters.php`
2. `woocommerce\src\Internal\ProductFilters\FilterData.php`

### Expected behavior

Product Filter blocks should have custom attribute filters appear on load of a product archive page/template.

Image

### Actual behavior

If the Product Filter uses a custom attribute, it does not appear on the frontend as if it were "missing".

Image

### Steps to reproduce

1. Use a full site editing template like Variations.
2. Add the Product Filter block to the default shop page's template.
3. Add a product attribute as a filter. It does not matter the configuration, just needs to be a product attribute.
4. Ensure there are products assigned to the product attribute you selected and that the products are in stock.
5. Save the changes.
6. Load the ship page on the frontend, and you will see the products but you will not see the filters.

### WordPress Environment

<details>

<summary>WordPress Environment</summary>

WordPress address (URL): REDACTED
Site address (URL): REDACTED
WC Version: 10.3.3
Legacy REST API Package Version: The Legacy REST API plugin is not installed on this site.
Action Scheduler Version: ✔ 3.9.3
Log Directory Writable: ✔
WP Version: 6.8.3
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: –
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.65 (Debian)
Server Architecture: Linux 6.1.0-37-amd64 x86_64
PHP Version: 8.2.28
PHP Post Max Size: 50 MB
PHP Time Limit: 60
PHP Max Input Vars: 2500
cURL Version: 7.88.1
OpenSSL/3.0.17

SUHOSIN Installed: –
MySQL Version: 8.0.35
Max Upload Size: 50 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 10.3.3
WC Database Prefix: wp_
Total Database Size: 109.70MB
Database Data Size: 72.61MB
Database Index Size: 37.09MB
wp_woocommerce_sessions: Data: 0.14MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.08MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 1.52MB + Index: 0.45MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 1.38MB + Index: 1.00MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.38MB + Index: 0.27MB + Engine InnoDB
wp_cartflows_ca_cart_abandonment: Data: 0.22MB + Index: 0.02MB + Engine InnoDB
wp_cartflows_ca_email_history: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_cartflows_ca_email_templates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cartflows_ca_email_templates_meta: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.20MB + Index: 0.16MB + Engine InnoDB
wp_gf_draft_submissions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_gf_entry: Data: 0.11MB + Index: 0.03MB + Engine InnoDB
wp_gf_entry_meta: Data: 0.28MB + Index: 0.41MB + Engine InnoDB
wp_gf_entry_notes: Data: 0.09MB + Index: 0.03MB + Engine InnoDB
wp_gf_form: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gf_form_meta: Data: 0.09MB + Index: 0.00MB + Engine InnoDB
wp_gf_form_revisions: Data: 0.14MB + Index: 0.03MB + Engine InnoDB
wp_gf_form_view: Data: 0.08MB + Index: 0.03MB + Engine InnoDB
wp_gf_rest_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_imagify_files: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_imagify_folders: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_newsletter: Data: 0.09MB + Index: 0.03MB + Engine InnoDB
wp_newsletter_automated: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_newsletter_automated_logs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_newsletter_emails: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
wp_newsletter_logs: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_newsletter_sent: Data: 0.11MB + Index: 0.09MB + Engine InnoDB
wp_newsletter_stats: Data: 0.14MB + Index: 0.09MB + Engine InnoDB
wp_newsletter_user_logs: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_newsletter_user_meta: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 8.05MB + Index: 1.63MB + Engine InnoDB
wp_postmeta: Data: 6.52MB + Index: 4.03MB + Engine InnoDB
wp_posts: Data: 17.52MB + Index: 0.66MB + Engine InnoDB
wp_redirection_404: Data: 0.34MB + Index: 0.14MB + Engine InnoDB
wp_redirection_groups: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_redirection_items: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_redirection_logs: Data: 0.06MB + Index: 0.05MB + Engine InnoDB
wp_snippets: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.22MB + Index: 0.16MB + Engine InnoDB
wp_term_taxonomy: Data: 1.52MB + Index: 3.03MB + Engine InnoDB
wp_termmeta: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 1.52MB + Index: 3.03MB + Engine InnoDB
wp_usermeta: Data: 1.52MB + Index: 1.94MB + Engine InnoDB
wp_users: Data: 0.09MB + Index: 0.05MB + Engine InnoDB
wp_vxcf_mailchimp: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_vxcf_mailchimp_accounts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_vxcf_mailchimp_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_addresses: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_operational_data: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.06MB + Index: 0.08MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_orders: Data: 0.08MB + Index: 0.11MB + Engine InnoDB
wp_wc_orders_meta: Data: 1.52MB + Index: 1.92MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.13MB + Index: 0.14MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.08MB + Index: 0.11MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wcpdf_invoice_number: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcpdf_packing_slip_number: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wcs_payment_retries: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wdr_order_discounts: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wdr_order_item_discounts: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wdr_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpf_filters: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpf_meta_keys: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wpf_meta_values: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wpf_meta_values_bk: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wpmailsmtp_debug_events: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpmailsmtp_email_tracking_events: Data: 0.34MB + Index: 0.38MB + Engine InnoDB
wp_wpmailsmtp_email_tracking_links: Data: 6.52MB + Index: 0.45MB + Engine InnoDB
wp_wpmailsmtp_emails_log: Data: 5.52MB + Index: 1.23MB + Engine InnoDB
wp_wpmailsmtp_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpr_above_the_fold: Data: 0.39MB + Index: 0.06MB + Engine InnoDB
wp_wpr_lazy_render_content: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
wp_wpr_performance_monitoring: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wpr_preconnect_external_domains: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
wp_wpr_preload_fonts: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wpr_rocket_cache: Data: 0.08MB + Index: 0.11MB + Engine InnoDB
wp_wpr_rucss_used_css: Data: 0.14MB + Index: 0.17MB + Engine InnoDB
wp_yoast_indexable: Data: 4.52MB + Index: 10.09MB + Engine InnoDB
wp_yoast_indexable_hierarchy: Data: 1.52MB + Index: 0.92MB + Engine InnoDB
wp_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_primary_term: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_yoast_seo_links: Data: 0.08MB + Index: 0.03MB + Engine InnoDB

### Post Type Counts ###

acf-field: 15
acf-field-group: 3
acf-post-type: 1
attachment: 924
fs_cm_ruleset: 2
mc4wp-form: 1
page: 16
post: 14
product: 358
product_variation: 46
revision: 1255
shop_coupon: 508
shop_order: 120
shop_order_placehold: 21
shop_order_refund: 7
wp_block: 4
wp_font_face: 2
wp_font_family: 1
wp_global_styles: 2
wp_navigation: 4
wp_template: 28
wp_template_part: 9
wpcode: 22

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (33) ###

Advanced Custom Fields PRO: by WP Engine – 6.6.1
Akismet Anti-spam: Spam Protection: by Automattic - Anti-spam Team – 5.5
Block Visibility: by Nick Diego – 3.7.1
Breeze: by Cloudways – 2.2.20
Cloudflare: by Cloudflare Inc. – 4.12.8
Custom Taxonomy Order: by Marcel Pol – 4.0.2
Shipping Live Rates and Access Points for UPS for WooCommerce PRO: by Octolize – 3.7.1
Shipping Live Rates for USPS for WooCommerce PRO: by Octolize – 3.3.1
Gift Up: by Gift Up – 3.1.4
Gravity Forms: by Gravity Forms – 2.9.20
Imagify: by Imagify Image Optimizer – Optimize Images & Convert WebP & Avif – 2.2.6
WPCode Lite: by WPCode – 2.3.0
Newsletter - Addons Manager and Support: by The Newsletter Team – 1.3.9
Newsletter - Import/Export: by The Newsletter Team – 1.5.9
Newsletter - Reports and Retargeting: by The Newsletter Team – 4.7.0
Newsletter - WooCommerce: by The Newsletter Team – 2.0.0
Newsletter: by Stefano Lissa & The Newsletter Team – 9.0.5
Payment Plugins for PayPal WooCommerce: by Payment Plugins support@paymentplugins.com – 1.1.14
Redirection: by John Godley – 5.5.2
Simple Page Ordering: by 10up – 2.7.4
CTX Feed: by WebAppick – 6.6.0
WooCommerce Wishlist: Multiple Wishlists per Customer: by WPFactory – 3.2.8
Auto Coupons for WooCommerce: by RLDD – 3.0.42
Cart Abandonment Recovery for WooCommerce: by Brainstorm Force – 2.0.2
Discount Rules for WooCommerce: by Flycart – 2.6.13
Pixel Manager for WooCommerce: by SweetCode – 1.49.2
PDF Invoices & Packing Slips for WooCommerce: by WP Overnight – 4.8.0
WooCommerce: by Automattic – 10.3.3
Yoast SEO: by Team Yoast – 26.2
WP Mail SMTP Pro: by WP Mail SMTP – 4.6.0
WP Rocket: by WP Media – 3.20.0.2

### Inactive Plugins (3) ###

Newsletter - Automated Newsletters: by The Newsletter Team – 4.8.6
WordPress Importer: by wordpressdotorg – 0.9.4

### Dropin Plugins () ###

advanced-cache.php: advanced-cache.php

### Settings ###

Legacy API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)
Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –
Enabled Features: analytics
marketplace
order_attribution
site_visibility_badge
blueprint
point_of_sale
custom_order_tables
cost_of_goods_sold

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 184 KB

### WC Pages ###

Shop base: #5 - /store
Cart: #6 - /cart -  Contains the woocommerce/classic-shortcode block
Checkout: #7 - /checkout -  Contains the woocommerce/classic-shortcode block
My account: #8 - /account -  This page's content is overridden by custom template content
Terms and conditions: #9 - /terms-conditions

### Theme ###

Name: Variations
Version: 4.4.0
Author URL: 
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
Theme type: Block theme
WooCommerce Support: ❌ Not declared

### Templates ###

Overrides: 
variations/parts/mini-cart.html
variations/templates/archive-product.html
variations/templates/order-confirmation.html
variations/templates/page-cart.html
variations/templates/page-checkout.html
variations/templates/single-product.html

Outdated Templates: ❌
					
					
						Learn how to update					 |
					
						
					
					
						Clear system status theme info cache

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
onboarding
onboarding-tasks
pattern-toolkit-full-composability
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page
launch-your-store

Disabled Features: product-data-views
experimental-blocks
experimental-iapi-mini-cart
experimental-iapi-runtime
coming-soon-newsletter-template
minified-js
product-pre-publish-modal
settings
async-product-editor-category-field
product-editor-template-system
use-wp-horizon
rest-api-v4

Daily Cron: ✔ Next scheduled: 2025-10-25 15:57:18 -04:00
Options: ✔
Notes: 55
Onboarding: skipped

### Action Scheduler ###

Complete: 2,317
Oldest: 2025-09-24 12:47:23 -0400
Newest: 2025-10-25 11:00:58 -0400

Failed: 117
Oldest: 2024-02-16 18:06:51 -0500
Newest: 2025-10-20 14:30:05 -0400

In-progress: 1
Oldest: –
Newest: –

Pending: 58
Oldest: 2025-10-25 11:00:12 -0400
Newest: 2025-11-22 07:54:28 -0500

### Status report information ###

Generated at: 2025-10-25 11:00:59 -04:00

</details>

### Isolating the problem

- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by praggmatica**
### Submission Review Guidelines:

- [X] -   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
- [X] -   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
- [X] -   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
- [X] -   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

When using the Product Filters block on a product archive page, if you use a custom product attribute, the SQL query to obtain the count of products associated with that term fails. This causes the custom attribute filters to not appear and silently fail. A PHP error is logged when this happens (the example below uses the Color attribute on product as an example):

```
[25-Oct-2025 14:20:19 UTC] WordPress database error Unknown column 'pa_color' in 'where clause' for query 
			SELECT COUNT( DISTINCT posts.ID ) as term_count, terms.term_id as term_count_id
			FROM wp_posts AS posts
			INNER JOIN wp_term_relationships AS term_relationships ON posts.ID = term_relationships.object_id
			INNER JOIN wp_term_taxonomy AS term_taxonomy USING( term_taxonomy_id )
			INNER JOIN wp_terms AS terms USING( term_id )
			WHERE posts.ID IN ( REDACTED )
			AND term_taxonomy.taxonomy IN ("pa_color")
			GROUP BY terms.term_id
		 made by require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), include('wp-includes/template-canvas.php'), get_the_block_template_html, do_blocks, render_block, WP_Block->render, WP_Block->render, Automattic\WooCommerce\Blocks\BlockTemplatesController->render_woocommerce_template_part, render_block_core_template_part, do_blocks, render_block, WP_Block->render, WP_Block->render, WP_Block->render, WP_Block->render, Automattic\WooCommerce\Blocks\BlockTypes\AbstractBlock->render_callback, Automattic\WooCommerce\Blocks\BlockTypes\ProductFilters->render, array_reduce, Automattic\WooCommerce\Blocks\BlockTypes\ProductFilters->Automattic\WooCommerce\Blocks\BlockTypes\{closure}, WP_Block->render, Automattic\WooCommerce\Blocks\BlockTypes\AbstractBlock->render_callback, Automattic\WooCommerce\Blocks\BlockTypes\ProductFilterAttribute->render, Automattic\WooCommerce\Blocks\BlockTypes\ProductFilterAttribute->get_attribute_counts, Automattic\WooCommerce\Internal\ProductFilters\FilterData->get_attribute_counts
```

This failure is due to the way the taxonomy is wrapped with double quotes instead of single quotes in the SQL query. The error is caused because the double quotes makes the string value of the slug for the attribute appear to be a column, instead of a string value. The errors are found inside the `get_attribute_counts()` method under the following files:

1. `woocommerce\src\Blocks\QueryFilters.php`
2. `woocommerce\src\Internal\ProductFilters\FilterData.php`

Closes #61629 

(For Bug Fixes) Bug introduced in version 10.3.0.

### How to test the changes in this Pull Request:

1. Use a full site editing template like Variations.
2. Add the Product Filter block to the default shop page's template.
3. Add a product attribute as a filter. It does not matter the configuration, just needs to be a product attribute.
4. Ensure there are products assigned to the product attribute you selected and that the products are in stock.
5. Save the changes.
6. Load the ship page on the frontend, and you will should now see the product filters for custom attributes appear.

### Testing that has already taken place:

1. Added multiple types of filters to the Product Filter block, and all other filters still appear.

### Changelog entry

-   [X] Automatically create a changelog entry from the details below.

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [X] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [X] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

Product Filters: add support for databases using ANSI_QUOTES

</details>

### CODE REVIEW

File: plugins/woocommerce/src/Blocks/QueryFilters.php
Comment (dinhtungdu) [inline plugins/woocommerce/src/Blocks/QueryFilters.php:1]: We willl deprecate this class soon, so you don't need to update this file. It's not used anywhere currently.

File: plugins/woocommerce/src/Internal/ProductFilters/FilterData.php [hunk 1]
```diff
@@ -266,17 +266,17 @@ public function get_attribute_counts( array $query_vars, string $attribute_to_co
...
+            $attribute_count_sql     = "
+                SELECT COUNT( DISTINCT posts.ID ) as term_count, terms.term_id as term_count_id
+                FROM {$wpdb->posts} AS posts
+                INNER JOIN {$wpdb->term_relationships} AS term_relationships ON posts.ID = term_relationships.object_id
+                INNER JOIN {$wpdb->term_taxonomy} AS term_taxonomy USING( term_taxonomy_id )
+                INNER JOIN {$wpdb->terms} AS terms USING( term_id )
+                WHERE posts.ID IN ( {$product_ids} )
+                AND term_taxonomy.taxonomy = '{$taxonomy_escaped}'
+                GROUP BY terms.term_id
+            ";
```
Comment (dinhtungdu) [inline plugins/woocommerce/src/Internal/ProductFilters/FilterData.php]: Can you please fix the linting error for this block? You can run the following command to check:

`pnpm --filter="@woocommerce/plugin-woocommerce" lint:changes:branch`

**Review by dinhtungdu — CHANGES_REQUESTED** [review]
Thanks for the PR! I can confirm this PR fixes the connected issue. Can you please fix the lint error so we can merge this PR?

File: plugins/woocommerce/src/Blocks/QueryFilters.php
Comment (praggmatica) [reply plugins/woocommerce/src/Blocks/QueryFilters.php:1]: No problem!

File: plugins/woocommerce/src/Internal/ProductFilters/FilterData.php (hunk 1 above)
Comment (praggmatica) [reply plugins/woocommerce/src/Internal/ProductFilters/FilterData.php]: This has been fixed!

File: plugins/woocommerce/src/Internal/ProductFilters/FilterData.php [hunk 2]
```diff
@@ -266,17 +266,17 @@ public function get_attribute_counts( array $query_vars, string $attribute_to_co
...
+			$attribute_count_sql = "
+				SELECT COUNT( DISTINCT posts.ID ) as term_count, terms.term_id as term_count_id
+				FROM {$wpdb->posts} AS posts
+				INNER JOIN {$wpdb->term_relationships} AS term_relationships ON posts.ID = term_relationships.object_id
+				INNER JOIN {$wpdb->term_taxonomy} AS term_taxonomy USING( term_taxonomy_id )
+				INNER JOIN {$wpdb->terms} AS terms USING( term_id )
+				WHERE posts.ID IN ( {$product_ids} )
+				AND term_taxonomy.taxonomy = '{$taxonomy_escaped}'
+				GROUP BY terms.term_id
+			";
```
[the remark this answers is not in the document]
Comment (praggmatica) [reply plugins/woocommerce/src/Internal/ProductFilters/FilterData.php:279]: @dinhtungdu making sure I am to ignore this "error", as you mentioned earlier to that the file mentioned is to be deprecated. Thanks.

**Review by dinhtungdu — APPROVED** [review]
Thanks for the update! This is LGTM now. 

Note that I updated the title and changelog to better reflect the actual change, and hope you don't mind.

**Comment by dinhtungdu** [comment]
@praggmatica I will make sure to get this PR merged today.
