### PR TITLE
Cast string to float when calculating refund totals within `WC_Order::get_total_refunded_for_item()`

### LINKED ISSUE #52180: Fatal error `unsupported operand types` in `WC_Order` `get_total_refunded_for_item`
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

In PHP 8.2+ we see fatal errors where `$refunded_item->get_total()` returns a string [here](https://github.com/woocommerce/woocommerce/blob/3c076b5187e615d95ac387a97578481b210fcf0d/plugins/woocommerce/includes/class-wc-order.php#L2213).

### Expected behavior

Since `get_total` in all cases (shipping, fees and product) appear tagged to return a string, defensive code is required.

### Actual behavior

An error is thrown

```
Error Details
=============
An error of type E_ERROR was caused in line 2213 of the file /nas/content/live/[redacted]/wp-content/plugins/woocommerce/includes/class-wc-order.php. Error message: Uncaught TypeError: Unsupported operand types: int + string in /nas/content/live/[redacted]/wp-content/plugins/woocommerce/includes/class-wc-order.php:2213
Stack trace:
0-zd-a8c /nas/content/live/[redacted]/wp-content/plugins/woocommerce/includes/admin/meta-boxes/views/html-order-shipping.php(67): WC_Order->get_total_refunded_for_item(127011, 'shipping')
```

### Steps to reproduce

We could not reproduce this error. However, the code path and stack dump are consistent, showing an integer and string getting added on a PHP 8.2.23 site environment.

8545438-zd-a8c

### WordPress Environment

`
### WordPress Environment ###

WC Version: 9.3.3
Legacy REST API Package Version: The Legacy REST API plugin is not installed on this site.
Action Scheduler Version: ✔ 3.7.4
Log Directory Writable: ✔
WP Version: ❌ 6.5.5 - There is a newer version of WordPress available (6.6.1)
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: –
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 8.2.23
PHP Post Max Size: 100 MB
PHP Time Limit: 3600
PHP Max Input Vars: 10000
cURL Version: 7.81.0
OpenSSL/3.0.2

SUHOSIN Installed: –
MySQL Version: 8.0.36-28
Max Upload Size: 50 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 9.1.4
WC Database Prefix: wp_
Total Database Size: 752.54MB
Database Data Size: 414.42MB
Database Index Size: 338.12MB
wp_woocommerce_sessions: Data: 2.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 6.52MB + Index: 2.52MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 102.64MB + Index: 63.16MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.16MB + Index: 0.08MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 1.52MB + Index: 0.73MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
sib_model_contact: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_actionscheduler_actions: Data: 2.06MB + Index: 1.14MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.06MB + Index: 0.05MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 1.02MB + Index: 1.27MB + Engine InnoDB
wp_afwc_campaigns: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_afwc_commission_plans: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_afwc_hits: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
wp_afwc_payout_orders: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_afwc_payouts: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_afwc_referrals: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_cky_banners: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_cky_cookie_categories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_cky_cookies: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_commentmeta: Data: 1.52MB + Index: 1.98MB + Engine InnoDB
wp_comments: Data: 16.55MB + Index: 12.09MB + Engine InnoDB
wp_counter_box: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_duplicator_pro_entities: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_duplicator_pro_packages: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_ee_product_sync_call: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ee_product_sync_data: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_ee_product_sync_profile: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ee_products_sync_list: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ee_prouct_pre_sync_data: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gla_budget_recommendations: Data: 0.22MB + Index: 0.14MB + Engine InnoDB
wp_gla_merchant_issues: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gla_shipping_rates: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gla_shipping_times: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_gpf_feeds: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_hustle_entries: Data: 2.52MB + Index: 3.03MB + Engine InnoDB
wp_hustle_entries_meta: Data: 29.56MB + Index: 20.58MB + Engine InnoDB
wp_hustle_modules: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_hustle_modules_meta: Data: 1.52MB + Index: 0.03MB + Engine InnoDB
wp_hustle_tracking: Data: 35.58MB + Index: 58.69MB + Engine InnoDB
wp_imagify_files: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_imagify_folders: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailchimp_carts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailchimp_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_custom_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_dynamic_segment_filters: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_feature_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_forms: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_log: Data: 0.09MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_newsletter_links: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_newsletter_option: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_option_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_posts: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_segment: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_templates: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_newsletters: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_scheduled_task_subscribers: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_scheduled_tasks: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_segments: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_sending_queues: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_settings: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_statistics_bounces: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_statistics_clicks: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_statistics_forms: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_statistics_newsletters: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_statistics_opens: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_mailpoet_statistics_unsubscribes: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_statistics_woocommerce_purchases: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_mailpoet_stats_notifications: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_subscriber_custom_field: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_subscriber_ips: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_subscriber_segment: Data: 4.52MB + Index: 4.03MB + Engine InnoDB
wp_mailpoet_subscriber_tag: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_subscribers: Data: 9.52MB + Index: 17.13MB + Engine InnoDB
wp_mailpoet_tags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_user_agents: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_user_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mc4wp_log: Data: 0.41MB + Index: 0.00MB + Engine InnoDB
wp_nf3_action_meta: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_nf3_actions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nf3_chunks: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nf3_field_meta: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_nf3_fields: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nf3_form_meta: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_nf3_forms: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nf3_object_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nf3_objects: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nf3_relationships: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nf3_upgrades: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 8.50MB + Index: 1.61MB + Engine InnoDB
wp_pmxi_files: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_hash: Data: 0.09MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_history: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_images: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_imports: Data: 0.11MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_posts: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_templates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_postmeta: Data: 101.64MB + Index: 74.23MB + Engine InnoDB
wp_posts: Data: 9.52MB + Index: 8.06MB + Engine InnoDB
wp_relevanssi: Data: 2.52MB + Index: 4.55MB + Engine InnoDB
wp_relevanssi_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_relevanssi_stopwords: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_smush_dir_images: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_term_relationships: Data: 1.52MB + Index: 0.38MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.08MB + Index: 0.06MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_tm_taskmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_tm_tasks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_usermeta: Data: 33.56MB + Index: 36.14MB + Engine InnoDB
wp_users: Data: 2.52MB + Index: 2.52MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 1.52MB + Index: 0.73MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_gpf_render_cache: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_od_time_framemeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_od_time_frames: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_bundle_lookup: Data: 3.52MB + Index: 8.08MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.20MB + Index: 0.31MB + Engine InnoDB
wp_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 6.52MB + Index: 8.06MB + Engine InnoDB
wp_wc_order_stats: Data: 1.52MB + Index: 0.89MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.05MB + Index: 0.11MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wcs_payment_retries: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wcsc_error_logs: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wcsc_logs: Data: 0.09MB + Index: 0.14MB + Engine InnoDB
wp_woocommerce_bundled_itemmeta: Data: 1.52MB + Index: 1.89MB + Engine InnoDB
wp_woocommerce_bundled_items: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_exported_csv_items: Data: 1.52MB + Index: 0.30MB + Engine InnoDB
wp_woocommerce_gpf_google_taxonomy: Data: 1.52MB + Index: 0.13MB + Engine InnoDB
wp_woomotiv_custom_popups: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woomotiv_stats: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpfm_backup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpmailsmtp_debug_events: Data: 3.52MB + Index: 0.00MB + Engine InnoDB
wp_wpmailsmtp_email_tracking_events: Data: 0.11MB + Index: 0.11MB + Engine InnoDB
wp_wpmailsmtp_email_tracking_links: Data: 0.09MB + Index: 0.02MB + Engine InnoDB
wp_wpmailsmtp_emails_log: Data: 1.52MB + Index: 0.14MB + Engine InnoDB
wp_wpmailsmtp_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpml_mails: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
wp_wt_iew_action_history: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
wp_wt_iew_cron: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wt_iew_ftp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wt_iew_mapping_template: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wt_sc_coupon_lookup: Data: 1.52MB + Index: 0.53MB + Engine InnoDB
wp_yoast_indexable: Data: 0.20MB + Index: 0.13MB + Engine InnoDB
wp_yoast_indexable_hierarchy: Data: 0.05MB + Index: 0.05MB + Engine InnoDB
wp_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_primary_term: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_yoast_seo_links: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_yoast_seo_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

acf-field: 321
acf-field-group: 26
attachment: 668
aw_workflow: 31
custom_css: 1
gtw_custom_fields: 3
gtw_rules: 5
mailpoet_page: 1
nav_menu_item: 36
nf_sub: 14244
oembed_cache: 14
page: 31
post: 27
product: 139
product_variation: 7
recipe: 112
revision: 12
shop_coupon: 11638
shop_order: 8948
shop_order_refund: 739
shop_subscription: 575
wc_membership_plan: 2
wc_user_membership: 74
wp_font_face: 33
wp_font_family: 12
wp_global_styles: 1
wphb_minify_group: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (35) ###

ACF Content Analysis for Yoast SEO: by Thomas Kräftner
ViktorFroberg
marol87
pekz0r
angrycreative
Team Yoast – 3.1

Advanced Custom Fields PRO: by WP Engine – 6.3.4
WP Engine Smart Plugin Manager: by WP Engine – 5.18.0
Custom Post Type UI: by WebDevStudios – 1.17.1
GTM4WP - A Google Tag Manager (GTM) plugin for WordPress: by Thomas Geiger – 1.20.2
Facebook for WooCommerce: by Facebook – 3.2.6
Gift Wrapper for WooCommerce: by Flintop – 5.7.0
Hustle Pro: by WPMU DEV – 7.8.4
Imagify: by Imagify – Optimize Images & Convert WebP & Avif – 2.2.2
MC4WP: Mailchimp for WordPress: by ibericode – 4.9.14
MC4WP: Mailchimp for WordPress Premium: by ibericode – 4.10.3
Ninja Forms - Mailchimp: by Saturday Drive – 3.3.6
Ninja Forms: by Saturday Drive – 3.8.8
Product Sales Count for WooCommerce: by Flintop – 1.9.0
Payment Plugins for PayPal WooCommerce: by Payment Plugins
support@paymentplugins.com – 1.0.50

Relevanssi: by Mikko Saari – 4.22.2
Simple Banner: by Ryan Petersen – 2.17.3
String Locator: by InstaWP – 2.6.5
UK Address Postcode Validation: by Ideal Postcodes – 3.5.7
CTX Feed: by WebAppick – 6.5.8
Payment Plugins for Stripe WooCommerce: by Payment Plugins
support@paymentplugins.com – 3.3.74

WooCommerce.com Update Manager: by Automattic – 1.0.3
WooCommerce Customer/Order/Coupon Export: by SkyVerge – 5.5.1
WooCommerce Memberships: by SkyVerge – 1.26.7
Order Delivery for WooCommerce: by Kestrel – 2.6.4
WooCommerce Print Invoices/Packing Lists: by SkyVerge – 3.13.5
Woo Product Bundles: by Woo – 7.2.1
WooCommerce Subscriptions: by WooCommerce – 6.5.0
WooCommerce: by Automattic – 9.1.4
Voodoo SMS – Notify Customers & Admin by Text Message: by VoodooSMS – 2.0.2
Yoast SEO: by Team Yoast – 23.1
WP Mail SMTP Pro: by WP Mail SMTP – 4.1.0
WP Rollback: by WP Rollback – 2.0.7
WPMU DEV Dashboard: by WPMU DEV – 4.11.26
Request Form for Zendesk: by pipdig – 3.0.4

### Inactive Plugins (4) ###

Product Import Export for WooCommerce: by WebToffee – 2.4.5
Subscriptions Add-On for WooCommerce: by Codup – 1.2.11.0
WooCommerce Database Cleanup: by  –
YITH WooCommerce Waiting List Premium: by YITH – 1.24.1

### Dropin Plugins () ###

advanced-cache.php: advanced-cache.php

### Must Use Plugins (5) ###

Force Strong Passwords - WPE Edition: by Jason Cosper – 1.8.0
WP Engine Cache Plugin: by WP Engine – 1.3.1
WP Engine Seamless Login Plugin: by WP Engine – 1.6.1
WP Engine Security Auditor: by wpengine – 1.1.1
WP Engine System: by WP Engine – 5.0.1

### Settings ###

API Enabled: –
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: bundle (bundle)
external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 89 MB

### WC Pages ###

Shop base: #551 - /shop/
Cart: #552 - /basket/ -  Contains the [woocommerce_cart] shortcode
Checkout: #553 - /checkout/ -  Contains the [woocommerce_checkout] shortcode
My account: #554 - /my-account/
Terms and conditions: #298 - /terms-conditions/

### Theme ###

Name: Frogspark
Version: 1
Author URL: 
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: frogspark/woocommerce/archive-product.php
frogspark/woocommerce/auth/footer.php
frogspark/woocommerce/auth/form-grant-access.php
frogspark/woocommerce/auth/form-login.php
frogspark/woocommerce/auth/header.php
frogspark/woocommerce/cart/cart-empty.php
frogspark/woocommerce/cart/cart-item-data.php
frogspark/woocommerce/cart/cart-shipping.php
frogspark/woocommerce/cart/cart-totals.php
frogspark/woocommerce/cart/cart.php
frogspark/woocommerce/cart/cross-sells.php
frogspark/woocommerce/cart/mini-cart.php
frogspark/woocommerce/cart/proceed-to-checkout-button.php
frogspark/woocommerce/cart/shipping-calculator.php
frogspark/woocommerce/checkout/cart-errors.php
frogspark/woocommerce/checkout/form-billing.php
frogspark/woocommerce/checkout/form-checkout.php
frogspark/woocommerce/checkout/form-coupon.php
frogspark/woocommerce/checkout/form-login.php
frogspark/woocommerce/checkout/form-pay.php
frogspark/woocommerce/checkout/form-shipping.php
frogspark/woocommerce/checkout/order-receipt.php
frogspark/woocommerce/checkout/payment-method.php
frogspark/woocommerce/checkout/payment.php
frogspark/woocommerce/checkout/review-order.php
frogspark/woocommerce/checkout/terms.php
frogspark/woocommerce/checkout/thankyou.php
frogspark/woocommerce/content-product-cat.php
frogspark/woocommerce/content-product.php
frogspark/woocommerce/content-single-product.php
frogspark/woocommerce/content-widget-price-filter.php
frogspark/woocommerce/content-widget-product.php
frogspark/woocommerce/content-widget-reviews.php
frogspark/woocommerce/emails/admin-cancelled-order.php
frogspark/woocommerce/emails/admin-failed-order.php
frogspark/woocommerce/emails/admin-new-order.php
frogspark/woocommerce/emails/customer-completed-order.php
frogspark/woocommerce/emails/customer-invoice.php
frogspark/woocommerce/emails/customer-new-account.php
frogspark/woocommerce/emails/customer-note.php
frogspark/woocommerce/emails/customer-on-hold-order.php
frogspark/woocommerce/emails/customer-processing-order.php
frogspark/woocommerce/emails/customer-refunded-order.php
frogspark/woocommerce/emails/customer-reset-password.php
frogspark/woocommerce/emails/email-addresses.php
frogspark/woocommerce/emails/email-customer-details.php
frogspark/woocommerce/emails/email-downloads.php
frogspark/woocommerce/emails/email-footer.php
frogspark/woocommerce/emails/email-header.php
frogspark/woocommerce/emails/email-order-details.php
frogspark/woocommerce/emails/email-order-items.php
frogspark/woocommerce/emails/email-styles.php
frogspark/woocommerce/emails/plain/admin-cancelled-order.php
frogspark/woocommerce/emails/plain/admin-failed-order.php
frogspark/woocommerce/emails/plain/admin-new-order.php
frogspark/woocommerce/emails/plain/customer-completed-order.php
frogspark/woocommerce/emails/plain/customer-invoice.php
frogspark/woocommerce/emails/plain/customer-new-account.php
frogspark/woocommerce/emails/plain/customer-note.php
frogspark/woocommerce/emails/plain/customer-on-hold-order.php
frogspark/woocommerce/emails/plain/customer-processing-order.php
frogspark/woocommerce/emails/plain/customer-refunded-order.php
frogspark/woocommerce/emails/plain/customer-reset-password.php
frogspark/woocommerce/emails/plain/email-addresses.php
frogspark/woocommerce/emails/plain/email-customer-details.php
frogspark/woocommerce/emails/plain/email-downloads.php
frogspark/woocommerce/emails/plain/email-order-details.php
frogspark/woocommerce/emails/plain/email-order-items.php
frogspark/woocommerce/global/breadcrumb.php
frogspark/woocommerce/global/form-login.php
frogspark/woocommerce/global/quantity-input.php
frogspark/woocommerce/global/sidebar.php
frogspark/woocommerce/global/wrapper-end.php
frogspark/woocommerce/global/wrapper-start.php
frogspark/woocommerce/loop/add-to-cart.php
frogspark/woocommerce/loop/loop-end.php
frogspark/woocommerce/loop/loop-start.php
frogspark/woocommerce/loop/no-products-found.php
frogspark/woocommerce/loop/orderby.php
frogspark/woocommerce/loop/pagination.php
frogspark/woocommerce/loop/price.php
frogspark/woocommerce/loop/rating.php
frogspark/woocommerce/loop/result-count.php
frogspark/woocommerce/loop/sale-flash.php
frogspark/woocommerce/myaccount/dashboard.php
frogspark/woocommerce/myaccount/downloads.php
frogspark/woocommerce/myaccount/form-add-payment-method.php
frogspark/woocommerce/myaccount/form-edit-account.php
frogspark/woocommerce/myaccount/form-edit-address.php
frogspark/woocommerce/myaccount/form-login.php
frogspark/woocommerce/myaccount/form-lost-password.php
frogspark/woocommerce/myaccount/form-reset-password.php
frogspark/woocommerce/myaccount/lost-password-confirmation.php
frogspark/woocommerce/myaccount/my-account.php
frogspark/woocommerce/myaccount/my-address.php
frogspark/woocommerce/myaccount/my-downloads.php
frogspark/woocommerce/myaccount/my-orders.php
frogspark/woocommerce/myaccount/navigation.php
frogspark/woocommerce/myaccount/orders.php
frogspark/woocommerce/myaccount/payment-methods.php
frogspark/woocommerce/myaccount/view-order.php
frogspark/woocommerce/notices/error.php
frogspark/woocommerce/notices/notice.php
frogspark/woocommerce/notices/success.php
frogspark/woocommerce/order/form-tracking.php
frogspark/woocommerce/order/order-again.php
frogspark/woocommerce/order/order-details-customer.php
frogspark/woocommerce/order/order-details-item.php
frogspark/woocommerce/order/order-details.php
frogspark/woocommerce/order/order-downloads.php
frogspark/woocommerce/order/tracking.php
frogspark/woocommerce/product-searchform.php
frogspark/woocommerce/single-product/add-to-cart/external.php
frogspark/woocommerce/single-product/add-to-cart/grouped.php
frogspark/woocommerce/single-product/add-to-cart/simple.php
frogspark/woocommerce/single-product/add-to-cart/variable.php
frogspark/woocommerce/single-product/add-to-cart/variation-add-to-cart-button.php
frogspark/woocommerce/single-product/add-to-cart/variation.php
frogspark/woocommerce/single-product/meta.php
frogspark/woocommerce/single-product/photoswipe.php
frogspark/woocommerce/single-product/price.php
frogspark/woocommerce/single-product/product-attributes.php
frogspark/woocommerce/single-product/product-image.php
frogspark/woocommerce/single-product/product-thumbnails.php
frogspark/woocommerce/single-product/rating.php
frogspark/woocommerce/single-product/related.php
frogspark/woocommerce/single-product/review-meta.php
frogspark/woocommerce/single-product/review-rating.php
frogspark/woocommerce/single-product/review.php
frogspark/woocommerce/single-product/sale-flash.php
frogspark/woocommerce/single-product/share.php
frogspark/woocommerce/single-product/short-description.php
frogspark/woocommerce/single-product/stock.php
frogspark/woocommerce/single-product/tabs/additional-information.php
frogspark/woocommerce/single-product/tabs/description.php
frogspark/woocommerce/single-product/tabs/tabs.php
frogspark/woocommerce/single-product/title.php
frogspark/woocommerce/single-product/up-sells.php
frogspark/woocommerce/single-product-reviews.php
frogspark/woocommerce/single-product.php
frogspark/woocommerce/taxonomy-product-cat.php
frogspark/woocommerce/taxonomy-product-tag.php

### Status report information ###

Generated at: 2024-07-29 14:17:40 +01:00
`

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by mikejolley**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

While I could not replicate this issue on PHP 8.2, we can be more defensive when calculating totals. We're working with floats stored as strings, so they should be typecasted back to float. This includes a round on the final total, and I've added some new tests to cover this logic.

Closes #52180

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Create a product, give it a decimal price such as `10.49` (avoid ints)
2. Add product to cart and place order.
3. View order in backend. Refund the line item.
4. Check the refunded total matches the line item total.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce/tests/php/includes/wc-order-functions-test.php [hunk 1]
```diff
@@ -184,4 +184,69 @@ public function test_wc_update_coupon_usage_counts() {
...
+		$product->save();
+
+		// Create an order with the product.
+		$order = new WC_Order();
+		$item  = new WC_Order_Item_Product();
+		$item->set_props(
+			array(
+				'product'  => $product,
+				'quantity' => 2,
+				'total'    => 199.98,
```
Comment (tjcafferkey) [inline plugins/woocommerce/tests/php/includes/wc-order-functions-test.php:204]: To satisfy my own curiosity even when we set `float` values here, `get_total()` returns these as `string` values?

Comment (mikejolley) [reply plugins/woocommerce/tests/php/includes/wc-order-functions-test.php:204]: For order items yes, they are stored and retrieved as strings.

**Review by tjcafferkey — APPROVED** [review]
