### PR TITLE
Fix meta data returns in API using JsonSerializable

### LINKED ISSUE #17047: PHP notice Trying to get property of non-object when reading product meta data
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [x] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

View shop page, single product page, or any page that reads product metadata.

You may need to have an extension that store custom metadata active (e.g, subscriptions or deposits).

## Expected/actual behavior

When I follow those steps, I see PHP notice is thrown:

```
Notice: Trying to get property of non-object in /srv/www/wordpress-default/wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-data.php on line 313
```

I was expecting to see no notice.

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

Notice is not thrown in WC 3.1.2.

https://github.com/woocommerce/woocommerce/blob/0e40d2c764f2592fcd238b28c8ee52ff380ed0ce/includes/abstracts/abstract-wc-data.php#L285

It seems `$meta_data[ current( $array_keys ) ]` is always an array instead of an object. PR is coming.

### PR DESCRIPTION
**Pull request by mikejolley**
WordPress has a JsonSerializable shim for 5.2 so this should be good to go :)

Closes #17048 
Fixes #17047

### CODE REVIEW

File: includes/class-wc-meta-data.php [hunk 1]
```diff
@@ -18,7 +18,7 @@
 /**
  * WC_Meta_Data class.
  */
-class WC_Meta_Data {
+class WC_Meta_Data implements JsonSerializable {
```
Comment (claudiosanches) [inline includes/class-wc-meta-data.php]: This is for PHP 5.4+

**Comment by Anooshmoosh** [comment]
I am still getting this notification in WordPress 4.9.8. This happens when uploading a product with image using woocommerce API in C#.  Also an out of memory issue happens.  Not sure if related.  A System.Net.WebException is thrown at httpWebRequest() after the call.

Here is the highlight in the wp-content/debug.log:
[03-Aug-2018 17:38:55 UTC] PHP Notice:  wp_woocommerce_session_5924b4b501bb13ab27aba05031382b09 cookie cannot be set - headers already sent by /home2/myname/mydomain.com/wp-content/themes/storefront/header.php on line 11 in /home2/myname/mydomain.com/wp-content/plugins/woocommerce/includes/wc-core-functions.php on line 835
[03-Aug-2018 17:38:57 UTC] PHP Notice:  wp_woocommerce_session_5924b4b501bb13ab27aba05031382b09 cookie cannot be set - headers already sent by /home2/myname/mydomain.com/wp-content/themes/storefront/header.php on line 11 in /home2/myname/mydomain.com/wp-content/plugins/woocommerce/includes/wc-core-functions.php on line 835
[03-Aug-2018 17:38:57 UTC] PHP Notice:  Undefined index: pa_width in /home2/myname/mydomain.com/wp-content/plugins/woocommerce-products-filter/views/woof.php on line 526
[03-Aug-2018 17:38:57 UTC] PHP Notice:  Undefined index: pa_width in /home2/myname/mydomain.com/wp-content/plugins/woocommerce-products-filter/views/woof.php on line 121
[03-Aug-2018 17:38:57 UTC] PHP Notice:  Undefined index: pa_width in /home2/myname/mydomain.com/wp-content/plugins/woocommerce-products-filter/views/woof.php on line 124
[03-Aug-2018 17:38:57 UTC] PHP Notice:  Undefined index: pa_width in /home2/myname/mydomain.com/wp-content/plugins/woocommerce-products-filter/views/woof.php on line 136
[03-Aug-2018 17:38:57 UTC] PHP Notice:  Undefined index: pa_width in /home2/myname/mydomain.com/wp-content/plugins/woocommerce-products-filter/views/woof.php on line 174
[03-Aug-2018 17:38:57 UTC] PHP Notice:  Undefined index: pa_width in /home2/myname/mydomain.com/wp-content/plugins/woocommerce-products-filter/views/woof.php on line 266
**[03-Aug-2018 17:38:57 UTC] PHP Notice:  Trying to get property of non-object in /home2/myname/mydomain.com/wp-content/plugins/woocommerce-products-filter/views/woof.php on line 266
[03-Aug-2018 17:38:57 UTC] PHP Notice:  Trying to get property of non-object in /home2/myname/mydomain.com/wp-content/plugins/woocommerce-products-filter/views/woof.php on line 266**
[03-Aug-2018 17:38:58 UTC] PHP Fatal error:  Out of memory (allocated 95944704) (tried to allocate 32 bytes) in /home2/myname/mydomain.com/wp-content/plugins/woocommerce/includes/wc-formatting-functions.php on line 707

**Comment by Anooshmoosh** [comment]
Deactivating WOOF eliminated the "trying to get property of non-object in... "
