### PR TITLE
[Accessibility] Add aria-current to the current link in My Account side nav

### LINKED ISSUE #43626: Accessibility: My Account nav missing aria-current page indicator
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

The navigation menu on the My Account page does not have a current page indicator for screen reader users. Links in navigation menus should use [aria-current="page"](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-current) to indicate the current page.

You need to add this attribute to the currently viewed page.

Relevant code: https://github.com/woocommerce/woocommerce/blob/758df4854d7b627fc26eb5c0860dc492dea6a06e/plugins/woocommerce/templates/myaccount/navigation.php#L25

### Expected behavior

Screen reader users will know what page is being viewed when utilizing a nav menu. 

### Actual behavior

Required aria is missing.

### Steps to reproduce

Inspect the My Account nav menu or see the code linked above.

### WordPress Environment

N/A

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by amesplant**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes #43626 .

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. When viewing the My Account page, inspect the current page link, to make sure that it has the `aria-current="page"`
2. Open chose of screen readers, navigate the 'current page link' in the navigation and make sure that the screen reader announces it.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

**Comment by amesplant** [comment]
@dkotter ready for you review

File: plugins/woocommerce/includes/wc-account-functions.php [hunk 1]
```diff
@@ -164,6 +164,33 @@ function wc_get_account_menu_item_classes( $endpoint ) {
...
 }
 
+/**
+ * Get current page in order to set the current menu item.
+ *
+ * @param string $endpoint Endpoint.
+ * @return string
+ * @since 9.2.0
+ */
+function wc_get_current_page( $endpoint ) {
```
Comment (opr) [inline plugins/woocommerce/includes/wc-account-functions.php]: I think this has the potential to be misleading, I'd recommend the following so it matches `wc_get_account_menu_item_classes` above.

```suggestion
function wc_get_account_menu_aria_current( $endpoint ) {
```

Do you agree?

**Review by opr — DISMISSED** [review]
Changes look great, just one suggestion about the function name.

File: plugins/woocommerce/includes/wc-account-functions.php (hunk 1 above)
Comment (amesplant) [reply plugins/woocommerce/includes/wc-account-functions.php]: @opr agreed and updated 😄

**Review by dkotter — APPROVED** [review]
@ankitguptaindia @qasumitbagthariya This is ready for QA

**Comment by qasumitbagthariya** [comment]
### QA Update ⚠️
-------------

@amesplant 

I have checked this PR in the `amesplant:fix/43626-account-nav-aria-current` branch but as you mention in PR description "screen readers, navigate the 'current page link' in the navigation and make sure that the screen reader announces it." it announces the URL instead current page link.

Please check the video below, let me know if I missed anything.



https://github.com/user-attachments/assets/87e985e4-fc21-4310-9609-cd843cc3dd51

**Comment by amesplant** [comment]
@qasumitbagthariya this is what this PR fixes, tabbing to the current link on the page. Hope this makes more sense.
https://github.com/user-attachments/assets/42a0d057-15f0-4087-a2b2-2ba8e058d421

**Comment by qasumitbagthariya** [comment]
### QA Update ✅ 
-------------

I have checked this PR in the `amesplant:fix/47071-navigation-landmarks` branch and changes working as expected.

- Current link on the page ✅

image

https://github.com/user-attachments/assets/1d1ebc6c-f470-4cc1-a8a6-8af7a9c3bea5


**Testing Environment** 

<Details>

- WordPress: 6.6
- Theme: Storefront 4.6.0
- WooCommerce - WooCommerce - Dev version with this fix specific branch.
- PHP: 8.0.30
- Web Server: Nginx 1.20.2
- Browser: Chrome 
- OS: macOS Ventura 13.3 
- Git Branch: amesplant:fix/43626-account-nav-aria-current

</Details>

@amesplant Please Un-draft this PR for the next step.

**Comment by amesplant** [comment]
@qasumitbagthariya removed draft and set ready for review

**Comment by vikrampm1** [comment]
@opr this PR is ready for your re-review.

File: plugins/woocommerce/includes/wc-account-functions.php [hunk 2]
```diff
@@ -164,6 +164,33 @@ function wc_get_account_menu_item_classes( $endpoint ) {
...
 }
 
+/**
+ * Get current page in order to set the current menu item.
+ *
+ * @param string $endpoint Endpoint.
+ * @return string
+ * @since 9.2.0
+ */
+function wc_get_account_menu_aria_current( $endpoint ) {
```
Comment (mikejolley) [inline plugins/woocommerce/includes/wc-account-functions.php]: The bulk of the "current" page detection code is duplicated from `wc_get_account_menu_item_classes`. Why don't we move this to a helper function? This will ensure the two never become out of sync and they behave in the same way.

i.e. (if we're sticking with functions) `wc_is_current_account_menu_item( $endpoint )` which returns boolean, then consume from both `wc_get_account_menu_aria_current` and `wc_get_account_menu_item_classes`.

File: plugins/woocommerce/includes/wc-account-functions.php [hunk 3]
```diff
@@ -164,6 +164,33 @@ function wc_get_account_menu_item_classes( $endpoint ) {
 	return implode( ' ', array_map( 'sanitize_html_class', $classes ) );
 }
 
+/**
+ * Get current page in order to set the current menu item.
+ *
+ * @param string $endpoint Endpoint.
+ * @return string
+ * @since 9.2.0
```
Comment (mikejolley) [inline plugins/woocommerce/includes/wc-account-functions.php]: Remember to update the since tags.

File: plugins/woocommerce/includes/wc-account-functions.php (hunk 2 above)
Comment (mikejolley) [reply plugins/woocommerce/includes/wc-account-functions.php]: Or use directly in the HTML:

```php
<?php echo wc_is_current_account_menu_item( $endpoint ) ? 'aria-current="page"' : '';  ?>
```

**Review by mikejolley — CHANGES_REQUESTED** [review]
Thanks for the changes.

I think we can move the shared logic to a helper function instead of repeating it. There is also a version bump on the `since` tag needed.

File: plugins/woocommerce/includes/wc-account-functions.php (hunk 3 above)
Comment (amesplant) [reply plugins/woocommerce/includes/wc-account-functions.php]: Thanks @mikejolley for the suggestion, this completely makes sense and I have updated the code to be cleaner. Front End Engineer attempting to do some basic PHP 😬

Comment (amesplant) [reply plugins/woocommerce/includes/wc-account-functions.php]: Done ✅

**Comment by vikrampm1** [comment]
@mikejolley @opr is there anything else needed on this PR before it can be merged?

**Review by mikejolley — APPROVED** [review]
Looks good now thank you.

**Comment by vikrampm1** [comment]
@mikejolley thanks! If the review is complete then this should be good to merge by you / Woo.

**Comment by mikejolley** [comment]
@vikrampm1 @amesplant I just re-ran CI and its spotted some linting errors which need attention. You can see the report here: https://github.com/woocommerce/woocommerce/actions/runs/10287576990/job/28813896826?pr=49800

**Comment by amesplant** [comment]
@mikejolley fixed the linting errors

**Comment by mikejolley** [comment]
Thanks, I believe the last CI issues are due to this being a fork. Ill merge it 👍🏻
