### PR TITLE
Fix deprecation warning when passing null to explode()

### LINKED ISSUE #58036: PHP deprecation in email Cc and Bcc
PHP Deprecated: explode(): Passing null to parameter #2 ($string) of type string is deprecated in /tmp/wordpress/wp-content/plugins/woocommerce/includes/emails/class-wc-email.php on line 604

### LINKED ISSUE #58043: [CFE]: Fix deprecation warning when passing null to explode()
### Which PR needs to be included? (please do not enter multiple PRs)

https://github.com/woocommerce/woocommerce/pull/58037

### Why do these PRs need to break the code freeze?

In some cases, there can be a deprecation warning in PHP 8.1+. It also makes some tests fail.

### What is the consequence if this exception does not get included?

It shouldn't affect the store, but it can log deprecation warnings.

### What is the plan should defects to be discovered in these PRs ahead of final release?

Reverting would be enough,

### How should this change be communicated in the release post on the public developer blog:

No need to communicate this. 

### If you’re not available and we have questions about this request, is there another person(s) and/or a team that we can ping?

Anyone from team Ballade. 

### Acknowledgement

- [x] I understand that I need to write an incident report (aka Escape Analysis) as a comment on this post. This is required for the request to be accepted.
- [x] I understand that I need to create an issue as a result of the Escape Analysis and reference it in a comment on this post. This can be done at a later time, but it is required for this request to be closed.
- [x] I understand that I will need to merge the PR to the target `release` branch for which the fix was intended, when my request is approved
- [x] I understand that I will need to merge the followup cherry-picked PR created by the github-actions bot to `trunk` when my request is approved

### Closing checklist for Solaris

- [x] Escape analysis completed
- [x] The fix is raised from intended release branch. For a fix targeting WC X.Y, the base branch should be `release/X.Y`
- [x] PR merged to target `release` branch
- [x] PR cherry-picked to `trunk` (you can find the links in PR comments to verify)
- [ ] Followup issue if any

### PR DESCRIPTION
**Pull request by NeosinneR**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

By default, the `get_option()` method returns `null` as an empty value, which is later used in `explode()`, which generates a deprecation warning since PHP 8.1. This PR changes it to an empty string. 

Closes WOOPLUG-4302, closes #58036, closes #58043.

(For Bug Fixes) Bug introduced in PR #54939.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. This is more of a code thing, not visible in the UI to test.

### CODE REVIEW

File: plugins/woocommerce/includes/emails/class-wc-email.php [hunk 1]
```diff
@@ -578,8 +577,8 @@ public function get_cc_recipient() {
 		 * @param object   $object The object (ie, product or order) this email relates to, if any.
 		 * @param WC_Email $email  WC_Email instance managing the email.
 		 */
-		$cc  = apply_filters( 'woocommerce_email_cc_recipient_' . $this->id, $cc, $this->object, $this );
-		$ccs = array_map( 'trim', explode( ',', $cc ) );
+		$cc  = apply_filters( 'woocommerce_email_cc_recipient_' . $this->id, $this->cc, $this->object, $this );
+		$ccs = array_map( 'trim', explode( ',', $cc ?? '' ) );
```
Comment (yuliyan) [inline plugins/woocommerce/includes/emails/class-wc-email.php:581]: Would it be worth applying the same approach for [get_recipient()](https://github.com/woocommerce/woocommerce/blob/d3e65e14bb6341ac69fbdd99bda7d9f69e975641/plugins/woocommerce/includes/emails/class-wc-email.php#L561)?

**Review by yuliyan — APPROVED** [review]
LGTM!

File: plugins/woocommerce/includes/emails/class-wc-email.php (hunk 1 above)
Comment (NeosinneR) [reply plugins/woocommerce/includes/emails/class-wc-email.php:581]: Thanks for the review, @yuliyan. I applied it in https://github.com/woocommerce/woocommerce/pull/58037/commits/3cd5c8440136be9bc62a7a1cff88b0a7cc5a7fcb. While the recipients should always be set to something (admin or customer email), technically the filter can change that, and there is no harm in adding the fix anyway.

Since this is CFE, I'm still waiting for https://github.com/woocommerce/woocommerce/issues/58043 to be approved before merging to the release branch.

**Review by Mayisha — APPROVED** [review]
Thank you for the fix @NeosinneR 🎉
