### PR TITLE
Do not disable empty attribute values in the attribute dropdown

### LINKED ISSUE #21383: [3.5-beta.1] issue when deleting all the terms from the Attributes tab
## Plugins & theme activated
WooCommerce 3.5.0-beta.1 
Storefront 2.3.3

## Issue description

In the product Attributes tab, if you delete all the terms from the global attribute metabox, this metabox disappears. And I'm not able to select it again in the list since the attribute is greyed. I don't reproduce this behavior with WooCommerce 3.4.5.

## Steps to reproduce

1. Create a simple product
2. Go to Attributes tab > add a global attribute here 'Color' > add a term as here:
screenshot-localhost-2018 09 18-15-38-02

3. Remove the term and save your changes: the 'Color' metabox has disappeared and 'Color" is greyed in the attributes list as shown below:
capture du 2018-09-18 15-39-43

In WooCommerce 3.4.5 the 'Color' metabox is still there after removing all the terms.

### PR DESCRIPTION
**Pull request by kloon**
### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:
When saving attributes on product and you do not enter any values the attribute is not saved, this PR adds a check to not keep the dropdown disabled when you save an attribute with no values.

Closes #21383 

### How to test the changes in this Pull Request:

1. Create a product
2. Add an attribute from the dropdown and check the attribute is disabled in the dropdown
3. Without adding any values click the save attributes button
4. Check that the attribute did not save and also that the attribute is enabled in the dropdown again.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

### Changelog entry

> Fix - Enable attribute in product attribute dropdown when saving fails with no values.

### CODE REVIEW

File: assets/js/admin/meta-boxes-product.js [hunk 1]
```diff
@@ -464,6 +464,14 @@ jQuery( function( $ ) {
 				$( '.product_attributes' ).html( response.data.html );
 				$( '.product_attributes' ).unblock();
 
+				// Make sure the dropdown is not disabled for empty value attributes.
+				var nr_elements = original_data.length / 6;
+				for ( i = 0; i < nr_elements; i++ ) {
+					if ( typeof( original_data ) != "undefined" && original_data[ i * 6 + 2 ].value === "" ) {
```
Comment (claudiosanches) [inline assets/js/admin/meta-boxes-product.js]: We don't use double quotes in our JS files, this will trigger errors on grunt, you can test first with `grunt jshint`.

**Review by claudiosanches — DISMISSED** [review]
Need some coding standard fixes.

**Comment by claudiulodro** [comment]
Works great in my testing.

**Review by claudiulodro — APPROVED** [review]
