### PR TITLE
Prevent deleting default product category via REST API

### LINKED ISSUE #21652: Prevent deleting the default product category
WooCommerce introduced `default_product_cat` from v3.3.0. Although it is not possible to delete this default category from admin panel, but one can delete it programmatically with `wp_delete_term` or with REST API endpoint `/products/categories/<default_cat_id>?force=true`. I've looked into WP core and find out that `wp_delete_term` doesn't provide any hook to prevent deleting default term except `category` taxonomy. So, instead of changing WooCommerce code in multiple places, I've submitted a ticket with patch in [WP Trac](https://core.trac.wordpress.org/ticket/45166). Please take a look into it and give your thoughts. Though, I think WC should have a fix before WP makes any changes.

**To Reproduce**
You can delete the default product category in multiple ways like:
1. Using `/products/categories/<default_cat_id>?force=true` REST API,
2. Running code like this,
`wp_delete_term( get_option( 'default_product_cat' ), 'product_cat' );`

**Expected behavior**
Default product category should not be able to delete.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
### WordPress Environment ###

Home URL: http://localhost/woocommerce
Site URL: http://localhost/woocommerce
WC Version: 3.5.0
Log Directory Writable: ✔
WP Version: 4.9.8
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.1.12 - We recommend using PHP version 7.2 or above for greater performance and security. How to update your PHP version
PHP Post Max Size: 32 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.52.1
OpenSSL/1.0.2j

SUHOSIN Installed: –
MySQL Version: 5.6.38
Max Upload Size: 32 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.5.0
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Total Database Size: 2.79MB
Database Data Size: 1.95MB
Database Index Size: 0.84MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_comments: Data: 0.02MB + Index: 0.08MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_options: Data: 1.41MB + Index: 0.02MB
wp_postmeta: Data: 0.02MB + Index: 0.03MB
wp_posts: Data: 0.02MB + Index: 0.06MB
wp_termmeta: Data: 0.02MB + Index: 0.03MB
wp_terms: Data: 0.02MB + Index: 0.03MB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wp_usermeta: Data: 0.02MB + Index: 0.03MB
wp_users: Data: 0.02MB + Index: 0.05MB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB

### Post Type Counts ###

page: 6
post: 2
product: 2

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (3) ###

Debug Bar Console: by koopersmith – 0.3
Debug Bar: by wordpressdotorg – 0.9
WooCommerce: by Automattic – 3.5.0-rc.1 – 3.5.0 is available

### Settings ###

API Enabled: –
Force SSL: –
Currency: BDT (৳ )
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #5 - /shop/
Cart: #6 - /cart/
Checkout: #7 - /checkout/
My account: #8 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Seventeen
Version: 1.7
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –
</details>

### PR DESCRIPTION
**Pull request by siananda**
Prevent deleting the default product category. Added additional checking is the category is the default category or not.

### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes #21652 .

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Prevent deleting the default product category.

### CODE REVIEW

**Review by kloon — APPROVED** [review]
LGTM, since there is no hooks in WP core we can hook in to prevent deleting it when someone calls wp_delete_term this is the only change we can make to ensure it is not deleted for now.

File: includes/abstracts/abstract-wc-rest-terms-controller.php [hunk 1]
```diff
@@ -533,6 +533,14 @@ public function delete_item( $request ) {
 		}
 
 		$term = get_term( (int) $request['id'], $taxonomy );
+		// Get default category id.
+		$default_category_id = absint( get_option( 'default_product_cat', 0 ) );
+
+		// Prevent deleting the default product category
```
Comment (kloon) [inline includes/abstracts/abstract-wc-rest-terms-controller.php]: Just update this line to contain the colon so that PHPCS passes and we are good to go.
```suggestion
		// Prevent deleting the default product category.
```

**Review by kloon — DISMISSED** [review]

File: includes/abstracts/abstract-wc-rest-terms-controller.php [hunk 2]
```diff
@@ -533,6 +533,14 @@ public function delete_item( $request ) {
 		}
 
 		$term = get_term( (int) $request['id'], $taxonomy );
+		// Get default category id.
+		$default_category_id = absint( get_option( 'default_product_cat', 0 ) );
+
+		// Prevent deleting the default product category.
+		if ( $default_category_id === $term ) {
```
Comment (claudiulodro) [inline includes/abstracts/abstract-wc-rest-terms-controller.php]: `$term` will be a term object and `$default_category_id` is an integer, so this comparison won't work. You should be able to compare `$default_category_id` with `(int) $request['id']`, though.

**Review by claudiulodro — CHANGES_REQUESTED** [review]
Good idea, just needs a slight tweak.

File: includes/abstracts/abstract-wc-rest-terms-controller.php [hunk 3]
```diff
@@ -533,6 +533,14 @@ public function delete_item( $request ) {
...
+			return new WP_Error( 'woocommerce_rest_default_product_cat_cannot_delete', __( 'Default product category cannot be deleted.', 'woocommerce' ), array( 'status' => 500 ) );
```
Comment (claudiulodro) [inline includes/abstracts/abstract-wc-rest-terms-controller.php]: Also it would be best to use the existing `woocommerce_rest_cannot_delete` error group here instead of `woocommerce_rest_default_product_cat_cannot_delete`.

**Review by claudiulodro — APPROVED** [review]
Latest version looks and works great. Thanks!
