### PR TITLE
[Experimental] Fix /wp-json/wc/store/v1/products/{productId} API to return the grouped products ids when the product type is grouped

### LINKED ISSUE #54784: Fix /wp-json/wc/store/v1/products/{productId} API to return the grouped products ids when the product type is grouped
**Description**

The Grouped Product Selector block from the Add to Cart uses the `product` from the `/wp-json/wc/store/v1/products/{productId}` endpoint to render the grouped products. The problem is that this endpoint does not returns the grouped products ids or the product children.

**ACs** 

- [x] Fix `/wp-json/wc/store/v1/products/{productId}` API to return the grouped products ids when the product type is grouped.
- [x] Change the Grouped Product Selector -> Product Item Template block to use the grouped product ids returned by the endpoint to render them in the Add to Cart block.
- [x] Make sure this works correctly for both SingleProductBlock and SingleProductTemplate

### PR DESCRIPTION
**Pull request by mdperez86**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes #54784

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Install and activate the WooCommerce Beta Tester plugin
2. Go to WooCommerce Admin Test Helper > Features and enable experimental-blocks and blockified-add-to-cart.
3. Go to Appearance > Editor > Templates > Single Product, select the Add to Cart with Options block and update it to the blockified one.
4. Select the Add to Cart block and choose the Grouped product type from the product type selector.
5. Since in this template the add to cart block sets a mock product then the grouped products listed in the form are the first 3 returned by the products endpoint.
6. Then create a new post
7. Add the single product block
8. Select a grouped product
9. Make sure the grouped products listed in the form are the right ones associated with the parent product.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

**Review by Aljullu — COMMENTED** [review]
This looks good to me. I'm a bit wary of introducing new methods into `WC_Product_Grouped`. For example, I think `get_visible_child_ids()` would be better implemented at the consumer level instead of becoming a method in the product class, but not a strong opinion. I think before merging it might be good to reach out to Proton in case they want to take a look given that this is a class that impacts several parts of WooCommerce. But overall, the approach taken in this PR looks good to me. :+1:

**Comment by mdperez86** [comment]
> This looks good to me. I'm a bit wary of introducing new methods into `WC_Product_Grouped`. For example, I think `get_visible_child_ids()` would be better implemented at the consumer level instead of becoming a method in the product class, but not a strong opinion. I think before merging it might be good to reach out to Proton in case they want to take a look given that this is a class that impacts several parts of WooCommerce. But overall, the approach taken in this PR looks good to me. 👍

I was following a similar pattern made in -> https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/includes/class-wc-product-variable.php#L245

File: plugins/woocommerce/src/StoreApi/Schemas/V1/ProductSchema.php [hunk 1]
```diff
@@ -362,6 +362,17 @@ public function get_properties() {
 					],
 				],
 			],
+			'grouped_products'    => [
```
Comment (Aljullu) [inline plugins/woocommerce/src/StoreApi/Schemas/V1/ProductSchema.php:365]: Wondering if this property should be called `children` instead of `grouped_products`. I understand that the Grouped product is the parent product and the children are the individual products contained by the grouped product, no?

**Review by Aljullu — COMMENTED** [review]
The code looks good to me. I left one minor comment about changing the property name in the endpoint, but not a big deal.

> I was following a similar pattern made in -> https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/includes/class-wc-product-variable.php#L245

I wasn't aware of that, thanks for sharing!

In that case, I agree it makes sense having `get_visible_children()` as a method in the `WC_Product_Grouped` to be aligned with `WC_Product_Variable`. I'm not sure about `get_visible_child_ids()`, though. I feel that if we add this method, somebody in the future might want a similar method to retrieve the children's names, prices, etc. so we would end up with many methods all returning the same data in a different shape. On the other hand, using `get_visible_children()` and getting the IDs from there should be quite straightforward for consumers. What do you think?

---

Btw, I noticed that the endpoint returns the products in this form `"grouped_products":{"1":66,"2":67},`, which JS considers to be an object, not an array. This causes the child products not to be shown when selecting a Grouped product in the _Single Product_ block in a post. Can you reproduce it too?

imatge

**Comment by albarin** [comment]
@mdperez86 @Aljullu
After talking a bit about it with the team, we agree with what @Aljullu was saying:
- It's okay to have the `get_visible_children` (similar to what the `WC_Product_Variable` class has).
- It's preferred not to have the `get_visible_child_ids` in the `WC_Product_Grouped` class.

Thank you both!

**Review by Aljullu — COMMENTED** [review]
> Btw, I noticed that the endpoint returns the products in this form `"grouped_products":{"1":66,"2":67},`, which JS considers to be an object, not an array. This causes the child products not to be shown when selecting a Grouped product in the _Single Product_ block in a post. Can you reproduce it too?

Strangely, I can only reproduce this with one Grouped product in my testing store, but can't reproduce it with newly created ones, so it's likely I had something broken on my dev site, sorry for the confusion!

Once the comment from @albarin has been addressed, this LGTM.

**Comment by mdperez86** [comment]
> In that case, I agree it makes sense having `get_visible_children()` as a method in the `WC_Product_Grouped` to be aligned with `WC_Product_Variable`. I'm not sure about `get_visible_child_ids()`, though. I feel that if we add this method, somebody in the future might want a similar method to retrieve the children's names, prices, etc. so we would end up with many methods all returning the same data in a different shape. On the other hand, using `get_visible_children()` and getting the IDs from there should be quite straightforward for consumers. What do you think?

done -> [da7e70d](https://github.com/woocommerce/woocommerce/pull/55024/commits/da7e70dfc49fb3685f52e71a4835c60e8756d547)

**Review by Aljullu — APPROVED** [review]
LGTM, good job, @mdperez86! :raised_hands:

File: plugins/woocommerce/tests/php/src/Blocks/StoreApi/Routes/Products.php [hunk 2]
```diff
@@ -66,12 +67,31 @@ public function test_get_item() {
...
 	}
 
+	/**
+	 * Test get grouped product.
+	 */
+	public function test_grouped_product() {
+		$response = rest_get_server()->dispatch( new \WP_REST_Request( 'GET', '/wc/store/v1/products/' . $this->products[2]->get_id() ) );
+		$data     = $response->get_data();
+
+		$grouped_product_ids = $this->products[2]->get_visible_child_ids();
```
Comment (Aljullu) [inline plugins/woocommerce/tests/php/src/Blocks/StoreApi/Routes/Products.php]: This test will need to be updated now that `get_visible_child_ids()` has been removed.
