### PR TITLE
Revise where context is added.

### LINKED ISSUE #16006: Structured data is incomplete
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [X] The issue still exists against the latest `master` branch of WooCommerce
- [X] This is not a usage question (Those should be directed to the [community](https://wordpress.org/support/plugin/woocommerce), unless this is a question about a premium plugin in which you should [use the helpdesk](https://woocommerce.com/my-account/tickets/) for official extensions or contact the author of 3rd party extensions)
- [X] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

Create a product with variants and check the resulting html.

## Expected behavior and actual behavior

Correct LD+JSON data rendered for the page.

On a launched site with the latest WP and WC I tried to locate the SEO data. I was happy what WC is using LD+JSON instead of markup, which is really theme dependent and a mess to maintain.

I found out that the simple product page contains 2 types of seo data: breadcrumb and product.

I see the following problems:
- Structured Data when wrapped into a graph element, there is not @context attribute at that level.
- Product item is missing the description, image and some other values, since in case of variants they're put into the Offers item and no default values lifted to the product level.

The root cause of the problem in the latest release is that this line was missing, which was re-added now in master: https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-structured-data.php#L237

### PR DESCRIPTION
**Pull request by mikejolley**
Adds `@context` at the `@graph` level in JSON+LD markup.

Closes #16006

### CODE REVIEW

File: includes/class-wc-structured-data.php [hunk 1]
```diff
@@ -91,15 +91,22 @@ public function get_structured_data( $types ) {
...
 		// Wrap the multiple values of each type inside a graph... Then add context to each type.
 		foreach ( $data as $type => $value ) {
-			$data[ $type ] = count( $value ) > 1 ? array( '@graph' => $value ) : $value[0];
-			$data[ $type ] = apply_filters( 'woocommerce_structured_data_context', array( '@context' => 'https://schema.org/' ), $data, $type, $value ) + $data[ $type ];
+			if ( 1 < count( $value ) ) {
+				$data[ $type ] = apply_filters( 'woocommerce_structured_data_context', array( '@context' => 'https://schema.org/' ), $data, $type, $value ) + array( '@graph' => $value );
+			} else {
+				$data[ $type ] = $value[0];
+			}
 		}
```
Comment (opportus) [inline includes/class-wc-structured-data.php]: @mikejolley, I think @saulfautley is right about the `@context`. This is putting item level `@context` only if there are multiple `$value`. Shouldn't we add `@context` to single `$value` also ?
