### PR TITLE
[HPOS] wc_get_order() should use global post/order object if necessary

### LINKED ISSUE #35561: wc_get_order() to get current order does not work with HPOS
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Calling `wc_get_order()` with no arguments to get the current order does not work when HPOS is enabled.

There is the global `$theorder` variable which still works, but I understand `wc_get_order()` is the preferred future-proof way to get an order. There is also `$_GET['id']` which is used [here](https://github.com/woocommerce/woocommerce/blob/736593ef1526ac1aa5495851789690b26eb2d657/plugins/woocommerce/src/Internal/Admin/Orders/PageController.php#L213), but that won't work on the Add Order screen.

Ideally, `wc_get_order()`  would be updated to work transparently with HPOS.

What is the currently recommended way to get the current order? Does the `$theorder` variable fall under the backward compatibility guarantee?

### Expected behavior

Calling `wc_get_order()` with no arguments should return the current order.

### Actual behavior

`false` is returned.

### Steps to reproduce

1. Call `wc_get_order()` from the Edit Order screen.

### WordPress Environment

<details>
<summary>Show details</summary>
`
### WordPress Environment ###

WC Version: 7.1.0
REST API Version: ✔ 7.1.0
WC Blocks Version: ✔ 8.7.5
Action Scheduler Version: ✔ 3.4.0
Log Directory Writable: ✔
WP Version: 6.1
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.14.0
PHP Version: 8.0.12
PHP Post Max Size: 2 GB
PHP Time Limit: 36000
PHP Max Input Vars: 1000
cURL Version: 7.76.1
OpenSSL/1.1.1l

SUHOSIN Installed: –
MySQL Version: 5.7.32
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.1.0
WC Database Prefix: wp_
Total Database Size: 5.29MB
Database Data Size: 3.43MB
Database Index Size: 1.86MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.06MB + Index: 0.13MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.05MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 2.02MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.14MB + Index: 0.06MB + Engine InnoDB
wp_posts: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wc_orders_meta: Data: 0.14MB + Index: 0.09MB + Engine InnoDB
wp_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 2
page: 6
post: 3
product: 3
product_variation: 1
revision: 9
shop_coupon: 1
shop_order: 10
shop_order_refund: 53
wp_global_styles: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: 
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: –

### WC Pages ###

Shop base: #4 - /shop/
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My account: #7 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty-Two
Version: 1.3
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
experimental-products-task
experimental-import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
multichannel-marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
settings

Daily Cron: ✔ Next scheduled: 2022-11-14 02:50:59 -05:00
Options: ✔
Notes: 10
Onboarding: completed

### Action Scheduler ###

Complete: 96
Oldest: 2022-10-18 22:28:34 -0400
Newest: 2022-11-13 20:29:10 -0500

Pending: 8
Oldest: 2022-11-13 20:36:49 -0500
Newest: 2022-11-19 18:20:44 -0500

### Status report information ###

Generated at: 2022-11-13 20:37:05 -05:00
`
</details>

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by barryhughes**
With the CPT data store for orders, calling `wc_get_order()` without passing an argument will still successfully return the current order object, so long as an order is referenced by the currently set global `$post` object.

In HPOS, it is desirable to have the same behavior since extension developers in particular rely on this to determine the current order object within the context of the admin order editor, and possibly other locations.

Closes #35561.

### How to test the changes in this Pull Request:

Add the following snippet to a suitable location, such as `wp-content/mu-plugins/test-35561.php`. Remove it when testing is complete.

```php
<?php

use Automattic\WooCommerce\Internal\DataStores\Orders\CustomOrdersTableController;

function add_wc_get_order_test_metabox() {
	$screen = wc_get_container()->get( CustomOrdersTableController::class )->custom_orders_table_usage_is_enabled()
		? wc_get_page_screen_id( 'shop-order' )
		: 'shop_order';

	add_meta_box(
		'test-35561',
		'TEST #35561',
		'render_wc_get_order_test_metabox',
		$screen,
		'side',
		'high'
	);
}

function render_wc_get_order_test_metabox() {
	$order   = wc_get_order();

	print '<p><strong style="color: red; ">';
	print $order ? 'SUCCESS! ORDER ID #' . $order->get_id() : 'FAILURE';
	print '</strong></p>';
}

add_action( 'add_meta_boxes', 'add_wc_get_order_test_metabox' );
```

This change should be tested with and without HPOS, but the above snippet should be in place both times.

1. To test *with* HPOS, you should visit **WooCommerce ▸ Settings ▸ Advanced ▸ Custom Data Stores** and select **Use the WooCommerce Order Stores** (don't see this option, or can't enable it? Please refer to the notes in [this earlier PR](https://github.com/woocommerce/woocommerce/pull/35999)).
2. To test without HPOS, select **Use the WordPress Posts Table** from that same admin screen.

Then:

1. Visit the order editor for any existing order.
2. Look at the sidebar, you should see a meta box labelled `TEST #35561`.
3. If this change is successful, you should see a message within the meta box indicating success and echoing the current order ID.
4. If the change is not successful, or if you are testing without this change, you should see a message indicating failure.

Screenshots of meta box output:

| Success | Failure |
| --- | --- |
| 35561-success | 35561-failure |

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

File: plugins/woocommerce/tests/legacy/unit-tests/order/class-wc-tests-order-functions.php [hunk 1]
```diff
@@ -178,11 +184,30 @@ public function test_wc_get_order() {
...
+			wc_get_order(),
+			'If no order ID is specified, wc_get_order() will use the global $post object to try and determine the current order.'
+		);
+
+		unset( $post );
+		$theorder = $order;
+		$this->assertInstanceOf(
+			'WC_Order',
+			wc_get_order(),
+			'If no order ID is specified, wc_get_order() will use the global $theorder object to try and determine the current order.'
```
Comment (coreymckrill) [inline plugins/woocommerce/tests/legacy/unit-tests/order/class-wc-tests-order-functions.php:205]: I think you mean "If the global $post object is not defined..." here?

**Review by coreymckrill — APPROVED** [review]
👍 Works as described with the test mu-plugin.

File: plugins/woocommerce/tests/legacy/unit-tests/order/class-wc-tests-order-functions.php (hunk 1 above)
Comment (barryhughes) [reply plugins/woocommerce/tests/legacy/unit-tests/order/class-wc-tests-order-functions.php:205]: Hmm 🤔 

That's actually not what I meant, and even if I didn't unset `$post` the assertion should pass, but you asking this makes me think I haven't laid things out very clearly.

`wc_get_order()` will potentially make use of the global `$theorder` object ***or*** the global `$post` object (and, in fact, the former takes precedence over the latter, though I decided not to highlight that subtlety here). The only reason I unset `$post` was to remove it from the landscape and show, as the description notes, that the SUT will also look to `$theorder` to figure out the current order.

Is there a way I could make this clearer?

Comment (barryhughes) [reply plugins/woocommerce/tests/legacy/unit-tests/order/class-wc-tests-order-functions.php:205]: To re-phrase a little, if all I did before this assertion was:

```php
$theorder = $order;
```

We might wonder if the SUT is still simply looking at the `$post` object. Unsetting it removes that ambiguity (or, that was my hope).
