### PR TITLE
Legacy shortcodes: block editor compatibility

### LINKED ISSUE #38169: [Block editor] Shortcodes and frontend functions can lead to fatal
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Simple shortcodes that take advantage of various WooCommerce helper functions such as `wc_print_notices()` (from within the shortcode's callback function) fail in the context of the block editor. Minimal example:

```php
add_shortcode( 'my_test', function () {
	ob_start();
	wc_print_notices();
	echo '<div>MY CUSTOM SHORTCODE</div>';
	return ob_get_clean();
} );
```

If a new page is created, and it contains a 'problematic' shortcode like the one defined above, the page cannot be saved as we will see a **Publishing Failed** error (see following screenshot). If an *existing* post is edited, and a problematic shortcode is added, we will essentially hit the same problem except the error will read **Updating Failed**.

<div align="center">publishing-failed</div>

### Expected behavior

No such error should occur, and the page should be successfully be published or updated.

### Actual behavior

The described error will occur, and the page or post cannot be saved or updated until the shortcode is removed. Again, this is only an issue in the block editor.

### Steps to reproduce

1. Add the sample code provided above.
2. Create a post or page (this must be done using the block editor).
3. Add the test shortcode `[my_test]` via a shortcode block, and then try to save.
4. Observe the error.
5. Rinse and repeat in the 'classic' editor, there is no problem.

### Notes

The problem here is two-fold:

- Various functions such as `wc_print_notices()` are [only loaded in the context of frontend requests](https://github.com/woocommerce/woocommerce/blob/7.6.1/plugins/woocommerce/includes/class-woocommerce.php#L553-L555).
- However, when a post containing a shortcode block is saved, the handler/callback is invoked outside of that context, resulting in undefined function errors.

I've logged this as a bug, because it feels like changing how and when WooCommerce Core includes these functions is the least disruptive way to solve this going forward—but an alternative would be to take the stance that existing any existing shortcodes that are subject to this problem should be updated and take their own precautions.

### WordPress Environment

—

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by barryhughes**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

In the pre-Gutenburg world, or when using the classic editor, shortcodes are typically entered in the editor but are only rendered during frontend requests. In the world of blocks, though, shortcodes may be (pre-)rendered in an admin context both when the block editor loads, and when a post is saved (which will happen via the REST API).

For this reason, any functions the shortcode handler might call need to be available, or else the shortcode handler needs to defensively check that they are available first. As described in the linked issue, there are particular problems relating to shortcodes that call our notice functions or that try to interact with the session handler (which is not instantiated for admin or REST requests).

Closes https://github.com/woocommerce/woocommerce/issues/38169.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Start by defining a shortcode. Here's some custom code you can use, which could be added to a location such as `wp-content/mu-plugins/test-40648.php` (once you finish testing, remember to remove it!):

```php
<?php
add_shortcode( 'my_test', function () {
	ob_start();
	wc_print_notices();
	echo '<div>MY CUSTOM SHORTCODE</div>';
	return ob_get_clean();
} );
```

2. Then, create a new page and add the shortcode (just to be extra clear, this should all be done using the block editor):

<div align="center">Screenshot 2023-10-25 at 16 10 18</div>

3. With this branch checked out, you should be able to publish and view the page without encountering any errors. 
4. With current `trunk` checked out, you will encounter problems. For instance, if you performed the above steps using this branch first, and then switch to trunk and reload the page editor, you will encounter a fatal error:

```
Fatal error: Uncaught Error: Call to undefined function wc_print_notices()
```

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Comment 

</details>

### Notes

In an ideal world, I think we'd cover this with an E2E test. My attempts to do that so far have been very flaky, though, so I decided not to commit it. We can either move forward without, or pause and (perhaps with help from Solaris) try to get that in place, or possibly circle back and add later.

### CODE REVIEW

File: plugins/woocommerce/includes/class-woocommerce.php [hunk 1]
```diff
@@ -417,7 +418,7 @@ private function is_request( $type ) {
 			case 'cron':
 				return defined( 'DOING_CRON' );
 			case 'frontend':
-				return ( ! is_admin() || defined( 'DOING_AJAX' ) ) && ! defined( 'DOING_CRON' ) && ! $this->is_rest_api_request();
+				return ( ! is_admin() || defined( 'DOING_AJAX' ) ) && ! defined( 'DOING_CRON' );
```
Comment (coreymckrill) [inline plugins/woocommerce/includes/class-woocommerce.php]: Kind of a nitpick, but it might be more accurate to add a separate case for `rest-api` and move `$this->is_rest_api_request()` into it. Also, defensively, it seems like `default:` should be added in a stack with `case 'frontend:` in case the front end case becomes more specific in the future.

File: plugins/woocommerce/includes/class-woocommerce.php [hunk 2]
```diff
@@ -584,7 +585,10 @@ public function includes() {
 			include_once WC_ABSPATH . 'includes/admin/class-wc-admin.php';
 		}
 
-		if ( $this->is_request( 'frontend' ) ) {
+		// We load frontend includes in the post editor, because they may be invoked via pre-loading of blocks.
+		$in_post_editor = doing_action( 'load-post.php' ) || doing_action( 'load-post-new.php' );
+
+		if ( $this->is_request( 'frontend' ) || $in_post_editor ) {
```
Comment (coreymckrill) [inline plugins/woocommerce/includes/class-woocommerce.php]: If you add the `rest-api` case mentioned above, you could use that here instead of `$in_post_editor`. Rationale being that there could be other non-frontend cases besides the post editor where a REST API request could potentially attempt to render a shortcode.

File: plugins/woocommerce/includes/wc-notice-functions.php [hunk 3]
```diff
@@ -137,7 +137,14 @@ function wc_print_notices( $return = false ) {
 		return;
 	}
 
-	$all_notices  = WC()->session->get( 'wc_notices', array() );
+	$session = WC()->session;
+
+	// If the session handler has not initialized, there will be no notices for us to read.
+	if ( null === $session ) {
+		return null;
```
Comment (coreymckrill) [inline plugins/woocommerce/includes/wc-notice-functions.php]: I think the `@return` clause in the doc block for this is wrong. It seems like it should be `string|void`, since that's what it does when you echo the content instead of returning it. As such, this should probably just be:

```suggestion
		return;
```

File: plugins/woocommerce/includes/class-woocommerce.php (hunk 2 above)
Comment (coreymckrill) [reply plugins/woocommerce/includes/class-woocommerce.php]: On the other hand, `frontend_includes` loads 12 more files, and I'm not sure whether that would appreciably impact REST API performance or not...

Comment (coreymckrill) [reply plugins/woocommerce/includes/class-woocommerce.php]: Just going to sit here and talk to myself while doing this PR review... 😅 

I think I would err on the side of preventing fatals, and if loading those extra files during every REST API request does end up having some kind of noticeable performance impact, we could devise a workaround for that in a separate PR.

**Review by coreymckrill — COMMENTED** [review]
👍 Works just as the testing instructions describe! A couple of comments/questions to ponder before merging, though.

File: plugins/woocommerce/includes/class-woocommerce.php (hunk 1 above)
Comment (barryhughes) [reply plugins/woocommerce/includes/class-woocommerce.php]: You're right! Updated in https://github.com/woocommerce/woocommerce/pull/40648/commits/b43a8cfc47d038b0c0c87f4873f69a70b0fc36cb.

- I restored the original test for `'frontend'` which, as you say, is more accurate.
- I initially added a case for `'rest-api'` ... then stripped it out in https://github.com/woocommerce/woocommerce/pull/40648/commits/9425dd049d81d38c76a18618144c7f1487852b77: this is a private method, so there are no external users, and internally we can simply use existing method `is_rest_api_request`.
- I did not make `'frontend'` the default clause. Though I definitely think there is a case for adding a default that returns false, it would seem risky to support a scenario where a typo like `is_request( 'badmin' )` evaluates to `is_request( 'frontend' )`.

File: plugins/woocommerce/includes/class-woocommerce.php (hunk 2 above)
Comment (barryhughes) [reply plugins/woocommerce/includes/class-woocommerce.php]: Updated in https://github.com/woocommerce/woocommerce/pull/40648/commits/b43a8cfc47d038b0c0c87f4873f69a70b0fc36cb.

- Though I decided in https://github.com/woocommerce/woocommerce/pull/40648/commits/9425dd049d81d38c76a18618144c7f1487852b77 *not* to support a `'rest-api'` case, I have added a call to `is_rest_api_request` which amounts to the same thing.
- We cannot strip the `$in_post_editor` check. To see this element of the problem, go ahead and create a page or post with the test shortcode, publish, then remove this test and reload the editor (fatal error).

Comment (barryhughes) [reply plugins/woocommerce/includes/class-woocommerce.php]: Regarding performance, we're chiefly loading class and function definitions and are not executing bodies of logic. That should be extremely low overhead (especially with opcode caching). That said, there are indeed some side effects as a result of including those files (ie, where we call `add_action()` without anything being invoked) ... even so, there are very few of these and I still expect overhead to be very low.

File: plugins/woocommerce/includes/wc-notice-functions.php (hunk 3 above)
Comment (barryhughes) [reply plugins/woocommerce/includes/wc-notice-functions.php]: Sharp eyes, great catch! Updated in https://github.com/woocommerce/woocommerce/pull/40648/commits/4a1b225571a42b500f26f69de6d00bd412f52bba.

File: plugins/woocommerce/includes/class-woocommerce.php (hunk 1 above)
Comment (coreymckrill) [reply plugins/woocommerce/includes/class-woocommerce.php]: > Though I definitely think there is a case for adding a default that returns false, it would seem risky to support a scenario where a typo like is_request( 'badmin' ) evaluates to is_request( 'frontend' ).

Good point 👍

**Review by coreymckrill — APPROVED** [review]
👍 Works great
