### PR TITLE
Fix missing data in certain WooCommerce blocks inside the Product block when editing as an author

### LINKED ISSUE #61369: Product block: several inner blocks show no content in the editor when logged in as an author
If, as an *author*, you add the *Product* block to a page, you will see there is some missing data: *Product Title*, *Product Description*, and *Images*.

| Admin | Author in WC 10.1 | Author in WC 10.2 |
| -- | -- | -- |
|  |  |  |

**To Reproduce**

1. Create a user with *Author* role.
2. Create a post and add the *Product* block.
3. Select a product and notice you don't see much of the block contents.

## **Expected behavior**

Authors should be able to preview the block as it will be displayed in the frontend.

### PR DESCRIPTION
**Pull request by Aljullu**
### Changes proposed in this Pull Request:

Closes https://github.com/woocommerce/woocommerce/issues/61369.

Alternative approach to https://github.com/woocommerce/woocommerce/pull/61470.

This PR updates the `/wc/v4/products/<id>` endpoint so it works for users with `edit_posts` capabilities (like _Authors_) when the product is published and not password-protected. This allows the endpoint to work in the post/page editor for authors, so the _Product_ block can render real product data.

As mentioned, for now I restricted this endpoint to users with the `edit_posts` capability so shoppers don't have access to it, even if the products are public. That's because I expect anything public-facing to be using the store API.

### How to test the changes in this Pull Request:

1. Create a user with *Author* role.
2. Create a post and add the *Product* block.
3. Select a product and verify the _Product Image Gallery_, _Product Rating_, _Product Summary_ and _Product Price_ blocks render the correct data. (Note: _Product Title_ is expected to be empty, that's a known issue)
4. Install WooCommerce Beta Tester, go to _Tools_ > _WCA Test Helper_ > _Features_ and enable _rest-api-v4_.
5. Repeat steps 1-3.

Before | After
--- | ---
imatge | imatge

6. Now, repeat steps 1-5 with an admin user.

### CODE REVIEW

File: plugins/woocommerce/src/Internal/RestApi/Routes/V4/Products/Controller.php [hunk 1]
```diff
@@ -134,6 +134,59 @@ public function register_routes() {
...
+	public function get_item_permissions_check( $request ) {
+		$object = $this->get_object( (int) $request['id'] );
+
+		if ( $object && 0 !== $object->get_id() ) {
+			if ( 'product' !== $object->post_type && 'product_variation' !== $object->post_type ) {
+				return new WP_Error( 'woocommerce_rest_cannot_view', __( 'Sorry, you cannot view this resource.', 'woocommerce' ), array( 'status' => rest_authorization_required_code() ) );
+			}
+
+			$object_id        = $object->get_id();
+			$post_type_object = get_post_type_object( 'product' );
```
[the remark this answers is not in the document]
Comment (Aljullu) [reply plugins/woocommerce/src/Internal/RestApi/Routes/V4/Products/Controller.php]: Fixed in b834c676f724eb729302b9f4e39b5f80c2724434.

File: plugins/woocommerce/client/blocks/assets/js/blocks/single-product/test/block.ts [hunk 2]
```diff
@@ -0,0 +1,131 @@
...
+describe( 'Product block', () => {
+	it( 'should render inner blocks for users without edit permissions', async () => {
+		// The V4 of this endpoint will return product data to authors,
+		// see https://github.com/woocommerce/woocommerce/pull/61718.
+		// However, V3 didn't, that's why we need this test.
+		server.use(
+			http.get( '/wc/v3/products/:id', () => {
+				return HttpResponse.json( '', { status: 403 } );
+			} )
+		);
```
Comment (gigitux) [inline plugins/woocommerce/client/blocks/assets/js/blocks/single-product/test/block.ts:95]: Are you sure that this is necessary? If the feature flag isn't enabled, the block should rely on the old system (store API)

File: plugins/woocommerce/client/blocks/assets/js/blocks/single-product/test/block.ts [hunk 3]
```diff
@@ -0,0 +1,131 @@
...
+		const productPrice = await screen.findByText( '20,00 €' );
+		expect( productPrice ).toBeInTheDocument();
+	} );
+
+	it( 'should render inner blocks for admins', async () => {
+		server.use(
+			http.get( '/wc/v3/products/:id', () => {
+				return HttpResponse.json( mockProduct );
+			} )
+		);
```
Comment (gigitux) [inline plugins/woocommerce/client/blocks/assets/js/blocks/single-product/test/block.ts:116]: Same question

File: plugins/woocommerce/src/Internal/RestApi/Routes/V4/Products/Controller.php [hunk 4]
```diff
@@ -134,6 +134,59 @@ public function register_routes() {
...
+			$object_id        = $object->get_id();
+			$post_type_object = get_post_type_object( $object->post_type );
+			$permission       = false;
+
+			if ( $post_type_object instanceof \WP_Post_Type ) {
+				// These are the default permissions inherited from
+				// `WC_REST_Products_V2_Controller`.
+				$permission = current_user_can( $post_type_object->cap->read_private_posts, $object_id );
+
+				// We add an especial case when the post is published, not
```
Comment (gigitux) [inline plugins/woocommerce/src/Internal/RestApi/Routes/V4/Products/Controller.php]: NIT:
```suggestion
				// We add an special case when the post is published, not
```

**Review by gigitux — CHANGES_REQUESTED** [review]
Thanks for working on this PR, I left small comments. 

Can you add an entry in the [README.md in the changelog section](https://github.com/woocommerce/woocommerce/blob/b834c676f724eb729302b9f4e39b5f80c2724434/plugins/woocommerce/src/Internal/RestApi/Routes/V4/Products/README.md#L25-L74)?

File: plugins/woocommerce/client/blocks/assets/js/blocks/single-product/test/block.ts (hunk 2 above)
Comment (Aljullu) [reply plugins/woocommerce/client/blocks/assets/js/blocks/single-product/test/block.ts:95]: Hmmm, I think so. :thinking: The old system was used because of this:

https://github.com/woocommerce/woocommerce/pull/61718/files#diff-98520f0d87c78581322458c813a536d9102f5c75d4c298066893f0ba300fb5c4L111-L113

If I follow the testing steps with `rest-api-v4` disabled, this is what I see as an author:

imatge

So this unit test is verifying that this is fixed.

File: plugins/woocommerce/src/Internal/RestApi/Routes/V4/Products/Controller.php (hunk 4 above)
Comment (Aljullu) [reply plugins/woocommerce/src/Internal/RestApi/Routes/V4/Products/Controller.php]: Nice catch, fixed!

File: plugins/woocommerce/client/blocks/assets/js/blocks/single-product/test/block.ts (hunk 2 above)
Comment (gigitux) [reply plugins/woocommerce/client/blocks/assets/js/blocks/single-product/test/block.ts:95]: Ah right, it makes sense!

**Review by gigitux — APPROVED** [review]
@Aljullu Thanks for this PR! I'm pre-approving this PR, but [can you update the README.md](https://github.com/woocommerce/woocommerce/pull/61718#pullrequestreview-3416691102) before merging this PR? Thanks!

**Comment by Aljullu** [comment]
> https://github.com/woocommerce/woocommerce/pull/61718#pullrequestreview-3416691102 before merging this PR?

Ups, sorry I missed that. :man_facepalming: Added in https://github.com/woocommerce/woocommerce/pull/61718/commits/7c67f666de0cf9c4a2c7c1f21cf7761a71023a46.
