### PR TITLE
[WIP][Accessibility] Add field for the email footer text color

### LINKED ISSUE #43603: Accessibility: Email footer #credit fails color contrast and there's no setting for users to override it
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Text in the credit in the email footer is set just to lighten the color of the body text. See:
https://github.com/woocommerce/woocommerce/blob/758df4854d7b627fc26eb5c0860dc492dea6a06e/plugins/woocommerce/templates/emails/email-styles.php#L100C30-L100C46

There is also no selector in admin settings to define the color for text in the credit. Even if the body text is quite dark and the background is set to nearly white, the 40% lighting results in a color contrast failure for text in the credit:
Screenshot showing color contrast issue in footer of email template

The only way to resolve the color contrast issue in this text is to add a span tag in the credit field and hardcode a color in that way.

### Expected behavior

Two things should happen here:

1. The default email template colors should be changed so that the colors pass contrast checks in their default state, if a website owner never changes them. [See this contrast checker for reference.](https://webaim.org/resources/contrastchecker/)
2. There should be a setting in the WP admin email settings allowing users to change the color of the credit text without having to use HTML in the credit text box.

### Actual behavior

There is a color contrast failure that is not easily fixed.

### Steps to reproduce

Open the default WooCommerce email settings and preview the email or reference the code link above.

### WordPress Environment

N/A

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by amesplant**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes #43603 

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Open the default Woocommerce > Settings > Email
image

2. There should now see an additional field for Footer text color
image

3. Update the color
4. Preview the email and note that the color is as-is with no reduction in opacity

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [x] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [x] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

Add field for the email footer text color

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

**Comment by amesplant** [comment]
@dkotter ready for your review

File: plugins/woocommerce/includes/admin/settings/class-wc-settings-emails.php [hunk 1]
```diff
@@ -191,6 +191,18 @@ protected function get_settings_for_default_section() {
 					'desc_tip' => true,
 				),
 
+                array(
```
Comment (dkotter) [inline plugins/woocommerce/includes/admin/settings/class-wc-settings-emails.php]: Getting a PHPCS error here due to using spaces instead of tabs: https://github.com/woocommerce/woocommerce/actions/runs/9980468073/job/27582309298?pr=49648#step:4:30

File: plugins/woocommerce/includes/admin/settings/class-wc-settings-emails.php [hunk 2]
```diff
@@ -191,6 +191,18 @@ protected function get_settings_for_default_section() {
...
+					'title'    => __( 'Footer text color', 'woocommerce' ),
+					/* translators: %s: footer default color */
+					'desc'     => sprintf( __( 'The footer text color. Default %s.', 'woocommerce' ), '<code>#3c3c3c</code>' ),
+					'id'       => 'woocommerce_email_footer_text_color',
```
Comment (dkotter) [inline plugins/woocommerce/includes/admin/settings/class-wc-settings-emails.php:198]: Unit tests are failing due to this new setting. We'll need to update those tests to account for this: https://github.com/woocommerce/woocommerce/actions/runs/9980468073/job/27582309555?pr=49648#step:7:121

**Review by dkotter — CHANGES_REQUESTED** [review]

**Review by nielslange — COMMENTED** [review]
Thanks for working on this, @amesplant. I have a couple of questions regarding the proposed addition of a new field for the footer text color:

1. Could we use the existing body text color for the footer instead of introducing a new field?
2. If distinct customization for the footer is necessary, should we also consider adding an option to define the footer background color for consistency?

I'm asking with the following scenario in mind. Imagine a merchant is using `#ffffff` as a body background color, `#000000` as a body text color and `#cccccc` as a footer text color. In this scenario, the footer text would render almost invisible.

**Comment by amesplant** [comment]
@nielslange 
> 1. Could we use the existing body text color for the footer instead of introducing a new field?
- we definitely could do this, if that would be the preferred solution

> 2. If distinct customization for the footer is necessary, should we also consider adding an option to define the footer background color for consistency?
> I'm asking with the following scenario in mind. Imagine a merchant is using `#ffffff` as a body background color, `#000000` as a body text color and `#cccccc` as a footer text color. In this scenario, the footer text would render almost invisible.
- the author of the issue made the request to customize the footer text, which I have set at the moment as the same default as the body text. I am happy to either go with scenario 1 or if we are allowing for the custom footer text color, could add in easily the footer background color as well.

Do you have a preference in which direction we take?

**Comment by amesplant** [comment]
@nielslange I added an option for the footer background color in case that was the route we wanted to go.

**Comment by nielslange** [comment]
Sorry for my delayed reply, @amesplan. 

> @nielslange I added an option for the footer background color in case that was the route we wanted to go.

While I cannot make that decision, I would have gone with reusing the body color as the footer color. Introducing new fields, increases the complexity and the maintenance-burdern, while reusing an existing field prevents that. 

@ralucaStan and @opr Which approach would you suggest in this case?

**Comment by amesplant** [comment]
> While I cannot make that decision, I would have gone with reusing the body color as the footer color. Introducing new fields, increases the complexity and the maintenance-burdern, while reusing an existing field prevents that.

Totally understood, and happy to update to whatever direction is recommended 😁 cc @ralucaStan and @opr

**Comment by vikrampm1** [comment]
@ralucaStan @opr can you review the comments above and suggest an approach here? Thanks.

**Comment by opr** [comment]
Thanks for the ping.

I think there are cases where using the body text would result in completely invisible footer text, e.g.

image


Based on that, I think having the footer text colour editable is fine, but I don't think there's a need to allow the footer background colour to be set, this can be set by `Background color`.

**Comment by amesplant** [comment]
@opr I have removed the footer background color

**Comment by opr** [comment]
Thanks! @nielslange would you be able to continue reviewing this? 🙏🏼  feel free to hand it off to me if you don't have time.

**Review by nielslange — APPROVED** [review]
I successfully tested this change, @amesplant:

Screenshot 2024-07-31 at 10 33 02

I did notice that the `plugins/woocommerce/templates/emails/email-styles.php` template needs to be bumped to version 9.3.0, as version 9.2.0 is currently in preparation. Please notify me once you've adjusted the version so that I can merge this PR. And thanks for working on this improvement. 👏

**Comment by amesplant** [comment]
@nielslange `plugins/woocommerce/templates/emails/email-styles.php` template has been bumped to version 9.3.0 😄

**Comment by nielslange** [comment]
> @nielslange `plugins/woocommerce/templates/emails/email-styles.php` template has been bumped to version 9.3.0 😄

Great! Thanks for addressing this last point. I'm merging this PR now, and thanks again for working on this improvement. 🙌

**Comment by amesplant** [comment]
@nielslange is there something that you still need to be done here, I see that you reopened this

**Comment by opr** [comment]
@amesplant Niels closed and opened this to trigger the CI jobs, sometimes they get stuck.

There are some fixes that you need to make to satisfy the linter, [this run](https://github.com/woocommerce/woocommerce/actions/runs/10204232496/job/28232351791?pr=49648) contains the errors encountered.

**Comment by amesplant** [comment]
@opr linting fixed 😁

**Comment by opr** [comment]
Thanks a lot, @amesplant, really appreciate your work on this!
