### PR TITLE
Reset slug when duplicating product - fix #14128

### LINKED ISSUE #14128: Duplicate product no longer updates slug based on product title when saved
### EXPLANATION OF THE ISSUE

Duplicate product no longer updates slug based on product title when saved in 3.0.1 . Previous versions prior to update would generate new slug from the updated product title.

### STEPS TO REPRODUCE THE ISSUE

Simply duplicate a product, change the title and publish. The slug does not update as it used to. 

### SYSTEM STATUS

<details>
`
### WordPress Environment ###

Home URL: redacted
Site URL: redacted
Log Directory Writable: ✔
WP Version: 4.7.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.29
PHP Post Max Size: 64 MB
PHP Time Limit: 0
PHP Max Input Vars: 1000
cURL Version: 7.24.0
OpenSSL/1.0.0

SUHOSIN Installed: –
MySQL Version: 5.6.32
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.1
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (11) ###

All-in-One WP Migration: by ServMask – 6.42
Enhanced Media Library: by wpUXsolutions – 2.4.4
GetBowtied Tools: by GetBowtied – 1.3.1
WPBakery Visual Composer: by Michael M - WPBakery.com – 5.0.1
Ultimate WooCommerce Brands PRO: by MagniumThemes – 1.5
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 2.2.6
Category Order and Taxonomy Terms Order: by Nsp-Code – 1.4.9
WooCommerce Category Accordion.: by TechieResource – 1.2.1
Booster for WooCommerce: by Algoritmika Ltd – 2.6.0
WooCommerce Variable Product Description: by Shop Plugins – 1.0.1
WooCommerce: by Automattic – 3.0.1

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: CAD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: simple (simple)
grouped (grouped)
variable (variable)
external (external)

### WC Pages ###

Shop base: #5 - /shop/
Cart: #6 - /cart/
Checkout: #7 - /checkout/
My account: #8 - /my-account/

### Theme ###

Name: Mr. Tailor Child
Version: 1.0
Author URL: http:%20//www.getbowtied.com/
Child Theme: ✔
Parent Theme Name: Mr. Tailor
Parent Theme Version: 2.4
Parent Theme Author URL: http://www.getbowtied.com/
WooCommerce Support: ✔

### Templates ###

Overrides: mrtailor/woocommerce/archive-product.php
mrtailor/woocommerce/cart/cart-empty.php
mrtailor/woocommerce/cart/mini-cart.php
mrtailor/woocommerce/checkout/form-billing.php version 2.1.2 is out of date. The core version is 3.0.0
mrtailor/woocommerce/checkout/form-checkout.php
mrtailor/woocommerce/checkout/form-coupon.php
mrtailor/woocommerce/checkout/form-login.php
mrtailor/woocommerce/checkout/form-shipping.php
mrtailor/woocommerce/checkout/payment-method.php
mrtailor/woocommerce/checkout/thankyou.php
mrtailor/woocommerce/content-product.php version 2.6.1 is out of date. The core version is 3.0.0
mrtailor/woocommerce/content-product_cat.php
mrtailor/woocommerce/content-single-product.php
mrtailor/woocommerce/global/wrapper-end.php
mrtailor/woocommerce/global/wrapper-start.php
mrtailor/woocommerce/loop/loop-end.php
mrtailor/woocommerce/loop/loop-start.php
mrtailor/woocommerce/loop/no-products-found.php
mrtailor/woocommerce/loop/orderby.php
mrtailor/woocommerce/loop/result-count.php version 2.0.0 is out of date. The core version is 3.0.0
mrtailor/woocommerce/myaccount/form-login.php
mrtailor/woocommerce/notices/error.php
mrtailor/woocommerce/order/form-tracking.php
mrtailor/woocommerce/single-product/product-image.php
mrtailor/woocommerce/single-product/product-thumbnails.php
mrtailor/woocommerce/single-product/short-description.php
mrtailor/woocommerce/single-product/tabs/tabs.php
mrtailor/woocommerce/single-product.php

Outdated Templates: ❌Learn how to update
`
</details>

### PR DESCRIPTION
**Pull request by 4refael**
Closes #14128

### CODE REVIEW

File: includes/admin/class-wc-admin-duplicate-product.php [hunk 1]
```diff
@@ -123,6 +123,7 @@ public function product_duplicate( $product ) {
 		}
 		$duplicate->set_status( 'draft' );
 		$duplicate->set_date_created( null );
+		$duplicate->set_slug( null );
```
Comment (mikejolley) [inline includes/admin/class-wc-admin-duplicate-product.php]: Should this be empty string rather than null? Method expects string.

Comment (rellect) [inline includes/admin/class-wc-admin-duplicate-product.php]: Yea you're right, the docs say the expected type is a string. I've changed it now.
Although I think null is more self-explanatory for such cases. (empty strings looks to me like a mistake at first glance)

**Comment by claudiulodro** [comment]
Looks good to me now.
