### PR TITLE
Show notice in checkout with only Express Payments available

### LINKED ISSUE #58585: Remove error message on blocks checkout when only express payment methods enabled
## **Describe the bug**

When only express checkout payment methods enabled in the store, there is an error message displayed at the bottom of the blocks checkout page, saying that no payment methods available.

That is misleading because express checkout methods are still available and properly rendered at the top.

## **To Reproduce**

1. Disable all payment methods.
2. Enable PayPal payments only.
3. Add **Subscription product** to cart and proceed to blocks checkout.
4. The error message displayed at the botton.

## **Expected behavior**

No error message should be displayed, when express checkout methods are available.

## **Screenshots**

Added below

## Environment

Please fill out any of the below that applies

**Operating System/Device**

- [ ] Windows
- [X] MacOS
- [ ] Linux
- [ ] iPhone
- [ ] Samsung
- [ ] Other (add in additional context field)

**Version:** Add the Desktop OS and/or Device version(s) here

**Browser**

- [ ] Desktop Edge
- [X] Desktop Chrome/Chromium
- [ ] Desktop Safari
- [ ] Mobile Edge
- [ ] Mobile Chrome/Chromium
- [ ] Mobile Safari
- [ ] Other (add in additional context field)

**Version:** Add the browser version(s) here.

## **Additional context**

Noticed on WooCommerce 9.8.5. Haven't tested on newer versions.

### PR DESCRIPTION
**Pull request by ralucaStan**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes https://github.com/woocommerce/woocommerce/issues/58585
Closes https://linear.app/a8c/issue/WOOPLUG-4524/remove-error-message-on-blocks-checkout-when-only-express-payment

 It also fixes an unrelated additional fields blocks E2E test which was randomly failing. See commit https://github.com/woocommerce/woocommerce/pull/59075/commits/d4fc63b0858acb09ce8368c1fc8d96130bf1fd4c

### Screenshots or screen recordings:

| Before | After |
| ------ | ----- |
|68747470733a2f2f75706c6f6164732e6c696e6561722e6170702f66363239666364652d366639622d343865382d386166332d3630656564383832336266662f32356662393233362d656330322d343661332d613363642d3635393762376662343437332f38396137326466652d393662612d346332332d   |    Screenshot 2025-06-23 at 13 43 55 |

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

On your local site make sure you have WooCommerce Subscription enabled, with a subscription product and no payment methods installed
### Set up an express payment method that accepts subs
1. Clone https://github.com/woocommerce/woocommerce-gateway-dummy
2. Edit `resources/js/frontend/index.js` and replace the code with the code below in order to only register an Express payments method
3. [Install the project ](https://github.com/woocommerce/woocommerce-gateway-dummy/blob/a94c4766e64c11df5ea089b13b7a5cfadc577a39/README.md)and activate the Dummy Gateway plugin on your test site

1. Add a subs to cart and go to checkout
2. Notice the info notice (blue notice) in the payments options area and the Express button from the plugin
3. Disable the Dummy Gateway 
4. Notice the error notice in the payments options area with the updated text

```
import { sprintf, __ } from "@wordpress/i18n";
import {
  registerPaymentMethod,
  registerExpressPaymentMethod,
} from "@woocommerce/blocks-registry";
import { decodeEntities } from "@wordpress/html-entities";
import { getSetting } from "@woocommerce/settings";

const settings = getSetting("dummy_data", {});

const defaultLabel = __("Dummy Payments", "woo-gutenberg-products-block");

const label = decodeEntities(settings.title) || defaultLabel;
/**
 * Content component
 */
const Content = () => {
  return decodeEntities(settings.description || "");
};
/**
 * Label component
 *
 * @param {*} props Props from payment API.
 */
const Label = (props) => {
  const { PaymentMethodLabel } = props.components;
  return <PaymentMethodLabel text={label} />;
};

const DummyExpress = {
  name: "dummy-express",
  label: <Label />,
  content: <button>Dummy Express</button>,
  edit: <button>Dummy Express</button>,
  canMakePayment: () => true,
  ariaLabel: label,
  supports: {
    features: ["products", "subscriptions"],
  },
};

registerExpressPaymentMethod(DummyExpress);

```

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

**Review by straku — APPROVED** [review]
Works as advertised. The only bit I am wondering about is the wording used in the error state:
> Only express payment methods are available. Please contact us for help placing your order.

I know contact is necessary when there's no payment methods, but with express one available shouldn't we suggest using it instead?

**Comment by ralucaStan** [comment]
> I know contact is necessary when there's no payment methods, but with express one available shouldn't we suggest using it instead?

Thank you for the review. I used another text. Let me know what you think

File: plugins/woocommerce/client/blocks/assets/js/blocks/cart-checkout-shared/payment-methods/only-express-payments/index.tsx [hunk 1]
```diff
@@ -0,0 +1,30 @@
...
+ */
+const OnlyExpressPayments = () => {
+	return (
+		<NoticeBanner
+			isDismissible={ false }
+			className="wc-block-checkout__only-express-payments-notice"
+			status="info"
+		>
+			{ __(
+				'Only express payment methods are available for this order. Please choose one to place your order.',
```
Comment (straku) [inline plugins/woocommerce/client/blocks/assets/js/blocks/cart-checkout-shared/payment-methods/only-express-payments/index.tsx]:
```suggestion
				'Only express payment methods are available for this order. Please select one to continue.',
```
I think the repeated "order" breaks my brain a little. What do you think about this suggestion?

**Comment by ralucaStan** [comment]
For visibility, I've also fixed another unrelated blocks E2E test failing on this PR in this commit https://github.com/woocommerce/woocommerce/pull/59075/commits/d4fc63b0858acb09ce8368c1fc8d96130bf1fd4c.
