### PR TITLE
CYS: Fix opt-in flow fonts

### LINKED ISSUE #49161: CYS: Revisit Opt-in usage tracking UX
During a QA @verofasulo said:

> The behavior here is quite strange. I clicked on “usage tracking” and the modal appeared—all good so far. But when I clicked the button to opt in, my screen changed. I saw a loading screen (the one with the illustration we show when the user clicks “Start designing”), then a blank screen with a spinner, and finally, I was directed to the homepage section with the intro panel closed.

>Correct behavior: no loaders, no change of context. When the user clicks the button to opt in, the button should enter a loading state, and once finished, the modal should close and the patterns should update. The panel should remain open.

image

### PR DESCRIPTION
**Pull request by gigitux**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes https://github.com/woocommerce/woocommerce/issues/49161

https://github.com/user-attachments/assets/c7e34585-dd4f-432d-9a69-4f75f36a3fd6

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Ensure that the tracking is disabled (`wp-admin/admin.php?page=wc-settings&tab=advanced&section=woocommerce_com` -> enable tracking setting)
2. Head over to WooCommerce > Home > Customize your store.
3. Click on "Choose your fonts".
4. Ensure that you see only two font pairs.
5. Ensure that `Opt in to usage tracking to get access to more fonts.` is visible.
6. Click on `usage tracking`.
7. Ensure that the modal is visible.
8. Click on `Opt-in`.
9. Ensure that the modal is closed and other font pairs are visible.

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [x] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [x] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

CYS: Improve opt-in flow fonts.

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce-admin/client/customize-store/assembler-hub/utils/fonts.ts [hunk 1]
```diff
@@ -0,0 +1,282 @@
...
+
+	return ( await Promise.all( [
+		...fontFamiliesWithFontFaceToInstallPromises,
+		...fontFacesToInstallPromises,
+	] ) ) as Array<
+		Array< {
+			font_face_settings: FontFace;
+		} >
+	>;
+};
```
Comment (gigitux) [inline plugins/woocommerce-admin/client/customize-store/assembler-hub/utils/fonts.ts:282]: I moved this code from `service.ts` file

**Review by albarin — APPROVED** [review]
👏 👏 👏
