### PR TITLE
Accessibility: Set aria-role to presentational for layout tables within emails.

### LINKED ISSUE #60410: Accessibility: Email tables.
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

This was initially reported as WOOPRE-64, however the markup referenced in the ticket is generated by WooCommerce Core in the various `woocommerce_email_*` hooks ([code reference](https://github.com/woocommerce/woocommerce/blob/aae056e36ca0cabe15c995040839611969c12867/plugins/woocommerce/includes/class-wc-emails.php#L233-L242))

> Tables in ~the pre-order~ emails are missing row and column header or are used for presentation purposes but not indicated as such.

1. The "Order summary" tables lack table headers for the icon, product name, quantity and sub-total. Recommendation: Add headers with `scope=col`
2. Each product row is missing a table header (which should probably be the product name). I don't have a complete recommendation for this as I think it needs a11y expert feedback.
3. Tables used for presentation last the suitable role. Recommendation: add `role=presentation` to these tables so screen readers will ignore it and not announce the content as being within a table.

Suggested Labels: Email, Accessibility

### Expected behavior

Email tables should use accessible markup

### Actual behavior

Email tables lack headers, roles.

### Steps to reproduce

1. Navigate to email settings, `/wp-admin/admin.php?page=wc-settings&tab=email`
2. Inspect the HTML email preview in your browser's dev tools
3. Observe lack of appropriate markup in table.

<details>

<summary>New Order Email Markup</summary>

```html
<table width="100%" id="outer_wrapper" style="background-color: #fff;" bgcolor="#fff">
			<tbody><tr>
				<td><!-- Deliberately empty to support consistent sizing and layout across multiple email clients. --></td>
				<td width="600">
					<div id="wrapper" dir="ltr" style="margin: 0 auto; padding: 24px 0; width: 100%; max-width: 600px; -webkit-text-size-adjust: none;" width="100%">
						<table border="0" cellpadding="0" cellspacing="0" height="100%" width="100%" id="inner_wrapper" style="background-color: #fff; border-radius: 8px;" bgcolor="#fff">
							<tbody><tr>
								<td align="center" valign="top">
																			<table border="0" cellpadding="0" cellspacing="0" width="100%">
											<tbody><tr>
												<td id="template_header_image" style="padding: 32px 32px 0;">
													<p class="email-logo-text" style="color: #111; font-family: &quot;Helvetica Neue&quot;,Helvetica,Roboto,Arial,sans-serif; font-size: 18px; margin-bottom: 0; text-align: left;" align="left">Pre-orders (AUD)</p>												</td>
											</tr>
										</tbody></table>
																		<table border="0" cellpadding="0" cellspacing="0" width="100%" id="template_container" style="box-shadow: none; background-color: #fff; border: 0; border-radius: 3px;" bgcolor="#fff">
										<tbody><tr>
											<td align="center" valign="top">
												<!-- Header -->
												<table border="0" cellpadding="0" cellspacing="0" width="100%" id="template_header" style="background-color: #fff; color: #111; border-bottom: 0; font-weight: bold; line-height: 100%; vertical-align: middle; font-family: &quot;Helvetica Neue&quot;,Helvetica,Roboto,Arial,sans-serif; border-radius: 3px 3px 0 0;" bgcolor="#fff">
													<tbody><tr>
														<td id="header_wrapper" style="padding: 20px 32px 0; display: block;">
															<h1 style="font-family: &quot;Helvetica Neue&quot;,Helvetica,Roboto,Arial,sans-serif; font-size: 32px; font-weight: 700; letter-spacing: -1px; line-height: 120%; margin: 0; color: #111; background-color: inherit; text-align: left;" bgcolor="inherit">New order: #PWCC-1753150877-12345</h1>
														</td>
													</tr>
												</tbody></table>
												<!-- End Header -->
											</td>
										</tr>
										<tr>
											<td align="center" valign="top">
												<!-- Body -->
												<table border="0" cellpadding="0" cellspacing="0" width="100%" id="template_body">
													<tbody><tr>
														<td valign="top" id="body_content" style="background-color: #fff;" bgcolor="#fff">
															<!-- Content -->
															<table border="0" cellpadding="20" cellspacing="0" width="100%">
																<tbody><tr>
																	<td valign="top" id="body_content_inner_cell" style="padding: 20px 32px 32px;">
																		<div id="body_content_inner" style="color: #414141; font-family: &quot;Helvetica Neue&quot;,Helvetica,Roboto,Arial,sans-serif; font-size: 16px; line-height: 150%; text-align: left;" align="left">

<div class="email-introduction" style="padding-bottom: 24px;">
<p style="margin: 0 0 16px;">You’ve received a new order from John Doe:</p>
</div>

<h2 class="email-order-detail-heading" style="color: #111; display: block; font-family: &quot;Helvetica Neue&quot;,Helvetica,Roboto,Arial,sans-serif; font-size: 20px; font-weight: bold; line-height: 160%; margin: 0 0 18px; text-align: left;">
	Order summary<br><span style="color: #787c82; display: block; font-size: 14px; font-weight: normal;"><a target="_blank" class="link" href="https://steady-starling-concrete.ngrok-free.app/pre-orders/wp-admin/admin.php?page=wc-orders&amp;action=edit&amp;id=12345" style="font-weight: normal; text-decoration: underline; color: #111;">Order #PWCC-1753150877-12345</a> (August 18, 2025)</span>
</h2>

<div style="margin-bottom: 24px;">
	<table class="td font-family email-order-details" cellspacing="0" cellpadding="6" border="0" style="color: #414141; border: 0; vertical-align: middle; font-family: &quot;Helvetica Neue&quot;,Helvetica,Roboto,Arial,sans-serif; width: 100%;" width="100%">
				<tbody>
				<tr class="order_item">
		<td class="td font-family text-align-left" style="color: #414141; border: 0; font-family: &quot;Helvetica Neue&quot;,Helvetica,Roboto,Arial,sans-serif; text-align: left; padding: 8px 12px; padding-left: 0; vertical-align: middle; word-wrap: break-word;" align="left">
							<table class="order-item-data" style="color: #111; font-family: &quot;Helvetica Neue&quot;,Helvetica,Roboto,Arial,sans-serif;">
					<tbody><tr>
						<td style="vertical-align: middle; padding-left: 0; border-bottom: 1px solid rgba(0,0,0,.2); padding-bottom: 24px; border: 0; padding: 0;"><img src="https://steady-starling-concrete.ngrok-free.app/content/plugins/woocommerce/assets/images/placeholder.webp" width="48" height="48" alt="" style="border: none; display: inline-block; font-size: 14px; font-weight: bold; height: auto; outline: none; text-decoration: none; text-transform: capitalize; vertical-align: middle; margin-right: 24px; max-width: 100%;" border="0"></td>						<td style="vertical-align: middle; padding-right: 0; border-bottom: 1px solid rgba(0,0,0,.2); padding-bottom: 24px; border: 0; padding: 0;">
							Dummy Product<div class="email-order-item-meta" style="color: #787c82; font-size: 14px; line-height: 140%;"></div>						</td>
					</tr>
				</tbody></table>
						</td>
		<td class="td font-family text-align-right" style="color: #414141; border: 0; font-family: &quot;Helvetica Neue&quot;,Helvetica,Roboto,Arial,sans-serif; text-align: right; padding: 8px 12px; vertical-align: middle;" align="right">
			×2		</td>
		<td class="td font-family text-align-right" style="color: #414141; border: 0; font-family: &quot;Helvetica Neue&quot;,Helvetica,Roboto,Arial,sans-serif; text-align: right; padding: 8px 12px; padding-right: 0; vertical-align: middle;" align="right">
			<span class="woocommerce-Price-amount amount"><span class="woocommerce-Price-currencySymbol">$</span>50.00</span>		</td>
	</tr>
	
	<tr class="order_item">
		<td class="td font-family text-align-left" style="color: #414141; border: 0; font-family: &quot;Helvetica Neue&quot;,Helvetica,Roboto,Arial,sans-serif; text-align: left; padding: 8px 12px; padding-left: 0; border-bottom: 1px solid rgba(0,0,0,.2); padding-bottom: 24px; vertical-align: middle; word-wrap: break-word;" align="left">
							<table class="order-item-data" style="color: #111; font-family: &quot;Helvetica Neue&quot;,Helvetica,Roboto,Arial,sans-serif;">
					<tbody><tr>
						<td style="vertical-align: middle; padding-left: 0; border-bottom: 1px solid rgba(0,0,0,.2); padding-bottom: 24px; border: 0; padding: 0;"><img src="https://steady-starling-concrete.ngrok-free.app/content/plugins/woocommerce/assets/images/placeholder.webp" width="48" height="48" alt="" style="border: none; display: inline-block; font-size: 14px; font-weight: bold; height: auto; outline: none; text-decoration: none; text-transform: capitalize; vertical-align: middle; margin-right: 24px; max-width: 100%;" border="0"></td>						<td style="vertical-align: middle; padding-right: 0; border-bottom: 1px solid rgba(0,0,0,.2); padding-bottom: 24px; border: 0; padding: 0;">
							Dummy Product Variation<div class="email-order-item-meta" style="color: #787c82; font-size: 14px; line-height: 140%;">
<span>Color:</span> Red<br><span>Size:</span> Small</div>						</td>
					</tr>
				</tbody></table>
						</td>
		<td class="td font-family text-align-right" style="color: #414141; border: 0; font-family: &quot;Helvetica Neue&quot;,Helvetica,Roboto,Arial,sans-serif; text-align: right; padding: 8px 12px; border-bottom: 1px solid rgba(0,0,0,.2); padding-bottom: 24px; vertical-align: middle;" align="right">
			×1		</td>
		<td class="td font-family text-align-right" style="color: #414141; border: 0; font-family: &quot;Helvetica Neue&quot;,Helvetica,Roboto,Arial,sans-serif; text-align: right; padding: 8px 12px; padding-right: 0; border-bottom: 1px solid rgba(0,0,0,.2); padding-bottom: 24px; vertical-align: middle;" align="right">
			<span class="woocommerce-Price-amount amount"><span class="woocommerce-Price-currencySymbol">$</span>20.00</span>		</td>
	</tr>
	
		</tbody>
		<tfoot>
								<tr class="order-totals order-totals-subtotal">
						<th class="td text-align-left" scope="row" colspan="2" style="color: #414141; border: 0; vertical-align: middle; text-align: left; padding: 8px 12px; font-weight: normal; padding-bottom: 5px; padding-left: 0; padding-top: 24px; border-top-width: 4px;" align="left">
							Subtotal: 						</th>
						<td class="td text-align-right" style="color: #414141; border: 0; vertical-align: middle; text-align: right; padding: 8px 12px; font-weight: normal; padding-bottom: 5px; padding-right: 0; padding-top: 24px; border-top-width: 4px;" align="right"><span class="woocommerce-Price-amount amount"><span class="woocommerce-Price-currencySymbol">$</span>70.00</span></td>
					</tr>
										<tr class="order-totals order-totals-discount">
						<th class="td text-align-left" scope="row" colspan="2" style="color: #414141; border: 0; vertical-align: middle; text-align: left; padding: 8px 12px; font-weight: normal; padding-bottom: 5px; padding-top: 5px; padding-left: 0;" align="left">
							Discount: 						</th>
						<td class="td text-align-right" style="color: #414141; border: 0; vertical-align: middle; text-align: right; padding: 8px 12px; font-weight: normal; padding-bottom: 5px; padding-top: 5px; padding-right: 0;" align="right">-<span class="woocommerce-Price-amount amount"><span class="woocommerce-Price-currencySymbol">$</span>10.00</span>
</td>
					</tr>
										<tr class="order-totals order-totals-shipping">
						<th class="td text-align-left" scope="row" colspan="2" style="color: #414141; border: 0; vertical-align: middle; text-align: left; padding: 8px 12px; font-weight: normal; padding-bottom: 5px; padding-top: 5px; padding-left: 0;" align="left">
							Shipping: Flat rate						</th>
						<td class="td text-align-right" style="color: #414141; border: 0; vertical-align: middle; text-align: right; padding: 8px 12px; font-weight: normal; padding-bottom: 5px; padding-top: 5px; padding-right: 0;" align="right"><span class="woocommerce-Price-amount amount"><span class="woocommerce-Price-currencySymbol">$</span>5.00</span></td>
					</tr>
										<tr class="order-totals order-totals-total">
						<th class="td text-align-left" scope="row" colspan="2" style="color: #414141; border: 0; vertical-align: middle; text-align: left; padding: 8px 12px; padding-bottom: 5px; padding-top: 5px; font-weight: bold; padding-left: 0;" align="left">
							Total: 						</th>
						<td class="td text-align-right" style="color: #414141; border: 0; vertical-align: middle; text-align: right; padding: 8px 12px; padding-bottom: 5px; padding-top: 5px; font-weight: bold; font-size: 20px; padding-right: 0;" align="right"><span class="woocommerce-Price-amount amount"><span class="woocommerce-Price-currencySymbol">$</span>65.00</span></td>
					</tr>
										<tr class="order-totals order-totals-payment_method order-totals-last">
						<th class="td text-align-left" scope="row" colspan="2" style="color: #414141; border: 0; vertical-align: middle; text-align: left; padding: 8px 12px; font-weight: normal; padding-top: 5px; border-bottom: 1px solid rgba(0,0,0,.2); padding-bottom: 24px; padding-left: 0;" align="left">
							Payment method: 						</th>
						<td class="td text-align-right" style="color: #414141; border: 0; vertical-align: middle; text-align: right; padding: 8px 12px; font-weight: normal; padding-top: 5px; border-bottom: 1px solid rgba(0,0,0,.2); padding-bottom: 24px; padding-right: 0;" align="right">Direct bank transfer</td>
					</tr>
									<tr class="order-customer-note">
					<td class="td text-align-left" colspan="3" style="color: #414141; border: 0; vertical-align: middle; text-align: left; padding: 8px 12px; border-bottom: 1px solid rgba(0,0,0,.2); padding-bottom: 24px; padding-top: 24px; padding-left: 0; padding-right: 0;" align="left">
						<b>Customer note</b><br>
						This is a customer note. Customers can add a note to their order on checkout.<br>
<br>
It can be multiple lines. If there’s no note, this section is hidden.					</td>
				</tr>
						</tfoot>
	</table>
</div>

<table id="addresses" cellspacing="0" cellpadding="0" border="0" style="width: 100%; vertical-align: top; margin-bottom: 0; padding: 0;" width="100%">
	<tbody><tr>
		<td class="font-family text-align-left" valign="top" width="50%" style="font-family: &quot;Helvetica Neue&quot;,Helvetica,Roboto,Arial,sans-serif; text-align: left; border: 0; padding: 0;" align="left">
							<b class="address-title" style="color: #111; font-family: &quot;Helvetica Neue&quot;,Helvetica,Roboto,Arial,sans-serif;">Billing address</b>
			
			<address class="address" style="color: #111; font-style: normal; padding: 8px 0; word-break: break-all;">
				John Doe<br>Company<br>123 Fake Street<br>Faketown, CA 12345<br>United States (US)									<br><a target="_blank" href="tel:5555555555" style="color: #111; font-weight: normal; text-decoration: underline;">555-555-5555</a>													<br>john@company.com											</address>
		</td>
					<td class="font-family text-align-left" valign="top" width="50%" style="font-family: &quot;Helvetica Neue&quot;,Helvetica,Roboto,Arial,sans-serif; text-align: left; padding: 0; padding-left: 10px;" align="left">
									<b class="address-title" style="color: #111; font-family: &quot;Helvetica Neue&quot;,Helvetica,Roboto,Arial,sans-serif;">Shipping address</b>
				
				<address class="address" style="color: #111; font-style: normal; padding: 8px 0; word-break: break-all;">
					John Doe<br>Company<br>123 Fake Street<br>Faketown, CA 12345<br>United States (US)											<br><a target="_blank" href="tel:5555555555" style="color: #111; font-weight: normal; text-decoration: underline;">555-555-5555</a>														</address>
			</td>
			</tr>
</tbody></table>
<br><table border="0" cellpadding="0" cellspacing="0" width="100%"><tbody><tr><td class="email-additional-content" style="color: #111; font-family: &quot;Helvetica Neue&quot;,Helvetica,Roboto,Arial,sans-serif; padding: 32px 0 0;">
<p style="text-align: center; margin: 0 0 16px;" align="center">Congratulations on the sale!</p>
</td></tr></tbody></table>Process your orders on the go. <a target="_blank" href="https://woocommerce.com/mobile?blog_id=0&amp;utm_campaign=deeplinks_promote_app&amp;utm_medium=email&amp;utm_source=steady-starling-concrete.ngrok-free.app&amp;utm_term=0" style="color: #111; font-weight: normal; text-decoration: underline;">Get the app</a>.																		</div>
																	</td>
																</tr>
															</tbody></table>
															<!-- End Content -->
														</td>
													</tr>
												</tbody></table>
												<!-- End Body -->
											</td>
										</tr>
									</tbody></table>
								</td>
							</tr>
							<tr>
								<td align="center" valign="top">
									<!-- Footer -->
									<table border="0" cellpadding="10" cellspacing="0" width="100%" id="template_footer">
										<tbody><tr>
											<td valign="top" style="padding: 0; border-radius: 0;">
												<table border="0" cellpadding="10" cellspacing="0" width="100%">
													<tbody><tr>
														<td colspan="2" valign="middle" id="credit" style="border-radius: 0; border: 0; border-top: 1px solid rgba(0,0,0,.2); font-family: &quot;Helvetica Neue&quot;,Helvetica,Roboto,Arial,sans-serif; font-size: 12px; line-height: 140%; text-align: center; padding: 32px; color: #787c82;" align="center">
															<p style="margin: 0;">Pre-orders (AUD) — Built with <a target="_blank" href="https://woocommerce.com" style="font-weight: normal; text-decoration: underline; color: #787c82;">WooCommerce</a></p>
														</td>
													</tr>
												</tbody></table>
											</td>
										</tr>
									</tbody></table>
									<!-- End Footer -->
								</td>
							</tr>
						</tbody></table>
					</div>
				</td>
				<td><!-- Deliberately empty to support consistent sizing and layout across multiple email clients. --></td>
			</tr>
		</tbody></table>
```

</details>

### WordPress Environment

<details>

<summary>WordPress Environment</summary>

<details><summary>System Status Report</summary>

```
### WordPress Environment ###

WordPress address (URL): [Redacted]
Site address (URL): [Redacted]
WC Version: 10.1.0
Legacy REST API Package Version: The Legacy REST API plugin is not installed on this site.
Action Scheduler Version: ✔ 3.9.3
Log Directory Writable: ✔
WP Version: 6.9-alpha-60643
WP Multisite: ✔
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: –
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.18.0
Server Architecture: Linux 5.15.0-92-generic aarch64
PHP Version: 8.3.20
PHP Post Max Size: 2 GB
PHP Time Limit: 900
PHP Max Input Vars: 1000
cURL Version: 7.81.0
OpenSSL/3.0.2

SUHOSIN Installed: –
MySQL Version: 8.0.36-0ubuntu0.22.04.1
Max Upload Size: 0 B
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

[REDACTED]

### Post Type Counts ###

attachment: 9
page: 6
post: 2
product: 3
shop_order_placehold: 13
wp_navigation: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (6) ###

Airplane Mode: by Andrew Norcross – 0.2.5
Query Monitor: by John Blackbourn – 3.19.0
User Switching: by John Blackbourn – 1.10.0
WooCommerce Dummy Payments Gateway: by Woo – 1.10.0
WooCommerce Pre-Orders: by WooCommerce – 2.2.9
WooCommerce: by Automattic – 10.1.0

### Inactive Plugins (21) ###

Braintree for WooCommerce Payment Gateway: by WooCommerce – 3.2.9
Google for WooCommerce: by WooCommerce – 3.3.1
Loco Translate: by Tim Whitlock – 2.8.0
WooCommerce Accommodation Bookings: by WooCommerce – 1.3.4
WooCommerce Bookings: by WooCommerce – 2.2.8
WooCommerce Bookings Availability: by WooCommerce – 1.3.0
WooCommerce Box Office: by WooCommerce – 1.3.6
WooCommerce Bulk Stock Management: by WooCommerce – 2.3.0
WooCommerce Deposits: by WooCommerce – 2.4.0
WooCommerce EU VAT Number: by WooCommerce – 2.9.16
WooCommerce Payfast Gateway: by WooCommerce – 1.7.3
WooCommerce Product Bundles: by Woo – 8.4.2
WooCommerce Product CSV Import Suite: by WooCommerce – 1.10.78
WooCommerce Product Vendors: by WooCommerce – 2.4.6
WooCommerce Purchase Order Payment Gateway: by WooCommerce – 1.5.4
WooCommerce Square: by WooCommerce – 4.9.7
WooCommerce Stripe Gateway: by Stripe – 9.8.0
WooCommerce Subscriptions: by WooCommerce – 7.5.0
WooCommerce Xero Integration: by WooCommerce – 1.9.6
WooPayments: by WooCommerce – 9.8.0
WP Dev Tools: by Peter Wilson – 1.0.0

### Dropin Plugins () ###

db.php: Query Monitor Database Class (Drop-in)

### Must Use Plugins (16) ###

add-site-id-to-admin-menu.php: by  –
Cavalcade-loader.php: by  –
deposits-cart-stuff.php: by  –
filter-bookings-my-account-endpoint.php: by  –
more-products-per-page.php: by  –
no-ssl.php: by  –
pre-orders-fast-schedule.php: by  –
Preload options used by Woo that do not use autoload.: by  –
Rapid Deposits.: by  –
rewrite-apple-pay.php: by  –
Unique order IDs: by  –
wpcli-dev-commands.php: by  –
Xero - Mock API Rate Limiting: by  –
_init-as-live-store.php: by  –
_no-log-doing-wrong-i18n.php: by  –
_qm-mappings.php: by  –

### Settings ###

Legacy API Enabled: –
Force SSL: –
Currency: AUD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –
Enabled Features: analytics
marketplace
order_attribution
site_visibility_badge
remote_logging
email_improvements
blueprint
point_of_sale
custom_order_tables


### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 379 B

### WC Pages ###

Shop base: #5 - /shop/
Cart: #26 - /cart/ -  Contains the woocommerce/classic-shortcode block
Checkout: #27 - /checkout/ -  Contains the woocommerce/classic-shortcode block
My account: #8 - /my-account/ -  Contains the [woocommerce_my_account] shortcode
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty-Five
Version: 1.3
Author URL: https://wordpress.org
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
Theme type: Block theme
WooCommerce Support: ❌ Not declared

### Templates ###

Overrides: /vagrant/content/plugins/woocommerce/templates/block-notices/error.php
/vagrant/content/plugins/woocommerce/templates/block-notices/notice.php
/vagrant/content/plugins/woocommerce/templates/block-notices/success.php


### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
onboarding
onboarding-tasks
pattern-toolkit-full-composability
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
printful
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page
launch-your-store
add-to-cart-with-options-stepper-layout

Disabled Features: product-data-views
experimental-blocks
experimental-iapi-mini-cart
experimental-iapi-runtime
coming-soon-newsletter-template
minified-js
product-pre-publish-modal
settings
async-product-editor-category-field
product-editor-template-system
use-wp-horizon
experimental-wc-rest-api

Daily Cron: ✔ Next scheduled: 2025-08-18 01:24:27 +00:00
Options: ✔
Notes: 73
Onboarding: completed

### Action Scheduler ###

Complete: 5
Oldest: 2025-12-03 00:00:14 +0000
Newest: 2025-08-18 00:50:45 +0000

Failed: 1
Oldest: 2025-05-30 01:05:20 +0000
Newest: 2025-05-30 01:05:20 +0000

Pending: 3
Oldest: 2025-08-19 00:39:46 +0000
Newest: 2025-12-03 12:00:14 +0000


### Status report information ###

Generated at: 2025-08-18 01:03:23 +00:00
```
</details>

</details>

### Isolating the problem

- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by peterwilsoncc**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Modifies the email templates to add `role="presentation"` to table elements used for layout purposes. In the accessibility tree, this sets the nodes to "generic" rather than "table", removing incorrect information for users of assistive technology.

Closes #60410.
Closes https://linear.app/a8c/issue/WOO10UP-29/tracking-issue-for-accessibility-email-tables

### How to test the changes in this Pull Request:

This pull request changes the HTML markup in all the emails generated by WooCommerce Core and any extensions making use of the actions for generating the HTML emails (which is most extensions in my experience).

These emails can be found listed on `/wp-admin/admin.php?page=wc-settings&tab=email`.

The HTML markup for emails should be checked both with and without "Email improvements" enabled, see `/wp-admin/admin.php?page=wc-settings&tab=advanced&section=features`

Firefox makes it easier to open an iframe in it's own tab, so I suggest you use that.

1. Navigate to emails, `/wp-admin/admin.php?page=wc-settings&tab=email`
2. Select the first email in the dropdown list for previewing emails. Screenshot 2025-09-10 at 12 06 43 pm
3. Once the preview loads in the iframe, in Firefox you can right click on the email select "This frame > Open Frame in new tab".
4. In the browser console, run `$$( 'table:not([role="presentation"])')` (works in both Chrome and Firefox)
5. Ensure that each of the elements listed are tables containing table data. In both Chrome and Firefox you can click on each list in the items returned.
   In most emails, this should be two items: the order details (listing each product) and the order summary (ie, subtotal, etc)
6. In the browser console run `$$( 'table[role="presentation"]')` to list tables that have had their semantic role removed
7. Ensure that each of the elements listed are NOT tables containing presentational table data.

### Testing that has already taken place:

Above with a sub-section of the emails: New order, processing, new account with email improvements enabled and disabled.

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [x] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

Improve accessibility of emails by setting the aria-role of layout tables to presentation.

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce/templates/emails/email-downloads.php [hunk 1]
```diff
@@ -43,7 +43,7 @@ class="td font-family<?php echo $email_improvements_enabled ? ' email-order-deta
 	<?php foreach ( $downloads as $download ) : ?>
 		<tr>
 			<?php foreach ( $columns as $column_id => $column_name ) : ?>
-				<td class="td <?php echo $email_improvements_enabled && array_key_last( $columns ) === $column_id ? 'text-align-right' : 'text-align-left'; ?>">
+				<<?php echo 'download-product' === $column_id ? 'th scope="row"' : 'td'; ?> class="td <?php echo $email_improvements_enabled && array_key_last( $columns ) === $column_id ? 'text-align-right' : 'text-align-left'; ?>">
```
Comment (peterwilsoncc) [inline plugins/woocommerce/templates/emails/email-downloads.php]: I don't really like this, however the code needs something like this to account for the `woocommerce_email_downloads_columns` filter adding or removing columns.

**Review by dkotter — COMMENTED** [review]
Code looks good to me.

One question though: since we're updating a bunch of templates, do we need to update the `@version` property in those? I know that's typically the process but not sure if there's a reason we didn't update those here.

**Comment by peterwilsoncc** [comment]
@dkotter Yep, I forgot about that. The version bump is usually to the version for WooCommerce in which the change was released so I'll set it to 10.3 given 10.2 is currently in the beta period.

**Review by dkotter — COMMENTED** [review]
Looks good to me 👍🏻 

@qasumitbagthariya @ankitguptaindia This is ready for QA

**Comment by qasumitbagthariya** [comment]
### QA/Test Report ✅ 
-------------

I have checked this PR in the `peterwilsoncc:fix/60410-a11y-email-template-presentational-tables` branch and changes working as expected.

1. $$('table:not([role="presentation"])') 
 It returned 5 elements (different <table class="form-table">) ✅

2. $$('table[role="presentation"]') 
 It returned an empty array ([]) ✅

image


**Testing Environment** 

<Details>

- WordPress: 6.8.1
- Theme: Storefront 4.6.0
- WooCommerce - WooCommerce - Dev version with this fix specific branch.
- PHP: 8.0.30
- Web Server: Nginx 1.20.2
- Browser: Chrome 
- OS: macOS  15.2 
- Git Branch: peterwilsoncc:fix/60410-a11y-email-template-presentational-tables

</Details>


Please Un-draft this PR for the next step.

cc @vikrampm1

File: plugins/woocommerce/templates/emails/email-order-details.php [hunk 2]
```diff
@@ -95,52 +93,52 @@
...
 				<?php
 			}
+		}
+		if ( $order->get_customer_note() && ! $email_improvements_enabled ) {
 			?>
-		</tfoot>
+			<tr>
+				<th class="td text-align-left" scope="row" colspan="2"><?php esc_html_e( 'Note:', 'woocommerce' ); ?></th>
+				<td class="td text-align-left"><?php echo wp_kses( nl2br( wc_wptexturize_order_note( $order->get_customer_note() ) ), array() ); ?></td>
+			</tr>
```
[the remark this answers is not in the document]
Comment (peterwilsoncc) [reply plugins/woocommerce/templates/emails/email-order-details.php:128]: This is intended as it is currently the case in `trunk`. If this is to be changed it should be done in a dedicated issue rather than this one.

Code from trunk:

https://github.com/woocommerce/woocommerce/blob/a98958e2d78f6168ad238b6af7e96c85048a23c1/plugins/woocommerce/templates/emails/email-order-details.php#L123-L130

**Comment by peterwilsoncc** [comment]
> ❌ Failed checks (2 warnings)

Each of the items highlighted in this section were discussed with Amber in the comment thread of the linked issue.

**Comment by jeffpaul** [comment]
@woocommerce/rubik tagging you for your review here. Please re-assign if this should be reviewed by another team instead. Thanks!

**Comment by jeffpaul** [comment]
@jamesckemp I don't seem to be able to @mention Woo teams, so can you help ensure this gets routed for review/merging?

**Comment by jeffpaul** [comment]
@peterwilsoncc is there more work needed here or is this awaiting Woo review?

**Comment by peterwilsoncc** [comment]
@jeffpaul All done and just waiting on a review. I've just rebased against trunk to help ensure it doesn't get conflicted.

**Comment by vikrampm1** [comment]
@PanosSynetos could you help review this PR or route it to someone at Woo who can assist with the review? Thanks.

**Comment by PanosSynetos** [comment]
Sure thing, @vikrampm1 - Tagging @NeosinneR to have a go at it and review the PR.

**Comment by NeosinneR** [comment]
Hi @peterwilsoncc, I plan to review the PR tomorrow, but a quick initial review based on the CI:
1. As WooCommerce 10.3.0 was released today, the `@version` in templates will need to be updated to `10.4.0` (the CI job will fail anyway, but we can work around that). 
2. There are some [lint errors](https://github.com/woocommerce/woocommerce/actions/runs/18673274271/job/53427055200?pr=60447). 

Thank you 🙇‍♂️

File: plugins/woocommerce/templates/emails/email-order-details.php [hunk 3]
```diff
@@ -95,52 +93,52 @@
...
+			<?php
+		}
+		?>
 	</table>
```
[the remark this answers is not in the document]
Comment (peterwilsoncc) [reply plugins/woocommerce/templates/emails/email-order-details.php:132]: Table split upon a11y advice from Amber, see https://github.com/woocommerce/woocommerce/issues/60410#issuecomment-3208303504 and https://github.com/woocommerce/woocommerce/issues/60410#issuecomment-3268836938

**Comment by peterwilsoncc** [comment]
Thanks @NeosinneR, I've bumped the template versions to 10.4, fixed the CS issues and addressed an alignment issue the bot picked up.

File: plugins/woocommerce/templates/emails/email-order-items.php [hunk 4]
```diff
@@ -68,7 +68,7 @@
 							 * @param WC_Order_Item_Product $item      The item being displayed.
 							 * @since 2.1.0
 							 */
-							echo wp_kses_post( apply_filters( 'woocommerce_order_item_name', $item->get_name(), $item, false ) );
+							echo wp_kses_post( apply_filters( 'woocommerce_order_item_name', "<h3 style='font-size: inherit;'>" . $item->get_name() . '</h3>', $item, false ) );
```
Comment (NeosinneR) [inline plugins/woocommerce/templates/emails/email-order-items.php]: The `'woocommerce_order_item_name'` filter should receive only the name, without any HTML markup (which should be extracted outside of filter). It's used around the codebase and needs to be consistent in what argument is passed. And to keep the font style the same, please also add `font-weight: inherit;` otherwise header is bold by default.

File: plugins/woocommerce/templates/emails/email-order-details.php [hunk 5]
```diff
@@ -71,15 +71,13 @@
 
 <div style="margin-bottom: <?php echo $email_improvements_enabled ? '24px' : '40px'; ?>;">
 	<table class="td font-family <?php echo esc_attr( $order_table_class ); ?>" cellspacing="0" cellpadding="6" style="width: 100%;" border="1">
-		<?php if ( ! $email_improvements_enabled ) { ?>
 		<thead>
 			<tr>
 				<th class="td" scope="col" style="text-align:<?php echo esc_attr( $text_align ); ?>;"><?php esc_html_e( 'Product', 'woocommerce' ); ?></th>
 				<th class="td" scope="col" style="text-align:<?php echo esc_attr( $text_align ); ?>;"><?php esc_html_e( 'Quantity', 'woocommerce' ); ?></th>
```
Comment (NeosinneR) [inline plugins/woocommerce/templates/emails/email-order-details.php]: Quantity should also be aligned right 

Image

File: plugins/woocommerce/templates/emails/email-downloads.php (hunk 1 above)
Comment (NeosinneR) [reply plugins/woocommerce/templates/emails/email-downloads.php]: Yeah, agree that this is not ideal, as it also breaks highlighting or linting in IDEs. Even if more verbose and a bit duplicated, I'd go with 
```php
	<?php if ( 'download-product' === $column_id ) : ?>
		<th scope="row" class="td <?php echo $email_improvements_enabled && array_key_last( $columns ) === $column_id ? 'text-align-right' : 'text-align-left'; ?>">
	<?php else : ?>
		<td class="td <?php echo $email_improvements_enabled && array_key_last( $columns ) === $column_id ? 'text-align-right' : 'text-align-left'; ?>">
	<?php endif; ?>
```

and 
```php
	<?php if ( 'download-product' === $column_id ) : ?>
		</th>
	<?php else : ?>
		</td>
	<?php endif; ?>
```

**Review by NeosinneR — CHANGES_REQUESTED** [review]
Looks good overall, thanks for the changes @peterwilsoncc. Below I share a couple of notes I noticed to maintain existing styling and backwards compatibility:

**Comment by peterwilsoncc** [comment]
Thank @NeosinneR, I've made those changes in 56c2ae3fa8eee70588c4e596534db6894225290b, 69b15692e140aef6ff4e41f19edb3fc627644708 and 323abeb6ed4ff3bf9b8b586f88525d4104595d01 respectively.

For the final change, I altered your suggestion slightly to calculate the first table cell/header's class on a separate line at the start of the loop as I felt it made the code a little clearer. 

The [Analyze Branch Changes action failed](https://github.com/woocommerce/woocommerce/actions/runs/18734923883/job/53492621425?pr=60447) when you allowed them to run. I suspect a permission error because I am working from a fork.

File: plugins/woocommerce/templates/emails/email-order-details.php [hunk 6]
```diff
@@ -25,6 +25,7 @@
 $heading_class              = $email_improvements_enabled ? 'email-order-detail-heading' : '';
 $order_table_class          = $email_improvements_enabled ? 'email-order-details' : '';
 $order_total_text_align     = $email_improvements_enabled ? 'right' : 'left';
+$order_quantity_text_align  = $email_improvements_enabled ? 'right' : 'left';
```
[the remark this answers is not in the document]
Comment (peterwilsoncc) [reply plugins/woocommerce/templates/emails/email-order-details.php:28]: N/A

These classes are used in trunk for the columns based on the value of `$email_improvements_enabled`. Although they use `-left` and `-right`, the alignment is reversed on the `RTL` style sheets generated as part of the build process.

Testing method: used English but hardcoded `is_rtl()` to return `true` in order to load the style sheets.

**Comment by NeosinneR** [comment]
@peterwilsoncc thanks for the changes. There are some [lint errors](https://github.com/woocommerce/woocommerce/actions/runs/18763137441/job/53555271882?pr=60447), otherwise the PR looks good. Will approve and merge once those are fixed.

**Comment by peterwilsoncc** [comment]
@NeosinneR I think I have them fixed.

**Review by NeosinneR — APPROVED** [review]
Thanks for the fixes @peterwilsoncc. The changes look good to me now.
