### PR TITLE
Fix shortcode cart table and update a th to td

### LINKED ISSUE #59887: Cart Product Label missing on mobile after WooCommerce update
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

After updating WooCommerce from 9.8.5 to 10.0.3, the "Produit" label from data-title="Produit" in the cart is no longer displayed on mobile. As a result, customers see a list of product details without knowing which product each line refers to.

Previously, the product name was inside a `<td class="product-name" data-title="Produit">`, but after the update it’s rendered as `<th class="product-name" data-title="Produit">`.

It seems the CSS or responsive behavior showing the data-title label only applies to `<td>`, not `<th>`.

If I change via the inspector `<th>` to `<td>` then it works again

Image
Image

Note:
I tried rolling back to WooCommerce 9.9.5 and this fixed the problem — the label displays correctly again.

### Expected behavior

On mobile, the Product label should be displayed before the product name, making it clear which product each cart item refers to.

### Actual behavior

The Product label is missing on mobile, so customers only see product details (like quantity and price) without knowing which product they correspond to.

### Steps to reproduce

1. Fresh install of WordPress.
2. Install the Hello theme or StoreFront or Astra or....
3. Install WooCommerce (last version).
4. Install Elementor.
5. Install Elementor Pro (with license activated).
6. Edit the Cart page with Elementor.
7. Remove all existing content.
8. Add the WooCommerce Pages widget and select Cart.
9. Go to the Shop page, add a product to the cart.
10. Resize the browser window (or use a mobile device) to a width under 768px.

→ The issue appears: the "Produit" label (data-title="Produit") is missing from the cart, making product identification unclear on mobile.

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): http://davidt764.sg-host.com
Site address (URL): http://davidt764.sg-host.com
WC Version: 10.0.3
Legacy REST API Package Version: The Legacy REST API plugin is not installed on this site.
Action Scheduler Version: ✔ 3.9.2
Log Directory Writable: ✔
WP Version: 6.8.2
WP Multisite: –
WP Memory Limit: 768 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
Server Architecture: Linux 6.6.63-MCIclouder663-c9 x86_64
PHP Version: 8.2.29
PHP Post Max Size: 256 MB
PHP Time Limit: 120
PHP Max Input Vars: 3000
cURL Version: 8.9.1
OpenSSL/3.2.4

SUHOSIN Installed: –
MySQL Version: 8.0.41-32
Max Upload Size: 256 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 10.0.3
WC Database Prefix: tri_
Total Database Size: 5.12MB
Database Data Size: 2.76MB
Database Index Size: 2.36MB
tri_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
tri_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
tri_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
tri_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
tri_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
tri_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
tri_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
tri_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
tri_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
tri_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
tri_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
tri_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
tri_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
tri_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
tri_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
tri_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
tri_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
tri_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
tri_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
tri_comments: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
tri_e_events: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
tri_e_notes: Data: 0.02MB + Index: 0.17MB + Engine InnoDB
tri_e_notes_users_relations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
tri_e_submissions: Data: 0.02MB + Index: 0.23MB + Engine InnoDB
tri_e_submissions_actions_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
tri_e_submissions_values: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
tri_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
tri_options: Data: 1.45MB + Index: 0.06MB + Engine InnoDB
tri_postmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
tri_posts: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
tri_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
tri_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
tri_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
tri_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
tri_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
tri_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
tri_wc_admin_note_actions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
tri_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
tri_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
tri_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
tri_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
tri_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
tri_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
tri_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
tri_wc_order_product_lookup: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
tri_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
tri_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
tri_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
tri_wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
tri_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
tri_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
tri_wc_product_meta_lookup: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
tri_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
tri_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
tri_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
tri_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
tri_yoast_indexable: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
tri_yoast_indexable_hierarchy: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
tri_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
tri_yoast_primary_term: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
tri_yoast_seo_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 2
elementor_library: 2
page: 9
post: 2
product: 2
revision: 10
shop_order_placehold: 1
wp_global_styles: 1
wp_navigation: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (4) ###

Classic Editor: by WordPress Contributors – 1.6.7
Elementor Pro: by Elementor.com – 3.30.0
Elementor: by Elementor.com – 3.30.2
WooCommerce: by Automattic – 10.0.3

### Inactive Plugins (8) ###

Advanced Order Export For WooCommerce: by AlgolPlus – 4.0.3
Temporary Login: by Elementor.com – 1.3.0
WooCommerce Multilingual & Multicurrency: by OnTheGoSystems – 5.3.8
WooCommerce Stripe Gateway: by Stripe – 9.6.0
WPML Media Translation: by OnTheGoSystems – 2.7.5
WPML SEO: by OnTheGoSystems – 2.1.1
WPML String Translation: by OnTheGoSystems – 3.2.18
Yoast SEO: by Team Yoast – 25.5

### Settings ###

Legacy API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –
Enabled Features: analytics
marketplace
order_attribution
site_visibility_badge
remote_logging
email_improvements
blueprint
point_of_sale
custom_order_tables

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 449 B

### WC Pages ###

Shop base: #7 - /shop/
Cart: #8 - /cart/ -  Contains the woocommerce_cart shortcode
Checkout: #9 - /checkout/ -  Contains the woocommerce/checkout block
My account: #10 - /my-account/ -  Contains the [woocommerce_my_account] shortcode
Terms and conditions: ❌ Page not set

### Theme ###

Name: Hello Elementor
Version: 3.4.4
Author URL: https://elementor.com/?utm_source=wp-themes&utm_campaign=author-uri&utm_medium=wp-dash
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
Theme type: Classic theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
onboarding
onboarding-tasks
pattern-toolkit-full-composability
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
printful
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page
launch-your-store
add-to-cart-with-options-stepper-layout

Disabled Features: product-data-views
experimental-blocks
experimental-iapi-mini-cart
experimental-iapi-runtime
coming-soon-newsletter-template
minified-js
product-pre-publish-modal
settings
async-product-editor-category-field
product-editor-template-system
use-wp-horizon

Daily Cron: ✔ Next scheduled: 2025-07-23 05:42:18 +00:00
Options: ✔
Notes: 64
Onboarding: -

### Action Scheduler ###

Complete: 12
Oldest: 2025-07-22 05:42:21 +0000
Newest: 2025-07-22 13:34:17 +0000

Failed: 1
Oldest: 2025-07-22 05:44:06 +0000
Newest: 2025-07-22 05:44:06 +0000

Pending: 2
Oldest: 2025-07-22 17:42:20 +0000
Newest: 2025-07-23 05:42:21 +0000

### Status report information ###

Generated at: 2025-07-22 14:16:28 +00:00
`

### Isolating the problem

- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

### LINKED ISSUE #59951: Recent td-to-th change #57883 (cart.php) altered CSS applied to cart details for add-ons and more
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

In cart.php, #57883 changed the ``<td>`` for "product-name" to ``<th>``, causing changes in CSS applied.  So now, for example, if you have add-ons shown in the order details, everything might be in bold, and the quantity (input-multiplier) values might be on the next line.  But the problem doesn't require add-ons;  at a minimum, any product might be bold, suddenly.

While the PR said this td-to-th change was intentional, it doesn't seem like it, since the other td cells were not changed to th, as well.

Temporary workaround is to add the pre-changed version of cart.php to the theme.

### Expected behavior

```
MyProduct
A:  5
B:  1
```

### Actual behavior

(and imagine in bold):
```
MyProduct
A:
   5
B:
   1
```

### Steps to reproduce

1.  Use product with add-ons or variation or really anything, since the issue affects any order details.
2.  Add to cart, and view cart.

### WordPress Environment

Happens on any environment.

### Isolating the problem

- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by PanosSynetos**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

In PR #57883 we improved the accessibility of the cart table, by introducing scoped headers. One of the `td` inside a `tbody/tr` was changed to a `th` , causing semantic issues.

With this PR, we keep the `scope="row"` that was added but change the `th` to a `td`.

Accessibility should function as expected.

This also fixes a visual regression, as reported by @eja2025

Closes #59951 
Closes #59887

- #59951
- #59887

(For Bug Fixes) Bug introduced in PR #57883 .
- #57883

### Screenshots or screen recordings:

| Before | After |
| ------ | ----- |
|    image    |   image    |

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Add a variable product to your cart
2. Navigate to a cart page rendered via the [woocommerce_cart] shortcode.
3. Visual regression should be solved, and `dl` should be rendered properly

I'll invite @amberhinds to also test this one, in case it breaks accessibility. Accoding to my research, this should't affect a11y.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

**Comment by PanosSynetos** [comment]
@coderabbitai full review

**Review by opr — CHANGES_REQUESTED** [review]
Hi @PanosSynetos I think this is better than my proposed fix however the original PR introduced a `th` for accessibility reasons, and by reverting it to a `td` then the product name is not read when moving through rows. I suggested a change inline that should resolve the issue while keeping the `td` 👏🏼

File: plugins/woocommerce/templates/cart/cart.php [hunk 1]
```diff
@@ -97,7 +97,7 @@
 						?>
 						</td>
 
-						<th scope="row" class="product-name" data-title="<?php esc_attr_e( 'Product', 'woocommerce' ); ?>">
+						<td scope="row" class="product-name" data-title="<?php esc_attr_e( 'Product', 'woocommerce' ); ?>">
```
Comment (opr) [inline plugins/woocommerce/templates/cart/cart.php]: If we add `role="rowheader"` to this it will be picked up by screen readers

**Comment by PanosSynetos** [comment]
@opr thanks for the review and the suggestion. Can you please check the voice-over? I'm still not able to move through rows, instead it scrolls up and down on my machine

**Comment by opr** [comment]
> @opr thanks for the review and the suggestion. Can you please check the voice-over? I'm still not able to move through rows, instead it scrolls up and down on my machine

I just tested and it's working ok for me! Thanks @PanosSynetos

**Comment by PanosSynetos** [comment]
I'll go ahead and merge this, and backport it to `10.1.0`

**Review by opr — APPROVED** [review]
Tested with screen-reader and it works OK, tested on mobile and desktop in Edge, Safari, and Firefox. Looking good, thanks Panos!

**Comment by amberhinds** [comment]
RE:
>With this PR, we keep the scope="row" that was added but change the th to a td.

Putting and `scope="row"` on a td does not make it read as a header. You have to use a `<th>` tag to make it announce as a header.

**Comment by PanosSynetos** [comment]
Hey @amberhinds - The fix was not well thought and just changing the `td` to a `th` caused issues with product titles getting hidden on the classic cart.

- https://github.com/woocommerce/woocommerce/issues/60039
- https://github.com/woocommerce/woocommerce/issues/59951
- https://github.com/woocommerce/woocommerce/issues/59887

We already have several reports of this issue, so the short term solution is to revert it back to a `td` and see for a proper solution. Also, I'd like to note that changing this from a `td` to a `th` will break several themes.

What other alternatives do we have Amber? cc @opr @jamesckemp

**Comment by PanosSynetos** [comment]
And @amberhinds , it's not just scope="row" , this is what we added `<td scope="row" role="rowheader" ` and @opr verified that it works and it's announced. @opr can you share a screencast?

**Comment by opr** [comment]
https://www.loom.com/share/7ae7a5942e934730b0b4c25dae7be7d0 you can't see in the video but I'm using ctrl + option + arrow keys to move through the table, you can hear voiceover announce the product name when moving between rows

**Comment by amberhinds** [comment]
Setting `role="rowheader"` works. Sorry, I missed that it was done in a follow-up comment. I was going through notifications during a down moment on vacation and read them out of order. Thank you.

**Comment by PanosSynetos** [comment]
Awesome ;) That's relieving! Thanks Amber!

**Comment by JimmyAppelt** [comment]
@PanosSynetos 

It seems `scope` on `td` is deprecated https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/td#scope
