### PR TITLE
Fix incorrect product data displayed in Product Collection in context of Single Product block

### LINKED ISSUE #43991: Product Collection displays content from Single Product block when used in Single Product block
**Steps to reproduce:**
1. Go to Editor
2. Add Single Product block
3. Choose some product
4. Inside Single Product block add Product Collection block

**Expected:**
- All products in Product Collection display their own images and prices

**Actual:**
- All products in Product Collection display image from product set in Single Product block
- All products in Product Collection display price of product set in Single Product block

image

### PR DESCRIPTION
**Pull request by kmanijak**
The initial approach is more like POC. Unfortunately, it has an impact on the performance so won't be a way.

### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Product Collection (or more technically Product Template) has been using `BlockContextProvider` to pass the product context to nested blocks. This was following the core's Query Loop block.

However, in Blocks world, many blocks are using `ProductDataContextProvider` along with `withProduct` HOC. That includes Single Product block and Product Elements (excluding Product Title and Product Summary that are variations of core blocks).

**Problem:**
The problem was that Product Collection displayed content from Single Product block when used in Single Product block (check Before/After below). This is due to:
- most of Product Elements (e.g. Image, Price) read the `ProductDataContextProvider` set by Single Product parent and wouldn't care about `BlockContextProvider`
- Title read the `BlockContextProvider` set by Product Template and wouldn't care about `ProductDataContextProvider`

**Solution:**
Considering we have inner blocks reacting on two separate contexts we need to pass both of them.

Closes https://github.com/woocommerce/woocommerce/issues/43991

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Create new post
2. Add Product Collection block
3. Choose any collection
4. Expected: Make sure all the products display correct data. Example of incorrect data:
  - "Title" as product name
  - Duplicated images
  - Duplicated prices
5. Focus on different product elements (image, price, title) and make sure there's no blinking or images reloading
6. Add Single Product block
7. Add Product Collection block inside of Single Product block _(note: make sure you're adding it inside some **Column** block. It's forbidden to add any block inside **Columns** block)_
8. Expected: Make sure all the products display correct data. Example of incorrect data:
  - "Title" as product name
  - Duplicated images or images taken from wrapping Single Product block
  - Duplicated prices or prices taken from wrapping Single Product block
9. Focus on different product elements (image, price, title) and make sure there's no blinking or images reloading

Before | After
-- | --
image | image

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce-blocks/assets/js/blocks/product-template/edit.tsx [hunk 1]
```diff
@@ -69,6 +71,48 @@ const ProductTemplateBlockPreview = ( {
...
+		isLoading: boolean;
+		product: ProductResponseItem;
+		displayTemplate: boolean;
+		blocks: BlockInstance[];
+		blockContext: {
+			postType: string;
+			postId: string;
+		};
+		setActiveBlockContextId: ( id: string ) => void;
+	} ) => {
```
Comment (thealexandrelara) [inline plugins/woocommerce-blocks/assets/js/blocks/product-template/edit.tsx]: Since this HOC receives many props, WDYT about putting these typings for the props to its own Interface? Something like:
```ts
interface ProductContentProps {
    attributes: { productId: string };
    ...
}
```

**Review by thealexandrelara — APPROVED** [review]
Great job! I left a comment with a minor improvement proposal, but I'm approving this PR.

✅ All the products are displayed correctly inside the Product Collection (Beta) block
✅ All the products are displayed correctly inside the Product Collection (Beta) block, when the block is included inside the Single Product block.

There are a few things I noticed while testing that I don't think are blockers for this PR, but I wanted to report them to you just in case they haven't been mapped already. I can create separate issues for these if you think it's necessary.

⚠️ During testing, I noticed that when switching the selection between product names, the products in the second row shift slightly. You can see this behavior in the video below.

⚠️ When I select a product name, it appears as a link and the cursor changes to a "pointer," even though the link isn't clickable in the editor. You can see this behavior in the video below.

https://github.com/woocommerce/woocommerce/assets/20469356/c1765894-e0b7-4bfb-a09f-8a746cbde6b2

⚠️ There is no space to the right side of the Product Collection block:
CleanShot 2024-01-31 at 17 13 33@2x

**Comment by kmanijak** [comment]
@thealexandrelara Appreciate the review! I'll double-check if this PR introduces the issues you spotted or if they are already on `trunk`. If the latter, I'll create followup issues not to block this fix.

PS. But great catches! I think we're too biased with @imanish003 by constantly working with this block and don't spot such stuff so really good to have fresh eyes looking at the Product Collection! 😅

**Comment by kmanijak** [comment]
@thealexandrelara, I verified the issues you raised and they all exist in `trunk` so I went ahead and created issues for them:

> During testing, I noticed that when switching the selection between product names, the products in the second row shift slightly. You can see this behavior in the video below.

It's been introduced with https://github.com/woocommerce/woocommerce-blocks/pull/12041/ while I think the original PR didn't account for Product Collection responsiveness which can break block into two rows.
Issue: https://github.com/woocommerce/woocommerce/issues/44253

> When I select a product name, it appears as a link and the cursor changes to a "pointer," even though the link isn't clickable in the editor. You can see this behavior in the video below.

Product Title is a variation of Gutenberg's post title so that would have to be changed upstream. But personally, I'm not sure if that's a bug or not TBH.

> There is no space to the right side of the Product Collection block:

Good spot, issue created: https://github.com/woocommerce/woocommerce/issues/44255

**Comment by thealexandrelara** [comment]
Thank you for creating issues for these. Yeah, after testing, I noticed it wasn't something related to these changes, so thank you for double-checking this. 

> Product Title is a variation of Gutenberg's post title so that would have to be changed upstream. But personally, I'm not sure if that's a bug or not TBH. 

I wonder if we can use the [Disabled component](https://developer.wordpress.org/block-editor/reference-guides/components/disabled/) in this case, WDYT?

**Comment by kmanijak** [comment]
> I wonder if we can use the [Disabled component](https://developer.wordpress.org/block-editor/reference-guides/components/disabled/) in this case, WDYT?

@thealexandrelara , forgot such a component exists! Here's an issue: https://github.com/woocommerce/woocommerce/issues/44277. I may tackle those three soon to relax after heavier stuff! Again, appreciate the attention to detail! 🙌
