### PR TITLE
Fix/37601 Add `aria-describedby` to Select options button

### LINKED ISSUE #37601: Accessibility Improvements ‣ Shop ‣ Action Buttons
As originally noted [over here](https://github.com/woocommerce/woocommerce/issues/24185#issuecomment-779227823), the **Select Options** (variable products) and **Add to Cart** buttons do not have meaningful text.

<div align="center">shop-selectoptions-addtocart</div>

It is proposed we add an `aria-describedby` attribute to these buttons, referencing the corresponding product.

### PR DESCRIPTION
**Pull request by faisal-alvi**
### Submission Review Guidelines:

- I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
- I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
- I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/). 
- Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

* This PR adds a function to get the `aria-describedby` description for the add to cart button.
* Also adds default description for the Select options button.

Closes #37601.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Go to the Shop page.
2. Inspect the button "Select options"
3. Check the `aria-describedby` attribute is added with the value: `"This product has multiple variants. The options may be chosen on the product page"`.

image

### CODE REVIEW

File: plugins/woocommerce/includes/abstracts/abstract-wc-product.php [hunk 1]
```diff
@@ -1932,6 +1932,21 @@ public function single_add_to_cart_text() {
 		return apply_filters( 'woocommerce_product_single_add_to_cart_text', __( 'Add to cart', 'woocommerce' ), $this );
 	}
 
+	/**
+	 * Get the aria-describedby description for the add to cart button.
+	 *
+	 * @return string
+	 */
+	public function aria_describedby_description() {
```
Comment (jorgeatorres) [inline plugins/woocommerce/includes/abstracts/abstract-wc-product.php]: For consistency with the `add_to_cart_text()` and `add_to_cart_description()` functions, I think we should name this `add_to_cart_aria_describedby()` or similar, as it only applies in that context ("add to cart").

File: plugins/woocommerce/includes/abstracts/abstract-wc-product.php [hunk 2]
```diff
@@ -1932,6 +1932,21 @@ public function single_add_to_cart_text() {
...
+		$aria_describedby_description = '';
+
+		if ( 'Select options' === $this->add_to_cart_text() ) {
+			$aria_describedby_description = __( 'This product has multiple variants. The options may be chosen on the product page', 'woocommerce' );
+		}
```
Comment (jorgeatorres) [inline plugins/woocommerce/includes/abstracts/abstract-wc-product.php]: We shouldn't rely on 'Select options' being the text here as that can be translated. Instead, we can override this new method in `WC_Product_Variable` and make it return the string there, as we already do for the `add_to_cart_text()` and `add_to_cart_description()` methods (see below).

https://github.com/woocommerce/woocommerce/blob/722a752a2e586818c275404fd328d9a43b132dba/plugins/woocommerce/includes/class-wc-product-variable.php#L59-L61

https://github.com/woocommerce/woocommerce/blob/722a752a2e586818c275404fd328d9a43b132dba/plugins/woocommerce/includes/class-wc-product-variable.php#L69-L72

File: plugins/woocommerce/includes/abstracts/abstract-wc-product.php [hunk 3]
```diff
@@ -1932,6 +1932,21 @@ public function single_add_to_cart_text() {
...
+
+		return apply_filters( 'woocommerce_product_aria_describedby_description', $aria_describedby_description, $this );
```
Comment (jorgeatorres) [inline plugins/woocommerce/includes/abstracts/abstract-wc-product.php]: Similarly, for consistency the filter should probably be `woocommerce_product_add_to_cart_aria_describedby` or similar.

Also, since this is a new filter, we need to document it with a docblock. See more details in WP's coding standards here: https://developer.wordpress.org/coding-standards/inline-documentation-standards/php/#4-hooks-actions-and-filters.

File: plugins/woocommerce/includes/wc-template-functions.php [hunk 4]
```diff
@@ -1365,12 +1365,19 @@ function woocommerce_template_loop_add_to_cart( $args = array() ) {
...
 					'data-product_sku' => $product->get_sku(),
 					'aria-label'       => $product->add_to_cart_description(),
+					'aria-describedby' => $product->aria_describedby_description(),
 					'rel'              => 'nofollow',
 				),
 			);
 
 			$args = apply_filters( 'woocommerce_loop_add_to_cart_args', wp_parse_args( $args, $defaults ), $product );
 
+			if ( isset( $args['attributes']['aria-describedby'] ) && ! empty( $args['attributes']['aria-describedby'] ) ) {
```
Comment (jorgeatorres) [inline plugins/woocommerce/includes/wc-template-functions.php]: There's no need to check that the key is set with `isset()`. `empty()` already takes care of that.

File: plugins/woocommerce/includes/wc-template-functions.php [hunk 5]
```diff
@@ -1365,12 +1365,19 @@ function woocommerce_template_loop_add_to_cart( $args = array() ) {
...
+				$args['attributes']['aria-describedby'] = wp_strip_all_tags( $args['attributes']['aria-describedby'] );
+			} else {
+				unset( $args['attributes']['aria-describedby'] );
```
Comment (jorgeatorres) [inline plugins/woocommerce/includes/wc-template-functions.php]: Nothing necessarily wrong here, but do we really need to unset the attribute? I'm not that familiar with accessibility issues, but if it does no harm even when empty, then that would simplify this logic a little.

**Review by jorgeatorres — CHANGES_REQUESTED** [review]
Hi @faisal-alvi!

Thanks for your contribution 💯. I tested and while this works when the default "Select options" string is used, it doesn't really work if that string changes (for example, when translated).

I left some comments on how to possibly fix that, as well as some general (though easily solved) feedback.

Please let me know what you think. Looking forward to hearing back from you.

**Comment by faisal-alvi** [comment]
@jorgeatorres thanks for the feedback. The suggestions/changes are implemented. Please check https://github.com/woocommerce/woocommerce/pull/37880/commits/99b5c7e82ad915875f47ae1186b3f5841f291e27 and let me know if any changes are required.

**Review by jorgeatorres — APPROVED** [review]
LGTM. Thank you @faisal-alvi!

(I just made a tiny change to address a PHPCS issue, but other than that, it looked good)
