### PR TITLE
Fix/unsupported operand types

### LINKED ISSUE #31008: Fix Uncaught TypeError: Unsupported operand types: string * float
Please provide us with the information requested in this bug report. Without these details, we won't be able to fully evaluate this issue. 
Bug reports lacking detail, or for any other reason than to report a bug, may be closed without action.

**Prerequisites (mark completed items with an [x]):**
- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
From csv import, I've imported products. In there, I tried to bulk edit with empty sale priced products. I increase 10% regular price and 10% sale price. when I try to save data it gives me Fatal error: Uncaught TypeError: Unsupported operand types: string * float in PATH/wp-content/plugins/woocommerce/includes/admin/class-wc-admin-post-types.php on line 946

**Expected behavior**
It suppose to save data.

**Actual behavior**
A clear and concise description of what actually happens. Please be as descriptive as possible; 

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Go to Products
2. Check on WordPress 0 sale priced product and increase 10% regular price and 10% sale price. Then save it.
3. See an error

**Screenshots**
https://prnt.sc/1wyzz0t
https://prnt.sc/1wyzrwl

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
`
### WordPress Environment ###

WordPress address (URL): http://dokan-app.test
Site address (URL): http://dokan-app.test
WC Version: 5.7.1
REST API Version: ✔ 5.7.1
WC Blocks Version: ✔ 5.7.2
Action Scheduler Version: ✔ 3.2.1
WC Admin Version: ✔ 2.6.5
Log Directory Writable: ✔
WP Version: 5.8.1
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.21.3
PHP Version: 8.0.11
PHP Post Max Size: 512 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.79.1
(SecureTransport) OpenSSL/1.1.1l

SUHOSIN Installed: –
MySQL Version: 8.0.26
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 5.7.1
WC Database Prefix: wp_
Total Database Size: 5.08MB
Database Data Size: 3.44MB
Database Index Size: 1.64MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.06MB + Index: 0.13MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_dokan_announcement: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_dokan_delivery_time: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_dokan_follow_store_followers: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_dokan_orders: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_dokan_product_map: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_dokan_refund: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_dokan_report_abuse_reports: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_dokan_rma_conversations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_dokan_rma_request: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_dokan_rma_request_product: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_dokan_shipping_tracking: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_dokan_shipping_zone_locations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_dokan_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_dokan_vendor_balance: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_dokan_withdraw: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 2.02MB + Index: 0.03MB + Engine InnoDB
wp_postmeta: Data: 0.14MB + Index: 0.09MB + Engine InnoDB
wp_posts: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 25
page: 11
post: 1
product: 20
product_variation: 7
revision: 1

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (4) ###

Custom Role Creator (CRC): by Ratul Hasan – 1.1.0
Dokan Pro: by weDevs – 3.3.6
Dokan: by weDevs – 3.2.13
WooCommerce: by Automattic – 5.7.1 (update to version 5.8.0 is available)

### Inactive Plugins (4) ###

Akismet Anti-Spam: by Automattic – 4.1.12
Hello Dolly: by Matt Mullenweg – 1.7.2
WooCommerce Conversion Tracking: by weDevs – 2.0.8
WooCommerce Conversion Tracking Pro: by weDevs – 1.0.7

### Settings ###

API Enabled: –
Force SSL: –
Currency: BDT (৳ )
Currency Position: right
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #6 - /shop/
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 3.9.1
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 153
Oldest: 2021-10-01 03:51:28 +0000
Newest: 2021-10-21 11:59:51 +0000

### Status report information ###

Generated at: 2021-10-21 14:59:16 +00:00
`

### PR DESCRIPTION
**Pull request by RatulHasan**
### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes #31008

### How to test the changes in this Pull Request:

1. Save bulk edit without any error.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

Fix Uncaught TypeError: Unsupported operand types: string * float on set new price 

### FOR PR REVIEWER ONLY:

* [x] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

File: plugins/woocommerce/includes/admin/class-wc-admin-post-types.php [hunk 1]
```diff
@@ -928,7 +928,7 @@ private function set_new_price( $product, $price_type ) {
 			return false;
 		}
 
-		$old_price     = $product->{"get_{$price_type}_price"}();
+		$old_price     = empty( $product->{"get_{$price_type}_price"}() ) ? 0 : $product->{"get_{$price_type}_price"}();
```
Comment (jeffstieler) [inline plugins/woocommerce/includes/admin/class-wc-admin-post-types.php]: Let's change this to a `(float)` value cast instead of using `empty()` and a ternary.

**Review by jeffstieler — CHANGES_REQUESTED** [review]
Thanks for your contribution!

This indeed fixes the issue, but we'd like the logic changed to be a float type casting for consistency with similar operations in WooCommerce.

**Comment by RatulHasan** [comment]
@jeffstieler, Fixed the logic of those codes.

**Review by barryhughes — APPROVED** [review]
