### PR TITLE
Product Sale Badge: render the block on the Single Product Block 

### LINKED ISSUE #57983: Product Sale Badge: the block isn't rendered on the frontend when used inside the Single Product Block
When the Product Sale Badge block is used inside the Single Product block, it doesn’t render on the frontend. This issue prevents the badge from being visible to users, even though it’s correctly added in the editor.

> 
> Also, just noticed that the `woocommerce/product-sale-badge` is not showing up on the frontend. Please let me know if I'm missing something here.
> 
> https://github.com/user-attachments/assets/411bdea1-d57d-4501-aa34-3e01d0610b95

 _Originally posted by @AhmarZaidi in [#42382](https://github.com/woocommerce/woocommerce/issues/42382#issuecomment-2876333434)_

### Description

When the **Product Sale Badge** block is used inside the **Single Product** block, it doesn't render on the frontend. This issue prevents the badge from being visible to users, even though it's correctly added in the editor.

### Steps to Reproduce

1. Create a new post.
2. Add the Single Product block. Ensure that you select a product that it is on sale.
3. Inside the Single Product block, add the Product Sale Badge block.
4. Save the changes.
5. Visit a product page on the frontend where the product is on sale.

### Expected Behavior
The Product Sale Badge should appear, indicating the product is on sale.

### Actual Behavior

The Product Sale Badge block is not rendered on the frontend.

### PR DESCRIPTION
**Pull request by gigitux**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

This PR ensures that the Product Sale Badge is rendered when it used in the Single Product Block. 

Currently, the block isn't rendered in the Single Product Block because `isDescendentOfSingleProductBlock` attribute isn't set. In this case,`isDescendentOf` variables are set to ensure that JS assets are loaded **only** when the block is used in the All Products block. As mentioned in [this discussion](https://github.com/woocommerce/woocommerce/discussions/57024), we want to get rid of these attributes. In this case, it is pretty complex because on the PHP side, we need to have a value that indicates that the block is used inside the All Products block. Unfortunately, I didn't find a way :( 

At the same time, I noticed the block is broken when used inside the All Products block:

https://github.com/user-attachments/assets/83498f69-ec00-4d0f-ad4e-cf4603bab44c

Given that the block is broken when used with the `All Products`, I removed the compatibility with this block and removed all the `isDescendent` variables.

Related Slack Discussion: p1747144749570319-slack-C02SGH7JBGS

Closes #57983 (WOOPLUG-4274) .

(For Bug Fixes) Bug introduced in PR # .

### Screenshots or screen recordings:

| Before | After |
| ------ | ----- |
|  image   |  image     |

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Ensure that you're on trunk.
2. Create a post. 
3. Add the `Single Product Block`
4. In the `Single Product Block` add the On Sale Badge.
5. Save the post.
6. Visit the post.
7. See that the block isn't rendered.
8. Create a new post.
9. Add the `All Products` block via [this snippet](https://gist.github.com/gigitux/5cb489fa10a960354e0f1baf797e1c7f).
10. Edit the `All Products` block.
11. Add the `On Sale Badge` block.
12. Click on done button and save the post.
13. Visit the post.
14. See that the On Sale Badge is not visible.
15. Checkout this branch.
16. Visit both post on the editor side and frontend side.
17. Ensure that the Product Sale Badge is rendered inside the Single Product Block.
18. Ensure that the `All Products` block is rendered. 
19. Edit the Single Product Template.
20. Add the `On Sale Badge` block.
21. Visit a product page for an item that is on sale.
22. Ensure that the block is visible.
23. Visit a product page for an item that is not on sale.
24. Ensure that the block isn't visible.

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [x] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 
Product Sale Badge: render the block on the Single Product Block.

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

**Comment by Marc-pi** [comment]
@gigitux hello, is there a plan to add by default also the out of stock badge ???

File: plugins/woocommerce/client/blocks/assets/js/atomic/blocks/product-elements/sale-badge/edit.tsx [hunk 1]
```diff
@@ -4,47 +4,37 @@
...
 	const blockProps = useBlockProps();
 
+	const isTemplate = useSelect( ( select ) => {
+		const { getCurrentPostType } = select( editorStore );
+
+		const template = getCurrentPostType() === 'wp_template';
+
+		return template;
+	}, [] );
+
```
Comment (kmanijak) [inline plugins/woocommerce/client/blocks/assets/js/atomic/blocks/product-elements/sale-badge/edit.tsx]: It's too generic and applies to Product Catalog as well which results in On Sale displayed on every product in Product Collection. It should only apply:

image

I think we can keep:

```
const { isDescendentOfSingleProductTemplate } =
		useIsDescendentOfSingleProductTemplate();
```

but simply avoiding setting it as an `attribute`.

File: plugins/woocommerce/client/blocks/assets/js/atomic/blocks/product-elements/sale-badge/index.tsx [hunk 2]
```diff
@@ -20,7 +19,7 @@ const blockConfig = {
 		/>
 	),
 	edit,
-	save,
+	save: () => null,
```
Comment (kmanijak) [inline plugins/woocommerce/client/blocks/assets/js/atomic/blocks/product-elements/sale-badge/index.tsx:23]: If someone had a block inserted in Single Product block, this will result in validation error at first check. But I guess it's fine and worth the change! I don't think we should go through `migrate` from deprecation API for this edge case but mentioning it just in case 🤔

**Review by kmanijak — CHANGES_REQUESTED** [review]
Thanks for this change! `isTemplate` has to be improved but otherwise it looks good! 🚀

File: plugins/woocommerce/client/blocks/assets/js/atomic/blocks/product-elements/sale-badge/edit.tsx (hunk 1 above)
Comment (gigitux) [reply plugins/woocommerce/client/blocks/assets/js/atomic/blocks/product-elements/sale-badge/edit.tsx]: Nice catch! I completely to forgot about the Product Collection!

**Comment by Marc-pi** [comment]
image

the better is to display it "on" the image
how did you manage this ?
because in case some product are not on sale, there will be an unalignement of the "cards" list in the Collection

File: plugins/woocommerce/client/blocks/assets/js/atomic/blocks/product-elements/sale-badge/edit.tsx (hunk 1 above)
Comment (gigitux) [reply plugins/woocommerce/client/blocks/assets/js/atomic/blocks/product-elements/sale-badge/edit.tsx]: Fixed with 838f988

File: plugins/woocommerce/client/blocks/assets/js/atomic/blocks/product-elements/sale-badge/index.tsx (hunk 2 above)
Comment (gigitux) [reply plugins/woocommerce/client/blocks/assets/js/atomic/blocks/product-elements/sale-badge/index.tsx:23]: Good point! I implemented the migration with 941997f5abe03ad045c5ed5f313b5d29afa8d84b

**Comment by gigitux** [comment]
As I mentioned in p1747224413225419-slack-C02SGH7JBGS, I was able to discover why the migration didn't work, so I implemented it! Also, I opened an issue on Gutenberg: https://github.com/WordPress/gutenberg/issues/70123.

@kmanijak thanks for the review and the help! 🙇

File: plugins/woocommerce/client/blocks/assets/js/atomic/blocks/product-elements/sale-badge/index.tsx (hunk 2 above)
Comment (kmanijak) [reply plugins/woocommerce/client/blocks/assets/js/atomic/blocks/product-elements/sale-badge/index.tsx:23]: Amazing job with investigating the deprecation API!!! ❤️

**Review by kmanijak — APPROVED** [review]
I re-tested the PR and it works as expected:
- All Products - badge is not displayed but we're aware of it and accept it
- Single Product - badge is displayed, migration works correctly!
- Product Collection in Product Catalog - badge is displayed only for products on sale.

Great job! 🚀

**Comment by gigitux** [comment]
> @gigitux hello, is there a plan to add by default also the out of stock badge ???

No, currently we are not planning to add it as default.
