### PR TITLE
[Block Checkout] Hide shipping toggle when only local pickup methods exist

### LINKED ISSUE #48509: [Enhancement]: Add option to disable shipping when only local pickup is enabled at store level
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

If you are using the checkout block, it is not possible to show local pickup as the only option. It keeps showing a shipping option which does not work correctly.

### Expected behavior

If you use the checkout block and do not have local pickup set up, the checkout will only show the shipping options. 
So it is expected to only show pickup options if this is the only thing set up on the website.

### Actual behavior

A shipping option shows on checkout anyway.

If you have the checkout block, you won't be able to add local pickup as a shipping method on the shipping zone. You need to set it up on the local pickup setting page.

Then, when you click on Shipping on the checkout it will say there's no shipping method available, which is not ideal.
image

If you used to have the checkout shortcode and have local pickup added on the shipping zone (which still works with the shortcode), when you click on shipping it will show local pickup as a shipping option, but not in the correct way.

image

The correct way would be to show the pickup locations as it does when you click on local pickup. But even if it showed correctly, it would be redundant to have buttons for shipping and local pickup that show the same thing.
image

### Steps to reproduce

1. Have the checkout block on checkout page
2. Add a pickup location, but do not add any other shipping method
3. Go to checkout

To see the other option:
1. Have the shortcode on the checkout page
2. Add local pickup as a shipping method on a shipping zone
3. Have no other shipping method 
4. Switch to the checkout block
5. Go to checkout

<details>
<summary>WordPress Environment</summary>

```
### WordPress Environment ###

WordPress address (URL): https://carol-testing.mystagingwebsite.com
Site address (URL): https://carol-testing.mystagingwebsite.com
WC Version: 8.9.3
REST API Version: ✔ 8.9.3
Action Scheduler Version: ✔ 3.7.4
Log Directory Writable: ✔
WP Version: 6.5.4
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 8.2.20
PHP Post Max Size: 2 GB
PHP Time Limit: 1200
PHP Max Input Vars: 6144
cURL Version: 8.7.1
OpenSSL/1.1.1w

SUHOSIN Installed: –
MySQL Version: 10.6.15-MariaDB-log
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.9.3
WC Database Prefix: wp_
Total Database Size: 58.23MB
Database Data Size: 39.08MB
Database Index Size: 19.15MB
wp_woocommerce_sessions: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.19MB + Index: 0.19MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vp_backup_wp_actionscheduler_actions: Data: 2.02MB + Index: 0.89MB + Engine InnoDB
vp_backup_wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vp_backup_wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vp_backup_wp_actionscheduler_logs: Data: 1.14MB + Index: 0.55MB + Engine InnoDB
vp_backup_wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vp_backup_wp_comments: Data: 0.08MB + Index: 0.09MB + Engine InnoDB
vp_backup_wp_gla_attribute_mapping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
vp_backup_wp_gla_budget_recommendations: Data: 0.19MB + Index: 0.14MB + Engine InnoDB
vp_backup_wp_gla_merchant_issues: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
vp_backup_wp_gla_shipping_rates: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vp_backup_wp_gla_shipping_times: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vp_backup_wp_jetpack_sync_queue: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
vp_backup_wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vp_backup_wp_mailpoet_automations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
vp_backup_wp_mailpoet_automation_runs: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
vp_backup_wp_mailpoet_automation_run_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
vp_backup_wp_mailpoet_automation_run_subjects: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vp_backup_wp_mailpoet_automation_triggers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
vp_backup_wp_mailpoet_automation_versions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vp_backup_wp_mailpoet_custom_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vp_backup_wp_mailpoet_dynamic_segment_filters: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vp_backup_wp_mailpoet_feature_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vp_backup_wp_mailpoet_forms: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
vp_backup_wp_mailpoet_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
vp_backup_wp_mailpoet_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vp_backup_wp_mailpoet_newsletters: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
vp_backup_wp_mailpoet_newsletter_links: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
vp_backup_wp_mailpoet_newsletter_option: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vp_backup_wp_mailpoet_newsletter_option_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vp_backup_wp_mailpoet_newsletter_posts: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vp_backup_wp_mailpoet_newsletter_segment: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vp_backup_wp_mailpoet_newsletter_templates: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
vp_backup_wp_mailpoet_scheduled_tasks: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
vp_backup_wp_mailpoet_scheduled_task_subscribers: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vp_backup_wp_mailpoet_segments: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vp_backup_wp_mailpoet_sending_queues: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vp_backup_wp_mailpoet_settings: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vp_backup_wp_mailpoet_statistics_bounces: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
vp_backup_wp_mailpoet_statistics_clicks: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
vp_backup_wp_mailpoet_statistics_forms: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vp_backup_wp_mailpoet_statistics_newsletters: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vp_backup_wp_mailpoet_statistics_opens: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
vp_backup_wp_mailpoet_statistics_unsubscribes: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
vp_backup_wp_mailpoet_statistics_woocommerce_purchases: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
vp_backup_wp_mailpoet_stats_notifications: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vp_backup_wp_mailpoet_subscribers: Data: 0.02MB + Index: 0.23MB + Engine InnoDB
vp_backup_wp_mailpoet_subscriber_custom_field: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vp_backup_wp_mailpoet_subscriber_ips: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vp_backup_wp_mailpoet_subscriber_segment: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vp_backup_wp_mailpoet_subscriber_tag: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vp_backup_wp_mailpoet_tags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vp_backup_wp_mailpoet_user_agents: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vp_backup_wp_mailpoet_user_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vp_backup_wp_options: Data: 1.22MB + Index: 0.06MB + Engine InnoDB
vp_backup_wp_postmeta: Data: 0.38MB + Index: 0.33MB + Engine InnoDB
vp_backup_wp_posts: Data: 0.14MB + Index: 0.06MB + Engine InnoDB
vp_backup_wp_snippets: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vp_backup_wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vp_backup_wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vp_backup_wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vp_backup_wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vp_backup_wp_usermeta: Data: 0.13MB + Index: 0.03MB + Engine InnoDB
vp_backup_wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
vp_backup_wp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
vp_backup_wp_wc_admin_note_actions: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
vp_backup_wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
vp_backup_wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vp_backup_wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vp_backup_wp_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
vp_backup_wp_wc_orders_meta: Data: 0.08MB + Index: 0.13MB + Engine InnoDB
vp_backup_wp_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
vp_backup_wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vp_backup_wp_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vp_backup_wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
vp_backup_wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
vp_backup_wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vp_backup_wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vp_backup_wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vp_backup_wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
vp_backup_wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vp_backup_wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
vp_backup_wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vp_backup_wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vp_backup_wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vp_backup_wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vp_backup_wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
vp_backup_wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vp_backup_wp_woocommerce_order_itemmeta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
vp_backup_wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vp_backup_wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vp_backup_wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vp_backup_wp_woocommerce_sessions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
vp_backup_wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
vp_backup_wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vp_backup_wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
vp_backup_wp_woocommerce_square_customers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
vp_backup_wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
vp_backup_wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vp_backup_wp_wpml_mails: Data: 0.36MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 2.14MB + Index: 0.95MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 1.31MB + Index: 1.38MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.23MB + Index: 0.16MB + Engine InnoDB
wp_gla_attribute_mapping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gla_budget_recommendations: Data: 0.17MB + Index: 0.14MB + Engine InnoDB
wp_gla_merchant_issues: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gla_shipping_rates: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gla_shipping_times: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_jetpack_sync_queue: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_automations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_automation_runs: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_mailpoet_automation_run_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_automation_run_subjects: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_automation_triggers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_automation_versions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_custom_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_dynamic_segment_filters: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_feature_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_forms: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletters: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_newsletter_links: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_newsletter_option: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_option_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_posts: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_segment: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_templates: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_scheduled_tasks: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_scheduled_task_subscribers: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_segments: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_sending_queues: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_settings: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_statistics_bounces: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_statistics_clicks: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_statistics_forms: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_statistics_newsletters: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_statistics_opens: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_mailpoet_statistics_unsubscribes: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_statistics_woocommerce_purchases: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_mailpoet_stats_notifications: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_subscribers: Data: 0.02MB + Index: 0.23MB + Engine InnoDB
wp_mailpoet_subscriber_custom_field: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_subscriber_ips: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_subscriber_segment: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_subscriber_tag: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_tags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_user_agents: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_user_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 2.13MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 2.52MB + Index: 2.95MB + Engine InnoDB
wp_posts: Data: 1.50MB + Index: 0.28MB + Engine InnoDB
wp_say_what_strings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_snippets: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.09MB + Index: 0.05MB + Engine InnoDB
wp_term_taxonomy: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.14MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_orders: Data: 0.06MB + Index: 0.11MB + Engine InnoDB
wp_wc_orders_meta: Data: 0.25MB + Index: 0.44MB + Engine InnoDB
wp_wc_order_addresses: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_operational_data: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.05MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.08MB + Index: 0.05MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.13MB + Index: 0.17MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_square_customers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpml_mails: Data: 2.52MB + Index: 0.02MB + Engine InnoDB
wp_yoast_indexable: Data: 0.06MB + Index: 0.09MB + Engine InnoDB
wp_yoast_indexable_hierarchy: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_primary_term: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_yoast_seo_links: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_actionscheduler_actions: Data: 2.02MB + Index: 0.73MB + Engine InnoDB
__wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_actionscheduler_logs: Data: 1.38MB + Index: 0.45MB + Engine InnoDB
__wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_comments: Data: 0.06MB + Index: 0.09MB + Engine InnoDB
__wp_gla_attribute_mapping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
__wp_gla_budget_recommendations: Data: 0.19MB + Index: 0.14MB + Engine InnoDB
__wp_gla_merchant_issues: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
__wp_gla_shipping_rates: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_gla_shipping_times: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_mailpoet_automations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
__wp_mailpoet_automation_runs: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
__wp_mailpoet_automation_run_logs: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
__wp_mailpoet_automation_run_subjects: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_mailpoet_automation_triggers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
__wp_mailpoet_automation_versions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_mailpoet_custom_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_mailpoet_dynamic_segment_filters: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_mailpoet_feature_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_mailpoet_forms: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
__wp_mailpoet_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
__wp_mailpoet_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_mailpoet_newsletters: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
__wp_mailpoet_newsletter_links: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
__wp_mailpoet_newsletter_option: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_mailpoet_newsletter_option_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_mailpoet_newsletter_posts: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_mailpoet_newsletter_segment: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_mailpoet_newsletter_templates: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
__wp_mailpoet_scheduled_tasks: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
__wp_mailpoet_scheduled_task_subscribers: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_mailpoet_segments: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_mailpoet_sending_queues: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_mailpoet_settings: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_mailpoet_statistics_bounces: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
__wp_mailpoet_statistics_clicks: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
__wp_mailpoet_statistics_forms: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_mailpoet_statistics_newsletters: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_mailpoet_statistics_opens: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
__wp_mailpoet_statistics_unsubscribes: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
__wp_mailpoet_statistics_woocommerce_purchases: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
__wp_mailpoet_stats_notifications: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_mailpoet_subscribers: Data: 0.02MB + Index: 0.23MB + Engine InnoDB
__wp_mailpoet_subscriber_custom_field: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_mailpoet_subscriber_ips: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_mailpoet_subscriber_segment: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_mailpoet_subscriber_tag: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_mailpoet_tags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_mailpoet_user_agents: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_mailpoet_user_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_options: Data: 2.09MB + Index: 0.06MB + Engine InnoDB
__wp_postmeta: Data: 0.25MB + Index: 0.23MB + Engine InnoDB
__wp_posts: Data: 0.16MB + Index: 0.06MB + Engine InnoDB
__wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_usermeta: Data: 0.13MB + Index: 0.03MB + Engine InnoDB
__wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
__wp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
__wp_wc_admin_note_actions: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
__wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
__wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
__wp_wc_orders_meta: Data: 0.05MB + Index: 0.09MB + Engine InnoDB
__wp_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
__wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
__wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
__wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
__wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
__wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
__wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_woocommerce_sessions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
__wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
__wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
__wp_woocommerce_square_customers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
__wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
__wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB

### Post Type Counts ###

attachment: 74
customize_changeset: 16
custom_css: 1
mailpoet_page: 1
nav_menu_item: 11
page: 10
post: 2
product: 268
product_variation: 643
revision: 152
shop_coupon: 9
shop_order: 125
shop_order_refund: 3
wp_global_styles: 3
wp_navigation: 1
wp_template: 4

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (10) ###

Jetpack: by Automattic – 13.6-a.1
WooCommerce Smooth Generator: by Automattic – 1.1.0
WooCommerce Stripe Gateway: by WooCommerce – 8.4.0
WooPayments: by Automattic – 7.7.0
WooCommerce PayPal Payments: by WooCommerce – 2.8.0
WooCommerce Shipping & Tax: by WooCommerce – 2.6.0
WooCommerce Square: by WooCommerce – 4.6.2
WooCommerce: by Automattic – 8.9.3
WP Mail Logging: by WP Mail Logging Team – 1.12.0
WP Rollback: by WP Rollback – 2.0.7

### Inactive Plugins (8) ###

Akismet Anti-spam: Spam Protection: by Automattic - Anti-spam Team – 5.3.2
Braintree for WooCommerce Payment Gateway: by WooCommerce – 3.1.6
Code Snippets: by Code Snippets Pro – 3.6.5.1
Jetpack Protect: by Automattic - Jetpack Security team – 2.2.0
Loco Translate: by Tim Whitlock – 2.6.10
Query Monitor: by John Blackbourn – 3.16.3
Say What?: by Ademti Software – 2.2.2
WooCommerce Blocks: by Automattic – 11.7.0

### Dropin Plugins () ###

advanced-cache.php: advanced-cache.php
db.php: Query Monitor Database Class (Drop-in)
object-cache.php: Memcached

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: ✔

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 4 MB

### WC Pages ###

Shop base: #5 - /shop/
Cart: #6 - /cart/
Checkout: #7 - /checkout/
My account: #8 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 4.6.0
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### WooPayments ###

Version: 7.7.0
Connected to WPCOM: Yes
WPCOM Blog ID: 226468543
Account ID: acct_1OI81EC8WnAGsBn1
Payment Gateway: Enabled
Test Mode: Enabled
Enabled APMs: card,klarna
WooPay: Enabled (product,cart,checkout)
WooPay Incompatible Extensions: No
Apple Pay / Google Pay: Disabled
Fraud Protection Level: basic
Multi-currency: Enabled
Auth and Capture: Enabled
Documents: Disabled
Logging: Enabled

### WooCommerce PayPal Payments ###

Onboarded: ✔
Shop country code: CA
WooCommerce currency supported: ✔
Advanced Card Processing available in country: ✔
Pay Later messaging available in country: –
Webhook status: –
PayPal Vault enabled: –
ACDC Vault enabled: –
Logging enabled: –
Reference Transactions: ✔
Used PayPal Checkout plugin: –
Subscriptions Mode: Disabled

### Square ###

Environment: Production
Tokenization Enabled: ✔
Debug Mode: Off

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
product-virtual-downloadable
product-external-affiliate
product-grouped
product-linked
product-pre-publish-modal
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
settings
async-product-editor-category-field
launch-your-store

Daily Cron: ✔ Next scheduled: 2024-06-15 13:35:37 -03:00
Options: ✔
Notes: 88
Onboarding: completed

### Action Scheduler ###

Canceled: 5
Oldest: 2024-05-15 20:11:20 +0000
Newest: 2024-05-30 20:26:20 +0000

Complete: 1,681
Oldest: 2024-05-15 13:14:56 +0000
Newest: 2024-06-15 11:59:43 +0000

Failed: 1,707
Oldest: 2023-11-30 10:08:08 +0000
Newest: 2024-06-11 14:53:22 +0000

Pending: 3
Oldest: 2024-06-15 12:24:27 +0000
Newest: 2024-06-15 14:53:31 +0000


### Status report information ###

Generated at: 2024-06-15 09:06:14 -03:00
```

</details>

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by mikejolley**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

On checkout, if local pickup is enabled we show a toggle between delivery and collection:

Screenshot 2025-01-07 at 15 08 34

If local pickup is disabled, this toggle is hidden. This however was not the case if delivery was disabled but local pickup was enabled. This PR fixes this.

Now, if you have only local pickup configured, there will be no toggle visible. Uses the existing `wc_get_shipping_method_count` core functionality to determine if shipping methods are configured or not.

This PR fixes some styling issues in the pickup area also so the spacing matches payment methods.

Closes #48509

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Go to WooCommerce > Settings > Shipping
2. Remove all shipping methods and zones
3. Go to WooCommerce > Settings > Shipping > Local PIckup. Enable it and setup some pickup locations.
4. As a customer, add something to cart and go to checkout. Confirm you only see local pickup methods and there is no delivery/collection toggle.
5. Go to WooCommerce > Settings > Shipping
6. Add a shipping method to any zone and save.
7. As a customer, add something to cart and go to checkout. Confirm there is a delivery/collection toggle and it functions accordingly.
8. Go to WooCommerce > Settings > Shipping. 
9. Toggle the "enabled" checkbox off and save.
10. As a customer, add something to cart and go to checkout. Confirm you only see local pickup methods and there is no delivery/collection toggle.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

**Review by opr — CHANGES_REQUESTED** [review]
Thanks for working on this Mike, I noticed there's an failing test related to shipping, not sure what would cause that, the changes don't seem like they'd affect that. Maybe the first arg to `wc_get_shipping_method_count` that you changed is causing an issue, but that shouldn't affect store API routes 🤔 

> Automattic\WooCommerce\Tests\Blocks\StoreApi\Utilities\OrderControllerTests::test_validate_selected_shipping_methods
Automattic\WooCommerce\StoreApi\Exceptions\RouteException: Sorry, this order requires a shipping option.
>
> /var/www/html/wp-content/plugins/woocommerce/src/StoreApi/Utilities/OrderController.php:549
>/var/www/html/wp-content/plugins/woocommerce/tests/php/src/Blocks/StoreApi/Utilities/OrderControllerTests.php:41

This isn't failing locally either, seems like the setup in CI has some different shipping methods somehow.

I think we should write tests for this behaviour, especially around the `Local pickup is included with legacy shipping methods since they do not support shipping zones.` logic, seems like this could be easily broken by changes elsewhere in the codebase.

Besides this PHP fail, it's testing well for me following the instructions.

**Comment by mikejolley** [comment]
- Added an e2e test for the toggle visibility
- Fixed a core bug with how rate counts are cached
- Fixed a core bug with lingering packages after cart is cleared
- Fix test suite tear downs to clean up cart after running tests

File: plugins/woocommerce/includes/class-wc-cart.php [hunk 1]
```diff
@@ -651,6 +651,7 @@ public function empty_cart( $clear_persistent_cart = true ) {
 		}
 
 		$this->fees_api->remove_all_fees();
+		WC()->shipping()->reset_shipping();
```
Comment (opr) [inline plugins/woocommerce/includes/class-wc-cart.php:656]: Do we need to update any docs anywhere for this? I doubt we documented this in so much detail but could be worth checking?

**Review by opr — APPROVED** [review]
Working well now, followed the instructions and I placed an order with a virtual product and a normal product, both were fine 👌🏼

File: plugins/woocommerce/includes/class-wc-cart.php (hunk 1 above)
Comment (mikejolley) [reply plugins/woocommerce/includes/class-wc-cart.php:656]: I've added a little docblock. I don't see other docs for it.

Comment (opr) [reply plugins/woocommerce/includes/class-wc-cart.php:656]: Looks good, thanks!
