### PR TITLE
Prevent theme styles from being used in the block-based product editor

### LINKED ISSUE #38279: Consider bleed of `theme.json` styles into the block-based product editor.
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

The product editor is showing the background color from global styles in the editor. This is usually expected behaviour in a block editor instance because of the wysiwyg for layout previewing. However, with the design of the product editor being more form-based, the styles don't work.

However, we'll want to make sure the styles _are_ considered when editing the product description.

### Expected behavior

Frontend global styles are not applied to the product editor.

### Actual behavior

Frontend global styles **are** applied to the product editor.
CleanShot 2023-05-12 at 10 05 26@2x

### Steps to reproduce

1. Activate a theme like Twenty Twenty Three.
2. Activate a style such as "Block out" via the Styles panel in the site editor.
3. View the experimental block-based product editor and see that the chosen styles are affecting the product editor.

### WordPress Environment

n/a

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by mattsherman**
### Submission Review Guidelines:

- I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
- I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
- I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/). 
- Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

This PR changes the implementation to only apply the editor styles to the description content preview. Previously, it was being applied to the entire product editor, which was unexpected and undesired.

Note: The editor styles are still being applied to the modal editor used to edit the description, as is expected.

#### Before

Screenshot 2023-05-26 at 11 20 28

#### After

Screenshot 2023-05-26 at 15 02 21

Closes #38279.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Enable the experimental block-based product editor.
2. Activate a theme such as Twenty Twenty-Three.
3. Activate a style for the theme that results in easy to spot differences (such as the background), such as "Block out" or "Pilgrimage", via the Styles panel in the Site Editor.
4. Go to the block-based product editor.
5. Verify the theme styles are not affecting the product editor.
6. Verify the theme styles are applied to the description content preview.
7. Verify the theme styles are applied to the modal editor for the description.

### CODE REVIEW

File: packages/js/product-editor/src/components/content-preview/content-preview.tsx [hunk 1]
```diff
@@ -47,13 +59,35 @@ const CONTENT_ATTR = [
...
 	return (
-		<div
-			className="woocommerce-content-preview"
-			dangerouslySetInnerHTML={ sanitizeHTML( content, {
-				tags: CONTENT_TAGS,
-				attr: CONTENT_ATTR,
-			} ) }
-		/>
+		<div className="woocommerce-content-preview">
+			<Iframe
```
Comment (joshuatf) [inline packages/js/product-editor/src/components/content-preview/content-preview.tsx:70]: Nice reuse of the `Iframe` component!

**Review by joshuatf — APPROVED** [review]
Testing well for me and styles are limited to the iframe modal and preview area!  Thanks for the fixes, Matt! 🚢
