### PR TITLE
change string 'automatically generate an account password'

### LINKED ISSUE #31560: 'automatically generate an account password' Accounts & Privacy setting label is outdated.
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Due to #31305 (STOP sending passwords via e-mail Please) and #31257 (PR: Send set password link instead of the actual password to new users.), the WooCommerce accounts and privacy setting text no longer reflects what the setting actually does:

Screenshot  
*If you do not see the image, please [click here](https://d.pr/i/Xr3xNY).*

### Expected behavior

It could more accurately say: `When creating an account, send the new user a password reset link`

Even better, it could be a radio between 'Send a password reset link' and 'Ask user to set the password upon registration' so it isn't confusing what the behavior will be when unchecked.

### Actual behavior

It says: `When creating an account, automatically generate an account password`

### Steps to reproduce

Create an account on a site with `When creating an account, automatically generate an account password` checked.

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://ldg-wc-test.mystagingwebsite.com
Site address (URL): https://ldg-wc-test.mystagingwebsite.com
WC Version: 6.0.0
REST API Version: ✔ 6.0.0
WC Blocks Version: ✔ 6.3.3
Action Scheduler Version: ✔ 3.3.0
WC Admin Version: ✔ 2.9.4
Log Directory Writable: ✔
WP Version: 5.8.2
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 7.4.27
PHP Post Max Size: 2 GB
PHP Time Limit: 1200
PHP Max Input Vars: 6144
cURL Version: 7.80.0
OpenSSL/1.1.1d

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.3.31-MariaDB-log
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 6.0.0
WC Database Prefix: wp_
Total Database Size: 25.81MB
Database Data Size: 16.02MB
Database Index Size: 9.79MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.14MB + Index: 0.16MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 2.02MB + Index: 1.00MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 1.02MB + Index: 0.56MB + Engine InnoDB
wp_advanced_notifications: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_advanced_notification_triggers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_automatewoo_abandoned_carts: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_automatewoo_customers: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_automatewoo_customer_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_events: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_guests: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_automatewoo_guest_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_log_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_queue: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_queue_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_referrals: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_automatewoo_referral_advocate_keys: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_automatewoo_referral_invites: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.09MB + Index: 0.11MB + Engine InnoDB
wp_followup_coupons: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_coupon_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_customers: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_followup_customer_carts: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_customer_notes: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_customer_orders: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_followup_email_excludes: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_email_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_email_orders: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_followup_email_tracking: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_followup_followup_history: Data: 0.05MB + Index: 0.05MB + Engine InnoDB
wp_followup_order_categories: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_order_items: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_subscribers: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_subscribers_to_lists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_subscriber_lists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gla_budget_recommendations: Data: 0.22MB + Index: 0.14MB + Engine InnoDB
wp_gla_merchant_issues: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gla_shipping_rates: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gla_shipping_times: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_custom_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_dynamic_segment_filters: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_feature_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_forms: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_mapping_to_external_entities: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletters: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_newsletter_links: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_newsletter_option: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_option_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_posts: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_segment: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_templates: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_scheduled_tasks: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_scheduled_task_subscribers: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_segments: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_sending_queues: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_settings: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_statistics_bounces: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_statistics_clicks: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_statistics_forms: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_statistics_newsletters: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_statistics_opens: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_mailpoet_statistics_unsubscribes: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_statistics_woocommerce_purchases: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_mailpoet_stats_notifications: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_subscribers: Data: 0.02MB + Index: 0.13MB + Engine InnoDB
wp_mailpoet_subscriber_custom_field: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_subscriber_ips: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_subscriber_segment: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_user_agents: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_user_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_ms_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 4.03MB + Index: 1.09MB + Engine InnoDB
wp_postmeta: Data: 2.13MB + Index: 2.06MB + Engine InnoDB
wp_posts: Data: 0.27MB + Index: 0.13MB + Engine InnoDB
wp_redirection_404: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_redirection_groups: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_redirection_items: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_redirection_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_say_what_strings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wcpv_commissions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcpv_per_product_shipping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcrp_rental_products_rentals: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcs_payment_retries: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_bookings_availability: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_bookings_availabilitymeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_booking_relationships: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_deposits_payment_plans: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_deposits_payment_plans_schedule: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_bundle_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_points_rewards_user_points: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_points_rewards_user_points_log: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.06MB + Index: 0.13MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_warranty_products: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wdr_order_discounts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wdr_order_item_discounts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wdr_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfblockediplog: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfblocks7: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wfconfig: Data: 0.13MB + Index: 0.00MB + Engine InnoDB
wp_wfcrawlers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wffilechanges: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wffilemods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfhits: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wfhoover: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfissues: Data: 0.13MB + Index: 0.06MB + Engine InnoDB
wp_wfknownfilelist: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wflivetraffichuman: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wflocs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wflogins: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wfls_2fa_secrets: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfls_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfnotifications: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfpendingissues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wfreversecache: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfsnipcache: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wfstatus: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wftrafficrates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_amazon_buyer_index: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_bundled_itemmeta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_bundled_items: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_exported_csv_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_per_product_shipping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_flat_rate_boxes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_table_rates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_software_activations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_software_licenses: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_square_customers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_subscription_downloads: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpml_mails: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wp_phpmyadmin_extension__errors_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wrd_discounts: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wrd_sent_coupons: Data: 0.02MB + Index: 0.05MB + Engine InnoDB

### Post Type Counts ###

addify_rfq: 1
attachment: 102
auto-print-templates: 1
aw_workflow: 10
bookable_person: 12
bookable_resource: 5
conditional-checkout: 3
customize_changeset: 1
custom_css: 1
event_ticket: 7
follow_up_email: 3
global_product_addon: 1
mailpoet_page: 1
nav_menu_item: 11
oembed_cache: 1
page: 8
polylang_mo: 3
product: 84
product_variation: 41
revision: 39
shipping_package: 2
shop_coupon: 4
shop_order: 95
shop_order_refund: 3
shop_subscription: 13
wc-donation: 3
wcpf_item: 6
wcpf_project: 1
wc_booking: 47
wc_membership_plan: 2
wc_user_membership: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (12) ###

Akismet Anti-Spam: by Automattic – 4.2.1
AutomateWoo: by WooCommerce – 5.5.7
Facebook for WooCommerce: by Facebook – 2.6.8
Google Listings and Ads: by WooCommerce – 1.9.0
Jetpack: by Automattic – 10.5-a.3
MailPoet 3 (New): by MailPoet – 3.75.1
Plugin Toggle: by Cedaro – 1.3.1
Facebook for WooCommerce - settings tools: by SkyVerge – 1.0.0
WooCommerce Stripe Gateway: by WooCommerce – 5.9.0
WooCommerce Memberships: by SkyVerge – 1.21.6
WooCommerce Subscriptions: by WooCommerce – 3.1.6
WooCommerce: by Automattic – 6.0.0

### Inactive Plugins (133) ###

Age Verification Popup: by KoalaApps – 1.0.2
AutomateWoo - Birthdays Add-on: by WooCommerce – 1.3.2
AutomateWoo - Refer A Friend Add-on: by WooCommerce – 2.6.1
Automatic Order Printing for WooCommerce: by Procom – 1.0.2
Birthday Discount Coupon: by KoalaApps – 1.0.0
Bookings Helper: by WooCommerce – 1.0.3
Bulk Discounts for WooCommerce: by Plugify – 1.0.2
Cart Upsell for WooCommerce: by SKROTRON – 1.0.6
Code Snippets: by Code Snippets Pro – 2.14.3
Conditional Checkout For WooCommerce: by WebMeteors – 1.0.0
Custom Product Boxes: by CodeIncept – 1.0.5
Deals for WooCommerce: by FantasticPlugins – 1.7
Debug Bar: by wordpressdotorg – 1.1.2
Delivery Slots for WooCommerce: by FantasticPlugins – 1.6
Donation For Woocommerce: by wpexpertsio – 2.2.1
Email Customizer Pro For WooCommerce: by StoreApps – 3.1.1
Follow-Up Emails: by WooCommerce – 4.9.16
Health Check & Troubleshooting: by The WordPress.org community – 1.4.5
Loco Translate: by Tim Whitlock – 2.5.5
Meks Quick Plugin Disabler: by Meks – 1.0
Polylang: by WP SYNTEX – 3.1.3
Preview E-mails for WooCommerce: by Digamber Pradhan – 2.0.1
Product Filters for WooCommerce: by WooCommerce – 1.2.5
Product Variation Table Plugin: by FMEADDONS – 1.0.3
Query Monitor: by John Blackbourn – 3.8.1
Redirection: by John Godley – 5.1.3
Rental Products: by 99w – 3.0.4
Request a Quote for WooCommerce: by Addify – 2.3.0
Say What?: by Ademti Software – 2.0.2
Search By SKU - for Woocommerce: by Unroll Digital – 0.8.0
Sensei with WooCommerce Paid Courses: by Automattic – 3.11.0.2.3.3
Shipping Locations Pro: by WPExtend – 1.1.1
User Role Editor: by Vladimir Garagulya – 4.61
WC Shipping Rates Importer: by joesat – 1.1.0
WooCommerce - ShipStation Integration: by WooCommerce – 4.1.48
WooCommerce 360° Image: by WooCommerce – 1.1.21
WooCommerce Accommodation Bookings: by WooCommerce – 1.1.25
WooCommerce Additional Variation Images: by WooCommerce – 1.9.0
WooCommerce Advanced Ajax Layered Navigation: by WooCommerce – 1.7.0
WooCommerce Advanced Notifications: by WooCommerce – 1.2.33
WooCommerce Advanced Shipping Packages: by Jeroen Sormani – 1.1.8
WooCommerce Affirm Gateway: by WooCommerce – 1.2.2
WooCommerce All Products For Subscriptions: by SomewhereWarm – 3.1.30
WooCommerce Amazon Pay: by WooCommerce – 2.0.3
WooCommerce Amazon S3 Storage: by WooCommerce – 2.1.22
WooCommerce Australia Post Shipping: by WooCommerce – 2.4.28
WooCommerce AvaTax: by SkyVerge – 1.14.0
WooCommerce Blocks: by Automattic – 6.6.0
WooCommerce Bookings: by WooCommerce – 1.15.48
WooCommerce Bookings Availability: by WooCommerce – 1.1.19
WooCommerce Box Office: by WooCommerce – 1.1.36
WooCommerce Branding: by WooCommerce – 1.0.30
WooCommerce Brands: by WooCommerce – 1.6.25
WooCommerce Bulk Stock Management: by WooCommerce – 2.2.31
WooCommerce Canada Post Shipping: by WooCommerce – 2.5.25
WooCommerce Cart Add-Ons: by WooCommerce – 2.0.0
WooCommerce Checkout Field Editor: by WooCommerce – 1.6.1
WooCommerce Composite Products: by SomewhereWarm – 8.0.2
WooCommerce Conditional Shipping and Payments: by SomewhereWarm – 1.9.3
WooCommerce Coupon Campaigns & Tracking: by WooCommerce – 1.1.17
WooCommerce Customer/Order/Coupon CSV Import Suite: by SkyVerge – 3.10.2
WooCommerce Customer/Order/Coupon Export: by SkyVerge – 5.3.2
WooCommerce Deposits: by WooCommerce – 1.5.6
WooCommerce Distance Rate Shipping: by WooCommerce – 1.0.28
WooCommerce Drip: by WooCommerce – 1.2.25
WooCommerce Dropshipping: by OPMC Australia Pty Ltd – 2.13
WooCommerce Dynamic Pricing: by Element Stark – 3.1.26
WooCommerce Email Customizer: by WooCommerce – 1.1.19
WooCommerce EU VAT Number: by WooCommerce – 2.3.26
WooCommerce evriPay Payment Gateway: by Gerhard Potgieter – 1.1
WooCommerce Eway Payment Gateway: by WooCommerce – 3.3.0
WooCommerce FedEx Shipping: by WooCommerce – 3.4.39
WooCommerce Flat Rate Box Shipping: by WooCommerce – 2.0.16
WooCommerce Force Sells: by WooCommerce – 1.1.29
WooCommerce Freshdesk: by Automattic – 1.1.27
WooCommerce Give Products: by WooCommerce – 1.1.13
WooCommerce GoCardless Gateway: by WooCommerce – 2.4.14
WooCommerce Google Analytics Integration: by WooCommerce – 1.5.6
WooCommerce Measurement Price Calculator: by SkyVerge – 3.20.1
WooCommerce Min/Max Quantities: by WooCommerce – 2.4.24
WooCommerce One Page Checkout: by Automattic – 1.8.1
WooCommerce Opayo Form and Direct Gateway: by Andrew Benbow – 4.9.0
WooCommerce Order Barcodes: by WooCommerce – 1.3.24
WooCommerce PayFast Gateway: by WooCommerce – 1.4.19
WooCommerce Payments: by Automattic – 3.5.0
WooCommerce PayPal Checkout Gateway: by WooCommerce – 2.1.3
WooCommerce PayPal Here Gateway: by WooCommerce – 1.1.3
WooCommerce PayPal Payments: by WooCommerce – 1.6.4
WooCommerce PayPal Payments Advanced Gateway: by WooCommerce – 1.24.12
WooCommerce Photography: by WooCommerce – 1.0.29
WooCommerce Points and Rewards: by WooCommerce – 1.7.0
WooCommerce Pre-Orders: by WooCommerce – 1.5.30
WooCommerce Product Add-ons: by WooCommerce – 4.4.0
WooCommerce Product Bundles: by SomewhereWarm – 6.12.7
WooCommerce Product CSV Import Suite: by WooCommerce – 1.10.46
WooCommerce Product Enquiry Form: by WooCommerce – 1.2.18
WooCommerce Product Finder: by WooCommerce – 1.2.18
WooCommerce Product Vendors: by WooCommerce – 2.1.57
WooCommerce Purchase Order Payment Gateway: by WooCommerce – 1.2.12
WooCommerce Review for Discount: by WooCommerce – 1.6.21
WooCommerce Royal Mail: by WooCommerce – 2.5.34
WooCommerce Sale Flash Pro: by WooCommerce – 1.2.20
WooCommerce Sales Report Email: by WooCommerce – 1.1.20
WooCommerce Shared Variation Inventory: by Webis – 3.1.6
WooCommerce Shipment Tracking: by WooCommerce – 1.6.26
WooCommerce Shipping & Tax: by WooCommerce – 1.25.20
WooCommerce Shipping Per Product v2: by WooCommerce – 2.3.13
WooCommerce Ship to Multiple Addresses: by WooCommerce – 3.6.25
WooCommerce Slack: by WooCommerce – 1.2.8
WooCommerce Smart Coupons: by StoreApps – 4.33.1
WooCommerce Smart Refunder: by StoreApps – 1.5.3
WooCommerce SnapScan Gateway: by WooCommerce – 1.1.12
WooCommerce Software Add-On: by WooCommerce – 1.7.18
WooCommerce Splash Popup: by WooCommerce – 1.2.20
WooCommerce Square: by WooCommerce – 2.7.0
WooCommerce Stamps.com API integration: by WooCommerce – 1.3.22
WooCommerce Store Catalog PDF Download: by WooCommerce – 1.10.27
WooCommerce Subscription Downloads: by WooCommerce – 1.1.31
WooCommerce Subscriptions - Custom Price String: by Prospress Inc. – 1.0.4
WooCommerce Subscriptions - Do Not Reduce Stock on Renewal: by Prospress Inc. –
WooCommerce Table Rate Shipping: by WooCommerce – 3.0.34
WooCommerce UPS Shipping: by WooCommerce – 3.2.31
WooCommerce USPS Shipping: by WooCommerce – 4.4.68
WooCommerce Variation Swatches and Photos: by Element Stark – 3.1.3
WooCommerce Warranty Requests: by WooCommerce – 1.9.22
WooCommerce Xero Integration: by WooCommerce – 1.7.38
Woo Discount Rules: by Flycart – 2.3.11
WooSlider - WooCommerce Products Slideshow: by WooCommerce – 1.0.23
WP Crontrol: by John Blackbourn & crontributors – 1.12.0
WP Debugging: by Andy Fragen – 2.11.3
WP Mail Logging: by Wysija – 1.10.2
WP PHP Console: by Fulvio Notarstefano – 1.6.0
WP phpMyAdmin: by Puvox.software – 5.1.1.05

### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
object-cache.php: Memcached

### Must Use Plugins (1) ###

Health Check Troubleshooting Mode: by  – 1.7.2

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 0
Taxonomies: Product Types: accommodation-booking (accommodation-booking)
booking (booking)
bundle (bundle)
composite (composite)
external (external)
grouped (grouped)
photography (photography)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
exclude_from_catalog (exclude_from_catalog)
exclude_from_search (exclude_from_search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)
visible (visible)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: ❌ Page not set
Cart: #6 - /cart/
Checkout: #7 - /checkout/
My account: #8 - /my-account/
Terms and conditions: #3 - /privacy-policy/

### Theme ###

Name: Storefront
Version: 3.9.1
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Memberships ###

Restriction mode:: Hide content only
Public content:: –
Excluded from discounts:: –
Membership plans:: 2
Site Membership:: Members: 0Access method: Product(s) purchaseAccess length: Unlimited Subscription: YesInstallment plan: No
Site Membership:: Members: 2Access method: Manual assignment onlyAccess length: Unlimited Subscription: No

### Subscriptions ###

WCS_DEBUG: ✔ No
Subscriptions Mode: ✔ Live
Subscriptions Live URL: https://ldg-wc-test.mystagingwebsite.com
Subscription Statuses: wc-active: 3
wc-expired: 3
wc-on-hold: 4
wc-cancelled: 3

WooCommerce Account Connected: ❌ No
Custom Retry Rules: ✔ No
Custom Retry Rule Class: ✔ No
Custom Raw Retry Rule: ✔ No
Custom Retry Rule: ✔ No
Retries Migration Status: ✔ Completed
Report Cache Enabled: ✔ Yes
Cache Update Failures: ✔ 0 failure

### Store Setup ###

Country / State: Malaysia — Kuala Lumpur

### Subscriptions by Payment Gateway ###

Cash on delivery: wc-cancelled: 1
Stripe: wc-active: 3
wc-cancelled: 1
wc-expired: 3
wc-on-hold: 1

other: wc-on-hold: 2

### Payment Gateway Support ###

Cash on delivery: products
Stripe: products
refunds
tokenization
add_payment_method
subscriptions
subscription_cancellation
subscription_suspension
subscription_reactivation
subscription_amount_changes
subscription_date_changes
subscription_payment_method_change
subscription_payment_method_change_customer
subscription_payment_method_change_admin
multiple_subscriptions

### Action Scheduler ###

Complete: 3,092
Oldest: 2021-12-04 18:09:01 -0700
Newest: 2022-01-04 15:22:10 -0700

Failed: 34
Oldest: 2021-09-17 14:37:50 -0600
Newest: 2021-12-30 17:31:10 -0700

Pending: 11
Oldest: 2022-01-04 15:27:10 -0700
Newest: 2022-03-04 14:18:50 -0700

### Status report information ###

Generated at: 2022-01-04 15:25:50 -07:00
`

4660319-zen

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by masteradhoc**
### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:
Change Text for Checkbox due to reasons listed here #31560

Closes #31560 .

### How to test the changes in this Pull Request:

1. go to woocommerce settings
2. visit account area
3. Check Account Creation Part and last checkbox

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [] Have you successfully run tests with your changes locally?

### Changelog entry
Change Checkbox Text to clarify that the user receives a link to set his password instead to send him the password directly
> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

### FOR PR REVIEWER ONLY:

* [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

File: plugins/woocommerce/includes/admin/settings/class-wc-settings-accounts.php [hunk 1]
```diff
@@ -93,7 +93,7 @@ protected function get_settings_for_default_section() {
 				'autoload'      => false,
 			),
 			array(
-				'desc'          => __( 'When creating an account, automatically generate an account password', 'woocommerce' ),
+				'desc'          => __( 'When creating an account, send the new user a link to set his password', 'woocommerce' ),
```
Comment (peterfabian) [inline plugins/woocommerce/includes/admin/settings/class-wc-settings-accounts.php]: Can we please make this more inclusive, i.e. update `his` to `their`?

**Review by peterfabian — COMMENTED** [review]
Thanks for fixing this. Looks good, just one small change, please.

File: plugins/woocommerce/includes/admin/settings/class-wc-settings-accounts.php (hunk 1 above)
Comment (masteradhoc) [reply plugins/woocommerce/includes/admin/settings/class-wc-settings-accounts.php]: ofc. soory - i could have known that ;) @peterfabian

**Review by peterfabian — APPROVED** [review]
Thanks! Looks good now! 👍
