### PR TITLE
[Experimental] Don't trigger hooks in Add to Cart with Options block when simple product is not purchasable

### LINKED ISSUE #56682: Blockified Add to Cart with Options block: don't render hooks content if simple product is out of stock or not purchasable
Since https://github.com/woocommerce/woocommerce/pull/56390, we hide the quantity selector and add to cart button for simple products which are out of stock or not purchasable. We should also hide the content added by PHP filters.

## Steps to reproduce

0. Install and activate the WooCommerce Beta Tester plugin.
0. Go to _Tools_ > _WCA Helper_ > _Features_ and enable `experimental-blocks` and `blockified-add-to-cart`.
1. Install [WooCommerce Product Add-Ons](https://woocommerce.com/products/product-add-ons/).
2. Create an out of stock product with a product add-on.
3. Create a post or page, add the _Single Product_ block and choose the product you just edited.
4. In the frontend, notice the add-on form element is shown but the quantity selector and add to cart button aren't.

Image

Expected behavior: the add-on form element should be hidden as well.

### PR DESCRIPTION
**Pull request by Aljullu**
### Changes proposed in this Pull Request:

This PR makes it so the compatibility later PHP hooks are not run in the Add to Cart with Options block when the form is not rendered. That happens in simple products which are out of stock or not purchasable.

Closes #56682.
Closes WOOPLUG-3602.

### How to test the changes in this Pull Request:

0. Install and activate the WooCommerce Beta Tester plugin.
1. Go to _Tools_ > _WCA Helper_ > _Features_ and enable `experimental-blocks` and `blockified-add-to-cart`.
2. Install [WooCommerce Product Add-Ons](https://woocommerce.com/products/product-add-ons/).
3. Create an out-of-stock product with a product add-on.
4. Create a post or page, add the _Single Product_ block and choose the product you just edited.
5. In the frontend, verify the add-on form element is not shown.

Before | After
--- | ---
imatge | imatge

6. Edit the product again, set it in stock and remove its price, making it not-purchasable.
7. In the frontend, verify again the add-on form element is not shown.

### CODE REVIEW

File: plugins/woocommerce/src/Blocks/BlockTypes/AddToCartWithOptions.php [hunk 1]
```diff
@@ -129,9 +129,10 @@ protected function render( $attributes, $content, $block ) {
 			* @since 7.6.0
 			* @param boolean.
 			*/
-			$is_disabled_compatibility_layer = apply_filters( 'woocommerce_disable_compatibility_layer', false );
+			$is_disabled_compatibility_layer   = apply_filters( 'woocommerce_disable_compatibility_layer', false );
+			$is_not_purchasable_single_product = ProductType::SIMPLE === $product_type && ( ! $product->is_in_stock() || ! $product->is_purchasable() );
```
Comment (Aljullu) [inline plugins/woocommerce/src/Blocks/BlockTypes/AddToCartWithOptions.php]: We have this same check in several files, now. In https://github.com/woocommerce/woocommerce/issues/56558#issuecomment-2785933865 I added a task to evaluate if it would make sense to abstract it into a util.

File: plugins/woocommerce/src/Blocks/BlockTypes/AddToCartWithOptions.php [hunk 2]
```diff
@@ -129,9 +129,10 @@ protected function render( $attributes, $content, $block ) {
...
 
-			if ( ! $is_disabled_compatibility_layer ) {
+			if ( ! $is_disabled_compatibility_layer && ! $is_not_purchasable_single_product ) {
 				ob_start();
 				if ( ProductType::SIMPLE === $product_type ) {
```
Comment (dinhtungdu) [inline plugins/woocommerce/src/Blocks/BlockTypes/AddToCartWithOptions.php]: Nit pick but what do you think about moving this check into the `if` blocks below, like the following? It's just my preference in this case though, as I don't like the combination of a general condition for all product (`$is_disabled_compatibility_layer`) with a specific condition for simple product in a same place.

```suggestion
			if ( ! $is_disabled_compatibility_layer ) {
				ob_start();
				if ( ProductType::SIMPLE === $product_type && $product->is_in_stock() && $product->is_purchasable() ) {
```

Comment (Aljullu) [reply plugins/woocommerce/src/Blocks/BlockTypes/AddToCartWithOptions.php]: Oh, yes, much cleaner. Thanks, I implemented it in de8ca9b869f51f3e493ff4725d14d1b19857df29.

**Review by dinhtungdu — APPROVED** [review]
Thanks for addressing the feedback, the PR is looking and testing good for me.

#### 🖼️ Screenshots/ screen recordings

Left is when the product is purchasable. Right is when the product is not purchasable.

image

#### 📝 List of functionality tested / steps followed
- Activated Product Add-ons extension and configured a global addon for all product.
- Checked to see the addon was rendered for purchasable product.
- Removed the price of the test product, see the addon was rendered.
#### 🌐 Site details
<details><summary>System Status Report</summary>

```
### WordPress Environment ###

WordPress address (URL): [Redacted]
Site address (URL): [Redacted]
WC Version: 9.9.0-dev
Legacy REST API Package Version: The Legacy REST API plugin is not installed on this site.
Action Scheduler Version: ✔ 3.9.2
Log Directory Writable: ✔
WP Version: 6.7.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.25.4
PHP Version: 7.4.33
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 8.5.0
OpenSSL/3.1.4

SUHOSIN Installed: –
MySQL Version: 8.0.33
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

[REDACTED]

### Post Type Counts ###

attachment: 23
global_product_addon: 1
page: 7
post: 2
product: 18
product_variation: 7
revision: 6
wp_font_face: 36
wp_font_family: 12
wp_global_styles: 1
wp_navigation: 1
wp_template: 1

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (2) ###

WooCommerce Product Add-Ons: by Woo – 7.8.1
WooCommerce: by Automattic – 9.9.0-dev

### Inactive Plugins (5) ###

Akismet Anti-spam: Spam Protection: by Automattic - Anti-spam Team – 5.3.6
Hello Dolly: by Matt Mullenweg – 1.7.2
Laravel DD for Wordpress: by Peter Hegman – 1.0.1
WooCommerce: by Automattic – 9.7.1 (update to version 9.8.1 is available)
WooCommerce Beta Tester: by WooCommerce – 3.0.0

### Settings ###

Legacy API Enabled: –
Force SSL: –
Currency: HKD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 15 KB

### WC Pages ###

Shop base: #7 - /shop/
Cart: #8 - /cart/ -  Contains the woocommerce/cart block
Checkout: #9 - /checkout/ -  Contains the woocommerce/checkout block
My account: #10 - /my-account/ -  Contains the [woocommerce_my_account] shortcode
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty-Five
Version: 1.0 (update to version 1.1 is available)
Author URL: https://wordpress.org
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
Theme type: Block theme
WooCommerce Support: ❌ Not declared

### Templates ###

Overrides: /Users/tung/workspace/woocommerce/plugins/woocommerce/templates/block-notices/error.php
/Users/tung/workspace/woocommerce/plugins/woocommerce/templates/block-notices/notice.php
/Users/tung/workspace/woocommerce/plugins/woocommerce/templates/block-notices/success.php


### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
experimental-blocks
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
minified-js
mobile-app-banner
onboarding
onboarding-tasks
pattern-toolkit-full-composability
payment-gateway-suggestions
product-custom-fields
printful
remote-inbox-notifications
remote-free-extensions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page
async-product-editor-category-field
launch-your-store
add-to-cart-with-options-stepper-layout
blockified-add-to-cart
disable-core-profiler-fallback

Disabled Features: product-data-views
coming-soon-newsletter-template
product-pre-publish-modal
settings
product-editor-template-system
use-wp-horizon

Daily Cron: ✔ Next scheduled: 2025-04-11 08:18:38 +00:00
Options: ✔
Notes: 62
Onboarding: completed

### Action Scheduler ###

Complete: 142
Oldest: 2025-03-17 08:19:43 +0000
Newest: 2025-04-10 16:03:20 +0000

Failed: 1
Oldest: 2025-03-17 08:19:52 +0000
Newest: 2025-03-17 08:19:52 +0000

Pending: 1
Oldest: 2025-04-11 08:40:28 +0000
Newest: 2025-04-11 08:40:28 +0000


### Status report information ###

Generated at: 2025-04-10 16:04:28 +00:00
```
</details>
