### PR TITLE
Use enable onboarding path instead of manually setting onboarding option

### LINKED ISSUE #25526: New onboarding feature is not enabled on redirect
**Describe the bug**
When clicking "Yes please" in the old onboarding to opt in to the new onboarding experience, the user is redirected to the dashboard and nothing happens.

This appears to be due to a change in the option name responsible for determining whether or not this new feature is enabled.

**To Reproduce**
1. Create a new site.
1. Install activate WC.
1. Force the new onboarding via `update_option( 'woocommerce_setup_ab_wc_admin_onboarding', 'b' )`
1. Upload and activate https://github.com/woocommerce/woocommerce-admin/releases/tag/v0.25.0-plugin
1. Go to `/wp-admin?page=wc-setup`
1. Click the button to use the new experience.
1. Notice that you're redirected to the dashboard and nothing happens.

**Screenshots**
Screen Shot 2020-01-30 at 12 50 09 PM

**Expected behavior**
Expected to see the onboarding profiler on click.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by joshuatf**
### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Use wc admin built-in methods to enable onboarding

Closes #25526 

### How to test the changes in this Pull Request:

1. Create a new site.
1. Check out this branch
1. Force the new onboarding via `update_option( 'woocommerce_setup_ab_wc_admin_onboarding', 'b' )`
1. Upload and activate https://github.com/woocommerce/woocommerce-admin/releases/tag/v0.25.0-plugin
1. Go to `/wp-admin?page=wc-setup`
1. Click the button to use the new experience.
1. Check that the new onboarding experience is enabled and you end up in the profiler.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### CODE REVIEW

File: includes/admin/class-wc-admin-setup-wizard.php [hunk 1]
```diff
@@ -521,7 +519,7 @@ private function wc_setup_redirect_to_wc_admin_onboarding() {
 		$onboarding_data = get_option( 'wc_onboarding_profile', array() );
 		update_option( 'wc_onboarding_profile', array_merge( $onboarding_data, $profile_updates ) );
 
-		wp_safe_redirect( esc_url_raw( admin_url( 'admin.php?page=wc-admin' ) ) );
+		wp_safe_redirect( wc_admin_url( '&enable_onboarding=1' ) );
```
Comment (timmyc) [inline includes/admin/class-wc-admin-setup-wizard.php]: I realize the only current code path to this method already has a check to ensure `wc_admin_url` exists, but should we add one here now too just to be extra safe?

File: includes/admin/class-wc-admin-setup-wizard.php [hunk 2]
```diff
@@ -521,7 +519,7 @@ private function wc_setup_redirect_to_wc_admin_onboarding() {
 		$onboarding_data = get_option( 'wc_onboarding_profile', array() );
 		update_option( 'wc_onboarding_profile', array_merge( $onboarding_data, $profile_updates ) );
```
Comment (rrennick) [inline includes/admin/class-wc-admin-setup-wizard.php]: @joshuatf `wc_onboarding_profile` should also be updated.

File: includes/admin/class-wc-admin-setup-wizard.php (hunk 1 above)
Comment (rrennick) [reply includes/admin/class-wc-admin-setup-wizard.php]: This redirect should also have an `exit;`

File: includes/admin/class-wc-admin-setup-wizard.php (hunk 2 above)
Comment (claudiosanches) [inline includes/admin/class-wc-admin-setup-wizard.php]: Sorry for not realize it before, but using `wc_` prefix for options on WooCommerce isn't a good think, we only use `woocommerce_` prefix for options on core.
Also since it uses `wc_` prefix it doesn't get removed while running the [`uninstall.php`](https://github.com/woocommerce/woocommerce/blob/master/uninstall.php#L54).

@timmyc should be nice to fix those before merging WooCommerce Admin into core.

**Review by claudiosanches — DISMISSED** [review]
There's a few problems in this code, probably the most important now is what @rrennick pointed out about missing an `exit()` after `wp_safe_redirect()`.

File: includes/admin/class-wc-admin-setup-wizard.php (hunk 1 above)
Comment (joshuatf) [reply includes/admin/class-wc-admin-setup-wizard.php]: There's actually an `exit` above right after this is called, but moved it down here to avoid any confusion.

File: includes/admin/class-wc-admin-setup-wizard.php (hunk 2 above)
Comment (joshuatf) [reply includes/admin/class-wc-admin-setup-wizard.php]: Good catch, @rrennick

Comment (joshuatf) [reply includes/admin/class-wc-admin-setup-wizard.php]: Thanks for the review, @claudiosanches!  Addressed the changes mentioned above.

>should be nice to fix those before merging WooCommerce Admin into core.

I think they're all fixed in wc-admin and just needed to be updated here.  May be worthwhile to move some of this onboarding "reset" functionality into wc-admin so core doesn't need to know much about the logic behind each option; will follow-up on that in the upcoming weeks.

File: includes/admin/class-wc-admin-setup-wizard.php (hunk 1 above)
Comment (joshuatf) [reply includes/admin/class-wc-admin-setup-wizard.php]: >I realize the only current code path to this method already has a check to ensure wc_admin_url exists, but should we add one here now too just to be extra safe?

Added in https://github.com/woocommerce/woocommerce/pull/25527/commits/236bae9b6a8ed06f638e66cb0e2e4ba8b11fbd11

**Review by peterfabian — APPROVED** [review]
Tested and seems to be working fine. 
@claudiosanches please check if you see any other issues.
