### PR TITLE
[Performance] Products: edge-case, address attributes metas migration causing perfromance issues

### LINKED ISSUE #38877: WC_Product_Variable_Data_Store_CPT: Read attributes from post meta -> can cause timeouts
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When a product is called the method WC_Product_Variable_Data_Store_CPT::read_attributes is called for each product_id. In the part where data integrity is maintained (currently line 52-67) oldmeta data is called can updated with new sanitized name. Since it fetches all meta_keys only by old slug, it can cause huge problems when updating thousands of meta_keys with same name.

image (1)

### Expected behavior

It should not run into memory exhaus errors or timeouts and it should not update all metakeys at once but only those for the currently fetched product which is way easier on the database. <br>so the code should look like

`$old_meta_rows = $wpdb->get_results( $wpdb->prepare( "SELECT post_id, meta_value FROM {$wpdb->postmeta} WHERE meta_key = %s and post_id = %d;", [$old_slug, $product->get_id()] ) );`

### Actual behavior

Worst case (our case f.e.) it had to update 100k meta_keys at once for each product fetched.

The part looks like this<br>`$old_meta_rows = $wpdb->get_results( $wpdb->prepare( "SELECT post_id, meta_value FROM {$wpdb->postmeta} WHERE meta_key = %s;", $old_slug ) );`

### Steps to reproduce

1. add lot of products (> 10k) with variations (10+ per product) and "old named" attributes f.e. "damenherren"
2. open products list in admin
3. it should crash

### WordPress Environment

\`

### WordPress Environment

WordPress address (URL): [https://www.emotion-ebikes.de](<https://www.emotion-ebikes.de>)<br>Site address (URL): [https://www.emotion-ebikes.de](<https://www.emotion-ebikes.de>)<br>WC Version: 7.8.0<br>REST API Version: ✔ 7.8.0<br>WC Blocks Version: ✔ 10.2.3<br>Action Scheduler Version: ✔ 3.5.4<br>Log Directory Writable: ✔<br>WP Version: 6.2.2<br>WP Multisite: –<br>WP Memory Limit: 2 GB<br>WP Debug Mode: –<br>WP Cron: –<br>Language: de_DE<br>External object cache: –

### Server Environment

Server Info: Apache<br>PHP Version: 7.4.33<br>PHP Post Max Size: 128 MB<br>PHP Time Limit: 120<br>PHP Max Input Vars: 3000<br>cURL Version: 7.29.0<br>NSS/3.53.1

SUHOSIN Installed: –<br>MySQL Version: 5.5.5-10.7.8-MariaDB-1:10.7.8+maria\~ubu2004-log<br>Max Upload Size: 128 MB<br>Default Timezone is UTC: ✔<br>fsockopen/cURL: ✔<br>SoapClient: ✔<br>DOMDocument: ✔<br>GZip: ✔<br>Multibyte String: ✔<br>Remote Post: ✔<br>Remote Get: ✔

### Database

WC Database Version: 7.8.0<br>WC Database Prefix: wp\_<br>Datenbank-Gesamtgröße: 4462.66MB<br>Datenbank-Datengröße: 3799.77MB<br>Datenbank-Indexgröße: 662.89MB<br>wp_woocommerce_sessions: Daten: 1.02MB + Index: 0.02MB + Engine InnoDB<br>wp_woocommerce_api_keys: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB<br>wp_woocommerce_attribute_taxonomies: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB<br>wp_woocommerce_downloadable_product_permissions: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB<br>wp_woocommerce_order_items: Daten: 3.52MB + Index: 1.52MB + Engine InnoDB<br>wp_woocommerce_order_itemmeta: Daten: 37.58MB + Index: 33.11MB + Engine InnoDB<br>wp_woocommerce_tax_rates: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB<br>wp_woocommerce_tax_rate_locations: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB<br>wp_woocommerce_shipping_zones: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB<br>wp_woocommerce_shipping_zone_locations: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB<br>wp_woocommerce_shipping_zone_methods: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB<br>wp_woocommerce_payment_tokens: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB<br>wp_woocommerce_payment_tokenmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB<br>wp_woocommerce_log: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB<br>wp_actionscheduler_actions: Daten: 0.48MB + Index: 0.58MB + Engine InnoDB<br>wp_actionscheduler_claims: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB<br>wp_actionscheduler_groups: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB<br>wp_actionscheduler_logs: Daten: 0.39MB + Index: 0.25MB + Engine InnoDB<br>wp_apto_sort_list: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB<br>wp_aryo_activity_log: Daten: 17.52MB + Index: 0.00MB + Engine InnoDB<br>wp_borlabs_cookie_consent_log: Daten: 28.56MB + Index: 11.58MB + Engine InnoDB<br>wp_borlabs_cookie_content_blocker: Daten: 0.06MB + Index: 0.02MB + Engine InnoDB<br>wp_borlabs_cookie_cookies: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB<br>wp_borlabs_cookie_groups: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB<br>wp_borlabs_cookie_script_blocker: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB<br>wp_borlabs_cookie_statistics: Daten: 20.06MB + Index: 26.09MB + Engine InnoDB<br>wp_commentmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB<br>wp_comments: Daten: 14.52MB + Index: 9.09MB + Engine InnoDB<br>wp_duplicator_pro_entities: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB<br>wp_duplicator_pro_packages: Daten: 0.11MB + Index: 0.02MB + Engine InnoDB<br>wp_hook_list: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB<br>wp_icl_background_task: Daten: 0.09MB + Index: 0.00MB + Engine InnoDB<br>wp_icl_cms_nav_cache: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB<br>wp_icl_content_status: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB<br>wp_icl_core_status: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB<br>wp_icl_flags: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB<br>wp_icl_languages: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB<br>wp_icl_languages_translations: Daten: 0.19MB + Index: 0.09MB + Engine InnoDB<br>wp_icl_locale_map: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB<br>wp_icl_message_status: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB<br>wp_icl_mo_files_domains: Daten: 0.06MB + Index: 0.02MB + Engine InnoDB<br>wp_icl_node: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB<br>wp_icl_reminders: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB<br>wp_icl_strings: Daten: 1.52MB + Index: 1.09MB + Engine InnoDB<br>wp_icl_string_batches: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB<br>wp_icl_string_packages: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB<br>wp_icl_string_pages: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB<br>wp_icl_string_positions: Daten: 0.08MB + Index: 0.02MB + Engine InnoDB<br>wp_icl_string_status: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB<br>wp_icl_string_translations: Daten: 0.05MB + Index: 0.03MB + Engine InnoDB<br>wp_icl_string_urls: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB<br>wp_icl_translate: Daten: 43.55MB + Index: 2.52MB + Engine InnoDB<br>wp_icl_translate_job: Daten: 0.38MB + Index: 0.13MB + Engine InnoDB<br>wp_icl_translations: Daten: 24.56MB + Index: 59.22MB + Engine InnoDB<br>wp_icl_translation_batches: Daten: 0.05MB + Index: 0.00MB + Engine InnoDB<br>wp_icl_translation_downloads: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB<br>wp_icl_translation_status: Daten: 45.55MB + Index: 4.52MB + Engine InnoDB<br>wp_ju_queue: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB<br>wp_links: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB<br>wp_mc4wp_log: Daten: 1.52MB + Index: 0.00MB + Engine InnoDB<br>wp_mclean_refs: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB<br>wp_mclean_scan: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB<br>wp_options: Daten: 67.19MB + Index: 14.06MB + Engine InnoDB<br>wp_postmeta: Daten: 3232.98MB + Index: 371.69MB + Engine InnoDB<br>wp_posts: Daten: 183.72MB + Index: 68.22MB + Engine InnoDB<br>wp_redirection_404: Daten: 21.05MB + Index: 12.08MB + Engine InnoDB<br>wp_redirection_groups: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB<br>wp_redirection_items: Daten: 1.52MB + Index: 0.52MB + Engine InnoDB<br>wp_redirection_logs: Daten: 2.02MB + Index: 0.30MB + Engine InnoDB<br>wp_termmeta: Daten: 2.52MB + Index: 0.17MB + Engine InnoDB<br>wp_terms: Daten: 0.06MB + Index: 0.06MB + Engine InnoDB<br>wp_term_relationships: Daten: 11.55MB + Index: 8.52MB + Engine InnoDB<br>wp_term_taxonomy: Daten: 0.25MB + Index: 0.09MB + Engine InnoDB<br>wp_usermeta: Daten: 0.23MB + Index: 0.06MB + Engine InnoDB<br>wp_users: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB<br>wp_wc_admin_notes: Daten: 0.05MB + Index: 0.00MB + Engine InnoDB<br>wp_wc_admin_note_actions: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB<br>wp_wc_category_lookup: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB<br>wp_wc_customer_lookup: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB<br>wp_wc_download_log: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB<br>wp_wc_order_coupon_lookup: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB<br>wp_wc_order_product_lookup: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB<br>wp_wc_order_stats: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB<br>wp_wc_order_tax_lookup: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB<br>wp_wc_product_attributes_lookup: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB<br>wp_wc_product_download_directories: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB<br>wp_wc_product_meta_lookup: Daten: 21.06MB + Index: 30.11MB + Engine InnoDB<br>wp_wc_rate_limits: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB<br>wp_wc_reserved_stock: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB<br>wp_wc_tax_rate_classes: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB<br>wp_wc_webhooks: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB<br>wp_woof_query_cache: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB<br>wp_woof_stat_buffer: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM<br>wp_woof_stat_tmp: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM<br>wp_wpgb_cards: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB<br>wp_wpgb_facets: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB<br>wp_wpgb_grids: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB<br>wp_wpgb_index: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB<br>wp_wpr_rocket_cache: Daten: 0.23MB + Index: 0.36MB + Engine InnoDB<br>wp_wpr_rucss_used_css: Daten: 0.02MB + Index: 0.09MB + Engine InnoDB<br>wp_yoast_indexable: Daten: 8.52MB + Index: 4.44MB + Engine InnoDB<br>wp_yoast_indexable_hierarchy: Daten: 0.48MB + Index: 0.67MB + Engine InnoDB<br>wp_yoast_migrations: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB<br>wp_yoast_primary_term: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB<br>wp_yoast_seo_links: Daten: 0.14MB + Index: 0.11MB + Engine InnoDB<br>wp_yoast_seo_meta: Daten: 3.52MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts

acf-field: 703<br>acf-field-group: 45<br>apto_sort: 34<br>attachment: 259640<br>guideme: 3<br>location: 101<br>mc4wp-form: 3<br>nav_menu_item: 90<br>oembed_cache: 25<br>page: 170<br>post: 16<br>product: 14128<br>product_variation: 102247<br>revision: 298<br>shop_order: 26194<br>wpcf7_contact_form: 5

### Security

Secure connection (HTTPS): ✔<br>Hide errors from visitors: ✔

### Active Plugins (28)

Query Monitor: von John Blackbourn – 3.12.3<br>WPML Multilingual CMS: von OnTheGoSystems – 4.6.3<br>Advanced Custom Fields Multilingual: von OnTheGoSystems – 2.0.5<br>Advanced Custom Fields PRO: von WP Engine – 6.1.6<br>Advanced Custom Fields: Table Field: von Johann Heyne – 1.3.20<br>Advanced Post Types Order: von Nsp Code – 4.8.3<br>Advanced Taxonomy Terms Order: von Nsp Code – 3.2.8<br>Borlabs Cookie - Cookie Opt-in: von Borlabs GmbH – 2.2.64<br>Breadcrumb NavXT: von John Havlik – 6.6.0<br>Classic Editor: von WordPress-Mitwirkende – 1.6.3<br>Contact Form 7: von Takayuki Miyoshi – 5.2.2<br>Yoast Duplicate Post: von Enrico Battocchi & Team Yoast – 4.5<br>Duplicator Pro: von Duplicator – 4.5.11.1<br>Index WP MySQL For Speed: von Oliver Jones<br>Rick James – 1.4.13

MC4WP: Mailchimp for WordPress: von ibericode – 4.9.5<br>MC4WP: Mailchimp for WordPress Premium: von ibericode – 4.9.3<br>Redirection: von John Godley – 5.3.10<br>WooCommerce Multilingual & Multi-Currency: von OnTheGoSystems – 5.1.3<br>WooCommerce: von Automattic – 7.8.0<br>Yoast SEO: von Team Yoast – 20.9<br>WP Media folder: von Joomunited – 5.4.8<br>WP Rocket: von WP Media – 3.14<br>WPML CMS Nav: von OnTheGoSystems – 1.5.5<br>WPML Media: von OnTheGoSystems – 2.7.2<br>WPML String Translation: von OnTheGoSystems – 3.2.5<br>WPS Hide Login: von WPServeur<br>NicolasKulka<br>wpformation – 1.9.8

Yoast Test Helper: von Team Yoast – 1.17

### Inactive Plugins (14)

ACF Content Analysis for Yoast SEO: von Thomas Kräftner<br>ViktorFroberg<br>marol87<br>pekz0r<br>angrycreative<br>Team Yoast – 3.1

Activity Log: von Activity Log Team – 2.8.6<br>Advanced Database Cleaner: von Younes JFR. – 3.1.2<br>Beautiful taxonomy filter: von Jonathan de Jong – 2.4.3<br>Cookie Notice & Compliance for GDPR / CCPA: von [Hu-manity.co](<http://Hu-manity.co>) – 2.4.8<br>Debug Bar: von wordpressdotorg – 1.1.4<br>e-motion Airtable 2 WordPress: von ROARK – 1.0.3<br>e-motion Technologies Addons: von ROARK – 4.4.7<br>Force Regenerate Thumbnails: von Exactly WWW – 2.1.2<br>Preview E-mails for WooCommerce: von Digamber Pradhan – 2.1.3<br>Rewrite Rules Inspector: von Automattic<br>Daniel Bachhuber – 1.3.1

WP-Sweep: von Lester 'GaMerZ' Chan – 1.1.8<br>WP Grid Builder: von Loïc Blascos – 1.7.5<br>WP Grid Builder - Map Facet: von Loïc Blascos – 1.4.3

### Dropin Plugins (4)

advanced-cache.php: advanced-cache.php<br>db-error.php: db-error.php<br>db.php: Query Monitor Database Class (Drop-in)<br>maintenance.php: maintenance.php

### Must Use Plugins (1)

Index WP MySQL For Speed Upgrade Filter for mu-plugins.: von  – 1.4.12

### Settings

API Enabled: ✔<br>Force SSL: –<br>Currency: EUR (€)<br>Currency Position: right_space<br>Thousand Separator: .<br>Decimal Separator: ,<br>Number of Decimals: 2<br>Taxonomies: Product Types: simple (simple)<br>grouped (grouped)<br>variable (variable)<br>external (external)

Taxonomies: Product Visibility: rated-3 (rated-3)<br>rated-4 (rated-4)<br>rated-5 (rated-5)<br>exclude-from-search (exclude-from-search)<br>exclude-from-catalog (exclude-from-catalog)<br>featured (featured)<br>outofstock (outofstock)<br>rated-1 (rated-1)<br>rated-2 (rated-2)

Connected to [WooCommerce.com](<http://WooCommerce.com>): –<br>Enforce Approved Product Download Directories: –<br>HPOS feature screen enabled: –<br>HPOS feature enabled: –<br>Order datastore: WC_Order_Data_Store_CPT<br>HPOS data sync enabled: –

### WC Pages

Shop-Basis: #4 - /shop/<br>Warenkorb: #6 - /traum-e-bike/<br>Kasse: #8 - /kasse/<br>Mein Konto: #10 - /mein-konto/<br>Allgemeine Geschäftsbedingungen: ❌ Seite nicht festgelegt

### Theme

Name: Emotion Technologies<br>Version: 1.1<br>Author URL: [http://www.green-eye.de](<http://www.green-eye.de>)<br>Child Theme: ❌ – Wenn du WooCommerce mit einem Theme<br>das du nicht selbst entwickelt hast<br>an eigene Bedürfnisse anpasst<br>dann empfehlen wir die Verwendung eines Child-Themes. Siehe Wie du ein Child-Theme erstellst (engl.)

WooCommerce Support: ✔

### Templates

Overrides: emotiontechnologies/woocommerce/archive-product.php Version 2.0.0 ist veraltet. Die Hauptversion ist 3.4.0<br>emotiontechnologies/woocommerce/cart/cart-item-data.php<br>emotiontechnologies/woocommerce/cart/cart-totals.php<br>emotiontechnologies/woocommerce/cart/cart.php Version 3.1.0 ist veraltet. Die Hauptversion ist 7.8.0<br>emotiontechnologies/woocommerce/cart/proceed-to-checkout-button.php Version 2.4.0 ist veraltet. Die Hauptversion ist 7.0.1<br>emotiontechnologies/woocommerce/checkout/form-billing.php Version 3.0.9 ist veraltet. Die Hauptversion ist 3.6.0<br>emotiontechnologies/woocommerce/checkout/form-checkout.php Version 2.3.0 ist veraltet. Die Hauptversion ist 3.5.0<br>emotiontechnologies/woocommerce/checkout/form-shipping.php Version 3.0.9 ist veraltet. Die Hauptversion ist 3.6.0<br>emotiontechnologies/woocommerce/checkout/payment.php Version 3.4.0 ist veraltet. Die Hauptversion ist 7.8.0<br>emotiontechnologies/woocommerce/checkout/review-order.php Version 2.3.0 ist veraltet. Die Hauptversion ist 5.2.0<br>emotiontechnologies/woocommerce/checkout/thankyou.php Version 3.2.0 ist veraltet. Die Hauptversion ist 3.7.0<br>emotiontechnologies/woocommerce/content-product.php Version 3.0.0 ist veraltet. Die Hauptversion ist 3.6.0<br>emotiontechnologies/woocommerce/content-single-product.php Version 3.0.0 ist veraltet. Die Hauptversion ist 3.6.0<br>emotiontechnologies/woocommerce/emails/admin-new-order.php Version 2.5.0 ist veraltet. Die Hauptversion ist 3.7.0<br>emotiontechnologies/woocommerce/emails/customer-processing-order.php Version 2.5.0 ist veraltet. Die Hauptversion ist 3.7.0<br>emotiontechnologies/woocommerce/emails/email-addresses.php Version 3.2.1 ist veraltet. Die Hauptversion ist 5.6.0<br>emotiontechnologies/woocommerce/emails/email-customer-details.php<br>emotiontechnologies/woocommerce/emails/email-footer.php Version 2.3.0 ist veraltet. Die Hauptversion ist 7.4.0<br>emotiontechnologies/woocommerce/emails/email-header.php Version 2.4.0 ist veraltet. Die Hauptversion ist 7.4.0<br>emotiontechnologies/woocommerce/emails/email-order-details.php Version 3.2.0 ist veraltet. Die Hauptversion ist 3.7.0<br>emotiontechnologies/woocommerce/emails/email-order-items.php Version 3.2.0 ist veraltet. Die Hauptversion ist 3.7.0<br>emotiontechnologies/woocommerce/emails/email-styles.php Version 2.3.0 ist veraltet. Die Hauptversion ist 7.4.0<br>emotiontechnologies/woocommerce/global/breadcrumb.php<br>emotiontechnologies/woocommerce/loop/loop-start.php Version 2.0.0 ist veraltet. Die Hauptversion ist 3.3.0<br>emotiontechnologies/woocommerce/loop/no-products-found.php Version 2.0.0 ist veraltet. Die Hauptversion ist 7.8.0<br>emotiontechnologies/woocommerce/loop/orderby.php Version 2.2.0 ist veraltet. Die Hauptversion ist 3.6.0<br>emotiontechnologies/woocommerce/loop/pagination.php<br>emotiontechnologies/woocommerce/loop/price.php<br>emotiontechnologies/woocommerce/loop/result-count.php Version 3.0.0 ist veraltet. Die Hauptversion ist 3.7.0<br>emotiontechnologies/woocommerce/order/order-details-item.php Version 3.7.0 ist veraltet. Die Hauptversion ist 5.2.0<br>emotiontechnologies/woocommerce/order/order-details.php Version 3.7.0 ist veraltet. Die Hauptversion ist 7.8.0<br>emotiontechnologies/woocommerce/product-searchform.php Version 2.5.0 ist veraltet. Die Hauptversion ist 7.0.1<br>emotiontechnologies/woocommerce/single-product/add-to-cart/simple.php Version 3.0.0 ist veraltet. Die Hauptversion ist 7.0.1<br>emotiontechnologies/woocommerce/single-product/add-to-cart/variable.php Version 3.0.0 ist veraltet. Die Hauptversion ist 6.1.0<br>emotiontechnologies/woocommerce/single-product/add-to-cart/variation-add-to-cart-button.php Version 3.0.0 ist veraltet. Die Hauptversion ist 7.0.1<br>emotiontechnologies/woocommerce/single-product/add-to-cart/variation.php<br>emotiontechnologies/woocommerce/single-product/meta.php<br>emotiontechnologies/woocommerce/single-product/photoswipe.php<br>emotiontechnologies/woocommerce/single-product/product-attributes.php Version 3.1.0 ist veraltet. Die Hauptversion ist 3.6.0<br>emotiontechnologies/woocommerce/single-product/product-image.php Version 3.1.0 ist veraltet. Die Hauptversion ist 7.8.0<br>emotiontechnologies/woocommerce/single-product/product-thumbnails.php Version 3.1.0 ist veraltet. Die Hauptversion ist 3.5.1<br>emotiontechnologies/woocommerce/single-product/related.php Version 3.0.0 ist veraltet. Die Hauptversion ist 3.9.0<br>emotiontechnologies/woocommerce/single-product/tabs/tabs.php Version 2.4.0 ist veraltet. Die Hauptversion ist 3.8.0<br>emotiontechnologies/woocommerce/single-product.php<br>emotiontechnologies/woocommerce/content-product_cat.php Version 2.6.1 ist veraltet. Die Hauptversion ist 4.7.0

Outdated Templates: ❌

```
					Erfahre
```

wie du aktualisieren kannst

### Admin

Enabled Features: activity-panels<br>analytics<br>product-block-editor<br>coupons<br>customer-effort-score-tracks<br>import-products-task<br>experimental-fashion-sample-products<br>shipping-smart-defaults<br>shipping-setting-tour<br>homescreen<br>marketing<br>mobile-app-banner<br>navigation<br>onboarding<br>onboarding-tasks<br>remote-inbox-notifications<br>remote-free-extensions<br>payment-gateway-suggestions<br>shipping-label-banner<br>subscriptions<br>store-alerts<br>transient-notices<br>woo-mobile-welcome<br>wc-pay-promotion<br>wc-pay-welcome-page

Disabled Features: core-profiler<br>minified-js<br>new-product-management-experience<br>product-variation-management<br>settings<br>async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2023-06-23 06:29:11 +00:00<br>Options: ✔<br>Notes: 45<br>Onboarding: skipped

### Action Scheduler

Abgeschlossen: 1.651<br>Oldest: 2023-05-25 14:04:27 +0000<br>Newest: 2023-06-22 10:21:24 +0000

Fehlgeschlagen: 3<br>Oldest: 2023-06-16 13:07:16 +0000<br>Newest: 2023-06-16 16:15:04 +0000

Ausstehend: 1<br>Oldest: 2023-06-22 13:05:03 +0000<br>Newest: 2023-06-22 13:05:03 +0000

### Status report information

Generated at: 2023-06-22 12:42:52 +00:00<br>\`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](<https://woocommerce.com/storefront/>).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by kalessil**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes #38877, WOOPLUG-1335.

Addresses performance issues related to the metas migration introduced in https://github.com/woocommerce/woocommerce/pull/17784: the migration is limited to product-only.

### How to test the changes in this Pull Request:

- Covered by the new test case
- No manual testing required

### CODE REVIEW

File: plugins/woocommerce/tests/php/includes/data-stores/class-wc-product-variable-data-store-cpt-test.php [hunk 1]
```diff
@@ -706,4 +706,60 @@ public function test_read_children_with_validation_failure() {
 			'Transient should not be set when validation fails'
 		);
 	}
+
+	/**
+	 * Tests `read_attributes` for handling metas migration due to sanitize_title BC breaks.
+	 */
+	public function test_read_attributes_addresses_bc_break_in_sanitize(): void {
```
Comment (jorgeatorres) [inline plugins/woocommerce/tests/php/includes/data-stores/class-wc-product-variable-data-store-cpt-test.php:713]: I'm not sure this test is entirely correct as under normal circumstances attributes would only be set on a variable product, not a regular one.
It also sets `_product_attributes` and `attribute_...` meta on the product, which doesn't reflect real circumstances.

**Review by jorgeatorres — CHANGES_REQUESTED** [review]
Hey @kalessil!

Thanks for the PR. While the intention is clear and the existing on-the-fly migration less than ideal when there are a lot of variations, the new behavior is not entirely correct: `_product_attributes` is a meta set on the parent (variable) product while the different `attribute_` metas are set on the individual variations. That's why the original code tried to update that on all products and not just the current one.

The new code performs all the checks and acts only on the parent product, so this effectively means we don't perform the migration.

I still think there are opportunities here to improve performance, such as limiting the update to _all_ variations within the product or even doing the updates via SQL, but I'm sure you have way better ideas than me so looking forward to the next round of review! 😸 

As for "how to reproduce" the behavior I mentioned above above:

1. Create a variable product on the admin with a "Size/Style" attribute (that is not a taxonomy) and a few terms (say, "Small | Medium"). Take note of the product ID.
2. Generate the variations for those attributes and publish.
3. Simulate the WP 4.9 sanitization style:
   ```shell
   wp post meta update PRODUCT_ID _product_attributes 'a:1:{s:9:"sizestyle";a:3:{s:4:"name";s:10:"Size/Style";s:5:"value";s:21:"Small | Medium | Large";s:12:"is_variation";i:1;}}' --format=plaintext
   wp db query "UPDATE $(wp db prefix)postmeta SET meta_key = 'attribute_sizestyle' WHERE meta_key = 'attribute_size-style'"
   ```
4. Refresh the admin edit screen for the product:
   - On `trunk` everything will be as normal and you can confirm in the database that meta on the children products has been added with `attribute_size-style` as key.
   - On this branch, the attributes will remain on the parent but the variations will now be "disconnected" from their original values.

File: plugins/woocommerce/tests/php/includes/data-stores/class-wc-product-variable-data-store-cpt-test.php (hunk 1 above)
Comment (kalessil) [reply plugins/woocommerce/tests/php/includes/data-stores/class-wc-product-variable-data-store-cpt-test.php:713]: Ok, I'll reiterate on the changes. Thanks for the feedback!

**Comment by kalessil** [comment]
@jorgeatorres : I updated PR as per the last review - updated test and migration itself, so the changes in there are closer to the original code (just injecting posts ids into SQL - to compensate for the ack of the context on my end)

File: plugins/woocommerce/includes/data-stores/class-wc-product-variable-data-store-cpt.php [hunk 2]
```diff
@@ -52,15 +53,24 @@ protected function read_attributes( &$product ) {
...
+				// Maintain data integrity: WordPress 4.9 changed sanitization functions, and we update the values here so variations function correctly.
+				// As per 2026, we are refactoring the updates into product-level: BC-focused (not all-in on-spot migration), optimized for performance.
+				// Use-case: `_product_attributes` has data populated on WordPress pre-4.8 and containing symbols affected by the breaking changes.
 				if ( $meta_value['is_variation'] && strstr( $meta_value['name'], '/' ) && sanitize_title( $meta_value['name'] ) !== $meta_attribute_key ) {
 					global $wpdb;
 
-					$old_slug      = 'attribute_' . $meta_attribute_key;
-					$new_slug      = 'attribute_' . sanitize_title( $meta_value['name'] );
-					$old_meta_rows = $wpdb->get_results( $wpdb->prepare( "SELECT post_id, meta_value FROM {$wpdb->postmeta} WHERE meta_key = %s;", $old_slug ) ); // WPCS: db call ok, cache ok.
+					$products_to_migrate = implode( ', ', array( $product_id, ...$product->get_children() ) );
```
Comment (jorgeatorres) [inline plugins/woocommerce/includes/data-stores/class-wc-product-variable-data-store-cpt.php]: We don't need to include `$product_id` in the array. `attribute_X` meta keys are only set on children.

**Review by jorgeatorres — APPROVED** [review]
@kalessil: Thanks for making the changes. I'm pre-approving with just one nit, but this looks good to me.

File: plugins/woocommerce/includes/data-stores/class-wc-product-variable-data-store-cpt.php (hunk 2 above)
Comment (kalessil) [reply plugins/woocommerce/includes/data-stores/class-wc-product-variable-data-store-cpt.php]: Sounds good, I'll update PR accordingly and merge afterwards. Thanks for the guidance again 🙇

Comment (kalessil) [reply plugins/woocommerce/includes/data-stores/class-wc-product-variable-data-store-cpt.php]: Done in 00667d3aa677a5f0dac4863842ba9cc51d2be6dc
