### PR TITLE
[COT/HPOS] Fix trashing/untrashing of orders

### LINKED ISSUE #35089: [COT/HPOS] Trashing an order does not trigger an update to the posts table
While working on https://github.com/woocommerce/woocommerce/pull/35087 I noticed that, when COT is authoritative and sync is enabled, trashing an order does not impact the status of the matching post table record.

To replicate (current trunk code):

1. Set COT to authoritative, enable sync.
2. Trash an order.
3. Try to use the 'trash' link in the admin list table.
4. The order is instantly set back to its original status (it's as if it is automatically untrashed).

This is probably because, when we read an order, we also load the matching post record and if we notice a discrepancy (in this case, that will be the post status/order status), the post table's version of events 'wins'.

### PR DESCRIPTION
**Pull request by Konamiman**
-   [ ] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
-   [ ] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
-   [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change?

### Changes proposed in this Pull Request:

This pull request fixes some small bugs:

1. Trashing an order when COT was authoritative and sync was enabled didn't update the update date of the COT record. This caused that the next time the order was read it was untrashed (per the change introduced in https://github.com/woocommerce/woocommerce/pull/34465).
2. Similarly, trashing an order when COT was authoritative and sync was enabled wasn't trashing the equivalent entry in the posts table.
3. When an order was untrashed the corresponding `_wp_trash_meta_status` and `_wp_trash_meta_time` meta records weren't deleted. Thus if the order was trashed and untrashed repeatedly new meta rows would be created every time that would end up piling up in the meta table.
4. The change introduced in https://github.com/woocommerce/woocommerce/pull/34465 was unnecessarily re-syncing the orders when the update dates in COT and in the posts table were identical.
5. It was possible to load the order details in Admin when the order was trashed via direct URL. Now this shows an error in the same way as when posts is authoritative.

Closes #35089.

### How to test the changes in this Pull Request:

1. With COT enabled and sync active trash an order.
2. Verify that you can't access the order via Admin (navigate to `/wp-admin/admin.php?page=wc-orders&id=<order id>&action=edit` and you'll get an error).
3. Verify that the corresponding entry in the posts table is also trashed.
4. Go to the trashed orders view, then to the all orders view, verify that the order doesn't get untrashed automatically.
5. Untrash the order and verify that the order has the proper status and that there aren't `_wp_trash_meta_status` entries in the `wp_wc_orders_meta` table for the order.
6. Verify that the sync in the opposite direction (posts to COT) still works for the trash-untrash cycle (note that in this case you need to manually trigger the sync).
7. Manually alter the entry in posts table for an order, load the order, and verify that the data in COT has been synced with the changes you introduced (aka verify that https://github.com/woocommerce/woocommerce/pull/34465 still works).

### Other information:

-   [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
-   [ ] Have you written new tests for your changes, as applicable?
-   [ ] Have you successfully run tests with your changes locally?
-   [ ] Have you created a changelog file for each project being changed, ie `pnpm --filter=<project> run changelog add`?

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

File: plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableDataStore.php [hunk 1]
```diff
@@ -1059,9 +1059,7 @@ private function maybe_sync_order( \WC_Abstract_Order &$order, \WC_Abstract_Orde
 		 *
 		 * So we write back to the order table when order modified date is more recent than post modified date. Otherwise, we write to the post table.
 		 */
-		if ( $order_modified_date > $post_order_modified_date ) {
-			return;
-		} else {
+		if ( $post_order_modified_date > $order_modified_date ) {
```
Comment (barryhughes) [inline plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableDataStore.php]: If we're just simplifying the code down to keep things nice and clean, this would maintain the previous behaviour (in which we would also call `migrate_post_record` when the modification dates are equal):

```suggestion
		if ( $post_order_modified_date >= $order_modified_date ) {
```

This also fixes the three `OrdersTableDataStoreTests` fails.

File: plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableDataStore.php [hunk 2]
```diff
@@ -1757,13 +1755,21 @@ public function trash_order( $order ) {
...
-			array( '%s' ),
+			array( '%s', '%s' ),
 			array( '%d' )
 		);
 
 		$order->set_status( 'trash' );
+
+		$data_synchronizer = wc_get_container()->get( DataSynchronizer::class );
+		if ( $data_synchronizer->data_sync_is_enabled() ) {
+			wp_trash_post( $order->get_id() );
```
Comment (barryhughes) [inline plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableDataStore.php:1789]: > Untrash the order and verify that the order has the proper status

☝🏽 This part is not working for me (COT authoritative, sync enabled).

It looks to me like we store the pre-trash status and trash time as order meta data, just [a few lines above](https://github.com/woocommerce/woocommerce/pull/35125/files#diff-8c34c1a6f743002d1f2db13c299d2086d0209889f72abc86bef3bd734abb2585R1741-R1754) this point. Then execution reaches here and we trash the corresponding post record ... the problem is that those bits of meta data never makes it across to the post meta table. The result is the order is not restored to its original status when it is untrashed.

Steps to replicate:

1. Check out this branch, set COT to authoritative, enable sync.
2. Select an order that is **not** *pending payment,* note its status and trash it.
3. Visit the trashed orders view.
4. Untrash the order, note it will have been incorrectly restored to *pending payment* status (which is the default we use when the original status is not known).

**Review by barryhughes — CHANGES_REQUESTED** [review]

File: plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableDataStore.php (hunk 1 above)
Comment (Konamiman) [reply plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableDataStore.php]: I neglected the tests, my fault. But the removal of the `=` comparison is on purpose (the "cleanification" of the code was just a side effect): if both records have the exact same update date it means that they are in sync and thus there is no need to migrate, right?

File: plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableDataStore.php (hunk 2 above)
Comment (Konamiman) [reply plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableDataStore.php:1789]: I can't reproduce this. I have tried with "on hold", "processing" and "complete" and in all cases:

1. Trashing the order generates the proper meta items in both meta tables:

image

2. Untrashing the order restores it to the proper state.

What I have noticed is that after untrashing the entry in `wp_postmeta` is still there. Maybe because it doesn't have the `wc-` prefix in the status name?

File: plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableDataStore.php (hunk 1 above)
Comment (barryhughes) [reply plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableDataStore.php]: Due to the check at the top of the method [(is the post different from the order?)](https://github.com/woocommerce/woocommerce/pull/35125/files#diff-8c34c1a6f743002d1f2db13c299d2086d0209889f72abc86bef3bd734abb2585R1044-R1046) I assumed that if we reach this point then there *is* some kind of difference between the two records that ought to be reconciled?

File: plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableDataStore.php (hunk 2 above)
Comment (barryhughes) [reply plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableDataStore.php:1789]: Interesting ... I wonder why the difference. Let me dig just a little bit further and/or verify using a fresh/'blank' environment. Perhaps something particular to me environment is causing an issue.

File: plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableDataStore.php (hunk 1 above)
Comment (Konamiman) [reply plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableDataStore.php]: After discussing with @vedanshujain I'm applying this change. Turns out that data comparison is needed too when the dates are equal, since data in the metadata table could have been modified as well.

File: plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableDataStore.php (hunk 2 above)
Comment (barryhughes) [reply plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableDataStore.php:1789]: I still see this issue. I'll send you some details to help you see it.

Comment (Konamiman) [reply plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableDataStore.php:1789]: Fixed. Explanation of what was going on in [the commit message](https://github.com/woocommerce/woocommerce/pull/35125/commits/f538c7c272fa5c02010aea62a281462cf5b8dccb).

btw I wasn't able to reproduce initially because I was testing with an existing order that already had dummy meta status in the db, as soon as I tried with a brand new order I was able to see the the issue.

Comment (barryhughes) [reply plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableDataStore.php:1789]: Yep, works :+1:

**Review by barryhughes — DISMISSED** [review]

**Comment by barryhughes** [comment]
Conflict to resolve then we can merge :+1:

**Review by vedanshujain — APPROVED** [review]
