### PR TITLE
Delete Transients: avoid running statements without options_to_clear.

### LINKED ISSUE #56076: WP-CLI wp wc product create Triggers wpdb::prepare() Warning and SQL Syntax Error
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Running `wp wc product create` via WP-CLI in wp-env results in `wpdb::prepare` warnings and SQL errors.

### Expected behavior

The product should be created without any warnings or database errors, and the command should return only `Success: Created product {ID}.`

### Actual behavior

- The command completes successfully, but **multiple wpdb::prepare() warnings** appear.
- SQL syntax error due to an _empty_ option_name IN ( ) statement.

### Steps to reproduce

1. Checkout release branch release/9.8
2. Start wp-env
3. Execute the following WP-CLI command:
```
wp wc product create --user=admin --name="Product xyz" --regular_price=15
```
4. Observe the following error message:
```
Notice: Function wpdb::prepare was called incorrectly.
WordPress database error: DELETE FROM wp_options WHERE option_name IN ( )
```

### WordPress Environment

<details><summary>System Status Report</summary>

```
### WordPress Environment ###

WordPress address (URL): [Redacted]
Site address (URL): [Redacted]
WC Version: 9.8.0-beta.1
Legacy REST API Package Version: The Legacy REST API plugin is not installed on this site.
Action Scheduler Version: ✔ 3.9.2
Log Directory Writable: ✔
WP Version: 6.7.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.54 (Debian)
PHP Version: 7.4.33
PHP Post Max Size: 1 GB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.74.0
OpenSSL/1.1.1n

SUHOSIN Installed: –
MySQL Version: 11.4.5-MariaDB-ubu2404
Max Upload Size: 1 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

[REDACTED]

### Post Type Counts ###

attachment: 1
page: 7
post: 1
product: 2
wp_navigation: 1

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (1) ###

WooCommerce: by Automattic – 9.8.0-beta.1

### Inactive Plugins (3) ###

Akismet Anti-Spam: by Automattic – 5.0.1
Hello Dolly: by Matt Mullenweg – 1.7.2
WooCommerce Beta Tester: by WooCommerce – 3.0.0

### Settings ###

Legacy API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 58 KB

### WC Pages ###

Shop base: #5 - /?page_id=5
Cart: #6 - /?page_id=6 -  Contains the woocommerce/cart block
Checkout: #7 - /?page_id=7 -  Contains the woocommerce/checkout block
My account: #8 - /?page_id=8 -  Contains the [woocommerce_my_account] shortcode
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty-Five
Version: 1.0 (update to version 1.1 is available)
Author URL: https://wordpress.org
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
Theme type: Block theme
WooCommerce Support: ❌ Not declared

### Templates ###

Overrides: /var/www/html/wp-content/plugins/woocommerce/templates/block-notices/error.php
/var/www/html/wp-content/plugins/woocommerce/templates/block-notices/notice.php
/var/www/html/wp-content/plugins/woocommerce/templates/block-notices/success.php


### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
onboarding
onboarding-tasks
pattern-toolkit-full-composability
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
printful
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page
launch-your-store
add-to-cart-with-options-stepper-layout

Disabled Features: product-data-views
experimental-blocks
coming-soon-newsletter-template
minified-js
product-pre-publish-modal
settings
async-product-editor-category-field
product-editor-template-system
reactify-classic-payments-settings
use-wp-horizon
blockified-add-to-cart

Daily Cron: ✔ Next scheduled: 2025-03-05 15:06:03 +00:00
Options: ✔
Notes: 59
Onboarding: -

### Action Scheduler ###

Complete: 3
Oldest: 2025-03-04 16:11:29 +0000
Newest: 2025-03-04 16:11:29 +0000

Pending: 2
Oldest: 2025-03-04 16:11:34 +0000
Newest: 2025-03-04 16:11:34 +0000


### Status report information ###

Generated at: 2025-03-04 16:11:45 +00:00
```
</details>

### Isolating the problem

- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by cpapazoglou**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Fixes https://github.com/woocommerce/woocommerce/issues/56076
Bug introduced in https://github.com/woocommerce/woocommerce/pull/55931

When there aren't any transients saved to DB we should not run 

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

Follow testing instructions in https://github.com/woocommerce/woocommerce/issues/56076

CleanShot 2025-03-05 at 19 44 15

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 
Fixes an error when `_wc_delete_transients` is called but there aren't any transients stored in DB to delete yet.
</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce/includes/wc-core-functions.php [hunk 1]
```diff
@@ -2754,44 +2754,47 @@ function _wc_delete_transients( $transients ) {
...
-					foreach ( $options_to_clear as $option_name ) {
-						wp_cache_delete( $option_name, 'options' );
-					}
-				}
-
-				// Also update alloptions cache if needed.
-				// This is required to prevent phantom transients from being returned.
-				$alloptions         = wp_load_alloptions( true );
-				$updated_alloptions = false;
+			if ( ! empty( $options_to_clear ) ) {
```
Comment (cpapazoglou) [inline plugins/woocommerce/includes/wc-core-functions.php]: I just wrapped the next actions with this condition. If there aren't any `$options_to_clear` we shouldn't clear anything.

Comment (tjcafferkey) [reply plugins/woocommerce/includes/wc-core-functions.php]: Optional: Just a nitpick, and not a blocker but it might be better/more readable to inverse this condition:

```suggestion
			if ( empty( $options_to_clear ) ) {
				return true;
			}
```

**Review by tjcafferkey — APPROVED** [review]
Thanks for fixing this @cpapazoglou this change LGTM and there was some important things we missed initially which you've addressed!

**Screenshot**
CleanShot 2025-03-06 at 09 24 52

**Testing steps**
* Followed steps outlined in the original issue https://github.com/woocommerce/woocommerce/issues/56076
* Ran unit tests locally

**Environment**
Local WP-Env
