### PR TITLE
Checkout Refactoring

### LINKED ISSUE #12456: WC_Checkout is not a true singleton, 'woocommerce_checkout_init' can be trigger more than once
## EXPLANATION OF THE ISSUE

It is possible for `'woocommerce_checkout_init'` to be triggered more than once, even though it is called in `WC_Checkout::__construct()` and `WC_Checkout` is designed as a singleton.

If 3rd party code instantiates its own copy of `WC_Checkout`, the `'woocommerce_checkout_init'` hook is called again. As was the case with _Shipping Multiple Addresses_ (related PR to fix that here: https://github.com/woocommerce/woocommerce-shipping-multiple-addresses/pull/52).

## STEPS TO REPRODUCE THE ISSUE

To reproduce, install the following snippet then visit the **Checkout** page: https://gist.github.com/thenbrent/c03e5de61d334c4f02318c6ec9d0132a

That will produce log output similar to:

```
[23-Nov-2016 19:16:30 UTC] **** Start of Request ****
[23-Nov-2016 19:16:30 UTC] ** "woocommerce_checkout_init" called, did_action() count = 1
[23-Nov-2016 19:16:30 UTC] ** In wcst_create_new_checkout_sadface()
[23-Nov-2016 19:16:30 UTC] ** "woocommerce_checkout_init" called, did_action() count = 2
[23-Nov-2016 19:16:30 UTC] ** In wcst_create_new_checkout_sadface()
[23-Nov-2016 19:16:30 UTC] ** "woocommerce_checkout_init" called, did_action() count = 3
[23-Nov-2016 19:16:30 UTC] ** In wcst_create_new_checkout_sadface()
[23-Nov-2016 19:16:30 UTC] ** "woocommerce_checkout_init" called, did_action() count = 4
```

The `did_action()` exceeding `1` in those log entries demonstrates that `'woocommerce_checkout_init'` is being run more than once. This is because the snippet manually instantiates `WC_Checkout`, which leads to `WC_Checkout::__construct()` being called again, even though `WC()->checkout` is already setup.

## PROPOSED FIX

The simplest fix is to check if `WC_Checkout` has been instantiated within `WC_Checkout::__construct()`, e.g. :

```
	if ( ! is_null( self::$_instance ) ) {
		return self::instance();
	}
```

I haven't submitted a PR for this in case there are other considerations.

## OTHER CONSIDERATIONS

The same issue exists with others singletons, including:

* `WC_Payment_Gateways`
* `WC_Shipping`
* `WC_Emails`

However, it is really only an issue in `WC_Checkout` and `WC_Shipping` where special init hooks are called - `'woocommerce_shipping_init'` and `'woocommerce_checkout_init'` because these hooks may be called more than once.

### PR DESCRIPTION
**Pull request by mikejolley**
This PR consists of some work I’ve done on checkout when looking into #12456 

- Tidy up
- Split up large methods
- Move init logic to instance getter (fixes #12456)
- Fixed customer note saving
- Fixed shipping last name saving

Unit tests pass, test orders were successful.

### CODE REVIEW

**Comment by mikejolley** [comment]
@thenbrent do these changes look fine to you? Tried to do a general cleanup whilst fixing your init issue.

File: includes/class-wc-checkout.php [hunk 1]
```diff
@@ -1,156 +1,253 @@
...
- * Checkout
+ * Main checkout class.
  *
  * The WooCommerce checkout class handles the checkout process, collecting user data and processing the payment.
  *
  * @class 		WC_Checkout
- * @version		2.1.0
  * @package		WooCommerce/Classes
- * @category		Class
+ * @category	Class
```
Comment (justinshreve) [inline includes/class-wc-checkout.php]: `Class` is no longer aligned with the other lines here.

File: includes/class-wc-checkout.php [hunk 2]
```diff
@@ -1,156 +1,253 @@
...
+			case 'enable_signup' :
+				return $this->is_registration_enabled();
+			case 'enable_guest_checkout' :
+				return ! $this->is_registration_required();
+			case 'must_create_account' :
+				return $this->is_registration_required() && ! is_user_logged_in();
+			case 'checkout_fields' :
+				return $this->get_checkout_fields();
+			case 'posted' :
+				if ( ! $this->legacy_posted_data ) {
```
Comment (justinshreve) [inline includes/class-wc-checkout.php]: Since `get_posted_data` is a private function for this class - can we go ahead and use `get_posted_data` to do this check and just `return $this->get_posted_data();`? It would save a few lines in a few places.

File: includes/class-wc-checkout.php [hunk 3]
```diff
@@ -197,555 +290,505 @@ public function create_order() {
...
+	 */
+	protected function payment_complete( $order_id ) {
+		$order = wc_get_order( $order_id );
+		$order->payment_complete();
+		wc_empty_cart();
 
-				do_action( 'woocommerce_checkout_order_processed', $order_id, $this->posted );
+		if ( is_ajax() ) {
+			wp_send_json( array(
+				'result' 	=> 'success',
```
Comment (justinshreve) [inline includes/class-wc-checkout.php]: Alignment looks off.

File: includes/class-wc-checkout.php [hunk 4]
```diff
@@ -197,555 +290,505 @@ public function create_order() {
...
-				if ( is_wp_error( $order_id ) ) {
-					throw new Exception( $order_id->get_error_message() );
-				}
+	/**
+	 * Process an order that doesn't require payment.
+	 *
+	 * @since  2.7.0
+	 * @param  int $order_id
+	 */
+	protected function payment_complete( $order_id ) {
```
Comment (justinshreve) [inline includes/class-wc-checkout.php]: `payment_complete` seems like an odd name for a function that process an order that doesn't require payment. Maybe we should call it something else?

**Review by emdashcodes — CHANGES_REQUESTED** [review]
Just posted a few notes below.

**Comment by thenbrent** [comment]
@mikejolley moving the hooks to `instance()` is a good idea and will definitely work for the issue we saw.

Previously `'woocommerce_checkout_fields`' was called before `'woocommerce_checkout_init'`, whereas now it will be called after. That worries me a little as 3rd party code may have depended on that order (e.g. to access a field on `'woocommerce_checkout_init'` that was set via `'woocommerce_checkout_fields`'). As the way to access properties is being changed in v2.7 anyway, developers will need to tested & updated that though.

**Comment by mikejolley** [comment]
@thenbrent I don't think that will be an issue actually; if they have code referencing `woocommerce_checkout_fields` during `woocommerce_checkout_init` they will be accessing it via the method property `checkout_fields`. When this is called, the fields will be init, and`woocommerce_checkout_fields` will be ran before their logic does anything with it. Is that what you meant?

**Comment by thenbrent** [comment]
> When this is called, the fields will be init, andwoocommerce_checkout_fields will be ran before their logic does anything with it. Is that what you meant?

Ah right of course, because the old `checkout_fields` property now maps to `get_checkout_fields()`. That won't be an issue then. 👍
