### PR TITLE
Fix textdomain loading warning in woocommerce 9.8.0 beta-1

### LINKED ISSUE #56113: Textdomain loading warning in woocommerce 9.80 beta-1
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Notice: Function _load_textdomain_just_in_time was called incorrectly. Translation loading for the woocommerce domain was triggered too early. This is usually an indicator for some code in the plugin or theme running too early. Translations should be loaded at the init action or later. Please see Debugging in WordPress for more information. (This message was added in version 6.7.0.) in /var/docs/public/wp-includes/functions.php on line 6121

### Expected behavior

the same behaviour as in woo 9.7.1. No warning message

I am using wp 6.8

### Actual behavior

load the text domain at the correct moment

### Steps to reproduce

Install woo 9.8.0 beta.  Turn on debug mode in wordpress

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): http://mydomain.com
Site address (URL): http://mydomain.com
WC Version: 9.8.0-beta.1
Legacy REST API Package Version: The Legacy REST API plugin is not installed on this site.
Action Scheduler Version: ✔ 3.9.2
Log Directory Writable: ✔
WP Version: ❌ 6.8-alpha-59837 - There is a newer version of WordPress available (6.8-beta1-59935)
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.52 (Ubuntu)
PHP Version: 8.3.17
PHP Post Max Size: 512 MB
PHP Time Limit: 600
PHP Max Input Vars: 5000
cURL Version: 7.81.0
OpenSSL/3.0.2

SUHOSIN Installed: –
MySQL Version: 8.0.41-0ubuntu0.22.04.1
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 9.7.0
WC Database Prefix: wp_
Total Database Size: 20.37MB
Database Data Size: 15.30MB
Database Index Size: 5.07MB
wp_woocommerce_sessions: Data: 0.14MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.05MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_aioseo_cache: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_cky_banners: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_cky_cookie_categories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_cky_cookies: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cmplz_cookiebanners: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cmplz_cookies: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cmplz_dnsmpd: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cmplz_services: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_ct_ugdpr_consent_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_daextlwcn_category: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_daextlwcn_consent_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_daextlwcn_cookie: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_daextlwcn_section: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_e_events: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_e_notes: Data: 0.02MB + Index: 0.17MB + Engine InnoDB
wp_e_notes_users_relations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_e_submissions: Data: 0.02MB + Index: 0.27MB + Engine InnoDB
wp_e_submissions_actions_log: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_e_submissions_values: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_eg_grids: Data: 0.03MB + Index: 0.02MB + Engine InnoDB
wp_eg_item_elements: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_eg_item_skins: Data: 0.11MB + Index: 0.03MB + Engine InnoDB
wp_eg_navigation_skins: Data: 0.14MB + Index: 0.02MB + Engine InnoDB
wp_fbv: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_fbv_attachment_folder: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gdpr_cc_options: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gdpr_consent_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_gla_attribute_mapping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gla_budget_recommendations: Data: 0.19MB + Index: 0.11MB + Engine InnoDB
wp_gla_merchant_issues: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gla_shipping_rates: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gla_shipping_times: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 7.31MB + Index: 0.13MB + Engine InnoDB
wp_postmeta: Data: 3.52MB + Index: 2.00MB + Engine InnoDB
wp_posts: Data: 1.52MB + Index: 0.16MB + Engine InnoDB
wp_responsive_menu_pro: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_revslider_css: Data: 0.13MB + Index: 0.02MB + Engine InnoDB
wp_revslider_css_bkp: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_revslider_layer_animations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_layer_animations_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_navigations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_navigations_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_sliders: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_revslider_sliders7: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_revslider_sliders_bkp: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_revslider_slides: Data: 0.13MB + Index: 0.02MB + Engine InnoDB
wp_revslider_slides7: Data: 0.09MB + Index: 0.02MB + Engine InnoDB
wp_revslider_slides_bkp: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_revslider_static_slides: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_revslider_static_slides_bkp: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wpomp_group_map: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wpomp_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wpomp_maps: Data: 0.01MB + Index: 0.00MB + Engine MyISAM

### Post Type Counts ###

attachment: 277
elementor_library: 2
gdpr_request: 1
master-popups: 1
nav_menu_item: 105
page: 152
portfolio: 31
post: 18
preset: 2
product: 28
product_variation: 7
revision: 136
slideshow: 5
wp_global_styles: 1
wp_navigation: 1

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (4) ###

WooCommerce Beta Tester: by WooCommerce – 3.0.0
WooCommerce: by Automattic – 9.8.0-beta.1
WordPress Beta Tester: by WordPress Upgrade/Install Team – 3.6.2
Test jQuery Updates: by The WordPress Team – 3.0.2

### Inactive Plugins (1) ###

Akismet Anti-spam: Spam Protection: by Automattic - Anti-spam Team – 5.3.7

### Settings ###

Legacy API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: left_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 331 KB

### WC Pages ###

Shop base: #5903 - /shop/
Cart: #5904 - /cart/ -  Contains the woocommerce_cart shortcode
Checkout: #5905 - /checkout/ -  Contains the woocommerce/checkout block
My account: #5906 - /my-account/ -  Contains the [woocommerce_my_account] shortcode
Terms and conditions: ❌ Page not set

### Theme ###

Name: WP Professional Multi-Purpose WordPress Theme
Version: 3.7.4 Build 20 february 2025
Author URL: 
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
Theme type: Classic theme
WooCommerce Support: ✔

### Templates ###

Overrides: custom-theme/woocommerce/archive-product.php
custom-theme/woocommerce/content-product-cat.php
custom-theme/woocommerce/content-product.php
custom-theme/woocommerce/global/breadcrumb.php
custom-theme/woocommerce/product-searchform.php
custom-theme/woocommerce/single-product/meta.php
custom-theme/woocommerce/single-product/product-image.php
custom-theme/woocommerce/single-product/product-thumbnails.php
custom-theme/woocommerce/single-product/rating.php
custom-theme/woocommerce/single-product/related.php
custom-theme/woocommerce/single-product/tabs/additional-information.php
custom-theme/woocommerce/single-product/tabs/description.php
custom-theme/woocommerce/single-product/tabs/tabs.php
custom-theme/woocommerce/single-product/title.php
custom-theme/woocommerce/single-product/up-sells.php
custom-theme/woocommerce/single-product-reviews.php
custom-theme/woocommerce/single-product.php
custom-theme/woocommerce/content-product_cat.php

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
onboarding
onboarding-tasks
pattern-toolkit-full-composability
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
printful
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page
launch-your-store
add-to-cart-with-options-stepper-layout

Disabled Features: product-data-views
experimental-blocks
coming-soon-newsletter-template
minified-js
product-pre-publish-modal
settings
async-product-editor-category-field
product-editor-template-system
reactify-classic-payments-settings
use-wp-horizon
blockified-add-to-cart
beta-tester-slotfill-examples

Daily Cron: ✔ Next scheduled: 2024-10-10 10:21:36 +00:00
Options: ✔
Notes: 81
Onboarding: completed

### Action Scheduler ###

Complete: 90
Oldest: 2024-10-09 06:43:29 +0000
Newest: 2025-02-07 12:12:00 +0000

Pending: 6
Oldest: 2025-02-08 12:11:55 +0000
Newest: 2025-03-05 09:17:05 +0000

### Status report information ###

Generated at: 2025-03-05 10:36:30 +00:00
`

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by triple0t**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes https://github.com/woocommerce/woocommerce/issues/56113

This PR fixes https://github.com/woocommerce/woocommerce/issues/56113 and ensures the translation warning message is not logged.

(For Bug Fixes) Bug introduced in PR https://github.com/woocommerce/woocommerce/pull/55754

### Screenshots or screen recordings:

| Before | After |
| ------ | ----- |
|        |       |

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Ensure you are on [WordPress 6.8 Beta](https://wordpress.org/news/2025/03/wordpress-6-8-beta-1/) 
2. Enable `WP_DEBUG` i.e `define( 'WP_DEBUG', true );`
3. Install and activate the WooCommerce plugin
4. Notice you don't get the `Translation loading for the woocommerce domain was triggered too early.` message.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce/src/Internal/EmailEditor/Package.php [hunk 1]
```diff
@@ -35,15 +33,16 @@ class Package {
 	 * @internal
 	 */
 	final public static function init() {
-		self::$package_active = FeaturesUtil::feature_is_enabled( 'block_email_editor' );
+		self::$package_active = get_option( 'woocommerce_feature_block_email_editor_enabled', 'no' ) === 'yes'; // init is called pretty early. Cant use FeaturesUtil.
```
Comment (costasovo) [inline plugins/woocommerce/src/Internal/EmailEditor/Package.php:36]: I assume we are switching to get_option because FeatureUtil triggers translations loading. Correct?

**Review by costasovo — APPROVED** [review]
@triple0t  Thanks for the quick fix! Great job! Approved. I added just on additional question to confirm my understanding of the change.

I tested it and it fixes the issue.

Here is how I tested this fix:

1) I've checked out the release branch and installed WP 6.8
2) I was able to replicate the error notice
Screenshot 2025-03-06 at 10 19 20
3) I updated to the fixed branch and it fixed the issue causing the notice
Screenshot 2025-03-06 at 10 18 18
4) I tested the block email integration and it works as expected 
Screenshot 2025-03-06 at 10 21 42

File: plugins/woocommerce/src/Internal/EmailEditor/Package.php (hunk 1 above)
Comment (triple0t) [reply plugins/woocommerce/src/Internal/EmailEditor/Package.php:36]: Yes, this is correct.
