### PR TITLE
Fix dashboard and analytics crashing

### LINKED ISSUE #32979: Wordpress Dashboard not loading after updating Woocommerce
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

The /wp-admin is not loading after updating Woocommerce to the newest version. Frontend works just fine until an attempt to sign in to wordpress dashbord. My team has found this issue on 3 different websites.

### Expected behavior

The Wordpress dashboard should open after logging in.

### Actual behavior

The Wordpress dashboard keeps loading indefinitely until a 504 Error occurs (after 3 mins of loading).

### Steps to reproduce

1. Go to /wp-admin
2. Log in
3. Wordpress never loads

### WordPress Environment

Unable to get, because the Wordpress dashboard won't load.

Woocommerce Version: Newest (Updated Yesterday)
Theme: Flatsome (Newest Version)
Wordpress Version: Newest

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by ilyasfoo**
Build: [woocommerce.zip](https://github.com/woocommerce/woocommerce/files/8779476/woocommerce.zip)

### Changes proposed in this Pull Request:

Closes #32979. 

`get_weekstartend` utilizes the function [`mktime`](https://www.php.net/manual/en/function.mktime.php) date format which is sensitive to the timezone configuration set by [`date_default_timezone_set`](https://www.php.net/manual/en/function.date-default-timezone-set.php).

This function inadvertently converts the date passed in our [call](https://github.com/woocommerce/woocommerce/blob/13fe9b49707afdb50387bece76d2f588c3f05164/plugins/woocommerce/src/Admin/API/Reports/TimeInterval.php#L333) to `get_weekstartend` without respecting its original timezone information. This would cause the date calculation to be inaccurate, i.e: returning last week when the correct value should be this week. Since the function is called from a [loop](https://github.com/woocommerce/woocommerce/blob/13fe9b49707afdb50387bece76d2f588c3f05164/plugins/woocommerce/src/Admin/API/Reports/TimeInterval.php#L247-L250), the function incorrectly returning previous week makes the loop runs indefinitely thus crashing sites.

The following is a minimal code to reproduce date miscalculation (You can put this in a PHP file in any WordPress base installation and run it with `php -f file.php`)
```php
<?php
require_once __DIR__ . '/wp-load.php';

date_default_timezone_set( 'Europe/Berlin' );
$start_date = \DateTime::createFromFormat( 'U', get_weekstartend( '2022-05-02' )['start'] );
echo $start_date->format( 'Y-m-d' ); // 2022-04-25, this is the previous week.
echo $start_date->add( new \DateInterval( 'P7D' ) )->format( 'Y-m-d' ); // 2022-05-02, after adding 7 days, it returns the same date we've supplied
```

### How to test the changes in this Pull Request:

1. In a fresh site with WooCommerce 6.5.1 installed, go to `Settings -> General` and change `Timezone` to `Berlin`
2. Download [this plugin](https://gist.github.com/ilyasfoo/dbac0430d2741071dc6a00772f651a27) by clicking "Download ZIP" on top right corner
3. Install & activate the plugin
5. Go to Products page and click on "Help" (top right) > Setup Wizard > disable task list. 
6. Go to WordPress dashboard
7. Observe the the dashboard loads without errors and "WooCommerce Status" widget is loaded successfully
8. Go to Analytics > Overview and make sure "Leaderboards" stats are able to load

### Other information:

-   [x] Have you added an explanation of what your changes do and why you'd like us to include them?
-   [x] Have you written new tests for your changes, as applicable?
-   [x] Have you successfully run tests with your changes locally?
-   [x] Have you created a changelog file for each project being changed, ie `pnpm nx changelog <project>`?

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

**Comment by botwoo** [comment]
:bar_chart: Test reports for this pull request have been published and are accessible through the following links:

- [REST API Test Report](https://woocommerce.github.io/woocommerce-test-reports/pr/33206/api/)
- E2E Test Report (TBC)

Latest commit referenced in the reports: `Changelog` 0ea818457396c58cf5d5aa9d60b1aca4dcb728f4
This comment will automatically be updated with the latest referenced commit when you push new changes to this pull request.

---

_Visit the [WooCommerce Test Reports](https://woocommerce.github.io/woocommerce-test-reports) homepage to view all published reports. See the [FAQs](https://github.com/woocommerce/woocommerce-test-reports/wiki/FAQs) page if you're having problems accessing them._

File: plugins/woocommerce/src/Admin/API/Reports/TimeInterval.php [hunk 1]
```diff
@@ -330,14 +330,24 @@ public static function next_day_start( $datetime, $reversed = false ) {
...
+		date_default_timezone_set( $default_timezone );
+		// @codingStandardsIgnoreEnd
 		if ( $reversed ) {
-			return \DateTime::createFromFormat( 'U', $start_end['end'] )->sub( $seven_days );
+			$result = \DateTime::createFromFormat( 'U', $start_end_timestamp['end'] )->sub( $seven_days );
+		} else {
+			$result = \DateTime::createFromFormat( 'U', $start_end_timestamp['start'] )->add( $seven_days );
 		}
-		return \DateTime::createFromFormat( 'U', $start_end['start'] )->add( $seven_days );
+		return \DateTime::createFromFormat( 'Y-m-d H:i:s', $result->format( 'Y-m-d H:i:s' ), $original_timezone );
```
Comment (ilyasfoo) [inline plugins/woocommerce/src/Admin/API/Reports/TimeInterval.php:347]: Recreate the date object instead of `->setTimezone()` since otherwise it will add or subtract incorrectly from converting timezones

File: plugins/woocommerce/src/Admin/API/Reports/TimeInterval.php [hunk 2]
```diff
@@ -330,14 +330,24 @@ public static function next_day_start( $datetime, $reversed = false ) {
...
 	public static function next_week_start( $datetime, $reversed = false ) {
 		$seven_days = new \DateInterval( 'P7D' );
-		$start_end  = get_weekstartend( $datetime->format( 'Y-m-d' ) );
-
+		// Default timezone set in wp-settings.php.
+		$default_timezone = date_default_timezone_get();
+		// Timezone that the WP site uses in Settings > General.
+		$original_timezone = $datetime->getTimezone();
+		// @codingStandardsIgnoreStart
+		date_default_timezone_set( 'UTC' );
```
Comment (ilyasfoo) [inline plugins/woocommerce/src/Admin/API/Reports/TimeInterval.php:338]: Sets PHP timezone setting temporarily so `mktime` would always calculate with standardized UTC time

File: plugins/woocommerce/src/Admin/API/Reports/TimeInterval.php [hunk 3]
```diff
@@ -330,14 +330,24 @@ public static function next_day_start( $datetime, $reversed = false ) {
...
+		$start_end_timestamp  = get_weekstartend( $datetime->format( 'Y-m-d' ) );
+		date_default_timezone_set( $default_timezone );
+		// @codingStandardsIgnoreEnd
 		if ( $reversed ) {
-			return \DateTime::createFromFormat( 'U', $start_end['end'] )->sub( $seven_days );
+			$result = \DateTime::createFromFormat( 'U', $start_end_timestamp['end'] )->sub( $seven_days );
+		} else {
+			$result = \DateTime::createFromFormat( 'U', $start_end_timestamp['start'] )->add( $seven_days );
```
Comment (moon0326) [inline plugins/woocommerce/src/Admin/API/Reports/TimeInterval.php:345]: ~We should also set `$original_timezone` when `$reversed` is true and we don't need `else` anymore. We can return early if `$reversed` is set.~

My bad :) I did not read the last line correctly. It looks good.

**Comment by moon0326** [comment]
Nice work @ilyasfoo 👍 

I left one comment. Otherwise, everything LGTM!

**Review by moon0326 — APPROVED** [review]
Thank you for working on it so quickly 👍 

LGTM 🚀

**Comment by jonathansadowski** [comment]
This has been cherry-picked into the `release/6.6` branch.
