### PR TITLE
Fix encoded html entities for shipping rate names in cart and checkout blocks

### LINKED ISSUE #60139: Double-encoded HTML entities in WooCommerce Blocks shipping method names
## **Describe the bug**

Shipping method names containing dashes (e.g., "Pickup - Local") are being double-encoded in the WooCommerce Blocks checkout order summary, resulting in display issues where dashes appear as `&amp;#8211;` instead of proper en-dashes.

## **To Reproduce**

1. Set up a WooCommerce store with a shipping method that contains dashes in its name (e.g., "Pickup - Local")
2. Add items to cart and proceed to checkout
3. Select the shipping method with dashes in the name
4. View the order summary block on the checkout page

## **Expected behavior**

Shipping method names should display correctly with proper en-dashes (—) or regular dashes (-).

## **Screenshots**

If applicable, add screenshots to help explain your problem. (or upload as files via Asks)

<details><summary>Environment</summary>

Please fill out any of the below that applies

**Operating System/Device**

- [ ] Windows
- [ ] MacOS
- [ ] Linux
- [ ] iPhone
- [ ] Samsung
- [ ] Other (add in additional context field)

**Version:** Add the Desktop OS and/or Device version(s) here

**Browser**

- [ ] Desktop Edge
- [ ] Desktop Chrome/Chromium
- [ ] Desktop Safari
- [ ] Mobile Edge
- [ ] Mobile Chrome/Chromium
- [ ] Mobile Safari
- [ ] Other (add in additional context field)

**Version:** Add the browser version(s) here.

</details>

## **Additional context**

Based on some investigation with Claude, the flow appears to be

1. **Server-side encoding**: In `plugins/woocommerce/src/StoreApi/Schemas/V1/CartShippingRateSchema.php` (lines 307-309), shipping method names are processed through `prepare_html_response()` which applies WordPress's `wptexturize()` function.
2. **wptexturize transformation**: The `wptexturize()` function converts double dashes (`--`) to en-dash HTML entities (`&#8211;`).
3. **Client-side decoding**: In the frontend JavaScript components (e.g., `plugins/woocommerce/client/blocks/assets/js/base/components/cart-checkout/totals/shipping/shipping-via.tsx` line 12), the `decodeEntities()` function attempts to decode these HTML entities.
4. **Double encoding**: However, the HTML entities are being double-encoded somewhere in the process, likely due to additional HTML escaping in the Store API response or during data transmission.

### PR DESCRIPTION
**Pull request by mikejolley**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Shipping rate names from the API are encoded. Similar to how we've handled coupons and fees, rates need to be decoded. To this end, I've added a normalization function within `useStoreCart` so all consumers of that hook have decoded entities.

While in there, I standardised this approach for the other properties, and sorted the properties alphabetically for readability.

Closes #60139

(For Bug Fixes) Bug introduced in PR # .

### How to test the changes in this Pull Request:

1. Enable free shipping and re-label it as "Free Shipping - Dash". Disable other methods.
2. Enable Local Pickup and rename re-label it as "Local Pickup - Dash"
3. Add a dash to the name of some pickup locations
4. Add an item to cart and go to the cart page. Free shipping should be selected (if not, go to checkout and select it). Ensure the dash is an actual `-` and not an entity.
5. Go to checkout and see the shipping rate name in order summary. Check the dash is a `-`.
6. Select local pickup and a location. Check the dash is a `-`.
7. Place order. Check the shipping name uses a real `-` in the order confirmation.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce/client/blocks/assets/js/base/context/hooks/cart/use-store-cart.ts [hunk 1]
```diff
@@ -93,31 +96,77 @@ const decodeValues = <
...
+		decodeValues( address )
+	);
+	if ( ! fastDeepEqual( addressRef.current, normalizedAddress ) ) {
+		addressRef.current = normalizedAddress;
+	}
+	return addressRef.current;
+};
+
+const normalizeCoupons = ( coupons: CartResponseCouponItem[] ) => {
+	return coupons.length > 0
```
Comment (ralucaStan) [inline plugins/woocommerce/client/blocks/assets/js/base/context/hooks/cart/use-store-cart.ts:116]: We could be more defensive here and not just reply on the length check. Same for fees and rated

File: plugins/woocommerce/client/blocks/assets/js/base/context/hooks/cart/use-store-cart.ts [hunk 2]
```diff
@@ -165,64 +214,40 @@ export const useStoreCart = (
...
 		isLoadingRates,
-		cartHasCalculatedShipping: cartData.hasCalculatedShipping,
-		paymentRequirements: cartData.paymentRequirements,
 		paymentMethods: cartData.paymentMethods,
+		paymentRequirements: cartData.paymentRequirements,
 		receiveCart,
 		receiveCartContents,
-		hasPendingItemsOperations,
+		shippingAddress,
+		shippingRates: normalizeShippingRates( cartData.shippingRates ),
```
Comment (ralucaStan) [inline plugins/woocommerce/client/blocks/assets/js/base/context/hooks/cart/use-store-cart.ts:250]: We could use useMemo: 
```
	const normalizedShippingRates = useMemo( () => {
		return normalizeShippingRates( cartData.shippingRates );
	}, [ cartData.shippingRates ] );
```
same for coupons and fees

**Review by ralucaStan — COMMENTED** [review]
Looks good and tests good; went through a order with coupons and shipping rates with `-`. A nice to have if you have the capacity would be to add unit tests to the rates util.

File: plugins/woocommerce/client/blocks/assets/js/base/context/hooks/cart/use-store-cart.ts (hunk 1 above)
Comment (mikejolley) [reply plugins/woocommerce/client/blocks/assets/js/base/context/hooks/cart/use-store-cart.ts:116]: FWIW This is the same code as before just moved into a utility function. I think we can trust the types here; this comes from `cartData` which in terms comes from a hook. I think the there were an unexpected type here we'd get problems in many other places before this.

File: plugins/woocommerce/client/blocks/assets/js/base/context/hooks/cart/use-store-cart.ts (hunk 2 above)
Comment (mikejolley) [reply plugins/woocommerce/client/blocks/assets/js/base/context/hooks/cart/use-store-cart.ts:250]: @ralucaStan I looked into this. Because `cartData.shippingRates` is an object, it is not usable as a hook dependency (changes on every render). So we'd have to stringify the object or something first which would likely mitigate the benefits of using memo. `normalizeShippingRates` doesn't do much, just decodes. Should we leave it?

Comment (ralucaStan) [reply plugins/woocommerce/client/blocks/assets/js/base/context/hooks/cart/use-store-cart.ts:250]: Yes, we can leave it.

Comment (mikejolley) [reply plugins/woocommerce/client/blocks/assets/js/base/context/hooks/cart/use-store-cart.ts:250]: In that case no action I think is needed. Can you approve @ralucaStan ?

**Review by ralucaStan — APPROVED** [review]

**Comment by K13NN13** [comment]
Facing the same issue on version 10.1.2
