### PR TITLE
Fix PHP warning of missing default value in spec

### LINKED ISSUE #32154: Payment gateway suggestions spec missing default param, causing warning
### Describe the bug
One of the specs in the Payment gateway suggestions doesn't include a `default` param that we expect on our end, this causes the following warning:
```
Undefined property: stdClass::$default
 Type: PHP Notice Line: 45
 File: /wp-content/plugins/woocommerce-admin/src/RemoteInboxNotifications/OptionRuleProcessor.php
```

This appears to be missing on our `payment-gateway-suggestions` endpoint specifically in the rules for selling venues: https://github.com/Automattic/woocommerce.com/blob/trunk/plugins/wccom-plugins/payment-gateway-suggestions/includes/class-payment-gateway-suggestions.php#L452-L455

### To Reproduce
1. On a fresh site, or make sure this transient is deleted `woocommerce_admin_payment_gateway_suggestions_specs`
2. Click on the `Set up payments` task
3. Open up your `debug.log` and notice the warning mentioned above.

### Screenshots

Screen Shot 2022-02-23 at 1 09 59 PM

### Expected behavior

Should not show a warning.

### Desktop (please complete the following information):

* OS: [e.g. iOS]
* Browser [e.g. chrome, safari]
* Version [e.g. 22]

### Smartphone (please complete the following information):

* Device: [e.g. iPhone6]
* OS: [e.g. iOS8.1]
* Browser [e.g. stock browser, safari]
* Version [e.g. 22]

### PR DESCRIPTION
**Pull request by louwie17**
### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Make use of `$default` value when passing it into the Transformer service.

Closes #32154 

### How to test the changes in this Pull Request:

1. On a fresh site, or make sure this transient is deleted `woocommerce_admin_payment_gateway_suggestions_specs`
2. Click on the `Set up payments` task
3. Open up your `debug.log` and make sure there are no new warnings displayed, specifically this warning:
```
Undefined property: stdClass::$default
 Type: PHP Notice Line: 45
 File: /wp-content/plugins/woocommerce-admin/src/RemoteInboxNotifications/OptionRuleProcessor.php
```

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully run tests with your changes locally?

### Changelog entry

> Fix PHP warning when default param is missing in payments spec.

### FOR PR REVIEWER ONLY:

* [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

File: plugins/woocommerce/src/Admin/RemoteInboxNotifications/OptionRuleProcessor.php [hunk 1]
```diff
@@ -42,7 +42,7 @@ public function process( $rule, $stored_state ) {
 		}
 
 		if ( isset( $rule->transformers ) && is_array( $rule->transformers ) ) {
-			$option_value = TransformerService::apply( $option_value, $rule->transformers, $rule->default );
+			$option_value = TransformerService::apply( $option_value, $rule->transformers, $default );
```
Comment (louwie17) [inline plugins/woocommerce/src/Admin/RemoteInboxNotifications/OptionRuleProcessor.php:45]: There is a `$default` value set on line 25 that checks if `$rule->default` is actually set.

**Review by chihsuan — APPROVED** [review]
Thanks for the fix! Looks good and tested well. 🚢
