### PR TITLE
ProductCollection: Refactor tests into focused and maintainable files

### LINKED ISSUE #59239: Product Collection: Separate tests into unit/integration and add editor-side integration tests
#### Summary

The `plugins/woocommerce/tests/php/src/Blocks/BlockTypes/ProductCollection.php` [file](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/tests/php/src/Blocks/BlockTypes/ProductCollection.php) has grown quite large and currently mixes different types of tests. To improve maintainability and test coverage, we should consider the following:

#### Suggestions

1. **Split Unit and Integration Tests**
   - Separate the unit tests that focus on SQL query generation from the integration tests that cover the Product Collection block’s behavior.
   - This will make the tests easier to maintain and understand, and will help isolate failures to specific areas.

2. **Add Editor-Side Integration Tests**
   - Begin adding integration tests specifically for the Product Collection block in the editor context.
   - This will help ensure that the block behaves as expected in the editor, and will catch regressions related to editor-side functionality.

### PR DESCRIPTION
**Pull request by amitraj2203**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

This PR refactors the large `ProductCollection.php` test file into 4 focused, maintainable test files organized by functionality.

**Problem**: The current `ProductCollection.php` test file is very large and covers multiple distinct concerns (query building, SQL generation, collection handlers, REST API integration), making it difficult to maintain and navigate.

**New Structure**:

- `QueryBuilder.php` - Query building & merging logic (23 tests)
- `SqlGeneration.php` - SQL clause generation (12 tests) 
- `HandlerRegistry.php` - Collection handler system (8 tests)
- `RestApi.php` - REST API integration (2 tests)

Closes #59239 

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. **Confirm the tests runs as expected**:
   ```bash
   pnpm --filter=@woocommerce/plugin-woocommerce test:unit:env -- --filter=ProductCollection
   ```

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

**Comment by amitraj2203** [comment]
Hi @kmanijak,
Could you please review this PR when you have a chance?

I realize the number of changed lines appears quite large, but the changes are just moving test functions across the four files for better organization.

Also, a few functions like `get_base_parsed_block`, `initialize_merged_query`, `setUp`, and `build_request` are now duplicated across these files. Would it be a good idea to create a parent class extending `\WP_UnitTestCase`, and then have the other test classes inherit from it to avoid this duplication?

Thanks in advance!

---

Edit: I saw the lints are giving errors in local to add strict_types declaration in test files. Should I add those as it wasn't present earlier.

File: plugins/woocommerce/tests/php/src/Blocks/BlockTypes/ProductCollection/SqlGeneration.php [hunk 1]
```diff
@@ -0,0 +1,541 @@
...
+		$this->assertEquals(
+			array(
+				'min' => 1,
+			),
+			$merged_query['priceRange'],
+		);
+
+		$query = new WP_Query( $merged_query );
+
+		$this->assertStringContainsString( 'wc_product_meta_lookup.max_price >= 1.', $query->request );
```
[the remark this answers is not in the document]
Comment (kmanijak) [reply plugins/woocommerce/tests/php/src/Blocks/BlockTypes/ProductCollection/SqlGeneration.php:79]: This is potential improvement but considering the amount of changes let's keep this PR's scope clear and focused on restructure.

File: plugins/woocommerce/tests/php/src/Blocks/BlockTypes/ProductCollection/SqlGeneration.php [hunk 2]
```diff
@@ -0,0 +1,541 @@
+<?php
+
+namespace Automattic\WooCommerce\Tests\Blocks\BlockTypes\ProductCollection;
+
+use Automattic\WooCommerce\Tests\Blocks\Mocks\ProductCollectionMock;
+use WC_Helper_Product;
+use WC_Tax;
+use WP_Query;
+use Automattic\WooCommerce\Enums\ProductStockStatus;
```
Comment (kmanijak) [inline plugins/woocommerce/tests/php/src/Blocks/BlockTypes/ProductCollection/SqlGeneration.php]: Super nitpick: I know this is the order from original file but what about better ordering?

```suggestion
use Automattic\WooCommerce\Tests\Blocks\Mocks\ProductCollectionMock;
use Automattic\WooCommerce\Enums\ProductStockStatus;
use WC_Helper_Product;
use WC_Tax;
use WP_Query;
```

File: plugins/woocommerce/tests/php/src/Blocks/BlockTypes/ProductCollection/HandlerRegistry.php [hunk 3]
```diff
@@ -0,0 +1,404 @@
+<?php
+
+namespace Automattic\WooCommerce\Tests\Blocks\BlockTypes\ProductCollection;
+
+use Automattic\WooCommerce\Tests\Blocks\Mocks\ProductCollectionMock;
+use WC_Helper_Product;
+use Automattic\WooCommerce\Enums\ProductStockStatus;
```
Comment (kmanijak) [inline plugins/woocommerce/tests/php/src/Blocks/BlockTypes/ProductCollection/HandlerRegistry.php]: Super nitpick: let's order the `use` for easier reading:

```suggestion
use Automattic\WooCommerce\Tests\Blocks\Mocks\ProductCollectionMock;
use Automattic\WooCommerce\Enums\ProductStockStatus;
use WC_Helper_Product;
```

**Review by kmanijak — CHANGES_REQUESTED** [review]
Thanks for working on this issue!

> Also, a few functions like get_base_parsed_block, initialize_merged_query, setUp, and build_request are now duplicated across these files. Would it be a good idea to create a parent class extending \WP_UnitTestCase, and then have the other test classes inherit from it to avoid this duplication?

It definitely is a good idea! You can either do as you suggested (with a parent class) or simply create another Util class and just use it across test files. But yeah, removing duplication here is strongly advised here. 🙌 

> Edit: I saw the lints are giving errors in local to add strict_types declaration in test files. Should I add those as it wasn't present earlier.

Yep! This rule was added after the initial file was created. And rule doesn't affect existing files however we're organically apply it to files we edit propagating the rule more and more 👍 Appreciate attention to linter errors!

**Comment by amitraj2203** [comment]
@kmanijak I've created a `Utils` class and moved the duplicate functions there. There was also a merge conflict, so I moved the affected tests from this [PR](https://github.com/woocommerce/woocommerce/pull/58440) to the `QueryBuilder.php` file. I was wondering if we should follow [this nitpick comment](https://github.com/woocommerce/woocommerce/pull/59575#pullrequestreview-3010476810) from Coderabbit. Let me know if there's anything else needed from my side.

**Review by kmanijak — APPROVED** [review]
Great work @amitraj2203! Thanks for extracting common methods into Utils class.

> I was wondering if we should follow https://github.com/woocommerce/woocommerce/pull/59575#pullrequestreview-3010476810 from Coderabbit. Let me know if there's anything else needed from my side.

While this is a nice suggestion from Code Rabbit, I'd stick with the main goal for this PR and not include additional changes but appreciate attention to details and considering this!

Anyway, once the CI pass I'll merge it, appreciate another contribution @amitraj2203! Keep up the good work!
