### PR TITLE
[Experiment] Handle customer session meta data

### LINKED ISSUE #42024: Figure out why saving meta data to WC_Customer is not working.
In Additional Fields, we save fields values to order meta and customer meta. Both classes use a data store below them, and the three data stores are `WC_Order_Data_Store`, `WC_Customer_Data_Store`, and `WC_Customer_Data_Store_Session`. All of them implement `WC_Data`, which supports methods like `get_meta` and `update_meta_data`.

When it comes to Order, calling `update_meta_data` and then `order->save` will persist the meta data to the order. When doing that to the customer, the value is not persisted, in my testing, I found that it's being persisted to the postmeta table instead of usermeta table for some reason.

For that, we switched the implementation to directly read and save from the usermeta table using WordPress meta functions, and if we don't have a current user, we would use the session to save those values.

This creates a lot of code hacks, and doesn't support moving meta from guest to registered customer, and we ideally want to go back to using `WC_Data`.

### PR DESCRIPTION
**Pull request by mikejolley**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

When working with the `wc()->customer` object we were finding inconsistencies when it came to updating meta data and saving. This PR improves inline documentation and cleans things up so that:

1. `meta_data` is stored to session instead of discarded. Rather than save all meta, only certain fields are stored (an allow list containing fields from additional fields)
2. Additional fields will correctly persist data to session using the `WC_Customer` object.
3. Additional fields will correctly persist data to database now that `filter_fields_for_customer` has been patched.

This could use a detailed review because it touches on core components so I will be tagging 2 reviewers.

Closes #42024

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

Register additional checkout fields before testing:

```
add_action(
	'woocommerce_blocks_loaded',
	function() {
		woocommerce_blocks_register_checkout_field(
			array(
				'id'       => 'plugin-namespace/some-new-billing-field',
				'label'    => __( 'Custom address field', 'woocommerce' ),
				'location' => 'address',
				'type'     => 'text',
			),
		);

		woocommerce_blocks_register_checkout_field(
			array(
				'id'       => 'plugin-namespace/some-new-contact-field',
				'label'    => __( 'Custom new contact field', 'woocommerce' ),
				'location' => 'contact',
				'type'     => 'text',
			),
		);

		woocommerce_blocks_register_checkout_field(
			array(
				'id'       => 'plugin-namespace/leave-on-porch',
				'label'    => __( 'Please leave my package on the porch if I\'m not home', 'woocommerce' ),
				'location' => 'additional',
				'type'     => 'checkbox',
			),
		);

		woocommerce_blocks_register_checkout_field(
			array(
				'id'       => 'plugin-namespace/location-on-porch',
				'label'    => __( 'Describe where we should hide the parcel', 'woocommerce' ),
				'location' => 'additional',
				'type'     => 'text',
			)
		);
		woocommerce_blocks_register_checkout_field(
			array(
				'id'       => 'plugin-namespace/leave-with-neighbor',
				'label'    => __( 'Which neighbor should we leave it with if unable to hide?', 'woocommerce' ),
				'location' => 'additional',
				'type'     => 'select',
				'options'  => array(
					array(
						'label' => 'Neighbor to the left',
						'value' => 'left',
					),
					array(
						'label' => 'Neighbor to the right',
						'value' => 'right',
					),
					array(
						'label' => 'Neighbor across the road',
						'value' => 'across',
					),
					array(
						'label' => 'Do not leave with a neighbor',
						'value' => 'none',
					),
				),
			)
		);
	}
);
```

**As a logged out guest user:**

1. Add something to your cart and go to checkout.
2. Fill out the form, including address fields.
3. Place the order and confirm details were saved.
4. Add something to your cart and go to checkout again.
5. Confirm the contact and address fields are still populated. The "Please leave my package" options should be empty.

**As a logged in user perform the testing steps above, and additionally:**

1. Add something to your cart and go to checkout.
2. Change the shipping first name.
3. Refresh checkout and the change persists.
4. Go to my account _without_ placing the order. Confirm the shipping address has the previous value for first name.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce/includes/class-wc-customer.php [hunk 1]
```diff
@@ -105,10 +113,12 @@ public function __construct( $data = 0, $is_session = false ) {
 			$this->set_id( $data );
 		}
 
-		$this->data_store = WC_Data_Store::load( 'customer' );
+		// We enable sessions if requested, the session handle exists, and the user is not logged in.
+		$this->is_session = $is_session && isset( WC()->session );
+		$this->data_store = $this->is_session ? WC_Data_Store::load( 'customer-session' ) : WC_Data_Store::load( 'customer' );
```
Comment (mikejolley) [inline plugins/woocommerce/includes/class-wc-customer.php]: Rather than use both data-stores (session being an incomplete store) we use one or the other depending on whether this is a session. The `customer-session` store will extend `customer`. The difference is, `customer-session` does not persist anything to the DB.

File: plugins/woocommerce/includes/abstracts/abstract-wc-data.php [hunk 2]
```diff
@@ -117,6 +117,14 @@ abstract class WC_Data {
 	 */
 	protected $legacy_datastore_props = array();
 
+	/**
+	 * Legacy package key.
+	 *
+	 * @deprecated 4.4.0 For legacy actions.
+	 * @var string
+	 */
+	public $legacy_package_key;
```
Comment (mikejolley) [inline plugins/woocommerce/includes/abstracts/abstract-wc-data.php]: Unrelated notice fix that was bugging me.

File: plugins/woocommerce/includes/class-wc-customer.php [hunk 3]
```diff
@@ -105,10 +113,12 @@ public function __construct( $data = 0, $is_session = false ) {
...
 
 		// If we have an ID, load the user from the DB.
-		if ( $this->get_id() ) {
+		if ( $this->get_id() || $this->is_session ) {
```
Comment (mikejolley) [inline plugins/woocommerce/includes/class-wc-customer.php]: When using sessions, we read (from session).

File: plugins/woocommerce/includes/data-stores/class-wc-customer-data-store-session.php [hunk 4]
```diff
@@ -81,19 +84,41 @@ public function save_to_session( $customer ) {
 			if ( 'billing_' === substr( $session_key, 0, 8 ) ) {
 				$session_key = str_replace( 'billing_', '', $session_key );
 			}
-			$data[ $session_key ] = (string) $customer->{"get_$function_key"}( 'edit' );
+			if ( 'meta_data' === $session_key ) {
```
Comment (mikejolley) [inline plugins/woocommerce/includes/data-stores/class-wc-customer-data-store-session.php:87]: This handles the saving of meta data to session. To avoid saving all meta to session, we have an allowlist of properties. Other meta is discarded like before.

File: plugins/woocommerce/includes/data-stores/class-wc-customer-data-store-session.php [hunk 5]
```diff
@@ -81,19 +84,41 @@ public function save_to_session( $customer ) {
...
-	 * which case the stored ID will differ from the actual ID.
+	 * Read customer data from the session unless the user has logged in, in which case the stored ID will differ from
+	 * the actual ID.
 	 *
 	 * @since 3.0.0
 	 * @param WC_Customer $customer Customer object.
 	 */
 	public function read( &$customer ) {
+		if ( $customer->get_id() ) {
+			parent::read( $customer );
```
Comment (mikejolley) [inline plugins/woocommerce/includes/data-stores/class-wc-customer-data-store-session.php]: This was added because we'll only load one data store from now on instead of both, when using sessions.

File: plugins/woocommerce/includes/data-stores/class-wc-customer-data-store-session.php [hunk 6]
```diff
@@ -163,37 +200,4 @@ protected function set_defaults( &$customer ) {
...
 	}
-
-	/**
-	 * Gets the customers last order.
-	 *
-	 * @since 3.0.0
-	 * @param WC_Customer $customer Customer object.
-	 * @return WC_Order|false
-	 */
-	public function get_last_order( &$customer ) {
```
Comment (mikejolley) [inline plugins/woocommerce/includes/data-stores/class-wc-customer-data-store-session.php]: Extending `WC_Customer_Data_Store` means we don't need to worry about these methods, and as a bonus they'll work for logged in users.

File: plugins/woocommerce/src/Blocks/Domain/Services/CheckoutFields.php [hunk 7]
```diff
@@ -744,33 +745,29 @@ public function is_field( $key ) {
...
 	public function persist_field_for_order( $key, $value, $order, $set_customer = true ) {
 		$this->set_array_meta( $key, $value, $order );
-		if ( $set_customer ) {
-			if ( isset( wc()->customer ) ) {
-				$this->set_array_meta( $key, $value, wc()->customer );
-			} elseif ( $order->get_customer_id() ) {
-				$customer = new \WC_Customer( $order->get_customer_id() );
-				$this->set_array_meta( $key, $value, $customer );
-			}
+		if ( $set_customer && $order->get_customer_id() ) {
```
Comment (mikejolley) [inline plugins/woocommerce/src/Blocks/Domain/Services/CheckoutFields.php:761]: No need to persist to session here; only for real customers.

**Comment by mikejolley** [comment]
@senadir I'm getting there with this one but I'm not sure how to populate default values. Where do we populate default values for fields shown on checkout? It works for address fields but not contact/additional, even though I know its stored to account and works from the My Account page.

File: plugins/woocommerce/includes/class-wc-order-item-product.php [hunk 8]
```diff
@@ -14,6 +14,22 @@
...
+	public $legacy_values;
+
+	/**
+	 * Legacy cart item key.
+	 *
+	 * @deprecated 4.4.0 For legacy actions.
+	 * @var string
+	 */
+	public $legacy_cart_item_key;
+
```
Comment (senadir) [inline plugins/woocommerce/includes/class-wc-order-item-product.php]: Should this be here?

File: plugins/woocommerce/includes/class-wc-order-item.php [hunk 9]
```diff
@@ -52,6 +52,14 @@ class WC_Order_Item extends WC_Data implements ArrayAccess {
...
 	protected $object_type = 'order_item';
 
+	/**
+	 * Legacy package key.
+	 *
+	 * @deprecated 4.4.0 For legacy actions.
+	 * @var string
+	 */
+	public $legacy_package_key;
+
```
Comment (senadir) [inline plugins/woocommerce/includes/class-wc-order-item.php]: Also this.

File: plugins/woocommerce/includes/data-stores/class-wc-customer-data-store-session.php [hunk 10]
```diff
@@ -81,14 +84,32 @@ public function save_to_session( $customer ) {
...
+						$customer->get_meta_data(),
+						function( $meta_data ) use ( $allowed_meta_data_keys ) {
+							return in_array( $meta_data->key, $allowed_meta_data_keys, true );
+						}
+					)
+				);
+			} else {
+				$session_value = $customer->{"get_$function_key"}( 'edit' );
+			}
+			$data[ $session_key ] = (string) $session_value;
```
Comment (senadir) [inline plugins/woocommerce/includes/data-stores/class-wc-customer-data-store-session.php]: I'm afraid this logic is getting a bit too far and touching places it shouldn't? Can we filter out the allowed meta data keys list and move that logic away? we can keep the wp_json_encode here.

File: plugins/woocommerce/src/Blocks/Domain/Services/CheckoutFields.php (hunk 7 above)
Comment (senadir) [reply plugins/woocommerce/src/Blocks/Domain/Services/CheckoutFields.php:761]: Why shouldn't we persist to session? If the same guest user was to make another order, they would need to fill the fields again?

File: plugins/woocommerce/src/Blocks/Domain/Services/CheckoutFields.php [hunk 11]
```diff
@@ -800,39 +797,24 @@ private function set_array_meta( $key, $value, $object ) {
...
-				wc()->session->set( $meta_key, $meta_data );
-			} else {
-				update_user_meta( $object->get_id(), $meta_key, $meta_data );
-			}
-		} elseif ( $object instanceof \WC_Order ) {
-			$object->update_meta_data( $meta_key, $meta_data );
-		}
 
+		// Replacing all meta using `add_meta_data`. For some reason `update_meta_data` causes duplicate keys.
+		$object->add_meta_data( $meta_key, $meta_data, true );
```
Comment (senadir) [inline plugins/woocommerce/src/Blocks/Domain/Services/CheckoutFields.php:811]: The true here should handle existing meta.

File: plugins/woocommerce/src/Blocks/Domain/Services/CheckoutFields.php (hunk 7 above)
Comment (senadir) [reply plugins/woocommerce/src/Blocks/Domain/Services/CheckoutFields.php:761]: Ah okay I got it, this is only when persisting something to an order.

**Review by senadir — COMMENTED** [review]
I did a code review for this, I have a concern about the changes made to customer class, and there seems to be rouge commit here.

File: plugins/woocommerce/includes/class-wc-order-item-product.php (hunk 8 above)
Comment (mikejolley) [reply plugins/woocommerce/includes/class-wc-order-item-product.php]: Could be separate PR, but yeah, there are deprecated notices on checkout reported by query monitor.

File: plugins/woocommerce/includes/class-wc-order-item.php (hunk 9 above)
Comment (mikejolley) [reply plugins/woocommerce/includes/class-wc-order-item.php]: https://github.com/woocommerce/woocommerce/pull/44181#discussion_r1474794763

File: plugins/woocommerce/includes/data-stores/class-wc-customer-data-store-session.php (hunk 10 above)
Comment (mikejolley) [reply plugins/woocommerce/includes/data-stores/class-wc-customer-data-store-session.php]: We could, but what is the benefit to doing so?

File: plugins/woocommerce/src/Blocks/Domain/Services/CheckoutFields.php (hunk 11 above)
Comment (mikejolley) [reply plugins/woocommerce/src/Blocks/Domain/Services/CheckoutFields.php:811]: This ensures the meta overwrites existing meta to prevent duplicates. Otherwise you get duplicates of our top level keys.

File: plugins/woocommerce/includes/data-stores/class-wc-customer-data-store-session.php (hunk 10 above)
Comment (opr) [reply plugins/woocommerce/includes/data-stores/class-wc-customer-data-store-session.php]: I'm not sure of the tangible _benefit_, but my gut feeling is that WC Blocks code is creeping in here and doesn't belong. I do think we should have a filter here and then use that in our own code.

Comment (mikejolley) [reply plugins/woocommerce/includes/data-stores/class-wc-customer-data-store-session.php]: Needed to make it init during store api requests so it can hook in time, but change here https://github.com/woocommerce/woocommerce/pull/44181/commits/497f7c5bd01fc23896c41f5015e5975b838dbf5a

File: plugins/woocommerce/includes/class-wc-order-item-product.php (hunk 8 above)
Comment (opr) [reply plugins/woocommerce/includes/class-wc-order-item-product.php]: How do you feel about moving to a separate PR? I know it's extra work but if this needs to be reverted for some reason we lose that fix too. Also it can be tested without being behind a feature flag. My recommendation is to do it separately.

**Comment by mikejolley** [comment]
@senadir @opr did you want another pass now tests are passing?

**Review by opr — CHANGES_REQUESTED** [review]
I tested this out and it's working fine, however I noticed the fields in the "additional" area are being saved to the order (fine) but then persisted to the user account and then show up pre-filled during the next checkout.

I understood that these additional information fields would not persist but not sure if we changed that? @senadir do you see an issue with persisting these? The argument was contact/address fields are likely to be the same for each customer on each order, but the additional information fields would be specific to that order. My position on this is neutral, I don't mind either way but I want to make sure we're sticking to spec.

**Comment by mikejolley** [comment]
@opr I've shifted those changes out to another PR.

Regarding saving additional fields, the benefit is that if you leave and come back to checkout they are populated. Would it be desirable to keep them in session, but not save to user meta? Or does it not matter?

These fields are not editable in the account area.

**Comment by opr** [comment]
Ok, I've thought about it more and looked at Baymard. It suggests pre-filling info where possible and where it makes sense to do so. 

Since this feature is open ended and we don't know every use case of how merchants will use it I think we should pre-fill everything we can by default. It makes the feature more consistent and prevents people wondering why some fields persist and some don't. Instead, we should implement an option during field registration which will prevent persistence (since we don't know the use case, it should be up to the merchant to decide if it makes sense to pre-fill or not). This can be done as a follow up in "nice to have" though.

I think address fields and contact fields should always pre-fill and the option should only apply to additional information.

**Review by opr — APPROVED** [review]

File: plugins/woocommerce/src/StoreApi/Schemas/V1/CheckoutSchema.php [hunk 12]
```diff
@@ -260,7 +260,10 @@ function( $key, $value ) {
 	 * @return array
 	 */
 	protected function get_additional_fields_response( \WC_Order $order ) {
-		$fields   = $this->additional_fields_controller->get_all_fields_from_order( $order );
+		$fields   = wp_parse_args(
+			$this->additional_fields_controller->get_all_fields_from_order( $order ),
+			$this->additional_fields_controller->get_all_fields_from_customer( wc()->customer )
```
Comment (senadir) [inline plugins/woocommerce/src/StoreApi/Schemas/V1/CheckoutSchema.php:265]: This is to get fields saved to the customer like contact right?

Comment (mikejolley) [reply plugins/woocommerce/src/StoreApi/Schemas/V1/CheckoutSchema.php:265]: This ensures fields already in session are loaded.

**Review by senadir — APPROVED** [review]
Testing fine. Thank you for working on this.

Do we need to document \'woocommerce_customer_allowed_session_meta_keys\' in any special way or would it be picked down the road by automation tools?

**Comment by mikejolley** [comment]
Thanks @senadir 

The hook `woocommerce_customer_allowed_session_meta_keys` has a docblock and I believe we'll be the only consumers for some time. We can cover it in our docs.
