### PR TITLE
Remove FullScreenMode component from new product editor

### LINKED ISSUE #41334: WordPress sidebar scrolling alongside new product editor
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When you scroll in the new product editor and scroll, the sidebar scrolls together. For some reason, if you resize the page's width, it starts working properly.

https://github.com/woocommerce/woocommerce/assets/13437655/fcd89b83-06b0-4aa5-a113-d2535906f29e

### Expected behavior

The sidebar should be fixed, instead of scrolling together with the content.

### Actual behavior

The sidebar is scrolling

### Steps to reproduce

1. Open the new product editor
2. Scroll

### WordPress Environment

- WP 6.4
- WooCommerce 8.2.1

### Isolating the problem

- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by nathanss**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

I'm assuming that we don't use this component for anything, since we don't have full-screen mode yet. It was removing the `sticky-menu` CSS class from the body, causing the issue.

Closes #41334 .

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Activate the new product editor.
2. Go to Product > Add New.
3. Scroll up and down. The WordPress sidebar shouldn't move.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Comment 

</details>

### CODE REVIEW

File: packages/js/product-editor/src/components/editor/editor.tsx [hunk 1]
```diff
@@ -29,7 +29,7 @@ import { ShortcutProvider } from '@wordpress/keyboard-shortcuts';
 // eslint-disable-next-line @typescript-eslint/ban-ts-comment
 // @ts-ignore No types for this exist yet.
 // eslint-disable-next-line @woocommerce/dependency-group
-import { FullscreenMode, InterfaceSkeleton } from '@wordpress/interface';
+import { InterfaceSkeleton } from '@wordpress/interface';
```
Comment (mdperez86) [inline packages/js/product-editor/src/components/editor/editor.tsx:32]: Yep, maybe we can re consider this when we start working on the new design. Nor sure yet, but fullscreen can be a requested feature then.

**Review by mdperez86 — APPROVED** [review]
Approving this since we are not using that yet. Nice job @nathanss !!!!
