### PR TITLE
Adapt receipt to take into account order status

### LINKED ISSUE #51813: Add the ability to provide a printable receipt for a failed payment attempt
On the receipt front, it is currently possible to generate a receipt for any order with any status, including with a `failed` status, but the receipt does not indicate the failure, other than having an empty `Date Paid` field. The receipt rendering engine should probably take order status into account, and use a separate template when the status is `failed`.

To include in the receipt:
- Amount (same as in `order-receipt.php`)
- Date (date when it failed, it shows empty in the current `order-receipt.php` template)
- Payment method (same as in `order-receipt.php`)
- Last 4 digits of the credit card (when the payment gateway is WooPayments)
- Summary order (same as in `order-receipt.php`)

### PR DESCRIPTION
**Pull request by albarin**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

This PR adds a new `Payment status` field to the order receipts. Paid orders will show as the screenshot in the right column 👇 (notice the `paid` in the diff section titles).

| Failed order | Paid order |
|--------|--------|
|Screenshot 2024-10-21 at 11 17 38| Screenshot 2024-10-21 at 11 15 08| 

Closes https://github.com/woocommerce/woocommerce/issues/51813

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Install the `WooCommerce Stripe Gateway` plugin.
2. Check the `Enable Stripe` and `Enable test mode` options in the settings.
3. Go to the store, add a product to the cart, and go to the checkout.
4. Use a [decline test card](https://docs.stripe.com/testing#declined-payments) as a payment method and try to place the order. You should see an error indicating the order failed.
5. Go to `wp-admin/admin.php?page=wc-settings&tab=advanced&section=keys` and add a new key with `Read/Write` permissions.
6. Make the following request using the consumer key and secret generated in the previous step:
```bash
curl --insecure -u [KEY]:[SECRET] --request POST --url 'https://store.local/wp-json/wc/v3/orders/33/receipt?force_new=true' --header 'Content-Type: application/json'
```
7. It should respond with something similar to:
```json
{
  "receipt_url": "https://store.local/wc/file/transient/XXXXXXXXX",
  "expiration_date": "2024-10-15"
}
```
8. Copy the `receipt_url` and open it in a browser.
9. Check that it looks like the `Failed order` image in the PR description. It should clearly show that the receipt is for an order with `Failed` status.
10. Repeat the process using a valid test card so the order doesn't fail and check the receipt looks light the `Paid receipt` one above.

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [x] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [x] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 
Adapt receipt to take into account failed orders.
</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

**Comment by albarin** [comment]
@coreymckrill I've created this PR with the approach we talked about.
Let me know what you think. We may need design/copy suggestions (I've added a red color to the `Order failed` copy that probably is too much 😅).

File: plugins/woocommerce/src/Internal/ReceiptRendering/Templates/order-receipt.php [hunk 1]
```diff
@@ -21,10 +21,14 @@
...
 		<p>
+			<?php if ( $data['is_order_failed'] ) { ?>
+				<span class="order-status-failed"><?php echo $data['texts']['order_failed_title']; ?> </span> -
+			<?php } ?>
+
 			<?php if ( $data['payment_info'] ) { ?>
 				<span class="card-icon"></span> - <?php echo $data['payment_info']['card_last4']; ?>
 			<?php } else { ?>
-				<p><?php echo $data['payment_method']; ?></p>
+				<span><?php echo $data['payment_method']; ?></span>
```
Comment (coreymckrill) [inline plugins/woocommerce/src/Internal/ReceiptRendering/Templates/order-receipt.php:31]: Nice fix!

File: plugins/woocommerce/src/Internal/ReceiptRendering/Templates/order-receipt-css.php [hunk 2]
```diff
@@ -30,3 +30,6 @@
 	background-image: url("data:image/svg+xml;base64,<?php echo $data['payment_info']['card_icon']; ?>");
 }
 <?php } ?>
+.order-status-failed {
+	color: #FF0000;
+}
```
Comment (coreymckrill) [inline plugins/woocommerce/src/Internal/ReceiptRendering/Templates/order-receipt-css.php]: Would it be worth wrapping this is a conditional check of `$data['is_order_failed']`, similar to the card icon conditional above?

**Review by coreymckrill — APPROVED** [review]
👍 This looks good to me. I agree that the red color may be a bit much (also might not show up as clearly if printed in grayscale?).

🤔 I wonder if there's a better place to put the "order failed" message where it would be easier to notice. Perhaps, under a separate header called "Payment Status" after the "Payment Method" one? Just an idea, not saying that we should for sure do that. Either way, I'm approving this, but not merging, so we can discuss further and decide if we should have the copy editing folks take a look.

Testing notes:
* Tried with a failed order first, worked as described in testing instructions
* Then tried with a non-failed order. It worked just as before, this PR had no effect that I could see.

File: plugins/woocommerce/src/Internal/ReceiptRendering/Templates/order-receipt-css.php (hunk 2 above)
Comment (albarin) [reply plugins/woocommerce/src/Internal/ReceiptRendering/Templates/order-receipt-css.php]: Good suggestion, I think I'll remove this new CSS code.

**Comment by albarin** [comment]
> 🤔 I wonder if there's a better place to put the "order failed" message where it would be easier to notice. Perhaps, under a separate header called "Payment Status" after the "Payment Method" one? Just an idea, not saying that we should for sure do that. Either way, I'm approving this, but not merging, so we can discuss further and decide if we should have the copy editing folks take a look.

Yeah, I think that's a good idea, would look like this:
Screenshot 2024-10-15 at 11 58 37

I'll remove the red color as well, do you think we can already send it to Laura these two options and see what she thinks?

**Comment by coreymckrill** [comment]
Yep, I think the "Payment Status" header looks good there. Maybe we should just include it for normal receipts as well and put "Success" or something as the status?

> do you think we can already send it to Laura these two options and see what she thinks?

Good idea 👍

**Comment by albarin** [comment]
@coreymckrill, I've changed the PR description and the implementation logic to include a new `Order status` section that will show on every receipt. Please have a look again when you have time 🙏

**Comment by albarin** [comment]
### Discussed options

#### Adding an `Order failed` label in the payment method section
This would only show on `Failed` receipts (notice the difference in the different section titles).
| Failed order | Other orders |
|--------|--------|
|Screenshot 2024-10-16 at 10 07 59| Screenshot 2024-10-16 at 10 19 22|


#### Adding a new `Order status` section for **all** receipts
(notice the difference in the section titles in paid vs non-paid receipts)

| Other orders | Paid orders |
|--------|--------|
| failed| completed|

**Comment by lauroraa** [comment]
Hey @albarin & @coreymckrill! I much prefer the second option (having a separate "order status" line on the receipt) — it's a lot clearer and less likely to be missed. The copy used is good, so no further feedback from me :)

File: plugins/woocommerce/src/Internal/ReceiptRendering/ReceiptRenderingEngine.php [hunk 3]
```diff
@@ -381,17 +383,19 @@ private function get_order_data( WC_Order $order ): array {
 			),
 			'texts'            => array(
 				'receipt_title'                => $receipt_title,
-				'amount_paid_section_title'    => __( 'Amount Paid', 'woocommerce' ),
-				'date_paid_section_title'      => __( 'Date Paid', 'woocommerce' ),
+				'amount_paid_section_title'    => $is_order_paid ? __( 'Amount Paid', 'woocommerce' ) : __( 'Order Total', 'woocommerce' ),
+				'date_paid_section_title'      => $is_order_paid ? __( 'Date Paid', 'woocommerce' ) : __( 'Order Date', 'woocommerce' ),
 				'payment_method_section_title' => __( 'Payment method', 'woocommerce' ),
+				'order_status_section_title'   => __( 'Order status', 'woocommerce' ),
+				'order_status'                 => wc_get_order_status_name( $order->get_status() ),
```
Comment (coreymckrill) [inline plugins/woocommerce/src/Internal/ReceiptRendering/ReceiptRenderingEngine.php]: The one concern I have with this is that some merchants might have an order workflow where it goes to "processing" or "on hold" or something custom after the payment is successfully made, which they probably wouldn't want showing on their receipts.

🤔 Maybe the section title should be "Payment Status" instead of "Order Status", and then we would just have "Failed" or "Success" as the two possible values?

Comment (albarin) [reply plugins/woocommerce/src/Internal/ReceiptRendering/ReceiptRenderingEngine.php]: Yes, it makes sense, I had that implemented previously but changed it 😬 But you are right about the possible custom configuration. Just pushed the changes.

**Review by coreymckrill — APPROVED** [review]

**Comment by coreymckrill** [comment]
Since this updates one of the receipt templates, which [are customizable](https://github.com/woocommerce/woocommerce/blob/25cc4630beb034201b2c9842b1a314ee4a5913cd/plugins/woocommerce/src/Internal/ReceiptRendering/ReceiptRenderingEngine.php#L203-L214), I think this would be another good candidate for a feature highlight, or perhaps a developer advisory.
