### PR TITLE
[Accessibility] Remain coupon error visible in classic Cart/Checkout pages

### LINKED ISSUE #57664: WCAG 2.1 A and AA compliance issues with coupon input field error messages
### Current behavior in WooCommerce
The specific issue occurs when inputting an invalid coupon code on the cart or checkout page. In this case, an error message is shown below the input field. If the user selects another element (e.g. by pressing tab) the input field loses focus and the error message vanishes.

### Compliance issues regarding WCAG 2.1 A and AA
**1.4.13 – Content on Hover or Focus (Level AA)**
This criterion states that content that appears on hover or focus (like tooltips, popups, or messages) must:

- Remain visible when the pointer or focus is moved over the content itself,
- Be dismissible, and
- Remain visible until the user dismisses it or it’s no longer relevant.

In this case:

- The error message disappears as soon as the input field loses focus.
- This violates the requirement that the content must remain available unless dismissed or resolved.

**3.3.1 – Error Identification (Level A)**
This criterion requires that: If an input error is detected, it is identified and described to the user in text.

While WooCommerce does show the error message, it fails to persist the message long enough for all users to perceive it, particularly screen reader or keyboard users. If it disappears on blur, screen reader users may never hear the message, and sighted users may not see it if they tab quickly.

**2.4.7 – Focus Visible (Level AA) (indirectly relevant)**
While not about the disappearing message per se, the sudden vanishing may confuse users who rely on visible focus and clear error states.

### References
[WCAG 2.1](https://www.w3.org/TR/WCAG21/)

### Possible optimization to meet requirements
Make error messages persist until the input is corrected or the form is submitted again.

### PR DESCRIPTION
**Pull request by Manussakis**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes #57664 .

(For Bug Fixes) Bug introduced in PR # .

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Make sure your store uses the classic Cart and Checkout pages..
3. On both pages, add an invalid coupon.
4. The error below the input should remain visible even if the focus moves away from the coupon input.
5. The error should disappear as soon as the user changes the input value, either by cleaning it or typing more content.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

**Comment by Manussakis** [comment]
@dkotter This PR is ready for code review.
Thanks!

**Review by dkotter — APPROVED** [review]
@ankitguptaindia @qasumitbagthariya This is ready for QA

**Comment by ankitguptaindia** [comment]
QA Status: Needs feedback/fixes. ⚠️ 
---


Thanks @Manussakis, this works as expected! However, there is another use case that requires fixes.

When the coupon **does not exist** or has **already been applied**, the same error message is shown **repeatedly** if the user keeps clicking the button.

This flow works correctly on the `trunk` branch.

Screenshot 2025-05-26 at 4 01 04 PM

Can we also consider addressing this scenario in the fix? (Active theme: Storefront Version: 4.6.1)


**Same Flow with `trunk`:** 


https://github.com/user-attachments/assets/756b9a1a-fc3a-4dcf-95b5-d16e3add8942



**With this PR:**

https://github.com/user-attachments/assets/d976db82-6958-4ee4-8448-465f7e21317a



**Next Step-** Moving back to remediation.

**Comment by Manussakis** [comment]
Thanks, @ankitguptaindia, for finding a new use case.

@dkotter please review this commit that fixes the issue flagged by @ankitguptaindia 
- [Remove coupon error when submitting the coupon form](https://github.com/woocommerce/woocommerce/pull/58088/commits/63854c2146552b42204771112deeece424b3ad50)
Thanks!

**Review by dkotter — APPROVED** [review]

**Comment by ankitguptaindia** [comment]
**QA Status:** Needs Feedback 💡🛠️ 
----


@Manussakis – Thanks for the fixes! After the current implementation, a new scenario arises where a customer/user must manually remove an already-applied coupon in order to use a second one.



* In **block checkout**, when a coupon is already applied, the input field is **automatically cleared**. 


Can we align the behaviour in the current implementation with the above flows to enhance UX ?


### Steps to Reproduce:

1. Add a product to the cart and go to the checkout page.
2. Enter a coupon code in the field — it applies successfully.
3. Click on the coupon field again to add a second/new coupon.
4. You'll notice that the previously applied coupon is still present in the input field.
5. You will have to **manually remove** the old coupon to enter a new one.


**Flow with this PR:**

[Screen recording (1).webm](https://github.com/user-attachments/assets/77992809-70b5-4ad6-86ab-74f2aa9ac07e)


**Flow with Block CHeckout** 

[Screen recording (2).webm](https://github.com/user-attachments/assets/8f8f736c-c151-4e6f-a7a2-928f0b915469)



---

Please let me know if this needs to be discussed/reported in a separate ticket, or not related to the current changes/needs more discussion

**Comment by amesplant** [comment]
Thanks, @ankitguptaindia 

@dkotter  please review the last two commit that fixes:
**Cart**
- if a coupon threw an error (was already applied), the error was still showing when a coupon was removed; this clears the coupon input and the error

**Checkout**
- if a user continues to press Apply Coupon, the error message is no longe being duplicated
- when a coupon is applied (or removed), the coupon input is cleared, and if there was an error it is cleared now too

File: plugins/woocommerce/changelog/fix-57664 [hunk 1]
```diff
@@ -0,0 +1,4 @@
+Significance: patch
+Type: fix
+
+Remain coupon error visible in Cart and Checkout classic pages until resolved
```
Comment (dkotter) [inline plugins/woocommerce/changelog/fix-57664]:
```suggestion
Ensure coupon error remains visible in Cart and Checkout classic pages until resolved
```

**Review by dkotter — APPROVED** [review]

**Comment by ankitguptaindia** [comment]
**QA Status: Verified ✅**
----
 The main issue reported in **#57664** has also been successfully resolved and all the above-reported QA findings have been addressed.

**Comment by ankitguptaindia** [comment]
@amesplant Could you please open this PR for the next step in our process toward Woo CR?

@vikrampm1 Could you please assign to Woo CR?

**Review by ankitguptaindia — APPROVED** [review]

**Comment by vikrampm1** [comment]
@opr this PR is now ready for Woo review if you can please help tag the appropriate team, thanks!

File: plugins/woocommerce/client/legacy/js/frontend/checkout.js [hunk 2]
```diff
@@ -954,19 +956,38 @@ jQuery( function ( $ ) {
...
+				.removeAttr('aria-describedby')
+				.next('.coupon-error-notice')
+				.remove();
+		},
 		submit: function ( evt ) {
 			var $form = $( evt.currentTarget );
 			var $coupon_field = $form.find( '#coupon_code' );
 			var self = this;
 
+      self.remove_coupon_error();
```
Comment (opr) [inline plugins/woocommerce/client/legacy/js/frontend/checkout.js]: Please can we keep indentation consistent, we have added spaces here but the rest of the file uses tabs.

File: plugins/woocommerce/client/legacy/js/frontend/checkout.js [hunk 3]
```diff
@@ -934,7 +934,9 @@ jQuery( function ( $ ) {
 				return;
 			}
 
-			var msg = $( $.parseHTML( html_element ) ).text().trim();
+      this.remove_coupon_error();
+
+      var msg = $( $.parseHTML( html_element ) ).text().trim();
```
Comment (opr) [inline plugins/woocommerce/client/legacy/js/frontend/checkout.js]: Inconsistent indentation here also

**Review by opr — CHANGES_REQUESTED** [review]
Thanks @Manussakis this looks pretty good, I left two comments about spacing, kind of nitpicky, but I think consistency is important. 

When the issues I mentioned are addressed I will approve.

**Review by opr — CHANGES_REQUESTED** [review]
Thanks @Manussakis this looks pretty good, I left two comments about spacing, kind of nitpicky, but I think consistency is important. 

When the issues I mentioned are addressed I will approve.

**Comment by vikrampm1** [comment]
With @Manussakis unavailable, @amesplant this is back to you to address a couple of minor updates noted [here](https://github.com/woocommerce/woocommerce/pull/58088#pullrequestreview-2910691319). Thanks!

File: plugins/woocommerce/client/legacy/js/frontend/checkout.js (hunk 3 above)
Comment (amesplant) [reply plugins/woocommerce/client/legacy/js/frontend/checkout.js]: @opr updated the spacing, apologies from my IDE :D

File: plugins/woocommerce/client/legacy/js/frontend/checkout.js (hunk 2 above)
Comment (amesplant) [reply plugins/woocommerce/client/legacy/js/frontend/checkout.js]: @opr updated the spacing, apologies from my IDE :D

**Comment by amesplant** [comment]
@opr  updated the spacing, apologies from my IDE :D

**Review by opr — APPROVED** [review]
Thanks @Manussakis! Looks good to me, I tested and it's working well, thanks for the changes @amesplant
