### PR TITLE
Fix: Reset password form missing required indicator

### LINKED ISSUE #43660: Accessibility: Reset password form missing required indicator
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

The reset password form on the My Account page does not have a required indicator.
Screenshot of reset password form

Relevant code: https://github.com/woocommerce/woocommerce/blob/33ae0d607df0704e59025bb1b33cdcb96b497b0f/plugins/woocommerce/templates/myaccount/form-lost-password.php#L28

### Expected behavior

All required fields should have a visible and auditory required indicator.

Add an aria-label to the asterisk or change it to visible required text (preferred).
A) Best:
`<label for="user_login"><?php esc_html_e( 'Username or email', 'woocommerce' ); ?></label>&nbsp;<span class="required">(required)</span></label>`

B) Sufficient:
`<label for="user_login"><?php esc_html_e( 'Username or email', 'woocommerce' ); ?></label>&nbsp;<span class="required" aria-label="required">*</span></label>`

Add the required attribute to the inputs like this:
<input class="woocommerce-Input woocommerce-Input--text input-text" type="text" name="user_login" id="user_login" autocomplete="username" required />

### Actual behavior

No required indicator for sighted or screen reader users.

### Steps to reproduce

See code linked above.

### WordPress Environment

N/A

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by naman03malhotra**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes #43660 

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Visit `accounts` section of the shop.
2. Make sure you are logged out.
3. Goto login page and select forgot password.
4. See the new (*) mark along with the `username or email` label
5. Enable Voice reader (On Mac, press `CMD + F5`). There must be other keys for other OS.
6. Click the form field.
7. The voice reader will read it out as a required field.

image

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce/templates/myaccount/form-lost-password.php [hunk 1]
```diff
@@ -25,7 +25,7 @@
 	<p><?php echo apply_filters( 'woocommerce_lost_password_message', esc_html__( 'Lost your password? Please enter your username or email address. You will receive a link to create a new password via email.', 'woocommerce' ) ); ?></p><?php // @codingStandardsIgnoreLine ?>
 
 	<p class="woocommerce-form-row woocommerce-form-row--first form-row form-row-first">
-		<label for="user_login"><?php esc_html_e( 'Username or email', 'woocommerce' ); ?></label>
+		<label for="user_login"><?php esc_html_e( 'Username or email', 'woocommerce' ); ?>&nbsp;<span class="required" aria-label="required">*</span></label>
```
Comment (jorgeatorres) [inline plugins/woocommerce/templates/myaccount/form-lost-password.php]: I guess there are different approaches but IMO instead of using [`aria-label`](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-label) to give the `*` an accessible name, we should instead use [`aria-required="true"`](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-required) on the `<input>` field itself.

The voice reader software should respect that too and indicate the field is required.

What do you think?

**Review by jorgeatorres — CHANGES_REQUESTED** [review]
Hi @naman03malhotra!

Thanks for picking this up. Left some suggestion so that we can discuss the approach.

Also, there are similar accessibility issues in the login form itself. Unless you're already taking care of that in another PR, maybe we can fix those too here?

Please let me know what you think.

File: plugins/woocommerce/templates/myaccount/form-lost-password.php (hunk 1 above)
Comment (naman03malhotra) [reply plugins/woocommerce/templates/myaccount/form-lost-password.php]: Thanks for the feedback, yeah there are multiple ways to fix this issue. Though I like the approach your suggested as it better aligns with `a11y` standards. Made change here https://github.com/woocommerce/woocommerce/pull/47229/commits/995928a63327e70230da4d312259ed06ca70a8ca

**Comment by naman03malhotra** [comment]
>Also, there are similar accessibility issues in the login form itself. Unless you're already taking care of that in another PR, maybe we can fix those too here?

Can you please point me to those issues?  

I might take a pause on the `a11y` issues and move to a different focus area, so if I do plan to pick that up, I'll probably do it in a separate PR.

**Comment by jorgeatorres** [comment]
> Can you please point me to those issues?

Sure! I was referring to these files: https://github.com/woocommerce/woocommerce/blob/8ee74ede0ebc1957089af08207ae2a1a8250610e/plugins/woocommerce/templates/myaccount/form-login.php, https://github.com/woocommerce/woocommerce/blob/8ee74ede0ebc1957089af08207ae2a1a8250610e/plugins/woocommerce/templates/global/form-login.php, though there are probably others.

You can see that the fields have the `*` symbol but neither an `aria-label` on it or a `aria-required` on the field.

**Review by jorgeatorres — APPROVED** [review]
LGTM. Thank you @naman03malhotra!
