### PR TITLE
Fix payment instruction location in on-hold email (#31880)

### LINKED ISSUE #31880: Payment instructions placement disrupts text flow in on-hold email
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Payment instructions are placed between the sentence _“In the meantime, here’s a reminder of what you ordered:”_ and the actual list of ordered items. I find this text flow broken for the readers of the email (customers).
screenshot of described issue

### Expected behavior

I can think of two possible solutions:

1. The payment instructions should be moved _after_ the table of ordered items. This would only require altering the hook used to include the payment instructions but it would make the payment instructions less prominent although it’s the very important part of the on-hold email.
2. The payment instructions should be placed like so: _“It’s on-hold until we confirm that payment has been received. `<payment instructions>` In the meantime, here’s a reminder of what you ordered:”_ This would mean a better experience for the customers but it means more work for the developers and translators (a current string split into two).

### Actual behavior

See above.

### Steps to reproduce

1. Set up an offline payment method like BACS.
2. Create an order using the offline payment method.
3. Open the received on-hold email sent to the customer.

### WordPress Environment

`
WordPress address (URL): http://localhost/woocommerce-dev
Site address (URL): http://localhost/woocommerce-dev
WC Version: 6.2.0
REST API Version: ✔ 6.2.0
WC Blocks Version: ✔ 6.7.3
Action Scheduler Version: ✔ 3.4.0
WC Admin Version: ✔ 3.1.0
Log Directory Writable: ✔
WP Version: 5.9
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.48 (Unix) PHP/7.4.20
PHP Version: 7.4.20
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.77.0
(SecureTransport) OpenSSL/1.1.1k

SUHOSIN Installed: –
MySQL Version: 8.0.25
Max Upload Size: 8 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 6.2.0
WC Database Prefix: wp_
Total Database Size: 10.51MB
Database Data Size: 7.62MB
Database Index Size: 2.89MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.13MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_ngg_album: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_ngg_gallery: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_ngg_pictures: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 4.03MB + Index: 0.03MB + Engine InnoDB
wp_postmeta: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_posts: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_transients: Data: 1.52MB + Index: 0.02MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wptests_actionscheduler_actions: Data: 0.02MB + Index: 0.13MB + Engine InnoDB
wptests_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wptests_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wptests_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wptests_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wptests_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wptests_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wptests_options: Data: 0.16MB + Index: 0.03MB + Engine InnoDB
wptests_postmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wptests_posts: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wptests_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wptests_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wptests_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wptests_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wptests_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wptests_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wptests_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wptests_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wptests_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wptests_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wptests_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wptests_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wptests_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wptests_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wptests_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wptests_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wptests_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wptests_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wptests_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wptests_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wptests_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wptests_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wptests_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wptests_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wptests_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wptests_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wptests_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wptests_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wptests_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wptests_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wptests_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wptests_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wptests_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB

### Post Type Counts ###

attachment: 1
ngg_gallery: 1
ngg_pictures: 2
page: 7
post: 1
product: 2
product_variation: 6
revision: 1
shop_order: 2

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 6.2.0

### Inactive Plugins (6) ###

Automatic NBSP: by Damian Góra – 1.5.4
Dedicated Transients: by Derrick Hammer – 0.1.10
NextGEN Gallery: by Imagely – 3.23
WebP Express: by Bjørn Rosell – 0.25.0
Whitespace Pro: by Melebius – 0.1
WooCommerce: by Automattic – 6.3.0-dev

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #6 - /shop/
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 3.9.1
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 33
Oldest: 2022-01-13 11:56:38 +0000
Newest: 2022-02-10 09:16:33 +0000

### Status report information ###

Generated at: 2022-02-10 10:44:53 +00:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by Melebius**
Show payment instructions after the relevant sentence and before the intro to ordered items.

New action 'woocommerce_email_payment_instructions' introduced.

### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes #31880 using the more thorough solution (option 2). This is the new look of the email:

screenshot

### How to test the changes in this Pull Request:

1. Set up an offline payment method like BACS.
2. Create an order using the offline payment method.
3. Open the received on-hold email sent to the customer.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally? _Yes, unit tests._

This change should be safe to use with extensions adding other offline payments methods. They would simply continue to show the payment instructions in the original location until they’re updated to use the new hook.

### Changelog entry

> Tweak: Corrected the position of payment instructions in on-hold emails

### FOR PR REVIEWER ONLY:

* [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

**Review by vedanshujain — COMMENTED** [review]
@barryhughes suggested that we can actually just remove the text `'In the meantime, here’s a reminder of what you ordered:` and that will also fix the issue. See inline comment

File: plugins/woocommerce/templates/emails/plain/customer-on-hold-order.php [hunk 1]
```diff
@@ -23,7 +23,11 @@
 
 /* translators: %s: Customer first name */
 echo sprintf( esc_html__( 'Hi %s,', 'woocommerce' ), esc_html( $order->get_billing_first_name() ) ) . "\n\n";
-echo esc_html__( 'Thanks for your order. It’s on-hold until we confirm that payment has been received. In the meantime, here’s a reminder of what you ordered:', 'woocommerce' ) . "\n\n";
+echo esc_html__( 'Thanks for your order. It’s on-hold until we confirm that payment has been received.', 'woocommerce' ) . "\n\n";
```
Comment (vedanshujain) [inline plugins/woocommerce/templates/emails/plain/customer-on-hold-order.php:26]: This sentence 

echo esc_html__( 'Thanks for your order. It’s on-hold until we confirm that payment has been received. In the meantime, here’s a reminder of what you ordered:', 'woocommerce' ) . "\n\n";

to

echo esc_html__( 'Thanks for your order. It’s on-hold until we confirm that payment has been received. ', 'woocommerce' ) . "\n\n";

**Comment by Melebius** [comment]
> @barryhughes suggested that we can actually just remove the text `'In the meantime, here’s a reminder of what you ordered:` and that will also fix the issue. See inline comment

Yes, this would be the simplest solution if no one insists on keeping that sentence.

**Comment by barryhughes** [comment]
> Yes, this would be the simplest solution if no one insists on keeping that sentence.

I think simplicity wins, here—the existing solution is comprehensive and would otherwise be a good way to go: but that particular phrase doesn't really seem to be needed (not to mention, it can easily be added back by those who wish to keep it) so reducing the complexity and size of the change seems worthwhile :+1:

**Comment by Konamiman** [comment]
Hi @Melebius, it seems that we agreed that  just removing the "In the meantime..." part was a better solution. Could you please implement the change so we can unblock this pull request?

**Comment by barryhughes** [comment]
- Rebased against `trunk` since it's been sitting for a while.
- Rolled back the introduction of a new hook.
- Simplified the wording (the simpler option discussed earlier).

**Review by jorgeatorres — APPROVED** [review]
LGTM 👍
