### PR TITLE
Product gallery/fix console error

### LINKED ISSUE #52936: Product Gallery: Displays error after page refresh in Editor
**Steps to reproduce:**

1. Go to Single Product template
2. Replace Product Image Gallery with Product Gallery (Beta)
3. Save the template and refresh the page

**Expected:** Block displays normally
**Actual:** There's error displayed:

```
**Sorry, an error occurred**
The following error was returned
productGalleryClientId and clientId codes mismatch.
```

**Video:**

https://github.com/user-attachments/assets/3e555267-fffb-41d9-94b4-9f99fcb8f1e8

### PR DESCRIPTION
**Pull request by roykho**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes https://github.com/woocommerce/woocommerce/issues/52936

This PR reverts the mismatch error that is shown when Product Gallery block is added and saved/refreshed. This change was first implemented [here](https://github.com/woocommerce/woocommerce/pull/51189) to fix two issues [here](https://github.com/woocommerce/woocommerce/issues/51154) and [here](https://github.com/woocommerce/woocommerce/issues/51175) but caused a regression.

- While I reverted the mismatch error trap, I kept the defensive guards to prevent https://github.com/woocommerce/woocommerce/issues/51154 and https://github.com/woocommerce/woocommerce/issues/51175 from happening.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

### Test Case 1

1. Go to Appearance->Editor->Templates->WooCommerce->Single Product Template.
2. Click on the Product Image Gallery block in the Document Overview (list view) and remove it.
3. In it's place, add the Product Gallery (Beta) block. Ensure there are no console errors.
4. Save the template and ensure you see the block in the frontend and functioning as expected.

### Test Case 2

1. Go to Appearance->Editor->Patterns->Add New Pattern.
2. Enter any name for your pattern and click on Add.
3. Click on the Document Overview (list view) and add the Product Gallery (Beta) block to the page. Save.
4. Go to Appearance->Editor->Templates->WooCommerce->Single Product Template.
5. Click on the Product Image Gallery block in the Document Overview (list view) and remove it.
6. In it's place, add the new pattern you just added in step 2.
7. Ensure there are no errors or hanging in the browser.
8. Save the template and ensure you see the block in the frontend and functioning as expected.

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 
Product Gallery (Beta) - Fix block not rendering after being added.
</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce-blocks/assets/js/blocks/product-gallery/utils.tsx [hunk 1]
```diff
@@ -136,10 +136,10 @@ export const moveInnerBlocksToPosition = (
 ): void => {
 	const { getBlock, getBlockRootClientId, getBlockIndex } =
 		select( 'core/block-editor' );
+	const { moveBlockToPosition } = dispatch( 'core/block-editor' );
```
Comment (kmanijak) [inline plugins/woocommerce-blocks/assets/js/blocks/product-gallery/utils.tsx]: Nitpick but what's the reason for this change? I think it's a good approach to initiate variable only when it's going to be used. If anywhere, I'd move to this `if` statement as it's only used in this particular case:

https://github.com/woocommerce/woocommerce/blob/9f57a9a7b7d93a2e0ddb78e117c52fc9050f4072/plugins/woocommerce-blocks/assets/js/blocks/product-gallery/utils.tsx#L212

File: plugins/woocommerce-blocks/assets/js/blocks/product-gallery/edit.tsx [hunk 2]
```diff
@@ -136,16 +132,14 @@ export const Edit = ( {
...
 
 		setAttributes( {
 			...attributes,
 			mode,
-			productGalleryClientId: newProductGalleryClientId,
+			productGalleryClientId: clientId,
 		} );
 		// Move the Thumbnails block to the correct above or below the Large Image based on the thumbnailsPosition attribute.
-		moveInnerBlocksToPosition( attributes, newProductGalleryClientId );
+		moveInnerBlocksToPosition( attributes, clientId );
```
Comment (kmanijak) [inline plugins/woocommerce-blocks/assets/js/blocks/product-gallery/edit.tsx:142]: It may be me misunderstanding the concept of using `clientId` and  `productGalleryClientId` attribute. But my feeling is we should use attribute here. Also, in line 158 raw `clientId` is passed to the context. 

```suggestion
		moveInnerBlocksToPosition( attributes ); // and just read the `productGalleryClientId` from `attributes` inside the function
```

Otherwise seems the whole `productGalleryClientId` attribute is redundant as all the blocks inside seems to be relying on `context.productGalleryClientId` 🤔

**Review by kmanijak — COMMENTED** [review]
It works as expected! But I feel there's some redundancy with `productGalleryClientId` attribute.

I think either it should be removed completely or used in the `plugins/woocommerce-blocks/assets/js/blocks/product-gallery/edit.tsx`. Unless there's a good reason to keep it (some hidden block logic or attribute recalculation required so it works correctly? In that case I'd add a comment explaining it's necessary.)

**Comment by roykho** [comment]
@kmanijak Thanks for the initial review. Your suggestions are valid however this is mainly just a revert of the original PR with the safe guards left in place. So I didn't really add any code to this. This is mainly just to get the block working again without the regression errors pointed out in the PR notes.

For any code revisions, I think should be done in separate PR.

**Review by kmanijak — APPROVED** [review]
> @kmanijak Thanks for the initial review. Your suggestions are valid however this is mainly just a revert of the original PR with the safe guards left in place. So I didn't really add any code to this. This is mainly just to get the block working again without the regression errors pointed out in the PR notes.
> For any code revisions, I think should be done in separate PR.

I see, it makes sense and I'm approving then becvause it works well! If you don't mind though, you can skip changing `plugins/woocommerce-blocks/assets/js/blocks/product-gallery/utils.tsx` as that change seemed to be a nice little optimisation.
