### PR TITLE
Fix classic checkout validation

### LINKED ISSUE #56353: Error thrown in checkout page when validation error is getting added to DOM
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

An inline error message is thrown when validation fails and the error is added to the DOM on the checkout page. The issue started getting to happen after changes happend in [this commit](https://github.com/woocommerce/woocommerce/commit/53814af6783d1afbda0c6b69fc2ce7ac5153ef51) in the [line](https://github.com/woocommerce/woocommerce/commit/53814af6783d1afbda0c6b69fc2ce7ac5153ef51#diff-5af603e494bcdbedc4d7fd1af25480af8804f352010958fe0b3025608580234dR654). Mostly the commit was related to "Secure link inside inline error messages".  In the code, instead of using append(), appendChild() is used.

### Expected behavior

It should not throw error when inline message is getting added to DOM.

### Actual behavior

Image

### Steps to reproduce

1. Go to checkout page after adding any product to cart.
2. Fill the billing details and leave one of the required fields blank so that error message is thrown on validation.
3. Now Click on "Proceed to Pay"

You can see error thrown on console stating "$formRow.appendChild is not a function"

### WordPress Environment

<details><summary>System Status Report</summary>

```
### WordPress Environment ###

WordPress address (URL): [Redacted]
Site address (URL): [Redacted]
WC Version: 9.7.1
Legacy REST API Package Version: The Legacy REST API plugin is not installed on this site.
Action Scheduler Version: ✔ 3.9.0
Log Directory Writable: ✔
WP Version: 6.7.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.41 (Ubuntu)
PHP Version: 8.2.27
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.68.0
OpenSSL/1.1.1f

SUHOSIN Installed: –
MySQL Version: 8.0.41-0ubuntu0.20.04.1
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

[REDACTED]

### Post Type Counts ###

attachment: 7
customize_changeset: 3
forum: 2
nav_menu_item: 7
page: 10
post: 2
product: 1
reply: 13
revision: 16
shop_order: 4
topic: 11
wp_global_styles: 1
wp_navigation: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (8) ###

WP CanvasJS: by Vishwas R – 1.5
Akismet Anti-spam: Spam Protection: by Automattic - Anti-spam Team – 5.3.5
bbPress: by The bbPress Contributors – 2.6.12
Classic Editor: by WordPress Contributors – 1.6.7
WooCommerce Stripe Gateway: by Stripe – 9.2.0
WooCommerce: by Automattic – 9.7.1
Yoast SEO: by Team Yoast – 24.6
WP Cerber Security, Anti-spam & Malware Scan: by Cerber Tech Inc. – 9.0

### Inactive Plugins (4) ###

Advance Ecommerce Tracking Premium: by theDotstore – 3.6.4
Conversios.io - All-in-one Google Analytics, Pixels and Product Feed Manager for WooCommerce: by Conversios – 5.2.1
Featured Image from URL (FIFU): by fifu.app – 4.1.4
WooCommerce Google Analytics Integration: by WooCommerce – 1.5.18

### Settings ###

Legacy API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 185 B

### WC Pages ###

Shop base: #5 - /shop/
Cart: #6 - /cart/ -  Contains the woocommerce_cart shortcode
Checkout: #7 - /checkout/ -  Contains the woocommerce_checkout shortcode
My account: #8 - /my-account/ -  Contains the [woocommerce_my_account] shortcode
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty
Version: 2.8
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
Theme type: Classic theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
onboarding
onboarding-tasks
pattern-toolkit-full-composability
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
printful
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page
launch-your-store
add-to-cart-with-options-stepper-layout

Disabled Features: product-data-views
experimental-blocks
coming-soon-newsletter-template
minified-js
product-pre-publish-modal
settings
async-product-editor-category-field
product-editor-template-system
blueprint
reactify-classic-payments-settings
use-wp-horizon
blockified-add-to-cart

Daily Cron: ✔ Next scheduled: 2021-07-08 02:57:08 +00:00
Options: ✔
Notes: 90
Onboarding: skipped

### Action Scheduler ###

Complete: 194
Oldest: 2022-06-27 10:10:53 +0000
Newest: 2025-01-31 11:13:35 +0000

Pending: 6
Oldest: 2025-01-31 11:20:59 +0000
Newest: 2025-03-13 09:43:38 +0000

Failed: 3
Oldest: 2025-01-31 10:48:04 +0000
Newest: 2025-01-31 11:13:21 +0000


### Status report information ###

Generated at: 2025-03-13 09:47:40 +00:00
```
</details>

### Isolating the problem

- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by nielslange**
### Changes proposed in this Pull Request:

Closes #56353.

(For Bug Fixes) Bug introduced in PR  #56047.

During a recent security audit, we've improved the security when displaying inline error messages. While working on this section, we've accidentally used the JS functions `appendChild` and `setAttribute` on a jQuery object, instead of using the jQuery functions `append` and `attr`. As a result of that, the inline error messages disappeared, and an error occurred in the console, when a shopper submitted an incomplete billing or address form while using the classic checkout. This PR corrects the functions to ensure that the inline error messages are displayed correctly, and to prevent the console error.

### Screenshots or screen recordings:

<table>
<tr>
<td valign="top">Before:
<br><br>
Screenshot 2025-03-19 at 13 34 33
</td>
<td valign="top">After:
<br><br>
Screenshot 2025-03-19 at 13 32 43
</td>
</tr>
</table>

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Create a page with the classic checkout.
2. Open an incognito window.
3. Add a product to the cart.
4. Go to the checkout page with the classic checkout.
5. Open the console.
6. Without filling out the billing and shipping forms, try to submit the order.
7. Verify that inline error messages appear for all required fields.
8. Verify that no error is visible in the console.

### Testing that has already taken place:

See testing steps above.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

**Comment by nielslange** [comment]
Closing and re-opening to trigger the CI pipeline.

File: plugins/woocommerce/client/legacy/js/frontend/checkout.js [hunk 1]
```diff
@@ -651,9 +651,9 @@ jQuery( function( $ ) {
 					errorMessage.className = 'checkout-inline-error-message';
 					errorMessage.textContent = msg;
 
-					$formRow.appendChild( errorMessage );
-					$field.setAttribute( 'aria-describedby', descriptionId );
-					$field.setAttribute( 'aria-invalid', 'true' );
```
Comment (ralucaStan) [inline plugins/woocommerce/client/legacy/js/frontend/checkout.js:656]: How about making this code more defensive:


```
if ($formRow && errorMessage) {
    $formRow.append(errorMessage);
}

if ($field) {
    $field.attr('aria-describedby', descriptionId);
    $field.attr('aria-invalid', 'true');
}
```

**Review by ralucaStan — COMMENTED** [review]
Added a small comment. Are there any basic unit tests that can be added as part of this PR? Maybe by adding an assertion to an existing test file? I know you created a separate ticket to add tests later, but why not doing it in this PR?

File: plugins/woocommerce/client/legacy/js/frontend/checkout.js (hunk 1 above)
Comment (nielslange) [reply plugins/woocommerce/client/legacy/js/frontend/checkout.js:656]: Thanks for your review, @ralucaStan. That's a great suggestion to code more defensive. I've changed the code as follows:

```js
if ( $field.length === 1 ) {
	const descriptionId = dataId + '_description';
	const msg = $this.text().trim();
	const $formRow = $field.closest( '.form-row' );

	const errorMessage = document.createElement( 'p' );
	errorMessage.id = descriptionId;
	errorMessage.className = 'checkout-inline-error-message';
	errorMessage.textContent = msg;

	if ( $formRow && errorMessage.textContent.length > 0 ) {
		$formRow.append( errorMessage );
	}

	$field.attr( 'aria-describedby', descriptionId );
	$field.attr( 'aria-invalid', 'true' );
}
```

I did apply the first suggestion and slightly improved it. As `errorMessage` gets created shortly before the check,  it would always exist. Therefore, I'm also checking if it actually has a value, to prevent adding an empty element to the DOM, which might use up some space.

As for the second check, that's not needed as this part is already wrapped inside `if ( $field.length === 1 ) { ... }`. This way, `$field` does exist if that particular section gets executed.

I also checked for unit tests, but I could not see any unit tests for the classic checkout, apart from the PHPUnit tests. To get this CFE shipped on time, I'd rather follow-up with the tests in #56539. 

Would you agree with that and could you do another review?

**Review by mikejolley — APPROVED** [review]
Thanks @nielslange I've retested this and works as described. No errors on my console.

I agree that this can ship to speed up the CFE so long as tests are added in https://github.com/woocommerce/woocommerce/issues/56539. This is quite easy to manual test and is unlikely to regress as this script is not touched often and is not influenced by the rest of the codebase.

Thank for your detailed PR testing steps.

**Comment by nielslange** [comment]
> I agree that this can ship to speed up the CFE so long as tests are added in #56539. This is quite easy to manual test and is unlikely to regress as this script is not touched often and is not influenced by the rest of the codebase.

Thanks for confirming this.

> Thank for your detailed PR testing steps.

Thank you for reviewing and approving this PR, @mikejolley. 🙌
