### PR TITLE
Fix tax settings pagination 

### LINKED ISSUE #50074: WooCommerce Standard rate taxes  getting issues with pagination
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

1.) WooCommerce standard rate tax list; when click on the arrow of the pagintation then the cursor changed to text cursor
2.) While loading and after clicking on the pagination hover anywhere only the text cursor is visible and not able to do click anything
3.) Till then when I hover anywhere getting text cursor instead of pointed cursor .
4.) Loading time is very high 

### Expected behavior

When hover on arrow buttons of pagination should get pointed cusor when change the page 

While changing the page or in between loading process the cursor should not be changed to text cursor when hovering anywhere expect for the text one 

### Actual behavior

1.) WooCommerce standard rate tax list; when click on the arrow of the pagintation then the cursor changed to text cursor
2.) While loading and after clicking on the pagination hover anywhere only the text cursor is visible and not able to do click anything
3.) Till then when I hover anywhere getting text cursor instead of pointed cursor .
4.) Loading time is very high 

When hover on arrow buttons of pagination should get pointed cusor when change the page 

While changing the page or in between loading process the cursor should not be changed to text cursor when hovering anywhere expect for the text one 

### Steps to reproduce

1. Go to WooCommerce 
2. Go to Settings 
3. Enable Tax 
4. Then click on standard rates
5. and import more than 300 tax so as to get pagination
6. then click on arrow button or hover getting text cusror instead of pointer.

https://jam.dev/c/a27f1f4b-d7ce-4e96-a619-f6bfb4587bf5

### WordPress Environment

<details><summary>System Status Report</summary>

```
### WordPress Environment ###

WordPress address (URL): [Redacted]
Site address (URL): [Redacted]
WC Version: 9.1.4
Legacy REST API Package Version: The Legacy REST API plugin is not installed on this site.
Action Scheduler Version: ✔ 3.7.4
Log Directory Writable: ✔
WP Version: 6.6.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.41 (Ubuntu)
PHP Version: 8.2.14
PHP Post Max Size: 200 MB
PHP Time Limit: 360
PHP Max Input Vars: 1000
cURL Version: 7.68.0
OpenSSL/1.1.1f

SUHOSIN Installed: –
MySQL Version: 8.0.37-0ubuntu0.20.04.3
Max Upload Size: 200 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

[REDACTED]

### Post Type Counts ###

attachment: 495
mt_pp: 1
page: 7
post: 1
product: 46
product_variation: 20
revision: 6
shop_coupon: 4
shop_order_placehold: 11
wp_font_family: 12
wp_navigation: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (3) ###

Query Monitor: by John Blackbourn – 3.16.4
WooCommerce: by Automattic – 9.1.4
WP PHP Console (Forked for wppcd): by Fulvio Notarstefano – 9.9.10

### Inactive Plugins (3) ###

POS RFGUN Socket Search Addon: by Webkul – 1.0.0
WooCommerce Point of Sale: by Webkul – 5.2.0
WooCommerce Shopify Connector: by Webkul – 3.1.0

### Dropin Plugins () ###

db.php: Query Monitor Database Class (Drop-in)

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: e_ticket (e_ticket)
external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 551 KB

### WC Pages ###

Shop base: #7 - /shop/
Cart: #8 - /cart/ -  Contains the [woocommerce_cart] shortcode
Checkout: #9 - /checkout/ -  Contains the [woocommerce_checkout] shortcode
My account: #10 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 4.6.0
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page
launch-your-store

Disabled Features: experimental-blocks
minified-js
pattern-toolkit-full-composability
product-pre-publish-modal
printful
settings
async-product-editor-category-field
product-editor-template-system

Daily Cron: ✔ Next scheduled: 2024-07-30 06:15:13 +00:00
Options: ✔
Notes: 77
Onboarding: completed

### Action Scheduler ###

Complete: 15,962
Oldest: 2024-07-02 06:23:45 +0000
Newest: 2024-07-29 11:00:29 +0000

Failed: 8
Oldest: 2024-04-03 06:22:19 +0000
Newest: 2024-07-29 11:01:32 +0000

Pending: 2
Oldest: 2024-07-30 04:44:02 +0000
Newest: 2024-07-30 10:18:16 +0000


### Status report information ###

Generated at: 2024-07-29 11:32:59 +00:00
```
</details>

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by ismaeldcom**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes #50074

- Replace the `$tbody` render logic with a single DOM operation.
- Stop event propagation on page change to avoid triggering jQuery UI Menu collapse event.
- Update `wc-tax-table-pagination` template to ensure consistency with WP list tables.

After profiling the code using the browser tools, I noticed that the next page task was taking a lot of time to render, and I traced it back to `this.$el.empty()`, which removes children one at a time. After exploring various options for doing a single DOM manipulation, such as using the document fragment API, I decided that string concatenation and using `innerHTML` was the simplest, most readable, and compatible solution.

The jQuery UI Menu Collapse event is fired on every page click, so stopping the event propagation also saves us some extra milliseconds.

I think the issue started to become more noticeable after #47444, because the mutation observer is triggered on every DOM manipulation in the table, which takes an extra ~600ms. We should look for a better way to do this, such as using a form event and comparing the data. But that's beyond the scope of this issue.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. A large number of tax records are required to test it properly:
    - Download [nearly 40k tax rates from the US](https://raw.githubusercontent.com/MirzaAreebBaig/Woocommerce-US-ZipCodes-TaxRates/refs/heads/main/tax_rates.csv).
    - Go to **WooCommerce → Settings → Tax → Standard rates**
    - Click on **Import CSV**
    - Select the downloaded `tax_rates.csv` file
2. Navigating across pages shouldn't block the UI
3. Confirm that the pagination looks and behaves like any other WP one (EG orders page)

### Comparison
| Before | After |
|--------|--------|
|before|after|

https://github.com/user-attachments/assets/8d0b325b-7b11-4be2-ad1e-6b4d704b8525

https://github.com/user-attachments/assets/c8e50ad3-1bdb-432d-a169-663d20ea2e83

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

Fix tax settings pagination blocking the UI and ensure design consistency.

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce/client/legacy/js/admin/settings-views-html-settings-tax.js [hunk 1]
```diff
@@ -145,16 +145,11 @@
...
-					// Blank out the contents.
-					this.$el.empty();
-
-					if ( paged_rates.length ) {
+					if (paged_rates.length) {
 						// Populate $tbody with the current page of results.
-						$.each( paged_rates, function( id, rowData ) {
-							view.$el.append( view.rowTemplate( rowData ) );
-						} );
+						this.el.innerHTML = paged_rates.map(rowData => view.rowTemplate(rowData)).join('');
```
Comment (jessepearson) [inline plugins/woocommerce/client/legacy/js/admin/settings-views-html-settings-tax.js]: Nitpicky question, should this have the spaces like this?

```
this.el.innerHTML = paged_rates.map( rowData => view.rowTemplate( rowData ) ).join( '' );
```

**Review by jessepearson — APPROVED** [review]
This is an amazing fix. I haven't touched this page in years, but I remember it being such a nightmare. Besides the nitpick, this is good to go :shipit:

File: plugins/woocommerce/client/legacy/js/admin/settings-views-html-settings-tax.js (hunk 1 above)
Comment (ismaeldcom) [reply plugins/woocommerce/client/legacy/js/admin/settings-views-html-settings-tax.js]: Great catch! This legacy code uses ESLint for code formatting, but the autoformat doesn't seem to add these spaces. Addressed in 405349b
