### PR TITLE
Remove cart contents session on next user initiated request

### LINKED ISSUE #60950: Remove `removed_cart_contents` from session data when no longer needed.
Part of [WOOPLUG-4180](https://linear.app/a8c/issue/WOOPLUG-4180/clean-up-session-data-so-cookie-can-be-removed-when-empty)  / #57780

When an item is removed from a user's shopping cart, a session variable is set storing details about the removed item.  This is used by the classic cart implementation to provide an `Undo` link.  This undo button is only available in the classic cart immediately after a user removes the item.  However, the `removed_cart_contents` value stays in the session, keeping it from being empty.

The ideal fix will remove the `removed_cart_contents` value as soon as it is no longer needed.  I am not sure of any triggers we can use for this off hand since the value has to potentially live for multiple requests.  

To reproduce:

1.  Add an item to your cart
2. Remove the item from the cart - from any cart implementation, classic, shortcode, or blocks.
3. Add logging to see the session content, e.g.

   ```
   add_filter( 'woocommerce_restored_session_data', function ( $session_data ) {
   	error_log( json_encode( $session_data ) );
   }
   ```

### PR DESCRIPTION
**Pull request by joshuatf**
### Changes proposed in this Pull Request:

This is an alternative approach to https://github.com/woocommerce/woocommerce/pull/61030 where bugs were discovered with Product Bundles undo implementation.

This PR removes `removed_cart_contents` from the session after the next request so that the undo functionality continues to work for the following user request and requests can be edge cached after a cart is emptied.  This results in much higher performance where edge caching is available and was previously missed until the session was fully cleared.

* Remove `removed_cart_contents` from the session on the next user request after an item was removed
* (optional) Expiration times have been added to the session data, but we can probably stick with one approach as this should not be necessary if the above is working correctly

Closes #60950 .

### Screenshots or screen recordings:

Screenshot 2025-09-17 at 11 26 48 AM

### How to test the changes in this Pull Request:

```php
add_action(
	'wp_head',
	function () {
		$session = WC()->session;
		echo '<pre>' . print_r( $session->get_session_data(), true ) . '</pre>';
	}
);
add_action(
	'woocommerce_remove_cart_item',
	function ( $cart_item_key, $cart ) use ( &$hooks_fired ) {
		error_log( 'woocommerce_remove_cart_item' );
		error_log( print_r( $cart_item_key, true ) );
		error_log( print_r( $cart, true ) );
	},
	10,
	2
);
add_action(
	'woocommerce_cart_item_removed',
	function ( $cart_item_key, $cart ) use ( &$hooks_fired ) {
		error_log( 'woocommerce_removed_cart_item' );
		error_log( print_r( $cart_item_key, true ) );
		error_log( print_r( $cart, true ) );
	},
	10,
	2
);
```

1. Add the above snippet to your site
2. Set up a classic cart page and block
3. Note that `removed_cart_contents` does not exist in your session at the top of the screen
4. On your classic cart, add an item to the cart
5. Remove the item from the cart
6. Note that `removed_cart_contents` exists in the ssion
7. Click the "Undo?" option in the notice
8. Make sure the item is restored to the cart
9. Remove the item from the cart
10. Refresh the page twice (once to remove the session data and another to see it reflected in the snippet after it was remvoed)
11. Note that `removed_cart_contents` has been removed from the session
12. Check your error logs and make sure that the appropriate hooks are still firing and show the correct data
13. Optionally, test with some plugins that make use of the removed_cart_contents getters, setters, hooks, or attempt to modify session.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce/includes/class-wc-cart-session.php [hunk 1]
```diff
@@ -706,4 +714,81 @@ private function cart_has_shippable_products() {
 		}
 		return false;
 	}
+
+	/**
+	 * Get removed cart contents with time-based expiration (5 minutes).
+	 *
+	 * @return array Processed removed cart contents.
+	 */
+	private function get_processed_removed_cart_contents() {
```
Comment (joshuatf) [inline plugins/woocommerce/includes/class-wc-cart-session.php]: Note that this is unnecessary if we keep `clean_up_removed_cart_contents`, but leaving this in for comparison for now.

I'll remove this if we agree that `clean_up_removed_cart_contents` is safe enough.

File: plugins/woocommerce/includes/class-wc-cart-session.php [hunk 2]
```diff
@@ -706,4 +714,81 @@ private function cart_has_shippable_products() {
...
+
+		return $processed_contents;
+	}
+
+	/**
+	 * Removes items from the removed cart contents on next user initiatedrequest.
+	 *
+	 * @return bool True if expired items should be removed, false otherwise.
+	 */
+	public function clean_up_removed_cart_contents() {
```
Comment (joshuatf) [inline plugins/woocommerce/includes/class-wc-cart-session.php:717]: Also noting that I'll add some tests here pending the approach we choose.

Comment (prettyboymp) [reply plugins/woocommerce/includes/class-wc-cart-session.php:717]: I was hopeful this would be good enough, but after some testing, there are still some issues.  

I was wrong about `template_redirect`.  Looks like it gets loaded for other requests as well, e.g. the fav-icon, feeds, etc.

I think the `template_include` filter would be a good alternative, but it also seems to get fired for 404s, which would mean it fires anytime an extension may reference a static file that doesn't exist.  E.g. a .js or .css file it doesn't properly include.  Sadly a common scenario.  So we'll also need a check for `is_404()`

File: plugins/woocommerce/includes/class-wc-cart-session.php [hunk 3]
```diff
@@ -706,4 +714,81 @@ private function cart_has_shippable_products() {
...
+				$item['removed_timestamp'] = $current_time;
+			}
+			$processed_contents[ $key ] = $item;
+		}
+
+		return $processed_contents;
+	}
+
+	/**
+	 * Removes items from the removed cart contents on next user initiatedrequest.
```
Comment (ralucaStan) [inline plugins/woocommerce/includes/class-wc-cart-session.php]:
```suggestion
	 * Removes items from the removed cart contents on next user initiated request.
```

File: plugins/woocommerce/includes/class-wc-cart-session.php (hunk 1 above)
Comment (ralucaStan) [reply plugins/woocommerce/includes/class-wc-cart-session.php]: `clean_up_removed_cart_contents` seems to be the most straightforward way to reach the goal of this PR. The `get_processed_removed_cart_contents` brings extra complexity, and probably some regressions for consumers of `removed_cart_contents`. It the goal is performance and not session management of removed items, then I'd drop get_processed_removed_cart_contents

**Review by ralucaStan — COMMENTED** [review]
I left my comment, I see there was already a comment about `template_redirect` and when it fires, but outside of that, I've shared my 2 cents about going with the `clean_up_removed_cart_contents` route. 

I also recommend getting someone from Bundles to test this PR, I am not aware what the issue was there. 

I'll be away at a meetup, so feel free to reassign if you need another review from Rubik.

File: plugins/woocommerce/includes/class-wc-cart-session.php (hunk 2 above)
Comment (joshuatf) [reply plugins/woocommerce/includes/class-wc-cart-session.php:717]: Discussed over Slack, but adding here for visibility: `template_include` created pseudo race conditions with contents being removed and added back to the session.

I kept `template_redirect` but made it more robust by adding checks for 404 and general page requests.

File: plugins/woocommerce/includes/class-wc-cart-session.php [hunk 4]
```diff
@@ -706,4 +708,25 @@ private function cart_has_shippable_products() {
...
 	}
+
+	/**
+	 * Removes items from the removed cart contents on next user initiated request.
+	 *
+	 * @return bool True if expired items should be removed, false otherwise.
+	 */
+	public function clean_up_removed_cart_contents() {
+		// Limit to page requests initiated by the user.
+		$is_page = is_singular() || is_archive() || is_search();
```
Comment (joshuatf) [inline plugins/woocommerce/includes/class-wc-cart-session.php:719]: This might not be comprehensive and we can add more if we find them, but worked well in my testing.

There's a possibility it does not always get triggered, but not removing it is safer and the clean up will still happen on next page load, so this is relatively safe AFAIK.

**Review by prettyboymp — APPROVED** [review]
I think this works well enough without getting too aggressive that we have conflicts.  👍
