### PR TITLE
REST API - Allow remove product category image

### LINKED ISSUE #12119: Rest API: Product Category Images cannot be deleted
We cannot delete product Category Images over the Rest API.

Post empty 'image' will not work and set image['id'] = 0 also not work.

### PR DESCRIPTION
**Pull request by claudiosanches**
Closes #12119

### CODE REVIEW

**Comment by justinshreve** [comment]
LGTM.

File: includes/api/class-wc-rest-product-categories-controller.php [hunk 1]
```diff
@@ -126,7 +126,7 @@ protected function update_term_meta_fields( $term, $request ) {
 
 				$image_id = wc_rest_set_uploaded_image_as_attachment( $upload );
 			} else {
-				$image_id = absint( $request['image']['id'] );
+				$image_id = isset( $request['image']['id'] ) ? absint( $request['image']['id'] ) : 0;
```
Comment (danielhuesken) [inline includes/api/class-wc-rest-product-categories-controller.php]: @claudiosanches $image_id with 0 will not pass the next if statement. And than the id will not be updated/deleted.

Comment (claudiosanches) [inline includes/api/class-wc-rest-product-categories-controller.php]: In this way you can pass `"image": []` or `"image": ["id": 0]` and will work for both.
