### PR TITLE
Variations: fix minor UI issue

### LINKED ISSUE #58442: minor ui issue in woocommerce 9.9.0 Beta rc1
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Hi,

In the product variable details section, the fields are broken.

Image

### Expected behavior

-

### Actual behavior

-

### Steps to reproduce

1. In variable products, the problem will be clear by opening the details section.

- Visit `wp-admin/admin.php?page=wc-settings&tab=advanced&section=features`
- Enable `Cost of Goods Sold`
- Create a variable product and enter some variations
- In one of the variations, check `Manage stock`

| Just COGS | With Manage stock |
|--------|--------|
| Image  |  Image | 

### WordPress Environment

<details>

<summary>WordPress Environment</summary>

<details><summary>System Status Report</summary>

```
### WordPress Environment ###

WordPress address (URL): [Redacted]
Site address (URL): [Redacted]
WC Version: 9.9.0-rc.1
Legacy REST API Package Version: The Legacy REST API plugin is not installed on this site.
Action Scheduler Version: ✔ 3.9.2
Log Directory Writable: ✔
WP Version: 6.8.1
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.54 (Win64) OpenSSL/1.1.1q PHP/8.1.10
Server Architecture: Windows NT 10.0 AMD64
PHP Version: 8.1.10
PHP Post Max Size: 2 GB
PHP Time Limit: 36000
PHP Max Input Vars: 1000
cURL Version: 7.77.0
OpenSSL/1.1.1q

SUHOSIN Installed: –
MySQL Version: 8.0.30
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

[REDACTED]

### Post Type Counts ###

attachment: 12
e-floating-buttons: 1
elementor_library: 1
page: 9
post: 15
product: 6
product_variation: 6
revision: 186
shop_order_placehold: 1
wp_font_face: 36
wp_font_family: 12
wp_global_styles: 1
wp_navigation: 1
wp_template: 1
wp_template_part: 1

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 9.9.0-rc.1

### Inactive Plugins (1) ###

Elementor: by Elementor.com – 3.29.0

### Settings ###

Legacy API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 0
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –
Enabled Features: analytics
marketplace
order_attribution
site_visibility_badge
hpos_fts_indexes
hpos_datastore_caching
email_improvements
blueprint
custom_order_tables
cost_of_goods_sold


### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 5 KB

### WC Pages ###

Shop base: #262 - /shop/
Cart: #263 - /cart/ -  Contains the woocommerce/cart block
Checkout: #264 - /checkout/ -  Contains the woocommerce/checkout block
My account: #265 - /my-account/ -  Contains the [woocommerce_my_account] shortcode
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty-Five
Version: 1.2
Author URL: https://wordpress.org
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
Theme type: Block theme
WooCommerce Support: ❌ Not declared

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
onboarding
onboarding-tasks
pattern-toolkit-full-composability
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
printful
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page
launch-your-store
add-to-cart-with-options-stepper-layout
disable-core-profiler-fallback

Disabled Features: product-data-views
experimental-blocks
coming-soon-newsletter-template
minified-js
point-of-sale
product-pre-publish-modal
settings
async-product-editor-category-field
product-editor-template-system
use-wp-horizon
blockified-add-to-cart

Daily Cron: ✔ Next scheduled: 2025-06-01 12:36:15 +00:00
Options: ✔
Notes: 56
Onboarding: skipped

### Action Scheduler ###

Complete: 74
Oldest: 2025-05-20 20:29:00 +0000
Newest: 2025-05-31 18:38:52 +0000

Pending: 1
Oldest: 2025-06-01 08:31:45 +0000
Newest: 2025-06-01 08:31:45 +0000


### Status report information ###

Generated at: 2025-05-31 21:16:15 +00:00
```
</details>

</details>

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by roccotripaldi**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes https://linear.app/a8c/issue/WOOPLUG-4469
Closes #58442

### Screenshots or screen recordings:

| Before | After |
|--------|--------|
|  Image   | Screenshot 2025-06-11 at 2 36 41 PM | 

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Edit (or create) a product that has variations.
2. Click the "Variations" section under "Product Data", then click on one of the variations to edit.
3. Check the "Manage stock" checkbox.
4. The added stock fields should appear in a nice grid 🍏.
5. Now, visit wp-admin/admin.php?page=wc-settings&tab=advanced&section=features .
6. Enable Cost of Goods Sold
7. Repeat steps 1 - 4.

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

Fixes a bug where the variation fields for a product become misaligned when both COGS and Manage Stock is enabled.

</details>

### CODE REVIEW

**Review by PanosSynetos — CHANGES_REQUESTED** [review]
Hey @roccotripaldi - Thanks for this PR.

I took it for a spin, but I don't see it the way you do. It seems like your screenshot is with COGS disabled. Can you please verify?

### Screenshots or screen recordings:

| Mine COGS enabled | Mine COGS disabled | Yours |
|--------|--------|--------|
| image   |image   | Screenshot 2025-06-10 at 10 27 05 AM | 


### Changelog

There are two ways to create a changelog for a PR - either through the PR's description, or through command line

#### Command Line
- `pnpm --filter=@woocommerce/plugin-woocommerce changelog add`

#### PR Description

As you would have noticed, the CI failed, as it couldn't create a changelog. 
https://github.com/woocommerce/woocommerce/actions/runs/15576842836/job/43863266177?pr=58696#step:5:12

The reason was

```
Getting pull request data for PR number 58696
Task complete.
Only patch changes can have a comment. Please change the significance to patch or remove the comment
```

So, two things here

1️⃣  If indeed there's no need for a changelog entry, you've done it right - just change from minor to patch and we're good.

--or--

2️⃣  If you want a changelog to be created remove the `comment`, and add it under the `changelog entry comment` - See another PR https://github.com/woocommerce/woocommerce/pull/58131

Now that we're here, can you please make the changelog a bit more descriptive? 


Thank you!

**Comment by roccotripaldi** [comment]
Thanks for the review @PanosSynetos - I got the changelog sorted! And yep, I had previously uploaded the wrong "After" image. Now the image is correct.

File: plugins/woocommerce/includes/admin/meta-boxes/views/html-variation-admin.php [hunk 1]
```diff
@@ -236,7 +236,7 @@
 			<?php endif; ?>
 
 			<?php if ( 'yes' === get_option( 'woocommerce_manage_stock' ) ) : ?>
-				<div class="show_if_variation_manage_stock" style="display: none;">
+				<div class="show_if_variation_manage_stock" style="display: none; clear: both;">
```
Comment (PanosSynetos) [inline plugins/woocommerce/includes/admin/meta-boxes/views/html-variation-admin.php]: Judging by the rest of the file, there are classes that do what the inline `clear: both` does.

Can you give it a try with those classes instead `form-row form-row-full` ?

**Review by PanosSynetos — APPROVED** [review]
Tested and works as expected. Left a small comment, pre-approving - let me know how the classes work and we can merge this one!

🚢 🍾

File: plugins/woocommerce/includes/admin/meta-boxes/views/html-variation-admin.php (hunk 1 above)
Comment (roccotripaldi) [reply plugins/woocommerce/includes/admin/meta-boxes/views/html-variation-admin.php]: Great catch!
