### PR TITLE
wp-cli make-json and Loco Translate support for admin dashboard.

### LINKED ISSUE #35500: woocommerce-{locale}-wc-admin-app.json not being generated because of incorrect file format.
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

To generate wc-admin-app.json language file, code reads precompiled language JSON files in translations directory with the following format, woocommerce-{locale}-{MD5}.json, and then merges all the strings in to one single woocommerce-{locale}-wc-admin-app.json file.
Problem here is, code is looking for different format than what wp-cli or loco translate generates.

This is an example file downloaded automatically if selected locale has official translations.
`{
  "translation-revision-date": "2022-11-01 19:37:59+0000",
  "generator": "GlotPress/4.0.0-alpha.3",
  "domain": "messages",
  "locale_data": {
    "messages": {
      "": {
        "domain": "messages",
        "plural-forms": "nplurals=2; plural=n > 1;",
        "lang": "tr"
      },
      "Edit selected product": [
        "Seçili ürünü düzenle"
      ]
    }
  },
  "comment": {
    "reference": "packages/woocommerce-blocks/assets/js/blocks/single-product/edit/editor-block-controls.js"
  }
}`

And this is the same file generated by wp-cli make-json command.

`{
    "translation-revision-date": "2022-11-02 17:33+0300",
    "generator": "WP-CLI\/2.7.1",
    "source": "packages\/woocommerce-blocks\/assets\/js\/blocks\/single-product\/edit\/editor-block-controls.js",
    "domain": "messages",
    "locale_data": {
        "messages": {
            "": {
                "domain": "messages",
                "lang": "az",
                "plural-forms": "nplurals=2; plural=n > 1;"
            },
            "Edit selected product": [
                "Se\u00e7ili \u00fcr\u00fcn\u00fc d\u00fczenle"
            ]
        }
    }
}`

[https://github.com/woocommerce/woocommerce/blob/0f0b2d5064079429f30e52335b66c91fcf081d44/plugins/woocommerce/src/Internal/Admin/Translations.php#L96](https://github.com/woocommerce/woocommerce/blob/0f0b2d5064079429f30e52335b66c91fcf081d44/plugins/woocommerce/src/Internal/Admin/Translations.php#L96)

As you can see while the official file has the format ["comment"]["reference"] for associated file, wp-cli generates files with ["source"] format. Because of that woocommerce fails to generate woocommerce-{locale}-wc-admin-app.json file.

### Expected behavior

After saving a translation with Loco Translate or uploading compiled files from POEdit, woocommerce should generate woocommerce-{locale}-wc-admin-app.json file for that locale.

### Actual behavior

Due to mismatch in formats, Woocommerce is unable to generate that file, resulting most of admin dashboard is not being translated.

### Steps to reproduce

1- Generate a .po file from woocommerce.pot file using POEdit or Loco Translate
2- Save&compile new language.
3- Woocommerce analytics dashboard and many other places won't be translated because woocommerce-{locale}-wc-admin-app.json is not generated.

### WordPress Environment

`
### wp-core ###

version: 6.1
site_language: en_US
user_language: en_US
timezone: Africa/Abidjan
permalink: /%year%/%monthnum%/%day%/%postname%/
https_status: false
multisite: false
user_registration: 0
blog_public: 1
default_comment_status: open
environment_type: production
user_count: 1
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: C:\laragon\www\azeri
wordpress_size: 65.04 MB (68199323 bytes)
uploads_path: C:\laragon\www\azeri/wp-content/uploads
uploads_size: 291.02 KB (298009 bytes)
themes_path: C:\laragon\www\azeri/wp-content/themes
themes_size: 6.34 MB (6644043 bytes)
plugins_path: C:\laragon\www\azeri/wp-content/plugins
plugins_size: 30.41 MB (31886329 bytes)
database_size: 5.30 MB (5554176 bytes)
total_size: 107.37 MB (112581880 bytes)

### wp-active-theme ###

name: Twenty Twenty-Two (twentytwentytwo)
version: 1.3
author: the WordPress team
author_website: https://wordpress.org/
parent_theme: none
theme_features: core-block-patterns, wc-product-gallery-zoom, wc-product-gallery-lightbox, wc-product-gallery-slider, woocommerce, post-thumbnails, responsive-embeds, editor-styles, html5, automatic-feed-links, block-templates, widgets-block-editor, wp-block-styles, editor-style
theme_path: C:\laragon\www\azeri/wp-content/themes/twentytwentytwo
auto_update: Disabled

### wp-plugins-active (2) ###

Loco Translate: version: 2.6.3, author: Tim Whitlock, Auto-updates disabled
WooCommerce: version: 7.0.1, author: Automattic, Auto-updates disabled

### wp-plugins-inactive (2) ###

Akismet Anti-Spam: version: 5.0.1, author: Automattic, Auto-updates disabled
Hello Dolly: version: 1.7.2, author: Matt Mullenweg, Auto-updates disabled

### wp-media ###

image_editor: WP_Image_Editor_GD
imagick_module_version: Not available
imagemagick_version: Not available
imagick_version: Not available
file_uploads: File uploads is turned off
post_max_size: 2G
upload_max_filesize: 2G
max_effective_size: 2 GB
max_file_uploads: 20
gd_version: bundled (2.1.0 compatible)
gd_formats: GIF, JPEG, PNG, WebP, BMP, AVIF, XPM
ghostscript_version: not available

### wp-server ###

server_architecture: Windows NT 10.0 AMD64
httpd_software: Apache/2.4.54 (Win64) OpenSSL/1.1.1q PHP/8.1.10
php_version: 8.1.10 64bit
php_sapi: apache2handler
max_input_variables: 1000
time_limit: 36000
memory_limit: 512M
max_input_time: 60
upload_max_filesize: 2G
php_post_max_size: 2G
curl_version: 7.77.0 OpenSSL/1.1.1q
suhosin: false
imagick_availability: false
pretty_permalinks: true
htaccess_extra_rules: false

### wp-database ###

extension: mysqli
server_version: 8.0.30
client_version: mysqlnd 8.1.10
max_allowed_packet: 536870912
max_connections: 151

### wp-constants ###

WP_HOME: http://azeri.test
WP_SITEURL: http://azeri.test
WP_CONTENT_DIR: C:\laragon\www\azeri/wp-content
WP_PLUGIN_DIR: C:\laragon\www\azeri/wp-content/plugins
WP_MEMORY_LIMIT: 40M
WP_MAX_MEMORY_LIMIT: 512M
WP_DEBUG: false
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: false
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_ENVIRONMENT_TYPE: Undefined
DB_CHARSET: utf8
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable

`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by kenarsuleyman**
### All Submissions:

-   [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
-   [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
-   [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes #35500  .

- [ ] This PR is a very minor change/addition and does not require testing instructions (if checked you can ignore/remove the next section).

### How to test the changes in this Pull Request:

1. Set WordPress locale to a language that doesn't have official translations for WooCommerce (Ex. Azerbaijan).
2. Create translations for that language in Loco Translate. There are 3 possible locations for PO file, you can choose any, It's irrelevant.
*languages/plugins/woocommerce-az.po
*languages/loco/plugins/woocommerce-az.po
*plugins/woocommerce/i18n/languages/woocommerce-az.po
3. Translate couple random words and save. This will compile MO file and generate JSON files in the chosen directory with following format "woocommerce-{locale}-{MD5}.json". AKA "chunks".
4. De-Activate and Activate WooCommerce to trigger the associated action.
5. In the chosen directory, chunk files should be combined into single woocommerce-{locale}-wc-admin-app.json file.

### Short summary of bug
Due to file format difference between the official and generated chunk files, WooCommerce was unable to generate combined JSON file.

### Other information:

-   [x] Have you added an explanation of what your changes do and why you'd like us to include them?
-   [ ] Have you written new tests for your changes, as applicable?
-   [ ] Have you created a changelog file for each project being changed, ie `pnpm --filter=<project> changelog add`?

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

**Comment by Konamiman** [comment]
Hi @kenarsuleyman, thanks for your contribution. Could you please make the following adjustments to your pull request:

1. Fix the formatting issues outlined here: https://github.com/woocommerce/woocommerce/actions/runs/4075563397/jobs/7038439499, you can do so by using `phpcbf` and `phpcs` (available in `vendor/bin`).
2. Add a changelog file. You can do so by running `pnpm --filter=plugins/woocommerce run changelog add`.
3. Add more detail to the testing instructions: how are files generated and compiled with Loco Translate, and whre's the `woocommerce-{locale}-wc-admin-app.json` file supposed to be generated?

**Comment by kenarsuleyman** [comment]
@Konamiman Thanks for the clear instructions. For some reason, both `phpcbf` and `phpcs` got stuck at %98 but I manually tried to fix formatting based on the error log you showed, also added a changelog and more detailed instructions.

File: plugins/woocommerce/src/Internal/Admin/Translations.php [hunk 1]
```diff
@@ -93,11 +93,17 @@ private function get_translation_chunk_data( $lang_dir, $domain, $locale ) {
 				continue;
 			}
 
-			if ( ! isset( $chunk_data['comment']['reference'] ) ) {
+			// Support for wp-cli --make-json and Loco Translate file format.
+
+			if ( ! ( isset( $chunk_data['comment']['reference'] ) || isset( $chunk_data['source'] ) ) ) {
```
Comment (adrianduffell) [inline plugins/woocommerce/src/Internal/Admin/Translations.php]: I think it would be better extracting each parser into separate functions rather than lumping them into one. For me, the resulting nested `if` branch conditions add too much complexity to this function.

An alternative might be to have `get_translation_chunk_data`, perform heuristics on the file to detect the format, and then call the appropriate parser function for that format.

**Comment by adrianduffell** [comment]
Hi @kenarsuleyman, thanks for this PR and your contribution. I think it's valuable to fix the bug.

I'd like to better understand why the formats are different between the official and Loco Translate generated files. Is it an error / deviation in the way one of them is generating the files?

I think ideally, we should aim to have the tooling converge to provide the data in the same format, rather than adding complexity at WooCommerce's end in supporting multiple formats.

**Comment by kenarsuleyman** [comment]
> Hi @kenarsuleyman, thanks for this PR and your contribution. I think it's valuable to fix the bug.
> 
> I'd like to better understand why the formats are different between the official and Loco Translate generated files. Is it an error / deviation in the way one of them is generating the files?
> 
> I think ideally, we should aim to have the tooling converge to provide the data in the same format, rather than adding complexity at WooCommerce's end in supporting multiple formats.

About the difference, I also agree to focus on why there is a difference between files in the first place. I checked the changelog for both GlotPress(based on official files, It's generated by GlotPress) and Loco, but couldn't see any reference to this format change.

Since wp-cli and Loco has same formats and GlotPress has a different format, the problem is most likely caused by GlotPress. Do you think is it better to write a workaround like this and revert it after the underlying problem gets fixed, or try to find a way to fix the underlying issue( which I don't exactly know )?

**Comment by adrianduffell** [comment]
> Since wp-cli and Loco has same formats and GlotPress has a different format, the problem is most likely caused by GlotPress. Do you think is it better to write a workaround like this and revert it after the underlying problem gets fixed, or try to find a way to fix the underlying issue( which I don't exactly know )?

Hi @kenarsuleyman, thanks for the explanation. I think it would be good to merge this as a temporary workaround, while aiming to fix the underlying issue in the meantime. We'll want to merge it by Monday 20 Feb to land it safely in the next release.

I'll take a further look this week.

File: plugins/woocommerce/src/Internal/Admin/Translations.php (hunk 1 above)
Comment (chihsuan) [reply plugins/woocommerce/src/Internal/Admin/Translations.php]: Hi @kenarsuleyman, Would you be able to make a change as Adrian's suggestion? 🙏

Comment (kenarsuleyman) [reply plugins/woocommerce/src/Internal/Admin/Translations.php]: Hi, @chihsuan since this is only a workaround fix and will get reverted sometime in near future, I might refactor the entire function based on Adrian's suggestion. Right now I don't know how long this fix needs to stay in the codebase. If current version is not suitable for standarts to merge it, I can do it this week.

Comment (chihsuan) [reply plugins/woocommerce/src/Internal/Admin/Translations.php]: > If current version is not suitable for standarts to merge it, I can do it this week.

Hi @kenarsuleyman Yeah, I think that would be perfect, thanks!

Comment (kenarsuleyman) [reply plugins/woocommerce/src/Internal/Admin/Translations.php]: Hi @adrianduffell, I wrote separate functions to combine translation chunks after your suggestion. I agree that this made the code more readable only problem is I'm not fully happy how those separate functions ended up with. There are "duplicate looking" lines, they are not exact duplicates, just the same logic for different file formats. Unfortunately, I couldn't think of a more optimized approach.

Comment (chihsuan) [reply plugins/woocommerce/src/Internal/Admin/Translations.php]: Hi @kenarsuleyman Just saw you push a new commit, we will review it soon. 👍  Thank you!

Sorry for late notice, @adrianduffell is unavailable.

**Review by chihsuan — APPROVED** [review]
Thanks for your contribution! @kenarsuleyman LGTM and tested well. 

@moon0326 Could you also look at this when you get a chance? 🙏

**Review by Konamiman — APPROVED** [review]

**Comment by Konamiman** [comment]
LGTM so I approved, but I'll wait for @moon0326 to take a look too as requested by @chihsuan before merging. Please ping me once that happens.

**Review by adrianduffell — APPROVED** [review]
LGTM and tested well! 🚀

**Comment by adrianduffell** [comment]
Hey @Konamiman, I've reviewed this instead of @moon0326. I'll go ahead and merge now to meet the code freeze deadline.

**Comment by adrianduffell** [comment]
Thanks for the PR @kenarsuleyman !

**Comment by kenarsuleyman** [comment]
> Thanks for the PR @kenarsuleyman !

It was pleasure for me  🙌
