### PR TITLE
Fix encoded special chars in layered nav "Any %s" string.

### LINKED ISSUE #21295: " (quote) in attribute name displayed as &quot; in filter widget dropdown (select2)
**Describe the bug**
 `"` in attribute name displayed as `&quot;` in filter widget

**To Reproduce**
Create an attribute with `"` in the name.

**Expected behavior**
Quote  `"` should be displayed, not `&quot;`.

**Reason in code**
[layered_nav_dropdown uses $any_label as argument to placehold for select2](https://github.com/woocommerce/woocommerce/blob/d9b5cf7b6f859066cfb73105fb0348c29d3d8c75/includes/widgets/class-wc-widget-layered-nav.php#L296): `placeholder: '" . esc_js( $any_label ) . "',` which is usually from [`$taxonomy_label = wc_attribute_label( $taxonomy );`](https://github.com/woocommerce/woocommerce/blob/d9b5cf7b6f859066cfb73105fb0348c29d3d8c75/includes/widgets/class-wc-widget-layered-nav.php#L227), which is already HTML [escaped by wp_kses_post function in wp-core-functions.php on woocommerce_attribute_label filter](https://github.com/woocommerce/woocommerce/blob/d9b5cf7b6f859066cfb73105fb0348c29d3d8c75/includes/wc-core-functions.php#L41), causing the bug.

**Suggested fix**
Since plugins might relay on the wc_attribute_label function being used and other WooCommerce code might expect the label to be HTML escaped, I suggest to change line [296](https://github.com/woocommerce/woocommerce/blob/d9b5cf7b6f859066cfb73105fb0348c29d3d8c75/includes/widgets/class-wc-widget-layered-nav.php#L296) to `placeholder: '" . esc_js( wp_specialchars_decode( $any_label ) ) . "',` in order to somewhat reverse the escaping.

### PR DESCRIPTION
**Pull request by kloon**
### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

This PR fixes an issue with the Any %s string when using the layered nav widget where it will show the encoded special chars instead of the actual character.

Closes #21295 

### How to test the changes in this Pull Request:

1. Create a global attribute with quotes in the name.
2. Assign the attribute to a product
3. View the layered nav widget, the Any Attribute Name string should show the actual quote and not the HTML entity code.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

### Changelog entry

> Update - Fix Layered Nav Widget where special HTML entities did not display correctly in the "Any %s" string.

### CODE REVIEW

File: includes/widgets/class-wc-widget-layered-nav.php [hunk 1]
```diff
@@ -293,7 +293,7 @@ protected function layered_nav_dropdown( $terms, $taxonomy, $query_type ) {
 				if ( jQuery().selectWoo ) {
 					var wc_layered_nav_select = function() {
 						jQuery( '.dropdown_layered_nav_" . esc_js( $taxonomy_filter_name ) . "' ).selectWoo( {
-							placeholder: '" . esc_js( $any_label ) . "',
+							placeholder: '" . wp_specialchars_decode( esc_js( $any_label ), ENT_QUOTES, get_bloginfo( 'charset' ) ) . "',
```
Comment (dtugend) [inline includes/widgets/class-wc-widget-layered-nav.php]: Shouldn't this be
`placeholder: '" . esc_js( wp_specialchars_decode( $any_label, ENT_QUOTES, get_bloginfo( 'charset' ) ) ). "'`
instead?

Comment (dtugend) [reply includes/widgets/class-wc-widget-layered-nav.php]: Example attribute label I am concerned about:
`Test'.(alert('Hello World!'),' label').'`

Comment (kloon) [reply includes/widgets/class-wc-widget-layered-nav.php]: Unfortunately esc_js will convert the double quotes again, that is why I added it inside. Will do some more testing and see what I can achieve without opening it up to an XSS attack.

**Comment by kloon** [comment]
@dtugend I removed the charset but keeping the esc_js first to avoid encoding the double quotes again. I tested an XSS string and it gets escaped fine since it also gets run through wc_enqueue_js which does escaping before output.

**Comment by dtugend** [comment]
@kloon I am actually worried about something _encoded_ that passes by esc_js and then gets decoded to a single quote, causing errors at best, or an XSS.

It seems the recommended way to fix it without touching too much code is to use [wp_json_encode](https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/issues/1270#issuecomment-354455348)

**Comment by kloon** [comment]
Using wp_json_encode will still not fix it, the issue here is that esc_js runs encoding on the string again, so even if you run it through wp_json_encode esc_js will just encode it again, also you will see slashes in the dropdown before quotes.

As mentioned the current change is not susceptible to XSS due to it being passed through a check in wc_print_js that escapes the strings.

Are you able to do a XSS or cause a JS error by manipulating the string with the current code in this PR?

**Comment by dtugend** [comment]
Hi, sorry it took the long, here is the desired example (I know it's a bit mean, but it works):
Enter this as attribute label (once) and then load the dropdown filter on frontend:
`&amp;#x27+(alert(&amp;#x27Hello World!&amp;#x27),&amp;#x27&amp;#x27)+&amp;#x27`

File: includes/widgets/class-wc-widget-layered-nav.php [hunk 2]
```diff
@@ -293,7 +293,7 @@ protected function layered_nav_dropdown( $terms, $taxonomy, $query_type ) {
 				if ( jQuery().selectWoo ) {
 					var wc_layered_nav_select = function() {
 						jQuery( '.dropdown_layered_nav_" . esc_js( $taxonomy_filter_name ) . "' ).selectWoo( {
-							placeholder: '" . wp_specialchars_decode( esc_js( $any_label ), ENT_QUOTES, get_bloginfo( 'charset' ) ) . "',
+							placeholder: '" . wp_specialchars_decode( esc_js( $any_label ), ENT_QUOTES ) . "',
```
Comment (dtugend) [inline includes/widgets/class-wc-widget-layered-nav.php]: I recommend to change this to: `placeholder: " . wp_json_encode( (string)wp_specialchars_decode($any_label, ENT_QUOTES ) ) . ",`,  because example XSS for current code: `&amp;#x27+(alert(&amp;#x27Hello World!&amp;#x27),&amp;#x27&amp;#x27)+&amp;#x27`

**Review by claudiulodro — APPROVED** [review]
