### PR TITLE
Product Collection: sync with current query doesnt display the correct products in the specific category templates

### LINKED ISSUE #46201: Product Collection: "Sync with current query" doesn't display the correct products in the specific category templates
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When "Sync with current query" is used on a user-created category template, it doesn't display the correct products from the given category.

Switching from a Products (Beta) block to a Product Collection block does not resolve this. For context, the Query Loop block does not have this issue, and it correctly displays post from a given category when creating a new category-specific template.

Product Category

Post Category

### Expected behavior

Products from a given category to be displayed.

### Actual behavior

Seems to display all products.

### Steps to reproduce

1. Add some products and categories.
2. Navigate to the Site Editor and create a new template.
3. Select the Category (product_cat) template and pick a category.
4. See products not within the specified category on the template that's created.

### WordPress Environment

<details>

`
### WordPress Environment ###

WordPress address (URL): https://mortally-mystic.jurassic.ninja
Site address (URL): https://mortally-mystic.jurassic.ninja
WC Version: 8.7.0
REST API Version: ✔ 8.7.0
Action Scheduler Version: ✔ 3.7.2
Log Directory Writable: ✔
WP Version: 6.5
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 8.1.27
PHP Post Max Size: 2 GB
PHP Time Limit: 1200
PHP Max Input Vars: 6144
cURL Version: 8.4.0
OpenSSL/3.0.11

SUHOSIN Installed: –
MySQL Version: 10.6.17-MariaDB-log
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.7.0
WC Database Prefix: wp_
Total Database Size: 3.37MB
Database Data Size: 1.58MB
Database Index Size: 1.79MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_jetpack_sync_queue: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 0.31MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.11MB + Index: 0.06MB + Engine InnoDB
wp_posts: Data: 0.13MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 24
page: 8
post: 3
product: 19
product_variation: 7
revision: 10
shop_order_placehold: 4
wp_global_styles: 2
wp_navigation: 1
wp_template: 5

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (8) ###

Akismet Anti-spam: Spam Protection: by Automattic - Anti-spam Team – 5.3.2
Companion Plugin: by Osk – 1.30
Jetpack: by Automattic – 13.3-beta
WooCommerce Stripe Gateway: by WooCommerce – 8.1.0
WooCommerce Payments Dev Tools: by Automattic –
WooPayments: by Automattic – 7.4.0
WooCommerce: by Automattic – 8.7.0
WP Rollback: by WP Rollback – 2.0.6

### Inactive Plugins (1) ###

Gutenberg: by Gutenberg Team – 18.0.0

### Dropin Plugins () ###

advanced-cache.php: advanced-cache.php
object-cache.php: Memcached

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to Woo.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 462 KB

### WC Pages ###

Shop base: #5 - /shop/
Cart: #6 - /cart/
Checkout: #7 - /checkout/
My account: #8 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty-Four
Version: 1.1
Author URL: https://wordpress.org
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ❌ Not declared

### Templates ###

Overrides: /srv/htdocs/wp-content/plugins/woocommerce/templates/block-notices/error.php
/srv/htdocs/wp-content/plugins/woocommerce/templates/block-notices/notice.php
/srv/htdocs/wp-content/plugins/woocommerce/templates/block-notices/success.php

### WooPayments ###

Version: 7.4.0
Connected to WPCOM: Yes
WPCOM Blog ID: 231531225
Account ID: acct_1P1GnFFj90jxspIy
Payment Gateway: Enabled
Test Mode: Enabled
Enabled APMs: card
WooPay: Enabled (product,cart,checkout)
WooPay Incompatible Extensions: No
Apple Pay / Google Pay: Enabled (product,cart,checkout)
Fraud Protection Level: basic
Multi-currency: Enabled
Public Key Encryption: Disabled
Auth and Capture: Enabled
Documents: Disabled
Logging: Enabled

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
product-virtual-downloadable
product-external-affiliate
product-grouped
product-linked
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: customize-store
minified-js
new-product-management-experience
product-pre-publish-modal
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2024-04-03 23:17:59 +00:00
Options: ✔
Notes: 67
Onboarding: skipped

### Action Scheduler ###

Complete: 37
Oldest: 2024-04-02 23:19:24 +0000
Newest: 2024-04-03 20:49:00 +0000

Failed: 4
Oldest: 2024-04-02 23:21:24 +0000
Newest: 2024-04-03 20:50:11 +0000

Pending: 1
Oldest: 2024-04-03 23:19:24 +0000
Newest: 2024-04-03 23:19:24 +0000

### Status report information ###

Generated at: 2024-04-03 21:41:05 +00:00
`

</details>

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by kmanijak**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

When user created a template for products from specific category or tag, all of the products were displayed in Editor (it worked correctly in Frontend).

This PR:
- major: makes a correct products displayed by default in Products by specific Category/Tag templates
- minor: makes "Sync with current query" option appear in Products by specific Category/Tag templates
- minor: allows removing the preview label in the Products by specific Category/Tag templates

Closes https://github.com/woocommerce/woocommerce/issues/46201

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

#### Prerequisites
1. Make sure Products by Category and Products by Tag templates in Editor are in default state
2. Go to Editor -> Templates -> WooCommerce
3. Find Products by Category and Products by Tag and reset them:

image

#### Products by specific Category

1. Go to Editor -> Templates
2. Click "Add new template"
3. Choose Products by Category (Note: the options load really slowly, you can even wait up to 30s!)
image

4. Choose some category that you know you have products assigned to
5. Choose default layout
6. **Expected:** Make sure Product Collection displays products from chosen category
7. Focus on PC and open Inspector Controls
8. **Expected** There's "Sync with current query" option and it's enabled by default
9. Repeat steps 1 - 8 for "Products by Tag" in step 3.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce-blocks/assets/js/blocks/product-collection/utils.tsx [hunk 1]
```diff
@@ -199,17 +212,18 @@ export const useSetPreviewState = ( {
...
+				__privatePreviewState: {
+					isPreview: isGenericArchiveTemplate
+						? !! attributes?.query?.inherit
+						: false,
+					previewMessage: __(
+						'Actual products will vary depending on the page being viewed.',
+						'woocommerce'
+					),
+				},
+			} );
```
Comment (kmanijak) [inline plugins/woocommerce-blocks/assets/js/blocks/product-collection/utils.tsx:234]: This change is to disable preview when the term ID is resolved later.

Basically if the preview was set to `true` and `isGenericArchiveTemplate` changed to `false`, there was no way for preview to get disabled.

Comment (imanish003) [reply plugins/woocommerce-blocks/assets/js/blocks/product-collection/utils.tsx:234]: Aha, I see. Good catch! Thanks for taking care of this edge case 🚀

File: plugins/woocommerce-blocks/assets/js/blocks/product-collection/utils.tsx [hunk 2]
```diff
@@ -64,6 +64,15 @@ const isInProductArchive = () => {
...
 		'woocommerce/woocommerce//product-search-results',
+		// Custom taxonomy templates have structure:
+		// <<THEME>>//taxonomy-product_cat-<<CATEGORY>>
+		// hence we're checking if template ID includes the middle part.
+		//
+		// That includes:
+		// - woocommerce/woocommerce//taxonomy-product_cat
+		// - woocommerce/woocommerce//taxonomy-product_tag
+		'//taxonomy-product_cat',
+		'//taxonomy-product_tag',
```
Comment (imanish003) [inline plugins/woocommerce-blocks/assets/js/blocks/product-collection/utils.tsx:73]: I believe it would be better to add `-` in the end of the template paths:
```
//taxonomy-product_cat-
//taxonomy-product_tag-
```

This way, it's more specific and less likely to have false positives.

In case you think we shouldn't add `-`, we can consider removing `woocommerce/woocommerce//taxonomy-product_cat` and `woocommerce/woocommerce//taxonomy-product_tag` from the list. Because `//taxonomy-product_cat` and `//taxonomy-product_tag` will match them as well.

File: plugins/woocommerce-blocks/assets/js/blocks/product-template/edit.tsx [hunk 3]
```diff
@@ -240,8 +235,29 @@ const ProductTemplateEdit = (
 			}
 			// If `inherit` is truthy, adjust conditionally the query to create a better preview.
 			if ( inherit ) {
-				if ( templateCategory ) {
-					query.categories = templateCategory[ 0 ]?.id;
+				const { taxonomy, slug } = parseTemplateSlug( templateSlug );
+
+				if ( taxonomy && slug ) {
+					const templateCategory = getEntityRecords(
```
Comment (imanish003) [inline plugins/woocommerce-blocks/assets/js/blocks/product-template/edit.tsx]: Nitpick: The name `templateCategory` is a bit misleading. Maybe it can be replaced with `fetchedTaxonomyTerm` OR `taxonomyTermRecord`?

File: plugins/woocommerce-blocks/assets/js/blocks/product-template/edit.tsx [hunk 4]
```diff
@@ -240,8 +235,29 @@ const ProductTemplateEdit = (
...
+							slug,
+						}
+					);
+
+					if ( templateCategory ) {
+						const taxonomyId = templateCategory[ 0 ]?.id;
+						if ( taxonomy === 'category' ) {
+							query.categories = taxonomyId;
+						} else {
+							// If taxonomy is not `category`, we expect either `product_cat` or `product_tag`
```
Comment (imanish003) [inline plugins/woocommerce-blocks/assets/js/blocks/product-template/edit.tsx:257]: I'm just curious. It will work for other custom taxonomies, too. Right? For example, Brands taxonomy. 🤔 
If yes, maybe we can update the comment to make it more generic.

File: plugins/woocommerce-blocks/assets/js/blocks/product-template/edit.tsx [hunk 5]
```diff
@@ -240,8 +235,29 @@ const ProductTemplateEdit = (
...
+							_fields: [ 'id' ],
+							slug,
+						}
+					);
+
+					if ( templateCategory ) {
+						const taxonomyId = templateCategory[ 0 ]?.id;
+						if ( taxonomy === 'category' ) {
+							query.categories = taxonomyId;
+						} else {
```
Comment (imanish003) [inline plugins/woocommerce-blocks/assets/js/blocks/product-template/edit.tsx:256]: Out of curiosity, should we even handle WordPress default categories in PC block? When that could be useful? 🤔 (Probably I am missing something here)

File: plugins/woocommerce-blocks/assets/js/blocks/product-template/utils.tsx [hunk 6]
```diff
@@ -366,3 +366,32 @@ export const useProductCollectionQueryContext = ( {
...
+	const categoryPrefix = 'category-';
+	const productCategoryPrefix = 'taxonomy-product_cat-';
+	const productTagPrefix = 'taxonomy-product_tag-';
+
+	if ( rawTemplateSlug.startsWith( categoryPrefix ) ) {
+		return {
+			taxonomy: 'category',
+			slug: rawTemplateSlug.replace( categoryPrefix, '' ),
+		};
+	}
```
Comment (imanish003) [inline plugins/woocommerce-blocks/assets/js/blocks/product-template/utils.tsx:380]: As I mentioned in another comment, if we decide not to handle WordPress default categories, we can remove this code 🙂

File: plugins/woocommerce-blocks/tests/e2e/tests/product-collection/product-collection.block_theme.spec.ts [hunk 7]
```diff
@@ -1458,6 +1458,68 @@ test.describe( 'Product Collection', () => {
 			} );
 		} );
 	}
+	test.describe( 'Editor: In taxonomies templates', () => {
```
Comment (imanish003) [inline plugins/woocommerce-blocks/tests/e2e/tests/product-collection/product-collection.block_theme.spec.ts:1461]: Thanks for adding E2E tests! 🚀

**Review by imanish003 — APPROVED** [review]
Hey Karol! I reviewed the PR and it looks good to me. I have left some comments and questions for you to consider. I would request you to take a look at them before merging the PR. As there isn't any major concern, I am pre-approving the PR. Great work! 🚀

**Test results:**
- ✅ Product Collection displays products from chosen category
- ✅ "Sync with current query" option is enabled by default

File: plugins/woocommerce-blocks/assets/js/blocks/product-collection/utils.tsx (hunk 2 above)
Comment (kmanijak) [reply plugins/woocommerce-blocks/assets/js/blocks/product-collection/utils.tsx:73]: > we can consider removing woocommerce/woocommerce//taxonomy-product_cat and woocommerce/woocommerce//taxonomy-product_tag from the list. Because //taxonomy-product_cat and //taxonomy-product_tag will match them as well.

Ah, that was my intention 😅 Thanks for catching it!

File: plugins/woocommerce-blocks/assets/js/blocks/product-template/edit.tsx (hunk 4 above)
Comment (kmanijak) [reply plugins/woocommerce-blocks/assets/js/blocks/product-template/edit.tsx:257]: I don't think it would. We do pretty explicit `templateSlug` matching hence this logic won't be fired for other taxonomies the same way it wasn't handled for WooCommerce taxonomies (category and tag).

File: plugins/woocommerce-blocks/assets/js/blocks/product-template/edit.tsx (hunk 5 above)
Comment (kmanijak) [reply plugins/woocommerce-blocks/assets/js/blocks/product-template/edit.tsx:256]: Hmm.. You may be right. It was there, taken from Query Loop so I didn't even think about that and didn't challenge it. 😅 

> should we even handle WordPress default categories in PC block? When that could be useful? 

While I can't think of any scenario this is useful, I also don't have confidence I can safely remove it. 🤔

File: plugins/woocommerce-blocks/assets/js/blocks/product-template/edit.tsx (hunk 4 above)
Comment (imanish003) [reply plugins/woocommerce-blocks/assets/js/blocks/product-template/edit.tsx:257]: Oh, I see. Thanks for clarifying that. IMO It would be great if we can handle it for other custom taxonomies too. I believe custom taxonomies will have paths like `<<THEME>>//taxonomy-<<TAXONOMY>>-<<TERM>>`; therefore, we should be able to handle them as well. 

But I am not sure if it should be part of this PR. Therefore, We can handle it later in a separate PR. What do you think? 🤔

Comment (kmanijak) [reply plugins/woocommerce-blocks/assets/js/blocks/product-template/edit.tsx:257]: Yeah, let me create an issue for that!

Comment (imanish003) [reply plugins/woocommerce-blocks/assets/js/blocks/product-template/edit.tsx:257]: Thanks Karol 🙇 🚀

Comment (kmanijak) [reply plugins/woocommerce-blocks/assets/js/blocks/product-template/edit.tsx:257]: Issue created: https://github.com/woocommerce/woocommerce/issues/50068

File: plugins/woocommerce-blocks/assets/js/blocks/product-template/edit.tsx (hunk 5 above)
Comment (kmanijak) [reply plugins/woocommerce-blocks/assets/js/blocks/product-template/edit.tsx:256]: I raised that elsewhere to confirm (p1722245694194949-slack-C02FL3X7KR6). In the meantime, I suggest proceeding with this PR and if we have consensus in the related covo, I'll create a follow-up PR to remove the `category` related code. WDYT?

Comment (kmanijak) [reply plugins/woocommerce-blocks/assets/js/blocks/product-template/edit.tsx:256]: Let's keep the code as per linked discussion.

Comment (imanish003) [reply plugins/woocommerce-blocks/assets/js/blocks/product-template/edit.tsx:256]: That sounds good to me! Thanks for raising this on Slack 🚀
