### PR TITLE
[CYS] Add missing typography settings for the Site Title block

### LINKED ISSUE #44794: [CYS] Font styles not applied correctly to the Site Title block
Steps to reproduce:

1. Go through the CYS flow.
2. In the assembler click on `Change fonts`.
3. Scroll until the footer pattern and try to apply some new font pairing.
4. Check the `Site title` block is not changing fonts with some of the pairings (Bodoni, Albert Sans, Newsreader, Cormorant, Raleway).

### PR DESCRIPTION
**Pull request by albarin**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes https://github.com/woocommerce/woocommerce/issues/44794

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Ensure the `WooCommerce Beta Tester` plugin is installed and activated (available on this monorepo).
2. Head over to `/wp-admin/tools.php?page=woocommerce-admin-test-helper` and enable `customize-store` feature flag.
3. Go to `WooCommerce > Home`, click on `Start customizing`, and finish the flow.
4. Scroll to the bottom of the page until you see the footer with the `Site title` block on the right side.
5. Click on `Choose fonts`.
6. Click on all available fonts and check the `Site Title` block changes to each one of the fonts.

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [x] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 
CYS - Add missing typography settings for the Site Title block
#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce-admin/client/customize-store/assembler-hub/sidebar/global-styles/font-pairing-variations/constants.ts [hunk 1]
```diff
@@ -225,6 +225,16 @@ export const FONT_PAIRINGS_WHEN_AI_IS_OFFLINE = [
 					},
 				},
 			},
+			blocks: {
+				'core/site-title': {
+					typography: {
+						fontFamily:
+							'var(--wp--preset--font-family--albert-sans)',
+						fontSize: 'var(--wp--preset--font-size--medium)',
+						fontStyle: 'normal',
```
Comment (gigitux) [inline plugins/woocommerce-admin/client/customize-store/assembler-hub/sidebar/global-styles/font-pairing-variations/constants.ts]: Is there a particular reason why are we adding fontStyle on this font pair? If I remember well, `normal` fontStyle should be the default one.

**Review by gigitux — APPROVED** [review]
Thanks for your fix! The PR LGTM. I just have a question about `fontStyle`. I think that we can omit it.

I'm pre-approving this PR!

File: plugins/woocommerce-admin/client/customize-store/assembler-hub/sidebar/global-styles/font-pairing-variations/constants.ts (hunk 1 above)
Comment (albarin) [reply plugins/woocommerce-admin/client/customize-store/assembler-hub/sidebar/global-styles/font-pairing-variations/constants.ts]: Good catch, removed!
