### PR TITLE
Clear global_unique_id when restoring a product with an existing global_unique_id

### LINKED ISSUE #50442: Able to create two products with the same GTIN, UPC, EAN or ISBN value through trashing and restoring.
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

The introduction of the GTIN, UPC, EAN or ISBN field in Woo 9.2 allowed us to enter a globally unique id to products. This means that no two products should have the same value, much like how SKU works. 

However, I was able to find a way to end up with two products having the exact same GTIN, UPC, EAN or ISBN by temporarily trashing a product, creating a new one with the same GTIN, UPC, EAN or ISBN, and then restoring the first product from the trash.

### Expected behavior

We're not sure yet on how to handle this scenario, but at the very least we should not end up with two products that have the same GTIN, UPC, EAN or ISBN when one of them was restored from trash. My suggestion would be to empty the GTIN, UPC, EAN or ISBN field of the product at the moment it's restored. Or maybe have an error notice saying that restoring it will cause duplicate unique id's, while at the same time preventing the restoration from proceeding.

### Actual behavior

You end up with two products that have the same GTIN, UPC, EAN or ISBN values.

### Steps to reproduce

1. Create a simple product with a GTIN, UPC, EAN or ISBN value of `012345678905`. The GTIN, UPC, EAN or ISBN field can be found in the Inventory tab of the product editor.
2. Trash that product.
3. Create another simple product that also has the same GTIN, UPC, EAN or ISBN (`012345678905`).
4. Restore the first product from trash.
5. Inspect both of their GTIN, UPC, EAN or ISBN values. You will notice that you now have two products with exactly the same GTIN, UPC, EAN or ISBN, which shouldn't be the case. We should only have 1 product that has that value.

### WordPress Environment

Reproducible in JN with Woo 9.2 beta.

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by nathanss**
…unique id

### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Clear global_unique_id when restoring a product with an existing global_unique_id

Closes #50442 .

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

(copied from original issue)

1. Create a simple product with a GTIN, UPC, EAN or ISBN value of `012345678905`. The GTIN, UPC, EAN or ISBN field can be found in the Inventory tab of the product editor.
2. Trash that product.
3. Create another simple product that also has the same GTIN, UPC, EAN or ISBN (`012345678905`).
4. Restore the first product from trash.
5.  Verify that the field was cleared on the restored product

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce/includes/class-wc-post-data.php [hunk 1]
```diff
@@ -405,13 +405,27 @@ public static function untrash_post( $id ) {
...
 	}
 
+	/**
+	 * Clear global unique id if it's not unique.
+	 *
+	 * @param mixed $id Post ID.
+	 */
+	private static function clear_global_unique_id_if_necessary( $id ) {
+		$product = wc_get_product( $id );
+		if ( ! wc_product_has_global_unique_id( $id, $product->get_global_unique_id() ) ) {
```
Comment (mattsherman) [inline plugins/woocommerce/includes/class-wc-post-data.php]: There should be a check that `$product` exists before attempting to call methods on it.

**Review by mattsherman — CHANGES_REQUESTED** [review]
Tested and works as expected.

I think that the code should be made more robust by checking that the `$product` exists before calling methods on it.

File: plugins/woocommerce/includes/class-wc-post-data.php [hunk 2]
```diff
@@ -405,13 +405,27 @@ public static function untrash_post( $id ) {
...
 	}
 
+	/**
+	 * Clear global unique id if it's not unique.
+	 *
+	 * @param mixed $id Post ID.
+	 */
+	private static function clear_global_unique_id_if_necessary( $id ) {
+		$product = wc_get_product( $id );
+		if ( $product && ! wc_product_has_global_unique_id( $id, $product->get_global_unique_id() ) ) {
```
Comment (mattsherman) [inline plugins/woocommerce/includes/class-wc-post-data.php:423]: Thanks for updating this.

**Review by mattsherman — APPROVED** [review]
Works as expected after re-testing with latest change. Nice job!
