### PR TITLE
Session handler: restore use of _table property, for consistency with other methods.

### LINKED ISSUE #28193: Regression: hard-coded database table in WC_Session_Handler
#21455 caused a regression by replacing `$this->_table` with `{$wpdb->prefix}woocommerce_sessions`.

This forces sub-classes of `WC_Session_Handler` to overwrite `save_data` if they use a different database table.

This can be fixed by reinstating `{$this->_table}` in the new code.

### PR DESCRIPTION
**Pull request by barryhughes**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

[`WC_Session_Handler`](https://github.com/woocommerce/woocommerce/blob/8.5.2/plugins/woocommerce/includes/class-wc-session-handler.php) uses its [`_table`](https://github.com/woocommerce/woocommerce/blob/8.5.2/plugins/woocommerce/includes/class-wc-session-handler.php#L55) property to store a reference to the `woocommerce_sessions` database table. 

At one point, all methods within the class used this property to refer to the table, and that meant subclasses could change the target database table quite easily. This was apparently broken by mistake in https://github.com/woocommerce/woocommerce/pull/21455, which hard-coded the table name within one method.

This change restores the use of `_table` across the class. Functionally, nothing actually changes: it just makes it easier for third parties to implement certain types of customization (and also makes things more consistent than previously).

I did not add a unit test, because the class depends on the cookies superglobal and it felt cleaner to infer it is operating successfully via our existing battery of storefront, cart and checkout E2E tests.

Closes #28193.

### How to test the changes in this Pull Request:

You should experience the same behavior with or without this change (we are verifying nothing has changed or broken, rather than looking for a difference):

1. Login as a known shopper.
2. Add an item to the cart.
3. Open a new browsing session (this could mean using a different browser, an incognito or private browsing session, or a fresh container if you use Firefox).
4. Login as the same shopper.
5. You should find the cart is populated with the same item you added in the first browsing session: this indicates that session data is continuing to work correctly with this change in place.

<div align="center">Two separate browser sessions, showing the same cart contents for the same authenticated shopper.</div>

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce/includes/class-wc-session-handler.php [hunk 1]
```diff
@@ -358,7 +358,7 @@ public function save_data( $old_session_key = 0 ) {
 
 			$wpdb->query(
 				$wpdb->prepare(
-					"INSERT INTO {$wpdb->prefix}woocommerce_sessions (`session_key`, `session_value`, `session_expiry`) VALUES (%s, %s, %d)
+					"INSERT INTO $this->_table (`session_key`, `session_value`, `session_expiry`) VALUES (%s, %s, %d)
```
Comment (barryhughes) [inline plugins/woocommerce/includes/class-wc-session-handler.php:362]:
```suggestion
					// phpcs:ignore WordPress.DB.PreparedSQL.InterpolatedNotPrepared
					"INSERT INTO $this->_table (`session_key`, `session_value`, `session_expiry`) VALUES (%s, %s, %d)
```

**Review by jorgeatorres — APPROVED** [review]
LGTM. Thank you @barryhughes!
