### PR TITLE
Fix index key length for status on wc_order_stats table

### LINKED ISSUE #60790: Admin\API\Reports\Orders\Datastore::get_all_statuses() causes full table scan.
The query in `Admin\API\Reports\Orders\Datastore::get_all_statuses()` causes full table scan when it is run. The query is looking for all the distinct values, but can't use the `status` index because the index length on the status column (191) is shorter than the status column (200).

This should be double checked, but there should be no reason for the status column to be set as `varchar(200)` when the source of the data for orders comes from either the posts or orders tables which have status column of `varchar(20)`. 

We should:

1. Update the table definition of the status column to `varchar(20)`
2. Drop the (191) from the index definition on the status
3. Switch from using a transient within `::get_all_statuses()` to normal wp_cache as the query should no longer be slow enough to warrant the use of transients.

### PR DESCRIPTION
**Pull request by joshuatf**
### Changes proposed in this Pull Request:

Our index key length was incorrectly set to `200` (or max of `191`) for the `status` column in the `wc_order_stats` table, probably either a typo or concern for longer statuses.  However, statuses are capped to 20 characters in other tables and this prevents the indexes from working.

This PR reduces the character length to 20 for that column and updates the status related methods to use WP_Cache instead of transients.
Closes #60790  .

### Performance Metrics

Previous: 0.146s
After: .0001s
Delta: 99.93% decrease
Scaled site savings: 1.46s (estimated on 1m order site, linear scale for full table scan) 

### Screenshots or screen recordings:

**Before**
Screenshot 2025-09-12 at 7 59 23 AM
**After**
Screenshot 2025-09-12 at 7 58 47 AM

Screenshot 2025-09-12 at 8 07 37 AM

#### Performance Testing

1. Create a scaled site with at least 100k orders
2. Before checking out this PR or running DB updates, query your distinct statuses: `SELECT DISTINCT status FROM wp_wc_order_stats`
3. Note the query time
4. Check out this branch and trigger DB deltas: `wp transient delete wc_installing && wp option set woocommerce_db_version 10.1.0 && wp option set woocommerce_version 10.1.0`
5. Note that the index is updating on the table
6. Run the query again `SELECT DISTINCT status FROM wp_wc_order_stats`
7. Note the improved time

#### Regression Testing

1. Install a plugin like [Query Monitor](https://wordpress.org/plugins/query-monitor/) to monitor SQL queries
2. Modify an order stats row to include an unregistered status: **`UPDATE wp_wc_order_stats SET `status` = 'wc-my-custom-status' WHERE `order_id` = '{ORDER_ID}';`
3. Navigate to the Analytics -> Settings page
4. Make sure that all settings are shown, including the newly added unregistered status
5. Install a persistent cache, like Docket Cache
6. Navigate back to the Analytics -> Settings page
7. Refresh the page
8. Make sure that this query is not run: `SELECT DISTINCT status FROM wp_wc_order_stats`

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce/includes/class-wc-install.php [hunk 1]
```diff
@@ -1946,12 +1946,12 @@ private static function get_schema() {
 	shipping_total double DEFAULT 0 NOT NULL,
 	net_total double DEFAULT 0 NOT NULL,
 	returning_customer tinyint(1) DEFAULT NULL,
-	status varchar(200) NOT NULL,
+	status varchar(20) NOT NULL,
```
Comment (kalessil) [inline plugins/woocommerce/includes/class-wc-install.php:1949]: Nice! Can we also add an update script to alter the table?

File: plugins/woocommerce/src/Admin/API/Reports/Orders/DataStore.php [hunk 2]
```diff
@@ -625,7 +625,7 @@ protected function get_order_attributions_by_order_ids( $order_ids ) {
 	public static function get_all_statuses() {
 		global $wpdb;
 
-		$statuses = get_transient( self::ORDERS_STATUSES_ALL_TRANSIENT );
+		$statuses = wp_cache_get( self::ORDERS_STATUSES_ALL_CACHE_KEY, 'woocommerce_analytics' );
```
Comment (kalessil) [inline plugins/woocommerce/src/Admin/API/Reports/Orders/DataStore.php:628]: Yay, with the main query getting faster, we can indeed ditch transient!
In the update script I mentioned, it would be nice to drop the transient as well (optional, it'll expire at some point).

File: plugins/woocommerce/src/Admin/API/Reports/Orders/DataStore.php [hunk 3]
```diff
@@ -646,14 +646,14 @@ public static function get_all_statuses() {
 	 * @internal
 	 * @param int $order_id Order ID.
 	 */
-	public static function maybe_update_order_statuses_transient( $order_id ) {
+	public static function maybe_update_order_statuses_cache( $order_id ) {
```
Comment (kalessil) [inline plugins/woocommerce/src/Admin/API/Reports/Orders/DataStore.php:645]: Given it's a callback for analytics hooks, even if it's a public method, it's very low probability that someone uses it already.

**Review by kalessil — CHANGES_REQUESTED** [review]
Love the improved version of this optimization! Leaving some code review comments to look into.

File: plugins/woocommerce/includes/class-wc-install.php (hunk 1 above)
Comment (joshuatf) [reply plugins/woocommerce/includes/class-wc-install.php:1949]: The `dbDelta` function is what handles this.  Any changes to schema automatically get applied at the new version (which should occur in the testing instructions of this PR).

Are those changes not working for you or is there an edge case where you think this doesn't get hit?

File: plugins/woocommerce/src/Admin/API/Reports/Orders/DataStore.php (hunk 3 above)
Comment (joshuatf) [reply plugins/woocommerce/src/Admin/API/Reports/Orders/DataStore.php:645]: Good callout.  I can still add back the previous method with a deprecated warning for a couple versions.

File: plugins/woocommerce/src/Admin/API/Reports/Orders/DataStore.php (hunk 2 above)
Comment (joshuatf) [reply plugins/woocommerce/src/Admin/API/Reports/Orders/DataStore.php:628]: I think it's fine to let this expire since they naturally have a TTL and the additional space usage is minor.

**Comment by joshuatf** [comment]
@kalessil I added in the deprecation warning discussed in https://github.com/woocommerce/woocommerce/pull/60896#discussion_r2344165248 but just waiting on a response from you on the other items.

**Comment by kalessil** [comment]
@joshuatf : will followup on this PR as start my day tomorrow, thanks for the nudge!

File: plugins/woocommerce/includes/class-wc-install.php (hunk 1 above)
Comment (kalessil) [reply plugins/woocommerce/includes/class-wc-install.php:1949]: Gotcha, was not aware of `dbDelta` - it's pretty convenient!
Verified: following the testing instructions and updating the version options will handle the schema update correctly.

File: plugins/woocommerce/changelog/fix-60790 [hunk 4]
```diff
@@ -0,0 +1,4 @@
+Significance: patch
+Type: fix
```
Comment (kalessil) [inline plugins/woocommerce/changelog/fix-60790]: How about tagging this change as performance?

File: plugins/woocommerce/src/Admin/API/Reports/Orders/DataStore.php [hunk 5]
```diff
@@ -645,19 +645,32 @@ public static function get_all_statuses() {
...
 
+	/**
+	 * Ensure the order status will present in `get_all_statuses` call result.
+	 *
+	 * @deprecated 10.3.0 Use maybe_update_order_statuses_cache().
+	 * @param int $order_id Order ID.
+	 * @return void
+	 */
+	public static function maybe_update_order_statuses_transient( $order_id ) {
+		wc_deprecated_function( __METHOD__, '10.3.0', __CLASS__ . '::maybe_update_order_statuses_cache()' );
```
Comment (kalessil) [inline plugins/woocommerce/src/Admin/API/Reports/Orders/DataStore.php:665]: Nit: I might be mistaken, but for the first argument, we are missing `__CLASS__ . '::'` prefix.

**Review by kalessil — APPROVED** [review]
LGTM! Leaving a couple of non-blocking nit-comments.

EDIT: I pushed 53b425ed9621071f98cf33515e2b9af36dbab3dc to polish a bit of the original caching implementation.

File: plugins/woocommerce/changelog/fix-60790 (hunk 4 above)
Comment (joshuatf) [reply plugins/woocommerce/changelog/fix-60790]: Good call!  Updated.

File: plugins/woocommerce/src/Admin/API/Reports/Orders/DataStore.php (hunk 5 above)
Comment (joshuatf) [reply plugins/woocommerce/src/Admin/API/Reports/Orders/DataStore.php:665]: `__METHOD__` will return the class::method combo, e.g. `Automattic\WooCommerce\Admin\API\Reports\Orders\DataStore::maybe_update_order_statuses_transient`
