### PR TITLE
Clear only plugin cache if WC header are not present to load with WC headers.

### LINKED ISSUE #26348: [WOOCOMMERCE 4.1.0 RC2] Update plugin notices are missing/disappear from Installed Plugins page and Updates page on WC 4.1.0 RC2
**Describe the bug**
Hi. I found this issue when I use WC 4.1.0 RC 2 version (using WC Beta Tester) 
I have plugin update notices available for several plugins and after I update to WC 4.1.0 RC 2 the plugin notices are disappear from Installed Plugins page and from Updates page (in Updates page, when I try to force check update, the plugin notices sometimes shows up there and sometimes disappear from that page)

**To Reproduce**
step to reproduce:
1. **use WC 4.0.1 or WC 4.1.9 RC1 installed**
2. make sure you have update plugin available
3. navigate to "Plugins > Installed Plugins" and notice to update plugin showing here
4. navigate to "Dashboard > Updates" and notice to update plugin showing here
5. **update to WC 4.1.0 RC 2**
6. navigate to "Dashboard > Updates" and click "Update" button to force check
7. **Issue Found:** refresh "Dashboard > Updates" page and notice to update plugin disappear from updates page
8. **Issue Found:** navigate to "Plugins > Installed Plugins" and notice to update plugin disappear from plugins page

and traced it back to the commit and it seems this might be related to this commit:
https://github.com/woocommerce/woocommerce/commit/4b454a8b3d791cf21770fb021d8ddd10080b112c

**Screenshots**
please check this screencast for more detail: http://somup.com/cYfv0RiKDG

**Expected behavior**
On WC 4.1.0 RC 2:
- when user open Installed Plugins page the notice should not disappear from installed plugins page
- and after force check update on Updates page before we update the plugin, the notice should not disappear from updates page

**Isolating the problem (mark completed items with an [x]):**
- [x] I have try using WC 4.1.0 RC 1 version and confirmed this bug occurs when I use  WooCommerce WC 4.1.0 RC 2
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
### WordPress Environment ###

WordPress address (URL): http://localhost/slmw_demo
Site address (URL): http://localhost/slmw_demo
WC Version: 4.1.0
REST API Version: ✔ 1.0.7
WC Blocks Version: ✔ 2.5.16
Action Scheduler Version: ✔ 3.1.4
WC Admin Version: ✔ 1.1.1
Log Directory Writable: ✔
WP Version: 5.4.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.37 (Win64) PHP/7.2.14
PHP Version: 7.2.14
PHP Post Max Size: 8 MB
PHP Time Limit: 120
PHP Max Input Vars: 2500
cURL Version: 7.61.1
OpenSSL/1.1.1a

SUHOSIN Installed: –
MySQL Version: 5.7.24
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.1.0
WC Database Prefix: wp_
Total Database Size: 1.08MB
Database Data Size: 0.80MB
Database Index Size: 0.28MB
wp_woocommerce_sessions: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_api_keys: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_woocommerce_order_items: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_order_itemmeta: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wp_woocommerce_tax_rates: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_acfw_loyalprog_entries: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_actionscheduler_actions: Data: 0.01MB + Index: 0.02MB + Engine MyISAM
wp_actionscheduler_claims: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_actionscheduler_groups: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_actionscheduler_logs: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wp_commentmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_comments: Data: 0.02MB + Index: 0.02MB + Engine MyISAM
wp_links: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_options: Data: 0.65MB + Index: 0.04MB + Engine MyISAM
wp_postmeta: Data: 0.04MB + Index: 0.03MB + Engine MyISAM
wp_posts: Data: 0.04MB + Index: 0.03MB + Engine MyISAM
wp_slmw_report_entries: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_termmeta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_terms: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_term_relationships: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_term_taxonomy: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_usermeta: Data: 0.01MB + Index: 0.02MB + Engine MyISAM
wp_users: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_admin_notes: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_admin_note_actions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_category_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_customer_lookup: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_download_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_order_coupon_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_order_product_lookup: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_order_stats: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_order_tax_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_product_meta_lookup: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_tax_rate_classes: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_webhooks: Data: 0.00MB + Index: 0.00MB + Engine MyISAM

### Post Type Counts ###

attachment: 10
page: 8
post: 2
product: 2
revision: 3
shop_order: 7
slmw_license: 10

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (6) ###

Advanced Coupons for WooCommerce Free: by Rymera Web Co – 1.0
Advanced Coupons for WooCommerce Premium: by Rymera Web Co – 2.0 – Installed version not tested with active version of WooCommerce 4.1.0
Easy WP SMTP: by wpecommerce
alexanderfoxc – 1.3.9.1

Software License Manager for WooCommerce: by Rymera Web Co – 1.7 – Installed version not tested with active version of WooCommerce 4.1.0
WooCommerce Beta Tester: by WooCommerce – 2.0.1 – Installed version not tested with active version of WooCommerce 4.1.0
WooCommerce: by Automattic – 4.1.0-rc.2

### Inactive Plugins (22) ###

Aelia Currency Switcher for WooCommerce: by Aelia – 4.6.9.181217 – Installed version not tested with active version of WooCommerce 4.1.0
Aelia Foundation Classes for WooCommerce: by Aelia – 2.0.8.190822 – Installed version not tested with active version of WooCommerce 4.1.0
Current Date and Time: by Tawhidur Rahman Dear – 1.0
Insert Headers and Footers: by WPBeginner – 1.4.4
Payment Gateway Based Fees and Discounts for WooCommerce: by Tyche Softwares – 2.6 – Installed version not tested with active version of WooCommerce 4.1.0
Query Monitor: by John Blackbourn – 3.4.0
Query Monitor: WC Session Inspector: by gamaup – 1.0
TNT Express Australia WooCommerce: by Alex Kebbell – 1.0 – Installed version not tested with active version of WooCommerce 4.1.0
Transdirect Shipping: by Transdirect – 7.0
User Role Editor: by Vladimir Garagulya – 4.52
WooCommerce Admin: by WooCommerce – 0.20.1 – Installed version not tested with active version of WooCommerce 4.1.0
WooCommerce Bookings: by WooCommerce – 1.15.1 – Installed version not tested with active version of WooCommerce 4.1.0
WooCommerce Composite Products: by SomewhereWarm – 3.13.11 – Installed version not tested with active version of WooCommerce 4.1.0
WooCommerce Memberships: by SkyVerge – 1.14.0 – Installed version not tested with active version of WooCommerce 4.1.0
WooCommerce Product Add-ons: by WooCommerce – 3.0.11 – Installed version not tested with active version of WooCommerce 4.1.0
WooCommerce Product Bundles: by SomewhereWarm – 5.7.11 – Installed version not tested with active version of WooCommerce 4.1.0
WooCommerce UPS Shipping: by WooThemes – 3.1.3 – Installed version not tested with active version of WooCommerce 4.1.0
WooCommerce Wholesale Prices: by Rymera Web Co – 1.10 – Installed version not tested with active version of WooCommerce 4.1.0
WooCommerce Wholesale Prices Premium: by Rymera Web Co – 1.23.5 – Installed version not tested with active version of WooCommerce 4.1.0
WP Crontrol: by John Blackbourn & crontributors – 1.7.1
WP Monolog: by RPP – 0.3
WP Server Date Time: by Dhruwal Patel – 0.5

### Dropin Plugins (1) ###

db.php: Query Monitor Database Class

### Settings ###

API Enabled: –
Force SSL: –
Currency: AUD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #6 - /shop/
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 2.5.3 (update to version 2.5.5 is available)
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 31
Oldest: 2020-04-22 06:23:58 +0000
Newest: 2020-04-30 23:50:16 +0000
</details>

### PR DESCRIPTION
**Pull request by vedanshujain**
### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

WC headers are added in filter `extra_plugin_headers`, however, in case when WooCommerce is activated/updated, `get_plugins` will be called and cache will be set before this filter can be cached.

Earlier we were also clearing the update cache, which was causing issue with showing update notices (see #26348), this only clears the plugin cache.

Also, `get_plugins` call is expensive even with an update cache present, because it does many I/O calls, so we should clear the cache very conservatively.

Closes #26348.

### How to test the changes in this Pull Request:

1. Install an outdated plugin ([example](https://downloads.wordpress.org/plugin/akismet.4.1.zip)) (you can download the previous version of a plugin from WordPress.org > Plugin page > Advanced view ).
2. Update to WooCommerce 4.1 RC2 from any older WooCommerce version
3. Make sure that update prompt for your outdated plugin is still displayed.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Fix - Clear only plugin cache after check if headers are not present.

### CODE REVIEW

**Comment by vedanshujain** [comment]
Note: We introduced the original change in #26358.

File: tests/php/includes/admin/helper/class-tests-wc-helper.php [hunk 1]
```diff
@@ -0,0 +1,33 @@
...
+/**
+ * Class WC_Tests_WC_Helper file.
+ *
+ * @package WooCommerce|Tests|WC_Helper.
+ */
+
+/**
+ * Class WC_Tests_WC_Helper.
+ */
+class WC_Tests_WC_Helper extends WC_Unit_Test_Case {
```
Comment (ObliviousHarmony) [inline tests/php/includes/admin/helper/class-tests-wc-helper.php:11]: Since this is a test for legacy code in the `includes` directory, this test actually belongs in the `legacy` test directory!

File: tests/legacy/bootstrap.php [hunk 2]
```diff
@@ -44,6 +44,15 @@ public function __construct() {
...
 		$this->wp_tests_dir = getenv( 'WP_TESTS_DIR' ) ? getenv( 'WP_TESTS_DIR' ) : sys_get_temp_dir() . '/wordpress-tests-lib';
 
+		if ( ! defined( 'WP_PLUGIN_DIR' ) ) {
+			define( 'WP_PLUGIN_DIR', $this->plugin_dir );
+		}
+
+		if ( file_exists( WP_PLUGIN_DIR . '/sample-woo-plugin.php' ) ) {
+			unlink( WP_PLUGIN_DIR . '/sample-woo-plugin.php' );
+		}
+		copy( __DIR__ . '/data/sample-woo-plugin.php', WP_PLUGIN_DIR . '/sample-woo-plugin.php' );
```
Comment (ObliviousHarmony) [inline tests/legacy/bootstrap.php:54]: How would you feel about doing this in the test's `setUp` and `tearDown` instead? This isn't something every test needs. I recognize this is likely done in a tmp directory, but it doesn't HAVE to!

File: sample-woo-plugin.php [hunk 3]
```diff
@@ -0,0 +1,6 @@
+<?php // phpcs:ignoreFile
```
Comment (ObliviousHarmony) [inline sample-woo-plugin.php]: Accidentally added by a previous `copy` iteration?

File: includes/admin/helper/class-wc-helper.php [hunk 4]
```diff
@@ -1149,9 +1149,19 @@ public static function get_local_woo_plugins() {
...
-		wp_clean_plugins_cache();
-		$plugins     = get_plugins();
+		$plugins = get_plugins();
+
+		/**
+		 * Check if plugins have WC headers, if not then clear cache and fetch again.
+		 * WC Headers will not be present if `wc_enable_wc_plugin_headers` hook was added after a `get_plugins` call -- for example when WC is activated/updated.
+		 * Also, get_plugins call is expensive so we should clear this cache very conservatively.
+		 */
+		$first_plugin = array_keys( $plugins )[0];
```
Comment (denho) [inline includes/admin/helper/class-wc-helper.php:1159]: It could be worth adding a check if `$plugins` is not empty.

**Review by denho — APPROVED** [review]
Thanks, @vedanshujain. LGTM, approved!

File: includes/admin/helper/class-wc-helper.php (hunk 4 above)
Comment (ObliviousHarmony) [inline includes/admin/helper/class-wc-helper.php:1159]: I think we can simplify this a bit since we can be sure that the `$plugins` array is never empty. What do you think of something like `if ( ! array_key_exists( 'Woo', reset( $plugins ) ) ) {`?

**Review by ObliviousHarmony — CHANGES_REQUESTED** [review]
I'm a big fan of the caching being done to minimize the directory scanning! There's just a few comments!

File: includes/admin/helper/class-wc-helper.php (hunk 4 above)
Comment (vedanshujain) [reply includes/admin/helper/class-wc-helper.php:1159]: I am hoping that `$plugins` will at least contain WooCommerce. Is there an edge case where this won't happen?

Comment (vedanshujain) [reply includes/admin/helper/class-wc-helper.php]: Agreed, added in https://github.com/woocommerce/woocommerce/pull/26358/commits/fd6c5f34ce9d58577319446f1ae7f47cc0df47ff.

File: sample-woo-plugin.php (hunk 3 above)
Comment (vedanshujain) [reply sample-woo-plugin.php]: Yup, removed now in https://github.com/woocommerce/woocommerce/pull/26358/commits/28fd8850fa84b42d38d116e7aed35c9d0d537322

File: tests/legacy/bootstrap.php (hunk 2 above)
Comment (vedanshujain) [reply tests/legacy/bootstrap.php]: Makes sense, I have moved this logic to test's body instead of setUp though because not all tests will use this boilerplate. Ref: https://github.com/woocommerce/woocommerce/pull/26358/commits/f4e169f21e2c4bee3c17c0160ac2b1b4cc21cff5

**Review by ObliviousHarmony — APPROVED** [review]
Noting that I'm approving the code changes, but the test file location will need examined next week!

**Comment by vedanshujain** [comment]
@ObliviousHarmony I have made some more changes -- I have renamed file and class name to resemble PSR4. Also, since we actually are not enforcing PSR4 in tests/php folder, I have not changed the file location because searching/adding tests in the legacy folder was pretty un-intuitive. 

We can add tests for files in `src` directory in `tests/php/src` folder. Let me know what you think?

**Comment by ObliviousHarmony** [comment]
Sorry for letting this slip @vedanshujain! I think this is a great balance. Let's also go ahead and change the PSR-4 namespace to the `tests/php/src` folder you've mentioned, and then that should be great!

**Comment by vedanshujain** [comment]
@ObliviousHarmony Make sense. I am merging this PR then and starting another PR so that we have separation of scope and we can include this PR in 4.2 milestones.

**Comment by vedanshujain** [comment]
@ObliviousHarmony Added new PR, which right now contains changes only for readme.md. I don't think any other changes are necessary. Let me know if you have something more in mind: https://github.com/woocommerce/woocommerce/pull/26451.

**Comment by vedanshujain** [comment]
Also, removing change log label because it was already added in 4.1
