### PR TITLE
When setting props, exclude deprecated ones

### LINKED ISSUE #13928: Notice: WC_Customer::set_city is deprecated produced for spurious user meta data
## EXPLANATION OF THE ISSUE
```
Notice: WC_Customer::set_city is deprecated since version 3.0! 
Use WC_Customer::set_billing_city instead. in wp-includes\functions.php on line 3829

Notice: WC_Customer::set_country is deprecated since version 3.0! 
Use WC_Customer::set_billing_country instead. in wp-includes\functions.php on line 3829
```

* In my development machine I have used many plugins which have set values in wp_usermeta.
* During init processing, WooCommerce discovers values which it thinks may be important and attempts to create the WC_Customer from them.
* Amongst the fields which are stored are 'city' and 'country'.
* When it tries to add these fields to the WC_Customer object deprecated notices are issued.
* In my opinion, it doesn't matter which plugin created the fields.
* WooCommerce 3.0 shouldn't be issuing a Notice when incorrectly assuming they are the values for billing_city and billing_country. 

Stack trace:

0. bw_lazy_backtrace oik-lib\libs\bwtrace.php:108 0
1. bw_backtrace oik-bwtrace\includes\bwtrace-actions.php:170 0
2. bw_trace_deprecated_function_run(WC_Customer::set_city,WC_Customer::set_billing_city,3.0) \wp-includes\class-wp-hook.php:298 3
3. apply_filters(,array) \wp-includes\class-wp-hook.php:323 2
4. do_action(array) \wp-includes\plugin.php:453 1
5. do_action(deprecated_function_run,WC_Customer::set_city,WC_Customer::set_billing_city,3.0) \wp-includes\functions.php:3816 4
6. _deprecated_function(WC_Customer::set_city,3.0,WC_Customer::set_billing_city) woocommerce\includes\wc-deprecated-functions.php:48 3
7. wc_deprecated_function(WC_Customer::set_city,3.0,WC_Customer::set_billing_city) woocommerce\includes\legacy\class-wc-legacy-customer.php:235 3
8. set_city(Rowland's Castle) woocommerce\includes\abstracts\abstract-wc-data.php:537 1
9. set_props(array) woocommerce\includes\data-stores\class-wc-customer-data-store.php:138 1
10. read(object) woocommerce\includes\class-wc-data-store.php:143 1
11. read(object) woocommerce\includes\class-wc-customer.php:104 1
12. __construct(1,1) woocommerce\woocommerce.php:439 2
13. init() wp-includes\class-wp-hook.php:298 1
14. apply_filters(unsupported,array) wp-includes\class-wp-hook.php:323 2
15. do_action(array) wp-includes\plugin.php:453 1
16. do_action(init) wp-settings.php:449 1
17. require_once(wp-settings.php) wp-config.php:213 1
18. require_once(wp-config.php) wp-load.php:37 1
19. require_once(wp-load.php) wp-blog-header.php:13 1
20. require(wp-blog-header.php) index.php:17 1

## STEPS TO REPRODUCE THE ISSUE

1. Pick any user with WooCommerce customer data.
2. Insert wp_usermeta rows for this user with field names that have been deprecated in WooCommerce 3.0. e.g. city, country
3. Set WP_DEBUG true
4. Visit the site as that user 

Note: Whether or not the plugin that created the data in the first place is active is irrelevant. 

### Workaround. 
Remove the entries that cause a problem. 
I changed the keys by adding a suffix _breaks_woo.

## SYSTEM STATUS REPORT

```
Grab the system status report from WooCommerce > System Status and paste it here.
```
`
### WordPress Environment ###

Home URL: https://qw/wordpress
Site URL: https://qw/wordpress
WC Version: 3.1.0
Log Directory Writable: ✔
WP Version: 4.7.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: –
Language: en_US

### Server Environment ###

Server Info: Apache/2.4.18 (Win64) OpenSSL/1.0.2e PHP/7.0.7
PHP Version: 7.0.7
PHP Post Max Size: 25 MB
PHP Time Limit: 121
PHP Max Input Vars: 1000
cURL Version: 7.47.1
OpenSSL/1.0.2e

SUHOSIN Installed: –
MySQL Version: 5.6.15
Max Upload Size: 25 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.1.0
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (55) ###

allow-reinstalls: by bobbingwide – 0.0.2
Genesis Footer Widgets: by bobbingwide – 0.0.1
my-hacks: by bobbingwide – 0.0.0
oik-a2z: by bobbingwide – 0.0.5
oik-ajax: by bobbingwide – 0.0.1
oik-batch: by bobbingwide – 0.9.0
oik-wp: by bobbingwide – 0.9.0
oik batchmove: by bobbingwide – 2.4.3
oik bob bing wide shortcodes: by bobbingwide – 1.30.6
oik bwtrace: by bobbingwide – 2.1.1-alpha.20170303
oik-clone: by bobbingwide – 1.0.0-RC2
oik-cons: by bobbingwide – 0.1
oik-css: by bobbingwide – 0.8.2
oik-dates: by bobbingwide – 0.1
oik-debug-filters: by bobbingwide – 1.2.1217
oik-edd: by bobbingwide – 1.7.0
oik email signature: by bobbingwide – 1.19
oik fields: by bobbingwide – 1.40.5
oik library management: by bobbingwide – 0.0.8
oik-media: by bobbingwide – 0.0.1
oik-ms: by bobbingwide – 0.2.1
oik mshot: by bobbingwide – 0.4.0
oik-nivo-slider: by bobbingwide – 1.14.4
oik plugins server: by bobbingwide – 1.15.9
oik-popup: by bobbingwide – 0.4.0
oik-privacy-policy: by bobbingwide – 1.3.3
oik-rating: by bobbingwide – 0.3
oik-read-more: by bobbingwide – 0.2.2
oik-requests: by bobbingwide – 0.0.0-alpha.0320
oik rewrite: by bobbingwide – 1.17
oik-rwd: by bobbingwide – 0.5.2
oik shortcode help shortcodes: by bobbingwide – 1.20.5
oik shortcode and API server letter taxonomies: by bobbingwide – 0.0.1
oik shortcodes server: by bobbingwide – 1.27.9
oik-sites: by bobbingwide – 0.2
oik-squeeze: by bobbingwide – 0.7.1
oik-testimonials: by bobbingwide – 0.5.1
oik themes server: by bobbingwide – 1.2.1
oik todo list: by bobbingwide – 0.2
oik-types: by bobbingwide – 1.9.2
oik user: by bobbingwide – 0.6.0
oik Weight/Country Shipping: by bobbingwide – 1.3.4
oik-widget-cache: by bobbingwide – 0.0.1
oik window width: by bobbingwide – 0.1.1
Weight zone shipping rates shortcode: by bobbingwide – 0.0.0
oik: by bobbingwide – 3.1.4
schunter: by bobbingwide – 0.0.2
Shortcake (Shortcode UI): by Fusion Engineering and community – 0.5.0
Sneak peek: by bobbingwide – 2.11
TRAC 29608: by bobbingwide – 0.0.1
UK tides - heights and times: by bobbingwide – 1.6.3
WooCommerce: by Automattic – 3.1.0-alpha
Yoast SEO: by Team Yoast – 4.4
y z: by bobbingwide – 0.0.0
z z: by bobbingwide – 0.0.0

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### WC Pages ###

Shop base: #4376 - /shop/
Cart: #4378 - /cart/
Checkout: #332 - /checkout/
My account: ❌ Page does not contain the shortcode.

### Theme ###

Name: Genesis a2z
Version: 1.0.9
Author URL: http://www.oik-plugins.com/author/bobbingwide
Child Theme: ✔
Parent Theme Name: Genesis
Parent Theme Version: 2.4.2
Parent Theme Author URL: https://www.studiopress.com/
WooCommerce Support: ✔

### Templates ###

Overrides: –
`

### PR DESCRIPTION
**Pull request by mikejolley**
Fixes #13928

### CODE REVIEW

File: includes/data-stores/class-wc-customer-data-store.php [hunk 1]
```diff
@@ -132,7 +132,16 @@ public function read( &$customer ) {
 		}
 
 		$customer_id = $customer->get_id();
-		$customer->set_props( array_map( 'wc_flatten_meta_callback', get_user_meta( $customer_id ) ) );
+		// Load meta but exclude deprecated props.
+		$user_meta   = array_diff_key( array_map( 'wc_flatten_meta_callback', get_user_meta( $customer_id ) ), array(
```
Comment (justinshreve) [inline includes/data-stores/class-wc-customer-data-store.php]: I think it might be a bit cleaner to do something like `array_flip( array( 'country', 'state', 'postcode', 'city', 'address', 'address_2' ) )` here to help reduce the number of lines -- but the actual logic here LGTM.

**Review by emdashcodes — APPROVED** [review]
