### PR TITLE
Fix variation category restriction and limit to x uses

### LINKED ISSUE #14068: Coupons no longer honor Restrictions and Limitations
### EXPLANATION OF THE ISSUE

Coupons set up prior to 3.0 that had restrictions for which product categories they could be used on simply state that the coupon does not apply to items in cart when applied, even though it should. Changing coupon to "exclude categories" and choosing the rest of the categories results in ANY product being applied the coupon. Limitations are being ignored on these coupons, too, so customers can use the coupons over and over in a cart even if I have "1" set in each limitation field.

### STEPS TO REPRODUCE THE ISSUE

Add a coupon and restrict the category it can be used on. This will result in an error in the cart about products in the cart not matching even when they do. Remove the category and set limitations of 1/1/1 and you can actually apply the coupon to multiple items in the cart.

### SYSTEM STATUS

<details>
`
### WordPress Environment ###

Home URL: https://raiser.clothing
Site URL: https://raiser.clothing
WC Version: 3.0.0
Log Directory Writable: ✔
WP Version: 4.7.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: –
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.30
PHP Post Max Size: 8 MB
PHP Time Limit: 60
PHP Max Input Vars: 1000
cURL Version: 7.19.7
NSS/3.19.1 Basic ECC

SUHOSIN Installed: –
MySQL Version: 5.6.35
Max Upload Size: 8 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.0
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (53) ###

Affiliates Manager WooCommerce Product Specific Commission: by wp.insider
affmngr – 1.0.1

Affiliates Manager WooCommerce Coupons Integration: by wp.insider
affmngr – 1.0.2

WP Affiliate Manager: by wp.insider
wpaffiliatemgr – 2.4.3

Analytics Cat Free: by Fatcat Apps – 1.0.2
API KEY for Google Maps: by GeoDirectory – 1.1.0
Async JavaScript: by Clough I.T. Solutions – 1.17.02.06
Better WordPress Minify: by Khang Minh – 1.3.3
Cherry MediaParallax Plugin: by Cherry Team. – 1.0
Cherry Plugin: by Cherry Team. – 1.2.6
Contact Form 7: by Takayuki Miyoshi – 4.7
WooCommerce Coupon Generator: by Jeroen Sormani – 1.0.0
Favicon by RealFaviconGenerator: by Philippe Bernard – 1.3.10
Force Regenerate Thumbnails: by Pedro Elsner – 2.0.6
Heartbeat Control: by Jeff Matson – 1.0.3
Hide products count: by Joan Boluda – 0.5
Product Sales Report Pro for WooCommerce: by Potent Plugins – 2.0.10
Maintenance Mode Free: by ShapedPlugin – 1.2
Newsletters - WooCommerce Subscribers: by Tribulant Software – 1.0
Obfuscate Email: by Scott Reilly – 3.5.1
PayPal for WooCommerce: by Angell EYE – 1.3.3
Popup Builder PRO: by Sygnoos – 3.1.4
Post Snippets: by Johan Steen – 2.5.3
Post Types Order: by Nsp Code – 1.9.3
Printful Integration for WooCommerce: by Printful – 1.2.7
Replace Image: by Potent Plugins – 1.1.6
WooCommerce Send Emails: by Stuart O'Brien
cxThemes – 1.2

ShiftNav - Responsive Mobile Menu: by Chris Mavricos
SevenSpark – 1.5.1.1

ShortPixel Image Optimizer: by ShortPixel – 4.2.9
WC Speed Drain Repair: by WP Fix It – 1.0
Abandoned Cart Lite for WooCommerce: by Tyche Softwares – 3.6
Woocommerce Advanced Bulk Edit: by George Iron – 4.0.4
WooCommerce Advanced Notifications: by WooCommerce – 1.2.5
WooCommerce Cost of Goods: by SkyVerge – 2.3.0
WooCommerce Google Analytics Pro: by SkyVerge – 1.2.0
Booster for WooCommerce: by Algoritmika Ltd – 2.6.0
WooCommerce Quantity Increment: by Automattic
WooThemes – 1.1.0

WooCommerce: by Automattic – 3.0.0
WooCommerce Helper: by WooCommerce – 1.7.2 – Network enabled
Yoast SEO Premium: by Team Yoast – 4.4
WP Asset CleanUp: by Gabriel Livan – 1.2.4.3
WP-Cron Control: by Thorsten Ott
Erick Hitter
Automattic – 0.7.1

WP Crontrol: by John Blackbourn & contributors – 1.5
wp Hosting Performance Check: by Scott Farrell – 2.14.15
Mail Bank Business Edition: by Tech Banker – 2.1.16
Newsletters: by Tribulant Software – 4.6.5.4
WP-Optimize: by David Anderson
Ruhani Rabin
Team Updraft – 2.1.1

WP Product Feed Manager: by Michel Jongbloed – 1.4.3
WP Super Cache: by Automattic – 1.4.9
YITH Essential Kit for WooCommerce #1: by YIThemes – 1.4.3
YITH WooCommerce Badge Management Premium: by YITHEMES – 1.3.0
YITH WooCommerce Color and Label Variations Premium: by YITHEMES – 1.3.0
YITH WooCommerce Review Reminder Premium: by YITHEMES – 1.3.0
YITH WooCommerce Surveys Premium: by YITHEMES – 1.0.8

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### WC Pages ###

Shop base: #1914 - /store/
Cart: #1915 - /cart/
Checkout: #1916 - /checkout/
My account: #1917 - /my-account/

### Theme ###

Name: theme52383
Version: 3.1
Author URL: http://info.template-help.com/help/
Child Theme: ✔
Parent Theme Name: cherry
Parent Theme Version: 3.1.5.1
Parent Theme Author URL: //info.template-help.com/help/
WooCommerce Support: ✔

### Templates ###

Overrides: theme52383/woocommerce/checkout/thankyou.php
theme52383/woocommerce/emails/customer-completed-order.php

`
</details>

### PR DESCRIPTION
**Pull request by mikejolley**
Fixes #14068

### CODE REVIEW

File: includes/data-stores/class-wc-coupon-data-store-cpt.php [hunk 1]
```diff
@@ -105,7 +105,7 @@ public function read( &$coupon ) {
 			'excluded_product_ids'        => array_filter( (array) explode( ',', get_post_meta( $coupon_id, 'exclude_product_ids', true ) ) ),
 			'usage_limit'                 => get_post_meta( $coupon_id, 'usage_limit', true ),
 			'usage_limit_per_user'        => get_post_meta( $coupon_id, 'usage_limit_per_user', true ),
-			'limit_usage_to_x_items'      => get_post_meta( $coupon_id, 'limit_usage_to_x_items', true ),
+			'limit_usage_to_x_items'      => 0 < get_post_meta( $coupon_id, 'limit_usage_to_x_items', true ) ? get_post_meta( $coupon_id, 'limit_usage_to_x_items', true ) : null,
```
Comment (claudiulodro) [inline includes/data-stores/class-wc-coupon-data-store-cpt.php]: What about the case where x is 0? Then limit gets set to null default (unlimited). I don't know if that will cause any problems.

Comment (mikejolley) [inline includes/data-stores/class-wc-coupon-data-store-cpt.php]: 0 is not valid - 0 would mean the coupon cannot apply to any items.

Comment (claudiulodro) [inline includes/data-stores/class-wc-coupon-data-store-cpt.php]: That's what I figured, but I didn't know whether we wanted to allow users to make coupons like that. :)

Good to go!
