### PR TITLE
Transactions, caching, and version transient cleanup issues

### LINKED ISSUE #17660: Orders overwriting when placed at same time
It seems as though when two customers place an order (complete checkout) at the same time (or very close together) all of the items in one of the orders are added into the other. This leaves one order with no items and another order with too many items. The totals, tax and shipping however all remain in tact. It's consistently always the adjcent order which accrues all of the items. For example:

Order 001 & 002 are placed at 12:00am

Customer A placed order 001 for product A at £10
Customer B placed order 002 for product B at £20

Upon checkout completion of both orders, the following is saved in the database:

Customer A's order 001 has no products at £10
Customer B's order 002 has product A & product B at £20 << always the adjacent order number

Our store is hosted on AWS. I'm using a load balanced elastic beanstalk with at least two servers at any time. Along with an RDS instance. Our average load is between 200 and 400 users with peak load being around 1000 users.

I have not been able to reproduce the issue in a non production environment to understand exactly why it happens. 

Is it possible that when an order item is saved in the 'woocommerce_order_items' table the wrong order ID is used?

System status dump: 

<details>
`
### WordPress Environment ###

Home URL: https://www.alpha.mous.co
Site URL: https://www.alpha.mous.co
WC Version: 3.2.3
Log Directory Writable: ✔
WP Version: 4.8.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 7.0.21
PHP Post Max Size: 32 MB
PHP Time Limit: 600
PHP Max Input Vars: 1000
cURL Version: 7.51.0
NSS/3.28.4

SUHOSIN Installed: –
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.2.3
WC Database Prefix: mous_
MaxMind GeoIP Database: ✔
Total Database Size: 726.91MB
Database Data Size: 433.48MB
Database Index Size: 293.43MB
mous_woocommerce_sessions: Data: 23.59MB + Index: 1.52MB
mous_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
mous_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
mous_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
mous_woocommerce_order_items: Data: 7.52MB + Index: 3.52MB
mous_woocommerce_order_itemmeta: Data: 58.59MB + Index: 63.17MB
mous_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
mous_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
mous_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
mous_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
mous_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
mous_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
mous_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
mous_woocommerce_log: Data: 0.02MB + Index: 0.02MB
mous_aelia_dismissed_messages: Data: 0.02MB + Index: 0.00MB
mous_commentmeta: Data: 1.52MB + Index: 0.72MB
mous_comments: Data: 19.55MB + Index: 16.09MB
mous_links: Data: 0.02MB + Index: 0.02MB
mous_options: Data: 2.47MB + Index: 1.52MB
mous_pmlca_links: Data: 0.02MB + Index: 0.02MB
mous_pmxe_exports: Data: 1.52MB + Index: 0.00MB
mous_pmxe_google_cats: Data: 0.39MB + Index: 0.00MB
mous_pmxe_posts: Data: 5.52MB + Index: 0.00MB
mous_pmxe_templates: Data: 0.09MB + Index: 0.00MB
mous_pmxi_files: Data: 0.02MB + Index: 0.00MB
mous_pmxi_history: Data: 0.02MB + Index: 0.00MB
mous_pmxi_imports: Data: 0.14MB + Index: 0.00MB
mous_pmxi_posts: Data: 6.52MB + Index: 0.00MB
mous_pmxi_templates: Data: 0.02MB + Index: 0.00MB
mous_postmeta: Data: 147.70MB + Index: 165.44MB
mous_posts: Data: 58.59MB + Index: 34.19MB
mous_redirection_404: Data: 1.52MB + Index: 1.05MB
mous_redirection_groups: Data: 0.02MB + Index: 0.03MB
mous_redirection_items: Data: 0.02MB + Index: 0.08MB
mous_redirection_logs: Data: 3.52MB + Index: 0.91MB
mous_social_users: Data: 0.02MB + Index: 0.02MB
mous_termmeta: Data: 0.02MB + Index: 0.03MB
mous_terms: Data: 0.02MB + Index: 0.03MB
mous_term_relationships: Data: 7.52MB + Index: 4.52MB
mous_term_taxonomy: Data: 0.02MB + Index: 0.03MB
mous_usermeta: Data: 0.11MB + Index: 0.09MB
mous_users: Data: 0.02MB + Index: 0.05MB
mous_w3tc_cdn_queue: Data: 0.02MB + Index: 0.02MB
mous_wc_warranty_products: Data: 0.02MB + Index: 0.05MB
mous_woel_woocommerce_order_emails_log: Data: 86.52MB + Index: 0.00MB
mous_wpmelon_advbedit_temp: Data: 0.02MB + Index: 0.00MB
mous_yoast_seo_links: Data: 0.02MB + Index: 0.02MB
mous_yoast_seo_meta: Data: 0.02MB + Index: 0.00MB

### Post Type Counts ###

attachment: 407
blocks: 2
custom_css: 1
klaviyo_shop_cart: 173946
nav_menu_item: 10
page: 22
post: 2
post_type: 2
product: 8
product_variation: 105
revision: 274
shop_coupon: 2065
shop_order: 30196
shop_order_refund: 636
warranty_request: 5

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (22) ###

Add From Server: by Dion Hulse – 3.3.3
Disable/Configure Plugins: by Chris Sewell – 1.0.1
WooThumbs - Awesome Product Imagery: by Iconic – 4.6.1 – Not tested with the active version of WooCommerce
WooCommerce Order Emails Log (Premium): by RaiserWeb – 2.0 – Not tested with the active version of WooCommerce
Redirection: by John Godley – 2.9.2
SSL Insecure Content Fixer: by WebAware – 2.4.0
User Role Editor: by Vladimir Garagulya – 4.37
WooCommerce Variation Swatches: by ThemeAlien – 1.0.3 – Not tested with the active version of WooCommerce
W3 Total Cache: by Frederick Townes – 0.9.5.4
Aelia Foundation Classes for WooCommerce: by Aelia – 1.8.9.170629 – Not tested with the active version of WooCommerce
WooCommerce Tree Table Rate Shipping: by tablerateshipping.com – 1.16.4 – Not tested with the active version of WooCommerce
Woocommerce Advanced Bulk Edit: by George Iron – 3.6 – Not tested with the active version of WooCommerce
Aelia Currency Switcher for WooCommerce: by Aelia – 4.4.19.170602 – Not tested with the active version of WooCommerce
WooCommerce Direct Variation Link: by WP BackOffice – 1.0.3 – Not tested with the active version of WooCommerce
WooCommerce Stripe Gateway: by WooCommerce – 3.2.3 – Not tested with the active version of WooCommerce
WooCommerce Google Analytics Pro: by SkyVerge – 1.3.4 – 1.3.5 is available – Not tested with the active version of WooCommerce
WooCommerce - ShipStation Integration: by WooCommerce – 4.1.12 – 4.1.18 is available – Not tested with the active version of WooCommerce
WooCommerce Smart Checkout: by AppPresser Team – 1.1.2 – Not tested with the active version of WooCommerce
WooCommerce Warranty Requests: by WooCommerce – 1.8.7 – Not tested with the active version of WooCommerce
WooCommerce: by Automattic – 3.2.3
WP Crontrol: by John Blackbourn & contributors – 1.5
WP SES: by Sylvain Deaure – 0.7.21

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #9 - /shop/
Cart: #10 - /basket/
Checkout: #11 - /checkout/
My account: #12 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: mous
Version: 99.0
Author URL: 
Child Theme: ✔
Parent Theme Name: Mous
Parent Theme Version: 99.0.0
Parent Theme Author URL: 
WooCommerce Support: ✔

### Templates ###

Overrides: mous_child/woocommerce/archive-product.php
mous_child/woocommerce/cart/cart-empty.php version 2.0.0 is out of date. The core version is 3.1.0
mous_child/woocommerce/cart/cart-shipping.php version 2.5.0 is out of date. The core version is 3.2.0
mous_child/woocommerce/cart/cart.php version 3.0.3 is out of date. The core version is 3.1.0
mous_child/woocommerce/cart/proceed-to-checkout-button.php
mous_child/woocommerce/checkout/form-billing.php version 3.0.0 is out of date. The core version is 3.0.9
mous_child/woocommerce/checkout/form-coupon.php
mous_child/woocommerce/checkout/form-shipping.php version 3.0.0 is out of date. The core version is 3.0.9
mous_child/woocommerce/checkout/review-order.php version - is out of date. The core version is 2.3.0
mous_child/woocommerce/checkout/thankyou.php version 3.0.0 is out of date. The core version is 3.2.0
mous_child/woocommerce/content-product.php
mous_child/woocommerce/content-product_cat.php
mous_child/woocommerce/content-single-product.php
mous_child/woocommerce/global/breadcrumb.php
mous_child/woocommerce/global/form-login.php
mous_child/woocommerce/global/quantity-input.php version 2.5.0 is out of date. The core version is 3.2.0
mous_child/woocommerce/global/wrapper-end.php
mous_child/woocommerce/global/wrapper-start.php
mous_child/woocommerce/loop/loop-end.php
mous_child/woocommerce/loop/loop-start.php
mous_child/woocommerce/loop/orderby.php
mous_child/woocommerce/loop/pagination.php
mous_child/woocommerce/loop/result-count.php
mous_child/woocommerce/loop/sale-flash.php
mous_child/woocommerce/myaccount/form-login.php version 2.6.0 is out of date. The core version is 3.2.0
mous_child/woocommerce/myaccount/navigation.php
mous_child/woocommerce/notices/error.php
mous_child/woocommerce/notices/notice.php
mous_child/woocommerce/notices/success.php
mous_child/woocommerce/product-searchform.php
mous_child/woocommerce/single-product/add-to-cart/external.php
mous_child/woocommerce/single-product/add-to-cart/grouped.php version 3.0.3 is out of date. The core version is 3.0.7
mous_child/woocommerce/single-product/add-to-cart/simple.php
mous_child/woocommerce/single-product/add-to-cart/variable.php
mous_child/woocommerce/single-product/add-to-cart/variation-add-to-cart-button.php
mous_child/woocommerce/single-product/add-to-cart/variation.php
mous_child/woocommerce/single-product/photoswipe.php
mous_child/woocommerce/single-product/price.php
mous_child/woocommerce/single-product/product-image.php version 3.0.2 is out of date. The core version is 3.1.0
mous_child/woocommerce/single-product/product-thumbnails.php version 3.0.2 is out of date. The core version is 3.1.0
mous_child/woocommerce/single-product/related.php
mous_child/woocommerce/single-product/review.php
mous_child/woocommerce/single-product/sale-flash.php
mous_child/woocommerce/single-product/share.php
mous_child/woocommerce/single-product/short-description.php
mous_child/woocommerce/single-product/tabs/tabs.php
mous_child/woocommerce/single-product/title.php
mous_child/woocommerce/single-product/up-sells.php
mous_child/woocommerce/single-product-reviews.php version 2.3.2 is out of date. The core version is 3.2.0
mous_child/woocommerce/single-product.php

Outdated Templates: ❌Learn how to update
`
</details>

### LINKED ISSUE #20528: Lock tables issues
Hi, our live website is getting following error in logs and some of orders are not converted from pending payment to processing even after successful payment from customer. Can anyone help?
Log :
WordPress database error Deadlock found when trying to get lock; try restarting transaction for query DELETE FROM wp_options WHERE option_name LIKE '\\_transient\\_%1528939471' ORDER BY option_id LIMIT 1000; made by require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), do_action('template_redirect'), WP_Hook->do_action, WP_Hook->apply_filters, WC_AJAX::do_wc_ajax, do_action('wc_ajax_checkout'), WP_Hook->do_action, WP_Hook->apply_filters, WC_AJAX::checkout, WC_Checkout->process_checkout, WC_Checkout->process_order_payment, WC_Gateway_Stripe->process_payment, WC_Stripe_Payment_Gateway->process_response, WC_Order->payment_complete, WC_Order->save, WC_Data_Store->update, WC_Order_Data_Store_CPT->update, Abstract_WC_Order_Data_Store_CPT->update, Abstract_WC_Order_Data_Store_CPT->clear_caches, wc_delete_shop_order_transients, WC_Cache_Helper::get_transient_version, WC_Cache_Helper::delete_version_transients

### PR DESCRIPTION
**Pull request by mikejolley**
3 changes here, all semi-related, which should be rolled out to prevent current conflicts.

This should also help with #17660, however we're not 100% sure as we're unable to replicate the cases in that thread.

This PR reverts some changes made in https://github.com/woocommerce/woocommerce/commit/1918e2e554ba3ea2a286786dbd3ce860e5cb3fb3 which has been causing odd issues on stores due to deadlocks, and is potentially guilty of causing double charges on woo.com (cc @kloon).

**To Test:**
- Create some test orders, ensure they go through without error. Try as a guest and logged in user.
- Ensure unit tests pass.

**Transactions**
Transactions were used so changes could be rolled back, however, it seems this is causing issue if large amounts of data are written due to all the hooks that fire. e.g. in #20528 Not using transactions could lead to partial updates, however, these are not expected and only occur if something (plugin?) causes an error. As such, _I'm confident logging will be enough for an admin to resolve._

Disabling transactions seemed to have a positive impact on woo.com, so rolling this out as a fix.

**Transient cleanup**
Related to the above and raised in #20528. I noticed cleanup runs immediately. We don't need to clean up right away and slow the current process. Deferring the event via cron will work.

**Cache ID 0**
Not confirmed, but we theorised caching for order ID 0 could be a factor in #17660. This PR simply checks to ensure there is an ID before using caching.

Closes #17660
Closes #20528

### CODE REVIEW

**Comment by claudiulodro** [comment]
[The unit tests are freaking out, man.](https://travis-ci.org/woocommerce/woocommerce/jobs/392263820)

File: includes/class-wc-cache-helper.php [hunk 1]
```diff
@@ -136,7 +136,7 @@ public static function get_transient_version( $group, $refresh = false ) {
 		$transient_value = get_transient( $transient_name );
 
 		if ( false === $transient_value || true === $refresh ) {
-			self::delete_version_transients( $transient_value );
+			self::queue_delete_version_transients( $transient_value );
```
Comment (claudiulodro) [inline includes/class-wc-cache-helper.php]: There is still [one failing unit test](https://travis-ci.org/woocommerce/woocommerce/jobs/392314671). It seems to be caused by this change, as reverting this line to instantly delete makes it pass again. 

If there is potential for this to cause issues, maybe have the deferred transaction delete only happen if a defined constant is true (e.g. `WC_DEFER_TRANSACTION_DELETE`)?

Comment (mikejolley) [reply includes/class-wc-cache-helper.php]: Tests run so quick I assume it's because `time()` is returning the same value. Thats a bug.

**Review by claudiulodro — APPROVED** [review]
Recent changes look good and all tests pass.
