### PR TITLE
Make increase_usage_count work correctly on concurrent checkout

### LINKED ISSUE #13505: Coupon usage count is incorrect
## EXPLANATION OF THE ISSUE
When multiple orders are coming in at the same time, the coupon usage doesn't update properly.

We've recently had a large promotion where hundreds of users were buying products at the same time.

We had a coupon set to expire when it was used 1000 times, however we had to manually disable it after we reached more than 1500 times. The counter was still showing 700 uses.

## STEPS TO REPRODUCE THE ISSUE

1. Create a coupon. Usage will be 0
2. Set a usage limit (optional)
3. Have multiple (>100 in our case) users placing orders at the same time (preferrably at the same second).
4. Check the coupon usage.

## Possible cause
On class WC_Coupon line 278 you've got function inc_usage_count that increases the usage_count meta field of the coupon. This function gets the current usage_count, increases it and then writes it on the SQL.

In the miliseconds between read and write, it's possible that another process will have read the same number and will update to the same number.

Process A: Reads count as 0
Process B: Reads count as 0
Process A: Increases count to 1
Process B: Increases count to 1
Process A: Writes count as 1
Process B: Writes count as 1

Total orders 2
Reported usage count 1

## Possible solution
Replace line 278 & 279 on class WC_Coupon with the following query
`UPDATE wp_postmeta
SET meta_value = meta_value + 1
WHERE
post_id = '".$this->id."'
AND meta_key = 'usage_count'`

### PR DESCRIPTION
**Pull request by claudiulodro**
Fixes #13505.

Increasing the usage count now does so using a query that works correctly if multiple people check out at the exact same time.

I've also changed some places where we were using the legacy `inc_usage_count`/`dcr_usage_count` to use the new 2.7 methods.

### CODE REVIEW

**Comment by mikejolley** [comment]
What are your thoughts on this vs https://github.com/woocommerce/woocommerce/blob/b81faa0780dcd7d0752f14935435c67f01b56109/includes/data-stores/class-wc-product-data-store-cpt.php#L1006-L1024? The code is similar, you don't need set, just increment/decrement, but it could make this more DRY.

**Comment by claudiulodro** [comment]
Good call. I like the way you propose much better. I'll switch it over.

File: includes/data-stores/class-wc-coupon-data-store-cpt.php [hunk 1]
```diff
@@ -258,6 +261,29 @@ public function decrease_usage_count( &$coupon, $used_by = '' ) {
...
+	 */
+	private function vary_usage_count_meta( &$coupon, $operation = 'increase' ) {
+		global $wpdb;
+		$id = $coupon->get_id();
+		$operator = ( 'increase' === $operation ) ? '+' : '-';
+		$new_count = ( 'increase' === $operation ) ? ( $coupon->get_usage_count( 'edit' ) + 1 ) : ( $coupon->get_usage_count( 'edit' ) - 1 );
+
+		$updated = $wpdb->query( $wpdb->prepare( "UPDATE $wpdb->postmeta SET meta_value = meta_value {$operator} 1 WHERE meta_key = 'usage_count' AND post_id = %d;", $id ) );
+		if ( ! $updated ) {
+			add_post_meta( $id, 'usage_count', $new_count, true );
```
Comment (mikejolley) [inline includes/data-stores/class-wc-coupon-data-store-cpt.php]: It may be safer to add beforehand so there is no query error if the meta does not exist?

File: includes/data-stores/class-wc-coupon-data-store-cpt.php [hunk 2]
```diff
@@ -258,6 +261,29 @@ public function decrease_usage_count( &$coupon, $used_by = '' ) {
...
+
+	/**
+	 * Increase or decrease the usage count for a coupon by 1.
+	 *
+	 * @since 2.7.0
+	 * @param WC_Coupon
+	 * @param string $operation 'increase' or 'decrease'
+	 * @return int New usage count
+	 */
+	private function vary_usage_count_meta( &$coupon, $operation = 'increase' ) {
```
Comment (mikejolley) [inline includes/data-stores/class-wc-coupon-data-store-cpt.php]: "vary_" feels odd to read. I think "update_" is fine :)

File: includes/class-wc-coupon.php [hunk 3]
```diff
@@ -721,8 +721,8 @@ public function increase_usage_count( $used_by = '' ) {
 	 */
 	public function decrease_usage_count( $used_by = '' ) {
 		if ( $this->get_id() && $this->get_usage_count() > 0 && $this->data_store ) {
-			$this->set_prop( 'usage_count', ( $this->get_usage_count( 'edit' ) - 1 ) );
-			$this->data_store->decrease_usage_count( $this, $used_by );
+			$new_count = $this->data_store->decrease_usage_count( $this, $used_by );
+			$this->set_prop( 'usage_count', $new_count );
```
Comment (mikejolley) [inline includes/class-wc-coupon.php]: May be an issue here - if this object is 'saved', won't this increment or decrement be ignored when the data-store runs the update logic? This should probably bypass set_prop and not be part of `changes`

File: includes/data-stores/class-wc-coupon-data-store-cpt.php [hunk 4]
```diff
@@ -258,6 +261,29 @@ public function decrease_usage_count( &$coupon, $used_by = '' ) {
...
+		global $wpdb;
+		$id = $coupon->get_id();
+		$operator = ( 'increase' === $operation ) ? '+' : '-';
+		$new_count = ( 'increase' === $operation ) ? ( $coupon->get_usage_count( 'edit' ) + 1 ) : ( $coupon->get_usage_count( 'edit' ) - 1 );
```
Comment (mikejolley) [inline includes/data-stores/class-wc-coupon-data-store-cpt.php]: For the reasons in https://github.com/woocommerce/woocommerce/pull/13516/files#r105386129, doing this may be wrong. We should get the updated value from the DB after write.

**Review by mikejolley — CHANGES_REQUESTED** [review]

File: includes/data-stores/class-wc-coupon-data-store-cpt.php (hunk 2 above)
Comment (claudiulodro) [inline includes/data-stores/class-wc-coupon-data-store-cpt.php]: I got it from [here](http://english.stackexchange.com/questions/55416/hypernym-for-increase-and-decrease) :) Update is good, too. I'll switch it over.

File: includes/class-wc-coupon.php (hunk 3 above)
Comment (claudiulodro) [inline includes/class-wc-coupon.php]: That makes sense. Good call.

File: includes/data-stores/class-wc-coupon-data-store-cpt.php (hunk 1 above)
Comment (claudiulodro) [inline includes/data-stores/class-wc-coupon-data-store-cpt.php]: My understanding is that it will return the number of lines updated, which would be 0 if the meta doesn't exist. I'll double check to make sure.
