### PR TITLE
Fix/Additional checkout field  select type placeholder not shown through edit account page form

### LINKED ISSUE #52110: woocommerce_register_additional_checkout_field : "select" type placeholder not shown through "edit-account" page form.
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When adding a new "select" field with woocommerce_register_additional_checkout_field, everything is okay in the checkout page. But when a user wants to change the value through its "my account" section, the placeholder is not shown. This forces the user to select an option, even though the field is not required.

### Expected behavior

Consistent behavior between two pages, i.e. display the placeholder.

### Actual behavior

Placeholder (= select none of the options) is not possible in the my-account page.

### Steps to reproduce

Fresh WP/WC install, add the following code into wp-content/themes/twentytwentyfour/functions.php:
```
add_action(
        'woocommerce_init',
        function() {
                woocommerce_register_additional_checkout_field(
                        array(
                                'id'            => 'mynamespace/number',
                                'type'          => 'select',
                                'label'         => 'Choose number',
                                'location'      => 'address',
                                'required'      => false,
                                'options'       => [
                                        [
                                                'value' => 0,
                                                'label' => "Zero"
                                        ],
                                        [ 
                                                'value' => 1,
                                                'label' => "One"
                                        ]
                                ],
                              'placeholder'   => 'Choose a number'
                        ),
                );
        }
);
```
Note 1: the same problem occurs regardless of the "required" and "placeholder" field values.
Note 2: in the my account page, if the field "location" is "contact", the value can't be changed (already reported here : #52066)

### WordPress Environment

<details><summary>System Status Report</summary>

```
### WordPress Environment ###

WordPress address (URL): [Redacted]
Site address (URL): [Redacted]
WC Version: 9.3.3
Legacy REST API Package Version: L’extension Legacy REST API n’est pas installée sur ce site.
Action Scheduler Version: ✔ 3.8.1
Log Directory Writable: ✔
WP Version: 6.6.2
WP Multisite: –
WP Memory Limit: 256 Mo
WP Debug Mode: ✔
WP Cron: ✔
Language: fr_FR
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.41 (Ubuntu)
PHP Version: 8.2.4
PHP Post Max Size: 100 Mo
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.68.0
OpenSSL/1.1.1f

SUHOSIN Installed: –
MySQL Version: 10.3.39-MariaDB-0ubuntu0.20.04.2
Max Upload Size: 100 Mo
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Votre serveur n’a pas la classe SoapClient activée - certaines extensions de passerelle utilisant SOAP peuvent ne pas fonctionner correctement.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

[REDACTED]

### Post Type Counts ###

attachment: 1
page: 7
post: 2
product: 1
revision: 2
shop_order_placehold: 1
wp_navigation: 1

### Security ###

Secure connection (HTTPS): ❌
					Votre boutique n’utilise pas HTTPS. En savoir plus sur HTTPS et les certificats SSL.
Hide errors from visitors: ❌Les messages d’erreur ne doivent pas s’afficher aux visiteurs.

### Active Plugins (1) ###

WooCommerce: par Automattic – 9.3.3

### Inactive Plugins (2) ###

Akismet Anti-spam: Spam Protection: par Automattic - Anti-spam Team – 5.3.3
Hello Dolly: par Matt Mullenweg – 1.7.2

### Settings ###

Legacy API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: 
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 jours
Level threshold: –
Log directory size: 13 o

### WC Pages ###

Base de la boutique: #7 - /index.php/boutique/
Panier: #8 - /index.php/panier/ -  Contient le bloc woocommerce/cart
Commander: #9 - /index.php/commander/ -  Contient le bloc woocommerce/checkout
Mon compte: #10 - /index.php/mon-compte/
Conditions générales de vente et d’utilisation: ❌ Page non définie

### Theme ###

Name: Twenty Twenty-Four
Version: 1.2
Author URL: https://fr.wordpress.org
Child Theme: ❌ – Si vous modifiez WooCommerce sur un thème parent que vous n‘avez pas construit personnellement
nous vous recommandons d‘utiliser un thème enfant. Voir : Comment créer un thème enfant

WooCommerce Support: ❌ Non déclaré

### Templates ###

Overrides: /var/www/wptest/wp-content/plugins/woocommerce/templates/block-notices/error.php
/var/www/wptest/wp-content/plugins/woocommerce/templates/block-notices/notice.php
/var/www/wptest/wp-content/plugins/woocommerce/templates/block-notices/success.php


### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
pattern-toolkit-full-composability
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
printful
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page
launch-your-store

Disabled Features: experimental-blocks
minified-js
product-pre-publish-modal
settings
async-product-editor-category-field
product-editor-template-system
blueprint
reactify-classic-payments-settings

Daily Cron: ✔ Next scheduled: 2024-10-17 17:18:49 +02:00
Options: ✔
Notes: 55
Onboarding: completed

### Action Scheduler ###

Terminé: 7
Oldest: 2024-10-16 19:19:19 +0200
Newest: 2024-10-17 13:55:23 +0200

Échoué: 1
Oldest: 2024-10-17 13:45:21 +0200
Newest: 2024-10-17 13:45:21 +0200

En attente: 1
Oldest: 2024-10-17 19:19:20 +0200
Newest: 2024-10-17 19:19:20 +0200


### Status report information ###

Generated at: 2024-10-17 14:03:58 +02:00
```
</details>

### Isolating the problem

- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by wavvves**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

This PR prepares the options for a select box used as an additional address field, so it can display a placeholder. On that view, opposed to the checkout block, it doesn't rely on the data placeholder entry, and instead expects an empty keyed placeholder text.

Closes #52110 .

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Add the following snippet to your theme functions.php or at the end of the main woocommerce.php file.
2. Go to My Account > Addresses > Edit Shipping Address
3. Verify that the placeholder "Click to choose something" is selected. Save other values and verify they get persisted.
5. Change back to the placeholder, and verify the value is cleared.

```php
add_action(
	'woocommerce_init',
	function() {
		woocommerce_register_additional_checkout_field(
			array(
				'id'            => 'mynamespace/number',
				'type'          => 'select',
				'label'         => 'Choose something',
				'location'      => 'address',
				'required'      => false,
				'options'       => [
					[
						'value' => 0,
						'label' => "ZERO"
					],
					[
						'value' => "1",
						'label' => "One!"
					],
					[
						'value' => 2,
						'label' => "Two!"
					],
					[
						'value' => 'green',
						'label' => "The color green!"
					],
					[
						'value' => "7",
						'label' => "Seven!"
					]
				],
				'placeholder'   => 'Click to choose something'
			),
		);
	}
);
```

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 
Fixed a bug causing placeholder for additional select fields not to be shown when editing addresses on My Account screen.
</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce/includes/wc-template-functions.php [hunk 1]
```diff
@@ -3108,15 +3108,14 @@ function woocommerce_form_field( $key, $args, $value = null ) {
...
 				$options = '';
 
 				if ( ! empty( $args['options'] ) ) {
 					foreach ( $args['options'] as $option_key => $option_text ) {
 						if ( '' === $option_key ) {
-							// If we have a blank option, select2 needs a placeholder.
+							// A blank option is the proper way to set a placeholder. If one is supplied we make sure the placeholder key is set for selectWoo.
 							if ( empty( $args['placeholder'] ) ) {
-								$args['placeholder'] = $option_text ? $option_text : __( 'Choose an option', 'woocommerce' );
+								$args['placeholder'] = $option_text ? : __( 'Choose an option', 'woocommerce' );
```
Comment (alexflorisca) [inline plugins/woocommerce/includes/wc-template-functions.php]: This feels weird to me. What is the value if `$option_text` is set? `undefined`? `null`? Maybe it's worth being a bit more explicit here with an actual value for the `?` part of the ternary expression

File: plugins/woocommerce/src/Blocks/Domain/Services/CheckoutFieldsFrontend.php [hunk 2]
```diff
@@ -242,6 +242,15 @@ public function edit_address_fields( $address, $address_type ) {
 
 			if ( 'select' === $field['type'] ) {
 				$address[ $field_key ]['options'] = array_column( $field['options'], 'label', 'value' );
+
+				// If a placeholder is set, add a placeholder option if it doesn't exist already.
+				if (
+					! empty( $address[ $field_key ]['placeholder'] )
+					&& ! array_key_exists( '', $address[ $field_key ]['options'] )
+				) {
+					$address[ $field_key ]['options'] = array_merge( array( '' => $address[ $field_key ]['placeholder'] ), $address[ $field_key ]['options'] );
```
Comment (alexflorisca) [inline plugins/woocommerce/src/Blocks/Domain/Services/CheckoutFieldsFrontend.php]:
```suggestion
					$address[ $field_key ]['options'] = array_merge( array( $address[ $field_key ]['placeholder'] => '' ), $address[ $field_key ]['options'] );
```

Comment (alexflorisca) [reply plugins/woocommerce/src/Blocks/Domain/Services/CheckoutFieldsFrontend.php]: Should the `''` be the value here?

**Review by alexflorisca — CHANGES_REQUESTED** [review]
Hey Paulo, I'm getting some strange behaviour when testing this one (see video) but I think you may have mixed up the `key` with `value` in your code, left a suggestion below. 


https://github.com/user-attachments/assets/674219a2-0a73-4e49-b921-350e60f3aea5

**Comment by wavvves** [comment]
Thanks Alex, I don't think it was mixed, it's not actually sending keys, just 0,1 etc and that points to the wrong value in the db or something like that. I thought I had outdated data in the db because I saved but changed the added additional field with the same id, but it seems to be an actual bug. Thanks, I'll have a look!

File: plugins/woocommerce/includes/wc-template-functions.php (hunk 1 above)
Comment (nielslange) [reply plugins/woocommerce/includes/wc-template-functions.php]: The [shorthand ternary operator](https://stitcher.io/blog/shorthand-comparisons-in-php#shorthand-ternary-operator) in the following line looks broken:
```php
$args['placeholder'] = $option_text ? : __( 'Choose an option', 'woocommerce' );
```

Shouldn't it be `?:` instead of `? :`? Note the extra space between the the chars.

Comment (wavvves) [reply plugins/woocommerce/includes/wc-template-functions.php]: It's not broken, space is optional and formatter added it. But I'll revert this because linting doesn't allow shorthand ternaries.

@alexflorisca it's the shorthand operator, in the cases the value itself decides if it stays the same or gets assigned a new one, enabling us to ommit that part. It was equivalent to the unchanged line, but the linter doesn't like it so I'll remove.

**Comment by alexflorisca** [comment]
Hey @wavvves let me know if I should review this again

**Comment by ralucaStan** [comment]
@wavvves is there anything keeping this PR review from progressing? Should it be marked as a draft?

**Comment by wavvves** [comment]
@ralucaStan marking this as draft for now, but will be picking it up tomorrow again.

File: plugins/woocommerce/src/Blocks/Domain/Services/CheckoutFieldsFrontend.php (hunk 2 above)
Comment (wavvves) [reply plugins/woocommerce/src/Blocks/Domain/Services/CheckoutFieldsFrontend.php]: It's not a mistake, if I do that I don't get to set a placeholder on the dropdown:
image

This is for selectWoo (fork from select2 for a11y), I updated [this comment](https://github.com/woocommerce/woocommerce/pull/52836/commits/6e100578a3d49dd17cb952616fc906a2c4d6ba7a#diff-d49488c34017d273db858b7b6eff58f22d95310991d26638e75793c6a1e98678L3117) because I found it confusing too.

Comment (wavvves) [reply plugins/woocommerce/src/Blocks/Domain/Services/CheckoutFieldsFrontend.php]: The bug was caused by `array_merge()` which didn't preserve keys. I replaced it with the `+` and seems to be working fine now.

**Comment by wavvves** [comment]
This ready for another review @alexflorisca 🙂

**Comment by alexflorisca** [comment]
This tests well now Paulo, thank you!

**Review by alexflorisca — APPROVED** [review]
This tests well now Paulo, thank you!
