### PR TITLE
Fatal error: urldecode() receives array in wc_product_canonical_redirect()

### LINKED ISSUE #63582: Fatal error: urldecode() receives array in wc_product_canonical_redirect() (PHP 8+)
Description:
wc_product_canonical_redirect() in wc-product-functions.php line 381 calls urldecode($value) on $_GET values without checking if $value is an array. When a URL contains array-style parameters like product_cat[]=debroussailleuse, PHP 8+ throws a fatal TypeError.

Image

Steps to reproduce:

Visit a URL with an array GET parameter, e.g.: https://example.com/listing/?product_cat[]=debroussailleuse
Fatal error is triggered
Fix: Add is_array($value) check before calling urldecode().

Environment:

WooCommerce: 10.5.3
PHP: 8.x (vérifiez la version exacte dans WooCommerce > État du système)
WordPress: 6.9.1
URL example: ?product_cat[]=debroussailleuse
Expected behavior: The page should load normally, array GET parameters should be handled gracefully.

Actual behavior: Fatal TypeError crashes the entire page.

Suggested fix: Add an is_array() check before urldecode() at line 381 of wc-product-functions.php

`<?php
// Before (current code):
if ( urldecode( $value ) !== $value ) {

// After (fixed):
if ( is_array( $value ) || urldecode( $value ) !== $value ) {`

Workaround plugin:

In the meantime, I created a lightweight plugin that sanitizes array $_GET parameters before WooCommerce's template_redirect hook runs:

`<?php
/**
 * Plugin Name: Fix WooCommerce urldecode Fatal Error
 * Description: Fixes urldecode() crash when a $_GET parameter is an array.
 * Version: 3.0
 * Author: Patrice Défago - Consultant SEO, SEA & SXO - PATDEF-webdesign
 * Author URI: https://patdef-webdesign.ch
 * Plugin URI: https://patricedefago.com
 */

if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

$GLOBALS['_GET_original_arrays'] = [];

foreach ( $_GET as $key => $value ) {
    if ( is_array( $value ) ) {
        $GLOBALS['_GET_original_arrays'][ $key ] = $value;
        $_GET[ $key ] = implode( ',', array_map( 'strval', $value ) );
    }
}

add_action( 'template_redirect', function () {
    if ( ! empty( $GLOBALS['_GET_original_arrays'] ) ) {
        foreach ( $GLOBALS['_GET_original_arrays'] as $key => $value ) {
            $_GET[ $key ] = $value;
        }
    }
}, 11 );`

### PR DESCRIPTION
**Pull request by bhavz-10**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes #63582

(For Bug Fixes) Bug introduced in PR # .

### Screenshots or screen recordings:

| Before | After |
| ------ | ----- |
|image|image|

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://developer.woocommerce.com/docs/contribution/testing/writing-high-quality-testing-instructions/), include your detailed testing instructions:

1. Add Products or Load the Sample Products
2. Go to Settings -> Permalinks
3. Set the Permalink Structure to Post name
image
4. In the Product Permalinks, Select the Shop Base
image
5. Save Changes.
6. Go to pages like `/listing/?product_cat[]=debroussailleuse` and you will no longer see the fatal

### Milestone

- [x] Automatically assign milestone for the **[next WooCommerce version](../blob/trunk/plugins/woocommerce/woocommerce.php#L6)**

> **Note:** Check the box above to have the milestone automatically assigned when merged.
> Alternatively (e.g. for point releases), manually assign the appropriate milestone.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce/includes/wc-product-functions.php [hunk 1]
```diff
@@ -398,9 +398,14 @@ function wc_product_canonical_redirect(): void {
 
 	// In the event we are dealing with ugly permalinks, this will be empty.
 	$specified_category_slug = get_query_var( 'product_cat' );
-	$specified_category_slug = urldecode( $specified_category_slug );
 
-	if ( ! is_string( $specified_category_slug ) || strlen( $specified_category_slug ) < 1 ) {
+	if ( ! is_string( $specified_category_slug ) ) {
```
Comment (kalessil) [inline plugins/woocommerce/includes/wc-product-functions.php]: This early return slightly alters how previously data types were handled. I suggest following this approach to maintain semantics as closely as possible to the original:

```php
	// https://3v4l.org/hGlto#veol as behaviour evaluation.

	// In the event we are dealing with ugly permalinks, this will be empty.
	$specified_category_slug = get_query_var( 'product_cat' );
	$specified_category_slug = is_array( $specified_category_slug ) ? '' : urldecode( (string) $specified_category_slug );

	if ( $specified_category_slug === '' ) {
		return;
	}

```

File: plugins/woocommerce/changelog/fix-63582-urldecode()-receives-array-in-wc_product_canonical_redirect() [hunk 2]
```diff
@@ -0,0 +1,4 @@
+Significance: patch
+Type: fix
+
+Fatal error: urldecode() receives array in wc_product_canonical_redirect() (PHP 8+)
```
Comment (kalessil) [inline plugins/woocommerce/changelog/fix-63582-urldecode()-receives-array-in-wc_product_canonical_redirect()]: Let's tweak this entry a bit for better readability: `Fixed a fatal error where urldecode() received an array in wc_product_canonical_redirect() when running on PHP 8 or higher.`

**Review by kalessil — CHANGES_REQUESTED** [review]
Thank you for working on this @bhavz-10 and adding great test coverage!

I'm leaving two comments: simplification and changelog readability improvements.
Can you please look into those comments and update `plugins/woocommerce/phpstan-baseline.neon` as per the [CI complaint](https://github.com/woocommerce/woocommerce/actions/runs/23294740455/job/67739430127) (and [the linter complaints](https://github.com/woocommerce/woocommerce/actions/runs/23294740444/job/67739480897))?

File: plugins/woocommerce/includes/wc-product-functions.php (hunk 1 above)
Comment (bhavz-10) [reply plugins/woocommerce/includes/wc-product-functions.php]: Hello @kalessil 

Thanks for suggesting this. This is a better approach. Will keep this in mind going forwards :raised_hands: 

I have applied the changes

File: plugins/woocommerce/changelog/fix-63582-urldecode()-receives-array-in-wc_product_canonical_redirect() (hunk 2 above)
Comment (bhavz-10) [reply plugins/woocommerce/changelog/fix-63582-urldecode()-receives-array-in-wc_product_canonical_redirect()]: Hello @kalessil 

I have applied these changes 

Thanks a lot :raised_hands:

**Comment by kalessil** [comment]
We are almost there, @bhavz-10. Could you please address [the linter complaints](https://github.com/woocommerce/woocommerce/actions/runs/23351604706/job/67931792192?pr=63723)?

**Comment by bhavz-10** [comment]
> We are almost there, @bhavz-10. Could you please address [the linter complaints](https://github.com/woocommerce/woocommerce/actions/runs/23351604706/job/67931792192?pr=63723)?

Apologies for missing that. I just resolved them and pushed the changes. Will wait for the pipelines to clear and see if I missed anything.

**Review by kalessil — APPROVED** [review]

**Comment by kalessil** [comment]
Merged. Thank you @bhavz-10.
