### PR TITLE
Fix flakiness in e2e checkout block and launch your store tests

### LINKED ISSUE #47743: [Flaky] shopper/launch-your-store.spec.js
Entire site coming soon mode 

Failed on: https://github.com/woocommerce/woocommerce/actions/runs/9201499697

### PR DESCRIPTION
**Pull request by veljkho**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes #47743, #47630, #47629, #47628, #47765

I realized that in checkout block tests, many times Playwright or the page unexpectedly removed an added email address. I believe this is because the page is not loaded completely, and it just required `waitForLoadState` for every goto page because Playwright was just too fast.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. `pnpm test:e2e-pw ./tests/e2e-pw/tests/shopper/checkout-block.spec.js`
2. `pnpm test:e2e-pw ./tests/e2e-pw/tests/shopper/launch-your-store.spec.js`

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

#### Comment 

</details>

### CODE REVIEW

**Review by adimoldovan — CHANGES_REQUESTED** [review]
Thanks for working on this @veljkho, it's appreciated.

However, we're trying to move away from using `page.waitForLoadState( 'networkidle' )` and we removed a lot of the occurrences in the last months. 
Most of the time there should be something else that can be checked on page instead.
If you find that a network request is needed to complete you can wait only for that specific request.

**Comment by veljkho** [comment]
TFLMK @adimoldovan, I agree. I never liked that function, but in this case, I was unsure because in the future, there may be changes to what loads first on the page.

I added now waiting for the product price because in my testing that's the last thing to load on page and it worked greatly.

File: plugins/woocommerce/tests/e2e-pw/utils/checkout.js [hunk 1]
```diff
@@ -16,6 +16,10 @@ export async function fillShippingCheckoutBlocks(
 	city = 'Springfield',
 	zip = '97403'
 ) {
+	await page.getByLabel( 'Country/Region' ).click();
+	await page
+		.getByRole( 'option', { name: 'United States (US)', exact: true } )
```
Comment (adimoldovan) [inline plugins/woocommerce/tests/e2e-pw/utils/checkout.js]: Can you use a function parameter instead of hardcoding the country?

File: plugins/woocommerce/tests/e2e-pw/utils/checkout.js [hunk 2]
```diff
@@ -32,6 +36,10 @@ export async function fillShippingCheckoutBlocks(
 		.getByRole( 'group', { name: 'Shipping address' } )
 		.getByLabel( 'City' )
 		.fill( city );
+	await page.getByLabel( 'State', { exact: true } ).click();
+	await page
+		.getByRole( 'option', { name: 'California', exact: true } )
```
Comment (adimoldovan) [inline plugins/woocommerce/tests/e2e-pw/utils/checkout.js]: Same as above, better to use a parameter instead of hardcoding

File: plugins/woocommerce/tests/e2e-pw/tests/shopper/launch-your-store.spec.js [hunk 3]
```diff
@@ -36,6 +36,10 @@ test.describe( 'Launch Your Store front end - logged out', () => {
 
 		await page.goto( baseURL );
 
+		await page
```
Comment (adimoldovan) [inline plugins/woocommerce/tests/e2e-pw/tests/shopper/launch-your-store.spec.js:39]: I'm not sure how this extra waitFor helps in this case. It should wait for the text in the next line anyway.

**Review by adimoldovan — COMMENTED** [review]
Thanks for removing the networkidle wait @veljkho. I left some suggestions.

File: plugins/woocommerce/tests/e2e-pw/utils/checkout.js (hunk 1 above)
Comment (veljkho) [reply plugins/woocommerce/tests/e2e-pw/utils/checkout.js]: Ah, I missed that definitely. Good spot! Updated.

File: plugins/woocommerce/tests/e2e-pw/utils/checkout.js (hunk 2 above)
Comment (veljkho) [reply plugins/woocommerce/tests/e2e-pw/utils/checkout.js]: Updated, good catch!

File: plugins/woocommerce/tests/e2e-pw/tests/shopper/launch-your-store.spec.js (hunk 3 above)
Comment (veljkho) [reply plugins/woocommerce/tests/e2e-pw/tests/shopper/launch-your-store.spec.js:39]: The issue with this flaky test was that the page loaded with proper text, but it couldn't verify with the expected assertion for some reason. It might be some race condition or Playwright again. The page was loaded and was waiting for a timeout with proper text, and it couldn't assert with expect.

I added that to solve any potential race conditions, and if it was about Playwright. It will wait now for the element first and then try to execute expect assertion.

**Comment by adimoldovan** [comment]
@veljkho It looks like selecting the country is not working and the test is failing. Can you check please?

**Comment by veljkho** [comment]
@adimoldovan I think I have a much easier solution to this.

**Review by adimoldovan — APPROVED** [review]
