### PR TITLE
Fix: React error in filter blocks due to duplicated renders

### LINKED ISSUE #49637: Filter by Price causes a JavaScript error when used with Filter by Attribure
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

We’ve noticed that when the **Filter by Price** block is used along with the **Filter by Attribute** block, it causes this error:

`react-dom.min.js?ver=18.2.0:10 DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.`

The error doesn’t appear every time. Here is a video that shows the issue: https://share.zight.com/GGuBbpNv

The blocks have been tested using a clean WordPress instance (latest WooCommerce and WordPress versions). Also, the issue has been noted on previous WooCommerce versions and custom WordPress themes.

If the Shop page uses only Filter by Attributes, there are no issues.

### Expected behavior

We expected the filters to work without causing JavaScript errors.

### Actual behavior

Using the combination of Filter by Price and Filter by Attribute WooCommerce blocks cause an error.

### Steps to reproduce

 1. Add the following blocks to a Shop page:
    - Filter by Price
    - Filter by Attribute (e.g. size)
    - Filter by Attribute (e.g. color)
 2. Product Collection (used for showing products)
 3. Go to the home page of the website.
 4. After that, go to the Shop page.
 5. Start using the Attribute filters.

### WordPress Environment ###

WordPress address (URL): https://shop.test
Site address (URL): https://shop.test
WC Version: 9.1.2
Legacy REST API Package Version: The Legacy REST API plugin is not installed on this site.
Action Scheduler Version: ✔ 3.7.4
Log Directory Writable: ✔
WP Version: 6.5.5
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.25.5
PHP Version: 8.3.7
PHP Post Max Size: 512 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 8.7.1
(SecureTransport) OpenSSL/3.3.0

SUHOSIN Installed: –
MySQL Version: 8.3.0
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 9.1.2
WC Database Prefix: wp_
Total Database Size: 6.95MB
Database Data Size: 5.24MB
Database Index Size: 1.71MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 4.05MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_posts: Data: 0.14MB + Index: 0.06MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.03MB + Index: 0.02MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 11
page: 7
post: 2
product: 9
revision: 6
wp_font_face: 33
wp_font_family: 12
wp_global_styles: 1
wp_navigation: 1
wp_template: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 9.1.2

### Dropin Plugins () ###

advanced-cache.php: advanced-cache.php

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 188 B

### WC Pages ###

Shop base: #6 - /shop/
Cart: #7 - /cart/ -  Contains the woocommerce/cart block
Checkout: #8 - /checkout/ -  Contains the woocommerce/checkout block
My account: #9 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty-Four
Version: 1.1
Author URL: https://wordpress.org
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ❌ Not declared

### Templates ###

Overrides: /Users/hb/Sites/shop/wp-content/plugins/woocommerce/templates/block-notices/error.php
/Users/hb/Sites/shop/wp-content/plugins/woocommerce/templates/block-notices/notice.php
/Users/hb/Sites/shop/wp-content/plugins/woocommerce/templates/block-notices/success.php

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page
launch-your-store

Disabled Features: experimental-blocks
minified-js
pattern-toolkit-full-composability
product-pre-publish-modal
printful
settings
async-product-editor-category-field
product-editor-template-system

Daily Cron: ✔ Next scheduled: 2024-07-17 09:09:20 +00:00
Options: ✔
Notes: 64
Onboarding: completed

### Action Scheduler ###

Complete: 21
Oldest: 2024-07-11 09:10:47 +0000
Newest: 2024-07-16 11:25:38 +0000

Failed: 1
Oldest: 2024-07-11 11:01:07 +0000
Newest: 2024-07-11 11:01:07 +0000

Pending: 1
Oldest: 2024-07-17 11:25:38 +0000
Newest: 2024-07-17 11:25:38 +0000

### Status report information ###

Generated at: 2024-07-16 11:26:16 +00:00

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by dinhtungdu**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes #49637, replaces #51736.

This PR fixes the React render error due to duplicated wrapper and filter block rendering.

Technically, we can remove the frontend render for individual filter blocks as the wrapper block now handles the rendering, but we're keeping the frontend render component of each filter block for backward compatible (stores that haven't upgraded to use filter wrapper yet).

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Go to the Shop page and click on Edit site
4. Add the Filter blocks pattern to the Shop page: (Make sure browser cache is enabled).
5. Go to the shop page and try to filter by size or color
6. Click on reset filters
7. Repeat steps 5 and 6 many times to verify there aren't any errors and the filter blocks work as expected.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce-blocks/assets/js/blocks/attribute-filter/frontend.ts [hunk 1]
```diff
@@ -17,7 +17,8 @@ const getProps = ( el: HTMLElement ) => {
 };
 
 renderFrontend( {
-	selector: '.wp-block-woocommerce-attribute-filter',
+	selector:
+		'div:not(.wp-block-woocommerce-filter-wrapper) > .wp-block-woocommerce-attribute-filter',
```
Comment (chihsuan) [inline plugins/woocommerce-blocks/assets/js/blocks/attribute-filter/frontend.ts]: Thanks for the quick fix! @dinhtungdu 

 If I'm not mistaken, it looks like `.wp-block-woocommerce-attribute-filter` is not directly under `.wp-block-woocommerce-filter-wrapper`, there is a `.wc-blocks-filter-wrapper div` in between.  

Should we update the selector to 
`.wp-block-woocommerce-attribute-filter:not(.wp-block-woocommerce-filter-wrapper .wp-block-woocommerce-attribute-filter)`?


Screenshot 2024-10-02 at 13 40 37

**Comment by chihsuan** [comment]
> but we're keeping the frontend render component of each filter block for backward compatible (stores that haven't upgraded to use filter wrapper yet)

Do you know what's the best way to test stores that use the old filter block? To confirm that the old filter block still works as expected.

File: plugins/woocommerce-blocks/assets/js/blocks/attribute-filter/frontend.ts (hunk 1 above)
Comment (dinhtungdu) [reply plugins/woocommerce-blocks/assets/js/blocks/attribute-filter/frontend.ts]: That div is rendered by React, it does not exist in the original DOM. We need to target the DOM on rendering.

**Comment by dinhtungdu** [comment]
> > but we're keeping the frontend render component of each filter block for backward compatible (stores that haven't upgraded to use filter wrapper yet)

> Do you know what's the best way to test stores that use the old filter block? To confirm that the old filter block still works as expected.

@chihsuan You can use the old pattern [here](https://github.com/woocommerce/woocommerce/blob/5bcabd036196a9b033a499137a8c2d34a4d76a63/plugins/woocommerce-blocks/patterns/filters.php) or the following snippet directly:

```html
<!-- wp:woocommerce/active-filters -->
<div class="wp-block-woocommerce-active-filters is-loading"><span aria-hidden="true" class="wc-block-active-filters__placeholder"></span></div>
<!-- /wp:woocommerce/active-filters -->

<!-- wp:woocommerce/price-filter -->
<div class="wp-block-woocommerce-price-filter is-loading"><span aria-hidden="true" class="wc-block-product-categories__placeholder"></span></div>
<!-- /wp:woocommerce/price-filter -->

<!-- wp:woocommerce/attribute-filter {"attributeId":1,"showCounts":true} -->
<div class="wp-block-woocommerce-attribute-filter is-loading"></div>
<!-- /wp:woocommerce/attribute-filter -->

<!-- wp:woocommerce/stock-filter {"showCounts":true} -->
<div class="wp-block-woocommerce-stock-filter is-loading"></div>
<!-- /wp:woocommerce/stock-filter -->
```

**Review by gigitux — APPROVED** [review]
Thanks for the quick fix, @dinhtungdu! 🚀 

I tested the PR with the current version of the filter blocks and with the old one using the snippet shared by you: everything works as expected!


Thanks, @chihsuan, for helping us to debug this issue! 🙇

File: plugins/woocommerce-blocks/assets/js/blocks/attribute-filter/frontend.ts (hunk 1 above)
Comment (chihsuan) [reply plugins/woocommerce-blocks/assets/js/blocks/attribute-filter/frontend.ts]: Thank you for the clarification! 

In that case, if the filter wrapper renders the attribute filter block first and alters the DOM structure, then the attribute filter block itself renders, will the selector still function correctly?

My understanding is that the attribute filter selector will be a match since it would already be present in the DOM at that point. Do I miss anything?

**Comment by chihsuan** [comment]
> @chihsuan You can use the old pattern [here](https://github.com/woocommerce/woocommerce/blob/5bcabd036196a9b033a499137a8c2d34a4d76a63/plugins/woocommerce-blocks/patterns/filters.php) or the following snippet directly:
> 

Thanks, tested the old filter block and confirmed that it still works as expected.

File: plugins/woocommerce-blocks/assets/js/blocks/attribute-filter/frontend.ts (hunk 1 above)
Comment (chihsuan) [reply plugins/woocommerce-blocks/assets/js/blocks/attribute-filter/frontend.ts]: I tried to simulate the scenario by delaying the rendering of the attribute filter block. The issue seems to still happen. 🤔 

```js
setTimeout( () => {
	renderFrontend( {
		selector:
			'div:not(.wp-block-woocommerce-filter-wrapper) > .wp-block-woocommerce-attribute-filter',
		Block,
		getProps,
	} );
}, 3000 );
```

Comment (dinhtungdu) [reply plugins/woocommerce-blocks/assets/js/blocks/attribute-filter/frontend.ts]: That's a good point! Let me test it with your timeout trick to see what happens.
Edit: I didn't see your recent comment at the time I posted this.

Comment (dinhtungdu) [reply plugins/woocommerce-blocks/assets/js/blocks/attribute-filter/frontend.ts]: Perhaps we can be more aggressive here, check if there is `.wp-block-woocommerce-filter-wrapper` in the DOM, then we bail the rendering for individual filter blocks, based on the assumption that if users upgrade filter blocks, they upgraded all blocks already. What do you think @chihsuan ?

Comment (dinhtungdu) [reply plugins/woocommerce-blocks/assets/js/blocks/attribute-filter/frontend.ts]: I don't want to remove the extra div ~(even though I consider it's not necessary)~ because of (again) the backward compat reason.

Comment (chihsuan) [reply plugins/woocommerce-blocks/assets/js/blocks/attribute-filter/frontend.ts]: >  based on the assumption that if users upgrade filter blocks, they upgraded all blocks already. 

If the assumption is correct, then it should work. If users only partially upgrade the blocks, then the individual filters will not be rendered. 😅 I'm not sure if it's likely to happen, do users manually upgrade the blocks one by one?

Comment (dinhtungdu) [reply plugins/woocommerce-blocks/assets/js/blocks/attribute-filter/frontend.ts]: Hmm, let me try another CSS query.

Comment (dinhtungdu) [reply plugins/woocommerce-blocks/assets/js/blocks/attribute-filter/frontend.ts]: @chihsuan I think I got it, can you please test the latest commit.

Comment (dinhtungdu) [reply plugins/woocommerce-blocks/assets/js/blocks/attribute-filter/frontend.ts]: Tested with timeout and it's working.

Comment (chihsuan) [reply plugins/woocommerce-blocks/assets/js/blocks/attribute-filter/frontend.ts]: Thanks for the update! I've tested the latest commit and it works as expected. 

I tested the following scenarios:

1. Shop page with new attribute filters, price filter, stock filter, rating filter, and active filters.
2. Shop page mixed with old and new attribute filters.
3. Shop page with only old attribute filters.
4. With and without the delay in rendering the attribute filter block.
5. With and without network cache.

I think we're good to go! 🙌

**Review by chihsuan — APPROVED** [review]
Looks good to me! 🙂
