### PR TITLE
Factory classname handling

### LINKED ISSUE #12718: [2.7] Create variations from all attributes doesn't create any product variations
## EXPLANATION OF THE ISSUE

I'm using the current master, fetched and merged at 29.12 @ 14:00 CET, and WP 4.7. When creating a Variable product - **that was not been saved (Save Draft) or Published** - the _Create variations from all attributes_ doesn't create any product variations

## STEPS TO REPRODUCE THE ISSUE

1. create new variable product.
2. add/create a new custom attribute or select an existing attribute.
3. add 1 or more terms to the attribute.
4. go to Variations tab and choose to "create variations from all attributes"
5. confirm the javascript message that returns 'No variations added'.

If the Product has a saved draft or has been published, this issue is not present.

## SYSTEM STATUS REPORT

```
### WordPress Environment ###

Home URL: https://virtualbox-mageia.carvalho-pc/tlc-dev
Site URL: https://virtualbox-mageia.carvalho-pc/tlc-dev
WC Version: 2.7.0
Log Directory Writable: ✔
WP Version: 4.7
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_GB

### Server Environment ###

Server Info: Apache/2.4.10 (Mageia) OpenSSL/1.0.2j PHP/5.6.27
PHP Version: 5.6.27
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.40.0
OpenSSL/1.0.2j

SUHOSIN Installed: –
Max Upload Size: 8 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.7.0
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (24) ###

ALO EasyMail Newsletter: by Alessandro Massasso – 2.9.3
WP Offload S3 Lite: by Delicious Brains – 1.1.4
Amazon Web Services: by Delicious Brains – 1.0.1
Autoptimize: by Frank Goossens (futtta) – 2.1.0
BackWPup: by Inpsyde GmbH – 3.3.4
Contact Form 7: by Takayuki Miyoshi – 4.6
Cookie Notice: by dFactory – 1.2.37
Events Maker: by dFactory – 1.6.12
Homepage Control: by WooThemes – 2.0.2
Loco Translate: by Tim Whitlock – 2.0.10
Maintenance Page: by ThemeGrill – 1.0.8
Polylang: by Frédéric Demarle – 2.0.11
Postman SMTP: by Jason Hendriks – 1.7.2
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 2.2.6
Remove query strings from static resources: by Your WP Expert – 1.3.1
Shariff Wrapper: by Jan-Peter Lambeck & 3UU – 4.3.0
Storefront Parallax Hero Polylang Integration: by Antonio de Carvalho – 1.0.0
Storefront Parallax Hero: by WooThemes – 1.5.4
Storefront Reviews: by WooThemes – 1.0.2
Tipu Scroll To Top: by Zubair Mushtaq – 3.0
WooCommerce: by WooThemes – 2.7.0-beta-1
WooCommerce Helper: by WooCommerce – 1.7.2 – Network enabled
WP Smush: by WPMU DEV – 2.5.2
WP Overnight Sidekick: by Jeremiah Prummer – 1.0.1

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)


### WC Pages ###

Shop base: #8 - /en/shop/
Basket: #9 - /en/cart/
Checkout: #10 - /en/checkout/
My account: #11 - /en/my-account/

### Theme ###

Name: Storefront Child Theme
Version: 1.1.0
Author URL: https://github.com/decarvalhoaa
Child Theme: ✔
Parent Theme Name: Storefront
Parent Theme Version: 2.1.6
Parent Theme Author URL: https://woocommerce.com/
WooCommerce Support: ✔

### Templates ###

Overrides: storefront-child-theme-master/woocommerce/checkout/terms.php
```

### PR DESCRIPTION
**Pull request by mikejolley**
This fixes #12718 by posting the classname before attributes get saved. This also adds a new static method to get a filtered classname so you can programmatically get a class before the object is actually saved.

### CODE REVIEW

File: includes/class-wc-product-factory.php [hunk 1]
```diff
@@ -60,6 +58,23 @@ public function get_product( $product_id = false, $deprecated = array() ) {
 	}
 
 	/**
+	 * Gets a product classname and allows filtering. Returns WC_Product_Simple if the class does not exist.
+	 *
+	 * @since  2.7.0
+	 * @param  string $product_type
```
Comment (justinshreve) [inline includes/class-wc-product-factory.php]: Needs a docblock line for `$product_id`.

**Review by emdashcodes — APPROVED** [review]
I just saw one issue with a missing docblock line, but otherwise it LGTM.
