### PR TITLE
Fix/46128 check cached order id before get order return

### LINKED ISSUE #46128: WC_Order_Factory::get_order() returns invalid orders from cache
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Related to #45550 

When using order cache, if SQL replication lag is present, `WC_Order_Factory::get_order()` will return an invalid order object ($id===0) instead of `false`.

Because WC_Data objects are serialized to only include the $id, Orders have their constructor re-run when being unserialized after being retrieved from cache.  When this happens, if the DB data for the given order does not exist, the Order will set it's ID to `0` and finish it's construction.

However the order cache loading in `WC_Order_Factory` doesn't account for this:

https://github.com/woocommerce/woocommerce/blob/561a3d18c562834eb058283f08d8b3563b58ed70/plugins/woocommerce/includes/class-wc-order-factory.php#L37-L40

If the object were not cached at all, `false` would be returned if replication lag were still present because of the $classname check below:

https://github.com/woocommerce/woocommerce/blob/561a3d18c562834eb058283f08d8b3563b58ed70/plugins/woocommerce/includes/class-wc-order-factory.php#L43-L46

### Expected behavior

The following line should also check that `$order->get_id() !== 0` before returning the `$order`, otherwise, return `false` since we already know the order wasn't able to be read. https://github.com/woocommerce/woocommerce/blob/561a3d18c562834eb058283f08d8b3563b58ed70/plugins/woocommerce/includes/class-wc-order-factory.php#L38-L40

### Actual behavior

Orders with an ID of `0` are returned.

### Steps to reproduce

Write a custom script that will do the following:
1. Load a valid order through `WC_Order_Factory::get_order()` to have it cached.
2. Run a query directly against the orders table to remove the row from the DB to mimic replication lag.
3. Attempt to reload the same order from step 1 through `WC_Order_Factory::get_order()`.

### WordPress Environment

WPCOM

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by prettyboymp**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes #46128.

This change corrects the behavior within `WC_Order_Factory::get_order()` to return false for an order that was not able to load from the database when the order was saved to the `OrderCache`.

It multi-datacenter environments where data has to be replicated from one datacenter to another, cache can propagate faster than SQL data. When this happens, the `OrderCache` may contain a cached Order that does not yet exist in the database.  Since the `WC_Data` `__sleep()/__wakeup()` methods only cache the ID of the order, the rest of the data is read from the DB during construction as the order is deserialized.

Without this change, the order instance that is returned from `::get_order()` was unable to load any data and has an ID set to `0` when it was present in the `OrderCache`.

With this change, `::get_order()` will now return `false` for the order when it is in the `OrderCache` just like it would if it weren't previously cached.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

The test `WC_Order_Factory_Test::test_get_order_doesnt_return_invalid_cached_order()` has been added to the to cover this.

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [x] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce/tests/php/includes/class-wc-order-factory-test.php [hunk 1]
```diff
@@ -98,4 +101,42 @@ public function test_cache_dont_interfere_with_orders() {
...
+		 * - return false because the order was not able to fully load.
+		 * - return a fully loaded order. Our direct DB write purposefully does not trigger a cache refresh so a fully
+		 *      loaded order should also be an expected result with cache enabled.
+		 */
+		$retrieved_order = WC_Order_Factory::get_order( $order->get_id() );
+		if ( is_object( $retrieved_order ) ) {
+			$this->assertEquals( $order->get_id(), $retrieved_order->get_id() );
+		} else {
+			$this->assertFalse( $retrieved_order );
+		}
```
Comment (Konamiman) [inline plugins/woocommerce/tests/php/includes/class-wc-order-factory-test.php]: It looks like this should be two different tests, one in which the order exists in the db and is then retrieved successfully, and another one in which the order only exists in the cache and `false` is returned. Maybe you can use [PHPUnit's testWith annotation](https://docs.phpunit.de/en/9.6/annotations.html#testwith) to pass an `$orderExistsInDb` boolean to the test method and thus reuse the same method for both test cases.

**Review by Konamiman — CHANGES_REQUESTED** [review]

File: plugins/woocommerce/tests/php/includes/class-wc-order-factory-test.php (hunk 1 above)
Comment (prettyboymp) [reply plugins/woocommerce/tests/php/includes/class-wc-order-factory-test.php]: @Konamiman The test here is verifying that `WC_Order_Factory::get_order()` doesn't return an Order object with and ID of `0`.  The behavior here, though, depends on whether #46023 is merged. 

Without #46023, ``WC_Order_Factory::get_order()` should return false because the order data wasn't able to be loaded from the database.  However, with #46023, the order would still be able to load because the data is available in cache.  So, if one of this or #46023 is merged, this test will break for the other without the if/else here.

I'll just assume this simpler PR would be merged first, and check that the `$retrieved_order` is always `false` and then update #46023 with two tests based on cache state.

Comment (Konamiman) [reply plugins/woocommerce/tests/php/includes/class-wc-order-factory-test.php]: > I'll just assume this simpler PR would be merged first, and check that the $retrieved_order is always false and then update https://github.com/woocommerce/woocommerce/pull/46023 with two tests based on cache state.

Thanks, that makes sense; as long as you remember to rebase https://github.com/woocommerce/woocommerce/pull/46023 from `trunk` after this one is merged, we're good.

Good job with `SerializingCacheProxy` and `SerializingCacheTrait`, by the way; any helpful additions and improvements on the unit testing infrastructure are highly welcome.

**Review by Konamiman — APPROVED** [review]
