### PR TITLE
Block Patterns cache: ensure that relative path are used

### LINKED ISSUE #53345: Block patterns cache transient may contain incorrect paths
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

After updating WooCommerce to **9.5.0 Beta** in MailPoet automated tests we started getting many PHP Notices `User Notice: Function WP_Block_Patterns_Registry::register was called incorrectly. Pattern content must be a string`

The source of the problem is that the newly added cache for block patterns (https://github.com/woocommerce/woocommerce/pull/51802) stores absolute paths to the pattern source files (e.g. `/var/www/html/wp-content/plugins/woocommerce/patterns/banner.php`).

In our test environment, we have two containers with WordPress (test suite container and test site container). They share the same DB but WordPress is installed in different paths. When we run a WP CLI command in the suite container, it caches the Woo patterns data, and then we get the notices when we access the test site on the site container.

This issue is likely an edge case, which won't happen on standard WordPress installs. We are able to work around the issue. As there is a straightforward way to prevent it, I chose to submit this issue so we can consider addressing it. It can potentially affect sites that, for some reason, have WordPress installed in multiple places or change the WordPress installation path.

The issue could be prevented by [caching only path relative to `$this->patterns_path`](https://github.com/woocommerce/woocommerce/blob/f666a3f549c567520a56d80466050b344d4c9b30/plugins/woocommerce/src/Blocks/BlockPatterns.php#L150-L161) and adding the `$this->patterns_path` when reading from the cache.

### Expected behavior

Block patterns cache is dependent on the WordPress installation path.

### Actual behavior

Block patterns cache is not dependent on the WordPress installation path.

### Steps to reproduce

1) Install WordPress in two locations with shared DB
2) Run a WP CLI command from the first location
3) Access the site set up on the second location

### WordPress Environment

<details><summary>System Status Report</summary>

```
### WordPress Environment ###

WordPress address (URL): [Redacted]
Site address (URL): [Redacted]
WC Version: 9.5.0-beta.2
Legacy REST API Package Version: The Legacy REST API plugin is not installed on this site.
Action Scheduler Version: ✔ 3.8.2
Log Directory Writable: ✔
WP Version: 6.7.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: –
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.62 (Debian)
PHP Version: 8.3.14
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.88.1
OpenSSL/3.0.15

SUHOSIN Installed: –
MySQL Version: 5.7.38
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

[REDACTED]

### Post Type Counts ###

attachment: 1
mailpoet_page: 2
page: 13
post: 4
wp_navigation: 1

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (2) ###

MailPoet: by MailPoet – 5.4.1
WooCommerce: by Automattic – 9.5.0-beta.2

### Inactive Plugins (6) ###

Akismet Anti-spam: Spam Protection: by Automattic - Anti-spam Team – 5.3.5
AutomateWoo: by WooCommerce – 6.1.2
Hello Dolly: by Matt Mullenweg – 1.7.2
MailPoet Premium: by MailPoet – 5.4.0
WooCommerce Memberships: by SkyVerge – 1.26.5 (update to version 1.26.9 is available)
WooCommerce Subscriptions: by WooCommerce – 6.9.1

### Settings ###

Legacy API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: right
Thousand Separator: 
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 4 KB

### WC Pages ###

Shop base: #16 - /shop-2/
Cart: #17 - /shortcode-cart/ -  Contains the [woocommerce_cart] shortcode
Checkout: #18 - /shortcode-checkout/ -  Contains the [woocommerce_checkout] shortcode
My account: #19 - /shortcode-my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty-One
Version: 2.4
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
Theme type: Classic theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### MailPoet ###

Sending Method: PHPMail
Send all site's emails with: Default WordPress sending method
Task Scheduler method: Action Scheduler
Cron ping URL: http://test.local?mailpoet_router&endpoint=cron_daemon&action=ping

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
onboarding
onboarding-tasks
pattern-toolkit-full-composability
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
printful
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page
launch-your-store

Disabled Features: product-data-views
experimental-blocks
coming-soon-newsletter-template
minified-js
product-pre-publish-modal
settings
async-product-editor-category-field
product-editor-template-system
blueprint
reactify-classic-payments-settings
use-wp-horizon
add-to-cart-with-options-stepper-layout

Daily Cron: ✔ Next scheduled: 2024-12-02 09:35:30 +00:00
Options: ✔
Notes: 1
Onboarding: completed

### Action Scheduler ###

Complete: 24
Oldest: 2024-12-02 09:35:32 +0000
Newest: -0001-11-30 00:00:00 +0000

Pending: 3
Oldest: 2024-12-02 09:35:52 +0000
Newest: 2024-12-02 09:36:48 +0000


### Status report information ###

Generated at: 2024-12-02 09:36:04 +00:00
```
</details>

### Isolating the problem

- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by gigitux**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes #53345 (WOOPLUG-2826)

### Screenshots or screen recordings:

| Before | After |
| ------ | ----- |
|        |       |

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

## Ensure that patterns are visible even if the cache has still the absolute path:

1. Ensure that you're trunk.
2. Install Transient Manager plugin.
3. In WP Admin, click Tools > Transients.
4. Search for `woocommerce_blocks_patterns`.
5. Edit it.
6. Ensure that `source` contains the absolute path.
7. Visit the post editor and search for `woocommerce-blocks/banner`.
8. Ensure that it is visible.
9. Switch to this branch.
10. Visit the post editor and search for `woocommerce-blocks/banner`.
11. Ensure that it is visible.

## Ensure that patterns are visible when the cache has relative path:

1. In WP Admin, click Tools > Transients.
2. Search for `woocommerce_blocks_patterns`.
3. Remove.
4. Refresh the page.
5. Search for `woocommerce_blocks_patterns`.
6. Edit it.
7. Ensure that `source` contains the relative path.
8. Visit the post editor and search for `woocommerce-blocks/banner`.
9. Ensure that it is visible.

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [x] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 
Block Patterns cache: ensure that relative path are used.

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce/src/Blocks/BlockPatterns.php [hunk 1]
```diff
@@ -114,7 +114,16 @@ public function register_block_patterns() {
...
 		$patterns = $this->get_block_patterns();
 		foreach ( $patterns as $pattern ) {
-			$this->pattern_registry->register_block_pattern( $pattern['source'], $pattern, $this->get_patterns_dictionary() );
+			/**
+			 * Handle backward compatibility for pattern source paths.
+			 * Previously, patterns were stored with absolute paths. Now we store relative paths.
+			 * If we encounter a pattern with an absolute path (containing $patterns_path),
+			 * we keep it as is. Otherwise, we construct the full path from the relative source.
+			 */
+			$pattern_path      = str_contains( $pattern['source'], $this->patterns_path ) ? $pattern['source'] : $this->patterns_path . '/' . $pattern['source'];
```
Comment (Aljullu) [inline plugins/woocommerce/src/Blocks/BlockPatterns.php:125]: Not a big deal, but in the next release it will be safe to remove this check because any old cache will be invalidated, no? Wondering if we should open an issue (or leave a `@todo` comment) so we know it's safe to remove. What do you think?

**Review by Aljullu — APPROVED** [review]
Nice improvement, looks good on my end. I tested checking the transient directly in the database. Before, `_site_transient_woocommerce_blocks_patterns` contained absolute paths and after deleting and reloading the editor, `_site_transient_woocommerce_blocks_patterns` only contains relative paths.

Also, everything seems to work with both, relative and absolute paths. So LGTM.

<details>
<summary>Testing environment</summary>

* WordPress 6.8 local dev environment
* Plugins: Gutenberg, WooCommerce Beta Tester, WordPress Beta Tester
* Theme: Twenty Twenty-Five
* Store creation: April 15th 2025
* Store size: small
</details>

File: plugins/woocommerce/src/Blocks/BlockPatterns.php (hunk 1 above)
Comment (gigitux) [reply plugins/woocommerce/src/Blocks/BlockPatterns.php:125]: Good point! I think that you're right! Maybe I would not target the immediately next release just to play safe 😁

What do you think about wrapping up the work during the work cycle for Woo 10.1?

Comment (Aljullu) [reply plugins/woocommerce/src/Blocks/BlockPatterns.php:125]: > What do you think about wrapping up the work during the work cycle for Woo 10.1?

It sounds good to me! Definitely not something that we need to do right after. But I think it's worth keeping a reminder somewhere. :slightly_smiling_face:

Comment (gigitux) [reply plugins/woocommerce/src/Blocks/BlockPatterns.php:125]: I updated the comment (059bda41cd6b0b1a7100a456af69d166de5aaee8) and created a dedicated issue https://github.com/woocommerce/woocommerce/issues/57354
