### PR TITLE
Product Filters: properly handle special characters in filter option label

### LINKED ISSUE #59719: Inconsistent Character Decoding for Special Characters in Filter UI Components (Active Filters, Chips, and Checkbox List)
**Describe the bug**

There is an issue with character decoding in the Active Filters display. The `&` character (and possibly others) is rendered correctly in some places, but appears incorrectly in the Active Filters section. Additionally, the same decoding issue is present in the Chips and Checkbox list components inside the editor—special characters such as `&` are not being consistently and correctly decoded, leading to incorrect display of attribute terms with special characters across these components.

**To Reproduce**

1. In the block inserter, add a filter block for a specific product attribute (such as “Color” or “Size”)—for example, “Filter by Color.”
2. Ensure that at least one term for the attribute contains a special character, such as `&` (e.g., “Black & White”).
3. Apply the filter by selecting the attribute term with the special character.
4. Observe that the filter chip and Checkbox list in the editor, as well as the Active Filters section, may display the character incorrectly.

**Expected behavior**

Special characters such as `&` should be consistently and correctly decoded in all filter UI components, including filter chips, Checkbox lists in the editor, and the Active Filters section.

**Additional context**

This issue was identified during the review of #59589. As noted in the PR, the encoding issue is related to Active filter data and is planned to be addressed in a follow-up. The same issue now also affects filter chips and Checkbox lists in the editor.

**Reference**

See discussion and context in PR woocommerce/woocommerce#59589.

**Suggested Solution**

Review the encoding/decoding logic used for displaying filter terms in the Active Filters section, Chips, and Checkbox list components (both frontend and editor) and ensure consistent, correct decoding of special characters across all filter UI components.

### PR DESCRIPTION
**Pull request by dinhtungdu**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

This PR addresses an issue where special characters in product filter labels were not being properly decoded, causing shoppers to see encoded HTML entities (such as &amp; instead of &) that create a poor user experience and make filter labels harder to read.

Closes WOOPLUG-5048.
Closes https://github.com/woocommerce/woocommerce/issues/59719.

### Screenshots or screen recordings:

| Before | After |
| ------ | ----- |
| image | image |
| image | image |

### How to test the changes in this Pull Request:

1. Create a product with special characters in its attributes (e.g., "Size & Color" or "Material & Finish")
2. Add a Product Filters block to a page
3. Configure the filter to show the attribute with special characters
4. In the editor, verify that the filter options display the decoded characters properly
5. View the page on the frontend and verify that both the filter options and active filter labels show decoded characters
6. Test with various special characters: `&`, `<`, `>`, `"`, `'`, `©`, `®`, etc.

### CODE REVIEW

File: plugins/woocommerce/client/blocks/assets/js/blocks/product-filters/frontend.ts [hunk 1]
```diff
@@ -38,6 +39,21 @@ function unselectFilter() {
...
+function decodeHtmlEntities( text: unknown ): string {
+	if ( typeof text !== 'string' ) {
+		return '';
+	}
+
+	const doc = document.implementation.createHTMLDocument( '' );
+	doc.body.innerHTML = text;
+	return doc.body.textContent || '';
+}
+
```
Comment (gigitux) [inline plugins/woocommerce/client/blocks/assets/js/blocks/product-filters/frontend.ts]: Newbie question: can we import it without the module aliases?

**Review by gigitux — APPROVED** [review]
LGTM! Out of curiosity, can't we import the `decodeHtmlEntities` without the alias?

| Frontend | Editor |
|--------|--------|
| image | image | 



Not related to this PR: is it right that the rating filter block is rendered without stars on the editor side?

image

File: plugins/woocommerce/client/blocks/assets/js/blocks/product-filters/frontend.ts (hunk 1 above)
Comment (dinhtungdu) [reply plugins/woocommerce/client/blocks/assets/js/blocks/product-filters/frontend.ts]: Oh no, it's my newbiew mistake, I just didn't think about it.

**Comment by dinhtungdu** [comment]
> Not related to this PR: is it right that the rating filter block is rendered without stars on the editor side?

@gigitux it's actually related to my changes in this PR. I fixed that issue. Please give this one another look.

**Review by gigitux — APPROVED** [review]
All good, @dinhtungdu! LGTM! 🚢 

|  Editor | Frontend |
|--------|--------|
| image | image |
