### PR TITLE
Disable add to cart button in variable products until the script has loaded

### LINKED ISSUE #62448: When opening the single-product page on a slow network, selecting a variant product to add to cart will result in a message indicating that no product has been selected.
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When opening the single-product page on a slow network, selecting a variant product to add to cart will result in a message indicating that no product has been selected.

Image

### Expected behavior

Even with a slow network, you can quickly add items to your cart, or disable the cart button.

### Actual behavior

When using a slow network, clicking "Add to Cart" on the page will prompt "Please choose product options by visiting..."

### Steps to reproduce

1.Accessing the variant product page under a low-speed 4G network
2.Quickly add to cart

Image

### WordPress Environment

<details>

<summary>WordPress Environment</summary>

<details><summary>System Status Report</summary>

```
### WordPress Environment ###

WordPress address (URL): [Redacted]
Site address (URL): [Redacted]
WC Version: 10.3.6
Legacy REST API Package Version: The Legacy REST API plugin is not installed on this site.
Action Scheduler Version: ✔ 3.9.3
Log Directory Writable: ✔
WP Version: 6.9
WP Multisite: –
WP Memory Limit: 5 GB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.24.0
Server Architecture: Linux 6.8.0-57-generic x86_64
PHP Version: 8.3.6
PHP Post Max Size: 1 GB
PHP Time Limit: 300
PHP Max Input Vars: 1000
cURL Version: 8.5.0
OpenSSL/3.0.13

SUHOSIN Installed: –
MySQL Version: 8.0.41-0ubuntu0.24.04.1
Max Upload Size: 1 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

[REDACTED]

### Post Type Counts ###

attachment: 354
custom_css: 1
custom-css-js: 1
elementor_library: 8
nav_menu_item: 15
page: 33
post: 3
product: 39
product_variation: 47
revision: 758
shop_coupon: 6
shop_order_placehold: 122
wp_font_face: 36
wp_font_family: 12
wp_global_styles: 2
wp_navigation: 1
wpforms: 5

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (29) ###

Advanced Google reCAPTCHA: by WebFactory Ltd – 1.31
Blocksy Companion: by CreativeThemes – 2.1.2
Check Conflicts: by ioannup – 1.1.6
Classic Editor: by WordPress Contributors – 1.6.7
Code Snippets: by Code Snippets Pro – 3.6.8
Cookie Notice & Compliance for GDPR / CCPA: by Hu-manity.co – 2.5.7
Simple Custom CSS and JS: by SilkyPress.com – 3.50
Elementor Pro: by Elementor.com – 3.29.2
Elementor: by Elementor.com – 3.29.2
Flexible Shipping Import/Export Add-on: by Octolize – 1.5.9
Flexible Shipping PRO: by Octolize – 4.0.3
Flexible Shipping: by Octolize – 6.2.1
Loco Translate: by Tim Whitlock – 2.8.0
Pre-Orders for WooCommerce: by Bright Plugins – 2.1
Payment Plugins for PayPal WooCommerce: by Payment Plugins
support@paymentplugins.com – 2.0.3

Raw HTML: by Janis Elsts – 1.6.4
Custom Product tabs for WooCommerce: by Web Builder 143 – 1.4.3
Advanced Shipment Tracking for WooCommerce: by zorem – 3.8.4
WPC Frequently Bought Together for WooCommerce (Premium): by WPClever – 7.6.6
Advanced Order Export For WooCommerce: by AlgolPlus – 4.0.3
Additional Variation Images Gallery for WooCommerce: by Emran Ahmed – 1.3.28
Variation Swatches for WooCommerce: by Emran Ahmed – 2.2.0
PDF Invoices & Packing Slips for WooCommerce: by WP Overnight – 4.5.2
WooCommerce: by Automattic – 10.3.6 (update to version 10.4.2 is available)
Wordfence Security: by Wordfence – 8.1.3
Yoast SEO: by Team Yoast – 25.4
WP Mail SMTP: by WP Mail SMTP – 4.5.0
Smart Coupons for WooCommerce Pro: by WebToffee – 3.5.0
Smart Coupons For WooCommerce Coupons: by WebToffee – 2.2.4

### Inactive Plugins (12) ###

Acowebs Product Labels For Woocommerce: by Acowebs – 1.5.12
Akismet Anti-spam: Spam Protection: by Automattic - Anti-spam Team – 5.3.7
Camthink WooCommerce Member: by lemon – 0.0.1
Cart Abandonment Recovery for WooCommerce: by Brainstorm Force – 2.0.3
Discount Rules for WooCommerce: by Flycart – 2.6.13
Image Optimizer - Compress, Resize and Optimize Images: by Elementor.com – 1.6.7
Performance Lab: by WordPress Performance Team – 4.0.0
Simple Discount Rules for Woocommerce: by QuanticEdge – 5.11
Site Kit by Google: by Google – 1.157.0
WooCommerce PayPal Payments: by PayPal – 3.3.1-rc1 (update to version 3.3.1 is available)
WP Data Access: by Passionate Programmers B.V. – 5.5.43
WP phpMyAdmin: by Puvox.software – 5.2.2.01

### Must Use Plugins (1) ###

mu-check-conflicts.php: by  –

### Settings ###

Legacy API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –
Enabled Features: analytics
marketplace
order_attribution
site_visibility_badge
remote_logging
email_improvements
blueprint
point_of_sale
custom_order_tables


### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 615 KB

### WC Pages ###

Shop base: #7 - /store/
Cart: #8 - /cart/ -  Contains the [woocommerce_cart] shortcode
Checkout: #9 - /checkout/ -  Contains the woocommerce/checkout block
My account: #10 - /my-account/ -  Contains the [woocommerce_my_account] shortcode
Terms and conditions: ❌ Page not set

### Theme ###

Name: blocksy-child
Version: (update to version 0 is available)
Author URL: 
Child Theme: ✔
Parent Theme Name: Blocksy
Parent Theme Version: 2.1.0 – 2.1.23 is available
Parent Theme Author URL: https://creativethemes.com
Theme type: Classic theme
WooCommerce Support: ✔

### Templates ###

Overrides: blocksy-child/woocommerce/cart/cart.php version 7.9.0 is out of date. The core version is 10.1.0
blocksy/woocommerce/cart/mini-cart.php version 9.4.0 is out of date. The core version is 10.0.0
blocksy-child/woocommerce/checkout/form-checkout.php
blocksy/woocommerce/content-widget-product.php
blocksy/woocommerce/content-widget-reviews.php
blocksy-child/woocommerce/emails/admin-new-order.php version 9.8.0 is out of date. The core version is 10.0.0
blocksy/woocommerce/myaccount/my-account.php
blocksy/woocommerce/product-searchform.php
/var/www/wordpress/wp-content/plugins/woo-variation-gallery/templates/product-images.php
/var/www/wordpress/wp-content/plugins/woo-variation-gallery/templates/product-thumbnails.php version 9.5.0 is out of date. The core version is 9.8.0
blocksy/woocommerce/single-product/tabs/tabs.php

Outdated Templates: ❌
					
					
						Learn how to update					 |
					
						
					
					
						Clear system status theme info cache

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
onboarding
onboarding-tasks
pattern-toolkit-full-composability
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
printful
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page
launch-your-store

Disabled Features: product-data-views
experimental-blocks
experimental-iapi-mini-cart
experimental-iapi-runtime
coming-soon-newsletter-template
minified-js
product-pre-publish-modal
settings
async-product-editor-category-field
product-editor-template-system
use-wp-horizon
rest-api-v4

Daily Cron: ✔ Next scheduled: 2025-12-15 10:04:12 -04:00
Options: ✔
Notes: 66
Onboarding: skipped

### Action Scheduler ###

Canceled: 1
Oldest: 2025-12-09 06:05:58 +0000
Newest: 2025-12-09 06:05:58 +0000

Complete: 2,609
Oldest: 2025-11-17 05:24:23 +0000
Newest: 2025-12-15 00:51:38 +0000

Failed: 61
Oldest: 2025-06-30 09:53:01 +0000
Newest: 2025-12-14 09:18:10 +0000

Pending: 23
Oldest: 2025-12-15 01:51:38 +0000
Newest: 2025-12-20 10:00:15 +0000


### Status report information ###

Generated at: 2025-12-14 21:46:16 -04:00
```
</details>
</details>

### Isolating the problem

- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by Aljullu**
### Changes proposed in this Pull Request:

Closes #62448.

### How to test the changes in this Pull Request:

1. Using your browser devtools, set your network speed to a slower one (ie: 3G).
2. Open the frontend of a variable product in a classic theme or a block theme **not using** the blockified _Add to Cart + Options_ block.
3. Try hitting the _Add to cart_ button before the option selects are loaded in the screen.
4. Verify it doesn't submit the form because it's disabled.

### Milestone

- [x] Automatically assign milestone for the **[next WooCommerce version](../blob/trunk/plugins/woocommerce/woocommerce.php#L6)**

### CODE REVIEW

File: plugins/woocommerce/client/legacy/js/frontend/add-to-cart-variation.js [hunk 1]
```diff
@@ -52,17 +100,24 @@
...
+		setTimeout( function () {
 			$form.trigger( 'check_variations' );
 			$form.trigger( 'wc_variation_form', self );
+
+			// For variable products, we disable the button by default to avoid
+			// shoppers submitting the form with invalid data. We remove the
+			// disabled attribute as soon as the script is loaded and let the
+			// script handle the button state.
+			// @see https://github.com/woocommerce/woocommerce/issues/62448
+			$form.find( '.single_add_to_cart_button' ).removeAttr( 'disabled' );
```
Comment (Aljullu) [inline plugins/woocommerce/client/legacy/js/frontend/add-to-cart-variation.js:112]: This is the only change in this file. Everything else was due to auto-formatting.

**Review by dinhtungdu — APPROVED** [review]
Thanks for the PR. I can confirm the button is disabled while loading the options.

Image
