### PR TITLE
Restore support for float based quantities in Store API and Blocks

### LINKED ISSUE #54815: Decimal Quantities Are Rounded Down on Checkout Since WooCommerce 9.5.0 Update
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Since updating WooCommerce to version 9.5.0 and later, decimal quantities are being rounded down during the checkout process. This issue does not occur in WooCommerce version 9.4.3, where decimal quantities are handled correctly.

Our store does not use a standard cart page; instead, we rely solely on the mini-cart and the checkout page. Decimal quantities work correctly in the following scenarios:

Adding products with fractional quantities (e.g., 1.5 or 0.75) to the cart.
Viewing the quantities in the mini-cart.
However, as soon as the user proceeds to the checkout page, the decimal quantities are rounded down to the nearest whole number. Once this happens, the rounded value is saved in the session, and any subsequent views of the mini-cart or checkout page reflect the incorrect, rounded quantity.

### Expected behavior

Decimal quantities should be preserved throughout the checkout process and should not be rounded down. The quantity shown in the mini-cart should remain consistent with the quantity on the checkout page and in the final order. The price should also be multiplied by the decimal quantity.

### Actual behavior

Decimal quantities are rounded down to whole numbers during the checkout process. This affects both the checkout page and subsequent displays in the mini-cart after you go back after visiting the checkout page. The incorrect value is also saved in the session and the final order. Also the price is rounded down, because it takes the rounded down quantity as the desired quanityt. 

### Steps to reproduce

1. Install WooCommerce 9.4.3 and enable decimal quantities.
2. Add a product with a decimal quantity (e.g., 1.5) to the cart.
3. Confirm that the decimal quantity is preserved in the mini-cart and checkout.
4. Update WooCommerce to version 9.5 or later.
5. Add a product with a decimal quantity (e.g., 1.5) to the cart.
6. Proceed to the checkout page and observe that the quantity is rounded down to a whole number.

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://staging.tegeloutletnederland.nl
Site address (URL): https://staging.tegeloutletnederland.nl
WC Version: 9.6.0
Legacy REST API Package Version: De verouderde REST API plugin is niet geïnstalleerd op deze site.
Action Scheduler Version: ✔ 3.9.0
Log Directory Writable: ✔
WP Version: 6.7.1
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: nl_NL_formal
External object cache: –

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 8.2.25
PHP Post Max Size: 512 MB
PHP Time Limit: 60
PHP Max Input Vars: 10000
cURL Version: 8.9.1
OpenSSL/1.1.1w

SUHOSIN Installed: –
MySQL Version: 10.11.10-MariaDB-cll-lve
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 9.4.3
WC Database Prefix: wp_
Totale database grootte: 145.61MB
Database gegevens grootte: 99.37MB
Database index grootte: 46.24MB
wp_woocommerce_sessions: Data: 0.16MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.17MB + Index: 0.14MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
usHUdOyYr_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
usHUdOyYr_comments: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
usHUdOyYr_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
usHUdOyYr_options: Data: 0.11MB + Index: 0.03MB + Engine InnoDB
usHUdOyYr_postmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
usHUdOyYr_posts: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
usHUdOyYr_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
usHUdOyYr_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
usHUdOyYr_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
usHUdOyYr_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
usHUdOyYr_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
usHUdOyYr_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_actionscheduler_actions: Data: 18.55MB + Index: 18.69MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 20.55MB + Index: 9.03MB + Engine InnoDB
wp_asenha_failed_logins: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_bkntc_appearance: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_bkntc_appointments: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_bkntc_appointment_custom_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_bkntc_appointment_extras: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_bkntc_appointment_prices: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_bkntc_cart: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_bkntc_customers: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_bkntc_data: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_bkntc_forms: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_bkntc_form_inputs: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_bkntc_form_input_choices: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_bkntc_holidays: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_bkntc_locations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_bkntc_services: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_bkntc_service_categories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_bkntc_service_extras: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_bkntc_service_extra_categories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_bkntc_service_staff: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_bkntc_special_days: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_bkntc_staff: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_bkntc_staff_busy_slots: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_bkntc_timesheet: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_bkntc_translations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_bkntc_workflows: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_bkntc_workflow_actions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_bkntc_workflow_logs: Data: 0.52MB + Index: 0.00MB + Engine InnoDB
wp_breakdance_icons: Data: 3.52MB + Index: 0.33MB + Engine InnoDB
wp_breakdance_icon_sets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cmplz_cookiebanners: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cmplz_cookies: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_cmplz_dnsmpd: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cmplz_services: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.14MB + Index: 0.09MB + Engine InnoDB
wp_dgwt_wcas_index: Data: 0.17MB + Index: 0.02MB + Engine InnoDB
wp_dgwt_wcas_index_tmp: Data: 0.17MB + Index: 0.02MB + Engine InnoDB
wp_dgwt_wcas_invindex_cache: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_dgwt_wcas_invindex_cache_tmp: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_dgwt_wcas_invindex_doclist: Data: 1.52MB + Index: 0.89MB + Engine InnoDB
wp_dgwt_wcas_invindex_doclist_tmp: Data: 1.52MB + Index: 0.64MB + Engine InnoDB
wp_dgwt_wcas_invindex_wordlist: Data: 0.13MB + Index: 0.08MB + Engine InnoDB
wp_dgwt_wcas_invindex_wordlist_tmp: Data: 0.13MB + Index: 0.08MB + Engine InnoDB
wp_dgwt_wcas_stats: Data: 0.22MB + Index: 0.00MB + Engine InnoDB
wp_dgwt_wcas_tax_index: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_dgwt_wcas_tax_index_tmp: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_dgwt_wcas_var_index: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_dgwt_wcas_var_index_tmp: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_ewwwio_images: Data: 1.52MB + Index: 0.36MB + Engine InnoDB
wp_ewwwio_queue: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_e_events: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_e_notes: Data: 0.02MB + Index: 0.17MB + Engine InnoDB
wp_e_notes_users_relations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_e_submissions: Data: 0.09MB + Index: 0.27MB + Engine InnoDB
wp_e_submissions_actions_log: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_e_submissions_values: Data: 0.17MB + Index: 0.03MB + Engine InnoDB
wp_gla_attribute_mapping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gla_budget_recommendations: Data: 0.19MB + Index: 0.11MB + Engine InnoDB
wp_gla_merchant_issues: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gla_shipping_rates: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gla_shipping_times: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_hfcm_scripts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_litespeed_url: Data: 0.05MB + Index: 0.06MB + Engine InnoDB
wp_litespeed_url_file: Data: 0.06MB + Index: 0.14MB + Engine InnoDB
wp_mailchimp_carts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailchimp_jobs: Data: 0.16MB + Index: 0.00MB + Engine InnoDB
wp_mclean_refs: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
wp_mclean_scan: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_mollie_pending_payment: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 8.25MB + Index: 0.38MB + Engine InnoDB
wp_pmxe_exports: Data: 0.11MB + Index: 0.00MB + Engine InnoDB
wp_pmxe_google_cats: Data: 0.38MB + Index: 0.00MB + Engine InnoDB
wp_pmxe_posts: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_pmxe_templates: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_files: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_hash: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_history: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_images: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_imports: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_posts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_templates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_postmeta: Data: 26.52MB + Index: 8.55MB + Engine InnoDB
wp_posts: Data: 1.52MB + Index: 0.52MB + Engine InnoDB
wp_post_smtp_logmeta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_post_smtp_logs: Data: 0.44MB + Index: 0.00MB + Engine InnoDB
wp_rank_math_404_logs: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_rank_math_analytics_ga: Data: 0.33MB + Index: 0.23MB + Engine InnoDB
wp_rank_math_analytics_gsc: Data: 1.52MB + Index: 0.83MB + Engine InnoDB
wp_rank_math_analytics_inspections: Data: 0.17MB + Index: 0.14MB + Engine InnoDB
wp_rank_math_analytics_keyword_manager: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_rank_math_analytics_objects: Data: 0.09MB + Index: 0.05MB + Engine InnoDB
wp_rank_math_internal_links: Data: 0.08MB + Index: 0.06MB + Engine InnoDB
wp_rank_math_internal_meta: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_rank_math_redirections: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_rank_math_redirections_cache: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_redirects: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_sgs_log_events: Data: 0.44MB + Index: 0.16MB + Engine InnoDB
wp_sgs_log_visitors: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_smush_dir_images: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_snippets: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.23MB + Index: 0.11MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.17MB + Index: 0.11MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_tm_taskmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_tm_tasks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_usermeta: Data: 0.14MB + Index: 0.09MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wcpdf_invoice_number: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_activecampaign: Data: 0.08MB + Index: 0.08MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.13MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.09MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.06MB + Index: 0.11MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wpcode_revisions: Data: 2.52MB + Index: 0.05MB + Engine InnoDB
wp_wpfm_backup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpforms_payments: Data: 0.02MB + Index: 0.14MB + Engine InnoDB
wp_wpforms_payment_meta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wpforms_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpgb_cards: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wpgb_facets: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wpgb_grids: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wpgb_index: Data: 0.19MB + Index: 0.23MB + Engine InnoDB
wp_wpgb_styles: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wpmailsmtp_debug_events: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpmailsmtp_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpml_mails: Data: 3.03MB + Index: 0.02MB + Engine InnoDB
wp_wpr_above_the_fold: Data: 0.03MB + Index: 0.06MB + Engine InnoDB
wp_wpr_rocket_cache: Data: 0.05MB + Index: 0.05MB + Engine InnoDB
wp_wpr_rucss_used_css: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wp_phpmyadmin_extension__errors_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

acf-field: 41
acf-field-group: 4
attachment: 700
blocks: 3
breakdance_block: 16
breakdance_footer: 2
breakdance_form_res: 131
breakdance_header: 2
breakdance_popup: 7
breakdance_template: 15
custom_css: 2
elementor_font: 1
elementor_library: 36
elementor_snippet: 3
jet-engine-booking: 3
jet-menu: 4
jet-popup: 2
jet-smart-filters: 8
jet-woo-builder: 17
nav_menu_item: 33
page: 32
post: 14
product: 263
rank_math_schema: 2
revision: 171
shop_coupon: 411
shop_order: 76
shop_order_refund: 3
wcct_countdown: 1
wmpc-trash: 40
wp_global_styles: 1
wp_navigation: 1
wpcode: 34
yaymail_template: 11

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (31) ###

ActiveCampaign for WooCommerce: door ActiveCampaign – 2.8.2
ActiveCampaign: door ActiveCampaign – 8.1.16
Admin and Site Enhancements (ASE): door wpase.com – 7.6.7.1
Advanced Custom Fields PRO: door WP Engine – 6.3.5
FiboSearch - AJAX Search for WooCommerce (Pro): door FiboSearch Team – 1.28.0
Custom forms for Booknetic: door FS Code – 2.1.1
Google Calendar integration for Booknetic: door FS Code – 1.2.2
Email action for Booknetic workflows: door FS Code – 1.2.6
Booknetic: door FS-Code – 4.1.7
Breakdance: door Breakdance – 2.2.0
Complianz | GDPR/CCPA Cookie Consent: door Really Simple Plugins – 7.2.0
WooCommerce Coupon Generator: door Jeroen Sormani – 1.2.0
GTM4WP - A Google Tag Manager (GTM) plugin for WordPress: door Thomas Geiger – 1.20.3
Facebook for WooCommerce: door Facebook – 3.3.2
Headspin Copilot: door Headspin UI – 1.3.0
Kadence WooCommerce Email Designer: door Kadence WP – 1.5.14
LiteSpeed Cache: door LiteSpeed Technologies – 6.5.4
Mollie Payments for WooCommerce: door Mollie – 7.9.1
WP All Export - WooCommerce Order Export Add-On: door Soflyy – 1.0.4
Perfmatters: door forgemedia – 2.3.8
WP All Export - WooCommerce Product Export Add-On: door Soflyy – 1.0.3
Search & Replace: door WP MEDIA SAS – 3.2.3
Rank Math SEO PRO: door Rank Math – 3.0.65
Rank Math SEO: door Rank Math SEO – 1.0.236
Trustpilot-reviews: door Trustpilot – 2.5.925
PDF Invoices & Packing Slips for WooCommerce: door WP Overnight – 3.9.6
WooCommerce: door Automattic – 9.6.0
WP All Export: door Soflyy – 1.4.8
WP Grid Builder: door Loïc Blascos – 2.1.4
WP Rollback: door WP Rollback – 2.0.7
WPCode Pro: door WPCode – 2.2.5

### Inactive Plugins (3) ###

Akismet Anti-spam: Spam Protection: door Automattic - Anti-spam Team – 5.3.5
Mailchimp for WooCommerce: door Mailchimp – 5.1
YayMail - WooCommerce Email Customizer: door YayCommerce – 3.5.9

### Must Use Plugins (1) ###

WP Toolkit Worker Plugin: door  – 6.6.2-9073

### Settings ###

Legacy API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: left
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 7 dagen
Level threshold: –
Log directory size: 112 KB

### WC Pages ###

Winkelbasis: #64 - /producten/
Winkelwagen: ❌ Pagina heeft geen [woocommerce_cart] shortcode of het woocommerce/cart blok.
Afrekenen: #5631 - /afrekenen/ -  Bevat het woocommerce/checkout blok
Mijn account: ❌ Pagina bevat niet de [woocommerce_my_account] shortcode.
Algemene voorwaarden: #2927 - /klantenservice/algemene-voorwaarden/

### Theme ###

Name: Breakdance Zero Theme
Version: 1.0.0
Author URL: https://breakdance.com/
Child Theme: ❌ – Als u WooCommerce wijzigt op een hoofdthema dat u niet zelf gebouwd heeft
raden we u aan een subthema te gebruiken. Zie: Hoe maakt u een subthema

Theme type: Klassiek thema
WooCommerce Support: ✔

### Templates ###

Overrides: /home/tegeloutlet/staging.tegeloutletnederland.nl/wp-content/plugins/breakdance/subplugins/breakdance-woocommerce/templates/cart/cart-totals.php
/home/tegeloutlet/staging.tegeloutletnederland.nl/wp-content/plugins/breakdance/subplugins/breakdance-woocommerce/templates/cart/mini-cart.php versie 7.9.0 is verouderd. De hoofdversie is 9.4.0
/home/tegeloutlet/staging.tegeloutletnederland.nl/wp-content/plugins/breakdance/subplugins/breakdance-woocommerce/templates/checkout/form-billing.php
/home/tegeloutlet/staging.tegeloutletnederland.nl/wp-content/plugins/breakdance/subplugins/breakdance-woocommerce/templates/checkout/form-checkout.php versie 3.5.0 is verouderd. De hoofdversie is 9.4.0
/home/tegeloutlet/staging.tegeloutletnederland.nl/wp-content/plugins/breakdance/subplugins/breakdance-woocommerce/templates/checkout/form-login.php
/home/tegeloutlet/staging.tegeloutletnederland.nl/wp-content/plugins/breakdance/subplugins/breakdance-woocommerce/templates/checkout/form-shipping.php
/home/tegeloutlet/staging.tegeloutletnederland.nl/wp-content/plugins/breakdance/subplugins/breakdance-woocommerce/templates/checkout/payment.php
/home/tegeloutlet/staging.tegeloutletnederland.nl/wp-content/plugins/breakdance/subplugins/breakdance-woocommerce/templates/content-product.php versie 3.6.0 is verouderd. De hoofdversie is 9.4.0
/home/tegeloutlet/staging.tegeloutletnederland.nl/wp-content/plugins/breakdance/subplugins/breakdance-woocommerce/templates/global/form-login.php versie 7.1.0 is verouderd. De hoofdversie is 9.2.0
/home/tegeloutlet/staging.tegeloutletnederland.nl/wp-content/plugins/breakdance/subplugins/breakdance-woocommerce/templates/global/quantity-input.php versie 7.8.0 is verouderd. De hoofdversie is 9.4.0
/home/tegeloutlet/staging.tegeloutletnederland.nl/wp-content/plugins/breakdance/subplugins/breakdance-woocommerce/templates/loop/loop-start.php
/home/tegeloutlet/staging.tegeloutletnederland.nl/wp-content/plugins/breakdance/subplugins/breakdance-woocommerce/templates/loop/rating.php

Outdated Templates: ❌
					
					
						Leer hoe te updaten					 |
					
						
					
					
						Thema infocache van systeemstatus wissen

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
onboarding
onboarding-tasks
pattern-toolkit-full-composability
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
printful
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page
launch-your-store

Disabled Features: product-data-views
experimental-blocks
coming-soon-newsletter-template
minified-js
product-pre-publish-modal
settings
async-product-editor-category-field
product-editor-template-system
blueprint
reactify-classic-payments-settings
use-wp-horizon
add-to-cart-with-options-stepper-layout
blockified-add-to-cart

Daily Cron: ✔ Next scheduled: 2025-01-24 13:22:40 +01:00
Options: ✔
Notes: 207
Onboarding: completed

### Action Scheduler ###

Canceled: 4
Oldest: 2024-12-24 19:47:47 +0100
Newest: 2025-01-21 03:00:23 +0100

Complete: 2.320
Oldest: 2024-12-23 20:00:25 +0100
Newest: 2025-01-23 17:48:33 +0100

Failed: 60.430
Oldest: 2022-10-26 17:18:00 +0200
Newest: 2025-01-15 12:51:35 +0100

Pending: 4
Oldest: 2025-01-24 03:00:00 +0100
Newest: 2025-02-12 11:06:52 +0100

### Status report information ###

Generated at: 2025-01-23 17:57:41 +01:00
`

### Isolating the problem

- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by mikejolley**
### Submission Review Guidelines:

* I have followed the [WooCommerce Contributing Guidelines](<https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md>) and the [WordPress Coding Standards](<https://make.wordpress.org/core/handbook/best-practices/coding-standards/>).
* I have checked to ensure there aren't other open [Pull Requests](<https://github.com/woocommerce/woocommerce/pulls>) for the same update/change.
* I have reviewed my code for [security best practices](<https://developer.wordpress.org/apis/security/>).
* Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

By default, WooCommerce and Store API use integer based quantities. Historically there have been enough filters in place to circumvent this via extensions to, for example, replace `integer` with `float`, which opens up the opportunity to have partial decimal based stock levels and quantities in the cart.

Over time new functionality (mainly Store API) has assuming integer is the only correct way and implements forced casting to `int`. This has made it impossible for extensions to implement decimal support in Store API and block based cart and checkout, and fatal errors were triggered in certain circumstances.

There is potentially an argument for supporting decimals in core and offering UIs to manage this at a per-product level, but for now we've decided to just remove forced casting and allow decimals to be used via custom code.

It's possible to test parts of this using a plugin such as *measurement price calculator* however, I'm not certain they implement all the required hooks to support this at cart and checkout level because Store API has some unique hooks for controlling stock `quantity`, `minimum`, `maximum`, and `multiple_of` properties, therefore you can test with the below snippet.

Includes test coverage for float mode. This snippet will let you test decimal based quantities in blocks:

```php
add_action(
	'init',
	function () {
		remove_filter( 'woocommerce_stock_amount', 'intval' );
		add_filter( 'woocommerce_stock_amount', 'floatval' );

		add_filter(
			'woocommerce_quantity_input_step',
			function () {
				return 0.5;
			},
			10
		);
		add_filter(
			'woocommerce_quantity_input_min',
			function () {
				return 0.5;
			},
			10
		);
	}
);
```

I added some tests for the `QuantityLimits` class which handles most of this functionality to ensure methods work in float mode.

Closes woocommerce/woocommerce#54815

### Screenshots or screen recordings:

With the snippet above in place, you'll be able to increment qty in cart by `0.5`.

Screenshot 2025-06-11 at 11 10 37

Some notices in core were also forcing integer, for example the add to cart notice which is now fixed:

Screenshot 2025-06-11 at 12 07 22

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](<https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions>), include your detailed testing instructions:

1. Implement the above snippet.
2. Add an item to the cart using decimal quantity. Confirm any visible quantities and notices show as decimals, not forced to integer.
3. Go to the block cart page.
4. Increase the quantity—it will increment in 0.5 steps. Set stock to 1.5 or above and place order. The quantity should persist. Confirm display on order confirmation and backend all uses decimals.
5. Repeat the above but this time go via classic cart and checkout, again, checking that any quantities displayed use decimal format.
6. Remove the snippet. Repeat the tests to ensure there are no regressions with integer quantities (default, should be covered by many tests already)

You can also test with extensions that introduce decimal support. They may not "work" in blocks due to the different filters used, but you should be able to go through the legacy flows without fatal errors.

Other edge case things that should be smoke tested:

* Adding grouped products to cart
* Adding variations to cart
* Adding a product that is sold individually to cart
* Checking stock managed products have their stock reduced correctly

### Testing that has already taken place:

* Tested above snippet with blocks and legacy
* Tested "Decimal Product Quantity for WooCommerce" with legacy and fixed fatal errors/block compat.
* Tested "WooCommerce Measurement Price Calculator". This one didn't see to touch qty, it had a custom input.
* Tested Smart Product Discounts. This one worked aside from min/max limits in block cart.

### Changelog entry

- [ ] Automatically create a changelog entry from the details below.
- [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details><summary>Changelog Entry Details</summary>

#### Significance

- [ ] Patch
- [ ] Minor
- [ ] Major

#### Type

- [ ] Fix - Fixes an existing bug
- [ ] Add - Adds functionality
- [ ] Update - Update existing functionality
- [ ] Dev - Development related task
- [ ] Tweak - A minor adjustment to the codebase
- [ ] Performance - Address performance issues
- [ ] Enhancement - Improvement to existing functionality

#### Message

</details>

<details><summary>Changelog Entry Comment</summary>

#### Comment

</details>

### CODE REVIEW

**Comment by straku** [comment]
I started the review with a Claude Code session to evaluate the tool. I tried to guide it into a direction of checking the changes alongside the whole codebase from the perspective of using float quantities instead of integer ones. It found some issues that were not touched directly by the PR, but I think that are worth addressing if we want to properly support floats. They are pre-existing, so technically they shouldn't block this PR. I leave it here more as a general note.

**Incorrect Loop Iterations in Discount Calculations**

[plugins/woocommerce/includes/class-wc-discounts.php:568](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/includes/class-wc-discounts.php#L568-L588)

```php
for ( $i = 0; $i < $item->quantity; $i++ ) {
  // Discount calculation logic
}
```

Problem: When `$item->quantity` is a float (e.g., 2.5), the loop runs floor(2.5) = 2 times instead of the expected behavior. This can cause an incorrect discount calculation.

<details>
<summary>EDITED: The second issue I shared here was fixed in the PR, Claude was checking local files instead of the changed ones 🤦‍♂️ Leaving it hidden here.</summary>

**Modulo Operations with Float Quantities**

[plugins/woocommerce/src/StoreApi/Utilities/QuantityLimits.php](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/src/StoreApi/Utilities/QuantityLimits.php)

[Line 95-96](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/src/StoreApi/Utilities/QuantityLimits.php#L95-L97):
```php
if ( $new_quantity % $limits['multiple_of'] ) {
    $new_quantity = $this->limit_to_multiple( $new_quantity, $limits['multiple_of'], 'round' );
}
```

[Line 156-159](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/src/StoreApi/Utilities/QuantityLimits.php#L156-L159):
```php
if ( $quantity % $limits['multiple_of'] ) {
    return new \WP_Error( 'invalid_quantity', /* error message */ );
}
```

Problem: PHP's % operator automatically converts floats to integers, causing:
- Real Examples:
  - 2.5 % 1.5 becomes 2 % 1 = 0 (should be 1.0)
  - 3.7 % 2.5 becomes 3 % 2 = 1 (should be 1.2)
  - 1.8 % 0.6 becomes 1 % 0 = DivisionByZeroError!
- PHP Warning: "Implicit conversion from float 2.5 to int loses precision"


</details>

**Comment by straku** [comment]
Notes from my testing:
- ✅ no issues noticed with displaying float quantity, it was always properly reflected; in cart, checkout, notices and the admin area
- ✅ quantity limits were properly enforced in my testing
- ⚠️ "Add to cart" button still tries to add a single item instead of 0.5 expected with your snippet
- ⚠️ when an item is added to a cart with "Add to cart" button its quantity is set to 1, I cannot lower it to 0.5 in cart using the decrement button (both in block and shortcode one); I also can't type in anything below 1

File: plugins/woocommerce/src/StoreApi/Schemas/V1/ProductSchema.php [hunk 1]
```diff
@@ -44,6 +44,16 @@ public function __construct( ExtendSchema $extend, SchemaController $controller
...
 
+	/**
+	 * Get the type for the quantity property. This is usually integer, but can be number if the stock amount is
+	 * filtered by third party plugins.
+	 *
+	 * @return string
+	 */
+	public function get_quantity_property_type() {
+		return has_filter( 'woocommerce_stock_amount', 'intval' ) ? 'integer' : 'number';
+	}
```
[the remark this answers is not in the document]
Comment (mikejolley) [reply plugins/woocommerce/src/StoreApi/Schemas/V1/ProductSchema.php]: Number covers all non-int cases so can be left as is.

**Comment by straku** [comment]
Updates to my previous [testing notes](https://github.com/woocommerce/woocommerce/pull/58693#issuecomment-2966621485).

> ⚠️ "Add to cart" button still tries to add a single item instead of 0.5 expected with your snippet

This is still the case (but I also don't think this should be part of this PR).

> ⚠️ when an item is added to a cart with "Add to cart" button its quantity is set to 1, I cannot lower it to 0.5 in cart using the decrement button (both in block and shortcode one); I also can't type in anything below 1

This is no longer a case 👏 

Everything else works for me, I've tested 0.5 increments, but also 0.25 (with some edge cases like setting the quantity limit to 3.75 with 0.5 increment, etc.). Tested new and old cart and checkout, notices and admin area. I also went through the code and I don't see any obvious issues with the code, but for this part I would prefer @opr to take a deeper dive.

**Review by straku — APPROVED** [review]

**Comment by mikejolley** [comment]
Thanks @straku I agree it needs a second pair of eyes. Sorry @opr

File: plugins/woocommerce/client/blocks/assets/js/base/hooks/use-schema-parser.ts [hunk 2]
```diff
@@ -79,7 +79,10 @@ const useDocumentObject = < T extends FormType | 'global' >(
 					),
 				],
 				items: items
-					.map( ( item ) => Array( item.quantity ).fill( item.id ) )
+					.map(
+						( item ) =>
+							Array( Math.ceil( item.quantity ) ).fill( item.id ) // Rounds up to nearest integer.
+					)
```
Comment (opr) [inline plugins/woocommerce/client/blocks/assets/js/base/hooks/use-schema-parser.ts:85]: Should we udpate `docs/block-development/cart-and-checkout-blocks/additional-checkout-fields.md` to mention that this won't handle floats

File: plugins/woocommerce/client/blocks/assets/js/data/cart/notify-quantity-changes.ts [hunk 3]
```diff
@@ -30,8 +30,7 @@ type NotifyQuantityChangesArgs = {
 const isWithinQuantityLimits = ( cartItem: CartItem ) => {
 	return (
 		cartItem.quantity >= cartItem.quantity_limits.minimum &&
-		cartItem.quantity <= cartItem.quantity_limits.maximum &&
-		cartItem.quantity % cartItem.quantity_limits.multiple_of === 0
+		cartItem.quantity <= cartItem.quantity_limits.maximum
```
Comment (opr) [inline plugins/woocommerce/client/blocks/assets/js/data/cart/notify-quantity-changes.ts]: Why can't the `cartItem.quantity % cartItem.quantity_limits.multiple_of === 0` check work here? If you're limited to multiple of 0.5 and you have 1, 1.5, 2, 2.5 this would still work, right?

**Review by opr — CHANGES_REQUESTED** [review]
Thanks Mike, the changes look good to me, mentioned a place where docs should be updated, and also checking about quantity notices.

I think we should look at the quantity input field on the Cart block too. Trying to enter decimal values there doesn't work and instantly resets to an int.

https://www.loom.com/share/d051e20f61fe46708a4b3205b6e2abab

In that video I'm trying to enter `.5` after the number, as you can see it keeps resetting to 2.

Btw, when it jumps to 5.5 (the max quantity I set in my snippet) it's because I tried entering `25`, so that's still working which is good.

File: plugins/woocommerce/client/blocks/assets/js/data/cart/notify-quantity-changes.ts (hunk 3 above)
Comment (mikejolley) [reply plugins/woocommerce/client/blocks/assets/js/data/cart/notify-quantity-changes.ts]: Modulus does not support float and I didn't think it was worth doing the check here when its validated and enforced in other places @opr

Comment (opr) [reply plugins/woocommerce/client/blocks/assets/js/data/cart/notify-quantity-changes.ts]: I also read that it doesn't usually, but I think that applied to other languages. JS does support it (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Remainder). I tried in console and it works fine.

Please can we try it because I do think it would be good to keep the notice if quantity changes unexpectedly.

File: plugins/woocommerce/client/blocks/assets/js/base/hooks/use-schema-parser.ts (hunk 2 above)
Comment (mikejolley) [reply plugins/woocommerce/client/blocks/assets/js/base/hooks/use-schema-parser.ts:85]: Added in https://github.com/woocommerce/woocommerce/pull/58693/commits/ab539ac7c7bbb091589a786c80a78e579c6f10d7

**Comment by mikejolley** [comment]
@opr see the typing fix in https://github.com/woocommerce/woocommerce/pull/58693/commits/9dfe001da2a6c6d4c5cd3199b14c54ba9e297ae7

File: plugins/woocommerce/client/blocks/assets/js/data/cart/notify-quantity-changes.ts (hunk 3 above)
Comment (mikejolley) [reply plugins/woocommerce/client/blocks/assets/js/data/cart/notify-quantity-changes.ts]: @opr I feel this is very edge case. It wouldn't happen in normal operation because user input is forced to a multiple by the step attribute. You'd have to somehow get an invalid qty into the cart for it to happen.

I'm concerned that the remainder may be a decimal close to `0` but not `===0` causing it to fail and cause excessive notices. After testing in console I am seeing `0` for basic float remainders so maybe JS is not as susceptible as we saw with PHP.

Comment (mikejolley) [reply plugins/woocommerce/client/blocks/assets/js/data/cart/notify-quantity-changes.ts]: https://github.com/woocommerce/woocommerce/pull/58693/commits/6cd5d4b533a347a58219ac8c1448e6ac1e53d457

**Review by opr — CHANGES_REQUESTED** [review]
I also noticed that when quantity is a float, it causes an error here because `array_fill` expects an integer, but the `$cart['items']` have a float `quantity`

File: plugins/woocommerce/client/blocks/assets/js/data/cart/notify-quantity-changes.ts (hunk 3 above)
Comment (opr) [reply plugins/woocommerce/client/blocks/assets/js/data/cart/notify-quantity-changes.ts]: Thanks, it's not related to your change but I did notice that manually updating the quantity slowly multiple times results in a notice being shown. I can handle it in a separate PR.

**Review by opr — CHANGES_REQUESTED** [review]
The quantity input still isn't working properly, for example I have my quantity multiple set to 1.5, when I try to enter `7.5` into the field it resets immediately to 6 (since 7 is not a multiple of 1.5). Maybe we should be less aggressive about forcing the values and apply only on blur?

File: plugins/woocommerce/client/blocks/assets/js/base/components/quantity-selector/index.tsx [hunk 4]
```diff
@@ -4,8 +4,8 @@
 import { __, sprintf } from '@wordpress/i18n';
```
Comment (mikejolley) [inline plugins/woocommerce/client/blocks/assets/js/base/components/quantity-selector/index.tsx:4]: Changes in this file were to prevent submission happening too early when typing decimals. For example, if I wanted to type `2.5`, it would submit when I've typed `2`. The local state coupled with debounce fixes this.

File: plugins/woocommerce/includes/abstracts/abstract-wc-product.php [hunk 5]
```diff
@@ -2004,20 +2004,57 @@ public function get_formatted_name() {
...
+		/**
+		 * Filters the minimum quantity which can be purchased at once.
+		 *
+		 * @since 10.1.0
+		 *
+		 * @param int|float $quantity The minimum quantity.
+		 * @param WC_Product $this The product object.
+		 * @return int|float The minimum quantity.
+		 */
+		return wc_stock_amount( apply_filters( 'woocommerce_quantity_input_min', 1, $this ) );
```
Comment (mikejolley) [inline plugins/woocommerce/includes/abstracts/abstract-wc-product.php:2018]: This filter was present in the qty input, but I wanted to consolidate the hooks rather than add new ones here. This means that `woocommerce_quantity_input_min`, `woocommerce_quantity_input_max`, `woocommerce_quantity_input_step` can be used to modify the quantity inputs on classic cart, product pages, and Store API all at once.

File: plugins/woocommerce/includes/class-wc-discounts.php [hunk 6]
```diff
@@ -565,7 +565,9 @@ protected function apply_coupon_remainder( $coupon, $items_to_apply, $amount ) {
 		$total_discount = 0;
 
 		foreach ( $items_to_apply as $item ) {
-			for ( $i = 0; $i < $item->quantity; $i++ ) {
+			$quantity = NumberUtil::ceil( $item->quantity );
```
Comment (mikejolley) [inline plugins/woocommerce/includes/class-wc-discounts.php:568]: New util takes care of ensuring `ceil` works regardless of what format quantity is in.

File: plugins/woocommerce/includes/wc-formatting-functions.php [hunk 7]
```diff
@@ -478,7 +478,24 @@ function wc_array_overlay( $a1, $a2 ) {
...
+}
+
+/**
+ * Check if the stock amount is an integer.
+ *
+ * @since 10.1.0
+ * @return bool
+ */
+function wc_is_stock_amount_integer() {
+	return wc_stock_amount( 1 ) === 1;
```
Comment (mikejolley) [inline plugins/woocommerce/includes/wc-formatting-functions.php:505]: Instead of testing for `intval` I think its more reliable to test the result of applying `wc_stock_amount`. If someone implemented `floatval` this would be false, because it would return `1.0` as a float.

File: plugins/woocommerce/includes/wc-template-functions.php [hunk 8]
```diff
@@ -2050,6 +2062,10 @@ function woocommerce_quantity_input( $args = array(), $product = null, $echo = t
 		$type = $args['min_value'] > 0 && $args['min_value'] === $args['max_value'] ? 'hidden' : 'number';
 		$type = $args['readonly'] && 'hidden' !== $type ? 'text' : $type;
 
+		if ( $product && $product->is_sold_individually() ) {
+			$type = 'hidden';
+		}
```
Comment (mikejolley) [inline plugins/woocommerce/includes/wc-template-functions.php]: Handling this here instead of the cart template.

File: plugins/woocommerce/src/Blocks/BlockTypes/AddToCartWithOptions/Utils.php [hunk 9]
```diff
@@ -63,22 +63,6 @@ public static function add_quantity_stepper_classes( $quantity_html ) {
...
-			 */
-			'min_value'   => apply_filters( 'woocommerce_quantity_input_min', $product->get_min_purchase_quantity(), $product ),
-			/**
-			 * Filter the maximum quantity value allowed for the product.
-			 *
-			 * @since 2.0.0
-			 * @param int        $max_value Maximum quantity value.
-			 * @param WC_Product $product   Product object.
-			 */
-			'max_value'   => apply_filters( 'woocommerce_quantity_input_max', $product->get_max_purchase_quantity(), $product ),
```
Comment (mikejolley) [inline plugins/woocommerce/src/Blocks/BlockTypes/AddToCartWithOptions/Utils.php]: These filters are ran in the product class now.

File: plugins/woocommerce/includes/wc-template-functions.php [hunk 10]
```diff
@@ -2012,25 +2012,34 @@ function woocommerce_quantity_input( $args = array(), $product = null, $echo = t
...
 			'autocomplete' => apply_filters( 'woocommerce_quantity_input_autocomplete', 'off', $product ),
 			'readonly'     => false,
 		);
 
+		if ( $product ) {
+			$defaults['min_value']    = $product->get_min_purchase_quantity();
+			$defaults['max_value']    = $product->get_max_purchase_quantity();
+			$defaults['step']         = $product->get_purchase_quantity_step();
+			$defaults['product_name'] = $product->get_title();
+		} else {
```
Comment (mikejolley) [inline plugins/woocommerce/includes/wc-template-functions.php]: Product class will run the filters. This is much cleaner!

File: plugins/woocommerce/templates/single-product/add-to-cart/grouped.php [hunk 11]
```diff
@@ -93,7 +93,8 @@
 										'min_value'   => apply_filters( 'woocommerce_quantity_input_min', 0, $grouped_product_child ),
 										'max_value'   => apply_filters( 'woocommerce_quantity_input_max', $grouped_product_child->get_max_purchase_quantity(), $grouped_product_child ),
 										'placeholder' => '0',
-									)
+									),
+									$grouped_product_child
```
Comment (mikejolley) [inline plugins/woocommerce/templates/single-product/add-to-cart/grouped.php]: qty input function uses global unless a product is passed

File: plugins/woocommerce/src/StoreApi/Utilities/QuantityLimits.php [hunk 12]
```diff
@@ -32,70 +33,77 @@ public function get_cart_item_quantity_limits( $cart_item ) {
...
+			// phpcs:ignore WooCommerce.Commenting.CommentHooks.MissingHookComment
+			$filtered_args = apply_filters(
+				'woocommerce_quantity_input_args',
+				[
+					'min_value' => $minimum,
+					'max_value' => $maximum,
+					'step'      => $multiple_of,
+				],
+				$product
+			);
```
Comment (opr) [inline plugins/woocommerce/src/StoreApi/Utilities/QuantityLimits.php]: Maybe consider refactoring to ensure the array passed to the hook has the same items as  in `woocommerce_quantity_input`

File: plugins/woocommerce/src/StoreApi/Utilities/QuantityLimits.php [hunk 13]
```diff
@@ -104,41 +112,69 @@ public function normalize_cart_item_quantity( int $quantity, array $cart_item )
...
+	 * @param int|float $multiple_of The multiple.
+	 * @return bool
+	 */
+	protected function is_multiple_of( $number, $multiple_of ) {
+		if ( 0 >= $multiple_of ) {
+			return false;
+		}
+
+		$division_result = $number / $multiple_of;
+		return abs( $division_result - round( $division_result ) ) < 0.0001;
```
Comment (opr) [inline plugins/woocommerce/src/StoreApi/Utilities/QuantityLimits.php:150]: Maybe comment here why we're doing this comparison

File: plugins/woocommerce/tests/php/src/Blocks/StoreApi/Utilities/QuantityLimitsTests.php [hunk 14]
```diff
@@ -11,6 +11,51 @@
...
+	 */
+	public function setUp(): void {
+		$this->manage_stock = get_option( 'woocommerce_manage_stock' );
+		parent::setUp();
+	}
+
+	/**
+	 * Clean up test environment.
+	 */
+	public function tearDown(): void {
```
Comment (opr) [inline plugins/woocommerce/tests/php/src/Blocks/StoreApi/Utilities/QuantityLimitsTests.php:30]: Add tests for the old hook too

File: plugins/woocommerce/tests/php/src/Blocks/StoreApi/Utilities/QuantityLimitsTests.php [hunk 15]
```diff
@@ -199,4 +252,338 @@ public function test_quantity_limit_when_sold_individually_without_stock() {
...
+		$cart_item = array(
+			'data' => $product,
+		);
+
+		$quantity_limits = new QuantityLimits();
+
+		// Test normalization with float quantities.
+		$normalized = $quantity_limits->normalize_cart_item_quantity( 5.7, $cart_item );
+		$this->assertIsFloat( $normalized, 'Normalized quantity should be a float when float support is enabled' );
+		$this->assertTrue( $normalized <= 10.5, 'Normalized quantity should not exceed stock limit' );
```
Comment (opr) [inline plugins/woocommerce/tests/php/src/Blocks/StoreApi/Utilities/QuantityLimitsTests.php]: Change value to match the quantity above

Comment (opr) [reply plugins/woocommerce/tests/php/src/Blocks/StoreApi/Utilities/QuantityLimitsTests.php]: consiser adding another condition that checks that the value is _greater_ than 10.4 also (to ensure `normalize_cart_item_quantity` returns values within the expected range

**Review by opr — CHANGES_REQUESTED** [review]
Thanks @mikejolley  couple of comments that we discussed in huddle, let me know when ready for another look 👌🏼

File: plugins/woocommerce/src/StoreApi/Utilities/QuantityLimits.php (hunk 13 above)
Comment (mikejolley) [reply plugins/woocommerce/src/StoreApi/Utilities/QuantityLimits.php:150]: https://github.com/woocommerce/woocommerce/pull/58693/commits/7fa45e62cffe40e0230395fc9db4a8b6583cad6a

File: plugins/woocommerce/tests/php/src/Blocks/StoreApi/Utilities/QuantityLimitsTests.php (hunk 15 above)
Comment (mikejolley) [reply plugins/woocommerce/tests/php/src/Blocks/StoreApi/Utilities/QuantityLimitsTests.php]: https://github.com/woocommerce/woocommerce/pull/58693/commits/818e84c3ec41cf054a44e0f19d37066deae4ec7d

File: plugins/woocommerce/tests/php/src/Blocks/StoreApi/Utilities/QuantityLimitsTests.php (hunk 14 above)
Comment (mikejolley) [reply plugins/woocommerce/tests/php/src/Blocks/StoreApi/Utilities/QuantityLimitsTests.php:30]: https://github.com/woocommerce/woocommerce/pull/58693/commits/e5b65f3e17cc9dd579d47006e5c5e35edb57fda2

File: plugins/woocommerce/src/StoreApi/Utilities/QuantityLimits.php (hunk 12 above)
Comment (mikejolley) [reply plugins/woocommerce/src/StoreApi/Utilities/QuantityLimits.php]: https://github.com/woocommerce/woocommerce/pull/58693/commits/e5b65f3e17cc9dd579d47006e5c5e35edb57fda2

**Review by opr — APPROVED** [review]
Thanks Mike! Looking good now, tested with Cart/Checkout blocks, shortcode cart/checkout and via StoreAPI in Insomnia.

I also tested with `[fee percent="10"]` on shipping and the value came out as expected when using decimal quantities

👏🏼  great effort on the PR thanks

File: plugins/woocommerce/includes/wc-formatting-functions.php [hunk 16]
```diff
@@ -485,7 +485,24 @@ function wc_array_overlay( $a1, $a2 ) {
...
 function wc_stock_amount( $amount ) {
-	return apply_filters( 'woocommerce_stock_amount', $amount );
+	/**
+	 * Filter the stock amount. If an invalid value is returned by hooks, falls back to intval( $amount ).
+	 *
+	 * @since  2.3
+	 * @param int|float $amount Stock amount.
+	 * @return int|float
+	 */
+	return NumberUtil::normalize( apply_filters( 'woocommerce_stock_amount', $amount ), intval( $amount ) );
```
Comment (dinhtungdu) [inline plugins/woocommerce/includes/wc-formatting-functions.php:495]: Using `intval` here means that the return value of the `wc_stock_amount()` function without filtering is always an integer. This is different from previous behavior, where it can return `''` or `null`.

Comment (mikejolley) [reply plugins/woocommerce/includes/wc-formatting-functions.php:495]: The docblock for `wc_stock_amount` says `@return int|float`. Trying to account for strings, nulls, or integers anywhere this function is used is problematic and unreliable. It should be consistent, and any filtered values should be normalised before use and not trusted.

Comment (dinhtungdu) [reply plugins/woocommerce/includes/wc-formatting-functions.php:495]: While triaging https://github.com/woocommerce/woocommerce/issues/61598, I came across https://github.com/woocommerce/woocommerce/pull/48863 and your PR here. I agree that we should normalize the return value of this function. But looks like extensions may rely on the stock being `null` too. I tagged you in a Linear issue where I included the full context, can you please take a look.

Comment (mikejolley) [reply plugins/woocommerce/includes/wc-formatting-functions.php:495]: Ill take a look. FWIW `null` doesn't make sense for a formatting function. There are other flags that can be used to determine if stock is enabled.
