### PR TITLE
[Experimental] Fix add to cart action url to be the same as the current url

### LINKED ISSUE #53284: [Enhancement]: Find a way to identify when a block is descendant of the SingleProduct block
The current method of identifying whether a block is a descendant of the SingleProduct block is [not ideal](https://github.com/woocommerce/woocommerce/pull/53215/files#r1861908953). This approach could be improved for better maintainability and reliability.

Let's try to find a better way to [handle is-descendent-of-single-product-block](https://github.com/woocommerce/woocommerce/blob/35a975865fe1bfa1e7aaabc5a2a02a6578e545f5/plugins/woocommerce/src/Blocks/BlockTypes/AddToCartWithOptions.php#L161).

### PR DESCRIPTION
**Pull request by mdperez86**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes #53284

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Make sure `Redirect to the cart page after successful addition` is unchecked under `/wp-admin/admin.php?page=wc-settings&tab=products`
2. Create a new post
5. Add the single product block
6. Select a simple product and save the post
7. Go to view the post created
8. The simple product should be shown in the frontend
9. Select 1 and click add to cart
10. Notice that the form does not perform a new redirect and it remains in the same page.
11. The same should also happens when trying to add a product cart form the single product page.
12. If the check `Redirect to the cart page after successful addition` is checked
13. Then a redirection to the cart page should happens after adding a product to the cart

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce/src/Blocks/BlockTypes/AddToCartForm.php [hunk 1]
```diff
@@ -155,6 +138,14 @@ protected function render( $attributes, $content, $block ) {
 		$is_external_product_with_url = $product instanceof \WC_Product_External && $product->get_product_url();
 		$is_stepper_style             = 'stepper' === $attributes['quantitySelectorStyle'] && ! $product->is_sold_individually() && Features::is_enabled( 'add-to-cart-with-options-stepper-layout' );
 
+		add_filter( 'woocommerce_add_to_cart_form_action', function ( $url ) use ( $is_descendent_of_single_product_block ) {
+			if ( $is_descendent_of_single_product_block ) {
```
Comment (Aljullu) [inline plugins/woocommerce/src/Blocks/BlockTypes/AddToCartForm.php]: Could this `if` be around the `add_filter()` instead of inside? This way we avoid registering the filter unnecessarily. Ie:

```PHP
if ( $is_descendent_of_single_product_block ) {
  add_filter( ... );
}
```

Also, not a strong opinion, but wondering if we should maybe add a `remove_filter()` after we rendered the template? Just to make sure we leave things as they were before the block was rendered.

**Review by Aljullu — COMMENTED** [review]
The approach looks good to me and it works as expected, thanks for investigating this, @mdperez86!

I left one comment about the way we add the filter, but not a big deal. I think we should also remove `[Experimental]` from the PR title, as this PR impacts a block available in production builds.

File: plugins/woocommerce/src/Blocks/BlockTypes/AddToCartForm.php (hunk 1 above)
Comment (mdperez86) [reply plugins/woocommerce/src/Blocks/BlockTypes/AddToCartForm.php]: done -> [5a1ec50](https://github.com/woocommerce/woocommerce/pull/55250/commits/5a1ec50fd64982fbabba2669c48d73052cb8eebd)

**Review by peterfabian — APPROVED** [review]
This fixes the issue we saw in Gift Cards, so 👍  from me.

**Review by Aljullu — APPROVED** [review]
LGTM as well. Really nice cleanup. :clap:

**Comment by PanosSynetos** [comment]
Awesome teamwork here! Thanks for the prompt fix and the reviews
