### PR TITLE
Show community forum link if wccom is not connected

### LINKED ISSUE #25442: Support link in the plugin list confusing and/or incorrect
**Describe the bug**
p6q6po-aos-p2
We should improve the user experience and, preferably, make the link point either to forum or appropriate support channel based on customer type.

**To Reproduce**
1. Go to installed plugins
2. Click on 'Premium support'
3. See what happens

### PR DESCRIPTION
**Pull request by vedanshujain**
### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

When a store is not connected to WooCommerce.com, showing the a link to premium support is bad UX. This PR links support forum, and optionally premium support link if the store is connected to WooCommerce.com

Screenshot when the store is connected:
Screenshot 2020-07-02 at 1 27 32 AM

Screenshot when the store is not connected:
Screenshot 2020-07-02 at 1 21 03 AM

Closes #25442.

### How to test the changes in this Pull Request:

1. Connect store to WooCommerce.com
2. Go to the `wp-admin/plugins.php` page.
3. You should be able to see both support forum and premium support forum links.
4. Disconnect store from WooCommerce.com (Go to WooCommerce > Extensions > WooCommerce.com Subscriptions, then from `Connected to WooCommerce.com` dropbox, select disconnect.)
5. Go back to the `wp-admin/plugins.php` page.
6. Premium support link would not show.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully run tests with your changes locally?

### Changelog entry

> Fix - Don't show premium support forum link if the store is not connected to WooCommerce.com.

### CODE REVIEW

File: src/Internals/WCCom/WCConnectionHelper.php [hunk 1]
```diff
@@ -0,0 +1,31 @@
...
+namespace Automattic\WooCommerce\Internals\WCCom;
+
+defined( 'ABSPATH' ) || exit;
+
+/**
+ * Class WCConnectionHelper.
+ *
+ * Helpers for managing connection to WooCommerce.com.
+ */
+final class WCConnectionHelper {
```
Comment (claudiosanches) [inline src/Internals/WCCom/WCConnectionHelper.php:17]: Since it uses `WCCom` namespace, we could just use `ConnectionHelper`

**Review by claudiosanches — CHANGES_REQUESTED** [review]
Looks great, but I left a note for a small tweak.

File: src/Internals/WCCom/WCConnectionHelper.php [hunk 2]
```diff
@@ -0,0 +1,31 @@
+<?php
+/**
+ * Helpers for managing connection to WooCommerce.com.
+ *
+ * @package Automattic\WooCommerce\Internals\WCCom
+ */
+
+namespace Automattic\WooCommerce\Internals\WCCom;
```
Comment (ObliviousHarmony) [inline src/Internals/WCCom/WCConnectionHelper.php:8]: Just noting that the namespace should be `Automattic\WooCommerce\Internal\WCCom`!

File: src/Internals/WCCom/WCConnectionHelper.php [hunk 3]
```diff
@@ -0,0 +1,31 @@
...
+ * Helpers for managing connection to WooCommerce.com.
+ */
+final class WCConnectionHelper {
+	/**
+	 * Check if WooCommerce.com account is connected.
+	 *
+	 * @since 4.4.0
+	 * @return bool Whether account is connected.
+	 */
+	public static function is_wccom_connected() {
```
Comment (ObliviousHarmony) [inline src/Internals/WCCom/WCConnectionHelper.php:24]: How would you feel about just `is_connected` since the method is already in the WCCom connection helper?

**Review by ObliviousHarmony — CHANGES_REQUESTED** [review]
This looks great, thanks a lot! I've left a few small comments. I recognize it may seem a bit pedantic but how would you feel about a test for the connection helper class too?

File: src/Internals/WCCom/WCConnectionHelper.php (hunk 3 above)
Comment (vedanshujain) [reply src/Internals/WCCom/WCConnectionHelper.php]: Renamed in https://github.com/woocommerce/woocommerce/pull/26932/commits/4500e86198729ce893945a39fe9e22cee3991856

File: src/Internals/WCCom/WCConnectionHelper.php (hunk 2 above)
Comment (vedanshujain) [reply src/Internals/WCCom/WCConnectionHelper.php]: Good catch! Changed in https://github.com/woocommerce/woocommerce/pull/26932/commits/4500e86198729ce893945a39fe9e22cee3991856

File: src/Internals/WCCom/WCConnectionHelper.php (hunk 1 above)
Comment (vedanshujain) [reply src/Internals/WCCom/WCConnectionHelper.php]: Renamed in https://github.com/woocommerce/woocommerce/pull/26932/commits/4500e86198729ce893945a39fe9e22cee3991856 . Although I have kept the same name by using the keyword `as` in WCInstall class because I felt just ConnectionHelper class is pretty generic and can conflict with something in future.

**Comment by vedanshujain** [comment]
@ObliviousHarmony I have added a test for connection helper class as well, but right now it's too coupled with internal implementation. But I guess that's fine because I don't see any other way to test it.

**Review by ObliviousHarmony — APPROVED** [review]
LGTM! For what its worth, I don't feel that the test is too tightly coupled!

**Review by claudiosanches — APPROVED** [review]
Works great!
