### PR TITLE
Ensure `QuantityLimits::limit_to_multiple` receives correct values to prevent fatal errors

### LINKED ISSUE #51340: [Fatal] Uncaught type error in `QuantityLimits::get_add_to_cart_limits()` | `QuantityLimits.php`
While observing the 9.3.1 release (though it does not appear to be new as of 9.3.x) we noticed the following fatal error being logged:

```
PHP Fatal error: Uncaught TypeError: Automattic\WooCommerce\StoreApi\Utilities\QuantityLimits::limit_to_multiple(): Argument #1 ($number) must be of type int, string given
in /.../wp-content/plugins/woocommerce/src/StoreApi/Utilities/QuantityLimits.php on line 58
```

[Relevant code](https://github.com/woocommerce/woocommerce/blob/release/9.3/plugins/woocommerce/src/StoreApi/Utilities/QuantityLimits.php#L58)

<details>
<summary> Backtrace </summary>

```
#0 /.../wp-content/plugins/woocommerce/src/StoreApi/Utilities/QuantityLimits.php(58): 
   Automattic\WooCommerce\StoreApi\Utilities\QuantityLimits->limit_to_multiple('', '', 'ceil')

#1 /.../wp-content/plugins/woocommerce/src/StoreApi/Schemas/V1/ProductSchema.php(487): 
   Automattic\WooCommerce\StoreApi\Utilities\QuantityLimits->get_add_to_cart_limits(Object(WC_Product_Variable))

#2 [internal function]: 
   Automattic\WooCommerce\StoreApi\Schemas\V1\ProductSchema->get_item_response(Object(WC_Product_Variable))

#3 /.../wp-content/plugins/woocommerce/src/Blocks/BlockTypes/AbstractProductGrid.php(114): 
   array_map(Array, Array)

#4 /.../wp-content/plugins/woocommerce/src/Blocks/BlockTypes/AbstractBlock.php(98): 
   Automattic\WooCommerce\Blocks\BlockTypes\AbstractProductGrid->render(Array, '', Object(WP_Block))

#5 /.../wp-includes/class-wp-block.php(519): 
   Automattic\WooCommerce\Blocks\BlockTypes\AbstractBlock->render_callback(Array, '', Object(WP_Block))

#6 /.../wp-includes/blocks.php(2061): 
   WP_Block->render()

#7 /.../wp-includes/blocks.php(2113): 
   render_block(Array)

#8 /.../wp-includes/class-wp-hook.php(324): 
   do_blocks('<!-- wp:paragra...')

#9 /.../wp-includes/plugin.php(205): 
   WP_Hook->apply_filters('<!-- wp:paragra...', Array)

#10 /.../wp-includes/post-template.php(256): 
    apply_filters('the_content', '<!-- wp:paragra...')

#11 /.../wp-content/themes/bam-pro/partials/content-page.php(23): 
    the_content()

#12 /.../wp-includes/template.php(812): 
    require('/srv/htdocs/wp-...')

#13 /.../wp-includes/template.php(745): 
    load_template('/srv/htdocs/wp-...', false, Array)

#14 /.../wp-includes/general-template.php(206): 
    locate_template(Array, true, false, Array)

#15 /.../wp-content/themes/bam-pro/front-page.php(90): 
    get_template_part('partials/conten...', 'page')

#16 /.../wp-includes/template-loader.php(106): 
    include('/srv/htdocs/wp-...')

#17 /.../wp-blog-header.php(19): 
    
    require_once('/.../wp-content/core...')

#18 /.../index.php(17): 
    require('/.../wp-content/core...')

#19 {main} thrown in
    /.../wp-content/plugins/woocommerce/src/StoreApi/Utilities/QuantityLimits.php on line 72
```

</details>

No steps to replicate, as this was captured while monitoring logs.

### PR DESCRIPTION
**Pull request by mikejolley**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Ensure that filtered values are in fact integers before passing to `QuantityLimits::limit_to_multiple` to prevent fatal errors.

Closes #51340

### How to test the changes in this Pull Request:

Should be covered by CI, but to test something that consumes the changed function:

1. Make a product stock managed and give it 10 units in stock
2. Add the product to cart
3. Go to the cart block and increase the qty using the step + button. You should be able to increase qty to 10 and no more.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce/src/StoreApi/Utilities/QuantityLimits.php [hunk 1]
```diff
@@ -50,9 +50,9 @@ public function get_cart_item_quantity_limits( $cart_item ) {
 	 * @return array
 	 */
 	public function get_add_to_cart_limits( \WC_Product $product ) {
-		$multiple_of = $this->filter_value( 1, 'multiple_of', $product );
-		$minimum     = $this->filter_value( 1, 'minimum', $product );
-		$maximum     = $this->filter_value( $this->get_product_quantity_limit( $product ), 'maximum', $product );
+		$multiple_of = (int) $this->filter_value( 1, 'multiple_of', $product );
+		$minimum     = (int) $this->filter_value( 1, 'minimum', $product );
+		$maximum     = (int) $this->filter_value( $this->get_product_quantity_limit( $product ), 'maximum', $product );
```
Comment (senadir) [inline plugins/woocommerce/src/StoreApi/Utilities/QuantityLimits.php]: This only casts, but does it check if someone returned I dunno a random abc string? This would evaluate to 0, which works fine for minimum but would break multiple and maximum

Comment (mikejolley) [reply plugins/woocommerce/src/StoreApi/Utilities/QuantityLimits.php]: This is true if the filter is misused. The filter docblock and passed value is int. The error logs showed that someone filtered it to return `''` empty string. I guess we could add another layer of value forcing.

**Comment by mikejolley** [comment]
@senadir Its a bit more complicated now but I added some basic enforcing of min/max values and more explicit types on the filters.

**Review by senadir — APPROVED** [review]

File: plugins/woocommerce/src/StoreApi/Utilities/QuantityLimits.php [hunk 2]
```diff
@@ -30,10 +30,16 @@ public function get_cart_item_quantity_limits( $cart_item ) {
...
+		$multiple_of = $this->filter_numeric_value( 1, 'multiple_of', $cart_item );
+		$minimum     = $this->filter_numeric_value( 1, 'minimum', $cart_item );
+		$maximum     = $this->filter_numeric_value( $this->get_product_quantity_limit( $product ), 'maximum', $cart_item );
+		$editable    = $this->filter_boolean_value( ! $product->is_sold_individually(), 'editable', $cart_item );
+
+		// Minimum must be at least 1.
+		$minimum = max( $minimum, 1 );
+
+		// Maximum must be at least minimum.
+		$maximum = max( $maximum, $minimum );
```
Comment (senadir) [inline plugins/woocommerce/src/StoreApi/Utilities/QuantityLimits.php:42]: Thank you for this!
