### PR TITLE
Fix Stock status behavior

### LINKED ISSUE #53460: Incorrect Stock Status in Product Collection block
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

The stock status displayed on the product page doesn’t match the stock status shown in the `Product Collection` block for products with notified backorders.

### Expected behavior

The stock status should be the same on the `Product collection` block we show at the front end and on the product page.

### Steps to reproduce

1. Create a product.
2. Set the stock option to `Allow, but notify customer` for a product.
Image
`Allow, but notify customer` is selected and `quantity` is 0
3. Set the `quantity` to 0.
4. Go to Pages > Add New Page and create a page with a `Product Collection` block (don't add filters).

The product page will show: `Available on backorder`.
Image

But the same product in the collection will say: `2 left in stock`
Image

Notice that the quantity is also wrong.

### WordPress Environment

It's happening on `trunk`.

### Isolating the problem

- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by octaedro**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

This PR modifies the Stock Indicator block to ensure it matches the product stock status.

Currently, some product stock statuses don't match between the `Product Collection` front end and the product page.

Errors:

**Simple Product**
| Status | Collection Frontend | Product page |
|--------|--------|--------|
| In stock / No stock management| Screenshot 2024-12-05 at 5 11 40 PM | Screenshot 2024-12-05 at 5 12 08 PM |
| Quantity 0 / Allow backorders (no notify) / Stock management | Screenshot 2024-12-05 at 5 15 45 PM | Screenshot 2024-12-05 at 5 12 08 PM |
| Quantity 1 / No allow backorders / Stock management | Screenshot 2024-12-05 at 5 18 01 PM | Screenshot 2024-12-05 at 5 17 43 PM |
| Quantity 1 / Allow backorders (notify) / Stock management | Screenshot 2024-12-05 at 5 20 59 PM | Screenshot 2024-12-05 at 5 20 46 PM | 
| Quantity 1 / Allow backorders (no notify) / Stock management  | Screenshot 2024-12-05 at 5 23 17 PM | Screenshot 2024-12-05 at 5 23 02 PM | 

Closes #53460.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Create a simple product and keep the product editor open. 

Screenshot 2024-12-10 at 12 41 44 PM

2. In another tab, go to Pages > Add New Page and add a `Product collection` block.
3. Choose `Hand-Picked Products` and select the product you just created.
4. Now add a `Stock indicator` block inside the product you picked.

Screenshot 2024-12-10 at 10 40 10 AM

5. Save the page and view it. The stock indicator may be shown (depending on the inventory details described above). E.g.: The indicator won't be visible for simple products `In stock` and without `Stock management`. 
6. Now, view the product page and verify there is no difference between what we show in both stock indicators (inside the Product Collection and the product page).
7. Verify the indicator always matches and consider [this change](https://github.com/woocommerce/woocommerce/pull/53462#discussion_r1872177154).

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce/src/Blocks/BlockTypes/ProductStockIndicator.php [hunk 1]
```diff
@@ -78,42 +76,44 @@ protected static function getTextBasedOnStock( $is_in_stock, $is_low_stock, $low
...
 		$classes_and_styles = StyleAttributesUtils::get_classes_and_styles_by_attributes( $attributes );
 
 		$classnames  = isset( $classes_and_styles['classes'] ) ? ' ' . $classes_and_styles['classes'] . ' ' : '';
-		$classnames .= ! $is_in_stock ? ' wc-block-components-product-stock-indicator--out-of-stock ' : '';
-		$classnames .= $is_in_stock ? ' wc-block-components-product-stock-indicator--in-stock ' : '';
-		$classnames .= $is_low_stock ? ' wc-block-components-product-stock-indicator--low-stock ' : '';
-		$classnames .= $is_on_backorder ? ' wc-block-components-product-stock-indicator--available-on-backorder ' : '';
+		$classnames .= sprintf( ' wc-block-components-product-stock-indicator--%s', $availability['class'] );
+
+		if ( empty( $content ) && $is_low_stock ) {
```
[the remark this answers is not in the document]
Comment (octaedro) [reply plugins/woocommerce/src/Blocks/BlockTypes/ProductStockIndicator.php]: This change was added to modify the text `(can be back ordered)` in product collections. Currently, we present a shorter version of the text; otherwise, it would take up two lines:

| in two lines | in one line |
|--------|--------|
| Screenshot 2024-12-05 at 4 33 21 PM | Screenshot 2024-12-05 at 4 28 36 PM |

File: plugins/woocommerce/src/Blocks/BlockTypes/ProductStockIndicator.php [hunk 2]
```diff
@@ -78,42 +47,46 @@ protected static function getTextBasedOnStock( $is_in_stock, $is_low_stock, $low
...
 		$classnames  = isset( $classes_and_styles['classes'] ) ? ' ' . $classes_and_styles['classes'] . ' ' : '';
-		$classnames .= ! $is_in_stock ? ' wc-block-components-product-stock-indicator--out-of-stock ' : '';
-		$classnames .= $is_in_stock ? ' wc-block-components-product-stock-indicator--in-stock ' : '';
-		$classnames .= $is_low_stock ? ' wc-block-components-product-stock-indicator--low-stock ' : '';
-		$classnames .= $is_on_backorder ? ' wc-block-components-product-stock-indicator--available-on-backorder ' : '';
+		$classnames .= sprintf( ' wc-block-components-product-stock-indicator--%s', $availability['class'] );
+
+		$is_backorder_notification_visible = $product->is_in_stock() && $product->backorders_require_notification();
+
+		if ( empty( $content ) && $is_backorder_notification_visible ) {
```
Comment (octaedro) [inline plugins/woocommerce/src/Blocks/BlockTypes/ProductStockIndicator.php:73]: When `$content` is empty, we assume we are displaying a `Product Collection`.

Comment (octaedro) [reply plugins/woocommerce/src/Blocks/BlockTypes/ProductStockIndicator.php:73]: This change was added to modify the text `(can be back ordered)` in product collections. Currently, we present a shorter version of the text; otherwise, it would take up two lines:

| in two lines | in one line |
|--------|--------|
| Screenshot 2024-12-05 at 4 33 21 PM | Screenshot 2024-12-05 at 4 28 36 PM |

File: plugins/woocommerce/src/Blocks/BlockTypes/ProductStockIndicator.php [hunk 3]
```diff
@@ -78,42 +56,46 @@ protected static function getTextBasedOnStock( $is_in_stock, $is_low_stock, $low
...
 		$classnames  = isset( $classes_and_styles['classes'] ) ? ' ' . $classes_and_styles['classes'] . ' ' : '';
-		$classnames .= ! $is_in_stock ? ' wc-block-components-product-stock-indicator--out-of-stock ' : '';
-		$classnames .= $is_in_stock ? ' wc-block-components-product-stock-indicator--in-stock ' : '';
-		$classnames .= $is_low_stock ? ' wc-block-components-product-stock-indicator--low-stock ' : '';
-		$classnames .= $is_on_backorder ? ' wc-block-components-product-stock-indicator--available-on-backorder ' : '';
+		$classnames .= sprintf( ' wc-block-components-product-stock-indicator--%s', $availability['class'] );
+
+		$is_backorder_notification_visible = $product->is_in_stock() && $product->backorders_require_notification();
+
+		if ( empty( $content ) && $is_backorder_notification_visible && $total_stock > 0 ) {
```
Comment (octaedro) [inline plugins/woocommerce/src/Blocks/BlockTypes/ProductStockIndicator.php:87]: When `$content` is empty, we assume we are displaying a `Product Collection`.

Comment (octaedro) [reply plugins/woocommerce/src/Blocks/BlockTypes/ProductStockIndicator.php:87]: This change was added to modify the text `(can be back ordered)` in product collections. Currently, we present a shorter version of the text; otherwise, it would take up two lines:

| in two lines | in one line |
|--------|--------|
| Screenshot 2024-12-05 at 4 33 21 PM | Screenshot 2024-12-05 at 4 28 36 PM |

**Comment by tjcafferkey** [comment]
@octaedro perhaps I am doing something wrong, but I am not seeing the Stock Indicator block get rendered on the frontend for some status' such as `In stock / No stock management`. I have built `trunk` for comparison and it works here. Can you let me know if its an issue with something I am doing or a regression in the PR?

Also, I think it might be worth mentioning in the testing steps that you need to add the Stock Indicator block once you've added the Product Collections block.

**Comment by octaedro** [comment]
Hi @tjcafferkey, 

> @octaedro perhaps I am doing something wrong, but I am not seeing the Stock Indicator block get rendered on the frontend for some status' such as In stock / No stock management. I have built trunk for comparison and it works here. Can you let me know if its an issue with something I am doing or a regression in the PR?

Oh, that is interesting. When I view a simple product in `trunk` with stock status: `In stock / No stock management`, I don't see the `In stock` message either. AFAIU, that's the expected behavior. Could you share your configuration so I can take a closer look?

> Also, I think it might be worth mentioning in the testing steps that you need to add the Stock Indicator block once you've added the Product Collections block.

💯 I just added it—thanks for pointing that out!

File: plugins/woocommerce/changelog/fix-53460_errors_in_stock_status [hunk 4]
```diff
@@ -0,0 +1,4 @@
+Significance: minor
+Type: fix
+
+Fix Stock status behavior #53462
```
Comment (Aljullu) [inline plugins/woocommerce/changelog/fix-53460_errors_in_stock_status]: I would try to make this a bit more explanatory, like:

```suggestion
Make Stock Indicator block behavior consistent between the Product Collection block and the Single Product template
```

(or something along these lines :sweat_smile: )

File: plugins/woocommerce/src/Blocks/BlockTypes/ProductStockIndicator.php [hunk 5]
```diff
@@ -78,42 +56,46 @@ protected static function getTextBasedOnStock( $is_in_stock, $is_low_stock, $low
...
```
Comment (Aljullu) [inline plugins/woocommerce/src/Blocks/BlockTypes/ProductStockIndicator.php:87]: In these two lines first we check if `$product->is_in_stock()` and then if `$total_stock > 0`. Do you know if both of them are needed?

File: plugins/woocommerce/src/Blocks/BlockTypes/ProductStockIndicator.php [hunk 6]
```diff
@@ -39,36 +39,14 @@ protected function get_block_type_uses_context() {
 	}
 
 	/**
-	 * Get stock text based on stock. For example:
-	 * - In stock
-	 * - Out of stock
-	 * - Available on backorder
-	 * - 2 left in stock
+	 * Get the product types that are allowed in the editor.
```
Comment (Aljullu) [inline plugins/woocommerce/src/Blocks/BlockTypes/ProductStockIndicator.php]: Should we update this comment? It's not 100% clear to me what the "in the editor" means here. :thinking:

File: plugins/woocommerce/src/Blocks/BlockTypes/ProductStockIndicator.php [hunk 7]
```diff
@@ -78,42 +56,46 @@ protected static function getTextBasedOnStock( $is_in_stock, $is_low_stock, $low
 	 * @return string Rendered block type output.
 	 */
 	protected function render( $attributes, $content, $block ) {
-		if ( ! empty( $content ) ) {
-			parent::register_block_type_assets();
-			$this->register_chunk_translations( [ $this->block_name ] );
-			return $content;
-		}
```
Comment (Aljullu) [inline plugins/woocommerce/src/Blocks/BlockTypes/ProductStockIndicator.php]: Not a big deal, but I think we should keep this. It was preventing all the logic to run unnecessarily in the _All Products_ block.

File: plugins/woocommerce/src/Blocks/BlockTypes/ProductStockIndicator.php [hunk 8]
```diff
@@ -39,36 +39,14 @@ protected function get_block_type_uses_context() {
...
-				$low_stock_amount
-			);
-		} elseif ( $is_on_backorder ) {
-			return __( 'Available on backorder', 'woocommerce' );
-		} elseif ( $is_in_stock ) {
-			return __( 'In stock', 'woocommerce' );
-		} else {
-			return __( 'Out of stock', 'woocommerce' );
-		}
+	protected function product_types_without_stock_indicator() {
```
Comment (Aljullu) [inline plugins/woocommerce/src/Blocks/BlockTypes/ProductStockIndicator.php]: Nit: Personal preference, but for functions and methods, I prefer it they start with a verb, so in this case this could be `get_product_types_without_stock_indicator()`. Alternatively, this could be converted to a property of the PHP class.

**Review by Aljullu — APPROVED** [review]
LGTM! Thanks for investigating all the inconsistencies we had in this block. I left some minor comments inline, but pre-approving from my end.

File: plugins/woocommerce/src/Blocks/BlockTypes/ProductStockIndicator.php (hunk 5 above)
Comment (octaedro) [reply plugins/woocommerce/src/Blocks/BlockTypes/ProductStockIndicator.php:87]: Yes, it's a little confusing, but it's possible to have `$product->is_in_stock()` as `true` and  `$total_stock > 0` as `false`, because we are not managing stock.

File: plugins/woocommerce/src/Blocks/BlockTypes/ProductStockIndicator.php (hunk 6 above)
Comment (octaedro) [reply plugins/woocommerce/src/Blocks/BlockTypes/ProductStockIndicator.php]: Done in [3e7e20b](https://github.com/woocommerce/woocommerce/pull/53462/commits/3e7e20b6c418b4bb7450d8955440f76eae0d3f29)!

File: plugins/woocommerce/src/Blocks/BlockTypes/ProductStockIndicator.php (hunk 7 above)
Comment (octaedro) [reply plugins/woocommerce/src/Blocks/BlockTypes/ProductStockIndicator.php]: Done in [aefebbe](https://github.com/woocommerce/woocommerce/pull/53462/commits/aefebbeed7936ec68f0ebc583ed279892d893e44).

File: plugins/woocommerce/src/Blocks/BlockTypes/ProductStockIndicator.php (hunk 8 above)
Comment (octaedro) [reply plugins/woocommerce/src/Blocks/BlockTypes/ProductStockIndicator.php]: Good call! Done in [fe26112](https://github.com/woocommerce/woocommerce/pull/53462/commits/fe261120ba504f9ac8491460489bdf5dae87a457)!

File: plugins/woocommerce/src/Blocks/BlockTypes/ProductStockIndicator.php (hunk 5 above)
Comment (Aljullu) [reply plugins/woocommerce/src/Blocks/BlockTypes/ProductStockIndicator.php:87]: Oh, ok. Makes sense. Thanks for explaining it!
