### PR TITLE
PluginUtil: Add method to get active valid plugins

### LINKED ISSUE #48132: 'active_plugins' doesn't mean plugin file exists
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

PHP notice 

>file_get_contents(...): failed to open stream: No such file or directory

from `$data                  = get_plugin_data( WP_PLUGIN_DIR . '/' . $plugin );` in 
class-wc-rest-system-status-v2-controller.php

because the plugin might still be in the option but the file doesn't exist anymore in that point in time e.g. bc the directory was removed in the meantime.

### Expected behavior

No notice

### Actual behavior

Notice

### Steps to reproduce

Irrelevant to fix it

### WordPress Environment

Irrelevant

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by coreymckrill**
### Changes proposed in this Pull Request:

When getting a list of active plugins directly from the options table, you can run into an error if you try to then access one of the plugin files if it doesn't actually exist. WP Core has a method that verifies that the files exist before returning the list. But it's marked as a "private" method, which means it could change and break backcompat. That seems very unlikely, though, so we're using the method (it was already in use actually), but putting in some safeguards so we can detect if a backcompat issue arises.

Fixes #48132

### How to test the changes in this Pull Request:

Replicate the issue on trunk:

1. Ensure that `WP_DEBUG` and `WP_DEBUG_LOG` constants are set to true.
1. Have at least two plugins active on your test site.
1. Make a request to `wc/v3/system_status`. Filter the response to view the `active_plugins` property, and note which plugins are shown.
1. Now in the filesystem, remove or rename one of the active plugins (this must be done outside of a WordPress context so that the cached values don't get updated automatically).
1. Clear the transient that stores the current active plugins list for the System Status tool: `wp transient delete --all`
1. Now make another request to `wc/v3/system_status`. There may not be a difference in the list of active plugins. But if you check your WP debug log file, you should see an error message like the following: `PHP Warning:  file_get_contents(/var/www/html/wp-content/plugins/wc-smooth-generator/wc-smooth-generator.php): Failed to open stream: No such file or directory in /var/www/html/wp-includes/functions.php on line 6852`

On this PR branch:

1. Follow the same steps as above. This time, when making the second request to `wc/v3/system_status`, you should only see the active plugins that haven't been renamed/deleted, and there shouldn't be any new PHP warnings in the log file.
2. Try the same thing on a multisite network, with network activated plugins.

### CODE REVIEW

File: plugins/woocommerce/includes/rest-api/Controllers/Version2/class-wc-rest-system-status-v2-controller.php [hunk 1]
```diff
@@ -1044,16 +1044,11 @@ public function get_active_plugins() {
...
 			}
 
-			$active_plugins = (array) get_option( 'active_plugins', array() );
-			if ( is_multisite() ) {
-				$network_activated_plugins = array_keys( get_site_option( 'active_sitewide_plugins', array() ) );
-				$active_plugins            = array_merge( $active_plugins, $network_activated_plugins );
-			}
-
-			$active_plugins_data = array();
+			$active_valid_plugins = wc_get_container()->get( PluginUtil::class )->get_active_and_valid_plugins();
```
Comment (jorgeatorres) [inline plugins/woocommerce/includes/rest-api/Controllers/Version2/class-wc-rest-system-status-v2-controller.php]: We were including network-activated plugins here too, but `get_active_and_valid_plugins()` doesn't. Should we also create a wrapper method for `wp_get_active_network_plugins()`?

**Review by jorgeatorres — CHANGES_REQUESTED** [review]
Hey @coreymckrill!

Thanks for working on this. It tested well on my machine but I did some testing using WPMU on JN and noticed that we were no longer including network-activated plugins in the results. I left a comment about it. Could you please check when you have the chance?

Thanks again!

File: plugins/woocommerce/includes/rest-api/Controllers/Version2/class-wc-rest-system-status-v2-controller.php (hunk 1 above)
Comment (coreymckrill) [reply plugins/woocommerce/includes/rest-api/Controllers/Version2/class-wc-rest-system-status-v2-controller.php]: 🤔 Oh hmm, I thought this method was still including network-activated plugins, but I didn't test. Thank you for doing so! I'll take another look.

Comment (coreymckrill) [reply plugins/woocommerce/includes/rest-api/Controllers/Version2/class-wc-rest-system-status-v2-controller.php]: 🤔 I'm trying to think of a case where we _wouldn't_ want to include active network plugins, and I'm drawing a blank. What if we change the helper function introduced in this PR to combine `get_active_and_valid_plugins` and `wp_get_active_network_plugins` into one list? That would probably actually be better for the usage in `woocommerce_is_active_in_current_site` anyway...

Comment (coreymckrill) [reply plugins/woocommerce/includes/rest-api/Controllers/Version2/class-wc-rest-system-status-v2-controller.php]: Ok, in 37c871b0ac1779282ccc47e71da1b1b8beae8c6c I updated the method to combine `wp_get_active_and_valid_plugins` and `wp_get_active_network_plugins`.

Comment (jorgeatorres) [reply plugins/woocommerce/includes/rest-api/Controllers/Version2/class-wc-rest-system-status-v2-controller.php]: > I'm trying to think of a case where we wouldn't want to include active network plugins, and I'm drawing a blank.

Yep. I agree. If, for any reason, that time comes, we can maybe supplement the function with an arg to filter results.

**Review by jorgeatorres — APPROVED** [review]
LGTM. Thank you @coreymckrill!

I also tested the flow that installs the Legacy REST API plugin to make sure it didn't break (not that there were any reasons).
