### PR TITLE
Basic range download handling for Force download.

### LINKED ISSUE #19640: Downloading audio files on iOS, if the download is "forced" the audio is mistaken for a Live Broadcast
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Create a Downloadable product with an audio file
2. Go to **WooCommerce > Settings > Products > Downloadable** products and make sure that the file download method is set to `Force downloads`.
3. Process an order of your Downloadable product.
4. From iOS, login to your account in the site, go to **My Account > Downloads** and try to open the audio file.

## Expected/actual behavior

When I follow those steps, the audio opens in a new window and appears to be a "Live Broadcast". This means that I cannot fast forward or rewind the audio. After a minute or so, the audio stops and restarts. It never finishes all the way to the end.

I was expecting to be able to control the timer in the audio, and for the audio to play completely and not stop half way through.

Image Link: http://cld.wthms.co/ev5XiK

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

### PR DESCRIPTION
**Pull request by peterfabian**
### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

This change adds support for HTTP_RANGE requests (used by iOS devices) to `Force download` method.
One thing to note is that range request downloads are not logged (so that they are not counted as multiple downloads). The most reasonable option in my view would be to add extra column(s) to table `wp_wc_download_log`, e.g. columns `start` and `length` and then exclude range request log entries when counting number of downloads. 
Not sure how feasible db changes are mid-release-cycle, so I went for easier option for now--ignoring ranged downloads from the log. 
As the initial request from an iOS device is a normal (non-range) request, the download should be logged once anyway.
 
Closes #19640 .

### How to test the changes in this Pull Request:

1. Create a downloadable virtual product which contains larger audio or video file, e.g. an mp3 file.
2. Buy the product, go to My account > Downloads.
3. Try to download the mp3 file on iPhone/iPad.
4. Audio only plays first ~2 minutes, then starts from the beginning again, it does not indicate the length and does not allow seeking.
5. Apply this branch.
6. See the audio now shows correct length and allows seeking.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable? No, it's a bit tricky as headers interfere with phpunit's output and e2e tests don't run on iOS device.
* [x] Have you successfully ran tests with your changes locally?

### Changelog entry

> Added support for HTTP_RANGE requests (used by iOS devices) to `Force download` method.

### CODE REVIEW

**Comment by tiagonoronha** [comment]
Tested and can confirm it's no longer showing up as a "Live Broadcast".

File: includes/class-wc-customer-download.php [hunk 1]
```diff
@@ -290,15 +290,21 @@ public function set_download_count( $value ) {
 	 * @throws Exception When permission ID is invalid.
 	 * @param int    $user_id         Id of the user performing the download.
 	 * @param string $user_ip_address IP Address of the user performing the download.
+	 * @param bool   $range_download  Whether the download is a partial/range download.
 	 */
-	public function track_download( $user_id = null, $user_ip_address = null ) {
+	public function track_download( $user_id = null, $user_ip_address = null, $range_download = false ) {
```
Comment (mikejolley) [inline includes/class-wc-customer-download.php]: If track_download does not run for `range_download` (which I agree is the correct handling) why is this passed through?

Could this check not go in the download handler?

Comment (peterfabian) [reply includes/class-wc-customer-download.php]: Good point, I initially thought that we might be updating the ranges in the `wp_wc_download_log`, but since that's not the way it ended up, it can be removed altogether.

**Review by mikejolley — APPROVED** [review]
Works for me now 👍 

@claudiulodro you should check too as this is larger than other PRs.

**Comment by claudiulodro** [comment]
This looks good to me also. Works well in my testing and I don't notice anything wrong in the code.

**Review by claudiulodro — APPROVED** [review]
