### PR TITLE
[Launch Your Store] Fix failed to load coming-soon resources

### LINKED ISSUE #47072: Failed to load resource: coming-soon.css 404
The file coming-soon.css is not found and causes 404 errors. 

p1714492243304479-slack-C01SFMVEYAK

```
GET http://localhost:8885/wp-content/plugins/woocommerce/assets/client/blocks/coming-soon.css?ver=wc-9.0.0 net::ERR_ABORTED 404 (Not Found)

GET http://localhost:8885//wp-content/plugins/woocommerce/assets/client/blocks/coming-soon-frontend.js?ver=wc-9.0.0](http://localhost:8885/mywordpress/wp-content/plugins/woocommerce/assets/client/blocks/coming-soon-frontend.js?ver=wc-9.0.0"
````

No 404 error should be thrown when coming soon page is loaded.

### PR DESCRIPTION
**Pull request by chihsuan**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes https://github.com/woocommerce/woocommerce/issues/47072

We created a ComingSoon Block type for the Launch Your Store feature. The block defaults to loading the coming-soon CSS/JS resources. However, we don't have those resources in the [coming-soon block](https://github.com/woocommerce/woocommerce/tree/trunk/plugins/woocommerce-blocks/assets/js/blocks/coming-soon) and it causes 404 errors.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Enable `launch-your-store` feature flag.
2. Go to `WooCommerce > Settings > Site Visibility` and enable `Coming soon` checkbox and save if it's not already enabled.
3. Open dev tools
4. Go to Frontend in incognito mode and check if there are no 404 errors for coming-soon resources.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce/src/Blocks/BlockTypes/ComingSoon.php [hunk 1]
```diff
@@ -5,18 +5,39 @@
...
-		 * It is necessary to register and enqueue assets during the render phase because we want to load assets only if the block has the content.
-		 */
+	/**
+	 * It is necessary to register and enqueue assets during the render phase because we want to load assets only if the block has the content.
+	 */
 	protected function register_block_type_assets() {
 			parent::register_block_type_assets();
 			$this->register_chunk_translations( [ $this->block_name ] );
 	}
+
```
Comment (ilyasfoo) [inline plugins/woocommerce/src/Blocks/BlockTypes/ComingSoon.php:22]: Nit
```suggestion
```

**Review by ilyasfoo — APPROVED** [review]
Tests well, LGTM!

**Review by psealock — APPROVED** [review]
Testing well and code looks good!
