### PR TITLE
[Checkout blocks] Fix display of products with a 0 price 

### LINKED ISSUE #60533: Checkout block: free products prevent subtotal showing
## **Describe the bug**

The Order summary > Subtotal field doesn't load on a block-based checkout page when only free products are in the cart. It shows a loading bar instead.

## **To Reproduce**

1. Create a £0.00 product
2. Add it to the cart
3. Visit a block-based checkout page
4. Notice how the Subtotal doesn't render but shows a loading image instead.

## **Expected behavior**

Up to WC 10.0.4 it still shows £0.00 as expected, but in WC 10.1.x the issues starts.

## **Screenshots**

free-product-in-wc-10.0.4.png - Subtotal shows £0.00
free-product-in-wc-10.1.x.png - Subtotal shows grey bar

## Environment

Please fill out any of the below that applies

**Operating System/Device**

- [ ] Windows
- [ ] MacOS
- [ ] Linux
- [ ] iPhone
- [ ] Samsung
- [ ] Other (add in additional context field)

**Version:** Add the Desktop OS and/or Device version(s) here

**Browser**

- [ ] Desktop Edge
- [ ] Desktop Chrome/Chromium
- [ ] Desktop Safari
- [ ] Mobile Edge
- [ ] Mobile Chrome/Chromium
- [ ] Mobile Safari
- [ ] Other (add in additional context field)

**Version:** Add the browser version(s) here.

## **Additional context**

This issue will be published publicly, add system status report and internal links to Slack thread after issue created.

### PR DESCRIPTION
**Pull request by ralucaStan**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

This PR fixes the display of the Skeleton for Subtotals equal to 0.
Additionally, I've fixed the display in the Cart item line for products with a price 0 and added some tests that would have prevented this bug.

Closes https://linear.app/a8c/issue/WOOPLUG-5394/checkout-block-free-products-prevent-subtotal-showing
Closes https://github.com/woocommerce/woocommerce/issues/60533

(For Bug Fixes) Bug introduced in PR https://github.com/woocommerce/woocommerce/pull/58782#discussion_r2154382928

### Screenshots or screen recordings:

| Before | After |
| ------ | ----- |
|   Screenshot 2025-08-22 at 10 14 15 |   Screenshot 2025-08-22 at 10 13 44   |

| Before | After |
| ------ | ----- |
|   Screenshot 2025-08-22 at 10 13 10 |    Screenshot 2025-08-22 at 10 12 57  |

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Create a product with 0 as a price
2. Add the product to cart
3. Go to Cart and notice the Subtotal is showing 0
4. Go to Checkout and noticed the Subtotal is 0

5. Add another product (with a price) to the cart
6. Go to the checkout block
7. In the cart summary notice both product show prices

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce/client/blocks/assets/js/base/components/product-price/index.tsx [hunk 1]
```diff
@@ -332,7 +332,7 @@ const ProductPrice = ( {
 				priceStyle={ priceStyle }
 			/>
 		);
-	} else if ( price ) {
+	} else if ( price || price === 0 ) {
```
Comment (ralucaStan) [inline plugins/woocommerce/client/blocks/assets/js/base/components/product-price/index.tsx:335]: This is needed to show 0 prices in Cart line items for the Checkout cart summary

File: plugins/woocommerce/client/blocks/packages/components/totals/item/index.tsx [hunk 2]
```diff
@@ -61,7 +61,7 @@ const TotalsItem = ( {
 				{ label }
 			</span>
 			<DelayedContentWithSkeleton
-				isLoading={ ! value || showSkeleton }
```
Comment (ralucaStan) [inline plugins/woocommerce/client/blocks/packages/components/totals/item/index.tsx:64]: The visibility of the skeleton should only be dependent on the `showSkeleton` prop. 
The component can handle null, undefined, {}.

File: plugins/woocommerce/client/blocks/assets/js/base/components/product-price/index.tsx (hunk 1 above)
Comment (opr) [reply plugins/woocommerce/client/blocks/assets/js/base/components/product-price/index.tsx:335]: I feel that this would be helpful as an inline comment too

**Review by opr — APPROVED** [review]
Thanks it's working for me 😎

**Comment by ralucaStan** [comment]
Thank you, Thomas! 🚀
