### PR TITLE
Ensure multi-line order notes display correctly

### LINKED ISSUE #54452: Order note new lines are stripped in order emails
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

New lines are stripped from the customer note when sending an order-related email.

Introduced in Automattic/woocommerce#331

### Expected behavior

When a customer provides an order note with new lines, such as
```
This is 
a
multi-line note.
```
it will be rendered like this in order emails.

### Actual behavior

Now, it's rendered like this: 
```
This is a multi-line note.
```

### Steps to reproduce

1. Wait for #54441 to be merged, or check out the branch (it's much easier to reproduce this without sending an email).
2. Enable the `Email improvements` feature in **WooCommerce > Settings > Advanced > Feature**.
3. Go to **WooCommerce > Settings > Emails**.
4. In the email preview, observe that the customer note doesn't have new lines.
5. Changing [this line](https://github.com/woocommerce/woocommerce/blob/b377e757856cd74160ac97b4bf6eea7d9d201183/plugins/woocommerce/templates/emails/email-order-details.php#L81) to allow `<br>` (`wp_kses( nl2br( wptexturize( $order->get_customer_note() ) ), array( 'br' => array() ) );` fixes the issue and new lines are present.
6. It's likely, that this issue is present in other places where order notes are rendered.

Current state:
Image

Fixed state:
Image

### WordPress Environment

<details><summary>System Status Report</summary>

```
### WordPress Environment ###

WordPress address (URL): [Redacted]
Site address (URL): [Redacted]
WC Version: 9.7.0-dev
Legacy REST API Package Version: The Legacy REST API plugin is not installed on this site.
Action Scheduler Version: ✔ 3.9.0
Log Directory Writable: ✔
WP Version: 6.7.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.54 (Debian)
PHP Version: 7.4.33
PHP Post Max Size: 1 GB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.74.0
OpenSSL/1.1.1n

SUHOSIN Installed: –
MySQL Version: 11.4.4-MariaDB-ubu2404
Max Upload Size: 1 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

[REDACTED]

### Post Type Counts ###

attachment: 29
mailpoet_page: 1
page: 9
post: 3
product: 19
product_variation: 7
revision: 1
shop_order_placehold: 2
wp_font_face: 33
wp_font_family: 12
wp_global_styles: 1
wp_navigation: 1

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (2) ###

Database Manager - WP Adminer: by Pexle Chris – 3.1.1
WooCommerce: by Automattic – 9.7.0-dev

### Inactive Plugins (2) ###

Akismet Anti-spam: Spam Protection: by Automattic - Anti-spam Team – 5.3.5
Hello Dolly: by Matt Mullenweg – 1.7.2

### Settings ###

Legacy API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: 
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 29 KB

### WC Pages ###

Shop base: #5 - /shop/
Cart: #6 - /cart/ -  Contains the woocommerce/cart block
Checkout: #7 - /checkout/ -  Contains the woocommerce/checkout block
My account: #8 - /my-account/ -  Contains the [woocommerce_my_account] shortcode
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty-Four
Version: 1.3
Author URL: https://wordpress.org
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
Theme type: Block theme
WooCommerce Support: ❌ Not declared

### Templates ###

Overrides: /var/www/html/wp-content/plugins/woocommerce/templates/block-notices/error.php
/var/www/html/wp-content/plugins/woocommerce/templates/block-notices/notice.php
/var/www/html/wp-content/plugins/woocommerce/templates/block-notices/success.php


### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
experimental-blocks
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
minified-js
mobile-app-banner
onboarding
onboarding-tasks
pattern-toolkit-full-composability
payment-gateway-suggestions
product-custom-fields
printful
remote-inbox-notifications
remote-free-extensions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page
async-product-editor-category-field
launch-your-store
blueprint
add-to-cart-with-options-stepper-layout
blockified-add-to-cart

Disabled Features: product-data-views
coming-soon-newsletter-template
product-pre-publish-modal
settings
product-editor-template-system
reactify-classic-payments-settings
use-wp-horizon

Daily Cron: ✔ Next scheduled: 2025-01-14 12:50:56 +00:00
Options: ✔
Notes: 72
Onboarding: skipped

### Action Scheduler ###

Complete: 69
Oldest: 2024-12-16 07:32:53 +0000
Newest: 2025-01-13 15:52:14 +0000

Failed: 288
Oldest: 2024-10-28 15:45:57 +0000
Newest: 2025-01-14 09:57:14 +0000

Pending: 5
Oldest: 2025-01-14 09:59:14 +0000
Newest: 2025-01-20 13:31:37 +0000


### Status report information ###

Generated at: 2025-01-14 09:58:04 +00:00
```
</details>

### Isolating the problem

- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by opr**
### Changes proposed in this Pull Request:

This PR updates the uses of `wp_kses` when filtering the order notes to allow `<br />` tags through. This allows mutli-line order notes to be submitted, whereas previously they would become a single line.

There are no security implications of allowing this linebreak character through. 

Added a new PHP unit test to check this functionality is working correctly.

Closes #54452

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Add an item to your cart and go to the Checkout block.
2. Fill in your details and at the bottom check the `Add a note to your order` box.
3. Enter some text in this box using the return key to create multiple lines of text.
4. Place the order.
5. Verify the multi-line note is visible on the order confirmation screen.
6. Verify the multi-line note is visible on the order dashboard in WP Admin.
7. Verify the multi-line note is visible on the order confirmation emails sent both to the merchant and the shopper.
8. Repeat the test using the Shortcode checkout.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce/tests/php/includes/class-wc-checkout-test.php [hunk 1]
```diff
@@ -97,6 +97,34 @@ public function test_order_notes() {
...
+
+		$content = wc_get_template_html(
+			'order/order-details.php',
+			array(
+				'order_id'       => $result,
+				'show_downloads' => false,
+			)
+		);
+		// The \n are necessary because those characters actually exist in the template.
+		$this->assertStringContainsString( 'A string<br />with linebreaks<br />in it.', preg_replace('/[\t|\\n]+/', '', $content) );
```
Comment (opr) [inline plugins/woocommerce/tests/php/includes/class-wc-checkout-test.php]: Is the `preg_replace` fine here? he template outputs a bunch of tabs and spaces so I think it's easier to reason with this test if we replace them, rather than trying to account for them.

File: plugins/woocommerce/templates/emails/email-order-details.php
Comment (opr) [inline plugins/woocommerce/templates/emails/email-order-details.php:1]: This doesn't need a template bump, the structure hasn't changed

File: plugins/woocommerce/templates/emails/plain/email-order-details.php
Comment (opr) [inline plugins/woocommerce/templates/emails/plain/email-order-details.php:1]: This doesn't need a template bump, the structure hasn't changed

File: plugins/woocommerce/templates/order/order-details.php
Comment (opr) [inline plugins/woocommerce/templates/order/order-details.php:1]: This doesn't need a template bump, the structure hasn't changed

File: plugins/woocommerce/tests/php/includes/class-wc-checkout-test.php [hunk 2]
```diff
@@ -97,6 +97,34 @@ public function test_order_notes() {
...
 
+	/**
+	 * @testdox the customer notes can have linebreaks.
+	 */
+	public function test_order_notes_linebreaks() {
+		$data = array(
+			'ship_to_different_address' => false,
+			'order_comments'            => 'A string
+			with linebreaks
+			in it.',
```
Comment (wavvves) [inline plugins/woocommerce/tests/php/includes/class-wc-checkout-test.php]: Can we make this less indent weird and use the PHP constant to work across systems? (Never know if tests move to windows 😂 )
```suggestion
			'order_comments'            => 'A string' . PHP_EOL . 'with linebreaks' . PHP_EOL . 'in it.',
```

Comment (opr) [reply plugins/woocommerce/tests/php/includes/class-wc-checkout-test.php]: Good idea thanks!

File: plugins/woocommerce/tests/php/includes/class-wc-checkout-test.php [hunk 3]
```diff
@@ -97,6 +97,34 @@ public function test_order_notes() {
...
+
+		$content = wc_get_template_html(
+			'order/order-details.php',
+			array(
+				'order_id'       => $result,
+				'show_downloads' => false,
+			)
+		);
+		// The preg_replace is necessary because the template outputs a lot of whitespace, we can just make sure the <br /> tags are there as the other whitespace doesn't matter.
+		$this->assertStringContainsString( 'A string<br />with linebreaks<br />in it.', preg_replace( '/[\t|\\n]+/', '', $content ) );
```
Comment (wavvves) [inline plugins/woocommerce/tests/php/includes/class-wc-checkout-test.php]: It's not removing the newline but the literal `\n` substring, we can add the carriage return `\r`, and there's no need for `|` there (this is taken as literal inside the brackets, so it is actually replacing the `|` char) 👍🏼 

You can also probably inject `PHP_EOL` in there, to avoid _regexing_ all newline cases, or to simplify, to make use of `\s` that matches all the whitespace (including tabs and newlines, with a few odd exceptions, not applicable here). But in that case, replace it with a single space and adjust the expected param not to mess with the space inside `<br />`.

```suggestion
		$this->assertStringContainsString( 'A string<br />with linebreaks<br />in it.', preg_replace( '/[\t\n\r]+/', '', $content ) );
```

**Review by wavvves — APPROVED** [review]
Thanks Thomas!
Although I left a couple requests, I'm approving this so you can merge it without waiting again, as this is a small change.
Also, there's template bumps needed there 😖

File: plugins/woocommerce/tests/php/includes/class-wc-checkout-test.php (hunk 3 above)
Comment (wavvves) [reply plugins/woocommerce/tests/php/includes/class-wc-checkout-test.php]: The love I feel for this tool [https://www.phpliveregex.com/](https://www.phpliveregex.com/#tab-preg-replace) is outlasting my relationships 😂

**Comment by opr** [comment]
> Thanks Thomas!
> Although I left a couple requests, I'm approving this so you can merge it without waiting again, as this is a small change.
> Also, there's template bumps needed there 😖

Why are the template bumps needed? Do you think letting `<br />` tags through could be considered a change to the template? I'm not sure

File: plugins/woocommerce/templates/emails/plain/email-order-details.php [hunk 4]
```diff
@@ -43,7 +43,7 @@
 }
 
 if ( $order->get_customer_note() ) {
-	echo esc_html__( 'Note:', 'woocommerce' ) . "\t " . wp_kses( wptexturize( $order->get_customer_note() ), array() ) . "\n";
+	echo esc_html__( 'Note:', 'woocommerce' ) . "\t " . wp_kses( wptexturize( $order->get_customer_note() ), array( 'br' => array() ) ) . "\n";
```
Comment (NeosinneR) [inline plugins/woocommerce/templates/emails/plain/email-order-details.php]: This one is in plain text emails, so I think this could stay as it was before (an empty array) so we don't output any HTML in plain text email (e.g. if the customer manually saved `<br>` in the note).

**Review by NeosinneR — COMMENTED** [review]
@opr I rebased the PR to fix a conflict, but I'm sharing one note before merging.

File: plugins/woocommerce/templates/emails/plain/email-order-details.php (hunk 4 above)
Comment (opr) [reply plugins/woocommerce/templates/emails/plain/email-order-details.php]: Thanks, done!

**Review by NeosinneR — APPROVED** [review]
