### PR TITLE
Fix badge number fails to match the number of unfinished tasks

### LINKED ISSUE #50878: [GlobalStep] Badge number fails to match the number of unfinished tasks in the setup list on the "WooCommerce > Home" menu item.
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Badge number fails to match the number of unfinished tasks in the setup list on the "WooCommerce > Home" menu item.

### Expected behavior

Badge number should match the number of unfinished tasks in the setup list on the "WooCommerce > Home" menu item.

### Actual behavior

Badge number fails to match the number of unfinished tasks in the setup list on the "WooCommerce > Home" menu item.

### Steps to reproduce

1. Create a test site.
2. Install and activate all the required plugins.
3. Install and activate the Woocommerce version 9.3.0-beta.1 plugins.
4. Complete or skip the core profiler
5. Go to WooCommerce > Home
6. Observe that, Badge number fails to match the number of unfinished tasks in the setup list on the "WooCommerce > Home" menu item.

### WordPress Environment

Woocommerce Version: 9.3.0-beta.1
WordPress version: 6.6.1

PC:
Windows 10
Chrome (Version 128.0.6613.85)
Firefox (Version 129.0.2)

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

<details><summary>System Status Report</summary>

```
### WordPress Environment ###

WordPress address (URL): [Redacted]
Site address (URL): [Redacted]
WC Version: 9.3.0-beta.1
Legacy REST API Package Version: The Legacy REST API plugin is not installed on this site.
Action Scheduler Version: ✔ 3.8.1
Log Directory Writable: ❌ To allow logging
make /srv/htdocs/wp-content/uploads/wc-logs/ writable.

WP Version: 6.6.1
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 8.1.29
PHP Post Max Size: 2 GB
PHP Time Limit: 1200
PHP Max Input Vars: 6144
cURL Version: 8.7.1
OpenSSL/1.1.1w

SUHOSIN Installed: –
MySQL Version: 10.6.19-MariaDB-log
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

[REDACTED]

### Post Type Counts ###

attachment: 1
page: 7
post: 2
revision: 1
wp_navigation: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (3) ###

Query Monitor: by John Blackbourn – 3.16.4
Akismet Anti-spam: Spam Protection: by Automattic - Anti-spam Team – 5.3.3
WooCommerce: by Automattic – 9.3.0-beta.1

### Inactive Plugins (0) ###


### Dropin Plugins () ###

advanced-cache.php: advanced-cache.php
db.php: Query Monitor Database Class (Drop-in)
object-cache.php: Memcached

### Must Use Plugins (1) ###

load.php: by  –

### Settings ###

Legacy API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 0 B

### WC Pages ###

Shop base: #7 - /shop/
Cart: #8 - /cart/ -  Contains the woocommerce/cart block
Checkout: #9 - /checkout/ -  Contains the woocommerce/checkout block
My account: #10 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty-Four
Version: 1.2
Author URL: https://wordpress.org
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ❌ Not declared

### Templates ###

Overrides: /srv/htdocs/wp-content/plugins/woocommerce/templates/block-notices/error.php
/srv/htdocs/wp-content/plugins/woocommerce/templates/block-notices/notice.php
/srv/htdocs/wp-content/plugins/woocommerce/templates/block-notices/success.php


### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
pattern-toolkit-full-composability
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
printful
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page
launch-your-store

Disabled Features: experimental-blocks
minified-js
product-pre-publish-modal
settings
async-product-editor-category-field
product-editor-template-system
blueprint
reactify-classic-payments-settings

Daily Cron: ✔ Next scheduled: 2024-08-23 10:46:09 +00:00
Options: ✔
Notes: 55
Onboarding: skipped

### Action Scheduler ###

Complete: 3
Oldest: 2024-08-22 10:47:35 +0000
Newest: 2024-08-22 11:03:10 +0000

Failed: 1
Oldest: 2024-08-22 10:49:16 +0000
Newest: 2024-08-22 10:49:16 +0000

Pending: 1
Oldest: 2024-08-23 10:47:35 +0000
Newest: 2024-08-23 10:47:35 +0000


### Status report information ###

Generated at: 2024-08-22 11:47:08 +00:00
```
</details>

### PR DESCRIPTION
**Pull request by chihsuan**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes https://github.com/woocommerce/woocommerce/issues/50878

Currently, the core profiler renders the header, footer, StoreAlerts, and Plugin area, which is not needed for the setup wizard. It is fetching the task list data from the server on the core profiler page load and causing the LYS task to be marked as completed. This PR hides the header, footer, StoreAlerts, and Plugin area for the setup wizard to fix the issue.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Create a fresh site.
2. Complete or skip the core profiler (Please make sure Core profiler is working as expected).
3. Go to WooCommerce > Home
4. Observe that the badge number matches the number of unfinished tasks in the setup list on the "WooCommerce > Home" menu item.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce-admin/client/layout/controller.js [hunk 1]
```diff
@@ -275,6 +275,13 @@ export const getPages = () => {
 					__( 'Profiler', 'woocommerce' ),
 				],
 				capability: 'manage_woocommerce',
+				layout: {
```
Comment (rjchow) [inline plugins/woocommerce-admin/client/layout/controller.js:278]: wow that's neat, I never realised this..!

**Review by rjchow — APPROVED** [review]
Tests well, thanks!

**Review by ilyasfoo — APPROVED** [review]
Tests well! 🚢
