### PR TITLE
Add to Cart - stepper style: fix input field when the product stock quantity is 1

### LINKED ISSUE #57454: Stepper > left Qty = 1 : display issue (only input field is hidden, not the whole stepper)
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When the product left quantity is 1, the stepper does not display the quantity field, which makes the customer questionning if there is a bug

ping @gigitux who was the last who worked on the feature

It is a follow up of 
https://github.com/woocommerce/woocommerce/pull/48876 (Scenario 4)
https://github.com/woocommerce/woocommerce/issues/42299#issuecomment-2427062426
https://github.com/woocommerce/woocommerce/pull/52193

### Expected behavior

the whole stepper should be hidden, with the same behavior of the sold individually option enabled
OR
just display the quantity field but don't let user play with +-

### Actual behavior

See the screenshots

Image

### Steps to reproduce

1. Set your single product template with the Stepper Option activated for the Add to Cart
2. Set your product with a remaining qty of 1 
    - in my case it is a single product type, with sold individually option set to OFF
4. Observe the stepper layout on that product, front side 
### WordPress Environment

- WP6.8
- Woo 9.8.1
- TT5 theme

### Isolating the problem

- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by gigitux**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes https://github.com/woocommerce/woocommerce/issues/57454 (WOOPLUG-4034) .

(For Bug Fixes) Bug introduced in PR # .

### Screenshots or screen recordings:

| Before | After |
| ------ | ----- |
| image| image|

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Edit the Single Product Template
2. Edit the `Add to Cart with Options`.
3. Switch the quantity selector to stepper.
4. Save the template.
5. Edit a product.
6. Click on Inventory.
7. Click on `Track stock quantity for this product`
8. Update quantity to 1.
9. Save.
10. Visit the product.
11. Ensure that the stepper buttons aren't rendered.

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [x] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

Add to Cart - stepper style: fix input field when the product stock quantity is 1

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

**Review by Aljullu — COMMENTED** [review]
Nice fix! I tested setting a product's inventory to 1 and confirming the stepper buttons aren't shown unnecessarily and it works correctly

Before | After
--- | ---
imatge | imatge


@gigitux I noticed the issue also affects the _Quantity Selector_ block of the _Add to Cart with Options_ block. So while not a blocker of this PR, I was wondering if we should fix it there as well? I think adding the same stock check [here](https://github.com/woocommerce/woocommerce/blob/7edde48eaf24e719ade0c1fcb1446d0aaf06c019/plugins/woocommerce/src/Blocks/BlockTypes/AddToCartWithOptionsQuantitySelector.php#L133) would be enough.

Update: also, not a blocker, but I think it would be nice to get automated tests for this.

**Comment by gigitux** [comment]
@Aljullu Thanks for the feedback!

> I noticed the issue also affects the Quantity Selector block of the Add to Cart with Options block. So while not a blocker of this PR, I was wondering if we should fix it there as well? I think adding the same stock check [here](https://github.com/woocommerce/woocommerce/blob/7edde48eaf24e719ade0c1fcb1446d0aaf06c019/plugins/woocommerce/src/Blocks/BlockTypes/AddToCartWithOptionsQuantitySelector.php#L133) would be enough.

Done with 65cea3c. Also, I improved the logic given that we need to check `stock_quantity` only when `managing_stock` is set to true.


> Update: also, not a blocker, but I think it would be nice to get automated tests for this.


Done with 42ad135. I wasn't able to find specific E2E tests for `add-to-cart-with-options-quantity-selector`. Let me know if I missed them, or I should add this test in another file to cover the Blockified Add To cart block as well.

File: plugins/woocommerce/src/Blocks/BlockTypes/AddToCartForm.php [hunk 1]
```diff
@@ -136,7 +136,13 @@ protected function render( $attributes, $content, $block ) {
...
 
 		$is_external_product_with_url = $product instanceof \WC_Product_External && $product->get_product_url();
-		$is_stepper_style             = 'stepper' === $attributes['quantitySelectorStyle'] && ! $product->is_sold_individually() && Features::is_enabled( 'add-to-cart-with-options-stepper-layout' );
+		$managing_stock               = $product->managing_stock();
+		$stock_quantity               = $product->get_stock_quantity();
+
+		/**
+		 * The stepper buttons don't show when the product is sold individually or stock quantity is less or equal to 1 because the quantity input field is hidden.
+		 */
+		$is_stepper_style = 'stepper' === $attributes['quantitySelectorStyle'] && ! $product->is_sold_individually() && ( ( $managing_stock && $stock_quantity > 1 ) || ! $managing_stock ) && Features::is_enabled( 'add-to-cart-with-options-stepper-layout' );
```
Comment (Aljullu) [inline plugins/woocommerce/src/Blocks/BlockTypes/AddToCartForm.php:148]: Ups, sorry I missed in the first review, but in the _Add to Cart with Options_ block there will only be the stepper style (https://github.com/woocommerce/woocommerce/issues/56686), so this variable will be removed. I think it would be easier to simply tweak the _Quantity Selector_ block and [return early](https://github.com/woocommerce/woocommerce/blob/7edde48eaf24e719ade0c1fcb1446d0aaf06c019/plugins/woocommerce/src/Blocks/BlockTypes/AddToCartWithOptionsQuantitySelector.php#L135) when there is only one item in stock?

**Review by Aljullu — COMMENTED** [review]
Thanks for the updates!

> Done with 42ad135. I wasn't able to find specific E2E tests for `add-to-cart-with-options-quantity-selector`. Let me know if I missed them, or I should add this test in another file to cover the Blockified Add To cart block as well.

Right, we don't have specific tests for the inner blocks, we test them as part of the _Add to Cart with Options_ wrapper. In this specific case, I think the [PHP unit tests](https://github.com/woocommerce/woocommerce/blob/b49c1b3e9e77e742e604f368fe8c685516b5de07/plugins/woocommerce/tests/php/src/Blocks/BlockTypes/AddToCartWithOptions.php) might be useful as we have some similar tests there.

I'm happy to work on it in a follow-up if you prefer. Or if you can include it in this PR, that would be awesome! :100:

**Comment by gigitux** [comment]
No worries, @Aljullu! I fixed the code and added unit test.

I believe you’re already aware, but since the new block only supports the stepper style, it seems we can simplify the logic by removing some of the checks:


https://github.com/woocommerce/woocommerce/blob/d77461822512d9f3dee97c0e5d7635beddbe8037/plugins/woocommerce/src/Blocks/BlockTypes/AddToCartWithOptionsQuantitySelector.php#L174-L177


https://github.com/woocommerce/woocommerce/blob/d77461822512d9f3dee97c0e5d7635beddbe8037/plugins/woocommerce/src/Blocks/BlockTypes/AddToCartWithOptionsQuantitySelector.php#L201-L202


I didn’t update this in the current PR to keep the scope focused. Let me know if that sounds good!

File: plugins/woocommerce/tests/php/src/Blocks/BlockTypes/AddToCartWithOptions.php [hunk 2]
```diff
@@ -190,4 +190,29 @@ public function test_grouped_product_selector_cta() {
...
+	 * Tests that the quantity selector block is not visible for sold individually products and manage stock products with stock quantity <= 1.
+	 */
+	public function test_stepper_not_visible_for_sold_individually_products_and_manage_stock() {
+		$simple_product = new \WC_Product_Simple();
+		$simple_product->set_regular_price( 10 );
+		$simple_product->set_sold_individually( true );
+		$simple_product_id = $simple_product->save();
+
+		$markup = do_blocks( '<!-- wp:woocommerce/single-product {"productId":' . $simple_product_id . '} --><!-- wp:woocommerce/add-to-cart-with-options /--><!-- /wp:woocommerce/single-product -->' );
+		$this->assertStringNotContainsString( 'data-block-name="woocommerce/add-to-cart-with-options-quantity-selector"', $markup, 'The Add to Cart with Options form does not contains a quantity selector block for sold individually products.' );
```
Comment (Aljullu) [inline plugins/woocommerce/tests/php/src/Blocks/BlockTypes/AddToCartWithOptions.php]:
```suggestion
		$this->assertStringNotContainsString( 'data-block-name="woocommerce/add-to-cart-with-options-quantity-selector"', $markup, 'The Add to Cart with Options form does not contain a quantity selector block for sold individually products.' );
```

File: plugins/woocommerce/tests/php/src/Blocks/BlockTypes/AddToCartWithOptions.php [hunk 3]
```diff
@@ -190,4 +190,29 @@ public function test_grouped_product_selector_cta() {
...
+
+		$simple_product->set_sold_individually( false );
+		$simple_product->set_manage_stock( true );
+		$simple_product->set_stock_quantity( 1 );
+		$simple_product->save();
+		$markup = do_blocks( '<!-- wp:woocommerce/single-product {"productId":' . $simple_product_id . '} --><!-- wp:woocommerce/add-to-cart-with-options /--><!-- /wp:woocommerce/single-product -->' );
+		$this->assertStringNotContainsString( 'data-block-name="woocommerce/add-to-cart-with-options-quantity-selector"', $markup, 'The Add to Cart with Options form does not contains a quantity selector block for products with manage stock set to true and stock quantity set to 1.' );
```
Comment (Aljullu) [inline plugins/woocommerce/tests/php/src/Blocks/BlockTypes/AddToCartWithOptions.php]:
```suggestion
		$this->assertStringNotContainsString( 'data-block-name="woocommerce/add-to-cart-with-options-quantity-selector"', $markup, 'The Add to Cart with Options form does not contain a quantity selector block for products with manage stock set to true and stock quantity set to 1.' );
```

**Review by Aljullu — APPROVED** [review]
Thanks for the updates, it looks good to me, @gigitux! I left a couple of suggestions to fix typos, but that's all.

Besides testing the current block, I also tested the new blockified _Add to Cart with Options_ block and confirming the issue is fixed there too:

`trunk` | This branch
--- | ---
imatge | imatge

> I believe you’re already aware, but since the new block only supports the stepper style, it seems we can simplify the logic by removing some of the checks:

Yes, this is being cleaned up in #57442. :slightly_smiling_face:
