### PR TITLE
Fix incorrect VAT exempt behaviour on shop page when prices are exclusive of tax. 

### LINKED ISSUE #27012: is_vat_exempt removes VAT from shop pages only if prices are entered inclusive of tax
Please provide us with the information requested in this bug report. Without these details, we won't be able to fully evaluate this issue. 
Bug reports lacking detail, or for any other reason than to report a bug, may be closed without action.

**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
I have programatically set a user to be tax exempt using the woocommerce set_is_vat_exempt() function.
This correctly removes VAT from the Cart pages. However, in the shop pages, it removes VAT only if the shop setting is "I will enter prices inclusive of tax".

**Expected behavior**
The way a user enters prices (inclusive or exclusive of tax), should have no relation whatsoever to how tax is displayed. I would expect WooCommerce to remove tax in shop pages for VAT exempt users regardless of how the shop owner enters prices.

**Actual behavior**
WooCommerce only removes tax in shop pages if the setting is "I will enter prices inclusive of tax".

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Set current user as vat exempt programatically: WC()->customer->set_is_vat_exempt(true);
2. Set the following settings: 
A) Display prices in the shop including tax. 
B) Display prices in the cart including tax. 
C) I will enter prices inclusive of tax

3. Create a product with the price of 100 and a tax rate of 15% for testing purposes.
3.5. Edited: Also please set "Calculate tax based on Shop Settings" (and set the 15% tax rate for the country the shop is based in)
4. Price appears correctly with the tax removed: 86.96
5. Change I will enter prices inclusive of tax to " I will enter prices exclusive of tax"
6. The price that should now appear in shop pages is 100. However it is 115. The tax is no longer being removed by the is_vat_exempt status

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report we won't be able to fully evaluate this issue.
<details>
`
### WordPress Environment ###

WordPress address (URL): http://localhost:10093
Site address (URL): http://localhost:10093
WC Version: 4.3.0
REST API Version: ✔ 1.0.10
WC Blocks Version: ✔ 2.7.1
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.3.0
Log Directory Writable: ✔
WP Version: 5.4.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.16.0
PHP Version: 7.3.5
PHP Post Max Size: 1,000 MB
PHP Time Limit: 1200
PHP Max Input Vars: 4000
cURL Version: 7.64.0
OpenSSL/1.1.1b

SUHOSIN Installed: –
MySQL Version: 8.0.16
Max Upload Size: 300 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.3.0
WC Database Prefix: wp_
Total Database Size: 3.74MB
Database Data Size: 2.34MB
Database Index Size: 1.40MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 1.50MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_posts: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 1
b2bking_custom_field: 9
b2bking_custom_role: 2
b2bking_rule: 1
page: 6
post: 2
product: 2

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 4.3.0

### Inactive Plugins (1) ###

B2BKing: by WebWizards – 1.8.0

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: left
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #19 - /shop/
Cart: #20 - /cart/
Checkout: #21 - /checkout/
My account: #22 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 2.5.8
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 5
Oldest: 2020-07-10 12:49:11 +0000
Newest: 2020-07-10 13:39:16 +0000

Pending: 1
Oldest: 2020-07-11 12:49:11 +0000
Newest: 2020-07-11 12:49:11 +0000

`
</details>

**Solving this**
I suppose you could go about solving this in 2 ways, but I would ask that you please address this in a way that offers an option to consistently remove tax from shop pages (perhaps add a parameter to the set_is_vat_exempt function regarding display of VAT in shop pages).

This option is extremely important for legal reasons for business-to-business e-commerce, particularly in Europe.

### PR DESCRIPTION
**Pull request by iamdharmesh**
### All Submissions:

-   [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
-   [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
-   [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change?

**Note: This PR superceed the other PR #27020 by adding unit tests. ( #27020 is older and require rebase. So, I included changes of that PR in this PR as well)**

### Changes proposed in this Pull Request:
As described on #27012, VAT from product prices on shop pages is not getting removed for vat exempted customers, if prices are entered exclusive of tax. It removes VAT only if the shop setting is "I will enter prices inclusive of tax". 

Closes #27012

### How to test the changes in this Pull Request:

Please see more detailed instructions in the [comment below](https://github.com/woocommerce/woocommerce/pull/33991#issuecomment-1451924872).

1. Set VAT exempt on the current user using one of the below ways.
     A. Install [EU VAT Number](https://woocommerce.com/products/eu-vat-number/) and save the correct VAT number from My Account. 
           - OR -
     B. Set vat exempt programmatically:  
     ```
     add_action('init', function(){
       if (isset(WC()->customer)){
          WC()->customer->set_is_vat_exempt(true);
       }
    });
     ```
2. Set tax options like this in Woo settings
image
3. Create a product with a price of 100 and a tax rate of 15% for testing purposes.
4. Visit the Shop page and make sure the price for the created product showing 100.

### Other information:

-   [x] Have you added an explanation of what your changes do and why you'd like us to include them?
-   [x] Have you written new tests for your changes, as applicable?
-   [x] Have you successfully run tests with your changes locally?
-   [x] Have you created a changelog file for each project being changed, ie `pnpm changelog add --filter=<project>`?

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

**Comment by jeffpaul** [comment]
@peterfabian note that this PR is up for review to help resolve #27012 and superceed/replace #27020.

**Comment by peterfabian** [comment]
Notes from testing:

If you're going to use the EU VAT Extension, in my local testing, I had to amend the code of the extension, otherwise I was getting an SLL error:

Screenshot 2023-03-02 at 14 44 35

SO thread that provided the solution: https://stackoverflow.com/questions/25142227/unable-to-connect-to-wsdl

To provide more specific testing instructions:

1. Set the store's country to one of the EU countries, e.g. I used Denmark
2. Enable Tax rates & calculations under WC > Settings > General.
3. Install & activate [EU VAT Number](https://woocommerce.com/products/eu-vat-number/) extension
4. Go to My Account > Addresses and set an address in DK, eg. City = Copenhagen, ZIP = 2100
5. In My Account > VAT Number and save a valid VAT number, e.g. use the one for Vestas: DK28118171
6. In My Account, set the billing country to Denmark to test for cases where the customer is based in the same country as the store
7. Go to WC > Settings > Tax and make sure this setting is enabled
Screenshot 2023-03-02 at 14 49 55
Set the rest according to the [settings above](https://user-images.githubusercontent.com/10613171/179961522-2cc7fafd-a571-4ac2-a816-bdfcd459f236.png)


8. Create Standard rates Tax settings under WC > Settings > Tax > Standard rates for a couple of EU countries, e.g. DK = 25% and SK. = 19% and rest = 20% as per the setting below:

Screenshot 2023-03-02 at 14 51 10

9. Create a product with price 100 and Standard Tax rate.
10. Go to see your product in the Shop/Single Product page. The product price is displayed including VAT (price = 125):
Screenshot 2023-03-02 at 14 57 14

11. After adding the product to Cart, the price is modified to exclude VAT (price = 100):
Screenshot 2023-03-02 at 14 57 36

12. Now change the pricing in the store to be entered including the tax.
Screenshot 2023-03-02 at 14 59 43
13. You should see the same price in Single Product page and in the Cart/Checkout (price = 80)
Screenshot 2023-03-02 at 15 00 34

Screenshot 2023-03-02 at 15 00 42

14. Apply the changes from this branch. 
15. Check the product pricing is correct when prices are entered including VAT (price should be 80 in Shop, Cart and Checkout)
16. Change the Tax settings to be entered exclusive of VAT (same setting as in step 12, just the other radio button)
17. Check the product pricing is correct when prices are entered including VAT (price should be 100 in Shop, Cart and Checkout)
18. Test this (steps 16-17) also with a customer that is based in another EU country, e.g. set billing country to Slovakia and VAT number to SK2020317068 (Eset)
19. The results should still be price = 100 in all cases.
20. Test this (steps 16-17) also with a customer that is based outside of the EU. In that case, price should be 120, if you used the same settings as in the screenshot above, as vat for * (all other countries) is 20%.
21. Ideally, this would be tested also with Tax setting of displaying prices excluding tax in shop and in cart/checkout, so there are 8 different scenarios, if we're conservative.

File: plugins/woocommerce/tests/php/includes/wc-product-functions-test.php [hunk 1]
```diff
@@ -128,4 +128,72 @@ public function get_customer_id() {
...
+	 *           [true, false]
+	 *           [false, true]
+	 *           [false, false]
+	 *
+	 * @param bool $prices_include_tax Whether entered prices are inclusive of tax.
+	 * @param bool $is_vat_exempt      Whether the VAT is exempted for customer.
+	 */
+	public function test_wc_get_price_including_tax( $prices_include_tax, $is_vat_exempt ) {
+		// Set VAT exempt and Mock prices_include_tax.
+		WC()->customer->set_is_vat_exempt( $is_vat_exempt );
```
Comment (peterfabian) [inline plugins/woocommerce/tests/php/includes/wc-product-functions-test.php:145]: Does this setting also need a cleanup or is the order of execution of `testWith` annotation guaranteed, so it will end up with neutral (false) value?

**Review by peterfabian — CHANGES_REQUESTED** [review]

**Comment by peterfabian** [comment]
Sorry for the long wait on the review. I just have a small question, otherwise, it works as advertised, so it should be good to go once the question is answered. 

Nice that you added unit tests. Thanks!

Side note: I had to rebase to build it, so it might help other testers if you rebased this. Thx!

File: plugins/woocommerce/tests/php/includes/wc-product-functions-test.php (hunk 1 above)
Comment (iamdharmesh) [reply plugins/woocommerce/tests/php/includes/wc-product-functions-test.php:145]: Thanks for noticing this @peterfabian. Yes, cleanup is needed I have added the cleanup code. Could you please check it once? Thanks.

**Review by peterfabian — APPROVED** [review]
Looks good now, thanks!
