### PR TITLE
[Checkout] Added selected rate name when showing multiple shipping packages in cart and checkout.

### LINKED ISSUE #51041: Cart Block does not display shipping rates/costs per package when using subscriptions
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

If you allow multiple subscriptions to be checked out at the same time, cart block displays shipping packages in a collapsed form. But you cannot see which option is chosen per package unless you toggle open the section.

Screenshot 2024-08-29 at 11 52 40

Additionally, the main shipping section lists only one shipping option name; the last one toggled. This is extremely confusing.

Screenshot 2024-08-29 at 11 52 54

### Expected behavior

Each package should show which shipping option is selected.

The top level shipping total should have the shipping option name hidden and just show the grand totals.

### Actual behavior

Selected shipping options are hidden unless the package is uncollapsed.

The top level totals row only shows the "last selected" shipping option.

### Steps to reproduce

1. Install woo subscriptions
2. Setup 2 subscription products with differing billing periods
3. Setup multiple shipping options
4. Add both subscriptions to cart
5. Go to the cart block and see how shipping options are presented
6. Open a shipping package and select a different shipping option. Notice the "shipping" row only shows the last shipping option you choose

### WordPress Environment

N/A

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by mikejolley**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

This PR improves the display of multiple shipping packages in conjunction with subscriptions which utilises them. Selected rates are shown in the panel header so you can see selections, and the initial render is fixed.

Cart view:

Screenshot 2024-12-09 at 16 01 15

Checkout view:

Screenshot 2024-12-09 at 16 01 23

Notice the rate name is shown below the package name.

Closes #51041

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Install WooCommerce subscriptions. Create some subscriptions with different billing intervals e.g. weekly and monthly.
2. Add a regular product, and your new subscription products to the cart.
3. Ensure some shipping methods are setup.
4. View the cart and checkout and see how packages are displayed. Toggle open the panels and ensure its rendered correcrly.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce-blocks/assets/js/base/components/cart-checkout/shipping-rates-control-package/index.tsx [hunk 1]
```diff
@@ -36,12 +36,29 @@ export const ShippingRatesControlPackage = ( {
...
+			);
+		};
+
+		updateCount();
+
+		const observer = new MutationObserver( updateCount );
+		observer.observe( document.body, { childList: true, subtree: true } );
+
+		return () => {
+			updateCount();
```
Comment (nielslange) [inline plugins/woocommerce-blocks/assets/js/base/components/cart-checkout/shipping-rates-control-package/index.tsx]: Is there are particular reason why we want to call `updateCount()` within the cleanup function?

File: plugins/woocommerce-blocks/assets/js/base/components/cart-checkout/shipping-rates-control-package/style.scss [hunk 2]
```diff
@@ -45,11 +39,19 @@
 	}
 }
 
+.wc-block-components-shipping-rates-control__package-header {
+	margin: 0 0 $gap-small 0;
```
Comment (nielslange) [inline plugins/woocommerce-blocks/assets/js/base/components/cart-checkout/shipping-rates-control-package/style.scss]: Nitpic: We can shorten this SCSS definition like this:

```suggestion
	margin: 0 0 $gap-small;
```

**Review by nielslange — COMMENTED** [review]
Thanks for working on this, @mikejolley. 

In https://github.com/woocommerce/woocommerce/issues/51041, you mentioned

> The top level totals row only shows the "last selected" shipping option.

I tested this PR with two shipping methods and two pickup locations enabled, as well as two subscription products with different renewal intervals, per your instructions. During testing, I noticed that selecting a pickup location for the renewal shipment caused the initial shipment's value to inherit the same pickup location. You can see this behavior in the screen recording below:

<details>
<summary>Screen recording</summary>

https://github.com/user-attachments/assets/50f0887e-0889-4f0b-b313-484f9a510137

</details>

This issue seems specific to pickup locations; selecting a shipping method for the renewal shipment leaves the initial shipment unchanged.

Apart from this, I also left a question and a suggestion below. The question is regarding the clean-up function of the `useEffect`, the suggestion is a _nitpic_ regarding a minor SCSS improvement.

File: plugins/woocommerce-blocks/assets/js/base/components/cart-checkout/shipping-rates-control-package/index.tsx (hunk 1 above)
Comment (mikejolley) [reply plugins/woocommerce-blocks/assets/js/base/components/cart-checkout/shipping-rates-control-package/index.tsx]: Since this is ran on unmount I think you're right its not needed.

Comment (nielslange) [reply plugins/woocommerce-blocks/assets/js/base/components/cart-checkout/shipping-rates-control-package/index.tsx]: Shall we remove it then?

Comment (mikejolley) [reply plugins/woocommerce-blocks/assets/js/base/components/cart-checkout/shipping-rates-control-package/index.tsx]: https://github.com/woocommerce/woocommerce/pull/53579/commits/95169ab0383ddf0fbc6f93651a80fdcd94d52e55

**Comment by mikejolley** [comment]
@nielslange That issue with selection is present on trunk. We have logic in place to force all packages local pickup when selecting local pickup because we don't allow a mix of rates. However, this doesn't seem to extend the the recurring packages of subscriptions. This will need more investigation and may require a patch subs side. 

Should be logged separately as it wasn't related to https://github.com/woocommerce/woocommerce/issues/51041

**Comment by mikejolley** [comment]
@nielslange removed that code so ready for you again.

**Review by nielslange — APPROVED** [review]
I just tested the changes again, @mikejolley, and the PR works as expected. Let's ⛴️ these improvements.

**Comment by PanosSynetos** [comment]
Thanks @mikejolley 

FYI @mattallan tagging you, as this is related to Subscriptions

**Comment by mikejolley** [comment]
@PanosSynetos I was going to create an issue somewhere but since you're here, is it already logged?

**Comment by PanosSynetos** [comment]
Not sure if there's an issue in subscriptions - but I have the conversation in Slack, if you'd like to reach out

p1724878814303219-slack-C7U3Y3VMY

**Comment by mikejolley** [comment]
Logged here https://github.com/woocommerce/woocommerce-subscriptions/issues/4767
