### PR TITLE
Replacing rest_namespace modification with middleware due to blocks issues

### LINKED ISSUE #37619: [New Block Editor] - Changes to product base config when feature enabled breaks implementation of products data in other editors.
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When a store where the new block powered product editor feature is enabled, product blocks in other editors (such as Product Title) are broken and not rendering content.

**This is currently in the WC 7.6 release candidate so would be nice to be fixed before release.** However, it will only impact stores that have enabled the block powered product editor feature.

### Expected behavior

I expect that existing product related blocks on non product-editor routes work as expected.

### Actual behavior

In the new block editor powered product editor, to utilize the WordPress entity store the base config for the product post type is [filtered](https://github.com/woocommerce/woocommerce/blob/c0efe1f2f537720d6b2fa8db15f33b055bf5856a/plugins/woocommerce/src/Admin/Features/ProductBlockEditor/Init.php#L36) to return the namespace for the Woo Products data (`wc/v3`) which replaces the default `wp/v2` route for grabbing posts. The shapes of the response for the Woo REST route is different than that returned from the WordPress route. 

While not problematic for the use case in the product editor, because this is globally applied for any user with the feature enabled, this breaks the default behaviour of the WP entity stores in other editors (post, page, site editor etc) which results in the editor not showing things like product title in blocks using that entity store. For example, the Products Block is a variation of the WP Query Loop block which uses the entity store and passes data through via context to the inner blocks. The Product Title block is a variation of the "Post Title" block which expects things like [`rawTitle` and `fullTitle`](https://github.com/WordPress/gutenberg/blob/e9b4e69331ce64212273a702c8f6944a97f4701c/packages/block-library/src/post-title/edit.js#L34-L39) in the data store (which is provided by the default WP core route for grabbing post data. Besides the Products block, the same behaviour exists when inserting a Query Loop Block and configuring it to query from the product post type.

CleanShot 2023-04-07 at 09 22 19@2x

**To be clear: This is a fairly severe modification to the current behaviour of the the registered Product Post type. There could be other implementations in the wild that are relying on the WP route configured with the post type that could also break. At a minimum, this change should be limited to the context of the new product editor.**

### Steps to reproduce

1. With the block product editor feature enabled.
2. Go to any other WP editor other than the Product editor and add a Products Block. Notice that Product titles are not rendering.

### WordPress Environment

- WP 6.2
- WooCommerce 7.6.rc2

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by joelclimbsthings**
### Submission Review Guidelines:

- I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
- I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
- I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/). 
- Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

In development of the product block editor require the use of the `/wc/v3/products` version of the products API. Adding this to the postType has created [an issue](https://github.com/woocommerce/woocommerce/issues/37619) (and potentially others) in other areas of the application. In this PR I'm removing any modification on the post type definition directly and using `apiFetch` middle ware to conditionally modify the path only for the purpose of the product block editor. 

Closes #37619  .

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Enable this branch and install the WCA Test Helper plugin. 
2. Create a simple test product.
3. Enable the `product-block-editor` feature flag using the WCA Test Helper plugin.
4. Navigate to Products -> Add new, and you should see the product block editor.
5. Ensure that it renders properly with no error, in particular the images block should appear like so:
image

6. Navigate to any page block editor through Pages -> (select page), and add the `Products (beta)` block:
image

7. The block should appear correctly, including the product title/etc:
image

### CODE REVIEW

File: plugins/woocommerce-admin/client/products/hooks/use-product-entity-record.ts [hunk 1]
```diff
@@ -4,9 +4,32 @@
...
+	next: ( options: ApiFetchOptions ) => void
+) => void;
+
+type ApiFetch = {
+	use: ( middleware: Middleware ) => void;
+};
+
+declare const wp: { apiFetch: ApiFetch };
+
+const isProductEditor = () => {
```
Comment (joelclimbsthings) [inline plugins/woocommerce-admin/client/products/hooks/use-product-entity-record.ts]: For a little extra caution I'm only enabling this only when on the add/edit product screen, since the middle-ware will technically remain as you navigate to other React pages.

File: plugins/woocommerce-admin/client/products/hooks/use-product-entity-record.ts [hunk 2]
```diff
@@ -15,6 +38,21 @@ export function useProductEntityRecord(
...
+		// without disturbing the rest_namespace outside of the product block editor.
+		wp.apiFetch.use( ( options, next ) => {
+			const versionTwoRegex = new RegExp( '^/wp/v2/product/' );
+			if ( versionTwoRegex.test( options?.path ) && isProductEditor() ) {
+				options.path = options.path.replace(
+					versionTwoRegex,
+					'/wc/v3/products/'
+				);
+			}
+			return next( options );
```
Comment (nerrad) [inline plugins/woocommerce-admin/client/products/hooks/use-product-entity-record.ts]: This doesn't really need to be in an effect?

Comment (joelclimbsthings) [reply plugins/woocommerce-admin/client/products/hooks/use-product-entity-record.ts]: Not really, although it only needs to run once on the initial render, which this ensures. That said this component likely won't re-render unless the product ID changes and it wouldn't be very consequential if it did.

Comment (nerrad) [reply plugins/woocommerce-admin/client/products/hooks/use-product-entity-record.ts]: I wonder if it'd be better then to move it outside of the component into the global scope? That would make it slightly more discoverable in the future if it was refactored to be a part of some other initiatlization script. It's not really component level logic.

File: plugins/woocommerce-admin/client/products/hooks/use-product-entity-record.ts [hunk 3]
```diff
@@ -4,9 +4,32 @@
...
+type Middleware = (
+	options: ApiFetchOptions,
+	next: ( options: ApiFetchOptions ) => void
+) => void;
+
+type ApiFetch = {
+	use: ( middleware: Middleware ) => void;
+};
+
+declare const wp: { apiFetch: ApiFetch };
```
Comment (nerrad) [inline plugins/woocommerce-admin/client/products/hooks/use-product-entity-record.ts]: `apiFetch` is loaded via external and the Dependency Extraction Webpack Plugin should be able to handle the transformation of the import. So would be better here to import from `@wordpress/api-fetch`?

Comment (joelclimbsthings) [reply plugins/woocommerce-admin/client/products/hooks/use-product-entity-record.ts]: Good call, I tried importing from `@wordpress/data-controls` but that doesn't benefit from the Dependency Extraction Plugin in the same way it seems. Fixed in https://github.com/woocommerce/woocommerce/pull/37621/commits/7eb75469c2731b8496361cc20306d64bbf23e99b.

Comment (nerrad) [reply plugins/woocommerce-admin/client/products/hooks/use-product-entity-record.ts]: Ahh, `apiFetch` exported from `@wordpress/data-controls` is something different. It's a control wrapper around `wp.apiFetch` typically used in actions or resolvers.

File: plugins/woocommerce-admin/client/products/hooks/use-product-entity-record.ts (hunk 2 above)
Comment (joelclimbsthings) [reply plugins/woocommerce-admin/client/products/hooks/use-product-entity-record.ts]: Point taken, although it may be a difference in mental model. My understanding is to keep this as narrow as possible for the time being, targeting only the product block editor, so keeping it close to that logic makes sense in my mind. 

I don't believe we have any other similar logic on the front-end, or it may sense to consolidate that in the same place. That said, I'm receptive to moving this elsewhere.

Comment (joelclimbsthings) [reply plugins/woocommerce-admin/client/products/hooks/use-product-entity-record.ts]: Perhaps a WCA script enqueued on the backend? I'm open to what might feel more appropriate to others.

**Review by louwie17 — DISMISSED** [review]
This tested well and code looks good, thanks for getting on this so quickly @joelclimbsthings 🎉 

I do have a couple more general thoughts:
- This will definitely still be a short term solution, as this only works because WooCommerce Admin and the page/post editor don't share the same React router yet, so the Redux state is reset when navigating between these two pages.
Once that does happen, we will run into the same scenario if a user navigates between the two pages and loads/renders the same product.
- I do agree with @nerrad that `apiFetch.use` logic might be better of separated and called outside of a component level, and maybe something that we can move to the `product-editor` package and expose some initialization function that is required?
I assume if you wrap the `apiFetch.use` logic with the `isProductEditor` outside of the component it would still be fine and not overlap?
This could be done as a follow up.

**Comment by joelclimbsthings** [comment]
Thanks @louwie17 and @nerrad for the reviews!

I agree that this isn't really component level logic. As mentioned it's a bit hard to think of a more appropriate "global" part of the application to insert it, but I've refactored to add the middle-ware to the `product-editor` package and I'm implementing outside of the component on the `product-page`. 

> This will definitely still be a short term solution, as this only works because WooCommerce Admin and the page/post editor don't share the same React router yet, so the Redux state is reset when navigating between these two pages.

Yeah, the fact that this is a short-term "patch" is why it felt better to keep it close to the product editor logic. It's an interesting issue, and long-term we'll either need to unify our usage of the endpoints, or have a cleaner solution for specifying the endpoint we want to use for a specific use case of the entity data store. 

Do we have a place where we're tracking these types of concerns currently @louwie17 ?

**Review by louwie17 — APPROVED** [review]
Thanks for moving the logic to the `product-editor` package, this looks great! And still tested well :)

> Do we have a place where we're tracking these types of concerns currently @louwie17 ?

We do not yet, would you be up for creating an google sheets to get it started?
