### PR TITLE
Replaced deprecated Jetpack::is_staging_site call

### LINKED ISSUE #25664: Old & new OBW error when activating Jetpack with WP_DEBUG on
**Describe the bug**
Notice: Jetpack::is_staging_site is deprecated since version jetpack-8.1! Use /Automattic/Jetpack/Status->is_staging_site instead. in /srv/users/usercc2521bd/apps/usercc2521bd/public/wp-includes/functions.php on line 4648
Screenshot 2020-02-13 at 19 22 34

**To Reproduce**
1. Open a fresh JN site
2. Go through the OBW, but this time, try to connect with Jetpack
3. Observe the error

### PR DESCRIPTION
**Pull request by peterfabian**
Replaces #25665 .

### All Submissions:

* [ ] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [ ] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes #25664 .

### How to test the changes in this Pull Request:

1. Get a new JN instance
2. Build this package and upload it as a plugin to JN
3. Go through the OBW and 
- allow tracking, 
- activate Jetpack, 
4. you shouldn't see any error (ideally). Or at least not the error saying Notice: Jetpack::is_staging_site is deprecated since version jetpack-8.1! Use /Automattic/Jetpack/Status->is_staging_site instead.
4. Get another JN without Jetpack
5. Install Jetpack older than 8.1, e.g. 7.9 or 8.0
6. Verify that there are no error during OBW when activating Jetpack.

### Other information:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully run tests with your changes locally?

### Changelog entry

> Fix - Replaced deprecated Jetpack::is_staging_site call.

### CODE REVIEW

File: includes/class-wc-tracker.php [hunk 1]
```diff
@@ -111,9 +111,22 @@ private static function get_tracking_data() {
 		$data['inactive_plugins'] = $all_plugins['inactive_plugins'];
 
 		// Jetpack & WooCommerce Connect.
+		// Test if the site if a staging site based on the Jetpack criteria.
+		$is_jp_staging = false;
```
Comment (rodrigoprimo) [inline includes/class-wc-tracker.php]: Maybe this code to decide which method to use to determine if the site is a staging site depending on the Jetpack available should be abstracted to its own method?

File: includes/class-wc-tracker.php [hunk 2]
```diff
@@ -111,9 +111,22 @@ private static function get_tracking_data() {
...
+		if ( class_exists( '\Automattic\Jetpack\Status' ) ) {
+			// Preferred way of checking with Jetpack 8.1+.
+			$jp_status = new \Automattic\Jetpack\Status();
+			if ( is_callable( '$jp_status->is_staging_site()' ) && $jp_status->is_staging_site() ) {
```
Comment (rodrigoprimo) [inline includes/class-wc-tracker.php]: I don't think that `is_callable( '$jp_status->is_staging_site()' )` works. I believe it will always return false. To check if a given method of an object is callable you should pass an array where the first item is the object and the second item is the name of the method:

```php
is_callable( array( $jp_status, 'is_staging_site' ) )
```

**Review by rodrigoprimo — CHANGES_REQUESTED** [review]
IMO the solution proposed in this PR is a good one, but there is a bug that needs to be fixed before merging. I also left a suggestion to change the organization of the code. More information in inline comments.

**Comment by rodrigoprimo** [comment]
I forgot to mention that I was not able to reproduce this warning during the OBW but I didn't spend much time investigating why. To test the changes proposed in this PR, I changed the visibility of the method WC_Tracker::get_tracking_data() to public and called it directly.

File: includes/class-wc-tracker.php (hunk 1 above)
Comment (peterfabian) [reply includes/class-wc-tracker.php]: Agreed, was thinking about this today as well.

File: includes/class-wc-tracker.php (hunk 2 above)
Comment (peterfabian) [reply includes/class-wc-tracker.php]: You're right of course. Thanks, fixed both items in https://github.com/woocommerce/woocommerce/pull/25670/commits/88b8c006dbd92e5f64ebc35ee5658c0fcac4c0a1, I believe.

**Review by rodrigoprimo — APPROVED** [review]
Looks good to me now. Thanks for the fix.

File: includes/class-wc-tracker.php [hunk 3]
```diff
@@ -86,6 +86,30 @@ private static function get_last_send_time() {
...
+	 * it uses Jetpack::is_staging_site.
+	 *
+	 * @return bool
+	 */
+	private static function is_jetpack_staging_site() {
+		$is_jp_staging = false;
+		if ( class_exists( '\Automattic\Jetpack\Status' ) ) {
+			// Preferred way of checking with Jetpack 8.1+.
+			$jp_status = new \Automattic\Jetpack\Status();
+			if ( is_callable( array( $jp_status, 'is_staging_site' ) ) && $jp_status->is_staging_site() ) {
```
Comment (kraftbj) [inline includes/class-wc-tracker.php]: There are versions of Jetpack with `\Automattic\Jetpack\Status` before `is_staging_site` was added to it and would still need to use the old fallback.

Comment (peterfabian) [reply includes/class-wc-tracker.php]: Thanks, fixed in 3dcb3e0.

**Comment by peterfabian** [comment]
Tested on JN with JP 8.2.3, 8.1, 8.0 and 7.9, it seems like it doesn't throw any deprecations anymore.

**Review by vedanshujain — APPROVED** [review]
LGTM! Like @rodrigoprimo  I was not able to repro on OBW so I called get_tracking_data directly to test.
