### PR TITLE
Redirect to canonical product permalink

### LINKED ISSUE #24244: %product_cat% URL Issue
**Describe the bug**
When product URLs are set to a structure of `/any-text-here/%product_cat%/` in the Permalink settings (`Settings > Permalinks`), anything can be input for the `/%product_cat%/` section and the product will still display without issue: 

https://cld.wthms.co/qODuRj
Image link: https://cld.wthms.co/qODuRj

Example shown here: 

https://cld.wthms.co/V2lU7y
Screencast link: https://cld.wthms.co/V2lU7y

It's particularly an issue as Google is still showing old, deleted categories under coverage but not indexed as "Alternate page with proper canonical tag" because these products still resolve from the URLs as any text string can be input.

**To Reproduce**
1. Go to 'Settings > Permalinks' and set something like this: https://cld.wthms.co/YUSEIa (where `/product/` can be anything.
2. Go to the frontend of any product and change the `/product/` section of the url to anything.
3. The URL still works without issue.

**Screenshots**

https://cld.wthms.co/qODuRj
Image link: https://cld.wthms.co/qODuRj

Example shown here: 

https://cld.wthms.co/V2lU7y
Screencast link: https://cld.wthms.co/V2lU7y

**Expected behavior**
Not sure if this is expected behavior, but this is an issue for sites that may have updated the `/product/` section of the URL because Google will still show the old, deleted URLs (as "Alternate page with proper canonical tag") because these products still resolve from the URLs as any text string can be input.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
`
### WordPress Environment ###

WordPress address (URL): https://allthingsgutenberg.mystagingwebsite.com
Site address (URL): https://allthingsgutenberg.mystagingwebsite.com
WC Version: 3.6.5
Log Directory Writable: ✔
WP Version: 5.2.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 7.2.19
PHP Post Max Size: 100 MB
PHP Time Limit: 300
PHP Max Input Vars: 6144
cURL Version: 7.65.0
OpenSSL/1.0.1t

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.1.17-MariaDB
Max Upload Size: 100 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.6.5
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Total Database Size: 12.40MB
Database Data Size: 10.41MB
Database Index Size: 1.99MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_order_itemmeta: Data: 0.08MB + Index: 0.03MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_advanced_notifications: Data: 0.02MB + Index: 0.00MB
wp_advanced_notification_triggers: Data: 0.02MB + Index: 0.00MB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_comments: Data: 0.08MB + Index: 0.09MB
wp_itsec_distributed_storage: Data: 0.02MB + Index: 0.02MB
wp_itsec_fingerprints: Data: 0.02MB + Index: 0.03MB
wp_itsec_geolocation_cache: Data: 0.02MB + Index: 0.03MB
wp_itsec_lockouts: Data: 0.02MB + Index: 0.08MB
wp_itsec_logs: Data: 0.02MB + Index: 0.09MB
wp_itsec_temp: Data: 0.02MB + Index: 0.06MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_ms_snippets: Data: 0.02MB + Index: 0.00MB
wp_options: Data: 3.02MB + Index: 0.05MB
wp_postmeta: Data: 2.13MB + Index: 0.27MB
wp_posts: Data: 1.28MB + Index: 0.09MB
wp_snippets: Data: 0.02MB + Index: 0.00MB
wp_termmeta: Data: 0.02MB + Index: 0.03MB
wp_terms: Data: 0.02MB + Index: 0.03MB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wp_usermeta: Data: 0.02MB + Index: 0.03MB
wp_users: Data: 0.02MB + Index: 0.05MB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB
wp_wc_booking_relationships: Data: 0.02MB + Index: 0.03MB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_wc_gpf_render_cache: Data: 0.02MB + Index: 0.02MB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB
wp_wc_points_rewards_user_points: Data: 0.02MB + Index: 0.03MB
wp_wc_points_rewards_user_points_log: Data: 0.02MB + Index: 0.05MB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_gpf_google_taxonomy: Data: 2.52MB + Index: 0.00MB
wp_woocommerce_shipping_quotes: Data: 0.02MB + Index: 0.06MB
wp_wpml_mails: Data: 0.34MB + Index: 0.00MB
wp_yoast_seo_links: Data: 0.02MB + Index: 0.02MB
wp_yoast_seo_meta: Data: 0.02MB + Index: 0.00MB

### Post Type Counts ###

attachment: 102
custom_css: 1
customize_changeset: 15
jetpack_migration: 2
jp_img_sitemap: 4
jp_sitemap: 4
jp_sitemap_master: 4
nav_menu_item: 8
oembed_cache: 1
page: 12
post: 1
product: 20
product_variation: 21
revision: 28
scheduled-action: 73
shop_coupon: 10
shop_order: 26
wc_order_status: 7

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (3) ###

Akismet Anti-Spam: by Automattic – 4.1.2
WooCommerce Admin: by WooCommerce – 0.16.0
WooCommerce: by Automattic – 3.6.5

### Inactive Plugins (35) ###

Advanced Database Cleaner: by Younes JFR. – 2.0.0
Classic Editor: by WordPress Contributors – 1.5
Code Snippets: by Shea Bunge – 2.13.3
Disable Real MIME Check: by Sergey Biryukov – 1.0
Gutenberg: by Gutenberg Team – 6.1.1
Homepage Control: by WooThemes – 2.0.3
iThemes Security: by iThemes – 7.4.0
Jetpack by WordPress.com: by Automattic – 7.5.3
Loco Translate: by Tim Whitlock – 2.3.0
Storefront Mega Menus: by WooCommerce – 1.6.2 – Not tested with the active version of WooCommerce
Storefront Powerpack: by WooCommerce – 1.5.0
WC Custom Thank You: by Nicola Mustone – 1.2.1 – Not tested with the active version of WooCommerce
WooCommerce Advanced Notifications: by WooCommerce – 1.2.16
WooCommerce Amazon Pay Gateway: by WooCommerce – 1.10.1
WooCommerce AvaTax: by SkyVerge – 1.7.0 – 1.7.3 is available – Not tested with the active version of WooCommerce
WooCommerce Blocks: by Automattic – 2.2.1
WooCommerce Checkout Field Editor: by WooCommerce – 1.5.21
WooCommerce Contact for Shipping Quote: by Jeroen Sormani – 1.0.0
WooCommerce FedEx Shipping: by WooCommerce – 3.4.19
WooCommerce Google Analytics Integration: by WooCommerce – 1.4.10
WooCommerce Google Product Feed: by Ademti Software Ltd. – 7.6.6 – 7.9.1 is available – Not tested with the active version of WooCommerce
WooCommerce Google Product Reviews Feed for Google Shopping Ads: by WebPerfect.com – 1.1 – Not tested with the active version of WooCommerce
WooCommerce Order Status Manager: by SkyVerge – 1.9.4
WooCommerce PayPal Checkout Gateway: by WooCommerce – 1.6.16
WooCommerce Points and Rewards: by WooCommerce – 1.6.22
WooCommerce Product CSV Import Suite: by WooCommerce – 1.10.23
WooCommerce Product Reviews Pro: by SkyVerge – 1.12.3 – 1.13.5 is available – Not tested with the active version of WooCommerce
WooCommerce Quick View: by WooCommerce – 1.2.1 – 1.2.3 is available
WooCommerce Services: by Automattic – 1.21.0
WooCommerce Stripe Gateway: by WooCommerce – 4.2.3
WooCommerce Subscriptions: by Automattic – 2.5.7
WP Crontrol: by John Blackbourn & crontributors – 1.7.1
WP Mail Logging: by Christian Zöller – 1.9.1
WP Staging: by WP-Staging – 2.6.1
Yoast SEO: by Team Yoast – 11.7 – Not tested with the active version of WooCommerce

### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
object-cache.php: Memcached

### Must Use Plugins (1) ###

WP Staging Optimizer: by René Hermenau – 1.1

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: booking (booking)
external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #8 - /shop/
Cart: #9 - /cart/
Checkout: #10 - /checkout/
My account: #11 - /my-account/
Terms and conditions: #3370 - /terms-conditions/

### Theme ###

Name: Storefront
Version: 2.5.1
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 71
Oldest: 2019-06-28 07:10:09 -0500
Newest: 2019-07-27 08:42:09 -0500

Pending: 2
Oldest: 2019-07-27 09:08:32 -0500
Newest: 2019-07-29 08:43:14 -0500

Canceled: 0
Oldest: –
Newest: –

In-progress: 0
Oldest: –
Newest: –

Failed: 0
Oldest: –
Newest: –

`
```
</details>

### PR DESCRIPTION
**Pull request by coreymckrill**
### Changes proposed in this Pull Request:

This ensures that if product permalinks are set to include the `%product_cat%` replacement token, arbitrary values for that part of the URL will redirect to the canonical product category value, rather than successfully loading the single product page.

This changeset is largely based on the gist linked to in [this comment](https://github.com/woocommerce/woocommerce/issues/24244#issuecomment-2359635024). (props @barryhughes). I decided to go with `301` for the http status code, because presumably a product's categories won't change that often.

I haven't been able to think of a good way to unit test this, since it involves making requests to permalinks and doing template redirects (cURL doesn't seem to work in the test environment), but I'm open to ideas.

Fixes #24244

### How to test the changes in this Pull Request:

1. Before checking out this branch, follow the reproduction steps in #24244 to see the behavior without this change.
2. After checking out this branch, try the same steps. This time it should redirect to the correct URL whenever you try to put something arbitrary in the `%product_cat%` part of the URL.

Other things to try:

* Try changing the URL for a product that has a single product category term that is the child of another term. And even one where the term is nested multiple levels deep.
* Update the permalink setting so that `%product_cat%` is somewhere else in the URL structure besides at the end, and see if the redirection still works.
* Try changing the case of some of the characters in the `%product_cat%` value and see if it still redirects (it should).
* Try some other views besides single product view (e.g. post type or taxonomy archive) and make sure the redirect isn't happening in unexpected places.
* What else could cause this to break or cause an endless redirect loop?

### CODE REVIEW

File: plugins/woocommerce/changelog/fix-24244-custom-permalink [hunk 1]
```diff
@@ -0,0 +1,4 @@
+Significance: minor
+Type: fix
+
+Redirect arbitrary term values wto the canonical value when product_cat is part of the product permalink structure
```
Comment (barryhughes) [inline plugins/woocommerce/changelog/fix-24244-custom-permalink]: Small typo:

```suggestion
Redirect arbitrary term values to the canonical value when product_cat is part of the product permalink structure.
```

Also wondering (and please feel free to ignore, as I could be over-thinking it 🙌🏼) if it would be slightly clearer to more people if we describe the fix something like this:

```suggestion
Redirect to the canonical single page URL if the wrong category slug has been used.
```

File: plugins/woocommerce/includes/wc-product-functions.php [hunk 2]
```diff
@@ -282,6 +282,47 @@ function wc_product_post_type_link( $permalink, $post ) {
...
+ *
+ * If other values are used in this part of the permalink, it will be redirected.
+ *
+ * @return void
+ */
+function wc_product_canonical_redirect(): void {
+	global $wp_rewrite;
+
+	if (
+		! did_action( 'woocommerce_init' )
```
Comment (barryhughes) [inline plugins/woocommerce/includes/wc-product-functions.php:296]: I think this may be superfluous now we're placing the logic inside WooCommerce itself ... then again, perhaps the safest thing is to leave it (from a defensive code perspective, as we often come up against unexpected conditions) 🤔

File: plugins/woocommerce/includes/wc-product-functions.php [hunk 3]
```diff
@@ -282,6 +282,47 @@ function wc_product_post_type_link( $permalink, $post ) {
...
+		return;
+	}
+
+	// phpcs:ignore WordPress.Security.NonceVerification.Recommended
+	$query_vars = isset( $_GET ) && is_array( $_GET ) ? $_GET : array();
+
+	wp_safe_redirect( add_query_arg( $query_vars, wc_get_product( get_the_ID() )->get_permalink() ), 301 );
+	exit();
+}
+add_action( 'template_redirect', 'wc_product_canonical_redirect', 5 );
```
Comment (barryhughes) [inline plugins/woocommerce/includes/wc-product-functions.php:324]: Mostly just asking because curious ... why the non-default priority?

**Review by barryhughes — APPROVED** [review]
Great, tests well. Left a couple of questions, and a possible correction for the changelog entry, but no real blockers.

Testing notes:

- When `%product_cat%` is used in the URL, we now redirect as described in the testing instructions.
- With or without `%product_cat%` in our URLs, single product pages, the shop page, the cart and my account areas all work as expected.
- Navigating the store via ugly permalinks continues to work as expected.

File: plugins/woocommerce/changelog/fix-24244-custom-permalink (hunk 1 above)
Comment (coreymckrill) [reply plugins/woocommerce/changelog/fix-24244-custom-permalink]: I like the second one, but I think it should say "product" instead of "page":

```suggestion
Redirect to the canonical single product URL if the wrong category slug has been used.
```

File: plugins/woocommerce/includes/wc-product-functions.php (hunk 2 above)
Comment (coreymckrill) [reply plugins/woocommerce/includes/wc-product-functions.php:296]: Yeah, I think there are a lot of other places where we make this `did_action` check within WC... I'm inclined to leave it there.

File: plugins/woocommerce/includes/wc-product-functions.php (hunk 3 above)
Comment (coreymckrill) [reply plugins/woocommerce/includes/wc-product-functions.php:324]: I did an audit of all the callbacks we're adding to the `template_redirect` hook and nearly all of them are on the default priority. Some of them are also related to single product pages, so it seemed like we would want this to resolve first before other stuff runs.

**Comment by coreymckrill** [comment]
> Navigating the store via ugly permalinks continues to work as expected.

Good idea checking this!

File: plugins/woocommerce/changelog/fix-24244-custom-permalink (hunk 1 above)
Comment (barryhughes) [reply plugins/woocommerce/changelog/fix-24244-custom-permalink]: oh, yes!
