### PR TITLE
Adding legal messaging and fixing click behavior on task list experiment

### LINKED ISSUE #32762: [WC 6.5 beta1] WCPay task add missing legal message within task
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

The WooCommerce Payments task for experiment one is missing a legal message within the task and prevents a user from clicking the task and redirecting (forcing the user to click in the header).
The WooCommerce Payments task for experiment two is showing the terms of service, but the copy should be updated to match the design.

### Expected behavior

- Clicking in the WCPayments task should redirect the user to the WCPayments onboarding in experiment 1
- We need to display the legal message (the copy for both experiments should match the design as linked to below):
_By setting up, you are agreeing to the [Terms of Service](https://wordpress.com/tos/)_

Extra context of expected behaviour is here: p1650634563738529-slack-C01CMSA1VHS

Updated design: 
* G9vi4e286yjdzyIdg8hBb1-fi-1607%3A156382 (Experiment 1)
* G9vi4e286yjdzyIdg8hBb1-fi-1607%3A171234 (Experiment 2)

### Steps to reproduce

1. Install the latest of `trunk`
2. Enable usage tracking
3. Install WooCommerce Payments in the Business features step
4. Visit Tools > WCA Test Helper > Experiments and enable woocommerce_tasklist_setup_experiment_2_2022_04
5. Visit the home screen and see the legal message is there, but also with a very large chunk of copy, this should match the design instead.
6. Visit Tools > WCA Test Helper > Experiments and enable woocommerce_tasklist_setup_experiment_1_2022_04
7. Visit the home screen and see that the legal message is missing in the WCPaymens task, try clicking the task, and notice how it doesn't do anything. Forcing the user to click the `Verify details` in the header instead.

### WordPress Environment

WooCommerce 6.5 Beta 1

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by joelclimbsthings**
* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

There are a few issues with the WCPay task and the active task list experiments:
`woocommerce_tasklist_setup_experiment_1_2022_04`
- Missing legal text
- Click behavior not functioning

`woocommerce_tasklist_setup_experiment_2_2022_04`
- Legal text does not match design
- Clicking on legal terms and conditions link still follows task click as well

Closes #32762  .

**Experiment 1:**
image

**Experiment 2:**
image

### How to test the changes in this Pull Request:

1. Checkout branch on fresh site.
2. Install the WC Admin Test Helper plugin
3. Fill out OBW, and ensure that you enable marketing.
4. Be sure to install WCPay on the Business Step of the OBW.
5. Use WC Admin Test Helper to enable `woocommerce_tasklist_setup_experiment_1_2022_04` experiment.
6. Go back to Homescreen.
7. Observe WCPay task, which should now include legal text with Terms and Conditions link.
8. Click Terms link, ensure that opens the terms and conditions in a new tab.
9. Go back to setup task list, and click the WCPay task. Ensure that it directs you to WCPay Connect screen.
10. Use WC Admin Test Helper to disable that experiment, and enable `woocommerce_tasklist_setup_experiment_2_2022_04` instead. 
11. Go back to Homescreen and click visible terms link. Ensure it works as expected.
12. Click WCPay task again and ensure it directs to WCPay Connect screen as expected.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?
* [x] Have you created a changelog file by running `pnpm nx affected --target=changelog`?

### FOR PR REVIEWER ONLY:

* [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

File: plugins/woocommerce-admin/client/two-column-tasks/task-list-item-two-column.tsx [hunk 1]
```diff
@@ -0,0 +1,114 @@
+/**
```
Comment (joelclimbsthings) [inline plugins/woocommerce-admin/client/two-column-tasks/task-list-item-two-column.tsx:1]: In order to resolve the issues with `woocommerce_tasklist_setup_experiment_1_2022_04`, I needed to add slotfill behavior again, which involved creating a separate version of the `task-list-item.tsx` file (this file). I spent some time trying to utilize the same `task-list-item.tsx` for both experiments, but the subtle differences in styling and UI were creating a good amount of time-consuming work, that would likely be bug prone. Since in the end only a single version will survive, I didn't see an issue with simply creating another file.

File: plugins/woocommerce-admin/client/two-column-tasks/task-list-item-two-column.tsx [hunk 2]
```diff
@@ -0,0 +1,114 @@
...
+			return (
+				<TaskItem
+					key={ taskId }
+					className={ className }
+					title={ title }
+					completed={ isComplete }
+					additionalInfo={ additionalInfo }
+					content={ content }
+					onClick={ ( e: React.ChangeEvent ) => {
+						if ( e.target.tagName === 'A' ) {
```
Comment (joelclimbsthings) [inline plugins/woocommerce-admin/client/two-column-tasks/task-list-item-two-column.tsx]: Necessary to prevent the click action when the "terms and conditions" link is clicked.

File: plugins/woocommerce-admin/client/two-column-tasks/task-list-item.tsx [hunk 3]
```diff
@@ -123,8 +123,8 @@ export const TaskListItem: React.FC< TaskListItemProps > = ( {
 					action={ () => {} }
 					actionLabel={ task.actionLabel }
 					{ ...props }
-					onClick={ () => {
-						if ( task.isDisabled ) {
+					onClick={ ( e: React.ChangeEvent ) => {
+						if ( task.isDisabled || e.target.tagName === 'A' ) {
```
Comment (joelclimbsthings) [inline plugins/woocommerce-admin/client/two-column-tasks/task-list-item.tsx:126]: Again, preventing click action when ancestor link is clicked.

File: plugins/woocommerce-admin/client/two-column-tasks/style.scss [hunk 4]
```diff
@@ -176,6 +176,7 @@
 			position: absolute;
 			width: 100%;
 			height: 100%;
+			pointer-events: none;
```
Comment (joelclimbsthings) [inline plugins/woocommerce-admin/client/two-column-tasks/style.scss:179]: The lack of this was preventing click events on terms and conditions link.

File: plugins/woocommerce-admin/client/two-column-tasks/task-list-item.tsx (hunk 3 above)
Comment (louwie17) [reply plugins/woocommerce-admin/client/two-column-tasks/task-list-item.tsx:126]: Nice fix 👍 
The addition of `e: React.ChangeEvent` does give a TypeScript error for me. I was able to fix it by rebasing (Moon's latest fix) and changing this line https://github.com/woocommerce/woocommerce/blob/trunk/packages/js/experimental/src/experimental-list/task-item/index.tsx#L42
to:
`onClick: React.MouseEventHandler< HTMLElement >;`

**Review by louwie17 — CHANGES_REQUESTED** [review]
Great work on this @joelclimbsthings, the changes tested very well 👍 
I just left one comment in relation to a TS error I was getting on build, that is my only suggested fix.

**Review by louwie17 — APPROVED** [review]

**Review by jacob-sewell — APPROVED** [review]
Tests well.
