### PR TITLE
[Experimental] Add to Cart + Options: support missing hooks in variable products

### LINKED ISSUE #58358: Blockified Add to Cart + Options block: Variable Product form is missing some PHP hooks
When we added support for PHP hooks in the *Add to Cart + Options* block ([https://github.com/woocommerce/woocommerce/pull/55234](https://github.com/woocommerce/woocommerce/pull/55234)) I missed some hooks for the variable product form, that's because I only checked the [variable.php](https://github.com/woocommerce/woocommerce/blob/4895a28dbb4c741ceea50a47aaa85499925fde59/plugins/woocommerce/templates/single-product/add-to-cart/variable.php) template and not the [variation-add-to-cart-button.php](https://github.com/woocommerce/woocommerce/blob/4895a28dbb4c741ceea50a47aaa85499925fde59/plugins/woocommerce/templates/single-product/add-to-cart/variation-add-to-cart-button.php) template. 😅 

This issue is about adding the missing hooks, if I'm not wrong they are:

* `woocommerce_before_add_to_cart_button`
* `woocommerce_before_add_to_cart_quantity`
* `woocommerce_after_add_to_cart_quantity`
* `woocommerce_after_add_to_cart_button`

### PR DESCRIPTION
**Pull request by Aljullu**
### Changes proposed in this Pull Request:

Closes #58358.

This PR adds some extra PHP actions to the Add to Cart + Options compatibility layer when displaying variable products. I also updated the `@since` version of all of them to 10.0.0, which is when the block is planned to be released.

#### Preparation

0. Install and activate the [WooCommerce Beta Tester](https://woocommerce.com/products/woocommerce-beta-tester/) extension.
0. Go to _WooCommerce Admin Test Helper_ > _Features_ and enable `experimental-blocks` and `blockified-add-to-cart`.
1. Go to _Appearance_ > _Editor_ > _Templates_ > _Single Product_.
2. Click on the _Add to Cart with Options_ block and update to the blockified version.

##### Testing a real extension

3. Install [Product Add-Ons](https://woocommerce.com/products/product-add-ons/).
4. Edit a variable product and add some add-ons to it.
5. In the frontend, add that product to the cart (while selecting some of the add-ons).
6. Verify the product was added correctly to cart, including the add-ons.

Before | After
--- | ---
image | image

##### Testing PHP hooks

6. Add this PHP code snippet to your store (you can use the [Code Snippets](https://wordpress.org/plugins/code-snippets/) plugin):
```PHP
$actions = [
	'woocommerce_before_variations_form',
	'woocommerce_before_add_to_cart_quantity',
	'woocommerce_after_add_to_cart_quantity',
	'woocommerce_before_add_to_cart_button',
	'woocommerce_after_add_to_cart_button',
	'woocommerce_before_single_variation',
	'woocommerce_single_variation',
	'woocommerce_after_single_variation',
	'woocommerce_after_variations_table',
];

foreach ( $actions as $action ) {
	add_action( $action, function() use ( $action ) {
		echo '<p>' . $action . ' run</p>';
	} );
}
```

7. In the frontend, visit the template of a variable product.
8. Verify hooks are rendered correctly.

### CODE REVIEW

File: plugins/woocommerce/src/Blocks/BlockTypes/AddToCartWithOptions/AddToCartWithOptions.php [hunk 1]
```diff
@@ -220,30 +220,69 @@ function ( $variation ) {
...
+					do_action( 'woocommerce_after_variations_table' );
+					/**
+					 * Hook: woocommerce_before_single_variation.
+					 *
+					 * @since 10.0.0
+					 */
+					do_action( 'woocommerce_before_single_variation' );
+
+					remove_action( 'woocommerce_single_variation', 'woocommerce_single_variation', 10 );
+					remove_action( 'woocommerce_single_variation', 'woocommerce_single_variation_add_to_cart_button', 20 );
```
Comment (dinhtungdu) [inline plugins/woocommerce/src/Blocks/BlockTypes/AddToCartWithOptions/AddToCartWithOptions.php:267]: Can you explain why do we need to remove these actions before `do_action` call and add them back after. We don't want `woocommerce_single_variation()` and `woocommerce_single_variation_add_to_cart_button()` included in the block, right?

Comment (Aljullu) [reply plugins/woocommerce/src/Blocks/BlockTypes/AddToCartWithOptions/AddToCartWithOptions.php:267]: Yes, I added an explanatory comment in 8a9fd7776168ea4c5cf7a6d7cf62dec1ad9b2505. Those functions render markup which in our case is handled by blocks. So if we don't remove these actions, we end up with a duplicate _Add to Cart_ button, for example. They are added in:

https://github.com/woocommerce/woocommerce/blob/60dfdbc6c971e37fe33d238cd654a91f807d38c7/plugins/woocommerce/includes/wc-template-hooks.php#L187-L188

**Review by dinhtungdu — APPROVED** [review]
Thanks for adding the comment. This is LGTM!


#### 🖼️ Screenshots/ screen recordings
image

#### 📝 List of functionality tested / steps followed

Tested with Product Add-ons, both global and product specific addons.

#### 🌐 Site details
<details><summary>System Status Report</summary>

```
### WordPress Environment ###

WordPress address (URL): [Redacted]
Site address (URL): [Redacted]
WC Version: 10.0.0-dev
Legacy REST API Package Version: The Legacy REST API plugin is not installed on this site.
Action Scheduler Version: ✔ 3.9.2
Log Directory Writable: ✔
WP Version: 6.8.1
WP Multisite: –
WP Memory Limit: 2 GB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.25.4
Server Architecture: Darwin 24.5.0 arm64
PHP Version: 7.4.33
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 8.5.0
OpenSSL/3.1.4

SUHOSIN Installed: –
MySQL Version: 8.0.33
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

[REDACTED]

### Post Type Counts ###

attachment: 25
global_product_addon: 1
page: 17
post: 7
product: 19
product_tab: 1
product_variation: 7
revision: 159
shop_order_placehold: 1
wp_font_face: 36
wp_font_family: 12
wp_global_styles: 3
wp_navigation: 1
wp_template: 6
wp_template_part: 8

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (4) ###

Laravel DD for Wordpress: by Peter Hegman – 1.0.1
WooCommerce Beta Tester: by WooCommerce – 3.0.0
WooCommerce Product Add-Ons: by Woo – 7.8.1 (update to version 7.9.0 is available)
WooCommerce: by Automattic – 10.0.0-dev

### Inactive Plugins (13) ###

Akismet Anti-spam: Spam Protection: by Automattic - Anti-spam Team – 5.3.6
bbPress: by The bbPress Contributors – 2.6.13
Block Hooks Experiments for WooCommerce: by Automattic –
Custom Product Tabs Manager: by Addify – 1.2.2
Gutenberg: by Gutenberg Team – 20.3.0
Hello Dolly: by Matt Mullenweg – 1.7.2
Product Filters for WooCommerce: by WooCommerce – 1.4.38
Query Monitor: by John Blackbourn – 3.17.2
What Can Wp Scripts Do: by The WordPress Contributors – 0.1.0
WooCommerce: by Automattic – 9.7.1 (update to version 9.8.5 is available)
WooCommerce PayPal Payments: by PayPal – 3.0.0 (update to version 3.0.6 is available)
WooPayments: by WooCommerce – 9.1.0 (update to version 9.4.0 is available)
WP BASIC Auth: by wokamoto – 1.1.4

### Must Use Plugins (1) ###

WooCommerce Product Details Extension Demo: by  – 1.0.0

### Settings ###

Legacy API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 1
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –
Enabled Features: analytics
marketplace
order_attribution
site_visibility_badge
remote_logging
email_improvements
point_of_sale
custom_order_tables


### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 1 MB

### WC Pages ###

Shop base: #7 - /shop/
Cart: #8 - /cart/ -  Contains the woocommerce/cart block
Checkout: #9 - /checkout/ -  Contains the woocommerce/checkout block
My account: #10 - /my-account/ -  Contains the [woocommerce_my_account] shortcode
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty-Five
Version: 1.2
Author URL: https://wordpress.org
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
Theme type: Block theme
WooCommerce Support: ❌ Not declared

### Templates ###

Overrides: /Users/tung/workspace/woocommerce/plugins/woocommerce/templates/block-notices/error.php
/Users/tung/workspace/woocommerce/plugins/woocommerce/templates/block-notices/notice.php
/Users/tung/workspace/woocommerce/plugins/woocommerce/templates/block-notices/success.php


### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
experimental-blocks
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
minified-js
mobile-app-banner
onboarding
onboarding-tasks
pattern-toolkit-full-composability
payment-gateway-suggestions
product-custom-fields
printful
remote-inbox-notifications
remote-free-extensions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page
async-product-editor-category-field
launch-your-store
add-to-cart-with-options-stepper-layout
blockified-add-to-cart
disable-core-profiler-fallback

Disabled Features: product-data-views
experimental-iapi-mini-cart
experimental-iapi-runtime
coming-soon-newsletter-template
product-pre-publish-modal
settings
product-editor-template-system
use-wp-horizon
beta-tester-slotfill-examples

Daily Cron: ✔ Next scheduled: 2025-06-04 10:10:56 +00:00
Options: ✔
Notes: 75
Onboarding: completed

### Action Scheduler ###

Complete: 120
Oldest: 2025-05-05 00:34:37 +0000
Newest: 2025-06-04 01:47:21 +0000

Failed: 7
Oldest: 2025-03-05 03:00:25 +0000
Newest: 2025-05-20 11:45:14 +0000

Pending: 1
Oldest: 2025-06-04 04:33:18 +0000
Newest: 2025-06-04 04:33:18 +0000


### Status report information ###

Generated at: 2025-06-04 01:49:25 +00:00
```
</details>
