### PR TITLE
Change when stock notif emails are triggered

### LINKED ISSUE #31664: Low stock email is not triggered via the API
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

4686173-zen

User here says that they have an external system that updates product stock via the API. When the stock goes below the low or no stock threshold, they do *not* receive an email. 

@vedanshujain [confirmed this was a bug](https://a8c.slack.com/archives/C7U3Y3VMY/p1642191794037300) and not intentional, hence this bug report.

### Expected behavior

Low stock email should be triggered via API when stock goes below the low stock threshold.

### Actual behavior

User mentioned:

>  I have tested over API via postman via this call:
> https://visitsiberia.voxop.dk/wp-json/wc/v3/products/16440?stock_quantity=0
> This does write down stock but does not trigger "sold out" or "low
> stock" emails.

### Steps to reproduce

`wc_maybe_reduce_stock_levels ()` (which eventually fires off the email) is only hooked into order-related actions here: https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/includes/wc-stock-functions.php#L112-L115

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://woosite.mystagingwebsite.com
Site address (URL): https://woosite.mystagingwebsite.com
WC Version: 6.1.0
REST API Version: ✔ 6.1.0
WC Blocks Version: ✔ 6.5.1
Action Scheduler Version: ✔ 3.4.0
WC Admin Version: ✔ 3.0.3
Log Directory Writable: ✔
WP Version: 5.8.3
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 7.4.27
PHP Post Max Size: 2 GB
PHP Time Limit: 1200
PHP Max Input Vars: 6144
cURL Version: 7.80.0
OpenSSL/1.1.1d

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.4.22-MariaDB-log
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 6.1.0
WC Database Prefix: wp_
Total Database Size: 16.85MB
Database Data Size: 8.19MB
Database Index Size: 8.66MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.17MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.33MB + Index: 0.41MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.30MB + Index: 0.34MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.19MB + Index: 0.16MB + Engine InnoDB
wp_advanced_notifications: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_advanced_notification_triggers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_automatewoo_abandoned_carts: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_automatewoo_customers: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_automatewoo_customer_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_events: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_guests: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_automatewoo_guest_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_log_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_queue: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_queue_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_referrals: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_automatewoo_referral_advocate_keys: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_automatewoo_referral_invites: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_ced_ebay_accounts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ced_ebay_discription_template: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ced_ebay_logs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ced_ebay_profiles: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ced_ebay_shipping: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.14MB + Index: 0.09MB + Engine InnoDB
wp_FmeCCFA_fields: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_followup_coupons: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_coupon_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_customers: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_followup_customer_carts: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_customer_notes: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_followup_customer_orders: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_followup_email_excludes: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_email_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_email_orders: Data: 0.05MB + Index: 0.09MB + Engine InnoDB
wp_followup_email_tracking: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_followup_followup_history: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_followup_order_categories: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_order_items: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_subscribers: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_followup_subscribers_to_lists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_subscriber_lists: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_gla_budget_recommendations: Data: 0.22MB + Index: 0.14MB + Engine InnoDB
wp_gla_merchant_issues: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
wp_gla_shipping_rates: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gla_shipping_times: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_ms_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 1.06MB + Index: 0.14MB + Engine InnoDB
wp_postmeta: Data: 1.50MB + Index: 3.00MB + Engine InnoDB
wp_posts: Data: 0.34MB + Index: 0.20MB + Engine InnoDB
wp_say_what_strings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_taxjar_record_queue: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_termmeta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wcpv_commissions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcpv_per_product_shipping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_bookings_availability: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_bookings_availabilitymeta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_booking_relationships: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_deposits_payment_plans: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_deposits_payment_plans_schedule: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_bundle_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.05MB + Index: 0.11MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.36MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_points_rewards_user_points: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_points_rewards_user_points_log: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_pos_grid_tiles: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.05MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_warranty_products: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_zapier_history: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_bis_activity: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_bis_notifications: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_woocommerce_bis_notificationsmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_bundled_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_bundled_items: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_gc_activity: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_gc_cards: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_gc_cardsmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_per_product_shipping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_pickup_locations_geodata: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_prl_deploymentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_prl_deployments: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_prl_frequencies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_prl_tracking_clicks: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_prl_tracking_conversions: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_prl_tracking_views: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_table_rates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_software_activations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_software_licenses: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_square_customers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_subscription_downloads: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpml_mails: Data: 1.52MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

afadv_qty: 1
af_crt_order_rstrct: 1
attachment: 40
aw_workflow: 13
bookable_person: 6
bookable_resource: 2
customize_changeset: 4
custom_css: 2
event_ticket: 1
follow_up_email: 1
gtw_custom_fields: 3
gtw_rules: 1
mc4wp-form: 1
nav_menu_item: 4
order_shipment: 4
page: 29
post: 3
pos_outlet: 1
pos_receipt: 1
pos_register: 1
prl_engine: 1
product: 164
product_variation: 170
revision: 64
rts_order_rule: 1
shipping_package: 3
shop_coupon: 5
shop_order: 227
shop_order_refund: 5
shop_subscription: 46
slide: 1
user_request: 1
warranty_request: 1
wc-donation: 1
wcpf_item: 12
wcpf_project: 1
wc_booking: 23
wc_membership_plan: 1
wc_order_status: 11
wc_pickup_location: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (6) ###

Cart and Order Restrictions: by Addify – 1.0.1
WooCommerce Bookings: by WooCommerce – 1.15.43 (update to version 1.15.49 is available)
WooCommerce Stripe Gateway: by WooCommerce – 6.0.0
WooCommerce Payments: by Automattic – 3.5.0
WooCommerce: by Automattic – 6.1.0
WP Mail Logging: by Wysija – 1.10.2

### Inactive Plugins (67) ###

Akismet Anti-Spam: by Automattic – 4.2.1
AutomateWoo: by WooCommerce – 5.5.4
AutomateWoo - Refer A Friend Add-on: by WooCommerce – 2.6.2
Bookings Helper: by WooCommerce – 1.0.3
Classic Widgets: by WordPress Contributors – 0.2
Code Snippets: by Code Snippets Pro – 2.14.1
eBay Integration for Woocommerce: by CedCommerce – 2.0.4
Facebook for WooCommerce: by Facebook – 2.6.8
Google Listings and Ads: by WooCommerce – 1.10.0
Jetpack: by Automattic – 10.6-a.1
Loco Translate: by Tim Whitlock – 2.5.5
MC4WP: Mailchimp for WordPress: by ibericode – 4.8.6
Meks Quick Plugin Disabler: by Meks – 1.0
Order Restrictions for WooCommerce: by FantasticPlugins – 1.3
Product Filters for WooCommerce: by WooCommerce – 1.2.5 (update to version 1.2.8 is available)
Say What?: by Ademti Software – 2.0.2
Storefront Mega Menus: by WooCommerce – 1.6.2
Storefront Powerpack: by WooCommerce – 1.6.1
Teams for WooCommerce Memberships: by SkyVerge – 1.6.0 (update to version 1.6.2 is available)
WooCommerce Accommodation Bookings: by WooCommerce – 1.1.24 (update to version 1.1.25 is available)
WooCommerce Additional Variation Images: by WooCommerce – 1.9.0
WooCommerce Advanced Ajax Layered Navigation: by WooCommerce – 1.6.0 (update to version 1.7.0 is available)
WooCommerce Advanced Notifications: by WooCommerce – 1.2.36
WooCommerce Advanced Shipping Packages: by Jeroen Sormani – 1.1.8
WooCommerce All Products For Subscriptions: by WooCommerce – 3.1.33 (update to version 3.2.0 is available)
WooCommerce Australia Post Shipping: by WooCommerce – 2.4.29 (update to version 2.4.31 is available)
WooCommerce AvaTax: by SkyVerge – 1.12.0 (update to version 1.15.0 is available)
WooCommerce Back In Stock Notifications: by SomewhereWarm – 1.2.0
WooCommerce Blocks: by Automattic – 6.7.0
WooCommerce Box Office: by WooCommerce – 1.1.34 (update to version 1.1.36 is available)
WooCommerce Brands: by WooCommerce – 1.6.25 (update to version 1.6.26 is available)
WooCommerce Bulk Stock Management: by WooCommerce – 2.2.31
WooCommerce Checkout Field Editor: by WooCommerce – 1.6.1 (update to version 1.7.0 is available)
WooCommerce Conditional Shipping and Payments: by WooCommerce – 1.11.0 (update to version 1.12.0 is available)
WooCommerce Currency Converter: by WooCommerce – 1.6.25 (update to version 1.6.26 is available)
WooCommerce Deposits: by WooCommerce – 1.5.6 (update to version 1.5.7 is available)
WooCommerce EU VAT Number: by WooCommerce – 2.4.1
WooCommerce Gift Cards: by WooCommerce – 1.10.0
WooCommerce Local Pickup Plus: by SkyVerge – 2.9.5 (update to version 2.9.10 is available)
WooCommerce Memberships: by SkyVerge – 1.22.5 (update to version 1.22.9 is available)
WooCommerce Min/Max Quantities: by WooCommerce – 2.4.24
WooCommerce Order Barcodes: by WooCommerce – 1.3.23 (update to version 1.3.24 is available)
WooCommerce Order Status Manager: by SkyVerge – 1.13.2 (update to version 1.13.3 is available)
WooCommerce PayFast Gateway: by WooCommerce – 1.4.19
WooCommerce PayPal Checkout Gateway: by WooCommerce – 2.1.3
WooCommerce PayPal Payments: by WooCommerce – 1.6.4
WooCommerce Points and Rewards: by WooCommerce – 1.7.2 (update to version 1.7.5 is available)
WooCommerce Pre-Orders: by WooCommerce – 1.5.30
WooCommerce Product Add-ons: by WooCommerce – 4.4.0 (update to version 4.5.0 is available)
WooCommerce Product Bundles: by WooCommerce – 6.13.2 (update to version 6.13.3 is available)
WooCommerce Product Recommendations: by WooCommerce – 1.4.15
WooCommerce Product Vendors: by WooCommerce – 2.1.51 (update to version 2.1.58 is available)
WooCommerce Royal Mail: by WooCommerce – 2.5.34 (update to version 2.5.39 is available)
WooCommerce Shipping & Tax: by WooCommerce – 1.25.20
WooCommerce Shipping Per Product v2: by WooCommerce – 2.3.13 (update to version 2.3.17 is available)
WooCommerce Ship to Multiple Addresses: by WooCommerce – 3.6.32 (update to version 3.6.39 is available)
WooCommerce Software Add-On: by WooCommerce – 1.7.19
WooCommerce Square: by WooCommerce – 2.7.0
WooCommerce Subscription Downloads: by WooCommerce – 1.1.31
WooCommerce Subscriptions: by WooCommerce – 3.1.5 (update to version 3.1.6 is available)
WooCommerce Table Rate Shipping: by WooCommerce – 3.0.36
WooCommerce UPS Shipping: by WooCommerce – 3.2.34 (update to version 3.2.37 is available)
WooCommerce USPS Shipping: by WooCommerce – 4.4.50 (update to version 4.4.69 is available)
WooCommerce Warranty Requests: by WooCommerce – 1.9.30 (update to version 1.9.31 is available)
WooCommerce Xero Integration: by WooCommerce – 1.7.38 (update to version 1.7.40 is available)
WP Crontrol: by John Blackbourn & crontributors – 1.12.0
WP STAGING: by WP-STAGING – 2.9.2

### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
object-cache.php: Memcached

### Must Use Plugins (1) ###

WP STAGING Optimizer: by René Hermenau – 1.4.1

### Settings ###

API Enabled: –
Force SSL: –
Currency: AUD ($)
Currency Position: left
Thousand Separator: 
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: accommodation-booking (accommodation-booking)
booking (booking)
bundle (bundle)
cpb_custom_product_boxes (cpb_custom_product_boxes)
external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #5 - /
Cart: #6 - /cart/
Checkout: #7 - /checkout/
My account: #8 - /my-account/
Terms and conditions: #15 - /communication-preferences/

### Theme ###

Name: Storefront
Version: 3.9.1
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### WooCommerce Payments ###

Version: 3.5.0
Connected to WPCOM: Yes
Blog ID: 191000457
Account ID: acct_1IpV8z2HOdqomKRe

### Action Scheduler ###

Complete: 765
Oldest: 2022-01-05 10:16:09 +0000
Newest: 2022-01-18 10:39:22 +0000

Failed: 12
Oldest: 2021-09-21 11:03:07 +0000
Newest: 2021-09-30 10:07:17 +0000

Pending: 20
Oldest: 2022-01-18 11:35:02 +0000
Newest: 2022-10-22 12:45:17 +0000

### Status report information ###

Generated at: 2022-01-18 11:24:29 +00:00
`

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by coreymckrill**
### Changes proposed in this Pull Request:

Moves the check for low/no stock to the point when a product's stock quantity is updated. This decouples the check from orders, since stock can also change in other contexts (such as updates via REST API).

**Open question:** When a product is out of stock, and back ordering is enabled, should an "out of stock" email get sent _every time_ a back order is made, or only the first time? We could potentially set a post meta flag when an "out of stock" email has already been sent (and clear the flag when the stock is changed back to a positive number).

Fixes #31664

### How to test the changes in this Pull Request:

1. Install a plugin like [WP Mail Logging](https://wordpress.org/plugins/wp-mail-logging/) on your test site so you can capture outgoing emails.
2. Create a product. Under Product data > Inventory, check the box for Stock management, and set the Quantity to 3. Under Allow backorders, select Allow, but notify customer.
3. Using cURL or your favorite API client, send a request like the following:
    ```
    curl --request POST \
      --url http://localhost:8888/wp-json/wc/v3/products/{product id} \
      --data '{
      "stock_quantity": 2
    }'
    ```
4. Check the mail log. There should be a message about the stock quantity for the product becoming "low" (this won't happen if you test on the trunk branch).
5. Send another request with `"stock_quantity": 1`. The same email should be sent again. Then send another with `"stock_quantity": 0`. This time the email should say the product is out of stock.
6. Now, with the product stock level at `0`, create a new order through the admin UI. Add the product, set the order status to On Hold, and save the order. Three new emails should be generated: a "new order" email, a "product backorder" email, and a "product out of stock" email. The product's stock level should now show as `-1`.
7. Note that if you set the product's stock level to a negative number through the API, a "product out of stock" email should be generated, but not the "product backorder", since the change is not associated with an order.

### CODE REVIEW

File: plugins/woocommerce/includes/data-stores/class-wc-product-data-store-cpt.php [hunk 1]
```diff
@@ -642,21 +642,21 @@ protected function update_post_meta( &$product, $force = false ) {
...
 						/**
-						* Action to signal that the value of 'stock_quantity' for a product is about to change.
-						*
-						* @since 4.9
-						*
-						* @param int $product The product whose stock is about to change.
-						*/
+						 * Action to signal that the value of 'stock_quantity' for a product is about to change.
+						 *
+						 * @param WC_Product $product The product whose stock is about to change.
```
Comment (naman03malhotra) [inline plugins/woocommerce/includes/data-stores/class-wc-product-data-store-cpt.php:656]: Curious why flip this one?, as I can see the pattern is @since is above @param in other places.

File: plugins/woocommerce/includes/wc-stock-functions.php [hunk 2]
```diff
@@ -261,6 +273,44 @@ function wc_trigger_stock_change_notifications( $order, $changes ) {
...
+ *
+ * This functionality was moved out of `wc_trigger_stock_change_notifications` in order to decouple it from orders,
+ * since stock quantity can also be updated in other ways.
+ *
+ * @param WC_Product $product        The product whose stock level has changed.
+ * @param int|float  $stock_quantity The new quantity of stock.
+ *
+ * @return void
+ */
+function wc_trigger_stock_change_actions( $product, $stock_quantity ) {
```
Comment (naman03malhotra) [inline plugins/woocommerce/includes/wc-stock-functions.php:287]: Since we extracted it out, it would be great if we cover this flow with tests from both REST API and UI, if not already present.

File: plugins/woocommerce/includes/data-stores/class-wc-product-data-store-cpt.php [hunk 3]
```diff
@@ -732,16 +732,52 @@ protected function handle_updated_props( &$product ) {
...
+				/**
+				 * Action to signal that the value of 'stock_quantity' for a product has changed.
+				 *
+				 * @since 3.0
+				 * @since 9.2 Added $stock parameter.
+				 *
+				 * @param WC_Product $product The variation whose stock has changed.
+				 * @param int|float  $stock   The new stock value.
+				 */
+				do_action( 'woocommerce_product_set_stock', $product, $product->get_stock_quantity() );
```
Comment (naman03malhotra) [inline plugins/woocommerce/includes/data-stores/class-wc-product-data-store-cpt.php:755]: I am curious why you passed stock quantity explicitly in the second param since we were already passing the product object as a whole.

**Review by naman03malhotra — COMMENTED** [review]
Very neat, thanks for working on it. Tests well for both REST API and UI flow. Left some minor comments to quench quriousity but overall looks great. Code is much cleaner now.

Nitpick: It would be also nice (not necessary) to add testing instructions from the UI flow perspective as well as the old logic has been refactored. As in, from add to cart flow. To test everything end to end.

image

File: plugins/woocommerce/includes/data-stores/class-wc-product-data-store-cpt.php (hunk 1 above)
Comment (coreymckrill) [reply plugins/woocommerce/includes/data-stores/class-wc-product-data-store-cpt.php:656]: I think I must have copied the block from somewhere else before updating the values. It's actually pretty common to have `@since` be the last thing in the doc block, if you do a regex search in the codebase with something like `\* @since .*\n\t+ \*/` there are lots of examples.

It would be nice if we had a standard for the order that doc block attributes should be in, but I don't think that exists at the moment...

File: plugins/woocommerce/includes/data-stores/class-wc-product-data-store-cpt.php (hunk 3 above)
Comment (coreymckrill) [reply plugins/woocommerce/includes/data-stores/class-wc-product-data-store-cpt.php:755]: 🤔 I think it was because in the other instance of the action in the other file, the stock value is derived separately from the product object. Looking at it again, the product object does get saved after updating the stock value, so it's probably not strictly necessary. It's also just convenient to have the value available separately without having to retrieve it as part of your callback function 🤷

File: plugins/woocommerce/includes/wc-stock-functions.php (hunk 2 above)
Comment (coreymckrill) [reply plugins/woocommerce/includes/wc-stock-functions.php:287]: Fair point. I'll look into it

Comment (coreymckrill) [reply plugins/woocommerce/includes/wc-stock-functions.php:287]: Tests added in 3712135482

**Review by naman03malhotra — APPROVED** [review]
Thanks for adding tests and making the changes 🚢

**Comment by JapeNZ** [comment]
Looks like this might be causing emails to be sent when we manually change the stock from product quick edit or in the product page itself.
It also seems to be firing the emails off whenever we create a duplicate product.
([Stock emails received when manually changing stock, and duplicating product](https://wordpress.org/support/topic/stock-emails-received-when-manually-changing-stock-and-duplicating-product/#post-18015845))

Any chance of adding an option to only send stock notificiation emails if the stock change is the result of an order being received?

I'm not sure why stock changes not related to orders would require notifications, as if it's not order based then the stock change is being intentionally done by the store owner so they're altready aware aren't they?

**Comment by asgeo1** [comment]
Having the same or similar issue, where this change seems to be causing WooCommerce to trigger out-of-stock emails when a product is programatically updated, even when the quantity itself hasn't changed from it's previous value.

My client was using All Import Pro plugin to bulk-update their products, and often the CSV file they are processing contains product quantities that are the same as the current values and haven't actually changed.

Pre v9.3, they claim it would not trigger any out-of-stock emails when programatically updating products, whereas the client tells me now every record being updated seems to triggers an email, even if not necessary.

I also question why programatic updates should trigger out-of-stock notifications. If you're trying to keep stock-on-hand in sync with some external source, it would seem unnecessary to trigger all those emails. Whereas I agree, out-of-stock notifications triggered from received orders are quite useful.

**Comment by dev-vip** [comment]
cheers for keep breaking things, we had to clear over 5k emails thanks to the latest code changes.

**Comment by dev-vip** [comment]
Think of wp all import importing/updating qty, it is automated, you just made it once again a manual process by having to intervene. 

Did anyone even think of wp all import ?

**Comment by dev-vip** [comment]
@coreymckrill 
@naman03malhotra  not a good review of this change...  It is causing duplicate out of stock emails on normal orders and out of stock to fire when importing via wp all import. 

So changes are made and a test that should be done to prevent this, claimed to have been done, has clearly not even being carried out, you guys are not even following standard procedure and hence it is breaking.
