### PR TITLE
Fix/29540

### LINKED ISSUE #29540: product assigned to no category
**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
I have a master store and a child store, I exported the products from the master store using the woocommerce core import/export feature. I imported them into my new store (imported all the categories and products). I then decided I wanted to change the default category on my child store which i did. I then removed some categories I did not want on my child store expecting my products within the categories i am removing to be moved to the to the default category. However I noticed that the products were not in there. Due to naivety i had just assumed maybe the products were removed when i deleted the categories, which i thought was strange as normally if a category is deleted then the products within that category are moved to the default category instead. Some time has passed and while i was working on a script today i noticed that the products are actually still on the site somewhere with no assigned category?

**Expected behavior**
I expected the products within the category i deleted to be moved to the default category.

**Actual behavior**
products are now on the site with no assigned category

**Screenshots**
https://imgur.com/a/AQUugvB

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report we won't be able to fully evaluate this issue.
<details>
```
`
### WordPress Environment ###

WordPress address (URL): https://tonsoffunparties.ie
Site address (URL): https://tonsoffunparties.ie
WC Version: 5.1.0
REST API Version: ✔ 5.1.0
WC Blocks Version: ✔ 4.4.3
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 2.0.2
Log Directory Writable: ✔
WP Version: 5.7
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.4.16
PHP Post Max Size: 16 MB
PHP Time Limit: 300
PHP Max Input Vars: 1000
cURL Version: 7.29.0
NSS/3.53.1

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.3.28-MariaDB
Max Upload Size: 16 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 5.1.0
WC Database Prefix: m7O0KqA_
Total Database Size: 232.57MB
Database Data Size: 153.59MB
Database Index Size: 78.98MB
m7O0KqA_woocommerce_sessions: Data: 0.03MB + Index: 0.02MB + Engine InnoDB
m7O0KqA_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
m7O0KqA_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
m7O0KqA_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
m7O0KqA_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
m7O0KqA_woocommerce_order_itemmeta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
m7O0KqA_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
m7O0KqA_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
m7O0KqA_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
m7O0KqA_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
m7O0KqA_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
m7O0KqA_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
m7O0KqA_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
m7O0KqA_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
m7O0KqA_actionscheduler_actions: Data: 1.02MB + Index: 0.81MB + Engine InnoDB
m7O0KqA_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
m7O0KqA_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
m7O0KqA_actionscheduler_logs: Data: 1.09MB + Index: 0.59MB + Engine InnoDB
m7O0KqA_aelia_dismissed_messages: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
m7O0KqA_aelia_exchange_rates_history: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
m7O0KqA_aioseo_notifications: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
m7O0KqA_aioseo_posts: Data: 2.52MB + Index: 0.16MB + Engine InnoDB
m7O0KqA_aws_cache: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
m7O0KqA_aws_index: Data: 27.38MB + Index: 13.59MB + Engine InnoDB
m7O0KqA_chaty_contact_form_leads: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
m7O0KqA_cli_cookie_scan: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
m7O0KqA_cli_cookie_scan_categories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
m7O0KqA_cli_cookie_scan_cookies: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
m7O0KqA_cli_cookie_scan_url: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
m7O0KqA_cli_scripts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
m7O0KqA_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
m7O0KqA_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
m7O0KqA_gdbc_attempts: Data: 0.34MB + Index: 0.09MB + Engine InnoDB
m7O0KqA_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
m7O0KqA_ms_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
m7O0KqA_options: Data: 8.02MB + Index: 1.28MB + Engine InnoDB
m7O0KqA_pmxi_files: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
m7O0KqA_pmxi_hash: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
m7O0KqA_pmxi_history: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
m7O0KqA_pmxi_images: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
m7O0KqA_pmxi_imports: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
m7O0KqA_pmxi_posts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
m7O0KqA_pmxi_templates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
m7O0KqA_postmeta: Data: 84.47MB + Index: 47.09MB + Engine InnoDB
m7O0KqA_posts: Data: 15.30MB + Index: 6.05MB + Engine InnoDB
m7O0KqA_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
m7O0KqA_stock_log: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
m7O0KqA_termmeta: Data: 1.48MB + Index: 1.95MB + Engine InnoDB
m7O0KqA_terms: Data: 0.48MB + Index: 0.52MB + Engine InnoDB
m7O0KqA_term_relationships: Data: 5.02MB + Index: 4.17MB + Engine InnoDB
m7O0KqA_term_taxonomy: Data: 1.52MB + Index: 0.63MB + Engine InnoDB
m7O0KqA_usermeta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
m7O0KqA_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
m7O0KqA_wcpdf_invoice_number: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
m7O0KqA_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
m7O0KqA_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
m7O0KqA_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
m7O0KqA_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
m7O0KqA_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
m7O0KqA_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
m7O0KqA_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
m7O0KqA_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
m7O0KqA_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
m7O0KqA_wc_product_meta_lookup: Data: 1.03MB + Index: 1.02MB + Engine InnoDB
m7O0KqA_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
m7O0KqA_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
m7O0KqA_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
m7O0KqA_wss_log: Data: 0.27MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

attachment: 13041
cmm4e_menu_theme: 1
cookielawinfo: 6
custom_css: 1
customize_changeset: 47
elementor_library: 9
iksm: 2
nav_menu_item: 63
page: 10
post: 2
product: 5751
revision: 344
seedprod: 2
shop_order: 7
shop_order_refund: 4
sp_wp_carousel: 1
wpmm_theme: 3

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (21) ###

WPBruiser: by Mihai Chelaru – 3.1.43
Advanced Woo Search: by ILLID – 2.24
All in One SEO: by All in One SEO Team – 4.0.17
Chaty: by Premio – 2.7.6
Code Snippets: by Code Snippets Pro – 2.14.1
GDPR Cookie Consent: by WebToffee – 2.0.1
Disable Real MIME Check: by Sergey Biryukov – 1.0
Elementor Pro: by Elementor.com – 3.2.0-dev1
Elementor: by Elementor.com – 3.2.0-dev4
Iks Menu: by IksStudio – 1.9.0
ID Back To Top: by Idenovasi – 1.1.1
UberMenu 3 - The Ultimate WordPress Mega Menu: by Chris Mavricos
SevenSpark – 3.7.3

UpdraftPlus - Backup/Restore: by UpdraftPlus.Com
DavidAnderson – 1.16.50

WooCommerce Weight Based Shipping: by weightbasedshipping.com – 5.3.10
Widget Options: by Widget Options Team – 3.7.7
Stock Sync for WooCommerce Pro: by Lauri Karisola / WooElements.com – 2.0.3
WooCommerce EU VAT Assistant: by Aelia – 2.0.14.210317
WooCommerce Stripe Gateway: by WooCommerce – 5.0.0
WooCommerce PDF Invoices & Packing Slips: by Ewout Fernhout – 2.8.2
WooCommerce Stock Manager: by StoreApps – 2.5.6
WooCommerce: by Automattic – 5.1.0

### Inactive Plugins (0) ###


### Dropin Plugins (1) ###

maintenance.php: maintenance.php

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: EUR (€)
Currency Position: left
Thousand Separator: .
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #6 - /shop/
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: #58575 - /elementor-58575/

### Theme ###

Name: Supermarket Ecommerce
Version: 0.3.4
Author URL: https://www.luzuk.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: supermarket-ecommerce/woocommerce/archive-product.php
supermarket-ecommerce/woocommerce/checkout/form-checkout.php
supermarket-ecommerce/woocommerce/global/wrapper-end.php
supermarket-ecommerce/woocommerce/global/wrapper-start.php
supermarket-ecommerce/woocommerce/single-product.php


### Action Scheduler ###

Complete: 3,427
Oldest: 2021-02-27 16:52:31 +0000
Newest: 2021-03-30 16:00:17 +0000

Pending: 3
Oldest: 2021-03-30 16:00:47 +0000
Newest: 2021-03-31 15:31:05 +0000


### Status report information ###

Generated at: 2021-03-30 16:01:02 +00:00
`
```
</details>

### PR DESCRIPTION
**Pull request by roykho**
### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes #29540

On the action of deleting a product category, we want to reassign any products that have no categories to a default category.

### How to test the changes in this Pull Request:

1. Create a product category.
2. Create several simple products and assign them the category from step 1.
3. Now go to the product category page and delete the category you've created in step 1.
4. Go back to the products page and ensure these products have the `Uncategorized` category assigned instead of nothing.
5. Do the same test with REST API deleting the product category via `wp-json/wc/v3/products/categories/{cat_id}` endpoint using `DELETE` method. Tip make sure to have a JSON payload of `"force": true` for this to work.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Fix - Products left without default category assignment when all categories are deleted.

### CODE REVIEW

File: includes/wc-term-functions.php [hunk 1]
```diff
@@ -689,3 +690,40 @@ function _wc_recount_terms_by_product( $product_id = '' ) {
...
 }
+
+/**
+ * Assigns default product category for products
+ * that have no categories.
+ *
+ * @since 5.4
+ * @return void
+ */
+function _wc_maybe_assign_default_product_cat() {
```
Comment (Konamiman) [inline includes/wc-term-functions.php:701]: Instead of creating a new "private" (as indicated by the initial underscore in the name) function, it would be cleaner and easier to maintain/refactor to create a new class in the `src/Internal` directory. The action scheduling part can be left as is.

Comment (roykho) [reply includes/wc-term-functions.php:701]: So I am just following consistency here as seen in https://github.com/woocommerce/woocommerce/blob/trunk/includes/wc-term-functions.php#L392 and https://github.com/woocommerce/woocommerce/blob/trunk/includes/wc-term-functions.php#L152

Comment (roykho) [reply includes/wc-term-functions.php]: Ok I have converted the PR into using the internal DI container.

File: includes/admin/class-wc-admin-taxonomies.php [hunk 2]
```diff
@@ -49,6 +51,7 @@ public function __construct() {
 
 		// Category/term ordering.
 		add_action( 'create_term', array( $this, 'create_term' ), 5, 3 );
+		add_action( 'delete_product_cat', array( $this, 'assign_default_product_cat' ) );
```
Comment (Konamiman) [inline includes/admin/class-wc-admin-taxonomies.php:54]: Adding a new public function for the sole purpose of invoking a method on a private class kind of defeats the whole purpose of making that class private... what about removing the function and adding a direct callback instead? Something like this:

```suggestion
		add_action(
			'delete_product_cat',
			function() {
				wc_get_container()->get( AssignDefaultCategory::class )->schedule_action();
			},
		);
```

File: src/Internal/AssignDefaultCategory.php [hunk 3]
```diff
@@ -0,0 +1,72 @@
...
+			array(),
+			'wc_update_product_default_cat'
+		);
+	}
+
+	/**
+	 * Assigns default product category for products
+	 * that have no categories.
+	 *
+	 * @since 5.4
```
Comment (Konamiman) [inline src/Internal/AssignDefaultCategory.php:42]: Maybe adding `@since` to internal classes wouldn't be needed since those aren't intended for external usage, although that should be something to be discussed more in depth.

Anyway, if we are adding `@since`s, shouldn't the `schedule_action` method have one too?

**Comment by roykho** [comment]
@Konamiman  - Updated based on comments.

**Review by Konamiman — APPROVED** [review]
