### PR TITLE
Avoid exception when serializing context

### LINKED ISSUE #32576: Exception when serializing Order in WC_Log_Handler_DB
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

On my site, we have WC_Log_Handler_DB active.

I'm finding that, when there's an error when changing the status of an order, the log shows the Exception "Serialization of 'Closure' is not allowed", instead of the actual exception that caused the Order error.

After debugging the problem, I've found that it's ultimately caused by WC_Order class when emitting an error to the log passing the Order in the $context object. Then, WC_Log_Handler_DB tries to serialize this Order object, causing this exception. This serialization doesn't happen with the standard behaviour of WC_Log_Handler_File class, active by default, that ignores extra objects passed in the $context array when generating error logs.

### Expected behavior

I would expect the actual Exception message showing in the logs, not an exception caused while trying to log it.

### Actual behavior

The log shows the Exception "Serialization of 'Closure' is not allowed", instead of the actual exception that caused the error when trying to change the status of the Order.

### Steps to reproduce

We have this problem consistently reproducing when payment gateways experience errors changing the status of an Order.

### WordPress Environment

We'd rather not share this information publicly

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by davefx**
Fixes #32576

### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes #32576 .

### How to test the changes in this Pull Request:

This is a bit technical. The change just fixes the problem described in #32576. Let's better have an error message in the context than having a wrong Exception in the message.

### Other information:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Fix to avoid closure serialization exception in class WC_Log_Handler_DB

### FOR PR REVIEWER ONLY:

* [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

File: plugins/woocommerce/includes/log-handlers/class-wc-log-handler-db.php [hunk 1]
```diff
@@ -78,7 +78,11 @@ protected static function add( $timestamp, $level, $message, $source, $context )
 		);
 
 		if ( ! empty( $context ) ) {
-			$insert['context'] = serialize( $context ); // @codingStandardsIgnoreLine.
+			try {
+				$insert['context'] = serialize( $context ); // @codingStandardsIgnoreLine.
+			} catch ( Exception $e ) {
+				$insert['context'] = 'There was an error while serializing the context: ' . $e->getMessage();
```
Comment (vedanshujain) [inline plugins/woocommerce/includes/log-handlers/class-wc-log-handler-db.php]: this error message needs to be serialized before storing otherwise it will trip when reading from this log

**Review by vedanshujain — CHANGES_REQUESTED** [review]
hey, added a minor comment, looks good otherwise. although it may be good idea to store the error separately as well.

File: plugins/woocommerce/includes/log-handlers/class-wc-log-handler-db.php (hunk 1 above)
Comment (davefx) [reply plugins/woocommerce/includes/log-handlers/class-wc-log-handler-db.php]: You are right. Solved.

**Review by vedanshujain — APPROVED** [review]

**Comment by vedanshujain** [comment]
Looks good, will merge after tests passes.
