### PR TITLE
Always sanitize coupon code to prevent inconsistent between admins and shop owners

### LINKED ISSUE #23655: Coupon code with ampersand is inconsistent between logged in user and guest
**Describe the bug**
When we create a coupon with a ampersand in the code (ex: `a&a`), it works for a logged in user, but not for a guest user. If we create a coupon with the html representation of a ampersand in the code (ex: `b&amp;b), it works for guest users but not for logged in users.

**To Reproduce**
1. Create a coupon with code `a&a`
2. Create a coupon with code `b&amp;b`
3. Add a product to the cart as a logged in user
4. Apply the coupon `a&a` in the cart, and see that the coupon is applied
5. Apply the coupon `b&b` in the cart, and we get a message that it doesn't exist
6. Add a product to the cart when not logged in (guest user)
7. Apply the coupon `a&a` in the cart, and we get a message that it doesn't exist
8. Apply the coupon `b&b` in the cart, and see that the coupon is applied

**Screenshots**
Logged in user: 
image

Guest user:
image

**Expected behavior**
In both scenario's I'd expect to receive consistent results. It seems when the coupon object loaded, the difference is that the ID is 0, which causes the following check to fail:
https://github.com/woocommerce/woocommerce/blob/3.6.2/includes/class-wc-discounts.php#L586

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>

```
WordPress 5.2
WooCommerce 3.6.2
Storefront 2.4.6
```
</details>

### PR DESCRIPTION
**Pull request by claudiosanches**
### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

By default WordPress will run `kses_init_filters()` if the current user can't use unfiltered HTML, applying the `wp_filter_kses()` function to the `title_save_pre`.
That's why admins can save a coupon code like `a&a` without getting converted into `a&amp;a`.

To fix the inconsistent I'm changing to always apply the same sanitation for all users on WooCommerce, also should be safer to always sanitize.
And it also includes a upgrade routine to fix all codes at once.

Closes #23655.

### How to test the changes in this Pull Request:

1. Create two coupons with the following codes using an admin:
- `a&a`
- `b&amp;b`
2. Now create more two coupons using a shop manager:
- `c&c`
- `d&amp;d`
3. Check that with the shop manager ampersand gets encoded.
4. With the shop manager edit the coupon with code `a&a` and note that the ampersand got encoded making impossible to restore.
5. Apply this patch, edit or create coupons with any user and see that ampersands always get encoded.
6. Added some products to the cart and try use your coupons created in the previous steps.
7. Also try apply coupons with both formats: `a&a` and `a&amp;a`.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Fix - Coupon code inconsistent between admins and shop owners.

### CODE REVIEW

**Comment by vedanshujain** [comment]
Adding high impact label because this will existing coupon codes.

**Comment by claudiosanches** [comment]
@vedanshujain not sure if it's "high impact", since there's a migration script, and will also accept the old format too, since will got converted before searching in the database.

**Review by vedanshujain — CHANGES_REQUESTED** [review]
Since the intention is to get to a state where code everywhere had run through `wp_filter_kses` I have a few questions/suggestions:
1. We have a method `wc_format_coupon_code`, perhaps it will be good to add `wp_filter_kses` there as well.
2. Should we batch the update function for shops that have large amount of coupons (incase running the request takes more than 30s).
3. Do we really need to run the update command for every coupon code, I think if we do it only where old_code !== new_code, it will be a good improvement.

wdyt?

**Comment by vedanshujain** [comment]
@claudiosanches agree with high impact assessment, removing the label.

**Comment by claudiosanches** [comment]
@vedanshujain 

> We have a method wc_format_coupon_code, perhaps it will be good to add wp_filter_kses there as well.

It already gets applied there by the `woocommerce_coupon_code` filter. See:

https://github.com/woocommerce/woocommerce/blob/8c2412ea7d7d452eb022f7225cd228b00cb144c1/includes/wc-core-functions.php#L38-L40

> Should we batch the update function for shops that have large amount of coupons (incase running the request takes more than 30s).

The query used doesn't sound too expensive, but if you prefer I can implement a batch update, not a problem, but while those aren't updated problem will generate some problems if trying to use a coupon containing HTML entities.

> Do we really need to run the update command for every coupon code, I think if we do it only where old_code !== new_code, it will be a good improvement.

It will solve problems later, like for querying coupons where we should be search for `a&amp;a` while in the database it's still `a&a`.

**Comment by claudiosanches** [comment]
> Should we batch the update function for shops that have large amount of coupons (incase running the request takes more than 30s).

I just implemented that, now will update 10 coupons for each run.

File: includes/wc-update-functions.php [hunk 1]
```diff
@@ -2175,3 +2175,69 @@ function wc_update_440_insert_attribute_terms_for_variable_products() {
...
+	WC_Install::update_db_version( '4.5.0' );
+}
+
+/**
+ * Get coupons to update in the DB.
+ */
+function wc_update_450_get_coupons() {
+	global $wpdb;
+
+	$coupons = $wpdb->get_results( "SELECT ID, post_title FROM {$wpdb->posts} WHERE post_type = 'shop_coupon';", ARRAY_A );
```
Comment (vedanshujain) [inline includes/wc-update-functions.php:2192]: This approach has a race condition incase we take too much time in processing these coupons, someone can update the title to something after we have fetched and stored them, and we will end up resetting it from our stored value in options.

File: includes/wc-update-functions.php [hunk 2]
```diff
@@ -2175,3 +2175,69 @@ function wc_update_440_insert_attribute_terms_for_variable_products() {
...
+
+/**
+ * Sanitize all coupons code.
+ *
+ * @return bool True to run again, false if completed.
+ */
+function wc_update_450_sanitize_coupons_code() {
+	global $wpdb;
+
+	$coupons = array_filter( (array) get_option( 'woocommerce_update_350_coupons', array() ) );
```
Comment (vedanshujain) [inline includes/wc-update-functions.php:2205]: What do you think about changing the algorithm a little bit:
1. Instead of the post title and ID of all coupons, store only one ID starting from zero.
2. Then in each iteration, fetch using `where id > $stored_id limit 10`, and process them. Update the ID to last ID.
3. Stop when there are no more Ids.

This way we won't have to do any large inserts and updates, and we will prevent the race condition that I mentioned in above comment.

**Review by vedanshujain — COMMENTED** [review]
Great work! I have a couple more suggestions, let me know what you think.

**Comment by claudiosanches** [comment]
@vedanshujain I just made the changes, if you like to test again, in additional to change the `$version` to 4.5.0 you should also set the follow:

```bash
wp option update woocommerce_db_version "4.4.0"
wp option update woocommerce_version "4.4.0"
```

It will force to trigger the upgrade again.

File: includes/wc-update-functions.php [hunk 3]
```diff
@@ -2175,3 +2175,70 @@ function wc_update_440_insert_attribute_terms_for_variable_products() {
...
+/**
+ * Sanitize all coupons code.
+ *
+ * @return bool True to run again, false if completed.
+ */
+function wc_update_450_sanitize_coupons_code() {
+	global $wpdb;
+
+	$coupon_id      = 0;
+	$last_coupon_id = get_option( 'woocommerce_update_350_last_coupon_id', '0' );
```
Comment (vedanshujain) [inline includes/wc-update-functions.php:2195]: i think this option name was missed during rename, should be `woocommerce_update_450_last_coupon_id`

**Review by vedanshujain — APPROVED** [review]
LGTM! I have left some comments but they are suggestions rather blockers, so approving the PR anyway.

File: includes/wc-update-functions.php [hunk 4]
```diff
@@ -2175,3 +2175,70 @@ function wc_update_440_insert_attribute_terms_for_variable_products() {
...
+	if ( empty( $coupons ) ) {
+		delete_option( 'woocommerce_update_350_last_coupon_id' );
+		return false;
+	}
+
+	foreach ( $coupons as $key => $data ) {
+		$coupon_id = intval( $data['ID'] );
+		$code      = trim( wp_filter_kses( $data['post_title'] ) );
+
+		if ( ! empty( $code ) ) {
```
Comment (vedanshujain) [inline includes/wc-update-functions.php:2214]: we can also add a condition `&& $data['post_title'] !== $code` to prevent some more queries and cache operations. (for those coupon codes that didn't have any special character anyway)

File: includes/wc-update-functions.php (hunk 3 above)
Comment (claudiosanches) [reply includes/wc-update-functions.php]: Oops, sorry I missed that!

File: includes/wc-update-functions.php (hunk 4 above)
Comment (claudiosanches) [reply includes/wc-update-functions.php]: Good idea

**Comment by claudiosanches** [comment]
@vedanshujain thank you very much for reviewing and for all the tips :hugs:

**Review by Konamiman — APPROVED** [review]
