### PR TITLE
Accept both wrapped and unwrapped JSON schema for additional fields

### LINKED ISSUE #58488: Custom block-based checkout field not being validated if it has conditional hidden rules
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When registering a custom block-based checkout field with `woocommerce_register_additional_checkout_field` we have the option to set hidden to `true`, `false`, or an array of json schema validation rules.

If we use the last, that field is never validated with the function passed to the `validate_callback` argument, even if it's shown. I expect for the validation not to happen if it's hidden at the moment, but if the rules make it visible, it should be run through the `validate_callback` function, which it doesn't.

This happens because `$this->is_hidden_field( $key, $document_object )` inside `CheckoutFields::get_contextual_fields_for_location` returns `false` when the field is always visible (no hidden conditional rules) and so the `validate_callback` is used, and returns `true` if the field has hidden conditional rules even if it's visible by those rules. Inside `is_hidden_field` `Validation::validate_document_object( $document_object, $field['hidden'] )` is returning true with valid hidden conditional rules which makes this function return true (is hidden).

### Expected behavior

Even if the field has conditional hidden rules, it should be validated if it's shown by its rules.

If the field  has conditional hidden rules, it should be NOT be validated if it's hidden by its rules.

### Actual behavior

Not coherent. Even if the field is shown, the `validate_callback` is not called.

### Steps to reproduce

1. Register a field and make it show conditional, also create a validate_callback function for it and return a WP_Error
2. Run the checkout and make sure that field is shown by the rules: it won't be validated and the checkout will go through without errors
3. Now remove the conditional hidden rules: it will be validated and the checkout will throw an error

### WordPress Environment

<details><summary>System Status Report</summary>

```
### WordPress Environment ###

WordPress address (URL): [Redacted]
Site address (URL): [Redacted]
WC Version: 9.9.0
Legacy REST API Package Version: O plugin Legacy REST API não está instalado neste site.
Action Scheduler Version: ✔ 3.9.2
Log Directory Writable: ✔
WP Version: ❌ 6.9-alpha-60258 - Há uma nova versão do WordPress disponível (6.9-alpha-60272)
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: –
Language: pt_BR
External object cache: –

### Server Environment ###

Server Info: nginx/1.26.1
Server Architecture: Darwin 24.5.0 arm64
PHP Version: 8.3.0
PHP Post Max Size: 1.000 MB
PHP Time Limit: 1200
PHP Max Input Vars: 4000
cURL Version: 8.7.1
(SecureTransport) LibreSSL/3.3.6

SUHOSIN Installed: –
MySQL Version: 8.0.35
Max Upload Size: 300 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

[REDACTED]

### Post Type Counts ###

acf-field: 38
acf-field-group: 8
amn_smtp: 1
atividade: 4
attachment: 6283
aw_workflow: 6
blocks: 8
chefpanda_market: 3
doctor: 4
easy-pricing-table: 1
featured_item: 8
frm_form_actions: 1
frm_styles: 1
homey_reservation: 2
ibwp_mp_popup: 1
listing: 1
mb_payment_request: 1
medical-agreements: 3
medical-booking: 10
medical-consultation: 6
medical-exam: 2
medical-specialty: 4
memberpressproduct: 2
nav_menu_item: 25
oksofasstore: 3
page: 79
person: 5
post: 23
private_post: 4
product: 7970
product_variation: 138
revision: 363
shop_coupon: 25
shop_order: 971
shop_order_placehold: 6
shop_order_refund: 93
shop_subscription: 10
store: 1
szbdzones: 1
was: 1
wc_appointment: 1
wc_conditional_fee: 1
wc_order_status: 9
wc-donation: 2
wc-donation-report: 6
wcdp_payment: 4
wd_client_contract: 1
wd_support_ticket: 1
webdados_client_serv: 15
webdados_service: 8
wfacp_checkout: 1
wffn_ty: 1
wishlist: 1
wp_block: 1
wp_global_styles: 6
wp_navigation: 1
wp_template: 1
wp_template_part: 1
wpbdp_listing: 1
wpcf7_contact_form: 6
wpforms: 1
wps_subscriptions: 1
wpsc_ticket_thread: 3

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (9) ###

WooCommerce Beta Tester: por WooCommerce – 3.0.0
WooCommerce: por Automattic – 9.9.0
WordPress Beta Tester: por WordPress Upgrade/Install Team – 3.6.3

### Inactive Plugins (347) ###

Not relevant

### Dropin Plugins () ###

db.php: db.php

### Settings ###

Legacy API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: 
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: appointment (appointment)
external (external)
grouped (grouped)
mwb_booking (mwb_booking)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: –
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: ✔
Enabled Features: marketplace
order_attribution
site_visibility_badge
hpos_fts_indexes
email_improvements
custom_order_tables


### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 dias
Level threshold: –
Log directory size: 81 KB

### WC Pages ###

Base da loja: #14857 - /loja-pt/
Carrinho: #17882 - /cart-blocks/ -  Contém o bloco woocommerce/cart
Finalização de compra: #17884 - /checkout-blocks-2/ -  Contém o bloco woocommerce/checkout
Minha conta: #16787 - /my-account-2/ -  Contém o shortcode [woocommerce_my_account]
Termos e condições: #16621 - /16621-2/

### Theme ###

Name: Storefront Child
Version: 20230130.01
Author URL: 
Child Theme: ✔
Parent Theme Name: Storefront
Parent Theme Version: 4.6.1
Parent Theme Author URL: https://woocommerce.com/
Theme type: Tema clássico
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
onboarding
onboarding-tasks
pattern-toolkit-full-composability
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
printful
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page
launch-your-store
add-to-cart-with-options-stepper-layout
disable-core-profiler-fallback

Disabled Features: product-data-views
experimental-blocks
coming-soon-newsletter-template
minified-js
point-of-sale
product-pre-publish-modal
settings
async-product-editor-category-field
product-editor-template-system
use-wp-horizon
blockified-add-to-cart
beta-tester-slotfill-examples

Daily Cron: ✔ Next scheduled: 2025-03-26 15:19:07 +00:00
Options: ✔
Notes: 202
Onboarding: completed

### Action Scheduler ###

Concluído: 3.558
Oldest: 2025-04-11 00:50:00 +0100
Newest: 2025-06-02 21:36:06 +0100

Malsucedido: 2.350
Oldest: 2023-02-01 17:31:32 +0000
Newest: 2025-04-22 15:46:01 +0100

Pendente: 2
Oldest: 2025-06-02 22:36:06 +0100
Newest: 2025-06-03 09:45:41 +0100


### Status report information ###

Generated at: 2025-06-02 21:52:13 +01:00
```
</details>

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by senadir**
This PR fixes a minor issue in which we didn't accept wrapped JSON schema for `hidden` prop in additional fields, only for `required` one, meaning code examples from the docs wouldn't have worked.
Closes https://github.com/woocommerce/woocommerce/issues/58488

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Add the following snippet somewhere:
```php

add_action(
	'woocommerce_init',
	function () {
		woocommerce_register_additional_checkout_field(
			array(
				'id'       => 'plugin-namespace/wrapped-field',
				'label'    => 'Wrapped field',
				'location' => 'address',
				'type'     => 'checkbox',
				'hidden'   => array(
					'type'       => 'object',
					'properties' => array(
						'customer' => array(
							'properties' => array(
								'address' => array(
									'properties' => array(
										'country' => array(
											'const' => 'US',
										),
									),
								),
							),
						),
					),
				),
				'required' => array(
					'type'       => 'object',
					'properties' => array(
						'customer' => array(
							'properties' => array(
								'address' => array(
									'properties' => array(
										'country' => array(
											'not' => array(
												'const' => 'US',
											),
										),
									),
								),
							),
						),
					),
				),
			),
		);

		woocommerce_register_additional_checkout_field(
			array(
				'id'       => 'plugin-namespace/unwrapped-field',
				'label'    => 'Unwrapped field',
				'location' => 'address',
				'type'     => 'checkbox',
				'hidden'   => array(
					'customer' => array(
						'properties' => array(
							'address' => array(
								'properties' => array(
									'country' => array(
										'const' => 'US',
									),
								),
							),
						),
					),

				),
				'required' => array(
					'customer' => array(
						'properties' => array(
							'address' => array(
								'properties' => array(
									'country' => array(
										'not' => array(
											'const' => 'US',
										),
									),
								),
							),
						),
					),

				),
			),
		);
	}
);

```
2. On Checkout, notice that you have 2 new checkboxes, both are required,
3. If you switch country to US, both fields should be hidden.

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

Accept both wrapped and unwrapped JSON for Checkout additional fields.

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

## Summary by CodeRabbit

- **Bug Fixes**
	- Improved handling of additional checkout fields in WooCommerce to support both wrapped and unwrapped JSON formats, ensuring smoother checkout experiences and compatibility with various field configurations.
	- Corrected validation schema formats for checkout fields to enhance data consistency and prevent errors during checkout.

### CODE REVIEW

File: plugins/woocommerce/client/blocks/assets/js/base/components/cart-checkout/form/use-form-fields.ts [hunk 1]
```diff
@@ -72,10 +72,23 @@ export const useFormFields = < T extends keyof FormFields >(
...
+							key === 'customer'
+					)
+				) {
+					schema = {
+						type: 'object',
+						properties: defaultConfig.hidden,
+					};
+				} else {
+					schema = defaultConfig.hidden;
+				}
```
Comment (straku) [inline plugins/woocommerce/client/blocks/assets/js/base/components/cart-checkout/form/use-form-fields.ts:90]: Minor: since this logic is repeated 2 times, you can consider extracting it to a function, could offer more clarity into what we're doing here.

File: plugins/woocommerce/client/blocks/tests/e2e/plugins/additional-checkout-fields.php [hunk 2]
```diff
@@ -103,12 +103,15 @@ public function register_custom_checkout_fields(): void {
...
-										'maximum' => 4000,
+					'type'       => 'object',
+					'properties' => array(
+						'cart' => array(
+							'properties' => array(
+								'totals' => array(
+									'properties' => array(
+										'totalPrice' => array(
+											'maximum' => 4000,
+										),
```
Comment (straku) [inline plugins/woocommerce/client/blocks/tests/e2e/plugins/additional-checkout-fields.php:127]: I am wondering whether it would be beneficial for tests to cover both wrapped and unwrapped objects?

**Review by straku — APPROVED** [review]
Tests well, on your branch the logic is applied correctly to both fields, whereas on `trunk` only one field is hidden for US. Left some minor (and non-blocking) comments.

File: plugins/woocommerce/client/blocks/assets/js/base/components/cart-checkout/form/use-form-fields.ts (hunk 1 above)
Comment (tjcafferkey) [reply plugins/woocommerce/client/blocks/assets/js/base/components/cart-checkout/form/use-form-fields.ts:90]: I think we could abstract the `Object.keys` condition to make the code more digestible but I'm in favour of being explicit about the rest of the code here and leaving it. That said, not a super strong opinion on this.

File: plugins/woocommerce/client/blocks/tests/e2e/plugins/additional-checkout-fields.php (hunk 2 above)
Comment (tjcafferkey) [reply plugins/woocommerce/client/blocks/tests/e2e/plugins/additional-checkout-fields.php:127]: I'm in favour of this since its in an area of extensibility so we'd want that safety net for backcompat. Wonder if this test case would be better suited for a unit/integration test though.

Comment (senadir) [reply plugins/woocommerce/client/blocks/tests/e2e/plugins/additional-checkout-fields.php:127]: I agree, I will expand the tests.

File: plugins/woocommerce/client/blocks/assets/js/base/components/cart-checkout/form/use-form-fields.ts (hunk 1 above)
Comment (senadir) [reply plugins/woocommerce/client/blocks/assets/js/base/components/cart-checkout/form/use-form-fields.ts:90]: I didn't feel like it's worth abstracting this yet, but maybe you're right.

**Comment by webdados** [comment]
following :-)

**Comment by webdados** [comment]
Looks good. I tested the PR with the rules below and it works just fine.

The field using these rules should only be visible if:
- billing first name contains "marco" AND billing last name contains "almeida"
OR
- billing country is "PT" (Portugal)
The "not" at the first level is because we want to SHOW the field if the rules match, not HIDE it.


```
{
    "not": {
        "anyOf": [
            {
                "allOf": [
                    {
                        "type": "object",
                        "properties": {
                            "customer": {
                                "type": "object",
                                "properties": {
                                    "billing_address": {
                                        "type": "object",
                                        "properties": {
                                            "first_name": {
                                                "type": "string",
                                                "pattern": "marco"
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    },
                    {
                        "type": "object",
                        "properties": {
                            "customer": {
                                "type": "object",
                                "properties": {
                                    "billing_address": {
                                        "type": "object",
                                        "properties": {
                                            "last_name": {
                                                "type": "string",
                                                "pattern": "almeida"
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                ]
            },
            {
                "allOf": [
                    {
                        "type": "object",
                        "properties": {
                            "customer": {
                                "type": "object",
                                "properties": {
                                    "billing_address": {
                                        "type": "object",
                                        "properties": {
                                            "country": {
                                                "type": "string",
                                                "const": "PT"
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                ]
            }
        ]
    }
}
```

**Comment by senadir** [comment]
Rewrote the rules you provided for PHP, thank you Marco:

```php
add_action(
  'woocommerce_init',
  function () {
    woocommerce_register_additional_checkout_field(
      array(
        'id'       => 'namespace/test-field',
        'label'    => 'VAT Number',
        'location' => 'address',
        'type'     => 'text',
        'required' => true,
        'hidden'   => array(
          'not' => array(
            'anyOf' => array(
              array(
                'allOf' => array(
                  array(
                    'type'       => 'object',
                    'properties' => array(
                      'customer' => array(
                        'type' => 'object',
                        'properties' => array(
                          'billing_address' => array(
                            'type' => 'object',
                            'properties' => array(
                              'first_name' => array(
                                'type' => 'string',
                                'pattern' => 'marco',
                              ),
                            ),
                          ),
                        ),
                      ),
                    ),
                  ),
                  array(
                    'type'       => 'object',
                    'properties' => array(
                      'customer' => array(
                        'type' => 'object',
                        'properties' => array(
                          'billing_address' => array(
                            'type' => 'object',
                            'properties' => array(
                              'last_name' => array(
                                'type' => 'string',
                                'pattern' => 'almeida',
                              ),
                            ),
                          ),
                        ),
                      ),
                    ),
                  ),
                ),
              ),
              array(
                'allOf' => array(
                  array(
                    'type'       => 'object',
                    'properties' => array(
                      'customer' => array(
                        'type' => 'object',
                        'properties' => array(
                          'billing_address' => array(
                            'type' => 'object',
                            'properties' => array(
                              'country' => array(
                                'type' => 'string',
                                'const' => 'PT',
                              ),
                            ),
                          ),
                        ),
                      ),
                    ),
                  ),
                ),
              ),
            ),
          ),
        ),
      ),
    );
  }
);

```

**Comment by webdados** [comment]
@senadir as an example it makes way more sense, of course. I haven't shared it that way because I'm dynamically creating the rules and I don't actually had the PHP code written as you just shared.

This is so cool and will open so many possibilities for advanced custom field management.

**Comment by webdados** [comment]
Can we assume this is all available for "required" as well?

**Comment by senadir** [comment]
> Can we assume this is all available for "required" as well?

Yes, let me know if it's not working

**Comment by webdados** [comment]
🙌
