### PR TITLE
Fix: wc_get_price_excluding_tax when an order with no customer is passed

### LINKED ISSUE #31013: [GlobalStep - 5.9.0 beta] Correct prices are not displayed for the taxes with and without Fixes
# Bug Description:
Correct prices are not displayed for the taxes with and without Fixes.

# Environment:
Woocommerce Version : WooCommerce 5.9.0
WordPress version: v5.8.1

# PC:
Windows 10
Firefox(Version 93.0)
Chrome (Version 94.0.4606.81)
Safari: v14.1.2

# Test Instruction link:
https://github.com/woocommerce/woocommerce/wiki/Release-Testing-Instructions-WooCommerce-5.9#use-proper-location-for-taxes-when-adding-products-via-admin-30692

# Steps To Reproduce:
1. Create any test site using JN site.
1. Install WooCommerce plugins.
1. Use the WooCommerce Beta Tester plugin in order to get WooCommerce 5.9 beta.
1. Install and activate Code Snippets plugin.
1. Add a new snippet with the following code: add_filter( 'woocommerce_adjust_non_base_location_prices', '__return_false' );
1. Go to WooCommerce - Settings - Tax - Tax options.
1. Make sure that you have the "Prices entered with tax" option set as "Yes, I will enter prices inclusive of tax".
1. Let A be the country where your currently logged in user is based. Create an user based on a different country B.
1. Go to WooCommerce - Settings - Tax - Standard rates and set 20% for country A and 10% for country B.
1. Create a simple product, taxable with standard rates, with a price of 110.
1. Create an order from admin area, set U as the customer.
1. Add the product you just created to the order.
1. Observe that without the fix,the price 91,67 (110 minus 20% of taxes) and with the fix, the price 100 (10% of taxes subtracted this time).is not displayed.

# Actual Result:
Correct prices are not displayed for the taxes with and without Fixes.

# Expected Result:
Without the fix, the price that will appear in the line item is 91,67 (110 minus 20% of taxes). With the fix, the price will be 100 (10% of taxes subtracted this time).

*Isolating the problem (mark completed items with an [x]):*
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

ScreenShot:

<details>
`
### WordPress Environment ###

WC Version: 5.9.0
REST API Version: ✔ 5.9.0
WC Blocks Version: ✔ 6.1.0
Action Scheduler Version: ✔ 3.3.0
WC Admin Version: ✔ 2.8.0-rc.2
Log Directory Writable: ✔
WP Version: 5.8.1
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 8.0.11
PHP Post Max Size: 2 GB
PHP Time Limit: 1200
PHP Max Input Vars: 6144
cURL Version: 7.78.0
OpenSSL/1.1.0l

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.3.31-MariaDB-log
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 5.9.0
WC Database Prefix: wp_
Total Database Size: 7.25MB
Database Data Size: 4.80MB
Database Index Size: 2.45MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.08MB + Index: 0.13MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_custom_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_dynamic_segment_filters: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_feature_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_forms: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_mapping_to_external_entities: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletters: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_newsletter_links: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_newsletter_option: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_option_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_posts: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_segment: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_templates: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_scheduled_tasks: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_scheduled_task_subscribers: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_segments: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_sending_queues: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_settings: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_statistics_bounces: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_statistics_clicks: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_statistics_forms: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_statistics_newsletters: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_statistics_opens: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_mailpoet_statistics_unsubscribes: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_statistics_woocommerce_purchases: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_mailpoet_stats_notifications: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_subscribers: Data: 0.02MB + Index: 0.13MB + Engine InnoDB
wp_mailpoet_subscriber_custom_field: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_subscriber_ips: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_subscriber_segment: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_user_agents: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_user_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 0.34MB + Index: 0.05MB + Engine InnoDB
wp_postmeta: Data: 0.17MB + Index: 0.13MB + Engine InnoDB
wp_posts: Data: 0.11MB + Index: 0.06MB + Engine InnoDB
wp_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 27
mailpoet_page: 1
page: 18
post: 3
product: 30
product_variation: 10
revision: 16
shop_coupon: 1
shop_order: 28
shop_order_refund: 3
wp_global_styles: 1
wp_template: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (9) ###

Query Monitor: by John Blackbourn – 3.7.1
Akismet Anti-Spam: by Automattic – 4.2.1
Code Snippets: by Code Snippets Pro – 2.14.2
Jetpack: by Automattic – 10.3-2110.1
MailPoet 3 (New): by MailPoet – 3.71.3
WooCommerce Beta Tester: by WooCommerce – 2.0.4
WooCommerce Payments: by Automattic – 3.1.0
WooCommerce Shipping & Tax: by WooCommerce – 1.25.19
WooCommerce: by Automattic – 5.9.0-beta.1

### Inactive Plugins (9) ###

AMP: by AMP Project Contributors – 2.1.4
CoBlocks: by GoDaddy – 2.17.0
Crowdsignal Forms: by Automattic – 1.5.9
Crowdsignal Polls & Ratings: by Automattic
Inc. – 3.0.1

Gutenberg: by Gutenberg Team – 11.7.0
Layout Grid: by Automattic – 1.7
Page Optimize: by Automattic – 0.5.1
WooCommerce Blocks: by Automattic – 6.1.0
WordPress.com Editing Toolkit: by Automattic – 3.17039

### Dropin Plugins (3) ###

advanced-cache.php: advanced-cache.php
db.php: Query Monitor Database Class
object-cache.php: Memcached

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #6 - /shop/
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 3.9.1
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 178
Oldest: 2021-10-20 13:56:44 +0000
Newest: 2021-10-22 08:15:05 +0000

### Status report information ###

Generated at: 2021-10-22 08:24:42 +00:00
`

</details>

### PR DESCRIPTION
**Pull request by Konamiman**
### All Submissions:

* [ ] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
* [ ] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

https://github.com/woocommerce/woocommerce/pull/30692 introduced a change in the `wc_get_price_excluding_tax` function: if the `woocommerce_adjust_non_base_location_prices` is set to return `false`, the function is supposed to take the location of the customer from the order for the taxes calculation, but wasn't doing so when the order was being created directly from the admin area because no customer was being passed to `WC_Tax::get_rates`; thus, the location from the currently logged in user was being used instead. With the fix from that PR, the order was being passed to `woocommerce_adjust_non_base_location_prices` and its customer location was used for the taxes calculation.

The problem is that a newly created order with no customer whatsowever has actually a "null customer" with a zero customer id. The code was taking that to calculate taxes, which resulted in no taxes being deducted; adding a new line item would result in the full product price being added, with taxes; and pressing "Recalculate" would add the taxes again.

This PR fixes that: if an order is passed to `woocommerce_adjust_non_base_location_prices`, a check is done for the cusomer id, and if it's 0 then the shop base location is used for the tax calculation as a fallback.

Closes #31013.

### How to test the changes in this Pull Request:

**Note:** These instructions are an extended version of the ones for https://github.com/woocommerce/woocommerce/pull/30692.

1. Add the following snippet to your store: `add_filter( 'woocommerce_adjust_non_base_location_prices', '__return_false' );`
2. Make sure that you have the "Prices entered with tax" option set as "Yes, I will enter prices inclusive of tax" (_WooCommerce - Settings - Tax - Tax options_).
3. Let A be the country where your currently logged in user is based, and B the country where the shop is based. Create an user U based on a different country C.
4. Go to _WooCommerce - Settings - Tax - Standard rates_ and set 30% for country A, 20% for country B and 10% for country C.
5. Create a simple product, taxable with standard rates, with a price of 110.
6. Create an order from admin area, don't set any customer for it and save it ("Create" button in "Order actions").
7. Add the product you just created to the order. You should see that the price that will appear in the line item is 91,67 (110 minus 20% of taxes), and if you click "Recalculate", the tax for country B is added and the final order price is 110.
8. Remove the line item from the order
9. Set U as the order customer and save the order ("Update" button in "Order actions").
10. Add the same product to the order again. This time the price that will appear in the line item is 100 (110 minus 10% of taxes), and if you click "Recalculate", the tax for country C is added and the final order price is again 110.

### Other information:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully run tests with your changes locally?

### Changelog entry

N/A (it's a fix for https://github.com/woocommerce/woocommerce/pull/30692, which was included in 5.9 beta)

### FOR PR REVIEWER ONLY:

* [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

File: tests/php/includes/wc-product-functions-test.php [hunk 1]
```diff
@@ -75,23 +87,41 @@ public function get_tax_class( $context = 'view' ) {
...
 			$this->assertFalse( $customer_id_passed_to_wc_customer_constructor );
-			$this->assertNull( $customer_passed_to_get_rates );
+			$this->assertFalse( $customer_passed_to_get_rates );
+			$this->assertTrue( $get_base_rates_invoked );
 		}
 
-		// phpcs:enable Squiz.Commenting.FunctionComment.Missing
+		// phpcs:enable Squiz.Commenting
+
+		if ( $set_filter ) {
```
Comment (peterfabian) [inline tests/php/includes/wc-product-functions-test.php:123]: This can get confusing quite quickly; If we set the `$set_filter` to `true`, then the filter is set to `false` :)

**Review by peterfabian — APPROVED** [review]
Side note for future myself:
- `woocommerce_adjust_non_base_location_prices` filter set to false means that all customers irrespective of their billing/shipping country should pay the same price incl tax.

Overall, I think it works fine, although the UX is not super nice since the merchant needs to save/update orders in between.

Great job with those tests, I think it should cover all the eventualities.

**Comment by Konamiman** [comment]
Merged into `release/5.9` for inclusion in WooCommerce 5.9 RC. Needs to be cherry-picked into `trunk`.

**Comment by Konamiman** [comment]
Cherry-picked into `trunk` for inclusion in 6.0.
