### PR TITLE
Manually init template registry and controller for non-block themes

### LINKED ISSUE #50270: Critical error on T51 site after turning Coming Soon mode
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Testing the T51 test site and turning Coming Soon mode, the site breaks. Turning Coming Soon mode OFF, restores the site.

### Expected behavior

Coming Soon working as expected on T51 site

### Actual behavior

Critical [error](https://d.pr/i/VOtDQI)

### Steps to reproduce

1. Go to T51 site
2. Go to WC Settings > Site visibility
3. Turn the Coming Soon mode ON
4. Go to the front-end site and observe issue

### WordPress Environment

<details><summary>System Status Report</summary>

```
### WordPress Environment ###

WordPress address (URL): [Redacted]
Site address (URL): [Redacted]
WC Version: 9.2.0-beta.1
Legacy REST API Package Version: ✔ 1.0.4
Action Scheduler Version: ✔ 3.8.1
Log Directory Writable: ✔
WP Version: 6.6.1
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 8.2.21
PHP Post Max Size: 2 GB
PHP Time Limit: 1200
PHP Max Input Vars: 6144
cURL Version: 8.7.1
OpenSSL/3.0.13

SUHOSIN Installed: –
MySQL Version: 10.6.18-MariaDB-log
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

[REDACTED]

### Post Type Counts ###

acf-field: 3
acf-field-group: 1
asp-products: 9
attachment: 1132
aw_workflow: 11
boxzilla-box: 2
coblocks_pattern: 1
course: 5
custom_css: 2
event_ticket: 36
feedback: 1667
follow_up_email: 1
jetpack_migration: 2
jetpack-testimonial: 3
jp_img_sitemap: 3
jp_sitemap: 3
jp_sitemap_master: 3
jp_vid_sitemap: 3
lesson: 74
letter: 35
mts_notification_bar: 1
nav_menu_item: 49
page: 62
popup: 2
popup_theme: 8
post: 52
product: 29
product_variation: 77
pys_event: 1
quiz: 11
rbbc_letters: 7
rbbc_press: 27
rbbc_testimonials: 24
redirect_rule: 9
revision: 2653
sensei_email: 19
shop_coupon: 18
shop_order: 2
shop_order_refund: 28
stripe_order: 109
wp_block: 5
wp_global_styles: 2
wp_navigation: 1
wp_template: 1
wpcode: 4
wppopups: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (49) ###

Actionable Google Analytics: by Tatvic – CC-V3-3.6
Add Widget After Content: by Arelthia Phillips – 2.4.6
Advanced Custom Fields: by WP Engine – 6.3.5
Akismet Anti-spam: Spam Protection: by Automattic - Anti-spam Team – 5.3.3
AutomateWoo: by WooCommerce – 6.0.30
Canonical SEO WordPress Plugin: by Harsh Agrawal – 3.0
Carousel Slider Block: by  – 1.0.14
CoBlocks: by GoDaddy – 3.1.13
Duplicate Page: by mndpsingh287 – 4.5.4
301 Redirects: by WebFactory Ltd – 2.76
Image SEO: by WPChill – 3.1.2
WPCode Lite: by WPCode – 2.2.0
Smash Balloon Instagram Feed: by Smash Balloon – 6.4.3
IP Location Block: by IP Location Block – 1.3.2
Jetpack Protect: by Automattic - Jetpack Security team – 2.2.0
Jetpack: by Automattic – 13.7-a.7
Meta pixel for WordPress: by Facebook – 3.0.16
Page Links To: by Mark Jaquith – 3.3.7
Plugin Autoupdate Filter: by WordPress.com Special Projects – 1.6.2
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 3.1.6
Remove hooked_block_types filter: by  –
Safe Redirect Manager: by 10up – 2.1.2
Safe SVG: by 10up – 2.2.5
Sensei LMS: by Automattic – 4.24.1
Sensei LMS Media Attachments: by Automattic – 2.0.3
Typeform: by Typeform – 2.9.1
Unbounce Landing Pages: by Unbounce – 1.1.2
Advanced Order Export For WooCommerce: by AlgolPlus – 3.5.3
WooCommerce.com Update Manager: by Automattic – 1.0.3
Variation Swatches for WooCommerce: by Emran Ahmed – 2.1.1
WooCommerce Box Office: by WooCommerce – 1.2.6
WooCommerce Checkout Manager: by QuadLayers – 7.5.6
WooCommerce Legacy REST API: by WooCommerce – 1.0.4
WooCommerce One Page Checkout: by Automattic – 2.8.5
Woo Product Bundles: by Woo – 7.2.1
WooCommerce Shipping & Tax: by WooCommerce – 2.7.0
WooCommerce Subscriptions - Custom Price String: by WooCommerce – 1.0.6
WooCommerce Subscriptions: by WooCommerce – 6.5.0
WooCommerce: by Automattic – 9.2.0-beta.1
Sensei Pro (WC Paid Courses): by Automattic – 4.24.1.1.24.0
Wordfence Security: by Wordfence – 7.11.7
WordPress Importer: by wordpressdotorg – 0.8.2
Yoast SEO Premium: by Team Yoast – 22.6
Yoast SEO: by Team Yoast – 23.1
WP Mail Logging: by WP Mail Logging Team – 1.12.0
WP Notification Bars: by MyThemeShop – 1.0.12
WP Popups Lite: by timersys – 2.2.0.2
Schema Pro: by Brainstorm Force – 2.7.19
WP Test Email: by Boopathi Rajan – 1.1.7

### Inactive Plugins (20) ###

Accept Stripe Payments: by Tips and Tricks HQ
wptipsntricks – 2.0.86

ActiveCampaign for WooCommerce: by ActiveCampaign – 2.7.6
Afterpay Gateway for WooCommerce: by Afterpay – 3.8.6
Boxzilla: by ibericode – 3.3.1
ConvertKit: by ConvertKit – 2.5.2
Creative Mail by Newfold Digital: by Newfold Digital – 1.6.9
Easy Forms for Mailchimp: by Code Parrots – 6.9.0
ES Woocommerce ActiveCampaign: by EqualServing.com – 2.1.4
GA Google Analytics: by Jeff Starr – 20240701
GTM4WP - A Google Tag Manager (GTM) plugin for WordPress: by Thomas Geiger – 1.20.2
Mailchimp for WooCommerce: by Mailchimp – 4.2.1
MC4WP: Mailchimp for WordPress: by ibericode – 4.9.14
PixelYourSite: by PixelYourSite – 9.7.1
Popup Maker: by Popup Maker – 1.19.0
Two Factor: by Plugin Contributors – 0.9.1
User Submitted Posts: by Jeff Starr – 20240703
WooCommerce Dummy Payments Gateway: by SomewhereWarm – 1.0.9
WooCommerce Stripe Gateway: by WooCommerce – 8.5.2
WP Rocket: by WP Media – 3.15.10
Zoho Mail: by Zoho Mail – 1.5.8

### Dropin Plugins () ###

advanced-cache.php: advanced-cache.php
object-cache.php: Memcached

### Must Use Plugins (2) ###

mu-autoloader.php: by  –
Safety Net Loader: by  – 1.0.0

### Settings ###

Legacy API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: bundle (bundle)
external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: ✔

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 86 MB

### WC Pages ###

Shop base: #4849 - /shop/
Cart: #4850 - /cart/ -  Contains the woocommerce/cart block
Checkout: #4851 - /checkout/ -  Contains the woocommerce/checkout block
My account: #4852 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: [redacted]
Version: 2.0.0
Author URL: https://wpspecialprojects.wordpress.com
Child Theme: ✔
Parent Theme Name: Twenty Twenty-One
Parent Theme Version: 1.4 – 2.3 is available
Parent Theme Author URL: https://wordpress.org/
WooCommerce Support: ✔

### Templates ###

Overrides: [redacted]/woocommerce/archive-product.php version 3.4.0 is out of date. The core version is 8.6.0
[redacted]/woocommerce/cart/cart.php version 3.8.0 is out of date. The core version is 7.9.0
[redacted]/woocommerce/checkout/form-coupon.php version 3.4.4 is out of date. The core version is 7.0.1
[redacted]/woocommerce/myaccount/dashboard.php
[redacted]/woocommerce/single-product/add-to-cart/simple.php version 3.4.0 is out of date. The core version is 7.0.1
[redacted]/woocommerce/single-product.php

Outdated Templates: ❌
					
					
						Learn how to update

### Subscriptions ###

WCS_DEBUG: ✔ No
Subscriptions Mode: ❌ Staging
Subscriptions Live URL: [redacted]
Subscriptions-core Library Version: 7.3.0
Subscriptions Template Theme Overrides: [redacted]/woocommerce/emails/subscription-info.php
Subscription Statuses: –
WooCommerce Account Connected: ✔ Yes
Active Product Key: ✔ Yes
Custom Retry Rules: ✔ No
Custom Retry Rule Class: ✔ No
Custom Raw Retry Rule: ✔ No
Custom Retry Rule: ✔ No
Retries Migration Status: ✔ Completed
Report Cache Enabled: ✔ Yes
Cache Update Failures: ✔ Thanks for your payment order. It’s on-hold until we confirm that payment has been received. In the meantime
here’s a reminder of your order:


### Store Setup ###

Country / State: Canada — British Columbia

### Subscriptions by Payment Gateway ###


### Payment Gateway Support ###

Cash on delivery: products

### Product Bundles ###

Database Version: 7.2.1
Loopback Test: ✔
Template Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
pattern-toolkit-full-composability
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
printful
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page
launch-your-store

Disabled Features: experimental-blocks
minified-js
product-pre-publish-modal
settings
async-product-editor-category-field
product-editor-template-system

Daily Cron: ✔ Next scheduled: 2024-08-02 18:26:20 -07:00
Options: ✔
Notes: 41
Onboarding: completed

### Action Scheduler ###

Complete: 30,394
Oldest: 2024-07-02 05:15:21 -0700
Newest: 2024-08-02 05:14:50 -0700

Failed: 47
Oldest: 2022-04-29 14:36:17 -0700
Newest: 2023-05-12 14:42:08 -0700

Pending: 17
Oldest: 2024-08-02 05:16:14 -0700
Newest: 2024-08-03 21:44:16 -0700


### Status report information ###

Generated at: 2024-08-02 05:14:58 -07:00
```
</details>

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by moon0326**
### Changes proposed in this Pull Request:

Fixes https://github.com/woocommerce/woocommerce/issues/50270

This PR addresses an issue where `get_query_template` fails to return anything for non-block themes by manually initializing the BlockTemplatesRegistry and BlockTemplatesController

This change is required due to the recent change in how/when both controllers are initialized. See https://github.com/woocommerce/woocommerce/pull/48905
 

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Create a new JN site with this branch.
2. Navigate to `WooCommerce -> Settings -> Site Visibility` and make sure the site is in `coming soon` mode.

#### Block theme
3. Navigate to `Appearance -> Themes` and activate a block theme such as Twenty Twenty-Four.
4. Open a new incognito session and visit the frontend.
5. Confirm you see the coming soon mode page.

#### Classic theme
6. Navigate to `Appearance -> Themes` and activate a classic theme such as Storefront.
7. Open a new incognito session and visit the frontend.
8. Confirm you see the coming soon mode page.

#### Regression testing
Repeat testing instructions in https://github.com/woocommerce/woocommerce/pull/48905

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

Manually initialize block template registry and controller for non-block themes.

</details>

### CODE REVIEW

**Review by adrianduffell — APPROVED** [review]
Thanks @moon0326! This is testing well for me. Code looks good and I've made a few tweaks.

* Wrap the `include` call with a `file_exists` check.
* Move the container registration to the Blocks' Bootstrap.

Approving but we'll need another reviewer from Ghidorah as well as FSE team review 🚀

File: plugins/woocommerce/src/Internal/ComingSoon/ComingSoonRequestHandler.php [hunk 1]
```diff
@@ -66,7 +77,9 @@ function () {
 			}
 		);
 
-		include $coming_soon_template;
+		if ( ! empty( $coming_soon_template ) && file_exists( $coming_soon_template ) ) {
+			include $coming_soon_template;
+		}
```
Comment (ilyasfoo) [inline plugins/woocommerce/src/Internal/ComingSoon/ComingSoonRequestHandler.php:82]: I think it's better to have the default behaviour - which is to not block templates from rendering when coming soon template is not available.

This means it'll render the original template, like coming soon feature is disabled.

What do you think?

```suggestion
		} else {
			return $template;
		}
```

**Review by ilyasfoo — COMMENTED** [review]
Tests well, ~~but I have an opinion about the default behaviour when coming soon template doesn't exist~~.

Edit: Taking it back, this might not be an expected behaviour.

File: plugins/woocommerce/src/Internal/ComingSoon/ComingSoonRequestHandler.php (hunk 1 above)
Comment (ilyasfoo) [reply plugins/woocommerce/src/Internal/ComingSoon/ComingSoonRequestHandler.php:82]: I'm taking this back - admin may not intend for the contents to show when the site is in coming soon mode

**Review by ilyasfoo — APPROVED** [review]
Tests well, LGTM!

File: plugins/woocommerce/src/Blocks/Domain/Bootstrap.php [hunk 2]
```diff
@@ -113,6 +113,20 @@ protected function init() {
...
+			function () {
+				return new BlockTemplatesRegistry();
+			}
+		);
+		$this->container->register(
+			BlockTemplatesController::class,
+			function () {
+				return new BlockTemplatesController();
+			}
+		);
```
Comment (Aljullu) [inline plugins/woocommerce/src/Blocks/Domain/Bootstrap.php]: Could this be moved to `register_dependencies()` with all the other class registrations?

File: plugins/woocommerce/src/Internal/ComingSoon/ComingSoonRequestHandler.php [hunk 3]
```diff
@@ -48,13 +51,21 @@ public function handle_template_include( $template ) {
 		// A coming soon page needs to be displayed. Don't cache this response.
 		nocache_headers();
 
+		$is_fse_theme         = wc_current_theme_is_fse_theme();
+		$is_store_coming_soon = $this->coming_soon_helper->is_store_coming_soon();
+
+		if ( ! $is_fse_theme ) {
```
Comment (Aljullu) [inline plugins/woocommerce/src/Internal/ComingSoon/ComingSoonRequestHandler.php]: This should probably be the opposite of the check [here](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/src/Blocks/Domain/Bootstrap.php#L134), no? Otherwise, in a classic theme with support for block templates we are initializing those classes twice.

**Review by Aljullu — APPROVED** [review]
Thanks for working on this and fixing this issue! I left a couple of inline comments, but they are not blocking, so pre-approving this PR anyway given its urgency.

I have a couple of additional questions, though:

1. Has it been considered having a PHP template for the coming soon mode in classic themes? Trying to load a block template in a theme that doesn't support block templates feels a bit brittle to me, and I worry it might break again in the future.
2. ~In relation to that, do we have automated tests to verify the coming soon mode works in classic themes?~ Never mind, I see there is an issue for that: https://github.com/woocommerce/woocommerce/issues/50511.

None of those questions is a blocker either, but I thought it was worth asking.

File: plugins/woocommerce/src/Blocks/Domain/Bootstrap.php (hunk 2 above)
Comment (ilyasfoo) [reply plugins/woocommerce/src/Blocks/Domain/Bootstrap.php]: Good call! Moved it in [5720557](https://github.com/woocommerce/woocommerce/pull/50507/commits/57205577d74ebab5cc56943945fb41bd14c0008f)

File: plugins/woocommerce/src/Internal/ComingSoon/ComingSoonRequestHandler.php (hunk 3 above)
Comment (ilyasfoo) [reply plugins/woocommerce/src/Internal/ComingSoon/ComingSoonRequestHandler.php]: You're right! I've updated the logic in [d655c60](https://github.com/woocommerce/woocommerce/pull/50507/commits/d655c60747bb7f9d9d246e17f80f70de24bc4733).

I've tested registration with block theme, classic theme, and classic theme with blocks support using both [storefront-child-i.zip](https://github.com/user-attachments/files/16054910/storefront-child-i.zip) and [storefront-child-ii.zip](https://github.com/user-attachments/files/16054901/storefront-child-ii.zip) and it seems like the init runs only once in coming soon mode after the change.

**Comment by ilyasfoo** [comment]
> Has it been considered having a PHP template for the coming soon mode in classic themes? Trying to load a block template in a theme that doesn't support block templates feels a bit brittle to me, and I worry it might break again in the future.

Thanks for the feedback, @Aljullu! I agree, having a PHP template sounds like the best alternative for classic themes. However for the context of a CFE, we're trying to minimize the change to have the least potential side effects. I'll create an issue for further discussion.

Edit: Created issue: https://github.com/woocommerce/woocommerce/issues/50520

File: plugins/woocommerce/src/Internal/ComingSoon/ComingSoonRequestHandler.php (hunk 3 above)
Comment (ilyasfoo) [reply plugins/woocommerce/src/Internal/ComingSoon/ComingSoonRequestHandler.php]: Documenting the behaviour:

- twentytwentyfour: Initialize at bootstrap
- storefront-child-i.zip: Initialize at bootstrap
- storefront-child-ii.zip: Initialize at bootstrap
- storefront: Initialize at coming soon
