### PR TITLE
Use admin password reset link on admin login screen

### LINKED ISSUE #50195: 'Coming Soon' mode is preventing lost password flow
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

image

### Expected behavior

Should be able to access the lost password flow. Probably do an audit of similar functionality that may be obscured, starting with `./my-account/*`

### Actual behavior

Lost password flow is obscured when in coming soon mode

### Steps to reproduce

image

### WordPress Environment

\>= WC 9.1

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by adrianduffell**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes https://github.com/woocommerce/woocommerce/issues/50195 .

This PR keeps users in the admin UI flow when they choose to reset password from the admin login screen. This is thought to be a better experience than sending admins to the front-end My Account page to reset their password.

It also solves a bug related to coming soon mode, because the My Account page is not accessible to logged-out users, which could prevent admin users from resetting their password.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Go to Settings > Site visibility 
2. Set the store to Live and save
3. Logout and go to the admin login screen `/wp-login.php`
4. Click "Lost your password?"
5. See that the lost password screen is presented with the admin UI.
image

6. Go to the front-end of the store
7. Click "My account" in the navigation
8. Click "Lost your password?"
9. See that the lost password screen is presented with the front-end UI.

front end forget

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

**Comment by adrianduffell** [comment]
I changed approach in [42308e0](https://github.com/woocommerce/woocommerce/pull/50200/commits/42308e04b3e1cc9c0b296ea5215f13d41844ac77).

The WP function [is_login](https://developer.wordpress.org/reference/functions/is_login/) function incorrectly returns `false` on the JN admin login screen. This is because the `SCRIPT_NAME` has a custom prefix added: `/__wp__/wp-login.php`. Since other hosts may do the same, I have opted for a different approach that detects whether the My Account page is shown.

Possibly a bug fix should be made in JN or WordPress core to ensure `is_login` works in the JN environment.

**Review by psealock — APPROVED** [review]
Changes look good and this is testing well

File: plugins/woocommerce/includes/wc-account-functions.php [hunk 1]
```diff
@@ -29,15 +29,16 @@ function wc_lostpassword_url( $default_url = '' ) {
 
 	$wc_account_page_url    = wc_get_page_permalink( 'myaccount' );
 	$wc_account_page_exists = wc_get_page_id( 'myaccount' ) > 0;
+	$is_account_page        = get_the_permalink() === $wc_account_page_url;
```
Comment (rjchow) [inline plugins/woocommerce/includes/wc-account-functions.php]: I'm 50/50 on this vs only excluding the wp-admin page from the URL change - do you think there may be themes or customisation that rely on this, on custom pages involved with customer login?

Comment (adrianduffell) [reply plugins/woocommerce/includes/wc-account-functions.php]: Thanks @rjchow, it's a good point. Now that you mention it I don't have total confidence in the solution. It is probably better to re-think a way to detect the admin screen.

The existing code (below) also assumes the My Account page has been set up in the standard way, but I can't say with confidence my change would have no impact on any customizations being made.

```
if ( $wc_account_page_exists  && ! empty( $lost_password_endpoint ) ) {
	return wc_get_endpoint_url( $lost_password_endpoint, '', $wc_account_page_url );
}
```

Comment (adrianduffell) [reply plugins/woocommerce/includes/wc-account-functions.php]: @rjchow I addressed this in [4c8f9cd](https://github.com/woocommerce/woocommerce/pull/50200/commits/4c8f9cd4a5de83cbdd3e085f5ba78c35dd3f9493). 

Since I couldn't use `is_login()` (see https://github.com/woocommerce/woocommerce/pull/50200#issuecomment-2262678230), I've used an alternative mentioned in its [announcement post](https://make.wordpress.org/core/2022/09/11/new-is_login-function-for-determining-if-a-page-is-the-login-screen/). I elected to use the action detection because I understand the login page name in `$pagenow` can be commonly changed ([example](https://jetpack.com/blog/wordpress-login-url/)). I think ultimately we need to use `is_login()` but will need to get a bug fixed upstream first.

**Review by rjchow — APPROVED** [review]
Tested well! Thanks for considering the alternative! This approach works for me but I don't know if @psealock might have any comment? Just making sure there's an abundance of caution here because auth systems are quite critical and its annoying when it doesn't work right

**Review by psealock — APPROVED** [review]
Thanks for the ping @rjchow. I re tested this and its all working as expected and the solution seems more intuitive.
