### PR TITLE
Make the structured data price of group products refer to the latest child product price

### LINKED ISSUE #27941: Grouped products are missing a price update
Problem description:
- When a grouped product is created with multiple simple products in its group, it contains a range from lowest product price to highest product price.
- This lowest (simple) product price is also set in the <script type="application/ld+json"> in the source on the page of the grouped product. 
- The data in <script type="application/ld+json"> is often crawled/used for marketing purposes.
- Whenever the simple product with the lowest price gets updated, the new price will not be set in the <script type="application/ld+json">.
- When removing the simple product from the group and re-attach it afterwards the price in <script type="application/ld+json"> does get updated.

Because we use this price for marketing purposes it now shows an incorrect price.  

Environment details:
Wordpress: v5.5.1
Plugins: Woocommerce v4.5.2
Theme: Twenty Twenty v1.5

Reproduce:    
    1. Create an environment with solely the details listed above.
    2. Create at least 2 simple products one with a price of 100 and one with a price of 200
    3. Create a grouped product and link the simple products
    4. Check the section <script type="application/ld+json"> the price should say 100 now
    5. Now update the price of the 100 priced product to 50
    6. Check the section <script type="application/ld+json"> this still says the products lowest range is 100 when this should be 50
Question:
    Is it possible to make a change to the WooCommerce plugin to update this section <script type="application/ld+json"> of a grouped product to have the correct price.

### PR DESCRIPTION
**Pull request by mt8**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

- Make the structured data price of group products refer to the latest child product price

Closes #27941 .

### How to test the changes in this Pull Request:

1. Create an environment with solely the details listed above.
2. Create at least 2 simple products one with a price of 100 and one with a price of 200
3. Create a grouped product and link the simple products
4. Check the section <script type="application/ld+json"> the price should say 100 now
5. Now update the price of the 100 priced product to 50
6. Check the <script type="application/ld+json"> section. Make sure your product has a minimum range of 50

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce/includes/class-wc-structured-data.php [hunk 1]
```diff
@@ -241,6 +241,36 @@ public function generate_product_data( $product = null ) {
...
+				if ( empty( $child_prices ) ) {
+					$min_price = 0;
+				} else {
+					$min_price = min( $child_prices );
+				}
+	
+				$markup_offer = array(
+					'@type'              => 'Offer',
+					'price'              => wc_format_decimal( $min_price, wc_get_price_decimals() ),
+					'priceValidUntil'    => $price_valid_until,
```
Comment (jorgeatorres) [inline plugins/woocommerce/includes/class-wc-structured-data.php:267]: `$price_valid_until` is only defined when the product is on sale. We should also define it for products that are not on sale (as it's done above).

**Review by jorgeatorres — APPROVED** [review]
Hey @mt8!

Thanks for your contribution and apologies for the delay here. Changes look good to me.

For future reference, I think grouped products should be more performant and there would be a way to quickly determine prices instead of having to iterate over all child products. The performance penalty here should not be that high given we're anyways going to loop over the children when displaying details.

Thanks again!
