### PR TITLE
Fix react 18 upgrade todos in wc admin

### LINKED ISSUE #55398: react-18-upgrade TODOs in WC Admin
Some TODOs to be cleaned up:

https://github.com/woocommerce/woocommerce/blob/aa7ff784746fef516368022a9dfc64fcfd34074b/packages/js/onboarding/src/components/WooOnboardingTaskListHeader/WooOnboardingTaskListHeader.tsx#L24
https://github.com/woocommerce/woocommerce/blob/aa7ff784746fef516368022a9dfc64fcfd34074b/packages/js/data/src/user/test/use-user-preferences.ts#L12
https://github.com/woocommerce/woocommerce/blob/aa7ff784746fef516368022a9dfc64fcfd34074b/packages/js/admin-layout/src/plugins/woo-header-page-title/index.tsx#L38
https://github.com/woocommerce/woocommerce/blob/aa7ff784746fef516368022a9dfc64fcfd34074b/plugins/woocommerce/client/admin/client/wp-admin-scripts/print-shipping-label-banner/shipping-banner/test/index.js#L628
https://github.com/woocommerce/woocommerce/blob/aa7ff784746fef516368022a9dfc64fcfd34074b/plugins/woocommerce/client/admin/client/wp-admin-scripts/print-shipping-label-banner/shipping-banner/test/index.js#L604
https://github.com/woocommerce/woocommerce/blob/aa7ff784746fef516368022a9dfc64fcfd34074b/plugins/woocommerce/client/admin/client/wp-admin-scripts/print-shipping-label-banner/shipping-banner/test/index.js#L534
https://github.com/woocommerce/woocommerce/blob/aa7ff784746fef516368022a9dfc64fcfd34074b/plugins/woocommerce/client/admin/client/wp-admin-scripts/print-shipping-label-banner/shipping-banner/test/index.js#L224
https://github.com/woocommerce/woocommerce/blob/aa7ff784746fef516368022a9dfc64fcfd34074b/plugins/woocommerce/client/admin/client/analytics/components/report-summary/test/index.js#L13

### PR DESCRIPTION
**Pull request by chihsuan**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes https://github.com/woocommerce/woocommerce/issues/55398

Address react-18-upgrade TODOs in WC Admin

1. **User Preferences Tests**
   - Fixed test suite by using Jest mocking instead of manual store registration. The tests failed because it's not allowed to register the store multiple times with the new wp data package.
   - Removed unnecessary TypeScript ignore comments

2. **Shipping Banner Tests**
   - Removed unnecessary `act()` wrapper and `.skip()` calls
   - Improved async handling using `userEvent` and `waitFor`

3. **Report Summary Tests**
   - Added proper async tooltip handling with `waitFor`
   - Improved tooltip visibility test assertions
   - Replaced `userEvent.unhover()` with hoverOutside(). I don't know why, but it's just not working with `userEvent.unhover()`.

4. Fixed type error in `packages/js/data/src/onboarding/actions.ts`. 

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Unit tests CI should pass
2. You can also run the tests locally:

```bash
cd plugins/woocommerce/client/admin

pnpm run test:js ./client/analytics/components/report-summary/test/index.js  ./client/wp-admin-scripts/print-shipping-label-banner/shipping-banner
```

```bash
cd packages/js/data

pnpm run test:js src/user/test/use-user-preferences.ts
```

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [x] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

Fix skipped test suites after React 18 upgrade

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce/client/admin/client/wp-admin-scripts/print-shipping-label-banner/shipping-banner/test/index.js [hunk 1]
```diff
@@ -550,7 +574,7 @@ describe.skip( 'The message in the banner', () => {
 		);
 
 	const notActivatedMessage =
-		'By clicking "Create shipping label", WooCommerce Shipping(opens in a new tab) will be installed and you agree to its Terms of Service(opens in a new tab).';
+		'By clicking "Create shipping label", WooCommerce Shipping↗ will be installed and you agree to its Terms of Service↗.';
```
Comment (chihsuan) [inline plugins/woocommerce/client/admin/client/wp-admin-scripts/print-shipping-label-banner/shipping-banner/test/index.js:575]: The external link contains `↗` in rendered HTML and `aria-label` is `(opens in a new tab)`. 

https://wordpress.github.io/gutenberg/?path=/docs/components-externallink--docs

File: plugins/woocommerce/client/admin/client/wp-admin-scripts/print-shipping-label-banner/shipping-banner/test/index.js [hunk 2]
```diff
@@ -643,7 +660,7 @@ describe( 'If incompatible WCS&T is active', () => {
 			expect( acceptWcsTos ).not.toHaveBeenCalled();
 		} );
 
-		const notice = getByText( ( _, element ) => {
+		const notice = await findByText( ( _, element ) => {
```
Comment (chihsuan) [inline plugins/woocommerce/client/admin/client/wp-admin-scripts/print-shipping-label-banner/shipping-banner/test/index.js:661]: `findByText` works because it waits for the element to appear in the DOM (asynchronous).

File: plugins/woocommerce/client/admin/client/wp-admin-scripts/print-shipping-label-banner/shipping-banner/test/index.js [hunk 3]
```diff
@@ -93,6 +98,11 @@ describe( 'Tracking clicks in shippingBanner', () => {
 				getExpectedTrackingData( 'shipping_banner_create_label', false )
 			)
 		);
+
+		// Wait for any async calls to complete so we don't get `Warning: An update to ShippingBanner inside a test was not wrapped in act(...).
+		await waitFor( () => {
+			expect( acceptWcsTos ).toHaveBeenCalled();
+		} );
```
Comment (chihsuan) [inline plugins/woocommerce/client/admin/client/wp-admin-scripts/print-shipping-label-banner/shipping-banner/test/index.js:105]: There were many warnings when running the test suite.

```
Warning: An update to ShippingBanner inside a test was not wrapped in act(...).
```

I fixed it by waiting for acceptWcsTos to be called. When clicking the button, it will trigger the async call to accept the WCS TOS and trigger a state update so we need to wait for that to complete.

File: plugins/woocommerce/client/admin/client/analytics/components/report-summary/test/index.js [hunk 4]
```diff
@@ -10,9 +10,24 @@ import { createElement } from '@wordpress/element';
...
+const waitExpectTooltipToShow = async ( timeout = 3000 ) =>
+	await waitFor( expectTooltipToBeVisible, { timeout } );
+
+const waitExpectTooltipToHide = async ( timeout = 3000 ) =>
+	await waitFor( expectTooltipToBeHidden, { timeout } );
+
+const hoverOutside = async () => {
+	await userEvent.hover( document.body );
+	await userEvent.hover( document.body, { clientX: 10, clientY: 10 } );
+};
```
Comment (chihsuan) [inline plugins/woocommerce/client/admin/client/analytics/components/report-summary/test/index.js:28]: See how WP Tooltip component is tested.

https://github.com/WordPress/gutenberg/blob/3416bf4b0db6679b86e8e4226cbdb0d3387b25d7/packages/components/src/tooltip/test/index.tsx#L23-L42

Comment (rjchow) [reply plugins/woocommerce/client/admin/client/analytics/components/report-summary/test/index.js:28]: smart lol, I struggled with this for quite awhile but didn't think to hover outside!

File: plugins/woocommerce/client/admin/client/wp-admin-scripts/print-shipping-label-banner/shipping-banner/test/index.js (hunk 3 above)
Comment (rjchow) [reply plugins/woocommerce/client/admin/client/wp-admin-scripts/print-shipping-label-banner/shipping-banner/test/index.js:105]: Good one!

**Review by rjchow — APPROVED** [review]
Thank you 🙇 Test changes look fine to me - only thing that stood out to me is the change from registerStore to directly mocking select. There is a slight difference there but I'm not sure it matters

**Review by adrianduffell — APPROVED** [review]
Nice, thanks @chihsuan 🚀
