### PR TITLE
[Performance]: WooCommerce status widget on dashboard now loads async

### LINKED ISSUE #46931: woocommerce_dashboard_status is extremely slow for high volume stores
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

The status widget from the WC_Admin_Dashboard class runs several queries that all add up to an extremely slow load time for sites with a lot of data. 

Note, that the worst of the queries added to this widget come from WooCommerce Subscriptions, but WooCommerce core has a few that take several seconds to complete.  The overall load time for an uncached visit to the dashboard each day is nearly two minutes.

### Expected behavior

~~These queries should be cached to prevent them from running every time the dashboard is rendered.  Since this is just a report, it shouldn't need to be updated constantly with live data.  It should be good enough to have~~ The cached report should be regenerated as an async cron/action as opposed to being rendered during a user visit to the dashboard.

### Actual behavior

The initial priming of cache takes place during a user/admin visit to the dashboard causing long wait times.

### Steps to reproduce

1. On a site with a high number of orders, use a tool like debug bar to show the queries being run.
2. Load the wp-admin dashboard and review the queries.

### WordPress Environment

WPCOM

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by naman03malhotra**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes #46931 
From the issue ^
>The overall load time for an uncached visit to the dashboard each day is nearly two minutes.

In high volume store, this PR should bring down the home page load times from minutes to milliseconds.

At present, the status widget loads synchronously, which is a blocker for the page to load due to a high number of slow queries in the status widget. This PR enables the status widget to load asynchronously, thus eliminating the long page wait times for sites with a high number of orders.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Create a site with a large number of orders (>1k) with status `completed`. You can use [smooth generator](https://github.com/woocommerce/wc-smooth-generator) for this. You can use `wp wc generate orders <nr of orders> --status=completed`
2. From `Status > Scheduled Actions`, run the pending actions to generate analytics data.
3. When on `trunk`, Visit `https://w.test/wp-admin/index.php`.
4. When using a tool like query monitor, you'll see a number of slow queries related to the status widget, and the complete page has to load for the widget to render.
5. Now switch to `fix/46931-async-widget`, reload the home page. You should be able to see that the above queries and slow queries related to the status widget no longer exist.
6. You'll observe a placeholder indicating the widget is loading, and after a few milliseconds (or seconds, depending on the processing time of widget queries), the widget gets loaded.
7. You'll also observe an Ajax request set from the browser post the past is loaded with action `woocommerce_load_status_widget`

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

**Review by albarin — APPROVED** [review]
- Checked in `trunk` I was seeing the slow query which disappeared when in the PR branch.
- Checked the widget now loads async on the dashboard.

loading

loaded

**Comment by naman03malhotra** [comment]
@prettyboymp requested a review from you as well, to make sure this is the outcome we wanted.

File: plugins/woocommerce/includes/class-wc-ajax.php [hunk 1]
```diff
@@ -3636,6 +3637,20 @@ public static function toggle_gateway_enabled() {
 		wp_die();
 	}
 
+	/**
+	 * AJAX handler for asynchronously loading the status widget content.
+	 */
+	public static function load_status_widget() {
+		check_ajax_referer( 'wc-status-widget', 'security' );
```
Comment (prettyboymp) [inline plugins/woocommerce/includes/class-wc-ajax.php:3644]: We should add the capability checks from `WC_Admin_Dashboard::should_display_widget()` here as well.

**Review by prettyboymp — CHANGES_REQUESTED** [review]
Great simple fix to offload the report loading from the initial request.  This has been a huge pain point when first logging into the admin.

I have just one suggestion around security.

File: plugins/woocommerce/includes/class-wc-ajax.php (hunk 1 above)
Comment (naman03malhotra) [reply plugins/woocommerce/includes/class-wc-ajax.php:3644]: 💯 Added as part of https://github.com/woocommerce/woocommerce/pull/56039/commits/c9e0ba2a9ac482de6be0376ca0e51c3fd2e53fa7

**Comment by naman03malhotra** [comment]
@albarin @prettyboymp can please take a final look 👀

**Review by albarin — APPROVED** [review]

**Review by prettyboymp — APPROVED** [review]
Looks great.  :shipit:

**Comment by vbelolapotkov** [comment]
FYI folks (no action needed), that PR broke WooCommerce Subscriptions integration and potentially some other integrations, because now hooks for extending widget content are moved from dashboard loading request (we had hooks here) to new ajax request (no hooks here).

See WOOSUBS-697 for more context, if curious.
