### PR TITLE
Fix: Customer Table not populating due to error caused when ANSI_QUOTES setting is enabled in Database Setting

### LINKED ISSUE #55818: Bad string quoting in SQL when using a POST to /orders leads to [Unknown column '0000-00-00 00:00:00' in 'field list']
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

I am posting a new order using the POST /orders endpoint of the rest API. The post data may well be incorrect; I can't tell because Woo is throwing the following error:

WordPress database error: [Unknown column '0000-00-00 00:00:00' in 'field list']
SELECT wp_wc_customer_lookup.customer_id as id, user_id, username, CONCAT_WS( ' ', first_name, last_name ) as name, email, country, city, state, postcode, date_registered, IF( date_last_active <= "0000-00-00 00:00:00", NULL, date_last_active ) AS date_last_active, MAX( wp_wc_order_stats.date_created ) as date_last_order, SUM( CASE WHEN parent_id = 0 THEN 1 ELSE 0 END ) as orders_count, SUM( total_sales ) as total_spend, CASE WHEN SUM( CASE WHEN parent_id = 0 THEN 1 ELSE 0 END ) = 0 THEN NULL ELSE SUM( total_sales ) / SUM( CASE WHEN parent_id = 0 THEN 1 ELSE 0 END ) END AS avg_order_value FROM wp_wc_customer_lookup LEFT JOIN wp_wc_order_stats ON wp_wc_customer_lookup.customer_id = wp_wc_order_stats.customer_id AND ( wp_wc_order_stats.status NOT IN ( 'wc-auto-draft','wc-trash','wc-pending','wc-failed','wc-cancelled','wc-checkout-draft' ) ) WHERE 1=1 AND wp_wc_customer_lookup.customer_id IN (308) GROUP BY wp_wc_customer_lookup.customer_id ORDER BY date_registered DESC LIMIT 0, 10

This statement seems to be generated in `Admin/API/Reports/Customers/DataStore.php`

A second issue: art appears that order creation is not transactional, as I am left with an empty order in WooCommerce corresponding to this failed post, and the API returns 2021/created when it actually failed.

### Expected behavior

I would expect no record to be created, and some indication of why my upload failed.

### Actual behavior

See above

### Steps to reproduce

Here's the data I was sending:

~~~ ruby
{:number=>"#28207",
  :status=>"completed",
  :date_created_gmt=>"2006-40-13T01:40:22Z",
  :date_updated_gmt=>"2007-17-09T14:17:51Z",
  :date_paid=>"2006-06-13T17:06:41Z",
  :billing=>
   {:first_name=>"xxxx",
    :last_name=>"xxx",
    :email=>"a@a.net",
    :company=>"xxxxx",
    :phone=>"",
    :address_1=>"xxxxx",
    :address_2=>"",
    :postcode=>"xxxxx",
    :city=>"xxxxx",
    :state=>"VIC",
    :country=>"Australia"},
  :shipping=>
   {:first_name=>"xxxx",
    :last_name=>"yyy",
    :email=>"a@a.net",
    :company=>"xxxxxxxx",
    :phone=>"",
    :address_1=>"xxxxxx",
    :address_2=>"",
    :postcode=>"xxxx",
    :city=>"xxxx",
    :state=>"VIC",
    :country=>"Australia"},
  :payment_method=>"CC",
  :transaction_id=>"credit card",
  :line_items=>[{:name=>"Rails Recipes", :product_id=>1216, :variation_id=>nil, :total=>21.5, :quantity=>1, :sku=>"FR_RR-P-00", :price=>21.5}],
  :tax_items=>[],
  :fee_lines=>[],
  :coupon_lines=>[],
  :refunds=>[],
  :set_paid=>true}]
~~~

### WordPress Environment

<details><summary>System Status Report</summary>

```
### WordPress Environment ###

WordPress address (URL): [Redacted]
Site address (URL): [Redacted]
WC Version: 9.6.2
Legacy REST API Package Version: The Legacy REST API plugin is not installed on this site.
Action Scheduler Version: ✔ 3.9.0
Log Directory Writable: ✔
WP Version: ❌ 6.7.1 - There is a newer version of WordPress available (6.7.2)
WP Multisite: –
WP Memory Limit: 2 GB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.24.0
PHP Version: 8.3.6
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 8.5.0
OpenSSL/3.0.13

SUHOSIN Installed: –
MySQL Version: 8.0.30
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

[REDACTED]

### Post Type Counts ###

attachment: 575
customize_changeset: 2
nav_menu_item: 24
nectar_slider: 4
page: 23
post: 51
product: 471
product_variation: 1568
revision: 46
salient_g_sections: 2
shop_coupon: 2
shop_order_placehold: 1
user_registration: 1
wp_font_family: 12
wp_global_styles: 3
wp_navigation: 1
wp_template: 2
yith_wcan_preset: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (1) ###

WooCommerce: by Automattic – 9.6.2

### Inactive Plugins (33) ###

Add From Server: by Dion Hulse – 3.4.5
Akismet Anti-spam: Spam Protection: by Automattic - Anti-spam Team – 5.3.7
Classic Editor: by WordPress Contributors – 1.6.7
MailPoet: by MailPoet – 5.7.0
Redirection: by John Godley – 5.5.2
Redis Object Cache: by Till Krüss – 2.5.4
Salient Core: by ThemeNectar – 3.0.4
Salient Custom Branding: by ThemeNectar – 1.0.0
Salient Demo Importer: by ThemeNectar – 1.7
Salient Home Slider: by ThemeNectar – 1.4.1
Salient Nectar Slider: by ThemeNectar – 1.7.7
Salient Portfolio: by ThemeNectar – 1.8
Salient Shortcodes: by ThemeNectar – 1.5.4
Salient Social: by ThemeNectar – 1.2.5
Salient Widgets: by ThemeNectar – 1.3.1
Salient WPBakery Page Builder: by Michael M - WPBakery.com | Modified by ThemeNectar – 7.8.1
UpdraftPlus - Backup/Restore: by TeamUpdraft
DavidAnderson – 1.25.1

User Registration & Membership: by WPEverest – 4.0.4
User Role Editor: by Vladimir Garagulya – 4.64.4
WordPress Importer: by wordpressdotorg – 0.8.3
WP All Import - Gravity Forms Add-On: by Soflyy – 1.0.1
WP All Import - JetEngine Add-On: by Soflyy – 1.0.0
WP All Import - Meta Box Add-On: by Soflyy – 1.0.1
WP All Import - Toolset Types Add-On Pro: by Soflyy – 1.0.7
WP All Import - User Import Add-On Pro: by Soflyy – 1.1.8
WP All Import - WooCommerce Import Add-On Pro: by Soflyy – 4.0.0
WP All Import Pro: by Soflyy – 4.9.11
WP Crontrol: by John Blackbourn – 1.18.0
WP fail2ban: by Charles Lecklider – 5.4.0.1
WP File Manager: by mndpsingh287 – 8.0.1
WP Image Mask: by Bogdan Bendziukov – 3.1.2
WP Test Email: by Boopathi Rajan – 1.1.8
YITH WooCommerce Ajax Product Filter: by YITH – 5.8.0

### Settings ###

Legacy API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 78 KB

### WC Pages ###

Shop base: #7 - /shop/
Cart: #8 - /cart/ -  Contains the woocommerce/cart block
Checkout: #9 - /checkout/ -  Contains the woocommerce/checkout block
My account: #10 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty-Five
Version: 1.1
Author URL: https://wordpress.org
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
Theme type: Block theme
WooCommerce Support: ❌ Not declared

### Templates ###

Overrides: /home/deploy/oho-site/wordpress/wp-content/plugins/woocommerce/templates/block-notices/error.php
/home/deploy/oho-site/wordpress/wp-content/plugins/woocommerce/templates/block-notices/notice.php
/home/deploy/oho-site/wordpress/wp-content/plugins/woocommerce/templates/block-notices/success.php


### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
onboarding
onboarding-tasks
pattern-toolkit-full-composability
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
printful
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page
launch-your-store

Disabled Features: product-data-views
experimental-blocks
coming-soon-newsletter-template
minified-js
product-pre-publish-modal
settings
async-product-editor-category-field
product-editor-template-system
blueprint
reactify-classic-payments-settings
use-wp-horizon
add-to-cart-with-options-stepper-layout
blockified-add-to-cart

Daily Cron: ✔ Next scheduled: 2025-02-25 17:45:49 +00:00
Options: ✔
Notes: 65
Onboarding: skipped

### Action Scheduler ###

Complete: 7,332
Oldest: 2025-02-13 17:46:58 +0000
Newest: 2025-02-25 03:54:22 +0000

Failed: 6
Oldest: 2025-02-13 17:46:58 +0000
Newest: 2025-02-21 21:14:31 +0000

Pending: 1
Oldest: 2025-02-25 20:11:19 +0000
Newest: 2025-02-25 20:11:19 +0000


### Status report information ###

Generated at: 2025-02-25 03:54:35 +00:00
```
</details>

### Isolating the problem

- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

### LINKED ISSUE #61161: Customer table not populating with ANSI_QUOTES enabled database
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Similar to the bug described in [#51216](https://github.com/woocommerce/woocommerce/issues/51216)

With `ANSI_QUOTES` enabled, when you navigate to Woocommerce -> Customers page, the customer table is empty and it shows : **No data to display**.

In `debug.log` we can see an error:

```
WordPress database error Unknown column '0000-00-00 00:00:00' in 'field list'
```

on the Query:

```
SELECT
    wp_wc_customer_lookup.customer_id AS id,
    user_id,
    username,
    CONCAT_WS(' ', first_name, last_name) AS name,
    email,
    country,
    city,
    state,
    postcode,
    date_registered,
    IF(date_last_active <= "0000-00-00 00:00:00", NULL, date_last_active) AS date_last_active,
    MAX(wp_wc_order_stats.date_created) AS date_last_order,
    SUM(CASE WHEN parent_id = 0 THEN 1 ELSE 0 END) AS orders_count,
    SUM(total_sales) AS total_spend,
    CASE 
        WHEN SUM(CASE WHEN parent_id = 0 THEN 1 ELSE 0 END) = 0 
        THEN NULL 
        ELSE SUM(total_sales) / SUM(CASE WHEN parent_id = 0 THEN 1 ELSE 0 END) 
    END AS avg_order_value
FROM
    wp_wc_customer_lookup
    LEFT JOIN wp_wc_order_stats 
        ON wp_wc_customer_lookup.customer_id = wp_wc_order_stats.customer_id
        AND (
            wp_wc_order_stats.status NOT IN (
                'wc-auto-draft',
                'wc-trash',
                'wc-pending',
                'wc-cancelled',
                'wc-failed',
                'wc-checkout-draft'
            )
        )
WHERE
    1 = 1
GROUP BY
    wp_wc_customer_lookup.customer_id
ORDER BY
    date_last_active DESC
LIMIT 0, 25;
```

The above query contains a line with double quotes which causes the database error in MySQL with `ANSI_QUOTES` enabled:

```
IF(date_last_active <= "0000-00-00 00:00:00", NULL, date_last_active)
```

This query is done in `assign_report_columns()` method which lives inside the `DataStore` class in `Automattic\WooCommerce\Admin\API\Reports\Customers`.

### Expected behavior

Customer table inside Woocommerce should populate data with MySQL having ANSI_QUOTES enabled.

### Actual behavior

Customer table displays no data.

### Steps to reproduce

1. Edit `my.cnf` to add sql_mode=ANSI_QUOTES
2. Add a new user with the Customer role, fill in their basic details, and place an order
3. In the WordPress Admin Dashboard, go to WooCommerce → Customers
4. You will see “No data to display” even though customer data exists

### WordPress Environment

<details>

<summary>WordPress Environment</summary>

```
### WordPress Environment ###

WordPress address (URL): [Redacted]
Site address (URL): [Redacted]
WC Version: 9.8.5
Legacy REST API Package Version: The Legacy REST API plugin is not installed on this site.
Action Scheduler Version: ✔ 3.9.2
Log Directory Writable: ✔
WP Version: ❌ 6.6.2 - There is a newer version of WordPress available (6.8.2)
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_GB
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.63 (Unix) PHP/8.4.10
PHP Version: 8.4.10
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 8.15.0
OpenSSL/3.5.1

SUHOSIN Installed: –
MySQL Version: 9.3.0
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

[REDACTED]

### Post Type Counts ###

attachment: 10034
custom_css: 8
custom-css-js: 14
customize_changeset: 2
jetpack_migration: 2
nav_menu_item: 84
oembed_cache: 3
page: 38
post: 59
product: 876
product_variation: 1593
revision: 1359
shop_coupon: 279
shop_order: 63196
shop_order_placehold: 739
shop_order_refund: 1281
wapf_product: 1
woo_discount: 5
woo_discount_cart: 3
wp_global_styles: 1
wp_navigation: 1

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 9.8.5

### Inactive Plugins () ###

### Dropin Plugins () ###

### Must Use Plugins () ###

### Settings ###

Legacy API Enabled: –
Force SSL: –
Currency: INR (₹)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: composite (composite)
external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: –
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 0 B

### WC Pages ###

Shop base: #204 - /shop/
Cart: #205 - /cart/ -  Contains the woocommerce/cart block
Checkout: #206 - /checkout/ -  Contains the woocommerce/checkout block
My account: #207 - /my-account/ -  Contains the [woocommerce_my_account] shortcode
Terms and conditions: #508 - /terms-and-conditions/

### Theme ###

Name:
Version: 1.0.0
Author URL: 
Child Theme: ✔
Parent Theme Name: Neve
Parent Theme Version: 4.1.2 – 4.1.4 is available
Parent Theme Author URL: https://themeisle.com
Theme type: Classic theme
WooCommerce Support: ✔


### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
onboarding
onboarding-tasks
pattern-toolkit-full-composability
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
printful
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page
launch-your-store
add-to-cart-with-options-stepper-layout

Disabled Features: product-data-views
experimental-blocks
coming-soon-newsletter-template
minified-js
product-pre-publish-modal
settings
async-product-editor-category-field
product-editor-template-system
use-wp-horizon
blockified-add-to-cart

Daily Cron: ✔ Next scheduled: 2025-09-24 19:13:09 +05:30
Options: ✔
Notes: 25
Onboarding: completed

### Action Scheduler ###

Canceled: 5,901
Oldest: 2025-09-24 12:07:40 +0000
Newest: -0001-11-30 00:00:00 +0000

Complete: 17,723
Oldest: 2025-08-01 18:17:55 +0000
Newest: 2025-09-24 12:09:53 +0000

Failed: 93
Oldest: 2022-07-12 06:31:33 +0000
Newest: 2025-08-22 10:04:30 +0000

Pending: 2
Oldest: 2025-09-25 08:02:35 +0000
Newest: 2025-09-25 08:02:35 +0000


### Status report information ###

Generated at: 2025-09-24 19:19:40 +05:30
```
</details>

### Isolating the problem

- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by EthanVaz11**
### Changes proposed in this Pull Request:

Closes #61161, closes #55818, closes WOOPLUG-3240

This PR fixes an SQL query issue in the Customer Reports where the use of incorrect quotation marks caused errors when running under MySQL mode that is: `ANSI_QUOTES` enabled.  
The fix updates the `assign_report_columns()` method in the `DataStore` class to use appropriate quotation marks:

The Error I encountered clearly directs it to the `IF Clause`:

```
WordPress database error Unknown column '0000-00-00 00:00:00' in 'field list' for query 
			SELECT
				wp_wc_customer_lookup.customer_id as id, user_id, username, CONCAT_WS( ' ', first_name, last_name ) as name, email, country, city, state, postcode, date_registered, IF( date_last_active <= "0000-00-00 00:00:00", NULL, date_last_active ) AS date_last_active, MAX( wp_wc_order_stats.date_created ) as date_last_order, SUM( CASE WHEN parent_id = 0 THEN 1 ELSE 0 END ) as orders_count, SUM( total_sales ) as total_spend, CASE WHEN SUM( CASE WHEN parent_id = 0 THEN 1 ELSE 0 END ) = 0 THEN NULL ELSE SUM( total_sales ) / SUM( CASE WHEN parent_id = 0 THEN 1 ELSE 0 END ) END AS avg_order_value
			FROM
				wp_wc_customer_lookup
				LEFT JOIN wp_wc_order_stats ON wp_wc_customer_lookup.customer_id = wp_wc_order_stats.customer_id AND ( wp_wc_order_stats.status NOT IN ( 'wc-auto-draft','wc-trash','wc-pending','wc-cancelled','wc-failed','wc-checkout-draft' ) )
			WHERE
				1=1
				
		
				GROUP BY
					wp_wc_customer_lookup.customer_id
			
				ORDER BY
					date_last_active desc
			LIMIT 0, 25 made by require('wp-blog-header.php'), wp, WP->main, WP->parse_request, do_action_ref_array('parse_request'), WP_Hook->do_action, WP_Hook->apply_filters, rest_api_loaded, WP_REST_Server->serve_request, WP_REST_Server->dispatch, WP_REST_Server->respond_to_request, Automattic\WooCommerce\Admin\API\Reports\GenericController->get_items, Automattic\WooCommerce\Admin\API\Reports\Customers\Controller->get_datastore_data, Automattic\WooCommerce\Admin\API\Reports\GenericQuery->get_data, WC_Data_Store->__call, Automattic\WooCommerce\Admin\API\Reports\DataStore->get_data, Automattic\WooCommerce\Admin\API\Reports\Customers\DataStore->get_noncached_data
```

### How to test the changes in this Pull Request:

1. Set up WooCommerce with a MySQL configuration that includes `ANSI_QUOTES`.
2. Navigate to **WooCommerce → Analytics → Customers** in wp-admin.
3. Without the fix, the query fails and the customer report does not load along with a Database Error:
  
image
image

4. With this fix applied, the report loads correctly without errors:
    
image

### Testing that has already taken place:

- Tested locally on MySQL 8.0 with `ANSI_QUOTES` enabled.  
- Verified reports load correctly without errors.

### Changelog entry

- [x] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message This PR fixes the bug where Customer Analytics are not getting populated for DBs with ANSI_QUOTES enabled

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment
</details>

### CODE REVIEW

**Comment by tjcafferkey** [comment]
Thanks for this @EthanVaz11, the CI is currently failing the changelog check. You can generate one by navigating into the `plugins/woocommerce` directory and running `npm run changelog add` which will run you through a quick 2-3 steps process to create one which you can commit to this PR

**Comment by EthanVaz11** [comment]
> Thanks for this @EthanVaz11, the CI is currently failing the changelog check. You can generate one by navigating into the `plugins/woocommerce` directory and running `npm run changelog add` which will run you through a quick 2-3 steps process to create one which you can commit to this PR

@tjcafferkey Thanks for acknowledging this PR and helping me out with the workflow. Although I ran the `npm`command to generate the changelog and answered the following questions asked on the terminal it's still giving the same error. As you can see in my commits that the changelog has been added in the directory `plugins/woocommerce/changelog/61212-fix-customer-analytics-fix-with-ansi_quotes-enabled` :
```
Run pnpm utils changefile 61212 -o woocommerce

> woocommerce-monorepo@ utils /home/runner/work/woocommerce/woocommerce
> ./tools/monorepo-utils/bin/run "changefile" "61212" "-o" "woocommerce"

Getting pull request data for PR number 61212
Task complete.
No changelog message found
 ELIFECYCLE  Command failed with exit code 1.
 WARN   Local package.json exists, but node_modules missing, did you mean to install?
Error: Process completed with exit code 1.
```

Is there something else that I missed out on ?

**Comment by EthanVaz11** [comment]
> > Thanks for this @EthanVaz11, the CI is currently failing the changelog check. You can generate one by navigating into the `plugins/woocommerce` directory and running `npm run changelog add` which will run you through a quick 2-3 steps process to create one which you can commit to this PR
> 
> @tjcafferkey Thanks for acknowledging this PR and helping me out with the workflow. Although I ran the `npm`command to generate the changelog and answered the following questions asked on the terminal it's still giving the same error. As you can see in my commits that the changelog has been added in the directory `plugins/woocommerce/changelog/61212-fix-customer-analytics-fix-with-ansi_quotes-enabled` :
> 
> ```
> Run pnpm utils changefile 61212 -o woocommerce
> 
> > woocommerce-monorepo@ utils /home/runner/work/woocommerce/woocommerce
> > ./tools/monorepo-utils/bin/run "changefile" "61212" "-o" "woocommerce"
> 
> Getting pull request data for PR number 61212
> Task complete.
> No changelog message found
>  ELIFECYCLE  Command failed with exit code 1.
>  WARN   Local package.json exists, but node_modules missing, did you mean to install?
> Error: Process completed with exit code 1.
> ```
> 
> Is there something else that I missed out on ?

@tjcafferkey I figured what the issue was by seeing where and how the error was getting Logged causing it to fail. Apparently it has a regex checker that checks a Message inside the PR description xD `const messageRegex = /#### Message ?(<!--(.*?)-->)?(.*?)<\/details>/gms;`
and I had unconsciously removed it. Anyways it passed the changelog check !

**Comment by tjcafferkey** [comment]
Thanks for this! I have approved the workflows to run against this PR. I will assign @sunyatasattva as the reviewer as he's assigned to the issue.

**Comment by EthanVaz11** [comment]
@tjcafferkey Sorry for the inconvenience — I think I accidentally closed the issue when I intended to approve your comment. (For some reason, when adding a comment, it shows both “Close with comment” and “Comment” buttons, and I must have clicked the wrong one.)

Just wanted to check if this might have affected the workflow since it’s now showing:
"4 workflows awaiting approval. This workflow requires approval from a maintainer."

Really sorry about the mix-up!

**Comment by EthanVaz11** [comment]
@sunyatasattva Hey have you got a chance to review this PR ?

File: plugins/woocommerce/src/Admin/API/Reports/Customers/DataStore.php [hunk 1]
```diff
@@ -82,7 +82,7 @@ protected function assign_report_columns() {
 			'state'            => 'state',
 			'postcode'         => 'postcode',
 			'date_registered'  => 'date_registered',
-			'date_last_active' => 'IF( date_last_active <= "0000-00-00 00:00:00", NULL, date_last_active ) AS date_last_active',
+			'date_last_active' => "IF( date_last_active <= '0000-00-00 00:00:00', NULL, date_last_active ) AS date_last_active", // Changed IF clause from Double Quotes to Single Quotes with sql_mode=ANSI_QUOTES
```
Comment (sunyatasattva) [inline plugins/woocommerce/src/Admin/API/Reports/Customers/DataStore.php]: Thank you for submitting the PR @EthanVaz11 ! I've got quite a big backlog of reviews, but I'm going through them and I should be able to get through this within a week. In the meantime, I have approved the workflows to run, so we can spot anything you might need to fix.

Also, just quickly perusing the code, I can already say that we probably want to change this comment. I agree that a comment is needed here if that's the fix that we require. However, it should be a line above the `date_last_active` and explain why the line below has double quotes (it should explain the _status quo_, not mention something in the past like “changed”).

**Review by sunyatasattva — CHANGES_REQUESTED** [review]

File: plugins/woocommerce/src/Admin/API/Reports/Customers/DataStore.php (hunk 1 above)
Comment (EthanVaz11) [reply plugins/woocommerce/src/Admin/API/Reports/Customers/DataStore.php]: @sunyatasattva Thank you for taking the time to review this! I can imagine the backlog you’re working through — no worries at all on my end.
I’ve updated the PR with your suggested changes, and thanks for spotting that detail as well!

**Comment by EthanVaz11** [comment]
@sunyatasattva Hey any update on this ? Sorry for the disturbance I understand that you must be having a lot of workload. Just adding a small reminder on this

**Review by sunyatasattva — APPROVED** [review]
There was a small linting error, everything else looks good to me. I'm trying to get CI to run the jobs, but I'm getting some strange errors. Once they are gone, we are ready to merge! Thanks for the contribution!
