### PR TITLE
Better locale switching for emails

### LINKED ISSUE #15414: [3.1.0] Order details in wrong language
Storefront 2.2.3
only WooCommerce 3.1.0-beta
WordPress 4.7.5

To reproduce:
Go to Users > Your profile: set French
Go to Settings > General > Site Language: set English (United States).

The WooCommerce menu (admin sidebar) is in French as expected.

But go to WooCommerce > Orders > edit order: 

* the Order metabox is in English, such as the labels 'General Details', 'Order Status'('Pending payment', 'Processing'..)'Customer', 'Billing details'... 

* the Order actions metabox is in English (except the title) such as 'Resend order emails'.

* the Note metabox is in English (except the title) such as 'Add note', 'Private note', 'Add' button ...

* the Item metabox is in English, such as the 'SKU', the 'Refund', the 'Add item(s)' and the 'Add tax' buttons and also the labels 'Cost', 'Qty',  'Discount', 'Shipping', 'Order total'.

* the Downloadable product permissions metabox is also in English (except the title) such as 'Search for a downloadable product ...) and the 'Grant access' button.

I didn't reproduce this issue when the Site Language and the Admin language are in French.
No issue in WooCommerce 3.0.7

### PR DESCRIPTION
**Pull request by mikejolley**
This PR makes it so emails only switch to site language during the actual send, not on construct. This is more efficient.

This PR also implements a more robust way to switch locale using WP filters so the correct language files are loaded when we need site language, not user language.

Closes #15414

### CODE REVIEW

File: includes/wc-core-functions.php [hunk 1]
```diff
@@ -1624,8 +1624,40 @@ function wc_get_permalink_structure() {
...
+	}
+}
+
+/**
+ * Switch WooCommerce language to original.
+ *
+ * @since 3.1.0
+ */
+function wc_restore_locale() {
+	restore_previous_locale();
```
Comment (claudiulodro) [inline includes/wc-core-functions.php]: `restore_previous_locale` was introduced in 4.7, so I think we need a `function_exists` check here, too.

**Comment by claudiulodro** [comment]
Looks good and works well. Just needs one tiny change then it's good to go.
