### PR TITLE
Prevent analytics import orders action from being scheduled when analytics is disabled

### LINKED ISSUE #54791: Scheduled action `wc-admin_import_orders` fails
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Since WooCommerce 9.6.0, I discovered that for every new order, an action named `wc-admin_import_orders` is automatically scheduled but fails. 
The error message in the scheduled actions list is as follows:
`Action failed via WP Cron: Scheduled action for wc-admin_import_orders will not be executed as no callbacks are registered.`

Upon reviewing the source code, I noticed that there is indeed an action registered with that hook.

### Expected behavior

The scheduled action shouldn't fail or be removed if not needed.

### Actual behavior

The scheduled action runs on every new order and fails.

### Steps to reproduce

1. Create a new order
2. Open Scheduled Actions \ Failed tab

### WordPress Environment

<details><summary>System Status Report</summary>

```
### WordPress Environment ###

WordPress address (URL): [Redacted]
Site address (URL): [Redacted]
WC Version: 9.6.0
Legacy REST API Package Version: The Legacy REST API plugin is not installed on this site.
Action Scheduler Version: ✔ 3.9.0
Log Directory Writable: ✔
WP Version: 6.7.1
WP Multisite: ✔
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.19.2
PHP Version: 8.2.4
PHP Post Max Size: 8 MB
PHP Time Limit: 360
PHP Max Input Vars: 1000
cURL Version: 7.68.0
OpenSSL/1.0.2u

SUHOSIN Installed: –
MySQL Version: 5.7.39
Max Upload Size: 1 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

[REDACTED]

### Post Type Counts ###

attachment: 18
campaign: 1
nav_menu_item: 5
page: 13
post: 8
product: 4
product_variation: 43
revision: 56
shop_coupon: 7
shop_discount: 2
shop_order: 37
shop_order_refund: 3
shop_subscription: 11
wp_global_styles: 1
wps_subscriptions: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (10) ###

Co-Authors Plus: by Mohammad Jangda
Daniel Bachhuber
Automattic – 3.6.3

iubenda | All-in-one Compliance for GDPR / CCPA Cookie Consent + more: by iubenda – 3.11.3
Simple Local Avatars: by 10up – 2.8.3
User Switching: by John Blackbourn – 1.9.1
WooCommerce Stripe Gateway: by Stripe – 9.1.1
WooCommerce Subscriptions: by WooCommerce – 7.1.0
WooCommerce: by Automattic – 9.6.0
WordPress Importer: by wordpressdotorg – 0.8.3
WP Crontrol: by John Blackbourn – 1.18.0
WP Mail SMTP: by WP Mail SMTP – 4.3.0

### Inactive Plugins (1) ###

Classic Editor: by WordPress Contributors – 1.6.7

### Settings ###

Legacy API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 72 KB

### WC Pages ###

Shop base: #45 - /products/
Cart: ❌ Page does not contain the [woocommerce_cart] shortcode or the woocommerce/cart block.
Checkout: #47 - /checkout/ -  Contains the [woocommerce_checkout] shortcode
My account: #48 - /account/
Terms and conditions: #353 - /legal/terms/

### Theme ###

Name: Mine
Version: 1.0
Author URL: 
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
Theme type: Classic theme
WooCommerce Support: ❌ Not declared

### Templates ###



### Subscriptions ###

WCS_DEBUG: ✔ No
Subscriptions Mode: ✔ Live
Subscriptions Live URL: https://
Subscriptions-core Library Version: 7.9.0
Subscriptions Template Theme Overrides: 
Subscription Statuses: wc-active: 6
wc-pending: 1
wc-on-hold: 3
wc-cancelled: 1

WooCommerce Account Connected: ❌ No
Custom Retry Rules: ✔ No
Custom Retry Rule Class: ✔ No
Custom Raw Retry Rule: ✔ No
Custom Retry Rule: ✔ No
Retries Migration Status: ✔ Completed
Report Cache Enabled: ✔ Yes
Cache Update Failures: ✔ 0 failure

### Store Setup ###

Country / State: United States (US) — Delaware

### Subscriptions by Payment Gateway ###

Direct bank transfer: wc-on-hold: 1
Stripe: wc-active: 5
wc-cancelled: 1
wc-on-hold: 2
wc-pending: 1


### Payment Gateway Support ###

Stripe: products
refunds
tokenization
add_payment_method
subscriptions
subscription_cancellation
subscription_suspension
subscription_reactivation
subscription_amount_changes
subscription_date_changes
subscription_payment_method_change
subscription_payment_method_change_customer
subscription_payment_method_change_admin
multiple_subscriptions

Direct bank transfer: products

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
onboarding
onboarding-tasks
pattern-toolkit-full-composability
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
printful
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page
launch-your-store

Disabled Features: product-data-views
experimental-blocks
coming-soon-newsletter-template
minified-js
product-pre-publish-modal
settings
async-product-editor-category-field
product-editor-template-system
blueprint
reactify-classic-payments-settings
use-wp-horizon
add-to-cart-with-options-stepper-layout
blockified-add-to-cart

Daily Cron: ✔ Next scheduled: 2025-01-23 04:33:42 +00:00
Options: ✔
Notes: 41
Onboarding: completed

### Action Scheduler ###

Complete: 162
Oldest: 2024-12-23 08:07:39 +0000
Newest: 2025-01-22 19:06:20 +0000

Failed: 19
Oldest: 2024-11-08 07:07:07 +0000
Newest: 2025-01-22 12:04:39 +0000

Pending: 20
Oldest: 2025-01-23 07:05:28 +0000
Newest: 2050-03-16 00:00:00 +0000


### Status report information ###

Generated at: 2025-01-22 19:14:48 +00:00
```
</details>

### Isolating the problem

- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

### LINKED ISSUE #55123: Actions "wc-admin_import_orders" being scheduled, and failing, when orders are processed
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Even though we do not use WC-Admin and have disabled it, we frequently see events for "wc-admin_import_orders" being scheduled, and subsequently failing. This happens for we created an order in the admin backend.

### Expected behavior

When WC-Admin is disabled, no events related to it should be scheduled.

### Actual behavior

See above

### Steps to reproduce

n/a

### WordPress Environment

<details><summary>System Status Report</summary>

```
### WordPress Environment ###

WordPress address (URL): [Redacted]
Site address (URL): [Redacted]
WC Version: 9.6.0
Legacy REST API Package Version: The Legacy REST API plugin is not installed on this site.
Action Scheduler Version: ✔ 3.9.0
Log Directory Writable: ✔
WP Version: 6.7.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 8.0.30
PHP Post Max Size: 16 MB
PHP Time Limit: 600
PHP Max Input Vars: 1000
cURL Version: 7.76.1
OpenSSL/3.0.7

SUHOSIN Installed: –
MySQL Version: 8.0.32
Max Upload Size: 16 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

[REDACTED]

[redacted]

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (36) ###

Akismet Anti-spam: Spam Protection: by Automattic - Anti-spam Team – 5.3.5
Analytics Insights: by DeConf – 6.3.9
Solid Security Basic: by SolidWP – 9.3.6
Default featured image: by Jan Willem Oostendorp – 1.8.0
Disable Toolbar: by Michael Dance – 1.0
Divi Toolbox: by Divi Lover – 1.7.4
Gravity Forms: by Gravity Forms – 2.9.2
InfiniteWP - Client: by Revmakx – 1.13.1
Kadence WooCommerce Email Designer: by Kadence WP – 1.5.14
Mailgun: by Mailgun – 2.1.3
No Nonsense: by Room 34 Creative Services LLC – 3.5.1
Redirection: by John Godley – 5.5.1
W3 Total Cache: by BoldGrid – 2.8.4
Checkout Field Editor for WooCommerce: by ThemeHigh – 2.1.2
WooCommerce.com Update Manager: by Automattic – 1.0.3
WooCommerce EU VAT Number: by WooCommerce – 2.9.13
WooCommerce Stripe Gateway: by Stripe – 9.1.1
PDF Invoices & Packing Slips for WooCommerce: by WP Overnight – 3.9.6
WooCommerce Product Add-Ons: by Woo – 7.4.0
WooCommerce Shipping & Tax: by WooCommerce – 2.8.7
WooCommerce Subscriptions: by WooCommerce – 7.1.0
WooCommerce: by Automattic – 9.6.0 (update to version 9.6.1 is available)
Yoast SEO: by Team Yoast – 24.3
WP Crontrol: by John Blackbourn – 1.18.0
Divi Gravity Forms: by WP Tools – 8.5.0
YITH WooCommerce Customize My Account Page Premium: by YITH – 4.16.0

### Inactive Plugins (1) ###

--

### Dropin Plugins () ###

advanced-cache.php: advanced-cache.php
db.php: db.php

### Must Use Plugins (2) ###

InfiniteWP - Client Loader: by Revmakx – 1.0.1
Some filters for Gravity Forms processing: by Erik Geurts – 1.0.0

### Settings ###

Legacy API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: –
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 818 KB

### WC Pages ###

Shop base: #14654 - /shop/
Cart: #14655 - /cart/ -  Contains the [woocommerce_cart] shortcode
Checkout: #14656 - /checkout/ -  Contains the [woocommerce_checkout] shortcode
My account: #14657 - /my-account/
Terms and conditions: #97 - /about/terms-conditions/

### Theme ###

Name: Divi 404 (English)
Version: 1.1.0
Author URL: [Redacted]
Child Theme: ✔
Parent Theme Name: Divi
Parent Theme Version: 4.27.4
Parent Theme Author URL: http://www.elegantthemes.com
Theme type: Classic theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Subscriptions ###

WCS_DEBUG: ✔ No
Subscriptions Mode: ✔ Live
Subscriptions Live URL: [Redacted]
Subscriptions-core Library Version: 7.9.0
Subscriptions Template Theme Overrides: Divi-404-en/woocommerce/emails/customer-notification-auto-renewal.php
Divi-404-en/woocommerce/emails/customer-notification-expiring-subscription.php

Subscription Statuses: wc-active: [Redacted]
wc-cancelled: [Redacted]

WooCommerce Account Connected: ✔ Yes
Active Product Key: ✔ Yes
Custom Retry Rules: ✔ No
Custom Retry Rule Class: ✔ No
Custom Raw Retry Rule: ✔ No
Custom Retry Rule: ✔ No
Retries Migration Status: ✔ Completed
Report Cache Enabled: ✔ Yes
Cache Update Failures: ✔ 0 failure

### Store Setup ###

Country / State: Netherlands

### Subscriptions by Payment Gateway ###

Stripe: wc-active: [Redacted]
wc-cancelled: [Redacted]


### Payment Gateway Support ###

Stripe: products
refunds
tokenization
add_payment_method
subscriptions
subscription_cancellation
subscription_suspension
subscription_reactivation
subscription_amount_changes
subscription_date_changes
subscription_payment_method_change
subscription_payment_method_change_customer
subscription_payment_method_change_admin
multiple_subscriptions


### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
onboarding
onboarding-tasks
pattern-toolkit-full-composability
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
printful
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page
launch-your-store

Disabled Features: product-data-views
experimental-blocks
coming-soon-newsletter-template
minified-js
product-pre-publish-modal
settings
async-product-editor-category-field
product-editor-template-system
blueprint
reactify-classic-payments-settings
use-wp-horizon
add-to-cart-with-options-stepper-layout
blockified-add-to-cart

Daily Cron: ✔ Next scheduled: 2025-02-05 15:41:08 -05:00
Options: ✔
Notes: 3
Onboarding: completed

### Action Scheduler ###

Complete: 427
Oldest: 2025-01-05 13:15:15 +0000
Newest: 2025-02-05 03:07:05 +0000

Failed: 26
Oldest: 2025-01-27 13:35:06 +0000
Newest: 2025-02-03 14:16:05 +0000

Pending: 218
Oldest: 2025-02-05 21:50:07 +0000
Newest: 2026-02-03 08:00:54 +0000


### Status report information ###

Generated at: 2025-02-05 05:11:48 -05:00
```
</details>

### Isolating the problem

- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

### LINKED ISSUE #56616: Action `wc-admin_import_orders` is still scheduled when WC Analytics disabled
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

The issue was related to #54791 #55123.

Starting from WooCommerce 9.6, when the WC Analytics feature is disabled from `WooCommerce > Settings > Advanced > Features`, the action `wc-admin_import_orders` will still be scheduled when, for example, an order is created or updated, and caused the error after it's run:

> Action failed via WP Cron: Scheduled action for wc-admin_import_orders will not be executed as no callbacks are registered.

Before WC 9.6, when WC Analytics feature is disabled the action wouldn't be scheduled when an order is created / updated.

### Expected behavior

When WC Analytics feature is disabled, the action `wc-admin_import_orders` should not be scheduled when an order is created / updated.

### Actual behavior

When WC Analytics feature is disabled, the action `wc-admin_import_orders` is scheduled when an order is created / updated after WC 9.6.

### Steps to reproduce

1. Use WC >= 9.6
2. Disable WC Analytics feature in  `WooCommerce > Settings > Advanced > Features`
3. Purchase some products so an order is created
4. Go to `WooCommerce > Status > Scheduled Actions`, see the action `wc-admin_import_orders` is scheduled
5. Wait for it or click `Run` on the action, see the error occur
6. Use WC 9.5.2
7. Purchase some products
8. The action is not scheduled in `WooCommerce > Status > Scheduled Actions`

### WordPress Environment

Copied from the issue #54791

<details><summary>System Status Report</summary>

### WordPress Environment ###

WordPress address (URL): [Redacted]
Site address (URL): [Redacted]
WC Version: 9.6.0
Legacy REST API Package Version: The Legacy REST API plugin is not installed on this site.
Action Scheduler Version: ✔ 3.9.0
Log Directory Writable: ✔
WP Version: 6.7.1
WP Multisite: ✔
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.19.2
PHP Version: 8.2.4
PHP Post Max Size: 8 MB
PHP Time Limit: 360
PHP Max Input Vars: 1000
cURL Version: 7.68.0
OpenSSL/1.0.2u

SUHOSIN Installed: –
MySQL Version: 5.7.39
Max Upload Size: 1 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

[REDACTED]

### Post Type Counts ###

attachment: 18
campaign: 1
nav_menu_item: 5
page: 13
post: 8
product: 4
product_variation: 43
revision: 56
shop_coupon: 7
shop_discount: 2
shop_order: 37
shop_order_refund: 3
shop_subscription: 11
wp_global_styles: 1
wps_subscriptions: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (10) ###

Co-Authors Plus: by Mohammad Jangda
Daniel Bachhuber
Automattic – 3.6.3

iubenda | All-in-one Compliance for GDPR / CCPA Cookie Consent + more: by iubenda – 3.11.3
Simple Local Avatars: by 10up – 2.8.3
User Switching: by John Blackbourn – 1.9.1
WooCommerce Stripe Gateway: by Stripe – 9.1.1
WooCommerce Subscriptions: by WooCommerce – 7.1.0
WooCommerce: by Automattic – 9.6.0
WordPress Importer: by wordpressdotorg – 0.8.3
WP Crontrol: by John Blackbourn – 1.18.0
WP Mail SMTP: by WP Mail SMTP – 4.3.0

### Inactive Plugins (1) ###

Classic Editor: by WordPress Contributors – 1.6.7

### Settings ###

Legacy API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 72 KB

### WC Pages ###

Shop base: #45 - /products/
Cart: ❌ Page does not contain the [woocommerce_cart] shortcode or the woocommerce/cart block.
Checkout: #47 - /checkout/ -  Contains the [woocommerce_checkout] shortcode
My account: #48 - /account/
Terms and conditions: #353 - /legal/terms/

### Theme ###

Name: Mine
Version: 1.0
Author URL: 
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
Theme type: Classic theme
WooCommerce Support: ❌ Not declared

### Subscriptions ###

WCS_DEBUG: ✔ No
Subscriptions Mode: ✔ Live
Subscriptions Live URL: https://
Subscriptions-core Library Version: 7.9.0
Subscriptions Template Theme Overrides: 
Subscription Statuses: wc-active: 6
wc-pending: 1
wc-on-hold: 3
wc-cancelled: 1

WooCommerce Account Connected: ❌ No
Custom Retry Rules: ✔ No
Custom Retry Rule Class: ✔ No
Custom Raw Retry Rule: ✔ No
Custom Retry Rule: ✔ No
Retries Migration Status: ✔ Completed
Report Cache Enabled: ✔ Yes
Cache Update Failures: ✔ 0 failure

### Store Setup ###

Country / State: United States (US) — Delaware

### Subscriptions by Payment Gateway ###

Direct bank transfer: wc-on-hold: 1
Stripe: wc-active: 5
wc-cancelled: 1
wc-on-hold: 2
wc-pending: 1

### Payment Gateway Support ###

Stripe: products
refunds
tokenization
add_payment_method
subscriptions
subscription_cancellation
subscription_suspension
subscription_reactivation
subscription_amount_changes
subscription_date_changes
subscription_payment_method_change
subscription_payment_method_change_customer
subscription_payment_method_change_admin
multiple_subscriptions

Direct bank transfer: products

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
onboarding
onboarding-tasks
pattern-toolkit-full-composability
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
printful
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page
launch-your-store

Disabled Features: product-data-views
experimental-blocks
coming-soon-newsletter-template
minified-js
product-pre-publish-modal
settings
async-product-editor-category-field
product-editor-template-system
blueprint
reactify-classic-payments-settings
use-wp-horizon
add-to-cart-with-options-stepper-layout
blockified-add-to-cart

Daily Cron: ✔ Next scheduled: 2025-01-23 04:33:42 +00:00
Options: ✔
Notes: 41
Onboarding: completed

### Action Scheduler ###

Complete: 162
Oldest: 2024-12-23 08:07:39 +0000
Newest: 2025-01-22 19:06:20 +0000

Failed: 19
Oldest: 2024-11-08 07:07:07 +0000
Newest: 2025-01-22 12:04:39 +0000

Pending: 20
Oldest: 2025-01-23 07:05:28 +0000
Newest: 2050-03-16 00:00:00 +0000

### Status report information ###

Generated at: 2025-01-22 19:14:48 +00:00
</details>

### Isolating the problem

- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by ianlin**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes #56616.
Closes #54791.
Closes #55123.

This PR prevents the `wc-admin_import_orders` analytics action from being scheduled when the analytics feature is disabled.

The issue was introduced in [#52480](https://github.com/woocommerce/woocommerce/pull/52480), which aimed to stop admin feature classes from loading on the frontend. However, it also [checks in get_feature_class()](https://github.com/woocommerce/woocommerce/pull/52480/files#diff-445f2f2cde958786c92a21d75fbed58a94a5594efc1f2056843fb4c6a9ccb3a7R114-R117), which is called by [Features::is_enabled](https://github.com/woocommerce/woocommerce/blob/59ae21fd3bc070153eae5d095cb76ba022996dc1/plugins/woocommerce/src/Admin/Features/Features.php#L206) -> [Features::get_available_features()](https://github.com/woocommerce/woocommerce/blob/59ae21fd3bc070153eae5d095cb76ba022996dc1/plugins/woocommerce/src/Admin/Features/Features.php#L176). If the feature class doesn't exist, it defaults to returning all features, including analytics, even when analytics is disabled.

Since `get_feature_class()` returns the class as a string, it's fine to remove the check while still fulfilling the purpose of #52480.

### Screenshots or screen recordings:

| Before | After |
| ------ | ----- |
|        |       |

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Use WC >= 9.6
2. Disable WC Analytics feature in `WooCommerce > Settings > Advanced > Features`
3. Purchase some products so an order is created
4. Go to `WooCommerce > Status > Scheduled Actions`, see the action `wc-admin_import_orders` is not scheduled
5. Verifying the unit test is passed by running ~`pnpm --filter="@woocommerce/plugin-woocommerce" test:php:env --testsuite=wc-phpunit-legacy -- --filter 'WC_Admin_Tests_Analytics_Feature'`~ `pnpm --filter="@woocommerce/plugin-woocommerce" test:php:env --testsuite=wc-phpunit-main -- --filter 'FeatureEnabledTest'`
6. Revert the c1e0444005f88b6a06b10419602675e9055ba948 locally and run the test, see the test is failed

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

Fix - Prevent analytics import orders action from being scheduled when analytics is disabled

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

**Comment by ianlin** [comment]
Hey @chihsuan, tagging you as a reviewer since you're the author of #52480 and I'd like to make sure I'm not missing something. 🙏

**Review by chihsuan — COMMENTED** [review]
Thanks for the investigation and the fix! @ianlin Apologize for the problems caused by #52480

> Since get_feature_class() returns the class as a string, it's fine to remove the check while still fulfilling the purpose of #52480.

I think that eliminating the check in `get_feature_class()` will result in the feature classes being autoloaded when `get_feature_class()` is called. Because `class_exists` will trigger the autoloader and load the class. It doesn't initialize the class though.

Do you think there is an alternative solution to address this issue?

File: plugins/woocommerce/tests/legacy/unit-tests/woocommerce-admin/features/analytics-feature.php [hunk 1]
```diff
@@ -0,0 +1,28 @@
...
+ */
+
+declare(strict_types=1);
+
+use Automattic\WooCommerce\Admin\Features\Features;
+
+/**
+ * class WC_Admin_Tests_Analytics_Feature.
+ */
+class WC_Admin_Tests_Analytics_Feature extends WC_Unit_Test_Case {
```
Comment (chihsuan) [inline plugins/woocommerce/tests/legacy/unit-tests/woocommerce-admin/features/analytics-feature.php]: We should move the tests to `woocommerce/plugins/woocommerce/tests/php/src/Admin/Features/`.

**Comment by ianlin** [comment]
Thanks for reviewing and the suggestion @chihsuan.

> Because class_exists will trigger the autoloader and load the class. It doesn't initialize the class though.

Thanks for the heads up, and you're right that `class_exists` will auto load the classes if it's not loaded by default if we don't specify the 2nd parameter as false. However, I was following the testing instruction in #52840:

> 9. Add the following code to `Features.php` before [line 56](https://github.com/woocommerce/woocommerce/blob/eb4cfbcc4e5b10780d72bd7097e67b40c9d37afa/plugins/woocommerce/src/Admin/Features/Features.php#L55):
>
> ```php
> spl_autoload_register(
>	function( $classname ) {
>		error_log( print_r( $classname, true ) );
>	}
> );
>```
>
> 10. Add `define( 'DISABLE_WP_CRON', true );` to `wp-config.php` to prevent wp-cron from loading admin features by itself
> 11. Go to frontend in incognito mode and confirm no errors
> 12. Confirm `wp-content/debug.log` doesn't log any `Automattic\WooCommerce\Admin\Features\` classes

And I didn't see the Admin Feature classes were being loaded in the `debug.log`, not sure if I miss something?

**Comment by ianlin** [comment]
Either way, I added a commit to pass the 2nd parameter to `class_exists()` method so it's explicitly not loading the class while checking its existence. I also moved the test to the correct folder as you suggested, it's ready for another round of review.

**Review by chihsuan — APPROVED** [review]
> And I didn't see the Admin Feature classes were being loaded in the debug.log, not sure if I miss something?

I couldn't see the logs, either. I guess something might have changed.

> Either way, I added a commit to pass the 2nd parameter to class_exists() method so it's explicitly not loading the class while checking its existence. I also moved the test to the correct folder as you suggested, it's ready for another round of review.

Thanks for addressing the feedback, the changes look good to me! Tested well. 👍 

___

#### Test environment

<details>
- WordPress: 6.7.2
- Theme: Twenty Twenty-Five Version: 1.1
- WooCommerce: Development version with fix/56616-54791-55123-analytics-import-orders-action-scheduled-when-analytics-is-disabled branch
- PHP: 8.3
- Web Server: Nginx
- Browser: Brave
- OS: macOS Sequoia 15.3.1
</details>

#### Review checklist

| Parameter | Result |
|-----------|---------|
| Approach | ✅ Good - Addresses root cause by fixing class autoloading behavior |
| Implementation | ✅ Clean and focused change |
| Automated tests | ✅ Tests moved to correct location and cover core functionality |
| Naming | ✅ Clear and consistent |
| Typing | ✅ Appropriate use of types |
| Code comments | ✅ Sufficient |
| Changelog | ✅ Clear and descriptive |
| Documentation | ✅ Sufficient inline documentation |
| PR description | ✅ Well explained with context |
| Testing instructions | ✅ Clear and comprehensive |
| Manual testing | ✅ Works as expected |

#### Scenarios tested

| Scenario | Result | Screenshot |
|----------|---------|------------|
| Create new order with analytics disabled | ✅ No import action scheduled | |
| Create new order with analytics enabled | ✅ Import action scheduled correctly | Screenshot 2025-04-01 at 17 48 24 |

**Comment by chihsuan** [comment]
@ianlin  This isn't a blocker for the merge, but I wanted to check if we need to initialize these classes on the front end. Would you happen to have any insights on their necessity there?

https://github.com/woocommerce/woocommerce/blob/fec0008b32ec0895bb111205b8034fb89e2bc444/plugins/woocommerce/src/Internal/Admin/FeaturePlugin.php#L174-L181

I noticed that other admin classes are being initialized in the front end as well. Some of them, such as onboarding classes, are only required in the admin context. I think there is a chance to optimize the performance.

**Comment by ianlin** [comment]
Thanks for the detailed review @chihsuan!

> I wanted to check if we need to initialize these classes on the front end. Would you happen to have any insights on their necessity there?
> https://github.com/woocommerce/woocommerce/blob/fec0008b32ec0895bb111205b8034fb89e2bc444/plugins/woocommerce/src/Internal/Admin/FeaturePlugin.php#L174-L181

The `ReportsSync` class is required on the frontend when the Analytics feature is enabled (i.e. when the `woocommerce_analytics_enabled` option is set to true via `WooCommerce > Settings > Advanced > Features`). It registers actions like `wc-admin_import_orders`, so when an order is created or updated, the action gets scheduled to import order data into the `wc_order_stats` table for analytics.

I'm not so sure but I think `ReportExport` class might not be required on the frontend, it would require some testing to understand.

> I noticed that other admin classes are being initialized in the front end as well. Some of them, such as onboarding classes, are only required in the admin context. I think there is a chance to optimize the performance.

Indeed, there are still room for performance improvement, but I think it's not an easy task to determine which is not needed. I can create an issue as a follow up. Thanks for pointing this out!

**Comment by kaushikasomaiya** [comment]
@ianlin @chihsuan I cannot replicate this issue on my end but a merchant is seeing it - assume the PR takes care of it but I am curious how can we replicate this?

**Comment by ianlin** [comment]
@kaushikasomaiya Did you follow the steps to reproduce in #56616? Those steps are sufficient enough to replicate the issue I think.

**Comment by kaushikasomaiya** [comment]
@ianlin  Yes those steps did not help replicate - in merchant's case one thing I am sure is possibly_schedule_import() was getting hooked despite Analytics disabled from settings while in my site, possibly_schedule_import was not being hooked.

**Comment by pawelkmpt** [comment]
It'd be nice if it was merged also to previous WooCommerce versions. I'm running 9.7.1 and this is spamming my log heavily.

**Comment by chihsuan** [comment]
@pawelkmpt Sorry for causing you any trouble! We don't really support patching older versions. Any reasons that you want to keep using 9.7.1 instead of updating to the latest version?

While we don't officially support older versions, you can manually apply the fix by copying the changes from the PR. Just remember to create a backup of the file first for safety.

**Comment by pawelkmpt** [comment]
> @pawelkmpt Sorry for causing you any trouble! We don't really support patching older versions. Any reasons that you want to keep using 9.7.1 instead of updating to the latest version?

Updating to the latest version immediately is usually risky, so I prefer to wait couple of weeks until given release is stable.

I made a workaround fix with attaching empty callback to the action to prevent spamming. Will remove it once I'm on 9.9.
