### PR TITLE
Hide ratings when reviews are disabled

### LINKED ISSUE #22470: Star ratings not editable when reviews are disabled
**Describe the bug**
When the **Enable reviews** option is disabled the review stars still show on the shop and category pages. In turn, then **Product ratings** is no longer editable from the Settings > Product page.

**Expected behavior**
Because the star option within **Product ratings** isn't dependant on **Enable reviews**, it should not be hidden based on the **Enable reviews** configuration. The problem this creates is when **Enable reviews** is set to disable, the expectation is assumed stars should remain enabled without the ability to control otherwise.

**Screenshot to reproduce**
Here is a screenshot of the stars option not longer becoming available after reviews are disabled([#](http://cld.wthms.co/D6GIGC))

**Isolating the problem (mark completed items with an [x]):**
- [X ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by kloon**
### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:
Ratings forms part of the review system, this PR fixes an issue where if you disable reviews it will still show the ratings. Since ratings are part of reviews and the settings are hidden when you disable reviews the ratings should also not be disabled as reviews when you disable reviews.

Closes #22470 

### How to test the changes in this Pull Request:

1. Enable ratings and enable reviews and save settings
2. Create a rating for a product
3. Disable just the reviews setting and save
4. Check the shop page for the product and ensure no star ratings are displayed.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

### Changelog entry

> Fix - Hide ratings on the shop page when reviews are disabled.

### CODE REVIEW

File: templates/loop/rating.php [hunk 1]
```diff
@@ -21,8 +21,8 @@
 
 global $product;
 
-if ( get_option( 'woocommerce_enable_review_rating' ) === 'no' ) {
+if ( 'no' === get_option( 'woocommerce_enable_review_rating' ) || 'no' === get_option( 'woocommerce_enable_reviews' ) ) {
```
Comment (mikejolley) [inline templates/loop/rating.php]: Can we make a helper function for this to see if ratings should be enabled/visible? Then if we need to tweak this logic in the future, we can avoid a template update.

**Review by mikejolley — CHANGES_REQUESTED** [review]

**Comment by mikejolley** [comment]
Let's keep this back for 3.6 since it's spanning multiple template files. The bug itself isn't critical or new.

**Comment by kloon** [comment]
Sounds good.

**Review by mikejolley — CHANGES_REQUESTED** [review]
Versions need changing to 3.6.0 then this can be merged.

**Review by mikejolley — APPROVED** [review]
