### PR TITLE
Fix product count display on mini cart first render

### LINKED ISSUE #52114: Mini cart with Show Cart Item Count: Never shows the quantity until hovered
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

This issue is the reverse of https://github.com/woocommerce/woocommerce/issues/50877 but I didn't spot it at that time.

The mini cart block has a setting "Show Cart Item Count: Never" which should NOT show a quantity badge, but on first load it does. When hovered the badge disappears.

### Expected behavior

Mini cart block should never show the quantity badge when the "Show Cart Item Count: Never" setting is enabled for the block

### Actual behavior

It does show the badge, although it does vanish when you hover the icon on the frontend.

### Steps to reproduce

* Edit the page template containing the mini cart block
* Select the mini-cart block
* Change the Show Cart Item Count setting to "Never"
* Go to front end shop page and add some items to your cart
* Now reload the page
* Note that the quantity badge is shown
* Hover the badge to see it vanish

### PR DESCRIPTION
**Pull request by opr**
### Changes proposed in this Pull Request:

Updates the PHP render of the Mini-Cart block so that the setting for displaying the product count is reflected on first render. In the block settings the count can be shown: always (`always`), never (`never`), or if cart is not empty (`greater_than_zero`).

The bug manifests because the initial HTML for the block is written to the page as plain HTML and hydrated only when the user interacts with the mini cart, this led to an incorrect state being shown where the setting was not respected.

In the case that the attribute is set to `never`, or `greater_than_zero` and product count is 0, the HTML for the badge will not be output in PHP.

If `always` or `greater_than_zero` and product count is >0 the HTML for the badge _will_ be output in PHP.

Also, PHP Unit tests have been added

Closes #52114

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Add the Mini-Cart block to your site (or find it in the site editor, usually in the header)
2. Select the Mini-Cart block in the editor and go to the `Show Cart Item Count:` setting
3. Set this to `Never`.
4. Ensure the preview on the editor updates, and the badge is hidden.
5. Load the block on the front end and ensure there is no count badge on the Mini-Cart block. Test this with an item in the cart, and no items in the cart. Ensure the badge never shows.
6. Go back to the Mini-Cart block in the editor and go to the `Show Cart Item Count:` setting
7. Set this to `Always (Even if empty)`.
8. Ensure the preview on the editor updates, and the badge is shown.
9. Load the block on the front end and ensure there is a count badge on the Mini-Cart block. Test this with an item in the cart, and no items in the cart. It should show 0 when the cart is empty, and the number of products when it is not. Ensure the number updates as you add/remove items from your cart.
10. Go back to the Mini-Cart block in the editor and go to the `Show Cart Item Count:` setting
11. Set this to `Only if cart has items`.
12. Ensure the preview on the editor updates, and the badge is shown.
13. Load the block on the front end and empty your cart. Ensure there is no count badge on the Mini-Cart block.
14. Add an item to your cart and ensure the count is shown.
15. Remove the item from your cart and ensure the count is no longer shown.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce/tests/php/src/Blocks/BlockTypes/MiniCart.php [hunk 1]
```diff
@@ -0,0 +1,88 @@
...
+		$output = render_block( $block[0] );
+		$this->assertStringContainsString( '<span class="wc-block-mini-cart__badge"', $output );
+
+		// Tests badge *is* shown, because product count is greater than zero when "greater_than_zero" is selected.
+		$block  = parse_blocks( '<!-- wp:woocommerce/mini-cart {"productCountVisibility":"greater_than_zero"} /-->' );
+		$output = render_block( $block[0] );
+		$this->assertStringContainsString( '<span class="wc-block-mini-cart__badge"', $output );
+
+		// Tests badge is not shown with items in cart when "never" is selected.
+		$block  = parse_blocks( '<!-- wp:woocommerce/mini-cart {"productCountVisibility":"always"} /-->' );
```
Comment (alexflorisca) [inline plugins/woocommerce/tests/php/src/Blocks/BlockTypes/MiniCart.php]:
```suggestion
		$block  = parse_blocks( '<!-- wp:woocommerce/mini-cart {"productCountVisibility":"never"} /-->' );
```

File: plugins/woocommerce/tests/php/src/Blocks/BlockTypes/MiniCart.php [hunk 2]
```diff
@@ -0,0 +1,88 @@
...
+		$output = render_block( $block[0] );
+		$this->assertStringContainsString( '<span class="wc-block-mini-cart__badge"', $output );
```
Comment (alexflorisca) [inline plugins/woocommerce/tests/php/src/Blocks/BlockTypes/MiniCart.php]:
```suggestion
		$this->assertStringNotContainsString( '<span class="wc-block-mini-cart__badge"', $output );
```

**Review by alexflorisca — CHANGES_REQUESTED** [review]
Nice work, this tests well, code looks good mostly, I think you just missed changing some of the logic in the test

**Comment by opr** [comment]
> Nice work, this tests well, code looks good mostly, I think you just missed changing some of the logic in the test

Thanks, yeah I did 🙈

**Review by alexflorisca — APPROVED** [review]
All good now, thanks for making the changes. 👍

**Comment by samueljseay** [comment]
I think this closes https://github.com/woocommerce/woocommerce/issues/50877 as well?

**Comment by opr** [comment]
Yes, thanks Sam
