### PR TITLE
Fixed the jetpack redirect url for sites in subdirectories

### LINKED ISSUE #17296: Setup Wizard Redirect Back to Site After Jetpack Signup
Brand new vanilla WordPress install (ver 4.8.2) and vanilla WooCommerce install (ver 3.2.1) Upon installing WooCommerce I went through the setup wizard. I got to the step where I could enable live shipping and sales tax. I left the options on and was asked to login or create a new WordPress.com account. I chose the option to create a new account. When the account creation was completed I was redirected back to the new WooCommerce install at https://www.example.com/wootest/wootest/wp-admin/?page=wc-setup&step=activate&from=wpcom NOTE: how it included the subfolder twice in the URL /wootest/wootest/ I'm not sure if this a WooCommerce hiccup or if it's coming from WordPress.com or even Jetpack itself....

### PR DESCRIPTION
**Pull request by marcinbot**
Fixes #17296

To test:
* Set up a wordpress site in a subdirectory
* Checkout this branch
* Go through the setup wizard and select a service that requires a Jetpack connection
* Connect Jetpack via a wizard step and verify that you're redirected back to the wizard
* Should also still work for the sites located at the root directory

### CODE REVIEW

File: includes/admin/class-wc-admin-setup-wizard.php [hunk 1]
```diff
@@ -1576,10 +1576,12 @@ public function wc_setup_activate_save() {
 			exit;
 		}
 
-		$redirect_url   = site_url( add_query_arg( array(
+		$redirect_url   = add_query_arg( array(
```
Comment (mikejolley) [inline includes/admin/class-wc-admin-setup-wizard.php]: Does this need to be escaped?

Comment (marcinbot) [reply includes/admin/class-wc-admin-setup-wizard.php]: I don't think so. None of this is coming from a non-admin input, and also passing the result to `esc_url` results in escaped &s in the query string

File: includes/admin/class-wc-admin-setup-wizard.php [hunk 2]
```diff
@@ -1576,10 +1576,12 @@ public function wc_setup_activate_save() {
...
+			'page'           => 'wc-setup',
+			'step'           => 'activate',
 			'from'           => 'wpcom',
 			'activate_error' => false,
-		) ) );
+		), get_admin_url() );
```
Comment (dechov) [inline includes/admin/class-wc-admin-setup-wizard.php]: The original redirect (and the rest of the codebase) uses `admin_url`:
https://github.com/woocommerce/woocommerce/blob/e296a276e3c540188d77e5494f7eba15209c7f52/includes/admin/class-wc-admin.php#L150 Probably a trivial concern but FYI in case it makes any difference.

File: includes/admin/class-wc-admin-setup-wizard.php (hunk 1 above)
Comment (mikejolley) [reply includes/admin/class-wc-admin-setup-wizard.php]: `get_admin_url` is filterable by plugins. It's not high-risk at all, but implementing `esc_url_raw` would not be a bad idea IMO.

Comment (marcinbot) [reply includes/admin/class-wc-admin-setup-wizard.php]: 👍 Fixed in cbcbc29
