### PR TITLE
#23850 Fixed the coupon usage limit issue when apply coupon from admin panel

### LINKED ISSUE #23850: Unable to use coupon on orders' backend since 3.6.4
**Describe the bug**

Applying coupons to an order (on the backend) gives the `Coupon usage limit has been reached` error, even though coupon has no restrictions. This happens only for WooCommerce 3.6.4, while it works fine on WooCommerce 3.6.3.

**To Reproduce**

- Create an order on wp-admin backend.
- Set it to `Pending payment` or `On hold` status. The other statuses do not allow applying a coupon code.
- Create a coupon code with percentage discount, say 10% off.
- Open the `On hold` order.
- Apply the coupon code.
- Notice the error.

**Screenshots**

Screenshot 2019-05-31 at 08 53 06

**Expected behavior**

The coupon code applies as expected.

**Situation on WooCommerce 3.6.3**:

Try the same process on WooCommerce 3.6.3, and the error will not be seen. The coupon code applies fine in that case.

Screenshot 2019-05-31 at 08 52 16

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
`
### WordPress Environment ###

WordPress address (URL): https://certain-jackal.jurassic.ninja
Site address (URL): https://certain-jackal.jurassic.ninja
WC Version: 3.6.4
Log Directory Writable: ✔
WP Version: 5.2.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.39 (Unix) OpenSSL/1.0.2g
PHP Version: 7.3.5
PHP Post Max Size: 1 GB
PHP Time Limit: 30
PHP Max Input Vars: 5000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.7.26-0ubuntu0.16.04.1-log
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.6.4
WC Database Prefix: wp_39f7fbc23c_
MaxMind GeoIP Database: ✔
Total Database Size: 4.32MB
Database Data Size: 3.06MB
Database Index Size: 1.26MB
wp_39f7fbc23c_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
wp_39f7fbc23c_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_39f7fbc23c_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_39f7fbc23c_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB
wp_39f7fbc23c_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wp_39f7fbc23c_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB
wp_39f7fbc23c_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_39f7fbc23c_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wp_39f7fbc23c_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_39f7fbc23c_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wp_39f7fbc23c_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_39f7fbc23c_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_39f7fbc23c_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_39f7fbc23c_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_39f7fbc23c_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_39f7fbc23c_comments: Data: 0.02MB + Index: 0.09MB
wp_39f7fbc23c_links: Data: 0.02MB + Index: 0.02MB
wp_39f7fbc23c_options: Data: 2.09MB + Index: 0.05MB
wp_39f7fbc23c_postmeta: Data: 0.25MB + Index: 0.23MB
wp_39f7fbc23c_posts: Data: 0.08MB + Index: 0.06MB
wp_39f7fbc23c_snippets: Data: 0.02MB + Index: 0.00MB
wp_39f7fbc23c_termmeta: Data: 0.02MB + Index: 0.03MB
wp_39f7fbc23c_terms: Data: 0.02MB + Index: 0.03MB
wp_39f7fbc23c_term_relationships: Data: 0.02MB + Index: 0.02MB
wp_39f7fbc23c_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wp_39f7fbc23c_usermeta: Data: 0.02MB + Index: 0.03MB
wp_39f7fbc23c_users: Data: 0.02MB + Index: 0.05MB
wp_39f7fbc23c_wcpv_commissions: Data: 0.02MB + Index: 0.00MB
wp_39f7fbc23c_wcpv_per_product_shipping_rules: Data: 0.02MB + Index: 0.00MB
wp_39f7fbc23c_wc_bookings_availability: Data: 0.02MB + Index: 0.02MB
wp_39f7fbc23c_wc_bookings_availabilitymeta: Data: 0.02MB + Index: 0.03MB
wp_39f7fbc23c_wc_booking_relationships: Data: 0.02MB + Index: 0.03MB
wp_39f7fbc23c_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_39f7fbc23c_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB
wp_39f7fbc23c_wc_webhooks: Data: 0.02MB + Index: 0.02MB

### Post Type Counts ###

attachment: 41
page: 2
post: 4
product: 39
product_variation: 55
scheduled-action: 1
shop_coupon: 1
shop_order: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (2) ###

WooCommerce Smooth Generator: by Automattic – 1.0.0 – Not tested with the active version of WooCommerce
WooCommerce: by Automattic – 3.6.4

### Inactive Plugins (5) ###

Code Snippets: by Shea Bunge – 2.13.3
Jetpack by WordPress.com: by Automattic – 7.3.1
Reset Database: by MalteseSolutions – 1.1.3
WooCommerce Bookings: by WooCommerce – 1.14.3
WooCommerce Bookings Events Block: by WooCommerce – 1.0.0-rc.1 – Not tested with the active version of WooCommerce

### Settings ###

API Enabled: –
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: ❌ Page not set
Cart: ❌ Page not set
Checkout: ❌ Page not set
My account: ❌ Page not set
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Nineteen
Version: 1.4
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 1
Oldest: 2019-05-30 06:35:43 +0000
Newest: 2019-05-30 06:35:43 +0000

Pending: 0
Oldest: –
Newest: –

Canceled: 0
Oldest: –
Newest: –

In-progress: 0
Oldest: –
Newest: –

Failed: 0
Oldest: –
Newest: –

`
```
</details>

### PR DESCRIPTION
**Pull request by ajayghaghretiya**
### All Submissions:

* [X] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [X] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [X] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes #23850 .

### How to test the changes in this Pull Request:

1 Create an order on wp-admin backend.
2 Set it to Pending payment or On hold status. The other statuses do not allow applying a coupon code. 
3 Create a coupon code with a percentage discount, say 10% off.
4 Open the On hold order.
5 Apply the coupon code.

It's working as expected now.

### Other information:

* [X] Have you added an explanation of what your changes do and why you'd like us to include them?
* [X] Have you written new tests for your changes, as applicable?
* [X] Have you successfully run tests with your changes locally?

### Changelog entry

> Fix - Fixed the usage limit issue when applying coupon for the order from admin panel.

### CODE REVIEW

File: includes/abstracts/abstract-wc-order.php [hunk 1]
```diff
@@ -969,7 +969,7 @@ public function apply_coupon( $raw_coupon ) {
 		if ( 0 === $this->get_customer_id() ) {
 			$data_store  = $coupon->get_data_store();
 			$usage_count = $data_store->get_usage_by_email( $coupon, $this->get_billing_email() );
-			if ( $usage_count >= $coupon->get_usage_limit_per_user() ) {
+			if ( !empty( $usage_count ) && $usage_count >= $coupon->get_usage_limit_per_user() ) {
```
Comment (claudiosanches) [inline includes/abstracts/abstract-wc-order.php]: Missing one space after `!`, just to fix all coding standards.
Thanks for your help!

**Review by claudiosanches — CHANGES_REQUESTED** [review]

File: includes/abstracts/abstract-wc-order.php (hunk 1 above)
Comment (ajayghaghretiya) [reply includes/abstracts/abstract-wc-order.php]: @claudiosanches Thanks for the review & suggestion.

File: includes/abstracts/abstract-wc-order.php [hunk 2]
```diff
@@ -969,7 +969,7 @@ public function apply_coupon( $raw_coupon ) {
 		if ( 0 === $this->get_customer_id() ) {
 			$data_store  = $coupon->get_data_store();
 			$usage_count = $data_store->get_usage_by_email( $coupon, $this->get_billing_email() );
-			if ( $usage_count >= $coupon->get_usage_limit_per_user() ) {
+			if ( ! empty( $usage_count ) && $usage_count >= $coupon->get_usage_limit_per_user() ) {
```
Comment (claudiosanches) [inline includes/abstracts/abstract-wc-order.php]: I just tested, checking for `! empty( $usage_count )` doesn't fix this problem, should works only for the first time for each email address, after will start showing the same message again, because we need to check for the setting and not how many times some user have used that coupon.
So in order to properly fix it, need to check if `$coupon->get_usage_limit_per_user()` is greater than `0`, see:

```php
if ( 0 < $coupon->get_usage_limit_per_user() && $usage_count >= $coupon->get_usage_limit_per_user() ) {
```

**Review by claudiosanches — CHANGES_REQUESTED** [review]

File: includes/abstracts/abstract-wc-order.php (hunk 2 above)
Comment (ajayghaghretiya) [reply includes/abstracts/abstract-wc-order.php]: Yeah. Make sense.

Comment (ajayghaghretiya) [reply includes/abstracts/abstract-wc-order.php]: Check it now and let me know if you need any help for this.

**Review by claudiosanches — APPROVED** [review]
Thanks for your help!

**Comment by claudiosanches** [comment]
cc @kloon

**Comment by aegrant00** [comment]
@claudiosanches  @ajayghaghretiya 

SO this commit DOES fix the problem with guest orders in admin panel allowing coupon codes... HOWEVER, we found it breaks several other things.

1) https://li.wordpress.org/plugins/wc-duplicate-order/ no longer works.  Now, this plugin has not been tested with the last 3 releases of WP/WC, so I am actively looking for a replacement.
2) All orders to https://woocommerce.com/products/shipstation-integration/ stopped being sent.  No idea WHY, this one file is all I replaced, but once I did so, shipstation stopped receiving orders.  As soon as I rolled back to the public release version of this file, shipstation started getting orders again.
3) Customers were somehow creating duplicate orders (in addition to their confirmed processing order).  

I will document all three of these better, but I wanted to let you know that although #23850 fixed the coupon issue, it created others.  Our site sees 600-800 orders per day, so it's a viable environment.  We have 3 platforms, test, staging, and production, and saw this clearly once we pushed this one file to production.

I was talking with @burlesonbrad about this, and we were shaking our heads.  If you need more info, or specifics, I can provide by DM.

**Comment by claudiosanches** [comment]
@aegrant00 sorry, but I can't reproduce any of the issues you reported, also what you reported doesn't sounds related to the changes proposed in here. Thanks anyway.

**Comment by ambisyoso901** [comment]
Hello, for some reason I have this issue in the latest version of Woocommerce.

Guest checkout can still used the code, even though they are already have made the purchase.

**Comment by jxh2** [comment]
I am seeing this in WC 5.5.2 / WP 5.7.2.

> Hello, for some reason I have this issue in the latest version of Woocommerce.
> 
> Guest checkout can still used the code, even though they are already have made the purchase.
