### PR TITLE
Fix broken product import file uploads on windows

### LINKED ISSUE #20268: Can’t Import Products Using CSV
**Can’t Import Products Using CSV**
When we try to import the CSV file we are geting the "Specified file failed upload test." massage and eds thare. 

**To Reproduce**
1. Go to 'Woocommerce All product'
2. Click on 'Import Button'
3. Choose a CSV file to be uploded 
4. Check Update existing products
5. Click on Continue. 

**Screenshots**

image

image

**WordPress Environment**
`
### WordPress Environment ###

Home URL: http://sa.myhommer.com
Site URL: http://sa.myhommer.com
WC Version: 3.4.0
Log Directory Writable: ✔
WP Version: 4.9.6
WP Multisite: ✔
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: Microsoft-IIS/10.0
PHP Version: 7.2.2
PHP Post Max Size: 32 MB
PHP Time Limit: 600
PHP Max Input Vars: 3000
cURL Version: 7.57.0
OpenSSL/1.1.0g

SUHOSIN Installed: –
MySQL Version: 8.0.11
Max Upload Size: 32 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

Contact Form 7: by Takayuki Miyoshi – 5.0.2
Elementor: by Elementor.com – 2.0.12
Ocean Extra: by OceanWP – 1.4.11
WooCommerce: by Automattic – 3.4.0
WordPress Importer: by wordpressdotorg – 0.6.4

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: SAR (SAR )
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### PR DESCRIPTION
**Pull request by kloon**
### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:
Use wc_clean and not wp_unslash when cleaning the filename and path before uploading. wp_unslash strips out windows path slashes.

Closes #20268.

### How to test the changes in this Pull Request:

1. On a Windows-based server go to Products -> All Products -> Import
2. Select the sample product file bundled with WooCommerce and click `Continue`
3. Next step should load without any issues

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

### Changelog entry

> Fix - Product imports on Windows-based servers.

### CODE REVIEW

File: includes/admin/importers/class-wc-product-csv-importer-controller.php [hunk 1]
```diff
@@ -295,7 +295,7 @@ public function handle_upload() {
 				'test_form' => false,
 				'mimes'     => $valid_filetypes,
 			);
-			$import    = wp_unslash( $_FILES['import'] ); // WPCS: sanitization ok.
+			$import    = wc_clean( $_FILES['import'] ); // WPCS: sanitization ok.
```
Comment (rodrigoprimo) [inline includes/admin/importers/class-wc-product-csv-importer-controller.php]: I don't think we need to call `wc_clean()` or `wp_unslash()` here. `wp_handle_upload()` since handles sanitizing file names:

https://github.com/WordPress/WordPress/blob/b4320bc/wp-admin/includes/file.php#L827
https://github.com/WordPress/WordPress/blob/fdd5b8d/wp-includes/functions.php#L2137

An example of an instance where WP core passes a file from `$_FILES` directly to `wp_handle_upload()`:

https://github.com/WordPress/WordPress/blob/fdd5b8dacdf5f3e107747e9870c2f2db3f3481b1/wp-admin/custom-background.php#L488

Am I missing something?

`wp_unslash()` was probably added by mistake during the PHPCS fixes effort mislead by this PHPCS message:

"Missing wp_unslash() before sanitization."

**Review by rodrigoprimo — DISMISSED** [review]

File: includes/admin/importers/class-wc-product-csv-importer-controller.php (hunk 1 above)
Comment (rodrigoprimo) [reply includes/admin/importers/class-wc-product-csv-importer-controller.php]: Just to elaborate a little bit more, I fear that `wc_clean()` might introduce other bugs similar to the one that `wp_unslash()` introduced while sanitizing `$_FILES['import']` so I suggest we keep it only if necessary which I don't think it is.

Comment (rodrigoprimo) [reply includes/admin/importers/class-wc-product-csv-importer-controller.php]: What I suggest is that you remove the line that declares `$import` and change the next line to:

```
$upload    = wp_handle_upload( $_FILES['import'], $overrides ); // phpcs:ignore WordPress.VIP.ValidatedSanitizedInput.MissingUnslash
```

**Review by mikejolley — CHANGES_REQUESTED** [review]
Docs here https://codex.wordpress.org/Function_Reference/wp_handle_upload say you should pass a variable rather than $_FILES directly?

**Review by mikejolley — APPROVED** [review]
