### PR TITLE
[HPOS/COT] Ensure date_creation_gmt is correctly populated with a GMT datetime

### LINKED ISSUE #34874: [COT/HPOS] When a new order is created, store the creation date in GMT
When the HPOS data-store is in use, a newly created order may be stored with the wrong creation date: this should be GMT, but it seems possible for it to be stored in whatever the WP timezone is.

### Steps to replicate

1. Enable COT/HPOS.
2. Via **Settings ▸ General** set your WP timezone to `America/Vancouver` or some other non-GMT timezone.
3. As a customer, create a new order.
4. As an admin user, promptly visit **WooCommerce ▸ Orders** and look at the new entry in the list table. In the date column, we could reasonably expect to see something like *"Created 10 seconds ago"* but in fact we will see a displacement such as *"Created 7 hours ago"* (if you were to select `America/Vancouver`, at least):

hpos-cot-order-date-created

6. Similarly, if you inspect the corresponding row of the `wp_wc_orders` table, you will see the entry in the `date_created_gmt` column is close to the current time as per the WP timezone setting.

### PR DESCRIPTION
**Pull request by barryhughes**
When the HPOS data-store is in use, a newly created order may be stored with the wrong creation date: this should be GMT, but it seems possible for it to be stored in whatever the WP timezone is.

### Steps to replicate

1. Enable COT/HPOS.
2. Via **Settings ▸ General** set your WP timezone to `America/Vancouver` or some other non-GMT timezone.
3. As a customer, create a new order.
4. As an admin user, promptly visit **WooCommerce ▸ Orders** and look at the new entry in the list table. In the date column, we could reasonably expect to see something like *"Created 10 seconds ago"* but in fact we will see a displacement such as *"Created 7 hours ago"* (if you were to select `America/Vancouver`, at least):

hpos-cot-order-date-created

6. Similarly, if you inspect the corresponding row of the `wp_wc_orders` table, you will see the entry in the `date_created_gmt` column is close to the current time as per the WP timezone setting.
With this branch checked out, however, the problem should not occur.

Closes #34874.

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

File: plugins/woocommerce/src/Internal/Utilities/DatabaseUtil.php [hunk 1]
```diff
@@ -157,10 +160,12 @@ public function format_object_value_for_db( $value, string $type ) {
 				$value = strval( $value );
 				break;
 			case 'date':
```
Comment (barryhughes) [inline plugins/woocommerce/src/Internal/Utilities/DatabaseUtil.php:162]: I wondered if it might be better to keep this clause (for the `'date'` type) as it is, and instead add a new clause for new type `'date_gmt'` (then update the relevant column mappings). 

Since this only seems to be used in relation to COT/HPOS, though, and since all the relevant date columns in our COT tables are GMT, I decided changing the way `'date'` works would be cleaner.

**Comment by barryhughes** [comment]
✍🏽 E2E fails seem unrelated, and are not unique to this PR. Some work is in progress to figure that out. Internal link: p1664395739215099/1664377590.875839-slack-C01BWDDTGKX

File: plugins/woocommerce/src/Internal/Utilities/DatabaseUtil.php (hunk 1 above)
Comment (peterfabian) [reply plugins/woocommerce/src/Internal/Utilities/DatabaseUtil.php:162]: I think `date_gmt` is better. Explicit is always better than implicit and since WP has both local and GMT dates, it can easily lead to confusion. That said, it's a minor problem in the context of this PR.

**Review by peterfabian — APPROVED** [review]
This fixes the GMT timestamp problems for me, so approving. Tested it together with #35033
