### PR TITLE
Fix duplicate task list shown in some occurrences

### LINKED ISSUE #32896: [GlobalStep] "Setup Check List" appears twice after clicking the "Finish Setup" menu on "Analytics > Overview" page.
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

"Setup Check List" appears twice after clicking the "Finish Setup" menu on "Analytics > Overview" page.

### Expected behavior

"Setup Check List" should appear once after clicking the "Finish Setup" menu on "Analytics > Overview" page.

### Actual behavior

"Setup Check List" appears twice after clicking the "Finish Setup" menu on "Analytics > Overview" page.

### Steps to reproduce

1. Create any test site using JN site.
2. Install and activate WooCommerce 6.5.0-rc2.
3. Click on the "Analytics > Overview" page.
4. Click on the "Finish Setup" menu.
5. Observe that  "Setup Check List" appears twice after clicking the "Finish Setup" menu on "Analytics > Overview" page.

### Note:
1. Also observed on the all the pages of  "Analytics" panel.
2. Also observed on the "Orders", "Customers", "Coupons", "Report", "Settings", "Status", "Extensions" page of "WooCommerce" pages.

### Video:

https://user-images.githubusercontent.com/41110392/167159006-ab7bb7d3-9d5b-4915-87a9-3ba05827c979.mp4

### WordPress Environment

Woocommerce Version: 
WooCommerce: 6.5.0-rc2
Wordpress version: 5.9.3

PC:
Windows 10
Chrome(Version 101.0.4951.54) 
Firefox(Version 100.0)

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

<details>

`
### WordPress Environment ###

WC Version: 6.5.0
REST API Version: ✔ 6.5.0
WC Blocks Version: ✔ 7.4.3
Action Scheduler Version: ✔ 3.4.0
Log Directory Writable: ✔
WP Version: 5.9.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.53 (Unix) OpenSSL/1.0.2g
PHP Version: 7.4.29
PHP Post Max Size: 1 GB
PHP Time Limit: 30
PHP Max Input Vars: 5000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.7.33-0ubuntu0.16.04.1-log
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 6.5.0
WC Database Prefix: wp_
Total Database Size: 15.28MB
Database Data Size: 12.28MB
Database Index Size: 3.00MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.09MB + Index: 0.09MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.06MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_gla_budget_recommendations: Data: 0.22MB + Index: 0.14MB + Engine InnoDB
wp_gla_merchant_issues: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gla_shipping_rates: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_gla_shipping_times: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_custom_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_dynamic_segment_filters: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_feature_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_forms: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_mapping_to_external_entities: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletters: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_newsletter_links: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_newsletter_option: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_option_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_posts: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_segment: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_templates: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_scheduled_tasks: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_scheduled_task_subscribers: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_segments: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_sending_queues: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_settings: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_statistics_bounces: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_statistics_clicks: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_statistics_forms: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_statistics_newsletters: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_statistics_opens: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_mailpoet_statistics_unsubscribes: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_statistics_woocommerce_purchases: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_mailpoet_stats_notifications: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_subscribers: Data: 0.02MB + Index: 0.13MB + Engine InnoDB
wp_mailpoet_subscriber_custom_field: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_subscriber_ips: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_subscriber_segment: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_user_agents: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_user_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 6.03MB + Index: 0.25MB + Engine InnoDB
wp_postmeta: Data: 0.20MB + Index: 0.17MB + Engine InnoDB
wp_posts: Data: 0.08MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wpml_mails: Data: 1.52MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

attachment: 29
mailpoet_page: 1
page: 7
post: 2
product: 20
product_variation: 7
shop_coupon: 1
shop_order: 27

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (3) ###

Query Monitor: by John Blackbourn – 3.9.0
Companion Plugin: by Osk – 1.25
WooCommerce: by Automattic – 6.5.0-rc.2

### Inactive Plugins (6) ###

Akismet Anti-Spam: by Automattic – 4.2.3
Gutenberg: by Gutenberg Team – 13.1.0
Hello Dolly: by Matt Mullenweg – 1.7.2
Jetpack: by Automattic – 10.9
WP Crontrol: by John Blackbourn & crontributors – 1.12.1
WP Mail Logging: by Wysija – 1.10.4

### Dropin Plugins (1) ###

db.php: Query Monitor Database Class (Drop-in)

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔

### WC Pages ###

Shop base: #7 - /shop/
Cart: #8 - /cart/
Checkout: #9 - /checkout/
My account: #10 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 4.1.0
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 115
Oldest: 2022-05-04 06:38:01 +0000
Newest: 2022-05-06 13:00:37 +0000

### Status report information ###

Generated at: 2022-05-06 14:59:14 +00:00
`

</details>

### PR DESCRIPTION
**Pull request by louwie17**
### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes #32896 

Made two changes, one fix is in the activity panel with the check if the Task list is hidden, checking if it is set to `false` which is the new default.
Secondly the success actions for hide and unhide task lists weren't passing the `taskListId` to the reducer, causing an `undefined` task list and hence an extra task list showing up.

### How to test the changes in this Pull Request:

1. Load `trunk` first and finish the onboarding wizard
2. Go to **WooCommerce > Home** (one task list should show) and navigate to **WooCommerce > Analytics > Overview**
3. Notice the **Finish setup** button in the top right, open your console to monitor network requests, and click the Finish setup button (it should redirect home)
4. Notice how a second task list shows up and a request has been made to `/onboarding/tasks/<task list id>/unhide`
5. Now load this branch and refresh the home screen
6. Follow steps 2-4 again, this time it should not have made a request to `unhide` and a second task list should not be shown.
7. Try hiding the task list and see if that works correctly.

### Other information:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully run tests with your changes locally?
* [ ] Have you created a changelog file by running `pnpm nx affected --target=changelog`?

### FOR PR REVIEWER ONLY:

* [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

File: plugins/woocommerce-admin/client/activity-panel/activity-panel.js [hunk 1]
```diff
@@ -246,7 +246,10 @@ export const ActivityPanel = ( { isEmbedded, query } ) => {
 				if ( currentLocation !== homescreenLocation ) {
 					// Ensure that if the user is trying to get to the task list they can see it even if
 					// it was dismissed.
-					if ( setupTaskListHidden === 'no' ) {
+					if (
+						setupTaskListHidden === 'no' ||
+						setupTaskListHidden === false
```
Comment (joshuatf) [inline plugins/woocommerce-admin/client/activity-panel/activity-panel.js]: Can this second condition be met?  This item should not be visible given the check for `setupTaskListHidden` below in visibility.

I think there are two issues happening here:
1.  We have more "setup" task lists now than when we started and this logic is slightly dated.
2. We're treating `setupTaskListHidden` as a boolean in some cases and as a string in others.  I'm pretty sure it's a boolean and we should not be comparing it to a string.

File: packages/js/data/src/onboarding/actions.js [hunk 2]
```diff
@@ -169,6 +169,7 @@ export function hideTaskListSuccess( taskList ) {
 	return {
 		type: TYPES.HIDE_TASK_LIST_SUCCESS,
 		taskList,
+		taskListId: taskList.id,
```
Comment (joshuatf) [inline packages/js/data/src/onboarding/actions.js:172]: Nice fix!

File: plugins/woocommerce-admin/client/activity-panel/activity-panel.js (hunk 1 above)
Comment (louwie17) [reply plugins/woocommerce-admin/client/activity-panel/activity-panel.js]: > We have more "setup" task lists now than when we started and this logic is slightly dated.

Yeah, kinda confusing in relation to the experimental task lists, in this case that part doesn't matter as the hide/show setting is the same for all 4? of them.
In theory we might want some thing more like `getActiveSetupTaskList` instead of passing in the `setup` id every where, but that should not be done as part of this fix.

**Review by joshuatf — DISMISSED** [review]
Changes look good and are testing well.

One slightly related issue is that the "Finish setup" button continues to show for both new task list experiments since they have different IDs.

I think we can tackle either here or in a separate issue if that makes things easier.

**Review by joshuatf — APPROVED** [review]
Rollback looks good 👍
