### PR TITLE
Cache bust resource hints transient when site URL changes

### LINKED ISSUE #59049: _site_transient_woocommerce_block_asset_resource_hints may contain incorrect paths
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

In the latest version of WooCommerce, when I clone a site to another domain, the new site’s frontend still references URLs from the original site. This usually appears as:

```html
<link href='https://a.com/wp-content/plugins/woocommerce/assets/client/blocks/cart-frontend.js?ver=4e031729927ec3a04970' as='script' rel='prefetch'/>
<link href='https://a.com/wp-content/plugins/woocommerce/assets/client/blocks/wc-cart-checkout-base-frontend.js?ver=7d01b022a3ccdebeef08' as='script' rel='prefetch'/>
<link href='https://a.com/wp-includes/js/dist/vendor/wp-polyfill.min.js?ver=3.15.0' as='script' rel='prefetch'/>
<link href='https://a.com/wp-includes/js/dist/i18n.min.js?ver=5e580eb46a90c2b997e6' as='script' rel='prefetch'/>
<link href='https://a.com/wp-includes/js/dist/hooks.min.js?ver=4d63a3d491d11ffd8ac6' as='script' rel='prefetch'/>
```

Later, I found that these URLs are stored in the database under the key:
_site_transient_woocommerce_block_asset_resource_hints

This value does not store relative paths, but rather full absolute URLs.

### Expected behavior

dependent on the WordPress installation path.

### Actual behavior

not dependent on the WordPress installation path.

### Steps to reproduce

Copy the site to a new domain.

Visit the new domain and inspect the page source.

### WordPress Environment

<details>

<summary>WordPress Environment</summary>

The System Status Report is found in your WordPress admin under **WooCommerce > Status**. 
Please select “Get system report”, then “Copy for GitHub”, and then paste it here.

</details>

### Isolating the problem

- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by joshuatf**
### Changes proposed in this Pull Request:

When sites change their base URL, there is a small window where the cached resource hint URLs for the site may be different than those from the actual site.

This PR adds cache busting by verifying that the site URL has not changed.

Closes #59049 .

(For Bug Fixes) Bug introduced in PR # .

### How to test the changes in this Pull Request:

1. Add a product to your cart
2. Visit the cart page on the frontend of your site
3. Using your favorite DB tool, check the value of the `_site_transient_woocommerce_block_asset_resource_hints` transient in the `wp_options` table
4. Note that the URLs include the current site URL
5. Update the current site URL by defining `WP_SITEURL` and `WP_HOME` in your `wp-config.php` and make any changes necessary to your hosting configuration to reflect the new site URL
6. Visit the cart page again
7. Using your favorite DB tool, check the value of the `_site_transient_woocommerce_block_asset_resource_hints` transient in the `wp_options` table
8. Note that the URLs include the updated site URL and not the previous site URL

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce/src/Blocks/AssetsController.php [hunk 1]
```diff
@@ -288,6 +289,7 @@ private function set_block_asset_resource_hints_cache( $filename, $data ) {
 			'version' => array(
 				'woocommerce' => WOOCOMMERCE_VERSION,
 				'wordpress'   => get_bloginfo( 'version' ),
+				'site_url'    => wp_guess_url(),
```
Comment (kalessil) [inline plugins/woocommerce/src/Blocks/AssetsController.php:292]: Makes sense to actualize the tests for this class.

**Review by kalessil — APPROVED** [review]
LGTM and works as described!

Leaving a nudge to add a new test case and pre-approving.

File: plugins/woocommerce/src/Blocks/AssetsController.php (hunk 1 above)
Comment (joshuatf) [reply plugins/woocommerce/src/Blocks/AssetsController.php:292]: Good call!  Updated in https://github.com/woocommerce/woocommerce/pull/59342/commits/297d91ee2eebf9cf6972c70e750c48b047ce6931 if you want to take a look.

Comment (kalessil) [reply plugins/woocommerce/src/Blocks/AssetsController.php:292]: Looks good, thanks!
