### PR TITLE
Fix fatal error in order reports when parent order doesn't exist for a refund. 

### LINKED ISSUE #32202: Displaying 100 rows of orders returns error 500, fatals
### Describe the bug

If you navigate to **Analytics > Orders** and change the `Rows Per Page` to `100`, the following error occurs on the page:

```
There was an error getting your stats. Please try again.
```

Additionally, a fatal error occurs:

```
2022-01-02T16:22:13+00:00 CRITICAL Uncaught Error: Call to a member function get_id() on bool in /Users/chris/Local Sites/woosites/cm/app/public/wp-content/plugins/woocommerce/packages/woocommerce-admin/src/API/Reports/Controller.php:202
Stack trace:
#0 /Users/chris/Local Sites/woosites/cm/app/public/wp-content/plugins/woocommerce/packages/woocommerce-admin/src/API/Reports/Orders/Controller.php(86): Automattic\WooCommerce\Admin\API\Reports\Controller->get_order_number(8640)
woocommerce/woocommerce-admin#1 /Users/chris/Local Sites/woosites/cm/app/public/wp-includes/rest-api/class-wp-rest-server.php(1140): Automattic\WooCommerce\Admin\API\Reports\Orders\Controller->get_items(Object(WP_REST_Request))
woocommerce/woocommerce-admin#2 /Users/chris/Local Sites/woosites/cm/app/public/wp-includes/rest-api/class-wp-rest-server.php(987): WP_REST_Server->respond_to_request(Object(WP_REST_Request), '/wc-analytics/r...', Array, NULL)
woocommerce/woocommerce-admin#3 /Users/chris/Local Sites/woosites/cm/app/public/wp-includes/rest-api/class-wp-rest-server.php(414): WP_REST_Server->dispatch(Object(WP_REST_Request))
woocommerce/woocommerce-admin#4 /Users/chris/Local Sites/wo in /Users/chris/Local Sites/woosites/cm/app/public/wp-content/plugins/woocommerce/packages/woocommerce-admin/src/API/Reports/Controller.php on line 202
```

Lastly, the following console error appears:

```
Failed to load resource: the server responded with a status of 500 (Internal Server Error)
```

### To Reproduce

1. Go to **Analytics**.
2. Go to **Orders**.
3. Modify the dates to get a large number of orders.
4. The `Rows Per Page` field defaults to `25`. Change the `Rows Per Page` field to `100`.
5. Notice the server answers with Error 500, an error occurs on the page, and a fatal error log is generated.

### Actual behavior:

The server answers with Error 500, an error occurs on the page, and a fatal error log is generated.

### Screenshots

Markup on 2022-01-02 at 10:29:58

Markup on 2022-01-02 at 10:30:19

### Expected behavior

Reports should display without an error.

### Desktop (please complete the following information):

* OS: macOS 12.1
* Browser: Chrome
* Version: 96.0.4664.110

### Additional context

May be similar to woocommerce/woocommerce-admin#1948
Reported in 4648836-zen

### System Status Report

<details>
`
### WordPress Environment ###

WordPress address (URL): http://cm.local
Site address (URL): http://cm.local
WC Version: 6.0.0
REST API Version: ✔ 6.0.0
WC Blocks Version: ✔ 6.3.3
Action Scheduler Version: ✔ 3.3.0
WC Admin Version: ✔ 2.9.4
Log Directory Writable: ✔
WP Version: 5.8.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.16.0
PHP Version: 7.4.1
PHP Post Max Size: 1,000 MB
PHP Time Limit: 1200
PHP Max Input Vars: 4000
cURL Version: 7.54.0
LibreSSL/2.6.5

SUHOSIN Installed: –
MySQL Version: 8.0.16
Max Upload Size: 300 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 5.9.0
WC Database Prefix: wp_
Total Database Size: 30.58MB
Database Data Size: 22.50MB
Database Index Size: 8.08MB
wp_woocommerce_sessions: Data: 0.34MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.17MB + Index: 0.16MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.28MB + Index: 0.25MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.19MB + Index: 0.16MB + Engine InnoDB
wp_automatewoo_abandoned_carts: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_automatewoo_customer_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_customers: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_automatewoo_events: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_guest_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_guests: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_automatewoo_log_meta: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_queue: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_queue_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.11MB + Index: 0.09MB + Engine InnoDB
wp_email_log: Data: 3.52MB + Index: 0.00MB + Engine InnoDB
wp_followup_coupon_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_coupons: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_customer_carts: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_customer_notes: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_customer_orders: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_followup_customers: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_followup_email_excludes: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_email_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_email_orders: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_followup_email_tracking: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_followup_followup_history: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_order_categories: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_order_items: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_subscriber_lists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_subscribers: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_subscribers_to_lists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gla_budget_recommendations: Data: 0.22MB + Index: 0.14MB + Engine InnoDB
wp_gla_merchant_issues: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gla_shipping_rates: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gla_shipping_times: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 12.05MB + Index: 0.09MB + Engine InnoDB
wp_postmeta: Data: 2.13MB + Index: 4.03MB + Engine InnoDB
wp_posts: Data: 1.52MB + Index: 0.33MB + Engine InnoDB
wp_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_term_relationships: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wc_booking_relationships: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_bookings_availability: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_bookings_availabilitymeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_deposits_payment_plans: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_deposits_payment_plans_schedule: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_bundle_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.13MB + Index: 0.17MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_warranty_products: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wcpv_commissions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcpv_per_product_shipping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_bundled_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_bundled_items: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_exported_csv_items: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_gc_activity: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_gc_cards: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_gc_cardsmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_table_rates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_software_activations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_software_licenses: Data: 0.02MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

attachment: 170
aw_workflow: 6
custom_css: 1
event_ticket: 7
event_ticket_email: 1
follow_up_email: 1
global_product_addon: 2
page: 19
post: 4
product: 111
product_variation: 959
revision: 34
shop_coupon: 6
shop_order: 93
shop_order_refund: 9
shop_subscription: 14
warranty_request: 1
wc_booking: 4
wcpf_item: 5
wcpf_project: 2

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (2) ###

Meks Quick Plugin Disabler: by Meks – 1.0
WooCommerce: by Automattic – 6.0.0

### Inactive Plugins (13) ###

AutomateWoo: by WooCommerce – 5.5.6
Code Snippets: by Code Snippets Pro – 2.14.2
Email Log: by Sudar – 2.4.8
Product Filters for WooCommerce: by WooCommerce – 1.2.5 (update to version 1.2.7 is available)
Variation Shared Inventory for WooCommerce: by Webis – 3.4.1
WooCommerce Bulk Stock Management: by WooCommerce – 2.2.31
WooCommerce Deposits: by WooCommerce – 1.5.7
WooCommerce Gift Cards: by SomewhereWarm – 1.9.3 (update to version 1.9.5 is available)
WooCommerce Product Add-ons: by WooCommerce – 4.4.0
WooCommerce Product Bundles: by SomewhereWarm – 6.12.7 (update to version 6.13.2 is available)
WooCommerce Stripe Gateway: by WooCommerce – 5.9.0
WooCommerce Subscriptions: by WooCommerce – 3.1.6
WooCommerce USPS Shipping: by WooCommerce – 4.4.67 (update to version 4.4.68 is available)

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: booking (booking)
bundle (bundle)
external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude_from_catalog (exclude_from_catalog)
exclude_from_search (exclude_from_search)
exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)
visible (visible)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: woocommerce/woocommerce-admin#6 - /shop/
Cart: woocommerce/woocommerce-admin#7 - /cart/
Checkout: woocommerce/woocommerce-admin#8 - /checkout/
My account: woocommerce/woocommerce-admin#9 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 3.9.1
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 644
Oldest: 2021-12-08 17:46:52 +0000
Newest: 2022-01-02 16:25:30 +0000

Pending: 12
Oldest: 2022-01-02 16:59:19 +0000
Newest: 2022-01-20 17:12:29 +0000

### Status report information ###

Generated at: 2022-01-02 16:32:28 +00:00
`
</details>

### PR DESCRIPTION
**Pull request by jorgemd24**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes https://github.com/woocommerce/woocommerce/issues/32202

This PR addresses the issue of retrieving order reports for orphaned refunds (refunds with non-existent parent orders). See this comment for more details: https://github.com/woocommerce/woocommerce/issues/32202#issuecomment-1072895998.

Generally, this scenario shouldn't occur because using `$order->delete()` will trash the `order` and the `refund` and `wp_delete_post($order->get_id())` will prevent it from becoming orphaned because of this filter: [maybe_prevent_deletion_of_post](https://github.com/woocommerce/woocommerce/blob/97a0d9b16006b089f7d1e98af19d61f6d71b621b/plugins/woocommerce/src/Internal/DataStores/Orders/DataSynchronizer.php#L916) . However, if an order is manually deleted from the database or the parent ID of a refund is updated to a non-existent order ID:

```
		wp_update_post(
			array(
				'ID'          => $refund->get_id(),
				'post_parent' => '99999999', <- Doesn't exist
			)
		);
```

The following endpoint will throw a fatal error: `GET wp-json/wc-analytics/reports/orders`, resulting in `Call to a member function get_id() on bool` as mentioned in the issue.

This PR adds a check to ensure that the parent order ID exists before proceeding. If it does not exist, the function will return `null`, which is the same value that was previously returned if the order was not found.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Create an order.
2. Create a refund for that order.
3. Get the ID of the refund created.

image

4. Run `wp shell ` -> `wp_update_post( array( 'ID'  => YOUR_REFUND_ID, 'post_parent' => '99999999', ) );`
5. Go to Analytics -> Orders -> Select a Range that includes that order and the refund that you created.
6. See that the report is loaded correctly. If you checkout `trunk` you will see that you get a fatal error.
7. As the refund does not have a valid parent order, it will show as empty the field of `Order #`:

image

### Changelog entry

-   [X] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [X] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [X] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

Fix fatal error in order reports when parent order doesn't exist

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce/src/Admin/API/Reports/Controller.php [hunk 1]
```diff
@@ -151,6 +151,11 @@ protected function get_order_number( $order_id ) {
 
 		if ( 'shop_order_refund' === $order->get_type() ) {
 			$order = wc_get_order( $order->get_parent_id() );
+
+			// If the parent order doesn't exist, return null.
+			if ( ! $order instanceof \WC_Order && ! $order instanceof \WC_Order_Refund ) {
```
Comment (ianlin) [inline plugins/woocommerce/src/Admin/API/Reports/Controller.php]: It might be better to wrap this check into a method as it has been used four times in this code.

**Review by ianlin — APPROVED** [review]
Thanks for the fix. Tested locally and confirmed the error was no longer appear, and the order reports data were displayed correctly. Just a minor suggestion that wouldn't block this PR.

File: plugins/woocommerce/src/Admin/API/Reports/Controller.php (hunk 1 above)
Comment (jorgemd24) [reply plugins/woocommerce/src/Admin/API/Reports/Controller.php]: Thanks done here: [b93e55e](https://github.com/woocommerce/woocommerce/pull/49006/commits/b93e55eef5a9c3f3df88181b79013a2874d58472)
