### PR TITLE
Fix attribute apostrophe saving, and usage in variations

### LINKED ISSUE #22147: Can't save variations from attributes that have an apostrophe
**Describe the bug**

After saving an attribute that contains an apostrophe, this attribute cannot be used in variations.

**To Reproduce**
1. Create an attribute that contains an apostrophe (e.g. `Test's`)
2. Select to use this attribute for variations, and save it.
3. Go to the Variations tab, and choose to create variations from all attributes.
4. Save changes.

**Screenshots**

First, when saving an attribute with an apostrophe, the name is changed to include a `\`. For example, this was originally entered as `Test's`, but it saved as `Test\'s`:

Image Link: http://cld.wthms.co/r89kg7

Then, when trying to create variations for my attributes, all the variations are initially created correctly:

Image Link: http://cld.wthms.co/DYauKh

But once I click on `Save changes`, that variation is changed to this:

Image Link: http://cld.wthms.co/4Ls53r

If I try to change it again, it doesn't save:

Image Link: http://cld.wthms.co/jiClMi

**Expected behavior**
To be able to use an attribute for variations, regardless of whether it contains an apostrophe or not.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
### WordPress Environment ###

Home URL: https://fernando.mystagingwebsite.com
Site URL: https://fernando.mystagingwebsite.com
WC Version: 3.5.2
Log Directory Writable: ✔
WP Version: 4.9.8
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 7.0.32 - We recommend using PHP version 7.2 or above for greater performance and security. How to update your PHP version
PHP Post Max Size: 100 MB
PHP Time Limit: 300
PHP Max Input Vars: 6144
cURL Version: 7.61.1
OpenSSL/1.0.1t

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.1.17-MariaDB
Max Upload Size: 100 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.5.2
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Total Database Size: 47.17MB
Database Data Size: 43.64MB
Database Index Size: 3.53MB
wp_woocommerce_sessions: Data: 14.02MB + Index: 0.44MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_order_itemmeta: Data: 0.11MB + Index: 0.09MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_advanced_notifications: Data: 0.02MB + Index: 0.00MB
wp_advanced_notification_triggers: Data: 0.02MB + Index: 0.00MB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_comments: Data: 0.08MB + Index: 0.09MB
wp_followup_coupons: Data: 0.02MB + Index: 0.03MB
wp_followup_coupon_logs: Data: 0.02MB + Index: 0.05MB
wp_followup_customers: Data: 0.02MB + Index: 0.06MB
wp_followup_customer_carts: Data: 0.02MB + Index: 0.03MB
wp_followup_customer_notes: Data: 0.02MB + Index: 0.03MB
wp_followup_customer_orders: Data: 0.02MB + Index: 0.02MB
wp_followup_email_excludes: Data: 0.02MB + Index: 0.05MB
wp_followup_email_logs: Data: 0.02MB + Index: 0.05MB
wp_followup_email_orders: Data: 0.16MB + Index: 0.09MB
wp_followup_email_tracking: Data: 0.02MB + Index: 0.08MB
wp_followup_followup_history: Data: 0.02MB + Index: 0.05MB
wp_followup_order_categories: Data: 0.02MB + Index: 0.03MB
wp_followup_order_items: Data: 0.02MB + Index: 0.05MB
wp_followup_subscribers: Data: 0.02MB + Index: 0.03MB
wp_followup_subscribers_to_lists: Data: 0.02MB + Index: 0.03MB
wp_followup_subscriber_lists: Data: 0.02MB + Index: 0.03MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_options: Data: 26.16MB + Index: 0.44MB
wp_postmeta: Data: 1.50MB + Index: 0.78MB
wp_posts: Data: 0.48MB + Index: 0.14MB
wp_termmeta: Data: 0.02MB + Index: 0.03MB
wp_terms: Data: 0.02MB + Index: 0.03MB
wp_term_relationships: Data: 0.05MB + Index: 0.02MB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wp_usermeta: Data: 0.06MB + Index: 0.03MB
wp_users: Data: 0.02MB + Index: 0.05MB
wp_wc_booking_relationships: Data: 0.02MB + Index: 0.03MB
wp_wc_deposits_payment_plans: Data: 0.02MB + Index: 0.00MB
wp_wc_deposits_payment_plans_schedule: Data: 0.02MB + Index: 0.02MB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_wc_points_rewards_user_points: Data: 0.02MB + Index: 0.03MB
wp_wc_points_rewards_user_points_log: Data: 0.02MB + Index: 0.05MB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_bundled_itemmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_bundled_items: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_per_product_shipping_rules: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_pickup_locations_geodata: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_shipping_table_rates: Data: 0.02MB + Index: 0.00MB
wp_wpml_mails: Data: 0.08MB + Index: 0.00MB

### Post Type Counts ###

attachment: 49
customize_changeset: 4
follow_up_email: 1
jetpack_migration: 2
jp_img_sitemap: 3
jp_sitemap: 3
jp_sitemap_master: 3
order_shipment: 2
page: 15
post: 2
product: 54
product_variation: 54
revision: 16
scheduled-action: 147
shipping_package: 2
shop_coupon: 6
shop_order: 62
shop_order_refund: 1
wc_order_status: 12

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (2) ###

Jetpack by WordPress.com: by Automattic – 6.8-pressable
WooCommerce: by Automattic – 3.5.2

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: bundle (bundle)
external (external)
grouped (grouped)
mix and match (mix-and-match)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: #3 - /shop/
Cart: #4 - /cart/
Checkout: #5 - /checkout/
My account: #6 - /my-account/
Terms and conditions: #292 - /terms/

### Theme ###

Name: Storefront
Version: 2.3.5
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –
```
</details>

### PR DESCRIPTION
**Pull request by mikejolley**
Supercedes #22361 
Closes #22147

Found out that the quotes needed `wp_unslash` when posted, and also to preserve slashes, `wp_slash` was needed on the meta value [because of this behaviour in WordPress core](https://codex.wordpress.org/Function_Reference/update_post_meta#Workaround).

After getting an attribute and value saving called `test'ing"\s` I found that there was a related issue on the frontend variation form whereby the values were not shown in the attribute dropdown. This appears to be due to trying to match an escaped version of that string to the actual value (the attribute dropdown uses `esc_attr` which turns `"` to `&quot` etc).

To fix this I had to remove the value matcher and use a loop instead so text versions are compared (without entities). This is now also fixed.

## How to test the changes in this Pull Request:

1. Add `\,",',+` to an attribute value list and save.
2. The list should display the values saved.
3. Refreshing the page, the value should remain.
4. Adding the attribute value to a variation should save.
5. Frontend form should allow you to add that new variation to the cart.

Thanks @rrennick for working on this prior.

> Fix: allow apostrophes in product attribute values list to save, and be used by variations.

Propose punting this to 3.6.0 for more testing since it was a little more in-depth than hoped. Should also run through automated tests.

### CODE REVIEW

File: assets/js/frontend/add-to-cart-variation.js [hunk 1]
```diff
@@ -371,8 +379,21 @@
...
 
 			// Check if current selection is in attached options.
-			if ( selected_attr_val && ( attached_options_count === 0 || new_attr_select.find( 'option.attached.enabled[value="' + form.addSlashes( selected_attr_val ) + '"]' ).length === 0 ) ) {
-				selected_attr_val_valid = false;
+			if ( selected_attr_val ) {
+				if ( 0 === attached_options_count ) {
+					selected_attr_val_valid = false;
+				} else {
+					selected_attr_val_valid = false;
+
```
Comment (claudiulodro) [inline assets/js/frontend/add-to-cart-variation.js]: This logic can probably be simplified:

```
selected_attr_val_valid = false;
if ( 0 !== attached_options_count ) {
    new_attr_select.find( 'option.attached.enabled' ).each( function( index, el ) {
		...
}
```

**Review by claudiulodro — APPROVED** [review]
This solves the issue, tests pass, and code looks reasonable. Just one area where code could be simplified, but it's not a blocker for merging this.

**Comment by lkraav** [comment]
Unfortunately, this strategy seems to have produced a show-stopping effect on https://github.com/woocommerce/woocommerce/issues/12929

Specifically, `break`-ing in this loop eliminates my ability to render multiple options within the same attribute scope, but with different variations.

https://github.com/woocommerce/woocommerce/blob/4.1.1/assets/js/frontend/add-to-cart-variation.js#L377-L380

Now only the first found attribute is displayed.

Any ideas how to get this simple variation list to render?

```html
```html
<select id="pa_asukoht" name="attribute_pa_asukoht" data-attribute_name="attribute_pa_asukoht">
    <option value="">Choose an option…</option>
    <option value="1101-3" data-variation-id="10804" class="attached enabled">2019, Mar 11 — Tallinn</option>
    <option value="1101-3" data-variation-id="10803" class="attached enabled">2019, Apr 29 — Tallinn</option>
    <option value="1101-3" data-variation-id="4516" class="attached enabled">2019, May 6 — Tallinn</option>
</select>
```

PS trying to work with add-to-cart-variation.js seems to be prohibitively hard at the moment:

* very complex loops
* near-zero inline documentation for reasoning throughout
* not sure I'm equipped to refactor any of it.. too much going on

Curious about the outlook here, does any core dev have bright ideas on how to break it up into more manageable pieces without breaking variable product pages all over?
