### PR TITLE
Cart Data Store: Prevent unnecessary requests to cart API when cart is empty (for the mini cart block)

### LINKED ISSUE #50793: Mini Cart always trigger a request to Store API's Cart even if its' empty
On a default, new guest session, Mini Cart will always trigger request to `store/cart`, even if the session is new and has nothing, this happens on multiple refreshes and cache in local storage doesn't matter.

### Steps to reproduce

1. On a guest session, go to a page with mini cart.
2. Notice a request to store/cart in network.
3. Remove Mini Cart.
4. Notice that the request is now gone.

I tried with a combo of settings for mini cart and they all produced the request regardless.

### Expected Behavior

There should be no request on page load, on each page, for guest sessions at least.

### Current behavior

A request is always made.

### PR DESCRIPTION
**Pull request by mikejolley**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

This is an updated approach to prevent API requests on load when using the mini-cart block. This supersedes #51981 

1. Removes the mini cart specific caching (local storage) and update logic
2. Makes the mini cart use the cart data store
3. Adds persistent caching to cart data store
4. Resolves early without an API request if the cart is empty (no cookie) or the local storage contains the current cart which matches the current cookie. Otherwise fires an API request as normal.

This should mitigate page caching issues with stale data without the extra request to the server when its not needed.

Closes #50793
Closes #51981

### How to test the changes in this Pull Request:

1. Add the Mini Cart Block to a page.
2. Ensure it renders the correct quantity in cart on page load. Add some items to the cart to test this.
3. With a new session and empty cart, view the page with the browser network inspector open. Ensure no XHR requests are made.
4. Add `?add-to-cart=16` (use a valid product ID) to the URL. Ensure mini cart is updated.
5. Open the shop page on another tab and add something to the cart. Refresh mini cart. It updates.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce/tests/php/src/Blocks/BlockTypes/MiniCart.php [hunk 1]
```diff
@@ -55,7 +55,7 @@ public function test_product_count_visibility_with_empty_cart() {
 		// Tests badge is not shown, because product count is not greater than zero when "greater_than_zero" is selected.
 		$block  = parse_blocks( '<!-- wp:woocommerce/mini-cart {"productCountVisibility":"greater_than_zero"} /-->' );
 		$output = render_block( $block[0] );
-		$this->assertStringNotContainsString( '<span class="wc-block-mini-cart__badge"', $output );
+		$this->assertStringContainsString( '<span class="wc-block-mini-cart__badge"', $output );
```
Comment (mikejolley) [inline plugins/woocommerce/tests/php/src/Blocks/BlockTypes/MiniCart.php:58]: I changed this behaviour in the PR to hide empty badge with CSS so the initial state from local storage has an element to render into if the page is cached.

File: plugins/woocommerce-blocks/assets/js/base/context/providers/add-to-cart-form/form/submit/index.js [hunk 2]
```diff
@@ -87,6 +87,9 @@ const FormSubmit = () => {
 				// Update nonce.
 				triggerFetch.setNonce( fetchResponse.headers );
 
+				// Update cart hash.
+				triggerFetch.setCartHash( fetchResponse.headers );
```
Comment (mikejolley) [inline plugins/woocommerce-blocks/assets/js/base/context/providers/add-to-cart-form/form/submit/index.js:91]: This implementation mimics the nonces and uses a similar middleware.

File: plugins/woocommerce-blocks/assets/js/blocks/mini-cart/block.tsx [hunk 3]
```diff
@@ -76,24 +76,6 @@ const MiniCartBlock = ( attributes: Props ): JSX.Element => {
 		}
 	}, [ cartIsLoading, cartIsLoadingForTheFirstTime ] );
 
-	useEffect( () => {
```
Comment (mikejolley) [inline plugins/woocommerce-blocks/assets/js/blocks/mini-cart/block.tsx:79]: I removed this effect because all local storage/caching has moved to data store level.

File: plugins/woocommerce-blocks/assets/js/blocks/mini-cart/frontend.ts [hunk 4]
```diff
@@ -24,8 +22,6 @@ interface dependencyData {
 	translations?: string;
 }
 
-updateTotals( getMiniCartTotalsFromLocalStorage() );
-getMiniCartTotalsFromServer().then( updateTotals );
```
Comment (mikejolley) [inline plugins/woocommerce-blocks/assets/js/blocks/mini-cart/frontend.ts:28]: These were responsible for the extra server requests on every page load.

File: plugins/woocommerce-blocks/assets/js/blocks/mini-cart/frontend.ts [hunk 5]
```diff
@@ -35,6 +31,14 @@ declare global {
 }
 
 window.addEventListener( 'load', () => {
+	// Update the totals immediately on load.
+	updateTotals( select( CART_STORE_KEY ).getCartData() );
```
Comment (mikejolley) [inline plugins/woocommerce-blocks/assets/js/blocks/mini-cart/frontend.ts:35]: We do this on load, but due to the new caching mechanism it will not always result in a new API request.

File: plugins/woocommerce-blocks/assets/js/blocks/mini-cart/quantity-badge/style.scss [hunk 6]
```diff
@@ -2,6 +2,10 @@
 	align-items: center;
 	display: flex;
 	position: relative;
+
+	&:empty {
+		display: none;
+	}
```
Comment (mikejolley) [inline plugins/woocommerce-blocks/assets/js/blocks/mini-cart/quantity-badge/style.scss:8]: This is to hide the badge when its empty instead of doing it on the PHP side.

File: plugins/woocommerce-blocks/assets/js/data/cart/index.ts [hunk 7]
```diff
@@ -27,10 +38,29 @@ const store = createReduxStore( STORE_KEY, {
...
 
 register( store );
 
+// The resolver for getCartData fires off an API request. But if we know the cart is empty, we can skip the request.
+// Likewise, if we have a valid persistent cart, we can skip the request.
+// The only reliable way to check if the cart is empty is to check the cookies.
+window.addEventListener( 'load', () => {
+	if (
+		( ! hasCartSession() || persistenceLayer.get() ) &&
+		! isAddingToCart
```
Comment (mikejolley) [inline plugins/woocommerce-blocks/assets/js/data/cart/index.ts:58]: I added a check for isAddingToCart because on those requests we're most likely going to need to do an API request, and also the playwright test suite was expecting a request.

File: plugins/woocommerce-blocks/assets/js/data/cart/thunks.ts [hunk 8]
```diff
@@ -39,18 +39,24 @@ export const receiveCart =
...
+		const cartResponse = camelCaseKeys( response ) as unknown as Cart;
 		const oldCart = select.getCartData();
 		const oldCartErrors = [ ...oldCart.errors, ...select.getCartErrors() ];
 
-		updateCartErrorNotices( newCart.errors, oldCartErrors );
+		// Set data from the response.
+		dispatch.setCartData( cartResponse );
+
+		// Get the new cart data before showing updates.
+		const newCart = select.getCartData();
```
Comment (mikejolley) [inline plugins/woocommerce-blocks/assets/js/data/cart/thunks.ts:50]: This ensures the `newCart` object is complete, because the data from the action may contain partial data which causes issues in other functions which look for specific object parameters.

**Review by alexflorisca — APPROVED** [review]
This tests well and code looks good. It makes sense to tie the local storage to the data store and have the mini cart use that. Nice work
