### PR TITLE
Provide server architecture message when php_uname is disabled

### LINKED ISSUE #58675: System Status requests fatal when php_uname() is disabled
## **Describe the bug**

Ref: [https://wordpress.org/support/topic/critical-uncaught-error-after-9-9-3/](https://wordpress.org/support/topic/critical-uncaught-error-after-9-9-3/)

Some hosting providers disable the `php_uname()` function in the name of security. 

In #57168, we introduced the usage of `php_uname()` when gathering OS data to include in the status reports for WooCommerce breaking those features for sites with the function blocked.  This includes the admin page and the rest route.

We'll need to add a `function_exists()` check to this usage.

## **Additional context**

### PR DESCRIPTION
**Pull request by joshuatf**
### Changes proposed in this Pull Request:

Some hosts disable `php_uname` for security reasons.  This adds a simple check to see if it's enabled and show the information if so.  If not, it recommends asking the host for the information.

Closes #58675  .

### Screenshots or screen recordings:

Screenshot 2025-06-10 at 5 25 15 PM
Screenshot 2025-06-10 at 5 23 25 PM

### How to test the changes in this Pull Request:

1. Navigate to `/wp-admin/admin.php?page=wc-status`
2. Under "Server Architecture" check that the correct information is shown
3. In your `php.ini` file for your server, add the following line or append `,php_uname` to `disable_functions` if it already exists:
```
disable_functions = php_uname
```
4. Restart your server
5. Navigate to `/wp-admin/admin.php?page=wc-status`
6. Under "Server Architecture" check that the error message is shown: "Unable to determine server architecture. Please ask your hosting provider for this information."

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce/includes/rest-api/Controllers/Version2/class-wc-rest-system-status-v2-controller.php [hunk 1]
```diff
@@ -987,7 +987,9 @@ public function get_environment_info_per_fields( $fields ) {
 		}
 
 		// Operating system.
-		$server_architecture = sprintf( '%s %s %s', php_uname( 's' ), php_uname( 'r' ), php_uname( 'm' ) );
+		$server_architecture = function_exists( 'php_uname' )
+			? sprintf( '%s %s %s', php_uname( 's' ), php_uname( 'r' ), php_uname( 'm' ) )
+			: __( 'Unable to determine server architecture.  Please ask your hosting provider for this information.', 'woocommerce' );
```
Comment (jorgeatorres) [inline plugins/woocommerce/includes/rest-api/Controllers/Version2/class-wc-rest-system-status-v2-controller.php]: Should this just be `unknown` so it is easier to parse by our tools? If we want to provide a nicer message on the Status page itself, we can probably do that [inside the template itself](https://github.com/woocommerce/woocommerce/blob/37e5f1e785c164878a2554490e8078a3f10b047e/plugins/woocommerce/includes/admin/views/html-admin-page-status-report.php#L254-L258).

**Review by jorgeatorres — APPROVED** [review]
Hey @joshuatf! Thanks for your PR. I left a suggestion, but totally optional, this looks good to me and tests well.

File: plugins/woocommerce/includes/rest-api/Controllers/Version2/class-wc-rest-system-status-v2-controller.php (hunk 1 above)
Comment (joshuatf) [reply plugins/woocommerce/includes/rest-api/Controllers/Version2/class-wc-rest-system-status-v2-controller.php]: Good call!  Updated in https://github.com/woocommerce/woocommerce/pull/58734/commits/11de35d44d2cfce07abc7cd5664b4f574d1a61dd.

Updated this to an empty string `''` to match other data without information.  While I think `null` would be even better, I don't want to change the expected return type in case any consumers are expecting strings.
