### PR TITLE
Data Stores & update_post_meta: Update changed & keys that don't exist.

### LINKED ISSUE #12816: Cannot create coupons with Discount Type of Fixed Cart Discount
## EXPLANATION OF THE ISSUE

Observed on master from Jan 12, 2017

If you create a Coupon of **Discount Type** "Fixed cart discount" and then edit it, it displays as **Discount Type** of "Percentage Discount" instead.  Also, there is nothing displayed in the **Coupon Type** column on the Coupons page for such coupons:

screen shot 2017-01-13 at 11 00 23 am

## STEPS TO REPRODUCE THE ISSUE

Attempt to create a coupon of discount type "Fixed Cart Discount"

## SYSTEM STATUS REPORT

N/A

### PR DESCRIPTION
**Pull request by emdashcodes**
@mikejolley I used the idea you came up with here: https://github.com/woocommerce/woocommerce/pull/12842#issuecomment-274469142

It nicely removes the force logic and seems to handle things correctly. Fixed the coupons bug, and I tested updating various order and product properties as well.

Moving to a new PR/branch since it's different from the original attempt.

Fixes #12816.

### CODE REVIEW

File: includes/data-stores/class-wc-data-store-wp.php [hunk 1]
```diff
@@ -165,4 +165,41 @@ protected function exclude_internal_meta_keys( $meta ) {
...
+	 * @param  WC_Data $object              The WP_Data object (WC_Coupon for coupons, etc).
+	 * @param  array   $meta_key_to_props   A mapping of meta keys => prop names.
+	 * @param  string  $meta_type           The internal WP meta type (post, user, etc).
+	 * @return array                        A mapping of meta keys => prop names, filtered by ones that should be updated.
+	 */
+	protected function get_props_to_update( $object, $meta_key_to_props, $meta_type = 'post' ) {
+		$props_to_update = array();
+		$changed_props   = $object->get_changes();
+
+		// Normalize billing / shipping / other keys that might be part of a sub array.
```
Comment (mikejolley) [inline includes/data-stores/class-wc-data-store-wp.php]: Shouldn't this logic be in the order data store?

File: includes/data-stores/class-wc-data-store-wp.php [hunk 2]
```diff
@@ -165,4 +165,41 @@ protected function exclude_internal_meta_keys( $meta ) {
...
+				unset( $changed_props[ $sub ] );
+			}
+		}
+
+		// Props should be updated if they are a part of the $changed array or don't exist yet.
+		foreach ( $meta_key_to_props as $meta_key => $prop ) {
+			if ( array_key_exists( $prop, $changed_props ) ) {
+				$props_to_update[ $meta_key ] = $prop;
+			}
+			if ( ! metadata_exists( $meta_type, $object->get_id(), $meta_key ) ) {
```
Comment (mikejolley) [inline includes/data-stores/class-wc-data-store-wp.php]: You could combine this with the rule above to keep it DRY

File: includes/data-stores/class-wc-order-data-store-cpt.php [hunk 3]
```diff
@@ -197,21 +191,16 @@ protected function update_post_meta( &$order, $force = false ) {
...
-			foreach ( $props as $meta_key => $prop ) {
-				$prop_key = substr( $prop, 8 );
-				if ( ! $force && ( ! isset( $changed_props[ $props_key ] ) || ! array_key_exists( $prop_key, $changed_props[ $props_key ] ) ) ) {
-					continue;
-				}
+			$props_to_update = $this->get_props_to_update( $order, $props );
+			foreach ( $props_to_update as $meta_key => $prop ) {
 				$value = $order->{"get_$prop"}( 'edit' );
-
-				if ( '' !== $value ? update_post_meta( $order->get_id(), $meta_key, $value ) : delete_post_meta( $order->get_id(), $meta_key ) ) {
```
Comment (mikejolley) [inline includes/data-stores/class-wc-order-data-store-cpt.php]: Was this removed for compatibility with the meta exists check?

**Review by mikejolley — COMMENTED** [review]
Looks better :) Added some notes and a qu.

File: includes/data-stores/class-wc-order-data-store-cpt.php (hunk 3 above)
Comment (justinshreve) [inline includes/data-stores/class-wc-order-data-store-cpt.php]: Yeah there are a few places where the meta is deleted like that if the value is empty -- which would cause it to be reinserted as empty and deleted again in the future.

File: includes/data-stores/class-wc-data-store-wp.php (hunk 1 above)
Comment (justinshreve) [inline includes/data-stores/class-wc-data-store-wp.php]: I've actually moved this up to WC_Order. It needs to act on get_changes.

https://github.com/woocommerce/woocommerce/pull/12950/files#diff-d40ff36ba2766206bbf9818c26167af8R344

**Comment by mikejolley** [comment]
Looks good to me now 👍
