### PR TITLE
convert user creation GMT datestamp to local datetime in API

### LINKED ISSUE #22247: date_created value for "customer created" web hook showing wrong time.
- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x ] I have attempted to find the simplest possible steps to reproduce the issue

## Steps to reproduce the issue

1. Use Melbourne timezone in Settings -> General 
2.  Create a web hook with customer created in WP REST API integration v2
3. Register a user through my account page and test the web hook http request. 

## Expected/actual behavior
When I register a user to the site, the web hook for customer created shows wrong **date_created** and **date_created_gmt**. 

I created a user in 11:51 am GMT. My site is on GMT + 11 timezone (Melbourne)
Here is the http response:
{
  "id": 6,
  "date_created": "2018-12-17T11:51:54",
  "date_created_gmt": "2018-12-17T00:51:54",
  "date_modified": null,
  "date_modified_gmt": null,
  "email": "test@test.com",
  "first_name": "",
  "last_name": "",
  "role": "customer",
  "username": "test",
  "billing": {
    "first_name": "",
    "last_name": "",
    "company": "",
    "address_1": "",
    "address_2": "",
    "city": "",
    "state": "",
    "postcode": "",
    "country": "",
    "email": "",
    "phone": ""
  },
  "shipping": {
    "first_name": "",
    "last_name": "",
    "company": "",
    "address_1": "",
    "address_2": "",
    "city": "",
    "state": "",
    "postcode": "",
    "country": ""
  },
  "is_paying_customer": false,
  "orders_count": 0,
  "total_spent": "0.00",
  "avatar_url": "http://2.gravatar.com/avatar/b642b4217b34b1e8d3bd915fc65c4452?s=96&d=mm&r=g",
  "meta_data": [
    {
      "id": 170,
      "key": "wc_last_active",
      "value": "1545004800"
    }
  ]
}

The date_created need to show local site time of registration instead of GMT time and date_created_gmt need to show GMT time of the user registration. 

When I test other web hooks like coupon and order create, those are working as expected. On those date_created shows the local site time and  date_created_gmt shows that local time converted to GMT

## Isolating the problem

- [ x] This bug happens with only WooCommerce plugin active
- [x ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x ] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>

`
### WordPress Environment ###

Home URL: http://woocommerce-148425-466749.cloudwaysapps.com
Site URL: http://woocommerce-148425-466749.cloudwaysapps.com
WC Version: 3.5.2
Log Directory Writable: ✔
WP Version: ❌ 4.9.9 - There is a newer version of WordPress available (5.0.1)
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.10 (Debian)
PHP Version: 7.0.32-1~dotdeb+8.1 - We recommend using PHP version 7.2 or above for greater performance and security. How to update your PHP version
PHP Post Max Size: 10 MB
PHP Time Limit: 60
PHP Max Input Vars: 2500
cURL Version: 7.38.0
OpenSSL/1.0.1t

SUHOSIN Installed: –
MySQL Version: ❌ 5.5.62-0+deb8u1 - We recommend a minimum MySQL version of 5.6. See: WordPress requirements
Max Upload Size: 10 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.2.6
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Total Database Size: 39.08MB
Database Data Size: 33.07MB
Database Index Size: 6.01MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_comments: Data: 0.02MB + Index: 0.09MB
wp_custom_checkout_url: Data: 0.02MB + Index: 0.00MB
wp_hidemysiteSecure: Data: 0.02MB + Index: 0.00MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_mobileassistant_accounts: Data: 0.02MB + Index: 0.02MB
wp_mobileassistant_devices: Data: 0.02MB + Index: 0.02MB
wp_mobileassistant_failed_login: Data: 0.02MB + Index: 0.00MB
wp_mobileassistant_push_settings: Data: 0.02MB + Index: 0.00MB
wp_mobileassistant_session_keys: Data: 0.02MB + Index: 0.00MB
wp_mobileassistant_users: Data: 0.02MB + Index: 0.02MB
wp_options: Data: 4.06MB + Index: 0.05MB
wp_pieregister_code: Data: 0.00MB + Index: 0.00MB
wp_pieregister_lockdowns: Data: 0.00MB + Index: 0.00MB
wp_pieregister_redirect_settings: Data: 0.00MB + Index: 0.00MB
wp_postmeta: Data: 24.47MB + Index: 4.02MB
wp_posts: Data: 3.45MB + Index: 0.77MB
wp_smush_dir_images: Data: 0.02MB + Index: 0.03MB
wp_strong_views: Data: 0.02MB + Index: 0.00MB
wp_termmeta: Data: 0.08MB + Index: 0.09MB
wp_terms: Data: 0.08MB + Index: 0.09MB
wp_term_relationships: Data: 0.22MB + Index: 0.13MB
wp_term_taxonomy: Data: 0.09MB + Index: 0.14MB
wp_usermeta: Data: 0.02MB + Index: 0.03MB
wp_users: Data: 0.02MB + Index: 0.05MB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB

### Post Type Counts ###

attachment: 3412
page: 14
post: 2
product: 486
product_variation: 11
revision: 7
rooms: 1
scheduled-action: 2
shop_coupon: 6
shop_order: 5
wpm-testimonial: 1

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 3.5.2

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: 
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #39 - /shop
Cart: #40 - /cart
Checkout: #41 - /checkout
My account: #42 - /my-account
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 2.3.5 – 2.4.2 is available
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –
`
</details>

### PR DESCRIPTION
**Pull request by rrennick**
### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

WordPress stores the user registered date as a GMT. The modified date in user meta is a local time. The rest controller is written to prepare local times. This PR converts the user registered date to local time in the rest controller.

Closes #22247 .

### How to test the changes in this Pull Request:

1. Create a user with the rest API.
2. The response should have the correct datestamps for both created & modified dates.
3.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?

### Changelog entry

> Fix customer creation dates in API.

### CODE REVIEW

**Comment by sarun007** [comment]
any updation for this issue??

File: includes/api/class-wc-rest-customers-controller.php [hunk 1]
```diff
@@ -38,7 +39,7 @@ protected function get_formatted_item_data( $object ) {
 
 		// Format date values.
 		foreach ( $format_date as $key ) {
-			$datetime              = $data[ $key ];
+			$datetime              = 'date_created' == $key ? get_date_from_gmt( $data[ $key ] ) : $data[ $key ];
```
Comment (rodrigoprimo) [inline includes/api/class-wc-rest-customers-controller.php]: After creating a user, if I try to get its data using the WC API, below is what I get for the `date_created` and `date_created_gmt` fields:

```
"date_created": "1970-01-01T00:00:00",
"date_created_gmt": "1970-01-01T00:00:00",
```

The value stored in the `user_registered` field is `2019-01-10 12:35:09`.

I believe this is happening because `get_date_from_gmt()` expects a string and `$data[$key]` is a instance of `WC_DateTime`. The unit test pass because the same problem happens when defining `$date_created` and `get_date_from_gmt()` also returns `1970-01-01T00:00:00`.

Besides the above, I would suggest adding a inline comment here explaining why it is necessary to use different logics to deal with `date_created` and `date_modified` (basically what you mentioned in the PR description).

**Review by rodrigoprimo — CHANGES_REQUESTED** [review]
I could confirm that the problem was correctly identified, but it seems to me that there is a bug in the proposed solution. See comment below for more details.

File: includes/api/class-wc-rest-customers-controller.php (hunk 1 above)
Comment (rrennick) [reply includes/api/class-wc-rest-customers-controller.php]: I'm getting the correct dates. When I wrote this I had PHP 7.2 but have since updated to 7.3. Are you working with PHP 5.X ?

```
  "id": 8,
  "date_created": "2019-01-10T14:56:50",
  "date_created_gmt": "2019-01-10T18:56:50",
  "date_modified": "2019-01-10T14:56:50",
  "date_modified_gmt": "2019-01-10T18:56:50",
```

Comment (rrennick) [reply includes/api/class-wc-rest-customers-controller.php]: @rodrigoprimo thanks for looking at this. I have updated the PR with both suggestions.

Comment (rodrigoprimo) [reply includes/api/class-wc-rest-customers-controller.php]: > When I wrote this I had PHP 7.2 but have since updated to 7.3. Are you working with PHP 5.X ?

I'm running PHP 7.2. I'm not sure why we are getting different results. I tried your newest patch and still got the wrong dates. I didn't have much time to investigate this today, but I did a quick test and it seems that on Travis the dates are also wrong:

https://travis-ci.org/rodrigoprimo/woocommerce/jobs/478494434#L662
https://github.com/rodrigoprimo/woocommerce/pull/23
https://github.com/rodrigoprimo/woocommerce/pull/23/commits/ba0d6fe3c599b8f56235513c8103ca093163f4ef#diff-def46ca6e3bffed618e410eaad72eff1R61

I can take a closer look at this next week if necessary.

Comment (rrennick) [reply includes/api/class-wc-rest-customers-controller.php]: @rodrigoprimo `get_date_from_gmt( WC_Customer::get_date_created() )` always returns Jan 1, 1970 when the `timezone_string` is not set so this test has always been comparing Jan 1, 1970 to Jan 1, 1970 for the creation date.

I have added another block of code which sets the TZ to `America/New York` and checks that the API returns the correct dates.

**Review by kloon — APPROVED** [review]
GTM with the recent changes, tests are passing and getting the correct results now via the API.

**Comment by AbdulSamadKt** [comment]
Hi, 

Thanks for the fix. Can I know how to add this fix to the WooCommerce? So I can fix it myself instead of waiting for 3.6.0

**Comment by rrennick** [comment]
> Can I know how to add this fix to the WooCommerce?

The file you need to update is https://github.com/woocommerce/woocommerce/blob/89ab2748dac7fe6f5450153c47f2cd22667cf50c/includes/api/class-wc-rest-customers-controller.php

**Comment by AbdulSamadKt** [comment]
I replaced the following file inside WooCommerce plugin folder but it didn't solved the issue. Still I am getting wrong values for the customer created web-hook.
https://github.com/woocommerce/woocommerce/blob/89ab2748dac7fe6f5450153c47f2cd22667cf50c/includes/api/class-wc-rest-customers-controller.php

**Comment by rrennick** [comment]
@AbdulSamadKt Sorry, you need to replace both files updated in the PR.

**Comment by AbdulSamadKt** [comment]
@rrennick  I couldn't find the other file in WooCommerce plugin. Can I know where is the other file in WooCommerce plugin folder?

**Comment by rrennick** [comment]
@AbdulSamadKt If you scroll to the top of this pull request there is a `Files changed` tab.

**Comment by AbdulSamadKt** [comment]
@rrennick I downloaded the woocommerce master plugin and tested. Still getting same wrong date_created and date_created_gmt. 

Here is my example:
My site is on Melbourne timezone and I registered a user at 06:57 am GMT. 

{
  "id": 12,
  "date_created": "2019-02-22T06:57:01",
  "date_created_gmt": "2019-02-21T19:57:01",
  "date_modified": null,
  "date_modified_gmt": null,
  "email": "sa112@fds.ig",
  "first_name": "",
  "last_name": "",
  "role": "subscriber",
  "username": "sa112",
  "billing": {
    "first_name": "",
    "last_name": "",
    "company": "",
    "address_1": "",
    "address_2": "",
    "city": "",
    "state": "",
    "postcode": "",
    "country": "",
    "email": "",
    "phone": ""
  },
  "shipping": {
    "first_name": "",
    "last_name": "",
    "company": "",
    "address_1": "",
    "address_2": "",
    "city": "",
    "state": "",
    "postcode": "",
    "country": ""
  },
  "is_paying_customer": false,
  "orders_count": 0,
  "total_spent": "0.00",
  "avatar_url": "http://0.gravatar.com/avatar/9d3916e36261faa96a9bd3f4f146cd32?s=96&d=mm&r=g",
  "meta_data": [
    {
      "id": 297,
      "key": "default_password_nag",
      "value": "1"
    }
  ]
}

**Comment by rrennick** [comment]
> I downloaded the woocommerce master plugin version 3.6.0-dev

The change was merged into `master`. That's the branch you should test.

**Comment by AbdulSamadKt** [comment]
Hi, Can I know is this issue fixed in latest WooCommerce ( 3.6.2)? I am still getting the same result as before. date_created showing GMT time instead of time in that timezone.

**Comment by rrennick** [comment]
@AbdulSamadKt What is your `timezone_string` in your `wp_options` table ?

**Comment by AbdulSamadKt** [comment]
@rrennick it is  Australia/Melbourne

**Comment by rrennick** [comment]
@AbdulSamadKt I changed my dev install to `Australia/Melbourne` and am getting the correct calculated dates:

```json
[
  {
    "id": 8,
    "date_created": "2019-01-11T05:56:50",
    "date_created_gmt": "2019-01-10T18:56:50",
    "date_modified": "2019-01-11T05:56:50",
    "date_modified_gmt": "2019-01-10T18:56:50",
    "email": "adoe@example.com",
    "first_name": "Ann",
    "last_name": "Doe",
    "role": "customer",
    "username": "ann.doe",
```

**Comment by AbdulSamadKt** [comment]
@rrennick  Australia/Melbourne time is GMT+10, so do you think this is correct?

**Comment by rrennick** [comment]
> so do you think this is correct?

The difference is 11 hours. Does Melbourne do DST? My dev computer is in a timezone that has DST which could be creating the additional hour.

**Comment by rrennick** [comment]
@AbdulSamadKt According to https://www.timeanddate.com/time/change/australia/melbourne the date I posted above is during Melbourne DST which is UTC+11 making it the correct calculated date.

**Comment by AbdulSamadKt** [comment]
@rrennick  Ok. So is the date_created need to show time in GMT?  or the timezone time (Melbourne time)?

I did another test now at 5:18 GMT and I got below values. Do you think this is correct?
 "date_created": "2019-05-23T05:18:19",
 "date_created_gmt": "2019-05-22T19:18:19",

**Comment by rrennick** [comment]
> For more clarity, I have created another webhook now for coupon created and the result is below at the time 05:41 GMT and for me, it shows correctly.

This PR was for the times in the REST api. If you have an issue with what's being sent to a webhook then create a new issue with steps to reproduce.

**Comment by AbdulSamadKt** [comment]
This but I reported here already https://github.com/woocommerce/woocommerce/issues/22247
