### PR TITLE
Track completion of non visible tasks as well

### LINKED ISSUE #32140: Task completion event not firing with WCPay task
### Describe the bug
The `wcadmin_tasklist_task_completed` event is not working properly with the WooCommerce Payments task. It went from ~200/day to almost 0 after Dec 15 (WooCommerce 6.0, [WC Admin 2.9](https://github.com/woocommerce/woocommerce-admin/blob/release/2.9.4/changelog.txt))

### To Reproduce

1. Create a new store with US as a country
2. Install WCPay in the business features step
3. Visit the home screen and click on the WCPay task
4. Finish the WCPay KYC
5. Confirm that `wcadmin_tasklist_task_completed` `task_name`: `woocommerce-payments`

### PR DESCRIPTION
**Pull request by louwie17**
### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Make sure we also track completion of non visible tasks and fix parent id in WooCommercePayments task

Closes #32140 

### How to test the changes in this Pull Request:

1. Run `pnpm nx build woocommerce` which will generate a zip
2. Load a Jurassic site with the zip, the [WooCommerce Admin Test Helper](https://github.com/woocommerce/woocommerce-admin-test-helper), and [WooCommerce Payments Dev Tools](https://github.com/Automattic/woocommerce-payments-dev-tools) (you probably want to disable the **Proxy WPCOM requests** setting in the WC Pay Dev Tools
3. Finish the onboarding wizard, installing WC Pay as part of the free business features
4. Enable the `progression_headercard` experiment under **WCA Test Helper > Experiments** enable the header card and the 2 col one to `treatment`
5. Go to **WooCommerce > Home** and finish the WooCommerce Payments task
6. Once connected The experiment task list won't show the Payments task anymore, but there should be a `wcadmin_tasklist_task_completed` generated to view this go to **WooCommerce > Status > Logs** and look for the `tracks-__current_date.log` log.

### Other information:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully run tests with your changes locally?

### Changelog entry

> Track completion of non visible tasks within the task list.

### FOR PR REVIEWER ONLY:

* [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

File: plugins/woocommerce/src/Admin/Features/OnboardingTasks/Tasks/AdditionalPayments.php [hunk 1]
```diff
@@ -73,8 +73,11 @@ public function can_view() {
 
 		$woocommerce_payments = new WooCommercePayments();
 
-		if ( ! $woocommerce_payments->is_requested() || ( $woocommerce_payments->is_supported() && ! $woocommerce_payments->is_connected() ) ) {
-			// Hide task if WC Pay is installed via OBW, in supported country, but not connected.
+		if ( ! $woocommerce_payments->is_requested() || ! $woocommerce_payments->is_supported() || ! $woocommerce_payments->is_connected() ) {
```
Comment (louwie17) [inline plugins/woocommerce/src/Admin/Features/OnboardingTasks/Tasks/AdditionalPayments.php:76]: Matches condition of latest `3.3.1` patch release -> https://github.com/woocommerce/woocommerce-admin/pull/8506

File: plugins/woocommerce/src/Admin/Features/OnboardingTasks/Tasks/AdditionalPayments.php [hunk 2]
```diff
@@ -73,8 +73,11 @@ public function can_view() {
...
+			// Hide task if WC Pay is not installed via OBW, or is not connected, or the store is located in a country that is not supported by WC Pay.
+			return false;
+		}
+		if ( $this->get_parent_id() === 'extended_two_column' && WooCommercePayments::is_connected() ) {
```
Comment (louwie17) [inline plugins/woocommerce/src/Admin/Features/OnboardingTasks/Tasks/AdditionalPayments.php:80]: Specific condition for the `extended_two_column` experimental task list

File: plugins/woocommerce/src/Admin/Features/OnboardingTasks/Tasks/WooCommercePayments.php [hunk 3]
```diff
@@ -19,15 +19,6 @@ public function get_id() {
...
 	}
 
-	/**
-	 * Parent ID.
-	 *
-	 * @return string
-	 */
-	public function get_parent_id() {
-		return 'setup';
-	}
```
Comment (louwie17) [inline plugins/woocommerce/src/Admin/Features/OnboardingTasks/Tasks/WooCommercePayments.php:29]: Remove this as the `Task` class contains this method.

Comment (joshuatf) [reply plugins/woocommerce/src/Admin/Features/OnboardingTasks/Tasks/WooCommercePayments.php:29]: Nice 👍 

Just a heads up that this override also exists in some old tests as well - https://github.com/woocommerce/woocommerce/blob/90a545b013c90580af2ce619d0b69f0d42faf29a/plugins/woocommerce/tests/legacy/unit-tests/woocommerce-admin/features/onboarding-tasks/test-task.php#L104-L106

File: plugins/woocommerce/src/Admin/Features/OnboardingTasks/Tasks/AdditionalPayments.php (hunk 2 above)
Comment (joshuatf) [reply plugins/woocommerce/src/Admin/Features/OnboardingTasks/Tasks/AdditionalPayments.php:80]: Specific knowledge around the parent task list `extended_two_column` feels a tiny bit like a code smell, but I'm honestly not quite sure where else this would live at the moment.

File: plugins/woocommerce/src/Admin/Features/OnboardingTasks/TaskList.php [hunk 4]
```diff
@@ -350,6 +350,13 @@ public static function possibly_remove_reminder_bar() {
 	 */
 	public function get_json() {
 		$this->possibly_track_completion();
+		// Track completion of non viewable tasks.
+		foreach ( $this->tasks as $task ) {
```
Comment (joshuatf) [inline plugins/woocommerce/src/Admin/Features/OnboardingTasks/TaskList.php:354]: Nicely done!

What do you think about calling `get_json()` on all tasks below when we get the tasks?  We could then keep logic around tracking individual task completion to a minimum in the list and defer to the `Task` for tracking logic.

Then we can either filter them by viewable here or filter by viewable on the client if that's not too much work.  I think the latter is the way we should be handling this FWIW, but if this requires heavy changes on the frontend then we don't need to open that can of worms.

**Review by joshuatf — COMMENTED** [review]
Code looks good and is testing well!  Tracks for non-viewable tasks also show in the new experiment.

Left a comment about moving the task track logic into the task, but otherwise this LGTM.

File: plugins/woocommerce/src/Admin/Features/OnboardingTasks/Tasks/AdditionalPayments.php (hunk 2 above)
Comment (louwie17) [reply plugins/woocommerce/src/Admin/Features/OnboardingTasks/Tasks/AdditionalPayments.php:80]: Yeah I would agree, we would almost just want a new Payments task class just for this task list with the updated logic, but that feels slightly like overkill.

File: plugins/woocommerce/src/Admin/Features/OnboardingTasks/TaskList.php (hunk 4 above)
Comment (louwie17) [reply plugins/woocommerce/src/Admin/Features/OnboardingTasks/TaskList.php:354]: I think that would be fine, my only caveat to that would be if the `get_json` triggers other expensive logic within tasks that are not viewable, meaning it would be kinda unnecessary.
But maybe that is something the actual task should handle anyway.

Comment (joshuatf) [reply plugins/woocommerce/src/Admin/Features/OnboardingTasks/TaskList.php:354]: Totally.  I share the same concerns, though my thinking is that `can_view` and `is_complete` are likely the expensive queries which we now need to run in both scenarios.

Using `get_json` was kind of a workaround to trigger tracks anyway and long-term we should probably refactor this slightly to possibly track completion in the constructor now that we're doing this for all tasks.

**Comment by louwie17** [comment]
Thanks for your review @joshuatf, I addressed your PR feedback in this commit -> https://github.com/woocommerce/woocommerce/pull/32493/commits/828e34a9745e5f84e195f76ed08e099048de4130
and responded to some of your comments.

**Review by joshuatf — COMMENTED** [review]
Thanks for the changes, @louwie17!  Everything looks good, though I think we'll also need to remove these lines to allow this to work:

https://github.com/woocommerce/woocommerce/blob/6336cb39f74d5b03ce14b2db34968aa9d3faf68d/plugins/woocommerce/src/Admin/Features/OnboardingTasks/Task.php#L361-L363

**Comment by louwie17** [comment]
> Thanks for the changes, @louwie17! Everything looks good, though I think we'll also need to remove these lines to allow this to work:
> 
> https://github.com/woocommerce/woocommerce/blob/6336cb39f74d5b03ce14b2db34968aa9d3faf68d/plugins/woocommerce/src/Admin/Features/OnboardingTasks/Task.php#L361-L363

Good catch @joshuatf, not sure how I missed that previously! I removed this in this commit -> https://github.com/woocommerce/woocommerce/pull/32493/commits/473d63d043a2a925b90a142454c4dd3e20fd9dd4

**Review by joshuatf — APPROVED** [review]
Great work, @louwie17!  LGTM 🎉
