### PR TITLE
Fix CSV import cleanup methods

### LINKED ISSUE #19863: Product Importer - Successful Import, But No Products in System
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [X] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [X ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Imported Products from attached Chariots-Import.csv
2. Importer indicated 1000+ products imported successfully, a few not successful (missing image)
3. WooCommerce shows ZERO products in the system.
4. Attempting to run the import again results in all the products being skipped because...."SKU already exists in system."
5. See https://youtu.be/IJ5IvLhvlXE for live demo.

## Expected/actual behavior

When I follow those steps, I see...

No products in the system, but WooCommerce claims all the products in the CSV are in the system when another import is attempted.

I was expecting to see...

Either the products showing up in WooCommerce OR an error indicating why the products did not get imported.

## Isolating the problem

- [X] This bug happens with only WooCommerce plugin active
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [X
[Chariots-Import.zip](https://github.com/woocommerce/woocommerce/files/1948860/Chariots-Import.zip)
] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```
</details>

### PR DESCRIPTION
**Pull request by mikejolley**
This fixes #19863 by cleaning up orphan data correctly so SKU does not appear used.

Use the CSV and test instructions in #19863 to reproduce. For the import to succeed you need to unset the images column because those images don't exist.

If you leave it set, no products will import, but this fix will avoid the broken products lingering around.

### CODE REVIEW

File: includes/admin/class-wc-admin-importers.php [hunk 1]
```diff
@@ -235,26 +235,34 @@ public function do_ajax_product_import() {
...
+				'post_type'   => 'product',
+				'post_status' => 'importing',
+			) );
+			$wpdb->delete( $wpdb->posts, array(
+				'post_type'   => 'product_variation',
+				'post_status' => 'importing',
+			) );
+			// @codingStandardsIgnoreEnd.
+
+			// Clean up orphanned data.
```
Comment (claudiulodro) [inline includes/admin/class-wc-admin-importers.php]: spelling

**Review by claudiulodro — APPROVED** [review]
