### PR TITLE
Check for _reduced_stock meta when restocking refunded items

### LINKED ISSUE #22489: Canceling Order is Restocking Item Twice
**Describe the bug**
When I cancel an Order the system restocks the order twice. Extra note. I haven't deactivated any plugins as this started happening out of nowhere. No Updates were made. One order was fine then it just started restocking twice.

**To Reproduce**
1. Go to 'Any Order and Cancel it.'
2. Scroll down to 'Look at Order Notes on the Order Page you just Canceled.'
4. See that order has been restocked twice.

**Expected behavior**
When the Orders Canceled it restocks 1 time.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
`
### WordPress Environment ###

Home URL: https://kingdomorganicseeds.com
Site URL: https://kingdomorganicseeds.com
WC Version: 3.5.3
Log Directory Writable: ✔
WP Version: 5.0.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.2.15
PHP Version: 7.2.13
PHP Post Max Size: 10 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.19.7
NSS/3.27.1

SUHOSIN Installed: –
MySQL Version: 5.6.42
Max Upload Size: 10 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.5.3
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Total Database Size: 24.82MB
Database Data Size: 19.83MB
Database Index Size: 4.99MB
wp_woocommerce_sessions: Data: 3.30MB + Index: 0.10MB
wp_woocommerce_api_keys: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_order_items: Data: 0.12MB + Index: 0.08MB
wp_woocommerce_order_itemmeta: Data: 0.88MB + Index: 0.66MB
wp_woocommerce_tax_rates: Data: 0.00MB + Index: 0.01MB
wp_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_log: Data: 0.00MB + Index: 0.00MB
Lord_linus_contact_form: Data: 0.02MB + Index: 0.00MB
wp_ac_abandoned_cart_history_lite: Data: 0.17MB + Index: 0.00MB
wp_ac_email_templates_lite: Data: 0.03MB + Index: 0.00MB
wp_ac_guest_abandoned_cart_history_lite: Data: 0.02MB + Index: 0.00MB
wp_ac_sent_history_lite: Data: 0.02MB + Index: 0.00MB
wp_commentmeta: Data: 0.06MB + Index: 0.06MB
wp_comments: Data: 1.21MB + Index: 0.36MB
wp_failed_jobs: Data: 0.02MB + Index: 0.00MB
wp_huge_itgallery_gallerys: Data: 0.00MB + Index: 0.00MB
wp_huge_itgallery_images: Data: 0.01MB + Index: 0.00MB
wp_huge_itgallery_like_dislike: Data: 0.00MB + Index: 0.00MB
wp_links: Data: 0.00MB + Index: 0.00MB
wp_mailchimp_carts: Data: 0.08MB + Index: 0.00MB
wp_options: Data: 0.61MB + Index: 0.06MB
wp_popupwith_fancybox: Data: 0.00MB + Index: 0.00MB
wp_postmeta: Data: 3.52MB + Index: 1.72MB
wp_posts: Data: 1.33MB + Index: 0.17MB
wp_queue: Data: 0.02MB + Index: 0.00MB
wp_sfa_abandoned_carts: Data: 2.94MB + Index: 0.05MB
wp_termmeta: Data: 0.01MB + Index: 0.01MB
wp_terms: Data: 0.02MB + Index: 0.06MB
wp_term_relationships: Data: 0.02MB + Index: 0.04MB
wp_term_taxonomy: Data: 0.02MB + Index: 0.04MB
wp_usermeta: Data: 1.09MB + Index: 0.70MB
wp_users: Data: 0.06MB + Index: 0.06MB
wp_wc_download_log: Data: 0.00MB + Index: 0.00MB
wp_wc_webhooks: Data: 0.00MB + Index: 0.00MB
wp_wfBadLeechers: Data: 0.00MB + Index: 0.00MB
wp_wfBlockedCommentLog: Data: 0.00MB + Index: 0.00MB
wp_wfBlockedIPLog: Data: 0.04MB + Index: 0.03MB
wp_wfBlocks: Data: 0.00MB + Index: 0.00MB
wp_wfBlocks7: Data: 0.01MB + Index: 0.01MB
wp_wfBlocksAdv: Data: 0.00MB + Index: 0.00MB
wp_wfConfig: Data: 1.03MB + Index: 0.01MB
wp_wfCrawlers: Data: 0.00MB + Index: 0.00MB
wp_wfFileChanges: Data: 0.00MB + Index: 0.00MB
wp_wfFileMods: Data: 0.58MB + Index: 0.13MB
wp_wfHits: Data: 1.79MB + Index: 0.29MB
wp_wfHoover: Data: 0.00MB + Index: 0.00MB
wp_wfIssues: Data: 0.01MB + Index: 0.01MB
wp_wfKnownFileList: Data: 0.28MB + Index: 0.04MB
wp_wfLeechers: Data: 0.07MB + Index: 0.12MB
wp_wfLiveTrafficHuman: Data: 0.05MB + Index: 0.07MB
wp_wfLockedOut: Data: 0.00MB + Index: 0.00MB
wp_wfLocs: Data: 0.02MB + Index: 0.00MB
wp_wfLogins: Data: 0.20MB + Index: 0.04MB
wp_wfNet404s: Data: 0.00MB + Index: 0.00MB
wp_wfNotifications: Data: 0.02MB + Index: 0.00MB
wp_wfPendingIssues: Data: 0.00MB + Index: 0.00MB
wp_wfReverseCache: Data: 0.00MB + Index: 0.00MB
wp_wfScanners: Data: 0.01MB + Index: 0.01MB
wp_wfSNIPCache: Data: 0.00MB + Index: 0.00MB
wp_wfStatus: Data: 0.12MB + Index: 0.05MB
wp_wfThrottleLog: Data: 0.00MB + Index: 0.00MB
wp_wfTrafficRates: Data: 0.00MB + Index: 0.00MB
wp_wfVulnScanners: Data: 0.00MB + Index: 0.00MB
wp_woo_shippment_provider: Data: 0.02MB + Index: 0.00MB

### Post Type Counts ###

amn_exact-metrics: 1
attachment: 517
gallery: 1
nav_menu_item: 37
page: 6
post: 45
product: 29
revision: 208
shipping_validation: 1
shop_coupon: 1
shop_order: 779
shop_order_refund: 2
widget: 1
wpcf7_contact_form: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (21) ###

Advanced Shipping Validation for WooCommerce: by Jeroen Sormani – 1.1.3 – Not tested with the active version of WooCommerce
w3dev Ban Users: by WEBxMedia LTD. (Matt Whiteman) – 1.5.3
Contact Form 7: by Takayuki Miyoshi – 5.1.1
Duplicate Post: by Enrico Battocchi – 3.2.2
Enhanced E-commerce for Woocommerce store: by Tatvic – 2.1.6
Mailchimp for WooCommerce: by Mailchimp – 2.1.11 – Not tested with the active version of WooCommerce
MailChimp: by MailChimp – 1.5.7
Popup with fancybox: by Gopi Ramasamy – 2.6
PromoBar by BestWebSoft: by BestWebSoft – 1.1.5
SSL Insecure Content Fixer: by WebAware – 2.7.2
TinyMCE Advanced: by Andrew Ozz – 5.0.0
Abandoned Cart Reports For WooCommerce: by Small Fish Analytics – 2.5.1
WooCommerce Advanced Shipment Tracking: by Zorem – 1.1 – Not tested with the active version of WooCommerce
WooCommerce Blocks: by Automattic – 1.3.0
Abandoned Cart Lite for WooCommerce: by Tyche Softwares – 5.1.3
WooCommerce Auto Restore Stock: by Gerhard Potgieter – 1.0.1 – Not tested with the active version of WooCommerce
WooCommerce Offline Credit Card Processing: by WP Lab – 1.7.9 – Not tested with the active version of WooCommerce
WooCommerce Discounts Per Payment Method: by Claudio Sanches – 3.0.0 – Not tested with the active version of WooCommerce
WooCommerce Product Stock Alert: by WC Marketplace
The Grey Parrots – 1.5.2

WooCommerce: by Automattic – 3.5.3
Wordfence Security: by Wordfence – 7.1.20

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #502 - /
Cart: #503 - /index.php/cart/
Checkout: #504 - /index.php/checkout/
My account: #505 - /index.php/my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Excellent
Version: 1.2.1
Author URL: https://themefreesia.com
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Archive Template: Your theme has a woocommerce.php file
you will not be able to override the woocommerce/archive-product.php custom template since woocommerce.php has priority over archive-product.php. This is intended to prevent display issues.

Overrides: –
`
</details>

### PR DESCRIPTION
**Pull request by mikejolley**
Fixes #22489

When restocking items after performing a refund it was not setting correct meta values for each item. Refunded items are tracked using meta on the item named `_reduced_stock`.

This PR checks if that meta exists before restocking the item, and deletes it after doing the restock action.

To test,

- Order an item that is stock managed
- Mark order complete. Stock is reduced.
- Refund the line item. Stock is restored.
- Cancel the order. No stock is changed.

> Fix - Set correct item meta after restocking items with refunds.

### CODE REVIEW

File: includes/wc-order-functions.php [hunk 1]
```diff
@@ -689,17 +689,23 @@ function wc_restock_refunded_items( $order, $refunded_line_items ) {
...
-			$order->add_order_note( sprintf( __( 'Item #%1$s stock increased from %2$s to %3$s.', 'woocommerce' ), $product->get_id(), $old_stock, $new_stock ) );
+		$old_stock = $product->get_stock_quantity();
+		$new_stock = wc_update_product_stock( $product, $refunded_line_items[ $item_id ]['qty'], 'increase' );
 
-			do_action( 'woocommerce_restock_refunded_item', $product->get_id(), $old_stock, $new_stock, $order, $product );
-		}
+		/* translators: 1: product ID 2: old stock level 3: new stock level */
+		$order->add_order_note( sprintf( __( 'Item #%1$s stock increased from %2$s to %3$s.', 'woocommerce' ), $product->get_id(), $old_stock, $new_stock ) );
+
+		$item->delete_meta_data( '_reduced_stock' );
```
Comment (peterfabian) [inline includes/wc-order-functions.php]: I think this does not cater for some scenarios:

### Partial refund
1. Order 4 products P ... `_reduced_stock` set to 4, product qty -4
2. Refund 2 products P ... `_reduced_stock` deleted, product qty +2
3. Cancel order ... no `_reduced_stock`, product qty +0

### Multi-refund
1. Order 4 products P ... `_reduced_stock` set to 4
2. Refund 1 products P ... `_reduced_stock` deleted, product qty +1
2. Refund 1 products P ... no `_reduced_stock`, product qty +0
3. Cancel order ... no `_reduced_stock`, product qty +0

**Review by peterfabian — CHANGES_REQUESTED** [review]
I think some cases are not covered, perhaps not very common ones. Please see below.

File: includes/wc-order-functions.php (hunk 1 above)
Comment (mikejolley) [reply includes/wc-order-functions.php]: You're right. I will borrow the correct logic for https://github.com/woocommerce/woocommerce/pull/22329/files since I worked on that in a different place already.

Comment (mikejolley) [reply includes/wc-order-functions.php]: Sorted

**Review by peterfabian — APPROVED** [review]
I think this works fine now. 

I also noticed that adding a product to order in admin does not update the qty, but I'll probably log a new issue for that (https://github.com/woocommerce/woocommerce/issues/22761)
