### PR TITLE
Mini Cart Bugfix - Error notices dont show up in the mini cart on initial load.

### LINKED ISSUE #59506: Error notices don't show up in the mini-cart on initial load
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When using a very simple snippet to add errors to the cart, taking inspiration from the [https://github.com/woocommerce/woocommerce/blob/1aa92f68805c83899b3d796c0396f7a4f4\[…\]oocommerce/client/blocks/docs/examples/validate-cart.md?plain=1](https://github.com/woocommerce/woocommerce/blob/1aa92f68805c83899b3d796c0396f7a4f4fdf127/plugins/woocommerce/client/blocks/docs/examples/validate-cart.md?plain=1#L12):

```
function my_function_callback( $errors, $cart ) {

  // Validate the $cart object and add errors. For example, to create an error if the cart contains more than 10 items:
  
    $errors->add( 'my_error_code', 'Too many cart items!' );
 
}

add_action( 'woocommerce_store_api_cart_errors', 'my_function_callback', 10, 2 );
```

I notice that the error message is not displayed in the mini-cart on initial load, but instead I need to change the cart item quantity to trigger the error to show up. This was working correctly in v9.9.5, but not in `trunk`.

### Expected behavior

The expected behavior is that all errors that are active in the cart should also be displayed in the mini-cart from the initial load.

### Actual behavior

The actual behavior is that cart errors are not displayed in the mini-cart on initial load.

### Steps to reproduce

1. Check out `trunk` and use the Twenty Twenty Five theme with a cart block.
2. Install this snippet that should always display a cart error:

```
function my_function_callback( $errors, $cart ) {

  // Validate the $cart object and add errors. For example, to create an error if the cart contains more than 10 items:
  
    $errors->add( 'my_error_code', 'Too many cart items!' );
 
}

add_action( 'woocommerce_store_api_cart_errors', 'my_function_callback', 10, 2 );
```

3. Add a product to the cart.
4. View the cart block -- ensure that you see the error there.
5. View the single product page and open the mini-cart.
6. Notice that the error is not displayed there.
7. Change the cart item quantity -- the error is displayed.
8. Go back to v9.9.5 and ensure that the error is displayed from the first time you open the mini-cart.

### WordPress Environment

Fresh WordPress installation with WooCommerce nightly and Twenty Twenty Five theme with a cart block.

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by samueljseay**
### Changes proposed in this Pull Request:

Closes #59506 

To fix this issue, I've opted to server hydrate error notices and to get them straight from the hydrated cart response since we want to use the Store API wherever possible.

It wasn't possible to fully utilize wp-each without manually rendering the children because the spans contain HTML that's rendered client-side. So we escape and render the content of the notice server side and bind a wp-watch to update it later.

### How to test the changes in this Pull Request:

1. First add a code snippet to your site that persistently adds an error notice every request. I've copied @jimjasson 's snippet from the original issue:

```php
function my_function_callback( $errors, $cart ) {

  // Validate the $cart object and add errors. For example, to create an error if the cart contains more than 10 items:
  
    $errors->add( 'my_error_code', 'Too many cart items!' );
 
}

add_action( 'woocommerce_store_api_cart_errors', 'my_function_callback', 10, 2 );
```

2. Add some items to your cart from anywhere. (the error only shows when there is something in the cart).
3. Open the Mini Cart drawer, you should see the error notice added by the snippet at the top of the mini cart.
4. Also leave the items in cart and refresh the page and open the cart, also observe the error notice is present.

*Screenshot of expected UI*

Screenshot 2025-12-08 at 11 05 54 PM

### Testing that has already taken place:

Manual testing of the scenario above carried out with WP 6.9.

### Milestone

- [x] Automatically assign milestone for the **[next WooCommerce version](../blob/trunk/plugins/woocommerce/woocommerce.php#L6)**

> **Note:** Check the box above to have the milestone automatically assigned when merged.
> Alternatively (e.g. for point releases), manually assign the appropriate milestone.

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [x] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 
Fix a bug where error notices don't show up in the Mini Cart on first load.

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce/src/Blocks/BlockTypes/FilledMiniCartContentsBlock.php [hunk 1]
```diff
@@ -58,42 +65,75 @@ protected function render_experimental_filled_mini_cart_contents( $attributes, $
 			)
 		);
 
+		// Error icon SVG path - matches ICON_PATHS.error in store-notices.ts.
+		$error_icon_path    = 'M12 3.2c-4.8 0-8.8 3.9-8.8 8.8 0 4.8 3.9 8.8 8.8 8.8 4.8 0 8.8-3.9 8.8-8.8 0-4.8-4-8.8-8.8-8.8zm0 16c-4 0-7.2-3.3-7.2-7.2C4.8 8 8 4.8 12 4.8s7.2 3.3 7.2 7.2c0 4-3.2 7.2-7.2 7.2zM11 17h2v-6h-2v6zm0-8h2V7h-2v2z';
```
Comment (samueljseay) [inline plugins/woocommerce/src/Blocks/BlockTypes/FilledMiniCartContentsBlock.php]: Just noting that we fix to the error notice here because the notices we get from the Cart are always just error notices.

File: plugins/woocommerce/src/Blocks/Utils/BlocksSharedState.php [hunk 2]
```diff
@@ -190,4 +190,36 @@ public static function load_placeholder_image( string $consent_statement ): void
...
+		self::check_consent( $consent_statement );
+
+		if ( null === self::$blocks_shared_cart_state ) {
+			return array();
+		}
+
+		$errors  = self::$blocks_shared_cart_state['errors'] ?? array();
+		$notices = array();
+
+		foreach ( $errors as $error ) {
```
Comment (samueljseay) [inline plugins/woocommerce/src/Blocks/Utils/BlocksSharedState.php:215]: Here we do map to a new format for the store notices, but we could enforce that all data from BlocksSharedState retains the format of the Store API and change the shape of this data elsewhere. I'm open to suggestion on this.

File: plugins/woocommerce/src/Blocks/BlockTypes/FilledMiniCartContentsBlock.php [hunk 3]
```diff
@@ -39,9 +40,15 @@ protected function render( $attributes, $content, $block ) {
 	 * @return string Rendered block type output.
 	 */
 	protected function render_experimental_filled_mini_cart_contents( $attributes, $content, $block ) {
+		// Manually enqueue the store-notices store.
+		wp_enqueue_script_module( '@woocommerce/stores/store-notices' );
+
+		$consent = 'I acknowledge that using private APIs means my theme or plugin will inevitably break in the next version of WooCommerce';
+		$notices = BlocksSharedState::get_cart_error_notices( $consent );
```
[the remark this answers is not in the document]
Comment (samueljseay) [reply plugins/woocommerce/src/Blocks/BlockTypes/FilledMiniCartContentsBlock.php:44]: This one's a good idea, I'll fix that.

File: plugins/woocommerce/src/Blocks/BlockTypes/FilledMiniCartContentsBlock.php [hunk 4]
```diff
@@ -39,9 +40,15 @@ protected function render( $attributes, $content, $block ) {
 	 * @return string Rendered block type output.
 	 */
 	protected function render_experimental_filled_mini_cart_contents( $attributes, $content, $block ) {
+		// Manually enqueue the store-notices store.
+		wp_enqueue_script_module( '@woocommerce/stores/store-notices' );
```
Comment (samueljseay) [inline plugins/woocommerce/src/Blocks/BlockTypes/FilledMiniCartContentsBlock.php]: I can't work out why I need this, but if I don't manually load it server side, the renderNoticeContent directive is not processed.

I tried a static import in mini cart frontend but it made no difference. @luisherranz or @DAreRodz if someone could help me take a look at that, I'd appreciate it.

File: plugins/woocommerce/src/Blocks/BlockTypes/FilledMiniCartContentsBlock.php [hunk 5]
```diff
@@ -39,9 +40,15 @@ protected function render( $attributes, $content, $block ) {
...
+
+		$consent = 'I acknowledge that using private APIs means my theme or plugin will inevitably break in the next version of WooCommerce';
+		$notices = BlocksSharedState::get_cart_error_notices( $consent );
+
 		$context = wp_json_encode(
 			array(
-				'notices' => array(),
+				'notices' => $notices,
```
[the remark this answers is not in the document]
Comment (samueljseay) [reply plugins/woocommerce/src/Blocks/BlockTypes/FilledMiniCartContentsBlock.php:48]: I don't think its practical for us to add deprecations for change in context like this.

File: plugins/woocommerce/src/Blocks/BlockTypes/FilledMiniCartContentsBlock.php [hunk 6]
```diff
@@ -53,47 +60,80 @@ protected function render_experimental_filled_mini_cart_contents( $attributes, $
 		$wrapper_attributes = get_block_wrapper_attributes(
 			array(
 				'data-wp-interactive'  => 'woocommerce/mini-cart',
-				'data-wp-context'      => 'woocommerce/store-notices::' . $context,
+				'data-wp-context'      => $context,
```
[the remark this answers is not in the document]
Comment (samueljseay) [reply plugins/woocommerce/src/Blocks/BlockTypes/FilledMiniCartContentsBlock.php]: This change was redundant. I've removed it.

File: plugins/woocommerce/src/Blocks/BlockTypes/FilledMiniCartContentsBlock.php [hunk 7]
```diff
@@ -53,47 +60,80 @@ protected function render_experimental_filled_mini_cart_contents( $attributes, $
...
 		ob_start();
 		?>
 		<div <?php echo $wrapper_attributes; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped ?>>
 			<div
 				class="wc-block-components-notices"
 				data-wp-interactive="woocommerce/store-notices"
-			><template
-				data-wp-each--notice="context.notices"
-				data-wp-each-key="context.notice.id"
+				data-wp-context="<?php echo esc_attr( $context ); ?>"
```
[the remark this answers is not in the document]
Comment (samueljseay) [reply plugins/woocommerce/src/Blocks/BlockTypes/FilledMiniCartContentsBlock.php]: > Custom JavaScript that previously interacted with this container or expected a specific initialization order may break.

Custom JavaScript or css selectors on data attributes are not public back compat APIs we will try and support.

File: plugins/woocommerce/src/Blocks/BlockTypes/FilledMiniCartContentsBlock.php [hunk 8]
```diff
@@ -53,47 +60,80 @@ protected function render_experimental_filled_mini_cart_contents( $attributes, $
...
+							aria-label="<?php echo esc_attr( $dismiss_aria_label ); ?>"
+							data-wp-on--click="actions.removeNotice"
+						>
+							<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
+								<path d="M13 11.8l6.1-6.3-1-1-6.1 6.2-6.1-6.2-1 1 6.1 6.3-6.5 6.7 1 1 6.5-6.6 6.5 6.6 1-1z" />
+							</svg>
+						</button>
+					</div>
+			</template>
+			<?php foreach ( $notices as $notice ) : ?>
```
[the remark this answers is not in the document]
Comment (samueljseay) [reply plugins/woocommerce/src/Blocks/BlockTypes/FilledMiniCartContentsBlock.php]: I think we just need to careful to check styling has not broken, but I haven't changed the structure of the rendered list items.

File: plugins/woocommerce/src/Blocks/Utils/BlocksSharedState.php [hunk 9]
```diff
@@ -190,4 +190,37 @@ public static function load_placeholder_image( string $consent_statement ): void
...
+		// Ensure cart state is loaded so this method works independently.
+		if ( null === self::$blocks_shared_cart_state ) {
+			self::load_cart_state( $consent_statement );
+		}
+
+		$errors  = self::$blocks_shared_cart_state['errors'] ?? array();
+		$notices = array();
+
+		foreach ( $errors as $error ) {
+			$notices[] = array(
```
[the remark this answers is not in the document]
Comment (samueljseay) [reply plugins/woocommerce/src/Blocks/Utils/BlocksSharedState.php:216]: The cart *only* contains error messages. This is extracting the error messages from the cart and using them as context for the store notices. I do agree theres a question about where data transform could happen, but I don't think it's very critical.

File: plugins/woocommerce/src/Blocks/BlockTypes/FilledMiniCartContentsBlock.php (hunk 4 above)
Comment (DAreRodz) [reply plugins/woocommerce/src/Blocks/BlockTypes/FilledMiniCartContentsBlock.php]: > I tried a static import in mini cart frontend but it made no difference.

I tried as well, and at first I also thought it wasn't working. It seems I just had to restart the `watch:build` process. 🤔

This is the change I did:

```patch
diff --git a/plugins/woocommerce/client/blocks/assets/js/blocks/mini-cart/iapi-frontend.ts b/plugins/woocommerce/client/blocks/assets/js/blocks/mini-cart/iapi-frontend.ts
index 86d3a81a08..95bc2f26d1 100644
--- a/plugins/woocommerce/client/blocks/assets/js/blocks/mini-cart/iapi-frontend.ts
+++ b/plugins/woocommerce/client/blocks/assets/js/blocks/mini-cart/iapi-frontend.ts
@@ -11,6 +11,7 @@ import {
 	withSyncEvent,
 } from '@wordpress/interactivity';
 import '@woocommerce/stores/woocommerce/cart';
+import '@woocommerce/stores/store-notices';
 import type {
 	Store as WooCommerce,
 	WooCommerceConfig,

```

While `watch:build` was running, I noticed in the generated `assets/client/blocks/interactivity-blocks-frontend-assets.php` file that `@wordpress/stores/store-notices` was included as a dynamic dependency, even though it is imported statically.

```php
'woocommerce/mini-cart.js' => array(
    'dependencies' => array(
        '@woocommerce/stores/woocommerce/cart',
        '@wordpress/interactivity',
        array(
            'id'     => '@woocommerce/stores/store-notices',
            'import' => 'dynamic'
        )
    ),
```

However, after restarting the process, the dependency was correctly included as static.

```php
'woocommerce/mini-cart.js' => array(
    'dependencies' => array(
        '@woocommerce/stores/store-notices',
        '@woocommerce/stores/woocommerce/cart',
        '@wordpress/interactivity'
    ),
```

I have no idea why it is considered dynamic until the process is restarted, though.

File: plugins/woocommerce/src/Blocks/BlockTypes/FilledMiniCartContentsBlock.php (hunk 1 above)
Comment (DAreRodz) [reply plugins/woocommerce/src/Blocks/BlockTypes/FilledMiniCartContentsBlock.php]: Now that I have removed the part that served-rendered the notices in 74703b6, I'm wondering what we should do with `$error_icon_path` and maybe other variables as well.

The path is being read from `state.iconPath`, so maybe we should implement that getter in PHP and move the `$error_icon_path` to the initial state. 🤔

Comment (DAreRodz) [reply plugins/woocommerce/src/Blocks/BlockTypes/FilledMiniCartContentsBlock.php]: Same with `$dismiss_aria_label`, below.

**Review by opr — COMMENTED** [review]
I tested this out and it works, it would be great to add or update a unit/integration test to cover this scenario

File: plugins/woocommerce/src/Blocks/BlockTypes/FilledMiniCartContentsBlock.php (hunk 1 above)
Comment (samueljseay) [reply plugins/woocommerce/src/Blocks/BlockTypes/FilledMiniCartContentsBlock.php]: > Now that I have removed the part that served-rendered the notices in 74703b6, 

Nice! 

> Same with $dismiss_aria_label, below.

For this one it's completely static, we've been recommending using wp_interactivity_config when it's not really changeable state so I'd be inclined to use that or just keep the rendering you have here as is.

For the icon path, is there any benefit in this store notice in using `state.iconPath`? Since they're all error notices for this particular usage. 

I see that it looks a bit clunky / inconsistent with other uses of store notices, but I also think that'd be part of a broader discussion where we need to decided how we consolidate all store notices to a single place where they're server side rendered in PHP which is out of the scope of this.

I'd be inclined to either delete the variable here and rely on `state.iconPath` for now or just hardcode it and remove the binding to `state.iconPath`. Wdyt? 

We could do more refactoring as a follow up. At least from my perspective it doesn't seem very high value to worry about solving it here.

Comment (samueljseay) [reply plugins/woocommerce/src/Blocks/BlockTypes/FilledMiniCartContentsBlock.php]: @DAreRodz I also didn't realize till I wrote some tests that actually binding directives server side for SVGs is [not yet supported](https://make.wordpress.org/core/2024/06/28/updates-to-the-interactivity-api-in-6-6/#unsupported-html-tags).

So that means if we put it in PHP state we wouldn't get the directive processed anyway? Should we just hardcode it for this instance since all messages are errors, add a comment about why we've done this and look to solve later?

File: plugins/woocommerce/tests/php/src/Blocks/BlockTypes/FilledMiniCartContentsBlockTest.php [hunk 10]
```diff
@@ -0,0 +1,173 @@
...
+		$reflection = new \ReflectionClass( BlocksSharedState::class );
+		$property   = $reflection->getProperty( 'blocks_shared_cart_state' );
+		$property->setValue( null, null );
+	}
+
+	/**
+	 * @testdox Should render error notices in data-wp-context when cart has errors.
+	 */
+	public function test_renders_error_notices_in_context_when_cart_has_errors(): void {
+		// TODO: Should we hardcode the path? Because server side rendering does not support SVG, we will get a _doing_it_wrong warning,
```
Comment (samueljseay) [inline plugins/woocommerce/tests/php/src/Blocks/BlockTypes/FilledMiniCartContentsBlockTest.php]: @DAreRodz I've added some tests, but I wanted to get your opinion on whether we should hardcode the path of the SVG for now to avoid this issue. It seemed from my perspective that we shouldn't cause warnings in normal usage of WooCommerce.

I also wonder, if you agree it's an issue whether we should check if we're doing directive binding to SVGs anywhere else in WooCommerce.

**Comment by samueljseay** [comment]
I've added some tests in [7ad5c8a](https://github.com/woocommerce/woocommerce/pull/62315/commits/7ad5c8a3e26b6934ceca1e32428a94be69c41997)

But I also want to get @DAreRodz opinion on the [SVG issue](https://github.com/woocommerce/woocommerce/pull/62315#discussion_r2652254945) before requesting re-review from others.

**Comment by luisherranz** [comment]
> But I also want to get @DAreRodz opinion on the https://github.com/woocommerce/woocommerce/pull/62315#discussion_r2652254945 before requesting re-review from others.

Until we have support for SVGs, let's try not to add directives unless they are strictly necessary. I fixed it in https://github.com/woocommerce/woocommerce/pull/62315/changes/fee0c950f9a1ac5087333821779594c71de934d7.

_The Interactivity API will support SVGs when the HTML API is finished and can finally be used._

EDIT: I'm thinking about whether there would be a way to avoid introducing a span wrapper, because even though changing the CSS fixes the WooCommerce styles, we might be breaking the theme styles.

For experimentation, I have also tested how the solution would look with a `data-wp-dangerous-html` directive: https://github.com/woocommerce/woocommerce/pull/62315/changes/a16e783efdb8965cbfb63257bbc6eb26932e1453, reverted in https://github.com/woocommerce/woocommerce/pull/62315/changes/b77bf7159d2ef2528ed622bcbb9e5cdd4156b073.

**Comment by luisherranz** [comment]
Here is an alternative that keeps the HTML (and CSS) intact.

https://github.com/woocommerce/woocommerce/pull/62315/commits/5c1971d841d875ad865f9782373ebffbad2490d8

File: plugins/woocommerce/client/blocks/assets/js/base/components/notice-banner/style.scss [hunk 11]
```diff
@@ -64,7 +64,12 @@
 		}
 	}
 
-	> svg {
+	> .wc-block-components-notice-banner__icon {
```
[the remark this answers is not in the document]
Comment (luisherranz) [reply plugins/woocommerce/client/blocks/assets/js/base/components/notice-banner/style.scss]: Fixed in https://github.com/woocommerce/woocommerce/commit/5c1971d841d875ad865f9782373ebffbad2490d8.

**Review by luisherranz — APPROVED** [review]
This looks good as a bugfix, but it makes me think that we should really spend some time working on the store notices soon.

On the other hand, I don't quite understand why you included another `data-wp-context` in the template wrapper div. I've deleted it in https://github.com/woocommerce/woocommerce/pull/62315/changes/5c1971d841d875ad865f9782373ebffbad2490d8 but now your tests are failing. Can you fix them? The `data-wp-context` needs to be in the outermost wrapper so it captures the actions in the `$content`.

**Comment by samueljseay** [comment]
> On the other hand, I don't quite understand why you included another data-wp-context in the template wrapper div. I've deleted it in https://github.com/woocommerce/woocommerce/commit/5c1971d841d875ad865f9782373ebffbad2490d8 but now your tests are failing. Can you fix them? The data-wp-context needs to be in the outermost wrapper so it captures the actions in the $content.

I'm looking back on it and not sure why I did that either. I think I was having some problem with the context being picked up, but it could have been because I removed the namespace from the outer context. Anyway, I've re-tested your changes and they work well.

I've decided to remove the test that needed fixing, I think it was quite low value. I've added an e2e test that explicitly tests that the notice was SSR'd. Testing it here on Github CI though as I'm having env troubles with e2e.

File: plugins/woocommerce/src/Blocks/BlockTypes/FilledMiniCartContentsBlock.php [hunk 12]
```diff
@@ -72,10 +70,8 @@ protected function render_experimental_filled_mini_cart_contents( $attributes, $
 			<div
 				class="wc-block-components-notices"
 				data-wp-interactive="woocommerce/store-notices"
-				data-wp-context="<?php echo esc_attr( $context ); ?>"
-			>
-				<template
-					data-wp-each--notice="context.notices"
+			><template
+					data-wp-each--notice="state.notices"
```
Comment (samueljseay) [inline plugins/woocommerce/src/Blocks/BlockTypes/FilledMiniCartContentsBlock.php]: @luisherranz Was this change intentional? While I can certainly see it makes sense, it broke the SSR because we're not populating state server side right now.

Comment (luisherranz) [reply plugins/woocommerce/src/Blocks/BlockTypes/FilledMiniCartContentsBlock.php]: I did it to maintain consistency with the other blocks, but feel free to revert it.

File: plugins/woocommerce/client/blocks/tests/e2e/tests/mini-cart/mini-cart-block.shopper.block_theme.spec.ts [hunk 13]
```diff
@@ -27,6 +27,55 @@ const test = base.extend< { productCollectionPage: ProductCollectionPage } >( {
...
+		// Verify error notice is rendered in SSR output (not client-side JS).
+		await expect(
+			noJsPage.locator( '.wc-block-components-notice-banner' )
+		).toBeVisible();
+		await expect(
+			noJsPage.getByText( /out of stock|not available/i )
+		).toBeVisible();
+
+		await noJsContext.close();
+	} );
```
[the remark this answers is not in the document]
Comment (samueljseay) [reply plugins/woocommerce/client/blocks/tests/e2e/tests/mini-cart/mini-cart-block.shopper.block_theme.spec.ts]: I'd agree, but just inline with consistency elsewhere I think we can ignore this. The other tests rely on resetting of db snapshots right now. We could improve it in the future.
