### PR TITLE
[Experimental] Refactor the interactivity dropdown to remove dependence on FormTokenField

### LINKED ISSUE #43154: Dropdown and Checkbox list components register wrong style URL

### LINKED ISSUE #43158: Dropdown component: refactor to remove use of FormTokenField styles

### PR DESCRIPTION
**Pull request by samueljseay**
### Changes proposed in this Pull Request:

* Remove FormTokenField html markup from Dropdown.php
* Remove FormTokenField from editor side rendering of collection filter blocks (including removing use of emotion to color text)
* Fix bugs where stock status filter did not support multi select dropdown
* Fix other small bugs or clean up (e.g. AssetsController bug not loading CSS for dropdown and checkbox list)

Closes #43158

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Test a couple of the filter blocks that have a dropdown mode (e.g. rating and stock status filter), both in single and multi select mode and see that they work as before.
2. Compare the styles to the old styles (simplest is to compare to trunk, could use JN for this purpose). I haven't made it pixel for pixel identical, but I feel that looks the same as the old one.
3. Also test overriding text color, see that the text color is respected in editor and front end for dropdown mode.

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [x] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message

[Experimental] Refactor interactivity dropdown to remove FormTokenField. Also fix multi select for rating filter.

#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce-blocks/packages/interactivity-components/dropdown/index.ts [hunk 1]
```diff
@@ -2,6 +2,10 @@
  * External dependencies
  */
 import { getContext, store } from '@woocommerce/interactivity';
+/**
+ * External dependencies
+ */
```
Comment (dinhtungdu) [inline plugins/woocommerce-blocks/packages/interactivity-components/dropdown/index.ts]: this comment is duplicated

File: plugins/woocommerce-blocks/packages/interactivity-components/dropdown/style.scss [hunk 2]
```diff
@@ -1,145 +1,90 @@
-@import "../../../assets/js/blocks/shared/styles/style";
-
 .wc-interactivity-dropdown {
```
Comment (dinhtungdu) [inline plugins/woocommerce-blocks/packages/interactivity-components/dropdown/style.scss:1]: image

File: plugins/woocommerce-blocks/assets/js/blocks/collection-filters/inner-blocks/attribute-filter/components/attribute-dropdown.tsx [hunk 3]
```diff
@@ -1,36 +1,28 @@
...
 	return (
 		<div className="wc-block-attribute-filter style-dropdown">
-			<StyledFormTokenField
-				suggestions={ [] }
+			<PreviewDropdown
 				placeholder={ sprintf(
 					/* translators: %s attribute name. */
 					__( 'Select %s', 'woocommerce' ),
 					label
 				) }
```
Comment (dinhtungdu) [inline plugins/woocommerce-blocks/assets/js/blocks/collection-filters/inner-blocks/attribute-filter/components/attribute-dropdown.tsx:25]: The Dropdown component currently always shows `Select an option` on the frontend, it'd be nice to add this ability to customize the placeholder (in another PR) on the frontend.

**Review by dinhtungdu — APPROVED** [review]
Really great work! The logic is much simpler than it was before. I left some minor comments but this is LGTM already so I'm pre approving!

File: plugins/woocommerce-blocks/packages/interactivity-components/dropdown/index.ts (hunk 1 above)
Comment (samueljseay) [reply plugins/woocommerce-blocks/packages/interactivity-components/dropdown/index.ts]: Thanks for spotting! 😅 resolved in https://github.com/woocommerce/woocommerce/pull/43183/commits/46dd5b6bde6700340695e1c8121d3751ca2556a0

File: plugins/woocommerce-blocks/packages/interactivity-components/dropdown/style.scss (hunk 2 above)
Comment (samueljseay) [reply plugins/woocommerce-blocks/packages/interactivity-components/dropdown/style.scss:1]: Good spotting! I fixed that here https://github.com/woocommerce/woocommerce/pull/43183/commits/e414cd0300130c198aa10723b9ca8aaccec70827

Preview:

Screenshot 2024-01-02 at 11 04 32 AM

File: plugins/woocommerce-blocks/assets/js/blocks/collection-filters/inner-blocks/attribute-filter/components/attribute-dropdown.tsx (hunk 3 above)
Comment (samueljseay) [reply plugins/woocommerce-blocks/assets/js/blocks/collection-filters/inner-blocks/attribute-filter/components/attribute-dropdown.tsx:25]: Yep that should be a quick fix! I'll add a task for that.

Comment (samueljseay) [reply plugins/woocommerce-blocks/assets/js/blocks/collection-filters/inner-blocks/attribute-filter/components/attribute-dropdown.tsx:25]: https://github.com/woocommerce/woocommerce/issues/43205
