### PR TITLE
Enhancement/variation selector attribute options

### LINKED ISSUE #62863: Update Variation Selector: Attribute Options attributes UI
## **Describe the bug**

Follow-up of https://github.com/woocommerce/woocommerce/pull/61389.

We should update the UI to select the attributes in the _Variation Selector: Attribute Options_ block so:

1. We move away from PanelBody to ToolsPanel as mentioned in [https://github.com/woocommerce/woocommerce/issues/59464](https://github.com/woocommerce/woocommerce/issues/59464).
2. In the first toggle, I would rename "Auto-select when only one attribute is compatible" to "Auto-select when only one option is available" and the description could be "Automatically select options on page load or after the shopper changes attributes, when only one valid choice is available."
3. Let's make it so the second option uses a `<ToggleGroupControl>` instead of a select given that it only offers two options. The two options can be renamed to: "Grayed-out" and "Hidden". The title could be: "Invalid options" and the description: "Control the display of invalid options." Something like this:

Image

## **To Reproduce**

1. Create a variable product with variations such that some combinations are missing.
2. Go to Appearance > Editor > Templates > Single Product.
3. Make sure your store is using the *Add to Cart + Options* block, switch to it otherwise.
4. Select the Variation Selector: Attribute Options block and see the sidebar options.

Image

### PR DESCRIPTION
**Pull request by AbdullahAymanMSRE**
### Submission Review Guidelines:

  - [x] I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and
   the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
  - [x] I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same
  update/change.
  - [x] I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
  - [x] Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

  ### Changes proposed in this Pull Request:

  This PR enhances the Variation Selector Attribute Options block settings UI for improved clarity and better user experience.

  **Changes include:**
  1. Moved away from PanelBody to ToolsPane as mentioned in #59464.
  2. Updated auto-select toggle label from "Auto-select when only one attribute is compatible" to "Auto-select when only one option is available".
  3. Converted the "Values in conflict with current selection" SelectControl to a ToggleGroupControl
  4. Renamed to "Invalid options" with clearer description
  5. Simplified option labels from "Grayed-out/crossed-out and disabled" to "Grayed-out"

  These changes make the settings more intuitive and consistent with modern WordPress block editor patterns.

  Closes #62863.

  ### Screenshots or screen recordings:

  | Before | After |
  | ------ | ----- |
  | image | image |

  ### How to test the changes in this Pull Request:

  Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions),
  include your detailed testing instructions:

  1. Create a variable product with variations such that some combinations are missing.
  2. Go to Appearance > Editor > Templates > Single Product.
  3. Make sure your store is using the Add to Cart + Options block, switch to it otherwise.
  4. Select the Variation Selector: Attribute Options block and see the sidebar options.
  5. Verify the following UI changes:
     - The auto-select toggle label reads "Auto-select when only one option is available"
     - The auto-select description is concise and clear
     - The invalid options control is a toggle group (not a dropdown)
     - The invalid options label reads "Invalid options"
     - The toggle options are "Grayed-out" and "Hidden"
  6. Test that both toggle controls work correctly and save settings properly
  7. Verify that existing blocks with saved settings continue to work without issues

  ### Testing that has already taken place:

  - Manual testing of the UI changes in the block editor
  - Verified backwards compatibility with existing saved block settings
  - Confirmed that attribute values ('hide', 'disable') remain unchanged for data compatibility

  ### Milestone

  - [x] Automatically assign milestone for the **[next WooCommerce version](../blob/trunk/plugins/woocommerce/woocommerce.php#L6)**

  ### Changelog entry

  - [ ] Automatically create a changelog entry from the details below.
  - [ ] This Pull Request does not require a changelog entry. (Comment required below)

  <details>

  <summary>Changelog Entry Details</summary>

  #### Significance

  - [x] Patch
  - [ ] Minor
  - [ ] Major

  #### Type

  - [ ] Fix - Fixes an existing bug
  - [ ] Add - Adds functionality
  - [ ] Update - Update existing functionality
  - [ ] Dev - Development related task
  - [ ] Tweak - A minor adjustment to the codebase
  - [ ] Performance - Address performance issues
  - [x] Enhancement - Improvement to existing functionality

  #### Message

  Updated Variation Selector Attribute Options block settings UI for improved clarity

  </details>

  <details>

  <summary>Changelog Entry Comment</summary>

  #### Comment

  </details>

### CODE REVIEW

File: plugins/woocommerce/client/blocks/assets/js/blocks/add-to-cart-with-options/variation-selector/attribute-options/edit.tsx [hunk 1]
```diff
@@ -96,83 +99,98 @@ export default function AttributeOptionsEdit(
...
+						>
+							<ToggleGroupControlOption
+								value="disable"
+								label={ __( 'Grayed-out', 'woocommerce' ) }
+							/>
+							<ToggleGroupControlOption
+								value="hide"
+								label={ __( 'Hidden', 'woocommerce' ) }
+							/>
+						</ToggleGroupControl>
```
Comment (dinhtungdu) [inline plugins/woocommerce/client/blocks/assets/js/blocks/add-to-cart-with-options/variation-selector/attribute-options/edit.tsx:215]: This should be in a separate Tools Panel Item

File: plugins/woocommerce/client/blocks/assets/js/blocks/add-to-cart-with-options/variation-selector/attribute-options/edit.tsx [hunk 2]
```diff
@@ -96,83 +99,98 @@ export default function AttributeOptionsEdit(
...
+							<ToggleGroupControlOption
+								value="dropdown"
+								label={ __( 'Dropdown', 'woocommerce' ) }
+							/>
+						</ToggleGroupControl>
+					</ToolsPanelItem>
+				</ToolsPanel>
+				<ToolsPanel
+					label={ __( 'Auto-select', 'woocommerce' ) }
+					resetAll={ () => setAttributes( { autoselect: false } ) }
```
Comment (dinhtungdu) [inline plugins/woocommerce/client/blocks/assets/js/blocks/add-to-cart-with-options/variation-selector/attribute-options/edit.tsx]: This misses handling for `disabledAttributesAction`.

**Review by dinhtungdu — DISMISSED** [review]
Thanks for the PR! I left some comments about the Tools Panel migration. The copy looks good to me and they're shorter/cleaner than before, so kudo on that 👍🏽 . Tagging @Aljullu as he works on the block and might see things we missed.

To Albert: Look like we need some notes/announcement on copy changes if this merge, right?

**Review by Aljullu — APPROVED** [review]
Thanks for the updates, @AbdullahAymanMSRE! This is testing well on my end, and code looks good!

Image
