### PR TITLE
Deprecate the $check_key_exists parameter from AssetDataRegistry and disallow duplicate data for all cases

### LINKED ISSUE #43404: CYS: When `WP_DEBUG` is enabled, the assembler is not loaded
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When `WP_DEBUG` is enabled, the assembler is not loaded. WordPress returns:
```
Uncaught Exception: Overriding existing data with an already registered key is not allowed
```

https://github.com/woocommerce/woocommerce/assets/4463174/472fafdd-f6a4-453a-aea4-2ef6a615c83e

### Expected behavior

With `WP_DEBUG` enabled, the assembler should load correctly.

### Actual behavior

-

### Steps to reproduce

1. Ensure that`WP_DEBUG` flag is enabled.
2. Ensure the WooCommerce Beta Tester plugin is installed and activated (available on this monorepo).
3. Head over to `/wp-admin/tools.php?page=woocommerce-admin-test-helper` and enable `customize-store` feature flag.
4. Head over to WooCommerce -> Home and click on "Start Customizing".
5. See the error.

### WordPress Environment

-

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by nefeline**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Currently, [AssetDataRegistry::add_data](https://github.com/woocommerce/woocommerce/blob/25d42b0c053c0b12db7401b5ec33b7c760a81fda/plugins/woocommerce/src/Blocks/Assets/AssetDataRegistry.php#L429) doesn't allow overriding existing data for a given key. 

Still, the only method that calls it, [AssetDataRegistry::add](https://github.com/woocommerce/woocommerce/blob/25d42b0c053c0b12db7401b5ec33b7c760a81fda/plugins/woocommerce/src/Blocks/Assets/AssetDataRegistry.php#L305), has an optional param `$check_key_exists` with the default value set to false, which in practice doesn't have any impact in the end results, as whenever set to false, no data is overridden: in this case we have an early return combined with a fatal error triggered exclusively whenever `WP_DEBUG` is set to TRUE.

This logic has caused us a few problems, and after internal discussion, which happened on pdnLyh-5U0-p2, **I'm proposing for us to deprecate the `$check_key_exists` parameter**, as if we allow data override, quoting @senadir : 

> The structure of that data is considered public API, allowing it to be overridden opens the risk to having mismatched expectations between frontend code that’s consuming it and what was modified with. This is magnified by the fact that we evolved from passing simple primitives to objects in wcSettings.

Porting over @samueljseay 's comment here as well:

> I also had a recent discussion in slack p1708450555264569/1708435510.631329-slack-C03CPM3UXDJ about this. In almost all cases we pass true to check key exists or we guard by checking if it exists before adding it. So I think we should as you say remove the param and always check or set the default to true. We could warn if the key exists, because it might be an indication your code is not working as expected?

Following Sam's suggestion, I've also updated the pre-existing logic that would throw a fatal exclusively whenever DEBUG is set to true to throw a PHP warning instead.

This is a change that should not have any impact on functionality, still, I'm tagging folks from the various teams to review this PR and test so we can confirm things are working as expected.

Closes #43404

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Ensure your WordPress install has `WP_DEBUG` [set to true](https://developer.wordpress.org/advanced-administration/debug/debug-wordpress/).
2. Access WooCommerce > Home > Customize Your Store > Start designing ( `wp-admin/admin.php?page=wc-admin&path=%2Fcustomize-store%2Fassembler-hub` )
3. Make sure you can access the pattern assembler without any problems: no fatal errors should be triggered.
4. Do a general smoke test including the Templates and the Cart, Mini-Cart, Checkout, Product Image, Product Collection, Reviews, and Filter blocks, and confirm that everything is working as expected: you should not see any warnings in your PHP error log.

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [x] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

Deprecate the $check_key_exists parameter from AssetDataRegistry and disallow duplicate data for all cases.

#### Comment 

</details>

### CODE REVIEW

**Review by senadir — COMMENTED** [review]
I'm approving initially on the premise of this PR, but there might be some unintended side-effect so let's wait and see if all tests pass.

**Review by wavvves — COMMENTED** [review]
There seems to be a related [test failure](https://github.com/woocommerce/woocommerce/actions/runs/8540886005/job/23399405244?pr=46139)

```
Time: 07:40.002, Memory: 305.00 MB

There was 1 error:

1) Automattic\WooCommerce\Tests\Blocks\Assets\AssetDataRegistry::test_invalid_key_on_adding_data
array_key_exists(): The first argument should be either a string or an integer

/var/www/html/wp-content/plugins/woocommerce/src/Blocks/Assets/AssetDataRegistry.php:288
/var/www/html/wp-content/plugins/woocommerce/src/Blocks/Assets/AssetDataRegistry.php:310
/var/www/html/wp-content/plugins/woocommerce/tests/php/src/Blocks/Assets/AssetDataRegistry.php:53
phpvfscomposer:///var/www/html/wp-content/plugins/woocommerce/vendor/phpunit/phpunit/phpunit:[106](https://github.com/woocommerce/woocommerce/actions/runs/8540886005/job/23399405244?pr=46139#step:5:107)

--

There was 1 failure:

1) Automattic\WooCommerce\Tests\Blocks\Assets\AssetDataRegistry::test_already_existing_key_on_adding_data
Failed asserting that exception of type "InvalidArgumentException" is thrown.
```

**Review by samueljseay — APPROVED** [review]
Apart from the need to update the unit tests this is looking good to me. Thanks for including the warnings too 🙇🏻

**Comment by nefeline** [comment]
I did some additional changes here to account for the fact that we are not throwing an exception anymore https://github.com/woocommerce/woocommerce/pull/46139/commits/627b911e64fa66d6d2e6d5b33aaf863c8bbe1a2e

Also, I've moved the call to $this->exists to the `add_data` method to ensure all validations happen at that level and resolve the failing test, which was throwing a type error on `array_key_exists` instead of the expected warning https://github.com/woocommerce/woocommerce/pull/46139/commits/1fcb81c38f8280cb4de587f46cd71c5ca963341c

@samueljseay would you help me out with a second review here? We want to open a CFE for this work, it would be great to have another final review here to confirm we are on track.

File: plugins/woocommerce/src/Blocks/Assets/AssetDataRegistry.php [hunk 1]
```diff
@@ -297,24 +297,15 @@ public function exists( $key ) {
...
-		}
-		try {
-			$this->add_data( $key, $data );
-		} catch ( Exception $e ) {
-			if ( $this->debug() ) {
-				// bubble up.
-				throw $e;
-			}
-			wc_caught_exception( $e, __METHOD__, [ $key, $data ] );
+		if ( $check_key_exists ) {
```
Comment (roykho) [inline plugins/woocommerce/src/Blocks/Assets/AssetDataRegistry.php:304]: For this since we're deprecating the parameter, what do you think if we check for `isset` instead. This way, the caller will get a deprecated feedback whether they passed 'true' or 'false' there.

Comment (nefeline) [reply plugins/woocommerce/src/Blocks/Assets/AssetDataRegistry.php:304]: > For this since we're deprecating the parameter, what do you think if we check for isset instead. This way, the caller will get a deprecated feedback whether they passed 'true' or 'false' there.

Thanks for the review @roykho. This is a good point, and I agree it makes sense to check for `isset`, but given the urgency of this work, I'd like to propose working on this as part of a separate PR so we can unblock the release. What do you think?

Comment (roykho) [reply plugins/woocommerce/src/Blocks/Assets/AssetDataRegistry.php:304]: Sure, if you don't mind please create a separate issue for it.

**Review by roykho — APPROVED** [review]
Left a comment which will be addressed at a later date. I've tested this PR with WP_DEBUG enabled and it fixes the fatal error. LGTM!

File: plugins/woocommerce/src/Blocks/Assets/AssetDataRegistry.php (hunk 1 above)
Comment (nefeline) [reply plugins/woocommerce/src/Blocks/Assets/AssetDataRegistry.php:304]: Thanks, absolutely! https://github.com/woocommerce/woocommerce/issues/46349
