### PR TITLE
Ensure stock change notifications only fire when necessary

### LINKED ISSUE #50958: "Product out of stock" email sent when stock quantity is not tracked
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

I think #49583 introduced a bug related to the "Product out of stock" email being sent when the stock quantity is not tracked.

Possible fix:
Maybe `wc_trigger_stock_change_actions()` should use the value of `manage_stock` and bail out if `false`.
Also, a test checking that no emails are sent in such case should be added.

### Expected behavior

If the stock quantity is not tracked for a given product, WooCommerce should not send a "Product out of stock" email.

### Actual behavior

WooCommerce sends a "Product out of stock" email for products not tracking the stock quantity.

### Steps to reproduce

1. Optional: install a plugin that logs emails.
2. Create a simple product and in `Inventory` => `Stock management`, do not tick `Track stock quantity for this product`.
3. Upon saving the product, the email is sent and can be listed in the email logs.

Can also be reproduced by doing `WC_Helper_Product::create_simple_product()` without arguments.

### WordPress Environment

This can be reproduced in #49583's WordPress Playground.

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by coreymckrill**
### Changes proposed in this Pull Request:

In #49583 we changed when the actions that trigger stock change notifications fire, to decouple them from order creation. However, it turns out what during product creation, the stock quantity update routines still run even when no stock is being set and even when the "manage stock" setting is set to false. Rather than try to untangle the web of why this happens (and potentially break other things in the process), this simply adds a check for the "manage stock" setting prior to firing the notif actions, and bail early if the product does not have managed stock.

It also adds a unit test, which is really more of an integration test, to ensure this behavior.

Fixes #50958

### How to test the changes in this Pull Request:

1. Install a plugin like [WP Mail Logging](https://wordpress.org/plugins/wp-mail-logging/) on your test site so you can capture outgoing emails.
2. Create a new simple product. Give it a price, but do _not_ check the box to manage inventory. Publish.
3. Check the mail log and ensure that no email notification was sent about the new product being out of stock.

### CODE REVIEW

File: plugins/woocommerce/tests/php/includes/wc-stock-functions-tests.php [hunk 1]
```diff
@@ -432,4 +432,28 @@ public function test_wc_update_product_stock_no_stock_action() {
...
+	public function test_wc_trigger_stock_change_actions_bails_early_for_unmanaged_stock() {
+		$action_fired = false;
+		$callback     = function () use ( &$action_fired ) {
+			$action_fired = true;
+		};
+		add_action( 'woocommerce_no_stock', $callback );
+
+		$product = WC_Helper_Product::create_simple_product();
+
+		$this->assertFalse( $action_fired );
```
Comment (naman03malhotra) [inline plugins/woocommerce/tests/php/includes/wc-stock-functions-tests.php:449]: Product creation takes care of firing the action, but perhaps we want to be more   explicit here, in case if the behaviour ever changes.
```suggestion
        $product->set_stock_quantity( 0 );
		$this->assertFalse( $action_fired );
```

File: plugins/woocommerce/tests/php/includes/wc-stock-functions-tests.php [hunk 2]
```diff
@@ -432,4 +432,28 @@ public function test_wc_update_product_stock_no_stock_action() {
...
+	 */
+	public function test_wc_trigger_stock_change_actions_bails_early_for_unmanaged_stock() {
+		$action_fired = false;
+		$callback     = function () use ( &$action_fired ) {
+			$action_fired = true;
+		};
+		add_action( 'woocommerce_no_stock', $callback );
+
+		$product = WC_Helper_Product::create_simple_product();
+
```
Comment (naman03malhotra) [inline plugins/woocommerce/tests/php/includes/wc-stock-functions-tests.php:448]: maybe we should also have `$product->set_manage_stock( false );`, because if the default assignment of `managed_stock` changed while product creation then this test will fail.

On second thought, that might also act as a deterrent to such a change.

**Review by naman03malhotra — COMMENTED** [review]
Tests well, left some comments about tests none of which are blocking in nature.

image

**Review by naman03malhotra — APPROVED** [review]
Since @coreymckrill is AFK, I am going to merge this PR to include this in RC for testing as the comments are not blocking. We can take care of the comments when Corey is back from AFK in a different PR.

File: plugins/woocommerce/tests/php/includes/wc-stock-functions-tests.php (hunk 2 above)
Comment (coreymckrill) [reply plugins/woocommerce/tests/php/includes/wc-stock-functions-tests.php:448]: Yeah, I think it's usually fine in tests to assume defaults, as that does offer some protection against inadvertently breaking backcompat by changing a default.
