### PR TITLE
Prevent skeleton display when express payment methods are active

### LINKED ISSUE #60362: Checkout block - Express payment components unmount when shipping rates updated, breaking PayPal checkout flow
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

**Summary:** Calling shippingData.setSelectedRates() in WooCommerce 10.1.0 causes express payment components to unmount and re-render, breaking the user experience for express payment methods like PayPal.

**Detailed Description:**
In WooCommerce versions prior to 10.1.0, express payment methods (such as PayPal) could reliably call shippingData.setSelectedRates() to synchronize shipping selections made within the payment method's own UI with the block checkout interface. This is a common pattern where express payment options provide their own address and shipping selection interface.

**Regression in 10.1.0:**
Starting with WooCommerce 10.1.0, calling shippingData.setSelectedRates() triggers an unmount and re-render of the express payment component. For payment methods like PayPal, this causes the payment window/modal to unexpectedly close, interrupting the customer's checkout flow.

**Impact:**
This breaks the checkout experience for customers using express payment methods, as any shipping option changes within the payment method's interface will close the payment window, forcing customers to restart the payment process.

**Confirmed Affected Plugins:**
WooCommerce PayPal Payments plugin

### Expected behavior

When `shippingData.setSelectedRates()` is called from within an express payment method (such as PayPal), the shipping rates should be updated in the block checkout without affecting the express payment component's lifecycle. 

Specifically:
- The express payment component should remain mounted and functional
- The payment window/modal should stay open and accessible to the customer
- Only the shipping-related data should be synchronized between the express payment method's UI and the block checkout
- The customer should be able to continue with their payment process seamlessly after making shipping option changes

This behavior should be consistent with how it functioned in WooCommerce versions prior to 10.1.0, where express payment methods could update shipping selections without disrupting the payment flow.

### Actual behavior

When `shippingData.setSelectedRates()` is called to update the selected shipping rate, the express checkout components are unmounted and then recreated. This unmount/remount cycle removes the express payment button elements from the DOM and replaces them with new instances.

For PayPal specifically, this DOM manipulation causes the PayPal payment popup to close abruptly because PayPal's payment popup maintains a dependency on the original button element remaining in the HTML throughout the popup's lifecycle. When the button element is removed from the DOM during the component unmount, PayPal's popup loses its connection and automatically closes.

This forces customers to restart the entire payment process, creating a frustrating user experience and potentially leading to cart abandonment.

### Steps to reproduce

1. Install the WooCommerce PayPal Payments plugin (https://wordpress.org/plugins/woocommerce-paypal-payments/)
2. Connect the plugin to a PayPal sandbox account
3. Add an item to the cart and navigate to the block-based checkout page
4. Click the PayPal button in the express checkout section
5. Once the PayPal popup opens, select a shipping option
6. Observe that the popup closes abruptly

**Expected result**: The PayPal popup should remain open after selecting a shipping option, allowing the customer to continue with the payment process.

**Actual result**: The PayPal popup closes immediately when a shipping option is selected, forcing the customer to restart the payment process.

### WordPress Environment

<details>

<summary>WordPress Environment</summary>

The System Status Report is found in your WordPress admin under **WooCommerce > Status**. 
Please select “Get system report”, then “Copy for GitHub”, and then paste it here.

</details>

### Isolating the problem

- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by ralucaStan**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

- We're only displaying Express Payments skeleton when an express payment isn't active to prevent the buttons to rerender. I've also added the fix to the cart block
- I've improved the a11y handling in both cases
- There is some duplication in place in the files, but those were there before [the PR](https://github.com/woocommerce/woocommerce/pull/59449) that introduced the bug. This duplication can be addressed outside of this PR

Closes https://github.com/woocommerce/woocommerce/issues/60362
Closes https://linear.app/a8c/issue/WOOPLUG-5315/checkout-block-express-payment-components-unmount-when-shipping-rates

(For Bug Fixes) Bug introduced in PR  https://github.com/woocommerce/woocommerce/pull/59449

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

If you want to use PayPal Payments in your local store
- Clone locally https://github.com/woocommerce/woocommerce-paypal-payments
- Go to WooCommerce > Payments > PayPal
- Go through setup wizzard
- Choose test sandbox
- Create a developer sandbox account [Instructions for the account here](https://github.com/woocommerce/woocommerce-paypal-payments/wiki/Testing-Setup) (don’t try to log in with personal account, that you use as a shopper)

## Checkout block
1. Go to Checkout block
2. Checkout using the Express PayPal
3. In the PayPal window do some address manipulation
4. Place the order without issues

## Cart block - will be handled separately
Progressive loading for Cart comes in 10.2; I'll update the logic in a separate before the feature freeze of 10.2

Optionally also repeat tests with Stripe, but the bug was not happening there.

### Testing that has already taken place:

I've updated the checkout testing with this case;
Added tests for the cart express area, there weren't any in place

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce/client/blocks/assets/js/blocks/cart-checkout-shared/payment-methods/express-payment/checkout-express-payment.tsx [hunk 1]
```diff
@@ -93,18 +102,18 @@ const CheckoutExpressPayment = () => {
...
-					isExpressPaymentMethodActive || checkoutProcessing
-				}
-				aria-busy={ checkoutProcessing }
+				aria-disabled={ checkoutProcessing }
 				aria-live="polite"
-				aria-label={ __(
-					'Processing express checkout',
-					'woocommerce'
-				) }
+				{ ...( checkoutProcessing && {
```
Comment (ralucaStan) [inline plugins/woocommerce/client/blocks/assets/js/blocks/cart-checkout-shared/payment-methods/express-payment/checkout-express-payment.tsx]: These were always displayed, I've improved the logic and added testing for it.

File: plugins/woocommerce/client/blocks/assets/js/blocks/cart-checkout-shared/payment-methods/express-payment/cart-express-payment.js [hunk 2]
```diff
@@ -50,6 +50,14 @@ const CartExpressPayment = () => {
 		registeredExpressPaymentMethods,
 	} );
 
+	// We show the skeleton when
+	// the express payment method is not active (because they trigger recalculations) and
+	// the checkout is calculating, because it can result in different express payment methods
+	// or when the express payment methods are not initialized
```
Comment (straku) [inline plugins/woocommerce/client/blocks/assets/js/blocks/cart-checkout-shared/payment-methods/express-payment/cart-express-payment.js:56]:
```suggestion
	// We show the skeleton when the express payment method is not active
	// (because they trigger recalculations) and the checkout is calculating,
	// because it can result in different express payment methods or when the
	// express payment methods are not initialized
```
Found the first line weirdly short, reflowed with claude

File: plugins/woocommerce/client/blocks/assets/js/blocks/cart-checkout-shared/payment-methods/express-payment/cart-express-payment.js [hunk 3]
```diff
@@ -50,6 +50,14 @@ const CartExpressPayment = () => {
...
+	const showSkeleton =
+		! isExpressPaymentMethodActive &&
+		( isCalculating || hasRegisteredNotInitializedExpressPaymentMethods );
```
Comment (ralucaStan) [inline plugins/woocommerce/client/blocks/assets/js/blocks/cart-checkout-shared/payment-methods/express-payment/cart-express-payment.js]: I'll actually remove isCalculating which is checkout specific and only include `hasPendingOperations`.
The only available actions in cart: quantity update & coupons. In checkout, we don't reload for coupons, so this simplifies things.

**Comment by ralucaStan** [comment]
I just realised that on 10.1 the Cart does not have progressive rendering. So I'll update this PR to only include the checkout changes, and create a separate PR for the Cart improvements.

**Review by opr — APPROVED** [review]
I tested this and it's working for me - the code changes look fine.

I also tested with Google Pay and Link from Stripe and verified that changing address there did not break the experience.
