### PR TITLE
Validate that tinymce exists before using it.

### LINKED ISSUE #34221: JS error on product save since 6.7.0
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Since WooCommerce 6.7.0, if I update a product I get the following JavaScript error:

```
post.php?post=78750&action=edit:4948 Uncaught TypeError: Cannot read properties of null (reading 'getContent')
    at HTMLInputElement.<anonymous> (post.php?post=78750&action=edit:4948:114)
    at HTMLInputElement.dispatch (jquery.min.js?ver=3.6.0:2:43064)
    at v.handle (jquery.min.js?ver=3.6.0:2:41048)
...
post.php?post=78750&action=edit:4948 Uncaught TypeError: Cannot read properties of null (reading 'getContent')
    at HTMLInputElement.<anonymous> (post.php?post=78750&action=edit:4948:114)
    at HTMLInputElement.dispatch (jquery.min.js?ver=3.6.0:2:43064)
    at v.handle (jquery.min.js?ver=3.6.0:2:41048)
    at Object.trigger (jquery.min.js?ver=3.6.0:2:71515)
    at HTMLInputElement.<anonymous> (jquery.min.js?ver=3.6.0:2:72110)
    at Function.each (jquery.min.js?ver=3.6.0:2:3003)
    at s.fn.init.each (jquery.min.js?ver=3.6.0:2:1481)
    at s.fn.init.trigger (jquery.min.js?ver=3.6.0:2:72086)
    at e.success (acf-input.min.js?ver=5.12.3:1:94404)
    at n.complete (acf-input.min.js?ver=5.12.3:1:95265)
```

The line that triggered the error (file: `class-wp-products-tracking.php`):

image

### Expected behavior

The product to update successfully.

### Actual behavior

A JavaScript exception is thrown that prevents the product from being updated.

### Steps to reproduce

1. Make sure WooCommerce 6.7.0 is installed
2. Edit an already existing product
3. Save the product

### WordPress Environment

```
### WordPress Environment ###

WordPress address (URL): <redacted>
Site address (URL): <redacted>
WC Version: 6.7.0
REST API Version: ✔ 6.7.0
WC Blocks Version: ✔ 7.8.3
Action Scheduler Version: ✔ 3.4.0
Log Directory Writable: ✔
WP Version: 6.0.1
WP Multisite: ✔
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_GB
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.54 (Unix) OpenSSL/1.1.1
PHP Version: 8.0.21
PHP Post Max Size: 256 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.58.0
OpenSSL/1.1.1

SUHOSIN Installed: –
MySQL Version: 10.2.44-MariaDB-1:10.2.44+maria~bionic-log
Max Upload Size: 256 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 6.7.0
WC Database Prefix: wp_
Total Database Size: 746.91MB
Database Data Size: 472.25MB
Database Index Size: 274.66MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 4.52MB + Index: 1.52MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 74.59MB + Index: 35.11MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.17MB + Index: 0.19MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_7_actionscheduler_actions: Data: 0.02MB + Index: 0.13MB + Engine InnoDB
wp_7_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_7_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_7_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_7_affiliate_wp_affiliatemeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_7_affiliate_wp_affiliates: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_7_affiliate_wp_campaigns: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_7_affiliate_wp_coupons: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_7_affiliate_wp_creatives: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_7_affiliate_wp_customermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_7_affiliate_wp_customers: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_7_affiliate_wp_payouts: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_7_affiliate_wp_referralmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_7_affiliate_wp_referrals: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_7_affiliate_wp_rest_consumers: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_7_affiliate_wp_sales: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_7_affiliate_wp_visits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_7_apto_sort_list: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_7_commentmeta: Data: 0.11MB + Index: 0.16MB + Engine InnoDB
wp_7_comments: Data: 3.52MB + Index: 1.55MB + Engine InnoDB
wp_7_followup_coupons: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_7_followup_coupon_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_7_followup_customers: Data: 0.09MB + Index: 0.17MB + Engine InnoDB
wp_7_followup_customer_carts: Data: 1.52MB + Index: 0.11MB + Engine InnoDB
wp_7_followup_customer_notes: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_7_followup_customer_orders: Data: 0.09MB + Index: 0.08MB + Engine InnoDB
wp_7_followup_email_excludes: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_7_followup_email_logs: Data: 0.42MB + Index: 0.31MB + Engine InnoDB
wp_7_followup_email_orders: Data: 1.52MB + Index: 0.61MB + Engine InnoDB
wp_7_followup_email_tracking: Data: 0.25MB + Index: 0.39MB + Engine InnoDB
wp_7_followup_followup_history: Data: 0.39MB + Index: 0.17MB + Engine InnoDB
wp_7_followup_order_categories: Data: 1.52MB + Index: 0.72MB + Engine InnoDB
wp_7_followup_order_items: Data: 0.28MB + Index: 0.45MB + Engine InnoDB
wp_7_followup_subscribers: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_7_followup_subscribers_to_lists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_7_followup_subscriber_lists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_7_gdpr_consent: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_7_gdpr_userlogs: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_7_gens_raf: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_7_gens_rafmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_7_gf_draft_submissions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_7_gf_entry: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_7_gf_entry_meta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_7_gf_entry_notes: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_7_gf_form: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_7_gf_form_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_7_gf_form_revisions: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_7_gf_form_view: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_7_gf_rest_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_7_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_7_mailchimp_carts: Data: 0.09MB + Index: 0.00MB + Engine InnoDB
wp_7_mailchimp_jobs: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
wp_7_mc4wp_log: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_7_options: Data: 4.52MB + Index: 3.03MB + Engine InnoDB
wp_7_pimwick_gift_card: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_7_pimwick_gift_card_activity: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_7_postmeta: Data: 33.56MB + Index: 14.03MB + Engine InnoDB
wp_7_posts: Data: 3.45MB + Index: 0.97MB + Engine InnoDB
wp_7_pys_stat_landing: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_7_pys_stat_order: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_7_pys_stat_product_order: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_7_pys_stat_traffic: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_7_pys_stat_utm_campaing: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_7_pys_stat_utm_content: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_7_pys_stat_utm_medium: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_7_pys_stat_utm_source: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_7_pys_stat_utm_term: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_7_termmeta: Data: 0.08MB + Index: 0.09MB + Engine InnoDB
wp_7_terms: Data: 0.16MB + Index: 0.17MB + Engine InnoDB
wp_7_term_relationships: Data: 0.22MB + Index: 0.16MB + Engine InnoDB
wp_7_term_taxonomy: Data: 0.16MB + Index: 0.17MB + Engine InnoDB
wp_7_tinvwl_analytics: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_7_tinvwl_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_7_tinvwl_lists: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_7_tinvwl_subscribers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_7_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_7_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_7_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_7_wc_customer_lookup: Data: 0.16MB + Index: 0.14MB + Engine InnoDB
wp_7_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_7_wc_order_coupon_lookup: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_7_wc_order_product_lookup: Data: 1.52MB + Index: 0.69MB + Engine InnoDB
wp_7_wc_order_stats: Data: 0.20MB + Index: 0.23MB + Engine InnoDB
wp_7_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_7_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_7_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_7_wc_product_meta_lookup: Data: 0.06MB + Index: 0.09MB + Engine InnoDB
wp_7_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_7_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_7_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_7_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_7_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_7_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_7_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_7_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_7_woocommerce_order_itemmeta: Data: 11.52MB + Index: 7.03MB + Engine InnoDB
wp_7_woocommerce_order_items: Data: 1.52MB + Index: 0.19MB + Engine InnoDB
wp_7_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_7_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_7_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_7_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_7_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_7_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_7_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_7_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_7_yith_wcwl: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_7_yith_wcwl_lists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_7_yoast_indexable: Data: 2.52MB + Index: 0.81MB + Engine InnoDB
wp_7_yoast_indexable_hierarchy: Data: 0.08MB + Index: 0.14MB + Engine InnoDB
wp_7_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_7_yoast_primary_term: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_7_yoast_prominent_words: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_7_yoast_seo_links: Data: 0.16MB + Index: 0.13MB + Engine InnoDB
wp_7_yoast_seo_meta: Data: 0.20MB + Index: 0.00MB + Engine InnoDB
wp_8_actionscheduler_actions: Data: 0.02MB + Index: 0.13MB + Engine InnoDB
wp_8_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_8_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_8_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_8_affiliate_wp_affiliatemeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_8_affiliate_wp_affiliates: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_8_affiliate_wp_campaigns: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_8_affiliate_wp_coupons: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_8_affiliate_wp_creatives: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_8_affiliate_wp_customermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_8_affiliate_wp_customers: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_8_affiliate_wp_payouts: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_8_affiliate_wp_referralmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_8_affiliate_wp_referrals: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_8_affiliate_wp_rest_consumers: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_8_affiliate_wp_sales: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_8_affiliate_wp_visits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_8_apto_sort_list: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_8_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_8_comments: Data: 0.36MB + Index: 0.33MB + Engine InnoDB
wp_8_followup_coupons: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_8_followup_coupon_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_8_followup_customers: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_8_followup_customer_carts: Data: 0.14MB + Index: 0.03MB + Engine InnoDB
wp_8_followup_customer_notes: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_8_followup_customer_orders: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_8_followup_email_excludes: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_8_followup_email_logs: Data: 0.11MB + Index: 0.05MB + Engine InnoDB
wp_8_followup_email_orders: Data: 0.34MB + Index: 0.13MB + Engine InnoDB
wp_8_followup_email_tracking: Data: 0.09MB + Index: 0.08MB + Engine InnoDB
wp_8_followup_followup_history: Data: 0.14MB + Index: 0.05MB + Engine InnoDB
wp_8_followup_order_categories: Data: 0.11MB + Index: 0.14MB + Engine InnoDB
wp_8_followup_order_items: Data: 0.06MB + Index: 0.05MB + Engine InnoDB
wp_8_followup_subscribers: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_8_followup_subscribers_to_lists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_8_followup_subscriber_lists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_8_gdpr_consent: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_8_gdpr_userlogs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_8_gens_raf: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_8_gens_rafmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_8_gf_draft_submissions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_8_gf_entry: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_8_gf_entry_meta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_8_gf_entry_notes: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_8_gf_form: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_8_gf_form_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_8_gf_form_revisions: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_8_gf_form_view: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_8_gf_rest_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_8_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_8_mailchimp_carts: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_8_mailchimp_jobs: Data: 0.13MB + Index: 0.00MB + Engine InnoDB
wp_8_mc4wp_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_8_options: Data: 2.45MB + Index: 0.44MB + Engine InnoDB
wp_8_pimwick_gift_card: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_8_pimwick_gift_card_activity: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_8_postmeta: Data: 23.56MB + Index: 6.03MB + Engine InnoDB
wp_8_posts: Data: 2.52MB + Index: 0.77MB + Engine InnoDB
wp_8_pys_stat_landing: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_8_pys_stat_order: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_8_pys_stat_product_order: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_8_pys_stat_traffic: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_8_pys_stat_utm_campaing: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_8_pys_stat_utm_content: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_8_pys_stat_utm_medium: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_8_pys_stat_utm_source: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_8_pys_stat_utm_term: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_8_termmeta: Data: 0.08MB + Index: 0.09MB + Engine InnoDB
wp_8_terms: Data: 0.16MB + Index: 0.16MB + Engine InnoDB
wp_8_term_relationships: Data: 0.22MB + Index: 0.17MB + Engine InnoDB
wp_8_term_taxonomy: Data: 0.16MB + Index: 0.17MB + Engine InnoDB
wp_8_tinvwl_analytics: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_8_tinvwl_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_8_tinvwl_lists: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_8_tinvwl_subscribers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_8_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_8_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_8_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_8_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_8_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_8_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_8_wc_order_product_lookup: Data: 0.13MB + Index: 0.16MB + Engine InnoDB
wp_8_wc_order_stats: Data: 0.05MB + Index: 0.05MB + Engine InnoDB
wp_8_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_8_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_8_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_8_wc_product_meta_lookup: Data: 0.06MB + Index: 0.09MB + Engine InnoDB
wp_8_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_8_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_8_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_8_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_8_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_8_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_8_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_8_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_8_woocommerce_order_itemmeta: Data: 2.52MB + Index: 1.88MB + Engine InnoDB
wp_8_woocommerce_order_items: Data: 0.13MB + Index: 0.06MB + Engine InnoDB
wp_8_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_8_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_8_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_8_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_8_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_8_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_8_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_8_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_8_yith_wcwl: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_8_yith_wcwl_lists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_8_yoast_indexable: Data: 0.48MB + Index: 0.19MB + Engine InnoDB
wp_8_yoast_indexable_hierarchy: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_8_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_8_yoast_primary_term: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_8_yoast_prominent_words: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_8_yoast_seo_links: Data: 0.14MB + Index: 0.11MB + Engine InnoDB
wp_8_yoast_seo_meta: Data: 0.14MB + Index: 0.00MB + Engine InnoDB
wp_9_actionscheduler_actions: Data: 0.02MB + Index: 0.13MB + Engine InnoDB
wp_9_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_9_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_9_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_9_affiliate_wp_affiliatemeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_9_affiliate_wp_affiliates: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_9_affiliate_wp_campaigns: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_9_affiliate_wp_coupons: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_9_affiliate_wp_creatives: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_9_affiliate_wp_customermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_9_affiliate_wp_customers: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_9_affiliate_wp_payouts: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_9_affiliate_wp_referralmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_9_affiliate_wp_referrals: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_9_affiliate_wp_rest_consumers: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_9_affiliate_wp_sales: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_9_affiliate_wp_visits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_9_apto_sort_list: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_9_commentmeta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_9_comments: Data: 1.52MB + Index: 0.80MB + Engine InnoDB
wp_9_followup_coupons: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_9_followup_coupon_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_9_followup_customers: Data: 0.06MB + Index: 0.09MB + Engine InnoDB
wp_9_followup_customer_carts: Data: 1.52MB + Index: 0.09MB + Engine InnoDB
wp_9_followup_customer_notes: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_9_followup_customer_orders: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_9_followup_email_excludes: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_9_followup_email_logs: Data: 0.28MB + Index: 0.22MB + Engine InnoDB
wp_9_followup_email_orders: Data: 1.52MB + Index: 0.44MB + Engine InnoDB
wp_9_followup_email_tracking: Data: 0.20MB + Index: 0.30MB + Engine InnoDB
wp_9_followup_followup_history: Data: 0.34MB + Index: 0.14MB + Engine InnoDB
wp_9_followup_order_categories: Data: 0.36MB + Index: 0.42MB + Engine InnoDB
wp_9_followup_order_items: Data: 0.19MB + Index: 0.28MB + Engine InnoDB
wp_9_followup_subscribers: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_9_followup_subscribers_to_lists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_9_followup_subscriber_lists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_9_gdpr_consent: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_9_gdpr_userlogs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_9_gens_raf: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_9_gens_rafmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_9_gf_draft_submissions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_9_gf_entry: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_9_gf_entry_meta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_9_gf_entry_notes: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_9_gf_form: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_9_gf_form_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_9_gf_form_revisions: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_9_gf_form_view: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_9_gf_rest_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_9_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_9_mailchimp_carts: Data: 0.20MB + Index: 0.00MB + Engine InnoDB
wp_9_mailchimp_jobs: Data: 0.42MB + Index: 0.00MB + Engine InnoDB
wp_9_mc4wp_log: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_9_options: Data: 3.52MB + Index: 2.88MB + Engine InnoDB
wp_9_pimwick_gift_card: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_9_pimwick_gift_card_activity: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_9_postmeta: Data: 29.56MB + Index: 10.03MB + Engine InnoDB
wp_9_posts: Data: 2.52MB + Index: 0.89MB + Engine InnoDB
wp_9_pys_stat_landing: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_9_pys_stat_order: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_9_pys_stat_product_order: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_9_pys_stat_traffic: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_9_pys_stat_utm_campaing: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_9_pys_stat_utm_content: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_9_pys_stat_utm_medium: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_9_pys_stat_utm_source: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_9_pys_stat_utm_term: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_9_termmeta: Data: 0.08MB + Index: 0.09MB + Engine InnoDB
wp_9_terms: Data: 0.16MB + Index: 0.16MB + Engine InnoDB
wp_9_term_relationships: Data: 0.22MB + Index: 0.14MB + Engine InnoDB
wp_9_term_taxonomy: Data: 0.16MB + Index: 0.17MB + Engine InnoDB
wp_9_tinvwl_analytics: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_9_tinvwl_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_9_tinvwl_lists: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_9_tinvwl_subscribers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_9_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_9_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_9_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_9_wc_customer_lookup: Data: 0.13MB + Index: 0.11MB + Engine InnoDB
wp_9_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_9_wc_order_coupon_lookup: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_9_wc_order_product_lookup: Data: 0.41MB + Index: 0.44MB + Engine InnoDB
wp_9_wc_order_stats: Data: 0.13MB + Index: 0.11MB + Engine InnoDB
wp_9_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_9_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_9_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_9_wc_product_meta_lookup: Data: 0.06MB + Index: 0.09MB + Engine InnoDB
wp_9_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_9_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_9_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_9_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_9_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_9_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_9_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_9_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_9_woocommerce_order_itemmeta: Data: 7.52MB + Index: 5.03MB + Engine InnoDB
wp_9_woocommerce_order_items: Data: 0.38MB + Index: 0.13MB + Engine InnoDB
wp_9_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_9_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_9_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_9_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_9_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_9_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_9_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_9_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_9_yoast_indexable: Data: 1.52MB + Index: 0.34MB + Engine InnoDB
wp_9_yoast_indexable_hierarchy: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_9_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_9_yoast_primary_term: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_9_yoast_prominent_words: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_9_yoast_seo_links: Data: 0.14MB + Index: 0.11MB + Engine InnoDB
wp_9_yoast_seo_meta: Data: 0.16MB + Index: 0.00MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.05MB + Index: 0.13MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_affiliate_wp_affiliatemeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_affiliate_wp_affiliates: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_affiliate_wp_campaigns: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_affiliate_wp_coupons: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_affiliate_wp_creatives: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_affiliate_wp_customermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_affiliate_wp_customers: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_affiliate_wp_payouts: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_affiliate_wp_referralmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_affiliate_wp_referrals: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_affiliate_wp_rest_consumers: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_affiliate_wp_sales: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_affiliate_wp_visits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_apto_sort_list: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_blogmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_blogs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_blog_versions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_commentmeta: Data: 0.14MB + Index: 0.17MB + Engine InnoDB
wp_comments: Data: 14.52MB + Index: 10.09MB + Engine InnoDB
wp_followup_coupons: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_coupon_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_customers: Data: 0.39MB + Index: 0.77MB + Engine InnoDB
wp_followup_customer_carts: Data: 3.52MB + Index: 0.53MB + Engine InnoDB
wp_followup_customer_notes: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_customer_orders: Data: 0.44MB + Index: 0.25MB + Engine InnoDB
wp_followup_email_excludes: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_email_logs: Data: 3.52MB + Index: 3.39MB + Engine InnoDB
wp_followup_email_orders: Data: 10.52MB + Index: 6.80MB + Engine InnoDB
wp_followup_email_tracking: Data: 2.52MB + Index: 2.70MB + Engine InnoDB
wp_followup_followup_history: Data: 3.52MB + Index: 0.72MB + Engine InnoDB
wp_followup_order_categories: Data: 3.52MB + Index: 5.03MB + Engine InnoDB
wp_followup_order_items: Data: 2.52MB + Index: 4.55MB + Engine InnoDB
wp_followup_subscribers: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_subscribers_to_lists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_subscriber_lists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gdpr_consent: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gdpr_userlogs: Data: 3.52MB + Index: 0.00MB + Engine InnoDB
wp_gens_raf: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gens_rafmeta: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_gf_draft_submissions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_gf_entry: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gf_entry_meta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_gf_entry_notes: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gf_form: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gf_form_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gf_form_revisions: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gf_form_view: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gf_rest_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailchimp_carts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailchimp_jobs: Data: 5.52MB + Index: 0.00MB + Engine InnoDB
wp_mc4wp_log: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
wp_mpd_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 12.34MB + Index: 10.06MB + Engine InnoDB
wp_pimwick_gift_card: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_pimwick_gift_card_activity: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_postmeta: Data: 82.63MB + Index: 47.16MB + Engine InnoDB
wp_posts: Data: 10.45MB + Index: 3.66MB + Engine InnoDB
wp_pys_stat_landing: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pys_stat_order: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pys_stat_product_order: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pys_stat_traffic: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pys_stat_utm_campaing: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pys_stat_utm_content: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pys_stat_utm_medium: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pys_stat_utm_source: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pys_stat_utm_term: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_redirection_404: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_redirection_groups: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_redirection_items: Data: 0.05MB + Index: 0.09MB + Engine InnoDB
wp_redirection_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_registration_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_signups: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_site: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_sitemeta: Data: 1.06MB + Index: 0.03MB + Engine InnoDB
wp_smush_dir_images: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_termmeta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.42MB + Index: 0.55MB + Engine InnoDB
wp_term_relationships: Data: 0.33MB + Index: 0.31MB + Engine InnoDB
wp_term_taxonomy: Data: 0.39MB + Index: 0.41MB + Engine InnoDB
wp_tinvwl_analytics: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_tinvwl_items: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_tinvwl_lists: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_usermeta: Data: 38.56MB + Index: 39.14MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_vo_broadcaster_post_relations: Data: 0.20MB + Index: 0.00MB + Engine InnoDB
wp_vo_log_records: Data: 1.48MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 1.52MB + Index: 0.81MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.20MB + Index: 0.27MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 4.52MB + Index: 6.06MB + Engine InnoDB
wp_wc_order_stats: Data: 1.52MB + Index: 0.75MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.06MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wmcc_relationships: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpgdprc_access_requests: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpgdprc_consents: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpgdprc_delete_requests: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpgdprc_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wsal_metadata: Data: 7.52MB + Index: 14.02MB + Engine InnoDB
wp_wsal_occurrences: Data: 0.42MB + Index: 0.67MB + Engine InnoDB
wp_yith_wcwl: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yith_wcwl_lists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_yoast_indexable: Data: 4.52MB + Index: 3.08MB + Engine InnoDB
wp_yoast_indexable_hierarchy: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_primary_term: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_yoast_prominent_words: Data: 0.09MB + Index: 0.09MB + Engine InnoDB
wp_yoast_seo_links: Data: 0.31MB + Index: 0.17MB + Engine InnoDB
wp_yoast_seo_meta: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
wp__3wp_broadcast_broadcastdata: Data: 0.42MB + Index: 0.08MB + Engine InnoDB

### Post Type Counts ###

acf-field: 78
apto_sort: 58
attachment: 1975
awards: 10
dummy: 3034
follow_up_email: 3
ingredients: 23
mc4wp-form: 1
nav_menu_item: 66
oembed_cache: 24
page: 42
post: 278
press: 145
product: 199
product_variation: 31
revision: 564
shop_coupon: 143
shop_order: 8583
shop_order_refund: 142
stockists: 19
wishlist: 24
wp_global_styles: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (51) ###

Advanced Custom Fields PRO: by Delicious Brains – 5.12.3
Giftable for WooCommerce: by Decom – 1.0.5
Mailchimp for WooCommerce: by Mailchimp – 2.7.2
MC4WP: Mailchimp for WordPress: by ibericode – 4.8.7
MC4WP: Mailchimp for WordPress Premium: by ibericode – 4.9
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 3.1.5
TI WooCommerce Wishlist: by TemplateInvaders – 1.47.0
Advanced Order Export For WooCommerce: by AlgolPlus – 3.3.1
WPC Product Bundles for WooCommerce (Premium): by WPClever – 6.3.6
WooCommerce Extended Coupon Features PRO: by Soft79 – 3.0.6
WooCommerce: by Automattic – 6.7.0
WordPress Importer: by wordpressdotorg – 0.7
Yoast SEO Premium: by Team Yoast – 15.3
Refer a Friend for WooCommerce PREMIUM: by WPGens – 2.3.2
WPMU DEV Dashboard: by WPMU DEV – 4.11.14
Advanced Custom Fields PRO: by Delicious Brains – 5.12.3
Advanced Order Export For WooCommerce: by AlgolPlus – 3.3.1
MC4WP: Mailchimp for WordPress: by ibericode – 4.8.7
MC4WP: Mailchimp for WordPress Premium: by ibericode – 4.9
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 3.1.5
WooCommerce Extended Coupon Features PRO: by Soft79 – 3.0.6
Preview E-mails for WooCommerce: by Digamber Pradhan – 2.0.3
Yoast SEO Premium: by Team Yoast – 15.3
Export Users to CSV: by Boopathi Rajan – 1.3.2
ACF Content Analysis for Yoast SEO: by Thomas Kräftner
ViktorFroberg
marol87
pekz0r
angrycreative
Team Yoast – 3.0.1

MailChimp User Sync: by ibericode – 1.7.7
Follow-Up Emails: by WooCommerce – 4.9.26
PW WooCommerce Gift Cards Pro: by Pimwick
LLC – 1.403

Cookie Information | Free WP GDPR Consent Plugin: by Cookie Information – 2.0.18
Smush Pro: by WPMU DEV – 3.10.3
Send E-mails with Mandrill: by Miller Media ( Matt Miller ) – 1.3
Mailchimp for WooCommerce: by Mailchimp – 2.7.2
GTM4WP: by Thomas Geiger – 1.16.1
ManageWP - Worker: by GoDaddy – 4.9.14
WPC Product Bundles for WooCommerce (Premium): by WPClever – 6.3.6
What The File: by Never5 – 1.5.4
Gravity Forms: by Gravity Forms – 2.6.4
WooCommerce: by Automattic – 6.7.0
Giftable for WooCommerce: by Decom – 1.0.5
PixelYourSite PRO: by PixelYourSite – 9.2.1
Ajax add to cart for WooCommerce: by QuadLayers – 1.3.1
WooCommerce Product Stock Alert: by WC Marketplace – 1.7.5
WP Crontrol: by John Blackbourn & contributors – 1.14.0
AffiliateWP: by AffiliateWP – 2.9.4
Custom field finder: by Team Yoast – 0.3
Payment Plugins Braintree For WooCommerce: by Payment Plugins
support@paymentplugins.com – 3.2.37

Redirection: by John Godley – 5.3.1
Akismet Anti-Spam: by Automattic – 5.0
Simple Custom Post Order: by Colorlib – 2.5.6
Yoast Duplicate Post: by Enrico Battocchi and Team Yoast – 4.5
PixelYourSite Super Pack: by PixelYourSite – 3.0.7

### Inactive Plugins (6) ###

CDN Enabler: by KeyCDN – 2.0.5
Facebook for WooCommerce: by Facebook – 2.6.19
Warpdrive: by Savvii – 2.10.2
WebP Express: by Bjørn Rosell – 0.25.5
WP Activity Log: by WP White Security – 4.4.2.1
Yoast SEO: by Team Yoast – 19.4

### Dropin Plugins (1) ###

advanced-cache.php: advanced-cache.php

### Settings ###

API Enabled: –
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: dgfw_gift (dgfw_gift)
external (external)
grouped (grouped)
pw gift card (pw-gift-card)
simple (simple)
variable (variable)
woosb (woosb)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: –

### WC Pages ###

Shop base: #65109 - /test-shop/
Basket: #21 - /bag/
Checkout: #22 - /checkout/
My account: #23 - /account/
Terms and conditions: #10 - /terms-conditions/

### Theme ###

Name: Van Ons Theme
Version: 3.0.1
Author URL: <redacted>
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build
personally we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: vo-theme/woocommerce/cart/cart-shipping.php
vo-theme/woocommerce/checkout/payment-method.php version - is out of date. The core version is 3.5.0
vo-theme/woocommerce/checkout/thankyou.php version - is out of date. The core version is 3.7.0
vo-theme/woocommerce/emails/customer-new-account.php version - is out of date. The core version is 6.0.0
vo-theme/woocommerce/emails/email-footer.php version - is out of date. The core version is 3.7.0
vo-theme/woocommerce/emails/email-header.php version - is out of date. The core version is 4.0.0
vo-theme/woocommerce/emails/email-order-details.php version - is out of date. The core version is 3.7.0
vo-theme/woocommerce/emails/email-order-items.php version - is out of date. The core version is 3.7.0
vo-theme/woocommerce/emails/email-styles.php version - is out of date. The core version is 4.0.0
vo-theme/woocommerce/myaccount/dashboard.php

Outdated Templates: ❌
					
					
						Learn how to update

### Pimwick Plugins ###

PW WooCommerce Gift Cards Pro: License key: <redacted>
Result: success
Cached: 2022-08-08


### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
experimental-products-task
experimental-import-products-task
experimental-fashion-sample-products
experimental-product-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
wc-pay-promotion
wc-pay-welcome-page
wc-pay-subscriptions-page

Disabled Features: minified-js
settings

Daily Cron: ✔ Next scheduled: 2022-08-09 07:24:43 +01:00
Options: ✔
Notes: 23
Onboarding: completed

### TI WooCommerce Wishlist Templates ###

Overrides: –

### Action Scheduler ###

Complete: 68
Oldest: 2022-07-11 15:42:34 +0100
Newest: 2022-08-08 08:40:37 +0100

Failed: 5
Oldest: 2020-10-09 15:04:39 +0100
Newest: 2020-10-09 15:04:39 +0100

Pending: 4
Oldest: 2022-08-09 05:38:32 +0100
Newest: 2022-08-12 07:20:41 +0100


### Status report information ###

Generated at: 2022-08-08 08:55:53 +01:00
```

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by mdperez86**
If wp is not configured to use blocks and the tinymce was changed by a different editor then the error happends because tinymce is required. Applying a validation that makes sure tinymce exists before using it solves the problem. But this introduces a new problem, the description property will be send with value 'No' when event 'product_update' will be fired.
What do you thing about this @pmcpinto? We can implement a more specific code to consider tracking some kind of error messega or flag that tell us the customer is not using tinymce or blocks. Or it's no necesary to spend more time on this considering this page is gonna be replaced by the new experience.

### All Submissions:

-   [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
-   [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
-   [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes #34221 .

### How to test the changes in this Pull Request:

1. Go to All Products
2. Click on edit link of any product
3. In Edit product page, change the description of the product.
4. Open the DevTools Console in your borwser and type `delete tinymce`
5. Then click Update button
6. The product description should be saved succesfully without any error
7. The `product_update` event should be sent with `desciption: 'No'`

### Other information:

-   [x] Have you added an explanation of what your changes do and why you'd like us to include them?
-   [x] Have you written new tests for your changes, as applicable?
-   [x] Have you successfully run tests with your changes locally?
-   [x] Have you created a changelog file for each project being changed, ie `pnpm changelog add --filter=<project>`?

### FOR PR REVIEWER ONLY:

-   [x] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

**Review by octaedro — DISMISSED** [review]
Great job @mdperez86! This is testing well on my end and the code looks really good 🚀

File: plugins/woocommerce/includes/tracks/events/class-wc-products-tracking.php [hunk 1]
```diff
@@ -152,7 +152,11 @@ public function track_product_updated_client_side( $post ) {
 
 					if ( ! isBlockEditor ) {
 						tagsText          = $( '[name=\"tax_input[product_tag]\"]' ).val();
-						description_value  = $( '#content' ).is( ':visible' ) ? $( '#content' ).val() : tinymce.get( 'content' ).getContent();
+						if ( $( '#content' ).is( ':visible' ) ) {
+							description_value = $( '#content' ).val();	
+						} else if ( typeof tinymce === 'object' ) {
```
Comment (louwie17) [inline plugins/woocommerce/includes/tracks/events/class-wc-products-tracking.php]: Sorry for the quick double check here, but I think we also want to add this condition `tinymce.get( 'content' )`
The way the error read in the original issue, made it sound like that `tinymce.get( 'content' )` was actually returning  `null` and `tinymce` was available.
But I think the `tinymce` check is still helpful.

**Review by louwie17 — CHANGES_REQUESTED** [review]
Sorry for the double check here, but I did leave one comment on adding an extra condition.

File: plugins/woocommerce/includes/tracks/events/class-wc-products-tracking.php (hunk 1 above)
Comment (mdperez86) [reply plugins/woocommerce/includes/tracks/events/class-wc-products-tracking.php]: Great point @louwie17 thanks for your advice. Could you take a look now please?

**Review by louwie17 — DISMISSED** [review]
Thanks for adding the extra condition @mdperez86, nice work, this tested well and code looks good :)

**Review by louwie17 — APPROVED** [review]
Things still look good after rebase.
