### PR TITLE
Validate missing fields in Store API

### LINKED ISSUE #45496: Checkout Additional fields not validated if required in Store API
When you have a required custom field in contact or additional, it doesn't get validated when you place a Store API order and it seems to be ignored.

### Steps to reproduce:

- Add the following field via code:
```php
add_action(
	'woocommerce_loaded',
	function() {
		__experimental_woocommerce_blocks_register_checkout_field(
			array(
				'id'       => 'plugin-namespace/job-function',
				'label'    => 'What is your main role at your company?',
				'location' => 'contact',
				'required' => true,
				'type'     => 'text'
			)
		);
	}
);
```
- In a REST client, add an item to cart, then head to Checkout and place the following the order:
```json
{
	"billing_address": {
		"first_name": "test",
		"last_name": "test",
		"company": "",
		"address_1": "test",
		"address_2": "",
		"city": "test",
		"state": "",
		"postcode": "cb241ab",
		"country": "GB",
		"phone": "",
		"email": "testaccount@test.com"
	},
	"shipping_address": {
		"first_name": "test",
		"last_name": "test",
		"company": "",
		"address_1": "test",
		"address_2": "",
		"city": "test",
		"state": "",
		"postcode": "cb241ab",
		"country": "GB",
		"phone": ""
	},
	"payment_method": "bacs",
	"additional_fields": []
}
```
- Notice that you can place an order just fine, regardless if `plugin-namespace/job-function` is required or not.

### Expected behavior
The order placing should reject.

### PR DESCRIPTION
**Pull request by senadir**
### Changes proposed in this Pull Request:

In additional fields, we would only validate passed fields, this means required missing fields would not get validated, this fixes it and enable the test for it.

Closes https://github.com/woocommerce/woocommerce/issues/45496

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Tests should pass.
2. Add the following snippet to your store
```php
add_action(
	'woocommerce_loaded',
	function () {
		__experimental_woocommerce_blocks_register_checkout_field(
			array(
				'id'       => 'plugin-namespace/job-function',
				'label'    => 'What is your main role at your company?',
				'location' => 'additional',
				'required' => true,
				'type'     => 'text',
			)
		);
	}
);
```
3. Send this request to Store API after adding to cart:
```json
{
	"billing_address": {
		"first_name": "test",
		"last_name": "test",
		"company": "",
		"address_1": "test",
		"address_2": "",
		"city": "test",
		"state": "",
		"postcode": "cb241ab",
		"country": "GB",
		"phone": "",
		"email": "testaccount@test.com"
	},
	"shipping_address": {
		"first_name": "test",
		"last_name": "test",
		"company": "",
		"address_1": "test",
		"address_2": "",
		"city": "test",
		"state": "",
		"postcode": "cb241ab",
		"country": "GB",
		"phone": ""
	},
	"payment_method": "bacs",
	"additional_fields": {}
}
```
4. You should get an error saying the field is missing or not the correct type.

### CODE REVIEW

File: plugins/woocommerce/src/Blocks/Domain/Services/CheckoutFields.php [hunk 1]
```diff
@@ -38,7 +38,7 @@ class CheckoutFields {
 	 *
```
Comment (senadir) [inline plugins/woocommerce/src/Blocks/Domain/Services/CheckoutFields.php]: This file has no changes.

File: plugins/woocommerce/src/StoreApi/Schemas/V1/CheckoutSchema.php [hunk 2]
```diff
@@ -383,12 +383,14 @@ public function validate_additional_fields( $fields, $request ) {
 		$fields                  = $this->sanitize_additional_fields( $fields );
 		$additional_field_schema = $this->get_additional_fields_schema();
```
Comment (senadir) [inline plugins/woocommerce/src/StoreApi/Schemas/V1/CheckoutSchema.php:385]: Changes are starting from here.

**Review by wavvves — APPROVED** [review]
LGTM 👍🏼
