### PR TITLE
WC_Data: Throw an exception when attempting to parse an invalid date format

### LINKED ISSUE #58401: REST API orders GET with coupons has TypeError: preg_match Argument 2 must be of type string stdClass given abstract-wc-data.php:910
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

I can reproduce this in dev sandbox with a default theme and only WooCommerce active. I must set-up a set of Woo REST API keys and use Postman App to query GET `https://sandbox.local/wp-json/wc/v3/orders?include=56450&per_page=50&consumer_key=ck_REDACTED&consumer_secret=cs_REDACTED`

Klaviyo reported this 500 issue to me. From what I can tell it mostly affects older orders that contain a coupon line item. Indeed getting the coupon date_created is in the stack trace.

Noting here that the coupon in question has email addresses cached into the order item meta - has the per-customer restriction.

### Expected behavior

I expect the REST API request to work or result in an error message, not crash.

### Actual behavior

500 error / crash. Here's the details:

```
2025-05-28T17:59:44+00:00 Critical Uncaught TypeError: preg_match(): Argument #2 ($subject) must be of type string, stdClass given in /nas/content/live/REDACTED/wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-data.php:910  
Additional context
{
    "error": {
        "type": 1,
        "file": "/wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-data.php",
        "line": 910
    },
    "remote-logging": true,
    "backtrace": [
        "",
        "#0 /wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-data.php(910): preg_match('/^(\\d{4})-(\\d{2...', Object(stdClass), NULL)",
        "#1 /wp-content/plugins/woocommerce/includes/class-wc-coupon.php(596): WC_Data->set_date_prop('date_created', Object(stdClass))",
        "#2 /wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-data.php(799): WC_Coupon->set_date_created(Object(stdClass))",
        "#3 /wp-content/plugins/woocommerce/includes/rest-api/Controllers/Version2/class-wc-rest-orders-v2-controller.php(303): WC_Data->set_props(Array)",
        "#4 [internal function]: WC_REST_Orders_V2_Controller->get_order_item_data(Object(WC_Order_Item_Coupon))",
        "#5 /wp-content/plugins/woocommerce/includes/rest-api/Controllers/Version2/class-wc-rest-orders-v2-controller.php(477): array_map(Array, Array)",
        "#6 /wp-content/plugins/woocommerce/includes/rest-api/Controllers/Version2/class-wc-rest-orders-v2-controller.php(574): WC_REST_Orders_V2_Controller->get_formatted_item_data(Object(Automattic\WooCommerce\Admin\Overrides\Order))",
        "#7 /wp-content/plugins/woocommerce/includes/rest-api/Controllers/Version3/class-wc-rest-orders-controller.php(438): WC_REST_Orders_V2_Controller->prepare_object_for_response_core(Object(Automattic\WooCommerce\Admin\Overrides\Order), Object(WP_REST_Request))",
        "#8 /wp-content/plugins/woocommerce/includes/rest-api/Controllers/Version2/class-wc-rest-orders-v2-controller.php(542): WC_REST_Orders_Controller->prepare_object_for_response_core(Object(Automattic\WooCommerce\Admin\Overrides\Order), Object(WP_REST_Request))",
        "#9 /wp-content/plugins/woocommerce/includes/rest-api/Controllers/Version3/class-wc-rest-crud-controller.php(405): WC_REST_Orders_V2_Controller->prepare_object_for_response(Object(Automattic\WooCommerce\Admin\Overrides\Order), Object(WP_REST_Request))",
        "#10 /wp-includes/rest-api/class-wp-rest-server.php(1292): WC_REST_CRUD_Controller->get_items(Object(WP_REST_Request))",
        "#11 /wp-includes/rest-api/class-wp-rest-server.php(1125): WP_REST_Server->respond_to_request(Object(WP_REST_Request), '/wc/v3/orders', Array, NULL)",
        "#12 /wp-includes/rest-api/class-wp-rest-server.php(439): WP_REST_Server->dispatch(Object(WP_REST_Request))",
        "#13 /wp-includes/rest-api.php(459): WP_REST_Server->serve_request('/wc/v3/orders')",
        "#14 /wp-includes/class-wp-hook.php(324): rest_api_loaded(Object(WP))",
        "#15 /wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)",
        "#16 /wp-includes/plugin.php(565): WP_Hook->do_action(Array)",
        "#17 /wp-includes/class-wp.php(418): do_action_ref_array('parse_request', Array)",
        "#18 /wp-includes/class-wp.php(818): WP->parse_request('')",
        "#19 /wp-includes/functions.php(1342): WP->main('')",
        "#20 /wp-blog-header.php(16): wp()",
        "#21 /index.php(17): require('/nas/content/li...')",
        "#22 {main}",
        "thrown"
    ]
}
```

### Steps to reproduce

1. Setup a local sandbox with WooCommerce and order histories containing coupons
2. Using the open-source Postman App or otherwise, send a REST API request to the sandbox using the link in the description adjusted for your environment.
3. Request an order number for an order that has a coupon line item.
4. Observe the 500 response.

### WordPress Environment

<details>

<summary>WordPress Environment</summary>

`
### WordPress Environment ###

WordPress address (URL): https://sandbox.local
Site address (URL): https://sandbox.local
WC Version: 9.8.5
Legacy REST API Package Version: The Legacy REST API plugin is not installed on this site.
Action Scheduler Version: ✔ 3.9.2
Log Directory Writable: ✔
WP Version: 6.8.1
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.27.5
PHP Version: 8.1.32
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 8.13.0
OpenSSL/3.5.0 (SecureTransport)

SUHOSIN Installed: –
MySQL Version: 9.3.0
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 9.8.5
WC Database Prefix: fas1_
Total Database Size: 2026.66MB
Database Data Size: 1472.77MB
Database Index Size: 553.89MB
fas1_woocommerce_sessions: Data: 4.52MB + Index: 0.08MB + Engine InnoDB
fas1_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
fas1_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
fas1_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
fas1_woocommerce_order_items: Data: 30.56MB + Index: 7.52MB + Engine InnoDB
fas1_woocommerce_order_itemmeta: Data: 970.73MB + Index: 134.38MB + Engine InnoDB
fas1_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
fas1_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
fas1_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
fas1_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
fas1_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
fas1_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
fas1_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
fas1_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
fas1_actionscheduler_actions: Data: 0.02MB + Index: 0.13MB + Engine InnoDB
fas1_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
fas1_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
fas1_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
fas1_adtribes_my_conversions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
fas1_aiowps_events: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
fas1_aiowps_failed_logins: Data: 0.41MB + Index: 0.00MB + Engine InnoDB
fas1_aiowps_global_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
fas1_aiowps_login_activity: Data: 0.16MB + Index: 0.00MB + Engine InnoDB
fas1_aiowps_login_lockdown: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
fas1_aiowps_permanent_block: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
fas1_commentmeta: Data: 2.52MB + Index: 3.03MB + Engine InnoDB
fas1_comments: Data: 30.56MB + Index: 25.09MB + Engine InnoDB
fas1_e_events: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
fas1_e_notes: Data: 0.02MB + Index: 0.17MB + Engine InnoDB
fas1_e_notes_users_relations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
fas1_e_submissions: Data: 0.02MB + Index: 0.27MB + Engine InnoDB
fas1_e_submissions_actions_log: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
fas1_e_submissions_values: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
fas1_ewwwio_images: Data: 3.52MB + Index: 4.00MB + Engine InnoDB
fas1_ewwwio_queue: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
fas1_failed_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
fas1_gf_draft_submissions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
fas1_gf_entry: Data: 0.45MB + Index: 0.13MB + Engine InnoDB
fas1_gf_entry_meta: Data: 2.52MB + Index: 2.22MB + Engine InnoDB
fas1_gf_entry_notes: Data: 0.36MB + Index: 0.14MB + Engine InnoDB
fas1_gf_form: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
fas1_gf_form_meta: Data: 0.17MB + Index: 0.00MB + Engine InnoDB
fas1_gf_form_revisions: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
fas1_gf_form_view: Data: 0.45MB + Index: 0.42MB + Engine InnoDB
fas1_gf_rest_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
fas1_image_compression_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
fas1_itsec_opaque_tokens: Data: 14.59MB + Index: 13.64MB + Engine InnoDB
fas1_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
fas1_mailchimp_carts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
fas1_newsletter: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
fas1_newsletter_emails: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
fas1_newsletter_sent: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
fas1_newsletter_stats: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
fas1_options: Data: 9.47MB + Index: 1.67MB + Engine InnoDB
fas1_pmxe_exports: Data: 0.22MB + Index: 0.00MB + Engine InnoDB
fas1_pmxe_google_cats: Data: 0.39MB + Index: 0.00MB + Engine InnoDB
fas1_pmxe_posts: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
fas1_pmxe_templates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
fas1_pmxi_files: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
fas1_pmxi_history: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
fas1_pmxi_images: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
fas1_pmxi_imports: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
fas1_pmxi_posts: Data: 0.13MB + Index: 0.11MB + Engine InnoDB
fas1_pmxi_templates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
fas1_postmeta: Data: 177.73MB + Index: 163.47MB + Engine InnoDB
fas1_posts: Data: 15.38MB + Index: 9.06MB + Engine InnoDB
fas1_queue: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
fas1_revslider_css: Data: 0.13MB + Index: 0.00MB + Engine InnoDB
fas1_revslider_layer_animations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
fas1_revslider_navigations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
fas1_revslider_sliders: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
fas1_revslider_slides: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
fas1_revslider_static_slides: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
fas1_searchwp_index: Data: 1.52MB + Index: 1.11MB + Engine InnoDB
fas1_searchwp_log: Data: 14.55MB + Index: 21.58MB + Engine InnoDB
fas1_searchwp_status: Data: 0.08MB + Index: 0.08MB + Engine InnoDB
fas1_searchwp_tokens: Data: 0.20MB + Index: 0.36MB + Engine InnoDB
fas1_smush_dir_images: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
fas1_snippets: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
fas1_swp_cf: Data: 3.52MB + Index: 6.55MB + Engine InnoDB
fas1_swp_index: Data: 8.52MB + Index: 8.03MB + Engine InnoDB
fas1_swp_log: Data: 7.52MB + Index: 12.55MB + Engine InnoDB
fas1_swp_tax: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
fas1_swp_terms: Data: 1.52MB + Index: 3.55MB + Engine InnoDB
fas1_term_relationships: Data: 0.14MB + Index: 0.13MB + Engine InnoDB
fas1_term_taxonomy: Data: 0.13MB + Index: 0.06MB + Engine InnoDB
fas1_termmeta: Data: 0.11MB + Index: 0.11MB + Engine InnoDB
fas1_terms: Data: 0.08MB + Index: 0.09MB + Engine InnoDB
fas1_usermeta: Data: 60.59MB + Index: 59.19MB + Engine InnoDB
fas1_users: Data: 4.52MB + Index: 5.55MB + Engine InnoDB
fas1_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
fas1_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
fas1_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
fas1_wc_customer_lookup: Data: 1.52MB + Index: 1.86MB + Engine InnoDB
fas1_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
fas1_wc_gpf_render_cache: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
fas1_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
fas1_wc_order_coupon_lookup: Data: 1.52MB + Index: 0.69MB + Engine InnoDB
fas1_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
fas1_wc_order_product_lookup: Data: 12.52MB + Index: 14.06MB + Engine InnoDB
fas1_wc_order_stats: Data: 2.52MB + Index: 3.45MB + Engine InnoDB
fas1_wc_order_tax_lookup: Data: 0.09MB + Index: 0.09MB + Engine InnoDB
fas1_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
fas1_wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
fas1_wc_product_attributes_lookup: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
fas1_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
fas1_wc_product_meta_lookup: Data: 0.14MB + Index: 0.33MB + Engine InnoDB
fas1_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
fas1_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
fas1_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
fas1_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
fas1_wcpdf_invoice_number: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
fas1_wcpdf_packing_slip_number: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
fas1_wfauditevents: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
fas1_wfblockediplog: Data: 0.22MB + Index: 0.00MB + Engine InnoDB
fas1_wfblocks7: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
fas1_wfconfig: Data: 3.52MB + Index: 0.00MB + Engine InnoDB
fas1_wfcrawlers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
fas1_wffilechanges: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
fas1_wffilemods: Data: 9.52MB + Index: 0.00MB + Engine InnoDB
fas1_wfhits: Data: 1.52MB + Index: 0.27MB + Engine InnoDB
fas1_wfhoover: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
fas1_wfissues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
fas1_wfknownfilelist: Data: 7.52MB + Index: 0.00MB + Engine InnoDB
fas1_wflivetraffichuman: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
fas1_wflocs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
fas1_wflogins: Data: 0.47MB + Index: 0.14MB + Engine InnoDB
fas1_wfls_2fa_secrets: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
fas1_wfls_role_counts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
fas1_wfls_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
fas1_wfnotifications: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
fas1_wfpendingissues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
fas1_wfreversecache: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
fas1_wfsecurityevents: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
fas1_wfsnipcache: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
fas1_wfstatus: Data: 0.23MB + Index: 0.14MB + Engine InnoDB
fas1_wftrafficrates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
fas1_wfwafconfig: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
fas1_wfwaffailures: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
fas1_woocommerce_bundled_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
fas1_woocommerce_bundled_items: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
fas1_woocommerce_gpf_google_taxonomy: Data: 1.52MB + Index: 0.13MB + Engine InnoDB
fas1_wp_optimisation_sizes_info: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
fas1_wpfm_backup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
fas1_wpforms_entries: Data: 2.52MB + Index: 0.05MB + Engine InnoDB
fas1_wpforms_entry_fields: Data: 1.52MB + Index: 0.66MB + Engine InnoDB
fas1_wpforms_entry_meta: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
fas1_wpmailsmtp_debug_events: Data: 0.19MB + Index: 0.00MB + Engine InnoDB
fas1_wpmailsmtp_emails_log: Data: 41.56MB + Index: 15.61MB + Engine InnoDB
fas1_wpmailsmtp_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
fas1_wt_iew_action_history: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
fas1_wt_iew_cron: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
fas1_wt_iew_ftp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
fas1_wt_iew_mapping_template: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
fas1_yith_wcan_cache: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
fas1_yith_wcwl: Data: 2.52MB + Index: 1.52MB + Engine InnoDB
fas1_yith_wcwl_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
fas1_yith_wcwl_lists: Data: 2.52MB + Index: 27.67MB + Engine InnoDB
fas1_yoast_indexable: Data: 1.52MB + Index: 0.48MB + Engine InnoDB
fas1_yoast_indexable_hierarchy: Data: 0.11MB + Index: 0.17MB + Engine InnoDB
fas1_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
fas1_yoast_primary_term: Data: 0.08MB + Index: 0.06MB + Engine InnoDB
fas1_yoast_prominent_words: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
fas1_yoast_seo_links: Data: 0.22MB + Index: 0.16MB + Engine InnoDB
fas1_yoast_seo_meta: Data: 0.45MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

acf-field: 130
acf-field-group: 20
adt_product_feed: 3
attachment: 2542
custom_css: 2
customize_changeset: 14
elementor_library: 1
ep-synonym: 1
nav_menu_item: 49
oembed_cache: 7
order_shipment: 3
page: 77
popup: 2
popup_theme: 8
post: 107
product: 653
product_variation: 181
revision: 45
shop_coupon: 59
shop_order_placehold: 31098
sidebar: 1
tablepress_table: 5
wafs: 1
wp_global_styles: 1
wp_navigation: 1
wpforms: 4
yith_wcan_preset: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (3) ###

WooCommerce.com Update Manager: by Automattic – 1.0.3
WooCommerce: by Automattic – 9.8.5
WPMU DEV Dashboard: by WPMU DEV – 4.11.29

### Inactive Plugins (27) ###

Advanced Custom Fields PRO: by WP Engine – 6.4.2
Advanced Order Export For WooCommerce: by AlgolPlus – 4.0.2
Classic Editor: by WordPress Contributors – 1.6.7
Code Snippets: by Code Snippets Pro – 3.6.8
Elementor: by Elementor.com – 3.29.1
Gratisfaction- Loyalty Rewards Referral Birthday and Giveaway Program: by Appsmav – 4.5.1
Gravity Forms: by Gravity Forms – 2.9.8
Kadence WooCommerce Email Designer: by Kadence WP – 1.5.16
Klaviyo: by Klaviyo
Inc. – 3.5.0

PDF Invoices & Packing Slips for WooCommerce: by WP Overnight – 4.5.2
Product Feed PRO for WooCommerce: by AdTribes.io – 13.4.4.2
SearchWP: by SearchWP – 4.4.0
SearchWP WooCommerce Integration: by SearchWP – 1.4.0
Sequential Order Numbers for WooCommerce: by SkyVerge – 1.11.1
Simple Banner: by Ryan Petersen – 3.0.7
SiteOrigin Widgets Bundle: by SiteOrigin – 1.68.4
TablePress: by Tobias Bäthge – 3.1.3
User Switching: by John Blackbourn – 1.9.2
WooCommerce Extended Coupon Features FREE: by Soft79 – 3.3.9
WooCommerce FedEx Shipping: by WooCommerce – 4.4.0
WooCommerce Google Product Feed: by Ademti Software Ltd. – 11.0.19
WooCommerce Legacy REST API: by WooCommerce – 1.0.5
WooCommerce Purchase Order Payment Gateway: by WooCommerce – 1.5.4
WooCommerce Stripe Gateway: by Stripe – 9.5.2
WooCommerce USPS Shipping: by WooCommerce – 5.1.8
YITH WooCommerce Ajax Product Filter: by YITH – 5.10.0
YITH WooCommerce Wishlist Premium: by YITH – 4.1.0

### Settings ###

Legacy API Enabled: –
Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: bundle (bundle)
composite (composite)
external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: –
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 491 KB

### WC Pages ###

Shop base: #4 - /shop/
Cart: #5 - /cart/ -  Contains the woocommerce_cart shortcode
Checkout: #6 - /checkout/ -  Contains the woocommerce_checkout shortcode
My account: #7 - /my-account/ -  Contains the [woocommerce_my_account] shortcode
Terms and conditions: #14748 - /terms-conditions/

### Theme ###

Name: Twenty Twenty-Five
Version: 1.2
Author URL: https://wordpress.org
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
Theme type: Block theme
WooCommerce Support: ❌ Not declared

### Templates ###

Overrides: /wp-content/plugins/woocommerce/templates/block-notices/error.php
/wp-content/plugins/woocommerce/templates/block-notices/notice.php
/wp-content/plugins/woocommerce/templates/block-notices/success.php

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
onboarding
onboarding-tasks
pattern-toolkit-full-composability
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
printful
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page
launch-your-store
add-to-cart-with-options-stepper-layout

Disabled Features: product-data-views
experimental-blocks
coming-soon-newsletter-template
minified-js
product-pre-publish-modal
settings
async-product-editor-category-field
product-editor-template-system
use-wp-horizon
blockified-add-to-cart

Daily Cron: ✔ Next scheduled: 2025-05-19 20:55:29 -06:00
Options: ✔
Notes: 10
Onboarding: completed

### Action Scheduler ###

Pending: 6
Oldest: 2025-05-20 20:39:08 -0600
Newest: 2025-05-29 13:58:51 -0600

Canceled: 4
Oldest: -0001-11-29 17:00:04 -0659
Newest: -0001-11-29 17:00:04 -0659

### Status report information ###

Generated at: 2025-05-29 15:01:43 -06:00
`

</details>

### Isolating the problem

- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by roccotripaldi**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

**The issue:**

In `WC_Data->set_date_prop` assumes that the value of the date, if it is not an int or a WC_DateTime object, will be a string. It will attempt to run `preg_match` on the value, without fully ensuring the value is of type string. This will result in fatals in rare cases when the value is something other than an int, a WC_DateTime object, or a string. 

**My fix:**

Make sure the value is actually a string before running `preg_match`. If it's not a string, throw an exception.

Closes #58401

### How to test the changes in this Pull Request:

~Testing the actually failure is difficult because it requires having a Woo store with older data. ~

Here is a patch to emulate the error from the bug report:
[debug.patch](https://github.com/user-attachments/files/20718901/debug.patch)

We can emulate the error like this:
1. On your testing site, checkout trunk
2. In WP Admin, create an order and apply a coupon to the order.
3. Using Postman or Curl send a GET request to `/wp-json/wc/v3/orders`
4. You should receive a 200 response.
5. Apply the patch above, and resend the request.
6. You'll get a 500 error.

Test the fix in this PR:
1. Check out this PR, and send the request again.
2. You should get a 200.

You can remove the patch, and finally test:
1. That GET requests to `wp-json/wc/v3/orders` continue to work.
7. That there are no side effects from the new Exception introduced in this PR. We can ensure this by merging this PR into a beta release.

### Testing that has already taken place:

I've run through the testing instructions above a few times, and made sure the issue goes away.

I did make some attempts to unit test here, but I wasn't able to create a test that worked, or made any sense!

See my latest commit:
https://github.com/woocommerce/woocommerce/pull/58700/commits/96821570fc3411989e2cd51448d6ebbb3068e9f3

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

Fixes a bug where listing Woo orders on the REST API will crash if the order has a coupon with a malformed date.

</details>

## Summary by CodeRabbit

- **Bug Fixes**
  - Resolved an issue where retrieving orders with coupons containing malformed dates in the WooCommerce REST API could cause a crash.
  - Improved error handling for invalid date inputs to prevent similar issues in the future.

- **Style**
  - Minor formatting improvements for code readability.

### CODE REVIEW

File: plugins/woocommerce/includes/abstracts/abstract-wc-data.php [hunk 1]
```diff
@@ -905,7 +906,7 @@ protected function set_date_prop( $prop, $value ) {
 			} elseif ( is_numeric( $value ) ) {
 				// Timestamps are handled as UTC timestamps in all cases.
 				$datetime = new WC_DateTime( "@{$value}", new DateTimeZone( 'UTC' ) );
-			} else {
+			} else if( is_string( $value ) ) {
```
Comment (roccotripaldi) [inline plugins/woocommerce/includes/abstracts/abstract-wc-data.php]: Maybe this one line is enough to stop the crashes.

File: plugins/woocommerce/includes/abstracts/abstract-wc-data.php [hunk 2]
```diff
@@ -914,6 +915,13 @@ protected function set_date_prop( $prop, $value ) {
 					$timestamp = wc_string_to_timestamp( get_gmt_from_date( gmdate( 'Y-m-d H:i:s', wc_string_to_timestamp( $value ) ) ) );
 				}
 				$datetime = new WC_DateTime( "@{$timestamp}", new DateTimeZone( 'UTC' ) );
+			} else {
+				throw new WC_Data_Exception(
+					'woocommerce_invalid_date_value',
+					sprintf( __( 'Invalid date value for %s: %s', 'woocommerce' ), $prop, print_r( $value, true ) ),
+					400,
+					array( 'property_name' => $prop )
+				);
```
Comment (roccotripaldi) [inline plugins/woocommerce/includes/abstracts/abstract-wc-data.php]: Do you think throwing here could be too disruptive?

**Review by naman03malhotra — DISMISSED** [review]
>Testing the actual failure is difficult because it requires having a Woo store with older data.

👋 Hey Rooco, thanks for taking this forward.
Would it be possible to simulate the behavior that might be causing this issue? I believe it’s important to replicate the exact scenario before proposing a fix that will help us to remove any uncertainty. One approach could be to manually adjust the relevant database values (or use a temporary data stub) to mimic older store data and observe the outcome.

**Comment by roccotripaldi** [comment]
@naman03malhotra challenge accepted.

**Comment by PanosSynetos** [comment]
@roccotripaldi make sure to check the failing tests. For example, linting failed on this PR

```
. lint:changes:branch:php: FILE: plugins/woocommerce/includes/abstracts/abstract-wc-data.php
. lint:changes:branch:php: -----------------------------------------------------------------------------------------------
. lint:changes:branch:php: FOUND 3 ERRORS AND 1 WARNING AFFECTING 4 LINES
. lint:changes:branch:php: -----------------------------------------------------------------------------------------------
. lint:changes:branch:php:  908 | WARNING | Usage of ELSE IF is discouraged; use ELSEIF instead (PSR2.ControlStructures.ElseIfDeclaration.NotAllowed)
. lint:changes:branch:php:  908 | ERROR | Space after opening control structure is required (WordPress.WhiteSpace.ControlStructureSpacing.NoSpaceAfterStructureOpen)
. lint:changes:branch:php:  908 | ERROR | No space before opening parenthesis is prohibited (WordPress.WhiteSpace.ControlStructureSpacing.NoSpaceBeforeOpenParenthesis)
. lint:changes:branch:php:  908 | ERROR | Expected 1 space after IF keyword; 0 found (Squiz.ControlStructures.ControlSignature.SpaceAfterKeyword)
```

Coderabbit has also made some suggestions, check them out if they are valid :) Thanks to both of you @naman03malhotra and @roccotripaldi for driving this forward

**Review by naman03malhotra — COMMENTED** [review]
Hey Rocco, thanks for taking it forward. Please do take a look at the failing linter CI and tests, as Panos mentioned. Additionally, it is important that we test this change to ensure it remains future-proof against any unintended alterations.

I'll take a proper look at it next week.

**Comment by roccotripaldi** [comment]
Thanks for the review Naman. I spent 2 hours today trying to write a unit test for this, but I couldn't figure out how. There are higher priorities now, so I don't want to spend too much time with this. I'll close this PR, but maybe someone with more Woo experience can take a try at a later date.

**Comment by PanosSynetos** [comment]
Hey @roccotripaldi - before closing the PR, let's discuss what you tested, if you were able to replicate or not the issue , so the next one is aware.

Thank you

**Comment by roccotripaldi** [comment]
> Hey @roccotripaldi - before closing the PR, let's discuss what you tested, if you were able to replicate or not the issue , so the next one is aware.


Thanks for that Panos. I didn't believe there was any value in this PR, but maybe their is!  I've updated the PR description to better summarize my fix, and what I've tried.

**Review by naman03malhotra — COMMENTED** [review]
Hey @roccotripaldi your fix looks good, I've tested it with mutiple invalid date formats and I am able to reproduce it with the instructions you mentioned.

I've created a followup PR to add test for this to make sure we don't regress, I've assigned it for the review: https://github.com/woocommerce/woocommerce/pull/60022

**Review by naman03malhotra — COMMENTED** [review]
Once we merge the next PR with tests: https://github.com/woocommerce/woocommerce/pull/60022, the next step would be to fix the lint issues and make sure everything is green before we merge.

File: plugins/woocommerce/includes/abstracts/abstract-wc-data.php [hunk 3]
```diff
@@ -19,7 +19,7 @@
  *
  * Implemented by classes using the same CRUD(s) pattern.
  *
- * @version  2.6.0
+ * @version  x.x.x
```
Comment (naman03malhotra) [inline plugins/woocommerce/includes/abstracts/abstract-wc-data.php]: So in core we don't rename it to `x.x.x`, we add the exact version, i.e the version this PR will be released with.

Also, I think we add @since to preserve the original version.

**Review by naman03malhotra — COMMENTED** [review]
Looking good now overall, let's merge when tests are green!

**Review by naman03malhotra — COMMENTED** [review]
Hey @roccotripaldi, this should be good to go, I've merged the PR for tests https://github.com/woocommerce/woocommerce/pull/60022, once the CI passed and some minor feedback to be addressed in the PR.

**Comment by naman03malhotra** [comment]
CI is passing now after the fresh pull from trunk.

File: plugins/woocommerce/includes/abstracts/abstract-wc-data.php (hunk 3 above)
Comment (PanosSynetos) [reply plugins/woocommerce/includes/abstracts/abstract-wc-data.php]: What @naman03malhotra said :)

```
@since    2.6.0
@version  10.2.0
```

**Review by naman03malhotra — APPROVED** [review]
Approving as CI is passing! testing well and the test PR https://github.com/woocommerce/woocommerce/pull/60022 is also merged!

**Comment by naman03malhotra** [comment]
@roccotripaldi this is ready to be merged, but I'll let you do the honors.
