### PR TITLE
[Experimental]: Find a way to identify when a block is descendant of the SingleProduct block

### LINKED ISSUE #53283: [Enhancement]: Refactor setting attributes after first render to avoid anti-pattern
Currently, attributes are being set [after the first render](https://github.com/woocommerce/woocommerce/blob/35a975865fe1bfa1e7aaabc5a2a02a6578e545f5/plugins/woocommerce-blocks/assets/js/blocks/product-elements/add-to-cart-form/edit.tsx#L68-L72) of the `add-to-cart-with-options` block, which has been identified as problematic. 

That approach introduces some issues:
- It causes unexpected bugs in the Site Editor, as reported in [Issue #48936](https://github.com/woocommerce/woocommerce/issues/48936).

We should try to find a different way to handle this instead of using a block attribute.

Please take a look at [this comment](https://github.com/woocommerce/woocommerce/pull/53215/files#r1861882695) for more context.

### LINKED ISSUE #53284: [Enhancement]: Find a way to identify when a block is descendant of the SingleProduct block
The current method of identifying whether a block is a descendant of the SingleProduct block is [not ideal](https://github.com/woocommerce/woocommerce/pull/53215/files#r1861908953). This approach could be improved for better maintainability and reliability.

Let's try to find a better way to [handle is-descendent-of-single-product-block](https://github.com/woocommerce/woocommerce/blob/35a975865fe1bfa1e7aaabc5a2a02a6578e545f5/plugins/woocommerce/src/Blocks/BlockTypes/AddToCartWithOptions.php#L161).

### PR DESCRIPTION
**Pull request by mdperez86**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes #53284
Closes #53283

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Install and activate the WooCommerce Beta Tester plugin
2. Go to WooCommerce Admin Test Helper > Features and enable experimental-blocks and blockified-add-to-cart.
3. Go to Appearance > Editor > Templates > Single Product, select the Add to Cart with Options block and update it to the blockified one.
4. Create a new post
5. Add the single product block
6. Select a simple product and save the post
7. Go to view the post created
8. The simple product should be shown in the frontend
9. When adding the product to the cart no notice should be shown
10. Go to edit the single product template
11. Change the add to cart with options block to the blockified one
12. Save the template and go to the view a simple product from the store
13. When click on add to cart the simple product the notice should be shown.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce/src/Blocks/BlockTypes/AddToCartWithOptionsVariationSelector.php [hunk 1]
```diff
@@ -308,16 +308,9 @@ private function get_reset_button_row(): string {
...
-			return '';
-		}
-
 		global $product;
-		$previous_product = $product;
-		$product          = wc_get_product( $block->context['postId'] );
 
-		if ( ! $product instanceof \WC_Product || ! $product->is_type( 'variable' ) ) {
-			$product = $previous_product;
+		if ( ! $product->is_type( 'variable' ) ) {
```
Comment (Aljullu) [inline plugins/woocommerce/src/Blocks/BlockTypes/AddToCartWithOptionsVariationSelector.php]: Should we keep `! $product instanceof \WC_Product`? Or are we sure that `global $product` will always exist and will be a product?

File: plugins/woocommerce/src/Blocks/BlockTypes/AddToCartWithOptionsGroupedProductSelectorItemTemplate.php [hunk 2]
```diff
@@ -65,15 +65,7 @@ private function get_product_row( $product_id, $attributes, $block ): string {
...
-		if ( ! isset( $block->context['postId'] ) ) {
-			return '';
-		}
-
-		$product = wc_get_product( $block->context['postId'] );
-
-		if ( ! $product instanceof \WC_Product || ! $product->is_type( 'grouped' ) ) {
-			return '';
-		}
+		global $product;
```
Comment (Aljullu) [inline plugins/woocommerce/src/Blocks/BlockTypes/AddToCartWithOptionsGroupedProductSelectorItemTemplate.php:68]: Same here, what's the benefit of removing the check that verifies `$product` is a grouped product?

File: plugins/woocommerce/src/Blocks/BlockTypes/AddToCartWithOptionsGroupedProductSelector.php [hunk 3]
```diff
@@ -26,7 +26,9 @@ class AddToCartWithOptionsGroupedProductSelector extends AbstractBlock {
 	 * @return string Rendered block output.
 	 */
 	protected function render( $attributes, $content, $block ): string {
-		if ( ! isset( $block->context['postId'] ) ) {
+		global $product;
+
+		if ( ! $product->is_type( 'grouped' ) ) {
```
Comment (Aljullu) [inline plugins/woocommerce/src/Blocks/BlockTypes/AddToCartWithOptionsGroupedProductSelector.php]: And possibly we should add an additional check that `$product` is a `WC_Product` here too? :thinking:

File: plugins/woocommerce/src/Blocks/BlockTypes/AddToCartForm.php [hunk 4]
```diff
@@ -174,11 +176,7 @@ protected function render( $attributes, $content, $block ) {
 		$product_html = $is_stepper_style ? $this->add_steppers( $product_html, $product_name ) : $product_html;
 
 		$parsed_attributes                     = $this->parse_attributes( $attributes );
-		$is_descendent_of_single_product_block = $parsed_attributes['isDescendentOfSingleProductBlock'];
```
Comment (Aljullu) [inline plugins/woocommerce/src/Blocks/BlockTypes/AddToCartForm.php:177]: If we don't need to read this attribute from the PHP-side anymore, could we remove it from the JS-side?

https://github.com/woocommerce/woocommerce/blob/f7025af6837eaf71842d99ba0f81d71654395cff/plugins/woocommerce-blocks/assets/js/blocks/product-elements/add-to-cart-form/edit.tsx#L50-L54

**Review by Aljullu — COMMENTED** [review]
Overall looking good, nice to see that we can remove the `isDescendantOf...` attribute! :partying_face: 

I tested adding a _Single Product_ block inside a _Single Product_ template and setting `Redirect to the cart page after successful addition` to true in WooCommerce > Settings > Products and it seems to no longer redirect to the _Cart_ page. Can you reproduce too?

imatge

File: plugins/woocommerce/src/Blocks/BlockTypes/AddToCartWithOptionsGroupedProductSelectorItemTemplate.php (hunk 2 above)
Comment (mdperez86) [reply plugins/woocommerce/src/Blocks/BlockTypes/AddToCartWithOptionsGroupedProductSelectorItemTemplate.php:68]: done

File: plugins/woocommerce/src/Blocks/BlockTypes/AddToCartWithOptionsGroupedProductSelector.php (hunk 3 above)
Comment (mdperez86) [reply plugins/woocommerce/src/Blocks/BlockTypes/AddToCartWithOptionsGroupedProductSelector.php]: done

File: plugins/woocommerce/src/Blocks/BlockTypes/AddToCartForm.php (hunk 4 above)
Comment (mdperez86) [reply plugins/woocommerce/src/Blocks/BlockTypes/AddToCartForm.php:177]: done

**Review by Aljullu — APPROVED** [review]
Looks good to me, good job, @mdperez86!

imatge

:heart_eyes:
