### PR TITLE
Bugfix/Ajax Warning/Notices: Add Fix for Warning and Notices on save attribute button click

### LINKED ISSUE #22821: Warning and Notices on save attribute button click
**Describe the bug**
When there is not attribute added. on Save attribute button click. 
It throw a Notice and warning in error log. 

**To Reproduce**
1. Go for Add new product
2. Click on 'save product button inside attributes tab'
3. check the error log

PHP Notice:  Undefined index: attribute_names in /srv/www/wordpress-new/public_html/wp-content/plugins/woocommerce/includes/class-wc-ajax.php on line 635

Warning:  Invalid argument supplied for foreach() in /srv/www/wordpress-new/public_html/wp-content/plugins/woocommerce/includes/class-wc-ajax.php on line 635

**Expected behavior**
The functionality should not throw any warning or notices. 

**WordPress Environment**
<details>
```
WordPress address (URL):		http://local.newwp.test
Site address (URL):		http://local.newwp.test
WooCommerce version:		3.6.0
Log directory writable:		 /srv/www/wordpress-new/public_html/wp-content/uploads/wc-logs/
WordPress version:		5.1
WordPress multisite:		–
WordPress memory limit:		256 MB
WordPress debug mode:		
WordPress cron:		
Language:		en_US
External object cache:		–
Server environment
Server info:		nginx/1.15.8
PHP version:		7.2.15-1+ubuntu14.04.1+deb.sury.org+1
PHP post max size:		1 GB
PHP time limit:		30
PHP max input vars:		1000
cURL version:		7.35.0, OpenSSL/1.0.1f
SUHOSIN installed:		–
MySQL version:		5.5.5-10.3.12-MariaDB-1:10.3.12+maria~trusty
Max upload size:		1 GB
Default timezone is UTC:		
fsockopen/cURL:		
SoapClient:		
DOMDocument:		
GZip:		
Multibyte string:		
Remote post:		
Remote get:		
Database
WooCommerce database version:		3.6.0
Database prefix	 	wp_
MaxMind GeoIP database:		 /srv/www/wordpress-new/public_html/wp-content/uploads/GeoLite2-Country.mmdb
Total Database Size	 	5.81MB
Database Data Size	 	3.82MB
Database Index Size	 	1.99MB
wp_woocommerce_sessions	 	Data: 0.02MB + Index: 0.02MB
wp_woocommerce_api_keys	 	Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies	 	Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions	 	Data: 0.02MB + Index: 0.05MB
wp_woocommerce_order_items	 	Data: 0.02MB + Index: 0.02MB
wp_woocommerce_order_itemmeta	 	Data: 0.02MB + Index: 0.03MB
wp_woocommerce_tax_rates	 	Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations	 	Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zones	 	Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations	 	Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zone_methods	 	Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens	 	Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta	 	Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log	 	Data: 0.02MB + Index: 0.02MB
wp_alm	 	Data: 0.02MB + Index: 0.00MB
wp_bp_activity	 	Data: 0.02MB + Index: 0.16MB
wp_bp_activity_meta	 	Data: 0.02MB + Index: 0.03MB
wp_bp_friends	 	Data: 0.02MB + Index: 0.03MB
wp_bp_groups	 	Data: 0.02MB + Index: 0.05MB
wp_bp_groups_groupmeta	 	Data: 0.02MB + Index: 0.03MB
wp_bp_groups_members	 	Data: 0.02MB + Index: 0.09MB
wp_bp_messages_messages	 	Data: 0.02MB + Index: 0.03MB
wp_bp_messages_meta	 	Data: 0.02MB + Index: 0.03MB
wp_bp_messages_notices	 	Data: 0.02MB + Index: 0.02MB
wp_bp_messages_recipients	 	Data: 0.02MB + Index: 0.08MB
wp_bp_notifications	 	Data: 0.02MB + Index: 0.11MB
wp_bp_notifications_meta	 	Data: 0.02MB + Index: 0.03MB
wp_bp_user_blogs	 	Data: 0.02MB + Index: 0.03MB
wp_bp_user_blogs_blogmeta	 	Data: 0.02MB + Index: 0.03MB
wp_bp_xprofile_data	 	Data: 0.02MB + Index: 0.03MB
wp_bp_xprofile_fields	 	Data: 0.02MB + Index: 0.08MB
wp_bp_xprofile_groups	 	Data: 0.02MB + Index: 0.02MB
wp_bp_xprofile_meta	 	Data: 0.02MB + Index: 0.03MB
wp_commentmeta	 	Data: 0.02MB + Index: 0.03MB
wp_comments	 	Data: 0.02MB + Index: 0.08MB
wp_crm_campaign	 	Data: 0.02MB + Index: 0.00MB
wp_crm_company	 	Data: 0.02MB + Index: 0.00MB
wp_crm_customer	 	Data: 0.02MB + Index: 0.00MB
wp_crm_project	 	Data: 0.02MB + Index: 0.00MB
wp_crm_roadmap	 	Data: 0.09MB + Index: 0.00MB
wp_failed_jobs	 	Data: 0.02MB + Index: 0.00MB
wp_gdt_users	 	Data: 0.02MB + Index: 0.00MB
wp_links	 	Data: 0.02MB + Index: 0.02MB
wp_mailchimp_carts	 	Data: 0.02MB + Index: 0.00MB
wp_options	 	Data: 2.02MB + Index: 0.05MB
wp_pattern_lock	 	Data: 0.02MB + Index: 0.00MB
wp_postmeta	 	Data: 0.44MB + Index: 0.06MB
wp_posts	 	Data: 0.13MB + Index: 0.06MB
wp_queue	 	Data: 0.02MB + Index: 0.00MB
wp_signups	 	Data: 0.02MB + Index: 0.06MB
wp_slp_extendo_meta	 	Data: 0.02MB + Index: 0.05MB
wp_sm_sessions	 	Data: 0.02MB + Index: 0.02MB
wp_store_locator	 	Data: 0.02MB + Index: 0.05MB
wp_termmeta	 	Data: 0.02MB + Index: 0.03MB
wp_terms	 	Data: 0.02MB + Index: 0.03MB
wp_term_relationships	 	Data: 0.02MB + Index: 0.02MB
wp_term_taxonomy	 	Data: 0.02MB + Index: 0.03MB
wp_usermeta	 	Data: 0.02MB + Index: 0.03MB
wp_users	 	Data: 0.02MB + Index: 0.05MB
wp_wc_download_log	 	Data: 0.02MB + Index: 0.03MB
wp_wc_webhooks	 	Data: 0.02MB + Index: 0.02MB
Post Type Counts
attachment	 	11
bp-email	 	15
crm_contacts	 	10
customize_changeset	 	1
dxcrm_campaign	 	2
dxcrm_company	 	2
dxcrm_customers	 	2
dxcrm_milestones	 	5
dxcrm_projects	 	3
dxcrm_roadmap	 	1
fca_qc_quiz	 	1
forum	 	2
nav_menu_item	 	10
page	 	15
post	 	8
product	 	3
reply	 	10
revision	 	15
topic	 	2
user_request	 	1
wp-type-contacts	 	1
wpcf7_contact_form	 	1
Security
Secure connection (HTTPS):		 Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors		
Active plugins (11)
Query Monitor	 	by John Blackbourn & contributors – 3.1.1
Custom List Table Example	 	by Matt van Andel – 1.4.1
Jetpack by WordPress.com	 	by Automattic – 7.0.1
Liveblog	 	by WordPress.com VIP, Big Bite Creative and contributors – 1.9.4
Mailchimp for WooCommerce	 	by Mailchimp – 2.1.13 – Not tested with the active version of WooCommerce
Quiz Cat Free	 	by Fatcat Apps – 1.7.0
WooCommerce PayPal Checkout Gateway	 	by WooCommerce – 1.6.9 – Not tested with the active version of WooCommerce
WooCommerce Services	 	by Automattic – 1.19.0 – Not tested with the active version of WooCommerce
WooCommerce	 	by Automattic – 3.6.0-dev
WP Cookie Notifier	 	by DevriX – 1.0.0
WP Geodirectory Test	 	by 1naveengiri – 1.0
Settings
API enabled:		–
Force SSL:		–
Currency		INR (₹)
Currency position		left
Thousand separator		,
Decimal separator		.
Number of decimals		2
Taxonomies: Product types		external (external), grouped (grouped), simple (simple), variable (variable)
Taxonomies: Product visibility		exclude-from-catalog (exclude-from-catalog), exclude-from-search (exclude-from-search), featured (featured), outofstock (outofstock), rated-1 (rated-1), rated-2 (rated-2), rated-3 (rated-3), rated-4 (rated-4), rated-5 (rated-5)
WooCommerce pages
Shop base:		#435 - /shop/
Cart:		#437 - /cart/
Checkout:		#439 - /checkout/
My account:		#441 - /my-account/
Terms and conditions:		 Page not set
Theme
Name:		Storefront
Version:		2.4.3
Author URL:		https://woocommerce.com/
Child theme:		 – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce support:
```
</details>

### PR DESCRIPTION
**Pull request by 1naveengiri**
PHP Notice:  Undefined index: attribute_names in /srv/www/wordpress-new/public_html/wp-content/plugins/woocommerce/includes/class-wc-ajax.php on line 635
Warning:  Invalid argument supplied for foreach() in /srv/www/wordpress-new/public_html/wp-content/plugins/woocommerce/includes/class-wc-ajax.php on line 635

### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes #22821 

### How to test the changes in this Pull Request:

1. pull the code branch
2. follow the step of from the issue description
3. check the log file for notices and warning

### Changelog entry

> Added isset and empty check for empty array field.

### CODE REVIEW

File: includes/class-wc-ajax.php [hunk 1]
```diff
@@ -632,21 +632,22 @@ public static function save_attributes() {
 			ob_start();
 			$attributes = $product->get_attributes( 'edit' );
 			$i          = -1;
+			if( isset( $data['attribute_names'] ) && !empty( $data['attribute_names'] ) ){
```
Comment (mikejolley) [inline includes/class-wc-ajax.php]: `empty` does not trigger warnings so only that needs to be checked. You can remove the `isset`.

Also, please correct the spacing for code standards. `! empty` and `) {` and `if (`
