### PR TITLE
Fix #24365: Prevent billing address from being updated on shipping update.

### LINKED ISSUE #24365: Shipping Calculator in Cart updates Billing address details
**Related ticket**
2258618-zen

**Describe the bug**
Logged in as user with full address details in account settings.

Shipping settings set to default to Customer Shipping address

https://cld.wthms.co/LYLiCX 
Full Size: https://cld.wthms.co/LYLiCX

Purchase by logged in user.
Address auto populates the Cart shipping calculator with details from account:

https://cld.wthms.co/HzxHFI 
Full Size: https://cld.wthms.co/HzxHFI

Address is also pre-loaded in the checkout

https://cld.wthms.co/do0yYi 
Full Size: https://cld.wthms.co/do0yYi

Change the address details in the cart shipping calculator:

https://cld.wthms.co/VZ43Ev 
Full Size: https://cld.wthms.co/VZ43Ev

and proceed to the checkout. Street address in the Billing section is missing and shipping town/city has changed to shipping town/city

https://cld.wthms.co/PS9gje 
Full Size: https://cld.wthms.co/PS9gje

**To Reproduce**
1. Create User with full Billing and Shipping Address in account details
2. Enable  Shipping calculator in cart
3. Add items to cart and see that shipping calculator is pre-loaded with users address
4. Change shipping address in shipping calculator
5. Checkout and see that Billing address is lacking Street address

**Expected behavior**
Only Shipping address would be updated in the checkout and the Billing address would remain as that set in the users account

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
### WordPress Environment ###

WordPress address (URL): https://edisonlightglobes.com/Shop
Site address (URL): https://edisonlightglobes.com/Shop
WC Version: 3.6.5
Log Directory Writable: ✔
WP Version: 5.2.2
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.3.8
PHP Post Max Size: 800 MB
PHP Time Limit: 600
PHP Max Input Vars: 1000
cURL Version: 7.65.3
OpenSSL/1.0.2s

SUHOSIN Installed: –
MySQL Version: 5.6.44
Max Upload Size: 800 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.6.5
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Total Database Size: 1788.52MB
Database Data Size: 1582.96MB
Database Index Size: 205.56MB
wp_woocommerce_sessions: Data: 2.39MB + Index: 0.09MB
wp_woocommerce_api_keys: Data: 0.00MB + Index: 0.01MB
wp_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.01MB
wp_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_order_items: Data: 4.41MB + Index: 1.92MB
wp_woocommerce_order_itemmeta: Data: 38.11MB + Index: 21.97MB
wp_woocommerce_tax_rates: Data: 0.00MB + Index: 0.01MB
wp_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.01MB
wp_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_log: Data: 0.00MB + Index: 0.00MB
wp_advanced_notifications: Data: 0.00MB + Index: 0.00MB
wp_aelia_dismissed_messages: Data: 0.02MB + Index: 0.00MB
wp_cart_notices: Data: 0.00MB + Index: 0.00MB
wp_commentmeta: Data: 3.60MB + Index: 2.05MB
wp_comments: Data: 21.63MB + Index: 8.46MB
wp_csp3_subscribers: Data: 0.00MB + Index: 0.00MB
wp_cspv5_pages: Data: 0.01MB + Index: 0.00MB
wp_easypost_packages: Data: 0.00MB + Index: 0.00MB
wp_gglcptch_whitelist: Data: 0.02MB + Index: 0.02MB
wp_image_mapper_object: Data: 0.00MB + Index: 0.00MB
wp_image_mapper_object_meta: Data: 0.06MB + Index: 0.01MB
wp_links: Data: 0.00MB + Index: 0.00MB
wp_options: Data: 1193.77MB + Index: 88.75MB
wp_postmeta: Data: 258.80MB + Index: 51.99MB
wp_posts: Data: 13.97MB + Index: 2.99MB
wp_rg_campaignmonitor: Data: 0.00MB + Index: 0.00MB
wp_rg_form: Data: 0.00MB + Index: 0.00MB
wp_rg_form_meta: Data: 0.05MB + Index: 0.00MB
wp_rg_form_view: Data: 0.54MB + Index: 0.20MB
wp_rg_lead: Data: 0.04MB + Index: 0.01MB
wp_rg_lead_detail: Data: 0.06MB + Index: 0.10MB
wp_rg_lead_meta: Data: 0.01MB + Index: 0.02MB
wp_rg_lead_notes: Data: 0.00MB + Index: 0.00MB
wp_sbi_instagram_feeds_posts: Data: 4.52MB + Index: 1.09MB
wp_sbi_instagram_posts: Data: 0.05MB + Index: 0.00MB
wp_termmeta: Data: 0.14MB + Index: 0.10MB
wp_terms: Data: 0.31MB + Index: 0.56MB
wp_term_relationships: Data: 1.19MB + Index: 2.11MB
wp_term_taxonomy: Data: 0.31MB + Index: 0.31MB
wp_tm_taskmeta: Data: 0.00MB + Index: 0.00MB
wp_tm_tasks: Data: 0.00MB + Index: 0.00MB
wp_usermeta: Data: 30.34MB + Index: 17.07MB
wp_users: Data: 1.55MB + Index: 1.15MB
wp_usin_user_data: Data: 0.07MB + Index: 0.04MB
wp_wc_admin_notes: Data: 0.00MB + Index: 0.00MB
wp_wc_admin_note_actions: Data: 0.00MB + Index: 0.00MB
wp_wc_customer_lookup: Data: 0.96MB + Index: 0.62MB
wp_wc_download_log: Data: 0.00MB + Index: 0.00MB
wp_wc_gpf_render_cache: Data: 0.00MB + Index: 0.00MB
wp_wc_order_coupon_lookup: Data: 0.00MB + Index: 0.00MB
wp_wc_order_product_lookup: Data: 1.83MB + Index: 1.33MB
wp_wc_order_stats: Data: 0.75MB + Index: 0.41MB
wp_wc_order_tax_lookup: Data: 0.33MB + Index: 0.38MB
wp_wc_product_meta_lookup: Data: 0.20MB + Index: 0.29MB
wp_wc_warranty_products: Data: 0.03MB + Index: 0.06MB
wp_wc_webhooks: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_exported_csv_items: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_gpf_google_taxonomy: Data: 0.86MB + Index: 0.00MB
wp_woocommerce_pinterest: Data: 0.01MB + Index: 0.00MB
wp_woocommerce_shipping_zone_shipping_methods: Data: 0.00MB + Index: 0.00MB
wp_woo_debug: Data: 0.00MB + Index: 0.00MB
wp_yoast_seo_links: Data: 0.64MB + Index: 0.11MB
wp_yoast_seo_meta: Data: 1.31MB + Index: 1.29MB
wp__wordpress_eventlog: Data: 0.06MB + Index: 0.02MB
wp__wordpress_eventlog_details: Data: 0.01MB + Index: 0.00MB

### Post Type Counts ###

attachment: 5722
customize_changeset: 14
custom_css: 1
feature: 4
global_product_addon: 12
nav_menu_item: 202
oembed_cache: 2
page: 49
popup: 1
popup_theme: 6
post: 78
postman_sent_mail: 250
product: 1178
product_variation: 3469
revision: 31
scheduled-action: 2767
shipping_package: 1
shop_coupon: 8
shop_order: 18240
shop_order_refund: 843
sidebar: 1
user_request: 2
warranty_request: 947
wccc: 1
wc_product_tab: 1706
wc_zapier_feed: 1
wishlist: 283

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (64) ###

VaultPress: by Automattic – 2.0.1
Cloudflare Flexible SSL: by One Dollar Plugin – 1.3.0
WooCommerce Currency Switcher - Product Add-ons Integration: by Aelia  – 1.2.8.190502 – Not tested with the active version of WooCommerce
AfterShip - WooCommerce Tracking: by AfterShip – 1.9.9 – Not tested with the active version of WooCommerce
Akismet Anti-Spam: by Automattic – 4.1.2
ELEX WooCommerce Australia Post Shipping With Tracking: by ELEX – 2.4.5 – Not tested with the active version of WooCommerce
Caxton: by PootlePress – 1.10.0
Cloudflare: by John Wineman
Furkan Yilmaz
Junade Ali (Cloudflare Team) – 3.3.3

Colorlib Login Customizer: by Colorlib – 1.2.91
ELEX DHL Express/DHL Paket WooCommerce Shipping with Print Label: by ELEX – 3.9.8 – Not tested with the active version of WooCommerce
Google Tag Manager for Wordpress: by Thomas Geiger – 1.10
Facebook for WooCommerce: by Facebook – 1.9.15 – Not tested with the active version of WooCommerce
Google Captcha Pro (reCAPTCHA) by BestWebSoft: by BestWebSoft – 1.50
Google XML Sitemaps: by Arne Brachhold – 4.1.0
Health Check & Troubleshooting: by The WordPress.org community – 1.3.2
Hide Featured Image: by shahpranaf – 1.3.1
Homepage Control: by WooThemes – 2.0.3
HREFLANG Tags Pro: by DCGWS Internet Solutions – 1.6.5
Instagram Feed Pro Business: by Smash Balloon – 5.0.4
Jetpack by WordPress.com: by Automattic – 7.6
Menu Image: by Rui Guerreiro – 2.9.2
Woocomerce Image Mapper: by Br0 – 2.1 – Not tested with the active version of WooCommerce
Post SMTP: by Yehuda Hassine – 2.0.2
Remove Query Strings From Static Resources: by Speed Up My Website – 1.4
WP Video Popup: by David Vongries – 2.4
Search By SKU - for Woocommerce: by Matthew Lawson – 0.6.1 – Not tested with the active version of WooCommerce
Simple Lightbox: by Archetyped – 2.7.1
Storefront Blog Customiser: by WooCommerce – 1.3.0
Storefront Blog Excerpt: by Wooassist – 1.1.4
Storefront Footer Bar: by WooThemes – 1.0.4
Storefront Hamburger Menu: by WooCommerce – 1.2.2
Storefront Mega Menus: by WooCommerce – 1.6.2 – Not tested with the active version of WooCommerce
Storefront Parallax Hero: by WooCommerce – 1.5.7
Storefront Powerpack: by WooCommerce – 1.5.0
Tracking Code Manager: by IntellyWP – 1.12.0 – Not tested with the active version of WooCommerce
User Role Editor: by Vladimir Garagulya – 4.51.2
Aelia Foundation Classes for WooCommerce: by Aelia – 2.0.4.190201 – Not tested with the active version of WooCommerce
Woocommerce Partial Shipment: by Vikram Singh – 1.7 – Not tested with the active version of WooCommerce
WooCommerce Blocks: by Automattic – 2.2.1 – Not tested with the active version of WooCommerce
WooCommerce Admin: by WooCommerce – 0.16.0 – Not tested with the active version of WooCommerce
Aelia Currency Switcher for WooCommerce: by Aelia – 4.7.8.190709 – Not tested with the active version of WooCommerce
WooCommerce Brands: by WooCommerce – 1.6.9 – Not tested with the active version of WooCommerce
WooCommerce Bulk Pricing: by WP Lab – 1.9.5 – Not tested with the active version of WooCommerce
WooCommerce Cache Handler: by Aelia – 1.0.10.190522 – Not tested with the active version of WooCommerce
WooCommerce Customer/Order CSV Export: by SkyVerge – 4.7.1 – Not tested with the active version of WooCommerce
WooCommerce PayPal Powered by Braintree Gateway: by WooCommerce – 2.2.6 – Not tested with the active version of WooCommerce
WooCommerce Google Analytics Pro: by SkyVerge – 1.7.1 – Not tested with the active version of WooCommerce
WooCommerce Measurement Price Calculator: by SkyVerge – 3.14.2 – Not tested with the active version of WooCommerce
WooCommerce PDF Invoice: by RightPress – 3.2 – Not tested with the active version of WooCommerce
Pinterest for WooCommerce: by premmerce – 1.1.3 – Not tested with the active version of WooCommerce
WooCommerce Product Add-ons: by WooCommerce – 3.0.13 – Not tested with the active version of WooCommerce
WooCommerce Product Documents: by SkyVerge – 1.9.2 – Not tested with the active version of WooCommerce
WooCommerce Sequential Order Numbers Pro: by SkyVerge – 1.13.2 – Not tested with the active version of WooCommerce
WooCommerce Store Catalog PDF Download: by WooCommerce – 1.0.16 – Not tested with the active version of WooCommerce
WooCommerce Tab Manager: by SkyVerge – 1.11.0 – Not tested with the active version of WooCommerce
Aelia Tax Display by Country for WooCommerce: by Aelia – 1.11.0.190719 – Not tested with the active version of WooCommerce
WooCommerce Warranty Requests: by WooCommerce – 1.9.0 – Not tested with the active version of WooCommerce
WooCommerce Xero Integration: by WooCommerce – 1.7.18 – Not tested with the active version of WooCommerce
WooCommerce: by Automattic – 3.6.5
Woopra: by <a href="https://www.woopra.com">Elie Khoury</a> – 2.9.2
Yoast SEO Premium: by Team Yoast – 11.8
WP-Optimize - Clean, Compress, Cache: by David Anderson
Ruhani Rabin
Team Updraft – 3.0.10

Yoast SEO: WooCommerce: by Team Yoast – 11.8 – Not tested with the active version of WooCommerce
YITH Infinite Scrolling Premium: by YITH – 1.1.10

### Inactive Plugins (7) ###

Storefront Pro Blocks: by Pootlepress – 1.3.1 – Not tested with the active version of WooCommerce
WooCommerce Cart Notices: by SkyVerge – 1.9.1 – Not tested with the active version of WooCommerce
WooCommerce Checkout Manager: by Visser Labs – 4.3 – Not tested with the active version of WooCommerce
WooCommerce Smart Coupons: by StoreApps – 4.0.8 – Not tested with the active version of WooCommerce
WooCommerce Subscribe to Newsletter: by WooCommerce – 2.4.0 – Not tested with the active version of WooCommerce
WP Mail SMTP: by WPForms – 1.5.2
Zendesk Support for WordPress: by Zendesk – 1.7.3

### Must Use Plugins (1) ###

Health Check Troubleshooting Mode: by  – 1.6.0

### Settings ###

API Enabled: –
Force SSL: –
Currency: AUD (AUD $)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: downloadable (downloadable)
external (external)
grouped (grouped)
simple (simple)
variable (variable)
virtual (virtual)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #4 - /shop/
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My account: #8 - /my-account/
Terms and conditions: #227 - /terms-and-conditions/

### Theme ###

Name: Storefront Child
Version: 1.0.0
Author URL: http://edisonlightglobes.com
Child Theme: ✔
Parent Theme Name: Storefront
Parent Theme Version: 2.5.1
Parent Theme Author URL: https://woocommerce.com/
WooCommerce Support: ✔

### Templates ###

Overrides: edisonglobes/woocommerce/emails/admin-cancelled-order.php
edisonglobes/woocommerce/emails/email-order-details.php
edisonglobes/woocommerce/emails/email-order-items.php
edisonglobes/woocommerce/emails/email-styles.php


### Store Catalog PDF Download ###

System Temp Directory: ( /tmp )
Upload Directory: Yes ( /home/edisonl1/public_html/Shop/wp-content/uploads/woocommerce-store-catalog-pdf-download/ )
DOMDocument extension: Yes ( 20031129 )
GD Library: Yes
MBString: Yes
URL fopen: No
Template Overrides: 

### Braintree (Credit Card) ###

Environment: Production
Tokenization Enabled: ✔
Debug Mode: Off

### Braintree (PayPal) ###

Environment: Production
Tokenization Enabled: ✔
Debug Mode: Off

### Customer/Order CSV Export ###

Order Export Format: legacy_import
Customer Export Format: import
Automatically Export Orders: disabled
Automatically Export Customers: disabled

### Action Scheduler ###

Complete: 2,750
Oldest: 2019-07-08 10:13:51 +1000
Newest: 2019-08-08 09:07:02 +1000

Pending: 4
Oldest: 2019-08-08 10:01:48 +1000
Newest: 2019-08-08 11:40:52 +1000

Canceled: 0
Oldest: –
Newest: –

In-progress: 0
Oldest: –
Newest: –

Failed: 13
Oldest: 2019-06-04 09:01:54 +1000
Newest: 2019-06-21 14:25:55 +1000
```
</details>

### PR DESCRIPTION
**Pull request by JP19-bit**
### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:
When you press the update button in the modify shipping section of your cart page, a function called 'calculate_shipping()' gets executed (class-wc-shortcode-cart.php). 

Inside this function, there's a particular method "WC()->customer->set_billing_location( [params])" which causes the undesired behavior presented in this bug. By simply deleting it, the problem gets solved. 

Now, when updating your shipping information in the cart page, only the shipping address will change; billing information will remain the same.

Closes #24365  .

### How to test the changes in this Pull Request:

(Same as the steps described in the issue description)
1. Create User with full Billing and Shipping Address in account details
2. Enable Shipping calculator in cart
3. Add items to cart and see that shipping calculator is pre-loaded with users address
4. Change shipping address in shipping calculator
5. Go to checkout page
6. Billing address should be the same (when running this PR code); only shipping address should have changed

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?

### Changelog entry
Prevent billing address from being updated on shipping update.

### CODE REVIEW

**Review by claudiosanches — CHANGES_REQUESTED** [review]
Thanks for your help, but this don't really solve all the problem, since we should fill when is emtpy, we need to check if there's already a billing address set, and then set only if is empty.
Note that `WC()->customer->set_billing_address_to_base();` may change the address as well, and in this case for the shop base address, so we need to check it as well.

**Comment by JuanchoPestana** [comment]
Great Claudio, thanks for the feedback! I'll work on those changes and get commit them once they're done...

**Comment by JuanchoPestana** [comment]
Hey Claudio,

I think this last commit (f7efeda) I made takes care of this:
> Thanks for your help, but this don't really solve all the problem, since we should fill when is empty, we need to check if there's already a billing address set, and then set only if is empty.

Could you please review it and let me know your thoughts?

File: includes/shortcodes/class-wc-shortcode-cart.php [hunk 1]
```diff
@@ -40,7 +40,9 @@ public static function calculate_shipping() {
 			}
 
 			if ( $address['country'] ) {
+				if ( ! WC()->customer->get_billing_first_name() ) {
 				WC()->customer->set_billing_location( $address['country'], $address['state'], $address['postcode'], $address['city'] );
```
Comment (claudiosanches) [inline includes/shortcodes/class-wc-shortcode-cart.php]: Not correctly indented. Missing a tab here.

**Review by claudiosanches — CHANGES_REQUESTED** [review]
Just a minor coding standards issue to fix.

File: includes/shortcodes/class-wc-shortcode-cart.php (hunk 1 above)
Comment (JuanchoPestana) [reply includes/shortcodes/class-wc-shortcode-cart.php]: Thanks Claudio! I just added it...

**Review by claudiosanches — APPROVED** [review]
Thanks for your contribution!
