### PR TITLE
iAPI-powered MiniCart: Support legacy cart events

### LINKED ISSUE #60819: iAPI-powered MiniCart: counter and total price not updated on category page in classic theme
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When Adding product to cart with "add to cart button" in product category using classic theme. New iAPI-powered MiniCart doesn't update counter, sum price values and content. It updates only after full page reloading. 
Previous **react** version of mini-cart dynamically updated counter, sum price values and content of mini cart.

### Expected behavior

Update mini-cart content inside drawer, product count and price value above mini-cart widget after pressing "add to cart" button on product page.

### Actual behavior

Mini-cart content inside drawer, product count and price value above mini-cart widget not updates after pressing "add to cart" button on product page. You have to manually reload page to see changes.

### Steps to reproduce

1. Activate iAPI-powered MiniCart.
2. Activate some classic theme: GeneratePress
3. Go to product category page (product archive)
4. Click add to cart button on product

### WordPress Environment

<details><summary>System Status Report</summary>

```
### WordPress Environment ###

WordPress address (URL): [Redacted]
Site address (URL): [Redacted]
WC Version: 10.1.2
Action Scheduler Version: ✔ 3.9.3
Log Directory Writable: ✔
WP Version: 6.8.2
WP Multisite: –
WP Memory Limit: 512 МБ
WP Debug Mode: –
WP Cron: –
External object cache: ✔

### Server Environment ###

Server Info: nginx/1.26.2
Server Architecture: Linux 5.15.0-144-generic x86_64
PHP Version: 8.1.33
PHP Post Max Size: 150 МБ
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 8.14.1
OpenSSL/3.5.1

SUHOSIN Installed: –
MySQL Version: 11.6.2-MariaDB-ubu2404
Max Upload Size: 150 МБ
Default Timezone is UTC: ✔
fsockopen/cURL: ✔

DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

[REDACTED]

### Post Type Counts ###

adt_product_feed: 4
attachment: 6249
br_filters_group: 13
br_product_filter: 42
cities: 29
condition_group: 9
custom_css: 1
filter-field: 55
filter-seo-rule: 128
filter-set: 10
gp_elements: 23
nav_menu_item: 265
page: 63
post: 20
product: 8019
product_variation: 331
revision: 364
shop_order: 513
shop_order_placehold: 369
sidebar: 5
stackable_temp_post: 1
wp_block: 12
wp_global_styles: 1
wp_navigation: 4
wpmm_theme: 3

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Settings ###

Legacy API Enabled: –
Force SSL: –
Currency: RUB (₽)
Currency Position: right_space
Thousand Separator: 
Decimal Separator: .
Number of Decimals: 0
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: –
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –
Enabled Features: marketplace
email_improvements
blueprint
point_of_sale
custom_order_tables


### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 дней
Level threshold: –
Log directory size: 689 Б

### Theme ###

Name: Theme
Version: 1.0
Author URL: https://tomusborne.com
Child Theme: ✔
Parent Theme Name: GeneratePress
Parent Theme Version: 3.4.0 – 3.6.0
Parent Theme Author URL: https://tomusborne.com
Theme type: Classic theme
WooCommerce Support: ✔

### Templates ###

Overrides: –
```
</details>

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by SantosGuillamot**
### Changes proposed in this Pull Request:

In this PR, I'm adding support to legacy cart events to ensure the minicart is updated when items are added through HTML that doesn't use the most recent methods.

Closes #60819.

### Screenshots or screen recordings:

**Before**

https://github.com/user-attachments/assets/024f253e-5015-4b05-9b6b-7e65e6ccddc4

**After**

https://github.com/user-attachments/assets/f43d039e-f9d0-435e-bbf7-efec65701335

### How to test the changes in this Pull Request:

1. Install a classic theme like Twenty Fifteen.
2. Go to Appeareance -> Widgets.
3. Add the minicart block.
4. Go to the shop page or to a category page.
5. Add a product to the cart.
6. Check the minicart is properly updated.

You can change the minicart block setting to open the drawer and check it works as well.

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message Support legacy event listeners in iAPI-powered minicart.
</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce/changelog/60849-wooplug-5503-iapi-powered-minicart-counter-and-total-price-not-updated-on [hunk 1]
```diff
@@ -0,0 +1,4 @@
+Significance: patch
+Type: fix
+
+Support legacy event listeners
```
Comment (luisherranz) [inline plugins/woocommerce/changelog/60849-wooplug-5503-iapi-powered-minicart-counter-and-total-price-not-updated-on]: I wonder if we should include information here about the block we are improving.

File: plugins/woocommerce/client/blocks/assets/js/base/stores/woocommerce/legacy-events.ts [hunk 2]
```diff
@@ -49,3 +49,25 @@ export const triggerAddedToCartEvent = ( {
...
+	// Name of the native event to dispatch.
+	nativeEventName: string,
+	// Whether the event bubbles.
+	bubbles = false,
+	// Whether the event is cancelable.
+	cancelable = false
+): ( () => void ) => {
+	if ( typeof jQuery !== 'function' ) {
+		return () => void null;
+	}
```
Comment (luisherranz) [inline plugins/woocommerce/client/blocks/assets/js/base/stores/woocommerce/legacy-events.ts]: You are doing this check twice, as it is also in the `iapi-frontend.ts` file.

File: plugins/woocommerce/client/blocks/assets/js/base/stores/woocommerce/legacy-events.ts [hunk 3]
```diff
@@ -49,3 +49,25 @@ export const triggerAddedToCartEvent = ( {
...
+
+	const eventDispatcher = () => {
+		dispatchEvent( nativeEventName, { bubbles, cancelable } );
+	};
+
+	jQuery( document ).on( jQueryEventName, eventDispatcher );
+	return () => jQuery( document ).off( jQueryEventName, eventDispatcher );
```
Comment (luisherranz) [inline plugins/woocommerce/client/blocks/assets/js/base/stores/woocommerce/legacy-events.ts:64]: What this function returns should also be returned in the callback.

File: plugins/woocommerce/client/blocks/assets/js/base/stores/woocommerce/legacy-events.ts [hunk 4]
```diff
@@ -49,3 +49,25 @@ export const triggerAddedToCartEvent = ( {
...
+
+export const translateJQueryEventToNative = (
+	// Name of the jQuery event to listen to.
+	jQueryEventName: string,
+	// Name of the native event to dispatch.
+	nativeEventName: string,
+	// Whether the event bubbles.
+	bubbles = false,
+	// Whether the event is cancelable.
+	cancelable = false
```
Comment (luisherranz) [inline plugins/woocommerce/client/blocks/assets/js/base/stores/woocommerce/legacy-events.ts]: We can skip these until they are necessary.

**Review by luisherranz — CHANGES_REQUESTED** [review]
I'ts okay, but here are a few small improvements.

File: plugins/woocommerce/changelog/60849-wooplug-5503-iapi-powered-minicart-counter-and-total-price-not-updated-on (hunk 1 above)
Comment (SantosGuillamot) [reply plugins/woocommerce/changelog/60849-wooplug-5503-iapi-powered-minicart-counter-and-total-price-not-updated-on]: You're right. Changed here https://github.com/woocommerce/woocommerce/pull/60849/commits/fd7db17ceed5c979c198babe9cb34cee7c4670aa

File: plugins/woocommerce/client/blocks/assets/js/base/stores/woocommerce/legacy-events.ts (hunk 2 above)
Comment (SantosGuillamot) [reply plugins/woocommerce/client/blocks/assets/js/base/stores/woocommerce/legacy-events.ts]: I copied the function as it was in case it is used somewhere else, but you're right that we can always add that later if needed. Changed in this commit: https://github.com/woocommerce/woocommerce/pull/60849/commits/1119869106cd30d180110bfe172abe8967697b9f

File: plugins/woocommerce/client/blocks/assets/js/base/stores/woocommerce/legacy-events.ts (hunk 4 above)
Comment (SantosGuillamot) [reply plugins/woocommerce/client/blocks/assets/js/base/stores/woocommerce/legacy-events.ts]: I copied the function as it was in case it is used somewhere else, but you're right that we can always add that later if needed. Changed in this commit: https://github.com/woocommerce/woocommerce/pull/60849/commits/1119869106cd30d180110bfe172abe8967697b9f

File: plugins/woocommerce/client/blocks/assets/js/base/stores/woocommerce/legacy-events.ts (hunk 3 above)
Comment (SantosGuillamot) [reply plugins/woocommerce/client/blocks/assets/js/base/stores/woocommerce/legacy-events.ts:64]: If I understood you correctly, this should be solved: https://github.com/woocommerce/woocommerce/pull/60849/commits/610b67bbd8d047fbfb42e8129cf30e43f8dc44f6

Comment (SantosGuillamot) [reply plugins/woocommerce/client/blocks/assets/js/base/stores/woocommerce/legacy-events.ts:64]: Not sure what is the cleanest way to handle this, though: https://github.com/woocommerce/woocommerce/pull/60849/commits/615a3b83ae9e6b61db62ea766defc998902b9d8d.

So any ideas are welcome

**Review by luisherranz — APPROVED** [review]
Thanks Mario! LGTM!
