### PR TITLE
Use CRUD in coupons list

### LINKED ISSUE #13292: [2.7] Wrong expiry date in admin coupon overview
Very tiny bug (so I won't make a full report) which hasn't made it to GitHub yet: on the WooCommerce -> Coupons dashboard panel the current day is shown as the expiry date for all coupons, never mind the expiry date you have set ...

I did some digging and it looks like [this line](https://github.com/woocommerce/woocommerce/blob/master/includes/admin/class-wc-admin-post-types.php#L507) in render_shop_coupon_columns() is causing it. The 'expiry_date'-field is refactored to contain a timestamp in WooCommerce 2.7, so the strtotime() makes no sense anymore.

On a side note: it might be nice to use the default date format of the site, so I replaced the line with:

`echo esc_html( date_i18n( get_option( 'date_format', 'F j, Y' ), $expiry_date ) );`

in my test environment and all is fine now.

### PR DESCRIPTION
**Pull request by mikejolley**
Fixes #13292

### CODE REVIEW

File: includes/admin/class-wc-admin-post-types.php [hunk 1]
```diff
@@ -450,28 +450,29 @@ public function render_product_columns( $column ) {
 	 * @param string $column
 	 */
 	public function render_shop_coupon_columns( $column ) {
-		global $post;
+		global $post, $the_coupon;
```
Comment (justinshreve) [inline includes/admin/class-wc-admin-post-types.php]: Does this need to be a global? The only other reference I am seeing to `$the_coupon` is in wc-cart - it's not a global variable there/doesn't seem needed.

Comment (claudiosanches) [inline includes/admin/class-wc-admin-post-types.php]: @justinshreve this method is applied for each column, so if is global, we can do only one query for all columns.
