### PR TITLE
Product Filters: support unicode value

### LINKED ISSUE #61711: Double URL-encoding issue with non-Latin filter slugs (e.g. Armenian)
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

I’m experiencing an issue where WooCommerce filter URLs are getting double-encoded when product attributes filter slugs contain non-Latin (Armenian) characters.

For example, the filter URL looks like this:

`/?filter_book-format=%25d5%25a1%25d5%25b8%25d6%2582%25d5%25a4%25d5%25ab%25d5%25b8%25d5%25a3%25d5%25ab%25d6%2580%25d6%2584&query_type_book-format=or`

When decoded once, it becomes:

`/?filter_book-format=%d5%a1%d5%b8%d6%82%d5%a4%d5%ab%d5%b8%d5%a3%d5%ab%d6%80%d6%84&query_type_book-format=or`

And only after decoding twice, the correct Armenian value appears:

`/?filter_book-format=աուդիոգիրք&query_type_book-format=or`

Screenshots for reference:
https://www.awesomescreenshot.com/image/57094308?key=3c2fbc989a2e7e63fc729ccaa3060b5a
https://www.awesomescreenshot.com/image/57094312?key=5806fdfbc3424ed841cf3186fc3c7d1e

I’ve tested this with all plugins disabled except WooCommerce, and using the default Twenty Twenty-Five theme.

WooCommerce version: 10.3.3
WordPress version: 6.8.3

### Expected behavior

The URLs should be encoded only once, as it works correctly with English filters.

### Actual behavior

WooCommerce filter URLs are getting double-encoded when using non-Latin (Armenian) characters.

### Steps to reproduce

1. Create an attribute and add a term in Armenian to it, for example, name it “Աուդիոգիրք”.
2. Add an Attribute Filter to the shop page.
3. Check the “Աուդիոգիրք” attribute.

### WordPress Environment

<details>

<summary>WordPress Environment</summary>

```
### WordPress Environment ###

WordPress address (URL): http://wpdefault.test
Site address (URL): http://wpdefault.test
WC Version: 10.3.3
Legacy REST API Package Version: The Legacy REST API plugin is not installed on this site.
Action Scheduler Version: ✔ 3.9.3
Log Directory Writable: ✔
WP Version: 6.8.3
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.62 (Win64) OpenSSL/3.0.15 PHP/8.2.28
Server Architecture: Windows NT 10.0 AMD64
PHP Version: 8.2.28
PHP Post Max Size: 2 GB
PHP Time Limit: 36000
PHP Max Input Vars: 1000
cURL Version: 8.7.0-DEV
OpenSSL/3.0.15

SUHOSIN Installed: –
MySQL Version: 8.4.3
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 10.3.3
WC Database Prefix: wp_
Total Database Size: 17.34MB
Database Data Size: 11.00MB
Database Index Size: 6.34MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.17MB + Index: 0.17MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.08MB + Index: 0.06MB + Engine InnoDB
wp_arca_pg_banks: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_arca_pg_config: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_arca_pg_currency: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_arca_pg_errorlogs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_arca_pg_idram_config: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_arca_pg_idram_language: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_arca_pg_language: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_arca_pg_orders: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_arca_pg_pricelist: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_give_campaign_forms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_give_campaigns: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_give_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_give_comments: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_give_donationmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_give_donormeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_give_donors: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_give_formmeta: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_give_log: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_give_migrations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_give_revenue: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_give_sequential_ordering: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_give_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_give_subscriptionmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_give_subscriptions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_icl_background_task: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_content_status: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_core_status: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_languages: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_icl_languages_translations: Data: 0.20MB + Index: 0.17MB + Engine InnoDB
wp_icl_links_post_to_post: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_links_post_to_term: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_locale_map: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_message_status: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_icl_mo_files_domains: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_node: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_reminders: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_string_batches: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_string_packages: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_string_positions: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_icl_string_status: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_string_translations: Data: 1.52MB + Index: 0.36MB + Engine InnoDB
wp_icl_strings: Data: 2.52MB + Index: 2.98MB + Engine InnoDB
wp_icl_translate: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_icl_translate_job: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_translation_batches: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_translation_downloads: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_translation_status: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_icl_translations: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 4.02MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_posts: Data: 0.31MB + Index: 0.06MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_indexable: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_yoast_indexable_hierarchy: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_primary_term: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_yoast_seo_links: Data: 0.02MB + Index: 0.03MB + Engine InnoDB

### Post Type Counts ###

attachment: 13
event: 3
faq: 4
give_forms: 4
give_payment: 2
media_library: 1
page: 26
post: 2
product: 3
publication: 2
revision: 80
shop_order_placehold: 1
testimonial: 1
video: 4
wp_font_face: 36
wp_font_family: 12
wp_global_styles: 3
wp_navigation: 3
wp_template: 3
wp_template_part: 1

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (1) ###

WooCommerce: by Automattic – 10.3.3

### Inactive Plugins (13) ###

Akismet Anti-spam: Spam Protection: by Automattic - Anti-spam Team – 5.5
CNGO Core Modules: by  – 1.0.2
Give - Donation Plugin: by GiveWP – 4.11.0
Hello Dolly: by Matt Mullenweg – 1.7.2
Mashtots Core Modules: by  – 1.0.2
Pinterest for WooCommerce: by WooCommerce – 1.4.21
Planet Studio Payment Gateway for ArCa: by Planet Studio team – 1.5.2
Video Gallery: by Susanna –
WPML Multilingual & Multicurrency for WooCommerce: by OnTheGoSystems – 5.5.2.1
WPML Multilingual CMS: by OnTheGoSystems – 4.8.1
WPML SEO: by OnTheGoSystems – 2.2.3
WPML String Translation: by OnTheGoSystems – 3.4.0
Yoast SEO: by Team Yoast – 25.9

### Settings ###

Legacy API Enabled: –
Force SSL: –
Currency: AMD (AMD)
Currency Position: right_space
Thousand Separator: 
Decimal Separator: ,
Number of Decimals: 0
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –
Enabled Features: analytics
marketplace
order_attribution
site_visibility_badge
remote_logging
email_improvements
blueprint
point_of_sale
custom_order_tables


### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 3 KB

### WC Pages ###

Shop base: #8 - /shop/
Cart: #9 - /cart/ -  Contains the woocommerce/cart block
Checkout: #10 - /checkout/ -  Contains the woocommerce/checkout block
My account: #11 - /my-account/ -  Contains the [woocommerce_my_account] shortcode
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty-Five
Version: 1.3
Author URL: https://wordpress.org
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
Theme type: Block theme
WooCommerce Support: ❌ Not declared

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
onboarding
onboarding-tasks
pattern-toolkit-full-composability
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
printful
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page
launch-your-store

Disabled Features: product-data-views
experimental-blocks
experimental-iapi-mini-cart
experimental-iapi-runtime
coming-soon-newsletter-template
minified-js
product-pre-publish-modal
settings
async-product-editor-category-field
product-editor-template-system
use-wp-horizon
rest-api-v4

Daily Cron: ❌ Not scheduled
Options: ✔
Notes: 74
Onboarding: completed

### Action Scheduler ###

Complete: 228
Oldest: 2025-09-26 09:32:08 +0000
Newest: 2025-10-27 08:27:29 +0000

Failed: 20
Oldest: 2025-08-26 12:27:21 +0000
Newest: 2025-10-02 08:16:34 +0000

Pending: 13
Oldest: 2025-10-27 09:27:29 +0000
Newest: 2025-10-29 12:19:09 +0000


### Status report information ###

Generated at: 2025-10-27 09:05:40 +00:00
```

</details>

### Isolating the problem

- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by dinhtungdu**
### Submission Review Guidelines:

- I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
- I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
- I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
- Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

- Decode filter value before using for navigation so unicode slug can be used for filter

Closes WOOPLUG-5762.
Closes https://github.com/woocommerce/woocommerce/issues/61711.

### Screenshots or screen recordings:

image

### How to test the changes in this Pull Request:

1. Create an attribute and add a term in Armenian to it, for example, name it “Աուդիոգիրք”.
2. Use that attribute for some products.
3. Add an Attribute Filter to the shop page.
4. Check the “Աուդիոգիրք” attribute.
5. Confirm filtered results contain products in step 2.

### Testing that has already taken place:

- `pnpm --filter='@woocommerce/block-library' test:js -- product-filters/__tests__/frontend.test.ts`

### CODE REVIEW

**Review by gigitux — APPROVED** [review]
Thanks for working on this, @dinhtungdu! The PR works as expected! 


| Before | After |
|--------|--------|
| image | image | 



What do you think if we add another unit test that covers this string `Աուդիոգիրք`? 

I noticed that WordPress removes the accent from Café, so it normalizes the string:

https://github.com/user-attachments/assets/e502d1e9-c976-4a43-aa18-09fba70b487e


This doesn't happen for Աուդիոգիրք




https://github.com/user-attachments/assets/f3439150-82d3-46da-b005-0cd28044d76e

**Comment by dinhtungdu** [comment]
> What do you think if we add another unit test that covers this string Աուդիոգիրք?

Good catch! I updated the test to test for `Աուդիոգիրք` instead.

File: plugins/woocommerce/client/blocks/assets/js/blocks/product-filters/frontend.ts [hunk 1]
```diff
@@ -204,7 +204,10 @@ const productFiltersStore = {
 			}
 
 			for ( const key in state.params ) {
-				searchParams.set( key, state.params[ key ] );
+				searchParams.set(
+					key,
+					decodeURIComponent( state.params[ key ] )
+				);
```
[the remark this answers is not in the document]
Comment (dinhtungdu) [reply plugins/woocommerce/client/blocks/assets/js/blocks/product-filters/frontend.ts]: Right, updated!

**Comment by dinhtungdu** [comment]
@gigitux as I updated the logic in the latest commit, can you please take another look at this?

File: plugins/woocommerce/client/blocks/assets/js/blocks/product-filters/frontend.ts [hunk 2]
```diff
@@ -204,7 +204,23 @@ const productFiltersStore = {
...
+				try {
+					decodedValue = decodeURIComponent( value );
+				} catch ( error ) {
+					if ( error instanceof URIError ) {
+						// eslint-disable-next-line no-console
+						console.warn(
+							'woocommerce/product-filters: Failed to decode filter parameter',
+							key,
+							error
+						);
```
Comment (gigitux) [inline plugins/woocommerce/client/blocks/assets/js/blocks/product-filters/frontend.ts:219]: Should we use `@woocommerce/remote-logging` with the `captureException` method?

Comment (dinhtungdu) [reply plugins/woocommerce/client/blocks/assets/js/blocks/product-filters/frontend.ts:219]: It looks like an overkill to me tbh.

Comment (gigitux) [reply plugins/woocommerce/client/blocks/assets/js/blocks/product-filters/frontend.ts:219]: I agree that in this case it could be an overkill, but given that we have a logging library, should we rely on it by default?

Comment (dinhtungdu) [reply plugins/woocommerce/client/blocks/assets/js/blocks/product-filters/frontend.ts:219]: Yes we should always consider using it, but it should be case by case.

**Review by gigitux — APPROVED** [review]
I don't want to block this PR for the `logging` discussion, so LGTM! At the same time, I think that it makes sense to clarify when `@woocommerce/remote-logging` should be used: p1762331452130369-slack-C08LFQ29RT7

**Comment by dinhtungdu** [comment]
> I think that it makes sense to clarify when @woocommerce/remote-logging should be used: p1762331452130369-slack-C08LFQ29RT7

Totally agree!
