### PR TITLE
Fix: Order endpoint returns empty values for 'Any' variation attributes

### LINKED ISSUE #62407: Store API - Order endpoint variation data doesn't match cart endpoint for "Any" variations
#### A clear and concise description of what the bug is.

When a variable product has variations set to "Any" for all attributes, the /cart endpoint correctly
  returns the user's selected attribute values, but the /order endpoint returns empty values for those
  same attributes. This creates a data mismatch between cart and order responses.

1. Empty values: The order endpoint returns empty strings for attribute values instead of the user's  selections
2. Missing attribute\_ prefix: The raw_attribute field is missing the attribute\_ prefix that the cart endpoint includes
3. Duplicate attribute names: Both attributes show "attribute": "Size" in the order response, losing the distinction between the global and custom attribute

#### Write steps here

1. Use the existing Size global attribute or create if missing:
   * Go to Products → Attributes
   * Create a global attribute called "Size"
   * Add terms (e.g., "Small", "Medium", "Large")
2. Create a variable product with 2 attributes:
   \- Create a new variable product
   \- Add the global "Size" attribute - check "Used for variations"
   \- Add a custom attribute also called "size" - check "Used for variations"
   \- Give both attributes some values
3. Create a variation:
   \- Go to Variations tab
   \- Add a variation
   \- Leave both attributes set to "Any..."
   \- Set a price and save
4. Add product to cart via Store API:
   \- Add the product to cart with specific attribute selections
   \- Call the /wc/store/v1/cart endpoint
5. Place an order:
   \- Complete checkout via Store API
   \- Call the /wc/store/v1/order/{id} endpoint

#### A clear and concise description of what you expected to happen.

The variation array in the order endpoint should contain the same user-selected values as the cart
  endpoint:

```
  "variation": [
      {
          "raw_attribute": "attribute_pa_size",
          "attribute": "Size",
          "value": "Large"
      },
      {
          "raw_attribute": "attribute_size",
          "attribute": "size",
          "value": "blue"
      }
  ]
```

Actual Behavior

Cart endpoint (/wc/store/v1/cart) - Correct:
  "variation": \[
      {
          "raw_attribute": "attribute_pa_size",
          "attribute": "Size",
          "value": "Large"
      },
      {
          "raw_attribute": "attribute_size",
          "attribute": "size",
          "value": "blue"
      }
  \]

Order endpoint (/wc/store/v1/order/{id}) - Incorrect:
  "variation": \[
      {
          "raw_attribute": "pa_size",
          "attribute": "Size",
          "value": ""
      },
      {
          "raw_attribute": "size",
          "attribute": "Size",
          "value": ""
      }
  \]

#### Upload files

### PR DESCRIPTION
**Pull request by faisuc**
### Submission Review Guidelines:

- [x] I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
- [x] I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
- [x] I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).

### Changes proposed in this Pull Request:

Fixes a bug where the Store API order endpoint returns empty values for variation attributes when the product variation is set to "Any".

Closes #62407.

### Milestone

- [x] Automatically assign milestone for the **[next WooCommerce version](../blob/trunk/plugins/woocommerce/woocommerce.php#L6)**

> **Note:** Check the box above to have the milestone automatically assigned when merged.
> Alternatively (e.g. for point releases), manually assign the appropriate milestone.

### Changelog entry

- [x] Automatically create a changelog entry from the details below.

<details>

<summary>Changelog Entry Details</summary>

#### Significance

- [x] Patch

#### Type

- [x] Fix - Fixes an existing bug

#### Message

Fix Store API order endpoint returning empty values for "Any" variation attributes. Retrieves customer selections from order metadata to match cart endpoint behavior.

</details>

### CODE REVIEW

File: plugins/woocommerce/src/StoreApi/Schemas/V1/OrderItemSchema.php [hunk 1]
```diff
@@ -121,4 +121,48 @@ public function get_totals( $order_item ) {
...
+			if ( empty( $meta_key ) || '' === $meta_value || ! is_scalar( $meta_value ) || strpos( $meta_key, '_' ) === 0 ) {
+				continue;
+			}
+
+			$is_variation_attribute = false;
+
+			if ( strpos( $meta_key, 'pa_' ) === 0 ) {
+				$is_variation_attribute = true;
+			} else {
+				$product_attributes = $product->get_parent_id() ? wc_get_product( $product->get_parent_id() )->get_attributes() : array();
```
Comment (mikejolley) [inline plugins/woocommerce/src/StoreApi/Schemas/V1/OrderItemSchema.php]: As Coderabbit said, doing this on multiple loops can be inefficient. Can we cache this? It might not be called at all, so rather than just do it at the top of this method, you could create a new protected method to get the parent product attributes and cache them to a class variable. i.e. `get_parent_product_attributes()`. Ensure you add error handling in case the product is not found because right now this could break if `wc_get_product` returns false.

File: plugins/woocommerce/src/StoreApi/Schemas/V1/OrderItemSchema.php [hunk 2]
```diff
@@ -121,4 +121,48 @@ public function get_totals( $order_item ) {
...
+				foreach ( $product_attributes as $attribute ) {
+					if ( strtolower( $attribute->get_name() ) === strtolower( $meta_key ) ) {
+						$is_variation_attribute = true;
+						break;
+					}
+				}
+			}
+
+			if ( $is_variation_attribute ) {
+				$variation_data[ 'attribute_' . $meta_key ] = $meta_value;
```
Comment (mikejolley) [inline plugins/woocommerce/src/StoreApi/Schemas/V1/OrderItemSchema.php]: Should `$meta_key` be formatted here? You could use the `wc_variation_attribute_name()` function to correctly format this.

**Review by mikejolley — CHANGES_REQUESTED** [review]
Thanks for looking into this and including tests. There is some feedback from coderabbit and myself to improve some of the logic. Cheers.

**Comment by faisuc** [comment]
@mikejolley Thanks for the feedback. I've made the changes.

**Review by mikejolley — APPROVED** [review]
Thanks for making those changes, this is looking much better now.

I tested this by submitting an order for variable products with a variety of attributes, some set to "all" in admin, and checking the API response. Compared to cart route, it matched. And the order was shown correcrly in the backend as well. 

I think once the CI is green this is good to merge. Thank you.
