### PR TITLE
Ensuring transient value is an array

### LINKED ISSUE #61981: WooCommerce Helper updater fatal error on PHP 8.4 when cached update transient contains unexpected string data
## **Describe the bug**

A merchants site (10488304-zen) is repeatedly entering recovery mode due to a fatal error inside WC_Helper_Updater::\_update_check(). The crash occurs when the updater receives malformed or corrupted update data from the \_woocommerce_helper_updates transient. PHP 8.4 treats array-access-on-string as a fatal error, so the updater cannot complete and the admin cannot load.

Rolling back WooCommerce (10.3.5 > 10.3.3) temporarily resolves it, but the issue returns as soon as the cached update data is read again. The problem appears to be triggered by strict type handling in PHP 8.4 combined with helper update data that is stored as a string instead of an array.

## **To Reproduce**

These steps are based on the merchants logs and local code analysis (not yet fully reproducible on my side):

```
1.	Site runs WooCommerce 10.3.3–10.3.5 on PHP 8.4.x
2.	A malformed or incomplete helper update payload is stored in _woocommerce_helper_updates
3.	Visiting the WP admin triggers the update transient check
4.	WC_Helper_Updater::_update_check() attempts to access array offsets, but the value is a string
5.	PHP 8.4 throws: TypeError: Cannot access offset of type string on string
6.	Site enters recovery mode
```

## **Expected behavior**

WooCommerce Helper updater should validate update data types before attempting array access. If the update payload is malformed or non-array, it should safely bail, refresh the transient, or log a warning instead of crashing the admin.

## **Screenshots**

If applicable, add screenshots to help explain your problem. (or upload as files via Asks)

## Environment

Please fill out any of the below that applies

**Operating System/Device**

- [ ] Windows
- [ ] MacOS
- [ ] Linux
- [ ] iPhone
- [ ] Samsung
- [ ] Other (add in additional context field)

**Version:** Add the Desktop OS and/or Device version(s) here

**Browser**

- [ ] Desktop Edge
- [ ] Desktop Chrome/Chromium
- [ ] Desktop Safari
- [ ] Mobile Edge
- [ ] Mobile Chrome/Chromium
- [ ] Mobile Safari
- [ ] Other (add in additional context field)

**Version:** Add the browser version(s) here.

## **Additional context**

Uncaught TypeError: Cannot access offset of type string on string
in wp-content/plugins/woocommerce/includes/admin/helper/class-wc-helper-updater.php:623
Stack trace:
#0 WC_Helper_Updater::\_update_check()
#1 WC_Helper_Updater::get_update_data()
#2 WC_Helper_Updater::transient_update_plugins()
...

### PR DESCRIPTION
**Pull request by gedex**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

This PR fixes a critical PHP 8.4 compatibility issue where the WooCommerce Helper updater crashes with a fatal `TypeError` when the `_woocommerce_helper_updates` transient contains malformed string data instead of the expected array.

**Problem:**
- On PHP 8.4, attempting to access array offsets on a string value throws a fatal `TypeError`
- The `WC_Helper_Updater::_update_check()` method was attempting to access `$data['hash']` and `$data['products']` without validating that `$data` is actually an array
- When the transient becomes corrupted or contains unexpected string data, fatal error is thrown

**Solution:**
- Add type validation to ensure `$data` is an array before attempting array access
- Changed condition from `if ( false !== $data )` to `if ( false !== $data && is_array( $data ) )`
- This allows the updater to safely handle malformed transient data by treating it as a cache miss and refreshing the data

Closes #61981
Closes WOOPLUG-5866

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

**Testing the fix:**

1. Set up a test site with PHP 8.4 and WooCommerce 10.3.5+
2. Manually corrupt the transient to simulate the issue:
   ```
   pnpm wp-env run cli wp transient set _woocommerce_helper_updates ''
   ```

3. Visit WooCommerce Extensions page at http://localhost:8888/wp-admin/admin.php?page=wc-admin&path=%2Fextensions
4. Verify that the site loads without errors
5. Check that the helper updates functionality continues to work normally

**Expected behavior:**

No fatal errors occur

### Testing that has already taken place:

- Code review and analysis of the crash scenario from merchant logs (site 10488304-zen)
- Verification that the fix handles the specific PHP 8.4 TypeError mentioned in issue #61981
- Confirmed that adding `is_array()` check prevents array access on string values
- The fix is minimal and defensive, only adding type validation without changing existing logic

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message

Fix PHP 8.4 fatal error in WooCommerce Helper updater when transient contains malformed data

</details>

### CODE REVIEW

**Review by KokkieH — APPROVED** [review]
Confirmed I see the error on `trunk`. Page loads without errors on this branch.

**Comment by gedex** [comment]
I added unit test for `WC_Helper_Updater` in 62acedd874482c286d43999f36109cd36de8d6c5.

```
pnpm test:php:env --filter=WC_Helper_Updater_Test

> @woocommerce/plugin-woocommerce@10.5.0 test:php:env /Users/akeda/code/woocommerce/plugins/woocommerce
> sh ./client/blocks/bin/copy-blocks-json.sh && wp-env run --env-cwd='wp-content/plugins/woocommerce' tests-cli vendor/bin/phpunit -c phpunit.xml --verbose "--filter=WC_Helper_Updater_Test"

ℹ Starting 'vendor/bin/phpunit -c phpunit.xml --verbose --filter=WC_Helper_Updater_Test' on the tests-cli container.

Installing...
Running as single site... To run multisite, use -c tests/phpunit/multisite.xml
Installing WooCommerce...
Not running ajax tests. To execute these, use --group ajax.
Not running ms-files tests. To execute these, use --group ms-files.
Not running external-http tests. To execute these, use --group external-http.
PHPUnit 9.6.29 by Sebastian Bergmann and contributors.

Runtime:       PHP 8.1.33
Configuration: phpunit.xml

.........                                                           9 / 9 (100%)

Time: 00:00.091, Memory: 171.00 MB

OK (9 tests, 15 assertions)
✔ Ran `vendor/bin/phpunit -c phpunit.xml --verbose --filter=WC_Helper_Updater_Test` in 'tests-cli'. (in 3s 274ms)
```

File: plugins/woocommerce/includes/admin/helper/class-wc-helper-updater.php [hunk 1]
```diff
@@ -619,7 +619,7 @@ private static function _update_check( $payload ) {
 
 		$cache_key = '_woocommerce_helper_updates';
 		$data      = get_transient( $cache_key );
-		if ( false !== $data ) {
+		if ( false !== $data && is_array( $data ) ) {
 			if ( hash_equals( $hash, $data['hash'] ) ) {
```
Comment (mcliwanow) [inline plugins/woocommerce/includes/admin/helper/class-wc-helper-updater.php]: For an abundance of caution, should we also check if `$data['products']` is an array?

Comment (gedex) [reply plugins/woocommerce/includes/admin/helper/class-wc-helper-updater.php]: Sounds reasonable to prevent potential fatal error. We should also verify `$data['hash']`.

Comment (gedex) [reply plugins/woocommerce/includes/admin/helper/class-wc-helper-updater.php]: Added helper method to check (with additional test cases) in 6fbf360500c2efc4b165e26be60eb430abe47d16.
