### PR TITLE
Normalise state keys

### LINKED ISSUE #15977: Getting "Billing State / County is not valid." when selecting Mexico as a country and Edo de Mexico as state
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce
- [x] This is not a usage question (Those should be directed to the [community](https://wordpress.org/support/plugin/woocommerce), unless this is a question about a premium plugin in which you should [use the helpdesk](https://woocommerce.com/my-account/tickets/) for official extensions or contact the author of 3rd party extensions)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Set your general settings to 
2. Checkout with a product and select `Edo de Mexico` as Billing state
3. Click `Place Order` to be greeted with:  

## Expected behavior and actual behavior

I was expecting the order to be placed but got an error from the Billing state field.

## Environment

<details>

### WordPress Environment ###

Home URL: http://wootest.dev
Site URL: http://wootest.dev
WC Version: 3.1.0
Log Directory Writable: ✔
WP Version: 4.8
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: nginx/1.13.1
PHP Version: 7.0.20-2~ubuntu14.04.1+deb.sury.org+1
PHP Post Max Size: 1 GB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.35.0
OpenSSL/1.0.1f

SUHOSIN Installed: –
Max Upload Size: 1 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.1.0
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (1) ###

WooCommerce: by Automattic – 3.1.0

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: MXN ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #4 - /?page_id=4
Cart: #5 - /?page_id=5
Checkout: #6 - /?page_id=6
My account: #7 - /?page_id=7

### Theme ###

Name: Twenty Sixteen
Version: 1.3
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

</details>

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently

@mattyza @mikejolley

### PR DESCRIPTION
**Pull request by mikejolley**
MX has lowercase state keys which break the validation.

I’ve applied this to 3.1 because master has correct state codes. This should still be cherry picked.

Fixes #15977

### CODE REVIEW

File: includes/class-wc-checkout.php [hunk 1]
```diff
@@ -655,15 +655,15 @@ protected function validate_posted_data( &$data, &$errors ) {
...
+						$valid_state_values = array_map( 'wc_strtoupper', array_flip( array_map( 'wc_strtoupper', $valid_states ) ) );
 						$data[ $key ]       = wc_strtoupper( $data[ $key ] );
 
 						if ( isset( $valid_state_values[ $data[ $key ] ] ) ) {
 							// With this part we consider state value to be valid as well, convert it to the state key for the valid_states check below.
 							$data[ $key ] = $valid_state_values[ $data[ $key ] ];
 						}
 
-						if ( ! in_array( $data[ $key ], array_keys( $valid_states ) ) ) {
+						if ( ! in_array( $data[ $key ], array_values( $valid_state_values ) ) ) {
```
Comment (claudiosanches) [inline includes/class-wc-checkout.php]: `in_array()` already look for values by default, so no need of `array_values()`.

**Comment by mayakid** [comment]
Hi I am having problems with the state again. The box where the state comes in is small and you cannot see any of the states provided.
captura de pantalla 2017-10-17 a la s 13 47 48
