### PR TITLE
Fix report days calculation to account for DST

### LINKED ISSUE #32220: When requesting to download a Revenue Report for the Last Month no report is emailed
### Describe the bug

Ticket: 4438598-zen

When requesting to download a Revenue Report for the Last Month no report is emailed when not a size to be immediately downloaded.

last-month-revenue-report

Other reports like Year to date etc are all emailed when requested and too large to initiate an immediate download.

### To Reproduce

1. Go to 'Analytics > Revenue'
2. Set the report you wish to be exported to be **Last Month** ( Note you'll need enough orders that the report will be generated and sent as an email )
3. Click the download button to generate the report.
4. Have WP Mail Logging installed to catch all outgoing emails.
5. See that no report email with a download link is emailed for the Last Month.

### Actual behavior:

When requesting to download a Revenue Report for the Last Month no report is emailed when not a size to be immediately downloaded.

last-month-revenue-report

Looking at **WooCommerce > Status > Action Scheduler** I can see that the `woocommerce_admin_email_report_download_link` action for the requested revenue report being fired as pending and then complete when the process has ran.

**Processing action ( generating report )**

pending-revenue-email-report

**Completed action ( report generated )**

completed-revenue-email-report

I know the Last Month Revenue report has been created on the server as it can be downloaded via a direct link by adding the scheduled action report ID to the end of a report download link.

report-action-id

`wp-admin/?action=woocommerce_admin_download_report_csv&filename=wc-revenue-report-export-16365562862955`

revenue-report-csv

The report however is never emailed to the store owner.

Other reports generated within Analytics > Revenue like **Year to Date** are however emailed successfully to the store owner.

wp-mail-logging year-to-date

It seems like the only report date range affected is the **Last Month** one which does not send an email for that generated report.

### Expected behaviour

We expect a report to be emailed to the store owner when generating a **Last Month** Revenue report which is too large to be instantly downloaded.

## Software

* WordPress v5.8.1
* WooCommerce v5.9.0

Also tested with WooCommerce Admin v2.8.0 and received the same results.

## Other user reports of the same behaviour.

* Ticket: 4438007-zen
* Ticket: 4439771-zen

### PR DESCRIPTION
**Pull request by joshuatf**
### All Submissions:

-   [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
-   [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
-   [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Updates the calculation for days between two dates to fix issues where DST based timezones would miscalculate days and cause reports to not be exported properly.

Closes #32220  .

### How to test the changes in this Pull Request:

1. Select a timezone (US, London, etc) that utilizes DST in your site's General settings
2. Install an email logging plugin
3. Go to the Revenue report
4. Select October 1 - October 31 as a custom date
5. Click "Download" to export the report
6. Check your email logs to make sure the report is sent and can be downloaded
7. Check that the number of "days" is correct in the summary numbers at the bottom of the Revenue report
8. Smoketest other areas of the app to make sure no regressions have occurred

### Other information:

-   [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
-   [ ] Have you written new tests for your changes, as applicable?
-   [ ] Have you successfully run tests with your changes locally?
-   [ ] Have you created a changelog file for each project being changed, ie `pnpm nx changelog <project>`?

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

**Comment by botwoo** [comment]
:bar_chart: Test reports for this pull request have been published and are accessible through the following links:

- [REST API Test Report](https://woocommerce.github.io/woocommerce-test-reports/pr/33036/api/)
- E2E Test Report (TBC)

Latest commit referenced in the reports: `Update tests to use EST timezone` 15decc9301f9bbaa75b1e9b374b7f818c006db06
This comment will automatically be updated with the latest referenced commit when you push new changes to this pull request.

---

_Visit the [WooCommerce Test Reports](https://woocommerce.github.io/woocommerce-test-reports) homepage to view all published reports. See the [FAQs](https://github.com/woocommerce/woocommerce-test-reports/wiki/FAQs) page if you're having problems accessing them._

File: plugins/woocommerce/tests/legacy/unit-tests/woocommerce-admin/api/reports-interval.php [hunk 1]
```diff
@@ -612,6 +612,20 @@ public function test_intervals_between() {
...
+				'week_start' => 1,
+				'intervals'  => array(
+					'hour'    => 31 * 24,
+					'day'     => 31,
+					'week'    => 5,
+					'month'   => 1,
+					'quarter' => 1,
+					'year'    => 1,
+				),
+			),
```
Comment (louwie17) [inline plugins/woocommerce/tests/legacy/unit-tests/woocommerce-admin/api/reports-interval.php:629]: Should we be explicitly setting the timezone to a DST adhering timezone for this test? Given it might not be using that as the timezone?

File: plugins/woocommerce/src/Admin/API/Reports/TimeInterval.php [hunk 2]
```diff
@@ -229,17 +229,14 @@ public static function intervals_between( $start_datetime, $end_datetime, $inter
...
 			case 'day':
-				$end_timestamp      = (int) $end_datetime->format( 'U' );
-				$start_timestamp    = (int) $start_datetime->format( 'U' );
-				$addendum           = 0;
+				$days               = $start_datetime->diff( $end_datetime )->format( '%r%a' );
 				$end_hour_min_sec   = (int) $end_datetime->format( 'H' ) * HOUR_IN_SECONDS + (int) $end_datetime->format( 'i' ) * MINUTE_IN_SECONDS + (int) $end_datetime->format( 's' );
 				$start_hour_min_sec = (int) $start_datetime->format( 'H' ) * HOUR_IN_SECONDS + (int) $start_datetime->format( 'i' ) * MINUTE_IN_SECONDS + (int) $start_datetime->format( 's' );
 				if ( $end_hour_min_sec < $start_hour_min_sec ) {
-					$addendum = 1;
+					$days++;
```
Comment (louwie17) [inline plugins/woocommerce/src/Admin/API/Reports/TimeInterval.php:236]: I don't quite understand this condition, at-least it was never hit when running the monthly reports.
Is this only relevant when looking at specific times of day? (which I don't think we can do, or at-least not in revenue).
If this logic is specifically for DST, should we add a comment describing it?

File: plugins/woocommerce/src/Admin/API/Reports/TimeInterval.php [hunk 3]
```diff
@@ -229,17 +229,14 @@ public static function intervals_between( $start_datetime, $end_datetime, $inter
 
 				return (int) floor( ( (int) $diff_timestamp ) / HOUR_IN_SECONDS ) + 1 + $addendum;
 			case 'day':
-				$end_timestamp      = (int) $end_datetime->format( 'U' );
-				$start_timestamp    = (int) $start_datetime->format( 'U' );
-				$addendum           = 0;
+				$days               = $start_datetime->diff( $end_datetime )->format( '%r%a' );
```
Comment (louwie17) [inline plugins/woocommerce/src/Admin/API/Reports/TimeInterval.php:232]: Nice use of `diff` instead 💯

**Review by louwie17 — COMMENTED** [review]
This tested well, and thanks for fixing this 🥇 
I did leave a couple questions, as I was slightly confused by some of the logic in there. I trust your changes, but want to make sure.

File: plugins/woocommerce/tests/legacy/unit-tests/woocommerce-admin/api/reports-interval.php (hunk 1 above)
Comment (joshuatf) [reply plugins/woocommerce/tests/legacy/unit-tests/woocommerce-admin/api/reports-interval.php:629]: Good idea.  Updated to set a specific timezone in https://github.com/woocommerce/woocommerce/pull/33036/commits/15decc9301f9bbaa75b1e9b374b7f818c006db06.

File: plugins/woocommerce/src/Admin/API/Reports/TimeInterval.php (hunk 2 above)
Comment (joshuatf) [reply plugins/woocommerce/src/Admin/API/Reports/TimeInterval.php:236]: This is pre-existing logic and unrelated to the DST logic.  I updated where the variable gets added to make it more clear, but logic here remains the same.

You can see similar logic in other time units, but I believe how this works is counting partial days.  For example, the diff of days between 10-01-2022 12:00:00 and 10-02-2022 11:00:00 would be 0 since no full days exist.  Adding the check for end time allows us to count those partial days.

Comment (louwie17) [reply plugins/woocommerce/src/Admin/API/Reports/TimeInterval.php:236]: Thanks for the extra explanation, that clarifies that.

**Review by louwie17 — APPROVED** [review]
LGTM 🚀 thanks for the update in the tests and giving some extra clarification on the logic. :shipit:
