### PR TITLE
Fix clearing search input in In-App Marketplace

### LINKED ISSUE #51687: Clearing the Extensions Search removes the search text, but the results remain filtered.
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

It seems this is already a "[known issue](https://github.com/woocommerce/woocommerce/pull/51413#issuecomment-2371402693)," but I'm logging it here for potential improvement. While testing the PR (https://github.com/woocommerce/woocommerce/pull/51413) (more context: pf59Ax-219-p2), I noticed that clicking the "X" clears the search text, but the results remain filtered. From a user experience perspective, it’s unclear how to return to the full list of results. It would be great to improve consistency by fully clearing the results and showing the original extensions list.

See video:

https://github.com/user-attachments/assets/505a4fa3-3a07-4467-a9f0-4c089881eca2

See this comment for context: https://github.com/woocommerce/woocommerce/pull/51413#issuecomment-2368876030

### Expected behavior

Clicking the "X" should reset the results or, at the very least, provide an option to view the original list of extensions.

### Actual behavior

Clicking the "X" clears the text, but the results remain filtered.

### Steps to reproduce

1. Go to `/wp-admin/admin.php?page=wc-admin`
2. Search for something.
3. See that the results are filtered.
4. Clear the results, clicking "X".
6. See that the results remain filtered. 

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://wootestautomata.wpcomstaging.com
Site address (URL): https://wootestautomata.wpcomstaging.com
WC Version: 9.4.0-beta.1
Legacy REST API Package Version: The Legacy REST API plugin is not installed on this site.
Action Scheduler Version: ✔ 3.8.2
Log Directory Writable: ✔
WP Version: 6.6.2
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_GB
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 8.1.29
PHP Post Max Size: 2 GB
PHP Time Limit: 1200
PHP Max Input Vars: 6144
cURL Version: 8.7.1
OpenSSL/3.0.11

SUHOSIN Installed: –
MySQL Version: 10.11.9-MariaDB-log
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 9.4.0
WC Database Prefix: wp_
Total Database Size: 16.72MB
Database Data Size: 10.55MB
Database Index Size: 6.17MB
wp_woocommerce_sessions: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 2.50MB + Index: 1.39MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 1.52MB + Index: 0.70MB + Engine InnoDB
wp_automatewoo_abandoned_carts: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_automatewoo_customers: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_automatewoo_customer_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_guests: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_automatewoo_guest_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_log_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_queue: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_queue_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_gla_attribute_mapping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gla_budget_recommendations: Data: 0.19MB + Index: 0.14MB + Engine InnoDB
wp_gla_merchant_issues: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gla_shipping_rates: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gla_shipping_times: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_jetpack_sync_queue: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_automations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_automation_runs: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_mailpoet_automation_run_logs: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_mailpoet_automation_run_subjects: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_automation_triggers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_automation_versions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_custom_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_dynamic_segment_filters: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_feature_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_forms: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletters: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_newsletter_links: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_newsletter_option: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_option_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_posts: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_segment: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_templates: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_scheduled_tasks: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_scheduled_task_subscribers: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_segments: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_sending_queues: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_settings: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_statistics_bounces: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_statistics_clicks: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_statistics_forms: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_statistics_newsletters: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_statistics_opens: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_mailpoet_statistics_unsubscribes: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_statistics_woocommerce_purchases: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_mailpoet_stats_notifications: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_subscribers: Data: 0.02MB + Index: 0.23MB + Engine InnoDB
wp_mailpoet_subscriber_custom_field: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_subscriber_ips: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_subscriber_segment: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_subscriber_tag: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_tags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_user_agents: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_user_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 1.41MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_posts: Data: 0.08MB + Index: 0.06MB + Engine InnoDB
wp_taxjar_record_queue: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_bundle_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_bis_activity: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_bis_notifications: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_woocommerce_bis_notificationsmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_bundled_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_bundled_items: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_gc_activity: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_gc_cards: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_gc_cardsmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_prl_amplifier_cache: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_prl_deploymentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_prl_deployments: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_prl_frequencies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_prl_generator_queue: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_prl_tracking_conversions: Data: 0.02MB + Index: 0.05MB + Engine InnoDB

### Post Type Counts ###

attachment: 14
jetpack_migration: 2
mailpoet_page: 1
page: 10
post: 2
product: 4
revision: 3
wp_global_styles: 1
wp_navigation: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (38) ###

Akismet Anti-spam: Spam Protection: by Automattic - Anti-spam Team – 5.3.3
AutomateWoo: by WooCommerce – 6.1.0
Blaze Ads: by Automattic – 0.4.1
Crowdsignal Forms: by Automattic – 1.7.2
Facebook for WooCommerce: by Facebook – 3.2.9
WordPress.com Editing Toolkit: by Automattic – 4.30504
Google for WooCommerce: by WooCommerce – 2.8.5
Gutenberg: by Gutenberg Team – 19.2.0
Jetpack: by Automattic – 13.9-a.7
Layout Grid: by Automattic – 1.8.4
MailPoet Premium: by MailPoet – 5.2.0
MailPoet: by MailPoet – 5.2.2
Page Optimize: by Automattic – 0.5.5
Pinterest for WooCommerce: by WooCommerce – 1.4.10
Crowdsignal Polls & Ratings: by Automattic
Inc. – 3.1.2

TaxJar - Sales Tax Automation for WooCommerce: by TaxJar – 4.2.3
TikTok: by TikTok – 1.2.8
Woo AI: by WooCommerce – 0.6.0
Avalara AvaTax: by Avalara – 2.8.2
Woo Back In Stock Notifications: by Woo – 2.0.3
WooCommerce Brands: by WooCommerce – 1.7.6
WooCommerce EU VAT Number: by WooCommerce – 2.9.7
WooCommerce Gift Cards: by Woo – 2.0.4
Google Analytics for WooCommerce: by WooCommerce – 2.1.7
Woo Min/Max Quantities: by Woo – 5.0.1
WooPayments: by WooCommerce – 8.2.2
WooCommerce Product Add-Ons: by Woo – 7.1.0
WooCommerce Product Bundles: by Woo – 8.1.0
WooCommerce Product Recommendations: by Woo – 4.1.0
WooCommerce Shipping & Tax: by WooCommerce – 2.8.2
WooCommerce Shipment Tracking: by WooCommerce – 2.5.1
WooCommerce Australia Post Shipping: by WooCommerce – 2.6.3
WooCommerce Canada Post Shipping: by WooCommerce – 3.0.1
WooCommerce FedEx Shipping: by WooCommerce – 4.1.1
WooCommerce Royal Mail: by WooCommerce – 3.4.0
WooCommerce UPS Shipping: by WooCommerce – 3.7.1
WooCommerce USPS Shipping: by WooCommerce – 5.0.0
WooCommerce: by Automattic – 9.4.0-beta.1

### Inactive Plugins (1) ###

Classic Editor: by WordPress Contributors – 1.6.4

### Dropin Plugins () ###

advanced-cache.php: advanced-cache.php
object-cache.php: Memcached

### Must Use Plugins (1) ###

wpcomsh-loader.php: by  –

### Settings ###

Legacy API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: bundle (bundle)
external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 46 KB

### WC Pages ###

Shop base: #36 - /shop/
Basket: #37 - /basket/ -  Contains the woocommerce/cart block
Checkout: #38 - /checkout/ -  Contains the woocommerce/checkout block
My account: #39 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Tsubaki
Version: 1.3.0
Author URL: https://automattic.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build
personally we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: /srv/htdocs/wp-content/plugins/woocommerce/templates/block-notices/error.php
/srv/htdocs/wp-content/plugins/woocommerce/templates/block-notices/notice.php
/srv/htdocs/wp-content/plugins/woocommerce/templates/block-notices/success.php
/wordpress/themes/premium/tsubaki/parts/mini-cart.html
/wordpress/themes/premium/tsubaki/templates/archive-product.html
/wordpress/themes/premium/tsubaki/templates/product-search-results.html
/wordpress/themes/premium/tsubaki/templates/single-product.html
/wordpress/themes/premium/tsubaki/templates/taxonomy-product_cat.html
/wordpress/themes/premium/tsubaki/templates/taxonomy-product_tag.html

### WooPayments ###

Version: 8.2.2
Connected to WPCOM: Yes
WPCOM Blog ID: 237299165
Account ID: ❌ Not connected
Logging: Disabled

### MailPoet ###

Sending Method: MailPoet
Send all site's emails with: Default WordPress sending method
Task Scheduler method: Action Scheduler
Cron ping URL: https://wootestautomata.wpcomstaging.com?mailpoet_router&endpoint=cron_daemon&action=ping

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
onboarding
onboarding-tasks
pattern-toolkit-full-composability
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
printful
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: product-data-views
experimental-blocks
minified-js
navigation
product-pre-publish-modal
settings
async-product-editor-category-field
launch-your-store
product-editor-template-system
blueprint
reactify-classic-payments-settings
use-wp-horizon

Daily Cron: ✔ Next scheduled: 2024-09-25 16:29:09 +02:00
Options: ✔
Notes: 56
Onboarding: skipped

### Back In Stock ###

Database Version: 2.0.3
Loopback Test: ✔

### Gift Cards ###

Database Version: 2.0.4
Loopback Test: ✔
Task Queueing Test: ✔

### Product Bundles ###

Database Version: 8.1.0
Loopback Test: ✔
Template Overrides: –

### Action Scheduler ###

Complete: 3,791
Oldest: 2024-09-23 18:32:13 +0200
Newest: 2024-09-25 16:34:17 +0200

Pending: 15
Oldest: 2024-09-25 16:35:18 +0200
Newest: 2024-09-26 00:00:00 +0200

### Product Recommendations ###

Database Version: 4.1.0
Loopback Test: ✔
Task Queueing Test: ✔
Page Cache Test: No cache detected

### Status report information ###

Generated at: 2024-09-25 16:35:54 +02:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by mcliwanow**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Fix clearing search input in In-App Marketplace. Currently, clicking on X icon clears the input but doesn't update displayed results. This PR should fix it.

Closes 21868-gh-Automattic/woocommerce.com.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Checkout this branch and get a new build
2. Visit the In-App Marketplace and visit[ the Extensions page](http://localhost:8888/wp-admin/admin.php?page=wc-admin&tab=extensions&path=%2Fextensions&category=_all).
3. Use search input to filter extensions
4. Once extensions are filtered, use 'X' (close) icon in the search control to clear the input
5. Confirm that using the icon clears the input, refreshes properly list of displayed products, and properly updates URL (removing `term` query parameter)
6. Try also clearing the input by removing all text and clicking Enter to submit it. It should work the same as when you would use the close icon.
7. Check that functionality works properly in other tabs too
8. Please test around this issue

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

Fix clearing search input in In-App Marketplace using close icon

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

image

### CODE REVIEW

File: plugins/woocommerce-admin/client/marketplace/components/search/search.tsx [hunk 1]
```diff
@@ -64,13 +67,19 @@ function Search(): JSX.Element {
...
+	};
+
 	return (
 		<SearchControl
 			label={ searchPlaceholder }
 			placeholder={ searchPlaceholder }
 			value={ searchTerm }
 			onChange={ setSearchTerm }
 			onKeyUp={ handleKeyUp }
+			onClose={ onClose }
```
Comment (bor0) [inline plugins/woocommerce-admin/client/marketplace/components/search/search.tsx:82]: Wow, there's a `onClose`? That is neat!

**Review by bor0 — APPROVED** [review]
Tests well! Thanks for tackling this.

File: plugins/woocommerce-admin/client/marketplace/components/search/search.tsx (hunk 1 above)
Comment (mcliwanow) [reply plugins/woocommerce-admin/client/marketplace/components/search/search.tsx:82]: Yup, it's in the docs https://wordpress.github.io/gutenberg/?path=/docs/components-searchcontrol--docs :)
