### PR TITLE
Fix `TableCard`s menu being displayed off the page

### LINKED ISSUE #43256: Columns popover in Analytics displays off the page – along with downstream usage of `TableCard` (WooPayments)
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

The `components-dropdown__content` popover, which allows a merchant to enable/disable columns in Analytics (and elsewhere), currently displays in such a fashion that it runs off of the page. Changing the size of the window does not alleviate the issue.

If I disable the `position: absolute;` styling of this element via my browser's developer tools, this popover displays as expected and does not run off the page.

### Expected behavior

The columns popover menu is completely visible.

### Actual behavior

The columns popover menu is obscured because it runs off the page. This affects other plugins that use these same components, such as the Transactions, Deposits, and Disputes columns in WooPayments.

### Steps to reproduce

1. Navigate to an Analytics sub-page (e.g., Analytics > Revenue).
2. Select the ellipsis menu to change what columns are visible.
3. Note that the column options run off the page and are not fully visible.

### WordPress Environment

```
### WordPress Environment ###

WordPress address (URL): https://wcpaytest.jurassic.tube
Site address (URL): https://wcpaytest.jurassic.tube
WC Version: 8.4.0
REST API Version: ✔ 8.4.0
WC Blocks Version: ✔ 11.6.2
Action Scheduler Version: ✔ 3.7.0
Log Directory Writable: ✔
WP Version: 6.4.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.16.0
PHP Version: 8.2.8
PHP Post Max Size: 1,000 MB
PHP Time Limit: 1200
PHP Max Input Vars: 4000
cURL Version: 8.4.0
(SecureTransport) LibreSSL/3.3.6

SUHOSIN Installed: –
MySQL Version: 8.0.16
Max Upload Size: 300 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.4.0
WC Database Prefix: wp_
Total Database Size: 19.42MB
Database Data Size: 17.36MB
Database Index Size: 2.06MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.08MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.11MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 14.03MB + Index: 0.08MB + Engine InnoDB
wp_postmeta: Data: 0.28MB + Index: 0.28MB + Engine InnoDB
wp_posts: Data: 0.11MB + Index: 0.06MB + Engine InnoDB
wp_snippets: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.11MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_deposits_payment_plans: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_deposits_payment_plans_schedule: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wp_phpmyadmin_extension__errors_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wpml_mails: Data: 1.52MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 26
customize_changeset: 1
page: 9
post: 2
product: 21
product_variation: 7
revision: 10
shop_order: 52
shop_order_refund: 5
wp_global_styles: 2
wp_navigation: 1
wp_template: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (4) ###

Jetpack Beta Tester: by Automattic – 3.1.6
Jetpack: by Automattic – 12.9.3
WooPayments: by Automattic – 7.0.0
WooCommerce: by Automattic – 8.4.0

### Inactive Plugins (6) ###

Code Snippets: by Code Snippets Pro – 3.6.2
WooCommerce Deposits: by WooCommerce – 2.2.2
WooPayments: by Automattic – 7.1.0-dev_PR-7956_commit-0af42f5
Woo Subscriptions: by WooCommerce – 5.5.0
WP Mail Logging: by WP Mail Logging Team – 1.12.0
WP phpMyAdmin: by Puvox.software – 5.2.1.02

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to Woo.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### WC Pages ###

Shop base: #7 - /
Cart: #8 - /cart/
Checkout: #80 - /checkout-block/
My account: #10 - /my-account/
Terms and conditions: #2 - /sample-page/

### Theme ###

Name: Storefront
Version: 4.5.3
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: /Users/chris/Local Sites/woosites/wcpaytest/app/public/wp-content/plugins/woocommerce/packages/woocommerce-blocks/templates/notices/error.php
/Users/chris/Local Sites/woosites/wcpaytest/app/public/wp-content/plugins/woocommerce/packages/woocommerce-blocks/templates/notices/notice.php
/Users/chris/Local Sites/woosites/wcpaytest/app/public/wp-content/plugins/woocommerce/packages/woocommerce-blocks/templates/notices/success.php


### WooPayments ###

Version: 7.0.0
Connected to WPCOM: Yes
WPCOM Blog ID: 222616489
Account ID: acct_1NhdHh2EHhK9IQzL
Payment Gateway: Enabled
Test Mode: Enabled
Enabled APMs: card,affirm,klarna,afterpay_clearpay,bancontact,eps,giropay,ideal,sofort,p24
WooPay: Disabled
WooPay Incompatible Extensions: No
Apple Pay / Google Pay: Enabled (product,cart,checkout)
Fraud Protection Level: basic
Multi-currency: Enabled
Public Key Encryption: Disabled
Auth and Capture: Enabled
Documents: Disabled
Logging: Enabled

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
product-virtual-downloadable
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: customize-store
minified-js
new-product-management-experience
product-external-affiliate
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2024-01-04 02:02:41 +00:00
Options: ✔
Notes: 84
Onboarding: skipped

### Action Scheduler ###

Complete: 155
Oldest: 2023-12-06 00:40:41 +0000
Newest: 2024-01-03 21:45:38 +0000

Pending: 2
Oldest: 2024-01-03 22:46:39 +0000
Newest: 2024-01-04 03:37:54 +0000

Failed: 1
Oldest: 2023-08-15 19:04:41 +0000
Newest: 2023-08-15 19:04:41 +0000

Canceled: 5
Oldest: 2023-12-26 15:09:16 +0000
Newest: 2023-12-31 03:34:58 +0000


### Status report information ###

Generated at: 2024-01-03 22:45:54 +00:00
```

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by tomalec**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

- [Forward placement prop from EllipsisMenu to the Dropdown](https://github.com/woocommerce/woocommerce/commit/6df34ae3e72f8d89b8fd9df7acd698fa7755c9e6)
- [Place ellipsis popover at bottom-end of TableCard's menu.](https://github.com/woocommerce/woocommerce/commit/8cc9bd171e690ba43e8b9d751e79d3b27c4054db) 

Fixes https://github.com/woocommerce/woocommerce/issues/43256

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Checkout and build this branch
2. Run automated tests
3. Go to 
   - _Analytics > Revenue_ `/wp-admin/admin.php?page=wc-admin&path=%2Fanalytics%2Frevenue`
   - _Analytics > Dashboard_ `/wp-admin/admin.php?page=wc-admin&path=%2Fanalytics%2Foverview`
5. Click on the kebab icon(s)
6. Check that the menu is displayed within the viewport.
8. Smoke test other instances of Ellipsis menu for the regression, like inbox panel on the dashboard `/wp-admin/admin.php?page=wc-admin`

#### Before
image

#### After
image

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

File: packages/js/components/src/ellipsis-menu/index.tsx [hunk 1]
```diff
@@ -42,6 +50,9 @@ const EllipsisMenu = ( {
 	renderContent,
 	className,
 	onToggle,
+	// if set bottom-start, it will fallback to bottom-end / top-end / top-start
+	// if it's bottom, it will fallback to only top
+	placement = 'bottom-start',
```
Comment (eason9487) [inline packages/js/components/src/ellipsis-menu/index.tsx:55]: Could the component's README be updated for the `placement` prop accordingly?

**Review by eason9487 — APPROVED** [review]
Thanks for the fix! LGTM.

The only comment is not a blocker.

Side notes:

- I tried to reproduce the issue with the current `trunk` (df28518b75d1517efec51411d686fca4b46bcebc) but could not. I then realized that a merged PR happened to fix the issue as well.
   - Even so, I think this PR is still worth merging because it adds `placement` props for `EllipsisMenu` component to make it more flexible to use.
   - PR ref: #53033
   - Commit ref: [9f57a9a](https://github.com/woocommerce/woocommerce/commit/9f57a9a7b7d93a2e0ddb78e117c52fc9050f4072#diff-392ed500109c069303cd40d8a946434e634f10be94ba15caec5b9090bbd3f416R94)
- I also confirmed that #49535 has been fixed by the way.

   https://github.com/user-attachments/assets/fcf03d6d-58a8-45e3-8618-2ad7ceddf868
