### PR TITLE
Fix editing Shipping methods auto-saving

### LINKED ISSUE #38114: Editing Shipping Methods auto saves the entire form which is confusing behaviour
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When editing a shipping zone and adding/removing a shipping method the entire form gets saved disabling the `Save changes` button.
This causes confusing behaviour, where the user might not be sure if things actually saved or not.

### Expected behavior

The **Save changes** should stay active and the shipping methods not changed until **Save changes** is hit.
We could also be more explicit that the entire form is saved when a shipping method has changed.

### Actual behavior

**Save changes** gets disabled after shipping methods updated and everything in the form is automatically saved, see video:

https://user-images.githubusercontent.com/2240960/236168504-836adc4a-b6af-4086-99b2-1f801ee915c3.mp4

### Steps to reproduce

1. Set up a brand new WooCommerce store and finish the set up task list.
2. Go to **WooCommerce > Settings > Shipping**
3. Create a shipping zone and click edit.
4. Update the zone name and add a new shipping method
5. Notice how the a loading icon shows up on the shipping method table and the form gets saved without clicking **Save changes**

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://strategic-jellyfish.jurassic.ninja
Site address (URL): https://strategic-jellyfish.jurassic.ninja
WC Version: 7.6.1
REST API Version: ✔ 7.6.1
WC Blocks Version: ✔ 9.8.5
Action Scheduler Version: ✔ 3.5.4
Log Directory Writable: ✔
WP Version: 6.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.57 (Unix) OpenSSL/1.0.2g
PHP Version: 7.4.33
PHP Post Max Size: 1 GB
PHP Time Limit: 30
PHP Max Input Vars: 5000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.7.33-0ubuntu0.16.04.1-log
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.6.1
WC Database Prefix: wp_
Total Database Size: 10.96MB
Database Data Size: 8.13MB
Database Index Size: 2.83MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_gla_attribute_mapping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gla_budget_recommendations: Data: 0.22MB + Index: 0.14MB + Engine InnoDB
wp_gla_merchant_issues: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gla_shipping_rates: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gla_shipping_times: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_automations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_automation_runs: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_automation_run_logs: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_automation_run_subjects: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_automation_triggers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_automation_versions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_custom_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_dynamic_segment_filters: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_feature_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_forms: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletters: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_newsletter_links: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_newsletter_option: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_option_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_posts: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_segment: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_templates: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_scheduled_tasks: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_scheduled_task_subscribers: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_segments: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_sending_queues: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_settings: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_statistics_bounces: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_statistics_clicks: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_statistics_forms: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_statistics_newsletters: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_statistics_opens: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_mailpoet_statistics_unsubscribes: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_statistics_woocommerce_purchases: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_mailpoet_stats_notifications: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_subscribers: Data: 0.02MB + Index: 0.13MB + Engine InnoDB
wp_mailpoet_subscriber_custom_field: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_subscriber_ips: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_subscriber_segment: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_subscriber_tag: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_tags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_user_agents: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_user_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 3.48MB + Index: 0.08MB + Engine InnoDB
wp_postmeta: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_posts: Data: 0.05MB + Index: 0.06MB + Engine InnoDB
wp_sc_delivery_methods: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_sc_delivery_zones: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 12
mailpoet_page: 1
page: 8
post: 2
product: 9
revision: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (11) ###

Companion Plugin: by Osk – 1.29
Google Listings and Ads: by WooCommerce – 2.4.4
Jetpack: by Automattic – 12.1
MailPoet: by MailPoet – 4.14.0
Pinterest for WooCommerce: by WooCommerce – 1.2.21
Sendcloud | Smart Shipping Service: by Sendcloud B.V. – 2.2.19
TikTok: by TikTok – 1.0.16
WooCommerce Beta Tester: by WooCommerce – 2.2.0
WooCommerce Payments: by Automattic – 5.8.1
WooCommerce Shipping & Tax: by WooCommerce – 2.2.4
WooCommerce: by Automattic – 7.6.1 (update to version 7.7.0-rc.1 is available)

### Inactive Plugins (2) ###

Akismet Anti-Spam: by Automattic – 5.1
Hello Dolly: by Matt Mullenweg – 1.7.2

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: left_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
Order datastore: WC_Order_Data_Store_CPT

### WC Pages ###

Shop base: #6 - /shop/
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 4.2.0
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
multichannel-marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: block-editor-feature-enabled
minified-js
new-product-management-experience
product-variation-management
settings

Daily Cron: ✔ Next scheduled: 2023-05-05 09:00:05 +00:00
Options: ✔
Notes: 57
Onboarding: completed

### WooCommerce Payments ###

Version: 5.8.1
Connected to WPCOM: Yes
Blog ID: 218621164
Account ID: -

### Action Scheduler ###

Complete: 25
Oldest: 2023-05-04 09:01:12 +0000
Newest: 2023-05-04 09:18:38 +0000

Pending: 5
Oldest: 2023-05-04 09:20:38 +0000
Newest: 2023-05-05 09:01:20 +0000

### Status report information ###

Generated at: 2023-05-04 09:19:21 +00:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by octaedro**
### Submission Review Guidelines:

- I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
- I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
- I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/). 
- Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

This PR fixes the issue with Shipping Methods auto-saving the entire form. Now, when a shipping method is added and there is another change in the form, the `Save changes` button will remain enabled, and no other change will be saved except for the added method.

Screen Capture on 2023-05-26 at 12-27-00

Closes #38114.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Go `WooCommerce` > `Settings` > `Shipping` (URL: `wp-admin/admin.php?page=wc-settings&tab=shipping`).
2. Create a shipping zone and click edit.
3. Update the zone name and add a new shipping method
4. Notice how the loading icon shows up on the shipping method table, and the form gets saved without clicking `Save changes`.
5. Add another change to the form (like changing `Zone name`).
6. Add another shipping method.
7. Verify that the `Save changes` button is still enabled and only the added shipping method is saved.

_We currently [don't have a method to delete shipping zones](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/includes/class-wc-ajax.php#L128-L180) individually, which is why I opted for this workaround.  The form will be saved automatically if we add a new shipping method. However, if another change is made, then pressing `Save changes` will be necessary to save it._

_When editing a specific shipping method, all the changes in the form will be saved after pressing the `Save changes` button inside the modal._

### CODE REVIEW

File: plugins/woocommerce/client/legacy/js/admin/wc-shipping-zone-methods.js [hunk 1]
```diff
@@ -388,11 +389,12 @@
 								}
 								// Trigger save if there are changes, or just re-render
```
Comment (louwie17) [inline plugins/woocommerce/client/legacy/js/admin/wc-shipping-zone-methods.js:411]: Hmm although these changes do prevent the **Save changes** from being disabled again, it is actually the request above that saves the data. So even if I don't hit **Save changes** and refresh the page the new shipping method is still in the list.

**Review by louwie17 — CHANGES_REQUESTED** [review]
@octaedro unfortunately this looks like it will require a whole lot more work, as the request to `woocommerce_shipping_zone_add_method` already saves the shipping method.

As I am looking at this, it looks like these steps should be implemented, if we really wanted to do it well (otherwise we should just add some clarifying notes in different places):
- New Ajax call to retrieve all the shipping method data ( title, description, etc )
- On add shipping method replace call to `woocommerce_shipping_zone_add_method` with retrieving all shipping method data (with new ajax call) and display within table (keep track of this data )
- Keep track of changes within shipping method changes and change **Save changes** button to **Done** or something to that affect.
- When user hits **Save changes** we submit all the changed data ( new methods, and updated method changes, etc...)

@pmcpinto this was to address a bug found during one of the user flow calls and turns out to be quite a big task and re-factor that will probably take a good week (or longer ) of developer time.
Did we potentially want to re-consider this? 
I am also trying to think of alternate (less dev heavy ) solutions, like maybe just adding a note that adding a new shipping method auto saves the form?

**Comment by pmcpinto** [comment]
Hey @louwie17 thanks for the heads up.

> Did we potentially want to re-consider this?
> I am also trying to think of alternate (less dev heavy ) solutions, like maybe just adding a note that adding a new shipping method auto saves the form?

Given the time it will take, it makes total sense to reconsider this. Displaying a snackbar informing the user that all the changes were saved could be a good workaround. It's not perfect but it does the job. @jarekmorawski what do you think?

**Comment by louwie17** [comment]
> Given the time it will take, it makes total sense to reconsider this. Displaying a snackbar informing the user that all the changes were saved could be a good workaround. It's not perfect but it does the job. @jarekmorawski what do you think?

A quick follow up as I also talked with @octaedro about this more. This issue does address the issue where a user may edit the zone name and then add a shipping method, that only the shipping methods are saved and the user still has to click **Save changes** for the zone name update.

If we want, we could keep that structure, where all the changes within the shipping methods (adding/removing/editing) is saved automatically, but outside of that requires the call to **Save changes**?

**Comment by alopezari** [comment]
Hi @octaedro!

I reviewed the changes in the E2E tests and they look good. I ran them in multiple combinations (the whole spec in headless, headed and UI mode, as well as running all these tests individually) and they always passed. I also ran them several times consecutively in order to spot potential flaky issues, but they seem to be pretty consistent.

I don't know if it will need any further changes based on the recent comments, in that case, let us know and we'll happily review the testing details again. Thank you!

File: plugins/woocommerce/client/legacy/js/admin/wc-shipping-zone-methods.js [hunk 2]
```diff
@@ -197,16 +198,33 @@
...
 
 					event.preventDefault();
-
-					delete methods[ instance_id ];
-					changes.methods = changes.methods || { methods : {} };
-					changes.methods[ instance_id ] = _.extend( changes.methods[ instance_id ] || {}, { deleted : 'deleted' } );
-					model.set( 'methods', methods );
-					model.logChanges( changes );
-					view.render();
+					shippingMethodView.block();
```
Comment (louwie17) [inline plugins/woocommerce/client/legacy/js/admin/wc-shipping-zone-methods.js]: We also discussed showing a confirmation dialog first, to see if the user really wanted to delete the shipping method, could we still add that?

File: plugins/woocommerce/client/legacy/js/admin/wc-shipping-zone-methods.js [hunk 3]
```diff
@@ -197,16 +198,33 @@
...
+						success: function( { data } ) {
+							delete methods[instance_id];
+							changes.methods = changes.methods || data.methods;
+							model.set('methods', methods);
+							model.logChanges( changes );
+							view.render();
+							shippingMethodView.unblock();
+						},
+						error: function( jqXHR, textStatus, errorThrown ) {
+							console.error( 'There was an error removing the shipping method.', errorThrown );
```
Comment (louwie17) [inline plugins/woocommerce/client/legacy/js/admin/wc-shipping-zone-methods.js]: Instead of a `console.error` I think we should trigger a `window.alert` similar to other places within this `JS` file.
See `window.alert( data.strings.save_failed );` cases. We did have to add a new localized string, it looks like there is already one for `add_method_failed`, so we could also create one for `remove_method_failed`?

**Review by louwie17 — CHANGES_REQUESTED** [review]
Overall this is testing quite well, nice work on this @octaedro! 
I did leave two suggestions, on the window confirmation dialog before removing and showing a window alert instead of a console alert.

File: plugins/woocommerce/client/legacy/js/admin/wc-shipping-zone-methods.js (hunk 3 above)
Comment (octaedro) [reply plugins/woocommerce/client/legacy/js/admin/wc-shipping-zone-methods.js]: Good call @louwie17! I just added the changes you mentioned. Could you take another look at this PR?

Comment (octaedro) [reply plugins/woocommerce/client/legacy/js/admin/wc-shipping-zone-methods.js]: Please scratch my comment. I'll add a couple of e2e tests before pinging you for a re review.

**Comment by pmcpinto** [comment]
> A quick follow up as I also talked with @octaedro about this more. This issue does address the issue where a user may edit the zone name and then add a shipping method, that only the shipping methods are saved and the user still has to click Save changes for the zone name update.
> If we want, we could keep that structure, where all the changes within the shipping methods (adding/removing/editing) is saved automatically, but outside of that requires the call to Save changes?

This approach can work well. @jarekmorawski what do you think?

**Review by louwie17 — APPROVED** [review]
LGTM 🚀 Thanks for your hard work on this @octaedro and for adding the E2E tests as well, nice work!!!
