### PR TITLE
Fix tax task showing as not completed after setting up tax

### LINKED ISSUE #35745: Tax task showing as not completed after setting up tax
**Issue Description:**
Reported by a user and surfaced by @verofasulo, tax task completion isn't marked as completed when the user is sent back to WCAdmin dashboard after a user has installed WC Tax and Services plugin and connected their site. 

I suspect the cause is the [`wc_connect_taxes_enabled`](https://github.com/woocommerce/woocommerce/blob/9fabda744ae49099a525c8e54632adfe91f22f61/plugins/woocommerce-admin/client/tasks/fills/tax/index.tsx#L100) option is not set synchronously while it is being used as the flag for completion in the [Tax task](https://github.com/woocommerce/woocommerce/blob/9fabda744ae49099a525c8e54632adfe91f22f61/plugins/woocommerce/src/Admin/Features/OnboardingTasks/Tasks/Tax.php#L118).

**To Reproduce**

1. In a new site, skip OBW
2. Go to WooCommerce > Home > Add tax rates
3. Do all the steps and connect the site
4. Observe that the tax task isn't marked as completed until you refresh the page

https://user-images.githubusercontent.com/3747241/204278036-05ea8cfc-c8c6-4790-b9b6-040a2fbb5d3c.mov

### PR DESCRIPTION
**Pull request by chihsuan**
### All Submissions:

-   [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
-   [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
-   [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes #35745.

Wait for requests to finish before redirecting to make sure the [wc_connect_taxes_enabled](https://github.com/woocommerce/woocommerce/blob/9fabda744ae49099a525c8e54632adfe91f22f61/plugins/woocommerce-admin/client/tasks/fills/tax/index.tsx#L100) option is set synchronously.

Ideally, we should also add a test for it, but it's a bit challenging because it requires a Jetpack connection to complete the flow. I think we can tackle this problem when we start to work on the e2e project.

- [ ] This PR is a very minor change/addition and does not require testing instructions (if checked you can ignore/remove the next section).

### How to test the changes in this Pull Request:

1. In a new site, skip OBW
2. Go to `WooCommerce > Home > Add tax rates`
3. Do all the steps and connect the site
4. Click on "Yes please" button when seeing "Jetpack and WooCommerce Tax can automate your sales tax calculations" texts.
5. Observe that the tax task is marked as completed

You can use this [release zip file](https://github.com/woocommerce/woocommerce/actions/runs/3937194291) for testing.

### Other information:

-   [x] Have you added an explanation of what your changes do and why you'd like us to include them?
-   [ ] Have you written new tests for your changes, as applicable?
-   [x] Have you created a changelog file for each project being changed, ie `pnpm --filter=<project> changelog add`?

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

https://user-images.githubusercontent.com/4344253/212846119-801bdddd-2e08-4943-bb3b-e2798fde7b41.mov

### CODE REVIEW

**Review by ilyasfoo — APPROVED** [review]
Awesome fix, @chihsuan! LGTM. Makes sense to not have e2e at the moment for this flow.

File: plugins/woocommerce-admin/client/tasks/fills/tax/index.tsx [hunk 1]
```diff
@@ -92,20 +92,34 @@ const Tax: React.FC< TaxProps > = ( { onComplete, query, task } ) => {
...
-		updateAndPersistSettingsForGroup( 'general', {
-			general: {
-				...generalSettings,
-				woocommerce_calc_taxes: 'yes',
-			},
-		} );
+		try {
+			await Promise.all( [
+				updateAndPersistSettingsForGroup( 'tax', {
+					tax: {
```
Comment (rjchow) [inline plugins/woocommerce-admin/client/tasks/fills/tax/index.tsx:100]: not introduced by this PR, but I'm surprised there's no bug or lint complaint about taxSettings not being in the useCallback dependency array. 

Do you know if it's necessary to add it?

**Review by rjchow — APPROVED** [review]
Looks good to me other than the comment on the dependency array!

File: plugins/woocommerce-admin/client/tasks/fills/tax/index.tsx (hunk 1 above)
Comment (chihsuan) [reply plugins/woocommerce-admin/client/tasks/fills/tax/index.tsx:100]: Good point! I took a quick look, and I think it's okay for new users because there are only default tax settings. But we should better add it to the dependency array to avoid some edge cases. I'll create an issue for it. We may need to look into it deeper.

Comment (chihsuan) [reply plugins/woocommerce-admin/client/tasks/fills/tax/index.tsx:100]: issue created https://github.com/woocommerce/woocommerce/issues/36502
