### PR TITLE
Fix Homescreen TS errors

### LINKED ISSUE #54610: Fix TS errors `plugins/woocommerce/client/admin/client/embedded-body-layout/render-embedded-layout.tsx`

### LINKED ISSUE #54611: Fix TS errors `plugins/woocommerce/client/admin/client/error-boundary/index.tsx`

### LINKED ISSUE #54613: Fix TS errors  `plugins/woocommerce/client/admin/client/homescreen/`

### LINKED ISSUE #54614: Fix TS errors `plugins/woocommerce/client/admin/client/layout/footer/footer.tsx`

### PR DESCRIPTION
**Pull request by chihsuan**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Part of https://github.com/woocommerce/woocommerce/issues/53939

Closes https://github.com/woocommerce/woocommerce/issues/54613
Closes https://github.com/woocommerce/woocommerce/issues/54614
Closes https://github.com/woocommerce/woocommerce/issues/54611
Closes https://github.com/woocommerce/woocommerce/issues/54610

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Vist WooCommerce > Home
3. Do smoke test Homescreen

#### Only dev 

1. Run `pnpm build`
2. Go to `plugins/woocommerce/client/admin`
3. Run `npx tsc`
4. Ensure that no TS errors are related to the homescreen or layout.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [x] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce/client/admin/client/homescreen/mobile-app-modal/layouts/ModalIllustrationLayout.tsx [hunk 1]
```diff
@@ -37,7 +37,6 @@ export const ModalIllustrationLayout = ( {
 				label={ __( 'Close', 'woocommerce' ) }
 				icon={ <Icon icon={ closeSmall } viewBox="6 4 12 14" /> }
 				iconSize={ 16 }
-				size={ 16 }
```
Comment (chihsuan) [inline plugins/woocommerce/client/admin/client/homescreen/mobile-app-modal/layouts/ModalIllustrationLayout.tsx:40]:
```ts
	/**
	 * The size of the button.
	 *
	 * - `'default'`: For normal text-label buttons, unless it is a toggle button.
	 * - `'compact'`: For toggle buttons, icon buttons, and buttons when used in context of either.
	 * - `'small'`: For icon buttons associated with more advanced or auxiliary features.
	 *
	 * If the deprecated `isSmall` prop is also defined, this prop will take precedence.
	 *
	 * @default 'default'
	 */
	size?: 'default' | 'compact' | 'small';
```

**Review by moon0326 — APPROVED** [review]
I see some errors from other components, but not from homescreen.

LGTM and tested well 👍 🚀
