### PR TITLE
Fix inconsistent behavior for Net Sales in Analytics for single line refund

### LINKED ISSUE #48761: Inconsistent behavior of Net Sales in Analytics for partial refunds
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When there are partial refunds, the Net sales total displayed in the Products report doesn't match the total we show in the Orders report.

image
image

The discrepancy arises because the lines refunded in a partial refund are not recorded in the `wp_wc_order_product_lookup` table. This table serves as the data source for the `Products` and `Categories` reports, leading to mismatched `Net Sales` totals.
The result of this problem is a mismatch in the Net sales totals.

### Steps to reproduce

1. Create a few orders with multiple lines. Remember that you'll need a product with status: `Completed`.
2. Refund an item.
3. Verify that the Products report shows a different Net sales value than Revenue and Orders.

### WordPress Environment

This is happening on `trunk`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by octaedro**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

This PR fixes an error that appeared after creating a partial refund. The Net sales total displayed in the Products report did not match the total shown in the Orders report.

Before

Screen Recording on 2024-06-28 at 04-31-53

After

Screen Recording on 2024-06-28 at 04-25-18

The problem with partial refunds and Analytics is bigger than this PR. The changes here do:
- [This check here](https://github.com/woocommerce/woocommerce/pull/48768/files#diff-d2438118f148f28d98ab96e1a12bdd753e462f4659970939f2fe3e2b87155f59L417) was preventing the order line from being recorded in the `wc_order_product_lookup` table when there were partial refunds. Affecting the Analytics results.
- It also adds an update to run the action to synchronize the orders with missing lines.

The changes here don't cover:

- Total refunds, issue [here](https://github.com/woocommerce/woocommerce/issues/48775).
- Partial order refunds, issue [here](https://github.com/woocommerce/woocommerce/issues/48954).
- As a follow-up, we should clean the `wc_order_product_lookup` table after deleting an order. Similar to what happens [in Orders report](https://github.com/woocommerce/woocommerce/issues/48955).

Closes #48761.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Before checking out this branch.
2. Create some products and orders with multiple lines. Remember that you'll need a product with status: `Completed`.
3. Refund an item. Don't refund every item in the order, just one and in the way shown [here](https://github.com/woocommerce/woocommerce/assets/1314156/0c5c5781-2a7d-4450-bedb-cf75d03de335).
4. Verify that the `Products` report shows a different `Net sales` value than `Revenue` and `Orders`.

image
image

5. Now checkout this branch and update the WC version in your DB. It will be under `woocommerce_db_version` (running  `wp option update woocommerce_db_version 9.0.0` in wp-cli would do the trick).
6. Go to `/wp-admin/admin.php?page=wc-status&tab=action-scheduler&status=pending` and verify that every action under `Pending` have been triggered.
7. The `Net sales` now should match. The Products report now shows the same `Net sales` value as Revenue and Orders.
9. Repeat steps 2 and 3.
10. Now, the Product report should have included the new order with the partial refunds.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce/includes/class-wc-install.php [hunk 1]
```diff
@@ -257,6 +257,7 @@ class WC_Install {
 		),
 		'9.1.0' => array(
 			'wc_update_910_add_launch_your_store_tour_option',
+			'wc_update_910_add_old_refunded_order_items_to_product_lookup_table',
```
Comment (ianlin) [inline plugins/woocommerce/includes/class-wc-install.php]: WC dev newbie question: since 9.1 is releasing soon, should this be updated to `920` instead?

**Review by ianlin — APPROVED** [review]
Thanks for fixing the net sales in product analytics page. Tested locally and confirmed the net sales were displayed correctly in product analytics page, and the database update script can import the old refunded order items. I just left a minor question regarding the WC release version.

File: plugins/woocommerce/includes/class-wc-install.php (hunk 1 above)
Comment (octaedro) [reply plugins/woocommerce/includes/class-wc-install.php]: Hi @ianlin
Good call! It should say:
```
'9.2.0' => array(
		'wc_update_920_add_launch_your_store_tour_option',
),
```

Since code freeze will happen this week, it will probably be 9.3.0.

I think this fix shouldn't be released alone. I would release it with the other fixes needed to address the problems related to Net sales.

Comment (puntope) [reply plugins/woocommerce/includes/class-wc-install.php]: > I think this fix shouldn't be released alone

I will create a feature branch then.

**Comment by ianlin** [comment]
I've created a shared branch [fix/32837-48761-48775-48954-inconsistent-behavior-of-net-sales-in-analytics](https://github.com/woocommerce/woocommerce/tree/fix/32837-48761-48775-48954-inconsistent-behavior-of-net-sales-in-analytics) since we need to address all the issues related to inconsistent net sales together before releasing the fix.

Tagging @woocommerce/automata for visibility.

This issues are:

- #32837
- #48761
- #48775
- #48954
