### PR TITLE
[WC Payments NOX] Fixes and improvements for non-standard provider behavior

### LINKED ISSUE #54290: [WC Payments NOX] Some partner gateways aren't showing in the NOX list
### Describe the bug
Some partner gateways aren't showing in the NOX list, this is probably because the gateway isn't registered until onboarding is completed.

### To Reproduce
Install one of these gateways:
- Mollie
- Viva Wallet

### Links
- p1736343293094009-slack-C0800LPNCET
- p1736328042859919-slack-C0800LPNCET

### LINKED ISSUE #54291: [WC Payments NOX] Multiple gateways displayed instead of a top one
### Describe the bug
Some gateways display multiple choices in the NOX page -with the same name- which makes it hard to know which to select.

Example:
Image

### To Reproduce
Try with one of these providers:

- Antom
- Mercado Pago
- Amazon Pay
- Square
- Payoneer

### Links
- p1736343293094009-slack-C0800LPNCET
- p1736255703466689-slack-C0800LPNCET

### PR DESCRIPTION
**Pull request by vladolaru**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

We introduce special handling for the Mollie extension when it is only installed and activated, without any setup. Now it shows in the providers list, just like other extensions.

We don't overwrite the gateway and description with the ones provided by PESs for Antom, Mercado Pago, Amazon Pay, Square, Payoneer.

We add custom provider handling for Amazon Pay (specifically around sandbox mode).

Closes #54290
Closes #54291 

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Create a new JurassicNinja site with WooCommerce on this PR's live branch and WooCommerce Beta Tester (here is [a direct JN create link](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce-beta-tester&woocommerce&branches.woocommerce=fix/54290-missing-partner-gateway-in-nox-provider-list))
1. Go to the newly created site WP admin dashboard.
1. Go to Tools > WCA Test Helper > Features and enable the `reactify-classic-payments-settings` feature. 
1. Go through the WooCommerce profiler (click on the "WooCommerce" menu item if it doesn't start automatically), click on "Skip guided setup", and choose **United Kingdom** as your store's location.
1. Click on the "Payments" main menu item (that should have a red do notice), and you should see the new Payments settings page, with a WooPayments incentive banner:
Screenshot 2025-01-15 at 10 26 48
1. Click on "Other payments options" to expand the section and install the Mollie extension:
Screenshot 2025-01-15 at 10 34 29
1. After the extension is installed, Mollie should not be present in the "Other payments options" section, but instead appear in the providers list with a "Complete setup" CTA button:
Screenshot 2025-01-15 at 10 35 02
1. Change the Payments page business location to "United States" from the top right-hand select
Screenshot 2025-01-15 at 10 47 05
1. Click on "Install" for the "Accept payments with Woo" provider, then click on "Continue" when presented with the "Choose your payment methods" step, connect your store to your WPCOM account and wait for the test account setup to finish on the "Finishing payments setup" step.
Screenshot 2025-01-13 at 19 49 49
1. Close the modal:
Screenshot 2025-01-15 at 10 43 23
1. Click on the "Other payment options" section to expand it and install the Amazon Pay extension:
Screenshot 2025-01-15 at 10 49 01
1. After the extension is installed, you should see two new entries added to the providers list:
Screenshot 2025-01-15 at 10 52 49
1. Change the Payments page business location to "China" from the top right-hand select.
1. Click on the "Other payment options" section to expand it and install the Antom extension.
1. Once the extension is installed you should see many payment methods added to the providers list, each with a different name:  
Screenshot 2025-01-15 at 10 55 45

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce/changelog/fix-54290-missing-partner-gateway-in-nox-provider-list [hunk 1]
```diff
@@ -0,0 +1,5 @@
+Significance: patch
+Type: update
+Comment: We improve the handling of non-standard payment extension behavior (e.g. Mollie not registering a gateway until after setup).
```
Comment (oaratovskyi) [inline plugins/woocommerce/changelog/fix-54290-missing-partner-gateway-in-nox-provider-list]:
```suggestion
Comment: Improve the handling of non-standard payment extension behavior (e.g. Mollie not registering a gateway until after setup).
```

File: plugins/woocommerce/src/Internal/Admin/Settings/PaymentProviders.php [hunk 2]
```diff
@@ -954,21 +1020,38 @@ private function get_gateway_provider_instance( string $gateway_id ): PaymentGat
...
+		 * The provider class for the gateway.
+		 *
+		 * @var PaymentGateway|null $provider_class
+		 */
+		$provider_class = null;
+		if ( isset( $this->payment_gateways_providers_class_map[ $gateway_id ] ) ) {
+			$provider_class = $this->payment_gateways_providers_class_map[ $gateway_id ];
+		} else {
+			// Check for wildcard mappings.
+			foreach ( $this->payment_gateways_providers_class_map as $gateway_id_pattern => $mapped_class ) {
```
Comment (oaratovskyi) [inline plugins/woocommerce/src/Internal/Admin/Settings/PaymentProviders.php:1035]: I'd love to the unit test that checks this

**Comment by oaratovskyi** [comment]
@vladolaru let me know when you address Mollie gateway description and descriptions for Mercado gateways and I'll check it again 
context: p1736932591443409/1736928007.860599-slack-C03KTTK2YMA

File: plugins/woocommerce/src/Internal/Admin/Settings/PaymentProviders.php (hunk 2 above)
Comment (vladolaru) [reply plugins/woocommerce/src/Internal/Admin/Settings/PaymentProviders.php:1035]: I added [a unit test](https://github.com/woocommerce/woocommerce/pull/54487/commits/d504d19dc8f4b08269a0dfac1c515d8d25261a9c) to test the wildcard mapping indirectly.

**Review by oaratovskyi — APPROVED** [review]
Great work 🚀 
Tested all the providers that are referenced in the related issues :shipit: 
Thanks for addressing the feedback, all good now!

**Review by elazzabi — COMMENTED** [review]
Went through the testing steps, works perfectly!

Screenshot 2025-01-15 at 15 38 24
Screenshot 2025-01-15 at 15 37 34
Screenshot 2025-01-15 at 15 35 22

**Review by elazzabi — APPROVED** [review]
After testing and reviewing the code, looks great!
