### PR TITLE
Prevent orders being placed when no shipping options are available

### LINKED ISSUE #45912: Possible to place order when no shipping is available
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When the checkout page is built with the Checkout Block, it is possible to place an order even when there are no shipping options available.

### Expected behavior

When using the Checkout Block, and there are no shipping options available, the "**Place Order**" button should not work.  Instead, clicking on it should trigger the message "_Sorry, the order requires a shipping option._"

order-correct

### Actual behavior

In WooCommerce 8.7.0, clicking the "**Place Order**" button puts the order through and processes it.

This issue only appears on WooCommerce 8.7.0 on the Blocks version of the checkout page. 
It does *not* happen with WooCommerce 8.6.1 or earlier, and also *not* with the classic/shortcode checkout.

### Steps to reproduce

1. Have a site with WooCommerce 8.7.0.
2. Have a shipping zone with at least one shipping method, but **do not enable it**.  (If there are no shipping zones/methods at all, Woo will not include a shipping section at all on the checkout page.)
3. Make sure that the checkout page is built with the Checkout Block.
4. As a customer, buy a product and go to the checkout page.
5. Eenter an address that does not support shipping. You'll want to see the message "_There are no shipping options available. Please check your shipping address._"
6. Select the **Place Order** button.

You can test and reproduce on https://automatic-alpaca.jurassic.ninja

### WordPress Environment ###

```
WordPress address (URL): https://automatic-alpaca.jurassic.ninja
Site address (URL): https://automatic-alpaca.jurassic.ninja
WC Version: 8.7.0
REST API Version: ✔ 8.7.0
Action Scheduler Version: ✔ 3.7.2
Log Directory Writable: ✔
WP Version: 6.4.3
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 8.1.27
PHP Post Max Size: 2 GB
PHP Time Limit: 1200
PHP Max Input Vars: 6144
cURL Version: 8.4.0
OpenSSL/3.0.11

SUHOSIN Installed: –
MySQL Version: 10.6.17-MariaDB-log
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.7.0
WC Database Prefix: wp_
Total Database Size: 2.88MB
Database Data Size: 1.21MB
Database Index Size: 1.67MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 0.13MB + Index: 0.03MB + Engine InnoDB
wp_postmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_posts: Data: 0.05MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 1
page: 7
post: 2
product: 1
shop_order_placehold: 2
wp_navigation: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (2) ###

Companion Plugin: by Osk – 1.30
WooCommerce: by Automattic – 8.7.0

### Inactive Plugins (0) ###


### Dropin Plugins () ###

advanced-cache.php: advanced-cache.php
object-cache.php: Memcached

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to Woo.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 385 B

### WC Pages ###

Shop base: #5 - /shop/
Cart: #6 - /cart/
Checkout: #7 - /checkout/
My account: #8 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 4.5.4
Author URL: https://woo.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
product-virtual-downloadable
product-external-affiliate
product-grouped
product-linked
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: customize-store
minified-js
new-product-management-experience
product-pre-publish-modal
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2024-03-26 22:08:43 +00:00
Options: ✔
Notes: 63
Onboarding: -

### Action Scheduler ###

Complete: 12
Oldest: 2024-03-25 22:10:07 +0000
Newest: 2024-03-25 22:26:35 +0000

Failed: 3
Oldest: 2024-03-25 22:14:47 +0000
Newest: 2024-03-25 22:26:35 +0000

Pending: 1
Oldest: 2024-03-26 22:10:07 +0000
Newest: 2024-03-26 22:10:07 +0000


### Status report information ###

Generated at: 2024-03-25 22:29:14 +00:00
```

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by opr**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Adds a check to the `OrderController`'s `validate_selected_shipping_methods` method to check if the selected shipping method is a valid method.

In https://github.com/woocommerce/woocommerce/pull/43869/files#diff-cdc9f1829f52d7b83e3542948622d924ef5cf6a3e0b4580e6ebd1c9643bc49b4R501 we made some changes to shipping method handling to prevent fatal errors, the chosen method was cast to a string in this PR.

This meant our check in `validate_selected_shipping_methods` no longer worked because we are checking for: `if ( false === $chosen_shipping_method )` which would no longer be the case.

In this PR I am validating a little further by checking the selected method against the available methods. 

We set the default value of the `chosen_shipping_method` session variable to `[]` when validating orders. This means if it's unset, and shipping is _required_, sessions with no value will not be allowed to sneak through.

This PR brings some changes to PHP unit tests. In the Checkout route unit tests, we now add a Flat Rate shipping method before each test (and remove it afterwards). This is because previously we were using the legacy flat rate which didn't need to be part of a zone to work. This meant that it was not possible to test the fix for this bug as it requires a zone to have a (disabled) shipping method.

We also discovered an issue with the `test_checkout_force_create_account`, `test_checkout_do_not_create_account`, and `test_checkout_create_account` tests. They were passing even though no valid shipping method was selected. This PR fixes that by introducing a new class to override `WC()->session` called. `MockSessionHandler`.

In `MockSessionHandler` I changed places where `wp_set_cache` was used and implemented a class property to act as the cache, and also overrode the `set` function to automatically update the cache when setting data. This was required as the `$this->_data` was overwritten with blank data from the empty cache when logging in as a user. The session was never saved to the DB as the PHPUnit tests run in a single context, so by the time `shutdown` runs the test is over.

In these tests that use it, we are explicitly overriding WC()->session as there is no good way of setting this up using the `woocommerce_session_handler` filter on a per-test basis.

These tests need special handling as they need to be able to set a cookie during guest -> logged in user switching.

Closes https://github.com/woocommerce/woocommerce/issues/45912.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Have a shipping zone with at least one shipping method, but **do not enable it**.  (If there are no shipping zones/methods at all, Woo will not include a shipping section at all on the checkout page.)
2. Make sure that the checkout page is built with the Checkout Block.
3. As a customer, buy a product and go to the checkout page.
4. Eenter an address that does not support shipping. You'll want to see the message "_There are no shipping options available. Please check your shipping address._"
5. Select the **Place Order** button.
6. Ensure the order does not place.

#### Regression testing

1. Enable various shipping zones and various methods (across different countries).
2. Place an order with them all and ensure no errors are encountered.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce/src/StoreApi/Utilities/OrderController.php [hunk 1]
```diff
@@ -168,7 +168,7 @@ public function sync_customer_data_with_order( \WC_Order $order ) {
 	 */
 	public function validate_order_before_payment( \WC_Order $order ) {
 		$needs_shipping          = wc()->cart->needs_shipping();
-		$chosen_shipping_methods = wc()->session->get( 'chosen_shipping_methods' );
+		$chosen_shipping_methods = wc()->session->get( 'chosen_shipping_methods', [ '' ] );
```
Comment (senadir) [inline plugins/woocommerce/src/StoreApi/Utilities/OrderController.php]: I think it's best to have this as an empty array and strengthen the checks in `validate_selected_shipping_methods` by separating the check for need_shipping out, and doing array validation second.

File: plugins/woocommerce/tests/php/src/Blocks/StoreApi/MockSessionHandler.php [hunk 2]
```diff
@@ -0,0 +1,31 @@
...
+		$cookie_value      = $this->_customer_id . '||' . $this->_session_expiration . '||' . $this->_session_expiring . '||' . $cookie_hash;
+		$this->_has_cookie = true;
+
+		if ( ! isset( $_COOKIE[ $this->_cookie ] ) || $_COOKIE[ $this->_cookie ] !== $cookie_value ) {
+
+			// Manually set the cookie here because the response is already sent, so wc_setcookie() (as in the parent class) won't work.
+			$_COOKIE[ $this->_cookie ] = $cookie_value;
+		}
+	}
+}
```
Comment (senadir) [inline plugins/woocommerce/tests/php/src/Blocks/StoreApi/MockSessionHandler.php]: This might be a bit risky because it's overreaching, in this case you're replacing `init_session_cookie` but are you handling the process of moving from guest to logged in?

File: plugins/woocommerce/tests/php/src/Blocks/StoreApi/Routes/Checkout.php [hunk 3]
```diff
@@ -361,12 +380,20 @@ public function test_checkout_create_account() {
...
 	}
 
 	/**
 	 * Test account creation options.
 	 */
 	public function test_checkout_do_not_create_account() {
+		// We need to replace the WC_Session with a mock because this test relies on cookies being set which
+		// is not easy with PHPUnit. This is a simpler approach.
+		$old_session  = WC()->session;
+		WC()->session = new MockSessionHandler();
```
Comment (senadir) [inline plugins/woocommerce/tests/php/src/Blocks/StoreApi/Routes/Checkout.php:396]: I guess the `woocommerce_session_handler` filter didn't work?

**Review by senadir — CHANGES_REQUESTED** [review]
I think this is in the right direction, I do think we should be more defensive in `validate_order_before_payment`.

For the test, I left some comments but overall I think it's fine. We might need to refactor it in the future to ensure it's as close as possible to real life session manager to avoid false positives.

File: plugins/woocommerce/tests/php/src/Blocks/StoreApi/Routes/Checkout.php (hunk 3 above)
Comment (opr) [reply plugins/woocommerce/tests/php/src/Blocks/StoreApi/Routes/Checkout.php:396]: Yep, afraid not the only place to set this up was in `plugins/woocommerce/tests/legacy/bootstrap.php` which would affect all tests, not just the ones we need it for. This is a good solution for now.

File: plugins/woocommerce/tests/php/src/Blocks/StoreApi/MockSessionHandler.php (hunk 2 above)
Comment (opr) [reply plugins/woocommerce/tests/php/src/Blocks/StoreApi/MockSessionHandler.php]: Refactored now. The functions are the same as the WC_Session_Handler except instead of using wp_cache it uses a mock cache. For some reason caching was preventing the switch from logged out to logged in customer from working.

During this switch, the session data is saved in cache and re-read later when setting the session up for a logged-in user. In tests the cache was not saving it.

File: plugins/woocommerce/src/StoreApi/Utilities/OrderController.php (hunk 1 above)
Comment (opr) [reply plugins/woocommerce/src/StoreApi/Utilities/OrderController.php]: Done!

**Review by senadir — APPROVED** [review]
Working fine! thank you for doing the changes.

**Review by senadir — APPROVED** [review]
Thanks for the changes!

We might need to look into the future of ways to reduce the size of the session handler.
