### PR TITLE
Fix issue #34344 - Cannot edit replies to product reviews

### LINKED ISSUE #34344: Cannot edit replies to product reviews
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Cannot edit replies to product reviews on admin panel.
You can edit it with quick reply, but with quick reply you cannot edit published date etc.

### Expected behavior

"Edit Review Reply" page must show reply information when clicked "edit" on Product Reviews page.

image

### Actual behavior

It shows the edit screen for parent review of the reply.

image

### Steps to reproduce

1. Go to Products tab on admin panel
2. Go to Reviews
3. Click "edit" on a reply
4. Edit screen appears for the parent comment of the reply

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://iqc-someka-live-prod-dl090822113954.local
Site address (URL): https://iqc-someka-live-prod-dl090822113954.local
WC Version: 6.8.0
REST API Version: ✔ 6.8.0
WC Blocks Version: ✔ 8.0.0
Action Scheduler Version: ✔ 3.4.0
Log Directory Writable: ✔
WP Version: 6.0.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: –
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.16.0
PHP Version: 7.4.1
PHP Post Max Size: 1,000 MB
PHP Time Limit: 1200
PHP Max Input Vars: 4000
cURL Version: 7.67.0
OpenSSL/1.1.1d

SUHOSIN Installed: –
MySQL Version: 8.0.16
Max Upload Size: 300 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 6.8.0
WC Database Prefix: some2_
Total Database Size: 1492.21MB
Database Data Size: 765.94MB
Database Index Size: 726.27MB
some2_woocommerce_sessions: Data: 4.52MB + Index: 0.17MB + Engine InnoDB
some2_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
some2_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
some2_woocommerce_downloadable_product_permissions: Data: 31.56MB + Index: 54.34MB + Engine InnoDB
some2_woocommerce_order_items: Data: 16.55MB + Index: 4.52MB + Engine InnoDB
some2_woocommerce_order_itemmeta: Data: 106.66MB + Index: 93.27MB + Engine InnoDB
some2_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
some2_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
some2_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
some2_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
some2_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
some2_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
some2_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
some2_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
some2_actionscheduler_actions: Data: 0.06MB + Index: 0.13MB + Engine InnoDB
some2_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
some2_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
some2_actionscheduler_logs: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
some2_adtribes_my_conversions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
some2_commentmeta: Data: 0.27MB + Index: 0.30MB + Engine InnoDB
some2_comments: Data: 38.58MB + Index: 34.09MB + Engine InnoDB
some2_ewwwio_images: Data: 5.52MB + Index: 6.06MB + Engine InnoDB
some2_ewwwio_queue: Data: 0.25MB + Index: 0.14MB + Engine InnoDB
some2_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
some2_mc4wp_log: Data: 7.52MB + Index: 0.00MB + Engine InnoDB
some2_options: Data: 3.38MB + Index: 0.14MB + Engine InnoDB
some2_postmeta: Data: 438.00MB + Index: 467.98MB + Engine InnoDB
some2_posts: Data: 67.59MB + Index: 35.16MB + Engine InnoDB
some2_term_relationships: Data: 0.19MB + Index: 0.17MB + Engine InnoDB
some2_term_taxonomy: Data: 0.16MB + Index: 0.20MB + Engine InnoDB
some2_termmeta: Data: 0.11MB + Index: 0.14MB + Engine InnoDB
some2_terms: Data: 0.16MB + Index: 0.20MB + Engine InnoDB
some2_usermeta: Data: 0.23MB + Index: 0.11MB + Engine InnoDB
some2_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
some2_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
some2_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
some2_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
some2_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
some2_wc_download_log: Data: 13.52MB + Index: 15.03MB + Engine InnoDB
some2_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
some2_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
some2_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
some2_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
some2_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
some2_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
some2_wc_product_meta_lookup: Data: 0.06MB + Index: 0.09MB + Engine InnoDB
some2_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
some2_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
some2_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
some2_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
some2_yoast_indexable: Data: 8.52MB + Index: 5.89MB + Engine InnoDB
some2_yoast_indexable_hierarchy: Data: 1.52MB + Index: 0.80MB + Engine InnoDB
some2_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
some2_yoast_primary_term: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
some2_yoast_prominent_words: Data: 0.25MB + Index: 0.50MB + Engine InnoDB
some2_yoast_seo_links: Data: 13.52MB + Index: 6.03MB + Engine InnoDB
some2_yoast_seo_meta: Data: 6.52MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

acf: 1
acf-field: 70
acf-field-group: 4
attachment: 7500
customize_changeset: 3
custom_css: 1
dhwc_template: 4
html-form: 1
mc4wp-form: 1
nav_menu_item: 56
oembed_cache: 194
page: 17
post: 264
postman_sent_mail: 250
product: 219
product_variation: 41
shop_order: 197180
shop_order_refund: 13
templatera: 4
wpcf7_contact_form: 1
wp_block: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (16) ###

Advanced Custom Fields: by Delicious Brains – 5.12.3
Contact Form 7: by Takayuki Miyoshi – 5.6.2
DHWCPage - WooCommerce Page Builder: by SiteSao Team – 5.2.24
Disable Bloat for WordPress & WooCommerce: by Disable Bloat – 3.0.3
EWWW Image Optimizer: by Exactly WWW – 6.7.0
WPBakery Page Builder: by Michael M - WPBakery.com – 6.9.0
MC4WP: Mailchimp for WordPress: by ibericode – 4.8.7
MC4WP: Mailchimp for WordPress Premium: by ibericode – 4.9
Perfmatters: by forgemedia – 1.9.5
Send E-mails with Mandrill: by Miller Media ( Matt Miller ) – 1.3
Templatera: by WPBakery – 2.0.5
Total Theme Core: by WPExplorer – 1.4.4
WooCommerce: by Automattic – 6.8.0
Yoast SEO Premium: by Team Yoast – 19.0.1
Yoast SEO: by Team Yoast – 19.5.1
Yoast SEO: WooCommerce: by Team Yoast – 15.0

### Inactive Plugins (2) ###

Advanced Order Export For WooCommerce: by AlgolPlus – 3.3.2
Permalink Manager Pro: by Maciej Bis – 2.2.18

### Must Use Plugins (1) ###

Kinsta Must-use Plugins: by Kinsta Team – 2.4.8

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: –

### WC Pages ###

Shop base: #6 - /products/
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: ❌ Page visibility should be public
Terms and conditions: ❌ Page not set

### Theme ###

Name: Someka Custom Theme
Version: 1.1
Author URL: http://totalwptheme.com
Child Theme: ✔
Parent Theme Name: Total
Parent Theme Version: 5.4.4
Parent Theme Author URL: https://www.wpexplorer.com/
WooCommerce Support: ✔

### Templates ###

Archive Template: Your theme has a woocommerce.php file
you will not be able to override the woocommerce/archive-product.php custom template since woocommerce.php has priority over archive-product.php. This is intended to prevent display issues.

Overrides: Total/woocommerce/archive-product.php
Total/woocommerce/checkout\form-checkout.php
someka-custom-theme/woocommerce/emails\customer-completed-order.php version - is out of date. The core version is 3.7.0
Total/woocommerce/loop\loop-start.php
Total/woocommerce/loop\orderby.php
Total/woocommerce/loop\pagination.php
Total/woocommerce/single-product\add-to-cart\simple.php
Total/woocommerce/single-product\add-to-cart\variation-add-to-cart-button.php
Total/woocommerce/single-product\meta.php
Total/woocommerce/single-product\rating.php
Total/woocommerce/single-product\title.php

Outdated Templates: ❌
					
					
						Learn how to update

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
experimental-products-task
experimental-import-products-task
experimental-fashion-sample-products
experimental-product-tour
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
wc-pay-promotion
wc-pay-welcome-page
wc-pay-subscriptions-page

Disabled Features: minified-js
settings

Daily Cron: ✔ Next scheduled: 2022-08-09 13:08:14 +03:00
Options: ✔
Notes: 6
Onboarding: completed

### Action Scheduler ###

Complete: 108
Oldest: 2022-08-03 12:54:01 +0300
Newest: 2022-08-09 14:24:02 +0300

Pending: 2
Oldest: 2022-08-10 13:30:50 +0300
Newest: 2022-08-16 10:59:21 +0300

### Status report information ###

Generated at: 2022-08-16 17:17:24 +03:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by horzu**
### All Submissions:

-   [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
-   [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
-   [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes #34344 

- [ ] This PR is a very minor change/addition and does not require testing instructions (if checked you can ignore/remove the next section).

### How to test the changes in this Pull Request:

1. Go to Admin Panel
2. Open Products > Reviews
3. Select a reply to a product review and click edit.

### Other information:

-   [x] Have you added an explanation of what your changes do and why you'd like us to include them?
-   [x] Have you written new tests for your changes, as applicable?
-   [ ] Have you created a changelog file for each project being changed, ie `pnpm --filter=<project> changelog add`?

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

File: plugins/woocommerce/src/Internal/Admin/ProductReviews/Reviews.php [hunk 1]
```diff
@@ -537,7 +537,7 @@ protected function edit_comments_screen_text( $translation, $text ) {
 
 		if ( isset( $comment->comment_parent ) && $comment->comment_parent > 0 ) {
 			$is_reply = true;
-			$comment  = get_comment( $comment->comment_parent ); // phpcs:ignore WordPress.WP.GlobalVariablesOverride.Prohibited
+			$comment  = get_comment($comment_id); // phpcs:ignore WordPress.WP.GlobalVariablesOverride.Prohibited
```
Comment (jorgeatorres) [inline plugins/woocommerce/src/Internal/Admin/ProductReviews/Reviews.php]: I don't think this line is really needed at all. Removing it should have the same effect (of fixing the issue).
If `$comment` is already set (which it is, as this inside an `if` branch that tests for `$comment->comment_parent`), then it shouldn't be necessary to re-load the whole `$comment` again. That should've happened on line 533 above.

**Review by jorgeatorres — CHANGES_REQUESTED** [review]
Hi @horzu,

Thank you for your contribution! 💯 It's very much appreciated 🥇.
I ran some tests and this does fix the problem, but I believe there's another way to address the issue with a slightly different approach, which I've noted as a review comment.

Please let me know if you have any questions.

**Review by jorgeatorres — APPROVED** [review]
LGTM 👍
