### PR TITLE
Fix: Make coupon code discount total lookup case insensitive

### LINKED ISSUE #58864: Forcing of lowercase coupon codes breaks functionality in some cases
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

We experienced a bug where doing `$coupon->set_amount( $amount );` in `woocommerce_coupon_loaded ` suddenly would yield inconsistent results if the coupon code was UPPERCASE in the WooCommerce admin panel.

The bug stemmed from the discount system forcing lowercase in some parts of the system, but not all. This was causing coupons from order objects and in the cart object to return 0 as discount amount. Session was something like:

`s:15:"applied_coupons";s:28:"a:1:{i:0;s:10:"lowercase_code";}";s:22:"coupon_discount_totals";s:29:"a:1:{s:10:"UPPERCASE_CODE";d:40;}";s:26:"coupon_discount_tax_totals";s:29:"a:1:{s:10:"UPPERCASE_CODE";d:10;}";`

### Expected behavior

I expect casing to not really matter as long as doing `$coupon->set_amount( $amount );` in `woocommerce_coupon_loaded` because that should force the amount on the coupon object to a given number for that coupon for the entire request (as long as it is not changed later).

### Actual behavior

Cart coupons and order coupons return 0 for coupon discount amount, but only when coupon code is UPPERCASE.

### Steps to reproduce

1. Create uppercase coupon.
2. Hook into `woocommerce_coupon_loaded` to set amount
3. Call for instance `WC()->cart->get_coupon_discount_amount( $coupon_code, WC()->cart->display_cart_ex_tax ); ` after adding it to cart and see a returned value 0
4. One caveat to the above is that the coupon was saved as uppercase before updating from 9.8.x to 9.9.3, so I do not know the behavior if already on 9.9.3 and I don't have the resources to test this further.

### WordPress Environment

I am omitting this because of time constraints and since I think this appeared because somewhere between 9.8.x and 9.9.3 something introduced inconsistencies in case forcing/comparisons for coupon codes. I sadly don't have the resources to pursue this further, but thought it nice to at least flag it and document it so others can get answers if they have the same problems. And of course so it could be fixed if it really is a problem in core.

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by mikejolley**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

`strtolower` was removed from coupon formatting in https://github.com/woocommerce/woocommerce/pull/56319 which has broken some methods used to lookup coupon discount amounts if the case of the coupon differs between user input, and the coupon code stored in the DB.

The fix is to normalize (lowercase) coupon codes when looking up discount amounts.

This PR also changes:

- Store API to return actual codes so the correct case is displayed in cart block
- adds a unit test for coupon case handling

Closes #58864

(For Bug Fixes) Bug introduced in PR #56319

### How to test the changes in this Pull Request:

There is a new php unit test for this.

1. Create a coupon called TESTCOUPON with value 0
2. Use the snippet below
3. Go to the classic cart and confirm a $10 coupon applies and the amount shown below says "Discount amount is: 10".

```
/**
 * Changes the discount amount of the fixed cart coupon.
 *
 * @param WC_Coupon $coupon The coupon.
 *
 * @return void
 */
function change_coupon_discount_amount( $coupon ) {
	if ( is_admin() ) {
		return;
	}

	if ( strtolower( $coupon->get_code() ) !== 'testcoupon' ) {
		return;
	}

	$coupon->set_amount( 10 );
}
add_action( 'woocommerce_coupon_loaded', 'change_coupon_discount_amount' );

/**
 * Adds a coupon to the cart.
 *
 * @return void
 */
function apply_coupon() {
	$applied_coupons = array_map( 'wc_strtolower', WC()->cart->get_applied_coupons() );

	if ( ! in_array( 'testcoupon', $applied_coupons, true ) ) {
		WC()->cart->apply_coupon( 'testcoupon' );
	}
}
add_action( 'woocommerce_before_calculate_totals', 'apply_coupon' );

/**
 * Echoes the discount amount of the fixed cart coupon.
 *
 * @return void
 */
function echo_discount_amount() {
	if ( ! WC()->cart->has_discount() ) {
		return;
	}

	echo 'Discount amount is: ' . WC()->cart->get_coupon_discount_amount( 'testcoupon', WC()->cart->display_cart_ex_tax );
}
add_action( 'woocommerce_after_cart', 'echo_discount_amount' );
```

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

## Summary by CodeRabbit

- **Bug Fixes**
  - Resolved issues with coupon code matching by making coupon lookups case-insensitive, ensuring coupons work regardless of letter casing.
  - Improved error messages to display the correct coupon code format.
  - Enhanced coupon sanitization to better handle HTML entities.
  - Fixed coupon retrieval queries to be case-insensitive for accurate coupon identification.

- **New Features**
  - Added an action hook that triggers after a coupon is applied, enabling integrations with external systems.

- **Tests**
  - Introduced new tests to confirm coupon discount calculations are accurate regardless of coupon code case.

- **Refactor**
  - Streamlined coupon discount and tax retrieval for improved reliability and consistency.
  - Unified coupon code comparisons across cart operations for consistent behavior.
  - Updated rounding functions to support customizable rounding modes.

### CODE REVIEW

File: plugins/woocommerce/includes/class-wc-cart.php [hunk 1]
```diff
@@ -1810,16 +1810,22 @@ public function is_coupon_emails_allowed( $check_emails, $restrictions ) {
...
+
+		if ( ! $coupon_code ) {
+			return count( $applied_coupons ) > 0;
+		}
+
+		$coupon_code = wc_format_coupon_code( $coupon_code );
+
+		// Check if the coupon is in applied coupons using case-insensitive comparison.
+		foreach ( $applied_coupons as $applied_coupon ) {
+			if ( wc_is_same_coupon( $applied_coupon, $coupon_code ) ) {
```
Comment (ralucaStan) [inline plugins/woocommerce/includes/class-wc-cart.php:1823]: should we call `wc_format_coupon_code` on $applied_coupon? The previous code was doing that.

File: plugins/woocommerce/includes/class-wc-cart.php [hunk 2]
```diff
@@ -1959,8 +1977,15 @@ public function get_coupon_discount_amount( $code, $ex_tax = true ) {
...
-		return wc_cart_round_discount( isset( $totals[ $code ] ) ? $totals[ $code ] : 0, wc_get_price_decimals() );
+		$totals     = $this->get_coupon_discount_tax_totals();
+		$tax_amount = 0;
+		foreach ( $totals as $key => $value ) {
+			if ( wc_is_same_coupon( $key, $code ) ) {
+				$tax_amount = $value;
+				break;
+			}
+		}
+		return wc_cart_round_discount( $tax_amount, wc_get_price_decimals(), PHP_ROUND_HALF_DOWN );
```
Comment (ralucaStan) [inline plugins/woocommerce/includes/class-wc-cart.php]: I see there is a wc_get_tax_rounding_mode; should we use this here? Also, what do you think about fixing this in a separate PR to keep the scope of this PR related to the coupon codes cases

Comment (mikejolley) [reply plugins/woocommerce/includes/class-wc-cart.php]: This mirrors how it was done in Store API. Rounding discount up, tax down. The reason its in this PR is because I had to update the implementation in Store API to use shared functionality instead of handling it manually. You can see that here https://github.com/woocommerce/woocommerce/pull/58918/files#diff-62aaf031b2b5082e6c7b3782cd33b67a80e1e69761b893d8d10748cfcd3d2d5aL102-R101

File: plugins/woocommerce/includes/class-wc-cart.php (hunk 1 above)
Comment (mikejolley) [reply plugins/woocommerce/includes/class-wc-cart.php:1823]: `wc_is_same_coupon` handles lowercasing. Should `wc_is_same_coupon` use `wc_format_coupon_code` instead?

File: plugins/woocommerce/includes/class-wc-cart.php [hunk 3]
```diff
@@ -1983,19 +2008,13 @@ public function remove_coupons( $deprecated = null ) {
...
-		);
 
-		if ( false !== $position ) {
-			unset( $this->applied_coupons[ $position ] );
+		// Find the coupon in applied coupons using case-insensitive comparison.
+		foreach ( $this->get_applied_coupons() as $key => $applied_coupon ) {
+			if ( wc_is_same_coupon( $applied_coupon, $coupon_code ) ) {
+				unset( $this->applied_coupons[ $key ] );
+				break;
+			}
```
Comment (ralucaStan) [inline plugins/woocommerce/includes/class-wc-cart.php:2017]: the previous function was also using `wc_format_coupon_code` on the applied codes. But I see that [apply_coupon](https://github.com/woocommerce/woocommerce/blob/f6b266f9e8e86510aa20b9e5c0bad8c87c203b32/plugins/woocommerce/includes/class-wc-cart.php#L1844) already runs wc_format_coupon_code, so we are good.

File: plugins/woocommerce/includes/class-wc-cart.php (hunk 1 above)
Comment (ralucaStan) [reply plugins/woocommerce/includes/class-wc-cart.php:1823]: see comment https://github.com/woocommerce/woocommerce/pull/58918/files#r2159237871

File: plugins/woocommerce/src/StoreApi/Utilities/CartController.php [hunk 4]
```diff
@@ -1003,7 +1003,7 @@ public function apply_coupon( $coupon_code ) {
 				sprintf(
 					/* translators: %s coupon code */
 					esc_html__( 'Coupon code "%s" has already been applied.', 'woocommerce' ),
-					esc_html( $coupon_code )
+					esc_html( $coupon->get_code() )
```
Comment (ralucaStan) [inline plugins/woocommerce/src/StoreApi/Utilities/CartController.php:1006]: 👍

File: plugins/woocommerce/includes/wc-core-functions.php [hunk 5]
```diff
@@ -2591,10 +2591,11 @@ function wc_decimal_to_fraction( $decimal ) {
...
  * @param  double $value Amount to round.
  * @param  int    $precision DP to round.
+ * @param  int    $round_mode Round mode.
  * @return float
  */
-function wc_round_discount( $value, $precision ) {
-	return NumberUtil::round( $value, $precision, WC_DISCOUNT_ROUNDING_MODE ); // phpcs:ignore PHPCompatibility.FunctionUse.NewFunctionParameters.round_modeFound
+function wc_round_discount( $value, $precision, $round_mode = WC_DISCOUNT_ROUNDING_MODE ) {
+	return NumberUtil::round( $value, $precision, $round_mode ); // phpcs:ignore PHPCompatibility.FunctionUse.NewFunctionParameters.round_modeFound
 }
```
Comment (ralucaStan) [inline plugins/woocommerce/includes/wc-core-functions.php]: I feel we should put these rounding changes in another PR with testing steps that target it.

**Review by ralucaStan — CHANGES_REQUESTED** [review]
Hi Mike, I've added some comments. I think the rounding changes should live in a separate PR if there isn't a strong reason for keeping them together.

About my testing, the tests worked as expected:
- tested both cart/checkout shortcode and block
- tested with the code `VÅR20` from the PR that introduced the issue
- tested with `woocommerce_coupon_code` 
```
add_filter('woocommerce_coupon_code', function($code) {
    if ($code === 'filtercoupon') {
        return 'testcoupon'; // actual coupon stored in DB
    }
    return $code;
});
```

File: plugins/woocommerce/includes/class-wc-cart.php (hunk 1 above)
Comment (ralucaStan) [reply plugins/woocommerce/includes/class-wc-cart.php:1823]: I don't think `wc_is_same_coupon` use `wc_format_coupon_code` instead because:
- applied coupons have already had `wc_format_coupon_code` applied
- the pattern is to use `wc_format_coupon_code` on cart codes
- we might end up applying twice the filer to a coupon which might result in different codes

File: plugins/woocommerce/includes/class-wc-cart.php (hunk 2 above)
Comment (ralucaStan) [reply plugins/woocommerce/includes/class-wc-cart.php]: do you want to share some testing steps to test the rounding changes?

Comment (ralucaStan) [reply plugins/woocommerce/includes/class-wc-cart.php]: my concern was that we are fixing 2 aspects of coupons, case and tax, in the same PR. A regression in any of the areas won't make it easy to revert this PR.

Comment (mikejolley) [reply plugins/woocommerce/includes/class-wc-cart.php]: If I were to reuse the code from cart in the Store API, the rounding would change in Store API. So I have to duplicate logic to avoid that and leave one case incorrect. I'm assuming Store API which rounds discount tax total down is correct, because thats how other taxes are handled. There is no existing test case for correct discount totals which covers this edge case.

File: plugins/woocommerce/includes/wc-core-functions.php (hunk 5 above)
Comment (mikejolley) [reply plugins/woocommerce/includes/wc-core-functions.php]: https://github.com/woocommerce/woocommerce/pull/58918/commits/66d75cbb306a8a742193da7faa957421146cbf4f

File: plugins/woocommerce/includes/wc-formatting-functions.php [hunk 6]
```diff
@@ -376,11 +376,12 @@ function wc_format_coupon_code( $value ) {
  * Due to the unfiltered_html captability that some (admin) users have, we need to account for slashes.
  *
  * @since  3.6.0
+ * @since  10.0.0 Decode HTML entities here instead of via woocommerce_coupon_code filter.
  * @param  string $value Coupon code to format.
  * @return string
  */
 function wc_sanitize_coupon_code( $value ) {
-	$value = wp_kses( sanitize_post_field( 'post_title', $value ?? '', 0, 'db' ), 'entities' );
+	$value = wp_kses( sanitize_post_field( 'post_title', html_entity_decode( $value ?? '', ENT_COMPAT, get_bloginfo( 'charset' ) ), 0, 'db' ), 'entities' );
```
Comment (ralucaStan) [inline plugins/woocommerce/includes/wc-formatting-functions.php:390]: I did an analysis of this change and apparently: 
- `html_entity_decode` decodes an HTML entity
- `sanitize_post_field` re-encodes the character to an HTML entity
- and `wp_kses` allow HTML entities to pass 

because we do save the HTML entity in the database, do you think html_entity_decode is needed?

**Comment by ralucaStan** [comment]
Noticed one thing that is not consistent between block and shortcode. The saved coupon in the block is shown with the HTML entity, as it's saved in the database, while in the shortcode it's shown with characters. 

Screenshot 2025-06-24 at 16 57 46
Screenshot 2025-06-24 at 16 57 03

**Review by ralucaStan — COMMENTED** [review]
I retested my previous testing steps and it works as expected. I left a couple of comments. let me know what you think

File: plugins/woocommerce/includes/wc-formatting-functions.php (hunk 6 above)
Comment (mikejolley) [reply plugins/woocommerce/includes/wc-formatting-functions.php:390]: I'm not 100% sure but it exists in the codebase right now and I wouldn't want to regress something further by removing it. It was filtered before, I've moved it to this function.

**Comment by mikejolley** [comment]
@ralucaStan we need to decode entities in the client. [Fixed here](https://github.com/woocommerce/woocommerce/pull/58918/commits/7b009dc7bd00afabaddaa14db52d46388834b705)

File: plugins/woocommerce/includes/wc-formatting-functions.php (hunk 6 above)
Comment (mikejolley) [reply plugins/woocommerce/includes/wc-formatting-functions.php:390]: [Looks like an old change](https://github.com/woocommerce/woocommerce/commit/62cb430eaa60e2e503b0757698e9e167a2b9d54c) I don't think its needed. I've removed it and we'll see what CI does. I tested some coupons with ampersands and quotes and it seemed fine.

**Review by ralucaStan — APPROVED** [review]
tested again with yesterday's changes with encoding & decoding and it works as expected. approving

File: plugins/woocommerce/includes/wc-formatting-functions.php (hunk 6 above)
Comment (mikejolley) [reply plugins/woocommerce/includes/wc-formatting-functions.php:390]: Was needed. Added tests https://github.com/woocommerce/woocommerce/pull/58918/commits/e28e15b089af4959328bb373da5db5f9627e0bf1

Comment (ralucaStan) [reply plugins/woocommerce/includes/wc-formatting-functions.php:397]: why was it needed?

Comment (ralucaStan) [reply plugins/woocommerce/includes/wc-formatting-functions.php:390]: Already HTML encoded coupon codes weren't really on our radar. Amazing job adding the tests to catch any future regressions.

**Review by ralucaStan — APPROVED** [review]

**Comment by ralucaStan** [comment]
I've approved the PR. I also tested coupons with HTML entities inside and they work as expected in both shortcode and Block.
Mike, this PR brings significant value to the coupon area, not only ensuring casing but also providing a consistent experience and correct handling of user input. 👏
