### PR TITLE
Fixed - Cart Block shows dummy data for local pickup options in block editor

### LINKED ISSUE #55068: [Cart block editor] The Cart Block shows dummy data for local pickup options
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

In the Checkout block, https://github.com/woocommerce/woocommerce/pull/54533 removed the dummy local pickup options displayed in the editor, using the merchant-defined ones instead. 

We need to apply the same change to the Cart block.

### Expected behavior

When Local pickup is enabled, and there are local pickup options defined, they need to be shown in the Cart block; The list should reflect the options displayed in the Checkout block.

Notice the merchant defined Local pickup option in the Checkout block.
Image

### Actual behavior

The Cart block still uses the dummy local pickup options.

Notice the `Local pickup #1` option.

Image

### Steps to reproduce

1. Go to /wp-admin/admin.php?page=wc-settings&tab=shipping&section=pickup_location.
2. Enable local pickup and add a pickup location
3. Go to the Editor, see both checkout blocks
4.  notice the different Local pickup option displayed

### WordPress Environment

n/a

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by SpaceSurfer1**
Now the cart block shows dynamic data for local pickup options in block editor.

### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes #55068 .

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Go to /wp-admin/admin.php?page=wc-settings&tab=shipping&section=pickup_location.
2. Enable local pickup and add a pickup location
3. Go to the Editor, in cart block, the local pickup options are now dynamic as saved earlier.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [x] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 
Now the cart block shows dynamic data for local pickup options in block editor.
</details>

### CODE REVIEW

**Comment by SpaceSurfer1** [comment]
Hi, @opr , @kmanijak , This PR makes the local pickup options in cart block dynamic instead of earlier dummy data as requested in #55068. Kindly review it. Thanks.

File: plugins/woocommerce-blocks/assets/js/previews/shipping-rates.ts [hunk 1]
```diff
@@ -12,6 +12,7 @@ import { API_SITE_CURRENCY, displayForMinorUnit } from './utils';
 
 // Get local pickup locations from the settings and format into some preview shipping rates for the response.
 const localPickupEnabled = getSetting< boolean >( 'localPickupEnabled', false );
+const localPickupTitle = getSetting< string >( 'localPickupText', '' );
```
Comment (opr) [inline plugins/woocommerce-blocks/assets/js/previews/shipping-rates.ts]: We should default to something here, for example:
```suggestion
const localPickupTitle = getSetting< string >( 'localPickupText', __( 'Local pickup', 'woocommerce' ) );
```

File: plugins/woocommerce-blocks/assets/js/previews/shipping-rates.ts [hunk 2]
```diff
@@ -28,7 +29,7 @@ const localPickupRates = localPickupLocations
 	? Object.values( localPickupLocations ).map(
 			( location, index: number ) => ( {
 				...API_SITE_CURRENCY,
-				name: __( 'Local pickup #1', 'woocommerce' ),
+				name: localPickupTitle + ' (' + location.name + ')',
```
Comment (opr) [inline plugins/woocommerce-blocks/assets/js/previews/shipping-rates.ts]:
```suggestion
				name: `${ localPickupTitle } (${ location.name })`,
```

**Review by opr — CHANGES_REQUESTED** [review]
Hi @SpaceSurfer1 thanks for working on this, it's a great start. I left a couple of suggestions for how to improve it.

It will also need a changelog, you can generate this by running: `pnpm --filter=@woocommerce/plugin-woocommerce changelog add` and following the steps there. Commit this file when it's done.

Thanks!

File: plugins/woocommerce-blocks/assets/js/previews/shipping-rates.ts (hunk 2 above)
Comment (opr) [reply plugins/woocommerce-blocks/assets/js/previews/shipping-rates.ts]: I feel this makes the code more readable

**Comment by SpaceSurfer1** [comment]
@opr , Thanks for reviewing 👍 . I have commited the changes suggested and also added changelog. Thanks.

**Comment by opr** [comment]
@SpaceSurfer1 will review soon. BTW you don't need to keep updating the PR with changes from trunk, it stops the CI running.

**Comment by SpaceSurfer1** [comment]
> @SpaceSurfer1 will review soon. BTW you don't need to keep updating the PR with changes from trunk, it stops the CI running.

Understood 👍 . Thanks.

File: plugins/woocommerce-blocks/assets/js/previews/shipping-rates.ts [hunk 3]
```diff
@@ -12,6 +12,7 @@ import { API_SITE_CURRENCY, displayForMinorUnit } from './utils';
 
 // Get local pickup locations from the settings and format into some preview shipping rates for the response.
 const localPickupEnabled = getSetting< boolean >( 'localPickupEnabled', false );
+const localPickupTitle = getSetting< string >( 'localPickupText', __( 'Local pickup', 'woocommerce' ) );
```
Comment (opr) [inline plugins/woocommerce-blocks/assets/js/previews/shipping-rates.ts]: Apologies, this should be:
```suggestion
const localPickupTitle = getSetting< string >(
	'localPickupText',
	__( 'Local pickup', 'woocommerce' )
);
```

Comment (SpaceSurfer1) [reply plugins/woocommerce-blocks/assets/js/previews/shipping-rates.ts]: Resolved linting issue.

**Review by opr — APPROVED** [review]
Thanks a lot @SpaceSurfer1 looking good! We really appreciate your contribution 🙇🏼
