### PR TITLE
fix null strpos param

### LINKED ISSUE #44598: Deprecated: strpos(): Passing null to parameter
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

With PHP 8.2, on all the subpages of Tools > Import (for instance /wp-admin/admin.php?import=fgj2wp), I get this message:

`Deprecated: strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in /wp-content/plugins/woocommerce/src/Internal/Admin/Orders/PageController.php on line 146`

After investigation, I have found that in the file wp-content\plugins\woocommerce\src\Internal\Admin\Orders\PageController.php on line 134, we see:

`global $plugin_page`

The problem is that the variable `$plugin_page` isn’t defined on the Tools > Import pages.

### Expected behavior

No "deprecated" message should be displayed.

### Actual behavior

The message
`Deprecated: strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in /wp-content/plugins/woocommerce/src/Internal/Admin/Orders/PageController.php on line 146`
is displayed at the top of the page /wp-admin/admin.php?import=fgj2wp.

### Steps to reproduce

It happens only with PHP 8.2 when HPOS is enabled.

Steps to reproduce the issue:

1. Set define(‘WP_DEBUG’, true); in wp-config.php
2. Install and activate WooCommerce
3. Install and activate FG Joomla to WordPress https://wordpress.org/plugins/fg-joomla-to-wordpress/
4. Enable HPOS in the WooCommerce Advanced settings
5. Go to Tools > Import > Joomla (FG)

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): http://localhost/test/wordpresstest
Site address (URL): http://localhost/test/wordpresstest
WC Version: 8.5.2
REST API Version: ✔ 8.5.2
WC Blocks Version: ✔ 11.8.0-dev
Action Scheduler Version: ✔ 3.7.1
Log Directory Writable: ✔
WP Version: 6.4.3
WP Multisite: –
WP Memory Limit: 2 Go
WP Debug Mode: ✔
WP Cron: ✔
Language: fr_FR
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.54 (Unix) OpenSSL/1.0.2u PHP/8.2.0 mod_wsgi/3.5 Python/2.7.18 mod_fastcgi/mod_fastcgi-SNAP-0910052141 mod_perl/2.0.11 Perl/v5.30.1
PHP Version: 8.2.0
PHP Post Max Size: 8 Mo
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.68.0
OpenSSL/1.0.2u

SUHOSIN Installed: –
MySQL Version: 5.7.39
Max Upload Size: 8 Mo
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.5.2
WC Database Prefix: wp_
Taille totale de la base de données: 4.25MB
Taille de la base de données: 2.56MB
Taille de l’index: 1.69MB
wp_woocommerce_sessions: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_woocommerce_api_keys: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_woocommerce_attribute_taxonomies: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_woocommerce_downloadable_product_permissions: Données : 0.02MB + Index : 0.06MB + Moteur InnoDB
wp_woocommerce_order_items: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_woocommerce_order_itemmeta: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_woocommerce_tax_rates: Données : 0.02MB + Index : 0.06MB + Moteur InnoDB
wp_woocommerce_tax_rate_locations: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_woocommerce_shipping_zones: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_woocommerce_shipping_zone_locations: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_woocommerce_shipping_zone_methods: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_woocommerce_payment_tokens: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_woocommerce_payment_tokenmeta: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_woocommerce_log: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_actionscheduler_actions: Données : 0.02MB + Index : 0.11MB + Moteur InnoDB
wp_actionscheduler_claims: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_actionscheduler_groups: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_actionscheduler_logs: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_commentmeta: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_comments: Données : 0.02MB + Index : 0.09MB + Moteur InnoDB
wp_links: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_options: Données : 1.47MB + Index : 0.05MB + Moteur InnoDB
wp_postmeta: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_posts: Données : 0.06MB + Index : 0.06MB + Moteur InnoDB
wp_termmeta: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_terms: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_term_relationships: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_term_taxonomy: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_usermeta: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_users: Données : 0.02MB + Index : 0.05MB + Moteur InnoDB
wp_wc_admin_notes: Données : 0.06MB + Index : 0.00MB + Moteur InnoDB
wp_wc_admin_note_actions: Données : 0.05MB + Index : 0.02MB + Moteur InnoDB
wp_wc_category_lookup: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_wc_customer_lookup: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_wc_download_log: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_wc_orders: Données : 0.02MB + Index : 0.11MB + Moteur InnoDB
wp_wc_orders_meta: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_wc_order_addresses: Données : 0.02MB + Index : 0.06MB + Moteur InnoDB
wp_wc_order_coupon_lookup: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_wc_order_operational_data: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_wc_order_product_lookup: Données : 0.02MB + Index : 0.06MB + Moteur InnoDB
wp_wc_order_stats: Données : 0.02MB + Index : 0.05MB + Moteur InnoDB
wp_wc_order_tax_lookup: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_wc_product_attributes_lookup: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_wc_product_download_directories: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_wc_product_meta_lookup: Données : 0.02MB + Index : 0.09MB + Moteur InnoDB
wp_wc_rate_limits: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_wc_reserved_stock: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_wc_tax_rate_classes: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_wc_webhooks: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB

### Post Type Counts ###

attachment: 1
page: 7
post: 2
wp_navigation: 1
wp_template: 2

### Security ###

Secure connection (HTTPS): ❌
					Votre boutique n’utilise pas HTTPS. En savoir plus sur HTTPS et les certificats SSL.
Hide errors from visitors: ❌Les messages d’erreur ne doivent pas s’afficher aux visiteurs.

### Active Plugins (2) ###

FG Joomla to WordPress: par Frédéric GILLES – 4.20.0
WooCommerce: par Automattic – 8.5.2

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: 
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to Woo.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### WC Pages ###

Base de la boutique: #7 - /boutique/
Panier: #8 - /panier/
Commander: #9 - /commander/
Mon compte: #10 - /mon-compte/
Conditions générales de vente et d’utilisation: ❌ Page non définie

### Theme ###

Name: Twenty Twenty-Four
Version: 1.0
Author URL: https://fr.wordpress.org
Child Theme: ❌ – Si vous modifiez WooCommerce sur un thème parent que vous n‘avez pas construit personnellement
nous vous recommandons d‘utiliser un thème enfant. Voir : Comment créer un thème enfant

WooCommerce Support: ❌ Non déclaré

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
product-virtual-downloadable
product-external-affiliate
product-grouped
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: customize-store
minified-js
new-product-management-experience
product-linked
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2024-02-06 12:18:55 +01:00
Options: ✔
Notes: 63
Onboarding: skipped

### Action Scheduler ###

Terminé: 2
Oldest: 2024-02-05 13:19:58 +0100
Newest: 2024-02-05 13:19:58 +0100

En attente: 1
Oldest: 2024-02-06 13:19:58 +0100
Newest: 2024-02-06 13:19:58 +0100

### Status report information ###

Generated at: 2024-02-05 13:21:15 +01:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by olsonpm**
check whether $plugin_page is set prior to passing it to strpos

### Submission Review Guidelines:

- [x]  I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
- [x]  I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
- [x] I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).

-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

This PR fixes a bug where null was being passed to strpos causing an error

> Deprecated: strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in /wp-content/plugins/woocommerce/src/Internal/Admin/Orders/PageController.php on line 146

Closes #44598 

### How to test the changes in this Pull Request:

to reproduce the issue

1. clone woocommerce, ensure you're on the trunk branch and go through the setup instructions
2. edit "phpVersion" in plugins/woocommerce/.wp-env.json from "7.4" to "8.2"
3. run `pnpm --filter=@woocommerce/plugin-woocommerce env:dev`
4. on port 8888 you can now log in - install and activate the plugin "FG Joomla to WordPress"
5. on the installed plugins page click "Import" under the new plugin
6. confirm you see the following error at the top of the page

> Deprecated: strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in /var/www/html/wp-content/plugins/woocommerce/src/Internal/Admin/Orders/PageController.php on line 146

to confirm the fix, repeat all of the above with the following changes
in step 1: ensure you're on the branch in this pr
in step 6: confirm no error appears at the top of the page

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 
Fix a null parameter being passed into strpos in Admin/Orders/PageController.php
</details>

### CODE REVIEW

**Comment by olsonpm** [comment]
re: changelog job failure
- I wasn't aware I needed to remove the unused details block.  So I did, then force pushed the fixed changelog entry.  So the job failure shouldn't be relevant

File: plugins/woocommerce/src/Internal/Admin/Orders/PageController.php [hunk 1]
```diff
@@ -143,7 +143,7 @@ public function setup(): void {
 		}
 
 		// Not on an Orders page.
-		if ( 'admin.php' !== $pagenow || 0 !== strpos( $plugin_page, 'wc-orders' ) ) {
+		if ( ! isset( $plugin_page ) || 'admin.php' !== $pagenow || 0 !== strpos( $plugin_page, 'wc-orders' ) ) {
```
Comment (nerrad) [inline plugins/woocommerce/src/Internal/Admin/Orders/PageController.php]:
```suggestion
		if ( empty($plugin_page) || 'admin.php' !== $pagenow || 0 !== strpos( $plugin_page, 'wc-orders' ) ) {
```

A minor optimization, but I'm suggesting an `empty` check instead because that will cover when $plugin_page is both `null` or an empty string which would short circuit the other checks.

**Review by nerrad — COMMENTED** [review]
Thanks for the PR, I have a minor suggestion.

File: plugins/woocommerce/src/Internal/Admin/Orders/PageController.php (hunk 1 above)
Comment (olsonpm) [reply plugins/woocommerce/src/Internal/Admin/Orders/PageController.php]: if you don't mind making the commit, please do.  I'm no php dev, just took the change OP had.  I assume your suggestion makes sense :)

Comment (olsonpm) [reply plugins/woocommerce/src/Internal/Admin/Orders/PageController.php]: whoops, didn't realize github had a feature where i can just press commit.  Very convenient

**Review by Konamiman — APPROVED** [review]

**Comment by Konamiman** [comment]
For the record, alternative testing instructions using WP CLI:

Make sure that you have `define( 'WP_DEBUG', true );` in `wp_config.php`, then run `wp shell` and execute the following:

```php
global $plugin_page;
$plugin_page = NULL;
global $pagenow;
$pagenow = 'admin.php';
$pc = new Automattic\WooCommerce\Internal\Admin\Orders\PageController();
$pc->setup();
```

Without the fix you'll see the error message, with the fix you won't see it.

**Comment by Konamiman** [comment]
Hi @olsonpm, please rebase the branch from the latest trunk and let's see if the CI errors go away, thanks.

**Comment by olsonpm** [comment]
Thanks for explaining the simpler test setup.  The rebase was just force pushed, hopefully the build steps feel like working this time around
