### PR TITLE
[Accessibility] Announce to screen readers when the variations have been cleared

### LINKED ISSUE #43609: Accessibility: Reset variations "Clear" button on product single incorrectly coded as a link
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

The reset variations button is coded as a link when it should be a button. This is the current code:
`<a class="reset_variations" href="#" style="visibility: visible;">Clear</a>`

Links take people to a new page or a new part of a page. Buttons perform actions on a page. Because this clears the selections in the product variation inputs, this should be a button and not a link.

This either needs to be re-coded using a button tag, or it needs [role="button"](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/button_role) added to it and JavaScript written to add keyboard handlers for the Space Bar.

### Expected behavior

The clear button should be coded as a button and not a link.

### Actual behavior

The button is coded as a link, as show here:
https://github.com/woocommerce/woocommerce/blob/758df4854d7b627fc26eb5c0860dc492dea6a06e/plugins/woocommerce/templates/single-product/add-to-cart/variable.php#L48shown

### Steps to reproduce

See code linked above.

### WordPress Environment

N/A

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### LINKED ISSUE #43611: Accessibility: Clear button for product variations does not have an audible success message for screen reader users
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When using the clear button on the product single to reset selections on variable products, no success message is announced to screen reader users.

This video shows the clear button being triggered via keyboard and the variation fields clear but nothing is indicated to screen reader users that the button worked.
https://github.com/woocommerce/woocommerce/assets/13153456/e07c9d12-e343-4824-a16e-bfb0c8c5df88

### Expected behavior

There needs to be an auditory message for screen reader users so they know that the clear button works. 

Add a status message above or below the variation selection when options are cleared that says "Product selections cleared." Use [aria-live](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-live) to ensure screen readers read the message when it appears. If you don't want the visual notice, you can hide it as screen reader only text.

### Actual behavior

See video shared above.

### Steps to reproduce

1. Turn on a screen reader such as VoiceOver or NVDA.
2. Go to a variable product and select options.
3. Use your mouse or keyboard to trigger the "clear" button.
4. Listen and hear that nothing is announced telling you that it was successful.

### WordPress Environment

N/A

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by amesplant**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes #43611
Closes #43609

- The `reset_variations` has been updated from a link to a button
- The `reset_variations` button adds cleared screen reader text
- The `reset_variations` button also updates a new screen reader `alert`, announcing to users when they activate it, 'Your selection has been reset. Please select some product options before adding this product to your cart.' (translated into the appropriate language)

**Note**: since the `reset_variations` button has changed from a link to a button, it does change the appearance of the button for the Storefront Theme

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Activate your screen reader of chose
2. Select a Product that includes variations
3. Tab to a variation, use your arrows and space bar to make a selection
4. repeat for all variations
5. tab to the "clear" button
6. press spacebar to activate the clear button
7. you should hear that 'Your selection has been reset. Please select some product options before adding this product to your cart.' (translated into the appropriate language)

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce/templates/single-product/add-to-cart/variable.php [hunk 1]
```diff
@@ -45,13 +45,20 @@
...
 									)
 								);
-								echo end( $attribute_keys ) === $attribute_name ? wp_kses_post( apply_filters( 'woocommerce_reset_variations_link', '<a class="reset_variations" href="#">' . esc_html__( 'Clear', 'woocommerce' ) . '</a>' ) ) : '';
 							?>
 						</td>
 					</tr>
 				<?php endforeach; ?>
+				<tr>
+					<td colspan="2">
+						<button class="reset_variations wp-element-button" aria-label="<?php echo esc_html__( 'Clear options', 'woocommerce' ); ?>">
```
Comment (dkotter) [inline plugins/woocommerce/templates/single-product/add-to-cart/variable.php]: Looks like previously this was an anchor link and we're switching that to a button (and a slight change to how this is output). The concern I have here is it seems we're getting rid of the existing `woocommerce_reset_variations_link` filter, is that correct? Wondering if we can keep that or if not, we'll probably need to deprecate that for anyone that may be utilizing it.

**Review by dkotter — CHANGES_REQUESTED** [review]
In addition to the comment I left inline, there's also some failing E2E tests here, one of which seems related to variations: https://github.com/woocommerce/woocommerce/actions/runs/10185745386/job/28176011481?pr=50183#step:7:286

File: plugins/woocommerce/templates/single-product/add-to-cart/variable.php (hunk 1 above)
Comment (amesplant) [reply plugins/woocommerce/templates/single-product/add-to-cart/variable.php]: @dkotter I removed it as it felt like we just needed to have that button outside the actual variation options to make it easier for screen readers to navigate. If you think that there is a need to add it back in, maybe I am not understanding its purpose?

Comment (samueljseay) [reply plugins/woocommerce/templates/single-product/add-to-cart/variable.php]: @amesplant the issue is the removing of the filter. That's a breaking change for anyone using the filter. As mentioned by @dkotter if we want to remove a filter we really need to deprecate it to give chance to find an alternate solution.

Comment (amesplant) [reply plugins/woocommerce/templates/single-product/add-to-cart/variable.php]: @dkotter cc @samueljseay totally understand and happy to reinstate the filter, I will get that done today.

I am also working on the tests as well as the css since they are looking for a link and not a button.

Comment (amesplant) [reply plugins/woocommerce/templates/single-product/add-to-cart/variable.php]: @dkotter cc @samueljseay `woocommerce_reset_variations_link` has been reinstated 😄 , and tests and css have been addressed.

Do we need to add a test for the `reset` button since additional functionality has been included? In addition to its normal behavior, I have added a screen reader announcement for when the button has been selected.

**Review by dkotter — APPROVED** [review]
@ankitguptaindia @qasumitbagthariya This is ready for QA

**Comment by ankitguptaindia** [comment]
Hi @amesplant Thanks for working on this PR. I tried to test this PR but `'Your selection has been reset. Please select some product options before adding this product to your cart.'` doesn't announce when using macOS Sonoma 14.5 Voice Over. But this work fine when using Voice Over Chrome extension. 


**[Voice Over Chrome extension](https://chromewebstore.google.com/detail/screen-reader/kgejglhpjiefppelpmljglcjbhoiplfn):**  works ✅ 


https://github.com/user-attachments/assets/f7b7dea8-d7be-4a1a-9b46-00af1b7ea943


**macOS Sonoma 14.5 Voice Over:**  ⚠️ 



https://github.com/user-attachments/assets/f20ba31e-dcdd-4eae-820d-6fd6abddcaef


I tested this on two different setups with WP 2024 and Storefront and facing the same response.

**Comment by amesplant** [comment]
@ankitguptaindia 
Curious .. I have it working using Mac VoiceOver browsing with Safari (which is the browser that VoiceOver supports) as well as in Chrome. Same OS (Mac Sonoma Version 14.5)
[ProductVarationsClear.webm](https://github.com/user-attachments/assets/615f46e1-e4ce-4def-854b-43156afcdbee)

**Comment by qasumitbagthariya** [comment]
@amesplant @ankitguptaindia 

I've cross-check this PR and it's working using **macOS Ventura 13.3** Voice Over. ✅


https://github.com/user-attachments/assets/ee011729-0d71-4248-95f0-d59d33c2445a

**Testing Environment** 

<Details>

- WordPress: 6.6.1
- Theme: Storefront 4.6.0
- WooCommerce - WooCommerce - Dev version with this fix specific branch.
- PHP: 8.0.30
- Web Server: Nginx 1.20.2
- Browser: Chrome 
- OS: macOS Ventura 13.3 
- Branch: [smoke-testing](amesplant:fix/43611-product-variation-clear-button)

</Details>

**Comment by ankitguptaindia** [comment]
@amesplant, I have tested my testing setup site on @qasumitbagthariya's system and found that the same product and URL  working as expected. This confirms that the issue is not related to the site settings or plugin compatibility. The only difference I notice is the macOS/Voice Over versions between Sumit's system and mine.

**Comment by ankitguptaindia** [comment]
@amesplant

In addition to the note above, I tested this again in a new environment with some troubleshooting steps, such as simulating a slow network connection and using a new browser instance, etc.

When testing on Safari (Version 17.5 (19618.2.12.11.6)), I noticed that it works fine when using a mouse instead of keyboard tabs. However, when using the tab key, it does not display the intended message.

On Chrome (Version 127.0.6533.89), it only works once out of every 8-10 attempts.

I have configured this PR on a disposable site where I am able to reproduce the issue. If you want to troubleshoot here, you can use this product: https://testy-toad-5lhm4.instawp.xyz/product/hoodie/.



**Please watch the below screencast for testing steps:**

<details>

Safari: 

https://github.com/user-attachments/assets/91513ae1-66c2-4439-b282-4709c4189e97

Chrome: 


https://github.com/user-attachments/assets/b2e56219-ce60-4829-95d0-4b72ff50cb60


</details>

**Comment by amesplant** [comment]
@ankitguptaindia try now .. I had to do some "extra" stuff to get Voiceover to work on Chrome like it does on Safari, and it seems to be working on my side.

**Comment by ankitguptaindia** [comment]
@amesplant Could you please quickly check, I can still see `Your selection has been reset. Please select some product options before adding this product to your cart.` below the clear button when using Storefront theme. 

https://i.imgur.com/bLV5IHo.jpeg

**Comment by amesplant** [comment]
@ankitguptaindia I made some tweaks to how this functions and so now the alert should not be visible on any theme, announced correctly, and the focus after clearing gets placed on the first variation.

**Comment by ankitguptaindia** [comment]
**QA/Test Report-** ✅ 
------------

**Testing Environment -** 

<Details>

* WordPress: 6.6.1
* Theme: 
**Storefront Version: 4.6.0  
**Twenty Twenty-Four Version: 1.2
* WooCommerce - Development version with this fix-specific branch.  
* PHP: 8.3
* Web Server: Nginx
* Browser: Chrome - Version 127
* OS: macOS Sonoma 14.5
* Git Branch: fix/43614


</Details>


**Test Results -** 

The changes work as intended and tested across Safari, Firefox, and Chrome. Accessibility was verified using macOS VoiceOver and the Chrome Screen Reader extension. Testing was conducted with both the Storefront theme and the Twenty Twenty-Four theme.
 

**Functional Demo /  Screencast -**

**With macOS VoiceOver:**

https://github.com/user-attachments/assets/1afc79f3-98ed-4156-ab20-0abbf377d38c

**Comment by ankitguptaindia** [comment]
Hi 👋🏼 @amesplant 
Thanks for the excellent work on this PR! All cases have been successfully verified in testing. Could you please undraft and mark this PR as ready for review?

**Comment by amesplant** [comment]
@dkotter do you want to make one more pass a the code since I changed direction a bit on where the focus was added once the the variations were reset? It has passed QA and so if the code looks good, then we can pass this to @vikrampm1 to assign over to Woo for review.

File: plugins/woocommerce/templates/single-product/add-to-cart/variable.php [hunk 2]
```diff
@@ -45,13 +45,27 @@
...
+							 * @param string  $button The reset variation button HTML.
+							 */
+							echo end( $attribute_keys ) === $attribute_name ? wp_kses_post( apply_filters( 'woocommerce_reset_variations_link', '<button class="reset_variations"  aria-label="' . esc_html__( 'Clear options', 'woocommerce' ) . '">' . esc_html__( 'Clear', 'woocommerce' ) . '</button>' ) ) : '';
 							?>
 						</td>
 					</tr>
 				<?php endforeach; ?>
 			</tbody>
 		</table>
+		<div class="reset_variations_alert screen-reader-text" role='alert' aria-live='polite' aria-relevant="all"></div>
```
Comment (dkotter) [inline plugins/woocommerce/templates/single-product/add-to-cart/variable.php]: For consistency sake, we should use double quotes on all attributes:

```suggestion
		<div class="reset_variations_alert screen-reader-text" role="alert" aria-live="polite" aria-relevant="all"></div>
```

**Review by dkotter — CHANGES_REQUESTED** [review]

**Comment by amesplant** [comment]
@dkotter thanks .. I have committed your suggestion, @vikrampm1 passing to you to assign over to Woo for review.

**Comment by vikrampm1** [comment]
@samueljseay / @woocommerce/woo-fse this PR is ready for your review!

**Comment by vikrampm1** [comment]
@samueljseay / @woocommerce/woo-fse noting that this PR is awaiting your review.

**Comment by samueljseay** [comment]
@vikrampm1 

Hey folks, I am not aware with the process when handing over to Woo, but it's a little unclear to me what my review should entail here. I cannot assign the time to do accessibility testing like has already been done here right now, but I can give a code review if that's enough?

🙇🏻

**Comment by vikrampm1** [comment]
@samueljseay I think a code review from you would be good enough. Please also merge the PR once it is good to go as it has already completed all the steps from our end. Thanks!

**Review by samueljseay — APPROVED** [review]
I'm happy with the code changes that have been made here 👍🏻

**Comment by samueljseay** [comment]
@amesplant @vikrampm1 It looks good, but I think someone will need to retest the conflict because it's in the same area as the manipulated code here and probably we want to be careful that any changes don't introduce a regression in the modified code.

**Comment by vikrampm1** [comment]
@ankitguptaindia can you test this PR again and share the QA report? If everything looks good then @samueljseay can proceed and merge the PR.

**Comment by jeffpaul** [comment]
@samueljseay if your code review looks good now, then should be good to merge for Woo core (as we're done review/testing on our end)?

**Comment by jeffpaul** [comment]
@samueljseay checking back in to see if you had additional code review feedback here or if this was good to merge?

**Comment by samueljseay** [comment]
Sorry @jeffpaul I missed the ping, thanks for the reminder. I think due to release timing that the version number on the template will need to be bumped. Are you able to do that? 

Apart from that I don't have any additional feedback. It looks good.

**Comment by vikrampm1** [comment]
@Manussakis can you able to help bumping the version number here? I think it should be updated to 9.4.0.
 Once that is done @samueljseay can proceed and merge the PR.

**Comment by Manussakis** [comment]
@vikrampm1 @samueljseay The template version has been bumped!

**Comment by vikrampm1** [comment]
@samueljseay please proceed and merge the PR. Thanks!

**Comment by vikrampm1** [comment]
@samueljseay is there anything else needed on this PR?

**Comment by samueljseay** [comment]
@vikrampm1 Passing CI 😅 I updated a couple of times to see whether it was a flaky CI step but it's still failing.

**Comment by samueljseay** [comment]
@vikrampm1 Oh it looked like required checks were failing, but they're non-critical ones. I'll merge this. Sorry about the delay.

**Comment by vikrampm1** [comment]
@woocommerce/woo-fse can someone please help merge this PR as Sam seems to be unavailable and this has been pending for a while now? Thanks.

**Comment by samueljseay** [comment]
@vikrampm1 Sorry again for the delay, this dropped off my radar before I went on leave. I have bumped the template version since this won't make it in to 9.4.0. I will merge this when CI is green
