### PR TITLE
Round late when rounding at subtotal to reduce rounding error.

### LINKED ISSUE #23917: Multiple tax rates with tax inclusive pricing returning 1 cent off totals
**Describe the bug**
This is a question, but may turn into a bug. 

If two tax rates are used, along with tax inclusive pricing, the total for products will become incorrect in the cart. 

**Related tickets**
2080235-zen

**To Reproduce**
1. Set two tax rates at 9%, one with priority of 1, the other priority of 2
2. Create two products, one with a cost of 599.00, and the other 4.50
3. Add the 599 product to the cart, the total is 599.00
4. Remove the 599 product and add the 4.50 to the cart, total is 4.49

**Screenshots**

Image Link: https://cld.wthms.co/4BsntR

Image Link: https://cld.wthms.co/IJyV67

Image Link: https://cld.wthms.co/BDHgKZ

**Expected behavior**
I would expect that the total would be the same as the product prices for both instances

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
`
### WordPress Environment ###

WordPress address (URL): http://clean.test
Site address (URL): http://clean.test
WC Version: 3.6.4
Log Directory Writable: ✔
WP Version: 5.2.1
WP Multisite: –
WP Memory Limit: 2 GB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.15.2
PHP Version: 7.2.13
PHP Post Max Size: 128 MB
PHP Time Limit: 300
PHP Max Input Vars: 2500
cURL Version: 7.63.0
OpenSSL/1.0.2q

SUHOSIN Installed: –
MySQL Version: 5.7.21
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.6.4
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Total Database Size: 5.38MB
Database Data Size: 3.78MB
Database Index Size: 1.60MB
wp_woocommerce_sessions: Data: 0.03MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_comments: Data: 0.06MB + Index: 0.09MB
wp_failed_jobs: Data: 0.02MB + Index: 0.00MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_mailchimp_carts: Data: 0.02MB + Index: 0.00MB
wp_options: Data: 2.02MB + Index: 0.05MB
wp_postmeta: Data: 0.34MB + Index: 0.36MB
wp_posts: Data: 0.14MB + Index: 0.06MB
wp_queue: Data: 0.02MB + Index: 0.00MB
wp_termmeta: Data: 0.02MB + Index: 0.03MB
wp_terms: Data: 0.02MB + Index: 0.03MB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wp_usermeta: Data: 0.02MB + Index: 0.03MB
wp_users: Data: 0.02MB + Index: 0.05MB
wp_wcpv_commissions: Data: 0.02MB + Index: 0.00MB
wp_wcpv_per_product_shipping_rules: Data: 0.02MB + Index: 0.00MB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB
wp_wc_bookings_availability: Data: 0.02MB + Index: 0.02MB
wp_wc_bookings_availabilitymeta: Data: 0.02MB + Index: 0.03MB
wp_wc_booking_relationships: Data: 0.02MB + Index: 0.03MB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB
wp_wpml_mails: Data: 0.41MB + Index: 0.00MB

### Post Type Counts ###

attachment: 2
bookable_person: 13
bookable_resource: 15
page: 6
post: 2
product: 46
product_variation: 12
revision: 1
scheduled-action: 58
shop_order: 2
user_request: 3
wc_booking: 151

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 3.6.4

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: booking (booking)
external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #5 - /shop/
Cart: #6 - /cart/
Checkout: #7 - /checkout/
My account: #8 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 2.4.3 – 2.5.0 is available
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 57
Oldest: 2019-06-04 07:55:36 -0400
Newest: 2019-06-12 10:50:00 -0400

Pending: 0
Oldest: –
Newest: –

Canceled: 1
Oldest: 2019-06-12 11:50:00 -0400
Newest: 2019-06-12 11:50:00 -0400

In-progress: 0
Oldest: –
Newest: –

Failed: 0
Oldest: –
Newest: –

`
```
</details>

### PR DESCRIPTION
**Pull request by vedanshujain**
### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

This experiments with approach suggested in https://github.com/woocommerce/woocommerce/issues/23917#issuecomment-505033366 . When the setting "Round at subtotal" is selected, we will round as late as possible. This means that there could be a 0.01 difference between sum of individual lines and the actual total value, when prices are inclusive of taxes, but that total will the same as the price that author entered. 

This should not affect anything when the setting "round at subtotal" is disabled. More explanation in commit message.

Closes #23917  .

### How to test the changes in this Pull Request:

1. Enable settings:
a. Round at subtotal
b. Prices are inclusive of taxes
2. Add a product with price `599`
3. Add two tax rows for 24% with priority 1 and 2 respectively
4. Add the product in the card. You will notice that the sum is now `599`, instead of `599.01` without this commit.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

Round tax late when rounding at subtotal setting is enabled to reduce rounding error.

### CODE REVIEW

**Comment by vedanshujain** [comment]
Note that travis ci is failing on code standard check, although none of violations are because of the code in this PR. Because of the large number of violations in that file, its probably better to fix it in a separate PR.

**Comment by vedanshujain** [comment]
@mikejolley What do you think about this approach?

**Comment by mikejolley** [comment]
@vedanshujain If the unit tests continue to pass, looks solid :) I don't see any obvious issues here.

File: includes/class-wc-cart-totals.php [hunk 1]
```diff
@@ -876,4 +887,18 @@ protected function round_line_tax( $value ) {
...
 	}
+
+	/**
+	 * Apply rounding to item subtotal before summing.
+	 *
+	 * @param float $value Item subtotal value.
+	 *
+	 * @return float
+	 */
+	protected function round_item_subtotal( $value ) {
```
Comment (kloon) [inline includes/class-wc-cart-totals.php]: Can you add a @ since tag here so we know when this was introduced?

**Review by kloon — APPROVED** [review]
Looks good, thanks for adding the units tests as well. Just a small suggestion but not a blocker to merge.

File: includes/class-wc-cart-totals.php (hunk 1 above)
Comment (vedanshujain) [reply includes/class-wc-cart-totals.php]: Added
