### PR TITLE
Move product button add to cart text strings from state to context 

### LINKED ISSUE #59032: Add to Cart + Options: adding a grouped product to cart shows '### in cart' if there are simple products in cart with other product buttons
Initially reported by @helgatheviking in https://github.com/woocommerce/woocommerce/issues/58990#issuecomment-2988563229.

When simple products are in the cart and their *Add to Cart Button* block is rendered on the page, adding a grouped product to cart from the *Add to Cart + Options* block can cause the button text to be `### in cart` instead of `Added to cart`. Depending on the order of the products on the page, the opposite might happen: `Added to cart` being used for both, the grouped and the simple products.

## Steps to reproduce

1. Add two _Single Product_ blocks into a post or page, one containing a grouped product and the next containing a simple product.
2. In the frontend, add the simple product into the cart.
3. Reload the page.
4. Add the grouped product into the cart.
5. `### in cart` appears on the button.

https://github.com/user-attachments/assets/2072c845-e604-426a-9619-1d0f0ab270af

## Solution

As @helgatheviking mentions in https://github.com/woocommerce/woocommerce/pull/58997#discussion_r2159063447, the issue might be that we are saving `inTheCartText` in the global state instead of a local store.

### PR DESCRIPTION
**Pull request by helgatheviking**
### Changes proposed in this Pull Request:

Move product button add to cart text strings from state to context. this improves compatibility with multiple buttons on a single page. 

Closes #59032.
### Screenshots or screen recordings:

before:
image

after:
image

### How to test the changes in this Pull Request:

see https://github.com/woocommerce/woocommerce/issues/59032 for how to reproduce. I was also able to see it with a grouped products single product page and a related products block on the same page.

with this patch the text should always say "added to cart" after a grouped product is added to cart. 

Keep in mind that until #58990 is merged you will automatically add _all_ the grouped products.

### CODE REVIEW

File: plugins/woocommerce/src/Blocks/BlockTypes/ProductButton.php [hunk 1]
```diff
@@ -279,9 +270,10 @@ class="{button_classes}"
 					'{wrapper_attributes}'     => $wrapper_attributes,
 					'{html_element}'           => $html_element,
 					'{button_classes}'         => $button_classes,
+					'{context_directives}'     => $context_directives,
 					'{button_styles}'          => esc_attr( $styles_and_classes['styles'] ),
 					'{attributes}'             => isset( $args['attributes'] ) ? wc_implode_html_attributes( $args['attributes'] ) : '',
-					'{add_to_cart_text}'       => $is_ajax_button ? '' : $add_to_cart_text,
```
Comment (gigitux) [inline plugins/woocommerce/src/Blocks/BlockTypes/ProductButton.php]: Is there a particular reason do you removed this check?

**Review by gigitux — CHANGES_REQUESTED** [review]
Thanks for the contribution! 🙇 

I only reviewed the code. Everything looks great except that for a removed check that I think that we should keep. Furthermore, could you fix the lint errors as well? Thanks!

File: plugins/woocommerce/src/Blocks/BlockTypes/ProductButton.php (hunk 1 above)
Comment (helgatheviking) [reply plugins/woocommerce/src/Blocks/BlockTypes/ProductButton.php]: I think it was because the button text was empty and it was printing an empty button. The text was added via JS, so with no JS there was no text.

image

Though looks like that might have been because I forgot to change:

```
data-wp-text="state.addToCartText"
```

to

```data-wp-text="context.addToCartText"```

Can you explain the reason for the check? Like what is the desired outcome if there's no ajax add to cart support? Once I fix the state -> context line this check doesn't seem to make a difference.

File: plugins/woocommerce/src/Blocks/BlockTypes/ProductButton.php [hunk 2]
```diff
@@ -213,17 +202,18 @@ protected function render( $attributes, $content, $block ) {
...
+		$context_directives = wp_interactivity_data_wp_context( $context );
+
 		$button_directives = $is_descendant_of_add_to_cart_form ?
 			'data-wp-class--disabled="woocommerce/add-to-cart-with-options::!state.isFormValid"' :
 			'data-wp-on--click="actions.addCartItem"';
 		$anchor_directive  = $is_descendant_of_add_to_cart_form ? '' : 'data-wp-on--click="woocommerce/product-collection::actions.viewProduct"';
 
 		$span_button_directives = '
-			data-wp-text="state.addToCartText"
+			data-wp-text="context.addToCartText"
```
Comment (gigitux) [inline plugins/woocommerce/src/Blocks/BlockTypes/ProductButton.php]: This should be 
```suggestion
			data-wp-text="state.addToCartText"
```


[According to the documentation](https://developer.wordpress.org/block-editor/reference-guides/interactivity-api/core-concepts/server-side-rendering/#:~:text=Let%E2%80%99s%20fix%20that,logic%20in%20PHP%3A), we need to define the derived state too on the server side to avoid any flickering effect. In this case, this snippet is enough.

```php
		wp_interactivity_state(
			'woocommerce/product-button',
			array(
				'addToCartText' => function () {
					$context = wp_interactivity_get_context();
					return $context['addToCartText'];
				},
			)
		);
```

File: plugins/woocommerce/src/Blocks/BlockTypes/ProductButton.php (hunk 1 above)
Comment (gigitux) [reply plugins/woocommerce/src/Blocks/BlockTypes/ProductButton.php]: `is_ajax_button` is necessary to ensure that this setting is correctly applied when the Product Button is used in the Product Collection:

**Review by gigitux — CHANGES_REQUESTED** [review]
Thanks for address the feedback. This component is used inside the Product Collection block. Currently, the button is broken:



https://github.com/user-attachments/assets/70a7c73b-7cf1-47e3-9908-3431b2f8de5b




I left a few comments that you should be able to fix the flickering effect and I left more details regarding the `is_ajax_button`. Ping me if something is not clear 🙇 Thanks!

File: plugins/woocommerce/src/Blocks/BlockTypes/ProductButton.php (hunk 2 above)
Comment (helgatheviking) [reply plugins/woocommerce/src/Blocks/BlockTypes/ProductButton.php]: To prevent flickering (and to make it work without JS) we could also just provide text in the button element. That's what I was going for by removing the `$is_ajax_button` check. Adding state seems like overkill when we can do `<button>text</button>`. It's just a question of the right text, since as you pointed out, it's NOT "add to cart" in the product collection if the ajax setting is not enabled. :thinking:

Comment (helgatheviking) [reply plugins/woocommerce/src/Blocks/BlockTypes/ProductButton.php]: ah i see. if we go back to `state.addToCartText` (And that's needed to fix the button) then WP will parse that and we do have to provide an initial state. on it.

Comment (gigitux) [reply plugins/woocommerce/src/Blocks/BlockTypes/ProductButton.php]: > ah i see. if we go back to state.addToCartText (And that's needed to fix the button) then WP will parse that and we do have to provide an initial state. on it.

Yep, exactly!

**Comment by helgatheviking** [comment]
@gigitux Is there a command for fixing the lint errors on JUST these changes? I tried running `pnpm run lint:php:fix` and it touched every file in the plugin! :scream: 

I found 2 things
1. If you are on the single product page and you have one of that product in the cart already the add to cart button reads: "1 in cart". But if you then remove the product from the cart (Via the mini cart). The button text flashes, but it doesn't change back to "Add to cart". This does work if you load the page with nothing in the cart. 
[Apple Soda – Kathy Sandbox - 27 June 2025 - Watch Video](https://www.loom.com/share/cb8b5f84ba554636a5b8c9f2314bef01) (hopefully fixed in https://github.com/woocommerce/woocommerce/pull/59037/commits/7ad0366ea9ab6c430e572260ed7c6914972f905c)

and 

2. If JS is disabled the collection buttons still read "add to cart" but they are buttons and don't DO anything. The "read more" buttons are actually link elements and so they still function. This is a regression, if you look at the Storefront archive for example, the button was a `?add-to-cart=225` link, so clicking on it still added the product to the cart (just with page reload)

File: plugins/woocommerce/src/Blocks/BlockTypes/ProductButton.php (hunk 2 above)
Comment (helgatheviking) [reply plugins/woocommerce/src/Blocks/BlockTypes/ProductButton.php]: If the add to cart text is parsed by the iAPI server side state, then does `$is_ajax_button` still matter for the `{add_to_cart_text}`?

Comment (gigitux) [reply plugins/woocommerce/src/Blocks/BlockTypes/ProductButton.php]: No, we can remove `{add_to_cart_text}`.

Comment (gigitux) [reply plugins/woocommerce/src/Blocks/BlockTypes/ProductButton.php]: No. For this reason, I think that we need to include the `$is_ajax_button` check when the `add_to_cart_text` is defined in the context: does it make sense?

Comment (helgatheviking) [reply plugins/woocommerce/src/Blocks/BlockTypes/ProductButton.php]: Not yet :sweat_smile: if it's parsed by the iAPI in all cases, you can put text there or not and it's still going to be the state value. so what does the conditional do differently?

**Comment by gigitux** [comment]
> 2\. If JS is disabled the collection buttons still read "add to cart" but they are buttons and don't DO anything. The "read more" buttons are actually link elements and so they still function. This is a regression, if you look at the Storefront archive for example, the button was a `?add-to-cart=225` link, so clicking on it still added the product to the cart (just with page reload)

Are you sure? I'm not able to replicate this issue.

**Comment by helgatheviking** [comment]
If the store setting for ajax add to cart is enabled, you get a `<button>` element in the markup
```
<button class="wp-block-button__link wp-element-button wc-block-components-product-button__button add_to_cart_button ajax_add_to_cart product_type_simple has-font-size has-small-font-size has-text-align-center wc-interactive" style="" type="button" data-product_id="225" data-product_sku="SODAAPPLE" aria-label="Add to cart: “Apple Soda”" data-wp-on--click="actions.addCartItem">
					<span data-wp-text="state.addToCartText" data-wp-class--wc-block-slide-in="state.slideInAnimation" data-wp-class--wc-block-slide-out="state.slideOutAnimation" data-wp-on--animationend="actions.handleAnimationEnd" data-wp-watch="callbacks.startAnimation" data-wp-run="callbacks.syncTempQuantityOnLoad" data-wp-on--click="actions.handlePressedState">Add to cart</span>
					</button>
```

But if the customer has JS disabled in their browser, the button does nothing.

**Comment by gigitux** [comment]
> If the store setting for ajax add to cart is enabled, you get a `<button>` element in the markup
> 
> ```
> <button class="wp-block-button__link wp-element-button wc-block-components-product-button__button add_to_cart_button ajax_add_to_cart product_type_simple has-font-size has-small-font-size has-text-align-center wc-interactive" style="" type="button" data-product_id="225" data-product_sku="SODAAPPLE" aria-label="Add to cart: “Apple Soda”" data-wp-on--click="actions.addCartItem">
> 					<span data-wp-text="state.addToCartText" data-wp-class--wc-block-slide-in="state.slideInAnimation" data-wp-class--wc-block-slide-out="state.slideOutAnimation" data-wp-on--animationend="actions.handleAnimationEnd" data-wp-watch="callbacks.startAnimation" data-wp-run="callbacks.syncTempQuantityOnLoad" data-wp-on--click="actions.handlePressedState">Add to cart</span>
> 					</button>
> ```
> 
> But if the customer has JS disabled in their browser, the button does nothing.

I think that this is the right behavior. It is impossible to have AJAX without JavaScript.


Also, this happens on the current stable WooCommerce version:


https://github.com/user-attachments/assets/f207c057-a906-4e66-a3b8-bb15550511f5

**Comment by helgatheviking** [comment]
If you go to storefront theme or something using the old templates those were links that still _worked_.

**Comment by gigitux** [comment]
> If you go to storefront theme or something using the old templates those were links that still _worked_.

Yeah, you're right! 

https://github.com/user-attachments/assets/2042d991-2ad8-4ba9-90ae-cfffbb0d81ff

Hoverer, this issue isn't related to this PR. Could you create a dedicated issue, so we can discuss it there? Thanks 🙇

**Comment by helgatheviking** [comment]
here's the separate issue https://github.com/woocommerce/woocommerce/issues/59330

**Review by gigitux — APPROVED** [review]
Thanks for working on this! I fixed a lint error with 6538ddf. I tested the PR following the reproduction steps in https://github.com/woocommerce/woocommerce/issues/59032 and everything works as expected:


https://github.com/user-attachments/assets/d4062b7e-314a-403a-94b9-915536edef5e
