### PR TITLE
Analytics stock totals excludes trashed products

### LINKED ISSUE #62750: Analytics Stock totals incorrectly include trashed products
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

The Analytics Stock Stats include products that have been moved to the trash in the footer totals. Trashed products should be ignored as they are "soft deleted". Physically deleting the products results in correct statistics. This is appears related to issue #36747 which may have the same root cause for order analytics.

### Expected behavior

Products moved to the trash should be excluded from Analytics Stock Stats footer totals. Only published products should be counted.

### Actual behavior

Products that have been moved to the trash continue to affect the Analytics Stock Stats footer totals. Their counts appear in fields like "Out of Stock" count at the bottom of the Analytics > Stock page.

The trashed products are correctly removed from the product list displayed as rows in the table on the page, but they remain included in the summary statistics shown in the footer.

### Steps to reproduce

1. On a WooCommerce site, create a two new products and set the both to "Out of Stock"
2. Go to WooCommerce > Analytics > Stock
3. Scroll to the bottom of the page and note the footer totals (e.g., "2 out of stock")
4. Go to Products page
5. Move the out of stock product to the trash
6. Return to WooCommerce > Analytics > Stock
7. Refresh the page

Image

Expected: Footer should show "1 out of stock"<br>Actual: Footer still shows "2 out of stock"

Additional test:

1. Go to Products > Trash
2. Delete the product permanently
3. Return to WooCommerce > Analytics > Stock and refresh
4. The footer now correctly shows "1 out of stock"

### WordPress Environment

<details><summary>System Status Report</summary>

```
### WordPress Environment ###

WordPress address (URL): [Redacted]
Site address (URL): [Redacted]
WC Version: 10.4.3
Legacy REST API Package Version: The Legacy REST API plugin is not installed on this site.
Action Scheduler Version: ✔ 3.9.3
Log Directory Writable: ✔
WP Version: ❌ 6.8.3 - There is a newer version of WordPress available (6.9)
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: –
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: Unit/1.33.0
Server Architecture: Linux 5.14.0-611.13.1.el9_7.x86_64 x86_64
PHP Version: 8.1.34
PHP Post Max Size: 1 GB
PHP Time Limit: 180
PHP Max Input Vars: 10000
cURL Version: 7.88.1
OpenSSL/3.0.17

SUHOSIN Installed: –
MySQL Version: 8.0.37-29
Max Upload Size: 1 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

[REDACTED]

### Post Type Counts ###

attachment: 41
custom_css: 1
nav_menu_item: 8
page: 20
post: 5
product: 84
product_variation: 175
revision: 19
shop_order_placehold: 10

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (6) ###

Akismet Anti-spam: Spam Protection: by Automattic - Anti-spam Team – 5.6
CoBlocks: by GoDaddy – 3.1.16
Code Snippets: by Code Snippets Pro – 3.9.3
Log HTTP Requests: by FacetWP
LLC – 1.5.0

MWC Core.: by  –
WooCommerce: by Automattic – 10.4.3

### Inactive Plugins (0) ###


### Dropin Plugins () ###

object-cache.php: Object Cache Pro (Drop-in)

### Must Use Plugins (3) ###

Disable System MWC Core: by  – 1.0.0
Object Cache Pro (MU): by Rhubarb Group – 1.24.5
System Plugin: by  – 4.221.0

### Settings ###

Legacy API Enabled: –
Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature enabled: ✔
Order datastore: GoDaddy\WordPress\MWC\Core\Features\Commerce\Orders\WooCommerce\OrderDataStore
HPOS data sync enabled: –
Enabled Features: analytics
marketplace
order_attribution
site_visibility_badge
remote_logging
email_improvements
blueprint
point_of_sale
custom_order_tables


### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 7 days
Level threshold: –
Log directory size: 456 B

### WC Pages ###

Shop base: #58 - /shop-page/
Cart: #72 - /cart-page/ -  Contains the [woocommerce_cart] shortcode
Checkout: #71 - /checkout-page/ -  Contains the [woocommerce_checkout] shortcode
My account: #63 - /account-page/ -  Contains the [woocommerce_my_account] shortcode
Terms and conditions: ❌ Page not set

### Theme ###

Name: Go
Version: 1.8.18
Author URL: https://www.godaddy.com
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
Theme type: Classic theme
WooCommerce Support: ✔

### Templates ###

Archive Template: Your theme has a woocommerce.php file
you will not be able to override the woocommerce/archive-product.php custom template since woocommerce.php has priority over archive-product.php. This is intended to prevent display issues.

Overrides: go/woocommerce/cart/cart.php

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
experimental-iapi-mini-cart
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
onboarding
onboarding-tasks
pattern-toolkit-full-composability
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
printful
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page
launch-your-store

Disabled Features: product-data-views
experimental-blocks
experimental-iapi-runtime
coming-soon-newsletter-template
minified-js
product-pre-publish-modal
products-catalog-api
settings
async-product-editor-category-field
product-editor-template-system
use-wp-horizon
rest-api-v4

Daily Cron: ❌ Not scheduled
Options: ✔
Notes: 6
Onboarding: completed

### Action Scheduler ###

Complete: 20,152
Oldest: 2025-12-09 13:58:04 +0000
Newest: 2026-01-09 13:54:13 +0000

Failed: 22
Oldest: 2025-10-31 15:50:11 +0000
Newest: 2025-11-24 14:09:18 +0000

Pending: 15
Oldest: 2026-01-09 13:56:12 +0000
Newest: 2026-01-15 16:35:32 +0000


### Status report information ###

Generated at: 2026-01-09 13:55:14 +00:00
```

</details>

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](<https://woocommerce.com/products/storefront/>).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by anandrajaram21**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes #62750 

More details can be found in this particular comment in the issue https://github.com/woocommerce/woocommerce/issues/62750#issuecomment-3754317884

### Screenshots or screen recordings:

| Before | After |
| ------ | ----- |
| image | image |

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. On a WooCommerce site, create a two new products and set the both to "Out of Stock"
2. Go to WooCommerce > Analytics > Stock
3. Scroll to the bottom of the page and note the footer totals (e.g., "2 out of stock")
4. Go to Products page
5. Move the out of stock product to the trash
6. Return to WooCommerce > Analytics > Stock
7. Refresh the page

### Milestone

- [x] Automatically assign milestone for the **[next WooCommerce version](../blob/trunk/plugins/woocommerce/woocommerce.php#L6)**

> **Note:** Check the box above to have the milestone automatically assigned when merged.
> Alternatively (e.g. for point releases), manually assign the appropriate milestone.

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

Fixes a bug with analytics stock totals that included trashed products

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

**Comment by anandrajaram21** [comment]
@jamesckemp Hey, here's the followup PR for #62750. Thanks!

File: plugins/woocommerce/src/Admin/ReportsSync.php [hunk 1]
```diff
@@ -27,6 +27,9 @@ public static function init() {
 		add_action( 'woocommerce_new_product', array( __CLASS__, 'clear_stock_count_cache' ) );
 		add_action( 'update_option_woocommerce_notify_low_stock_amount', array( __CLASS__, 'clear_stock_count_cache' ) );
 		add_action( 'update_option_woocommerce_notify_no_stock_amount', array( __CLASS__, 'clear_stock_count_cache' ) );
+		add_action( 'trashed_post', array( __CLASS__, 'clear_stock_count_cache' ) );
+		add_action( 'untrashed_post', array( __CLASS__, 'clear_stock_count_cache' ) );
+		add_action( 'delete_post', array( __CLASS__, 'clear_stock_count_cache' ) );
```
Comment (Aljullu) [inline plugins/woocommerce/src/Admin/ReportsSync.php]: What do you think about creating a specific method for these actions that checks whether the post being trashed/deleted is a `product` or `product_variation` (similar to what's done [here](https://github.com/woocommerce/woocommerce/blob/2674fc7800d778edcb6167c8967e5cb858f4da4f/plugins/woocommerce/src/Internal/Caches/ProductVersionStringInvalidator.php#L228-L234))? Then, if it's not a product, we don't need to call `clear_stock_count_cache` unnecessarily, which would be good for performance.

I would also add `@internal` to the method doc block to make sure it's not used by 3rd-parties.

**Review by Aljullu — COMMENTED** [review]
Thanks for working on this, @anandrajaram21! Overall the fix looks good, but I left one minor performance suggestion. Let me know how it sounds!

File: plugins/woocommerce/src/Admin/ReportsSync.php (hunk 1 above)
Comment (anandrajaram21) [reply plugins/woocommerce/src/Admin/ReportsSync.php]: Oh yeah, that makes sense. I'll add this as well to the changes

**Review by Aljullu — APPROVED** [review]
Thanks for the update, @anandrajaram21! This is testing as described, and code changes look good to me, good job!

Before | After
--- | ---
Image | Image

I will go ahead and merge it, it will ship in WooCommerce 10.6. 🙌
