### PR TITLE
Fix: Add multiple variable products with "Any" in attributes

### LINKED ISSUE #63527: Add to Cart + Options: can't add two different variations if they have an attribute set as 'any'
Since WooCommerce 10.6, it's not possible to add two consecutive variations of the same product if they have an attribute defined as 'any'.

## Steps to reproduce

1. Create a variable product making sure at least two of the variations have one of the attributes set to 'any'. (Alternatively, use the `V-Neck T-Shirt` product from the sample data)
2. In the frontend, using the blockified *Add to Cart + Options* block, try adding those two variations to cart.
3. Notice after you added the first one, there is a JS error in the console.

https://github.com/user-attachments/assets/4f755c6b-4bef-4c99-96bc-389f7abfa6b5

## Investigation

The error happens in [doesCartItemMatchAttributes()](<https://github.com/woocommerce/woocommerce/blob/f491da4e2ebfb5c5e065ba3c3832c323bdaf3431/plugins/woocommerce/client/blocks/assets/js/base/utils/variations/does-cart-item-match-attributes.ts#L40>). `raw_attribute` doesn't exist when the cart item has been [added optimistically](<https://github.com/woocommerce/woocommerce/blob/f491da4e2ebfb5c5e065ba3c3832c323bdaf3431/plugins/woocommerce/client/blocks/assets/js/base/stores/woocommerce/cart.ts#L449-L453>).

I believe this issue has been there for a long time, but since [https://github.com/woocommerce/woocommerce/pull/62880](<https://github.com/woocommerce/woocommerce/pull/62880>) it's more visible because it causes a JS error.

One quick workaround would be to update `doesCartItemMatchAttributes()` to fall back to using `attribute` when `raw_attribute` is undefined.

### PR DESCRIPTION
**Pull request by SantosGuillamot**
### Changes proposed in this Pull Request:

Closes #63527 .

This PR fixes a bug where users cannot add two different variations of the same product to the cart when a variation attribute is set to "any". What this PR includes:
  - Updated `doesCartItemMatchAttributes()` to fall back to `attribute` when `raw_attribute` is unavailable (`raw_attribute ?? attribute`), so attribute matching works for both server-confirmed and optimistic cart items. Ideally, they should have the same format, but it can be done in a follow-up PR.
  - Created a centralized `itemInCart` state helper in the `woocommerce` store to consolidate duplicated cart item lookup logic.
  - Removed the duplicate copy of `doesCartItemMatchAttributes` that lived in `cart.ts` and now imports the shared utility instead. We should move that into a module in a follow-up PR.
  - Simplified the product button quantity getter and mini-cart item lookup to use the new `itemInCart` helper.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://developer.woocommerce.com/docs/contribution/testing/writing-high-quality-testing-instructions/), include your detailed testing instructions:

1. Create a variable product making sure at least two of the variations have one of the attributes set to 'any'. (Alternatively, use the V-Neck T-Shirt product from the sample data)
2. In the frontend, using the blockified Add to Cart + Options block, try adding those two variations to cart.
3. Notice after you added the first one, there is no JS error in the console.

### Milestone

- [ ] Automatically assign milestone for the **[next WooCommerce version](../blob/trunk/plugins/woocommerce/woocommerce.php#L6)**

> **Note:** Check the box above to have the milestone automatically assigned when merged.
> Alternatively (e.g. for point releases), manually assign the appropriate milestone.

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Fix adding multiple variable products with "any" attributes</summary>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment Fix adding multiple variable products with "any" attributes

</details>

### CODE REVIEW

**Comment by SantosGuillamot** [comment]
I think this should be ready for review. I want to note that I'd like to work on some follow-up PRs:

### 1. Remove `doesCartItemMatchAttributes` and move `attribute-matching` to a module?

The copy of that function that was previously in the `cart.ts` file was failing, so I used the one exported in `utils`. However, it is now used only once, so maybe it makes sense to remove it. Additionally, it relies on `attribute-matching`, so I want to review it and potentially move `attribute-matching` into a module?

### 2. Unified `variation`/`selectedAttributes` format

Right now, I find it a bit confusing that in some places it uses `raw_attribute` and in others `attribute` for the same purpose. I believe it makes sense to unify those.

### 3. Make the product button agnostic from "Add to Cart with Options"

In the product button `frontend.ts` store, there are some references to the Add to Cart with Options. However, the button block can be used outside of the Add to Cart with Options. I believe that once the product context is refactored ([PR1](https://github.com/woocommerce/woocommerce/pull/63208) & [PR2](https://github.com/woocommerce/woocommerce/pull/63210)), it should rely on that context instead.

**Review by Aljullu — APPROVED** [review]
Thanks for looking into this! Confirming the issue is fixed and code changes look good. I also agree with the next steps you highlighted, @SantosGuillamot!

I think CodeRabbit's comment is a valid one, but it doesn't seem to be specific to this PR and it's present in `trunk`, so it shouldn't be a blocker IMO.

https://github.com/user-attachments/assets/1b8e8caa-0c38-47f0-a14d-aa553c776bc1

**Comment by SantosGuillamot** [comment]
Thanks for the review! I've implemented the suggestion in this commit: https://github.com/woocommerce/woocommerce/pull/63535/commits/09f1b131a759a7b8e76c973a193ec205e00f8c3d

File: plugins/woocommerce/client/blocks/assets/js/base/stores/woocommerce/cart.ts [hunk 1]
```diff
@@ -318,6 +290,35 @@ async function sendCartRequest(
...
+							cartItem.variation.length !== variation.length
+						) {
+							return false;
+						}
+						return doesCartItemMatchAttributes(
+							cartItem,
+							variation
+						);
+					}
+					return key ? key === cartItem.key : id === cartItem.id;
```
[the remark this answers is not in the document]
Comment (SantosGuillamot) [reply plugins/woocommerce/client/blocks/assets/js/base/stores/woocommerce/cart.ts]: I've implemented the suggestion in this commit: https://github.com/woocommerce/woocommerce/commit/09f1b131a759a7b8e76c973a193ec205e00f8c3d

File: plugins/woocommerce/client/blocks/assets/js/base/stores/woocommerce/cart.ts [hunk 2]
```diff
@@ -318,6 +290,38 @@ async function sendCartRequest(
 const { state, actions } = store< Store >(
 	'woocommerce',
 	{
+		state: {
+			itemInCart( {
```
Comment (luisherranz) [inline plugins/woocommerce/client/blocks/assets/js/base/stores/woocommerce/cart.ts]: `state.itemInCart` is not very explicit for what it does. At first, I imagined it would be `state.isItemInCart`, but it's more like `state.findItemInCart`.

File: plugins/woocommerce/client/blocks/assets/js/atomic/blocks/product-elements/button/frontend.ts [hunk 3]
```diff
@@ -63,32 +65,16 @@ const { state: productDataState } = store< ProductDataStore >(
...
-			}
-
-			// Return the product quantity when the item is a non-variable product.
-			if ( products[ 0 ]?.type !== 'variation' ) {
-				return products.reduce(
-					( acc, item ) => acc + item.quantity,
-					0
-				);
-			}
+			const product = wooState.itemInCart( {
```
Comment (luisherranz) [inline plugins/woocommerce/client/blocks/assets/js/atomic/blocks/product-elements/button/frontend.ts]: `product` -> `item`? (not sure it makes sense)

**Review by luisherranz — APPROVED** [review]
LGTM, and the follow-ups look good to me as well.

Just a small suggestion: `state.findItemInCart()`?

File: plugins/woocommerce/client/blocks/assets/js/base/stores/woocommerce/cart.ts (hunk 2 above)
Comment (SantosGuillamot) [reply plugins/woocommerce/client/blocks/assets/js/base/stores/woocommerce/cart.ts]: Changed in this commit: https://github.com/woocommerce/woocommerce/pull/63535/commits/3815a306f83bcf8f3dceddf32566f69c24e51d3b

File: plugins/woocommerce/client/blocks/assets/js/atomic/blocks/product-elements/button/frontend.ts (hunk 3 above)
Comment (SantosGuillamot) [reply plugins/woocommerce/client/blocks/assets/js/atomic/blocks/product-elements/button/frontend.ts]: Changed in this commit: https://github.com/woocommerce/woocommerce/pull/63535/commits/3815a306f83bcf8f3dceddf32566f69c24e51d3b
