### PR TITLE
Store API: Use the order data instead of cart data for validation in the checkout order endpoint.

### LINKED ISSUE #53032: `woocommerce_rest_invalid_address_country` on guest checkout order w/ no shipping needed
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

I noticed some inconsistencies with the Store API's "Checkout order API", more specifically in the validation done during [the "Process Order and Payment" endpoint](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/src/StoreApi/docs/checkout-order.md#process-order-and-payment).

When attempting to pay for an order that doesn't need shipping (e.g.: an order that only contains virtual products), validation on the customer's cart is performed instead, causing inconsistent behavior.

### Expected behavior

I would expect the validation on the shipping (and whether shipping is needed) to be performed on the order itself, instead of the customer's cart.

### Actual behavior

The `OrderController->validate_addresses( \WC_Order $order )` is currently performing the validation on the `needs_shipping` attribute from the customer's cart, instead of the order itself: https://github.com/woocommerce/woocommerce/blob/c051a5755c2a15d92c57d6444803afc71a4f6696/plugins/woocommerce/src/StoreApi/Utilities/OrderController.php#L294

Since this function is used both in pay-for-order and cart API flows, the behavior is inconsistent in the pay-for-order flow.

### Steps to reproduce

1. Onboard a new WooCommerce site
2. Ensure you have at least a virtual and a physical product, just one of each type
3. Go to WooCommerce > Settings > Payments, enable the "Cash on delivery" payment method (just so you have an available payment method - but you can also use the "Dummy gateway" plugin: https://github.com/woocommerce/woocommerce-gateway-dummy/releases/tag/1.10.0 )
4. Navigate to WooCommerce > Orders > Click the "Add order" button
  - Click on the pencil icon on the billing section, add a billing email (Store API requires a billing email)
  - Click on "Add item(s)" > "Add product(s)" > Add the virtual product to the order
  - Save the order by clicking "Update"
  - It should look about like this: 
Image

5. Take note of the "Customer payment page" link
6. As a customer, navigate to the Store, add the physical product to your cart
7. Navigate to the cart page, ensure the shipping is needed and shipping options are present
8. Open your browser's console to interact with the Store API. Use this call:
```js
// retrieve `orderId`, `orderKey` from the "Customer payment page" link, retrieve `billingEmail` from the order you created
const orderId = '46';
const orderKey = 'wc_order_R3ua0RyNTj883';
const billingEmail = 'cheese@toast.com';

// getting the order information from the API, just so that we can pass them again when placing the order
const order = await wp.apiFetch({
	method: 'GET',
	path: `/wc/store/v1/order/${orderId}?billing_email=${billingEmail}&key=${orderKey}`,
	parse: false,
});
const orderData = await order.json();
wp.apiFetch({
	method: 'POST',
	path: `/wc/store/v1/checkout/${orderId}`,
	headers: { Nonce: order.headers.get('Nonce') },
	data: {
		key: orderKey,
		billing_email: billingEmail,
		billing_address: orderData.billing_address,
		shipping_address: orderData.shipping_address,
		payment_method: 'cod',
	},
});
```
9. The Store API returns a `woocommerce_rest_invalid_address_country` error code with "Sorry, we do not ship orders to the provided country"
10. Remove the physical product from the cart
11. Try again the script from step 8
12. The order is processed

### WordPress Environment

<details><summary>System Status Report</summary>

```
### WordPress Environment ###

WordPress address (URL): [Redacted]
Site address (URL): [Redacted]
WC Version: 9.4.2
Legacy REST API Package Version: The Legacy REST API plugin is not installed on this site.
Action Scheduler Version: ✔ 3.8.2
Log Directory Writable: ✔
WP Version: 6.7
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 8.3.13
PHP Post Max Size: 2 GB
PHP Time Limit: 850
PHP Max Input Vars: 6144
cURL Version: 8.10.1
OpenSSL/3.0.14

SUHOSIN Installed: –
MySQL Version: 10.11.10-MariaDB-log
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

[REDACTED]

### Post Type Counts ###

attachment: 17
customize_changeset: 1
page: 9
post: 2
product: 13
revision: 3
shop_order_placehold: 4

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (4) ###

Akismet Anti-spam: Spam Protection: by Automattic - Anti-spam Team – 5.3.5
Jetpack: by Automattic – 14.1-a.3
WooCommerce Dummy Payments Gateway: by Woo – 1.10.0
WooCommerce: by Automattic – 9.4.2

### Inactive Plugins (0) ###


### Dropin Plugins () ###

advanced-cache.php: advanced-cache.php
object-cache.php: Memcached

### Must Use Plugins (1) ###

load.php: by  –

### Settings ###

Legacy API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 378 B

### WC Pages ###

Shop base: #5 - /shop/
Cart: #6 - /cart/ -  Contains the woocommerce/cart block
Checkout: #7 - /checkout/ -  Contains the woocommerce/checkout block
My account: #8 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 4.6.0
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
pattern-toolkit-full-composability
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
printful
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page
launch-your-store

Disabled Features: product-data-views
experimental-blocks
minified-js
product-pre-publish-modal
settings
async-product-editor-category-field
product-editor-template-system
blueprint
reactify-classic-payments-settings
use-wp-horizon

Daily Cron: ✔ Next scheduled: 2024-11-22 09:48:50 +00:00
Options: ✔
Notes: 56
Onboarding: completed

### Action Scheduler ###

Complete: 17
Oldest: 2024-11-21 09:48:55 +0000
Newest: 2024-11-21 10:19:57 +0000

Failed: 2
Oldest: 2024-11-21 09:52:15 +0000
Newest: 2024-11-21 09:54:11 +0000

Pending: 2
Oldest: 2024-11-22 09:48:55 +0000
Newest: 2024-11-22 09:56:34 +0000


### Status report information ###

Generated at: 2024-11-21 10:28:27 +00:00
```
</details>

### Isolating the problem

- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by danielmx-dev**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

As described in #53032, when making a request using the Store API's [Checkout Order Endpoint](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/src/StoreApi/docs/checkout-order.md), the address validation is currently using data from the Cart instead of using exclusively the order data.

Besides the reported issue, I found other instances of the Checkout Order endpoint using data from the cart for validations or manipulating the cart data, which is unnecessary given that this endpoint should operate exclusively on existing orders. The changes can be summarized as:

- Use the order data for address validation instead of using the cart data
- Skip the `validate_selected_shipping_methods` since the shipping packages will be empty, as we are not using the cart.
- If there are invalid coupons, remove them from the order instead of removing them from the cart.
- Avoid calling the `AbstractCartRoute::cart_updated` function, override with an empty function instead.

Closes #53032

### How to test the changes in this Pull Request:

1. Onboard a new WooCommerce site
2. Ensure you have at least a virtual and a physical product, just one of each type
3. Go to WooCommerce > Settings > Payments, enable the "Cash on delivery" payment method (just so you have an available payment method - but you can also use the "Dummy gateway" plugin: https://github.com/woocommerce/woocommerce-gateway-dummy/releases/tag/1.10.0 )
4. Navigate to WooCommerce > Orders > Click the "Add order" button
  - Click on the pencil icon on the billing section, add a billing email (Store API requires a billing email)
  - Click on "Add item(s)" > "Add product(s)" > Add the virtual product to the order
  - Save the order by clicking "Update"
  - It should look about like this: 
Image

5. Take note of the "Customer payment page" link
6. As a customer, navigate to the Store, add the physical product to your cart
7. Navigate to the cart page, ensure the shipping is needed and shipping options are present
8. Open your browser's console to interact with the Store API. Use this call:
```js
// retrieve `orderId`, `orderKey` from the "Customer payment page" link, retrieve `billingEmail` from the order you created
const orderId = '46';
const orderKey = 'wc_order_R3ua0RyNTj883';
const billingEmail = 'cheese@toast.com';

// getting the order information from the API, just so that we can pass them again when placing the order
const order = await wp.apiFetch({
	method: 'GET',
	path: `/wc/store/v1/order/${orderId}?billing_email=${billingEmail}&key=${orderKey}`,
	parse: false,
});
const orderData = await order.json();
wp.apiFetch({
	method: 'POST',
	path: `/wc/store/v1/checkout/${orderId}`,
	headers: { Nonce: order.headers.get('Nonce') },
	data: {
		key: orderKey,
		billing_email: billingEmail,
		billing_address: orderData.billing_address,
		shipping_address: orderData.shipping_address,
		payment_method: 'cod',
	},
});
```

**Before** 
The Store API returns a `woocommerce_rest_invalid_address_country` error code with "Sorry, we do not ship orders to the provided country"

**Now**
The order is processed

#### Test Coupons

Repeat the steps 1-7. Before running the command from step 8, perform the following steps.

- Create a coupon following these instructions: https://woocommerce.com/document/coupon-management/#adding-a-coupon Make sure to add an email restriction to the coupon so it matches the order's billing email.
- Apply the new coupon to the order
- After the coupon has been added, edit the coupon so it's restricted to a different email address.
- Run the command from Step 8 in the pay for order page.
- The Store API should return the following error: `woocommerce_rest_order_coupon_errors`
- If you refresh the order in WP Admin, the coupon should no be longer applied.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [x] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 
Store API: Use the order data instead of cart data for validation in checkout order requests. Avoid modifying the cart data.
</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce/src/StoreApi/Routes/V1/CheckoutOrder.php [hunk 1]
```diff
@@ -177,6 +177,14 @@ protected function get_route_post_response( \WP_REST_Request $request ) {
 		);
 	}
 
+	/**
+	 * Since this endpoint only operates on existing orders, we don't need to do updates based on
+	 * the cart data.
+	 *
+	 * @param \WP_REST_Request $request Request object.
+	 */
+	protected function cart_updated( \WP_REST_Request $request ) {}
```
Comment (danielmx-dev) [inline plugins/woocommerce/src/StoreApi/Routes/V1/CheckoutOrder.php:186]: Calling  the parent `cart_updated` method in theory shouldn't have any negative side effects since the method updates the cart using the data from the draft order, not the order currently being processed by Checkout Order, however, I think that adds unnecessary overhead, but please let me know what do you think.

File: plugins/woocommerce/src/StoreApi/Utilities/OrderController.php [hunk 2]
```diff
@@ -171,7 +171,26 @@ public function validate_order_before_payment( \WC_Order $order ) {
...
+	 *
+	 * @throws RouteException Exception if invalid data is detected.
+	 * @param \WC_Order $order Order object.
+	 */
+	public function validate_existing_order_before_payment( \WC_Order $order ) {
+		$needs_shipping = $order->needs_shipping();
+
+		$this->validate_coupons( $order, true );
+		$this->validate_email( $order );
+		$this->validate_addresses( $order, $needs_shipping );
```
Comment (danielmx-dev) [inline plugins/woocommerce/src/StoreApi/Utilities/OrderController.php:196]: As mentioned in the PR description, I'm skipping the `validate_selected_shipping_methods` method since `WC()->shipping()->get_packages()` returns an empty array when used with an existing order instead of a cart.

File: plugins/woocommerce/src/StoreApi/Utilities/OrderController.php [hunk 3]
```diff
@@ -289,10 +343,10 @@ protected function validate_email( \WC_Order $order ) {
 	 *
 	 * @throws RouteException Exception if invalid data is detected.
 	 * @param \WC_Order $order Order object.
+	 * @param bool      $needs_shipping Whether the order needs shipping.
 	 */
-	protected function validate_addresses( \WC_Order $order ) {
+	protected function validate_addresses( \WC_Order $order, bool $needs_shipping ) {
```
Comment (danielmx-dev) [inline plugins/woocommerce/src/StoreApi/Utilities/OrderController.php:366]: Since this is a protected method should this be classified as a breaking (major) change? Or is it fine to keep it as a minor change?

Comment (opr) [reply plugins/woocommerce/src/StoreApi/Utilities/OrderController.php:366]: As far as I know, we are the only consumers of `OrderController` I don't think it's public API. @senadir any idea of any use cases where someone else besides us would be accessing `OrderController` ?

File: plugins/woocommerce/src/StoreApi/Routes/V1/CheckoutOrder.php (hunk 1 above)
Comment (opr) [reply plugins/woocommerce/src/StoreApi/Routes/V1/CheckoutOrder.php:186]: When testing with the coupon and incorrect email, the _order_ is updated when the coupon is removed (https://github.com/woocommerce/woocommerce/pull/56645/files#diff-d9ab83839d5125c7c4155bfca1666c6c1c87b9ee1ed46c66f4426c96da681b3eR290) - so still no need to call the parent method 👌🏼 

Just noting that in case this scenario is spotted by another reviewer.

File: plugins/woocommerce/src/StoreApi/Utilities/OrderController.php (hunk 2 above)
Comment (opr) [reply plugins/woocommerce/src/StoreApi/Utilities/OrderController.php:196]: Makes sense, but do you want to validate the shipping methods on the order? In case they changed between the order being created and paid? Is it even possible to do that, from what I remember the shipping methods aren't saved as anything except string/price.

**Review by opr — COMMENTED** [review]
Thanks for this, I've tested the PR according to the instructions and reviewed the code. I added a couple of comments and left one question, for someone else on the team. 

The unit tests look good, thanks for adding them.

I did notice that when paying for an existing order, the current cart is also cleared. Is this something we are OK with?

I do appreciate it's an edge case, but did you look into whether it is possible to conserve the existing cart? It may not be, but I think it'd be great if we could just confirm that.

I also discussed the PR with Claude, and asked about the short circuiting of `cart_updated` which it thought was fine. I looked into this method and researched how and why it was called, and concluded that it's fine to skip it on the `CheckoutOrder` endpoint since the _cart_ won't update, only the order.

Claude flagged no major issues but did suggest explaining the difference between `validate_existing_order_before_payment` and the regular method. 

Skipping approving for now, as I have asked a couple of questions here.

File: plugins/woocommerce/src/StoreApi/Utilities/OrderController.php (hunk 2 above)
Comment (senadir) [reply plugins/woocommerce/src/StoreApi/Utilities/OrderController.php:196]: Yes after the order is placed there is no reference back to them, nothing to validate

File: plugins/woocommerce/src/StoreApi/Utilities/OrderController.php (hunk 3 above)
Comment (senadir) [reply plugins/woocommerce/src/StoreApi/Utilities/OrderController.php:366]: no I think this is fine

**Comment by frosso** [comment]
> I did notice that when paying for an existing order, the current cart is also cleared. Is this something we are OK with?
> I do appreciate it's an edge case, but did you look into whether it is possible to conserve the existing cart? It may not be, but I think it'd be great if we could just confirm that.

FWIW, I looked into it in the past, and it happens when the customer lands on the "Order received" page - something WooCommerce Core will do.

EDIT: I see that semi-recently, a `woocommerce_should_clear_cart_after_payment` filter was introduced, which I think would help in this case.

**Comment by senadir** [comment]
> FWIW, I looked into it in the past, and it happens when the customer lands on the "Order received" page - something WooCommerce Core will do.

Well that's bad, I think we can set a flag in the pay for order flow and not clear cart when you land on that page?

**Comment by danielmx-dev** [comment]
> > FWIW, I looked into it in the past, and it happens when the customer lands on the "Order received" page - something WooCommerce Core will do.
> 
> Well that's bad, I think we can set a flag in the pay for order flow and not clear cart when you land on that page?

`WC()->cart->empty_cart();` is also usually called by payment gateways inside the `process_payment` method.

This also affects the regular Pay For Order flow, so I think it should be addressed in a separate issue.

**Comment by senadir** [comment]
yes but most payment methods moved away from that, in Store API, we call the empty cart

**Comment by senadir** [comment]
>  I think it should be addressed in a separate issue.

I agree.

**Review by opr — APPROVED** [review]
Thanks, looks like the questions I had have been answered, and we need to create a follow up issue to prevent cart clearing on pay for order. Can you take care of this @danielmx-dev ?

**Comment by danielmx-dev** [comment]
I created this issue for the empty cart problem: https://github.com/woocommerce/woocommerce/issues/56772

**Review by mdmoore — APPROVED** [review]
This is testing well for me. The order processed as expected and the restricted coupon is removed from the order with the validation. I also noticed the cart was cleared when the order was processed, but I see you've already created an issue for that. Thanks Daniel!
