### PR TITLE
Make `Table` component accept `className` prop

### LINKED ISSUE #36129: `Table` component accepts `classNames` instead of `className` prop
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Setting `className` prop to the `Table` component does not set the `class` HTML attribute. Instead, the `Table` component accepts `classNames` prop and set it in `class` HTML attribute, which I believe is a mistake.

Related code is here:

https://github.com/woocommerce/woocommerce/blob/1e815be51625855c2f9dcefafb9f0f503a560a4c/packages/js/components/src/table/table.js#L143

### Expected behavior

The `Table` component should accept `className` prop and apply it in the final rendered HTML.

### Actual behavior

Setting `className` to `Table` component doesn't do anything.

### Steps to reproduce

1. Render a `Table` component like the following, with `className` set to `"class111"`:

```
<Table
	className="class111"
	caption="Revenue last week"
	rows={ rows }
	headers={ headers }
	rowKey={ row => row.display }
/>
```

2. Check the rendered HTML. Notice that there is no `class111`.
3. Change `className="class111"` to `classNames="class111"`.
4. Check the rendered HTML. Notice that there is `class111`.

### WordPress Environment

Not applicable.

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by ecgan**
### All Submissions:

-   [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
-   [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
-   [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes https://github.com/woocommerce/woocommerce/issues/36129.

This PR makes the `Table` component accept `className` props. 

The component will continue to work with the existing `classNames` prop for backward compatibility reason.

I added tests to cover both `className` and `classNames` props usage.

`classNames` prop is used in the `TablePlaceholder` component. I have changed it to `className`.

### How to test the changes in this Pull Request:

Component testing:

1. Run `pnpm --filter=@woocommerce/components run test`. All tests should pass.

### Other information:

-   [x] Have you added an explanation of what your changes do and why you'd like us to include them?
-   [x] Have you written new tests for your changes, as applicable?
-   [x] Have you created a changelog file for each project being changed, ie `pnpm --filter=<project> changelog add`?

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

File: packages/js/components/src/table/table.js [hunk 1]
```diff
@@ -148,10 +149,15 @@ class Table extends Component {
 			rows,
 		} = this.props;
 		const { isScrollableRight, isScrollableLeft, tabIndex } = this.state;
-		const classes = classnames( 'woocommerce-table__table', classNames, {
-			'is-scrollable-right': isScrollableRight,
-			'is-scrollable-left': isScrollableLeft,
-		} );
+		const classes = classnames(
+			'woocommerce-table__table',
+			classNames,
```
Comment (chihsuan) [inline packages/js/components/src/table/table.js:165]: Good catch! 😄  @ecgan  

I think we can log a message for `classNames` using [@wordpress/deprecated](https://www.npmjs.com/package/@wordpress/deprecated). What do you think?

File: packages/js/components/src/table/test/index.js [hunk 2]
```diff
@@ -172,3 +173,35 @@ describe( 'TableCard', () => {
 		);
 	} );
 } );
+
+describe( 'Table', () => {
```
Comment (chihsuan) [inline packages/js/components/src/table/test/index.js:177]: Thanks for adding the tests!

File: packages/js/components/src/table/table.js (hunk 1 above)
Comment (ecgan) [reply packages/js/components/src/table/table.js:165]: I was looking for a way to mark the `classNames` prop as deprecated (was looking for something like `@deprecated`), and TIL about [@wordpress/deprecated](https://www.npmjs.com/package/@wordpress/deprecated). 😄 

I made the change in [`42ca68e` (#36151)](https://github.com/woocommerce/woocommerce/pull/36151/commits/42ca68e1a53c217d76ac733cfbb9dddb173f7c6c). I use `since: '11.1.0'` (current version) and `version: '12.0.0'` (next major version), does that make sense? Do you know what is our process or strategy to remove the deprecated prop? 🤔 

With the code change, I can see this warning message in the browser console: "Table component's classNames prop is deprecated since version 11.1.0 and will be removed from @woocommerce/components in version 12.0.0. Please use className instead."

Comment (chihsuan) [reply packages/js/components/src/table/table.js:165]: > I made the change in [42ca68e (#36151)](https://github.com/woocommerce/woocommerce/pull/36151/commits/42ca68e1a53c217d76ac733cfbb9dddb173f7c6c). I use since: '11.1.0' (current version) and version: '12.0.0' (next major version), does that make sense? Do you know what is our process or strategy to remove the deprecated prop? 🤔

Yes, that makes sense. You can add an issue in our backlog to remove this deprecated prop in the future. 🙌 

> With the code change, I can see this warning message in the browser console: "Table component's classNames prop is deprecated since version 11.1.0 and will be removed from @woocommerce/components in version 12.0.0. Please use className instead."

Thanks! Looks good to me. 🙂

**Review by chihsuan — APPROVED** [review]
Thanks @ecgan LGTM and tested well. 👍

File: packages/js/components/src/table/table.js (hunk 1 above)
Comment (ecgan) [reply packages/js/components/src/table/table.js:165]: I have created issue https://github.com/woocommerce/woocommerce/issues/36184 to remove the deprecated prop in the future.
