### PR TITLE
Store API: If payment is not needed, clear order payment method field

### LINKED ISSUE #58090: $order has a saved payment method (the default payment method), although $order does not need payment
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

If an order is placed by a customer that does not need payment (free products, free shipping), the default payment method is saved as the payment method in the order. That only happens if the checkout block is used. The bug does not appear if the shortcode checkout is used. 

The bug occurs in all versions from version 9.8, including 9.9.0-beta-1, but not in previous versions (<=9.7.1)

This is impractical if the payment transactions are evaluated for statistics.

### Expected behavior

The saved payment method in the order should be "N/A"

Image

### Actual behavior

The default payment method is saved in the order:

Image

### Steps to reproduce

1. Set your payment methods so that only check payment is activated
2. Use WC 9.8 or a newer version
3. Use the checkout block
4. Create a free product and a free shipping method
5. Buy this product with the free shipping method in the frontend
6. Check the payment method of the order in the backend

### WordPress Environment

<details><summary>System Status Report</summary>

```
### WordPress Environment ###

WordPress address (URL): [Redacted]
Site address (URL): [Redacted]
WC Version: 9.9.0-beta.1
Legacy REST API Package Version: The Legacy REST API plugin is not installed on this site.
Action Scheduler Version: ✔ 3.9.2
Log Directory Writable: ✔
WP Version: 6.8.1
WP Multisite: –
WP Memory Limit: 5 GB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: Apache
Server Architecture: Linux 6.1.0-34-amd64 x86_64
PHP Version: 8.3.21
PHP Post Max Size: 200 MB
PHP Time Limit: 1000
PHP Max Input Vars: 1000
cURL Version: 7.88.1
OpenSSL/3.0.15

SUHOSIN Installed: –
MySQL Version: 10.11.11-MariaDB-hz2
Max Upload Size: 200 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

[REDACTED]

### Post Type Counts ###

attachment: 111
custom_css: 7
customer_groups: 6
customize_changeset: 3
document_template: 7
nav_menu_item: 5
option-tree: 1
page: 29
post: 18
product: 20
product_variation: 516
revision: 424
shop_coupon: 201
shop_order: 388
shop_order_refund: 88
shop_subscription: 6
wp_global_styles: 9
wp_navigation: 1
wp_template: 5

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (5) ###

Performant Translations: by WordPress Performance Team – 1.2.0
Plugin Check (PCP): by WordPress Performance Team and Plugin Review Team – 1.5.0
WooCommerce Beta Tester: by WooCommerce – 2.5.1
WooCommerce: by Automattic – 9.9.0-beta.1
WordPress Beta Tester: by WordPress Upgrade/Install Team – 3.6.3

### Settings ###

Legacy API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: bundle (bundle)
composite (composite)
external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: –
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: ✔
Enabled Features: analytics
marketplace
order_attribution
site_visibility_badge
reactify-classic-payments-settings
custom_order_tables


### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 975 KB

### WC Pages ###

Shop base: #7446 - /shop/
Checkout: #20001677 - /checkout/ -  Contains the woocommerce/checkout block
My account: #7449 - /mein-konto/ -  Contains the [woocommerce_my_account] shortcode
Terms and conditions: #20000222 - /toc/

### Theme ###

Name: Twenty Twenty-One
Version: 2.5
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
Theme type: Classic theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
onboarding
onboarding-tasks
pattern-toolkit-full-composability
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
printful
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page
launch-your-store
add-to-cart-with-options-stepper-layout
disable-core-profiler-fallback
reactify-classic-payments-settings

Disabled Features: product-data-views
experimental-blocks
coming-soon-newsletter-template
minified-js
point-of-sale
product-pre-publish-modal
settings
async-product-editor-category-field
product-editor-template-system
use-wp-horizon
blockified-add-to-cart
beta-tester-slotfill-examples

Daily Cron: ✔ Next scheduled: 2025-05-17 17:49:19 +02:00
Options: ✔
Notes: 8
Onboarding: completed

### Action Scheduler ###

Complete: 607
Oldest: 2025-04-16 12:04:46 +0200
Newest: 2025-05-17 10:57:29 +0200

Failed: 117
Oldest: 2023-07-05 11:34:17 +0200
Newest: 2025-05-16 08:44:56 +0200

Pending: 4
Oldest: 2025-05-18 10:19:19 +0200
Newest: 2026-12-31 23:59:59 +0100


### Status report information ###

Generated at: 2025-05-17 11:02:59 +02:00
```
</details>

### Isolating the problem

- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by mikejolley**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

The default payment method is saved to draft orders. If the API is called with a blank payment method, clear it if payment is not required.

Closes #58090

(For Bug Fixes) Bug introduced in PR https://github.com/woocommerce/woocommerce/pull/53553

### How to test the changes in this Pull Request:

1. Add a paid item to cart. Proceed to checkout. Place order.
2. View order in admin backend. Ensure it says "Paid via X", replacing X with the chosen payment method.
3. Add a free item to cart. Proceed to checkout. Place order.
4. View order in admin backend. The "Paid via X" message is not present. Payment method field says NA.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

**Comment by mikejolley** [comment]
There are some CI issues Ill look into.

File: plugins/woocommerce/src/StoreApi/Schemas/V1/CheckoutSchema.php [hunk 1]
```diff
@@ -149,7 +149,7 @@ public function get_properties() {
 				'context'     => [ 'view', 'edit' ],
 				// Validation may be based on cart contents which is not available here; this returns all enabled
 				// gateways. Further validation occurs during the request.
-				'enum'        => array_values( WC()->payment_gateways->get_payment_gateway_ids() ),
+				'enum'        => array_merge( [ '' ], array_values( WC()->payment_gateways->get_payment_gateway_ids() ) ),
```
Comment (senadir) [inline plugins/woocommerce/src/StoreApi/Schemas/V1/CheckoutSchema.php:152]: So what? we never accepted an empty payment? or we just didn't send `payment_method`?

**Review by senadir — APPROVED** [review]
Works as expected, it still shows "Paid on date" which is confusing, but maybe not part of this PR.

File: plugins/woocommerce/src/StoreApi/Schemas/V1/CheckoutSchema.php (hunk 1 above)
Comment (mikejolley) [reply plugins/woocommerce/src/StoreApi/Schemas/V1/CheckoutSchema.php:152]: It required a value if sent with the request. You could leave it out because it wasn't required.

Comment (mikejolley) [reply plugins/woocommerce/src/StoreApi/Schemas/V1/CheckoutSchema.php:152]: Double checked. Prior to this leaving it blank would give an enum error unless you used a named payment method. Now, if you leave it blank but payment is required you see a `woocommerce_rest_checkout_missing_payment_method` error unless payment is not needed, so I think its working as intended.
