### PR TITLE
Fix progress header title

### LINKED ISSUE #32720: [GlobalStep] Unable to display "Welcome to <site name>" above the progress header task list on "Woocommerce > Home" page.
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Unable to display "Welcome to <site name>" above the progress header task list on "Woocommerce > Home" page.

### Expected behavior

"Welcome to <site name>" should be displayed above the progress header task list on "Woocommerce > Home" page.

### Actual behavior

Unable to display "Welcome to <site name>" above the progress header task list on "Woocommerce > Home" page.

### Steps to reproduce

1. Create any test site using JN site.
2. Install and activate WooCommerce 6.5.0-beta.1.
3. Install and activate the latest WooCommerce Test Helper plugin
4. Navigate to Tools > WCA Test Helper > Experiments and toggle woocommerce_tasklist_setup_experiment_2_2022_* to treatment.
5. Go to WooCommerce > Home.
6. Observe that "Welcome to <site name>" is not displayed above the progress header task list on "Woocommerce > Home" page.

### Screenshot:
welcome

### WordPress Environment

PC:
Windows 10
Chrome(Version 100.0.4896.127) 
Firefox(Version 99.0.1)

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

<details>

`
### WordPress Environment ###

WC Version: 6.5.0
REST API Version: ✔ 6.5.0
WC Blocks Version: ✔ 7.4.1
Action Scheduler Version: ✔ 3.4.0
Log Directory Writable: ✔
WP Version: 5.9.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.53 (Unix) OpenSSL/1.0.2g
PHP Version: 7.4.28
PHP Post Max Size: 1 GB
PHP Time Limit: 30
PHP Max Input Vars: 5000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.7.33-0ubuntu0.16.04.1-log
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 6.5.0
WC Database Prefix: wp_
Total Database Size: 4.79MB
Database Data Size: 3.32MB
Database Index Size: 1.47MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 2.42MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_posts: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 1
page: 7
post: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (5) ###

Query Monitor: by John Blackbourn – 3.9.0
Companion Plugin: by Osk – 1.24
WooCommerce Admin Test Helper: by WooCommerce – 0.7.1
WooCommerce Beta Tester: by WooCommerce – 2.0.5
WooCommerce: by Automattic – 6.5.0-beta.1

### Inactive Plugins (3) ###

Akismet Anti-Spam: by Automattic – 4.2.2
Hello Dolly: by Matt Mullenweg – 1.7.2
Jetpack: by Automattic – 10.8

### Dropin Plugins (1) ###

db.php: Query Monitor Database Class (Drop-in)

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: –

### WC Pages ###

Shop base: #6 - /shop/
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 4.1.0
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 2
Oldest: 2022-04-21 07:18:09 +0000
Newest: 2022-04-21 07:25:03 +0000

### Status report information ###

Generated at: 2022-04-21 15:02:08 +00:00
`

</details>

### PR DESCRIPTION
**Pull request by octaedro**
### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

This PR fixes the progress header title behavior.

The progress header title `Welcome to <store_name>` will be visible only when any of these conditions is true:
- The user doesn't have any completed tasks
- After completing every task
- The user completed only the OBW

(more details [here](https://github.com/woocommerce/woocommerce/issues/32163#issuecomment-1109848748))

If we don't know the store's name, it will say `Welcome to your store` (more details [here](https://github.com/woocommerce/woocommerce/issues/32163#issuecomment-1108657903)).

Closes #32720.

### How to test the changes in this Pull Request:

1. Start with a fresh install
2. Install and activate the latest [WooCommerce Test Helper plugin](https://github.com/woocommerce/woocommerce-admin-test-helper/releases/tag/v0.7.1)
3. Navigate to **Tools > WCA Test Helper > Experiments** and toggle `woocommerce_tasklist_setup_experiment_2_2022_*` to treatment.
4. Navigate to **WooCommerce > Home**, start the onboarding wizard, and press skip.
5. The progress header should show up with a `Welcome to <site name>` above the task list.
6. Now start and finish the OBW.
7. The progress header should stay the same,
8. Finish another task.
9. Now the progress header should say `Let's get you started :rocket:`.
10. Finish all the tasks.
11. Now the progress header should show: `Welcome to <site name>`.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?
* [x] Have you created a changelog file by running `pnpm nx affected --target=changelog`?

### FOR PR REVIEWER ONLY:

* [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

File: plugins/woocommerce-admin/client/task-lists/progress-header/progress-header.tsx [hunk 1]
```diff
@@ -38,25 +37,23 @@ export const ProgressHeader: React.FC< ProgressHeaderProps > = ( {
...
 	} );
 
 	const progressTitle = useMemo( () => {
 		if (
-			( ! hasVisitedTasks &&
-				completedCount < 2 + disabledCompletedCount ) ||
-			completedCount === tasksCount
+			completedCount === 0 ||
+			completedCount === tasksCount ||
+			( hasFinishedStoreDetails && completedCount === 1 )
```
Comment (louwie17) [inline plugins/woocommerce-admin/client/task-lists/progress-header/progress-header.tsx]: This logic doesn't seem to work for me. It always shows `Let's get you started` now at the beginning. Because either the finishedStoreDetails is false and completedCount === 1 or finishedStoreDetails is true and completedCount === 2. Neither of these work for the above condition.

As a simpler fix, could we just filter out the `store_details` task from the previous `hasVisitedTasks` logic?

File: plugins/woocommerce-admin/client/task-lists/progress-header/progress-header.tsx [hunk 2]
```diff
@@ -65,7 +62,7 @@ export const ProgressHeader: React.FC< ProgressHeaderProps > = ( {
 						__( 'Welcome to %s', 'woocommerce' ),
 						siteTitle
 				  )
-				: __( 'Welcome', 'woocommerce' );
+				: __( 'Welcome to your store', 'woocommerce' );
```
Comment (louwie17) [inline plugins/woocommerce-admin/client/task-lists/progress-header/progress-header.tsx:57]: Nice!

**Review by louwie17 — CHANGES_REQUESTED** [review]
@octaedro I tried to follow the testing instructions, but I always get `Let's get you started 🚀` for the first several steps and I don't see `Welcome to <store name>` anymore, only at the end once I completed all the tasks.
I left a comment inline as well.

File: plugins/woocommerce-admin/client/task-lists/progress-header/progress-header.tsx (hunk 1 above)
Comment (octaedro) [reply plugins/woocommerce-admin/client/task-lists/progress-header/progress-header.tsx]: Yes, this is pretty confusing. Sorry for not having been more explicit in my instructions.
The title `Welcome to <store name>` won't be visible if [any task (other than the Store Details) has been finished](https://github.com/woocommerce/woocommerce/issues/32163#issuecomment-1109914307).
If `completedCount` is 1 but the Store Details task is incomplete, the title shouldn't be visible and we will see `Let's get you started 🚀` instead. Same if there is more than one task completed.

On the other hand, although the functionality is almost the same, the change you mentioned makes the code easier to read so I added it.

**Comment by octaedro** [comment]
Thank you @louwie17 for the review. I addressed the change you suggested. Could you take another look at this PR?

**Review by louwie17 — COMMENTED** [review]
@octaedro thanks for the changes, this test great now for the task list experiment 1, but not for task experiment 2, which I will take the blame for, as it looks like a bug that I caused. It doesn't update the `visitedTasks` logic in the sectioned task list.

Would you potentially be able to add that logic as part of this PR, we did need to add most of these lines (with the update in the `trackClick` function) https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce-admin/client/tasks/task-list-item.tsx#L108-L130
To this component: https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce-admin/client/two-column-tasks/task-list-item.tsx#L41

**Comment by octaedro** [comment]
@louwie17 I added the fix you suggested in the commit 23c829e
I think that this PR is ready for another review 🙂

**Review by louwie17 — APPROVED** [review]
Thanks for sticking with my suggested changes @octaedro, this tested great and changes look good! Thanks for fixing this 🚀
