### PR TITLE
Prevent unnecessary admin feature class loading and initialization on frontend

### LINKED ISSUE #38308: Why is anything WooCommerce Admin loaded front-end?
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

While developing an autoloader I noticed a lot of WooCommerce Admin classes mentioned front-end.
It's not classes that's getting loaded, but I wonder why they are there at all, in the end there is logic front end that I would think is exclusively for admin. Examples:

```
Automattic\WooCommerce\Admin\Features\Navigation
Automattic\WooCommerce\Admin\Features\ImportProductsTask
Automattic\WooCommerce\Admin\Features\ImportProductsTask\Init
Automattic\WooCommerce\Admin\Features\ExperimentalFashionSampleProducts
Automattic\WooCommerce\Admin\Features\ExperimentalFashionSampleProducts\Init
Automattic\WooCommerce\Admin\Features\ShippingSmartDefaults
Automattic\WooCommerce\Admin\Features\ShippingSmartDefaults\Init
Automattic\WooCommerce\Admin\Features\ShippingSettingTour
Automattic\WooCommerce\Admin\Features\ShippingSettingTour\Init
Automattic\WooCommerce\Admin\Features\OnboardingTasks
Automattic\WooCommerce\Admin\Features\RemoteFreeExtensions
Automattic\WooCommerce\Admin\Features\PaymentGatewaySuggestions
Automattic\WooCommerce\Admin\Features\Subscriptions
Automattic\WooCommerce\Admin\Features\Subscriptions\Init
Automattic\WooCommerce\Admin\Features\StoreAlerts
Automattic\WooCommerce\Admin\Features\StoreAlerts\Init
Automattic\WooCommerce\Admin\Features\WooMobileWelcome
Automattic\WooCommerce\Admin\Features\WooMobileWelcome\Init
Automattic\WooCommerce\Admin\Features\WcPayPromotion
```

I would think wrapping this in some admin check would be a good practise?
https://github.com/woocommerce/woocommerce/blob/06006619b36840e4cacaa8d7f47ef328725f2926/plugins/woocommerce/src/Packages.php#L64

### Expected behavior

Avoid parsing admin only code front-end

### Actual behavior

Unknown consequences performance wise, but there is a lot of checks for WooCommerce Admin features and if they are enabled or not.

### Steps to reproduce

Check the code linked in issue. Follow the init() function and especially look at the `$feature_plugin_instance = FeaturePlugin::instance();` 

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): http://project-boiler.local
Site address (URL): http://project-boiler.local
WC Version: 7.7.0
REST API Version: ✔ 7.7.0
WC Blocks Version: ✔ 10.0.4
Action Scheduler Version: ✔ 3.5.4
Log Directory Writable: ✔
WP Version: 6.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.16.0
PHP Version: 8.1.9
PHP Post Max Size: 1,000 MB
PHP Time Limit: 1200
PHP Max Input Vars: 4000
cURL Version: 7.84.0
(SecureTransport) OpenSSL/1.1.1q

SUHOSIN Installed: –
MySQL Version: 8.0.16
Max Upload Size: 300 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.7.0
WC Database Prefix: wp_
Total Database Size: 6.53MB
Database Data Size: 4.88MB
Database Index Size: 1.65MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_gla_attribute_mapping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gla_budget_recommendations: Data: 0.22MB + Index: 0.14MB + Engine InnoDB
wp_gla_merchant_issues: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gla_shipping_rates: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gla_shipping_times: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 3.52MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.08MB + Index: 0.03MB + Engine InnoDB
wp_posts: Data: 0.05MB + Index: 0.06MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 20
page: 8
post: 3
product: 9
revision: 1
wp_global_styles: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 7.7.0

### Inactive Plugins (1) ###

Project Name Customizations: by Maksimer – 1.0.0

### Settings ###

API Enabled: –
Force SSL: –
Currency: NOK (kr)
Currency Position: left_space
Thousand Separator: 
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### WC Pages ###

Shop base: #6 - /shop/
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty-Three
Version: 1.1
Author URL: https://wordpress.org
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: product-block-editor
minified-js
new-product-management-experience
product-variation-management
settings

Daily Cron: ✔ Next scheduled: 2023-05-16 16:57:39 +00:00
Options: ✔
Notes: 66
Onboarding: completed

### Action Scheduler ###

Complete: 18
Oldest: 2023-05-15 16:57:40 +0000
Newest: 2023-05-15 17:16:13 +0000

Pending: 2
Oldest: 2023-05-15 22:04:13 +0000
Newest: 2023-05-16 16:57:40 +0000

Failed: 1
Oldest: 2023-05-15 17:00:41 +0000
Newest: 2023-05-15 17:00:41 +0000

### Status report information ###

Generated at: 2023-05-15 22:03:15 +00:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by chihsuan**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes https://github.com/woocommerce/woocommerce/issues/38308

This PR optimizes how WooCommerce admin features are loaded by preventing unnecessary initialization on frontend requests.

- Prevents unnecessary class autoloading on frontend requests
- Maintains full functionality for admin, AJAX, cron, CLI, and REST API context, except for store API requests. I checked the code, and from my understanding, store API requests are designed for frontend usage and don't need to load admin features. Please correct me if I'm wrong.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Create a fresh site with `wc-smooth-generator` plugin installed and activated.
2. Complete the core profiler
3. Confirm the coming soon footer banner is shown when the site is coming soon for admin users
4. Test around the admin pages and confirm no errors
5. Go to WooCommerce Admin Test Helper (Tools > WCA Test Helper) > Tools
6. Run `wc_admin_daily` and confirm it runs successfully
7. Go to WooCommerce Admin Test Helper >  `Features` and confirm you can toggle the features
8. Go to Tools > Smooth Generator > Generate Products and confirm no errors
9. Add the following code to `Features.php` before [line 56](https://github.com/woocommerce/woocommerce/blob/eb4cfbcc4e5b10780d72bd7097e67b40c9d37afa/plugins/woocommerce/src/Admin/Features/Features.php#L55):

```php
spl_autoload_register(
	function( $classname ) {
		error_log( print_r( $classname, true ) );
	}
);
```

10. Add `define( 'DISABLE_WP_CRON', true );` to `wp-config.php` to prevent wp-cron from loading admin features by itself
11. Go to frontend in incognito mode and confirm no errors
12. Confirm `wp-content/debug.log` doesn't log any `Automattic\WooCommerce\Admin\Features\` classes

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

**Review by psealock — APPROVED** [review]
Code is looking good and testing well 🚢

**Review by rjchow — APPROVED** [review]
Tested well for me, but I think the scope is big enough that we should consider asking for additional reviews or feedback from another team that works with the frontend. Maybe proton?

**Comment by chihsuan** [comment]
> Tested well for me, but I think the scope is big enough that we should consider asking for additional reviews or feedback from another team that works with the frontend. Maybe proton?

Sounds good! cc @woocommerce/proton  if you have any feedback on this PR, it would be much appreciated. 🙏

File: plugins/woocommerce/src/Admin/Features/Features.php [hunk 1]
```diff
@@ -358,4 +370,26 @@ private function register_internal_class_aliases() {
...
 	}
+
+	/**
+	 * Check if we're in an admin context where features should be loaded.
+	 *
+	 * @return boolean
+	 */
+	private static function should_load_features() {
+		if ( class_exists( 'WC_Unit_Tests_Bootstrap' ) ) {
+			// Always load features in unit tests.
```
Comment (Konamiman) [inline plugins/woocommerce/src/Admin/Features/Features.php]: I don't like the idea of production code actively checking for a unit testing context... is this really needed? If there are tests that get broken when admin features aren't loaded, maybe these tests should be adjusted instead.

Alternatively, the `is_admin()` check below could be replaced with `wc_get_container()->get(LegacyProxy::class)->call_function('is_admin')`, and then the function can be mocked to always return true in the tests where that's needed.

File: plugins/woocommerce/src/Admin/Features/Features.php [hunk 2]
```diff
@@ -358,4 +370,26 @@ private function register_internal_class_aliases() {
 			class_alias( $new_class, $orig_class );
 		}
 	}
+
+	/**
+	 * Check if we're in an admin context where features should be loaded.
+	 *
+	 * @return boolean
+	 */
+	private static function should_load_features() {
```
Comment (Konamiman) [inline plugins/woocommerce/src/Admin/Features/Features.php:379]: Random idea (not a blocker): might it be worth wrapping the return value of this method in a `woocommerce_load_admin_features` filter? Is there any scenario in which an extension might need these to be loaded even when not in an admin context?

File: plugins/woocommerce/src/Admin/Features/Features.php (hunk 1 above)
Comment (chihsuan) [reply plugins/woocommerce/src/Admin/Features/Features.php]: Thanks for the feedback! @Konamiman 🙏  The reason for the check is that some tests like `Payment_Gateways_V2`, which test the REST API endpoints, require loading admin features to return the correct data. We could potentially adjust these tests, but it might change their expected behavior and make them less useful, so I didn't want to go down that route.

> Alternatively, the is_admin() check below could be replaced with wc_get_container()->get(LegacyProxy::class)->call_function('is_admin'), and then the function can be mocked to always return true in the tests where that's needed.

I gave it a try, but unfortunately it didn't work well. The admin features are loaded in the `init` hook, which is loaded when [loading the WP testing environment](https://github.com/woocommerce/woocommerce/blob/331dee997b6d64741ea135319b6777839ea231c8/plugins/woocommerce/tests/legacy/bootstrap.php#L80-L81), so we need to mock `is_admin` before the environment is initialized. However, I think that would affect all tests, not just those needing admin features.

Comment (chihsuan) [reply plugins/woocommerce/src/Admin/Features/Features.php]: As your comment suggests below, I think the best approach is to add a filter. It allows the extension to load admin features in different contexts if needed and also allows us to force load admin features in the testing environment. I added a filter and hooked it into `tests/legacy/bootstrap.php` to load admin features in the testing environment.  facbfbebc6ea0a0c6c7a8c49f37ca3506b884ed5, e51c0f9cb6bfd105496a61153fb57c098896b985

Let me know if you have any other suggestions or concerns. Thanks!

File: plugins/woocommerce/src/Admin/Features/Features.php (hunk 2 above)
Comment (chihsuan) [reply plugins/woocommerce/src/Admin/Features/Features.php:379]: Yeah, I think that's a good idea.

File: plugins/woocommerce/src/Admin/Features/Features.php (hunk 1 above)
Comment (chihsuan) [reply plugins/woocommerce/src/Admin/Features/Features.php]: @Konamiman, Could you please review the changes I made when you get a chance? Thanks! 🙂

**Comment by Konamiman** [comment]
Tests well except the last steps. Adding the `spl_autoload_register` snippet right ad the top of the constructor of the `Features` class and loading the site on an incognito window (and without any other page of the site open in other windows) causes the following to show up in `debug.log`:

```
Automattic\WooCommerce\Admin\Features\ProductBlockEditor
Automattic\WooCommerce\Admin\Features\CoreProfiler
Automattic\WooCommerce\Admin\Features\CoreProfiler\Init
Automattic\WooCommerce\Admin\Features\CustomizeStore
Automattic\WooCommerce\Admin\Features\CustomizeStore\Init
Automattic\WooCommerce\Admin\Features\ImportProductsTask
Automattic\WooCommerce\Admin\Features\ImportProductsTask\Init
Automattic\WooCommerce\Admin\Features\ExperimentalFashionSampleProducts
Automattic\WooCommerce\Admin\Features\ExperimentalFashionSampleProducts\Init
Automattic\WooCommerce\Admin\Features\ShippingSmartDefaults
Automattic\WooCommerce\Admin\Features\ShippingSmartDefaults\Init
Automattic\WooCommerce\Admin\Features\ShippingSettingTour
Automattic\WooCommerce\Admin\Features\ShippingSettingTour\Init
Automattic\WooCommerce\Admin\Features\OnboardingTasks
Automattic\WooCommerce\Admin\Features\PatternToolkitFullComposability
Automattic\WooCommerce\Admin\Features\PatternToolkitFullComposability\Init
Automattic\WooCommerce\Admin\Features\ProductCustomFields
Automattic\WooCommerce\Admin\Features\ProductCustomFields\Init
Automattic\WooCommerce\Admin\Features\RemoteFreeExtensions
Automattic\WooCommerce\Admin\Features\PaymentGatewaySuggestions
Automattic\WooCommerce\Admin\Features\Printful
Automattic\WooCommerce\Admin\Features\Printful\Init
Automattic\WooCommerce\Admin\Features\Subscriptions
Automattic\WooCommerce\Admin\Features\Subscriptions\Init
Automattic\WooCommerce\Admin\Features\StoreAlerts
Automattic\WooCommerce\Admin\Features\StoreAlerts\Init
Automattic\WooCommerce\Admin\Features\WooMobileWelcome
Automattic\WooCommerce\Admin\Features\WooMobileWelcome\Init
Automattic\WooCommerce\Admin\Features\WcPayPromotion
```

**Comment by Konamiman** [comment]
Also there are merge conflicts, could you please fix them?

**Comment by Konamiman** [comment]
I have added the following right before your snippet:

```php
error_log("******* should load admin features: " . (self::should_load_features() ? "YES" : "NO"));
```

After loading the site once in incognito mode, this gets logged twice, first with value "NO", after that no admin classes are loaded; but then it gets logged with value "YES" and the admin classes from my previous comment are loaded. Might it be because of the WC Beta Tester?

**Comment by chihsuan** [comment]
> After loading the site once in incognito mode, this gets logged twice, first with value "NO", after that no admin classes are loaded; but then it gets logged with value "YES" and the admin classes from my previous comment are loaded. Might it be because of the WC Beta Tester?

Thanks @Konamiman! I was able to reproduce the issue locally, but It only occurs sometimes when I visit the site.  I discovered that the issue happens when the wp-cron is scheduled to run, causing should_load_features to return true. The issue was resolved after disabling the cron by adding `define( 'DISABLE_WP_CRON', true );` to `wp-config.php.` Let me know if you're experiencing the same behavior. 🙏 

> Also there are merge conflicts, could you please fix them?

Sure, I have fixed the merge conflicts.

**Review by Konamiman — APPROVED** [review]

**Comment by Konamiman** [comment]
Indeed, with `define( 'DISABLE_WP_CRON', true );` it works as expected. Approved.
