### PR TITLE
Fix stock indicator visibility for Variable products

### LINKED ISSUE #53720: Stock Indicator for Variations visibility is not working well
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

The `Stock Indicator` block should be visible only when a variable product has no variations with a price. In such cases, the stock indicator message should read:
`This product is currently out of stock and unavailable.`
However, we are not showing that message.

Additionally, the `Stock Indicator` block should not be visible for variable products in any other circumstances. Currently, it is visible when it shouldn't be.

### Expected behavior

The Stock Indicator block should be visible when a variable product doesn't have variations with price.

The Stock Indicator block should be hidden for variable products in any other circumstances.

### Steps to reproduce

1. Create a new variable product; create a few variations, but don't add a price to them.
2.  Go to Pages > Add New Page.
3. Add a Single Product block and select the product you just created (not the variations, but the parent).
4. Add a Stock indicator inside the Single Product block.
5. The stock indicator should say:
```
This product is currently out of stock and unavailable.
```
 Instead, it will say:
```
Out of stock
```
6. Add a price for every variation and go back to the page you were creating.
7. No stock indicator message should be shown for variable products.

### WordPress Environment

It's happening on `trunk`.

### Isolating the problem

- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by octaedro**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

This PR fixes an error with the `Stock Indicator` message for variable products (in the `Single Product` block) when they don't have variations with a price. In such case, the stock indicator message will read:
`This product is currently out of stock and unavailable.`

| Before | After |
|--------|--------|
| Image | Image |
| Image | Image | 

Additionally, the `Stock Indicator` block should not be visible for variable products in any other circumstances. This PR also fixes that error.

Closes #53720.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Create a new variable product; create a few variations, but don't add a price to them.
2.  Go to Pages > Add New Page.
3. Add a `Single Product` block and select the product you just created (not the variations, but the parent).
4. Add a `Stock indicator` inside the `Single Product` block.
5. The stock indicator should say:
```
This product is currently out of stock and unavailable.
```
6. Save the page and view it.
7. Verify the text looks correct in the front end as well.
8. Add a price for every variation and go back to the page you created.
9. No stock indicator message should be shown for variable products.

Screenshot 2025-01-03 at 1 17 52 PM

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce/src/Blocks/BlockTypes/ProductStockIndicator.php [hunk 1]
```diff
@@ -82,15 +83,13 @@ protected function render( $attributes, $content, $block ) {
...
-		$availability = $product->get_availability();
+		$availability = ProductAvailabilityUtils::get_product_availability( $product );
 
 		if ( empty( $availability['availability'] ) ) {
 			return '';
 		}
 
-		$low_stock_amount   = $product->get_low_stock_amount();
 		$total_stock        = $product->get_stock_quantity();
-		$is_low_stock       = $low_stock_amount && $total_stock <= $low_stock_amount;
```
Comment (octaedro) [inline plugins/woocommerce/src/Blocks/BlockTypes/ProductStockIndicator.php:93]: We don't use these two variables (`$low_stock_amount` and `$is_low_stock`) anymore.

File: plugins/woocommerce/src/Blocks/BlockTypes/ProductStockIndicator.php [hunk 2]
```diff
@@ -45,7 +46,7 @@ protected function get_block_type_uses_context() {
 	 * @return array
 	 */
 	protected function get_product_types_without_stock_indicator() {
-		return array( ProductType::EXTERNAL, ProductType::GROUPED, ProductType::VARIABLE );
+		return array( ProductType::EXTERNAL, ProductType::GROUPED );
```
Comment (octaedro) [inline plugins/woocommerce/src/Blocks/BlockTypes/ProductStockIndicator.php:49]: Variable products only display a stock indicator under the circumstances outlined in this PR. For this reason, we need to remove it from this list.

File: plugins/woocommerce/src/Blocks/Utils/ProductAvailabilityUtils.php [hunk 3]
```diff
@@ -0,0 +1,48 @@
...
+			return $product_availability;
+		}
+
+		// If the product is a variable product, check if it has any available variations.
+		// We will show a custom availability message if it does.
+		if ( $product->get_type() === ProductType::VARIABLE ) {
+			$available_variations = $product->get_available_variations();
+			if ( empty( $available_variations ) && false !== $available_variations ) {
+				$product_availability['availability'] = __( 'This product is currently out of stock and unavailable.', 'woocommerce' );
+				$product_availability['class']        = 'out-of-stock';
```
Comment (octaedro) [inline plugins/woocommerce/src/Blocks/Utils/ProductAvailabilityUtils.php:34]: We set the product availability class to `out-of-stock` for consistency with the variable product page. We assume it's out of stock [here](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/templates/single-product/add-to-cart/variable.php#L32).

**Review by Aljullu — COMMENTED** [review]
Overall looks good, but I'm a bit confused now. If I have the _Stock Indicator_ and _Add to Cart with Options_ (the existing one) on the same _Single Product_ block, I see the message twice in the frontend:

imatge

Can you reproduce too? I think it's a bit unfortunate that WooCommerce is using the Variable product Add to Cart template to render this message instead of the Stock Indicator space.

I'm not sure what's a good solution here, to be honest. :confused:  Wondering if there is a way to make it so the message is only displayed conditionally, to make sure we don't display it twice.

**Comment by octaedro** [comment]
Hi @Aljullu, thank you for reviewing this PR!

> If I have the _Stock Indicator_ and _Add to Cart with Options_ (the existing one) on the same _Single Product_ block, I see the message twice in the frontend:

I can reproduce this behavior, but I’m not sure if it’s a bug. The `Add to Cart with Options` block mimics the add to cart form used on the product page. Since we display the stock indicator on the product page, it makes sense for it to also appear in the `Add to Cart with Options` block ([add-to-cart-form](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/src/Blocks/BlockTypes/AddToCartForm.php)).

> Wondering if there is a way to make it so the message is only displayed conditionally, to make sure we don't display it twice.

Considering that both the old and new versions of the `Add to Cart with Options` block automatically include the `Stock Indicator`, I believe that when a user chooses to add an additional `Stock Indicator` to the `Single Product` block, it indicates they intentionally want two stock indicators on the page.

One of the benefits of blocking the `Add to Cart with Options` is that it allows the user to remove the `Stock Indicator` from the add to cart and place it elsewhere on the page if desired.

Please let me know if I understood your comments correctly.

**Review by Aljullu — APPROVED** [review]
Yeah, sorry I was wrong, I thought it was a special case for this "special" availability message, but it happens in all of them, so I agree it's the expected behavior.

imatge

Disregard my previous comment and sorry for the confusion! :sweat_smile: 

LGTM :ship:
