### PR TITLE
Prevent fatal errors during uninstall

### LINKED ISSUE #32915: Error: Call to undefined function wc_get_container() while deleting the woocommerce plugin when "WC_REMOVE_ALL_DATA" is set to true in wp-config.php
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Fully remove all WooCommerce data is not working while deleting the plugin when `"WC_REMOVE_ALL_DATA"` is set to true in wp-config.php

### Expected behavior

This should have fully removed all WooCommerce data and the WooCommerce plugin from the website.

### Actual behavior

I found the following error in the `wp-content\debug.log` file.

> **Error: Call to undefined function wc_get_container()**

### Steps to reproduce

1. I created a new wordpress website and installed the woocommerce plugin via `Plugins` > `Add New`
2. Skipped the store setup process.
3. Added `define( 'WC_REMOVE_ALL_DATA', true );` into `wp-config.php`.  
4. Then deactivated the plugin.
5. Then clicked on the `Delete` button in front of the woocommerce plugin on the plugins page. 

But it did not work. 
I found the following error in the `wp-content\debug.log` file.

> **Error: Call to undefined function wc_get_container()**

### WordPress Environment

<details>

```
### WordPress Environment ###

WordPress address (URL): http://ca_wordpress.test
Site address (URL): http://ca_wordpress.test
WC Version: 6.4.1
REST API Version: ✔ 6.4.1
WC Blocks Version: ✔ 7.2.2
Action Scheduler Version: ✔ 3.4.0
WC Admin Version: ✔ 3.3.2
Log Directory Writable: ✔
WP Version: 5.9.3
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.16.0
PHP Version: 7.4.29
PHP Post Max Size: 2 GB
PHP Time Limit: 36000
PHP Max Input Vars: 1000
cURL Version: 7.70.0
OpenSSL/1.1.1n

SUHOSIN Installed: –
MySQL Version: 8.0.28
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 6.4.1
WC Database Prefix: wp_
Total Database Size: 7.13MB
Database Data Size: 4.64MB
Database Index Size: 2.49MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_e_events: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_erp_acct_bill_account_details: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_erp_acct_bill_details: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_erp_acct_bills: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_erp_acct_cash_at_banks: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_erp_acct_chart_of_accounts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_erp_acct_currency_info: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_erp_acct_expense_checks: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_erp_acct_expense_details: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_erp_acct_expenses: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_erp_acct_financial_years: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_erp_acct_invoice_account_details: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_erp_acct_invoice_details: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_erp_acct_invoice_details_tax: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_erp_acct_invoice_receipts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_erp_acct_invoice_receipts_details: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_erp_acct_invoices: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_erp_acct_journal_details: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_erp_acct_journals: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_erp_acct_ledger_categories: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_erp_acct_ledger_details: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_erp_acct_ledger_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_erp_acct_ledgers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_erp_acct_opening_balances: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_erp_acct_pay_bill: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_erp_acct_pay_bill_details: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_erp_acct_pay_purchase: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_erp_acct_pay_purchase_details: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_erp_acct_payment_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_erp_acct_people_account_details: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_erp_acct_people_trn: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_erp_acct_people_trn_details: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_erp_acct_product_categories: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_erp_acct_product_details: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_erp_acct_product_types: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_erp_acct_products: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_erp_acct_purchase: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_erp_acct_purchase_account_details: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_erp_acct_purchase_details: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_erp_acct_purchase_details_tax: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_erp_acct_synced_taxes: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_erp_acct_tax_agencies: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_erp_acct_tax_agency_details: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_erp_acct_tax_cat_agency: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_erp_acct_tax_categories: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_erp_acct_tax_pay: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_erp_acct_taxes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_erp_acct_transfer_voucher: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_erp_acct_trn_status_types: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_erp_acct_voucher_no: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_erp_audit_log: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_erp_company_locations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_erp_crm_activities_task: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_erp_crm_contact_group: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_erp_crm_contact_subscriber: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_erp_crm_customer_activities: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_erp_crm_customer_companies: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_erp_crm_save_email_replies: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_erp_crm_save_search: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_erp_holidays_indv: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_erp_hr_announcement: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_erp_hr_dependents: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_erp_hr_depts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_erp_hr_designations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_erp_hr_education: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_erp_hr_employee_history: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_erp_hr_employee_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_erp_hr_employee_performance: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_erp_hr_employees: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_erp_hr_financial_years: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_erp_hr_holiday: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_erp_hr_leave_approval_status: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_erp_hr_leave_encashment_requests: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_erp_hr_leave_entitlements: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_erp_hr_leave_policies: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_erp_hr_leave_policies_segregation: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_erp_hr_leave_request_details: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_erp_hr_leave_requests: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_erp_hr_leaves: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_erp_hr_leaves_unpaid: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_erp_hr_work_exp: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_erp_people_type_relations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_erp_people_types: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_erp_peoplemeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_erp_peoples: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_erp_user_leaves: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mphb_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mphb_customers: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mphb_customers_meta: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mphb_sync_logs: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mphb_sync_queue: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mphb_sync_stats: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mphb_sync_urls: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 2.03MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_posts: Data: 0.05MB + Index: 0.06MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 1
elementor_library: 1
mphb_rate: 2
mphb_room: 1
mphb_room_service: 1
mphb_room_type: 3
mphb_season: 5
page: 18
post: 1
revision: 4
wp_global_styles: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (10) ###

ChargeAutomation: by Mutahhar Naseer – 1.0.0
Elementor: by Elementor.com – 3.6.5
Laravel DD for Wordpress: by Peter Hegman – 1.0.1
Hotel Booking Lite: by MotoPress – 4.2.4
Hotel Booking & Elementor Integration: by MotoPress – 1.1.4
Hotel Booking Styles: by MotoPress – 1.0.2
One Click Demo Import: by OCDI – 3.1.1
Stratum - Elementor Widgets: by MotoPress – 1.3.13
SVG Support: by Benbodhi – 2.4.2
WooCommerce: by Automattic – 6.4.1

### Inactive Plugins (2) ###

WP ERP: by weDevs – 1.10.5
WPPB Demo Plugin: by Devin Vinson – 1.0.0

### Settings ###

API Enabled: –
Force SSL: –
Currency: PKR (₨)
Currency Position: left_space
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 0
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: ❌ Page visibility should be public
Cart: ❌ Page visibility should be public
Checkout: ❌ Page visibility should be public
My account: ❌ Page visibility should be public
Terms and conditions: ❌ Page not set

### Theme ###

Name: Albatross
Version: 1.0.3 (update to version 1.0.4 is available)
Author URL: https://motopress.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ❌ Not declared

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 3
Oldest: 2022-04-28 09:46:40 +0000
Newest: 2022-05-09 05:39:33 +0000


### Status report information ###

Generated at: 2022-05-09 05:39:59 +00:00
```

</details>

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by barryhughes**
When WooCommerce is uninstalled, and if the constant `WC_REMOVE_ALL_DATA` is defined and true, then WooCommerce is expected to remove all of its custom tables (and all of its data from regular WordPress tables). Currently, this is failing. Reasons:

- During uninstall, some services are now accessed through our container, but `wc_get_container()` is not defined (`uninstall.php` tries to be very lightweight and has not traditionally loaded all of WooCommerce). This leads to a fatal error.
- It expects `WC_PLUGIN_BASENAME` to be defined but it is not ... previously this only resulted in a warning, but as of PHP 8.0 it also leads to a fatal error.

Additionally, it does not take care of cleaning up our COT tables (if they exist), so this felt like a good opportunity to also address that.

Closes #32915.

### How to test the changes in this Pull Request:

1. Install and activate WooCommerce.
2. Visit **WooCommerce ▸ Status ▸ Tools** and create the Custom Order Tables.
3. Deactivate WooCommerce, then click on the `Delete` link (triggers the uninstall routine).
4. The plugin should (eventually) be deleted. 
    - Without this change, fatal errors occur.
    - With this change, those fatals (as noted in the description) should be resolved.
5. All WooCommerce tables, including COT tables, should have been removed (verify using a tool of choice ... for instance, you can do `wp db query "SHOW TABLES"`).

† Bear in mind when testing that WP may be unable to remove the plugin files for a wide variety of reasons, especially if you symlinked your plugin directory from the monorepo and if PHP executes as a user that does not have permission to modify those files, etc. 

### Other information:

-   [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
-   [ ] Have you written new tests for your changes, as applicable?
-   [ ] Have you successfully run tests with your changes locally?
-   [ ] Have you created a changelog file for each project being changed, ie `pnpm changelog add --filter=<project>`?

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

File: plugins/woocommerce/uninstall.php [hunk 1]
```diff
@@ -33,8 +34,8 @@
  * and to ensure only the site owner can perform this action.
  */
 if ( defined( 'WC_REMOVE_ALL_DATA' ) && true === WC_REMOVE_ALL_DATA ) {
-	// Drop WC Admin tables.
-	include_once dirname( __FILE__ ) . '/includes/class-wc-install.php';
+	// Load WooCommerce so we can access the container, install routines, etc, during uninstall.
+	require_once __DIR__ . '/woocommerce.php';
```
Comment (barryhughes) [inline plugins/woocommerce/uninstall.php:38]: ✍🏽 I'll just quickly note, requiring this file takes care of requiring `/includes/class-wc-install.php`, hence why I removed that existing line.

File: plugins/woocommerce/uninstall.php [hunk 2]
```diff
@@ -65,15 +66,17 @@
 	// Delete usermeta.
 	$wpdb->query( "DELETE FROM $wpdb->usermeta WHERE meta_key LIKE 'woocommerce\_%';" );
 
-	// Delete posts + data.
+	// Delete our data from the post and post meta tables, and remove any additional tables we created.
 	$wpdb->query( "DELETE FROM {$wpdb->posts} WHERE post_type IN ( 'product', 'product_variation', 'shop_coupon', 'shop_order', 'shop_order_refund' );" );
```
Comment (vedanshujain) [inline plugins/woocommerce/uninstall.php:70]: offtopic- should we even do this during uninstall? i don't think that we give any warning that your data will be deleted

File: plugins/woocommerce/uninstall.php [hunk 3]
```diff
@@ -65,15 +66,17 @@
...
 	$wpdb->query( "DELETE meta FROM {$wpdb->postmeta} meta LEFT JOIN {$wpdb->posts} posts ON posts.ID = meta.post_id WHERE posts.ID IS NULL;" );
 
 	$wpdb->query( "DELETE FROM {$wpdb->comments} WHERE comment_type IN ( 'order_note' );" );
 	$wpdb->query( "DELETE meta FROM {$wpdb->commentmeta} meta LEFT JOIN {$wpdb->comments} comments ON comments.comment_ID = meta.comment_id WHERE comments.comment_ID IS NULL;" );
 
-	$wpdb->query( "DROP TABLE IF EXISTS {$wpdb->prefix}woocommerce_order_items" );
-	$wpdb->query( "DROP TABLE IF EXISTS {$wpdb->prefix}woocommerce_order_itemmeta" );
+	foreach ( wc_get_container()->get( OrdersTableDataStore::class )->get_all_table_names() as $cot_table ) {
```
Comment (vedanshujain) [inline plugins/woocommerce/uninstall.php:76]: `woocommerce_order_items` and `woocommerce_order_itemmeta` are different tables from COT and needs to be deleted (if we are deleting tables).

**Review by vedanshujain — CHANGES_REQUESTED** [review]
Requesting a change for also dropping order _items tables. Otherwise looks good.

File: plugins/woocommerce/uninstall.php (hunk 3 above)
Comment (barryhughes) [reply plugins/woocommerce/uninstall.php:76]: > If we are deleting tables

Well ... we *are* and have been deleting tables during uninstall (at least, when `WC_REMOVE_ALL_DATA` is set). So, this change is mostly for consistency. Otherwise, I envision a future complaint where someone runs the uninstall process, and everything is cleaned up except for this subset of our tables.

> woocommerce_order_items and woocommerce_order_itemmeta are different tables from COT and needs to be deleted

To be clear, I removed lines 75-76 because they are superfluous and not because I wanted us to keep those tables. Up on line 60 you will see a call to [`WC_Install::remove_tables()`](https://github.com/woocommerce/woocommerce/blob/ce3ce7cb869e9a50419b32bf60f6dd6d53195210/plugins/woocommerce/uninstall.php#L60) which was already taking care of this (in my testing this was perfectly fine, but let me know if you found a case where those two tables still manage to survive).

File: plugins/woocommerce/uninstall.php (hunk 2 above)
Comment (barryhughes) [reply plugins/woocommerce/uninstall.php:70]: By default, we don't do this: for these lines to be executed, the site owner has to modify `wp-config.php` (or other suitable location) and define constant `WC_REMOVE_ALL_DATA` as `true` (see [line 36](https://github.com/woocommerce/woocommerce/blob/ce3ce7cb869e9a50419b32bf60f6dd6d53195210/plugins/woocommerce/uninstall.php#L31-L36)). So, it's a very deliberate choice and it would be hard for someone to do unintentionally.

**Comment by barryhughes** [comment]
Pinging @vedanshujain! (Just in case my responses to your questions got lost in the notifications.)

**Review by vedanshujain — APPROVED** [review]
Thanks for answering, lgtm. Nice work!
