### PR TITLE
Fix incorrect adjustment of post count in WC_Query

### LINKED ISSUE #27162: wc 4.4 beta don't show previous orders as a logged customer(in the backend are ok)
**Prerequisites (mark completed items with an [x]):**
- [ x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [ x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
Upgraded on a staging site to wc 4.4 beta from 4.3.1. Everything is fine but, if i log as a customer with previous orders and visit
My Account, Orders a message appears:
**No order has been made yet.**
(and the user has a lot of orders), "in wc 4.3.1 the list of orders, when the customer is logged are ok, only happens in the 4.4 beta "

**Expected behavior**
The usual list of orders of the logged user must be shown.

**Actual behavior**
No previous orders are shown(to the customer as a logged user, in the backend the orders are fine for all customers)

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
Upgrade to wc 4.4 beta from 4.3.1 , log as a customer with previous orders, or make new ones, and go to my orders.

**Isolating the problem (mark completed items with an [x]):**
- [ x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ x] I can reproduce this bug consistently using the steps above.

This happens with all plugins deactivated and with a default theme too(tested with twenty-twenty). No plugin or theme-related.

### PR DESCRIPTION
**Pull request by Konamiman**
### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

https://github.com/woocommerce/woocommerce/pull/26260 introduced a handler for the `found_posts` filter in the `WC_Query` class in order to adjust the count depending on the visibility of variation products. However the handler incorrectly assumed that the filter was triggered only when listing products, when actually it's also triggered for any post type e.g. pages. In these cases the post count was set to zero, which caused bugs (e.g. orders list appeared empty in customer profiles).

Now the handler starts with the originally supplied posts count, and only decrements it when a post is a product AND is not visible.

Closes #27162.

### How to test the changes in this Pull Request:

1. Login as a customer, go to the orders page in your account and verify that all your orders are listed (place a new order if you didn't have any).
2. Verify that the functionality introduced in https://github.com/woocommerce/woocommerce/pull/26260 still works.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

Not needed since the bug was introduced in 4.4 beta 1 and the fix will be included in the final release.

### CODE REVIEW

File: tests/legacy/unit-tests/util/class-wc-tests-wc-query.php [hunk 1]
```diff
@@ -517,4 +521,16 @@ public function test_adjust_posts_count_when_there_are_no_posts() {
 
 		$this->assertEquals( 34, $sut->adjust_posts_count( 34 ) );
 	}
+
+	/**
+	 * @testdox adjust_posts should return the input unmodified if the posts do not represent products.
+	 */
+	public function test_adjust_posts_count_when_the_posts_are_not_products() {
+		list($sut, $products) = $this->setup_adjust_posts_test( true, true, 'page' );
```
Comment (claudiosanches) [inline tests/legacy/unit-tests/util/class-wc-tests-wc-query.php:529]:
```suggestion
		list( $sut, $products ) = $this->setup_adjust_posts_test( true, true, 'page' );
```

**Review by claudiosanches — CHANGES_REQUESTED** [review]
The code looks good, I left one note to fix a small coding standard issue

**Comment by Konamiman** [comment]
@claudiosanches Thanks for the fix suggestion, I applied it.

**Review by claudiosanches — APPROVED** [review]
LGTM!

**Review by rrennick — APPROVED** [review]
@Konamiman Looks good.
