### PR TITLE
Add to Cart + Options block: simplify and fix pills colors

### LINKED ISSUE #58925: Add to Cart + Options Variation Selector: remove hover styles on disabled pills
In the *Add to Cart + Options* variation selector, the disabled pills have hover styles that make them feel clickable.

#### Preparation

1. Go to *Appearance* > *Editor* > *Templates* > *Single Product*.
2. Click on the *Add to Cart with Options* block and update to the blockified version.

#### Reproducing the issue

1. If needed, edit the variations of a variable product to make sure there is a specific combination of attributes where one attribute will be disabled.
2. Visit that product in the frontend.
3. Notice you can hover the pill and the background color changes and the cursor becomes a pointer.

https://github.com/user-attachments/assets/2127bdf8-650d-42eb-aba5-31bdb8be9a48

**Expected result**

When a pill is disabled, the background shouldn't change on hover and the cursor should be the default one.

### PR DESCRIPTION
**Pull request by Aljullu**
### Changes proposed in this Pull Request:

This PR makes several improvements to the way we define colors for the _Variation Selector_ pills in the _Add to Cart + Options_. Specifically, it does:

* Removes `:hover` styles from disabled pills (fixes https://github.com/woocommerce/woocommerce/issues/58925).
* Fixes the `:focus` outline not being visible.
* Removes calls to theme CSS variables like `var(--wp--preset--color--contrast)`.
* Uses `:focus-within` instead of `&:has(.wc-block-add-to-cart-with-options-variation-selector-attribute-options__pill-input:focus)`, so the code is cleaner.
* Defines `--pill-color` and `--pill-background-color`, so the same CSS can be used for the different states.

#### Preparation

1. Go to *Appearance* > *Editor* > *Templates* > *Single Product*.
2. Click on the *Add to Cart with Options* block and update to the blockified version.

#### Reproducing the issue

1. If needed, edit the variations of a variable product to make sure there is a specific combination of attributes where one attribute will be disabled.
2. Visit that product in the frontend.
3. Verify when hovering the disabled pill, the background color doesn't change and the cursor becomes `not-allowed`.
4. Verify focusing pills shows an outline around them.
5. In general, do some smoke testing to make sure there are no styling regressions.

https://github.com/user-attachments/assets/4f2a6417-b9a9-4076-a414-a6c2ebc3bdab

### CODE REVIEW

File: plugins/woocommerce/client/blocks/assets/js/blocks/add-to-cart-with-options/variation-selector/attribute-options/set-styles.ts [hunk 1]
```diff
@@ -70,13 +70,9 @@ function setStyles(): void {
...
-			`:where(.wc-block-add-to-cart-with-options-variation-selector-attribute-options__pill):has(.wc-block-add-to-cart-with-options-variation-selector-attribute-options__pill-input:checked) {
-				background-color: ${ selectedPillBackgroundColor };
-				color: ${ selectedPillColor };
-				border-color: ${ selectedPillBackgroundColor };
-			}
-			:where(.wc-block-add-to-cart-with-options-variation-selector-attribute-options__pill):has(.wc-block-add-to-cart-with-options-variation-selector-attribute-options__pill-input:checked):hover{
-				background-color: color-mix(in srgb,${ selectedPillBackgroundColor } 85%,transparent)
+			`.wc-block-add-to-cart-with-options-variation-selector-attribute-options__pill:has(.wc-block-add-to-cart-with-options-variation-selector-attribute-options__pill-input:checked) {
+				--pill-color: ${ selectedPillColor };
+				--pill-background-color: ${ selectedPillBackgroundColor };
```
Comment (gigitux) [inline plugins/woocommerce/client/blocks/assets/js/blocks/add-to-cart-with-options/variation-selector/attribute-options/set-styles.ts]: Is it expected that we are removing the `:where`? If yes, we should update the comment.

File: plugins/woocommerce/client/blocks/assets/js/blocks/add-to-cart-with-options/variation-selector/attribute-options/edit.tsx [hunk 2]
```diff
@@ -71,10 +71,9 @@ export default function AttributeOptionsEdit(
 	useThemeColors(
 		'add-to-cart-with-options-variation-selector-attribute-options',
 		( { editorBackgroundColor, editorColor } ) => `
-			:where(.wc-block-add-to-cart-with-options-variation-selector-attribute-options__pill--selected) {
-				background-color: ${ editorColor };
-				color: ${ editorBackgroundColor };
-				border-color: ${ editorColor };
+			.wc-block-add-to-cart-with-options-variation-selector-attribute-options__pill--selected {
+				--pill-color: ${ editorBackgroundColor };
+				--pill-background-color: ${ editorColor };
```
Comment (gigitux) [inline plugins/woocommerce/client/blocks/assets/js/blocks/add-to-cart-with-options/variation-selector/attribute-options/edit.tsx]: Same question here

**Review by gigitux — APPROVED** [review]
I tested the PR and it works fine! 

https://github.com/user-attachments/assets/b41978d0-d6e1-48ba-9b39-2b3fa12b5a9d


I'm pre-approving the PR, but I noticed that `:where` has been removed. Is it expected?

File: plugins/woocommerce/client/blocks/assets/js/blocks/add-to-cart-with-options/variation-selector/attribute-options/set-styles.ts (hunk 1 above)
Comment (Aljullu) [reply plugins/woocommerce/client/blocks/assets/js/blocks/add-to-cart-with-options/variation-selector/attribute-options/set-styles.ts]: Good catch, added them back in 25f679f138fb136687a380822838a942f4d86ff7.

File: plugins/woocommerce/client/blocks/assets/js/blocks/add-to-cart-with-options/variation-selector/attribute-options/edit.tsx (hunk 2 above)
Comment (Aljullu) [reply plugins/woocommerce/client/blocks/assets/js/blocks/add-to-cart-with-options/variation-selector/attribute-options/edit.tsx]: Same 25f679f138fb136687a380822838a942f4d86ff7. :slightly_smiling_face:
