### PR TITLE
[Settings] Add Legacy save API

### LINKED ISSUE #54867: [Settings] Enable Saving
Create the ability to Save form data when merchants click "Save".

The proof of concept handled this by gathering all input values from the form and submitting the data to `/wp-json/wc-admin/settings` as form data.

https://github.com/woocommerce/woocommerce/pull/48340/files#diff-08711774f4a65ea5c2516f4bee385d36dc0ec3366f8a7e5e2c31d7cf0e7fe4f9R36

### Requirements
* Collect all data within the DataForm. Keep in mind this includes any inputs with ids added via slotFill or rendered custom HTML created by an extension.
* DataForms have a concept of [internal data](https://github.com/woocommerce/woocommerce/blob/6cb8c4d3fdea55b3379b427f4d9bae296ba15fb0/packages/js/settings-editor/src/hooks/use-settings-form.ts#L60). Decide if this is useful. What is the source of truth?
* After clicking Save, other sections and tabs should be aware of the changes. @chihsuan had the idea to reconstruct the data created by `WC_Settings_Page::add_settings_page_data` on success and repopulate `window.wcSettings.admin.settingsData`. 
* Keep in mind this will be only for Legacy screens. Modern screens may also use this system or create an entirely new one. What would you recommend?

### LINKED ISSUE #55530: [Settings] Tax page should not be visible if tax is disabled
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Currently, the tax page is visible when the tax feature is disabled. When visiting the tax page, the blank content is shown.

We can use the `woocommerce_settings_tabs_array` filter to check whether the tax page should be visible.

### Expected behavior

We should hide the tax page from navigation if the tax is disabled, like the classic settings page.

### Actual behavior

 the tax page is visible when the tax feature is disabled. 

### Steps to reproduce

1. Add/Enable Gutenberg 19.8 or earlier
2. Enable `settings` feature flag
3. Turn on the Settings feature flag and go to WooCommerce > Settings 

### WordPress Environment

n/a

### Isolating the problem

- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by psealock**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes https://github.com/woocommerce/woocommerce/issues/54867
Closes https://github.com/woocommerce/woocommerce/issues/55530

Enable the Save button on Settings.

* Create new Settings endpoint for saving.
* Use DataProvider context for keeping track of data.
* Add `<Notices />` to display core notices.

### Key Decisions made

1. Avoid a data store on the client in favor of using the [Context api](https://react.dev/reference/react/useContext) to create a Data Provider. I choose using the context because the legacy settings are powered by a large complex singular piece of data. Instead of manipulating pieces here and there, the entire object is returned from the api and replaced wholesale.
2. Create a new Admin API endpoint specific to the new Settings. Other possibilities include using the WooCommerce API settings endpoint or the existing Options endpoint. I decided on this path because it was easiest to call `WC_Admin_Settings::save();` which is the method employed by the traditional POST request we have on current screens.
3. Generally keep implementation as simple as possible without making design decisions. This will all come later. 

### Possible Next Steps

Here are some things we can do in follow ups and I'm are open to suggestions.

1. Use this new api to populate data instead of populating the global `window` on page construction.
2. Add unit test to for the new api endpoint.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. WooCommerce > Settings. Poke around and make sure Settings are working and saving properly.
2. Add/Enable Gutenberg 19.8 or earlier.
3. Turn on the `settings` feature flag.
4. Manipulate a few settings and ensure a Notice is displayed.
5. Refresh the page and make sure settings were truly saved.
6. WooCommerce > Settings > General > Enable tax rates and calculations. Toggle this on/off and save. You should see the Tax tab in the sidebar update accordingly.  
7. Click on Taxes when it appears after saving. The "Tax options" section should be populated with settings.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

File: packages/js/settings-editor/src/index.tsx [hunk 1]
```diff
@@ -28,9 +30,54 @@ dispatch( editSiteStore ).updateSettings( {
...
+		>
+			{ children }
+		</SettingsDataContext.Provider>
+	);
+};
+
+const Notices = () => {
+	// eslint-disable-next-line @typescript-eslint/ban-ts-comment
+	// @ts-ignore
+	const notices = useSelect( ( select: any ) => {
```
Comment (psealock) [inline packages/js/settings-editor/src/index.tsx]: I'm not sure why, but a type is required here.

File: plugins/woocommerce/src/Admin/API/Settings.php [hunk 2]
```diff
@@ -0,0 +1,120 @@
...
+	public function save_settings( $request ) {
+        global $current_section, $current_tab;
+
+        $params = $request->get_params();
+
+        try {
+            // Get current tab/section and set global variables.
+            $current_tab     = empty( $params['tab'] ) ? 'general' : sanitize_title( wp_unslash( $params['tab'] ) ); // WPCS: input var okay, CSRF ok.
+            $current_section = empty( $params['section'] ) ? '' : sanitize_title( wp_unslash( $params['section'] ) ); // WPCS: input var okay, CSRF ok.
+
```
Comment (adrianduffell) [inline plugins/woocommerce/src/Admin/API/Settings.php]: It would be nice to add the tab and section to the schema in `save_items_schema`, and I think it can handle default values as well. Something like.

```
'tab' => array(
    'type'        => 'string',
    'description' => __( 'Description here', 'woocommerce' ),
     'default'     => 'general',
 ),
 ```

Comment (psealock) [reply plugins/woocommerce/src/Admin/API/Settings.php]: Nice, done in https://github.com/woocommerce/woocommerce/pull/55467/commits/30408928f79ddac61a62a0d79b7e9c2c32c1c5d3

**Comment by chihsuan** [comment]
@psealock The CI is failing because of linting/tests errors. Could you take a look? I'll review the PR soon.

File: packages/js/settings-editor/src/index.tsx [hunk 3]
```diff
@@ -28,9 +31,33 @@ dispatch( editSiteStore ).updateSettings( {
 	__experimentalDashboardLink: getAdminLink( 'admin.php?page=wc-admin' ),
 } );
 
+const Notices = () => {
+	const notices: { id: string; content: string }[] = useSelect(
```
Comment (chihsuan) [inline packages/js/settings-editor/src/index.tsx:35]: It seems that `@wordpress/notices` notice action types don't match the types in the `@wordpress/components` package. I'm okay with converting the types like this. 👍 

Another option I considered is to make the types match the `SnackbarList` types.

```ts
	const notices = useSelect( ( select ) => {
		const { getNotices } = select( noticesStore );

		return getNotices().map( ( notice ) => ( {
			...notice,
			actions: notice.actions?.map( ( action ) => ( {
				label: action.label,
				onClick:
					action.onClick as unknown as React.MouseEventHandler< HTMLButtonElement >,
				url: action.url ?? '',
			} ) ),
		} ) );
	}, [] );
```

File: plugins/woocommerce/includes/admin/settings/class-wc-settings-page.php [hunk 4]
```diff
@@ -188,6 +188,20 @@ public function add_settings_page( $pages ) {
...
+			 * Filters the settings tabs array.
+			 *
+			 * @since 2.5.0
+			 *
+			 * @param array $available_pages The available pages.
+			 */
+			$available_pages = apply_filters( 'woocommerce_settings_tabs_array', array() );
+
+			// If any page has removed itself from the tabs array, avoid adding this page to the settings editor.
+			if ( ! in_array( $this->id, array_keys( $available_pages ), true ) ) {
```
Comment (chihsuan) [inline plugins/woocommerce/includes/admin/settings/class-wc-settings-page.php]: Nice! 👍  I think this would fix this issue https://github.com/woocommerce/woocommerce/issues/55530.

File: plugins/woocommerce/includes/admin/settings/class-wc-settings-page.php [hunk 5]
```diff
@@ -188,6 +188,20 @@ public function add_settings_page( $pages ) {
...
 		 */
 		public function add_settings_page_data( $pages ) {
+			/**
+			 * Filters the settings tabs array.
+			 *
+			 * @since 2.5.0
+			 *
+			 * @param array $available_pages The available pages.
+			 */
+			$available_pages = apply_filters( 'woocommerce_settings_tabs_array', array() );
```
Comment (chihsuan) [inline plugins/woocommerce/includes/admin/settings/class-wc-settings-page.php]: I am concerned (not too sure) about potential performance issues. It appears that `apply_filters` is invoked for each page. If this proves problematic, we could move this check to `get_page_data` to ensure it is only called once.

File: plugins/woocommerce/src/Admin/Features/Settings/Init.php [hunk 6]
```diff
@@ -165,18 +165,33 @@ public static function add_component_settings( $settings ) {
 		$setting_pages = \WC_Admin_Settings::get_settings_pages();
 		$pages         = array();
 		foreach ( $setting_pages as $setting_page ) {
-			$scripts_before_adding_settings = $wp_scripts->queue;
-			$pages                          = $setting_page->add_settings_page_data( $pages );
-
+			$scripts_before_adding_settings                         = $wp_scripts->queue;
```
Comment (chihsuan) [inline plugins/woocommerce/src/Admin/Features/Settings/Init.php]: This changes the result of `settingsScripts`. The `$scripts_before_adding_settings` is now the same as next line where we compare the difference to know what scripts are needed for the current page.

File: packages/js/settings-editor/src/legacy/form.tsx [hunk 7]
```diff
@@ -50,30 +60,60 @@ export const Form = ( {
...
+				method: 'POST',
+				body: payload,
+				credentials: 'same-origin', // Include cookies for nonce validation
+				headers: {
+					'X-WP-Nonce': settingsData._wpnonce,
+				},
+			}
 		);
+
+		const responseData = await response.json();
```
Comment (chihsuan) [inline packages/js/settings-editor/src/legacy/form.tsx]: This might throw an error. I think we need to add a `try...catch`.

```ts
    try {
        // ... existing code ...
    } catch (error) {
        createNotice(
            'error',
            __('Failed to save settings. Please try again.', 'woocommerce')
        );
        console.error('Settings save error:', error);
    } finally {
        setIsBusy(false);
    }
```

File: packages/js/settings-editor/src/legacy/form.tsx [hunk 8]
```diff
@@ -50,30 +60,60 @@ export const Form = ( {
...
+		updatedData._wpnonce = settingsData._wpnonce;
+		updatedData._w_http_referer = '/wp-admin/' + getNewPath( query );
+
+		const payload = new FormData();
+		for ( const [ key, value ] of Object.entries( updatedData ) ) {
+			payload.append( key, value );
+		}
+
+		const response = await fetch(
+			`/?rest_route=/wc-admin/legacy-settings&${ new URLSearchParams(
```
Comment (chihsuan) [inline packages/js/settings-editor/src/legacy/form.tsx]: This might cause an issue if the store is in a subdirectory. For example, if the URL is `https://example.com/subdirectory/`, the fetch call to `/?rest_route=/wc-admin/legacy-settings` will return an invalid response. I wonder if we can use `apiFetch` to make the request. I think it will handle this automatically.

**Review by chihsuan — COMMENTED** [review]
I've reviewed the code first and left some comments/suggestions. I'll test it later.

File: plugins/woocommerce/includes/admin/settings/class-wc-settings-page.php (hunk 5 above)
Comment (psealock) [reply plugins/woocommerce/includes/admin/settings/class-wc-settings-page.php]: Good call. I moved in in [move woocommerce_settings_tabs_array to get_page_data](https://github.com/woocommerce/woocommerce/pull/55467/commits/474de6457c639ebe6a18b14a755ec66837bdbdd2). Now the hook is called once.

File: plugins/woocommerce/includes/admin/settings/class-wc-settings-page.php (hunk 4 above)
Comment (psealock) [reply plugins/woocommerce/includes/admin/settings/class-wc-settings-page.php]: Yes it does!

File: packages/js/settings-editor/src/index.tsx (hunk 3 above)
Comment (psealock) [reply packages/js/settings-editor/src/index.tsx:35]: Ok, thanks for bringing this up. I will leave this as it is because its likely temporary. I added the notices to let merchants know the action succeeded/failed but all this depends on what Design determines about the saving mechanism, so I think we'll remove this eventually.

File: plugins/woocommerce/src/Admin/Features/Settings/Init.php (hunk 6 above)
Comment (psealock) [reply plugins/woocommerce/src/Admin/Features/Settings/Init.php]: Oh yikes, didn't see that.

Fixed in [keep script diff logic intact](https://github.com/woocommerce/woocommerce/pull/55467/commits/eea96217fb55be67a823f018e19678cc94681b23)

File: packages/js/settings-editor/src/legacy/form.tsx (hunk 7 above)
Comment (psealock) [reply packages/js/settings-editor/src/legacy/form.tsx]: Fixed in [add try/catch to response handling](https://github.com/woocommerce/woocommerce/pull/55467/commits/8925a710987d1551ec6a3e18d5cd330198326f2e)

File: packages/js/settings-editor/src/legacy/form.tsx (hunk 8 above)
Comment (psealock) [reply packages/js/settings-editor/src/legacy/form.tsx]: Nice, fixed in [use apiFetch for api call](https://github.com/woocommerce/woocommerce/pull/55467/commits/812f9643b150d61db1d1b91259156b640c637a60)

**Review by chihsuan — COMMENTED** [review]
Thanks for addressing the feedback. @psealock 👍  I've tested the changes. I can see the Tax tab update when I toggle the Tax option. However, I found that the settings are reset when I save the settings on other tabs. 🤔 

https://github.com/user-attachments/assets/f87f9e18-ca5d-4e47-a505-d1a771ab8ef2

**Comment by psealock** [comment]
>However, I found that the settings are reset when I save the settings on other tabs. 🤔

Oh whoops! in a refactor I forgot to add the query parameters to the request, so any page other than the default main page was getting settings reset to default values. Fixed in [add query args](https://github.com/woocommerce/woocommerce/pull/55467/commits/f573ec141a09e31dc999c48b03cedeab0d81d437).

Thanks for going beyond the test instructions @chihsuan, can you check again?

**Review by chihsuan — APPROVED** [review]
Thanks, I tested it again and confirmed that settings persist when I save on other tabs. 👍

Just found another issue, I see that payment page renders duplicate methods sections when saving settings on other tabs. I'm unsure if it's easy to fix. I'm okay if you want to address it in a separate PR.


https://github.com/user-attachments/assets/e2ac7f29-60cf-4486-9538-49f6e364a61a

**Comment by psealock** [comment]
Just noting here Settings in broken until https://github.com/woocommerce/woocommerce/pull/55848 is merged

**Review by adrianduffell — APPROVED** [review]
It's testing nice! Thanks for the improvements to the REST API schema 🚀

**Comment by psealock** [comment]
>Just found another issue, I see that payment page renders duplicate methods sections when saving settings on other tabs. I'm unsure if it's easy to fix. I'm okay if you want to address it in a separate PR.

Thanks @chihsuan, I'll need to dive in a bit deeper on this on in a follow up
