### PR TITLE
Add the CallbackUtil class and fix get_price_hash for variations

### LINKED ISSUE #37547: Variable data store read_price_data bypassing transients when hooked using add_filter(..., [$this, 'hookname'])
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Bug:
- Prices are recomputed in read_price_data for every request for every variant loaded in cases where woocommerce_variation_prices_price, woocommerce_variation_prices_regular_price, or woocommerce_variation_prices_sale_price are hooked via **$this**
```
add_filter('woocommerce_variation_prices_sale_price', [$this, 'product_sale_price'], 10, 3)
```
- If any value in $this changes from request to request, read_price_data will recompute the prices over and over and never used the saved transient.  This is because get_price_hash method used for storing the transient uses md5( wp_json_encode(...  of an array of class objects.
- read_price_data is a pretty resource intensive operation and causes severe performance issues in cases where this happens.  Because this is ran for every variant, performance penalty is pretty severe
- After workaround, page performance went from 200+ seconds to load, to under 3s on product single page that loads 1 main product with 79 variants, and three "related" products with 50+ variants each

### Expected behavior

read_price_data does not recompute prices every time and reads from transient

### Actual behavior

read_price_data recomputes price data each time because $price_hash changes every run

First run:
image
$price_hash array on line 425 of woocommerce/includes/data-stores/class-wc-product-variable-data-store-cpt.php - evaluates to "56a3c2b4e9a476f6abd6426393fe6f74"

Second run - Same exact hooks - should be the same price_hash, read_price_data should not recompute all prices:
image
$price_hash array on line 425 of woocommerce/includes/data-stores/class-wc-product-variable-data-store-cpt.php - evaluates to "3fa707c32a07b825b5380d9b38095cd6"

Line 274 of never uses cache
```
		if ( empty( $this->prices_array[ $price_hash ] ) ) {
```

IMO
- get_price_hash - line 420 should compute md5 on only the namespace and class of the class if a class object is supplied and not the whole class object 
```
foreach ( $wp_filter[ $filter_name ] as $priority => $callbacks ) {
    $price_hash[ $filter_name ][] = array_values( wp_list_pluck( $callbacks, 'function' ) );
}
```

### Steps to reproduce

**Add class and make sure it runs:**
```
<?php

class WooPricehashBug
{
    public $time;

    public function __construct()
    {
        $this->time = microtime(true);
        add_filter('woocommerce_variation_prices_sale_price', [$this, 'product_sale_price'], 10, 3);
    }

    public function product_sale_price($price, $variation, $product)
    {
        return $price;
    }
}

new WooPricehashBug();
```

**Set a breakpoint on line 274 of woocommerce/includes/data-stores/class-wc-product-variable-data-store-cpt.php**
**Observe transient cache never being used on line 274**

### WordPress Environment

Not needed

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by Konamiman**
#### The problem

`WC_Product_Variable_Data_Store_CPT` uses transients to cache information about the prices of all the variations for variable products. Since there are filters that can influence these prices, the generation of the hash key for the transient for a given product (`get_price_hash` method) includes information about the current usages of these filters: if `add_filter`s are added or removed for those, the next hash calculation will yield a different result, and this will effectively invalidate the cached prices.

However, while this approach is valid, the implementation has a flaw: when retrieving the information for a given filter usage (priority and callback), the entire callback is being serialized. For callbacks that are class methods (which is the most common case), this meant that the entire object containing the method is being serialized, and any change in a public property of that object meant a different serialization, thus a different hash, thus a prices transient that was effectively noy used.

This may or may not be desirable depending on the context. If a plugin is hooking on `woocommerce_variation_prices_price` and it returns a pice that depends on any varying factor (e.g. the current user), then it SHOULD also hook on `woocommerce_get_variation_prices_hash` to incorporate this factor into the price hash. Unfortunately plugins that don't follow this rule exist.

#### The solution

This pull request:

1. Introduces a new `CallbackUtil` class with a `get_callback_signature` method that will generate a proper signature string for any callback, irrespective of any state in the involved objects; and a `get_hook_callback_signatures` method that given a hook name will return an array of `priority => [callback signature1, callback signature 2...]`
2. Adds a `woocommerce_use_legacy_get_variations_price_hash` filter inside `WC_Product_Variable_Data_Store_CPT::get_price_hash` that defaults to returning `true`. If changed to return `false`,  `CallbackUtil::get_hook_callback_signatures` will be used on each of the relevant hooks instead of the old full callback serialization code.

Closes #37547.

### How to test the changes in this Pull Request:

1. Make sure that your store has at least one variable product (preferably with a large number of variations), take note of the product id.

2. Add the following code snippet to your server:

```php
class WooPriceHashTester
{
    public $random;

    public function __construct()
    {
        $this->random = microtime(true);
        add_filter('woocommerce_variation_prices_sale_price', [$this, 'product_sale_price'], 10, 3);
    }

    public function product_sale_price($price, $variation, $product)
    {
        return $price;
    }

	public static function test_price_hash($product_id, bool $delete_transients_first=false) {
		if($delete_transients_first) {
			delete_transient('wc_var_prices_' . $product_id);
		}

		$datastore = new class extends WC_Product_Variable_Data_Store_CPT {
			public function get_price_hash( &$product, $for_display = false ) {
				return parent::get_price_hash( $product, $for_display );
			}
		};

		$tester = new self();
		$product = wc_get_product( $product_id );
		$hash1 = $datastore->get_price_hash( $product );

		$tester->random++;
		$hash2 = $datastore->get_price_hash( $product );

		echo "Hash 1: $hash1\n";
		echo "Hash 2: $hash2\n";

		$time1 = microtime(true);
		echo "Reading price data... ";
		$datastore->read_price_data($product);
		$time2 = microtime(true);
		echo " done in " . round(($time2-$time1)*1000, 2) . " ms\n";
	}
}

add_filter( 'woocommerce_use_legacy_get_variations_price_hash', '__return_false' );
```

6. Run the following in your terminal: 

```php
wp eval 'WooPriceHashTester::test_price_hash(<product id>, true);'
```

The two hashes printed should be the same ones.

7. Now run the following command but passing `false` to the function. You should get the exact same hashes and this time it should have finished much faster.

8. Repeat 3 and 4 a few times, the hashes should always be the same ones.

Without these changes (or if you remove the hooking on `woocommerce_use_legacy_get_variations_price_hash`, or change it to return true) you would get a different hash every time, even within the same run of the command.

9. Go to the shop and verify that you can still see the product with the correct prices, place an order including a couple of variations, and verify that everything is correct in the generated order.

#### Testing the performance gain

Replace the previous snippet with this one:

```php
class CallbackUtilTest {
	public $random;

	public function __construct() {
		$this->random = rand();
		add_filter( 'woocommerce_variation_prices_price', [ $this, 'get_prices' ] );
	}

	public function get_prices( $value ) {
		return $value;
	}
}

add_filter( 'woocommerce_use_legacy_get_variations_price_hash', '__return_false' );

new CallbackUtilTest();
```

then run the following specifying the id of the variable product:

```
wp eval "wc_delete_product_transients(<product id>);"
```

...then the following a few times:

```
wp eval "\$x=microtime(true);wc_get_product(<product id>)->get_variation_prices();echo (int)((microtime(true)-\$x)*1000) . \"\n\";"
```

The second and subsequent executions of the last command will be much faster than the first one, without these changes all the executions would be as slow as the first one.

In a local test using a product with 800 variations (taken from a product export provided by a real WooCommerce user) this test yields a change in execution time for `get_variation_prices` of ~500ms to 40-50ms.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

**Review by joshuatf — DISMISSED** [review]
Thanks for working on this, @Konamiman!

I see how this solves the problem in the original issue, though I think this might open the door for a different set of problems that we might want to consider.

There are probably cases where changes in the underlying class state should affect the hash.  For example, a dynamic property in the class is used by the function callback we're serializing.  Additionally, if any changes to the method occur (not the name or arguments, but the code within the method itself), the hash will remain unchanged and we'll incorrectly continue to persist the existing hash.

**Comment by Konamiman** [comment]
> For example, a dynamic property in the class is used by the function callback we're serializing.

I think this goes beyond what we can reasonably track, and we could even say that a filter that depends on mutable state is an antipattern (from [the WordPress docs](https://developer.wordpress.org/plugins/hooks/): _"[filters] are meant to work in an isolated manner, and should never have side effects such as affecting global variables and output. Filters expect to have something returned back to them."_)

> if any changes to the method occur (not the name or arguments, but the code within the method itself), the hash will remain unchanged and we'll incorrectly continue to persist the existing hash.

But that's something that was already true in the old code (the hook callback signatures were being retrieved via `wp_list_pluck($callbacks, 'function')` and this doesn't capture method implementations).

As I see it the performance benefit of this change outweighs the risks. Worst case (not considering actual code changes in methods that are hook targets, since that wasn't covered by the old code either): a site having a plugin that uses the relevant hooks to modify the prices based on some dynamically changing property that _does_ actually change while the price data is cached; then we'll serve stale data for a while. I don't see this happening often.

**Comment by joshuatf** [comment]
>(from [the WordPress docs](https://developer.wordpress.org/plugins/hooks/): "[filters] are meant to work in an isolated manner, and should never have side effects such as affecting global variables and output. Filters expect to have something returned back to them.")

I think you might be misinterpreting this.  We're not talking about **affecting** global variables or output, we're talking about **reading** from an internal state.  These are two very different things.

If you think this is really rare, I'll reconsider my position on this.

>As I see it the performance benefit of this change outweighs the risks.

Can you show the performance benefits in this PR?  This is something we should be doing anyway and could help show the trade off is worthwhile.

**Comment by Konamiman** [comment]
> I think you might be misinterpreting this. We're not talking about affecting global variables or output, we're talking about reading from an internal state. These are two very different things.

Ok, fair enough. However the general idea from that document seems to be (as I see it at least) that values returned by filters should be consistent across requests; but admittedly that's debatable.

> If you think this is really rare, I'll reconsider my position on this.

Yes, but not only that, I think it's also a bit pointless to worry about that: code that hooks on the filter can use other kinds of mutable state (variables in other classes, globals, database records...) that won't be captured by the callback serialization anyway, even with the current code. So "mutable variable in the class that handles the hook" is just one particular case.

> Can you show the performance benefits in this PR? This is something we should be doing anyway and could help show the trade off is worthwhile.

Yes, I've updated the pull request description with information about this towards the end.

File: plugins/woocommerce/src/Utilities/CallbackUtil.php [hunk 1]
```diff
@@ -0,0 +1,118 @@
...
+		// phpcs:disable WordPress.PHP.DiscouragedPHPFunctions.serialize_serialize
+
+		if ( ! is_object( $wp_filter[ $hook_name ] ) || ! is_array( $wp_filter[ $hook_name ]->callbacks ?? null ) ) {
+			return array( 0 => array( serialize( $wp_filter[ $hook_name ] ) ) );
+		}
+
+		$result = array();
+
+		foreach ( $wp_filter[ $hook_name ]->callbacks as $priority => $priority_callbacks ) {
+			$result[ $priority ] = self::is_valid_wp_filter_priority_entry( $priority, $priority_callbacks )
```
Comment (joshuatf) [inline plugins/woocommerce/src/Utilities/CallbackUtil.php]: Is the check to `is_valid_wp_filter_priority_entry()` necessary?  I'm not opposed to some extra safety, though I would think there would be a lot of other issues if what's stored in global filters does not have valid priorities or callbacks.

There's not much harm in keeping this to the code itself, but it does add overhead in understanding what's happening here if this is already reasonably protected.

**Review by joshuatf — COMMENTED** [review]
>However the general idea from that document seems to be (as I see it at least) that values returned by filters should be consistent across requests; but admittedly that's debatable.

I don't believe that is what the document implies as mentioned above.  If WP expected a pure function that did not take into account state (which is rarely ever the case, even if we look at WC alone), at a minimum it would encourage use of static functions.  While I agree that it would better if this were the case, it's not very realistic.

>Yes, but not only that, I think it's also a bit pointless to worry about that: code that hooks on the filter can use other kinds of mutable state (variables in other classes, globals, database records...) that won't be captured by the callback serialization anyway, even with the current code. So "mutable variable in the class that handles the hook" is just one particular case.

Fair point that there are many mutable states not accounted for, so let's just consider the ones that are currently accounted for.

The instance itself is currently accounted for and I believe some plugins take advantage of that.  For example, [WooCommerce Memberships](https://woocommerce.com/products/woocommerce-memberships/) in our marketplace relies on a class property `$should_apply_discounts` in the `woocommerce_variation_prices_price` hook.  I believe the implementation in this PR would break that implementation.

There are many similar cases on the `woocommerce_variation_prices_price` filter alone ([Price By Country](https://woocommerce.com/products/price-by-country/), [Restaurant for WooCommerce](https://woocommerce.com/products/restaurant-for-woocommerce/), and many more) just in our marketplace.

Going back to the original issue this PR tries to solve, is there a way we can prevent or strip those public properties in the offending classes instead of ignoring them for all classes where they might be needed?  If not, let's test with the above plugins and others that use these filters and make sure we're not breaking them or issue dev advisories if this trade off in BC is worth the performance gains.

**Comment by Konamiman** [comment]
@joshuatf I have manually tested the Membership plugins (logging in and out users with and without membership discounts) and it works fine with this branch. Looking at the code of that plugin, tuns out that it hooks on `woocommerce_get_variation_prices_hash` to produce a different cache hash for each user - which is the proper thing to do if the prices vary by user.

The Price By Country and Restaurant for WooCommerce, on the other hand, don't hook on that filter. So indeed, a developer advisory stating that plugins hooking on `woocommerce_variation_prices_price` should also hook on `woocommerce_get_variation_prices_hash` if the returned prices vary by user or by any other internal parameter seems appropriate (and mentioning this too in code comments near  the point where the filters are fired could be a good idea too).

Additionally, to be extra safe, we could add a new filter (or a setting?) that allows reverting to the old behavior (in spite of the performance degradation) for cases where a given store is using a plugin that is affected by the new behavior.

File: plugins/woocommerce/src/Utilities/CallbackUtil.php (hunk 1 above)
Comment (Konamiman) [reply plugins/woocommerce/src/Utilities/CallbackUtil.php]: Fair enough. Removed.

**Comment by Konamiman** [comment]
Pull request updated with the following changes:

- Removed `CallbackUtil::is_valid_wp_filter_priority_entry` and usages.
- `woocommerce_use_legacy_get_variations_price_hash` filter that allows reverting to the old behavior.
- Docblocks for the filters in `WC_Product_Variable_Data_Store_CPT` added, with prominent warning in `woocommerce_variation_prices_price` to also hook on `woocommerce_get_variation_prices_hash` for prices that have a varying factor.
- `CallbackUtil::get_callback_signature` now uses a reflection-based approach to get consistent(ish) signatures for closures.

File: plugins/woocommerce/includes/data-stores/class-wc-product-variable-data-store-cpt.php [hunk 2]
```diff
@@ -530,7 +638,8 @@ public function child_has_weight( $product ) {
 		$format   = array_fill( 0, count( $children ), '%d' );
 		$query_in = '(' . implode( ',', $format ) . ')';
 
-		return null !== $wpdb->get_var( $wpdb->prepare( "SELECT post_id FROM $wpdb->postmeta WHERE meta_key = '_weight' AND meta_value > 0 AND post_id IN {$query_in}", $children ) ); // @codingStandardsIgnoreLine.
+		// phpcs:ignore WordPress.DB
```
Comment (jorgeatorres) [inline plugins/woocommerce/includes/data-stores/class-wc-product-variable-data-store-cpt.php]: Can we ignore the specific set of rules that is problematic, and not the whole namespace? Same in other places.

File: plugins/woocommerce/src/Utilities/CallbackUtil.php [hunk 3]
```diff
@@ -0,0 +1,120 @@
...
+	 *
+	 * This method normalizes callbacks into consistent string representations,
+	 * regardless of changes in dynamic properties in callback instances.
+	 *
+	 * @param callable|mixed $callback A PHP callback.
+	 * @return string Normalized callback signature.
+	 *
+	 * @since 10.4.0
+	 */
+	public static function get_callback_signature( $callback ): string {
```
Comment (jorgeatorres) [inline plugins/woocommerce/src/Utilities/CallbackUtil.php:24]: Noting that for anonymous classes, similar to the prior situation with anonymous functions, it'll return a signature that changes every time.

I believe this is not a commonly used feature, but I just wanted to note it so we do a quick check, at least against the Marketplace.

File: plugins/woocommerce/src/Utilities/CallbackUtil.php [hunk 4]
```diff
@@ -0,0 +1,120 @@
...
+	public static function get_hook_callback_signatures( string $hook_name ): array {
+		global $wp_filter;
+
+		if ( ! isset( $wp_filter[ $hook_name ] ) ) {
+			return array();
+		}
+
+		// phpcs:disable WordPress.PHP.DiscouragedPHPFunctions.serialize_serialize
+
+		if ( ! is_object( $wp_filter[ $hook_name ] ) || ! is_array( $wp_filter[ $hook_name ]->callbacks ?? null ) ) {
```
Comment (jorgeatorres) [inline plugins/woocommerce/src/Utilities/CallbackUtil.php]: Is this really something that can happen? I'm not necessarily against the check but if `$wp_filter` or one of the `WP_Hook` instances in it is broken, we could probably say "the hook" is broken and some other things will probably malfunction anyway.

I'm also unsure why the return value would be what we see here in this case. Why do you think we should serialize it like that?

File: plugins/woocommerce/tests/php/src/Utilities/CallbackUtilTest.php [hunk 5]
```diff
@@ -0,0 +1,377 @@
...
+
+		$this->assertIsArray( $signatures );
+		$this->assertEmpty( $signatures );
+	}
+
+	/**
+	 * @testdox `get_hook_callback_signatures` should return signatures for all callbacks on a hook.
+	 */
+	public function test_get_hook_callback_signatures_with_multiple_callbacks() {
+		$hook_name = 'test_hook_' . wp_rand();
```
Comment (jorgeatorres) [inline plugins/woocommerce/tests/php/src/Utilities/CallbackUtilTest.php]: Any reason the hook names need to use `wp_rand()`? Not saying this is the heaviest function (though it's not simple either), but seems a bit unnecessary.

**Review by jorgeatorres — CHANGES_REQUESTED** [review]
Thanks for working on this @Konamiman!

I left some minor feedback, but I share some of @joshuatf's concerns. Can we do a quick check on the marketplace to see how plugins use the hash filter and whether they also implement `woocommerce_get_variation_prices_hash` or not)? Happy to assist with this if you need me to.

Overall, I like the new `CallbackUtil` and how a hash based on signatures will help performance in most cases, but checking `all-plugins` for peace of mind will be useful. This could also help inform whether we need to make this a setting (even if temporarily) or whether the filter should default to `true` or `false`.

Also, given 10.4 is past feature freeze, maybe it'd be a good opportunity to post that dev advisory about the prices hash filter before 10.5 and _then_ we enable this new functionality (once reviewed) in 10.5. Even if we don't end up merging this PR as is, reminding developers of how to handle this caching seems like a good plan. What do you think?

File: plugins/woocommerce/src/Utilities/CallbackUtil.php (hunk 3 above)
Comment (Konamiman) [reply plugins/woocommerce/src/Utilities/CallbackUtil.php:24]: For consistency I have modified it to use a reflection based approach, as it was doing already for closures.

File: plugins/woocommerce/src/Utilities/CallbackUtil.php (hunk 4 above)
Comment (Konamiman) [reply plugins/woocommerce/src/Utilities/CallbackUtil.php]: Agreed, that's overkill. Removed.

File: plugins/woocommerce/tests/php/src/Utilities/CallbackUtilTest.php (hunk 5 above)
Comment (Konamiman) [reply plugins/woocommerce/tests/php/src/Utilities/CallbackUtilTest.php]: No specific reason. I have changed these to `uniqid()`.

File: plugins/woocommerce/src/Utilities/CallbackUtil.php [hunk 6]
```diff
@@ -0,0 +1,136 @@
...
+		}
+
+		if ( is_object( $callback ) ) {
+			// Invokable object.
+			try {
+				return self::get_invokable_signature( $callback );
+			} catch ( \Exception $e ) {
+				return get_class( $callback ) . '::__invoke';
+			}
+		}
```
Comment (jorgeatorres) [inline plugins/woocommerce/src/Utilities/CallbackUtil.php:57]: Do we really need special handling for invocable objects? Why not assume (without using reflection) that it's similar to the case `[ class, '__invoke' ]`?

I might be missing something, though, so happy to be corrected 😊.

File: plugins/woocommerce/src/Utilities/CallbackUtil.php [hunk 7]
```diff
@@ -0,0 +1,136 @@
...
+	 *
+	 * @param object $invokable The invokable object to generate a signature for.
+	 * @return string Signature in the format 'ClassName::__invoke@filename:startLine-endLine'.
+	 * @throws \ReflectionException If reflection fails.
+	 */
+	private static function get_invokable_signature( object $invokable ): string {
+		$reflection = new \ReflectionMethod( $invokable, '__invoke' );
+		$file       = $reflection->getFileName();
+		$start      = $reflection->getStartLine();
+		$end        = $reflection->getEndLine();
```
Comment (jorgeatorres) [inline plugins/woocommerce/src/Utilities/CallbackUtil.php]: Using start and end lines can actually result in unnecessary cache invalidation if the code is just moved around. Is that intended? We're obviously not doing that for global functions, for example.

File: plugins/woocommerce/tests/php/src/Utilities/CallbackUtilTest.php [hunk 8]
```diff
@@ -0,0 +1,374 @@
...
+
+		$this->assertIsArray( $signatures );
+		$this->assertEmpty( $signatures );
+	}
+
+	/**
+	 * @testdox `get_hook_callback_signatures` should return signatures for all callbacks on a hook.
+	 */
+	public function test_get_hook_callback_signatures_with_multiple_callbacks() {
+		$hook_name = 'test_hook_' . uniqid();
```
Comment (jorgeatorres) [inline plugins/woocommerce/tests/php/src/Utilities/CallbackUtilTest.php]: I mentioned this before, but my point was that we don't need this to be unique or random. Why not just use a hardcoded string?

We're removing all callbacks before the test finishes so isolation is not broken. And even then, we could just use a hardcoded string that is different in each test.

What do you think?

**Review by jorgeatorres — CHANGES_REQUESTED** [review]
Hi @Konamiman!

Thanks for making the changes. I left some additional comments, but nothing too serious.

I like the change in default for the legacy filter to `true` so we can roll this out more carefully. Just to confirm, the plan we discussed includes merging this (once approved), writing a dev advisory about the hash filter and propose a date and WC version for the new logic to be switched on by default. Is that correct?

File: plugins/woocommerce/src/Utilities/CallbackUtil.php (hunk 6 above)
Comment (Konamiman) [reply plugins/woocommerce/src/Utilities/CallbackUtil.php:57]: As you pointed out in a previous comment, for anonymous classes the signature would be different for each request, so we need to use the "class name+start+end" approach. Which as you mention in another comment, will change if the code is moved around; but I think that goes beyond what we can reasonably track, and the consequence if the code is moved (which shouldn't happen often anyway) is a one time unneeded cache invalidation, which is not a big issue.

We could go and try to check if the class is anonymous, but that would require using reflection anyway.

Comment (Konamiman) [reply plugins/woocommerce/src/Utilities/CallbackUtil.php:57]: Anyway: I have tweaked the method to use the class name when it's not anonymous. But for anonymous classes, I think the "class name+start+end" approach is the best we can reasonably do.

**Comment by Konamiman** [comment]
> the plan we discussed includes merging this (once approved), writing a dev advisory about the hash filter and propose a date and WC version for the new logic to be switched on by default. Is that correct?

Yes, that's the plan. As for the version, 11.0 should give plenty of time for extensions to adjust; and meanwhile, whoever wants to use the new system can use the filter.

**Review by jorgeatorres — APPROVED** [review]
LGTM. Thank you @Konamiman!

I tested various (filter, callback) pairs including anonymous functions, public methods, etc. and confirmed the variation in the product hashes and the use of the transient/cache.

I'm still worried about breakage, even though the prior implementation was flawed (as you say, ignoring "internal state" for functions but not for classes, for example), but I like the plan of maintaining the current implementation for now, announcing the change and the use of the hash filter so extensions can adopt it, etc.

One thing I noticed, though it's unrelated to this PR, is that the `wc_var_prices_<id>` transient can get very large if there's variability in the callbacks associated to the hook. With the new implementation this is less likely to happen, but it could still happen, and given the transient's expiration is reset when the hash changes to a new one, the option will continue growing and will not be invalidated. I'll open an issue about this so we can investigate.
