### PR TITLE
CYS - Core: fix font load when user opts out of tracking

### LINKED ISSUE #45138: [CYS - Core] Font Preview and Site Preview Fail to load fonts when user opts out of tracking
#44532 adds a specific font pairing when the user doesn't allow tracking. Even if the user selects these fonts, these latter aren't being loaded.

### PR DESCRIPTION
**Pull request by gigitux**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

As a spec, we had to add the "Instrument Sans + Jost" font pair. The issue is that these fonts are loaded in a different variation of the TT4. Currently, we are using the default one. With the default variation, [only Inter and Cargo fonts are loaded.](https://github.com/WordPress/twentytwentyfour/blob/trunk/theme.json#L198).

Adding the "Instrument Sans + Jost" font pair could be complex. Should we work on it?

cc @verofasulo @nefeline @albarin 

EDIT: @verofasulo confirmed that we can avoid to work to implement the  "Instrument Sans + Jost" font pair. p1709138640335519/1709039848.913899-slack-C053716F2H2

### Changes proposed in this Pull Request:

Closes #45138.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Enable the WooCommerce Beta Tester plugin if you don't have it enabled yet
2. On your Dashboard, head over to Tools > WCA Test Helper > Features and enable the `customize-store`
3. Ensure you have the Gutenberg plugin installed from the latest trunk (or install it from this zip file: [gutenberg.zip](https://github.com/woocommerce/woocommerce/files/14384613/gutenberg.zip)
4. Visit `/wp-admin/admin.php?page=wc-settings&tab=advanced&section=woocommerce_com` and ensure that the `Allow usage of WooCommerce to be tracked` **isn't** enabled.
5. Visit the `/wp-admin/admin.php?page=wc-admin&path=/customize-store`.
6. Follow the process.
7. On the sidebar, click on `Choose your Fonts`. 
8. Ensure that only `Cardo/System sans-serif` and `Inter/Cardo` are visible.
9. For each preview, ensure that the right fonts are rendered:

| Header | Header |
|--------|--------|
|image| | 

10. Visit `/wp-admin/admin.php?page=wc-settings&tab=advanced&section=woocommerce_com` and enable the tracking.
11. Visit the `/wp-admin/admin.php?page=wc-admin&path=/customize-store`.
12. Follow the process.
13. On the sidebar, click on `Choose your Fonts`.
14. Ensure that more than two font pairs are visible.
15. For each preview, ensure that the right fonts are rendered.

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [x] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

CYS - Core: fix font load when user opts out of tracking.

#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce-admin/client/customize-store/assembler-hub/sidebar/global-styles/font-pairing-variations/constants.ts [hunk 1]
```diff
@@ -558,14 +523,14 @@ export const FONT_PAIRINGS_WHEN_USER_DID_NOT_ALLOW_TRACKING = [
 			elements: {
 				heading: {
 					typography: {
-						fontFamily: 'var(--wp--preset--font-family--inter)',
+						fontFamily: 'var(--wp--preset--font-family--body)',
```
Comment (gigitux) [inline plugins/woocommerce-admin/client/customize-store/assembler-hub/sidebar/global-styles/font-pairing-variations/constants.ts:529]: We have to use the variable defined by the theme: https://github.com/WordPress/twentytwentyfour/blob/trunk/theme.json#L215

File: plugins/woocommerce-admin/client/customize-store/assembler-hub/sidebar/global-styles/font-pairing-variations/constants.ts [hunk 2]
```diff
@@ -558,14 +523,14 @@ export const FONT_PAIRINGS_WHEN_USER_DID_NOT_ALLOW_TRACKING = [
...
 						fontStyle: 'normal',
 						fontWeight: '300',
 					},
 				},
 			},
 			typography: {
-				fontFamily: 'var(--wp--preset--font-family--cardo)',
+				fontFamily: 'var(--wp--preset--font-family--heading)',
```
Comment (gigitux) [inline plugins/woocommerce-admin/client/customize-store/assembler-hub/sidebar/global-styles/font-pairing-variations/constants.ts:536]: Same here: https://github.com/WordPress/twentytwentyfour/blob/trunk/theme.json#L240

**Review by albarin — APPROVED** [review]
👌

**Review by albarin — APPROVED** [review]
