### PR TITLE
fix: Validate sold individually products in shortcode cart/checkout

### LINKED ISSUE #62269: Sold individually is not enforced in the shortcode cart and checkout pages
**Describe the bug**

Currently if you add a simple product to your cart twice and then enable sold individually the shortcode cart and checkout pages will not remove the extra one. Allowing customers to place orders with multiple of the same product.

If the customer visites either the blocks cart or checkout pages the extra item is automatically removed

**Expected behavior**

Shortcode cart and checkout pages should remove extra items when sold individually is enabled.

**How to simulate**

* Create a simple product
* As a customer add that product to your cart twice
* Now check the `Sold Individually` option on wp-admin > Products > Edit product > Inventory
* Go to the shortcode cart or checkout pages
* Notice the quantity is gone but the total is for two of them

### PR DESCRIPTION
**Pull request by faisuc**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Fixed a bug where shortcode cart and checkout pages did not validate sold individually products. When a product was added to the cart with quantity greater than 1, and then marked as "Sold Individually" in the admin, the shortcode pages would display quantity as 1 but calculate totals for the original quantity.

**Changes:**
- Added `check_cart_item_sold_individually()` method to `WC_Cart` class to validate and fix sold individually products
- Integrated the validation into `check_cart_items()` method which runs on shortcode cart and checkout pages
- Added test coverage to verify the fix works correctly

The fix ensures that when a product is marked as "Sold Individually" after being added to the cart, the quantity is automatically reduced to 1 and totals are recalculated correctly, matching the behavior of blocks cart and checkout pages.

Closes #62269

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [x] Patch

#### Type

-   [x] Fix - Fixes an existing bug

#### Message

Fixed sold individually validation on shortcode cart and checkout pages. Products marked as "Sold Individually" after being added to cart now have quantity automatically reduced to 1 with correct totals calculation.

</details>

### CODE REVIEW

**Comment by straku** [comment]
@faisuc Sorry for not taking the time to look at it recently. Unfortunately, I am starting my AFK tomorrow and will be back Jan 5th. I will make sure to look at the PR at this time, unless someone else from the team finds the time to do it sooner. Sorry again!

**Review by ralucaStan — COMMENTED** [review]
@faisuc thank you so much for your contribution. 

I tried replicating the bug on trunk, and I couldn't see it surfacing anymore. The total was correct, shown for 1 item.

Could you also test on trunk? If you also can't replicate, we can keep only the tests from this PR. Let me know.

Thank you for your valuable help.

**Comment by faisuc** [comment]
Hi @ralucaStan,

I tested this on trunk and the bug is still there. On trunk, `check_cart_items()` only calls [check_cart_item_validity()](https://github.com/woocommerce/woocommerce/blob/922cc40ed9c61c15c73231d53ea939768c56b731/plugins/woocommerce/includes/class-wc-cart.php#L741C3-L741C47) and [check_cart_item_stock()](https://github.com/woocommerce/woocommerce/blob/922cc40ed9c61c15c73231d53ea939768c56b731/plugins/woocommerce/includes/class-wc-cart.php#L748). It doesn't check sold individually. So if you add a product with qty 2, then enable "Sold Individually" in admin, visiting shortcode cart or checkout pages leaves the quantity at 2 with incorrect totals.

Blocks and mini-cart work because they use the Store API, which validates sold individually via `QuantityLimits` (sets `editable => false` for sold individually products) and `CartController::validate_cart_item()` (throws an exception if qty > 1). Shortcode pages don't have this check.

I ran a test on trunk: add product with qty 2, enable sold individually, then call `check_cart_items()`. Quantity stays 2 and subtotal stays 20 (should be 10). This confirms the bug.

This PR adds `check_cart_item_sold_individually()` to `check_cart_items()`, following the same pattern as the other validation methods. It loads a fresh product instance to get the current sold individually setting (cart items can have cached product objects), reduces quantity to 1, and shows an error notice. All tests pass, including the new one covering this scenario.

If you're not seeing it, are you testing on actual shortcode pages ([woocommerce_cart] or [woocommerce_checkout])? And did you add the product with qty > 1 before enabling sold individually? Thanks for the review, and let me know if I’m missing something.

**Comment by ralucaStan** [comment]
@faisuc I was able to replicate it in the cart shortcode. I'll have to handover this PR to @straku, and he'll continue with the review once he's back.

Thank you for your patience.

**Comment by faisuc** [comment]
Thanks for confirming. I'll wait for @straku's review.

File: plugins/woocommerce/includes/class-wc-cart.php [hunk 1]
```diff
@@ -789,6 +796,39 @@ public function check_cart_item_validity() {
 		return $return;
 	}
 
+	/**
+	 * Looks through cart items and ensures sold individually products have quantity of 1.
+	 *
+	 * @return bool|WP_Error
```
Comment (opr) [inline plugins/woocommerce/includes/class-wc-cart.php:836]: This needs a `@since 10.7.0` annotation - it is likely this will miss the 10.6 code freeze as I am AFK until after it happens.

File: plugins/woocommerce/includes/class-wc-cart.php [hunk 2]
```diff
@@ -789,6 +796,39 @@ public function check_cart_item_validity() {
...
+		$return = true;
+
+		foreach ( $this->get_cart() as $cart_item_key => $values ) {
+			$product = $values['data'];
+
+			if ( ! $product || ! $product->exists() ) {
+				continue;
+			}
+
+			$product_id = $values['variation_id'] ? $values['variation_id'] : $values['product_id'];
```
Comment (opr) [inline plugins/woocommerce/includes/class-wc-cart.php]:
```suggestion
			$product_id    = $values['variation_id'] ? $values['variation_id'] : $values['product_id'];
```

File: plugins/woocommerce/includes/class-wc-cart.php [hunk 3]
```diff
@@ -789,6 +796,39 @@ public function check_cart_item_validity() {
...
+			$fresh_product = wc_get_product( $product_id );
```
Comment (opr) [inline plugins/woocommerce/includes/class-wc-cart.php]: Minor nitpick but `$fresh_product` could be improved to be more descriptive, it could be `$product_to_check` or similar

File: plugins/woocommerce/includes/class-wc-cart.php [hunk 4]
```diff
@@ -789,6 +796,39 @@ public function check_cart_item_validity() {
...
+
+			if ( ! $fresh_product || ! $fresh_product->exists() ) {
+				continue;
+			}
+
+			if ( $fresh_product->is_sold_individually() && $values['quantity'] > 1 ) {
+				$this->cart_contents[ $cart_item_key ]['data'] = $fresh_product;
+				$this->set_quantity( $cart_item_key, 1, false );
+				/* translators: %s: product name */
+				$return = new WP_Error( 'sold-individually', sprintf( __( 'You can only have 1 %s in your cart.', 'woocommerce' ), $fresh_product->get_name() ) );
```
Comment (opr) [inline plugins/woocommerce/includes/class-wc-cart.php]: This is overwriting `$return` on each loop so only the last product will have a notice added, do you instead want to set up a `WP_Error` outside the loop and `->add` to it ?

**Review by opr — CHANGES_REQUESTED** [review]
Hi thanks for the work so far, and for your patience while we review it! I suggested a few changes, let me know what you think 🙇🏼

**Comment by faisuc** [comment]
@opr Thanks for the review. Added the `@since 10.7.0` tag, aligned `$product_id`, renamed `$fresh_product` to `$product_to_check`, and switched to a single `WP_Error` outside the loop with `->add()` so we report all sold-individually items. Also updated `check_cart_items()` to loop over `get_error_messages()` so each product gets its own notice.

**Comment by opr** [comment]
> @opr Thanks for the review. Added the `@since 10.7.0` tag, aligned `$product_id`, renamed `$fresh_product` to `$product_to_check`, and switched to a single `WP_Error` outside the loop with `->add()` so we report all sold-individually items. Also updated `check_cart_items()` to loop over `get_error_messages()` so each product gets its own notice.


Thanks a lot for the changes. Unfortunately I'm now AFK and due to capacity constraints it's not likely that we'll be able to review this until 23rd February at the earliest, so I appreciate your patience here. Thank you.

File: plugins/woocommerce/includes/class-wc-cart.php [hunk 5]
```diff
@@ -820,6 +829,40 @@ public function check_cart_item_validity() {
...
+			}
+
+			$product_id       = $values['variation_id'] ? $values['variation_id'] : $values['product_id'];
+			$product_to_check = wc_get_product( $product_id );
+
+			if ( ! $product_to_check || ! $product_to_check->exists() ) {
+				continue;
+			}
+
+			if ( $product_to_check->is_sold_individually() && $values['quantity'] > 1 ) {
```
Comment (opr) [inline plugins/woocommerce/includes/class-wc-cart.php:855]: Are you assuming that `$values['data']->is_sold_individually()` can be stale here, is that why it's being overwritten? If that assumption isn't being made, then this whole method could be simplified to:

```php
foreach ( $this->get_cart() as $cart_item_key => $values ) {
    $product = $values['data'];

    if ( ! $product || ! $product->exists() ) {
        continue;
    }

    if ( $product->is_sold_individually() && $values['quantity'] > 1 ) {
        $this->set_quantity( $cart_item_key, 1, false );
        /* translators: %s: product name */
        $errors->add( 'sold-individually', sprintf( __( 'You can only have 1 %s in your cart.', 'woocommerce' ), $product->get_name() ) );
    }
}
```

`$values['data']` would already be the variant product if set (set in `class-wc-cart-session.php:146`)

File: plugins/woocommerce/tests/php/includes/class-wc-cart-test.php [hunk 6]
```diff
@@ -112,6 +112,66 @@ public function test_order_again_enforces_sold_individually_for_variations() {
...
+		$this->assertNotFalse( $cart_item_key, 'Product should be added to cart' );
+
+		$cart_contents = WC()->cart->get_cart();
+		$this->assertCount( 1, $cart_contents, 'Cart should have one item' );
+		$cart_item = array_values( $cart_contents )[0];
+		$this->assertEquals( 2, $cart_item['quantity'], 'Cart item should have quantity 2' );
+
+		WC()->cart->calculate_totals();
+		$initial_subtotal = WC()->cart->get_subtotal();
+		$initial_quantity = $cart_item['quantity'];
```
Comment (opr) [inline plugins/woocommerce/tests/php/includes/class-wc-cart-test.php]: Not strictly necessary for this test as it's just testing core WC functionality

File: plugins/woocommerce/tests/php/includes/class-wc-cart-test.php [hunk 7]
```diff
@@ -112,6 +112,66 @@ public function test_order_again_enforces_sold_individually_for_variations() {
...
+
+		$cart_contents_after = WC()->cart->get_cart();
+		$this->assertCount( 1, $cart_contents_after, 'Cart should still have one item' );
+		$cart_item_after = array_values( $cart_contents_after )[0];
+		$this->assertEquals( 1, $cart_item_after['quantity'], 'Cart item quantity should be reduced to 1' );
+
+		WC()->cart->calculate_totals();
+		$final_subtotal = WC()->cart->get_subtotal();
+
+		$this->assertEquals( $initial_subtotal / $initial_quantity, $final_subtotal, 'Cart subtotal should be recalculated based on quantity 1', 0.01 );
```
Comment (opr) [inline plugins/woocommerce/tests/php/includes/class-wc-cart-test.php]: This also seems to be testing core WC functionality rather than the specific behaviour of reducing sold individually qty to 1.

File: plugins/woocommerce/tests/php/includes/class-wc-cart-test.php [hunk 8]
```diff
@@ -112,6 +112,66 @@ public function test_order_again_enforces_sold_individually_for_variations() {
...
+		$product->set_regular_price( 10 );
+		$product->save();
+
+		$cart_item_key = WC()->cart->add_to_cart( $product->get_id(), 2 );
+		$this->assertNotFalse( $cart_item_key, 'Product should be added to cart' );
+
+		$cart_contents = WC()->cart->get_cart();
+		$this->assertCount( 1, $cart_contents, 'Cart should have one item' );
+		$cart_item = array_values( $cart_contents )[0];
+		$this->assertEquals( 2, $cart_item['quantity'], 'Cart item should have quantity 2' );
```
Comment (opr) [inline plugins/woocommerce/tests/php/includes/class-wc-cart-test.php]: This is testing add to cart functionality, we could skip this

File: plugins/woocommerce/tests/php/includes/class-wc-cart-test.php [hunk 9]
```diff
@@ -112,6 +112,66 @@ public function test_order_again_enforces_sold_individually_for_variations() {
...
+
+		$found_notice = false;
+		foreach ( $notices['error'] as $notice ) {
+			$notice_text = is_array( $notice ) && isset( $notice['notice'] ) ? $notice['notice'] : (string) $notice;
+			if ( strpos( $notice_text, 'You can only have 1' ) !== false ) {
+				$found_notice = true;
+				break;
+			}
+		}
+		$this->assertTrue( $found_notice, 'Should find notice about sold individually quantity limit' );
```
Comment (opr) [inline plugins/woocommerce/tests/php/includes/class-wc-cart-test.php]: This could be simplified to

```php
$error_notices = wp_list_pluck( wc_get_notices( 'error' ), 'notice' );
$this->assertContains(
    sprintf( 'You can only have 1 %s in your cart.', $product->get_name() ),
    $error_notices
);
```

**Review by opr — CHANGES_REQUESTED** [review]
@faisuc thanks I pushed a lint change, hope you don't mind. Also some other comments added in line.

It would also be nice to have a test that verifies that a sold-individually product that already has quantity=1 doesn't trigger an error or get modified, just to be safe.

The direction of this PR is great and I think we can get it merged as soon as the points I mentioned are addressed.

**Comment by faisuc** [comment]
@opr Thanks for the review and the lint change.

I’ve applied your test suggestions and added a test for sold-individually with qty=1. On the cart method, we do assume `$values['data']` can be stale when the product is changed after it’s in the cart, so I kept the re-fetch and overwrite. The existing test would fail without it.

**Review by opr — APPROVED** [review]
> @opr Thanks for the review and the lint change.
> 
> I’ve applied your test suggestions and added a test for sold-individually with qty=1. On the cart method, we do assume `$values['data']` can be stale when the product is changed after it’s in the cart, so I kept the re-fetch and overwrite. The existing test would fail without it.

Thanks for clarifying!

Only thing I'd suggest in that case is a short inline comment on the overwrite line explaining why it's necessary. Something like:

```php
// Re-fetch and overwrite to reflect product changes made after item was added to cart.
```

Just to prevent a refactor cleaning this up

**Comment by faisuc** [comment]
@opr Added the comment you suggested.

**Review by opr — APPROVED** [review]
@faisuc Thank you for the PR and for your patience while we reviewed! I'm happy to approve this now! 😎
