### PR TITLE
Use CRUD search helper in admin products table

### LINKED ISSUE #18757: SKUs are no longer searchable in WP Admin
By design or mistake?

## Steps to reproduce the issue

1. Search for a product SKU in the WP Admin

## Expected/actual behavior

When I follow those steps, I see no search results. 

I was expecting to see the same results as 3.2.6, the appropriate products with assigned sku. 

Works with text, numbers, and symbols in 3.2.6 http://cld.wthms.co/885DY8

### PR DESCRIPTION
**Pull request by mikejolley**
Closes #18757

Test by doing some searches for partial SKUs on parent/variations.

### CODE REVIEW

File: includes/admin/list-tables/class-wc-admin-list-table-products.php [hunk 1]
```diff
@@ -453,50 +452,23 @@ protected function query_filters( $query_vars ) {
...
-
-		$search_ids = array_filter( array_unique( array_map( 'absint', $search_ids ) ) );
-
-		if ( count( $search_ids ) > 0 ) {
-			$where = str_replace( 'AND (((', "AND ( ({$wpdb->posts}.ID IN (" . implode( ',', $search_ids ) . ')) OR ((', $where );
-		}
-
-		return $where;
-	}
+	public function sku_search( $where ) {}
```
Comment (claudiulodro) [inline includes/admin/list-tables/class-wc-admin-list-table-products.php]: I think this PR should also remove the hook that hooks this method in the constructor of this class.

Just to be safe, this should also probably return unchanged `$where` (since it used to be a filter).
