### PR TITLE
Stock sorting issue when Yoast installed

### LINKED ISSUE #23587: Sorting issue when Yoast SEO is active
**Describe the bug**
There is a conflict when sorting product if the store uses the SEO by yoast plugin. I'm attaching screenshots of the before/after yoast activation. I fixed the issue by removing the `add_filter( 'the_posts', array( $this, 'remove_ordering_args' ) );` and placing the `remove_ordering_args` function inside the `add_filter( 'posts_clauses', array( $this, 'posts_clauses' ), 10, 2 );` function in the first line. 

**To Reproduce**
1. Create new installation.
2. Install WooCommerce with Storefront and demo content.
3. Check and see if the ordering works  on the frontend and backend.
4. Install Yoast SEO
5. Check and see if the ordering works on the frontend and backend.

**Screenshots**
Yoast active + Price ASC
Yoast active + Price DESC
Yoast deactive + Price ASC
Yoast deactive + Price DESC

**Expected behavior**
Sorting should work as expected. 

**WordPress Environment**
<details>
```
`
### WordPress Environment ###

WordPress address (URL): http://localhost/las
Site address (URL): http://localhost/las
WC Version: 3.6.2
Log Directory Writable: ✔
WP Version: 5.1.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.37 (Unix) OpenSSL/1.0.2q PHP/7.3.1 mod_perl/2.0.8-dev Perl/v5.16.3
PHP Version: 7.3.1
PHP Post Max Size: 300 GB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.45.0
OpenSSL/1.0.2q

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.1.37-MariaDB
Max Upload Size: 300 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.6.2
WC Database Prefix: las_
MaxMind GeoIP Database: ✔
Total Database Size: 3.42MB
Database Data Size: 2.43MB
Database Index Size: 0.99MB
las_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
las_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
las_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
las_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
las_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
las_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB
las_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
las_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
las_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
las_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
las_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
las_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
las_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
las_woocommerce_log: Data: 0.02MB + Index: 0.02MB
las_aws_index: Data: 0.02MB + Index: 0.00MB
las_commentmeta: Data: 0.02MB + Index: 0.03MB
las_comments: Data: 0.06MB + Index: 0.09MB
las_links: Data: 0.02MB + Index: 0.02MB
las_nf3_actions: Data: 0.02MB + Index: 0.00MB
las_nf3_action_meta: Data: 0.02MB + Index: 0.00MB
las_nf3_chunks: Data: 0.02MB + Index: 0.00MB
las_nf3_fields: Data: 0.02MB + Index: 0.00MB
las_nf3_field_meta: Data: 0.02MB + Index: 0.00MB
las_nf3_forms: Data: 0.02MB + Index: 0.00MB
las_nf3_form_meta: Data: 0.02MB + Index: 0.00MB
las_nf3_objects: Data: 0.02MB + Index: 0.00MB
las_nf3_object_meta: Data: 0.02MB + Index: 0.00MB
las_nf3_relationships: Data: 0.02MB + Index: 0.00MB
las_nf3_upgrades: Data: 0.02MB + Index: 0.00MB
las_options: Data: 1.48MB + Index: 0.05MB
las_postmeta: Data: 0.05MB + Index: 0.03MB
las_posts: Data: 0.06MB + Index: 0.06MB
las_termmeta: Data: 0.02MB + Index: 0.03MB
las_terms: Data: 0.02MB + Index: 0.03MB
las_term_relationships: Data: 0.02MB + Index: 0.02MB
las_term_taxonomy: Data: 0.02MB + Index: 0.03MB
las_usermeta: Data: 0.02MB + Index: 0.03MB
las_users: Data: 0.02MB + Index: 0.05MB
las_wc_download_log: Data: 0.02MB + Index: 0.03MB
las_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB
las_wc_webhooks: Data: 0.02MB + Index: 0.02MB
las_yoast_seo_links: Data: 0.02MB + Index: 0.02MB
las_yoast_seo_meta: Data: 0.02MB + Index: 0.00MB

### Post Type Counts ###

attachment: 1
page: 5
post: 2
product: 3
scheduled-action: 94

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (3) ###

Advanced Woo Search: by ILLID – 1.69
WooCommerce: by Automattic – 3.6.2
Yoast SEO: by Team Yoast – 11.1 – Not tested with the active version of WooCommerce

### Inactive Plugins (5) ###

Advanced Custom Fields: Ninjaforms Add-on: by Danny van Holten – 1.1
Advanced Custom Fields PRO: by Elliot Condon – 5.6.8
Force Regenerate Thumbnails: by Pedro Elsner – 2.0.6
Jetpack by WordPress.com: by Automattic – 6.0
Ninja Forms: by The WP Ninjas – 3.4.10

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: AED (د.إ)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #5 - /shop/
Cart: #6 - /cart/
Checkout: #7 - /checkout/
My account: #8 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Seventeen
Version: 1.4 – 2.1 is available
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 94
Oldest: 2019-05-02 08:20:41 +0000
Newest: 2019-05-02 08:21:04 +0000

Pending: 0
Oldest: –
Newest: –

Canceled: 0
Oldest: –
Newest: –

In-progress: 0
Oldest: –
Newest: –

Failed: 0
Oldest: –
Newest: –

`
```
</details>

### PR DESCRIPTION
**Pull request by kloon**
### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

This PR fixes an issue where you cannot sort by stock status when you have Yoast active. Hat tip @m1tk00 for the fix.

Closes #23587 

### How to test the changes in this Pull Request:

1. Activate Yoast plugin on store
2. Use the sort by stock dropdown and check that products are sorted correctly

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Fix - Product sorting issue caused by Yoast plugin conflict.

### CODE REVIEW

File: includes/admin/list-tables/class-wc-admin-list-table-products.php [hunk 1]
```diff
@@ -520,18 +520,16 @@ public function posts_clauses( $args, $query ) {
 	/**
 	 * Remove ordering queries.
 	 *
-	 * @param array $posts Posts from WP Query.
-	 * @return array
+	 * @return void
 	 */
-	public function remove_ordering_args( $posts ) {
+	public function remove_ordering_args() {
```
Comment (claudiosanches) [inline includes/admin/list-tables/class-wc-admin-list-table-products.php]: We probably should keep `$posts` since it's a public method, also people may extend this class.
Probably `$posts = array()` should solve this problem, also keep returning `$posts`.

**Review by claudiosanches — CHANGES_REQUESTED** [review]

**Review by claudiosanches — APPROVED** [review]
LGTM!
