### PR TITLE
Fix handling of order modified date during HPOS sync-on-read

### LINKED ISSUE #62492: Potential HPOS sync-on-read causing repeated `order.updated` webhooks during webhook delivery
## Summary

A possible issue where **HPOS compatibility mode may trigger repeated** `order.updated` **webhooks** during asynchronous webhook delivery. In one production environment, this appeared to result in Action Scheduler backlogs and elevated CPU usage.

## Environment

* WordPress: 6.9
* WooCommerce: 10.4.2
* HPOS: Enabled
* HPOS compatibility mode: Enabled
* Action Scheduler: 3.9.3
* WP-Cron: Disabled (server-side cron)
* Webhooks: Active (`order.updated`)

## Observed Behavior

In this environment, the following was observed:

* Large numbers of pending Action Scheduler jobs, primarily:
  * `woocommerce_deliver_webhook_async`
  * `wc-admin_import_orders`
* Repeated delivery of `order.updated` webhooks for the **same order IDs**
* Elevated CPU usage caused by self-originating HTTP requests
* WooCommerce Analytics imports are stalling or failing under load

## Hypothesis

Based on tracing and call stacks, it appears that:

1. Webhook delivery (`wc_deliver_webhook_async`) reads the order to build a REST payload.
2. While reading, HPOS compatibility mode detects the order as out of sync.
3. HPOS performs a sync/write during this read (`maybe_sync_order`).
4. That write triggers `order.updated`.
5. The webhook is queued again, repeating the cycle.

This suggests a possible **write-on-read** scenario occurring during webhook payload generation.

### Evidence / Call Stack (Observed Repeatedly)

```
Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore->maybe_sync_order
Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore->read
WC_REST_Orders_V2_Controller->get_object
WC_Webhook->get_wp_api_payload
WC_Webhook->deliver
wc_deliver_webhook_async
ActionScheduler_Action->execute
```

## Temporary Mitigation

As a test, HPOS compatibility mode was disabled **only during webhook delivery** using an MU-plugin:

```
add_filter(
    'woocommerce_hpos_enable_compatibility_mode',
    function ( $enabled ) {
        if ( doing_action( 'woocommerce_deliver_webhook_async' ) ) {
            return false;
        }
        return $enabled;
    },
    100
);
```

Results observed after applying this:

* Pending Action Scheduler jobs dropped to zero
* Webhook delivery stabilized
* CPU usage normalized
* Analytics imports recovered

This is **not intended as a recommended solution**, only as a signal that HPOS compatibility sync may be involved.

### Open Questions

1. Is it expected for HPOS compatibility mode to perform **writes during order reads** triggered by webhook payload generation?
2. Should HPOS sync behavior be suppressed or guarded during `wc_deliver_webhook_async`?
3. Are there known edge cases around HPOS compatibility + webhooks that could explain this behavior?

### PR DESCRIPTION
**Pull request by jorgeatorres**
### Changes proposed in this Pull Request:

As described in #62492, when an order is updated via HPOS sync-on-read, it triggers events such as webhooks and Analytics events related to the update. Under certain circumstances (when the modified date in the posts version is ahead of the HPOS one) processing of those events triggers sync-on-read again, enqueuing those same events over and over again.

While this bug has been present in HPOS sync-on-read since it was initially rolled out, it was only now that some related changes made it visible. See below for the details on why this happens.

This PR addresses the main issue and ensures that:

- Sync-on-read doesn't trigger changes to the "modified" date of HPOS orders when metadata is updated as part of the sync.
- Skips backfilling the posts version of an order when the save is happening as part of a sync-on-read, given the posts version is actually what we're copying from.
- Entirely disables sync-on-read during Analytics import and webhook processing.

Closes #62492.

<details>
<summary>Why this happens? (click for details)</summary>

While updating the HPOS order from the posts version, [metadata is updated first](https://github.com/woocommerce/woocommerce/blob/8e9b868158947b84e5b1bf09deeb49cc51138911/plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableDataStore.php#L1713) and then the base properties. As part of updating metadata, HPOS sets the "modified" date [to the current time](https://github.com/woocommerce/woocommerce/blob/8e9b868158947b84e5b1bf09deeb49cc51138911/plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableDataStore.php#L3394-L3395) and also [writes the changes](https://github.com/woocommerce/woocommerce/blob/8e9b868158947b84e5b1bf09deeb49cc51138911/plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableDataStore.php#L2880) back to the [posts version](https://github.com/woocommerce/woocommerce/blob/8e9b868158947b84e5b1bf09deeb49cc51138911/plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableDataStore.php#L2959).

When [the rest of the base properties are processed](https://github.com/woocommerce/woocommerce/blob/8e9b868158947b84e5b1bf09deeb49cc51138911/plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableDataStore.php#L1714-L1725), the modified date gets set to that of the order that originally triggered the sync-on-read, which is the same timestamp the posts version had initially.

When those new changes are persisted, the posts versions is no longer backfilled ([on purpose](https://github.com/woocommerce/woocommerce/blob/8e9b868158947b84e5b1bf09deeb49cc51138911/plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableDataStore.php#L1726)) as we're actually copying data from it.

In the end, the HPOS version gets the _intended_ modified date, but the posts version gets the current time, so they are never in agreement.

</details>

#### Pre-requisites
We're going to disable automatic processing of the A-S queue for testing, to make things more manageable (otherwise tons of events will occur while we test).

1. Enable the following snippet on your test site, which disabled A-S processing and also takes care of logging certain events of interest:
   ```php
   <?php

   add_filter( 'action_scheduler_allow_async_request_runner', '__return_false' );
   add_action( 'init', fn () => remove_action( ActionScheduler_QueueRunner::WP_CRON_HOOK, [ ActionScheduler_QueueRunner::instance(), 'run' ] ) );
   add_filter( 'woocommerce_hpos_enable_sync_on_read', '__return_true' );
   
   add_action(
       'woocommerce_hpos_post_record_migrated_on_read',
       function( $order, $diff ) {
           error_log( 'woocommerce_hpos_post_record_migrated_on_read: ' . $order->get_id() );

       },
       10,
       2
   );
   
   add_action(
       'woocommerce_hpos_post_record_backfilled',
       function( $order ) {
           error_log( 'woocommerce_hpos_post_record_backfilled: ' . $order->get_id() );
       }
   );
   ```
1. Enable Analytics in **WooCommerce > Settings > Advanced > Features**.
1. Ensure that HPOS data storage and compatibility mode are both enabled in **WooCommerce > Settings > Advanced > Features > Order data storage**.
1. Go to **WooCommerce > Orders** and create a new order with any details. Take note of the order ID.
1. Add some 'complex' metadata to your order:
   ```
   $o = wc_get_order( <order_id> )
   $o->add_meta_data( 'complex_meta', array( 'x' => 'y', 'z' => new stdClass() ) );
   $o->save();
   ```
1. Close any admin order screen you might have open. This is to prevent the heartbeat and edit lock pings that could include your order from adding noise to the logs.

#### Test the fix
1. Change the "modified" date in the posts version of your order to be a bit ahead of the HPOS version:
   ```
   wp db query "UPDATE wp_wc_orders o JOIN wp_posts p ON p.ID = o.id SET o.date_updated_gmt = DATE_SUB(p.post_modified_gmt, INTERVAL 1 MINUTE) WHERE o.id  <order_id>"
   ```
1. Run `wp eval 'wc_get_order( <order_id> );'` to trigger read-on-sync.
1. Confirm that your logs show an entry:
   ```
   woocommerce_hpos_post_record_migrated_on_read: <order_id>
   ```

   **No** `woocommerce_hpos_post_record_backfilled` entries should be logged.
1. Confirm, again, that both versions of the order have the same modified date:
   ```
   wp db query "SELECT p.post_modified_gmt, o.date_updated_gmt FROM wp_posts p JOIN wp_wc_orders o ON o.id = p.ID WHERE p.ID = <order_id>"
   ```
1. Run `wp eval 'wc_get_order( <order_id> );'` again and confirm that this time no entries are logged.
1. Add some metadata to the posts version of your order:
   ```
   wp post meta add <order_id> foo bar
   ```
1. Run `wp eval 'wc_get_order( <order_id> );'` to trigger read-on-sync. Confirm `woocommerce_hpos_post_record_migrated_on_read` is again logged.
1. Confirm that both modified dates are identical:
   ```
   wp db query "SELECT p.post_modified_gmt, o.date_updated_gmt FROM wp_posts p JOIN wp_wc_orders o ON o.id = p.ID WHERE p.ID = <order_id>"
   ```
1. Now mix both types of change: differences in metadata and modified date.
   ```
   wp db query "UPDATE wp_wc_orders o JOIN wp_posts p ON p.ID = o.id SET o.date_updated_gmt = DATE_SUB(p.post_modified_gmt, INTERVAL 1 MINUTE) WHERE o.id =<order_id>"

   wp post meta add <order_id> another_meta no
   ```
1. Run `wp eval 'wc_get_order( <order_id> );'` to trigger read-on-sync. Confirm `woocommerce_hpos_post_record_migrated_on_read` is again logged and that both versions have the same "modified" date.
1. Run `wp eval 'wc_get_order( <order_id> )->save();'` to simulate a normal order edit. Confirm that there's a pending A-S job for the Analytics related to your order:

   ```
   wp action-scheduler action list --hook=wc-admin_import_orders --status=pending --fields=id,hook,args --args="[<order_id>]"
   ```

   Make a note of the action ID that has your order id in args.
1. Run the job from the previous step:

   ```
   wp action-scheduler action run <action_id>
   ```

   Confirm that no job with your order in args remains:

   ```
   wp action-scheduler action list --hook=wc-admin_import_orders --status=pending --fields=id,hook,args --args="[<order_id>]"
   ```

#### Confirm the issue on `trunk` and that updating will address it
1. Check out `trunk`.
1. Change the "modified" date in the posts version of your order to be a bit ahead of the HPOS version:
   ```
   wp db query "UPDATE wp_wc_orders o JOIN wp_posts p ON p.ID = o.id SET o.date_updated_gmt = DATE_SUB(p.post_modified_gmt, INTERVAL 1 MINUTE) WHERE o.id  <order_id>"
   ```
1. Run `wp eval 'wc_get_order( <order_id> );'` to trigger read-on-sync. Confirm that both `woocommerce_hpos_post_record_backfilled` and `wocommerce_hpos_post_record_migrated_on_read` entries are logged.
1. Repeat `wp eval 'wc_get_order( <order_id> );'` to trigger read-on-sync a few times and confirm that each time `woocommerce_hpos_post_record_backfilled` and `wocommerce_hpos_post_record_migrated_on_read` entries are logged, indicating that sync-on-read is already in a loop.
1. Confirm that the "modified" date in both versions is different:
   ```
   wp db query "SELECT p.post_modified_gmt, o.date_updated_gmt FROM wp_posts p JOIN wp_wc_orders o ON o.id = p.ID WHERE p.ID = <order_id>"
   ```
1. Confirm that there's an A-S job associated to your order:
   ```
   wp action-scheduler action list --hook=wc-admin_import_orders --status=pending --fields=id,hook,args --args="[<order_id>]"
   ```
1. Run the job:
   ```
   wp action-scheduler action run <action_id>
   ```
1. Confirm that there's a new A-S job still associated to your order (demonstrating the "infinite loop" situation):
   ```
   wp action-scheduler action list --hook=wc-admin_import_orders --status=pending --fields=id,hook,args --args="[<order_id>]"
   ```
1. Check out this branch (`fix/62492`) to simulate an upgrade.
1. Run the pending A-S job:
   ```
   wp action-scheduler action list --hook=wc-admin_import_orders --status=pending --fields=id,hook,args --args="[<order_id>]"

   wp action-scheduler action run <order_id>
   ```
1. Confirm that no new job has been enqueued, demonstrating the infinite loop ending:
   ```
   wp action-scheduler action list --hook=wc-admin_import_orders --status=pending --fields=id,hook,args --args="[<order_id>]"
   ```

### CODE REVIEW

File: plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableDataStore.php [hunk 1]
```diff
@@ -1364,7 +1372,10 @@ public function read_multiple( &$orders ) {
 			 *
 			 * @since 8.1.0
 			 */
-			$data_sync_enabled = apply_filters( 'woocommerce_hpos_enable_sync_on_read', $data_sync_enabled );
+			$data_sync_enabled = apply_filters(
+				'woocommerce_hpos_enable_sync_on_read',
+				! doing_action( 'woocommerce_deliver_webhook_async' ) && ! doing_action( 'wc-admin_import_orders' )
```
[the remark this answers is not in the document]
Comment (jorgeatorres) [reply plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableDataStore.php]: This is on purpose and actually useful to prevent unnecessary I/O. The orders will again be synced (if necessary) when read via any other means (either via API or browsing the admin). Skipping sync-on-read for these operations actually makes sense as the events are just to deliver information and not update orders.

File: plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableDataStore.php [hunk 2]
```diff
@@ -1710,6 +1721,8 @@ private function get_diff_meta_data_between_orders( \WC_Abstract_Order &$order1,
 	 * @return void
 	 */
 	private function migrate_post_record( \WC_Abstract_Order &$order, \WC_Abstract_Order $post_order ): void {
+		self::$sync_on_read_order_ids[] = $order->get_id();
```
Comment (ObliviousHarmony) [inline plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableDataStore.php]: It's a small thing, but for performance, should we make this a map and check `isset()` instead?

File: plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableDataStore.php (hunk 1 above)
Comment (ObliviousHarmony) [inline plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableDataStore.php]: It isn't super clear (outside of this PR) why we are doing this. How would you feel about extracting this to a variable right above with a relevant name and a comment explaining why?

File: plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableDataStore.php (hunk 2 above)
Comment (ObliviousHarmony) [inline plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableDataStore.php]: Nit: Wouldn't it be more performant for all of these static arrays to use `isset()` and be treated as a map? It's O(1) for checking and then we avoid the memory and CPU cost of `array_diff()` right below!

File: plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableDataStore.php [hunk 3]
```diff
@@ -3421,6 +3440,7 @@ private function should_save_after_meta_change( $order, $meta = null ) {
 
 		$should_save =
 			$order->get_id() > 0
+			&& ! in_array( $order->get_id(), self::$sync_on_read_order_ids, true )
```
Comment (ObliviousHarmony) [inline plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableDataStore.php]: I'm _really_ sorry if this should be obvious, however, I'm not entirely sure I understand the change! Wouldn't you _want_ to update the modified timestamp if it synchronized on read? Are there consequences to performing the sync but not recording that we did?

**Review by ObliviousHarmony — COMMENTED** [review]
Hey @jorgeatorres!

This is looking pretty good, I appreciate the simplistic approach here to identifying orders that are being synchronized on read.

I took your (very) comprehensive testing instructions for a spin and it does what it says it does. With that said, when I did the testing instructions with 10.4.2, I was unable to replicate the bug the PR is supposed to fix! I went through all of the instructions and they behaved the same way both times. Did I do something wrong?

File: plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableDataStore.php (hunk 2 above)
Comment (jorgeatorres) [reply plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableDataStore.php]: Good idea! Done in d2d7829ece2ca4e32a8e9dbb74cf3256bef1d80d.

File: plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableDataStore.php (hunk 1 above)
Comment (jorgeatorres) [reply plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableDataStore.php]: Fair! Done in 919671fa1b5197e185a316696a89a948d233fd7a.

File: plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableDataStore.php (hunk 3 above)
Comment (jorgeatorres) [reply plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableDataStore.php]: It's a good question and I think _ideally_ we want both the HPOS and posts version to be updated to the current timestamp after any sync event, but the way things are implemented right now makes that a bit cumbersome.

I wouldn't oppose revising it later (as well as disabling sync-on-read altogether), but I think we should prevent the infinite loops some sites are seeing first.

The thing is that this attempt at updating the timestamp happens after any metadata change (which can naturally happen [as part of a sync-on-read](https://github.com/woocommerce/woocommerce/blob/919671fa1b5197e185a316696a89a948d233fd7a/plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableDataStore.php#L1727)). If we let it update the timestamp, this would then be persisted to _both_ the HPOS and posts version of the order (through the `$order->save()` below) but then when [the rest of the sync picks up after the metadata step](https://github.com/woocommerce/woocommerce/blob/919671fa1b5197e185a316696a89a948d233fd7a/plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableDataStore.php#L1728-L1740) it'll overwrite the modified date to the one the post had when the sync started (as the base props being updated are all taken from the posts version).

So this timestamp update would get overwritten once again, and we would've written to the database for nothing (including triggering all the associated events)... **and** because we're only writing to the HPOS version and actually avoiding [backfilling the posts version](https://github.com/woocommerce/woocommerce/blob/919671fa1b5197e185a316696a89a948d233fd7a/plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableDataStore.php#L1740), the modified date on the post is ahead, so the order is now subject to yet another sync-on-read next time.

**Review by albarin — APPROVED** [review]
Thanks for the fix, Jorge!

✅ Confirmed I was able to reproduce the issue on `trunk`.
✅ Confirmed checking out to this branch fixed the loop situation.

**Review by Konamiman — APPROVED** [review]
