### PR TITLE
Remove use of SQL_CALC_FOUND_ROWS in low stock query 

### LINKED ISSUE #38932: Potential slow SQL query in Products Low In Stock `/products/low-in-stock` endpoint.
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Opening this up for visibility and investigation. This report will help merchants facing similar issues.

6458996-zen

A new endpoint was introduced here for pulling Low In Stock products: https://github.com/woocommerce/woocommerce-admin/issues/7358#issuecomment-883908480 to resolve a similar slow query earlier.

This endpoint is called from some places like the **WooCommerce > Home > Stock** widget:

https://d.pr/i/YStdZP 
Full Size: https://d.pr/i/YStdZP

Merchant reports their site times out when store admins are working in the backend.

They have following specs

```
WC Version: 7.8.0
REST API Version: ✔ 7.8.0
WC Blocks Version: ✔ 10.2.3
Action Scheduler Version: ✔ 3.6.1
Log Directory Writable: ✔
WP Version: 6.2.2
WP Multisite: ✔
WP Memory Limit: 4 GB
WP Debug Mode: –
WP Cron: –
Language: nl_NL
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.57 (Debian)
PHP Version: 7.4.33
PHP Post Max Size: 250 MB
PHP Time Limit: 900
PHP Max Input Vars: 10000
cURL Version: 7.64.0
OpenSSL/1.1.1n

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.4.20-MariaDB-1:10.4.20+maria~buster-log
Max Upload Size: 1 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.8.0
WC Database Prefix: wp_
Totale database grootte: 987.19MB
Database gegevens grootte: 556.88MB
Database index grootte: 430.31MB
```

The slow query generates from 'products/low-in-stock' endpoint. Below is the slow query log shared by the merchant. 

```
SELECT
   SQL_CALC_FOUND_ROWS wp_posts.*,
   meta.meta_value AS low_stock_amount,
   wc_product_meta_lookup.stock_quantity 
FROM
   wp_wc_product_meta_lookup wc_product_meta_lookup 
   LEFT JOIN
      wp_posts wp_posts 
      ON wp_posts.ID = wc_product_meta_looku p.product_id 
   LEFT JOIN
      wp_postmeta AS meta 
      ON wp_posts.ID = meta.post_id 
      AND meta.meta_key = '_low_stock_amount' 
WHERE
   wp_posts.post_type IN 
   (
      'product',
      'product_variation'
   )
   AND wp_posts.post_status = 'publish' 
   AND wc_product_meta_lookup.st ock_quantity IS NOT NULL 
   AND wc_product_meta_lookup.stock_status IN
   (
      'instock',
      'outofstock'
   )
   AND 
   (
( meta.meta_value > '' 
      AND wc_product_meta_lookup.stock_quantity <= CAST( meta.meta_value AS SIGNED ) ) 
      OR 
      (
( meta.meta_value IS NULL 
         OR meta.meta_value <= '' ) 
         AND wc_product_meta_lookup.stock_quantity <= 1 
      )
   )
order by
   wc_product_meta_lookup.product_id DESC limit 0,
   1;

```

Above is a more expensive version of the query because "Low stock threshold" is configured on a per product basis.

https://github.com/woocommerce/woocommerce/blob/ba5cc19757459384361981c931ff9d4574345fc8/plugins/woocommerce/src/Admin/API/ProductsLowInStock.php#L249

I've opened this up so that we can track more instances and devs can investigate as necessary.

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by moon0326**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes #38932

This PR changes the following.

- Removed use of `SQL_CALC_FOUND_ROWS` -- SQL_CALC_FOUND_ROWS can cause inconsistent performance depending on the # of rows or DB version. Some stores may even experience timeout. See https://www.percona.com/blog/to-sql_calc_found_rows-or-not-to-sql_calc_found_rows/ for more info.
- Added `products/count-low-in-stock` API endpoint and uses it from the frontend. The endpoint is faster than the existing `products/low-in-stock` endpoint as it doesn't query the data. 

### How to test the changes in this Pull Request:

1. Create a new JN site with this branch.
2. Install and activate WooCommerce Smooth Generator from https://github.com/woocommerce/wc-smooth-generator/releases
3. Go to `Tools -> Smooth Generator.`
4. Generate 100 products and orders.
5. Wait until products and orders are ready.
6. Go to `WooCommerce -> Home`. Complete the core profiler if necessary.
7. Click ellipsis button and click `Hide setup list.`
8. Confirm `Stock` tap appears and it's working as expected.

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [x] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

Remove use SQL_CALC_FOUND_ROWS from the query. SQL_CALC_FOUND_ROWS can cause inconsistent performance depending on the # of rows or DB version. 

#### Comment 

</details>

### CODE REVIEW

**Comment by moon0326** [comment]
@woocommerce/mothra Hey Mothra ✋ Could you take a look at this issue when you get a chance please?

File: plugins/woocommerce/src/Admin/API/ProductsLowInStock.php [hunk 1]
```diff
@@ -216,16 +258,15 @@ protected function transform_post_to_api_response( $query_result ) {
 	 * Generate a query.
 	 *
 	 * @param bool $siteside_only generates a query for sitewide low stock threshold only query.
+	 * @param bool $return_count_query returns country query instead of the actual query.
```
Comment (louwie17) [inline plugins/woocommerce/src/Admin/API/ProductsLowInStock.php]: Spelling mistake `country` versus `count`

File: plugins/woocommerce/src/Admin/API/ProductsLowInStock.php [hunk 2]
```diff
@@ -216,16 +258,15 @@ protected function transform_post_to_api_response( $query_result ) {
...
 	 *
 	 * @return string
 	 */
-	protected function get_query( $siteside_only = false ) {
+	protected function get_query( $siteside_only = false, $return_count_query = false ) {
```
Comment (louwie17) [inline plugins/woocommerce/src/Admin/API/ProductsLowInStock.php]: Having this as a parameter feels very strange to me. I would prefer a `get_count_query` function. Although that may require some extra refactor to avoid a large amount of duplicate code, which I assume is some of the reason you stuck to this approach.
Maybe we could separate it out into `get_post_meta_args` and `get_base_query` ( or something to that extend ).

This would of been a lot easier if we made use of [WP_Query](https://developer.wordpress.org/reference/classes/wp_query/).

**Review by louwie17 — CHANGES_REQUESTED** [review]
Thanks for addressing this @moon0326, I left a couple inline comments and did notice one bug:
When updating the stock of the last item in the list it turns into a permanent loading screen.
It's a pretty easy fix, you did just want to update the invalidate resolution api endpoint as well to tag on the `count-` to `products/count-low-in-stock` in this file: [here](https://github.com/woocommerce/woocommerce/blob/7068c78101a6062e66d46be0dedfc96ca86102fb/plugins/woocommerce-admin/client/homescreen/activity-panel/stock/index.js#L55)

File: plugins/woocommerce/src/Admin/API/ProductsLowInStock.php (hunk 1 above)
Comment (moon0326) [reply plugins/woocommerce/src/Admin/API/ProductsLowInStock.php]: Thanks! I'll update it.

File: plugins/woocommerce/src/Admin/API/ProductsLowInStock.php (hunk 2 above)
Comment (moon0326) [reply plugins/woocommerce/src/Admin/API/ProductsLowInStock.php]: Yup..that was the reason.

I actually tried to use WP_Query when I first worked on this endpoint last year and I could not find a good way to work with WP_Query for multi-table joins. I'll look into it one more time to see if we can use WP_Query.

Comment (moon0326) [reply plugins/woocommerce/src/Admin/API/ProductsLowInStock.php]: @louwie17 I've refactored code in https://github.com/woocommerce/woocommerce/pull/40289/commits/991ddaa56d6d78ec383338c2542e9767e1cd5810
I wish there was a generic query builder in WP or WC (May be a cooldown/HACK issue :) ? )

Comment (moon0326) [reply plugins/woocommerce/src/Admin/API/ProductsLowInStock.php]: Hey @louwie17 ✋ Could you take another look at it please?

File: plugins/woocommerce-admin/client/homescreen/activity-panel/orders/utils.js [hunk 3]
```diff
@@ -74,7 +70,7 @@ export function getLowStockCount( select ) {
 	// depend on `getItemsTotalCount` to have been called.
 	// eslint-disable-next-line @wordpress/no-unused-vars-before-return
 	const totalLowStockProducts = getItemsTotalCount(
-		'products/low-in-stock',
+		'products/count-low-in-stock',
```
Comment (louwie17) [inline plugins/woocommerce-admin/client/homescreen/activity-panel/orders/utils.js:73]: We should also update the call on line 83 and 86 below: https://github.com/woocommerce/woocommerce/blob/aea1e858931f389d258184eed61646a6a8140413/plugins/woocommerce-admin/client/homescreen/activity-panel/orders/utils.js#L79-L82

I believe this is causing the infinite loading screen when updating the last stock item.

**Review by louwie17 — CHANGES_REQUESTED** [review]
Sorry for looping back to this so late, next time feel free to ping me in Slack as well if I don't respond in time or ping our team ( cause I will be AFK most of next week ).
I still noticed the unlimited loading bug, I left an inline comment in regards to that.

Also the count is not updating when the list of products is greater then 1. This is because of a condition here: https://github.com/woocommerce/woocommerce/blob/7068c78101a6062e66d46be0dedfc96ca86102fb/plugins/woocommerce-admin/client/homescreen/activity-panel/stock/index.js#L54-L60
We should remove this and update it to make use of `count-low-in-stock` as well. I think we had this condition previously, as the request to `low-in-stock` would automatically update the count anyway, but that isn't the case now.

File: plugins/woocommerce/src/Admin/API/ProductsLowInStock.php (hunk 2 above)
Comment (louwie17) [reply plugins/woocommerce/src/Admin/API/ProductsLowInStock.php]: Yup, sorry for getting back to this so late, I sometimes loose track of my GH notifications.

File: plugins/woocommerce-admin/client/homescreen/activity-panel/orders/utils.js (hunk 3 above)
Comment (moon0326) [reply plugins/woocommerce-admin/client/homescreen/activity-panel/orders/utils.js:73]: Thank you for catching it 🙇

**Comment by moon0326** [comment]
> Sorry for looping back to this so late, next time feel free to ping me in Slack as well if I don't respond in time or ping our team ( cause I will be AFK most of next week ). I still noticed the unlimited loading bug, I left an inline comment in regards to that.
> 
> Also the count is not updating when the list of products is greater then 1. This is because of a condition here:
> 
> https://github.com/woocommerce/woocommerce/blob/7068c78101a6062e66d46be0dedfc96ca86102fb/plugins/woocommerce-admin/client/homescreen/activity-panel/stock/index.js#L54-L60
> 
> 
> We should remove this and update it to make use of `count-low-in-stock` as well. I think we had this condition previously, as the request to `low-in-stock` would automatically update the count anyway, but that isn't the case now.

Thank you! I was actually AFK as well 😄 Enjoy AFK 👍 

Updated https://github.com/woocommerce/woocommerce/pull/40289/commits/174669eb3386aa6c0a5905c52c5108776c8a45e7 and https://github.com/woocommerce/woocommerce/pull/40289/commits/c4e34df9ba988e97924cf17d98e4b99c30ed34b8 to address the count and loading issues.

@woocommerce/mothra  ✋ Could you take a look at it please?

File: plugins/woocommerce-admin/client/homescreen/activity-panel/orders/utils.js [hunk 4]
```diff
@@ -74,16 +70,16 @@ export function getLowStockCount( select ) {
...
 		defaultValue
 	);
 
 	const isError = Boolean(
-		getItemsError( 'products/low-in-stock', getLowStockCountQuery )
+		getItemsError( 'products/count-low-in-stock', getLowStockCountQuery )
 	);
 	const isRequesting = isResolving( 'getItemsTotalCount', [
-		'products/low-in-stock',
+		'products/ount-clow-in-stock',
```
Comment (louwie17) [inline plugins/woocommerce-admin/client/homescreen/activity-panel/orders/utils.js]: Slight spelling/typing mistake `products/count-low-in-stock`

**Review by louwie17 — CHANGES_REQUESTED** [review]
One minor suggestion @moon0326, which end up happening with one of the last changes, but for the rest things are testing well.

File: plugins/woocommerce-admin/client/homescreen/activity-panel/orders/utils.js (hunk 4 above)
Comment (moon0326) [reply plugins/woocommerce-admin/client/homescreen/activity-panel/orders/utils.js]: Thank you for catching it! "slight" is an understatement 😄 

Fixed in https://github.com/woocommerce/woocommerce/pull/40289/commits/c487220750528ff0c30625cb9170bece82c049c7

**Review by louwie17 — APPROVED** [review]
LGTM 🚀 Thanks for the final fix @moon0326, nice work!! This is good to 🚢

**Comment by nigeljamesstevenson** [comment]
Checks appeared to have stopped on this so I closed and reopened the PR in the hope they would be sparked into life

**Comment by moon0326** [comment]
Sorry for the delay in fixing the failed GH jobs, @nigeljamesstevenson. They're all cleared now. Could you please take another look at this PR 🙏 ?

**Comment by rodelgc** [comment]
Analysis done. Assigning the 8.4 milestone now and then merge after.
