### PR TITLE
fix ensure cancelling unpaid orders is always re-scheduled

### LINKED ISSUE #30682: woocommerce_cancel_unpaid_orders cron stops indefinitely
I found a bug on multiple WooCommerce stores I am running. The scheduled hook `woocommerce_cancel_unpaid_orders` is no longer registered. After looking into the official code of the function `wc_cancel_unpaid_orders()` I see it re-schedules the hook only AFTER SUCCESSFUL execution.

This leads to the following scenario:
1. `woocommerce_cancel_unpaid_orders` hook is scheduled on WC install
2. if `wc_cancel_unpaid_orders()` crashes or times-out once (database currently overloaded,...) it is never scheduled again. See the original function code attached. 

Suggested fix:
The `wp_schedule_single_event()` for `woocommerce_cancel_unpaid_orders` should be at the beginning of the `wc_cancel_unpaid_orders()` function. Otherwise on long running installations cancelling orders will eventually stop working.

My Workaround:
We now called `wc_cancel_unpaid_orders(`) from our own cron.

```
/**
 * Cancel all unpaid orders after held duration to prevent stock lock for those products.
 */
function wc_cancel_unpaid_orders() {
	$held_duration = get_option( 'woocommerce_hold_stock_minutes' );

	if ( $held_duration < 1 || 'yes' !== get_option( 'woocommerce_manage_stock' ) ) {
		return;
	}

	$data_store    = WC_Data_Store::load( 'order' );
	$unpaid_orders = $data_store->get_unpaid_orders( strtotime( '-' . absint( $held_duration ) . ' MINUTES', current_time( 'timestamp' ) ) );

	if ( $unpaid_orders ) {
		foreach ( $unpaid_orders as $unpaid_order ) {
			$order = wc_get_order( $unpaid_order );

			if ( apply_filters( 'woocommerce_cancel_unpaid_order', 'checkout' === $order->get_created_via(), $order ) ) {
				$order->update_status( 'cancelled', __( 'Unpaid order cancelled - time limit reached.', 'woocommerce' ) );
			}
		}
	}
	wp_clear_scheduled_hook( 'woocommerce_cancel_unpaid_orders' );
	$cancel_unpaid_interval = apply_filters( 'woocommerce_cancel_unpaid_orders_interval_minutes', absint( $held_duration ) );
	wp_schedule_single_event( time() + ( absint( $cancel_unpaid_interval ) * 60 ), 'woocommerce_cancel_unpaid_orders' );
}
add_action( 'woocommerce_cancel_unpaid_orders', 'wc_cancel_unpaid_orders' );
```

### PR DESCRIPTION
**Pull request by Ekliptor**
### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes https://github.com/woocommerce/woocommerce/issues/30682

I have moved the `wp_schedule_single_event()`to the beginning of the `wc_cancel_unpaid_orders()`as suggested in my bug report. This ensures that cancelling order does not stop in case of a script timeout or plugin-related crash happening once. Moving it up will ensure it gets scheduled for retry.

### How to test the changes in this Pull Request:

1. add a call to `do_action('woocommerce_cancel_unpaid_orders');` inside a WP init hook to call the new code. Alternatively call `wc_cancel_unpaid_orders();` directly
2. call `exit` in `wc_cancel_unpaid_orders()`to simulate a crash.
3. On next script run: print `$timestamp = wp_next_scheduled ( 'woocommerce_cancel_unpaid_orders' );` to ensure `$timestamp > 0`

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Fix - Ensure `woocommerce_cancel_unpaid_orders` event is always re-scheduled.

### CODE REVIEW

File: includes/wc-order-functions.php [hunk 1]
```diff
@@ -915,6 +915,12 @@ function wc_update_coupon_usage_counts( $order_id ) {
 function wc_cancel_unpaid_orders() {
 	$held_duration = get_option( 'woocommerce_hold_stock_minutes' );
 
+	// re-schedule the event before cancelling orders
```
Comment (claudiosanches) [inline includes/wc-order-functions.php]:
```suggestion
	// Re-schedule the event before cancelling orders
```

File: includes/wc-order-functions.php [hunk 2]
```diff
@@ -915,6 +915,12 @@ function wc_update_coupon_usage_counts( $order_id ) {
...
+	// this way in case of a DB timeout or (plugin) crash the event is always scheduled for retry
```
Comment (claudiosanches) [inline includes/wc-order-functions.php]:
```suggestion
	// this way in case of a DB timeout or (plugin) crash the event is always scheduled for retry.
```

**Review by claudiosanches — CHANGES_REQUESTED** [review]

**Review by claudiosanches — APPROVED** [review]
Works great.

Just a note: during update WooCommerce re-schedule all events, so no migration or any action is required to fix existing stores.

**Comment by azanoni** [comment]
Sadly this doesnt fix the issue, I tried with my client this version (5.9.0) and we are still experience the same issue, random (maybe because other plugin cause this) the cron job is "deleted", the only way to restoring this again is change the HOLD STOCK MINUTES with another number...save it, and after that the CRON appear again.

**Comment by Ekliptor** [comment]
Can you paste a System Report under WooCommerce -> Status?
I'm also assuming another plugin is modifying the `woocommerce_cancel_unpaid_orders` single event.

The current fix keeps using `wp_schedule_single_event()`.
A more "brutal" fix would be to add an additional `wp_schedule_event()` that checks hourly if the event is still scheduled. If not, re-schedule it using `wp_schedule_single_event()` according to your "hold stock minutes" setting.

**Comment by azanoni** [comment]
Yeah I was thinking in the same idea, another cronjob that checks if cancel_unpaid is alive, if not trigger the cronjob, was as you said before, is like a "brutal" fix

`
### WordPress Environment ###

WordPress address (URL): https://clientdomain.com
Site address (URL): https://clientdomain.com
WC Version: 5.9.0
REST API Version: ✔ 5.9.0
WC Blocks Version: ✔ 6.1.0
Action Scheduler Version: ✔ 3.3.0
WC Admin Version: ✔ 2.8.0
Log Directory Writable: ✔
WP Version: ❌ 5.7.4 - There is a newer version of WordPress available (5.8.2)
WP Multisite: –
WP Memory Limit: 98 GB
WP Debug Mode: –
WP Cron: ✔
Language: en_GB
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.3.29
PHP Post Max Size: 100 MB
PHP Time Limit: 600
PHP Max Input Vars: 1000
cURL Version: 7.61.1
OpenSSL/1.0.2k

SUHOSIN Installed: –
MySQL Version: 5.7.22-log
Max Upload Size: 100 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 5.9.0
WC Database Prefix: custompref_
Total Database Size: 13816.08MB
Database Data Size: 12213.97MB
Database Index Size: 1602.11MB
custompref_woocommerce_sessions: Data: 23.05MB + Index: 1.02MB + Engine InnoDB
custompref_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
custompref_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
custompref_woocommerce_downloadable_product_permissions: Data: 11.52MB + Index: 27.92MB + Engine InnoDB
custompref_woocommerce_order_items: Data: 8.52MB + Index: 3.52MB + Engine InnoDB
custompref_woocommerce_order_itemmeta: Data: 104.64MB + Index: 58.14MB + Engine InnoDB
custompref_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
custompref_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
custompref_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
custompref_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
custompref_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
custompref_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
custompref_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
custompref_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
migrate_memberships: Data: 3.52MB + Index: 0.00MB + Engine InnoDB
translator_categories: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
translator_dictionary: Data: 0.42MB + Index: 0.06MB + Engine InnoDB
translator_dictionary_theme: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
translator_languages: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
translator_languages_list: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
translator_languages_status: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
translator_options: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
translator_position_status: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
translator_products: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
translator_products_downloads: Data: 30.56MB + Index: 54.13MB + Engine InnoDB
translator_profile_digit_styles: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
translator_profile_list_styles: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
translator_profile_theme: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
translator_sort_type: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
translator_texts_styles: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
translator_translations: Data: 4.52MB + Index: 0.89MB + Engine InnoDB
translator_translations_import_log: Data: 6.52MB + Index: 0.02MB + Engine InnoDB
translator_translation_styles: Data: 0.08MB + Index: 0.03MB + Engine InnoDB
translator_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
translator_users_ip: Data: 24.55MB + Index: 0.00MB + Engine InnoDB
translator_user_languages: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
translator_user_roles: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
custompref_actionscheduler_actions: Data: 22.05MB + Index: 22.11MB + Engine InnoDB
custompref_actionscheduler_claims: Data: 0.08MB + Index: 0.06MB + Engine InnoDB
custompref_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
custompref_actionscheduler_logs: Data: 17.05MB + Index: 13.03MB + Engine InnoDB
custompref_aelia_dismissed_messages: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
custompref_aelia_exchange_rates_history: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
custompref_affiliate_custompref_affiliatemeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
custompref_affiliate_custompref_affiliates: Data: 0.16MB + Index: 0.06MB + Engine InnoDB
custompref_affiliate_custompref_campaigns: Data: 0.17MB + Index: 0.13MB + Engine InnoDB
custompref_affiliate_custompref_coupons: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
custompref_affiliate_custompref_creatives: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
custompref_affiliate_custompref_customermeta: Data: 0.11MB + Index: 0.16MB + Engine InnoDB
custompref_affiliate_custompref_customers: Data: 0.17MB + Index: 0.16MB + Engine InnoDB
custompref_affiliate_custompref_payouts: Data: 0.20MB + Index: 0.13MB + Engine InnoDB
custompref_affiliate_custompref_referralmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
custompref_affiliate_custompref_referrals: Data: 3.52MB + Index: 0.23MB + Engine InnoDB
custompref_affiliate_custompref_rest_consumers: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
custompref_affiliate_custompref_sales: Data: 0.09MB + Index: 0.06MB + Engine InnoDB
custompref_affiliate_custompref_visits: Data: 8784.00MB + Index: 398.00MB + Engine InnoDB
custompref_bbapp_iap_ordermeta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
custompref_bbapp_iap_orders: Data: 0.02MB + Index: 0.17MB + Engine InnoDB
custompref_bbapp_iap_products: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
custompref_bbapp_itemmeta: Data: 0.14MB + Index: 0.00MB + Engine InnoDB
custompref_bbapp_logs: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
custompref_bbapp_notifications: Data: 0.02MB + Index: 0.14MB + Engine InnoDB
custompref_bbapp_notifications_devices: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
custompref_bbapp_push_notifications: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
custompref_bbapp_push_notifications_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
custompref_bbapp_push_queue: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
custompref_bbapp_queue: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
custompref_bbapp_user_segment: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
custompref_bb_performance_cache: Data: 3.52MB + Index: 0.08MB + Engine InnoDB
custompref_bp_activity: Data: 8.52MB + Index: 6.03MB + Engine InnoDB
custompref_bp_activity_meta: Data: 1.52MB + Index: 0.61MB + Engine InnoDB
custompref_bp_document: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
custompref_bp_document_folder: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
custompref_bp_document_folder_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
custompref_bp_document_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
custompref_bp_follow: Data: 0.11MB + Index: 0.09MB + Engine InnoDB
custompref_bp_friends: Data: 0.38MB + Index: 0.42MB + Engine InnoDB
custompref_bp_groups: Data: 0.13MB + Index: 0.05MB + Engine InnoDB
custompref_bp_groups_groupmeta: Data: 0.28MB + Index: 0.17MB + Engine InnoDB
custompref_bp_groups_members: Data: 1.52MB + Index: 1.88MB + Engine InnoDB
custompref_bp_invitations: Data: 0.02MB + Index: 0.14MB + Engine InnoDB
custompref_bp_media: Data: 0.19MB + Index: 0.25MB + Engine InnoDB
custompref_bp_media_albums: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
custompref_bp_messages_messages: Data: 8.52MB + Index: 0.80MB + Engine InnoDB
custompref_bp_messages_meta: Data: 0.09MB + Index: 0.06MB + Engine InnoDB
custompref_bp_messages_notices: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
custompref_bp_messages_recipients: Data: 0.28MB + Index: 0.80MB + Engine InnoDB
custompref_bp_moderation: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
custompref_bp_moderation_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
custompref_bp_notifications: Data: 6.52MB + Index: 20.81MB + Engine InnoDB
custompref_bp_notifications_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
custompref_bp_suspend: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
custompref_bp_suspend_details: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
custompref_bp_user_blogs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
custompref_bp_user_blogs_blogmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
custompref_bp_xprofile_data: Data: 3.52MB + Index: 4.00MB + Engine InnoDB
custompref_bp_xprofile_fields: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
custompref_bp_xprofile_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
custompref_bp_xprofile_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
custompref_bp_zoom_meetings: Data: 0.05MB + Index: 0.05MB + Engine InnoDB
custompref_bp_zoom_meeting_meta: Data: 1.52MB + Index: 0.03MB + Engine InnoDB
custompref_bp_zoom_recordings: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
custompref_bp_zoom_webinars: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
custompref_bp_zoom_webinar_meta: Data: 0.50MB + Index: 0.03MB + Engine InnoDB
custompref_bp_zoom_webinar_recordings: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
custompref_commentmeta: Data: 3.52MB + Index: 2.94MB + Engine InnoDB
custompref_comments: Data: 36.56MB + Index: 30.06MB + Engine InnoDB
custompref_e_submissions: Data: 0.02MB + Index: 0.27MB + Engine InnoDB
custompref_e_submissions_actions_log: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
custompref_e_submissions_values: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
custompref_fc_campaigns: Data: 0.23MB + Index: 0.00MB + Engine InnoDB
custompref_fc_campaign_emails: Data: 61.52MB + Index: 5.72MB + Engine InnoDB
custompref_fc_campaign_url_metrics: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
custompref_fc_funnels: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
custompref_fc_funnel_metrics: Data: 2.52MB + Index: 3.03MB + Engine InnoDB
custompref_fc_funnel_sequences: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
custompref_fc_funnel_subscribers: Data: 1.52MB + Index: 0.47MB + Engine InnoDB
custompref_fc_lists: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
custompref_fc_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
custompref_fc_sequence_tracker: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
custompref_fc_smart_links: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
custompref_fc_subscribers: Data: 3.52MB + Index: 3.45MB + Engine InnoDB
custompref_fc_subscriber_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
custompref_fc_subscriber_notes: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
custompref_fc_subscriber_pivot: Data: 4.52MB + Index: 7.55MB + Engine InnoDB
custompref_fc_tags: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
custompref_fc_url_stores: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
custompref_followup_coupons: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
custompref_followup_coupon_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
custompref_followup_customers: Data: 1.52MB + Index: 2.84MB + Engine InnoDB
custompref_followup_customer_carts: Data: 9.05MB + Index: 2.98MB + Engine InnoDB
custompref_followup_customer_notes: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
custompref_followup_customer_orders: Data: 2.52MB + Index: 1.48MB + Engine InnoDB
custompref_followup_email_excludes: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
custompref_followup_email_logs: Data: 2.52MB + Index: 2.17MB + Engine InnoDB
custompref_followup_email_orders: Data: 9.52MB + Index: 2.80MB + Engine InnoDB
custompref_followup_email_tracking: Data: 2.52MB + Index: 3.11MB + Engine InnoDB
custompref_followup_followup_history: Data: 55.52MB + Index: 0.63MB + Engine InnoDB
custompref_followup_order_categories: Data: 2.52MB + Index: 3.02MB + Engine InnoDB
custompref_followup_order_items: Data: 2.52MB + Index: 4.44MB + Engine InnoDB
custompref_followup_subscribers: Data: 0.38MB + Index: 0.39MB + Engine InnoDB
custompref_followup_subscribers_to_lists: Data: 0.38MB + Index: 0.48MB + Engine InnoDB
custompref_followup_subscriber_lists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
custompref_fsmpt_email_logs: Data: 669.05MB + Index: 0.00MB + Engine InnoDB
custompref_gf_draft_submissions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
custompref_gf_entry: Data: 4.52MB + Index: 1.88MB + Engine InnoDB
custompref_gf_entry_meta: Data: 18.55MB + Index: 20.30MB + Engine InnoDB
custompref_gf_entry_notes: Data: 0.52MB + Index: 0.14MB + Engine InnoDB
custompref_gf_form: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
custompref_gf_form_meta: Data: 1.48MB + Index: 0.00MB + Engine InnoDB
custompref_gf_form_revisions: Data: 0.27MB + Index: 0.03MB + Engine InnoDB
custompref_gf_form_view: Data: 0.31MB + Index: 0.27MB + Engine InnoDB
custompref_gf_rest_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
custompref_gk_tk_delta_positions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
custompref_gk_tk_clientdomain: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
custompref_gk_tk_line_paragraphs: Data: 0.31MB + Index: 0.00MB + Engine InnoDB
custompref_gk_tk_spheres: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
custompref_learndash_user_activity: Data: 33.53MB + Index: 86.66MB + Engine InnoDB
custompref_learndash_user_activity_meta: Data: 25.56MB + Index: 24.06MB + Engine InnoDB
custompref_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
custompref_options: Data: 28.25MB + Index: 5.03MB + Engine InnoDB
custompref_postmeta: Data: 858.00MB + Index: 268.53MB + Engine InnoDB
custompref_posts: Data: 506.47MB + Index: 41.33MB + Engine InnoDB
custompref_redirection_404: Data: 8.02MB + Index: 7.05MB + Engine InnoDB
custompref_redirection_groups: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
custompref_redirection_items: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
custompref_redirection_logs: Data: 10.02MB + Index: 4.30MB + Engine InnoDB
custompref_sib_model_contact: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
custompref_sib_model_country: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
custompref_sib_model_forms: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
custompref_sib_model_users: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
custompref_signups: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
custompref_simple_history: Data: 73.13MB + Index: 27.08MB + Engine InnoDB
custompref_simple_history_contexts: Data: 359.02MB + Index: 203.03MB + Engine InnoDB
custompref_slc_simple_login_captcha: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
custompref_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
custompref_terms: Data: 0.08MB + Index: 0.09MB + Engine InnoDB
custompref_term_relationships: Data: 2.50MB + Index: 1.52MB + Engine InnoDB
custompref_term_taxonomy: Data: 0.08MB + Index: 0.11MB + Engine InnoDB
custompref_trp_dictionary_en_gb_bg_bg: Data: 5.52MB + Index: 3.14MB + Engine InnoDB
custompref_trp_dictionary_en_gb_ru_ru: Data: 10.52MB + Index: 8.58MB + Engine InnoDB
custompref_trp_gettext_bg_bg: Data: 1.52MB + Index: 0.67MB + Engine InnoDB
custompref_trp_gettext_en_gb: Data: 2.52MB + Index: 3.33MB + Engine InnoDB
custompref_trp_gettext_ru_ru: Data: 1.52MB + Index: 0.66MB + Engine InnoDB
custompref_trp_original_meta: Data: 1.52MB + Index: 0.94MB + Engine InnoDB
custompref_trp_original_strings: Data: 10.52MB + Index: 5.55MB + Engine InnoDB
custompref_uap_action_log: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
custompref_uap_action_logs_view: Data: 0.00MB + Index: 0.00MB + Engine
custompref_uap_action_log_meta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
custompref_uap_closure_log: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
custompref_uap_closure_log_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
custompref_uap_recipe_log: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
custompref_uap_recipe_logs_view: Data: 0.00MB + Index: 0.00MB + Engine
custompref_uap_trigger_log: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
custompref_uap_trigger_logs_view: Data: 0.00MB + Index: 0.00MB + Engine
custompref_uap_trigger_log_meta: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
custompref_ulike: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
custompref_ulike_activities: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
custompref_ulike_comments: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
custompref_ulike_forums: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
custompref_ulike_meta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
custompref_usermeta: Data: 140.75MB + Index: 99.27MB + Engine InnoDB
custompref_users: Data: 3.52MB + Index: 4.53MB + Engine InnoDB
custompref_vimeography_gallery: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
custompref_vimeography_gallery_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
custompref_vimeography_pro_filters: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
custompref_vimeography_pro_gallery_filters: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
custompref_vimeography_pro_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
custompref_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
custompref_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
custompref_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
custompref_wc_customer_lookup: Data: 2.52MB + Index: 1.84MB + Engine InnoDB
custompref_wc_deposits_payment_plans: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
custompref_wc_deposits_payment_plans_schedule: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
custompref_wc_download_log: Data: 5.52MB + Index: 6.03MB + Engine InnoDB
custompref_wc_order_coupon_lookup: Data: 0.17MB + Index: 0.23MB + Engine InnoDB
custompref_wc_order_product_lookup: Data: 4.48MB + Index: 5.94MB + Engine InnoDB
custompref_wc_order_stats: Data: 4.52MB + Index: 4.48MB + Engine InnoDB
custompref_wc_order_tax_lookup: Data: 2.52MB + Index: 3.03MB + Engine InnoDB
custompref_wc_product_meta_lookup: Data: 0.05MB + Index: 0.09MB + Engine InnoDB
custompref_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
custompref_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
custompref_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
custompref_woocommerce_exported_csv_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
custompref_wpfm_backup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
custompref_wpmailsmtp_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
custompref_wpmm_subscribers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
custompref_custompref_pro_quiz_category: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
custompref_custompref_pro_quiz_form: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
custompref_custompref_pro_quiz_lock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
custompref_custompref_pro_quiz_master: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
custompref_custompref_pro_quiz_prerequisite: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
custompref_custompref_pro_quiz_question: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
custompref_custompref_pro_quiz_statistic: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
custompref_custompref_pro_quiz_statistic_ref: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
custompref_custompref_pro_quiz_template: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
custompref_custompref_pro_quiz_toplist: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
custompref_wt_iew_action_history: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
custompref_wt_iew_cron: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
custompref_wt_iew_ftp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
custompref_wt_iew_mapping_template: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
custompref_yoast_indexable: Data: 111.64MB + Index: 49.66MB + Engine InnoDB
custompref_yoast_indexable_hierarchy: Data: 7.42MB + Index: 10.13MB + Engine InnoDB
custompref_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
custompref_yoast_primary_term: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
custompref_yoast_seo_links: Data: 6.31MB + Index: 4.67MB + Engine InnoDB

### Post Type Counts ###

acf-field: 260
acf-field-group: 8
anr-post: 1
app_page: 2
attachment: 4969
bp_ps_form: 1
bp-email: 38
bp-group-type: 9
bp-member-type: 6
bpgtc_group_tab: 18
bpptc_profile_tab: 1
buddyboss_fonts: 2
coursenote: 11563
custom_css: 6
customize_changeset: 5
docs: 91
elementor_library: 58
fc_template: 12
follow_up_email: 11
forum: 243
gk_dream_arc: 5
gk_replay: 14
groups: 168
language_switcher: 4
nav_menu_item: 93
oembed_cache: 353
page: 538
post: 198
postman_sent_mail: 900
product: 106
product_variation: 12
reply: 12950
revision: 22323
sfwd-certificates: 1
sfwd-courses: 13
sfwd-lessons: 178
sfwd-question: 1
sfwd-quiz: 1
sfwd-topic: 381
shop_coupon: 4491
shop_order: 49753
shop_order_refund: 422
topic: 2413
uo-recipe: 1
uo-trigger: 1
user_request: 5
vc_grid_item: 2
vc_settings_preset: 16
wc_membership_plan: 99
wc_user_membership: 90310
custompref_block: 28

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (57) ###

Gravity Forms: by Gravity Forms – 2.5.14
ACF Flexible Layouts Manager: by Valentin PELLEGRIN – 1.1.6
Advanced Custom Fields PRO: by Delicious Brains – 5.10.2
Advanced noCaptcha & invisible Captcha: by WP White Security – 6.1.7
AffiliateWP: by Sandhills Development
LLC – 2.7.8

AffiliateWP - Affiliate Area Tabs: by Sandhills Development
LLC – 1.4

AffiliateWP - Show Affiliate Coupons: by AffiliateWP – 1.0.7
BestAzon - Localize Amazon Links: by AwesomeAffiliatePlugins – 5.2
BetterDocs Pro: by WPDeveloper – 1.6.11
BetterDocs: by WPDeveloper – 1.9.7
BuddyPress Profile Visibility Manager: by BuddyDev – 1.8.6
BuddyBoss Platform Pro: by BuddyBoss – 1.1.6
BuddyBoss Platform: by BuddyBoss – 1.8.0
BuddyPress Group Tabs Creator Pro: by BuddyDev – 1.1.9
BuddyPress User Profile Tabs Creator Pro: by BuddyDev – 1.2.6
Yoast Duplicate Post: by Enrico Battocchi and Team Yoast – 4.1.2
Elementor Pro: by Elementor.com – 3.5.0
Elementor: by Elementor.com – 3.4.7
FluentCRM - Marketing Automation For WordPress: by Fluent CRM – 2.3.0
FluentSMTP: by FluentSMTP & WPManageNinja Team – 2.1.0
FluentCRM Pro: by Fluent CRM – 2.3.1
Go Live Update Urls: by OnPoint Plugins – 6.3.3
Product Sales Report Pro for WooCommerce: by Aspen Grove Studios – 2.2.17
If Menu - Visibility control for menu items: by Layered – 0.16.2
WPBakery Page Builder: by Michael M - WPBakery.com – 6.7.0
LearnDash Course theme color: by clientdomain – 1.5
Notes for LearnDash: by SnapOrbital – 1.6.7.2
LearnDash LMS - ProPanel: by LearnDash – 2.1.4.1
LearnDash LMS - WooCommerce Integration: by LearnDash – 1.9.3.3
Newsletter, SMTP, Email marketing and Subscribe forms by Sendinblue: by Sendinblue – 3.1.23
Redirection: by John Godley – 5.1.3
LearnDash LMS: by LearnDash – 3.5.1.3
Simple History: by Pär Thernström – 2.43.0
TranslatePress - Business: by Cozmoslabs
Razvan Mocanu
Madalin Ungureanu – 1.0.7

TranslatePress - Multilingual: by Cozmoslabs
Razvan Mocanu
Madalin Ungureanu
Cristophor Hurduban – 2.1.5

Two Factor: by Plugin Contributors – 0.7.1
Ultimate Addons for Gutenberg: by Brainstorm Force – 1.21.0
Ultimate Addons for Elementor: by Brainstorm Force – 1.35.0
Uncanny Toolkit for LearnDash: by Uncanny Owl – 3.5.2
Uncanny Toolkit Pro for LearnDash: by Uncanny Owl – 3.7.10
User Role Editor: by Vladimir Garagulya – 4.60.2
Vimeography Developer Bundle: by Dave Kiss – 2.1.1
Vimeography Pro: by Dave Kiss – 2.1.1
Vimeography: by Dave Kiss – 2.3.0
Advanced Order Export For WooCommerce: by AlgolPlus – 3.2.0
WooCommerce Customer/Order/Coupon Export: by SkyVerge – 5.3.3
WooCommerce EU/UK VAT Compliance (Premium): by David Anderson – 1.25.8
WooCommerce Gravity Forms Product Add-Ons: by Element Stark – 3.3.24
WooCommerce Memberships: by SkyVerge – 1.22.7
WooCommerce Name Your Price: by Kathy Darling – 3.3.4 (update to version 3.3.5 is available)
WooCommerce PayPal Payments: by WooCommerce – 1.6.1
Sendinblue - WooCommerce Email Marketing: by Sendinblue – 2.0.31
WooCommerce Smart Coupons: by StoreApps – 4.32.0
WooCommerce: by Automattic – 5.9.0
Yoast SEO: by Team Yoast – 17.5
WP Crontrol: by John Blackbourn & contributors – 1.11.0

### Inactive Plugins (11) ###

AffiliateWP - Affiliate Portal: by Sandhills Development
LLC – 1.0.9

BuddyBoss App: by BuddyBoss – 1.3.6
BuddyPress Extended Friendship Request: by BuddyDev Team – 1.2.1
Enable jQuery Migrate Helper: by The WordPress Team – 1.3.0
Gelato Integration for WooCommerce: by Gelato – 1.0.0
Post SMTP: by Yehuda Hassine – 2.0.23
RumbleTalk Chat: by RumbleTalk Ltd – 5.8.1
Uncanny Automator: by Uncanny Owl – 3.3.0.1
WooCommerce PayPal Checkout Gateway: by WooCommerce – 2.1.3
WordPress Users & WooCommerce Customers Import Export(BASIC): by WebToffee – 2.2.2
WP Rocket: by WP Media – 3.8.8

### Dropin Plugins (1) ###

php-error.php: php-error.php

### Must Use Plugins (10) ###

admin-settings.php: by  –
BuddyBoss API Caching: by BuddyBoss – 1.0.1
ct-mods.php: by  –
Disable Emojis: by Ryan Hellyer – 1.5.2
force-theme.php: by  –
Hide comments: by Xavier Keeling – 0.1
LearnDash LMS Multisite: by LearnDash – 1.0.0
Post-type settings: by Xavier Keeling – 0.1
rewrites.php: by  –
wp-dashboard.php: by  –

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: course (course)
external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #300262 - /store-home/
Basket: #300004 - /cart/
Checkout: #300005 - /checkout/
My account: #300006 - /my-account/
Terms and conditions: #300249 - /terms-and-conditions/

### Theme ###

Name: BuddyBoss Child clientdomain Theme
Version: 1.0
Author URL: http://clientdomain.com
Child Theme: ✔
Parent Theme Name: BuddyBoss Theme
Parent Theme Version: 1.7.8.1
Parent Theme Author URL: https://www.buddyboss.com/
WooCommerce Support: ✔

### Templates ###

Overrides: buddyboss-theme-child/woocommerce/checkout/form-checkout.php
buddyboss-theme/woocommerce/checkout/review-order.php
buddyboss-theme-child/woocommerce/checkout/thankyou.php
buddyboss-theme-child/content-single-product.php
buddyboss-theme-child/woocommerce/emails/email-footer.php
buddyboss-theme/woocommerce/global/quantity-input.php
buddyboss-theme/woocommerce/myaccount/dashboard.php
buddyboss-theme/woocommerce/myaccount/downloads.php
buddyboss-theme/woocommerce/myaccount/form-edit-account.php
buddyboss-theme/woocommerce/myaccount/form-edit-address.php
buddyboss-theme/woocommerce/myaccount/form-login.php
buddyboss-theme/woocommerce/myaccount/form-lost-password.php
buddyboss-theme/woocommerce/myaccount/my-account.php
buddyboss-theme/woocommerce/myaccount/my-address.php
buddyboss-theme/woocommerce/myaccount/my-downloads.php
buddyboss-theme/woocommerce/myaccount/my-orders.php
buddyboss-theme/woocommerce/myaccount/navigation.php
buddyboss-theme/woocommerce/myaccount/orders.php
buddyboss-theme/woocommerce/myaccount/view-order.php
buddyboss-theme/woocommerce/order/order-details-customer.php
buddyboss-theme/woocommerce/order/order-details-item.php
buddyboss-theme/woocommerce/order/order-details.php
buddyboss-theme-child/woocommerce/single-product/add-to-cart/external.php
buddyboss-theme-child/woocommerce/single-product/add-to-cart/simple.php
buddyboss-theme/woocommerce/single-product/meta.php
buddyboss-theme-child/woocommerce/single-product/product-image.php
buddyboss-theme-child/woocommerce/single-product/related.php
buddyboss-theme-child/woocommerce/single-product/review.php
buddyboss-theme-child/woocommerce/single-product/short-description.php


### Memberships ###

Restriction mode:: Hide content only
Public content:: Pages: 6 itemsProducts: 2 items
Excluded from discounts:: –
Membership plans:: 99

### WooCommerce PayPal Payments ###

Onboarded: Yes
Shop country code: GB
PayPal card processing available in country: Yes
Pay Later messaging available in country: Yes
Vault enabled: No

### WooCommerce Customer/Order/Coupon Export ###

Automated exports: 0
Custom formats: 0
Next export: Not scheduled

### Action Scheduler ###

Canceled: 1
Oldest: 2021-10-29 17:01:15 +0100
Newest: 2021-10-29 17:01:15 +0100

Complete: 70,478
Oldest: 2021-10-14 18:01:16 +0100
Newest: 2021-11-13 13:49:58 +0000

Failed: 3
Oldest: 2020-11-10 21:25:04 +0000
Newest: 2020-11-10 21:25:04 +0000

Pending: 18
Oldest: 2021-11-13 13:52:18 +0000
Newest: 2021-11-14 01:15:51 +0000


### Name Your Price ###

Version: 
Template overrides: –

### Status report information ###

Generated at: 2021-11-13 13:52:51 +00:00
`
Also I checked on the plugin list if another plugin is using the same schedule event and not, all is being use by woocommerce plugin only

image

**Comment by Ekliptor** [comment]
OK most likely not plugin-related.
Before we go for the "brutal" fix adding a 2nd cron to watch if the 1st cron is running, I would like to understand **how** the cron still can get lost?

By digging through the code, I see the cron definitely gets stored in DB immediately, so a crash/timeout/abort could not stop it from being re-scheduled. To call stack to store is a new cron in DB is *roughly* as follows:
`wp_schedule_single_event()` -> `_set_cron_array()` -> `update_option()` -> `$wpdb->update()`

Any idea from WP team?
