### PR TITLE
Initialize BlockTemplatesController for block themes only

### LINKED ISSUE #46461: Prevent 'BlockTemplatesController::add_archive_product_to_eligible_for_fallback_templates' to leak into classic themes
There is a method in `BlockTemplatesController` called `add_archive_product_to_eligible_for_fallback_templates` which seems to be leaking into classic themes. From my investigation, it doesn't have any impact in functionality, but we should make it so it only runs in block themes to avoid running unnecessary code and to prevent unexpected bugs.

The method can be found here:

https://github.com/woocommerce/woocommerce/blob/de54195c3ab3a091c3c406984622b61a6f8fa413/plugins/woocommerce/src/Blocks/BlockTemplatesController.php#L191-L215

### LINKED ISSUE #46463: Prevent 'BlockTemplatesController' to be initialized in classic themes which don't support templates nor template parts
`BlockTemplatesController` is a class used to handle block templates and templates parts.

While several of its methods check for the theme to support block templates/block templates parts before running, there are several other methods which don't have those checks, which is easy to cause bugs (see https://github.com/woocommerce/woocommerce/pull/46429 and https://github.com/woocommerce/woocommerce/issues/46461).

This issue is about try to only initialize `BlockTemplatesController` when the theme supports block templates or block template parts. So `BlockTemplatesController` wouldn't be initialized in classic themes at all.

One challenge is that the `check_should_use_blockified_product_grid_templates` method needs to be run also in classic themes, so it should be moved out of this class:

https://github.com/woocommerce/woocommerce/blob/de54195c3ab3a091c3c406984622b61a6f8fa413/plugins/woocommerce/src/Blocks/BlockTemplatesController.php#L217-L235

### LINKED ISSUE #48468: Ensure BlockTemplatesController is initialized for classic themes supporting block templates parts
While working on #46463, we [realized](https://github.com/woocommerce/woocommerce/pull/48382#discussion_r1636556494) that we don't have a test that ensures the `BlockTemplatesController` is initialized for themes that support block template parts. Let's add that test.

### PR DESCRIPTION
**Pull request by Aljullu**
### Changes proposed in this Pull Request:

Closes https://github.com/woocommerce/woocommerce/issues/46463.
Closes https://github.com/woocommerce/woocommerce/issues/46461.
Closes https://github.com/woocommerce/woocommerce/issues/48468.

Supersedes https://github.com/woocommerce/woocommerce/pull/48382. Kudos to @WunderBart who did most of the hard work on this and to @tjcafferkey who suggested a path forward to initialize BlockTemplatesController. :raised_hands: 

### How to test the changes in this Pull Request:

This PR is a refactor, testing is based on making sure there are no regressions:

**With a block theme**

1. Go to Appearance > Editor > Templates.
2. Modify some WooCommerce templates (ie: Product Catalog, Single Product...).
3. Visit those pages in the frontend and verify the edits have been applied correctly.
4. Go back to the editor and reset the edited templates.
5. Verify the edits have been successfully reset in the frontend.

**With a classic theme that supports block template parts**

You can install this theme [storefront-child-i.zip](https://github.com/user-attachments/files/16054910/storefront-child-i.zip) (you will also need to have Storefront installed).

1. Go to Appearance > Template parts.
2. Modify the Mini-Cart template part.
3. Create a page and add the Mini-Cart block. In the frontend, open the Mini-Cart and verify the edits were applied correctly.
4. Go back to the editor and reset the Mini-Cart template part.
5. Verify the WooCommerce default template part is visible again when opening the Mini-Cart in the frontend.

**With a classic theme that supports block template parts and has a custom Mini-Cart template part**

You can install this theme [storefront-child-ii.zip](https://github.com/user-attachments/files/16054901/storefront-child-ii.zip) (you will also need to have Storefront installed).

1. Go to Appearance > Template parts.
2. Modify the Mini-Cart template part.
3. Create a page and add the Mini-Cart block. In the frontend, open the Mini-Cart and verify the edits were applied correctly.
4. Go back to the editor and reset the Mini-Cart template part.
5. Verify the theme template part is visible again when opening the Mini-Cart in the frontend.

**Blockified templates option**

We have some code that runs when switching themes. 

1. Switch your theme to a classic theme (ie: Storefront).
2. Go to your database and modify, the option `wc_blocks_use_blockified_product_grid_block_as_template` to false in `wp_options`.
3. Then switch it to a block theme (ie: Twenty Twenty-Four).
4. Go to Appearance > Editor > Templates and verify the templates are blockified. In other words, they are displayed as blocks instead of a gray placeholder:

image

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce/src/Blocks/BlockTemplatesController.php [hunk 1]
```diff
@@ -355,16 +332,26 @@ public function add_block_templates( $query_result, $query, $template_type ) {
...
 			}
 
-			$is_not_custom   = false === array_search(
+			$possible_template_ids = [
 				$theme_slug . '//' . $template_file->slug,
-				array_column( $query_result, 'id' ),
-				true
-			);
+				$theme_slug . '//' . BlockTemplateUtils::DIRECTORY_NAMES['TEMPLATE_PARTS'] . '/' . $template_file->slug,
+				$theme_slug . '//' . BlockTemplateUtils::DIRECTORY_NAMES['DEPRECATED_TEMPLATE_PARTS'] . '/' . $template_file->slug,
```
Comment (Aljullu) [inline plugins/woocommerce/src/Blocks/BlockTemplatesController.php:336]: Template parts in classic themes that support template parts seemed to have a different ID than expected, that's the reason of this change.

File: plugins/woocommerce/src/Blocks/OptionsManager.php [hunk 2]
```diff
@@ -0,0 +1,37 @@
...
+		add_action( 'after_switch_theme', array( $this, 'check_should_use_blockified_product_grid_templates' ), 10, 2 );
+	}
+
+	/**
+	 * Checks the old and current themes and determines if the "wc_blocks_use_blockified_product_grid_block_as_template"
+	 * option need to be updated accordingly.
+	 *
+	 * @return void
+	 */
+	public function check_should_use_blockified_product_grid_templates() {
```
Comment (tjcafferkey) [inline plugins/woocommerce/src/Blocks/OptionsManager.php]: This code feels like it should belong closer to the templating logic. I'd expect an `OptionsManager` class to provide me with generic methods, that would be extended. Whereas this method feels very specific to a single part of functionality.

File: plugins/woocommerce/src/Blocks/BlockTemplatesController.php [hunk 3]
```diff
@@ -28,76 +28,73 @@ public function init() {
...
-					// phpcs:ignore WordPress.Security.NonceVerification.Recommended
-					if ( $current_screen && 'page' === $current_screen->id && ! empty( $_GET['post'] ) && in_array( absint( $_GET['post'] ), array( wc_get_page_id( 'cart' ), wc_get_page_id( 'checkout' ) ), true ) ) {
-						wp_add_inline_style( 'wc-blocks-editor-style', '.edit-post-post-template { display: none; }' );
-					}
-				},
-				10
-			);
-		}
+
+		// By default, the Template Part Block only supports template parts that are in the current theme directory.
```
Comment (tjcafferkey) [inline plugins/woocommerce/src/Blocks/BlockTemplatesController.php:32]: Nit: Shall we normalize the comments with either `//` or `/**` formatting?

File: plugins/woocommerce/src/Blocks/OptionsManager.php (hunk 2 above)
Comment (Aljullu) [reply plugins/woocommerce/src/Blocks/OptionsManager.php]: We intentionally moved this code out from `BlockTemplatesController` because it needs to run when `BlockTemplatesController` is not initialized. The main goal is to make sure `BlockTemplatesController` is not initialized in classic themes.

Would renaming this class from `OptionsManager` to something more specific help? Ie: `TemplateOptions` or something along these lines? :thinking:

File: plugins/woocommerce/src/Blocks/BlockTemplatesController.php [hunk 4]
```diff
@@ -28,76 +28,73 @@ public function init() {
...
+		// This render_callback wrapper allows us to add support for plugin-housed template parts.
+		add_filter(
+			'block_type_metadata_settings',
+			function ( $settings, $metadata ) {
```
Comment (tjcafferkey) [inline plugins/woocommerce/src/Blocks/BlockTemplatesController.php:36]: Just curious as to why these are inline functions instead of methods?

File: plugins/woocommerce/src/Blocks/BlockTemplatesController.php (hunk 3 above)
Comment (Aljullu) [reply plugins/woocommerce/src/Blocks/BlockTemplatesController.php:32]: I think we usually use `/**` for doc blocks and `//` for inline comments, no?

File: plugins/woocommerce/src/Blocks/OptionsManager.php (hunk 2 above)
Comment (tjcafferkey) [reply plugins/woocommerce/src/Blocks/OptionsManager.php]: >Would renaming this class from OptionsManager to something more specific help? Ie: TemplateOptions or something along these lines?

I think that would be better imo otherwise I can see this class getting completely irrelevant methods added to it.

File: plugins/woocommerce/src/Blocks/BlockTemplatesController.php (hunk 4 above)
Comment (Aljullu) [reply plugins/woocommerce/src/Blocks/BlockTemplatesController.php:36]: I don't think there is any specific _why_ other than historical reasons. I'm happy to change that to make it consistent with the rest of the class, but would rather do it in a separate PR to avoid mixing this PR with unrelated changes. How does it sound?

Comment (tjcafferkey) [reply plugins/woocommerce/src/Blocks/BlockTemplatesController.php:36]: >but would rather do it in a separate PR to avoid mixing this PR with unrelated changes. How does it sound?

I think thats fine, using named methods will help give the reader an idea of its intent without having to read the code as well as make it more consistent.

File: plugins/woocommerce/src/Blocks/BlockTemplatesController.php (hunk 3 above)
Comment (tjcafferkey) [reply plugins/woocommerce/src/Blocks/BlockTemplatesController.php:32]: Uh I'm not actually sure but if thats how they're used I think thats fine?

**Comment by tjcafferkey** [comment]
I've given the changes a cursory look over and added some comments but I will likely get around the the testing steps on Monday if that's OK @Aljullu? Also I love to see the tests that have been added 🙌🏻

File: plugins/woocommerce/src/Blocks/OptionsManager.php (hunk 2 above)
Comment (tjcafferkey) [inline plugins/woocommerce/src/Blocks/OptionsManager.php]: Do we have any existing tests for this? Seems like something we should write tests for

**Comment by Aljullu** [comment]
> I've given the changes a cursory look over and added some comments but I will likely get around the the testing steps on Monday if that's OK @Aljullu?

Sure, no hurries! I will also follow-up on your comments next week.

File: plugins/woocommerce/src/Blocks/OptionsManager.php (hunk 2 above)
Comment (Aljullu) [reply plugins/woocommerce/src/Blocks/OptionsManager.php]: Yup, it's tested as part of the BlockTemplatesUtils here:

https://github.com/woocommerce/woocommerce/blob/38d4a9753627068b8034eb909c9105eee830a4e4/plugins/woocommerce/tests/php/src/Blocks/Utils/BlockTemplateUtilsTest.php#L285-L346

Comment (Aljullu) [reply plugins/woocommerce/src/Blocks/OptionsManager.php]: I changed the class name to `TemplateOptions` in bedc8157fde8ed210eaa33b24b59fcef82447f24.

File: plugins/woocommerce/src/Blocks/BlockTemplatesController.php (hunk 3 above)
Comment (Aljullu) [reply plugins/woocommerce/src/Blocks/BlockTemplatesController.php:32]: Well, I see we are a bit inconsistent with comments before `add_filter()` and `add_action()`. I just changed one here 4293b802849451189ce9c87145a882bb317755ab, so at least they are consistent in this file now.

File: plugins/woocommerce/src/Blocks/Domain/Bootstrap.php [hunk 5]
```diff
@@ -122,6 +124,35 @@ function () {
...
 		);
 
+		// We need to initialize BlockTemplatesController and BlockTemplatesRegistry at the end of `after_setup_theme`
+		// so themes had the opportunity to declare support for template parts.
+		add_action(
+			'after_setup_theme',
+			function () {
+				$is_rest = wc()->is_rest_api_request();
+				// phpcs:disable WordPress.Security.ValidatedSanitizedInput.MissingUnslash, WordPress.Security.ValidatedSanitizedInput.InputNotSanitized
+				$is_store_api_request = $is_rest && ! empty( $_SERVER['REQUEST_URI'] ) && ( false !== strpos( $_SERVER['REQUEST_URI'], trailingslashit( rest_get_url_prefix() ) . 'wc/store/' ) );
```
Comment (tjcafferkey) [inline plugins/woocommerce/src/Blocks/Domain/Bootstrap.php]: Shall we turn this into its own method inside this class since we're not using it twice in `Bootstrap.php`?

Comment (tjcafferkey) [reply plugins/woocommerce/src/Blocks/Domain/Bootstrap.php]: There is actually already a method on the `WooCommerce` class [here](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/includes/class-woocommerce.php#L477-L488). Is there any reason we can't/aren't using this?

Comment (Aljullu) [reply plugins/woocommerce/src/Blocks/Domain/Bootstrap.php]: Oh, good catch! I can't think of any reason for not using the `WooCommerce` method. Should be solved in 1a5ca98e7d83d3d4ba07f6d4a8e675b2837dd119.

File: plugins/woocommerce/src/Blocks/TemplateOptions.php [hunk 6]
```diff
@@ -0,0 +1,37 @@
...
+	 * option need to be updated accordingly.
+	 *
+	 * @return void
+	 */
+	public function check_should_use_blockified_product_grid_templates() {
+		$option_name           = Options::WC_BLOCK_USE_BLOCKIFIED_PRODUCT_GRID_BLOCK_AS_TEMPLATE;
+		$should_use_blockified = wc_bool_to_string( wc_current_theme_is_fse_theme() );
+
+		// We don't need to do anything if the user switched to a classic theme or if the option is already set to true.
+		if ( ! $should_use_blockified || get_option( $option_name ) === 'true' ) {
```
Comment (tjcafferkey) [inline plugins/woocommerce/src/Blocks/TemplateOptions.php]: When we are updating the option we are using `wc_bool_to_string` which turns `true` values to `"yes"` and `false` values to `"no"` but when we are operating on the value of this option (line 31) we are comparing against `true`? Is this correct?

Just curious if we have incorrectly assumed `wc_bool_to_string` would turn `true` into `"true"` based on this code here on line 31.

```suggestion
		if ( ! $should_use_blockified || get_option( $option_name ) === wc_bool_to_string( true ) ) {
```

**Comment by tjcafferkey** [comment]
Some testing notes

* If I make a change to `Product Catalog` the same change is applied to all my product archive templates. If I reset my `Products by Category` template my changes are reset on all my product archive templates. I'm not sure if this is expected, or related to this PR but I do seem to remember us agreeing to remove this functionality of syncing templates?
* Sometimes the menu hidden behind the three dots on the all templates view says ["Delete"](https://github.com/woocommerce/woocommerce/assets/8639742/76ec39f3-c63a-4cd4-b89b-5ac353b8292b) other times it says ["Reset"](https://github.com/woocommerce/woocommerce/assets/8639742/7dd751aa-2fd3-4ee8-b37d-daf4d94606f0)? When I've selected delete, it does the same thing. Not sure why there is different wording but they have different connotations (see screenshots below)
* On the "All templates" [view it looks like some of the blocks aren't registering for the Single Product template](https://github.com/woocommerce/woocommerce/assets/8639742/bf79be66-d726-45f4-81cb-dc2717e58d73) but when you go into the template they load as expected. Maybe something that can be tackled/fix as part of https://github.com/woocommerce/woocommerce/pull/47819
* ~On step 2 under "With a classic theme that supports block template parts and has a custom Mini-Cart template part" I get an error when saving the template part seen [here](https://github.com/woocommerce/woocommerce/assets/8639742/0ade5c80-2d0b-4104-a62f-20caa244d038).~

File: plugins/woocommerce/src/Blocks/TemplateOptions.php (hunk 6 above)
Comment (tjcafferkey) [reply plugins/woocommerce/src/Blocks/TemplateOptions.php]: An alternative to the above suggestion would be to use our [`wc_string_to_bool` function](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/includes/wc-formatting-functions.php#L25) which I think would be the better option.

```suggestion
		if ( ! $should_use_blockified || wc_string_to_bool( get_option( $option_name ) ) ) {
```

Comment (Aljullu) [reply plugins/woocommerce/src/Blocks/TemplateOptions.php]: Your suggestion makes sense, merging it. :slightly_smiling_face:

**Comment by Aljullu** [comment]
Thanks for the in-depth review, @tjcafferkey!

> * If I make a change to `Product Catalog` the same change is applied to all my product archive templates. If I reset my `Products by Category` template my changes are reset on all my product archive templates. I'm not sure if this is expected, or related to this PR but I do seem to remember us agreeing to remove this functionality of syncing templates?

Yeah, according to what's described in https://github.com/woocommerce/woocommerce/issues/42532, _Products by Category_, _Products by Tag_, etc. won't exist by default, but when rendering those templates in the frontend they will still fall back to the _Product Catalog_ template. Instead of doing all kind of behind-the-scene magic with templates, we will be able to simply use the [`template_hierarchy` hook](https://developer.wordpress.org/reference/hooks/type_template_hierarchy/). I played around with this idea in https://github.com/woocommerce/woocommerce/pull/44778, but it's blocked by making templates to be attached to the theme (https://github.com/woocommerce/woocommerce/issues/42181), which at its turn, is blocked by the upstream PR (https://github.com/WordPress/gutenberg/pull/61577).

> * Sometimes the menu hidden behind the three dots on the all templates view says ["Delete"](https://github.com/woocommerce/woocommerce/assets/8639742/76ec39f3-c63a-4cd4-b89b-5ac353b8292b) other times it says ["Reset"](https://github.com/woocommerce/woocommerce/assets/8639742/7dd751aa-2fd3-4ee8-b37d-daf4d94606f0)? When I've selected delete, it does the same thing. Not sure why there is different wording but they have different connotations (see screenshots below)

I will keep an eye on this one. I also see in one case you are allowed to rename the template while in the other you aren't. That's weird. :thinking: 

> * On the "All templates" [view it looks like some of the blocks aren't registering for the Single Product template](https://github.com/woocommerce/woocommerce/assets/8639742/bf79be66-d726-45f4-81cb-dc2717e58d73) but when you go into the template they load as expected. Maybe something that can be tackled/fix as part of https://github.com/woocommerce/woocommerce/pull/47819

I guess that issue is this one: https://github.com/woocommerce/woocommerce/issues/46781?

> * ~On step 2 under "With a classic theme that supports block template parts and has a custom Mini-Cart template part" I get an error when saving the template part seen [here](https://github.com/woocommerce/woocommerce/assets/8639742/0ade5c80-2d0b-4104-a62f-20caa244d038).~

Update: we discovered this is an issue from Gutenberg. I filled it here: https://github.com/WordPress/gutenberg/issues/63030.

**Comment by tjcafferkey** [comment]
>I will keep an eye on this one. I also see in one case you are allowed to rename the template while in the other you aren't. That's weird. 🤔

I did have xdebug running which _could_ have caused some interference somehow. I've just retested this without and everything works as expected.

File: plugins/woocommerce/src/Blocks/TemplateOptions.php [hunk 7]
```diff
@@ -0,0 +1,39 @@
...
+
+	/**
+	 * Checks the old and current themes and determines if the "wc_blocks_use_blockified_product_grid_block_as_template"
+	 * option need to be updated accordingly.
+	 *
+	 * @return void
+	 */
+	public function check_should_use_blockified_product_grid_templates() {
+		$option_name           = Options::WC_BLOCK_USE_BLOCKIFIED_PRODUCT_GRID_BLOCK_AS_TEMPLATE;
+		$should_use_blockified = wc_bool_to_string( wc_current_theme_is_fse_theme() );
```
Comment (tjcafferkey) [inline plugins/woocommerce/src/Blocks/TemplateOptions.php]: Below we are using `! $should_use_blockified` in the conditional so if we use `wc_bool_to_string()` on this value it will never be falsey since `"no"` and `"yes"` will resolve to `true`. When we update the option value anyway we use `wc_bool_to_string()` before storing it anyway.

```suggestion
		$should_use_blockified = wc_current_theme_is_fse_theme();
```

File: plugins/woocommerce/src/Blocks/TemplateOptions.php [hunk 8]
```diff
@@ -0,0 +1,39 @@
...
+		add_action( 'after_switch_theme', array( $this, 'check_should_use_blockified_product_grid_templates' ), 10, 2 );
+	}
+
+	/**
+	 * Checks the old and current themes and determines if the "wc_blocks_use_blockified_product_grid_block_as_template"
+	 * option need to be updated accordingly.
+	 *
+	 * @return void
+	 */
+	public function check_should_use_blockified_product_grid_templates() {
```
Comment (tjcafferkey) [inline plugins/woocommerce/src/Blocks/TemplateOptions.php]: We are currently storing "yes" or "no" values here which means when we are doing comparisons there's a lot of conversions going on to check whether they are truthy or falsey. We can optimize this whilst maintaining these old values by refactoring below which will save new values in the database as `1` or `0` instead.

```php
	public function check_should_use_blockified_product_grid_templates() {
		$option_name = Options::WC_BLOCK_USE_BLOCKIFIED_PRODUCT_GRID_BLOCK_AS_TEMPLATE;
		// We previously stored "yes" or "no" values. This will convert them to true or false.
		$option_value          = wc_string_to_bool( get_option( $option_name ) );
		$should_use_blockified = wc_current_theme_is_fse_theme();

		// We don't need to do anything if the user switched to a classic theme or if the option is already set to true.
		if ( ! $should_use_blockified || $option_value ) {
			return;
		}

		update_option( $option_name, $should_use_blockified );
	}
```

Comment (Aljullu) [reply plugins/woocommerce/src/Blocks/TemplateOptions.php]: Good catches! I updated it in 8ae1080c6f1da1188010f5b9624da03ab9b85861 and f76d28d6680c03ad72df01740bf0163d51c59e6a. I did a small change to keep its behavior as it was, until now we weren't updating the option when switching between block themes, so I kept it that way.

**Review by tjcafferkey — APPROVED** [review]
Great work on this @Aljullu and I appreciate the additional test coverage needed to support some of the refactoring. It all LsGTM now 🎉

File: plugins/woocommerce-blocks/tests/e2e/tests/templates/template-part-customization.classic_theme_with_template_parts_support.spec.ts [hunk 9]
```diff
@@ -0,0 +1,163 @@
...
+			await testData.visitPage( { frontendUtils, page } );
+
+			await expect(
+				page.getByText( woocommerceTemplateUserText ).first()
+			).toBeVisible();
+			await expect( page.getByText( userText ) ).toHaveCount( 0 );
+
+			await requestUtils.activateTheme(
+				CLASSIC_CHILD_THEME_WITH_BLOCK_TEMPLATE_PARTS_SUPPORT_SLUG
+			);
```
Comment (WunderBart) [inline plugins/woocommerce-blocks/tests/e2e/tests/templates/template-part-customization.classic_theme_with_template_parts_support.spec.ts]: This won't have any effect here - the theme will be reset to the default one once this test is over!

File: plugins/woocommerce-blocks/tests/e2e/tests/templates/template-part-customization.classic_theme_with_template_parts_support.spec.ts [hunk 10]
```diff
@@ -0,0 +1,163 @@
...
+			page: Page;
+		} ) => {
+			await frontendUtils.goToShop();
+			await frontendUtils.addToCart();
+			await page.goto( '/mini-cart' );
+			const block = await frontendUtils.getBlockByName(
+				'woocommerce/mini-cart'
+			);
+			await block.click();
+		},
```
Comment (WunderBart) [inline plugins/woocommerce-blocks/tests/e2e/tests/templates/template-part-customization.classic_theme_with_template_parts_support.spec.ts]: As per [this guide section](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce-blocks/docs/contributors/e2e-guidelines.md#creating-new-utilities), let's follow the good practice of extending the fixtures instead of defining a utility within the `testData` constant. For example:

```ts
import { Page } from '@playwright/test';
import { test as base, FrontendUtils } from '@woocommerce/e2e-utils';

class TestUtils {
	page: Page;
	frontendUtils: FrontendUtils;

	constructor( {
		page,
		frontendUtils,
	}: {
		page: Page;
		frontendUtils: FrontendUtils;
	} ) {
		this.page = page;
		this.frontendUtils = frontendUtils;
	}

	async openMiniCart() {
		await this.frontendUtils.goToShop();
		await this.frontendUtils.addToCart();
		await this.page.goto( '/mini-cart' );
		const miniCart = await this.frontendUtils.getBlockByName(
			'woocommerce/mini-cart'
		);
		await miniCart.click();
	}
}

const test = base.extend< { testUtils: TestUtils } >( {
	testUtils: async ( { page, frontendUtils }, use ) => {
		await use( new TestUtils( { page, frontendUtils } ) );
	},
} );

// ...

test( 'can be modified and reverted', async ( { testUtils } ) => {
	// ...
	await testUtils.openMiniCart();
	// ...
} );
```

File: plugins/woocommerce-blocks/tests/e2e/tests/templates/template-part-customization.classic_theme_with_template_parts_support.spec.ts [hunk 11]
```diff
@@ -0,0 +1,163 @@
...
+			// Verify the edition can be reverted.
+			await admin.visitSiteEditor( {
+				postType: 'wp_template_part',
+			} );
+			await editor.revertTemplateCustomizations( {
+				templateName: testData.templateName,
+				templateType: 'wp_template_part',
+			} );
+			await testData.visitPage( { frontendUtils, page } );
+			await expect( page.getByText( userText ) ).toHaveCount( 0 );
```
Comment (WunderBart) [inline plugins/woocommerce-blocks/tests/e2e/tests/templates/template-part-customization.classic_theme_with_template_parts_support.spec.ts]: Why are we not checking via the `expect(...).toBeHidden()` here and the other instances?

**Review by WunderBart — COMMENTED** [review]
Thanks for taking this over the line, @Aljullu! 🙇 

I'm leaving a few questions regarding the tests and moving on to the manual testing. 💪

File: plugins/woocommerce-blocks/tests/e2e/tests/templates/template-part-customization.classic_theme_with_template_parts_support.spec.ts (hunk 11 above)
Comment (Aljullu) [reply plugins/woocommerce-blocks/tests/e2e/tests/templates/template-part-customization.classic_theme_with_template_parts_support.spec.ts]: Good question! :smile: I copied it from `template-customization.block_theme.spec.ts`, but now I updated it everywhere (see e1fc725a8e31bb17ad593ace1f8ef0acf5adb5e3), thanks!

File: plugins/woocommerce-blocks/tests/e2e/tests/templates/template-part-customization.classic_theme_with_template_parts_support.spec.ts (hunk 9 above)
Comment (Aljullu) [reply plugins/woocommerce-blocks/tests/e2e/tests/templates/template-part-customization.classic_theme_with_template_parts_support.spec.ts]: Good catch, should be fixed in 006b349e9c15b20c8b88cfc411762a00d35b47db!

File: plugins/woocommerce-blocks/tests/e2e/tests/templates/template-part-customization.classic_theme_with_template_parts_support.spec.ts (hunk 10 above)
Comment (Aljullu) [reply plugins/woocommerce-blocks/tests/e2e/tests/templates/template-part-customization.classic_theme_with_template_parts_support.spec.ts]: Makes a lot of sense. I changed it in fc08b41e652fea8e70dad0aad5fc85440c7fa6f0, `TestUtils` is the same in two files, but I felt it was simpler to keep the duplication than creating a shared util. What do you think?

Comment (WunderBart) [reply plugins/woocommerce-blocks/tests/e2e/tests/templates/template-part-customization.classic_theme_with_template_parts_support.spec.ts]: Sure, I don't mind a little duplication! 😄

File: plugins/woocommerce-blocks/tests/e2e/tests/templates/template-part-customization.classic_theme_with_template_parts.spec.ts [hunk 12]
```diff
@@ -0,0 +1,109 @@
...
+			await testUtils.openMiniCart();
+
+			await expect(
+				page
+					.getByText(
+						`${ templateName } template loaded from classic theme with template part support`
+					)
+					.first()
+			).toBeVisible();
+			await expect( page.getByText( userText ) ).toHaveCount( 0 );
```
Comment (WunderBart) [inline plugins/woocommerce-blocks/tests/e2e/tests/templates/template-part-customization.classic_theme_with_template_parts.spec.ts]: Just one more left! 😛

**Review by WunderBart — APPROVED** [review]
Great work, thank you! 🚀

File: plugins/woocommerce-blocks/tests/e2e/tests/templates/template-part-customization.classic_theme_with_template_parts.spec.ts (hunk 12 above)
Comment (Aljullu) [reply plugins/woocommerce-blocks/tests/e2e/tests/templates/template-part-customization.classic_theme_with_template_parts.spec.ts]: Good catch!
