### PR TITLE
Use state name in Checkout block address card

### LINKED ISSUE #45583: Saved information on Japanese Checkout not showing state name correctly
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

If the website language is set to Japanese, on the saved information card, the state shows as a code instead of the state name.

### Expected behavior

For the state name to show on the address on the saved information card.

### Actual behavior

It shows as a code. If you click on edit, it shows correctly.

image

### Steps to reproduce

1. Set the language of your website to Japanese
2. Save an address 
3. Check the checkout page

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://carol-testing.mystagingwebsite.com
Site address (URL): https://carol-testing.mystagingwebsite.com
WC Version: 8.6.1
REST API Version: ✔ 8.6.1
WC Blocks Version: ✔ 11.8.0-dev
Action Scheduler Version: ✔ 3.7.1
Log Directory Writable: ✔
WP Version: 6.4.3
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 8.2.16
PHP Post Max Size: 2 GB
PHP Time Limit: 1200
PHP Max Input Vars: 6144
cURL Version: 8.6.0
OpenSSL/1.1.1w

SUHOSIN Installed: –
MySQL Version: 10.6.15-MariaDB-log
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.6.1
WC Database Prefix: wp_
Total Database Size: 50.21MB
Database Data Size: 34.02MB
Database Index Size: 16.19MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.09MB + Index: 0.09MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vp_backup_wp_actionscheduler_actions: Data: 2.02MB + Index: 0.89MB + Engine InnoDB
vp_backup_wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vp_backup_wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vp_backup_wp_actionscheduler_logs: Data: 1.14MB + Index: 0.55MB + Engine InnoDB
vp_backup_wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vp_backup_wp_comments: Data: 0.08MB + Index: 0.09MB + Engine InnoDB
vp_backup_wp_gla_attribute_mapping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
vp_backup_wp_gla_budget_recommendations: Data: 0.19MB + Index: 0.14MB + Engine InnoDB
vp_backup_wp_gla_merchant_issues: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
vp_backup_wp_gla_shipping_rates: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vp_backup_wp_gla_shipping_times: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vp_backup_wp_jetpack_sync_queue: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
vp_backup_wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vp_backup_wp_mailpoet_automations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
vp_backup_wp_mailpoet_automation_runs: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
vp_backup_wp_mailpoet_automation_run_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
vp_backup_wp_mailpoet_automation_run_subjects: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vp_backup_wp_mailpoet_automation_triggers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
vp_backup_wp_mailpoet_automation_versions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vp_backup_wp_mailpoet_custom_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vp_backup_wp_mailpoet_dynamic_segment_filters: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vp_backup_wp_mailpoet_feature_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vp_backup_wp_mailpoet_forms: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
vp_backup_wp_mailpoet_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
vp_backup_wp_mailpoet_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vp_backup_wp_mailpoet_newsletters: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
vp_backup_wp_mailpoet_newsletter_links: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
vp_backup_wp_mailpoet_newsletter_option: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vp_backup_wp_mailpoet_newsletter_option_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vp_backup_wp_mailpoet_newsletter_posts: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vp_backup_wp_mailpoet_newsletter_segment: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vp_backup_wp_mailpoet_newsletter_templates: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
vp_backup_wp_mailpoet_scheduled_tasks: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
vp_backup_wp_mailpoet_scheduled_task_subscribers: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vp_backup_wp_mailpoet_segments: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vp_backup_wp_mailpoet_sending_queues: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vp_backup_wp_mailpoet_settings: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vp_backup_wp_mailpoet_statistics_bounces: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
vp_backup_wp_mailpoet_statistics_clicks: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
vp_backup_wp_mailpoet_statistics_forms: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vp_backup_wp_mailpoet_statistics_newsletters: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vp_backup_wp_mailpoet_statistics_opens: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
vp_backup_wp_mailpoet_statistics_unsubscribes: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
vp_backup_wp_mailpoet_statistics_woocommerce_purchases: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
vp_backup_wp_mailpoet_stats_notifications: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vp_backup_wp_mailpoet_subscribers: Data: 0.02MB + Index: 0.23MB + Engine InnoDB
vp_backup_wp_mailpoet_subscriber_custom_field: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vp_backup_wp_mailpoet_subscriber_ips: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vp_backup_wp_mailpoet_subscriber_segment: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vp_backup_wp_mailpoet_subscriber_tag: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vp_backup_wp_mailpoet_tags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vp_backup_wp_mailpoet_user_agents: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vp_backup_wp_mailpoet_user_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vp_backup_wp_options: Data: 1.22MB + Index: 0.06MB + Engine InnoDB
vp_backup_wp_postmeta: Data: 0.38MB + Index: 0.33MB + Engine InnoDB
vp_backup_wp_posts: Data: 0.14MB + Index: 0.06MB + Engine InnoDB
vp_backup_wp_snippets: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vp_backup_wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vp_backup_wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vp_backup_wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vp_backup_wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vp_backup_wp_usermeta: Data: 0.13MB + Index: 0.03MB + Engine InnoDB
vp_backup_wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
vp_backup_wp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
vp_backup_wp_wc_admin_note_actions: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
vp_backup_wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
vp_backup_wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vp_backup_wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vp_backup_wp_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
vp_backup_wp_wc_orders_meta: Data: 0.08MB + Index: 0.13MB + Engine InnoDB
vp_backup_wp_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
vp_backup_wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vp_backup_wp_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vp_backup_wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
vp_backup_wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
vp_backup_wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vp_backup_wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vp_backup_wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vp_backup_wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
vp_backup_wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vp_backup_wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
vp_backup_wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vp_backup_wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vp_backup_wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vp_backup_wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vp_backup_wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
vp_backup_wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vp_backup_wp_woocommerce_order_itemmeta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
vp_backup_wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vp_backup_wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vp_backup_wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vp_backup_wp_woocommerce_sessions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
vp_backup_wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
vp_backup_wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vp_backup_wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
vp_backup_wp_woocommerce_square_customers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
vp_backup_wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
vp_backup_wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vp_backup_wp_wpml_mails: Data: 0.36MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 2.14MB + Index: 1.14MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 1.31MB + Index: 1.73MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.13MB + Index: 0.09MB + Engine InnoDB
wp_gla_attribute_mapping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gla_budget_recommendations: Data: 0.17MB + Index: 0.14MB + Engine InnoDB
wp_gla_merchant_issues: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gla_shipping_rates: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gla_shipping_times: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_jetpack_sync_queue: Data: 0.14MB + Index: 0.06MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_automations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_automation_runs: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_mailpoet_automation_run_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_automation_run_subjects: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_automation_triggers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_automation_versions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_custom_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_dynamic_segment_filters: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_feature_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_forms: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletters: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_newsletter_links: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_newsletter_option: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_option_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_posts: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_segment: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_templates: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_scheduled_tasks: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_scheduled_task_subscribers: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_segments: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_sending_queues: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_settings: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_statistics_bounces: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_statistics_clicks: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_statistics_forms: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_statistics_newsletters: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_statistics_opens: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_mailpoet_statistics_unsubscribes: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_statistics_woocommerce_purchases: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_mailpoet_stats_notifications: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_subscribers: Data: 0.02MB + Index: 0.23MB + Engine InnoDB
wp_mailpoet_subscriber_custom_field: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_subscriber_ips: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_subscriber_segment: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_subscriber_tag: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_tags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_user_agents: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_user_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 2.17MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.52MB + Index: 0.44MB + Engine InnoDB
wp_posts: Data: 0.22MB + Index: 0.06MB + Engine InnoDB
wp_snippets: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.14MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.08MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_orders: Data: 0.05MB + Index: 0.11MB + Engine InnoDB
wp_wc_orders_meta: Data: 0.13MB + Index: 0.22MB + Engine InnoDB
wp_wc_order_addresses: Data: 0.05MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_square_customers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpml_mails: Data: 1.52MB + Index: 0.02MB + Engine InnoDB
__wp_actionscheduler_actions: Data: 2.02MB + Index: 0.73MB + Engine InnoDB
__wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_actionscheduler_logs: Data: 1.38MB + Index: 0.45MB + Engine InnoDB
__wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_comments: Data: 0.06MB + Index: 0.09MB + Engine InnoDB
__wp_gla_attribute_mapping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
__wp_gla_budget_recommendations: Data: 0.19MB + Index: 0.14MB + Engine InnoDB
__wp_gla_merchant_issues: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
__wp_gla_shipping_rates: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_gla_shipping_times: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_mailpoet_automations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
__wp_mailpoet_automation_runs: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
__wp_mailpoet_automation_run_logs: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
__wp_mailpoet_automation_run_subjects: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_mailpoet_automation_triggers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
__wp_mailpoet_automation_versions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_mailpoet_custom_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_mailpoet_dynamic_segment_filters: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_mailpoet_feature_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_mailpoet_forms: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
__wp_mailpoet_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
__wp_mailpoet_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_mailpoet_newsletters: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
__wp_mailpoet_newsletter_links: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
__wp_mailpoet_newsletter_option: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_mailpoet_newsletter_option_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_mailpoet_newsletter_posts: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_mailpoet_newsletter_segment: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_mailpoet_newsletter_templates: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
__wp_mailpoet_scheduled_tasks: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
__wp_mailpoet_scheduled_task_subscribers: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_mailpoet_segments: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_mailpoet_sending_queues: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_mailpoet_settings: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_mailpoet_statistics_bounces: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
__wp_mailpoet_statistics_clicks: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
__wp_mailpoet_statistics_forms: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_mailpoet_statistics_newsletters: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_mailpoet_statistics_opens: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
__wp_mailpoet_statistics_unsubscribes: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
__wp_mailpoet_statistics_woocommerce_purchases: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
__wp_mailpoet_stats_notifications: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_mailpoet_subscribers: Data: 0.02MB + Index: 0.23MB + Engine InnoDB
__wp_mailpoet_subscriber_custom_field: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_mailpoet_subscriber_ips: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_mailpoet_subscriber_segment: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_mailpoet_subscriber_tag: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_mailpoet_tags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_mailpoet_user_agents: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_mailpoet_user_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_options: Data: 2.09MB + Index: 0.06MB + Engine InnoDB
__wp_postmeta: Data: 0.25MB + Index: 0.23MB + Engine InnoDB
__wp_posts: Data: 0.16MB + Index: 0.06MB + Engine InnoDB
__wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_usermeta: Data: 0.13MB + Index: 0.03MB + Engine InnoDB
__wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
__wp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
__wp_wc_admin_note_actions: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
__wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
__wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
__wp_wc_orders_meta: Data: 0.05MB + Index: 0.09MB + Engine InnoDB
__wp_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
__wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
__wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
__wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
__wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
__wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
__wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_woocommerce_sessions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
__wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
__wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
__wp_woocommerce_square_customers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
__wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
__wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB

### Post Type Counts ###

attachment: 37
customize_changeset: 28
custom_css: 1
mailpoet_page: 1
nav_menu_item: 11
page: 9
post: 1
product: 34
product_variation: 34
revision: 70
shop_coupon: 7
shop_order: 62
shop_order_refund: 1
wp_global_styles: 2
wp_navigation: 1
wp_template: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (10) ###

Akismet Anti-spam: Spam Protection: by Automattic - Anti-spam Team – 5.3.1
Code Snippets: by Code Snippets Pro – 3.6.2
Jetpack Protect: by Automattic - Jetpack Security team – 2.0.0
Jetpack: by Automattic – 13.3-a.1
WooCommerce Stripe Gateway: by WooCommerce – 8.0.1
WooPayments: by Automattic – 7.3.0
WooCommerce PayPal Payments: by WooCommerce – 2.5.3 (update to version 2.5.4 is available)
WooCommerce Square: by WooCommerce – 4.5.1
WooCommerce: by Automattic – 8.6.1
WP Mail Logging: by WP Mail Logging Team – 1.12.0

### Inactive Plugins (8) ###

Google Listings and Ads: by WooCommerce – 2.6.2
Loco Translate: by Tim Whitlock – 2.6.6
MailPoet: by MailPoet – 4.46.0
Query Monitor: by John Blackbourn – 3.15.0
User Roles Editor for WooCommerce: by FME ADDONS – 1.0.8
WooCommerce Blocks: by Automattic – 11.7.0
WooCommerce Payfast Gateway: by WooCommerce – 1.6.1
WooCommerce Shipping & Tax: by WooCommerce – 2.5.3

### Dropin Plugins (3) ###

advanced-cache.php: advanced-cache.php
db.php: Query Monitor Database Class (Drop-in)
object-cache.php: Memcached

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to Woo.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: ✔

### WC Pages ###

Shop base: #5 - /shop/
Cart: #6 - /cart/
Checkout: #7 - /checkout/
My account: #8 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 4.5.4
Author URL: https://woo.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### WooPayments ###

Version: 7.3.0
Connected to WPCOM: Yes
WPCOM Blog ID: 226468543
Account ID: acct_1OI81EC8WnAGsBn1
Payment Gateway: Enabled
Test Mode: Enabled
Enabled APMs: card
WooPay: Enabled (product,cart,checkout)
WooPay Incompatible Extensions: No
Apple Pay / Google Pay: Disabled
Fraud Protection Level: basic
Multi-currency: Enabled
Public Key Encryption: Disabled
Auth and Capture: Enabled
Documents: Disabled
Logging: Enabled

### WooCommerce PayPal Payments ###

Onboarded: ✔
Shop country code: CA
WooCommerce currency supported: ✔
Advanced Card Processing available in country: ✔
Pay Later messaging available in country: –
Webhook status: –
PayPal Vault enabled: –
ACDC Vault enabled: –
Logging enabled: –
Reference Transactions: ✔
Used PayPal Checkout plugin: –
Subscriptions Mode: Disabled

### Square ###

Environment: Production
Tokenization Enabled: 
Debug Mode: Off

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
product-virtual-downloadable
product-external-affiliate
product-grouped
product-linked
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: customize-store
minified-js
new-product-management-experience
product-pre-publish-modal
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2024-03-14 18:28:17 -03:00
Options: ✔
Notes: 82
Onboarding: completed

### Action Scheduler ###

Canceled: 18
Oldest: 2024-02-12 19:23:43 +0000
Newest: 2024-03-12 16:37:39 +0000

Complete: 2,714
Oldest: 2024-02-12 14:51:19 +0000
Newest: 2024-03-14 10:50:34 +0000

Failed: 1,682
Oldest: 2023-11-30 10:08:08 +0000
Newest: 2024-02-15 19:57:21 +0000

Pending: 2
Oldest: 2024-03-14 11:50:34 +0000
Newest: 2024-03-14 13:08:49 +0000

### Status report information ###

Generated at: 2024-03-14 07:58:03 -03:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by senadir**
### Changes proposed in this Pull Request:

When we introduced the address card, we didn't take into account that we should use state names, not codes, in building the address. This caused some countries like Algeria and Japan to show the things like DZ-31 instead of Oran.

I also added integration test for this, and setup Checkout to be used with integration tests.

Closes #45583

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. In Checkout, use a Japanese address, fill the whole address form.
2. Refresh the page, make sure the address card shows the state name and not some XX-XX code.

| Before | After |
|--------|--------|
|image |image|

### CODE REVIEW

File: plugins/woocommerce-blocks/assets/js/blocks/checkout/address-card/index.tsx [hunk 1]
```diff
@@ -25,6 +26,19 @@ const AddressCard = ( {
 	target: string;
 	fieldConfig: FormFieldsConfig;
 } ): JSX.Element | null => {
+	const formattedCountry =
+		typeof ALLOWED_COUNTRIES[ address.country ] === 'string'
+			? decodeEntities( ALLOWED_COUNTRIES[ address.country ] )
+			: '';
+
+	const formattedState =
+		typeof ALLOWED_STATES[ address.country ] === 'object' &&
```
Comment (opr) [inline plugins/woocommerce-blocks/assets/js/blocks/checkout/address-card/index.tsx]: this is true for `null`, we do have an `isObject` helper and `objectHasProp` helper in [this file](https://github.com/woocommerce/woocommerce/blob/336591f8d4c9b1b41d079069f67516387566680c/plugins/woocommerce-blocks/assets/js/types/type-guards/object.ts#L7)

File: plugins/woocommerce-blocks/assets/js/blocks/checkout/inner-blocks/checkout-fields-block/frontend.tsx [hunk 2]
```diff
@@ -10,7 +10,7 @@ const FrontendBlock = ( {
 	children,
 	className,
 }: {
-	children: JSX.Element;
+	children: JSX.Element[];
```
Comment (opr) [inline plugins/woocommerce-blocks/assets/js/blocks/checkout/inner-blocks/checkout-fields-block/frontend.tsx]: This is deprecated, I think we can use `ReactElement` instead of `JSX.Element`

when importing you should use it like this:

`import type { ReactElement } from 'react';` (the `type` keyword is important because you get an eslint error otherwise).

**Review by opr — CHANGES_REQUESTED** [review]
The code is working and tests look good, but I left some suggestions, the `isObject` one you should action before merging, but the JSX one isn't critial

File: plugins/woocommerce-blocks/assets/js/blocks/checkout/address-card/index.tsx (hunk 1 above)
Comment (opr) [reply plugins/woocommerce-blocks/assets/js/blocks/checkout/address-card/index.tsx]: image

Comment (senadir) [reply plugins/woocommerce-blocks/assets/js/blocks/checkout/address-card/index.tsx]: Okay, I will update the other place in which this happens as well.

**Review by opr — APPROVED** [review]
Looks good now, if the additional fields E2E test fails I think we can merge, that's addressed in https://github.com/woocommerce/woocommerce/pull/45789#pullrequestreview-1952447847

**Comment by senadir** [comment]
Nothing is failing.
