### PR TITLE
Apply woocommerce_short_description filter before check if excerpt is empty

### LINKED ISSUE #18225: Cannot Filter Short Description If Empty
Should run the filter before checking if it's empty:
https://github.com/woocommerce/woocommerce/blob/master/templates/single-product/short-description.php#L25

```
if ( ! $post->post_excerpt ) {
	return;
}
```

This will make the filter useless if no content in excerpt.
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

### PR DESCRIPTION
**Pull request by claudiosanches**
Closes #18225

### CODE REVIEW

File: templates/single-product/short-description.php [hunk 1]
```diff
@@ -10,23 +10,25 @@
...
+$short_description = apply_filters( 'woocommerce_short_description', $post->post_excerpt );
+
+if ( ! $short_description ) {
 	return;
 }
 
 ?>
 <div class="woocommerce-product-details__short-description">
-    <?php echo apply_filters( 'woocommerce_short_description', $post->post_excerpt ); ?>
+	<?php echo $short_description; // WPCS: XSS ok. ?>
```
Comment (rodrigoprimo) [inline templates/single-product/short-description.php]: @claudiosanches, wouldn't be better to use `esc_html()` instead of telling phpcs to ignore the XSS check?

Comment (claudiosanches) [reply templates/single-product/short-description.php]: `woocommerce_short_description` applies some filters like `the_content`. That's why we are avoiding to escape things here.
