### PR TITLE
Fix the visibility of partially out of stock variable products when using the layered nav widget

### LINKED ISSUE #25524: Explore the feasibility of improved filtering of variations
Now that we have lookup table for products, maybe there are some approaches we could explore to support filtering variations by attributes + in stock/out of stock. 

Ref old issue with some proposed solutions: https://github.com/woocommerce/woocommerce/issues/20689

Note: Within the scope of this issue, we'll cover a proof of concept and write tests for the failing cases. Actual implementation will be handled separately

### PR DESCRIPTION
**Pull request by Konamiman**
### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

This PR fixes an issue that appears when using the layered nav widget (which allows filtering the listed products by an attribute) and there are variable products where some variations have stock and others don't. The issue is that when an attribute is selected for filtering, all variable products having a variation that corresponds to that attribute will be displayed, even those not having stock for that variation (as long as at least one variation has stock).

Example: you sell shoes in two colors, black and blue. Black is out of stock but there's stock for blue. You select "black" (but not "blue") in the widget. The shoes will be included in the products list, but they shouldn't.

Additionally, the count of products that appear in the widget for each attribute is also wrongly including the variable products that don't have stock for the attribute corresponding to that variation.

Note that the original issue is about products out of stock, but the changes act actually on the more wide visibility condition. A product is "visible" if it's published, not excluded for catalog, and has stock. Additionally, a variable product will not be considered visible if the parent product is not.

#### New behavior of the counters

Now the counters count all the variations that are in stock, regardless of whether the filter uses OR or AND logic; that's because one given variation has always one single value for the attribute, so the logic in use is irrelevant. For non-variable products they continue working as usual.

Variation counts will be equivalent to product counts when one single attribute is used to define variations, but if more than one attribute is used that could not be the case. For example you have a "shoes" product with two attributes used for variations, "color" and "style"; if you define variations as "black classic" and "black sport" then "black" will be counted twice in the filter (if both variations have stock).

Also, when using multiple filters they interact with AND logic as usual: only variations that have both attributes in its definition are counted.

Closes #25524.

### How to test the changes in this Pull Request:

**NOTE:** You need to run database updates for the widget counters to work properly!

1. Go to Settings > Products > Inventory, mark "Hide out of stock items from the catalog".
2. Create an attribute named "Color", with the following terms: Black, Brown, Blue, Green, Pink.
3. Create the following variable products: Big shoes, Medium shoes, Small shoes, Kid shoes. Create variations for all the existing colors on all of them. Assign any regular price to all the variations. (Hint: create one product, then duplicate)
4. Modify the products so the following variations are in stock and the others are out of stock:
* Big: black, brown.
* Medium: blue, brown.
* Small: blue, green.
* Kids: green, pink.
5. Add the "Filter by attribute" widget, filtering by color with OR.
6. Try filtering by one or two colors and verify that the results make sense. For example when filtering by "blue" you should see only "Medium shoes" and "Small shoes" (without the fix you would see all four shoe types). Verify also that the results count that appear at the beginning and the end of the list is correct.
7. Change the widget filtering type to AND and try different combinations again. Verify that selecting pink and black displays the "No products available" message.

#### How to test the counters

With the same setup, verify that the counters display the following, no matter what attributes you select in the widget:

image

Now make sure that nothing is selected, then go and change the widget operator to AND. Reload the products page and verify that the behavior is the same.

#### Testing counters with multiple attributes

1. Create an attribute named "Style" with two terms: Classic, and Sport.
2. Modify all the products so that all of them use the new style for variations, but leave the value for all variations as "Any style".
3. Modify the Big shoes product so that the Black variation is Classic, and create a new variation that is Black Sport (leave both in stock).
4. Modify the Medium shoes product so that the Brown variation is Sport (and still has stock).
5. Add the "Filter by attribute" widget, filtering by style with any logic.
6. Reload the page and verify that the counters now appear like this:

image

Note how there are two variations listed for Black, since we added a new one to the Big shoes. Also note how the two classic variations and the single sport variation are listed in the style filter.

7. Select "Black" in the color filter and note how the style filter now displays a value of 1 for classic and 1 for sport, since there's one visible variation of each.
8. Unselect all and select "Blue" in the color filter and note how the style filter disappears, since there's no variation that is blue and has a style associated.
9. Unselect all in the color filter and select "Sport" in the style filter, you will see this:

image

#### Testing visibility with multiple filters

While testing counters with multiple filters you may have noticed that regardless of what filters you selected in the style filter you were still seeing all the products in the catalog (if you don't filter by color). That's because all of the products have visible variations with "Any style" and thus they always match the style filter.

Modify the "Kid shoes" product so that all the variations have the sport style, then select "Classic" in the style filter while not filtering by color, and you'll see that the product disappears from the catalog.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Fix - The filtering widget now works as expected with variable products, displaying those products for which visible variations are available.

### CODE REVIEW

File: includes/abstracts/abstract-wc-product.php [hunk 1]
```diff
@@ -1963,7 +1974,8 @@ public function get_file_download_path( $download_id ) {
 	public function get_price_suffix( $price = '', $qty = 1 ) {
 		$html = '';
 
-		if ( ( $suffix = get_option( 'woocommerce_price_display_suffix' ) ) && wc_tax_enabled() && 'taxable' === $this->get_tax_status() ) { // @phpcs:ignore Squiz.PHP.DisallowMultipleAssignments.Found, WordPress.CodeAnalysis.AssignmentInCondition.Found
+		// phpcs:ignore Squiz.PHP.DisallowMultipleAssignments.FoundInControlStructure, WordPress.CodeAnalysis.AssignmentInCondition.Found
```
Comment (claudiosanches) [inline includes/abstracts/abstract-wc-product.php:1977]: You can remove both lines and fix the conditional.

File: includes/abstracts/abstract-wc-product.php [hunk 2]
```diff
@@ -1871,7 +1881,8 @@ public function get_image( $size = 'woocommerce_thumbnail', $attr = array(), $pl
 	 * @return string
 	 */
 	public function get_shipping_class() {
-		if ( $class_id = $this->get_shipping_class_id() ) { // @phpcs:ignore Squiz.PHP.DisallowMultipleAssignments.Found, WordPress.CodeAnalysis.AssignmentInCondition.Found
+		// phpcs:ignore Squiz.PHP.DisallowMultipleAssignments.FoundInControlStructure, WordPress.CodeAnalysis.AssignmentInCondition.Found
```
Comment (claudiosanches) [inline includes/abstracts/abstract-wc-product.php:1884]: Better stop ignoring those rules, we just need to fix the `if` moving the assignment to a variable.

**Review by claudiosanches — CHANGES_REQUESTED** [review]
I still need to test it in full, but here's some coding standards that can be fixed without excluding from PHPCS.

File: includes/abstracts/abstract-wc-product.php (hunk 1 above)
Comment (Konamiman) [reply includes/abstracts/abstract-wc-product.php:1977]: Ok, thanks for spotting those. I'll wait in case someone else (or yourself) comes up with more, then fix all of them in a single refactoring commit.

File: includes/class-wc-product-variation.php [hunk 3]
```diff
@@ -580,4 +583,22 @@ protected function get_valid_tax_classes() {
 
 		return $valid_classes;
 	}
+
+	/**
+	 * Delete variation, set the ID to 0, and return result.
+	 *
+	 * @since  2.6.0
```
Comment (claudiosanches) [inline includes/class-wc-product-variation.php:590]:
```suggestion
	 * @since  4.4.0
```

File: includes/class-wc-install.php [hunk 4]
```diff
@@ -148,6 +148,10 @@ class WC_Install {
 			'wc_update_400_reset_action_scheduler_migration_status',
 			'wc_update_400_db_version',
 		),
+		'4.2.0' => array(
```
Comment (claudiosanches) [inline includes/class-wc-install.php:151]:
```suggestion
		'4.4.0' => array(
```

File: includes/class-wc-install.php [hunk 5]
```diff
@@ -148,6 +148,10 @@ class WC_Install {
...
+			'wc_update_420_insert_attribute_terms_for_variable_products',
```
Comment (claudiosanches) [inline includes/class-wc-install.php:152]:
```suggestion
			'wc_update_440_insert_attribute_terms_for_variable_products',
```

File: includes/class-wc-install.php [hunk 6]
```diff
@@ -148,6 +148,10 @@ class WC_Install {
...
+			'wc_update_420_db_version',
```
Comment (claudiosanches) [inline includes/class-wc-install.php:153]:
```suggestion
			'wc_update_440_db_version',
```

File: includes/class-wc-query.php [hunk 7]
```diff
@@ -363,6 +367,60 @@ public function remove_product_query_filters( $posts ) {
 		return $posts;
 	}
 
+	/**
+	 * When the request is filtering by attributes via layered nav plugin we need to adjust the total posts count
+	 * to account for variable products having stock in some variations but not in others.
+	 * We do that by just checking if each product is visible.
+	 *
+	 * We also cache the post visibility so that it isn't checked again when displaying the posts list.
+	 *
```
Comment (claudiosanches) [inline includes/class-wc-query.php:376]:
```suggestion
	 *
	 * @since 4.4.0
```

File: includes/class-wc-query.php [hunk 8]
```diff
@@ -666,9 +728,11 @@ public function get_tax_query( $tax_query = array(), $main_query = false ) {
 			$product_visibility_not_in[] = $product_visibility_terms['outofstock'];
 		}
 
+		// phpcs:disable WordPress.Security.NonceVerification.Recommended, WordPress.Security.ValidatedSanitizedInput.MissingUnslash
```
Comment (claudiosanches) [inline includes/class-wc-query.php:731]:
```suggestion
		// phpcs:disable WordPress.Security.NonceVerification.Recommended
```

File: includes/class-wc-query.php [hunk 9]
```diff
@@ -685,6 +749,7 @@ public function get_tax_query( $tax_query = array(), $main_query = false ) {
 				);
 			}
 		}
+		// phpcs:enable WordPress.Security.NonceVerification.Recommended, WordPress.Security.ValidatedSanitizedInput.MissingUnslash
```
Comment (claudiosanches) [inline includes/class-wc-query.php:752]:
```suggestion
		// phpcs:enable WordPress.Security.NonceVerification.Recommended
```

File: includes/class-wc-query.php [hunk 10]
```diff
@@ -666,9 +728,11 @@ public function get_tax_query( $tax_query = array(), $main_query = false ) {
 			$product_visibility_not_in[] = $product_visibility_terms['outofstock'];
 		}
 
+		// phpcs:disable WordPress.Security.NonceVerification.Recommended, WordPress.Security.ValidatedSanitizedInput.MissingUnslash
 		// Filter by rating.
-		if ( isset( $_GET['rating_filter'] ) ) { // WPCS: input var ok, CSRF ok.
-			$rating_filter = array_filter( array_map( 'absint', explode( ',', $_GET['rating_filter'] ) ) ); // WPCS: input var ok, CSRF ok, Sanitization ok.
+		if ( isset( $_GET['rating_filter'] ) ) {
+			// phpcs:ignore WordPress.Security.ValidatedSanitizedInput.InputNotSanitized
+			$rating_filter = array_filter( array_map( 'absint', explode( ',', $_GET['rating_filter'] ) ) );
```
Comment (claudiosanches) [inline includes/class-wc-query.php:735]:
```suggestion
			$rating_filter = array_filter( array_map( 'absint', explode( ',', wp_unslash( $_GET['rating_filter'] ) ) ) );
```

File: includes/data-stores/class-wc-product-variable-data-store-cpt.php [hunk 11]
```diff
@@ -200,7 +200,7 @@ public function read_variation_attributes( &$product ) {
 					$values = array();
 				}
 
-				// Empty value indicates that all options for given attribute are available.
+				// Empty value inicates that all options for given attribute are available.
```
Comment (claudiosanches) [inline includes/data-stores/class-wc-product-variable-data-store-cpt.php:203]: Sounds like you introduced a typo here.

File: includes/wc-template-functions.php [hunk 12]
```diff
@@ -8,6 +8,8 @@
  * @version  2.5.0
  */
 
+// phpcs:disable Generic.Commenting.Todo.TaskFound
```
Comment (claudiosanches) [inline includes/wc-template-functions.php:11]: You can remove it, we should get notices about TODOs.

File: includes/wc-template-functions.php [hunk 13]
```diff
@@ -232,6 +238,27 @@ function wc_set_loop_prop( $prop, $value = '' ) {
 	$GLOBALS['woocommerce_loop'][ $prop ] = $value;
 }
 
+/**
+ * Set the current visbility for a product in the woocommerce_loop global.
+ *
```
Comment (claudiosanches) [inline includes/wc-template-functions.php:243]:
```suggestion
 *
 * @since 4.4.0
```

File: includes/wc-template-functions.php [hunk 14]
```diff
@@ -232,6 +238,27 @@ function wc_set_loop_prop( $prop, $value = '' ) {
...
+ * @param int  $product_id Product it to cache visbiility for.
+ * @param bool $value The poduct visibility value to cache.
+ */
+function wc_set_loop_product_visibility( $product_id, $value ) {
+	wc_set_loop_prop( "product_visibility_$product_id", $value );
+}
+
+/**
+ * Gets the cached current visibility for a product from the woocommerce_loop global.
+ *
```
Comment (claudiosanches) [inline includes/wc-template-functions.php:253]:
```suggestion
 *
 * @since 4.4.0
```

File: includes/wc-template-functions.php [hunk 15]
```diff
@@ -241,7 +268,7 @@ function wc_set_loop_prop( $prop, $value = '' ) {
  * @return bool
  */
 function woocommerce_product_loop() {
-	return have_posts() || 'products' !== woocommerce_get_loop_display_mode();
+	return wc_get_loop_prop( 'total' ) > 0 || 'products' !== woocommerce_get_loop_display_mode();
```
Comment (claudiosanches) [inline includes/wc-template-functions.php:271]: `wc_get_loop_prop()` it set again the loop, also `have_posts()` works different, and probably better keep it for backwards compatibility.

File: includes/wc-template-functions.php [hunk 16]
```diff
@@ -704,7 +731,9 @@ function wc_product_class( $class = '', $product_id = null ) {
  */
 function wc_query_string_form_fields( $values = null, $exclude = array(), $current_key = '', $return = false ) {
 	if ( is_null( $values ) ) {
-		$values = $_GET; // phpcs:ignore WordPress.Security.NonceVerification.Recommended
+		// phpcs:disable WordPress.Security.NonceVerification.Recommended
+		$values = $_GET;
```
Comment (claudiosanches) [inline includes/wc-template-functions.php:735]: It should work with just one line using `phpcs:ignore WordPress.Security.NonceVerification.Recommended`

File: includes/wc-update-functions.php [hunk 17]
```diff
@@ -2110,3 +2130,48 @@ class_exists( 'ActionScheduler_DataController' ) &&
 function wc_update_400_db_version() {
 	WC_Install::update_db_version( '4.0.0' );
 }
+
+/**
+ * Register attributes as terms for variable products, in increments of 100 products.
+ *
+ * @return bool true if there are more products to process.
+ */
+function wc_update_420_insert_attribute_terms_for_variable_products() {
```
Comment (claudiosanches) [inline includes/wc-update-functions.php:2139]:
```suggestion
function wc_update_440_insert_attribute_terms_for_variable_products() {
```

File: includes/wc-update-functions.php [hunk 18]
```diff
@@ -2110,3 +2130,48 @@ class_exists( 'ActionScheduler_DataController' ) &&
...
+		}
+	}
+
+	return update_option( $state_option_name, $page + 1 );
+}
+
+/**
+ * Update DB version.
+ */
+function wc_update_420_db_version() {
```
Comment (claudiosanches) [inline includes/wc-update-functions.php:2175]:
```suggestion
function wc_update_440_db_version() {
```

File: includes/wc-update-functions.php [hunk 19]
```diff
@@ -2110,3 +2130,48 @@ class_exists( 'ActionScheduler_DataController' ) &&
...
+	WC_Install::update_db_version( '4.2.0' );
```
Comment (claudiosanches) [inline includes/wc-update-functions.php:2176]:
```suggestion
	WC_Install::update_db_version( '4.4.0' );
```

File: includes/widgets/class-wc-widget-layered-nav.php [hunk 20]
```diff
@@ -397,17 +433,119 @@ protected function get_filtered_term_product_counts( $term_ids, $taxonomy, $quer
...
 			}
+			// phpcs:enable WordPress.DB.PreparedSQL.NotPrepared
 		}
 
 		return array_map( 'absint', (array) $cached_counts[ $query_hash ] );
 	}
 
+	/**
+	 * Wrapper for WC_Query::get_main_tax_query() to ease unit testing.
+	 *
```
Comment (claudiosanches) [inline includes/widgets/class-wc-widget-layered-nav.php:487]:
```suggestion
	 *
	 * @since 4.4.0
```

File: includes/widgets/class-wc-widget-layered-nav.php [hunk 21]
```diff
@@ -397,17 +433,119 @@ protected function get_filtered_term_product_counts( $term_ids, $taxonomy, $quer
...
+	 * @return array
+	 */
+	protected function get_main_tax_query() {
+		return WC_Query::get_main_tax_query();
+	}
+
+	/**
+	 * Wrapper for WC_Query::get_main_search_query_sql() to ease unit testing.
+	 *
```
Comment (claudiosanches) [inline includes/widgets/class-wc-widget-layered-nav.php:496]:
```suggestion
	 *
	 * @since 4.4.0
```

File: includes/widgets/class-wc-widget-layered-nav.php [hunk 22]
```diff
@@ -397,17 +433,119 @@ protected function get_filtered_term_product_counts( $term_ids, $taxonomy, $quer
...
+	 * @return string
+	 */
+	protected function get_main_search_query_sql() {
+		return WC_Query::get_main_search_query_sql();
+	}
+
+	/**
+	 * Wrapper for WC_Query::get_main_search_queryget_main_meta_query to ease unit testing.
+	 *
```
Comment (claudiosanches) [inline includes/widgets/class-wc-widget-layered-nav.php:505]:
```suggestion
	 *
	 * @since 4.4.0
```

File: includes/widgets/class-wc-widget-layered-nav.php [hunk 23]
```diff
@@ -397,17 +433,119 @@ protected function get_filtered_term_product_counts( $term_ids, $taxonomy, $quer
...
+	 * @return array
+	 */
+	protected function get_main_meta_query() {
+		return WC_Query::get_main_meta_query();
+	}
+
+	/**
+	 * Get a tax query SQL for a given set of taxonomy, terms and operator.
+	 * Uses an intermediate WP_Tax_Query object.
+	 *
```
Comment (claudiosanches) [inline includes/widgets/class-wc-widget-layered-nav.php:515]:
```suggestion
	 *
	 * @since 4.4.0
```

File: includes/widgets/class-wc-widget-layered-nav.php [hunk 24]
```diff
@@ -397,17 +433,119 @@ protected function get_filtered_term_product_counts( $term_ids, $taxonomy, $quer
...
+				'include_children' => false,
+			),
+		);
+
+		return $this->convert_tax_query_to_sql( $query );
+	}
+
+	/**
+	 * Convert a tax query array to SQL using an intermediate WP_Tax_Query object.
+	 *
```
Comment (claudiosanches) [inline includes/widgets/class-wc-widget-layered-nav.php:538]:
```suggestion
	 *
	 * @since 4.4.0
```

**Review by claudiosanches — CHANGES_REQUESTED** [review]
I left some code suggestions for you.

**Comment by MohsinQK** [comment]
@Konamiman  I found a strange problem. the filter is working but a bit buggy.
I have one test Product with the Quantities as shown in the screenshot.
image

in frontend the filter works but buggy for example

1. if I select Green Color (Only) from the color Filter the Product disappears as expected because it's not available in Green Color. (✅)
2.  if I select Large Size (Only) Product appears in the list even its not available in Large Size.(❌)
3. if I select Green Color First **AND** then select Large Size Product not get listed Which is correct.(✅) 
4. if I select Large Size First **AND** then select Green Color Product gets listed which is wrong(❌)

below are all screenshots of the use cases in the order mentioned above in each use case Product must **NOT** appear in the list but in 2 cases it's listing even its Quantity is zero.

This is the Product I am testing on.
image

1. 
image
2. 
image
3. 
image
4. 
image

I think its only working in the Order their Variation attributes are selected from the backend.
Please let me know for any other information you need

**Comment by Konamiman** [comment]
Hi @MohsinQK. Regarding your feedback, I assume you are using two separate filtering widgets, one for color and another one for size, at the same time.

> 2. if I select Large Size (Only) Product appears in the list even its not available in Large Size.(❌)

The product is still available in large size, for the Black and Indigo colors. Therefore it should still be listed, right? Please tell me if I'm missing something else.

> 3. if I select Green Color First AND then select Large Size Product not get listed Which is correct.(✅)
> 4. if I select Large Size First AND then select Green Color Product gets listed which is wrong(❌)

This is indeed inconsistent. I'm not sure if the product should be listed or not in these cases (we have "AND"/"OR" behavior selection for each individual widget, but when using two filters at the same time I don't know how it's supposed to behave), but what's for sure is that it should act in the same way in both cases.

I'll have to take a look at this and check with my team, thanks for reporting!

**Comment by IlPicasso** [comment]
> Hi @MohsinQK. Regarding your feedback, I assume you are using two separate filtering widgets, one for color and another one for size, at the same time.
> 
> 
> 
> > 1. if I select Green Color First AND then select Large Size Product not get listed Which is correct.(✅)
> 
> This is indeed inconsistent. I'm not sure if the product should be listed or not in these cases (we have "AND"/"OR" behavior selection for each individual widget, but when using two filters at the same time I don't know how it's supposed to behave), but what's for sure is that it should act in the same way in both cases.
> 
> I'll have to take a look at this and check with my team, thanks for reporting!

> > 1. if I select Large Size (Only) Product appears in the list even its not available in Large Size.(❌)
> The product is still available in large size, for the Black and Indigo colors. Therefore it should still be listed, right? Please tell me if I'm missing something else.

I believe this is the correct behaviour. 


> > 2. if I select Large Size First AND then select Green Color Product gets listed which is wrong(❌)

If I choose Large and Green, it is supposed that I am searching for an item that HAS Large Size and green color so everything else should dissapear if there is not those attributes, otherwise I wouldnt filter it that way

File: includes/wc-template-functions.php (hunk 16 above)
Comment (Konamiman) [reply includes/wc-template-functions.php:737]: I could swear that I did it that way because it wasn't accepting the one-liner version. But now it is accepting it. 🤷🏻‍♂️

**Comment by Konamiman** [comment]
Hi @MohsinQK and @IlPicasso, I have made changes so that:

* The special behavior for the AND filtering case has been removed. One doesn't usually think "I want to see shoes that have stock of blue AND have stock of green" so that logic was unnecessarily complex and confusing.  Now the filters have always OR behavior as far as variations are concerned, since one given variation will always have one single value for a given attribute.
* Filtering by multiple attributes works as expected, regardless of the order in which you select them.

I hope those changes are sensible and useful.

File: includes/wc-template-functions.php (hunk 15 above)
Comment (Konamiman) [reply includes/wc-template-functions.php]: I don't remember why I made this change, maybe I needed it while I was in the middle of the development; but I have verified that everything still works after reverting to using `have_posts` again so I did and pushed that.

**Comment by MohsinQK** [comment]
@Konamiman yes the Point 2 is correct it's my misunderstanding. but point 4 was not fine for which you made some changes already.

**Review by claudiosanches — APPROVED** [review]
Great work!

**Review by jonathansadowski — APPROVED** [review]
Works well, nice work 👍

**Comment by B-Anders** [comment]
I've noticed a bunch of other strange behavior from that filter. I hope @Konamiman can take a look and make some sense.

To reproduce:

1. Start with one simple product (Product1). It has 2 attributes, "ARTIST" and "COLOR".
ARTIST is used in the attribute filter widget and everything works as expected.
2. Change product to variable and generate two (or more) variations with (only) the second attribute "COLOR". Give it some quantity to have the variations on stock.
3. Check: product shows on the shop and category pages, variations are correct on the single product page.
_Problem: the filter for attribute ARTIST doesn't count the product and the whole widget isn't showing on any pages._
4. Add a second product (Product2): simple, with attribute ARTIST, same value as the first product.
Now the filter widget is displayed again and filters both products correctly. _So now it's counting the variable product too?!?_
5. Edit the variable "Product1" and make variations with the attribute ARTIST and COLOR so that all variations have both attributes (in my case it doesn't make sense to show variation options for ARTIST, but we need this step).
Now the filter is showing on pages as expected even if we delete Product1 > filter is counting the ARTIST attribute.
6. Edit the Product1 again, by unchecking attribute ARTIST from 'use for variations'. Don't touch anything else, just save. The product still has the variations with the COLOR attribute.
_Now the filter is counting the product with ARTIST attribute correctly!!!_
7. ...but the last step only works for the Shop page. The widget isn't showing on the product's category page.

If you know a fix, please let me know, I have just three days left on this project.

**Comment by Konamiman** [comment]
@B-Anders (and everybody having similar issues), please take a look at this: https://github.com/woocommerce/woocommerce/issues/27419#issuecomment-689657524

**Comment by TheGranadilla** [comment]
Hi,
I was wondering if you were still planning to improve nav filtering by attributes for variables products.
Just to hide results for not in stock items. 

I know it's a complex thing, that is discuss since months, maybe years.
But it's also something important. Actually, the filtering return out of stock variations, which is verry not great for customers.
They filter by a product size, and then, in my case, 50% of the products are out of stock in the variation they were looking for...

The only solution would be to delete the variations, but this is going to be a nightmare, especially since those variations might get back in stock one day... 

Is fixing this still an objective?

Thanks !

**Comment by Konamiman** [comment]
Hi @TheGranadilla,

Yes, we plan to take on this problem again at some point in the future. Please see [this comment in the original issue](https://github.com/woocommerce/woocommerce/issues/25524#issuecomment-698869326).

**Comment by MohsinQK** [comment]
This feature stopped working again in the latest releases of woocommerce.
in 4.4 it works as expected, but in 4.7 it's not working as expected.
this is a very important feature. is this removed in the latest version or its by mistake?

WooCommerce 4.7
image

Just Changed the woocommerce version to 4.4 and it works again. out of stock(Red Background) is not in the listing any more.
image

**Comment by TheGranadilla** [comment]
@MohsinQK This was reverted in 4.5 because it introduced new bugs.
But it seems they aren't working anymore on variables products Filtering........
@Konamiman Any update on this? Woocmmerce widget still return out of stock variations....
