### PR TITLE
Implemented PHPCS Fixes in OrdersTableQuery.php and ProductQuery.php

### LINKED ISSUE #51280: PHPCS warning & errors in `OrdersTableQuery.php` and `ProductQuery.php `
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

There are PHPCS warning & errors in `OrdersTableQuery.php` and `ProductQuery.php ` which needs to be fixed.
Screenshot from 2024-09-11 14-40-37
Screenshot from 2024-09-11 14-48-31

### Expected behavior

These PHPCS warning & errors should not come in `OrdersTableQuery.php` and `ProductQuery.php `

### Actual behavior

The PHPCS warning & errors coming in `OrdersTableQuery.php` and `ProductQuery.php `
Screenshot from 2024-09-11 14-40-37
Screenshot from 2024-09-11 14-48-31

### Steps to reproduce

1. Run the PHPCS for `woocommerce/src/Internal/DataStores/Orders/OrdersTableQuery.php`
2. Run the PHPCS for `woocommerce/src/StoreApi/Utilities/ProductQuery.php`

### WordPress Environment

I am using **WooCommerce Version:** 9.4.0-dev

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by narenin**
Closes #51280 .

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Run the PHPCS for `woocommerce/src/Internal/DataStores/Orders/OrdersTableQuery.php`
2. Run the PHPCS for `woocommerce/src/StoreApi/Utilities/ProductQuery.php`

-   [X] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [X] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

### CODE REVIEW

File: plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableQuery.php [hunk 1]
```diff
@@ -353,7 +353,7 @@ private function date_to_date_query_arg( $date ): array {
 		} elseif ( ! is_a( $date, 'WC_DateTime' ) ) {
 			// For backwards compat (see https://github.com/woocommerce/woocommerce/wiki/wc_get_orders-and-WC_Order_Query#date)
 			// only YYYY-MM-DD is considered for date values. Timestamps do support second precision.
-			$date      = wc_string_to_datetime( date( 'Y-m-d', strtotime( $date ) ) );
+			$date      = wc_string_to_datetime( gmdate( 'Y-m-d', strtotime( $date ) ) );
```
Comment (alexflorisca) [inline plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableQuery.php]: I'd rather not change the `date` to `gmdate` here unless there is a specific reason for doing so. This is not a PHPCS change and it may have unintended consequences

File: plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableQuery.php [hunk 2]
```diff
@@ -373,21 +373,23 @@ private function date_to_date_query_arg( $date ): array {
...
+	 * 
 	 * @since 8.2.0
 	 */
 	private function local_time_to_gmt_date_query( $dates_raw, $operator ) {
 		$result = array();
 
 		// Convert YYYY-MM-DD to UTC timestamp. Per https://github.com/woocommerce/woocommerce/wiki/wc_get_orders-and-WC_Order_Query#date only date is relevant (time is ignored).
 		foreach ( $dates_raw as &$raw_date ) {
-			$raw_date = is_numeric( $raw_date ) ? $raw_date : strtotime( get_gmt_from_date( date( 'Y-m-d', strtotime( $raw_date ) ) ) );
+			$raw_date = is_numeric( $raw_date ) ? $raw_date : strtotime( get_gmt_from_date( gmdate( 'Y-m-d', strtotime( $raw_date ) ) ) );
```
Comment (alexflorisca) [inline plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableQuery.php]: same as above, let's leave this as `date`

File: plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableQuery.php (hunk 1 above)
Comment (narenin) [reply plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableQuery.php]: Thanks for the review. I have reverted the `gmdate()` to `date()` in PR.

File: plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableQuery.php (hunk 2 above)
Comment (narenin) [reply plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableQuery.php]: I have reverted the `gmdate()` to `date()` in PR.

Comment (narenin) [reply plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableQuery.php]: @alexflorisca Please check.

**Review by alexflorisca — APPROVED** [review]
Thought I'd started a review but instead I left single comments. Then 2 mins later I saw the changes being pushed!! Freaked me out a bit, thought you were telepathic. 

Anyway thanks for these changes, code is a little cleaner. I smoke tested the All products block which uses `ProductQuery.php` and the Admin orders which uses `OrdersTableQuery.php`. All seems fine. I'll add a changelog and merge once CI passes.

**Comment by narenin** [comment]
@alexflorisca Thanks for your prompt response, and feedback :100:  . I am looking forward to contribute more to WooCommerce.

**Comment by alexflorisca** [comment]
You're very welcome. Look forward to seeing your contributions in the future 👍

**Comment by alexflorisca** [comment]
@narenin Linting script failed, could you take a look and fix the error before I merge?

**Comment by narenin** [comment]
@alexflorisca I have fixed the `Linting script failed` issue, please check.
