### PR TITLE
Variation add to cart logic

### LINKED ISSUE #17601: Variation IDs aren't working with add-to-cart=### unless additional arguments provided
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Log into WP Admin and click Products
2. Set-up a product of type Variable Product
3. Create an Attribute, a custom product attribute named "Price" with a value of "Regular" and Save
4. Create a Variation using the above created Attribute. I used the "create variations from all attributes" option. Once created, click into it and set the regular price of the variation to $1.00
5. Take note of the product ID and the newly created variation ID
6. In a clean browser session, navigate to http://[mysite]/?add-to-cart=XXX&variation_id=YYY&attribute_price=Regular, where XXX is the product ID and YYY is the variation ID. This scenario should add the item to the cart successfully.
7. In a clean browser session, navigate to http://[mysite]/?add-to-cart=YYY, where YYY is the variation ID. This used to work with WooCommerce 3.1.2 but no longer works.

## Expected/actual behavior

Actual behavior: When I follow those steps, I see the home page of the site load with nothing on the cart. If I click on the Cart icon, it says "Price is a required field".

Example URL Failing: https://bodymadewell.com/?add-to-cart=1893

Expected behavior: I was expecting to see the cart with the variation added, without having to provide the product ID nor the attribute title.

Example URL Working: https://bodymadewell.com/?add-to-cart=1885&variation_id=1893&attribute_price=Regular

## Workaround 1

To prevent lost sales in the interim, I am using the Redirection plugin with RegEx rules to replace all known active variation IDs with the expanded arguments. For example:

Source URL: `^(.*)?add-to-cart=127714(.*)$`

Target URL: `https://spicefit.com/?add-to-cart=458&variation_id=127714&attribute_price=Mega+Sale$2`

## Workaround 2

The variation ID can still be used in an `add-to-cart=` argument if you provide the `attribute_price=` argument.

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active [T17]
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
`
### WordPress Environment ###

Home URL: https://bodymadewell.com
Site URL: https://bodymadewell.com
WC Version: 3.2.3
Log Directory Writable: ✔
WP Version: 4.8.3
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: nginx/1.10.3
PHP Version: 7.0.22-0ubuntu0.16.04.1
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.2.3
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Total Database Size: 23.83MB
Database Data Size: 21.62MB
Database Index Size: 2.21MB
wp_woocommerce_sessions: Data: 0.05MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_order_itemmeta: Data: 0.06MB + Index: 0.03MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_chained_choices: Data: 0.02MB + Index: 0.00MB
wp_chained_completed: Data: 0.02MB + Index: 0.00MB
wp_chained_questions: Data: 0.02MB + Index: 0.00MB
wp_chained_quizzes: Data: 0.02MB + Index: 0.00MB
wp_chained_results: Data: 0.02MB + Index: 0.00MB
wp_chained_user_answers: Data: 0.02MB + Index: 0.00MB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_comments: Data: 0.02MB + Index: 0.09MB
wp_et_divi_ab_testing_clients: Data: 0.02MB + Index: 0.00MB
wp_et_divi_ab_testing_stats: Data: 0.02MB + Index: 0.00MB
wp_gb_ocu_customers: Data: 0.02MB + Index: 0.03MB
wp_gb_ocu_funnels: Data: 0.02MB + Index: 0.02MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_ocu_stats: Data: 0.02MB + Index: 0.05MB
wp_options: Data: 0.27MB + Index: 0.05MB
wp_postmeta: Data: 0.41MB + Index: 0.38MB
wp_posts: Data: 18.48MB + Index: 0.27MB
wp_termmeta: Data: 0.02MB + Index: 0.03MB
wp_terms: Data: 0.02MB + Index: 0.03MB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wp_usermeta: Data: 1.50MB + Index: 0.61MB
wp_users: Data: 0.09MB + Index: 0.08MB
wp_woocommerce_bundled_itemmeta: Data: 0.06MB + Index: 0.06MB
wp_woocommerce_bundled_items: Data: 0.02MB + Index: 0.03MB
wp_yoast_seo_links: Data: 0.06MB + Index: 0.02MB
wp_yoast_seo_meta: Data: 0.02MB + Index: 0.00MB

### Post Type Counts ###

attachment: 125
custom_css: 2
et_pb_layout: 45
nav_menu_item: 1
page: 28
popup: 2
popup_theme: 6
post: 16
product: 34
product_variation: 6
revision: 1002
shop_coupon: 1
shop_order: 19
shop_order_refund: 11

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (35) ###

Chained Quiz: by Kiboko Labs – 1.0.5.1
Debug Bar: by wordpressdotorg – 0.9
Divi - Awesome Woo Products: by Bruno Bouyajdad | Indikator Design – 1.0.9.6 – Not tested with the active version of WooCommerce
Easy FancyBox: by RavanH – 1.6
Enhanced E-commerce for Woocommerce store: by Tatvic – 1.2.0.1 – Not tested with the active version of WooCommerce
Enhanced Text Widget: by Boston Dell-Vandenberg – 1.4.6
Import users from CSV with meta: by codection – 1.10.7.5
Maropost Plugin: by Codesushi – 1.0.0
NMI 3 step: by Codesushi – 3.1.0
OPcache Dashboard: by Daisuke Takahashi(Extend Wings) – 0.3.1
Popup Maker: by WP Popup Maker – 1.6.6
Redis Object Cache: by Till Krüss – 1.3.5
SendGrid: by SendGrid – 1.11.7
UpdraftPlus - Backup/Restore: by UpdraftPlus.Com
DavidAnderson – 2.13.13.22

User Role Editor Pro: by Vladimir Garagulia – 4.38
W3 Total Cache: by Frederick Townes – 0.9.5.4
WooCommerce 3PL Order Sync: by Webdibs – 2.7.2 – Not tested with the active version of WooCommerce
WooCommerce Ad Tracking: by Sean.Conklin – 1.0 – Not tested with the active version of WooCommerce
Woocommerce Custom Checkout Handler: by Codesushi – 1.0.0 – Not tested with the active version of WooCommerce
WooCommerce Custom Checkout: by Sean.Conklin – 1.0.1 – Not tested with the active version of WooCommerce
WooCommerce Custom Product Page: by Sean.Conklin – 1.0 – Not tested with the active version of WooCommerce
WooCommerce Custom Receipt: by Sean.Conklin – 1.0 – Not tested with the active version of WooCommerce
WooCommerce Amazon Pay Gateway: by WooCommerce – 2.1.7.1 – Not tested with the active version of WooCommerce
WooCommerce CyberSource SA SOP Gateway: by SkyVerge – 2.7.1 – Not tested with the active version of WooCommerce
WooCommerce PayPal Express Checkout Gateway: by WooCommerce – 1.4.4
Advanced Order Export For WooCommerce (Pro): by AlgolPlus – 1.5.0
WooCommerce Product Bundles: by SomewhereWarm – 5.5.3
1 click upsell stats plugin: by Codesushi – 2.0.0
WooCommerce 1 Click Upsells & Downsells: by WooCurve – 2.0.0 – Not tested with the active version of WooCommerce
1 click payment plugin: by Codesushi – 1.0.0
WooCommerce: by Automattic – 3.2.3
WP Crontrol: by John Blackbourn & contributors – 1.5
WP Migrate DB Pro Media Files: by Delicious Brains – 1.4.8
WP Migrate DB Pro: by Delicious Brains – 1.8
WP-Optimize: by David Anderson
Ruhani Rabin
Team Updraft – 2.1.1

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: bundle (bundle)
external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: ❌ Page not set
Cart: #148 - /
Checkout: #149 - /checkout/
My account: ❌ Page visibility should be public
Terms and conditions: ❌ Page not set

### Theme ###

Name: BodyMadeWell (Divi Child)
Version: 1.0
Author URL: http://bodymadewell.com
Child Theme: ✔
Parent Theme Name: Divi
Parent Theme Version: 3.0.86
Parent Theme Author URL: http://www.elegantthemes.com
WooCommerce Support: ✔

### Templates ###

Overrides: –

### CyberSource SA SOP ###

Environment: Live
Debug Mode: Off
`
</details>

### PR DESCRIPTION
**Pull request by mikejolley**
When a variation is added to cart by ID, some validation code is ran to ensure posted attributes are correct.

If these values are missing, instead of erroring in all cases, we only need to error if the attribute is UNKNOWN. i.e. the variation has ‘any’ selected.

Fixes #17601

### CODE REVIEW

File: includes/class-wc-form-handler.php [hunk 1]
```diff
@@ -834,8 +834,8 @@ private static function add_to_cart_handler_grouped( $product_id ) {
 	 */
 	private static function add_to_cart_handler_variable( $product_id ) {
 		try {
-			$variation_id       = empty( $_REQUEST['variation_id'] ) ? '' : absint( $_REQUEST['variation_id'] );
-			$quantity           = empty( $_REQUEST['quantity'] ) ? 1 : wc_stock_amount( $_REQUEST['quantity'] );
+			$variation_id       = empty( $_REQUEST['variation_id'] ) ? '' : absint( wp_unslash( $_REQUEST['variation_id'] ) );
```
Comment (claudiosanches) [inline includes/class-wc-form-handler.php]: No need to include `wp_unslash()` when using `absint()`.
