### PR TITLE
[HPOS] Improve handling of "visible" statuses in orders list

### LINKED ISSUE #35362: [HPOS] Orders list is empty when all orders are in trash
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When there are no orders except trashed ones, WC > Orders is totally empty (the "default state" shows). This also prevents you from accessing the trashed orders.

### Expected behavior

At least the nav menu with the order statuses should appear.

### Actual behavior

Nothing appears (see screenshot).

Screenshot 2022-10-27 at 11 42 49

### Steps to reproduce

1. Enable HPOS/COT.
2. Go to WC > Orders.
3. If you don't have any orders, create one.
4. Trash all orders.
5. Confirm that WC > Orders is empty and you don't have a way to get to the trashed orders.

### WordPress Environment

N/A

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by jorgeatorres**
### All Submissions:

-   [X] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
-   [X] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
-   [X] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change?

### Changes proposed in this Pull Request:

This PR improves how we handle visible statuses in the orders list table. As a consequence, #35362 is addressed (which has to do with rendering of blank state), but the PR also fixes some wrong counts (such as "All" including trashed orders).

Closes #35362.

- [ ] This PR is a very minor change/addition and does not require testing instructions (if checked you can ignore/remove the next section).

### How to test the changes in this Pull Request:

1. Check out `trunk`.
1. Follow test instructions on #35362 to confirm the issue.
2. Notice that the "All" count in the filters includes trashed orders too, which is not standard.
3. Check out this branch.
4. Confirm that blank state now works correctly: filters and table appear even if all orders are trashed but blank state returns when there are _no_ orders at all.
5. Confirm that "All" doesn't include trashed orders (or other non-visible statuses).

### Other information:

-   [X] Have you added an explanation of what your changes do and why you'd like us to include them?
-   [X] Have you written new tests for your changes, as applicable?
-   [X] Have you created a changelog file for each project being changed, ie `pnpm --filter=<project> changelog add`?

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

File: plugins/woocommerce/src/Internal/Admin/Orders/ListTable.php [hunk 1]
```diff
@@ -408,22 +406,51 @@ public function get_views() {
...
 	 * Count orders by status.
 	 *
-	 * @param string $status The order status we are interested in.
+	 * @param string|string[] $status The order status we are interested in.
 	 *
 	 * @return int
 	 */
-	private function count_orders_by_status( string $status ): int {
+	private function count_orders_by_status( $status ): int {
 		$orders = wc_get_orders(
```
Comment (vedanshujain) [inline plugins/woocommerce/src/Internal/Admin/Orders/ListTable.php]: We should probably replace this with direct count query, it definitely won't work on large sites.

**Review by vedanshujain — DISMISSED** [review]
Requesting a performance-related change (and maybe some unit tests). Otherwise lgtm!

File: plugins/woocommerce/src/Internal/Admin/Orders/ListTable.php (hunk 1 above)
Comment (jorgeatorres) [reply plugins/woocommerce/src/Internal/Admin/Orders/ListTable.php]: You're right. I've changed this to use `wc_orders_count()` instead, which uses the underlying datastore for counting and is also cached. I have no problem with writing a count query but thought it'd be best to use our own APIs if those worked here.

The only drawback I see is that it doesn't count multiple statuses at once, but that shouldn't be too bad (as there aren't that many statuses). Also, we need the individual count later so caching covers that.

If you still think I should go with a direct query, I'd be more than happy to do that.

File: plugins/woocommerce/src/Internal/Admin/Orders/ListTable.php [hunk 2]
```diff
@@ -408,20 +406,40 @@ public function get_views() {
...
-	private function count_orders_by_status( string $status ): int {
-		$orders = wc_get_orders(
-			array(
-				'limit'  => -1,
-				'return' => 'ids',
-				'status' => $status,
-			)
-		);
+	private function count_orders_by_status( $status ): int {
+		return array_sum( array_map( 'wc_orders_count', (array) $status ) );
```
Comment (vedanshujain) [inline plugins/woocommerce/src/Internal/Admin/Orders/ListTable.php]: seems like this counts all order types (including refunds, subscriptions etc), although I really like that it does cache out of the box. This implementation is consistent with earlier implementation (where we also were not considering other order type), but the post-type implementation does consider only `shop_order`. (This also makes sense since we will only display only `shop_order` type, so count should be also on only that type). This means we may wanna do the custom query, (or wc_query is also fine, just with specifying types and a limit of 1). WDYT?

**Review by vedanshujain — COMMENTED** [review]
Looks good, but left another comment for a possible bug (which was also there in previous implementation, but we may wanna fix it here).

File: plugins/woocommerce/src/Internal/Admin/Orders/ListTable.php (hunk 2 above)
Comment (jorgeatorres) [reply plugins/woocommerce/src/Internal/Admin/Orders/ListTable.php]: Thanks for the feedback V!

This function doesn't count refunds nor subscriptions because those order types are registered with [`exclude_from_order_count`](https://github.com/woocommerce/woocommerce/blob/5b1296fe45927cc03b2d286a64e5532afc6640e0/plugins/woocommerce/includes/wc-order-functions.php#L198-L204), which this function [takes into account](https://github.com/woocommerce/woocommerce/blob/5b1296fe45927cc03b2d286a64e5532afc6640e0/plugins/woocommerce/includes/wc-order-functions.php#L359
).

That said, it _could_ end up including other order types if those are not registered with that flag. I'll see if I can adjust `wc_orders_count()` so that we can specify the type, because I thought it'd be best to use an API function instead of relying on a direct query.

That said, if that becomes too cumbersome, I'll default to a direct query or a `WC_Order_Query` as you've suggested.

Comment (jorgeatorres) [reply plugins/woocommerce/src/Internal/Admin/Orders/ListTable.php]: Hey @vedanshujain!

I've tried to implement what I described above. In f8a5fbc0d61ef3e599f4a7a429aaf2a0f7072880, I've added a `$type` argument to `wc_orders_count()` which allows specifying the order type. The arg is optional, and defaults to the same order types as before, so no breakage of backwards compat.

I've also expanded the unit tests related to `wc_orders_count()` (in 3f63a599329dc3c8d8c937e25705eef167b0ec8c) to confirm the new functionality works correctly.

With these changes in place, which might be useful on its own, we can limit the HPOS list table to only `shop_order` types while still using our APIs. In the end, this is mostly the same as a direct query but has some benefits (datastore handles the query and a more flexible `wc_orders_count()`).

Please let me know what you think 😸.

**Comment by Konamiman** [comment]
Looks good but about this (emphasis mine):

> Confirm that "All" doesn't include trashed orders _**(or other non-visible statuses)**_

While this makes sense as it makes the count for "All" to match the sums of all the other view counts displayed, this deviates from the count that is displayed when the posts table is in use. In that case the "All" count includes also non-visible statuses, for example "Pending payment" which is registered by the Bookings plugins as a new post status (but not as a new order status).

So what do we prefer to do? The "correct" thing (not including the hidden statuses in the "All" count) or the "backwards compatible" way (including them)?

**Review by Konamiman — APPROVED** [review]

**Comment by Konamiman** [comment]
Regarding [the previous comment](https://github.com/woocommerce/woocommerce/pull/35370#issuecomment-1315138011), after discussing within Proton we decided to go with the "correct" approach, that is, the count for "All" will be the sum of the counts for the other views, instead of the total count of irders in the database.
