### PR TITLE
Tidy and update product attribute TypeScript types

### LINKED ISSUE #46908: Product Block Editor: organize product attribute TS types
There are a few inconsistencies in the types defined in the data CRUD implementation.

For instance, the object passed to the action to create a new item accepts an `id,` which is incorrect. The `id` is generated and provided by the server side, [here](https://github.com/woocommerce/woocommerce/blob/130866fdaa3a2423b0633cd44048b7c06de2b189/plugins/woocommerce/includes/rest-api/Controllers/Version3/class-wc-rest-product-attributes-controller.php#L71).

### PR DESCRIPTION
**Pull request by retrofox**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

This PR tidies and updates the Product Attribute TS types defined in the data CRUD implementation and updates another part of the code where it's required.

 ### Relevante changes

* **Rename `ProductAttribute` type with `ProductProductAttribute`**
It may not sound confusing, but it makes the difference between the `ProductAttribute` and `ProductProductAttribute` types more evident.
`ProductProductAttribute` is the object that belongs to the `Product` one. For instance, its what the `wc/v3/products/<product-id>` responses:

image
`position`, `options`, etc, are properties that make sense when the attribute belongs to a product instance.

* Introduce `ProductAttribute` type
It defines the types for the product attribute, decoupled of the product attribute object. For instance, what the `wc/v3/products/<product-id>/attributes` responses:

image

* Update the `QueryProductAttribute` type
It removes the `id` property from there. When creating a new attribute, the server-side doesn't take it from the request but it generates it

Closes # .

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

Building the Product Block editor will check the TS definitions. It should be enough.

Additionally, you could use your IDE to easily check what the types of the Attribute selector and actions:

For instance, open the `packages/js/product-editor/src/components/attribute-input-field/attribute-input-field.tsx` file.
If you take a look at the type of the selector:

Screenshot 2024-04-25 at 11 32 51

The type is `ProductAttribute`.

Or when creating a new attribute:

Screenshot 2024-04-25 at 11 35 47

The type `QueryProductAttribute`, which doesn't include the `id`, for instance.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Comment 

</details>

### CODE REVIEW

File: packages/js/data/src/products/types.ts [hunk 1]
```diff
@@ -28,7 +28,7 @@ export type ProductDownload = {
 	file: string;
 };
 
-export type ProductAttribute = {
+export type ProductProductAttribute = {
```
Comment (louwie17) [inline packages/js/data/src/products/types.ts:31]: Haha I guess this will do :) Not the most spectacular name, but does make sense.

**Review by louwie17 — APPROVED** [review]
LGTM 🚀 Thanks for cleaning this up 👍

File: packages/js/data/src/products/types.ts (hunk 1 above)
Comment (retrofox) [reply packages/js/data/src/products/types.ts:31]: Agree :developers:! I'm afraid it would get funnier when renaming `ProductDownload`, etc :-D
