### PR TITLE
[Migrator]: Fix the tax migration and add XSS filtering

### LINKED ISSUE #61270: [Migrator]: Taxable attributes are not being migrated properly
From internal testing feedback

### PR DESCRIPTION
**Pull request by naman03malhotra**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes #61270 #61397 #61396

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

**Taxable product**
1.  Visit pdqkbG-5P2-p2 CFT post for setup instructions
2. Once you have access to the Shopify store, mark the Oil product as taxable.
3. Run the migration with
4. `wp wc migrate products --product-type="Oil"`
5. Feel free to create a new product as well.
6. Notice that while migrating to Woo 
7. the product is marked as taxable.
8. Now delete the migrated product 
9. Uncheck the product as taxable on Shopify
10. Run the migration again
11. Observe that the product is not taxable.

**XSS filtering**
1. Goto pdqkbG-5P2-p2 CFT post for setup instructions
2. Once you have access to the Shopify store, change the Oil product's title to something like "Great Keratin serum <script>alert("Test")</script>"
3. `wp wc migrate products --product-type="Oil"`
4. Feel free to create a new product as well.
5. Notice that while migrating to Woo 
6. The text with the script tag is not migrated

Also, notice that the progress indicator starts from not zero, improving the perceived experience for the user to show progress.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce/src/Internal/CLI/Migrator/Platforms/Shopify/ShopifyMapper.php [hunk 1]
```diff
@@ -357,10 +384,10 @@ private function map_basic_product_fields( object $shopify_product, bool $is_var
 		$basic_data['original_product_id'] = ! empty( $shopify_product->id ) ? basename( $shopify_product->id ) : null;
 
 		// Basic Product Fields.
-		$basic_data['name']              = $shopify_product->title;
+		$basic_data['name']              = sanitize_text_field( $shopify_product->title );
 		$basic_data['slug']              = $shopify_product->handle;
 		$basic_data['description']       = $this->sanitize_product_description( $shopify_product->descriptionHtml ?? '' ); // phpcs:ignore WordPress.NamingConventions.ValidVariableName.UsedPropertyNotSnakeCase -- GraphQL uses camelCase.
```
Comment (PanosSynetos) [inline plugins/woocommerce/src/Internal/CLI/Migrator/Platforms/Shopify/ShopifyMapper.php]: Why not use `wp_kses_post` instead of custom sanitization?

File: plugins/woocommerce/src/Internal/CLI/Migrator/Platforms/Shopify/ShopifyMapper.php [hunk 2]
```diff
@@ -357,10 +384,10 @@ private function map_basic_product_fields( object $shopify_product, bool $is_var
...
-		$basic_data['short_description'] = $shopify_product->descriptionPlainSummary ?? ''; // phpcs:ignore WordPress.NamingConventions.ValidVariableName.UsedPropertyNotSnakeCase -- GraphQL uses camelCase.
+		$basic_data['short_description'] = sanitize_textarea_field( $shopify_product->descriptionPlainSummary ?? '' ); // phpcs:ignore WordPress.NamingConventions.ValidVariableName.UsedPropertyNotSnakeCase -- GraphQL uses camelCase.
```
Comment (PanosSynetos) [inline plugins/woocommerce/src/Internal/CLI/Migrator/Platforms/Shopify/ShopifyMapper.php]: Short description supports HTML. Why do we limit it and not use `wp_kses_post` ?

**Review by PanosSynetos — DISMISSED** [review]
Hey @naman03malhotra - Thanks for this. Could you please check my comments when you get a chance?

Thank you

File: plugins/woocommerce/src/Internal/CLI/Migrator/Platforms/Shopify/ShopifyMapper.php [hunk 3]
```diff
@@ -487,8 +518,8 @@ private function map_variable_product_data( object $shopify_product, bool $is_va
 		if ( $is_variable && property_exists( $shopify_product, 'options' ) && ! empty( $shopify_product->options ) ) {
 			foreach ( $shopify_product->options as $option ) {
 				$variable_data['attributes'][] = array(
-					'name'         => $option->name,
-					'options'      => $option->values,
+					'name'         => sanitize_text_field( $option->name ),
+					'options'      => array_map( 'sanitize_text_field', $option->values ),
```
Comment (xristos3490) [inline plugins/woocommerce/src/Internal/CLI/Migrator/Platforms/Shopify/ShopifyMapper.php]: Nit. The `wc_clean()` function has the same logic :) We could replace it here for consistency.

**Review by xristos3490 — DISMISSED** [review]
Looking good to me overall! Left a minor comment but I do agree with @PanosSynetos that titles and descriptions should go through the `wp_kses_post()` instead of a custom set of tags.

File: plugins/woocommerce/src/Internal/CLI/Migrator/Platforms/Shopify/ShopifyMapper.php (hunk 3 above)
Comment (naman03malhotra) [reply plugins/woocommerce/src/Internal/CLI/Migrator/Platforms/Shopify/ShopifyMapper.php]: Makes sense, fixed as part of https://github.com/woocommerce/woocommerce/pull/61453/commits/ada58664ecb3e70d5987f570ee6e8e1fd4ddbed8

File: plugins/woocommerce/src/Internal/CLI/Migrator/Platforms/Shopify/ShopifyMapper.php (hunk 1 above)
Comment (naman03malhotra) [reply plugins/woocommerce/src/Internal/CLI/Migrator/Platforms/Shopify/ShopifyMapper.php]: good point, fixed as part of https://github.com/woocommerce/woocommerce/pull/61453/commits/51b3de02a6bde34b2c3b663f76cf37c468686f54

File: plugins/woocommerce/src/Internal/CLI/Migrator/Platforms/Shopify/ShopifyMapper.php (hunk 2 above)
Comment (naman03malhotra) [reply plugins/woocommerce/src/Internal/CLI/Migrator/Platforms/Shopify/ShopifyMapper.php]: added in recent commits

**Comment by PanosSynetos** [comment]
Given the handoff to a new team, I would tag @joshuatf to wrap this PR up. cc @jamesckemp

**Comment by joshuatf** [comment]
@ObliviousHarmony is going to take over this project, so I'm re-assigning this review to him.  @ObliviousHarmony if you have to make any additional changes here, feel free to tag someone else on Flux for review.

File: plugins/woocommerce/src/Internal/CLI/Migrator/Lib/ImportSession.php [hunk 4]
```diff
@@ -671,4 +671,23 @@ public function set_reentrancy_cursor( $cursor ) {
...
\ No newline at end of file
+
+	/**
+	 * Save the original command arguments for session resumption.
+	 *
+	 * @param array $args The original command arguments
+	 */
+	public function set_original_arguments( array $args ) {
+		update_post_meta( $this->post_id, 'original_arguments', $args );
+	}
```
[the remark this answers is not in the document]
Comment (ObliviousHarmony) [reply plugins/woocommerce/src/Internal/CLI/Migrator/Lib/ImportSession.php:682]: There's no way for malicious data to end up here in our use-case. Filtering to the list of options that we already know are the only options is unnecessary and would be error-prone if the arguments were extended in the future.

**Review by ObliviousHarmony — APPROVED** [review]
The tax status is migrated correctly and I can't find any other XSS issues. Looks good!

File: plugins/woocommerce/src/Internal/CLI/Migrator/Platforms/Shopify/ShopifyMapper.php [hunk 5]
```diff
@@ -424,7 +415,7 @@ private function map_simple_product_data( object $shopify_product ): array {
 			}
 
 			if ( $this->should_process( 'sku' ) ) {
-				$simple_data['sku'] = $variant_node->sku;
+				$simple_data['sku'] = wc_clean( $variant_node->sku );
```
[the remark this answers is not in the document]
Comment (ObliviousHarmony) [reply plugins/woocommerce/src/Internal/CLI/Migrator/Platforms/Shopify/ShopifyMapper.php:418]: As far as I can tell, `wc_clean()` will normalize the input and the null coalescing isn't necessary.

**Comment by PanosSynetos** [comment]
Sorry @ObliviousHarmony for re-requesting a review - I wanted to change the assignee

**Review by prettyboymp — APPROVED** [review]
**DISCLAIMER** I did not go through a testing process for this.

Code looks good.  

I did verify that the fact that the `import_session` post type isn't registered wouldn't accidentally expose it in some way.  I didn't see any current risk there and I wouldn't expect that behavior to change for WP core in the future.  So it shouldn't be an issue.
