### PR TITLE
Fix fulfillment object rendering

### LINKED ISSUE #58970: [Order fulfillments] Post-MVP: Clean up script loading
As per comment in [https://github.com/woocommerce/woocommerce/pull/58731/files#r2155380365](https://github.com/woocommerce/woocommerce/pull/58731/files#r2155380365), we need to clean up the script loading of fulfillments drawer and the fulfillments specific settings rendering.

### PR DESCRIPTION
**Pull request by tpaksu**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

This replaces the fulfillment settings object rendering with `wp_localize_script` from directly rendering the script tags and JSON encoded PHP object, also fixes some comments and renames a method. 

Closes WOOPLUG-4693.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

Tests should pass, and the order screen should have the `wcFulfillmentsSettings` object filled with providers, statuses and currency symbols settings. 

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 
Replace script output of wcFulfillmentsSettings with wp_localize_script
</details>

### CODE REVIEW

File: plugins/woocommerce/src/Internal/Fulfillments/FulfillmentsRenderer.php [hunk 1]
```diff
@@ -391,19 +383,24 @@ public function print_fulfillments_object() {
...
-			window.wcFulfillmentSettings = <?php echo wp_json_encode( $fulfillment_settings ); ?>;
-		</script>
-		<?php
+		wp_localize_script( 'wc-admin-fulfillments', 'wcFulfillmentSettings', $fulfillment_settings );
 	}
 
 	/**
 	 * Check if the fulfillment drawer should be rendered.
+	 * Check if the fulfillment drawer should be rendered (admin only).
 	 *
```
Comment (ismaeldcom) [inline plugins/woocommerce/src/Internal/Fulfillments/FulfillmentsRenderer.php:392]: _Nitpick:_ Duplicated comment.

**Review by ismaeldcom — APPROVED** [review]
Code change look good and works as expected. The global variable is correctly populated, and the drawer keeps working. I only left a tiny nitpick, but apart from that, it's ready to go!

image

File: plugins/woocommerce/src/Internal/Fulfillments/FulfillmentsRenderer.php (hunk 1 above)
Comment (tpaksu) [reply plugins/woocommerce/src/Internal/Fulfillments/FulfillmentsRenderer.php:392]: Yep it'll be deleted on the linked PR :) 

https://github.com/woocommerce/woocommerce/pull/58859/files#diff-80468fb54a04166b572da8fe1748309d786a4ee4f69d053966ce3b395c5661b9L388-L393
