### PR TITLE
fix: add check for wp_get_current_user() before calling it

### LINKED ISSUE #51301: [Fatal] Call to undefined function `wp_get_current_user()` | `RemoteLogger.php`
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

We observed the following fatal error in relation to WooCommerce 9.3.0 (which may have its origins in [this PR](https://github.com/woocommerce/woocommerce/pull/49599), which introduced the use of the WP function in question):

```
PHP Fatal error: Uncaught Error: Call to undefined function Automattic\WooCommerce\Internal\Logging\wp_get_current_user() 
in /.../woocommerce/src/Internal/Logging/RemoteLogger.php:93
```

<details>
<summary> Stack trace </summary>

```
#0 /.../woocommerce/src/Internal/Logging/RemoteLogger.php(203):
Automattic\WooCommerce\Internal\Logging\RemoteLogger->get_formatted_log('critical', 'Cannot redeclar...', Array)

#1 /.../woocommerce/src/Internal/Logging/RemoteLogger.php(46):
Automattic\WooCommerce\Internal\Logging\RemoteLogger->log('critical', 'Cannot redeclar...', Array)

#2 /.../woocommerce/includes/class-wc-logger.php(189):
Automattic\WooCommerce\Internal\Logging\RemoteLogger->handle(1726086801, 'critical', 'Cannot redeclar...', Array)

#3 /.../woocommerce/includes/class-wc-logger.php(236):
WC_Logger->log('critical', 'Cannot redeclar...', Array)

#4 /.../woocommerce/includes/class-woocommerce.php(406):
WC_Logger->critical('Cannot redeclar...', Array)

#5 [internal function]: WooCommerce->log_errors()

#6 {main}
thrown in /wordpress/plugins/woocommerce/9.3.0/src/Internal/Logging/RemoteLogger.php on line 93
```

</details>

[Relevant code](https://github.com/woocommerce/woocommerce/blob/7d34ae5c5b0bb4c45b8fc5731997261c02f2b14b/plugins/woocommerce/src/Internal/Logging/RemoteLogger.php#L160)

It seems like there are conditions in which an error occurs, *after* WooCommerce and the RemoteLogger are available, but *before* the pluggable WP function `wp_get_current_user()` is available. In some cases, if the error is severe enough, PHP enters shutdown (which of course can happen at pretty much any point), and we try to report the error via the `RemoteLogger`, but things break down because functions like the one referenced in the error have not actually been defined.

### Expected behavior

The RemoteLogger should log any captured errors, without a fatal error.

### Actual behavior

As described, it seems like in some cases the RemoteLogger itself fails with a fatal error.

### Steps to reproduce

We observed this by monitoring error logs, so have not yet ascertained concrete steps to replicate, but it seems a good starting point would be to trigger a suitable error after WooCommerce is loaded but *before* the last `plugin_loaded` (for the avoidance of any doubt that's `plugin_loaded`, singular) action is fired.

### WordPress Environment

—

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by rjchow**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes https://github.com/woocommerce/woocommerce/issues/51301

The direct cause of the bug above has been addressed by adding a check for the function's existence before calling it, and secondarily, the try-catch around it has been enhanced to catch PHP errors so that it does not obscure the original error.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. I'm not sure how to reproduce the situation where `wp_get_current_user()` is undefined, but an inspection of the code should be satisfactory. 
2. Test that it still works correctly by using WC Beta Tester to simulate an error. See PCYsg-11XN-p2 for instructions on viewing the logs
3. Using `./wp-admin/plugin-editor.php`, Modify [./src/Internal/Logging/RemoteLogger.php](https://github.com/woocommerce/woocommerce/blob/393b18b760714c8d150cbf0c792054e21efcf7f5/plugins/woocommerce/src/Internal/Logging/RemoteLogger.php#L92) on L92 so that `wp_get_current_user()` becomes an non-existent function - e.g `aaaaaaaaa()`
4. Reset the rate limiting and trigger the error again
5. Should see two lines of logs in debug.log (use a plugin like "Debug log manager" or ssh into the site to see view it)

```
[12-Sep-2024 07:22:17 UTC] PHP Fatal error:  Uncaught Exception: Simulated WooCommerce error for remote logging test in /srv/htdocs/wp-content/plugins/woocommerce-beta-tester/woocommerce-beta-tester.php:148
Stack trace:
#0 /srv/htdocs/__wp__/wp-includes/class-wp-hook.php(324): simulate_woocommerce_error('')
#1 /srv/htdocs/__wp__/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)
#2 /srv/htdocs/__wp__/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#3 /srv/htdocs/wp-content/plugins/wc_beta_tester_live_branch_9.4.0-dev-10824980923-gfa486af/includes/class-woocommerce.php(259): do_action('woocommerce_loa...')
#4 /srv/htdocs/__wp__/wp-includes/class-wp-hook.php(324): WooCommerce->on_plugins_loaded('')
#5 /srv/htdocs/__wp__/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)
#6 /srv/htdocs/__wp__/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#7 /srv/htdocs/__wp__/wp-settings.php(555): do_action('plugins_loaded')
#8 /srv/htdocs/wp-config.php(85): require_once('/srv/htdocs/__w...')
#9 /srv/htdocs/__wp__/wp-load.php(55): require_once('/srv/htdocs/wp-...')
#10 /srv/htdocs/__wp__/wp-admin/admin.php(34): require_once('/srv/htdocs/__w...')
#11 {main}
  thrown in /srv/htdocs/wp-content/plugins/woocommerce-beta-tester/woocommerce-beta-tester.php on line 148
[12-Sep-2024 07:22:17 UTC] Remote logging failed: Call to undefined function Automattic\WooCommerce\Internal\Logging\wp_get_current_userz()
```
The first line is the original error log, and the second line would be the error that was caught within the Remote Logging feature

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce/src/Internal/Logging/RemoteLogger.php [hunk 1]
```diff
@@ -88,7 +88,7 @@ public function get_formatted_log( $level, $message, $context = array() ) {
 			unset( $context['tags'] );
 		}
 
-		if ( class_exists( '\WC_Tracks' ) ) {
+		if ( class_exists( '\WC_Tracks' ) && function_exists( 'wp_get_current_user' ) ) {
```
Comment (adrianduffell) [inline plugins/woocommerce/src/Internal/Logging/RemoteLogger.php:91]: We might be better to wrap the whole thing in try/catch 🤔  I suppose there could be all sorts of possible errors associated with calling other functions when the site is in a fatal error state. Rather than just protecting against this function not existing, we could try catch a larger surface.

File: plugins/woocommerce/src/Internal/Logging/RemoteLogger.php [hunk 2]
```diff
@@ -88,7 +88,7 @@ public function get_formatted_log( $level, $message, $context = array() ) {
...
 			$user         = wp_get_current_user();
 			$blog_details = \WC_Tracks::get_blog_details( $user->ID );
```
Comment (adrianduffell) [inline plugins/woocommerce/src/Internal/Logging/RemoteLogger.php:93]: Interestingly, `WC_Tracks::get_blog details` uses the user ID to get the site's language -- which I think is technically incorrect considering the name of the function. It would be more accurate to get the site language setting with something like `get_bloginfo('language')` rather than that of the current user.

Potentially we change the WC_Tracks class to use the site language and won't need to query user info here 🤔

File: plugins/woocommerce/src/Internal/Logging/RemoteLogger.php (hunk 1 above)
Comment (rjchow) [reply plugins/woocommerce/src/Internal/Logging/RemoteLogger.php:91]: There's a try/catch just one level above though, https://github.com/woocommerce/woocommerce/blob/573d1bebed2543f2f34e37dcb7abf01ebcf32522/plugins/woocommerce/src/Internal/Logging/RemoteLogger.php#L201

I think we need to change something about that try-catch as mentioned in a separate chat

Comment (adrianduffell) [reply plugins/woocommerce/src/Internal/Logging/RemoteLogger.php:91]: Right, sorry I forgot try-catch will still let fatal errors slip through.

Riffing on your original idea, I could see it being beneficial to create some guard rails around every non-inbuilt function -- ` wp_parse_url`, `WC`, `wp_get_current_user` etc -- by making private method wrappers/aliases. Something like:

```
private function wp_parse_url() {
 if ( function_exists( 'wp_parse_url' ) ) {
   wp_parse_url();
 }
 else {
   return null; // or alternatively throw an exception 🤔 
 }
}
```

File: plugins/woocommerce/src/Internal/Logging/RemoteLogger.php (hunk 2 above)
Comment (adrianduffell) [reply plugins/woocommerce/src/Internal/Logging/RemoteLogger.php:93]: We could also reduce our dependency on `WC_Tracks` entirely and determine `blog_id` and `store_id` values independently.

```
$blog_id  = class_exists( 'Jetpack_Options' ) ? Jetpack_Options::get_option( 'id' ) : null
$store_id' = get_option( \WC_Install::STORE_ID_OPTION, null );
```

The dependency on [Jetpack_Options](https://github.com/Automattic/jetpack-options) could perhaps also be removed and just make a straight call to WP `get_option` 🤔

Comment (rjchow) [reply plugins/woocommerce/src/Internal/Logging/RemoteLogger.php:93]: I'll make a separate issue for that since the scope of those changes have a bigger blast radius than the ones I've made

Comment (rjchow) [reply plugins/woocommerce/src/Internal/Logging/RemoteLogger.php:93]: Issue created: https://github.com/woocommerce/woocommerce/issues/51310

**Review by adrianduffell — CHANGES_REQUESTED** [review]
Thanks for jumping on this, @rjchow!! It looks good at fixing the specific issue found with `wp_get_current_user`, but I worry there are other dependent functions in use that can have similar problems.

I've created an issue https://github.com/woocommerce/woocommerce/issues/51317 to improve our error simulations. I think it could be best to work on that issue first to help reveal the entire scope of the problem, but also open to merging this PR first and addressing the larger scope in a follow-up.

File: plugins/woocommerce/src/Internal/Logging/RemoteLogger.php (hunk 1 above)
Comment (chihsuan) [reply plugins/woocommerce/src/Internal/Logging/RemoteLogger.php:91]: Thanks, this is tested well! 

What do you think if we require `pluggable.php` explicitly when `wp_get_current_user` is not defined? 🤔  We can require it early in the method so we can ensure all wp pluggable functions are available to avoid any related issues.

```php
if ( ! function_exists( 'wp_get_current_user' ) ) {
  require_once ABSPATH . WPINC . '/pluggable.php';
}
```

Comment (chihsuan) [reply plugins/woocommerce/src/Internal/Logging/RemoteLogger.php:91]: > What do you think if we require pluggable.php explicitly when wp_get_current_user is not defined? 

After thinking about it a bit, I think this might not be necessary if we will likely change `WC_Tracks` to use the site language.

**Review by chihsuan — APPROVED** [review]
Thanks for jumping in to help! LGTM and tested well. 👍

**Review by adrianduffell — APPROVED** [review]

**Comment by adrianduffell** [comment]
I didn't grasp previously that catching `\Throwable` will protect against other functions missing. Nice! Approving, though thinking it might be worth as a follow-up creating safe wrappers around the dependent functions being used ([example](https://github.com/woocommerce/woocommerce/pull/51302#discussion_r1756135944)) 🚀
