### PR TITLE
Product Editor: Fix crash and issues with variations (that will cause problems with React 18)

### LINKED ISSUE #48933: Product Editor: Adding variations erroring after React 18 createRoot() change
**Issue Description:**

After the change from React 17's `render()` to React 18's `createRoot()`, it seems like creating a variation in the new product editor causes a block error.

To reproduce, you need to make this change in `./plugins/woocommerce-admin/client/index.js` or use the build from [this branch](https://github.com/woocommerce/woocommerce/pull/48785).

```diff
-import { render } from '@wordpress/element';
+import { render, createRoot } from '@wordpress/element';
...
-       render(
+	createRoot( appRoot ).render(
		<ErrorBoundary>
			<HydratedPageLayout />
-		</ErrorBoundary>,
-              appRoot
+		</ErrorBoundary>
	);
``` 

Screen Capture:

https://github.com/woocommerce/woocommerce/assets/27843274/3d15f749-7ea5-4f8d-9bab-920b70fb294f

Stack Trace:
```
TypeError: w is undefined
    zw https://lemur-of-plovers.jurassic.ninja/wp-includes/js/dist/block-editor.min.js?ver=868d782fcb169133c92b:26
    wt https://lemur-of-plovers.jurassic.ninja/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.2.0:10
    vr https://lemur-of-plovers.jurassic.ninja/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.2.0:10
    js https://lemur-of-plovers.jurassic.ninja/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.2.0:10
    wl https://lemur-of-plovers.jurassic.ninja/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.2.0:10
    bl https://lemur-of-plovers.jurassic.ninja/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.2.0:10
    yl https://lemur-of-plovers.jurassic.ninja/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.2.0:10
    il https://lemur-of-plovers.jurassic.ninja/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.2.0:10
    fl https://lemur-of-plovers.jurassic.ninja/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.2.0:10
    Nn https://lemur-of-plovers.jurassic.ninja/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.2.0:10
    xl https://lemur-of-plovers.jurassic.ninja/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.2.0:10
    xl https://lemur-of-plovers.jurassic.ninja/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.2.0:10
    ol https://lemur-of-plovers.jurassic.ninja/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.2.0:10
    v https://lemur-of-plovers.jurassic.ninja/wp-includes/js/dist/vendor/react.min.js?ver=18.2.0:10
    ce https://lemur-of-plovers.jurassic.ninja/wp-includes/js/dist/vendor/react.min.js?ver=18.2.0:10
```

As far as I can determine, this error originates from [the block editor package from Gutenberg](https://github.com/WordPress/gutenberg/blob/ea72cf12669b42e477ce3b388c5a00ecc2954e29/packages/block-editor/src/components/inner-blocks/index.js#L135)

Reasons for believing so:

The error occurs in this minified file: `./wp-includes/js/dist/block-editor.min.js?ver=868d782fcb169133c92b` on line 41107.
```
 return 0 === Object.keys(w.providesContext).length ? P : (0, s.createElement) (Ow, {
```

Findings on this:
- `w` seems to be a block from context
- changing from `render()` to `createRoot()` activates React's concurrent mode and batching
- It's likely an issue with either of those causing a race condition 
- It's not reproducible in my local environment
- Installing Gutenberg doesn't fix it
- Happens on Jurassic Ninja with WP 6.5.5

### PR DESCRIPTION
**Pull request by mattsherman**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

This PR is a follow up of #49058, which didn't actually fix the problem with the variations tab crashing when variations are generated with React 18.

This PR is a second attempt at fixing the crash. 

This PR is still using the React 17 compatibility mode (`render` vs `createRoot`) --  -- the switch to React 18 for WC Admin is in #48785. **_To run these changes in React 18 mode, see the draft PR #49216 that includes the changes from #48785._**

The change made to prevent the crash when generating variations is honestly more of a workaround than a proper fix. An `ErrorBoundary` was added to the tabs, and that suppresses the error (it is never shown because the tabs re-render before it does). I think that underlying issue causing the error will be addressed when #49014 is addressed.

Without this fix, in the general case of an error in the processing of the tabs (outside of a scenario where the tabs then re-render and correct themselves), the entire tab block (including the tab buttons in the header) are not shown, and the generic block error is shown:

Screenshot 2024-07-08 at 16 40 06

It also makes the following related changes:

- `useLayoutTemplate` is changed to only fetch layout template when an id is provided, preventing the following error from appearing in the dev console when generating variations:

```
Failed to load resource: the server responded with a status of 404 () https://[HOST]/wp-json/wc/v3/layout-templates/__invalid-template-id?_locale=user
```

- The variation options list styling was made more specific, to prevent the following issue when running with React 18:

Screenshot 2024-07-07 at 08 28 43

Closes #48933.

### How to test the changes in this Pull Request:

With a WooCommerce env with the new product editor enabled (**WooCommerce** > **Settings** > **Advanced** > **Features** > **Experimental features**)...

1. Go to **Products** > **Add New**
2. On the `Variations` tab, click `Add Options` and add some variation options.
3. Verify that the variations are added correctly and the selected tab remains `Variations` (note, the loading state showing is a known issue and will be addressed separately; see #49014)
4. Verify that no `Failed to load resource` error was logged in the browser dev console (see above)
5. Verify that the variation options list styling is correct (like below, not above)

Screenshot 2024-07-08 at 16 23 28

6. Install a [test version of the Gutenberg plugin](https://github.com/user-attachments/files/16160002/gutenberg.zip) that forces a crash in the inner block processing of the product editor tabs (don't use this test version of the Gutenberg plugin for anything else... it has hardcoded errors!).
7. Go to **Products** > **Add New**
8. Verify that an error message is shown in each tab and that the tab buttons remain visible.

Screenshot 2024-07-08 at 16 30 52

_Note: This is just to verify that the `ErrorBoundary` put in place looks okay in case it actually ever is shown. It does *not* show when the error causing the crash when generating variations under React 18 happens, because the tabs re-render again before actually shown._

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

File: packages/js/block-templates/src/hooks/use-layout-template/use-layout-template.ts [hunk 1]
```diff
@@ -49,11 +49,11 @@ export const useLayoutTemplate = ( layoutTemplateId: string | null ) => {
 		// To prevent this, we pass `__invalid-template-id` as the ID when there is no layout template ID.
 		// A request will still be triggered, but it will return no results.
 		layoutTemplateId || '__invalid-template-id',
-		// Only perform the query if we have a layout template ID; otherwise, just return null.
+		// Only perform the query if the layout template entity is registered and we have a layout template ID; otherwise, just return null.
 		// Note: Until we are using @woocommerce/core-data 6.24.0 (Gutenberg 17.2),
 		// the REST API requests will still be triggered even when the query is disabled due to a regression.
 		// See: https://github.com/WordPress/gutenberg/pull/56108
-		{ enabled: isEntityRegistered }
+		{ enabled: isEntityRegistered && !! layoutTemplateId }
```
Comment (louwie17) [inline packages/js/block-templates/src/hooks/use-layout-template/use-layout-template.ts:56]: We did have the `!! layoutTemplateId` condition before, which got removed in this PR: https://github.com/woocommerce/woocommerce/pull/47678/files
Adding it back in is fine, but just want to make sure we test the scenario of that PR so that we aren't re-introducing errors. ( This seemed to be related to the latest version of GB, so testing with and without GB would be helpful )

Comment (mattsherman) [reply packages/js/block-templates/src/hooks/use-layout-template/use-layout-template.ts:56]: Agreed. Looking at the PR where it was removed and the code, it seems clear to me that it was an error to remove that. I'll double-check though. Thanks for making sure we are careful here.

**Review by nathanss — APPROVED** [review]
I've tested with the branch provided in the description and was able to run the scenario correctly. No console errors were thrown after generating variations. 

Regarding the code, all the changes look good! Thanks!

File: packages/js/block-templates/src/hooks/use-layout-template/use-layout-template.ts (hunk 1 above)
Comment (mattsherman) [reply packages/js/block-templates/src/hooks/use-layout-template/use-layout-template.ts:56]: I verified that the scenario in #47678 still works, both with GB and without.
