### PR TITLE
Option for free shipping if should ignore discounts or not

### LINKED ISSUE #24754: Coupon Brings Total Below Free Shipping Threshold
I apologize in advance if this isn't the correct section for this issue. Here's the problem I came across:

When a $X off coupon is applied, there are instances where, because of the item cost and the coupon amount, the order total goes below the free shipping threshold which then charges the user shipping, when it shouldn't.

To reproduce create a Free Shipping option for X amount and a Coupon for $X off. Purchase an Item with a price that is eligible for free shipping but will drop below the free shipping threshold when the coupon is applied.

I believe the coupon should be applied after the total amount is calculated, therefore making the coupon always valid.

Thanks for allowing me to bring this to your attention.

### PR DESCRIPTION
**Pull request by boghy933**
### All Submissions:

* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Hello guys, this is my first pull request, i hope i did everything right.
Let me know if i have to change something.

Closes #24754

### How to test the changes in this Pull Request:

1. Create a product
2. Create a discount coupon
3. Create a free shipping method:
 a. Select minimum order amount (insert the product price)
 b. Check the ignore discounts checkbox
4. Go to checkout and try the feature

### Changelog

> Enhancement - Added option to ignore discounts from cart's total amount to enable free shipping.

### CODE REVIEW

File: includes/shipping/free-shipping/class-wc-shipping-free-shipping.php [hunk 1]
```diff
@@ -143,8 +151,10 @@ public function is_available( $package ) {
 			$total = WC()->cart->get_displayed_subtotal();
 
 			if ( WC()->cart->display_prices_including_tax() ) {
-				$total = round( $total - ( WC()->cart->get_discount_total() + WC()->cart->get_discount_tax() ), wc_get_price_decimals() );
-			} else {
+				$total = round( $total - WC()->cart->get_discount_tax(), wc_get_price_decimals() );
+			}
+
+			if ( 'no' === $this->ignore_discounts ) {
```
Comment (claudiosanches) [inline includes/shipping/free-shipping/class-wc-shipping-free-shipping.php]: Maybe this new code can generate problem with rounding values twice.
Better only round those values after this block, like:

```php
if ( WC()->cart->display_prices_including_tax() ) {
	$total = $total - WC()->cart->get_discount_tax();
}

if ( 'no' === $this->ignore_discounts ) {
	$total = $total - WC()->cart->get_discount_total();
}

$total = round( $total, wc_get_price_decimals() );
```

**Review by claudiosanches — CHANGES_REQUESTED** [review]
Good work on it, but there's only one thing that should be nice to fix in order to avoid any trouble with rounding values.

File: includes/shipping/free-shipping/class-wc-shipping-free-shipping.php (hunk 1 above)
Comment (boghy933) [reply includes/shipping/free-shipping/class-wc-shipping-free-shipping.php]: Thank you, i perfectly understand the problem and i have pushed the fix as you suggested.

**Review by claudiosanches — APPROVED** [review]
Thanks for your contribution.

**Comment by rodrigoprimo** [comment]
@claudiosanches I merged this PR and added it to the 4.1.0 milestone since it was already approved by you. Please let me know if you had other plans for it.

**Comment by dougaitken** [comment]
Added needs docs as this will require an update to our documentation for the 4.1 release.
