### PR TITLE
Preview cart updates

### LINKED ISSUE #60150: The editor is not showing previewCart data for the checkout blocks
When the admin doesn't have a cart session, or a cart already saved in localStorage the Editor pages for the checkout blocks fail to display the preview cart 

## **Describe the bug**

When the admin doesn't have a cart session, or a cart already saved in localStorage the Editor pages for the checkout blocks fail to display the preview cart

## **To Reproduce**

1. Log in as an admin in incognito. Make sure you have no cart in the storefront, or a cached cart in LocalStorage
2. Go to the Site Editor > Templates > WooCommerce > Page: Cart or Page: Checkout
3. Notice the missing cart items and data

## **Expected behavior**

A preview cart should be rendered with the Beanie and Cap products

## Environment

Please fill out any of the below that applies

**Operating System/Device**

- [ ] Windows
- [ ] MacOS
- [ ] Linux
- [ ] iPhone
- [ ] Samsung
- [ ] Other (add in additional context field)

**Version:** 

**Browser**

- [ ] Desktop Edge
- [ ] Desktop Chrome/Chromium
- [ ] Desktop Safari
- [ ] Mobile Edge
- [ ] Mobile Chrome/Chromium
- [ ] Mobile Safari
- [ ] Other (add in additional context field)

**Version:**

### PR DESCRIPTION
**Pull request by ralucaStan**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

When using the store to get the `previewCart` data in the Editor, we don't finish resolutions for `getCartData` and we don't save the `previewCart` to the persistence layer.

This bug happened because there was some overlap at the cart store and cart persistence level, between preview cart data (Editor) and real carts.

Some context: 
Before [this change](https://github.com/woocommerce/woocommerce/pull/58782/files#r2143193550) the cart call was made everywhere and `finishResolution('getCartData')` was never called. So in the editor, we would[ be here](https://github.com/woocommerce/woocommerce/blob/912a59181b894d2029e00b6909c05acacac11de2/plugins/woocommerce/client/blocks/assets/js/data/cart/resolvers.ts#L22-L24), dispatching the same `receiveCart` after getting a `previewCart` 
 [my 2nd chage](https://github.com/woocommerce/woocommerce/pull/59920/files#diff-d8b0e5af5b93537eb599d6e53651c3be94f2765556df3bbe47780c86d3067b19L62) made sense in a storefront. But in the editor, not so much, now that we don’t have the cart call. We still need that cart preview data, which previously we were getting via the call.

While debugging, I found another issue. We are saving the `previewCart` in localStorage. Not an issue before, because the `/cart` call was mostly done everywhere. So we were getting the right cart.

Closes  https://github.com/woocommerce/woocommerce/issues/60150 \
Closes https://linear.app/a8c/issue/WOOPLUG-5239/the-editor-is-not-showing-previewcart-data-for-the-checkout-blocks

(For Bug Fixes) Bug introduced in PR  https://github.com/woocommerce/woocommerce/pull/58782/files#r2143193550

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Log in as an admin in incognito. Make sure you have no cart in the storefront, or a cached cart in LocalStorage
2. Go to the Site Editor > Templates > WooCommerce > Page: Cart or Page: Checkout
3. Notice the cart preview data is shown (Beanie & Cap)

4. Go to the store. Notice the Mini-Cart is empty; click it to confirm 
5. Add a product to the cart; 
6. Go to the Editor cart page and notice the preview data

7. Go back to the store, and notice you have the product you previously added
8. Log out
9. Log back in again and notice the Mini-Cart is showing the product you added
10. Go to checkout and place the order

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce/client/blocks/assets/js/blocks/cart/test/editor-integration.tsx [hunk 1]
```diff
@@ -126,13 +140,44 @@ describe( 'Cart block editor integration', () => {
 		expect( filledCartAudioOption ).not.toBeInTheDocument();
 	} );
 
+	it( 'shows the cart preview in the editor', async () => {
```
Comment (ralucaStan) [inline plugins/woocommerce/client/blocks/assets/js/blocks/cart/test/editor-integration.tsx:143]: As an integration test this wouldn't have helped catch the bug, but I think we removed the editor e2e test.

File: plugins/woocommerce/client/blocks/assets/js/data/cart/index.ts [hunk 2]
```diff
@@ -65,11 +67,15 @@ window.addEventListener( 'load', () => {
...
+		! isAddingToCart() &&
+		! isEditor() // Don't finish resolution in editor,but only for real carts
 	) {
-		// Prevent the API request from being made.
 		wpDispatch( store ).finishResolution( 'getCartData' );
 	}
+
+	if ( isEditor() ) {
+		wpDispatch( store ).receiveCart( previewCart );
+	}
```
Comment (mikejolley) [inline plugins/woocommerce/client/blocks/assets/js/data/cart/index.ts]: Why is this needed? We resolve `previewCart` in `getCartData` if in the editor. I removed this and it seemed to work still?

File: plugins/woocommerce/client/blocks/assets/js/data/cart/index.ts [hunk 3]
```diff
@@ -65,11 +67,15 @@ window.addEventListener( 'load', () => {
 
 	if (
 		( ! hasCartSession() || hasItemsInCachedCart ) &&
-		! isAddingToCart()
+		! isAddingToCart() &&
+		! isEditor() // Don't finish resolution in editor,but only for real carts
 	) {
-		// Prevent the API request from being made.
```
Comment (mikejolley) [inline plugins/woocommerce/client/blocks/assets/js/data/cart/index.ts:70]: Was this comment inaccurate?

**Review by mikejolley — COMMENTED** [review]
I'm going to test some more but I've left some comments. I think one change might be unnecessary. Can you confirm?

File: plugins/woocommerce/client/blocks/assets/js/data/cart/index.ts (hunk 3 above)
Comment (ralucaStan) [reply plugins/woocommerce/client/blocks/assets/js/data/cart/index.ts:70]: It was accurate, I'll add it back.

File: plugins/woocommerce/client/blocks/assets/js/data/cart/index.ts (hunk 2 above)
Comment (ralucaStan) [reply plugins/woocommerce/client/blocks/assets/js/data/cart/index.ts]: It's not necessary. I've removed it.

File: plugins/woocommerce/client/blocks/assets/js/data/cart/index.ts [hunk 4]
```diff
@@ -65,7 +66,8 @@ window.addEventListener( 'load', () => {
 
 	if (
 		( ! hasCartSession() || hasItemsInCachedCart ) &&
-		! isAddingToCart()
+		! isAddingToCart() &&
+		! isEditor() // Don't finish resolution in editor,but only for real carts
```
Comment (mikejolley) [inline plugins/woocommerce/client/blocks/assets/js/data/cart/index.ts:70]:
```suggestion
		! isEditor() // Don't finish resolution in editor. Only resolve real carts.
```

**Review by mikejolley — APPROVED** [review]
Thanks @ralucaStan Added one comment. I smoke tested cart, and checked the page editor and site editor. Issue is resolved.

R/e the test, I see its checking that data is loading. But isn't this data you resolve before the test? I wonder if that would catch a real world issue. Regardless, thanks for adding something.

✅

File: plugins/woocommerce/client/blocks/assets/js/data/cart/index.ts (hunk 4 above)
Comment (ralucaStan) [reply plugins/woocommerce/client/blocks/assets/js/data/cart/index.ts:70]: Missed this one, sorry.

Comment (ralucaStan) [reply plugins/woocommerce/client/blocks/assets/js/data/cart/index.ts:70]: > R/e the test, I see its checking that data is loading. But isn't this data you resolve before the test? I wonder if that would catch a real world issue. Regardless, thanks for adding something.

Same thoughts here: https://github.com/woocommerce/woocommerce/pull/60138#discussion_r2247572061
