### PR TITLE
Throw an error if a coupon item ID (readonly) is specified during an order update | #27290

### LINKED ISSUE #27290: [API] PUT /orders with incorrect coupon format removes coupons
**Describe the bug**
When using the API to update (`PUT`) an order, sending back the 'coupon_lines' we got from the API during the`GET` call removes all set coupons on the order. 

The (API documentation)[https://woocommerce.github.io/woocommerce-rest-api-docs/#update-an-order] doesn't specify this behaviour, or the correct way to deliver the `coupon_line` property.

**To Reproduce**
1. Create a coupon.
2. Create an order using the coupon using the store or admin interface (note, coupon has been correctly added to the order).
3. `GET` the order via the API.
4. `PUT` the response from the `GET` via the API.
5. Note the coupon has disappeared in the admin interface, and totals have been recalculated.

**Expected behavior**
I expect the coupon to remain on the order. Otherwise I would expect the API to error (`400 Bad Request`). Or the current behaviour to be documented, with the correct format to update/change `coupon_lines` added.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
N/A

### PR DESCRIPTION
**Pull request by barryhughes**
### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Currently, if an order is updated via the REST API (see full steps to replicate in #27290), _and_ if coupons are specified, _and_ if one or more of those coupon objects contain an `id` property, then:

* The order is updated, and a `200 OK` response comes back.
* All coupons that were previously applied to the order will have been dropped, and the coupon specified in the request will not have been added.

The coupon lines are being rejected in the above case because the `id` field is readonly [(see here)](https://woocommerce.github.io/woocommerce-rest-api-docs/?php#order-coupon-lines-properties). However, as discussed in the linked issue, in a situation like this it would be preferable to bail out so that:

* A suitable error message is returned (with a `400 Bad Request` status)
* The order is not modified at all.

Closes #27290.

### How to test the changes in this Pull Request:

To see the problem using the [latest production code (5.0)](https://github.com/woocommerce/woocommerce/releases/tag/5.0.0) first of all:

1. Generate an order with a coupon applied.
2. Via a `PUT` request, try updating the order and apply another (or the same) coupon—be sure to include an `id` field for each coupon in the `coupon_lines` array.
3. Notice a `200 OK` response comes back but that _all coupons have been removed (unexpected!)_ :grimacing: 

Using this changeset:

1. Repeat the above.
2. Notice the response is a `400 Bad Request` and that the order itself is unchanged _(much clearer!)_ :slightly_smiling_face: 

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

:memo: This change makes us stricter when it comes to handling situations where a coupon ID is set, _but nothing is changed if other readonly coupon fields are specified._ For example, with this change in place, if we update an order and specify one of the coupon lines as follows:

```json
{
    "id": 123,
    "code": "big-discount"
}
```

Then we get a `400 Bad Request`. However, the following will result in a `200 OK`, even though the `discount` field—just like the `id` field—is also readonly.

```json
{
    "id": 123,
    "discount": "500"
}
```

Arguably, we should also be strict about this _but it also feels like it is less critical_ and so we could follow-up with a future change to further tighten things, but still ship this more important incremental change in the meantime.

### Changelog entry

> Fix - If `coupon_lines` are specified within a REST API order update, return an error if coupon item IDs are also specified.

### CODE REVIEW

File: tests/legacy/unit-tests/rest-api/Tests/Version3/orders.php [hunk 1]
```diff
@@ -682,6 +683,25 @@ public function test_update_order_add_coupons() {
...
+						'code' => 'fake-coupon',
+					),
+				),
+			)
+		);
+		$response = $this->server->dispatch( $request );
+		$data     = $response->get_data();
+
+		$this->assertEquals( 400, $response->get_status() );
+		$this->assertEquals( 'woocommerce_rest_coupon_item_id_readonly', $data['code'] );
```
Comment (barryhughes) [inline tests/legacy/unit-tests/rest-api/Tests/Version3/orders.php:704]: It felt logical to ad this scenario (a failing update involving coupons, where the item ID is specified for a `coupon_line` item) to this existing test but I'm definitely happy to break it out into its own test method if preferred.

**Review by claudiosanches — APPROVED** [review]
Great work!
