### PR TITLE
#48459 coupon email restrictions fix

### LINKED ISSUE #48459: [BUG]: Coupon email restrictions not correctly validating customer emails
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When a customer is logged-in and attempts to apply a coupon that is restricted by email in their cart the coupon does not correctly validate the logged-in customer's profile or billing email addresses.

### Expected behavior

A coupon with an email restriction should correctly validate and be redeemable if a customer is logged in with the restricted email or has the restricted email saved as their billing email.

### Actual behavior

Coupons that are saved with email restrictions do not correctly validate with logged-in customer profile or saved billing email addresses.

### Steps to reproduce

1. Create a new coupon and save "_test@test.test_" to the "_Allowed emails_" field under "_Usage restriction_".
image
2. Create a new customer account with the "_test@test.test_" email address.
image
3. [Optional] Update the newly created customer account's billing email address to "_test@test.test_".
image
4. Log in with the newly created customer account.
5. Add any priced product to your cart.
6. Navigate to the cart page.
7. Apply the above newly created coupon to the cart.
image

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): http://wordpress.local
Site address (URL): http://wordpress.local
WC Version: 8.9.3
REST API Version: ✔ 8.9.3
Action Scheduler Version: ✔ 3.7.4
Log Directory Writable: ✔
WP Version: 6.5.4
WP Multisite: –
WP Memory Limit: 2 GB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.23.3
PHP Version: 8.2.3
PHP Post Max Size: 500 MB
PHP Time Limit: 300
PHP Max Input Vars: 1000
cURL Version: 7.74.0
OpenSSL/1.1.1n

SUHOSIN Installed: –
MySQL Version: 8.0.32
Max Upload Size: 500 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.2.0
WC Database Prefix: wp_
Total Database Size: 7.20MB
Database Data Size: 5.35MB
Database Index Size: 1.85MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 4.08MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_posts: Data: 0.05MB + Index: 0.06MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_bundle_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_bundled_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_bundled_items: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wpsmtp_logs: Data: 0.08MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

attachment: 3
guest_author: 1
page: 7
post: 3
product: 10
product_variation: 3
revision: 2
shop_coupon: 1
shop_order: 2
wp_navigation: 1
wp_template: 2

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 8.9.3

### Settings ###

API Enabled: –
Force SSL: –
Currency: ZAR (R)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: bundle (bundle)
external (external)
grouped (grouped)
simple (simple)
variable (variable)
woosb (woosb)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 32 KB

### WC Pages ###

Shop base: #9 - /shop/
Cart: #10 - /cart/
Checkout: #11 - /checkout/
My account: #12 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty-Four
Version: 1.1
Author URL: https://wordpress.org
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ❌ Not declared

### Templates ###

Overrides: /var/www/wp/wp-content/plugins/woocommerce/templates/block-notices/error.php
/var/www/wp/wp-content/plugins/woocommerce/templates/block-notices/notice.php
/var/www/wp/wp-content/plugins/woocommerce/templates/block-notices/success.php

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
product-virtual-downloadable
product-external-affiliate
product-grouped
product-linked
product-pre-publish-modal
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
settings
async-product-editor-category-field
launch-your-store

Daily Cron: ✔ Next scheduled: 2023-09-26 12:37:18 +00:00
Options: ✔
Notes: 75
Onboarding: skipped

### Action Scheduler ###

Pending: 25
Oldest: 2023-09-26 12:37:20 +0000
Newest: 2024-06-13 07:53:24 +0000

### Status report information ###

Generated at: 2024-06-13 07:59:26 +00:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by EstianH**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

We're creating a $customer (WC_Customer) object from the $user (WP_user) object to correctly fetch the current customer's email address (_$customer->get_email_) and billing address (_$customer->get_billing_email()_).
This PR fixes bug #48459 by making use of the WC_Customer class methods instead of WP_User class methods.

Closes #48459

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Create a new coupon and save "_test@test.test_" to the "_Allowed emails_" field under "_Usage restriction_".
2. Create a new customer account with the "_test@test.test_" email address.
3. [Optional] Update the newly created customer account's billing email address to "_test@test.test_".
4. Log in with the newly created customer account.
5. Add any priced product to your cart.
6. Navigate to the cart page.
7. Apply the above newly created coupon in the cart.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

**Comment by tarunvijwani** [comment]
@EstianH Thank you for raising the PR.  Unfortunately, I'm unable to reproduce the issue and asked for more details here: https://github.com/woocommerce/woocommerce/issues/48459. Looking forward to hearing back from you.

**Comment by EstianH** [comment]
@tarun

> @EstianH Thank you for raising the PR. Unfortunately, I'm unable to reproduce the issue and asked for more details here: #48459. Looking forward to hearing back from you.

@tarunvijwani I've left feedback on the issue #48459 .

File: plugins/woocommerce/includes/class-wc-discounts.php [hunk 1]
```diff
@@ -969,8 +969,16 @@ protected function validate_coupon_allowed_emails( $coupon ) {
...
 		$user         = wp_get_current_user();
-		$check_emails = array( $user->get_billing_email(), $user->get_email() );
+
+		try {
+			$customer     = new WC_Customer( $user->ID );
+			$check_emails = array( $customer->get_billing_email(), $customer->get_email() );
+		} catch ( Exception $e ) {
+			$wc_logger = wc_get_logger();
+			$wc_logger->debug( $e->getMessage() );
+		}
```
Comment (wavvves) [inline plugins/woocommerce/includes/class-wc-discounts.php]: Perhaps we can avoid using the WC_Customer object, and dealing with a possible Exception, and also make this on par with an existing validation on [class-wc-cart.php#L1663](https://github.com/woocommerce/woocommerce/blob/86bc37797707b822324c241761922b8bfa9717e8/plugins/woocommerce/includes/class-wc-cart.php#L1663) by using:

`$check_emails = array( $user->user_email );`

Then billing email would come from customer (via `WC_Cart`) or directly from `WC_Order`.

An alternate way to this would be resorting to `wc()->customer`, but I believe` $user->user_email` would be enough to cover the account email.

File: plugins/woocommerce/changelog/48488-48459-coupon-email-restriction-fix [hunk 2]
```diff
@@ -0,0 +1,4 @@
+Significance: patch
+Type: fix
+
+</details>  <details>  <summary>Changelog Entry Comment</summary>
```
Comment (wavvves) [inline plugins/woocommerce/changelog/48488-48459-coupon-email-restriction-fix]:
```suggestion
Fixed a bug causing account email not to be taken in consideration for coupon validation when a customer has a different billing email set.
```

**Review by wavvves — DISMISSED** [review]
Thanks for your contribution, this is highly appreciated :) 
I left some suggestions.

Also, can we add/update a unit test for this? Let me know if you need assistance, or prefer that I would collaborate and submit the test myself.

**Comment by EstianH** [comment]
> Also, can we add/update a unit test for this? Let me know if you need assistance, or prefer that I would collaborate and submit the test myself.

Thanks @wavvves, I've pushed a new commit re the change you recommended.
Please could you jump in to collaborate by submitting the unit test from your end :).

**Review by mikejolley — APPROVED** [review]
I've retested this and updated the changelog. Thanks for making the changes.

@wavvves I didn't see any coupon restriction tests in place currently so this is definitely a gap. I don't think creation of those should block this fix so I've made a small note in https://github.com/woocommerce/woocommerce/issues/45584
