### PR TITLE
[Accessibility] Remove reference to label in aria-describedby attribute on payment radio options

### LINKED ISSUE #55416: Accessibility: Duplicative label Announcement
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

The fix to https://github.com/woocommerce/woocommerce/issues/51794 in https://github.com/woocommerce/woocommerce/pull/52949 added a duplicative label announcement for screen reader users.

### Recommended Fix
Remove the "ID" referring to the `<label>` from the aria-describedby attributes on each radio input. The only ID that should be referenced by the aria-describedby attribute is the ID for the description. The label is already associated with the input because the `<label>` tag is wrapped around the input.

### Expected behavior

The label will only be read once and then the description will be read out.

### Actual behavior

The label is read twice by NVDA because it is read as the label and is also referenced in the aria-describedby attribute on the input. 

For instance, the Cash on Delivery input reads as "Cash on delivery radio button checked Cash on
delivery Pay with cash upon delivery. 3 of 3".

#### Screenshot 
Image showing NVDA output on Cash on Deliver filed

#### Code causing the issue:
```
<div class="wc-block-components-radio-control-accordion-option wc-block-components-radio-control-accordion-option--checked-option-highlighted">
   <label class="wc-block-components-radio-control__option wc-block-components-radio-control__option-checked" for="radio-control-wc-payment-method-options-cod">
      <input id="radio-control-wc-payment-method-options-cod" class="wc-block-components-radio-control__input" type="radio" name="radio-control-wc-payment-method-options" aria-describedby="radio-control-wc-payment-method-options-cod__label radio-control-wc-payment-method-options-cod__content" aria-disabled="false" value="cod">
      <div class="wc-block-components-radio-control__option-layout">
         <div class="wc-block-components-radio-control__label-group">
            <span id="radio-control-wc-payment-method-options-cod__label" class="wc-block-components-radio-control__label">
               <span class="wc-block-components-payment-method-label">Cash on delivery</span>
            </span>
         </div>
      </div>
   </label>
   <div id="radio-control-wc-payment-method-options-cod__content" class="wc-block-components-radio-control-accordion-content"
      <div>Pay with cash upon delivery.</div>
   </div>
</div>
```

### Steps to reproduce

1. Add a product the cart.
2. Go to the checkout page.
3. Turn on the NVDA or VoiceOver screen reader.
4. Listen to the radio inputs in the payment method section.

Alternatively, you can also review the code for the aria-describedby attribute on the input here: https://github.com/woocommerce/woocommerce/blob/71f0b7201d0df436affc785d79c5bdbbb854818e/plugins/woocommerce-blocks/packages/components/radio-control/option.tsx#L49

### WordPress Environment

N/A

### Isolating the problem

- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by Manussakis**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes #55416 .

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Add at least two payment options in the admin.
2. Install a block-based theme and make sure the Checkout page uses the block version.
3. Add a product to the Cart and go to the Checkout page.
4. Turn on screen reader.
5. Focus on the payment options.
6. Verify the radio input label is not voiced twice.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [x] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce-blocks/packages/components/radio-control/option.tsx [hunk 1]
```diff
@@ -47,7 +47,6 @@ const Option = ( {
 				onChange={ onChangeValue }
 				checked={ checked }
 				aria-describedby={ clsx( {
-					[ `${ name }-${ value }__label` ]: label,
 					[ `${ name }-${ value }__secondary-label` ]: secondaryLabel,
 					[ `${ name }-${ value }__description` ]: description,
 					[ `${ name }-${ value }__secondary-description` ]:
```
Comment (Manussakis) [inline plugins/woocommerce-blocks/packages/components/radio-control/option.tsx:52]: The `secondaryLabel`, `description`, and `secondaryDescription` references have not been removed since they point to valid DOM elements:
image

**Comment by Manussakis** [comment]
@dkotter This PR is ready for code review.
Thanks!

**Review by dkotter — APPROVED** [review]
@ankitguptaindia @qasumitbagthariya This is ready for QA

**Comment by ankitguptaindia** [comment]
**QA/Test Report-** ✅ 
------------

**Testing Environment -** 

<Details>

* WordPress: 6.7.2
* Theme:  
  - Storefront Version: 4.6.0  
  - Twenty Twenty-Five Version: 1.1
  - Any Random theme- Twenty Ten Version: 4.3
* WooCommerce - Development version with this fix-specific branch.  
* PHP: 8.3
* Web Server: Nginx
* Browser: Chrome - Version 132
* OS: macOS Sonoma 14.6.1 


</Details>


**Test Results -** 

The changes work as intended and tested across Safari, Firefox, and Chrome. Accessibility was verified using macOS VoiceOver Version 10. Testing was conducted with both the Twenty Twenty-Five, Storefront theme and Twenty Twenty-Four theme.
 

**Functional Demo /  Screencast -**

**With macOS Voice Over:**



**Without Fix** 

https://github.com/user-attachments/assets/762d66f9-0891-47f2-ac9e-4a8115d34a93

**With Fix** 

https://github.com/user-attachments/assets/88b9b2ff-5186-470d-9e79-713cd406115c

**Comment by ankitguptaindia** [comment]
Hi [@Manussakis](https://github.com/Manussakis) Would you mind un-draft this PR for next review?

[@vikrampm1](https://github.com/vikrampm1) Could you please cross check auto assigned WooCR team is correct for this PR?

Thanks both!

**Review by opr — COMMENTED** [review]
I'm getting a different experience than what is logged in the [QA report](https://github.com/woocommerce/woocommerce/pull/55503#issuecomment-2660900828) in my voiceover testing in Firefox, for this

image


https://www.loom.com/share/4f4d0505b5694ad5ae173c177888ad3f

It reads it out twice, I think it's reading each individual line and then the content as a whole. Are you experiencing this? Could it be that I am using VoiceOver incorrectly? I am tabling into the shipping option and just waiting for the readout, would users typically navigate to it in a different way?

**Comment by vikrampm1** [comment]
@Manussakis for your review above. Please also remove [WIP] from the title and make this PR ready for review.

**Review by Konamiman — APPROVED** [review]

**Comment by Manussakis** [comment]
Hey @opr 👋

> I'm getting a different experience than what is logged in the QA report in my voiceover testing in Firefox... It reads it out twice

I don't believe you are using VoiceOver incorrectly, It just seems that this is how VoiceOver+Firexfox treats radio groups.
I set a very basic example and got the same outcome as yours:

The code:
```html
<div>
    <label for="payment-1">
        <input type="radio" name="payment" id="payment-1" value="1">
        Direct transfer
    </label>
    <label for="payment-2">
        <input type="radio" name="payment" id="payment-2" value="2">
        Cash on delivery
    </label>
</div>
```

How VoiceOver+Firefox announces it:

https://github.com/user-attachments/assets/b1860f33-a992-441f-9497-f62933b54ccb

**Comment by opr** [comment]
Ok, thanks. Is it possible to fix this in Firefox, or is this just expected and normal behaviour? @amberhinds (pinging as the initial issue creator) do you have any experience with this?

Gabriel, what happens if we only render the `content` class in `aria-describedby`, and remove everything else. From my testing that _seemed_ OK but maybe you could do a more thorough investigation on that?

**Comment by Manussakis** [comment]
@opr 
> Is it possible to fix this in Firefox, or is this just expected and normal behaviour?

That's the normal behavior of Firefox when the input is wrapped by the label like the [radio-control option component is](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce-blocks/packages/components/radio-control/option.tsx#L33).
If the markup was like the example below, the second announcement (i.e., "Direct transfer", group) wouldn't happen.
```html
<div>
    <label for="payment-1">Direct transfer</label>
    <input type="radio" name="payment" id="payment-1" value="1">
    
    <label for="payment-2">Cash on delivery</label>
    <input type="radio" name="payment" id="payment-2" value="2">
</div>
```
That's how Firefox+VoiceOver announces it:

image


I don't recommend investing time in updating the markup because this would cause more harm than good since could break CSS selectors of other themes and plugins.

---

> Gabriel, what happens if we only render the content class in aria-describedby, and remove everything else. From my testing that seemed OK but maybe you could do a more thorough investigation on that?

I touched on this topic in [this comment](https://github.com/woocommerce/woocommerce/pull/55503#discussion_r1956687198). If we only keep the content in `aria-describedby`, the others pieces of information wouldn't be voiced, i.e.:
- Description.
- Secondary description.
- Secondary label.

**Review by opr — APPROVED** [review]
Thanks @Manussakis for the writeup and looking into how VoiceOver on Firefox works!

I agree refactoring markup here isn't a good solution, and I appreciate you highlighting what happens if we remove the other classnames besides content.

So, since this is working, and doesn't introduce a regression I will approve the PR. Thanks again for helping out with this 🙇🏼
