### PR TITLE
Fix filter by attribute widget now working for "Any..." attributes

### LINKED ISSUE #27419: Widget filter products by attributes does not work correctly
Hi dear,

Recently I updated WooCommerce to version 4.4.1 and I found the widget filter products does not work correctly

**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
I use Storefront theme and run on WordPress 5.5 and WooCommerce 4.4.1, I create an attribute "Color" with three options "Blue, Grey, Red" and I create variable product and setup the same price for all product variations

**Expected behavior**
The widget need to work correctly

**Actual behavior**

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Go to 'WooCommerce -> Attributes' and create the "Color" attributes with three options  "Blue, Grey, Red"
2. Create a new product variable with these options
3. And then setup the variation like as screenshot
4. Go to Appearance -> Widgets and drop a "Widget Filter Products by attribute" in "Sidebar" area
5. Go to Shop page and see 

**Screenshots**
alt text
alt text
alt text
alt text

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a [Storefront](https://woocommerce.com/storefront/) theme active 
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
### WordPress Environment ###

WordPress address (URL): http://localhost/theme-upgrade/payna
Site address (URL): http://localhost/theme-upgrade/payna
WC Version: 4.4.1
REST API Version: ✔ 1.0.15
WC Blocks Version: ✔ 3.1.0
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.4.0
Log Directory Writable: ✔
WP Version: 5.5
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.4.2
PHP Post Max Size: 128 MB
PHP Time Limit: 60
PHP Max Input Vars: 5000
cURL Version: 7.65.1
OpenSSL/1.0.2o

SUHOSIN Installed: –
MySQL Version: 5.7.26
Max Upload Size: 32 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.4.1
WC Database Prefix: wp_
Total Database Size: 13.37MB
Database Data Size: 11.43MB
Database Index Size: 1.94MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 4.02MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 4.52MB + Index: 0.42MB + Engine InnoDB
wp_posts: Data: 1.52MB + Index: 0.17MB + Engine InnoDB
wp_revslider_css: Data: 0.13MB + Index: 0.00MB + Engine InnoDB
wp_revslider_css_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_layer_animations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_layer_animations_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_navigations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_navigations_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_sliders: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_sliders_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_slides: Data: 0.20MB + Index: 0.00MB + Engine InnoDB
wp_revslider_slides_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_static_slides: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_static_slides_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.06MB + Index: 0.05MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 330
elementor_library: 39
nav_menu_item: 132
page: 38
post: 16
product: 123
product_variation: 1
revision: 10
shop_order: 1
wp_block: 2
wpcf7_contact_form: 2

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 4.4.1

### Inactive Plugins (11) ###

Akismet Anti-Spam: by Automattic – 4.1.5
Contact Form 7: by Takayuki Miyoshi – 5.2.1
Elementor: by Elementor.com – 2.9.14
Elementor Pro: by Elementor.com – 2.7.2
Envato Market: by Envato – 2.0.3
Hello Dolly: by Matt Mullenweg – 1.7.2
LA-Studio Core: by LA-Studio – 2.0.5
LA-Studio Header Builder: by LA-Studio – 1.0.5
LaStudio Elements For Elementor: by LaStudio – 1.0.4
Payna Package Demo Data: by LA Studio – 1.0.1
Slider Revolution: by ThemePunch – 6.2.19

### Settings ###

API Enabled: –
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #3331 - /shop/
Cart: #3336 - /cart/
Checkout: #3343 - /checkout/
My account: ❌ Page does not contain the shortcode.
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 2.6.0
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 38
Oldest: 2020-08-14 08:54:40 +0000
Newest: 2020-08-20 05:19:00 +0000
</details>

### PR DESCRIPTION
**Pull request by Konamiman**
### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

This pull requests fixes two bugs related to attribute filtering for variable products:

1. [Filter by attribute widget not counting variations having an attribute value of "Any..."](https://github.com/woocommerce/woocommerce/issues/27419)

When a variation has a value of "Any..." for a given attribute, then that variation isn't counted by the "Filter by attribute" widget corresponding to that attribute.

2. `attribute_` metadata entries with empty values not handled correctly when adding or removing variation attributes

This is an old bug (present in pre-4.4 versions). When a new variation attribute is added to the main product, then all the already existing variations will display the attribute with a value of "Any...", but the corresponding `attribute_` metadata entry for the variation won't be created. (If an existing variation is manually set to "Any..." and saved then it works as expected and the entry is created)

Conversely, when removing the attribute from the main product the corresponding `attribute_` metadata entries for the variations won't be removed.

A data migration is added too to backfill possible missing values for these metadata entries.

Closes #27419.

### How to test the changes in this Pull Request:

Start with an empty shop (no products).

1. Create an attribute named "Color" with three terms, e.g. "Black", "White", "Blue".
2. Create an attribute named "Style" with three terms, e.g. "Classic", "Sport", "Beach".
3. Add a "Filter by attribute" widget, to filter by "Color".
4. Add a variable product in which the "Color" attribute is used for all variations, with one variation per color.
5. Load the shop, verify that the filter by color widget is displaying all three colors, with a count of 1 for each.
6. Add a second variable product, but this time use the "Style" attribute to generate all variations.
7. After the three style variations have been created, add "Color" as an additional variation attribute with all three values. Now the existing variations should automatically get "Any..." as the value for the color attribute:

image

8. Reload the shop. Without the fix, it still displays 1 for all colors. With the fix, it displays 2 for each color (it's counting the "Any..." product now).
9. Set one of the variations to "Out of stock". Reload the shop and verify that the value of the counters hasn't changed.
10. Set all the variations to "Out of stock". Reload the shop and verify that the value of the counters is now 1 (and now the product doesn't display in the shop). Set the variations to "In stock" again.
11. Remove the "Color" attribute from the product, reload the shop and verify that all counters go back to 1.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Fix - Filter by attribute widget not working properly for variations having attribute values of "Any..."
> Fix - "attribute_" metadata entries not created and deleted properly for variations

### CODE REVIEW

**Comment by rrennick** [comment]
@Konamiman You've got a unit test failure in PHP 7.4.

**Comment by rrennick** [comment]
@Konamiman In the screenshot below the `Test 25133` product has 5 variations that are `Blue` so the count of `8` is technically correct. However, it's inconsistent with the number showing in the sorting and the number of products shown on the page.

Screen Shot 2020-08-28 at 10 22 37 AM

**Comment by rrennick** [comment]
The other thing I wanted to test was adding an attribute term after the variable product had been created. I added `Extra Large`. 

Screen Shot 2020-08-28 at 10 44 46 AM

The first test product has `Any` size

Screen Shot 2020-08-28 at 10 45 13 AM

The widget on refresh

Screen Shot 2020-08-28 at 10 46 13 AM

A hook needs to be added on updating attribute terms to sync the product lookup table.

**Comment by Konamiman** [comment]
Hi @rrennick. After you add a new term you need to manually add that new term to the list of values used for variations here:

image

If what you mean is that adding a new term should automatically add the term to the list of attributes used for variations on all variable products using that attribute: maybe. But I think that's a separate discussion, not really related to this PR as that's the way it worked before.

File: includes/widgets/class-wc-widget-layered-nav.php [hunk 1]
```diff
@@ -409,9 +410,36 @@ protected function get_filtered_term_product_counts( $term_ids, $taxonomy, $quer
...
+		        SELECT ID FROM {$wpdb->posts} AS parent
+		        WHERE parent.ID = {$wpdb->posts}.post_parent AND parent.post_status NOT IN ('publish')
+		    )
+			{$main_tax_query_sql['where']}";
+
+		// Generate the final query as the union+count of both.
+		$query_sql = "
+			SELECT COUNT(DISTINCT(product_id)) AS term_count, term_count_id FROM (
+				{$main_query_sql}
+				UNION ALL
```
Comment (vedanshujain) [inline includes/widgets/class-wc-widget-layered-nav.php:438]: Instead of unionizing this, can we fetch the result in two separate queries and then combine. Basically group by over union is forcing MySQL to do a filesort with both the results, also this can have a large insert locking footprint.

I think we should favor performance here instead of atomicity.

**Review by vedanshujain — COMMENTED** [review]
I am still reviewing and testing the PR, but adding some initial comments that will be helpful.

File: includes/widgets/class-wc-widget-layered-nav.php [hunk 2]
```diff
@@ -365,9 +365,10 @@ protected function get_filtered_term_product_counts( $term_ids, $taxonomy, $quer
 		$main_tax_query_sql = $this->convert_tax_query_to_sql( $main_tax_query );
 		$term_ids_sql       = '(' . implode( ',', array_map( 'absint', $term_ids ) ) . ')';
 
-		// Generate query.
+		// Generate the first part of the query.
+		// This one will return non-variable products and variable products with concrete values for the attributes.
 		$query           = array();
-		$query['select'] = "SELECT COUNT( DISTINCT {$wpdb->posts}.ID ) as term_count, terms.term_id as term_count_id";
+		$query['select'] = "SELECT {$wpdb->posts}.post_parent as product_id, terms.term_id as term_count_id";
```
Comment (vedanshujain) [inline includes/widgets/class-wc-widget-layered-nav.php:371]: are we sure about this change? `post_parent` is set to 0 for normal products, i think this is applicable only for variations.

File: includes/wc-update-functions.php [hunk 3]
```diff
@@ -2242,3 +2242,41 @@ function wc_update_450_sanitize_coupons_code() {
...
 	return false;
 }
+
+/**
+ * Add empty meta attribute values for variable products having a value of "Any..." for the attribute,
+ * only for the variations missing them, in increments of 100 products.
+ *
+ * @return bool true if there are more products to process.
+ */
+function wc_update_450_insert_attribute_metadata_for_variations_not_having_it() {
```
Comment (vedanshujain) [inline includes/wc-update-functions.php:2252]: any way to work around this migration? this is going to really really long time for many hosts, let's go an extra mile to avoid this if we can.

File: includes/widgets/class-wc-widget-layered-nav.php (hunk 1 above)
Comment (ObliviousHarmony) [reply includes/widgets/class-wc-widget-layered-nav.php:438]: It's worth mentioning that we're caching this in a transient so if it's a little bit slower it isn't necessarily a significant problem so long as the locking footprint isn't against the posts table. @Konamiman and @vedanshujain what do you think of using this instead of a union or two queries:

```php
// Generate query.
$query           = array();
$query['select'] = "SELECT COUNT( DISTINCT {$wpdb->posts}.ID ) as term_count, terms.term_id as term_count_id";
$query['from']   = "FROM {$wpdb->posts}";
$query['join']   = "
	INNER JOIN {$wpdb->term_relationships} AS tr ON {$wpdb->posts}.ID = tr.object_id OR {$wpdb->posts}.post_parent = tr.object_id
	INNER JOIN {$wpdb->term_taxonomy} AS term_taxonomy ON tr.term_taxonomy_id = term_taxonomy.term_taxonomy_id
	LEFT JOIN (
		SELECT term_taxonomy_sub.taxonomy, tr_sub.object_id, term_taxonomy_sub.term_id FROM {$wpdb->term_relationships} AS tr_sub
		INNER JOIN {$wpdb->term_taxonomy} AS term_taxonomy_sub ON tr_sub.term_taxonomy_id = term_taxonomy_sub.term_taxonomy_id
	) AS tr_variation ON {$wpdb->posts}.ID = tr_variation.object_id AND term_taxonomy.taxonomy = tr_variation.taxonomy
	INNER JOIN {$wpdb->terms} AS terms
		ON tr_variation.term_id IS NULL AND term_taxonomy.term_id = terms.term_id
		OR tr_variation.term_id = terms.term_id
	{$main_tax_query_sql['join']} {$meta_query_sql['join']}"; // Not an omission, really no more JOINs required.
```

**Review by ObliviousHarmony — CHANGES_REQUESTED** [review]
Thanks for this @Konamiman, I've left some comments I think we should address.

Regarding the PR itself however I don't think this is the route that we should take. I'm worried that automatically synchronizing the attributes to variations is a little too destructive and might be considered backwards incompatible. Right now (without this PR), when you remove an attribute from a variable product, none of the terms are removed from the variations. This allows you to add back the attribute without needing to restore a backup.

It also appears that the behavior of the widget isn’t exactly the same as without the PR when things are handled correctly, but that may just be a misunderstanding on my part.

From what I can tell it seems like mostly everything other than this widget is resilient to the missing entries and so perhaps we should just correct the count query and leave the rest as it is for now?

File: includes/class-wc-product-variable.php [hunk 4]
```diff
@@ -468,10 +468,17 @@ public function save() {
 		 */
 		do_action( 'woocommerce_before_' . $this->object_type . '_object_save', $this, $this->data_store );
 
-		// Get names before save.
+		// Get names and variation attributes before save.
 		$previous_name = $this->data['name'];
 		$new_name      = $this->get_name( 'edit' );
 
+		if ( $this->get_id() ) {
```
[the remark this answers is not in the document]
Comment (Konamiman) [reply includes/class-wc-product-variable.php:475]: We need to sync empty meta values, because that's what we are using to count "Any" attributes.

File: includes/wc-update-functions.php (hunk 3 above)
Comment (Konamiman) [reply includes/wc-update-functions.php:2252]: But we are using those empty meta values to detect "Any" variations. If we don't ensure that these meta values exist for all variations, the widget won't work properly.

**Review by ObliviousHarmony — APPROVED** [review]
I've tested this out with various product types and it seems to do what it says on the tin! 

One nitpick is that we're now counting variable products using the `post_parent` instead of their own `ID`. This behavior is different than what it was doing before as it was previously considering each in-stock variation in the count. This might lead to strange behavior when combining multiple widgets and I think we should use the `ID` for variations as well.

**Comment by Konamiman** [comment]
> One nitpick is that we're now counting variable products using the post_parent instead of their own ID. This behavior is different than what it was doing before as it was previously considering each in-stock variation in the count. This might lead to strange behavior when combining multiple widgets and I think we should use the ID for variations as well.

Originally it did count variations, but as @rrennick pointed out, that resulted in the widget displaying a number that was higher than the actual amount of products being displayed, which was quite confusing. So it now looks at which variations are supposed to be visible, keeps its parent id, and counts how many different parent ids are in the result; this also blends nicely with the counts for simple products.

File: includes/class-wc-product-variable.php (hunk 4 above)
[the remark this answers is not in the document]
Comment (vedanshujain) [reply includes/class-wc-product-variable.php]: Resolving this because we discussed offline and figured out a way to not need this sync.

File: includes/wc-update-functions.php (hunk 3 above)
Comment (vedanshujain) [reply includes/wc-update-functions.php]: Resolving because we discussed offline and figured out a way to not need this migration.

File: includes/widgets/class-wc-widget-layered-nav.php (hunk 1 above)
Comment (vedanshujain) [reply includes/widgets/class-wc-widget-layered-nav.php:437]: We discussed this offline, and the query suggested by @ObliviousHarmony is currently non-optimized, so going ahead with a different query added in https://github.com/woocommerce/woocommerce/pull/27508/commits/07b62dabbde388d17d9e7e772de4e8b29b10d410

**Review by vedanshujain — CHANGES_REQUESTED** [review]
I have left a comment about splitting the query, I found out a couple more issues but let's tackle them in different PR:
1. Looks like we have introduced performance regressions in `get_available_variations` and then calling it in `is_visible_core` for every product. This makes the whole page slow if there are many products with a large number of variations.
2. I am not sure if using `IF` in select statement and selecting `post_parent` is the best way because we are applying the rest of the checks to post.ID. to explain, if a variable product is marked out of stock, then the variations are still counted and shown if the particular variations are not marked out of stock. This is because the checking is done on the post.ID but we are bubbling up post.post_parent in the SELECT statement.

Let's deal with these two changes later on, but I think we should still split this query into two and run them separately.

**Comment by Konamiman** [comment]
> if a variable product is marked out of stock, then the variations are still counted and shown if the particular variations are not marked out of stock

This is the point of the whole thing. Take in account only variations that are in stock, but in the end, get the main product id so that counters are consistent with the list of products shown (which are always the main products).

E.g. assuming one single product, if two variations are in stock for the same attribute, say "blue-big" and "blue-small", then count only one for "blue". Otherwise we would be displaying a count of 2 but there would be only one product in the displayed list, which would be confusing.

Or am I misunderstanding you?

**Comment by vedanshujain** [comment]
> Take in account only variations that are in stock, but in the end, get the main product id so that counters are consistent with the list of products shown (which are always the main products).

So this becomes inconsistent with the main query when the parent product is out of stock but variations are in stock. Then we will count it in the widget, but main query won't as the product is tagged out of stock. That said, I mentioned that we will deal with this later because currently the only way to repro this scenario is to convert the product into simple, then make it out of stock, and then convert it back to the variable. This is definitely an edge case, let's not block the whole PR for this. (You can also manually add `out_of_stock` term relationship on a variable product to repro).

File: includes/widgets/class-wc-widget-layered-nav.php [hunk 5]
```diff
@@ -425,19 +442,53 @@ protected function get_filtered_term_product_counts( $term_ids, $taxonomy, $quer
...
+
+		$total_counts = null;
+
+		foreach ( $queries as $query ) {
+			$query = "
+				SELECT COUNT(DISTINCT(product_id)) AS term_count, term_count_id FROM (
+					{$query}
+				) AS x GROUP BY term_count_id";
+
+			$results = $wpdb->get_results( $query, ARRAY_A ); // phpcs:ignore WordPress.DB.PreparedSQL.NotPrepared
```
Comment (vedanshujain) [inline includes/widgets/class-wc-widget-layered-nav.php:473]: lets cache here instead of in callee function, so that both the queries can be cached separately

**Review by vedanshujain — APPROVED** [review]
I have left a comment, but pre-approving since its minor. Note that this whole widget needs perf improvements, but I think we can merge it for now.

File: includes/widgets/class-wc-widget-layered-nav.php (hunk 5 above)
Comment (Konamiman) [reply includes/widgets/class-wc-widget-layered-nav.php:473]: Do we really need to cache the queries separately? We have split the original query in two for performance reasons, but conceptually they are still a single one; they will always be used together and with the same set of parameters.

**Comment by jonathansadowski** [comment]
Thanks for the reviews and work to get this in to 4.5

**Comment by Gasper90** [comment]
This is still not working on our side. The filter doesn't show up on the page.

**Comment by Gasper90** [comment]
Ok, because I saw this in the [changelog](https://wordpress.org/plugins/woocommerce/#developers): 

>  * Fix – Filter by attribute widget not working properly for variations having attribute values of “Any…”. #27508

**Comment by jonathansadowski** [comment]
Sorry @Gasper90, I thought I was looking at the revert commit (#27625). You're correct. We originally included this PR in hopes that it would improve things, and have a revert queued for early next week.

**Comment by Gasper90** [comment]
It works now! 👍
