### PR TITLE
Fix extensionCartUpdates not surfacing errors to cart and checkout

### LINKED ISSUE #49724: extensionCartUpdates not surfacing errors without extra error handling
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When an extensionCartUpdate 's server-side callback throws an exception, the error in the exception (and therefore the error in the response) is not shown anywhere on the client. The error is ignored and the request fails silently.

### Expected behavior

The error should be shown on the client in one of the notice areas, ideally if the exception specifies one, it should use that context.

### Actual behavior

The error is ignored and the request fails silently.

### Steps to reproduce

1. Install the Code Snippets extension and add the following snippet:
```php
add_action(
	'woocommerce_blocks_loaded',
	function () {
		woocommerce_store_api_register_update_callback(
			[
				'namespace' => 'debug-test',
				'callback'  => function ( ) {
					throw new Automattic\WooCommerce\StoreApi\Exceptions\RouteException( 'hello_error', 'something.', 400 );
				},
			]
		);
	}
);
```
2. Add something to the cart and proceed to the Cart Blocks page
3. Open the JS console, and paste the following `wc.blocksCheckout.extensionCartUpdate( { namespace: 'debug-test' } )`
4. Verify that no error displays on the frontend. An error notice like the following should be the expected result
image

### WordPress Environment

n/a

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by mikejolley**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

When errors are received using the `receiveError` action, those errors are not surfaced in the UI. This can be tested using some code snippets:

```
add_action(
	'woocommerce_blocks_loaded',
	function () {
		woocommerce_store_api_register_update_callback(
			array(
				'namespace' => 'debug-test',
				'callback'  => function () {
					throw new Automattic\WooCommerce\StoreApi\Exceptions\RouteException( 'hello_error', 'This is an error with contact context.', 400, array( 'context' => 'wc/checkout/contact-information' ) );
				},
			)
		);
	}
);
```

And then running some commands in the console:

```
wc.blocksCheckout.extensionCartUpdate( { namespace: 'debug-test' } )
```

You'll see an uncaught promise error in the console, but nothing in the UI. Extensions need to capture these errors using the returned promise. I've included some basic examples of how to do this.

As for more generic errors, for instance, when a callback does not exist, or if something in the cart errors instead of the callback itself with a `woocommerce_rest_cart_extensions_error` exception, we can capture these and surface them accordingly. This PR however fixes this behaviour. Notices are caught and surfaced using (by default) `wc/cart` notice context, or a context provided in the response.

Screenshot 2024-07-24 at 15 22 37

If you run both of these commands you'll see a notice for the one which has no valid namespace:

```
wc.blocksCheckout.extensionCartUpdate( { namespace: 'debug-test' } )
wc.blocksCheckout.extensionCartUpdate( { namespace: 'debug-test-2' } )
```

Closes #49724

### How to test the changes in this Pull Request:

Developers should test using the snippet + console commands above. Non-developers should smoke test:

1. You can place an order on the block based checkout
2. Test some notices; e.g. apply an invalid coupon and ensure the notice saying the coupon does not exist is shown

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

**Comment by mikejolley** [comment]
@opr @senadir We might need some extra tests? But let me know what you think to this. It surfaces generic/implementation type errors but lets extensions do their own error handling for other error types.

**Review by nielslange — COMMENTED** [review]
Thanks for working on this, @mikejolley. I've successfully tested the testing steps and the code changes look good, but I'd appreciate it if @opr or @senadir could have a second look at the code. 

@opr and @senadir I've requested a review from the two of you. Whoever comes first, feel free to remove the other reviewer.

**Review by opr — CHANGES_REQUESTED** [review]
I think tests would be good for this, I recommend:

- Test that callbacks throwing a `woocommerce_rest_cart_extensions_error` calls `createErrorNotice` on the `core/notices` data store
- Test that any other errors trigger some code in the catch block

It still feels a little wrong to me that any other error is not shown, e.g. a filter returning invalid data:

```php
add_filter( 'woocommerce_countries', function ( $countries ) {
	return null;
} );
```

would not show any notices, but we agreed it's hard to know the cause of the error.

The code looks and works OK, but I think we should add the tests.

**Comment by mikejolley** [comment]
I added tests for the caught and uncaught exceptions. Found an error when doing so; we resolved to `false` instead of throwing the error.

File: plugins/woocommerce-blocks/assets/js/data/cart/notify-errors.ts [hunk 1]
```diff
@@ -7,27 +7,50 @@ import { decodeEntities } from '@wordpress/html-entities';
 import { dispatch } from '@wordpress/data';
 
 /**
- * This function is used to notify the user of cart item errors/conflicts
+ * This function is used to normalize errors into an array of ApiErrorResponse objects.
+ */
+const filterValidErrors = ( errors: ApiErrorResponse | ApiErrorResponse[] ) => {
```
Comment (opr) [inline plugins/woocommerce-blocks/assets/js/data/cart/notify-errors.ts]: I think a bit more info on what the two ternary cases are doing here would be good. e.g. when is `errors` _not_ going to be an `ApiErrorResponse`, and in that case why would we filtering it normalize the errors? Is it because `errors` can be an array of responses, but not all of them will be errors?

**Review by opr — APPROVED** [review]
Thanks Mike, I reviewed the functionality and it's working well. The code looks good but I think clarification in the one place I commented would be useful. Feel free to merge after updating the comment. Cheers 🍻

File: plugins/woocommerce-blocks/assets/js/data/cart/notify-errors.ts (hunk 1 above)
Comment (mikejolley) [reply plugins/woocommerce-blocks/assets/js/data/cart/notify-errors.ts]: It's because sometimes you receive a single error, other times you receive an array of errors. It depends on the route e.g. cart errors are an array, but an endpoint returning 402 is a single error. This just normalises it to an array and ensures each error has valid/expected properties. I can document in the doc block.

Comment (mikejolley) [reply plugins/woocommerce-blocks/assets/js/data/cart/notify-errors.ts]: Saying that, current usage seems to only use this for cart so maybe I can remove it. Ill try that and check tests continue to pass.
