### PR TITLE
Make sure Add to Cart button state updates when changing variations in the Add to Cart + Options block

### LINKED ISSUE #59117: Add to Cart with Options: Button appears "disabled" for variation products
Button appears "disabled" for variation products but it isn't really:

* when no attributes are chosen it's still interactive so the error is displayed when clicked
* when attributes are chosen it's still appear as "disabled" (gray on hover and cursor not-allowed) but it's interactive and product can be added to cart

**Steps to reproduce:**

1. Use Add to Cart with Options (Beta) in Single Product template
2. Go to frontend of **variable** product
3. Without choosing any attributes, hover on add to cart - it appears disabled but is still interactive
4. Click it

Expected: it should not be clickable

Actual: it is clickable and error is displayed that product cannot be added upon page refresh

5. Choose attributes
6. Hover on add to cart and click it

Expected: it should just be clickable

Actual: is appears as "disabled" (gray on hover and cursor not-allowed) but should not

[disabledcursor.mov](https://uploads.linear.app/f629fcde-6f9b-48e8-8af3-60eed8823bff/86d45f42-b0c7-4e2a-81bb-f76f3ec63edc/48b2f3e0-2698-4ef7-898b-89ddba090d66?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2Y2MjlmY2RlLTZmOWItNDhlOC04YWYzLTYwZWVkODgyM2JmZi84NmQ0NWY0Mi1iMGM3LTRlMmEtODFiYi1mNzZmM2VjNjNlZGMvNDhiMmYzZTAtMjY5OC00ZWY3LTg5OGItODlkZGJhMDkwZDY2IiwiaWF0IjoxNzUwNzY4NjYxLCJleHAiOjMzMzIxMzI4NjYxfQ.DH-UAXr0Yg4M9Yj6TV76e-lEKonCvQyGwasic4HlA9w)

### PR DESCRIPTION
**Pull request by Aljullu**
### Changes proposed in this Pull Request:

Closes #59117.

Closes WOOPLUG-4757.

This PR is divided in two commits:

* f54fd4931ef733df892feedfdebf5b1d5c5361bd makes it so `isFormValid` state doesn't depend on `variationId` state. For some reason, it was working in Firefox but not in Chrome. There is probably a better way to improve this, but it's likely we will refactor these stores in the future (moving data to global or upper stores) so for now it's an interim solution.
* c346b57ae64ea6f27ce157b25f9894a4a819a037 includes some clean up related to the Interactivity API, I commented it inline below.

#### Preparation

1. Go to *Appearance* > *Editor* > *Templates* > *Single Product*.
2. Click on the *Add to Cart with Options* block and update to the blockified version.

#### Reproducing the issue

1. Go to a variable product page.
2. Select the attributes and hover the Add to Cart button.
3. Verify the cursor is not `not-allowed`.

Before | After
--- | ---
imatge | imatge

### CODE REVIEW

File: plugins/woocommerce/client/blocks/assets/js/blocks/add-to-cart-with-options/frontend.ts [hunk 1]
```diff
@@ -18,7 +18,6 @@ export type Context = {
 	productId: number;
 	productType: string;
 	selectedAttributes: CartVariationItem[];
-	variationId: number | null;
```
Comment (Aljullu) [inline plugins/woocommerce/client/blocks/assets/js/blocks/add-to-cart-with-options/frontend.ts:21]: `variationId` is part of the state, not the context, so it shouldn't be here.

File: plugins/woocommerce/src/Blocks/BlockTypes/AddToCartWithOptions/AddToCartWithOptions.php [hunk 2]
```diff
@@ -187,7 +187,14 @@ protected function render( $attributes, $content, $block ) {
...
 				array(
-					'isFormValid' => ! $product->is_type( 'variable' ),
+					'isFormValid' => function () {
+						$context = wp_interactivity_get_context();
+						$product = wc_get_product( $context['productId'] );
+						if ( $product instanceof \WC_Product && $product->is_type( 'variable' ) ) {
+							return false;
+						}
+						return true;
+					},
```
Comment (Aljullu) [inline plugins/woocommerce/src/Blocks/BlockTypes/AddToCartWithOptions/AddToCartWithOptions.php:197]: This value depends on the context, so it should be initialized based on the `productId`.

File: plugins/woocommerce/src/Blocks/BlockTypes/AddToCartWithOptions/AddToCartWithOptions.php [hunk 3]
```diff
@@ -464,7 +471,6 @@ function ( $variation ) {
 					<input type="hidden" name="product_id" value="' . esc_attr( $product_id ) . '" />
 					<input type="hidden"
 						name="variation_id"
-						data-wp-interactive="woocommerce/add-to-cart-with-options"
```
Comment (Aljullu) [inline plugins/woocommerce/src/Blocks/BlockTypes/AddToCartWithOptions/AddToCartWithOptions.php:467]: This element is already inside the `woocommerce/add-to-cart-with-options` store, so there is no need to declare it here too.

**Review by kmanijak — APPROVED** [review]
Tested the PR and form validation works as expected in Chrome:
- `not-allowed` cursor appears when attribute are not chosen completely
- regular cursor appears when attributes are chosen.
