### PR TITLE
Fix wrong type passed to `add_meta_boxes` action

### LINKED ISSUE #41579: With HPOS, WooCommerce fires add_meta_boxes, but doesn't provide a WP_Post, leading to PHP Notice
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Hello Woocommerce!

I would like to report a case of `doing it wrong` in a recent patch, which might lead to PHP notice on any third party plugin that try to add a meta box.

The issue come from this line added in a recent update of Woocommerce:

```php
do_action( 'add_meta_boxes', $this->screen_id, $this->order );
```

In the file [/woocommerce/src/Internal/Admin/Orders/Edit.php:159](https://github.com/woocommerce/woocommerce/blob/6fb787e954af29605d793c6cbb35c558d6e1d737/plugins/woocommerce/src/Internal/Admin/Orders/Edit.php#L159)

Woocommerce fires the native [`add_meta_boxes`](https://developer.wordpress.org/reference/hooks/add_meta_boxes/) hook, but instead of filling arguments with the `WP_Post`, it uses a custom `WC_Order` object.

The [WP documentation](https://developer.wordpress.org/reference/hooks/add_meta_boxes/) explicitly requires a `$post_type` as first argument and a `WP_Post` as second argument.

This code will produce a notice on any third party plugin that use `add_meta_boxes` to add meta box, expecting a `WP_Post` as the second argument and trying to access `$post->ID` for example.

`WP_Post` allows to access the `ID` property directly, but not `WC_Order`, so it will produce a notice.

The issue can be reproduced using this code in the theme's `functions.php` file:

```php
add_action('add_meta_boxes', 'my_add_meta_boxes', 10, 2);
function my_add_meta_boxes($post_type, $post){
    $post_id = $post->ID;
}
```

Then head over an order details in the WP Admin, and the following notice show up:

```
Function ID was called incorrectly. Order properties should not be accessed directly. Backtrace: do_action('load-woocommerce_page_wc-orders'), WP_Hook->do_action, WP_Hook->apply_filters, Automattic\WooCommerce\Internal\Admin\Orders\PageController->__call, call_user_func_array, Automattic\WooCommerce\Internal\Admin\Orders\PageController->handle_load_page_action, Automattic\WooCommerce\Internal\Admin\Orders\PageController->setup_action_new_order, Automattic\WooCommerce\Internal\Admin\Orders\PageController->prepare_order_edit_form, Automattic\WooCommerce\Internal\Admin\Orders\Edit->setup, do_action('add_meta_boxes'), WP_Hook->do_action
```

Thanks!

Regards.

### Expected behavior

Provide a valid `WP_Post` as second argument of `add_meta_boxes`, following the [WP documentation](https://developer.wordpress.org/reference/hooks/add_meta_boxes/) specifications.

### Actual behavior

Provide a `WC_Order` as second argument of `add_meta_boxes`.

### Steps to reproduce

The issue can be reproduced using this code in the theme's `functions.php` file:

```php
add_action('add_meta_boxes', 'my_add_meta_boxes', 10, 2);
function my_add_meta_boxes($post_type, $post){
    $post_id = $post->ID;
}
```

Then head over an order details in the WP Admin.

### WordPress Environment ###

WordPress address (URL): https://www.wordpress.dev/
Site address (URL): https://www.wordpress.dev/
WC Version: 8.3.0
REST API Version: ✔ 8.3.0
WC Blocks Version: ✔ 11.4.8
Action Scheduler Version: ✔ 3.6.4
Log Directory Writable: ✔
WP Version: 6.4.1
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.35 (Win64) OpenSSL/1.1.1h PHP/7.4.12
PHP Version: 7.4.12
PHP Post Max Size: 2 GB
PHP Time Limit: 36000
PHP Max Input Vars: 1000
cURL Version: 7.70.0
OpenSSL/1.1.1h

SUHOSIN Installed: –
MySQL Version: 5.7.24
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.3.0
WC Database Prefix: wp_
Total Database Size: 11.01MB
Database Data Size: 7.92MB
Database Index Size: 3.09MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_3_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_3_comments: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_3_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_3_options: Data: 1.52MB + Index: 0.03MB + Engine InnoDB
wp_3_postmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_3_posts: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_3_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_3_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_3_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_3_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_blogmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_blogs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_e_events: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_e_submissions: Data: 0.02MB + Index: 0.23MB + Engine InnoDB
wp_e_submissions_actions_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_e_submissions_values: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_fea_submissions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gf_draft_submissions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_gf_entry: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gf_entry_meta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_gf_entry_notes: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gf_form: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gf_form_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gf_form_revisions: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gf_form_view: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_icl_background_task: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_content_status: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_core_status: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_languages: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_icl_languages_translations: Data: 0.20MB + Index: 0.17MB + Engine InnoDB
wp_icl_locale_map: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_message_status: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_icl_mo_files_domains: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_node: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_reminders: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_strings: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_icl_string_batches: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_string_packages: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_string_pages: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_icl_string_positions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_string_status: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_string_translations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_string_urls: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_translate: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_translate_job: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_translations: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_icl_translation_batches: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_translation_downloads: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_translation_status: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 4.02MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_posts: Data: 0.08MB + Index: 0.06MB + Engine InnoDB
wp_registration_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_signups: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_site: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_sitemeta: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

admin_form: 1
af_entry: 2
af_form: 1
attachment: 9
elementor_library: 1
event: 1
oembed_cache: 2
page: 5
polylang_mo: 2
post: 1
product: 1
project: 2
project-person: 2
revision: 18
wp_global_styles: 3
wp_navigation: 1
wp_template: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 8.3.0

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### WC Pages ###

Shop base: ❌ Page ID is set
but the page does not exist

Cart: ❌ Page ID is set
but the page does not exist

Checkout: ❌ Page ID is set
but the page does not exist

My account: ❌ Page ID is set
but the page does not exist

Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty-Four
Version: 1.0
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ❌ Not declared

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: customize-store
minified-js
new-product-management-experience
product-virtual-downloadable
product-external-affiliate
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2023-11-21 13:42:25 +01:00
Options: ✔
Notes: 101
Onboarding: skipped

### Action Scheduler ###

Complete: 6
Oldest: 2023-11-20 14:42:26 +0100
Newest: 2023-11-20 14:43:31 +0100

Pending: 1
Oldest: 2023-11-21 14:42:26 +0100
Newest: 2023-11-21 14:42:26 +0100

### Status report information ###

Generated at: 2023-11-20 14:43:36 +01:00

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by amiut**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:
This PR fixes an issue reported in #41579 where a `TypeError` is thrown in order edit pages because a wrong type is passed to `add_meta_boxes` and `add_meta_boxes_{screen}` actions in the following file:
[src/Internal/Admin/Orders/Edit.php (lines 165 and 175)](https://github.com/woocommerce/woocommerce/blob/35ba49a1f29bad8a1685ae4a179c7273eee3f298/plugins/woocommerce/src/Internal/Admin/Orders/Edit.php#L165-L175)

The TypeError indicates that the passed parameter must be an instance of `WP_Post`, but instance of `Automattic\WooCommerce\Admin\Overrides\Order` given

The issue is reproducible by a code snippet like this:
```PHP
add_action(
	'add_meta_boxes',
	function (string $postType, \WP_Post $post) {
		// Add a metabox
	},
	10,
	2
);
```
It breaks the order edit page with an fatal uncaught TypeError.
The HPOS system stores an order placeholder entry in the `posts` table with the same ID ([source](https://github.com/woocommerce/woocommerce/blob/35ba49a1f29bad8a1685ae4a179c7273eee3f298/docs/high-performance-order-storage/README.md#placeholder-records)), the fix tries to fetch a `WP_Post` object from a given order id and pass it where a `WP_Post` object is expected.

Closes #41579 .

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Add a test metabox, using this example snippet in your theme's functions.php or within a mu-plugin:
```PHP
add_action(
	'add_meta_boxes',
	function (string $postType, \WP_Post $post) {
		add_meta_box(
			'foo_bar_baz',
			'Foo',
			function (WP_Post $post): void {
				echo 'Test';
			},
			null,
			'advanced',
			'high',
		);
	},
	10,
	2
);
```
2. Submit an order.
3. Go to WooCommerce > Orders and edit the newly submitted order.
4. You should not face a fatal error and the order edit page should correctly load.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce/src/Internal/Admin/Orders/Edit.php [hunk 1]
```diff
@@ -155,24 +156,28 @@ public function setup( \WC_Order $order ) {
...
-		/**
-		 * Provides an opportunity to inject custom meta boxes into the order editor screen. This
-		 * hook is an analog of `add_meta_boxes_<POST_TYPE>` as provided by WordPress core.
-		 *
-		 * @since 7.4.0
-		 *
-		 * @param WC_Order $order The order being edited.
-		 */
-		do_action( 'add_meta_boxes_' . $this->screen_id, $this->order );
+		if ( $order_post instanceof WP_Post ) {
```
Comment (barryhughes) [inline plugins/woocommerce/src/Internal/Admin/Orders/Edit.php:161]: Thanks for submitting this. 

We'll discuss it, but I don't think we can accept the PR in its current form because, in reality and given we're inside the HPOS order editor code, I don't think this check would ever be satisfied. 

Though I understand the problem it seeks to solve, this will cause a different set of breakages and back-compat problems that your testing instructions don't cover (for example, WooCommerce extensions that anticipate the current behavior and rely on it to integrate with the order editor).

Comment (amiut) [reply plugins/woocommerce/src/Internal/Admin/Orders/Edit.php:161]: Hi @barryhughes, Thank you for your reply.

> I don't think this check would ever be satisfied.

It actually does satisfy, the reason is that even with HPOS, a placeholder entry is created in the `wp_posts` table (please [see here](https://github.com/woocommerce/woocommerce/blob/35ba49a1f29bad8a1685ae4a179c7273eee3f298/docs/high-performance-order-storage/README.md#placeholder-records)).

> Though I understand the problem it seeks to solve, this will cause a different set of breakages and back-compat problems that your testing instructions don't cover (for example, WooCommerce extensions that anticipate the current behavior and rely on it to integrate with the order editor).

I understand your concern about other plugins using the same hook, but objects of `Order` are unexpected as second parameter of `add_meta_boxes` hook, according to the [hook reference](https://developer.wordpress.org/reference/hooks/add_meta_boxes/).

So even for the "WooCommerce extensions that anticipate the current behavior" this issue will cause a fatal error as soon as they use a native type hint (because other WordPress metaboxes are passing `WP_Post` but the 3rd party extension is expecting `Order` object in it's hook callback).

Comment (barryhughes) [reply plugins/woocommerce/src/Internal/Admin/Orders/Edit.php:161]: > It actually does satisfy

Yes, you're right.

File: plugins/woocommerce/src/Internal/Admin/Orders/Edit.php [hunk 2]
```diff
@@ -155,24 +156,28 @@ public function setup( \WC_Order $order ) {
...
+			/**
+			 * Provides an opportunity to inject custom meta boxes into the order editor screen. This
+			 * hook is an analog of `add_meta_boxes_<POST_TYPE>` as provided by WordPress core.
+			 *
+			 * @since 7.4.0
+			 *
+			 * @param WP_Post $order_post The order being edited.
+			 */
+			do_action( 'add_meta_boxes_' . $this->screen_id, $order_post );
+		}
```
Comment (barryhughes) [inline plugins/woocommerce/src/Internal/Admin/Orders/Edit.php:180]: Thanks for your patience, @amiut. This section all seems reasonable, but we think it makes sense to also add a new action *outside* of this block, that passes the order object. For example, `woocommerce_order_editor_add_meta_boxes`.

File: plugins/woocommerce/src/Internal/Admin/Orders/Edit.php [hunk 3]
```diff
@@ -492,14 +497,17 @@ class="metabox-holder columns-<?php echo ( 1 === get_current_screen()->get_colum
...
 		<div id="postbox-container-1" class="postbox-container">
 			<?php do_meta_boxes( $this->screen_id, 'side', $this->order ); ?>
 		</div>
 		<div id="postbox-container-2" class="postbox-container">
 			<?php
-			do_meta_boxes( $this->screen_id, 'normal', $this->order );
-			do_meta_boxes( $this->screen_id, 'advanced', $this->order );
+			if ( $order_post instanceof WP_Post ) {
+				do_meta_boxes( $this->screen_id, 'normal', $order_post );
+				do_meta_boxes( $this->screen_id, 'advanced', $order_post );
```
Comment (barryhughes) [inline plugins/woocommerce/src/Internal/Admin/Orders/Edit.php]: The risk seems different here, and the third parameter (in a call made to `do_meta_boxes`) is the `$data_object`, which is not necessarily a `WP_Post`. Does this section make as much sense?

File: plugins/woocommerce/src/Internal/Admin/Orders/Edit.php (hunk 2 above)
Comment (amiut) [reply plugins/woocommerce/src/Internal/Admin/Orders/Edit.php:180]: Hello @barryhughes, thank you very much for your review.
Yes, that makes total sense to me.

I wanted to add below action after Line 180, but after checking other occurrences I realised they all have a `@since` in their docblock, should I add it here or is it ok to disregard `@since`? and what should version should it be if it's needed?

```PHP
/**
 * Provides an opportunity to inject custom meta boxes into the order editor screen.
 *
 * @param WC_Order $order The order being edited.
 */
do_action( 'woocommerce_order_editor_add_meta_boxes', $this->order );
```

File: plugins/woocommerce/src/Internal/Admin/Orders/Edit.php (hunk 3 above)
Comment (amiut) [reply plugins/woocommerce/src/Internal/Admin/Orders/Edit.php]: You are absolutely right, In My tests I have used `WP_Post` as the metabox callback parameter, but that's wrong, sorry for that. I reverted the change in here.

File: plugins/woocommerce/src/Internal/Admin/Orders/Edit.php (hunk 2 above)
Comment (barryhughes) [reply plugins/woocommerce/src/Internal/Admin/Orders/Edit.php:180]: I believe `@since` is needed to pass linting (which is a required CI check). We can set it to `9.5.0`.

Comment (amiut) [reply plugins/woocommerce/src/Internal/Admin/Orders/Edit.php:180]: Thank you, I added the hook.

**Review by barryhughes — APPROVED** [review]
Thank you, @amiut!

**Comment by barryhughes** [comment]
Thanks for fixing the changelog correction: all required checks are now passing, so will go ahead and merge.
