### PR TITLE
Do not call login if user is already logged in

### LINKED ISSUE #34127: First Login for New User Always Fails With No Error Messages
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

1. New user is created during checkout
2. User gets a link in email to set their password
3. User follows link and sets new password
4. User is taken to the login page with message “Your password has been reset successfully.”
5. User enters email and password, clicks “Login” – nothing happens. The password field is cleared and no errors of any kind are displayed.
6. User enters email and same password again – login successful.

This is consistent with every new account. All subsequent login attempts are fine. Logins after “forgot password” reset are also fine.
The issue is only with the very first login for a new account.

If an account is registered though WordPress, then first login through WooCommerce is successful.
It appears that this only affects accounts created during WooCommerce checkout.

WordPress 6.0.1. All plugins except woocommerce disabled. Storefront theme.No custom CSS, no custom PHP.

This happens because the customer is already logged in so on the first attempt WooCommerce logs the customer out and then lets them log them back in. If the user logs out before setting the password, then the first login works fine. 

I think woocommerce just needs to somehow improve the user experience, because all new users will be logged in once they create an account during checkout. Then they’ll get the email, click on the link, and be taken to the site where they’re already logged in. May be the password reset page can automatically terminate the current logged in session?

### Expected behavior

Successful login first time after password reset. 

### Actual behavior

First Login for New User Always Fails With No Error Messages

### Steps to reproduce

1. New user is created during checkout
2. User gets a link in email to set their password
3. User follows link and sets new password
4. User is taken to the login page with message “Your password has been reset successfully.”
5. User enters email and password, clicks “Login” – nothing happens. The password field is cleared and no errors of any kind are displayed.
6. User enters email and same password again – login successful.

### WordPress Environment

WordPress 6.0.1. All plugins except woocommerce disabled. Storefront theme.No custom CSS, no custom PHP.

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by alexiglesias31**
### Submission Review Guidelines:

- I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
- I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
- I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/). 
- Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Prevent to call to login function if the user is already logged in.

Closes #34127.

### How to test the changes in this Pull Request:

1. New user is created during checkout.
2. User gets a link in email to set their password.
3. User follows link and sets new password.
4. User is taken to the login page with message “Your password has been reset successfully.”
5. User enters email and password, clicks “Login”. The login operation should be successful at the first try.

### CODE REVIEW

**Comment by rrennick** [comment]
@alexiglesias31 Thanks for taking on this issue. I tested this PR in an incognito window and the behaviour was the same as in `trunk`. I did not dig through the code but noticed that the `password-reset` query string was still on the URL after completing log in. I suspect that the query string might be overriding the after login redirect vs it being an issue with the user being already logged in.

**Comment by alexiglesias31** [comment]
Hey @rrennick, thanks for your feedback, I will update properly and tag you for a new revision when this be done :+1:

**Comment by alexiglesias31** [comment]
Hello @rrennick, after another round of debugging I found that the `password-reset` arg is not the actual cause of the problem.

The issue is caused because the function `process_login()` is executed more than once when an user submits the login form, causing that nonce verification fails.
By doing the result of the verification static we can avoid this issue and achieve the expected behavior.

Please let me know if you need me to elaborate a bit more on this and if there is any other feedback.

Thanks for reviewing this.

File: plugins/woocommerce/includes/class-wc-form-handler.php [hunk 1]
```diff
@@ -929,10 +929,17 @@ private static function add_to_cart_handler_variable( $product_id ) {
 	 * @throws Exception On login error.
 	 */
 	public static function process_login() {
+
+		static $valid_nonce;
```
Comment (rrennick) [inline plugins/woocommerce/includes/class-wc-form-handler.php]:
```suggestion
		static $valid_nonce = null;
```

File: plugins/woocommerce/includes/class-wc-form-handler.php [hunk 2]
```diff
@@ -929,10 +929,17 @@ private static function add_to_cart_handler_variable( $product_id ) {
...
+
 		// The global form-login.php template used `_wpnonce` in template versions < 3.3.0.
 		$nonce_value = wc_get_var( $_REQUEST['woocommerce-login-nonce'], wc_get_var( $_REQUEST['_wpnonce'], '' ) ); // @codingStandardsIgnoreLine.
 
-		if ( isset( $_POST['login'], $_POST['username'], $_POST['password'] ) && wp_verify_nonce( $nonce_value, 'woocommerce-login' ) ) {
+		if ( ! empty( $nonce_value ) ) {
```
Comment (rrennick) [inline plugins/woocommerce/includes/class-wc-form-handler.php]: If you moved this to above line 936 you could change it to

```suggestion
		if ( null === $valid_nonce ) {
```

This would ensure the nonce logic only ran once.

**Review by rrennick — CHANGES_REQUESTED** [review]
@alexiglesias31 Thanks for the follow up. This tested great for me. I just had the two suggestions.

**Comment by alexiglesias31** [comment]
Thanks for the suggestion @rrennick. I just pushed the amends from your CR.

**Review by rrennick — APPROVED** [review]
@alexiglesias31 Thanks for the help.
