### PR TITLE
Fix fulfillments UI design issues found in design review

### LINKED ISSUE #58715: [Order fulfillments] Post-MVP: Review design problems
We need to consult with the design team before shipping the project, to reach to an agreement about applied design versus design in Figma. It seems like Figma design has the specifications of Calpyso, but the applied design uses WP specs.

### PR DESCRIPTION
**Pull request by tpaksu**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

This PR contains UI fixes surfaced in https://linear.app/a8c/issue/WOOPLUG-4575/order-fulfillments-post-mvp-review-design-problems. The details of the UI inconsistencies can be found in the testing instructions below.

Closes #58715 WOOPLUG-4575

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

#### 🛠️ Preparation 

1. Checkout this branch
2. Run `npm run watch:build` to rebuild the assets
3. Create an order if you don't have one, containing multiple quantities of some items
4. Go to WooCommerce > Orders page, and open the fulfillments drawer by clicking the pen icon in the fulfillment status column. 

> [!Note]
> If you are testing this after the feature flag implementation is already merged, you need to enable the fulfillments feature with setting `woocommerce_feature_fulfillments_enabled` option to `yes`

#### 🧪 Testing chevron direction change on expandable items

The chevron on collapsed items should point downwards, and upwards when expanded.

#### Testing bulk selection link removals

The _Select all_ and _Clear selection_ links should be removed, as the checkbox does the same thing, and the "X Selected" label should be visible in all cases, including "0 selected" label.

#### 🧪 Testing accordion feature of fulfillment drawer

All the accordion items should be collapsable when clicked to its title, including "Pending items", "Order Items", and all "Fulfillment X", one open at a time. Before, the Pending Items accordion wasn't collapsing when clicked to its title, and was expanding pending items when a saved fulfillment was collapsed. Now it'll work like an accordion (no priorities).

#### 🧪 Testing error message visibility

You need a list of many items for this, or you can reduce the height of your browser to make your bulk actions part of the items list not visible when scrolled down to the buttons. Deselect all items, click to "Save draft" while the error label isn't in the viewport, you should see the drawer contents scroll up when an error pops.

#### 🧪 Testing "Other" option being always visible, and sticked to bottom

The shipping providers combo box on manual shipping information entry form now should show the "Other" option as a sticky, always visible on bottom item when the dropdown is shown.

#### 🧪 Testing accordion when there's one item in it

When there's only one item in the accordion, it shouldn't act like an accordion, e.g. no chevron shown, no collapsing when clicked on the title.

#### 🧪 Testing immediate order fulfillment status updates

When there's a change in the order fulfillment status after these actions: 

- Fulfillment created
- Fulfillment deleted
- Fulfillment fulfilled

Which may result in the order fulfillment status having these switches

- Fulfilled
- Unfulfilled
- Partially fulfilled
- No fulfillments

And they should immediately be reflected on the UI when something changes the status in the drawer.

#### 🧪 Testing mobile scroll of fulfillments drawer in order details page also scrolling the whole page

1. Go to the order with many items
2. Open Chrome dev tools
3. Click the mobile view switch on top left corner
4. Scroll down to order details box
5. Open the fulfillment drawer by clicking the pen near the fulfillment status badge
6. Scroll the drawer, it should only scroll inside the drawer, there shouldn't be a scroll on the document beneath it
7. Create a fulfillment with only one item in it
8. Expand the fulfillment by clicking its title
9. It shouldn't cover the full page (e.g. no scroll offset on the drawer)
10. Try to scroll the page
11. It shouldn't scroll the page beneath it. 
12. When you close the drawer, you should see the part of the page where you opened it
13. The page should continue to scroll normally when the drawer is closed

#### 🧪 Testing the errors of an order is showing on another order

Before this PR, for example, when you unselected all items on the order, and clicked to "Save as draft", an error showed, which was normal, but when you switched to another order, the error continued to display on the new order too. This PR should've fixed it. 

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [x] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 
This PR is a part of a feature that only will have one changelog entry. Because of that, sub PR's of the feature branch doesn't need one.
</details>

### CODE REVIEW

File: plugins/woocommerce/client/admin/client/wp-admin-scripts/fulfillments/utils/fulfillment-utils.ts [hunk 1]
```diff
@@ -28,6 +35,67 @@ export function getFulfillmentItems(
...
+			const status = window.wcFulfillmentSettings
+				.order_fulfillment_statuses[ order_status ] || {
+				label: __( 'Unknown', 'woocommerce' ),
+				background_color: '#f8f9fa',
+				text_color: '#6c757d',
+			};
+			// Set content of the marker to the label of the status.
+			const textContainer = marker.querySelector( 'span' );
+			if ( textContainer ) {
+				textContainer.textContent = status.label;
```
Comment (Ferdev) [inline plugins/woocommerce/client/admin/client/wp-admin-scripts/fulfillments/utils/fulfillment-utils.ts:83]: should we sanitize `status.label`?

Comment (tpaksu) [reply plugins/woocommerce/client/admin/client/wp-admin-scripts/fulfillments/utils/fulfillment-utils.ts:83]: Does it have a chance to be misused? We don't send back the value, and it is coming from the server as sanitized. If someone alters it, it will stay on their browser.

File: plugins/woocommerce/client/admin/client/wp-admin-scripts/fulfillments/index.tsx [hunk 2]
```diff
@@ -43,8 +46,14 @@ function FulfillmentsController() {
...
 				}
 			}
-		} );
-	}, [] ); // eslint-disable-line react-hooks/exhaustive-deps
+		};
+
+		document.body.addEventListener( 'click', handleClick );
+
+		return () => {
+			document.body.removeEventListener( 'click', handleClick );
```
Comment (Ferdev) [inline plugins/woocommerce/client/admin/client/wp-admin-scripts/fulfillments/index.tsx:54]: `selectOrderRow` depends on `deselectOrderRow`... I wonder if you have experienced multiple registrations of the `click` event without removing previous registratations. I'm concerned the app could get more registrations of the event than deregistrations of it.

Comment (tpaksu) [reply plugins/woocommerce/client/admin/client/wp-admin-scripts/fulfillments/index.tsx:54]: The page is not a React page, it's a PHP rendered WP_List_Table, and every pagination change re-renders the full page, the event deregistration possibly never runs. The event registration is listening for click events on the body element, registering once per page load (not every render of the fulfillments drawer, it's running on the entry point of the script, which isn't bound to any react component), and checks if there are any `.fulfillments-trigger` element in the ascendants or descendants of the clicked element, then runs the code according to it. How can it register more than it's deregistered?

**Review by Ferdev — APPROVED** [review]
Working as expected! Great job, Taha! Left a couple of nitpicks, this is good to go!
