### PR TITLE
[COT] Fix editor trash link

### LINKED ISSUE #34375: [COT] "Move to Trash" in individual orders does not work
The following link still points to the posts implementation and doesn't do anything when COT is authoritative:

### PR DESCRIPTION
**Pull request by barryhughes**
The *"Move to Trash"* link in the COT-powered order editor should work as expected.

move-to-trash

Closes #34375.

### How to test the changes in this Pull Request:

Use the settings found in **WooCommerce ⏵ Settings ⏵ Advanced ⏵ Custom Data Stores** to test this once with custom order tables as the authoritative data-store, and then repeat with the posts table (to ensure nothing has inadverently broken there).

1. Edit an order.
2. Use the move-to-trash link.
3. The order should be trashed, and you should be returned to the orders list table.

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

**Comment by barryhughes** [comment]
Ready for review/testing!

File: plugins/woocommerce/includes/admin/meta-boxes/class-wc-meta-box-order-actions.php [hunk 1]
```diff
@@ -88,6 +88,31 @@ public static function output( $post ) {
...
+	 *
+	 * @return string
+	 */
+	private static function get_trash_or_delete_order_link( int $order_id ): string {
+		if ( OrderUtil::custom_orders_table_usage_is_enabled() ) {
+			$order_list_url  = admin_url( 'admin.php?page=wc-orders' );
+			$trash_order_url = add_query_arg(
+				array(
+					'action'           => 'trash',
+					'order'            => array( $order_id ),
```
Comment (jorgeatorres) [inline plugins/woocommerce/includes/admin/meta-boxes/class-wc-meta-box-order-actions.php:104]: Not that I'm reviewing this PR but was taking a quick look in relation with #34229 and noticed we're using `id` instead of `order` for the edit page (e.g. `admin.php?page=wc-orders&id=5894&action=edit`). Shouldn't we do the same here?

Comment (barryhughes) [reply plugins/woocommerce/includes/admin/meta-boxes/class-wc-meta-box-order-actions.php:104]: It works because the checkbox column (in the list table) uses `order[]` and that is also what the bulk action handler looks for. Perhaps it would be nice to change things so that we have greater consistency† ... whether we should consolidate on `id` or `order`, though, I'm less sure. Here's a take on that, though:

- The work to [introduce the new list table](https://github.com/woocommerce/woocommerce/pull/32864) was completed before the new editor screen was worked upon.
- When that initial work was done, we picked `order` and `orders` as the singular and plural object names.
- This felt like a good analog for the CPT list table, where `post` is used (instead of `ID`).

† *Consistency is good, generally, but I'd also note in the case of taxonomy list tables WordPress uses `tag_ID` for the edit links and `delete_tags[]` for bulk actions, so what we currently have here isn't so unusual.*

What are your thoughts? I don't personally lean very strongly in either direction, but am happy to make a change if a change is desired 🙃

Comment (jorgeatorres) [reply plugins/woocommerce/includes/admin/meta-boxes/class-wc-meta-box-order-actions.php:104]: Yeah. I get where this is coming from, just thought it was "funny" that we're using different names (CPT at least "consistently" uses `post`).

> What are your thoughts? I don't personally lean very strongly in either direction.

I don't either, though I tend to prefer "order". Maybe this is something we can decide later or add some support for re-mapping some of the args in a given context (for example, translate `?action=trash&id=1` to `?action=trash&order[]=1`).

In the mean time, I've used the same approach as here for #34229.

Comment (jorgeatorres) [reply plugins/woocommerce/includes/admin/meta-boxes/class-wc-meta-box-order-actions.php:104]: ... which, as luck would have it, was assigned to you for review 😅.

Comment (barryhughes) [reply plugins/woocommerce/includes/admin/meta-boxes/class-wc-meta-box-order-actions.php:104]: 🙇🏽 

Cool; we definitely have some time before things are really 'locked down' to revise areas like this.

Comment (barryhughes) [reply plugins/woocommerce/includes/admin/meta-boxes/class-wc-meta-box-order-actions.php:104]: <facepalm> On further reflection, I guess `order` as a query arg is not ideal, as it has a lot of potential for confusion with the query arg used for ordering direction (asc, desc).

I'll create a PR to address this, probably after #34229 is merged to avoid unnecessary work there.

**Review by Konamiman — APPROVED** [review]
