### PR TITLE
7day should start from midnight, not current time

### LINKED ISSUE #15870: First day results in Last 7 Day report keeps changing as new orders received
## Prerequisites

- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of WooCommerce
- [x ] This is not a usage question (Those should be directed to the [community](https://wordpress.org/support/plugin/woocommerce), unless this is a question about a premium plugin in which you should [use the helpdesk](https://woocommerce.com/my-account/tickets/) for official extensions or contact the author of 3rd party extensions)
- [x ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1.  As orders come in throughout the day, just refresh the Last 7 Day report
2.
3.

## Expected behavior and actual behavior
The first day of the last 7 day report should always remain constant since it reflects sales from 6 days ago so results should never change.  However, we see variation in the first day results as additional orders are received.  When running a custom date range report on the same 7 day period, day 1 results are shown correctly but the 7 Day report has day 1 results incorrectly.   I have attached pictures of the graph using the custom date range, and pictures of the 7 Day report throughout the day.  One would expect the 7th day to change as new orders are received, but the first day should always be the same.

When I follow those steps, I see...
variation in data on the first day

I was expecting...
The first day should always have the same results throughout the day.

## Environment

<details>
```
Grab the system status report from WooCommerce > System Status and paste it here.
```
`
### WordPress Environment ###

Home URL: https://kappapuzzles.com
Site URL: https://kappapuzzles.com
WC Version: 3.0.8
Log Directory Writable: 
WP Version: 4.8
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: 
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.30
PHP Post Max Size: 65 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.45.0
OpenSSL/1.0.1e

SUHOSIN Installed: –
MySQL Version: 5.6.32
Max Upload Size: 64 MB
Default Timezone is UTC: 
fsockopen/cURL: 
SoapClient: 
DOMDocument: 
GZip: 
Multibyte String: 
Remote Post: 
Remote Get: 

### Database ###

WC Database Version: 3.0.8
WC Database Prefix: wp_1mcgxq2kjc_
woocommerce_sessions: 
woocommerce_api_keys: 
woocommerce_attribute_taxonomies: 
woocommerce_downloadable_product_permissions: 
woocommerce_order_items: 
woocommerce_order_itemmeta: 
woocommerce_tax_rates: 
woocommerce_tax_rate_locations: 
woocommerce_shipping_zones: 
woocommerce_shipping_zone_locations: 
woocommerce_shipping_zone_methods: 
woocommerce_payment_tokens: 
woocommerce_payment_tokenmeta: 
MaxMind GeoIP Database: 

### Security ###

Secure connection (HTTPS): 
Hide errors from visitors: 

### Active Plugins (27) ###

HTML in Category Descriptions: by Arno Esterhuizen – 1.2.1.1
Beaver Builder Plugin (Lite Version): by The Beaver Builder Team – 1.10.5.1
Contact Form 7 Conditional Fields: by Jules Colle – 1.3.4
Contact Form 7: by Takayuki Miyoshi – 4.8
Contact Widgets: by GoDaddy – 1.4.1
Easy Google Fonts: by Titanium Themes – 1.4.3
Error Log Monitor: by Janis Elsts – 1.5.4
Google Analytics for WordPress by MonsterInsights: by MonsterInsights – 6.2.0
iframe: by webvitaly – 4.3
Insert PHP: by Will Bontrager Software
LLC  – 1.3

Menu Image: by Alex Davyskiba aka Zviryatko – 2.7.0
WooCommerce Order Export and More: by JEM Plugins – 1.3.2
Post Expirator: by Aaron Axelsen – 2.2.1
Quick Page/Post Redirect Plugin: by anadnet – 5.1.8
Responsive Image Maps: by Philip Newcomer – 1.4
Storefront Product Pagination: by WooThemes – 1.2.1
Storefront Product Sharing: by WooThemes – 1.0.3
Storefront Sticky Add to Cart: by WooThemes – 1.1.6
WooCommerce Menu Cart: by Jeremiah Prummer
Ewout Fernhout – 2.6.0

WooCommerce Remove Product Sorting: by SkyVerge – 1.0.0
WooCommerce Shortcodes: by WooThemes
Claudio Sanches – 1.0.0

WooCommerce: by Automattic – 3.0.8 – 3.1.0 is available
Crossword Compiler Puzzles: by WordWeb Software – 11.0
WP Mail Logging: by Christian Zöller – 1.8.1
WP-Mail-SMTP: by Callum Macdonald – 0.10.1
WP Rollback: by WordImpress – 1.4
WP101 Video Tutorials: by WP101Plugin.com – 0.3

### Settings ###

API Enabled: 
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #5 - /shop/
Cart: #6 - /cart/
Checkout: #7 - /checkout/
My account:  Page visibility should be public

### Theme ###

Name: Merlin Child Theme
Version: 1.0.0
Author URL: 
Child Theme: 
Parent Theme Name: Merlin
Parent Theme Version: 1.2.3
Parent Theme Author URL: https://themezee.com
WooCommerce Support: 

### Templates ###

Overrides: –
</details>

[Woocommerce Last 7 Day issue.pdf](https://github.com/woocommerce/woocommerce/files/1112776/Woocommerce.Last.7.Day.issue.pdf)

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ ] I can reproduce this bug consistently

### PR DESCRIPTION
**Pull request by mikejolley**
Fixes #15870

### CODE REVIEW

File: includes/admin/reports/class-wc-admin-report.php [hunk 1]
```diff
@@ -558,7 +558,7 @@ public function calculate_current_range( $current_range ) {
 			break;
 
 			case '7day' :
-				$this->start_date    = strtotime( '-6 days', current_time( 'timestamp' ) );
+				$this->start_date    = strtotime( '-6 days', strtotime( 'midnight', current_time( 'timestamp' ) ) );
```
Comment (claudiulodro) [inline includes/admin/reports/class-wc-admin-report.php]: Looks good. I think strtotime can be simplified to `strtotime( 'today midnight' )`, but that's just pedantry. :)

Comment (mikejolley) [inline includes/admin/reports/class-wc-admin-report.php]: current_time is local time so that could upset this depending on timezone.

Comment (claudiulodro) [inline includes/admin/reports/class-wc-admin-report.php]: Actually, after doing some more research, I think the best way of doing this is `strtotime( 'today midnight - 6 days')`.
