### PR TITLE
Sort countries using new ascii comparison function

### LINKED ISSUE #21175: Alphabetical listing of some countries in Spanish is incorrect.
**Describe the bug**
The sorting of  certain countries, including México, among others, is incorrectly set to a later place in the list based on the accent marks. México should come after Mayotte, but before Micronesia, but it is (in Spanish) placed after Mozambique.

Also some others: 
Antártida must be shown before Antigua y Barbuda, Bélgica before Benin, Irán before Irlanda, Mónaco before Mongolia, Níger before Nigeria, Países Bajos before Pakistán, and Túnez before Turkmenistán. 

Hattip to @rodrigoprimo for pointing out that the issue also happens when you call `WC()->countries->get_countries()` and that it's likely from here: https://github.com/woocommerce/woocommerce/blob/9319b3c2621ed0a7f1bf2aee803e74332922a0d1/includes/class-wc-countries.php#L53

**To Reproduce**
1. Set your language to Spanish (I set it to Mexican Spanish)
2. Go to your checkout page.
3. Select the country list, and scroll down.

**Expected behavior**

The sorting should just essentially ignore the accent marks.

**Isolating the problem (mark completed items with an [x]):**
- [ x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
`
### WordPress Environment ###

Home URL: https://slashandy.mystagingwebsite.com
Site URL: https://slashandy.mystagingwebsite.com
WC Version: 3.4.4
Log Directory Writable: ✔
WP Version: 4.9.8
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 7.0.31 - We recommend using PHP version 7.2 or above for greater performance and security. How to update your PHP version
PHP Post Max Size: 100 MB
PHP Time Limit: 300
PHP Max Input Vars: 6144
cURL Version: 7.61.0
OpenSSL/1.0.1t

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.1.17-MariaDB
Max Upload Size: 100 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.4.4
WC Database Prefix: wp_
Total Database Size: 5.62MB
Database Data Size: 3.51MB
Database Index Size: 2.11MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_order_itemmeta: Data: 0.06MB + Index: 0.03MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_commentmeta: Data: 0.06MB + Index: 0.03MB
wp_comments: Data: 0.05MB + Index: 0.09MB
wp_followup_coupons: Data: 0.02MB + Index: 0.03MB
wp_followup_coupon_logs: Data: 0.02MB + Index: 0.05MB
wp_followup_customers: Data: 0.02MB + Index: 0.06MB
wp_followup_customer_carts: Data: 0.02MB + Index: 0.03MB
wp_followup_customer_notes: Data: 0.02MB + Index: 0.03MB
wp_followup_customer_orders: Data: 0.02MB + Index: 0.02MB
wp_followup_email_coupons: Data: 0.02MB + Index: 0.02MB
wp_followup_email_excludes: Data: 0.02MB + Index: 0.05MB
wp_followup_email_logs: Data: 0.02MB + Index: 0.05MB
wp_followup_email_orders: Data: 0.20MB + Index: 0.09MB
wp_followup_email_order_coupons: Data: 0.02MB + Index: 0.02MB
wp_followup_email_tracking: Data: 0.02MB + Index: 0.08MB
wp_followup_followup_history: Data: 0.02MB + Index: 0.05MB
wp_followup_order_categories: Data: 0.02MB + Index: 0.03MB
wp_followup_order_items: Data: 0.02MB + Index: 0.05MB
wp_followup_subscribers: Data: 0.02MB + Index: 0.03MB
wp_followup_subscribers_to_lists: Data: 0.02MB + Index: 0.03MB
wp_followup_subscriber_lists: Data: 0.02MB + Index: 0.03MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_options: Data: 1.48MB + Index: 0.05MB
wp_postmeta: Data: 0.44MB + Index: 0.25MB
wp_posts: Data: 0.28MB + Index: 0.06MB
wp_termmeta: Data: 0.02MB + Index: 0.03MB
wp_terms: Data: 0.02MB + Index: 0.03MB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wp_usermeta: Data: 0.02MB + Index: 0.03MB
wp_users: Data: 0.02MB + Index: 0.05MB
wp_wcpv_commissions: Data: 0.02MB + Index: 0.00MB
wp_wcpv_per_product_shipping_rules: Data: 0.02MB + Index: 0.00MB
wp_wc_booking_relationships: Data: 0.02MB + Index: 0.03MB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_wc_points_rewards_user_points: Data: 0.02MB + Index: 0.03MB
wp_wc_points_rewards_user_points_log: Data: 0.02MB + Index: 0.05MB
wp_wc_warranty_products: Data: 0.02MB + Index: 0.05MB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_bundled_itemmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_bundled_items: Data: 0.02MB + Index: 0.03MB

### Post Type Counts ###

attachment: 52
carts: 4
customize_changeset: 1
jp_img_sitemap: 4
jp_sitemap: 4
jp_sitemap_master: 4
page: 10
post: 2
product: 29
product_variation: 12
revision: 4
scheduled-action: 74
shop_coupon: 2
shop_order: 19

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (9) ###

VaultPress: by Automattic – 1.9.5
Akismet Anti-Spam: by Automattic – 4.0.8
Gutenberg: by Gutenberg Team – 3.4.0
Homepage Control: by WooThemes – 2.0.3
Jetpack by WordPress.com: by Automattic – 6.4.2
Storefront Powerpack: by WooCommerce – 1.4.9 – 1.4.11 is available
User Switching: by John Blackbourn & contributors – 1.3.1
WooCommerce Gutenberg Products Block: by Automattic – 1.1.0
WooCommerce: by Automattic – 3.4.4

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: booking (booking)
bundle (bundle)
external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: #3 - /shop/
Cart: #4 - /cart/
Checkout: #5 - /checkout/
My account: #6 - /my-account/
Terms and conditions: #121 - /my-ticket/

### Theme ###

Name: Storefront
Version: 2.3.3
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –
`.
```
</details>

### PR DESCRIPTION
**Pull request by kloon**
### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

This PR introduces a new uasort function called wc_ascii_uasort_comparison, this function converts strings to ascii before comparing it, this fixes issues where if your site was in a language that uses accents it would not order the countries correctly.

Closes #21175

### How to test the changes in this Pull Request:

1. Switch your WordPress site to Spanish
2. Follow [this guide](https://docs.woocommerce.com/document/woocommerce-localization/) and download the Spanish WooCommerce translation
3. Go to any page where countries are displayed, ie checkout, and ensure the orders of accented countries are correctly sorted alphabetically.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

### Changelog entry

> Fix country sorting for stores which use a language that uses a lot of accented characters, ie Spanish.

### CODE REVIEW

File: includes/wc-core-functions.php [hunk 1]
```diff
@@ -1553,6 +1553,19 @@ function wc_uasort_comparison( $a, $b ) {
...
 
+/**
+ * Sort values based on ascii, usefull for special chars in strings.
+ *
+ * @param string $a First value.
+ * @param string $b Second value.
+ * @return int
+ */
+function wc_ascii_uasort_comparison( $a, $b ) {
+	$aconv = iconv( 'UTF-8', 'ASCII//TRANSLIT', $a );
```
Comment (mikejolley) [inline includes/wc-core-functions.php]: I'm not sure `iconv` is available on all installs - we have function exists checks in other places. Is that neeed here too?

**Review by mikejolley — APPROVED** [review]

**Comment by mikejolley** [comment]
@kloon related to this change: https://github.com/woocommerce/woocommerce/pull/22981#issuecomment-471526798

@tristanbes doing anything custom/special with country names on your install?

**Comment by tristanbes** [comment]
Not that I'm aware of (= unlikely it's the case)

**Comment by websupporter** [comment]
Hi, sorry for being quite late, but I noticed this function today in KCacheGrind. I guess this comes to late but maybe as a hint:

The way `wc_ascii_uasort_comparison()` utilizes `iconv()` is quite time consuming, because `iconv()` gets called very often.

In my test it is called 1894 times, while there are only 249 countries, due to how `uasort()` works.

```
/**
 * Sort values based on ascii, useful for special chars in strings.
 *
 * @param array values to sort.
 * @return array
 */
function wc_ascii_uasort_comparison( $data ) {
	$sorted_data = $data;
	array_walk( $sorted_data,function( &$entry ) {
		$entry = iconv( 'UTF-8', 'ASCII//TRANSLIT', $entry );
	} );
	uasort($sorted_data, 'strcmp' );
	foreach ( $sorted_data as $key => $val ) {
		$sorted_data[$key] = $data[$key];
	}
	return $sorted_data;
}
```
A sorting function like this one would take less time.

Current implementation
current

Improvement:
updated
