### PR TITLE
Prevent the "return to cart" link being clickable in the editor

### LINKED ISSUE #56207: Cart Link Block - Prevent navigation
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

The Cart Link block is throwing this error:

```
TypeError: Cannot read properties of null (reading 'ResizeObserver')
    at http://wp-src.test/wp-content/plugins/gutenberg/build/block-editor/index.min.js?ver=c3c74ef22219c0ab5da2:28736:19
    at commitHookEffectListMount (http://wp-src.test/wp-content/plugins/gutenberg/build/vendors/react-dom.js?ver=18:23199:28)
    at commitLayoutEffectOnFiber (http://wp-src.test/wp-content/plugins/gutenberg/build/vendors/react-dom.js?ver=18:23317:19)
    at commitLayoutMountEffects_complete (http://wp-src.test/wp-content/plugins/gutenberg/build/vendors/react-dom.js?ver=18:24737:11)
    at commitLayoutEffects_begin (http://wp-src.test/wp-content/plugins/gutenberg/build/vendors/react-dom.js?ver=18:24723:9)
    at commitLayoutEffects (http://wp-src.test/wp-content/plugins/gutenberg/build/vendors/react-dom.js?ver=18:24661:5)
    at commitRootImpl (http://wp-src.test/wp-content/plugins/gutenberg/build/vendors/react-dom.js?ver=18:26872:7)
    at commitRoot (http://wp-src.test/wp-content/plugins/gutenberg/build/vendors/react-dom.js?ver=18:26731:7)
    at performSyncWorkOnRoot (http://wp-src.test/wp-content/plugins/gutenberg/build/vendors/react-dom.js?ver=18:26166:5)
    at flushSyncCallbacks (http://wp-src.test/wp-content/plugins/gutenberg/build/vendors/react-dom.js?ver=18:12052:24)
```

This happens when a user clicks the block and navigates away from the page.

I wonder if Gutenberg should prevent all links from working in the editor.

### Expected behavior

Clicking on the Cart Link block shouldn't navigate the user.

### Actual behavior

The above error!

### Steps to reproduce

1. Insert a Cart Link block
2. Click on the block to navigate
3. You navigate to another page
4. Now try to use the editor - it crashes

See video:

https://github.com/user-attachments/assets/cd098c90-2cbd-4e96-a5e3-187ed56ccf7b

<details>
<summary>WordPress Environment</summary>

```
### WordPress Environment ###

WordPress address (URL): http://wp-src.test
Site address (URL): http://wp-src.test
WC Version: 9.7.1
Legacy REST API Package Version: The Legacy REST API plugin is not installed on this site.
Action Scheduler Version: ✔ 3.9.0
Log Directory Writable: ✔
WP Version: 6.8-alpha-59274-src
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.62 (Unix) PHP/8.3.9
PHP Version: 8.3.9
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 8.8.0
(SecureTransport) OpenSSL/3.3.1

SUHOSIN Installed: –
MySQL Version: 8.3.0
Max Upload Size: 0 B
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 9.7.1
WC Database Prefix: wp_
Total Database Size: 13.25MB
Database Data Size: 11.38MB
Database Index Size: 1.87MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 5.06MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.09MB + Index: 0.03MB + Engine InnoDB
wp_posts: Data: 5.20MB + Index: 0.20MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_word_frequencies: Data: 0.05MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

acf-field: 2
acf-field-group: 1
attachment: 44
guest-author: 1
nav_menu_item: 5
page: 13
post: 125
revision: 633
wp_block: 1
wp_font_face: 38
wp_font_family: 14
wp_global_styles: 42
wp_nav_overlay: 2
wp_navigation: 14
wp_template: 7
wp_template_part: 21

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (9) ###

Block Experiments: by Automattic – 1.0.0
Create Block Theme: by WordPress.org – 2.4.0
Responsive Navigation Block - control your menus based on screen size.: by Dave Smith – 1.0.0
Gutenberg: by Gutenberg Team – 19.9.0
Members: by MemberPress – 3.2.17
Page Optimize: by Automattic – 0.5.6
Theme Check: by Themes Team – 20231220
WooCommerce: by Automattic – 9.7.1
Word Frequency Analyzer: by Your Name – 1.0.0

### Inactive Plugins (9) ###

Advanced Custom Fields: by WP Engine – 6.3.5
Co-Authors Plus: by Mohammad Jangda
Daniel Bachhuber
Automattic – 3.5.15

CoBlocks: by GoDaddy – 3.0.2
Hello Dolly: by Matt Mullenweg – 1.7.2
Highlight Search Terms: by RavanH – 1.8.2
Sample plugin: by  –
Styles plugin: by  –
WordPress Reset: by Aristeides Stathopoulos
Matt Martz – 1.4.2

WP Database Reset: by WebFactory Ltd – 3.22

### Must Use Plugins (1) ###

0-sandbox.php: by  –

### Settings ###

Legacy API Enabled: –
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 3 KB

### WC Pages ###

Shop base: #2330 - /shop/
Cart: #2331 - /cart/ -  Contains the woocommerce/cart block
Checkout: #2332 - /checkout/ -  Contains the woocommerce/checkout block
My account: #2333 - /my-account/ -  Contains the [woocommerce_my_account] shortcode
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty-Five
Version: 1.0
Author URL: https://wordpress.org
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
Theme type: Block theme
WooCommerce Support: ❌ Not declared

### Templates ###

Overrides: /Users/ben/Sites/wordpress-develop/src/wp-content/plugins/woocommerce/templates/block-notices/error.php
/Users/ben/Sites/wordpress-develop/src/wp-content/plugins/woocommerce/templates/block-notices/notice.php
/Users/ben/Sites/wordpress-develop/src/wp-content/plugins/woocommerce/templates/block-notices/success.php


### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
onboarding
onboarding-tasks
pattern-toolkit-full-composability
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
printful
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page
launch-your-store
add-to-cart-with-options-stepper-layout

Disabled Features: product-data-views
experimental-blocks
coming-soon-newsletter-template
minified-js
product-pre-publish-modal
settings
async-product-editor-category-field
product-editor-template-system
blueprint
reactify-classic-payments-settings
use-wp-horizon
blockified-add-to-cart

Daily Cron: ✔ Next scheduled: 2025-03-08 10:31:17 +00:00
Options: ✔
Notes: 59
Onboarding: skipped

### Action Scheduler ###

Complete: 5
Oldest: 2025-03-06 10:32:20 +0000
Newest: 2025-03-07 10:56:23 +0000

Pending: 1
Oldest: 2025-03-08 10:56:23 +0000
Newest: 2025-03-08 10:56:23 +0000


### Status report information ###

Generated at: 2025-03-07 11:37:03 +00:00```

</details>


### Isolating the problem

- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by mikejolley**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Allows the link to be rendered as a span instead of an anchor to prevent navigation. I considered using `<Disabled>` here, but decided against it because it would prevent interaction with the `<RichText>` component.

Closes #56207

(For Bug Fixes) Bug introduced in PR # .

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Edit the checkout page
2. Select the checkout block and enable the "return to cart link" if disabled
3. Click on the link (to edit the text). It should not navigate away from the current page.
4. Save changes and view checkout on the frontend.
5. Confirm return to cart link works on frontend 

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

**Review by opr — APPROVED** [review]
Looks good, I tried clicking it in the editor and it lets me edit it, it doesn't navigate away from the editor.

I suggested a change to prevent adding an invalid attribute to a span, but it's a simple change so pre-approving.

File: plugins/woocommerce/client/blocks/assets/js/base/components/cart-checkout/return-to-cart-button/index.tsx [hunk 1]
```diff
@@ -12,24 +12,27 @@ import './style.scss';
...
 }: ReturnToCartButtonProps ): JSX.Element | null => {
 	const cartLink = href || CART_URL;
 	if ( ! cartLink ) {
 		return null;
 	}
+	const Element = element;
 	return (
-		<a
+		<Element
 			href={ cartLink }
```
Comment (opr) [inline plugins/woocommerce/client/blocks/assets/js/base/components/cart-checkout/return-to-cart-button/index.tsx]: We should probably not put href on it if it's a span
```suggestion
			{ ...( element === 'a' ? { href: cartLink } : {} ) }
```
