### PR TITLE
[Accessibility] Provide screen readers with product sorting status message

### LINKED ISSUE #43569: Accessibility: Product sorting status message not provided for screen reader users
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

There's no status message for screen reader users associated with product sorting on the product archive.

### Expected behavior

Screen reader users should receive a status message or clear indication that the sorting worked and the product order changed. 

This message could be handled in several ways since the page reloads. Here are some options to consider:

- Add a dismissable success message "Shop order changed to sort by popularity" that is visible to everyone.
- Add visible or screen reader only text to the H1 that indicates how the products are ordered "Shop - sorted by popularity."
- Append the order by information to the result count and set keyboard focus on that element when the page reloads so it it is read out: "Showing all 13 results sorted by popularity."

### Actual behavior

When sorting products with the dropdown on the shop archive, the page reloads and products are sorted, however this is not announced to screen reader users. When the page reloads, screen reader users are back at the top of the page and they have to explore the products to see if the order has changed and sorting was successful.

### Steps to reproduce

1. Turn on either NVDA or VoiceOver screen readers.
2. Sort the products on the shop archive using the Shop Order dropdown.
3. Listen and notice that no announcement of success it provided.

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://shop.equalizedigital.com
Site address (URL): https://shop.equalizedigital.com
WC Version: 8.4.0
REST API Version: ✔ 8.4.0
WC Blocks Version: ✔ 11.6.2
Action Scheduler Version: ✔ 3.7.1
Log Directory Writable: ✔
WP Version: 6.4.2
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 8.2.14
PHP Post Max Size: 100 MB
PHP Time Limit: 43300
PHP Max Input Vars: 10000
cURL Version: 7.81.0
OpenSSL/3.0.2

SUHOSIN Installed: –
MySQL Version: 8.0.35-27
Max Upload Size: 50 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.4.0
WC Database Prefix: wp_
Total Database Size: 11.55MB
Database Data Size: 7.50MB
Database Index Size: 4.05MB
wp_woocommerce_sessions: Data: 0.08MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_ac_segments: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_accessibility_checker: Data: 1.44MB + Index: 0.02MB + Engine InnoDB
wp_accessibility_checker_audit_history: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_accessibility_checker_global_ignores: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_actionscheduler_actions: Data: 1.50MB + Index: 0.83MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.42MB + Index: 0.36MB + Engine InnoDB
wp_admin_columns: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_gf_draft_submissions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_gf_entry: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gf_entry_meta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_gf_entry_notes: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gf_form: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gf_form_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gf_form_revisions: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gf_form_view: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gf_rest_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 0.45MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 1.52MB + Index: 0.56MB + Engine InnoDB
wp_posts: Data: 0.42MB + Index: 0.14MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.06MB + Index: 0.05MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.06MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woo_shippment_provider: Data: 0.14MB + Index: 0.00MB + Engine InnoDB
wp_wpforms_payment_meta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wpforms_payments: Data: 0.02MB + Index: 0.14MB + Engine InnoDB
wp_wpforms_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpmailsmtp_debug_events: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpmailsmtp_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_yoast_indexable: Data: 0.05MB + Index: 0.09MB + Engine InnoDB
wp_yoast_indexable_hierarchy: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_primary_term: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_yoast_seo_links: Data: 0.02MB + Index: 0.03MB + Engine InnoDB

### Post Type Counts ###

attachment: 127
custom_css: 1
customize_changeset: 26
page: 13
post: 3
product: 14
product_variation: 257
shop_order_placehold: 1
wp_global_styles: 1
wp_navigation: 5
wp_template: 5
wp_template_part: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (16) ###

Gravity Forms: by Gravity Forms – 2.8.1
Accessibility Checker: Audit History: by Equalize Digital – 1.0.2
Accessibility Checker Pro: by Equalize Digital – 1.5.2
Accessibility Checker: by Equalize Digital – 1.7.0
Accessibility New Window Warnings: by Equalize Digital – 1.0.8
Admin Columns Pro: by AdminColumns.com – 6.4.3
WP Engine Smart Plugin Manager: by WP Engine – 5.17.30
Font Awesome: by Font Awesome – 4.4.0
Gravity Forms Zero Spam: by GravityKit – 1.4.1
Printful Integration for WooCommerce: by Printful – 2.2.7
SimpleTOC - Table of Contents Block: by Marc Tönsing – 6.0.14
Advanced Shipment Tracking for WooCommerce: by zorem – 3.6.5
WooCommerce Stripe Gateway: by WooCommerce – 7.9.0
WooCommerce: by Automattic – 8.4.0
Yoast SEO: by Team Yoast – 21.8
WP Mail SMTP: by WP Mail SMTP – 3.11.0

### Inactive Plugins (2) ###

Akismet Anti-spam: Spam Protection: by Automattic - Anti-spam Team – 5.3
Variation Swatches for WooCommerce: by Emran Ahmed – 2.0.29

### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
object-cache.php: Memcached Redux

### Must Use Plugins (5) ###

Force Strong Passwords - WPE Edition: by Jason Cosper – 1.8.0
WP Engine Cache Plugin: by WP Engine – 1.1.4
WP Engine Seamless Login Plugin: by WP Engine – 1.6.1
WP Engine Security Auditor: by wpengine – 1.1.1
WP Engine System: by WP Engine – 5.0.1

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to Woo.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### WC Pages ###

Shop base: #31 - /shop/
Cart: #32 - /cart/
Checkout: #33 - /checkout/
My account: #34 - /my-account/
Terms and conditions: #35 - /refund-returns/

### Theme ###

Name: Twenty Twenty-Four
Version: 1.0
Author URL: https://wordpress.org
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ❌ Not declared

### Templates ###

Overrides: /nas/content/live/edshopprd/wp-content/plugins/woocommerce/packages/woocommerce-blocks/templates/notices/error.php
/nas/content/live/edshopprd/wp-content/plugins/woocommerce/packages/woocommerce-blocks/templates/notices/notice.php
/nas/content/live/edshopprd/wp-content/plugins/woocommerce/packages/woocommerce-blocks/templates/notices/success.php

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
product-virtual-downloadable
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: customize-store
minified-js
new-product-management-experience
product-external-affiliate
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2024-01-12 22:12:37 -06:00
Options: ✔
Notes: 70
Onboarding: completed

### Action Scheduler ###

Complete: 2,712
Oldest: 2023-12-18 21:21:19 -0600
Newest: 2024-01-12 09:31:39 -0600

Failed: 2
Oldest: 2024-01-03 00:25:12 -0600
Newest: 2024-01-03 00:25:12 -0600

Pending: 5
Oldest: 2024-01-12 09:32:39 -0600
Newest: 2024-01-12 20:50:19 -0600

### Status report information ###

Generated at: 2024-01-12 09:31:52 -06:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by Manussakis**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes #43569 .

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

#### Testing product catalog with pagination.
1. Go to the shop page.
2. Sort products by any one of the options available in the sort input.
3. Verify the sorting status message is announced once the page loads.
4. Verify the sorting status message is not announced when products are sorted by the default option once the page loads.

#### Testing product catalog with one page.
If you used the sample product data to create your store, the `music` category should meet this criteria `product-category/music/` since only two products are under it.
1. Open the product catalog page.
2. Sort products by any one of the options available in the sort input.
3. Verify the sorting status message is announced once the page loads.
4. Verify the sorting status message is not announced when products are sorted by the default option once the page loads.

#### Testing product catalog with one product.
If you used the sample product data to create your store, the `decor` product category should meet this criteria `product-category/decor/` since only one product is under it.
1. Open the product catalog page.
2. The sorting status message should never be announced since the sort action takes no effect if there is only one product in the catalog once the page loads.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

**Comment by Manussakis** [comment]
@dkotter This task is ready for code review.

File: plugins/woocommerce/client/legacy/js/frontend/woocommerce.js [hunk 1]
```diff
@@ -119,4 +119,19 @@ jQuery( function( $ ) {
...
+		var $sorted_by_live_region = $( '.woocommerce-result-count[data-is-sorted-by="true"]' );
+
+		if ( $sorted_by_live_region.length > 0 ) {
+			var text = $sorted_by_live_region.first().html();
+			
+			$sorted_by_live_region.delay( 1000 ).queue( function() {
+				$( this )
+					.html( '' )
+					.html( text )
+					.deuqueue();
```
Comment (dkotter) [inline plugins/woocommerce/client/legacy/js/frontend/woocommerce.js]: Is this supposed to be `dequeue`?

File: plugins/woocommerce/includes/wc-template-functions.php [hunk 2]
```diff
@@ -1486,10 +1486,46 @@ function woocommerce_result_count() {
...
-			'per_page' => wc_get_loop_prop( 'per_page' ),
-			'current'  => wc_get_loop_prop( 'current_page' ),
+
+		/**
+			* Filters the default orderby option..
+			*
+			* @since 1.6.4
+			*
+			* @param string  $default_orderby The default orderby option.
+			*/
```
Comment (dkotter) [inline plugins/woocommerce/includes/wc-template-functions.php]: Spacing looks off here

File: plugins/woocommerce/includes/wc-template-functions.php [hunk 3]
```diff
@@ -1486,10 +1486,46 @@ function woocommerce_result_count() {
 		if ( ! wc_get_loop_prop( 'is_paginated' ) || ! woocommerce_products_will_display() ) {
 			return;
 		}
-		$args = array(
-			'total'    => wc_get_loop_prop( 'total' ),
-			'per_page' => wc_get_loop_prop( 'per_page' ),
-			'current'  => wc_get_loop_prop( 'current_page' ),
+
+		/**
+			* Filters the default orderby option..
```
Comment (dkotter) [inline plugins/woocommerce/includes/wc-template-functions.php]:
```suggestion
			* Filters the default orderby option.
```

File: plugins/woocommerce/includes/wc-template-functions.php [hunk 4]
```diff
@@ -1486,10 +1486,46 @@ function woocommerce_result_count() {
...
+		// If products follow the default order this doesn't need to be informed.
+		$orderby = 'menu_order' === $orderby ? '' : $orderby;
+
+		/**
+			* Filters ordered by messages.
+			*
+			* @since 9.3.0
+			*
+			* @param array  $orderedby_messages The list of messages per orderby key.
+			*/
```
Comment (dkotter) [inline plugins/woocommerce/includes/wc-template-functions.php]: Spacing looks off here

**Review by dkotter — CHANGES_REQUESTED** [review]

**Comment by Manussakis** [comment]
@dkotter This task is ready for re-review.

**Review by dkotter — APPROVED** [review]
@ankitguptaindia @qasumitbagthariya This is ready for QA

**Comment by qasumitbagthariya** [comment]
@Manussakis Thanks for the PR.

### QA Update  ⚠️
-------------

**Testing product catalog with pagination. ⚠️**

The Default sorting status message, which is currently announced when products are sorted by the default option, should not be announced according to the PR description.


https://github.com/user-attachments/assets/42507c6e-ad28-4f60-96df-b794463bf847

---

**Testing product catalog with one page. ⚠️**

The Default sorting status message, which is currently announced when products are sorted by the default option, should not be announced according to the PR description.


https://github.com/user-attachments/assets/75fbf958-9b59-484b-b254-862ecd32bea7

---

**Testing product catalog with one product.** ⚠️

The sorting status message, which is currently announced when products are sorted, should not be announced according to the PR description.

https://github.com/user-attachments/assets/3b897589-3adb-4b45-9296-5e194cf3e0c4

---

**Comment by Manussakis** [comment]
@qasumitbagthariya Thanks for testing the PR.
I apologize if I was unclear in my communication when putting together the steps for QA.

> 3. Verify the sorting status message is announced once the page loads.
> 4. Verify the sorting status message is not announced when products are sorted by the default option.

I should have also specified **"... once the page loads."** on the item number 4.

The following message, that is present on your screen record:

> Default sorting, Shop order, menu pop up collapsed, button

is announced when users focus/select the "Default sorting" option. It's correct for this message to be announced since users need to know the option name before choosing it. However, once the option is applied, the page loads and that's when the "Default sorting" option should not be announced.

Let's have the "Sort by popularity" option as an example. Once the page loads after selecting this option, this is what screen readers announce (see image):

Screen Shot 2024-08-19 at 6 35 35 PM

This type of message should not be announced for the "Default sorting" option.

Would you mind testing the PR again now that I have given you more context on it?

Thanks!

**Comment by vikrampm1** [comment]
@qasumitbagthariya this is back for your QA again.

**Comment by qasumitbagthariya** [comment]
@Manussakis Thanks for the detailed comment.

### QA Update ✅
---

**Testing product catalog with pagination.**   ✅

https://github.com/user-attachments/assets/6d146713-7d3a-4c16-a951-25313d7ca233

**Testing product catalog with one page.**  ✅

https://github.com/user-attachments/assets/70bb5712-786f-4f78-b83e-de94a26966ae

**Testing product catalog with one product.**  ✅

https://github.com/user-attachments/assets/318c6a87-6642-4b13-950e-86fde63f3471


status update:
@vikrampm1 PR is ready for the next step.

**Comment by vikrampm1** [comment]
@Manussakis please remove WIP from the title and make the PR ready for review.

**Comment by vikrampm1** [comment]
@woocommerce/woo-fse this PR is ready for your review!

**Comment by vikrampm1** [comment]
@roykho noting that this PR is awaiting your review. cc @woocommerce/woo-fse

**Comment by roykho** [comment]
@vikrampm1 thanks for the ping. I will try to get to this by tomorrow.

File: plugins/woocommerce/client/legacy/js/frontend/woocommerce.js [hunk 5]
```diff
@@ -119,4 +119,19 @@ jQuery( function( $ ) {
...
+			var text = $sorted_by_live_region.first().html();
+			
+			$sorted_by_live_region.delay( 1000 ).queue( function() {
+				$( this )
+					.html( '' )
+					.html( text )
+					.dequeue();
+			} );
+		}
+	} );
```
Comment (tjcafferkey) [inline plugins/woocommerce/client/legacy/js/frontend/woocommerce.js]: Please can we rewrite this in vanilla JS? We are trying to reduce additional jQuery code being added to the codebase so we can remove it as a dependency sometime in the future. I don't think this particular block of code should be too difficult to rewrite and I'm happy to assist if needed.

File: plugins/woocommerce/includes/wc-template-functions.php [hunk 6]
```diff
@@ -1480,10 +1480,46 @@ function woocommerce_result_count() {
...
+		 * Filters the default orderby option.
+		 *
+		 * @since 1.6.4
+		 *
+		 * @param string  $default_orderby The default orderby option.
+		 */
+		$default_orderby = apply_filters( 'woocommerce_default_catalog_orderby', get_option( 'woocommerce_default_catalog_orderby', '' ) );
+		// phpcs:disable WordPress.Security.NonceVerification.Recommended
+		$orderby = isset( $_GET['orderby'] ) ? wc_clean( wp_unslash( $_GET['orderby'] ) ) : $default_orderby;
+		// phpcs:enable WordPress.Security.NonceVerification.Recommended
```
Comment (tjcafferkey) [inline plugins/woocommerce/includes/wc-template-functions.php]: We can use `phpcs:ignore` instead of enabling/disabling here

```suggestion
		// phpcs:ignore WordPress.Security.NonceVerification.Recommended
		$orderby = isset( $_GET['orderby'] ) ? wc_clean( wp_unslash( $_GET['orderby'] ) ) : $default_orderby;
```

File: plugins/woocommerce/includes/wc-template-functions.php [hunk 7]
```diff
@@ -1480,10 +1480,46 @@ function woocommerce_result_count() {
...
-			'current'  => wc_get_loop_prop( 'current_page' ),
+
+		/**
+		 * Filters the default orderby option.
+		 *
+		 * @since 1.6.4
+		 *
+		 * @param string  $default_orderby The default orderby option.
+		 */
+		$default_orderby = apply_filters( 'woocommerce_default_catalog_orderby', get_option( 'woocommerce_default_catalog_orderby', '' ) );
```
Comment (tjcafferkey) [inline plugins/woocommerce/includes/wc-template-functions.php:1491]: There is no guarantee this will be a `string` once all filters are run. Please can we add a type check when using this value?

File: plugins/woocommerce/includes/wc-template-functions.php [hunk 8]
```diff
@@ -1480,10 +1480,46 @@ function woocommerce_result_count() {
...
+		$orderby = 'menu_order' === $orderby ? '' : $orderby;
+
+		/**
+		 * Filters ordered by messages.
+		 *
+		 * @since 9.3.0
+		 *
+		 * @param array  $orderedby_messages The list of messages per orderby key.
+		 */
+		$catalog_orderedby_options = apply_filters(
```
Comment (tjcafferkey) [inline plugins/woocommerce/includes/wc-template-functions.php:1507]: Same goes for this, please can we type check this result before using it. There's no guarantee this will be an `array` once all filters have run.

**Review by tjcafferkey — CHANGES_REQUESTED** [review]
Thanks for this! I've reviewed the code and added some comments regarding some changes I think would be good to see implemented. Happy to assist if needed 😄

File: plugins/woocommerce/includes/wc-template-functions.php (hunk 7 above)
Comment (Manussakis) [reply plugins/woocommerce/includes/wc-template-functions.php:1491]: @tjcafferkey Thanks for catching that!
The `$default_orderby` variable is used to set the `$orderby` value, so I decided to add this piece of code as the final statement to set it:
```php
$orderby = is_string( $orderby ) ? $orderby : '';
```

File: plugins/woocommerce/includes/wc-template-functions.php (hunk 8 above)
Comment (Manussakis) [reply plugins/woocommerce/includes/wc-template-functions.php:1507]: @tjcafferkey Please take a look at this statement below:

```php
$orderedby = isset( $catalog_orderedby_options[ $orderby ] ) ? $catalog_orderedby_options[ $orderby ] : '';
```

If `$catalog_orderedby_options` is not an array, the result of the `isset` function will be `false` and `$orderedby` will be set to `''`. Unless I missed something, `isset` is already checking if `$catalog_orderedby_options` is an array and if `$orderby` property exists.

File: plugins/woocommerce/includes/wc-template-functions.php [hunk 9]
```diff
@@ -1480,10 +1480,48 @@ function woocommerce_result_count() {
...
+				'menu_order' => __( 'Default sorting', 'woocommerce' ),
+				'popularity' => __( 'Sorted by popularity', 'woocommerce' ),
+				'rating'     => __( 'Sorted by average rating', 'woocommerce' ),
+				'date'       => __( 'Sorted by latest', 'woocommerce' ),
+				'price'      => __( 'Sorted by price: low to high', 'woocommerce' ),
+				'price-desc' => __( 'Sorted by price: high to low', 'woocommerce' ),
+			)
+		);
+		$orderedby                 = isset( $catalog_orderedby_options[ $orderby ] ) ? $catalog_orderedby_options[ $orderby ] : '';
+		$orderedby								 = is_string( $orderedby ) ? $orderedby : '';
```
Comment (tjcafferkey) [inline plugins/woocommerce/includes/wc-template-functions.php]: I think there is some linting issues with this lint. It uses tabs (instead of spaces) and isn't aligned properly.

File: plugins/woocommerce/includes/wc-template-functions.php (hunk 8 above)
Comment (tjcafferkey) [reply plugins/woocommerce/includes/wc-template-functions.php:1507]: Thanks for the reply @Manussakis. I agree with your explanation, I feel like we have enough safety with this check.

File: plugins/woocommerce/templates/loop/result-count.php [hunk 10]
```diff
@@ -14,26 +14,28 @@
  *
  * @see         https://woocommerce.com/document/template-structure/
  * @package     WooCommerce\Templates
- * @version     3.7.0
+ * @version     9.3.0
```
Comment (tjcafferkey) [inline plugins/woocommerce/templates/loop/result-count.php]: Looks like this needs to be `9.4.0` now?

File: plugins/woocommerce/includes/wc-template-functions.php (hunk 7 above)
Comment (tjcafferkey) [reply plugins/woocommerce/includes/wc-template-functions.php:1491]: Thanks!

File: plugins/woocommerce/includes/wc-template-functions.php (hunk 9 above)
Comment (Manussakis) [reply plugins/woocommerce/includes/wc-template-functions.php]: Fixed [Fix php lint error](https://github.com/woocommerce/woocommerce/pull/50573/commits/98b045e1eb30b7b12172350b82e90e5d8f365edc)

**Comment by Manussakis** [comment]
@tjcafferkey I have addressed your feedback. This PR is ready now for another round of code review. Thanks!

@dkotter @qasumitbagthariya  I don't believe a new QA by 10up is necessary as the changes were small refactors.

**Comment by tjcafferkey** [comment]
Thanks for this @Manussakis, just a few questions regarding the testing steps:

#### Testing product catalog with pagination.

> 3. Verify the sorting status message is announced once the page loads.
> 4. Verify the sorting status message is not announced when products are sorted by the default option once the page loads.

#### Testing product catalog with once page.

> 3. Verify the sorting status message is announced once the page loads.
> 4. Verify the sorting status message is not announced when products are sorted by the default option once the page loads.

On both of these steps the sorting message is announced (Firefox + VoiceOver) unless I am misunderstanding the steps.

#### Testing product catalog with one product

> 2. The sorting status message should never be announced since the sort action takes no effect if there is only one product in the catalog once the page loads.

The sorting message is announced here? When I load the page it cycles through the page elements and reads out the sorting option.

https://github.com/user-attachments/assets/3b8dca46-ba1b-4325-9a2e-96ed87f1d5d1

_For some reason the sound isn't working for the recording but when its highlighting the select box at 45 seconds, it reads out the sorting option._

**Comment by Manussakis** [comment]
@tjcafferkey Thanks for testing it.
I believe your question is similar to the @qasumitbagthariya 's one: https://github.com/woocommerce/woocommerce/pull/50573#issuecomment-2295366091

Please, read my response here: https://github.com/woocommerce/woocommerce/pull/50573#issuecomment-2297526814

Thanks!

**Comment by jeffpaul** [comment]
@tjcafferkey if things look good to you here then I think we're good to merge to Woo core yeah?

**Comment by tjcafferkey** [comment]
This looks good and tests well, thanks for the feedback on that testing issue. Just updated with latest trunk in the hope of satisfying some failing CI tasks which appeared unrelated.

**Review by tjcafferkey — APPROVED** [review]

**Comment by tjcafferkey** [comment]
Thanks for your contribution @Manussakis 🎉

**Comment by Manussakis** [comment]
> Thanks for your contribution @Manussakis 🎉

Thanks!!
