### PR TITLE
Also consider refunded item quantity while increasing stock.

### LINKED ISSUE #24489: Inventory decreased when update button is clicked after partial refund
**Describe the bug**
As the title states, inventory is decreased by the qty refunded when the update button is clicked after a partial refund has been completed. Navigating away then back yields the same result. This does not happen on a full refund.

**To Reproduce**
1. Click on Refund and select less than full Qty on line item
2. Click Refund manually
3. Click Update button (with or without changing status)
4. Order note is created stating Adjusted stock by the qty of refund and a quick check of product inventory shows qty reduced back down to pre-refund level.

**Screenshots**
Screenshot from 2019-08-24 14-38-10

**Expected behavior**
Clicking on update button should not reduce stock of a partially refunded line item after a partial refund has been applied.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Wordpress Environment**
<details>
`
### WordPress Environment ###

WordPress address (URL): https://redacted.mystagingwebsite.com
Site address (URL): https://redacted.mystagingwebsite.com
WC Version: 3.7.0
REST API Version: ✔ 1.0.2
Log Directory Writable: ✔
WP Version: 5.2.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: –
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.10 (Debian)
PHP Version: 7.3.6-1+0~20190531112546.39+jessie~1.gbp6131b7
PHP Post Max Size: 35 MB
PHP Time Limit: 60
PHP Max Input Vars: 2500
cURL Version: 7.38.0
OpenSSL/1.0.1t

SUHOSIN Installed: –
MySQL Version: 5.6.44-86.0
Max Upload Size: 35 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.6.5
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Total Database Size: 3.28MB
Database Data Size: 2.02MB
Database Index Size: 1.26MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 1.05MB + Index: 0.02MB + Engine InnoDB
wp_postmeta: Data: 0.16MB + Index: 0.11MB + Engine InnoDB
wp_posts: Data: 0.13MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (2) ###

WooCommerce Admin: by WooCommerce – 0.17.0
WooCommerce: by Automattic – 3.7.0

### Inactive Plugins (4) ###

Capability Manager Enhanced: by PublishPress – 1.7.5
FedEx WooCommerce Extension (BASIC): by PluginHive – 2.1.5 – Not tested with the active version of WooCommerce
Pacific Color Add-on Plugin: by  – 1.6
Query Monitor: by John Blackbourn – 3.3.7

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #8 - /shop
Cart: #9 - /cart
Checkout: #10 - /checkout
My account: #11 - /my-account
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 2.5.3
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 0
Oldest: –
Newest: –

Pending: 10
Oldest: 2019-07-15 07:40:46 -0700
Newest: 2019-08-24 14:19:58 -0700

Canceled: 0
Oldest: –
Newest: –

In-progress: 0
Oldest: –
Newest: –

Failed: 0
Oldest: –
Newest: –

`
</details>

### PR DESCRIPTION
**Pull request by vedanshujain**
### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

When updating an order, we call `wc_maybe_adjust_line_item_product_stock` to see if any item stock needs adjusting. We were not considering if an item has been refunded, which was causing incorrect stock adjustments.
This fix also takes in to account that an order has been refunded partially or fully.

Fixes #24489

### How to test the changes in this Pull Request:

See #24489

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully run tests with your changes locally?

### Changelog entry

> Fix - Also consider refunded item when updating order and adjusting stocks.

### CODE REVIEW

File: includes/admin/wc-admin-functions.php [hunk 1]
```diff
@@ -214,21 +214,27 @@ function wc_maybe_adjust_line_item_product_stock( $item, $item_quantity = -1 ) {
...
 
 	if ( is_wp_error( $new_stock ) ) {
 		return $new_stock;
 	}
 
-	$item->update_meta_data( '_reduced_stock', $item_quantity );
+	$item->update_meta_data( '_reduced_stock', $item_quantity + $refunded_item_quantity );
 	$item->save();
 
+	if ( 0 === $diff ) {
```
Comment (kloon) [inline includes/admin/wc-admin-functions.php]: Perhaps better to move this above the update meta call as if there is no difference no stock should be adjusted?

**Review by kloon — CHANGES_REQUESTED** [review]

File: includes/admin/wc-admin-functions.php (hunk 1 above)
Comment (vedanshujain) [reply includes/admin/wc-admin-functions.php]: you still need to adjust `_reduced_stock` in line 231, so we cannot move it above (even if diff is 0).

Comment (kloon) [reply includes/admin/wc-admin-functions.php]: Not sure I understand why it needs to adjust the meta value when no stock adjustment was made? You have the following statement which does the actual stock adjustment

```
if ( $diff < 0 ) {
		$new_stock = wc_update_product_stock( $product, $diff * -1, 'increase' );
	} elseif ( $diff > 0 ) {
		$new_stock = wc_update_product_stock( $product, $diff, 'decrease' );
	}
```
If $diff is 0 not adjust is made, yet you are updating the _reduced_stock meta value even if no adjustment was made.

Comment (vedanshujain) [reply includes/admin/wc-admin-functions.php]: Ah you are right, I am presuming that we were updating `_reduced_stock` value in order to maintain consistency, but you don't need to when the diff is 0. 

Updating to return early when diff is 0.

**Review by kloon — APPROVED** [review]
LGTM now!
