### PR TITLE
Make the price filter widget tax aware redux

### LINKED ISSUE #21203: Price filtering min/max issue with tax exclusive prices
**Describe the bug**
I've tested the current code and it seems that both "min" and "max" do not work properly in price filtering.

Inserting prices excluding tax
Showing prices including tax

Currently I have a category which has prices (without tax) from 227.55 to 1748.25. The price filter range widgets show range from 227 to 1749.
Tax is 20% to all products, so it would be 273.06 and 2097.9 accordingly.

When I submit price filter form without changing min/max values, so it would include full range (227-1749 via $_GET), price filter query sets SQL query as:
`( ( wp_postmeta.meta_key = '_price'
AND CAST(wp_postmeta.meta_value AS DECIMAL(10,2)) BETWEEN '272.4' AND '1399.2' ) )`

Minimum in 227 + 20% = 272.4, but as prices are entered without tax, it should be left as it, without any calculations. Not sure where the max value came, but here applies the same as min. So, I removed completely the extra calculation from `wc_get_min_max_price_meta_query()` and it now worked as supposed to:
https://github.com/woocommerce/woocommerce/blob/master/includes/wc-product-functions.php#L787-L807

After that, the query was:
`( ( wp_postmeta.meta_key = '_price'
AND CAST(wp_postmeta.meta_value AS DECIMAL(10,2)) BETWEEN '227' AND '1749' ) )`

Now both, minimum and maximum priced products were visible.

However, a completely different issue remains: price filter widget ranges are showing tax exclusive prices, so it is not respecting the settings.

I tried a quick fix to add taxes in price filter widget, and then in `wc_get_min_max_price_meta_query()` remove taxes for DB query, but tax calculation went wrong. So I tweaked tax calculation in 32ca6c7, but that didn't work as expected.

Related to PR #18174 and issue #18170.

**To Reproduce**
1. Insert prices excluding tax
2. Show prices including tax
3. Set up tax 20% for all products
4. Add price filtering widget

### PR DESCRIPTION
**Pull request by mikejolley**
Supercedes #21942
Closes #21203

#21942 semi-solved the problem but relied on some extra inputs to see which slider was used. We have price slider query dedicated methods so we can handle the tax subtraction there instead.

This PR:
- Moves the logic from #21942 to a more appropriate location
- Implements https://github.com/woocommerce/woocommerce/pull/22533
- Uses standard tax class only for the inc tax calculation, with a filter if needed. We cannot guess which tax class to use so standard makes the most sense.
- Implements a step of 10 so the ranges increment +10 at a time. This will produce more cache hits plus makes it slightly more user friendly as it can be hard to get a specific price with +1 increments.

**How to test the changes in this Pull Request:**

1. Enable taxes on your store and set a tax rate
2. Choose to enter product prices excl tax
3. Choose to display product prices incl tax on the frontend.
4. Add a Price filter widget and view the page with the widget.
5. Ensure that the filter range matches the range of the prices incl tax in your catalog.
6. Do a filter search with a price range and check that it returns the correct products.

> Fix - Make price filter widget tax aware when you have excl prices entered but show prices incl of tax.

### CODE REVIEW

File: includes/widgets/class-wc-widget-price-filter.php [hunk 1]
```diff
@@ -68,23 +68,45 @@ public function widget( $args, $instance ) {
...
+		// Check to see if we should add taxes to the prices if store are excl tax but display incl.
+		$tax_display_mode = get_option( 'woocommerce_tax_display_shop' );
+
+		if ( wc_tax_enabled() && ! wc_prices_include_tax() && 'incl' === $tax_display_mode ) {
+			$tax_class = apply_filters( 'woocommerce_price_filter_widget_tax_class', '' ); // Uses standard tax class.
+			$tax_rates = WC_Tax::get_rates( $tax_class );
 
-		if ( $min === $max ) {
+			if ( $tax_rates ) {
+				$min_price += WC_Tax::get_tax_total( WC_Tax::calc_exclusive_tax( $min_price, $tax_rates ) );
```
Comment (peterfabian) [inline includes/widgets/class-wc-widget-price-filter.php]: Similarly to adjusting max in `get_tax_query`, maybe we should not adjust min here in case we have low priced products with zero/reduced tax rate?

File: includes/class-wc-query.php [hunk 2]
```diff
@@ -679,7 +679,33 @@ public function get_tax_query( $tax_query = array(), $main_query = false ) {
...
+				$tax_class = apply_filters( 'woocommerce_price_filter_widget_tax_class', '' ); // Uses standard tax class.
+				$tax_rates = WC_Tax::get_rates( $tax_class );
+
+				if ( $tax_rates ) {
+					$current_min_price -= WC_Tax::get_tax_total( WC_Tax::calc_inclusive_tax( $current_min_price, $tax_rates ) );
+					$current_max_price -= WC_Tax::get_tax_total( WC_Tax::calc_inclusive_tax( $current_max_price, $tax_rates ) );
+				}
+			}
+
+			$step              = max( apply_filters( 'woocommerce_price_filter_widget_step', 10 ), 1 );
```
Comment (peterfabian) [inline includes/class-wc-query.php]: Great to have a filter here, I think a lot of people are using WC for currencies like VND where step 10 is sth like 1/100 of US cent.

File: includes/wc-product-functions.php [hunk 3]
```diff
@@ -793,37 +793,19 @@ function wc_get_product_visibility_options() {
...
-
-			if ( $tax_rates ) {
-				$class_min = $min + WC_Tax::get_tax_total( WC_Tax::calc_exclusive_tax( $min, $tax_rates ) );
-				$class_max = $max - WC_Tax::get_tax_total( WC_Tax::calc_exclusive_tax( $max, $tax_rates ) );
-			}
-		}
-
-		$min = $class_min;
-		$max = $class_max;
-	}
```
Comment (peterfabian) [inline includes/wc-product-functions.php]: This function seems to be used in REST API, so it will change how price filters work via the API when searching for products. Is that not a concern for compatibility?

**Review by peterfabian — COMMENTED** [review]
I think this works quite nicely. Just a couple of notes (plus needs an update from master).

File: includes/class-wc-query.php [hunk 4]
```diff
@@ -679,7 +679,33 @@ public function get_tax_query( $tax_query = array(), $main_query = false ) {
...
+			 * Adjust if the store taxes are not displayed how they are stored.
+			 * Kicks in when prices excluding tax are displayed including tax.
+			 */
+			if ( wc_tax_enabled() && 'incl' === get_option( 'woocommerce_tax_display_shop' ) && ! wc_prices_include_tax() ) {
+				$tax_class = apply_filters( 'woocommerce_price_filter_widget_tax_class', '' ); // Uses standard tax class.
+				$tax_rates = WC_Tax::get_rates( $tax_class );
+
+				if ( $tax_rates ) {
+					$current_min_price -= WC_Tax::get_tax_total( WC_Tax::calc_inclusive_tax( $current_min_price, $tax_rates ) );
+					$current_max_price -= WC_Tax::get_tax_total( WC_Tax::calc_inclusive_tax( $current_max_price, $tax_rates ) );
```
[the remark this answers is not in the document]
Comment (mikejolley) [reply includes/class-wc-query.php]: Yeah and the reverse of that is, if it's not reduced you'll see results outside of your chosen bracket. Drawbacks to both but no workable solution unfortunetely.

File: includes/widgets/class-wc-widget-price-filter.php (hunk 1 above)
Comment (mikejolley) [reply includes/widgets/class-wc-widget-price-filter.php]: See comment above.

File: includes/wc-product-functions.php (hunk 3 above)
Comment (mikejolley) [reply includes/wc-product-functions.php]: It's possible however the REST API doens't need to adjust for tax display since the REST API returns actual stored prices. With this in mind, it probably makes more sense in REST API to bypass the old logic.

**Review by peterfabian — APPROVED** [review]
I think this change should work fine.

**Comment by mikejolley** [comment]
@peterfabian Famous last words but Ill take it!
