### PR TITLE
Fix: order being incorrectly changed to "Completed"

### LINKED ISSUE #62173: Troubleshooting intermittent pending -> completed status switch on orders
Hello devs,

In 10505505-zen we're seeing **intermittent** Pending -> Completed status switch instead of "processing" for shippable items. (Tests done via WC Stripe)

On investigating further - we found that typically wc_get_order would have items as

```
    [items:protected] => Array
        (
        )
```

if a plugin say Stripe for example calls `$order->get_items( [ 'line_item', 'fee' ] ) );` that would populate the items within $order object.

```
    [items:protected] => Array
        (
            [line_items] => Array
                (
                    [29] => WC_Order_Item_Product Object
...
```

This means that when `needs_processing()` is called when it is the time to switch order status, it checks

```
			if ( count( $this->get_items() ) > 0 ) {
				foreach ( $this->get_items() as $item ) {
```

Typically this would either hit items in object or pull items from the DB.

In merchant's case the affected orders seem to have the below when `needs_processing` is called

```
    [items:protected] => Array
        (
            [line_items] => Array
                (
                )

            [tax_lines] => Array
                (
                )

            [shipping_lines] => Array
                (
                )

            [fee_lines] => Array
                (
                )

            [coupon_lines] => Array
                (
                )

        )
```

This means that the condition here will evaluate false [https://github.com/woocommerce/woocommerce/blob/d9e133e45a817be2b000a105cc81f8dd8404e8cc/plugins/woocommerce/includes/abstracts/abstract-wc-order.php#L924](https://github.com/woocommerce/woocommerce/blob/d9e133e45a817be2b000a105cc81f8dd8404e8cc/plugins/woocommerce/includes/abstracts/abstract-wc-order.php#L924)

and no items will be returned. We've verified the DB SQL queries - no modification is done on the order items table after insertion. We also verified calls to get_items() indeed returns valid values initially but suddenly turns into above blank arrays in between somewhere and needs_processing() ends up reading that.

**Question**: Under what cases $order would have set  \~\~`~~\~\~line_items\~\~~~` etc..but blank values? I think that's after $order->save() or something calling get_items() when actually no items are present in the order  - however in this case items stay intact throughout the process.

**New Update**: (please disregard the question above)

There is at least one scenario where this can happen.

* Imagine something hooks into woocommerce_new_order early and reads the order via wc_get_order
* By this time caches would have been cleared so the next wc_get_order would push order to cache however in case HPOS sync is enabled a backfill operation might be performed which can call [get_data](https://github.com/woocommerce/woocommerce/blob/b302da82e12e40b56dff74a569d992517ba7617c/plugins/woocommerce/includes/class-wc-order.php#L540) and that fills in the order with blank items (since save_items() is yet to be called to insert items to DB)
* Now with the below data, order is pushed to memory cache

```
    [items:protected] => Array
        (
            [line_items] => Array
                (
                )

            [tax_lines] => Array
                (
                )

            [shipping_lines] => Array
                (
                )

            [fee_lines] => Array
                (
                )

            [coupon_lines] => Array
                (
                )

        )
```

* In typical scenarios - Order attribution logic will wipe off order cache again so there would be fresh reads further anywhere - thus correct line items.
* However if Order attribution is disabled - the cached order will hit various places resulting no line items and causing issues at various logic - eg needs_processing returning false.
* This is intermittent because I think backfill is not performed in all scenarios

The key point here is $order->get_data(); or $order->get_items(); might get called during HPOS read() operation and end up pushing blank item lines to memory when items are yet to be added to DB. Above is one such scenario where HPOS sync is capable of doing that.

**To Replicate**

* Enable HPOS
* Have classic cart/checkout
* Disable Order Attribution
* Enable COGs feature
* Deploy the snippet below

```
add_action( 'woocommerce_new_order', 'kaushikdebug', 10, 2);

function kaushikdebug( $order_id, $order ) {
		
	$order = wc_get_order($order_id); // causes cache set() and also triggers HPOS read_multiple()
	
}

add_action('woocommerce_load_order_cogs_value', 'cogssimulate',10,2);
function cogssimulate($val, $order){
	// we hook into COGs filter because backfill logic is difficult to trigger during checkout ajax
	$order->get_data();
	return $val;
}
```

* Place order via WC Stripe UPE (for a shippable item)
* See order complete instead of "processing"

### PR DESCRIPTION
**Pull request by Konamiman**
### Changes proposed in this Pull Request:

This pull request fixes an issue where orders were intermittently go from "Pending" directly to "Completed" instead of "Processing" for shippable items. This was caused by a race condition where `get_items()` was called on an order object before items were saved to the database, causing empty items to be cached in the order object's `$this->items` array.

`get_items()` (in `abstract-wc-order.php`) has this:

```php
if ( ! isset( $this->items[ $group ] ) ) {
    $this->items[ $group ] = array_filter( $this->data_store->read_items( $this, $type ) );
}
```

The `isset()` check returns `true` for empty arrays. Once `$this->items['line_items']` is set to `[]`, subsequent calls won't re-read from DB.

The complete race confition sequence is:

1. Order is created via `$order->save()`.
2. `create()` in datastore calls `persist_save()` which saves order to database (but NOT items yet).
3. During `persist_save()`, if HPOS sync is enabled, backfill calls `wc_get_order()` and `get_data()` → `get_items()` - items are NOT in the database yet → empty items are cached.
4. `persist_save()` calls `clear_caches()` - removes order from OrderCache.
5. `woocommerce_new_order` action fires.
6. If a hook calls `wc_get_order()`, a NEW order object is created and cached - items STILL not in database.
7. If something triggers `get_items()` on this cached order (e.g., COGs filter calling `get_data()`), empty items are primed.
8. `create()` returns, `save_items()` is called - items saved to database.
9. Later, `wc_get_order()` returns the cached order with stale empty items.
10. `needs_processing()` returns `false` because it sees no items.
11. Order goes to "Completed" instead of "Processing".

Closes #62173.

### How to test the changes in this Pull Request:

1. Enable HPOS with backfill, enable Cost of Goods Sold, and disable the order attribution feature (which clears cache and thus masks the bug) in WooCommerce - Settings - Advanced - Features.
2. Enable the "Direct Bank Transfer" payment method.
3. Add the following snippet to your server:

```php
// Simulate the race condition - fetch order before items are saved
add_action( 'woocommerce_new_order', function( $order_id, $order ) {
    $order = wc_get_order($order_id);
}, 10, 2);

// COGs filter triggers get_data() which calls get_items() - primes empty items
add_action('woocommerce_load_order_cogs_value', function($val, $order) {
    $order->get_data();
    return $val;
}, 10, 2);

// Force payment_complete to trigger needs_processing check
add_action( 'woocommerce_checkout_order_processed', function( $order_id, $posted_data, $order ) {
    $order->payment_complete();
}, 100, 3 );
```

4. Go to the store and place an order for a shippable product.
5. Go to the orders list in admin and verify that the order is in "Processing" state (without this fix it would be in "Completed" state).

### Milestone

- [x] Automatically assign milestone for the **[next WooCommerce version](../blob/trunk/plugins/woocommerce/woocommerce.php#L6)**

> **Note:** Check the box above to have the milestone automatically assigned when merged.
> Alternatively (e.g. for point releases), manually assign the appropriate milestone.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Fix: order being incorrectly changed to "Completed"</summary>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce/tests/php/src/Internal/DataStores/Orders/OrdersTableDataStoreTests.php [hunk 1]
```diff
@@ -3926,4 +3926,67 @@ public function test_loading_order_deleted_from_posts_table() {
...
+	 * @testdox needs_processing returns correct result when order cache is invalidated after items are saved.
+	 *
+	 * This test verifies the fix for a race condition bug (GitHub issue #62173) where:
+	 * 1. An order is created
+	 * 2. get_items() is called before items are saved (e.g., during HPOS backfill), caching empty items
+	 * 3. Items are then saved to DB
+	 * 4. The order cache is invalidated so new wc_get_order() calls get fresh data
+	 * 5. needs_processing() correctly returns true for physical products
+	 */
+	public function test_needs_processing_with_stale_cached_empty_items() {
```
Comment (prettyboymp) [inline plugins/woocommerce/tests/php/src/Internal/DataStores/Orders/OrdersTableDataStoreTests.php]: This test passes with and without the other changes.  Can you make sure it triggers the issue for the scenario we're attempting to fix?

**Review by prettyboymp — CHANGES_REQUESTED** [review]
@Konamiman, I'm trying to fully understand the underlying issue, but am having trouble.  The added unit test doesn't trigger the bug making it harder to understand.

I'm not seeing how removing the Order from OrderCache would affect the items being cached empty.  The only thing I see off hand is that the `::__clone()` method doesn't take care of cloning attached objects, like items ore metadata.  That may be the underlying cause, but its hard to tell without the test triggering the bug.

File: plugins/woocommerce/tests/php/src/Internal/DataStores/Orders/OrdersTableDataStoreTests.php (hunk 1 above)
Comment (Konamiman) [reply plugins/woocommerce/tests/php/src/Internal/DataStores/Orders/OrdersTableDataStoreTests.php]: True. I have updated the test.

Comment (prettyboymp) [reply plugins/woocommerce/tests/php/src/Internal/DataStores/Orders/OrdersTableDataStoreTests.php]: The updated test still doesn't test against the original issue reported in #62173.  It now just verifies that `Order::add_item()` triggers removal of the order from cache - testing the proposed change, not that it fixes the issue.

**Review by prettyboymp — CHANGES_REQUESTED** [review]
@Konamiman, digging into this more and understanding the underlying issue better, I think we need to fix the behavior of the `woocommerce_load_order_cogs_value` hook.  Because it ends up being run during the construction and hydration process of an Order instance, it gives extensions opportunities to put the Order object in an incomplete or modified state prior to caching by making changes to the Order instance via that hook.  

I think both `woocommerce_load_order_cogs_value` and `woocommerce_hpos_post_record_migrated_on_read` should probably pass a clone of the order to avoid an order instance that is being constructed for cache getting modified.

**Comment by Konamiman** [comment]
> I think both woocommerce_load_order_cogs_value and woocommerce_hpos_post_record_migrated_on_read should probably pass a clone of the order

Wouldn't that be a breaking change? Clients of these hooks might be modifying the order (even if they shouldn't), but now they would be modifying a clone that will be discarded later instead.

Also even if we go with this approach, probably we would still need to keep the cache invalidation part, in case there are other "offending" hooks that we are missing.

**Comment by Konamiman** [comment]
> The updated test still doesn't test against the original issue

Fair point, I have updated the test.

**Review by prettyboymp — APPROVED** [review]
We shouldn't be passing a partially hydrated WC_Data object into hooks, but that isn't something we can easily change now.

I would also rather the `WC_Abstract_Order` class not directly call the OrderCache and have the datastore handle it, but `::save_items()` saves items individually instead of as a set making that difficult.  The open hierarchy of datastores also makes that difficult to change.

Having said all that, I'm approving this fix as is.  I don't see a better alternative without getting into backward compatibility concerns.

File: plugins/woocommerce/includes/abstracts/abstract-wc-order.php [hunk 2]
```diff
@@ -303,6 +304,14 @@ protected function save_items() {
 
 		if ( $items_changed ) {
 			delete_transient( 'wc_order_' . $this->get_id() . '_needs_processing' );
+
+			// Invalidate the order cache to prevent stale item data.
+			// This fixes a race condition where get_items() may have been called
+			// before items were saved, caching empty items arrays.
+			// See https://github.com/woocommerce/woocommerce/issues/62173.
+			if ( OrderUtil::orders_cache_usage_is_enabled() ) {
+				wc_get_container()->get( OrderCache::class )->remove( $this->get_id() );
```
Comment (Nikschavan) [inline plugins/woocommerce/includes/abstracts/abstract-wc-order.php:313]: This line has PHPStan error `Cannot call method remove() on mixed.` - For this PR IMO it would be Ok to push this error to baseline using `composer phpstan:baseline`, I can create a separate task to fix the return type of container so that all these ignored errors get fixed

Comment (Nikschavan) [reply plugins/woocommerce/includes/abstracts/abstract-wc-order.php:313]: This is now fixed with - https://github.com/woocommerce/woocommerce/pull/62301
