### PR TITLE
Fix TS issues within components package

### LINKED ISSUE #54159: Fix Typescript errors from `packages/js/components`
**Description**

As part of the React 18 PR updates we have disabled the TS errors in the components package.

The goal of this issue is to fix these TS errors and set `noCheck` in the TSConfig back to `false`.

Related issue: #53943

### PR DESCRIPTION
**Pull request by louwie17**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

This PR re-enables the type checking in the component package and fixes all the errors in relation to the React 18 update.
95% of the changes are only type changes and shouldn't affect functionality. There were a few places where this was not entirely possible. For those cases I added additional test instructions below to test these components, these changes were only internal ( see test instructions for date time picker, select tree control, search / select control, sortFillByOrder, and tooltip ).

Closes #54159

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Run `pnpm --filter=@woocommerce/components build` and make sure it builds correctly ( no errors ).
2. Run `pnpm --filter=@woocommerce/plugin-woocommerce build` and make sure it builds correctly.
3. Test a couple of the components that included more changes, details below:

**DateTimePickerControl**
1. Enable the new product editor under **WooCommere > Settings > Advanced > Features**
2. Go to **Products > Add New**
3. Set a regular price and sale price and enable **Schedule sale**
4. Select a date/time in the dropdowns and make sure the work correctly, you can also type and see if the dropdown gets updated.

**SelectTreeControl**
1. In the new product editor go to the **Organization** tab and click on the **Category** input field
2. The dropdown should close correctly when clicked outside of it, and not when clicking inside of it ( like selecting an item or expanding a parent item ).
3. Click the **Add new** and make sure the parent **Parent category** works well within the Modal as well.

**Search / SelectControl**
1. Go to **Analytics > Products**
2. Click the **Show** dropdown and select both the **single product** and **comparison**
3. Search and select one or multiple products and remove them again. The search/select control should work correctly.
4. Go to **Analytics > Orders** and select the **Advanced filters** from the **Show** dropdown
5. And add a couple filters like **Product Attribute**
6. Click **Filter** the data should be updated, now hard refresh the page, the filter should still be shown.

**Tooltip**
1. Go to the new product editor again -> **Products > Add new**
2. Click on the Question mark icon beside each icon title ( see image below ) and click outside of it again it should close correctly.
3. Same if you open one and directly click on another tooltip ( a header of another section ).

Screenshot 2025-01-06 at 3 42 26 PM

**sortFillsByOrder**
1. Go to the new product editor again -> **Products > Add new**
2. Open your console and paste this in your console:
```
wp.plugins.registerPlugin( 'your-prefix-more-menu-item', {
    scope: 'woocommerce-product-block-editor',
    render: function() {
        return wp.element.createElement(
            wp.element.Fragment,
            {},
            wp.element.createElement(
                wc.productEditor.__experimentalWooProductMoreMenuItem,
                {
                    order: 100,
                },
                wp.element.createElement(
                    wp.element.Fragment,
                    {},
                    wp.element.createElement(
                        wp.components.MenuItem,
                        {},
                        'My custom menu item'
                    )
                )
            ),
        );
    }
} );
```
3. Open the more menu by clicking the 3 dots in the top right, this should show the **My Custom Menu Item** under the **Turn off the new product form**
4. Now paste this code ( note I changed the `order` to 0:
```
wp.plugins.registerPlugin( 'your-prefix-more-menu-item-2', {
    scope: 'woocommerce-product-block-editor',
    render: function() {
        return wp.element.createElement(
            wp.element.Fragment,
            {},
            wp.element.createElement(
                wc.productEditor.__experimentalWooProductMoreMenuItem,
                {
                    order: 0,
                },
                wp.element.createElement(
                    wp.element.Fragment,
                    {},
                    wp.element.createElement(
                        wp.components.MenuItem,
                        {},
                        'My custom menu item 2'
                    )
                )
            ),
        );
    }
} );
```
5. Open the more menu again, this should show the **My Custom Menu Item 2** at the very top now.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

File: packages/js/components/src/date-time-picker-control/date-time-picker-control.tsx [hunk 1]
```diff
@@ -413,23 +412,26 @@ export const DateTimePickerControl = forwardRef(
...
-				// it won't be set back to the pre-change value
-				setInputStringAndMaybeCallOnChange(
-					inputControl.current.value,
-					true
-				);
-				onBlurRef.current();
-			}
-		}, [] );
+		const callOnBlurIfDropdownIsNotOpening = useCallback(
+			( willOpen: boolean ) => {
```
Comment (louwie17) [inline packages/js/components/src/date-time-picker-control/date-time-picker-control.tsx:416]: I only added the `boolean` type for `willOpen`

File: packages/js/components/src/experimental-select-tree-control/select-tree.tsx [hunk 2]
```diff
@@ -86,18 +93,22 @@ export const SelectTree = function SelectTree( {
 
 	const selectedItemsFocusHandle = useRef< SelectedItemFocusHandle >( null );
 
-	function isEventOutside( event: React.FocusEvent ) {
+	function isEventOutside( event: React.SyntheticEvent | React.FocusEvent ) {
+		let target: Element | null = event.currentTarget;
+		if ( isBlurEvent( event ) ) {
+			target = event.relatedTarget;
+		}
```
Comment (louwie17) [inline packages/js/components/src/experimental-select-tree-control/select-tree.tsx:100]: Needed this, as the above is called on blur and on focus. The blur event has the `FocusEvent` and thus includes the `relatedTarget`. The focus event only returns `SyntheticEvent` and thus does not have `relatedTarget`, to be specific the `onFocusOutside` -> https://github.com/WordPress/gutenberg/blob/775eed2cb8e480e5978fd888ba8df7a98e7e53f4/packages/components/src/popover/types.ts#L95

File: packages/js/components/src/form/form.tsx [hunk 3]
```diff
@@ -396,8 +435,7 @@ function FormComponent< Values extends Record< string, any > >(
 
 	function getChildren() {
 		if ( typeof children === 'function' ) {
-			const element = children( getStateAndHelpers() );
-			return cloneElement( element );
+			return children( getStateAndHelpers() );
```
Comment (louwie17) [inline packages/js/components/src/form/form.tsx:438]: Removed redundant `cloneElement`

File: packages/js/components/src/product-fields/fields/basic-select-control/render.tsx [hunk 4]
```diff
@@ -21,13 +22,16 @@ const SelectControlField: React.FC< SelectControlFieldProps > = ( {
...
 	return (
-		<SelectControl
-			multiple={ multiple }
-			label={ label }
-			options={ options }
-			onChange={ onChange }
-			value={ value }
-		/>
+		<>
+			{ /* @ts-expect-error wrong type for multiple, should be boolean but explicitly set to true/false */ }
```
Comment (louwie17) [inline packages/js/components/src/product-fields/fields/basic-select-control/render.tsx:26]: I only added the `Fragment` for this comment 🤷‍♂️ 
Annoyingly the `SelectControl` type for `multiple` sets it to `true` or `false` right away which is different from `boolean`.
So I ignored the error for now: https://github.com/WordPress/gutenberg/blob/bd7e9c2ab0c41269e22b4eb4cd2b2afe3fe84e66/packages/components/src/select-control/types.ts#L67

File: packages/js/components/src/product-fields/fields/checkbox/render.tsx [hunk 5]
```diff
@@ -20,7 +20,7 @@ const CheckboxField: React.FC< CheckboxFieldProps > = ( {
 		<CheckboxControl
 			label={ label }
 			onChange={ onChange }
-			selected={ value }
+			checked={ value }
```
Comment (louwie17) [inline packages/js/components/src/product-fields/fields/checkbox/render.tsx:23]: `selected` didn't even exist on `CheckboxControl`. Reason this was never noticed is because we don't use this code. We can actually remove the entire `product-fields` directory, this was also part of the first iteration of the product editor ( pre block editor era ). Will do this as a follow up.

File: packages/js/components/src/search/index.tsx [hunk 6]
```diff
@@ -243,9 +237,12 @@ export class Search extends Component< Props, State > {
...
 	}
 
-	fetchOptions( previousOptions: unknown[], query: string ) {
+	fetchOptions(
+		previousOptions: unknown[],
+		query: string | null
+	): Promise< Option[] > {
 		if ( ! query ) {
-			return [];
+			return Promise.resolve( [] );
```
Comment (louwie17) [inline packages/js/components/src/search/index.tsx:243]: `fetchOptions` expects a return type of a Promise. So I fixed this.

File: packages/js/components/src/select-control/control.tsx [hunk 7]
```diff
@@ -305,7 +305,11 @@ class Control extends Component< Props, State > {
 			selected,
 		} = this.props;
 		const selectedValue =
-			isArray( selected ) && selected.length ? selected[ 0 ].label : '';
+			isArray( selected ) &&
+			selected.length &&
+			typeof selected[ 0 ].label === 'string'
+				? selected[ 0 ].label
+				: '';
```
Comment (louwie17) [inline packages/js/components/src/select-control/control.tsx:312]: `label` can be a ReactElement in this case.

File: packages/js/components/src/image-gallery/image-gallery-toolbar.tsx [hunk 8]
```diff
@@ -132,12 +132,7 @@ export const ImageGalleryToolbar: React.FC< ImageGalleryToolbarProps > = ( {
 				{ ! isCoverItem && (
 					<ToolbarGroup>
 						<ToolbarItem>
-							{ ( toggleProps: {
-								'data-toolbar-item': boolean;
-								ref: React.ForwardedRef<
-									typeof ImageGalleryToolbarDropdown
-								>;
-							} ) => (
+							{ ( toggleProps ) => (
```
Comment (louwie17) [inline packages/js/components/src/image-gallery/image-gallery-toolbar.tsx:135]: `toggleProps` type is now retrieved from the `ToolbarItem` component.

File: packages/js/components/src/tooltip/tooltip.tsx [hunk 9]
```diff
@@ -71,14 +71,13 @@ export const Tooltip: React.FC< TooltipProps > = ( {
 
 				{ isPopoverVisible && (
 					<Popover
-						focusOnMount="container"
+						focusOnMount="firstElement"
```
Comment (louwie17) [inline packages/js/components/src/tooltip/tooltip.tsx]: `true` is for container: https://github.com/WordPress/gutenberg/blob/ca2ee4d6fa8c7044cd1d3045c0985a77659f44fa/packages/components/src/popover/README.md#L142

File: packages/js/components/src/utils.tsx [hunk 10]
```diff
@@ -77,10 +82,18 @@ export { createOrderedChildren };
...
-	const sortedFills = [ ...fills ].sort( ( a, b ) => {
-		return a[ 0 ].props.order - b[ 0 ].props.order;
+	const sortedFills = Children.toArray( fills ).sort( ( a, b ) => {
+		if (
+			typeof a === 'object' &&
+			'key' in a &&
+			typeof b === 'object' &&
+			'key' in b
+		) {
+			return a.props.order - b.props.order;
```
Comment (louwie17) [inline packages/js/components/src/utils.tsx:94]: Reminder to myself: To test this and write some testing instructions for this change.
As this did change from `a[0]` to `a.props`, which in theory should break this functionality, but the typing seems to disagree.

Comment (louwie17) [reply packages/js/components/src/utils.tsx:94]: I updated the test instructions to include this case.
Turns out that the `Children.toArray` actually flattens the fills for us and allows us to get access to the `props` directly.

File: packages/js/components/src/form/form.tsx [hunk 11]
```diff
@@ -123,6 +122,43 @@ export type ConsumerInputProps< Values > = {
...
+	setValues: ( valuesToSet: Values ) => void;
+	handleSubmit: () => unknown;
+	getCheckboxControlProps: (
+		name: string,
+		inputProps?: ConsumerInputProps< Values >
+	) => CheckboxProps< Values, Values[ keyof Values ] >;
+	getInputProps: < P extends keyof Values >(
+		name: P,
+		inputProps?: ConsumerInputProps< Values >
+	) => InputProps< Values, Values[ P ] >;
```
Comment (louwie17) [inline packages/js/components/src/form/form.tsx:144]: Using the `P` here to make sure that `getInputProps` returns the correct value for the passed in parameter.
This means that `getInputProps('name')` will correctly return a string and `getInputProps('count')` will return a `number` ( dependent on the `Values` type of-course ).

File: packages/js/components/src/experimental-select-tree-control/select-tree.tsx (hunk 2 above)
Comment (gigitux) [reply packages/js/components/src/experimental-select-tree-control/select-tree.tsx:100]: Can't we check the `event.type` value? From [this JSFiddle demo](https://jsfiddle.net/ef8bj5c3/), it looks like that works fine.

File: packages/js/components/src/search/index.tsx [hunk 12]
```diff
@@ -243,9 +237,12 @@ export class Search extends Component< Props, State > {
 		return formattedOptions;
 	}
 
-	fetchOptions( previousOptions: unknown[], query: string ) {
+	fetchOptions(
+		previousOptions: unknown[],
+		query: string | null
+	): Promise< Option[] > {
```
Comment (gigitux) [inline packages/js/components/src/search/index.tsx]: NIT: We can remove `:Promise< Option[] >`

File: packages/js/components/src/search/index.tsx [hunk 13]
```diff
@@ -263,7 +260,10 @@ export class Search extends Component< Props, State > {
 		} );
 	}
 
-	updateSelected( selected: Option[] ) {
+	updateSelected( selected: Option[] | string ) {
+		if ( ! Array.isArray( selected ) ) {
+			return;
+		}
```
Comment (gigitux) [inline packages/js/components/src/search/index.tsx]: I would refactor this code, moving this logic outside of `updateSelected` (before invoking the method)

**Review by gigitux — COMMENTED** [review]
Thanks for working on this PR! I tested all the functionality and I didn't find any regression! I left few comments! Let me know what you think about.

File: packages/js/components/src/search/index.tsx (hunk 12 above)
Comment (louwie17) [reply packages/js/components/src/search/index.tsx]: Aaah yeah, good suggestion 👍

File: packages/js/components/src/search/index.tsx (hunk 13 above)
Comment (louwie17) [reply packages/js/components/src/search/index.tsx]: Updated: https://github.com/woocommerce/woocommerce/pull/54197/commits/c9a0d8ee450c2630abdb640764dfe9a3c49a0e52

File: packages/js/components/src/experimental-select-tree-control/select-tree.tsx (hunk 2 above)
Comment (louwie17) [reply packages/js/components/src/experimental-select-tree-control/select-tree.tsx:100]: Hmm yeah that does work and I updated it: https://github.com/woocommerce/woocommerce/pull/54197/commits/218601a3384a8871c281a97114febd9e60cbdba0
but the one downside is that it doesn't auto select the type because of this. So I still need the `isBlurEvent` function using the `is`. I made use of `type` within there.

Comment (gigitux) [reply packages/js/components/src/experimental-select-tree-control/select-tree.tsx:100]: Yeah, type guards for the win!

**Review by gigitux — APPROVED** [review]
Awesome work! LGTM! :shipit:
