### PR TITLE
Fix the permissions check for customer downloads REST API endpoints.

### LINKED ISSUE #27109: REST API: customer download permission check applies wrong ID function
**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
It's a little subtle and hard to describe, as it usually wouldn't be triggered.

In v4.3.1 the `woocommerce-rest-api` package's `WC_REST_Customer_Downloads_V1_Controller->get_items_permissions_check` has these lines:

```
		if ( ! wc_rest_check_user_permissions( 'read', $customer->get_id() ) ) {
			return new WP_Error( 'woocommerce_rest_cannot_view', __( 'Sorry, you cannot list resources.', 'woocommerce' ), array( 'status' => rest_authorization_required_code() ) );
		}
```

However, `get_id()` doesn't exist for `WP_User`.  Usually not noticeable, but in custom situations (e.g. when hooking into the filter `woocommerce_rest_check_permissions`) this does have an impact, as `wc_rest_check_user_permissions` receives a `object_id=false`, hence the filter doesn't receive the user ID at all and no further checks can be made.

Changing the parameter to `$customer->ID` works.

I'd like to fix it myself, but the dev barrier is a little high for such small fixes. I hope someone more experienced will pick this up.

**Expected behavior**
`woocommerce_rest_check_permissions` receiving the correct `object_id`, i.e. the ID of the authenticated user.

**Actual behavior**
`woocommerce_rest_check_permissions` receives `object_id=false`, regardless which user authenticates.

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Register a filter for `woocommerce_rest_check_permissions`, e.g.:
```
add_filter( 'woocommerce_rest_check_permissions', array( $this, 'changeWooPermissions') , 10, 4 )

function changeWooPermissions( $permission, $context, $object_id, $type ) {
    if ($type === 'user') {
        $current_user_id = get_current_user_id();
        return $current_user_id === $object_id;
    }
     return $permission;
 }
```
2. Hit the REST endpoint for the user ID you're authenticating the request with, e.g. `http://domain.com/wp-json/wc/v3/customers/<user_id>/downloads`
3. Expected would be a successful request, however, it's throwing a 403 `woocommerce_rest_cannot_view`.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report we won't be able to fully evaluate this issue.
<details>

```
### WordPress Environment ###

WordPress address (URL): http://localhost:8080
Site address (URL): http://localhost:8080
WC Version: 4.3.1
REST API Version: ✔ 1.0.10
WC Blocks Version: ✔ 2.7.2
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.3.1
Log Directory Writable: ✔
WP Version: 5.4.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.38 (Debian)
PHP Version: 7.2.32
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.64.0
OpenSSL/1.1.1d

SUHOSIN Installed: –
MySQL Version: 5.7.30
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.3.1
WC Database Prefix: wp_
Total Database Size: 11.00MB
Database Data Size: 6.59MB
Database Index Size: 4.41MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta_geo: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_failed_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailchimp_carts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 3.41MB + Index: 0.08MB + Engine InnoDB
wp_postmeta: Data: 0.09MB + Index: 0.03MB + Engine InnoDB
wp_postmeta_geo: Data: 0.09MB + Index: 0.07MB + Engine MyISAM
wp_posts: Data: 0.05MB + Index: 0.06MB + Engine InnoDB
wp_pp_builder_widget: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pp_edit_profile_builder: Data: 0.03MB + Index: 0.00MB + Engine InnoDB
wp_pp_login_builder: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
wp_pp_melange: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pp_passwordless: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pp_password_reset_builder: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
wp_pp_profile_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_pp_registration_builder: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pp_revisions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pp_user_profile_builder: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_queue: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta_geo: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.11MB + Index: 0.08MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_usermeta_geo: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 1.52MB + Index: 2.81MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wpmailsmtp_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wrc_caches: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wrc_relations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB

### Post Type Counts ###

attachment: 19
page: 14
post: 5
product: 6
product_variation: 6
revision: 2
wpcf7_contact_form: 1

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (11) ###

Akismet Anti-Spam: by Automattic – 4.1.6
Boundless WC REST Payment: by SK8Tech – 1.4.1 – Installed version not tested with active version of WooCommerce 4.3.1
Boundless: by Nils Nolde – 0.0.1
Contact Form 7: by Takayuki Miyoshi – 5.2
Stop Generating Unnecessary Thumbnails: by codexpert – 3.0.4
ProfilePress - Email Confirmation: by Collins Agbonghama – 1.3
ProfilePress: by ProfilePress Team – 2.9.1
Simple-JWT-Login: by Nicu Micle – 2.2.5
WooCommerce Stripe Gateway: by WooCommerce – 4.5.0 – Installed version not tested with active version of WooCommerce 4.3.1
WooCommerce: by Automattic – 4.3.1
WP Mail SMTP: by WPForms – 2.2.1

### Inactive Plugins (0) ###


### Settings ###

API Enabled: ✔
Force SSL: –
Currency: EUR (€)
Currency Position: left
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: variable (variable)
Taxonomies: Product Visibility: outofstock (outofstock)
Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #6 - /shop/
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Nineteen
Version: 1.4 (update to version 1.6 is available)
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: twentynineteen/woocommerce/emails/email-downloads.php

### Action Scheduler ###

Complete: 26
Oldest: 2020-04-06 00:27:15 +0200
Newest: 2020-07-17 13:33:44 +0200

Pending: 9
Oldest: 2020-07-18 10:42:54 +0200
Newest: 2020-07-21 20:13:46 +0200

Canceled: 1
Oldest: -0001-11-30 01:00:00 +0100
Newest: -0001-11-30 01:00:00 +0100
```

</details>

### PR DESCRIPTION
**Pull request by barryhughes**
Within our permissions check for the `/customers/<ID>/downloads` route, we were trying to use a non-existent `WP_User` method to obtain the customer ID.

A little surprisingly, then, this still worked without triggering fatal errors, because of some fairly relaxed magic methods within `WP_User`. However, it did have consequences for any code hooking into `woocommerce_rest_check_permissions` since that would not receive the ID of the actual customer.

Closes #27109.

### How to test the changes in this Pull Request:

Let's firstly check that the happy path remains happy (ie, we aren't disrupting typical flows). You will need:

1. An API key for a shop manager or above.
1. A customer who has purchased one or more downloadable products.
2. A customer with no downloads.

From there:

1. Send a series of REST API requests to `/wp-json/wc/v3/customers/<ID>/downloads`.
2. First time, use the customer with the downloads (insert their user ID). These should be listed in the response data.
3. Second time, use the customer with no downloads. This time, no downloads should be listed in the response.

Now, add the following snippet to a suitable location (such as `wp-content/mu-plugins/pr-47854.php`):

```php
<?php

add_filter(
	'woocommerce_rest_check_permissions',
	function ( $permission, $context, $object_id, $type ) {
		if ( $type === 'user' && $object_id < 1 ) {
			throw new Exception( 'Where be the user ID?' );
		}

		return $permission;
	},
	10,
	4
);
```

1. Send another REST API request to `/wp-json/wc/v3/customers/<ID>/downloads` (supplying a valid user ID).
2. With this branch, you should get back the expected response.
3. Without this branch, a fatal error will occur (because of the exception thrown by the snippet, which is very crudely testing to see if it was passed a valid user ID).
4. A further variation of this can be found in the linked issue.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Comment 

</details>

### CODE REVIEW

**Comment by barryhughes** [comment]
```
Error:   1) [default] › merchant/products/block-editor/create-variable-product-block-editor.spec.js:194:3 › Variations tab › Create variable product › can edit a variation 
```

Triggered a re-run.

File: plugins/woocommerce/tests/php/includes/rest-api/Controllers/Version1/class-wc-rest-customer-downloads-v1-controller-tests.php [hunk 1]
```diff
@@ -0,0 +1,46 @@
...
+ * Tests relating to WC_REST_Orders_V1_Controller.
+ */
+class WC_REST_Customer_Downloads_V1_Controller_Tests extends WC_Unit_Test_Case {
+	/**
+	 * Describes the basic expectations for permission checks, as implemented for the customer downloads endpoint.
+	 *
+	 * @return void
+	 */
+	public function test_get_items_permissions_check(): void {
+		$sut                 = new WC_REST_Customer_Downloads_V1_Controller();
```
Comment (coreymckrill) [inline plugins/woocommerce/tests/php/includes/rest-api/Controllers/Version1/class-wc-rest-customer-downloads-v1-controller-tests.php:13]: I hate to say this 😬, but given that the v2 and v3 controllers inherit from v1, I suspect we should probably duplicate this test in the files for the other two versions. Even though they don't override the `get_items_permissions_check` method right now, they _could_ at some point in the future, and we'd want to make sure such an override doesn't cause a regression.

**Review by coreymckrill — APPROVED** [review]
👍 Tests well locally with the testing instructions. One suggestion below about unit testing, but otherwise I think this is good to go, so I'm pre-approving.

File: plugins/woocommerce/tests/php/includes/rest-api/Controllers/Version1/class-wc-rest-customer-downloads-v1-controller-tests.php (hunk 1 above)
Comment (barryhughes) [reply plugins/woocommerce/tests/php/includes/rest-api/Controllers/Version1/class-wc-rest-customer-downloads-v1-controller-tests.php:13]: I think that's a great call-out... let me think if there is an elegant way to do that besides just duplicating (like adding `test_get_items_permissions_check` to the test class for each version, but they call a sort of 'utility method' containing the assertions, or something along those lines).

Comment (barryhughes) [reply plugins/woocommerce/tests/php/includes/rest-api/Controllers/Version1/class-wc-rest-customer-downloads-v1-controller-tests.php:13]: Revisiting this conversation: it seems reasonable to think that if an override is added to the V2 or V3 controller, a corresponding test would be expected and required. I guess I'm just a little leery of duplicating chunks of code and adding additional tests in a pattern we haven't traditionally followed (so am giving it some further thought).

Comment (coreymckrill) [reply plugins/woocommerce/tests/php/includes/rest-api/Controllers/Version1/class-wc-rest-customer-downloads-v1-controller-tests.php:13]: > it seems reasonable to think that if an override is added to the V2 or V3 controller, a corresponding test would be expected and required

Good point! I'll mark this as resolved.
