### PR TITLE
Fix transient notices overlapping product editor footer (take 2)

### LINKED ISSUE #38651: Product Block Editor: Notices should not overlap feedback footer
## Issue Description

In #38599, the feedback footer was introduced to the product editor. When the feedback footer is visible, notices overlap it.

Notices should be displayed above the footer.

## Before

Screenshot 2023-06-05 at 19 36 54

## After

Notices appear above the footer, not overlapping it.

### PR DESCRIPTION
**Pull request by mattsherman**
### Submission Review Guidelines:

- I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
- I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
- I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/). 
- Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

In #38599, the product editor footer was introduced.

Transient notices overlapped this new footer.

This PR updates the the transient notices to not overlap the WooCommerce Admin footer.

To support this change, the `TransientNotices` component was changed to use the `WooFooterItem` fill. The CSS was updated to account for this change. No visible changes should be introduced to the use of `TransientNotices` anywhere in WooCommerce except for the case this PR is addressing (not overlapping the footer).

Closes #38651.

#### Before (overlapping transient notices)

Screenshot 2023-06-05 at 19 36 54

#### After (transient notices above footer)

Screenshot 2023-06-09 at 15 11 31

### How to test the changes in this Pull Request:

Note: To reset the state of the system so that the feedback footer will be shown, delete the following options:
* `woocommerce_product_editor_show_feedback_bar`
* `woocommerce_ces_shown_for_actions`

1. Enable experimental "new product editor" (beta) in WooCommerce > Settings > Advanced > Features
2. Go to Products > Add New
3. Verify no feedback footer is shown.
4. Fill out some fields and save draft (or publish).
5. Verify feedback footer is shown and transient notice is shown correctly above it.
6. Dismiss the footer.
7. Make a change to the product and save draft.
8. Verify the transient notice is shown correct at the bottom of the screen.

### CODE REVIEW

File: packages/js/product-editor/src/components/editor/editor.tsx [hunk 1]
```diff
@@ -86,13 +86,17 @@ export function Editor( { product, settings }: EditorProps ) {
...
 
 								<Popover.Slot />
 							</ValidationProvider>
 						</SlotFillProvider>
 					</ShortcutProvider>
+					{ /* We put Footer here instead of in InterfaceSkeleton because Footer uses
+					WooFooterItem to actually render in the WooFooterItem.Slot defined by
+					WooCommerce Admin. And, we need to put it outside of the SlotFillProvider
+					we create in this component. */ }
+					<Footer product={ product } />
```
Comment (mattsherman) [inline packages/js/product-editor/src/components/editor/editor.tsx:99]: @joshuatf Do you think we should remove the `SlotFillProvider` from this component and require the consumer of it to make sure it is in a `SlotFillProvider`?

Otherwise, any blocks/components in in the product editor won't be able to use fill slots in WooCommerce Admin (since the slot don't be in the context of this SlotFillProvider). Or, is that actually a good thing?

**Comment by mattsherman** [comment]
Oops, failing test -- probably due to lack of SlotFillProvider (so notices are not rendered). I'll update the tests later and put it back up for review!

**Comment by mattsherman** [comment]
Fixed failing unit tests... mocking was a little tricky to figure out, due to slot-fill. In the end, mocking `WooFooterItem` itself worked and made the most sense.

File: packages/js/product-editor/src/components/feedback-bar/feedback-bar.tsx [hunk 2]
```diff
@@ -93,42 +92,40 @@ export function FeedbackBar( { product }: FeedbackBarProps ) {
 	return (
 		<>
 			{ shouldShowFeedbackBar && (
```
Comment (joshuatf) [inline packages/js/product-editor/src/components/feedback-bar/feedback-bar.tsx:94]: Optional and obviously not a part of this PR, but since this code is being touched: I really like the following pattern for readability and reducing indentation.

```
if ( ! shouldShowFeedbackBar ) {
  return null;
}

return <>{/* Feedbackbar render */}</>;

File: plugins/woocommerce-admin/client/layout/transient-notices/test/index.js [hunk 3]
```diff
@@ -26,6 +27,18 @@ useDispatch.mockReturnValue( {
 	createNotice: jest.fn(),
 } );
 
+jest.mock( '@woocommerce/admin-layout', () => {
+	const originalModule = jest.requireActual( '@woocommerce/admin-layout' );
+
+	return {
+		__esModule: true, // Use it when dealing with esModules
+		...originalModule,
+		WooFooterItem: jest.fn( ( { children } ) => {
```
Comment (joshuatf) [inline plugins/woocommerce-admin/client/layout/transient-notices/test/index.js:35]: Nice!  This is always a little of a pain to mock.  Would be nice to get some utils around slot fills to make this easier on us in the future.

File: packages/js/product-editor/src/components/editor/editor.tsx (hunk 1 above)
Comment (joshuatf) [reply packages/js/product-editor/src/components/editor/editor.tsx:99]: Definitely!  Good call.  Do you want to tackle here or in a follow up?

**Review by joshuatf — APPROVED** [review]
Nicely done, Matt!  Love how clean this implementation is now.

Left one optional comment and agree with your suggestion on the `SlotFillProvider`.  Pre-approving pending whether or not you want to add those changes here.  If so, feel free to re-ping me and I can re-approve.

File: packages/js/product-editor/src/components/feedback-bar/feedback-bar.tsx (hunk 2 above)
Comment (mattsherman) [reply packages/js/product-editor/src/components/feedback-bar/feedback-bar.tsx:94]: Agreed. Will try to do this on future code.

File: packages/js/product-editor/src/components/editor/editor.tsx (hunk 1 above)
Comment (mattsherman) [reply packages/js/product-editor/src/components/editor/editor.tsx:99]: I'll handle this in a follow-up, in case there are any details that cause that to blow things up a bit.
