### PR TITLE
Fix issue #31477

### LINKED ISSUE #31477: data.coupon_code undefined in checkout.js
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

`data.coupon_code` is `undefined` in `woocommerce/assets/js/frontend/checkout.js` line 671:

```JavaScript
$( document.body ).trigger( 'removed_coupon_in_checkout', [ data.coupon_code ] );
```

### Expected behavior

When `removed_coupon_in_checkout` is triggered, a `data` parameter contains the removed coupon code.

### Actual behavior

When `removed_coupon_in_checkout` is triggered, the `data` parameter is always `undefined`.

### Steps to reproduce

When removing a coupon on Checkout page:

1. Add the following in a script or console:

```JavaScript
jQuery(document.body).on( 'removed_coupon_in_checkout', function(e, data) {
	console.log(data);
});
```
2. See `undefined` in console
3. change `coupon_code` into `coupon`  in `woocommerce/assets/js/frontend/checkout.js` line 671
4. Start from 1. and see the actual coupon code in console

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://test.froger.me
Site address (URL): https://test.froger.me
WC Version: 6.0.0
REST API Version: ✔ 6.0.0
WC Blocks Version: ✔ 6.3.3
Action Scheduler Version: ✔ 3.3.0
WC Admin Version: ✔ 2.9.4
Log Directory Writable: ✔
WP Version: 5.8.2
WP Multisite: –
WP Memory Limit: 2 GB
WP Debug Mode: ✔
WP Cron: –
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.4.26
PHP Post Max Size: 1,000 MB
PHP Time Limit: 300
PHP Max Input Vars: 1000
cURL Version: 7.58.0
OpenSSL/1.1.1

SUHOSIN Installed: –
MySQL Version: 5.7.36-0ubuntu0.18.04.1
Max Upload Size: 1,000 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 6.0.0
WC Database Prefix: wp_
Total Database Size: 24.93MB
Database Data Size: 21.02MB
Database Index Size: 3.91MB
wp_woocommerce_sessions: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_api_keys: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_order_items: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wp_woocommerce_order_itemmeta: Data: 0.11MB + Index: 0.09MB + Engine MyISAM
wp_woocommerce_tax_rates: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_actionscheduler_actions: Data: 0.22MB + Index: 0.11MB + Engine MyISAM
wp_actionscheduler_claims: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_actionscheduler_groups: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_actionscheduler_logs: Data: 0.16MB + Index: 0.13MB + Engine MyISAM
wp_admin_columns: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_commentmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_comments: Data: 0.07MB + Index: 0.03MB + Engine MyISAM
wp_links: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_matomo_access: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_matomo_archive_blob_2012_01: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_matomo_archive_blob_2013_01: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_matomo_archive_blob_2014_01: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_matomo_archive_blob_2015_01: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_matomo_archive_blob_2016_01: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_matomo_archive_blob_2017_01: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_matomo_archive_blob_2018_01: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_matomo_archive_blob_2019_01: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_matomo_archive_blob_2020_01: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_matomo_archive_blob_2021_01: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_matomo_archive_blob_2021_02: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_matomo_archive_blob_2021_03: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_matomo_archive_blob_2021_04: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_matomo_archive_blob_2021_05: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_matomo_archive_blob_2021_06: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_matomo_archive_blob_2021_07: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_matomo_archive_blob_2021_08: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_matomo_archive_blob_2021_09: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_matomo_archive_blob_2021_10: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_matomo_archive_blob_2021_11: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_matomo_archive_blob_2021_12: Data: 0.17MB + Index: 0.05MB + Engine InnoDB
wp_matomo_archive_blob_2022_01: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_matomo_archive_invalidations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_matomo_archive_numeric_2012_01: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_matomo_archive_numeric_2013_01: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_matomo_archive_numeric_2014_01: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_matomo_archive_numeric_2015_01: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_matomo_archive_numeric_2016_01: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_matomo_archive_numeric_2017_01: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_matomo_archive_numeric_2018_01: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_matomo_archive_numeric_2019_01: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_matomo_archive_numeric_2020_01: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_matomo_archive_numeric_2021_01: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_matomo_archive_numeric_2021_02: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_matomo_archive_numeric_2021_03: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_matomo_archive_numeric_2021_04: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_matomo_archive_numeric_2021_05: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_matomo_archive_numeric_2021_06: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_matomo_archive_numeric_2021_07: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_matomo_archive_numeric_2021_08: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_matomo_archive_numeric_2021_09: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_matomo_archive_numeric_2021_10: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_matomo_archive_numeric_2021_11: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_matomo_archive_numeric_2021_12: Data: 0.09MB + Index: 0.03MB + Engine InnoDB
wp_matomo_archive_numeric_2022_01: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_matomo_brute_force_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_matomo_custom_dimensions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_matomo_goal: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_matomo_locks: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_matomo_logger_message: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_matomo_log_action: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_matomo_log_conversion: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_matomo_log_conversion_item: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_matomo_log_link_visit_action: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_matomo_log_profiling: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_matomo_log_visit: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_matomo_option: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_matomo_plugin_setting: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_matomo_privacy_logdata_anonymizations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_matomo_report: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_matomo_report_subscriptions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_matomo_segment: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_matomo_sequence: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_matomo_session: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_matomo_shortcode: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_matomo_site: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_matomo_site_setting: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_matomo_site_url: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_matomo_tagmanager_container: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_matomo_tagmanager_container_release: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_matomo_tagmanager_container_version: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_matomo_tagmanager_tag: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_matomo_tagmanager_trigger: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_matomo_tagmanager_variable: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_matomo_tracking_failure: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_matomo_twofactor_recovery_code: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_matomo_user: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_matomo_user_dashboard: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_matomo_user_language: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_matomo_user_token_auth: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 1.46MB + Index: 0.06MB + Engine MyISAM
wp_postmeta: Data: 1.00MB + Index: 0.31MB + Engine MyISAM
wp_posts: Data: 1.95MB + Index: 0.05MB + Engine MyISAM
wp_simple_login_log: Data: 12.96MB + Index: 0.92MB + Engine MyISAM
wp_termmeta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_terms: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_term_relationships: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_term_taxonomy: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_usermeta: Data: 0.96MB + Index: 0.33MB + Engine MyISAM
wp_users: Data: 0.07MB + Index: 0.07MB + Engine MyISAM
wp_wc_admin_notes: Data: 0.03MB + Index: 0.00MB + Engine MyISAM
wp_wc_admin_note_actions: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wp_wc_category_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine MyISAM
wp_wc_download_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_order_coupon_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.02MB + Engine MyISAM
wp_wc_order_stats: Data: 0.01MB + Index: 0.02MB + Engine MyISAM
wp_wc_order_tax_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_product_meta_lookup: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_tax_rate_classes: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_webhooks: Data: 0.00MB + Index: 0.00MB + Engine MyISAM

### Post Type Counts ###

attachment: 65
nav_menu_item: 14
page: 14
post: 1
product: 3
product_variation: 39
revision: 107
shop_coupon: 1
shop_order: 163
shop_order_refund: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (21) ###

Query Monitor: by John Blackbourn – 3.7.1
Adminimize: by Frank Bültge – 1.11.7
Classic Editor: by WordPress Contributors – 1.6.2
Admin Columns: by AdminColumns.com – 4.4.4
Simple Custom CSS and JS: by SilkyPress.com – 3.38.1
Disable WooCommerce Bloat: by ospiotr – 2.6.1
Duplicate Page: by mndpsingh287 – 4.4.7
Health Check & Troubleshooting: by The WordPress.org community – 1.4.5
Loco Translate: by Tim Whitlock – 2.5.5
Matomo Analytics - Ethical Stats. Powerful Insights.: by Matomo – 4.5.0
Simple Login Log: by Max Chirkov – 1.1.3
Advanced Editor Tools (previously TinyMCE Advanced): by Automattic – 5.6.0
Transients Manager: by WPBeginner – 2.0.0
UpdraftPlus - Backup/Restore: by UpdraftPlus.Com
DavidAnderson – 1.16.66

Url Rewrite Analyzer: by DevlopEr – 1.3.1
User Role Editor: by Vladimir Garagulya – 4.60.2
WooCommerce Admin: by WooCommerce – 2.9.4
Direct Checkout for WooCommerce: by QuadLayers – 2.5.7
WooCommerce: by Automattic – 6.0.0
WP Crontrol: by John Blackbourn & crontributors – 1.12.0
WP Options Editor: by Mike Selander – 1.1

### Dropin Plugins (1) ###

db.php: Query Monitor Database Class

### Must Use Plugins (1) ###

Health Check Troubleshooting Mode: by  – 1.7.2

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #94 - /shop/
Cart: #95 - /cart/
Checkout: #96 - /checkout/
My account: #97 - /my-account/
Terms and conditions: /toc/

### Theme ###

Name: Storefront
Version: 3.9.1
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Outdated Templates: ✔

### Action Scheduler ###

Complete: 807
Oldest: 2021-11-30 13:56:37 +0800
Newest: 2021-12-18 13:09:47 +0800

### Status report information ###

Generated at: 2021-12-19 07:34:18 +08:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by froger-me**
### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes https://github.com/woocommerce/woocommerce/issues/31477

### How to test the changes in this Pull Request:

See https://github.com/woocommerce/woocommerce/issues/31477

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Fix - Guard against undefined `data.coupon_code` error in `frontend/checkout.js`.

### FOR PR REVIEWER ONLY:

* [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

**Review by barryhughes — DISMISSED** [review]
LGTM.

As soon as tests pass, we can merge—thank you :-)

**Comment by froger-me** [comment]
Thanks @barryhughes ; I notice the E2E failure but I'm not really familiar with the automated test process. Is there anything I need to do on my end, and if yes, could you please offer guidance?

**Comment by barryhughes** [comment]
So I re-ran the tests (since sometimes they fail unexpectedly, for unrelated reasons) but this seems to be failing consistently and in relation to coupon-related tests ... so it definitely deserves a closer look. 

Feel free to poke around if you have time (I don't have any specific tips, though) and if you don't, don't worry: we'll figure it out. My suspicion is there is an oversight in one of the tests.

**Comment by froger-me** [comment]
What I can gather from the test's trace (and I don't know what to do with that info) is that there is a `TimeoutError` thrown I assume when loading assets to execute the test, resulting in a missing HTML element `.woocommerce-message` that's necessary.

**Comment by barryhughes** [comment]
(Re-based on latest `trunk` code.)

**Comment by barryhughes** [comment]
Sorry for the delay getting back to you here, @froger-me. The test fails are legitimate, as this change prevents removal of the coupon from the checkout. We're going to need a small change: I'll leave some notes inline.

File: plugins/woocommerce/legacy/js/frontend/checkout.js [hunk 1]
```diff
@@ -653,8 +653,8 @@ jQuery( function( $ ) {
 			});
 
 			var data = {
-				security: wc_checkout_params.remove_coupon_nonce,
-				coupon:   coupon
+				security:		wc_checkout_params.remove_coupon_nonce,
+				coupon_code:	coupon
```
Comment (barryhughes) [inline plugins/woocommerce/legacy/js/frontend/checkout.js]: Let's revert this change, taking things back to:

```suggestion
				security: wc_checkout_params.remove_coupon_nonce,
				coupon:   coupon
```

Reason being the corresponding ajax handler expects to receive the `coupon` field in the request. Further down (line 671) we should switch from:

```js
$( document.body ).trigger( 'removed_coupon_in_checkout', [ data.coupon_code ] );
```

To:

```js
$( document.body ).trigger( 'removed_coupon_in_checkout', [ data.coupon ] );
```

**Review by barryhughes — CHANGES_REQUESTED** [review]
Please see notes; we need a minor change before we can accept this. Thanks!

**Review by barryhughes — APPROVED** [review]
