### PR TITLE
Timezone/DST fixes

### LINKED ISSUE #13708: (WC 3.0.0 RC1) Can't change product status
I have two issues.
1. When i put some product tags, the product was turned from publish to scheduled automatically.
2. I can't change the schedule status to publish status both on quick edit or edit. there is maybe missing publish status either.

screen shot 2017-03-22 at 7 05 02 am

### PR DESCRIPTION
**Pull request by mikejolley**
Fixes #13708

Also adds GMT and gmdate to protect against non-UTC php timezone.

### CODE REVIEW

**Comment by mikejolley** [comment]
@thenbrent Looks like something you dealt with in subs.

**Comment by mikejolley** [comment]
To explain the problem a little since I didn't go into much detail, the creation time was off by one hour when using a manual -5 offset. It was matching the New York timezone, but the New York timezone is currently in DST (-4) not -5.

This removes the forced `0` for isdst so it's detected, and matches the current DST for the site timezone against the timezones to get a better match.

To test (best do this on master first to compare):

- Set timezone to UTC -5 in settings > general.
- Add product. Set title. Save. 
- See timezone is +1.
- If you quick edit this product it becomes scheduled because it's in the future.

@justinshreve @maxrice @thenbrent

**Comment by mikejolley** [comment]
Some issues in some environments https://travis-ci.org/woocommerce/woocommerce/jobs/213814283

File: includes/wc-formatting-functions.php [hunk 1]
```diff
@@ -558,15 +558,15 @@ function wc_timezone_string() {
 	$utc_offset *= 3600;
 
 	// attempt to guess the timezone string from the UTC offset
-	$timezone = timezone_name_from_abbr( '', $utc_offset, 0 );
+	$timezone = timezone_name_from_abbr( '', $utc_offset );
 
 	// last try, guess timezone string manually
 	if ( false === $timezone ) {
-		$is_dst = date( 'I' );
+		$is_dst = "1" === date( 'I' );
```
Comment (claudiosanches) [inline includes/wc-formatting-functions.php]: Require single quote.

**Comment by maxrice** [comment]
nice find, LGTM 👍

**Comment by mikejolley** [comment]
HHVM is not liking this.

**Review by claudiosanches — APPROVED** [review]
:ok_hand:

**Comment by mikejolley** [comment]
@claudiosanches it's passing in HHVM now. Getting timezone offset from strings was too unreliable.

File: includes/data-stores/class-wc-coupon-data-store-cpt.php [hunk 2]
```diff
@@ -94,8 +94,8 @@ public function read( &$coupon ) {
 		$coupon->set_props( array(
 			'code'                        => $post_object->post_title,
 			'description'                 => $post_object->post_excerpt,
-			'date_created'                => strtotime( $post_object->post_date_gmt ),
-			'date_modified'               => strtotime( $post_object->post_modified_gmt ),
+			'date_created'                => 0 < $post_object->post_date_gmt ? wc_string_to_timestamp( $post_object->post_date_gmt ) : null,
```
Comment (claudiulodro) [inline includes/data-stores/class-wc-coupon-data-store-cpt.php]: Auto-drafts have a `post_date_gmt` of `0000-00-00 00:00:00`, so this will evaluate to true as that string is greater than 0. What is this check supposed to catch?

Comment (claudiulodro) [inline includes/data-stores/class-wc-coupon-data-store-cpt.php]: This question applies to all the places where you do `0 < $post_object->post_date_gmt`

Comment (mikejolley) [inline includes/data-stores/class-wc-coupon-data-store-cpt.php]: This is to prevent it creating a timestamp from 0000.. so you don't get invalid times. It should be null. @claudiulodro is that wrong?

Comment (claudiulodro) [inline includes/data-stores/class-wc-coupon-data-store-cpt.php]: Well I'll be darned. :) 

After more testing, it looks like `0 < '0000-00-00 00:00:00'` is false in PHP and `0 < '2017-03-23 18:48:11'` is true. You're absolutely correct; this works properly. I misunderstood what happens when those time strings are cast to an integer.

Everything looks good to me, then. 👍

**Review by claudiulodro — APPROVED** [review]

**Comment by maxrice** [comment]
@mikejolley just updating our extensions with this new DateTime stuff now, works great. The only area I've seen for improvement is what's returned when a date doesn't exist (yet). We have a few situations where this can occur, like XML Export, which includes a `CompletedDate` attribute. Of course, that date may not be set, depending on the order status at the time of export.

Because `$order->get_date_completed()` can return either an instance of `WC_DateTime` _or_ `null`, we end up having write not-so-clean code like:

```php
$date_completed = is_callable( array( $order->get_date_completed(), 'date' ) ) ? $order->get_date_completed()->date( 'Y-m-d H:i:s' ) : null;
```

It would be nicer if an instance of `WC_DateTime` was always returned and those methods simply returned `null`.

**Comment by mikejolley** [comment]
@maxrice I don't agree there - this extends DateTime which as you know has it's own methods for things like formatting dates. If say, you tried to format a date and it was NULL you'd either get an odd result or error.

Better to handle NULLS when they can occur IMO.

**Comment by mikejolley** [comment]
Merging this as it's had a few reviews now; I cannot see anything wrong or broken with this approach and it's all self-contained.
