### PR TITLE
Handle coming soon templates created prior 9.8.0

### LINKED ISSUE #56170: [GlobalStep] Black design is display for "Page: Coming Soon" template after upgrading Woocommerce version from 9.7.1 to 9.8.0-beta.1 on "Appearance > Editor" page.
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Black design is display for "Page: Coming Soon" template after upgrading Woocommerce version from 9.7.1 to 9.8.0-beta.1 on "Appearance > Editor" page.

### Expected behavior

Proper customized design should be displayed for "Page: Coming Soon" template after upgrading Woocommerce version from 9.7.1 to 9.8.0-beta.1 on "Appearance > Editor" page.

### Actual behavior

Black design is display for "Page: Coming Soon" template after upgrading Woocommerce version from 9.7.1 to 9.8.0-beta.1 on "Appearance > Editor" page.

### Steps to reproduce

1. Create a new test site.
2. Install all the required plugins.
3. Install and activate the Woocommerce version 9.7.1 plugins.
4. Go to WP Admin > Appearance > Editor
5. Click "Templates > WooCommerce > Page: Coming Soon"
6. Now inside the editor you will see purple coming soon design.
7. Customize the template then click save and check if the changes are saved and display properly on editor and frontend.
8. Go to "Plugins > Add new plugin"
9. Install and activate the Woocommerce version 9.8.0-beta.1 plugins.
10. Again go to WP Admin > Appearance > Editor.
11. Click Templates > WooCommerce.
12. Observe that black design is displayed for "Page: Coming Soon" preview screen.
13. Click on "Page: Coming Soon" template.
14. Observe that, black design is display for "Page: Coming Soon" template editor page.
15. Refresh frontend and same issue will be observed.

### Video:

https://github.com/user-attachments/assets/611d179b-bd30-485e-b233-0956eb1bc874

### WordPress Environment

Woocommerce Version : 9.8.0-beta.1
Wordpress version: 6.7.2

PC:
Windows 10,
Chrome(Version 134.0.6998.36)
Firefox(Version 136.0)

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

<details><summary>System Status Report</summary>

```
### WordPress Environment ###

WordPress address (URL): [Redacted]
Site address (URL): [Redacted]
WC Version: 9.8.0-beta.1
Legacy REST API Package Version: The Legacy REST API plugin is not installed on this site.
Action Scheduler Version: ✔ 3.9.2
Log Directory Writable: ✔
WP Version: 6.7.2
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 8.3.17
PHP Post Max Size: 2 GB
PHP Time Limit: 850
PHP Max Input Vars: 6144
cURL Version: 8.12.1
OpenSSL/3.0.15

SUHOSIN Installed: –
MySQL Version: 10.11.11-MariaDB-log
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

[REDACTED]

### Post Type Counts ###

attachment: 1
page: 7
post: 2
revision: 1
wp_font_face: 36
wp_font_family: 12
wp_global_styles: 1
wp_navigation: 1
wp_template: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (3) ###

Akismet Anti-spam: Spam Protection: by Automattic - Anti-spam Team – 5.3.7
Query Monitor: by John Blackbourn – 3.17.2
WooCommerce: by Automattic – 9.8.0-beta.1

### Inactive Plugins (0) ###


### Dropin Plugins () ###

advanced-cache.php: advanced-cache.php
db.php: Query Monitor Database Class (Drop-in)
object-cache.php: Memcached

### Must Use Plugins (1) ###

load.php: by  –

### Settings ###

Legacy API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 2 KB

### WC Pages ###

Shop base: #5 - /shop/
Cart: #6 - /cart/ -  Contains the woocommerce/cart block
Checkout: #7 - /checkout/ -  Contains the woocommerce/checkout block
My account: #8 - /my-account/ -  Contains the [woocommerce_my_account] shortcode
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty-Four
Version: 1.3
Author URL: https://wordpress.org
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
Theme type: Block theme
WooCommerce Support: ❌ Not declared

### Templates ###

Overrides: /srv/htdocs/wp-content/plugins/woocommerce/templates/block-notices/error.php
/srv/htdocs/wp-content/plugins/woocommerce/templates/block-notices/notice.php
/srv/htdocs/wp-content/plugins/woocommerce/templates/block-notices/success.php


### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
onboarding
onboarding-tasks
pattern-toolkit-full-composability
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
printful
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page
launch-your-store
add-to-cart-with-options-stepper-layout

Disabled Features: product-data-views
experimental-blocks
coming-soon-newsletter-template
minified-js
product-pre-publish-modal
settings
async-product-editor-category-field
product-editor-template-system
reactify-classic-payments-settings
use-wp-horizon
blockified-add-to-cart

Daily Cron: ✔ Next scheduled: 2025-03-07 10:26:18 +00:00
Options: ✔
Notes: 59
Onboarding: skipped

### Action Scheduler ###

Complete: 5
Oldest: 2025-03-06 10:26:24 +0000
Newest: 2025-03-06 10:30:36 +0000

Pending: 1
Oldest: 2025-03-07 10:26:24 +0000
Newest: 2025-03-07 10:26:24 +0000


### Status report information ###

Generated at: 2025-03-06 13:46:05 +00:00
```
</details>

### PR DESCRIPTION
**Pull request by ilyasfoo**
### Changes proposed in this Pull Request:

Closes #56170.

Fixes missing CSS when store has coming soon template persisted from WooCommerce < 9.8.0. I decided to add back previous CSS to ensure old styling is preserved (i.e: buttons would look wierd, font sizes janky if these styles are removed).

### Screenshots or screen recordings:

| Before | After |
| ------ | ----- |
| image |   image |

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

#### Testing fix
1. Create a JN based on this branch
2. Go to `Plugins > Installed Plugins` and deactivate WooCommerce plugin
1. Install and activate WooCommerce 9.7.1 and WooCommerce Beta Tester
3. Go to `WooCommerce > Settings > Site visibility`
4. Ensure `Coming soon` is **selected** and `Apply to store pages only` is **deselected** and save
5. Go to `Appearance > Editor > Templates > Page: Coming soon`
6. Change the background color of the middle heading
7. Select `Coming soon` block and set background color ([example](https://github.com/user-attachments/assets/3375a3fb-87c5-4ba9-aa88-a65643dd937d))
1. Save template
1. Go to `Plugins > Installed Plugins`, deactivate WooCommerce 9.7.1 and reactivate the original WooCommerce
2. Go back to coming soon template and refresh
3. Observe the background colors are preserved

#### Regression test
1. Continue from above instructions, expand `Design` panel
3. Select `Coming Soon Minimal Left Image` and no unexpected UI issues ([screenshot](https://github.com/user-attachments/assets/37d08316-40ab-4379-b5b5-cf3f4a5fdc80))
2. Select `Default Coming Soon` and observe no unexpected UI issues ([screenshot](https://github.com/user-attachments/assets/117173ef-da3e-4df2-a33e-50de4d0f1e07))
4. Open browser developer console and go to the networks tab
5. Filter for `coming-soon-entire-site-deprecated.css`
6. Back to the site editor, press `Save`
7. Observe no entry for the CSS in networks tab

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce/patterns/page-coming-soon-default.php [hunk 1]
```diff
@@ -15,8 +15,8 @@
 
 ?>
 
-<!-- wp:woocommerce/coming-soon {"comingSoonPatternId":"page-coming-soon-default","className":"woocommerce-coming-soon-entire-site","style":{"color":{"background":"#bea0f2","text":"#000000"},"elements":{"link":{"color":{"text":"#000000"}}}}} -->
-<div class="wp-block-woocommerce-coming-soon woocommerce-coming-soon-entire-site has-text-color has-background has-link-color" style="color:#000000;background-color:#bea0f2"><!-- wp:cover {"customOverlayColor":"transparent","isUserOverlayColor":true,"minHeight":100,"minHeightUnit":"vh","className":"coming-soon-is-vertically-aligned-center coming-soon-cover","style":{"spacing":{"padding":{"top":"0px","bottom":"0px","left":"24px","right":"24px"}},"color":{"text":"inherit"},"elements":{"link":{"color":{"text":"inherit"}}}},"layout":{"type":"constrained","wideSize":"1280px"}} -->
+<!-- wp:woocommerce/coming-soon {"comingSoonPatternId":"page-coming-soon-default","className":"woocommerce-coming-soon-default","style":{"color":{"background":"#bea0f2","text":"#000000"},"elements":{"link":{"color":{"text":"#000000"}}}}} -->
```
Comment (ilyasfoo) [inline plugins/woocommerce/patterns/page-coming-soon-default.php:18]: Updated classname `woocommerce-coming-soon-default ` to prevent conflicting styles with older version

File: plugins/woocommerce-blocks/assets/js/blocks/coming-soon/index.tsx [hunk 2]
```diff
@@ -15,6 +15,7 @@ import deprecated from './deprecated';
 import NewsletterPanel from './newsletter-panel';
 import './store-only.scss';
 import './entire-site.scss';
+import './entire-site-deprecated.scss';
```
Comment (chihsuan) [inline plugins/woocommerce-blocks/assets/js/blocks/coming-soon/index.tsx]: I think we should only enqueue the entire-site-deprecated stylesheet when the deprecated template is in use to avoid the [performance issue](https://github.com/woocommerce/woocommerce/issues/54077)

**Review by psealock — APPROVED** [review]
Tested on JN instance.
* Made CSS changes to various blocks using Woo 9.7.1.
* Switched back to this branch's build and saw those style changes persist.

Approving pending Chi's comment.

Screenshot
image

File: plugins/woocommerce-blocks/assets/js/blocks/coming-soon/index.tsx (hunk 2 above)
Comment (ilyasfoo) [reply plugins/woocommerce-blocks/assets/js/blocks/coming-soon/index.tsx]: Thanks for catching that, @chihsuan! Unfortunately it wasn't simple to add a conditional CSS asset using block's JS build, so I changed it to use enqueue [frontend](https://github.com/woocommerce/woocommerce/pull/56210/files#diff-45e03efebf7424b6f8b494a3f3941289c6fac876171c7183c8ef63c9770f8911R52-R56) and [site-editor](https://github.com/woocommerce/woocommerce/pull/56210/files#diff-45e03efebf7424b6f8b494a3f3941289c6fac876171c7183c8ef63c9770f8911R64-R94)

**Review by chihsuan — APPROVED** [review]
Thanks for the fix! @ilyasfoo I've tested the changes for handling coming soon templates from pre-9.8.0 versions and everything works as expected. 

#### Test environment

<details>
WordPress: 6.4.3
Theme: Twenty Twenty-Four Version: 1.0
WooCommerce: Development version with fix/56170-coming-soon-upgrade branch
PHP: 8.2
Web Server: Nginx
Browser: Chrome 122
OS: macOS Sonoma 14.3.1
</details>

#### Review checklist

| Parameter  | Result |
| ------------- | ------------- |
| Approach  | ✅ Good solution for backward compatibility |
| Implementation  | ✅ Improved with conditional loading |
| Automated tests  | Not applicable |
| Naming  | ✅ Clear and consistent |
| Typing  | ✅ All good |
| Code comments  | ✅ All good |
| Changelog  | ✅ All good |
| Documentation  | non applicable |
| PR description  | ✅ Clear and includes before/after screenshots |
| Testing instructions  | ✅ Comprehensive |
| Manual testing  | ✅ Works as expected |

#### Scenarios tested

| Scenario  | Result | Screenshot |
| ------------- | ------------- | ------------- |
| Coming soon template from WC 9.7.1 | ✅ Styles preserved correctly | Screenshot 2025-03-11 at 10 55 59 |
| New coming soon template in 9.8.0 | ✅ | Screenshot 2025-03-11 at 11 04 51 |
