### PR TITLE
Fix increasing & decreasing sale price in product bulk edit

### LINKED ISSUE #43149: sconti di massa non funzionanti
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

stavo verificando che esiste un problema presente da oltre 2 anni senza soluzione e già stato segnalato in questo forum al seguente link https://github.com/woocommerce/woocommerce/issues/29617 

### Expected behavior

modificando il prezzo scontato di una determinata categoria ad esempio impostando un prezzo di listino a € 30,00 e applicando uno sconto del -5% gli importi dovrebbero diventare € 28,50 

### Actual behavior

modificando il prezzo scontato di una determinata categoria ad esempio impostando un prezzo inferiore di -5% gli importi scontati diventano 0

### Steps to reproduce

1 woccommerce 
2 prodotti
3 categoria
4 seleziona prodotti 
5 modifica rapida 
6 diminuisci il prezzo di -5% 
7 applica 

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): http://www.ferramentamagnante.com
Site address (URL): http://www.ferramentamagnante.com
WC Version: 8.4.0
REST API Version: ✔ 8.4.0
WC Blocks Version: ✔ 11.6.2
Action Scheduler Version: ✔ 3.7.0
Log Directory Writable: ✔
WP Version: 6.4.2
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: –
WP Cron: ✔
Language: it_IT
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 8.2.10
PHP Post Max Size: 300 MB
PHP Time Limit: 120
PHP Max Input Vars: 10000
cURL Version: 7.68.0
OpenSSL/1.1.1f

SUHOSIN Installed: –
MySQL Version: 5.7.33-36-log
Max Upload Size: 300 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.4.0
WC Database Prefix: wp_
Dimensione totale database: 689.88MB
Dimensione dati database: 661.83MB
Dimensione indice database: 28.05MB
wp_woocommerce_sessions: Dati: 206.27MB + indice: 1.69MB + motore MyISAM
wp_woocommerce_api_keys: Dati: 0.00MB + indice: 0.01MB + motore MyISAM
wp_woocommerce_attribute_taxonomies: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wp_woocommerce_downloadable_product_permissions: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wp_woocommerce_order_items: Dati: 0.01MB + indice: 0.01MB + motore MyISAM
wp_woocommerce_order_itemmeta: Dati: 0.08MB + indice: 0.04MB + motore MyISAM
wp_woocommerce_tax_rates: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wp_woocommerce_tax_rate_locations: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wp_woocommerce_shipping_zones: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wp_woocommerce_shipping_zone_locations: Dati: 0.03MB + indice: 0.04MB + motore MyISAM
wp_woocommerce_shipping_zone_methods: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wp_woocommerce_payment_tokens: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wp_woocommerce_payment_tokenmeta: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wp_woocommerce_log: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpstg0_actionscheduler_actions: Dati: 2.38MB + indice: 0.75MB + motore MyISAM
wpstg0_actionscheduler_claims: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpstg0_actionscheduler_groups: Dati: 0.00MB + indice: 0.01MB + motore MyISAM
wpstg0_actionscheduler_logs: Dati: 1.50MB + indice: 1.42MB + motore MyISAM
wpstg0_aiowps_events: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpstg0_aiowps_failed_logins: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpstg0_aiowps_global_meta: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpstg0_aiowps_login_activity: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpstg0_aiowps_login_lockdown: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpstg0_aiowps_permanent_block: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpstg0_bwt_failed_submissions: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wpstg0_bwt_passed_submissions: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wpstg0_cartflows_ca_cart_abandonment: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wpstg0_cartflows_ca_email_history: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wpstg0_cartflows_ca_email_templates: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wpstg0_cartflows_ca_email_templates_meta: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wpstg0_cff_facebook_feed_locator: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wpstg0_cff_feeds: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wpstg0_cff_feed_caches: Dati: 0.05MB + indice: 0.02MB + motore InnoDB
wpstg0_cff_sources: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wpstg0_chaty_contact_form_leads: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wpstg0_cky_banners: Dati: 0.05MB + indice: 0.00MB + motore InnoDB
wpstg0_cky_cookies: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wpstg0_cky_cookie_categories: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wpstg0_commentmeta: Dati: 0.02MB + indice: 0.01MB + motore MyISAM
wpstg0_comments: Dati: 0.02MB + indice: 0.02MB + motore MyISAM
wpstg0_cr_local_forms: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wpstg0_duplicator_packages: Dati: 0.01MB + indice: 0.00MB + motore MyISAM
wpstg0_ewwwio_images: Dati: 2.11MB + indice: 1.22MB + motore MyISAM
wpstg0_ewwwio_queue: Dati: 0.09MB + indice: 0.06MB + motore MyISAM
wpstg0_e_events: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wpstg0_gla_attribute_mapping_rules: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wpstg0_gla_budget_recommendations: Dati: 0.19MB + indice: 0.14MB + motore InnoDB
wpstg0_gla_merchant_issues: Dati: 1.52MB + indice: 0.00MB + motore InnoDB
wpstg0_gla_shipping_rates: Dati: 0.02MB + indice: 0.05MB + motore InnoDB
wpstg0_gla_shipping_times: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wpstg0_grp_google_place: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpstg0_grp_google_review: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpstg0_jetpack_sync_queue: Dati: 0.02MB + indice: 0.06MB + motore InnoDB
wpstg0_jetpack_waf_blocklog: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wpstg0_links: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpstg0_mailchimp_carts: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpstg0_mailchimp_jobs: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpstg0_mailpoet_custom_fields: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpstg0_mailpoet_dynamic_segment_filters: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpstg0_mailpoet_feature_flags: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpstg0_mailpoet_forms: Dati: 0.01MB + indice: 0.00MB + motore MyISAM
wpstg0_mailpoet_log: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpstg0_mailpoet_mapping_to_external_entities: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpstg0_mailpoet_newsletters: Dati: 0.07MB + indice: 0.00MB + motore MyISAM
wpstg0_mailpoet_newsletter_links: Dati: 0.02MB + indice: 0.02MB + motore MyISAM
wpstg0_mailpoet_newsletter_option: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpstg0_mailpoet_newsletter_option_fields: Dati: 0.00MB + indice: 0.01MB + motore MyISAM
wpstg0_mailpoet_newsletter_posts: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpstg0_mailpoet_newsletter_segment: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpstg0_mailpoet_newsletter_templates: Dati: 2.31MB + indice: 0.00MB + motore MyISAM
wpstg0_mailpoet_scheduled_tasks: Dati: 0.16MB + indice: 0.04MB + motore MyISAM
wpstg0_mailpoet_scheduled_task_subscribers: Dati: 0.00MB + indice: 0.01MB + motore MyISAM
wpstg0_mailpoet_segments: Dati: 0.00MB + indice: 0.01MB + motore MyISAM
wpstg0_mailpoet_sending_queues: Dati: 0.74MB + indice: 0.00MB + motore MyISAM
wpstg0_mailpoet_settings: Dati: 0.02MB + indice: 0.00MB + motore MyISAM
wpstg0_mailpoet_statistics_bounces: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wpstg0_mailpoet_statistics_clicks: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpstg0_mailpoet_statistics_forms: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpstg0_mailpoet_statistics_newsletters: Dati: 0.00MB + indice: 0.01MB + motore MyISAM
wpstg0_mailpoet_statistics_opens: Dati: 0.00MB + indice: 0.01MB + motore MyISAM
wpstg0_mailpoet_statistics_unsubscribes: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpstg0_mailpoet_statistics_woocommerce_purchases: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpstg0_mailpoet_stats_notifications: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpstg0_mailpoet_subscribers: Dati: 0.02MB + indice: 0.04MB + motore MyISAM
wpstg0_mailpoet_subscriber_custom_field: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpstg0_mailpoet_subscriber_ips: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpstg0_mailpoet_subscriber_segment: Dati: 0.02MB + indice: 0.03MB + motore MyISAM
wpstg0_mailpoet_user_agents: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wpstg0_mailpoet_user_flags: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpstg0_mo_openid_linked_user: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wpstg0_ms_snippets: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpstg0_nf3_actions: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpstg0_nf3_action_meta: Dati: 0.01MB + indice: 0.00MB + motore MyISAM
wpstg0_nf3_chunks: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpstg0_nf3_fields: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpstg0_nf3_field_meta: Dati: 0.02MB + indice: 0.01MB + motore MyISAM
wpstg0_nf3_forms: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpstg0_nf3_form_meta: Dati: 0.01MB + indice: 0.00MB + motore MyISAM
wpstg0_nf3_objects: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpstg0_nf3_object_meta: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpstg0_nf3_relationships: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpstg0_nf3_upgrades: Dati: 0.02MB + indice: 0.00MB + motore MyISAM
wpstg0_options: Dati: 7.12MB + indice: 0.29MB + motore MyISAM
wpstg0_postmeta: Dati: 25.84MB + indice: 4.57MB + motore MyISAM
wpstg0_posts: Dati: 35.47MB + indice: 0.46MB + motore MyISAM
wpstg0_pum_subscribers: Dati: 0.02MB + indice: 0.06MB + motore InnoDB
wpstg0_sbi_feeds: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wpstg0_sbi_feed_caches: Dati: 0.05MB + indice: 0.02MB + motore InnoDB
wpstg0_sbi_instagram_feeds_posts: Dati: 0.01MB + indice: 0.01MB + motore MyISAM
wpstg0_sbi_instagram_feed_locator: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpstg0_sbi_instagram_posts: Dati: 0.18MB + indice: 0.00MB + motore MyISAM
wpstg0_sbi_sources: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wpstg0_sib_model_contact: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wpstg0_sib_model_country: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wpstg0_sib_model_forms: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wpstg0_sib_model_users: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wpstg0_smush_dir_images: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpstg0_snippets: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpstg0_termmeta: Dati: 0.19MB + indice: 0.13MB + motore MyISAM
wpstg0_terms: Dati: 0.03MB + indice: 0.06MB + motore MyISAM
wpstg0_term_relationships: Dati: 0.19MB + indice: 0.39MB + motore MyISAM
wpstg0_term_taxonomy: Dati: 0.06MB + indice: 0.05MB + motore MyISAM
wpstg0_tinvwl_analytics: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wpstg0_tinvwl_items: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wpstg0_tinvwl_lists: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wpstg0_usermeta: Dati: 0.35MB + indice: 0.16MB + motore MyISAM
wpstg0_users: Dati: 0.02MB + indice: 0.02MB + motore MyISAM
wpstg0_wcpdf_invoice_number: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wpstg0_wcpdf_packing_slip_number: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wpstg0_wcpicfi_sessions: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wpstg0_wc_admin_notes: Dati: 0.08MB + indice: 0.01MB + motore MyISAM
wpstg0_wc_admin_note_actions: Dati: 0.05MB + indice: 0.01MB + motore MyISAM
wpstg0_wc_category_lookup: Dati: 0.00MB + indice: 0.01MB + motore MyISAM
wpstg0_wc_customer_lookup: Dati: 0.01MB + indice: 0.01MB + motore MyISAM
wpstg0_wc_download_log: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpstg0_wc_orders: Dati: 0.02MB + indice: 0.11MB + motore InnoDB
wpstg0_wc_orders_meta: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wpstg0_wc_order_addresses: Dati: 0.02MB + indice: 0.06MB + motore InnoDB
wpstg0_wc_order_coupon_lookup: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpstg0_wc_order_operational_data: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wpstg0_wc_order_product_lookup: Dati: 0.01MB + indice: 0.01MB + motore MyISAM
wpstg0_wc_order_stats: Dati: 0.00MB + indice: 0.01MB + motore MyISAM
wpstg0_wc_order_tax_lookup: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpstg0_wc_product_attributes_lookup: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wpstg0_wc_product_download_directories: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wpstg0_wc_product_meta_lookup: Dati: 0.10MB + indice: 0.12MB + motore MyISAM
wpstg0_wc_rate_limits: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wpstg0_wc_reserved_stock: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpstg0_wc_tax_rate_classes: Dati: 0.00MB + indice: 0.01MB + motore MyISAM
wpstg0_wc_webhooks: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpstg0_wdp_orders: Dati: 0.02MB + indice: 0.05MB + motore InnoDB
wpstg0_wdp_order_items: Dati: 0.02MB + indice: 0.06MB + motore InnoDB
wpstg0_wdp_persistent_rules_cache: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wpstg0_wdp_rules: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wpstg0_wfblockediplog: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wpstg0_wfblocks7: Dati: 0.02MB + indice: 0.05MB + motore InnoDB
wpstg0_wfconfig: Dati: 1.52MB + indice: 0.00MB + motore InnoDB
wpstg0_wfcrawlers: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wpstg0_wffilechanges: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wpstg0_wffilemods: Dati: 48.61MB + indice: 0.00MB + motore InnoDB
wpstg0_wfhits: Dati: 0.45MB + indice: 0.09MB + motore InnoDB
wpstg0_wfhoover: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wpstg0_wfissues: Dati: 0.02MB + indice: 0.06MB + motore InnoDB
wpstg0_wfknownfilelist: Dati: 35.56MB + indice: 0.00MB + motore InnoDB
wpstg0_wflivetraffichuman: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wpstg0_wflocs: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wpstg0_wflogins: Dati: 0.28MB + indice: 0.11MB + motore InnoDB
wpstg0_wfls_2fa_secrets: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wpstg0_wfls_role_counts: Dati: 0.00MB + indice: 0.00MB + motore MEMORY
wpstg0_wfls_settings: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wpstg0_wfnotifications: Dati: 0.09MB + indice: 0.00MB + motore InnoDB
wpstg0_wfpendingissues: Dati: 0.02MB + indice: 0.06MB + motore InnoDB
wpstg0_wfreversecache: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wpstg0_wfsecurityevents: Dati: 0.16MB + indice: 0.00MB + motore InnoDB
wpstg0_wfsnipcache: Dati: 0.02MB + indice: 0.05MB + motore InnoDB
wpstg0_wfstatus: Dati: 1.52MB + indice: 0.36MB + motore InnoDB
wpstg0_wftrafficrates: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wpstg0_wfwaffailures: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wpstg0_woocommerce_api_keys: Dati: 0.00MB + indice: 0.01MB + motore MyISAM
wpstg0_woocommerce_attribute_taxonomies: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpstg0_woocommerce_downloadable_product_permissions: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpstg0_woocommerce_log: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpstg0_woocommerce_order_itemmeta: Dati: 0.07MB + indice: 0.04MB + motore MyISAM
wpstg0_woocommerce_order_items: Dati: 0.01MB + indice: 0.01MB + motore MyISAM
wpstg0_woocommerce_payment_tokenmeta: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpstg0_woocommerce_payment_tokens: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpstg0_woocommerce_sessions: Dati: 62.73MB + indice: 0.10MB + motore MyISAM
wpstg0_woocommerce_shipping_zones: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpstg0_woocommerce_shipping_zone_locations: Dati: 0.03MB + indice: 0.04MB + motore MyISAM
wpstg0_woocommerce_shipping_zone_methods: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpstg0_woocommerce_tax_rates: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpstg0_woocommerce_tax_rate_locations: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpstg0_woof_query_cache: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wpstg0_woof_sd: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wpstg0_woof_sd_presets: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wpstg0_woo_shippment_provider: Dati: 0.14MB + indice: 0.00MB + motore InnoDB
wpstg0_wpforms_tasks_meta: Dati: 0.01MB + indice: 0.00MB + motore MyISAM
wpstg0_wpsr_caches: Dati: 0.14MB + indice: 0.00MB + motore InnoDB
wpstg0_wpsr_optimize_images: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wpstg0_wpsr_reviews: Dati: 0.05MB + indice: 0.00MB + motore InnoDB
wpstg0_wt_iew_action_history: Dati: 0.27MB + indice: 0.00MB + motore InnoDB
wpstg0_wt_iew_mapping_template: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wpstg0_yoast_indexable: Dati: 1.39MB + indice: 0.24MB + motore MyISAM
wpstg0_yoast_indexable_hierarchy: Dati: 0.05MB + indice: 0.11MB + motore MyISAM
wpstg0_yoast_migrations: Dati: 0.00MB + indice: 0.01MB + motore MyISAM
wpstg0_yoast_primary_term: Dati: 0.04MB + indice: 0.05MB + motore MyISAM
wpstg0_yoast_seo_links: Dati: 0.32MB + indice: 0.07MB + motore MyISAM
wpstg0_yoast_seo_meta: Dati: 0.00MB + indice: 0.01MB + motore MyISAM
wp_actionscheduler_actions: Dati: 2.72MB + indice: 1.13MB + motore MyISAM
wp_actionscheduler_claims: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wp_actionscheduler_groups: Dati: 0.00MB + indice: 0.01MB + motore MyISAM
wp_actionscheduler_logs: Dati: 1.78MB + indice: 1.24MB + motore MyISAM
wp_aiowps_events: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wp_aiowps_failed_logins: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wp_aiowps_global_meta: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wp_aiowps_login_activity: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wp_aiowps_login_lockdown: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wp_aiowps_permanent_block: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wp_bwt_failed_submissions: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wp_bwt_passed_submissions: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wp_cartflows_ca_cart_abandonment: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp_cartflows_ca_email_history: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp_cartflows_ca_email_templates: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wp_cartflows_ca_email_templates_meta: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp_cff_facebook_feed_locator: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp_cff_feeds: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp_cff_feed_caches: Dati: 0.08MB + indice: 0.02MB + motore InnoDB
wp_cff_sources: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp_chaty_contact_form_leads: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wp_cky_banners: Dati: 0.05MB + indice: 0.00MB + motore InnoDB
wp_cky_cookies: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wp_cky_cookie_categories: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp_commentmeta: Dati: 0.03MB + indice: 0.01MB + motore MyISAM
wp_comments: Dati: 0.04MB + indice: 0.02MB + motore MyISAM
wp_cr_local_forms: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp_duplicator_packages: Dati: 0.01MB + indice: 0.00MB + motore MyISAM
wp_ewwwio_images: Dati: 2.49MB + indice: 1.25MB + motore MyISAM
wp_ewwwio_queue: Dati: 0.14MB + indice: 0.08MB + motore MyISAM
wp_e_events: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp_gla_attribute_mapping_rules: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wp_gla_budget_recommendations: Dati: 0.19MB + indice: 0.14MB + motore InnoDB
wp_gla_merchant_issues: Dati: 3.02MB + indice: 0.00MB + motore InnoDB
wp_gla_shipping_rates: Dati: 0.02MB + indice: 0.05MB + motore InnoDB
wp_gla_shipping_times: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp_grp_google_place: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wp_grp_google_review: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wp_jetpack_sync_queue: Dati: 0.02MB + indice: 0.06MB + motore InnoDB
wp_jetpack_waf_blocklog: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp_links: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wp_mailchimp_carts: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wp_mailchimp_jobs: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wp_mailpoet_custom_fields: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wp_mailpoet_dynamic_segment_filters: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wp_mailpoet_feature_flags: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wp_mailpoet_forms: Dati: 0.01MB + indice: 0.00MB + motore MyISAM
wp_mailpoet_log: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wp_mailpoet_mapping_to_external_entities: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wp_mailpoet_newsletters: Dati: 0.07MB + indice: 0.00MB + motore MyISAM
wp_mailpoet_newsletter_links: Dati: 0.02MB + indice: 0.02MB + motore MyISAM
wp_mailpoet_newsletter_option: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wp_mailpoet_newsletter_option_fields: Dati: 0.00MB + indice: 0.01MB + motore MyISAM
wp_mailpoet_newsletter_posts: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wp_mailpoet_newsletter_segment: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wp_mailpoet_newsletter_templates: Dati: 2.30MB + indice: 0.00MB + motore MyISAM
wp_mailpoet_scheduled_tasks: Dati: 0.18MB + indice: 0.05MB + motore MyISAM
wp_mailpoet_scheduled_task_subscribers: Dati: 0.01MB + indice: 0.01MB + motore MyISAM
wp_mailpoet_segments: Dati: 0.00MB + indice: 0.01MB + motore MyISAM
wp_mailpoet_sending_queues: Dati: 0.74MB + indice: 0.00MB + motore MyISAM
wp_mailpoet_settings: Dati: 0.02MB + indice: 0.00MB + motore MyISAM
wp_mailpoet_statistics_bounces: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wp_mailpoet_statistics_clicks: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wp_mailpoet_statistics_forms: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wp_mailpoet_statistics_newsletters: Dati: 0.00MB + indice: 0.01MB + motore MyISAM
wp_mailpoet_statistics_opens: Dati: 0.00MB + indice: 0.01MB + motore MyISAM
wp_mailpoet_statistics_unsubscribes: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wp_mailpoet_statistics_woocommerce_purchases: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wp_mailpoet_stats_notifications: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wp_mailpoet_subscribers: Dati: 0.02MB + indice: 0.04MB + motore MyISAM
wp_mailpoet_subscriber_custom_field: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wp_mailpoet_subscriber_ips: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wp_mailpoet_subscriber_segment: Dati: 0.02MB + indice: 0.03MB + motore MyISAM
wp_mailpoet_user_agents: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp_mailpoet_user_flags: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wp_mo_openid_linked_user: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wp_ms_snippets: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wp_nf3_actions: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wp_nf3_action_meta: Dati: 0.01MB + indice: 0.00MB + motore MyISAM
wp_nf3_chunks: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wp_nf3_fields: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wp_nf3_field_meta: Dati: 0.02MB + indice: 0.01MB + motore MyISAM
wp_nf3_forms: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wp_nf3_form_meta: Dati: 0.01MB + indice: 0.00MB + motore MyISAM
wp_nf3_objects: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wp_nf3_object_meta: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wp_nf3_relationships: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wp_nf3_upgrades: Dati: 0.02MB + indice: 0.00MB + motore MyISAM
wp_options: Dati: 20.37MB + indice: 0.66MB + motore MyISAM
wp_postmeta: Dati: 26.38MB + indice: 4.49MB + motore MyISAM
wp_posts: Dati: 34.73MB + indice: 0.65MB + motore MyISAM
wp_pum_subscribers: Dati: 0.02MB + indice: 0.06MB + motore InnoDB
wp_sbi_feeds: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp_sbi_feed_caches: Dati: 0.05MB + indice: 0.02MB + motore InnoDB
wp_sbi_instagram_feeds_posts: Dati: 0.01MB + indice: 0.01MB + motore MyISAM
wp_sbi_instagram_feed_locator: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wp_sbi_instagram_posts: Dati: 0.18MB + indice: 0.00MB + motore MyISAM
wp_sbi_sources: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp_sib_model_contact: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wp_sib_model_country: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wp_sib_model_forms: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wp_sib_model_users: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wp_smush_dir_images: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wp_snippets: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wp_termmeta: Dati: 0.20MB + indice: 0.13MB + motore MyISAM
wp_terms: Dati: 0.03MB + indice: 0.06MB + motore MyISAM
wp_term_relationships: Dati: 0.19MB + indice: 0.45MB + motore MyISAM
wp_term_taxonomy: Dati: 0.07MB + indice: 0.04MB + motore MyISAM
wp_tinvwl_analytics: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp_tinvwl_items: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wp_tinvwl_lists: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wp_usermeta: Dati: 4.21MB + indice: 0.34MB + motore MyISAM
wp_users: Dati: 0.04MB + indice: 0.04MB + motore MyISAM
wp_wcpdf_invoice_number: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wp_wcpdf_packing_slip_number: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wp_wcpicfi_sessions: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp_wc_admin_notes: Dati: 0.09MB + indice: 0.01MB + motore MyISAM
wp_wc_admin_note_actions: Dati: 0.05MB + indice: 0.02MB + motore MyISAM
wp_wc_category_lookup: Dati: 0.00MB + indice: 0.01MB + motore MyISAM
wp_wc_customer_lookup: Dati: 0.01MB + indice: 0.01MB + motore MyISAM
wp_wc_download_log: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wp_wc_orders: Dati: 0.02MB + indice: 0.11MB + motore InnoDB
wp_wc_orders_meta: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp_wc_order_addresses: Dati: 0.02MB + indice: 0.06MB + motore InnoDB
wp_wc_order_coupon_lookup: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wp_wc_order_operational_data: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp_wc_order_product_lookup: Dati: 0.01MB + indice: 0.01MB + motore MyISAM
wp_wc_order_stats: Dati: 0.00MB + indice: 0.01MB + motore MyISAM
wp_wc_order_tax_lookup: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wp_wc_product_attributes_lookup: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp_wc_product_download_directories: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp_wc_product_meta_lookup: Dati: 0.12MB + indice: 0.15MB + motore MyISAM
wp_wc_rate_limits: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp_wc_reserved_stock: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wp_wc_tax_rate_classes: Dati: 0.00MB + indice: 0.01MB + motore MyISAM
wp_wc_webhooks: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wp_wdp_orders: Dati: 0.02MB + indice: 0.05MB + motore InnoDB
wp_wdp_order_items: Dati: 0.02MB + indice: 0.06MB + motore InnoDB
wp_wdp_persistent_rules_cache: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wp_wdp_rules: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp_wfblockediplog: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wp_wfblocks7: Dati: 0.02MB + indice: 0.05MB + motore InnoDB
wp_wfconfig: Dati: 2.27MB + indice: 0.00MB + motore InnoDB
wp_wfcrawlers: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wp_wffilechanges: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wp_wffilemods: Dati: 74.64MB + indice: 0.00MB + motore InnoDB
wp_wfhits: Dati: 1.02MB + indice: 0.19MB + motore InnoDB
wp_wfhoover: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp_wfissues: Dati: 0.02MB + indice: 0.06MB + motore InnoDB
wp_wfknownfilelist: Dati: 35.56MB + indice: 0.00MB + motore InnoDB
wp_wflivetraffichuman: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp_wflocs: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wp_wflogins: Dati: 0.08MB + indice: 0.03MB + motore InnoDB
wp_wfls_2fa_secrets: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp_wfls_role_counts: Dati: 0.00MB + indice: 0.00MB + motore MEMORY
wp_wfls_settings: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wp_wfnotifications: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wp_wfpendingissues: Dati: 0.02MB + indice: 0.06MB + motore InnoDB
wp_wfreversecache: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wp_wfsecurityevents: Dati: 0.09MB + indice: 0.00MB + motore InnoDB
wp_wfsnipcache: Dati: 0.02MB + indice: 0.05MB + motore InnoDB
wp_wfstatus: Dati: 1.02MB + indice: 0.09MB + motore InnoDB
wp_wftrafficrates: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wp_wfwaffailures: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wp_woof_query_cache: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wp_woof_sd: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wp_woof_sd_presets: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wp_woo_shippment_provider: Dati: 0.16MB + indice: 0.00MB + motore InnoDB
wp_wpforms_tasks_meta: Dati: 0.01MB + indice: 0.00MB + motore MyISAM
wp_wpsr_caches: Dati: 0.14MB + indice: 0.00MB + motore InnoDB
wp_wpsr_optimize_images: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wp_wpsr_reviews: Dati: 0.05MB + indice: 0.00MB + motore InnoDB
wp_wt_iew_action_history: Dati: 0.13MB + indice: 0.00MB + motore InnoDB
wp_wt_iew_mapping_template: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wp_yoast_indexable: Dati: 1.33MB + indice: 0.33MB + motore MyISAM
wp_yoast_indexable_hierarchy: Dati: 0.07MB + indice: 0.21MB + motore MyISAM
wp_yoast_migrations: Dati: 0.00MB + indice: 0.01MB + motore MyISAM
wp_yoast_primary_term: Dati: 0.04MB + indice: 0.06MB + motore MyISAM
wp_yoast_seo_links: Dati: 0.86MB + indice: 0.17MB + motore MyISAM
wp_yoast_seo_meta: Dati: 0.00MB + indice: 0.01MB + motore MyISAM

### Post Type Counts ###

attachment: 2139
custom_css: 6
customize_changeset: 2
elementor_library: 8
feedback: 1
instagram_shortcodes: 1
jb_store_css: 1
mailpoet_page: 1
mc4wp-form: 1
nav_menu_item: 69
nf_sub: 6
ocean_modal_window: 2
oceanwp_library: 8
oembed_cache: 2
page: 37
popup: 5
popup_theme: 8
post: 9
product: 1371
product_variation: 207
revision: 1642
rmp_menu: 2
shop_coupon: 3
shop_order: 51
shop_order_refund: 1
sp_wps_shortcodes: 2
watermark: 1
wcps: 1
wcps_layout: 1
wp_global_styles: 1
wp_social_reviews: 5
wpcode: 10
wpforms: 2
wpsr_social_chats: 1
yith_wcan_preset: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (72) ###

Akismet Anti-spam: Spam Protection: by Automattic - Squadra antispam – 5.3
Aruba HiSpeed Cache: by Aruba.it – 2.0.7
Bing Webmaster Url Submission: by Bing Webmaster – 1.0.13
Bot for Telegram on WooCommerce: by guru-team – 1.2.4
Check Conflicts: by ioannup – 1.1.6
Click to Chat: by HoliThemes – 3.31
Code Snippets: by Code Snippets Pro – 3.6.2
Colorlib Login Customizer: by Colorlib – 1.3.1
CookieYes | GDPR Cookie Consent: by CookieYes – 3.1.7
Smash Balloon Custom Facebook Feed: by Smash Balloon – 4.2
Customer Reviews for WooCommerce: by CusRev – 5.38.8
EAN for WooCommerce: by WPFactory – 4.8.8
Elementor: by Elementor.com – 3.18.3
EWWW Image Optimizer: by Exactly WWW – 7.2.2
Facebook for WooCommerce: by Facebook – 3.1.6
Flexible Shipping: by Octolize – 4.24.6
Gallery Slider for WooCommerce: by WooGallery Slider Team
ShapedPlugin LLC – 2.0.0

Google Listings and Ads: by WooCommerce – 2.5.14
WPCode Lite: by WPCode – 2.1.7
Feed Instagram di Smash Balloon: by Smash Balloon – 6.2.6
Jetpack Boost: by Automattic - Il team Jetpack Site Speed – 2.2.1
Jetpack: by Automattic – 12.9.3
Loco Translate: by Tim Whitlock – 2.6.6
Newsletter, SMTP, Email marketing and Subscribe forms by Brevo: by Brevo – 3.1.72
Members: by MemberPress – 3.2.9
Social Login, Social Sharing by miniOrange: by <a href="https://www.miniorange.com/">miniOrange</a> – 7.6.7
Ninja Forms: by Saturday Drive – 3.7.0
Ocean Elementor Widgets: by OceanWP – 2.4.1
Ocean Extra: by OceanWP – 2.2.4
Ocean Hooks: by OceanWP – 2.1.0
Ocean Instagram: by OceanWP – 1.2.2
Ocean Modal Window: by OceanWP – 2.2.0
Ocean Pro Demos: by OceanWP – 1.4.7
Ocean Product Sharing: by OceanWP – 2.0.8
Ocean Social Sharing: by OceanWP – 2.0.6
Ocean Stick Anything: by OceanWP – 2.0.7
Ocean Woo Popup: by OceanWP – 2.0.7
Perfect Brands for WooCommerce: by QuadLayers – 3.2.9
Popup Maker: by Popup Maker – 1.18.2
Product Import Export for WooCommerce: by WebToffee – 2.3.8
Really Simple SSL: by Really Simple Plugins – 7.2.1
Super Progressive Web Apps: by Super PWA – 2.2.23.1
Tawk.to Live Chat: by Tawkto – 0.8.2
TI WooCommerce Wishlist: by TemplateInvaders – 2.8.0
Trustpilot-reviews: by Trustpilot – 2.5.925
WC Hide Shipping Methods: by Rynaldo Stoltz – 1.5
WooCommerce Smart COD: by woosmartcod.com – 1.7.1
Monitoraggio avanzato della spedizione per WooCommerce: by zorem – 3.6.4
WooCommerce Cart Abandonment Recovery: by CartFlows Inc – 1.2.26
Checkout Field Editor for WooCommerce: by ThemeHigh – 2.0.0
WooCommerce P.IVA e Codice Fiscale per Italia: by dot4all – 2.1.11
Product Slider for WooCommerce: by ShapedPlugin LLC – 2.6.9
WooCommerce Checkout Manager: by QuadLayers – 7.4.1
WooCommerce Stripe Gateway: by WooCommerce – 7.8.0
WooCommerce Google Analytics Integration: by WooCommerce – 1.8.11
WooPayments: by Automattic – 6.9.2
WooCommerce PayPal Payments: by WooCommerce – 2.4.2
PDF Invoices & Packing Slips for WooCommerce: by WP Overnight – 3.7.5
HUSKY - Products Filter Professional for WooCommerce: by realmag777 – 1.3.4.5
Brevo - WooCommerce Email Marketing: by Brevo – 4.0.7
WooCommerce Shipping & Tax: by WooCommerce – 2.4.2
WooCommerce: by Automattic – 8.4.0
ShopLentor – WooCommerce Builder for Elementor & Gutenberg: by HasThemes – 2.7.6
Wordfence Security: by Wordfence – 7.11.0
Yoast SEO: by Team Yoast – 21.7
WP Content Copy Protection & No Right Click: by wp-buy – 3.5.7
WP Social Ninja: by WP Social Ninja Team - WPManageNinja LLC – 3.12.1
WP STAGING - Backup Duplicator & Migration: by WP-STAGING
WPStagingBackup – 3.1.4

WPS Hide Login: by WPServeur
NicolasKulka
wpformation – 1.9.10

WP Telegram Login: by WP Socio – 1.10.7
WP Telegram: by WP Socio – 4.0.14
Zeus For Elementor: by UranusWP – 1.0.7

### Inactive Plugins (9) ###

Advanced noCaptcha & invisible Captcha: by WP White Security – 6.1.7
Import and export users and customers: by codection – 1.24.7
Max Mega Menu: by megamenu.com – 3.3
Menu Image: by Freshlight Lab – 3.10
Product GTIN (EAN, UPC, ISBN) for WooCommerce: by Emanuela Castorina – 1.1.1
Ultimate Social Media PLUS: by social share pro – 3.6.1
WooCommerce Blocks: by Automattic – 11.7.0
WooCommerce PayPal Checkout Gateway: by WooCommerce – 2.1.3
WP Fastest Cache: by Emre Vona – 1.2.2

### Must Use Plugins (1) ###

WP STAGING Optimizer: by WP STAGING – 1.5.5

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: EUR (€)
Currency Position: left
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to Woo.com: ✔
Enforce Approved Product Download Directories: –
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### WC Pages ###

Shop base: #500 - /shop/
Carrello: #501 - /carrello/
Pagamento: #502 - /checkout-2/
Il mio account: #10 - /mio-account/
Termini e condizioni: #1052 - /politica-dei-resi/

### Theme ###

Name: OceanWP Child
Version: 1.0
Author URL: https://oceanwp.org/
Child Theme: ✔
Parent Theme Name: OceanWP
Parent Theme Version: 3.5.3
Parent Theme Author URL: https://oceanwp.org/about-oceanwp/
WooCommerce Support: ✔

### Templates ###

Overrides: oceanwp/woocommerce/cart/mini-cart.php
oceanwp/woocommerce/content-single-product.php
oceanwp-child-theme-master/woocommerce/emails/customer-on-hold-order.php
oceanwp/woocommerce/loop/loop-start.php
oceanwp/woocommerce/single-product/product-image.php
oceanwp/woocommerce/single-product/title.php

### WooPayments ###

Version: 6.9.2
Connected to WPCOM: Sì
WPCOM Blog ID: 175558567
Account ID: acct_1L3cXM2HbZlRLGR2
Payment Gateway: Abilitato
Test Mode: Disabilitato
UPE: Abilitato (deferred_intent)
UPE Enabled APMs: card
WooPay: Non idoneo
Apple Pay / Google Pay: Abilitato (product,cart,checkout)
Fraud Protection Level: basic
Multi-currency: Abilitato
Public Key Encryption: Disabilitato
Auth and Capture: Abilitato
Documents: Abilitato
Logging: Disabilitato

### WooCommerce PayPal Payments ###

Onboarded: ✔
Shop country code: IT
WooCommerce currency supported: ✔
Advanced Card Processing available in country: ✔
Pay Later messaging available in country: ✔
Webhook status: –
PayPal Vault enabled: –
ACDC Vault enabled: –
Logging enabled: –
Reference Transactions: –
Used PayPal Checkout plugin: ✔
Subscriptions Mode: Disabled

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
product-virtual-downloadable
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: customize-store
minified-js
new-product-management-experience
product-external-affiliate
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2023-12-28 23:21:57 +01:00
Options: ✔
Notes: 193
Onboarding: completed

### TI WooCommerce Wishlist Templates ###

Overrides: –

### Action Scheduler ###

Completato: 7.017
Oldest: 2023-11-27 08:51:12 +0100
Newest: 2023-12-28 07:51:44 +0100

Operazione non riuscita: 1.697
Oldest: 2020-10-28 10:29:11 +0100
Newest: 2023-12-27 11:31:23 +0100

In attesa: 5
Oldest: 2023-12-28 15:42:49 +0100
Newest: 2024-01-01 15:14:01 +0100

### Status report information ###

Generated at: 2023-12-28 08:11:51 +01:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by albarin**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes https://github.com/woocommerce/woocommerce/issues/43149

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Go to `WooCommerce > Products`.
2. Select a product from the list.
3. Click on `Bulk actions`, select `Edit`, and click the `Apply` button.
4. Click on the `Sale` input and select `Decrease existing sale price by (fixed amount or %):`.
5. Enter a percentage sale (like 10%) click `Update`, and check the product is on sale and the price is decreased in the percentage you entered.
6. Update the price and remove the sale price.
7. Repeat steps 2-5 with the `Increase existing sale price by (fixed amount or %):` option.

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [x] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 
Product bulk edit: fix increasing & decreasing sale price when there was no previous sale.
</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

**Comment by Marc-pi** [comment]
@albarin hello, glad to see you're working on this
can you have a look at this https://github.com/woocommerce/woocommerce/issues/36802 (variable product case)
from the issue you mentionned (in italian), it's hard to know if this case is covered
thx

File: plugins/woocommerce/includes/admin/class-wc-admin-post-types.php [hunk 1]
```diff
@@ -897,6 +897,7 @@ private function set_new_price( $product, $price_type ) {
 		}
 
 		$old_price     = (float) $product->{"get_{$price_type}_price"}();
+		$old_price     = ! $old_price ? (float) $product->get_regular_price() : $old_price;
```
Comment (imanish003) [inline plugins/woocommerce/includes/admin/class-wc-admin-post-types.php]: I have a question about this code. What happens when `$old_price` is `0`? Imagine the following situation:

1. Product price is `100` (regular price)
2. Product is put on sale for `0` (sale price)
3. User increases sale price by 10%. The new sale price should be `10`.

But in above code, `$old_price` will be `0`. Therefore, `! $old_price` will be `true` and `$old_price` will be set to the regular price, which is `100`. So the new price will be `100` instead of `10`.

Does it make sense? I believe we should handle this case. Let me know in case I am missing something 🙂

**Review by imanish003 — CHANGES_REQUESTED** [review]

File: plugins/woocommerce/includes/admin/class-wc-admin-post-types.php (hunk 1 above)
Comment (albarin) [reply plugins/woocommerce/includes/admin/class-wc-admin-post-types.php]: @imanish003 Good catch! The case where `$old_price` is `0` is wrong, but I'm not sure if should be `10` in the case you mention.
The increase & decrease percentages are calculated from the existing sale amount, not from the product price.
For example:

1. Product price is `100` (regular price)
2. Product is put on sale for `10` (sale price)
3. User increases sale price by 10%. The new sale price will be `11`, not `20` (because 10% of 10 is 1, 10+1=11).

So, following this logic, in the case you mention, the new price should still be `0`, since 10% of `0` is still `0`.
I know it's a bit weird, wdyt?

Comment (imanish003) [reply plugins/woocommerce/includes/admin/class-wc-admin-post-types.php]: > So, following this logic, in the case you mention, the new price should still be 0, since 10% of 0 is still 0.
> I know it's a bit weird, wdyt?

Ah! I see what you mean. You are right. It should still be 0. 
But in case user increases the sale price by fixed amount i.e. 10, then the new price will be 10. Right?

Comment (albarin) [reply plugins/woocommerce/includes/admin/class-wc-admin-post-types.php]: That's correct!
I'll push a fix soon 🙌

**Review by imanish003 — APPROVED** [review]
Hey Alba! Changes look good to me. Thanks for also handling the edge case 🚀
