### PR TITLE
Toggle Visibility doesn't seem to work always as it should in the product variations

### LINKED ISSUE #44467: Toggle Visibility doesn't seem to work always as it should in the product variations
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When trying to bulk toggle visibility for some variations in the new product editor, it doesn't seem to work always, just once. This may be because when expanding variations something occurs the ability to toggle all previously selected variations, it works if I manually select them again.

### Expected behavior

Variations visibility toggled on or off

### Actual behavior

Variations visibility toggled off always until again selected

### Steps to reproduce

1. Make sure you have some products and attributes with values
2. Go to a new product editor
3. Click on Variations tab
4. Add variations by selecting any attribute and values
5. Make sure to have more than 5, e.g. 10 or 15 results present
6. Select some variations and then click Quick Update button and then Toggle Visibility
7. You should see variations toggled off
8. Click again Quick Update and then Toggle Visibility
9. Observe issue

Check this video for reproduction: https://d.pr/i/0oZtGx

### WordPress Environment

N/A

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by mdperez86**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes #44467

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Make sure feature `New product editor` is enabled under `/wp-admin/admin.php?page=wc-settings&tab=advanced&section=features`
2. Make sure feature `product-variation-management` is enabled under `Features` tab from `/wp-admin/tools.php?page=woocommerce-admin-test-helper` (WooCommerce Beta Tester plugin) is required
3. Go to `/wp-admin/admin.php?page=wc-admin&path=/add-product`
4. Under the `Variations` tab, add some `Variation options` to generate many variations.
5. Once generated select some of them form the `Variations` table then click on `Quick update` menu and then click `Set list price` from the menu and add the price you want to the selected variations.
image

6. The table should looks like 
image

7. Note that the selected variations should remain checked.
8. Then click on `Quick update` menu again and select `Toggle visibility` 
image

9. The table now should looks like 
image

10. Doing the point 8 again should revert the table state to the one in point 6 

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Comment 

</details>

### CODE REVIEW

File: packages/js/product-editor/src/components/variations-table/use-variations/use-variations.ts [hunk 1]
```diff
@@ -371,14 +374,18 @@ export function useVariations( { productId }: UseVariationsProps ) {
...
-			for ( const variation of subset ) {
+			for ( const variation of updatedVariations ) {
 				await coreInvalidateResolution( 'getEntityRecord', [
 					'postType',
 					'product_variation',
 					variation.id,
 				] );
+
+				selectedVariationsRef.current[ variation.id ] = variation;
+				setSelectedCount( ( current ) => current + 1 );
```
Comment (louwie17) [inline packages/js/product-editor/src/components/variations-table/use-variations/use-variations.ts:388]: Do we need to call this within this loop?
Couldn't we just call it outside of this loop by using `Object.keys(selectedVariationsRef.current).length`?

File: packages/js/product-editor/src/components/variations-table/use-variations/use-variations.ts [hunk 2]
```diff
@@ -340,6 +340,9 @@ export function useVariations( { productId }: UseVariationsProps ) {
 		const { batchUpdateProductVariations, invalidateResolutionForStore } =
 			dispatch( EXPERIMENTAL_PRODUCT_VARIATIONS_STORE_NAME );
 
+		selectedVariationsRef.current = {};
+		setSelectedCount( 0 );
```
Comment (louwie17) [inline packages/js/product-editor/src/components/variations-table/use-variations/use-variations.ts:344]: I understand resetting the selectedVariationsRef, but is it needed to explicitly set the selected count to 0, if we are explicitly setting it within the for loop already?

File: packages/js/product-editor/src/components/variations-table/use-variations/use-variations.ts [hunk 3]
```diff
@@ -432,16 +442,18 @@ export function useVariations( { productId }: UseVariationsProps ) {
...
+			for ( const variation of deletedVariations ) {
 				await coreInvalidateResolution( 'getEntityRecord', [
 					'postType',
 					'product_variation',
 					variation.id,
 				] );
 
-				onSelect( variation as never )( false );
+				delete selectedVariationsRef.current[ variation.id ];
+				setSelectedCount( ( current ) => current - 1 );
```
Comment (louwie17) [inline packages/js/product-editor/src/components/variations-table/use-variations/use-variations.ts:456]: Similar comment to the above, given `setSelectedCount` changes a state, how will this affect rendering when we do it in a for loop? Or will they all get combined into a single render?

**Review by louwie17 — COMMENTED** [review]
This tested well, I am just not entire sure about the `setSelected` approach, let me know what you think ( I left more thoughts in the inline comment ).

File: packages/js/product-editor/src/components/variations-table/use-variations/use-variations.ts (hunk 1 above)
Comment (mdperez86) [reply packages/js/product-editor/src/components/variations-table/use-variations/use-variations.ts:388]: Well I need to call `setSelectedCount` to produce a change in the `selected` variations to notify the consumers, this call can be made for the whole batch update, but since the UI manage to show partial updated data chunks then it is nicer to notify consumers per chunk. Meaning the notification must happens within the while loop to achieve that. Then it does not matter if I keep the notification within the for loop or move it outside of it, react batches the update and execute it at the right moment. But if you strongly consider this needs to be moved out of the for loop, I can change it to `setSelectedCount( ( current ) => current + updatedVariations.length );` instead.

Comment (louwie17) [reply packages/js/product-editor/src/components/variations-table/use-variations/use-variations.ts:388]: No that's fine then, I just wanted to know the reasoning and double check if it affected the React rendering state.
Your consensus makes sense.

File: packages/js/product-editor/src/components/variations-table/use-variations/use-variations.ts (hunk 3 above)
Comment (mdperez86) [reply packages/js/product-editor/src/components/variations-table/use-variations/use-variations.ts:456]: Yep, something like that. It is called [React state batch update](https://react.dev/learn/queueing-a-series-of-state-updates)

**Review by louwie17 — APPROVED** [review]
Approving given this reply from @mdperez86 providing some extra context about the `setSelectedCount` changes: https://github.com/woocommerce/woocommerce/pull/44508#discussion_r1484676582

File: packages/js/product-editor/src/components/variations-table/use-variations/use-variations.ts (hunk 2 above)
Comment (mdperez86) [reply packages/js/product-editor/src/components/variations-table/use-variations/use-variations.ts:344]: As you can see I'm incrementing the count within the loop, if I don't reset this here to 0 then the final amount could mismatch with the selected variations.
