### PR TITLE
Brands: Clear thumbnail after creating a brand

### LINKED ISSUE #51576: Clear form after adding a new Brand
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When creating a new Brand via Products > Brands and clicking the submit button, then the form is not fully cleared -- the thumbnail selection remains. When creating a new Category on the other hand, the entire form is cleared (including the thumbnail).

### Expected behavior

Clear the thumbnail selection after creating a new brand.

### Actual behavior

The previously selected thumbnail remains after creating a new brand. 

### Steps to reproduce

1. Go to Products > Brands. 
2. Create a new brand -- make sure that you select a thumbnail. 
3. Click to submit the form. 
4. Ensure that all fields, except for the thumbnail, are cleared. 

### WordPress Environment

Clean WP/Woo installation. 

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by tyxla**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Resets the thumbnail field after creating a new brand.

This uses the same approach that we currently use for product categories. Note that the code still uses jQuery, so there are a few potential follow-up opportunities here:
- Unify the additional taxonomy management code with product categories
- Move away from jQuery

Closes #51576.
Closes WOOPLUG-2606.

### Screenshots or screen recordings:

Before:

https://github.com/user-attachments/assets/8c9cdd78-5c41-48c5-bad9-94d89ff457f2

After:

https://github.com/user-attachments/assets/0f7c248f-daa4-4b6c-954d-97f9bb6a0970

### How to test the changes in this Pull Request:

1. Go to Brands (`/wp-admin/edit-tags.php?taxonomy=product_brand&post_type=product`)
2. Create a new brand, choosing a thumbnail
3. Verify that the thumbnail is erased after creating the brand.

### Testing that has already taken place:

Manual testing as per the testing instructions. 

### Milestone

- [x] Automatically assign milestone for the **[next WooCommerce version](../blob/trunk/plugins/woocommerce/woocommerce.php#L6)**

> **Note:** Check the box above to have the milestone automatically assigned when merged.
> Alternatively (e.g. for point releases), manually assign the appropriate milestone.

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

Brands: Clear thumbnail after creating a brand

</details>

### CODE REVIEW

File: plugins/woocommerce/includes/admin/class-wc-admin-brands.php [hunk 1]
```diff
@@ -370,6 +370,23 @@ public function add_thumbnail_field() {
...
+								return;
+							}
+							// Clear Thumbnail fields on submit
+							jQuery( '#product_cat_thumbnail' ).find( 'img' ).attr( 'src', '<?php echo esc_js( wc_placeholder_img_src() ); ?>' );
+							jQuery( '#product_cat_thumbnail_id' ).val( '' );
+							jQuery( '.remove_image_button' ).hide();
+
+							return;
+						}
+					} );
```
[the remark this answers is not in the document]
Comment (tyxla) [reply plugins/woocommerce/includes/admin/class-wc-admin-brands.php:391]: No need for this extra guard IMO

File: plugins/woocommerce/includes/admin/class-wc-admin-brands.php [hunk 2]
```diff
@@ -370,6 +370,23 @@ public function add_thumbnail_field() {
...
+							&& options.data && 0 <= options.data.indexOf( 'action=add-tag' ) ) {
+
+							var res = wpAjax.parseAjaxResponse( request.responseXML, 'ajax-response' );
+							if ( ! res || res.errors ) {
+								return;
+							}
+							// Clear Thumbnail fields on submit
+							jQuery( '#product_cat_thumbnail' ).find( 'img' ).attr( 'src', '<?php echo esc_js( wc_placeholder_img_src() ); ?>' );
+							jQuery( '#product_cat_thumbnail_id' ).val( '' );
+							jQuery( '.remove_image_button' ).hide();
```
Comment (kmanijak) [inline plugins/woocommerce/includes/admin/class-wc-admin-brands.php]: > Unify the additional taxonomy management code with product categories

Yeah this is an opportunity but given they're in separate scripts/scopes I wouldn't invest in unifying it.

However, this part is nearly exactly the same as `jQuery(document).on( 'click', '.remove_image_button',` callback within the same scope. How about extracting it to the function (something like `clearThumbnailField`) and reuse it in both places?

**Review by kmanijak — APPROVED** [review]
It's testing well, Thumbnail is cleared upon creating a brand, !

I left one minor comment but pre-approving otherwise.

It's a nice UX improvement!

File: plugins/woocommerce/includes/admin/class-wc-admin-brands.php (hunk 2 above)
Comment (tyxla) [reply plugins/woocommerce/includes/admin/class-wc-admin-brands.php]: Nice suggestion, thanks! Addressed in f80c07f54c955e70187e8f1d13f2cba1c0954ae4
