### PR TITLE
Fix/issue 36668: Shows warning only when the variation price is empty

### LINKED ISSUE #36668: No price variation warning shows for zero priced variations.
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When using variations and setting a variation Regular price to $0, the message appears above the variations:
 "1 variation does not have a price. Variations (and their attributes) that do not have prices will not be shown in your store."
This should only appear when the variation price is left blank

### Expected behavior

This message should only appear when the Regular price is left blank.

### Actual behavior

Adding a variation with a 0 price shows the warning that is for having a blank price.

### Steps to reproduce

Create a variation and have one product with a 0 price. The message will appear.

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://kalamundalearningcentre.org.au
Site address (URL): https://kalamundalearningcentre.org.au
WC Version: 7.2.2
REST API Version: ✔ 7.2.2
WC Blocks Version: ✔ 8.9.2
Action Scheduler Version: ✔ 3.5.2
Log Directory Writable: ✔
WP Version: 6.1.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_AU
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.54 (Unix) OpenSSL/1.1.1f
PHP Version: 8.1.12
PHP Post Max Size: 256 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.68.0
OpenSSL/1.1.1f

SUHOSIN Installed: –
MySQL Version: 10.4.27-MariaDB-1:10.4.27+maria~ubu2004-log
Max Upload Size: 256 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.2.2
WC Database Prefix: wp_
Total Database Size: 196.44MB
Database Data Size: 143.12MB
Database Index Size: 53.32MB
wp_woocommerce_sessions: Data: 2.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 1.52MB + Index: 1.52MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 12.52MB + Index: 11.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.49MB + Index: 0.25MB + Engine MyISAM
wp_actionscheduler_claims: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_actionscheduler_groups: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_actionscheduler_logs: Data: 0.37MB + Index: 0.25MB + Engine MyISAM
wp_ac_segments: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_admin_columns: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_aiowps_events: Data: 0.20MB + Index: 0.00MB + Engine InnoDB
wp_aiowps_failed_logins: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
wp_aiowps_global_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_aiowps_login_activity: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_aiowps_login_lockdown: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_aiowps_permanent_block: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_aws_cache: Data: 0.04MB + Index: 0.00MB + Engine MyISAM
wp_aws_index: Data: 1.28MB + Index: 0.00MB + Engine InnoDB
wp_better_user_search_meta_keys: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_cff_facebook_feed_locator: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_cff_feeds: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_cff_feeds_posts: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_cff_feed_caches: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_cff_posts: Data: 0.09MB + Index: 0.00MB + Engine InnoDB
wp_cff_sources: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.08MB + Index: 0.08MB + Engine MyISAM
wp_comments: Data: 6.23MB + Index: 2.72MB + Engine MyISAM
wp_facetwp_index: Data: 0.06MB + Index: 0.05MB + Engine InnoDB
wp_failed_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_itsec_bans: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_itsec_dashboard_events: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_itsec_distributed_storage: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_itsec_fingerprints: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_itsec_geolocation_cache: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_itsec_lockouts: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_itsec_logs: Data: 0.36MB + Index: 0.11MB + Engine InnoDB
wp_itsec_mutexes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_itsec_opaque_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_itsec_temp: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_itsec_user_groups: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_itsec_webauthn_credentials: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_itsec_webauthn_users: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_links: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mailchimp_carts: Data: 0.09MB + Index: 0.00MB + Engine InnoDB
wp_mailchimp_jobs: Data: 0.02MB + Index: 0.00MB + Engine MyISAM
wp_mail_catcher_logs: Data: 10.52MB + Index: 0.00MB + Engine InnoDB
wp_mepr_events: Data: 1.13MB + Index: 1.36MB + Engine MyISAM
wp_mepr_jobs: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mepr_members: Data: 0.12MB + Index: 0.41MB + Engine MyISAM
wp_mepr_rule_access_conditions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mepr_subscriptions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mepr_subscription_meta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mepr_tax_rates: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mepr_tax_rate_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mepr_transactions: Data: 0.39MB + Index: 0.83MB + Engine MyISAM
wp_mepr_transaction_meta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_msf_fileds: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nf3_actions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nf3_action_meta: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_nf3_chunks: Data: 0.19MB + Index: 0.00MB + Engine MyISAM
wp_nf3_fields: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nf3_field_meta: Data: 0.45MB + Index: 0.00MB + Engine InnoDB
wp_nf3_forms: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nf3_form_meta: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_nf3_objects: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nf3_object_meta: Data: 0.23MB + Index: 0.00MB + Engine InnoDB
wp_nf3_relationships: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nf3_upgrades: Data: 0.39MB + Index: 0.00MB + Engine MyISAM
wp_ngg_album: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_ngg_gallery: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_ngg_pictures: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
wp_options: Data: 11.95MB + Index: 0.31MB + Engine MyISAM
wp_pmxe_exports: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
wp_pmxe_google_cats: Data: 0.39MB + Index: 0.00MB + Engine InnoDB
wp_pmxe_posts: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
wp_pmxe_templates: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_files: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_hash: Data: 0.13MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_history: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_images: Data: 0.02MB + Index: 0.01MB + Engine MyISAM
wp_pmxi_imports: Data: 0.39MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_posts: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_templates: Data: 0.16MB + Index: 0.00MB + Engine InnoDB
wp_postmark_log: Data: 6.52MB + Index: 0.00MB + Engine InnoDB
wp_postmeta: Data: 29.66MB + Index: 19.10MB + Engine MyISAM
wp_posts: Data: 22.43MB + Index: 1.96MB + Engine MyISAM
wp_power_stats_browsers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_power_stats_os: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_power_stats_pageviews: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_power_stats_posts: Data: 0.14MB + Index: 0.11MB + Engine InnoDB
wp_power_stats_referers: Data: 0.36MB + Index: 0.00MB + Engine InnoDB
wp_power_stats_searches: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_power_stats_visits: Data: 1.52MB + Index: 0.16MB + Engine InnoDB
wp_po_plugins: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_pta_sus_sheets: Data: 0.07MB + Index: 0.01MB + Engine MyISAM
wp_pta_sus_signups: Data: 0.07MB + Index: 0.05MB + Engine MyISAM
wp_pta_sus_tasks: Data: 0.16MB + Index: 0.04MB + Engine MyISAM
wp_queue: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_redirection_404: Data: 5.89MB + Index: 1.46MB + Engine MyISAM
wp_redirection_groups: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_redirection_items: Data: 0.00MB + Index: 0.02MB + Engine MyISAM
wp_redirection_logs: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_revslider_css: Data: 0.09MB + Index: 0.00MB + Engine MyISAM
wp_revslider_layer_animations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_revslider_navigations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_revslider_sliders: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_revslider_slides: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_revslider_static_slides: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_searchwp_index: Data: 1.52MB + Index: 1.23MB + Engine InnoDB
wp_searchwp_log: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_searchwp_status: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_searchwp_tokens: Data: 0.09MB + Index: 0.16MB + Engine InnoDB
wp_simple_history: Data: 0.19MB + Index: 0.13MB + Engine InnoDB
wp_simple_history_contexts: Data: 1.52MB + Index: 1.80MB + Engine InnoDB
wp_simple_login_log: Data: 3.52MB + Index: 0.44MB + Engine InnoDB
wp_sm_advanced_search_temp: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_sm_views: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_stb_styles: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_supsystic_tbl_columns: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_supsystic_tbl_diagrams: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_supsystic_tbl_rows: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
wp_supsystic_tbl_tables: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_termmeta: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wp_terms: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_term_relationships: Data: 0.07MB + Index: 0.13MB + Engine MyISAM
wp_term_taxonomy: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_usermeta: Data: 4.86MB + Index: 3.37MB + Engine MyISAM
wp_users: Data: 0.22MB + Index: 0.20MB + Engine MyISAM
wp_volunteer_emails: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_volunteer_rsvps: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.19MB + Index: 0.14MB + Engine InnoDB
wp_wc_download_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_order_coupon_lookup: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 1.52MB + Index: 0.91MB + Engine InnoDB
wp_wc_order_stats: Data: 0.42MB + Index: 0.36MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.06MB + Index: 0.05MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.06MB + Index: 0.09MB + Engine MyISAM
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_webhooks: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wpfront_ure_login_redirect: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpfront_ure_options: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_yoast_indexable: Data: 2.01MB + Index: 0.83MB + Engine MyISAM
wp_yoast_indexable_hierarchy: Data: 0.09MB + Index: 0.28MB + Engine MyISAM
wp_yoast_migrations: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_yoast_primary_term: Data: 0.03MB + Index: 0.03MB + Engine MyISAM
wp_yoast_seo_links: Data: 0.12MB + Index: 0.03MB + Engine MyISAM
wp_yoast_seo_meta: Data: 0.15MB + Index: 0.13MB + Engine MyISAM

### Post Type Counts ###

attachment: 965
customize_changeset: 7
custom_css: 1
def_reg_fields: 10
displayed_gallery: 2
display_type: 7
efbl_skins: 6
foogallery: 1
itsec-dash-card: 16
itsec-dashboard: 2
log_emails_log: 2148
memberpressproduct: 8
mif_skins: 2
nav_menu_item: 39
nf_sub: 351
ngg_gallery: 2
ngg_pictures: 51
oembed_cache: 29
page: 58
plugin_filter: 1
popup: 3
popup_theme: 6
post: 3
product: 599
product_variation: 250
revision: 2327
shop_coupon: 1421
shop_order: 7598
shop_order_refund: 187
shortcoder: 1
tablepress_table: 2
us_content_template: 1
us_grid_layout: 4
us_header: 1
us_page_block: 5
volunteer_opp: 1
wccc: 1
wc_membership_plan: 2
wc_user_membership: 1061
wll_records: 428
ywctm-button-label: 6

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (67) ###

weLaunch Framework: by weLaunch.io – 1.0.14
Admin Columns Pro: by AdminColumns.com – 6.0.3
Advanced Woo Search PRO: by ILLID – 1.30
Autoclear Autoptimize Cache: by Theme Surgeons – 2.1.1
Autoptimize: by Frank Goossens (futtta) – 3.1.4
BAW Login/Logout menu: by Juliobox
GregLone
jbrodiev – 1.3.5

Better User Search: by Dale Higgs – 1.1.1
Bulk remove posts from category: by MasterNs – 3.3
Classic Editor: by WordPress Contributors – 1.6.2
Classic Widgets: by WordPress Contributors – 0.3
Custom Facebook Feed Pro Smash: by Smash Balloon – 4.3.4
Export User Data: by Q Studio – 2.2.6
FacetWP: by FacetWP
LLC – 4.1.3

Favicon by RealFaviconGenerator: by Philippe Bernard – 1.3.27
GPL Kit: by GPL Kit – 2.0.1
IgniteWoo Updater: by IgniteWoo.com – 3.0.3
iThemes Security Pro: by iThemes – 7.2.4
WPBakery Page Builder: by Michael M - WPBakery.com – 6.10.0
Loco Translate: by Tim Whitlock – 2.6.3
Log cleaner for iThemes Security: by Michael Ott – 1.3.5
Logged In Purchases Only: by Web Complete – 1.0.0
LoginPress - Customizing the WordPress Login Screen.: by WPBrigade – 1.6.3
Mailchimp for WooCommerce: by Mailchimp – 2.7.6
Manage Notification E-mails: by Virgial Berveling – 1.8.4
Nav Menu Roles: by Kathy Darling – 2.1.0
Ninja Forms: by Saturday Drive – 3.6.14
Plugin Organizer: by Jeff Sterup – 10.1.7
ActiveCampaign Postmark (Official): by Andrew Yates & Matt Gibbs – 1.17.2
Volunteer Sign Up Sheets: by Stephen Sherrard – 4.3.0
Volunteer Sign Up Sheet Groups Extension: by Stephen Sherrard – 1.5.0
Really Simple CAPTCHA: by Takayuki Miyoshi – 2.1
reCaptcha for WooCommerce: by I Thirteen Web Solution – 2.17
Redirection: by John Godley – 5.3.6
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 3.1.5
Simple Google reCAPTCHA: by Michal Novák – 4.0
Simple History: by Pär Thernström – 3.3.1
Simple Login Log: by Max Chirkov – 1.1.3
Smart Manager - WooCommerce Inventory Management, Advanced Bulk Edit & more...: by StoreApps – 6.6.0
TablePress: by Tobias Bäthge – 2.0.2
Category Order and Taxonomy Terms Order: by Nsp-Code – 1.7.4
UpdraftPlus - Backup/Restore: by UpdraftPlus.com
DavidAnderson – 2.22.25.26

UpSolution Core: by UpSolution – 8.13.3
User Role Editor: by Vladimir Garagulya – 4.63.2
User Switching: by John Blackbourn & contributors – 1.7.0
Product Customer List for WooCommerce: by Kokomo – 3.1.2
When Last Login: by Yoohoo Plugins – 1.2.1
Widget Clone: by 93digital – 1.1.4
Advanced Order Export For WooCommerce: by AlgolPlus – 3.3.3
WooCom SecurePay Payment Gateway: by Hem Thapa – 1.8
WooCommerce Bulk Stock Management: by WooCommerce – 2.2.31
WooCommerce Cart Stock Reducer: by James Golovich – 3.90
WooCommerce Checkout Manager PRO: by QuadLayers – 1.5.7
WooCommerce Checkout Manager: by QuadLayers – 6.4.1
WooCommerce Conditional Content: by Lucas Stark – 2.1.8
WooCommerce Phone Orders & Manual Orders: by IgniteWoo.com – 3.2.3
WooCommerce Memberships: by SkyVerge – 1.24.0
WooCommerce Order Status Control: by SkyVerge – 1.15.0
WooCommerce PDF Catalog: by weLaunch – 1.16.9
WooCommerce Product Dependencies: by SomewhereWarm – 1.2.7
WooCommerce Smart Coupons: by StoreApps – 6.0.0 (update to version 6.5.0 is available)
WooCommerce Waitlist: by Neil Pie – 2.3.4
WooCommerce: by Automattic – 7.2.2 (update to version 7.3.0 is available)
Yoast SEO: by Team Yoast – 19.13
Mail logging - WP Mail Catcher: by James Ward – 2.0.5
Widget Disable: by required – 2.1.0
YITH WooCommerce Catalog Mode Premium: by YITH – 2.1.2
YITH WooCommerce Customize My Account Page Premium: by YITH – 3.15.0

### Inactive Plugins (2) ###

Transients Manager: by WPBeginner – 2.0.3
WooCommerce Private Store: by Barn2 Plugins – 1.7.0

### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
maintenance.php: maintenance.php

### Must Use Plugins (1) ###

Plugin Organizer MU: by Jeff Sterup – 10.1.7

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: AUD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: simple (simple)
grouped (grouped)
variable (variable)
external (external)
registrations (registrations)
subscription (subscription)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-search (exclude-from-search)
exclude-from-catalog (exclude-from-catalog)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: –
Order datastore: WC_Order_Data_Store_CPT

### WC Pages ###

Shop base: #1578 - /enrolments/shop/
Cart: #1579 - /cart/
Checkout: #1580 - /checkout/
My account: #1581 - /member-details/
Terms and conditions: #2132 - /terms-and-conditions/

### Theme ###

Name: Impreza Child
Version: 1.0
Author URL: http://us-themes.com/
Child Theme: ✔
Parent Theme Name: Impreza
Parent Theme Version: 8.13
Parent Theme Author URL: http://us-themes.com/
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Memberships ###

Restriction mode:: Hide content only
Public content:: –
Excluded from discounts:: –
Membership plans:: 2
Tutor Membership 2022:: Members: 105Access method: Product(s) purchaseAccess length: Fixed dates (364 days)
Community Membership 2022:: Members: 956Access method: Product(s) purchaseAccess length: Fixed dates (364 days)

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
experimental-products-task
experimental-import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
multichannel-marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
settings

Daily Cron: ✔ Next scheduled: 2023-01-29 08:05:39 +08:00
Options: ✔
Notes: 23
Onboarding: completed

### Action Scheduler ###

Complete: 1,765
Oldest: 2022-12-29 16:25:53 +0800
Newest: 2023-01-29 16:00:03 +0800

Failed: 9
Oldest: 2022-10-17 10:31:57 +0800
Newest: 2023-01-05 15:41:24 +0800

Pending: 2
Oldest: 2023-01-29 16:33:23 +0800
Newest: 2023-01-30 15:20:07 +0800

### Smart Coupons related settings ###

Number of coupons to show: 5
Number of characters in auto-generated coupon code: 
Valid order status for auto-generating coupon: processing
completed

Include tax in the amount of the generated gift card: no
Deduct credit/gift before doing tax calculations: no
Gift Card discount is inclusive of tax: no
Automatic deletion: no
Coupon emails: yes
Printing coupons: yes
Sell gift cards at less price?: no
Use gift card applied in first subscription order for subsequent renewals until credit reaches zero: yes
Renewal orders should not generate coupons even when they include a product that issues coupons: no
Allow sending of coupons to others: yes
Allow schedule sending of coupons?: no
Combine emails: no
Auto generated coupon email: yes
Combined auto generated coupons email: no
Acknowledgement email: yes
Enable taxes: no
Prices entered with tax: no
Rounding: no
Display prices in the shop: excl
Display prices during cart and checkout: excl
Display tax totals: itemized
Enable the use of coupon codes: yes
Calculate coupon discounts sequentially: no
Account endpoints > Coupons: wc-smart-coupons

### Status report information ###

Generated at: 2023-01-29 16:00:21 +08:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by iyut**
### Submission Review Guidelines:

- I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
- I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
- I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/). 
- Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:
This PR is to fix issue for a warning that being displayed when user put `0` price for product variation.
To fix that, I changed the condition in sql to be like this : 
```
SELECT count(post_id) FROM {$wpdb->postmeta}
WHERE post_id in (" . implode( ',', array_map( 'absint', $variation_ids ) ) . ")
AND ( meta_key='_subscription_sign_up_fee' OR meta_key='_price' )
AND meta_value >= 0
AND meta_value != ''
```
By doing this, it allows the user to set the price with 0.

Closes #36668  .

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Create a new variable product.
2. Set two new attributes for the product like the screenshot below : 
image

3. Go to "Variations" tab and click "Generate variations".
4. Add the regular price for the first variant with `0` and the other variants with any number but more than 0.
image

image

5. Click "Save Changes" to save the variations.
6. Notice that no Warning being displayed.
7. Now, empty the regular price for the first variant and click "Save Changes".
image

8. Notice that the warning being displayed : 
image

### CODE REVIEW

**Comment by mattsherman** [comment]
I'll review this

File: plugins/woocommerce/includes/admin/wc-admin-functions.php [hunk 1]
```diff
@@ -508,27 +508,29 @@ function wc_render_invalid_variation_notice( $product_object ) {
 
 	// Check if a variation exists without pricing data.
 	// phpcs:disable WordPress.DB.PreparedSQL.NotPrepared
-	$invalid_variation_count = $wpdb->get_var(
+	$valid_variation_count = $wpdb->get_var(
```
Comment (mattsherman) [inline plugins/woocommerce/includes/admin/wc-admin-functions.php:511]: Thanks for fixing this up... it was so confusing that this was incorrectly named `$invalid_variation_count` previously! Most of my time reviewing this was just making sure that I wasn't missing something with this obvious of a misname! 😄

**Review by mattsherman — APPROVED** [review]
Nice work on this @iyut!

In addition to fixing the issue, the code is now much clearer, thanks to your naming of `$invalid_variation_count` to `$valid_variation_count`.

**Comment by iyut** [comment]
Hi @mattsherman , just wanted to say thanks for reviewing this PR 🙏
