### PR TITLE
enhance/create wrapper for all external func using proxy

### LINKED ISSUE #51361: [Remote Logger] Create a wrapper function for all external dependency function calls for safety
> Right, sorry I forgot try-catch will still let fatal errors slip through.
> 
> Riffing on your original idea, I could see it being beneficial to create some guard rails around every non-inbuilt function -- ` wp_parse_url`, `WC`, `wp_get_current_user` etc -- by making private method wrappers/aliases. Something like:
> 
> ```
> private function wp_parse_url() {
>  if ( function_exists( 'wp_parse_url' ) ) {
>    wp_parse_url();
>  }
>  else {
>    return null; // or alternatively throw an exception 🤔 
>  }
> }
> ```

_Originally posted by @adrianduffell in https://github.com/woocommerce/woocommerce/pull/51302#discussion_r1756135944_
           

 A form this could take could be something like https://github.com/symfony/error-handler.

It should
- Be a function that wraps around a function call
- Return the function call results if it is sound (not sure if we need to do any validation?)
- If an error or something unexpected occurs, we simply return a safe value such as null or a placeholder "Unable to retreive"
- We might want to consider collating these errors and also inserting them into the remote error log so that we are aware that such situations are occurring

### PR DESCRIPTION
**Pull request by rjchow**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes https://github.com/woocommerce/woocommerce/issues/51361

This PR create a wrapper for non-built-in functions that are used in `RemoteLogger.php` for safety.

For each function, the wrapper will:

1. If the function is not defined, try to require the file that contains the function once.
2. If the function throws an exception, catch it, log it locally, and return a placeholder value based on the function return type and behavior.

And previously we used `WC()->version` to get the WooCommerce version, but this is not safe because if WC instance fails to initialize, it will cause a fatal error again. So, I changed to get it from constant `WC_VERSION` instead, which is also widely used in WooCommerce core.

Additionally, this PR move the try catch block from `RemoteLogger::log` method to the top of the `RemoteLogger::handle` method to catch any exception that may be thrown by the functions used in the method

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

I'm not exactly sure how to fully test this PR, but I think we can test it by:

**Should log error remotely as previously**

1. Create a fresh site
2. Go to `Tools -> WCA Test Helper -> Remote Logging`
3. Enable remote logging
4. Click on `PHP Simulate Core Exception`, refresh the page and confirm it throws an error
5. See PCYsg-11XN-p2 for instructions on viewing the logs
6. Confirm the error is logged remotely

**Should log error locally if the function is not defined**

1. Create a fresh site (Can reuse the site from the previous test)
2. Go to `Tools -> WCA Test Helper -> Remote Logging`
3. Enable remote logging
4. SSH into server and open the `wp-includes/http.php` file, `~/__wp__/wp-includes/http.php` for JN site.
5. Find the `wp_safe_remote_post` function and comment it out
4. Reset PHP Rate Limit
5. Click on `PHP Simulate Core Exception`, refresh the page and confirm it throws an error
6. Go to `WooCommerce > Status > Logs`
7. Find the `remote-logging` source and open the log file
8. Confirm that `Error [Wrapper function error] Error in wp_safe_remote_post: call_user_func_array(): Argument #1 ($callback) must be a valid callback, function "wp_safe_remote_post" not found or invalid function name ....` is logged
9. Confirm that `Error Failed to call wp_safe_remote_post while sending the log to the remote logging service.` is logged

image

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce/src/Internal/Logging/RemoteLogger.php [hunk 1]
```diff
@@ -284,7 +288,16 @@ private function should_current_version_be_logged() {
...
+		return version_compare( $this->get_wc_version(), $new_version, '>=' );
+	}
+
+	/**
+	 * Get the current WooCommerce version.
+	 *
+	 * @return string The current WooCommerce version.
+	 */
+	private function get_wc_version() {
+		return WC()->version;
```
Comment (chihsuan) [inline plugins/woocommerce/src/Internal/Logging/RemoteLogger.php]: We should use `Constants::get_constant( 'WC_VERSION' );` instead.

I found that `WC()->version` is not safe because if the WC instance fails to initialize, it will cause a fatal error again.

File: plugins/woocommerce/src/Internal/Logging/RemoteLogger.php [hunk 2]
```diff
@@ -324,6 +337,9 @@ protected function is_third_party_error( string $message, array $context ): bool
 			}
 		}
 
+		if ( ! function_exists( 'apply_filters' ) ) {
```
Comment (chihsuan) [inline plugins/woocommerce/src/Internal/Logging/RemoteLogger.php:366]: I wasn't very sure if we should also wrap the `apply_filters` function because we have doc comments for apply_filters. I didn't wrap it because it will not show lint errors for SafeGlobalFunctionProxy::apply_filters, and if there are some automatically generated docs for apply_filters, it will not include them. Just bringing this up for discussion

File: plugins/woocommerce/src/Internal/Logging/RemoteLogger.php [hunk 3]
```diff
@@ -212,46 +221,41 @@ protected function should_handle( $level, $message, $context ) {
...
-			}
+		if ( ! is_array( $log_data ) || empty( $log_data['message'] ) || empty( $log_data['feature'] ) ) {
+			return false;
+		}
 
-			$body = array(
-				'params' => wp_json_encode( $log_data ),
-			);
+		$body = array(
+			'params' => SafeGlobalFunctionProxy::wp_json_encode( $log_data ) ?? 'Error occurred while encoding the log data',
```
Comment (chihsuan) [inline plugins/woocommerce/src/Internal/Logging/RemoteLogger.php]: It occurs to me that the fallback string here and line 244 are not a valid JSON string and will produce an invalid JSON string in the API response. I think we should throw an exception here to log the error locally. Otherwise, we need to set a valid JSON string as the fallback value. 🤔

File: plugins/woocommerce/src/Internal/Logging/RemoteLogger.php [hunk 4]
```diff
@@ -212,46 +221,41 @@ protected function should_handle( $level, $message, $context ) {
...
+				),
+				'blocking' => true,
+			)
+		);
 
-			return true;
-		} catch ( \Throwable $e ) {
-			// Log the error locally if the remote logging fails.
-			error_log( 'Remote logging failed: ' . $e->getMessage() ); // phpcs:ignore WordPress.PHP.DevelopmentFunctions.error_log_error_log
+		if ( SafeGlobalFunctionProxy::is_wp_error( $response ) ) {
```
Comment (chihsuan) [inline plugins/woocommerce/src/Internal/Logging/RemoteLogger.php]: Should we throw an exception here when unable to call the is_wp_error function since we can't determine if the response is an error or not?

**Review by chihsuan — COMMENTED** [review]
Nice work, thank you so much! @rjchow 

I tried to change the methods to non-existent ones, and it worked as expected. 👍 
I think one downside of this approach is that editor completion / type checking won't work when using the proxy but I think it's a good trade-off. We should still able to catch the errors during code review or unit tests.

I rebase the PR and left some suggestions for the code. Please take a look. I think we should get more eyes from the team to review this PR. Thanks! 🙌

File: plugins/woocommerce/src/Internal/Logging/RemoteLogger.php (hunk 3 above)
Comment (rjchow) [reply plugins/woocommerce/src/Internal/Logging/RemoteLogger.php]: I thiiiiink its ok? Tried this in the shell and it seems equivalent:
```
> json_decode(wp_json_encode(array("params" => 'Error occurred while encoding the log data')))
= {#12158
    +"params": "Error occurred while encoding the log data",
  }

> json_decode(wp_json_encode(array("params" => wp_json_encode("a long string"))))
= {#12146
    +"params": ""a long string"",
  }
```

File: plugins/woocommerce/src/Internal/Logging/RemoteLogger.php (hunk 4 above)
Comment (rjchow) [reply plugins/woocommerce/src/Internal/Logging/RemoteLogger.php]: Good call! I think testing for null here should suffice - that's what it'll return if the call fails. What do you think?

Comment (chihsuan) [reply plugins/woocommerce/src/Internal/Logging/RemoteLogger.php]: Sounds good!

File: plugins/woocommerce/src/Internal/Logging/RemoteLogger.php (hunk 3 above)
Comment (chihsuan) [reply plugins/woocommerce/src/Internal/Logging/RemoteLogger.php]: Ah, you're right. That's actually valid.

Comment (chihsuan) [reply plugins/woocommerce/src/Internal/Logging/RemoteLogger.php]: Actually, I think the server will not log this content as the params format is not correct. Since the API will return false, I think we don't need to call the API at all. Does that make sense? 🤔

File: plugins/woocommerce/src/Internal/Logging/RemoteLogger.php (hunk 1 above)
Comment (rjchow) [reply plugins/woocommerce/src/Internal/Logging/RemoteLogger.php]: I was a bit conflicted about this one because it'll be reliant on Jetpack::Constants being available, which I'm not sure is more reliable than having WC() available. Furthermore it's a dependency for testing purposes, so I'm wondering if we should have a series of fallbacks for this instead ?

Maybe something like

```
function get_wc_version() {
    if (function_exists('WC') && method_exists(WC(), 'version')) {
        return WC()->version();
    }

    if (class_exists('\Automattic\Jetpack\Constants') && method_exists('\Automattic\Jetpack\Constants', 'get_constant')) {
        $wc_version = \Automattic\Jetpack\Constants::get_constant('WC_VERSION');
        if ($wc_version) {
            return $wc_version;
        }
    }

    if (defined('WC_VERSION')) {
        return WC_VERSION;
    }

    // Return null since none of the above worked
    return null;
}
```

File: plugins/woocommerce/src/Internal/Logging/RemoteLogger.php (hunk 2 above)
Comment (rjchow) [reply plugins/woocommerce/src/Internal/Logging/RemoteLogger.php:366]: I think its valid and we can leave this one unwrapped, good thinking!

File: plugins/woocommerce/src/Internal/Logging/RemoteLogger.php (hunk 1 above)
Comment (chihsuan) [reply plugins/woocommerce/src/Internal/Logging/RemoteLogger.php]: Good point! The [automattic/jetpack-constants](https://github.com/Automattic/jetpack-constants/tree/trunk) package is in our composer.json and has no dependencies, so I think it's safe to use. But fallbacks are a good idea! 👍 

I prefer using Jetpack::Constants first if available, then falling back to WC() if not. This can help prevent the fatal error loop when WC() fails to initialize. What do you think?

Comment (rjchow) [reply plugins/woocommerce/src/Internal/Logging/RemoteLogger.php]: I'll defer to your suggestion because I don't know better 😆

**Review by moon0326 — APPROVED** [review]
LGTM and tested well 👍 🚀
