### PR TITLE
Skip tax calculation for shipping when its status is set as none 

### LINKED ISSUE #44356: On cart/checkout blocks if shipping method with tax status none used, the order gets a different total/tax total than shown in cart/checkout
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

I have found that when taxes are enabled in a store and when there is a shipping method which is set to tax status of none the totals shown during cart/checkout are inconsistent with the totals after placing the order (shown on order confirmation and the actual data on the order).

### Expected behavior

Totals calculated and displayed in cart/checkout blocks persist to the order once placed.

### Actual behavior

Totals on cart/checkout blocks do not match the final order totals after placing the order.

### Steps to reproduce

1. Enable tax rates and calculations in general settings
2. In tax settings tab set: `Yes, I will enter prices inclusive of tax`, `display prices in the shop including tax`, `display prices during cart and checkout including tax`
3. In tax rates, set standard tax rate to one row of 20% on all countries
4. In shipping settings tab set up this shipping method: `Name: Flat rate with fee`, `Tax status: None`, `Cost: $10.00`
5. Ensure cart/checkout blocks are enabled
6. Add 1 x simple product with price $10.00 to cart
7. Choose the Flat rate with fee shipping method ($10.00)
8. Total shows $20.00 (including $1.67 tax)
9. Proceed to checkout, total still same
10. Place order
11. Order confirmation and order details shows the totals have now changed from what they were at checkout to shipping: $12.00, total $22.00 (including $3.67 tax)

**Cart/checkout:**

image

**Actual order:**

image

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://daycarinsurance.s3-tastewp.com
Site address (URL): https://daycarinsurance.s3-tastewp.com
WC Version: 8.5.2
REST API Version: ✔ 8.5.2
WC Blocks Version: ✔ 11.8.0-dev
Action Scheduler Version: ✔ 3.7.1
Log Directory Writable: ✔
WP Version: 6.4.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: TasteWP-S3 Official/3.0.0
PHP Version: 8.0.30
PHP Post Max Size: 128 MB
PHP Time Limit: 100
PHP Max Input Vars: 5000
cURL Version: 7.68.0
OpenSSL/1.1.1f

SUHOSIN Installed: –
MySQL Version: 8.0.32-0ubuntu0.20.04.2
Max Upload Size: 60 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.5.2
WC Database Prefix: wp_
Total Database Size: 2.87MB
Database Data Size: 1.18MB
Database Index Size: 1.69MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_postmeta: Data: 0.11MB + Index: 0.06MB + Engine InnoDB
wp_posts: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wpfm_backup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

attachment: 24
page: 7
post: 2
product: 18
product_variation: 7
revision: 1
shop_order_placehold: 6

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (2) ###

Classic Widgets: by WordPress Contributors – 0.3
WooCommerce: by Automattic – 8.5.2

### Dropin Plugins (1) ###

maintenance.php: maintenance.php

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to Woo.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### WC Pages ###

Shop base: #7 - /shop/
Cart: #8 - /cart/
Checkout: #9 - /checkout/
My account: #10 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: GeneratePress
Version: 3.3.1
Author URL: https://tomusborne.com
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
product-virtual-downloadable
product-external-affiliate
product-grouped
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: customize-store
minified-js
new-product-management-experience
product-linked
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2024-02-06 11:12:40 +00:00
Options: ✔
Notes: 64
Onboarding: skipped

### Action Scheduler ###

Complete: 42
Oldest: 2024-02-05 11:13:42 +0000
Newest: 2024-02-05 12:28:57 +0000

Failed: 1
Oldest: 2024-02-05 11:13:42 +0000
Newest: 2024-02-05 11:13:42 +0000

Pending: 1
Oldest: 2024-02-06 11:13:42 +0000
Newest: 2024-02-06 11:13:42 +0000

### Status report information ###

Generated at: 2024-02-05 12:29:17 +00:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by senadir**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Order totals calculation didn't respect a shipping method tax status, this PR enables it, as well as adding in all the places it needs to be.

It seems this PR changed also changed the output of `wc/v3/orders` `shipping_lines` tax status, I'm not sure if that should be shown there or not, or if this PR needs extra measures to account for that. I can look into removing it if needed.

Closes https://github.com/woocommerce/woocommerce/issues/44356

### How to test the changes in this Pull Request:

1. Enable taxes, make sure they account for shipping, set them to a predictable amount (20% for example).
2. Add 2 flat rates, both having the same price, one of them should have a tax status of none, the other should be taxable.
3. Add an item to cart and go to Checkout, select the taxable shipping rate, ensure the totals are correct `(item + shipping) * 120%`.
4. Place the order, ensure the total value is still the same in the order confirmation screen.
5. Add the same item back to cart, go to Checkout, select the none-taxable item, make sure the totals are correct `(item * 120%) + shipping`.
6. Place the order,  ensure the total value is still the same in the order confirmation screen.
7. Go to the admin order screen, and go to the first order, make sure the "Recalculate" button is visible, if it's not, change the order status to `on hold` and save.
8. Take note of the totals, hit "Recalculate", the totals should stay the same.
9. Go to the newer order, do the same, ensure the values are stable.

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [x] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message
Skip capturing shipping taxes if the shipping method tax status is set to none.

#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce/includes/class-wc-shipping-rate.php [hunk 1]
```diff
@@ -232,6 +246,15 @@ public function get_shipping_tax() {
 		return apply_filters( 'woocommerce_get_shipping_tax', count( $this->taxes ) > 0 && ! WC()->customer->get_is_vat_exempt() ? (float) array_sum( $this->taxes ) : 0.0, $this );
 	}
 
+	/**
+	 * Get tax status.
+	 *
+	 * @return string
+	 */
+	public function get_tax_status() {
+		return apply_filters( 'woocommerce_shipping_rate_tax_status', $this->data['tax_status'], $this );
```
Comment (opr) [inline plugins/woocommerce/includes/class-wc-shipping-rate.php:264]: As this is a new filter, we should add a docblock for it

**Review by opr — APPROVED** [review]
This is working for me, just a couple of lint issues to solve.

File: plugins/woocommerce/includes/class-wc-shipping-rate.php (hunk 1 above)
Comment (jorgeatorres) [reply plugins/woocommerce/includes/class-wc-shipping-rate.php:264]: It doesn't seem like we're going to support other tax statuses "soon" (other than `none` or `taxable`). As such, I wonder if we should sanitize the value here (after the filter is applied) to prevent incorrect values from bubbling up.

File: plugins/woocommerce/includes/class-wc-order-item-shipping.php [hunk 2]
```diff
@@ -122,6 +123,19 @@ protected function set_total_tax( $value ) {
...
+	 *
+	 * @param string $value Tax status.
+	 */
+	public function set_tax_status( $value ) {
+		if ( in_array( $value, array( 'taxable', 'none' ), true ) ) {
+			$this->set_prop( 'tax_status', $value );
+		} else {
+			$this->set_prop( 'tax_status', 'taxable' );
+		}
+	}
```
Comment (jorgeatorres) [inline plugins/woocommerce/includes/class-wc-order-item-shipping.php]: I find it a bit weird that calling `set_tax_status()` with an incorrect value will set the property to "taxable" rather than throw an error or simply do nothing.
If this is done so that initialization in the datastore is easier, maybe we should sanitize the value there before calling `set_tax_status()` on the object. Thoughts?

**Review by jorgeatorres — DISMISSED** [review]
I left some comments. Nothing super serious, but that would be worth discussing before this is merged. Thank you @senadir for your work on this!

File: plugins/woocommerce/includes/class-wc-order-item-shipping.php (hunk 2 above)
Comment (senadir) [reply plugins/woocommerce/includes/class-wc-order-item-shipping.php]: To be frank I followed what other line items were doing here in fear of breaking something. I think we can remove the else part and default to taxable.

**Comment by senadir** [comment]
Putting this back in draft until I sync it correctly with trunk.
