### PR TITLE
fix: wc-connect-tax option truthiness

### LINKED ISSUE #1288: Tax Task List marked as complete
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

I just started a new Woo Express store and the Tax task is marked as complete : 

Screenshot 2023-08-30 at 14 59 17

The site url is https://woo-softly-valiant-gardener.wpcomstaging.com/ in case that's helpful.

### Expected behavior

Tax task list shouldn't be completed on sign up.

### Actual behavior

NA

### Steps to reproduce

NA

### WordPress Environment

NA

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by rjchow**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

This is a symptomatic treatment of the bug which causes the Tax task to be shown as complete even on a freshly created WooExpress site. This symptom manifests because for some combinations of onboarding profile, it seems that the `wc_connect_taxes_enabled` option is set to the string 'no'. The code prior to this PR treats that as a true value, and thus the Tax task is shown as completed.

This PR defaults the completion to incomplete unless it is a boolean true or string 'yes'. 

Closes https://github.com/Automattic/wc-calypso-bridge/issues/1288.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

(For the below testing, you can set the option values using either WooCommerce Beta Tester plugin or using wp-cli. If you are using wp-env, you can access wp-cli by running `wp-env run cli bash`. To set the value, run `wp option add wc_connect_taxes_enabled "no"`)

1. Set up the WooCommerce installation as usual
2. Observe that the tax task should not show as completed
3. Set the `wc_connect_taxes_enabled` option to various values (true, false, 'yes', 'no') and observe that the completion status on the home screen should reflect correctly
4. Unset the option or set it to 'no', or false
5. Complete the tax task either by setting up WooCommerce Tax or adding tax rules or declaring no sales tax needed
6. Observe that the tax task completes successfully

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce/src/Admin/Features/OnboardingTasks/Tasks/Tax.php [hunk 1]
```diff
@@ -115,7 +115,10 @@ public function get_action_label() {
 	 */
 	public function is_complete() {
 		if ( $this->is_complete_result === null ) {
-			$this->is_complete_result = get_option( 'wc_connect_taxes_enabled' ) ||
+			$wc_connect_taxes_enabled = get_option('wc_connect_taxes_enabled');
+			$is_wc_connect_taxes_enabled = ($wc_connect_taxes_enabled === 'yes') || ($wc_connect_taxes_enabled === true); // seems that in some places boolean is used, and other places 'yes' | 'no' is used
```
Comment (ilyasfoo) [inline plugins/woocommerce/src/Admin/Features/OnboardingTasks/Tasks/Tax.php]: Lint
```suggestion
			$wc_connect_taxes_enabled = get_option( 'wc_connect_taxes_enabled' );
			$is_wc_connect_taxes_enabled = ( $wc_connect_taxes_enabled === 'yes' ) || ( $wc_connect_taxes_enabled === true ); // seems that in some places boolean is used, and other places 'yes' | 'no' is used
```

**Review by ilyasfoo — APPROVED** [review]
Thanks so much for the fix, @rjchow! Nit comment but tested well 🚢

**Review by chihsuan — APPROVED** [review]
Thanks for the fix! LGTM and tested well! 👍

**Comment by rodelgc** [comment]
Thank you so much @rjchow for providing full context and clear testing instructions!

A combination of external and internal testing will be done on this PR. External testing will be done against JN and the existing Woo Express test site. Internal testing will be done on a fresh new Woo Express one, since the bug was encountered on a newly created Woo Express site, together with the various possible values of the wc_connect_taxes_enabled option.
