### PR TITLE
Fix the inconsistent formatting of the numeric columns in the Leaderboards on the Analytics > Dashboard page

### LINKED ISSUE #36748: The Leaderboards in the Analytics > Dashboard report don't seem to be taking the correct currency formatting
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

**Notes**
1. This is a duplicate of the issue that [I already reported on the 17th September 2020 in the WooCommerce Admin issue tracker](https://github.com/woocommerce/woocommerce-admin/issues/5154). That issue was apparently ignored and it became stale, twice, and twice it was closed automatically. However, the bug is still there.
2. I left the checkbox "I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active" unchecked, because the currency filter comes from a plugin that I developed. Still, the issue is in the WooCommerce Admin, it seems to be a cosmetic issue of price formatting.

**Description**
I'm using a filter, written following your guidelines, to alter the currency formatting arguments depending on the currency selected on the reports. This ensures that amounts are formatted correctly on most reports, as well as most of the dashboard. However, the Leaderboards section doesn't seem to be taking the formatting arguments into account and always used the USD parameters (incidentally, USD is not even the shop's base currency).

**Screenshots**
1. Dashboard, amounts in the leaderboards are formatted incorrectly: https://prnt.sc/uitqwv
4. Orders report, correct: https://prnt.sc/uitp41
5. Products report, correct: https://prnt.sc/uitpib

### Expected behavior

The Leaderboards components should format the values using the selected currency, like all other components do.

### Actual behavior

The Leaderboards components format the values using the shop's base currency, regardless of the selected currency.

### Steps to reproduce

1. Implement a currency filter like the one described in your documentation (see [Extending WC-Admin Reports]
2. https://woocommerce.wordpress.com/2020/02/20/extending-wc-admin-reports/)).
3. Go to the Dashboard report.
4. Select a currency.
5. The currency in the dashboard reflects the selected one, while the Leaderboard shows amounts formatted as the shop's base currency.

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): http://localhost/wordpress_wc80
Site address (URL): http://localhost/wordpress_wc80
WC Version: 7.4.0
REST API Version: ✔ 7.4.0
WC Blocks Version: ✔ 9.4.2
Action Scheduler Version: ✔ 3.5.4
Log Directory Writable: ✔
WP Version: 6.0.3
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.35 (Win64) OpenSSL/1.1.1q PHP/8.0.22
PHP Version: 8.0.22
PHP Post Max Size: 2 GB
PHP Time Limit: 36000
PHP Max Input Vars: 1000
cURL Version: 7.76.1
OpenSSL/1.1.1q

SUHOSIN Installed: –
MySQL Version: 5.7.24
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.4.0
WC Database Prefix: wp_
Total Database Size: 52.46MB
Database Data Size: 28.54MB
Database Index Size: 23.92MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.08MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 1.52MB + Index: 0.78MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.08MB + Index: 0.13MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_aelia_dismissed_messages: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.27MB + Index: 0.36MB + Engine InnoDB
wp_groups_capability: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_groups_group: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_groups_group_capability: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_groups_user_capability: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_groups_user_group: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_layerslider_revisions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 6.44MB + Index: 1.17MB + Engine InnoDB
wp_postmeta: Data: 4.52MB + Index: 6.55MB + Engine InnoDB
wp_posts: Data: 1.52MB + Index: 0.22MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.09MB + Index: 0.17MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_orders: Data: 0.11MB + Index: 0.11MB + Engine InnoDB
wp_wc_orders_meta: Data: 1.52MB + Index: 3.03MB + Engine InnoDB
wp_wc_order_addresses: Data: 0.09MB + Index: 0.09MB + Engine InnoDB
wp_wc_order_bundle_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_order_composite_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_operational_data: Data: 0.08MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.08MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.06MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.05MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_shipping_table_rates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wss_sell_messages: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wss_service_notifications: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 26
def_reg_fields: 10
enr_subsc_plan: 1
nav_menu_item: 14
page: 36
post: 5
postman_sent_mail: 12
product: 84
product_variation: 166
revision: 61
shop_coupon: 11
shop_order: 291
shop_order_placehold: 3
shop_order_refund: 3
shop_subscription: 2
shopping-cart: 2
super_form: 1
user_request: 1
wp_global_styles: 1
wp_navigation: 1

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (4) ###

Loco Translate: by Tim Whitlock – 2.6.3
Aelia Foundation Classes for WooCommerce: by Aelia – 2.4.0.230202
Aelia Currency Switcher for WooCommerce: by Aelia – 4.15.0.220103
WooCommerce: by Automattic – 7.4.0-beta.2

### Inactive Plugins (15) ###
Post SMTP: by Post SMTP – 2.3.2
WooCommerce Beta Tester: by WooCommerce – 2.1.0

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: EUR (€)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: 
external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: ✔

### WC Pages ###

Shop base: #4 - /
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My account: #7 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront Child
Version: 1.0.0.180829
Author URL: http://woocommerce.com
Child Theme: ✔
Parent Theme Name: Storefront
Parent Theme Version: 4.1.3 – 4.2.0 is available
Parent Theme Author URL: https://woocommerce.com/
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
multichannel-marketing
mobile-app-banner
navigation
new-product-management-experience
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
product-variation-management
settings

Daily Cron: ✔ Next scheduled: 2023-02-04 11:51:20 +01:00
Options: ✔
Notes: 112
Onboarding: completed

### Action Scheduler ###

Complete: 127
Oldest: 2023-01-27 17:36:58 +0000
Newest: 2023-02-03 12:41:41 +0000

Failed: 27
Oldest: 2021-12-15 13:13:11 +0000
Newest: 2023-02-03 12:07:15 +0000

Pending: 11
Oldest: 2023-02-03 13:00:49 +0000
Newest: 2023-02-22 14:07:49 +0000

### Status report information ###

Generated at: 2023-02-03 13:58:55 +01:00
`

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by eason9487**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes #36748

This PR fixes the issue by:

- Add the `format` property to the items of the `rows` array in Analytics' Leaderboards API response to indicate how it's formatted.
- Make the `Leaderboard` component within Analytics aware of the currency context and format the numeric columns accordingly.

Extra changes to the *client/analytics/components/leaderboard/test/index.js* file:

- Apply better practice
- Avoid a warning when running JS tests
   
   Ref: https://github.com/woocommerce/woocommerce/blob/9.0.2/packages/js/components/src/pagination/pagination.tsx#L44

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Checkout this PR, and run `pnpm install` and `pnpm build`
2. Open another webpage to view the current currency options on the **WooCommerce > Settings > General** page
3. Go to the **Analytics > Overview** page
4. If there are not large enough values to test, modifying these two lines locally can adjust the API response
   - https://github.com/woocommerce/woocommerce/blob/45022b3705b3b5751870e09cd8603ea1e58942ea/plugins/woocommerce/src/Admin/API/Leaderboards.php#L203
   - https://github.com/woocommerce/woocommerce/blob/45022b3705b3b5751870e09cd8603ea1e58942ea/plugins/woocommerce/src/Admin/API/Leaderboards.php#L208
5. Check if the currency options are applied to the currency and formatting of all amount values in the Leaderboards
6. Check if the thousand separator of the currency options is applied to all values of the Items Sold column in the Leaderboards
7. Add the following PHP code snippet, where the currency options should be different from the ones in step 2:
   ```php
   add_action( 'admin_enqueue_scripts', function () {
   	wp_add_inline_script( 'wp-hooks', <<<EOD
   	wp.hooks.addFilter( 'woocommerce_admin_report_currency', 'dev-blog-example', function() {
   		return {
   			code: "NZD",
   			decimalSeparator: ".",
   			precision: 2,
   			priceFormat: "%1\$s %2\$s",
   			symbol: "\$NZ",
   			symbolPosition: "left",
   			thousandSeparator: ",",
   		};
   	} );
   	EOD );
   } );
   ```
8. Repeat the test similar to steps 5 and 6, but check that the formatting of the values reflects the currency options returned by the filter in step 7.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce-admin/client/analytics/components/leaderboard/index.js [hunk 1]
```diff
@@ -38,18 +79,7 @@ export class Leaderboard extends Component {
...
-						<div
-							dangerouslySetInnerHTML={ sanitizeHTML(
-								column.display
-							) }
-						/>
-					),
-					value: column.value,
-				};
-			} );
+			return row.map( this.getFormattedColumn.bind( this ) );
```
Comment (tomalec) [inline plugins/woocommerce-admin/client/analytics/components/leaderboard/index.js]: This creates a new function for every `row`, I think we can make it so we'll create a new function for each `getFormattedRows` call:
```js
		const getFormattedColumn = this.getFormattedColumn.bind( this );

		return this.props.rows.map( ( row ) => {
			return row.map( getFormattedColumn );
```

**Review by tomalec — APPROVED** [review]
I tested the changes locally and reviewed the code, despite a small comment regarding function binding LGTM

File: plugins/woocommerce-admin/client/analytics/components/leaderboard/index.js (hunk 1 above)
Comment (eason9487) [reply plugins/woocommerce-admin/client/analytics/components/leaderboard/index.js]: Thanks for the suggestion. Adjusted in https://github.com/woocommerce/woocommerce/pull/49097/commits/0cf5d717b9442251f19a24e8f630cd0ff69e2b3c.
