### PR TITLE
[Accessibility] Fix product page tabs keyboard accessibility

### LINKED ISSUE #58130: Accessibility issue: Improper ARIA role implementation in product tabs may causes screen reader navigation problems
## **Describe the bug**

The product description and review tabs on the single product template have ARIA role implementations that are flagged for accessibility standards:

1. Elements with an ARIA \[role\] that require children to contain a specific \[role\] are missing some or all of those required children.
   The ul.tabs.wc-tabs element has role="tablist" but the child elements were incorrectly structured, causing screen readers to misinterpret the tab interface.
   Specifically, the ARIA roles weren't properly assigned to their required parent-child relationship, failing WCAG accessibility requirements. This affects tab navigation for users relying on assistive technologies.
   Error identified on elements:

* ul.tabs.wc-tabs
* li#tab-title-description.description_tab.active
* li#tab-title-additional_information.additional_information_tab

2. \[role\]s are not contained by their required parent element
   Some anchor elements within the tabs structure were not properly associated with their required parent roles, further disrupting the accessible tab interface implementation.
   These combined issues create significant barriers for users navigating with screen readers or other assistive technologies.

## **To Reproduce**

1. Install WooCommerce
2. Create a product
3. Visit the product page and open the browser console
4. Navigate to Lighthouse and run a scan
5. View the results for Accessibility

## **Expected behavior**

The product tabs on the single product page should implement proper ARIA roles and relationships to ensure accessibility compliance. Specifically:

1. The tab list (ul.tabs.wc-tabs with role="tablist") should contain direct children with role="tab" correctly implemented on each tab item.
2. All ARIA roles should maintain the proper parent-child relationships as required by WCAG accessibility standards.
3. Tab navigation should be fully accessible to screen readers and other assistive technologies, allowing users to understand the tab structure and navigate between tabs seamlessly.
4. All interactive elements should be properly associated with their respective tab panels, maintaining the programmatic relationships needed for assistive technologies.

## **Screenshots**

Browser console: [https://share.cleanshot.com/pp4Ss5QY](https://share.cleanshot.com/pp4Ss5QY)
Area flagged on Single Product Template: [https://share.cleanshot.com/tkxNDr0B](https://share.cleanshot.com/tkxNDr0B)

## Environment

Please fill out any of the below that applies

**Operating System/Device**

- [ ] Windows
- [ ] MacOS
- [ ] Linux
- [ ] iPhone
- [ ] Samsung
- [ ] Other (add in additional context field)

**Version:** Add the Desktop OS and/or Device version(s) here

**Browser**

- [ ] Desktop Edge
- [X] Desktop Chrome/Chromium
- [ ] Desktop Safari
- [ ] Mobile Edge
- [ ] Mobile Chrome/Chromium
- [ ] Mobile Safari
- [ ] Other (add in additional context field)

**Version:** Add the browser version(s) here.

## **Additional context**

This issue will be published publicly, add system status report and internal links to Slack thread after issue created.

### PR DESCRIPTION
**Pull request by kdo**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes #58130 .

I believe the aria role issue mentioned in the original issue is actually a non-issue, we are using the presentation role to hide the li. ( https://www.w3.org/WAI/ARIA/apg/practices/hiding-semantics/ )
I also don't see it being brought up in my local Lighthouse scan.

This PR fixes keyboard navigation for vertical tabs by enabling up/down arrow keys navigation. 

### How to test the changes in this Pull Request:

1. Start with the Twenty Twenty-Four theme or another theme using horizontal tabs
2. Go to a Product Page
3. Scroll to the tabs
4. When focus is on a tab item, verify that left/right arrow keys work to navigate through the tabs, up/down arrows should have their default behavior (scroll up or down the page)
5. Enable the Storefront theme or another theme using vertical tabs
6. Go back to a Product Page
7. Scroll to the tabs
8. When focus is on a tab item, verify that up/down arrow keys work to navigate through the tabs, left/right arrows should have their default behavior (do nothing since we should not have an horizontal scroll)

Horizontal tabs:

Screen Shot 2025-06-03 at 16 41 41 PM

Vertical tabs:

Screen Shot 2025-06-03 at 16 41 54 PM

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

**Comment by kdo** [comment]
Hi @dkotter this is ready for review!

**Review by dkotter — APPROVED** [review]
@ankitguptaindia @qasumitbagthariya This is ready for QA

**Comment by qasumitbagthariya** [comment]
### QA/Test Report ✅ 
-------------

I have checked this PR in the `kdo:fix/58130` branch and changes working as expected.
- Tested with the Twenty Twenty-Four theme (horizontal tabs) ✅ 
- Switched to the Storefront theme (vertical tabs) ✅ 

https://github.com/user-attachments/assets/e27776c4-6d76-478a-acda-cd98cf1b853a


**Testing Environment** 

<Details>

- WordPress: 6.8.1
- Theme: Storefront 4.6.0
- WooCommerce - WooCommerce - Dev version with this fix specific branch.
- PHP: 8.0.30
- Web Server: Nginx 1.20.2
- Browser: Chrome 
- OS: macOS  15.2 
- Git Branch: kdo:fix/58130

</Details>

@kdo please remove [WIP] from the title and take this PR out of draft.

**Comment by vikrampm1** [comment]
@opr @dinhtungdu same here. I am unable to tag Rubik or Kirigami team for review like previously. Can you help request a review from the appropriate team when you get a chance?

**Review by Aljullu — COMMENTED** [review]
Thanks for this improvement, @kdo! I tested it with horizontal and vertical tabs and it's working as described. :raised_hands: 

While the issue is also present in `trunk`, I wonder if we should take the opportunity to invert the left and right axis in RTL languages?

In the video below I'm pressing the <kbd>→</kbd> arrow but the focus is moving to the left.

https://github.com/user-attachments/assets/6538528c-d2d6-4688-ac78-5705b53317e3

Whether the store is using an RTL locale can be known by checking the `.rtl` class in the `body`.

<details>
<summary>Testing environment</summary>

* WordPress 6.8.1 local dev environment
* Plugins: WooCommerce Beta Tester
* Theme: Twenty Twenty-Five
* Store creation: April 24th 2025
* Store size: small
</details>

**Comment by Aljullu** [comment]
Btw, @kdo you will need to create a changelog entry for the checks to pass. You can do so by running:

```
pnpm --filter='@woocommerce/plugin-woocommerce' changelog add
```

**Comment by kdo** [comment]
Thanks for the checks and great catch @Aljullu !
I've updated this PR to include a fix for RTL languages. In addition to the test in the original description:

1. Update site settings to an RTL language
2. Visit the product page tabs
3. Make sure direction of focus matches arrows pressed

Thanks!

CC @vikrampm1

File: plugins/woocommerce/client/legacy/js/frontend/single-product.js [hunk 1]
```diff
@@ -45,32 +45,68 @@ jQuery( function( $ ) {
 			$tabs_wrapper.find( '#' + $tab.attr( 'href' ).split( '#' )[1] ).show();
 		} )
 		.on( 'keydown', '.wc-tabs li a, ul.tabs li a', function( e ) {
+			var isRTL     = document.documentElement.dir === 'rtl';
 			var direction = e.key;
-			var next      = 'ArrowRight';
-			var prev      = 'ArrowLeft';
+			var right     = isRTL ? 'ArrowLeft' : 'ArrowRight';
+			var left      = isRTL ? 'ArrowRight' : 'ArrowLeft';
```
Comment (Aljullu) [inline plugins/woocommerce/client/legacy/js/frontend/single-product.js]: Nitpick: but I think it would be better to leave `next` and `prev` as the variable names now? I feel `right` being `ArrowLeft` might be confusing.

Comment (kdo) [reply plugins/woocommerce/client/legacy/js/frontend/single-product.js]: @Aljullu super valid nitpicking, I agree! Reverted to the next/prev variable names, thanks!

**Review by Aljullu — APPROVED** [review]
Good job, @kdo! This is looking great on my end. :raised_hands:
