### PR TITLE
Cart Link: preventDefault() on the <a> tag in the editor

### LINKED ISSUE #60777: Unable to edit text in Mini Cart Link block
## **Describe the bug**

Attempting to edit the default "Cart" text in the Cart Link block returns an error:

```
TypeError: Cannot read properties of null (reading 'getSelection')
    at https://c0.wp.com/c/6.8.2/wp-includes/js/dist/block-editor.min.js:21:466538
    at https://c0.wp.com/c/6.8.2/wp-includes/js/dist/compose.min.js:9:16457
    at F (https://c0.wp.com/c/6.8.2/wp-includes/js/dist/compose.min.js:9:19906)
    at https://c0.wp.com/c/6.8.2/wp-includes/js/dist/compose.min.js:9:20206
    at Array.forEach (<anonymous>)
    at https://c0.wp.com/c/6.8.2/wp-includes/js/dist/compose.min.js:9:20150
    at Ur (https://c0.wp.com/c/6.8.2/wp-includes/js/dist/vendor/react-dom.min.js:10:73201)
    at Jr (https://c0.wp.com/c/6.8.2/wp-includes/js/dist/vendor/react-dom.min.js:10:80402)
    at Zr (https://c0.wp.com/c/6.8.2/wp-includes/js/dist/vendor/react-dom.min.js:10:80258)
    at Gr (https://c0.wp.com/c/6.8.2/wp-includes/js/dist/vendor/react-dom.min.js:10:79798)
```

## **To Reproduce**

1. Open an existing or new template.
2. Add the Cart Link block.
3. Delete the default "Cart" text and start to type in new text.

## **Expected behavior**

Can change default "Cart" text to something else.

## **Screenshots**

[https://cloudup.com/cRbhPkxQioz](https://cloudup.com/cRbhPkxQioz)

## Environment

Please fill out any of the below that applies

**Operating System/Device**

- [ ] Windows
- [X] MacOS
- [ ] Linux
- [ ] iPhone
- [ ] Samsung
- [ ] Other (add in additional context field)

**Version:** OS X 15.6.1

**Browser**

- [ ] Desktop Edge
- [X] Desktop Chrome/Chromium
- [ ] Desktop Safari
- [ ] Mobile Edge
- [ ] Mobile Chrome/Chromium
- [ ] Mobile Safari
- [ ] Other (add in additional context field)

**Version:** 139.0.7258.155

### PR DESCRIPTION
**Pull request by tjcafferkey**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

The dummy `<a>` around the cart link text in the editor is not hijacking the onClick with `event.preventDefault()` to stop it from navigating away from the editor page when you click the text to try and edit it.

This PR introduces a fix for that issue.

Closes [WOOPLUG-5488](https://linear.app/a8c/issue/WOOPLUG-5488/unable-to-edit-text-in-mini-cart-link-block)
Closes https://github.com/woocommerce/woocommerce/issues/60777

(For Bug Fixes) Bug introduced in PR # .

### Screenshots or screen recordings:

| Before | After |
| ------ | ----- |
|        |       |

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Add the Cart Link block to a page or template
2. After inserting it your cursor should be focused on the text for edit, click elsewhere to focus on another element in the page.
3. Now click the cart link text again to edit it, ensure you're able to successfully.
4. Check the frontend to ensure it works as expected and theres no regressions.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

**Comment by tjcafferkey** [comment]
Waiting on https://github.com/woocommerce/woocommerce/pull/60805 to fix failing unit test

File: plugins/woocommerce/client/blocks/assets/js/blocks/cart-link/edit.tsx [hunk 1]
```diff
@@ -67,7 +68,13 @@ const Edit = ( { attributes, setAttributes }: Props ): JSX.Element => {
 					</ToggleGroupControl>
 				</PanelBody>
 			</InspectorControls>
-			<a className="wc-block-cart-link" href={ '#cart-pseudo-link' }>
+			<a
+				className="wc-block-cart-link"
+				href={ '#cart-pseudo-link' }
+				onClick={ ( event ) => event.preventDefault() }
+				aria-disabled={ true }
```
Comment (opr) [inline plugins/woocommerce/client/blocks/assets/js/blocks/cart-link/edit.tsx]: This would disable the components below wouldn't it?

File: plugins/woocommerce/client/blocks/assets/js/blocks/cart-link/edit.tsx [hunk 2]
```diff
@@ -67,7 +68,12 @@ const Edit = ( { attributes, setAttributes }: Props ): JSX.Element => {
 					</ToggleGroupControl>
 				</PanelBody>
 			</InspectorControls>
-			<a className="wc-block-cart-link" href={ '#cart-pseudo-link' }>
+			<a
+				className="wc-block-cart-link"
+				href={ '#cart-pseudo-link' }
+				onClick={ ( event ) => event.preventDefault() }
+				tabIndex={ -1 }
```
Comment (opr) [inline plugins/woocommerce/client/blocks/assets/js/blocks/cart-link/edit.tsx:75]: From https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Global_attributes/tabindex

> A negative value (the exact negative value doesn't actually matter, usually tabindex="-1") means that the element is not reachable via sequential keyboard navigation.

**Review by opr — APPROVED** [review]
Thanks @tjcafferkey looks good - thanks for skipping the failing JS test too.
