### PR TITLE
Revert Tax Task completion when all tax rates have been removed.

### LINKED ISSUE #56533: Tax completion should revert when taxes are enabled and no taxes exist
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

As part of https://github.com/woocommerce/woocommerce/pull/56089 we optimized the Tax completion calculation.  However, @woocommerce/ghidorah has noted that this task needs to be marked incomplete if taxes are later removed.

### Expected behavior

Expected the task to not be marked complete if taxes are later removed.

### Actual behavior

Once task is actioned once (completed), it will no longer be marked not complete.

Removing [this line](https://github.com/woocommerce/woocommerce/blob/faed6cd2385bec0355cd7b90b52ac914893faf4a/plugins/woocommerce/src/Admin/Features/OnboardingTasks/Tasks/Tax.php#L123) will probably suffice, though we may also be able to optimize on the presence of `woocommerce_calc_taxes` and ideally remove use of `woocommerce_no_sales_tax` (this needs to be tested).

### Steps to reproduce

1. Navigate to the task list and click the "Tax" task
2. Set up a tax
3. Note the task is complete
4. Remove the previously added tax
5. Note that the task is still marked complete

### WordPress Environment

n/a

### Isolating the problem

- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by prettyboymp**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes #56533 .

(For Bug Fixes) Bug introduced in PR #56089.

This updates the Tax Task so that removing all tax rates will mark the task as in complete again.  The changes previously included in #56089 left the task as complete even after taxes were removed.

### How to test the changes in this Pull Request:

Screenshot 2025-03-26 at 3 21 02 PM

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Navigate to the task list under WP-Admin -> WooCommerce -> Home.
2. The Tax Task will be considered complete under the following conditions:
  * Taxes are disabled.
  * A 3rd party filters to mark tax setup as complete
  * A tax rate exists.
3. If the task shows as complete, enable taxes and remove any existing tax rates.
4. Revisit the task list in WooCommerce -> Home to verify the task now shows as incomplete.
5. Go to WooCommerce -> Settings -> Taxes and add a tax rate.
6. Revisit the task list in WooCommerce -> Home again to verify the task now shows as complete.
7. Go back to WooCommerce -> Settings -> Taxes and remove the tax rate.
8. Revisit the task list in WooCommerce -> Home once again to verify the task now shows as incomplete again.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [X] This Pull Request does not require a changelog entry. (Comment required below)
This is a bug fix for a PR added in the same release, 9.9.

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce/src/Admin/Features/OnboardingTasks/Tasks/Tax.php [hunk 1]
```diff
@@ -13,6 +13,8 @@
  */
 class Tax extends Task {
 
+	private const TAX_RATE_EXISTS_CACHE_KEY = 'woocommerce_onboarding_task_tax_rates_exist';
```
Comment (joshuatf) [inline plugins/woocommerce/src/Admin/Features/OnboardingTasks/Tasks/Tax.php:16]: 👍

File: plugins/woocommerce/src/Admin/Features/OnboardingTasks/Tasks/Tax.php [hunk 2]
```diff
@@ -154,8 +151,18 @@ private function has_existing_tax_rates() {
 	 *
 	 * @return void
 	 */
-	public function track_actioned_on_tax_rate_added() {
+	public function on_tax_rate_added() {
 		$this->mark_actioned();
+		wp_cache_delete( self::TAX_RATE_EXISTS_CACHE_KEY );
```
Comment (joshuatf) [inline plugins/woocommerce/src/Admin/Features/OnboardingTasks/Tasks/Tax.php]: Could we go ahead and set the cache to `true` here to save ourselves a query on the next task load?

```suggestion
		wp_cache_set( self::TAX_RATE_EXISTS_CACHE_KEY, true );
```

**Review by joshuatf — COMMENTED** [review]
Thanks for picking this up, @prettyboymp.  Changes look good; just left a question about one potential optimization.

**Review by joshuatf — APPROVED** [review]
This LGTM!  Tested initially without a tax rate, added a tax rate manually, then removed it.  Also tested by opting out of tax rates for the store and the task was marked complete.

Pinged @woocommerce/ghidorah on this to give a review and make sure things look good here.


**Taxes added**
Screenshot 2025-03-31 at 3 40 36 PM

**Initial state and after removing taxes**
Screenshot 2025-03-31 at 3 39 23 PM

**Review by chihsuan — COMMENTED** [review]
Thanks for working on this! @prettyboymp  

I created a new JN site and noticed the tax task is already marked complete. Is this normal? I thought it should be incomplete on a fresh site. 🤔 

1. Create a new JN site
2. Skip Core Profiler
3. Go to WooCommerce -> Home
4. Tax task shows as complete

Screenshot 2025-04-03 at 15 13 32

**Comment by prettyboymp** [comment]
> Thanks for working on this! @prettyboymp
> 
> I created a new JN site and noticed the tax task is already marked complete. Is this normal? I thought it should be incomplete on a fresh site. 🤔
> 
> 1. Create a new JN site
> 2. Skip Core Profiler
> 3. Go to WooCommerce -> Home
> 4. Tax task shows as complete
> 
> Screenshot 2025-04-03 at 15 13 32

@chihsuan I fixed this issue and left a comment in the code describing the problem.  TLDR; since taxes are disabled by default, using `wc_tax_enabled()` in determining whether the tax task is complete makes it complete by default.  

https://github.com/woocommerce/woocommerce/pull/56735/commits/d9ee80ee2f53422b7485bc8ffac3c5ffc4bb6da0#diff-6879f7e26a5b64d1eae6a471cd098d885c35a40f35f98107d0eaaa737ff1ba36R123-R128

**Review by chihsuan — APPROVED** [review]
Thanks, tested well as described! 👍
