### PR TITLE
Fixes the shipping address map URL

### LINKED ISSUE #14398: DASHBOARD: Orders summary SHIP TO link to Google results in "Not Found" ..
### EXPLANATION OF THE ISSUE

PROBLEM: From admin > wc > orders > [Ship to] (Google Maps) link (includes CUSTOMER NAME resulting in map "not found".   
FIX: Starting the "link" at the STREET will exclude the customer name for a valid map result.  Map is high value for this feature.

### STEPS TO REPRODUCE THE ISSUE

  See any valid address under dashboard.

### SYSTEM STATUS

<details>
```
Grab the system status report from WooCommerce > System Status and paste it here between the `details` tags.
```
</details>

### PR DESCRIPTION
**Pull request by mattyza**
Fixes #14398 

This PR removes the first name, last name, and company from the generated Google Maps URL for the shipping address.

@mikejolley @claudiulodro - I see a filter present here, so I attempted using it, and figured I may have put the code in the incorrect file in terms of the current file structure, so I've opted for filtering out these data points directly inside the method instead, as it's a simpler approach, while not directly using the existing filter. I'd particularly appreciate y'all's thoughts on that approach.

### CODE REVIEW

File: includes/class-wc-order.php [hunk 1]
```diff
@@ -766,6 +766,11 @@ public function get_address( $type = 'billing' ) {
 	 */
 	public function get_shipping_address_map_url() {
 		$address = apply_filters( 'woocommerce_shipping_address_map_url_parts', $this->get_address( 'shipping' ), $this );
+		foreach ( array( 'first_name', 'last_name', 'company' ) as $key ) {
```
Comment (mikejolley) [inline includes/class-wc-order.php]: It would be better to get the address, remove the elements, and THEN filter, so user has full control over final array of data.

File: includes/class-wc-order.php [hunk 2]
```diff
@@ -766,6 +766,11 @@ public function get_address( $type = 'billing' ) {
...
+			if ( isset( $address[$key] ) ) {
```
Comment (mikejolley) [inline includes/class-wc-order.php]: $key needs spaces around it.

**Review by mikejolley — CHANGES_REQUESTED** [review]

**Comment by mattyza** [comment]
@mikejolley - thanks, I've applied your feedback. This is ready for another review.

**Comment by claudiulodro** [comment]
Looks like a test needs to get updated. :)

```
1) WC_Tests_CRUD_Orders::test_get_shipping_address_map_url
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'https://maps.google.com/maps?&q=Barney%2C+Rubble%2C+Bedrock+Ltd.%2C+34+Stonepants+avenue%2C+Rockville%2C+Bedrock%2C+Boulder%2C+00001%2C+US&z=16'
+'https://maps.google.com/maps?&q=34+Stonepants+avenue%2C+Rockville%2C+Bedrock%2C+Boulder%2C+00001%2C+US&z=16'
```

**Comment by mattyza** [comment]
Thanks @claudiulodro. I'll update the test and submit a new PR for that.

**Comment by mikejolley** [comment]
@claudiulodro @mattyza I already did it.

**Comment by rellect** [comment]
Could just do `unset( $address['first_name'], $address['last_name'], $address['company'] );` instead of looping. No need to check if keys exist in `unset`.

**Comment by mikejolley** [comment]
@rellect that would throw notices if not set.

**Comment by bekarice** [comment]
@mikejolley pretty sure that only throws notices if the _array_ isn't defined, but iirc unsetting an [undefined key won't throw notices](http://stackoverflow.com/a/35822050)

**Comment by claudiosanches** [comment]
@mikejolley 

```
$ wp shell
wp> $address = []
=> array(0) {
}
wp> unset( $address['first_name'], $address['last_name'], $address['company'] )
wp> $address
=> array(0) {
}
```

**Comment by mikejolley** [comment]
@bekarice @claudiosanches 🏫
