### PR TITLE
Fix Product Results Count not updating when filtering products

### LINKED ISSUE #63948: Product Results Count: block doesn't get updated when filtering products
Steps to repro:

1. Use block along with Product Filters and Product Collection with a default query (Product Catalog template)
2. Go to frontend
3. Set some product filters to make sure product count changes

**Expected:** Product Results Count is updated

**Actual:** Product Results Count does not update

4. If you refresh the page, block shows updated number of products

### PR DESCRIPTION
**Pull request by kmanijak**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

The `refresh_sorted_by_live_region()` function in the legacy `woocommerce.js` was unconditionally snapshotting the result count `innerHTML` on `DOMContentLoaded` and restoring it after a 2-second timeout. When the Interactivity API updated the Product Results Count block during that 2-second window (e.g. after applying product filters), the stale snapshot would overwrite the updated content.

**Fix:** Guard `refresh_sorted_by_live_region()` to only run when:
1. The page was loaded with a query string (result of filtering)
2. A legacy filter block (`.wc-blocks-filter-wrapper`) is present on the page

This ensures the accessibility announcement still works for classic/legacy filter blocks while not interfering with iAPI-managed content.

Also adds the `data-wp-interactive` attribute to the `ProductResultsCount` block output. Without it iAPI replacement with new filter blocks don't work at all.

Closes #63948.

Bug introduced in PR #55338.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://developer.woocommerce.com/docs/contribution/testing/writing-high-quality-testing-instructions/), include your detailed testing instructions:

### Product Filters - iAPI updates

1. Use the Product Results Count block together with Product Filters and Product Collection (Product Catalog template).
2. Go to the frontend.
3. Apply product filters that change the number of results.
4. Verify the Product Results Count updates correctly without needing a page refresh.
5. Use screen-reader and verify product results count is read on every filter update

### Classic filters

1. With legacy/classic filter blocks, verify the screen reader announcement still works on page reload with filters applied.

Example filters (insert via code editor):

```
<!-- wp:woocommerce/filter-wrapper {"filterType":"rating-filter","heading":"Filter by rating"} -->
<div class="wp-block-woocommerce-filter-wrapper"><!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading">Filter by rating</h3>
<!-- /wp:heading -->

<!-- wp:woocommerce/rating-filter {"lock":{"remove":true}} -->
<div class="wp-block-woocommerce-rating-filter is-loading"></div>
<!-- /wp:woocommerce/rating-filter --></div>
<!-- /wp:woocommerce/filter-wrapper -->


<!-- wp:woocommerce/filter-wrapper {"filterType":"price-filter","heading":"Filter by price"} -->
<div class="wp-block-woocommerce-filter-wrapper">
  <!-- wp:heading {"level":3} -->
  <h3 class="wp-block-heading">Filter by price</h3>
  <!-- /wp:heading -->
  <!-- wp:woocommerce/price-filter {"heading":"","lock":{"remove":true}} -->
  <div class="wp-block-woocommerce-price-filter is-loading">
    <span aria-hidden="true" class="wc-block-product-categories__placeholder"></span>
  </div>
  <!-- /wp:woocommerce/price-filter -->
</div>
<!-- /wp:woocommerce/filter-wrapper -->
```

### Testing that has already taken place:

Manual testing in the browser.

### Milestone

- [x] Automatically assign milestone for the **[next WooCommerce version](../blob/trunk/plugins/woocommerce/woocommerce.php#L6)**

> **Note:** Check the box above to have the milestone automatically assigned when merged.
> Alternatively (e.g. for point releases), manually assign the appropriate milestone.

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [x] Patch

#### Type

-   [x] Fix - Fixes an existing bug

#### Message
Fix Product Results Count block not updating when filtering products with the Interactivity API.

</details>

### CODE REVIEW

File: plugins/woocommerce/client/legacy/js/frontend/woocommerce.js [hunk 1]
```diff
@@ -184,11 +184,18 @@ jQuery( function ( $ ) {
...
+			'.remove_from_cart_button',
+			on_keydown_remove_from_cart
+		);
 	}
 
-	$( document.body ).on( 'item_removed_from_classic_cart updated_wc_div', focus_populate_live_region );
+	$( document.body ).on(
+		'item_removed_from_classic_cart updated_wc_div',
+		focus_populate_live_region
+	);
```
Comment (kmanijak) [inline plugins/woocommerce/client/legacy/js/frontend/woocommerce.js:198]: These are just formatting updates.

File: plugins/woocommerce/client/legacy/js/frontend/woocommerce.js [hunk 2]
```diff
@@ -240,23 +247,38 @@ function focus_populate_live_region() {
...
-		var sorted_by_live_region_id = setTimeout( function () {
-			sorted_by_live_region.setAttribute('aria-hidden', 'false');
-			sorted_by_live_region.innerHTML = '';
-			sorted_by_live_region.innerHTML = text;
-			clearTimeout( sorted_by_live_region_id );
-		}, 2000 );
+	if (
+		! sorted_by_live_region ||
+		! window.location.search ||
+		! legacyFilterBlock
```
Comment (dinhtungdu) [inline plugins/woocommerce/client/legacy/js/frontend/woocommerce.js]: What about widgets? AFAIU, this mean pages with widgets are excluded too, is that correct?

Comment (kmanijak) [reply plugins/woocommerce/client/legacy/js/frontend/woocommerce.js]: Good catch! I reverted the logic! And the refresh logic is only applied if:
- `window.location.search` is there, I guess we can take it as a good heuristic some filtering is applied
- there is NO iAPI filters

Given previously the logic was run every time I think it's acceptable it may run for some cases where iAPI filters are not present (and some query params are applied).

File: plugins/woocommerce/client/legacy/js/frontend/woocommerce.js [hunk 3]
```diff
@@ -240,23 +247,36 @@ function focus_populate_live_region() {
...
-
-		var sorted_by_live_region_id = setTimeout( function () {
-			sorted_by_live_region.setAttribute('aria-hidden', 'false');
-			sorted_by_live_region.innerHTML = '';
-			sorted_by_live_region.innerHTML = text;
-			clearTimeout( sorted_by_live_region_id );
-		}, 2000 );
+	if (
+		! sorted_by_live_region ||
+		! window.location.search ||
```
Comment (dinhtungdu) [inline plugins/woocommerce/client/legacy/js/frontend/woocommerce.js:264]: I'm sorry for incremental review but I didn't notice this earlier. Why do we need this? `search` could be present for non-filter reasons like UTM params/pagination, right?

Comment (kmanijak) [reply plugins/woocommerce/client/legacy/js/frontend/woocommerce.js:264]: Yeah, as I wrote in another comment

> window.location.search is there, I guess we can take it as a good heuristic some filtering is applied

I consider this logic invasive and I reckoned we should avoid running it more often than necessary. And while you're right, lots of other things may add some query params, I still considered it's better to limit the cases in which we run this logic.

Basically we can either remove `! window.location.search` and run the logic always if iAPI are not there or keep it here and limit some more cases (where query params are not present) even if that doesn't guarantee filtering applied.

But I don't have a strong opinion though, If you think it's worth it, I can remove this condition!

Comment (dinhtungdu) [reply plugins/woocommerce/client/legacy/js/frontend/woocommerce.js:264]: Yeah, makes sense! thanks for the explanation!

**Review by dinhtungdu — APPROVED** [review]
Thanks for addressing the feedback. This is LGTM now.

I have a question probably we should address it in the follow up. I know that we're doing progressive enhancement, which first started by wrapping the `woocommerce_result_count()` in the block. But I think with Interactivity API, we shouldn't do that right, we should introduce the block without connection to legacy JS which is causing the trouble like the one we're fixing. WDYT?

**Comment by kmanijak** [comment]
> I have a question probably we should address it in the follow up. I know that we're doing progressive enhancement, which first started by wrapping the woocommerce_result_count() in the block. But I think with Interactivity API, we shouldn't do that right, we should introduce the block without connection to legacy JS which is causing the trouble like the one we're fixing. WDYT?

Well, we'll have to support the classic scenario too. So while we could "disconnect" the block from the legacy JS, we still have to cover the scenario described. Keep in mind this logic in question (updating block content in `setTimeout` was an accessibility improvement introduced only recently (about a year ago). What I'm trying to say is, even with fully blockified block, we'll face the same issue if it's gonna support classic filters too.
