### PR TITLE
Prevent count cache errors when order hooks are run in different orders

### LINKED ISSUE #56650: Order count cache is incorrect when a status is immediately transitioned
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When creating an order that immediately sets a status to one of the "non-default" statuses (checkout draft, pending, etc), the order count cache increases the order count for both statuses since both the `woocommerce_new_order` and `woocommerce_order_status_changed` hooks are fired.

This issue is compounded by the fact that the hooks are run in different orders in the frontend and backend.

Image

Introduced in https://github.com/woocommerce/woocommerce/pull/54034

### Expected behavior

Expected a new order to only increase the cache count by 1 in the respective status.

### Actual behavior

Cache count incorrectly increments by 2 orders if order status is different.

### Steps to reproduce

1. Go to the admin orders screen
2. Make note of the order counts
3. Click "Add order"
4. Set the order status to complete
5. Click "Create"
6. Note that the order count has incorrectly increased by 2

### WordPress Environment

n/a

### Isolating the problem

- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by joshuatf**
### Changes proposed in this Pull Request:

This PR fixes the order count becoming out of sync as order hooks fire in different orders and potentially multiple times.

Closes #56650 .

(For Bug Fixes) Bug introduced in PR #54034.

### Screenshots or screen recordings:

| Before | After |
| ------ | ----- |
|   Screenshot 2025-03-24 at 3 22 34 PM  |   Screenshot 2025-03-24 at 3 22 25 PM |

### How to test the changes in this Pull Request:

For all tests, install an object persistent cache plugin like [Docket Cache](https://wordpress.org/plugins/docket-cache/).

**Admin orders without status changes**
1. Go to WooCommerce -> Orders
2. Take note of the order counts
3. Click "Add order"
4. Keep the order status as "Pending"
5. Click "Create"
6. Make sure that "Pending" has increased by 1 and no other order counts have

**Admin orders with status changes**
1. Go to WooCommerce -> Orders
2. Take note of the order counts
3. Click "Add order"
4. Set the status to "Complete" or any non-pending status
5. Click "Create"
6. Make sure that "Complete" has increased by 1 and no other order counts have increased or decreased

**Customer placed order**
1. Add various payment gateways from as a merchant that have different initial order statuses
2. Take note of the order counts
3. As a customer, add an item to the cart
4. Checkout as a customer
5. In the admin, make sure order counts are reflected correctly

**Programmatically placed order (dev only)**
1. Make sure tests pass
6. Attempt to create orders without status changes and persist
7. Make sure that order counts are correctly reflected
8. Attempt to create an order and set a status one or more times before persisting
9. Make sure that order counts are correctly reflected

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce/src/Caches/OrderCountCacheService.php [hunk 1]
```diff
@@ -44,6 +60,18 @@ public function update_on_new_order( $order_id, $order ) {
 			return;
 		}
 
+		// If the order status was updated, we need to increment the order count cache for the
+		// initial status that was errantly decremented on order status change.
+		if ( isset( $this->initial_order_statuses[ $order_id ] ) ) {
```
Comment (joshuatf) [inline plugins/woocommerce/src/Caches/OrderCountCacheService.php:65]: Because `woocommerce_new_order` can fire before or after `woocommerce_order_status_changed` and `woocommerce_order_status_changed` can fire multiple times, we want to make sure we didn't accidentally decrement a status count that had never been persisted.

**Review by joshuatf — COMMENTED** [review]
This is a bit hacky as the hooks have somewhat unexpected behavior.  The alternative to this is to directly integrate `OrderCountCache` into `WC_Order`.  Given there is existing caching in that class, this is not unprecedented.

File: plugins/woocommerce/src/Caches/OrderCountCacheService.php [hunk 2]
```diff
@@ -10,6 +10,8 @@
 
 /**
  * A service class to help with updates to the aggregate orders cache.
+ *
+ * @internal
  */
 class OrderCountCacheService {
```
Comment (kalessil) [inline plugins/woocommerce/src/Caches/OrderCountCacheService.php:16]: Since we are marking it internal, how about making it final?

File: plugins/woocommerce/src/Caches/OrderCountCacheService.php [hunk 3]
```diff
@@ -44,6 +60,18 @@ public function update_on_new_order( $order_id, $order ) {
...
 		}
 
+		// If the order status was updated, we need to increment the order count cache for the
+		// initial status that was errantly decremented on order status change.
+		if ( isset( $this->initial_order_statuses[ $order_id ] ) ) {
+			$this->order_count_cache->increment( $order->get_type(), $this->get_prefixed_status( $this->initial_order_statuses[ $order_id ] ) );
+		}
+
+		// If the order status count has already been incremented, we can skip incrementing it again.
+		if ( isset( $this->order_statuses[ $order->get_id() ] ) && $this->order_statuses[ $order->get_id() ] === $order->get_status() ) {
```
Comment (kalessil) [inline plugins/woocommerce/src/Caches/OrderCountCacheService.php:70]: Guess we could use `$order_id` over `$order->get_id()` for consistency?

Comment (kalessil) [reply plugins/woocommerce/src/Caches/OrderCountCacheService.php:70]: Also there is potential to extract repeating `$this->get_prefixed_status( ... )` in `update_on_order_status_changed` and `update_on_new_order` into local variables to simplify the codebase a bit.

**Review by kalessil — COMMENTED** [review]
Did a quick review and leaving some comments - will do manual testing tomorrow.

**Comment by kalessil** [comment]
Manual testing results:

- create an order as 'completed' from the admin area: :lady_beetle: - order counted twice
Screenshot from 2025-03-26 09-44-16

- change the order status to cancelled: :heavy_check_mark: 
Screenshot from 2025-03-26 09-47-19

- place an order from storefront: :heavy_check_mark: 
Screenshot from 2025-03-26 09-51-02

**Comment by joshuatf** [comment]
Thanks for testing, @kalessil!  Was able to reproduce and found [this relevant tracs issue](https://core.trac.wordpress.org/ticket/62236) in WP core.

It seems we can't use negative numbers (surprising since there's no mention of this in [the API docs](https://developer.wordpress.org/reference/functions/wp_cache_decr/)), so the initial decrement in status change was not successful, which may explain why we also didn't initially find issues in https://github.com/woocommerce/woocommerce/pull/54034.

Pushed a change in https://github.com/woocommerce/woocommerce/pull/56652/commits/21d33d3db77da834fb6322a51ebfadaa98fc0c6b that checks for decrement success before re-incrementing the number in new orders.

https://github.com/user-attachments/assets/b6d630f1-d320-47e3-b33b-dbee6119063b

**Review by kalessil — APPROVED** [review]
Works like a charm, preapproving!
