### PR TITLE
Product Editor: Show error notice when error occurs uploading an image via drop on Images

### LINKED ISSUE #48393: Product Editor: No error message when error occurs uploading an image via drop on Images
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When you drop an invalid file on the Images section of the new product editor, no error message is shown.

### Expected behavior

An error should be shown to the user specifying why the file was invalid.

### Actual behavior

No error is shown to the user specifying why the file was invalid.

### Steps to reproduce

With a WooCommerce env with the new product editor enabled (**WooCommerce** > **Settings** > **Advanced** > **Features** > **Experimental features**)...

1. Go to **Products** > **Add New**
2. Drag a `.txt` file to the Images section

Screenshot 2024-06-11 at 13 48 07

3. Verify that no error message is shown and the file isn't uploaded

### WordPress Environment

n/a

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by mattsherman**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

This PR shows errors that occur when uploading an image via drop on the Images section by displaying an error notice (snackbar).

Closes #48393.

### How to test the changes in this Pull Request:

With a WooCommerce env with the new product editor enabled (**WooCommerce** > **Settings** > **Advanced** > **Features** > **Experimental features**), and the Gutenberg plugin installed...

1. Go to **Products** > **Add New**
2. Drag a `.txt` file to the Images section
3. Verify an error notice is shown and the file isn't uploaded.

https://github.com/woocommerce/woocommerce/assets/2098816/94544d40-7eea-4f74-a13f-ac5abfafa025

Note: If multiple invalid files are dropped, an error notice will be shown for each one...

https://github.com/woocommerce/woocommerce/assets/2098816/6eb20165-77c7-435b-a790-bced975faf9e

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

File: packages/js/product-editor/changelog/fix-product-editor-images-drop-error [hunk 1]
```diff
@@ -0,0 +1,4 @@
+Significance: patch
+Type: fix
+
+Show error notice when unable to upload an image.
```
Comment (retrofox) [inline packages/js/product-editor/changelog/fix-product-editor-images-drop-error:4]: It seems that you need to add the `Product Editor: ` prefix here?

File: packages/js/components/src/index.ts [hunk 2]
```diff
@@ -23,7 +23,7 @@ export { ImageGallery, ImageGalleryItem } from './image-gallery';
 export { default as ImageUpload } from './image-upload';
 export { Link } from './link';
 export { default as List } from './list';
-export { MediaUploader } from './media-uploader';
+export { MediaUploader, MediaUploaderErrorCallback } from './media-uploader';
```
Comment (retrofox) [inline packages/js/components/src/index.ts:26]:
```suggestion
export { MediaUploader, type MediaUploaderErrorCallback } from './media-uploader';
```

File: packages/js/product-editor/src/blocks/product-fields/images/edit.tsx [hunk 3]
```diff
@@ -186,6 +190,12 @@ export function ImageBlockEdit( {
 		}
 	}
 
+	const handleMediaUploaderError: MediaUploaderErrorCallback = function (
+		error
+	) {
+		createErrorNotice( `Error uploading image:\n${ error.message }` );
```
Comment (retrofox) [inline packages/js/product-editor/src/blocks/product-fields/images/edit.tsx]: We need to translate this message.

**Review by retrofox — CHANGES_REQUESTED** [review]
I still need to test the PR, but anyway, I'm requesting changes to ensure the message is translated in case it shows up in the UI.

**Comment by retrofox** [comment]
Functionality-wise, it works pretty well 💯 

image

File: packages/js/product-editor/changelog/fix-product-editor-images-drop-error (hunk 1 above)
Comment (mattsherman) [reply packages/js/product-editor/changelog/fix-product-editor-images-drop-error:4]: Hmm... I've never added the prefix before, since it is in the `@woocommerce/product-editor` package.

File: packages/js/product-editor/src/blocks/product-fields/images/edit.tsx (hunk 3 above)
Comment (mattsherman) [reply packages/js/product-editor/src/blocks/product-fields/images/edit.tsx]: Great catch.

**Comment by mattsherman** [comment]
@retrofox Ready for re-review!

**Comment by mattsherman** [comment]
> @retrofox Ready for re-review!

Wait... need to fix lint errors :-(

**Review by retrofox — APPROVED** [review]
image

**Comment by retrofox** [comment]
> > @retrofox Ready for re-review!
> 
> Wait... need to fix lint errors :-(

okay!
