### PR TITLE
Use exact match when comparing normalized path against normalized pag…

### LINKED ISSUE #52895: Coming soon store only incorrectly flag URL with `/shopping`
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Originally [reported](https://wordpress.org/support/topic/how-can-i-completely-disable-site-visibility-functionality/page/2/#post-18136012) by a user in forum, their page with "/shopping" in URL is incorrectly flagged as a store page.

Image

### Expected behavior

Non-store pages should be hidden behind coming soon mode

### Actual behavior

Non-store pages are hid behind coming soon

### Steps to reproduce

1. Create a page with URL `/shopping-for-kids`
2. Go to `WooCommerce > Settings > Site visibility`
3. Set `Coming soon` and select `Apply to store pages only`
4. In an incognito window, browse the new page
5. Observe it's incorrectly hid behind coming soon

### Isolating the problem

- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by moon0326**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes #52895  

This PR fixes a bug where a URL containing part of a store page's URL is incorrectly identified as a valid store page URL.

I might be oversimplifying it, but I couldn’t find a reason to use `strpos`. I’ve replaced it with `===`, and all unit tests are passing.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Create a new JN site with this branch.
2. Set the site to Coming soon mode with `Apply to store pages only` option.
3. Create a new page from `Pages -> Add a new page`
4. Set the page title to `Shopping URL` and confirm the permalink is set to `shopping-url`.
5. Open the page in an incognito session.
6. The page content should render.

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

 Fixes a bug where a URL containing part of a store page's URL is incorrectly identified as a valid store page URL

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce/tests/legacy/unit-tests/woocommerce-admin/wc-admin-helper.php [hunk 1]
```diff
@@ -225,6 +225,7 @@ public function get_store_page_test_data() {
 			array( 'https://example.com/shop/uncategorized/test/', true ), // Test case 5: URL matches product page.
 			array( '/shop/t-shirt/test/', true ), // Test case 6: URL path matches product page.
 			array( 'https://example.com/about-us/', false ), // Test case 7: URL does not match any store page.
+			array( 'https://example.com/shopping-url/', false ), // Test case 8: URL path contains aprt of 'shop' page.
```
Comment (ilyasfoo) [inline plugins/woocommerce/tests/legacy/unit-tests/woocommerce-admin/wc-admin-helper.php]: Nit: Typo
```suggestion
			array( 'https://example.com/shopping-url/', false ), // Test case 8: URL path contains part of 'shop' page.
```

File: plugins/woocommerce/src/Admin/WCAdminHelper.php [hunk 2]
```diff
@@ -200,11 +200,12 @@ public static function is_store_page( $url = '' ) {
 
 			$permalink = get_permalink( $page_id );
 
+
```
Comment (ilyasfoo) [inline plugins/woocommerce/src/Admin/WCAdminHelper.php]: Nit: perhaps unintended?

```suggestion
```

File: plugins/woocommerce/tests/legacy/unit-tests/woocommerce-admin/wc-admin-helper.php [hunk 3]
```diff
@@ -225,6 +225,7 @@ public function get_store_page_test_data() {
...
 		);
```
Comment (ilyasfoo) [inline plugins/woocommerce/tests/legacy/unit-tests/woocommerce-admin/wc-admin-helper.php:232]: Also, I think it's useful to add more tests, such as:

```
array( 'https://example.com/shop/?tag=test', true )
```

and add all possible [store pages defined here](https://github.com/woocommerce/woocommerce/blob/9a9f0e7658e90fe0fc75f80c3703aaf47d16ad4e/plugins/woocommerce/src/Admin/WCAdminHelper.php#L168-L174). What do you think?

**Review by ilyasfoo — COMMENTED** [review]
Thanks for working on this, @moon0326! Tests well but I have suggestion to add more tests

File: plugins/woocommerce/tests/legacy/unit-tests/woocommerce-admin/wc-admin-helper.php (hunk 3 above)
Comment (moon0326) [reply plugins/woocommerce/tests/legacy/unit-tests/woocommerce-admin/wc-admin-helper.php:232]: @ilyasfoo Sounds good! I'm on it

Comment (moon0326) [reply plugins/woocommerce/tests/legacy/unit-tests/woocommerce-admin/wc-admin-helper.php:232]: @ilyasfoo Updated it in [Add more test cases](https://github.com/woocommerce/woocommerce/pull/53120/commits/67f2f808c4d75fd07ac4bba7d8b3eee36f5faaa2). FYI, I've excluded coming-soon and terms pages.

File: plugins/woocommerce/tests/legacy/unit-tests/woocommerce-admin/wc-admin-helper.php [hunk 4]
```diff
@@ -262,39 +270,39 @@ public function test_is_store_page() {
...
-		global $wp_post_types;
-		$wp_post_types['product']->has_archive = 'shop';
-
-		$product_post_type = get_post_type_object( 'product' );
-
-		$link = get_post_type_archive_link( 'product' );
-		$this->assertTrue( WCAdminHelper::is_store_page( $link ) );
-	}
+	//
+	// **
```
Comment (ilyasfoo) [inline plugins/woocommerce/tests/legacy/unit-tests/woocommerce-admin/wc-admin-helper.php]: Hey @moon0326, is this comment out intended?

File: plugins/woocommerce/tests/legacy/unit-tests/woocommerce-admin/wc-admin-helper.php [hunk 5]
```diff
@@ -240,14 +244,18 @@ public function test_is_store_page() {
 
 		$wp_rewrite->expects( $this->any() )
 			->method( 'generate_rewrite_rule' )
-			->willReturn( array( 'shop/(.+?)/?$' => 'index.php?product_cat=$matches[1]&year=$matches[2]' ) );
+			->willReturn(
+				array(
+					'shop/.*?$' => 'index.php?product_cat=$matches[1]&year=$matches[2]',
```
Comment (ilyasfoo) [inline plugins/woocommerce/tests/legacy/unit-tests/woocommerce-admin/wc-admin-helper.php]: I'm curious why was this change needed?

File: plugins/woocommerce/tests/legacy/unit-tests/woocommerce-admin/wc-admin-helper.php (hunk 4 above)
Comment (moon0326) [reply plugins/woocommerce/tests/legacy/unit-tests/woocommerce-admin/wc-admin-helper.php]: @ilyasfoo My bad 🤦 I forgot to uncomment them. Fixed!

File: plugins/woocommerce/tests/legacy/unit-tests/woocommerce-admin/wc-admin-helper.php (hunk 5 above)
Comment (moon0326) [reply plugins/woocommerce/tests/legacy/unit-tests/woocommerce-admin/wc-admin-helper.php]: @ilyasfoo The previous regex did not catch "https://example.com/shop/?tag=test".

Comment (ilyasfoo) [reply plugins/woocommerce/tests/legacy/unit-tests/woocommerce-admin/wc-admin-helper.php]: Got it, thanks. However, I believe the regex doesn't seem to capture any group, thus `$matches[1]` and `$matches[2]` will never be defined. I'm wondering if this will have any unexpected outcome 🤔 

cc @chihsuan since I think you originally introduced the regex

Comment (moon0326) [reply plugins/woocommerce/tests/legacy/unit-tests/woocommerce-admin/wc-admin-helper.php]: @ilyasfoo Good point. The tests are passing, so I also wonder if we still need them. I'll wait for Chi's input.

We can also add both of them if needed.

Comment (chihsuan) [reply plugins/woocommerce/tests/legacy/unit-tests/woocommerce-admin/wc-admin-helper.php]: Hey @moon0326 @ilyasfoo, The regex was introduced to catch the URL path when the Product permalinks is set to `/shop/%product_cat%/` or something like that.

For example, if the product permalink is `/shop/%product_cat%/`, then the URL path `/shop/test` will match the regex.


Screenshot 2024-11-26 at 15 50 49

Comment (ilyasfoo) [reply plugins/woocommerce/tests/legacy/unit-tests/woocommerce-admin/wc-admin-helper.php]: Thanks for the input, @chihsuan!

```suggestion
					'shop/.*?$' => 'index.php',
```

@moon0326  It seems we might not need `$matches` after all. What do you think of simplifying it so it doesn't add confusion in the future? My local test is passing with this change.

Comment (moon0326) [reply plugins/woocommerce/tests/legacy/unit-tests/woocommerce-admin/wc-admin-helper.php]: @ilyasfoo Sounds good!

**Review by ilyasfoo — CHANGES_REQUESTED** [review]
@moon0326  apologies for missing this but I gave it another spin and it seems pages like `/cart` and `/checkout` is not protected under coming soon when we use `Post name` in permalink settings. I confirm this does not happen in `trunk`.

It's also odd that the "coming soon notice" is still shown when viewing with logged-in admin, but non-logged-in users can still see the cart page.

image

I also wonder why our tests do not catch this, I imagine it does not cover all permalink use cases 🤔

**Comment by moon0326** [comment]
> apologies for missing this but I gave it another spin and it seems pages like `/cart` and `/checkout` is not protected under coming soon when we use `Post name` in permalink settings. I confirm this does not happen in `trunk`.

Thank you for the catch. I was able to reproduce it.

I think our test cases do not cover all the permalink settings. We have the following rewrite setup to simulate permalinks, but I think it’s insufficient. I need to investigate further to understand what’s really going on. I'll keep you updated.

```
$wp_rewrite->expects( $this->any() )
	->method( 'generate_rewrite_rule' )
	->willReturn(
		array(
			'shop/.*?$' => 'index.php?product_cat=$matches[1]&year=$matches[2]',
		)
	);
```  

> It's also odd that the "coming soon notice" is still shown when viewing with logged-in admin, but non-logged-in users can still see the cart page.

Let's handle that in a separate PR.

**Comment by moon0326** [comment]
> @moon0326 apologies for missing this but I gave it another spin and it seems pages like `/cart` and `/checkout` is not protected under coming soon when we use `Post name` in permalink settings. I confirm this does not happen in `trunk`.
> 
> It's also odd that the "coming soon notice" is still shown when viewing with logged-in admin, but non-logged-in users can still see the cart page.
> 
> image
> I also wonder why our tests do not catch this, I imagine it does not cover all permalink use cases 🤔

The issue is fixed in [When the provided URL does not have any paths, compare normalized lin…](https://github.com/woocommerce/woocommerce/pull/53120/commits/c21bf725a11ab3c1a17085f435efe27cbbc64065)

**Review by ilyasfoo — APPROVED** [review]
Thanks, @moon0326! Tests well!

> Let's handle that in a separate PR.

Sounds good!

**Comment by chihsuan** [comment]
Hey, @moon0326 I just noticed that this PR is still open. 😅  Could you please fix the CI and rebase the branch from trunk? I think it's ready to be merged. 

I'm also wondering if this PR would solve https://github.com/woocommerce/woocommerce/issues/53129 as well? cc @ilyasfoo

**Comment by ilyasfoo** [comment]
@chihsuan it seems this PR does not resolve https://github.com/woocommerce/woocommerce/issues/53129 since it's still reproducible in trunk.
