### PR TITLE
[PHP 8.1] Fix code that throws deprecation notices in tests in PHP 8.1

### LINKED ISSUE #31270: WooCommerce core and tests not compatible with PHP 8.1
As far as I can tell, WooCommerce core isn't currently being tested against the upcoming PHP version 8.1, which is due to be released in 3 days time on 25 November.

**Prerequisites (mark completed items with an [x]):**
- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
Unit tests fail to run (with a PHP fatal error) when using PHP 8.1 (both WooCommerce trunk and 5.8.2).

**Expected behavior**
Ideally, WooCommerce (including all tests) would run and pass when running against PHP 8.1.

**Actual behavior**

PHPUnit exits with several warnings and a fatal error during tests bootstrap before any tests can be run:
```
PHP Warning:  Private methods cannot be final as they are never overridden by other classes in wp-content/plugins/woocommerce/plugins/woocommerce/bin/composer/phpunit/vendor/phpunit/phpunit/src/Util/Configuration.php on line 176

Warning: Private methods cannot be final as they are never overridden by other classes in wp-content/plugins/woocommerce/plugins/woocommerce/bin/composer/phpunit/vendor/phpunit/phpunit/src/Util/Configuration.php on line 176
PHP Fatal error:  Cannot acquire reference to $GLOBALS in wp-content/plugins/woocommerce/plugins/woocommerce/bin/composer/phpunit/vendor/phpunit/phpunit/src/Util/Configuration.php on line 543

Fatal error: Cannot acquire reference to $GLOBALS in wp-content/plugins/woocommerce/plugins/woocommerce/bin/composer/phpunit/vendor/phpunit/phpunit/src/Util/Configuration.php on line 543
```

This means that currently no tests are run against PHP 8.1, making it impractical to know what actual plugin code changes are required to work successfully on PHP 8.1

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:

1. Check out latest trunk. cd to the `plugins/woocommerce` subdirectory
2. Using PHP 8.1, run `composer update --ignore-platform-reqs`
3. Run `vendor/bin/phpunit` and the above fatal error occurs.

**Screenshots**

N/A

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report we won't be able to fully evaluate this issue.
<details>

```
php -v
PHP 8.0.12 (cli) (built: Oct 21 2021 06:07:28) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.12, Copyright (c) Zend Technologies
    with Xdebug v3.1.1, Copyright (c) 2002-2021, by Derick Rethans
    with Zend OPcache v8.0.12, Copyright (c), by Zend Technologies
```

</details>

**Suggested Way Forward**

I believe the composer configand test suite will need to be updated [as outlined here](https://make.wordpress.org/core/2021/09/27/changes-to-the-wordpress-core-php-test-suite/), so that the test suite correctly uses newer PHPunit versions on PHP 8.1, while still using older PHPUnit versions. 

`yoast/phpunit-polyfills` likely needs to be updated to v1.0.1 as well.

The [CI config](https://github.com/woocommerce/woocommerce/blob/trunk/.github/workflows/ci.yml) should also ideally run against PHP 8.1.

Any PHP 8.1 related compatibility notices/warnings/errors should ideally be identified and resolved.

In our WooCommerce extension, we are running our own unit tests by using some of WooCommerce core's test structures, and so far I've been able to identify the following WooCommerce core deprecation warnings that will likely need to be resolved:

<details>
```
Installing...
Running as single site... To run multisite, use -c tests/phpunit/multisite.xml
PHP Deprecated:  Return type of WC_DateTime::setTimezone($timezone) should either be compatible with DateTime::setTimezone(DateTimeZone $timezone): DateTime, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /wp-content/plugins/woocommerce/plugins/woocommerce/includes/class-wc-datetime.php on line 57

Deprecated: Return type of WC_DateTime::setTimezone($timezone) should either be compatible with DateTime::setTimezone(DateTimeZone $timezone): DateTime, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /wp-content/plugins/woocommerce/plugins/woocommerce/includes/class-wc-datetime.php on line 57
PHP Deprecated:  Return type of WC_DateTime::getOffset() should either be compatible with DateTime::getOffset(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /wp-content/plugins/woocommerce/plugins/woocommerce/includes/class-wc-datetime.php on line 47

Deprecated: Return type of WC_DateTime::getOffset() should either be compatible with DateTime::getOffset(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /wp-content/plugins/woocommerce/plugins/woocommerce/includes/class-wc-datetime.php on line 47
PHP Deprecated:  Return type of WC_DateTime::getTimestamp() should either be compatible with DateTime::getTimestamp(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /wp-content/plugins/woocommerce/plugins/woocommerce/includes/class-wc-datetime.php on line 68

Deprecated: Return type of WC_DateTime::getTimestamp() should either be compatible with DateTime::getTimestamp(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /wp-content/plugins/woocommerce/plugins/woocommerce/includes/class-wc-datetime.php on line 68
PHP Deprecated:  Return type of WC_Meta_Data::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /wp-content/plugins/woocommerce/plugins/woocommerce/includes/class-wc-meta-data.php on line 50

Deprecated: Return type of WC_Meta_Data::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /wp-content/plugins/woocommerce/plugins/woocommerce/includes/class-wc-meta-data.php on line 50

PHP Deprecated:  Return type of ActionScheduler_DateTime::setTimezone($timezone) should either be compatible with DateTime::setTimezone(DateTimeZone $timezone): DateTime, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /wp-content/plugins/woocommerce/plugins/woocommerce/packages/action-scheduler/classes/ActionScheduler_DateTime.php on line 60

Deprecated: Return type of ActionScheduler_DateTime::setTimezone($timezone) should either be compatible with DateTime::setTimezone(DateTimeZone $timezone): DateTime, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /wp-content/plugins/woocommerce/plugins/woocommerce/packages/action-scheduler/classes/ActionScheduler_DateTime.php on line 60
PHP Deprecated:  Return type of ActionScheduler_DateTime::getOffset() should either be compatible with DateTime::getOffset(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /wp-content/plugins/woocommerce/plugins/woocommerce/packages/action-scheduler/classes/ActionScheduler_DateTime.php on line 48

Deprecated: Return type of ActionScheduler_DateTime::getOffset() should either be compatible with DateTime::getOffset(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /wp-content/plugins/woocommerce/plugins/woocommerce/packages/action-scheduler/classes/ActionScheduler_DateTime.php on line 48
PHP Deprecated:  Return type of ActionScheduler_DateTime::getTimestamp() should either be compatible with DateTime::getTimestamp(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /wp-content/plugins/woocommerce/plugins/woocommerce/packages/action-scheduler/classes/ActionScheduler_DateTime.php on line 27

Deprecated: Return type of ActionScheduler_DateTime::getTimestamp() should either be compatible with DateTime::getTimestamp(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /wp-content/plugins/woocommerce/plugins/woocommerce/packages/action-scheduler/classes/ActionScheduler_DateTime.php on line 27

PHP Fatal error:  Declaration of WP_HTTP_TestCase::setUpBeforeClass() must be compatible with Yoast\PHPUnitPolyfills\TestCases\TestCase::setUpBeforeClass(): void in /wp-content/plugins/woocommerce/plugins/woocommerce/tests/legacy/includes/wp-http-testcase.php on line 137

Fatal error: Declaration of WP_HTTP_TestCase::setUpBeforeClass() must be compatible with Yoast\PHPUnitPolyfills\TestCases\TestCase::setUpBeforeClass(): void in /wp-content/plugins/woocommerce/plugins/woocommerce/tests/legacy/includes/wp-http-testcase.php on line 137
```
</details>

Avoiding those kinds of deprecation warnings involves either bumping the minimum required PHP version from 7.0 to 7.1, or alternatively adding the `#[\ReturnTypeWillChange]` attribute.

Changes to Action Scheduler also look to be necessary.

Thanks for your time!

### LINKED ISSUE #31386: Deprecated warnings in WP CLI with PHP 8.1
I was testing a WP CLI PR with PHP 8.1 and had the following deprecated notices:

- `Deprecated: explode(): Passing null to parameter #2 ($string) of type string is deprecated in /Users/ronrennick/Sites/test/wp-content/plugins/woocommerce/includes/data-stores/class-wc-product-data-store-cpt.php on line 371`
- `Deprecated: Automatic conversion of false to array is deprecated in /Users/ronrennick/Sites/test/wp-content/plugins/woocommerce/includes/wc-term-functions.php on line 536`
- `Deprecated: Function strftime() is deprecated in /Users/ronrennick/Sites/test/wp-content/plugins/woocommerce/includes/data-stores/abstract-wc-order-data-store-cpt.php on line 264`

The line # correspond to WC5.9.0.

### PR DESCRIPTION
**Pull request by Konamiman**
### All Submissions:

* [ ] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
* [ ] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Do the necessary code fixes so that the WooCommerce unit tests don't throw deprecation notices in PHP 8.1. The deprecation notices fixed are:

- Various "passing null to parameter (...) is deprecated".
- Usage of `strftime`.
- Using `false` as if it was an empty array.
- Mismatching return type of implemented interfaces, that's fixed by adding `#[\ReturnTypeWillChange]` attributes.

Note that this pull request alone is not enough to fix all the tests:

1. Blocks and Action Scheduler will need fixes too (pull request links in the testing instructions).
2. WordPress core itself isn't currently compatible with PHP 8.1. Some tests are skipped temporarily (see `skip_on_php_8_1` method introduced in `class-wc-unit-test-case.php`), only in PHP 8.1, until that's no longer the case.

Once Blocks and Action Scheduler have got the required fixes we could extend the GitHub action that run the tests to include PHP 8.1, keeping the WordPress-offending ones disabled for the time being.

Closes: https://github.com/woocommerce/woocommerce/issues/31270
Closes: https://github.com/woocommerce/woocommerce/issues/31386

**NOTE:** A lot of code formatting changes were needed for the code sniffer to be happy. These are in a separate commit for easier review.

### How to test the changes in this Pull Request:

1. Ensure that the fixes required for Blocks and Action Scheduler are applied ([PR for blocks](https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/5287) - [PR for Action Scheduler](https://github.com/woocommerce/action-scheduler/pull/791)).
2. Run the unit tests in PHP 7.
3. Perform [the changes needed to run tests in PHP 8](https://github.com/woocommerce/woocommerce/tree/trunk/plugins/woocommerce/tests#running-tests-in-php-8).
4. Run the unit tests in both PHP 8.0 and PHP 8.1.

### Other information:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully run tests with your changes locally?

### Changelog entry

> Fix - Code that produces deprecation notices when running unit tests in PHP 8.1.

### FOR PR REVIEWER ONLY:

* [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

File: plugins/woocommerce/includes/data-stores/class-wc-product-data-store-cpt.php [hunk 1]
```diff
@@ -368,7 +368,7 @@ protected function read_product_data( &$product ) {
 		$set_props['category_ids']      = $this->get_term_ids( $product, 'product_cat' );
 		$set_props['tag_ids']           = $this->get_term_ids( $product, 'product_tag' );
 		$set_props['shipping_class_id'] = current( $this->get_term_ids( $product, 'product_shipping_class' ) );
-		$set_props['gallery_image_ids'] = array_filter( explode( ',', $set_props['gallery_image_ids'] ) );
+		$set_props['gallery_image_ids'] = array_filter( explode( ',', $set_props['gallery_image_ids'] ?? '' ) );
```
Comment (peterfabian) [inline plugins/woocommerce/includes/data-stores/class-wc-product-data-store-cpt.php:371]: Since we're fixing this, I think there are probably more places in code where the second argument may be null, e.g. maybe over here: https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/includes/class-wc-tax.php#L51
or here 
https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/includes/wc-core-functions.php#L984



Do you think we should fix them proactively or ad-hoc?

I suppose the situation is similar with a bunch of other functions like `str_replace`, `class_exists` or `urldecode`...

File: plugins/woocommerce/includes/data-stores/class-wc-product-variable-data-store-cpt.php [hunk 2]
```diff
@@ -119,6 +119,9 @@ protected function read_product_data( &$product ) {
 	public function read_children( &$product, $force_read = false ) {
 		$children_transient_name = 'wc_product_children_' . $product->get_id();
 		$children                = get_transient( $children_transient_name );
+		if(false === $children) {
```
Comment (peterfabian) [inline plugins/woocommerce/includes/data-stores/class-wc-product-variable-data-store-cpt.php]:
```suggestion
		if ( false === $children ) {
```

File: plugins/woocommerce/tests/legacy/bootstrap.php [hunk 3]
```diff
@@ -81,6 +81,8 @@ public function __construct() {
 
 		// re-initialize dependency injection, this needs to be the last operation after everything else is in place.
 		$this->initialize_dependency_injection();
+
+		//error_reporting(error_reporting() & ~E_DEPRECATED);
```
Comment (peterfabian) [inline plugins/woocommerce/tests/legacy/bootstrap.php]: I'm assuming this doesn't have any actual effect on the tests, right? Do you want to keep this?

File: plugins/woocommerce/tests/php/includes/class-wc-ajax-test.php [hunk 4]
```diff
@@ -112,4 +114,14 @@ public function test_create_api_key_long_description_failure() {
 		$this->assertFalse( $response['success'] );
 		$this->assertEquals( $response['data']['message'], 'There was an error generating your API Key.' );
 	}
+
+	/**
+	 * Skip the current test on PHP 8.1 and higher.
+	 * TODO: Remove this method and its usages once WordPress is compatible with PHP 8.1.
```
Comment (peterfabian) [inline plugins/woocommerce/tests/php/includes/class-wc-ajax-test.php]: Might be worth adding a comment that there are multiple copies of the method.

**Review by peterfabian — COMMENTED** [review]
Apologies for the monstrous delay! Thanks, overall it's looking pretty good! Great work! I have a couple of questions/suggestions in the comments below.

**Comment by peterfabian** [comment]
Side note: it might be worth rebasing this to make testing a bit easier, because only god knows how to build this now, I used `composer install`, not the new `pnpm` stuff, as it was giving me npm/node errors, plus it should fix the Blocks error without needing for manual patching.

File: plugins/woocommerce/includes/data-stores/class-wc-product-data-store-cpt.php (hunk 1 above)
Comment (Konamiman) [reply plugins/woocommerce/includes/data-stores/class-wc-product-data-store-cpt.php:371]: At the current point, with WordPress itself not being yet compatible with PHP 8.1, my bet is to keep a "reactive" approach and fix things as they appear. This also gives more time to the static analysis tools to become better.

File: plugins/woocommerce/tests/legacy/bootstrap.php (hunk 3 above)
Comment (Konamiman) [reply plugins/woocommerce/tests/legacy/bootstrap.php]: Ops, that's an oversight and indeed it was just a temporary change, thanks for catching it!

**Comment by masteradhoc** [comment]
any update on this @Konamiman. Would solve a lot php notices we got ;)

**Comment by botwoo** [comment]
:bar_chart: Test reports for this pull request have been published and are accessible through the following links:

- [REST API Test Report](https://woocommerce.github.io/woocommerce-test-reports/pr/31333/api/)
- E2E Test Report (TBC)

Latest commit referenced in the reports: `Formatting.` 0bc38d4152eeded4e26542ca3145c67ab0ab7974
This comment will automatically be updated with the latest referenced commit when you push new changes to this pull request.

---

_Visit the [WooCommerce Test Reports](https://woocommerce.github.io/woocommerce-test-reports) homepage to view all published reports. See the [FAQs](https://github.com/woocommerce/woocommerce-test-reports/wiki/FAQs) page if you're having problems accessing them._

**Review by peterfabian — COMMENTED** [review]
This has been a bit more involved than I hoped. 

Testing this in PHP 8.1 now with WP 6.0, I got a bunch of errors. After [cleaning up some WC Admin code](https://github.com/woocommerce/woocommerce/pull/33500) and some [code of ours](https://github.com/woocommerce/woocommerce/pull/33501) and applying a bunch of fixes to WP core while testing (adding several `#[\ReturnTypeWillChange]` statements to wp-includes/Requests/Cookie/Jar.php ([related issue](https://core.trac.wordpress.org/ticket/54672)) and wp-includes/Requests/Utility/CaseInsensitiveDictionary.php), I'm getting just 2 errors and 1 failure: 

```
There were 2 errors:

1) WC_Admin_Tests_API_Reports_Customers::test_user_creation
PHPUnit\Framework\Exception: PHP Deprecated:  trim(): Passing null to parameter #1 ($string) of type string is deprecated in /private/var/folders/rh/s6k2nr3s6qnc7bt1zz0glxwr0000gn/T/wordpress/wp-includes/pluggable.php on line 2481

2) WC_Admin_Tests_API_Reports_Customers::test_customer_user_profile_name
PHPUnit\Framework\Exception: PHP Deprecated:  trim(): Passing null to parameter #1 ($string) of type string is deprecated in /private/var/folders/rh/s6k2nr3s6qnc7bt1zz0glxwr0000gn/T/wordpress/wp-includes/pluggable.php on line 2481

--

There was 1 failure:

1) WC_Tests_Product_CSV_Importer::test_server_file
WP_Error Object (...) does not match expected type "string".

/Users/peter/Documents/GitHub/woocommerce/plugins/woocommerce/tests/legacy/unit-tests/importer/product.php:180

```

**Comment by peterfabian** [comment]
Just retested with PHP 8.0 and got just one failure: 

```
There was 1 failure:

1) WC_Tests_Product_CSV_Importer::test_server_file
WP_Error Object (...) does not match expected type "string".

/Users/peter/Documents/GitHub/woocommerce/plugins/woocommerce/tests/legacy/unit-tests/importer/product.php:180

--
```

So I think after this one failure gets fixed and the 2 PRs above are merged, this should be good to go.

**Comment by Konamiman** [comment]
> 1) WC_Tests_Product_CSV_Importer::test_server_file
WP_Error Object (...) does not match expected type "string".

I'm not getting this error, neither in `trunk` nor in the branch of this pull request, when testing in PHP 8.0. Maybe the error is caused by one of the other two pull requests?

**Comment by peterfabian** [comment]
So I retested this on a clean repo clone again to make sure my attempt to rebase won't interfere. I see no deprecation notices from PHP 8 or 8.1 anymore, so we can ignore those 2 PRs I opened, but the 1 failure is still there:

### PHP 8.0
```
PHPUnit 7.5.20.PHP-8-dev by Sebastian Bergmann and contributors.

Runtime:       PHP 8.0.20
Configuration: /Users/peter/Documents/GitHub/woocommerce/plugins/woocommerce/phpunit.xml
...
Time: 12.5 minutes, Memory: 201.50 MB

There was 1 failure:

1) WC_Tests_Product_CSV_Importer::test_server_file
WP_Error Object (...) does not match expected type "string".

/Users/peter/Documents/GitHub/woocommerce/plugins/woocommerce/tests/legacy/unit-tests/importer/product.php:180

--
```

### PHP 8.1
```
PHPUnit 7.5.20.PHP-8-dev by Sebastian Bergmann and contributors.

Runtime:       PHP 8.1.7
Configuration: /Users/peter/Documents/GitHub/woocommerce/plugins/woocommerce/phpunit.xml
...

Time: 11.06 minutes, Memory: 199.00 MB

There was 1 failure:

1) WC_Tests_Product_CSV_Importer::test_server_file
WP_Error Object (...) does not match expected type "string".

/Users/peter/Documents/GitHub/woocommerce/plugins/woocommerce/tests/legacy/unit-tests/importer/product.php:180

--
```

Will try to reinstall the testing suite to make sure my changes to WP aren't causing this, but I only added a couple of `#[\ReturnTypeWillChange]` flags, so that shouldn't cause a test error I think...

**Comment by peterfabian** [comment]
So the test that fails here will most likely fail also in PHP 7. It's not really related to the PHP 8 change, I think it was introduced as part of the changes in the downloadable files code ([over here](https://github.com/woocommerce/woocommerce/commit/654036850e92d4c68932eed21e78679b3b3afeb1)).

Either way, maybe your setup returns different paths for this test. For me, `test_server_file` results in failure because realpath beginning is different from ABSPATH:
```
file exist: 1
realpath: /private/var/folders/rh/s6k2nr3s6qnc7bt1zz0glxwr0000gn/T/wordpress/sample.csv
stripos:
abspath: /var/folders/rh/s6k2nr3s6qnc7bt1zz0glxwr0000gn/T/wordpress//
```

thus the check [over here](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/includes/admin/importers/class-wc-product-csv-importer-controller.php#L348-L349) fails.

**Review by peterfabian — DISMISSED** [review]
After a re-test, this works fine, so approving. Thanks!

**Review by peterfabian — APPROVED** [review]
👍
