### PR TITLE
Exclude block templates from showing up in product edit page

### LINKED ISSUE #30136: Hide template selector from Edit product pages in WP 5.8
Template editor will be automatically opted in for classic themes. This means that users can create custom templates from the block editor. Templates created that way become available for Products. We want to restrict this feature because it currently works differently in themes which explicitly support WooCommerce and themes that don't and because currently we don't have enough WooCommerce Blocks so product page templates can be created successfully.

**To reproduce**
Requisites:
* WP 5.8 or Gutenberg plugin enabled.
* A classic theme.

Steps:

1. Go to create a new page, in the sidebar, create a new template:<br>

2. Make some edits and click on Publish. Make sure the template you created is marked for publishing:<br>

3. Now, go to edit a product.
4. Notice there is a new panel in the sidebar that lets you change the template and select the one you just created.<br>

We would like the options in this panel not to be available when creating or editing products. So it would not possible to change the template of products.

@vedanshujain we would like to get this included in WC 5.5.0 given that it's the version that will need to support WP 5.8. I added it to the 5.5.0 milestone, but let me know if you have a different opinion. :slightly_smiling_face:

### PR DESCRIPTION
**Pull request by Aljullu**
This PR hooks into the [`theme_product_templates` filter](https://github.com/WordPress/wordpress-develop/blob/df724f991b1af4d87c8897af2922e0ba826371d5/src/wp-includes/class-wp-theme.php#L1325) in order to filter out block-based templates from appearing as template options in the product edit page. This way, templates created with the template editor included in WP 5.8 do not appear in the product edit page.

The rationale is that currently WooCommerce relies on PHP templating to format the product page so templates chosen from that selector have no effect in the frontend of classic themes.

In the future, we might enable the selector again for block-based themes. But that would require some investigation on how we can ensure only templates relevant to products show up in the selector (related issue in Gutenberg: https://github.com/WordPress/gutenberg/issues/31704).

Closes #30136.

### How to test the changes in this Pull Request:

Requisites:
* WP 5.8 or Gutenberg plugin enabled.
* A classic theme.

Steps:

1. Go to create a new page, in the sidebar, create a new template:<br>

2. Make some edits and click on Publish. Make sure the template you created is marked for publishing:<br>

3. Now, go to edit a product.
4. Verify there is no metabox in the sidebar that lets you change the template.<br>
<br>
<i>(this is what you shouldn't see)</i> :point_up_2: 

### Changelog entry

> Exclude block templates from showing up in product edit page

### CODE REVIEW

**Review by vedanshujain — DISMISSED** [review]
LGTM and working as expected. I will leave it for @nerrad to do a final review before merge.

File: includes/admin/class-wc-admin-meta-boxes.php [hunk 1]
```diff
@@ -222,6 +224,32 @@ public function save_meta_boxes( $post_id, $post ) {
...
+	public function remove_block_templates( $templates ) {
+		if ( count( $templates ) === 0 ) {
+			return $templates;
+		}
+
+		$theme              = wp_get_theme()->get_stylesheet();
+		$filtered_templates = array();
+
+		foreach ( $templates as $template_key => $template_name ) {
+			$gutenberg_template = gutenberg_get_block_template( $theme . '//' . $template_key );
```
Comment (nerrad) [inline includes/admin/class-wc-admin-meta-boxes.php:244]: Is this function WP version specific? If so, there should probably be a `function_exists` check before calling it (maybe in the initial check at the beginning of the function logic)?

**Review by nerrad — CHANGES_REQUESTED** [review]
I left a comment that should probably be addressed before merging (assuming the `gutenberg_get_block_template` function only appears in WP 5.8+).

Also, I didn't verify, but I'm assuming this filter is only executed on WC Admin product editor routes?

Other than the above, this looks great!

**Comment by frontdevde** [comment]
Tested as per testing instructions and it worked as expected for me. 

|before|after|
|-|-|
|Screenshot 2021-06-29 at 12 36 06|Screenshot 2021-06-29 at 12 36 41|

> there should probably be a function_exists check before calling it (maybe in the initial check at the beginning of the function logic)

As Albert is AFK at the moment, I added a small commit that hopefully addresses Darren's comment (who is AFK as well). As suggested, I added a check to test if the `gutenberg_get_block_template` function exists at the beginning of the function logic.

> Also, I didn't verify, but I'm assuming this filter is only executed on WC Admin product editor routes?

During my testing, that appeared to be the case, yes.

**Review by nerrad — APPROVED** [review]
Thanks for the changes @frontdevde - looks good to me 👍🏻
