### PR TITLE
Fix legacy access to array props (fees, taxes, coupon totals + taxes)

### LINKED ISSUE #16861: [3.2 Beta] Breaking changes to taxes and fees WC_Cart properties
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue

As of 3.2-beta-2, certain `WC_Cart` properties can no longer be modified as they could in 3.1.x and lower. So far I've found issues with these in my testing:

- `WC_Cart::$taxes`
- `WC_Cart::$fees`
- `WC_Cart::$shipping_taxes`

Getting and setting these properties directly works as expected, but their array values cannot be modified, i.e. `$cart->taxes['custom-rate'] = 100;`. This will throw a `Indirect modification of overloaded property WC_Cart::$taxes has no effect` notice and the modification will be lost. This is due to those properties now being overloaded.

## Steps to reproduce the issue

1. Hook into `woocommerce_after_calculate_totals`
2. Add an extra tax rate using `$cart->taxes['custom-rate'] = 100;`
3. See that nothing sticks, and the notice is logged

It's a fairly easy fix in custom code by just assigning `$cart->taxes` to a variable and setting it back after modification, but this is still a breaking change unfortunately.

### PR DESCRIPTION
**Pull request by mikejolley**
Closes #16861

### CODE REVIEW

File: includes/legacy/class-wc-legacy-cart.php [hunk 1]
```diff
@@ -70,62 +70,94 @@ public function __isset( $name ) {
...
-				return $this->get_cart_contents_count();
+				$value = $this->get_cart_contents_count();
+				break;
+			case 'coupons' :
+				$value = $this->get_coupons();
+				break;
+
+			// Arrays returned by reference to allow modification without notices. TODO: Remove in 4.0.
+			case 'taxes' :
+				wc_deprecated_function( 'WC_Cart->taxes', '3.2', sprintf( 'Use getters (%s) and setters (%s)', 'WC_Cart::get_cart_contents_taxes()', 'WC_Cart::set_cart_contents_taxes()' ) );
```
Comment (ChaseWiseman) [inline includes/legacy/class-wc-legacy-cart.php]: Should probably ditch the `Use ` here which ends up duplicated in the final notice string and is a bit off in the AJAX context, i.e. "Replace with Use getters..." or
