### PR TITLE
Move add_filter calls to block initialize(). Closes #61012.

### LINKED ISSUE #61012: ProductImageGallery block woocommerce_single_product_zoom_enabled filters not true inside blocks
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

I noticed that the Product Image Gallery block enqueues Photoswipe and [filters ](https://github.com/woocommerce/woocommerce/blob/e214e8a6eea24bff0dc2fb5be896bb8575f4e646/plugins/woocommerce/src/Blocks/BlockTypes/ProductImageGallery.php#L68)`woocommerce_single_product_zoom_enabled`[ to be ](https://github.com/woocommerce/woocommerce/blob/e214e8a6eea24bff0dc2fb5be896bb8575f4e646/plugins/woocommerce/src/Blocks/BlockTypes/ProductImageGallery.php#L68)`true`

### Expected behavior

Inside the render callback for the product gallery block and any other  block where the product gallery is present, that filter should return `true`

### Actual behavior

However, if adding content inside a block (such as custom product type displaying legacy content in the add to cart form block) this filter is not attached as the block is rendered before `wp_enqueue_scripts` has had a chance to run.

### Steps to reproduce

A mve would be something like the following:
```
add_filter( 'render_block_woocommerce/add-to-cart-form', function( $content ) {
	$test = apply_filters( 'woocommerce_single_product_photoswipe_enabled', get_theme_support( 'wc-product-gallery-lightbox' ) ) ? 'photoswipe enabled' : 'photoswipe disabled';
	return '<p>' . $test . '</p>' . $content;
} );
```
When viewing a product with add to cart with options block (I think not the beta one, but that might have the same problem) the value of `woocommerce_single_product_photoswipe_enabled` is actually `false` 

### WordPress Environment

n/a

### Isolating the problem

- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by helgatheviking**
### Changes proposed in this Pull Request:

Move the legacy filters to the block's `initialize` method so that they actually are fired during block render. 

Closes #61012.

### How to test the changes in this Pull Request:

Use the MVE snippet from #61012

```
add_filter( 'render_block_woocommerce/add-to-cart-form', function( $content ) {
	$test = apply_filters( 'woocommerce_single_product_photoswipe_enabled', get_theme_support( 'wc-product-gallery-lightbox' ) ) ? 'photoswipe enabled' : 'photoswipe disabled';
	return '<p>' . $test . '</p>' . $content;
} );
```

Without PR you should see `photoswipe disabled` and with PR you should see `photoswipe enabled` just prior to the single product's add to cart form block.

### CODE REVIEW

File: plugins/woocommerce/src/Blocks/BlockTypes/ProductImageGallery.php [hunk 1]
```diff
@@ -14,6 +14,25 @@ class ProductImageGallery extends AbstractBlock {
...
+		parent::initialize();
+		add_action(
+			'wp_footer',
+			function () {
+				wc_get_template( 'single-product/photoswipe.php' );
+			}
+		);
+		add_filter( 'woocommerce_single_product_zoom_enabled', '__return_true' );
+		add_filter( 'woocommerce_single_product_photoswipe_enabled', '__return_true' );
+		add_filter( 'woocommerce_single_product_flexslider_enabled', '__return_true' );
```
Comment (kmanijak) [inline plugins/woocommerce/src/Blocks/BlockTypes/ProductImageGallery.php]: That's not a good place either since it block doesn't even have to rendered and filters would return true:

image

I believe they should be moved to `render` function after [initial checks if block can be rendered here](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/src/Blocks/BlockTypes/ProductImageGallery.php#L96)

With Product Image Gallery |  Without Product Image Gallery
-- | --
image | image

Do you see any downsides of moving it there?

**Review by kmanijak — CHANGES_REQUESTED** [review]
Hi @helgatheviking, thanks for contribution and fixing this issue!

Current place for filters is not good either as it returns false positives but I suggested an alternative 🙌

File: plugins/woocommerce/src/Blocks/BlockTypes/ProductImageGallery.php (hunk 1 above)
Comment (helgatheviking) [reply plugins/woocommerce/src/Blocks/BlockTypes/ProductImageGallery.php]: @kmanijak Hi Karol! :wave Specifically I am trying to piggy back in Mix and Match on whether photoswipe is enabled. your suggestion looks like it should work. I'll commit it.

File: plugins/woocommerce/src/Blocks/BlockTypes/ProductImageGallery.php [hunk 2]
```diff
@@ -14,6 +14,22 @@ class ProductImageGallery extends AbstractBlock {
...
+	 * - Register the block with WordPress.
+	 */
+	protected function initialize() {
+		parent::initialize();
+		add_action(
+			'wp_footer',
+			function () {
+				wc_get_template( 'single-product/photoswipe.php' );
+			}
+		);
```
Comment (kmanijak) [inline plugins/woocommerce/src/Blocks/BlockTypes/ProductImageGallery.php]: I think this can be moved to the previous place.

**Review by kmanijak — COMMENTED** [review]
It tests well now for me but let's just make a cleanup and remove unnecessary changes with action moved to `initialize` 🙌 

Once done, I'm happy to approve!

File: plugins/woocommerce/src/Blocks/BlockTypes/ProductImageGallery.php (hunk 2 above)
Comment (helgatheviking) [reply plugins/woocommerce/src/Blocks/BlockTypes/ProductImageGallery.php]: You mean to the render callback? So we wouldn't need `initialize()` at all anymore

Comment (kmanijak) [reply plugins/woocommerce/src/Blocks/BlockTypes/ProductImageGallery.php]: I meant `enqueue_legacy_assets` so we have all the enqueueing in a single function (as it was on `trunk`).

> So we wouldn't need initialize() at all anymore

Yass!

**Review by kmanijak — APPROVED** [review]
Thanks for addressing my feedback and for fixing the issue in the first place! 🙌

**Comment by kmanijak** [comment]
Setting the milestone to 10.2, as we would like to backport it to a patch release.

Incorrect filter placement causes issues with Product Image Gallery block image sizes https://github.com/woocommerce/woocommerce/issues/61138 and this PR fixes the issue.
