### PR TITLE
iAPI powered MiniCart - Fix variable product actions

### LINKED ISSUE #60335: Interactivity API powered Mini Cart - Incorrect stock count and errors when changing product quantities
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Hi woocommerce team,

I was testing the new **Interactivity API powered Mini Cart** feature when I ran into a few issues.

1- One of the variables has 2 stocks. First I add one to the cart, then in the Mini cart I try to increase its number, but it has many problems as we can see in the gif below.

Image

2- As I mentioned in the previous case, a variable has 2 stock. When we add one of them to the Cart, the mini cart still shows [2 left in stock](https://prnt.sc/WpxWEXfxCBDC). Wouldn't it make more sense to show 1?

3- If we change the number of products quickly, we will get a bug.

Image

### Expected behavior

-

### Actual behavior

-

### Steps to reproduce

-

### WordPress Environment

<details>

<summary>WordPress Environment</summary>

<details><summary>System Status Report</summary>

```
### WordPress Environment ###

WordPress address (URL): [Redacted]
Site address (URL): [Redacted]
WC Version: 10.1.0
Legacy REST API Package Version: The Legacy REST API plugin is not installed on this site.
Action Scheduler Version: ✔ 3.9.3
Log Directory Writable: ✔
WP Version: 6.8.2
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
Server Architecture: Linux Linux Linux
PHP Version: 8.4.6
PHP Post Max Size: 64 MB
PHP Time Limit: 300
PHP Max Input Vars: 1000
cURL Version: 8.12.1
OpenSSL/3.2.2

SUHOSIN Installed: –
MySQL Version: 10.6.19-MariaDB
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ❌ wp_remote_post() failed. Contact your hosting provider. 403
Remote Get: ✔

### Database ###

[REDACTED]

### Post Type Counts ###

acf-field: 1
acf-field-group: 1
attachment: 134
bricks_fonts: 1
bricks_template: 36
faq: 9
nav_menu_item: 5
page: 26
post: 9
product: 20
product_variation: 4
revision: 2504
shop_coupon: 1
shop_order_placehold: 18
woo_email: 12
wp_font_face: 36
wp_font_family: 12
wp_global_styles: 2
wp_navigation: 1
wp_template: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (3) ###

JetEngine: by ElementorFa – 3.7.3
WooCommerce: by Automattic – 10.1.0
WP-Parsidate: by WP-Parsi Team – 5.1.7

### Inactive Plugins (1) ###

Polylang: by WP SYNTEX – 3.7.3

### Dropin Plugins () ###

advanced-cache.php: advanced-cache.php

### Settings ###

Legacy API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 0
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –
Enabled Features: analytics
marketplace
order_attribution
hpos_fts_indexes
hpos_datastore_caching
email_improvements
blueprint
point_of_sale
experimental-iapi-mini-cart
custom_order_tables
cost_of_goods_sold


### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 177 KB

### WC Pages ###

Shop base: #10 - /shop/
Cart: #2649 - /cart/ -  Contains the woocommerce/cart block
Checkout: #12 - /checkout/ -  Contains the woocommerce/checkout block
My account: #13 - /my-account/ -  Contains the [woocommerce_my_account] shortcode
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty-Five
Version: 1.3
Author URL: https://wordpress.org
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
Theme type: Block theme
WooCommerce Support: ❌ Not declared

### Templates ###

Overrides: /home2/gerozair/domains/domain.com/public_html/wp-content/plugins/woocommerce/templates/block-notices/error.php
/home2/gerozair/domains/domain.com/public_html/wp-content/plugins/woocommerce/templates/block-notices/notice.php
/home2/gerozair/domains/domain.com/public_html/wp-content/plugins/woocommerce/templates/block-notices/success.php


### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
onboarding
onboarding-tasks
pattern-toolkit-full-composability
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
printful
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page
launch-your-store
add-to-cart-with-options-stepper-layout

Disabled Features: product-data-views
experimental-blocks
experimental-iapi-mini-cart
experimental-iapi-runtime
coming-soon-newsletter-template
minified-js
product-pre-publish-modal
settings
async-product-editor-category-field
product-editor-template-system
use-wp-horizon
experimental-wc-rest-api

Daily Cron: ✔ Next scheduled: 2025-08-04 14:58:33 +03:30
Options: ✔
Notes: 53
Onboarding: skipped

### Action Scheduler ###

Canceled: 2
Oldest: 2025-08-02 19:18:37 +0000
Newest: 2025-08-10 18:05:47 +0000

Complete: 254
Oldest: 2025-07-12 21:41:38 +0000
Newest: 2025-08-12 18:28:22 +0000

Failed: 15
Oldest: 2025-02-10 15:03:57 +0000
Newest: 2025-07-29 21:51:29 +0000

Pending: 3
Oldest: 2025-08-12 20:07:02 +0000
Newest: 2025-08-13 17:40:33 +0000


### Status report information ###

Generated at: 2025-08-12 21:59:29 +03:30
```
</details>

</details>

### Isolating the problem

- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by SantosGuillamot**
### Changes proposed in this Pull Request:

In [this pull request](https://github.com/woocommerce/woocommerce/pull/59921), it was changed how the `addCartItem` works, so I've adapted the minicart actions to pass the `variation` when relevant.

Closes #60335 .

(For Bug Fixes) Bug introduced in PR #59921 .

### Screenshots or screen recordings:

Before

https://github.com/user-attachments/assets/c038fffb-78d9-4757-b023-f3d15123d1f1 

After

https://github.com/user-attachments/assets/c90a3470-e113-4ba3-8d69-97c6e68dce52

### How to test the changes in this Pull Request:

Follow the testing instructions in the original issue: https://github.com/woocommerce/woocommerce/issues/60335

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message Fix iAPI minicart variable products.

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce/client/blocks/assets/js/blocks/mini-cart/iapi-frontend.ts [hunk 1]
```diff
@@ -636,9 +636,16 @@ const { state: cartItemState } = store(
 			},
 
 			*changeQuantity(): Generator< unknown, void > {
+				const variation = cartItemState.cartItem.variation.map(
+					( { raw_attribute, ...rest } ) => ( {
+						...rest,
+						attribute: raw_attribute,
+					} )
+				);
```
Comment (SantosGuillamot) [inline plugins/woocommerce/client/blocks/assets/js/blocks/mini-cart/iapi-frontend.ts]: We need to override the `attribute` property because the response from the API has a different format than the object used in `addCartItem`.

The `variation` of the REST API has this format:

```json
{
    "raw_attribute": "attribute_pa_color",
	"attribute": "Color",
	"value": "Red"
}
```

While the `variation` in the `addCartItem` has this one:

```json
{
	"attribute": "attribute_pa_color",
	"value": "Red"
}
```

 I briefly discussed it with @Aljullu, it could make sense to unify both and change `attribute` to `selected_attribute`. Additionally, the descriptive attribute name ("Color"), is not used right now, but it could be used in other blocks like Cart and Checkout.

Anyways, it can be handled in another PR.

Comment (luisherranz) [reply plugins/woocommerce/client/blocks/assets/js/blocks/mini-cart/iapi-frontend.ts]: We should create an issue and remember to do it before marking the stores as public so that a change like this is not a breaking change.

**Review by luisherranz — COMMENTED** [review]
After reviewing this PR, I don't quite understand what the benefit is of not making this change in this PR.

- https://github.com/woocommerce/woocommerce/pull/60497#discussion_r2287844042

~Wouldn't the problem be solved in a simpler way?~

EDIT: Neverming, Mario has told me that there are many places in the code that would need to be changed, so it doesn't make sense to do it in this PR.

**Review by Aljullu — APPROVED** [review]
Code changes look good to me, and the original issue seems to be fixed. Thanks for investigating and fixing this, @SantosGuillamot! :raised_hands: 

https://github.com/user-attachments/assets/673fc44f-5d83-45b9-9753-b9ca173ce02a


<details>
<summary>Testing environment</summary>

* WordPress 6.8.2 local dev environment
* Plugins: WooCommerce Beta Tester
* Theme: TT5
* Store creation: June 2025
* Store size: small
</details>
