### PR TITLE
[Shipping] Unformat Shipping Method numeric values before sending data

### LINKED ISSUE #46558: Re-saving the "Free shipping" method breaks the minimum amount if , is decimal separator
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Related to https://github.com/woocommerce/woocommerce/issues/46173, but this one is affecting the Free shipping method. If the shop uses `,` as the decimal separator, the minimum amount will break upon resaving.

### Expected behavior

Re-saving the shipping method should have no impact on the minimum amount if we don't edit it.

### Actual behavior

The minimum amount will be broken if we re-save the shipping method, even if we change nothing.

### Steps to reproduce

1. In Settings > General, set the decimal separator to `,`
2. Create a free shipping method with a minimum amount (don't use the "Rest of the world" zone)
3. Test the cart with a product below that minimum, confirm free shipping isn't shown
4. Edit the free shipping method, click save
5. Test the cart again and notice that free shipping is now showing

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://delightfully-anonymous-toad.jurassic.ninja
Site address (URL): https://delightfully-anonymous-toad.jurassic.ninja
WC Version: 8.7.0
REST API Version: ✔ 8.7.0
Action Scheduler Version: ✔ 3.7.2
Log Directory Writable: ✔
WP Version: 6.5.2
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 8.1.27
PHP Post Max Size: 2 GB
PHP Time Limit: 1200
PHP Max Input Vars: 6144
cURL Version: 8.4.0
OpenSSL/1.1.1w

SUHOSIN Installed: –
MySQL Version: 10.6.15-MariaDB-log
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.7.0
WC Database Prefix: wp_
Total Database Size: 2.88MB
Database Data Size: 1.21MB
Database Index Size: 1.67MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 0.13MB + Index: 0.03MB + Engine InnoDB
wp_postmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_posts: Data: 0.05MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 1
page: 7
post: 2
product: 1
shop_order_placehold: 2
wp_navigation: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (2) ###

Akismet Anti-spam: Spam Protection: by Automattic - Anti-spam Team – 5.3.2
WooCommerce: by Automattic – 8.7.0

### Dropin Plugins () ###

advanced-cache.php: advanced-cache.php
object-cache.php: Memcached

### Must Use Plugins (1) ###

load.php: by  –

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: left
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to Woo.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 13 B

### WC Pages ###

Shop base: #5 - /shop/
Cart: #6 - /cart/
Checkout: #7 - /checkout/
My account: #8 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty-Four
Version: 1.1
Author URL: https://wordpress.org
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ❌ Not declared

### Templates ###

Overrides: /srv/htdocs/wp-content/plugins/woocommerce/templates/block-notices/error.php
/srv/htdocs/wp-content/plugins/woocommerce/templates/block-notices/notice.php
/srv/htdocs/wp-content/plugins/woocommerce/templates/block-notices/success.php

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
product-virtual-downloadable
product-external-affiliate
product-grouped
product-linked
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: customize-store
minified-js
new-product-management-experience
product-pre-publish-modal
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2024-04-14 10:37:59 +00:00
Options: ✔
Notes: 62
Onboarding: -

### Action Scheduler ###

Complete: 14
Oldest: 2024-04-13 10:39:57 +0000
Newest: 2024-04-13 10:56:23 +0000

Failed: 1
Oldest: 2024-04-13 10:39:57 +0000
Newest: 2024-04-13 10:39:57 +0000

Pending: 1
Oldest: 2024-04-14 10:39:57 +0000
Newest: 2024-04-14 10:39:57 +0000

### Status report information ###

Generated at: 2024-04-13 11:09:39 +00:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### LINKED ISSUE #47795: Flat rate shipping price incorrectly is set to 0.00 when shipping is >= 1,000.00
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Editing a flat rate shipping zone leads to calculation of a free flatrate shipping zone in checkout, when "," is the thousands separator and "." is the decimal point, or vice versa. This is not the same shipping cost bug described in previous issues I found regarding the decimal point.

### Expected behavior

Opening the flatrate edit and clicking on save should not break the shipping price calculation on the checkout page.

### Actual behavior

Opening the flatrate edit and clicking on save results in a calculated shipping price of 0 on the checkout page, given the above conditions.

### Steps to reproduce

This happens after opening the flat rate edit, and saving it, the decimal separator is a ".", and when the price contains a ",":

1. Go to WooCommerce->Settings->Shipping->(any zone)
2. Set up shipping method: with type flat rate
3. Enter 1000 in the cost field
4. Click "save"
5. Go to checkout, use the shipping zone, it should be showing flat rate with cost 1000: 
grafik
6. Click "edit" for the method, the form should now contain a "thousands separator"
grafik
7. Click "save" again
8. Use the shipping zone in Checkout, it now results in a flat rate with no shipping cost (this is the error) grafik

### WordPress Environment

`
### WordPress Environment ###

`
### WordPress Environment ###

WordPress address (URL): https://...
Site address (URL): https://...
WC Version: 8.8.3
REST API Version: ✔ 8.8.3
Action Scheduler Version: ✔ 3.7.4
Log Directory Writable: ✔
WP Version: 6.5.3
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: –
WP Cron: ✔
Language: en_GB
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 8.2.19
PHP Post Max Size: 2 GB
PHP Time Limit: 300
PHP Max Input Vars: 5000
cURL Version: 7.61.1
OpenSSL/1.1.1k

SUHOSIN Installed: –
MySQL Version: 8.0.36-cll-lve
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.8.3
WC Database Prefix: ioBaS_
Total Database Size: 42.48MB
Database Data Size: 28.40MB
Database Index Size: 14.08MB
ioBaS_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
ioBaS_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
ioBaS_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
ioBaS_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
ioBaS_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
ioBaS_woocommerce_order_itemmeta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
ioBaS_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
ioBaS_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
ioBaS_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
ioBaS_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
ioBaS_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
ioBaS_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
ioBaS_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
ioBaS_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
ioBaS_actionscheduler_actions: Data: 8.52MB + Index: 5.16MB + Engine InnoDB
ioBaS_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
ioBaS_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
ioBaS_actionscheduler_logs: Data: 6.52MB + Index: 3.03MB + Engine InnoDB
ioBaS_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
ioBaS_comments: Data: 0.06MB + Index: 0.09MB + Engine InnoDB
ioBaS_hkdev_mm_access_keys: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
ioBaS_hkdev_mm_unrestricted_ips: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
ioBaS_jetpack_sync_queue: Data: 0.05MB + Index: 0.06MB + Engine InnoDB
ioBaS_jetpack_waf_blocklog: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
ioBaS_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
ioBaS_options: Data: 6.09MB + Index: 0.13MB + Engine InnoDB
ioBaS_postmeta: Data: 1.52MB + Index: 2.00MB + Engine InnoDB
ioBaS_posts: Data: 1.52MB + Index: 0.20MB + Engine InnoDB
ioBaS_snippets: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
ioBaS_term_relationships: Data: 0.16MB + Index: 0.09MB + Engine InnoDB
ioBaS_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
ioBaS_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
ioBaS_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
ioBaS_user_registration_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
ioBaS_usermeta: Data: 1.52MB + Index: 0.16MB + Engine InnoDB
ioBaS_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
ioBaS_wc_admin_note_actions: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
ioBaS_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
ioBaS_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
ioBaS_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
ioBaS_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
ioBaS_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
ioBaS_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
ioBaS_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
ioBaS_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
ioBaS_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
ioBaS_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
ioBaS_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
ioBaS_wc_orders_meta: Data: 0.05MB + Index: 0.09MB + Engine InnoDB
ioBaS_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
ioBaS_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
ioBaS_wc_product_meta_lookup: Data: 0.14MB + Index: 0.30MB + Engine InnoDB
ioBaS_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
ioBaS_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
ioBaS_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
ioBaS_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
ioBaS_wcpdf_invoice_number: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
ioBaS_wcpdf_packing_slip_number: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
ioBaS_wt_iew_action_history: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
ioBaS_wt_iew_mapping_template: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
ioBaS_xoo_wl_list: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
ioBaS_xoo_wl_list_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
ioBaS_yoast_indexable: Data: 0.28MB + Index: 0.36MB + Engine InnoDB
ioBaS_yoast_indexable_hierarchy: Data: 0.08MB + Index: 0.08MB + Engine InnoDB
ioBaS_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
ioBaS_yoast_primary_term: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
ioBaS_yoast_seo_links: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
ioBaS_zbs_admlog: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
ioBaS_zbs_aka: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
ioBaS_zbs_companies: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
ioBaS_zbs_contacts: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
ioBaS_zbs_customfields: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
ioBaS_zbs_dbmigration_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
ioBaS_zbs_dbmigration_posts: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
ioBaS_zbs_event_reminders: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
ioBaS_zbs_events: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
ioBaS_zbs_externalsources: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
ioBaS_zbs_forms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
ioBaS_zbs_invoices: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
ioBaS_zbs_lineitems: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
ioBaS_zbs_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
ioBaS_zbs_meta: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
ioBaS_zbs_notifications: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
ioBaS_zbs_object_links: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
ioBaS_zbs_quotes: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
ioBaS_zbs_quotes_templates: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
ioBaS_zbs_security_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
ioBaS_zbs_segments: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
ioBaS_zbs_segments_conditions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
ioBaS_zbs_settings: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
ioBaS_zbs_sys_cronmanagerlogs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
ioBaS_zbs_sys_email: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
ioBaS_zbs_sys_email_hist: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
ioBaS_zbs_tags: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
ioBaS_zbs_tags_links: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
ioBaS_zbs_tax_table: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
ioBaS_zbs_temphash: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
ioBaS_zbs_tracking: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
ioBaS_zbs_transactions: Data: 0.02MB + Index: 0.14MB + Engine InnoDB
ioBaS_zbs_workflows: Data: 0.02MB + Index: 0.06MB + Engine InnoDB

### Post Type Counts ###

acf-field: 4
acf-field-group: 2
attachment: 23
cc_restriction: 1
cwginstocknotifier: 1
nav_menu_item: 2
order_status: 3
page: 11
post: 2
product: 1149
revision: 48
shop_order_placehold: 21
user_registration: 1
wp_global_styles: 1
wp_navigation: 1
wp_template: 2
wp_template_part: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 8.8.3 (update to version 8.9.1 is available)

### Inactive Plugins (14) ###

Advanced Custom Fields: by WP Engine – 6.2.9
Change Storefront Footer Copyright Text: by QuadLayers – 2.1.7
Code Snippets: by Code Snippets Pro – 3.6.4
Custom Order Status Manager for WooCommerce: by Bright Plugins – 1.1.3.2
Email Verification for WooCommerce Pro: by WPFactory – 2.6.7
Flexible Checkout Fields: by WP Desk – 4.1.5
Font Awesome: by Font Awesome – 4.4.0
Jetpack: by Automattic – 13.4.2
Jetpack CRM: by Automattic - Jetpack CRM team – 6.4.2
Members: by MemberPress – 3.2.9
Order Export & Order Import for WooCommerce: by WebToffee – 2.5.2
Waitlist woocommerce( Back in stock notifier ): by  – 2.5.3
WooPayments: by Automattic – 7.6.0
WP Menu Cart: by WP Overnight – 2.14.3

### Dropin Plugins () ###

maintenance.php: maintenance.php

### Must Use Plugins (1) ###

CloudLinux SmartAdvice: by CloudLinux – 0.6-22

### Settings ###

API Enabled: –
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 94 KB

### WC Pages ###

Shop base: #6 - /shop/
Basket: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /
Terms and conditions: #2537 - /terms-and-conditions-of-supply/

### Theme ###

Name: Storefront
Version: 4.5.5 (update to version 4.6.0 is available)
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build
personally we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
product-virtual-downloadable
product-external-affiliate
product-grouped
product-linked
product-pre-publish-modal
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
product-custom-fields
settings
async-product-editor-category-field
launch-your-store

Daily Cron: ✔ Next scheduled: 2024-05-24 11:05:19 +00:00
Options: ✔
Notes: 87
Onboarding: completed

### Action Scheduler ###

Complete: 3,605
Oldest: 2024-04-23 10:26:20 +0000
Newest: 2024-05-24 09:14:06 +0000

Failed: 15,865
Oldest: 2023-10-31 09:51:12 +0000
Newest: 2024-05-13 12:50:16 +0000

Pending: 2
Oldest: 2024-05-24 19:55:05 +0000
Newest: 2024-05-25 07:55:05 +0000

### Status report information ###

Generated at: 2024-05-24 09:14:09 +00:00
`

### Isolating the problem

- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

### LINKED ISSUE #53315: [Bug] Store ignores minimum cart total free shipping setting when cart total > 100
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Shipping cost switches back to €5 when the cart total exceeds €100, despite the configuration of free shipping for orders over €65.
[Bug reported on the forum](https://wordpress.org/support/topic/free-shipping-not-working-21/)

### Expected behavior

The free shipping option should still be available for orders over €65.

### Actual behavior

We identified that this might be related to decimals used in the settings for the shipping options. This was supposed to be fixed in [WooCommerce 9.0.2 – Dot release to fix shipping calculation issues](https://developer.woocommerce.com/2024/06/21/developer-advisory-flat-rate-shipping-separators-in-woocommerce-9-0-1/), but the issue is present for a store with 9.4.2.

When saving `65` as a minimum for free shipping an saving, `65,00` is stored and the bug is present.
When saving `65.00` the value is kept and the bug does not happen.

### Steps to reproduce

- Go to WooCommerce → Settings → Shipping → Shipping Zones.
- Select the Germany shipping zone.
- Verify that it contains the following shipping methods:
  - DHL: Flat rate of €5.
  - Free Shipping: Set to activate when the order total exceeds €65.

Add 1 product < €65 -> see flat rate
Add more products until you have a €65 <  sum < €100 -> see free shipping
Add more products until sum > €100 -> see flat rate

### WordPress Environment

WordPress 9.4.2

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

### LINKED ISSUE #53876: Problems with free shipping
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

We have free shipping above 200 pln. In settings we can see it correct. But if starts shopping for less than 100 pln then comes free shipping too. we cannot find this fail. 
At this moment we can see that free shipping works from 0-100zł , then 100-200 pln is not free and the above 200 pln again free. It should be only above 200 pln.Image

### Expected behavior

free shipping only above 200 pln

### Actual behavior

We have free shipping above 200 pln. In settings we can see it correct. But if starts shopping for less than 100 pln then comes free shipping too. we cannot find this fail. 
At this moment we can see that free shipping works from 0-100zł , then 100-200 pln is not free and the above 200 pln again free. It should be only above 200 pln.

Image

### Steps to reproduce

We have free shipping above 200 pln. In settings we can see it correct. But if starts shopping for less than 100 pln then comes free shipping too. we cannot find this fail. 
At this moment we can see that free shipping works from 0-100zł , then 100-200 pln is not free and the above 200 pln again free. It should be only above 200 pln.

### WordPress Environment

[SystemStatusReport_bajewski.pl_2024-12-19T10-34-02.txt](https://github.com/user-attachments/files/18196414/SystemStatusReport_bajewski.pl_2024-12-19T10-34-02.txt)

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by psealock**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes https://github.com/woocommerce/woocommerce/issues/53876
Closes https://github.com/woocommerce/woocommerce/issues/53315
Closes https://github.com/woocommerce/woocommerce/issues/47795

When Shipping Method values were edited in the the Shipping Method Modal, numbers with thousandth and decimal separators were sent as human readable strings with separators. This caused errors on the server and values were getting saved as `0.00`. This PR makes sure the formatting separators are removed and the value sent to the server is a valid number.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Go to WooCommerce->Settings->Shipping->(any zone that you are in)
2. Set up shipping method: with type flat rate
3. Enter 1000 in the cost field and click "save"
4. Once again, edit the shipping method by clicking "Edit" and saving. This step is important as this is where the error occurs on trunk.
5. Add a test product with price, enable a payment method like Cash on delivery
6. On the shopper side, add the product to your cart and note the shipping method and its price are accurately shown.

image

7. Test a formula as the value by placing `1000 * [qty]` as the value and save. In the cart, refresh the page and increase the product quantity in your cart. The flat rate shipping should update accordingly.
8. Repeat this with different thousand and decimal separators at WooCommerce > Settings > General > Thousand separator | Decimal separator.
9. Try once again with free shipping and a minimum order amount.

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

Unformat Shipping Method numeric values before persisting data to the server.

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

**Review by rjchow — DISMISSED** [review]
This doesn't fix the case where the merchant enters the comma and decimal point intentionally - e.g a min order amount of "1,000.00" will not be correctly applied.

I think let's fix this properly by both ensuring that the frontend only sends a valid numeric value without thousands separator, currency symbol, and a period for indicating decimal points, as well as ensuring that the backend properly fails when an invalid value according to those rules is sent. Configuration that includes formulae should be separately handled, ideally in another endpoint. This should do its own validation, since there's really no overlap. 

A more risky follow up would be to also correctly fail when an invalid value is encountered when evaluating shipping costs. This is risky because it will break existing non-compliant store setups. A way to make this less risky is to only flag it in a notice in WC Admin if it is detected on init.

Edit: for expediency we can just mitigate it in frontend first, which just needs an extension of this PR to also handle intentional entries. (I haven't looked into why it doesn't, but just entering a minimum free shipping criteria of "1,000.00" in the US currency settings gives away free shipping on a cart value of $10)

Edit 2: A small UI tweak to make validation easier would be to split the field into integer and float fields with the separator as a fixed part of the UI

**Comment by rjchow** [comment]
> This doesn't fix the case where the merchant enters the comma and decimal point intentionally - e.g a min order amount of "1,000.00" will not be correctly applied.

More testing indicates that this was an inaccurate finding, it seems that the unformatting is not being triggered on the 'Rest of world' zone rather than the unformatting not applying at all for min order amount of "1,000.00"

File: plugins/woocommerce/client/legacy/js/admin/wc-shipping-zone-methods.js [hunk 1]
```diff
@@ -351,6 +351,44 @@
...
+						
+						if ( ! formattedValue ) {
+							return;
+						}
+
+						if ( 'number' === typeof formattedValue ) {
+							return;
+						}
+
+						// Brackets signal a formula. Avoid unformatting these values.
```
Comment (waclawjacek) [inline plugins/woocommerce/client/legacy/js/admin/wc-shipping-zone-methods.js]: Could we maybe have some logic to sanitize the string, split it into components (number/not number), and then run the sanitization on all numbers instead of not doing anything at all when there's a shortcode?

**Review by waclawjacek — CHANGES_REQUESTED** [review]
Thanks for this PR! 🙌 

I did some testing and found behavior that makes me think that we should have some more/different logic to handle the formatting.

I see that while WooCommerce doesn't allow using completely made-up values for the shipping cost (tested: `  foobar `), there's a lot you can get away with.

For example, I got the following results when testing with a shipping cost input of `1 000,00.00`:

<table>
<tr>
<th>Thousands separator</th>
<th>Decimal separator</th>
<th>What was sent in the HTTP update request (on this branch)</th>
</tr>
<tr><td><kbd>,</kbd></td><td><kbd>.</kbd></td><td>1 00000.00</td></tr>
<tr><td><kbd>,</kbd></td><td><kbd>&nbsp;</kbd></td><td>1.00000.00</td></tr>
<tr><td><kbd>&nbsp;</kbd></td><td><kbd>,</kbd></td><td>1000.00.00</td></tr>
<tr><td><kbd>&nbsp;</kbd></td><td><kbd>.</kbd></td><td>1000,00.00</td></tr>
</table>

I am also not super confident about having one behavior happen when a shortcode is not present (sanitize), and another - when it is present (no sanitization). I see the value is covering many cases that don't use a shortcode but it'd be great to have a fix for all cases.

Additionally, I also came across the same issue that @rjchow reported - the sanitization doesn't trigger for the "Rest of the world" shipping zone. It seems to be caused by `window.wc.ShippingCurrencyContext` not being defined in that zone.

I think an ideal solution for me (which I realize might not be viable to implement but just sharing in case it might be) would be if WooCommerce ran validation upon every attempt to store a number that has characters outside of the expected separators (looking only at the current settings, not all possible separators for all locales), and then persisted the value in the database as an integer instead of a value with separators (e.g. if the input is `5.50`, we could store `550`). This would also allow changing the separator settings without affecting the values (although this is probably a super edge case).

**Comment by rjchow** [comment]
Hey @waclawjacek ! Thanks for the review - there's one bit to clarify 
> It seems to be caused by window.wc.ShippingCurrencyContext not being defined in that zone.

I think rather than that, it's because it has [its own saving routine](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/client/legacy/js/admin/wc-shipping-zone-methods.js#L36) which originally ran the same code, but was not kept in sync when more logic was added to `onConfigureShippingMethod`.

For the purpose of this PR I think I would be satisfied if we just extract the logic and call it from both of these functions so that this divergence doesn't happen again. Additionally some unit tests around the new `unformatShippingMethodNumericValues()` method would be prudent

File: plugins/woocommerce/client/legacy/js/admin/wc-shipping-zone-methods.js [hunk 2]
```diff
@@ -351,6 +351,44 @@
...
+					];
+
+					numericValuesFields.forEach( function( field ) {
+						const formattedValue = data[ field ];
+						
+						if ( ! formattedValue ) {
+							return;
+						}
+
+						if ( 'number' === typeof formattedValue ) {
```
Comment (rjchow) [inline plugins/woocommerce/client/legacy/js/admin/wc-shipping-zone-methods.js]: I think we should use `Number.isFinite()` to test instead - `NaN` also evalutes to typeof 'number'

**Comment by waclawjacek** [comment]
I have prepared an alternative solution that only accepts numbers using only the thousand and decimal separators defined in settings, then saves them as numbers passing the `is_numeric()` check in the database.

Then for display, it converts them back to a format using separators defined in settings.

The PR is here: https://github.com/woocommerce/woocommerce/pull/54542

**Comment by psealock** [comment]
>I think let's fix this properly by both ensuring that the frontend only sends a valid numeric value without thousands separator, currency symbol, and a period for indicating decimal points, as well as ensuring that the backend properly fails when an invalid value according to those rules is sent. Configuration that includes formulae should be separately handled, ideally in another endpoint. This should do its own validation, since there's really no overlap.

This seems like the proper solution. While making sure the client isn't sending improper strings as numbers solves the immediate concern, making sure the backend rejects invalid values future proofs the situation. @waclawjacek, what do you think? Seems to me like we should merge both approaches.

**Comment by psealock** [comment]
>I think rather than that, it's because it has [its own saving routine](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/client/legacy/js/admin/wc-shipping-zone-methods.js#L36) which originally ran the same code, but was not kept in sync when more logic was added to onConfigureShippingMethod.

I was able to get the logic running for "Rest of the world" by using `window.wc.wcSettings.CURRENCY` instead of the context, which wasn't available. I can't get this `save` function to fire, so not sure where its actually used 🤷🏽 .

**Comment by psealock** [comment]
>For example, I got the following results when testing with a shipping cost input of 1 000,00.00:

In [5fcf3b3](https://github.com/woocommerce/woocommerce/pull/54181/commits/5fcf3b3b5a50202d5652322aae9765df895352b6) I add a regex to strip the input of all non numeric and separator values. This helps with the `1 000,00.00` input scenario.

>Additionally some unit tests around the new unformatShippingMethodNumericValues() method would be prudent

I agree. We'll need to add some testing infrastructure

**Comment by waclawjacek** [comment]
> Seems to me like we should merge both approaches.

One issue I can see with forcing front-end strings to be formatted like in the US locale is that it could be counterintuitive to merchants to input using commas and a dot if they are used to, say, spaces and a comma (like we are in Poland). What do you think would be the best solution here? In #54542 I made it so that only amounts formatted using the separators specified in WC settings are accepted, and then the backend will also look at what the separators are and convert the number into a number that passes PHP's `is_numeric` check.

**Comment by rjchow** [comment]
@waclawjacek the frontend display is still formatted according to the locale, the unformatting only happens pre-http request.

I think it would be great to merge your approach into this PR if that's acceptable? I like that you've extracted the duplicated sanitisation code!

**Comment by waclawjacek** [comment]
> @waclawjacek the frontend display is still formatted according to the locale, the unformatting only happens pre-http request.

Doesn't it only happen the first time, after which it's US locale-formatted?

**Comment by waclawjacek** [comment]
> I think it would be great to merge your approach into this PR if that's acceptable? I like that you've extracted the duplicated sanitisation code!

For sure! I'll do that now.

**Comment by rjchow** [comment]
> > @waclawjacek the frontend display is still formatted according to the locale, the unformatting only happens pre-http request.
> 
> Doesn't it only happen the first time, after which it's US locale-formatted?

Nope it should follow the store's locale - the unformatting turns it into a standard unlocalised decimal, and the locale formatting is re-applied when it's fetched again

**Comment by rjchow** [comment]
@psealock , @waclawjacek I worked on the unit tests for the backend to move things along and found / fixed some issues 
- there was a sanitisation miss with wp_kses_post normalising the html entities, which made them not match the str_replace for the currency entities
- I realised that the root zone still had issues because of the reliance on the injected context which was not being injected, so i moved the formatting functions to woo/currency

After all that I realised that the new unformatting code quietly reformats things like $1ooo to $1 without erroring, so if the user makes a typo they won't realise. I think that's not great so I'm working on that next.

Feel free to leave any feedback on the changes or anything at all

**Comment by adrianduffell** [comment]
@rjchow Would we be able add the tests in a standalone PR? I envision that we would be able to see most tests passing with some needing to be skipped due to the present bugs. Then, with this PR, all tests would pass without any changes to the tests. I think it would help us prove this PR doesn't introduce regressions.

File: plugins/woocommerce/client/legacy/js/admin/wc-shipping-zone-methods.js (hunk 1 above)
Comment (psealock) [reply plugins/woocommerce/client/legacy/js/admin/wc-shipping-zone-methods.js]: >then run the sanitization on all numbers

Are you suggesting that we accept something like `[qty] * 4,5` for locales with commas as decimal places and it becomes `[qty] * 4.5` in the database? If so, I'd think this would be something outside the scope of this PR.

File: plugins/woocommerce/client/legacy/js/admin/wc-shipping-zone-methods.js [hunk 3]
```diff
@@ -457,12 +499,12 @@
 					return htmlContent.prop( 'outerHTML' );
 				},
 				addCurrencySymbol: function( html ) {
-					if ( ! window.wc.ShippingCurrencyContext || ! window.wc.ShippingCurrencyNumberFormat ) {
+					if ( ! window.wc.wcSettings.CURRENCY || ! window.wc.currency.localiseMonetaryValue ) {
```
Comment (psealock) [inline plugins/woocommerce/client/legacy/js/admin/wc-shipping-zone-methods.js:494]: @rjchow, optional chaining here?
```suggestion
					if ( ! window.wc.wcSettings.CURRENCY || ! window.wc.currency?.localiseMonetaryValue ) {
```

**Review by psealock — COMMENTED** [review]
>After all that I realised that the new unformatting code quietly reformats things like $1ooo to $1 without erroring, so if the user makes a typo they won't realise. I think that's not great so I'm working on that next.

Theres a `validateFormArguments` function on the class we can hook into. It runs validation on every input, which isn't as nice as on blur, but we can run ` Number.isFinite( formattedData[ field ] )` before enabling the save button. Maybe thats best in a follow up

File: plugins/woocommerce/client/legacy/js/admin/wc-shipping-zone-methods.js (hunk 1 above)
Comment (rjchow) [reply plugins/woocommerce/client/legacy/js/admin/wc-shipping-zone-methods.js]: I agree it's outside the scope of this PR - and possibly entirely outside the scope of what we should support. There was a previous PR that tried to allow this but it got reverted due to the mess it made.

I do think we should define a grammar for the formula and then parse it according to the grammar though, that shouldn't be too much work and will be reuseable going forward.

Comment (rjchow) [reply plugins/woocommerce/client/legacy/js/admin/wc-shipping-zone-methods.js]: (with just standard ISO decimal numbers in the formula)

File: plugins/woocommerce/client/legacy/js/admin/wc-shipping-zone-methods.js (hunk 3 above)
Comment (rjchow) [reply plugins/woocommerce/client/legacy/js/admin/wc-shipping-zone-methods.js:494]: I initially started off with it but then I realised we don't transpile this file so it doesn't get polyfilled for lower envs. But I just looked up the browser support and I think it's fine so I'll make the change

image

**Comment by psealock** [comment]
Noting here that we need to extend this logic to these class fields
Screenshot 2025-01-21 at 11 08 46 PM

**Comment by rjchow** [comment]
> Noting here that we need to extend this logic to these class fields Screenshot 2025-01-21 at 11 08 46 PM

Oh yea I missed that even after all the studying 😮‍💨

File: plugins/woocommerce/src/Utilities/NumberUtil.php [hunk 4]
```diff
@@ -49,4 +49,63 @@ public static function array_sum( array $arr ): float {
...
+
+		$allowed_characters_regex = sprintf(
+			'/^[0-9\%s\%s]*$/',
+			wc_get_price_thousand_separator(),
+			wc_get_price_decimal_separator()
+		);
+
+		if ( 1 !== preg_match( $allowed_characters_regex, $value ) ) {
+			throw new \InvalidArgumentException( sprintf( __( '%s is not a valid numeric value. Allowed characters: %s', 'woocommerce' ), $value, $allowed_characters_regex ) );
+		}
```
Comment (psealock) [inline plugins/woocommerce/src/Utilities/NumberUtil.php:101]: This is great feedback when things go wrong! We should offer a more merchant friendly message though. How about something like: `1oooo is not a valid numeric value. Please make sure to enter a valid number`

image

**Comment by psealock** [comment]
>Noting here that we need to extend this logic to these class fields

@rjchow I handled this in https://github.com/woocommerce/woocommerce/pull/54181/commits/28c66bb189659eebd43a4da5ed9c29730b911e40

#### To Test

1. Make sure you have a shipping class. Add two to fully test.
2. Go to or add a shipping zone with a flat rate shipping method
3. Play around with the shipping class costs inputs and see the formatting occur on blur. The formatting will be based on your settings.
4. In the Network tab, filter by `woocommerce_shipping_zone_methods_save_settings` and check the values sent by the client regarding shipping class costs. They should be stripped of their formatting in favour of a numeric value.

File: plugins/woocommerce/src/Utilities/NumberUtil.php (hunk 4 above)
Comment (rjchow) [reply plugins/woocommerce/src/Utilities/NumberUtil.php:101]: I had something like that initially but it just seemed to provide less information and the second sentence doesn't help the user troubleshoot 🙈 I could translate the regex to english?

**Review by rjchow — APPROVED** [review]
Ok I think it's good to go, thanks! @waclawjacek would you like to give it a final look over?

**Comment by waclawjacek** [comment]
I'll take a look later today. Thanks!

File: plugins/woocommerce/includes/shipping/flat-rate/class-wc-shipping-flat-rate.php [hunk 5]
```diff
@@ -282,6 +282,12 @@ public function sanitize_cost( $value ) {
 		$value = is_null( $value ) ? '' : $value;
 		$value = wp_kses_post( trim( wp_unslash( $value ) ) );
 		$value = str_replace( array( get_woocommerce_currency_symbol(), html_entity_decode( get_woocommerce_currency_symbol() ) ), '', $value );
+
+		$contains_shortcodes = false !== strpos( $value, '[' ) || false !== strpos( $value, ']' );
+		if ( ! $contains_shortcodes ) {
+			$value = \Automattic\WooCommerce\Utilities\NumberUtil::sanitize_cost_in_current_locale( $value );
+		}
```
Comment (waclawjacek) [inline plugins/woocommerce/includes/shipping/flat-rate/class-wc-shipping-flat-rate.php:289]: Do y'all think we should follow up with a PR to also handle cost input containing shortcodes?

File: plugins/woocommerce/src/Utilities/NumberUtil.php [hunk 6]
```diff
@@ -49,4 +53,66 @@ public static function array_sum( array $arr ): float {
 
 		return array_sum( $sanitized_array );
 	}
+
+	/**
+	 * Sanitize a cost value based on the current locale decimal and thousand separators.
+	 *
+	 * @param string $value               The value to sanitize.
+	 * @return string The sanitized value, or empty string if invalid.
```
Comment (waclawjacek) [inline plugins/woocommerce/src/Utilities/NumberUtil.php]: If `$value` is invalid, it will throw an exception.

The suggestion below also fixes indentation.

```suggestion
	 * @return string                     The sanitized value.
```

File: plugins/woocommerce/src/Utilities/NumberUtil.php [hunk 7]
```diff
@@ -49,4 +53,66 @@ public static function array_sum( array $arr ): float {
...
+		$decimal_separator  = wc_get_price_decimal_separator();
+		$thousand_separator = wc_get_price_thousand_separator();
+
+		if (
+			// Check that there is only 1 decimal separator.
+			substr_count( $value, $decimal_separator ) > 1 ||
+			(
+				// Check that decimal separator appears after thousand separator if both exist.
+				str_contains( $value, $thousand_separator ) &&
+				str_contains( $value, $decimal_separator ) &&
```
Comment (waclawjacek) [inline plugins/woocommerce/src/Utilities/NumberUtil.php]: `str_contains` is only available in PHP 8+.

```suggestion
				false !== strpos( $value, $thousand_separator ) &&
				false !== strpos( $value, $decimal_separator ) &&
```

File: plugins/woocommerce/src/Utilities/NumberUtil.php [hunk 8]
```diff
@@ -49,4 +53,66 @@ public static function array_sum( array $arr ): float {
...
+	public static function sanitize_cost_in_current_locale( $value ): string {
+		$value                      = is_null( $value ) ? '' : $value;
+		$value                      = wp_kses_post( trim( wp_unslash( $value ) ) );
+		$currency_symbol_encoded    = get_woocommerce_currency_symbol();
+		$currency_symbol_variations = array( $currency_symbol_encoded, wp_kses_normalize_entities( $currency_symbol_encoded ), html_entity_decode( $currency_symbol_encoded ) );
+
+		$value = str_replace( $currency_symbol_variations, '', $value );
+
+		$allowed_characters_regex = sprintf(
+			'/^[0-9\%s\%s]*$/',
```
Comment (waclawjacek) [inline plugins/woocommerce/src/Utilities/NumberUtil.php:84]: I am looking at a function called [`wc_format_decimal()`](https://github.com/woocommerce/woocommerce/blob/67407d21886cceca10d0b7cfe429295b461a7d4f/plugins/woocommerce/includes/wc-formatting-functions.php#L288) which recognizes more decimal separators than this method currently does.

It calls `localeconv()` and gets `decimal_point` and `mon_decimal_point` ("mon" stands for "monetary") from it, therefore also allowing the current locale's decimal separators and not only what is set in WC settings.

It also does some other things around sanitizing the value.

Do you think we should be using that function here, or doing some of what it is doing?

I suppose if we have the message explaining what separators are accepted then it should be OK but just wanted to bring this up in case I am missing something.

File: plugins/woocommerce/src/Utilities/NumberUtil.php (hunk 4 above)
Comment (waclawjacek) [reply plugins/woocommerce/src/Utilities/NumberUtil.php:101]: Not sure if that's helpful but we could also include the separators we're talking about in the message, like:

> [...] are the thousand (`,`) and decimal (`.`) separators.

File: plugins/woocommerce/includes/shipping/flat-rate/class-wc-shipping-flat-rate.php (hunk 5 above)
Comment (psealock) [reply plugins/woocommerce/includes/shipping/flat-rate/class-wc-shipping-flat-rate.php:289]: >Do y'all think we should follow up with a PR to also handle cost input containing shortcodes?

Sanitization and validations of formulas is an important thing, but I'm not certain we should expand the scope of this effort right now.

Comment (waclawjacek) [reply plugins/woocommerce/includes/shipping/flat-rate/class-wc-shipping-flat-rate.php:289]: Oh yeah! I mean in another issue.

File: plugins/woocommerce/src/Utilities/NumberUtil.php (hunk 8 above)
Comment (rjchow) [reply plugins/woocommerce/src/Utilities/NumberUtil.php:84]: localeconv() would get the server's locale though - and I think in most cases that probably won't be the user's locale

File: plugins/woocommerce/includes/shipping/flat-rate/class-wc-shipping-flat-rate.php (hunk 5 above)
Comment (rjchow) [reply plugins/woocommerce/includes/shipping/flat-rate/class-wc-shipping-flat-rate.php:289]: Yea I'll be writing up a separate issue for that - I'm thinking to specify a grammar and then implement a proper parser

File: plugins/woocommerce/src/Utilities/NumberUtil.php (hunk 8 above)
Comment (psealock) [reply plugins/woocommerce/src/Utilities/NumberUtil.php:84]: >It also does some other things around sanitizing the value.

In addition to getting the decimal point from server locale in and the one in Settings this function will convert multiple dots to just one. Otherwise, its the same as we already have, except it does not handle thousands separators.

I think its better to just add in consolidating multiple dots to just one, if applicable, than to use this function in addition to separately handling thousands separators.

File: plugins/woocommerce/src/Utilities/NumberUtil.php [hunk 9]
```diff
@@ -76,8 +76,8 @@ public static function sanitize_cost_in_current_locale( $value ): string {
 		);
 
 		if ( 1 !== preg_match( $allowed_characters_regex, $value ) ) {
-			/* translators: %s: Invalid value that was input by the user */
-			throw new \InvalidArgumentException( sprintf( esc_html__( '%s is not a valid numeric value. Allowed characters are numbers and the thousand and decimal separators.', 'woocommerce' ), esc_html( $value ) ) );
+			/* translators: %1$s: Invalid value that was input by the user, %2$s: thousand separator, %3$s: decimal separator */
+			throw new \InvalidArgumentException( sprintf( esc_html__( '%1$s is not a valid numeric value. Allowed characters are numbers, and the thousand (%2$s) and decimal (%3$s) separators.', 'woocommerce' ), esc_html( $value ), esc_html( wc_get_price_thousand_separator() ), esc_html( wc_get_price_decimal_separator() ) ) );
```
Comment (waclawjacek) [inline plugins/woocommerce/src/Utilities/NumberUtil.php]: Not a required change:

How about this instead? Same thing, just less `esc_html`s:

```suggestion
			throw new \InvalidArgumentException(
				esc_html(
					sprintf(
						__( '%1$s is not a valid numeric value. Allowed characters are numbers, and the thousand (%2$s) and decimal (%3$s) separators.', 'woocommerce' ),
						$value,
						wc_get_price_thousand_separator(),
						wc_get_price_decimal_separator()
					)
				)
			);
```

**Comment by waclawjacek** [comment]
:eyes:

File: packages/js/currency/src/utils.tsx [hunk 10]
```diff
@@ -406,3 +406,100 @@ export function getCurrencyData() {
...
+	) {
+		throw new Error( 'Invalid decimal separator' );
+	}
+
+	const unformattedValue = inputNumber
+		.replace(
+			new RegExp( escapeRegExp( config.thousandSeparator ), 'g' ),
+			''
+		)
+		.replace( config.decimalSeparator, '.' );
```
Comment (waclawjacek) [inline packages/js/currency/src/utils.tsx:502]: This now creates a conflict - the backend (`src/Utilities/NumberUtil.php`) expects a localized number, and the front-end sends an unformatted value.

A way to test this is to set the thousand separator to ` ` and the decimal separator to `,`, then providing this as the price: `1 234,12`

**Review by waclawjacek — DISMISSED** [review]

File: packages/js/currency/src/utils.tsx (hunk 10 above)
Comment (psealock) [reply packages/js/currency/src/utils.tsx:502]: Yikes, we really can't unlocalize twice: once on client and again on server - Good catch and thanks for bringing it up. 

On the server, what if we check to see if the string is in fact a legit number with `is_numeric` before unlocalizing?

If we don't do that I see a couple options:

1. unlocalize on the client only.
2. unlocalize on the server only.
3. Pass a parameter to say whats being sent (localized/unlocalized) and proceed accordingly.
4. Go back to `<input type="number" ... />` before all this fanciness started.

Logically 2. makes sense, but with the system designed for numbers we'd need to check to make sure the API isn't used elsewhere in the app or by extensions. I think the `is_numeric` check is the way to go.
```

Comment (rjchow) [reply packages/js/currency/src/utils.tsx:502]: _grumble grumble_ why is this so hard 🥲

How about - on the backend:

1. if it has anything other than a single decimal point, attempt to delocalise according to localisation rules
2. if it has a single decimal point && is_numeric, accept it as a number (because is_numeric is slightly looser, [1](https://www.php.net/manual/en/function.is-numeric.php), [2](https://www.php.net/manual/en/language.types.numeric-strings.php))
3. else: error

Comment (psealock) [reply packages/js/currency/src/utils.tsx:502]: Yippie, sounds good to me

**Comment by ismaeldcom** [comment]
If I'm not wrong this PR should also fix #54768 and #50717

File: packages/js/currency/src/utils.tsx (hunk 10 above)
Comment (rjchow) [reply packages/js/currency/src/utils.tsx:502]: @waclawjacek does the [commit](https://github.com/woocommerce/woocommerce/pull/54181/commits/5eb5e149fdd1dace6658749dcfb3d4646d917e2c) I pushed look ok to you? I'd like to get this into a 9.7.0 CFE soon

**Comment by waclawjacek** [comment]
:eyes:

File: plugins/woocommerce/src/Utilities/NumberUtil.php [hunk 11]
```diff
@@ -49,4 +53,85 @@ public static function array_sum( array $arr ): float {
...
+			wc_get_price_thousand_separator(),
+			wc_get_price_decimal_separator()
+		);
+
+		if ( 1 !== preg_match( $allowed_characters_regex, $value ) ) {
+			throw new \InvalidArgumentException(
+				esc_html(
+					sprintf(
+						/* translators: %1$s: Invalid value that was input by the user, %2$s: thousand separator, %3$s: decimal separator */
+						__( '%1$s is not a valid numeric value. Allowed characters are numbers, and the thousand (%2$s) and decimal (%3$s) separators.', 'woocommerce' ),
```
Comment (kallehauge) [inline plugins/woocommerce/src/Utilities/NumberUtil.php]: I really like the new inclusion of expected separators!

Screenshot 2025-02-13 at 23 34 23

**[Non-blocking, opinionated] UX suggestion**

I'm 99% sure this is outside scope, but might it be a better experience to show the error inside the edit modal? The current experience closes the modal on save to then surface the error message. 

It's quite niche, but if I had loads of shipping methods, then it might be annoying trying to find the one that failed because I was in a groove setting up or something (again, very niche!)

Alternatively, then we could also include the name of the shipping method in the error message? It's part of the `woocommerce_shipping_zone_methods_save_settings` response, so it should be doable?

_I want to recognise that the display of the error happens elsewhere which is why I consider it outside scope, but sharing it just for the sake of it anyway_

```json
{
    "success": true,
    "data": {
        "zone_id": 1,
        "zone_name": "US",
        "methods": {
            "1": {
                "min_amount": "5",
                "requires": "min_amount",
                "id": "free_shipping",
                "method_title": "Free shipping",
                "method_description": "<p>Free shipping is a special method which can be triggered with coupons and minimum spends.<\/p>\n",
                "title": "Free shipping",
                ...
            }
        },
        "errors": [
            "5_000 is not a valid numeric value. Allowed characters are numbers, and the thousand (,) and decimal (.) separators."
        ]
    }
}
```

File: plugins/woocommerce/src/Utilities/NumberUtil.php [hunk 12]
```diff
@@ -49,4 +53,85 @@ public static function array_sum( array $arr ): float {
...
+				strpos( $value, $decimal_separator ) <= strpos( $value, $thousand_separator )
+			)
+		) {
+			/* translators: %s: Invalid value that was input by the user */
+			throw new \InvalidArgumentException( sprintf( esc_html__( '%s is not a valid numeric value: there should be one decimal separator and it has to be after the thousands separator.', 'woocommerce' ), esc_html( $value ) ) );
+		}
+
+		/**
+		 * For context, as of 2025.
+		 * The full set of thousands separators is PERIOD, COMMA, SPACE, APOSTROPHE.
```
Comment (kallehauge) [inline plugins/woocommerce/src/Utilities/NumberUtil.php:130]: ℹ️  I tested digit groupings just for the sake of it since it's technically supported by [PHP (7.4+)](https://www.php.net/manual/en/language.types.integer.php) which is responsible for validating our numeric values and it's being rejected as expected (I say "as expected" since it might be a common programming pattern but has nothing to do with $$$).

_Context: PHP, JS, and some other programming languages allow underscores (`_`) to do digit groupings. Example: `1_000_000` means `1000000` and the underscores are purely for presentation as a way to more easily read numbers._
_You can open the JS dev console and enter `1_000*10` which will return `10000`_.

File: plugins/woocommerce/src/Utilities/NumberUtil.php (hunk 11 above)
Comment (kallehauge) [inline plugins/woocommerce/src/Utilities/NumberUtil.php]: I believe Matt generally pushes for Oxford commas which (AFAIK) just means we should add a `,` before `and` in this case because it's "a list" 😄 

```suggestion
						__( '%1$s is not a valid numeric value. Allowed characters are numbers, the thousand (%2$s), and decimal (%3$s) separators.', 'woocommerce' ),
```

File: plugins/woocommerce/src/Utilities/NumberUtil.php [hunk 13]
```diff
@@ -49,4 +53,85 @@ public static function array_sum( array $arr ): float {
...
+			substr_count( $value, $decimal_separator ) > 1 ||
+			(
+				// Check that decimal separator appears after thousand separator if both exist.
+				false !== strpos( $value, $thousand_separator ) &&
+				false !== strpos( $value, $decimal_separator ) &&
+				strpos( $value, $decimal_separator ) <= strpos( $value, $thousand_separator )
+			)
+		) {
+			/* translators: %s: Invalid value that was input by the user */
+			throw new \InvalidArgumentException( sprintf( esc_html__( '%s is not a valid numeric value: there should be one decimal separator and it has to be after the thousands separator.', 'woocommerce' ), esc_html( $value ) ) );
```
Comment (kallehauge) [inline plugins/woocommerce/src/Utilities/NumberUtil.php]: [Non-blocking, opinionated] Suggestion to keep our formatting the same and we've approved this once already with the above `InvalidArgumentException` (I personally prefer this as well since I read it better - just to share my two cents between the two):

```suggestion
			throw new \InvalidArgumentException(
				esc_html(
					sprintf(
						/* translators: %s: Invalid value that was input by the user */
						__( '%s is not a valid numeric value: there should be one decimal separator and it has to be after the thousands separator.', 'woocommerce' ),
						$value
					)
				)
			);
```

File: plugins/woocommerce/src/Utilities/NumberUtil.php [hunk 14]
```diff
@@ -49,4 +53,85 @@ public static function array_sum( array $arr ): float {
...
+		 * And the full set of decimal separators is PERIOD, COMMA.
+		 * There are no locales that use the same thousands and decimal separators.
+		 */
+
+		$value = str_replace( wc_get_price_thousand_separator(), '', $value );
+		$value = str_replace( wc_get_price_decimal_separator(), '.', $value );
+
+		if ( $value && ! is_numeric( $value ) ) {
+			/* translators: %s: Invalid value that was input by the user */
+			throw new \InvalidArgumentException( sprintf( esc_html__( '%s is not a valid numeric value', 'woocommerce' ), esc_html( $value ) ) );
```
Comment (kallehauge) [inline plugins/woocommerce/src/Utilities/NumberUtil.php]: [Non-blocking, opinionated] Suggestion to keep our formatting the same and we've approved this once already with the above `InvalidArgumentException` (I personally prefer this as well since I read it better - just to share my two cents between the two):

```suggestion
			throw new \InvalidArgumentException(
				esc_html(
					sprintf(
						/* translators: %s: Invalid value that was input by the user */
						__( '%s is not a valid numeric value.', 'woocommerce' ),
						$value
					)
				)
			);
```

File: packages/js/currency/src/test/utils.ts [hunk 15]
```diff
@@ -0,0 +1,285 @@
...
+			...config,
+			decimalSeparator: ',',
+			thousandSeparator: '.',
+		};
+		expect( localiseMonetaryValue( customConfig, '123.456.789' ) ).toBe(
+			'123.456.789,00'
+		);
+	} );
+
+	it( 'should not format incorrectly formatted numbers according to current config', () => {
```
Comment (kallehauge) [inline packages/js/currency/src/test/utils.ts:48]: [Non-blocking; opinionated]: Since we've already been concerned about failing silently, should we throw an error for incorrect thousand separator placements? 

I'm working of a personally biased understanding of how I would work with WC, but if I add a thousand separator, then I'd expect it to be in the correct location, so if I wrote `7,50` then I'd prefer to get an error saying it doesn't look like an expect format (which should probably have been `7,500`).
That being said then I could also have mistyped `75,00` which should be `7500` so ignoring it would be correct in this case; but is that enough to counterweight allowing the other case?

File: plugins/woocommerce/src/Utilities/NumberUtil.php [hunk 16]
```diff
@@ -49,4 +53,85 @@ public static function array_sum( array $arr ): float {
...
+	public static function sanitize_cost_in_current_locale( $value ): string {
+		$value                      = is_null( $value ) ? '' : $value;
+		$value                      = wp_kses_post( trim( wp_unslash( $value ) ) );
+		$currency_symbol_encoded    = get_woocommerce_currency_symbol();
+		$currency_symbol_variations = array( $currency_symbol_encoded, wp_kses_normalize_entities( $currency_symbol_encoded ), html_entity_decode( $currency_symbol_encoded ) );
+
+		$value = str_replace( $currency_symbol_variations, '', $value );
+
+		// Count the number of decimal points.
+		$decimal_point_count = substr_count( $value, '.' );
```
Comment (kallehauge) [inline plugins/woocommerce/src/Utilities/NumberUtil.php:73]: > @waclawjacek does the [commit](https://github.com/woocommerce/woocommerce/pull/54181/commits/5eb5e149fdd1dace6658749dcfb3d4646d917e2c) I pushed look ok to you? I'd like to get this into a 9.7.0 CFE soon

@rjchow I'm not entirely sure here. If `.` has been defined as the thousand separator, wouldn't we be making an incorrect assumption by hardcoding the decimal pointer?
```suggestion
		$decimal_point_count = substr_count( $value, wc_get_price_decimal_separator() );
```

File: plugins/woocommerce/src/Utilities/NumberUtil.php [hunk 17]
```diff
@@ -49,4 +53,85 @@ public static function array_sum( array $arr ): float {
...
+
+		// If it's a standard decimal number (single decimal point and is_numeric), accept it directly. This could be in the case where the frontend has de-localised the value.
+		// We check for the decimal point count because is_numeric is looser than that.
```
Comment (kallehauge) [inline plugins/woocommerce/src/Utilities/NumberUtil.php]: Should we make the comment more specific and explain how it's looser and the consequences that makes us do custom checks?

**Comment by kallehauge** [comment]
**Existing values**

Just making sure that it's expected behaviour 😄 

The test instructions doesn't say anything about values that has already been stored to the database using `trunk`. Example: minimum amount for free shipping being `(string) 100,00` and the store uses `,` as decimal separators:

```php
a:4:{s:5:"title";s:13:"Free shipping";s:8:"requires";s:10:"min_amount";s:10:"min_amount";s:6:"100,00";s:16:"ignore_discounts";s:2:"no";}
``` 

But if I inject this into my database and use this branch, then checkout behaves as expected (read: Free Shipping is only available when the cart is >100) 😄

File: plugins/woocommerce/src/Utilities/NumberUtil.php (hunk 11 above)
Comment (rjchow) [reply plugins/woocommerce/src/Utilities/NumberUtil.php]: I did consider it out of concern for the UX, but yea decided it was out of scope especially because it's written in very old school JS that I'm not confident with making big changes in, and we'll probably be reworking this with the settings project

File: plugins/woocommerce/src/Utilities/NumberUtil.php (hunk 12 above)
Comment (rjchow) [reply plugins/woocommerce/src/Utilities/NumberUtil.php:130]: I think I'd rather not support this 😅 It's complex enough handling just the locale-specifics

File: packages/js/currency/src/test/utils.ts (hunk 15 above)
Comment (rjchow) [reply packages/js/currency/src/test/utils.ts:48]: This function actually formats the value retrieved from the backend, for display in the frontend - I think it's correct to ignore incorrectly formatted numbers so that it throws an error when the user saves it. We don't currently have a routine that displays an error thrown where this function is called 🥲

This is out of consideration that we might have mal-formatted numbers saved prior to this PR, which should not occur going forward.

File: plugins/woocommerce/src/Utilities/NumberUtil.php (hunk 16 above)
Comment (rjchow) [reply plugins/woocommerce/src/Utilities/NumberUtil.php:73]: This is hardcoded because we expect the frontend to produce standard PHP numbers with only `.` for decimal separators, after this PR is merged. This is a way of cleaning up the database going forward so that we only have PHP numbers in the database instead of locale-specific numbers

File: plugins/woocommerce/src/Utilities/NumberUtil.php (hunk 17 above)
Comment (rjchow) [reply plugins/woocommerce/src/Utilities/NumberUtil.php]: Good callout because I forgot how it's looser by now 🤣 I'll update the comment

Comment (rjchow) [reply plugins/woocommerce/src/Utilities/NumberUtil.php]:
```suggestion
		// We check for the decimal point count in addition to using is_numeric.
		// This is because is_numeric is much looser and accepts non-base10 numbers as well as 'e' to demarcate exponents.
```

File: plugins/woocommerce/src/Utilities/NumberUtil.php (hunk 12 above)
Comment (kallehauge) [reply plugins/woocommerce/src/Utilities/NumberUtil.php:130]: Oh yeah, totally agree! My intention was to share that we're not, unintentionally, supporting underscores just because the programming language supports it - sorry about any confusion! 😄

**Comment by psealock** [comment]
Thanks for the thoughtful review @kallehauge !

>Just making sure that it's expected behaviour 😄

Yes I think so. Although were not explicitly handling these cases, nor do I think we should because we'd be making stabs in the dark to correct things. Targeted outreach will be better. The error generally affected stores who operate currencies that require large denominations, such as shipping an item for 20,000 pesos. Of course thats a generalization, but a blog post would be useful to alert merchants the potentially serious error has been fixed.

Otherwise, was your testing sufficient to offer enough certainty to deem this fix robust?

**Review by kallehauge — APPROVED** [review]
>> Just making sure that it's expected behaviour 😄
>
>Yes I think so. Although were not explicitly handling these cases, nor do I think we should because we'd be making stabs in the dark to correct things. Targeted outreach will be better. The error generally affected stores who operate currencies that require large denominations, such as shipping an item for 20,000 pesos. Of course thats a generalization, but a blog post would be useful to alert merchants the potentially serious error has been fixed.

Makes sense! 👍 

> Otherwise, was your testing sufficient to offer enough certainty to deem this fix robust?

@psealock, I'd say so! It certainly held up to the different tests I threw at it 😄

**Comment by rjchow** [comment]
Thanks both @waclawjacek and @kallehauge for providing infinitely valuable feedback on this PR! It was a team effort!
