### PR TITLE
Fix zone routes in CLI

### LINKED ISSUE #14750: CLI router broken for some commands
CLI won't handle these commands:
wp wc --user=test shipping_zone_method list
wp wc --user=test shipping_zone_method get 0
wp wc --user=test shipping_zone_location list
wp wc --user=test shipping_zone get 0

They all echo:
Error: No route was found matching the URL and request method {"status":404}

WooCommerce 3.0.4
WordPress 4.7.4

### PR DESCRIPTION
**Pull request by mikejolley**
Fixes #14750

### CODE REVIEW

File: includes/cli/class-wc-cli-runner.php [hunk 1]
```diff
@@ -92,11 +92,13 @@ private static function register_route_commands( $rest_command, $route, $route_d
...
+				'id'           => __( 'ID.', 'woocommerce' ),
 				'product_id'   => __( 'Product ID.', 'woocommerce' ),
 				'customer_id'  => __( 'Customer ID.', 'woocommerce' ),
 				'order_id'     => __( 'Order ID.', 'woocommerce' ),
 				'refund_id'    => __( 'Refund ID.', 'woocommerce' ),
 				'attribute_id' => __( 'Attribute ID.', 'woocommerce' ),
+				'zone_id'      => __( 'Zone ID.', 'woocommerce' ),
 		);
 		$rest_command->set_supported_ids( $supported_ids );
 		$positional_args = array_merge( array( 'id' ), array_keys( $supported_ids ) );
```
Comment (justinshreve) [inline includes/cli/class-wc-cli-runner.php]: We can probably drop the `array_merge` here since `id` is now in `supported_ids`. I don't remember why it was separate in the first place.

**Review by emdashcodes — APPROVED** [review]
Changes LGTM. Just left one comment on something we can fix up.
