### PR TITLE
Importer; create placeholders when importing products with IDs

### LINKED ISSUE #15614: [3.1.0] The variations are not imported
Storefront 2.2.3
only WooCommerce 3.1.0-beta.2 (master)
WordPress 4.8

To reproduce:
Create a variable product with:
* a global attribute: for example 'Size'
* a term: for example 'XL'
* set a price at the level variation

Export this product: I keep the default options 'Export all columns' and 'Export all products'.

Import the csv file: I do not import the column name ID.

Then edit the just imported product: the variation tab is empty.

### PR DESCRIPTION
**Pull request by mikejolley**
This allows variations to be imported when IDs are used and set.

If you’re not updating via CSV, the default behaviour will be to create new products, but map based on provided IDs.

Fixes #15614

### CODE REVIEW

File: includes/data-stores/class-wc-product-variation-data-store-cpt.php [hunk 1]
```diff
@@ -38,23 +38,10 @@ protected function exclude_internal_meta_keys( $meta ) {
 	public function read( &$product ) {
 		$product->set_defaults();
 
-		if ( ! $product->get_id() || ! ( $post_object = get_post( $product->get_id() ) ) || 'product_variation' !== $post_object->post_type ) {
+		if ( ! $product->get_id() || ! ( $post_object = get_post( $product->get_id() ) ) || ! in_array( $post_object->post_type, array( 'product', 'product_variation' )) ) {
```
Comment (claudiulodro) [inline includes/data-stores/class-wc-product-variation-data-store-cpt.php]: `)) )` Needs a space.

**Comment by claudiulodro** [comment]
This looks good. I think making the temp products in the parser is what we have to do here. I'll fix the space issue then merge so we can get RC out the door.
