### PR TITLE
[Accessibility] Add aria-label for page numbers within pagination

### LINKED ISSUE #44376: Missing Accessible Markup in Pagination Template
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

If your store has enough products to paginate WooCommerce uses the **woocommerce > templates > loop > pagination.php** template. 

This template works for sighted users. But it doesn't work for users who rely on the keyboard.

You don't have the context to know you're going to go to another page of products. It could be a webpage called 2, a product called 2. Or any number of things. Without context a keyboard user will have to just click the link and see where they land which is very tedious.

This fails to meet [WCAG's criteria 2.4.4: Link Purpose in Context](https://www.w3.org/WAI/WCAG21/Understanding/link-purpose-in-context.html).

### Expected behavior

Screen reader software should know what the purpose of the link is and should describe it to the user.

Ex. 
* Go to page 2
* Go to next page

### Actual behavior

If you use screen reading software you will just hear:

> navigation list with 3 items, 2 link list item, right arrow link list item 

There is no context.

Sound on 🔉 :

https://github.com/woocommerce/woocommerce/assets/1065372/5c48d854-6000-4305-a1f1-fbbdb979873f

### Steps to reproduce

1. Fresh install of WooCommerce & Storefront
2. Add a few products so you have enough for multiple pages

### WordPress Environment ###

WordPress address (URL): http://woo-core.local
Site address (URL): http://woo-core.local
WC Version: 8.5.2
REST API Version: ✔ 8.5.2
WC Blocks Version: ✔ 11.8.0-dev
Action Scheduler Version: ✔ 3.7.1
Log Directory Writable: ✔
WP Version: 6.4.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.16.0
PHP Version: 8.1.23
PHP Post Max Size: 1,000 MB
PHP Time Limit: 1200
PHP Max Input Vars: 4000
cURL Version: 8.4.0
(SecureTransport) LibreSSL/3.3.6

SUHOSIN Installed: –
MySQL Version: 8.0.16
Max Upload Size: 300 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.5.2
WC Database Prefix: wp_
Total Database Size: 5.30MB
Database Data Size: 3.61MB
Database Index Size: 1.69MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 2.48MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_posts: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 11
page: 7
post: 2
product: 18
revision: 1
wp_global_styles: 1
wp_navigation: 1
wp_template: 2

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 8.5.2

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to Woo.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### WC Pages ###

Shop base: #7 - /shop/
Cart: #8 - /cart/
Checkout: #9 - /checkout/
My account: #10 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 4.5.4
Author URL: https://woo.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
product-virtual-downloadable
product-external-affiliate
product-grouped
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: customize-store
minified-js
new-product-management-experience
product-linked
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2024-02-06 21:22:38 +00:00
Options: ✔
Notes: 66
Onboarding: completed

### Action Scheduler ###

Complete: 26
Oldest: 2024-02-05 21:23:41 +0000
Newest: 2024-02-05 21:28:15 +0000

Failed: 1
Oldest: 2024-02-05 21:24:38 +0000
Newest: 2024-02-05 21:24:38 +0000

Pending: 1
Oldest: 2024-02-06 21:23:41 +0000
Newest: 2024-02-06 21:23:41 +0000

### Status report information ###

Generated at: 2024-02-05 23:50:33 +00:00

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by amesplant**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes #44376 .
- Adds screen reader text to announce as "Page X" instead of just the number

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Using a screen reader, tab to the page numbers 
2. When landing on a page number link, the page should announce "Page X" where X is the page number
3. Inspecting the code should reveal an `aria-label="Page X"` for each of the pagination links

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

### CODE REVIEW

**Comment by amesplant** [comment]
@dkotter passing over to you for Code Review

File: plugins/woocommerce/src/Blocks/BlockTypes/ProductCollection.php [hunk 1]
```diff
@@ -302,6 +302,20 @@ private function update_pagination_anchors( $processor, $class_name, $key_prefix
...
 				$processor->set_attribute( 'data-wc-watch', 'callbacks.prefetch' );
 				$processor->set_attribute( 'data-wc-on--mouseenter', 'actions.prefetchOnHover' );
+			} else {
+				$inner_text = __( 'Page ', 'woocommerce' );
+				$processor->set_bookmark( 'page_number' );
+				while ( $processor->next_token() ) {
+					if ( '#text' === $processor->get_token_type() ) {
+						$page = trim( $processor->get_modifiable_text() );
+						if ( is_numeric( $page ) ) {
+							$inner_text .= $page;
```
Comment (dkotter) [inline plugins/woocommerce/src/Blocks/BlockTypes/ProductCollection.php]: While I'm assuming this is unlikely, if there's ever a chance the `$page` variable isn't a numeric value, we end up setting the `aria-label` to `Page ` (with an extra space on the end). Thinking we may want to add that space when we combine the text with the page number to avoid that, something like:
```suggestion
				$inner_text = __( 'Page', 'woocommerce' );
				$processor->set_bookmark( 'page_number' );
				while ( $processor->next_token() ) {
					if ( '#text' === $processor->get_token_type() ) {
						$page = trim( $processor->get_modifiable_text() );
						if ( is_numeric( $page ) ) {
							$inner_text .= ' ' . $page;
```

**Comment by amesplant** [comment]
@dkotter applied your suggest .. thanks for that.

**Review by dkotter — APPROVED** [review]
@ankitguptaindia @qasumitbagthariya This is ready for QA

**Comment by ankitguptaindia** [comment]
QA Status: Needs feedback  ⚠️ 
----



Thanks @amesplant for creating this PR. I checked this PR and found when using Storefront theme, it announced "Link X" instead of "Page X". Also I noticed that it has `aria-current="page"` instead of 'aria-label="Page X"' as described in the description.   

Works as intended in TT4 theme:

Video has Sound 🔈 : ON


https://github.com/user-attachments/assets/cd66412c-81bc-4c1c-ad31-cba5d5b8acab


Doesn't work with Storefront: ⚠️ 

https://github.com/user-attachments/assets/d347795f-5d46-479a-8d64-c7529be9722c

**Comment by qasumitbagthariya** [comment]
@amesplant I also cross checked with my system and the result is the same it's not working for me with the storefront theme.

**Comment by amesplant** [comment]
Thanks @ankitguptaindia and @qasumitbagthariya I will investigate further with the Storefront theme.
FWIW the current page should also say `aria-current="page"` and is not an addition to this PR. 
Not sure why Storefront would announce "Link X", but will dig around and update the PR.

Edit:
The two themes are using 2 different pagination blocks, and thus the screen reader just announces "link X" without the "page" prefix for the Storefront theme. I will update the Storefront theme to add that "page" prefix.

**Comment by amesplant** [comment]
@ankitguptaindia and @qasumitbagthariya thanks again. I have updated the `pagination.php` that Storefront uses and that should now behave the same way, announcing "Page X" when on a page number link.

**Review by dkotter — CHANGES_REQUESTED** [review]
We'll need to bump the version number in the template file

**Comment by amesplant** [comment]
@dkotter bumped version

**Comment by ankitguptaindia** [comment]
**QA/Test Report-** ✅ 
------------

**Testing Environment -** 

<Details>

* WordPress: 6.6.1
* Theme: 
**Storefront Version: 4.6.0 
**Twenty Twenty-Four Version: 1.2
* WooCommerce - Development version with this fix-specific branch.  
* PHP: 8.3
* Web Server: Nginx
* Browser: Chrome - Version 127
* OS: macOS Sonoma 14.5



</Details>


**Test Results -** 

Changes work as expected. Tested via macOS Voice Over on Storefront theme and Twenty-Twenty-Four theme. 
 

**Functional Demo /  Screencast -** 

https://github.com/user-attachments/assets/9ad23324-9c60-4ca6-9ac3-d2785bdbec88

**Comment by ankitguptaindia** [comment]
@amesplant PR is QA-approved now. Please update the PR description for the next step.

**Comment by vikrampm1** [comment]
@WunderBart / @woocommerce/woo-fse this PR is now ready for your review.

File: plugins/woocommerce/templates/loop/pagination.php [hunk 2]
```diff
@@ -12,17 +12,20 @@
  *
  * @see     https://woocommerce.com/document/template-structure/
  * @package WooCommerce\Templates
- * @version 9.3.0
+ * @version 9.4.0
```
Comment (kmanijak) [inline plugins/woocommerce/templates/loop/pagination.php]: The expected version should be a corresponding WooCommerce version in which the change lands. So in this case it should stay at 9.3.0 as it was already bumped in https://github.com/woocommerce/woocommerce/pull/49924.

```suggestion
 * @version 9.3.0
```

File: plugins/woocommerce/src/Blocks/BlockTypes/ProductCollection.php [hunk 3]
```diff
@@ -380,6 +380,20 @@ private function update_pagination_anchors( $processor, $class_name, $key_prefix
...
+					if ( '#text' === $processor->get_token_type() ) {
+						$page = trim( $processor->get_modifiable_text() );
+						if ( is_numeric( $page ) ) {
+							$inner_text .= ' ' . $page;
+							break;
+						}
+					}
+				}
+				$processor->seek( 'page_number' );
+				$processor->set_attribute( 'aria-label', $inner_text );
```
Comment (kmanijak) [inline plugins/woocommerce/src/Blocks/BlockTypes/ProductCollection.php]: While it works as expected I don't think that's the way to go. Product Collection block uses `core/query-pagination` block underneath. Instead of iterating over and amending the HTML through Product Collection, I'd rather make updates in Gutenberg (and changes will eventually propagate to Product Collection block).

So [here in the source](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-library/src/query-pagination-numbers/index.php#L50), the changes could be done in the same way as in `plugins/woocommerce/templates/loop/pagination.php`. WDYT?

**Review by kmanijak — CHANGES_REQUESTED** [review]
I tested the changes and they work as expected, however, I'm not convinced if that's the way to go with Product Collection block. I'd rather suggest making updates to Core's block. Happy to hear your opinion 🙌

File: plugins/woocommerce/src/Blocks/BlockTypes/ProductCollection.php (hunk 3 above)
Comment (amesplant) [reply plugins/woocommerce/src/Blocks/BlockTypes/ProductCollection.php]: @kmanijak while I don't 'disagree', I think that this is a good fix at the moment until we can make that update with Gutenberg's native pagination.

Comment (kmanijak) [reply plugins/woocommerce/src/Blocks/BlockTypes/ProductCollection.php]: > I think that this is a good fix at the moment until we can make that update with Gutenberg's native pagination.

I'm still against patching Gutenberg's block from within Product Collection for a couple of reasons:
1. Upstream contribution would provide improvement to a wider audience (Query Loop, Product Collection, Products (Beta), and any other block that may be using core's Pagination), not only to Product Collection users.
2. While the fix is provided in the Pagination block, this piece of code needs to be removed, otherwise the `aria-label` will be overridden.

Having said that, I'm happy to help with or even kick off a contribution to Gutenberg but at the same time I'm against introducing this code to Product Collection block. 🙌

**Comment by vikrampm1** [comment]
With Ames off the project @Manussakis can you review the comments / feedback above and see what next steps we can take here?

**Comment by Manussakis** [comment]
@vikrampm1 I cannot add commits to this PR since I am not a Woo maintainer.

I believe we can work around it if @amesplant add me as a collaborator to their forked woocommerce repo.

Ames, would you mind trying that?

**Comment by amesplant** [comment]
> I believe we can work around it if @amesplant add me as a collaborator to their forked woocommerce repo
@Manussakis added :D

**Comment by Manussakis** [comment]
@kmanijak I have reviewed this issue and found that both [WooCommerce](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/templates/loop/pagination.php#L33) and [Gutenberg](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-library/src/query-pagination-numbers/index.php#L88) utilize the [`paginate_links`](https://developer.wordpress.org/reference/functions/paginate_links/) WP function for building the pagination HTML markup.

While there is room for improving pagination accessibility, the current implementation isn't necessarily incorrect. The links are within a `<nav>` element with the `role="pagination"` attribute, which provides users with the context of the links' purpose. Additionally, the `paginate_links` function includes the `paginate_links_output` filter for updating the pagination markup, so this doesn’t seem like an issue that should be raised on the WP side.

Therefore, I believe the best approach on the WooCommerce side is to hook into the `paginate_links_output` filter, as I've done in this PR. This solves the issue on both the classic and block paginations.

Please review it again!

cc: @dkotter

File: plugins/woocommerce/includes/wc-template-functions.php [hunk 4]
```diff
@@ -4095,3 +4095,37 @@ function wc_set_hooked_blocks_version_on_theme_switch( $old_name, $old_theme ) {
...
+/**
+ * Add aria-label to pagination numbers.
+ *
+ * @param string $r    HTML output.
+ * @param array  $args An array of arguments. See paginate_links()
+ *                     for information on accepted arguments.
+ *
+ * @return string
+ */
+function wc_add_aria_label_to_pagination_numbers( $r, $args ) {
```
Comment (kmanijak) [inline plugins/woocommerce/includes/wc-template-functions.php]: Can we rename the `$r` variable into more meaningful name? Like `$html` or something? Unless there's a good reason to keep it `$r`.

```suggestion
function wc_add_aria_label_to_pagination_numbers( $html, $args ) {
```

**Review by kmanijak — CHANGES_REQUESTED** [review]
Hey @Manussakis,

I like the overall, more generic approach! But we need to adjust the logic as it's incorrect in the current shape. It doesn't take into account the actual page numbers but just assumes the consecutive numbers. So with my pagination like this:

image

The aria-label says:
- `1` - page 1
- `2` - page 2
- `3` - page 3
- noninteractive `...` - page 4
- `557` - page 5

Screen Shot 2024-09-03 at 09 57 37 AM

It also starts counting from 1, even if you're on a page, let's say, 27.

image

Also, there are some linting errors:

```
. lint:changes:branch:php: FILE: plugins/woocommerce/includes/wc-template-functions.php
. lint:changes:branch:php: -----------------------------------------------------------------------------------------------
. lint:changes:branch:php: FOUND 6 ERRORS AND 1 WARNING AFFECTING 7 LINES
. lint:changes:branch:php: -----------------------------------------------------------------------------------------------
. lint:changes:branch:php:  4108 | WARNING | The method parameter $args is never used (Generic.CodeAnalysis.UnusedFunctionParameter.FoundAfterLastUsed)
. lint:changes:branch:php:  4116 | ERROR | Expected exactly one space after opening parenthesis; " \n" found. (WordPress.WhiteSpace.ControlStructureSpacing.ExtraSpaceAfterOpenParenthesis)
. lint:changes:branch:php:  4116 | ERROR | Whitespace found at end of line (Squiz.WhiteSpace.SuperfluousWhitespace.EndLine)
. lint:changes:branch:php:  4117 | ERROR | Whitespace found at end of line (Squiz.WhiteSpace.SuperfluousWhitespace.EndLine)
. lint:changes:branch:php:  4118 | ERROR | Whitespace found at end of line (Squiz.WhiteSpace.SuperfluousWhitespace.EndLine)
. lint:changes:branch:php:  4119 | ERROR | Mixing different binary boolean operators within an expression without using parentheses to clarify precedence is not allowed. (Generic.CodeAnalysis.RequireExplicitBooleanOperatorPrecedence.MissingParentheses)
. lint:changes:branch:php:  41[24](https://github.com/woocommerce/woocommerce/actions/runs/10640369778/job/29499976185?pr=50447#step:4:25) | ERROR | Increment and decrement operators must be bracketed when used in string concatenation (Squiz.Operators.IncrementDecrementUsage.NoBrackets)
```

File: plugins/woocommerce/includes/wc-template-functions.php (hunk 4 above)
Comment (Manussakis) [reply plugins/woocommerce/includes/wc-template-functions.php]: @kmanijak I used `$r` because that's how the filter is documented on https://developer.wordpress.org/reference/functions/paginate_links/, but I agree that `$html` provides more meaningful name and will change it. Thanks!

**Comment by Manussakis** [comment]
@kmanijak Thanks for testing it.
Good catch! I will fix the logic.

Thanks!

File: plugins/woocommerce/includes/wc-template-functions.php (hunk 4 above)
Comment (Manussakis) [reply plugins/woocommerce/includes/wc-template-functions.php]: ✅ Done
[Rename $r parameter to $html](https://github.com/woocommerce/woocommerce/pull/50447/commits/ed695c3a92ce6cb86af52d66aed8aca15f756a9e)

**Comment by Manussakis** [comment]
@dkotter Please code review this PR again. Thanks!

**Review by dkotter — APPROVED** [review]

**Comment by Manussakis** [comment]
@ankitguptaindia Please, QA this PR again. Thanks!!

**Comment by ankitguptaindia** [comment]
Thanks for the fixes @Manussakis It works as intended when store has less number of pages but when store has pages like 300+ then it has some issues.

1.  When the user reaches the page after some clicks on pagination, it announces an incorrect page number. In my case, after Page-5, or Page-6, it announces Page 375 but the actual page number is 3. Please watch the attached video.

Screenshot 2024-09-05 at 2 30 57 PM

https://github.com/user-attachments/assets/d700bfed-8591-4c5e-bcad-64aec998134f



2. On the Safari browser, these page numbers are not getting focused on the tab clicks although work fine in Chrome and Firefox. 



https://github.com/user-attachments/assets/8c80ec4c-42cd-4d55-b81e-d3935f3532ba

**Comment by Manussakis** [comment]
@ankitguptaindia Thanks for testing and flagging the issue.

I didn't account for a pagination scenario with two ellipsis elements. It's fixed now.

@dkotter Please re-review.

**Review by dkotter — APPROVED** [review]

File: plugins/woocommerce/includes/wc-template-functions.php [hunk 5]
```diff
@@ -4133,3 +4133,48 @@ function wc_set_hooked_blocks_version_on_theme_switch( $old_name, $old_theme ) {
...
+			} else {
+				$n = $args['total'] - $args['end_size'];
+			}
+			++$n;
+			continue;
+		}
+
+		$p->set_attribute( 'aria-label', $page_text . ' ' . number_format_i18n( $n ) );
+		++$n;
+	}
```
Comment (kmanijak) [inline plugins/woocommerce/includes/wc-template-functions.php:4183]: I tested the PR and it works fine. I'm wondering though if we cannot simplify this logic a bit. Rather than excluding elements like ellipsis and prev/next page, what if we simply look for `$p->has_class( 'page-number' )` and assign pages to them using [`get_modifiable_text()`](https://developer.wordpress.org/reference/classes/wp_html_tag_processor/get_modifiable_text/).

I imagined something like:

```suggestion
		if (
			$p->has_class( 'page-number' )
			    $n = $p->get_modifiable_text();
           		$p->set_attribute( 'aria-label', $page_text . ' ' . number_format_i18n( $n ) );
		}
	}
```

What do you think about such approach? Is there a need to calculate `$n` manually?

**Comment by ankitguptaindia** [comment]
Thanks @Manussakis for the fixes. Reported issues have been addressed and functional as expected in my test. We can move PR ahead once you have a look on https://github.com/woocommerce/woocommerce/pull/50447#discussion_r1762167364 feedback.

File: plugins/woocommerce/includes/wc-template-functions.php (hunk 5 above)
Comment (Manussakis) [reply plugins/woocommerce/includes/wc-template-functions.php:4183]: @kmanijak Thanks for your feedback!

The reason why I didn't use the `get_modifiable_text()` method is that users can pass the `before_page_number` and `after_page_number` arguments to [modify the page number text](https://github.com/WordPress/wordpress-develop/blob/trunk/src/wp-includes/general-template.php#L4625), but we don't want them to be part of the `aria-label` value.

By calculating `$n`, we ensure that only the page number is passed to the `aria-label` attribute.

Comment (kmanijak) [reply plugins/woocommerce/includes/wc-template-functions.php:4183]: Makes sense, thanks for explanation!

**Review by kmanijak — APPROVED** [review]
I tested the changes again and it LGTM! Thanks for patience and addressing all the comments 🙌

**Comment by vikrampm1** [comment]
@kmanijak thanks. Please proceed and merge the PR as it has completed all the steps from our end.

**Comment by kmanijak** [comment]
PR didn't trigger all of the CI actions so I created a temporary PR to trigger them all: https://github.com/woocommerce/woocommerce/pull/51722. 

All checks are green so merging this one!
