### PR TITLE
Move condition to check post status before rendering product

### LINKED ISSUE #44679: Upgrading to WP WooCommerce plugin 8.6.0 causes product page showing blank content for unauthenticated users
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Upgrading to WP WooCommerce plugin 8.6.0 causes product page showing blank content for unauthenticated users. Downgrading back to 8.5.2 makes it working again.

### Expected behavior

Single product page shows defined content for both authenticated and non-authenticated users. This is working properly in 8.5.2

### Actual behavior

Single product page shows defined content only for authenticated users. Content is blank for unauthenticated users, only title is shown. This is how it works in 8.6.0

### Steps to reproduce

Just open any single product page without logging in when 8.6.0 is installed. 

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://www.scienceofmassage.com
Site address (URL): https://www.scienceofmassage.com
WC Version: 8.5.2
REST API Version: ✔ 8.5.2
WC Blocks Version: ✔ 11.8.0-dev
Action Scheduler Version: ✔ 3.7.1
Log Directory Writable: ✔
WP Version: 6.4.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: –
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: Apache/2.4.57 (Debian)
PHP Version: 8.1.27
PHP Post Max Size: 128 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.88.1
OpenSSL/3.0.11

SUHOSIN Installed: –
MySQL Version: 11.2.2-MariaDB-1:11.2.2+maria~deb12
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.6.0
WC Database Prefix: wp_
Total Database Size: 336.04MB
Database Data Size: 244.59MB
Database Index Size: 91.45MB
wp_woocommerce_sessions: Data: 0.09MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.23MB + Index: 0.09MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 1.52MB + Index: 2.00MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
tmpbbdfea_actionscheduler_actions: Data: 0.41MB + Index: 0.42MB + Engine InnoDB
tmpbbdfea_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
tmpbbdfea_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
tmpbbdfea_actionscheduler_logs: Data: 0.31MB + Index: 0.17MB + Engine InnoDB
tmpbbdfea_aiowps_debug_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
tmpbbdfea_aiowps_events: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
tmpbbdfea_aiowps_failed_logins: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
tmpbbdfea_aiowps_global_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
tmpbbdfea_aiowps_login_activity: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
tmpbbdfea_aiowps_login_lockdown: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
tmpbbdfea_aiowps_permanent_block: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
tmpbbdfea_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
tmpbbdfea_comments: Data: 1.52MB + Index: 0.86MB + Engine InnoDB
tmpbbdfea_cppolls_forms: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
tmpbbdfea_cppolls_messages: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
tmpbbdfea_eab_bookings: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
tmpbbdfea_eab_booking_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
tmpbbdfea_em_modals: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
tmpbbdfea_em_modal_metas: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
tmpbbdfea_em_themes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
tmpbbdfea_em_theme_metas: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
tmpbbdfea_enewsletter_groups: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
tmpbbdfea_enewsletter_members: Data: 0.34MB + Index: 0.00MB + Engine InnoDB
tmpbbdfea_enewsletter_member_group: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
tmpbbdfea_enewsletter_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
tmpbbdfea_enewsletter_newsletters: Data: 0.34MB + Index: 0.00MB + Engine InnoDB
tmpbbdfea_enewsletter_send: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
tmpbbdfea_enewsletter_send_members: Data: 3.52MB + Index: 0.00MB + Engine InnoDB
tmpbbdfea_enewsletter_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
tmpbbdfea_eum_logs: Data: 7.52MB + Index: 0.00MB + Engine InnoDB
tmpbbdfea_forums: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
tmpbbdfea_forums_posts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
tmpbbdfea_forums_topics: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
tmpbbdfea_fv_player_emails: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
tmpbbdfea_fv_player_encoding_jobs: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
tmpbbdfea_fv_player_playermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
tmpbbdfea_fv_player_players: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
tmpbbdfea_fv_player_stats: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
tmpbbdfea_fv_player_videometa: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
tmpbbdfea_fv_player_videos: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
tmpbbdfea_gglcptch_allowlist: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
tmpbbdfea_h5p_contents: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
tmpbbdfea_h5p_contents_libraries: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
tmpbbdfea_h5p_contents_tags: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
tmpbbdfea_h5p_contents_user_data: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
tmpbbdfea_h5p_counters: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
tmpbbdfea_h5p_events: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
tmpbbdfea_h5p_libraries: Data: 1.52MB + Index: 0.03MB + Engine InnoDB
tmpbbdfea_h5p_libraries_cachedassets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
tmpbbdfea_h5p_libraries_hub_cache: Data: 0.11MB + Index: 0.02MB + Engine InnoDB
tmpbbdfea_h5p_libraries_languages: Data: 4.52MB + Index: 0.00MB + Engine InnoDB
tmpbbdfea_h5p_libraries_libraries: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
tmpbbdfea_h5p_results: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
tmpbbdfea_h5p_tags: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
tmpbbdfea_h5p_tmpfiles: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
tmpbbdfea_itsec_lockouts: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
tmpbbdfea_itsec_log: Data: 3.52MB + Index: 0.09MB + Engine InnoDB
tmpbbdfea_itsec_temp: Data: 0.05MB + Index: 0.06MB + Engine InnoDB
tmpbbdfea_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
tmpbbdfea_mepr_jobs: Data: 0.02MB + Index: 0.14MB + Engine InnoDB
tmpbbdfea_mepr_members: Data: 1.52MB + Index: 2.52MB + Engine InnoDB
tmpbbdfea_mepr_orders: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
tmpbbdfea_mepr_order_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
tmpbbdfea_mepr_rule_access_conditions: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
tmpbbdfea_mepr_subscriptions: Data: 0.42MB + Index: 1.30MB + Engine InnoDB
tmpbbdfea_mepr_subscription_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
tmpbbdfea_mepr_tax_rates: Data: 0.02MB + Index: 0.14MB + Engine InnoDB
tmpbbdfea_mepr_tax_rate_locations: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
tmpbbdfea_mepr_transactions: Data: 3.52MB + Index: 10.19MB + Engine InnoDB
tmpbbdfea_mepr_transactions_backup: Data: 0.02MB + Index: 0.17MB + Engine InnoDB
tmpbbdfea_mepr_transaction_meta: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
tmpbbdfea_moos_oauth_access_tokens: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
tmpbbdfea_moos_oauth_authorization_codes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
tmpbbdfea_moos_oauth_authorized_apps: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
tmpbbdfea_moos_oauth_clients: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
tmpbbdfea_moos_oauth_public_keys: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
tmpbbdfea_moos_oauth_refresh_tokens: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
tmpbbdfea_moos_oauth_scopes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
tmpbbdfea_moos_oauth_users: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
tmpbbdfea_newsletter: Data: 1.52MB + Index: 0.14MB + Engine InnoDB
tmpbbdfea_newsletter_emails: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
tmpbbdfea_newsletter_sent: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
tmpbbdfea_newsletter_stats: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
tmpbbdfea_newsman_an_clicks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
tmpbbdfea_newsman_an_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
tmpbbdfea_newsman_an_sub_details: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
tmpbbdfea_newsman_an_timeline: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
tmpbbdfea_newsman_blocked_domains: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
tmpbbdfea_newsman_emails: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
tmpbbdfea_newsman_email_templates: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
tmpbbdfea_newsman_lists: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
tmpbbdfea_newsman_locks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
tmpbbdfea_newsman_lst_default: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
tmpbbdfea_newsman_lst_wp_users: Data: 0.50MB + Index: 0.14MB + Engine InnoDB
tmpbbdfea_newsman_sentlog: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
tmpbbdfea_newsman_workers: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
tmpbbdfea_oauth_access_tokens: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
tmpbbdfea_oauth_authorization_codes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
tmpbbdfea_oauth_jwt: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
tmpbbdfea_oauth_public_keys: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
tmpbbdfea_oauth_refresh_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
tmpbbdfea_oauth_scopes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
tmpbbdfea_om_leads: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
tmpbbdfea_onclick_show_popup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
tmpbbdfea_options: Data: 6.52MB + Index: 0.44MB + Engine InnoDB
tmpbbdfea_pollsa: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
tmpbbdfea_pollsip: Data: 0.13MB + Index: 0.16MB + Engine InnoDB
tmpbbdfea_pollsq: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
tmpbbdfea_popover_ip_cache: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
tmpbbdfea_popularpostsdata: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
tmpbbdfea_popularpostssummary: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
tmpbbdfea_postexpirator_debug: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
tmpbbdfea_ppfuture_actions_args: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
tmpbbdfea_ppress_forms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
tmpbbdfea_ppress_formsmeta: Data: 0.06MB + Index: 0.05MB + Engine InnoDB
tmpbbdfea_ppress_meta_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
tmpbbdfea_sgpb_subscribers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
tmpbbdfea_sgpb_subscription_error_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
tmpbbdfea_sg_fblike_popup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
tmpbbdfea_sg_html_popup: Data: 0.09MB + Index: 0.00MB + Engine InnoDB
tmpbbdfea_sg_image_popup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
tmpbbdfea_sg_popup: Data: 0.13MB + Index: 0.00MB + Engine InnoDB
tmpbbdfea_sg_popup_addons: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
tmpbbdfea_sg_popup_addons_connection: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
tmpbbdfea_sg_popup_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
tmpbbdfea_sg_shortCode_popup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
tmpbbdfea_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
tmpbbdfea_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
tmpbbdfea_term_relationships: Data: 0.09MB + Index: 0.06MB + Engine InnoDB
tmpbbdfea_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
tmpbbdfea_usermeta: Data: 1.52MB + Index: 2.06MB + Engine InnoDB
tmpbbdfea_users: Data: 1.52MB + Index: 0.70MB + Engine InnoDB
tmpbbdfea_wafp_clicks: Data: 0.02MB + Index: 0.14MB + Engine InnoDB
tmpbbdfea_wafp_commissions: Data: 0.02MB + Index: 0.14MB + Engine InnoDB
tmpbbdfea_wafp_links: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
tmpbbdfea_wafp_payments: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
tmpbbdfea_wafp_responses: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
tmpbbdfea_wafp_transactions: Data: 1.52MB + Index: 2.25MB + Engine InnoDB
tmpbbdfea_wc_admin_notes: Data: 0.13MB + Index: 0.00MB + Engine InnoDB
tmpbbdfea_wc_admin_note_actions: Data: 0.08MB + Index: 0.02MB + Engine InnoDB
tmpbbdfea_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
tmpbbdfea_wc_customer_lookup: Data: 0.09MB + Index: 0.06MB + Engine InnoDB
tmpbbdfea_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
tmpbbdfea_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
tmpbbdfea_wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
tmpbbdfea_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
tmpbbdfea_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
tmpbbdfea_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
tmpbbdfea_wc_order_product_lookup: Data: 0.16MB + Index: 0.19MB + Engine InnoDB
tmpbbdfea_wc_order_stats: Data: 0.13MB + Index: 0.11MB + Engine InnoDB
tmpbbdfea_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
tmpbbdfea_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
tmpbbdfea_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
tmpbbdfea_wc_product_meta_lookup: Data: 0.06MB + Index: 0.09MB + Engine InnoDB
tmpbbdfea_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
tmpbbdfea_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
tmpbbdfea_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
tmpbbdfea_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
tmpbbdfea_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
tmpbbdfea_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
tmpbbdfea_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
tmpbbdfea_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
tmpbbdfea_woocommerce_order_itemmeta: Data: 1.52MB + Index: 2.03MB + Engine InnoDB
tmpbbdfea_woocommerce_order_items: Data: 0.23MB + Index: 0.09MB + Engine InnoDB
tmpbbdfea_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
tmpbbdfea_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
tmpbbdfea_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
tmpbbdfea_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
tmpbbdfea_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
tmpbbdfea_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
tmpbbdfea_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
tmpbbdfea_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
tmpbbdfea_word_replacer: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
tmpbbdfea_wpmailsmtp_debug_events: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
tmpbbdfea_wpmailsmtp_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
tmpbbdfea_wpwhpro_authentication: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
tmpbbdfea_yop_pollmeta: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
tmpbbdfea_yop_polls: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
tmpbbdfea_yop_poll_answermeta: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
tmpbbdfea_yop_poll_answers: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
tmpbbdfea_yop_poll_bans: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
tmpbbdfea_yop_poll_custom_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
tmpbbdfea_yop_poll_facebook_users: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
tmpbbdfea_yop_poll_logs: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
tmpbbdfea_yop_poll_templates: Data: 0.38MB + Index: 0.00MB + Engine InnoDB
tmpbbdfea_yop_poll_voters: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
tmpbbdfea_yop_poll_votes_custom_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.45MB + Index: 0.44MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.36MB + Index: 0.20MB + Engine InnoDB
wp_aiowps_debug_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_aiowps_events: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_aiowps_failed_logins: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_aiowps_global_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_aiowps_login_activity: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_aiowps_login_lockdown: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_aiowps_permanent_block: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 1.52MB + Index: 0.94MB + Engine InnoDB
wp_cppolls_forms: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cppolls_messages: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_eab_bookings: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_eab_booking_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_em_modals: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_em_modal_metas: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_em_themes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_em_theme_metas: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_enewsletter_groups: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_enewsletter_members: Data: 0.34MB + Index: 0.00MB + Engine InnoDB
wp_enewsletter_member_group: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_enewsletter_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_enewsletter_newsletters: Data: 0.34MB + Index: 0.00MB + Engine InnoDB
wp_enewsletter_send: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
wp_enewsletter_send_members: Data: 3.52MB + Index: 0.00MB + Engine InnoDB
wp_enewsletter_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_eum_logs: Data: 7.52MB + Index: 0.00MB + Engine InnoDB
wp_forums: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_forums_posts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_forums_topics: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_fv_player_emails: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_fv_player_encoding_jobs: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_fv_player_playermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_fv_player_players: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_fv_player_stats: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_fv_player_videometa: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_fv_player_videos: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gglcptch_allowlist: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_h5p_contents: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_h5p_contents_libraries: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_h5p_contents_tags: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_h5p_contents_user_data: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_h5p_counters: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_h5p_events: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_h5p_libraries: Data: 1.52MB + Index: 0.03MB + Engine InnoDB
wp_h5p_libraries_cachedassets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_h5p_libraries_hub_cache: Data: 0.11MB + Index: 0.02MB + Engine InnoDB
wp_h5p_libraries_languages: Data: 4.52MB + Index: 0.00MB + Engine InnoDB
wp_h5p_libraries_libraries: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_h5p_results: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_h5p_tags: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_h5p_tmpfiles: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_itsec_lockouts: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_itsec_log: Data: 3.52MB + Index: 0.09MB + Engine InnoDB
wp_itsec_temp: Data: 0.05MB + Index: 0.06MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mepr_events: Data: 7.52MB + Index: 14.58MB + Engine InnoDB
wp_mepr_jobs: Data: 0.02MB + Index: 0.14MB + Engine InnoDB
wp_mepr_members: Data: 1.52MB + Index: 2.27MB + Engine InnoDB
wp_mepr_orders: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_mepr_order_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mepr_rule_access_conditions: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mepr_subscriptions: Data: 0.42MB + Index: 1.30MB + Engine InnoDB
wp_mepr_subscription_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mepr_tax_rates: Data: 0.02MB + Index: 0.14MB + Engine InnoDB
wp_mepr_tax_rate_locations: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_mepr_transactions: Data: 3.52MB + Index: 10.19MB + Engine InnoDB
wp_mepr_transactions_backup: Data: 0.02MB + Index: 0.17MB + Engine InnoDB
wp_mepr_transaction_meta: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
wp_moos_oauth_access_tokens: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_moos_oauth_authorization_codes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_moos_oauth_authorized_apps: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_moos_oauth_clients: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_moos_oauth_public_keys: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_moos_oauth_refresh_tokens: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_moos_oauth_scopes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_moos_oauth_users: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_newsletter: Data: 1.52MB + Index: 0.14MB + Engine InnoDB
wp_newsletter_emails: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_newsletter_sent: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_newsletter_stats: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_newsman_an_clicks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_newsman_an_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_newsman_an_sub_details: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_newsman_an_timeline: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_newsman_blocked_domains: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_newsman_emails: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_newsman_email_templates: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
wp_newsman_lists: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_newsman_locks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_newsman_lst_default: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_newsman_lst_wp_users: Data: 0.50MB + Index: 0.14MB + Engine InnoDB
wp_newsman_sentlog: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_newsman_workers: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_oauth_access_tokens: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_oauth_authorization_codes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_oauth_jwt: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_oauth_public_keys: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_oauth_refresh_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_oauth_scopes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_om_leads: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_onclick_show_popup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 7.47MB + Index: 0.36MB + Engine InnoDB
wp_pollsa: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pollsip: Data: 0.13MB + Index: 0.16MB + Engine InnoDB
wp_pollsq: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_popover_ip_cache: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_popularpostsdata: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_popularpostssummary: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_postexpirator_debug: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_postmeta: Data: 11.52MB + Index: 13.03MB + Engine InnoDB
wp_posts: Data: 86.52MB + Index: 1.39MB + Engine InnoDB
wp_ppfuture_actions_args: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_ppress_forms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_ppress_formsmeta: Data: 0.06MB + Index: 0.05MB + Engine InnoDB
wp_ppress_meta_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_sgpb_subscribers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_sgpb_subscription_error_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_sg_fblike_popup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_sg_html_popup: Data: 0.09MB + Index: 0.00MB + Engine InnoDB
wp_sg_image_popup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_sg_popup: Data: 0.13MB + Index: 0.00MB + Engine InnoDB
wp_sg_popup_addons: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_sg_popup_addons_connection: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_sg_popup_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_sg_shortCode_popup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.09MB + Index: 0.06MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 7.52MB + Index: 9.03MB + Engine InnoDB
wp_users: Data: 1.52MB + Index: 0.70MB + Engine InnoDB
wp_wafp_clicks: Data: 0.02MB + Index: 0.14MB + Engine InnoDB
wp_wafp_commissions: Data: 0.02MB + Index: 0.14MB + Engine InnoDB
wp_wafp_links: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wafp_payments: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wafp_responses: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wafp_transactions: Data: 1.52MB + Index: 2.25MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.13MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.08MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.11MB + Index: 0.06MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.17MB + Index: 0.23MB + Engine InnoDB
wp_wc_order_stats: Data: 0.16MB + Index: 0.16MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.06MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_word_replacer: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpmailsmtp_debug_events: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpmailsmtp_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpml_mails: Data: 28.52MB + Index: 0.00MB + Engine InnoDB
wp_wpwhpro_authentication: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_yop_pollmeta: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yop_polls: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_yop_poll_answermeta: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yop_poll_answers: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yop_poll_bans: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yop_poll_custom_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yop_poll_facebook_users: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_yop_poll_logs: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yop_poll_templates: Data: 0.38MB + Index: 0.00MB + Engine InnoDB
wp_yop_poll_voters: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yop_poll_votes_custom_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

amn_om: 3
attachment: 834
calendar: 3
course: 1
courses: 94
cssmenupro: 7
custom_css: 1
customize_changeset: 9
forum: 5
inc_popup: 6
incsub_event: 1
memberpresscoupon: 5
memberpressgroup: 1
memberpressproduct: 3
memberpressrule: 11
mepr-subscriptions: 674
module: 16
module_response: 15
mp-reminder: 1
nav_menu_item: 277
newsman_ap: 7
oembed_cache: 1
optin: 3
option-tree: 1
page: 57
popupbuilder: 59
post: 561
product: 37
product_variation: 243
revision: 3605
seedprod: 1
shop_coupon: 1
shop_order: 1613
shop_order_refund: 55
sld: 1
tablepress_table: 2
text-blocks: 2
unit: 2
vz_custom_forms: 1
wo_client: 2
wp_global_styles: 1
wp_navigation: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (25) ###

Disclaimer: by Andy Mathys – 1.0
Category Posts Widget: by TipTopPress – 4.9.15
Classic Editor: by WordPress Contributors – 1.6.3
MenuMaker Pro: by cssmenumaker – 1.1.3
FV Player: by  – 7.5.41.7212
reCaptcha by BestWebSoft: by BestWebSoft – 1.74
H5P: by Joubel – 1.15.7
Highlight Search Terms: by RavanH – 1.8.2
iDevAffiliate Memberpress Integration: by iDevDirect.com LLC – 2.0
Knight Lab TimelineJS: by Knight Lab – 3.9.3.3
MemberPress Business (Legacy): by Caseproof
LLC – 1.11.24

Popup Builder: by Looking Forward Software Incorporated. – 4.2.6
PublishPress Future: by PublishPress – 3.2.0
Prevent Concurrent Logins: by Frankie Jarrett – 0.4.0
Text Blocks: by Hal Gatewood – 1.5.3
Easy Updates Manager: by Easy Updates Manager Team – 9.0.17
TablePress: by Tobias Bäthge – 2.2.5
Advanced Editor Tools: by Automattic – 5.9.2
User Switching: by John Blackbourn & contributors – 1.7.2
W3 Total Cache: by BoldGrid – 2.6.1
WooCommerce Bulk Discount: by Rene Puchinger – 3.0
WooCommerce: by Automattic – 8.5.2
WP Mail SMTP: by WP Mail SMTP – 3.11.1
WP-Polls: by Lester 'GaMerZ' Chan – 2.77.2
WP Webhooks: by Ironikus – 3.3.2

### Dropin Plugins (3) ###

advanced-cache.php: advanced-cache.php
db.php: db.php
object-cache.php: object-cache.php

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to Woo.com: –
Enforce Approved Product Download Directories: –
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### WC Pages ###

Shop base: #1943 - /shop/
Cart: #1961 - /cart/
Checkout: #1962 - /checkout/
My account: #1963 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: WP-Education
Version: 1.1
Author URL: http://www.vuzzu.net
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ❌ Not declared

### Templates ###

Overrides: wp-education/single-product.php version - is out of date. The core version is 1.6.4
Outdated Templates: ❌
					
					
						Learn how to update

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
product-virtual-downloadable
product-external-affiliate
product-grouped
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: customize-store
minified-js
new-product-management-experience
product-linked
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2024-02-16 17:15:47 -05:00
Options: ✔
Notes: 146
Onboarding: completed

### Action Scheduler ###

Complete: 359
Oldest: 2024-01-15 23:04:21 -0500
Newest: 2024-02-15 22:03:59 -0500

Failed: 739
Oldest: 2019-06-05 16:53:34 -0400
Newest: 2024-01-30 19:48:15 -0500

Pending: 19
Oldest: 2024-02-16 05:45:02 -0500
Newest: 2024-11-21 00:00:00 -0500

### Status report information ###

Generated at: 2024-02-15 22:33:53 -05:00
`

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by tjcafferkey**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

We were previously checking the status set on the shortcode rather than on the product introduced in https://github.com/Automattic/woocommerce/pull/298. We need to check the post_status once we have fetched the product before rendering.

Closes https://github.com/woocommerce/woocommerce/issues/44679

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

**Reproduce the issue:**
1. Install https://wordpress.org/themes/accesspress-lite/
2. Install WC 8.6 or trunk
3. View product pages as logged out user and check they are rendering blank pages

**Test this PR fixes the issue**
1. Install https://wordpress.org/themes/accesspress-lite/
2. Install WC from this PR's branch
3. View product pages as logged out user and check they are rendering product correctly
4. Change status of products and test they are rendering as expected for both logged out and logged in users.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message

Fix product pages rendering blank product details

#### Comment 

</details>

### CODE REVIEW

**Review by Aljullu — APPROVED** [review]
Confirming it fixes the issue and code changes look good to me.

**Comment by snduesel** [comment]
Love you <3 Approved

File: plugins/woocommerce/includes/class-wc-shortcodes.php [hunk 1]
```diff
@@ -575,6 +572,15 @@ public static function product_page( $atts ) {
 
 		$single_product = new WP_Query( $args );
 
+		if (
+			! isset( $force_rendering ) &&
+			$single_product->have_posts() &&
```
Comment (lsinger) [inline plugins/woocommerce/includes/class-wc-shortcodes.php:577]: Shouldn't we be able to leave early if this is false? Right after the query we could add ...

```php
		if ( ! $single_product->have_posts() ) {
			return '';
		}
```

What do you think?

Comment (tjcafferkey) [reply plugins/woocommerce/includes/class-wc-shortcodes.php:577]: I think you might be right but I didn't want to add another condition & early return in to this PR since this wasn't part of this method prior to https://github.com/Automattic/woocommerce/pull/298 anyway.

What do you think about creating this in a separate PR as a follow up? If you think it definitely should be included here then I can go ahead and add it.

Comment (tjcafferkey) [reply plugins/woocommerce/includes/class-wc-shortcodes.php:577]: It will not render anything anyway since this check is also done here I believe https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/includes/class-wc-shortcodes.php#L628-L635

Comment (lsinger) [reply plugins/woocommerce/includes/class-wc-shortcodes.php:577]: Yep, additional PR sounds good. Thanks!

**Review by lsinger — APPROVED** [review]
Looks good to me -- thanks Tom! :shipit:
