### PR TITLE
Stop unslashing password while registering user

### LINKED ISSUE #23922: Special characters in password not working
Hi there, 

I had a customer notice that when he added the single or double quotes characters (' or ") into their password it would be accepted upon registration. However, when they entered the password with those characters it failed to work during login. After he changed his password and removed the ' and " the password would work. 

I've tested those characters in my password and I too have noticed problems with them. It works when I change the password but they don't work when I try logging on. Is there any way you guys could double check this? I've only tested this using single quotes and double quotes in my password and not other special characters.

### PR DESCRIPTION
**Pull request by malviyaritesh**
### Changes proposed in this Pull Request:

After 79ff1b10e password is not being unslashed while logging in but this missed removing `wp_unslash` from password while registering. This causes the mismatch of password if user registered with a password containing quote (`"`).
Fixes #23922.

### How to test the changes in this Pull Request:

1. Make sure Account Creation section of WooCommerce->Settings->Accounts & Privacy, looks like:

image

2. Register a user on "My Account" page with password containing a quote (`"`).
3. Try to login with same credentials (step 2) and you will be logged in successfully without seeing Incorrect Password error.

### Other information:

Without the changes from this PR, the user will see password mismatch error if he registered with password containing a quote (`"`) character. WordPress allows registering user with quote character and successfully logs in.

### Changelog entry

> Fix password mismatch when user registered with password containing a quote (`"`).

### CODE REVIEW

File: includes/class-wc-ajax.php [hunk 1]
```diff
@@ -378,7 +378,7 @@ public static function update_order_review() {
 			array(
 				'result'    => empty( $messages ) ? 'success' : 'failure',
 				'messages'  => $messages,
-				'reload'    => $reload_checkout ? 'true' : 'false',
+				'reload'    => $reload_checkout,
```
Comment (claudiosanches) [inline includes/class-wc-ajax.php]: This change seems unrelated to what this PR propose.

Comment (malviyaritesh) [reply includes/class-wc-ajax.php]: @claudiosanches Yes, you're right. Sorry, I'm new to GitHub and don't know why this commit is showing in this PR. I've created this commit and opened another PR (#23891) to fix issue (#23888). Can you please guide me to resolve this? And let me know what possibly caused this, so in future I don't make same mistake. Thanks.

Comment (claudiosanches) [reply includes/class-wc-ajax.php]: Seems like you included an extra commit in here. You can use https://git-scm.com/docs/git-revert to revert it.

Comment (malviyaritesh) [reply includes/class-wc-ajax.php]: I think I have resolved the issue regarding the extra commit from another branch. I guess, this happened because I forgot to change branch to master before creating new branch while I was still checked out on the other branch for another issue, so it brought commits from that branch too into this. I used `git rebase -i HEAD~3` and removed that extra commit and then force pushed to origin.
I think, now this PR is ready to be merged. :)

**Review by claudiosanches — APPROVED** [review]
Thanks for your help!
