### PR TITLE
Set checkout field value with defined default

### LINKED ISSUE #950: Payment Request provide defaults to pass checkout validation
#### What I expected

I have a plugin that makes use of the filter `woocommerce_checkout_fields` that adds in an additional dropdown field:

```
$fields['billing']['foo'] = array(
        'type' => 'select',
        'input_class' => array('input-text',),
        'required' => true,
        'label' => __('Error message'),
        'options' => $optionsArray
    );

```

When using the Payment Request button via cart page (I have disabled for products), I was expecting the ability to provide default values to my custom field as I _believe_ Payment Requests do not currently support extra custom fields.

Questions:

- Am I right in my knowledge that custom fields on payment requests are not currently supported?
- Is there a preferred work around for adding required custom fields?

#### What happened instead

When an Apple Pay request was made the process resulted in an error message stating that  the required field was not completed.

#### Steps to reproduce the issue

Add extra field using a method below via plugin/functions

```
<?php

add_filter('woocommerce_checkout_fields', 'add_foo_to_checkout');
function add_foo_to_checkout($fields)
{
    $optionsArray = array();
    $optionsArray['bar'] = "bar";


    $fields['billing']['foo'] = array(
        'type' => 'select',
        'input_class' => array('input-text',),
        'required' => true,
        'label' => __('Foo'),
        'options' => $optionsArray
    );

    return $fields;
}

?>
```

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

### LINKED ISSUE #29746: Use defined default value for custom checkout fields on the Cart page
**Prerequisites**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Description**
This issue was actually first reported on `woocommerce-gateway-stripe` I didn't find a way to fix it within the scope of `woocommerce-gateway-stripe` so I'm reporting it here. I'll submit a PR right after with a fix for it.

The issue happens when a custom Shipping/Billing field via `woocommerce_checkout_fields` filter. The default value is not considered when using the Payment Request button on the **Cart page**.

On the "Cart" page, no form displayed to the user. There's no way to enter or change the value of the custom input. On this case, the `default` value (if defined) should be used instead.

**Expected behavior**

If custom field is "required" and a "default" value is passed it should not make the checkout process to fail. The custom field should have the default value.

**Actual behavior**

Field is stopping the checkout process and returns an error. 

Screen Shot 2021-04-23 at 12 53 23 AM

**Steps to reproduce the bug**

To be able to reproduce the bug we should enable the Payment Request button first. I've enabled it using the `woocommerce-gateway-stripe` plugin. Make sure you are on "dev mode" (If there's another easy way use it. The important thing is to be able to purchase using that button on the Cart page).

Add a payment method to Chrome or Add a card to the Wallet app in your iPhone/Mac. You should be able to see either of these two buttons depending if you are using Chrome or Safari.

Screen Shot 2021-04-23 at 1 08 41 AM

Screen Shot 2021-04-23 at 1 09 02 AM

Then add the following code to add the custom field. For testing purposes we can put it on the current theme's functions.php

```php
add_filter('woocommerce_checkout_fields', 'add_foo_field');

function add_foo_field($fields) {
	$fields['billing']['foo'] = array(
	    'type' => 'text',
	    'required' => true,
	    'label' => __('Foo'),
	    'default' => 'default foo value'
	);

	return $fields;
}
```

Steps to reproduce the bug:

1. Create a product.
2. Add product to cart
3. Go to Cart page
4. Click "Buy now"/ "Buy with Pay"  button
5. Purchase the product using valid card details. You can use [Stripe's test card](https://stripe.com/docs/testing)
6. You will not be able to complete the transaction. An error message will be displayed indicating "Billing Foo is a required field". 

**Isolating the problem:**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>

```

### WordPress Environment ###

WordPress address (URL): http://one.wordpress.test
Site address (URL): http://one.wordpress.test
WC Version: 5.3.0
REST API Version: ✔ 5.3.0
WC Blocks Version: ✔ 4.9.1
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 2.2.1
Log Directory Writable: ✔
WP Version: 5.7.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.19.10
PHP Version: 7.4.16
PHP Post Max Size: 1 GB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.58.0
OpenSSL/1.1.1

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.4.18-MariaDB-1:10.4.18+maria~bionic
Max Upload Size: 1 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 5.3.0
WC Database Prefix: wp_
Total Database Size: 3.83MB
Database Data Size: 2.34MB
Database Index Size: 1.49MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 1.50MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_posts: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 2
page: 6
post: 2
product: 4
shop_order: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (2) ###

WooCommerce Stripe Gateway: by WooCommerce – 5.1.0
WooCommerce: by Automattic – 5.3.0-dev

### Inactive Plugins (0) ###


### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: 
Decimal Separator: .
Number of Decimals: 0
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #6 - /shop/
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 3.5.1
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 4
Oldest: 2021-04-22 20:09:49 +0000
Newest: 2021-04-23 04:57:34 +0000


### Status report information ###

Generated at: 2021-04-23 06:17:20 +00:00

```

</details>

### PR DESCRIPTION
**Pull request by asumaran**
### All Submissions:
* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:
Fixes https://github.com/woocommerce/woocommerce/issues/29746 and Fixes https://github.com/woocommerce/woocommerce-gateway-stripe/issues/950 

The changes proposed in this PR affects mainly the Cart and Product Pages because the Payment Request button can be used to purchase without filling out check out details:

1. Pre-assigns the "default" value to every checkout field if defined. Otherwise the corresponding value via $_POST will be used.
2. We are keeping the previous default value if no "default" value for the checkout field is defined to keep things as before.

### How to test the changes in this Pull Request:

Here's a script to add all supported fields in `WC_Checkout->get_posted_data()`. We can put this on the current theme's `functions.php`

<details>
<summary>code to add checkout fields</summary>

```php
add_filter('woocommerce_checkout_fields', 'add_foo_fields');

function add_foo_fields($fields) {

	// billing
	$fields['billing']['billing_no_type'] = array(
		'required' => true,
		'label' => 'billing_no_type',
		'default' => 'no_type default value'
	);

	$fields['billing']['billing_checkbox'] = array(
		'type' => 'checkbox',
		'required' => true,
		'label' => 'billing_checkbox',
		'default' => '1'
	);

	// This is ignored because `woocommerce_form_field()` doesn't support this input type
	$fields['billing']['billing_multiselect'] = array(
		'type' => 'multiselect',
		'required' => true,
		'label' => 'billing_multiselect',
		'default' => 'billing_multiselect_default_value',
		'options' => array('foo' => 'foo_label', 'billing_multiselect_default_value' => 'billing_multiselect_default_value_label'),
	);

	$fields['billing']['billing_select'] = array(
		'type' => 'select',
		'required' => true,
		'label' => 'billing_select',
		'default' => 'billing_select_default_value',
		'options' => array('foo' => 'foo_label', 'billing_select_default_value' => 'billing_select_default_value_label'),
	);

	$fields['billing']['billing_textarea'] = array(
		'type' => 'textarea',
		'required' => true,
		'label' => 'billing_textarea',
		'default' => 'billing_textarea default_value',
	);

	$fields['billing']['billing_password'] = array(
		'type' => 'password',
		'required' => true,
		'label' => 'billing_password',
		'default' => 'billing_password default_value',
	);

	$fields['billing']['billing_radio'] = array(
		'type' => 'radio',
		'required' => true,
		'label' => 'billing_radio',
		'default' => 'billing_radio_default_value',
		'options' => array('foo' => 'foo_label', 'billing_radio_default_value' => 'billing_radio_default_value_label'),
	);

	$fields['billing']['billing_hidden'] = array(
		'type' => 'hidden',
		'required' => true,
		'label' => 'billing_hidden',
		'default' => 'billing_hidden default_value',
	);

	// shipping
	$fields['shipping']['shipping_no_type'] = array(
		'required' => true,
		'label' => 'billing_no_type',
		'default' => 'no_type default value'
	);

	$fields['shipping']['shipping_checkbox'] = array(
		'type' => 'checkbox',
		'required' => true,
		'label' => 'shipping_checkbox',
		'default' => '1'
	);

	// This is ignored because `woocommerce_form_field()` doesn't support this input type
	$fields['shipping']['shipping_multiselect'] = array(
		'type' => 'multiselect',
		'required' => true,
		'label' => 'shipping_multiselect',
		'default' => 'shipping_multiselect_default_value',
		'options' => array('foo' => 'foo_label', 'shipping_multiselect_default_value' => 'shipping_multiselect_default_value_label'),
	);

	$fields['shipping']['shipping_select'] = array(
		'type' => 'select',
		'required' => true,
		'label' => 'shipping_select',
		'default' => 'shipping_select_default_value',
		'options' => array('foo' => 'foo_label', 'shipping_select_default_value' => 'shipping_select_default_value_label'),
	);

	$fields['shipping']['shipping_textarea'] = array(
		'type' => 'textarea',
		'required' => true,
		'label' => 'shipping_textarea',
		'default' => 'shipping_textarea default_value',
	);

	$fields['shipping']['shipping_password'] = array(
		'type' => 'password',
		'required' => true,
		'label' => 'shipping_password',
		'default' => 'shipping_password default_value',
	);

	$fields['shipping']['shipping_radio'] = array(
		'type' => 'radio',
		'required' => true,
		'label' => 'shipping_radio',
		'default' => 'shipping_radio_default_value',
		'options' => array('foo' => 'foo_label', 'shipping_radio_default_value' => 'shipping_radio_default_value_label'),
	);

	$fields['shipping']['shipping_hidden'] = array(
		'type' => 'hidden',
		'required' => true,
		'label' => 'shipping_hidden',
		'default' => 'shipping_hidden default_value',
	);

	return $fields;
}
```

</details>

1. Use the code above to add checkout fields.
2. Add a product to the cart.
3. Purchase using the checkout page. In my case I'm using `woocommerce-gateway-stripe`. So I'm using a test credit card.
4. Fill out missing required information and submit the checkout form.
5. Then we can confirm the fields are being saved with the default value.

<details>
<summary>post meta for newly created order</summary>

```
MariaDB [wordpress-one]> SELECT * FROM `wp_postmeta` WHERE `post_id` = 45 AND (`meta_key` LIKE '_billing_%' OR `meta_key` LIKE '_shipping_%') ORDER BY meta_key;
+---------+---------+-------------------------+---------------------------------------------------------------------------------------------------------------+
| meta_id | post_id | meta_key                | meta_value                                                                                                    |
+---------+---------+-------------------------+---------------------------------------------------------------------------------------------------------------+
|    1875 |      45 | _billing_address_1      | 55 Music Concourse Dr                                                                                         |
|    1898 |      45 | _billing_address_index  | Alfredo Sumaran  55 Music Concourse Dr  San Francisco CA 94118 US alfredo.sumaran@automattic.com +14153798000 |
|    1904 |      45 | _billing_checkbox       | 1                                                                                                             |
|    1876 |      45 | _billing_city           | San Francisco                                                                                                 |
|    1879 |      45 | _billing_country        | US                                                                                                            |
|    1880 |      45 | _billing_email          | alfredo.sumaran@automattic.com                                                                                |
|    1873 |      45 | _billing_first_name     | Alfredo                                                                                                       |
|    1906 |      45 | _billing_hidden         | billing_hidden default_value                                                                                  |
|    1874 |      45 | _billing_last_name      | Sumaran                                                                                                       |
|    1905 |      45 | _billing_no_type        | no_type default value                                                                                         |
|    1902 |      45 | _billing_password       | billing_password default_value                                                                                |
|    1881 |      45 | _billing_phone          | +14153798000                                                                                                  |
|    1878 |      45 | _billing_postcode       | 94118                                                                                                         |
|    1901 |      45 | _billing_radio          | billing_radio_default_value                                                                                   |
|    1900 |      45 | _billing_select         | billing_select_default_value                                                                                  |
|    1877 |      45 | _billing_state          | CA                                                                                                            |
|    1903 |      45 | _billing_textarea       | billing_textarea default_value                                                                                |
|    1884 |      45 | _shipping_address_1     | 55 Music Concourse Dr                                                                                         |
|    1899 |      45 | _shipping_address_index | Alfredo Sumaran  55 Music Concourse Dr  San Francisco CA 94118 US                                             |
|    1911 |      45 | _shipping_checkbox      | 1                                                                                                             |
|    1885 |      45 | _shipping_city          | San Francisco                                                                                                 |
|    1888 |      45 | _shipping_country       | US                                                                                                            |
|    1882 |      45 | _shipping_first_name    | Alfredo                                                                                                       |
|    1913 |      45 | _shipping_hidden        | shipping_hidden default_value                                                                                 |
|    1883 |      45 | _shipping_last_name     | Sumaran                                                                                                       |
|    1912 |      45 | _shipping_no_type       | no_type default value                                                                                         |
|    1909 |      45 | _shipping_password      | shipping_password default_value                                                                               |
|    1887 |      45 | _shipping_postcode      | 94118                                                                                                         |
|    1908 |      45 | _shipping_radio         | shipping_radio_default_value                                                                                  |
|    1910 |      45 | _shipping_select        | shipping_select_default_value                                                                                 |
|    1886 |      45 | _shipping_state         | CA                                                                                                            |
|    1907 |      45 | _shipping_textarea      | shipping_textarea default_value                                                                               |
+---------+---------+-------------------------+---------------------------------------------------------------------------------------------------------------+
32 rows in set (0.001 sec)
```

</details>

6. Add a product to the cart
7. Purchase using the Payment Request button in the "Cart" page. For this I'm using the `woocommerce-gateway-plugin` in test mode.
8. No error should be displayed and the payment should be done successfully.
9. Then we can confirm the fields are being saved with the default value.

<details>
<summary>post meta for newly created order using Payment Request button</summary>

```
MariaDB [wordpress-one]> SELECT * FROM `wp_postmeta` WHERE `post_id` = 46 AND (`meta_key` LIKE '_billing_%' OR `meta_key` LIKE '_shipping_%') ORDER BY meta_key;
+---------+---------+-------------------------+---------------------------------------------------------------------------------------------------------------+
| meta_id | post_id | meta_key                | meta_value                                                                                                    |
+---------+---------+-------------------------+---------------------------------------------------------------------------------------------------------------+
|    1940 |      46 | _billing_address_1      | 55 Music Concourse Dr                                                                                         |
|    1963 |      46 | _billing_address_index  | Alfredo Sumaran  55 Music Concourse Dr  San Francisco CA 94118 US alfredo.sumaran@automattic.com +14153798000 |
|    1969 |      46 | _billing_checkbox       | 1                                                                                                             |
|    1941 |      46 | _billing_city           | San Francisco                                                                                                 |
|    1944 |      46 | _billing_country        | US                                                                                                            |
|    1945 |      46 | _billing_email          | alfredo.sumaran@automattic.com                                                                                |
|    1938 |      46 | _billing_first_name     | Alfredo                                                                                                       |
|    1971 |      46 | _billing_hidden         | billing_hidden default_value                                                                                  |
|    1939 |      46 | _billing_last_name      | Sumaran                                                                                                       |
|    1970 |      46 | _billing_no_type        | no_type default value                                                                                         |
|    1967 |      46 | _billing_password       | billing_password default_value                                                                                |
|    1946 |      46 | _billing_phone          | +14153798000                                                                                                  |
|    1943 |      46 | _billing_postcode       | 94118                                                                                                         |
|    1966 |      46 | _billing_radio          | billing_radio_default_value                                                                                   |
|    1965 |      46 | _billing_select         | billing_select_default_value                                                                                  |
|    1942 |      46 | _billing_state          | CA                                                                                                            |
|    1968 |      46 | _billing_textarea       | billing_textarea default_value                                                                                |
|    1949 |      46 | _shipping_address_1     | 55 Music Concourse Dr                                                                                         |
|    1964 |      46 | _shipping_address_index | Alfredo Sumaran  55 Music Concourse Dr  San Francisco CA 94118 US                                             |
|    1976 |      46 | _shipping_checkbox      | 1                                                                                                             |
|    1950 |      46 | _shipping_city          | San Francisco                                                                                                 |
|    1953 |      46 | _shipping_country       | US                                                                                                            |
|    1947 |      46 | _shipping_first_name    | Alfredo                                                                                                       |
|    1978 |      46 | _shipping_hidden        | shipping_hidden default_value                                                                                 |
|    1948 |      46 | _shipping_last_name     | Sumaran                                                                                                       |
|    1977 |      46 | _shipping_no_type       | no_type default value                                                                                         |
|    1974 |      46 | _shipping_password      | shipping_password default_value                                                                               |
|    1952 |      46 | _shipping_postcode      | 94118                                                                                                         |
|    1973 |      46 | _shipping_radio         | shipping_radio_default_value                                                                                  |
|    1975 |      46 | _shipping_select        | shipping_select_default_value                                                                                 |
|    1951 |      46 | _shipping_state         | CA                                                                                                            |
|    1972 |      46 | _shipping_textarea      | shipping_textarea default_value                                                                               |
+---------+---------+-------------------------+---------------------------------------------------------------------------------------------------------------+
32 rows in set (0.001 sec)
```

</details>

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully run tests with your changes locally?

### Changelog entry

- Set checkout fields value with the default defined value where form is not presented to the user.

### CODE REVIEW

**Comment by asumaran** [comment]
FYI. Build is failing for unrelated issues to this PR.

**Comment by asumaran** [comment]
FYI. Build is failing for causes unrelated  to this PR.

**Comment by Konamiman** [comment]
Hi @asumaran, there are code sniffer errors, could you please fix them?

**Comment by asumaran** [comment]
@Konamiman I've fixed the existing code sniff issue. It was just that old syntax to ignore a line is [not longer supported](https://github.com/squizlabs/PHP_CodeSniffer/wiki/Advanced-Usage#ignoring-parts-of-a-file).

File: includes/class-wc-checkout.php [hunk 1]
```diff
@@ -686,27 +686,32 @@ public function get_posted_data() {
...
+				} elseif ( isset( $field['default'] ) ) {
+					$value = $field['default'];
+				} else {
+					$value = '';
+				}
+
 				$type = sanitize_title( isset( $field['type'] ) ? $field['type'] : 'text' );
 
-				// phpcs:disable WordPress.Security.NonceVerification.Missing
 				switch ( $type ) {
```
Comment (Konamiman) [inline includes/class-wc-checkout.php:699]: There's a problem here: this `switch` statement is executed always, but it should execute only when there's no value set. Imagine for example a checkbox that defaults to 0 and is left unchecked, with the current code it will be stored as a 1.

To really mimic the previous logic the `switch` should be executed only when there's no value set:

```php
if('' !== $value) {
  switch(...) {...}
}
```

**Review by Konamiman — CHANGES_REQUESTED** [review]

File: includes/class-wc-checkout.php (hunk 1 above)
Comment (asumaran) [reply includes/class-wc-checkout.php]: Goot catch. done!  42bc356

Comment (asumaran) [reply includes/class-wc-checkout.php]:
```php
$value = 0 === $value || "0" === $value || false === $value ? '' : 1;
```
Adding that line in that place will cause if we add a non-required input with `'foo'` as default value it will saved as `"1"` even if the input was left unchecked since we are not checking for `"foo"` or any other other values.

[Looking](https://github.com/woocommerce/woocommerce/blob/f8340f80cbd9365ba5f4bb69a3fe5680e7a767b3/includes/wc-template-functions.php#L2807) [at](https://github.com/WordPress/WordPress/blob/2e762721b1e0cb634b85b315f58c82bf8f42e1b5/wp-includes/general-template.php#L4753-L4755) [the code](https://github.com/WordPress/WordPress/blob/2e762721b1e0cb634b85b315f58c82bf8f42e1b5/wp-includes/general-template.php#L4819-L4820) it seems the only way to mark a checkbox in the UI is to use a value that translates to `"1"` after string conversion. So I think it's better if we use the same logic here.

```php
$value = (string) $value === "1" ? 1 : '';
```

There was a small issue I've found though. When I added an optional checkbox with `"1"` as default value. It was saved even though the user unchecked the input. It made sense because the script didn't know if the user unchecked the input or it was never not presented to the user taking its default value instead. That's why I moved the line to the top and also added a conditional to know if the user was presented with the checkout form. 

I've tested my changes with many cases and can confirm that:

#### When UI is presented to the user (checkout page).
- [x] Checked inputs are saved as "1" no matter its default value or if they are required or optional.
- [x] Optional inputs are not saved if not checked on submit
- [x] Optional inputs are saved as "1" if marked on submit

#### When UI is not presented to the user (product page)
  - [x] Required inputs are saved as "1" if it has a default value that translates to "1"
  - [x] Optional inputs are saved as "1" if it has a default value that translates to "1" 
  - [x] Error message is displayed for required inputs with a default value that does not translate to "1"
  - [x] Optional inputs are not saved regardless if they have a default value or not.

<details>

```php
$fields['billing']['billing_checkbox11'] = array(
  'type' => 'checkbox',
  'required' => true,
  'label' => 'billing_checkbox11',
  'default' => '1'
);
$fields['billing']['billing_checkbox12'] = array(
  'type' => 'checkbox',
  'required' => true,
  'label' => 'billing_checkbox12',
  'default' => true
);
$fields['billing']['billing_checkbox13'] = array(
  'type' => 'checkbox',
  'required' => true,
  'label' => 'billing_checkbox13',
  'default' => 1
);
$fields['billing']['billing_checkbox14'] = array(
  'type' => 'checkbox',
  'required' => true,
  'label' => 'billing_checkbox14',
  'default' => '0'
);
$fields['billing']['billing_checkbox15'] = array(
  'type' => 'checkbox',
  'required' => true,
  'label' => 'billing_checkbox15',
  'default' => 0
);
$fields['billing']['billing_checkbox16'] = array(
  'type' => 'checkbox',
  'required' => true,
  'label' => 'billing_checkbox16',
  'default' => ''
);
$fields['billing']['billing_checkbox17'] = array(
  'type' => 'checkbox',
  'required' => true,
  'label' => 'billing_checkbox17',
  'default' => ' '
);
$fields['billing']['billing_checkbox18'] = array(
  'type' => 'checkbox',
  'required' => true,
  'label' => 'billing_checkbox18',
  'default' => 'foo'
);
$fields['billing']['billing_checkbox19'] = array(
  'type' => 'checkbox',
  'label' => 'billing_checkbox19',
  'default' => 'foo'
);
$fields['billing']['billing_checkbox20'] = array(
  'type' => 'checkbox',
  'label' => 'billing_checkbox20',
  'default' => '1'
);
```

</details>

---

```php
$is_checkout_page = isset( $_REQUEST['woocommerce-process-checkout-nonce'] );
```

This is probably not the best way to identify if the request came from the checkout page and/or the user was presented with the checkout form. Please let me know if is there a better way to know that.

Comment (Konamiman) [reply includes/class-wc-checkout.php]: I think that what we need is simply to exclude checkboxes from the default mechanism:

```php
if ( isset( $_POST[ $key ] ) && '' !== $_POST[ $key ] ) {
	$value = wp_unslash($_POST[$key]);
} elseif ( isset( $field['default'] ) && 'checkbox' !== $type ) {
	$value = $field['default'];
} else {
	$value = '';
}
```

This way it will work whether the default is checked or unchecked and whether the user changes the value or not.

"But what about mandatory checkboxes that are unchecked by default?", you may ask. We'll, consider what's the purpose of such a checkbox: it's usually to have the user agree on some terms and conditions. It doesn't make sense to add such a confirmation field in scenarios where the user doesn't have an opportunity to explicitly make a choice.

Additionally, you'll see the first line of my suggestion is `if ( isset( $_POST[ $key ] ) && '' !== $_POST[ $key ] )`. I have added the comparison against an empty string because otherwise, an empty text field will cause `isset( $_POST[ $key ] )` to be true (the key is set and has a value of `''`), but semantically that's an unset field and thus the default should be used.

Does that make sense?

Comment (asumaran) [reply includes/class-wc-checkout.php]: @Konamiman Yeah, I think it makes sense. I've tested it and it's working as expected

Comment (asumaran) [reply includes/class-wc-checkout.php]: Also do I need to add an entry to the `changelog.txt`? Where do I put it?

Comment (Konamiman) [reply includes/class-wc-checkout.php]: No, you should just place an appropriate one-line summary under "Changelog entry" in the pull request description, we handle `changelog.txt` entries ourselves at the time of preparing a new release.

**Comment by Konamiman** [comment]
I'm asking a second review from my team as this seems a somewhat risky change.

**Comment by asumaran** [comment]
@Konamiman I also think this PR introduces considerable changes and would be safer if other people gives a look at this PR before merge. I'll wait for any other feedback or what they decide to proceed with this PR.

File: includes/class-wc-checkout.php [hunk 2]
```diff
@@ -685,28 +685,37 @@ public function get_posted_data() {
 				continue;
 			}
 
+			$is_checkout_page = isset( $_REQUEST['woocommerce-process-checkout-nonce'] );
```
Comment (barryhughes) [inline includes/class-wc-checkout.php:688]: It doesn't look like we use `$is_checkout_page`, can this line be removed?

File: includes/class-wc-checkout.php [hunk 3]
```diff
@@ -685,28 +685,37 @@ public function get_posted_data() {
...
-					case 'textarea':
-						$value = isset( $_POST[ $key ] ) ? wc_sanitize_textarea( wp_unslash( $_POST[ $key ] ) ) : '';
-						break;
-					case 'password':
-						$value = isset( $_POST[ $key ] ) ? wp_unslash( $_POST[ $key ] ) : ''; // phpcs:ignore WordPress.Security.ValidatedSanitizedInput.InputNotSanitized
-						break;
-					default:
-						$value = isset( $_POST[ $key ] ) ? wc_clean( wp_unslash( $_POST[ $key ] ) ) : '';
-						break;
+				if ( isset( $_POST[ $key ] ) && '' !== $_POST[ $key ] ) { // phpcs:disable WordPress.Security.NonceVerification.Missing
```
Comment (barryhughes) [inline includes/class-wc-checkout.php:693]: I think we should consider the case where we have a **non-required** text field set to an empty string. For instance, consider a custom field defined something like this:

```php
add_filter( 'woocommerce_checkout_fields', function ( $fields ) {
	$fields['billing']['custom_text'] = [
		'type'     => 'text',
		'required' => false,
		'label'    => 'custom text field',
		'default'  => 'this is the default',
	];

	return $fields;
} );
```

If a customer proceeds to checkout they will see the field and it will be pre-populated with the default text. However, it's not _required_ and they may therefore choose to delete it.

* Currently [(trunk@5493218)](https://github.com/woocommerce/woocommerce/commit/5493218870b1234162e20b59f02caf5f4d33c277) if the customer chooses to wipe this field, that's fine.
* With this change in place, however, we effectively set it back to the default any time the submitted value is an empty string.

I think the current logic probably makes sense when we're dealing with required fields, but for non-required fields it will potentially cause breakages with existing third party and custom solutions.

**Review by barryhughes — CHANGES_REQUESTED** [review]

File: includes/class-wc-checkout.php (hunk 3 above)
Comment (asumaran) [reply includes/class-wc-checkout.php:693]: > ...we should consider the case where we have a non-required text field set to an empty string...

> ...If a customer proceeds to checkout they will see the field and it will be pre-populated with the default text. However, it's not required and they may therefore choose to delete it.

I think the case you mention it's the same case I mentioned in my comment above but with text inputs https://github.com/woocommerce/woocommerce/pull/29820#discussion_r630648672 

>There was a small issue I've found though. When I added an optional checkbox with "1" as default value. It was saved even though the user unchecked the input. It made sense because the script didn't know if the user unchecked the input or it was never not presented to the user taking its default value instead. 

The suggested solution was to skip checkboxes from the default mechanism. But here I guess we should save the text input as empty string. In that case I'll need the `$is_checkout_page` I created to know if the user was presented with the form or not. Does that sound good to you @barryhughes?

Comment (asumaran) [reply includes/class-wc-checkout.php:693]: @barryhughes I've tested my last commit 79db2d9 and here's the results. I used the following code.

```js
add_filter( 'woocommerce_checkout_fields', function ( $fields ) {
  $fields['billing']['billing_custom_text'] = [
    'type'     => 'text',
    'required' => false,
    'label'    => 'custom text field',
    'default'  => 'this is the default',
  ];

  return $fields;
} );
```

- Case 1. Checkout page, No changes to input.

```
MariaDB [wordpress-one]> SELECT * FROM `wp_postmeta` WHERE `post_id` = 96 AND `meta_key` = '_billing_custom_text' ORDER BY meta_key;
+---------+---------+----------------------+---------------------+
| meta_id | post_id | meta_key             | meta_value          |
+---------+---------+----------------------+---------------------+
|    4880 |      96 | _billing_custom_text | this is the default |
+---------+---------+----------------------+---------------------+
1 row in set (0.000 sec)
```

- Case 2. Checkout page, Input value was changed to "foo"


```
MariaDB [wordpress-one]> SELECT * FROM `wp_postmeta` WHERE `post_id` = 97 AND `meta_key` = '_billing_custom_text' ORDER BY meta_key;
+---------+---------+----------------------+------------+
| meta_id | post_id | meta_key             | meta_value |
+---------+---------+----------------------+------------+
|    4932 |      97 | _billing_custom_text | foo        |
+---------+---------+----------------------+------------+
```

- Case 3. Checkout page, Input value changed to empty string ("")

```
MariaDB [wordpress-one]> SELECT * FROM `wp_postmeta` WHERE `post_id` = 99 AND `meta_key` = '_billing_custom_text' ORDER BY meta_key;
+---------+---------+----------------------+------------+
| meta_id | post_id | meta_key             | meta_value |
+---------+---------+----------------------+------------+
|    5036 |      99 | _billing_custom_text |            |
+---------+---------+----------------------+------------+
1 row in set (0.000 sec)
```


- Case 4. Product page, purchase using Payment Request button


```
MariaDB [wordpress-one]> SELECT * FROM `wp_postmeta` WHERE `post_id` = 98 AND `meta_key` = '_billing_custom_text' ORDER BY meta_key;
+---------+---------+----------------------+---------------------+
| meta_id | post_id | meta_key             | meta_value          |
+---------+---------+----------------------+---------------------+
|    4984 |      98 | _billing_custom_text | this is the default |
+---------+---------+----------------------+---------------------+
1 row in set (0.000 sec)
```

For the case where the input is required, the same behavior is applied except Case 3 is not possible because validation responds with an error message.

File: includes/class-wc-checkout.php [hunk 4]
```diff
@@ -685,28 +685,37 @@ public function get_posted_data() {
 				continue;
 			}
 
+			$form_was_shown = isset( $_REQUEST['woocommerce-process-checkout-nonce'] );
```
Comment (barryhughes) [inline includes/class-wc-checkout.php:688]: Minor things: we could move outside of the foreach loop (no need to evaluate each iteration) and given the context we could be specific about the source (switch to `$_POST`).

File: includes/class-wc-checkout.php (hunk 3 above)
Comment (barryhughes) [reply includes/class-wc-checkout.php:693]: OK, I think this is good (also seems to work with [Express Checkout](https://woocommerce.com/products/express-checkout-for-woocommerce/) and [One Page Checkout](https://docs.woocommerce.com/document/woocommerce-one-page-checkout/) (I wanted to check those out, as I was curious about compatibility with add-ons). @Konamiman — any other thoughts on this from your end?

File: includes/class-wc-checkout.php (hunk 4 above)
Comment (asumaran) [reply includes/class-wc-checkout.php]: done f20e8ab

**Review by barryhughes — APPROVED** [review]
LGTM (but note we need sign-off from both reviewers)

File: includes/class-wc-checkout.php (hunk 3 above)
Comment (Konamiman) [reply includes/class-wc-checkout.php:693]: Nope, I think this behavior is good to go.

**Review by Konamiman — APPROVED** [review]
