### PR TITLE
Prevent prefilling of the billing address with the shipping address in the Checkout block for the Guest Shopper

### LINKED ISSUE #42140: Billing address prefilled with the shipping address once shown in the checkout
## Describe the bug

If I have shipping address filled with some data and then decide to use a different one for the billing (via checkbox), I see billing already prefilled with shipping address. We should have billing address empty in this case.

## To reproduce

1. As a guest go and add some item to the cart
2. Proceed to the checkout
3. Fill shipping address with any data
4. Click checkbox to use a different address for the billing
5. Observe issue

## Expected behavior

Empty field for the billing address

## Screenshots

GIF: https://d.pr/i/F1QCUg

## Additional context

Discussed on Slack: slack/C02TS23QJ1X/p1699025951440299

### PR DESCRIPTION
**Pull request by tarunvijwani**
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

This PR adds a new enhancement to the Checkout Block. It prevents the billing address from automatically filling in with the shipping address for the guest shopper.  

Closes #42140.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1.  Open the site in a private/incognito browser window.
2. Add a product to the Cart.
3. Visit the Checkout Block page.
4. Fill out the shipping address.
5. Uncheck the Use same address for billing checkbox.
6. Confirm that the billing address form is empty.
7. Confirm State and Country is pre-filled. 

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [x] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [x] Enhancement - Improvement to existing functionality

#### Message 
Prevent prefilling of the billing address with the shipping address in the Checkout block for the Guest Shopper. 

#### Comment 

</details>

### CODE REVIEW

File: plugins/woocommerce-blocks/assets/js/base/utils/address.ts [hunk 1]
```diff
@@ -105,6 +105,32 @@ export const emptyHiddenAddressFields = <
...
+	const addressForm = prepareFormFields(
+		ADDRESS_FORM_KEYS,
+		{},
+		address.country
+	);
+	const newAddress = Object.assign( {}, address ) as T;
+
+	addressForm.forEach( ( { key = '' } ) => {
+		if ( isValidAddressKey( key, address ) ) {
+			newAddress[ key ] = '';
```
Comment (wavvves) [inline plugins/woocommerce-blocks/assets/js/base/utils/address.ts:133]: Will this successfully reset all type of [form elements](https://www.w3schools.com/html/html_form_elements.asp) and element types?

File: plugins/woocommerce-blocks/tests/e2e/tests/checkout/checkout-block.shopper.block_theme.side_effects.spec.ts [hunk 2]
```diff
@@ -474,3 +474,37 @@ test.describe( 'Checkout Form Errors', () => {
 		).toBeVisible();
 	} );
 } );
+
+test.describe( 'Billing Address Form', () => {
+	test.use( { storageState: guestFile } );
+	const shippingTestData = {
```
Comment (wavvves) [inline plugins/woocommerce-blocks/tests/e2e/tests/checkout/checkout-block.shopper.block_theme.side_effects.spec.ts:508]: As discussed over the huddle, we could make this an array of addresses to test multiple edge cases and make it more robust 👍🏼

File: plugins/woocommerce-blocks/tests/e2e/tests/checkout/checkout-block.shopper.block_theme.side_effects.spec.ts [hunk 3]
```diff
@@ -474,3 +474,37 @@ test.describe( 'Checkout Form Errors', () => {
...
+		frontendUtils,
+		page,
+		checkoutPageObject,
+	} ) => {
+		await frontendUtils.goToShop();
+		await frontendUtils.addToCart( SIMPLE_PHYSICAL_PRODUCT_NAME );
+		await frontendUtils.goToCheckout();
+		await checkoutPageObject.fillShippingDetails( shippingTestData );
+		await page.getByLabel( 'Use same address for billing' ).uncheck();
+		await expect( page.locator( '#billing-first_name' ) ).toHaveValue( '' );
```
Comment (wavvves) [inline plugins/woocommerce-blocks/tests/e2e/tests/checkout/checkout-block.shopper.block_theme.side_effects.spec.ts]: We set 10 values but are only checking for 7. Maybe set a mapping object with selectors, and iterate on that would make this more dynamic and future proof ;)

**Review by wavvves — CHANGES_REQUESTED** [review]
It works out as expected, but I left some feedback on what could be some improvements to it.
Thanks for working on this Tarun, I know you're on a tight schedule, if needed you can handoff the PR to me and I'll tie any loose ends.

File: plugins/woocommerce-blocks/assets/js/base/utils/address.ts (hunk 1 above)
Comment (tarunvijwani) [reply plugins/woocommerce-blocks/assets/js/base/utils/address.ts:133]: Yes, this function will accept all elements because it is based on the address object rather than the form itself. The address object remains independent of the front-end display, whether it is a dropdown, radio button, checkbox, or any other element. It consists of properties in string format.
Type definitions:
 https://github.com/woocommerce/woocommerce/blob/ecae6df49cc7e6241463843e4fa9decd9c31b80d/plugins/woocommerce-blocks/assets/js/types/type-defs/cart-response.ts#L78-L83

https://github.com/woocommerce/woocommerce/blob/ecae6df49cc7e6241463843e4fa9decd9c31b80d/plugins/woocommerce-blocks/assets/js/types/type-defs/cart-response.ts#L30-L38

File: plugins/woocommerce-blocks/tests/e2e/tests/checkout/checkout-block.shopper.block_theme.side_effects.spec.ts (hunk 3 above)
Comment (tarunvijwani) [reply plugins/woocommerce-blocks/tests/e2e/tests/checkout/checkout-block.shopper.block_theme.side_effects.spec.ts]: Fixed it in https://github.com/woocommerce/woocommerce/pull/44347/commits/a2a13150ea43dfe899c1be438ea03d026d7bcd8e

File: plugins/woocommerce-blocks/tests/e2e/tests/checkout/checkout-block.shopper.block_theme.side_effects.spec.ts (hunk 2 above)
Comment (tarunvijwani) [reply plugins/woocommerce-blocks/tests/e2e/tests/checkout/checkout-block.shopper.block_theme.side_effects.spec.ts:508]: @wavvves I appreciate your suggestion to iterate through the fields to ensure that all of them are checked. However, I tried using a loop and encountered a limitation with the field type on the front-end. Specifically, the country and state fields require a `toHaveText` assertion check, which results in conditional assertions that are not recommended by our linters.

I also came to the realization that there is no need for the loop to iterate the fields because they will always be the same as the shipping address fields. Prior to the test, we define the shipping address, so we already know which address fields will be available for the billing address form. I'd love to hear your thoughts about it.

**Review by wavvves — APPROVED** [review]

File: plugins/woocommerce-blocks/tests/e2e/tests/checkout/checkout-block.shopper.block_theme.side_effects.spec.ts [hunk 4]
```diff
@@ -474,3 +474,135 @@ test.describe( 'Checkout Form Errors', () => {
...
+		postcode: '',
+		phone: '',
+	};
+
+	test( 'Ensure billing is empty and shipping address is filled for guest user', async ( {
+		frontendUtils,
+		page,
+		checkoutPageObject,
+	} ) => {
+		await frontendUtils.logout();
```
Comment (WunderBart) [inline plugins/woocommerce-blocks/tests/e2e/tests/checkout/checkout-block.shopper.block_theme.side_effects.spec.ts:538]: 👋 @tarunvijwani, just popping in to let you know that we shouldn't be logging the user out via the UI as it will stay logged out, affecting all the subsequent tests. Instead, let's use the dedicated guest user storage state file like in the test above:

https://github.com/woocommerce/woocommerce/blob/d5bcd7ccd7425eb3d125e0466043d95037a3d5b7/plugins/woocommerce-blocks/tests/e2e/tests/checkout/checkout-block.shopper.block_theme.side_effects.spec.ts#L415-L416

FYI, I am addressing it in https://github.com/woocommerce/woocommerce/pull/45624 as the tests are failing.

Comment (tarunvijwani) [reply plugins/woocommerce-blocks/tests/e2e/tests/checkout/checkout-block.shopper.block_theme.side_effects.spec.ts:538]: @WunderBart Thank you for catching the bug and sharing the solution. TIL. 🙂
